### ISSUE TITLE
[stable/jenkins] please make a documentation about Values.Master.JenkinsAdminEmail

### ISSUE THREAD

**Issue by Hokwang** [helm/charts#10015]
**Which chart**:
stable/jenkins

**What happened**:
https://github.com/helm/charts/blob/master/stable/jenkins/templates/config.yaml
line 180
there's Values.Master.JenkinsAdminEmail
but no documentation and it does not exist in values.yaml

Please improve this.

Thanks,

**Comment by maorfr** [comment]
Hey @Hokwang,

Would you like to get involved and create a PR for this issue? :)
