### ISSUE TITLE
Incorrect reference to ingress ip in the jenkins chart release notes

### ISSUE THREAD

**Issue by naveensrinivasan** [helm/charts#101]
I am using the jenkins chart to spin a jenkins instance in aws. When the instance starts the release notes https://raw.githubusercontent.com/kubernetes/charts/d745f4879e58d8c2f3a3497a7ed8e2369204f9b7/stable/jenkins/templates/NOTES.txt has reference to LB ip
 `export SERVICE_IP=$(kubectl get svc --namespace {{ .Release.Namespace }} {{ template "fullname" . }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')`

In `aws` within ingress, it is the `hostname` and the `ip` does not have value. 

How can this fixed in such a way it would work both in GKE and AWS?

**Comment by prydonius** [comment]
Thanks @naveensrinivasan, I have a proposal in #84 about this issue, but wanted to get other opinions. I'll close this in favour of #84.
