### ISSUE TITLE
MariaDB Chart Error Log Points to File Instead of STDOUT/STDERR

### ISSUE THREAD

**Issue by apeschel** [helm/charts#10109]
Maybe there's a reason for this that I'm not aware of, but the default configuration for the MariaDB chart points the error log to a local file within the container, rather than pointing it to stderr or stdout. This is problematic, as it means getting the error logs follows a non-standard workflow, and restarting the container means losing the error log.

https://github.com/helm/charts/blob/master/stable/mariadb/values.yaml#L158

**Which chart**:

Pretty much all MariaDB chart versions. Still present in MariaDB 5.2.4.

**Comment by juan131** [comment]
Hi @apeschel 

That file is a symbolic link to `/dev/stdout` as you can check in the link below:

https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.2/debian-9/rootfs/prepare.sh#L18

Therefore, all the logs are redirected to `stdout` so you can access to them through K8s API.
