### ISSUE TITLE
Can't disable grafana datasource sidecar

### ISSUE THREAD

**Issue by dteller** [helm/charts#10115]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-16T23:39:08Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

helm version
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}

**Which chart**:
stable/prometheus-operator

**What happened**:
The grafana datastores sidecar was enabled.

**What you expected to happen**:
The grafana datastores sidecar was disabled.

**How to reproduce it** (as minimally and precisely as possible):

values.yaml contains:

grafana:
  sidecar:
    datasources:
      enabled: false

helm install --namespace monitoring --name prometheus-operator stable/prometheus-operator -f values.yaml 

**Anything else we need to know**:

It seems that the datasource sidecar is forced on somewhere.
I can see in the templates where it checks the value, but setting it in the values.yaml has no effect.
(Setting the label used doesn't either).

The default setup generates a prometheus datasource and marks it default.
I want a thanos datasource to be the default but there is no way to do that.
You can create datasources with the datasource: section but setting one to default makes it clash with the prometheus datasource created by the sidecar.

**Comment by paskal** [comment]
@dteller it's the same, could you please post your values.yaml fragment with proper indentation?

**Comment by dteller** [comment]
sidecar:
    datasources:
       enabled: false

**Comment by dteller** [comment]
'''  sidecar:
    datasources:
      enabled: false
'''

**Comment by dteller** [comment]
```
grafana:
  enabled: true
  image:
    tag: 5.4.2
  sidecar:
    datasources:
      enabled: false
```

**Comment by dteller** [comment]
Thanks

**Comment by paskal** [comment]
Both fragments (`values.yaml` and `--set`) give the same output to the helm, you can play around with it with providing same arguments to `helm template` command to see what happens when.
I think problem is not with the chart but with the way you're passing values. In other words, it's only configuration problem on your side and no changes need to be introduced to the chart, developers won't have anything to do in this issue. I suggest to close it.

**Comment by dteller** [comment]
I don't understand what configuration could be wrong there. that seems very straightforward.
And if I use the same values.yaml and add the --set it works fine.
