### ISSUE TITLE
[stable/jenkins] kubernetes agent configuration

### ISSUE THREAD

**Issue by skalp** [helm/charts#10131]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Not relevant

**Which chart**:
jenkins

**What happened**:
In container template definition, command, args and template names are not configurable (hardcoded name "jnlp" and empty command)
[...]
< command ></ command >
[...]
< name >jnlp</ name >
[...]

**What you expected to happen**:
Those values should be configurable thanks to values.yml or cli command

**How to reproduce it** (as minimally and precisely as possible):
-

**Anything else we need to know**:
-

**Comment by maorfr** [comment]
Hey @skalp,

Thanks for bringing this up.
Would you like to get involved and get a PR going for this?
