### ISSUE TITLE
[stable/prometheus-operator] Missing metrics in k8s 1.12.* 

### ISSUE THREAD

**Issue by ppcololo** [helm/charts#10135]
**Is this a request for help?**: YES

**Version of Helm and Kubernetes**: kubernetes: 1.12.2, helm: 2.11.0

**Which chart**: stable/prometheus-operator

**What happened**: grafana doesn't show some graphs

**What you expected to happen**: working graphs

**How to reproduce it** (as minimally and precisely as possible): install stable/prometheus-operator on 1.12.* k8s version

**Anything else we need to know**: 
In dashboard "K8s / Compute Resources / Cluster" we have "Memory Usage (w/o cache)" / "CPU Usage" graph. And metric **container_memory_rss** and **container_cpu_usage_seconds_total** are missing in prometheus.
In 1.12.* kubelet doesn't expose cadvisor metrics anymore

What to do with it? I can install cadvisor as daemon set, but cadvisor doesn't has those metrics too...

**Comment by paskal** [comment]
Metrics are 4 months old, could you please test actual version from https://github.com/helm/charts/pull/9516? For that clone stable/prometheus-operator directory from [this repo](https://github.com/paskal/charts), run `helm dependency update` in it, and upgrade your chart as usual using this local version.
