### ISSUE TITLE
[stable/logstash] error: open /usr/share/logstash/config/logstash.yml: read-only file system

### ISSUE THREAD

**Issue by benedikt-haug** [helm/charts#10134]
Dear developers,

**Is this a request for help?**:
Yes. I am new to this so please excuse my naivete.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT (or me not understanding how to properly use it)

**Version of Helm and Kubernetes**:
Helm v2.11.0
Kubernetes:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/logstash

**What happened**:
Your helm-chart's templates/statefulset.yml sets environment parameters. They are evaluated by the image's env2yaml.go and wants to write the result to /usr/share/logstash/config/logstash.yml. This is read-only in my case which results in the error
```
error: open /usr/share/logstash/config/logstash.yml: read-only file system
```

**What you expected to happen**:
I thought it would "just work" :D

**How to reproduce it** (as minimally and precisely as possible):

Set the file system to read-only and try to use the image with minimal configuration.

**Anything else we need to know**:

Is having a read-only cluster that uncommon and not supported or can I weasel my way around this somehow? I would like to use your template to have no redundant code myself but don't know how.

Thank you!

**Comment by alen-z** [comment]
Still relevant. Can I use environmental variables in `logstash.yml`, e.g. `xpack.monitoring.elasticsearch.cloud_id: "${CLOUD_ID}"`?

**Comment by cvanhalt** [comment]
I have the same problem.
@alen-z Have you found a solution?
