### ISSUE TITLE
Missing template files for elastic-stack

### ISSUE THREAD

**Issue by InAnimaTe** [helm/charts#10145]
@rendhalver in `charts/stable/elastic-stack/templates/` there is only a helper and text file....no actual templates???

**Comment by philoserf** [comment]
The templates come from the charts listed in `requirements.yaml`

https://github.com/helm/charts/blob/master/stable/elastic-stack/requirements.yaml

Ref: https://docs.helm.sh/chart_best_practices/#requirements

**Comment by southwolf** [comment]
Then how can I set values like `cluster.name` for the children charts?

**Comment by philoserf** [comment]
Now that is a different problem. Currently, the parent chart must expose a value in its values file. Elasticsearch's default value is used unless it is exposed in the parent chart. Here it is not.

A pull request to this chart adding values from the child charts that need to be exposed may be the answer.

There are a number of issues surrounding values and parent/child charts. I believe most people expect that could `helm install stable/elastic-stack --set 'cluster.name=ladedah'` or local values file and use `--file my_values.yaml`

I looked around and didn't find any good community articles on the issues with umbrella charts.

**Comment by philoserf** [comment]
For the record the _stable/elastic-stack_ chart does work. Even without any templates of its own. It just doesn't give you the control you want...yet. `helm install stable/elastic-stack` gave me a *halting_huron* and it waded off into the marsh of my kubernetes cluster.

**Comment by Aisuko** [comment]
It needs to add helm repo repository address and run `helm dep update` command under chart folder.

**Comment by rendhalver** [comment]
elastic-stack is basically a meta chart.
When you install it is pulls in the dependencies and listed in the requirements file.
You configure each sub-chart by using it's name as the key for the config hash.
If you look in the values.yaml it has entries for each sub-chart.
Just put your values under that key and you sub-shart will use those values.

If you use a nice wrapper like helmfile it will do the sub-chart syncing for you.

**Comment by InAnimaTe** [comment]
With that excellent explanation, I'm going to close this. Thanks all for jumping on it.
