### ISSUE TITLE
Deploying Grafana and Prometheus pvc error

### ISSUE THREAD

**Issue by dkoshkin** [helm/charts#1014]
**k8s version**: v1.6.2
**helm version**: v2.4.1

Trying to deploy `stable/grafana` and `stable/prometheus` with default settings but getting a pvc error.

```
Name:		yummy-koala-grafana
Namespace:	default
StorageClass:
Status:		Pending
Volume:
Labels:		app=yummy-koala-grafana
		chart=grafana-0.3.1
		component=grafana
		heritage=Tiller
		release=yummy-koala
Annotations:	volume.alpha.kubernetes.io/storage-class=default
Capacity:
Access Modes:
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  54m		1s		60	persistentvolume-controller			Warning		ProvisioningFailed	cannot find volume plugin for alpha provisioning
```

I created a pv but it is not binding, I have deployed a different pv and pvc and it works: 
```
➜  out git:(heapster) kubectl get pv
NAME                CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS      CLAIM                           STORAGECLASS   REASON    AGE
grafana             10Gi       RWO           Retain          Available                                                            2h
heapster-influxdb   10Gi       RWO           Retain          Bound       kube-system/heapster-influxdb                            2h
```

**Comment by tomqwu** [comment]
Something is wrong with `volume.alpha.kubernetes.io/storage-class=default`

what's your `kubectl describe storageclass`? 

You should have something like `beta` for dynamic storage provisioning,  maybe you can try remove `storageClassName: default`
e.g. kubectl describe pvc, you can see below
`volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/aws-ebs`

**Comment by dkoshkin** [comment]
Thanks @tomqwu I think I misunderstood how the `default` StorageClass works. Im not creating a cluster with a cloud integrated provisioner, so I did not have any storage classes defined.

I was able to create the charts successfully using a different storage class.
