### ISSUE TITLE
[stable/postgresql] "initdbScripts" doesn't work if no scripts put under directory "docker-entrypoint-initdb.d"

### ISSUE THREAD

**Issue by ywk253100** [helm/charts#10197]

**Comment by juan131** [comment]
Hi @ywk253100 

Could you provide more information about the issue you're facing? Please provide the steps to reproduce it.

**Comment by AustinReichert** [comment]
@juan131 Hello, not the OP but I believe I have encountered the same issue. 

I've been trying to use the initdbScripts to install an extension for me that would be useful for another application. Perhaps this is not what initdbScripts is meant to be used for, but from the description provided [here](https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml#L117), I thought I'd try it.

My code is as follows:

`initdbScripts:
    init_postgres.sh: |
      #!/bin/bash
      /usr/lib/postgresql/9.6/bin/psql -U postgres -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;'`

I've logged into the database with `psql -U postgres` and did a `\dx` to see if the extension is present, but it never is. After manually running a `CREATE EXTENSION IF NOT EXISTS pg_trgm;'` and a subsequent `\dx`, it has succeeded.

I `grep`'d the charts/stable/postgresql directory for "initdbScripts" and the only .Values usage I've seen is for "initdbScriptsConfigMap".

I also tried peeking at the [docker-entrypoint.sh](https://github.com/docker-library/postgres/blob/040949af1595f49f2242f6d1f9c42fb042b3eaed/9.6/docker-entrypoint.sh) and the [Dockerfile](https://github.com/docker-library/postgres/blob/040949af1595f49f2242f6d1f9c42fb042b3eaed/9.6/Dockerfile) for any clues and I'm not sure I understand it well enough. 

As you can see, the command I'd like to run is extremely simple and if there's a better/easier way to install the extension, I'm happy to use that instead. I hope this has been helpful. Looking forward to your reply.

**Comment by ywk253100** [comment]
The logic [here](https://github.com/helm/charts/blob/master/stable/postgresql/templates/initialization-configmap.yaml#L1) seems wrong, the initialization configmap is rendered only when the `files/docker-entrypoint-initdb.d/*.{sh,sql,sql.gz}` exists `and` `.Values.initdbScriptsConfigMap` isn't null. I think it should be `or`?

**Comment by tompizmor** [comment]
I just sent this PR fixing the issue https://github.com/helm/charts/pull/10332
