### ISSUE TITLE
[stable/jaeger-operator] Chart installation fails with crd already exists

### ISSUE THREAD

**Issue by harshal-shah** [helm/charts#10207]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
kubernetes 1.11.5
helm 2.12.0

**Which chart**:
stable/jaeger-operator

**What happened**:
- run helm install --name jaeger-operator --namespace tracing stable/jaeger-operator
- installation fails with following error
~~~
Error: release jaeger-operator failed: customresourcedefinitions.apiextensions.k8s.io "jaegers.io.jaegertracing" already exists
~~~

**What you expected to happen**:
Installation should complete successfully.

**How to reproduce it** (as minimally and precisely as possible):
- run helm install --name jaeger-operator --namespace tracing stable/jaeger-operator

**Anything else we need to know**:
Proabably crd.yaml needs some conditionals such as https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus-operator/crd-prometheusrules.yaml#L1

**Comment by harshal-shah** [comment]
I was able to work around this by adding flag `--no-crd-hook` to the helm install command

**Comment by cpanato** [comment]
sounds good, i will add that in the chart

**Comment by harshal-shah** [comment]
@cpanato  No need to. I think this is a helm `2.12.0` issue. I tested the chart on another cluster with helm `2.11.0` and the chart got installed without any issues.

**Comment by harshal-shah** [comment]
Found a new helm release which should fix this, https://github.com/helm/helm/releases/tag/v2.12.1

testing it now

**Comment by pzheng64** [comment]
I notice the same issue with Helm 2.14.0.
