### ISSUE TITLE
[stable/datadog] Enable event collection

### ISSUE THREAD

**Issue by cknowles** [helm/charts#1021]
The datadog agent can collect Kubernetes events so ideally the chart would deal with this out of the box. From [the readme](https://github.com/DataDog/docker-dd-agent):

```
KUBERNETES_COLLECT_EVENTS enables event collection from the kubernetes API, 
given that KUBERNETES is also set. 
Note: only one agent should have KUBERNETES_COLLECT_EVENTS set per cluster.
```

So it's a little bit tricky to enable. One idea would be to use taints/tolerations so the Daemon Set runs on all nodes apart from one and then have a separate Deployment which runs on that single node. There could possibly be a Job in the chart as well which ensures only one node has the appropriate labels/taints.

In the future maybe this can be improved via [this issue](https://github.com/DataDog/dd-agent/issues/3113).

**Comment by pierreozoux** [comment]
I found a nice little hack:
https://github.com/kubernetes/charts/pull/1059#issuecomment-304076525

The idea is to deploy just on the node that has the `kube-state-metrics` pod, what do you think?

**Comment by cknowles** [comment]
@pierreozoux interesting, that could work. A couple of things I'm interested in; a) is the PID of `supervisord` still 1 when executed via your wrapper script? b) I ran the datadog event collection during some initial testing and it worked fine without kube-state-metrics, do those two things need to be tied together?

**Comment by mazzy89** [comment]
Not clear here if collection of events works. I've added the flag but no events are sent to the DD dashboard. Running v0.5.0 of the chart

**Comment by mazzy89** [comment]
I was able to see events in Datadog only when the events came from `namespace:default`. This because the datadog agent by default collects event by `default` namespace. Any idea around how to define namespaces from the config file of the chart?

**Comment by mazzy89** [comment]
Any updates on this?

**Comment by cknowles** [comment]
Looks like this is coming in https://github.com/DataDog/docker-dd-agent/pull/230.

**Comment by xvello** [comment]
Hi @mazzy89,

Getting events out of the `default` namespace is enabled via the `KUBERNETES_NAMESPACE_NAME_REGEX` option. I'm adding it to the documentation as that slipped through.

**Comment by hkaj** [comment]
Hey all,
We now have a simple way to enable event collection. Check out https://github.com/DataDog/docker-dd-agent#environment-variables-1 and look for `KUBERNETES_LEADER_CANDIDATE`. If you have RBAC enabled, here's an RBAC setup that makes the agent happy: https://gist.github.com/hkaj/404385619e5908f16ea3134218648237

**Comment by cknowles** [comment]
@hkaj, I've been trying to enable event collection to fix this issue up but having some problems. It's on an RBAC enabled cluster, the RBAC gist you mentioned is all done fine and access errors that we had at first are gone. `kubectl get events -w --all-namespaces` shows there are events happening, however still no events to be found in datadog. Other events like Docker are coming through fine from the same agents so I'm assuming this is Kubernetes event specific.

The only extra config added to the daemon set from previous settings is the service account plus these env vars:
```
- name: KUBERNETES_LEADER_CANDIDATE
  value: "true"
- name: KUBERNETES_LEADER_LEASE_DURATION
  value: "60"
- name: KUBERNETES_NAMESPACE_NAME_REGEX
  value: ".*"
```

Any ideas?

**Comment by hkaj** [comment]
Hey @c-knowles 
Can you check that you have a configmap called `datadog-leader-elector` in the same namespace as the agent? If so please look at the `creator` annotation it has, it should be an agent pod name. Then you can inspect the collector's log in this agent pod to see if leader election is working properly, or send a flare to our support and mention this issue, and we'll have a look at the logs to see what's going on.

**Comment by cknowles** [comment]
@hkaj thanks for the advice, config map is present, leader annotation is there and that pod is running. I'll have a look through the logs but otherwise send off a flare.

**Comment by hkaj** [comment]
@c-knowles  oh wait actually that might just be your `KUBERNETES_NAMESPACE_NAME_REGEX` regex. I think there are some escaping issue there. Can you try with a fixed namespace first to see if it comes from there?

**Comment by cknowles** [comment]
@hkaj, snap! I was just typing this. Turns out the problem is the regex. Could probably do with quoting the var in https://github.com/DataDog/docker-dd-agent/blob/cb8be3dc57f858a4478769efdf0c4254726f2576/entrypoint.sh#L66 which I think is best practice anyway.

After spotting the problem, it wasn't obvious at first what to change the value to so had a play around:
```
A  /entrypoint.sh: 66: [: bin: unexpected operator

A  /entrypoint.sh: 66: [: .: unexpected operator 
```

This works with the latest docker image, notice the double quoting of single quotes:
```
- name: KUBERNETES_NAMESPACE_NAME_REGEX
  value: "'.*'"
```

**Comment by xvello** [comment]
/close

Issue in the image and not the chart itself, tracked upstream

**Comment by cknowles** [comment]
Is this now explicitly supported or only under `env`? Other charts seem to have specific switches for features rather than bundle everything under additional parameters, I wondered if that’s the intention here.
