### ISSUE TITLE
[stable/jenkins] install with rbac doesn't work in tiller-less mode

### ISSUE THREAD

**Issue by 375gnu** [helm/charts#10267]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: helm v2.11.0 and v2.12.1, k8s 1.10

**Which chart**: stable/jenkins

**What happened**: processed `rbac.yaml` doesn't have `apiVersion` field

**What you expected to happen**: it has it.

**How to reproduce it** (as minimally and precisely as possible):

```
helm template -n rel --kube-version 1.10 .
```

**Anything else we need to know**:

The problem is 
```
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1beta1" }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
```

I suggest changing it to
```
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
```

**Comment by mrsmuneton** [comment]
Just for the record, I filed this and opened a PR with the fix back in Nov: https://github.com/helm/charts/issues/8582
