### ISSUE TITLE
helm install render error for annotations

### ISSUE THREAD

**Issue by ezlee** [helm/charts#10275]
I was trying to add annotations to the service when using helm to deploy traefik:

```
helm install stable/traefik --name traefik-internal --set serviceType=LoadBalancer,loadBalancerIP="172.20.0.130",replicas=0,service.annotations="service.beta.kubernetes.io/azure-load-balancer-internal: true",dashboard.enabled=true,ssl.enabled=true,rbac.enabled=true,acme.enabled=true,acme.persistence.enabled=true
Error: render error in "traefik/templates/service.yaml": template: traefik/templates/service.yaml:17:35: executing "traefik/templates/service.yaml" at <.Values.service.anno...>: range can't iterate over service.beta.kubernetes.io/azure-load-balancer-internal: true
```

Tried many different ways with escape "\" for slash,double quotes, colon,space, none of them works.
The only way is to add manually with "kuberctl edit svc traefik-internal" after it is installed.
```
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```

Does anyone have rendered it correctly? How?
thanks!

**Comment by maorfr** [comment]
Can this help? helm/helm#1987

**Comment by maorfr** [comment]
and in general, have you considered passing a local values file using `--values`\`-f` file instead of passing values on the command line using `--set`?

**Comment by ezlee** [comment]
@maorfr 
no, actually I tried the --values \ -f option with the following contents in the first place, it didn't work. 
`controller:
  service:
    loadBalancerIP: 172.20.0.131
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
`

**Comment by maorfr** [comment]
Here is how to solve it using `--set`:
```
--set service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal=true"
```

**Comment by abelal83** [comment]
for anyone else that comes across this I ended up with 
values.yaml
```
controller:
  service:
    annotations:
      service.beta.kubernetes.io/azure-dns-label-name: ""
```
main.tf
```
  set_string {
    name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/azure-dns-label-name"
    value = "${var.domain_name_label}"
  }
```
