### ISSUE TITLE
[stable/postgresql] `init-scripts` configmap is skipped with non-null `.Values.initdbScripts`

### ISSUE THREAD

**Issue by intelfx** [helm/charts#10284]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

N/A

**Which chart**:

[stable/postgresql](https://github.com/helm/charts/tree/master/stable/postgresql)

**What happened**:

`.Values.initdbScripts` is not honored

**What you expected to happen**:

`.Values.initdbScripts` should be honored

**How to reproduce it** (as minimally and precisely as possible):

1. Edit `values.yaml` to include:
    ```
    initdbScripts:
      test.sh: |
        #!/bin/sh
    ```

2. Deploy stable/postgresql chart

3. Run `kubectl get configmaps -l release=<release>`

4. Observe no `<release>-init-scripts` configmap created

**Anything else we need to know**:

Missing condition at https://github.com/helm/charts/blob/master/stable/postgresql/templates/initialization-configmap.yaml#L1

**Comment by andresbono** [comment]
Thanks for submitting the issue and the PR!

**Comment by tompizmor** [comment]
I miss this issue and the PR and sent this [other PR](https://github.com/helm/charts/pull/10332) that is already merged.  Please check [my comment](https://github.com/helm/charts/pull/10294#issuecomment-450835686) in your PR.
