### ISSUE TITLE
Cluster Autoscaler Chart - Can't Open /etc/gce.conf

### ISSUE THREAD

**Issue by elithrar** [helm/charts#10292]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report
**Version of Helm and Kubernetes**:

```
➜  ~  kops get simple.k8s.local -oyaml | rg 'kubernetesVersion'                                                                                      
  kubernetesVersion: 1.10.11       
```
```
➜  ~  helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

**Which chart**: cluster-autoscaler - https://github.com/helm/charts/tree/master/stable/cluster-autoscaler

**What happened**: Installation of the chart failed due to a missing configuration file in the Managed Instance Group provided to the chart.

**What you expected to happen**: Successful deployment of the Pods.

**How to reproduce it** (as minimally and precisely as possible):

```
➜  ~  helm install stable/cluster-autoscaler \
--name cluster-autoscaler-gce \
--set cloudProvider=gce \
--set autoDiscovery.clusterName="simple.k8s.local" \
# "as-nodes" is a new MIG. Also fails when using the existing kops-created MIG.
--set "autoscalingGroupsnamePrefix[0].name=as-nodes,autoscalingGroupsnamePrefix[0].maxSize=10,autoscalingGroupsnamePrefix[0].minSize=2"
```

* Pods enter a CrashLoopBackoff

```
kubectl logs -f $podname

I1228 19:10:59.169325       1 predicates.go:122] Using predicate CheckVolumeBinding
I1228 19:10:59.169411       1 predicates.go:122] Using predicate MaxAzureDiskVolumeCount
I1228 19:10:59.169494       1 predicates.go:122] Using predicate MaxCSIVolumeCountPred
I1228 19:10:59.169582       1 predicates.go:122] Using predicate MaxGCEPDVolumeCount
I1228 19:10:59.169666       1 predicates.go:122] Using predicate NoDiskConflict
I1228 19:10:59.169797       1 cloud_provider_builder.go:29] Building gce cloud provider.
E1228 19:10:59.170002       1 gce_manager.go:115] Couldn't read config: read /etc/gce.conf: is a directory
F1228 19:10:59.170103       1 gce_cloud_provider.go:334] Failed to create GCE Manager: read /etc/gce.conf: is a directory
```

It seems it's looking for `gce.conf` (which does not exist as a file) and failing.

**Comment by elithrar** [comment]
Related, but also unresolved (timed out): https://github.com/helm/charts/issues/7775

**Comment by elithrar** [comment]
Solved - the cloudConfig is at `/etc/kubernetes/cloud.config`

**Comment by RsknCankov** [comment]
Hello, faced same error, after setting cloudConfigPath t /etc/kubernetes/cloud.conf -> Failed to create GCE Manager: read /etc/kubernetes/cloud.conf: is a directory

Helm
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

Kubectl
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-dispatcher", GitCommit:"1215389331387f57594b42c5dd024a2fe27334f8", GitTreeState:"clean", BuildDate:"2019-05-13T18:18:50Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.25", GitCommit:"d4c79083ab6dea5d26ef4ed8d50b145268349bc3", GitTreeState:"clean", BuildDate:"2019-06-22T16:10:31Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
