### ISSUE TITLE
[meta] Cannot /assign to the users recommended by k8s-ci-robot

### ISSUE THREAD

**Issue by AaronFriel** [helm/charts#10308]
The bot gives bad advice and/or code OWNERS files are out of date. See here: https://github.com/helm/charts/pull/10305#issuecomment-450540277

**Comment by AaronFriel** [comment]
Not stale. Active bug.

**Comment by chrisingenhaag** [comment]
Yes, I noticed the same in my minio pull request

**Comment by chrisingenhaag** [comment]
I think this is something for @mattfarina or @unguiculus maybe. Nobody noticed the issue until now.

We think the k8s bot configuration has an issue and OWNERS assignments don´t work at the moment.

**Comment by mattfarina** [comment]
The issue here is that the https://github.com/helm/charts#owning-and-maintaining-a-chart process was not followed. The person being recommended was not added as a collaborator.

#12501 should fix this instance of the problem.
