### ISSUE TITLE
[stable/mariadb] Existing Persistent Storage fails

### ISSUE THREAD

**Issue by alokrajiv** [helm/charts#10322]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT (Possibly)

**Version of Helm and Kubernetes**: 

```
$helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```
```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3+IKS", GitCommit:"16085f81010963073bdba425efe1d277c44a224f", GitTreeState:"clean", BuildDate:"2018-12-04T10:07:31Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
[stable/mariadb] version: 5.0.9

**What happened**:
Existing Persistent Storage Volume behaviour is possibly inconsistent with other charts.
`persistence.enabled : true`
`persistence.existingClaim: xxxxx`
and
`persistence.enabled : false`
`persistence.existingClaim: xxxxx`

both don't seem to work.  [Issue #7647](https://github.com/helm/charts/issues/7647) does report this issue, but it was closed before, with no reopening after other users have reported the same.

**What you expected to happen**:
Possibly behaviour should be exactly be same if existing PVC specified or not, except that instead of a new PVC, the existing claim should be mounted and used to start the container.

**How to reproduce it** (as minimally and precisely as possible):
`persistence.existingClaim: xxxxx`

**Anything else we need to know**:
I have fixed this for my own deployment, and could possibly give in a PR. Unless ofcourse, someone confirm the intended behavior by the authors is different.

**Comment by juan131** [comment]
Hi @alokrajiv 

I don't understand very well the wrong behaviour you're explaining. You described two scenarios:

- Scenario A:
  - persistence.enabled : true
  - persistence.existingClaim: xxxxx
- Scenario B:
  - persistence.enabled : false
  - persistence.existingClaim: xxxxx

What do you expect on each scenario? I would expect the following behaviour:

- Scenario A: An existing PVC called "xxxxx" is used to store MariaDB data.
- Scenario B: No persistence is used. The existingClaim is ignored.

Am I right?

**Comment by alokrajiv** [comment]
Hi @juan131,

Scenario A: My current experience is PVC doesn't mount at `/bitnami/mariadb`

Notice: [mount point at line 156](https://github.com/helm/charts/blob/b89980b433d7883c2c494b05b90f16267a7bb903/stable/mariadb/templates/master-statefulset.yaml#L156)

[`data`](https://github.com/helm/charts/blob/b89980b433d7883c2c494b05b90f16267a7bb903/stable/mariadb/templates/master-statefulset.yaml#L144) that has the mountPoint of `/bitnami/mariadb` is actually the  [`volumeClaimTemplates`](https://github.com/helm/charts/blob/b89980b433d7883c2c494b05b90f16267a7bb903/stable/mariadb/templates/master-statefulset.yaml#L207) PVC.

**Comment by alokrajiv** [comment]
Also, do notice that Scenario B will not happen as well,

The [Volume](https://github.com/helm/charts/blob/b89980b433d7883c2c494b05b90f16267a7bb903/stable/mariadb/templates/master-statefulset.yaml#L154) is not wrapped in a `persistence.enabled` condition, and so, existingClaim will not be ignored and will be added, even if `persistence.enabled : false`

**Comment by juan131** [comment]
I'm able to reproduce the issue. Check my PR to allow the existing PVC to be mounted at `/bitnami/mariadb`
