### ISSUE TITLE
mysqldump helm chart doesn't add rsync command even though upload ssh is enabled 

### ISSUE THREAD

**Issue by salfand** [helm/charts#10361]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm version 2.12.1
K8S version 1.11.5

**Which chart**:
charts/stable/mysqldump/

**What happened**:
Installed the helm chart with ssh upload enabled, however the script didn't updated accordingly and rsync command didn't add to the script as it should be. 

**What you expected to happen**:
rsync command add to the script.

**How to reproduce it** (as minimally and precisely as possible):
edit values.yaml file and enable ssh upload, then install the helm chart

**Anything else we need to know**:

**Comment by monotek** [comment]
Whats the error message?

**Comment by monotek** [comment]
ah, is see... 
thats the problem:
https://github.com/helm/charts/issues/10296

fix is underway...

**Comment by monotek** [comment]
will be fixed with: https://github.com/helm/charts/pull/10469
