### ISSUE TITLE
[stable/jenkins] AdditionalConfig works only if OverwriteConfig is false

### ISSUE THREAD

**Issue by drzero42** [helm/charts#10372]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Which chart**: stable/jenkins 0.26.0

With PR #9296 a feature for adding additional config files was introduced. However, it was put inside an if/else block in config.yaml in the definition for apply_config.sh (line 215 in config.yaml at the time of writing this), which means the additional config files created, will only be copied from /var/jenkins_config to /var/jenkins_home if OverwriteConfig is set to false. This looks like a mistake. I think it should be put outside the if/else block pertaining to OverwriteConfig, so any additional config files will be copied into jenkins_home on every boot.
Either that, or it should follow the same rules as the default config files with regards to OverwriteConfig.

**Comment by maorfr** [comment]
Not stale
