### ISSUE TITLE
Prometheus Operator with latest release (1.3.0) using ServiceMonitors is now broken

### ISSUE THREAD

**Issue by omerxx** [helm/charts#10375]
**What happened:**
Trying to `helm install stable/prometheus` with `additionalServiceMonitors` enabled is now broken due to latest commit.
https://github.com/helm/charts/commit/8769497e64820ed06c7c9d0316823735b205520c

**Workaround:**
`helm install stable/prometheus --version 1.2.0`

**What needs to be fixed:**
https://github.com/helm/charts/blob/5b209bedf7c248312c0db83ac5c775d7780f70be/stable/prometheus-operator/templates/prometheus/servicemonitors.yaml#L6
This is only one of multiple lines in this commit assuming an internal path (`.Values...`) while it shouldn't as it's in a `Range` scope.

**Please review:**
@anandsinghkunwar

**Comment by anandsinghkunwar** [comment]
You're right, trying to push a change.

**Comment by omerxx** [comment]
@anandsinghkunwar Thanks for the quick response!

**Comment by anandsinghkunwar** [comment]
Fixed with  #10384. Feel free to close.
