### ISSUE TITLE
mysqlha user / password / database not created

### ISSUE THREAD

**Issue by Amos-85** [helm/charts#10383]
**Is this a request for help?**: yes

---

**BUG REPORT**

**Version of Helm and Kubernetes**: helm v2.12.1 / k8s v1.12.3

**Which chart**: mysqlha

**What happened**: mysqlha user / password / database not created

**What you expected to happen**: be able to create new mysql user / password / database

**How to reproduce it**: 

set those values from values.yaml file to create new user / password / database

mysqlUser
mysqlPassword
mysqlDatabase

**Anything else we need to know**: no

**Comment by afirth** [comment]
I think this database should be created by the [mysql entrypoint](https://github.com/docker-library/mysql/blob/696fc899126ae00771b5d87bdadae836e704ae7d/5.7/docker-entrypoint.sh#L176), which doesn't rely on this chart for anything besides setting the env vars. Try `helm install --debug` or `kubectl describe` the pod and check the values are rendering correctly in the template/being passed to the environment? If not perhaps there is an error in your 'values.yaml'. If that's all ok, maybe check the pod logs when the entrypoint runs. Hope that helps.
