### ISSUE TITLE
[stable/postgresql] Unable to install with persistence enabled && replication disabled

### ISSUE THREAD

**Issue by aerotog** [helm/charts#10407]
This is a BUG REPORT for the postgresql helm chart. The chart fails to install due to helm syntax errors when the following values are set:

- persistence.enabled=false
- replication.enabled=true

**Version of Helm and Kubernetes**:
```
λ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
λ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/postgresql v3.9.0

**What happened**:
The chart failed to install with:
`Error: YAML parse error on postgresql/templates/statefulset-slaves.yaml: error converting YAML to JSON: yaml: line 86: mapping values are not allowed in this context`

**What you expected to happen**:
The chart should install successfully.

**How to reproduce it** (as minimally and precisely as possible):
Run `λ helm install stable/postgresql --set persistence.enabled=false --set replication.enabled=true`

**Anything else we need to know**:
I've tried this same installation in both EKS and Docker for Windows. The same failure is observed.

**Comment by aerotog** [comment]
The error line `Error: YAML parse error on postgresql/templates/statefulset-slaves.yaml: error converting YAML to JSON: yaml: line 86: mapping values are not allowed in this context` points to a syntax error in the statefulset-slaves.yaml on line 86:

```yaml
...snip...
82          timeoutSeconds: 5
83          successThreshold: 1
84          failureThreshold: 6
85        volumeMounts:
86      volumes:
87  updateStrategy:
88    type: RollingUpdate
89        - name: data
90          emptyDir: {}
```

After testing, I'm pretty sure this is fixed by simply removing the following lines from the template file:
```yaml
200{{- else }}
201        - name: data
202          emptyDir: {}
```

**Comment by tompizmor** [comment]
Hello @aerotog,

Thanks for filling the issue. I just sent this PR fixing it https://github.com/helm/charts/pull/10428

**Comment by aerotog** [comment]
Verified working in 3.9.1. Thanks for the quick fix!
