### ISSUE TITLE
Add a Helm chart for pgbouncer

### ISSUE THREAD

**Issue by gajus** [helm/charts#10418]
Would be nice if someone contributed a chart for pgbouncer, https://pgbouncer.github.io/.

Some existing community options:

* https://github.com/cradlepoint/kubernetes-helm-chart-pgbouncer authored by @mattmessinger
* https://github.com/CenterForOpenScience/helm-charts/tree/master/pgbouncer authored by @icereval

**Comment by ianks** [comment]
Can this be re opened?

**Comment by george-oakling** [comment]
Yes please. I can prepare a chart for pgbouncer if needed. But definitely would be good to have one official chart.

**Comment by intellix** [comment]
Another: https://github.com/futuretechindustriesllc/charts/tree/master/charts/pgbouncer

**Comment by rms1000watt** [comment]
hate to just bump this with a comment.. but.. 👍 
This would be great to have

**Comment by drpebcak** [comment]
https://github.com/helm/charts#deprecation-timeline
