### ISSUE TITLE
[stable/redis] default disableCommands config error in  value.yaml 

### ISSUE THREAD

**Issue by sonicrang** [helm/charts#10425]
**Version of Helm and Kubernetes**:
helm 2.11.0
k8s 1.11.3

**Which chart**: 
redis 0.25.0

**What happened**:
I copy values.yaml or values-production.yaml to local, and run cmd like "helm install --values xxx.yaml(local file from values.yaml) stable/redis ". But shows err below:

`Error: release redis-service failed: Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment.Spec: v1beta1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found [, error found in #10 byte of ...|,"value":["FLUSHDB F|..., bigger context ...|ice"}}},{"name":"REDIS_DISABLE_COMMANDS","value":["FLUSHDB FLUSHALL"]}],"image":"docker.io/bitnami/r|...
`

**What you expected to happen**:
install successfully

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I found the default config about disableCommands is 
`  disableCommands:
  - FLUSHDB
  - FLUSHALL`

when I delete this cmds , everything is normally

**Comment by tompizmor** [comment]
OK! Thanks for letting us know!
