### ISSUE TITLE
[stable/mariadb] Support for extraInitContainers like in other popular charts

### ISSUE THREAD

**Issue by alokrajiv** [helm/charts#10421]
**Is this a request for help?**: Yes. (Kinda. I had to fix either way for work. so incase helpful for others I'm giving a PR. probably need help for ok-to-test if acceptable :) )

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

`extraInitContainers` feature support in mariadb.
currently this feature is available in other popular charts I was using:

- [elasticsearch](https://github.com/helm/charts/tree/master/stable/elasticsearch#configuration)
- [mysql](https://github.com/helm/charts/tree/master/stable/mysql#configuration)
- [nginx-ingress](https://github.com/helm/charts/tree/master/stable/nginx-ingress#configuration)
- [mattermost-team-edition](https://github.com/helm/charts/blob/master/stable/mattermost-team-edition/README.md#configuration)

**Version of Helm and Kubernetes**:

```
$ helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```

**Which chart**:
[stable/mariadb] version: 5.3.1

**What happened**:
I have to fetch and edit the chart to add an initContianer. Often used in cloud providers or applications where we need some pre-run setup. For example, IKS (IBM) I need to adjust permissions on my persistent storage nfs disk. There are other times, where I need some other update or reporting or waiting, i need the pod to do before initialising the main container or other side-cars.

**What you expected to happen**:
Like I mentioned earlier, as we have options in other popular charts like [mysql](https://github.com/helm/charts/tree/master/stable/mysql#configuration), [nginx-ingress](https://github.com/helm/charts/tree/master/stable/nginx-ingress#configuration), [mattermost-team-edition](https://github.com/helm/charts/blob/master/stable/mattermost-team-edition/README.md#configuration) and [elasticsearch](https://github.com/helm/charts/tree/master/stable/elasticsearch#configuration) ... would prefer to have a string in `values.yaml` that enables me to store a template to run through the `tpl` function.

**How to reproduce it** (as minimally and precisely as possible):
I am safely, leaving this question. Should be clear by now. Please shoot a comment otherwise.

**Anything else we need to know**:

I had to do it, either way, so modified the code and will submit a PR very soon.

**Comment by alokrajiv** [comment]
I had to fix this for my work and put in our local museum, but thought might be useful for others. 

I have given a PR onto the repo based on my references of the feature in other popular charts specifically mysql.

https://github.com/helm/charts/pull/10423

**Comment by tompizmor** [comment]
I agree this is a nice to have feature. Thanks for sending the PR, I will review it.

**Comment by alokrajiv** [comment]
The PR was merged. Closing this now. thanks

**Comment by alokrajiv** [comment]
@tompizmor Been lately shifting a project dependency from mysql  to mariadb chart. So, just opening a PR for the bugs/features at night for the fixes I do at work in the day time :)

btw, opened a bug issue #10464 & a PR #10465 . Do review through if you get time.
