### ISSUE TITLE
[stable/sonarqube] Add post-install job

### ISSUE THREAD

**Issue by RothAndrew** [helm/charts#10447]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Add an optional post-install job that gives the ability to configure SonarQube via its API.

Some of the things we always do programmatically via the API after we deploy SonarQube is:

- Change default admin password
- Create a Jenkins webhook
- Create a quality gate, its associated quality gate conditions, and set that quality gate as the system-wide default

If there were a post-install job like [this example](https://github.com/helm/helm/blob/master/docs/examples/nginx/templates/post-install-job.yaml) that can optionally be use, this would be a breeze. Currently we're talking about rolling our own Helm chart with `stable/sonarqube` as a requirement, but it would be so much better if it was baked in. We believe this is something that is done commonly enough to warrant adding to the base chart.

**Comment by rjkernick** [comment]
Sounds interesting. Feel free to open a PR if you have the bandwidth to try it out
