### ISSUE TITLE
[stable/mongo] broken indentation when specifying resource quota for metrics

### ISSUE THREAD

**Issue by erictcgs** [helm/charts#10445]
**Is this a request for help?**: 
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
Helm 2.10, K8s 1.10

**Which chart**:
Mongo

**What happened**:
Specifying metrics resource quotas results in invalid yaml

**What you expected to happen**:
Valid yaml

**How to reproduce it**:
Specify resource quotas for metrics

**Anything else we need to know**:
Problem is in line 163:
https://github.com/helm/charts/blob/feaa112a277a0b7ce9c0c1f8eb4e153ea1af298a/stable/mongodb/templates/deployment-standalone.yaml#L163

toYaml needs to be unindented for dictionary serialization to be correct, same as L131 (which works)

**Comment by juan131** [comment]
Thanks for reporting. I just created a PR to fix it.

**Comment by juan131** [comment]
Hi @erictcgs 

The indentation issues has been solved on version `5.0.2`. Could you give it a try?
