### ISSUE TITLE
[stable/mariadb] Existing Secret fails

### ISSUE THREAD

**Issue by alokrajiv** [helm/charts#10464]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 

```
$helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```
```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3+IKS", GitCommit:"16085f81010963073bdba425efe1d277c44a224f", GitTreeState:"clean", BuildDate:"2018-12-04T10:07:31Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
[stable/mariadb] version: 5.4.0

**What happened**:
Existing Secret behaviour is possibly inconsistent with other charts.
`rootUser.existingSecret: "my-secret"`
This don't seem to work because all templates will still refer to the `secretKeyRef` as `template "mariadb.fullname" .` (the default from the `secret` template)

**What you expected to happen**:
Possibly behaviour should be that the  `secretKeyRef` should be adjusted if `rootUser.existingSecret` is specified.

**How to reproduce it** (as minimally and precisely as possible):
`rootUser.existingSecret: "my-secret"`

**Anything else we need to know**:
I have fixed this for my own work, and have a PR.

**Comment by alokrajiv** [comment]
guys, I have a PR at #10465 I fixed earlier today locally. Do review and merge if it makes sense to others :)

**Comment by juan131** [comment]
https://github.com/helm/charts/pull/10465 was accepted and merged!
