### ISSUE TITLE
[jenkins] cp --no-clober / -n isn't supported by busybox

### ISSUE THREAD

**Issue by 375gnu** [helm/charts#10471]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Version of Helm and Kubernetes**: any

**Which chart**: jenkins 0.27

**What happened**: init pod failed

**What you expected to happen**: init pod finished successfully

**How to reproduce it** (as minimally and precisely as possible): use AlpineLinux based image for Jenkins, provision an updated deployment 

**Anything else we need to know**:

in templates/config.yml we have:
```
  apply_config.sh: |-
    mkdir -p /usr/share/jenkins/ref/secrets/;
    echo "false" > /usr/share/jenkins/ref/secrets/slave-to-master-security-kill-switch;
{{- if .Values.Master.OverwriteConfig }}
    cp /var/jenkins_config/config.xml /var/jenkins_home;
    cp /var/jenkins_config/jenkins.CLI.xml /var/jenkins_home;
    cp /var/jenkins_config/jenkins.model.JenkinsLocationConfiguration.xml /var/jenkins_home;
{{- else }}
    cp --no-clobber /var/jenkins_config/config.xml /var/jenkins_home;
    cp --no-clobber /var/jenkins_config/jenkins.CLI.xml /var/jenkins_home;
    cp --no-clobber /var/jenkins_config/jenkins.model.JenkinsLocationConfiguration.xml /var/jenkins_home;
{{- if .Values.Master.AdditionalConfig }}
{{- range $key, $val := .Values.Master.AdditionalConfig }}
    cp /var/jenkins_config/{{- $key }} /var/jenkins_home;
{{- end }}
{{- end }}
```

`--no-clobber` option is supported by GNU coreutils but not busybox, so in AlpineLinux based containers cp fails.

I suggest changing it to:
```
...
    test -f /var/jenkins_home/config.xml || cp /var/jenkins_config/config.xml /var/jenkins_home;
...
```
and so on.

Cases like
```
    # Copy plugins to shared volume
    cp -n /usr/share/jenkins/ref/plugins/* /var/jenkins_plugins;
```

can be changed to
```
    # Copy plugins to shared volume
    find /usr/share/jenkins/ref/plugins/ -maxdepth 1 -type f -exec /bin/sh -c 'test -f /var/jenkins_plugins/$(basename {}) || cp {} /var/jenkins_plugins' \;
```

This should work with any coreutils implementation.

Alternatively `cp` can be wrapped with shell script which implements `-n/--no-clobber`.

I can prepare a PR (but i don't want to sign any CLA or similar things).

**Comment by maorfr** [comment]
Hey @375gnu,

Thanks for bringing this up!
If you don't want to sign CLA, you can't prepare a PR ;)

Let's leave this issue open for now and see if anyone else wants to pick this up.

**Comment by maorfr** [comment]
https://helm.sh/blog/helm-dco/index.html
