### ISSUE TITLE
template "filebeat-ds.fullname" not defined

### ISSUE THREAD

**Issue by saravana-code** [helm/charts#10481]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG report

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

kubernetes version :1.8.1

**Which chart**:
stable/filebeat
stable/heapster
stable/nginx-ingress

**What happened**:
I have made the changed to according to my enviroment like influx/logstash url,influxdb names and creating a package and trying to install it, but it is throwing below error:

++++
Error: render error in "filebeat-ds/templates/service.yaml": template: filebeat-ds/templates/service.yaml:4:20: executing "filebeat-ds/templates/service.yaml" at <{{template "filebeat...>: template "filebeat-ds.fullname" not defined
++++++
**What you expected to happen**:

Wants to install these apps using helm

**How to reproduce it** (as minimally and precisely as possible):
Try installing the  charts after making the changes.

**Anything else we need to know**:
Error when trying heapster  and nginx-ingress

Error: render error in "heapster/templates/ingress.yaml": template: heapster/templates/ingress.yaml:1:14: executing "heapster/templates/ingress.yaml" at <.Values.ingress.enab...>: can't evaluate field enabled in type interface {}
+++
Please help.

**Comment by saravanakumarangamuthu** [comment]
getting the role authentication error as well:

Error: release my-release3 failed: clusterroles.rbac.authorization.k8s.io "my-release3-nginx-ingress" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["patch"]} PolicyRule{Resources:["ingresses/status"], APIGroups:["extensions"], Verbs:["update"]}] user=&{system:serviceaccount:kube-system:default 68ec4706-6e14-11e8-abe2-021978c6d1d6 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
