### ISSUE TITLE
Container does not get ready when the release name is reused

### ISSUE THREAD

**Issue by cjongseok** [helm/charts#10489]
**Is this a request for help?**:
YES

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm: 
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

k8s: I am using GKE
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.5", GitCommit:"d776b4deeb3655fa4b8f4e8e7e4651d00c5f4a98", GitTreeState:"clean", BuildDate:"2018-11-08T20:33:00Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/wordpress
stable/mediawiki

**What happened**:
Mariadb container does not get ready, when I re-installed a chart with the same release name after purging.

**What you expected to happen**:
Mariadb container status should turn to READY, although the release name is re-used.

**How to reproduce it** (as minimally and precisely as possible):
STEP 1: 1st Installation
```
> kubectl create namespace my-namespace

> helm --namespace my-namespace install stable/wordpress --name wordpress
Success with help messages

> kubectl -n my-namespace get po/wordpress-mariadb-0 -w
NAME                  READY     STATUS    RESTARTS   AGE
wordpress-mariadb-0   0/1       ContainerCreating   0          4s
wordpress-mariadb-0   0/1       Running   0          13s
wordpress-mariadb-0   1/1       Running   0          1m
```
STEP 2: Removal of the chart
```
> helm del --purge wordpress
release "wordpress" deleted

# Wait for enough time for the entire removal
> kubectl -n my-namespace get all
No resources found.
```
STEP 3: 2nd Installation
```
> helm --namespace my-namespace install stable/wordpress --name wordpress --replace
Success with help messages

> kubectl -n my-namespace get po/wordpress-mariadb-0 -w
NAME                  READY     STATUS    RESTARTS   AGE
wordpress-mariadb-0   0/1       ContainerCreating   0          4s
wordpress-mariadb-0   0/1       Running   0          13s
wordpress-mariadb-0   0/1       Running   1          2m
```

**Anything else we need to know**:
I tested two charts (stable/wordpress, stable/mediawiki) which include MariaDB container, and both have shown the same symptoms.

**Comment by cjongseok** [comment]
@javsalgar Thanks a lot. Yes right there were lots of PVCs and the same release name worked after their removal.

It seems helm needs to provide more persistence options on `delete` command. For example, `--pvc-purge` can be used to delete PVC together with its release. This option would make the release name really reusable as `--purge`'s usage, since a lot of charts use PVC.

How about this feature? If it makes sense, I can participate on its implementation.

**Comment by javsalgar** [comment]
Hi,

That's something it is being discussed. It could be possible to add hooks to remove the PVC in the chart, but it is argued that the feature should be added in Helm itself. I encourage you to join the Kubernetes slack channel and the Sig-Apps group. There you will find the current discussions that are taking place.

**Comment by cjongseok** [comment]
I should join the channel! I appreciate your comments, @javsalgar . They are really helpful.
