### ISSUE TITLE
[ODOO] Conf to remote postgres

### ISSUE THREAD

**Issue by TheMalloum** [helm/charts#10502]
**Is this a request for help?**:

--- yes 

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Version of Helm and Kubernetes**:

**Which chart**:

ODOO

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by juan131** [comment]
Hi @TheMalloum 

Could you please provide us more information about your feature request?
Are you having issues to customise the PostgreSQL chart that is created as dependency of the PostgresQL chart?
