### ISSUE TITLE
[meta] Add Atlantis maintainers as read-only collaborators.

### ISSUE THREAD

**Issue by jkodroff** [helm/charts#10500]
Could a Helm member please add the following people as read-only collaborators so that we can approve PRs for the Atlantis chart without bothering the maintainers?

https://github.com/helm/charts/blob/master/stable/atlantis/OWNERS

**Comment by jkodroff** [comment]
Pinging the maintainers - we have some open PRs and would like to be able to move them forward.

**Comment by lkysow** [comment]
We're in that file now so I think this can be closed?

**Comment by fejta** [comment]
Adding people to the OWNERS file does not make them repo collaborators, which is required in order for github to allow assigning them.

**Comment by lkysow** [comment]
How do we get people invited?

**Comment by fejta** [comment]
A repo or org admin needs to do this. Or the org can agree to use peribolos.

I help manage prow.k8s.io but otherwise minimally involved with the helm org.
