### ISSUE TITLE
Bump dependency version on dependent charts: mariadb 0.6.2

### ISSUE THREAD

**Issue by scottrigby** [helm/charts#1051]
## Method
PRs opened using my dependency version bump utility script (see https://github.com/kubernetes/helm/issues/1947), because https://github.com/kubernetes/helm/pull/2041 is not ready yet (also see https://github.com/kubernetes/helm/issues/2205 for future issue discussion).

## PRs to review
- [x] drupal #1109 
- [x] ghost #1110 
- [x] jasterreports #1111  
- [x] jooma #1112  
- [x] magento #1113  
- [x] mediawiki #1114  
- [x] moodle #1115  
- [x] opencart #1116  
- [x] orangehrm #1117  
- [x] osclass #1118  
- [x] owncloud #1119  
- [x] phabricator #1120  
- [x] phpbb #1121  
- [x] prestashop #1122  
- [x] redmine #1123  
- [x] testlink #1124  
- [x] wordpress #1125

**Comment by viglesiasce** [comment]
cc  @prydonius

**Comment by scottrigby** [comment]
@prydonius I updated the PRs and links in this issue to mariadb 0.6.2.

**Comment by scottrigby** [comment]
@prydonius ah, I just noticed all the PRs you incremented the version on each chart as well. This makes sense… I should also add that to the dependency version bump script, right (increment up the chart version itself)?

**Comment by prydonius** [comment]
@scottrigby that would be awesome, thanks!

**Comment by prydonius** [comment]
These are all merged now, thanks @scottrigby!
