### ISSUE TITLE
[inclubator/kafka] Accessing Kafka outside kubernetes not working

### ISSUE THREAD

**Issue by lagorsse** [helm/charts#10526]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
inclubator/kafka

**What happened**:
with kafka-console-producer.bat I got error
Connection to node -1 could not be established or Timeout
I am not sure if I am supose to use Node Cluster IP and port or localhost so I tried both

Then I updated the chart with helm repo update

Now I am getting this error:
Error: render error in "kafka/templates/service-brokers-external.yaml": template: kafka/templates/service-brokers-external.yaml:11:27: executing "kafka/templates/service-brokers-external.yaml" at <index $root.Values.e...>: error calling index: index out of range: 0

**What you expected to happen**:
No error and then able to connect outside of cluster, I need this for development environment

**How to reproduce it** (as minimally and precisely as possible):
Windows 10
helm repo update
helm install --name kafka-test-4 --namespace dev --set external.enabled=true,external.firstListenerPort=33090 incubator/kafka

**Anything else we need to know**:

**Comment by rishisharmamt** [comment]
The issue has already been fixed in earlier release.
@lagorsse can you confirm which chart version of kafka are you using ?

**Comment by lagorsse** [comment]
No Idea, I have clean up my helm release and reinstall a few days ago, I will retry today.

**Comment by chris-malloy-mri** [comment]
I'm having the same issue. There are a few duplicate tickets related to this, and none of the provided workarounds have done the trick for me yet.

**Comment by lagorsse** [comment]
kafka pod doesn't start anymore so it's worst than before, it's really a pain to develop without this.

**Comment by lagorsse** [comment]
It doesn't work on my local windows cluster and on google cloud, I tried with rbac as mention in the other issue.
helm install --namespace dev --name kafka --set prometheus.kafka.enabled=true,external.enabled=true,rbac.enabled=true incubator/kafka

I don't have much information to debug as log is empty
Error from server (BadRequest): container "kafka-broker" in pod "kafka-0" is waiting to start: PodInitializing

my worker is constantly restarting Back-off restarting failed container

**Comment by chris-malloy-mri** [comment]
Bump

**Comment by agolomoodysaada** [comment]
Documentation would be helpful here. Laying out some best practices for external connectivity as well as sample configuration would be super helpful. Recent changes such as https://github.com/helm/charts/commit/d83478b793f5d4ed620ee3e5a9cb01dd8755d719 without documentation make things really complicated for upgrades.
