### ISSUE TITLE
[stable/wordpress] pod restart causes wordpress to reinitialize.

### ISSUE THREAD

**Issue by nickjackson** [helm/charts#1054]
We are having an issue with stable/wordpress on Google Container Engine using persistent volumes.

The directory `/bitnami/wordpress` seems to be overwritten every time the pod restarts, and as a result wordpress seems to forget its previous config, and run through the `wp_install` process again. Saving a file within the root `/bitnami` dir, will be persisted.

The database is unaffected, and as result of the above issue we get repeat "Hello World!" wordpress posts.

I've tried the bitnami/wordpress using the docker-compose solution and this is unaffected, it appears to be an issue with the GCE PD / kubernetes volume claim.

**Comment by prydonius** [comment]
@nickjackson looks like this might be the same issue @bcorijn ran into - can you give the fix in #1053 a try to see if it works for you?

**Comment by nickjackson** [comment]
Yes will give it a try. Looks like it'll do the job.

**Comment by bcorijn** [comment]
Yeah, exact same issue I was seeing. The bitnami wordpress image is set up to make volumes for `/bitnami/wordpress`, `/bitnami/apache` and `/bitnami/php`. The chart on the other hand mounted a persistent volume under `/bitnami`. Docker treats those as different things, causing only an empty state to be persisted.

**Comment by nickjackson** [comment]
Yeah confirmed. Its definitely that.

**Comment by nickjackson** [comment]
Closing in favour of #1053
