### ISSUE TITLE
Migrating stable/elasticsearch charts out of helm/charts

### ISSUE THREAD

**Issue by rendhalver** [helm/charts#10543]
**FEATURE REQUEST**:

We would like to migrate the Elastic charts out of helm/charts.

But first some back story.
At  KubeCon in Seattle last year I ran into @jethr0null at the Elastic stand who is in charge of the effort to build Helm Charts for the Elastic suite.
We had a chat where she let me know  Elastic had their own Chart for deploying an Elasticsearch cluster into Kube and she wanted my opinion on them.

Today @jethr0null, @Crazybus and I had the first chat on how we would go about migrating people over to the Elastic Charts.

The first task on our list was to open a discussion with the community on how to proceed.
The second task is to write up a migration plan for people wanting to switch over.
There will be other tasks along the way but lets start there.

Elastic has already added their Chart repo to Helm Hub if you want to check them out.

If anyone has any concerns or comments this is the place to make them so we can work out how best to do this as the awesome community that we are.

**Comment by Towmeykaw** [comment]
Will elastic create an operator? If they are that would be a good time to migrate 😊

**Comment by Towmeykaw** [comment]
@jethr0null Ok good to know. Then it would be good to switch over earlier. Is it possible to just stop the old chart and keep pvs and then spin up again using the same pvs?

**Comment by rendhalver** [comment]
Working out that migration plan is the next step. At this stage I am not sure and we will need to test that process to see if it works.

**Comment by Towmeykaw** [comment]
Alright. I have to set up a test cluster next week so will try to do an upgrade and see what happens.

**Comment by rendhalver** [comment]
Thanks @Towmeykaw! Please let us know how that goes!

**Comment by desaintmartin** [comment]
I would love to spend some time to compare the two different approaches and give feedback. I hope I can do this in a few days.
In the end, I think it makes perfect sense for Elastic to maintain, with the help of the community, the Helm Chart.

**Comment by Towmeykaw** [comment]
I found one difference when deploying the elastic chart. When we use the stable chart we get one PVC per master and one PVC per data node. But the elastic chart only has masters which i guess contains all data. Not sure if that will be a problem. We would also need a way to specify an existing PV when creating the PVCs.

**Comment by rendhalver** [comment]
That is something we will need to address in the migration plan.

**Comment by Crazybus** [comment]
> But the elastic chart only has masters which i guess contains all data.

@Towmeykaw The chart doesn't use hardcoded types of nodes. Instead it is possible to deploy multiple releases with whatever roles you want and join them together. There are [notes](https://github.com/elastic/helm-charts/tree/master/elasticsearch#usage-notes-and-getting-started) about this in the readme and you can also look at the [multi example](https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/multi) to get a better idea of how it works. So yes, it is very much possible (and encouraged) to have separate master and data nodes. 

> We would also need a way to specify an existing PV when creating the PVCs.

This is something I still need to experiment to see if it is possible. If it isn't the plan is to try to join the new cluster to an existing cluster and sync the data across that way.

**Comment by Towmeykaw** [comment]
Ohh totally missed that part. Will try again and see if I can get it to work

**Comment by rendhalver** [comment]
I used the example chart in elastic/helm-charts#22 locally to deploy our new clusters and it worked very well.

**Comment by desaintmartin** [comment]
Not stale.

**Comment by desaintmartin** [comment]
Not stale.

**Comment by desaintmartin** [comment]
Not stale.
What is the status of this? charts.git elasticsearch release is doing great, how should we work to converge the two charts?

**Comment by jethr0null** [comment]
@desaintmartin I'm not sure if you saw, but the migration guide @Crazybus was working on has been merged into the Elastic chart repo. 

I'm thinking a call (or zoom?) to map out the next steps could be helpful. I believe @rendhalver is unavailable this week and @Crazybus and I are at traveling for work next week. Would you (and any of the other maintainers) be open to chatting the week of May 20th? If so, I can set something up and send out invites.

**Comment by desaintmartin** [comment]
Unfortunately, I'll be at kubecon Europe the week of May 20th.
I'll be available the week after or... At kubecon itself!

But having a call with all (most?) maintainers would be really nice in order to prepare the next steps.

**Comment by jethr0null** [comment]
Ah, excellent point. Let's shoot for the week after (week of the 27th). I won't be at Kubecon Europe, but I believe @Crazybus is be attending. Perhaps you two can connect there as well.

**Comment by Crazybus** [comment]
> Unfortunately, I'll be at kubecon Europe the week of May 20th.
I'll be available the week after or... At kubecon itself!

Yup I will also be there! If anyone else wants to come and say hi I'll be at the Elastic booth.

**Comment by desaintmartin** [comment]
Not stale.

**Comment by jethr0null** [comment]
Not stale.

**Comment by jethr0null** [comment]
Not stale.

**Comment by rendhalver** [comment]
Not stale!

**Comment by jethr0null** [comment]
Not stale.

**Comment by jethr0null** [comment]
Not stale. 

@rendhalver would you mind reopening this issue when you have a moment? Thanks so much.

**Comment by HaveFun83** [comment]
Any news here?

**Comment by desaintmartin** [comment]
I'm ok to deprecate it, possibly still making fixes (like I've done a few days agos) but no new feature.

**Comment by desaintmartin** [comment]
Should we go forward and officially deprecate this chart? I still see some new people using it instead of the elastic/charts.

**Comment by scottrigby** [comment]
All the elastic charts have not been officially deprecated in `stable` yet: https://github.com/elastic/helm-charts#charts

Linking https://github.com/helm/charts/issues/21103 so we can track this before November 13 https://github.com/helm/charts/blob/master/README.md#deprecation-timeline

**Comment by bridgetkromhout** [comment]
All the elastic charts listed on https://github.com/elastic/helm-charts#charts point to Elastic's own GitHub org, and the elastic-related charts in this repo are deprecated.
