### ISSUE TITLE
Concourse to postgres dependency should be optional

### ISSUE THREAD

**Issue by william-tran** [helm/charts#1056]
As a user, I would like to bring my own postgres instead of using a chart dependency.

**Comment by william-tran** [comment]
@frodenas Any input on how to do this before I submit a PR? Here's what we have so far: https://github.com/autonomic-ai/charts/commit/8608a487d680bcb0b08ef30aac5b7796ead635e7

**Comment by frodenas** [comment]
@william-tran Apologies for the late reply. I've been disconnected from this repo for a while, so unsure how conditionals work. If you were able to test your changes, submit a PR, I'll try to do some tests in the meantime.

**Comment by william-tran** [comment]
It's working out great plugging in our own RDS based postgres, but we're having other issues with runaway disk usage, though I have my workers not using PersistentVolumes. I'll send a PR once I can verify the whole setup is stable.

**Comment by alexisvincent** [comment]
@william-tran any progress on this?

**Comment by william-tran** [comment]
We were concerned over the stability of the version of Concourse we were
using (3.0.1) but it's been stable for us for a week. The stability issues
had nothing to do with postgres, but with the `btrfs` that workers were
using that would cause the fs to panic and go read only. We have a recovery
process for that case that I can include in the readme. I'll send over that
PR shortly.

On Jun 12, 2017 5:02 PM, "λex Vincent" <notifications@github.com> wrote:

@william-tran <https://github.com/william-tran> any progress on this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/charts/issues/1056#issuecomment-307928106>,
or mute the thread

**Comment by william-tran** [comment]
@alexisvincent @frodenas PR submitted
