### ISSUE TITLE
[stable/sonarqube] Plugins are not copied to their location?

### ISSUE THREAD

**Issue by mrdfuse** [helm/charts#10575]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.9.1
Kubernetes 1.11.5

**Which chart**:
stable/sonarqube

**What happened**:
I specified some plugins to install in my values file:
```
plugins:
  install:
    - "https://github.com/stevespringett/dependency-check-sonar-plugin/releases/download/1.1.3/sonar-dependency-check-plugin-1.1.3.jar"
    - "https://github.com/spotbugs/sonar-findbugs/releases/download/3.9.1/sonar-findbugs-plugin-3.9.1.jar"
```
They get downloaded by the init container, however they are put in a tmp folder. The copy-plugins.sh script that is also mounted is never called? So after starting SonarQube the plugins are not installed, only downloaded in a tmp folder.

**What you expected to happen**:
I expect the copy-plugins.sh script to be called somewhere during start, so that the plugins are installed on boot.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by mrdfuse** [comment]
Looks like this is related to https://github.com/helm/charts/pull/10510?

**Comment by melissapalmer** [comment]
Yes  #10510 will correct the above issue.
