### ISSUE TITLE
[stable/rabbitmq] Ingress does not expose amqp port.

### ISSUE THREAD

**Issue by rishisharmamt** [helm/charts#10571]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
helm version: 
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}

kubernetes version:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:38Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**: stable/rabbitmq

**What happened**: ingress for amqp port not exposed

**What you expected to happen**: ingress should be available for amqp port

**How to reproduce it** (as minimally and precisely as possible): install the helm with ingress.enabled=true. The ingress is exposed for management UI.

**Anything else we need to know**:

**Comment by javsalgar** [comment]
Hi,

Thanks for opening the ticket. I am not a RabbitMQ expert, but I think the AQMP port is not HTTP nor HTTPS, could you confirm that? If it is not HTTP or HTTPS, exposing them in Ingress would not work, as it is meant to be used for this kind of traffic.

**Comment by javsalgar** [comment]
A small test using curl:

```
2019-01-14 12:36:32.956 [info] <0.715.0> accepting AMQP connection <0.715.0> (127.0.0.1:54996 -> 127.0.0.1:5672)
2019-01-14 12:36:32.956 [error] <0.715.0> closing AMQP connection <0.715.0> (127.0.0.1:54996 -> 127.0.0.1:5672):
{bad_header,<<"GET / HT">>}
```

**Comment by rishisharmamt** [comment]
Hi @javsalgar , Yes, the AMQP port is not HTTP or HTTPs. AMQP is application layer protocol over TCP. So, they can't be exposed as Ingress.
Sorry, I missed the fact that only HTTP can be routed using Ingress.
Thank you for looking at the issue. Closing the issue as it is not a bug.
