### ISSUE TITLE
[stable/prometheus-operator] adding new grafana plugins

### ISSUE THREAD

**Issue by justingosan** [helm/charts#10599]
**Is this a request for help?**: Yes

**Version of Helm and Kubernetes**:
helm: v2.12.1
kubernetes: v1.11.5

**Which chart**: [stable/prometheus-operator]

Hi! is there any way to add new grafana plugins to this chart after install?

**Comment by rewt** [comment]
Plugins can be configured in the values:

`  plugins:
  # - digrich-bubblechart-panel
  # - grafana-clock-panel`

**Comment by rewt** [comment]
Exactly, just remember to remove those comment tags so like:

```
grafana:
  plugins:
  - digrich-bubblechart-panel
  - grafana-clock-panel
```
