### ISSUE TITLE
Add Option to Provide Annotations for Service Resource in Chart stable/ghost

### ISSUE THREAD

**Issue by dumrauf** [helm/charts#10595]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

It's already possible to add `annotations` to the `ingress` resource in the `stable/ghost` chart. Would it be possible to also add `annotations` to the `service` resource?

This is required when using the BackendConfig custom resource to configure Cloud Content Delivery Network (Cloud CDN) in Google Kubernetes Engine; see also https://cloud.google.com/kubernetes-engine/docs/how-to/cdn-backendconfig#creating_a_service for an example.

I can imagine that this could be achieved by adding the following lines to `svc.yaml`
```
  {{- if .Values.service.annotations }}  
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
```

**Which chart**: stable/ghost

**Anything else we need to know**: Thanks and keep up the great work!

**Comment by javsalgar** [comment]
Thanks for the request, here is the PR: https://github.com/helm/charts/pull/10608

**Comment by dumrauf** [comment]
Splendid. Well done and thanks for the quick turn around time! Much appreciated!

And you've also taught me something about empty dictionaries in YAML as well...!
