### ISSUE TITLE
PostgreSQL reported as ready before restart after user scripts

### ISSUE THREAD

**Issue by neerolyte** [helm/charts#10627]
**Is this a request for help?**: No.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

```
$ helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

https://github.com/helm/charts/tree/master/stable/postgresql @ 3.9.1.

**What happened**:

Using the default PostgreSQL chart I'm seeing `kubectl wait --for=condition=Ready pod/"$name"-postgresql-0` report the pod as ready before the user entrypoint is executed e.g

```
Sourcing /docker-entrypoint-initdb.d/createdb.sh
[...]
+ nami stop postgresql
+ nami start --foreground postgresql
2019-01-15 05:11:35.238 GMT [108] LOG:  received fast shutdown request
2019-01-15 05:11:35.251 GMT [108] LOG:  aborting any active transactions
2019-01-15 05:11:35.253 GMT [108] LOG:  worker process: logical replication launcher (PID 116) exited with exit code 1
2019-01-15 05:11:35.253 GMT [111] LOG:  shutting down
2019-01-15 05:11:35.291 GMT [108] LOG:  database system is shut down
```

logs after the pod is supposedly already ready, meaning any install process that's kicked off and depends on the DB immediately after it's ready will fail as the DB will shutdown part way through.

**What you expected to happen**:

The readiness probe should only indicate ready once the second startup has completed.

**How to reproduce it** (as minimally and precisely as possible):

```
check() {
    echo "Installing chart"
    helm install  --name=foo --set initdbScripts.create\\.sql="create role foo login password 'foo'; create database foo owner foo;" --set readinessProbe.periodSeconds=1 --set readinessProbe.initialDelaySeconds=1 --set livenessProbe.periodSeconds=1 --set livenessProbe.initialDelaySeconds=1 stable/postgresql
    echo "Waiting for pod to become Ready"
    while ! kubectl wait --for=condition=Ready pod/foo-postgresql-0; do
        sleep 1
    done
    echo "Attempting first psql connection"
    kubectl exec -it foo-postgresql-0  -- sh -c 'PGPASSWORD=foo psql --host 127.0.0.1 -U foo -tc "select version();"'
    sleep 10
    echo "Attempting second psql connection"
    kubectl exec -it foo-postgresql-0  -- sh -c 'PGPASSWORD=foo psql --host 127.0.0.1 -U foo -tc "select version();"'
}; check
```

Running the above should show something like:

```
... helm chart stuff ...
Waiting for pod to become Ready
pod/foo-postgresql-0 condition met
Attempting first psql connection
psql: FATAL:  password authentication failed for user "foo"
command terminated with exit code 2
Attempting second psql connection
 PostgreSQL 10.6 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1
) 6.3.0 20170516, 64-bit
```

The lowered delays are not strictly needed to hit the race condition, but they do make it show up more often.

**Anything else we need to know**:

Doesn't seem to be an issue if `initdbScripts` is left unconfigured.

It can be useful to monitor logs in another terminal preemptively e.g `while true; do kubectl logs -f foo-postgresql-0; sleep 1; done`.

**Comment by tompizmor** [comment]
Thanks for reporting the issue and for the steps to reproduce it. 
We will take a look at the possible options and update the issue once we have more information. 

One option can be disabling PostgreSQL remote connections until the end but we can not do that if the user mounts its own configuration via configMap as it will be read-only so we may need to think on something else.

**Comment by tompizmor** [comment]
Still unresolved

**Comment by tompizmor** [comment]
Still unresolved

**Comment by tompizmor** [comment]
Still unresolved

**Comment by tompizmor** [comment]
Unresolved yet. I plan to take a look in the following days

**Comment by tompizmor** [comment]
This issue should be fixed now @neerolyte!
