### ISSUE TITLE
[stable/prometheus-operator] Allow Grafana Anonymous Access

### ISSUE THREAD

**Issue by rewt** [helm/charts#10622]
It looks as though [anonymous access was configured in the `coreos` repo](https://github.com/coreos/prometheus-operator/blob/f93df14b658ef2588adcd968716389ceba23b833/helm/grafana/templates/grafana-deployment.yaml#L28), but hasn't been implemented in `helm` repo.

I'm noticing there isn't a `grafana-deployment.yaml` in `helm` repo, so wondering how things are currently setup?

It'd be great to allow anonymous access somehow.  Anyone have it figured out?

**Comment by krekac** [comment]
Below find my setup for the anonymous access in values.yaml. It is read-only access with possibility to sign in (e.g. admin or other users).

grafana:
  grafana.ini:
    users:
      viewers_can_edit: false
    auth:
      disable_login_form: false
      disable_signout_menu: false
    auth.anonymous:
      enabled: true
      org_role: Viewer

**Comment by rewt** [comment]
Dang finally!  I must've had formatting off or something, because I tried this before and failed.

Thank you!
