### ISSUE TITLE
[stable/mariadb] Assign service account via chart values

### ISSUE THREAD

**Issue by tylercamp** [helm/charts#10678]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Version of Helm and Kubernetes**: 2.11.0 / 1.10

**Which chart**: mariadb/stable

**What happened**:  I'm [contributing to a chart for Code Dx](https://github.com/codedx/codedx-kubernetes/tree/develop) that depends on MariaDB, and we're attempting to provide as many security options as is reasonable in a chart. Part of this is including a `PodSecurityPolicy`. In environments where PSPs are enabled, Code Dx will be able to launch fine, but our dependency MariaDB will not. As a shim, we've provided a MariaDB PSP and options for assigning the service name, and output the relevant `kubectl patch` commands to update the `StatefulSets`. This is relatively cumbersome and leads to some unnecessary initialization time, as the first MariaDB pods are created then destroyed after patching with the service account.

**What you expected to happen**: MariaDB would have a `serviceAccountName` property (and relevant properties ie `create: true`) in its `values.yaml` that we could reference.

**Anything else we need to know**: I've avoided modifying the chart directly (currently locally cloned in the repo) but will likely be making a pull request some time in the next two weeks.

**Comment by juan131** [comment]
Hi @tylercamp 

Thanks for sharing this feature request. I agree we should support it in the MariaDB chart.

Would you rather do the PR yourself? I'm glad to be your reviewer once you do it.

/assign @juan131

**Comment by tylercamp** [comment]
Hey @juan131 

Thanks for the response; I don't have any preference to the implementer, and am willing to make the pull request if necessary. I'd like the change sooner than later but I'm sure everyone is busy with their own work.

**Comment by juan131** [comment]
Hi @tylercamp 

I just created a PR to address this issue. Feel free to take a look at it.

**Comment by tylercamp** [comment]
Hey @juan131 

Thanks for the quick turnaround! I might be missing something, but it doesn't seem like setting `serviceAccount.create=true` actually creates the service account. Of course, I can make the SA in our chart, though it would be more appropriate for the MariaDB chart to handle that itself. Otherwise this is what I needed.
