### ISSUE TITLE
[stable/sonarqube] Add secrets

### ISSUE THREAD

**Issue by elijahsgh** [helm/charts#10675]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Version of Helm and Kubernetes**: 2.12.1, 1.10

**Which chart**: stable/sonarqube

**What happened**: I cannot specify a mapping for secrets for env vars and I cannot specify a secret to source sonarqube.properties from

**What you expected to happen**: I would like a way to store secrets (such as ldap password) and reference them from the chart

**Anything else we need to know**:

I can open a PR with secretEnvs or similar properties if necessary, but I wanted to start the conversation first.

Thank you!

**Comment by jcoeltjen** [comment]
Hi @tamarintech ,

I am currently working on a feature that may helps you.
My approach is it to add an option to mount a secret as the `sonar-secret.txt` used for [Settings Encryption](https://docs.sonarqube.org/latest/instance-administration/security/#header-6).
This way we can use encrypted settings (in my case `ldap.bindPassword`) in the sonar.properties file.
