### ISSUE TITLE
[stable/nginx-ingress] Configure AWS L7 ELB with SSL termination

### ISSUE THREAD

**Issue by e-jjj** [helm/charts#10688]
**Is this a request for help?**: Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): General Guidance

**Version of Helm and Kubernetes**:
KUBERNETES_VERSION: 1.8.6
HELM_VERSION: 2.7.0

**Which chart**: stable/nginx-ingress

**What happened**: Don't know the right place to annotate the controller with the values as shown in the instructions below, in order to terminate ssl connections in the AWS ELB.
 
https://github.com/helm/charts/tree/master/stable/nginx-ingress#aws-l7-elb-with-ssl-termination

**What you expected to happen**:
Add the annotations in the values.yaml. There are different places in this file to add them, not sure where exactly.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
Need to add the ssl certs to the aws load balancer created by the nginx ingress chart. It is not clear where or how the annotations mentioned here should be added/configured

https://github.com/helm/charts/tree/master/stable/nginx-ingress#aws-l7-elb-with-ssl-termination

Thanks!

**Comment by Towmeykaw** [comment]
They should be added at controller.service.annotations

**Comment by sysnasri** [comment]
I have an odd problem, these annotions wont be added to the service annotation! 
```
set {
    name  = "service.type"
    value = "LoadBalancer"

  }
  set {
    name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-backend-protocol"
    value = "http"
  }
  set {
    name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-ssl-ports"
    value = "https"
  }
  set {

    name  = "controller.service.annotations.service\\.ingress\\.kubernetes\\.io/ssl-redirect"
    value = "true"

  }
  set {
    name  = "controller.service.annotations.service\\.ingress\\.kubernetes\\.io/force-ssl-redirect"
    value = "true"
  }
  set {
    name  = "controller.service.annotations.service\\.ingress\\.kubernetes\\.io/rewrite-target"
    value = "/"
  }
  set {
    name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-ssl-cert"
    value = aws_acm_certificate.upday-cert.arn
  }
```
