### ISSUE TITLE
[rabbitmq-ha] change disk space limit from values

### ISSUE THREAD

**Issue by mmailhos** [helm/charts#10681]
**Feature Request**

**Version of Helm and Kubernetes**:
Helm: v2.10.0
Kubernetes: v1.10.7

**Which chart**:
```
rabbitmq-ha
appVersion: 3.7.8
version: 1.17.0
```

**What happened**:

There is a hard disk limit set to 50MB for each pod. We can however choose persistent volume and set it to a higher value (`persistentVolume.size`) but the hard limit is probably going to be a bottleneck at a point when RabbitMQ will be trying to swap for more than 50MB.

**What you expected to happen**:

We should be able to specify disk limit for RabbitMQ, the same way we specify memory alerts with:
```
# https://www.rabbitmq.com/memory.html
rabbitmqMemoryHighWatermark: 256MB
rabbitmqMemoryHighWatermarkType: absolute
```
But for: https://www.rabbitmq.com/disk-alarms.html

**How to reproduce it** (as minimally and precisely as possible):

GET /metrics on the rabbitmq exporter metric with the default chart:
```
rabbitmq_node_disk_free_limit{node="rabbit@rabbitmq-rabbitmq-ha-0.rabbitmq-rabbitmq-ha-discovery.ops.svc.cluster.local"} 5e+07
```

**Comment by Towmeykaw** [comment]
Isn't that limit that when it has less than 50mb it will stop receiving messages to prevent starvation of the system?

**Comment by steven-sheehy** [comment]
As @Towmeykaw mentions this is not the limit of the size of the disk, but instead how much _free disk space_ must be available. If it goes under 50MB, then a disk alarm will be triggered and it will stop receiving messages.

Also, this setting can already be adjusted if need be:
```yaml
extraConfig: |
  disk_free_limit.absolute = 1GB
```

**Comment by MathieuMailhos** [comment]
I have done tested that `extraConfig` variable and it works: `disk resource limit alarm has been set on node xx` and this is indeed the minimum disk space that must be available for the node to receive messages.
It could have had the same syntax as the memory variable though but that works for me like that. Thanks!
