### ISSUE TITLE
[stable/elasticsearch] plugins are not persistent 

### ISSUE THREAD

**Issue by mmailhos** [helm/charts#10685]
**Bug Report**

**Version of Helm and Kubernetes**:

Version of Helm and Kubernetes:
Helm: v2.10.0
Kubernetes: v1.10.7

**Which chart**:

stable/elasticsearch
version: 1.15.4
appVersion: 6.5.4

**What happened**:

Plugins require the service to restart. However, they are not persistent across reboot.
This means that the plugin can never be installed.

**What you expected to happen**:

Installing a plugin should be written on disk and be persistent across reboot.

**How to reproduce it** (as minimally and precisely as possible):

Run `./bin/elasticsearch-plugin install repository-s3` on an elasticsearch-client.
Delete the pod to simulate a service restart.
Run `./bin/elasticsearch-plugin install repository-s3` again and the plugin should still be installed.

**Anything else we need to know**:

The plugin is persistent on the elasticsearch-data node as it is a statefulset. However, there is no way to use it as it does not exist on the endpoint, on elasticsearch-client.

```
 curl -vvv -X PUT http://elasticsearch-client:9200/_snapshot/my_snapshots -H 'Content-Type: application/json'  -d '{"type":"s3", "settings": {"bucket": "mybucket"}}'

{"error":{"root_cause":[{"type":"repository_exception","reason":"[my_snapshots ] repository type [s3] does not exist"}],"type":"repository_exception","reason":"[my_snapshots ] repository type [s3] does not exist"},"status":500}
```
Indeed, I can re-install the s3 repo plugin from restarted pods.

elasticsearch-client stack trace indicated:
```
Caused by: org.elasticsearch.repositories.RepositoryException: [my_snapshots] repository type [s3] does not exist
```

**Comment by hustshawn** [comment]
@MathieuMailhos you can customise your ES image with plugin installed, and reuse this chart.

**Comment by MathieuMailhos** [comment]
Simple enough, that works for me

```
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
RUN ./bin/elasticsearch-plugin install -b repository-s3
```
