### ISSUE TITLE
[stable/kubernetes-dashboard] 1.1.0 unreachable from proxy

### ISSUE THREAD

**Issue by rfvermut** [helm/charts#10714]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 2.11.0, 1.11.0

**Which chart**: stable/kubernetes-dashboard 1.0.1, 1.1.0

**What happened**: after upgrading to 1.0.1 or 1.1.0 opening http://localhost:8877/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/node gives me
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"https:kubernetes-dashboard:\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```
```
kubectl -n kube-system describe service kubernetes-dashboard
Name:              kubernetes-dashboard
Namespace:         kube-system
Labels:            app=kubernetes-dashboard
                   chart=kubernetes-dashboard-1.0.1
                   heritage=Tiller
                   kubernetes.io/cluster-service=true
                   release=kubernetes-dashboard
Annotations:       <none>
Selector:          app=kubernetes-dashboard,release=kubernetes-dashboard
Type:              ClusterIP
IP:                10.100.179.254
Port:              https  443/TCP
TargetPort:        8443/TCP
Endpoints:         172.31.225.162:8443
Session Affinity:  None
Events:            <none>
```

**What you expected to happen**: dashboard to appear in browser. Version 0.10.2 works!
```
kubectl -n kube-system describe service kubernetes-dashboard
Name:              kubernetes-dashboard
Namespace:         kube-system
Labels:            app=kubernetes-dashboard
                   chart=kubernetes-dashboard-0.10.2
                   heritage=Tiller
                   kubernetes.io/cluster-service=true
                   release=kubernetes-dashboard
Annotations:       <none>
Selector:          app=kubernetes-dashboard,release=kubernetes-dashboard
Type:              ClusterIP
IP:                10.100.179.254
Port:              <unset>  443/TCP
TargetPort:        8443/TCP
Endpoints:         172.31.225.162:8443
Session Affinity:  None
Events:            <none>
```

The only visible difference is `Port` line. Pods are up and running both versions.

**How to reproduce it** (as minimally and precisely as possible): helm install kubernetes-dashboard 1.0.1 or 1.1.0. start `kubectl proxy`. Open dashboard url.

**Anything else we need to know**: EKS cluster (AWS). default values except for rbac.clusterAdminRole=true.

**Comment by grantwra** [comment]
Running into this as well. Only occurs with the helm installation of the dashboard. Installing directly from the repo (https://github.com/kubernetes/dashboard) works.

**Comment by alex-hempel** [comment]
Same problem with 1.2.0.

I tried to explicitly set the ports by adding 
`--set=service.externalPort=443`

And while kubectl describe gives me this result:

```Name:              kubernetes-dashboard
Namespace:         kube-system
Labels:            app=kubernetes-dashboard
                   chart=kubernetes-dashboard-1.2.0
                   heritage=Tiller
                   kubernetes.io/cluster-service=true
                   release=illocutionary-grizzly
Annotations:       <none>
Selector:          app=kubernetes-dashboard,release=illocutionary-grizzly
Type:              ClusterIP
IP:                100.67.132.133
Port:              https  443/TCP
TargetPort:        8443/TCP
Endpoints:         10.27.120.0:8443
Session Affinity:  None
Events:            <none>```


I can't use kubectl proxy to connect to the dashboard. The error is the same as described by @rfvermut

**Comment by spingel** [comment]
It appears that the port is now named "https" whereas before it did not have a name. It works for me if I use the following URL (note the extra https):

http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:https/proxy/#!/login

**Comment by alex-hempel** [comment]
Yes, that appears to be correct. Here, the helm chart deviates - if the dashboard is deployed the non-helm way, the port is not named. I am not sure how wise that is, but I am fairly new to Helm.

**Comment by rfvermut** [comment]
Well, I'd say it's all documented in the [README](https://github.com/helm/charts/tree/master/stable/kubernetes-dashboard#using-the-dashboard-with-kubectl-proxy), so I'm closing this.
