### ISSUE TITLE
[stable/nginx-ingress] extraArg can not be a false boolean

### ISSUE THREAD

**Issue by florianrusch** [helm/charts#10712]
**Is this a request for help?**: Yes and No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
```Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Which chart**: stable/nginx-ingress

**What happened**:
We tried to set the command line argument `--enableSSLChainCompletion false` on the nginx controller. For this we added `--set controller.extraArgs.enable-ssl-chain-completion=false` on the `helm install` command. Sadly only `--enableSSLChainCompletion` was set on the pod without `false`. We've also test to surround the `false` with some double ticks: `"false"` ... same result.

The only way to configure this was to edit the `deployment` via `kubectl edit`.

**What you expected to happen**:
That we can set the command line arguments to a boolean on the nginx controller.

**How to reproduce it** (as minimally and precisely as possible):
Try to set a command line argument to a boolean on the nginx controller. ;-)

**Anything else we need to know**:
This issue seams to be related to this line in the deployment ressource of the nginx-controller:
https://github.com/helm/charts/blob/4f3d5e25557ba68e43c2632d9f919c25c960be2d/stable/nginx-ingress/templates/controller-deployment.yaml#L77

**Comment by pinnymz** [comment]
This may be related to https://github.com/helm/charts/issues/9586

**Comment by florianrusch** [comment]
This is a duplicate issue – the other issue can be found here: #9586 

Workaround for all googlers:
```
--set-string controller.config.ssl-redirect=false
```
