### ISSUE TITLE
[stable/openvpn] unable to route to the other pods or services from client

### ISSUE THREAD

**Issue by adolli** [helm/charts#10749]
**Is this a request for help?**: Yes.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
```bash
# helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:  `stable/openvpn`

**What happened**: 
I run a command from client side. `ping 10.244.1.100` which is the ip address of another pod not the openvpn pod itself. This results in request timeout. I am sure there are no firewalls as I can ping inside the openvpn pod to any other pods. And also the routes for 10.244.0.0/16 has already added.

**What you expected to happen**:  
Be able to ping to any other pods.

**How to reproduce it** (as minimally and precisely as possible):
Simply run ping command.

**Anything else we need to know**:
I found that if I run the openvpn container in privileged mode with flag `--privileged` and run `sysctl -w net.ipv4.ip_forward=1` will solve this issue.

Thx!

**Comment by ntfs32** [comment]
yes I found this charts just add capabilities -NET_ADMIN  but, net.ipv4.ip_forward is disabled, we must up it by self.
it`s need update configure.sh set  `
sysctl -w net.ipv4.ip_forward=1`
?

**Comment by adolli** [comment]
https://github.com/helm/charts/pull/11852?w=1 I made a PR.

**Comment by ntfs32** [comment]
@adolli #11827 a same pr wait merge.

**Comment by adolli** [comment]
aha, i didnot notice that. forget about me

**Comment by adolli** [comment]
remove stale
