### ISSUE TITLE
Remove MongoDB - License issue

### ISSUE THREAD

**Issue by pierreozoux** [helm/charts#10785]
As [RedHat and Debian removed MongoDB](https://www.zdnet.com/article/mongodb-open-source-server-side-public-license-rejected/) from their catalog, I think we'll have to do the same here.

Does anybody has access to a lawyer to answer these questions?

As a consequence, we'll need to remove all project that depend on it as a default option.

**Comment by beltran-rubo** [comment]
Hi @pierreozoux, AFAIK there is not any issue about having MongoDB published in this repo. There is no requirement for the software package to be open source e.g. there is one for MSSQL available https://github.com/helm/charts/tree/master/stable/mssql-linux

**Comment by steven-sheehy** [comment]
I am one of the maintainers of the mongodb-replicaset chart. I am against removing MongoDB from this repository. All the charts in this repository are licensed under the Apache license and no MongoDB code or binaries are stored here. So even if there was any issue with MongoDB's license, it's not applicable because the charts are separate from the applications they run that are stored in a docker registry.

cc @unguiculus

**Comment by unguiculus** [comment]
IANAL, but I don't see any issue either and fully agree with @steven-sheehy.

**Comment by pierreozoux** [comment]
I guess then this issue depends on
 - https://github.com/docker-library/mongo/issues/324
 - https://github.com/bitnami/bitnami-docker-mongodb/issues/129

What if these repo remove MongoDB support, where will you host the docker image? (I can see that you already use personal repos, and I have to admit that this worries me a bit).

What is the strategy to warn users about the change from open source to proprietary software? I think it is important to manage our users expectations.
Maybe we can use a `acceptEula.value` flag, or `acceptProprietaryLicense.value` that default to false so users are aware.

I'm a hoster myself, and this worries me, event though i think my whole infrastructure is free software.
@steven-sheehy do you use this chart personally or in a professional context? If you use it in a professional context, what is the strategy of your company on this topic?

I'm very curious, and these are questions I think are important to answer.
