### ISSUE TITLE
Is there any way to add ssh-key-secret to master pod for private git access

### ISSUE THREAD

**Issue by agarhy** [helm/charts#10809]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
v2.9.1

**Which chart**:
stable/jenkins

**What happened**:
trying to add pre-generated ssh-key for master pod to allow private git repos access using

```
  # volumes:
  #   - type: Secret      
  #     secretName: cd-ssh-key-secret
  #     mountPath: /var/jenkins_home/.ssh

```

**What you expected to happen**:
secret private and public key copied to Jenkins user home dir @ /var/jenkins_home/.ssh
able to access private git repo with

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by dragid10** [comment]
Were you ever able to figure this out?

**Comment by VGerris** [comment]
looks like you can : https://github.com/helm/charts/issues/12140 with AdminSshKey .
