### ISSUE TITLE
RabbitMQ K8s peer discovery not working with 503 error

### ISSUE THREAD

**Issue by kferrone** [helm/charts#10811]
We are unable to run the `stable/rabbitmq` chart. Strangest thing is we had it running perfect and then I had to restart k8s and now rabbit is the only chart I can no longer run, every single other chart we use restarted like a dream. Basically a restart killed it and it could no longer start, so I tried to delete and run it again with the exact same values yet I get a different result. Huh?

**Version of Helm and Kubernetes**:
**Helm**
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

**k8s**
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.9", GitCommit:"e6ab4ee54f71e7a403cc733534bab86fd959ecb7", GitTreeState:"clean", BuildDate:"2018-10-16T12:01:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
[stable/rabbitmq](https://github.com/helm/charts/tree/master/stable/rabbitmq)

**What happened**:
I restarted k8s and now the rabbit chart no longer works. When I try and run the rabbit chart I constantly get the error below. 

```
2019-01-21 19:58:05.543 [info] <0.213.0> Configured peer discovery backend: rabbit_peer_discovery_k8s
2019-01-21 19:58:05.543 [info] <0.213.0> Will try to lock with peer discovery backend rabbit_peer_discovery_k8s
2019-01-21 19:58:05.543 [info] <0.213.0> Peer discovery backend does not support locking, falling back to randomized delay
2019-01-21 19:58:05.543 [info] <0.213.0> Peer discovery backend rabbit_peer_discovery_k8s does not support registration, skipping randomized startup delay.
2019-01-21 19:58:05.559 [info] <0.213.0> Failed to get nodes from k8s - 503
2019-01-21 19:58:05.560 [error] <0.212.0> CRASH REPORT Process <0.212.0> with 0 neighbours exited with reason: no case clause matching {error,"503"} in rabbit_mnesia:init_from_config/0 line 164 in application_master:init/4 line 138
2019-01-21 19:58:05.560 [info] <0.43.0> Application rabbit exited with reason: no case clause matching {error,"503"} in rabbit_mnesia:init_from_config/0 line 164
2019-01-21 19:58:05.561 [error] <0.106.0> Failed to write log message to file /opt/bitnami/rabbitmq/var/log/rabbitmq/rabbit@10.244.1.232.log: invalid argument
{"Kernel pid terminated",application_controller,"{application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{{case_clause,{error,\"503\"}},[{rabbit_mnesia,init_from_config,0,[{file,\"src/rabbit_mnesia.erl\"},{line,164}]},{rabbit_mnesia,init_with_lock,3,[{file,\"src/rabbit_mnesia.erl\"},{line,144}]},{rabbit_mnesia,init,0,[{file,\"src/rabbit_mnesia.erl\"},{line,111}]},{rabbit_boot_steps,'-run_step/2-lc$^1/1-1-',1,[{file,\"src/rabbit_boot_steps.erl\"},{line,49}]},{rabbit_boot_steps,run_step,2,[{file,\"src/rabbit_boot_steps.erl\"},{line,49}]},{rabbit_boot_steps,'-run_boot_steps/1-lc$^0/1-0-',1,[{file,\"src/rabbit_boot_steps.erl\"},{line,26}]},{rabbit_boot_steps,run_boot_steps,1,[{file,\"src/rabbit_boot_steps.erl\"},{line,26}]},{rabbit,start,2,[{file,\"src/rabbit.erl\"},{line,815}]}]}}}}}"}
 Kernel pid terminated (application_controller) ({application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{{case_clause,{error,"503"}},[{rabbit_mnesia,init_from_config,0,[{file
 
 Crash dump is being written to: /opt/bitnami/rabbitmq/var/log/rabbitmq/erl_crash.dump...done
```

**What you expected to happen**:
Rabbit should successfully get nodes from k8s when using peer discovery. 

**How to reproduce it** (as minimally and precisely as possible):
 Here are my `dev-server.yaml` values I pass to helm with `-f dev-server.yaml`. 

```yaml
rabbitmq:
  plugins: |-
      [rabbitmq_management, rabbitmq_peer_discovery_k8s, rabbitmq_mqtt, rabbitmq_stomp].
  ## Clustering settings
  clustering:
    address_type: hostname
    k8s_domain: cluster.local

  ## Configuration file content: required cluster configuration
  ## Do not override unless you know what you are doing. To add more configuration, use `extraConfiguration` instead
  configuration: |-
    ## Clustering
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.node_cleanup.interval = 10
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    # queue master locator
    queue_master_locator=min-masters
    # enable guest user
    loopback_users.guest = false
      
service:
  type: NodePort
  nodePort: 30672
```

**Anything else we need to know**:

I believe my issue has something to do with `rabbit_peer_discovery_k8s` and the host it is using. I read the `cluster_formation.k8s.host` is supposed to be the **k8s api server**. I also see the section below in the values but don't know what to put there. 

```yaml
rabbitmq:
    clustering:
        address_type: ip
        k8s_domain: cluster.local
```

I have also noticed we do have a service for the `API Server` simply named *kubernetes* and it is in the default namespace where I am trying to deploy rabbitmq. The service looks like below:

```yaml
apiVersion: "v1"
kind: "Service"
metadata:
  name: "kubernetes"
  namespace: "default"
  labels:
    component: "apiserver"
    provider: "kubernetes"
spec:
  clusterIP: "10.96.0.1"
  ports:
  - name: "https"
    port: 443
    protocol: "TCP"
    targetPort: 6443
  sessionAffinity: "None"
  type: "ClusterIP"
status:
  loadBalancer: {}
``` 

I also have a host entry to make the public hostname for kubernetes simply named `kubernetes` and the API is listening on port `6443`. 

Anyone know what values I need to get our rabbit runnin and thumpin? Anyone can explain to me what the real issue is?

**Comment by kferrone** [comment]
Logged by kubernetes? Do you mean the API server pod?

If so I am getting two very consistent errors inside it like below:

```W0122 17:23:18.184395       1 watcher.go:342] Fast watcher, slow processing. Number of buffered events: 100.Probably caused by slow decoding, user not receiving fast, or other processing logic```

```E0122 17:24:23.568033       1 upgradeaware.go:310] Error proxying data from client to backend: read tcp 10.20.10.207:6443->10.20.10.33:59774: read: connection reset by peer```

I also found errors in the `kube-proxy`:

```
E0121 18:11:20.898120       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: Failed to list *core.Endpoints: Get https://10.20.10.207:6443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.20.10.207:6443: getsockopt: connection refused
E0121 18:11:20.900989       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: Failed to list *core.Service: Get https://10.20.10.207:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.20.10.207:6443: getsockopt: connection refused
E0121 18:11:31.899697       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: Failed to list *core.Endpoints: Get https://10.20.10.207:6443/api/v1/endpoints?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E0121 18:11:31.902687       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: Failed to list *core.Service: Get https://10.20.10.207:6443/api/v1/services?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E0121 18:11:33.800220       1 event.go:209] Unable to write event: 'Post https://10.20.10.207:6443/api/v1/namespaces/default/events: net/http: TLS handshake timeout' (may retry after sleeping)
E0121 18:11:42.901389       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: Failed to list *core.Endpoints: Get https://10.20.10.207:6443/api/v1/endpoints?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E0121 18:11:42.904110       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: Failed to list *core.Service: Get https://10.20.10.207:6443/api/v1/services?limit=500&resourceVersion=0: net/http: TLS handshake timeout
I0121 18:11:49.421247       1 controller_utils.go:1026] Caches are synced for service config controller
I0121 18:11:49.422019       1 controller_utils.go:1026] Caches are synced for endpoints config controller
```

Here is a rabbit specific error I found in the `kube-dns` pod:

```
I0122 15:27:25.653980       1 dns.go:555] Could not find endpoints for service "honking-koala-rabbitmq-headless" in namespace "akxdev". DNS records will be created once endpoints show up.
```

Also found some errors in the `kube-scheduler`:

```
E0121 18:11:42.776257       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.PersistentVolume: Get https://10.20.10.207:6443/api/v1/persistentvolumes?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E0121 18:11:42.777180       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.StatefulSet: Get https://10.20.10.207:6443/apis/apps/v1beta1/statefulsets?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E0121 18:11:42.778364       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.ReplicaSet: Get https://10.20.10.207:6443/apis/extensions/v1beta1/replicasets?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E0121 18:11:42.779743       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.PodDisruptionBudget: Get https://10.20.10.207:6443/apis/policy/v1beta1/poddisruptionbudgets?limit=500&resourceVersion=0: net/http: TLS handshake timeout
I0121 18:11:50.066870       1 controller_utils.go:1019] Waiting for caches to sync for scheduler controller
```

From what I'm seeing, could it be an issue with my SSL certs?? Did they try tpo regenerate when I restarted?? I have yet to see anyone online talk about the ramifications of restarting k8s.

**Comment by juan131** [comment]
Hi @kferrone 

It looks like there's some miss-configuration in your cluster. Is your API server working? It looks like the different components of your cluster (`kube-dns`, `kube-scheduler`, etc.) are trying to connect with the API server but they can't access it.

Are you able to use `kubectl` to consult the K8s API?

**Comment by kferrone** [comment]
So I actually got rabbit to run. Turns out my issue was the k8s peer discovery could not connect over the default port 443 and I had to use the external port 6443 because `kubernetes.default.svc.cluster.local` resolved to the public port and could not find the internal, so yeah our config is messed up. 

On another note, it took me a while to realize the variable below was not overriding when I overrode it with  `helm install . -f server-values.yaml`.  

```yaml
rabbitmq:
  configuration: |-
    ## Clustering
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.port = 6443
    cluster_formation.node_cleanup.interval = 10
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    # queue master locator
    queue_master_locator=min-masters
    # enable guest user
    loopback_users.guest = false
```

I had to add `cluster_formation.k8s.port = 6443` to the main `values.yaml` file instead of my own. Once the port was changed specifically in the `values.yaml`, rabbit started right up.

**Comment by juan131** [comment]
Great @kferrone ! At least you could fix it using the external port.

> I had to add cluster_formation.k8s.port = 6443 to the main values.yaml file instead of my own. 

That's very weird.. You should be able to use the values from the YAML file you want.
