### ISSUE TITLE
etcd does not recover from crash

### ISSUE THREAD

**Issue by bit-herder** [helm/charts#1081]
If I install etcd with the chart, I get a working cluster. If I then delete a node in an autoscaling group with a etcd pod on it, it won't recover. That pod will be stuck in a reboot loop with 

 `etcdmain: listen tcp: lookup postgres-patroni-etcd-0.postgres-patroni-etcd on 100.64.0.10:53: no such host`

it will continue to restart like this forever. If I roll the whole cluster, the etcd cluster will break. I'm not sure posting config would help as this happens with the default config for me. 

I am using kops on AWS. 

Any ideas?

**Comment by bzub** [comment]
It looks like the chart defaults to v0.2.1 of etcd-operator, and later [releases](https://github.com/coreos/etcd-operator/releases) have improvements to cluster and pod restarts, as well as better DNS endpoints for etcd members.  I don't know yet if the chart will break with the newer versions, but you might give the latest version a shot with this chart.  If that doesn't work you might have to use etcd-operator outside of a chart until this chart is updated to support the latest version.

I'll see if I can find time in a few days to do some testing around this issue and update this chart.  The log of the etcd-operator pod could be useful if you posted it in some form for this issue.

**Comment by bit-herder** [comment]
my apologies, im speaking about etcd here https://github.com/kubernetes/charts/tree/master/incubator/etcd

not etcd-operator . 

the incubator etcd is included in the stolon and patroni charts, which is why im using that.

**Comment by lachie83** [comment]
Is there any way we could move the dependency to the etcd-operator?

**Comment by bit-herder** [comment]
i'd love to know how to do that.

**Comment by Elexy** [comment]
the cluster recovers after you delete the persistent volumes of the nodes that are unable to connect back into the cluster. The joining nodes will have to resync all data I guess

I am using Stolon as well.

**Comment by bit-herder** [comment]
all of the etcd clusters that stolon depends on don't recover... not the stolon nodes. thank you though.

**Comment by smirnov-mi** [comment]
Hi guys. Has anyone found a solution for this issue? I have the same with my patroni 1.3, using etcd 2.2.5. Deleting PVC and PV didn't help.
