### ISSUE TITLE
charts CI tests fail

### ISSUE THREAD

**Issue by fejta** [helm/charts#1083]
Test failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html#d7b63fd26f06aad82c6f

testgrid: https://k8s-testgrid.appspot.com/kubernetes-apps#charts-gce&sort-by-failures=

**Comment by prydonius** [comment]
cc @foxish

**Comment by foxish** [comment]
Should be fixed after we whitelist as per https://github.com/kubernetes/charts/issues/998

**Comment by fejta** [comment]
@kubernetes/sig-apps-test-failures 
/priority failing-test

**Comment by prydonius** [comment]
I believe these failures have since been fixed
/close
