### ISSUE TITLE
[stable/drone] Should docs include devel flag?

### ISSUE THREAD

**Issue by mikesplain** [helm/charts#10853]
As of https://github.com/helm/charts/pull/10614 the Drone chart now suggests running version drone version`1.0.0-rc.4` and thus helm chart version `2.0.0-rc.1`.  The only way I was able to install this version was to add the `--devel` flag to my install and upgrade commands.  I started playing with this chart by chance right after this merged and ran into a slew of issues since I thought that was the version that would automatically be installed.

Should docs include the --devel flag or a specific version of the chart, if they're going to so version specific with configuration? Just want to help others avoid what I ran into! 

Thanks!

**Comment by paulczar** [comment]
Mike!  thanks good catch.  I think adding a note in the README is a great idea!  Do you want to make a pull request to do so? We'd love to have you contribute.  If you haven't contributed to charts before and want help I'd be happy to chat on slack in Kubernetes #charts and help you out.
