### ISSUE TITLE
[stable/mariadb] Updating Config Values

### ISSUE THREAD

**Issue by 4ydx** [helm/charts#10859]
How is one meant to update config values?  I would like to increase the innodb buffer pool size, but am not familiar enough with kubernetes and this chart to know if I can simply change the config value for mysqld and then perform a helm upgrade or not.

My main concern is how one deals with the existing pvc.  I am sure this is probably straighforward, but help is appreciated.

**Comment by tompizmor** [comment]
Hello @4ydx,

If you also want to update the chart version to use the new docker image or leverage a new feature you would modify your configuration in the _values.yaml_ file and use `helm upgrade`. It is important that there is a new chart version as you can't update to the same version.

If you just want to add/delete/modify a configuration parameter from the _my.cnf_ file, I would just update the config map and then delete the MariaDB pods so they reload the configuration.

Once the new pod is started, it will load the existing data from the PVC.

**Comment by 4ydx** [comment]
Ok that went just fine.

I also performed the following steps because it seems appropriate for a mysql server.  I could be wrong of course.

https://dba.stackexchange.com/questions/35395/is-there-a-graceful-or-safe-restart-for-mysql-like-for-apache-httpd

**Comment by tompizmor** [comment]
Yes! Graceful ways to restart a server are always recommended!
