### ISSUE TITLE
[stable/kibana] Custom Pod Label Support

### ISSUE THREAD

**Issue by amitlalani** [helm/charts#10865]
I think this is a feature request as I couldn't see the functionality in the code.

I would like the ability to set custom pod labels to the Kibana deployment.

**Comment by pytimer** [comment]
Why are you need to  set custom labels on the Kibana pod?

If this feature need, i can send a PR to add this feature.

**Comment by amitlalani** [comment]
I usually add custom labels such as owner / team etc to all pods in the cluster for reporting and tracking purposes.

**Comment by pytimer** [comment]
@amitlalani I send a PR to implement this feature, you can see it. 

I don't have an environment to verify it. If you have any questions when use it, i hope you can tell me. Thanks.
