### ISSUE TITLE
stable/sentry fails if I specify --version

### ISSUE THREAD

**Issue by nicolas-g** [helm/charts#10888]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
```
⇒  helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```
Kubernetes version 1.11

**Which chart**:

stable/sentry

**What happened**:
Failed to install sentry If I define `--version` when I'm running helm 
```
helm install --version 9  stable/sentry
Error: failed to download "stable/sentry" (hint: running `helm repo update` may help)
```
PS: `helm repo update` didn't change anything.
**What you expected to happen**:

helm should install **sentry** successful .

**How to reproduce it** (as minimally and precisely as possible):

just run : 
```
helm install --version 9  stable/sentry
```

**Anything else we need to know**:

if I run the same command without the `--version` argument it runs successfully.
I only see this problem when I try to install sentry, other charts like consul, certmanager get install with no issues using the `--version` argument.

**Comment by Eraac** [comment]
Same kind of issue in my side, but with stable/datadog
```
$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
[774'407'393] kevin:~/code/abtasty/terraform/gcp-gke-mc$ helm install --version 1.18.1 --name dogstatsd --namespace unicollect-cron -f ./files/values_dogstatsd.yaml stable/datadog
Error: failed to download "stable/datadog"
```

latest chart version is 1.18.1 according to the Chart.yaml, but when you run `helm search stable/datadog`, you got
```
NAME          	CHART VERSION	APP VERSION	DESCRIPTION  
stable/datadog	1.10.0       	6.6.0      	DataDog Agent
```

**Comment by dgslv** [comment]
Have you managed to solve it?
I'm facing the same issue here

**Comment by serhiiromaniuk** [comment]
@dgslv Try this >
`helm install --name sentry --wait stable/sentry --values values.yaml --version 1.5.7 --namespace monitoring --atomic`

Seems like the problem related to versions. I'm not deep in this problem, but this command fixes me the issue.
