### ISSUE TITLE
[stable/elasticsearch] appVersion is not a method but has arguments

### ISSUE THREAD

**Issue by LudovicTOURMAN** [helm/charts#10899]
**Version of Helm and Kubernetes**:
```bash
$ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
```
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.2", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-04T16:19:46Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/elasticsearch

**What happened**:
Chart could not be deployed because of the error
`Error: render error in "charts/elasticsearch/templates/configmap.yaml": template: charts/elasticsearch/templates/configmap.yaml:51:16: executing "charts/elasticsearch/templates/configmap.yaml" at <.Values.appVersion>: appVersion is not a method but has arguments`

Worked previously on chart release `1.17.0`

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Add this requirement:
```yaml
- name: elasticsearch
  version: "1.17.1"
  repository: "@stable"
```
Then set this bunch of configuration in your `values.yaml`
```yaml
elasticsearch:
  appVersion: 5.6.14
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 5.6.14
```

**Anything else we need to know**:
Error seems to be caused because of the wrong [usage of comparator `gt`](https://github.com/helm/charts/commit/87d4f5cf6b7eb087209a5b4f051fb56b017cca4d#diff-bdfd97d5345541beca989e51d502315fR44) (And so on for the others).
Those ones are not "real comparators" but functions and should be used like this:
`{{- if (gt .Values.appVersion 5.4) or (eq .Values.appVersion 5.4) }}`
Instead of 
`{{- if .Values.appVersion gt 5.4 or .Values.appVersion eq 5.4 }}`

Some Helm official examples available here:
https://github.com/helm/helm/blob/master/docs/chart_template_guide/control_structures.md

Issue might concerne lines 44, 51, 67 in [configmap.yaml](https://github.com/helm/charts/blob/87d4f5cf6b7eb087209a5b4f051fb56b017cca4d/stable/elasticsearch/templates/configmap.yaml)

**Comment by kaarolch** [comment]
I added a small fix. They was two syntax problems. One that you mention and the second one: Author was  trying to compare `appVersion`  - semver (number.number.numer) so the string comparison was not work and also you can not convert it easy to float.

**Comment by kaarolch** [comment]
@LudovicTOURMAN changed already merged could you also check if everything works for you?

**Comment by LudovicTOURMAN** [comment]
> @LudovicTOURMAN changes already merged could you also check if everything works for you?

Thanks @kaarolch, issue seems to be greatly fixed :+1:
