### ISSUE TITLE
[stable/concourse] changes to maintainers and owners

### ISSUE THREAD

**Issue by paulczar** [helm/charts#10907]
In adding #10905 @cirocosta removed an owner (@frodenas) that is no longer owning the chart.  also remove were two people listed as maintainers @nexeck and @viglesiasce.

In follow-up it's not 100% clear that this was a correct action.  This issue is to give us a place to track whether or not they were removed correctly and if we should add them back.

This was an honest mistake of a new maintainer coming onboard and a minor miscommunication.  No malace or illwill was intended.

**Comment by cirocosta** [comment]
Hey,

I really appreciate the act of being transparent about it, and I'm really sorry for not being very clear about those removals!

Just to clarify,  before submitting the PR, I didn't reach directly to any of those being removed, and I'm sorry about that! There were no sneaky intentions on my side regarding just getting people out - my thoughts were all around the fact that the list didn't really reflect the current state of the maintainership around the chart.

So far I got in contact with Vic and sent messages to both Ferran (@frodenas) and (@nexeck). 

I'm more than happy to have them added back in case they want to get back to contributing to the Chart :grin:  

Thanks!!

**Comment by frodenas** [comment]
I'm also good with being removed.

**Comment by nexeck** [comment]
@cirocosta Thanks for your message. I am also good with being removed.
