### ISSUE TITLE
[stable/wordpress] helm install --set persistence.storageClass=nfs failed

### ISSUE THREAD

**Issue by jiefeng-xu** [helm/charts#10913]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
Helm v2.12.3
Kubernetes v1.13

**Which chart**:
stable/wordpress

**What happened**:

Following the readme, using `helm install --name my-release --set persistence.storageClass=nfs stable/wordpress`. This chart creates two pvc, but only create one storage class. So one pvc is bound and another one is always pending.

**What you expected to happen**:

Two storage classes should be created, and both pvc should be bound, and pods should be created successfully.

**How to reproduce it** (as minimally and precisely as possible):

`helm install stable/nfs-client-provisioner --set nfs.server=x.x.x.x --set nfs.path=/exported/path`
and then
`helm install --name my-release --set persistence.storageClass=nfs stable/wordpress`

**Anything else we need to know**:

**Comment by kaarolch** [comment]
Buf as I read from [nfs-client-provisioning readme](https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner#configuration) `storageClass.name` default is `nfs-client`. When you install `wordpress` you use storageClass:`nfs` not `nfs-client`. As I see during `nfs-client-provisioner` you do not change storageclass name.

**Comment by stantonxu** [comment]
@kaarolch , thanks for the quick response. Actually I did change the storage class name to `nfs-client`. I updated the command the used it as below,
```
helm install --name my-release --set persistence.storageClass=nfs-client stable/wordpress
```

The point is, this `wordpress` chart needs two pvc, while in the command it only asks for one storage class, so the second pvc is always pending.

**Comment by kaarolch** [comment]
The `wordpress` needs only one pvc the second pvc is probably for MariaDB, if yes, you need to add aditional option to values: `mariadb.master.persistence.storageClass=nfs-client`

**Comment by stantonxu** [comment]
In the commend you provided, it creates one storage class `nfs-client`, and let it be used by MariaDB. I think that will leave `wordpress` itself pending. I will test it soon to see the result though.

**Comment by stantonxu** [comment]
@kaarolch , your command works for me, thank you.

One question, how could the two pvc's `data-my-release-mariadb-0` and `my-release-wordpress` connect to the same storage class `nfs-client`? Should it be exclusive?

**Comment by kaarolch** [comment]
`StorageClass` should be use more like information for a kubernetes which storage driver should be use and how the `pv` should be handled (action, when you remove connected pvc, access type etc.) When you provide name of `storageClass` in your `pvc` definition, kuberentes would forward all `pv` orchestration request to specific storage/storage driver. In your case storageClass `nfs-client` would forward all pv request to nfs-client and nfs-client would create separate space on your `nfs-server`. In other words multiple `pv` could use one `storageClass`

**Comment by stantonxu** [comment]
Thank you, @javsalgar  and @kaarolch

**Comment by zerols** [comment]
![image](https://user-images.githubusercontent.com/35661759/111928753-7c2be380-8aef-11eb-8ee5-8d0af468f885.png)
I have use nfs-stor storageclass , but it show me don't bound storageclass, i have to delete pvc and creat a yaml to creat a same name pvc.
