### ISSUE TITLE
[stable/nginx-ingress] Disable controller-service on controller kind is specified as DaemonSet and useHostPort is true

### ISSUE THREAD

**Issue by msschl** [helm/charts#10921]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT/FEATURE REQUEST ...depends

**Version of Helm and Kubernetes**: Helm: v2.12.1;  Kubernetes: v1.13.2

**Which chart**: [stable/nginx-ingress]

**What happened**: 
**What you expected to happen**: When the controller kind is specified as DaemonSet and useHostPort is set to true, there is no need to spin up a service of type NodePort or LoadBalancer, or at least you should be able to disable this option.

**Comment by msschl** [comment]
Any news or comments?

**Comment by felippe-mendonca** [comment]
@msschl, I think you are right. Accordingly with the first note of nginx-ingress [documentation](https://kubernetes.github.io/ingress-nginx/deploy/baremetal/#via-the-host-network) when the setup is made via the host network, it's recommended to disable the service with this given configuration.

**Comment by msschl** [comment]
I have an open pull request pending for this issue
[#11911](https://github.com/helm/charts/pull/11911)

**Comment by msschl** [comment]
Is there any news?

**Comment by msschl** [comment]
@ChiefAlexander @taharah pending pull request #11911
