### ISSUE TITLE
[stable/external-dns] Support Digital Ocean

### ISSUE THREAD

**Issue by jeffmay** [helm/charts#10923]
**FEATURE REQUEST**

The [stable/external-dns](https://github.com/helm/charts/tree/master/stable/external-dns) helm deployment [does not currently support Digital Ocean](https://github.com/helm/charts/blob/b28194083eb3065cb932932c52c2d7fe43b65d49/stable/external-dns/values.yaml#L17-L18) as a provider. However, [external-dns does support Digital Ocean](https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/digitalocean.md). We should add that ability to the external-dns helm chart.

**Version of Helm and Kubernetes**: helm client v2.12.1 / server v2.12.1, kubernetes client v1.10.11 / server v1.13.1
**Which chart**: stable/external-dns
**What happened**: No support for Digital Ocean

**Comment by sebascastillocortez** [comment]
> **FEATURE REQUEST**
> 
> The [stable/external-dns](https://github.com/helm/charts/tree/master/stable/external-dns) helm deployment [does not currently support Digital Ocean](https://github.com/helm/charts/blob/b28194083eb3065cb932932c52c2d7fe43b65d49/stable/external-dns/values.yaml#L17-L18) as a provider. However, [external-dns does support Digital Ocean](https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/digitalocean.md). We should add that ability to the external-dns helm chart.
> 
> **Version of Helm and Kubernetes**: helm client v2.12.1 / server v2.12.1, kubernetes client v1.10.11 / server v1.13.1
> **Which chart**: stable/external-dns
> **What happened**: No support for Digital Ocean

+1
