### ISSUE TITLE
[incubator/fluentd-cloudwatch] Push logs to multiple log groups from one fluentd pod

### ISSUE THREAD

**Issue by rishiraaz** [helm/charts#10960]
**Is this a request for help?**:  No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

If this is a FEATURE REQUEST, please:
  - We want to push logs based on the source streams  to different logs groups in cloudwatch. 
For example logs like audit, infra can be pushed to one log group and application logs to another log group.

**Version of Helm and Kubernetes**:
helm: 2.9.1
k8s: 1.9.10

**Which chart**:
fluentd-cloudwatch

**What happened**:
Tried giving two different logs group names, didnt work.

**What you expected to happen**:
want to push logs to two log groups

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by async-dna** [comment]
this would be nice.
