### ISSUE TITLE
[stable/jenkins] Connection problem with GitHub and GitLab

### ISSUE THREAD

**Issue by marcelodearaujopedro** [helm/charts#10978]
**BUG REPORT**

**Version of Helm and Kubernetes**:
Kubernetes: v1.11.3
Helm: v2.12.2

**Which chart**:
stable/jenkins

**What happened**:
I can not do anything with GitHub or GitLab repository, always Jenkins show me the message:

> Failed to connect to repository : Command "git ls-remote -h git@gitlab.com:myuser/jenkins-test.git HEAD" returned status code 128:
stdout: 
stderr: ssh: connect to host gitlab.com port 22: Cannot assign requested address 
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

My credentials and certificate are configured correctly.

If I connect via SSH inside the pod and execute the command `ssh -T git@gitlab.com`, I got this message:

> ssh: connect to host gitlab.com port 22: Cannot assign requested address

What's wrong?

**Comment by maorfr** [comment]
Hey,

Did you install the required gitlab plugins?
