### ISSUE TITLE
rules are not enabled and disabled 

### ISSUE THREAD

**Issue by phoppe93** [helm/charts#10999]
BUG REPORT 

when i set the defaultRules.create to false and defaultRules.rules.alertmanager to true i have no default rules. 
I think it has to be enable the specified rules, when i enable it. 

For example in eks there are no kubelet services are running.

**Version of Helm and Kubernetes**:
2.0.0

**Which chart**:
charts/stable/prometheus-operator/

**What happened**:

**What you expected to happen**:
enable the specified rule 

**How to reproduce it** (as minimally and precisely as possible):
set vars
  values:
    defaultRules:
      create: false
      rules:
        alertmanager: true

**Anything else we need to know**:
when i set defaultRules.create: true i get all rules enabled

**Comment by paskal** [comment]
In a way it's currently done you need to have `defaultRules.create: true` and set all rules except ones you want to `false`. It's intended to be that way, other way (anything at all created with `defaultRules.create: false`) it's counter-intuitive. If it's not clear from documentation, than documentation should be altered - feel free to propose PR for that.

**Comment by phoppe93** [comment]
@paskal 
this is not working look at my vars

![grafik](https://user-images.githubusercontent.com/19833844/52204740-42e37b80-2875-11e9-9003-4b2f22ac02ba.png)


and i got any rules in prometheus

![grafik](https://user-images.githubusercontent.com/19833844/52204762-57277880-2875-11e9-829f-25e716d562d7.png)

**Comment by paskal** [comment]
Could you please post output of `helm version` and `kubectl version` commands, and also re-deploy your `prometheus-operator` to make sure it's the latest version? From initial report it's unclear which version you've deployed.
