### ISSUE TITLE
[stable/fluent-bit] Duplicate field 'time'

### ISSUE THREAD

**Issue by alwinmarkcf** [helm/charts#11000]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:

```
helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
[Stable/fluent-bit]

**What happened**:
Installing this chart will lead to two errors (using ES as Backend):
1. Duplicate field 'timestamp': This can be fixed via changing the config: backend.es.time_key. 
2. Duplicate field 'time': Which is produced by Elasticsearch itself. According to the Issues at fluent-bit: https://github.com/fluent/fluent-bit/issues/652 this can be fixed by modifying the parser, which is via just installing this chart docker for kubernetes.

```
{"took":63,"errors":true,"items":[{"index":{"_index":"kubernetes_cluster-2019.01.29","_type":"flb_type","_id":"UT4zn2gBxNK3QxeJ9ZIz","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"i_o_exception","reason":"Duplicate field 'time'\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@5121d0ca; line: 1, column: 2925]"}}}},{"index":{"_index":"kubernetes_cluster-2019.01.29","_type":"flb_type","_id":"Uj4zn2gBxNK3QxeJ9ZIz","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"i_o_exception","reason":"Duplicate field 'time'\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@8c4613a; line: 1, column: 2921]"}}}},{"index":{"_index":"kubernetes_cluster-2019.01.29","_type":"flb_type","_id":"Uz4zn2gBxNK3QxeJ9ZIz","status":400,"error":{"type":"mapper_parsing_exception","r
```

**What you expected to happen**:

As this as far as I understand the problem, will always happen, when let Elasticsearch log and collect those messages via fluent-bit and ES is a Backend option, I would think this problem is solved out of the box.

Not sure if this is true but I guess something like:
```
[PARSER]
    Name        kubernetes-docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep   Off
```
as parser would help.

I'd really appreciate a different solution, but I guess the solution for this should work out of the box.

**How to reproduce it** (as minimally and precisely as possible):

Install this chart while having an ES Cluster running on the same cluster which is also used as ES Backend.

That ES is producing logs like (found on the container log file on the system, which is also parsed by fluent-bit):
```
{"log":"[2019-01-30T10:09:07,116][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] TLS Transport Client Provider : null\n","stream":"stdout","time":"2019-01-30T10:09:07.11688363Z"}
```

**Anything else we need to know**:

**Comment by alwinmarkcf** [comment]
Ok so I don't know if that is really the fix, but it works for me solving both @timestamp and time duplicate fields issue:

https://github.com/fluent/fluent-bit/issues/628

So maybe this merge keys option should be disabled by default.

**Comment by alwinmark** [comment]
Hi,

can somebody open this again?

**Comment by linbingdouzhe** [comment]
facing the same problem

**Comment by acarsercan** [comment]
Same here

**Comment by tirelibirefe** [comment]
Not working as expected.
The same problem is still exist.
