### ISSUE TITLE
Kafka pod in pending state -  pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by thomaslees** [helm/charts#11002]
**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**: Kafka

**What happened**: Followed the steps in the below link to install Kafka.
https://github.com/helm/charts/tree/master/incubator/kafka
my-kafka-0 pod is in pending state.
kubectl describe pod my-kafka-0 -n kafka
gives 
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  42m (x2 over 42m)  default-scheduler  pod has unbound immediate PersistentVolumeClaims

kubectl describe pvc datadir-my-kafka-0 -n kafka
Name:          datadir-my-kafka-0
Namespace:     kafka
StorageClass:
Status:        Pending
Volume:
Labels:        app=kafka
               release=my-kafka
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Events:
  Type       Reason         Age                      From                         Message
  ----       ------         ----                     ----                         -------
  Normal     FailedBinding  2m45s (x743 over 4h52m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

 

**What you expected to happen**:
Expected the kafka pod to be in running state

**How to reproduce it** (as minimally and precisely as possible):
 helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
 kubectl create ns kafka
 helm install --name my-kafka --namespace kafka incubator/kafka

**Anything else we need to know**:

**Comment by thomaslees** [comment]
**Workaround**: 
Set the persistence to false in values.yaml. 
**Solution**: 
We have to manually create a storage class and link it with the persistent volume claim.
Follow the steps in for dynamic provisioning of a storage class 
https://github.com/MaZderMind/hostpath-provisioner 
 kubectl get sc
NAME                 PROVISIONER   AGE
hostpath (default)   hostpath      38m

Create a yaml file with the kafka persistent volume claim parameters.
kubectl  get pvc datadir-my-kafka-0 -n kafka -o yaml > kafka-pvc.yaml

Edit the kafka-pvc.yaml file by adding "storageClassName" as follows

vim kafka-pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2019-01-31T05:06:08Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: kafka
    release: my-kafka
  name: datadir-my-kafka-0
  namespace: kafka
  resourceVersion: "6094"
  selfLink: /api/v1/namespaces/kafka/persistentvolumeclaims/datadir-my-kafka-0
  uid: eb2013d1-2515-11e9-8d7c-080027f22955
spec:
  **storageClassName: "hostpath"**
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
status:
  phase: Pending

Delete the existing pvc
 kubectl delete pvc datadir-my-kafka-0 -n kafka

Create a new pvc 
kubectl create -f kafka-pvc.yaml

Check the pvc status for its binding
kubectl get pvc -n kafka

Issue the command
helm install --name my-kafka --namespace kafka incubator/kafka

Happy helming !!!!!!!!!!!!!!!!!!

**Comment by thomaslees** [comment]
Thanks to Akash Pahal (Akash.Pahal@radisys.com) for the helpful tips.

**Comment by jesusmariajurado** [comment]
Hi all, make sure you have "storage" addon enabled. You should have a "hostpath" pod running on system
