### ISSUE TITLE
postgresql helm chart dbinitscripts start too early: psql: FATAL:  the database system is starting up

### ISSUE THREAD

**Issue by planetf1** [helm/charts#11012]
**Is this a request for help?**:
Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT (possible)

**Version of Helm and Kubernetes**:
```
16:35 $ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
16:35 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4+IKS", GitCommit:"27c949c1ae36d3c99246bde7ef68ff8bd3bb4ad3", GitTreeState:"clean", BuildDate:"2019-01-09T10:08:47Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
postgresql 3.9.2
https://github.com/helm/charts/tree/master/stable/postgresql

**What happened**:
When Postgres initialized it attempted to execute initialization scripts before the server was ready:

```
16:32 $ kubectl logs -f quoting-jackal-postgresql-0

Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues

nami    INFO  Initializing postgresql
postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL with persisted data...
postgre INFO  ==> Cleaning stale postmaster.pid file...
postgre INFO  ==> Configuring PostgreSQL...
postgre INFO  ==> Configuring replication parameters...
postgre INFO  ==> Configuring permissions for config files...
postgre INFO
postgre INFO  ########################################################################
postgre INFO   Installation parameters for postgresql:
postgre INFO     Persisted data and properties have been restored.
postgre INFO     Any input specified will not take effect.
postgre INFO   This installation requires no credentials.
postgre INFO  ########################################################################
postgre INFO
nami    INFO  postgresql successfully initialized
INFO  ==> Starting postgresql...
INFO  ==> Loading user files from /docker-entrypoint-initdb.d
Ignoring /docker-entrypoint-initdb.d/CompDir-ContactEmail.csv
Ignoring /docker-entrypoint-initdb.d/CompDir-ContactList.csv
Ignoring /docker-entrypoint-initdb.d/CompDir-ContactPhone.csv
Ignoring /docker-entrypoint-initdb.d/Employee-Dept.csv
Ignoring /docker-entrypoint-initdb.d/Employee-Employee.csv
Ignoring /docker-entrypoint-initdb.d/EmplSAnl-EmpSalaryAnalysis.csv
Executing /docker-entrypoint-initdb.d/loadCOMPDIR.sql
psql: FATAL:  the database system is starting up

Executing /docker-entrypoint-initdb.d/loadEMPLOYEE.sql
psql: FATAL:  the database system is starting up

Executing /docker-entrypoint-initdb.d/loadEMPLSANL.sql
psql: FATAL:  the database system is starting up

Executing /docker-entrypoint-initdb.d/loadLOCATION.sql
psql: FATAL:  the database system is starting up

Executing /docker-entrypoint-initdb.d/loadPATIENT.sql
psql: FATAL:  the database system is starting up

Ignoring /docker-entrypoint-initdb.d/Location-WorkLocation.csv
Ignoring /docker-entrypoint-initdb.d/Patient-Patient.csv
✔ ~/src/egeria/open-metadata-resources/open-metadata-deployment/charts [helm12|✚ 2…5⚑ 12]
```

**What you expected to happen**:
I would have expected initialization scripts to be executed only once the server was ready to accept requests

**How to reproduce it** (as minimally and precisely as possible):
Create a number of initialization scripts along the lines of:
postgresql:
  postgresqlUsername: "psql"
  postgresqlPassword: "passw0rd"
  initdbScripts:
    CompDir-ContactEmail.csv: |
      RecId;EType;Email
      1;C;ZachNow@cocopharmaceutical.com
      1;S;zach@cocopharmaceutical.com
      2;C;SteveStarter@cocopharmaceutical.com
(I have about 10 files in total - a few csvs, and then the sql files to import them)

**Anything else we need to know**:

**Comment by planetf1** [comment]
This also occurs with 3.9.5

**Comment by planetf1** [comment]
I repeated this without persistence ... and the error does not occur.

Since this is a demo with static data it is good enough for me, however it indicates perhaps there is an issue in the chart. I did also consider a workaround of adding a 0-wait.sh script to the files which could go into a loop waiting for server to be ready.

**Comment by javsalgar** [comment]
Hi,

I see what's going on. So you are adding user scripts to an already initialized PostgreSQL instance. I am not sure if that's the expected way to work with it but it wouldn't hurt to add an extra check in the `run.sh` file. We will consider this issue in future releases of the container.

https://github.com/bitnami/bitnami-docker-postgresql/blob/master/9.6/debian-9/rootfs/run.sh

**Comment by javsalgar** [comment]
I'm just releasing a new version of the container that adds an extra check before executing the script. I think it should cover your use case

**Comment by javsalgar** [comment]
It is already out, could you check if it works for you?
