### ISSUE TITLE
[stable/elastic-stack] setup issues

### ISSUE THREAD

**Issue by AndiDog** [helm/charts#11037]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug/help

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/elastic-stack

**What happened**:
The default install configured `ELASTICSEARCH_URL: http://http.default.svc.cluster.local:9200` in the deployment. That left the Kibana pod fail-looping with error `Unable to revive connection` since there's no such Kubernetes service. I assume it should be `http://{{ .Release.Name }}-elasticsearch-client:9200` (or suffixed with `.default.svc.cluster.local` if you prefer the long DNS name)?! I edited the deployment manually to `http://elastic-stack-elasticsearch-client:9200` (where `elastic-stack` is my chosen release name), and Kibana connected just fine.

If someone googles this issue: for me, this was the reason why the Kibana web interface showed the error "Kibana server is not ready yet".

**What you expected to happen**:
Working out of the box \<naive developer face emoticon\>

**How to reproduce it** (as minimally and precisely as possible):
`helm install --name elastic-stack stable/elastic-stack`

**Anything else we need to know**:

**Comment by lhriley** [comment]
It looks like the elastic-stack chart might be rather outdated compared to the most recent individual components. For example, it looks like kibana is pinned at version `1.1.2` (https://github.com/helm/charts/blob/1912822188517fa4c71554b047667d494a85ea2e/stable/elastic-stack/requirements.lock#L5-L7) while the latest version is `1.4.0` (https://github.com/helm/charts/blob/1912822188517fa4c71554b047667d494a85ea2e/stable/kibana/Chart.yaml#L2).

It is also unclear how the configuration is supposed to transfer from the meta chart elastic-stack down to the dependency charts.

For example, this is the default configuration for kibana (https://github.com/helm/charts/blob/1912822188517fa4c71554b047667d494a85ea2e/stable/elastic-stack/values.yaml#L7-L9) in the elastic-stack chart, while the kibana chart has a much more detailed set of options including the `files` map added about 6 months ago (https://github.com/helm/charts/commit/67aeda73f3bc35200266627635e8138ee48ba195#diff-761d187d0b4be7a6e7099800525bcb80R19) which doesn't seem to be respected.

I've tried the following, for example, but get the same error as @AndiDog (`http://http.default.svc.cluster.local:9200` is always set in kibana):

```
      kibana:
        env: {}
        files:
          kibana.yml:
            ## Default Kibana configuration from kibana-docker.
            server.name: kibana
            server.host: "0"
            elasticsearch.hosts: ["http://elastic-stack-elasticsearch-client.default.svc.cluster.local:9200"]
```

Errors always look like:
```
{"type":"log","@timestamp":"2019-02-01T20:05:56Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://http.default.svc.cluster.local:9200/"}
{"type":"log","@timestamp":"2019-02-01T20:05:56Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
```

**Comment by AndiDog** [comment]
> @AndiDog Can you post your elk-values.yaml file? I'm having the same issue today and want to make sure I understand what all needs to change in the values file since that name appears in multiple places. Thanks.

`http.default.svc.cluster.local` only appears once 😉 (`kibana:` section). I ran the chart without any changes, then edited the Kubernetes resource directly. Still a Helm beginner...

**Comment by kianting** [comment]
I am facing the same issue while installing the elastickstack/stable helm chart

**Comment by MohammedFadin** [comment]
Any update on this issue?

**Comment by moshebeeri** [comment]
same issue with mac
