### ISSUE TITLE
[stable/redis] fails during installation

### ISSUE THREAD

**Issue by petrokashlikov** [helm/charts#11040]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes 1.1.15 on GKE Helm 2.10.0

**Which chart**:
[stable/redis]

**What happened**:
chart is failing to install with following error 

helm install stable/redis --values values-production.yaml

Error: release singing-anaconda failed: Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment.Spec: v1beta1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found [, error found in #10 byte of ...|,"value":["FLUSHDB F|..., bigger context ...|dis"}}},{"name":"REDIS_DISABLE_COMMANDS","value":["FLUSHDB FLUSHALL"]}],"image":"docker.io/bitnami/r|...

**What you expected to happen**:

Expect to install successfully

**How to reproduce it** (as minimally and precisely as possible):

Run helm install stable/redis --values values-production.yaml
**Anything else we need to know**:
I suspect that it might be related to latest commit https://github.com/helm/charts/commit/25d05a61f984cb012a4b8f299e23c7105e8cd5f7, as we were able to install it about week ago

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue:

```
± |master → origin ✓| → sudo helm install stable/redis --values values-production.yaml 
NAME:   trendy-bison
LAST DEPLOYED: Tue Feb  5 10:49:16 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME                AGE
trendy-bison-redis  1s

==> v1/ConfigMap
trendy-bison-redis         1s
trendy-bison-redis-health  1s

==> v1/Service
trendy-bison-redis-metrics  1s
trendy-bison-redis-master   1s
trendy-bison-redis-slave    1s

==> v1beta1/Deployment
trendy-bison-redis-metrics  1s
trendy-bison-redis-slave    1s

==> v1beta2/StatefulSet
trendy-bison-redis-master  1s

==> v1/NetworkPolicy
trendy-bison-redis  1s

==> v1/Pod(related)

NAME                                        READY  STATUS             RESTARTS  AGE
trendy-bison-redis-metrics-564479698-mmdrj  0/1    ContainerCreating  0         1s
trendy-bison-redis-slave-658486f776-4htqx   0/1    Pending            0         1s
trendy-bison-redis-slave-658486f776-6sqpt   0/1    Pending            0         1s
trendy-bison-redis-slave-658486f776-lf5dt   0/1    ContainerCreating  0         1s
trendy-bison-redis-master-0                 0/1    Pending            0         1s


NOTES:
** Please be patient while the chart is being deployed **
Redis can be accessed via port 6379 on the following DNS names from within your cluster:

trendy-bison-redis-master.default.svc.cluster.local for read/write operations
trendy-bison-redis-slave.default.svc.cluster.local for read-only operations


To get your password run:

    export REDIS_PASSWORD=$(kubectl get secret --namespace default trendy-bison-redis -o jsonpath="{.data.redis-password}" | base64 --decode)

To connect to your Redis server:

1. Run a Redis pod that you can use as a client:

   kubectl run --namespace default trendy-bison-redis-client --rm --tty -i --restart='Never' \
    --env REDIS_PASSWORD=$REDIS_PASSWORD \--labels="redis-client=true" \
   --image docker.io/bitnami/redis:4.0.12 -- bash

2. Connect using the Redis CLI:
   redis-cli -h trendy-bison-redis-master -a $REDIS_PASSWORD
   redis-cli -h trendy-bison-redis-slave -a $REDIS_PASSWORD


Note: Since NetworkPolicy is enabled, only pods with label
trendy-bison-redis-client=true"
will be able to connect to redis.
```

Did you execute `helm repo update` first? Maybe you are using an old version of the chart.

**Comment by petrokashlikov** [comment]
Hi, thanks for your reply. Looks actually my bad, as I didn't execute helm repo update :(

**Comment by carrodher** [comment]
No problem! If you have any other questions, please do not hesitate to let us know.

**Comment by javsalgar** [comment]
I suppose that we can close this issue then
