### ISSUE TITLE
[stable/prometheus-operator] ruleSelectorNilUseHelmValues: false disables all PrometheusRules

### ISSUE THREAD

**Issue by bjakubski** [helm/charts#11055]
**Is this a request for help?**:

no 
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

does not really matter here I believe

**Which chart**:
prometheus-operator

**What happened**:

I wanted to prometheus-operator to find and use all PrometheusRule there are (in single namespace, but not limited to ones created by prometheus operator).
To achieve it I've set (while keeping all other ruleSelector* settings at default values)
```
prometheus:
  prometheusSpec:
    ruleSelectorNilUseHelmValues: false
```

After installing chart *no* PromethusRule configmaps were mounted (not even own prometheus-operator ones).

**What you expected to happen**:

Given that ruleSelector defaults to {} I've expected operator to use *all* PrometheusRule objects in the namespace that prometheus-operator is deployed in.
While there seems to be some confusion what empty "selector" means exactly in k8s world this would make it consistent with how serviceMonitorNilUseHelmValues: false behaves (which has the same defaults and loads all ServiceMonitors it finds.)

**How to reproduce it** (as minimally and precisely as possible):

while keeping default values of other ruleSelector* variables set
```
ruleSelectorNilUseHelmValues: false
```
and deploy chart.

**Anything else we need to know**:

In 

https://github.com/helm/charts/blob/b5600383bcc9adae34cfd8d6ab426a72dd0a1fa0/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L101

there is no way to have ruleSelectorNilUseHelmValues be false and to pass empty (but existing) ruleSelector to created Prometheus object. I believe operator treats non-existent ruleSelector and empty dict differently (former causes no ProemtheusRules to be found and latter just uses all of them)

There is a workaround which I'm using:
```
ruleSelector:
  matchExpression:
    key: name
    operator: NotIn
    values: ['WillNeverHappen']
```

I guess solution would be to add else statement in the same way as serviceMonitorSelector is using in https://github.com/helm/charts/blob/b5600383bcc9adae34cfd8d6ab426a72dd0a1fa0/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L75

**Comment by paskal** [comment]
Could you please prepare PR with the fix, and document the behavior in readme and values.yaml? I think there is a very good chance of it to get merged, however updating readme is mandatory for such change. Also I suggest major version bump because it change chart behavior.

**Comment by vsliouniaev** [comment]
I think the behaviour with the latest merged PR should be correct now: https://github.com/helm/charts/pull/11395

**Comment by bjakubski** [comment]
Yes, #11395 has the fix I had in mind. Thanks everyone!
