### ISSUE TITLE
LIVENESS_PROBE_FATAL_ERRORS not set properly

### ISSUE THREAD

**Issue by bnoorduin** [helm/charts#11060]
**Is this a request for help?**:

No. Just pointing at an issue in the stable chart for concourse.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

Helm 2.12.1
Kubernetes: 1.11.5

**Which chart**:
stable/concourse

**What happened**:

The worker livenessprobe does not catch the fatal errors in values.yaml.

**What you expected to happen**:

The worker livenessprobe should catch the fatal errors in values.yaml.

**How to reproduce it** (as minimally and precisely as possible):

in the worker:

echo "guardian.api.garden-server.create.failed" >> /tmp/.liveness_probe

**Anything else we need to know**:

Yes. The environment variable in the helm chart is as such:

            - name: LIVENESS_PROBE_FATAL_ERRORS
              value: "guardian.api.garden-server.create.failed\nbaggageclaim.api.volume-server.create-volume-async.failed-to-create"

Should change it to:

            - name: LIVENESS_PROBE_FATAL_ERRORS
              value: "export ERRORS=$'guardian.api.garden-server.create.failed\nbaggageclaim.api.volume-server.create-volume-async.failed-to-create'"

and then in the livenessprobe
           eval "$LIVENESS_PROBE_FATAL_ERRORS"
and
           grep -F "$ERRORS" /tmp/.liveness_probe

Greetings,

**Comment by cirocosta** [comment]
Hi @bnoorduin ,

Thanks for submitting the issue!

Would you mind providing a PR for it?

As a side note, in Concourse itself, we're trying to make the process of detecting potential worker problems better by integrating into the health checks the creation of some minimal workload that would be able to detect such failures - you might be interested in checking this one out  https://github.com/concourse/concourse/pull/3025.

Thanks!

**Comment by bnoorduin** [comment]
I would, but I have no idea what a PR is. I am inclined to dig a bit
further into using appdynamics and fluentd for monitoring the logs of
various pods and taking actions from outside rather then relying on the
livenessprobe. For me, the idea that I cannot do a kubectl apply on a
statefulset that changes the livenessprobe makes it a bit too intrusive,
since I can monitor logs and perform corrective actions from outside for
which the config has no impact to the concourse deployment. Anyhow as part
of an upgrade yes it would be very valuable to be more robust.

Kindly,
Bob.
