### ISSUE TITLE
[stable/nginx-ingress] Pods do not restart

### ISSUE THREAD

**Issue by 4ydx** [helm/charts#11087]
When performing an upgrade helm indicates success but the controller pod is not restarted.  This is confusing to me.  Am I supposed to delete the pod myself?

**Comment by gtseres** [comment]
What did you change from the previous chart revision? Maybe you need to pass in the `--recreate-pods` flag to the upgrade command.

**Comment by 4ydx** [comment]
I see.  I am still learning helm/kubernetes and assumed that an upgrade would start new pods.  Is recreate-pods a graceful action?
