### ISSUE TITLE
can not connect openvpn chart 

### ISSUE THREAD

**Issue by 13567436138** [helm/charts#11101]
**Is this a request for help?**:

---
request for help
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
[root@node1 ~]# helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

[root@node1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
[root@node1 ~]# helm search openvpn
NAME            CHART VERSION   APP VERSION     DESCRIPTION                                                 
stable/openvpn  3.11.0          1.1.0           A Helm chart to install an openvpn server inside a kubern...

**What happened**:
client log:
Sun Feb 03 17:48:52 2019 Connection reset, restarting [-1]
Sun Feb 03 17:48:52 2019 SIGUSR1[soft,connection-reset] received, process restarting
Sun Feb 03 17:49:32 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]47.254.92.51:2222
Sun Feb 03 17:49:32 2019 Attempting to establish TCP connection with [AF_INET]47.254.92.51:2222 [nonblock]
Sun Feb 03 17:49:33 2019 TCP connection established with [AF_INET]47.254.92.51:2222
Sun Feb 03 17:49:33 2019 TCP_CLIENT link local: (not bound)
Sun Feb 03 17:49:33 2019 TCP_CLIENT link remote: [AF_INET]47.254.92.51:2222
Sun Feb 03 17:49:33 2019 Connection reset, restarting [-1]

server log：
Sun Feb  3 09:14:01 2019 172.20.164.160:39282 WARNING: Bad encapsulated packet length from peer (65524), which must be > 0 and <= 1546 -- please ensure that --tun-mtu or --link-mtu is equal on both peers -- this condition could also indicate a possible active attack on the TCP link -- [Attempting restart...]
Sun Feb  3 09:14:01 2019 172.20.164.160:39282 Connection reset, restarting [0]
Sun Feb  3 09:14:01 2019 172.20.164.160:39282 SIGUSR1[soft,connection-reset] received, client-instance restarting
Sun Feb  3 09:14:25 2019 TCP connection established with [AF_INET]172.20.164.160:39384
Sun Feb  3 09:14:26 2019 172.20.164.160:39384 TLS: Initial packet from [AF_INET]172.20.164.160:39384, sid=767c3742 7d216e6d
Sun Feb  3 09:14:26 2019 172.20.164.160:39384 Connection reset, restarting [0]
Sun Feb  3 09:14:26 2019 172.20.164.160:39384 SIGUSR1[soft,connection-reset] received, client-instance restarting
Sun Feb  3 09:14:31 2019 TCP connection established with [AF_INET]172.20.164.160:39412
Sun Feb  3 09:14:32 2019 172.20.164.160:39412 TLS: Initial packet from [AF_INET]172.20.164.160:39412, sid=43f74243 4f833ed3
Sun Feb  3 09:14:32 2019 172.20.164.160:39412 Connection reset, restarting [0]

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by MikeDaniel18** [comment]
@13567436138 Hey, did you ever fix this? I had a similar problem.
