### ISSUE TITLE
[stable/traefik] ACME dns-01 challenge get an expired Let's Encrypt certificate

### ISSUE THREAD

**Issue by JWDobken** [helm/charts#11106]
Is this a request for help?
**yes**

Is this a BUG REPORT or FEATURE REQUEST? (choose one): **bug?**

```bash
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

```bash
$ helm version

Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```

My `traefik-helm.yml`:

```
image: traefik
imageTag: 1.7.6
kubernetes:
    ingressClass: traefik
ssl:
    enabled: true
    enforced: true
acme:
    logging: true
    enabled: true
    email: <NAME@MY-EMAIL.com>
    challengeType: dns-01
    staging: true
    dnsProvider:
        name: transip
        transip:
            TRANSIP_ACCOUNTNAME: my_transip_account
            TRANSIP_PRIVATEKEYPATH: /Users/username/.ssh/transip
    domains:
        enabled: true
        domainsList:
        - main: "*.mydomain.com" 
dashboard:
    enabled: true
    domain: "traefik.dashboard.mydomain.com"
    ingress:
        annotations:
            kubernetes.io/ingress.class: traefik
```

I install traefik with the following command:

    helm upgrade --install --namespace kube-system --values traefik-helm.yml traefik stable/traefik

There are no errors, but the domains have a certificate that is expired???
Here is a screenshot of the certificate, as shown by Firefox:

<img width="588" alt="screenshot 2019-02-04 at 08 11 51" src="https://user-images.githubusercontent.com/15050499/52194578-c93b9580-2854-11e9-9b53-b837a5dfc9c2.png">

Is this a default result of the challenge and/or how can I solve it (I am not an expert!)

**Comment by costela** [comment]
This likely means the letsencrypt validation failed. You can confirm by checking the pod logs (`kubectl -n kube-system logs traefik-...` for the appropriate pod).

Depending on the cloud provider you are using, this might be a race condition between the validation and creation of the DNS entry for your dashboard. Traefik currently tries to create the certificate on startup, which may mean it tries to create it before letsencrypt can perform its validation. Again: the logs would either confirm this or point to another culprit.
If my assumption is correct, this is also related to containous/traefik#2670.
