### ISSUE TITLE
[stable/nginx-ingress] Latest nginx-ingress has a critical breaking change, with no way to deploy an earlier version.

### ISSUE THREAD

**Issue by avik-so** [helm/charts#11121]
**Is this a request for help?**:

No.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:

 ALL
**Which chart**:

stable/nginx-ingress

**What happened**:

It deploys version 0.22.0 which has breaking changes

**What you expected to happen**:

For it to deploy stable versions without major breaking changes, or give warnings that it is doing so.
In this case, the rewrite target rules no longer work.

**How to reproduce it** (as minimally and precisely as possible):

run helm install for stable/nginx-ingress

**Anything else we need to know**:

Need a way to deploy the stable version which doesn't have the breaking changes.

**Comment by Towmeykaw** [comment]
something like helm install stable/nginx-ingress --set controller.image.tag=0.21.0

**Comment by MMartyn** [comment]
Just wanted to note that you can use the latest but you need to add some annotations.
https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md#0220
