### ISSUE TITLE
[stable/mattermost-team-edition] Add possibility to use custom config.tpl

### ISSUE THREAD

**Issue by Xnyle** [helm/charts#11127]
**FEATURE REQUEST**

The Chart mattermost-team-edition mounts a config map as system config. Base is a config.tpl in the chart repo.

This Config has many hardcoded values one can not change at runtime, as the ConfigMap is mounted read only.

Therefore I would like to provide my own config.tpl via values.yaml which is currently not possible as the chart has no option for that.

**Comment by Xnyle** [comment]
Still w8ting for this feature Mr. StaleBot

**Comment by cpanato** [comment]
@Xnyle please check if this PR https://github.com/helm/charts/pull/8019 fix your issue

**Comment by Xnyle** [comment]
Yes, thanks, Version 3 solves it :+1:
