### ISSUE TITLE
[stable/elasticsearch] master_not_discovered_exception when using one master pod

### ISSUE THREAD

**Issue by martinnaughton** [helm/charts#11120]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.11
Kubernetes: v1.11.5-gke.5

**Which chart**:
stable/elasticsearch

**What happened**:
When starting up elastic search with 1 master, 1 data and 1 client the master complains that it can not contact the <release-name>-elasticsearch-discovery service because it is not available. The master is coming online faster than the service. After 45 the service can be pinged but the master only tries once on its startup.  The error that is logged is:

With the issue the cluster is in state red.

**What you expected to happen**:
The master is delayed for a while until the discovery service has enough time to come online. Then it will be able to contact it and complete the cluster.

**How to reproduce it** (as minimally and precisely as possible):
Install the helm chart with this values file edit with replicaset set to 1 for master, client and data
https://raw.githubusercontent.com/helm/charts/master/stable/elasticsearch/values.yaml

**Anything else we need to know**:
A work around is to increase the master replicaset to 2 so that when the 2nd master comes online the it is able to contact the discovery service because of its delay. the cluster is then set to green status.

**Comment by anapsix** [comment]
did you make sure to set `MINIMUM_MASTER_NODES:1` via `cluster.env`, as described in README?

**Comment by anapsix** [comment]
also see https://github.com/helm/charts/pull/8577

**Comment by simplypost** [comment]
I have the same issue.
Already set MINIMUM_MASTER_NODES:1
