### ISSUE TITLE
[stable/traefik] Support Ping entrypoint

### ISSUE THREAD

**Issue by Techcadia** [helm/charts#11125]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
Feature Request

Currently the Config Map does not support the ping entrypoint.

https://docs.traefik.io/configuration/ping/

I feel like there should be two options.
1. default to the default port traefik supports
1. support defining its own entrypoint if a port is defined for ping

**Version of Helm and Kubernetes**:
latest

**Which chart**:
traefik

**What happened**:
missing configuration

**What you expected to happen**:
support for the ping endpoint

**How to reproduce it** (as minimally and precisely as possible):
edit configmap adding values

**Anything else we need to know**:

**Comment by TechIsCool** [comment]
This is still an issue. It looks like case one has been solved by passing in
```
startupArguments:
  - "--ping"
  - "--ping.entrypoint=http"
```

But you still can't define a new entry point with a different port.
