### ISSUE TITLE
stable/airflow: not honoring `postgresql.portgresHost`

### ISSUE THREAD

**Issue by kalyanaramansanthanam** [helm/charts#11140]
*BUG REPORT*
I am trying to use an external RDS Postgres DB instead of persisted Postgres pod
according to the documentation,  it looks `postgresql.portgresHost` or `postgresql.uri` can be used instead of persisted Postgres pod
however, it doesn't seem to be honored in template

chart: stable/airflow

**Comment by PatrickHuetter** [comment]
I can confirm this issue. Although we disabled the creation of the postgres container because we're using an external postgres instance the chart creates one and also does the migrations on the wrong host (the newly created postgres container) instead of the configured host.

**Comment by kalyanaramansanthanam** [comment]
how do you connect to the external postgres instance? did you fork the chart?

**Comment by PatrickHuetter** [comment]
I didn't fork, i'm using the current stable and i configured the following environment variables:
```
postgres.enabled: false
env.pg_password: thepassword
env.pg_host: my.postgres.hostname
```

**Comment by kalyanaramansanthanam** [comment]
i wasn't seeing `env` field in values.yaml so didn't know it was supported
will try it out
