### ISSUE TITLE
[stable/redis-ha] secret password - error wrong number of args for b64enc

### ISSUE THREAD

**Issue by lakano** [helm/charts#11151]
**Is this a request for help?**:
No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

```
**Which chart**:
stable/redis-ha (default tag 5.0.3-alpine)

**What happened**:
An error occured when I try to install with existingSecret option:
```
helm install -n redis-ha --namespace redis-ha stable/redis-ha -f values.yaml
Error: render error in "redis-ha/templates/redis-auth-secret.yaml": template: redis-ha/templates/redis-auth-secret.yaml:10:35: executing "redis-ha/templates/redis-auth-secret.yaml" at <b64enc>: wrong number of args for b64enc: want 1 got 0
```

**What you expected to happen**:
Install it correctly, and use the existing secret password for AUTH.

**How to reproduce it** (as minimally and precisely as possible):
- create a namespace "redis-ha"
- create a secret « redis » in this namespace, with a key named « auth » and the password
- update the values.yaml to set « auth: true » and « existingSecret: "redis" »
- install it: « helm install -n redis-ha --namespace redis-ha stable/redis-ha -f values.yaml »

**Anything else we need to know**:
I've also tried simple alphanumeric passwords to be sure it's not related to special characters

**Comment by lakano** [comment]
@ssalaues I hope you could help me to found the problem :)

**Comment by ssalaues** [comment]
@lakano What version of the chart are you using? I know there was recently issues with the secrets that were fixed here https://github.com/helm/charts/pull/10693 .

I tested this on the latest which is v3.1.3 as of writing (you can ensure you're on the latest by running `helm repo update`)

- `kubectl create namespace redis-ha`
- `kubectl create secret generic redis --from-literal auth=redis123456 --namespace=redis-ha`
```
$ cat >> values.yaml <<EOF
auth: true
existingSecret: redis
EOF
```
- `helm install --name redis-ha stable/redis-ha -f values.yaml --namespace=redis-ha`
```
NAME:   redis-ha
LAST DEPLOYED: Tue Feb  5 10:41:09 2019
NAMESPACE: redis-ha
STATUS: DEPLOYED
```

**Comment by lakano** [comment]
Exact! My repo wasn't up to date!
Now, it's installed, thanks !
