### ISSUE TITLE
Jaeger exposes Elasticsearch password as configmap rather than secret

### ISSUE THREAD

**Issue by joeauty** [helm/charts#11172]
**Is this a request for help?**:

No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

feature request

The incubator/jaeger chart exposes the Elasticsearch password as a configmap rather than a secret:

https://github.com/helm/charts/blob/master/incubator/jaeger/templates/common-cm.yaml#L22

I would be happy to submit a PR to move this over to become a secret, but I'd like to know first whether this PR would be accepted, or if there is a more preferred convention for handling this? I also don't have experience with Cassandra, so I don't know if there might be some information there which should be moved over too, but I can look into this too.

**Comment by joeauty** [comment]
Totally tangential, but maybe not completely, the Elasticsearch Curator chart also exposes passwords in configmaps. Just bringing this up in case this has been part of a larger discussion I'm oblivious to?

**Comment by lcostea** [comment]
This would be a really good change and it would open up the path for using an existing secret (where we could use bitnami sealed secrets or aws-ssm to populate it).
I am also interested in such a change and I could help with the PR and I think all the es settings should go into a secret: es.server-urls, es.username, es.password
And probably a separate secret for cassandra settings
