### ISSUE TITLE
[stable/redis-ha] cluster info return: ERR This instance has cluster support disabled

### ISSUE THREAD

**Issue by lakano** [helm/charts#11188]
**Is this a request for help?**:
I suppose it's a problem of configuration yes.
 
---

**Version of Helm and Kubernetes**:
```
Helm
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

k8s
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/redis-ha 3.1.3 - tag 5.0.3

**What happened**:
May be @ssalaues could help me, I'm using the default configuration (excepted a CPU resources and secret/AUTH assigned), and after all pods created, the « cluster info » return « ERR This instance has cluster support disabled »
May be the default configuration is only HA ready, but not cluster ready (sharding) ?
I would like to use 3 masters + 3 slaves, so I kept the default value of 3 replicas (I suppose this will create the 3 slaves)

**What you expected to happen**:
Get a HA cluster (and not only a HA)

**How to reproduce it** (as minimally and precisely as possible):
Use the default configuration

**Anything else we need to know**:
I've surely not understood how to configure the values.yml to set a cluster mode with 3 masters and 3 slaves.
Thanks in advance for your time and help!

**Comment by lakano** [comment]
@ssalaues  I also precise, if I set in customConfig:
```
   customConfig: |-
      # Define configuration here
      cluster-enabled yes
      cluster-node-timeout 5000
```
The 2nd pod can't be created (STATUS Error), and the logs on the container redis inside this 2nd pod return:
```
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 4
>>> 'slaveof 10.43.74.91 6379'
replicaof directive not allowed in cluster mode

```

**Comment by ssalaues** [comment]
Currently the redis-ha chart doesn't support clustering mode. 

There are parts of the init script that are specifically only for master/slave mode that would have to be changed. For example the configuration of the `slaveof` directive.

Another thing that would have to change or be added is having a way to launch 6 individual Redis pods with only `cluster-enabled` and not in strictly replication mode. Once those 6 are up then a job can be ran to issue `redis-cli --cluster create <pod-0-ip>:<port> ... <pod-5-ip>:<port> ... --cluster-replicas 1` to instantiate the cluster as a whole. 

It's do able but would definitely require changes to the chart.

**Comment by lakano** [comment]
Ok thanks for your answer @ssalaues , I was confused because their is many reference to "cluster" in issues, so I've believed this chart support it.

Currently, I've created a STS with 6 pods, and linked manually with "redis-cli --cluster" (replace retrib.rb since 5.x), so I can get 3 masters + 3 slaves, but with this configuration, some time after may be crash of pod, I have a split brain. 

I don't use Sentinel, I don't known if it's related to my issue, and I don't known if it's necessary on a cluster mode since 5.x 

This could be awesome if redis-ha could sometime support the cluster mode ! :)

**Comment by taman9333** [comment]
I have same issue but with stable/redis !! any solutions @lakano ?

**Comment by lakano** [comment]
No @taman9333 I've stopped to use redis in cluster, too much problems.
