### ISSUE TITLE
[stable/jenkins] allow to expose slave listener port as hostPort

### ISSUE THREAD

**Issue by micw** [helm/charts#11186]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Which chart**:

stable/helm

**What happened**:

Jenkins listens for it's slaves on a specific TCP port. Within a cluster, this can easily be exposed as a service. But for the case that slaves are external, it's not that easy - especially on-premise if you don't have a TCP loadbalancer.

**What you expected to happen**:

The jenkins helm chart should provide an option to expose the slave listener port directly as hostPort. This should be disabled by default.

**How to reproduce it** (as minimally and precisely as possible):

Just try to expose the slave port on a fixed host port without having a load balancer.

**Anything else we need to know**:

A PR follows.

**Comment by albertogeniola** [comment]
Hi,
I see that the feature request has been merged, but I'd love to have some example in the readme about that.
