### ISSUE TITLE
[stable/elasticsearch] enableSysctlInitContainer used instead of sysctlInitContainer.enabled on client deployment

### ISSUE THREAD

**Issue by mechinn** [helm/charts#11195]
**Is this a request for help?**: 
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
BUG REPORT

**Version of Helm and Kubernetes**:
`helm version`
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
`kubectl version`
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-gke.1", GitCommit:"5c4fddf874319c9825581cc9ab1d0f0cf51e1dc9", GitTreeState:"clean", BuildDate:"2018-11-30T16:18:58Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/elasticsearch

**What happened**:
client pods do not have an init container to `sysctl -w vm.max_map_count=262144` due to the fact that it is checking for `enableSysctlInitContainer: true` instead of `sysctlInitContainer.enabled: true` like the master & data statefulsets do

**What you expected to happen**:
When `sysctlInitContainer.enabled: true` master & data statefulsets and client deployments should include an init container to run `sysctl -w vm.max_map_count=262144`

**How to reproduce it** (as minimally and precisely as possible):
`helm install stable/elasticsearch`

**Anything else we need to know**:
This looks like a typo from developing the feature and a late change to `sysctlInitContainer.enabled: true` from `enableSysctlInitContainer: true`

**Comment by mleneveut** [comment]
@trevex 
this commit is the problem : https://github.com/helm/charts/commit/471f21f11f9006c3a0c3df55704a4751d519d5bb

**Comment by mleneveut** [comment]
For those who don't want to wait for the fix or to clone the repo : 

```
helm install --name elasticsearch stable/elasticsearch --set enableSysctlInitContainer=true
```

**Comment by trevex** [comment]
I am sorry this was a typo on my end. Sorry about this. I will open a PR tomorrow morning ASAP.
