### ISSUE TITLE
[stable/sentry] Readiness and liveness probes for sentry workers

### ISSUE THREAD

**Issue by CCardosoDev** [helm/charts#11192]
**Is this a request for help?**:

Yes.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request.

**Version of Helm and Kubernetes**:
Helm version: v2.12.2
K8S version: v1.11.2

**Which chart**:
sentry.

**What happened**:
Celery workers stop processing tasks from time to time with the following type of error messages:

```
16:05:29 [WARNING] beacon: Failed sending beacon
16:05:29 [ERROR] multiprocessing: Process 'Worker-33' pid:47 exited with 'signal 9 (SIGKILL)'
20:05:19 [ERROR] multiprocessing: Process 'Worker-35' pid:49 exited with 'signal 9 (SIGKILL)'
10:05:21 [ERROR] multiprocessing: Process 'Worker-34' pid:48 exited with 'signal 9 (SIGKILL)'
12:00:03 [ERROR] multiprocessing: Process 'Worker-36' pid:50 exited with 'signal 9 (SIGKILL)'
12:00:05 [ERROR] multiprocessing: Process 'Worker-39' pid:53 exited with 'signal 9 (SIGKILL)'
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/billiard/pool.py", line 1175, in mark_as_worker_lost
human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).
12:00:05 [ERROR] celery.worker.job: Task sentry.tasks.reports.deliver_organization_user_report[edf8e147-114d-4462-b9ef-9dc06c9f75dd] raised unexpected: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).',) (data={u'hostname': 'celery@sentry-example-sentry-worker-758d88f9bc-bf9gp', u'name': 'sentry.tasks.reports.deliver_organization_user_report', u'args': '(1549238400.0, 604800, 1L, 2)', u'internal': False, u'kwargs': "{'dry_run': False}", u'id': 'edf8e147-114d-4462-b9ef-9dc06c9f75dd'})
12:05:18 [ERROR] multiprocessing: Process 'Worker-45' pid:59 exited with 'signal 9 (SIGKILL)'
15:05:20 [ERROR] multiprocessing: Process 'Worker-41' pid:55 exited with 'signal 9 (SIGKILL)'
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/billiard/pool.py", line 1175, in mark_as_worker_lost
human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).
15:05:21 [ERROR] celery.worker.job: Task sentry.tasks.process_buffer.process_pending[3c079df4-d2cc-487b-863e-33a675fd9681] raised unexpected: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).',) (data={u'hostname': 'celery@sentry-example-sentry-worker-758d88f9bc-bf9gp', u'name': 'sentry.tasks.process_buffer.process_pending', u'args': '[]', u'internal': False, u'kwargs': '{}', u'id': '3c079df4-d2cc-487b-863e-33a675fd9681'})
19:05:21 [ERROR] multiprocessing: Process 'Worker-38' pid:52 exited with 'signal 9 (SIGKILL)'
21:05:21 [ERROR] multiprocessing: Process 'Worker-37' pid:51 exited with 'signal 9 (SIGKILL)'
23:05:21 [ERROR] multiprocessing: Process 'Worker-42' pid:56 exited with 'signal 9 (SIGKILL)'
02:05:21 [ERROR] multiprocessing: Process 'Worker-40' pid:54 exited with 'signal 9 (SIGKILL)'
07:05:21 [ERROR] multiprocessing: Process 'Worker-43' pid:57 exited with 'signal 9 (SIGKILL)'
08:05:22 [ERROR] multiprocessing: Process 'Worker-44' pid:58 exited with 'signal 9 (SIGKILL)'
13:10:07 [ERROR] multiprocessing: Process 'Worker-49' pid:63 exited with 'signal 9 (SIGKILL)'
```
And when this happens we can see these type of messages on the UI: `Background workers haven't checked in recently. It seems that you have a backlog of 10053 tasks. Either your workers aren't running or you need more capacity.`

**What you expected to happen**:

I would expect that when this message occurs the works liveness prob would fail, but this does not happen since there is no such prob in place. Is there intentions to add liveness/readiness probs to sentry workers just like the web component has?  

**How to reproduce it**:

After installing a new instance of Sentry on K8S the workers work just fine, but after a few days or a few tasks processed the logs above start appearing and after some time (not sure how much) the workers processes are all dead. The only solution is to recreate the workers pods.

**Comment by virtuman** [comment]
were you ever able to solve this issue? having same problem .. any pointers?

**Comment by foal** [comment]
Have the same issue and resolve it by increasing the memory limit for workers twice

**Comment by CCardosoDev** [comment]
> Have the same issue and resolve it by increasing the memory limit for workers twice

I believe this is just a quick fix, there must be a way to define a readiness and liveness probs to handle extreme scenarios.

**Comment by alexey-gavrilov-flant** [comment]
maybe it will be useful https://github.com/helm/charts/pull/11847

**Comment by CCardosoDev** [comment]
This seems to be exactly what I was needing, thanks a lot.

**Comment by CH-anhngo** [comment]
@CCardosoDev  any luck to deal with the worker issue like this ? we started seeing it recently ?

**Comment by CCardosoDev** [comment]
Yes, I am using the new version of the chart with the probs (#11847) and till now it's working just fine :)
