### ISSUE TITLE
[stable/jenkins] Add ability to pass additional config files by path

### ISSUE THREAD

**Issue by muety** [helm/charts#11217]
I like the `AdditionalConfig` to write additional, custom files to `$JENKINS_HOME`. However, it only allows for the files' content to be defined inline. I would like to be able to reference an existing file on my local machine, which is then just copied over. This would be extremely helpful in situations, where your additional files are very large.

**Comment by maorfr** [comment]
I think its not possible to refrence files outside the chart scope...
