### ISSUE TITLE
[stable/airflow] Airflow scheduler does not start with -p parameter

### ISSUE THREAD

**Issue by moxordo** [helm/charts#11224]
**Is this a request for help?**:
YES
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm v2.12.1
Kube v1.12

**Which chart**:
stable/airflow

**What happened**:
Even when setting 
`schedulerDoPickle: true` in values.yaml, turns out the airflow scheduler does not start with the -p (DoPickle) parameter.
https://github.com/helm/charts/blob/eee84d29fdea80cd859d76210bd8262ad484ebd3/stable/airflow/values.yaml#L62

**What you expected to happen**:
I suppose appending the -p parameter to the command if `.Values.airflow.schedulerDoPickle` evaluates `true`. 
https://github.com/helm/charts/blob/eee84d29fdea80cd859d76210bd8262ad484ebd3/stable/airflow/templates/deployments-scheduler.yaml#L121

**How to reproduce it** (as minimally and precisely as possible):
The issue is apparent in the code.

**Anything else we need to know**:
Let me know if it was in deliberation the parameters were omitted.
Nope! Much obliged  for your efforts in maintaining this chart! @gsemet

**Comment by andykim92** [comment]
@gsemet Let me know if it would be better for me to write up a PR for this! =]

**Comment by gsemet** [comment]
Indeed this is a lost feature in the transition to kube/charts, sorry!

I do not use pickling, was unstable when I tested it. But either we remove this option or you can add it to the command line parameter.

There are 2 ongoing PR today. 0.16.0 is about to be merged, another PR will be opened soon (0.16.1) and you if you want to wait a little to submit 0.16.2, but you can test the stability of the pickling.

**Comment by andykim92** [comment]
@gsemet Nice! I will wait to submit to 0.16.2 =]. I'll try and test the stability of the pickling option on my side and update this thread with results!

**Comment by gsemet** [comment]
Hi. Have you had time to work on it? 0.17.0 is merged :)
