### ISSUE TITLE
InitScripts doesn't work

### ISSUE THREAD

**Issue by fznx-io** [helm/charts#11223]
**Is this a request for help?**:
Yes
---

**What happened**:
I want to add some command to Jenkins Master.
But no changes in my jenkins master, still no init script in my jenkins master container
**What you expected to happen**:
Container run the scripts every pods restart

**How to reproduce it** (as minimally and precisely as possible):
I added like this : 
  InitScripts:
    - sh "apt update"
    - sh "apt install vim"

**Comment by torstenwalter** [comment]
You can check this code to see where the `InitScripts` are used:
https://github.com/helm/charts/blob/master/stable/jenkins/templates/config.yaml#L255-L258

You can only provide groovy scripts here. They are executed by Jenkins during startup.
. [Post-initialization script](https://wiki.jenkins.io/display/JENKINS/Post-initialization+script)
- This repo contains some examples for init scripts: https://github.com/buildit/jenkins-startup-scripts/tree/master/scripts/scripts

**Comment by sellers** [comment]
@foosome  Did you switch to using Groovy for the script as @torstenwalter  mentioned?   

e.g. something like

InitScript:
  my-script-here: |-
    import jenkins.model.*
    groovy_code_here()
