### ISSUE TITLE
fluent-bit helm chart - support for stdout backend

### ISSUE THREAD

**Issue by mindgrep** [helm/charts#11248]
**Is this a request for help?**:
No, I would like to contribute a PR
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

The helm chart currently has (parametrized) the ability to choose from several backends, including the "test" backend which sets up the "file" output plugin. For testing, I find the "stdout" output plugin much more convenient/useful. Adding support for this should be trivial, and I can submit a PR for the same.

**Version of Helm and Kubernetes**:
helm: 2.12.3
k8s: 1.12.1

**Which chart**:
stable/fluent-bit

**Comment by Towmeykaw** [comment]
You could add it in the rawconfig section and just disable the other outputs.
