### ISSUE TITLE
[stable/traefik] Kvprovider Prefix Not Respected By ACME Storage Path

### ISSUE THREAD

**Issue by FrederikNJS** [helm/charts#11265]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
kubernetes: `Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`
helm: `Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}`

**Which chart**:
stable/traefik

**What happened**:
I switched to using Consul for storing the ACME certificates, in an effort to be able to run traefik in cluster mode.

Traefik started up correctly, got some certificates, and seemed to work fine. I decided to take a look in consul, and found that it had created both a `traefik-private` prefix (which I specified in the helm values) but also a `traefik` prefix. The `traefik-private` prefix contained most of the keys, but the ACME certificates seems to be stored under the `traefik` prefix.

Consul (`/`):
![image](https://user-images.githubusercontent.com/181295/52474889-088e1d00-2b9a-11e9-9101-2ac4bd741de3.png)

Consul (`/traefik-private/`, my configured prefix):
![image](https://user-images.githubusercontent.com/181295/52474897-15127580-2b9a-11e9-88b6-598a42cb25ae.png)

Consul (`/traefik-private/acme/`, notice missing `account`):
![image](https://user-images.githubusercontent.com/181295/52474913-1cd21a00-2b9a-11e9-992e-f00b491a950c.png)

Consul (`/traefik/`):
![image](https://user-images.githubusercontent.com/181295/52474920-252a5500-2b9a-11e9-8cb9-4153a08c8475.png)

Consul (`/traefik/acme/account/`):
![image](https://user-images.githubusercontent.com/181295/52474931-2ce9f980-2b9a-11e9-930b-794abcb1d0f8.png)

**What you expected to happen**:
I expected ALL keys created in Consul to be under my configured consul prefix. I intend to run multiple traefik ingress controllers on the same consul backend, currently I will be forced to share the same certificate storage for multiple completely different deployments of traefik.

**How to reproduce it** (as minimally and precisely as possible):
1. Set up Consul Cluster
2. Set up Traefik with values:
```
acme:
  challengeType: <your challenge type>
  email: <your LetsEncrypt email>
  enabled: true
kvprovider:
  consul:
    endpoint: <your consul hostname>:8500
    prefix: traefik-private #or your own preferred prefix
    watch: true
  storeAcme: true
```
3. Issue some certificates
4. Look in consul and see that 2 different prefixes have been created.

**Anything else we need to know**:
It seems to be due to https://github.com/helm/charts/blob/ae4e119ce28a642cd33466c51ea43cd1fbec1a44/stable/traefik/templates/configmap.yaml#L234 not being affected by my consul prefix configuration.

**Comment by FrederikNS** [comment]
Nope, not stale, a pull request has been posted for a fix

**Comment by FrederikNS** [comment]
Still not stale, there's ongoing activity in the pull request.

**Comment by nodesocket** [comment]
@FrederikNS I am also wondering does storing ACME (Let's Encrypt) on Consul work? I am seeing the following error:

> {"level":"error","msg":"Error building ACME client \u0026{Email: Registration:\u003cnil\u003e PrivateKey:[] KeyType: DomainsCertificate:{Certs:[] lock:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0}} ChallengeCerts:map[] HTTPChallenge:map[]}: private key was nil","time":"2019-10-22T04:52:05Z"}

**Comment by FrederikNS** [comment]
When I last used Traefik, the consul backend worked perfectly fine, my only problem was that all traefik installations on the cluster would share the same storage for the certificates.

That error makes me suspect that you haven't fully configured your Acme settings. Did you set an email?
