### ISSUE TITLE
[stable/airflow] private git repo doesnt seem to work

### ISSUE THREAD

**Issue by kalyanaramansanthanam** [helm/charts#11275]
**BUG REPORT**

I am trying to setup this chart using a private repo
the doc says you can use private repo by uploading private ssh keys as kube secrets
however, i noticed that the [git-clone.sh](https://github.com/helm/charts/blob/783788e36974f8da02fb144367bc995daa8774d7/stable/airflow/templates/configmap-git-clone.yaml#L12-L28) is not starting ssh-agent
so the initContainer is still failing on authentication

i am missing a step to start ssh-agent?

chart: stable/airflow

**Comment by wirehead** [comment]
Nope!  I created a password-less key so I didn't have to deal with ssh-agent, since it's mostly intended for GitHub repo-specific deploy keys with read-only access, not for uploading your primary SSH key.

**Comment by kalyanaramansanthanam** [comment]
i am using a passphrase-less read-only ssh key as well but i am not able to get it to work without starting the ssh-agent

**Comment by gsemet** [comment]
Seem like a configuration issue.

**Comment by dragid10** [comment]
@kalyanaramansanthanam were you able to figure this out? How do you start the ssh-agent, and if it is not needed, what is the proper configuration to do this?

**Comment by kalyanaramansanthanam** [comment]
can't help here since we have shelved using this chart for now and decided to take a DIY approach to managing the airflow service
