### ISSUE TITLE
[stable/percona] Persistence is not actually enabled by default

### ISSUE THREAD

**Issue by vreon** [helm/charts#1128]
The [README for the Percona chart](https://github.com/kubernetes/charts/blob/f357b77ed02ef0fc5bf8786f2a20d9cea38001aa/stable/percona/README.md) claims that persistence is enabled by default:

> | Parameter                  | Description                        | Default                                                    |
> | -----------------------    | ---------------------------------- | ---------------------------------------------------------- |
> | `persistence.enabled` | Create a volume to store data | true |
>
> By default a PersistentVolumeClaim is created and mounted into that directory. In order to disable this functionality you can change the values.yaml to disable persistence...

But [`values.yaml` defaults `persistence.enabled` to `false`](https://github.com/kubernetes/charts/blob/f357b77ed02ef0fc5bf8786f2a20d9cea38001aa/stable/percona/values.yaml#L32).

Should we fix the README or fix the default values?

**Comment by unguiculus** [comment]
We should fix the README. Could you submit a PR for this?

cc @CaptTofu
