### ISSUE TITLE
[stable/kong] Kong doesn't bind on port 80 and 443 using non-cloud kubernetes cluster

### ISSUE THREAD

**Issue by PatrickHuetter** [helm/charts#11299]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes v1.11.6
Rancher 2.1.6

**Which chart**:
stable/kong 0.9.2

**What happened**:
Everything deploys fine via helm (using rancher) and kong is running (with postgressql database included) except that kong doesn't listen on port 80 and 443 on my kubernetes worker nodes. Instead it's listening on some random higher ports (but working fine on them).

**What you expected to happen**:
I expected to have kong as ingress-controller listening on port 80 and 443 on all k8s worker nodes.

**How to reproduce it** (as minimally and precisely as possible):
Just deploy the helm chart with default settings and ingress-controller enabled on private, dedicated 3 node k8s cluster (not cloud).

**Anything else we need to know**:
I think the problem why kong isn't binding on port 80 and 443 is that i'm running a self hosted kubernetes cluster at hetzner. Maybe an option like ```hostNetwork: true``` is missing in the chart? 
I also had traefik as ingress controller running on port 80 and 443 in the past on an older k8s cluster but same setup without problems.

**Comment by szymonrychu** [comment]
Hey! I faced the same problem now! Did you get any resolution?
