### ISSUE TITLE
Setting InitContainerEnv 

### ISSUE THREAD

**Issue by ernestojeda** [helm/charts#11292]
**Is this a request for help?**:

Yes, need help with a PR

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
BUG REPORT

**Version of Helm and Kubernetes**:
Helm:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```
Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/jenkins

**What happened**:
When my valuesFile contains `InitContainerEnv` helm returns the following error:

```
# helm lint -f ../jenkins-values.yml stable/jenkins

[ERROR] templates/jenkins-master-deployment.yaml: unable to parse YAML
        error converting YAML to JSON: yaml: line 47: mapping values are not allowed in this context
```

Looking at the most recent commits to the repository, I found this PR: https://github.com/helm/charts/pull/9057. I was able to see that the indentation in the file`templates/jenkins-master-deployment.yaml` seems to have changed from the previous version causing the linting to fail:

Previous Line:
https://github.com/helm/charts/commit/c3e8c0b17ac553752ad0b2eecea315b61d14ce15#diff-3186f811e401dee5654955efc1ba4d42L71

Changed Line:
https://github.com/helm/charts/commit/c3e8c0b17ac553752ad0b2eecea315b61d14ce15#diff-3186f811e401dee5654955efc1ba4d42R92

**What you expected to happen**:
I expected the helm install to work with the settings defined in the jenkins-values.yml file

**How to reproduce it** (as minimally and precisely as possible):
`helm lint -f ../jenkins-values.yml stable/jenkins`

See attached jenkins-values.yml:
[jenkins-values.txt](https://github.com/helm/charts/files/2846960/jenkins-values.txt)

**Anything else we need to know**:
I am opening a PR to fix the issue. I will link to this issue.

**Comment by maorfr** [comment]
Good job on the quick fix :)
Feel free to close the issue if this is indeed fixed.

**Comment by ernestojeda** [comment]
Issue is fixed. Closing
