### ISSUE TITLE
Cannot set `extraVars` from `--set`

### ISSUE THREAD

**Issue by edfungus** [helm/charts#11295]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
v2.12.3

**Which chart**:
incubator/fluentd-cloudwatch

**What happened**:
I am trying to add `"{ name: FLUENT_UID, value: '0' }"` to `extraVars` via cmd line option `--set` but can't seem to find a way to add it. It either errors when parsing or errors when validating yaml

**What you expected to happen**:
I expect `DaemonSet.spec.template.spec.containers[0].env` to contain a the environment variable `FLUENT_UID` with a value of `0` like
```yaml
env:
- name: FLUENT_UID
  value: "0"
```

**How to reproduce it** (as minimally and precisely as possible):
`helm template fluentd-cloudwatch --set xxx > output.yaml`. Here are some of the`xxx` values I tried and the output in the yaml file

```yaml
# extraVars="{name: FLUENT_UID, value: '0'}"
env:
- name: FLUENT_UID
-  value: "0"

# extraVars="{name: FLUENT_UID\, value: '0'}"
env:
- name: FLUENT_UID, value: '0'

# extraVars[0]="{name: FLUENT_UID, value: '0'}"
env:
- [name: FLUENT_UID  value: '0']

# extraVars[0].name="FLUENT_UID",extraVars[0].value="0"
env:
- map[name:FLUENT_UID value:0]

# extraVars={"{name: FLUENT_UID, value: '0'}"} 
Error: failed parsing --set data: key "}" has no value

# extraVars=["{name: FLUENT_UID, value: '0'}"]
Error: failed parsing --set data: key " value: '0'}]" has no value

# extraVars=["{name: FLUENT_UID\, value: '0'}"]
Error: render error in "fluentd-cloudwatch/templates/daemonset.yaml": template: fluentd-cloudwatch/templates/daemonset.yaml:59:25: executing "fluentd-cloudwatch/templates/daemonset.yaml" at <.Values.extraVars>: range can't iterate over [{name: FLUENT_UID, value: '0'}]
```

**Anything else we need to know**:
Is there a way to do this? Help would be appreciated :)

**Comment by edfungus** [comment]
Ok, well it always happens that you find the answer right after posting an issue 😅

This ended up working: `extraVars[0]="\{ name: FLUENT_UID\, value: '0' \}"`

**Comment by aimarjs** [comment]
> Ok, well it always happens that you find the answer right after posting an issue 😅
> 
> This ended up working: `extraVars[0]="\{ name: FLUENT_UID\, value: '0' \}"`

Hey @edfungus 

How did you manage to get this working? For me, it will create the following mess. Very frustrating..

```
        env:
        - name: AWS_REGION
          value: us-east-1
        - name: LOG_GROUP_NAME
          value: kubernetes
        - "{ name: FLUENT_UID, value: 0 }"
```
