### ISSUE TITLE
[stable/minio] unable to upgrade or install when release strategy is set to Recreate

### ISSUE THREAD

**Issue by andrewnazarov** [helm/charts#11309]
**BUG REPORT**:

**Version of Helm and Kubernetes**:
K8s: 1.10.11-gke.1
Helm:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

**Which chart**:
[stable/minio] v.2.4.2

**What happened**:
I have a deployed release with the default strategy. If I want to change it later to Recreate my upgrade will fail with the error:
`Error: UPGRADE FAILED: Deployment.apps "s3" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'`

**What you expected to happen**:
I want it to be upgraded.

**How to reproduce it** (as minimally and precisely as possible):
Install the minio chart with default values.
Try to upgrade the release setting DeploymentUpdate.type to Recreate.

**Anything else we need to know**:
The error is due to https://github.com/kubernetes/kubernetes/issues/24198
Using this chart I cannot set strategy.rollingUpdate to null.

**Comment by andrewnazarov** [comment]
Actually, I cannot even install it from scratch setting DeploymentUpdate.type to Recreate since this part is hardcoded:
```
rollingUpdate:
      maxSurge: {{ .Values.DeploymentUpdate.maxSurge }}
      maxUnavailable: {{ .Values.DeploymentUpdate.maxUnavailable }}

```
Hence the following error appears:
`Deployment.apps "s3" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy "type" is 'Recreate'`

**Comment by chrisingenhaag** [comment]
Hello,
I just created a PR for this as I´m running into the same issue.

see #11546  @nitisht @wlan0 

regards, christian
