### ISSUE TITLE
[stable/prometheus] Prometheus does not scrap metrics from pods with /metrics endpoint

### ISSUE THREAD

**Issue by kamilgregorczyk** [helm/charts#11308]
Hi, why prometheus doesn't collect metrics from pods which have /metrics endpoint and that return body in prometheus format? I have few services running in kubernetes and I thought prometheus would detect (somehow) them as it does with kubernetes api. If prometheus doesn't detect it on its own, how is it possible to tell prometheus that there is something to scrap? (except changing prometheus config file as that's probably not recommended and not scalable)

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

**Which chart**:
stable/prometheus

**What happened**:
Prometheus does not scrap metrics from services that have /metrics endpoint

**What you expected to happen**:
Prometheus should somehow detect that target or there should be a way of defining (labeling?) deployments that have metrics

**Comment by Zefool** [comment]
If you take a look at the values file you will see some job configurations. 

The gist is: annotate your pod with 
prometheus.io/scrape = true
prometheus.io/path = /metrics (this is the default and can be omitted)
prometheus.io/port = #####

You'll need to quote all these for kubernetes.

**Comment by kamilgregorczyk** [comment]
thanks, will give it a try

**Comment by kamilgregorczyk** [comment]
Yes, it worked, it would be great to add such statement to the documentation and README that's printed after installing prometheus via helm

**Comment by Zefool** [comment]
Glad it did. I agree about the documentation, will you put in a PR?

**Comment by phongnx1** [comment]
@kamilgregorczyk Can you help me how to resolve this issue, I had seen value.yml but I don't understand how to fix this!

**Comment by kamilgregorczyk** [comment]
You need to annotate your services with proper tags which are defined in value.yml

**Comment by kamilgregorczyk** [comment]
That worked for me: https://github.com/kamilgregorczyk/sample-micronaut-blog/blob/master/kubernetes/Service.yaml#L9

**Comment by TeslaC-137** [comment]
How do I specify multiple ports if my pod is exposing metrics at multiple pods.

**Comment by runningman84** [comment]
You should use a servicemonitor which can scrape multiple ports.
