### ISSUE TITLE
[stable/heapster] service name causes top to fail

### ISSUE THREAD

**Issue by mikesplain** [helm/charts#1132]
When using the stable/heapster chart I'm seeing `kubectl top nodes` fail with:
```
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
```

I was wondering if heapster might need additional labels such as 
```
kubernetes.io/cluster-service: "true"
````
 however it looks like the service needs: 
* running in the `kube-system` namespace 
* named `heapster`

Running in the correct namespace could be left to the user using the `--namespace` flag, but should we consider dropping https://github.com/kubernetes/charts/blob/master/stable/heapster/templates/service.yaml#L4 to `.Chart.Name`?

**Comment by unguiculus** [comment]
cc @jose5918

**Comment by jose5918** [comment]
@mikesplain Do you think something along these lines would work for you?https://github.com/jose5918/charts/commit/109b6aa2644b06f4754fd9826845a1e35f809d29

**Comment by mikesplain** [comment]
@jose5918 Yep! That's perfect, though I think you have a typo here: 
https://github.com/jose5918/charts/blob/109b6aa2644b06f4754fd9826845a1e35f809d29/stable/heapster/templates/service.yaml#L10
I had to change it to `.Values.service.labels`

**Comment by jose5918** [comment]
@mikesplain Thanks for catching that. Didn't have a chance to test it yesterday

**Comment by ferminromero** [comment]
@jose5918 Any plans to send out a PR for this?
I think the way heapster chart is currently set up is surprising (e.g. I expected our horizontal pod autoscalers to work out of the box after installing the chart)

**Comment by jose5918** [comment]
@ferminromero Sorry about that. Thank you for reminding me. I had forgotten a few things since I was busy moving recently.
