### ISSUE TITLE
[stable/fluent-bit] output configmap when using extraEntries.output is malformed

### ISSUE THREAD

**Issue by bnookala** [helm/charts#11332]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**: Helm v2.11.0, Kubernetes v1.9.11

**Which chart**: stable/fluent-bit

**What happened**:

Adding output configuration to values.yaml `extraEntries.output`, and then running `helm template` produces a malformed fluentbit output configuration:

Input in values.yaml:

```
extraEntries:
    output: |-
        [OUTPUT]
          Name        azure
          Match       *
          Customer_ID workspaceid
          Shared_Key  secretkey
```

Output in fluent-bit configmap from `helm template`
```
  fluent-bit-output.conf: |-

    [OUTPUT]
        Name          forward
        Match         *
        Host          fluentd
        Port          24284
        Retry_Limit False

        [OUTPUT]
          Name        azure
          Match       *
          Customer_ID workspaceid
          Shared_Key  secretkey
```

As seen above, the azure plugin configuration is indented too much, causing fluent-bit containers to crash on start due to the malformed configuration:

```
Fluent Bit v1.0.4
Copyright (C) Treasure Data

[2019/02/11 19:09:41] [  Error] File fluent-bit-output.conf
[2019/02/11 19:09:41] [  Error] Error in line 9: Each key must have a value
````

**What you expected to happen**:

The configmap output by `helm template` should contain the correct indentation, and thus a correct config:

```
  fluent-bit-output.conf: |-

    [OUTPUT]
        Name          forward
        Match         *
        Host          fluentd
        Port          24284
        Retry_Limit False

    [OUTPUT]
        Name        azure
        Match       *
        Customer_ID workspaceid
        Shared_Key  secretkey
```

**How to reproduce it** (as minimally and precisely as possible):

1. Fetch the stable/fluent-bit chart
2. Modify the values.yaml file to include an extra output entry:

```
extraEntries:
  output: |-
    [OUTPUT]
      Name        azure
      Match       *
      Customer_ID workspaceid
      Shared_Key  secretkey
```
3. Run `helm template . > test.yaml` and observe the malformed configuration
4. Run `kubectl apply -f test.yaml` to apply helm template
5. Run `kubectl logs -lapp=fluent-bit` to view logs from fluent bit containers:

```
Fluent Bit v1.0.4
Copyright (C) Treasure Data

[2019/02/11 19:09:41] [  Error] File fluent-bit-output.conf
[2019/02/11 19:09:41] [  Error] Error in line 9: Each key must have a value
```

**Anything else we need to know**:

**Comment by kfox1111** [comment]
We had a big discussion/reimplementation about this a while ago. We finally settled on:

extraEntries is for adding additional lines to the existing things.

rawConfig is for adding as many additional sections as you want.

So it is working as intended.

**Comment by bnookala** [comment]
I've confirmed that using `rawConfig` does work, so I'll close this issue out. Thanks for the pointer.
