### ISSUE TITLE
[stable/airflow] install-requirements.sh script should be always available

### ISSUE THREAD

**Issue by mgaggero** [helm/charts#11353]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

  - Describe *in detail* the feature/behavior/change you'd like to see.

The install-requirements.sh script should be available even if the persistence is enabled.
There are cases when persistence is enabled (for example using NFS volumes) and initContainer is necessary to populate the dag folder from a Git repo at initialization.
In this moment, if persistence is enabled, the scripts volume is not mounted and the install-requirements.sh cannot be found nor executed.

**Version of Helm and Kubernetes**:
Helm:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

Kubernetes:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

stable/airflow

**What happened**:
If persistence is enabled, the scripts volume is not mounted and the install-requirements.sh cannot be found nor executed.

**What you expected to happen**:
Scripts volume should be mounted and the install-requirements.sh should be available even if persistence is enabled.

**Comment by gsemet** [comment]
Hi. I would be glad to have a pull request for this.
