### ISSUE TITLE
[stable/kibana] Failing to import predefined Kibana dashboard

### ISSUE THREAD

**Issue by zoyapronyakova** [helm/charts#11368]
Is this a request for help? YES
Is this a BUG REPORT?  Might be a bug

**Version of Helm and Kubernetes**:
Helm: Client v2.8.0, Server v2.9.1
Kubernetes: 1.13.2

**Which chart**:
https://github.com/helm/charts/tree/master/stable/kibana with changing values as below:
dashboardImport:
  xpackauth:
    timeout: 120
    enabled: true
  dashboards:
    k8s: https://raw.githubusercontent.com/monotek/kibana-dashboards/master/k8s-fluentd-elasticsearch.json

(taken from https://github.com/helm/charts/blob/master/stable/kibana/ci/url_dashboard-values.yaml example)

**What happened**:
Kibana is up and working, however the provided Kibanan dashboard is not imported and when i am looking at the logging of kibana pod -> kibana-dashboardimport container, i get the following error:
Importing k8s dashboard...
k8s is not valid JSON, assuming it's an URL...
* About to connect() to localhost port 5601 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5601 (#0)
* Server auth using Basic with user ''
> POST /api/kibana/dashboards/import?force=true HTTP/1.1
 > Authorization: Basic Og==
 > User-Agent: curl/7.29.0
 > Host: localhost:5601
 > Accept: */*
 > kbn-xsrf:true
 > Content-type:application/json
 > Content-Length: 46251
 > Expect: 100-continue
 > 
 < HTTP/1.1 100 Continue
 } [data not shown]
< HTTP/1.1 503 Service Unavailable
 < retry-after: 30
 < content-type: text/html; charset=utf-8
 < cache-control: no-cache
 < content-length: 30
< Date: Wed, 13 Feb 2019 08:58:34 GMT
 < 
 { [data not shown]
* Closing connection 0
Kibana server is not ready yet
Import of k8s dashboard finished :-)

Seems that kibana gets green status although elasticsearch is not ready
I added the following change before the import request in the templates/configmap-dashboardimport.yaml and solved the issue
echo "Waiting up to {{ .Values.dashboardImport.timeout }} seconds for Elasticsearch to get in green overall state..."
    for i in {1..{{ .Values.dashboardImport.timeout }}}; do
      curl -s -H "kbn-xsrf:true" -X POST  "http://127.0.0.1:5601/api/console/proxy?path=_cluster%2Fhealth&method=GET" | python -c 'import sys, json; print json.load(sys.stdin)["status"]' 2> /dev/null | grep green > /dev/null && break || sleep 1
    done

**What you expected to happen**:
The dashboard provided as URL is imported and i can see it in Kibana in Dashboard tab

**How to reproduce it** (as minimally and precisely as possible):
I've already installed elasticsearch stable version, fluentD and Fluent-bit
then I am installing the Kibana, providing values as described below.
The deployment is successful, however the dashboard is not in Kibana

Would really appreciate your help
Thanks!
Zoya

**Comment by pipko** [comment]
Please re-open the issue, it's absolutely correct. Seems that container kibana-dashboardimport starts before kibana and can't import json to kibana's url because kibana wait for this container to finish.

**Comment by zoyapronyakova** [comment]
> open the issue, it's

I don't have permissions :(

**Comment by pipko** [comment]
Create a new one?
