### ISSUE TITLE
Cannot configure advertised listeners to use host ip for external clients 

### ISSUE THREAD

**Issue by jasimsulaiman** [helm/charts#11370]
**Is this a request for help?**: Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
$ helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-04T07:48:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
incubator/kafka

**What happened**:
External client cannot connect to kafka pod, as it cannot resolve the external domain configured as EXTERNAL in ADVERTISED_LISTENER

**What you expected to happen**:
When a Kafka pod is restarted, applications can connect to the pod.

**How to reproduce it** (as minimally and precisely as possible):

    1. Run Kafka with this chart with values file updated to rbac.enabled=true,external.enabled=true,external.advertised.listeners="EXTERNAL://kafka.cluster.local:$((31090+${KAFKA_BROKER_ID}))",external.listener.security.protocol.map="PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"

    2. Start an external client that connects to Kafka using kafka.cluster.local:31090

    3. External client cannot connect to Kafka as it cannot resolve domain `kafka.cluster.local`.

**Anything else we need to know**:

Changing https://github.com/helm/charts/blob/master/incubator/kafka/templates/statefulset.yaml#L152 to pass the host ip as env should enable to use `$(HOST_IP)`  to configure ADVERTISED_LISTENERS in values.yaml```        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP```

**Comment by cjmalloy** [comment]
Bump

**Comment by TsuyoshiUshio** [comment]
The same.

**Comment by TsuyoshiUshio** [comment]
In my case, I found something. 

# Command 

```bash 
helm install --name ts-kafka incubator/kafka --set replicas=1,prometheus.jmx.enabled=true,prometheus.kafka.enabled=true,external.enabled=true,external.type=LoadBalancer,external.loadBalancerIP[0]=<IP_ADDRESS>,configurationOverrides.advertised.listeners="EXTERNAL://<IP_ADDRESS>:31090",'configurationOverrides.listener.security.protocol.map="PLAINTEXT:PLAINTEXT\,EXTERNAL:PLAINTEXT"'
```

# log 

The environment variables set however, configuration doesn't seem to reflected. 
```
  : 
KAFKA_ADVERTISED=map[listeners:EXTERNAL://<IP_ADDRESS>:31090]
KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://ts-kafka-0.ts-kafka-headless.default:9092
  : 
KAFKA_LISTENER=map[security:map[protocol:map[map:"PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"]]]
  : 
[2019-04-05 22:01:28,012] INFO KafkaConfig values:
        advertised.host.name = null
        advertised.listeners = PLAINTEXT://ts-kafka-0.ts-kafka-headless.default:9092
             : 
        listener.security.protocol.map = PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
        listeners = PLAINTEXT://0.0.0.0:9092
``` 
```
