### ISSUE TITLE
Error on HELM values-production.yaml

### ISSUE THREAD

**Issue by rshibley** [helm/charts#11382]
When i run without values-production.yaml it works otherwise I receive the following error on this command 

`helm install stable/redis --values values-production.yaml --name redis`

Error: release redis failed: StatefulSet in version "v1beta2" cannot be handled as a StatefulSet: v1beta2.StatefulSet.Spec: v1beta2.StatefulSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Command: []string: decode slice: expect [ or n, but found ", error found in #10 byte of ...|command":"/run.sh","|..., bigger context ...|,"/opt/bitnami/redis/etc/master.conf"],"command":"/run.sh","env":[{"name":"REDIS_REPLICATION_MODE","|...

**Comment by juan131** [comment]
Hi @rshibley I was unable to reproduce the issue.

What version of the Redis Helm chart are you using? Did you update the Helm repository?

```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
$ helm install stable/redis --values values-production.yaml --name redis
NAME:   redis
LAST DEPLOYED: Thu Feb 14 09:37:52 2019
NAMESPACE: default
STATUS: DEPLOYED
...
$ kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
redis-master-0                   1/1     Running   0          2m24s
redis-metrics-5888d9d78b-7ktwr   1/1     Running   0          2m24s
redis-slave-56695c4f8f-2dlh8     1/1     Running   0          2m24s
redis-slave-56695c4f8f-6fj9g     1/1     Running   0          2m24s
redis-slave-56695c4f8f-dgq4s     1/1     Running   0          2m24s
```

**Comment by rshibley** [comment]
I forgot to update my repo!!! Thanks 👍
