### ISSUE TITLE
Error while installing elasticsearch chart

### ISSUE THREAD

**Issue by jrosskopf** [helm/charts#114]
Hey,

I'am unable to install the current state of the elasticsearch chart. When I execute the install command from the chart's Readme I get an JSON paring error:

```
[root@kube-master-1 ~]# helm install --name es-test-1 charts/incubator/elasticsearch
Error: release es-test-1 failed: [unable to decode "": [pos 301]: json: decNum: got first char '"', unable to decode "": [pos 301]: json: decNum: got first char '"', unable to decode "": [pos 288]: json: decNum: got first char '"']
```

The issue is a little bit hard to debug, as the input of this chart is all yaml and I don't know if and where the intermediate json gets stored.

**Comment by prydonius** [comment]
Fixed in #115
