### ISSUE TITLE
psql: FATAL:  password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by bmcgair** [helm/charts#11404]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:

**Which chart**:
stable/postgres

**What happened**:
 helm install --name bitnami-sucks stable/postgresql --set "persistence.storageClass=postgres-plain,persistence.size=100Gi"

 export POSTGRES_PASSWORD=$(kubectl get secret --namespace default bitnami-sucks-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
kubectl port-forward --namespace default svc/bitnami-sucks-postgresql 5432:5432
psql --host 127.0.0.1 -U myuser
psql: FATAL:  password authentication failed for user "myuser"

**What you expected to happen**:
Not to waste my whole damn day with this BS chart

**How to reproduce it** (as minimally and precisely as possible):
Follow the steps above

**Anything else we need to know**:

**Comment by bmcgair** [comment]
It sure looks like the image is expecting:
POSTGRESQL_PASSWORD=
POSTGRESQL_USERNAME=postgres

but your chart is setting:
POSTGRES_PASSWORD=mypass
POSGRES_USER=myuser

When the chart is run with:
  helm install --name bitnami-sucks stable/postgresql --set "postgresqlUsername=myuser,postgresqlPassword=my_pass,persistence.storageClass=postgres-plain,persistence.size=100Gi"

Thanks for that. I'll never get the last 6 hours back.

**Comment by tompizmor** [comment]
**First issue:**

>helm install --name bitnami-sucks stable/postgresql --set "persistence.storageClass=postgres-plain,persistence.size=100Gi"
>
>export POSTGRES_PASSWORD=$(kubectl get secret --namespace default bitnami-sucks-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
kubectl port-forward --namespace default svc/bitnami-sucks-postgresql 5432:5432
psql --host 127.0.0.1 -U myuser
psql: FATAL: password authentication failed for user "myuser"

You can't login with the user `myuser` because you did not specify it when deploying the chart. In that case, the default value is `postgres` as it can be seen in the [values.yaml](https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml#L75).

**Second issue:**

> When the chart is run with:
helm install --name bitnami-sucks stable/postgresql --set "postgresqlUsername=myuser,postgresqlPassword=mypass,persistence.storageClass=postgres-plain,persistence.size=100Gi"

If you specify a custom user other than `postgres`, you should also specify a database name. This is clearer when launching the container directly as an error message pops up but kubernetes hide this error with a retry. We should improve this use case so it is clear.

If you run the following command it should work:

```
helm install --name postgresql stable/postgresql --set "postgresqlUsername=myuser,postgresqlPassword=mypass,postgresqlDatabase=myuserdb,persistence.storageClass=postgres-plain,persistence.size=100Gi"
```

Regarding the different sets of env vars, the bitnami/postgresql containers supports both but `POSTGRES_` env vars have preference over `POSTGRESQL_` ones. We did this so the chart can also be used with the Docker postgres image.

**Comment by bmcgair** [comment]
Unfortunately in the midst of my testing, I cut and pasted the wrong command above.  Here are the results from your command, which give the same (broken) results:
```
helm install --name postgresql stable/postgresql --set "postgresqlUsername=myuser,postgresqlPassword=mypass,postgresqlDatabase=myuserdb,persistence.storageClass=postgres-plain,persistence.size=100Gi"

Forwarding from 127.0.0.1:5432 -> 5432
Forwarding from [::1]:5432 -> 5432
psql --host 127.0.0.1 -U myuser
Handling connection for 5432
psql: FATAL:  database "myuser" does not exist
```
If I try the postgres user it works with no password:

```
ubuntu@ip-10-40-125-14:~$ psql --host 127.0.0.1 -U postgres
Handling connection for 5432
psql (9.5.14, server 10.6)
WARNING: psql major version 9.5, server major version 10.
         Some psql features might not work.
Type "help" for help.

postgres=# 
```
When I get the env on the container itself:
```
root@f36dc5169125:/container-deploy# kubectl exec -it postgresql-postgresql-0 -- /bin/bash
I have no name!@postgresql-postgresql-0:/$ env |grep POST
POSTGRESQL_REPLICATION_PASSWORD=
ENDPOINTS_POSTGRESQL_PORT_5432_TCP_PORT=5432
POSTGRESQL_POSTGRESQL_SERVICE_PORT_POSTGRESQL=5432
ENDPOINTS_POSTGRESQL_SERVICE_PORT=5432
POSTGRESQL_POSTGRESQL_SERVICE_HOST=10.43.194.234
POSTGRESQL_POSTGRESQL_PORT=tcp://10.43.194.234:5432
POSTGRESQL_REPLICATION_MODE=master
POSTGRESQL_CLUSTER_APP_NAME=walreceiver
POSTGRESQL_INITDB_WALDIR=
POSTGRESQL_POSTGRESQL_PORT_5432_TCP_PORT=5432
POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
POSTGRESQL_POSTGRESQL_PORT_5432_TCP=tcp://10.43.194.234:5432
POSTGRES_DB=myuserdb
ENDPOINTS_POSTGRESQL_SERVICE_HOST=10.43.171.253
POSTGRESQL_MASTER_PORT_NUMBER=5432
ENDPOINTS_POSTGRESQL_PORT_5432_TCP_PROTO=tcp
POSTGRESQL_DATABASE=
ENDPOINTS_POSTGRESQL_PORT_5432_TCP=tcp://10.43.171.253:5432
POSTGRESQL_DATA_DIR=/bitnami/postgresql
ENDPOINTS_POSTGRESQL_PORT_5432_TCP_ADDR=10.43.171.253
POSTGRES_PASSWORD=mypass
POSTGRESQL_PORT_NUMBER=5432
POSTGRESQL_POSTGRESQL_PORT_5432_TCP_ADDR=10.43.194.234
POSTGRES_USER=myuser
POSTGRESQL_POSTGRESQL_PORT_5432_TCP_PROTO=tcp
ENDPOINTS_POSTGRESQL_PORT=tcp://10.43.171.253:5432
POSTGRESQL_POSTGRESQL_SERVICE_PORT=5432
POSTGRESQL_MASTER_HOST=
POSTGRESQL_REPLICATION_USER=
ENDPOINTS_POSTGRESQL_SERVICE_PORT_POSTGRESQL=5432
POSTGRESQL_PASSWORD=
POSTGRESQL_USERNAME=postgres
POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=0
POSTGRESQL_INITDB_ARGS=
```

**Comment by bmcgair** [comment]
Unfortunately I cut and pasted the wrong command above. I was trying to devolve the issue to the simplest case. Here's the actual cmd I'm using:

```
  helm install --name db-mydb stable/postgresql --set "service.type=LoadBalancer,postgresqlUsername=myuser,postgresqlPassword=mypass,postgresqlDatabase=mydb,persistence.storageClass=postgres-plain,persistence.size=100Gi"
```
You'll notice I'm using a load balancer. I'm also annotating the ELB so that it has a dns name.

```
  kubectl annotate service mydb-postgresql "external-dns.alpha.kubernetes.io/hostname=mydb.ucoachapp.com, \
                                                        service.beta.kubernetes.io/aws-load-balancer-internal="0.0.0.0/0"
```
This all works and the ELB comes up properly but I can't login:
```
PGPASSWORD="mypass"
 psql -h db-bmcgair.ucoachapp.com -U inside_track bmcgair
Password for user inside_track: 
psql: FATAL:  password authentication failed for user "inside_track"
```
It does work if I do it this way
```
export SERVICE_IP=$(kubectl get svc --namespace default db-mydb --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")

PGPASSWORD="mypass" psql --host $SERVICE_IP --port 5432 -U myuser mydb
```
so that's some progress...

**Comment by bmcgair** [comment]
Sorry guys, I was attempting to narrow the problem down to the most basic case and cut and pasted the wrong helm command above. 

```
helm install --name bitnami-sucks stable/postgresql --set "service.type=LoadBalancer,postgresqlUsername=myusers,postgresqlPassword=mydb,postgresqlDatabase=mydb,persistence.storageClass=postgres-plain,persistence.size=100Gi"
```
Was the actual cmd I was testing with. Providing the db name on the cmdline does help. Though I'm still seeing some oddness that I can't quite characterize yet...

**Comment by bmcgair** [comment]
Yeah I don't know what the bug is here, but it keeps coming up. Here's what afaik is a completely default install:
```
root@ba21020ad806:/container-deploy# helm install --name db-dumper stable/postgresql --set "postgresqlUsername=myuser,postgresqlPassword=mypass,postgresqlDatabase=mydb,persistence.storageClass=postgres-plain,persistence.size=1024Gi"
NAME:   db-dumper
LAST DEPLOYED: Fri Feb 15 02:49:57 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME                  TYPE    DATA  AGE
db-dumper-postgresql  Opaque  1     1s

==> v1/Service
NAME                           TYPE       CLUSTER-IP    EXTERNAL-IP  PORT(S)   AGE
db-dumper-postgresql-headless  ClusterIP  None          <none>       5432/TCP  1s
db-dumper-postgresql           ClusterIP  10.43.234.69  <none>       5432/TCP  0s

==> v1beta2/StatefulSet
NAME                  DESIRED  CURRENT  AGE
db-dumper-postgresql  1        1        0s

==> v1/Pod(related)
NAME                    READY  STATUS    RESTARTS  AGE
db-dumper-postgresql-0  0/1    Init:0/1  0         0s


NOTES:


** Please be patient while the chart is being deployed **

PostgreSQL can be accessed via port 5432 on the following DNS name from within your cluster:

    db-dumper-postgresql.default.svc.cluster.local - Read/Write connection
To get the password for "myuser" run:

    export POSTGRES_PASSWORD=$(kubectl get secret --namespace default db-dumper-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run db-dumper-postgresql-client --rm --tty -i --restart='Never' --namespace default --image bitnami/postgresql --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host db-dumper-postgresql -U myuser



To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/db-dumper-postgresql 5432:5432 &
    PGPASSWORD="mypass" psql --host 127.0.0.1 -U myuser

root@ba21020ad806:/container-deploy#     export POSTGRES_PASSWORD=$(kubectl get secret --namespace default db-dumper-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
root@ba21020ad806:/container-deploy#     kubectl run db-dumper-postgresql-client --rm --tty -i --restart='Never' --namespace default --image bitnami/postgresql --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host db-dumper-postgresql -U myuser
psql: FATAL:  password authentication failed for user "myuser"
pod "db-dumper-postgresql-client" deleted
pod default/db-dumper-postgresql-client terminated (Error)
root@ba21020ad806:/container-deploy# helm install --name db-dumper stable/postgresql --set "postgresqlUsername=myuser,postgresqlPassword=mypass,postgresqlDatabase=mydb,persistence.storageClass=postgres-plain,persistence.size=1024Gi"^C
root@ba21020ad806:/container-deploy# kubectl run db-dumper-postgresql-client --rm --tty -i --restart='Never' --namespace default --image bitnami/postgresql --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host db-dumper-postgresql -U myuser mydb
psql: FATAL:  password authentication failed for user "myuser"
pod "db-dumper-postgresql-client" deleted
pod default/db-dumper-postgresql-client terminated (Error)
```

**Comment by sello4354** [comment]
I am facing similar issue and below is the command i used to deploy the helm chart : 
helm install azure-marketplace/postgresql --version=4.2.1 --name in1-psql-release --set global.imagePullSecrets={empotysecret} --set networkPolicy.enabled=true --set postgresqlPassword=******** . My Postgres is deployed in azure k8s service

**Comment by rakesh-007** [comment]
psql: FATAL:  password authentication failed for user "sonarUser"

**Comment by rakesh-007** [comment]
We can reset the password for PostgreSQL, documentation of how to do this is already provided by bitnami.
I have applied this & it's working perfectly fine.

https://docs.bitnami.com/aws/infrastructure/postgresql/administration/change-reset-password/
