### ISSUE TITLE
Spinnaker '/gate' redirection rule does not work

### ISSUE THREAD

**Issue by bartosznalewajka** [helm/charts#11420]
**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

**Which chart**:
`stable/spinnaker	1.7.0        	1.11.6     	Open source, multi-cloud continuous delivery platform for...`

**What happened**:
I've got a problem with installing Spinnaker using Helm on GKE. I installed fresh Spinnaker installation (with `ingress.enabled` set to `false`). I run SSH tunnels (for both `9000` and `8084`) and Deck works correctly on `localhost:9000`. 

The problem is when I'm trying to do anything more, e.g. list applications. When Deck is trying to call `http://localhost:9000/gate`, it returns `503 Service Unavailable` error code. But when I'm trying to call directly `http://localhost:8084` - it works. 

Seems that there is some problem with apache configuration on Deck pod (which I didn't change). Apache configuration looks like this:

```www-data@spin-deck-88d75d74c-8mklf:/etc/apache2/sites-enabled$ apachectl -S
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.20.1.32. Set the 'ServerName' directive globally to suppress this message
VirtualHost configuration:
*:80                   10.20.1.32 (/etc/apache2/sites-enabled/000-default.conf:1)
*:9000                 10.20.1.32 (/etc/apache2/sites-enabled/spinnaker.conf:1)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex proxy: using_defaults
Mutex default: dir="/var/run/apache2/" mechanism=default
Mutex watchdog-callback: using_defaults
Mutex proxy-balancer-shm: using_defaults
Mutex rewrite-map: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33 not_used
Group: name="www-data" id=33 not_used
```

And `spinnaker.conf` looks like this:

```
www-data@spin-deck-88d75d74c-8mklf:/etc/apache2/sites-enabled$ cat /etc/apache2/sites-enabled/spinnaker.conf
<VirtualHost 0.0.0.0:9000>
  DocumentRoot /opt/deck/html

  ProxyPass "/gate" "http://localhost:8084" retry=0
  ProxyPassReverse "/gate" "http://localhost:8084"
  ProxyPreserveHost On

  <Directory "/opt/deck/html/">
    Require all granted
  </Directory>
</VirtualHost>
```

And apache logs indicates:

> [Thu Feb 14 14:44:59.124227 2019] [proxy:error] [pid 40:tid 140118190905088] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:8084 (localhost) failed
> [Thu Feb 14 14:44:59.124318 2019] [proxy_http:error] [pid 40:tid 140118190905088] [client 127.0.0.1:51722] AH01114: HTTP: failed to make connection to backend: localhost

**What you expected to happen**:
Spinnaker works? ;)

**How to reproduce it** (as minimally and precisely as possible):
Just install it on GKE cluster with values:

```ingress:
  enabled: false

dockerRegistries:
- address: "gcr.io"
  email: "my@mail.com"
  name: "my-gcr"
  username: _json_key
  password: '-- file content--'

rbac:
  create: false

minio:
  enabled: true

s3:
  enabled: false

serviceAccount:
  create: true

spinnakerFeatureFlags:
  - artifacts
  - infrastructure-stages
  - jobs
  - pipeline-templates
```

**Anything else we need to know**:
I can confirm that problem doesn't occur on previous 1.6.1 version.

**Comment by rushrecon** [comment]
Could you, please, show `kubectl describe po` for spin-gate pode?
I have similar issue and
`  Warning  Unhealthy          2s (x21 over 3m22s)     kubelet, gke-mycluster-gke-clu-mycluster-gke-clu-c72c3ea1-9xq0  Readiness probe failed: Get http://10.20.1.7:8084/health: dial tcp 10.20.1.7:8084: connect: connection refused`
on gate pod.

**Comment by bartosznalewajka** [comment]
I just found this PR: https://github.com/helm/charts/pull/11397. Could someone confirm it's related to my and @rushrecon problem?

**Comment by milesmatthias** [comment]
@bartosznalewajka this is the behavior we were seeing when I sent that PR. You can get yourself unblocked by manually updating the apache config on the deck pod by changing `localhost` to `spin-gate.spinnaker` and restarting apache. Hoping @paulczar will get a chance to review the PR so we can merge it soon.

**Comment by milesmatthias** [comment]
https://github.com/helm/charts/pull/11397 has been merged, so please close this issue.

**Comment by strigazi** [comment]
Is this fixed? I still see localhost:8084 in the deck pod, when using: `spinnaker-1.13.2	1.12.5`
