### ISSUE TITLE
[stable/jenkins]: Deployment rollingUpdate field set to true when it should be an object

### ISSUE THREAD

**Issue by lachie83** [helm/charts#11423]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm: v2.13.0-rc.1, Kubernetes: v1.14.0-alpha.3

**Which chart**: stable/jenkins

**What happened**:

If Persistence.Enabled=false then the Deployment template is broken.

```
$ helm --namespace jenkins -n jenkins -f ./jenkins-values.yaml install stable/jenkins
Error: release jenkins failed: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Strategy: v1.DeploymentStrategy.RollingUpdate: readObjectStart: expect { or n, but found t, error found in #10 byte of ...|gUpdate":true,"type"|..., bigger context ...|ns-jenkins-master"}},"strategy":{"rollingUpdate":true,"type":"RollingUpdate"},"template":{"metadata"|...
```

The rollingUpdate field definition is an Object put the chart is passing in a bool of true.
```
FIELDS:
   rollingUpdate	<Object>
     Rolling update config params. Present only if DeploymentStrategyType =
     RollingUpdate.
```

This bug was introduced in https://github.com/helm/charts/pull/11166. I suggest we back out that change and re-assess other possible solutions

**Comment by sharmagaurav03** [comment]
Hello, I am still facing this issue at the same step.

Error: release jenkins failed: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Resources: v1.ResourceRequirements.Requests: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', error found in #10 byte of ...|:{"cpu":"","memory":|..., bigger context ...|riodSeconds":10},"resources":{"requests":{"cpu":"","memory":"512
