### ISSUE TITLE
[stable/keycloak] Allow custom values in JGROUPS_DISCOVERY_PROTOCOL and JGROUPS_DISCOVERY_PROPERTIES when in high availability mode 

### ISSUE THREAD

**Issue by twistyWater** [helm/charts#11435]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: Helm v2.12.2 Kubernetes 1.12.5

**Which chart**: stable/keycloak

**What happened**: JGROUPS_DISCOVERY_PROTOCOL and  JGROUPS_DISCOVERY_PROPERTIES have a default value that we cannot override. I would want to use KUBE_PING instead of DNS_PING. For that we need to set those 2 env variables.

**What you expected to happen**: Have a chart where those 2 env variables are customizable. Either have access to override values or extra vars. jgroup discovery properties should support format namespace=keycloak,labels="app=keycloak"

**How to reproduce it** (as minimally and precisely as possible):
helm upgrade --install --namespace keycloak --values values.yml keycloak-local stable/keycloak 

or

helm upgrade --install --namespace keycloak --set keycloak.replicas=2, keycloak.jgroups.discory_protocol=KUBE_PING,keycloak.jgroups.discovery_properties="namespace=keycloak,labels="app=keycloak""  keycloak-local stable/keycloak 

**Anything else we need to know**: I am available for PR

**Comment by unguiculus** [comment]
Thanks. I'll have a look.

**Comment by unguiculus** [comment]
Please test if this meets your needs.

**Comment by twistyWater** [comment]
Sorry for the delay, I will test it this weak

**Comment by unguiculus** [comment]
The Keycloak chart here is being deprecated (#13316) and moved to a new home:
https://github.com/codecentric/helm-charts

I'm closing this issue. Feel free to open a new issue in the new repo. Thanks.
