### ISSUE TITLE
Issue in helm "rabbimq-ha" chat if --> prometheus: enabled: true

### ISSUE THREAD

**Issue by AnudeepKumarDonthu** [helm/charts#11442]
issue ID 11414 is raised, mine is similar issue

**Is this a request for help?**: 
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Version of Helm and Kubernetes**:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
rabbitmq-ha

**What happened**:
We are facing issue while installing helm chat "rabbitmq-ha" by making prometheus: enabled:  true and if the value is false we can able to install the chat without any issue.

If the entry in values.yaml as below we are facing below issue.

ENTRY IN values.yaml File:
=============================================
prometheus:
  ## Configures Prometheus Exporter to expose and scrape stats.
  exporter:
    enabled: true

EROR MESSAGE:
=============================================
error: validation failed: [unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", ung.coreos.com/v1"]

**What you expected to happen**:
I am expected to install rabbitmq-ha chat with above ERROR MESSAGE and to start "kbudde/rabbitmq-exporter" container which will help to monitOo the RABBITMQ metrics in prometheus

**How to reproduce it** (as minimally and precisely as possible):
1) Get the rabbitmq-ha chat from belowgithub link 
    https://github.com/helm/charts/tree/master/stable/rabbitmq-ha
2) Open values.yaml file and find for "prometheus:" in that you can find sub child with "enabled: false" and change that to "enabled: true"
3) Then install the chat using command "helm install rabbitmq-ha"
4) Then above ERROR MESSAGE will come.

![helminstallerrormessgae](https://user-images.githubusercontent.com/24874185/52848905-e8c89d00-3135-11e9-9685-3348a5fae6e1.jpg)
![valuesyamlfile](https://user-images.githubusercontent.com/24874185/52848907-e9613380-3135-11e9-88a2-1efdba429cd9.jpg)

**Comment by AnudeepKumarDonthu** [comment]
Updated the Error Message:
===============================================================
Error: validation failed: [unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]

**Comment by steven-sheehy** [comment]
If you knew it was similar, why did you open a new issue? See my response to #11414.

**Comment by AnudeepKumarDonthu** [comment]
Even I I made the operator also true.... Even though it is showing the same error message

**Comment by steven-sheehy** [comment]
That's great, but it needs to be false I'd you're not using the Prometheus operator.

**Comment by AnudeepKumarDonthu** [comment]
If I disable Prometheus operator it is working and I am not sure what exactly Prometheus operator will do.
My requirement is to get the rabbitmq metrics using Prometheus. Is that can be achieved with out Prometheus operator?
