### ISSUE TITLE
[stable/postgresql] Initdbscripts mount path has changed after the PR https://github.com/helm/charts/pull/11233

### ISSUE THREAD

**Issue by adityasood** [helm/charts#11446]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Version of Helm and Kubernetes**: 

**Which chart**: PostgreSQL

**What happened**: Chart Functionality is broken due to the PR https://github.com/helm/charts/pull/11233. It restricts users to use bitnami postgres docker image as the official docker image ignores these files

**What you expected to happen**: The mount path for initdbScripts should not change. This leads to the docker-entrypoint.sh to not acknowledge the file and it ignores it due to [this](https://github.com/docker-library/postgres/blob/master/9.6/docker-entrypoint.sh#L145)

**How to reproduce it** add an initdbscript, it will not be executed as the check [here](https://github.com/docker-library/postgres/blob/master/9.6/docker-entrypoint.sh#L145) ignores it.

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting. I created PR that fixes the issue. However, I think it would make sense to also create PRs to Docker Inc's container so it supports subfolders.
