### ISSUE TITLE
Add vsliouniaev as a trusted collaborator

### ISSUE THREAD

**Issue by vsliouniaev** [helm/charts#11445]
Would like to help speed up work on prometheus-operator chart

I helped get the first stage of this across the line:
https://github.com/helm/charts/pull/6765
contributing more PRs and checking various issues around the same prometheus-operator chart. Would like to help out @gianrubio in maintaining it.

Here is a major issue still requiring helm changes that I'm tracking
https://github.com/helm/charts/issues/9241
Here are numerous PRs for the chart:
https://github.com/helm/charts/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Avsliouniaev

**Comment by unguiculus** [comment]
Invite sent.
