### ISSUE TITLE
RollingUpdate: readObjectStart: expect { or n, but found t, error found in #10 byte of

### ISSUE THREAD

**Issue by xrobeva** [helm/charts#11448]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  BUG REPORT

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

**Which chart**:
charts/stable/jenkins 
version: 0.32.1

**What happened**:
When Jenkins is deployed with .Values.Persistence.Enabled set to false, the deployment fails with this error message:
Error: release testing-udm-jenkins-66-dn failed: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment: Spec: v1.DeploymentSpec: Strategy: v1.DeploymentStrategy: RollingUpdate: readObjectStart: expect { or n, but found t, error found in #10 byte of ...|gUpdate":true,"type"|..., bigger context ...|dn-jenkins-master"}},"strategy":{"rollingUpdate":true,"type":"RollingUpdate"},"template":{"metadata"|...

**What you expected to happen**:
The deployment finishs SUCCESS

**How to reproduce it** (as minimally and precisely as possible):
Setting the .Values.Persistence.Enabled to false

**Anything else we need to know**:
This change "https://github.com/helm/charts/commit/07fc9dbdef1d658eec3cad50de718662381dfe9c" breaks the deployment.
rollingUpdate: {{ if .Values.Persistence.Enabled }}{{ else }}true{{ end }}
 .spec.strategy.rollingUpdate is a dictionary and the change sets a boolean.

**Comment by maorfr** [comment]
Duplicate of #11423

**Comment by maorfr** [comment]
Hey @xrobeva,

Can this issue be closed?

**Comment by xrobeva** [comment]
Yes, you can.
Our deployment is already working 
Thanks

**Comment by maorfr** [comment]
Go ahead and close it :)
