### ISSUE TITLE
InitdbScripts and initdbScriptsSecret error

### ISSUE THREAD

**Issue by jose-joye** [helm/charts#11449]
BUG REPORT

chart: 3.11.0

With this new chart, if we add the following to the values.yaml:

```
initdbScripts:
  setup.sql: |
    CREATE USER dbuser WITH PASSWORD 'secret';
    CREATE DATABASE mydb WITH OWNER dbuser;
```

The script is not executed at the first run.
It seems that the reason is due to the definition in line 188 of the statefulset.yaml

        - name: custom-init-scripts
          mountPath: /docker-entrypoint-initdb.d/configmap

Having the mountpath to the configmap directory seems not ok to me. It should be mounted directly under the directory above. Otherwise, the scripts are not executed.

--> removing this subpath, fixed the issue for me.

---------------------------------------------------------------------

The second issue I found is due to the initdbScriptsSecret  
Setting the following:
```
initdbScriptsSecret:
  set-maintenance-user.sql: |
    CREATE USER maintenance_user WITH PASSWORD 'fullysecret';
    ALTER  USER maintenance_user WITH SUPERUSER;
    CREATE DATABASE mydb WITH OWNER dbuser;
```

will generate an error during helm install:

```
helm install --name jose-backup2 .  --debug --namespace cbcd-testing
[debug] Created tunnel using local port: '44867'

[debug] SERVER: "127.0.0.1:44867"

[debug] Original chart version: ""
[debug] CHART PATH: /home/a80829872/postgresql

Error: YAML parse error on postgresql/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 108: could not find expected ':'
```

**Comment by javsalgar** [comment]
Hi,

I created a PR that fixes the issue with the mount path (it is not compatible with Docker Inc's PostgreSQL container).

https://github.com/helm/charts/pull/11482

Regarding the secret, in that parameter, you are supposed to use an existing secret, as mentioned in the README. You need to previously create the secret and use its name in the values.yaml file.

**Comment by javsalgar** [comment]
However, note that the use of secrets is not supported in Docker Inc's official PostgreSQL image, only the Bitnami PostgreSQL container.

**Comment by carrodher** [comment]
Hi @ajoyej, once #11482 was merged, can you confirm if the issue is fixed?

**Comment by ajoyej** [comment]
Hi,
Thanks for the fix! 
I double checked the code and it looks good to me

José

**Comment by carrodher** [comment]
Nice! Thanks for the confirmation, you can close the issue (or a bot will close it automatically in 15 days, as you prefer 😄 )
