### ISSUE TITLE
How to make ethereum helm data peristent?

### ISSUE THREAD

**Issue by amolmishra23** [helm/charts#11459]
**Is this a request for help?**: Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Am not sure

**Version of Helm and Kubernetes**:

	helm : "v2.12.3"
	kubernetes: "v1.13.3"

**Which chart**:

	https://github.com/helm/charts/tree/master/stable/ethereum

**What happened**:
	
	Not able to figure how to make blockchain persistent

**What you expected to happen**:
Example: 
in the geth-miner.deployment.yaml,
for the volume, present by default:

	volumes:
	      - name: data
	        emptyDir: {}
If i change it to, something like, 

	volumes:
	      - name: data
	        persistentVolumeClaim:
	          claimName: geth-miner

Where this PVC would be amazon EBS using storage class on my AWS.
I was expecting, now my block chain would be persistent, as emptyDir lifetime is just as lifetime of Pod. PVC could solve the issue. 
But what's happening is, when i have more than one replica of geth-miner, only one of the replica's is able to mount the persistent volume. And other 2 replica's go in Crash loop backoff state. 
Whats the right way to solve this issue?

**How to reproduce it** (as minimally and precisely as possible):

Just follow the above para, and you should be able to understand it. 
Make changes in geth-miner.deployment.yaml

	volumes:
	      - name: data
	        persistentVolumeClaim:
	          claimName: geth-miner

Make a new PVC meanwhile for geth-miner on aws. 
And try installing the helm chart.
All 3 replica's wont launch. Only 1 replica launches and will give crash loop backoff error. 

**Anything else we need to know**:
If I am expecting it wrong way, please correct me, whats the right way to go about it.

**Comment by WyseNynja** [comment]
Did you ever come up with a solution for this?
