### ISSUE TITLE
[stable/nginx-ingress] The '-' in the name prevents it from being used effectively as a dependency

### ISSUE THREAD

**Issue by yuvipanda** [helm/charts#1146]
If I have a custom values.yaml with values like:

```yaml
nginx-ingress:
   defaultBackendService: "something"
```

and I attempt to access it as `  {{ if .Values.nginx-ingress.defaultBackendService -}}` it fails, with an error:

```
Error: UPGRADE FAILED: parse error in "jupyterhub/templates/proxy.yaml": template: jupyterhub/templates/proxy.yaml:32: bad character U+002D '-'
```

So either the nginx-ingress should be automatically rewritten as nginxIngress, or the chart should be renamed (or I am confused about how to access values of a subchart from parent chart)

**Comment by yuvipanda** [comment]
If there's a way to get at .Values.nginx-ingress dynamically (uh, .Values.Get "nginx-ingress" or some such? I doubt it tho) it might work too.

**Comment by mgoodness** [comment]
So you're trying to refer to child values from a parent chart? If so, [this](https://github.com/kubernetes/helm/blob/master/docs/charts.md#importing-child-values-via-requirementsyaml) is how.
