### ISSUE TITLE
[stable/mongodb] impossible to pass extra args to mongodb_exporter

### ISSUE THREAD

**Issue by Zaspire** [helm/charts#11478]
**Version of Helm and Kubernetes**:
latest

**Which chart**:
latest

mongodb_exporter can expose additional metrics(https://github.com/percona/mongodb_exporter/blob/master/mongodb_exporter.go#L49)
but they are behind the flags and turn off by default.
It would be great to have an option to enable them.

**Comment by javsalgar** [comment]
Hi

Thanks for reporting. I created a PR that covers your use case https://github.com/helm/charts/pull/11488

**Comment by Zaspire** [comment]
Thank you!
works great for me.

turns out mongodb_exporter image is way outdated(0.3 vs 0.6.3 latest).
But it's not hard to build it myself(there is not official image:( )  and override default values.

**Comment by javsalgar** [comment]
At some point we would like to build the image ourselves and have it updated as we do with other assets. However, there are no short term plans to do so
