### ISSUE TITLE
"Kubernetes frontend couldn't provision a volume: no available backends for storage class basic (will retry upon resync)"  in ontap-san

### ISSUE THREAD

**Issue by anujakh** [helm/charts#11481]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm version v2.11.0

**Which chart**:
Mongo Db replicaset

**What happened**:
Kubectl pvc status pending

Output of kubectl describe pvc

Name:          datadir-my-release-mongodb-replicaset-0
Namespace:     default
StorageClass:  basic
Status:        Pending
Volume:
Labels:        app=mongodb-replicaset
               release=my-release
Annotations:   volume.beta.kubernetes.io/storage-provisioner: netapp.io/trident
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
Events:
  Type       Reason                Age                     From                         Message
  ----       ------                ----                    ----                         -------
  Normal     ExternalProvisioning  4m18s (x17445 over 3d)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "netapp.io/trident" or manually created by system administrator
  Normal     ProvisioningFailed    2m21s (x100 over 101m)  netapp.io/trident            no available backends for storage class basic
Mounted By:  <none>

**What you expected to happen**:
pvc must be binded and pods should be in running state

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
 ./tridentctl -n trident get storageclass basic -o json
{
  "items": [
    {
      "Config": {
        "version": "1",
        "name": "basic",
        "attributes": {
          "backendType": "ontap_san"
        },
        "storagePools": null,
        "additionalStoragePools": null
      },
      "storage": {}
    }
  ]
}
 here ii is showing empty storage

**Comment by vsliouniaev** [comment]
This error reads like a configuration issue with your specific storage provider rather than an issue with the chart
