### ISSUE TITLE
[stable/minio] Minio falls into pod has unbound immediate PersistentVolumeClaims (repeated 2 times)

### ISSUE THREAD

**Issue by rennokki** [helm/charts#11516]
**Is this a request for help?**: YES

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm 2.12.1, DigitalOcean 1.13.2

**Which chart**: stable/minio

**What happened**: The fourth statefulset of the distributed minio configuration falls into an error of `pod has unbound immediate PersistentVolumeClaims (repeated 2 times)`. The pods are being blocked like this:
```
minio-0                                          1/1     Running     2          6m5s
minio-1                                          1/1     Running     2          5m35s
minio-2                                          1/1     Running     2          5m7s
minio-3                                          0/1     Pending     0          4m47s
```

In my case, only 3/6 (the amount of replicas i need) PVs got created:
```
pvc-d2df4770-3416-11e9-9e3b-1adf13cb1193   50Gi       RWO            Delete           Bound    default/export-minio-0                  do-block-storage            6m54s
pvc-e4b2f22a-3416-11e9-9e3b-1adf13cb1193   50Gi       RWO            Delete           Bound    default/export-minio-1                  do-block-storage            6m24s
pvc-f582b832-3416-11e9-9e3b-1adf13cb1193   50Gi       RWO            Delete           Bound    default/export-minio-2                  do-block-storage            5m55s
```

The PVCs, however, got created properly:
```
export-minio-0                  Bound     pvc-d2df4770-3416-11e9-9e3b-1adf13cb1193   50Gi       RWO            do-block-storage   7m35s
export-minio-1                  Bound     pvc-e4b2f22a-3416-11e9-9e3b-1adf13cb1193   50Gi       RWO            do-block-storage   7m5s
export-minio-2                  Bound     pvc-f582b832-3416-11e9-9e3b-1adf13cb1193   50Gi       RWO            do-block-storage   6m37s
export-minio-3                  Pending
```

**What you expected to happen**: I expect to create the fourth statefulset and run off the distributed mode properly.

**How to reproduce it** (as minimally and precisely as possible): Install the chart with `distributed` as mode, and with service like this:
```yaml
service:
  type: ClusterIP
  clusterIP: None
```

**Anything else we need to know**: Either it's 4, 6, 8 and i assume more than 8, it always break on creating the fourth statefulset. I am currently working with a DO K8s Cluster.

**Comment by rennokki** [comment]
Upgraded the helm client, the problem still persists. The fourth PV for the fourth statefulset is not creating by any means. Thoughts? 😢

**Comment by rennokki** [comment]
It seems like DigitalOcean has a restriction on Block Storage Volumes i can create. This is not a Minio bug or something.

**Comment by barakethan** [comment]
Any news on that? What should we do?

**Comment by rennokki** [comment]
In the last reply i said that it was a DO limitation. I had 7 used volumes, tried to create 4 and the first 3 worked but the 4th did not because i reached the limit of 10 volumes.

**Comment by praveenvp07** [comment]
I am trying a standalone minio deployment using helm and once when I tried for an upgrade using values.yaml , I am getting same error. I have only 3 volumes in DigitalOcean, still facing the same issue. Controller is trying to create new pod but old one not getting destroyed thus pvc is still in bound state.This seems to be some issue with `minio `.


```
minio-67b876bc46-8b22x   1/1     Running             0          3d
minio-fb8f5c4d8-bnmdt    0/1     ContainerCreating   0          4m2s
```
```
pod has unbound immediate PersistentVolumeClaims (repeated 2 times)
```

**Comment by saadzimat430** [comment]
facing the same error... using minikube
