### ISSUE TITLE
[stable/concourse] Provide a changelog that communicate our changes

### ISSUE THREAD

**Issue by cirocosta** [helm/charts#11512]
Hey,

With some notable breaking changes that have been introduced, it'd be good for the consumers of this chart to quickly know what those breaking changes are and how to migrate from one version to another.

I've seen a few charts adopting a `CHANGELOG` file for that purpose:

- [gocd](https://github.com/helm/charts/blob/master/stable/gocd/CHANGELOG.md)
- [sysdig](https://github.com/helm/charts/blob/master/stable/sysdig/CHANGELOG.md)
- [falco](https://github.com/helm/charts/blob/master/stable/falco/CHANGELOG.md)

Do you have any opinions around that?

I feel like right now it's not very straightforward for users who are not frequent contributors to know about those changes. Although we try not to introduce many of those, sometimes it's necessary, thus, concisely communicating them seems pretty essential.

Wdyt?

thx!

**Comment by oradwell** [comment]
great idea. I've recently started creating charts for internal use and was looking to see if community charts had changelogs. I think having a change log should be part of best practices.

**Comment by YoussB** [comment]
I am going to be working on that starting from the worker only deployment #11280

**Comment by cirocosta** [comment]
This just got in in #12920 🙌
