### ISSUE TITLE
[incubator/patroni] Add option to select Postgres version

### ISSUE THREAD

**Issue by Adriien-M** [helm/charts#11522]
In order to specify the Postgres version used by spilo, we have to set the `PGVERSION` environment variable. (see release [10-1.4-p8](https://github.com/zalando/spilo/releases/tag/spilo-10-1.4-p8))

Currently, Spilo supports the versions 9.3, 9.4, 9.5, 9.6 or 10 (default) so it is useful to specify this variable...

I did a pull request to add this option.

**Comment by Adriien-M** [comment]
Please can someone review the pull request? Because I'm stuck and I'd like to pull another request depending on it...

**Comment by CaminGui** [comment]
+1 to have this configurable

**Comment by fbeauche** [comment]
From what i can see in Spilo repo , PGVERSION is a build argument of the Dockerfile so not sure it can be used in a chart. 

You would use a different image to use a diffement postgres version!

**Comment by Adriien-M** [comment]
@fbeauche The `PGVERSION` is specified in the Dockerfile to set the default version to use (the latest).

However, the spilo image contains multiple versions of Postgres (from 9.3 to 10). Indeed in our company, we use Patroni with Postgre version 10 for our applications and another Patroni with Postgres version 9.6 for our private Gitlab.

To confirm my says, you can check the changelog of the version of [spilo-10-1.4-p8](https://github.com/zalando/spilo/releases/tag/spilo-10-1.4-p8) which explain the usage of this variable...

**Comment by fbeauche** [comment]
@Adriien-M indeed your right, sorry i did not check correctly the Dockerfile.

**Comment by Adriien-M** [comment]
Is this chart dead? Noone to validate my PR?
