### ISSUE TITLE
Grafana helm chart: pod failing readonly file-system

### ISSUE THREAD

**Issue by anirvanr** [helm/charts#11526]
I tried to install grafana using below command 
```
helm install --name grafana --namespace grafana stable/grafana
```

But it failed and the error message
```
  Normal   Pulling                47s                kubelet, ip-172-20-20-100.eu-central-1.compute.internal  pulling image "grafana/grafana:5.4.3"
  Normal   Pulled                 39s                kubelet, ip-172-20-20-100.eu-central-1.compute.internal  Successfully pulled image "grafana/grafana:5.4.3"
  Normal   Pulled                 19s (x2 over 37s)  kubelet, 172-20-20-100.eu-central-1.compute.internal  Container image "grafana/grafana:5.4.3" already present on machine
  Normal   Created                18s (x3 over 38s)  kubelet, 172-20-20-100.eu-central-1.compute.internal  Created container
  Warning  Failed                 18s (x3 over 38s)  kubelet,172-20-20-100.eu-central-1.compute.internal  Error: failed to start container "grafana": Error response from daemon: error setting label on mount source '/var/lib/kubelet/pods/1234-5678-90/volume-subpaths/config/grafana/0': read-only file system
  Warning  BackOff                9s (x4 over 29s)   kubelet,172-20-20-100.eu-central-1.compute.internal  Back-off restarting failed container
```

Kubernetes version : 1.10.3
OS-IMAGE: Container Linux by CoreOS 1967.6.0 (Rhyolite)

Can you please help me on this ?

**Comment by maorfr** [comment]
This may be a problem with Kubernetes version 1.10.3, as stated here:
https://github.com/kubernetes/kubernetes/issues/64120#issuecomment-393338115

I may be wrong though ;)

**Comment by revandarth** [comment]
@anirvanr did you find any solution for this. I am seeing the problem with k8s version * v1.10.3*. 
`Error: failed to start container "grafana": Error response from daemon: error setting label on mount source '/var/lib/kubelet/pods/3a05c416-3baf-11e9-825e-02a83c48df5c/volume-subpaths/ldap/grafana/1': read-only file system
Back-off restarting failed container`
