### ISSUE TITLE
[stable/grafana] Provide automatic redeployment option on configuration change

### ISSUE THREAD

**Issue by vsliouniaev** [helm/charts#11528]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature Request

**Which chart**: stable/grafana

**What happened**: When changing the password or altering some configuration of the .ini section in the values file the grafana pod stays up and new values are not loaded. It is necessary to delete the pod before changes are applied.

**What you expected to happen**: An option to be available in values that will cause the pod to be updated and new values to be loaded. This could be done by doing a hash of the configuration used in the various configuration options.

**How to reproduce it** (as minimally and precisely as possible):

1. Deploy the chart with default values
2. Do a chart upgrade without changing the values - the password in the secret will be re-created but the grafana pod will not be updated.

**Anything else we need to know**:

* I am happy to work on a PR for this feature if it is desirable.
* I would like to know if there's a list of configurations that should be subject to this so I'm not missing anything I'm not currently aware of.

Replaces: #8798
Relates to : #7891, #11525, #11551

**Comment by maorfr** [comment]
Hey @vsliouniaev,

Thanks for bringing this up, and sorry for letting the previous issue get closed.
I will gladly approve such a PR!

There isn't a list of configuration files, but I trust your judgement.

Your contribution is appreciated!

**Comment by lee0c** [comment]
I also ran into issues re: the secret changing in the cluster without the pod updating. Happy to make a PR for this if you're not @vsliouniaev ?

**Comment by maorfr** [comment]
seems that this is now implemented in the chart as checksums for various files (configs, secrets, etc).

@vsliouniaev can you take a look at the chart and let me know if this issue can be closed?
