### ISSUE TITLE
[stable/prometheus-operator] Grafana configuration

### ISSUE THREAD

**Issue by cloud-rocket** [helm/charts#11525]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: Helm:  v2.12.3, Kubernetes; 1.11.6-gke.2

**Which chart**: prometheus-operator

**What happened**: Grafana configuration is not updated

**What you expected to happen**: Passing additional Grafana configuration via custom values.yaml the same way as with official Grafana chart should be allowed. 

**How to reproduce it** (as minimally and precisely as possible):

the following `custom.yaml` should affect grafana configuration

```
grafana:
  grafana.ini:

  ## LDAP Authentication can be enabled with the following values on grafana.ini
  ## NOTE: Grafana will fail to start if the value for ldap.toml is invalid
    auth.ldap:
      enabled: true
      allow_sign_up: true
      config_file: /etc/grafana/ldap.toml
    server:
      root_url: http://grafana.example.com
```

**Anything else we need to know**:

**Comment by vsliouniaev** [comment]
Looks to be the same issue as this:
https://github.com/helm/charts/issues/8798
