### ISSUE TITLE
Rabbitmq-ha management error

### ISSUE THREAD

**Issue by eamonnmcevoy** [helm/charts#11524]
**Is this a request for help?**: yes

---

**Version of Helm and Kubernetes**:
kubectl
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.11", GitCommit:"1bfeeb6f212135a22dc787b73e1980e5bccef13d", GitTreeState:"clean", BuildDate:"2018-09-28T21:35:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

helm
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Error: cannot connect to Tiller

**Which chart**:
rabbitmq-ha

**What happened**:
I installed on aks using the default settings.
I used kubectl port forwarding to access the management interface: `kubectl port-forward rabbitmq-ha-0 15672:15672`.
I login at localhost:15672. no data is displayed in the management interface. Some tabs are displaying errors:

`TypeError: Cannot read property 'name' of undefined TypeError: Cannot read property 'name' of undefined at Array.process (eval at compile (http://localhost:15672/js/ejs-1.0.min.js:1:6654), :100:139) at EJS.render (http://localhost:15672/js/ejs-1.0.min.js:1:1885) at format (http://localhost:15672/js/main.js:1086:21) at http://localhost:15672/js/main.js:444:24 at with_reqs (http://localhost:15672/js/main.js:1068:9) at http://localhost:15672/js/main.js:1064:17 at XMLHttpRequest.req.onreadystatechange (http://localhost:15672/js/main.js:1144:17)`

**What you expected to happen**:
to be able to use management plugin

**How to reproduce it** (as minimally and precisely as possible):
install rabbitmq-ha with default settings. happens on aks and local docker cluster

**Anything else we need to know**:
I am installing by running the helm template command, followed by kubectl apply -Rf

**Comment by pingod** [comment]
i have the same error

**Comment by steven-sheehy** [comment]
This sounds like a bug in rabbitmq itself or an issue with version skew in your cluster, which was fixed in PR https://github.com/helm/charts/pull/11982

**Comment by soulseen** [comment]
same issue in appVersion: 3.8.1 with the image tag 3.8.1-alpine.

**Comment by airclear** [comment]
same issue in appVersion: 3.8.1 with the image tag 3.8.5-alpine.
