### ISSUE TITLE
[stable/prometheus-operator] Synced alerts from upstream projects use different selection labels from chart

### ISSUE THREAD

**Issue by vsliouniaev** [helm/charts#11527]
The stable/prometheus-operator chart has scripts that will automatically sync alerts and dashboards from upstream projects. In some cases it is possible for these alerts to have alternate selectors due to the upstream project having a different deployment process. For example:
```
count_values("config_hash", alertmanager_config_hash{job="{{ $alertmanagerJob }}"}) BY (service) / ON(service) GROUP_LEFT() label_replace(prometheus_operator_spec_replicas{job="{{ $operatorJob }}",controller="alertmanager"}, "service", "alertmanager-$1", "name", "(.*)") != 1
```
[source](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/alertmanager/rules/alertmanager.rules.yaml#L26)

This alert uses a relabel expression to select an alertmanager service that does not get deployed by the chart, and so it will never trigger.

---

Creating a completely universal script that is capable of dealing with these conditions may be beyond the scope of this project, however, validating the functionality of the alerts, and amending the configuration to function with the chart is still necessary.

What are your thoughts on this, @paskal @gianrubio ?

**Comment by paskal** [comment]
I'm sorry, but what's the problem? Script make such substitutions and define these variables in the beginning of the script:
```
{{- $alertmanagerJob := printf "%s-%s" (include "prometheus-operator.fullname" .) "alertmanager" }}
<...>
      expr: count_values("config_hash", alertmanager_config_hash{job="{{ $alertmanagerJob }}",namespace="monitoring"}) BY (service) / ON(service) GROUP_LEFT() label_replace(prometheus_operator_spec_replicas{job="{{ $operatorJob }}",namespace="monitoring",controller="alertmanager"}, "service", "alertmanager-$1", "name", "(.*)") != 1
```
[source](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/alertmanager/rules/alertmanager.rules.yaml#L4)
It was defined that way before I've introduced auto-sync and I've re-used this mechanism in the synchronization script.

Could you please rephrase, what is the problem exactly?

**Comment by paskal** [comment]
Replacement rule:
```python
{
    'job="alertmanager-main"': {
        'replacement': 'job="{{ $alertmanagerJob }}"',
        'init': '{{- $alertmanagerJob := printf "%s-%s" (include "prometheus-operator.fullname" .) "alertmanager" }}'},
}
```
Currently entry title get replaced by `replacement` value, and `init` value added to file header.

Only current problem I see (after sync I've done) is many lines like this introduced:
```
expr: increase(prometheus_tsdb_compactions_failed_total{job="{{ $prometheusJob }}",namespace="monitoring"}[2h]) > 0
```
This namespace selector is not proper and need to be replaced with actual namespace of deployment.

**Comment by vsliouniaev** [comment]
The issue is with the `label_replace` function used as part of the alert expression.

The value of `replacement` from the source configuration is `"alertmanager-$1"`, which is correct for the project it is sourced from, but not correct for the helm naming conventions used in the chart. Here, the correct value is `"$1"`

**Comment by paskal** [comment]
I've added replacement rule, see #11617. I don't think maintaining script with such replacements is too much of a burden, in exchange we have reliable mechanism of having these files in up-to-date state.

**Comment by vsliouniaev** [comment]
Every time someone syncs rules from upstream repositories they will need to go through the changes to make sure that potential changes are not having one of these effects and add amend the script if it does That seems like it could get pretty out of hand

**Comment by paskal** [comment]
I understand you, however this particular thing was there for [9+ months](https://github.com/coreos/prometheus-operator/commit/c9f5e12212058cd7d937986427ab0aa861345574#diff-837f865a59e064f0b9c6c5757bd966ce). I think we have to manage these cases somehow anyway, and doing this via script rewrites is not the worst way possible.
