### ISSUE TITLE
[stable/rabbitmq-ha] Support TLS between cluster nodes

### ISSUE THREAD

**Issue by eldada** [helm/charts#11538]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

The official RabbitMQ Docker image seems to support TLS(SSL) (https://github.com/docker-library/rabbitmq).

The `stable/rabbitmq-ha` chart sets up a cluster. The inter-node communication is not encrypted.
On a zero trust cluster, I'd like to be able and
- Create my TLS sercet
- Pass the TLS secret to the RabbitMQ chart at deployment time
- RabbitMQ nodes will setup erlang TLS as described in https://www.rabbitmq.com/clustering-ssl.html

**Version of Helm and Kubernetes**:
Any

**Which chart**:
stable/rabbitmq-ha

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by steven-sheehy** [comment]
The chart is entirely community maintained, so PRs welcome.

**Comment by eldada** [comment]
I tried looking into it, and it feels like a good knowledge of internals of RabbitMQ and Erlang is needed. PRs are indeed welcome 😄
