### ISSUE TITLE
Json as local file or raw json

### ISSUE THREAD

**Issue by joeybdub** [helm/charts#11542]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**: 2.0.1 and 1.13 respectively

**Which chart**: Grafana

**What happened**: Change/Update to version 1.23.0 on the 11th of Jan removed the ability to pass raw json into a values file. Looks for files but doesn't find local file as I believe when I pass the stable/grafana its expanding the copy in local cache directory which doesn't find local json files.

**What you expected to happen**:
Json to be updated in the ./var/lib/grafana/dashboards/*.json from local file or the raw json in the  values.yaml

**How to reproduce it** (as minimally and precisely as possible):

Try use a local json file in the directory you run helm command above or update the values.yaml with raw json as per below.
e.g.
##
dashboardProviders: 
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards
    - name: 'json-configmap'
      orgId: 2 
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/json-configmap/

dashboards: 
  default:
    custom-dashboard:
      json: |
        {
          "annotations": {
              "list": [
                  {
                    "builtIn": 1,
                    "datasource": "-- Grafana --",
                    "enable": true,
                    "hide": true,
                    "iconColor": "rgba(0, 211, 255, 1)",
                    "name": "Annotations & Alerts",
                    "type": "dashboard"
                  }
              ]
            },
          }
  json-configmap:    
    joe1-dashbaord:
      json: dash.json

**Comment by joeybdub** [comment]
any help would be great!

**Comment by maorfr** [comment]
PR on its way :)

**Comment by joeybdub** [comment]
cheers!

**Comment by joeybdub** [comment]
Would it be possible to get something like...

data:
{{ (.Files.Glob "dashboards/*.json").AsConfig | indent 2 }}

or 

data:
{{ (.Files.Get "custom-.json").AsConfig | indent 4 }}

to the stable chart to enable the use of a local file?

**Comment by maorfr** [comment]
This is a bit misleading I suppose.

You can not actually use a local file, unless it is inside the chart directory. Meaning - you must have a local copy of the chart directory to use this feature, and you can not use it along with `helm install stable/grafana`.

Regarding `{{ (.Files.Glob "dashboards/*.json").AsConfig | indent 2 }}` - since all other dashboards are defined one by one, I would prefer to keep it as is. Another reason would be the usage of `$key` as the file name in the configmap.

Both these reasons are only my opinion. Should a PR come along to settle these, I would probably approve it ;)

**Comment by joeybdub** [comment]
Thanks for the quick feedback. 

So the team I work in don't want to use the local copy of the chart directory.  I don't see how we can pass external JSON to the chart without using a URL(This isn't ideal either for management of multiple and new dashboards)

Is there a suggested way to use `helm install stable/grafana` to pass external JSON?

Thanks again!

**Comment by maorfr** [comment]
I think the best way is using url. If this is not possible for you, I would use the `json` option and do something along the lines of:

Have the files in a directory.
Write a short script that iterates over the files and adds their content to a new values file. Lets call it `dashboards-values.yaml`.
This file only contains the dashbords now (need to create it to fit the structure of the `json` dashboard.

Now you can pass that file and do:
`helm install stable/grafana -f dashboards-values.yaml`.

Will that work for you?
Hope this helps.

**Comment by joeybdub** [comment]
Thanks I am using 

helm --debug install --namespace Joe --name grafana --values values.yaml stable/grafana

However the `json` option currently isn't working and hence the issue. Are you suggesting that the json option of passing raw json should work?

Thanks

**Comment by maorfr** [comment]
Yes! It is now working again :)

**Comment by joeybdub** [comment]
Super and thank you!
 However I am getting an issue with using raw json. 
Just to confirm that you have tried the raw json in the dashboards-values.yaml ?

**Comment by joeybdub** [comment]
just ignore the last message I got it! Many thanks for this!

**Comment by maorfr** [comment]
Happy to help ;)
