### ISSUE TITLE
[stable/postgresql] PodLabels and PodAnnotation in Postgresql slaves is broken

### ISSUE THREAD

**Issue by xtof2all** [helm/charts#11558]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  Bug Report

**Version of Helm and Kubernetes**: Openshift 3.11 (Kubernetes 3.11).

**Which chart**: stable/postgresql (3.11.5)

**What happened**: unable install with slaves. 

**What you expected to happen**: Install of postgresql pods with 1 replica

**How to reproduce it** (as minimally and precisely as possible): 
`helm upgrade --install stable/postgresql --set replication.enabled=true`

**Anything else we need to know**:
PodLabes and PodAnnotation in `stable/postgresql/templates/statefulset-slaves.yaml`

**Comment by Jul13nT** [comment]
This pull request fix it #11486

**Comment by xtof2all** [comment]
I confirm that the #11486 is a correct fix.

**Comment by carrodher** [comment]
I just added a comment to #11486, let's wait until this PR is merged to close this issue. Thanks for reporting it!

**Comment by carrodher** [comment]
Above PR (https://github.com/helm/charts/pull/11485) was merged in solving this issue. It was created before and also it was in a more advanced state than #11486.

**Comment by Jul13nT** [comment]
I can confirm that it's now solved, thanks.
