### ISSUE TITLE
[stable/bookstack] Default pod crashing due to segmentation fault

### ISSUE THREAD

**Issue by gfenn-newbury** [helm/charts#11567]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**: Client: 1.10, Sever 1.11

**Which chart**: `stable/bookstack`

**What happened**: Main pod crashes with segmentation fault:
```
ookstack.dev:80 10.122.135.1 - - [20/Feb/2019:10:40:51 +0000] "GET / HTTP/1.1" 302 1309 "-" "kube-probe/1.11+"
bookstack.dev:80 10.122.135.1 - - [20/Feb/2019:10:40:52 +0000] "GET /login HTTP/1.1" 200 2618 "http://10.122.135.211:80/" "kube-probe/1.11+"
bookstack.dev:80 10.122.135.1 - - [20/Feb/2019:10:40:59 +0000] "GET / HTTP/1.1" 302 1301 "-" "kube-probe/1.11+"
bookstack.dev:80 10.122.135.1 - - [20/Feb/2019:10:40:59 +0000] "GET /login HTTP/1.1" 200 2615 "http://10.122.135.211:80/" "kube-probe/1.11+"
[Wed Feb 20 10:41:03.097575 2019] [core:notice] [pid 1] AH00052: child pid 97 exit signal Segmentation fault (11)
[Wed Feb 20 10:41:04.099732 2019] [mpm_prefork:notice] [pid 1] AH00169: caught SIGTERM, shutting down
```
```
NAME                                 READY     STATUS             RESTARTS   AGE
pod/bookstack-dev-6496cc7b68-jds4l   0/1       CrashLoopBackOff   14         50m
pod/bookstack-dev-mariadb-0          1/1       Running            0          50m
```
**What you expected to happen**: Pod continues to serve pages

**How to reproduce it** (as minimally and precisely as possible): Unsure on exact details on how to reproduce. The pod will do this without any interaction

**Anything else we need to know**:
The pod will happily work and serve pages for what seems to be a random amount of time before reaching this segmentation fault. Normally this is a matter of minutes, though it has been a matter of seconds before. I'm unsure of the exact cause, as there is no obvious trigger.

**Comment by sabvente** [comment]
I've experienced the same issue. It's a really annoying thing, because bookstack ran for a day without problems, I've configured it, created books and pages etc. and it seems all my work is lost as there is no solution yet.

Looking forward for a fix.
