### ISSUE TITLE
[stable/redis-ha] NOREPLICAS error when AUTH is set

### ISSUE THREAD

**Issue by pyk** [helm/charts#11565]
**Is this a request for help?**:

no

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```
% helm version
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
% kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", 
BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.5", GitCommit:"9aba9c1237d9d2347bef28652b93b1cba3aca6d8", GitTreeState:"cl
ean", BuildDate:"2018-12-11T02:36:50Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/redis-ha

**What happened**:
If `AUTH` is set, the redis master cannot write due to `NOREPLICA` error.

**What you expected to happen**:
It should be OK.

**How to reproduce it** (as minimally and precisely as possible):

```
helm install \
    --set auth=true \
    --set redisPassword=somepassword \
    stable/redis-ha
```

1. Connect to one of the master via the sentinel
2. Then write a key with a value

You should get the following error:

```
(error) NOREPLICAS Not enough good replicas to write.
```

**Anything else we need to know**:

I have checked the configuration for:

```
requirepass
masterauth
```

and it set correctly.

From the logs:

<img width="1323" alt="screen shot 2019-02-20 at 17 30 30" src="https://user-images.githubusercontent.com/2213646/53085353-3e85b680-3535-11e9-8db4-84a55a81b164.png">

**Comment by devsinghnaini** [comment]
Hi Same issue for me also but is is occurring When i failed or shutdown any one node.

**Comment by ssalaues** [comment]
It sounds like you might have an unhealthy cluster. By default you should really only receive that if the master is unable to replicate to at least 1 slave. Check your slave logs to see if they are replicating from the master.

Also I know some of the more recent changes into the chart add fixes to help keep the pods in quorum. I would suggest trying the latest version of the chart (currently 3.3.3):
```
helm install \
  --version 3.3.3 \
  --set auth=true \
  --set redisPassword=somepassword \
   stable/redis-ha
```
