### ISSUE TITLE
[stable/kube-lego] created objects are not prefixed with release name

### ISSUE THREAD

**Issue by colemickens** [helm/charts#1159]
The `nginx-ingress` chart prefixed everything with the release name, allowing multi-releases in a single cluster.

The `kube-lego` chart does not does this. Is this intentional?

**Comment by colemickens** [comment]
It looks like maybe the deployment does, but not the Service.

**Comment by mgoodness** [comment]
The `kube-lego` application creates the Service itself, and (last I checked) the name is hard-coded. See https://github.com/jetstack/kube-lego/issues/78. Happy to update the chart if/when that's resolved.

**Comment by jsulinski** [comment]
There are environment variables you can use, right?

**Comment by jsulinski** [comment]
Ran into this as well, and tabled pending resolution of https://github.com/jetstack/kube-lego/issues/78
