### ISSUE TITLE
[stable/traefik] Multiple certificates in chart configuration

### ISSUE THREAD

**Issue by glenngbg** [helm/charts#11597]
**Is this a request for help?**

I dont´t think so, if I read the chart correct it´s a feature request.

**FEATURE REQUEST**

I think the chart is missing functionality to support more than one certificate uploaded as base64 string in secret.

There is the ssl.defaultCert and ssl.deafultKey but if you deploy a cluster where you need more than one certificate you have to do that manually afterwards with kubectl.

It´s achivalbe though a secret like this:
```
data:
  tls.crt: <base64data>
  tls.key: <base64data>
  tls2.crt: <base64data>
  tls2.key: <base64data>
```

and a traefik config like this
```
[entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls2.crt"
          KeyFile = "/ssl/tls2.key"
```

It would be nice to be able to configure a list of certs and keys and not only default properties.

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
traefik-1.55.1

**Comment by diogopms** [comment]
Hey, Any update on this feature?
Thanks 🙏
