### ISSUE TITLE
Set "nodeSelector" value to the Backup CronJob

### ISSUE THREAD

**Issue by rafaeloening-barigui** [helm/charts#11623]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm 2.12.3
Kubernetes 1.11.5

**Which chart**:
stable/jenkins

**What happened**:
I can't set the "nodeSelector" value to the backup CronJob. Doesn't exist this value in the values.yaml.

**What you expected to happen**:
I would like to specify the nodes where this CronJob will be executed.

**Comment by maorfr** [comment]
Hey @rafaeloening-barigui,

Would you like to get involved and try to tackle this issue yourself?
