### ISSUE TITLE
[stable/jenkins] CrashLoopBackOff sidecar container

### ISSUE THREAD

**Issue by ricardompcarvalho** [helm/charts#11642]
**Is this a request for help?**:

Yes, when i want to begin work with auto-reload jcasc configuration the sidecar pod gives me an error.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Which chart**: Jenkins

**What happened**: "Back-off 5m0s restarting failed container=jenkins-sc-config pod=jenkins-64476896d7-lggtw_default(62ec1612-3692-11e9-8a1f-42010a840215): CrashLoopBackOff"

**What you expected to happen**: "Running"

**How to reproduce it** (as minimally and precisely as possible): helm install --name jenkins stable/jenkins -f jenkins-values.yaml

**Anything else we need to know**:
Error log: 
`Traceback (most recent call last): File "/app/sidecar.py", line 190, in <module> main() File "/app/sidecar.py", line 185, in main ssh_port) File "/app/sidecar.py", line 100, in watchForChanges resource_version = v1.list_namespaced_config_map(namespace=namespace).metadata.resource_version File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11650, in list_namespaced_config_map (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs) File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11753, in list_namespaced_config_map_with_http_info collection_formats=collection_formats) File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api _return_http_data_only, collection_formats, _preload_content, _request_timeout) File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api _request_timeout=_request_timeout) File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 342, in request headers=headers) File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET query_params=query_params) File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request raise ApiException(http_resp=r) kubernetes.client.rest.ApiException: (403)`

jenkins-values.yaml: 

```
Master:
  Name: jenkins-master
  Image: "jenkins/jenkins"
  ImageTag: "latest"
  ImagePullPolicy: "IfNotPresent"
  Component: "jenkins-master"
  UseSecurity: true
  AdminUser: admin
  OwnSshKey: false
  Cpu: "200m"
  Memory: "1024Mi"
  InstallPlugins:
      - kubernetes:latest
      - kubernetes-credentials:latest
      - workflow-aggregator:latest
      - workflow-job:latest
      - credentials-binding:latest
      - git:latest
  
  CustomConfigMap: false
  Sidecars:
    configAutoReload:
      enabled: true
      image: shadwell/k8s-sidecar:0.0.2
      imagePullPolicy: IfNotPresent
      sshTcpPort: 1044
      label: jenkins_config
      folder: /var/jenkins_home/casc_configs
  JCasC:
    enabled: true
    PluginVersion: 1.5
    SupportPluginVersion: 1.5
    ConfigScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.

Agent:
  Enabled: true
  Image: jenkins/jnlp-slave
  ImageTag: 3.10-1
  CustomJenkinsLabels: []
  Component: "jenkins-slave"
  Privileged: false
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"```

**Comment by maorfr** [comment]
Maybe @holmesb can help?

**Comment by holmesb** [comment]
Hi @ricardompcarvalho 
Difficult to diagnose your yaml structure without tabulation.  But looks like you've got JCasC as a root-level key.  Instead, should be Master.JCasC.  
Pls follow the structure of the [values.yaml](https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml) in this repo.

The below values, with JCasC moved the right place, are working for me:

```Master:
  Name: jenkins-master
  Image: "jenkins/jenkins"
  ImageTag: "latest"
  ImagePullPolicy: "IfNotPresent"
  Component: "jenkins-master"
  UseSecurity: true
  AdminUser: admin
  OwnSshKey: false
  Cpu: "200m"
  Memory: "1024Mi"
  InstallPlugins:
    - kubernetes:latest
    - kubernetes-credentials:latest
    - workflow-aggregator:latest
    - workflow-job:latest
    - credentials-binding:latest
    - git:latest
  JCasC:
    enabled: true
    PluginVersion: 1.5
    SupportPluginVersion: 1.5
    ConfigScripts:
    welcome-message: |
      jenkins:
        systemMessage: Welcome to our CI\CD server. This Jenkins is configured and managed 'as code'.

  CustomConfigMap: false
  Sidecars:
    configAutoReload:
      enabled: true
      image: shadwell/k8s-sidecar:0.0.2
      imagePullPolicy: IfNotPresent
      sshTcpPort: 1044
      label: jenkins_config
      folder: /var/jenkins_home/casc_configs

Agent:
  Enabled: true
  Image: jenkins/jnlp-slave
  ImageTag: 3.10-1
  CustomJenkinsLabels: []
  Component: "jenkins-slave"
  Privileged: false
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
```

**Comment by ricardompcarvalho** [comment]
Hello @holmesb.
I was already using the correct indentation, but I was not able to put the yaml file here as it should be, that is, I was using the same as the Master.JCasC and I copied the code above but it still did not work: s

If I'm working inside a private network does this sidecar work?

**Comment by ricardompcarvalho** [comment]
Hello @holmesb.
I was already using the correct indentation (btw yours seemed to be wrong at the ConfigScripts key), but I was not able to put the yaml file here as it should be, that is, I was using the same as the Master.JCasC and I copied the code above but it still did not work: s

Besides the error above gives me this too :point_down: 
`"HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:serviceaccount:default:default\" cannot list configmaps in the namespace \"default\"","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}`

I'm miss something?

**Comment by holmesb** [comment]
Thanks, I've corrected.  Please do likewise using [triple back-ticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).  If the same values work for me, but not you, I expect you have RBAC enabled and your user lacks privileges.  Can you try in a new namespace\cluster without RBAC?

**Comment by ricardompcarvalho** [comment]
@holmesb gives me this -> `Error: could not find a ready tiller pod`
I have these commands before installing the jenkins pod :point_down: 
```
kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=$(gcloud config get-value account)

kubectl create serviceaccount tiller --namespace kube-system
kubectl create clusterrolebinding tiller-admin-binding --clusterrole=cluster-admin --serviceaccount=kube-system:tiller

helm init --service-account=tiller
helm repo update
```

**Comment by holmesb** [comment]
@ricardompcarvalho `rbac.install = true` should fix your permissions problem.

**Comment by ricardompcarvalho** [comment]
@holmesb The installation of rbac solved my problem but now every time I add new configuration or change an existing one, sidecar gives error but I can see the configuration in jenkins, only the container is always doing restart because of the existing error.
``` Traceback (most recent call last): File "/app/sidecar.py", line 190, in <module> main() File "/app/sidecar.py", line 185, in main ssh_port) File "/app/sidecar.py", line 123, in watchForChanges jenkinsReloadConfig(admin_private_key, admin_user, ssh_port, logger) File "/app/sidecar.py", line 22, in jenkinsReloadConfig ssh_client.connect('127.0.0.1', port=ssh_port, username=admin_user, pkey=private_key) File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 437, in connect passphrase, File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 749, in _auth raise saved_exception File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 649, in _auth self._transport.auth_publickey(username, pkey) File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1507, in auth_publickey return self.auth_handler.wait_for_response(my_event) File "/usr/local/lib/python3.6/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response raise e paramiko.ssh_exception.AuthenticationException: Authentication failed. ```

**Comment by holmesb** [comment]
@ricardompcarvalho Does reinstalling fix?  Ie `helm delete --purge <jenkins release>`  & reinstall.

**Comment by ricardompcarvalho** [comment]
@holmesb does not work that way... every time i do a change in configuration give me error

**Comment by ricardompcarvalho** [comment]
I have to do these steps because of having `rbac.install`?
```{{- if .Values.rbac.install }}
Configure the Kubernetes plugin in Jenkins to use the following Service Account name {{ template "jenkins.fullname" . }} using the following steps:
  Create a Jenkins credential of type Kubernetes service account with service account name {{ template "jenkins.fullname" . }}
  Under configure Jenkins -- Update the credentials config in the cloud section to use the service account credential you created in the step above.
{{- end }}```

**Comment by ricardompcarvalho** [comment]
@holmesb The error on the configmaps was exceeded with the inclusion of `rbac: install` but after that the container goes down with the error that i describe above

**Comment by holmesb** [comment]
> container goes down with the above error...
"does not work that way"

Please be more descriptive.  What exactly happens when you helm delete --purge and reinstall?

**Comment by ricardompcarvalho** [comment]
@holmesb When purge and reinstall the sidecar container continues in crashloopbackoff, but even with it giving error sometimes I can reload new settings in the jenkins

**Comment by holmesb** [comment]
What happens when you purge and then install a different release (call it jenkins-sidecarfix or something) using the [values.yaml](https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml) from this chart with no modifications except `Master.JCasC.enabled: true`, `Master.Sidecars.configAutoReload: true`  and `master.rbac.install: true`?

**Comment by ricardompcarvalho** [comment]
@holmesb using the values.yaml from the chart except those configurations works!

**Comment by ricardompcarvalho** [comment]
@holmesb can you help me, please?
I wanted instead of having a values.yaml with all the scripts corresponding to the CasC configuration, having the CasC configuration inside folders in the repository, how can I get this?
I hope you have a time to help me

**Comment by ricardompcarvalho** [comment]
@holmesb can you help?

**Comment by holmesb** [comment]
CasC config must be in one or more values yaml files.  You may store them in sub-folders in your repo.  Helm documentation explains how to apply different values files.

This question is unrelated to this issue.  Please open new issues for unrelated questions.

**Comment by ricardompcarvalho** [comment]
Yes but with auto-reload the configmaps will be inside configscripts no?

**Comment by holmesb** [comment]
This chart creates configmaps from the keys under master.JCasC.ConfigScripts.  The sidecar takes these configmaps and creates yaml files in a single dir (/var/jenkins_home/casc_configs) on the master pod's filesystem.

**Comment by ricardompcarvalho** [comment]
Yes, i know that, my doubt is how to apply casc configuration that i have in a folder and sub-folders on the repository. I want to have all my jobs inside a folder and apply them, do you know how to do it?

**Comment by torstenwalter** [comment]
I have to agree with @holmesb: How you store configmaps in version control and apply them to kubernetes is really off topic and unrelated to this chart.

You can just call 'kubectl apply -f folder' and that will apply all yaml files within that folder.

You don't have to manage JCasC scripts within this chart. You can store them in any config map you want as long as they have the same annotation the sidecar will pick them up and apply them.

Just ensure that you don't have conflicting configs as that will result in error. That also happens if you install Jenkins multiple times within the same namespace. That's the reason why the label has been changed since the 1.0.0 release of this chart.

**Comment by ricardompcarvalho** [comment]
Thanks for the answer @torstenwalter and sorry for writing here
