### ISSUE TITLE
[stable/airflow] existingAirflowSecret doesn't seem to override the secret in airflow-postgres/redis containers. 

### ISSUE THREAD

**Issue by nathadfield** [helm/charts#11655]
When trying to use `existingAirflowSecret` in order to specify a prexisting secret for the Postgres and Redis passwords, this does seem to work for the `airflow-web` container but in `airflow-postgres` and `aiflow-redis` it is still using the default password.

airflow-web
Image: my-airflow-image
Environment variables:
POSTGRES_USER (airflow-secrets):  
POSTGRES_PASSWORD (airflow-secrets):  
REDIS_PASSWORD (airflow-secrets):  

airflow-postgresql
Image: postgres:9.6.2
Environment variables:
POSTGRES_USER: postgres
PGUSER: postgres
POSTGRES_DB: airflow
POSTGRES_INITDB_ARGS: 
PGDATA: /var/lib/postgresql/data/pgdata
POSTGRES_PASSWORD (airflow-postgresql):  

airflow-redis
Image: docker.io/bitnami/redis:4.0.9
Environment variables:
REDIS_REPLICATION_MODE: master
REDIS_PASSWORD (airflow-redis):

**Comment by gsemet** [comment]
@strobus do you have any idea?

**Comment by nathadfield** [comment]
Any word on this?  I am by no means a Kubernetes expert so I could be doing something wrong but I can't see what it is.

@gsemet Are you able to validate whether this works for you or not?

**Comment by gsemet** [comment]
nop, not used it so far
