### ISSUE TITLE
omnibusConfigRuby not picked up anymore

### ISSUE THREAD

**Issue by msvechla** [helm/charts#1167]
**Which chart**:
https://docs.gitlab.com/ce/install/kubernetes/gitlab_chart.html
```helm install --name gitlab -f values.yaml stable/gitlab-ce```

**What happened**:
omnibusConfigRuby is not applied

**What you expected to happen**:
omnibusConfigRuby is applied

**How to reproduce it** (as minimally and precisely as possible):
set omnibusConfigRuby in values.yaml, then check config map and see that only the default values are applied

**Anything else we need to know**:
I also do not see any reference in the helm chart any more to that variable. Is this functionality removed? According to the documentation it should work: https://docs.gitlab.com/ce/install/kubernetes/gitlab_chart.html#custom-omnibus-gitlab-configuration

Is there another way to set:
```
nginx['listen_port'] = 80;
nginx['listen_https'] = false;
```

Thank you!

**Comment by klaus** [comment]
i can confirm this
