### ISSUE TITLE
I want to know the TLS configuration of prometheus-adapter in valus.yaml format. Can you send me a template?

### ISSUE THREAD

**Issue by huisebug** [helm/charts#11687]
I want to know the TLS configuration of prometheus-adapter in valus.yaml format. Can you send me a template?

**Comment by weijinxy** [comment]
So Do I, +1

**Comment by huisebug** [comment]
@DirectXMan12

**Comment by vsliouniaev** [comment]
Are you looking for anything more than what's available in the chart's values file source?

https://github.com/helm/charts/blob/master/stable/prometheus-adapter/values.yaml#L60

**Comment by huisebug** [comment]
Yes, but I don't know which ca file to put on here, and do I have templates? @vsliouniaev
