### ISSUE TITLE
[stable/prometheus-operator] Readonly grafana user

### ISSUE THREAD

**Issue by r-divakaran-hrs** [helm/charts#11704]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Yes

**Version of Helm and Kubernetes**:
Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Helm version
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

**Which chart**:
prometheus-operator

**What happened**:
I was using the grafana chart earlier and by default it was allowing read only access to Grafana for anyone having the URL. If any changes to be done, obviously need to login then we can give admin or other users if existing.
But with the grafana installation coming as part of prometheus-operator, it asking to login always and by default the admin user is existing.
I would like to avoid giving the admin credentials to all and have a read only user as well.

**What you expected to happen**:
Is it possible to make it like, anyone can access grafana and view graphs without credentials ? If not what is the correct way of creating a read only user ?

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by vsliouniaev** [comment]
I think the only security configuration change to the adminPassword, which is left unset on the default chart. You should be able to get the same behaviour with `grafana.adminPassword=null`

I believe the reasons for setting the password in the operator chart no longer apply, but it's there for backwards-compatibility.

**Comment by kcmartin** [comment]
If you want to keep the admin user, and add a read-only user, you can add the following to the grafana section of values.yaml:

```
  grafana.ini:
    auth.anonymous:
      enabled: true
```

**Comment by r-divakaran** [comment]
Thanks for both replies. I have unset the admin password so that it generates a random one and also added the config to allow anonymous login, which allows now to view grafana without prompting for credentials. (I have my grafana installation behind oauth, so it confirms the proper email domain and gives a read only access.. secure enough I guess 😄 )

**Comment by vsliouniaev** [comment]
@r-divakaran Be aware that every helm upgrade will re-generate a new password but it will only be re-loaded by grafana when the grafana container restarts
