### ISSUE TITLE
[stable/openldap] TLS config options

### ISSUE THREAD

**Issue by rojopolis** [helm/charts#11719]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

Please expose options to mount a Kubernetes secret representing custom TLS certificates.  Currently the only option appears to be forking osixia/docker-openldap , adding the certificates into the  image and setting appropriate environment variables.  If an option to mount a TLS secret into the openLDAP container were present it would feel a lot more flexible and would allow scenarios like using cert-manger, etc.

**Version of Helm and Kubernetes**:

**Which chart**:
stable/openldap

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by askm3** [comment]
merged in #13014
