### ISSUE TITLE
DCO link broken in Pull Request Template

### ISSUE THREAD

**Issue by rmccorm4** [helm/charts#11720]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
N/A

**What happened**:
N/A

**What you expected to happen**:
N/A

**How to reproduce it** (as minimally and precisely as possible):

Make a pull request, click on the DCO link at the bottom of the PR template.

**Anything else we need to know**:

In `.github/PULL_REQUEST_TEMPLATE.md`, the DCO link is broken. I'm not sure if the page is just down, or if it's been moved, etc. Just wanted to bring this up since it will appear in every pull request.

I can make a quick PR to fix this link to something like [https://github.com/integration/dco](https://github.com/integration/dco) instead if this page no longer exists.

**Comment by cpanato** [comment]
@rmccorm4 thanks for your report. this pr fixes the issue https://github.com/helm/charts/pull/11725

**Comment by rmccorm4** [comment]
No problem, thanks for quick fix.
