### ISSUE TITLE
kubelet target is down

### ISSUE THREAD

**Issue by vrathore18** [helm/charts#11738]
**What did you do?**
I change my worker node

**What did you expect to see?**
Everything should be working as previously

**What did you see instead? Under which circumstances?**
I am not getting any data in grafana and even in Prometheus.

While looking for the issue I found my kubelet target is down.

![image](https://user-images.githubusercontent.com/35921967/53404879-93657900-39dc-11e9-9ec4-1fa51deaa415.png)

below is my services running

kube-system kube-dns ClusterIP 172.20.0.10 53/UDP,53/TCP 87d
kube-system kubernetes-dashboard LoadBalancer 172.20.207.81 acac76d69fe2e... 443:32501/TCP 75d
kube-system metrics-server ClusterIP 172.20.82.155 443/TCP 87d
kube-system op-coredns ClusterIP None 9153/TCP 22d
kube-system kube-controller-manager ClusterIP None 10252/TCP 22d
kube-system kube-etcd ClusterIP None 4001/TCP 22d
kube-system prometheus-op-kube-scheduler ClusterIP None 10251/TCP 22d
kube-system prometheus-op-kubelet ClusterIP None 10250/TCP 24d
kube-system tiller-deploy ClusterIP 172.20.255.193 44134/TCP 56d
monitoring alertmanager-operated ClusterIP None 9093/TCP,6783/TCP 22d
monitoring alertmanager-sns-forwarder-svc ClusterIP 172.20.18.219 9087/TCP 11d
monitoring prometheus-msteams ClusterIP 172.20.55.185 2000/TCP 22d
monitoring appd-machine-agent-svc ClusterIP 172.20.127.235 9090/TCP 2h
monitoring prometheus-op-alertmanager ClusterIP 172.20.124.11 9093/TCP 22d
monitoring prometheus-op-operator ClusterIP None 8080/TCP 22d
monitoring prometheus-op-prometheus LoadBalancer 172.20.191.2 a1658930427e4... 9090:30227/TCP 22d
monitoring prometheus-operator-v1-grafana LoadBalancer 172.20.95.20 a164a2a4227e4... 80:32496/TCP 22d
monitoring prometheus-operator-v1-kube-state-metrics ClusterIP 172.20.6.181 8080/TCP 22d
monitoring prometheus-operator-v1-prometheus-node-exporter ClusterIP 172.20.35.50 9100/TCP 22d
monitoring prometheus-operated ClusterIP None 9090/TCP

Cause of the issue might be the port.

monitoring/prometheus-op-kubelet is trying to connect through 10255 but kubelete service is open on 10250. Is that is thereason? I tried to change the service to 10255 but it keep getting change to 10250.

I am going the change by edit the service directly.
kubectl -n kube-system edit service prometheus-op-kubelet

Any suggetiong how I can fixed the issue. And I am on AWS

**Comment by vsliouniaev** [comment]
This doesn't look related to helm or the prometheus-operator chart specifically. Duplicate of https://github.com/coreos/prometheus-operator/issues/2434

**Comment by vsliouniaev** [comment]
Since this issue on the linked ticket appears to be an http vs https configuration. Chart version 5.0.0 onwards has set the default configuration to https

**Comment by omni-lchen** [comment]
I experienced the same issue with stable/prometheus-operator v5.0.2, it looks like the endpoints of kubelet service is not up to date, it still holds the nodes terminated, however the endpoints of prometheus-operator-kubelet service are showing correct, not sure this is kubernets issue, you can run the following commands to verify.

kubectl -n kube-system get ep kubelet -o json | jq .subsets[].addresses[].ip | sort
kubectl -n kube-system get ep prometheus-operator-kubelet -o json | jq .subsets[].addresses[].ip | sort
