### ISSUE TITLE
[stable/minio] service.port is not mapped properly

### ISSUE THREAD

**Issue by alvgarvilla** [helm/charts#11751]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 

BUG REPORT

**Version of Helm and Kubernetes**:

Helm version: v2.12.3
Kubernetes version: v1.11.7

**Which chart**:
[stable/minio]

**What happened**:
As documentation said, service.port is "Kubernetes port where service is exposed", default to 9000.

So as we can see in https://github.com/helm/charts/blob/master/stable/minio/templates/service.yaml#L31, it should be mapped to "port" instead of "targetPort", since targetPort is the one exposed by the pod and in deployment.yaml is hardcoded to 9000 https://github.com/helm/charts/blob/master/stable/minio/templates/deployment.yaml

**What you expected to happen**:
It should be mapped to port instead of targetPort.

**How to reproduce it** (as minimally and precisely as possible):
Install the chart overriding the service.port value.

**Anything else we need to know**:

**Comment by marcadella** [comment]
Even if I set `service.port=9001` the container is still deployed on port 9000. This does not seem to be the expected behavior is it?
