### ISSUE TITLE
[stable/prometheus-operator] needs higher container cpu limits or need customization parameters

### ISSUE THREAD

**Issue by wu105** [helm/charts#11768]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
current

**Which chart**:
stable/prometheus

**What happened**:
Frequent CPUThrottlingHigh alerts on the following pod.containers:
alertmanager-prometheus-prometheus-oper-alertmanager-0.config-reloader  
prometheus-prometheus-prometheus-oper-prometheus-0.prometheus-config-reloader 
prometheus-prometheus-prometheus-oper-prometheus-0.rules-configmap-reloader 
There is no way to raise the current hardwired cpu limits (100m, 50m, and 100m) on them.

**What you expected to happen**:
Need a way to raise the cpu limits on them when need.  for instance, we estimate that we would need to raise the cpu limites to 200m, 150m, and 200m respectively to eliminate the frequent CPUThrottlingHigh alerts on them.  There are other hardwired resource limites generated by the operator that may need similar customization support.

**How to reproduce it** (as minimally and precisely as possible):
This seems a self-evident design issue.

**Anything else we need to know**:
This is similar to #9540 but different.
We observed this CPUThrottingHigh alert while using stable/prometheus 4..0.0 and 4.1.1.
The premetheus-operator itself must also make a change either to raise the hardwired cpu limits, or add support for the cpu limit customization.

**Comment by vsliouniaev** [comment]
@wu105 This change was made possible by operator 0.29.0 and there's an open pull request to get this change merged into the chart right now.
