### ISSUE TITLE
Cassandra fails to deploy with persistence disabled

### ISSUE THREAD

**Issue by touchdown** [helm/charts#1176]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm v2.4.2
K8s v1.6.4

**Which chart**:
incubator/cassandra

**What happened**:
setting persistence.enabled = false doesn't deploy

**What you expected to happen**:
deploy cassandra cluster with emptyDir

**How to reproduce it** (as minimally and precisely as possible):
helm install --namespace "cassandra" -n "cassandra" --set persistence.enabled=false incubator/cassandra
```
Error: error validating "": error validating data: [field spec.template.spec.containers[0].volumeMounts[0].mountPath for v1.VolumeMount is required, found invalid field emptyDir for v1.VolumeMount]
```

**Anything else we need to know**:
I have a fix locally, just want to make sure it is ok to submit a PR for the fix @KongZ

**Comment by KongZ** [comment]
@touchdown Sure, please submit a PR. Thanks a lot :)
