### ISSUE TITLE
Unable to deploy mongodb in production using stable/mongodb

### ISSUE THREAD

**Issue by pragyanatvade** [helm/charts#11763]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

**Which chart**: stable/mongodb

**What happened**: When I am running the command `helm install -f ./values-production.yaml stable/mongodb` it shows following error:
```
Error: render error in "mongodb/templates/statefulset-secondary-rs.yaml": template: mongodb/templates/statefulset-secondary-rs.yaml:184:54: executing "mongodb/templates/statefulset-secondary-rs.yaml" at <.Values.metrics.live...>: can't evaluate field initialDelaySeconds in type interface {}
```

**What you expected to happen**: I expected it to launch mongodb replicase in kubernetes cluster with 1 primary, 1 secondary, and 1 arbiter

**How to reproduce it** (as minimally and precisely as possible): 
Run `helm install -f ./values-production.yaml stable/mongodb` in recent version of helm

**Anything else we need to know**:

**Comment by juan131** [comment]
Thanks for reporting the issue @pntripathi9417 

It was an issue with the readiness/liveness probes configuration. I just created a PR to fix it.
