### ISSUE TITLE
[stable/fluent-bit] Capabilities.APIVersions condition checks 

### ISSUE THREAD

**Issue by bnookala** [helm/charts#11761]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**: Helm 2.12.3, Kubernetes 1.9.11

**Which chart**: stable/fluent-bit

**What happened**: `helm template` does not produce the correct rbac api version due to an empty `Capabilities.APIVersions` map used. This is a known issue: https://github.com/helm/helm/issues/3377, but can be resolved for this chart by changing the conditions used in `_helpers.tpl`. Example resolution here: https://github.com/helm/charts/pull/11031/files

**What you expected to happen**: The chart should default to the v1 rbac api and check for v1alpha1 and v1beta1 specifically

**How to reproduce it** (as minimally and precisely as possible): 

1. Clone the charts repository
2. Change active directory to stable/fluent-bit
3. Run `helm template . > test.yaml`
4. Observe the rbac apiVersion is always `rbac.authorization.k8s.io/v1alpha1`, even if the cluster only has `v1beta1` or `v1`.

**Comment by bnookala** [comment]
I can take this on, as it's relatively trivial.

**Comment by basvandenbrink** [comment]
I am also facing this issue and the corresponding pull request isn't closed. Can this issue be reopened?
