### ISSUE TITLE
[stable/jenkins] Allow ingress without specifying host

### ISSUE THREAD

**Issue by admoriarty** [helm/charts#11770]
I'm not sure if this is a feature request or a misunderstanding (can reword as a proper template feature request once I clear that up), but considering you can create an ingress in Kube without specifying a host, why does the chart force the setting of Master.HostName before even generating an ingress yaml ? I don't want a host entry in my ingress and removing it afterwards is obviously less than ideal. Am I missing a trick or would this be a nice enhancement?

**Comment by maorfr** [comment]
I would say that this would be a nice enhancement!

**Comment by timothyclarke** [comment]
Have you tried not setting `Master.HostName` or setting it to `false` ?  After all `jenkins-master-ingress.yaml` starts `if .Values.Master.HostName` so if it's blank / empty / false the ingress is simply not created.

Perhaps I'm missing something, but what's the point of jenkins without a web interface? I appreciate that you can send output elsewhere eg slack plugin, but the request implies that you would never use the web interface?

**Comment by admoriarty** [comment]
To be clear, I do want an ingress, I just do not want an ingress with a "host" property set, as is perfectly valid in Kube ingress syntax (and works for our setup when we manually remove it after-the-fact), but just doesn't seem possible with this chart as currently configured (because of what you described well :) )

**Comment by admoriarty** [comment]
So what I'm wondering is could we introduce a new boolean flag to create an ingress or not and move the 'if' statement from https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-ingress.yaml#L1 to just wrap https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-ingress.yaml#L16 (in fact you'd need to do a bit more, the leading hyphen needs to drop down to the http line then but you get my point)

**Comment by maorfr** [comment]
I suggest to start a PR, and we can discuss implementation details there ;)

**Comment by admoriarty** [comment]
Sure, I'm up for that, just wanted to be sure it was a sensible proposal in the first place... will get to it soon.

**Comment by admoriarty** [comment]
I cannot find a way to flush that DCO check failure...initially it was because my email address was private, but I've updated my profile and pushed a trivial change to force a recheck and its still blocked. If anyone knows a way around that, please suggest.

**Comment by admoriarty** [comment]
Thanks for reviewing @maorfr :+1:
