### ISSUE TITLE
[stable/Redis] Cannot create multiple masters nodes

### ISSUE THREAD

**Issue by khaleddu86** [helm/charts#11817]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
Helm: 2.11.0
Kubernates: 1.12.5
**Which chart**:
redis/stable

**What happened**:
Cannot create more that one redis master using the helm chart.

**What you expected to happen**:
Add an option to create more than one redis master

**How to reproduce it** (as minimally and precisely as possible):
-

**Anything else we need to know**:
-

**Comment by juan131** [comment]
Hi @ekhaduk 

This Redis chart configures the Redis cluster using a Master-Slave topology (it doesn't use Redis Cluster or Redis Sentinel to configure HA). Therefore, you don't need more than 1 master replica.

**Comment by ilterpehlivan** [comment]
Hi According to the documentation "https://redis.io/topics/cluster-tutorial" multiple masters are recommended and actually following quoted from this documentation:

> Note that the minimal cluster that works as expected requires to contain at least three master nodes. For your first tests it is strongly suggested to start a six nodes cluster with three masters and three slaves.

Moreover, during our tests by using stable/helm chart we figured out that 1 master memory is becoming full for high load and increasing Slaves have no help. 
That is why, I think master numbers should be configurable in the chart

Thanks

**Comment by juan131** [comment]
Hi @ilterpehlivan 

This Helm chart does not setup a Redis Cluster. It just creates a set of slaves for a single master node. 

Please note I'm not saying that Redis Cluster is not recommended, I'm just stating that this Helm chart is not designed for that kind of configuration.

You might be looking for a configuration such as the one available on this other chart: https://github.com/helm/charts/tree/master/stable/redis-ha

**Comment by ilterpehlivan** [comment]
Hi @juan131 ,

Thanks for the reply. 
I am well aware of redis-ha chart repo but it is giving the sentinel deployment option instead of redis-cluster. I want to use redis-cluster and not to have additional applications (sentinel) running on each node.
I though this repo is providing redis-cluster option with multiple master/slaves but apparently I was wrong.

So we need to build our charts :)

Anyway thanks again

**Comment by juan131** [comment]
You're welcome @ilterpehlivan !!

I'll share your feedback with the team and we'll study whether it's convenient to support Redis Cluster on this Helm chart. Thanks for your interest!

**Comment by cs94njw** [comment]
Can someone point to a true Redis-cluster helm chart?  Or is it not possible?
I need to create a multi-master high availability cluster for Redis, and I don't know if it's just not possible, or no-one has created a helm chart for it yet.
