### ISSUE TITLE
[stable/prometheus-operator] Cannot add extraArgs to Prometheus

### ISSUE THREAD

**Issue by trobert2** [helm/charts#11836]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request (mainly)
Can be considered bug because Prometheus is failing because of the lack of memory

**Version of Helm and Kubernetes**:
k8s: v1.13.3
helm: v2.12.3

**Which chart**:
`stable/prometheus-operator`

**What happened**:
When trying to use the `stable/prometheus-operator` chart, I couldn't find a way to pass in extra definitions. `query.max-samples` cannot be set and Prometheus runs out of memory.

Based on the documentation:
> Prometheus is configured via command-line flags and a configuration file. While the command-line flags configure immutable system parameters (such as storage locations, amount of data to keep on disk and in memory, etc.), the configuration file defines everything related to scraping jobs and their instances, as well as which rule files to load.

I think configuring the `query.max-samples` can only be done with flags at start up.

**What you expected to happen**:
Be able to configure the `query.max-samples` flag at start up.

**Comment by vsliouniaev** [comment]
@trobert2 While the prometheus-operator has a way to pass some parameters, not everything is actually supported by the prometheus CRD. The relevant section is here: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#queryspec

The helm chart doesn't support what's available either, but if you're looking for one of the other parameters, that could be done by fixing the chart itself.

**Comment by trobert2** [comment]
@vsliouniaev thank you for answering.
is there any plan to do this change?
