### ISSUE TITLE
[stable/prometheus-operator] kube-prometheus-exporter-kube-state crashing

### ISSUE THREAD

**Issue by antonyaugustus** [helm/charts#11846]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
lient: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

	Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
	Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
kube-prometheus         1               Tue Oct  2 20:08:01 2018        DEPLOYED        kube-prometheus-0.0.105                         monitoring

**What happened**:
Pod kube-prometheus-exporter-kube-state keeps crashing

**What you expected to happen**:
All resources up and running

**How to reproduce it** (as minimally and precisely as possible):
helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring 

**Anything else we need to know**:
Name:               kube-prometheus-exporter-kube-state-689f8f9bd6-nnfkj
Namespace:          monitoring
Priority:           0
PriorityClassName:  <none>
Node:               xxx/xxxx
Start Time:         Wed, 27 Feb 2019 21:02:53 +0000
Labels:             app=kube-prometheus-exporter-kube-state
                    component=kube-state
                    pod-template-hash=2459495682
                    release=kube-prometheus
                    version=v1.2.0
Annotations:        <none>
Status:             Running
IP:                 xxx.xxx.xxx.xxx
Controlled By:      ReplicaSet/kube-prometheus-exporter-kube-state-689f8f9bd6
Containers:
  exporter-kube-state:
    Container ID:   docker://6fb71030cbb9900a4d27206ff0d49e2554856ed227b61768667eafce9e6ff807
    Image:          gcr.io/google_containers/kube-state-metrics:v1.2.0
    Image ID:       docker-pullable://gcr.io/google_containers/kube-state-metrics@sha256:953a3b6bf0046333c656fcfa2fc3a08f4055dc3fbd5b1dcdcdf865a2534db526
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 27 Feb 2019 22:25:42 +0000
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 27 Feb 2019 22:19:40 +0000
      Finished:     Wed, 27 Feb 2019 22:20:32 +0000
    Ready:          False
    Restart Count:  18
    Limits:
      cpu:     110m
      memory:  150Mi
    Requests:
      cpu:        110m
      memory:     150Mi
    Liveness:     http-get http://:8080/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Readiness:    http-get http://:8080/ delay=30s timeout=5s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-prometheus-exporter-kube-state-token-mpvzd (ro)
  exporter-kube-state-addon-resizer:
    Container ID:  docker://ec579bd2ff879c0a33e98337e45d2928950a9131131efc5b8f6371a58171be6a
    Image:         gcr.io/google_containers/addon-resizer:1.7
    Image ID:      docker-pullable://gcr.io/google_containers/addon-resizer@sha256:dcec9a5c2e20b8df19f3e9eeb87d9054a9e94e71479b935d5cfdbede9ce15895
    Port:          <none>
    Host Port:     <none>
    Command:
      /pod_nanny
      --container=exporter-kube-state
      --cpu=100m
      --extra-cpu=1m
      --memory=130Mi
      --extra-memory=2Mi
      --threshold=5
      --deployment=kube-prometheus-exporter-kube-state
    State:          Running
      Started:      Wed, 27 Feb 2019 21:03:00 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  30Mi
    Requests:
      cpu:     100m
      memory:  30Mi
    Environment:
      MY_POD_NAME:       kube-prometheus-exporter-kube-state-689f8f9bd6-nnfkj (v1:metadata.name)
      MY_POD_NAMESPACE:  monitoring (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-prometheus-exporter-kube-state-token-mpvzd (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-prometheus-exporter-kube-state-token-mpvzd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-prometheus-exporter-kube-state-token-mpvzd
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                   From                                     Message
  ----     ------   ----                  ----                                     -------
  Warning  BackOff  3m5s (x306 over 81m)  kubelet, xxx.xxx.xxx.xxx  Back-off restarting failed container

**Comment by vsliouniaev** [comment]
Could you post the logs from the crashing container please?

**Comment by antonyaugustus** [comment]
Unfortunately I could not edit the title. Here are the logs when I described the pod.

Warning  Unhealthy  32m                     kubelet, xxx  Readiness probe failed: Get http://xxx.xxx.xxx.xxx:8080/: read tcp xxx.xxx.xxx.xxx:42222->xxx.xxx.xxx.xxx:8080: read: connection reset by peer
  Warning  BackOff    8m51s (x5519 over 23h)  kubelet, xxx  Back-off restarting failed container
  Normal   Pulled     3m45s (x234 over 23h)   kubelet, xxx  Container image "gcr.io/google_containers/kube-state-metrics:v1.2.0" already present on machine

Here are the exporter-kube-state-addon-resizer logs

kubectl logs --tail=1000 kube-prometheus-exporter-kube-state-689f8f9bd6-nnfkj exporter-kube-state-addon-resizer  -n monitoring
I0227 21:03:00.862878       1 pod_nanny.go:56] Invoked by [/pod_nanny --container=exporter-kube-state --cpu=100m --extra-cpu=1m --memory=130Mi --extra-memory=2Mi --threshold=5 --deployment=kube-prometheus-exporter-kube-state]
I0227 21:03:00.863028       1 pod_nanny.go:68] Watching namespace: monitoring, pod: kube-prometheus-exporter-kube-state-689f8f9bd6-nnfkj, container: exporter-kube-state.
I0227 21:03:00.863116       1 pod_nanny.go:69] cpu: 100m, extra_cpu: 1m, memory: 130Mi, extra_memory: 2Mi, storage: MISSING, extra_storage: 0Gi
I0227 21:03:00.863983       1 pod_nanny.go:110] Resources: [{Base:{i:{value:100 scale:-3} d:{Dec:<nil>} s:100m Format:DecimalSI} ExtraPerNode:{i:{value:1 scale:-3} d:{Dec:<nil>} s:1m Format:DecimalSI} Name:cpu} {Base:{i:{value:136314880 scale:0} d:{Dec:<nil>} s:130Mi Format:BinarySI} ExtraPerNode:{i:{value:2097152 scale:0} d:{Dec:<nil>} s:2Mi Format:BinarySI} Name:memory}]

and exporter logs

kubectl logs --tail=10 kube-prometheus-exporter-kube-state-689f8f9bd6-nnfkj exporter-kube-state -n monitoring
I0228 20:19:57.105249       1 statefulset.go:147] collected 1 statefulsets
I0228 20:19:57.161112       1 namespace.go:113] collected 197 namespaces
I0228 20:19:57.257122       1 job.go:165] collected 0 jobs
I0228 20:19:57.257585       1 cronjob.go:141] collected 0 cronjobs
I0228 20:19:57.263530       1 daemonset.go:136] collected 4 daemonsets
I0228 20:19:57.357414       1 node.go:186] collected 13 nodes
I0228 20:19:57.560849       1 resourcequota.go:99] collected 210 resourcequotas
I0228 20:19:59.364490       1 replicaset.go:124] collected 1222 replicasets
I0228 20:19:59.764573       1 service.go:112] collected 1566 services
I0228 20:20:00.057714       1 endpoint.go:120] collected 1568 endpoints

**Comment by vsliouniaev** [comment]
I think you may have removed the relevant section of the logs by tailing only the last 10 lines. Only need the crashlooping container logs

**Comment by antonyaugustus** [comment]
I don't this there are any error logs on the pods itself. But below is the message that shows the state.

Warning Unhealthy 32m kubelet, xxx Readiness probe failed: Get http://xxx.xxx.xxx.xxx:8080/: read tcp xxx.xxx.xxx.xxx:42222->xxx.xxx.xxx.xxx:8080: read: connection reset by peer
Warning BackOff 8m51s (x5519 over 23h) kubelet, xxx Back-off restarting failed container
Normal Pulled 3m45s (x234 over 23h) kubelet, xxx Container image "gcr.io/google_containers/kube-state-metrics:v1.2.0" already present on machine

**Comment by antonyaugustus** [comment]
Tried redeploying the helm charts after removing the existing one. Still running into the same issue.

helm init --upgrade
helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring
helm install coreos/kube-prometheus --name prometheus --namespace monitoring

helm ls --all --namespace monitoring
NAME                    REVISION        UPDATED                         STATUS          CHART                           APP VERSION     NAMESPACE
prometheus              1               Thu Feb 28 23:33:24 2019        DEPLOYED        kube-prometheus-0.0.105                         monitoring
prometheus-operator     1               Thu Feb 28 23:32:48 2019        DEPLOYED        prometheus-operator-0.0.29      0.20.0          monitoring

kubectl get pods -n monitoring
NAME                                              READY   STATUS             RESTARTS   AGE
alertmanager-prometheus-0                         2/2     Running            0          4m38s
prometheus-exporter-kube-state-6f9b5c8dcd-tvzkg   1/2     CrashLoopBackOff   3          4m30s
prometheus-exporter-node-8d5b4                    1/1     Running            0          4m39s
prometheus-exporter-node-dgcks                    1/1     Running            0          4m38s
prometheus-exporter-node-f2c26                    1/1     Running            0          4m38s
prometheus-exporter-node-gj4zv                    1/1     Running            0          4m38s
prometheus-exporter-node-jdqrj                    1/1     Running            0          4m39s
prometheus-exporter-node-lfk5x                    1/1     Running            0          4m38s
prometheus-exporter-node-mbmqk                    1/1     Running            0          4m39s
prometheus-exporter-node-mxwlv                    1/1     Running            0          4m38s
prometheus-exporter-node-n6brn                    1/1     Running            0          4m38s
prometheus-exporter-node-s6kzx                    1/1     Running            0          4m38s
prometheus-exporter-node-v6w4j                    1/1     Running            0          4m38
prometheus-exporter-node-vdjwn                    1/1     Running            0          4m38
prometheus-exporter-node-x4ljv                    1/1     Running            0          4m38
prometheus-grafana-5c8c8bfbd6-t9rn6               2/2     Running            0          4m38
prometheus-operator-87779759-k2wm2                1/1     Running            0          5m16
prometheus-prometheus-0                           3/3     Running            1          4m38

**Comment by vsliouniaev** [comment]
Apologies for not catching this sooner, you're installing the `coreos/prometheus-operator` chart, which isn't found in this repository at all and was part of the coreos project until it was replaced with the one here.

The new chart is simply `stable/prometheus-operator` and it is a single chart, rather than being composed of multiple separate pieces.

**Comment by antonyaugustus** [comment]
I am running into permissions issue. Please can you assist?

helm install stable/prometheus-operator --name prometheus-operator  --namespace monitoring
Error: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" is forbidden: User "system:serviceaccount:kube-system:monitoring" cannot delete resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope

**Comment by antonyaugustus** [comment]
I tried removing the crds manually but still the issues exists. Error: object is being deleted: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists

helm install stable/prometheus-operator  --name prometheus-operator --namespace monitoring

**Comment by antonyaugustus** [comment]
Here is the full logs from the rs

[tiller] 2019/03/06 20:24:41 preparing install for prometheus-operator
[storage] 2019/03/06 20:24:41 getting release history for "prometheus-operator"
[tiller] 2019/03/06 20:24:41 rendering prometheus-operator chart using values
2019/03/06 20:24:41 info: manifest "prometheus-operator/charts/prometheus-node-exporter/templates/endpoints.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/prometheus/additionalAlertmanagerConfigs.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/exporters/kube-dns/servicemonitor.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/alertmanager/podDisruptionBudget.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/grafana/configmap-dashboards.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/exporters/kube-controller-manager/endpoints.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/prometheus/additionalScrapeConfigs.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/charts/grafana/templates/dashboards-json-configmap.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/exporters/kube-dns/service.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/prometheus/ingress.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/exporters/kube-etcd/endpoints.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/prometheus-operator/cleanup-crds.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/alertmanager/ingress.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/charts/grafana/templates/pvc.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/prometheus/podDisruptionBudget.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/exporters/kube-scheduler/endpoints.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/prometheus/servicemonitors.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/charts/grafana/templates/ingress.yaml" is empty. Skipping.
2019/03/06 20:24:41 info: manifest "prometheus-operator/templates/prometheus/additionalAlertRelabelConfigs.yaml" is empty. Skipping.
[tiller] 2019/03/06 20:24:41 performing install for prometheus-operator
[tiller] 2019/03/06 20:24:41 executing 4 crd-install hooks for prometheus-operator
[tiller] 2019/03/06 20:24:41 deleting crd-install hook alertmanagers.monitoring.coreos.com for release prometheus-operator due to "before-hook-creation" policy
[kube] 2019/03/06 20:24:42 Starting delete for "alertmanagers.monitoring.coreos.com" CustomResourceDefinition
[kube] 2019/03/06 20:24:42 customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" not found
[kube] 2019/03/06 20:24:42 building resources from manifest
[kube] 2019/03/06 20:24:42 creating 1 resource(s)
[tiller] 2019/03/06 20:24:42 deleting crd-install hook prometheuses.monitoring.coreos.com for release prometheus-operator due to "before-hook-creation" policy
[kube] 2019/03/06 20:24:42 Starting delete for "prometheuses.monitoring.coreos.com" CustomResourceDefinition
[kube] 2019/03/06 20:24:42 customresourcedefinitions.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" not found
[kube] 2019/03/06 20:24:42 building resources from manifest
[kube] 2019/03/06 20:24:42 creating 1 resource(s)
[tiller] 2019/03/06 20:24:42 deleting crd-install hook prometheusrules.monitoring.coreos.com for release prometheus-operator due to "before-hook-creation" policy
[kube] 2019/03/06 20:24:42 Starting delete for "prometheusrules.monitoring.coreos.com" CustomResourceDefinition
[kube] 2019/03/06 20:24:42 customresourcedefinitions.apiextensions.k8s.io "prometheusrules.monitoring.coreos.com" not found
[kube] 2019/03/06 20:24:42 building resources from manifest
[kube] 2019/03/06 20:24:42 creating 1 resource(s)
[tiller] 2019/03/06 20:24:42 deleting crd-install hook servicemonitors.monitoring.coreos.com for release prometheus-operator due to "before-hook-creation" policy
[kube] 2019/03/06 20:24:42 Starting delete for "servicemonitors.monitoring.coreos.com" CustomResourceDefinition
[kube] 2019/03/06 20:24:42 customresourcedefinitions.apiextensions.k8s.io "servicemonitors.monitoring.coreos.com" not found
[kube] 2019/03/06 20:24:42 building resources from manifest
[kube] 2019/03/06 20:24:42 creating 1 resource(s)
[tiller] 2019/03/06 20:24:42 hooks complete for crd-install prometheus-operator
[tiller] 2019/03/06 20:24:42 executing 4 pre-install hooks for prometheus-operator
[tiller] 2019/03/06 20:24:42 hooks complete for pre-install prometheus-operator
[storage] 2019/03/06 20:24:42 getting release history for "prometheus-operator"
[storage] 2019/03/06 20:24:42 creating release "prometheus-operator.v1"
[kube] 2019/03/06 20:24:43 building resources from manifest
[kube] 2019/03/06 20:24:43 creating 102 resource(s)
[tiller] 2019/03/06 20:24:43 warning: Release "prometheus-operator" failed: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists
[storage] 2019/03/06 20:24:43 updating release "prometheus-operator.v1"
[tiller] 2019/03/06 20:24:44 failed install perform step: release prometheus-operator failed: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists

**Comment by antonyaugustus** [comment]
Finally was able to deploy prometheus-operator after following the steps to uninstall noted below

https://github.com/helm/charts/tree/master/stable/prometheus-operator#uninstalling-the-chart

**Comment by antonyaugustus** [comment]
Need help updating the kubelet port to use https vs http. I used the stable/prometheus-operator as mentioned above but the chart by default thought uses https

monitoring/prometheus-operator-kubelet/0 (0/18 up)

**Comment by antonyaugustus** [comment]
Any help? Getting http://xxxx:10255/metrics: dial tcp xxxx:10255: connect: connection refused

helm install stable/prometheus-operator  --name prometheus-operator --namespace monitoring  --tiller-namespace monitoring

**Comment by antonyaugustus** [comment]
Got it to work.

I had to update servicemonitor (prometheus-operator-kubelet) to use port: https-metrics. Any reason it did not pick up this port when the install was done?

spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 30s
    port: https-metrics
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 30s
    path: /metrics/cadvisor
    port: https-metrics
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kubelet

**Comment by antonyaugustus** [comment]
I am closing issue/question
