### ISSUE TITLE
[stable/cockroach] Init container conflict when upgrading

### ISSUE THREAD

**Issue by mcmathja** [helm/charts#11849]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
helm: 2.10
kubernetes: 1.11.1

**Which chart**:
stable/cockroachdb

**What happened**:
I have an existing release (chart version: v2.0.10 / app version: 2.1.4) with a cluster that has already been initialized.

When I attempt to upgrade the release to a newer crdb image version, it causes helm to spin up a new cluster-init job, resulting in a conflict with the previously completed resource:

```
$ helm upgrade crdb stable/cockroachdb --version 2.0.11
Error: UPGRADE FAILED: Job.batch "crdb-cockroachdb-init" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"controller-uid":"9617ae95-3bbb-11e9-9edc-025000000001", "job-name":"crdb-cockroachdb-init"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"cluster-init", Image:"cockroachdb/cockroach:v2.1.5", Command:[]string{"/bin/bash", "-ecx", "until /cockroach/cockroach init --insecure --host=crdb-cockroachdb-0.crdb-cockroachdb --port 26257; do sleep 5; done"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"Always", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc00764b090), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc01240a8c0), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), EnableServiceLinks:(*bool)(nil)}}: field is immutable
```

The database pods _do_ upgrade successfully to the newer version, but the release is left in a bad state, causing all subsequent upgrades to report the same ugly error even though they may succeed:

```
$ helm upgrade crdb stable/cockroachdb --set CacheSize=30%
... same error despite success ...
```

If the pre-existing job is removed manually prior to helm upgrade, the init container starts but gets caught in a failure loop, because the init container has `restartPolicy: OnFailure` and the `cockroach init` command returns an error if the cluster has already been initialized:

```
$ kubectl delete job crdb-cockroachdb-init
$ helm upgrade crdb stable/cockroachdb --version 2.0.11
$ kubectl logs crdb-cockroachdb-init-wtchn
+ /cockroach/cockroach init --insecure --host=crdb-cockroachdb-0.crdb-cockroachdb --port 26257
E190301 01:00:41.131605 1 cli/error.go:230  rpc error: code = AlreadyExists desc = cluster has already been initialized with ID 2d4097cd-9b71-47cf-b8e8-2a2325352cc7
Error: rpc error: code = AlreadyExists desc = cluster has already been initialized with ID 2d4097cd-9b71-47cf-b8e8-2a2325352cc7
Failed running "init"
+ sleep 5
+ /cockroach/cockroach init --insecure --host=crdb-cockroachdb-0.crdb-cockroachdb --port 26257
E190301 01:00:46.235969 1 cli/error.go:230  rpc error: code = AlreadyExists desc = cluster has already been initialized with ID 2d4097cd-9b71-47cf-b8e8-2a2325352cc7
Error: rpc error: code = AlreadyExists desc = cluster has already been initialized with ID 2d4097cd-9b71-47cf-b8e8-2a2325352cc7
Failed running "init"
+ sleep 5
... and so on forever ...
```

**What you expected to happen**:
Either the init container should not be launched after a version upgrade, or the job should complete successfully if it doesn't need to initialize a new cluster.

**How to reproduce it** (as minimally and precisely as possible):
```
# Initialize a basic cluster
helm install stable/cockroachdb --version 2.0.10 --name crdb

# Failure upgrading to chart specifying updated app image version.
helm upgrade crdb stable/cockroachdb --version 2.0.11

# Failure upgrading when setting app image version directly.
helm upgrade crdb stable/cockroachdb --set ImageTag=v2.1.5
```

**Anything else we need to know**:
I think this could be easily addressed by just adding a `"helm.sh/hook": post-install` annotation to the [cluster-init job spec](https://github.com/helm/charts/blob/master/stable/cockroachdb/templates/cluster-init.yaml)?

**Comment by stevenimle-honeywell** [comment]
We have also noticed this issue. That may work for upgrades but if you were to ever redeploy the helm chart without deleting the PVCs (yes, this is not a normal case, but does need to happen sometimes) then you run into this same issue.

**Comment by cgaolei** [comment]
I run into similar issue:
`* helm_release.cockroachdb: rpc error: code = Unknown desc = Job.batch "unimarket-db-cockroachdb-init" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"controller-uid":"40d9c469-3b41-11e9-93ae-4201c0a86f04", "job-name":"unimarket-db-cockroachdb-init"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:"client-certs", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(0xc43489b4c0), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(nil), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil)}}}, InitContainers:[]core.Container{core.Container{Name:"init-certs", Image:"cockroachdb/cockroach-k8s-request-cert:0.4", Command:[]string{"/bin/ash", "-ecx", "/request-cert -namespace=${POD_NAMESPACE} -certs-dir=/cockroach-certs -type=client -user=root -symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar{core.EnvVar{Name:"POD_NAMESPACE", Value:"", ValueFrom:(*core.EnvVarSource)(0xc43489b5a0)}}, Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:"client-certs", ReadOnly:false, MountPath:"/cockroach-certs", SubPath:"", MountPropagation:(*core.MountPropagationMode)(nil)}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"Always", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, Containers:[]core.Container{core.Container{Name:"cluster-init", Image:"cockroachdb/cockroach:v2.1.6", Command:[]string{"/bin/bash", "-ecx", "until /cockroach/cockroach init --certs-dir=/cockroach-certs --host=unimarket-db-cockroachdb-0.unimarket-db-cockroachdb --port 26257; do sleep 5; done"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:"client-certs", ReadOnly:false, MountPath:"/cockroach-certs", SubPath:"", MountPropagation:(*core.MountPropagationMode)(nil)}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"Always", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc427db0c40), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"unimarket-db-cockroachdb", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc424dd59d0), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil)}}: field is immutable`

This happened when I trying to upgrade the ImageTag..using `helm upgrade`
