### ISSUE TITLE
[stable/prometheus] Error from server (BadRequest): a container name must be specified for pod <container name>, choose one of: [prometheus-server-configmap-reload prometheus-server] or one of the init containers: [init-chown-data]

### ISSUE THREAD

**Issue by xlebenny** [helm/charts#11869]
**Is this a request for help?**:
help
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
```` 
λ helm version
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

λ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.2", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-04T16:19:46Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
````

**Which chart**:
stable/prometheus

**What happened**:
````
kubectl logs test-prometheus-server-6bdbfd556f-6tqqc
Error from server (BadRequest): a container name must be specified for pod test-prometheus-server-6bdbfd556f-6tqqc, choose one of: [prometheus-server-configmap-reload prometheus-server] or one of the init containers: [init-chown-data]
````

**What you expected to happen**:
Shouldn't have this message
or update read.me not just simply `helm install --name test stable/prometheus`

**How to reproduce it** (as minimally and precisely as possible):
`helm install --name aaa stable/prometheus`
`kubectl logs test-prometheus-server-6bdbfd556f-6tqqc`

**Anything else we need to know**:

**Comment by eklee** [comment]
This just means the pod has 2 containers, and you need to specify the container to see the logs, change your kubectl to:

kubectl logs test-prometheus-server-6bdbfd556f-6tqqc -c prometheus-server, this should show you the start up error of the prometheus-server container.

**Comment by xlebenny** [comment]
@eklee oh, sorry my stupid mistake, thanks for help
