### ISSUE TITLE
Unable to access Kafka cluster through LoadBalancer on GKE

### ISSUE THREAD

**Issue by valiksb** [helm/charts#11867]
**Is this a request for help?**:

YES

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:
helm version
`Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}`

Using GKE

**Which chart**:
helm install --name wfp-q --namespace wfp --set external.enabled=true --set external.type=LoadBalancer --set rbac.enabled=true incubator/kafka --version 0.13.1

**What happened**:
kafkacat -b 35.202.105.125:31090 -L

when I try to access one of the 3 brokers I get this error "% ERROR: Failed to acquire metadata: Local: Broker transport failure"

**What you expected to happen**:
I would get an overview of the brokers and topics available in the cluster

**How to reproduce it** (as minimally and precisely as possible):
1. helm install --name wfp-q --namespace wfp --set external.enabled=true --set external.type=LoadBalancer --set rbac.enabled=true incubator/kafka --version 0.13.1
2. kubectl get pods
`wfp-q3-kafka-0                           1/1     Running     1          2d`
`wfp-q3-kafka-1                           1/1     Running     0          2d`
`wfp-q3-kafka-2                           1/1     Running     0          2d`
`wfp-q3-zookeeper-0                       1/1     Running     0          2d`
`wfp-q3-zookeeper-1                       1/1     Running     0          2d`
`wfp-q3-zookeeper-2                       1/1     Running     0          2d`
3. kubectl get svc
`wfp-q3-0-external           LoadBalancer   10.19.252.214   35.202.105.125   31090:30924/TCP              2d`
`wfp-q3-1-external           LoadBalancer   10.19.255.238   35.202.77.4      31091:31395/TCP              2d`
`wfp-q3-2-external           LoadBalancer   10.19.254.46    35.202.87.34     31092:31807/TCP              2d`
`wfp-q3-kafka                ClusterIP      10.19.248.255   <none>           9092/TCP                     2d`
`wfp-q3-kafka-headless       ClusterIP      None            <none>           9092/TCP                     2d`
`wfp-q3-zookeeper            ClusterIP      10.19.247.148   <none>           2181/TCP                     2d`
`wfp-q3-zookeeper-headless   ClusterIP      None            <none>           2181/TCP,3888/TCP,2888/TCP   2d`
4. This is how the Kafka broker gets instantiated within a pod
`sh -exc unset KAFKA_PORT && \ export KAFKA_BROKER_ID=${HOSTNAME##*-} && \ export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092 && \ exec /etc/confluent/docker/run `

**Anything else we need to know**:
I went through values.xml and I read this which seems not to apply to LoadBalancer type
`Options required for external access via NodePort
  ref:
  - http://kafka.apache.org/documentation/#security_configbroker
  - https://cwiki.apache.org/confluence/display/KAFKA/KIP-103%3A+Separation+of+Internal+and+External+traffic`
  
  ` Setting "advertised.listeners" here appends to "PLAINTEXT://${POD_IP}:9092,"
   "advertised.listeners": |-
     EXTERNAL://kafka.cluster.local:$((31090 + ${KAFKA_BROKER_ID}))
   "listener.security.protocol.map": |-
   PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT`

For now I'm not using a DNS so I would like to access it through one of the 3 PUBLIC IPs

**Comment by mayankkapoor** [comment]
I'm having the same issue on kafka deployed via helm on my minikube cluster. I used NodePorts to expose my kafka cluster. My minikube IP is 192.168.99.127.
```
$ kubectl -n kafka get svc
NAME                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
my-kafka                      ClusterIP   10.101.47.135    <none>        9092/TCP                     136m
my-kafka-0-external           NodePort    10.108.63.200    <none>        19092:31090/TCP              70m
my-kafka-1-external           NodePort    10.105.92.161    <none>        19092:31091/TCP              70m
my-kafka-2-external           NodePort    10.102.209.111   <none>        19092:31092/TCP              70m
my-kafka-headless             ClusterIP   None             <none>        9092/TCP                     136m
my-kafka-zookeeper            ClusterIP   10.110.25.15     <none>        2181/TCP                     136m
my-kafka-zookeeper-headless   ClusterIP   None             <none>        2181/TCP,3888/TCP,2888/TCP   136m

$ kafkacat -b 192.168.99.127:31090 -L
% ERROR: Failed to acquire metadata: Local: Broker transport failure
```

Accessing from inside the kubernetes cluster works fine.

**Comment by bonovoxly** [comment]
@mayankkapoor I'm seeing this issue as well.

Here's where I think the issue is:

https://github.com/helm/charts/blob/master/incubator/kafka/templates/service-brokers-external.yaml#L52

If you edit each external service and change the `targetPort` from `3109*` to `9092`, the load balancer should work.

I have found that the pods don't seem to be listening on those ports.

**Comment by bonovoxly** [comment]
Working on testing this (unsure how to do it): https://github.com/helm/charts/compare/master...bonovoxly:master

**Comment by mayankkapoor** [comment]
@bonovoxly I'm trying to fix and test as well. One comment: This issue happens for external.type "NodePort" as well. So we need to handle both cases, not just for LoadBalancer. If you want, please open a PR and we can collaborate together.

**Comment by bonovoxly** [comment]
Sounds good.

I see you have a WIP PR up, that looks good so far.

**Comment by valiksb** [comment]
@mayankkapoor and @bonovoxly actually I realized that the issue is not completely resolved in 0.14.2, 

` kafkacat -b 35.222.161.140:31090 -L
Metadata for all topics (from broker -1: 35.222.161.140:31090/bootstrap):
 3 brokers:
  broker 2 at wfp-q-kafka-2.wfp-q-kafka-headless.wfp:9092
  broker 1 at wfp-q-kafka-1.wfp-q-kafka-headless.wfp:9092
  broker 0 at wfp-q-kafka-0.wfp-q-kafka-headless.wfp:9092
 1 topics:
  topic "topic1" with 1 partitions:
    partition 0, leader 0, replicas: 0, isrs: 0`

even if I temporarely change my /etc/hosts file and add the hostnames above, when I try to connect as a consumer or producer, this is not working

`kafkacat -P -b 35.222.161.140:31090 -t topic1`and `kafkacat -C -b 35.222.161.140:31090 -t topic1`

will never return and so I have to kill those sessions.

I tried also 0.14.4 and it is actually even worse I get the original issue as mentioned in the first comment.

Any ideas what I might be doing wrong?

**Comment by mayankkapoor** [comment]
@valiksb In the [README](https://github.com/helm/charts/tree/master/incubator/kafka#example-valuesyml-and-dns-setup-for-external-service-type-loadbalancer), I've given an example of values.yml needed for accessing Kafka broker from outside using LoadBalancer on GKE. I believe you're not setting the advertised.listeners variable properly there, and hence your advertised.listeners are of the form `*.wfp-q-kafka-headless.wfp:9092`. Please review the updated README and let me know.

**Comment by valiksb** [comment]
@mayankkapoor thanks for the amazing changes in the README those are very good, see below my command and the values.xml

`external:
  enabled: true
  type: LoadBalancer
  distinct: true
  domain: example.com
configurationOverrides:
  "advertised.listeners": |-
    EXTERNAL://kafka-$((${KAFKA_BROKER_ID})).example.com:19092
  "listener.security.protocol.map": |-
    PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT`

`helm install --name wfp-q --namespace wfp -f ~/Documents/zebra/tmp/values.xml --version 0.14.4 incubator/kafka`

this is the output
`NAME:   wfp-q
E0416 05:46:46.217777   82387 portforward.go:303] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:62225->127.0.0.1:62228: write tcp4 127.0.0.1:62225->127.0.0.1:62228: write: broken pipe`

not sure what is this though and after this 
`LAST DEPLOYED: Tue Apr 16 05:46:45 2019
NAMESPACE: wfp
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME                      TYPE          CLUSTER-IP     EXTERNAL-IP  PORT(S)                     AGE
wfp-q-zookeeper-headless  ClusterIP     None           <none>       2181/TCP,3888/TCP,2888/TCP  1s
wfp-q-zookeeper           ClusterIP     10.19.246.159  <none>       2181/TCP                    1s
wfp-q-0-external          LoadBalancer  10.19.250.169  <pending>    31090:31291/TCP             1s
wfp-q-1-external          LoadBalancer  10.19.249.203  <pending>    31091:30222/TCP             1s
wfp-q-2-external          LoadBalancer  10.19.245.0    <pending>    31092:31309/TCP             1s
wfp-q-kafka               ClusterIP     10.19.252.73   <none>       9092/TCP                    1s
wfp-q-kafka-headless      ClusterIP     None           <none>       9092/TCP                    1s

==> v1beta1/StatefulSet
NAME             DESIRED  CURRENT  AGE
wfp-q-zookeeper  3        1        1s
wfp-q-kafka      3        1        1s

==> v1/Pod(related)
NAME               READY  STATUS             RESTARTS  AGE
wfp-q-zookeeper-0  0/1    ContainerCreating  0         1s
wfp-q-kafka-0      0/1    ContainerCreating  0         0s

==> v1beta1/PodDisruptionBudget
NAME             MIN AVAILABLE  MAX UNAVAILABLE  ALLOWED DISRUPTIONS  AGE
wfp-q-zookeeper  N/A            1                0                    1s


NOTES:
### Connecting to Kafka from inside Kubernetes

You can connect to Kafka by running a simple pod in the K8s cluster like this with a configuration like this:

  apiVersion: v1
  kind: Pod
  metadata:
    name: testclient
    namespace: wfp
  spec:
    containers:
    - name: kafka
      image: confluentinc/cp-kafka:5.0.1
      command:
        - sh
        - -c
        - "exec tail -f /dev/null"

Once you have the testclient pod above running, you can list all kafka
topics with:

  kubectl -n wfp exec testclient -- /opt/kafka/bin/kafka-topics.sh --zookeeper wfp-q-zookeeper:2181 --list

To create a new topic:

  kubectl -n wfp exec testclient -- /opt/kafka/bin/kafka-topics.sh --zookeeper wfp-q-zookeeper:2181 --topic test1 --create --partitions 1 --replication-factor 1

To listen for messages on a topic:

  kubectl -n wfp exec -ti testclient -- /opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server wfp-q-kafka:9092 --topic test1 --from-beginning

To stop the listener session above press: Ctrl+C

To start an interactive message producer session:
  kubectl -n wfp exec -ti testclient -- /opt/kafka/bin/kafka-console-producer.sh --broker-list wfp-q-kafka-headless:9092 --topic test1

To create a message in the above session, simply type the message and press "enter"
To end the producer session try: Ctrl+C

### Connecting to Kafka from outside Kubernetes

You have enabled the external access feature of this chart.

**WARNING:** By default this feature allows Kafka clients outside Kubernetes to
connect to Kafka via NodePort(s) in `PLAINTEXT`.

Please see this chart's README.md for more details and guidance.

If you wish to connect to Kafka from outside please configure your external Kafka
clients to point at the following brokers. Please allow a few minutes for all
associated resources to become healthy.

  wfp-q.cluster.local:31090
  wfp-q.cluster.local:31091
  wfp-q.cluster.local:31092`

kubetctl get svc
`wfp-q-0-external            LoadBalancer   10.19.250.169   104.198.35.60     31090:31291/TCP              2m
wfp-q-1-external            LoadBalancer   10.19.249.203   104.198.214.128   31091:30222/TCP              2m
wfp-q-2-external            LoadBalancer   10.19.245.0     35.226.160.255    31092:31309/TCP              2m
wfp-q-kafka                 ClusterIP      10.19.252.73    <none>            9092/TCP                     2m
wfp-q-kafka-headless        ClusterIP      None            <none>            9092/TCP                     2m
wfp-q-zookeeper             ClusterIP      10.19.246.159   <none>            2181/TCP                     2m`

kubectl get pods
`wfp-q-kafka-0                            1/1     Running     0          3m
wfp-q-kafka-1                            1/1     Running     0          2m
wfp-q-kafka-2                            1/1     Running     0          1m
wfp-q-zookeeper-0                        1/1     Running     0          3m
wfp-q-zookeeper-1                        1/1     Running     0          3m
wfp-q-zookeeper-2                        1/1     Running     0          2m`

kafkacat -b 104.198.35.60:31090 -L
`% ERROR: Failed to acquire metadata: Local: Broker transport failure`

**Comment by mayankkapoor** [comment]
@valiksb A few things on a quick read of values.yml:
- You need to configure a DNS name for each external broker, as mentioned in the README.
- You need to update the domain in the values.yml, both in "domain: example.com" and in "advertised.listeners", with the actual Domain name configured.
- Even though your values.yml says you're setting advertised.listeners with port 19092, the external services are coming up with port 3109X and their domain is cluster.local. This doesn't look right.

Please read the README again, and try and follow the steps exactly as shown. I've tested that exact config in README on GKE already, with a real domain.

**Comment by amit-k-yadav** [comment]
@mayankkapoor is it possible to do it only with the IP addresses and not mentioning the domain?
Currently, we are not using domains so what should be my exact values.yaml file changes to expose one replica of Kafka broker as load balancer?
```
 external:
-  enabled: false
+  enabled: true
   # type can be either NodePort or LoadBalancer
-  type: NodePort
+  type: LoadBalancer
   # annotations:
   #  service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
   dns:
@@ -138,10 +138,10 @@ external:
   distinct: false
   servicePort: 19092
   firstListenerPort: 31090
   domain: cluster.local
   loadBalancerIP: [35.200.238.174,35.244.44.162,35.200.149.80]
   init:
     image: "lwolf/kubectl_deployer"
@@ -173,11 +173,11 @@ configurationOverrides:
   # "advertised.listeners": |-
   #   EXTERNAL://kafka.cluster.local:$((31090 + ${KAFKA_BROKER_ID}))
   ## If external service type is LoadBalancer and distinct is true:
-  # "advertised.listeners": |-
-  #   EXTERNAL://kafka-$((${KAFKA_BROKER_ID})).cluster.local:19092
+  "advertised.listeners": |-
+    EXTERNAL://${LOAD_BALANCER_IP}:31090
   ## Uncomment to define the EXTERNAL Listener protocol
-  # "listener.security.protocol.map": |-
-  #   PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
+  "listener.security.protocol.map": |-
+    PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
```

The above changes mentioned in the [README](https://github.com/helm/charts/tree/master/incubator/kafka) did not work for me.

**Comment by mayankkapoor** [comment]
@amit-k-yadav With `distinct` set to `true`, as long as the "advertised.listeners" variable is correctly set with all three distinct broker LOAD_BALANCER_IPs, it should work. I see no reason for it not to work.

In your snippet, I see that `distinct` is set to `false`. This means the all the externally exposed kafka brokers will have the same external IP. This doesn't make sense as any client who wants to connect to kafka will not be able to distinguish between the 3 brokers. I would recommend trying with `distinct: true`, and making sure `advertised.listeners` variable is set correctly. E.g. I would test by setting it to:
```
"advertised.listeners": |-
  EXTERNAL://${LOAD_BALANCER_IP}:19092
```

**Comment by dsindatry** [comment]
@mayankkapoor Can you explain what is external.distinct . I am using eks and spun up my kafka cluster and want to use load balancer per broker pod instead of Node/Port

**Comment by mayankkapoor** [comment]
> @mayankkapoor Can you explain what is external.distinct . I am using eks and spun up my kafka cluster and want to use load balancer per broker instead of Node/Port
> How do i get these ip's from for load balancer ? Example :- loadBalancerIP: [35.200.238.174,35.244.44.162,35.200.149.80]

@dsindatry Please see [here](https://github.com/helm/charts/tree/master/incubator/kafka#loadbalancer-external-service-type). 
```
   # If using external service type LoadBalancer and external dns, set distinct to true below.
   # This creates an A record for each statefulset pod/broker. You should then map the
   # A record of the broker to the EXTERNAL IP given by the LoadBalancer in your DNS server.
-  distinct: false
+  distinct: true
...
+  "advertised.listeners": |-
+    EXTERNAL://kafka-$((${KAFKA_BROKER_ID})).example.com:19092
```
Disclaimer: I haven't tried this in EKS. `external.distinct` set to `true` will create different A records for each broker. You should use your external DNS service to route these A records properly to LoadBalancer IP. The LoadBalancer IPs will be automatically assigned to the brokers' `service` if EKS LoadBalancer integration with Kubernetes is working fine. You would see the LB IPs when doing `kubectl get services --all-namespaces`

**Comment by dsindatry** [comment]
If my clients using kafka are also in aws why do i need external dns ? Why cannot i create an internal load balancer (ALB) . Internal ALB service per pod. 
Also, I am trying to spin a dev cluster and using "cp-helm-charts" . Can i not modify https://github.com/confluentinc/cp-helm-charts/blob/master/charts/cp-kafka/values.yaml bu adding the key:values for LoadBalancer and use it ?

**Comment by mayankkapoor** [comment]
@dsindatry 
1. Yes, An AWS internal service that translates broker URLs/LB IPs to the kafka broker kubernetes service should work as well.
2. Sorry, I haven't tried cp-helm-charts so wouldn't be able to answer.

**Comment by dsindatry** [comment]
ty. Can we expose zookeeper also as an loadbalancer ? I dont see external for zookeeper. @mayankkapoor

**Comment by dsindatry** [comment]
Hello, When i try to run a perf test using the load balanced urls i get this error. 

 ./kafka-producer-perf-test  --topic test-rep-five  --num-records 10000000 --record-size 100 --throughput -1 --producer-props bootstrap.servers=a466bc8bc64944d1ab0ead839717e730-f6bfddc3a8b62cd9.elb.us-east-2.amazonaws.com:31090,a80e43c5be5734c88ac138bd23f41396-fb1f496870363af3.elb.us-east-2.amazonaws.com:31090,aef764779769f436b95f20988db966a6-04824e4762152963.elb.us-east-2.amazonaws.com:31090

[2020-07-01 14:37:45,184] WARN [Producer clientId=producer-1] Error connecting to node my-kafka-0.my-kafka-headless.kafka.svc.cluster.local:31090 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: my-kafka-0.my-kafka-headless.kafka.svc.cluster.local


Can someone please throw some light ? should'nt this work as expected ?
@mayankkapoor
