### ISSUE TITLE
cannot enable jenkins JCasC

### ISSUE THREAD

**Issue by stubbi** [helm/charts#11864]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Version of Helm and Kubernetes**: 

```
helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.3", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-10T00:39:15Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: Jenkins

**What happened**: 
I set [`JCasC.enabled:true`](https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml#L176), try it via

```
helm install --name "jenkins" --set Master.JCasC.enabled=true  stable/jenkins
```

Helm seems to ignore this setting during the deployment. No part of the setup conditioned by

```
{{- if .Values.Master.JCasC.enabled }}
```

is performed. See for instance 

```
{{ if .Values.Master.JCasC.enabled }}
4. Use Jenkins Configuration as Code by specifying ConfigScripts in your values.yaml file, see documentation: http://{{ .Values.Master.HostName }}/configuration-as-code and examples: https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos
{{- end }}
```
in [NOTES.txt](https://github.com/helm/charts/blob/master/stable/jenkins/templates/NOTES.txt#L29-L31). Nor is the env var `CASC_JENKINS_CONFIG` set, checked by running

```
println System.getenv("CASC_JENKINS_CONFIG")
```

in `http://{JENKINS_URL}/computer/(master)/script`. This returns `null` although [it should also get set when `JCasC.enabled=true`](https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml#L178-L181)

**What you expected to happen**:
That `JCasC` becomes enabled in Jenkins and a configuration gets created. Neiher happens. Nor would I see the message from `NOTES.txt` in the console.

**How to reproduce it** (as minimally and precisely as possible):

1. 
```
helm install --name "jenkins" --set Master.JCasC.enabled=true  stable/jenkins
```
2. check `JCasC` configuration in jenkins.

**Anything else we need to know**:

JCasC becomes available in Jenkins UI when I add `configure-as-code` and `configure-as-code-support` in to the [`InstallPlugins`](https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml#L137) in `values.yaml`. This seems completely independent of any setting in the `JCasC` section of the `values.yaml`.

**Comment by maorfr** [comment]
What about:
```
helm install --name "jenkins" --set Master.JCasC.enabled=true  stable/jenkins
```

Or was this just a typo?

**Comment by stubbi** [comment]
@maorfr good catch! This was just a typo though, just verified it and edited the question. Is it working for you?

**Comment by maorfr** [comment]
It is.
maybe @holmesb can help here?

**Comment by stubbi** [comment]
okay. That's weird. Thanks for testing! 🙂

**Comment by forhire** [comment]
I seem to be having the same issue with the stable/jenkins Helm chart. If I git clone the github Helm and run:

jenkins install jenkins -f myvalues.yaml . 

it at least prints item 4 from the NOTES.TXT, indicating that it picked up the JCasC setting is enabled. There seems to be an issue with the stable/jenkins Helm Repo chart.

**Comment by forhire** [comment]
I verified that cloning the Jenkins code at https://github.com/helm/charts/tree/master/stable/jenkins and doing a deployment from that code works with JCasC while the stable/jenkins Helm chart doesn't. Seems like the current Github Helm chart code for Jenkins needs to be bundled and added to the https://kubernetes-charts.storage.googleapis.com repo.

**Comment by holmesb** [comment]
Can't reproduce this.  `helm install --name jenkins --set Master.JCasC.enabled=true stable/jenkins` is working fine for me.  CasC config (eg welcome message) is appearing, Notes is displaying point 4 and `println System.getenv("CASC_JENKINS_CONFIG")` is correctly showing `/var/jenkins_home/casc_configs`.

**Comment by forhire** [comment]
Compare and contrast:

$ helm install --name "jenkins-test" --set Master.JCasC.enabled=true stable/jenkins
NAME:   jenkins-test
LAST DEPLOYED: Mon Mar 11 17:38:12 2019
NAMESPACE: jenkins-kubernetes
STATUS: DEPLOYED

RESOURCES:
==> v1/PersistentVolumeClaim
NAME          STATUS   VOLUME    CAPACITY  ACCESS MODES  STORAGECLASS  AGE
jenkins-test  Pending  standard  1s

==> v1/Service
NAME                TYPE          CLUSTER-IP     EXTERNAL-IP  PORT(S)         AGE
jenkins-test-agent  ClusterIP     10.15.249.36   <none>       50000/TCP       1s
jenkins-test        LoadBalancer  10.15.240.248  <pending>    8080:31852/TCP  1s

==> v1/Deployment
NAME          DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
jenkins-test  1        1        1           0          1s

==> v1/Pod(related)
NAME                           READY  STATUS   RESTARTS  AGE
jenkins-test-54b5555976-9sz5v  0/1    Pending  0         1s

==> v1/Secret
NAME          TYPE    DATA  AGE
jenkins-test  Opaque  2     1s

==> v1/ConfigMap
NAME                DATA  AGE
jenkins-test        5     1s
jenkins-test-tests  1     1s


NOTES:
1. Get your 'admin' user password by running:
  printf $(kubectl get secret --namespace jenkins-kubernetes jenkins-test -o jsonpath="{.data.jenkins-admin-password}" | base64 --decode);echo
2. Get the Jenkins URL to visit by running these commands in the same shell:
  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        You can watch the status of by running 'kubectl get svc --namespace jenkins-kubernetes -w jenkins-test'
  export SERVICE_IP=$(kubectl get svc --namespace jenkins-kubernetes jenkins-test --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
  echo http://$SERVICE_IP:8080/login

3. Login with the password from step 1 and the username: admin

For more information on running Jenkins on Kubernetes, visit:
https://cloud.google.com/solutions/jenkins-on-container-engine

$ helm delete jenkins-test --purge 

$ helm install --name "jenkins-test" --set Master.JCasC.enabled=true . #from git repo
NAME:   jenkins-test
LAST DEPLOYED: Mon Mar 11 17:39:54 2019
NAMESPACE: jenkins-kubernetes
STATUS: DEPLOYED

RESOURCES:
==> v1/Pod(related)
NAME                           READY  STATUS       RESTARTS  AGE
jenkins-test-54b5555976-9sz5v  0/1    Terminating  0         102s
jenkins-test-7cf5d89d5b-g8wgf  0/1    Pending      0         1s

==> v1/Secret
NAME          TYPE    DATA  AGE
jenkins-test  Opaque  2     1s

==> v1/ConfigMap
NAME                DATA  AGE
jenkins-test        6     1s
jenkins-test-tests  1     1s

==> v1/PersistentVolumeClaim
NAME          STATUS   VOLUME    CAPACITY  ACCESS MODES  STORAGECLASS  AGE
jenkins-test  Pending  standard  1s

==> v1/Service
NAME                TYPE          CLUSTER-IP     EXTERNAL-IP  PORT(S)         AGE
jenkins-test-agent  ClusterIP     10.15.252.107  <none>       50000/TCP       1s
jenkins-test        LoadBalancer  10.15.242.44   <pending>    8080:30442/TCP  1s

==> v1/Deployment
NAME          DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
jenkins-test  1        1        1           0          1s


NOTES:
1. Get your 'admin' user password by running:
  printf $(kubectl get secret --namespace jenkins-kubernetes jenkins-test -o jsonpath="{.data.jenkins-admin-password}" | base64 --decode);echo
2. Get the Jenkins URL to visit by running these commands in the same shell:
  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        You can watch the status of by running 'kubectl get svc --namespace jenkins-kubernetes -w jenkins-test'
  export SERVICE_IP=$(kubectl get svc --namespace jenkins-kubernetes jenkins-test --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
  echo http://$SERVICE_IP:8080/login

3. Login with the password from step 1 and the username: admin

4. Use Jenkins Configuration as Code by specifying ConfigScripts in your values.yaml file, see documentation: http:///configuration-as-code and examples: https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos

For more information on running Jenkins on Kubernetes, visit:
https://cloud.google.com/solutions/jenkins-on-container-engine
For more information about Jenkins Configuration as Code, visit:
https://jenkins.io/projects/jcasc/

**Comment by forhire** [comment]
Doing a helm repo update got it working from stable/jenkins ...

Doug

**Comment by stubbi** [comment]
@forhire yes! Indeed all I needed to do was to run

```
helm repo update
```

to make it working 🎉 

Thanks a lot! I will close the issue
