### ISSUE TITLE
FT. REQ.: SFTP sidecar container on stable/wordpress

### ISSUE THREAD

**Issue by a-barbieri** [helm/charts#11882]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm `v2.13.0`
Kubernetes `v1.10.11`

**Which chart**:
stable/wordpress

**What happened**:

I cannot access Wordpress file via SFTP.

**What you expected to happen**:

I would like to have a *SFTP sidecar container* on the *stable/wordpress* chart. This would be useful for many reasons, above all allowing some WP developers to use their usual workflow (which requires a FTP connection).

I wonder if it hasn't been implemented on purpose. If not, I can try to make a PR.

**How to reproduce it** (as minimally and precisely as possible):

/

**Anything else we need to know**:

/

**Comment by javsalgar** [comment]
Hi,

I don't think that explicitily setting a SFTP sidecar container in the chart makes sense. However, I created a PR that you can use for adding custom sidecar containers and setting extra ports in the service definition. This way you could add the SFTP sidecar container that you need

https://github.com/helm/charts/pull/11893

**Comment by a-barbieri** [comment]
This is even better as it makes this chart more flexible in a number of ways.

Looking forward to see the PR accepted.
Much appreciated.
