### ISSUE TITLE
neo4j cant mount volumes for /data an /logs works in minikube not in other environments

### ISSUE THREAD

**Issue by prem-jason** [helm/charts#11889]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.3-1+fee411aca93f0e", GitCommit:"fee411aca93f0e786995cc125cf8f9783484f958", GitTreeState:"clean", BuildDate:"2018-12-04T06:45:24Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
neo4j

**What happened**:
volume mounts happen in minikube, but doesnt work in other environments 
$ kubectl logs -l "app=neo4j,component=core" 
Changed password for user 'neo4j'.
chmod: /data/.snapshot: Read-only file system
chmod: /data/.snapshot: Read-only file system
Changed password for user 'neo4j'.
chmod: /data/.snapshot: Read-only file system
chmod: /data/.snapshot: Read-only file system
Changed password for user 'neo4j'.

**What you expected to happen**:
its supposed work, help me identifying the issue

**How to reproduce it** (as minimally and precisely as possible):
just running helm install

**Anything else we need to know**:
as i am not that much experienced in kubernetes it can be simple issue

**Comment by dshakey** [comment]
did you get answer on how to fix this? I have same problem.
