### ISSUE TITLE
[stable/prometheus-operator] Low resource requests on sidecars Alertmanager and Prometheus

### ISSUE THREAD

**Issue by MisterTimn** [helm/charts#11891]
**Version of Helm and Kubernetes**:
Helm: v2.13
Kubernetes: v1.13.3

**Which chart**:
[stable/prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator)

**What happened**:
Prometheus and Alertmanager do not deploy properly, config-reloader and configmap-reloader go into error state.

output of kubectl describe on Alertmanager pod (only the sidecar part):
```
 config-reloader:
    Container ID:  docker://15b92a20305388ff7815cc9710ae5fd48b301ecee0c139f97877b70829169176
    Image:         quay.io/coreos/configmap-reload:v0.0.1
    Image ID:      docker-pullable://quay.io/coreos/configmap-reload@sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057
    Port:          <none>
    Host Port:     <none>
    Args:
      -webhook-url=http://127.0.0.1:9093/monitoring/alertmanager/-/reload
      -volume-dir=/etc/alertmanager/config
    State:          Running
      Started:      Fri, 01 Mar 2019 22:05:47 +0100
 State:          Running
      Started:      Fri, 01 Mar 2019 22:05:47 +0100
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write 10485760 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/kubepods/burstable/podc0b26c5c-3c3d-11e9-9063-005056a42579/6fb668d6128ec5ad33145c84b4c8816030f38985a41ec4ffc75c52c9b4b3ef9f/memory.limit_in_bytes: device or resource busy\\\"\"": unknown
```

After 61 restarts, the pod deploys succesfully and my service becomes available.

I found similar issues around low resource requests, to test it out I deployed some pods myself with the low resources request and I got the same error, uping the requests by a little made the pod deploy without a hitch.

I can't seem to change the resource requestof the prometheus and alertmanager daemonset, if I alter the daemonset and restart the pods, it still takes the old resource requests (probably this is defined in the custom resource def?)

**What you expected to happen**:
Both Prometheus and Alertmanager deploy without a hitch

**How to reproduce it** (as minimally and precisely as possible):
Deploy the chart on K8s v1.13.3

**Anything else we need to know**:
I looked into the issue and I think it has to do with the low resource requests that are set on the sidecars.

**Comment by vsliouniaev** [comment]
The defaults for these resources are specified as part of the coreos/prometheus-operator project.
The ability to add overrides to them is intended to be set through the prometheus operator deployment. There's an open pull-request for adding this configuration https://github.com/helm/charts/pull/11811
