### ISSUE TITLE
[stable/prometheus] Set default url http://prometheus.default.svc available

### ISSUE THREAD

**Issue by KlimTodrik** [helm/charts#11907]
**Is this a request for help?**:

Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

I develop HPA on Custom Metrics. I use Prometheus for scrapping metrics and Prometheus Adapter, to return this metrics to Kubernetes. But when i making chart, i use this as dependencies. Prometheus Adapter use default service name in default namespace http://prometheus.default.svc. Of course i can set custom name, but when chart installs i don't know yet how Prometheus service will names, and as a result his URL.

How can i set this (http://prometheus.default.svc) host for Prometheus? 

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

**Which chart**:
`stable/prometheus`

**Comment by djklim87** [comment]
Solution [there](https://github.com/helm/charts/issues/11924)
