### ISSUE TITLE
helm chart install fails with Error: error validating "": error validating data: field spec.dataSource for v1.PersistentVolumeClaimSpec is required

### ISSUE THREAD

**Issue by digressionary** [helm/charts#11901]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

Kubernetes 1.13.0

**Which chart**:
stable/mongodb

**What happened**:
Error: error validating "": error validating data: field spec.dataSource for v1.PersistentVolumeClaimSpec is required

**What you expected to happen**:
The chart to install mongo

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/mongodb
Error: error validating "": error validating data: field spec.dataSource for v1.PersistentVolumeClaimSpec is required

**Anything else we need to know**:
It was working before the last commit.

**Comment by juan131** [comment]
Hi @digressionary 

What version of the MongoDB chart are you using? I was unable to reproduce the issue using the latest one:

```bash
$ helm repo update
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
$ helm install stable/mongodb --name mongo
NAME:   mongo
LAST DEPLOYED: Wed Mar  6 11:36:53 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
...
```

**Comment by pauloeliasjr** [comment]
Hi @digressionary Try updating your helm version to a newer one (v2.13.0).  This release adds, among other features, kubernetes 1.13.0 libraries updates. I was having the same problem with other repositories and after upgrading to helm 2.13.0, the problem is gone.

**Comment by bzeyben** [comment]
I have the same problem with helm version 2.14.0.

**Comment by bzeyben** [comment]
Upgrading the components to: 
- minikube version: v1.0.1 
- kubectl v1.10.11 client, v1.14.1 server
- helm v2.14.0 client + server
did not help either...

**Comment by juan131** [comment]
Hi @bzeyben 

What version of the MongoDB chart are you using?
