### ISSUE TITLE
Helm install doesn't work with version 4.2.1 for prometheus-operator using inline repo flag

### ISSUE THREAD

**Issue by lahsivjar** [helm/charts#11918]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm version:
```Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```
Kubernetes version:
```Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.6", GitCommit:"a2fae0aa5d813f814d667711324501312b76e64f", GitTreeState:"clean", BuildDate:"2019-01-18T19:40:57Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
prometheus-operator version 4.2.1

**What happened**:
```Error: chart "prometheus-operator" version "4.2.0" not found in https://s3-eu-west-1.amazonaws.com/coreos-charts/stable repository```

**What you expected to happen**:
Prometheus operator installs without any issues

**How to reproduce it** (as minimally and precisely as possible):

Run the below command without adding explicit helm repository: 
```
helm install --repo https://s3-eu-west-1.amazonaws.com/coreos-charts/stable prometheus-operator --namespace temp --version 4.2.1
```

**Comment by vsliouniaev** [comment]
The helm/charts charts are pushed to https://kubernetes-charts.storage.googleapis.com. Incidentally, this is the default configured `stable` chart repository that comes with helm by default.

You can instead use
```
helm install stable/prometheus-operator --namespace temp --version 4.2.1
```
