### ISSUE TITLE
[stable/rabbitmq-ha] add ability to use management credentials from secret

### ISSUE THREAD

**Issue by chrisxaustin** [helm/charts#11915]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Version of Helm and Kubernetes**:

```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

**Which chart**:

stable/rabbitmq-ha

**What happened**:

The *existingSecret* in values.yaml allows the user to provide rabbitmq-username, rabbitmq-password, and definitions.json in a somewhat secure way, but does not appear to provide a way to configure the liveness and readiness checks to use credentials from the secret. These appear to be required in the values.yaml.

As a workaround I store most configuration in values.yaml within our github, and use a separate local yaml for the managementUsername and managementPassword. This limits me somewhat since I can't use terraform to apply this chart along with our others.

**What you expected to happen**:

Ability to provide management credentials for readiness/liveness checks in a secret.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by steven-sheehy** [comment]
I would accept a PR that does what you're suggesting. In the meantime, you can always use a tool like [git-crypt](https://github.com/LykkeCity/git-crypt) to store your secrets directly with the chart and have it decrypt via your CI/CD. I go one step further and use a dependent chart that only contains my secrets.
