### ISSUE TITLE
[stable/rabbitmq-ha] ServiceMonitor has 10 endpoints for 5 nodes

### ISSUE THREAD

**Issue by estahn** [helm/charts#11910]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

`stable/rabbitmq-ha`

**What happened**:

Prometheus targets 10 endpoints while having only 5 replicas of RabbitMQ running. The [service monitor](https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/templates/servicemonitor.yaml) appears to pick up both the [regular service](https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/templates/service.yaml) and [discovery service](https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/templates/service-discovery.yaml).

**What you expected to happen**:

Should only target the number of replicas available instead of double.

**How to reproduce it** (as minimally and precisely as possible):

* Run prometheus operator
* Run stable/rabbitmq-ha
* Check targets in prometheus

**Anything else we need to know**:

**Comment by steven-sheehy** [comment]
Not sure how to workaround that. The regular service is necessary for client apps and the discovery service is necessary for rabbit to rabbit communication. They both use the same labels except one tolerates unready endpoints. There doesn't seem to be a way in ServiceMonitor to re-use a service. Really, Prometheus should be smart enough to drop duplicate pods.

**Comment by estahn** [comment]
@steven-sheehy How about adding another label as a differentiator?

**Comment by steven-sheehy** [comment]
A new label would be a breaking change, not allowing upgrades. Also, I don't think it would solve your problem since the labels in podspec would be applied to all pods.

**Comment by estahn** [comment]
@steven-sheehy Apologies, I should have been more precise. I mean adding a label to the service, perhaps `service: default` and `service: discovery`.

**Comment by steven-sheehy** [comment]
Not sure how that would help, the ServiceMonitor doesn't filter down by service labels, right? As far as I understand it operates the same as the service `spec.selector` and filters down pods by their labels.

**Comment by estahn** [comment]
@steven-sheehy No, it's using [kubernetes_sd_config endpoints](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#endpoints).

I just added this manually and it works.

**Comment by estahn** [comment]
@steven-sheehy Do you want me to provide a pull request?

**Comment by steven-sheehy** [comment]
@estahn Sure, if I understand it correctly your change should be backwards compatible with existing installations.
