### ISSUE TITLE
Gitlab prometheus errors with RBAC enabled

### ISSUE THREAD

**Issue by simontesar** [helm/charts#1191]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
```
```
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.3.395+885ddcc1389bf7", GitCommit:"885ddcc1389bf744f00e7a5f96fbff5515423022", GitTreeState:"clean", BuildDate:"2017-05-15T06:32:31Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/gitlab-ce 
probably stable/gitlab-ee 

**What happened**:
Gitlab ships prometheus since 9.0 and tries to retrieve Kubernetes nodes per default, resulting in the following error:
```
2017-05-29_12:39:10.38663 time="2017-05-29T12:39:10Z" level=error msg="github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *v1.Node: the server does not allow access to the requested resource (get nodes)" component="kube_client_runtime" source="kubernetes.go:73"
```

**What you expected to happen**:
No errors to appear

**How to reproduce it** (as minimally and precisely as possible):
Install stable/gitlab-ce on a RBAC enabled cluster

**Anything else we need to know**:

**Comment by ivelichkovich** [comment]
@simt2 I had a similar issue with a different RBAC. I believe the error you're seeing comes from missing rights. Try giving prometheus full cluster rights and see if it fixes the issue. Then you can narrow down the permissions from there.
