### ISSUE TITLE
[stable/prometheus-adapter] Connect to Prometheus service

### ISSUE THREAD

**Issue by KlimTodrik** [helm/charts#11924]
**Is this a request for help?**: Yes
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
 FEATURE REQUEST
**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

**Which chart**:
`stable/prometheus-adapter`

**What happened**:
I'm using Prometheus and Prometheus Adapter as dependency for my project. How can i set connection url for Prometheus Adapter? Cause i don't know how will name's Prometheus Service and as a consequence can't know URL in advance!

**What you expected to happen**:
May be set default URL as Prometheus service name? Like http://{{.Release.Name}}-prometheus-server

https://github.com/benmathews/charts/blob/master/stable/prometheus/templates/server-service.yaml
Thus, with the default deployment, everything immediately works without needing to set URL

**Comment by steven-sheehy** [comment]
It would just be `http://<prometheus-service>`. If you're saying that because the service contains the release name in it you can't know that until it's deployed, you can always set the helm release name manually instead of letting it choose a random name.

Also, you can directly override the prometheus service name by setting `server.fullnameOverride=myprometheus` and it won't contain the chart name or release name.

**Comment by djklim87** [comment]
> you can always set the helm release name manually instead of letting it choose a random name.
I don't know how user will names chart. And i cant use {{.Release.Name}} in values.yaml

> Also, you can directly override the prometheus service name by setting `server.fullnameOverride=myprometheus` and it won't contain the chart name or release name.
This directive allowed only in Prometheus Operator

**Comment by steven-sheehy** [comment]
> This directive allowed only in Prometheus Operator

Actually, no I'm referring to the Prometheus chart which does have this [option](https://github.com/helm/charts/blob/5b434d3aefcbdcc231423713fb11b5dd72b8f76d/stable/prometheus/templates/_helpers.tpl#L145).

**Comment by djklim87** [comment]
Yes, but how i can override this, if i use that chart as dependency?

**Comment by steven-sheehy** [comment]
In your parent chart `values.yaml`:
```yaml
prometheus:
  server:
    fullnameOverride: myprometheus
```

Where `prometheus` is the name of the sub-chart or alias in your `requirements.yaml`.

**Comment by djklim87** [comment]
Yes it's good solution for me. Very strange that this directive is not documented [there](https://github.com/helm/charts/tree/master/stable/prometheus#configuration)
