### ISSUE TITLE
[stable/wordpress] Traefik ingress on baremetal doesn't find Wordpress service 

### ISSUE THREAD

**Issue by kevinhooke** [helm/charts#11920]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): No

**Version of Helm and Kubernetes**: Helm v2.12.3 / Kubernetes 1.13.0 on Ubuntu Server 16.04.5, running on VMware ESXi 

**Which chart**: stable/wordpress

**What happened**: Traefik ingress doesn't find Wordpress service

**What you expected to happen**: Traefik should be able to map an ingress route to Wordpress

**How to reproduce it** (as minimally and precisely as possible):
Helm Tiller installed in namespace=tiller
Wordpress chart installed in same namespace
Traefik installed in same namespace

**Anything else we need to know**:
Attempting to create a simple route in Traefik to Wordpress, and it does not find/map to the Wordpress service. Here's my ingress yaml:
`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ubuntu-esxi-test-wordpress
  namespace: tiller
spec:
  rules:
  - host: kube-esxi-vps3
    http:
      paths:
      - path: /
        backend:
          serviceName: ubuntu-esxi-test-wordpress
          servicePort: http`

Traefik doesn't find the Wordpress service with name ubuntu-esxi-test-wordpress. I suspect I'm missing a selector or something, but I don't know enough to be able to triage what is wrong/missing.

Is there an example Traefik ingress yaml for the Wordpress chart that can be used as a reference?

**Comment by kevinhooke** [comment]
I think I narrowed this down to an issue with the MariaDB pod starting up, with write permissions on the PV, which is in tern impacting the Wordpress pod and it's never reaching Running state. I'll close this for now to look at the MariaDB issue instead.

**Comment by juan131** [comment]
Hi @kevinhooke 

I guess WordPress pods didn't reach the ready status since MariaDB wasn't starting and therefore, WordPress could not initialise the database. That implicate the WordPress service can't find any endpoint and, as a consequence, the ingress can't access to WordPress.

Please let us know if we can help you debugging the permission issue with MariaDB PV.

**Comment by kevinhooke** [comment]
Thanks for the followup. I've read around and found suggestions to chown 1001:1001 for the MariaDB pv, but I haven't had a chance to try it yet. I'll report back once I've tried it out. Thanks!
