### ISSUE TITLE
[stable/mssql-linux] "pod has unbound PersistentVolumeClaims"

### ISSUE THREAD

**Issue by arielorvits** [helm/charts#11942]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
kubernetes v1.10.11
helm v2.12.3
**Which chart**:
stable/mssql-linux

**What happened**:
when installed locally (kubernetes on docker for windows) with the default installation:
helm install --name mymssql stable/mssql-linux --set acceptEula.value=Y --set edition.value=Developer
I got "pod has unbound PersistentVolumeClaims" error

**What you expected to happen**:
no errors

**How to reproduce it** (as minimally and precisely as possible):
just use this install command on kubernetes on docker for windows

**Anything else we need to know**:

**Comment by joshuaBonn** [comment]
Hi, I just ran into the same problem. 

You can fix this by adding `--set persistence.enabled=false`. The chart's documentation appears to be incorrect as the default value listed in values.yml is `true` while the documentation says its `false`.

**Comment by arielorvits** [comment]
Hi, 
what exactly it means that the data wont persist? 
is it means that if the sql machine deleted for some reason it wont persist for the replacement machine?
