### ISSUE TITLE
[stable/mongodb] Add init container support

### ISSUE THREAD

**Issue by unclenorton** [helm/charts#11948]
**Is this a request for help?**: Yes.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

**Which chart**:
[stable/mongodb] version 5.7.0

**What happened**:
I need to run an init container for some preliminary configuration, and I believe this is required in various scenarios. Since init container configuration is not included in the template, I had to fetch and edit it locally.

**What you expected to happen**:
Init container configuration values can be passed as values when including the chart as a dependency.

**How to reproduce it** (as minimally and precisely as possible):
Not quite applicable.

**Anything else we need to know**:
I've already fixed this in a way similar to #10423. I have prepared a pull request that I will reference below after this issue is created.

**Comment by unclenorton** [comment]
Hi, @tompizmor! Would you be able to review the PR fixing this?

**Comment by juan131** [comment]
Reviewing your PR @unclenorton !! Thanks for your contribution.
