### ISSUE TITLE
[Bug Report] [incubator/vault] optional consul agent encrypt key gets double encoded

### ISSUE THREAD

**Issue by kofl91** [helm/charts#11947]
**Version of Helm and Kubernetes**:
Helm: 2.9.4 
Kubernetes: 1.8 / 1.9 / 1.10

**Which chart**:
incubator/Vault

**What happened**:
When using the optional Consul Agent to connect to a Consul Server with encrypted Gossip
And providing the correct encryption key via a Kubernetes Secret
it results in an error saying 'no key in the keychain can be used to decrypt the message'.

On checking the file created by the helm chart to store the encryption key,
I see that the key is base64 encoded instead of plain text.

Trying out consul without Helm chart and Kubernetes,
I can see it requires a plain text encryption key.

**How to reproduce it** (as minimally and precisely as possible):
Have a Consul Server with enabled gossip encryption.
Deploy this Helm chart with the optional Consul Agent.
Provide a secret with the gossip encryption key.
See the logs of the failed pod sidecar `vault-consul-agent`

**Anything else we need to know**:

These lines should be changed:
```

            {{- if .Values.consulAgent.gossipKeySecretName }}
            if [ -e /etc/consul/secrets/gossip-key ]; then
              echo "{\"encrypt\": \"$(base64 /etc/consul/secrets/gossip-key)\"}" > /etc/consul/encrypt.json
              GOSSIP_KEY="-config-file /etc/consul/encrypt.json"
            fi
```
            {{- end }}

**Comment by openJT** [comment]
Came back to say thank you @kofl91, lost so much time because of this. Had to patch the deployment passing the GOSSIP_ENCRYPTION_KEY environment variable to go around this issue.
