### ISSUE TITLE
setting customHTAccessCM causes "not a directory" error

### ISSUE THREAD

**Issue by chrisovergaauw** [helm/charts#11941]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

**helm**
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}

**kubernetes**
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**: stable/wordpress

**What happened**: 
using the customHTAccessCM options does not work.

results in: `kubectl describe pod <POD_NAME>`

> Message:      OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/395bb3dd-3f99-11e9-8466-4a47a908bf31/volume-subpaths/custom-htaccess/wordpress/3\\\" to rootfs \\\"/var/lib/docker/overlay2/dd531cf4af6c76db72bc9285ac4c30160c36c736b8fef1830a206c967d799978/merged\\\" at \\\"/var/lib/docker/overlay2/dd531cf4af6c76db72bc9285ac4c30160c36c736b8fef1830a206c967d799978/merged/opt/bitnami/wordpress\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
>       Exit Code:    127

**What you expected to happen**: no such error? :-) It seems like an attempt is made to mount this file as a directory

This is what is shown under the pod mounts:
> /opt/bitnami/wordpress from custom-htaccess (rw)

**How to reproduce it** (as minimally and precisely as possible):

`kubectl create cm custom-htaccess --from-file=/path/to/wordpress-htaccess.conf`

`helm install stable/wordpress --set allowOverrideNone=yes --set customHTAccessCM=custom-htaccess`

**Anything else we need to know**:

**Comment by juan131** [comment]
Hi @chrisovergaauw 

I'm able to reproduce the issue. Thanks so much for reporting it. 

Working on a PR to fix it, I'll keep you updated!

**Comment by juan131** [comment]
Hi @chrisovergaauw 

Could you please give it a try using the latest Helm Chart? Please ensure you also pull the latest `bitnami/wordpress` image.

**Comment by jorgv** [comment]
I can confirm the bug still there even with the last versions of wordpress and chart

**Comment by Hydanium** [comment]
Bug is still present, even when using the latest Helm Chart and `bitnami/wordpress`

**Comment by joxper** [comment]
@juan131 could you take a look into this issue? can we reopen the issue?

**Comment by juan131** [comment]
Hi everyone,

We just merged a PR addressing this issue. Could you give a try to the latest chart version and provide feedback? Thanks in advance.

**Comment by joxper** [comment]
Thanks so much! @juan131 it works perfectly, tested with stable repo.

**Comment by juan131** [comment]
Great! I'm glad to hear that @joxper

**Comment by hmeerlo** [comment]
@juan131 Sorry, but I don't get it. Your PR has moved the wordpress-htaccess.conf file to a completely different location (/htaccess), it appears it is not used anymore now. At least I can't find a reference to it.
