### ISSUE TITLE
How to use extraEnv, extraVolumes and extraVolumeMounts

### ISSUE THREAD

**Issue by anareddy** [helm/charts#11981]
# to add extra environment variables
        env:
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 8 }}
{{- end }}

# to add extra volumes and mount paths.

        volumeMounts:

{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{- end }}

       volumes:
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
{{- end }}

++++in values.yaml file, how to insert environment variables, volumes, mount paths.
extraEnv:
  - name: URL
    value: "https://sample:80/admin"
extraVolumes:
  - name: ext-pvc
    persistentVolumeClaim:
      claimName: ext-pvc
extraVolumeMounts:
  - name: ext-pvc
    mountPath: /opt/config
    readOnly: true

**Comment by anareddy** [comment]
Hi Team,

The above one is not an issue, it is just documentation/ usage snippet of extraEnv, extraVolumes and extraVolumeMounts, might help others.

Thanks,
Ananda Reddy C.

**Comment by jgato** [comment]
Sorry, I neither understand how to use the extraVolumes and extraVolumeMounts. In my case, I would like to use it with elasticsearch helm. I would like to provide a /backup mount point with VolumeClaim of my default storage class.
