### ISSUE TITLE
[stable/postgresql] helm install --set persistence.storageClass=nfs-client doesn't work

### ISSUE THREAD

**Issue by soapergem** [helm/charts#11988]
**Is this a request for help?**:

Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Either it's a bug, or I'm just doing something wrong

**Version of Helm and Kubernetes**:
Helm v2.13.0
Kubernetes v1.13.4

**Which chart**:
stable/nfs-client-provisioner
stable/postgresql

**What happened**:

I first installed stable/nfs-client-provisioner to utilize my local NAS server for PersistentVolumes, using this command:

```
helm install --name nfs-provisioner --set nfs.server=192.168.1.175 --set nfs.path=/data/Kubernetes --set storageClass.defaultClass=true stable/nfs-client-provisioner
```

Then I tried to install Postgres using this command:

```
helm install --name postgres --set persistence.storageClass=nfs-client stable/postgresql
```

This then returns a `STATUS: DEPLOYED` saying `Please be patient while the chart is being deployed` however it never actually finishes.

**What you expected to happen**:

I would expect that when I type `kubectl get pods` I would see something like this:

```
NAME                     READY   STATUS
nfs-client-provisioner   1/1     Running
postgres-postgresql      1/1     Running
```

**What actually happens**:

Instead of seeing that, I see something like this:

```
NAME                     READY   STATUS
nfs-client-provisioner   1/1     Running
postgres-postgresql      0/1     Pending
```

It just stays on "Pending" forever. If I run `kubectl get events` I can see these two messages recurring:

```
REASON           KIND                    MESSAGE
FailedBinding    PersistentVolumeClaim   no persistent volumes available for this claim and no storage class is set
FailedScheduling Pod                     pod has unbound immediate PersistentVolumeClaims
```

**How to reproduce it** (as minimally and precisely as possible):

1. Have a local NAS server at 192.168.1.175 (or change the IP in step 3, below)
2. Set up a share on it at `/data/Kubernetes` and make sure it allows access to Kubernetes
3. Run this command: `helm install --name nfs-provisioner --set nfs.server=192.168.1.175 --set nfs.path=/data/Kubernetes --set storageClass.defaultClass=true stable/nfs-client-provisioner`
4. Run this command: `helm install --name postgres --set persistence.storageClass=nfs-client stable/postgresql`

**Anything else we need to know**:

I was surprised to see the error in the logs say "no storage class is set" since I can verify that the stable/nfs-client-provisioner chart did, indeed, set the default storage class. And moreover I'm specifying the storage class explicitly to the stable/postgresql chart. Any ideas why this isn't working?

Please note that my knowledge of Kubernetes is still pretty amateurish, so if you need me to get logs or do something else, please include the exact `kubectl` command you'd like me to run. I will gladly provide any additional detail.

**Comment by juan131** [comment]
I was unable to reproduce the issue. These are the steps I followed:

- Ensure my cluster has NFS packages installed (run this on every node): 

```bash
$ sudo apt-get install nfs-common
```

- Install the NFS provider:

```bash
$ helm install --name nfs-server-provisioner stable/nfs-server-provisioner --set persistence.enabled=true,persistence.size=10Gi
```

- Install PostgreSQL using NFS PVCs:

```
$ helm install --name postgres stable/postgresql --set persistence.storageClass=nfs --set persistence.accessMode=ReadWriteMany --set persistence.size=2Gi
```

As you can check the pods are running with a RWX PV mounted:

```
$ kubectl get pods
NAME                       READY   STATUS    RESTARTS   AGE
nfs-server-provisioner-0   1/1     Running   0          3m57s
postgres-postgresql-0      1/1     Running   0          3m10s
$ kubectl describe pod postgres-postgresql-0
...
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-postgres-postgresql-0
    ReadOnly:   false
...
$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                   STORAGECLASS   REASON   AGE
pvc-90dc8dc8-4630-11e9-988a-080027921c48   2Gi        RWO            Delete           Bound    default/data-postgres-postgresql-0      nfs                     3m50s
```

**Comment by soapergem** [comment]
Based on your comment here I was able to get it working. I think the problem was that I had omitted specifying the `persistence.size` variables on both charts when I was launching them. Now that I've included them both charts are working together harmoniously. Thank you!

**Comment by juan131** [comment]
Great @soapergem !!
I'm glad you were able to setup everything once you specified the `persistence.size`!!
