### ISSUE TITLE
[stable/consul] change configuration (enable ACLs)?

### ISSUE THREAD

**Issue by mitom** [helm/charts#1198]
**Is this a request for help?**: Yes/Maybe

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

I would like to be able to enable and configure ACLs on the cluster. I found no indication of how to achieve that. The default behaviour of Consul is to run without ACLs. I'd like for a master token to be generated and potentially stored in a secret in kubernetes when the cluster bootstraps if ACLs are enabled for the cluster.

**Version of Helm and Kubernetes**:
Helm version:
```
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
```
Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:07Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/consul

**What happened**:
ACLs can't be enabled.

**What you expected to happen**:
Configuration option to enable ACLs in the cluster.

**How to reproduce it** (as minimally and precisely as possible):
Deploy the chart
Open the UI
Try to access the ACL tab

**Comment by lachie83** [comment]
@mitom I'd be happy to do this. Can you confirm the flags that need to enable ACLs?

**Comment by mitom** [comment]
@lachie83 The basic configuration is explained on [consul's page](https://www.consul.io/docs/guides/acl.html#enabling-acls)

The very minimum to set it up is to provide `acl_datacenter`, there can only be one authoritative DC even when consul is set up cross-dc. I don't think this would cause any issues here, we can just set it to be `dc0` (the default value for dc for consul clusters that don't specify any).

The slightly more annoying part is setting the master token (`acl_master_token`). This can be any value (consul uses UUIDs as tokens, the master doesn't *have* to be one, but it would be convenient for consistency), but should be reasonable complex (as in long) since it will essentially have admin privileges. All of the servers need to have access to it, and when it changes the configuration needs to be reloaded on all the servers and the current leader needs to restart (to force a new leader-election). I imagine we could just create a new deployment and throw away the old containers which would satisfy this.

This also needs to be available to the user at least once, to use the ACL part of the interface one needs to specify a token. Since at the beginning there is only this master token and an anonymous one with no privileges to access that part, this is required to create more tokens (same applies to managing tokens through any other interface, this master token is needed to bootstrap the cluster properly).

The thing is, there are a lot more configuration options (not just about ACLs but in general) - maybe it would be worth to solve this via allowing to load in extra configuration files in some way?

Consul supports providing a directory for configurations via `-config-dir` in which it will load all `.json` files in alphabetical order (later overrides earlier). The position of specifying `-config-dir` and `-config-file` matters as well, as in the case of 
```
consul agent -config-dir /opt/consul/config -config-file /example.json
```
`example.json` will override the configs in `/opt/consul/config`
while in the case of 
```
consul agent -config-file /example.json -config-dir /opt/consul/config
```
the opposite is true.

Generally speaking, this would be easily solvable by allowing a list of `confimaps` to be passed, mounting them in a directory and then loading that directory *before* loading the generated things, like the gossip key config. The shortcoming of this is that the `acl_master_token` is highly sensitive data, so just taking it from a `configmap` is not really a way to go. There are also some other tokens  similar to it related to acls (they are all optional to set up, but there are use cases):
- [acl_agent_master_token](https://www.consul.io/docs/agent/options.html#acl_agent_master_token) - used when the authoritive DC is not available, should not matter for us since there is only 1 DC. Should only be used during outages.
- [acl_agent_token](https://www.consul.io/docs/agent/options.html#acl_agent_token) - used for internal cluster operations, defaults to `acl_token`
- [acl_token](https://www.consul.io/docs/agent/options.html#acl_token) - used for client requests
- [acl_replication_token](https://www.consul.io/docs/agent/options.html#acl_token) - used for ACL replication to other DCs, should not matter for us as there is only 1 DC.

These all range in terms of sensitivity but some - by definition - require high privileges. They are also meant to be set up by the cluster administrator once ACLs have been bootstrapped, but their values would need to be passed to the servers in some form of configuration. And there are also non-sensitive information, like acl TTLs and such.

Essentially, there should be a way to provide both sensitive and non-sensitive configuration. My best idea is to provide the ability to 
1. Set a list of `configmap`s in helm which will be mounted as files (say `/opt/consul/config` as an example)
2. Set a list of `secret`s in helm which will be mounted in the same folder as the configs.

In this scenario, someone could create `configmap`s named like `00_cluster_config` (.json..? I'm not sure what's the better practice there) which could be mounted as `/opt/consul/config/00_cluster_config.json` that contain general config, like ACL ttls and such and then a `secret` named `99_cluster_secret_config` (.json..? once again, not sure what's better in k8s naming terms). In this case the 2 configs would complement each other. It would also be possible to do things like specifying the different tokens in different `secret`s to control who can view what in k8s.

That's of course just an idea and would need to be tested, but that's what I could come up with to support all the configuration best and would stay relatively light in terms of the chart.

Let me know what you think!

**Comment by lachie83** [comment]
@mitom this is great thanks! Obviously happy to review a PR if you manage to get to this before me. I don't have many free cycles currently.

**Comment by mitom** [comment]
@lachie83 submitted a PR, there is 1 annoying thing in it with --set, see the PR for a explanation. Let me know what you think!
