### ISSUE TITLE
Locust custom tasks file at deploytime

### ISSUE THREAD

**Issue by juanmatias** [helm/charts#11992]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:
Using this:

```
↪ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```

```
↪ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Which chart**:
stable/locust

**What happened**:
I needed to add custom tasks to locust and I couldn't since the chart get the file already embedded in the image. 

**What you expected to happen**:
Chart should allow to specify a custom file.

**Anything else we need to know**:

I modified the chart to allow insert in values.yaml a code to set the tasks file content into a configmap that is then mounted into /locust-tasks dir. This way I can set a custom python file to specify all my tasks.

I'd like to give my improvements to the charts project but I don't know how to do it. Please, give me some advice on this. 
Thanks.

**Comment by nicwest** [comment]
Just hit the same issue, in it's present state I don't see how this chart would be useful to anyone beyond example code.

**Comment by juanmatias** [comment]
Just for the record: I modified this chart so you can edit tasks on deploy time without the need of image rebuild. 

Here it is: https://github.com/juanmatias/locust-chart/blob/master/README.md
