### ISSUE TITLE
stable/grafana ldap externalSecret not working

### ISSUE THREAD

**Issue by Superset1986** [helm/charts#12000]
**Is this a request for help?**:
 Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Version of Helm and Kubernetes**:
Helm: 2.9.1 
Kubernetes:  1.12.5 

**Which chart**:
Grafana stable

**What happened**:
Nothing happens when i set ldap existingSecret in the values file , also tried with --set ldap.existingSecret=ldap-toml  without luck.

**What you expected to happen**:
I expected my existing secret in kubernettes would be used to overwrite the default config in /etc/grafana/ldap.toml

**How to reproduce it** (as minimally and precisely as possible):
add the following lines to values.yaml and deploy the chart using this file: 

grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  auth.ldap:
    enabled: true
    allow_sign_up: true
    config_file: /etc/grafana/ldap.toml
  auth.anonymous:
    enabled: true
    org_name: Main Org.

ldap:

  existingSecret: "ldap-toml"

**Anything else we need to know**:

kubernetes secret for ldap:
Name:         ldap-toml
Namespace:    ritmon
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
ldap-toml:  789 bytes

**Comment by maorfr** [comment]
Just to make sure - you are installing the chart and the existing secret in the same namespace, right?

**Comment by skaarup1986** [comment]
> Just to make sure - you are installing the chart and the existing secret in the same namespace, right?

Yes this is correct.     I'm using existing secret for username and password and this is working fine.

**Comment by chs-bnet** [comment]
I'm having this exact same issue and it's troubling that no one ever responded to this and it was closed automatically.

My secret is named correctly, the contents are correct, and I'm using other secrets elsewhere in this same chart and other charts without any issues. It looks like there might be something wrong specifically with this chart and how it gets the `ldap.existingSecret`.

**Comment by maorfr** [comment]
Would you be interested in submitting a PR for this?

**Comment by guru-cool** [comment]
I wasted about 6 hours before I stumbled upon this !

**Comment by pedrojimenez** [comment]
@guru-cool ... Thanks for your time investment !!

We had a similar problem when migrating from BasciAuth to Ldap ... 

We were not removing the basic auth config block (from env vars) and the ldap file from Secret was not being generated
```diff
-env:
-  GF_AUTH_BASIC_ENABLED: "false"
-  GF_AUTH_ANONYMOUS_ENABLED: "true"
-  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
+# env:
+#   GF_AUTH_BASIC_ENABLED: "false"
+#   GF_AUTH_ANONYMOUS_ENABLED: "false"
+#   GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
```

**Comment by cnukwas** [comment]
> I want to always make sure I have a local admin user, so I just commented out `admin.existingSecret` AND `adminUser/adminPassword` and inject the `GF_SECURITY_ADMIN_USER=admin`, and `GF_SECURITY_ADMIN_PASSWORD=password` environment variables imported via `envFromSecret`.
> 

I know it's an old thread. Working this now and want to make sure that I am doing it right. If I understand it right, I need to create a secret with GF_SECURITY_ADMIN_USER and GF_SECURITY_ADMIN_PASSWORD as keys and set that secret name in for envFromSecret in the values.yaml, to use custom secret credentials for the admin id and still be able to use LDAP set up, is that right?
