### ISSUE TITLE
[stable/elasticsearch] EXPECTED_MASTER_NODES 

### ISSUE THREAD

**Issue by zakariahoussa** [helm/charts#12002]
**Is this a request for help?**: No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

BUG REPORT: None of the documentation or file values talks about the existence of the variable EXPECTED_MASTER_NODES  , so in case you want to set up just one master , the cluster will not work because the "gateway.expected_master_nodes" will be set to 2 , in case you dont know those variable and you will end up debuging for long to know that.

i think the EXPECTED_MASTER_NODES should be set to MINIMUM_MASTER_NODES if it isnt set 

=> gateway.expected_master_nodes: ${EXPECTED_MASTER_NODES:2}
to
 gateway.expected_master_nodes: ${EXPECTED_MASTER_NODES:MINIMUM_MASTER_NODES }

and add **documentation** about EXPECTED_MASTER_NODES  

**Version of Helm and Kubernetes** :any

**Which chart**:
elastic-search

**What happened**: cluster not working

**What you expected to happen**:

At least to follow the number of minimum_master_nodes

**How to reproduce it** (as minimally and precisely as possible):

Run cluster with one master or data

**Anything else we need to know**:

**Comment by chicken231** [comment]
I've run into this as well, when trying to run a 1 master cluster in a dev environment.

This looks to be where it's set: https://github.com/helm/charts/blob/fc77fdac89282c7b56790456308b8bbadcc7fabb/stable/elasticsearch/templates/configmap.yaml#L85

At a glance, I would think that defining these two environment variables together would work?

```
cluster:
  env:
    MINIMUM_MASTER_NODES: "3"
    EXPECTED_MASTER_NODES: "3"
```
