### ISSUE TITLE
chartmuseum ingress is failing 

### ISSUE THREAD

**Issue by fattahantar** [helm/charts#12006]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes: v1.12.5
helm version: v2.13.0

**Which chart**:
chartmuseum

**What happened**:
Configuring ingress is not working as expected.

**What you expected to happen**:
ingress should be created.

**How to reproduce it** (as minimally and precisely as possible):
I'm using this file chartmuseumCustom.yaml
image:
  tag: 'v0.8.2'
env:
  secret:
    BASIC_AUTH_USER: admin
    BASIC_AUTH_PASS: admin
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: "custom-vol"
  size: 8Gi
service:
  externalPort: 8080
ingress:
  ## Set to true to enable ingress record generation
  enabled: true
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  hosts:
  - name: chartmuseum.example.io
    path: /

when I run the dry-run as the normal installation is failing

helm install --dry-run --debug --name chartmuseum -f chartmuseumCustom.yaml --namespace charts-ns stable/chartmuseum

I'm  getting this output

# Source: chartmuseum/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chartmuseum-chartmuseum
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing

  labels:
    app: chartmuseum
    chart: chartmuseum-1.9.2
    heritage: "Tiller"
    release: "chartmuseum"
spec:
  rules:
  - host: 0
    http:
      paths:
      - path: chartmuseum.example.io
        backend:
          serviceName: chartmuseum-chartmuseum
          servicePort: 8080
      - path: /
        backend:
          serviceName: chartmuseum-chartmuseum
          servicePort: 8080

**Anything else we need to know**:

**Comment by SweetOps** [comment]
Hey @abdoo , I guess, should be 

```yml

name: chartmuseum.example.io
path: 
  - /
```
