### ISSUE TITLE
[stable/traefik] storeconfig job is not removed when release is deleted

### ISSUE THREAD

**Issue by phroggyy** [helm/charts#12019]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
Helm 2.12.3
Kubernetes Client 1.13.0
Kubernetes Server 1.12.5-gke.5

**Which chart**:
stable/traefik

**What happened**:
When running `helm del --purge my-release`, the `storeconfig` jobs remained. When subsequently running `helm upgrade`, it failed, as the jobs were still present, and a new job could not be created with the name.

**What you expected to happen**:
I expected the storeconfig jobs to be removed as part of `helm delete`

**How to reproduce it** (as minimally and precisely as possible):
```
helm install stable/traefik --name my-release --set kvprovider.consul.endpoint="consul:8500",kvprovider.consul.prefix=traefik
helm delete --purge my-release
helm install stable/traefik --name my-release --set kvprovider.consul.endpoint="consul:8500",kvprovider.consul.prefix=traefik
```

**Anything else we need to know**:
This relates to, but is not the same as, #11766

**Comment by alwinmarkcf** [comment]
This is a a Problem of Helm itself. Resources created by Hooks are not managed by Helm, so also not removed after purging the Chart.

Same applies to CRDs created by a Chart. In order to remove the Chart completely you have to:

```
helm delete --purge my-release
kubectl delete all -l app=traefik
```

Another way to work around this would be removing the Job on success which without further research should work.

**Comment by phroggyy** [comment]
@alwinmarkcf indeed, removing it upon success works. However, another way to approach it would be to have a single job that's part of the template, rather than hook-controlled. The downside of that is that you would only ever have the logs of the most recent job available, but it would mean that the job would get removed when deleting the release.
