### ISSUE TITLE
[stable/jenkins] not installing [BUG]

### ISSUE THREAD

**Issue by vasiliyb** [helm/charts#12045]
**Version of Helm and Kubernetes**:
k8s : `1.12.5-gke.10`
latest helm from brew

**Which chart**:
helm install --name jenkins stable/jenkins

**What happened**:
```
helm install --name jenkins stable/jenkins
```

```
Error: parse error in "jenkins/templates/jenkins-master-deployment.yaml": template: jenkins/templates/jenkins-master-deployment.yaml:47: function "nindent" not defined
```

**What you expected to happen**:
Jenkins helm chart to be installed

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by maorfr** [comment]
what is your helm version?
