### ISSUE TITLE
Is there a new version of Chart with latest spinnaker version?

### ISSUE THREAD

**Issue by saisantoshi76** [helm/charts#12044]
The current version of Chart which is using the spinnaker version 1.11.6 does not seems to be compatible with the docs. 
https://www.spinnaker.io/guides/tutorials/codelabs/kubernetes-v2-source-to-prod/#configure-spinnaker

When we create the staging-demo and prod-demo, those accounts are not visible in the UI after doing the "hal deploy apply". The deployment went fine but it is only showing the default account.

**Comment by florianrusch** [comment]
@saisantoshi76 the version was bumped 2 days ago. have a look here: b8eb432e0b54da92d86ca3eab4189e48e3e7d8fd
