### ISSUE TITLE
[stable/mysql] add support for affinity

### ISSUE THREAD

**Issue by sfitts** [helm/charts#12054]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature Request

**Version of Helm and Kubernetes**:

Kubernetes -- 1.11.5
Helm -- 2.11

**Which chart**:

stable/mysql

**What you expected to happen**:

It would be nice to be able to set the affinity clause of the deployment to help influence pod placement.  Currently this is not supported by the template.

**Comment by tf** [comment]
This would be nice. `stable/mariadb` supports this for example.

**Comment by nielsn** [comment]
Bumped into this today as well. I'm able and willing to implement this!
