### ISSUE TITLE
[stable/jenkins] Configuration not being applied

### ISSUE THREAD

**Issue by domcar** [helm/charts#12058]
**Is this a BUG REPORT or FEATURE REQUEST?** :
BUG REPORT

**Which chart**:
stable/jenkins 0.33.0

**What happened**:
Configuration not being applied

**What you expected to happen**:
New configuration to be applied

**How to reproduce it** (as minimally and precisely as possible):
The value `UseSecurity: false` is not being applied by init-container:

The first time I installed Jenkins I set the value to ´true´ and it was correctly set, in a second time I needed to set it to false but the init container wasn't able to apply the new config, the values was always `true`. I found out that the apply script `/var/jenkins_config/apply_config.sh` contains 
```
yes n | cp -i /var/jenkins_config/config.xml /var/jenkins_home;
yes n | cp -i /var/jenkins_config/jenkins.CLI.xml /var/jenkins_home;
yes n | cp -i /var/jenkins_config/jenkins.model.JenkinsLocationConfiguration.xml /var/jenkins_home;
```

this works if I run it manually (I modified init to sleep as command and then run it) but it does not work when run by init because the `cp -i` asks for confirmation even if there is `yes n`.

**Anything else we need to know**:
Personally I find this is an important bug when activating an external authentication mechanism e.g. gitlab oauth because the risk to be locked out is high and only with `UseSecurity: false` is possible to go back.
Thanks for your help

**Comment by maorfr** [comment]
`yes n | cp -i ...` - cp asks for confirmation and gets it. it gets a `n`, so it will not change anything after the first install.

I think you can use `.Values.Master.OverwriteConfig` to get passed that:
https://github.com/helm/charts/blob/master/stable/jenkins/templates/config.yaml#L224
