### ISSUE TITLE
[stable/concourse] Vault missing role_id

### ISSUE THREAD

**Issue by demamoh** [helm/charts#12053]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): potential bug

**Version of Helm and Kubernetes**:
helm: **v2.12.1**
kubernetes: **1.11**

**Which chart**:
from **3.0.1** to **4.0.0**

**What happened**:
Getting this error in the logs `URL: PUT http://vault:8200/v1/auth/approle/login\nCode: 400. Errors:\n\n* missing role_id","name":"vault","session":"8.4"}}`

**What you expected to happen**:

Expected login success on vault

**How to reproduce it** (as minimally and precisely as possible):
use:
 - authbackend `approle`
- vaultAuthParam = "role_id=example,secret_id=example"

**Anything else we need to know**:

**Comment by demamoh** [comment]
Looked through the source code.  Instead of `=` it has changed to `:` this is not updated in the site documentation.

**Comment by demamoh** [comment]
Digging through the code, I found that instead of `role_id=` the `=` should be replaced with `:`. The documentation currently doesn't mention this, which has made it a pain.

After doing that, I am now getting weird 403 errors and a weird url for vault get request which looks like this `%!C(MISSING)nil%!E(MISSING)`

**Comment by doughoke** [comment]
Documentation in Helm chart should be updated to match.  If you run 'docker run -t concourse/concourse web --help' it will list out 

          _--vault-auth-param=NAME:VALUE                                                      Paramter to pass when logging in via the backend. Can be specified multiple times.
                                                                                             [$CONCOURSE_VAULT_AUTH_PARAM]_

 Your 403 error might be a bad set up of Vault? your Values.yaml should have something like this...

vaultAuthParam: role_id:somehashfortherole,secret_id:someguidforthesecret

**Comment by cah-james-shingler** [comment]
Echoing Doug, ... we ran into it and switching from role_id=asdf to role_id:asdf worked

**Comment by jshingler** [comment]
PR #12197

**Comment by demamoh** [comment]
That change also worked. The other issue I ran into is fixed by setting up the vault pathPrefix, pre version 4.0 there was a good default set, that I had to manually add in. 

Thanks @doughoke  for the help, likewise @jshingler  thanks for the pr.

**Comment by cirocosta** [comment]
Hi @demamoh, thanks for filling the issue!

> The other issue I ran into is fixed by setting up the vault pathPrefix, pre version 4.0 there was a good default set, that I had to add in manually

Do you mean [this change](https://github.com/helm/charts/commit/bfd68b131a47682f1c69f61fb9b3ec9ee64d5fe8#diff-95cc28250f44d26990fee96ad2fbd63dL178)?

```diff
-      pathPrefix: /concourse
+      pathPrefix:
```

It seems to be broken indeed! The idea for the commit that introduced that changes was to make more use of concourse's default values, e.g.:

```sh
concourse web --help 2>&1 | ag vault-path-prefix
          --vault-path-prefix=       Path under which to namespace credential lookup. 
                                     (default: /concourse) [$CONCOURSE_VAULT_PATH_PREFIX]
```

But given that the Vault params do not have `if`'s on them

https://github.com/helm/charts/blob/5c794e8261f1b58b9a8065fd18e7d29d1ea92667/stable/concourse/templates/web-deployment.yaml#L352-L357

the result ends up being environment variables with empty values:

```yaml
            - name: CONCOURSE_VAULT_URL
              value: 
            - name: CONCOURSE_VAULT_PATH_PREFIX
              value: 
            - name: CONCOURSE_VAULT_AUTH_BACKEND
              value: ""
```

**Comment by cirocosta** [comment]
To ensure problems like this don't end up happening again, we'll be introducing few cross-compatibility end to end tests, e.g.: https://github.com/concourse/concourse/issues/3109 (for Vault).

**Comment by demamoh** [comment]
@cirocosta Thanks for background, those tests will definitely be helpful. Much appreciated.

**Comment by demamoh** [comment]
Also, you correct that is the path prefix I was referring to.

**Comment by cirocosta** [comment]
No problem! I just created a separate issue (https://github.com/helm/charts/issues/12221) to make sure we fix those cases where we previously had default values and now empty values prevent `concourse` from using its defaults.

Thank you!
