### ISSUE TITLE
Mongodb - Can't connect to server from other services

### ISSUE THREAD

**Issue by txbrown** [helm/charts#12090]
**Is this a request for help?**:
Yes

**Version of Helm and Kubernetes**:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
`stable/mongodb`

**What happened**:
My services cannot conenct to the mongo instances on mongo `mongo-mongodb.default.svc.cluster.local` and when I `kubectl exec` into one of the pods I have to run first `rs.slaveOk()` and then it won't allow me to run any queries and throws error 

```
Error: error: {
        "operationTime" : Timestamp(1552021460, 1),
        "ok" : 0,
        "errmsg" : "node is not in primary or recovering state",
        "code" : 13436,
        "codeName" : "NotMasterOrSecondary",
        "$clusterTime" : {
                "clusterTime" : Timestamp(1552021460, 1),
                "signature" : {
                        "hash" : BinData(0,"XfJCVFxzjxOx8pb/k8t6aE4CiWE="),
                        "keyId" : NumberLong("6664334391939956738")
                }
        }
}
```

**What you expected to happen**:

I am a beginner at this.

**How to reproduce it** (as minimally and precisely as possible):
Install helm chart with ```--name mongo....``` and try to connect to` mongo-mongodb.default.svc.cluster.local`

**Anything else we need to know**:

I am a beginner with kubernetes and I am trying to get mongo running in my cluster. All my other services are working apart from mongo which for weeks now has been having inconsistent behaviour. Sometimes I can connect but most of times it just won't work.

**Comment by codenakama** [comment]
Somehow deleting all pvc(s) and helm delete on the release, then helm install again solves the issue. which is odd because I don't know now how the issue even started since I didn't touch the cluster for a week and all of a sudden my services couldn't connect to the replicaset anymore and I was having the issues mentioned above when running commands inside the mongo server.

**Comment by juan131** [comment]
Hi @codenakama 

It seems sth happened to MongoDB and it was in an inconsistent state. 

Do you have the logs from the MongoDB pods when you were unable to connect to them? We might get more information from them.
