### ISSUE TITLE
[stable/fluent-bit] indent 8 should be indent 4?

### ISSUE THREAD

**Issue by flands** [helm/charts#12106]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Version of Helm and Kubernetes**:

Helm = 2.13
K8s = 1.11.7

**Which chart**:

stable/fluent-bit latest

**What happened**:

Attempted to add extra input section. For example:

```
extraEntries:
  input: |
    [INPUT]
        Name             tail-syslog
        Path             /var/log/syslog.log
        Parser           tail-syslog
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
```

**What you expected to happen**:

Configured to work, but it did not as it was indented incorrectly:

```
  fluent-bit-input.conf: |-
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
        [INPUT]
            Name             tail-syslog
            Path             /var/log/syslog.log
            Parser           tail-syslog
            Refresh_Interval 5
            Mem_Buf_Limit    5MB
            Skip_Long_Lines  On
```

**How to reproduce it** (as minimally and precisely as possible):

See above -- to note the indent 8 can be seen in multiple places in the config template.

**Anything else we need to know**:

**Comment by sirrapa** [comment]
Any update on this?

**Comment by flands** [comment]
I submitted a PR -- let's see

**Comment by kfox1111** [comment]
Sorry, I somehow didn't see this or the pr until after iit merged. This is an intentional design choice, not a bug.

You can use rawConfig to add any extra sections you want with the existing chart.

**Comment by ntroast** [comment]
@kfox1111 Many of us don't understand why extraEntries exists. For example in parsers.conf why would you allow extraEntries for the json parser, but not extraEntries for the regex parser? IMO extraEntries should either be removed, or added to all sections.
