### ISSUE TITLE
[stable/prometheus-operator] Specify readiness/liveness values for prometheus

### ISSUE THREAD

**Issue by candidoma** [helm/charts#12117]
**What did you do?**
Change Readiness/Liveness config for prometheus

**What did you expect to see?**
Define values override readiness/liveness into values.yaml file.

**What did you see instead? Under which circumstances?**
No values are available and prometheus use default values for both config.

**Comment by vsliouniaev** [comment]
These values are set by the prometheus operator project and cannot be changed. If you're interested in this functionality I suggest you open an issue against the project repository.
https://github.com/coreos/prometheus-operator
