### ISSUE TITLE
[stable/jenkins] OwnSshKey setting does not actually allow for specifying your own key

### ISSUE THREAD

**Issue by kashook** [helm/charts#12140]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:  helm 2.11.0, kubernetes v1.11.8-eks-7c34c0 (but irrelevant to this issue)

**Which chart**: stable/jenkins

**What happened**:
The jenkins chart has the `.Values.Master.OwnSshKey` setting, described [here](https://github.com/helm/charts/blob/8e4282c9c05bf246c655a499efc00b35db3f7472/stable/jenkins/values.yaml#L37:L41).  According to that, you are supposed to be able to supply your own key.  However, this does not appear to actually be possible. First, note that when setting `.Values.Master.OwnSshKey` to true, the value for the ssh key is no longer generated into the secret (see [here](https://github.com/helm/charts/blob/8e4282c9c05bf246c655a499efc00b35db3f7472/stable/jenkins/templates/secret.yaml#L19:L21)).

The deployment, however, provides no way to actually specify the secret it should get the value from instead.  See:

* https://github.com/helm/charts/blob/8e4282c9c05bf246c655a499efc00b35db3f7472/stable/jenkins/templates/jenkins-master-deployment.yaml#L92:L100
* https://github.com/helm/charts/blob/8e4282c9c05bf246c655a499efc00b35db3f7472/stable/jenkins/templates/jenkins-master-deployment.yaml#L168:L176
* https://github.com/helm/charts/blob/8e4282c9c05bf246c655a499efc00b35db3f7472/stable/jenkins/templates/jenkins-master-deployment.yaml#L298:L306

The secret referred to in these blocks is produced by [templates/secret.yaml](https://github.com/helm/charts/blob/8e4282c9c05bf246c655a499efc00b35db3f7472/stable/jenkins/values.yaml#L37:L41), which will no longer have the referenced `jenkins-admin-private-key` when `OwnSshKey` is `true`.

The placement of the `OwnSshKey` check also seems wrong to me.  If configAutoReload and JCasC are enabled, then `ADMIN_PRIVATE_KEY` environment variable is required, whether you are using your own key or not.  To me it seems like it should be checked inside of the `secretKeyRef` section as part of deciding whether to use the built-in secret or allowing for a custom secret supplied by the user.

**What you expected to happen**:
Provide a way to specify the name of the secret that the jenkins admin ssh key should be obtained from

**How to reproduce it** (as minimally and precisely as possible):
Set `.Values.Master.OwnSshKey` to true and `.Values.Master.JCasC.enabled` to true, and then try to specify your own SSH key.

**Comment by maorfr** [comment]
Maybe @holmesb or @torstenwalter can help?

**Comment by holmesb** [comment]
@kashook , OwnSshKey is working fine for me.  The logic is, if true, you are expected to manually add your own ssh (RSA) private key to the secret that has the name of the jenkins release.  I've just spun-up a release called jenkins-test2, then added my own private key using:
```kubectl create secret generic jenkins-test2 --dry-run --from-file=jenkins-admin-private-key=/home/brendan/.ssh/id_rsa -o yaml | kubectl apply -f -``` 
(per the guidance in values.yaml)

Then I enabled OwnSshKey, Master.JCasC.enabled and Sidecars.configAutoReload.enabled, ran helm upgrade --install again and the sidecar is successfully authenticating and reloading casc config in Jenkins.

**Comment by kashook** [comment]
@maorfr @holmesb thanks for the reply!

Ideally, I'd like to not have to edit a resource that is managed by helm outside of helm (in this case the secret that contains the key which is created by the jenkins chart).  I've run into problems with that in the past.  Here are some examples of stuff out there that talks about it being problematic (in addition to my own experience):

- https://github.com/helm/helm/issues/2070
- https://github.com/helm/helm/issues/1844#issuecomment-274112471
- https://github.com/helm/helm/issues/1844#issuecomment-274042885

In addition, our entire stack of tools are deployed and managed by helm.  My preference would be to deploy everything with helm and not also have to run extra `kubectl` commands.

What would you think about a modification to the chart to treat the admin key the same way as the admin password?  If a key is specified (not blank) then use that, otherwise generate one?  The places in the chart that check the `OwnSshKey` (which is a boolean) could instead just check if the given key is blank.  I'd be happy to submit a PR.

**Comment by holmesb** [comment]
> "My preference would be to deploy everything with helm and not also have to run extra kubectl commands"

I couldn't agree more.  I didn't include in the helm chart for two reasons:

1)  Most people store values.yaml in source.  Storing a private key in source is generally a bad idea.  
2)  Using our own private key is non-essential for us.  We didn't need it enough to put the extra work in.

We use a secrets management system, so can mitigate 1).  If you need this enough to add via a PR, it's an improvement that will be greatly appreciated.  I'd only suggest that due to 1), the default for OwnSshKey should be blank \ commented-out as per AdminPassword, and that you advise people not to store secrets in SCM.

**Comment by kashook** [comment]
@holmesb Thanks!  I will work on a PR.  I definitely agree about not storing the plain secret values in source control.  We keep our secret values in separate files that are encrypted with [mozilla sops](https://github.com/mozilla/sops).
