### ISSUE TITLE
[stable/rabbitmq-ha] not working in HA mode with istio 1.03/1.05 permissive

### ISSUE THREAD

**Issue by ghost** [helm/charts#12143]
this a request for help :)

**Version of Helm and Kubernetes**:
Helm version v2.13.0
Kubernetes version v1.11.7-gke.4

**Which chart**:
rabbitmq-ha chart
istio 1.03/1.05

**What happened**:
When installing managed istio in gcp (version 1.03 from what i can see with mtls PERMISSIVE) rabbitmq-ha stopped discovering all the nodes and stopped working in HA mode each node now stands solo.
I also tried this with istio helm chart version 1.05 with mtls enabled (1.06 is broken from what i've been told by google staff) and this also happens.

**What you expected to happen**:
rabbitmq-ha discovery keeps on working

**How to reproduce it** (as minimally and precisely as possible):
k8s gcp cluster with istio (permissive) (checkbox when creating a cluster in UI).
install rabbitmq-ha chart with 3 replicas with persistent volume.
see management to check if all 3 nodes are discovered.

**Anything else we need to know**:
i tried excluding the ports from istio with a policy as per a suggestion i found online.
my app that connects to the rabbit does reach the service and can communicate with it properly 
but queues are now distributed across all 3 nodes instead of being cloned on each node and working in HA mode.

apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: disable-mtls-test-gke-rabbitmq-ha
  namespace: default
spec:
  targets:
  - name: test-gke-rabbitmq-ha
    ports:
    - number: 4369
  - name: test-gke-rabbitmq-ha
    ports:
    - number: 25672
  - name: test-gke-rabbitmq-ha
    ports:
    - number: 5672
  - name: test-gke-rabbitmq-ha
    ports:
    - number: 15672
    peers:

i do not see any errors are attempts of node discovery from rabbitmq-ha.
when installing chart in namespace with no istio everything is working properly and nodes are discovered .

Thanks for the help

**Comment by steven-sheehy** [comment]
Since it works without Istio, this is more of a question on how to configure Istio. You should direct such questions to Istio support channels. All I can tell you is in order for rabbitmq to properly cluster it needs DNS of the service to resolve and it needs the epmd port (default 4369) to be reachable between the rabbitmq nodes.
