### ISSUE TITLE
[stable/concourse] 5.0.0 upgrade-worker pods error-/bin/sh: 3: concourse: not found

### ISSUE THREAD

**Issue by vijay-veeranki** [helm/charts#12168]
BUG REPORT

**Version of Helm and Kubernetes**:
Helm v2.12.2
Kubernetes 1.11.6

**Which chart**:
4.0.0

**What happened**:

Deployed concourse with new concourse image 5.0.0 and chart 4.0.0,  worker pod is keep on restarting with below error 

/bin/sh: 3: concourse: not found

**What you expected to happen**:

worker pods should not restart and don't give any error

**How to reproduce it** (as minimally and precisely as possible):

deploy 5.0.0 with chart 4.0.0

**Anything else we need to know**:

It is a new cluster was using 

old versions:

variable "concourse_image_tag" {
  default     = "4.2.2"
  description = "The docker image tag to use"
}

variable "concourse_chart_version" {
  default     = "3.5.1"
  description = "The Helm chart version"

As it is a new cluster destroyed every thing and deployed a new concourse using below

variable "concourse_image_tag" {
  default     = "5.0.0"
  description = "The docker image tag to use"
}

variable "concourse_chart_version" {
  default     = "4.0.0"
  description = "The Helm chart version"
}

**Comment by mprzygrodzki** [comment]
@vijay-veeranki-moj how did you resolve the issue ? Got the same behaviour after upgrading from 4.2.2.

**Comment by vijay-veeranki-moj** [comment]
used the latest values.yml file 
https://github.com/helm/charts/blob/master/stable/concourse/values.yaml

that fixed my issue
