### ISSUE TITLE
[stable/prometheus-adapter] No data in custom metrics API

### ISSUE THREAD

**Issue by Bulat-Gumerov** [helm/charts#12182]
Hi folks
Just deployed `prometheus-adapter` with helm: `helm install --name prometheus-adapter --set rbac.create=true,prometheus.url=http://prometheus-operator-prometheus.default.svc.cluster.local:9090,prometheus.port=9090 stable/prometheus-adapter`
but it can't  authenticate and fetch metrics from prometheus. http://prometheus-operator-prometheus.default.svc.cluster.local:9090 is my prometheus web ui that was also deployed previously using helm chart `stable/prometheus-operator`. Here is logs from `prometheus-adapter`:
[adapter.log](https://github.com/DirectXMan12/k8s-prometheus-adapter/files/2940243/adapter.log)
When I run `kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/ | jq`
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": []
}
$ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/main/pods/" --v=8
I0307 11:33:50.099558    2896 loader.go:359] Config loaded from file /Users/bulatgumerov/.kube/config
I0307 11:33:50.100283    2896 round_trippers.go:416] GET https://xxxxxx.yl4.ap-southeast-1.eks.amazonaws.com/apis/custom.metrics.k8s.io/v1beta1/namespaces/main/pods/
I0307 11:33:50.100297    2896 round_trippers.go:423] Request Headers:
I0307 11:33:50.100302    2896 round_trippers.go:426]     Accept: application/json, */*
I0307 11:33:50.100307    2896 round_trippers.go:426]     User-Agent: kubectl/v1.13.2 (darwin/amd64) kubernetes/cff46ab
I0307 11:33:51.441282    2896 round_trippers.go:441] Response Status: 404 Not Found in 1340 milliseconds
I0307 11:33:51.441362    2896 round_trippers.go:444] Response Headers:
I0307 11:33:51.441384    2896 round_trippers.go:447]     Audit-Id: 3fe98054-66f0-426a-8439-572149f106db
I0307 11:33:51.441398    2896 round_trippers.go:447]     Content-Type: application/json
I0307 11:33:51.441411    2896 round_trippers.go:447]     Date: Thu, 07 Mar 2019 08:33:51 GMT
I0307 11:33:51.441426    2896 round_trippers.go:447]     Content-Length: 159
I0307 11:33:51.441662    2896 request.go:942] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the metric  for pods","reason":"NotFound","code":404}
I0307 11:33:51.442519    2896 helpers.go:198] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the metric  for pods",
  "reason": "NotFound",
  "code": 404
}]
F0307 11:33:51.442554    2896 helpers.go:116] Error from server (NotFound): the server could not find the metric  for pods

**Comment by Towmeykaw** [comment]
In your logs it says Get http://prometheus-operator-prometheus.default.svc.cluster.local:9090:9090/api/v1/series?match%5B%5D=%7Bnamespace%21%3D%22%22%2C__name__%21~%22%5Econtainer_.%2A%22%7D&start=1551944936.556: invalid URL port "9090:9090".
You should not have the port number in prometheus.url value.
