### ISSUE TITLE
Value naming mismatch in README for 'rabbitmq.existingErlSecret'

### ISSUE THREAD

**Issue by frabe1579** [helm/charts#12208]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm v2.11.0
Kubernetes server v1.12.6
Kubernetes client: v1.13.3

**Which chart**:
stable/rabbitmq

**What happened**:
The passed value rabbitmq.existingErlangSecret is ignored and a new secret is created, but this fail because an existing secret is already created (with same name)

**What you expected to happen**:
The chart uses the existing secret without creating a new one.

**How to reproduce it** (as minimally and precisely as possible):
1. Create an existing secret: kubectl create secret generic test --from-literal=rabbitmq-password=somevalue --from-literal=rabbitmq-erlang-cookie=somevalue
2. Install che chart: helm install --set rabbitmq.existingPasswordSecret=test-rabbit --set rabbitmq.existingErlangSecret=test-rabbit

**Anything else we need to know**:
The origin of the problem seems to be the usage of two value names for the same data: in README.md the value is called "rabbitmq.existingErlSecret", but in templates is "rabbitmq.existingErlangSecret".

**Comment by tompizmor** [comment]
Hi @totalprogrammi,

I am not able to reproduce the issue. If I specify the secret containing the password and the erlangCookie, that is the only secret created by the chart (apart from the service-account one)

In any case, I have sent a PR to fix the typo in the README.
