### ISSUE TITLE
[stable/prometheus-operator] kubelet.serviceMonitor.cAdvisorMetricRelabelings doesn't work with https 

### ISSUE THREAD

**Issue by salamachinas** [helm/charts#12215]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
helm: 2.10.0
Client: 1.10.2
Server: 1.11.2

**Which chart**:
stable/prometheus-operator

**What happened**:
Unable apply cAdvisorMetricRelabelings on kubelet service monitor with https: True

**What you expected to happen**:
Configuration should by applied.

**How to reproduce it** (as minimally and precisely as possible):
* Chart config
```
{
  "kubelet": {
    "enabled": true,
    "namespace": "kube-system",
    "serviceMonitor": {
      "https": true,
      "cAdvisorMetricRelabelings": [
        {
          "sourceLabels": ["__name__", "image"],
          "separator": ";",
          "regex": "container_([a-z_]+);",
          "replacement": "$1",
          "action": "drop"
        },
        {
          "sourceLabels": ["__name__"],
          "separator": ";",
          "regex": "container_(network_tcp_usage_total|network_udp_usage_total|tasks_state|cpu_load_average_10s)",
          "replacement": "$1",
          "action": "drop"
        }
      ]
    }
  }
}
```
* Deploy chart:
```bash
helm install stable/prometheus-operator --name prometheus-operator --namespace prometheus-operator -f values.json
```
* Check kubelet service monitor
```bash
kubectl -n prometheus-operator get  servicemonitor/prometheus-operator-kubelet -o yaml
```
**Anything else we need to know**:
Configuration needed for memory safe purposes. More info https://github.com/coreos/prometheus-operator/pull/2387

**Comment by vsliouniaev** [comment]
Should now be working on version 5.0.0
