### ISSUE TITLE
[stable/mongodb-replicaset] How do I use the prometheus exporter when metrics.enabled is true

### ISSUE THREAD

**Issue by kwill4026** [helm/charts#12219]
**Is this a request for help?**: YES

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
NO

**Version of Helm and Kubernetes**: 
Helm version 2.12
Kubernetes: 1.11.5

**Which chart**:
mongodb-replicaset

**What happened**:
I have auth.enabled set to true, metrics.enabled set to true, and tls set to true. When I run the chart my statefulset produces the 3 pods successfully

NAME                                                        READY      STATUS        RESTARTS      AGE
pod/silly-goose-mongodb-replicaset-0    2/2            Running        0                    1h
pod/silly-goose-mongodb-replicaset-1    2/2            Running        0                    1h
pod/silly-goose-mongodb-replicaset-2    2/2            Running        0                    1h

NAME                                                              TYPE          CLUSTER-IP      EXTERNAL-IP    PORTS
service/silly-goose-mongodb-replicaset     ClusterIP     None                  None                 27017/TCP
service/silly-goose-mongodb-replicaset-client     ClusterIP     None         None       27017/TCP,9216/TCP

NAME                                                                         DESIRED     CURRENT            AGE
statefulset.apps/silly-goose-mongodb-replicaset          3                  3                   1h

kubectl  logs pod/silly-goose-mongodb-replicaset-0 -c mongodb-replicaset shows the mongodb connections are open and I am also able to exec into the container and connect securely to the database with no issues (mongo -u admin --authenticationDatabase admin --sslCAFile=/data/configdb/tls.crt --sslPEMKeyFile=/work-dir/mongodb.pem --ssl). However I am confused as to how do I get the metrics for each pod since it has been enabled in values.yml 

**What you expected to happen**:
I expect to be able to view the prometheus metrics per pod. 

**How to reproduce it** (as minimally and precisely as possible):
follow the steps I described above and set everything to true (authentication, metrics, tls, and base64 encode cacrt and cakey)

**Anything else we need to know**:
nope

**Comment by steven-sheehy** [comment]
They're Prometheus metrics so you'd view them in Prometheus or a UI for Prometheus like Grafana. Look for metrics starting with `mongodb_*` like `mongodb_mongod_connections`.

For troubleshooting, you can also view the current value by querying the pod:
`curl http://$POD_IP:9216/metrics`
