### ISSUE TITLE
[incubator/etcd] SSL and authentication support

### ISSUE THREAD

**Issue by alexlanz** [helm/charts#12275]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**Which chart**:
incubator/etcd

**Details**:
As also listed in the [todo section](https://github.com/helm/charts/tree/master/incubator/etcd#todo) of readme.md file, SSL settings are not yet supported in this chart for etcd.

Are there any plans or ongoing work to support it? 

Bitnami has already an etcd chart (https://github.com/bitnami/charts/tree/master/bitnami/etcd) with these features included, but it would be great if this functionalities are also present in the official helm chart.

And it would also be great to have authentication settings in place like setting root password or maybe also adding users if possible.

**Comment by alexlanz** [comment]
I'm willing also to help adding these features. Although, I'm not really an expert of etcd and so it would be great if someone could guide the implementation of the features like for example @lachie83 the maintainer of the chart and I could help out where I can.

**Comment by mfuxi** [comment]
I started working on this feature, how can I open it?
