### ISSUE TITLE
[stable/postgresql] missing variables in NOTES.txt

### ISSUE THREAD

**Issue by vdups** [helm/charts#12293]
**Is this a request for help?**:
no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
---

**Which chart**:
stable/postgresql

**What happened**:
helm status outputs some commands that can be copied / pasted to connect to the deployed database. Unfortunately in this output some variables default values are hard coded and do not reflect variables changed.

**What you expected to happen**:
Variables should neither be hardcoded nor ignored in "kubectl run..." sections in NOTES.txt
I'm thinking about
- image.registry
- image.repository
- image.tag

Maybe postgresqlDatabase variable should be used, too **psql -d** ( https://docs.postgresql.fr/10/app-psql.html )

**How to reproduce it** (as minimally and precisely as possible):

1. install chart overriding image.registry, image.repository, image.tag or postgresqlDatabase variable
2. helm status will display wrong content

**Anything else we need to know**:

**Comment by vdups** [comment]
Hi

First patch is [in my branch](https://github.com/vdups/charts/blob/issue-12293/stable/postgresql/templates/NOTES.txt)
I've never submitted any pullrequest so I'll need to read the contribution doc first.

Any idea if I may add a `psql -d` option to match the postgresqlDatabase variable ?

Cheers

**Comment by juan131** [comment]
Hi @vdups 

I just created a PR to address this issue. Thanks so much for reporting it!
