### ISSUE TITLE
[stable/logstash] Simplify port specification

### ISSUE THREAD

**Issue by andreykaipov** [helm/charts#12291]
This is a feature request for [stable/logstash](https://github.com/helm/charts/tree/master/stable/logstash).

Right now the chart has the following two values:

- `ports` to specify the ports exposed by the container
- `service.ports` to specify the ports exposed by the service

I found this kind of odd, since I have to specify the same ports twice in my values. Not a big deal, but it feels unnecessary. Combining the two into one `exposePorts` value that sets the exposed ports on both the container and service seems ideal. This would make the chart more opinionated, but I can't think of any reason why somebody wouldn't want to expose the same ports for the service.

Issue https://github.com/helm/charts/issues/9918 requests the same thing, but I don't think I can reopen it.

**Comment by MattLaw0** [comment]
Thanks for raising this - I was also a bit confused by the elaborate port setup for this chart.

One thing I've also discovered is the configuration of a custom nodePort seems broken. [This PR](https://github.com/helm/charts/pull/9051) supposedly introduced this functionality, but upon testing it out, it incorrectly adds it [at the `spec` level](https://github.com/helm/charts/blob/80a2a0ec1d83f9a2f0cc75e76169be2ba757abe6/stable/logstash/templates/service.yaml#L34) whereas it should be defined for each `spec.ports[]`.

As it stands you can define a custom node port by adding `service.ports.beats.nodePort` to customise the `beats` port for example, but it's probably best if we're revamping this configuration to also think about custom `nodePort` declarations for each service port too.

When I get more time I'll maybe get round to submitting a PR to to your branch that does this but feel free to beat me to it.

**Comment by andreykaipov** [comment]
Glad I'm not alone on this! 😄 I think I understand what you mean. I added reading `nodePort` value in this commit https://github.com/helm/charts/pull/12297/commits/38211ccf6642e28fef5751fe391699fe5c1ac7aa
