### ISSUE TITLE
[stable/sonatype-nexus] Add support for an S3 bucket back up

### ISSUE THREAD

**Issue by ChrisCooney** [helm/charts#12300]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

At the moment, the Sonatype nexus chart supports GCP buckets, but has no support for AWS S3 buckets. We should update the Helm chart to include S3 as a viable backup.

**Comment by draeron** [comment]
can this issue be re-open ?
