### ISSUE TITLE
[stable/redmine] External database config

### ISSUE THREAD

**Issue by denis111** [helm/charts#12324]
**Is this a request for help?**:

yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

Able to use external database without mariadb or postgresql charts.

**Version of Helm and Kubernetes**:

2.13.0 and 1.11.5

**Which chart**:

stable/redmine

**What happened**:

It seems impossible to configure external mysql database with custom user/password

**What you expected to happen**:

Configure mysql host, username and password.

**How to reproduce it** (as minimally and precisely as possible):

Launch chart with databaseType.postgresql=false and databaseType.mariadb=false, it will still set DB username as root an search password in non-existing secret {{ template "redmine.mariadb.fullname" . }} with key mariadb-root-password.

**Anything else we need to know**:
Workaround could be manually create secret and create user in external DB with username root and put DB IP in /etc/hosts with host {{ template "redmine.mariadb.fullname" . }}

Another request: describe how to install plugins.

**Comment by juan131** [comment]
Hi @denis111 

Thanks for suggesting this improvement. I just created a PR to address it.

**Comment by denis111** [comment]
Thank you very much! And what about plugins installation, or should i create another issue? I also find it difficult using bitnami/redmine docker image so i think there must be some init container installing plugins...

**Comment by juan131** [comment]
Hi @denis111 

Please create a different issue for that. 

The easiest way for us is to have one issue per topic so we can create a PR to address it and close it. This way, we can consider it done and move into the next issue/request.

**Comment by juan131** [comment]
Hi @denis111 

The PR was merged! Now you should be able to use an external database with Redmine!!
