### ISSUE TITLE
[stable/concourse] Can't login to concourse using github

### ISSUE THREAD

**Issue by koustubh25** [helm/charts#12321]
**Is this a request for help?**: YES

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Can't login using github login on concourse

**Version of Helm and Kubernetes**:

Helm:
1. client version v2.12.1
2. server version v2.12.1

Kubernetes:
server version: 1.12.5-gke.5

**Which chart**:
Concourse

**What happened**:
Internal Server Error while trying to login

**What you expected to happen**:
Github login should take place successfully

**How to reproduce it** (as minimally and precisely as possible):
1. Created a oauth app on github and acquired `clientid` and `secret`
2. Setup these values in values.yml
i. githubClientId
ii. githubClientSecret https://github.com/helm/charts/blob/master/stable/concourse/values.yaml#L1741-L1742
iii. github.enabled: true https://github.com/helm/charts/blob/master/stable/concourse/values.yaml#L666
iv. externalUrl: http://concourse-prod.myserver.com
https://github.com/helm/charts/blob/master/stable/concourse/values.yaml#L101
v. Github oauth application redirect uri: http://concourse-prod.myserver.com/sky/issuer/callback

This service is available publicly (server name changed)

When I try to login using github, I think the login is successful, but there seems to some issue exchanging the authorisation code for auth token. I get redirected to this uri 
http://concourse-prod.myserver.com/sky/issuer/callback?code=6620008a9dd2892397d8&state=rc4wyemnzeyt24lz6gqeqdf65

and it throws a 500 error (image attached)
![image](https://user-images.githubusercontent.com/5240529/54510002-c5e11100-499f-11e9-96c5-fdfd71a246e9.png)

I can see the folllowing in `concourse-web's` log 
```
"timestamp":"1552888898.884241104","source":"atc","message":"atc.dex.event","log_level":2,"data":{"fields":{},"message":"Failed to authenticate: github: failed to get token: oauth2: server response missing access_token","session":"5"}}
```
Did I miss any configuration?

**Comment by williammartin** [comment]
I'm seeing something very similar to this. After going through the web auth flow on GitHub, I am redirected back to Concourse and see:

![image](https://user-images.githubusercontent.com/1611510/72068735-0bcbe480-32e6-11ea-92fa-da85e9353c35.png)

The callback URL is `sky/issuer/callback?code=....&state=....` so it seems like this should work totally fine

**Comment by williammartin** [comment]
This was caused by my client secret being incorrect ^
