### ISSUE TITLE
[stable/jenkins] support for master service annotations

### ISSUE THREAD

**Issue by arielkung** [helm/charts#1234]
It will be really helpful to add annotations support in templates/jenkins-master-svc.yaml to allow https, dns and other useful stuff.

Example service supporting annotations: https://github.com/kubernetes/charts/blob/master/stable/prometheus/templates/server-service.yaml

**Comment by lachie83** [comment]
Does this do the trick?

**Comment by arielkung** [comment]
Yes!!! :)

**Comment by tobilarscheid** [comment]
I would like to see the same thing on pod level, specifically because we are using the jenkins prometheus plugin and need to add a prometheus scrape annotation to the pod.

**Comment by tobilarscheid** [comment]
Should I open a new issue?
