### ISSUE TITLE
README.md file in Keycloak chart includes 2 dead Links

### ISSUE THREAD

**Issue by ThomasUllrich666** [helm/charts#12342]
Hi team, 
the Readme.md file for the Keycloack Chart has two broken links:

    https://github.com/jboss-dockerfiles/keycloak/blob/master/server/cli/databases/postgres/change-database.cli
    https://github.com/jboss-dockerfiles/keycloak/blob/master/server/cli/databases/mysql/change-database.cli

**Comment by unguiculus** [comment]
The Keycloak chart here is being deprecated (#13316) and moved to a new home:
https://github.com/codecentric/helm-charts

I'm closing this issue. Feel free to open a new issue in the new repo. Thanks.
