### ISSUE TITLE
[stable/airflow] dags.initContainer.installRequirements=true does not work for all deployment strategies

### ISSUE THREAD

**Issue by billcrook** [helm/charts#12357]
**Is this a request for help?**:

no.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT AFAICT

**Version of Helm and Kubernetes**:
helm: 2.13.0
k8s: 1.13.4

**Which chart**:
stable/airflow 2.3.0

**What happened**:

Given the doc:
> Add a requirements.txt file at the root of your DAG project (dags.path entry at values.yaml) and they will be automatically installed. That works for both shared persistent volume and init-container deployment strategies (see below).

And given [this comment](https://github.com/helm/charts/issues/10103#issuecomment-452387231)

One should be able to drop a requirements.txt file in the dag root and it will be automatically installed event when *not* using the git fetch dag deployment strategy.

It appears `dags.initContainer.enabled` must be true to enter the block which calls the install-requirements.sh script. Unfortunately setting this value will then also cause containers to try to do the git fetch. See here as an example (the other container have same code):
https://github.com/helm/charts/blob/3a7e22cd4a3c9e417e5c130a09e33a108edd7734/stable/airflow/templates/deployments-scheduler.yaml#L109

**What you expected to happen**:
The requirements.txt file to be installed when not using the git fetch dag deployment strategy. In other words, the following configuration should still perform the pip install:
```
dags:
  initContainer:
    enabled: false
    installRequirements: true
```

**How to reproduce it** (as minimally and precisely as possible):
* use a persistent volume to mount the dag root
* put your requirements.txt file in the dag root.
* install via chart and set `dags.initContainer.installRequirements=true`

**Anything else we need to know**:

**Comment by heysusgarcia** [comment]
i am also trying to get this to work. I have set `installRequirements: true` under dags and placed my `requirements.txt` file in the dag root, but still no luck. My dag is still broken because it can't find the the needed module.

**Comment by cr1st1p** [comment]
I also wanted to just report this bug.

Indeed, to have requirements.txt auto installed, you need to also have that initContainers.enabled activated, which contradicts the README text saying 
```
That works for both shared persistent volume and init-container deployment strategies (see below).
```
And clearly this is a bug - I can't see why install requirements should be tied to how you get the dags files into there.

Also a documentation bug - or just a workaround for the bug? - later in the README.txt it says that you should mount yourself requirements.txt at /requirements.txt .. 

Can we have both the templates and documentation fixed please?
