### ISSUE TITLE
[stable/redmine] Plugin install

### ISSUE THREAD

**Issue by denis111** [helm/charts#12368]
**Is this a request for help?**:

yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

I can't see any way to install plugins. The only way seems to be entering the container (kubectl/docker exec), put the plugin manually, execute bundle install, etc. but I'm not sure. There must be another more k8s way to do that.

**Version of Helm and Kubernetes**:

2.13.0 and 1.11.8

**Which chart**:

stable/redmine

**What happened**:

Can't install plugins

**What you expected to happen**:

Have the way to install plugin.

**How to reproduce it** (as minimally and precisely as possible):

Install Redmine and try to install any plugin.

**Anything else we need to know**:

May be there must be some init container which tooks the list of plugin urls and installs them?

**Comment by juan131** [comment]
The process to follow, at this very moment, to install a plugin is very manual and it's summarised in the link below:

https://docs.bitnami.com/installer/apps/redmine/configuration/install-plugins/

There are several alternatives to implement a way to install these plugins automatically. 

I think a possible approach is to have a directory where the user can mount the desired plugins (ZIP format) so we add some init logic that detect and install them. This approach would be very similar to the one used on MariaDB chart where the user can include its custom .sql files and they're executed (see https://github.com/helm/charts/tree/master/stable/mariadb#initialize-a-fresh-instance).

I'm creating an issue at the image repo to support this feature in the Bitnami Redmine image, see  https://github.com/bitnami/bitnami-docker-redmine/issues/118

**Comment by denis111** [comment]
@juan131 Great! Also if you see, for example, kibana chart, there you supply a list of urls of plugins in zip to download and install by init container.

**Comment by juan131** [comment]
Yes, we can create an initContainer and download/place the ZIP files in the directory I mentioned so Redmine install them when initialising.

**Comment by denis111** [comment]
@stale Please, wait until https://github.com/bitnami/bitnami-docker-redmine/issues/118 finished ;)

**Comment by juan131** [comment]
Wait until the changes requested at bitnami/bitnami-docker-redmine#118 are implemented.
