### ISSUE TITLE
Hi team, when trying to install prometheus-operature 'helm install stable/prometheus-operator' getting this Error: apiVersion "monitoring.coreos.com/v1" in prometheus-operator/templates/exporters/kubelet/servicemonitor.yaml is not available, helm version v2.9.1 and kubectl version Major:"1", Minor:"11", GitVersion:"v1.11.3"

### ISSUE THREAD

**Issue by deepti-cloudibility** [helm/charts#12362]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
yes

**Version of Helm and Kubernetes**:
v2.9.1 
kubectl version : Major:"1", Minor:"11"

**Which chart**: Prometheus-operator

**What happened**:Error: apiVersion "monitoring.coreos.com/v1" in prometheus-operator/templates/alertmanager/servicemonitor.yaml is not available
or sometimes this error: Error: apiVersion "monitoring.coreos.com/v1" in prometheus-operator/templates/prometheus/rules/k8s.rules.yaml is not available

**What you expected to happen**: Installation of prometheus-operator

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/prometheus-operator --name prom --namespace monitoring

**Anything else we need to know**:

**Comment by vsliouniaev** [comment]
This appears to be a duplicate of: https://github.com/helm/charts/issues/9241

Please see this section in the readme for an explanation for how to work around this issue: https://github.com/helm/charts/blob/master/stable/prometheus-operator/README.md#helm-fails-to-create-crds
