### ISSUE TITLE
[stable/kibana] elasticsearch.url is deprecated

### ISSUE THREAD

**Issue by jbudz** [helm/charts#12378]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
https://github.com/helm/charts/blob/90bcd1a5ef30b87dafe543726f8fdaaf0fe6cf84/stable/kibana/values.yaml#L24
https://github.com/elastic/kibana-docker/commit/5c9c6d18146932c42a1203f5b42d4daf49a6616e
https://github.com/elastic/kibana/pull/21928

**Anything else we need to know**:
Renaming it to elasticsearch.hosts is sufficient, converting to an array is optional.  Maybe related to https://github.com/helm/charts/issues/12199 and https://github.com/helm/charts/pull/12200

**Comment by pjanuario** [comment]
This issue is still valid one.

**Comment by loqutus** [comment]
+1
