### ISSUE TITLE
[stable/prometheus-operator] Role binding for namespace not created if roleNamespaces is empty

### ISSUE THREAD

**Issue by masterada** [helm/charts#12376]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 
any

**Which chart**:
prometheus-operator

**What happened**:
Role for .Release.Namespace is not created when .Values.prometheus.rbac.roleNamespaces is empty

**What you expected to happen**:
Role for .Release.Namespace is created as documented: 
https://github.com/helm/charts/blob/452e2b181626ca629970e6334af5692484df1668/stable/prometheus-operator/values.yaml#L835

**How to reproduce it** (as minimally and precisely as possible):
set `prometheus.rbac.roleNamespaces = []`

**Anything else we need to know**:
The `.Values.prometheus.rbac.roleNamespaces` condition should be dropped, so the RoleList is created even when roleNamespaces is empty (so the role for .Release.Namespace is always created).
https://github.com/helm/charts/blob/452e2b181626ca629970e6334af5692484df1668/stable/prometheus-operator/templates/prometheus/role-specificNamespace.yaml#L1

Also see: go templates documentation: https://golang.org/pkg/text/template/#hdr-Actions

{{if pipeline}} T1 {{end}}
	If the value of the pipeline is empty, no output is generated;
	otherwise, T1 is executed. The empty values are false, 0, any
	nil pointer or interface value, and any array, **slice**, map, or
	string **of length zero**.
	Dot is unaffected.

**Comment by vsliouniaev** [comment]
I don't think that these namespace roles are actually needed, the cluster role grants enough permissions to provide all the necessary functionality. Splitting out permissions more granularly at this point may break a bunch of existing installs, so I'm hesitant to say that's a good direction to go. 

Do you think removing this configuration is the right way to go?

**Comment by masterada** [comment]
I tried it without https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/role-specificNamespace.yaml and https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/rolebinding-specificNamespace.yaml, it seems to be working (can see the pod metrics in grafana with a clean install of the chart).

I think it's safe to remove these roles & bindings, or at least make them removable (currently a role binding for the release namespace is always created, even if there is no role for it, because the role binding does not contain the .Values.prometheus.rbac.roleNamespaces check).
