### ISSUE TITLE
[stable/sonarqube] Plugins no longer persist when using persistance and installing plugins via UI

### ISSUE THREAD

**Issue by aaronmell** [helm/charts#12388]
**Version of Helm and Kubernetes**:

**Which chart**:
stable/sonarqube

**What happened**:
when using persistance and not using the plugins: install features, the plugins are wiped away after every restart of the pod, now that the volume is mapped to the /tmp directory.

**What you expected to happen**:
Installing a plugin via the UI should persist the plugin after a restart. 

**How to reproduce it** (as minimally and precisely as possible):
Install a plugin via the UI, restart the pod. Plugin is no longer installed.

**Anything else we need to know**:
Regression from issue https://github.com/helm/charts/issues/10195

**Comment by rjkernick** [comment]
I will try and look into this over the next few days. Thanks for reporting this

**Comment by ramk2020** [comment]
Looks like this issue does not solved. I have the same issue.
