### ISSUE TITLE
[stable/concourse] undeployable chart if concourse.web.kubernetes.createTeamNamespaces=false

### ISSUE THREAD

**Issue by weirdgiraffe** [helm/charts#12380]
**This is a BUG REPORT**

**Version of Helm and Kubernetes**:
```
❯❯❯❯ helm version
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```
```
❯❯❯❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.5-gke.5", GitCommit:"2c44750044d8aeeb6b51386ddb9c274ff0beb50b", GitTreeState:"clean", BuildDate:"2019-02-01T23:53:25Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/concourse

**What happened**:

```
❯❯❯❯ helm install stable/concourse --set=concourse.web.kubernetes.createTeamNamespaces=false --version=5.0.0
Error: release zeroed-rabbit failed: namespaces "zeroed-rabbit-main" not found
```

**What you expected to happen**:

should be installed

**How to reproduce it** (as minimally and precisely as possible):

```
❯❯❯❯ helm install stable/concourse --set=concourse.web.kubernetes.createTeamNamespaces=false --version=5.0.0
Error: release zeroed-rabbit failed: namespaces "zeroed-rabbit-main" not found
```

**Anything else we need to know**:

There are two checks which doesn't work well together:

https://github.com/helm/charts/blob/90bcd1a5ef30b87dafe543726f8fdaaf0fe6cf84/stable/concourse/templates/namespace.yaml#L1

https://github.com/helm/charts/blob/90bcd1a5ef30b87dafe543726f8fdaaf0fe6cf84/stable/concourse/templates/web-rolebinding.yaml#L1-L3

Team namespaces are not being created because of `createTeamNamespaces` option but `web-rolebinding.yaml` doesn't pay attention to `createTeamNamespaces` option and tries to create rolebindings in not existing namespaces

**Comment by paroxp** [comment]
I believe the `createTeamNamespaces` is intended to be used when you as an operator plan on creating these yourself before hand.

You may choose not to create `RBAC` by setting `.Values.rbac.create` to `false`, which will prevent your problem from happening.

Our workflow is to create these namespaces first, fill them in with secrets and pipelines, and then install concourse chart which we hope will create all the precious rbac roles for us.
