### ISSUE TITLE
Populate "icon" Chart.yaml attribute

### ISSUE THREAD

**Issue by migmartri** [helm/charts#124]
In the [Helm Monocular project](https://github.com/helm/monocular), we aim for indexing and exposing Helm Charts in a simple way via an user interface.

This interface relies on the Charts logos exposed via the "icon" attribute in the `Chart.yaml` files.

Currently, from the stable charts, only [Jenkins](https://github.com/kubernetes/charts/blob/master/stable/jenkins/Chart.yaml) includes this optional property. 

It would be great to populate the existing icon attributes and "enforce" as a best practice its addition in new official charts.

Thoughts?

**Comment by lachie83** [comment]
@migmartri I would like to understand the impact of not doing this? 

There is potential that not all charts will have an icon to associate. Is there a default icon that gets displayed in-lieu of a defined icon?

**Comment by migmartri** [comment]
Hi,

> There is potential that not all charts will have an icon to associate.

Sorry my comment might be confusing. I do not mean to make it mandatory what I meant was:

1 - For the current Charts, populate the icon URL if possible.
2 - For new charts, "recommend" the property addition using for example an INFO message in the linter.

>  Is there a default icon that gets displayed in-lieu of a defined icon?

In the monocular UI site there is not such option today but there will be a default icon replacement.

**Comment by lachie83** [comment]
@migmartri thank you very much for the additional context. You're initial comments were not confusing at all 👍. I was simply trying to gain a better understanding of the issue. Would you be interested in submitted PRs to add icons to the current stable charts? I would be happy to review?

As for point 2 would you like to raise an issue on the helm repo to discuss the possibility of adding recommendations? Referencing this issue?

+1 on the default icon in monocular.

**Comment by migmartri** [comment]
Thanks @lachie83 

>  Would you be interested in submitted PRs to add icons to the current stable charts? I would be happy to review?

Availability wise, I am currently checking with @prydonius so either him or I will do it.

> As for point 2 would you like to raise an issue on the helm repo to discuss the possibility of adding recommendations? Referencing this issue?

[Done](https://github.com/kubernetes/helm/issues/1501), same thing applies to this one.

Regards,
Miguel

**Comment by lachie83** [comment]
Fantastic! Thank you very much @migmartri!
