### ISSUE TITLE
[stable/Grafana] prebuilt dashboards won't be loaded after PR #11997

### ISSUE THREAD

**Issue by YingjunHu** [helm/charts#12400]
**Is this a request for help?**:
YES

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
Helm: 2.13.0
Kubernetes: 1.13.4

**Which chart**:
stable/Grafana

**What happened**:
The prebuilt dashboards won't be loaded as the Grafana launched. There are two characters **|-** in the beginning of the json dashboard files when they are mounted to the pod (I exec into the pod and check the file). 
This is due to the PR [stable/grafana] add missing multiline indicator #11997 that added these two characters at the end of the line 18 of templates/dashboards-json-configmap.yaml. (https://github.com/helm/charts/blob/master/stable/grafana/templates/dashboards-json-configmap.yaml#L18).
After remove these two characters, the prebuilt dashboards are loaded correctly. I don't know what these multiline indicators are doing but it seems like the strip indicator in YAML file but eventually are added to the beginning of the json file.

**What you expected to happen**:
Dashboard will be loaded when Grafana launches

**How to reproduce it** (as minimally and precisely as possible):
Use any prebuilt json dashboard and put it in the Grafana/dashboards and install Grafana using helm.

**Anything else we need to know**:

**Comment by maorfr** [comment]
asked the author of this PR to take a look.

**Comment by jcoeltjen** [comment]
I will take a look into that issue.
Seems to be that the multiline indicator was created by helm when using the `toYaml` function.

**Comment by YingjunHu** [comment]
Thanks!

**Comment by jcoeltjen** [comment]
I created a PR that should fix the regression (#12512).
Sorry for any inconveniences I may have caused with my previous PR. I did not test all cases and it worked fine as long you did not try to load dashboards from file.

As the PR is only a minor change it should not take too long to be reviewed.

**Comment by YingjunHu** [comment]
@jcoeltjen No worries! Thank you for the fast response :D

**Comment by maorfr** [comment]
Thanks a lot @YingjunHu for bringing this up and @jcoeltjen for the fix!
