### ISSUE TITLE
[stable/prometheus-operator] support disabling alertmanager.yaml secret creation

### ISSUE THREAD

**Issue by johnharris85** [helm/charts#12412]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm: v2.11.0
Kubernetes: v1.11.8

**Which chart**:
[stable/prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator)

**What happened**:
Prometheus supports a way to define config (secrets) external to the chart through the additionalScrapeConfigsExternal parameter, AlertManager does not.

**What you expected to happen**:
AlertManager should also allow the management of the secret / config outside of the Helm chart to support the use case for sealed secrets etc...

**Comment by lcostea** [comment]
@johnharris85 
I also need such a feature. I am thinking of just a simple parameter called useExistingSecret: true/false under alertmanager. 
When it will be true, the secret will not be created anymore and the helm chart user will be responsible to provide it (through sealed secrets, aws-ssm or other integrations with secured stores).
Will it work for you? 

Also please note that alertmanager config templating can be used for some secret obfuscation, even though not recommended and it doesn't work in all cases: https://github.com/prometheus/alertmanager/pull/1081

**Comment by johnharris85** [comment]
@lcostea ye I don't like that PR as it doesn't really solve the issue as I want to check everything into git, so my template is going in there anyway :(

I think the best solution is just to replicate what happens in Prometheus with the addition of an `...External` parameter which if `true` doesn't create the config secret and the responsibility is on the user as you say.

**Comment by lcostea** [comment]
Actually the template can be taken from a secret, which you can create yourself and only pass the name, something like this:
```
alertmanager:
    alertmanagerSpec:
      secrets:
      - alertmanager-some-integration
```
The secret ends up on the alertmanager pod and can be used as a template by importing it in the config:
```
  alertmanager:
    config:      
      templates:
      - '/etc/alertmanager/secrets/alertmanager-some-integration/notify.tmpl'
```
https://prometheus.io/blog/2016/03/03/custom-alertmanager-templates/

But it is not recommended because you can still get to the secret content pretty easy.

**Comment by johnharris85** [comment]
Oh OK cool, not really played with templates. Thanks @lcostea! Although ye, External seems the safer option :)
