### ISSUE TITLE
[Concouse] ReadWriteOnce used as access mode for workers

### ISSUE THREAD

**Issue by artamonovkirill** [helm/charts#12417]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Version of Helm and Kubernetes**: 2.6.2, 1.10.13

**Which chart**: stable/concourse

I've noticed that by default persistent volume claims for workers are created with "ReadWriteOnce" mode.
Does that mean that no matter how big the volume size it, the worker will eventually run out of space and start failing?
We sometimes (after weeks or even months of stable performance) have issues with workers starting to be slow and to randomly fail checking out resources or running builds.

**Comment by YoussB** [comment]
Hey @artamonovkirill,
As far as I understand, `RedWriteOnce` means:
> The volume can be mounted as read-write by a single node

not really sure how this would affect the worker's performance? 🤔
