### ISSUE TITLE
Nginx-Ingress update from app version 0.21.0 to 0.22.0 --> No routing anymore

### ISSUE THREAD

**Issue by tantweiler** [helm/charts#12423]
I have a pretty simple nginx ingress setup within the GKE by using the nginx-ingress helm chart:

`helm install --namespace nginx-ingress-lb --name nginx-ingress stable/nginx-ingress --set rbac.create=true`
All other apps which are also in other namespaces of course use this loadbalancer with the default annotation in each ingress.yaml:
`kubernetes.io/ingress.class: "nginx"`

Until chart version 1.1.5 and app version 0.21.0 everything was fine. But starting with chart version 1.2.0 and app version 0.22.0 the loadbalancer doesn't forward the traffic anymore. If I do a rollback to 0.21.0 again everything is fine. From my understanding the only thing that had a breaking change was 
`nginx.ingress.kubernetes.io/rewrite-target` 
which I don't use.

Any idea would be really appreciated since I don't wanna stick to app version 0.21.0.
Thank you in advance!

**Comment by uday1bhanu** [comment]
url-rewrite has been changed in 0.22.0 release and these are breaking changes which are not backwards compatible. Please refer to https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target for more instructions on how to get url-rewrite working for newer versions.

**Comment by azze1337** [comment]
> From my understanding the only thing that had a breaking change was
nginx.ingress.kubernetes.io/rewrite-target
**which I don't use.**

@uday1bhanu : Thanks for the hint but as I wrote I don't use this annotation!
