### ISSUE TITLE
[stable/redmine] Tolerations, nodeSelector and affinity

### ISSUE THREAD

**Issue by denis111** [helm/charts#12429]
**Is this a request for help?**:

yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

Please, add the way to specify pod tolerations, nodeSelector and affinity.

**Version of Helm and Kubernetes**:

2.13.0 and 1.11.8

**Which chart**:

stable/redmine

**What happened**:

can't move pods to nodes with taint without manual deployment post-install edit.

**What you expected to happen**:

Ability to specify tolerations, nodeSelector and affinity in values.

**How to reproduce it** (as minimally and precisely as possible):

try to install redmine chart on tainted node

**Anything else we need to know**:

We turn off dev/ci nodes at night time to save costs in aws and we want redmine to be executed 24h on another nodes.

**Comment by tompizmor** [comment]
@denis111 I just sent [this PR](https://github.com/helm/charts/pull/12525) that should add what you have requested. You can start testing until is reviewed and merged

**Comment by juan131** [comment]
Hi @denis111 

The changes were merged and now you should be able to configure Tolerations, nodeSelector and affinity in the deployment using the Redmine chart.

Please do not hesitate to let us know if you find any issues with them.
