### ISSUE TITLE
Add helm-chart for redis-cluster

### ISSUE THREAD

**Issue by vidhig** [helm/charts#12424]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST:
- Add a chart for installing redis as a redis-cluster

**What is a redis-cluster?**

Redis Cluster is a set of Redis instances working together to make your data storage scale across nodes while also making it a bit more resilient. Data is automatically split across nodes and it supports a master/slave setup for increased availability in case of a failure. It is basically a data sharding strategy, with the ability to reshard keys from one node to another while the cluster is running, together with a failover procedure that makes sure the system is able to survive certain kinds of failures.

For Reference: https://redislabs.com/redis-features/redis-cluster

**Comment by vidhig** [comment]
will be taking this up.

**Comment by juan131** [comment]
I'd say that Redis-HA chart configures this already. See https://github.com/helm/charts/tree/master/stable/redis-ha

**Comment by vidhig** [comment]
redis-cluster is slightly different from redis-ha. A redis-cluster has multiple masters and multiple slaves and the keys can distribute themselves among the master redis instances, basically a redis-cluster provides a redis database that is sharded across multiple nodes. 

From what I saw in the redis-ha chart, it can only provide a simple one master, multiple slave model and provide high availability.

Please let me know if I missed something.

**Comment by neglect-yp** [comment]
related issue: https://github.com/helm/charts/issues/11817

**Comment by neglect-yp** [comment]
I think that redis-cluster chart should be added as an incubator chart because Redis Cluster is different from Redis Sentinel (redis-ha chart).

I have already implemented my own redis-cluster chart (without enough documents). If @vidhig hasn't start to work for this yet, I'll add documents to my chart and create PR.

**Comment by vidhig** [comment]
@neglect-yp I have started working on this and planned on adding it to the incubator repo. I have the chart ready but working on writing the appropriate README.md and NOTES.txt. 

Will be creating the PR by the end of next week.

**Comment by neglect-yp** [comment]
@vidhig Thank you for your reply. I'm looking forward to your PR :smile: .

**Comment by vidhig** [comment]
Link to the PR: https://github.com/helm/charts/pull/13029

This PR is working but can be improved. Any inputs would be very helpful.
Thank you
