### ISSUE TITLE
[stable/concourse] Update flags that will be introduced in 5.1.0

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [helm/charts#12431]
**Is this a request for help?**:
No
---

**FEATURE REQUEST**
Update the concourse chart to reflect flag changes introduced in Concourse 5.1.0 release

Added values
- [ ] CONCOURSE_CONTAINER_SWEEPER_MAX_IN_FLIGHT
- [ ] CONCOURSE_TSA_PEER_ADDRESS
- [ ] CONCOURSE_VAULT_SHARED_PATH
- [ ] CONCOURSE_VOLUME_SWEEPER_MAX_IN_FLIGHT

Removed values
- [ ] CONCOURSE_BAGGAGECLAIM_REAP_INTERVAL
- [ ] CONCOURSE_PEER_URL
- [ ] CONCOURSE_TSA_PEER_IP

**Which chart**:
Stable/Concourse

**What happened**:
New release of Concourse

**What you expected to happen**:
Update the chart to configure the correct options provided by Concourse

**Comment by YoussB** [comment]
@xtreme-sameer-vohra and I are gonna work on it 😃

**Comment by YoussB** [comment]
🙌
