### ISSUE TITLE
Add checksum for secrets file in rabbitmq-ha

### ISSUE THREAD

**Issue by rishisharmamt** [helm/charts#12456]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:

**Which chart**: rabbitmq-ha

**What happened**: On updating definitions (queue, exchange, policies, etc.), the pods should be restarted so that updated definitions can be loaded on rabbitmq. However, as only secrets yaml is updated and not statefulset spec, the pod needs to be restarted manually on updating  definitions. 

**What you expected to happen**: There should have been an annotation including checksum of the the secrets file, so that in case of any changes in definitions, the pods are also restarted
and updated definitions are used automatically.

**How to reproduce it** (as minimally and precisely as possible): Add a policy using definitions.policies value in helm chart and run helm upgrade. Go to rabbitmq management plugin ui and you will not be able to see the policy that you added unless you restart the pods.

**Anything else we need to know**:

**Comment by yoshz** [comment]
I also would like to see this implemented or add a post-install/post-upgrade hook to import the definitions.
Right now you have to delete a pod or a add a custom pod annotation to have the new definitions imported.

**Comment by zerkms** [comment]
Can we please reopen it?

**Comment by heckad** [comment]
@zerkms This also need for PostgreSQL.
