### ISSUE TITLE
[stable/concourse] Unable to install concourse on minikube

### ISSUE THREAD

**Issue by ashic** [helm/charts#12455]
**Is this a request for help?**:

Erm... well, it's a bug report, which is also asking for help. I guess.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

With minikube, running

```
helm install --name concourse stable/concourse 
```

fails.

**Version of Helm and Kubernetes**:

```
 ~  helm install --name concourse stable/concourse
Error: error validating "": error validating data: field spec.dataSource for v1.PersistentVolumeClaimSpec is required
 ✘  ~  minikube version
minikube version: v0.35.0
 ~  k version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
 ~  helm version
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
 ~  

```

(k is my alias for kubectl). 

**Which chart**:
stable/concourse

**What happened**:
Fails with

```
Error: error validating "": error validating data: field spec.dataSource for v1.PersistentVolumeClaimSpec is required
```

**What you expected to happen**:
For concourse to be installed.

**How to reproduce it** (as minimally and precisely as possible):
Specified above.

**Anything else we need to know**:
I'm running this on archlinux with docker version:

```
 ~  docker version
Client:
 Version:           18.09.3-ce
 API version:       1.39
 Go version:        go1.12
 Git commit:        774a1f4eee
 Built:             Thu Feb 28 20:38:40 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.3-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12
  Git commit:       774a1f4eee
  Built:            Thu Feb 28 20:37:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Minikube is using the default VirtualBox instance it creates. 

```
 ✘  ~  VBoxManage --version
6.0.4r128164
```

**Comment by pauloeliasjr** [comment]
Hello @ashic! You are using a older version of helm. Try using a newer version (v2.13.0).
This release adds, among other features, kubernetes 1.13.0 client libraries updates. I was having the same problem with other repositories and after upgrading to helm 2.13.0, the problem is gone.

**Comment by ashic** [comment]
Hmm.. updated stuff, but now get:

```
 ~  helm install --name concourse stable/concourse
Error: error validating "": error validating data: the server could not find the requested resource
 ✘  ~  k version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
 ~  helm version
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```

**Comment by pauloeliasjr** [comment]
@ashic You're still using on old version of helm (v2.5.0). You need to update your local helm client binary (https://storage.googleapis.com/kubernetes-helm/helm-v2.13.1-linux-amd64.tar.gz) and using this one, do a `helm init --upgrade` or `--force-upgrade` to force the server component of helm (tiller) version on Kubernetes. You'll be fine after this.

> Hmm.. updated stuff, but now get:
> 
> ```
>  ~  helm install --name concourse stable/concourse
> Error: error validating "": error validating data: the server could not find the requested resource
>  ✘  ~  k version
> Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
>  ~  helm version
> Client: &version.Version**{SemVer:"v2.5.0",** GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
> Server: &version.Version**{SemVer:"v2.5.0",** GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
> ```
