### ISSUE TITLE
LetsEncrypt not fetching the production CAServer stable/Traefik Chart

### ISSUE THREAD

**Issue by sjkeerthi** [helm/charts#12462]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
 2.0 / v1.13.4

**Which chart**:
stable/traefik

**What happened**:
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: stable/traefik
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    debug.enabled: "true"
    acme.logging: "true"
    acme.enabled: "true"
    acme.staging: "false"
    acme.email: "keerthiraja@xxxxxx.com"
    acme.persistence.storageClass: "acme-data"
    acme.persistence.size: "1Gi"
    acme.challengeType: "dns-01"
    acme.dnsProvider.name: "godaddy"
    acme.dnsProvider.godaddy.GODADDY_API_KEY: "xxxxxxx"
    acme.dnsProvider.godaddy.GODADDY_API_SECRET: "xxxxx"
    acme.logging: "true"

After deploy still I could see  acme.staging: "false"  while the logs its goes to 
{"level":"info","msg":"Starting provider *acme.Provider {\"Email\":\"keerthiraja@xxxxxx.com\",\"ACMELogging\":true,\"CAServer\":\"https://acme-staging-v02.api.letsencrypt.org/directory\",\"Storage\":\"/acme/acme.json\",\"EntryPoint\":\"https\",\"KeyType\":\"\",\"OnHostRule\":true,\"OnDemand\":false,\"DNSChallenge\":{\"Provider\":\"godaddy\",\"DelayBeforeCheck\":0,\"Resolvers\":null,\"DisablePropagationCheck\":false},\"HTTPChallenge\":null,\"TLSChallenge\":null,\"Domains\":null,\"Store\":{}}","time":"2019-03-22T16:30:19Z"}

Still pointing to staging
CAServer\":\"https://acme-staging-v02.api.letsencrypt.org/directory\",\"Storage\":\"/acme/acme.json\

**What you expected to happen**:
It need to generate the production certificate.

**Comment by kalgecin** [comment]
@sjkeerthi did you end up solving this issue?
