### ISSUE TITLE
Do not use `command:` in Vault Deployment

### ISSUE THREAD

**Issue by krish7919** [helm/charts#12470]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature/Enhancement

**Version of Helm and Kubernetes**:
Helm v2.12, Kubernetes v1.11

**Which chart**:
Vault Helm chart at `charts/tree/master/incubator/vault`

**What happened**:
In the chart we run Vault as `root` as specified here: https://github.com/helm/charts/blob/master/incubator/vault/templates/deployment.yaml#L43

Output of deploying the chart:
```
# ps -ef
PID   USER     TIME  COMMAND
    1 root      0:07 vault server -config /opt/config/config.json
   26 root      0:00 bash
  176 root      0:00 ps -ef
```

**What you expected to happen**:
There is already a [docker-entrypoint.sh](https://github.com/hashicorp/docker-vault/blob/e6353cca743f951019a46a1cc597c34d9ff24f38/0.X/Dockerfile#L76) as per the official Dockerfile. This script does some additional checks and also runs the program as `vault` user inside the container, which might be useful. Hence, instead of using `command:` in the chart, we should enable the usage of using the official entrypoint in the imae.

**How to reproduce it** (as minimally and precisely as possible):
Deploy the chart and run a `ps -ef` to verify. Also, run the command `docker run vault` locally, and verify that you see Vault run as the `vault` user:

```
/ # ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 {docker-entrypoi} /usr/bin/dumb-init /bin/sh /usr/local/bin/docker-entrypoint.sh server -dev
    6 vault     0:05 vault server -config=/vault/config -dev-root-token-id= -dev-listen-address=0.0.0.0:8200 -dev
   42 root      0:00 sh
   96 root      0:00 ps -ef
```

**Anything else we need to know**:
Nothing else, I think.

**Comment by krish7919** [comment]
@jbialy @mikeraimondi @dimitrigraf @varshavaradarajan @wfernandes 

Can you please help in assigning on removing the `lifecycle/stale` policy here?

**Comment by jbialy** [comment]
@krish7919 Can you attempt to implement the change, test and submit a PR? I agree that we should be using the default entrypoint defined in the vault docker image as opposed to overwriting it, if possible. However, I haven't tested this!

**Comment by jbialy** [comment]
Going to bump this again!

**Comment by jbialy** [comment]
This is still a good issue to look into!
