### ISSUE TITLE
[stable/owncloud] About Owncloud pod is not run

### ISSUE THREAD

**Issue by it2911** [helm/charts#1249]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
Owncloud

**What happened**:
The mariadb is great run, but the owncloud pod is not run. It is lead to I cloud not access to owncloud page.

**What you expected to happen**:
I coud run owncloud pod and access to owncloud page.

**How to reproduce it** (as minimally and precisely as possible):
You can try the pasted yaml file(I zipped the file). I create the stroageclass which named officeapp
[owncloud.zip](https://github.com/kubernetes/charts/files/1053597/owncloud.zip)

. I successful to run wordpress, odoo etc. apps. Just owncloud is failed.

**Anything else we need to know**:
Thank you for your help. By the way, I use the 0.4.9 yaml file.

**Comment by prydonius** [comment]
@it2911 can you paste the `kubectl describe` output of the OwnCloud pod?
