### ISSUE TITLE
[stable/jenkins] Allow configmap for Master.JCasC.ConfigScripts

### ISSUE THREAD

**Issue by stevezau** [helm/charts#12514]
**Is this a FEATURE REQUEST**

**Which chart**: Jenkins  0.36.0

**What happened**: Trying to configure jobs DSL scripts in Master.JCasC.ConfigScripts resulting in huge and confusing values.yaml.

**What you expected to happen**: The ability to seperate out the jobs DSL using a configMap.

**Anything else we need to know**:
I am trying to configure Master.JCasC.ConfigScripts but it requires inline scripts for all the jobs i want to configure using job DSL. It is resulting in a huge values.yaml. It would be great if we can seperate this out using a configMap.

**Comment by stevezau** [comment]
As an alternative i'm looking at using butler to import the jobs but would much prefer to use job dsl in a nicely formatted values.yaml

**Comment by maorfr** [comment]
feel free to get in on this discussion #11706
