### ISSUE TITLE
The plugins are not getting installed using the jenkins helm chart after setting the InstallPlugins in the values.yml

### ISSUE THREAD

**Issue by Sam123ben** [helm/charts#12519]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
kubectl version --short
Client Version: v1.10.0
Server Version: v1.11.8-eks-7c34c0

helm version --short
Client: v2.9.1+g20adb27
Server: v2.13.0+g79d0794

**Which chart**:
jenkins

**What happened**:
I set the InstallPlugins values with the right plugins as suggested in the README file. When I ran the helm chart command I was expecting my plugins to be installed as part of the jenkins pod creation but instead I don't see the plugins rather saw the old default plugins installed. I did set OverwritePlugins: true but still I don't get the new set of requested plugins to be installed. When I logged into the jenkins pod and tried to see the plugins.txt I can find the the file with the set of plugins I entered in my values.yml and then manually i can install the plugins using the plugins.sh script, which mean whatever plugins I set that worked as expected but not via helm chart during the bootstrap of the jenkins pod. I am again not sure if I had missed any param or property. 

I even tried using my own cutom docker image by 
```
FROM jenkins/jenkins:lts

COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt
```
And when I ran the helm chart using the "--set Master.Image=<my-image> --set Master.ImageTag=<my-image-tag> I still dont see the set of plugins I installed"

**What you expected to happen**:

I expect all the required plugins I have in my values.yml file should be getting installed in the jenkins app during the bootstrap of the same. If there any additional steps we need to do as part of the plugin installation then please do outline that in the readme file too.

**How to reproduce it** (as minimally and precisely as possible):

> helm upgrade --install jenkins --namespace tools stable/jenkins --set Master.NumExecutors=3 --set Master.JenkinsAdminEmail=devops@gmail.com --set Master.RunAsUser=1000 --set Master.FsGroup=1000 --set Master.ServiceType=ClusterIP --set Master.CLI=true --set Master.ingress.enabled=true --set Master.ingress.hostName=jenkins.tools.***.com --set rbac.install=true --set Persistence.Size=30Gi --set backup.enabled=true --set backup.destination=s3://nonprod-vlocity-xom-restore-backup/jenkins --set Master.UseSecurity=false --set Master.ContainerEnv\[0\].name=FLAVOUR_TYPE --set Master.ContainerEnv\[0\].value=a --set Master.ContainerEnv\[1\].name=REGION_NAME --set Master.ContainerEnv\[1\].value=ap-southeast-2 --set Master.ContainerEnv\[2\].name=ENVIRONMENT_NAME --set Master.ContainerEnv\[2\].value=nonprod --set Master.ContainerEnv\[3\].name=PROJECT_NAME --set Master.ContainerEnv\[3\].value=vlocity --set Master.ContainerEnv\[4\].name=PIPELINE_ELASTICSEARCH_HOST --set Master.ContainerEnv\[4\].value=elasticsearch-client --set Master.ContainerEnv\[5\].name=KUBERNETES_NAMESPACE --set Master.ContainerEnv\[5\].value=tools --set Master.OverwritePlugins=true -f helm-values/jenkins/values.yml

**Anything else we need to know**:

**Comment by Sam123ben** [comment]
```
sh apply_config.sh
cp: overwrite '/var/jenkins_home/config.xml'? cp: overwrite '/var/jenkins_home/jenkins.CLI.xml'? cp: overwrite '/var/jenkins_home/jenkins.model.JenkinsLocationConfiguration.xml'? Creating initial locks...
mkdir: cannot create directory ‘/usr/share/jenkins/ref/plugins/echo $(cat /var/jenkins_home/plugins.txt).lock’: No such file or directory
cp: cannot stat '/usr/share/jenkins/ref/plugins/*': No such file or directory
```

**Comment by Sam123ben** [comment]
If I execute the above script manually from the container/pod then its failing as above. Can anyone please update me on this please?

**Comment by maorfr** [comment]
@erihanse, seems that this is related to #12338.
would you mind taking a look?

**Comment by erihanse** [comment]
Hm.. Haven't tried with many different combinations. All I can say is that I'm running fine with these values: 
```
    # OverwritePlugins: true
    InstallPlugins:
    - kubernetes:1.14.3
    - workflow-aggregator:2.5
    - workflow-job:2.31
    - credentials-binding:1.17
    - git:3.9.3
    - github-branch-source:2.4.2
    - pipeline-utility-steps:2.2.0
    - role-strategy:2.9.0
    - http_request:1.8.22
    CSRF:
      DefaultCrumbIssuer:
        Enabled: true
        ProxyCompatability: false
    JCasC:
      enabled: true
```

**Comment by srflaxu40** [comment]
Same here @Sam123ben any luck?

**Comment by srflaxu40** [comment]
Tried this with clean checkout....  Same difference.

**Comment by srflaxu40** [comment]
I was able to get this to work with an older version of the chart and version 2.87

**Comment by torstenwalter** [comment]
Which chart version caused the problem and which chart version worked?

**Comment by rajeshkannank** [comment]
Same problem here. I am using below version
Server : 2.13.1
Client : 2.13.1 

It's not installing additional plugins.. Its taking only default plugin only.

**Comment by torstenwalter** [comment]
Is your Jenkins instance behind a proxy server or firewall which could prevent internet connectivity?

**Comment by rajeshkannank** [comment]
Hi,
Manually i am able to install the jenkins plugin usings managed jenkins. But via helm chart its not installing the any plugin.

**Comment by torstenwalter** [comment]
Can you provide a minimal values.yaml to reproduce the issue?
Which chart version are you using?

**Comment by rajeshkannank** [comment]
i am using chat version 1.1.11
i tried with minimal value, below is the values mentioned in values.yaml file
master:
  
  adminPassword: admin
  # node port <to set explicitly, choose port between 30000-32767
  nodePort: 31234
  # List of plugins to be install during Jenkins master start
  installPlugins:
    - kubernetes:1.14.0
    - workflow-job:2.31
    - workflow-aggregator:2.6
    - credentials-binding:1.17
    - git:3.9.1
    - active-directory:2.60.3
    - ansible:1.596.1
    - ansicolor:2.145
    - artifactory:1.642.3
    - blueocean:2.121.1
    - gerrit-code-review:2.54
    - ldap:1.651.3
    - sonar-gerrit:1.625.3
    - sonar-quality-gates:2.89.3
    - sonar:2.89.4
    - ssh:1.609.3
    - ssh-credentials:2.73.3

installaing below plugins, but not installed other plugin mentioned above list
    - kubernetes:1.14.0
    - workflow-job:2.31
    - workflow-aggregator:2.6
    - credentials-binding:1.17
    - git:3.9.1

**Comment by rajeshkannank** [comment]
Aplologies.. my bad plugin version..after mention correct jenkins plugin version.. its working as expected..

Thanks for help

**Comment by torstenwalter** [comment]
Thanks for the feedback.

**Comment by jeisen** [comment]
I am having the same issue. My values.yaml:

```
master:
  installPlugins:
    - kubernetes:1.15.6
    - workflow-job:2.32
    - workflow-aggregator:2.6
    - credentials-binding:1.19
    - git:3.10.0
    - blueocean:1.16.0
    - prometheus:2.0.4
    - google-login:2.60.1
```

But when I look at the configmap that's created:
```
plugins.txt:
----
kubernetes:1.12.4
workflow-job:2.24
workflow-aggregator:2.5
credentials-binding:1.16
git:3.9.1
```
