### ISSUE TITLE
[stable/elastic-stack] pod elasticsearch-data-0 fail to start with Exec lifecycle hook ([/bin/bash /post-start-hook.sh])

### ISSUE THREAD

**Issue by abramovi** [helm/charts#12523]
**Version of Helm and Kubernetes**:
K8s version - {Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
[**elastic-stack**]

**What happened**:
the pod - fail with the following error:

>  Exec lifecycle hook ([/bin/bash /post-start-hook.sh]) for Container "elasticsearch" in Pod "efk-elasticsearch-data-0_default(8784be5c-4fa0-11e9-a453-06baf87ff184)" failed - error: command '/bin/bash /post-start-hook.sh' exited with 137: , message: ""

and when I check the pod log - I see the following :

> [2019-03-26T08:31:36,383][INFO ][o.e.b.BootstrapChecks    ] [efk-elasticsearch-data-0] bound or publishing to a non-loopback address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed
[1]: max file descriptors [8192] for elasticsearch process is too low, increase to at least [65536]

**Comment by dennisotugo** [comment]
This issue is very valid
