### ISSUE TITLE
[stable/odoo] Cannot retrieve existing PVC

### ISSUE THREAD

**Issue by chevalier-m** [helm/charts#12536]
Hello.

The chart doesn't include the possibility of selecting and claiming an existing persistent volume. It _needs_ to be created when you bootstrap the chart at the same time.

On the opposite, I would like to have the possibility of claiming PVCs (for both the odoo volume and the postgre one). Indeed, I use PV backup mechanisms, and I would like the restoring to happen flawlessly, i.e me filling up a persistent volume, and claim it once it's complete from the values file, and then having the Odoo just the way it was.

Thank you for your attention.

**Comment by juan131** [comment]
Hi @mumrau 

For PostgreSQL we already have this feature (see `persistence.existingClaim` at https://github.com/helm/charts/tree/master/stable/postgresql#Configuration). 

Regarding Odoo, I just created a new PR to add support to this feature. Thanks for reporting it.

**Comment by juan131** [comment]
Hi @mumoshu 

We just merged the changes and you should be able to use an existing PVC in the Odoo chart from version **6.2.0** on.
