### ISSUE TITLE
Collaborators for Atlantis

### ISSUE THREAD

**Issue by lkysow** [helm/charts#12531]
Please add @jkodroff @jeff-knurek and @anubhavmishra to this repo as collaborators so they can help maintain the `stable/atlantis` chart (https://github.com/helm/charts/blob/master/stable/atlantis/OWNERS)

**Comment by lkysow** [comment]
@unguiculus sorry to ping you directly but it looks like you were the one who invited me originally to the `helm/charts` organization. We had a [previous ticket](https://github.com/helm/charts/issues/10500) open to add the remaining folks as collaborators that never got resolved so I'm not sure the best way to move this forward.

**Comment by mattfarina** [comment]
They have been invited.
