### ISSUE TITLE
[stable/rabbitmq] fix logs when address_type: hostname is enabled

### ISSUE THREAD

**Issue by madushan1000** [helm/charts#12558]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Version of Helm and Kubernetes**: helm v2.12.1 / k8s 1.10.11

**Which chart**: stable/rabbitmq

**What happened**: logs dissaper when `address_type` is set to `hostname`. This happens because rabbitmq renames the log files to `{hostname}-....log` insted of `{pod-ip}-....log`. and the `{pod-ip}-....log` is manually linked to stdout in the startup command insted of using the built in rabbitmq method to pipe logs to stdout (passing `RABBITMQ_LOGS=-` in the env vars)

**What you expected to happen**: logs should still be printed to the console/stdout

**How to reproduce it** (as minimally and precisely as possible): set 
```
   clustering:
      address_type: hostname
```

**Anything else we need to know**: I would create a PR for this but several PR's I made to the charts repo hasn't even got any feedback. So I'm making an issue.

**Comment by tompizmor** [comment]
Hi @madushan1000,

I am working on a PR for this issue. I will just add a new value to specify the value of the RABBITMQ_LOGS env var and it will be `-` by default.

>I would create a PR for this but several PR's I made to the charts repo hasn't even got any feedback 

Regarding the above message, Bitnami has some support automation around Bitnami maintained charts and we try to review them daily. If you have made any contribution to a Bitnami maintained chart and you didn't have any response, could you let me know? It might be an issue in the support system.

**Comment by madushan1000** [comment]
I don't think I have tried to contribute to any bitnami charts before. So I don't think it's related to your support system.

**Comment by tompizmor** [comment]
OK! Thanks for the response! 

The PR https://github.com/helm/charts/pull/12659 has been already merged so the log issue should be fixed.

Also, this other PR https://github.com/helm/charts/pull/12677 is pending to be reviewed. Once it is merged, the cluster address_type will be hostname.

**Comment by rakeshnambiar** [comment]
@tompizmor @madushan1000  I am using the `stable/rabbitmq-ha` chart and in the `values.yaml` I set the value `logs: /var/lib/rabbitmq/logs` with and without single quotes. But when I run the `printenv` command the value is always `-`. 

Chat version - `rabbitmq-ha-1.46.4`
App version - `3.8.5`
