### ISSUE TITLE
[stable/efs-provisioner] add support for mounting with IP

### ISSUE THREAD

**Issue by kszalontai** [helm/charts#12585]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm v2.12.1
K8S v1.12.5-gke.5

**Which chart**: 
efs-provisioner

**What happened**:
I'd like to mount my EFS from outside my AWS VPC, but it's only possible with the IP address [see this](https://docs.aws.amazon.com/efs/latest/ug/efs-onpremises.html#wt5-step3-connect)

The chart currently supports efsFileSystemId so I can't use for the above scenario.

**Comment by garnold54** [comment]
This would also be very useful for us. It looks like the efs provisioner did add support for arbitrary DNS names which also works with IP addresses: https://github.com/kubernetes-incubator/external-storage/issues/422

If this chart could be extended to support that new env var then it would support IP address mounting.
