### ISSUE TITLE
Unable to deploy Redis chart in minikube

### ISSUE THREAD

**Issue by naveensrinivasan** [helm/charts#1259]
**Is this a request for help?**:
Yes, What is the workaround?
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
Helm Version
`helm version
Client: &version.Version{SemVer:"v2.3.1", GitCommit:"32562a3040bb5ca690339b9840b6f60f8ce25da4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.3.1", GitCommit:"32562a3040bb5ca690339b9840b6f60f8ce25da4", GitTreeState:"clean"}`

**Which chart**:
`redis-0.6.0`

**What happened**:
Redis Container does not start.
This is the error.
```
nami    INFO  redis successfully initialized
INFO  ==> Starting redis...
INFO  ==> Starting redis-server...
45:C 07 Jun 14:48:25.127 # Can't chdir to '/opt/bitnami/redis/data': Permission denied
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
In minikube OSX
`helm install  --set metrics.enable=true --name=redis  stable/redis`
**Anything else we need to know**:
This works in the AWS env but does not work in minikube

**Comment by ShahNewazKhan** [comment]
I am also having this same issue, trying to deploy redis-0.7.0 in minikube Ubuntu.

The same chart boots up fine in a GCP Container Engine K8s Node.

**Comment by bnelz** [comment]
This is an issue with Virtualbox shared mounts and I'm struggling a bit with these myself. Some reading that may help: https://github.com/kubernetes/minikube/issues/2

**Comment by ShahNewazKhan** [comment]
I was able to resolve this by deleting the k8s Redis persistance volume claim:

```
kubectl get pvc
NAME                               STATUS    VOLUME                                     CAPACITY   ACCESSMODES   AGE
dev-redis                          Bound     pvc-bf5a38f9-771d-11e7-8ef3-5254006c691d   8Gi        RWO           21m
```
```
kubectl delete pvc dev-redis
persistentvolumeclaim "dev-redis" deleted
```
As per the charts/stable/redis README:



The Bitnami Redis image stores the Redis data and configurations at the /bitnami/redis path of the container.

By default, the chart mounts a Persistent Volume volume at this location. The volume is created using dynamic volume provisioning. If a Persistent Volume Claim already exists, specify it during installation.
Existing PersistentVolumeClaim

    Create the PersistentVolume
    Create the PersistentVolumeClaim
    Install the chart

`$ helm install --set persistence.existingClaim=PVC_NAME redis`
