### ISSUE TITLE
[stable/external-dns] RFC2136: can not deploy with insecure flag

### ISSUE THREAD

**Issue by ChristianMoesl** [helm/charts#12596]
Hello!

This is a bug report regarding stable/external-dns.

I tried to deploy external-dns using the RFC2136 provider without TSIG (-> without authentication). So I read the [documentation of the chart](https://github.com/helm/charts/tree/master/stable/external-dns)  and disabled the `rfc2136.tsigKeyname` key as stated in there. After deploying this, I realised, that the application has started with the flag `--rfc2136-insecure=false`, which is exactly the opposite, of what it says in the documentation.

[The problematic piece of code:](https://github.com/helm/charts/blob/2fc288f1b2ad095d5b6dd0b60f9a3a16f663b049/stable/external-dns/templates/deployment.yaml#L96)
```
          {{- if eq .Values.provider "rfc2136" }}
            - --rfc2136-host={{ required "rfc2136.host must be supplied for provider 'rfc2136'" .Values.rfc2136.host }}
            - --rfc2136-port={{ .Values.rfc2136.port }}
            - --rfc2136-zone={{ required "rfc2136.zone must be supplied for provider 'rfc2136'" .Values.rfc2136.zone }}
            {{- if .Values.rfc2136.tsigKeyname }}
            - --rfc2136-tsig-secret-alg={{ .Values.rfc2136.tsigSecretAlg }}
            - --rfc2136-tsig-keyname={{ .Values.rfc2136.tsigKeyname }}
              {{- if .Values.rfc2136.tsigAxfr }}
            - --rfc2136-tsig-axfr
              {{- end }}
            {{- else }}
            - --rfc2136-insecure=false
            {{- end }}
          {{- end }}
```

**Comment by niriak** [comment]
Not sure if it belongs to this ticket: "--rfc2136-insecure=false" fails with "flag parsing error: unexpected false". Should be "--rfc2136-insecure" only without any value?

**Comment by ChristianMoesl** [comment]
Right, it's a bug. You can not start external-dns in "insecure" mode with this helm chart.

**Comment by ChristianMoesl** [comment]
The fix seems kind of simple: https://github.com/helm/charts/pull/12598/commits/8364ae405c2fe1964bab4f5e9cd3206225fb7a39
