### ISSUE TITLE
Postgres node failures and recovery

### ISSUE THREAD

**Issue by vladan-jovicic** [helm/charts#12632]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**: helm v2.12.2 / k8s 1.11.5

**Which chart**: stable/postgresql

**What happened**: What is the best practice to promote standby node to master?
Detailed description: I have a kubernetes cluster with two nodes across different fault/update domains and I would like to perform several tests with different failure scenarios.
The postgres master node is running on, say, node-0, and slave node is running on node-1.
A stateless service S is scheduled on one of nodes and has single connection string - one which points to the service of master node.
When node-0 dies, S becomes unstable since it can not connect to database. I would like to promote the running standby node to master node and avoid changing connection string in S. When node-0 recovers, I would like to promote back postgres node running on node-0 to master. The best approach I could think off so far is

1) Promote the standby node to master using pg_ctl
2) Update service of dead master node to point to new master node
3) Once when node-0 is live again, promote it to slave node and do backup

Is this a correct approach? Is there a better one (in terms of sum of downtime)? Should I rather work on recovering the dead node ?

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by javsalgar** [comment]
Hi,

Your approach makes sense to me. Unfortunately, we do not currently have an automated approach to do so, so you would need to perform these steps manually. It would be extremely helpful for us to know more details about your use case. Have you faced this issue in the past? Is it part of your testing pipeline?
