### ISSUE TITLE
[stable/jenkins] support for secrets

### ISSUE THREAD

**Issue by arielkung** [helm/charts#1263]
Customizing configmap is a great feature of the Jenkins chart that allows to modify configuration and the behaviour of apply_config.sh

However it would be much better if the deployment mounted also a secret (even if it's empty by default) and that secret could also be customized like the configmap.

That way apply_comfig.sh can create secrets / set secret values in config without having them plain in configmaps.

Use case:
apply_config.sh can set $JENKINS_HOME/secrets/master.key and $JENKINS_HOME/secrets/hudson.util.Secret so jenkins secrets can be generated on install/upgrade time setting the encrypted value.
So you can even deploy / recreate a fully working jenkins instance with google login and a pipeline including jobs with secrets without manual interaction.

**Comment by lachie83** [comment]
@arielkung this sounds good to me. Can you put together a PR? Happy to review

**Comment by arielkung** [comment]
Sure I'll do it.

**Comment by lachie83** [comment]
Great! Thanks

**Comment by ChrisCooney** [comment]
We've ran into this issue too! Would be good to be able to do this.
