### ISSUE TITLE
[stable/jenkins] How to create new users

### ISSUE THREAD

**Issue by marcelloromani** [helm/charts#12644]
**Is this a request for help?**: Yes

**Version of Helm and Kubernetes**:
$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.13-eks-g484b8", GitCommit:"484b857e3134d55ac6373fea2f51798fefa0533f", GitTreeState:"clean", BuildDate:"2019-03-08T05:32:36Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
[stable/jenkins]
Chart version reported by `helm list`: `jenkins-0.36.0`

**What happened**:
I am able to log in to jenkins as user `admin` (I get get the password via `kubectl get secret`).

I would like to configure new, non-admin users in order to then apply `Role-Based Strategy` security.

The Security realm option is set to `Delegate to servlet container`
How do I add users when this setting is active?

PS: I have tried selecting "Jenkins' own user database" but that kicks me out of the server and I can't log in any more.

**Comment by maorfr** [comment]
That is a good question. I don't think that the chart currently supports this use case.
Will you not prefer (if possible of course) to delegate authentication to github/gitlab/other where you manage your code?

**Comment by marcelloromani** [comment]
At the moment it says "delegate to servlet container" so I was wondering if that "fetched" users from the underlying Kubernetes cluster.

The gitlab/github option is interesting.

**Comment by maorfr** [comment]
I encourage you to go ahead and submit a PR if you like ;)

And that it a super cool plugin, didn't know it!

**Comment by shake76** [comment]
Were you able to find a solution for this? I'm looking for the same

**Comment by marcelloromani** [comment]
I am testing the GitLab authentication plugin.

**Comment by leonyi** [comment]
> At the moment it says "delegate to servlet container" so I was wondering if that "fetched" users from the underlying Kubernetes cluster.
> On second look it seems this plugin is a good answer to that question: https://jenkinsci.github.io/kubernetes-credentials-provider-plugin/
> 
> For gitlab there's the gitLab authentication plugin.
> 
> I am starting to see an answer to my own question: the chart is only responsible for bootstrapping the Jenkins server with an admin account.
> 
> Auth/Authz is down to user preferences by using available plugins to integrate with auth providers.
> 
> The only thing I would document is that if you switch to "Jenkins's own internal database" you lock yourself out because by default that db is not initialised.

**Comment by leonyi** [comment]
@marcelloromani how did manage to manage your users auth using the kubernetes-credentials-provider-plugin? I am running Jenkins on GKE (using the stable/jenkins chart).  I couldn't find the plugin, I am running Jenkins 2.176.2.  Feedback is appreciated!

**Comment by marcelloromani** [comment]
Hi @leonyi 
we eventually installed the GitLab plugin and configured it to delegate authentication to GitLab.

I have not had time to work with the k8s credentials plugin since, sorry :)

**Comment by kosfist** [comment]
You can install Role-based Authorization Strategy plugin and activate jenkins db users (realms) + Role-Based Strategy (authentication).
This steps allowed me to create new admin user and other users.
