### ISSUE TITLE
Slave pods being assigned Emptydir volume

### ISSUE THREAD

**Issue by Avik1993** [helm/charts#12663]
**Is this a request for help?**:
yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
2.12.0
K8s: 1.13

**Which chart**:
stable/redis

**What happened**:
Slave being deployed as Deployment not StatefulSet. Any way to change that to StatefulSet.
Also, what could be the way to mention PVC name for Slaves? Right not EmptyDir is being assigned to Slaves. 
Master is being deployed as STS with correct PVC as mentioned under 'persistent' field in values.yaml

**What you expected to happen**:
Would like to link slaves to particular PVC (Mounted as NFS server on one of the nodes in cluster)

**How to reproduce it** (as minimally and precisely as possible):
Create NFS PV and pvc and install redis chart with persistence enabled and mention PVC name.

**Anything else we need to know**:

**Comment by juan131** [comment]
Someone opened a similar issue at bitnami/charts repo some time ago: https://github.com/bitnami/charts/issues/1109

As I mentioned on that issue:

> The slaves on this solution are read-only and they don't persist the data. It's a matter of design in the chart.

Slaves just replicate the data available at master nodes so it's not necessary to persist it on them.

Slaves are not meant to persist any data and, therefore, the emptyDir volumes are fine. For the same reason, we don't need to use a statefulset for slaves either.

**Comment by Avik1993** [comment]
sounds logical. I cross checked for multiple keys, seem to work.
Thanks
