### ISSUE TITLE
[stable/concourse] Setting web replicas doesn't work

### ISSUE THREAD

**Issue by elsmorian** [helm/charts#12667]
## BUG REPORT

**Version of Helm and Kubernetes**: Helm v2.13.0, K8s v1.12.6-gke.7

**Which chart**: stable/concourse

**What happened**: Changing the number of web replicas in the values.yaml file does not change the number in k8s.

**What you expected to happen**: changing the value in the values.yaml to be detected and altered in the k8s cluster

**How to reproduce it** try to change the number of web replicas set in the values calm and then upgrade the provisioning and see this value doesn't seem to change.

**Anything else we need to know**:

Having some trouble with the Concourse Helm chart -  we can scale the worker replicas fine, update in the `values.yaml` and do a `helm upgrade` and that works well. However we cannot do the same with the web replicas!
The upgrade just ignores whatever we set the replicas to. Its not a K8s issue as we can manually poke the deployment and scale the web replicas by editing the deployment directly.

I think there's a bug with the templating - running a `helm template` check on templates/web-deployment.yaml shoes the web.replicas value from the values.yaml  is not passed in or updated, though the worker.replicas is passed in to templates/worker-statefulset.yaml  and is updated fine. I had a quick look and couldn't see anything obviously wrong with the templating set in the deployment yaml.

**Comment by cirocosta** [comment]
Hi @elsmorian !

Sorry for the long delay, and thanks for the feedback!

Would you mind sharing a sample `values.yaml` where that happened?

Looking at the latest version of the Chart (`6.1.0`), I can see the value changing accordingly:

```
helm template . -x ./templates/web-deployment.yaml | grep replicas
  replicas: 1
helm template --set=web.replicas=2 . -x ./templates/web-deployment.yaml | grep replicas
  replicas: 2
```

Thanks!

**Comment by cirocosta** [comment]
@pikesley, I noticed that you gave a thumbs up - are you having the same issue?

Thanks!

**Comment by elsmorian** [comment]
Apologies, this was caused by us overriding YAML dictionaries and it falling back to defaults, sorry!
