### ISSUE TITLE
mongodb add subPath to persistence like Redis

### ISSUE THREAD

**Issue by yianni-ververis** [helm/charts#12676]
It would be nice if there was a subpath in the persistence values like Redis. 

If there are many deployments sharing the same nfs, it is good have each to store their files in their directories

**Comment by yianni-ververis** [comment]
From Redis values
https://github.com/helm/charts/blob/master/stable/redis/values.yaml#L195

  persistence:
    enabled: true
    ## The path the volume will be mounted at, useful when using different
    ## Redis images.
    path: /data
    ## The subdirectory of the volume to mount to, useful in dev environments
    ## and one PV for multiple services.
    subPath: "Redis"

**Comment by juan131** [comment]
Hi @yianni-ververis 

Thanks for the suggestion! I just created a PR to address this feature.

**Comment by juan131** [comment]
Oops! That was for PostgreSQL! Doing it for MongoDB
