### ISSUE TITLE
Overriding Cassandra configuration

### ISSUE THREAD

**Issue by ghost** [helm/charts#12716]
**Is this a request for help?**:
Yes
---

**Version of Helm and Kubernetes**:

**Which chart**:
cassandra

**Description**:

Hi I am trying to use the cassandra chart and everything works perfectly.  The only issue I am having is trying to overide the cassandra.yml file so I can enable password authentication.  I have tried adding the config to the config section but that does not change anything.  There is a config override section which I assume is the way to go but unsure how I use it.  Can anyone help me out how I can use this chart to enable password authentication.

**Comment by MohammedFadin** [comment]
@simonmacklin have you figured it out? I'm having the same issue.

**Comment by g-dury** [comment]
@simonmacklin @MohammedFadin would be happy to know if you have a solution since I am facing the same issue?! Thanks!

**Comment by g-dury** [comment]
One workaround for you would be to rebuild the cassandra docker image with your new configuration:
https://github.com/docker-library/cassandra/tree/5b7eebbf4412cf8b1434cfe6430648c606cdd6de
and adding
`RUN echo "authenticator: PasswordAuthenticator" >> /etc/cassandra/cassandra.yaml`
in the Dockerfile, it is a bit dirty but it is working!
cheers

**Comment by MohammedFadin** [comment]
@g-dury Yes I did. I added a initContainers to copy past the custom configs. I can push and share the repo if you would like?

**Comment by g-dury** [comment]
@MohammedFadin That would be great! Cheers
