### ISSUE TITLE
rabbitmq node goes down randomly chart used rabbitmq-ha on AKS(1.12.6)

### ISSUE THREAD

**Issue by anoopswsib** [helm/charts#12730]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: KUBERNETES 1.12.6 helm version 2.13.1
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

**Which chart**:
rabbitmq-ha

**What happened**:
One of the rabbitmg node in a cluster randomly  goes down and then restart automatically every few hours. There is not much load on the system. The error in  logs is as follows:
2019-04-01 21:29:39.902 [info] <0.43.0> Application mnesia exited with reason: stopped
2019-04-01 21:29:41.221 [info] <0.287.0>
 Starting RabbitMQ 3.7.12 on Erlang 21.2.6

**What you expected to happen**:
All nodes should be up

**How to reproduce it** (as minimally and precisely as possible):
Install the helm chart and wait around 24 to 30 hours from installation time

**Anything else we need to know**:
I am using azure kubernetes service 1.12.6. Its happening in older version of charts as well

**Comment by fracasula** [comment]
I think I'm having the same issue. The secondary just goes down repeatedly right after the bootstrap is complete even though the pod is perfectly healthy, in fact it's not Kubernetes that is killing the pod. I spent some time investigating the chart code and it seems that a `on-start.sh` bash script gets executed every time at startup which appends its output to a log in a `/work-dir` folder. I grepped `on-start` in there and here's what I get:

```
mongodb@foodchain-backend-mongodb-replicaset-1:/work-dir$ grep -Rsin "on-start" log.txt 
1:[2019-04-02T08:26:45,706716338+00:00] [on-start.sh] Bootstrapping MongoDB replica set member: foodchain-backend-mongodb-replicaset-1
2:[2019-04-02T08:26:45,710914775+00:00] [on-start.sh] Reading standard input...
3:[2019-04-02T08:26:45,714422070+00:00] [on-start.sh] Skipping init mongod standalone script
4:[2019-04-02T08:26:45,716991788+00:00] [on-start.sh] Peers: foodchain-backend-mongodb-replicaset-0.foodchain-backend-mongodb-replicaset.foodchain.svc.cluster.local foodchain-backend-mongodb-replicaset-1.foodchain-backend-mongodb-replicaset.foodchain.svc.cluster.local
5:[2019-04-02T08:26:45,745360589+00:00] [on-start.sh] Starting a MongoDB replica
6:[2019-04-02T08:26:45,750323622+00:00] [on-start.sh] Waiting for MongoDB to be ready...
24:[2019-04-02T08:26:46,888299031+00:00] [on-start.sh] Retrying db.adminCommand('ping').ok on localhost
35:[2019-04-02T08:26:48,030713754+00:00] [on-start.sh] Retrying db.adminCommand('ping').ok on localhost
62:[2019-04-02T08:26:49,124455645+00:00] [on-start.sh] Retrying db.adminCommand('ping').ok on localhost
66:[2019-04-02T08:26:49,215711686+00:00] [on-start.sh] Initialized.
67:[2019-04-02T08:26:49,222225624+00:00] [on-start.sh] Checking if foodchain-backend-mongodb-replicaset-0.foodchain-backend-mongodb-replicaset.foodchain.svc.cluster.local is primary
72:[2019-04-02T08:26:49,452309549+00:00] [on-start.sh] Found primary: foodchain-backend-mongodb-replicaset-0.foodchain-backend-mongodb-replicaset.foodchain.svc.cluster.local
75:[2019-04-02T08:26:52,538916784+00:00] [on-start.sh] Waiting for replica to reach SECONDARY state...
79:[2019-04-02T08:26:52,614870243+00:00] [on-start.sh] ✓ Replica reached SECONDARY state.
80:[2019-04-02T08:26:52,620334018+00:00] [on-start.sh] MongoDB bootstrap complete
81:[2019-04-02T08:26:52,649779046+00:00] [on-start.sh] Shutting down MongoDB (force: true)...
```

I looked into that script and towards the end we get:

```bash
log "Peers: ${peers[*]}"
log "Starting a MongoDB replica"
mongod --config /data/configdb/mongod.conf --dbpath=/data/db --replSet="$replica_set" --port="${port}" "${auth_args[@]}" --bind_ip=0.0.0.0 2>&1 | tee -a /work-dir/log.txt 1>&2 &
pid=$!
trap shutdown_mongo EXIT

log "Waiting for MongoDB to be ready..."
```

Which corresponds to the output I get into the logs. Pay attention to the `shutdown_mongo` trap though, that is going to be executed when the script ends. Then at the very end of the `on-start.sh` script we get:

```bash
log "MongoDB bootstrap complete"
exit 0
```

Again it corresponds with my logs output. It looks to me that once the bootstrap is complete the script exits with a `0`. Since it exits the trap gets fired thus the instance gets shutdown.

Thoughts?

**Comment by steven-sheehy** [comment]
Not enough to go off of here. Check to see if Kubernetes is OOM killing it or if not enough CPU for health check to process. Try  increasing memory and CPU. Also adjust the rabbitmq memory watermark as appropriate.

**Comment by anoopswsib** [comment]
There is no OOM issue going on here. There is 500m cpu and 3500 mi memory assigned to limit and request assigned to the pod. At the time the pod went down, our monitoring tool showed only 181m cpu and around 150mb was being consumed by the rabbitmq pod. So clearly there was no issue with the memory or cpu on the kubernetes side. The memory watermark is set to about 8gb so that is not the issue going here.  I am attaching val
[values1.txt](https://github.com/helm/charts/files/3035898/values1.txt)
ues from values.yaml

## RabbitMQ application credentials
## Ref: http://rabbitmq.com/access-control.html
##
rabbitmqUsername: admin
rabbitmqPassword: xxxxxx

## RabbitMQ Management user used for health checks
managementUsername: management
managementPassword: xxxxxx

## Place any additional key/value configuration to add to rabbitmq.conf
## Ref: https://www.rabbitmq.com/configure.html#config-items
extraConfig: |
#  queue_master_locator = min-masters

## Place advanced.config file in /etc/rabbitmq/advanced.config
## Ref: https://www.rabbitmq.com/configure.html#advanced-config-file
advancedConfig: |

## Definitions specification within the secret, will always be mounted
## at /etc/definitions/defintions.json
definitionsSource: definitions.json

## Place any additional plugins to enable in /etc/rabbitmq/enabled_plugins
## Ref: https://www.rabbitmq.com/plugins.html
extraPlugins: |
  rabbitmq_shovel,
  rabbitmq_shovel_management,
  rabbitmq_federation,
  rabbitmq_federation_management,

definitions:
  users: |-
#   {
#     "name": "myUsername",
#     "password": "myPassword",
#     "tags": "administrator"
#   }
  vhosts: |-
#   {
#     "name": "/rabbit"
#   }
  parameters: |-
#   {
#     "value": {
#       "src-uri": "amqp://localhost",
#       "src-queue": "source",
#       "dest-uri": "amqp://localhost",
#       "dest-queue": "destination",
#       "add-forward-headers": false,
#       "ack-mode": "on-confirm",
#       "delete-after": "never"
#     },
#     "vhost": "/",
#     "component": "shovel",
#     "name": "test"
#   }
  permissions: |-
#   {
#     "user": "myUsername",
#     "vhost": "/rabbit",
#     "configure": ".*",
#     "write": ".*",
#     "read": ".*"
#   }
  queues: |-
#    {
#       "name":"myName",
#       "vhost":"/rabbit",
#       "durable":true,
#       "auto_delete":false,
#       "arguments":{}
#    }
  exchanges: |-
#    {
#       "name":"myName",
#       "vhost":"/rabbit",
#       "type":"direct",
#       "durable":true,
#       "auto_delete":false,
#       "internal":false,
#       "arguments":{}
#    }
  bindings: |-
#    {
#       "source":"myName",
#       "vhost":"/rabbit",
#       "destination":"myName",
#       "destination_type":"queue",
#       "routing_key":"myKey",
#       "arguments":{}
#    }
## Sets the policies in definitions.json. This can be used to control the high
## availability of queues by mirroring them to multiple nodes.
## Ref: https://www.rabbitmq.com/ha.html
  policies: |-
#    {
#      "name": "ha-all",
#      "pattern": ".*",
#      "vhost": "/",
#      "definition": {
#        "ha-mode": "all",
#        "ha-sync-mode": "automatic",
#        "ha-sync-batch-size": 1
#      }
#    }


## RabbitMQ default VirtualHost
## Ref: https://www.rabbitmq.com/vhosts.html
##
rabbitmqVhost: "/"

## Erlang cookie to determine whether different nodes are allowed to communicate with each other
## Ref: https://www.rabbitmq.com/clustering.html
##
rabbitmqErlangCookie: secretcookie

## RabbitMQ Memory high watermark
## Ref: http://www.rabbitmq.com/memory.html
##
rabbitmqMemoryHighWatermark: 8192MB
rabbitmqMemoryHighWatermarkType: absolute

## EPMD port for peer discovery service used by RabbitMQ nodes and CLI tools
## Ref: https://www.rabbitmq.com/clustering.html
##
rabbitmqEpmdPort: 4369

## Node port
rabbitmqNodePort: 5672

## Manager port
rabbitmqManagerPort: 15672

## Set to true to precompile parts of RabbitMQ with HiPE, a just-in-time
## compiler for Erlang. This will increase server throughput at the cost of
## increased startup time. You might see 20-50% better performance at the cost
## of a few minutes delay at startup.
rabbitmqHipeCompile: false

## SSL certificates
## Red: http://www.rabbitmq.com/ssl.html
rabbitmqCert:
  enabled: false

  # Specifies an existing secret to be used for SSL Certs
  existingSecret: ""

  ## Create a new secret using these values
  cacertfile: |
  certfile: |
  keyfile: |

## Extra volumes for statefulset
extraVolumes: []

## Extra volume mounts for statefulset
extraVolumeMounts: []

## Authentication mechanism
## Ref: http://www.rabbitmq.com/authentication.html
rabbitmqAuth:
  enabled: false

  config: |
    # auth_mechanisms.1 = PLAIN
    # auth_mechanisms.2 = AMQPLAIN
    # auth_mechanisms.3 = EXTERNAL

## Automatic Partition Handling Strategy (split brain handling)
## Ref: https://www.rabbitmq.com/partitions.html#automatic-handling
## Note: pause-if-all-down is not supported without using a custom configmap since it requires extra
## configuration.

rabbitmqClusterPartitionHandling: autoheal

## Authentication backend
## Ref: https://github.com/rabbitmq/rabbitmq-auth-backend-http
rabbitmqAuthHTTP:
  enabled: false

  config: |
    # auth_backends.1 = http
    # auth_http.user_path     = http://some-server/auth/user
    # auth_http.vhost_path    = http://some-server/auth/vhost
    # auth_http.resource_path = http://some-server/auth/resource
    # auth_http.topic_path    = http://some-server/auth/topic

## LDAP Plugin
## Ref: http://www.rabbitmq.com/ldap.html
rabbitmqLDAPPlugin:
  enabled: false

  ## LDAP configuration:
  config: |
    # auth_backends.1 = ldap
    # auth_ldap.servers.1  = my-ldap-server
    # auth_ldap.user_dn_pattern = cn=${username},ou=People,dc=example,dc=com
    # auth_ldap.use_ssl    = false
    # auth_ldap.port       = 389
    # auth_ldap.log        = false

## MQTT Plugin
## Ref: http://www.rabbitmq.com/mqtt.html
rabbitmqMQTTPlugin:
  enabled: false

  ## MQTT configuration:
  config: |
    # mqtt.default_user     = guest
    # mqtt.default_pass     = guest
    # mqtt.allow_anonymous  = true

## Web MQTT Plugin
## Ref: http://www.rabbitmq.com/web-mqtt.html
rabbitmqWebMQTTPlugin:
  enabled: false

  ## Web MQTT configuration:
  config: |
    # web_mqtt.ssl.port       = 12345
    # web_mqtt.ssl.backlog    = 1024
    # web_mqtt.ssl.certfile   = /etc/cert/cacert.pem
    # web_mqtt.ssl.keyfile    = /etc/cert/cert.pem
    # web_mqtt.ssl.cacertfile = /etc/cert/key.pem
    # web_mqtt.ssl.password   = changeme

## STOMP Plugin
## Ref: http://www.rabbitmq.com/stomp.html
rabbitmqSTOMPPlugin:
  enabled: false

  ## STOMP configuration:
  config: |
    # stomp.default_user = guest
    # stomp.default_pass = guest

## Web STOMP Plugin
## Ref: http://www.rabbitmq.com/web-stomp.html
rabbitmqWebSTOMPPlugin:
  enabled: false

  ## Web STOMP configuration:
  config: |
    # web_stomp.ws_frame = binary
    # web_stomp.cowboy_opts.max_keepalive = 10

## AMQPS support
## Ref: http://www.rabbitmq.com/ssl.html
rabbitmqAmqpsSupport:
  enabled: false

  # NodePort
  amqpsNodePort: 5671

  # SSL configuration
  config: |
    # listeners.ssl.default             = 5671
    # ssl_options.cacertfile            = /etc/cert/cacert.pem
    # ssl_options.certfile              = /etc/cert/cert.pem
    # ssl_options.keyfile               = /etc/cert/key.pem
    # ssl_options.verify                = verify_peer
    # ssl_options.fail_if_no_peer_cert  = false

## Number of replicas
replicaCount: 4

image:
  repository: rabbitmq
  tag: 3.7.12-alpine
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistrKeySecretName

busyboxImage:
  repository: busybox
  tag: latest
  pullPolicy: Always

## Duration in seconds the pod needs to terminate gracefully
terminationGracePeriodSeconds: 10

service:
  annotations: {}
  clusterIP: None

  ## List of IP addresses at which the service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: ClusterIP

  ## Customize nodePort number when the service type is NodePort
  ### Ref: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  ###
  epmdNodePort: null
  amqpNodePort: null
  managerNodePort: null

podManagementPolicy: OrderedReady

## Statefulsets rolling update update strategy
## Ref: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#rolling-update
##
updateStrategy: OnDelete

## Statefulsets Pod Priority
## Ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass
## priorityClassName: ""

## We usually recommend not to specify default resources and to leave this as
## a conscious choice for the user. This also increases chances charts run on
## environments with little resources, such as Minikube. If you do want to
## specify resources, uncomment the following lines, adjust them as necessary,
## and remove the curly braces after 'resources:'.
## If you decide to set the memory limit, make sure to also change the
## rabbitmqMemoryHighWatermark following the formula:
##   rabbitmqMemoryHighWatermark = 0.4 * resources.limits.memory
##
resources:
  requests:
    memory: 3500Mi
    cpu: 500m
  limits:
    memory: 3500Mi
    cpu: 500m
initContainer:
  resources: {}
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi

## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName:

## Data Persistency
persistentVolume:
  enabled: true
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  storageClass: managed-premium
  name: data
  accessModes:
    - ReadWriteOnce
  size: 100Gi
  annotations: {}

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
##
nodeSelector: {}

## Node tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
##
tolerations: []

## Extra Annotations to be added to pod
podAnnotations: {}

## Pod affinity
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
podAntiAffinity: soft

## Create default configMap
##
existingConfigMap: false

## Add additional labels to all resources
##
extraLabels: {}

## Role Based Access
## Ref: https://kubernetes.io/docs/admin/authorization/rbac/
##
rbac:
  create: true

## Service Account
## Ref: https://kubernetes.io/docs/admin/service-accounts-admin/
##
serviceAccount:
  create: true

  ## The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the fullname template
  # name:

ingress:
  ## Set to true to enable ingress record generation
  enabled: false

  path: /

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  ## hostName: foo.bar.com

  ## Set this to true in order to enable TLS on the ingress record
  tls: false

  ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
  tlsSecret: myTlsSecret

  ## Ingress annotations done as key:value pairs
  annotations:
  #  kubernetes.io/ingress.class: nginx

livenessProbe:
  initialDelaySeconds: 500
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  failureThreshold: 6
  initialDelaySeconds: 600
  timeoutSeconds: 3
  periodSeconds: 5

# Specifies an existing secret to be used for RMQ password and Erlang Cookie
existingSecret: ""


## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  fsGroup: 101
  runAsGroup: 101
  runAsNonRoot: true
  runAsUser: 100

prometheus:
  ## Configures Prometheus Exporter to expose and scrape stats.
  exporter:
    enabled: false
    env: {}
    image:
      repository: kbudde/rabbitmq-exporter
      tag: v0.29.0
      pullPolicy: IfNotPresent

    ## Port Prometheus scrapes for metrics
    port: 9090
    ## Comma-separated list of extended scraping capabilities supported by the target RabbitMQ server
    capabilities: "bert,no_sort"

    ## Allow overriding of container resources
    resources: {}
     # limits:
     #   cpu: 200m
     #   memory: 1Gi
     # requests:
     #   cpu: 100m
     #   memory: 100Mi

  ## Prometheus is using Operator.  Setting to true will create Operator specific resources like ServiceMonitors and Alerts
  operator:
    ## Are you using Prometheus Operator? [Blog Post](https://coreos.com/blog/the-prometheus-operator.html)
    enabled: false

    ## Configures Alerts, which will be setup via Prometheus Operator / ConfigMaps.
    alerts:
      ## Prometheus exporter must be enabled as well
      enabled: false

      ## Selector must be configured to match Prometheus Install, defaulting to whats done by Prometheus Operator
      ## See [CoreOS Prometheus Chart](https://github.com/coreos/prometheus-operator/tree/master/helm)
      selector:
        role: alert-rules
      labels: {}

    serviceMonitor:
      ## Interval at which Prometheus scrapes RabbitMQ Exporter
      interval: 10s

      # Namespace Prometheus is installed in
      namespace: monitoring

      ## Defaults to whats used if you follow CoreOS [Prometheus Install Instructions](https://github.com/coreos/prometheus-operator/tree/master/helm#tldr)
      ## [Prometheus Selector Label](https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/templates/prometheus.yaml#L65)
      ## [Kube Prometheus Selector Label](https://github.com/coreos/prometheus-operator/blob/master/helm/kube-prometheus/values.yaml#L298)
      selector:
        prometheus: kube-prometheus

## Kubernetes Cluster Domain
clusterDomain: cluster.local

**Comment by anoopswsib** [comment]
please provide yur feedback

**Comment by anoopswsib** [comment]
> Not enough to go off of here. Check to see if Kubernetes is OOM killing it or if not enough CPU for health check to process. Try increasing memory and CPU. Also adjust the rabbitmq memory watermark as appropriate.

There is no OOM issue going on here. There is 500m cpu and 3500 mi memory assigned to limit and request assigned to the pod. At the time the pod went down, our monitoring tool showed only 45m cpu and memory around 150mb was being consumed by the rabbitmq pod. So clearly there was no issue with the memory or cpu on the kubernetes side. The memory watermark is set to about 8gb so that is not the issue going here. I am attaching val
[values1.txt](https://github.com/helm/charts/files/3035912/values1.txt)

**Comment by pgdagenais** [comment]
I'm also getting this behavior with the rabbitmq-ha chart.

Cluster version: 1.11.7
Environment: AWS, self managed cluster with Kops
RabbitMQ Version: `RabbitMQ 3.7.13 on Erlang 21.3.2`

CPU and Memory usage is very stable, far from both limits.

Rabbitmq is restarting by itself. All of my 3 nodes does that with a 2-3 minutes interval.

Here is some bit of my logs before the restart:

```
[...]
2019-04-08 00:35:30.087 [info] <0.14557.0> connection <0.14557.0> (100.108.0.4:37276 -> 100.120.0.13:5672): user 'guest' authenticated and granted access to vhost '/'
2019-04-08 00:35:34.471 [info] <0.14154.0> closing AMQP connection <0.14154.0> (100.100.0.20:53388 -> 100.120.0.13:5672, vhost: '/', user: 'guest')
2019-04-08 00:35:45.280 [error] <0.14573.0> Timed out getting channel <0.14538.0> info
2019-04-08 00:35:52.259 [error] <0.14669.0> Timed out getting channel <0.14538.0> info
2019-04-08 00:35:59.290 [info] <0.14932.0> accepting AMQP connection <0.14932.0> (100.108.0.14:45238 -> 100.120.0.13:5672)
2019-04-08 00:35:59.334 [info] <0.14932.0> connection <0.14932.0> (100.108.0.14:45238 -> 100.120.0.13:5672): user 'guest' authenticated and granted access to vhost '/'
2019-04-08 00:35:59.381 [info] <0.14932.0> closing AMQP connection <0.14932.0> (100.108.0.14:45238 -> 100.120.0.13:5672, vhost: '/', user: 'guest')
2019-04-08 00:36:00.383 [error] <0.14776.0> Timed out getting channel <0.14538.0> info
2019-04-08 00:36:07.365 [error] <0.14844.0> Timed out getting channel <0.14538.0> info
2019-04-08 00:36:15.512 [error] <0.14954.0> Timed out getting channel <0.14538.0> info
2019-04-08 00:36:22.466 [error] <0.15036.0> Timed out getting channel <0.14538.0> info
2019-04-08 00:36:30.613 [error] <0.15148.0> Timed out getting channel <0.14538.0> info
2019-04-08 00:36:37.568 [error] <0.15215.0> Timed out getting channel <0.14538.0> info
2019-04-08 00:36:45.740 [error] <0.15309.0> Timed out getting channel <0.14538.0> info
2019-04-08 00:36:52.683 [error] <0.15397.0> Timed out getting channel <0.14538.0> info
2019-04-08 00:37:00.841 [error] <0.15491.0> Timed out getting channel <0.14538.0> info
2019-04-08 00:37:07.785 [error] <0.15559.0> Timed out getting channel <0.14538.0> info
Stopping and halting node rabbit@rabbitmq-ha-production-0.rabbitmq-ha-production-discovery.production.svc.cluster.local ...
2019-04-08 00:37:09.694 [info] <0.15669.0> RabbitMQ is asked to stop...
2019-04-08 00:37:09.779 [info] <0.15669.0> Stopping RabbitMQ applications and their dependencies in the following order:
    rabbitmq_shovel_management
    rabbitmq_federation_management
    rabbitmq_management
    rabbitmq_federation
    rabbitmq_shovel
    amqp_client
    rabbitmq_web_dispatch
    cowboy
    cowlib
    rabbitmq_consistent_hash_exchange
    rabbitmq_peer_discovery_k8s
    rabbitmq_peer_discovery_common
    rabbitmq_management_agent
    rabbit
    mnesia
    rabbit_common
    sysmon_handler
    os_mon
    amqp10_client
    amqp10_common
[...]
```

**Comment by anoopswsib** [comment]
> I'm also getting this behavior with the rabbitmq-ha chart.
> 
> Cluster version: 1.11.7
> Environment: AWS, self managed cluster with Kops
> RabbitMQ Version: `RabbitMQ 3.7.13 on Erlang 21.3.2`
> 
> CPU and Memory usage is very stable, far from both limits.
> 
> Rabbitmq is restarting by itself. All of my 3 nodes does that with a 2-3 minutes interval.
> 
> Here is some bit of my logs before the restart:
> 
> ```
> [...]
> 2019-04-08 00:35:30.087 [info] <0.14557.0> connection <0.14557.0> (100.108.0.4:37276 -> 100.120.0.13:5672): user 'guest' authenticated and granted access to vhost '/'
> 2019-04-08 00:35:34.471 [info] <0.14154.0> closing AMQP connection <0.14154.0> (100.100.0.20:53388 -> 100.120.0.13:5672, vhost: '/', user: 'guest')
> 2019-04-08 00:35:45.280 [error] <0.14573.0> Timed out getting channel <0.14538.0> info
> 2019-04-08 00:35:52.259 [error] <0.14669.0> Timed out getting channel <0.14538.0> info
> 2019-04-08 00:35:59.290 [info] <0.14932.0> accepting AMQP connection <0.14932.0> (100.108.0.14:45238 -> 100.120.0.13:5672)
> 2019-04-08 00:35:59.334 [info] <0.14932.0> connection <0.14932.0> (100.108.0.14:45238 -> 100.120.0.13:5672): user 'guest' authenticated and granted access to vhost '/'
> 2019-04-08 00:35:59.381 [info] <0.14932.0> closing AMQP connection <0.14932.0> (100.108.0.14:45238 -> 100.120.0.13:5672, vhost: '/', user: 'guest')
> 2019-04-08 00:36:00.383 [error] <0.14776.0> Timed out getting channel <0.14538.0> info
> 2019-04-08 00:36:07.365 [error] <0.14844.0> Timed out getting channel <0.14538.0> info
> 2019-04-08 00:36:15.512 [error] <0.14954.0> Timed out getting channel <0.14538.0> info
> 2019-04-08 00:36:22.466 [error] <0.15036.0> Timed out getting channel <0.14538.0> info
> 2019-04-08 00:36:30.613 [error] <0.15148.0> Timed out getting channel <0.14538.0> info
> 2019-04-08 00:36:37.568 [error] <0.15215.0> Timed out getting channel <0.14538.0> info
> 2019-04-08 00:36:45.740 [error] <0.15309.0> Timed out getting channel <0.14538.0> info
> 2019-04-08 00:36:52.683 [error] <0.15397.0> Timed out getting channel <0.14538.0> info
> 2019-04-08 00:37:00.841 [error] <0.15491.0> Timed out getting channel <0.14538.0> info
> 2019-04-08 00:37:07.785 [error] <0.15559.0> Timed out getting channel <0.14538.0> info
> Stopping and halting node rabbit@rabbitmq-ha-production-0.rabbitmq-ha-production-discovery.production.svc.cluster.local ...
> 2019-04-08 00:37:09.694 [info] <0.15669.0> RabbitMQ is asked to stop...
> 2019-04-08 00:37:09.779 [info] <0.15669.0> Stopping RabbitMQ applications and their dependencies in the following order:
>     rabbitmq_shovel_management
>     rabbitmq_federation_management
>     rabbitmq_management
>     rabbitmq_federation
>     rabbitmq_shovel
>     amqp_client
>     rabbitmq_web_dispatch
>     cowboy
>     cowlib
>     rabbitmq_consistent_hash_exchange
>     rabbitmq_peer_discovery_k8s
>     rabbitmq_peer_discovery_common
>     rabbitmq_management_agent
>     rabbit
>     mnesia
>     rabbit_common
>     sysmon_handler
>     os_mon
>     amqp10_client
>     amqp10_common
> [...]
> ```

what is your readiness and liveness setting, more specifically initialDelaySeconds for both. Also are you using pvc? How much size have you specified? Default is 8g

**Comment by pgdagenais** [comment]
@anoopswsib default value for both the liveness and readiness.

I'm using a pvc with the default values also. 8gb of data, using less than 100mb on all 3.

**Comment by anoopswsib** [comment]
I would increase the initial delay seconds on liveness and readiness to about 500 and 600 respectively

Try it and see if you see any improvement

**Comment by pgdagenais** [comment]
@anoopswsib I don't see how that would help since I'm getting the error after my rabbitmq cluster has been running for a while.

The `initialDelaySeconds` configuration is only for the first probe when the container starts up, here is the definition:
> `initialDelaySeconds`: Number of seconds after the container has started before liveness or readiness probes are initiated.

**Comment by anoopswsib** [comment]
i know what you are saying but try it trust me :) u should see some relief

**Comment by anoopswsib** [comment]
> @anoopswsib I don't see how that would help since I'm getting the error after my rabbitmq cluster has been running for a while.
> 
> The `initialDelaySeconds` configuration is only for the first probe when the container starts up, here is the definition:
> 
> > `initialDelaySeconds`: Number of seconds after the container has started before liveness or readiness probes are initiated.

Sorry didnt your question properly. I have the same behavior as well. After running for a while I started having the issues. Mmeory is fine cpu limits is fine. Just the rabbit mq pods they restart automatically. I still dont know the root cause of the issue

**Comment by pgdagenais** [comment]
I increased the `rabbitmqMemoryHighWatermark` value to `512MB` (it was `256MB`) and rabbitmq has been running for more than 1 day and 20 hours now.

Thanks all

**Comment by anoopswsib** [comment]
> I increased the `rabbitmqMemoryHighWatermark` value to `512MB` (it was `256MB`) and rabbitmq has been running for more than 1 day and 20 hours without any issue.
> 
> Thanks all

I have set rabbitmqMemoryHighWatermark as 8192GB and still it restarts automatically after few days. Lets hope it solves your issues :) What kind of kubernetes service are you using? Is it it azure, google or installed by hand?

**Comment by anoopswsib** [comment]
> Not enough to go off of here. Check to see if Kubernetes is OOM killing it or if not enough CPU for health check to process. Try increasing memory and CPU. Also adjust the rabbitmq memory watermark as appropriate.



> Not enough to go off of here. Check to see if Kubernetes is OOM killing it or if not enough CPU for health check to process. Try increasing memory and CPU. Also adjust the rabbitmq memory watermark as appropriate.

Steven I am using as follows:
resources:
  requests:
    memory: 3500Mi
    cpu: 500m
  limits:
    memory: 3500Mi
    cpu: 500m

rabbitmqMemoryHighWatermark: 8192MB

are these good enough?

**Comment by steven-sheehy** [comment]
rabbitmqMemoryHighWatermark should be set to less than your container memory limit. You can also set rabbitmqMemoryHighWatermarkType to relative and put a percentage value like 0.7.

Your CPU might be a little low, but I don't know what's causing your particular problem. You probably need to enable more rabbitmq debugs and get help from the rabbitmq people.

**Comment by anoopswsib** [comment]
> rabbitmqMemoryHighWatermark should be set to less than your container memory limit. You can also set rabbitmqMemoryHighWatermarkType to relative and put a percentage value like 0.7.
> 
> Your CPU might be a little low, but I don't know what's causing your particular problem. You probably need to enable more rabbitmq debugs and get help from the rabbitmq people.

Thanks steven for your advice, currently I am using rabbitmqMemoryHighWatermarkType: absolute
which is default settings. My container limit is 3500mi, I can change the rabbitmqMemoryHighWatermark=2500 Mb which is around 70 percent. Let me try that and see if the problem goes away. Much appreciated!!!

**Comment by anoopswsib** [comment]
> > rabbitmqMemoryHighWatermark should be set to less than your container memory limit. You can also set rabbitmqMemoryHighWatermarkType to relative and put a percentage value like 0.7.
> > Your CPU might be a little low, but I don't know what's causing your particular problem. You probably need to enable more rabbitmq debugs and get help from the rabbitmq people.
> 
> Thanks steven for your advice, currently I am using rabbitmqMemoryHighWatermarkType: absolute
> which is default settings. My container limit is 3500mi, I can change the rabbitmqMemoryHighWatermark=2500 Mb which is around 70 percent. Let me try that and see if the problem goes away. I will bump up the cpu to 1 core as well
Much appreciated!!!

**Comment by anoopswsib** [comment]
> rabbitmqMemoryHighWatermark should be set to less than your container memory limit. You can also set rabbitmqMemoryHighWatermarkType to relative and put a percentage value like 0.7.
> 
> Your CPU might be a little low, but I don't know what's causing your particular problem. You probably need to enable more rabbitmq debugs and get help from the rabbitmq people.

would this be correct, steven?

rabbitmqMemoryHighWatermark: .7
rabbitmqMemoryHighWatermarkType: relative

resources:
  requests:
    memory: 3500Mi
    cpu: 500m
  limits:
    memory: 3500Mi
    cpu: 1000m

**Comment by steven-sheehy** [comment]
Might need the 0 and to quote it: `rabbitmqMemoryHighWatermark: "0.7"`

**Comment by anoopswsib** [comment]
right sir :) I learn new things every day. I am gonna try it in dev server first before going for uat. 

rabbitmqMemoryHighWatermark: "0.7"
rabbitmqMemoryHighWatermarkType: relative

for storage, I have following, is that good enough or should i bump up the storage gb. we are using azure kubernetes so my storage class is managed-premium

persistentVolume:
  enabled: true
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  storageClass: managed-premium
  name: data
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}

**Comment by steven-sheehy** [comment]
That completely depends upon your workload and how many messages/second, size of those messages, how fast consumers are pulling them off, etc.

**Comment by anoopswsib** [comment]
> That completely depends upon your workload and how many messages/second, size of those messages, how fast consumers are pulling them off, etc.

Thanks for recommendations, we dont have crazy workloads just normal workloads 30 messages/ per minute type of deal. I can double it or maybe set 30gb to be safe side. DoI need to change any other parameter if I make it 30 gb?

**Comment by bbratchiv** [comment]
I know it's outdated, but I faced same RabbitMQ nodes down situation. This happened every 24h. Turns out that the 
`rabbitmqctl list_queues` was timing out because of wrong node names. Fixing RabbitMQ node name to the same ones as in the cluster configuration fixed the issue.
