### ISSUE TITLE
[stable/jenkins] errors installing multiple Jenkins instances into same namespace

### ISSUE THREAD

**Issue by torstenwalter** [helm/charts#12741]
**BUG REPORT**

**Version of Helm and Kubernetes**:
helm:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/jenkins

**What happened**:

When installing two Jenkins instances in the same namespace while JCasC is enabled and configAutoReload as well. Then the sidecar container which does the autoreload mixes up the configurations of both instances.

**What you expected to happen**:

I expect that each Jenkins instance has it's own configuration and a change in one has no effect for the other.

**How to reproduce it** (as minimally and precisely as possible):

For testing purposes I installed two Jenkins instances into the same namespace. For both instances I set:
- Master.JCasC.enabled=true
- Master.Sidecars.configAutoReload.enabled=true

The second one has no welcome message (`--set Master.JCasC.ConfigScripts.welcome-message=""`)

```
helm install stable/jenkins -n jenkins1 --namespace torsten --set Master.JCasC.enabled=true,Master.Sidecars.configAutoReload.enabled=true,rbac.install=true,Persistence.Enabled=false

helm install stable/jenkins -n jenkins2 --namespace torsten --set Master.JCasC.enabled=true,Master.Sidecars.configAutoReload.enabled=true,rbac.install=true,Persistence.Enabled=false --set Master.JCasC.ConfigScripts.welcome-message=""
```

As expected each instance has it's own config map for the welcome-message.

```
$ kubectl get configmap --show-labels   
NAME                                      DATA   AGE   LABELS
jenkins-config-jenkins1-welcome-message   1      95s   chart=jenkins-0.36.2,component=jenkins1-jenkins-master,jenkins_config=true,release=jenkins1
jenkins-config-jenkins2-welcome-message   1      12s   chart=jenkins-0.36.2,component=jenkins2-jenkins-master,jenkins_config=true,release=jenkins2
jenkins1                                  6      95s   <none>
jenkins1-tests                            1      95s   <none>
jenkins2                                  6      12s   <none>
jenkins2-tests                            1      11s   <none>
```

We can confirm that the welcome message within the config file of jenkins2 is empty while the welcome message of jenkins1 still contains the message "Welcome to ..."
```
$ kubectl get configmap jenkins-config-jenkins1-welcome-message -o jsonpath='{.data.welcome-message\.yaml}'

$ kubectl get configmap jenkins-config-jenkins2-welcome-message -o jsonpath='{.data.welcome-message\.yaml}'
jenkins:
  systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.% 
```

The issue is that the sidecar container which reloads the config-maps reloads configuration from all config maps with label "jenkins_config" (Master.Sidecars.configAutoReload.label)

That means that a configuration change for one Jenkins instance influence the configuration of the other unrelated Jenkins instance.

One can confirm that by looking at the logs for the sidecar:

```
$ kubectl logs jenkins1-545778fd5f-brzwf -c jenkins-sc-config
2019-04-02 11:05:14 INFO     Working on configmap torsten/jenkins2
INFO:sidecar:Working on configmap torsten/jenkins2
2019-04-02 11:05:14 INFO     Working on configmap torsten/jenkins1
INFO:sidecar:Working on configmap torsten/jenkins1
```

As you can see the sidecar is working on configmaps from both instances.

**Anything else we need to know**:
I suggest to use `{{ template "jenkins.fullname" . }}` as part of the label to make it unique.  I am going to prepare a PR for that, but it's going to be a breaking change for people who used the label `jenkins_config: "true"` in configuration files not managed by the helm chart.

@holmesb any objections?

**Comment by holmesb** [comment]
> The issue is that the sidecar container which reloads the config-maps reloads configuration from all config maps with label "jenkins_config"
No objections.  I expected people would manually change the label if deploying another jenkins (so it is unique).  But your plan is better: default it to include the name of the release.
