### ISSUE TITLE
[stable/rabbitmq] better visibility on probes failure

### ISSUE THREAD

**Issue by thomas-riccardi** [helm/charts#12743]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?**: feature request

**Which chart**: `stable/rabbitmq`

**What happened**:
When a `readinessProbe` or `livenessProbe` fails, we don't have any explanation of what the failure is:
```
kubectl describe ...
Warning  Unhealthy               2m45s (x3 over 5m15s)  kubelet, xxx  Readiness probe failed: 
```

**What you expected to happen**:
When a probe fails, kubectl displays stdout and stderr of the `exec` probe: the probe command should simply print the `GET /api/healthchecks/node` output.

**Anything else we need to know**:
I am preparing a PR to fix this issue.

**Comment by juan131** [comment]
Thanks for reporting it! I just commented your PR @thomas-riccardi
