### ISSUE TITLE
[stable/traefik] Unable to generate certificates from LetsEncrypt

### ISSUE THREAD

**Issue by dblencowe** [helm/charts#12742]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
```bash
→ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

```bash
→ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```
**Which chart**:
stable/traefik, version 1.65.0

**What happened**:
I've tried configuring Traefik to generate LE certificates for several ingresses. Unfortunately no matter what combination of configuration options I try I'm unable to generate a certificate. The following output is generated in the container:
```json
{"level":"info","msg":"Using TOML configuration file /config/traefik.toml","time":"2019-04-02T08:54:00Z"}
{"level":"fatal","msg":"Unknown entrypoint \"https\" for ACME configuration","time":"2019-04-02T08:54:00Z"}
```

values.yaml:
```yaml
traefik:
  kubernetes:
    ingressEndpoint:
      useDefaultPublishedService: true
  acme:
    enabled: true
    email: "ops+dev@valid-email.com"
    staging: true
    logging: true
    challengeType: http-01
  debug:
    enabled: true
  rbac:
    enabled: true
```

Example Ingress:
```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-crm
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - {{ .Values.environment }}-{{ .Values.application }}.{{ .Values.rootDomain }}
  secretName: crm-tls-secret
  rules:
  - host: {{ .Values.environment }}-{{ .Values.application }}.{{ .Values.rootDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-service-nginx
          servicePort: 80
```

**What you expected to happen**:
Certificates to be generated for each ingress

**How to reproduce it** (as minimally and precisely as possible):
Using the above configs against the version of the chart specified above

**Anything else we need to know**:
I've tried several variations of the above in order to try get it working:

- Removing the secretName option from the TLS section
- Also specifying ssl.enabled: true
- Using the DNS-01 provider

**Comment by Lindenk** [comment]
I've had the same problem. Apparently `ssl` needs be turned on manually otherwise the challange will fail. Add this to your `values.yml`:

```yaml
ssl:
  enabled: true
```

**Comment by dblencowe** [comment]
Thanks @Lindenk, unfortunately I've already tried this and didn't get anywhere. I ended up installing helm/letsencrypt to the cluster to handle certificate generation.
