### ISSUE TITLE
[stable/keycloak] Upgrade to newer keycloak version

### ISSUE THREAD

**Issue by juv** [helm/charts#12754]
**Is this a request for help?**:
Yes
---

I am currently using the Helm chart `version: 4.6.1` and I want to upgrade to the newest one. When looking at the [documentation](https://www.keycloak.org/docs/5.0/upgrading/), there are a few steps needed to upgrade to the latest Keycloak version. What kind of upgrade process is needed when using this Helm chart?

**Comment by juv** [comment]
@unguiculus @thomasdarimont

**Comment by unguiculus** [comment]
The Keycloak chart here is being deprecated (#13316) and moved to a new home:
https://github.com/codecentric/helm-charts

I'm closing this issue. Feel free to open a new issue in the new repo. Thanks.
