### ISSUE TITLE
Missing Credentials Error when using awsRole

### ISSUE THREAD

**Issue by jcoletaylor** [helm/charts#12767]
**Is this a request for help?**:

Yes, request for help.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

Unfortunately, it probably isn't actually a bug, but a configuration issue. But I don't know where else to ask. I don't want to open a new issue that seems so clearly related to #5810 since I can see where the pull request was merged quite a long time ago. But I still have the error and I don't know what to fix. I am getting the following error if I look at the pod logs:

`error_class="Aws::Errors::MissingCredentialsError" error="unable to sign request without credentials set"`
My values.yaml file looks like this:
```yaml
annotations: {}

awsRegion: us-east-1
awsRole: arn:aws:iam::601762473314:role/k8s-logger
logGroupName: k8s-staging

rbac:
  create: true

extraVars:
  - "{ name: FLUENT_UID, value: '0' }"
```

And I am installing the helm chart like this:

```bash
helm install --name fluentd -f values.yaml incubator/fluentd-cloudwatch
```
I am not explicitly assigning my `awsAccessKeyId` or `awsSecretAccessKey` because I want it to use the role and not my personal account credentials, especially since the log group has already been created via the aws cli. But is it necessary that these values are set? I can't seem to find a clear answer. And FWIW I do have `kube2iam` installed already.

The `k8s-logger` role above has the following policy attached:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "logs:DescribeLogGroups",
                "logs:DescribeLogStreams",
                "logs:PutLogEvents"
            ],
            "Resource": "*"
        }
    ]
}
```

**Version of Helm and Kubernetes**:

`kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

`helm version`

```
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

**Which chart**:

incubator/fluentd-cloudwatch

**What happened**:

I ran helm install with the above `values.yaml` file and it installed fine. But I get the error logs as noted above, specifically `Aws::Errors::MissingCredentialsError` 

**What you expected to happen**:

Not to get that error? :D

**How to reproduce it** (as minimally and precisely as possible):

As above, using the command noted and the values.yaml file noted. 

**Anything else we need to know**:

Just that I'm sorry to open another issue for what is almost certainly solved but I don't know where else to ask.

**Comment by jcoletaylor** [comment]
@hsinhoyeh Do you think this looks like the previous issue #5810 ?

**Comment by hsinhoyeh** [comment]
what I did before is to create another account dedicated for this purpose.

**Comment by jcoletaylor** [comment]
Okay. Thanks, I appreciate the feedback. So I guess the awsRole feature does not work on its own, but requires some kind of secret and id credentialing?
