### ISSUE TITLE
[stable/graylog] indexPrefix for elasticsearch isn't recognized

### ISSUE THREAD

**Issue by sercanacar** [helm/charts#12779]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
2.10

**Which chart**:
stable/graylog
kubernetes 1.11

**What happened**:
Setting indexprefix in values.yaml
```
elasticsearch:
  hosts: "http://elasticsearch-client.graylog.svc.cluster.local:9200"
  indexPrefix: kubernetes
```
```curl -XGET 'localhost:9200/_cat/indices?v&pretty'
health status index                         uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   kubernetes_cluster-2019.04.03 tH3EuJCFSWK_DqLHY8H4Hg   5   1      28508            0     28.9mb         13.7mb
```
**What you expected to happen**:
Expecting graylog to pick up the index prefix

**How to reproduce it** (as minimally and precisely as possible):
kubectl logs graylog

```graylog/graylog-1[graylog-server]: 2019-04-03 08:06:32,413 INFO    [ServerBootstrap] - Graylog server up and running. - {}
graylog/graylog-0[graylog-server]: 2019-04-03 08:06:48,959 ERROR   [Cluster] - Couldn't read cluster health for indices [graylog_*] (graylog-elasticsearch-client.graylog.svc.cluster.local) - {}
```

**Comment by KongZ** [comment]
This seems to be a Graylog bugs when you set default index prefix to something other than `graylog`. You can fix the problem by delete default index from Graylog web interface and create a new one.

This option will be remove on Graylog 3.0
