### ISSUE TITLE
[stable/datadog] collect events in defined namespaces

### ISSUE THREAD

**Issue by mazzy89** [helm/charts#1278]
**Is this a request for help?**:

Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

```bash
$ helm version
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:24Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2+coreos.0", GitCommit:"79fee581ce4a35b7791fdd92e0fc97e02ef1d5c0", GitTreeState:"clean", BuildDate:"2017-04-19T23:13:34Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/datadog

**What happened**:
When `datadog.collectEvents: true` the ENV variable `KUBERNETES_COLLECT_EVENTS ` is set to `true` inside the `Deployment` resource and passed to the Datadog agent. The events are sent to Datadog. Unfortunately only events from `namespace: default` are sent to Datadog. Other events are not sent. This because by default the `kubernetes.yaml` under `/etc/dd-agent/conf.d` doesn't define any other namespace and consequently it fallbacks to `default` as commented in the file.

**What you expected to happen**:
Collect event in all the namespaces.

**How to reproduce it** (as minimally and precisely as possible):
Enable `datadog.collectEvents: true` and 
```yaml
deployment:
    enabled: true
    replicas: 1
```

**Anything else we need to know**:
TBD

**Comment by mazzy89** [comment]
Any updates on this?

**Comment by hkaj** [comment]
Hi @mazzy89 
you can configure that in the yaml file, or by starting the container with the  `KUBERNETES_NAMESPACE_NAME_REGEX` env var.

**Comment by andredantasrocha** [comment]
@hkaj I am experiencing the same issue. How can I specify the namespaces during `helm install`?Thanks!

**Comment by andredantasrocha** [comment]
Does this `values.yaml` work?
```
datadog:
  env:
    - name: KUBERNETES_NAMESPACE_NAME_REGEX
      value: ".*"
```

**Comment by mazzy89** [comment]
yep I confirm. for me `KUBERNETES_NAMESPACE_NAME_REGEX` worked fine

**Comment by rossedman** [comment]
There are some known issues in the datadog agent with the regex expression, you may have to do this:

```
    env:
    - name: KUBERNETES_NAMESPACE_NAME_REGEX
      value: "'.*'"
```
