### ISSUE TITLE
[stable/postgresql] Postgres crash on drop database

### ISSUE THREAD

**Issue by mjrepo2** [helm/charts#12789]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Version of Helm and Kubernetes**: Helm = 2.13.0 Kubernetes = 1.13.3

**Which chart**: stable/postgresql (postgresql-3.15.0)

**What happened**: Upon dropping a database the entire postgres cluster fails. All you can do is to delete the three database pods (master-0, slave-0 and slave-1) so they will redeploy. 
The database will be dropped, all other data still availiable.

**What you expected to happen**: The database to be dropped and the cluster should remain stable without reboot of the pods.

**How to reproduce it** (as minimally and precisely as possible): 
Deploy cluster with 1 master and 2 slaves. Persistence is on.
Connect to postgres-postgressql service (e.g. via pgadmin), create database "test"
drop database "test"

**Anything else we need to know**:
There are no log entries regarding the error with 
kubectl logs postgres-postgresql-master-0 postgres-postgresql
Maybe it is only the connection crashing and the server not accepting new ones. How could we check that?

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue

```
± |fixRedisSlaveValues → origin ✓| → kubectl run jazzed-rat-postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:10.7.0 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host jazzed-rat-postgresql -U postgres
If you don't see a command prompt, try pressing enter.

postgres=# 
postgres=# 
postgres=# 
postgres=# create database test;
ERROR:  database "test" already exists
postgres=# drop database test;
DROP DATABASE
postgres=# create database test;
CREATE DATABASE
postgres=# drop database test;
DROP DATABASE
postgres=# 
```

Could you provide more details about your platform?

**Comment by mjrepo2** [comment]
Hi,

i think this can be closed. We investigated further and somewhen changed the persistent storage for the postgres. Since then the issue disappeared.
