### ISSUE TITLE
[stable/airflow] Airflow worker logs aren't persistent

### ISSUE THREAD

**Issue by stevenmanton** [helm/charts#12798]
**Is this a request for help?**:
No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
Helm 2.12.3
Kubernetes v1.13.3

**Which chart**:
stable/airflow

**What happened**:
The worker logs get wiped whenever the pod is restarted. This is because the logs are stored within the container filesystem, not within a persistent volume. Setting {{logsPersistence.enabled}} to {{true}} works for the webserver and scheduler pods, but not the worker pods.

**What you expected to happen**:
The logs should be persisted if the worker pod is restarted.

**How to reproduce it** (as minimally and precisely as possible):
Run a DAG and check the logs in the webserver. Make a change to the helm chart and upgrade. Check the logs for the same DAG run; they will be missing.

**Anything else we need to know**:
It seems others use the push-logs-to-S3 feature of airflow to avoid local log storage. This approach fixes the persistence issue.

It may be possible to simply mount the PVC created with {{logsPersistence.enabled=true}}, as with the webserver and scheduler pods. It's not clear to me if logs would collide and overwrite each other, but on simple inspection it seems this is a safe fix to the problem. I can do a PR if folks think that's a good approach.

**Comment by jtlz2** [comment]
[ @stevenmanton Apologies for asking here - but I've been unable to get the scheduler and web pods to deploy using this chart. It was a permissions issue (ValueError: Unable to configure handler 'processor': [Errno 13] Permission denied: '/usr/local/airflow/logs/scheduler') - are you using a local PV for dags/logs? You couldn't by any chance post your steps anywhere could you? See also https://stackoverflow.com/questions/54460678/airflow-k8s-how-do-i-correctly-set-permissions-for-dags-stored-in-a-persistent Thanks for any help!]

**Comment by stevenmanton** [comment]
Hey @jtlz2 are you using the branch in the PR or the stable/airflow in the master branch? If you're using master, I've never seen that permission error. If the former, I'm using the same PVC that's created by the `pvc-logs.yaml` template; I'm not sure why there would be any permission errors for that either.

Looking at your SO question, you might just drop the gid/uid annotations in your PVC yaml file. They aren't present in the `pvc-logs.yaml` template in the helm chart.

**Comment by gsemet** [comment]
Thanks for this remark. Indeed logs aren’t persistant on worker :) thanks for the PR

**Comment by will-beta** [comment]
Looking forward to this feature!

**Comment by will-beta** [comment]
any progress?

**Comment by stevenmanton** [comment]
@will-beta yeah I'm still trying to get that dang PR approved...

**Comment by gsemet** [comment]
Hum, look like #14221 can actually do the job
