### ISSUE TITLE
Problem in elastic stack set up issues

### ISSUE THREAD

**Issue by hitesh1907nayyar** [helm/charts#12806]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG Report

**Version of Helm and Kubernetes**:
Kubernetes Version - v1.12.0
helm Version - v2.11.0
**Which chart**:
elastic-stack

**What happened**:
Not able to run kibana as it always shows kibana server is not ready 

**What you expected to happen**:
Running Kibana and integrated with elastic search

**How to reproduce it** (as minimally and precisely as possible):
helm  upgrade --install --namespace logging-system elk stable/elastic-stack -f values.yaml. Screenshot attached for values.yaml

**Anything else we need to know**:
Always get this warning in the POD of kibana. Even though have kept the  ELASTICSEARCH_URL: http://elk-elasticsearch-client:9200 it is still trying to connected to :http://elasticsearch:9200/

{"type":"log","@timestamp":"2019-04-04T01:53:43Z","tags":http://elasticsearch:9200/ 
["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: 
![Values_yml_snapshot](https://user-images.githubusercontent.com/42111008/55524768-0fbe3c80-56ac-11e9-9bcd-34c1ef041b44.PNG)

http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2019-04-04T01:53:43Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}

bash-4.2$ curl -XGET http://elk-elasticsearch-client:9200
{
  "name" : "elk-elasticsearch-client-ffff4f779-hnhc5",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "L4yAZMPmT3CMqoLJ60gd8g",
  "version" : {
    "number" : "6.7.0",
    "build_flavor" : "oss",
    "build_type" : "docker",
    "build_hash" : "8453f77",
    "build_date" : "2019-03-21T15:32:29.844721Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

Everything was running till day before yesterday with the same values.yaml. Yesterday started to receive the problem

**Comment by 0xErnie** [comment]
Duplicate of #12378
