### ISSUE TITLE
[stable/prometheus] request: document example sidecar

### ISSUE THREAD

**Issue by chrisovergaauw** [helm/charts#12815]
**Is this a request for help?**: yes

I'm looking for more detailed information on something that does not seem to be documented.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST
**Version of Helm and Kubernetes**: 2.13 & 1.13.3
**Which chart**: Prometheus

The README specifies that sidecars can be defined but it does not mention anything about the syntax. I'd like to learn how to do this and maybe enhance the values.yaml with an example.

**Comment by chrisovergaauw** [comment]
I'd still like to see this improved.

**Comment by chrisovergaauw** [comment]
Pretty disappointing...

**Comment by u2g-tg** [comment]
The implementation looks pretty simple in the Prometheus statefulset definition

      {{- if .Values.server.sidecarContainers }}
       {{- toYaml .Values.server.sidecarContainers | nindent 8 }}
       {{- end }}

If you define an list of container definitions at server.sidecarContainers in your Helm values, then the containers will be started as sidecars.

The container definition would be a full block as per any StatefulSet/Deployment spec.template.spec.containers: element
