### ISSUE TITLE
Deployment in version "v1beta1" cannot be handled as a Deployment

### ISSUE THREAD

**Issue by FlogFr** [helm/charts#12827]
**Version of Helm and Kubernetes**:

Kubernetes version: v1.13
Helm version: v2.13.1

**Which chart**:

nginx-ingress

**What happened**:

```
# helm install --set controller.nodeSelector='{"ingress":"nginx"}' --name ingress-nginx ./charts/stable/nginx-ingress/
Error: release ingress-nginx failed: Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment.Spec: v1beta1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.NodeSelector: ReadMapCB: expect { or n, but found [, error found in #10 byte of ...|elector":["\"ingress|..., bigger context ...|ClusterFirst","hostNetwork":false,"nodeSelector":["\"ingress\":\"nginx\""],"serviceAccountName":"ing|...
# helm list
NAME         	REVISION	UPDATED                 	STATUS  	CHART              	APP VERSION	NAMESPACE  
ingress-nginx	1       	Thu Apr  4 16:03:58 2019	FAILED  	nginx-ingress-1.4.0 0.23.0     	default    
```

**What you expected to happen**:

Deploy the nginx-ingress without problem

**How to reproduce it** (as minimally and precisely as possible):

It is a fresh kubernetes v1.13 installed cluster, with helm v2.13.1. I git checkout this repository and run against the master (c7edb3f) in the charts nginx-ingress.

**Anything else we need to know**:

I tried to change the apiVersion of the deployment, in the controller-deployment.yml but same results. Not sure how to fix it.

**Comment by Towmeykaw** [comment]
I think the issue is with the nodeSelector. You could set it with --set controller.nodeSelector.ingress=nginx
