### ISSUE TITLE
[stable/postgresql]  The replication problem

### ISSUE THREAD

**Issue by greendog** [helm/charts#12829]
Replication does not work.
Here https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-9/Dockerfile#L32 we have env. variable with the name `POSTGRESQL_REPLICATION_MODE`.

Here https://github.com/helm/charts/blob/master/stable/postgresql/templates/statefulset.yaml#L112 we have env. variable with the name `POSTGRES_REPLICATION_MODE`

And here the same: https://github.com/helm/charts/blob/master/stable/postgresql/templates/statefulset-slaves.yaml#L99 

As result I have an error for a slave container:

>  Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
nami    INFO  Initializing postgresql
postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
postgre INFO  ==> Checking slave replication parameter ...
postgre INFO  ==> Valid slave replication parameter ...
postgre INFO  ==> Waiting for replication master to accept connections (60s timeout)...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
ERROR [canConnect] Connection with 'replication-db-user' user is unsuccessful
ERROR [canConnect] Connection with 'replication-db-user' user is unsuccessful
ERROR [canConnect] Connection with 'replication-db-user' user is unsuccessful
ERROR [canConnect] Connection with 'replication-db-user' user is unsuccessful
ERROR [canConnect] Connection with 'replication-db-user' user is unsuccessful
Error executing 'postInstallation': Cannot connect to PostgreSQL server:
psql: FATAL:  password authentication failed for user "replication-db-user" 

and for the master:

>  2019-04-04 15:42:42.029 GMT [79] LOG:  database system is shut down
waiting for server to shut down.... done
server stopped
2019-04-04 15:42:42.085 GMT [72] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-04-04 15:42:42.085 GMT [72] LOG:  listening on IPv6 address "::", port 5432
2019-04-04 15:42:42.090 GMT [72] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-04-04 15:42:42.122 GMT [116] LOG:  database system was shut down at 2019-04-04 15:42:41 GMT
2019-04-04 15:42:42.138 GMT [72] LOG:  database system is ready to accept connections
2019-04-04 15:42:43.755 GMT [123] FATAL:  password authentication failed for user "replication-db-user"
2019-04-04 15:42:43.755 GMT [123] DETAIL:  Role "replication-db-user" does not exist.
	Connection matched pg_hba.conf line 95: "host     all             all             0.0.0.0/0               md5"
2019-04-04 15:42:48.769 GMT [132] FATAL:  password authentication failed for user "replication-db-user"
2019-04-04 15:42:48.769 GMT [132] DETAIL:  Role "replication-db-user" does not exist.
	Connection matched pg_hba.conf line 95: "host     all             all             0.0.0.0/0               md5"
2019-04-04 15:42:53.784 GMT [133] FATAL:  password authentication failed for user "replication-db-user"
2019-04-04 15:42:53.784 GMT [133] DETAIL:  Role "replication-db-user" does not exist.
	Connection matched pg_hba.conf line 95: "host     all             all             0.0.0.0/0               md5"
2019-04-04 15:42:58.797 GMT [142] FATAL:  password authentication failed for user "replication-db-user"
2019-04-04 15:42:58.797 GMT [142] DETAIL:  Role "replication-db-user" does not exist.
	Connection matched pg_hba.conf line 95: "host     all             all             0.0.0.0/0               md5"
2019-04-04 15:43:04.382 GMT [144] LOG:  incomplete startup packet
2019-04-04 15:43:04.392 GMT [145] FATAL:  password authentication failed for user "replication-db-user"
2019-04-04 15:43:04.392 GMT [145] DETAIL:  Role "replication-db-user" does not exist.
	Connection matched pg_hba.conf line 95: "host     all             all             0.0.0.0/0               md5" 

Check the value:
```
# master
$ kubectl exec -it postgresql-master-0 -- bash
I have no name!@postgresql-master-0:/$ echo $POSTGRESQL_REPLICATION_MODE
master


# slave
$ kubectl exec -it postgresql-slave-0 -- bash
I have no name!@postgresql-slave-0:/$ echo $POSTGRESQL_REPLICATION_MODE
master
```

My config is:

```
postgresqlDatabase: testdb
persistence:
  enabled: true
  storageClass: postgres-pv
  accessModes:
  - ReadWriteOnce
  size: 10Gi
  annotations: {}
replication:
  enabled: true
  slaveReplicas: 2
  numSynchronousReplicas: 0
  user: replication-db-user
  applicationName: postgres_db_cluster
  password: testpasswd
```

**Comment by juan131** [comment]
Hi @greendog 

> Replication does not work.
> Here https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-9/Dockerfile#L32 we have env. variable with the name POSTGRESQL_REPLICATION_MODE.
>
> Here https://github.com/helm/charts/blob/master/stable/postgresql/templates/statefulset.yaml#L112 we have env. variable with the name POSTGRES_REPLICATION_MODE

What version of the Bitnami PostgreSQL image are you using? As you can check in the links below:

https://github.com/bitnami/bitnami-docker-postgresql#9611-r66-9611-ol-7-r83-1060-r68-1060-ol-7-r83-1110-r62-and-1110-ol-7-r79
https://github.com/bitnami/bitnami-docker-postgresql#environment-variables-aliases

Those env. variables are aliases.

**Comment by XBeg9** [comment]
I have the same issue, any updates?

**Comment by juan131** [comment]
Hi @XBeg9 

Could you please let us know what version of the PostgreSQL chart and the Bitnami PostgreSQL image are you using?

**Comment by AlyRagab** [comment]
I have the same exact issue , 
Image is the latest and chart version is 3.11.0

**Comment by greendog** [comment]
Guys, I had a mistake with password validation. I changed `replication-db-user` to `replication_db_user` and it helped me.

**Comment by XBeg9** [comment]
@juan131 @AlyRagab same issue, no changes to image and chart version is 3.11.0.

**Comment by juan131** [comment]
@XBeg9 @AlyRagab could you please share the **values.yaml** you're using to install the chart? I'd like to reproduce the same scenario you're struggling with.

**Comment by AlyRagab** [comment]
@juan131 i just used to run it as :
`helm install --name postgresql --set "postgresqlDatabase=mydb,replication.enabled=true,replication.slaveReplicas=2,postgresqlUsername=admin,postgresqlPassword=password" stable/postgresql --version 3.11.0`

**Comment by juan131** [comment]
Hi @AlyRagab 

I was unable to reproduce the issue using the command you shared an minikube as K8s cluster:

```bash
$ helm repo update
$ helm install --name postgresql --set "postgresqlDatabase=mydb,replication.enabled=true,replication.slaveReplicas=2,postgresqlUsername=admin,postgresqlPassword=password" stable/postgresql --version 3.11.0
...
$ kubectl get pods -l app=postgresql,chart=postgresql-3.11.0,role=slave
NAME                            READY   STATUS    RESTARTS   AGE
postgresql-postgresql-slave-0   1/1     Running   0          3m15s
postgresql-postgresql-slave-1   1/1     Running   0          2m1s
$ kubectl logs $(kubectl get pods -l app=postgresql,chart=postgresql-3.11.0,role=slave -o jsonpath={.items[0].metadata.name})

Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues

nami    INFO  Initializing postgresql
postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
postgre INFO  ==> Checking slave replication parameter ...
postgre INFO  ==> Valid slave replication parameter ...
postgre INFO  ==> Waiting for replication master to accept connections (60s timeout)...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql-postgresql:5432
postgre INFO  PostgreSQL server listening and working at postgresql-postgresql:5432
postgre INFO  ==> Replicating the initial database...
postgre INFO  ==> Configuring PostgreSQL...
postgre INFO  ==> Configuring replication parameters...
postgre INFO  ==> Setting up streaming replication slave...
postgre INFO  ==> Configuring permissions for config files...
postgre INFO
postgre INFO  ########################################################################
postgre INFO   Installation parameters for postgresql:
postgre INFO     Root User: postgres
postgre INFO     Password: Not set during installation
postgre INFO     Replication Mode: slave
postgre INFO     Replication Username: repl_user
postgre INFO     Replication Password: **********
postgre INFO     Master Host: postgresql-postgresql
postgre INFO     Master Port: 5432
postgre INFO   (Passwords are not shown for security reasons)
postgre INFO  ########################################################################
postgre INFO
nami    INFO  postgresql successfully initialized
INFO  ==> Starting postgresql...
$ kubectl logs $(kubectl get pods -l app=postgresql,chart=postgresql-3.11.0,role=slave -o jsonpath={.items[1].metadata.name})

Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues

nami    INFO  Initializing postgresql
postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
postgre INFO  ==> Checking slave replication parameter ...
postgre INFO  ==> Valid slave replication parameter ...
postgre INFO  ==> Waiting for replication master to accept connections (60s timeout)...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql-postgresql:5432
postgre INFO  PostgreSQL server listening and working at postgresql-postgresql:5432
postgre INFO  ==> Replicating the initial database...
postgre INFO  ==> Configuring PostgreSQL...
postgre INFO  ==> Configuring replication parameters...
postgre INFO  ==> Setting up streaming replication slave...
postgre INFO  ==> Configuring permissions for config files...
postgre INFO
postgre INFO  ########################################################################
postgre INFO   Installation parameters for postgresql:
postgre INFO     Root User: postgres
postgre INFO     Password: Not set during installation
postgre INFO     Replication Mode: slave
postgre INFO     Replication Username: repl_user
postgre INFO     Replication Password: **********
postgre INFO     Master Host: postgresql-postgresql
postgre INFO     Master Port: 5432
postgre INFO   (Passwords are not shown for security reasons)
postgre INFO  ########################################################################
postgre INFO
nami    INFO  postgresql successfully initialized
INFO  ==> Starting postgresql...
```

As you can check both slave were initialized successfully.

**Comment by XBeg9** [comment]
@juan131 please, try to do this new PVC, delete your previous one for both master and slave.

**Comment by carrodher** [comment]
Hi, I am not reproducing the issue from scratch, I mean, with everything deleted from previous deployments. Can you share your `values.yaml`?

**Comment by XBeg9** [comment]
@carrodher that's values-production.yaml that comes with helm chart.

**Comment by juan131** [comment]
Hi @XBeg9 

I was unable to reproduce the issue with the **values-production.yaml** on a Minikube K8s cluster without any previous existing PVC.

These are the steps I followed:

```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
$ curl -LO https://raw.githubusercontent.com/helm/charts/master/stable/postgresql/values-production.yaml
$ helm install stable/postgresql --name postgresql \
    --values values-production.yaml \
    --set postgresqlDatabase=my-custom-database,postgresqlPassword=my-custom-password
$ kubectl get pods -l app=postgresql,role=master
NAME                             READY   STATUS    RESTARTS   AGE
postgresql-postgresql-master-0   2/2     Running   0          2m6s
$ kubectl get pods -l app=postgresql,role=slave
NAME                            READY   STATUS    RESTARTS   AGE
postgresql-postgresql-slave-0   1/1     Running   0          2m11s
postgresql-postgresql-slave-1   1/1     Running   0          74s
$ kubectl logs $(kubectl get pods -l app=postgresql,role=slave -o jsonpath={.items[0].metadata.name})

Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues

nami    INFO  Initializing postgresql
postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
postgre INFO  ==> Checking slave replication parameter ...
postgre INFO  ==> Valid slave replication parameter ...
postgre INFO  ==> Waiting for replication master to accept connections (60s timeout)...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql-postgresql:5432
postgre INFO  PostgreSQL server listening and working at postgresql-postgresql:5432
postgre INFO  ==> Replicating the initial database...
postgre INFO  ==> Configuring PostgreSQL...
postgre INFO  ==> Configuring replication parameters...
postgre INFO  ==> Setting up streaming replication slave...
postgre INFO  ==> Configuring permissions for config files...
postgre INFO
postgre INFO  ########################################################################
postgre INFO   Installation parameters for postgresql:
postgre INFO     Root User: postgres
postgre INFO     Password: Not set during installation
postgre INFO     Replication Mode: slave
postgre INFO     Replication Username: repl_user
postgre INFO     Replication Password: **********
postgre INFO     Master Host: postgresql-postgresql
postgre INFO     Master Port: 5432
postgre INFO   (Passwords are not shown for security reasons)
postgre INFO  ########################################################################
postgre INFO
nami    INFO  postgresql successfully initialized
INFO  ==> Starting postgresql...
2019-05-09 07:44:15.266 GMT [88] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-05-09 07:44:15.266 GMT [88] LOG:  listening on IPv6 address "::", port 5432
2019-05-09 07:44:15.269 GMT [88] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-05-09 07:44:15.281 GMT [95] LOG:  database system was interrupted; last known up at 2019-05-09 07:44:14 GMT
2019-05-09 07:44:15.406 GMT [95] LOG:  entering standby mode
2019-05-09 07:44:15.409 GMT [95] LOG:  redo starts at 0/2000028
2019-05-09 07:44:15.410 GMT [95] LOG:  consistent recovery state reached at 0/20000F8
2019-05-09 07:44:15.410 GMT [88] LOG:  database system is ready to accept read only connections
2019-05-09 07:44:15.424 GMT [99] LOG:  started streaming WAL from primary at 0/3000000 on timeline 1
```

What K8s cluster are you using?

**Comment by Ascendance** [comment]
Am facing a similar issue. The replicas hang write queries. Ping'd and tested the master/replicas are reachable. 

` usename  | application_name |  client_addr  |         backend_start         |   state   | sync_state
----------+------------------+---------------+-------------------------------+-----------+------------
 postgres | "my_application" | 10.71.138.233 | 2019-09-20 23:31:16.935346+00 | streaming | async
 postgres | "my_application" | 10.71.129.185 | 2019-09-20 23:31:51.414429+00 | streaming | async`

whenever a write query is issued, the whole thing just hangs. no error, no logs one the replicas what-so-ever...

**Comment by Ascendance** [comment]
The problem seems to be `synchronousCommit`. When off, everything seems fine... but this basically means giving up a bit of ACID.

**Comment by tombh** [comment]
I'm currently seeing the same problem as @Ascendance on a fresh install. Replication is happening, as in data is written to both master and slaves, but master hangs on any kind of write waiting for complete replication confirmation.
