### ISSUE TITLE
[stable/wordpress] service pending for an IP despite ingress is on

### ISSUE THREAD

**Issue by kachkaev** [helm/charts#1282]
_Not sure if I'm reporting a right thing in a right place, because I'm very new to k8s and helm._

I noticed that in both instances of wordpress I started the wordpress service remained `pending` for a few days. The apps are running behind an ingress controller and work fine, just look odd in the dashboard:

![screenshot from 2017-06-12 11-33-13](https://user-images.githubusercontent.com/608862/27030303-9d907502-4f63-11e7-822a-c09f2f1aea1a.png)

```bash
kubectl get svc --namespace=wp
NAME                  CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
wp-test-2-mariadb     10.102.65.242    <none>        3306/TCP                     2d
wp-test-2-wordpress   10.106.186.60    <pending>     80:31972/TCP,443:30352/TCP   2d
wp-test-mariadb       10.106.168.164   <none>        3306/TCP                     2d
wp-test-wordpress     10.105.83.107    <pending>     80:31219/TCP,443:31942/TCP   2d
```

I guess the cause is in https://github.com/kubernetes/charts/blob/master/stable/wordpress/templates/svc.yaml, where serviceType is `LoadBalancer` by default. I tried switching it to `ClusterIP` by `--set="...,serviceType=ClusterIP"`, but helm returned:
```
Error: UPGRADE FAILED: Service "wp-test-2-wordpress" is invalid: [spec.ports[0].nodePort:
Invalid value: 31972: may not be used when `type` is 'ClusterIP', spec.ports[1].nodePort:
Invalid value: 30352: may not be used when `type` is 'ClusterIP']
```
When a new release is started with `serviceType=ClusterIP` straight away, the service does become `ready`. But it's not clear that this is something that needs to be defined from the docs (at least for a newbie like me).

Can serviceType automatically depend on whether ingress is enabled? Or at least could this issue be communicated somehow in the chart's README?

---

**Version of Helm and Kubernetes**:
2.4.2 / 1.6.4

**Which chart**:
wordpress 0.6.4

**How to reproduce it**:

Just install a chart with ingress enabled:
```
helm install --namespace=wp --name wp-test stable/wordpress --set="ingress.enabled=true,ingress.hostname=wp-test.kubernetes,persistence.storageClass=default,mariadb.persistence.storageClass=default"
```

/cc @bcorijn @jbianquetti-nami @mgoodness as recent contributors to this chart – big thank you guys!

**Comment by jbianquetti-nami** [comment]
Hi!   I think that your problem can be related to storage, since
I've just installed with this:

` helm install --namespace=wp --name wp-test stable/wordpress --set="ingress.enabled=true,ingress.hostname=wp-test.kubernetes,persistence.enabled=false,mariadb.persistence.enabled=false"` 

Also, it seems that you have tried to HELM UPGRADE a deployment changing his serviceType. I think it's not directly supported by Helm. 

Please, try it again with the command provided. If it works for you, please add more info about your environment in order to be able to reproduce your problem as close as your environment as possible: Minikube/CGE/AWS, disk types/storageClass

**Comment by kachkaev** [comment]
@jbianquetti-nami the storage was ok - I did prepare some volumes beforehand and the claims resolved to them without any issues. It was lack of `serviceType=ClusterIP` in `--set` while `ingress.enabled=true`, as it turned out. The service should not be `LoadBalancer` when ingress is on because it's ingress controller's job to expose the service to the node ports now.

My point is that either `serviceType=ClusterIP` must be automatically set when `ingress.enabled=true` is passed or at least this relationship between the config values should be documented somehow.

**Comment by Med-All** [comment]
I'm experiencing the same problem using Bitnami Helm Chart for Wordpress

```
> kubectl get services -n wordpress -o wide
NAME                TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE     SELECTOR
wordpress           LoadBalancer   10.43.137.240   <pending>     80:31672/TCP,443:31400/TCP   5d21h   app.kubernetes.io/instance=wordpress,app.kubernetes.io/name=wordpress
wordpress-mariadb   ClusterIP      10.43.7.73      <none>        3306/TCP                     5d21h   app=mariadb,component=master,release=wordpress
```

```
> kubectl describe services wordpress -n wordpress
Name:                     wordpress
Namespace:                wordpress
Labels:                   app.kubernetes.io/instance=wordpress
                          app.kubernetes.io/managed-by=Tiller
                          app.kubernetes.io/name=wordpress
                          helm.sh/chart=wordpress-9.5.1
                          io.cattle.field/appId=wordpress
Annotations:              <none>
Selector:                 app.kubernetes.io/instance=wordpress,app.kubernetes.io/name=wordpress
Type:                     LoadBalancer
IP:                       10.43.137.240
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  31672/TCP
Endpoints:                10.42.1.16:8080
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  31400/TCP
Endpoints:                10.42.1.16:8443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```
