### ISSUE TITLE
chart installation expects grafana configmaps when grafana disabled

### ISSUE THREAD

**Issue by thehhugg** [helm/charts#12855]
**Is this a request for help?**: Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
Helm:
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

K8s:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-3+602d21b1679fa5", GitCommit:"602d21b1679fa5f8de2f9a04bbf485f1fa09a973", GitTreeState:"clean", BuildDate:"2019-02-27T16:46:58Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
prometheus-operator 5.0.7

**What happened**:
We've disabled grafana, but when trying to install the chart, it fails with:

`no ConfigMap with the name "infra-grafana-config-dashboards" found`

**What you expected to happen**:
When grafana is disabled, the dashboards ConfigMap shouldn't need to be present for the install to succeed.

**How to reproduce it** (as minimally and precisely as possible):
In values.yaml:

```
  grafana:
    enabled: false
```

Then attempt to install the prometheus-operator helm chart.

**Anything else we need to know**:

**Comment by vsliouniaev** [comment]
The configmap template specifies that it will not be created when grafana is not enabled, so your request is already part of the chart.

I cannot reproduce your error when installing the chart. 

I can reproduce it if I do the following 
1. Install the chart with grafana enabled 
2. Manually delete the configmap 
3. Upgrade the chart with grafana disabled 

In the above case, recreating the cinfigmap manually should allow an upgrade (which will delete the cinfigmap) 

Are you certain your repro steps are correct?
