### ISSUE TITLE
[stable/mongodb-replicaset] azure AKS unable to set master slave

### ISSUE THREAD

**Issue by polganesh** [helm/charts#12852]
**Is this a request for help?**:
Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
It might be bug

**Version of Helm and Kubernetes**:
Version of Helm 2.13
version of k8s 1.12.5

**Which chart**:
stable/mongodb-replicaset

**What happened**:
i changed default mongodb version 

```
image:
  repository: mongo
  #tag: 3.6
  tag: 4

```
change storage type  to managed-premium
```
persistentVolume:
  enabled: true
  storageClass: "managed-premium"

```
then install helm chart with

> helm install --name=todo helm-charts/mongodb-replicaset
> 

`executed following command after some time. to check if my mongodb pods are up our not.

> kubectl get pods

once sure i exectued following command to check which POD is primary

`for ((i = 0; i < 3; ++i)); do kubectl exec --namespace default todo-mongodb-replicaset-$i -- sh -c 'mongo --eval="printjson(rs.isMaster())"'; done
`
**What you expected to happen**:
i can see which pod is primary.

but for all pods i am getting 

{
        "ismaster" : false,
        "secondary" : false,
        "info" : "Does not have a valid replica set config",
        "isreplicaset" : true,
        ....
        "readOnly" : false,
        "ok" : 1
}

**How to reproduce it** (as minimally and precisely as possible):
executing it on AKS with k8s version 1.12.5

**Anything else we need to know**:
Not specific

**Comment by steven-sheehy** [comment]
I don't know if anyone has tested this chart on 4.x yet. Do you know if it works @unguiculus?

Regardless, you need to provide the bootstrap and mongo container logs to debug.

**Comment by unguiculus** [comment]
I haven't looked into 4.x yet.
