### ISSUE TITLE
[stable/prometheus-operator] Consider making AdditionalPrometheusRules a map

### ISSUE THREAD

**Issue by alice-sawatzky** [helm/charts#12859]
I think `additionalPrometheusRules` would be better as a map, instead of a list of maps with name:groups[] pairs. Aside from removing a layer of indirection, it allows for finer-grained overrides in parent charts, multiple values files, `--set`, etc. The key would be the PrometheusRule name, and the value would be the value of `groups:` in the current schema.

**Comment by alice-sawatzky** [comment]
if only there were some way to annotate lists with their desired merge behavior (replace the list, append, prepend, replace non-null elements, etc) instead of treating them like opaque leaf nodes! until then it seems like we should shy away from lists in our values files whenever possible.

**Comment by vsliouniaev** [comment]
This is a significant breaking change for others from this chart and can be avoided by creating a separate chart for deploying rules into the cluster yourself
