### ISSUE TITLE
[stable/sentry] Make worker concurrency configurable in values.yaml

### ISSUE THREAD

**Issue by uipo78** [helm/charts#12865]
**Is this a request for help?**: Yes, although I'd be happy to submit a pull request.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm: v2.11.0
Kubernetes: v1.10.10

**Which chart**:
stable/sentry

**What happened**:
By default, the `sentry worker` pods set their concurrency to the number of cores available on the machine on which the pod is running. This is often a waste, and without setting the memory resource limit to something high for such pods, the pods are inevitably OOM killed.

**What you expected to happen**:
I'd expect to have the concurrency be configurable in the `values.yaml` file. This can happen by changing [this line](https://github.com/helm/charts/blob/master/stable/sentry/templates/workers-deployment.yaml#L46) to look something like this:
```
args: ["run", "worker", "--concurrency", {{ quote .Values.worker.concurrency }}]
```
**How to reproduce it** (as minimally and precisely as possible):
In my case, I used the default sentry installation (`helm install stable/sentry`). All of our boxes have at least 48 cores.

**Comment by uipo78** [comment]
I know this issue was closed because of a lack of response, but it'd be nice to at least hear back from someone, especially considering the fact that there's [a PR that fixes this issue](https://github.com/helm/charts/pull/12911)...

**Comment by uipo78** [comment]
@okgolove you're listed as an owner on this repo so I'm gonna tag you here, just in case you didn't receive a notification a while back.

**Comment by okgolove** [comment]
Hi @uipo78. You can reopen your PR.

**Comment by okgolove** [comment]
Btw https://github.com/helm/charts/pull/14940
