### ISSUE TITLE
[stable/jenkins] Cannot use ClusterIP on Master

### ISSUE THREAD

**Issue by berwyn** [helm/charts#12860]
**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.10", GitCommit:"aaf0906400b5fc1d858ce0566a571e4f3ed06b9f", GitTreeState:"clean", BuildDate:"2019-03-30T19:30:48Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/jenkins

**What happened**:
Given `values.yml` of
```yml
Master:
  Image: jenkins/jenkins
  ImageTag: lts-jdk11
  ServiceType: ClusterIP
  JCasC:
    enabled: true
  Sidecars:
    configAutoloadEnabled: true
  InstallPlugins:
    - kubernetes:1.14.9
    - workflow-aggregator:2.6
    - blueocean:1.14.0
    - git:3.9.3
    - github:1.29.4
    - github-branch-source:2.4.5
    - github-oauth:0.31
    - configuration-as-code:1.10
    - configuration-as-code-support:1.10
    - google-cloudbuild:0.2.2
    - google-oauth-plugin:0.7
    - google-storage-plugin:1.2
  EnableRawHtmlMarkupFormatter: true
  HealthProbes: true
  ingress:
    enabled: true
    apiVersion: extensions/v1beta1
    hostName: # redacted
    path: /
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: nginx
      kubernetes.io/ingress.global-static-ip-name: jenkins-static-ip
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      certmanager.k8s.io/acme-challenge-type: http01
    tls:
      - hosts:
          - # redacted
        secretName: jenkins-tls
rbac:
  install: true
NetworkPolicy:
  enabled: true
```

`helm upgrade -f values.yml jenkins stable/jenkins` will fail with the error
```
UPGRADE FAILED
ROLLING BACK
Error: Service "jenkins" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
Error: UPGRADE FAILED: Service "jenkins" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```

**What you expected to happen**:
The upgrade would apply, change my `ServiceType` to `ClusterIP` and allow my ingress controller to work

**How to reproduce it** (as minimally and precisely as possible):
1. Remove the `ServiceType: ClusterIP`, and install the chart
2. Restore the `ServiceType: ClusterIP`, and attempt to upgrade the chart

**Anything else we need to know**:
I can successfully install using the `LoadBalancer` format, but this causes problems using an nginx ingress controller. I've been reading and it seems I'm to use a `ClusterIP` instead, leading to this issue.

**Comment by berwyn** [comment]
Also, for context, I did a `--dry-run` of the upgrade (also trying with `--reuse-values` and `--reset-values`, neither of which helped) and it does output a manifest that looks correct:
```yml
# Source: jenkins/templates/jenkins-master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
    heritage: "Tiller"
    release: "jenkins"
    chart: "jenkins-0.37.0"
    component: "jenkins-jenkins-master"
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      
  selector:
    component: "jenkins-jenkins-master"
  type: ClusterIP
```

**Comment by berwyn** [comment]
Spent some time over the weekend debugging this and it may not be an issue with the chart. The generated yaml is perfectly valid, and if I delete the service and `helm upgrade` again from there everything applies and works correctly. It seems like either Helm or Kubernetes itself is retaining some values somewhere and not correctly removing the `nodePort` configuration when changing the service to a `ClusterIP`

**Comment by abdennour** [comment]
@berwyn  I did the same, I removed the service, and I ran "helm upgrade" and the upgrade works, however, when I tried to login , I cannot 😔 even though i am using the same username and password after checking the secret : 

```sh
printf $(kubectl get secret --namespace cicd cicd-jenkins -o jsonpath="{.data.jenkins-admin-password}" | base64 --decode);echo
```

**Comment by ishanrakitha** [comment]
I'm also experiencing the same issue. Unable to switch the jenkins-master service type to ClusterIp. Please advise.
