### ISSUE TITLE
[stable/nextcloud] duplicate location "/" in /tmp/nginx-cfg100189447:586

### ISSUE THREAD

**Issue by thomashoell** [helm/charts#12883]
**Version of Helm and Kubernetes**:
Helm: 2.13.1
Kubernetes: 1.13.5

**Which chart**:
stable/nextcloud

**What happened**:
Deployment of ingress failed

**How to reproduce it** 
Install the chart with the ingress annotations found in values.yaml

```
Error: exit status 1
2019/04/07 14:39:33 [notice] 19898#19898: ModSecurity-nginx v1.0.0
2019/04/07 14:39:33 [emerg] 19898#19898: duplicate location "/" in /tmp/nginx-cfg100189447:586
nginx: [emerg] duplicate location "/" in /tmp/nginx-cfg100189447:586
nginx: configuration file /tmp/nginx-cfg100189447 test failed
```

**Anything else we need to know**:
The is caused by the following rewrite rule found in the configuration snippet of values.yaml

```
location / {
  rewrite ^ /index.php$request_uri;
}
```

**Comment by roelofjansen** [comment]
I got the same problem and removed the "location /" part from the snippet in values.yaml.

**Comment by thomashoell** [comment]
> I got the same problem and removed the "location /" part from the snippet in values.yaml.

This broke Nextcloud for me because of the missing rewrite.

**Comment by chrisingenhaag** [comment]
Hi guys,
I´m already on this and improved the snippet. The block location / {} cannot be defined in server-snippet annotation. 

Pls try

```
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;

      rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      location = /.well-known/carddav {
        return 301 https://$host/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 https://$host/remote.php/dav;
      }
      location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
        deny all;
      }
```

In my dev in my dev env I got rid of most of the security warning from nextcloud.

**Comment by chrisingenhaag** [comment]
The snippet will be updated in the next few versions. I already have some pull requests open to get this live.

**Comment by thomashoell** [comment]
I did a quick test yesterday and it looked pretty promising, except that the new snippet probably broke certbot. The challenge URL returns 403:

Ingress Controller logs:
> 2019/05/17 05:04:02 [error] 313#313: *1455389 access forbidden by rule, client: 10.254.254.1, server: XXX.XXX.XXX, request: "GET /.well-known/acme-challenge/loaCojgaBNjmPPGdL3RB2Hv5Bh_yVBRwR9S2XXGgzGY HTTP/1.1", host: "XXX.XXX.XXX"

Certbot logs:
> I0517 05:04:08.007504 1 controller.go:171] certificates controller: syncing item 'cloud/nextcloud-tls'
> I0517 05:04:08.007949 1 sync.go:274] Preparing certificate cloud/nextcloud-tls with issuer
> I0517 05:04:08.008454 1 logger.go:43] Calling GetOrder
> I0517 05:04:08.323505 1 logger.go:73] Calling GetAuthorization
> I0517 05:04:08.494533 1 logger.go:93] Calling HTTP01ChallengeResponse
> I0517 05:04:08.494876 1 prepare.go:279] Cleaning up old/expired challenges for Certificate cloud/nextcloud-tls
> I0517 05:04:08.495063 1 logger.go:68] Calling GetChallenge
> I0517 05:04:08.708374 1 http.go:134] wrong status code '403'
> I0517 05:04:08.708673 1 ingress.go:49] Looking up Ingresses for selector certmanager.k8s.io/acme-http-domain=2410547817,certmanager.k8s.io/acme-http-token=1155272310
> I0517 05:04:08.708825 1 helpers.go:201] Found status change for Certificate "nextcloud-tls" condition "Ready": "False" -> "False"; setting lastTransitionTime to 2019-05-17 05:04:08.708818463 +0000 UTC m=+215023.355417671
> I0517 05:04:08.708960 1 sync.go:276] Error preparing issuer for certificate cloud/nextcloud-tls: http-01 self check failed for domain "nextcloud.hoellskitchen.de"
> E0517 05:04:08.709070 1 sync.go:197] [cloud/nextcloud-tls] Error getting certificate 'nextcloud-tls': secret "nextcloud-tls" not found
> E0517 05:04:08.713777 1 controller.go:180] certificates controller: Re-queuing item "cloud/nextcloud-tls" due to error processing: http-01 self check failed for domain "XXX.XXX.XXX"
> I0517 05:04:08.713937 1 controller.go:168] ingress-shim controller: syncing item 'cloud/ncloud-nextcloud'
> I0517 05:04:08.714041 1 sync.go:140] Certificate "nextcloud-tls" for ingress "ncloud-nextcloud" already exists
> I0517 05:04:08.714112 1 sync.go:143] Certificate "nextcloud-tls" for ingress "ncloud-nextcloud" is up to date
> I0517 05:04:08.714164 1 controller.go:182] ingress-shim controller: Finished processing work item "cloud/ncloud-nextcloud"

**Comment by chrisingenhaag** [comment]
Ok I took the config from nextcloud doc and I think the following is the problem:

```
  location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
    deny all;
  }
```

The following should do the trick:

``` 
location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
  deny all;
}
```

**Comment by thomashoell** [comment]
> Ok I took the config from nextcloud doc and I think the following is the problem:
> 
> ```
>   location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
>     deny all;
>   }
> ```
> 
> The following should do the trick because it removes the matcher for "path begins with ."
> 
> ```
> location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
>   deny all;
> }
> ```

Works like a charm, thank you!

**Comment by chrisingenhaag** [comment]
No worries, would you please close the issue?
