### ISSUE TITLE
 [stable/odoo] missing release on service selector

### ISSUE THREAD

**Issue by weeband** [helm/charts#12884]
**Which chart:**
stable / odoo

**What happened:**
when install two or more releases of odoo, it will not routed correctly.
eq: when I open service odoo1, it will not select pod from odoo2

**What you expected to happen:**
when 

**How to reproduce it (as minimally and precisely as possible):**
```
helm install stable/odoo --name odoo1
helm install stable/odoo --name odoo2
kubectl port-forward svc/odoo1 8080:80
```
it will load balanced to pod from odoo1 and odoo2

**Anything else we need to know:**
to fix this, just add
```
    release: {{ .Release.Name }}
```
to
```
  selector:
    app: {{ template "odoo.name" . }}
```
on [this](https://github.com/helm/charts/blob/ef428cead7ebfb2549d6c6f15f91cf4556544860/stable/odoo/templates/svc.yaml#L25) line

**Comment by juan131** [comment]
Hi @notwiben 

I can reproduce the issue. As shown below the selectors are the same for both generated services: 

```bash
$ kubectl get svc odoo1-odoo -o jsonpath='{.spec.selector}'
map[app:odoo]
$ kubectl get svc odoo2-odoo -o jsonpath='{.spec.selector}'
map[app:odoo]
```

However, for some reason, the service seems to be able to identify the correct endpoints.

```bash
$ kubectl get endpoints odoo1-odoo
NAME         ENDPOINTS   AGE
odoo1-odoo               2m3s
$ kubectl get endpoints odoo2-odoo
NAME         ENDPOINTS   AGE
odoo2-odoo               2m9s
```

I'm looking into it...

**Comment by juan131** [comment]
The changes were just merged! Could you please give the latest Odoo chart a try @notwiben ?
