### ISSUE TITLE
Jenkins pod not starting

### ISSUE THREAD

**Issue by hitesh1907nayyar** [helm/charts#12901]
**Is this a request for help?**:
help
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
kubectl - v1.12.0

**Which chart**:
jenkins

**What happened**:
Jenkins POD is not starting after running helm command. It is showing in state Init:0/1 and deployment is also coming unavailable. 

C:\Users\hitesh_n>kubectl --kubeconfig "D:\MACHINE LEARNING\Kubernates Microservices\hcl-kubeConfig" -n jenkins-system get all
NAME                           READY   STATUS     RESTARTS   AGE
pod/jenkins-86d5645b64-2q2nn   0/1     Init:0/1   6          82m

NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
service/jenkins         ClusterIP   172.20.195.145   <none>        8080/TCP    82m
service/jenkins-agent   ClusterIP   172.20.153.16    <none>        50000/TCP   82m

NAME                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/jenkins   1         1         1            0           82m

NAME                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/jenkins-86d5645b64   1         1         0       82m

**What you expected to happen**:
Jenkins POD running

**How to reproduce it** (as minimally and precisely as possible):
helm upgrade --install --namespace jenkins-system jenkins stable/jenkins -f values.yaml

**Anything else we need to know**:

**Comment by maorfr** [comment]
can we see your values.yaml?

**Comment by hitesh1907nayyar** [comment]
@maorfr - Please find the same.
![Jenkins-Value](https://user-images.githubusercontent.com/42111008/55847268-38d84480-5b66-11e9-934b-14719a93595e.png)

**Comment by maorfr** [comment]
what do the logs/describe say?

**Comment by manojshetty28** [comment]
Hi All

  We are getting the same error - after running Helm chart for Jenkins stable version 

  We have provided Existing PVC claim in Helm chart 

   The Container is not starting - showing init state and restart after 5 mins

  We have waited for 20 mins, the Jenkins container using PD of GCP Disk is not running

   Can you please help

regards
Manoj

**Comment by manojshetty28** [comment]
Is this Jenkins Helm chart error related with Kubernetes PVC and PV 

Using Existing PVC in Helm chart value

**Comment by manojshetty28** [comment]
Issue resolved with Jenkins container - we were running GKE cluster in Google cloud - Private network

Solution: we attached a NAT gateway to Private GKE cluster

Jenkins pod is working

**Comment by torstenwalter** [comment]
So the error has been with downloading plugin?
