### ISSUE TITLE
[stable/sonatype-nexus] Uncorrelate nexus backup pod and nexus backup volume

### ISSUE THREAD

**Issue by chevalier-m** [helm/charts#12900]
Hello.

`sonatype-nexus` as presented in this chart repository is meant for a GCP backup, and there is some configuration I would appreciate in order to not use GCP anymore.

In fact, for many apps we use in k8s, we have a backup procedure that backups a specific volume to our own backend. But in the chart configuration, there is no possibility for having a persistent volume for the `/nexus-data/backup` without having the GCP-related pod created.

My first thought is that it would be great to separate the backup container logic from the backup volume logic, i.e the values from the helm chart could be `nexusPodBackup.whatever` and `nexusBackup.something`. This would give the possiblity for the `nexus` container in the pod to mount a persistent volume instead of an `EmptyDir` in `nexus-data/backup`.

If the way described above looks good to you, I could possibly make a PR, it's literally 3 line changes and the `README` upgrade to reference the new value.

Let me know what you think.

**Comment by mumrau** [comment]
Not much activity over here, maybe someone could redirect me to a place where nexus community is more active?

**Comment by mumrau** [comment]
up

**Comment by mumrau** [comment]
up

**Comment by Dmitry1987** [comment]
The chart authors probably did not receive the notification about this issue. I also see other tickets with related questions, unanswered. It's better to modify the chart yourself and use it, and submit a PR with your changes. 

These tickets were also not answered:
1. About S3 backup option (which is why I'm here also :) )  https://github.com/helm/charts/issues/12300  and GCS backup option config https://github.com/helm/charts/issues/13570
2. About the proxy, is it necessary and how it can work directly without it https://github.com/helm/charts/issues/7999
3. Broken healthchecks when ingress is used https://github.com/helm/charts/issues/7697

Also you have this option of deployment https://github.com/travelaudience/kubernetes-nexus  without Helm, it might work as well.

**Comment by Dmitry1987** [comment]
lol I forgot what I wanted to ask myself...
So, I'm looking for an "official" method to backup to S3, and seems like I'll not find it here 🤕 .
Gotta make myself and send a PR.

**Comment by Dmitry1987** [comment]
@here  @everyone  if anybody hears us on this deserted island, please advice on a proper way to configure an AWS deployment with artifact storage on S3 and backups 🙏   thanks in advance! 😌

**Comment by TAvardit** [comment]
Hi, 
We currently don't have the time to develop and test S3 support but maybe you can join efforts with others that are interested in S3 support, develop and test it and then add a PR here:
https://github.com/travelaudience/docker-nexus-backup/
You can possibly connect with:
https://github.com/travelaudience/docker-nexus-backup/issues/5

**Comment by mumrau** [comment]
Up.

**Comment by mumrau** [comment]
up

**Comment by mumrau** [comment]
Keeping the pace

**Comment by petejohansonxo** [comment]
Bumpity bump.

**Comment by petejohansonxo** [comment]
No really.

**Comment by mumrau** [comment]
Thank you for keeping up the pace!

**Comment by titou10titou10** [comment]
We have the same kind of requirement
Actually, even if you set`"nexusBackup.enabled=false"`,a volume for backup is defined in the`"volume"`and `"volumeMounts"` specs of the deployment/sts
At a minimun, if`"nexusBackup.enabled=false"`, no volume should be defined in the deployment and we can then use`"deployment.additionalVolumes"`and`"deployment.additionalVolumeMounts"`values to define the volume backup
Note that it is still possible to define extra volume/volumeMount at a ddifferent mount point than `"/nexus-data/backup"

**Comment by mumrau** [comment]
Back at it.

**Comment by nmousouros** [comment]
This is still not solved why is it closed?
