### ISSUE TITLE
[stable/rocketchat] Adding Database Name to helm install command

### ISSUE THREAD

**Issue by IlonkaO** [helm/charts#12903]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

If this is a BUG REPORT:
The README told me to install RocketChat with the following command: 
`$ helm install --set mongodb.mongodbUsername=<your_username_here>,mongodb.mongodbPassword=<your_password_here> --name my-rocketchat stable/rocketchat`

But after starting the deployment the mongodb pod return the message: 
```
kubectl logs rocketchat-mongodb-d9ff4754f-jgjtl

Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues

nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB from scratch...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
mongodb INFO  ==> Creating root user...
Error executing 'postInstallation': If you defined an username you must define a password and a database too
```
 
After adding another parameter to the "helm install" command, deployment works for me:
`$ helm install --set mongodb.mongodbUsername=<your_username_here>,mongodb.mongodbPassword=<your_password_here>,mongodbDatabase=<your_database_name> --name my-rocketchat stable/rocketchat`

**Version of Helm and Kubernetes**: 
```
$ minikube version
minikube version: v0.35.0
```
```
$ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

**Which chart**: stable/rocketchat

**What happened**: Deployment stucks with error

**What you expected to happen**: Deployment should work without error

**How to reproduce it** (as minimally and precisely as possible): Using the mentioned "helm install" command in the README.md

**Anything else we need to know**: You are all doing a great job :-)

**Comment by srueg** [comment]
This is solved with the latest version. A default `mongodbDatabase` is set to `rocketchat`.

**Comment by srueg** [comment]
/close 
#13619
