### ISSUE TITLE
[stable/prometheus-operator] warning: cannot overwrite table with non table for value 

### ISSUE THREAD

**Issue by samjsong** [helm/charts#12918]
**Is this a request for help?**: No

---

**Which chart**:
`stable/prometheus-operator`

**What happened**:
When trying to install the chart with an overrides file:
```
$ helm install --name prometheus-operator stable/prometheus-operator -f overrides.yaml --no-crd-hook
2019/02/20 17:21:03 Warning: Merging destination map for chart 'prometheus-operator'. Cannot overwrite table item 'remoteWrite', with non table value: map[]
```
There is a warning due to the `values.yaml` file in the `prometheus-operator` chart containing `remoteWrite: {}` rather than `remoteWrite: []`.

**What you expected to happen**:
Install should succeed with no warnings.

**How to reproduce it** (as minimally and precisely as possible):
Run
```
$ helm install --name prometheus-operator stable/prometheus-operator -f overrides.yaml --no-crd-hook
```
where `overrides.yaml` looks like:
```
prometheus:
  prometheusSpec:
    remoteWrite:
    - url: <your_url>
```

**Anything else we need to know**:
This is the same as https://github.com/helm/charts/issues/7585, just a different place in a different file. PR incoming

**Comment by voa2000** [comment]
Changing from {} to [] did work.
