### ISSUE TITLE
[stable/mongodb-replicaset]  ideal way to  create  db and non root/admin user  with read and write access 

### ISSUE THREAD

**Issue by polganesh** [helm/charts#12917]
**Is this a request for help?**:

_Yes_
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

> Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
> 

> k8s version 1.12.7

**Which chart**:
stable/mongodb-replicaset

**What happened**:
we are able to create mongodb replicaset with following values.yaml

  ```
auth:
    enabled: true
    existingKeySecret: skeleton
    existingAdminSecret: skeleton

```
it has helped me to create mongodb stateful set with authentication enabled and taking admin user/password from secret with name **existingAdminSecret**.
**What you expected to happen**:
we want to provide non root user credentials from this chart similar to admin user and facility to create custom db.

i observed that it has possibility to provide init js  script 

![image](https://user-images.githubusercontent.com/13764801/55745401-6c688100-5a37-11e9-975b-dfc61a181cb1.png)

do we have any facility to pass non root user credentials from secret and apply in this js 
something like this

`db.createUser({ user: "$MONGO_USERNAME", pwd: "$MONGO_USER_PASSWORD", roles: [ { role: "readWrite", db: "$MONGO_INITDB_DATABASE" } ] } )
`
where "$MONGO_USERNAME", $MONGO_USER_PASSWORD and "$MONGO_INITDB_DATABASE" are env variables to be available via k8s secret

**Comment by steven-sheehy** [comment]
The contents of the init script are stored in a configmap, so you're welcome to do actions like createUser but it's not secure. The init container also doesn't support passing additional env variables either.

There was an old [PR](https://github.com/helm/charts/pull/9975) where someone was attempting to add mongo users declaratively, but it never got finished. You're welcome to do something similar.
