### ISSUE TITLE
[stable/drone]jobs.batch is forbidden when drone and pipeline have different k8s namespaces

### ISSUE THREAD

**Issue by tiggerlee2** [helm/charts#12928]
**BUG REPORT**

**Version of Helm and Kubernetes**:
Helm: v2.13.0
Kubernetes: 1.12

**Which chart**:
stable/drone
version: 2.0.0-rc.8

**What happened**:
I install drone to namespace __cd__ and use __drone-pipeline__ as pipeline space

```
helm install --name drone-release --namespace cd --version 2.0.0-rc.8 --set 'ingress.enabled=true' --set 'ingress.hosts[0]=mydomain' --set 'ingress.tls[0].secretName=mysecretname' --set 'sourceControl.provider=gogs' --set 'sourceControl.gogs.server=gogshost' --set 'server.host=mydomain'  --set 'server.kubernetes.namespace=drone-pipeline' --set 'server.kubernetes.pipelineServiceAccount=drone-pipeline-account' --set 'persistence.existingClaim=disk-drone' --set 'persistence.size=2Gi' --set 'rbac.apiVersion=v1beta1' --set 'serviceAccount.name=drone-account' stable/drone
```

Pipeline can be triggered but status stay pending and never finish. Following is error from drone server pod, drone-account does not  have jobs.batch permission of namespace drone-pipeline:
```
{"error":"jobs.batch is forbidden: User \"system:serviceaccount:cd:drone-account\" cannot create resource \"jobs\" in API group \"batch\" in the namespace \"drone-pipeline\"","level":"error","msg":"kubernetes: cannot create job","time":"2019-04-09T04:56:09Z"}
```
I  change role.yaml and role-binding.yaml  to use ClustRole instead of Role. The permission problem is resolved:

https://github.com/helm/charts/blob/18ea3a550bb7dac242838459424a2036daea184a/stable/drone/templates/role.yaml#L3

https://github.com/helm/charts/blob/18ea3a550bb7dac242838459424a2036daea184a/stable/drone/templates/role-binding.yaml#L3

https://github.com/helm/charts/blob/18ea3a550bb7dac242838459424a2036daea184a/stable/drone/templates/role-binding.yaml#L13

**Comment by jgrossmac** [comment]
Im having this issue as well on a new install.

**Comment by sasso** [comment]
any suggestions on how to get around this issue?

**Comment by christian-roggia** [comment]
@sasso @tiggerlee2 feel free to open a PR and ping @zakkg3 regarding a proposal.
