### ISSUE TITLE
[stable/redis-ha] - Benchmark Testing of RedisGraph (flask/locust)

### ISSUE THREAD

**Issue by styk-tv** [helm/charts#12925]
This is more of an FYI, anyone interested to review more details of `redis-ha` in combination with RedisGraph (running Cypher queries on Redis DB) please ask questions in this issue.

https://github.com/RedisLabsModules/RedisGraph/issues/430

Many thanks for the `redis-ha` chart. StatefulSet implementation was exactly what I was looking for.

**Comment by ssalaues** [comment]
That's pretty cool work! I'm glad you were able to load your model and was able to fit your use-case.
