### ISSUE TITLE
[stable/kong] no way to connect to postgres with ssl on

### ISSUE THREAD

**Issue by keeganmccallum** [helm/charts#12950]
There is currently no way to connect to postgres with ssl on in the default kong chart, would be nice to have a setting `pg_sslmode` that could be set to handle db providers like Heroku.

**Comment by hbagdi** [comment]
@keeganmccallum You can set `KONG_PG_SSL=on` variable in the `env` section in values.yaml:
```yaml
env:
  pg_ssl: on
```

Please close this issue. Thank you!
