### ISSUE TITLE
[stable/mattermost-team-edition] Can't enable the jira plugin

### ISSUE THREAD

**Issue by sbpro86** [helm/charts#12957]
**Is this a request for help?**:

NO

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

**HELM VERSION** 
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

**KUBERNETES**
1.11.7-gke.12 (GOOGLE GKE)

**Which chart**:
stable/mattermost-team-edition

**What happened**:
Enabling the JIRA plugin from GUI automatically disable it directly.

**What you expected to happen**:
JIRA plugin enabled.

**How to reproduce it** (as minimally and precisely as possible):
Just tap the enable button on the JIRA plugin box in the System Console plugin management

**Anything else we need to know**:
Tried to enable it through the config.json but the same happens.

**The logs just shows this line**:
{"level":"info","ts":1554848772.9559722,"caller":"scheduler/worker.go:78","msg":"Worker: Job is complete","worker":"Plugins","job_id":"trgegu8zkirj5rhx3rbmg15mua"}

**Comment by ahmadalli** [comment]
mattermost helm chart uses configmaps for it's configuration which is why settings on system console (including plugins) are read-only. 
the new mattermost's helm chart has a plugin section on it's value but I'm not sure how we can set things up there
