### ISSUE TITLE
How to create new users in Jenkins.

### ISSUE THREAD

**Issue by jdalfons** [helm/charts#12978]
I follow the tutorial of Google cloud to create my Jenkins Kubernetes pod with Helm but I can't create new Users, I need to manage the users that enter to the platform.
This is the tutorial:
https://cloud.google.com/solutions/jenkins-on-kubernetes-engine-tutorial
How can I install or configure Jenkins with the user manage and if is possible from the yaml file.

Aditional Info:
jenkins-war:2.164.2
slave-installer:1.6

**Comment by halcolo** [comment]
Closed.
https://sharadchhetri.com/2018/11/29/create-jenkins-user-command-line-gui/
