### ISSUE TITLE
How to deploy using helm templates?

### ISSUE THREAD

**Issue by bmarthi248** [helm/charts#12977]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Neither

**Version of Helm and Kubernetes**:
Helm:  v2.12.3
Kubernetes: 1.10

**Which chart**:
postgres

**What happened**:
We are not allowed to run tiller and helm installs wont work.  I am told to install using helm templates.  Is there documentation on how to deploy postgres using templates?

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by maorfr** [comment]
I think what you mean is to use helm to generate the manifests using `helm template` and piping the output to `kubectl apply`.

Another option is to use helm in tiller-less mode.

Hope that helped!

**Comment by bmarthi248** [comment]
Thank you.  That pointed me in the right direction.
