### ISSUE TITLE
[redis-ha] /readonly-config/init.sh fails as service names not in `getent hosts`

### ISSUE THREAD

**Issue by ArcticSnowman** [helm/charts#12980]
The init.sh script fails as it tries to look up the announce service but those DNS are not in the hosts table inside the pod..

```
Could not connect to Redis at test-redis-redis-ha:26379: Temporary failure in name resolution
Initializing config..
/readonly-config/init.sh: 85: /readonly-config/init.sh: Could not resolve the announce ip for this pod: not found
```

```kubectl exec -ti test-redis-redis-ha-server-0 -c config-init getent hosts
127.0.0.1       localhost
127.0.0.1       localhost ip6-localhost ip6-loopback
10.52.22.5      test-redis-redis-ha-server-0.test-redis-redis-ha.test-redis.svc.cluster.local test-redis-redis-ha-server-0
```

**Comment by jeason81** [comment]
I'm having the same issue. I was curious if you were able to resolve this?

**Comment by ArcticSnowman** [comment]
I took my fork of the helm template, commented out https://github.com/helm/charts/blob/master/stable/redis-ha/templates/_configs.tpl#L116-L124
and have another script to handle the master/secondary selection.

A version of https://github.com/smileisak/docker-images/blob/master/redis/alpine/redis-launcher.sh
