### ISSUE TITLE
[stable/atlantis] Manage webhook secrets separately

### ISSUE THREAD

**Issue by wvidana** [helm/charts#12999]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

  - We want to be able to handle secrets ourselves. I don't like the idea of having tokens at plain sight in a values file to install/upgrade the chart. We were able to just replicate `atlantis-aws` with no issue since the secrets file is "optional" (it has a conditional at the top of the template). But the secret `atlantis-webhook` is enforced, thus throwing an error at us since it already exists.

**Which chart**:
stable/atlantis

**What happened**:
Genereted `atlantis-webhook` secrets on our own, run `helm upgrade` and got an error about duplicated resource.

**What you expected to happen**:
Running the helm chart not requiring the secrets to be read from the values file.

**How to reproduce it** (as minimally and precisely as possible):
Using `kubectl` create a Secret called `atlantis-webhook`. After that try to install or upgrade atlantis with helm `helm upgrade -i atlantis stable/atlantis`

**Comment by wvidana** [comment]
Any comments?

**Comment by wvidana** [comment]
@lkysow anything?

**Comment by lkysow** [comment]
Hi Wilfrido, sorry I didn't see this because there's no way for me to only get notified about Atlantis issues. I suggest you open up an issue in runatlantis/atlantis next time.

Yes I think we should support a secret name that you can pass in. PR's welcome!

**Comment by wvidana** [comment]
@lkysow Thank you for the prompt response.

I wanted to keep it simple in the PR https://github.com/helm/charts/pull/13667

But maybe you were looking for something like this? https://github.com/helm/charts/compare/master...wvidana:atlantis-secret-webhook-name

**Comment by lkysow** [comment]
Yeah I think the latter would be better so folks don't have to name the secret a certain name

**Comment by wvidana** [comment]
Thanks for the feedback! Just pushed the changes to the original PR
