### ISSUE TITLE
[stable/concourse] Investigate and remove mounting `workerKeyPub` inside the worker pod

### ISSUE THREAD

**Issue by YoussB** [helm/charts#13019]
**Version of Helm and Kubernetes**:
latest

**Which chart**:
stable/concourse

**What happened**:
- the `workerKeyPub` is mounted on the worker pod, although, technically this is not needed.

**What you expected to happen**:
- the `workerKeyPub` should not be mounted on the worker pod.

**How to reproduce it** (as minimally and precisely as possible):
- `helm install` the chart

**Comment by YoussB** [comment]
🙌

**Comment by cirocosta** [comment]
👀

**Comment by YoussB** [comment]
awaiting the merge of:
- #15579 
- concourse/concourse#4133
