### ISSUE TITLE
[stable/jenkins] Continue receiving 404 error when trying to load jenkins server.  

### ISSUE THREAD

**Issue by thesamuelpark** [helm/charts#13015]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
kubernetes nodes version 1.10.12

**Which chart**:
stable/jenkins

**What happened**:
Tried helm upgrade after updating plugin versions and although pods are running and available, i continue receiving a 404 error.  No other changes have been made and was working perfectly fine before i attempted to upgrade my chart.

**What you expected to happen**:
When entering my URL, i expected it to hit my upgraded server that includes new plugin versions

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
Without any context e.g from which version to which version you tried to update, you used values etc. it will be hard to support you.
