### ISSUE TITLE
[percona-xtradb-cluster ] Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by liupeng0518** [helm/charts#13042]
**Is this a request for help?**:

**Version of Helm and Kubernetes**:
helm v2.12.3
k8s v1.11.6
**Which chart**:
percona-xtradb-cluster latest

**What happened**:
logs print 
```
Access denied for user 'root'@'localhost' (using password: YES)
```
**What you expected to happen**:
helm install, and the first pod init,and it will restart

**How to reproduce it** (as minimally and precisely as possible):
helm install percona-xtradb-cluster, 
And, the first pod will restart ,kubectl get pod :
```
RESTARTS 1
```
then It will always print the log and will not initialize the next pod.
**Anything else we need to know**:
When I remove readiness(statusfulset.yml),it will ok.

**Comment by xinghui-hou** [comment]
same problem here
