### ISSUE TITLE
[stable/redis-ha] don't deploy sentinels and redis in the same pod

### ISSUE THREAD

**Issue by mmack** [helm/charts#13048]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Version of Helm and Kubernetes**:
any

**Which chart**:
stable/redis-ha

**What happened**:
If the master pod goes down i loose my connection to the sentinel and the master redis instance.

**What you expected to happen**:
Just just loose the connection to either the sentinel or the master. Reconnecting is much faster / easier then.

**How to reproduce it** (as minimally and precisely as possible):
Deploy the chart, use a client lib and connect to the cluster. then find the current master and delete it. 
Changes are pretty high you find the sentinel connection retry to get back a connection and the actual redis client also. This takes more time than when we deploy the redis / sentinel in two statefulsets with a anti-affinity against each other. If a node goes down or we drain a node we loose either the sentinel (which does not affect the applications) or the active master.

Does that make sense? :)

**Comment by ssalaues** [comment]
While it makes sense why you would want this, having that as a default would make the installation barrier much higher as you would need 6 nodes to support the anti-affinity against each other. I think having the separate sentinel StatefulSet might be the best solution for you and I'm more than willing to review a PR for this kind of refactor.

An interim solution could be to simply add a client facing sentinel service to the redis-ha chart. This would give your clients a stable virtual IP that will load balance the requests to an available sentinel. Currently the chart only has a 'headless' service but this should be fairly easy to add.
