### ISSUE TITLE
Update affinity annotations to use the field instead of annotation

### ISSUE THREAD

**Issue by foxish** [helm/charts#1306]
Part of: https://github.com/kubernetes/charts/issues/1294

Scheduler changes in 1.6: https://docs.google.com/document/d/1YP3OJTKMpXkWAhipPjx9-bDMxJ87JZ6AcVak7c3SGos/edit
Charts affected:
- [x] concourse (@frodenas, @databus23)
- [x] cockroachdb (@a-robinson), in line with https://github.com/kubernetes/kubernetes/pull/45322

cc @kubernetes/charts-maintainers

**Comment by gregoryguillou** [comment]
#1462

**Comment by foxish** [comment]
/close

This has been completed.
