### ISSUE TITLE
[stable/postgresql] probes use ipv6 which creates istio<1.1 incompatibility

### ISSUE THREAD

**Issue by tmc** [helm/charts#13072]
Refs https://github.com/istio/istio/issues/10733

**Comment by carrodher** [comment]
What are the IPv6 references in the probes?

**Comment by tmc** [comment]
@carrodher it uses "localhost" which resolves to ::1

**Comment by carrodher** [comment]
Ok, I see, so it seems that in your system `localhost` resolves to `::1` instead of `127.0.0.1`.

I am accepting your PR in order to use `127.0.0.1` that it's more generic and should work without resolving `localhost`
