### ISSUE TITLE
The PR for add CRL support #6841 openvpn

### ISSUE THREAD

**Issue by joebeadle** [helm/charts#13078]
**Is this a request for help?**:

OpenVPN charts

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
2.11.0

**Which chart**:
openvpn

**What happened**:
Requirement for option to revoke user certs

**What you expected to happen**:
The pull request to be looked at as it seems to be ready to work,

**How to reproduce it** (as minimally and precisely as possible):
Just apply the PR CRL support #6841 

**Anything else we need to know**:

**Comment by joebeadle** [comment]
This is ridiculous!

**Comment by bekriebel** [comment]
This appears to be closed with the merge of #14452

**Comment by jasongwartz** [comment]
@joebeadle the chart seemed to be mostly abandoned for a while, I’m now helping maintain it (would be happy to have more maintainers, if you or anyone is interested). Can you confirm if #14452 covered what you wanted to do with your PR?

**Comment by joebeadle** [comment]
@jason Yes thanks helps a lot!

**Comment by jasongwartz** [comment]
Great, glad to hear
