### ISSUE TITLE
[incubator/jaeger] cannot parse env var JAEGER_AGENT_PORT=udp://100.67.30.30:5775

### ISSUE THREAD

**Issue by voslartomas** [helm/charts#13077]
Environment:

Infrastructure: Kubernetes v1.11.7
Deployment tool: Helm v2.12.2

Could not load jaeger tracer configuration: cannot obtain reporter config from env: 
cannot parse env var JAEGER_AGENT_PORT=udp://100.67.30.30:5775: 
strconv.ParseInt: parsing "udp://100.67.30.30:5775": invalid syntax

**Which chart**:
[incubator/jaeger]

**What happened**:

Installed loki-stack, everything seems fine, but if we install jaeger afterwards and restart loki pod, it will say: cannot parse env var JAEGER_AGENT_PORT=udp://100.67.30.30:5775

**What you expected to happen**:
I would expect to be able to run loki and jaeger alongside each other.

**How to reproduce it** (as minimally and precisely as possible):
Install loki-stack via helm chart
Install jaeger via helm chart
Delete loki pod (it will be in crash)

**Comment by acim** [comment]
This is not a problem of this chart, it is actually dependency https://github.com/jaegertracing/jaeger-client-go that fails:

https://github.com/jaegertracing/jaeger-client-go/blob/c58709fe19d793cdd40ad8bfa6e645a40a2eccf8/config/config_env.go#L186

If you install jaeger chart with name jaeger, environment variable JAEGER_AGENT_PORT will be automatically created by Kubernetes (as string) and jaeger-client-go expects integer (just the port number, not url) under the same name so it is going to fail. The easiest way to fix the problem would be to install jaeger under some different name, for example:

helm install incubator/jaeger --name jaeger-tracing

loki will happily work with that ;)
