### ISSUE TITLE
Make cluster publicly accesible

### ISSUE THREAD

**Issue by rnkhouse** [helm/charts#13093]
**Version of Helm and Kubernetes**:
Helm version:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Kubernets version:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/rabbitmq

How can I make cluster accessible thru public endpoint? Currently, I have a cluster with below configurations. I am able to access the management portal by given hostname (publicly endpoint, which is fine). But, when I checked inside the management portal cluster can be accessible by internal IP and/or hostname which is: `rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local` and `rabbit@<private_ip>`. I want to make cluster public so all other services can connect to it.

    helm install stable/rabbitmq --name rabbitmq \
      --set rabbitmq.username=xxx \
      --set rabbitmq.password=xxx \
      --set rabbitmq.erlangCookie=secretcookie \
      --set rbacEnabled=true \
      --set ingress.enabled=true \
      --set ingress.hostName=rabbitmq.xxx.com \
      --set ingress.annotations."kubernetes\.io/ingress\.class"="nginx" \
      --set resources.limits.memory="256Mi" \
      --set resources.limits.cpu="100m"

**Comment by juan131** [comment]
Hi @rnkhouse 

Are you running your Helm charts on a K8s cluster with "LoadBalancer" support (e.g. AKS, GKE, EKS)? Please note that you could use set the parameter `service.type` to `LoadBalancer` and an external accessible IP will be provided to access your RabbitMQ endpoints.
