### ISSUE TITLE
Rabbitmq: Service using Loadbalancer

### ISSUE THREAD

**Issue by rnkhouse** [helm/charts#13097]
**Is this a BUG REPORT or FEATURE REQUEST?**
BUG_REPORT

**Version of Helm and Kubernetes**:
Helm version:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Kubernets version:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/rabbitmq

**What happened**:
I am trying to set `service.type=LoadBalancer` but service is deployed with ClusterIP

**What you expected to happen**:
Service should deploy as LoadBalancer

    helm install stable/rabbitmq --name rabbitmq \
      --set rabbitmq.username=xxxxx \
      --set rabbitmq.password=xxxxx \
      --set rabbitmq.erlangCookie=secretcookie \
      --set rbacEnabled=true \
      --set service.type=LoadBalancer \
      --set resources.limits.memory="256Mi" \
      --set resources.limits.cpu="100m"

**Comment by rnkhouse** [comment]
@juan131 AKS. It supports loadbalancer type.

**Comment by tompizmor** [comment]
@rnkhouse The RabbitMQ creates two different services. A service to access the application (which is configurable) and another service to access to the statefulset pods (this is always a headless service so it is always a Cluster IP with None ip). 

I just deploy the rabbitmq chart with your command and I can see these services:

```
$ k get svc
NAME                TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)                                                         AGE
kubernetes          ClusterIP      10.96.0.1     <none>        443/TCP                                                         19d
rabbitmq            LoadBalancer   10.98.21.33   <pending>     4369:32099/TCP,5672:32413/TCP,25672:31867/TCP,15672:31560/TCP   33s
rabbitmq-headless   ClusterIP      None          <none>        4369/TCP,5672/TCP,25672/TCP,15672/TCP
```

Can you check that apart from the `rabbitmq-headless` service you also have another one that should be LoadBalancer type?

**Comment by rnkhouse** [comment]
@tompizmor In my case it's not creating loadbalancer ip.
rabbitmq                                 ClusterIP      10.0.10.127   <none>          4369/TCP,5672/TCP,25672/TCP,15672/TCP   16s
rabbitmq-headless                        ClusterIP      None          <none>          4369/TCP,5672/TCP,25672/TCP,15672/TCP   16s

**Comment by tompizmor** [comment]
That is very weird. 
- Are you using the same Kubernetes cluster when you install it manually and when you install it from Jenkins? 
- Are you installing the same chart version? You can check the version by checking the labels of any pod or in the output of the `helm list` command

**Comment by rnkhouse** [comment]
@tompizmor 

1) Yes
2) It's installing a different version. When I install it from Jenkins it's 3.5.5 and when I install manually it's 4.9.0

I don't understand, why is it installing different versions with the same command?

**Comment by tompizmor** [comment]
In order to update the local copy of your chart repositories, you need to run `helm repo update` before installing the chart.
The current version of the chart is 5.5.0 so you are testing outdated version in both environments. Try installing the latest version in both environments to check if it is consistent.

**Comment by rnkhouse** [comment]
Now, it's working. Silly mistake! Thanks for pointing out this.
