### ISSUE TITLE
[Stable/Drupal] add link to dependency in README

### ISSUE THREAD

**Issue by michelleN** [helm/charts#131]
Was a bit confused when reading the README. I didn't know exactly where the "Bitnami MariaDB Chart" lived whether it was referring to the chart in bitnami repo or the stable repo. A link here would be great!

**Comment by lachie83** [comment]
@michelleN - Can you kindly confirm if this has been addressed by #136?

**Comment by michelleN** [comment]
yes it has! Thanks, I'll close this.
