### ISSUE TITLE
Add clamoriniere as a trusted collaborator

### ISSUE THREAD

**Issue by clamoriniere** [helm/charts#13120]
Hello all,

I would like to be added as a trusted collaborator of the Datadog chart.
Per the documentation: https://github.com/helm/charts#trusted-collaborator, I'm opening an issue here.

Let me know if you would like me to share more on my background and knowledge of this chart and the overall Datadog product.

Cheers,

**Comment by hkaj** [comment]
👍 Cédric works at Datadog and maintains the Datadog Helm chart with us. We need him to be involved in the PR lifecycle.

**Comment by clamoriniere** [comment]
Hi @mattfarina, could you look at this issue? 
Thanks in advance

**Comment by mattfarina** [comment]
Invitation sent to join as a collaborator.
