### ISSUE TITLE
[stable/dask] Read-only file system

### ISSUE THREAD

**Issue by Bidek56** [helm/charts#13124]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT
**Version of Helm and Kubernetes**: Azure AKS 1.12.7
**Which chart**: [stable/dask]
**What happened**: 
After installing the dask chart using: `helm install --namespace=dask2 --name dask2 ./dask`
The lab interface http://153.168.127.59/lab? tries to ping:
http://153.168.127.59/lab/api/workspaces/lab?1555521810746 which results in 500 Internal Server Error and a message `{"message": "[Errno 30] Read-only file system: '/home/jovyan/.jupyter/lab'", "reason": null}`

**What you expected to happen**: Status 200

**Anything else we need to know**:
The work around is to add these lines to the templates/dask-jupyter-deployment.yaml:
          lifecycle:
              postStart:
                exec:
                  command: ["/bin/sh", "-c", "cp /tmp/.jupyter/jupyter_notebook_config.py /home/jovyan/.jupyter"]

But this is a hack ATM.
The reason for this issue is a K8s issue: https://github.com/kubernetes/kubernetes/issues/62099

**Comment by christianbeland** [comment]
Any workaround available for this through dask configuration files?

**Comment by Bidek56** [comment]
Not that I am aware of, attaching /home/jovyan/ to a PVC would be another solution.
