### ISSUE TITLE
[stable/jenkins] chart naming convention best practices

### ISSUE THREAD

**Issue by maorfr** [helm/charts#13132]
**Is this a request for help?**:
YES!
---

**Which chart**:
stable/jenkins

This is a call for contributors!

As chart maintainers, we have been working towards making the stable/jenkins chart follow chart best practices, while attempting to simplify it.
Over time, some breaking changes have been introduced to the chart. As this chart is in major version 0, the major version was not bumped, which is confusing as the chart is in the stable repository.
This has led to some discussions around these changes, and we have decided to move towards a 1.0 release.

We would like to know if someone is willing to pick up this task and make some improvements to the Jenkins chart.
The goal is to make the Jenkins chart follow [naming conventions best practices](https://helm.sh/docs/chart_best_practices/#naming-conventions).

Thanks!

**Comment by torstenwalter** [comment]
I'll pick this one up.

**Comment by maorfr** [comment]
awesome!!
