### ISSUE TITLE
neo4j pods CrashLoopBackOff with deafult config

### ISSUE THREAD

**Issue by vsakati** [helm/charts#13146]
Tried to install neo4j on kubernetes using helm

-bash-4.2$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
-bash-4.2$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.8", GitCommit:"4e209c9383fa00631d124c8adcc011d617339b3c", GitTreeState:"clean", BuildDate:"2019-02-28T18:40:05Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

using this single command: 
helm install --name neo4j-helm stable/neo4j --set acceptLicenseAgreement=yes --set neo4jPassword=mySecretPassword

-bash-4.2$ k get po | grep neo
neo4j-helm-neo4j-core-0                                         0/1       OOMKilled          6          8m
neo4j-helm-neo4j-core-1                                         0/1       CrashLoopBackOff   5          8m
neo4j-helm-neo4j-core-2                                         1/1       Running            6          8m

-bash-4.2$ k logs neo4j-helm-neo4j-core-0
Changed password for user 'neo4j'.
Active database: graph.db
Directories in use:
  home:         /var/lib/neo4j
  config:       /var/lib/neo4j/conf
  logs:         /var/lib/neo4j/logs
  plugins:      /plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
Starting Neo4j.

Events:
  Type     Reason                  Age               From                                         Message
  ----     ------                  ----              ----                                         -------
  Normal   Scheduled               9m                default-scheduler                            Successfully assigned default/neo4j-helm-neo4j-core-1 to sdp6-dev-csco-cloud-k8s-node-nf-24
  Normal   SuccessfulAttachVolume  9m                attachdetach-controller                      AttachVolume.Attach succeeded for volume "pvc-667ba3a2-6175-11e9-9ef8-fa163e158509"
  Normal   Pulled                  5m (x5 over 9m)   kubelet, sdp6-dev-csco-cloud-k8s-node-nf-24  Container image "neo4j:3.4.5-enterprise" already present on machine
  Normal   Created                 5m (x5 over 9m)   kubelet, sdp6-dev-csco-cloud-k8s-node-nf-24  Created container
  Normal   Started                 5m (x5 over 9m)   kubelet, sdp6-dev-csco-cloud-k8s-node-nf-24  Started container
  Warning  BackOff                 4m (x11 over 8m)  kubelet, sdp6-dev-csco-cloud-k8s-node-nf-24  Back-off restarting failed container

**Comment by TheJacobKim** [comment]
I'm having the same issue. Is there any resolution for this?

**Comment by hegwin** [comment]
Same issue.


NAME | READY | STATUS | RESTARTS| AGE
-|-|-|-|-
neo4j-core-0 | 0/1 | CrashLoopBackOff | 6 | 7m12s
neo4j-core-1 | 0/1 | CrashLoopBackOff | 5 | 4m58s

`$ kubectl describe pods/neo4j-core-0`

```
Name:           rooms-cn-neo4j-core-0
# Something hidden
Node:           cn-shanghai.172.16.228.180/172.16.228.180
Start Time:     Wed, 08 Apr 2020 10:22:24 +0000
Labels:         app.kubernetes.io/component=core
                app.kubernetes.io/managed-by=Tiller
                app.kubernetes.io/name=neo4j
                controller-revision-hash=rooms-cn-neo4j-core-5d4cb46d9f
                helm.sh/chart=neo4j-2.0.0
                statefulset.kubernetes.io/pod-name=neo4j-core-0
Annotations:    kubernetes.io/limit-ranger:
                  LimitRanger plugin set: cpu, memory request for container rooms-cn-neo4j; cpu, memory limit for container neo4j
Status:         Running
IP:             192.168.6.17
Controlled By:  StatefulSet/neo4j-core
Containers:
  neo4j:
    Container ID:  docker://478f00c202666521dd1ad88b3be238b7282cd8f58d3d57f35aeb6a0a0508b2c4
    Image:         neo4j:3.4.5-enterprise
    Image ID:      docker-pullable://neo4j@sha256:a1ba477fa412f19fc664b8e685f6bdf99b54b649c5a71a0e441646b3efba8841
    Ports:         5000/TCP, 7000/TCP, 6000/TCP, 7474/TCP, 7687/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/bash
      -c
      export NEO4J_dbms_connectors_default__advertised__address=$(hostname -f)
      export NEO4J_causal__clustering_discovery__advertised__address=$(hostname -f):5000
      export NEO4J_causal__clustering_transaction__advertised__address=$(hostname -f):6000
      export NEO4J_causal__clustering_raft__advertised__address=$(hostname -f):7000
      
      if [ "${AUTH_ENABLED:-}" == "true" ]; then
        export NEO4J_AUTH="neo4j/${NEO4J_SECRETS_PASSWORD}"
      else
        export NEO4J_AUTH="none"
      fi
      
      exec /docker-entrypoint.sh "neo4j"
      
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 08 Apr 2020 10:28:58 +0000
      Finished:     Wed, 08 Apr 2020 10:28:59 +0000
    Ready:          False
    Restart Count:  6
    Limits:
      cpu:     1
      memory:  512Mi
    Requests:
      cpu:     100m
      memory:  256Mi
    Environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT:                        yes
      NEO4J_dbms_mode:                                       CORE
      NUMBER_OF_CORES:                                       3
      AUTH_ENABLED:                                          false
      NEO4J_causal__clustering_discovery__type:              DNS
      NEO4J_causal__clustering_initial__discovery__members: neo4j.mx.svc.cluster.local:5000
    Mounts:
      /data from datadir (rw)
      /plugins from plugins (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5qqzx (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir-neo4j-core-0
    ReadOnly:   false
  plugins:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-token-5qqzx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-5qqzx
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
```
