### ISSUE TITLE
[stable/prometheus] Missing value --storage.tsdb.retention.size

### ISSUE THREAD

**Issue by oleksandr-semak** [helm/charts#13167]
In Prometheus 2.7 introduced an option for size-based retention with `--storage.tsdb.retention.size`.
I would be appreciate to be able use it with helm chart.

**Comment by roya** [comment]
This issue has been closed automatically but worth an answer as it might get relevant for others as well.

You can use the `extraArgs` map value for adding more flags:

```
server:
 extraArgs:
   storage.tsdb.retention.size: 5GB
```

Then Helm will add to the prometheus command in this form:

```
          {{- range $key, $value := .Values.server.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
```
