### ISSUE TITLE
Mongodb-replicaset chart vs Mongodb chart differences

### ISSUE THREAD

**Issue by kwill4026** [helm/charts#13186]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
General Question

**Version of Helm and Kubernetes**:
1.11.5 K8s
2.12.3 Helm 

**Which chart**:
Mongodb and mongodb-replicaset 

**What happened**:
Looking between the mongodb chart and the mongodb-replicaset chart I am confused as to what the major differences between the two charts are. The mongodb chart seems to provide more support than the mongodb-replicaset chart. 

**What you expected to happen**:
I expected the mongodb chart to not support replicasets or statefulsets seeing as how the mongodb-replicaset chart does, but it seems like both support the same

**How to reproduce it** (as minimally and precisely as possible):
for the mongodb-replicaset chart: helm install --name my-release stable/mongodb-replicaset
for the mongodb chart: helm install --name my-release stable/mongodb

**Anything else we need to know**:
no

**Comment by juan131** [comment]
Hi @kwill4026 

The MongoDB chart is more generic and supports different configurations (replica set is one of them). However, most of them are disabled by default (e.g. you need to set `replicaSet.enabled=true` to enable replica set configuration).

That said, it's true that they were much more different in the past, and the `stable/mongodb` chart has evolved becoming more flexible.

**Comment by kwill4026** [comment]
Thanks for the response @juan131, does the MongoDB chart also provide statefulset? And what about full TLS encryption with certs or is this something I will have to configure into files/docker-entrypoint-initdb.d to be consumed as a configmap?

**Comment by juan131** [comment]
> does the MongoDB chart also provide statefulset?

`stable/mongodb/` chart use 3 statefulsets when the parameter `replicaSet.enabled` is set to `true`:

 - One for Primary nodes
 - One for Secondary nodes
 - One for Arbitrary nodes

> And what about full TLS encryption with certs or is this something I will have to configure into files/docker-entrypoint-initdb.d to be consumed as a configmap?

By default, there are no parameters provided to configure TLS encryption. 

You can modify the chart to include the corresponding secrets to configure the TLS encryption and consume it on your MongoDB containers by using you custom configuration file (see `configmap` parameter).

**Comment by kwill4026** [comment]
Thanks! @juan131

**Comment by kwill4026** [comment]
One last thing, I am assuming the NGINX Ingress Controller helps solve external accessing of a mongo replicaset via URI issue .Which is when you need to access a replica set in mongodb to determine the master you can't connect through a NodePort exposed service because once you connect through the connection gets switch over to using internal kubernetes namespaces. Also when connecting via node port to a replicaset, it doesnt always land on the primary and instead sometimes selects the secondary.

**Comment by juan131** [comment]
Hi @kwill4026 

The NGINX Ingress Controller allows you accessing MongoDB though a web port (which is a little awkward) but you can use a custom external domain to access your MongoDB replicaset. It's not very common to use this feature.

As you mentioned, when configuring MongoDB with replicaSet, you can access to the primary nodes by selecting a NodePort or LoadBalancer service type. See:

https://github.com/helm/charts/blob/master/stable/mongodb/templates/svc-primary-rs.yaml
