### ISSUE TITLE
[incubator/raw] ConfigMap Artifact created for every raw chart

### ISSUE THREAD

**Issue by dcwangmit01** [helm/charts#13188]
@mumoshu, @josdotso ,

With the `incubator/raw` chart version `0.2.0`, there is a default configuration in the values.yaml file which creates an empty configmap called `raw` every time a release is deployed.  It is found here:

https://github.com/helm/charts/blob/37614efca42d212162d73260979c4c2cdcadcf1f/incubator/raw/values.yaml#L67-L73

Thus, when I deploy two releases of the same `incubator/raw` chart, the second release attempts to create the `raw` configmap again, and thus fails.  The `incubator/raw` chart prior version `0.1.0` does not exhibit this behavior.

Here is the original pull request: https://github.com/helm/charts/pull/12422/files

Reproducing the error:
```bash
$ helm install --name rawchart1 incubator/raw --version 0.2.0
NAME:   rawchart1
LAST DEPLOYED: Mon Apr 22 19:14:28 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME  DATA  AGE
raw   0     1s

$ helm install --name rawchart2 incubator/raw --version 0.2.0
Error: release rawchart2 failed: configmaps "raw" already exists
```

I believe the lines above need to be commented out by default in the values.yaml file.  If this is correct, I can submit a PR.

Thanks!

**Comment by josdotso** [comment]
@mumoshu Could you submit a PR to set templates to `[]` by default? 

Is that a proper fix in your opinion, @dcwangmit01

**Comment by mumoshu** [comment]
@josdotso Unfortunately I believe no, as doing so would break the helm charts CI... https://github.com/helm/charts/pull/12422#issuecomment-475458831

**Comment by mumoshu** [comment]
I wish the helm charts CI accepted a test-only values.yaml so that we can set `templates: []` in your default values.yaml. But I'm not sure if that's possible

**Comment by mumoshu** [comment]
@dcwangmit01 @josdotso PTAL at #13633. I realized that we can add CI-specific values.yaml at `ci/*-values.yaml` of the chart.
