### ISSUE TITLE
Jenkins Chart Problem

### ISSUE THREAD

**Issue by hitesh1907nayyar** [helm/charts#13199]
**Is this a request for help?**:
Help
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
helm - v2.11.0

**Which chart**:
Jenkins

**What happened**:
I am not able to get the POD name of jenkins through the command:
kubectl get pods --namespace jenkins-system -l "app=jenkins"
Till yesterday i was able to get the response for this. Now it is showing no resources found. 

Also if i am overwriting the master.deploymentLabels to be any value i am getting an error : Error: render error in "jenkins/templates/jenkins-master-deployment.yaml": template: jenkins/templates/jenkins-master-deployment.yaml:15:35: executing "jenkins/templates/jenkins-master-deployment.yaml" at <.Values.master.deplo...>: range can't iterate over jenkins

**What you expected to happen**:
Wanted to get the jenkins POD name

**How to reproduce it** (as minimally and precisely as possible):
You can install jenkins and run the above command:
kubectl get pods --namespace jenkins-system -l "app=jenkins"
This was running till yesterday.

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
This should work:

`kubectl get pods --namespace jenkins-system -l app.kubernetes.io/name=jenkins`

labels of the chart have been aligned with helm [chart best practices for labels](https://helm.sh/docs/chart_best_practices/#standard-labels). The major version of the chart has been bumped to indicate this breaking change.
