### ISSUE TITLE
Unable to update from stable charts repo due to string response

### ISSUE THREAD

**Issue by mattatcha** [helm/charts#1320]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
 BUG REPORT

**Version of Helm and Kubernetes**:
Helm: v2.2.1

**What happened**:
An attempt to run `helm repo update` fails with the following error.
```
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
	error unmarshaling JSON: json: cannot unmarshal string into Go value of type repo.IndexFile
```

**How to reproduce it** (as minimally and precisely as possible):
* `helm repo update` 
* `helm repo add stable https://kubernetes-charts.storage.googleapis.com/`

**Anything else we need to know**:
### Charts storage endpoint returns xml instead of json
`curl -H "Content-Type: application/json" https://kubernetes-charts.storage.googleapis.com`

<details>
<summary>
Ignore this, I accidentally used the wrong url</summary>

### Curl to documented google storage endpoint results in the following.
```

$ curl -H "Content-Type: application/json" 'https://www.googleapis.com/storage/v1/b/?project=kubernetes-charts'
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "required",
    "message": "Anonymous users does not have storage.buckets.list access to project 634643401250.",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Anonymous users does not have storage.buckets.list access to project 634643401250."
 }
}
```
</details>

**Comment by mattatcha** [comment]
After upgrading to `2.4.2` I noticed a different error fetching `https://kubernetes-charts.storage.googleapis.com/index.yml`

```
<Error>
<Code>AccountProblem</Code>
<Message>
Your Google account is not currently enabled for this operation. Please check https://console.developers.google.com/billing to see if you have a past due balance or if the credit card (or other payment mechanism) on your account is expired. You can find additional information at https://developers.google.com/storage/docs/signup
</Message>
<Details>
The billing account for the requested project is disabled in state 'absent'
</Details>
</Error>
```

**Comment by jpds** [comment]
This has been fixed

**Comment by prydonius** [comment]
Since this appears to be fixed now, I'm going to close this out. Please reopen this if you are stilling seeing this.
