### ISSUE TITLE
[stable/ambassador] Endpoints resource missing from clusterrole

### ISSUE THREAD

**Issue by bpehling** [helm/charts#13217]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
helm: 2.11.0
kubernetes: 1.12.7

**Which chart**:
Ambassador chart version 2.2.0

**What happened**:
Ambassador containers fail to init on clean install with error:
endpoints is forbidden: User "system:serviceaccount:infra:ambassador" cannot list resource "endpoints" in API group "" at the cluster scope

**What you expected to happen**:
Container should run successfully

**How to reproduce it** (as minimally and precisely as possible):
Install Ambassador with a clean environment with the helm chart (2.2.0)

**Anything else we need to know**:
Workaround:
manually editing the cluster role and adding "endpoints" fixes issue

**Comment by nbkrause** [comment]
https://github.com/helm/charts/pull/13218

**Comment by bpehling** [comment]
Fixed, closing  issue
