### ISSUE TITLE
[stable/kured] default image cited by chart is missing

### ISSUE THREAD

**Issue by ellieayla** [helm/charts#13227]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report.

**Version of Helm and Kubernetes**:

helm:

* Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

kubernetes:

* Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
* Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

stable/kured

**What happened**:

```
image:
  repository: quay.io/weaveworks/kured
  tag: 1.1.0
```

> requesting tags: Get https://quay.io/v2/weaveworks/kured/tags/list: unknown: Namespace weaveworks has been disabled. Please contact a system administrator.

**What you expected to happen**:

Chart mentions an image that exists

**How to reproduce it** (as minimally and precisely as possible):

Install the chart.
The chart cites an unreachable image.

**Anything else we need to know**:

`docker.io/weaveworks/kured` exists, see weaveworks/flux#1948

The image can be trivially overridden in the chart values, but the default aught to work

**Comment by alanjcastonguay** [comment]
This was fixed in commit 909f2510
