### ISSUE TITLE
[stable/nextcloud] Feature Request LDAP Support

### ISSUE THREAD

**Issue by himpierre** [helm/charts#13251]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:  v2.13.1 / v1.13.4 

**Which chart**: stable/nextcloud

**What happened**: helm chart does not support ldap authentication

**What you expected to happen**: helm chart supports setting nextcloud ldap authentication

Hello Devs.

It would be reallly nice to set LDAP Configuration via Helm Chart Values.

thanks and cheers

**Comment by chrisingenhaag** [comment]
That´s definitely something you should mention in the nextcloud/docker repo. The helm chart only uses env vars the docker image provides for configuration.
You can try to install it via helm and then just edit the config.php. It´s persistent and won´t be overwritten by future updates. But I don´t know if the official docker image provides the needed ldap php packages.

So from my side, pls close this ticket and ask the nextcloud/docker guys for that. If a mechanism for ldap config is available I´ll support a helm configurability of this values.

**Comment by himpierre** [comment]
Thank you for the answer @chrisingenhaag :-)
