### ISSUE TITLE
[stable/sonarqube] Support ingress path configuration

### ISSUE THREAD

**Issue by out-of-band** [helm/charts#13257]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Which chart**:
stable/sonarqube

The current ingress configuration supported by stable/sonarqube provides limited functionality because it does not support ingress path configuration.  Currently, the only way to configure ingress with SonarQube is at the root level (e.g., sonarqube.domain.com), where many use-cases may require an ingress path (e.g., domain.com/sonarqube).

I recommend that the ingress template be modified to allow for custom paths to be defined following the patterns used in other Helm charts such as WordPress, Jenkins, and ChartMuseum.

**Comment by out-of-band** [comment]
I am working on a PR to make the ingress paths configurable.  That's a pretty straightforward change to the `ingress.yaml` template.

However, despite the ingress setting up correctly, the SonarQube web UI will not load.  I just get the spinning loading animation forever with no errors in the logs that I can see.

Does `sonar.web.context` need to be set to match the ingress path?

I've tried setting it (both via `extraEnv` and `command: [ "-Dsonar.web.context" ]`) with no luck.  If I set `extraEnv` to match the ingress path, the pod goes into a crash loop.  If I use `command: [ "-Dsonar.web.context" ]` the pod starts but I still can't load the UI.

**Comment by Tabby** [comment]
> However, despite the ingress setting up correctly, the SonarQube web UI will not load. I just get the spinning loading animation forever with no errors in the logs that I can see.
> 
> Does `sonar.web.context` need to be set to match the ingress path?
> 
> I've tried setting it (both via `extraEnv` and `command: [ "-Dsonar.web.context" ]`) with no luck. If I set `extraEnv` to match the ingress path, the pod goes into a crash loop. If I use `command: [ "-Dsonar.web.context" ]` the pod starts but I still can't load the UI.

Did you ever solve this?

I'm using chart 2.3.0, have set all the sonarWebContext settings, but still the UI is trying to load JS from `/` and not `/sonarqube`

`spec:
  releaseName: sonarqube
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sonarqube
    version: 2.3.0
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  values:
    replicaCount: 1
    hpa:
      enabled: false
    livenessProbe:
      sonarWebContext: /sonarqube/
    readinessProbe:
      sonarWebContext: /sonarqube/
    sonarWebContext: /sonarqube/
    ingress:
      enabled: true
      annotations:
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      hosts:
        - name: someurl.uksouth.foo.azure.com
          path: /sonarqube
    extraEnv:
      sonar.web.context: /sonarqube/`

**Comment by hectoralicea** [comment]
@Tabby ;  Did you ever get this working?  I too am also having the problem of "spinning loading animation forever with no errors in the logs"

**Comment by Tabby** [comment]
@hectoralicea Nope. I just moved it to a different URL where it could live on `/` rather than `/sonarqube` :/

**Comment by out-of-band** [comment]
@Tabby @hectoralicea you can exec into your SonarQube container and use `jps -lvm` to see if the application actually started with the web context path you passed into it.

I have it working on an ingress path.  My issue was that setting `extraEnv.sonar.web.context: /sonarqube` (I'm not sure about the trailing slash in your values; I'm not using one) was causing the pod to crash.  This was a bug with SonarQube ... I filed an issue https://github.com/helm/charts/issues/13482 and resolved here: https://github.com/helm/charts/pull/13484

Also, I'm not sure about the `rewrite-target` annotation you're using here ... `/$2` would be your second capture group but you don't have any capture groups in the ingress path you posted.

And it may not be directly related, but it could be causing something upstream to fail which in turn prevents your `extraEnv` from getting passed correctly: the default `values.yaml` file in `stable/sonarqube` (and the values file I use to install) specify: `securityContext.fsGroup: 999`.

**Comment by hectoralicea** [comment]
> jps -lvm

command not found error.

```
alicehe$ kubectl exec -it -n sonar sonarqube-sonarqube-74bc9bc86d-8dg2s -- /bin/bash 
sonarqube@sonarqube-sonarqube-74bc9bc86d-8dg2s:/opt/sonarqube$ jps -lvm
bash: jps: command not found
```
