### ISSUE TITLE
multiple prometheus adaptors can not be installed into the same cluster

### ISSUE THREAD

**Issue by drewwells** [helm/charts#13259]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.31.1
K8s 1.11.9

**Which chart**:
stable/prometheus-adaptor

**What happened**:
Release failed to install b/c another one is already installed

**What you expected to happen**:
All k8s objects to be prefixed with the release name

**How to reproduce it** (as minimally and precisely as possible):
helm upgrade -i --debug --wait one stable/prometheus-adapter
helm upgrade -i --debug --wait two stable/prometheus-adapter

**Anything else we need to know**:

**Comment by tuckerconnelly** [comment]
Also running into this. Haven't looked too deep into this, but should probably change the ClusterRoleBindings to normal RoleBindings.
