### ISSUE TITLE
Update requirements.yaml charts for stable/airflow

### ISSUE THREAD

**Issue by cBournhonesque** [helm/charts#13262]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature Request

The postgres and redis charts that are installed from the airflow requirements.yaml are very outdated. I had some trouble to see what extra parameters I had to use in the `postgresql` section of the values.yaml file because I couldn't simply go on the github page of the postgresql chart to know what the values.yaml should look like.

I think it would be for the best to update the requirements.yaml to later versions of these charts

For instance, the version 0.13.1 of the postgresql chart prevents me from setting `listen_addresses: "'*'"` in the postgresConfig attribute because of it cannot parse the `*` character; this is fixes in later versions of the chart.

**Comment by ramkrishnan8994** [comment]
@cBournhonesque, @naseemkullah  - 
Please look at this issue - https://github.com/helm/charts/issues/15436#issue-466762092

Will the above issue get solved by adding `listen_addresses: "'*'"` to the postgres configuration.
My connection from airflow web/scheduler gets interrupted on an adhoc basis. On restart, its working fine.

**Comment by stevenmanton** [comment]
I'm interested in this change as well. Unfortunately, it's a breaking change and I'm not sure how to handle that. (For example, the name of the key used to store the postgres password is different in the `0.13.1` version and the current version: `postgresPassword` vs `posgresqlPassword` if memory serves.)

**Comment by javefang** [comment]
@stevenmanton can we look at upgrade to `0.14.4` which still uses `postgresPassword`? The reason I need this is because the postgresql chart fixed a bug in `0.14.1` (https://github.com/helm/charts/pull/6055/files), which generates broken yaml when using `helm template`.

**Comment by stevenmanton** [comment]
@javefang it wouldn't be my call whether to update the chart or not. It seems like the right thing to do, though. Someone would have to do put together a PR.

Honestly, I've stepped away from this chart because there are many issues that are hard to fix. You might look into using Helmfile to manage the Airflow chart (with Postgres disabled) and the newer version of the Postgres chart. Helmfile just makes it easy to manage multiple charts.
