### ISSUE TITLE
Add @mfpierre as Trusted Collaborator

### ISSUE THREAD

**Issue by mfpierre** [helm/charts#13279]
Hi,

In the same fashion as https://github.com/helm/charts/issues/13120 I'm also working at Datadog and one of the owners of the Datadog chart: 

https://github.com/helm/charts/blob/a5b16939ebc25a09200c36d2feb37e69674c907a/stable/datadog/OWNERS#L11

An would like to be added as a trusted collaborator to speed up the development on the Datadog Chart.

Thanks! 🙇 

Sponsor: @hkaj

**Comment by hkaj** [comment]
👍

**Comment by mfpierre** [comment]
Hey @mattfarina could you have a look at this one ? 🙏 (similar to #13120)

**Comment by mattfarina** [comment]
Invitation sent. Sorry for the delay.
