### ISSUE TITLE
[stable/sentry] make /var/lib/sentry/files a persistent volume

### ISSUE THREAD

**Issue by gboor** [helm/charts#13285]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Which chart**: stable/sentry

**What happened**: I tried to upload a file to sentry for a source map and sentry-cli just hung forever. The logs of sentry-worker shows that it could not create the file in /var/lib/sentry/files

**What you expected to happen**: File upload to succeed

**How to reproduce it** (as minimally and precisely as possible):
1. Install sentry using chart
2. Try to upload a file using sentry-cli

**Anything else we need to know**:
Sentry apparently stores uploaded files in /var/lib/sentry/files, but that mount needs to be shared across the various pods; at least worker and web need access to it (read and write).

**Comment by silvez-dh** [comment]
maybe a moment to use another storage option for sentry? https://github.com/getsentry/sentry/blob/c269e6cbb41bf4e22ad4c9fe633d01ea7cb8c549/src/sentry/data/config/config.yml.default#L60

**Comment by gboor** [comment]
This is not currently easily possible with the chart as far as I am aware.

There is a pull request to implement this, but there appear to be some issues;

https://github.com/helm/charts/pull/11153
