### ISSUE TITLE
[stable/mariadb] BUG REPORT: fail to re-deploy

### ISSUE THREAD

**Issue by QwertyJack** [helm/charts#13300]
**Is this a request for help?**:
Yeap
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
v2.13.1@618447cbf203d147601b4b9bd7f8c37a5d39fbb4

**Which chart**:
stable/mariadb

**What happened**:
Everything is OK during the first time deploy; but fails if deploy again.

**What you expected to happen**:
Further deploy is successful.

**How to reproduce it** (as minimally and precisely as possible):
- First deploy:
```bash
helm install --name mydb stable/mariadb
```
It works like a charm.
- Then try to deploy again; to delete and re-deploy, or add some parameter and upgrade:
```bash
helm delete --purge mydb
helm helm install --name mydb stable/mariadb
```
Then the pod of mariadb keeps crashing.

**Anything else we need to know**:
Change another release name solve the problem. But if I want to tweak parameters, it fails.
If I turn off replicas the problem still exists.

**Comment by QwertyJack** [comment]
Solved by deleting pvc.
BTW: Somehow `helm delete --purge` keeps pvc which is the root cause.

**Comment by javsalgar** [comment]
Hi,

Yes. By definition, the PVCs created by a StatefulSet are not deleted when deleting it. These are meant to be deleted manually
