### ISSUE TITLE
[stable/postgresql] Using non 5432 service.port will not work

### ISSUE THREAD

**Issue by isen-ng** [helm/charts#13303]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm: 2.12.3
minikube: 1.0.0

**Which chart**:
stable/postgresql
version: 3.18.1

**What happened**:
If i set the `service.port` to something other than `5432`, eg `2345` other pods will not be able to connect to the postgres server

**What you expected to happen**:
Other pods can connect to the server over specified pod

**How to reproduce it** (as minimally and precisely as possible):
```
helm install \
  --name postgresql-1 \
  --set postgresqlDatabase=postgres \
  --set postgresqlUsername=postgres \
  --set postgresqlPassword=postgres123 \
  --set servicePort=2345 \
  stable/postgresql;
```

```
helm install \
  --name postgresql-2 \
  --set postgresqlDatabase=postgres \
  --set postgresqlUsername=postgres \
  --set postgresqlPassword=postgres123 \
  --set servicePort=5432 \
  stable/postgresql;
```

From `postgres-1` this command succeeds to connect:
```
$ psql -h postgresql-2-postgresql -p 5432 -U postgres -W postgres
Password for user postgres:
psql (10.7)
Type "help" for help.

my_database=>
```

From `postgres-2` this command fails to connect:
```
$ psql -h postgresql-1-postgresql -p 2345 -U postgres -W postgres
Password for user postgres:
<hangs>
```

From a third pod with `nc` installed
```
# successfully connected to server-1 2345 (port is open)
$ nc -zv postgresql-1-postgresql 2345

# successfully connected to server-2 5432 (port is open)
$ nc -zv postgresql-2-postgresql 5432
```

**Anything else we need to know**:

**Comment by tompizmor** [comment]
Hi @isen-ng,

The key `servicePort` does not exist in the values.yaml. You should use `service.port` when installing the chart. 

In any case, I tried with the correct key and it didn't work either. The port information is not being passed to the docker image so it is always configured in the same port (5432). We will further check this issue and let you know once we have more information.

**Comment by isen-ng** [comment]
> The key servicePort does not exist in the values.yaml. You should use service.port when installing the chart.

Yes, it's bad copy, pasting and redacting on my side. I have been using `service.port` and it does not work.

I'm not terribly sure as im not well versed in kubernetes but is the issue here in
https://github.com/helm/charts/blob/master/stable/postgresql/templates/statefulset.yaml#L154
```yml
        ports:
        - name: postgresql
           containerPort: {{ template "postgresql.port" . }}
```
the `containerPort` should be tied to the `hostPort`??

**Comment by tompizmor** [comment]
I took a quick look to docker image and I think the issue is there. 

@javsalgar can you check if this issue is fixed after the changes you are implementing?

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. My question would be, would you like the postgresql container port to be different from 5432. It looks to me that what you want to change is the service, not the containerport itself

**Comment by tompizmor** [comment]
@isen-ng The previous PR that is already merged should have fixed the issue.
