### ISSUE TITLE
[stable/prometheus-operator] Targets are down on GKE (status 401 Unauthorized & connection refused)

### ISSUE THREAD

**Issue by occelebi** [helm/charts#13302]
**Is this a request for help?**:
Yes
---

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

**Which chart**:
prometheus-operator

**What happened**:
There are no kubelets (cadvisor) and coredns endpoints in Prometheus UI on Google kubernetes engine.
Kubelets give `server returned HTTP status 401 Unauthorized`
Coredns gives `Get http://IP:PORT/metrics: dial tcp 10.IP:PORT: connect: connection refused`

**How to reproduce it** (as minimally and precisely as possible):

helm install stable/prometheus-operator --name=monitoring --namespace=monitoring

**Comment by Pamir** [comment]
Hi 

This should work.
coreDns:
  enabled: true
  service:
    port: 10054
    targetPort: 10054
    selector:
      k8s-app: kube-dns

**Comment by occelebi** [comment]
Thanks @Pamir. Prometheus can scrape from coreDns but kubelets are still failing as we did not touch it. Do you have any idea on kubelet's error (`server returned HTTP status 401 Unauthorized`)

**Comment by occelebi** [comment]
For future googlers:

Edit servicemonitor: (**monitoring-prometheus-oper-kubelet**)
https://github.com/coreos/prometheus-operator/issues/926#issuecomment-374781066
