### ISSUE TITLE
[stable/prometheus-operator] Add namespace information to the TargetDown alert

### ISSUE THREAD

**Issue by marcindulak** [helm/charts#13335]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

The TargetDown alert does not list the namespace and therefore:

- the alert message does not provide the necessary context - one needs to guess the namespace
- the alert cannot be further filtered out based on the namespace 

https://github.com/helm/charts/blob/f6974d6307f964267df39cf1a77daf8e075082f5/stable/prometheus-operator/templates/prometheus/rules/general.rules.yaml#L23-L26

**Version of Helm and Kubernetes**:

helm-2.8.1
k8s-1.10.6

**Which chart**:

stable/prometheus-operator

**What happened**:

**What you expected to happen**:

If possible, more context of the alert should be provided in the alert.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by vsliouniaev** [comment]
Alerts are sourced from upstream repositories, originating with the kubernetes-mixin project. You're free to customize alerts in whatever way you wish, but if you would like to change the defaults, please ask in the source project
