### ISSUE TITLE
Typo in secret name when additionalScrapeConfigsExternal is enabled

### ISSUE THREAD

**Issue by nickytd** [helm/charts#13368]
When additionalScrapeConfigsExternal: true is enabled in prometheusSpec

https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/additionalScrapeConfigs.yaml

The secret which is looked is prometheus-oper-prometheus-scrape-confg
where it should be prometheus-oper-prometheus-scrape-config

**Comment by vsliouniaev** [comment]
This is a fair point. I think it's worth keeping the typo as changing this would be more disruptive than useful
