### ISSUE TITLE
coredns doesn't deploy if  loadbalancer is metallb

### ISSUE THREAD

**Issue by marklester** [helm/charts#13383]
BUG REPORT

**Version of Helm and Kubernetes**:
k8s: 1.14.1
helm: 2.13,1

**Which chart**:
stable/coredns

**What happened**:
try to deploy but failed with:
```
is invalid: spec.ports: Invalid value: []core.ServicePort{core.ServicePort{Name:"udp-53", Protocol:"UDP", Port:53, TargetPort:intstr.IntOrString{Type:0, IntVal:53, StrVal:""}, NodePort:0}, core.ServicePort{Name:"tcp-53", Protocol:"TCP", Port:53, TargetPort:intstr.IntOrString{Type:0, IntVal:53, StrVal:""}, NodePort:0}}: cannot create an external load balancer with mix protocols
```

**How to reproduce it** (as minimally and precisely as possible):
install coredns with value override of 
```
serviceType: "LoadBalancer"
loadBalancerIP: "assignable ip"
```

**Anything else we need to know**:
k8s doesn't like  service port on both tcp and udp for loadbalancer type services: https://metallb.universe.tf/usage/#ip-address-sharing

To resolve I believe 2 services need to be made one for udp and one for tcp
or wait til
https://github.com/kubernetes/kubernetes/issues/23880
is resolved

**Comment by dano0b** [comment]
workaround which work for me:
```
      servers:
        - zones:
            - zone: .
              scheme: dns://
              use_tcp: false
```

**Comment by rayterrill** [comment]
@dano0b's workaround worked for me as well. Thanks mate.
