### ISSUE TITLE
[stable/prometheus-operator] grafana graphs are broken again

### ISSUE THREAD

**Issue by dioguerra** [helm/charts#13409]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: stable/prometheus-operator

**What happened**: updated from 5.1.0 to 5.3.0

**How to reproduce it** (as minimally and precisely as possible):
values.yaml> http://paste.openstack.org/show/750115/
helm install stable/prometheus-operator --namespace kube-system --name prometheus-operator --version v5.3.0 --values values.yaml

**Comment by logicbomb421** [comment]
I might be having this issue myself, though the original description is a bit vague.

Installed prometheus-operator via helm with the `values.yaml` provided in the repo. I'm able to access and query prometheus without issue when port-forwarding 9090, however when port-forwarding grafana, all the pre-built queries time out.

Oddly I tested this chart out a few weeks ago and it all worked very well out-of-the-box, it wasn't until I went to actually install it in my real cluster that this issue appeared.

### Info
Helm Version:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```
K8S Version:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:23:04Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
Chart Version: **5.5.0**

**Comment by MrD2** [comment]
For me the graphs Most of the charts are ok. But some of them are missing values (mainly the last 2 from the grafana defaults). I suspect it's the new time series created by the evaluation rules

**Comment by MrD2** [comment]
with chart stable/prometheus-operator:5.5.0 works for me. 

Closing
