### ISSUE TITLE
stable/apm-server issue title

### ISSUE THREAD

**Issue by tnimni** [helm/charts#13459]
**Describe the bug**
helm fetch stable/apm-server --untar download version 0.1.0
chart version in github repo is 2.0.1

**Version of Helm and Kubernetes**:

kubernetes version 1.12

Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
**Which chart**:
stable-apm-server

**What happened**:
helm download wrong chart version

**What you expected to happen**:
helm download right chart version

**How to reproduce it** (as minimally and precisely as possible):
helm fetch stable/apm-server this will download the wrong version

**Anything else we need to know**:

**Comment by Towmeykaw** [comment]
Have you ran a helm repo update?
