### ISSUE TITLE
stable/mongodb - replicaset with single node always produces a SECONDARY

### ISSUE THREAD

**Issue by andrei-dascalu** [helm/charts#13461]
**Describe the bug**

**Version of Helm and Kubernetes**:

kubernetes: 1.12.7
helm: 2.13.1

**Which chart**:

stable/mongodb

**What happened**:

edit provided values file  with the following:
- image.debug: false
- usePassword: true
- mongodbDirectoryPerDB: false
- replicaSet.enabled: true
- replicaSet.replicas.secondary: 0
- replicaSet.replicas.arbiter: 0
- replicaSet.pdb.minAvailable.primary: 1
- replicaSet.pdb.minAvailable.secondary: 0
- replicaSet.pdb.minAvailable.arbiter: 0

The result was a replica set with a single pod called `mymongo-mongodb-primary-0`, but when logging into that mongopod, it would say `SECONDARY` rather than `PRIMARY` and any mongdb client would reject queries with error "not master"

**What you expected to happen**:

Have a replica set with a single replica that is a master 

**How to reproduce it** (as minimally and precisely as possible):

Perform the edits as per "what happened" section, then:

helm install \
  --name mymongo \
  --set mongodbRootPassword="rootPass" \
  --set mongodbUsername="userOne" \
  --set mongodbPassword="passwordOne" \
  --set mongodbDatabase="userOne" \
  -f values.yml \
  stable/mongodb

**Anything else we need to know**:

**Comment by tompizmor** [comment]
Hi! I tried to reproduce the issue using your values modifications and your install command. However, I don't get the same result.

In the primary log I see this line

```
2019-05-03T13:24:57.028+0000 I REPL     [replexec-0] transition to PRIMARY from SECONDARY
```

And if I connect to the pod the mongodb node is actually a primary node:

```
mongo
MongoDB shell version v4.0.9
connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("5636424d-cc81-42e6-86fd-c76509ac1e88") }
MongoDB server version: 4.0.9
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	http://docs.mongodb.org/
Questions? Try the support group
	http://groups.google.com/group/mongodb-user
2019-05-03T13:31:52.897+0000 I STORAGE  [main] In File::open(), ::open for '//.mongorc.js' failed with Unknown error
rs0:PRIMARY>
```

Can you reproduce this issue consistently? Or it only happens sometimes?
