### ISSUE TITLE
[stable/jenkins] wrong deprecation message of Master.JCasC.ConfigScripts

### ISSUE THREAD

**Issue by eh-am** [helm/charts#13467]
**Describe the bug**
Deprecation message for `Master.JCasC.ConfigScripts` is wrong

`(deprecation.yaml)`
```
        {{- if .Values.JCasC }}
            {{- if .Values.JCasC.ConfigScripts }}
               {{ fail "`Master.JCasC.ConfigScripts` does no longer exist. It has been renamed to `master.loadBalancerSourceRanges`" }}
            {{- end }}
        {{- end }}
```
it should be `master.JCasC.configScripts`

**Which chart**:
stable/jenkins

**Comment by torstenwalter** [comment]
Looks like a copy and paste mistake. Would you mind creating a PR which fixes it?

**Comment by eh-am** [comment]
sure!

just to be sure, do we need to bump the version in this case? @torstenwalter
