### ISSUE TITLE
[incubator/couchdb] Document need for prehashed COUCHDB_PASSWORD for cookie authentication

### ISSUE THREAD

**Issue by joshperry** [helm/charts#13480]
If COUCHDB_PASSWORD value is not prehashed, then couchdb on each instance will hash it on startup with a random salt. This causes an authentication cookie from one node to not work on another.

See apache/couchdb-docker#9 (took me a couple hours to find...)

**Comment by joshperry** [comment]
Actually, there is another part to this problem. The couchdb-statefulset-assembler sidecar needs the non-hashed version of this password, so just simply hashing the password in the secret will break autoformation. There will need to be a hashed and unhashed version of the password in the secret, and the nonhashed version should be used in the environment of the sidecar.

**Comment by willholley** [comment]
CouchDB 2.3.1 adds [seedlist](http://docs.couchdb.org/en/stable/config/cluster.html#cluster/seedlist) to the configuration which should allow the ss assembler sidecar to be removed. If we get that done, you should be okay to submit the pre-hashed password though it still seems a bit icky.

It seems like we need to allow a shared salt to be passed as a chart value.
