### ISSUE TITLE
[stable/jenkins] Error: Error: UPGRADE FAILED: no Role with the name "jenkins-schedule-agents" found

### ISSUE THREAD

**Issue by ricardompcarvalho** [helm/charts#13490]
I'm currently trying to upgrade the version of the chart because of best practices and changing the names to the correct ones when I do `helm upgrade ...` I get this error below.
```
UPGRADE FAILED
ROLLING BACK
Error: no Role with the name "jenkins-schedule-agents" found
Error: UPGRADE FAILED: no Role with the name "jenkins-schedule-agents" found
```
I have already checked and there is the role with the name jenkins-schedule-agents, in fact, when I did the helm upgrade he created me this role.

If you need more information please tell me!!

**Comment by torstenwalter** [comment]
Did you follow the upgrade guide and removed the deployment first?
https://github.com/helm/charts/tree/master/stable/jenkins#100

The error message is something I got in the past when not following it. I had to delete the deployment and also all object which have been created during the failed upgrade.

**Comment by ricardompcarvalho** [comment]
@torstenwalter thanks for reply, i already did it :+1:  Thanks once more
