### ISSUE TITLE
[stable/redis-ha] redis exporter not working

### ISSUE THREAD

**Issue by ray-haggerty** [helm/charts#13510]
**Describe the bug**
Redis exporter crashes for unknown reason

**Version of Helm and Kubernetes**:
```
~> helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```
```
~> kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
redis-ha

**What happened**:
When deploying redis-ha with the exporter set to enabled the export will die unexpectedly

**What you expected to happen**:
The redis exporter will not die 

**How to reproduce it** (as minimally and precisely as possible):
in values.yaml set exporter.enabled: true 

**Anything else we need to know**:

**Comment by juan131** [comment]
Hi @ray-haggerty 

This PR affects the `redis-ha` chart, doesn't it? 

If so, please update the title to reflect the right chart `[stable/redis-ha]`. It's very important so the maintainers of the corresponding chart can easily identify what issues to respond.

**Comment by ray-haggerty** [comment]
@juan131 You are right my mistake,  title has been updated!

**Comment by shield007** [comment]
I'm also seeing this issue in our cluster. I've not had much chance to dig into it, but i suppect it's the redis host the export uses.  

https://github.com/helm/charts/blob/839b667a710ac27c262bf35574fdd1d366796e2a/stable/redis-ha/templates/redis-ha-statefulset.yaml#L205

This should be using the address of a redis instance?
