### ISSUE TITLE
[stable/kong] make waitImage configurable in all files

### ISSUE THREAD

**Issue by marcwolff** [helm/charts#13527]
**Is your feature request related to a problem? Please describe.**
waitImage is´nt configurable in all files. In the migration files is busybox hard coded

**Describe the solution you'd like**

```
initContainers:
       - name: wait-for-postgres
         image: "{{ .Values.waitImage.repository }}:{{ .Values.waitImage.tag }}"
```

**Comment by hbagdi** [comment]
The fix is is in #13595. Thank you for reporting!
