### ISSUE TITLE
stable/mongodb related to picking passwords and key from existing secrets for replicaset

### ISSUE THREAD

**Issue by polganesh** [helm/charts#13531]
**is it request for help**
Yes

**what information i am looking for?**
currently i am trying to explore how stable/mongodb can be use as replica set for high availability
while checking values.yaml i observed following

```
# existingSecret: name-of-existing-secret

## MongoDB admin password
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#setting-the-root-password-on-first-run
##
# mongodbRootPassword:

## MongoDB custom user and database
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#creating-a-user-and-database-on-first-run
##
# mongodbUsername: username
# mongodbPassword: password
# mongodbDatabase: database

## Key used for replica set authentication
  ##
  # key: key
```

**my queries**

- is mongodb mongodbRootPassword will be picked up from existingSecret?
- is mongodbPassword will be picked up from existingSecret?
- as per my understanding key is kind of token used for authentication. can we fetch it from existing secret
- what will be mongodb url for connecting this replicaset

**Comment by juan131** [comment]
Hi @polganesh 

Here you have some reponses:

> is mongodb mongodbRootPassword will be picked up from existingSecret?
> is mongodbPassword will be picked up from existingSecret?

When **existingSecret** is selected, both parameters will be ignored, and the values will be picked up from the existing secret.

> as per my understanding key is kind of token used for authentication. can we fetch it from existing secret

When **existingSecret** is selected, it will be ignored too, using the one available in the existing secret.

> as per my understanding key is kind of token used for authentication. can we fetch it from existing secret


> what will be mongodb url for connecting this replicaset

I'll be displayed after installing the chart. It's calculated depending on your settings (e.g. you're using a ClusterIP service or a LoadBalancer one)

**Comment by polganesh** [comment]
Hi @juan131 
one query in context of this thread.

- is defining key is mandatory for replicas.?
- i am planning to use this chart as subchart. what will be consequence of omitting  key?
- will it impact authentication url from deployment?
