### ISSUE TITLE
[stable/wordpress] Update mariadb dependency

### ISSUE THREAD

**Issue by andreisergiu98** [helm/charts#13535]
**Describe the bug**
I'm trying to use an existing claim for mariadb, but this bug is preventing me to do so 
https://github.com/helm/charts/issues/10322 (basically the pod for mariadb doesn't start). This is a mariadb bug which was fixed with this pr https://github.com/helm/charts/pull/10378, but the wordpress chart is not using the release of mariadb which contains the fix. I updated the dependency locally and it works fine.

**Which chart**:
wordpress

**Anything else we need to know**:
Thank you in advance for your support. :)

**Comment by juan131** [comment]
Hi @andreisergiu98 

Thanks for reporting it. I just created a PR to update the **requirements.lock** file
