### ISSUE TITLE
[stable/kafka-manager] Kafka Manager bootstrap not connect with Kafka Manager

### ISSUE THREAD

**Issue by jonatasfreitasv** [helm/charts#13548]
Kafka Boostrap cant connect to Kafka Mananger because his try to connect in service kafka-manager service but this real service is kafka-manager.backoffice, with namespace, how i say that in values.yaml?

**Comment by samuelb** [comment]
Hello

As long the bootstrap job and kafka-manager is deployed in the same namespace, explicit name the namespace of the service is not required. And if you didn't do something really odd, both are deployed in the namespaces. If not, can you give us a bit more insight into you setup please?

Can it be that you changed the service port number to something different than 9000? The service port number is hard-coded in the bootstrap job. Changing it for the service will break the bootstrap job. I just stumbled over this problem, also #13615 is about that. I opened a PR #14165 to address this. So if you changed the port number, you might want to update the helm chart once my PR got merged.
