### ISSUE TITLE
[stable/postgresql]Warning FailedScheduling 17s (x3 over 17s) default-scheduler pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by booboothefool** [helm/charts#13562]
on IBM Cloud, helm install --name my-release stable/postgresql gives me this error and the pod stays stuck in Pending.

Can someone suggest example of how to set up the PV/PVC and use with helm command?

**Comment by carrodher** [comment]
Can you execute the following commands?
```
kubectl describe pod {PODNAME}
kubectl logs {PODNAME}
```
Replacing `{PODNAME}` by the name that appears in the output of `kubectl get pods`
