### ISSUE TITLE
[stable/sonatype-nexus]  Google service account for GCS backups

### ISSUE THREAD

**Issue by emiioan** [helm/charts#13570]
Hello.

At this moment, nexus-backup container suports just the admin password as secret to connect to nexus container and assumes that you are using node serviceaccount to upload backups to GCS bucket. 

It will be nice for nexus-backup container to have the option to mount a secret for a google service account that has restrict access to GCS bucket for backup uploads.

**Comment by Nosmoht** [comment]
Hi,

we have the same problem. I would like to use the GCP GKE Workload identity which requires to use a service account within the pods. This seems currently not be possible. Would be great to have the possibility to define a service account within the chart.
