### ISSUE TITLE
Applying to be a trusted collaborator

### ISSUE THREAD

**Issue by srueg** [helm/charts#13575]
I'd like to apply to become a trusted collaborator on the Helm org. We at [vshn](https://vshn.ch) use Helm a lot and often create PRs to create and improve stable Helm charts.
I'll be at KubeCon Barcelona (and VSHN is sponsoring) if you'd like to chat :smiley:

**Comment by srueg** [comment]
@unguiculus if you could take a look at this :pray: :+1: 
I'm not really familiar with the process, so if there's more information needed I'm happy to provide it.

**Comment by unguiculus** [comment]
Are you maintainer of a specific chart? Or would you be interested in becoming a charts maintainer?

**Comment by srueg** [comment]
I'd maintain the K8up chart: https://github.com/helm/charts/pull/13314
Also I'm working on an overhaul of the stable/rocketchat chart which I then could maintain

**Comment by unguiculus** [comment]
Invite sent. I noticed maintainer in `Chart.yaml` and `OWNERS` don't match. Could you fix that?

**Comment by srueg** [comment]
I didn't get any invite so far... Updated the `Chart.yaml` and `OWNERS` file.

**Comment by unguiculus** [comment]
My bad. I had picked the wrong person.
