### ISSUE TITLE
[stable/prometheus-operator] can't install it successfully

### ISSUE THREAD

**Issue by moluzhui** [helm/charts#13592]
**Describe the bug**

**Version of Helm and Kubernetes**:
Helm v2.13.1 and Kubernetes v1.14.0

**Which chart**:
stable/prometheus-operator

**What happened**:
can't install it
```
k8s1@k8s-master:~$ helm install --name prometheus-operator-release stable/prometheus-operator
Error: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" is forbidden: User "system:serviceaccount:kube-system:default" cannot delete resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

**What you expected to happen**:
install successfully

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by cybervagabond** [comment]
any progress in this issue?
