### ISSUE TITLE
[stable/kibana] Unable to install monitoring with Kibana chart

### ISSUE THREAD

**Issue by aangelog** [helm/charts#13610]
**Describe the bug**
I am trying to install Kibana on my Kubernetes cluster for monitoring Elasticsearch. The install works fine but there is no Monitoring app there and I can not find any way to enable/install it (I guess this has to do with xpack not being installed by default?). I do see Dev Tools/Management tabs but Monitoring is essential. The Monitoring app comes by default with Kibana i.e. when install via docker.

**Version of Helm and Kubernetes**:
Helm:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Kubernetes:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/kibana

**What happened**:
No Monitoring app on kibana by default - no way to install/enable it

**What you expected to happen**:
I would expect Monitoring is up/installed by default 

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/kibana --version 1.0.2 --set env.ELASTICSEARCH_URL=http://es-ip:9200

export POD_NAME=$(kubectl get pods --namespace default -l "app=kibana,release=wayfaring-sloth" -o jsonpath="{.items[0].metadata.name}")

kubectl port-forward --namespace default $POD_NAME 5601:5601

Visit localhost:5601 and observe the apps/tabs available on the left side.

**Anything else we need to know**:

**Comment by camilorivera** [comment]
@aangelog by default the chart use the image docker.elastic.co/kibana/kibana-oss which doesn't support the monitoring app specify the image docker.elastic.co/kibana/kibana and you will be able to install the monitoring app.
