### ISSUE TITLE
[stable/magento] can't install magento with ingress definition

### ISSUE THREAD

**Issue by Mattzr** [helm/charts#13611]
**Describe the bug**
Installing magento via helm fails if ingress definition is specified in values.yml or as parameter. Helm returns an error:

Error: render error in "magento/templates/ingress.yaml": template: magento/templates/ingress.yaml:8:24: executing "magento/templates/ingress.yaml" at <{{template "magento....>: template "magento.chart" not defined
Error: UPGRADE FAILED: render error in "magento/templates/ingress.yaml": template: magento/templates/ingress.yaml:8:24: executing "magento/templates/ingress.yaml" at <{{template "magento....>: template "magento.chart" not defined

I suspect magento.chart doesn't exist in the template. Ingress template could be {{ .Chart.Name }} instead.

**Version of Helm and Kubernetes:**

helm: v2.13.1
kubernetes: v1.11.8-gke.6
Which chart:
stable/magento

**What happened:**
Ingress was added but it seems to be broken

**What you expected to happen:**
Magento to successfully install in kubernetes with Ingress resource.

**How to reproduce it (as minimally and precisely as possible):**
add ingress into values.yaml (below), or run `helm install --set ingress.enabled=true .`:

ingress:
  enabled: true
  certManager: true
  annotations:
   kubernetes.io/ingress.class: nginx

  hosts:
  - name: magento.local
    path: /

    tls: false
    tlsSecret: magento.local-tls

**Anything else we need to know:**

**Comment by carrodher** [comment]
Thanks for the fix! I just added the proper tags to the PR, let's wait for the bot to merge it
