### ISSUE TITLE
stable/chart : Version 3.18.4  postgres image : 10.7.0

### ISSUE THREAD

**Issue by sathyu** [helm/charts#13617]

**Comment by prydonius** [comment]
it looks like `replication.password` is being set, so not sure why the initialisation is failing.

any ideas, @javsalgar?

**Comment by miguelaeh** [comment]
Hi @sathyu ,
You set the `usePasswordFile: true`, if this is true, the replication password is going to be taken from the file `/opt/bitnami/postgresql/secrets/postgresql-replication-password` and not from the environment variables. You can see that in the template:
> {{- if .Values.usePasswordFile }}
        - name: POSTGRES_REPLICATION_PASSWORD_FILE
          value: "/opt/bitnami/postgresql/secrets/postgresql-replication-password"
        {{- else }}
        - name: POSTGRES_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "postgresql.secretName" . }}
              key: postgresql-replication-password
        {{- end }}

As you can see, it is going to take the password from the file and not from the env var.
Did you set the password on this file?

**Comment by sathyu** [comment]
Thanks for the reply.

I set   userPasswordFile: false and given password in values.yaml file , now I am seeing below error:

2019-05-09 15:24:34.777 GMT [938] FATAL:  password authentication failed for user "repl_user"
2019-05-09 15:24:34.777 GMT [938] DETAIL:  Role "repl_user" does not exist.
	Connection matched pg_hba.conf line 95: "host     all             all             0.0.0.0/0

**Comment by sathyu** [comment]
I  created repl_user with replication and login allowed  after master pod came up.  Replication started happening.     Closing this issue.
Lesson learnt:   Just use stable/chart and deploy postgres.
                         login to master pod
                         execute this command at psql prompt
                         create role repl_user  with replication login;
                         this repl_user is what is mentioned in the values.yaml file.
Thanks
