### ISSUE TITLE
[stable/prometheus-operator] Enable extra(.*) args for prometheus mountings

### ISSUE THREAD

**Issue by dioguerra** [helm/charts#13642]
stable/prometheus enables a user to add parameters like  

extraVolumeMounts
extraVolumes
**extraHostPathMounts
extraConfigmapMounts
extraSecretMounts**

Because my etcd leaves outside of the cluster it cannot be auto-discovered like normal k8s pods. Also authentication is needed to access it but the prometheus does not have the required secrets mounted.

This is a feature request to implement the availability of extraSecretMounts and extraHostPathMounts on the values.yaml of the stable/prometheus-operator.

**Describe the solution you'd like**
This parameter will be added under 
- prometheus.prometheusSpec.extraHostPathMounts
- prometheus.prometheusSpec.extraSecretMounts

**Comment by vsliouniaev** [comment]
You should already be able to do this by using [`prometheusSpec.secrets` and `prometheusSpec.configMaps`](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec). Host path mounts aren't available, and would need implementation in the underlying coreos/prometheus-operator project.

**Comment by MrD2** [comment]
I shall check, thanks

**Comment by vsliouniaev** [comment]
I'm using this feature in my own deployment, should be working

**Comment by MrD2** [comment]
Yes, this worked thank you.
