### ISSUE TITLE
[stable/prometheus-operator] prometheus-oper-kubelet targets done on deleted nodes

### ISSUE THREAD

**Issue by wu105** [helm/charts#13669]
**Describe the bug**
After deleting a node from a k8s cluster, the targets on service=kubelet for endpoints https://*nodeip*:10250/metrics and https://*nodeip*:10250/metrics/cadvisor remain and in down status

**Version of Helm and Kubernetes**:
helm v2.11.0
kubernetes v1.11.3

**Which chart**:
prometheus-operator-4.1.1

**What happened**:
drained and deleted a node from a kubernetes cluster

**What you expected to happen**:
All targets on the deleted node should be removed.  A method to remove the targets left behind would also be serviceable.

**How to reproduce it** (as minimally and precisely as possible):
See what happened.

**Anything else we need to know**:
We also run heapster for the metrics on the dashboard and the kubelet top commands.

**Comment by vsliouniaev** [comment]
Could you please check if you have an endpoints object in the kube-system namespace that may be referring to the old nodes? It may be that you have had multiple installations of the prometheus-operator chart with different release names. It's possible that the prometheus-operator pod did not clean up the old kubelet service and endpoints after it was uninstalled.

**Comment by wu105** [comment]
Yes, the kubelet end point still has the removed node.
On the other hand, prometheus-prometheus-oper-kubelet is up to date.
There is only one installation through helm, using chart Prometheus-operator-4.1.1.
What would be a work around?

**Comment by vsliouniaev** [comment]
Could you please post the output of
```
 kubectl get endpoints -n kube-system -l k8s-app=kubelet
```
?

**Comment by wu105** [comment]
```
kubectl get endpoints -n kube-system -l k8s-app=kubelet
NAME                                 ENDPOINTS                                                              AGE
kubelet                              xxx.8.13.147:10255,xxx.8.13.148:10255,xxx.8.13.149:10255 + 9 more...   124d
prometheus-prometheus-oper-kubelet   xxx.8.13.147:10255,xxx.8.13.148:10255,xxx.8.13.153:10255 + 6 more...   115d
```

**Comment by vsliouniaev** [comment]
You have two sets of kubelet endpoints, one of which isn't being updated. The name suggests it was provisioned by an earlier install of the operator. There are corresponding, `service` objects too. You should delete the older ones.

**Comment by wu105** [comment]
Thanks!  I deleted the service (-l k8s-app=kubelet) with the extra ep and older creationiTimestamps and the alert went away.
