### ISSUE TITLE
stable/postgresql

### ISSUE THREAD

**Issue by shivasr** [helm/charts#13677]
**Describe the bug**
When I try to install stable/postgresql using helm the containers go into "CrashLoopBackOff" status. It seems to be working till yesterday, 9th May 2019. 

**Version of Helm and Kubernetes**:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/postgresql

**What happened**:
Upon installation of the chart the pod goes into "CrashLoopBackOff"

**What you expected to happen**:
The pod should be in running status

**How to reproduce it** (as minimally and precisely as possible):

Just run helm install stable/postgresql

**Anything else we need to know**:

**Comment by juan131** [comment]
Hi @shivasr 

What version the Helm chart and what version of the Bitnami Docker PostgreSQL image are you using?

**Comment by shivasr** [comment]
This is the version of the helm:

`Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}`

For the Bitnami Docker PostgreSQL - I just did try to install postgresql using `helm install stable/postgresql`

I think it's now working. Without any changes, it started working! Looks like new PostgreSQL image was still intermediate and when we try to pull it. it caused deployment issues.

**Comment by juan131** [comment]
Hi @shivasr 

> This is the version of the helm

I was talking about the version of the PostgreSQL chart. You can obtain the version of the chart by running: `helm search stable/postgresql`

> I think it's now working.

That's great! Please do not hesitate to let us know if you face any new issue.

**Comment by shivasr** [comment]
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
stable/postgresql       3.18.0          10.7.0          Chart for PostgreSQL, an object-relational database manag...

This is the version details.
