### ISSUE TITLE
[stable/jenkins] warning when overriding initscripts

### ISSUE THREAD

**Issue by peterbosalliandercom** [helm/charts#13672]
**Describe the bug**
In the latest chart (1.1.16) when overriding initscripts: a warning appears when running helm template.

**Version of Helm and Kubernetes**:
helm version 2.13.1

**Which chart**:
jenkins

**What happened**:
when changing 
  `initscripts: `
to
  ```
    initScripts:
      test: |-
         blah blaAh peter groovy
```

a warning appears:
 helm template -f values.yaml -f helm-config-test.yaml .  | grep peter
2019/05/10 08:28:30 Warning: Merging destination map for chart 'jenkins'. The destination item 'initScripts' is a table and ignoring the source 'initScripts' as it has a non-table value of: <nil>
    blah blaAh peter groovy

rendered template is correct: 
  inittest.groovy: |-
    blah blaAh peter groovy

**What you expected to happen**:
rendered template without warning. 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I think the solution is changing the default values.yaml like this

initscripts;

change to:

initscripts: {}

**Comment by torstenwalter** [comment]
Please try it like this:

```
    initScripts:
      - |
        import org.jenkinsci.plugins.authorizeproject.ProjectQueueItemAuthenticator
        import jenkins.security.QueueItemAuthenticatorConfiguration
        ...
```

That actually works for me. Using it as a list also allows you to separate different init scripts.

**Comment by torstenwalter** [comment]
Just checked the `values.yaml`. The example there is also a list.
https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml#L166-L168

**Comment by peterbosalliandercom** [comment]
Alright. My confusion was that I had to name the key of the list myself      
It works fine indeed like this way:
```
    initScripts:
      - |
        import hudson.EnvVars;
      - |
        #!groovy
```

resulted in this:
```
  init0.groovy: |-
    import hudson.EnvVars;
--

  init1.groovy: |-
    #!groovy
--
```
