### ISSUE TITLE
[stable/hadoop] YARN UI Reverse Proxy

### ISSUE THREAD

**Issue by ramkrishnan8994** [helm/charts#13671]
From the YARN UI if I click on any of the links, Eg: History, Logs, Node etc. It gets redirected to the pod service endpoint which would not be accessible - 
`**hdfs-yarn-hadoop-yarn-nm-0.hdfs-yarn-hadoop-yarn-nm.testing.svc.cluster.local**`

Spark UI has a reverse proxy configuration for the UI which solves the issue -
```
spark.ui.reverseProxy
spark.ui.reverseProxyUrl
```

Does the YARN UI also support anything like this.
There is an option to setup a Web Proxy - https://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/WebApplicationProxy.html
Will this solve the issue?

If yes, then this would require a separate deployment for the Proxy as a pod. Correct me if I'm wrong.

**Comment by ramkrishnan8994** [comment]
@paulczar

**Comment by ramkrishnan8994** [comment]
@paulczar @pfisterer Can anyone help me with this

**Comment by pfisterer** [comment]
@ramkrishnan8994 Not sure if this helps, but Apache Knox could potentially support your use case (cf. https://community.hortonworks.com/questions/114618/how-to-access-the-yarn-ui-through-knox-default-gat.html). 

However, this requires https://github.com/helm/charts/pull/13142 to be accepted before I can contribute my helm chart for Apache Knox - maybe @paulczar can have a look at this one and label it `ok-to-test`.

**Comment by ramkrishnan8994** [comment]
@pfisterer - The link says that it still does not support logs from NodeManager.
Without NodeManager there wont be any logs for the user to view

**Comment by pfisterer** [comment]
@ramkrishnan8994 I didn't try it out yet. Where exactly did you find this statement reg. the NodeManager? Maybe I overlooked it.

**Comment by ramkrishnan8994** [comment]
@pfisterer  
https://community.hortonworks.com/questions/194473/yarn-app-logs-through-knox.html

**Comment by pfisterer** [comment]
Ok, sorry. In this case I don't have any clue...

**Comment by ramkrishnan8994** [comment]
@pfisterer - Okay. Can you help me with this
I tried setting up **Spark history server** and access the logs that YARN creates on HDFS.

![image](https://user-images.githubusercontent.com/40425959/60257241-b5bac500-98f0-11e9-985f-153acd34f05f.png)

The Logs are generated in the given location. **spark.history.fs.logDirectory** is also set correctly. The permissions are also correct.

I have deployed it using the **stable/spark-history-server** chart

**Comment by ramkrishnan8994** [comment]
> @pfisterer - Okay. Can you help me with this
> I tried setting up **Spark history server** and access the logs that YARN creates on HDFS.
> 
> ![image](https://user-images.githubusercontent.com/40425959/60257241-b5bac500-98f0-11e9-985f-153acd34f05f.png)
> 
> The Logs are generated in the given location. **spark.history.fs.logDirectory** is also set correctly. The permissions are also correct.
> 
> I have deployed it using the **stable/spark-history-server** chart

This was an attempt to somehow overcome the lack of a reverse proxy

**Comment by rohit-menon** [comment]
@ramkrishnan8994 were you ever able to solve this issue? I am wondering if this is a complete blocker to run hadoop on k8s. thanks

**Comment by ramkrishnan8994** [comment]
> @ramkrishnan8994 were you ever able to solve this issue? I am wondering if this is a complete blocker to run hadoop on k8s. thanks

This isnt a blocker per se to run Hadoop on K8s. Its just that logs for YARN UI is not visible as there isnt a reverse proxy per se like the Spark UI has for a standalone cluster

I tried setting it up with Apache Knox but didnt find a  working docker image with the latest Knox version.

**Comment by rohit-menon** [comment]
I appreciate the response @ramkrishnan8994. Yes I shouldn't have called it a blocker, but its a usability blocker.

Looks like Knox gateway does not support node manager UI as you mentioned above. Do you have any other recommendations that could be tried? Thanks.

**Comment by ramkrishnan8994** [comment]
Knox supports the Node Manager logs, but there was a bug with the same. Theres a patch available. Details - 
https://issues.apache.org/jira/browse/KNOX-1581

**Comment by pfisterer** [comment]
@ramkrishnan8994 The current version of Apache Knox (1.3.0; cf. https://cwiki.apache.org/confluence/display/KNOX/News) is available as a Docker image (https://github.com/pfisterer/apache-knox-docker and https://hub.docker.com/repository/docker/farberg/apache-knox-docker/general). In addition, I've provided a Helm Chart (https://github.com/pfisterer/apache-knox-helm).

If you need any changed to the default configmap (cf. https://github.com/pfisterer/apache-knox-helm/blob/master/templates/knox-configmap.yaml), please let me know by opening an issue or by providing a PR.
