### ISSUE TITLE
[incubator/vault] Consul Agent TLS Support

### ISSUE THREAD

**Issue by infa-bsurber** [helm/charts#13689]
**Is your feature request related to a problem? Please describe.**
Currently if the backend Consul server is set to with `"verify_incoming": true`, there's no way to use this chart's Consul agent feature.
This is because the Consul agent needs a cert to use when interacting with the backend server, usually provided via the Consul config ("cert_file", "key_file", "ca_file"). 

**Describe the solution you'd like**
"extraConfig" and "extraVolumeMounts" values under "consulAgent" so users can provide their own tls certs, keys and ca certs via a volume then configure Consul to use those files via a string config which would be written to a file & loaded during agent startup.

**Describe alternatives you've considered**
Right now this can be done via extraContainers but if the chart is trying to offer these consulAgent values, it should be flexible.

**Additional context**

**Comment by rosteroster** [comment]
how should I draw attention to this?

**Comment by infa-bsurber** [comment]
how should attention to be drawn to this from the incubator/vault chart owners?

**Comment by infa-bsurber** [comment]
Not getting any attention so I guess I'll stick to a full sidecar container consul agent
