### ISSUE TITLE
Set image pull policy to `IfNotPresent` by default

### ISSUE THREAD

**Issue by gyliu513** [helm/charts#1368]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:
istio

**What happened**:
Set all of the image pull policy here https://github.com/kubernetes/charts/blob/master/incubator/istio/values.yaml to `IfNotPresent`

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by lachie83** [comment]
Would you like to raise a PR for this?

**Comment by gyliu513** [comment]
/assign @lachie83 

Can you help review?
