### ISSUE TITLE
Set grafana and Prometheus service type to NodePort by default

### ISSUE THREAD

**Issue by gyliu513** [helm/charts#1369]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:
istio

**What happened**:
With NodePort, we can access the dashboard for Grafana and Prometheus with NodePort mode.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by lachie83** [comment]
I'm okay with this. I'll raise a PR soon

**Comment by alex88** [comment]
Why export to a host port by default? IMHO it would be better to be able to configure it, but not by default otherwise someone that installs the chart to use it internally has the service open to the outside

**Comment by gyliu513** [comment]
Thanks @alex88 , yes, this is  already configurable. The reason that I want to make it as NodePort by default because I want to facilitate the access mode of those services, and they can also configure it back it to ClusterIP if needed. Another point is that I can see that most people are using Kubernetes in their internal env and most do not have network to access outside.

**Comment by alex88** [comment]
Don't kops or GKE expose those ports enabling them on the firewall to the external internet when using NodePort?
Anyway, I don't want to complain about this, I just thought having NodePort by default would make users unaware that their services have been silently opened to the public internet (if the cluster is running on some cloud services/public networks)

**Comment by gyliu513** [comment]
I see, then I think that mentioning this in document would be a good choice. So my proposal is

1) Use `NodePort` by default
2) Mention in document that it can be update to `ClusterIP` if do not want to expose the service outside.

What do you think @alex88 ?

**Comment by alex88** [comment]
Using big bold black font, yeah :) j/k, it's fine for me, it's just important that the user knows that IMHO
