### ISSUE TITLE
[stable/prometheus-operator] how to create a bearerTokenFile

### ISSUE THREAD

**Issue by runningman84** [helm/charts#13701]
**Describe the bug**
According to these docs you can use a bearerTokenFile:
https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint

It is unclear for me how to create or inject such file using the prometheus operator chart.

**Comment by vsliouniaev** [comment]
I think that you would use `prometheusSpec.secrets` to mount additional secrets into the Prometheus pod's filesystem, then configure the path to the mounted file
