### ISSUE TITLE
[stable/mercure] Wrong option in readme

### ISSUE THREAD

**Issue by morsok** [helm/charts#13717]
**Describe the bug**

In the configuration section there is `ingress.path` but this does does exists in the current version of the chart.

The current version has `ingress.paths` which is an array, furthermore, it has no default value (should be `['/']` in my opinion) and so enabling ingress without providing this options results in an error.

**Which chart**:

stable/mercure

**What happened**:

```
failed to create resource: Ingress.extensions "api-mercure" is invalid: spec.rules[0].http.paths: Required value
```

**What you expected to happen**:

```
deployment "mercure" successfully rolled out
```

**How to reproduce it** (as minimally and precisely as possible):

Deploy the chart with `--set ingress.enabled=true`

**Comment by morsok** [comment]
Maybe I should have pinged @dunglas ?

**Comment by morsok** [comment]
Nope not stale ><

**Comment by dunglas** [comment]
Goof catch, I badly copy/pasted the chart template. Would you want to open a PR to fix this?

**Comment by morsok** [comment]
Here you go opened a PR.
