### ISSUE TITLE
[stable/mongodb] routing read operations to one of the secondary

### ISSUE THREAD

**Issue by polganesh** [helm/charts#13736]
is this request for help ?
yes

query?
we are able to create  mongodb replica set with one primary and secondary. we are planning to use two secondary replicas. one secondary we are planning to use for taking backup while other secondary we are planning to use for routing read operations.

do we have any facility to perform this with the help of mongodb helm chart

**Comment by juan131** [comment]
Hi @polganesh 

Currently the MongoDB chart creates a service that redirects traffic to primary nodes exclusively. 

You'll need another service that allows you to access the secondary nodes and redirect the "read operations" to this service. 

You'll also need to modify the Read Preference Mode, you can find information about it in the link below:

https://docs.mongodb.com/manual/core/read-preference/
