### ISSUE TITLE
Error: open jenkins/values.yaml: no such file or directory

### ISSUE THREAD

**Issue by attaulbari** [helm/charts#13730]
getting an error while deploying Jenkins using helm. Any idea what to fix?

./helm install -n cd stable/jenkins -f jenkins/values.yaml --version 0.16.6 --wait

ERROR:

Error: open jenkins/values.yaml: no such file or directory

**Comment by torstenwalter** [comment]
You are telling helm to use a file `-f jenkins/values.yaml`. The error message tells you that there is no such file.

**Comment by rick77777** [comment]
Same here.....even though we have a file under jenkins/values.yaml
The directory structure is as follows - 
linux-amd64/helm
jenkins/values.yaml
We are executing the following command - ./helm install -n cd stable/jenkins -f jenkins/values.yaml --version 0.16.6 --wait from linux-amd64
linux-amd64 is on the same directory level as jenkins
Hope this information helps.

**Comment by rick77777** [comment]
I have found a way out of this error....
For more details.....visit https://github.com/rick77777/Problem_Solutions/blob/master/GCP_qwiklabs_jenkins_Error

**Comment by NachoDonnes** [comment]
This works for me:

./helm install -n cd stable/jenkins -f **continuous-deployment-on-kubernetes**/jenkins/values.yaml --version 0.16.6 --wait
