### ISSUE TITLE
Failed to connect to my-release-mariadb:3306 after 36 tries

### ISSUE THREAD

**Issue by RobertoDonPedro** [helm/charts#13746]
**Describe the bug**
The wordpress pod cannot connect to the maria-db pod on a new helm/kubernetes setup with the chart `stable/wordpress`
Log entry in the WordPress Pod: `Failed to connect to my-release-mariadb:3306 after 36 tries`

Note: I also checked some other closed bug reports in this regard, but they refer to older releases and should be fixed yet.

**Version of Helm and Kubernetes**:
helm version:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

kubectl verion:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:15:46Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/wordpress

**What happened**:
WordPress Pod cannot connect to Maria DB
`kubectl logs my-release-wordpress-7dd7bdbd4d-z5xqz`
mysql-c INFO  Trying to connect to MySQL server
**Error executing 'postInstallation': Failed to connect to my-release-mariadb:3306 after 36 tries**

After some time the wordpress pod switches its state from Running to CrashLoopBackOff

**What you expected to happen**:
Running

**How to reproduce it** (as minimally and precisely as possible):
Just use a default, clean installation:
`helm install --name my-release stable/wordpress`

Then wait and access the log of the wordpress pod

**Anything else we need to know**:
I am running minikube on a mac

**Comment by juan131** [comment]
Hi @RobertoDonPedro 

What version of the WordPress chart are you using? Have you updated the repository recently?

```bash
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
```

I was unable to reproduce the issue on Minikube on MacOS using the latest chart:

```bash
$ helm install --name my-release stable/wordpress
...
$ kubectl get pods
NAME                                    READY   STATUS    RESTARTS   AGE
my-release-mariadb-0                    1/1     Running   0          2m12s
my-release-wordpress-7dd7bdbd4d-jj2xw   1/1     Running   0          2m12s
$ kubectl logs $(kubectl get pods -l app=my-release-wordpress -o jsonpath='{.items[0].metadata.name}')

Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
apache  INFO  ==> Configuring dummy certificates...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
nami    INFO  Initializing wordpress
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at my-release-mariadb:3306
mysql-c INFO  MySQL server listening and working at my-release-mariadb:3306
wordpre INFO
wordpre INFO  ########################################################################
wordpre INFO   Installation parameters for wordpress:
wordpre INFO     First Name: FirstName
wordpre INFO     Last Name: LastName
wordpre INFO     Username: user
wordpre INFO     Password: **********
wordpre INFO     Email: user@example.com
wordpre INFO     Blog Name: User's Blog!
wordpre INFO     Table Prefix: wp_
wordpre INFO   (Passwords are not shown for security reasons)
wordpre INFO  ########################################################################
wordpre INFO
nami    INFO  wordpress successfully initialized
INFO  ==> Starting wordpress...
```

Did the associated MariaDB chart reached a healthy status?

**Comment by RobertoDonPedro** [comment]
Hi, I did the same like you, but wp cannot connect.
Neither the wp nor the mariadb chart enter Ready state. First both are running, then wp is failing then maria db is failing. Please see the details below:

```
Roberts-iMac:~ robert$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
```
`Roberts-iMac:~ robert$ helm install --name my-release stable/wordpress`

```
Roberts-iMac:~ robert$ kubectl get pods
NAME                                    READY   STATUS    RESTARTS   AGE
my-release-mariadb-0                    0/1     Running   5          14m
my-release-wordpress-7dd7bdbd4d-bkxk2   0/1     Running   6          14m
```
```
Roberts-iMac:~ robert$ kubectl logs $(kubectl get pods -l app=my-release-wordpress -o jsonpath='{.items[0].metadata.name}')

Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
apache  INFO  ==> Configuring dummy certificates...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
nami    INFO  Initializing wordpress
mysql-c INFO  Trying to connect to MySQL server
Error executing 'postInstallation': Failed to connect to my-release-mariadb:3306 after 36 tries
```
```
Roberts-iMac:~ robert$ kubectl get pods
NAME                                    READY   STATUS             RESTARTS   AGE
my-release-mariadb-0                    0/1     CrashLoopBackOff   6          17m
my-release-wordpress-7dd7bdbd4d-bkxk2   0/1     CrashLoopBackOff   6          17m
```
```
Roberts-iMac:~ robert$ kubectl logs my-release-mariadb-0

Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MariaDB setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
INFO  ==> Initializing mariadb database...
INFO  ==> Persisted data detected. Restoring...
INFO  ==> Stopping mariadb...
INFO  ==> ** MariaDB setup finished! **

INFO  ==> ** Starting MariaDB **
2019-05-14 14:01:31 140212342757248 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.39-MariaDB) starting as process 1 ...
2019-05-14 14:01:31 140212342757248 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.

2019-05-14 14:01:31 140212342757248 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2019-05-14 14:01:31 140212342757248 [Note] InnoDB: The InnoDB memory heap is disabled
2019-05-14 14:01:31 140212342757248 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-05-14 14:01:31 140212342757248 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2019-05-14 14:01:31 140212342757248 [Note] InnoDB: Compressed tables use zlib 1.2.8
2019-05-14 14:01:31 140212342757248 [Note] InnoDB: Using Linux native AIO
2019-05-14 14:01:31 140212342757248 [Note] InnoDB: Using SSE crc32 instructions
2019-05-14 14:01:31 140212342757248 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2019-05-14 14:01:31 140212342757248 [Note] InnoDB: Completed initialization of buffer pool
2019-05-14 14:01:31 140212342757248 [Note] InnoDB: Highest supported file format is Barracuda.
2019-05-14 14:01:31 140212342757248 [Note] InnoDB: 128 rollback segment(s) are active.
2019-05-14 14:01:31 140212342757248 [Note] InnoDB: Waiting for purge to start
2019-05-14 14:01:31 140212342757248 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.43-84.3 started; log sequence number 2574477
2019-05-14 14:01:31 140212342757248 [Note] Plugin 'FEEDBACK' is disabled.
2019-05-14 14:01:31 140211610707712 [Note] InnoDB: Dumping buffer pool(s) not yet started
2019-05-14 14:01:31 140212342757248 [Note] Server socket created on IP: '0.0.0.0'.
2019-05-14 14:01:32 140212342757248 [Warning] 'proxies_priv' entry '@% root@my-release-mariadb-0' ignored in --skip-name-resolve mode.
2019-05-14 14:01:32 140212342757248 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
Version: '10.1.39-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
2019-05-14 14:03:57 140212341909248 [Note] /opt/bitnami/mariadb/sbin/mysqld: Normal shutdown
2019-05-14 14:03:57 140212341909248 [Note] Event Scheduler: Purging the queue. 0 events
2019-05-14 14:03:57 140211656824576 [Note] InnoDB: FTS optimize thread exiting.
2019-05-14 14:03:57 140212341909248 [Note] InnoDB: Starting shutdown...
2019-05-14 14:03:58 140212341909248 [Note] InnoDB: Waiting for page_cleaner to finish flushing of buffer pool
2019-05-14 14:03:59 140212341909248 [Note] InnoDB: Shutdown completed; log sequence number 2574487
2019-05-14 14:03:59 140212341909248 [Note] /opt/bitnami/mariadb/sbin/mysqld: Shutdown complete
```

**Comment by juan131** [comment]
Hi @RobertoDonPedro 

For some reason, your MariaDB database is receiving a shutdown signal, see:`

```
2019-05-14 14:03:57 140212341909248 [Note] /opt/bitnami/mariadb/sbin/mysqld: Normal shutdown
```

That's probably related with readiness/liveness probes failing and it's very likely to be related with using the wrong database password on those probes.

Could it be possible you're installing the chart with the same name you'd done in a previous release? There could be existing PVCs that were not deleted from previous releases.

I'd delete the chart, check and delete the PVCs that are not necessary, and install again the chart.

**Comment by RobertoDonPedro** [comment]
Initially I have tried it with passwords like described in the readme
```
helm install --name my-release \
  --set wordpressUsername=admin,wordpressPassword=password,mariadb.mariadbRootPassword=secretpassword \
    stable/wordpress
```
This did not work. Maybe the parameter in this readme sample is not correct and it should be `mariadb.rootUser.password` instead of `mariadb.mariadbRootPassword`?

However I deleted it again with `helm del --purge my-release` and installed it again without passwords by `helm install --name my-release stable/wordpress`, but with the same negative results.
I did not assume, that `helm del --purge my-release` would leave the PVs and PVCs intact. So now I checked this and indeed the old pvs were still active. 
**According to your advise I deleted the old PVCs and PVs, built it from scratch and now it works.**

However, now there is a new problem, how can I get the Wordpress URL?  The install output says:
```
NOTES:
1. Get the WordPress URL:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w my-release-wordpress'
  export SERVICE_IP=$(kubectl get svc --namespace default my-release-wordpress --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo "WordPress URL: http://$SERVICE_IP/"
  echo "WordPress Admin URL: http://$SERVICE_IP/admin"

2. Login with the following credentials to see your blog
```
If I run this statement as advised above
`export SERVICE_IP=$(kubectl get svc --namespace default my-release-wordpress --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")`
then I get the following error:
`error: error executing template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}": template: output:1:10: executing "output" at <index .status.loadBalancer.ingress 0>: error calling index: index of untyped nil`
How need this statement to be changed so that it works with the default install commands in your readme file?

**Comment by juan131** [comment]
> I did not assume, that helm del --purge my-release would leave the PVs and PVCs intact. So now I checked this and indeed the old pvs were still active.

That's the problem, Helm doesn't delete the PVCs since they're dynamically created by the statefulset. That's why you need to look for the PVCs and delete them manually.

```bash
$ kubectl get pvc
$ kubectl delete pvc xxx yyy zzz
```

This is a known bug and it's already reported. See https://github.com/helm/helm/issues/5156

> However, now there is a new problem, how can I get the Wordpress URL? The install output says:

The problem is that you installed the chart with `service.type=LoadBalancer`. That kind of service is not supported on Minikube, you should use `service.type=ClusterIP` instead.

**Comment by RobertoDonPedro** [comment]
> This is a known bug and it's already reported. See helm/helm#5156

I  commented on that directly in  #helm/helm#5156

> The problem is that you installed the chart with service.type=LoadBalancer. That kind of service is not supported on Minikube, you should use service.type=ClusterIP instead.

For better initial UX I would expect the readme sample to work even minikube out of the box

However, now I tried it with `service.type=ClusterIP`:

`helm install --name my-release   --set wordpressUsername=admin,wordpressPassword=password,mariadb.mariadbRootPassword=secretpassword,service.type=ClusterIP stable/wordpress`

but when I try to access the URL I get connection refused with curl (and in the browser) 
```
Roberts-iMac:~ robert$ curl http://127.0.0.1:8080/
curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
```

**Comment by RobertoDonPedro** [comment]
Finally the port forwarding was missing:
`kubectl port-forward --namespace default svc/my-release-wordpress 8080:80`
Now it works 👍 .
However, if I may I would like to propose to adapt the readme file (or the default configuration) for a better "first time helm experience".

**Comment by juan131** [comment]
Hi @RobertoDonPedro 

I'm glad you could get it working!!! Please feel free to make a PR including the adaptions you consider necessary to improve the first experience.

**Comment by igortas** [comment]
> Finally the port forwarding was missing:
> `kubectl port-forward --namespace default svc/my-release-wordpress 8080:80`
> Now it works 👍 .
> However, if I may I would like to propose to adapt the readme file (or the default configuration) for a better "first time helm experience".

This is not solution, this is workaround.
