### ISSUE TITLE
[stable/jenkins] agent.containercap in values.yaml don't belong to confix.ml

### ISSUE THREAD

**Issue by Jdavid7x** [helm/charts#13743]
**Describe the bug**

You have a agent.containercap in values.yaml which don't belong to the configuration "Max number of instance" in config.xml of jenkins master

Helm 2.12

**Which chart**: Jenkins

**What happened**:

**What you expected to happen**: I expect that this value will fill the jenkins config to have at max N number of agents. 

**How to reproduce**: config the variable agent.containercap in value.yaml and check if is filled in the jenkins/config/Kubernetes Pod Template/Max Number Of Instance.

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
The property is named `agent.containerCap`. It's rendered as 

```
<containerCap>{{ .Values.agent.containerCap }}</containerCap>
```

https://github.com/helm/charts/blob/master/stable/jenkins/templates/config.yaml#L136

**Comment by Jdavid7x** [comment]
Sorry. I was confused about the values.

Thanks for the info
