### ISSUE TITLE
[stable/postgresql] Service Account support

### ISSUE THREAD

**Issue by denniseffing** [helm/charts#13748]
**Is your feature request related to a problem? Please describe.**
Kubernetes service accounts provide an identity for processes running in a Pod. When combining Kubernetes with an Istio service mesh, these identities can be used to enforce authorization policies. Without a defined service account, deployments fall back to the default service account of the namespace the deployment resides in. This makes it impossible to identify a particular service and thus enforce security policies.

**Describe the solution you'd like**
Utilize service accounts when deploying Postgres. The chart should automatically create a service account and/or use an existing service account. The name of an existing service account should be configurable.

**Describe alternatives you've considered**
The alternative is not using the Helm chart or not utilizing Istio's security features.

**Comment by juan131** [comment]
Hi @denniseffing 

Thanks so much for reporting this enhancement and create the corresponding PR!
