### ISSUE TITLE
[stable/mongodb-replicaset] peer-finder failing in bootstrap init container

### ISSUE THREAD

**Issue by kmhughes** [helm/charts#13757]
**Describe the bug**

I cannot bring up a 3 node MongoDB replicaset in Google Cloud. The first pod dies in the ``bootstrap`` init container.

**Version of Helm and Kubernetes**:

Helm: 2.13.1
Kubernetes: 1.11.1

**Which chart**:

stable/mongodb-replicaset

**What happened**:

I deployed the Helm chart. Everything is appropriately created up to the statefulset pods. While the -0 pod is trying to start, it fails in the bootstrap init container and pod -0 hangs in a crash loop.

**What you expected to happen**:

I expect all of the pods to start.

**How to reproduce it** (as minimally and precisely as possible):

``helm install --name mongo stable/mongodb-replicaset``

You will then see

> $ kubectl get pods
> NAME                         READY     STATUS                  RESTARTS   AGE
> mongo-mongodb-replicaset-0   0/1       Init:CrashLoopBackOff   2          1m

**Anything else we need to know**:

I ran the chart in minikube on my laptop for Kubernetes v1.13.0 and v1.11.1 and it ran just fine.

The Kubernetes cluster started in Google Cloud was created using KOPS 1.11.1.

After figuring out that the ``bootstrap`` init container was failing because the ``peer-finder`` executable had insufficient permissions to run, I replaced the startup command for the ``bootstrap`` init container with ``sleep infinity`` so that the container would stick around long enough for me to get a shell into it.

Looking at ``/etc/mtab`` I found the line

``/dev/sda1 /work-dir ext4 rw,nosuid,nodev,noexec,relatime,commit=30,data=ordered 0 0``

It seems the ``work-dir`` emptyDir volume is mounted ``noexec`` by Kubernetes.

Looking at Kubernetes running in Minikube, ``/etc/mtab`` has

``/dev/sda1 /work-dir ext4 rw,relatime,data=ordered 0 0``

Note that ``noexec`` is not there.

After a lot of Googling, a lot of folks feel that emptyDir volumes should be labeled ``noexec`` as a security precaution, and I found no way of telling Kubernetes that the ``work-dir`` volume should not be mounted with ``noexec`` enabled.

How is this working for anyone else?

I may create a Docker image with the ``peer-finder`` as part of the MongoDB image so I can keep moving forward, but the main chart should probably be fixed.

**Comment by kmhughes** [comment]
Is this not a problem that anyone else has? I have a change I made that seems to fix it. I could make a PR if anyone is interested.

**Comment by dnascimento** [comment]
@kmhughes  may you share/PR the change?

**Comment by kmhughes** [comment]
Sure, I will try and get it done this weekend.

**Comment by kmhughes** [comment]
> @kmhughes may you share/PR the change?

Sure, will be happy to. Is this something you can merge into the project?

**Comment by dnascimento** [comment]
I added this: https://github.com/helm/charts/pull/17883

**Comment by SachinMaharana** [comment]
@dnascimento we have a different cluster domain, and the mongodb-install 0.7 doesn't have domain flag in peer-finder to work accordingly. I tried creating custom-image with correct peer-finder version but it crashes in init. Any idea where i might be going wrong?
