### ISSUE TITLE
Missing apiVersion field on numerous charts

### ISSUE THREAD

**Issue by mattfarina** [helm/charts#13763]
The `apiVersion` field in the `Chart.yaml` file is a required field. See the docs at https://helm.sh/docs/developing_charts/#the-chart-yaml-file. Numerous charts do not have that field. We need to fix this.

With the coming of Helm v3 (even in the alpha stage) the version of a chart matters. We have v2 charts now and Helm needs to differentiate.

`helm lint` does not catch this issue. Patches coming for that. This is why we've missed it.

cc @helm/charts-maintainers

**Comment by cpanato** [comment]
Will open some prs to fix that

**Comment by mattfarina** [comment]
@cpanato wow... you got all over that. Count me impressed.

**Comment by maorfr** [comment]
Good work @cpanato!

**Comment by cpanato** [comment]
i think we can close this issue now :)

**Comment by maorfr** [comment]
wait for it... ;)

**Comment by maorfr** [comment]
...dary
legendary!
