### ISSUE TITLE
No Content-Encoding header in stable charts repo to indicate that a chart is a *gzipped* tar archive

### ISSUE THREAD

**Issue by ljnelson** [helm/charts#1383]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
redis-0.5.1 (but it doesn't really matter; what matters is that it's from https://kubernetes-charts.storage.googleapis.com/)

**What happened**:
`curl -H "Accept-Encoding: gzip" -I https://kubernetes-charts.storage.googleapis.com/redis-0.5.1.tgz` returns headers that indicate the `Content-Type` is `application/x-tar` but there is no corresponding header (`Content-Encoding`) to indicate that the representation identified by this URI is in fact a _gzipped_ tar archive.  Here is the output:

    HTTP/1.1 200 OK
    X-GUploader-UploadID: AEnB2UqBzSXfTToMAdMARXSjJeN0on3jaNY3u74eXcWfvqsOwRpi38Xc6T0XrrmY4otPeySaYRwXyHccHYtChoPAgFQwYZhQMhcpZRWtZURRANGdfRJoupI
    Expires: Tue, 27 Jun 2017 00:21:59 GMT
    Date: Mon, 26 Jun 2017 23:21:59 GMT
    Cache-Control: public, max-age=3600
    Last-Modified: Fri, 05 May 2017 03:03:41 GMT
    ETag: "e4184c81a58fb731283847222a1f4005"
    x-goog-generation: 1493953421241613
    x-goog-metageneration: 1
    x-goog-stored-content-encoding: identity
    x-goog-stored-content-length: 3550
    x-goog-meta-goog-reserved-file-mtime: 1493953414
    Content-Type: application/x-tar
    x-goog-hash: crc32c=bQHveg==
    x-goog-hash: md5=5BhMgaWPtzEoOEciKh9ABQ==
    x-goog-storage-class: STANDARD
    Accept-Ranges: bytes
    Content-Length: 3550
    Server: UploadServer
    Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"

**What you expected to happen**:
I would have expected to see a `Content-Encoding` header with `gzip` as its value.

**How to reproduce it** (as minimally and precisely as possible):
`curl -H "Accept-Encoding: gzip" -I https://kubernetes-charts.storage.googleapis.com/redis-0.5.1.tgz`

**Anything else we need to know**:
I have not tested other charts from this repository.

**Comment by prydonius** [comment]
Thanks @ljnelson, we may need to explicitly set the Content-Encoding header on the files we upload: https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata#content-encoding

It looks like there's also a `-z` option that can gzip files and set this header automatically.

cc @viglesiasce @foxish

**Comment by ljnelson** [comment]
What I'm not personally clear on is whether the object-at-rest in this case is fundamentally a gzipped tar file or just a tar file.  If it is the former, then `Content-Encoding` probably isn't relevant, but `Content-Type` would be (i.e. if fundamentally the object-at-rest is a gzipped file that can be retrieved with _no_ `Content-Encoding`, then the `Content-Type` should be changed to…to…well, it turns out there's no universally agreed-upon MIME type for a gzipped tar archive).  If  it is the latter, then to be completely correct my client should be able to indicate in some way that it wants _no_ `Content-Encoding`, and should get a stream of the uncompressed `.tar` archive directly.

**Comment by prydonius** [comment]
Ah you're right, the package at rest is gzipped so it's correct that Content-Encoding is not set.

**Comment by ljnelson** [comment]
Well, but that leads to its own set of issues.  The [Google documentation previously linked to](https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata#content-encoding) says, in part:

> Note that this is different from uploading a gzipped object foo.txt.gz with Content-Type: application/x-gzip because most browsers are able to dynamically decompress and process objects served with Content-Encoding: gzip based on the underlying Content-Type.

So that means all of these charts should be served with a `Content-Type` of `application/x-gzip`.  But that, of course, doesn't let anyone figure out from the `Content-Type` what is actually `gzip`ped.

I seem to recall one convention&mdash;because there apparently aren't standards for this&mdash;is to set a `Content-Type` of `application/x-tar+gzip` or some such.

Then there are other recommendations that say that even if the object-at-rest is fundamentally a gzipped something, you should never declare its gzipness as its MIME type.  See, as just one arbitrary example, https://serverfault.com/questions/304361/how-can-i-define-a-mime-type-in-nginx-for-tar-bz2-or-tar-gz-files/516095#516095.

Given all this I'd suggest keeping the `Content-Type` as `application/x-tar` and setting `Content-Encoding` to `gzip`, and storing the charts as actual `.tar` files.  That would be the most _correct_ way to do things, but obviously there might be other factors in play.

**Comment by prydonius** [comment]
The issue is that the `helm package` command gives us a gzipped tarball, so un-gzipping just to upload will be an extra step and I'm not sure how Helm handles non-gzipped tar packages.

We could go with `application/x-tar+gzip`, that said if you can assume all Helm chart packages are always gzipped do you really need to programatically check this?

**Comment by ljnelson** [comment]
Up to you folks on all of this.  I was just curious about the headers. 😄

**Comment by ljnelson** [comment]
An additional thought: what about a custom MIME type à la `application/vnd.helmchart`, which would allow you to define this thing however you want?  No harm/no foul to existing clients because if I'm hearing you right they just "know" that something downloaded from here is a tarball anyway.
