### ISSUE TITLE
[stable/wordpress] Hyper-V: MariaDB Permission denied

### ISSUE THREAD

**Issue by RobertoDonPedro** [helm/charts#13850]
**Describe the bug**
This time I tried a clean install of the stable/wordpress on a Windows 10 PC with Hyper-V enabled and Kubernetes on Docker Desktop for Windows.  
There were no existing PVCs or PVs available before running this install command:
```
helm install --name my-release --set wordpressUsername=admin,wordpressPassword=password,mariadb.mariadbRootPassword=secretpassword,servi
ce.type=ClusterIP stable/wordpress
```

It results in the follwing errors 
```
NAME                                    READY   STATUS                       RESTARTS   AGE
my-release-mariadb-0                    0/1     CrashLoopBackOff             6          9m57s
my-release-wordpress-8544c99bb6-6mjgd   0/1     CreateContainerConfigError   0          9m57s
```
MariaDB - Pod:
`mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied`

WP-Pod:
`Error from server (BadRequest): container "wordpress" in pod "my-release-wordpress-8544c99bb6-6mjgd" is waiting to start: CreateContainerConfigError`

Note: Probably the owner or the permissions of  '/bitnami/mariadb/data' need to be changed, however how can this be fixed with helm?

**Version of Helm and Kubernetes**:
PS C:\Users\Robert> helm version
```
Client: &version.Version{SemVer:"v2.14.0-rc.2", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0-rc.2", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
`stable/wordpress`

**What happened**:
MariaDB - Pod:
`mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied`

**What you expected to happen**:
Run basic helm install with working result

**How to reproduce it** (as minimally and precisely as possible):
Run
```
helm install --name my-release --set wordpressUsername=admin,wordpressPassword=password,mariadb.mariadbRootPassword=secretpassword,servi
ce.type=ClusterIP stable/wordpress
```
on a Windows 10 PC with Hyper-V enabled and Kubernetes on Docker Desktop for Windows 

**Anything else we need to know**:

**Comment by miguelaeh** [comment]
Hi @RobertoDonPedro ,
Just to be sure, could you try to purge all your releases? Use the command `helm delete <release-name> --purge` .
I tried with the same command you posted and it works fine for me, but I test on Linux, I am not familiar with Docker for Windows.
Also, your Wordpress pod seems to have a wrong configuration. Have you change something more than the parameters of the command?

**Comment by RobertoDonPedro** [comment]
I tried it again, same result. I also used the  --purge option and removed all available PVCs and PVs, now and before.
I know that it works with linux, since I also tested the same with Linux before. I had some other issues there but finally it worked, see #13746  
But it does not work on Windows.
```
PS C:\Users\Robert> kubectl get pods
NAME                                    READY   STATUS                       RESTARTS   AGE
my-release-mariadb-0                    0/1     CrashLoopBackOff             2          46s
my-release-wordpress-8544c99bb6-gvkmr   0/1     CreateContainerConfigError   0          46s

```
```
PS C:\Users\Robert> kubectl logs my-release-mariadb-0
[0m
[0m[1mWelcome to the Bitnami mariadb container[0m
[0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-mariadb[0m
[0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-mariadb/issues[0m
[0mSend us your feedback at [1mcontainers@bitnami.com[0m
[0m
[0m[38;5;2mINFO [0m ==> ** Starting MariaDB setup **
[0m[38;5;2mINFO [0m ==> Validating settings in MYSQL_*/MARIADB_* env vars..
[0m[38;5;2mINFO [0m ==> Initializing mariadb database...
mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied
[0m[38;5;2mINFO [0m ==> Stopping mariadb...
```
```
PS C:\Users\Robert> kubectl logs my-release-wordpress-8544c99bb6-gvkmr
Error from server (BadRequest): container "wordpress" in pod "my-release-wordpress-8544c99bb6-gvkmr" is waiting to start: CreateContainerConfigError

```

**Comment by miguelaeh** [comment]
Hi @RobertoDonPedro ,
Are you using the latest version of the chart?
I will try to launch a Windows VM to test there.

**Comment by RobertoDonPedro** [comment]
Yes, thx!

**Comment by miguelaeh** [comment]
Hi @RobertoDonPedro ,
Try to set the `runAsUser` to `0` to run MariaDB as root.
You can also change the volumes permissions using the `fsGroup` parameter.
