### ISSUE TITLE
[stable/prometheus-operator] Parameterized default prometheus name

### ISSUE THREAD

**Issue by sterchelen** [helm/charts#13865]
The name of the default prometheus is not a friendly name. A concatenation of the release + `_prometheus`.

I'm wondering if you see any blocking to parameterized the name ? If not it would be a pleasure to add this feature.
https://github.com/helm/charts/blob/73ddcb02fb0025ff3c2d35e80892be25ebfc0a07/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L2-L8

**Comment by vsliouniaev** [comment]
You can override the fullname and name in the chart (and most other Helm charts in this repository) by setting `nameOverride` and `fullnameOverride`.

**Comment by sterchelen** [comment]
Yep, I saw it. But it will be propagate to the other k8s object.
I think it will be more readable to have one specific name for the default
prometheus.

**Comment by vsliouniaev** [comment]
There are a lot of objects that compose this chart, what's the use-case?

**Comment by sterchelen** [comment]
Have the possibility to name it like a "normal" prometheus object.

**Comment by vsliouniaev** [comment]
Is there a reason to do this besides the aesthetic value of doing it?
