### ISSUE TITLE
[stable/nginx-ingress] Ingress endpoint - ELB subnets (availability zones) configuration

### ISSUE THREAD

**Issue by e-jjj** [helm/charts#13862]
The ingress-controller configures the AWS ELB (Load Balancer) as ingress endpoint during the installation with a single availability zone subnet.

**Is your feature request related to a problem? Please describe.**
Yes. 
Currently the ELB (load balancer) as ingress endpoint is automatically configured with a single subnet belonging to a single availability zone. This causes connectivity issues between the ingress endpoint and the cluster's worker nodes that run in different subnets belonging to the other availability zones in the region.

**Describe the solution you'd like**
It is expected to have the ELB as ingress endpoint automatically configured with more than just one availability zone subnet. It should be assigned with all of the subnets belonging to the other availability subnets as part of the ingress installation.
 
**Describe alternatives you've considered**
Currently the ELB needs to be assigned the additional subnets manually
<img width="1183" alt="Screen Shot 2019-05-15 at 12 13 43 pm" src="https://user-images.githubusercontent.com/22207113/57775625-cd832300-7760-11e9-9363-90577adc4f3a.png">

**Comment by ChiefAlexander** [comment]
You need to add an annotation to your service config for AWS to be aware that you want to route across availability zones.
```service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"```
