### ISSUE TITLE
Call for maintainers for charts with no OWNERS

### ISSUE THREAD

**Issue by maorfr** [helm/charts#13869]
Hello,

As maintaining this repository is growing harder by the day, this is a call for maintainers!

This issue is about 'recruiting' maintainers for charts that have no OWNERS file. The list of charts can be found at the end of this message.

If you wish to be added as a maintainer to one of the charts in this issue, please open a PR to add an OWNERS file, and add yourself to that OWNERS file.
In addition, maintainers in Chart.yaml and OWNERS should match.

We would suggest to include in the PR references to past contributions to the chart you are applying for.

If you are a planning to apply for being a maintainer and know someone who also fits this (and is interested) - feel free to approach them and include them!
we aim to have 2 maintainers per chart.

Once a PR exists, please add a comment referencing this issue, and ping one of the [maintainers](https://github.com/helm/charts/blob/master/OWNERS#L1) to get added as a read-only user to the helm/charts repository.

Thanks in advance to everyone who applies! We need your help.

All new OWNERS should be familiar with the following documents:
https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md
https://github.com/helm/charts/blob/master/CONTRIBUTING.md
https://helm.sh/docs/chart_best_practices/

Here is the list of charts:

~~incubator/artifactory~~
~~incubator/burrow~~
incubator/check-mk
incubator/common
incubator/couchdb
incubator/distribution
~~incubator/drone~~
incubator/etcd
incubator/fluentd-cloudwatch
~~incubator/fluentd~~
incubator/goldfish
~~incubator/istio~~
~~incubator/jaeger~~
incubator/jenkins-operator
incubator/keycloak-proxy
~~incubator/keycloak~~
incubator/kube-janitor
incubator/kube-registry-proxy
incubator/kubernetes-vault
~~incubator/kubewatch~~
incubator/mysqlha
~~incubator/oauth-proxy~~
incubator/patroni
incubator/puppet-forge
incubator/riemann
incubator/spring-cloud-data-flow
incubator/tensorflow-inception
incubator/vault
incubator/vaultingkube
incubator/webpagetest-agent
incubator/webpagetest-server
incubator/xray
incubator/orientdb
incubator/solr
~~stable/acs-engine-autoscaler~~
~~stable/aerospike~~ (moved #13867)
stable/ark
~~stable/aws-cluster-autoscaler~~
stable/aws-iam-authenticator
stable/bitcoind
stable/buildkite
~~stable/cert-manager~~
stable/cluster-autoscaler
stable/consul
stable/cosbench
stable/coscale
stable/dask-distributed
stable/dask
stable/distributed-tensorflow
stable/ethereum
stable/express-gateway
stable/external-dns
stable/factorio
stable/gcloud-endpoints
stable/gcp-night-king
~~stable/gitlab-ce~~
~~stable/gitlab-ee~~
stable/hackmd
stable/hadoop
stable/heapster
stable/heartbeat
stable/hubot
stable/ignite
stable/ipfs
stable/janusgraph
stable/k8s-spot-termination-handler
stable/kanister-operator
~~stable/kanister-operator/charts/profile~~
stable/kapacitor
stable/katafygio
stable/keel
~~stable/kiam~~
~~stable/kube-lego~~
stable/kube-ops-view
stable/kube-slack
~~stable/kube-state-metrics~~ (moved #13867)
stable/kube2iam
stable/kuberos
stable/kured
stable/lamp
stable/linkerd
stable/locust
stable/luigi
~~stable/mailhog~~ (moved #13315)
stable/mcrouter
stable/metabase
stable/metallb
stable/minecraft
~~stable/mission-control/charts/elasticsearch~~
stable/msoms
stable/namerd
stable/neo4j
stable/nginx-ldapauth-proxy
stable/nginx-lego
stable/openldap
stable/percona
stable/presto
~~stable/prometheus-adapter~~
stable/prometheus-consul-exporter
stable/prometheus-couchdb-exporter
stable/prometheus-mysql-exporter
stable/prometheus-postgres-exporter
stable/prometheus-rabbitmq-exporter
stable/prometheus-redis-exporter
stable/prometheus-to-sd
stable/rethinkdb
stable/risk-advisor
stable/rookout
stable/sapho
stable/sensu
~~stable/sentry~~ (moved #13867)
~~stable/signalfx-agent~~
~~stable/spark-history-server/charts/nfs~~
stable/spark
stable/spartakus
stable/spotify-docker-gc
~~stable/spring-cloud-data-flow~~
stable/stackdriver-exporter
stable/stolon
stable/sumokube
stable/superset
stable/tomcat
stable/uchiwa
stable/unbound
stable/verdaccio
~~stable/weave-scope~~
stable/zeppelin
stable/zetcd
stable/logdna-agent
stable/socat-tunneller
~~stable/velero~~

**Comment by okgolove** [comment]
@maorfr stable/aws-cluster-autoscaler has migrated to helm hub https://hub.helm.sh/charts/jetstack/cert-manager

**Comment by srueg** [comment]
`incubator/keycloak` is deprecated and moved to `codecentric/keycloak`

**Comment by monotek** [comment]
@unguiculus told me once, that incubator repo should / will die in the future, as unfinished or untested charts should not be published at all, so imho these charts should rather be deleted or moved to stable with an version bump.

Maybe it's also an idea to find people to be in the Github Helm organization / or in the root OWNERS file (https://github.com/helm/charts/blob/master/OWNERS) so they can help out without to be bound to a specific chart.

**Comment by unguiculus** [comment]
@monotek Well, it's not gonna die. I just prefer not to add new stuff there. IMO, we should try and promote existing charts to stable or deprecate them.

**Comment by zakkg3** [comment]
incubator/drone have a stable/drone working version

**Comment by tariq1890** [comment]
`stable/acs-engine-autoscaler` is deprecated.
`stable/kube-state-metrics` can be struck out.

**Comment by dperetti** [comment]
What makes maintaining the repository difficult is also probably related to the fact that all the projects and their issues are mixed there. As a quite recent Helm user, I really dislike this!

**Comment by desaintmartin** [comment]
incubator/fluentd is deprecated (https://github.com/helm/charts/pull/8477)

**Comment by Comradin** [comment]
incubator/istio is deprecated according to their README.md users are encouraged to use https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio from their repository instead.

**Comment by jeff-knurek** [comment]
`incubator/oauth-proxy` & `stable/kube-lego` are deprecated - I'd be inclined to think that several other of the charts in this list are already deprecated too

**Comment by desaintmartin** [comment]
stable/gitlab-ce and stable/gitlab-ee are deprecated as well.

**Comment by Comradin** [comment]
compleatang and k8s-ci-robot move **burrow** to stable repo (#3481)
Latest commit 0abd574  on 23 Mar 2018

I guess it should be deleted from the incubator path, then? And it can be removed from your list.

**Comment by naseemkullah** [comment]
PR to add OWNERS to incubator/jaeger https://github.com/helm/charts/pull/13693

**Comment by EricLemieux** [comment]
stable/signalfx-agent was deprecated in #13586

**Comment by EricLemieux** [comment]
@maorfr I made a pretty basic script to get the current number of maintainers, so you don't need to rely on comments letting you know whenever someone is added/removed.

This is a sample out the output displaying the number of maintainers, approvers, and reviewers per chart.

https://github.com/EricLemieux/Helm-Chart-Maintainers/blob/master/current-number-of-maintainers.md

**Comment by deepaksood619** [comment]
PR to add OWNERS to stable/kapacitor #14622

**Comment by koolamusic** [comment]
@maorfr any progress with `stable/lamp` I would like to join the maintainers for that project

**Comment by monotek** [comment]
added myself to prometheus-mysql-exporter: https://github.com/helm/charts/pull/14776

**Comment by deepaksood619** [comment]
`incubator/kubewatch` is deprecated and moved to `stable/kubewatch`

**Comment by Hashfyre** [comment]
@cristinanegrean, it'd be great if you could maintain `stable/stackdriver-exporter`
At work I mostly end up using your version: https://github.com/cristinanegrean/charts/tree/master/stable/stackdriver-exporter

Also, great blog post: https://blog.trifork.com/2019/02/07/centralized-metrics-with-stackdriver-prometheus-exporter/

**Comment by Neustradamus** [comment]
Can you look for this ticket?
- https://github.com/helm/charts/issues/10768

**Comment by bclermont** [comment]
@maorfr #17635 for `stable/ipfs`

**Comment by sekka1** [comment]
The [stable/locust] chart has no maintainers.  Adding myself as a maintainer/owner:

https://github.com/helm/charts/pull/17719

**Comment by dermicha** [comment]
We would like to offer maintaining stable/janusgraph helm chart.

We use JanusGraph and also use the helm chart in our core product.

**Comment by zanhsieh** [comment]
> We would like to offer maintaining stable/janusgraph helm chart.
> 
> We use JanusGraph and also use the helm chart in our core product.

@dermicha Would you mind to open an PR on modifying OWNERS file in stable/janusgraph chart and post the link to here please? Thank you.

**Comment by dermicha** [comment]
@zanhsieh OK

**Comment by Neustradamus** [comment]
Any news for https://github.com/helm/charts/issues/10768?

**Comment by desaintmartin** [comment]
Please do not hijack this thread.

**Comment by daixiang0** [comment]
#18439 for `stable/spark`
