### ISSUE TITLE
login failed for management console

### ISSUE THREAD

**Issue by kagemartin** [helm/charts#13876]
**Describe the bug**
Cannot log into management console after deploying rabbitmq pod.

**Version of Helm and Kubernetes**:
kubectl version: 1.10.11
helm version: 2.13.1

**Which chart**:
stable/rabbitmq

**What happened**:
Pod installed successfully.
Login failed from management console.

**What you expected to happen**:
Successfully access management console

**How to reproduce it** (as minimally and precisely as possible):

Installed as:

`helm install --name test-rabbit -f rabbit-values-production.yaml --set rabbitmq.username=admin,rabbitmq.password=rabbit1 stable/rabbitmq`

Ran:
`echo "Password      : $(kubectl get secret --namespace default test-rabbit-rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"`

Result: rabbit1

Forwarded management port:
`kubectl port-forward --namespace default svc/test-rabbit-rabbitmq 15672:15672`

Logged into management port using admin/rabbit1 and login failed.

Browsed to: http://127.0.0.1:15672/api/whoami and logged in using admin/rabbit1:

> Result: {"error":"not_authorised","reason":"Login failed"}

Ran: 
`kubectl attach test-rabbit-rabbitmq-0`

> 2019-05-15 19:06:51.735 [warning] <0.583.0> HTTP access denied: user 'admin' - invalid credentials

**Comment by miguelaeh** [comment]
Hi @andymartin ,
I tried with your command, but the file `rabbit-values-production.yaml` seems to not exist.
I used this command: 
```
helm install --name test-rabbit --set rabbitmq.username=admin,rabbitmq.password=rabbit1 stable/rabbitmq
```
And I can access correctly. Can you try without the option `-f rabbit-values-production.yaml` ?

**Comment by miguelaeh** [comment]
Hi @andymartin ,
I tested again with the `values-production.yaml`. I have seen that you change the file name. With the file we have in the repository it should work. Have you change the file?

Also, if not, can you tell me which is your helm and docker version?

**Comment by urvineet** [comment]
@andymartin even i  was facing same issue. i just changed the  `test-rabbit` . to `test-rabbit-1` then started
not sure but try to change name every delete and install for same chart 
i have faced  similar problem in other chart as well

**Comment by tompizmor** [comment]
@andymartin @urvineet sometimes that happens when you delete the chart and re-install with a different password using the same name.

The `helm delete --purge` command does not delete the PVC created by a stateful set so unless you manually delete them, the new helm chart will still use the password using during the first install.

**Comment by gochefling** [comment]
I have got a similar issue. 
When i run rabbitmq with this command 

```
helm install --name rabbitmq-prod -f values-production.yaml \
  --set rabbitmq.username=admin,rabbitmq.password=somepassword,rabbitmq.erlangCookie=2d323d23dwd33e12 \
    stable/rabbitmq
```
I cannot log in to the service, liveness probe fails, ingress is disabled could that be the problem ? 

I also tried 
`helm install --name rabbitmq-prod -f values-production.yaml stable/rabbitmq 
`
by specifying all parameters in values-production.yaml but no luck logging in.

Only this way of installation works 
```
helm install --name rabbit-mq-test \
  --set rabbitmq.username=admin,rabbitmq.password=verySECRETpassword,rabbitmq.erlangCookie=secretcookie,persistence.storageClass=gp2 \
    stable/rabbitmq
```
