### ISSUE TITLE
Become trusted collaborator for incubator/hoverfly chart

### ISSUE THREAD

**Issue by tommysitu** [helm/charts#13874]
Hello,

I am the maintainer of the incubator/hoverfly chart: https://github.com/helm/charts/tree/master/incubator/hoverfly

Could someone add me (@tommysitu) as a trusted collaborator please? I'd like to have the permission for merging PR for the chart. 

Thanks in advance.

**Comment by maorfr** [comment]
done!

**Comment by tommysitu** [comment]
Thank you!
