### ISSUE TITLE
[stable/kong] Allow to run DB Less and Without Ingress Controller

### ISSUE THREAD

**Issue by shreyaskarnik** [helm/charts#13883]
**Is your feature request related to a problem? Please describe.**
It would be great if the Kong chart allows to run Kong in DB Less Mode without the ingress controller.

**Describe the solution you'd like**
Currently ingress controller is switched off by default but when option `env.database=off` is provided along Kong chart deployment is unsuccessful and forces to set `--set ingressController.enabled=true` in order to get the chart working. It would be great if there is an option to only run Kong in DB Less Mode. In our use case we have other mechanism using `:8001/config` on all nodes to get the Kong config bootstrapped

**Comment by shreyu86** [comment]
False alarm, was a mis configuration on my part.
