### ISSUE TITLE
stable/achore-engine won't run in EKS

### ISSUE THREAD

**Issue by mickengland** [helm/charts#13888]
**Describe the bug**
helm install stable/anchore-engine gives the following error:
Error: validation failed: error validating "": error validating data: unknown object type "nil" in PersistentVolumeClaim.metadata.annotations.helm.sh/resource-policy

I can't see anything in the values.yaml to specify the storage class or pvc for AWS EBS volume.

**Version of Helm and Kubernetes**:
$ k version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.14.0-rc.2", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0-rc.2", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

**Which chart**:
stable/achore-engine

**What happened**:
Installation throws error about unknown object type "nil" in PersistentVolumeClaim.metadata.annotations.helm.sh/resource-policy

**What you expected to happen**:
Expected Anchore to install in the cluster

**How to reproduce it** (as minimally and precisely as possible):
run helm install stable/anchore-engine

**Anything else we need to know**:
No.

**Comment by Btodhunter** [comment]
@mickengland This is an issue with the postgresql dependent chart & helm v2.14.0. I just put in #13891 for Chart v1.0.3 that fixes the values.yaml file to fix this issue. You can also fix this issue by updating the values.yaml file with:
```
postgresql:
  persistence:
    resourcePolicy: nil

anchore-feeds-db:
  persistence:
    resourcePolicy: nil
```

**Comment by fermuch** [comment]
Exactly the same error occurs with `stable/sentry`, and it is solved with the same fix as @Btodhunter pointed out.

**Comment by zhill** [comment]
@mickengland or @Btodhunter can this be closed?
