### ISSUE TITLE
customizing a Helm chart install

### ISSUE THREAD

**Issue by hadifarnoud** [helm/charts#13901]
I have been using Dokuwiki helm chart and wordpress helm chart.

how can I customize the image of these charts? I mean, how can I edit a dokuwiki file and update it? looks like helm is pretty restrictive when it comes to editing installed software files. or, I don't know how to do it

**Comment by miguelaeh** [comment]
Hi @hadifarnoud ,
If you want to update the image you can build your own image on local, you need then to upload this image to a registry, for example Dockerhub, and finally set this image on the `values.yaml`.
Upload it to a registry is necessary because the cluster nodes do not use your local registry.
Is that what you are asking for?

**Comment by miguelaeh** [comment]
Hi @hadifarnoud ,
If you do not make important configuration changes, you don't need to create your own helm chart, just change the image in our. If you want to customize our image, you can modify our  `Dockerfile` from GitHub, rebuild the image and set your image in the chart template (or with the `--set` option on deploy time) but before you need to upload to an image registry.

>I mean, how can I edit a dokuwiki file and update it? 

If you actually just want to change content on the Dokuwiki web, you can do it through the browser in the `Media Manager` tab.   

If you need more info feel free to tell me what you want exactly so I can help you in more detail.

**Comment by hadifarnoud** [comment]
thank you @miguelaeh. dokuwiki built in ftp era. for simple things like editing footer or changing logo, I have to edit template files.

if the Helm Chart is using persistent storage for the dokuwiki core files, then I can just edit it via Media Manager and my changes will stick. is this assumption correct?

**Comment by hadifarnoud** [comment]
I found a way. I was able to ssh into the node that pvc was attached to. then I found what folder was the volume attached to. I was able to find the file and edit with `nano`.

it worked

**Comment by miguelaeh** [comment]
That's okay too, but a little complicated to modify a file.
