### ISSUE TITLE
[RabbitMQ High Available e.g. stable/rabbitmq-ha] Failed to get nodes from k8s 

### ISSUE THREAD

**Issue by ogetysaisandeep** [helm/charts#13932]
**Describe the bug**

Deployed EKS Cluster in AWS with 3 nodes.

Deployed regular stable/rabbitmq using helm and tried our various options. We have achieved our goal. Our backlog is to create with HA Nodes. So trying to deploy using ha as replicas 3.

When I tried to deploy, first node deployed successfully and when cluster tried to deploy second node, then I face this issues. 

Failed to get nodes from k8s - {failed_connect,[{to_address,{“kubernetes.default.svc.cluster.local”,443}},

I have tried various options but couldn't find any good solution.   

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

**Which chart**:
rabbitmq-ha

**Comment by liupeng0518** [comment]
same issues

**Comment by abhi-dwivedi** [comment]
any update on this

**Comment by steven-sheehy** [comment]
> Failed to get nodes from k8s - {failed_connect,[{to_address,{“kubernetes.default.svc.cluster.local”,443}},

rabbitmq-ha does peer discovery by connecting to the kube-apiserver using this service. Sounds like this service does not exist (`kubectl get service -n default`) or could be you're using a different domain than `cluster.local`. If so please set `clusterDomain` appropriately.

If not those, then it could be a connectivity issue in your cluster you'll need to diagnose on your own and is not specific to this chart. Try ping, curl, etc. from inside pods to ensure that service is reachable.

**Comment by CodechCFA** [comment]
Make sure your worker node kubernetes versions match the cluster version you set. I forgot to update the EKS worker AMIs to the 1.14 version after upgrading the cluster version from 1.11 to 1.14 and it resulted in this error popping up when trying to start rabbitmq.
