### ISSUE TITLE
[stable/redis-ha] not working properly

### ISSUE THREAD

**Issue by devlounge** [helm/charts#13937]
**Describe the bug**
check-quorum.sh is not used by liveness / readiness probes, maybe it should.

**Version of Helm and Kubernetes**:
Helm 2.13
Kubernetes 1.13

**Which chart**:
stable/redis-ha 3.0.4

**What happened**:
FYI: No persistence enabled.

After the statefulset gets fully provisioned:
0 becomes master => its sentinel report 0 slaves but its redis has 2 connected slaves
1 + 2 become slaves => sentinels + redis properly configured

Kill pod 0:
1 becomes master => but only 1 slave connects to it (pod 0 after restart)
2 remains slave => its sentinel still thinks 0 is its master
0 becomes slave of 1

Kill pod 1:
not getting better

and so on...

**What you expected to happen**:
full failover and both sentinels and redis report 2 slaves and 1 master and updated themselves post-failover.
I believe we need more checks in readiness and liveness probes. I was wondering why check-quorum.sh is not used as well.

**Comment by maxout123** [comment]
The same issue with redis-ha-3.6.1
