### ISSUE TITLE
Jenkins Helm chart - using existing PVC (Persistent Disk of Google cloud), Jenkins Pod is restarting for 20 mins - showing in state Init:0/1 

### ISSUE THREAD

**Issue by manojshetty28** [helm/charts#13954]
Hi All,
We created new PV and bound PV to PVC in GKE cluster. PV is Persistent disk of Google cloud.
When running Helm Jenkins chart, we are setting the new PVC name as values.

--set persistence.existingClaim=PVC_NAME

Error: 
Jenkins POD is not starting after running helm command.
It is showing in state Init:0/1 and deployment is also coming unavailable. error message: Back-off restarting failed container.

We have waited for 30 mins, but the container is restarting again and again

Can you please help, thanks

**Comment by eh-am** [comment]
Can you run `describe` on the pod?

**Comment by varshama** [comment]
Hello, 
Our container is getting restarted various times.

![image](https://user-images.githubusercontent.com/47240729/58000694-29e69980-7af7-11e9-94d7-ade4230b4586.png)
![jenkins beta](https://user-images.githubusercontent.com/47240729/58000723-3e2a9680-7af7-11e9-9ed4-be047e8ac15b.PNG)

**Comment by manojshetty28** [comment]
We need urgent help on this ? Thanks

**Comment by torstenwalter** [comment]
From the screenshots I can't see any error. Would be great if you could share more details of the error. 

e.g. kubectl describe deployment ...
kubectl logs <jebkins_pod>

Especially the logs from the init container in case that's not starting.

BTW: it makes it easier if you share a  text copy of output instead of screenshots.

**Comment by manojshetty28** [comment]
Thanks we will reply

**Comment by varshama** [comment]
Name:               jenkinsv2-8699b759dd-bj6kq
Namespace:          jenkins
Priority:           0
PriorityClassName:  <none>
Node:               gke-beta-jf-sf-clust-default-capacity-30324954-ktzf/10.250.0.32
Start Time:         Mon, 20 May 2019 08:45:29 +0000
Labels:             app.kubernetes.io/component=jenkins-master
                    app.kubernetes.io/instance=jenkinsv2
                    app.kubernetes.io/managed-by=Tiller
                    app.kubernetes.io/name=jenkins
                    helm.sh/chart=jenkins-1.1.16
                    pod-template-hash=8699b759dd
Annotations:        checksum/config: 7394d5224e7ac65de6f4a7b0df225c264b077d22482df684c5b9cfc5fe85ce5d
Status:             Pending
IP:                 172.20.0.15
Controlled By:      ReplicaSet/jenkinsv2-8699b759dd
Init Containers:
  copy-default-config:
    Container ID:  docker://c8ac038d3ebd4c719b319bfd9d41ac42da43d55fbf0abb207fe41057d614c02a
    Image:         jenkins/jenkins:lts
    Image ID:      docker-pullable://jenkins/jenkins@sha256:08bdd27b066e4ec6bfa1228876551e939df1aeaa9d878e6ddb2b183cd208dc2b
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      /var/jenkins_config/apply_config.sh
    State:          Running
      Started:      Mon, 20 May 2019 08:54:22 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 20 May 2019 08:45:48 +0000
      Finished:     Mon, 20 May 2019 08:54:21 +0000
    Ready:          False
    Restart Count:  1
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:     50m
      memory:  256Mi
    Environment:
      ADMIN_PASSWORD:  <set to the key 'jenkins-admin-password' in secret 'jenkinsv2'>  Optional: false
      ADMIN_USER:      <set to the key 'jenkins-admin-user' in secret 'jenkinsv2'>      Optional: false
    Mounts:
      /tmp from tmp (rw)
      /usr/share/jenkins/ref/plugins from plugins (rw)
      /usr/share/jenkins/ref/secrets/ from secrets-dir (rw)
      /var/jenkins_config from jenkins-config (rw)
      /var/jenkins_home from jenkins-home (rw)
      /var/jenkins_plugins from plugin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from jenkinsv2-token-jt6lc (ro)
Containers:
  jenkinsv2:
    Container ID:
    Image:         jenkins/jenkins:lts
    Image ID:
    Ports:         8080/TCP, 50000/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      --argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)
      --argumentsRealm.roles.$(ADMIN_USER)=admin
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:      50m
      memory:   256Mi
    Liveness:   http-get http://:http/login delay=90s timeout=5s period=10s #success=1 #failure=12
    Readiness:  http-get http://:http/login delay=60s timeout=1s period=10s #success=1 #failure=3
    Environment:
      JAVA_OPTS:
      JENKINS_OPTS:
      JENKINS_SLAVE_AGENT_PORT:  50000
      ADMIN_PASSWORD:            <set to the key 'jenkins-admin-password' in secret 'jenkinsv2'>  Optional: false
      ADMIN_USER:                <set to the key 'jenkins-admin-user' in secret 'jenkinsv2'>      Optional: false
    Mounts:
      /tmp from tmp (rw)
      /usr/share/jenkins/ref/plugins/ from plugin-dir (rw)
      /usr/share/jenkins/ref/secrets/ from secrets-dir (rw)
      /var/jenkins_config from jenkins-config (ro)
      /var/jenkins_home from jenkins-home (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from jenkinsv2-token-jt6lc (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  plugins:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  jenkins-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      jenkinsv2
    Optional:  false
  plugin-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  secrets-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  jenkins-home:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  beta-jenkins-pvc
    ReadOnly:   false
  jenkinsv2-token-jt6lc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  jenkinsv2-token-jt6lc
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason                  Age                  From                                                          Message
  ----    ------                  ----                 ----                                                          -------
  Normal  Scheduled               12m                  default-scheduler                                             Successfully assigned jenkins/jenkinsv2-8699b759dd-bj6kq to gke-beta-jf-sf-clust-default-capacity-30324954-ktzf
  Normal  SuccessfulAttachVolume  12m                  attachdetach-controller                                       AttachVolume.Attach succeeded for volume "beta-jenkins-pv"
  Normal  Pulling                 3m27s (x2 over 12m)  kubelet, gke-beta-jf-sf-clust-default-capacity-30324954-ktzf  pulling image "jenkins/jenkins:lts"
  Normal  Pulled                  3m27s (x2 over 12m)  kubelet, gke-beta-jf-sf-clust-default-capacity-30324954-ktzf  Successfully pulled image "jenkins/jenkins:lts"
  Normal  Created                 3m27s (x2 over 12m)  kubelet, gke-beta-jf-sf-clust-default-capacity-30324954-ktzf  Created container
  Normal  Started                 3m27s (x2 over 12m)  kubelet, gke-beta-jf-sf-clust-default-capacity-30324954-ktzf  Started container

**Comment by varshama** [comment]
root@jf-sf-bastion-host:~/betayaml# kubectl logs jenkinsv2-8699b759dd-bj6kq -n jenkins
Error from server (BadRequest): container "jenkinsv2" in pod "jenkinsv2-8699b759dd-bj6kq" is waiting to start: PodInitializing

**Comment by varshama** [comment]
Hello, we need urgent help.

**Comment by eh-am** [comment]
From what I see from the logs your Init Container is crashing. 

You can use the `--previous` flag to get logs from the previous run. Combine that with the `-c` flag to specify the container (in this case, `copy-default-config`). 

Btw use \`\`\` myCode \`\`\` to format the code (https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

**Comment by manojshetty28** [comment]
We are running Jenkins Pod in a Private GKE cluster

**Comment by torstenwalter** [comment]
@manojshetty28 You already said this in the issue description. I suggest to step into it using the suggestion from @eh-am 

The logs from the failing init container would be helpful. 
Did it work ever before with that pre-existing PVC? If not it could be an permission issue e.g. that the script is not able to write to disk.

The init container `copy-default-config` is defined here
https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml#L83-L146 and the content of the [apply_config.sh](https://github.com/helm/charts/blob/master/stable/jenkins/templates/config.yaml#L217) script.

Yours might differ depending of the version of the chart. You can always check the generated resources within your cluster. Digging into it is something only you would be able to to as long as you can't provide steps how to reproduce the issue. A lot depends on your setup e.g. the content of the existing disk.
