### ISSUE TITLE
Agent pods fail to start on worker nodes in EKS set-up

### ISSUE THREAD

**Issue by pravarag** [helm/charts#13970]
I've been facing the following error from agent pods while installing kiam helm chart on an EKS cluster. I've a 6 node cluster with 3 nodes dedicated to kiam-server processes with taints and tolerations, and 3 for kiam-agent  processes to run. With all the recommended settings, the agent pods fail to start up with the error `"level":"fatal","msg":"error creating server gateway: error dialing grpc server: context deadline exceeded"`. But, when I create the kiam resources manually using yamls as available here **https://github.com/uswitch/kiam/**, it works perfectly fine.

**Comment by varkey** [comment]
Ran into the same issue as this on a `kops` created cluster. Looks like the same issue @DReigada 's PR fixes - https://github.com/helm/charts/pull/14043

The certificate which gets created is below

```
        Subject: CN=Kiam Server
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:c3:10:a5:c7:43:9a:f8:f9:8b:e8:c8:19:1e:12:
                    61:a3:42:18:99:2b:ef:25:b2:f4:43:66:5a:ca:87:
                    16:08:bc:e0:9d:3f:1e:7c:49:ee:c5:f5:ff:cc:83:
                    ad:10:a9:a6:92:d2:6d:14:a3:3e:93:4d:57:87:eb:
                    18:b3:e9:5a:24:6d:f0:f4:a5:f1:f8:f6:5b:4b:d8:
                    5c:66:ef:6e:32:89:c1:23:60:9f:70:6b:a4:b0:3d:
                    53:bd:bf:bf:38:bd:2c:65:92:fe:10:10:f0:3b:e3:
                    22:58:bd:da:5f:90:9e:49:a8:ed:40:ab:83:90:54:
                    a6:bc:6e:01:0c:32:87:30:f6:67:43:b6:34:11:e0:
                    f3:94:93:8c:1d:72:15:b5:58:0a:07:bf:e7:c8:26:
                    8c:42:84:ff:cd:47:98:28:d2:d7:f2:98:81:11:56:
                    0f:0f:55:8e:ac:14:6b:d8:d7:e5:f1:67:71:ec:ab:
                    74:0c:fa:ed:3b:59:f2:42:f7:3a:dc:6d:65:74:0f:
                    3e:71:ef:ab:44:3c:9e:1d:63:3c:41:f4:93:31:3f:
                    5d:ae:62:6b:07:c0:97:e6:44:7d:a9:f4:da:31:8b:
                    d6:13:5e:f4:25:51:ea:c4:0c:e0:2d:a4:3c:c6:a8:
                    80:a0:e3:45:f2:f4:23:b1:40:7b:e2:8c:a4:ba:23:
                    cc:37
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Alternative Name:
                DNS:kiam-server, DNS:kiam-server:%!s(float64=443), DNS:127.0.0.1:%!s(float64=443), IP Address:127.0.0.1
```

However the `kiam-server` service which gets created has the release name as well, and the agent is configured to use the DNS name. The cert doesn't have a matching name and hence the connection from the agent fails.

**Comment by DReigada** [comment]
As a quick fix for the issue (if you don't want to use a forked version of the chart), you can add the following lines to your kiam configuration

```yaml
kiam:
  fullnameOverride: <someName>-kiam
  nameOverride: <someName>-kiam
  serviceAccounts:
    agent:
      name: <someName>-kiam-agent
    server:
      name: <someName>-kiam-server
```

**Comment by pravarag** [comment]
So, in my case the error mentioned above was more of a warning. The actual error faced was related to hostname mismatch for TLS certificates between Server and Agent. I was able to fix it, so closing this issue for now.

**Comment by varkey** [comment]
Not sure if this can be resolved, but if the `stable/kiam` chart is installed as-is with a release name other than `kiam`, the generated TLS certificate will be invalid causing the `agent` pods to go into `CrashLoopBackoff` as it wouldn't be able to establish a connection to the `kiam-server`
