### ISSUE TITLE
stable/chart/spinnaker: Error: parse error in "spinnaker/templates/configmap/service-settings.yaml"

### ISSUE THREAD

**Issue by aryak007** [helm/charts#13989]
**Describe the bug**
I'm trying to install the `spinnaker` chart with the following:
`helm install --name spinnaker --namespace spinnaker stable/spinnaker --timeout 600`
and I get the following error:
```Error: parse error in "spinnaker/templates/configmap/service-settings.yaml": template: spinnaker/templates/configmap/service-settings.yaml:37: function "mergeOverwrite" not defined```

**Version of Helm and Kubernetes**:
Helm :
```
Client: &version.Version{SemVer:"v2.11.0"
Server: &version.Version{SemVer:"v2.11.0"
```
Kubernetes - 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:05:06Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
`chart/spinnaker`
**What happened**:
```Error: parse error in "spinnaker/templates/configmap/service-settings.yaml": template: spinnaker/templates/configmap/service-settings.yaml:37: function "mergeOverwrite" not defined```

**How to reproduce it** (as minimally and precisely as possible):
Just run `helm install --name spinnaker --namespace spinnaker stable/spinnaker --timeout 600`

**Comment by emas80** [comment]
Same issue here... 
I've tried with the version 1.9.2 and 1.9.0 of the chart, without any luck.
It seems that a function that is used is not found

**Comment by mdcsaenz** [comment]
Same issue as well.

**Comment by gameiro83** [comment]
Same issue here too. Maybe some commit merge went wrong?

**Comment by mfreebairn-r7** [comment]
Have you tried updating your version of helm? I saw this issue before updating to latest helm version

**Comment by aryak93** [comment]
Is there an update on this? I'm still unable to get spinnaker up and running on my K8s cluster.

**Comment by mfreebairn-r7** [comment]
@aryak93 what version of helm/tiller are you using?

**Comment by mdcsaenz** [comment]
helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

**Comment by mfreebairn-r7** [comment]
can you try upgrading to v2.14.0 and check if you get the same error?

**Comment by mdcsaenz** [comment]
That actually worked thank you! @aryak93 upgrade your helm version for client and server.

**Comment by RikuXan** [comment]
For me, upgrading to v2.14.0 didn't work, I'm still getting the same error. Using version 1.8.1 of the chart works though.
