### ISSUE TITLE
mongodb-replicaset does not support non-default cluster domain

### ISSUE THREAD

**Issue by venezia** [helm/charts#1399]
**Version of Helm and Kubernetes**:
Helm: 2.5.0
Kubernetes: 1.6.4

**Which chart**:
mongodb-replicaset

**What happened**:
Statefulset would hang on second init container

**What you expected to happen**:
Statefulset deploys successfully

**How to reproduce it** (as minimally and precisely as possible):
Deploy a cluster with a non-default dns domain (_not `cluster.local`_)

**Anything else we need to know**:
I have fix(es)

After debugging it, I found that the issue was with how `peer-finder` works.  It presumes a domain suffix of `cluster.local` and if your cluster does not conform, you will find that `peer-finder` will hang without any messages in the logs.

`gcr.io/google_containers/mongodb-install:0.4` is what the init container uses, which in is built from [this source](https://github.com/kubernetes/charts/tree/master/stable/mongodb-replicaset/init)  The current Dockerfile grabs a [release](http://storage.googleapis.com/kubernetes-release/pets/peer-finder) of `peer-finder` but this release is actually not representative of the current code found in [kubernetes/contrib](https://github.com/kubernetes/contrib/blob/master/pets/peer-finder/peer-finder.go) - it seems to be older than November 10th 2016, when a [domain flag](https://github.com/kubernetes/contrib/commits/master/pets/peer-finder/peer-finder.go) argument was added.

***Fixes***
I have fixed this issue in a number of ways:
* There is a [PR](https://github.com/kubernetes/contrib/pull/2644) to update peer-finder to be a bit more sensible in a default domain
* I created an updated [chart](https://github.com/venezia/k8s-charts/tree/add-domain-mongodb-replicaset/stable/mongodb-replicaset) that would allow a user to specify the `-domain` flag for the init controller (clunky, but better than no option) - but did not create a PR because the current mongodb-install image does have support for the `-domain` flag
* I have created a new init container - the image is on [quay](https://quay.io/repository/samsung_cnct/install-mongodb?tab=tags) and the source for it is [available](https://github.com/samsung-cnct/install-mongodb)
* I have created an updated [chart](https://github.com/samsung-cnct/chart-mongodb-replicaset) that uses the new install-mongodb init container image.  This has worked in creating a working mongodb replicaset in a cluster with a non-default cluster domain.

***Not just MongoDB***
`peer-finder` is in `kubernetes/contrib` and is probably in use by several petsets/statefulset applications.  As it currently stands, anyone using a non-default cluster domain cannot use this program.  Fixing it probably helps other charts/applications beyond mongodb-replicaset.

Please help me contribute this back to the community.  /cc @kubernetes/sig-apps-proposals xref: kubernetes/contrib#2643

**Comment by spiffxp** [comment]
@kubernetes/sig-apps-proposals (restating as an org member to trigger notification)

**Comment by foxish** [comment]
Thanks for contributing back @venezia. I just went over your PR and have some suggestions.
I like the `clusterDomain` option you added to the chart. Why don't we let that option be passed to the init-container as the option `--domain=??` to the peer-finder binary.

**Comment by venezia** [comment]
Because `gcr.io/google_containers/mongodb-install:0.4` 's peer-finder does not have a `-domain` option (it is not up to date with the source found in kubernetes/contrib as I mentioned.

```
$ docker run --rm=true -it --entrypoint /peer-finder  gcr.io/google_containers/mongodb-install:0.4 --help
Usage of /peer-finder:
  -ns string
    	The namespace this pod is running in. If unspecified, the POD_NAMESPACE env var is used.
  -on-change string
    	Script to run on change, must accept a new line separated list of peers via stdin.
  -on-start string
    	Script to run on start, must accept a new line separated list of peers via stdin.
  -service string
    	Governing service responsible for the DNS records of the domain this pod is in.
```

**Comment by foxish** [comment]
I see.
@venezia I can update and push a new container image for mongodb with the latest peer-finder after the fix in https://github.com/kubernetes/contrib/pull/2644 is merged

**Comment by mattfarina** [comment]
@foxish that fix in #2644 has been merged. I noticed the mongodb-install image has a new 0.2 version pushed up but no version newer than 0.4. Any chance you could push up the new image no noted?

**Comment by foxish** [comment]
IIRC, we fixed this and pushed a new image at some point. @venezia can you confirm?

**Comment by venezia** [comment]
code got merged, i'm unsure if a new build of the container image ever happened.  IIRC, before this change, master didn't reflect the then-latest container image by a good bit, so its possible that a new build hasn't happened yet.  I'm not aware where builds are started/etc.

**Comment by mattfarina** [comment]
@venezia On 10/10 A 0.5 container image was pushed. Does a new release need to be cut to pickup the change?

**Comment by venezia** [comment]
It appears a new release is needed

```
$ docker run --rm=true -it --entrypoint=/peer-finder gcr.io/google_containers/mongodb-install:0.5 --help
Usage of /peer-finder:
  -ns string
    	The namespace this pod is running in. If unspecified, the POD_NAMESPACE env var is used.
  -on-change string
    	Script to run on change, must accept a new line separated list of peers via stdin.
  -on-start string
    	Script to run on start, must accept a new line separated list of peers via stdin.
  -service string
    	Governing service responsible for the DNS records of the domain this pod is in.
```

Doesn't match up with https://github.com/kubernetes/contrib/blob/master/peer-finder/peer-finder.go#L40-L46 (its missing the --domain)

This means we'll need to build & push a new build/tag, then update this chart to use the updated tag for its default value

**Comment by mythmoon** [comment]
Has this problem been solved yet? Install 0.6 still has a problem.
no  - domain

**Comment by rushabh-harness** [comment]
This problem is still not resolved. The current mongodb-install docker image is still pointing to the old image without the `-domain` support . Can we please upgrade the image.

**Comment by dnascimento** [comment]
https://github.com/helm/charts/pull/17883
