### ISSUE TITLE
Bad label selectors queries in some incubator chart READMEs

### ISSUE THREAD

**Issue by a-robinson** [helm/charts#140]
A handful of READMEs for incubator charts have instructions with kubectl commands demonstrating label selectors that flat out don't work. For example:

https://github.com/kubernetes/charts/tree/master/incubator/etcd/README.md has a bunch of kubectl commands in it with `-l "app=etcd"`, but that label never gets set anywhere in its template:

``` shell
$ helm install --name my-release incubator/etcd
NAME: my-release
LAST DEPLOYED: Fri Oct 21 13:50:01 2016
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> apps/PetSet
NAME              DESIRED   CURRENT   AGE
my-release-etcd   3         3         0s

==> v1/Service
NAME              CLUSTER-IP   EXTERNAL-IP   PORT(S)             AGE
my-release-etcd   None         <none>        2380/TCP,2379/TCP   0s
$ kubectl get pods
NAME                READY     STATUS    RESTARTS   AGE
my-release-etcd-0   1/1       Running   0          3m
my-release-etcd-1   1/1       Running   0          3m
my-release-etcd-2   1/1       Running   0          2m
$ kubectl get pods -l "app=etcd"
$ 
```

Incorrect "app=" label selectors appear in other incubator charts as well, probably due to being cribbed from the etcd chart.

**Comment by lachie83** [comment]
@a-robinson thanks for the feedback. I'll get these labelled correctly so that this works.

**Comment by lachie83** [comment]
Updated label query to use component on etcd,consul and zookeeper charts.
