### ISSUE TITLE
Please, add me as a trusted collaborator

### ISSUE THREAD

**Issue by hectorj2f** [helm/charts#14015]
I'd like to be added as a trusted collaborator. In my organization we're using Helm stable charts and contributing back to improve them.

I 'd be lately contributing to fluent-bit and elasticsearch charts, but I'll do for other charts if I have the chance. 

I've been maintainer of opensource projects during several years, as part of RedHat and other organizations.

Thanks.

**Comment by maorfr** [comment]
hey @hectorj2f,

thanks for stepping up!
are you currently maintaining any charts in this repository?

**Comment by hectorj2f** [comment]
@hectorj2f I started creating two PRs one for fluentbit and another elasticsearch. Also, I created some issues as well. The main idea is to use and help to maintain others such traefik, Prometheus, kibana, ... exporters too.

**Comment by maorfr** [comment]
check this out:
#13867 
#13869

**Comment by hectorj2f** [comment]
@maorfr I added myself as maintainer for velero https://github.com/helm/charts/pull/14031

**Comment by maorfr** [comment]
added you as a collaborator and approved #14031 

thanks for getting involved!

**Comment by hectorj2f** [comment]
@maorfr I think I'll offer myself to maintain certain charts like fluent-bit and elasticsearch. The response time of the current maintainers or owners is unfortunately pretty high
