### ISSUE TITLE
stable/jenkins securityRealm issue

### ISSUE THREAD

**Issue by nitrams0** [helm/charts#14048]
**Describe the bug**
I've defined an ActiveDirectory securityRealm in values.yaml but the the pod's securityRealm continues to default to Legacy.

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/jenkins

**What happened**:
I configured a custom securityRealm in the values.yaml, and applied it using the helm install command. (helm install --namespace sem --name sem-jenkins -f values.yaml stable/jenkins)
[values.yaml.txt](https://github.com/helm/charts/files/3204216/values.yaml.txt)

AD authentication does not work with the Jenkins instance generated. I audited the ~jenkins/config.xml in the pod and the XML has the default Legacy securityRealm.

**What you expected to happen**:
I would expect for AD authentication to work as expected and the custom securityRealm XML info to be in the config.xml file in the pod.

**How to reproduce it** (as minimally and precisely as possible):
run helm install command referencing a custom values.yaml file which includes an AD securityRealm.
helm install --namespace sem --name sem-jenkins -f values.yaml stable/jenkins
Verify the securityRealm config is in the newly created pod.

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
Was it the first install when you configured the security realm or was the chart installed with a different security real before and then changed the value and did a helm update?

You can check if the config.xml is rendered correctly. Here is the source:
https://github.com/helm/charts/blob/master/stable/jenkins/templates/config.yaml#L23

The config.xml is only ever copied once unless you set `master.overwriteConfig`.

**Comment by nitrams0** [comment]
I've tried both the first install and the upgrade and my the resulatant
pod's securityRealm still defaulted to the legacy.
I deleted, and purged my release.
I changed the master.overwriteConfig = true
I installed the release and the securityRealm is still set to the Legacy.
I even tried and ugrade using the same values.yaml, still Legacy.

I've attached the debug output of the upgrade command.
The USER-SUPPLIED VALUES: shows the correct securityRealm.
The COMPUTED VALUES: shows the correct securityRealm.
The MANIFEST: shows the Legacy securityRealm.

I'm unsure why my securityRealm config is not being included.

**Comment by torstenwalter** [comment]
I gave it a try with:

`helm install stable/jenkins --name jenkins --version 1.1.21 --values ci/security-values.yaml`

`ci/security-values.yaml`:
```
master:
  securityRealm: |-
    <securityRealm class="hudson.plugins.active_directory.ActiveDirectorySecurityRealm" plugin="active-directory@1.39">
      <domains>
        <hudson.plugins.active__directory.ActiveDirectoryDomain>
          <name>xx.xxx.xxx</name>
          <bindName>CN=xx_xxxxxxx,OU=xxxxxxxxxxxxxxx,OU=xxxxxxxxxxxxxxx,DC=xx,DC=xxx,DC=xxx</bindName>
          <bindPassword>{xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}</bindPassword>
          <tlsConfiguration>TRUST_ALL_CERTIFICATES</tlsConfiguration>
        </hudson.plugins.active__directory.ActiveDirectoryDomain>
      </domains>
      <startTls>true</startTls>
      <groupLookupStrategy>AUTO</groupLookupStrategy>
      <removeIrrelevantGroups>false</removeIrrelevantGroups>
    </securityRealm>
```

The generated config map contains the securityRealm as specified. I can't judge if the xml config is correct and what you want, but it's at least that what is passed in via `ci/security-values.yaml`

`kubectl get cm jenkins -o yaml`:
```
  ...
  config.xml: |-
    <?xml version='1.0' encoding='UTF-8'?>
    <hudson>
      <disabledAdministrativeMonitors/>
      <version>lts</version>
      <numExecutors>0</numExecutors>
      <mode>NORMAL</mode>
      <useSecurity>true</useSecurity>
      <authorizationStrategy class="hudson.security.FullControlOnceLoggedInAuthorizationStrategy">
        <denyAnonymousReadAccess>true</denyAnonymousReadAccess>
      </authorizationStrategy>
      <securityRealm class="hudson.plugins.active_directory.ActiveDirectorySecurityRealm" plugin="active-directory@1.39">
        <domains>
          <hudson.plugins.active__directory.ActiveDirectoryDomain>
            <name>xx.xxx.xxx</name>
            <bindName>CN=xx_xxxxxxx,OU=xxxxxxxxxxxxxxx,OU=xxxxxxxxxxxxxxx,DC=xx,DC=xxx,DC=xxx</bindName>
            <bindPassword>{xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}</bindPassword>
            <tlsConfiguration>TRUST_ALL_CERTIFICATES</tlsConfiguration>
          </hudson.plugins.active__directory.ActiveDirectoryDomain>
        </domains>

```

I had a look at your `values.yaml.txt` file. That looks like you've been using a version < 1.0 of this chart. Please check which chart version you are using. My comments related to the current one (1.1.21). Pre 1.0.0 most of the values used different case e.g. `Master.SecurityRealm` instead of `master.securityRealm`.
