### ISSUE TITLE
[stable/redis] Replication not working

### ISSUE THREAD

**Issue by Efp95** [helm/charts#14044]
**Describe the bug**

**Version of Helm and Kubernetes**:
Kubernetes v1.10.11
Helm v2.13.1

**Which chart**:
stable/redis

**What happened**:
Slaves got disconnected from master
`info.replication.master_link_status=down`

**What you expected to happen**:
Whenever I set a key in master, it should be replicated to existing slaves

**How to reproduce it** (as minimally and precisely as possible):
Just run `helm install stable/redis --name test --` on local

**Comment by javsalgar** [comment]
Hi,

We would need a bit more details about the platform you are using. In our environment it worked without issues. 

```
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:6379> info replication
# Replication
role:master
connected_slaves:2
slave0:ip=10.32.0.12,port=6379,state=online,offset=308,lag=1
slave1:ip=10.32.0.13,port=6379,state=online,offset=322,lag=0
master_replid:f335276d7e32b6d0cef97b8a468682bf3c32a2d8
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:322
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:322
```
