### ISSUE TITLE
[stable/prometheus-operator]] error on prometheus helm chart

### ISSUE THREAD

**Issue by dioguerra** [helm/charts#14075]
Can you reproduce?

**Describe the bug**
commonLabels not working. See 
https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/prometheus-operator

**What happened**:
The label is added to some of the resources but not all of them

**What you expected to happen**:
All resources to be added the respective labels

**How to reproduce it** (as minimally and precisely as possible):
replace in values file with 
```yaml
commonLabels: 
  scmhash: abc123
  myLabel: aakkmd
```

**Anything else we need to know**:
prom-operator chart v5.7.0

**Comment by vsliouniaev** [comment]
Generally speaking, the resources themselves have labels applied to them, but resources that may get created downstream may not. For example, if a `prometheus` object is created, labels are added to it, but prometheus pods created through the statefulset do not - that is controlled by the `podMetadata` in the `prometheusSpec`
