### ISSUE TITLE
[stable/telegraf] Upgrade to Telegraf 1.10

### ISSUE THREAD

**Issue by fungiboletus** [helm/charts#14094]
Telegraf 1.10 has been released, it's probably better to use the latest stable version.

The version needs to be changed there : https://github.com/helm/charts/blob/aa423569a326d35fc25d3c917fe9bb9c1244c959/stable/telegraf/values.yaml#L9

Sorry, I'm too lazy to do the pull-request as this project's administrative process looks quite cumbersome for simply bumping a docker tag.

**Comment by deepaksood619** [comment]
#14621 PR merged
