### ISSUE TITLE
[stable/postgresql/] ‘/bitnami/postgresql/data’: Permission denied

### ISSUE THREAD

**Issue by ceastman-ibm** [helm/charts#14127]
**Describe the bug**
Trying to use the latest stable/postgresql helm chart, the pods stay in a crashed loop back state: due to:

kubectl logs postgresql-postgresql-master-0
 15:38:03.02 
 15:38:03.02 Welcome to the Bitnami postgresql container
 15:38:03.02 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
 15:38:03.02 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
 15:38:03.03 Send us your feedback at containers@bitnami.com
 15:38:03.03 
 15:38:03.06 INFO  ==> ** Starting PostgreSQL setup **
 15:38:03.16 INFO  ==> Validating settings in POSTGRESQL_* env vars..
 15:38:03.17 INFO  ==> Initializing PostgreSQL database...
 15:38:03.19 INFO  ==> postgresql.conf file not detected. Generating it...
 15:38:03.20 INFO  ==> pg_hba.conf file not detected. Generating it...
mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied
 15:38:03.22 INFO  ==> Stopping PostgreSQL...

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

v1.12.8+IKS

**Which chart**:
https://github.com/helm/charts/tree/master/stable/postgresql

**What happened**:
kube pods fail to start

**What you expected to happen**:
kube pods to successfully start

**How to reproduce it** (as minimally and precisely as possible):
IBM Cloud, create new cluster, helm install this chart with storage persistence enabled

**Anything else we need to know**:

**Comment by tompizmor** [comment]
Hi @ceastman-ibm,

Currently, IBM Cloud Kubernetes Service has some limitations regarding non-root containers and persistent storage permissions. 

You can read more about the issues and the possible workarounds here:

- https://cloud.ibm.com/docs/containers?topic=containers-cs_troubleshoot_storage#nonroot
- https://cloud.ibm.com/docs/containers?topic=containers-cs_troubleshoot_storage#cs_storage_nonroot

**Comment by docktermj** [comment]
I'm getting the same error on minikube using the instructions at https://github.com/Senzing/kubernetes-demo/blob/master/docs/helm-kafka-postgresql/README.md.  Specifically, it fails on this step: https://github.com/Senzing/kubernetes-demo/blob/master/docs/helm-kafka-postgresql/README.md#install-postgresql-helm-chart

The instructions worked about 2 weeks ago, so I'm suspecting a recent change.   

Note:  I also experienced a similar error with bitnami/rabbitmq Helm chart yesterday.  Again, that chart worked 2 weeks ago.

**Comment by docktermj** [comment]
I opened https://github.com/bitnami/charts/issues/1210

**Comment by tompizmor** [comment]
@docktermj I don't think the issue is the same. By default, the postgressql chart should work in Minikube so better to handle your case in the issue you opened in the Bitnami repo.
