### ISSUE TITLE
[stable/sonarqube] volume mount /usr/local for copy_plugins.sh replace all previous content included Open jdk installed

### ISSUE THREAD

**Issue by leafar-maina** [helm/charts#14136]
**Describe the bug**
When I deploy stable/sonarqube the /usr/local content is replace with copy_plugins.sh script, deleting all previous content. The problem is that Open jdk 1.8 is in this place, causing the sonarqube does not to start. 

**Which chart**:
Latest. 

**What happened**:
SonarQube cannot init because java is not longer exist. And show this message: Error running exec bin/run.sh, java is not in PATH. Or something similar. 

**What you expected to happen**:
SonarQube start without problem.

**How to reproduce it** (as minimally and precisely as possible):
Always with base or custom values. 

**Anything else we need to know**:
If volume mount for copy_plugins.sh is changed for other location, pe. /usr/src, sonarqube start ok.

**Comment by svmaris** [comment]
I changed the deployment.yaml to put the file in /tmp/scripts in #14141, which works for me.
