### ISSUE TITLE
[stable/prometheus-operator] Unable to collect container metrics since Kubelets are down after install 

### ISSUE THREAD

**Issue by krishnadurai** [helm/charts#14160]
**Describe the bug**
I'm using helm charts prometheus-operator in order to collect container metrics through cAdvisor in kubelets. While I have deployed prometheus-operator and its components without an error, prometheus is unable to reach each node's kubelet to collect metrics.

**Version of Helm and Kubernetes**:
Helm: 2.13
Kubernetes:1.14

**Which chart**:
stable/prometheus-operator

**What happened**:
Kubelet pods aren't up for the node as shown in targets endpoint in prometheus:

<img width="1582" alt="image" src="https://user-images.githubusercontent.com/6263389/58427300-d22ecc00-80bc-11e9-92a2-a8d47b816901.png">

**What you expected to happen**:
Kubelet operator pods should have been up.

**How to reproduce it** (as minimally and precisely as possible):
Just follow [installation doc](https://github.com/helm/charts/blob/master/stable/prometheus-operator/README.md) for prometheus operator,

**Anything else we need to know**:
```
kubectl get pods
```
```
prometheus-rel-grafana-9fbdc7796-9ldrk                     2/2     Running   0          4h28m
prometheus-rel-kube-state-metrics-84b9dfcd84-v8msf         1/1     Running   0          4h28m
prometheus-rel-prometheus-node-exporter-zpvm9              1/1     Running   0          4h28m
prometheus-rel-prometheus-oper-operator-6cb4b65855-5qfp6   1/1     Running   0          4h28m
prometheus-
prometheus-rel-prometheus-oper-prometheus-0     3/3     Running   1          4h28m
```

**Related issues**:
https://github.com/istio/istio/issues/14119

**Comment by vsliouniaev** [comment]
Having deployed this into a minikube cluster, running `minikube version: v1.1.0` and using the switch `--kubernetes-version=v1.14.2` I cannot reproduce your issue.

**Comment by krishnadurai** [comment]
<img width="1653" alt="Screenshot 2019-05-28 at 12 03 57 AM" src="https://user-images.githubusercontent.com/6263389/58435026-2c8b5500-80dc-11e9-9113-0374d3d10ec9.png">

It's still the same for me @vsliouniaev.
What is interesting is that since I'm deploying in default namespace, prometheus is trying to look for kubelet collector pods in default (as shown in the diagram) whereas the tags say that these kubelet pods should in kube-system namespace.

Am I missing something here?

**Comment by vsliouniaev** [comment]
Kubelet endpoint discovery is done using an `endpoints` object deployed into the kube-system namespace. The scraping of the endpoint is working fine, the issue is that prometheus is unable to authenticate to the kubelet. The prometheus operator has a troubleshooting guide for setting up your cluster so that this auth works: https://github.com/coreos/prometheus-operator/blob/master/Documentation/troubleshooting.md#prometheus-kubelet-metrics-server-returned-http-status-403-forbidden

**Comment by krishnadurai** [comment]
@vsliouniaev, thank you! Your solution worked fine for me. I'm closing this issue.
