### ISSUE TITLE
[stable/jenkins] plugins lost

### ISSUE THREAD

**Issue by gimler** [helm/charts#14167]
**Describe the bug**
I have already installed a bunch of plugins in my container image. After deployment, all plugins are lost.

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

**Which chart**:
stable/jenkins:1.1.22

**What happened**:
All plugins from the container image are lost

**What you expected to happen**:
Plugins from the image exist

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I think the problem is that the initContainer override with mount the plugin folder. See
https://github.com/helm/charts/blob/825b32ece3e3bddcf764ba7b30a323e1407ee4c3/stable/jenkins/templates/jenkins-master-deployment.yaml#L139

set `installPlugins: false` doesn't work, because 
```
Error: render error in "jenkins/templates/jenkins-master-deployment.yaml": template: jenkins/templates/jenkins-master-deployment.yaml:41:28: executing "jenkins/templates/jenkins-master-deployment.yaml" at <include (print $.Template.BasePath "/config.yaml") .>: error calling include: template: jenkins/templates/_helpers.tpl:28:19: executing "jenkins.kubernetes-version" at <.Values.master.installPlugins>: range can't iterate over false
```

**Comment by torstenwalter** [comment]
If you don't want to install plugins set `installPlugins` to an empty value:

```
master:
  installPlugins:
```

**Comment by gimler** [comment]
works thanks.

**Comment by torstenwalter** [comment]
I also created a PR which documents it in the README. While fixing it I figured out that it's actually better to set the value to `[]` as it's used internally as array. `false` should also work once the PR is merged ;-)
