### ISSUE TITLE
[stable/odoo] Allow external Postgres server (not the one from chart dependencies)

### ISSUE THREAD

**Issue by cthiebault** [helm/charts#14172]
It would be nice if we could use Odoo chart with an existing Postgres server not configured from Odoo chart dependencies.

I have a Postgres server running in AWS RDS and I don't see how I can configure Odoo chart to use it...

See Keycloak chart as example:
https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/values.yaml#L250

**Comment by tompizmor** [comment]
Hi @cthiebault,

I agree it is a good feature to add to the chart. I will create an internal task so we don't forget to implement this change.

**Comment by ArnauFauquer** [comment]
How can i specify a external database name? in README.md it has the externalDatabase.database parameter but not in values and chart yaml files.
