### ISSUE TITLE
[stable/kong] replicaset service account error running with db-less config

### ISSUE THREAD

**Issue by luizferreira094** [helm/charts#14218]
**Describe the bug**
So, i'm trying to install kong in my cluster, but when i set `database=off` in my values.yaml, ReplicaSet doesn't start the pods because apparently it needs a serviceAccount, which is configured to be created automatically,

**Version of Helm and Kubernetes**:
**Helm Version**: 
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```
**Kubernetes Version**: 1.13.6-gke.0

**Which chart**: kong-0.11.2

**What happened**:
```
Events:
  Type     Reason        Age               From                   Message
  ----     ------        ----              ----                   -------
  Warning  FailedCreate  2s (x11 over 7s)  replicaset-controller  Error creating: pods "kong-kong-747b884764-" is forbidden: error looking up service account api-gateway/kong-kong: serviceaccount "kong-kong" not found
```

**What you expected to happen**: Kong starts using DB-less config

**How to reproduce it** (as minimally and precisely as possible):
```
helm upgrade --install kong stable/kong --set env.database=off --set postgresql.enabled=false
```

**Anything else we need to know**:
I'm not installing Kong as IngressController in this case, i just want it to be an application inside my cluster.

**Comment by aemmons** [comment]
I am experiencing the same issue. I am also trying to use dbless configuration. I had to manually create the ServiceAccount that the helm chart was expecting to get a successful deployment. I am using minikube.

Helm Chart:
`xkong                   1               Thu Aug 15 16:49:50 2019        DEPLOYED        kong-0.11.2             1.1             default`

Helm version:
`Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}`

minikube:
`minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631`

Should the Helm Chart be creating the ServiceAccount?
