### ISSUE TITLE
[stable/prometheus-operator] Upgrade kube-state-metrics to v1.6.0

### ISSUE THREAD

**Issue by Nuru** [helm/charts#14227]
`kube-state-metrics` v1.5.0 is installed by the current `prometheus-operator` chart. [`kube-state-metrics v1.6.0`](https://github.com/kubernetes/kube-state-metrics/releases/tag/v1.6.0) was released 2019-05-06. The current chart version is 1.6.3. Please upgrade the promethus-operator chart to the 1.6 version.

**Is your feature request related to a problem? Please describe.**
I would like to take advantage of the new features and bugfixes in the new version.

**Describe the solution you'd like**
AFAIK, all that is needed is a one character change to [requirements.yaml](https://github.com/helm/charts/blob/56890097c1d702702870c670eb942f1900ed0aac/stable/prometheus-operator/requirements.yaml#L4)
```
-     version: 1.1.*
+     version: 1.6.*
```

**Describe alternatives you've considered**
Setting `kube-state-metrics.image.tag: v1.6.0` in `values.yaml` does not work because the new version requires new RBAC permissions. The new permissions are installed with the new chart, but not by simply updating the image version.

**Comment by vsliouniaev** [comment]
@Nuru Would you be interested in submitting a PR to fix the issue?

**Comment by Nuru** [comment]
@vsliouniaev I do not want to submit a PR to fix this issue because I do not want to publicize my email address, as is required to submit a PR to this repo. I'm still getting spam on an email address I used for Mozilla 20 years ago. It's a 1-line change; someone who is already a part of the project can easily make it.
