### ISSUE TITLE
[stable/prometheus-operator] alert manager nodes die, error no such host

### ISSUE THREAD

**Issue by MaxDiOrio** [helm/charts#14286]
**Describe the bug**
When deploying a new instance of prometheus-operator, the Alertmanager pods die repeatedly with the following errors:

component=cluster msg="failed to join cluster" err="2 errors occurred:\n\t* Failed to resolve alertmanager-kindly-magpie-prometheus-o-alertmanager-0.alertmanager-operated.default.svc:6783: lookup alertmanager-kindly-magpie-prometheus-o-alertmanager-0.alertmanager-operated.default.svc on 10.43.0.10:53: no such host\n\t* Failed to resolve alertmanager-kindly-magpie-prometheus-o-alertmanager-1.alertmanager-operated.default.svc:6783: lookup alertmanager-kindly-magpie-prometheus-o-alertmanager-1.alertmanager-operated.default.svc on 10.43.0.10:53: no such host\n\n"

**Version of Helm and Kubernetes**:
Helm v2.14.0
K8S:  v1.11.6

**Which chart**:
stable/prometheus-operator

**What happened**:
Alert manager pods die repeatedly with the above error.  This appears to force the prometheus container to also die as it can't post to alert manager.  

If you look at service discovery, Alertmanager-operated has no IP's associated with it.

The DNS name that it is looking up also appears wrong as there is no cluster.local at the end. 

**What you expected to happen**:

Pods should turn up without an issue.

**How to reproduce it** (as minimally and precisely as possible):
Running a Rancher cluster, have never had an issue deploying helm charts before.

Did a helm install stable/prometheus-operator -f prometheus-operator.yaml

The yaml is my answer file, which is default except for my thanos config section.

**Anything else we need to know**:

**Comment by vsliouniaev** [comment]
@MaxDiOrio From what you are describing, this does not read like an application error.

alertmanager-operated and prometheus-operated services are used by the operator to keep track of the pods, but not for routing.

Prometheus does not exit if it finds no alertmanagers and alertmanagers do not exit if they cannot form a cluster. The logs you are seeing read like a symptom of the alertmanager pods not being up long enough to form a cluster.

You should be able to get the reason for the containers exiting by using `kubectl describe`

**Comment by MaxDiOrio** [comment]
Looks like someone had another instance
