### ISSUE TITLE
[stable/kubernetes-dashboard] README install and security don't work

### ISSUE THREAD

**Issue by MichaelJCole** [helm/charts#14289]
**Describe the bug**
Hi, there's been alot of work put into the dashboard and the chart, but the installation instructions and security info are out of date.  It's such a fundamental part of Kubernetes and security, it should have decent documentation and sensible security advice.

The [stable README](https://github.com/helm/charts/tree/master/stable/kubernetes-dashboard) says:

```
helm install stable/kubernetes-dashboard
```
It prints some connection info at the bottom, which results in this error:
```
E0529 11:40:39.044919   32294 portforward.go:400] an error occurred forwarding 8443 -> 8443: error forwarding port 8443 to pod 3600e06f6a48f5403a570a4a1ec313cfcc8fe16a9f1394f5132a08f9f6cd1da2, uid : exit status 1: 2019/05/29 18:40:39 socat[14515] E connect(5, AF=2 127.0.0.1:8443, 16): Connection refused
```
And leads to this in the logs:
```
kubectl logs sanguine-fly-kubernetes-dashboard-6bd4f7c558-z9tdh                                                                                                NewMod master
2019/05/29 18:41:23 Starting overwatch
2019/05/29 18:41:23 Using in-cluster config to connect to apiserver
2019/05/29 18:41:23 Using service account token for csrf signing
2019/05/29 18:41:23 Successful initial request to the apiserver, version: v1.14.2
2019/05/29 18:41:23 Generating JWE encryption key
2019/05/29 18:41:23 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2019/05/29 18:41:23 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2019/05/29 18:41:23 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: unexpected object: &Secret{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Data:map[string][]byte{},Type:,StringData:map[string]string{},}
2019/05/29 18:41:25 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2019/05/29 18:41:26 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2019/05/29 18:41:26 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2019/05/29 18:41:26 Storing encryption key in a secret
panic: secrets is forbidden: User "system:serviceaccount:default:sanguine-fly-kubernetes-dashboard" cannot create resource "secrets" in API group "" in the namespace "kube-system"

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.(*rsaKeyHolder).init(0xc42041d220)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:131 +0x35e
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.NewRSAKeyHolder(0x1367500, 0xc4203fdf20, 0xc4203fdf20, 0x1213a6e)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:170 +0x64
main.initAuthManager(0x13663e0, 0xc420287c20, 0xc4202c9cd8, 0x1)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:185 +0x12c
main.main()
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:103 +0x26b
```

Which leads to a variety of git issues and commits:
https://github.com/helm/charts/pull/12496/files#diff-814573c2b6c423b43e4c90eb469a41c8
https://github.com/helm/charts/issues/3104
https://github.com/helm/charts/issues/4102
https://github.com/helm/charts/issues/5493

I'm now just throwing options at the command line.  

What is the value of Helm as an abstraction if I have to learn the implementation details to get it to work and it's vaguely insecure?

Could you please document how to use this - as if it's the first thing someone would attempt to use with helm?  Thank you!  If I get it to work on DO, I'll post the command in the comments.

**Version of Helm and Kubernetes**:

Helm 2.14.0
kubectl version --short                                                                                                                                       
Client Version: v1.14.2
Server Version: v1.14.2
Digital Ocean cluster 

**Which chart**:
stable/kubernetes-dashboard

**What happened**:

see bug description

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

```
doctl k8s cluster create hurray --auto-upgrade --count 3 --region sfo2
kubectl -n kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account tiller
helm install stable/kubernetes-dashboard
# Follow the shell commands in the output.
```

**Anything else we need to know**:

**Comment by MichaelJCole** [comment]
Ok, fine.  I have to work on other things.  I got past the error above (the issue is about documenting something that works).

```
helm install stable/kubernetes-dashboard --name kubernetes-dashboard --namespace="kube-system" --set fullnameOverride="kubernetes-dashboard"  --set rbac.clusterAdminRole=true
kubectl get serviceaccounts kubernetes-dashboard --namespace kube-system -o yaml  
kubectl get secrets kubernetes-dashboard-token-dfl8r --namespace kube-system -o yaml  
```

Following the output from the helm install, the proxy loads a page, but the tokens from the kubernetes-dashboard or tiller secrets don't authenticate.

**Comment by MichaelJCole** [comment]
Ok, this is the best I can come up with before moving on to other things.
```
helm install stable/kubernetes-dashboard --name kubernetes-dashboard --namespace="kube-system" --set fullnameOverride="kubernetes-dashboard"  --set rbac.clusterReadOnlyRole=true --set enableSkipLogin=true

# To start:
export POD_NAME=$(kubectl get pods -n kube-system -l "app=kubernetes-dashboard,release=kubernetes-dashboard" -o jsonpath="{.items[0].metadata.name}")
echo https://127.0.0.1:8443/
sensible-browser https://127.0.0.1:8443/
kubectl -n kube-system port-forward $POD_NAME 8443:8443
```

I don't think there is a secure configuration for this chart, because no secure configuration has been communicated.  I tried some token options, but they didn't work.

**Comment by dhrn** [comment]
i am facing the same issue

`E0608 20:17:59.718055   19043 portforward.go:400] an error occurred forwarding 9090 -> 9090: error forwarding port 9090 to pod f488b77b9c41f3f6324fb5e3ae909ce58a2642d9dbfea9445c68edcdc9d000fb, uid : exit status 1: 2019/06/08 14:47:59 socat[14411] E connect(5, AF=2 127.0.0.1:9090, 16): Connection refused
`

is there any workaround?

**Comment by MichaelJCole** [comment]
It looks like Helm is having trouble maintaining these charts.  

I've been replacing Helm with https://kustomize.io/ - it's a configuration system built into `kubectl`.
