### ISSUE TITLE
[stable/mongodb-replicaset] document config secret must be file 'key.txt'

### ISSUE THREAD

**Issue by MichaelJCole** [helm/charts#14299]
**Describe the bug**
Snap! I'm trying this [DO tutorial](https://www.digitalocean.com/community/tutorials/how-to-scale-a-node-js-application-with-mongodb-using-helm) and it is failing.

```
$ helm install stable/mongodb-replicaset --name mongo --set replicas=3,replicaSetName=db,auth.enabled=true,auth.existingKeySecret=mongo-root,auth.existingAdminSecret=mongo-secret,persistentVolume.size=2Gi

NAME:   mongo
LAST DEPLOYED: Wed May 29 16:10:11 2019
NAMESPACE: default
STATUS: DEPLOYED

...
$  kubectl get pods                                                                                                                                               
NAME                         READY   STATUS       RESTARTS   AGE
mongo-mongodb-replicaset-0   0/1     Init:Error   2          32s
```
**Which chart**:
stable/mongodb-replicaset

**Anything else we need to know**:

The problem was I was creating the mongo-root secret like this:

```
kubectl create secret generic mongo-root --from-file=mongo-root.txt
```
The file must be named key.txt or copy-config fails.
```
kubectl create secret generic mongo-root --from-file=key.txt
```

This requirement isn't documented in the README.md

**Comment by steven-sheehy** [comment]
It is already documented [here](https://github.com/helm/charts/tree/master/stable/mongodb-replicaset#authentication).

**Comment by MichaelJCole** [comment]
Fair enough
