### ISSUE TITLE
Image pull secrets for jenkins chart

### ISSUE THREAD

**Issue by naveensrinivasan** [helm/charts#143]
The present jenkins chart does not provide an option for `imagePullSecrets:` for the master image. IMO it should be optional  where it can be provided  and chart should be able to use it for pulling the image.

**Comment by prydonius** [comment]
This seems like a fairly stringent requirement we would need to add to all the charts here.

**Comment by chrislovecnm** [comment]
Also I think it needs limits fixed

**Comment by lachie83** [comment]
Hi @naveensrinivasan and thanks for filling an issue. I think it's a valid concern and should be fairly straight forward to implement. Would you be interested in working on a PR? I would be more than happy to review.

You just need an if block that looks something like this for example -- https://github.com/kubernetes/charts/pull/151/files#diff-a75f323ecd620d8c8042dec5fadcb90dL62

**Comment by lachie83** [comment]
@chrislovecnm Happy to help with the limits concern. Can you please elaborate?

**Comment by naveensrinivasan** [comment]
@lachie83 Will do a PR for that. Thanks

**Comment by lachie83** [comment]
closing. stale. Please submit PR if you would like this functionality added to the chart
