### ISSUE TITLE
[stable/locust] Using predefined configmap

### ISSUE THREAD

**Issue by hsellik** [helm/charts#14337]
**Is your feature request related to a problem? Please describe.**
@haugene The locust.io documentation is good to follow, however, I am running into issues with configmap and it seems that there might be other people struggling as well (https://github.com/locustio/locust/issues/1012).

I am having the same issue, when I create a configmap referring to Python script as instructed, my master pod will fail, saying:
```
/usr/local/bin/locust -f /locust-tasks/locustfile.py --host=https://host.name/dev --master
[2019-05-30 15:55:46,760] helm-locust-master-6c4765bc9-xx459/ERROR/locust.main: Could not find any locustfile! Ensure file ends in '.py' and see --help for available options.
```
I suspect that  **tasks/tasks.py** in
`kubectl create configmap locust-worker-configs --from-file tasks/tasks.py`
is not right when making a configmap.

**Describe the solution you'd like**
It would be helpful if the configmap section (https://github.com/helm/charts/pull/10854) was explained a little more concise. For example, is `kubectl create configmap locust-worker-configs --from-file path/to/scripts` referring to Python scripts (the tasks.py file for example)?

**Additional context**
* I am using my own docker image which has locustfile.py under directory /locust-tasks/
* The documentation I am referring to:  
https://github.com/helm/charts/tree/master/stable/locust .
* **Docker image works locally, but not with helm**

**Comment by asher-pembroke** [comment]
I've found that if you rename your task file to `tasks.py` then it will load properly.

**Comment by hsellik** [comment]
> I've found that if you rename your task file to `tasks.py` then it will load properly.

Did you fork the repo, changed tasks.py and then deployed it? That's the way I got it to work.

What I really wanted to do is create a configmap of tasks and then deploy it without ever forking/downloading the locust chart before.
