### ISSUE TITLE
[ stable/nats] NATS routing can't works with 3 or more replicas

### ISSUE THREAD

**Issue by mivanovvs** [helm/charts#14332]
**Describe the bug**
When I tried to deploy the chart with replicas=3 I've got following configuration:
3 pods
10.233.66.6:6222 pod1
10.233.99.72:6222 pod2
10.233.94.7:6222 pod3
1 service ip
10.233.0.46:6222
As I understand each pod should be connected to two other pods. But each pod connected only to service IP and service IP is balanced to random pod. So, it looks like 
pod1 connected to pod2 and serviceIP
pod2 connected to serviceIP
pod3 connected to serviceIP

If I lost one node in cluster then I'll lost data because redundancy doesn't work as I understand.

**Version of Helm and Kubernetes**:
Helm version 2.11.0
K8S v1.12.5

**Which chart**:
stable/nats

**What happened**:
Routing in chart supports only 1 service with Cluster IP, and redundancy doesn't work.

**What you expected to happen**:
I thought each pod from replica should be connected to other pods. But in chart I see only route to serviceIP. It's working fine when you use replica=1 but it's not cluster.

**How to reproduce it** (as minimally and precisely as possible):
Deploy chart with 3 replicas. See logs in each pod.

`kubectl logs pod/nats-pod-1` 

And other. You will see only one connection to pod on port 6222.

**Comment by miguelaeh** [comment]
Hi @mivanovvs ,
I tried to reproduce it, but i can't.
I did the following:
```
helm install stable/nats --set replicaCount=3 --name my-nats
```
Logs:
```
[1] [INF] Listening for route connections on 0.0.0.0:6222
[1] [INF] 10.103.102.38:6222 - rid:1 - Route connection created
[1] [INF] 10.32.0.16:42162 - rid:2 - Route connection created
```

Is that what you expected?

**Comment by mivanovvs** [comment]
Yes, but are you sure that is ip of pods? 
`[1] [INF] 10.103.102.38:6222 - rid:1 - Route connection created
[1] [INF] 10.32.0.17:6222 - rid:2 - Route connection created`

I assume it's serviceIP and  IP from another pod.

**Comment by miguelaeh** [comment]
Okay, I checked it again.
There are 3 services. One of them is the `cluster` service, used by all pods to communicate with others. The `cluster` service uses the port `6222`.

**Comment by mivanovvs** [comment]
Okay, how about redundancy? If two pods of set down, whats will be with data?

**Comment by mivanovvs** [comment]
I mean I expected connectivity into cluster, like that
![image](https://user-images.githubusercontent.com/44364351/58710242-86ce3380-83c4-11e9-9b0e-8585848006e9.png)

**Comment by miguelaeh** [comment]
Hi @mivanovvs ,
the answer is not trivial. Nats' pods communicate their routes to each other and they reach the topology automatically. To do that, all of them use the `cluster` service.
If you want to know how kubernetes services works you can read this article: https://medium.com/google-cloud/understanding-kubernetes-networking-services-f0cb48e4cc82

**Comment by miguelaeh** [comment]
In any case, we will review the topology, thanks for your report.

**Comment by mivanovvs** [comment]
Thanks for response! But you said 

> Therefore a full mesh cluster, or complete graph, is recommended for NATS to function as intended

In which cases it's  recommended? I mean full mesh. And how to configure full mesh topology in chart?

**Comment by miguelaeh** [comment]
Hi @mivanovvs ,
The cases are not explained in the docs, I think it should be all cases. 
I understand you, the chart topology is confusing. I think there is no way to configure full mesh on the chart right now. I am going to create an internal task to review this an see if we can change it to provide full mesh.
Thank for your report.
