### ISSUE TITLE
[stable/prometheus-operator] Thanos no objectStorageConfig

### ISSUE THREAD

**Issue by MaxDiOrio** [helm/charts#14335]
Using latest releases of Prometheus-Operator and Thanos Sidecar (v0.4.0

What happened - Launched Prom Op with a Thanos Sidecar and receive the following error in the sidecar: caller=sidecar.go:123 msg="no supported bucket was configured, uploads will be disabled"

What you expected to happen. The sidecar would connect to the S3 compatible Object Storage

How to reproduce it (as minimally and precisely as possible):

Have the following in the Prometheus Operator values yaml file:

    thanos:
      baseImage: improbable/thanos
      version: v0.4.0
      peers: thanos-peers.prod.cluster:10900
      objectStorageConfig:
        key: bucket.yaml
        name: thanos-objstore-config
I have a secret name thanos-objstore-config in the same namespace with a key bucket.yaml and value:

type: S3
config:
  endpoint: "minioingress.rook-minio.10.85.166.33.xip.io"
  bucket: "thanos"
  access_key: "MINIO_Access_Key"
  secret_key: "MINIO_Secret_Key"
  insecure: true
  signature_version2: false

The actual Thanos Store container has no problems with the bucket config used to access this same bucket.

If I look at the yaml of the side car, it doesn't show the objectStorageConfig.

Doing a helm install as a dry run with debug mode on shows that it is there in all the yaml generated.

**Comment by vsliouniaev** [comment]
If I understand this correctly, are you finding that the objects have been created by helm but aren't being loaded into the prometheus pods? If this is the case, can you see if the secret is mounted into the Prometheus pod? You may find more information in the prometheus-operator logs - it should be correctly setting the pod configurations.

I'm haven't used Thanos, so it's difficult for me to say what the issue may be - you could ask on the coreos/prometheus-operator project if you feel this issue isn't specific to the method of installation (via the chart)

**Comment by simon71** [comment]
Hi @MaxDiOrio you wouldn't believe the hassle i went through getting to work. So all the other Thanos components read the storage config from a config map. The sidecar can only read this config from a secret (something i really hope changes in the future), also the secret isn't actually a secret, as it isn't a simple key,value pair it needs to be read in as a .yaml file with the correct indentation.

My situation was made even harder by the fact were using helm to deploy our k8s pods. So after trying for a few days to find a way of using helm to generate an indenteted .yaml file i gave up and my work around is:

1. create a local file called thanos.yaml

```YAML
type: S3
config:
    endpoint: "minioingress.rook-minio.10.85.166.33.xip.io"
    bucket: "thanos"
    access_key: "MINIO_Access_Key"
    secret_key: "MINIO_Secret_Key"
    insecure: true
    signature_version2: false
```
 
2. then use `$ kubectl create secret generic thanos-objstore-config --from-file=thanos.yaml=thanos-config.yaml -n <namespace>` to create the base64 encrypted secret.

4. then use `$ kubectl edit secret thanos-objstore-config -n <namespace> -o yaml` to see the encrypted yaml file
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  thanos.yaml: dHlwZTogczMKY29uZmlnOgoggrr2J1Y2tldDogbXNtLWdiLXByb21ldGhldXMxLWJsdWUKICBlbmNyeXB0c3NlOiB0cnVlCg==
kind: Secret
metadata:
  creationTimestamp: "2019-05-17T17:12:41Z"
  name: thanos-objstore-config
  namespace: default
  resourceVersion: "928656"
  selfLink: /api/v1/namespaces/default/secrets/thanos-objstore-config
  uid: fabe95c2-78c6-1fr49-9030-02f4ee719eec
type: Opaque
```

5. then create a basic helm chart using helm init with a single deployment template that uses the encrypted yaml file
```YAML
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
type: Opaque
data:
   thanos.yaml: dHlwZTogczMKY29uZmlnOgoggrr2J1Y2tldDogbXNtLWdiLXByb21ldGhldXMxLWJsdWUKICBlbmNyeXB0c3NlOiB0cnVlCg==
```

when you run helm install <chart name> it'll create the secret for you.

The one good thing i did find was that if you create the secret after deploying Prometheus-Operator the sidecar will still come up.

If you not using helm then all you need to do is the first part of creating the secret.

Anyway hope this helps.
