### ISSUE TITLE
[stable/fluent-bit] fluent-bit appends date to index

### ISSUE THREAD

**Issue by CDonoghue94** [helm/charts#14331]
**Describe the bug**
When I try and create an index using the fluent-bit helm chart it always appends a date unto my index like this:   kubernetes_cluster-2019.05.30, but I just want it to look like this:  kubernetes_cluster-1 so that I can use the index lifecycle policy which needs the index to end in a number like -1 but the date stops this from working.  This is even with me adding  logstash_format: "Off" to the config.  

`
backend:
  type: es
  forward:
    host: fluentd
    port: 24284
    tls: "off"
    tls_verify: "on"
    tls_debug: 1
    shared_key:
  es:
    host: elasticsearch-client
    port: 9200
    # Elastic Index Name
    index: kubernetes_cluster-1
    type: flb_type
    replace_dots: "On"
    logstash_format: "Off"
    # Optional username credential for Elastic X-Pack access
    http_user:
    # Password for user defined in HTTP_User
    http_passwd:
    # Optional TLS encryption to ElasticSearch instance
    tls: "off"
    tls_verify: "on"
    # TLS certificate for the Elastic (in PEM format). Use if tls=on and tls_verify=on.
    tls_ca: ""
    # TLS debugging levels = 1-4
    tls_debug: 1
  splunk:
    host: 127.0.0.1
    port: 8088
    token: ""
    send_raw: "on"
    tls: "on"
    tls_verify: "off"
    tls_debug: 1
    message_key: "kubernetes"
`

**Version of Helm and Kubernetes**:

Helm:
`Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
`
Kubernetes:
`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.10", GitCommit:"8d9b8641e72cf7c96efa61421e87f96387242ba1", GitTreeState:"clean", BuildDate:"2019-04-12T22:59:24Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
`
chart:
stable/fluent-bit

**What you expected to happen**:
To be able to create an index using fluent-bit's helm chart without a date being appended to it.

**How to reproduce it** (as minimally and precisely as possible):

Create fluent-bit chart to send logs to kibana to create and 

**Anything else we need to know**:

**Comment by Towmeykaw** [comment]
The Logstash_Format value seems to be not changeable right now. If you would like you could submit a PR. You can also make your own es output using rawConfig
