### ISSUE TITLE
[stable/prometheus-operator] [stable/prometheus-node-exporter] A node exporter pod always fails with error: Pod ... requires volume proc which is of an unsupported type

### ISSUE THREAD

**Issue by anujgeek** [helm/charts#14393]
**Describe the bug**
A node exported pod always fails with error: Pod ... requires volume proc which is of an unsupported type

**Version of Helm and Kubernetes**:
Helm version: v2.13.1
Kubernetes: v1.13.5

**Which chart**:
stable/prometheus-operator

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Using AKS virtual node enabled and RBAC enabled cluster, I inti helm usin tls. I then installed the operator using tls too. One of the node exported pod always wind up with this error, I've tried this multiple times.

Name:               gangly-pug-prometheus-node-exporter-9kfx9
Namespace:          monitoring
Priority:           0
PriorityClassName:  <none>
Node:               virtual-node-aci-linux/
Labels:             app=prometheus-node-exporter
                    chart=prometheus-node-exporter-1.4.2
                    controller-revision-hash=cbc476c95
                    heritage=Tiller
                    jobLabel=node-exporter
                    pod-template-generation=1
                    release=gangly-pug
Annotations:        <none>
Status:             Pending
**Reason:             ProviderFailed
Message:            Pod gangly-pug-prometheus-node-exporter-9kfx9 requires volume proc which is of an unsupported type**
IP:
Controlled By:      DaemonSet/gangly-pug-prometheus-node-exporter
Containers:
  node-exporter:
    Image:      quay.io/prometheus/node-exporter:v0.17.0
    Port:       9100/TCP
    Host Port:  9100/TCP
    Args:
      --path.procfs=/host/proc
      --path.sysfs=/host/sys
      --web.listen-address=0.0.0.0:9100
      --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
      --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
    Liveness:   http-get http://:9100/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:9100/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      KUBERNETES_PORT_443_TCP_ADDR:  containersampleaks3-dns-cefb8c3e.hcp.eastus.azmk8s.io
      KUBERNETES_PORT:               tcp://containersampleaks3-dns-cefb8c3e.hcp.eastus.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://containersampleaks3-dns-cefb8c3e.hcp.eastus.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       containersampleaks3-dns-cefb8c3e.hcp.eastus.azmk8s.io
    Mounts:
      /host/proc from proc (ro)
      /host/sys from sys (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from gangly-pug-prometheus-node-exporter-token-7jpcm (ro)
Conditions:
  Type           Status
  PodScheduled   True
Volumes:
  proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc
    HostPathType:
  sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:
  gangly-pug-prometheus-node-exporter-token-7jpcm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  gangly-pug-prometheus-node-exporter-token-7jpcm
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     :NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule

**Anything else we need to know**:

**Comment by vsliouniaev** [comment]
I don't have AWS to test this out, but from what I know, you should be able to disable various collectors of node_exporter that rely on getting metrics from `/proc/*` Please see here: https://github.com/prometheus/node_exporter

**Comment by anujgeek** [comment]
@vsliouniaev I was working on this setup in Azure (AKS). I've reported the same case here:
https://github.com/virtual-kubelet/virtual-kubelet/issues/673
https://github.com/Azure-Samples/virtual-node-autoscale/issues/40
Sadly, I've not been getting any replies on those as well.
