### ISSUE TITLE
[stable/mongodb] Can not enable metrics with pod security policy enabled with runAsNonRoot

### ISSUE THREAD

**Issue by waterscar** [helm/charts#14403]
**Can not install this chart with metrics enabled when PSP is set to runAsNonRoot is active**
Got an error of `Error: container has runAsNonRoot and image will run as root`

Would be nice if it's possible to set a security context of the mongo-exporter image

**Version of Helm and Kubernetes**:
helm v2.12.1
kubernetes v1.13.1

**Which chart**:
stable/mongodb

**What happened**:
Error: container has runAsNonRoot and image will run as root

**What you expected to happen**:
Being able to deploy

**How to reproduce it** (as minimally and precisely as possible):
In a kubernetes cluster that has psp enabled and a default rule to restrict root user

helm install --set metrics.enabled=true stable/mongodb

**Anything else we need to know**:

**Comment by miguelaeh** [comment]
Hi @waterscar ,
I created a pull request just now with your request:
https://github.com/helm/charts/pull/14443
