### ISSUE TITLE
[stable/jenkins] YAML parse error when overriding admin credentials

### ISSUE THREAD

**Issue by Tohaker** [helm/charts#14406]
**Describe the bug**
Whenever the adminUsername or adminPassword is provided a variable value in the style of:
```
adminPassword: |
    {{ .Values.adminPass }}
```
The following error occurs: `Error: YAML parse error on jenkins/templates/config.yaml: error converting YAML to JSON: yaml: line 58: could not find expected ':'`

**Version of Helm and Kubernetes**:
Helm: v2.14.0
Kubernetes: 
 - Kubectl: v1.14.2
 - Server: v1.12.8 (AKS)

**Which chart**:
stable/jenkins

**What happened**:
We are trying to modify the starter values YAML file to incorporate our own Password, set in another file called `secrets.yaml`. We are attempting to install through helm with the following command `helm install --name jenkins --namespace <namespace here> stable/jenkins -f values.yaml -f secrets.yaml`

When these values are hard coded, there is no problem. When we try to use Helm variables this issue occurs. It should also be noted that the line number changes sometimes - at one point it pointed to line 171. 
**What you expected to happen**:
The helm chart to deploy with our chosen variables.

**How to reproduce it** (as minimally and precisely as possible):
Open this values file: 
[values.txt](https://github.com/helm/charts/files/3247128/values.txt)
Create a secrets.yaml file with at least the variables `adminUser` and `adminPass`.
Run `helm install --name jenkins --namespace <your ns> stable/jenkins -f values.yaml -f secrets.yaml

**Anything else we need to know**:

*__This may or may not be part of the bug__*
Changing the value format to 
```
adminPassword: {{ .Values.adminPass }}
```
Gives a _different_ error `Error: failed to parse modules/aks/jenkins/values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.adminPass":interface {}(nil)}`

**Comment by torstenwalter** [comment]
Why don't you store the admin password as `adminPassword` within `secrets.yaml`?

**Comment by Tohaker** [comment]
> Why don't you store the admin password as `adminPassword` within `secrets.yaml`?
Storing it as either `adminPassword` or `master.adminPassword` has no effect, and Jenkins just randomises one.

**Comment by torstenwalter** [comment]
I put this into my secrets.yaml

```
master:
  adminPassword: demo
```

and the password was set correctly. Which version of the chart are you using? In older versions the property is named differently.

**Comment by Tohaker** [comment]
Thanks, that notation worked. I'm using the latest version of the chart so I'm aware of the naming conventions. Any idea why the inline version wouldn't have worked?

**Comment by torstenwalter** [comment]
variable notation is only supported for values rendered via the `tpl` helper. You can check which one causes the error. PRs to add templating possibilities are always welcome.

**Comment by Tohaker** [comment]
Would you be able to link to some documentation on `tpl`? I'm not sure what I'm looking for.

**Comment by torstenwalter** [comment]
https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#using-the-tpl-function

**Comment by Tohaker** [comment]
Thanks for your help, we've managed to fix the problems by formatting the `secrets.yaml` file to be in this format:
```
agent:
  respository: <some generated value>
master:
  adminUser: jenkins-admin
  adminPassword: password
```

Closing this ticket now.
