### ISSUE TITLE
[stable/chaoskube] chaoskube cannot list pods

### ISSUE THREAD

**Issue by jpds** [helm/charts#14405]
**Describe the bug**

`chaoskube` with `rbac.create=true` cannot list pods at a cluster scope:

```
level=error msg="failed to terminate victim" err="pods is forbidden: User \"system:serviceaccount:chaoskube:default\" cannot list pods at the cluster scope"
```

...rendering it useless.

**Comment by jpds** [comment]
@linki @alexvicegrab

**Comment by linki** [comment]
Thanks for the report @jpds.

It looks like when setting `rbac.create: true` the used service account should look like `{{ printf "%s-%s" .Release.Name .Values.name }}` ([see](https://github.com/helm/charts/blob/master/stable/chaoskube/templates/deployment.yaml#L76)).

The one you got configured is `default` which can only happen in the `else` branch of that if (in the latest chart version). Can you double check that you indeed correctly set `rbac.create` to `true`?

**Comment by jpds** [comment]
I had indeed used `rbac.enabled` instead of `.create` (copied from the `metrics` section).
