### ISSUE TITLE
stable/minio persistance.size

### ISSUE THREAD

**Issue by lagorsse** [helm/charts#14417]
When I enable persitant storage and setup a size different than default value it keep the old disk(storage capacity) from the previous creation even if I purge it

It doesn't happen if I change the name

Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}

How to reproduce
helm install --namespace dev --name miniotest --set mode=distributed,accessKey=toto,secretKey=tata,persistence.enabled=true,persistence.size=1Gi stable/minio
helm delete --purge miniotest
helm install --namespace dev --name miniotest --set mode=distributed,accessKey=toto,secretKey=tata,persistence.enabled=true,persistence.size=50Gi stable/minio

I am checking size using df -h
the /dev/sdi mount on /export is about the good size on the first creation but keep it's value on 2nd helm creation, if I change the name it will be ok.

**Comment by alexzimmer96** [comment]
Try deleting the persistent volume created by the persistent volume claim from this chart. 

With Automatic Volume provisioning, a pv will be created when you create a pvc. If kubernetes already has a pv with the right name/tags which is not in use, it will use the existing pv.

Just run `kubectl get pv` to get an Overview.

**Comment by lagorsse** [comment]
Yeah it was that, I also deleted associated pvc
Thanks
