### ISSUE TITLE
[stable/prisma] Support prisma 1.3x

### ISSUE THREAD

**Issue by hipstern** [helm/charts#14423]
Hello,

I would like to suggest/know if there are plans to support Prisma 1.3x.

The current chart seems to be incompatible.

Thanks,

Aviv

**Comment by hipstern** [comment]
Also, is there is a way to use the current published chart with the 1.3x image?

**Comment by haysclark** [comment]
@giacomoguiulfo These _Prisma_ issues likely should be addressed, possibly re-opened.

**Comment by giacomoguiulfo** [comment]
@hipstern Have you tried the images with the heroku suffix? Only those were intended to be supported for security reasons.
