### ISSUE TITLE
[stable/fluent-bit] extra entries and config blocks

### ISSUE THREAD

**Issue by ghost** [helm/charts#14494]
**Is your feature request related to a problem? Please describe.**
I am frustrated with the extraEntries configuration. I have seen several merges and reverts to change the indentation from 8 to 4. I understand that the intent was to allow additional key/value pairs for existing [INPUT], [OUTPUT], [FILTER] blocks. The problem is that not all blocks are accessible from extraEntries, only the last block is accessible.

Furthermore, adding additional filters is a pain since I actually need to modify the chart to add additional files to the configmap. There is no way to add additional filters by just modifying the values.

**Describe the solution you'd like**
Others have tried repurposing the extraEntries to add additional blocks by modifying the indentation of extraEntries from 8 to 4, but it has been reverted twice.

My proposal would be to add extraEntries for all existing blocks in the configmap instead of just the last block, and also add a new value for adding additional blocks to each config section.

For example,
```yaml
  fluent-bit-input.conf: |-
    [INPUT]
        Name tail
        ...
{{ .Values.extraEntries.input.tail | indent 8 }}
    [INPUT]
        Name systemd
        ...
{{ .Values.extraEntries.input.systemd | indent 8 }}
{{ .Values.extraInputs | indent 4 }}
```

**Comment by ntroast** [comment]
@kfox1111 ^

**Comment by Towmeykaw** [comment]
We have talked a lot about this issue and right now the consensus is if you want to a single value you use extraEntries and for more you use rawConfig. Not sure why you can't use rawConfig for adding additional filters? You can basically add whatever you want.

**Comment by ntroast** [comment]
@Towmeykaw could you please provide an example of how I can add an additional filter only by customizing values.yaml? Furthermore, could you provide an example of how to add an additional key/value pair to this existing input tail config?https://github.com/helm/charts/blob/0232f250401fb4c0db0c7d8811b7246e9323e759/stable/fluent-bit/templates/config.yaml#L28

**Comment by samjsong** [comment]
+1. As an example, I'd like to increase `rotate_wait` for the `in_tail` plugin, while also using `in_systemd`, but I don't believe that's possible without copying over the `systemd` config into my `rawConfig`.

**Comment by Towmeykaw** [comment]
That was kind of the point of rawConfig. If we are going to support every possible config then it will be unmaintainable.  I can't show an example right now since I'm on my phone but basically you can add how many config sections you want to the rawConfig.

**Comment by frankreno** [comment]
The problem with RawConfig is it requires user to now maintain a seperate copy of the configuration which is overkill in situations where you have one property that is not exposed that you want to add but only applies to a specific plugin.

**Comment by frankreno** [comment]
@Towmeykaw - thoughts on the above PR?

**Comment by vsinghal13** [comment]
@Towmeykaw thoughts on the above PR?
