### ISSUE TITLE
sonarqube chart issue title

### ISSUE THREAD

**Issue by danseo-reisys** [helm/charts#14497]
sonarqube has issue on OKD and OCP v3.11. 
The main issue is the underlying DB, either mysql or postgresql, does not start. 
in case of mysql, i get the following error.
error: failed switching to "mysql": operation not permitted

in case of postgresql, ige the following error. 
same error. error: failed switching to "postgres": operation not permitted

sonarq pod errors out because the DB is not responding.  

do you have any suggestion?
i am able to helm install wordpress with mariadb fine.  so the tiller seems to be working fine.

**Comment by yaxinlx** [comment]
Same problem. Openshift 3.11. mariadb/server:10.4

Anyone has a solution?

**Comment by yaxinlx** [comment]
Related issue: https://github.com/fabric8io/kubernetes-zipkin/issues/97
