### ISSUE TITLE
[stable/postgresql] Readiness probe "improvements" incompatible with non-default image 

### ISSUE THREAD

**Issue by SterlingMcCall** [helm/charts#14495]
**Describe the bug**
[This recent change](https://github.com/helm/charts/pull/14370) to the readiness probe assumes that the default Bitnami postgresql image is being used. However, the chart supports overriding the image and the [documentation even has an example](https://github.com/helm/charts/tree/master/stable/postgresql#user-content-deploy-chart-using-docker-official-postgresql-image) doing just that. For my use case I am using a custom image which does not have the file `/opt/bitnami/postgresql/tmp/.initialized` that the readiness probe now checks. As a result, my pod never becomes ready.

**Version of Helm and Kubernetes**:
Irrelevant

**Which chart**:
stable/postgresql version 5.2.3

**What happened**:
Recent readiness probe changes are not compatible with non-bitnami images.

**What you expected to happen**:
I would expect that documented supported features (using different images) aren't broken by changes to the readiness probe.

**How to reproduce it** (as minimally and precisely as possible):
Override the default bitnami image with an image that does not create the  `/opt/bitnami/postgresql/tmp/.initialized` file.

**Anything else we need to know**:
My current work-around is to use version 5.2.2 of the chart.

**Comment by tompizmor** [comment]
Hi @SterlingMcCall,

Thanks for reporting the issue. I was able to reproduce it and I am working on a fix.

**Comment by tompizmor** [comment]
@SterlingMcCall The fix is already merged

**Comment by SterlingMcCall** [comment]
@tompizmor Thank you for the quick fix! I appreciate it.
