### ISSUE TITLE
stable/sonarqube crash loop

### ISSUE THREAD

**Issue by emcay** [helm/charts#14507]
**Describe the bug**

-After performing the helm install the Sonarqube container enters a CrashLoopBackOff state in a minikube cluster.

**Version of Helm and Kubernetes**:
-helm 2.13.1
-kubectl 1.14.2
-minikube v1.1.0

**Which chart**:
-stable/sonarqube

**What happened**:
-Install completes without error, Sonarqube container enters a CrashLoopBackOff state.
 
-kubectl logs <podname> returning:

`./bin/run.sh: line 24: exec: java: not found
`

**What you expected to happen**:
-Sonarqube container to enter a "running state".

**How to reproduce it** (as minimally and precisely as possible):
-Not doing anything special here, just helm install stable/sonarqube 

**Anything else we need to know**:
-I am assuming the issue is with helm, since I can pull the Sonarqube docker image and it doesn't appear to have the same issue when ran without the chart:

```
sonarqube$ echo $JAVA_HOME
/usr/local/openjdk-8

```

**Comment by carlosjsanch3z** [comment]
Hi,

I have the same problem here, stack:

Helm: v2.13.1
Kubernetes (GKE): 1.11.8-gke.6
Kubectl: v1.14.1

```
kubectl logs sonarqube-sonarqube-5cf99d8c5-tbjwn -p
./bin/run.sh: line 24: exec: java: not found
```

The last time I displayed the sonarqube chart and **it worked was on May 22nd**. If it was helpful.

**Comment by frank-carnovale** [comment]
Got here with same bug.  Seems that in the underlying image, the environment var PATH is prepended with /usr/local/openjdk-8/bin..   (which looks like a workaround to compensate for an incomplete java install that didn't set up 'alternatives' properly..).  Yet In the k8s deployment, /usr/local is re-mounted for no other reason than to home the 'copy_plugins.sh' script which is delivered via a configMap.  Hence the java install has been effectively hidden from view.   How does this chart get classed as 'stable'?

**Comment by emcay** [comment]
I was able to get a working setup using the 7.6-community image in the values file. More recent images don't appear to work with the current helm chart still.

**Comment by 99** [comment]
Experiencing the same issue.

**Comment by smoyer64** [comment]
Same problem for both 7.7 and 7.8 ... but we had been running 7.7-community for a month and when the cluster restarted the pod, it failed.  I'm assuming that indicates a problem with the underlying docker image (which did change underneath the Helm chart).

**Comment by pauloeliasjr** [comment]
Tested today against 7.8 and 7.9: same issue

**Comment by smoyer64** [comment]
Here's some further activity ... this was still a problem last time we checked.

**Comment by smoyer64** [comment]
Still a problem for us

**Comment by smoyer64** [comment]
I'll check our most recent installation

**Comment by kav** [comment]
WHat is the result of kubectl describe on the sonarqube pod? I think I might be seeing the same issue and it looks like the healthcheck is wrong. Happy to investigate more if folks are seeing similar issues:
`  Warning  Unhealthy  9m7s  kubelet, docker-desktop  Liveness probe failed: Get http://10.1.8.189:9000/sessions/new: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
`

**Comment by tirelibirefe** [comment]
it's 2021, the same problem exists.
