### ISSUE TITLE
[stable/redis] Cannot add custom configuration via values.yaml in HA

### ISSUE THREAD

**Issue by 27Bslash6** [helm/charts#14515]
As per:
https://github.com/helm/charts/issues/7770#issuecomment-453014728

**Describe the bug**
Cannot add custom configuration via values.yaml when this chart is deployed HA

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
stable/redis

**Anything else we need to know**:

> The image used on this chart, uses the redis.conf mounted and skips the rest of configuration (replicacion included) when it detects it, check the logic below:
> 
> https://github.com/bitnami/bitnami-docker-redis/blob/master/5.0/debian-9/rootfs/libredis.sh#L311
> 
> Therefore, when using a custom configuration file, there's no way to configure master/slave configuration with the current approach.
>

**Comment by juan131** [comment]
Hi @27Bslash6 

Thanks for opening the issue. As we mentioned at #7770 it's a known issue and we have an internal task in our backlog to work on that.

We'll notify you once we find time to address it.

**Comment by sameersbn** [comment]
@27Bslash6 can you please take a look at https://github.com/helm/charts/pull/15343 and let us know if ir works for you?
