### ISSUE TITLE
[stable/postgresql] On pod restart, data directory has invalid permissions

### ISSUE THREAD

**Issue by aerotog** [helm/charts#14538]
**Describe the bug**
When restarting the postgres pods, the pods fail to enter a ready state. The logs show a permission error for the data directory:
> FATAL:  data directory "/bitnami/postgresql/data" has invalid permissions
> DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750)

**Which chart:**
stable/postgresql v5.2.3

**Version of Helm and Kubernetes:**
Kubernetes: v1.10.11
Helm: v2.11.0

**Describe the results you received:**
Pods fail to ready with FATAL error in logs.

**Describe the results you expected:**
Pod can restart without FATAL error.

**Additional information you deem important (e.g. issue happens only occasionally):**
I've taken a look at the init container 'init-chmod-data' and have confirmed the /data directory on my instance has mode '760'. This is b/c the latest init container only tries to create a new directory and does not chmod for an existing directory.

This seems to be related to changes from [this commit](https://github.com/helm/charts/commit/cdc331a5050ffbe33517faddaaa20fe167149213). I have a fix that I am testing locally. I plan to open a PR soon.

**Comment by carrodher** [comment]
Thanks for the fix! I just accepted the PR
