### ISSUE TITLE
sha1sum causing error in redis-ha chart

### ISSUE THREAD

**Issue by step42** [helm/charts#14547]
I am trying to install the redis-ha chart but it fails due to sha1sum 

>helm install redis-ha -f my-values.yaml -n redis --dry-run --debug

Error: parse error in "redis-ha/templates/redis-ha-statefulset.yaml": template: redis-ha/templates/redis-ha-statefulset.yaml:76: function "sha1sum" not defined

Here is the version of helm I am using
>helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

This is the content of my-values.yaml
auth: true
redisPassword: redis
redisPassword: red

I also tried to patch edis-ha-statefulset.yaml and replace sha1sum with sha256sum.
It gets me past the error and installs the pods but sentinel is not happy and crashes due to a wrong sentinel Id
>> Malformed Sentinel id in myid option

These are the sentinel ids that have been generated using sha256sum
        - name: SENTINEL_ID_0
          value: 7b2354840b1d1c4b055f3ff2d88933097247eab57fc1bef2ec1fb34cfb927be7

        - name: SENTINEL_ID_1
          value: d83719584cc91cb44e81ad12a372bb73f5a9a2fcfb1d708a5172376c216725e3

        - name: SENTINEL_ID_2
          value: 24df1ba489f8a5c2e81dd42666ec620592abf55fa3082b7e35f02b7335f20095

I know this is caused by using sha256sum instead of sha1sum. When I make the hashs shorter and hard code them in the template the pods come up but I would prefer a better fix. 
Has anyone else seen this? Is there a better fix?

Thanks
Step

**Comment by praveen056** [comment]
how you have installed redis-ha with  the modified chart or file of redis-ha downloaded locally . ?

**Comment by step42** [comment]
I downloaded the files locally and made the changes in order to install redis-ha. The unmodified version did not work for me.
