### ISSUE TITLE
[stable/memcached] despite Readme, cannot actually be installed as a Deployment

### ISSUE THREAD

**Issue by Fingel** [helm/charts#14544]
**Describe the bug**
The README.md for the memcached chart describes a configuration option, `kind` which defaults to `StatefulSet`, but it is description also says it can be set to `Deployment`. However, the value can only actually be `StatefulSet`, and if its set to `Deployment`, the chart fails to deploy. This is due to the `serviceName` attribute being invalid for the `Deployment` kind.

**Version of Helm and Kubernetes**:
Helm: 2.14.0
Kubernetes: 1.12

**Which chart**:
[memcached](https://github.com/helm/charts/tree/master/stable/memcached)

**What happened**:
When the value of `kind` is set to Deployment, the chart fails to deploy:

```
$ helm upgrade --install my-memcached-test stable/memcached --set kind=Deployment --debug --dry-run
[debug] Created tunnel using local port: '32985'

[debug] SERVER: "127.0.0.1:32985"

[debug] Fetched stable/memcached to /home/isnyder/.helm/cache/archive/memcached-2.8.2.tgz

Release "my-memcached-test" does not exist. Installing it now.
[debug] CHART PATH: /home/isnyder/.helm/cache/archive/memcached-2.8.2.tgz

Error: error validating "": error validating data: ValidationError(Deployment.spec): unknown field "serviceName" in io.k8s.api.apps.v1beta1.DeploymentSpec
```

**What you expected to happen**:
Either the deploy succeeds as a Deployment kind or the chart does not accept a `kind` configuration variable (and the documentation is updated accordingly).

**How to reproduce it** (as minimally and precisely as possible):
```
$ helm upgrade --install my-memcached-test stable/memcached --set kind=Deployment --debug --dry-run
```

And see that it fails.

**Comment by SteveEasley** [comment]
I ran into the inability to use as a kind deployment today as well, although oddly my error was `deployment in version "v1beta1" cannot be handled as a Deployment: no kind "deployment" is registered for version "apps/v1beta1"`.
