### ISSUE TITLE
[stable/concourse] postgres refusing connection from web node

### ISSUE THREAD

**Issue by anthonyvetter** [helm/charts#14579]
**Describe the bug**
On a new, local Kubernetes cluster. Running `helm install stable/concourse`. The web node goes into CrashLoopBackOff status. The Postgres node never leaves "pending" status.

```
kubectl get pods
NAME                                       READY     STATUS             RESTARTS   AGE
invited-mouse-postgresql-b478fcfdb-8vctk   0/1       Pending            0          12m
invited-mouse-web-698b6c5d8b-x8wnw         0/1       CrashLoopBackOff   7          12m
invited-mouse-worker-0                     0/1       Pending            0          12m
invited-mouse-worker-1                     0/1       Pending            0          12m
```

looking at the logs

```
kubectl logs invited-mouse-web-698b6c5d8b-x8wnw
{"timestamp":"2019-06-07T00:16:06.791608566Z","level":"info","source":"atc","message":"atc.cmd.start","data":{"session":"1"}}
{"timestamp":"2019-06-07T00:16:07.809906268Z","level":"error","source":"atc","message":"atc.db.failed-to-open-db-retrying","data":{"error":"dial tcp 10.98.132.40:5432: connect: connection refused","session":"3"}}
      duration:
{"timestamp":"2019-06-07T00:16:13.825870745Z","level":"error","source":"atc","message":"atc.db.failed-to-open-db-retrying","data":{"error":"dial tcp 10.98.132.40:5432: connect: connection refused","session":"3"}}
```

**Version of Helm and Kubernetes**:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

**Which chart**:
stable/concourse

**What happened**:
The web node crashes and Postgres node never comes up

**What you expected to happen**:
the web node to start and become ready, along with the rest of the nodes

**How to reproduce it** (as minimally and precisely as possible):
On a fresh, local k8s cluster (I essentially used this guide: https://vitux.com/install-and-deploy-kubernetes-on-ubuntu/). Use Helm for Mac and init Tiller. then helm install stable/concourse

**Anything else we need to know**:
Probably. I have not submitted many bug reports so let me know if I can answer additional questions. TIA!

**Comment by anthonyvetter** [comment]
I figured it out. Needs a StorageClass. Feel dumb. Thanks!

**Comment by gowrisankar22** [comment]
@anthonyvetter  I am also encountering the same issue. BTW I am trying to set up using minikube. 
How to fix this issue?

**Comment by anthonyvetter** [comment]
For me I was using a bare metal cluster with upstream k8s which doesn’t include a default storage class. I had to add it. I think Minikube includes a PV for local storage but I would start there. If Postgres isn’t starting it’s probably because it doesn’t have access to any PVC. Look into that. Also check out the values.yml and modify to point Postgres in the right direction.

**Comment by YoussB** [comment]
I think it would be nice if the chart README explicitly mentions the need for having a default `StorageClass`

wdyt @anthonyvetter ?
