### ISSUE TITLE
[elasticsearch stable/chart] restore snapshot

### ISSUE THREAD

**Issue by vasayn** [helm/charts#14588]
hi everyone 

how i can do restore\snapshots datas from my elasticsearch single mode on my PC to kubernetes cluster elasticsearch data\master pods. 

in official docs (https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_shared_file_system_repository) i need to have single sharing fs between all master\data pods, but standart helm charts (https://github.com/helm/charts/tree/master/incubator/elasticsearch) haven't possibility to choose sharing folder with snapshots

**Comment by Towmeykaw** [comment]
Im not sure if this will answer your question but the official elasticsearch chart has a guide on how to migrate to helm from a snapshot. The stable/elasticsearch chart will be depricated in favor of the official one in the future so might be worth migrating there.
https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/migration/README.md
