### ISSUE TITLE
[stable/metrics-server] Command arguments shouldn't be quoted

### ISSUE THREAD

**Issue by sungmincs** [helm/charts#14608]
**Describe the bug**
Currently metrics-server chart is quoting all the command line arguments by default and this ends up failing the deployment

https://github.com/helm/charts/blob/master/stable/metrics-server/templates/metrics-server-deployment.yaml#L51

```
          command:
            - /metrics-server
            - --cert-dir=/tmp
            - --logtostderr
            - --secure-port=8443
            - "--kubelet-insecure-tls"
```
Please note the quotes around `--kubelet-insecure-tls` flag
Given the `args` flag is meant for command argument, it shouldn't quote the list of `args` values.

**Version of Helm and Kubernetes**:
Kubernetes: v1.14.1
Helm: v2.12.1

**Which chart**:
stable/metrics-server

**What happened**:
Metrics-server helm install with extra command argument doesn't work due to the quotes.

**What you expected to happen**:
Extra command argument shouldn't be quoted

**How to reproduce it** (as minimally and precisely as possible):
try run the helm command either with value file,
```
args:
  - --kubelet-insecure-tls
```
or pass it as a flag
```
$ helm install stable/metrics-server \
...
--set args[0]=--kubelet-insecure-tls
```
and observe the compute value that command argument is quoted.

**Anything else we need to know**:

**Comment by dmxlsj** [comment]
Can anyone take a look at this issue? or I can create a PR

**Comment by dyresen** [comment]
This still seems to be a problem. All args are piped into quote, which makes it fail. Did you send a pull request @dmxlsj or find a workaround?

**Comment by dmxlsj** [comment]
I didn't file a PR because I was hoping someone would explain why it needs to be quoted, but for sure I can file PR unless there is any valid reason.

as a workaround you just need to remove `| quote` part from this deployment template.
https://github.com/helm/charts/blob/master/stable/metrics-server/templates/metrics-server-deployment.yaml#L51
