### ISSUE TITLE
[stable/postgresql] lost+found directory causes init pod failure

### ISSUE THREAD

**Issue by ljohnston** [helm/charts#14602]
**Describe the bug**
An existing "lost+found" directory can cause the "init-chmod-data" init container to fail with the following error message from its logs:

`chown: changing ownership of '/bitnami/postgresql/lost+found': Operation not permitted`

**Version of Helm and Kubernetes**:  Helm 2.13.1, Kubernetes 1.14.1

**Which chart**: stable/postgresql 5.3.4

**What happened**: 
Helm deployment failed pod initialization.

**What you expected to happen**:
Helm deployment to succeed.

**How to reproduce it** (as minimally and precisely as possible):
Do a 5.3.4 chart deployment to a mounted filesystem that has a "lost+found" directory.

This was not a problem with the 4.x versions of the chart. Only after upgrading to 5.3.4 did this start to occur (I didn't test any older 5.x versions). After encountering the error, I did look into the 4.x deployments, however, and see the same `chown: ... Operation not permitted` error in the logs, though the pod initializes correctly. It seems the difference is that the 4.x init container runs additional commands that do succeed _after_ running the `find ... |xargs chown ...` command. As those additional commands succeed, the "init-chmod-data" pod reports a 0 exit status and initialization succeeds.

Seems this could be resolved by changing the `find` command in the init container to include a test for the "lost+found" directory:
```
find {{ .Values.persistence.mountPath }} -mindepth 1 -maxdepth 1 -not -name ".snapshot" -a -not -name "lost+found" | \
  xargs chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }}
```

**Comment by alemorcuq** [comment]
Hi, @ljohnston.

Thank your for reporting this issue. Would you mind submitting a PR to fix this?

Regards,
Alejandro
