### ISSUE TITLE
[stable/grafana] Default config options not applied in templates

### ISSUE THREAD

**Issue by patricklucas** [helm/charts#1461]
In the grafana chart, two entries in values.yaml, `server.setDatasource.image` and `server.setDatasource.restartPolicy` are documented with defaults, but these defaults are not actually applied in the templates causing confusing errors like:

    Error: failed to create resource: Job.batch "grafana-grafana-set-datasource" is invalid: [spec.template.spec.containers[0].image: Required value, spec.template.spec.restartPolicy: Unsupported value: "Always": supported values: OnFailure, Never]

**Comment by patricklucas** [comment]
I believe this also applies to the templated JSON in the args to curl in `job.yaml`.

**Comment by fhemberger** [comment]
Related: #1458

**Comment by patricklucas** [comment]
Hmm is this related? I ran into the other issue as well, but in this case there is a documented default (that is commented out) in `values.yaml` but in the template it is referenced with `{{ Values.some.var }}` instead of e.g. `{{ default "some default value" Values.some.var }}`.

**Comment by fiunchinho** [comment]
Which image should be used for `server.setDatasource.image` ?
