### ISSUE TITLE
stable/sentry Client Keys DSN field empty

### ISSUE THREAD

**Issue by marcingorzynski77** [helm/charts#14613]
**Describe the bug**

**Version of Helm and Kubernetes**:
Helm 2.13.1, 1.13.1 kubernetes

**Which chart**:
Sentry

**What happened**:
After installation which seems to be successful Client DSN key is always empty for every project. I am not sure if this is a helm chart issue or some other but I am unable to find enough info to categorise it properly

**What you expected to happen**
Client DSN key to be populated for a new project

**How to reproduce it** (as minimally and precisely as possible):
Just install with default settings and go to a new project settings Client DSN Keys , DSN field is empty

**Anything else we need to know**:
Nope

**Comment by marcingorzynski77** [comment]
figure it out but we could improve the documentation, basically I have changed url from my ingress one to loadbalancer ip + exposed port in Root URL

**Comment by AviNitSri** [comment]
I have installed sentry and used my own ingress.
The sentry application is working were DSN: https://<public key>@<base url>/<project id>
But the DSN field is still empty. how to automatically populate the DSN field with correct DSN
