### ISSUE TITLE
stable/mongodb fixing permission issue via initContainer

### ISSUE THREAD

**Issue by rohits-dev** [helm/charts#14670]
**Is your feature request related to a problem? Please describe.**
While using stable/mongodb chart, with bitnami mongodb docker image, there is a issue of permission on the data dir. which can be solved by adding a init container which fixes the permission as suggested here. https://github.com/bitnami/bitnami-docker-mongodb/issues/103#issuecomment-494105869
There should be a way without changing the chart we can set init container which is possible that is passing extrainitContainer values. However while passing a extraInitContainer, it also get applies to arbiter and arbiter doesn't have the datadir volume mounted and that crashes the init container and you can't have a successful arbiter. 

**Describe the solution you'd like**
may be an extra variable for primary and secondary replicaset or something else so that we can define init containers specifically for each pod. 

**Describe alternatives you've considered**
As of now I am using updating this chart and putting it in my local repo.

**Additional context**
None

**Comment by javsalgar** [comment]
Hi,

We have something similar in stable/postgresql, so it could be interesting taking a look. Could you explain a bit more the platform you are using for deploying the chart?
