### ISSUE TITLE
[stable/nginx-ingress] NodePort http/https not working

### ISSUE THREAD

**Issue by jforman** [helm/charts#14681]
I am wishing to run nginx-ingress on my home-grown Kubernetes cluster (Ubuntu VM's running via libvirt/kvm on Ubuntu host) listening on ports 30080 and 30443 for http/https respectively on my controller-nodes. Specifying the below helm command line along with values.yaml, the log for the controllers still claim it is trying to listen on port 80.

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```
from 'kubectl version':
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
stable/nginx-ingress

with `values.yaml`:
```
controller:
  replicaCount: 2
  minAvailable: 2
  tolerations:
  - key: "key"
    operator: "Equal"
    value: "value"
    effect: "NoSchedule"
  nodeSelector:
    role: controller
  stats:
    enabled: true
  podSecurityPolicy:
    enabled: True
  service:
    type: "NodePort"
    nodePorts:
      http: 30080
      https: 30443
```

**What happened**:
```
W0611 00:51:47.973409       5 queue.go:130] requeuing initial-sync, err 
-------------------------------------------------------------------------------
Error: exit status 1
2019/06/11 00:51:47 [notice] 33#33: ModSecurity-nginx v1.0.0
nginx: the configuration file /tmp/nginx-cfg608773841 syntax is ok
2019/06/11 00:51:47 [emerg] 33#33: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: configuration file /tmp/nginx-cfg608773841 test failed

-------------------------------------------------------------------------------
W0611 00:51:50.405483       5 queue.go:130] requeuing default/nginx-ingress-release-controller, err 
-------------------------------------------------------------------------------
Error: exit status 1
2019/06/11 00:51:50 [notice] 41#41: ModSecurity-nginx v1.0.0
nginx: the configuration file /tmp/nginx-cfg785766829 syntax is ok
2019/06/11 00:51:50 [emerg] 41#41: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: configuration file /tmp/nginx-cfg785766829 test failed
------------------------------------------------------------------------------
```

**What you expected to happen**:
Ports 30080 and 30443 would begin listening on those controller hosts pointing to my nginx ingress controller.

**How to reproduce it** (as minimally and precisely as possible):
```
helm --kubeconfig /nas1/git/kubernetes/configs/prod/admin/admin.kubeconfig install stable/nginx-ingress --name nginx-ingress-release -f /nas1/git/kubernetes/configs/helm/nginx-ingress/values.yaml
```

See above for contents of values.yaml

**Anything else we need to know**:

**Comment by Aisuko** [comment]
If you don't need `pod security policy` to manage the container's security. You should set that's false. Or, you should override the `podsecuritypolicy.yaml`

**Comment by jforman** [comment]
@Aisuko What in the podsecuritypolicy.yaml would I change? I am running k8s 1.14.2 with PSP enabled, but looking at that YAML all seems correct (the nginx ingress pod is running as UID 33, not root), and the ports i'm trying to bind (30080 and 30443) are within the 1-65535 range. 

Are there other logs I could look at to determine if this is indeed a PSP problem?

**Comment by jforman** [comment]
I believe I've started to figure it out.

I believe it has to do with AppArmor in kubernetes 1.14.

I notices two different lists of annotations on two nginx-ingress controller pods on different clusters I have:

k8s 1.12 (nginx-ingress-controller 0.22.0):
Annotations:        <none>

k8s 1.14 (nginx-ingress-controller 0.24.1):
Annotations:        container.apparmor.security.beta.kubernetes.io/nginx-ingress-controller: runtime/default
                    kubernetes.io/psp: 999-privileged
                    seccomp.security.alpha.kubernetes.io/pod: docker/default


By setting:
controller:
  podAnnotations:
    container.apparmor.security.beta.kubernetes.io/nginx-ingress-controller: unconfined

in my values.yaml, the pods start up!

I still want to see if I can find some logs on the host machine complaining about the AppArmor violations.

**Comment by jforman** [comment]
Actually the pod starts up, but then gets killed by the PSP. Time to go back to using AppArmor but getting the PSP correctly configured for this service account to be able to use it.

**Comment by jforman** [comment]
@Aisuko Is there any reason why the podsecuritypolicy.yaml is not being populated and applied? When I perform a 'kubectl get psp', the PSP provided by the nginx-ingress chart is not present.

**Comment by Aisuko** [comment]
@jforman Please check your value.yaml about

https://github.com/helm/charts/blob/4527ebe8a36180ddd16973acddf476abe7264cfe/stable/nginx-ingress/values.yaml#L384
 
The default was `false` turn to 'true'

**Comment by Aisuko** [comment]
> I am wishing to run nginx-ingress on my home-grown Kubernetes cluster (Ubuntu VM's running via libvirt/kvm on Ubuntu host) listening on ports 30080 and 30443 for http/https respectively on my controller-nodes. Specifying the below helm command line along with values.yaml, the log for the controllers still claim it is trying to listen on port 80.
> 
> **Version of Helm and Kubernetes**:
> 
> ```
> Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
> ```
> 
> from 'kubectl version':
> 
> ```
> Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> **Which chart**:
> stable/nginx-ingress
> 
> with `values.yaml`:
> 
> ```
> controller:
>   replicaCount: 2
>   minAvailable: 2
>   tolerations:
>   - key: "key"
>     operator: "Equal"
>     value: "value"
>     effect: "NoSchedule"
>   nodeSelector:
>     role: controller
>   stats:
>     enabled: true
>   podSecurityPolicy:
>     enabled: True
>   service:
>     type: "NodePort"
>     nodePorts:
>       http: 30080
>       https: 30443
> ```
> 
> **What happened**:
> 
> ```
> W0611 00:51:47.973409       5 queue.go:130] requeuing initial-sync, err 
> -------------------------------------------------------------------------------
> Error: exit status 1
> 2019/06/11 00:51:47 [notice] 33#33: ModSecurity-nginx v1.0.0
> nginx: the configuration file /tmp/nginx-cfg608773841 syntax is ok
> 2019/06/11 00:51:47 [emerg] 33#33: bind() to 0.0.0.0:80 failed (13: Permission denied)
> nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
> nginx: configuration file /tmp/nginx-cfg608773841 test failed
> 
> -------------------------------------------------------------------------------
> W0611 00:51:50.405483       5 queue.go:130] requeuing default/nginx-ingress-release-controller, err 
> -------------------------------------------------------------------------------
> Error: exit status 1
> 2019/06/11 00:51:50 [notice] 41#41: ModSecurity-nginx v1.0.0
> nginx: the configuration file /tmp/nginx-cfg785766829 syntax is ok
> 2019/06/11 00:51:50 [emerg] 41#41: bind() to 0.0.0.0:80 failed (13: Permission denied)
> nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
> nginx: configuration file /tmp/nginx-cfg785766829 test failed
> ------------------------------------------------------------------------------
> ```
> 
> **What you expected to happen**:
> Ports 30080 and 30443 would begin listening on those controller hosts pointing to my nginx ingress controller.
> 
> **How to reproduce it** (as minimally and precisely as possible):
> 
> ```
> helm --kubeconfig /nas1/git/kubernetes/configs/prod/admin/admin.kubeconfig install stable/nginx-ingress --name nginx-ingress-release -f /nas1/git/kubernetes/configs/helm/nginx-ingress/values.yaml
> ```
> 
> See above for contents of values.yaml
> 
> **Anything else we need to know**:

```
controller:
  replicaCount: 2
  minAvailable: 2
  tolerations:
  - key: "key"
    operator: "Equal"
    value: "value"
    effect: "NoSchedule"
  nodeSelector:
    role: controller
  stats:
    enabled: true
 podSecurityPolicy:
    enabled: True
  service:
    type: "NodePort"
    nodePorts:
      http: 30080
      https: 30443
```
Is your `podsecuritypolicy.yaml` have been change for `Values.controller.podSecurityPolicy.enabled`

https://github.com/helm/charts/blob/120415f9ef44fda52d4b1da3e1a3fa38bfcfc2ea/stable/nginx-ingress/templates/podsecuritypolicy.yaml#L1
