### ISSUE TITLE
Please, add @darioblanco as Trusted Collaborator

### ISSUE THREAD

**Issue by darioblanco** [helm/charts#14682]
I would like to be added as a trusted collaborator. We use Helm charts in my company in all our infrastructure, I would like to make more contributions and I am already maintainer of `stable/hubot` and `incubator/buzzfeed-sso`. 

Especially with `buzzfeed-sso`, we get a lot of contributions that require an `/ok-to-test`, and I think I can take care of those without bothering other trusted collaborators.

Thank you!

**Comment by komljen** [comment]
@darioblanco I added `/ok-to-test` on a few `buzzfeed-sso` PRs to unblock them until this gets resolved. I'm also `buzzfeed-sso` user, so I can help you to maintain it.

**Comment by darioblanco** [comment]
Thank you @komljen !!!!

**Comment by maorfr** [comment]
added you! please add an OWNERS file to hubot :)
