### ISSUE TITLE
[stable/openvpn] helm install failure when keystoreSecret was specified

### ISSUE THREAD

**Issue by bigpigeon** [helm/charts#14695]
**Describe the bug**

**Version of Helm and Kubernetes**:

helm version: v2.13.1

kubernetes version: v1.14.2

**Which chart**:

stable/openvpn

**What happened**:

I want to use helm install -f values.yaml stable/openvpn

but the pod start failure

when I get log has following error

```
$ kubectl -n kube-system log rafting-jellyfish-openvpn-cb6cc87cb-vml2w
found existing certs - reusing
Options error: --crl-verify fails with '/etc/openvpn/certs/crl.pem': No such file or directory
Options error: Please correct these errors.
Use --help for more information.
```

**What you expected to happen**:

if I remove keystoreSecret it work well

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I use below command to create k8s secret that use for keystoreSecret
`kubectl create secret generic openvpn-keystore-secret --from-file=./server.key --from-file=./ca.crt --from-file=./server.crt --from-file=./dh.pem`

**Comment by irozet** [comment]
Error happens because crl.pem is added to config in the following commit:

https://github.com/helm/charts/commit/100d5a156b00d06214bff8eba8b259cce2daa63c#diff-426bf77ebc46805831ad90724aa62549

**Comment by jasongwartz** [comment]
@bigpigeon can you check if this is fixed by https://github.com/helm/charts/pull/14777 ? Cheers
