### ISSUE TITLE
[stable/mssql-linux] Run SQL queries during the bootup in "mssql-linux" chart

### ISSUE THREAD

**Issue by ctienshi** [helm/charts#14690]
**Is your feature request related to a problem? Please describe.**
MySQL and Postgres has the option to run SQL queries during the bootup using initializationFiles (MySQL) and configurationConfigMap (Postgres). The Helm chart for **mssql-linux** does not have this option.

**Describe the solution you'd like**
Allow users to run SQL queries during the bootup using a config map in the values.yaml for mssql-linux chart.

**Comment by chirangaalwis** [comment]
@ctienshi +1 for this feature. It is a basic use case of any DBMS based Helm Chart, AFAIU.

**Comment by VimukthiPerera** [comment]
It would be great if this feature can be added.

**Comment by juan131** [comment]
Hi @VimukthiPerera 

I'm afraid I'm not one of the maintainers of the `mssql-linux` chart. 

Please also update the title of the issue so it states `[stable/mssql-linux]` so the maintainers of the chart can easily identify it.

**Comment by VimukthiPerera** [comment]
Thanks @juan131. Changed the title.

**Comment by chirangaalwis** [comment]
@thomasliddledba we still cannot see the discussed feature in the MSSQL Helm chart.

This is an essential feature when it comes to Helm based deployments of database servers. Is this part of the future road map for this official chart?

**Comment by thomasliddledba** [comment]
@chirangaalwis - Thanks for pointing this out.  I believe because of the title not being correct and issue not assigned to me, I never saw this feature request.  Wow, this is old (based on the opened date).

I agree, this would be a great feature and something that can be added, however, with the [changes to this repository](https://github.com/helm/charts#deprecation-timeline) I hope to get it in.

**Comment by chirangaalwis** [comment]
@thomasliddledba thanks a bunch. This https://github.com/helm/charts/issues/19694 seems like a similar issue, too.

**Comment by chirangaalwis** [comment]
@thomasliddledba any update on this? Is it possible to let us know when this feature would be available?
