### ISSUE TITLE
[stable/spinnaker] unable to install stable/spinnaker

### ISSUE THREAD

**Issue by musabmasood** [helm/charts#14705]
**Describe the bug**
Simply installing the latest spinnaker helm chart is failing (helm chart version **1.11.1**):

`helm install --name ss --namespace ss stable/spinnaker`

Error:

`Error: parse error in "spinnaker/templates/configmap/service-settings.yaml": template: spinnaker/templates/configmap/service-settings.yaml:37: function "mergeOverwrite" not defined`

**Version of Helm and Kubernetes**:

Helm version:

```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

Kubernetes version: `1.12`

**Which chart**:

stable/spinnaker

**Comment by legal90** [comment]
Oh, it seems that `mergeOverwrite` function is available only since helm 2.13.0
Please try upgrading to the latest Helm 2.* , if you can.

We might need to replace `mergeOverwrite` logic with reversed `merge` in order to keep a backward compatibility of `stable/spinnaker` with older Helm versions.
