### ISSUE TITLE
[stable/redis] issue title

### ISSUE THREAD

**Issue by aleclerc-sonrai** [helm/charts#14702]
**Describe the bug**
Default sentinel production values lead to issues. By default, we suggest 3 slaves, which means 4 sentinels, and a quorum of 2 in `stable/redis/ci/production-sentinel-values.yaml`. Couldn't this lead to split head issues?

**Version of Helm and Kubernetes**:
n/a

**Which chart**:
redis 8.0.8

**What happened**:
n/a

**What you expected to happen**:
Having default values setup in a way that don't prevent split head

**How to reproduce it** (as minimally and precisely as possible):
n/a

**Anything else we need to know**:
n/a

**Comment by javsalgar** [comment]
Hi,

This values.yaml is actually used for testing, not to be used for production deployments. However, you are right, I think we should change it to 4 slaves and a quorum of 3

**Comment by javsalgar** [comment]
PR created. Could you take a look?

**Comment by tompizmor** [comment]
@javsalgar I added a comment in the PR
