### ISSUE TITLE
[stable/postgresql] Can not run the initContainer when `volumePermissions.securityContext.runAsUser=1001` is set

### ISSUE THREAD

**Issue by sd7y** [helm/charts#14721]
**Describe the bug**

I have an issue with #14538 and try to enable the initContainer, the PSP is set to runAsNonRoot is active in my kubernetes, so If I need to set `volumePermissions.securityContext.runAsUser=1001`, then I got an error 
```
chown: changing ownership of '/bitnami/postgresql/data': Permission denied
```

**Version of Helm and Kubernetes**:
helm v2.12.1
kubernetes v1.13.1

**Which chart**:
stable/postgresql

**What happened**:
Failed to start the pod.

**What you expected to happen**:
Can be run when `volumePermissions.securityContext.runAsUser=1001` is set.

**How to reproduce it** (as minimally and precisely as possible):
In a kubernetes cluster that has PSP enabled and set `volumePermissions.securityContext.runAsUser=1001`

Run
`helm install --set volumePermissions.securityContext.runAsUser=1001 stable/postgresql -n pgtest`

`kubectl logs pgtest-postgresql-0 -c init-chmod-data`

Will show
```
chown: changing ownership of '/bitnami/postgresql/data': Permission denied
```

**Anything else we need to know**:
If I set `volumePermissions.securityContext.runAsUser=0` will get that
```
Warning  FailedCreate      28s (x18 over 2m8s)  statefulset-controller  create Pod loopy-macaw-postgresql-0 in StatefulSet loopy-macaw-postgresql failed error: pods "loopy-macaw-postgresql-0" is forbidden: unable to validate against any pod security policy: [spec.initContainers[0].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden]
```

**Comment by carrodher** [comment]
This chart has two methods to set the proper permissions to the persist volume, both are enabled by default.

The first one is a [_securityContext_](https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml#L68) (`1001:1001`) and the second one is an _initContainer_ [executed as root](https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml#L58) that run the following actions:
```
mkdir -p {{ .Values.persistence.mountPath }}/data
chmod 700 {{ .Values.persistence.mountPath }}/data
find {{ .Values.persistence.mountPath }} -mindepth 1 -maxdepth 1 -not -name ".snapshot" |  xargs chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }}
```
in your case, this initContainer is executed as `1001` due to `volumePermissions.securityContext.runAsUser=1001`, but this generates a failure in the `chown` because of a permission denied, the `chmod` worked fine because you can change the permissions of the folder using `chmod` if you are the owner of that folder without root permissions but you cannot change the ownership, either user or group (using either `chown` or `chgrp`), of a folder even though you are the owner.

The solution proposed in the PR ensures that the `chown` command is only executed if you are root, but, does PostgreSQL work if you bypass this step/command?

In the other hand, what happens if you disable the _initContainer_ and trust only in the _securityContext_? Please, take into account that I am talking about the [global _securityContext_](https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml#L68), not the init or metrics containers ones.

**Comment by sd7y** [comment]
Hi, thank you for your reply, this thing is like this:
At the beginning I set `volumePermissions.enable=false`, at which time it worked fine, but then I found out that sometimes the slave won't start, I checked the logs and found these:
```
FATAL:  data directory "/bitnami/postgresql/data" has invalid permissions
DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
```
I found #14538 in the list of issues, it looks the same as I did, then I tried to set `volumePermissions.enable=true`, but my kubernetes set the PSP, it can not be operated by the root user, so I set `volumePermissions.securityContext.runAsUser=1001`. But I got another error message
```
chown: changing ownership of '/bitnami/postgresql/data': Permission denied
```
Now, as long as I can modify the permissions of `/bitnami/postgresql/data` in some way, it can run normally, so I mentioned this PR.

**Comment by sd7y** [comment]
Can `volumePermissions.securityContext.runAsUser` be set to a value other than `0`? If it can only run normally when `volumePermissions.securityContext.runAsUser=0`, what is the reason for this configuration?

**Comment by docktermj** [comment]
Possibly related:  https://github.com/helm/charts/issues/14390

**Comment by sd7y** [comment]
I think I found the cause of the issue, `chmod 0700 "$POSTGRESQL_DATA_DIR"` is executed in this line of code https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-9/rootfs/libpostgresql.sh#L727, but my pod is stopped by some reason before this code is executed.
I think I should fix the issue pod is stopped. 
Thank you for your suggestions @carrodher @docktermj

**Comment by tompizmor** [comment]
@sd7y If you can, share the logs of the pod that is not starting well and we may be able to help.

If you think it is unrelated to this issue, feel free to open a new one.

**Comment by sd7y** [comment]
This is the logs

```
 09:09:10.98 Welcome to the Bitnami postgresql container
 09:09:10.98 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
 09:09:10.99 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
 09:09:10.99 Send us your feedback at containers@bitnami.com
 09:09:10.99 
 09:09:11.04 INFO  ==> ** Starting PostgreSQL setup **
 09:09:11.23 INFO  ==> Validating settings in POSTGRESQL_* env vars..
 09:09:11.24 INFO  ==> Initializing PostgreSQL database...
 09:09:11.29 INFO  ==> postgresql.conf file not detected. Generating it...
 09:09:11.32 INFO  ==> pg_hba.conf file not detected. Generating it...
 09:09:11.35 INFO  ==> Waiting for replication master to accept connections (60 timeout)...
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - no response
pgtest-postgres-postgresql:5432 - rejecting connections
pgtest-postgres-postgresql:5432 - rejecting connections
pgtest-postgres-postgresql:5432 - rejecting connections
pgtest-postgres-postgresql:5432 - rejecting connections
pgtest-postgres-postgresql:5432 - rejecting connections
pgtest-postgres-postgresql:5432 - rejecting connections
pgtest-postgres-postgresql:5432 - rejecting connections
pgtest-postgres-postgresql:5432 - rejecting connections
pgtest-postgres-postgresql:5432 - rejecting connections
pgtest-postgres-postgresql:5432 - rejecting connections
pgtest-postgres-postgresql:5432 - rejecting connections
pgtest-postgres-postgresql:5432 - rejecting connections
pgtest-postgres-postgresql:5432 - rejecting connections
pgtest-postgres-postgresql:5432 - rejecting connections
pgtest-postgres-postgresql:5432 - accepting connections
 09:10:47.54 INFO  ==> Replicating the initial database
pg_basebackup: initiating base backup, waiting for checkpoint to complete
pg_basebackup: checkpoint completed
pg_basebackup: write-ahead log start point: 0/2000028 on timeline 1
pg_basebackup: starting background WAL receiver
pg_basebackup: created temporary replication slot "pg_basebackup_250"
    0/85388 kB (0%), 0/1 tablespace (...ami/postgresql/data/backup_label)
 2007/85388 kB (2%), 0/1 tablespace (.../postgresql/data/base/1/12903_vm)
 7689/85388 kB (9%), 0/1 tablespace (...nami/postgresql/data/base/1/3467)
12537/85388 kB (14%), 0/1 tablespace (.../postgresql/data/base/13067/2673)
18097/85388 kB (21%), 0/1 tablespace (.../postgresql/data/base/13068/2607)
25010/85388 kB (29%), 0/1 tablespace (...tgresql/data/base/16386/1259_fsm)
31111/85388 kB (36%), 0/1 tablespace (.../postgresql/data/base/16386/3604)
37095/85388 kB (43%), 0/1 tablespace (.../postgresql/data/base/16387/2692)
41223/85388 kB (48%), 0/1 tablespace (...tgresql/data/base/16388/2607_fsm)
47341/85388 kB (55%), 0/1 tablespace (...tgresql/data/base/16389/1249_fsm)
53555/85388 kB (62%), 0/1 tablespace (.../postgresql/data/base/16389/3258)
59763/85388 kB (69%), 0/1 tablespace (.../postgresql/data/base/16390/2686)
65251/85388 kB (76%), 0/1 tablespace (...tgresql/data/base/16391/2610_fsm)
71438/85388 kB (83%), 0/1 tablespace (...gresql/data/base/16392/12913_fsm)
77182/85388 kB (90%), 0/1 tablespace (.../postgresql/data/base/16392/3597)
83522/85388 kB (97%), 0/1 tablespace (...tgresql/data/base/16393/2753_fsm)
85398/85398 kB (100%), 0/1 tablespace (...ostgresql/data/global/pg_control)
85398/85398 kB (100%), 1/1 tablespace                                         
pg_basebackup: write-ahead log end point: 0/2000130
pg_basebackup: waiting for background process to finish streaming ...

```

At this time, the pod was killed with that event.
```
Killing container with id docker://pgtest-postgres-postgresql:Container failed liveness probe.. Container will be killed and recreated.
```

Then the pod was recreated and got that message `Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).`

```
 09:11:14.04 
 09:11:14.05 Welcome to the Bitnami postgresql container
 09:11:14.05 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
 09:11:14.05 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
 09:11:14.06 Send us your feedback at containers@bitnami.com
 09:11:14.06 
 09:11:14.11 INFO  ==> ** Starting PostgreSQL setup **
 09:11:14.30 INFO  ==> Validating settings in POSTGRESQL_* env vars..
 09:11:14.32 INFO  ==> Initializing PostgreSQL database...
 09:11:14.35 INFO  ==> postgresql.conf file not detected. Generating it...
 09:11:14.39 INFO  ==> pg_hba.conf file not detected. Generating it...
 09:11:14.41 INFO  ==> Deploying PostgreSQL with persisted data...
 09:11:14.42 INFO  ==> Configuring replication parameters
 09:11:14.49 INFO  ==> Configuring fsync
 09:11:14.51 INFO  ==> Loading custom scripts...
 09:11:14.52 INFO  ==> Enabling remote connections
 09:11:14.55 INFO  ==> Stopping PostgreSQL...

 09:11:14.56 INFO  ==> ** PostgreSQL setup finished! **
 09:11:14.68 INFO  ==> ** Starting PostgreSQL **
2019-06-13 09:11:14.708 GMT [1] FATAL:  data directory "/bitnami/postgresql/data" has invalid permissions
2019-06-13 09:11:14.708 GMT [1] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
```

The reason is that I restored the database when postgresql is just started, so the pg_basebackup will take more time, so I set `livenessProbe.failureThreshold=30` and `readinessProbe.failureThreshold=30`. 

And make sure the salve initialization is completed by checking if the file ["$POSTGRESQL_TMP_DIR"/.initialized](https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-9/rootfs/entrypoint.sh#L24) is created, then I start to restore the backup file.

Another reason is I just stop the pod after restore is completed. At this time, it is possible the pod has not completed initialization.
