### ISSUE TITLE
Can't create redis release without a password

### ISSUE THREAD

**Issue by chainlink** [helm/charts#1473]
**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}

Kube version: 1.6.4

**Which chart**:
Redis

**What happened**:
Redis deployment created with password

**What you expected to happen**:
Create a redis deployment without a password

**How to reproduce it** (as minimally and precisely as possible):

`helm install stable/redis --name web --set usePassword=false`

OR 

`helm install stable/redis --name web --set usePassword=0`

OR

`helm install stable/redis --name web-cache --values redis-variable.yml` Where redis-variable.yml is copy of [values.yaml](https://github.com/kubernetes/charts/blob/master/stable/redis/values.yaml)
either with `usePassword: false` or `usePassword` omitted

**Anything else we need to know**:

Not right now?

**Comment by jackdreilly** [comment]
For anyone potentially hitting this issue in the future: I solved this by making sure that "false" was interpreted as a string instead of being converted to "0".
