### ISSUE TITLE
[stable/stolon]Data persistance is not working in postgres with chart version v0.13.0

### ISSUE THREAD

**Issue by Amithpn** [helm/charts#14751]
**Bug Description**

**Version of Helm and Kubernetes**: v0.13.0

**Which chart**: stolon

**What happened**: 
We expected data to be retained every time in the keepers.

**What you expected to happen**:
All the databases and tables created are gone when we restart the pods(helm delete)

**How to reproduce it** (as minimally and precisely as possible):

    1. Install the postgres cluster using helm charts
    2. Add some data to the postgres pointing to stolon-proxy service.
    3. Restart the pods using helm delete command
    4. Check if the data exists. 

**Anything else we need to know**:
We are using proxy pods to connect to postgres. Let us know what is the issue.

We have downloaded charts from the below URL: https://github.com/sorintlab/stolon/releases
Version: v0.13.0

Im using dockerfile of postgres v10.8 as postgres image

**Comment by docktermj** [comment]
Not sure if it helps, but Persistent Volumes (PV) and Persistent Volume Claims (PVC) need to be created for persistence.

An example of how to creat PV and PVC is in https://github.com/helm/charts/issues/14390

**Comment by Amithpn** [comment]
Hi @docktermj ,

I don't think its a PV/PVC creation problem, but if you still believe its PV/PVC problem then let me know after looking at below details.

Yesterday i deployed this chart with persistence enabled and it has created PVC/PV.

[root@server]# kubectl get pvc | grep stolon
data-si-postgres-stolon-keeper-0       Bound    pvc-14ffb823-8cfd-11e9-81a5-fa163eda9ef5   10Gi       RWO            cinder-az-nova           19h
data-si-postgres-stolon-keeper-1       Bound    pvc-25321774-8cfd-11e9-81a5-fa163eda9ef5   10Gi       RWO            cinder-az-nova           19h

And when pods are getting created it's using same volume which has been created earlier but even then the data is missing.

[root@server]# kubectl get pod | grep stolon
si-postgres-stolon-create-cluster-5pb97         0/1     Completed      0          5m43s
si-postgres-stolon-keeper-0                     1/1     Running        0          5m43s
si-postgres-stolon-keeper-1                     1/1     Running        0          5m33s
si-postgres-stolon-proxy-8496794555-bt6sx       1/1     Running        0          5m43s
si-postgres-stolon-proxy-8496794555-rtwmw       1/1     Running        0          5m43s
si-postgres-stolon-sentinel-5bcc8b65db-c4d4r    1/1     Running        0          5m43s
si-postgres-stolon-sentinel-5bcc8b65db-gfjjc    1/1     Running        0          5m43s
[root@server]# kubectl describe pod si-postgres-stolon-keeper-0 |grep pvc-14ffb823-8cfd-11e9-81a5-fa163eda9ef5
  Normal  SuccessfulAttachVolume  5m55s  attachdetach-controller      AttachVolume.Attach succeeded for volume "pvc-14ffb823-8cfd-11e9-81a5-fa163eda9ef5"
[root@server]#

**Comment by Amithpn** [comment]
I see the below form one of the job which runs every time i deploy the chart:

[root@server]# k logs -f si-postgres-stolon-create-cluster-5pb97
WARNING: The current cluster data will be removed
WARNING: The databases managed by the keepers will be overwritten depending on the provided cluster spec.
[root@server]#

Does it makes sense to anyone why data persistence might not be happening for me?

**Comment by ath88** [comment]
Are you setting `job.autoCreateCluster: false`? If not - your current cluster will be removed.
