### ISSUE TITLE
[incubator/patroni] Add support for setting pg_hba.conf through helm chart

### ISSUE THREAD

**Issue by joshua-vandenhoek** [helm/charts#14759]
Would really like to see support for setting postgres-related settings files (e.g. pg_hba.conf) from the helm chart. Currently, it does not look like there is support for this. I could be very wrong about this, so if I am please let me know!

**Is your feature request related to a problem? Please describe.**

I guess the problem is setting things like pg_hba.conf at deploy time and not through manual intervention or through another resource (like a job or something) that sets required lines in pg_hba.conf. We really want that config information stored in our manifests, which then can get pushed to our installations without visiting them manually or using another resource.

**Describe the solution you'd like**

Add support in the helm chart for setting values in postgresql-related files (e.g. pg_hba.conf)

**Describe alternatives you've considered**

Manually visiting the pods and changing the pg_hba.conf (not good) or using some kind of job that uses `sed` or some other text-injection utility to add the required lines to pg_hba.conf (not ideal)

**Additional context**
No additional context, but if this issue isn't descriptive enough please let me know and I will do what I can to elaborate further. Thanks!

**Comment by andresbono** [comment]
Hi @joshua-vandenhoek, I'll point you to some sections in the README.md that you may find useful:

- [postgresql.conf / pg_hba.conf files as configMap](https://github.com/helm/charts/tree/master/stable/postgresql#postgresqlconf--pg_hbaconf-files-as-configmap)
- [Configuration](https://github.com/helm/charts/tree/master/stable/postgresql#configuration)
  - `pgHbaConfiguration`
  - `postgresqlConfiguration`

Let us know if this is what you are looking for!

**Comment by joshua-vandenhoek** [comment]
Hey there @andresbono , thank you very much for your reply! So I see you have linked me to the stabe postgresql community helm chart. So as my question pertains specifically to the incubator/patroni helm chart, does the patroni helm chart support setting configuration parameters for postgres through the postgresql chart as a dependency? I checked the requirements.yaml for incubator/patroni, and the only dependencies that I see there are 2 (conditional on what tech you choose to keep cluster state):

`dependencies:
- name: etcd
  version: 0.6.2
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: etcd.deployChart
- name: zookeeper
  version: 1.0.0
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: zookeeper.deployChart`

I suppose I am just a little confused as to how I would set postgresql related configs in the patroni chart, because yes you are totally right, the postgresql community helm chart supports dropping configuration in via the helm chart, but it would appear as patroni does not. Please let me know if I am incorrect in my assessment, and thank you again for your time!

**Comment by andresbono** [comment]
Oh, so sorry @joshua-vandenhoek! I was checking opened issues for the `stable/postgresql` chart that _Bitnami_ maintains and I didn't filter out this one!

You are absolutely right, `incubator/patroni` and `stable/postgresql` are independent charts with no dependencies.

Sorry again for the confusion!

**Comment by joshua-vandenhoek** [comment]
That's alright @andresbono ! I appreciate you taking time to check this out. So with that being the case, do you know of a means to inject configuration lines into config files like pg_hba.conf using the incubator/patroni helm chart? We really like the patroni chart for the HA it can provide, but the lack of configuration options for postgres makes it a bit unwieldy to work with...

Anyway, if you have any insight to share regarding the patroni chart I would be most appreciative. 

Thanks!
