### ISSUE TITLE
[stable/airflow] redis.enabled: false does not stop Redis from launching

### ISSUE THREAD

**Issue by ashleykozachek** [helm/charts#14769]
**Describe the bug**
Setting the redis.enabled option to false does not disable Redis from being run. Either the documentation is incorrect as to what this flag does or Redis cannot be disabled. There's no need for me to use Redis as I am using a different Broker client.

**Version of Helm and Kubernetes**:
Helm: 2.14.0
Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"
```

**Which chart**:
stable/airflow

**What happened**:
Redis templates were created and Redis was installed into k8s.

**What you expected to happen**:
Airflow chart should launch without Redis being installed into k8s.

**How to reproduce it** (as minimally and precisely as possible):
In `values.yaml`:
```
airflow:
  redis:
    enabled: false```
Run `helm install .` in shell.

**Comment by mkozachek** [comment]
Issue was resolved by moving the redis options in `values.yaml` outside of the `airflow` block.
