### ISSUE TITLE
[stable/jenkins] Does not use release namespace for resources

### ISSUE THREAD

**Issue by nesl247** [helm/charts#14773]
**Describe the bug**

**Version of Helm and Kubernetes**: 
`Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}`

`Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.6", GitCommit:"fcbc1d20b6bca1936c0317743055ac75aef608ce", GitTreeState:"clean", BuildDate:"2019-05-23T11:42:40Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}`

**Which chart**: stable/jenkins

**What happened**: Resources are created in default namespace

**What you expected to happen**: Resources should be created in the release namespace

**How to reproduce it** (as minimally and precisely as possible): Install chart

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
Whenever I tried the resources are created in the correct namespace.

Can you provide details how one can reproduce the problem? What's the command you are using to install the chart?

**Comment by nesl247** [comment]
I'm actually using `pulumi` to do this. I did set the namespace property. I'm new to helm charts, so I could be wrong, but it seems like none of the templates have the namespace defined in them. Does helm add it automatically, and therefore maybe it's an issue with Pulumi?

**Comment by torstenwalter** [comment]
I am not familiar with pulumi, but I assume it's the same effect as helm template. Often resources are rendered without namespace. Helm/Tiller take care of injecting them. It's similar to having manifests without namespace and using `kubectl apply -n <namespace>`

Here are related tickets for pulumi:
https://github.com/pulumi/pulumi-kubernetes/issues/200
https://github.com/pulumi/pulumi-kubernetes/issues/217

**Comment by nesl247** [comment]
Thanks, I'll close this.

**Comment by nesl247** [comment]
I'm reopening this per the discussion on Pulumi. When helm is used purely as a templating tool, this won't work.

**Comment by nesl247** [comment]
This is still relevant.

**Comment by torstenwalter** [comment]
This is solved via #15202. Namespaces are rendered as part of the templating for all namespaced resources.
