### ISSUE TITLE
[stable/mariadb] Pod goes to CrashLoopBackOff when deleted with PVC enabled

### ISSUE THREAD

**Issue by ganchandrasekaran** [helm/charts#14840]
**Describe the bug**
Install the chart with persistence enabled. When all pods are running, delete slave pod. Then when the pod comes back again it is stuck with CrashLoopBackOff, because it is using the previous pvc. I am using [NFS Server Provisioner chart](https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner) that creates automatic pvc for required pods. 
The same happens when you delete the deployment and redeploy. If you delete the pvc before redeploying then everything is smooth. 

**Version of Helm and Kubernetes**:
# helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:35:32Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
#mariadb chart
version: 5.11.1
appVersion: 10.1.38

**What happened**:
 Pod goes to CrashLoopBackOff when deleted with PVC enabled.

**What you expected to happen**:
All pods should be in running state. When using StatefulSet, the mariaDB image should be capable enough to reuse the PV that was provisioned previously. This might be a big issue when scalingDown and then scalingUp the StatefulSets.. 

**How to reproduce it** (as minimally and precisely as possible):
```
helm install --name my-release stable/mariadb
$kubectl get pvc #check pv is provisioned
$kubectl delete <slave-pod>
$kubectl get pods
mariadb-lcm-master-0                                         1/1     Running            0          2d21h
mariadb-lcm-slave-0                                          0/1     CrashLoopBackOff   4          2m14s
$kubectl logs <slave-pod>
INFO  ==> ** Starting MariaDB setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
INFO  ==> Initializing mariadb database...
INFO  ==> Persisted data detected. Restoring...
INFO  ==> Stopping mariadb...
INFO  ==> ** MariaDB setup finished! **
INFO  ==> ** Starting MariaDB **
2019-06-17 16:12:48 140577449867136 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.38-MariaDB) starting as process 1 ...
2019-06-17 16:12:48 140577449867136 [ERROR] mysqld: File './mysql-bin.index' not found (Errcode: 22 "Invalid argument")
2019-06-17 16:12:48 140577449867136 [ERROR] Aborting
```

**Anything else we need to know**:
The same didn't have any trouble when running the deployment the first time.

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue. This is what I got after deleting the slave pod.

```
 1 ❯ kubectl logs quaffing-bronco-mariadb-slave-0 -f

Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MariaDB setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
INFO  ==> Initializing mariadb database...
INFO  ==> Persisted data detected. Restoring...
INFO  ==> Stopping mariadb...
INFO  ==> ** MariaDB setup finished! **

INFO  ==> ** Starting MariaDB **
2019-06-17 16:12:43 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.3.15-MariaDB-log) starting as process 1 ...
2019-06-17 16:12:43 0 [Note] InnoDB: Using Linux native AIO
2019-06-17 16:12:43 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-06-17 16:12:43 0 [Note] InnoDB: Uses event mutexes
2019-06-17 16:12:43 0 [Note] InnoDB: Compressed tables use zlib 1.2.8
2019-06-17 16:12:43 0 [Note] InnoDB: Number of pools: 1
2019-06-17 16:12:43 0 [Note] InnoDB: Using SSE2 crc32 instructions
2019-06-17 16:12:43 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2019-06-17 16:12:43 0 [Note] InnoDB: Completed initialization of buffer pool
2019-06-17 16:12:43 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2019-06-17 16:12:43 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2019-06-17 16:12:43 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2019-06-17 16:12:43 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2019-06-17 16:12:43 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2019-06-17 16:12:43 0 [Note] InnoDB: 10.3.15 started; log sequence number 1643873; transaction id 48
2019-06-17 16:12:43 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
2019-06-17 16:12:43 0 [Note] InnoDB: Buffer pool(s) load completed at 190617 16:12:43
2019-06-17 16:12:43 0 [Note] Plugin 'FEEDBACK' is disabled.
2019-06-17 16:12:43 0 [Note] Server socket created on IP: '0.0.0.0'.
2019-06-17 16:12:43 0 [Warning] 'proxies_priv' entry '@% root@quaffing-bronco-mariadb-slave-0' ignored in --skip-name-resolve mode.
2019-06-17 16:12:44 0 [Note] Reading of all Master_info entries succeded
2019-06-17 16:12:44 0 [Note] Added new Master_info '' to hash table
2019-06-17 16:12:44 10 [Note] Slave I/O thread: Start asynchronous replication to master 'replicator@quaffing-bronco-mariadb:3306' in log 'mysql-bin.000002' at position 342
2019-06-17 16:12:44 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
Version: '10.3.15-MariaDB-log'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
2019-06-17 16:12:44 11 [Note] Slave SQL thread initialized, starting replication in log 'mysql-bin.000002' at position 342, relay log './mysql-relay-bin.000004' position: 641
2019-06-17 16:12:44 10 [Note] Slave I/O thread: connected to master 'replicator@quaffing-bronco-mariadb:3306',replication started in log 'mysql-bin.000002' at position 342
```

```
❯ kubectl get pv | grep bronco
pvc-82e29baa-911a-11e9-adfc-42010a80003a   8Gi        RWO            Delete           Bound       default/data-quaffing-bronco-mariadb-master-0   nfs                     16m
pvc-82efe6b4-911a-11e9-adfc-42010a80003a   8Gi        RWO            Delete           Bound       default/data-quaffing-bronco-mariadb-slave-0    nfs                     16m
```

Could you provide more details about your platform?

**Comment by ganchandrasekaran** [comment]
That's weird. Here are some information on Storage class and MariaDB chart

```
# kubectl describe storageclasses.storage.k8s.io
Name:                  nfs
IsDefaultClass:        Yes
Annotations:           storageclass.kubernetes.io/is-default-class=true
Provisioner:           cluster.local/e2eo-infra-paas-nfs-server
Parameters:            mountOptions=vers=4.1
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```
I initially tried it with Image: `bitnami/mariadb:10.1.38`
But the same happens with latest image and latest chart too. Is there any other info you would like me to share?

**Comment by javsalgar** [comment]
Could you share the command you used to deploy the nfs server provisioner chart?

**Comment by ganchandrasekaran** [comment]
@javsalgar sure, following are some difference from the current `values.yaml` in nfs server provisioner chart
```
image:
  tag: v1.0.9
persistence:
  enabled: true
  storageClass: "-"
  size: 100Gi
  accessMode: ReadWriteOnce
storageClass:
  create: true
  defaultClass: true
  parameters:
    mountOptions: vers=4.1

```
I am creating a PV that nfs's PVC can claim
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-provisioner-0
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    path: /srv/volumes/data-nfs-server-provisioner-0
```
One difference in the NFS chart is that an additonal  mountOptionsis introduced 
```    - vers=4.1
    - noatime```
I have already share my default StorageClass above. Following is the command I used to install NFS server. 
`helm install stable/nfs-server-provisioner`

**Comment by ganchandrasekaran** [comment]
I am also running other DBs (e.g. Cassandra) using the PVC from the same NFS provisioner. But they seam to start fine when the pod is deleted, this only happens to mariadb.

**Comment by miguelaeh** [comment]
Not sure about the deployment, You installed the Chart for the nfs storage provisioner but you didn't use  'persistence.storageClass=nfs' on your MariaDB install command, so probably you are using other storage provisioner:
>helm install --name my-release stable/mariadb

Apart from that, I deployed using the following:
```bash
$ helm install stable/nfs-server-provisioner
$ helm install --name mariadb-maca stable/mariadb --set persistence.storageClass=nfs
$ ROOT_PASSWORD=$(kubectl get secret --namespace default mariadb-maca -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)
$ helm upgrade mariadb-maca stable/mariadb --set rootUser.password=$ROOT_PASSWORD
```
After that I killed the slave pod to see if I the error appear, but I was not able to replicate it. Could you provide more information about how to replicate this issue?

**Comment by ganchandrasekaran** [comment]
@miguelaeh thanks you
My nfs  storageClass is configured to be default so I dont have to specify `--set persistence.storageClass=nfs` this is selected by default. 

In your case, can I ask who provisions the PVClaim that is made for stable/nfs-server-provisioner ? In my case I created a separate PersistantVolume yaml based on `hostPath` filesystem based (as described above). 
```
# kubectl get pvc,pv
persistentvolumeclaim/data-infra-paas-nfs-server-0                    Bound   data-nfs-server-provisioner-0              100Gi      RWO                           7d

persistentvolume/data-nfs-server-provisioner-0              100Gi      RWO            Retain           Bound    default/data-infra-paas-nfs-server-0                                         
```

You have just mentioned all the steps I followed exactly. But the issue is specific to my setup? Can you confirm if you used a seperate PV for the PVC on the NFS server?

**Comment by javsalgar** [comment]
Hi,

I used the local provisioner PV (which is based on hostpath) and found no issues


```
local-pv-a9e728ff                          19Gi       RWO            Delete           Bound       kube-system/data-nfs-provisioner-nfs-server-provisioner-0   fast-disks              16m
```

**Comment by ganchandrasekaran** [comment]
@javsalgar Thank you for your response. 
Not sure why this happens in my clusters.. If none can experience this issue, I better close this issue..

**Comment by ganchandrasekaran** [comment]
Just realised this issue is because of slow PV response time. 
Fixed in PR: https://github.com/bitnami/bitnami-docker-mariadb-galera/pull/38
