### ISSUE TITLE
how to access kibana from the outside and which file should I modify for that 

### ISSUE THREAD

**Issue by mounaBoo** [helm/charts#14850]
Hello everyone, 

I am new on using kybernetes and helm chart so mayebe my question seems stupid but I would like to know how to change the IP adress to access the kibana dashboard from outside , I have installed your helm shart but as far as I know the kibana dashboard has access throught 127.0.0.1:5601 I want to change it into 0.0.0.0:5601 can any one help me , if there is a configuration file or anything could you please provide me with the location into it under kubernetes ? 

Thank you in advance.

**Comment by monotek** [comment]
I guess what you want is an ingress configuration...

https://kubernetes.io/docs/concepts/services-networking/ingress/

In the kibana chart is configured here: https://github.com/helm/charts/blob/master/stable/kibana/values.yaml#L67

**Comment by mounaBoo** [comment]
> 
> 
> I guess what you want is an ingress configuration...
> 
> https://kubernetes.io/docs/concepts/services-networking/ingress/
> 
> In the kibana chart is configured here: https://github.com/helm/charts/blob/master/stable/kibana/values.yaml#L67
> 
> P.S: Please give your issues a meaningfull name in the future...
thank you.

I am looking into the kibana yaml on my kubernetes is there any thing to change in there to access the dashboard from outside.

and the values.yaml where can I found it on my cluster ?

**Comment by monotek** [comment]
Its outside the cluster in some local file.
If you're using helm you should not edit the created resources inside the cluster.
Instead change the values file and do an "helm upgrade...."

**Comment by mounaBoo** [comment]
thank sir , now I get kibana to work ( using the forwarding option on kubernetes) it's given me Kibana not ready error message so the elasticsearch is not runing when I do curl -XPOST 'localhost:9200'


curl curl: (7) Failed to connect to localhost port 9200: Connection refused

**Comment by monotek** [comment]
Yu need a running elasticsearch server and configure the elasticsearch url in kibanas values file.
