### ISSUE TITLE
[stable/jenkins] Chart tries to install Jenkins Configuration as Code Support plugin

### ISSUE THREAD

**Issue by rainerfrey** [helm/charts#14856]
**Describe the bug**
The Jenkins chart adds the Plugin `configuration-as-code-support` to the list of plugins to be installed, if JCasC is enabled. This plugin has been removed in recent releases of `configuration-as-code`, and is no longer listed on https://plugins.jenkins.io/.

**Version of Helm and Kubernetes**:
not relevant

**Which chart**:
stable/jenkins

**What happened**:
I removed the value `Master.JCasC.SupportPluginVersion` from my values.yml. Version 1.5 of `configuration-as-code-support` was installed (as per default value.yml). 

**What you expected to happen**:
`configuration-as-code-support` is not installed.

**How to reproduce it** (as minimally and precisely as possible):
Set the following values:

```
Master:
  JCasC:
      enabled: true
      pluginVersion: "1.20"
```

Deploy jenkins/stable

**Anything else we need to know**:
https://updates.jenkins.io/current/update-center.json contains no reference to `configuration-as-code-support`

**Comment by torstenwalter** [comment]
Thanks for raising this issues. Fix should be released soon. See linked PR for details.
