### ISSUE TITLE
[spark-history-server] Spark History UI Authentication

### ISSUE THREAD

**Issue by perdurabo93** [helm/charts#14857]
**Problem Description**
I would like to have the ability to authenticate the UI to LDAP, PAM or SPNEGO/Kerberos using whatever filter servlets/filters, etc might be required, and for this configuration to be handled with in the chart's values.yaml.  I have a hard security requirement that all web UIs must be authenticated and I don't have local Kerberos domain or Ambari managed Hadoop cluster to leverage.

**Describe the solution you'd like**
An easy UI authentication configuration in the chart with templates for several auth methods (LDAP/AD, PAM, SPNEGO/Kerberos).

**Describe alternatives you've considered**
Some sort of nginx proxy ingress authentication might be workable, if I can get examples.

**Comment by jahstreet** [comment]
> **Problem Description**
> I would like to have the ability to authenticate the UI to LDAP, PAM or SPNEGO/Kerberos using whatever filter servlets/filters, etc might be required, and for this configuration to be handled with in the chart's values.yaml. I have a hard security requirement that all web UIs must be authenticated and I don't have local Kerberos domain or Ambari managed Hadoop cluster to leverage.
> 
> **Describe the solution you'd like**
> An easy UI authentication configuration in the chart with templates for several auth methods (LDAP/AD, PAM, SPNEGO/Kerberos).
> 
> **Describe alternatives you've considered**
> Some sort of nginx proxy ingress authentication might be workable, if I can get examples.

Hi. 
We run AKS on Azure and do the trick with [Nginx Ingreess Controller](https://github.com/helm/charts/tree/master/stable/nginx-ingress) + [OAuth2 Proxy](https://github.com/helm/charts/tree/master/stable/oauth2-proxy) + [Certmanager](https://github.com/helm/charts/tree/master/stable/cert-manager).

You can refer my [helm chart repo](https://github.com/jahstreet/spark-on-kubernetes-helm/tree/master/charts/cluster-base) and [history-server chart settings](https://github.com/jahstreet/spark-on-kubernetes-helm/blob/master/charts/spark-cluster/values.yaml#L57). Will be glad to assist you on configurations, e-mail me with the details if you need a help.
