### ISSUE TITLE
[concourse/stable] Concourse Let's Encrypt usage w/ Ingress

### ISSUE THREAD

**Issue by aegershman** [helm/charts#14867]
See also: https://github.com/helm/charts/pull/14292#issuecomment-502834939

**Version of Helm and Kubernetes**:
helm 2.4.x, k8s 1.14.x

**Describe the bug**

Concourse web pods fail to start when attempting to leverage the Let's Encrypt feature because the `--tls-bind-port` is not supplied.

Using the following configuration values:

```yml
concourse:
  web:
    externalUrl: "https://concourse.example.com"
    letsEncrypt:
      enabled: true

web:
  ingress:
    enabled: true
    hosts:
    - concourse.example.com
```

Results in these error logs from web pod:

```
kubectl -n concourse-external logs -f concourse-external-web-84d86b5b55-bnpgq
1 error occurred:
        * must specify --tls-bind-port to use TLS
```

[but the only way to specify `tls-bind-port` is to turn on `concourse.web.tls.enabled=true`](https://github.com/helm/charts/blob/master/stable/concourse/templates/web-deployment.yaml#L178-L185), which will then require you to provide `secrets.webTlsCert` and `secrets.webTlsKey`, despite the fact that it's supposed to be generated by certbot.

**Background info**

I'd prefer not to use a `Service: LoadBalancer` for `web`, as it takes up extra IPs and LBs, requires a more hands-on DNS sync solution, makes it harder to deploy against multiple IaaSes, etc.

I haven't tried this, but maybe I could modify the chart to pass in a `--tls-bind-port` through a param besides the `concourse.web.tls.enabled: true`, keep using the Ingress, but set [SSL passthrough on the Ingress controller](https://kubernetes.github.io/ingress-nginx/user-guide/tls/#ssl-passthrough) so the ATC (`web`) pod can handle it's own SSL termination / use Let's Encrypt to generate the certs...? Haven't ever tried it, so unsure if it's possible.

Any thoughts? Thanks for your time 👍

**Comment by YoussB** [comment]
🙌

**Comment by aegershman** [comment]
see also:
- https://github.com/helm/charts/issues/16467
- https://github.com/concourse/concourse/issues/4216
