### ISSUE TITLE
[concourse/stable] Concourse worker name should have worker number in hostname

### ISSUE THREAD

**Issue by aegershman** [helm/charts#14868]
First off, I realize the title is a bit confusing. It's not as crazy as it sounds.

**Is your feature request related to a problem? Please describe.**

Want to deploy [external workers in multiple kubernetes environments](https://github.com/helm/charts/issues/11280) and have them all phone in to a single `web` deployment. These workers will be tagged so pipelines can take advantage of the workers' data locality.

When you deploy a Concourse chart, the workers uses the deployment's name as their hostname, e.g., if the deployment name is `concourse`, the workers are named `concourse-worker-X`

```yml
# assuming the chart's deployment name is "concourse"
fly -t main workers
name                                                   containers  platform  tags                                          team             state    version
concourse-worker-0                                     2           linux     none                                          none             running  2.1    
concourse-worker-1                                     1           linux     none                                          none             running  2.1    
```

So when you want to deploy **multiple external worker deployments** in various environments, you can't have the chart's deployment name be the same in each environment, or else they'll all clobber each other's worker name, and Concourse won't know how to distinguish them from each other.

E.g., if I did `helm deploy stable/concourse --name concourse-external` in vSphere, AWS, and Azure, all the workers from each deployment would report themselves as `concourse-external-worker-{0,1,2,etc.}`, even though they're on different deployments.

**Describe alternatives you've considered**

There's a field to override the Concourse worker name, like so:

```yml
concourse:
  worker:
    name: foo
```

But the problem is, it'll set the name of **every** Concourse worker in that external-workers deployment to the same value. So if you have a `replicaCount` greater than 1, everything will go haywire, since all the workers with their `concourse.worker.name: foo` configured will _all_ report themselves as `foo`. It'll only show up as one worker:

```
# assuming the chart's deployment name is "concourse"
fly -t main workers
name                                                   containers  platform  tags                                          team             state    version
foo                                     23           linux     none                                          none             running  2.1    
```

In order for them to be properly addressable, they need to report themselves as `foo-0`, `foo-1`, `foo-2`, etc. 

---

I've found the only way around this is to change the name of the chart for each deployment (`helm deploy stable/concourse --name conc-extern-aws-sandbox-us-west-2` for AWS maybe, and `--name conc-extern-azure-sandbox-centralus` for Azure, etc.), so that each worker reports in as `conc-extern-aws-sandbox-us-west-2-worker-0`, etc., OR

**Describe the solution you'd like**

Perhaps instead it would be better to have the `concourse.worker.name: foo` act as a _prefix_ for the worker's name, and suffix the name with the number associated to the worker pod's statefulset; e.g., `foo-0, foo1-1`, etc.

... I have no idea if that's even possible, though. It might not be possible to set the value of the worker's name as a "prefix" and then have the helm template suffix the worker's name with a number.

Perhaps instead a UUID could be generated and suffixed?

**Additional context**

Again, this problem could be solved by changing the name of the chart for each deployment, so it's not the end of the world... but it's a bit preferable to keep the chart name the same in each environment, and simply change the `values.yml` instead of the entire chart name. That's what I'm currently doing, at least.

Thoughts?

Thanks for your time!

**Comment by cirocosta** [comment]
Hey @aegershman,

If I understood correctly, I think what you want can already be achieved by leveraging the `worker.nameOverride` property as most of the "named" things we create are based on the templating of `concourse.worker.fullname`.

For instance, the name used for the worker container:

https://github.com/helm/charts/blob/5be1dd36fbbfb95372af3155e249b5a4366bff5f/stable/concourse/templates/worker-statefulset.yaml#L68


Looking at what that template function:

https://github.com/helm/charts/blob/5be1dd36fbbfb95372af3155e249b5a4366bff5f/stable/concourse/templates/_helpers.tpl#L18-L25

we can notice how that'd allow us to change the container name without having to change the release name.

Thus, if you try a `values.yaml` like the following:

```yaml
worker:
  nameOverride: "aws-sandbox"
```

And then deploy Concourse letting `helm` pick a random name (in my case, it picked `broken-buffalo`):

```
kubectl get pods
NAME                                         READY   STATUS    RESTARTS   AGE
broken-buffalo-aws-sandbox-0                 1/1     Running   0          17m
broken-buffalo-aws-sandbox-1                 1/1     Running   0          17m
...
```

Which leads to:

```
fly -t local workers
name                          containers  platform  tags  team  state    version
broken-buffalo-aws-sandbox-0  0           linux     none  none  running  2.1
broken-buffalo-aws-sandbox-1  0           linux     none  none  running  2.1
```

---

Do you think such property is enough?

Thanks!

**Comment by aegershman** [comment]
Ah! @cirocosta you smart cookie. Dang, apologies I missed this, I should've looked closer at it in the doc & chart. I will try this out later, though I think this will work just fine. Didn't mean to eat up your time in writing a response, I hope at least this issue can serve someone else who runs into a similar use-case. Thank you!
