### ISSUE TITLE
[stable/grafana] Grafana fails to pull image 6.2.3

### ISSUE THREAD

**Issue by azalenski** [helm/charts#14878]
**Describe the bug**
After trying to install grafana using helm, the pod fails to start due to the following error:

Failed to pull image "grafana/grafana:6.2.3": rpc error: code = Unknown desc = Error response from daemon: manifest for grafana/grafana:6.2.3 not found

**Version of Helm and Kubernetes**:
Helm: v2.14.1
Kubernetes v1.12.9

**Which chart**:
stable/grafana

**What happened**:
Grafana pod fails to start.

**What you expected to happen**:
Grafan pods pulls the image correctly and starts as expected

**How to reproduce it** (as minimally and precisely as possible):
helm install --name grafana stable/grafana ---set rbac.create=true

**Anything else we need to know**:

**Comment by StianOvrevage** [comment]
Introduced in commit https://github.com/helm/charts/commit/64ec62d89180a9228e70637cd88d1c10974267b5 by @davidkarlsen 

6.2.3 is not available on Docker hub: https://hub.docker.com/r/grafana/grafana/tags

**Comment by EricLemieux** [comment]
It looks like there was an issue with the 6.2.3 Image so it was removed from docker hub
https://github.com/grafana/grafana/blob/master/CHANGELOG.md#known-issues

**Comment by maorfr** [comment]
image has been since upgraded, closing this issue. thanks for bringing this uP!
