### ISSUE TITLE
[stable/nats] does not encode maxPayload correctly

### ISSUE THREAD

**Issue by baadc0de** [helm/charts#14879]
**Describe the bug**
The helm chart encodes the `maxPayload` option as a floating point number even when it is provided as an integer.

**Version of Helm and Kubernetes**:
helm 2.13.1, kubernetes 1.14.3

**Which chart**:
stable/nats

**What happened**:
The generated configMap encoded the `maxPayload` in scientific notation, `8.388608e06` which gnatsd failed to parse. As a result the server pod crashes and does not start.

**What you expected to happen**:
The integer value should have been passed through verbatim. If storage unit suffixes were expected (say, 8Mi) that should be documented.

**How to reproduce it** (as minimally and precisely as possible):
```
helm install stable/nats --set maxPayload=8388608
```

**Anything else we need to know**:
probably super easy to fix

**Comment by baadc0de** [comment]
Manually editing the configmap fixes the problem and the pod starts successfully.

**Comment by javsalgar** [comment]
Hi. Thanks for reporting. I created a PR that fixes the issue

https://github.com/helm/charts/pull/14891
