### ISSUE TITLE
[stable/prometheus-operator] Add support log.format for alertmanager

### ISSUE THREAD

**Issue by mcinquin** [helm/charts#14874]
**Is your feature request related to a problem? Please describe.**
Alertmanager is able to use json as log format. The option logFormat isn't avaiable for alertmanager in values.yaml.

**Describe the solution you'd like**
Add logFormat parameter just above logLevel in values.yaml and alertmanager.yaml

**Additional context**
Adding `logFormat: "json"` in the alertmanager.yaml as workaround works fine

**Comment by ys-taylorchristie** [comment]
FYI, this change makes a non-defined log format give a nil value in the pod command argument, and makes alert manager loop crash.

[
<img width="588" alt="Screen Shot 2019-07-08 at 9 20 28 AM" src="https://user-images.githubusercontent.com/51799307/60821986-d5a87f00-a161-11e9-9fad-69184e2345ed.png">

**Comment by jnaulty** [comment]
@ys-taylorchristie 
I found this issue too, and created the issue #15572 (with PR #15582 to resolve this)
