### ISSUE TITLE
[stable/prometheus-operator] How to install custom dashboards and alerting rules

### ISSUE THREAD

**Issue by ghost** [helm/charts#14889]
**Is your feature request related to a problem? Please describe.**
After going through the documentation, and examining the project, I am still not clear how
you're supposed to install custom grafana dashboards and custom alertmanager rules.

The section in the readme which pertains to developing rules and dashboards suggests to add changes to the original `kube-prometheus` repo, then they will be synced by the `hack`  scripts:
https://github.com/helm/charts/tree/master/stable/prometheus-operator#developing-prometheus-rules-and-grafana-dashboards

However, the `kube-prometheus` project states the idea is to use it as a library or package, 
and then extend the rules and dashboards with jsonnet in your own project.

Am I understanding this correctly, that the only way to customize rules and dashboards is to add PRs to the external repos, and there's no way to pass them as values to the `prometeus-operator` chart?

**Describe the solution you'd like**
A clear description on how to implement a workflow for adding custom grafana dashboards and alertmanager rules.

**Comment by MrD2** [comment]
Custom dashboards you need to set them as a CM with a grafana_dashboar: "1" label. Check existent dashboards. Alerting rules, you need to create a k8s object manifest PrometheusRules.
you can kubectl get PrometheusRules and check the examples on how you can do this.

/close
