### ISSUE TITLE
[Stable/apm-server]  liveness and readiness checks will fail after enable ssl 

### ISSUE THREAD

**Issue by snikaein** [helm/charts#14901]
**Describe the bug**
when you enable the TLS in config 
    ssl.enabled: true
    ssl.certificate : "cert"
    ssl.key : "private_key"

liveness and readiness failed after enabling the ssl.
just fix by editing the schema of  liveness & readiness to HTTPS

**Version of Helm and Kubernetes**:
helm = v2.14.1
kubernetes = 1.12

**Which chart**:
Stable/apm-server

**Comment by tomtom94** [comment]
`probesEnabled=false`
