### ISSUE TITLE
[stable/nginx-ingress] use-proxy-protocol default value

### ISSUE THREAD

**Issue by pierluigilenoci** [helm/charts#14937]
**Describe the bug**
If you remove “use-proxy-protocol”: “true” from helm values the ingress remain with this configuration

**Version of Helm and Kubernetes**:
K8s v1.12.7
Helm v2.14.1

**Which chart**:
v1.6.18

**What happened**:
I activated the value “use-proxy-protocol”: “true” inside the config and I updated the ingress. Unluckily the Cloud LB did not support proxy protocol and so I removed the line and updated again. Nginx has remained set with “use-proxy-protocol”: “true”. To resolve I had to update explicitly the configuration with “use-proxy-protocol”: “false”.

**What you expected to happen**:
I expected that once the row was removed in the config the ingress would return to the default configuration for "use-proxy-protocol"

**How to reproduce it** (as minimally and precisely as possible):
Redo the same step that I did.

**Anything else we need to know**:

**Comment by PierluigiLenociAkelius** [comment]
Has anyone else had this problem?

**Comment by PierluigiLenociAkelius** [comment]
Ref: https://github.com/kubernetes/ingress-nginx/issues/4305

**Comment by PierluigiLenociAkelius** [comment]
@ChiefAlexander could you please take a look?

**Comment by PierluigiLenociAkelius** [comment]
@ChiefAlexander @taharah could you please help me with this?

**Comment by pierluigilenoci** [comment]
Anyone with the same problem?

**Comment by pierluigilenoci** [comment]
@ChiefAlexander @taharah can I have a feedback?

**Comment by drmaxx** [comment]
☝️

**Comment by pierluigilenoci** [comment]
@drmaxx thank you!

**Comment by pierluigilenoci** [comment]
@ChiefAlexander @taharah please! 💋

**Comment by pierluigilenoci** [comment]
@ChiefAlexander @taharah I will continue in this way until I get an answer.

**Comment by pierluigilenoci** [comment]
@aledbf maybe you?

**Comment by pierluigilenoci** [comment]
Reopened here https://github.com/kubernetes/ingress-nginx/issues/5560
