### ISSUE TITLE
[stable/Kibana] Wrong elasticsearch.url

### ISSUE THREAD

**Issue by Larzack** [helm/charts#14934]
**Describe the bug**
Kibana is not starting because it can't connect to elasticsearch.url which is by default http://elasticsearch:9200

Installed my elasticsearch service with the name elk-elasticsearch-client

So the URL should be http://elk-elasticsearch-client:9200

**Version of Helm and Kubernetes**:

Kubernetes : v1.12
Helm : v2.14.1 

**Which chart**:

Kibana

**Comment by compleatang** [comment]
Fixed by #14905
