### ISSUE TITLE
[stable/grafana]Upgrade from 1.17.6 to 3.5.4 fails : kind PodSecurityPolicy with the name "grafana-test" already exists

### ISSUE THREAD

**Issue by cabrinoob** [helm/charts#14936]
Hi,
I'd like to upgrade my grafana release deployed on my K8S cluster.

The current version of my deployed grafana chart is v1.17.6.

When I run this command : 

    helm upgrade --install grafana stable/grafana --version 3.5.4 --namespace prometheus -f grafana-values.yaml

I have this error : 

    Error: UPGRADE FAILED: kind PodSecurityPolicy with the name "grafana-test" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart

If I download the last version of the grafana chart (the v3.5.4), I see a new sub-directory `test` in the `/templates` directory that does not exist in the previous version.

How can I do to upgrade my release without deleting it (and loosing my dashboards)

Thank you for your help

**Comment by voxmaster** [comment]
Same here when upgrading prometheus-operator-5.5.1 to prometheus-operator-5.14.1

**Comment by pgporada** [comment]
I'm encountering this as well with prometheus-operator-5.16.0 in one cluster. I was able to successfully upgrade another cluster though which is very strange.
```
Error: UPGRADE FAILED: kind PodSecurityPolicy with the name "prometheus-operator-grafana" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
```

I then delete the PSP and try again, but I receive
```
Error: UPGRADE FAILED: kind ConfigMap with the name "prometheus-operator-grafana-config-dashboards" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
```

What can we do without completely deleting the prometheus-operator?
