### ISSUE TITLE
[stable/redis] configmap contains wrong value

### ISSUE THREAD

**Issue by avirtual** [helm/charts#14951]
[https://github.com/helm/charts/blob/master/stable/redis/templates/configmap.yaml](https://github.com/helm/charts/blob/master/stable/redis/templates/configmap.yaml) has a reference to cluster.local, but it should be {{.Values.clusterDomain}}
```
sentinel monitor {{ .Values.sentinel.masterSet }} {{ template "redis.fullname" . }}-master-0.{{ template "redis.fullname" . }}-headless.{{ .Release.Namespace }}.svc.cluster.local {{ .Values.redisPort }} {{ .Values.sentinel.quorum }}

```

Since clusterDomain is a variable that can be set, having a constant string breaks sentinels.

**Comment by miguelaeh** [comment]
Hi @avirtual,
Thank you very much for your report, I see you provided the solution to other bugs too, it is a pleasure to have users like you.
This is fixed on https://github.com/helm/charts/pull/14955
