### ISSUE TITLE
Include how to validate install on spartickus

### ISSUE THREAD

**Issue by chrislovecnm** [helm/charts#150]
Update notes.txt to talk about how to validate the chat install.

**Comment by chrislovecnm** [comment]
@mgoodness thoughts on this?

**Comment by mgoodness** [comment]
Is something like this sufficient?

> To verify Spartakus installed correctly, run `kubectl get pods --ns {{ .Release.Namespace }} -l etc.`

**Comment by prydonius** [comment]
Personally I don't think this is useful, since the `helm status` command is intended to show that resources were installed successfully. IMO The current NOTES.txt is fine, but if @chrislovecnm feels strongly I am ok merging #156.

**Comment by chrislovecnm** [comment]
Ther are not any notes.txt.  ds currently has a nasty bug were they are failing silently for instance. I like clear validation instructions. Helps n00bs. 

Explain it to me like I am 5.

Much appreciated!!!!
