### ISSUE TITLE
[stable/wordpress] service.extraPorts it not indented correctly.

### ISSUE THREAD

**Issue by robinelfrink** [helm/charts#15009]
**Describe the bug**
service.extraPorts it not indented correctly.

**Version of Helm and Kubernetes**:
n/a

**Which chart**:
stable/wordpress

**What happened**:
I added a port to `service.extraPorts` and got the error:

```
Error: YAML parse error on wordpress/templates/svc.yaml: error converting YAML to JSON: yaml: line 21: did not find expected key
```

**What you expected to happen**:
No error, and a service which includes the extra defined port.

**How to reproduce it** (as minimally and precisely as possible):
Add a port to `extraPorts` in `values.yaml`.

**Anything else we need to know**:

**Comment by tompizmor** [comment]
Hi @robinelfrink!

Thanks for reporting it and create a PR with the fix. Please take a look at my comment there when you have a minute.
