### ISSUE TITLE
[stable/sonarqube] No language analyzers/default quality profiles

### ISSUE THREAD

**Issue by mascah** [helm/charts#15019]
**Describe the bug**
When installing a fresh release of sonarqube, none of the language analyzers appear to be loaded.

**Version of Helm and Kubernetes**:

helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", 
GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Kubernetes version
1.12

**Which chart**:
stable/sonarqube

**What happened**:
The application does not start with the default language analyzers

**What you expected to happen**:
Application to start with default language analyzers

**How to reproduce it** (as minimally and precisely as possible):
`helm install stable/sonarqube`

**Anything else we need to know**:
I went back a few version to version `0.12.0` and when doing a default helm install sonarqube starts up with all the default language analyzers.

**Comment by jcoeltjen** [comment]
The plugins folder is replaced with a volume that defaults to EmptyDir when using default values.
This was introduced via commit: https://github.com/helm/charts/commit/4ecc41158d8b9e0a268f3c42eb6c82133d9f4f74
PR: #12661
Issue: #12635

Simple workaround is to delete the mountPaths from the `deployment.yaml` but that would propably break the fixed issue from the PR that causes this issue.
We should have a look on how we can fix this without breaking the ability to run on readOnlyRoot enabled clusters.

**Comment by jcoeltjen** [comment]
Maybe we can use another init container that populates the emptyDir volumes before startup.
I will try this and give feedback.

**Comment by jcoeltjen** [comment]
I pushed a quick fix to my fork: https://github.com/jcoeltjen/charts/tree/feature/default-plugins
Currently I have no access to a cluster where PodSecurityPolicies are properly configured. Maybe somebody with a configured cluster on hand can try this.
