### ISSUE TITLE
[stable/external-dns] secret checksum breaks chart

### ISSUE THREAD

**Issue by grahamar** [helm/charts#15011]
**Describe the bug**

The latest chart cannot deploy due to the following error:

```
Error: validation failed: error validating "": error validating data: ValidationError(Deployment.spec.template.metadata): unknown field "checksum/secret" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
```

Looks like it's due to the following commit:
https://github.com/helm/charts/commit/0dc8468615aa0b23795e07178dfb330fe466e532

I assume this should be a Pod Annotation instead?

**Version of Helm and Kubernetes**:

**HELM**:
```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

**KUBERNETES**:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.0", GitCommit:"14c9138d6fb5b57473e270fe8a2973300fbd6fd6", GitTreeState:"clean", BuildDate:"2019-05-08T16:22:55Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
external-dns chart version 1.8.0

**What happened**:

checksum fields are not part of the kubernetes ObjectMeta V1 spec: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#objectmeta-v1-meta

**What you expected to happen**:

Chart to be valid

**How to reproduce it** (as minimally and precisely as possible):

Just a regular helm install stable/external-dns

**Anything else we need to know**:

I'm not specifying any pod annotations

**Comment by caarlos0** [comment]
same here, had to install previous version again...

**Comment by caarlos0** [comment]
cc/ @prydonius

**Comment by tanordheim** [comment]
For reference, if anyone else is looking - the last version where this seems to not be broken is 1.7.9.

**Comment by juan131** [comment]
I think it was solved on this PR: https://github.com/helm/charts/pull/15243
Could you please confirm it?

**Comment by chap-dr** [comment]
> I think it was solved on this PR: #15243
> Could you please confirm it?

I just tried installing chart v. 1.9.0 and got this error. 

Im using google as my provider.

**Comment by juan131** [comment]
Hi @chap-dr 

That PR solved the issue and bumped the chart version to **2.0.1**. Therefore, you will face the issue if you're using any previous version (such as **1.9.0**)

**Comment by chap-dr** [comment]
> Hi @chap-dr
> 
> That PR solved the issue and bumped the chart version to **2.0.1**. Therefore, you will face the issue if you're using any previous version (such as **1.9.0**)

Hmm, why am i getting 1.9.0 then? I just did a helm fetch.. 

a helm search returns 

``
$ helm search external-dns
NAME               	CHART VERSION	APP VERSION	DESCRIPTION
stable/external-dns	1.9.0        	0.5.14     	ExternalDNS is a Kubernetes addon that configures public ...

**Comment by caarlos0** [comment]
That PR does not properly fix the issue I'm afraid

check https://github.com/helm/charts/pull/15485

**Comment by caarlos0** [comment]
Should be good now, #15485 was merged :)
