### ISSUE TITLE
[stable/traefik] Invalid TOML generated

### ISSUE THREAD

**Issue by mhbrooks** [helm/charts#15015]
**Describe the bug**
I have enabled TLS on my consul endpoint and would like traefik to connect to it over https rather than http.

However because I am using a self signed certificate traefik does not trust the consul endpoint. Whilst I would like to add the self-signed ca as trusted this does not seem to be possible/trivial.

Instead I am hoping that `kvprovider.consul.tls.insecureSkipVerify` will do what I need. When I attempt to use this flag with this terraform snippet:
```
  set {
    name  = "kvprovider.consul.tls.insecureSkipVerify"
    value = true
  }
```
I get the following error from the traefik pods:
```
Error reading TOML config file /config/traefik.toml : toml: cannot load TOML value of type string into a Go boolean
```
Which I assume means the TOML file has been saved with the value set to `"true"` rather than `true`. Looking at the template it seems like the problem might be here:

https://github.com/helm/charts/blob/b620b76d5ea772a4893b26edb12ea432b1a2564a/stable/traefik/templates/configmap.yaml#L224

I am not particularly familiar with helm but from googling it seems like this forces all values into strings, which matches the error.

**Version of Helm and Kubernetes**:
Helm
```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

Helm Provider
0.10.0

Terraform 
0.12.2

Kubernetes
1.12.8-gke.10 

**Which chart**:
stable/traefik

**What happened**:
I get the following error from the traefik pods:
```
Error reading TOML config file /config/traefik.toml : toml: cannot load TOML value of type string into a Go boolean
```

**What you expected to happen**:
The value to be set correctly

**How to reproduce it** (as minimally and precisely as possible):
Use the `kvprovider.consul.tls.insecureSkipVerify` field in a chart

**Anything else we need to know**:

**Comment by KadenLNelson** [comment]
A little off topic, I'm curious, why do you use Terraform to deploy Helm charts?

**Comment by KadenLNelson** [comment]
Could you post the Traefik `config.toml` in the ConfigMap?

**Comment by mhbrooks** [comment]
> A little off topic, I'm curious, why do you use Terraform to deploy Helm charts?

Hey, its a good question, in general we do not use Terraform for k8s deployments. However we find that there a few charts where it makes sense to do so, for a few reasons:

- Logically they are closer to infrastructure resources than (our) application 
- They interact closely with other infrastructure resources
- It is important that they are deployed and ready before other services start
- They are common across all teams/clusters
- We do not maintain the source code so a full CI pipeline of our own would not make sense for them

The list of services where this applies is quite small but includes:
- Traefik
- (Google Cloud SQL) SQL Proxy
- Datadog/Grafana/Prometheus 
 - Weave Flux

**Comment by mhbrooks** [comment]
The toml config map looks like:
        ```"traefik.toml": "# traefik.toml\nlogLevel = \"info\"\ndefaultEntryPoints = [\"http\",\"https\"]\n[entryPoints]\n  [entryPoints.http]\n  address = \":80\"\n  compress = true\n    [entryPoints.http.redirect]\n      regex = \"^http://(.*)\"\n      replacement = \"https://$1\"\n      permanent = true\n  [entryPoints.https]\n  address = \":443\"\n  compress = true\n    [entryPoints.https.tls]\n      minVersion = \"1.1\"\n      [[entryPoints.https.tls.certificates]]\n      CertFile = \"/ssl/tls.crt\"\n      KeyFile = \"/ssl/tls.key\"\n[ping]\nentryPoint = \"http\"\n[kubernetes]\n[traefikLog]\n  format = \"json\"\n[accessLog]\n  format = \"json\"\n[accessLog.fields]\n  defaultMode = \"keep\"\n[accessLog.fields.names]\n[accessLog.fields.headers]\n  defaultMode = \"keep\"\n[accessLog.fields.headers.names]\n[consul]\nendpoint = \"http://consul:8500\"\nwatch = true\nprefix = \"traefik\"\n  [consul.tls]\n  \n  insecureSkipVerify = \"true\"\n  \n[acme]\nemail = \"test@example.com\"\nstorage = \"traefik/acme/account\"\nOverrideCertificates = true\nentryPoint = \"https\"\nonHostRule = true\nacmeLogging = true\n  [acme.httpChallenge]\n  entryPoint = \"http\"\n[[acme.domains]]\n   main = \"k8stest.example.com\"\n"```

With some very basic parsing:
```
# traefik.toml
logLevel = "info"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
      regex = "^http://(.*)"
      replacement = "https://$1"
      permanent = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      minVersion = "1.1"
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
[ping]
entryPoint = "http"
[kubernetes]
[traefikLog]
  format = "json"
[accessLog]
  format = "json"
[accessLog.fields]
  defaultMode = "keep"
[accessLog.fields.names]
[accessLog.fields.headers]
  defaultMode = "keep"
[accessLog.fields.headers.names]
[consul]
endpoint = "http://consul:8500"
watch = true
prefix = "traefik"
  [consul.tls]
  
  insecureSkipVerify = "true"
  
[acme]
email = "test@example.com"
storage = "traefik/acme/account"
OverrideCertificates = true
entryPoint = "https"
onHostRule = true
acmeLogging = true
  [acme.httpChallenge]
  entryPoint = "http"
[[acme.domains]]
   main = "k8stest.example.com"
```

**Comment by KadenLNelson** [comment]
Yeah it seems like that function you referenced is causing the problem for sure. If you would like I could open the PR for fixing the error.

**Comment by mhbrooks** [comment]
It would be useful if you could create a PR. I had a look at doing it but not sure how to only skip the function for that one flag.

**Comment by KadenLNelson** [comment]
Oh, I see what you mean

> It would be useful if you could create a PR. I had a look at doing it but not sure how to only skip the function for that one flag.

Oh, I see what you mean. Yeah, I believe the only reasonable solution is just removing the `| quote` from all relevant `kvprovider.tls` definitions.

**Comment by mhbrooks** [comment]
Yep, that was my fear. Not ideal, thanks for your input though.
