### ISSUE TITLE
istio chart version should ideally not get ahead of istio version

### ISSUE THREAD

**Issue by ldemailly** [helm/charts#1501]
**Which chart**:
https://github.com/kubernetes/charts/blob/master/incubator/istio/Chart.yaml

**What happened**:
it says 0.3.0

**What you expected to happen**:
it's confusing to istio users as the istio latest release is 0.1.6, work is on the way for 0.2.x and planned for 0.3.x this makes it seem 0.3.0 is already out

can we have the chart version be 4 digits, the first 3 would be the istio version and a fourth digit for revisions of the chart itself ?

**Comment by ldemailly** [comment]
cc @lachie83

**Comment by lachie83** [comment]
@ldemailly thanks for calling this out. The appVersion field is for this purpose. The chart version follows it's own release numbering that's in no way related to the appVersion

**Comment by ldemailly** [comment]
do you have very strict policies on chart version scheme ? does it have to have 3 digits ? if not I would think it'd be a lot less confusing to align the versions. If you have completely independant versions then try something else that doesn't appear to almost match istio version

there is also a PR to send people to the chart for istio installation but we can't do that if the version don't match (imo)

**Comment by lachie83** [comment]
version must be SymVer 2 compliant. https://github.com/kubernetes/helm/blob/master/docs/charts.md#the-chartyaml-file

We bump this version every time the chart structure changes so that users have the opportunity to manage changes to charts over time independent to the application version.

We could change the number to something that's not obviously similar to the Istio release to avoid confusion. 

Do you have any other suggestions?

**Comment by lachie83** [comment]
We should also move the chart to stable if you plan on pointing users at it.

**Comment by ldemailly** [comment]
maybe use the label part of semv2 
ie 0.1.6-chart1 0.1.6-chart2 etc... and once the chart itself is stable enough it can converge to 0.1.6
(remember than in semv2 anything 0.y.z has no guarantees and can change at anytime so you don't actually have to change the 0.1 part when making structural changes, until we reach 1.0 - for istio we use the 2nd digit for project planning / big release cadence until 1.0 - somewhat controversially: https://groups.google.com/d/msg/istio-dev/meK74evKGDw/Vl-RbMtUBAAJ )

**Comment by ldemailly** [comment]
alternatively if you'd rather disconnect the 2 entirely maybe you can start at 0.9 (and when our 0.2 comes out, you'll be at 0.10 ?) it's still a bit confusing but better than 0.3 (though there is a chance we rename our 0.3 to 0.9 as well if we get closer to GA quality)

my preference is use the same prefix and add build/chart version numbers through -chart-X label

**Comment by lachie83** [comment]
@ldemailly I agree with you. Testing now. PR to follow.

**Comment by ldemailly** [comment]
thanks a lot for the quick fix!

**Comment by ldemailly** [comment]
preemptive quick note / just in case (not sure where to post this): please don't change to 0.2.x until after it's marked as a stable release, we are only starting to make test builds of 0.2.x and no release yet - thanks !

**Comment by lachie83** [comment]
Will do. Appreciate the heads up!
