### ISSUE TITLE
[stable/kong] Cannot install 0.3.X ingress controller version with helm

### ISSUE THREAD

**Issue by Ngob** [helm/charts#15021]
**Describe the bug**
When trying to set the version manually of the ingress controller, kong-ingress is crashing. The log message is "Please specify --default-backend-service"
I believe it is because when releasing the 0.4, the parameter `--default-backend-service` has been removed, so it is not specified in the helm chart anymore. I think the helm chart should handle this

**Version of Helm and Kubernetes**:

helm version:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Kubernete version: 

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:53:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.13", GitCommit:"fcbc1d20b6bca1936c0317743055ac75aef608ce", GitTreeState:"clean", BuildDate:"2019-06-19T20:50:07Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
 kong-0.12.1  

**What happened**:

Running `helm install stable/kong --name=kong --set ingressController.enabled=true --set proxy.externalTrafficPolicy=Local --set ingressController.image.tag=0.3.0   --namespace kong ` 

**What you expected to happen**:

Pods in namespace kong running normally

**How to reproduce it** (as minimally and precisely as possible):

Install kong via the chart using the 0.3 version of kong-ingress

**Comment by hbagdi** [comment]
This is due to a breaking change in Kong Ingress Controller 0.4.0.
Either use an older version of the chart or upgrade your Ingress Controller.

**Comment by Ngob** [comment]
Thanks,
In case someone have a similar issue, i fixed my issue with:
```
helm install stable/kong --name=kong --set ingressController.enabled=true --set ingressController.image.tag=0.3.0 --namespace kong --version v0.9.8
```
