### ISSUE TITLE
[stable/graylog] trusted_proxies referred to in the wrong place

### ISSUE THREAD

**Issue by forsberg** [helm/charts#15033]
**Describe the bug**
In values.yaml there's an example provisioning job that configures the SSO component, which is great and helped me, so thanks to @cablespaghetti 

However, at https://github.com/helm/charts/blob/8e09a65c7652025f5283f58bbf92eaffc29f5257/stable/graylog/values.yaml#L280 there's a trusted_proxy setting being added, but it's in the wrong place - trusted_proxy belongs in the Graylog configuration file. 

The end result is that with the example configuration the SSO plugin will complain that there's no trusted_proxy set, and therefore it won't work.

**Version of Helm and Kubernetes**: Helm 2.14.1, Kubernetes 1.12+ (EKS)

**Which chart**: stable/graylog

**Comment by cablespaghetti** [comment]
In my environment it is set there and in graylog.config:
```
  config: |
    trusted_proxies = 0.0.0.0/0
```
I got that list of properties for the JSON from the Graylog 2.5 API browser. I'm not certain what removing one of them will do, as I've not tried it.

**Comment by forsberg** [comment]
At least on 3.0, setting it via the JSON and the API call to the SSO plugin endpoint has no effect, the SSO plugin will just complain that there's no trusted_proxies configured.
