### ISSUE TITLE
[stable/prometheus-operator] chart incompatible with thanos > 0.5.0

### ISSUE THREAD

**Issue by swtch1** [helm/charts#15051]
**Describe the bug**
The latest version of Thanos ([v0.5.0](https://github.com/improbable-eng/thanos/releases/tag/v0.5.0)) "removes gossip with all configuration flags (--cluster.*)." The 

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-dispatcher", GitCommit:"1215389331387f57594b42c5dd024a2fe27334f8", GitTreeState:"clean", BuildDate:"2019-05-13T18:09:56Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.13", GitCommit:"fcbc1d20b6bca1936c0317743055ac75aef608ce", GitTreeState:"clean", BuildDate:"2019-06-19T20:50:07Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
prometheus-operator

**What happened**:
I configured the values.yaml with:
```
thanos: 
  baseImage: improbable/thanos
  version: v0.5.0
~~~
```

**What you expected to happen**:
Prometheus-operator to deploy with Thanos configured.

**What actually happened:**
The `thanos-sidecar` container enters a crash loop.

**How to reproduce it** (as minimally and precisely as possible):
Add Thanos values to the values.yaml file, specifying v0.5.0.
```
thanos:
  baseImage: improbable/thanos
  version: v0.5.0
  objectStorageConfig:
    key: config.yaml
    name: thanos-objectstore-config
```
Add a stub secret so you don't error on missing the objectstore config.
```
cat > config.yaml << EOF
type: GCS
config:
  bucket: "bkt123"
EOF

kubectl create secret generic thanos-objectstore-config --from-file=config.yaml
```

**Anything else we need to know**:
The core issue is the thanos-sidecar arg `--cluster.address=[$(POD_IP)]:10900`, which is incompatible with the latest version.  This arg can be seen in the `kubectl describe pod <prometheus-operator-pod>` output.

I honestly wanted to contribute here, but I'm having difficulty seeing where the args are being added for the thanos-sidecar container.  Is this inside the operator?  In that case is this an upstream issue?  Any direction here could help me, or other contributers, with troubleshooting.

**Comment by simon71** [comment]
This is caused by the crd's in V0.30.0 https://github.com/coreos/prometheus-operator/blob/18fbf558ab7f8809fd610a3dc50bf483508dc1bb/pkg/prometheus/statefulset.go#L682 it has been removed in v0.31.0.

**Comment by caarlos0** [comment]
this should be fixed now afaik
