### ISSUE TITLE
[stable/prometheus-operator] additionalPrometheusRules conflicts with additionalServiceMonitors

### ISSUE THREAD

**Issue by Morriz** [helm/charts#15064]
if we provide both `additionalPrometheusRules` as well as `additionalServiceMonitors` the helm merging of the templates does not work correctly, as it is trying to merge a `List` object. This now results in the items in the `prometheus.additionalServiceMonitors` list being replaced by the items in the `additionalPrometheusRules` list.

Now, this could be considered a Helm bug and I will create an issue there as well, but for now I propose to explicitly create `templates/prometheus/list.yaml` and iterate over both sections there, removing `templates/prometheus/additionalPrometheusRules.yaml` and `templates/prometheus/additionalPrometheusRules.yaml` as these are the only two using `kind: List`

**Comment by Morriz** [comment]
I don't think this is a helm bug actually, and this chart is making a mistake by using two template files to create the same `Kind: List` resource. My proposed solution is a necessary fix imo

**Comment by Morriz** [comment]
still an issue

**Comment by Morriz** [comment]
bump

**Comment by mausspb** [comment]
+1
