### ISSUE TITLE
[stable/rabbitmq] RABBITMQ_PASSWORD containing slashes can cause rabbitmq pod to fail to start

### ISSUE THREAD

**Issue by karolinepauls** [helm/charts#15069]
Culprit: https://github.com/helm/charts/blob/407ca2a8d7195473f16e7c74de90af247c4a2604/stable/rabbitmq/templates/statefulset.yaml#L96

Example password: `0cWCt8qyaX2irS4DHQd0JbVtGEZVS8gvmX/YwfCH`

Reason: sed interprets `/` in the password. `/` are likely to obtain by base64-ing strings.

**Which chart**:
stable/rabbitmq 6.1.1

**What happened**:

```
$ kubectl logs depl-stack-rabbitmq-0 rabbitmq    
sed: -e expression #1, char 47: unknown option to `s'
```

**What you expected to happen**:

Escape forward slashes. Rabbit can support forward slashes in passwords. https://www.rabbitmq.com/passwords.html

This worked form me locally. I can make a PR with this change if you like it:

Change this:
```
sed -i "s/CHANGEME/$RABBITMQ_PASSWORD/g" /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf
```

To:
```
sed -i "s/CHANGEME/${RABBITMQ_PASSWORD//\//\\/}/g" /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf
```

Alternative: Validate the password is alphanumeric. 

*But the real problem is using shell in 2019, in docker containers that we can fully control. The real solution would be adding a small, **sane**, and powerful enough shell language to binami base containers. We should collectively work towards abandoning old shell languages.*

**How to reproduce it** (as minimally and precisely as possible):

```
kubectl create secret generic rabbitmq-secret --from-literal=rabbitmq-password='AAA/AAA'
helm install --name my-release stable/rabbitmq --set rabbitmq.existingPasswordSecret=rabbitmq-secret --set persistence.storageClass=local-storage
kubectl logs my-release-rabbitmq-0 --follow
sed: -e expression #1, char 16: unknown option to `s'
```

**Comment by prasadus92** [comment]
I just encountered the same problem, with the usage of `existingPasswordSecret`.

**Comment by miguelaeh** [comment]
Hi,
Thank you very much for the PR, we will review it as soon as we can.

**Comment by carrodher** [comment]
This PR is just moving the problem, at this moment the command will fail using `|` in the password because it's the new delimiter. Unless there are some limitations at RabbitMQ level that doesn't allow certain characters in the password (if RabbitMQ exclude `|` as a valid character, the PR will work)

**Comment by karolinepauls** [comment]
Testing the best thing I could come up with - uses `/match/creplacement` to replace the whole line. Backslash is still interpreted by sed so i need to double it. But the resulting line is identical to the var.

```
$ VAR='A/\/\--||?+*A'
$ cat > file
111
222
333
^d
$ sed "/2/c${VAR//\\/\\\\}" file
111
A/\/\--||?+*A
333
```
