### ISSUE TITLE
stable/chart] Pods failing with no such file.

### ISSUE THREAD

**Issue by deepak71** [helm/charts#15072]
**Describe the bug**
While deploying Master-Slave sentinel cluster, their pods are failing with /run.sh: No such file or directory in both master & slave entrypoint.

**Version of Helm and Kubernetes**:
Helm: SemVer:"v2.13.1"
Major:"1", Minor:"14"

**Which chart**:
Redis master-slave sentinel deployment

**What happened**:

I'm trying to deploy Master-slave with Sentinel using below command:
helm install --name my-release-redis --set sentinel.image.registry="private-one",sentinel.image.repository="bitnami/redis-sentinel",sentinel.image.tag="latest",cluster.enabled=true,sentinel.enabled=true,master.persistence.storageClass=openebs-cstor,master.persistence.size=200M,slave.persistence.storageClass=openebs-cstor,slave.persistence.size=120M,image.registry="private-one",image.repository="bitnami/redis-sentinel",image.tag="latest" -f values.yaml  stable/redis --tiller-namespace=k8stest-solr --namespace=k8stest-solr
Output:
kubectl logs pod/my-release-redis-master-0 -n k8stest-solr --all-containers=true
/bin/bash: line 15: /run.sh: No such file or directory
1:X 26 Jun 2019 12:23:01.279 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:X 26 Jun 2019 12:23:01.279 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:X 26 Jun 2019 12:23:01.279 # Configuration loaded
1:X 26 Jun 2019 12:23:01.282 * Running mode=sentinel, port=26379.
1:X 26 Jun 2019 12:23:01.282 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:X 26 Jun 2019 12:23:01.287 # Sentinel ID is 0eea02acb2121f0bccd82f37ebe7e12aef8f54b4
1:X 26 Jun 2019 12:23:01.287 # +monitor master mymaster 10.244.3.73 6379 quorum 2
1:X 26 Jun 2019 12:24:01.330 # +sdown master mymaster 10.244.3.73 6379

kubectl logs pod/my-release-redis-slave-0 -n k8stest-solr --all-containers=true
/bin/bash: line 20: /run.sh: No such file or directory

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 4
>>> 'sentinel monitor mymaster my-release-redis-master-0.my-release-redis-headless.k8stest-solr.svc.cluster.local 6379 2'
Can't resolve master instance hostname.

**What you expected to happen**:
To be deployed master-slave sentinel cluster

**How to reproduce it** (as minimally and precisely as possible):
Used above command to deploy a redis  cluster on K8s cluster.

**Anything else we need to know**:
We're using our own docker registry and openebs as persistenance storage.

**Comment by miguelaeh** [comment]
Hi @deepak71 ,
I guess it could be related to your command. I am not sure if you can specify a `--set` option and also a `-f`, but in case this is possible as you put the `-f` after the `--set` maybe it overrides the values of the `--set` parameters.
```
To override values in a chart, use either the '--values' flag and pass in a file
or use the '--set' flag and pass configuration from the command line.  To force string
values in '--set', use '--set-string' instead. In case a value is large and therefore
you want not to use neither '--values' nor '--set', use '--set-file' to read the
single large value from file.

	$ helm install -f myvalues.yaml ./redis

or

	$ helm install --set name=prod ./redis

or

	$ helm install --set-string long_int=1234567890 ./redis

or
    $ helm install --set-file multiline_text=path/to/textfile

You can specify the '--values'/'-f' flag multiple times. The priority will be given to the
last (right-most) file specified. For example, if both myvalues.yaml and override.yaml
contained a key called 'Test', the value set in override.yaml would take precedence:

	$ helm install -f myvalues.yaml -f override.yaml ./redis

You can specify the '--set' flag multiple times. The priority will be given to the
last (right-most) set specified. For example, if both 'bar' and 'newbar' values are
set for a key called 'foo', the 'newbar' value would take precedence:

	$ helm install --set foo=bar --set foo=newbar ./redis


To check the generated manifests of a release without installing the chart,
the '--debug' and '--dry-run' flags can be combined. This will still require a
round-trip to the Tiller server.

If --verify is set, the chart MUST have a provenance file, and the provenance
file MUST pass all verification steps.
```
