### ISSUE TITLE
stable/redis-ha : Error for Sha1sum function 

### ISSUE THREAD

**Issue by praveen056** [helm/charts#15086]
When i am installing redis-ha through helm using helm install stable/redis-ha it throws me a error sh1sum is not defined. May be you need to modify the file templates/redis-ha-statefulset.yaml with sha256sum in place of sha1sum so that it will remove this error. Can you please check if it a bug or there is workaround solution

**Comment by DandyDeveloper** [comment]
The Statefulset uses a sha1sum but I can't reproduce this. 

What version of helm you using?

**Comment by praveen056** [comment]
i am using 2.7.0 version of helm . What i do is to clone the redis-ha on a server and replace it with sha256sum instead of sha1sum  and then install the redis-ha from that server and it installed but its state is currently CrashLoopBackOff . is it correct?

**Comment by ssalaues** [comment]
@praveen056 Your issue is your version of Helm is too old to support the sha1sum function. It was added in Helm v2.10. Try updating Helm and it should allow you to install without any errors.
