### ISSUE TITLE
[stable/fluentd] Support User/Pass Authentication & Certificate Validation

### ISSUE THREAD

**Issue by DandyDeveloper** [helm/charts#15085]
**Is your feature request related to a problem? Please describe.**
Typical production level ES machines scaling over multiple clusters require some form of authentication. In my case, using open-distro, I need both user/pass and client certification validation enabled. 

**Describe the solution you'd like**
We need to add the following:
 - Authentication section in values.
 - Certificates section in values

These will:
 - Mount a local template for the secrets
 - Mount to the directory specified by the user
 - Create environment variables
 - Reference environment variables in fluentd configuration.

**Describe alternatives you've considered**
Not applicable.

**Comment by DandyDeveloper** [comment]
This can be done via customer configuration / configmap for the time being. It's an acceptable solution for the time being.

**Comment by AmitBaranes** [comment]
@DandyDeveloper  Would you mind sharing an example?
