### ISSUE TITLE
how to access helm charts folder

### ISSUE THREAD

**Issue by mounaBoo** [helm/charts#15099]
hello I installed elasticsearch using helm chart , I want to enable security on it so I did what's mentioned on the documentation but I have probleme accessing the folder examples to run the make file to enable security features , so how can I access that file or where can I found it , and which command to use so I could get to that location ?

**Comment by bcollard** [comment]
Hello, did you git clone this repo? or only ran helm install ...?
I guess you need to build your own Helm release of the ES chart.
