### ISSUE TITLE
[stable/prometheus-operator] Make allowedCapabilities in PSP configurable

### ISSUE THREAD

**Issue by mwieczorek** [helm/charts#15091]
**Is your feature request related to a problem? Please describe.**

I'd like to add a sidecar to the prometheus pod (vault agent - to provide vault token which can be used then by serviceMonitor). Problem is that it won't start with PSP from templates (https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/psp.yaml) because it requires some additional capabilities.

**Describe the solution you'd like**

I'd like to be able to configure `allowedCapabilities` of the PSP in values file.
I can submit a PR, but first I'd like to get the feedback from maintainers if such a solution would be acceptable. Maybe more 'general' solution for modifying PSP should be added?

**Describe alternatives you've considered**
Patching PSP after chart installation.

**Comment by mwieczorek** [comment]
@gianrubio  @vsliouniaev  @anothertobi - could you take a look at it and give me feedback? thanks

**Comment by mwieczorek** [comment]
@gianrubio @vsliouniaev @anothertobi - will you find time to take a look? thanks

**Comment by Aisuko** [comment]
@mwieczorek Hi, Did you joined the Slack channel `charts`?  You can make a question on the channel, and I believe you would get more reply there.

**Comment by mwieczorek** [comment]
Hi @Aisuko, I thought my question would be too specific for slack channel, but thanks, I'll try also there

**Comment by vsliouniaev** [comment]
@mwieczorek I think that this would be a welcome addition, feel free to open a PR for it
