### ISSUE TITLE
[stable/prometheus-operator] filesystem paths displayed in prometheus alerts web tab

### ISSUE THREAD

**Issue by alexsn** [helm/charts#15117]
**Describe the bug**
/etc/prometheus/rules filesystem paths are displayed in Prometheus `Alerts` tab, see attached screenshot.

**Screenshot**
<img width="1658" alt="Screen Shot 2019-06-28 at 13 14 42" src="https://user-images.githubusercontent.com/987019/60335745-494ecd00-99a7-11e9-8bd5-41a8563f85d9.png">

**Version of Helm and Kubernetes**:
> kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
> helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

**Which chart**:
stable/prometheus-operator

**How to reproduce it** (as minimally and precisely as possible):
I've updated prometheus-operator from 5.12.5 -> 5.14.0

**Comment by acaire** [comment]
Introduced first by [5.14.0](https://github.com/helm/charts/commit/d58247103fafd5930792bb1fd3ac240547523200#diff-b9f481ac97524bfb24d27f62676dc143) due to a `quay.io/prometheus/prometheus` image update from `v2.9.1` to `v2.10.0`.

Current work-around is to drop back to `v2.9.1`:
```
prometheus:
  prometheusSpec:
    image:
      tag: v2.9.1
```

Still looking for the cause
