### ISSUE TITLE
[stable/chart]: Old master failing to join the redis cluster as a slave

### ISSUE THREAD

**Issue by deepak71** [helm/charts#15115]
**Describe the bug**
When current master fails, running slaves elected new master but old master not joining the Redis cluster as slave. This leading to two master under the Redis service.

**Version of Helm and Kubernetes**:
Helm: SemVer:"v2.13.1"
Major:"1", Minor:"14"

**Which chart**:
Redis master-slave sentinel deployment

**What happened**:
To test master failover functionality of sentinel cluster when current master went down then one of the slave steps in as new master for the Redis cluster. We've three Redis instances and one acts as master and other two are in slave modes in the cluster.

Steps: Kept killing the pod that acting as a master or scale the master replicas to zero.

Result: when master pod is failed, write functionality is suspended (until Time for detecting a Redis node is down + Timeout for performing a election failover), but reads are allowed during this time. But, when old master joins the cluster, its joining as a master only. Basically, we resulted into two masters in the cluster and both takes writes its like cluster go in split brain condition.

**What you expected to happen**:
Old master should join the cluster as a slave instance as already redis cluster has current master.

**How to reproduce it** (as minimally and precisely as possible):
Redis master replica reduce to zero. Or Kept killing the master node.

**Anything else we need to know**:

**Comment by javsalgar** [comment]
Hi,

Could you show the "lost master" logs? At the beginning it would try querying the sentinel service to know which the new master is. I would like to know what went wrong

**Comment by deepak71** [comment]
**Our redis status before master failover:**

NAME                                        READY   STATUS             RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
my-release-redis-client                     1/1     Running            0          3d19h   10.244.3.98    dev-k8stest-worker-lx02   <none>           <none>
my-release-redis-master-0                   2/2     Running            0          2d17h   10.244.3.117   dev-k8stest-worker-lx02   <none>           <none>
my-release-redis-metrics-68989cd4c4-ndrj4   1/1     Running            0          2d17h   10.244.4.149   dev-k8stest-worker-lx03   <none>           <none>
my-release-redis-slave-0                    2/2     Running            2          2d17h   10.244.4.150   dev-k8stest-worker-lx03   <none>           <none>
my-release-redis-slave-1                    2/2     Running            0          2d17h   10.244.3.118   dev-k8stest-worker-lx02   <none>           <none>


**After stopping master replica, redis cluster promoted one of its slave to master and we received following logs on live nodes:**

1:S 01 Jul 2019 07:19:06.412 # Connection with master lost.
1:S 01 Jul 2019 07:19:06.412 * Caching the disconnected master state.
1:S 01 Jul 2019 07:19:06.568 * Connecting to MASTER 10.244.3.117:6379
1:S 01 Jul 2019 07:19:06.568 * MASTER <-> REPLICA sync started
1:S 01 Jul 2019 07:19:06.568 # Error condition on socket for SYNC: Connection refused
1:S 01 Jul 2019 07:19:07.573 * Connecting to MASTER 10.244.3.117:6379
1:S 01 Jul 2019 07:19:07.573 * MASTER <-> REPLICA sync started
1:X 01 Jul 2019 07:19:36.338 # +sdown sentinel a57d234f594f134634d10ff96a055a4b6fbb484c 10.244.3.117 26379 @ mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:36.470 # +sdown master mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:36.533 # +odown master mymaster 10.244.3.117 6379 #quorum 2/2
1:X 01 Jul 2019 07:19:36.533 # +new-epoch 1
1:X 01 Jul 2019 07:19:36.533 # +try-failover master mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:36.586 # +vote-for-leader 3f84a2b60caca32d76f53d521227eacae46c0b1a 1
1:X 01 Jul 2019 07:19:36.634 # 69d93545210e4861f45e537db22a39f39e2bc142 voted for 3f84a2b60caca32d76f53d521227eacae46c0b1a 1
1:X 01 Jul 2019 07:19:36.669 # +elected-leader master mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:36.669 # +failover-state-select-slave master mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:36.736 # +selected-slave slave 10.244.3.118:6379 10.244.3.118 6379 @ mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:36.736 * +failover-state-send-slaveof-noone slave 10.244.3.118:6379 10.244.3.118 6379 @ mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:36.798 * +failover-state-wait-promotion slave 10.244.3.118:6379 10.244.3.118 6379 @ mymaster 10.244.3.117 6379
1:M 01 Jul 2019 07:19:36.798 # Setting secondary replication ID to 0e1f0d3900a7d64d63e07997b2d03ed853b8f28a, valid up to offset: 48811858. New replication ID is a78db8b62f08019ec6e26651d600f5cfbc7c5004
1:M 01 Jul 2019 07:19:36.798 * Discarding previously cached master state.
1:M 01 Jul 2019 07:19:36.799 * MASTER MODE enabled (user request from 'id=4 addr=10.244.3.118:39695 fd=8 name=sentinel-3f84a2b6-cmd age=236807 idle=0 flags=x db=0 sub=0 psub=0 multi=3 qbuf=140 qbuf-free=32628 obl=36 oll=0 omem=0 events=r cmd=exec')
1:M 01 Jul 2019 07:19:36.841 # CONFIG REWRITE executed with success.
1:X 01 Jul 2019 07:19:37.617 # +promoted-slave slave 10.244.3.118:6379 10.244.3.118 6379 @ mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:37.617 # +failover-state-reconf-slaves master mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:37.677 * +slave-reconf-sent slave 10.244.4.150:6379 10.244.4.150 6379 @ mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:38.445 * +slave-reconf-inprog slave 10.244.4.150:6379 10.244.4.150 6379 @ mymaster 10.244.3.117 6379
1:M 01 Jul 2019 07:19:38.481 * Replica 10.244.4.150:6379 asks for synchronization
1:M 01 Jul 2019 07:19:38.481 * Partial resynchronization request from 10.244.4.150:6379 accepted. Sending 301 bytes of backlog starting from offset 48811858.
1:X 01 Jul 2019 07:19:38.792 # -odown master mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:39.485 * +slave-reconf-done slave 10.244.4.150:6379 10.244.4.150 6379 @ mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:39.536 # +failover-end master mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:39.536 # +switch-master mymaster 10.244.3.117 6379 10.244.3.118 6379
1:X 01 Jul 2019 07:19:39.537 * +slave slave 10.244.4.150:6379 10.244.4.150 6379 @ mymaster 10.244.3.118 6379
1:X 01 Jul 2019 07:19:39.537 * +slave slave 10.244.3.117:6379 10.244.3.117 6379 @ mymaster 10.244.3.118 6379
1:X 01 Jul 2019 07:20:09.550 # +sdown slave 10.244.3.117:6379 10.244.3.117 6379 @ mymaster 10.244.3.118 6379

**Another slave node logs:**

1:S 01 Jul 2019 07:19:06.413 # Connection with master lost.
1:S 01 Jul 2019 07:19:06.756 * Caching the disconnected master state.
1:S 01 Jul 2019 07:19:07.359 * Connecting to MASTER 10.244.3.117:6379
1:S 01 Jul 2019 07:19:07.359 * MASTER <-> REPLICA sync started
1:X 01 Jul 2019 07:19:36.314 # +sdown master mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:36.402 # +sdown sentinel a57d234f594f134634d10ff96a055a4b6fbb484c 10.244.3.117 26379 @ mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:36.634 # +new-epoch 1
1:X 01 Jul 2019 07:19:36.635 # +vote-for-leader 3f84a2b60caca32d76f53d521227eacae46c0b1a 1
1:X 01 Jul 2019 07:19:37.485 # +odown master mymaster 10.244.3.117 6379 #quorum 2/2
1:X 01 Jul 2019 07:19:37.485 # Next failover delay: I will not start a failover before Mon Jul  1 07:20:12 2019
1:S 01 Jul 2019 07:19:37.679 * REPLICAOF 10.244.3.118:6379 enabled (user request from 'id=15 addr=10.244.3.118:47147 fd=9 name=sentinel-3f84a2b6-cmd age=236806 idle=0 flags=x db=0 sub=0 psub=0 multi=3 qbuf=291 qbuf-free=32477 obl=36 oll=0 omem=0 events=r cmd=exec')
1:S 01 Jul 2019 07:19:37.681 # CONFIG REWRITE executed with success.
1:X 01 Jul 2019 07:19:37.679 # +config-update-from sentinel 3f84a2b60caca32d76f53d521227eacae46c0b1a 10.244.3.118 26379 @ mymaster 10.244.3.117 6379
1:X 01 Jul 2019 07:19:37.679 # +switch-master mymaster 10.244.3.117 6379 10.244.3.118 6379
1:X 01 Jul 2019 07:19:37.680 * +slave slave 10.244.4.150:6379 10.244.4.150 6379 @ mymaster 10.244.3.118 6379
1:X 01 Jul 2019 07:19:37.680 * +slave slave 10.244.3.117:6379 10.244.3.117 6379 @ mymaster 10.244.3.118 6379
1:S 01 Jul 2019 07:19:38.481 * Connecting to MASTER 10.244.3.118:6379
1:S 01 Jul 2019 07:19:38.481 * MASTER <-> REPLICA sync started
1:S 01 Jul 2019 07:19:38.481 * Non blocking connect for SYNC fired the event.
1:S 01 Jul 2019 07:19:38.482 * Master replied to PING, replication can continue...
1:S 01 Jul 2019 07:19:38.483 * Trying a partial resynchronization (request 0e1f0d3900a7d64d63e07997b2d03ed853b8f28a:48811858).
1:S 01 Jul 2019 07:19:38.483 * Successful partial resynchronization with master.
1:S 01 Jul 2019 07:19:38.483 # Master replication ID changed to a78db8b62f08019ec6e26651d600f5cfbc7c5004
1:S 01 Jul 2019 07:19:38.483 * MASTER <-> REPLICA sync: Master accepted a Partial Resynchronization.
1:X 01 Jul 2019 07:20:07.711 # +sdown slave 10.244.3.117:6379 10.244.3.117 6379 @ mymaster 10.244.3.118 6379``

**Now bring up the old master and expected to join the cluster as slave but it didn't occur. Please find the logs:**

1:X 01 Jul 2019 07:27:51.518 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:X 01 Jul 2019 07:27:51.518 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:X 01 Jul 2019 07:27:51.518 # Configuration loaded
1:X 01 Jul 2019 07:27:51.519 * Running mode=sentinel, port=26379.
1:X 01 Jul 2019 07:27:51.519 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:X 01 Jul 2019 07:27:51.527 # Sentinel ID is 73dca9021cdb8a57f1b120bb968ab302f643d734
1:X 01 Jul 2019 07:27:51.527 # +monitor master mymaster 10.244.3.120 6379 quorum 2
INFO  ==> ** Starting Redis **
1:C 01 Jul 2019 07:27:50.868 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 01 Jul 2019 07:27:50.868 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 01 Jul 2019 07:27:50.868 # Configuration loaded
1:M 01 Jul 2019 07:27:50.871 * Running mode=standalone, port=6379.
1:M 01 Jul 2019 07:27:50.871 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 01 Jul 2019 07:27:50.871 # Server initialized
1:M 01 Jul 2019 07:27:50.871 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 01 Jul 2019 07:27:50.873 * Reading RDB preamble from AOF file...
1:M 01 Jul 2019 07:27:50.873 * Reading the remaining AOF tail...
1:M 01 Jul 2019 07:27:50.873 * DB loaded from append only file: 0.002 seconds
1:M 01 Jul 2019 07:27:50.873 * Ready to accept connections

**Comment by javsalgar** [comment]
Hi,

It seems that the error is caused by this commit  https://github.com/helm/charts/commit/daaff5ef5590ab65ecfd7b6471986bf878199474#diff-bff5387866dba6e2bb69e1feba09ea9b. @sameersbn could you take a look?

**Comment by sameersbn** [comment]
Hi @deepak71  I've submitted a fix in https://github.com/helm/charts/pull/15258.
