### ISSUE TITLE
[stable/fluentd] stop enforcing elasticsearch as standart output

### ISSUE THREAD

**Issue by bcollard** [helm/charts#15114]
This chart uses the 'fluentd-elasticsearch' docker image. 
These image and chart don't allow to use other input / output plugins when they are not built-in with basic fluentd. I'm thinking about the list of available plugin to download and install via (fluent-)gem CLI.

For example, if I want to use the plugin 'fluent-plugin-amqp', I have start from scratch, ie. from the official fluent/fluentd image, gem install this plugin, then I have to build my own Helm chart.
That's not what I was expecting when I first saw this stable/fluentd chart. This one should replace the current stable/fluentd-elasticsearch, as this latter is now deprecated.

So, I think this fluent chart should not be so much opinionated with elasticsearch and let people use other plugins easily.

Maybe I'm missing something, let me know.

**Comment by mattshin** [comment]
If I am understanding you correctly, you should be able to create a "drop-in replacement" docker image and overwrite `.Values.image.repository`. You will still need to replace some of the elasticsearch-specific configuration, but at least you get the rest of the stuff without having to start from scratch.

**Comment by bcollard** [comment]
Well, this is what I actually did.
I was just not expecting so strong relationship with elasticsearch, given the name of this chart.

Also, still in my case, I have an output with the "file" plugin. So I'm transforming this deployment into a statefulset.
Good luck to everyone in similar situation.

**Comment by mattshin** [comment]
FWIW, I do agree that this chart should probably be renamed to better convey it's tight coupling with Elasticsearch, maybe if I have some time I can create a PR.

**Comment by isaacegglestone** [comment]
The chart becomes a lot less useful when it can't auto install plugins.
Even if your backend is elasticsearch there are numerous other plugins (Thousands). for input and output that one one would still want to use to integrate everything. 
Why not just add some code to allow for plugin install when the container launches.
Other charts do this kind of thing.
