### ISSUE TITLE
[incubator/jaeger] passwords should be in a secret and used via secretKeyRef.

### ISSUE THREAD

**Issue by naseemkullah** [helm/charts#15122]
Please see title.

**Comment by mentalblock** [comment]
I think in the current form this breaks my use case with Elasticsearch.

I do not use a password with ElasticSearch and now I must use `usePassword: false` in my values file. This prevents the creation of the elasticsearch secret at https://github.com/helm/charts/blob/80f5d310e20868fa0900e64664cbffc625ab404e/incubator/jaeger/templates/elasticsearch-secret.yaml#L1.

The problem with not creating the kubernetes secret is that it is still referenced in the deployment of the collector at https://github.com/helm/charts/blob/80f5d310e20868fa0900e64664cbffc625ab404e/incubator/jaeger/templates/collector-deploy.yaml#L73-L77. This causes the container not to start up. Perhaps it would work if there was a new conditional in the deployment would be broader in scope to not reference any secret at all if `usePassword: false`.

**Comment by naseemkullah** [comment]
Thanks for pointing this out in detail @mentalblock ... i've created https://github.com/helm/charts/pull/15367 can you please let me know if you think this will solve the issue?

**Comment by mentalblock** [comment]
I believe that is the correct solution. Thank you for the quick response and fix.

**Comment by naseemkullah** [comment]
merged!
