### ISSUE TITLE
[stable/grafana] syntax error in deployment.yaml in grafana 3.5.6

### ISSUE THREAD

**Issue by rshutt** [helm/charts#15134]
**Describe the bug**
Today, a new helm chart for grafana was release.  This was in it:

https://github.com/helm/charts/blob/9e0d2f23ced8ee73f51a09420b45b097bc89ab04/stable/grafana/templates/deployment.yaml#L78

It caused the YAML parser much chagrin.  Those quotes around the key name are no bueno.  The next line "args": also has the same issue.  Seems like it may have been a bug in converting from JSON to YAML?

**Version of Helm and Kubernetes**:
v2.14.1 and EKS v1.12.6

**Which chart**:  grafana

**What happened**:  YAML parser fail, doesn't install, rolled back to 3.5.4 I believe from 3.5.6

**What you expected to happen**: Things installed

**How to reproduce it** (as minimally and precisely as possible):  Just try to do a `helm install grafana/stable -n grafana --namespace grafana` and watch it go.  Make sure do do the repo update and the delete --purge first.

**Anything else we need to know**:  Not really.

**Comment by obeyler** [comment]
Sorry it's due to my last PR I don't understand why some "" have been added 
I'll fix that quikly
