### ISSUE TITLE
[stable/redis] Collect metrics from Sentinel service

### ISSUE THREAD

**Issue by sykorax** [helm/charts#15145]
**Is your feature request related to a problem? Please describe.**
When setting both metrics and sentinel true then the related exporter container (oliver006/redis_exporter) is still configured to grab statistics from the redis master and slave(s).

**Describe the solution you'd like**
I decided to do some research and found a solution to make this work. I had to explicitly set the metrics.extraArgs.[redis.addr] on the container and it finally used the sentinel service for collecting metrics.

**Describe alternatives you've considered**
Is it possible to make this fully automated while installing / upgrading charts?
When setting both metrics and sentinel to true then the exporter should use the sentinel service endpoint automatically.

**Comment by juan131** [comment]
Hi @sykorax 

I guess it's a matter of modifying the template in the lines below:

https://github.com/helm/charts/blob/master/stable/redis/templates/metrics-deployment.yaml#L55

Do you want to do a PR or would you rather me to do it?

**Comment by sykorax** [comment]
I'm new at k8s and helm and don't know much about templates. :/

**Comment by juan131** [comment]
No problem @sykorax ! I just created a PR addressing it

**Comment by sykorax** [comment]
Thank you :)
