### ISSUE TITLE
[stable/sealed-secrets] Chart doesn't work out of the box without specific Helm release name

### ISSUE THREAD

**Issue by Overv** [helm/charts#15161]
**Describe the bug**
If one deploys the `stable/sealed-secrets` chart with a release name other than `sealed-secrets-controller`, then the `kubeseal` command will not be able to find it by default. That's because the service is named after the Helm release and `kubeseal` expects this service to be named `sealed-secrets-controller` by default. It will fail with this error if it is named differently, e.g. `my-release`:

```
$ kubeseal version
panic: Error fetching certificate: services "sealed-secrets-controller" not found

goroutine 1 [running]:
main.main()
        /home/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/cmd/kubeseal/main.go:216 +0x3b9
```

The only way to avoid this is to explicitly specify it like so:

```
$ kubeseal --controller-name=my-release version
```

This is unintuitive for users of `kubeseal`.

**Version of Helm and Kubernetes**: Not relevant

**Which chart**: `stable/sealed-secrets`

**What happened**: See previous.

**What you expected to happen**: The [README](https://github.com/helm/charts/tree/master/stable/sealed-secrets) should recommend that the Helm release is always named `sealed-secrets-controller` to avoid unexpected problems with `kubeseal`.

**How to reproduce it** (as minimally and precisely as possible): See previous.

**Anything else we need to know**: Nothing.

**Comment by demisx** [comment]
Just ran into the same issue myself. It is confusing. Per author, this is what you have to 

```sh
helm install \
  --namespace kube-system \
  --name sealed-secrets-controller \ # <- Must set this release name for kubeseal to work w/o specifying controller name
  stable/sealed-secrets 
```

**Comment by Overv** [comment]
How do we get someone to pick this up?

**Comment by demisx** [comment]
Maybe current owners @olib963 or @stefanprodan could advise?
