### ISSUE TITLE
[stable/influxdb] Allow customization of livenessProbe & readinessProbe path

### ISSUE THREAD

**Issue by seils** [helm/charts#15165]
Rehash of issue #11878.

Currently influxdb's deployment is hard coding readinessProbe to be /ping. Influxdb respond /ping with a HTTP 204. It's fine for kubernetes to mark the pod as ready but when using in GKE ingress the health check by GLBC always expect a 200 response and it's not configurable.

While influxdb having a verbose endpoint for readinessProbe: /ping?verbose=true, the chart doesn't allow user to specify a value for readinessProbe. Thus requesting this to be configurable.

**Comment by Aisuko** [comment]
We strongly recommend that the end-user try to deploy the official `influxdb` charts. And the `stable/influxdb` has been not under maintain.
