### ISSUE TITLE
[stable/minio] service account is not created by default

### ISSUE THREAD

**Issue by Uvedale** [helm/charts#15188]
**Describe the bug**
A new setting was recently added to specify the service account name for minio with a default option to create the associated service account, however, nothing honours the "create" flag.

**Version of Helm and Kubernetes**:
Helm: v2.13.0
Kubernetes: v1.12.9

**Which chart**:
stable/minio

**What happened**:
I installed the minio chart and no minio pods were created because the associated service account is missing.

**What you expected to happen**:
Minio to start up successfully

**How to reproduce it** (as minimally and precisely as possible):
Install the latest version of minio

**Anything else we need to know**:
The breaking change was made in: https://github.com/helm/charts/pull/14917

**Comment by Uvedale** [comment]
@tylercamp could you have a look at this?

**Comment by tylercamp** [comment]
@Uvedale A pull request has been made and is pending a merge (which I don't have permissions to do) https://github.com/helm/charts/pull/15143

**Comment by tylercamp** [comment]
In the meantime can specify version 2.4.16 which does not have the service account reference

**Comment by Uvedale** [comment]
Thanks @tylercamp . Yeah I've pinned my version and all is well.

**Comment by tylercamp** [comment]
@Uvedale Pull request was merged, try again with latest

**Comment by szemkhel** [comment]
I think i have same issue when using stable. Replica set reports:

> Error creating: pods "s3-minio-58969f6fdc-" is forbidden: error looking up service account gitlab/s3-minio: serviceaccount "s3-minio" not found 

Reproduce:
`helm delete s3 --purge && helm install --namespace gitlab --name s3 --set persistence.existingClaim=pv-gitlab-storage stable/minio`

**Comment by tylercamp** [comment]
I can only think of tiller RBAC not being set to allow SA modifications, SA declaration uses `{{ .Release.Namespace }}` so it should be made under your `gitlab` namespace

Does `kubectl get sa -n gitlab` show any service accounts?

**Comment by szemkhel** [comment]
Now it is, but only because I have replicated helm chart workaround in form of minio-account.yaml:
`apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: gitlab`

`kubectl apply -f minio-account.yaml`

Account was not created by helm by default. Is permission to allow SA modifications default in Tiller setup?

**Comment by tylercamp** [comment]
@szemkhel It depends on the default RBAC permissions for your cluster

Try running `helm install <... other opts ...> --dry-run --debug` and check if the service account YAML is included in the generated output.

Alternatively, you can add `--set serviceAccount.create=false` so it doesn't try to create a service account. When no SA name is provided and it's not set to make a service account, it'll revert to `default`

**Comment by tylercamp** [comment]
I had set `serviceAccount.create=true` as default so that the chart would do a more "complete"/"correct" install as default behavior, but for backwards compatibility and cases like this I'm wondering if it's better to leave that default as `false`

👍 / 👎 on this comment and I guess we'll see preference?
