### ISSUE TITLE
[incubator/fluentd-cloudwatch] Be able to specify busybox image registry

### ISSUE THREAD

**Issue by joan-s-molas** [helm/charts#15232]
Currently the daemonset attempts to pull a busybox image from dockerhub - this can be an issue if we are deploying this chart in worker nodes that have no egress access to the internet or rely completely on private registries, such as AWS ECR, due to compliance or security issue.

It would be nice to be able to specify the repo for the busybox image in the values file.

**Comment by joan-serra** [comment]
#15353 would fix this
