### ISSUE TITLE
stable/nginx-ingress issue 

### ISSUE THREAD

**Issue by MarcoSchaar** [helm/charts#15249]
Hi
while using latest version for ingress-controller facing issues 

render error in "nginx-ingress/templates/controller-service.yaml": template: nginx-ingress/templates/controller-service.yaml:66:13

might be related to latest commit
https://github.com/helm/charts/commit/9ad9667545e58ec3f8cdfa5d7c78de7c2abd6a9a

**Comment by orzarchi** [comment]
happens here also, I've had to downgrade for now

**Comment by Aisuko** [comment]
Hello guys, thanks for your make the feedback on the issue. Would you like to paste your value.yaml there?  This may helpful

**Comment by MarcoSchaar** [comment]
Hi @Aisuko 
I dont use a dedicated yam file for values ... deployment in my case is done like this

helm install stable/nginx-ingress 
--version=<version>
--namespace <namespace> 
--name <release-name> 
--set controller.ingressClass=nginx-internal 
--set rbac.create=true 
--set controller.service.loadBalancerIP=<IP>
--set controller.service.annotations."nginx\.org/client-max-body-size"=64M 
--set defaultBackend.enabled=false 
--set controller.defaultBackendService=<namespace>/<service> 
--set controller.extraArgs.default-ssl-certificate=<namespace>/<service> 
--set tcp.<port>=<namespace>/<service>:<port>

**Comment by ChiefAlexander** [comment]
Could you try updating your repos `helm repo update` so that you can use the latest version 1.8.1? I believe this was already fixed by https://github.com/helm/charts/pull/15236

**Comment by MarcoSchaar** [comment]
great:)
can confirm version 1.8.1 fixed the issue
