### ISSUE TITLE
[Redis] Why using Deployment for Redis

### ISSUE THREAD

**Issue by gyliu513** [helm/charts#1524]
**Is this a request for help?**:
Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
Master

**Which chart**:
Redis

**What happened**:
I found that there are two ways to deploy a Redis cluster, one is in openshift, it is using statefulset https://github.com/openshift/origin/blob/master/examples/statefulsets/redis/redis.yaml

And another is in Kuberntes helm charts, it is using Deployment + Service to deploy the Redis cluster https://github.com/kubernetes/charts/tree/master/stable/redis/templates

Using statefulset can make sure the hostname of redis will never change even after redis restart, and the application can always use hostname to access redis.

Using deployment and service can enable other applications using service to access the redis, which also works even after the redis restart.

Does there are any recommendations for which one is better, or this depend on user scenarios?

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by edevil** [comment]
@gyliu513 I'm curious as well about advantages/disadvantages of these 2 scenarios. Did you reach a conclusion?

**Comment by gyliu513** [comment]
@edevil statefulset maybe better, as it can help for the upgrade case, hostname will not be changed. you can get more discussion here https://groups.google.com/forum/#!searchin/kubernetes-dev/Why$20using$20Deployment$20for$20Redis/kubernetes-dev/Dtywct7Ukq0/vvvIpgicCAAJ ,
