### ISSUE TITLE
[stable/redis] error: failed switching to "redis": unable to find user redis: no matching entries in passwd file

### ISSUE THREAD

**Issue by MohammedFadin** [helm/charts#15246]
**Describe the bug**
Master and Slave pods keep crashing due to the below error.

**Version of Helm and Kubernetes**: Kubernetes: v1.14, Helm v2.9.1

**Which chart**: stable/redis

**What happened**:
```
Mohammeds-MacBook-Pro:further-exchange mfadin$ kubectl logs gogs-redis-master-1
INFO  ==> ** Starting Redis **
error: failed switching to "redis": unable to find user redis: no matching entries in passwd file

Mohammeds-MacBook-Pro:further-exchange mfadin$ kubectl logs gogs-redis-slave-0
INFO  ==> ** Starting Redis **
error: failed switching to "redis": unable to find user redis: no matching entries in passwd file
```

**What you expected to happen**: Pods to run

**How to reproduce it** (as minimally and precisely as possible):
```
helm upgrade  --tls gogs-redis --set master.persistence.size=20Gi --set master.persistence.storageClass=ibmc-file-bronze --set securityContext.enabled=true --set securityContext.fsGroup=0 --set securityContext.runAsUser=0  --set volumePermissions.enabled=true  stable/redis
```
**Anything else we need to know**: None

**Comment by miguelaeh** [comment]
Hi @MohammedFadin ,
Thank you very much for reporting the issue. I can replicate it and it seems it happens when you deploy the Chart as root. But also I can see it doesn't appear when using docker-compose as root.
We will investigate the issue and let you know about the workaround.
Again, thank you for reporting.

**Comment by miguelaeh** [comment]
Hi @MohammedFadin ,
Is there any reason you have to run Redis as root?
You can see in the documentation the following:
> Redis does not requires root privileges to run. It is recommended to run it as an unprivileged redis user that is only used for this purpose.

**Comment by MohammedFadin** [comment]
Thank you @miguelaeh !

Our Volume Storage requires root user privileges only to read and write.

**Comment by miguelaeh** [comment]
Hi @MohammedFadin ,
When that PR will be merged it should solve your problem.
Thank you again for reporting.
