### ISSUE TITLE
[stable/rabbitmq-ha] with statically created local volumes.

### ISSUE THREAD

**Issue by Antiarchitect** [helm/charts#15294]
**Is your feature request related to a problem? Please describe.**
I want to build up a rabbitmq-ha cluster over manually provisioned bare-metal machines with no persistent volume layer driver installed (like openEBS, Ceph, etc.). So I stick with `local` volumes pre-created beforehand which could not be provisioned via PVC as stated in the docs.

**Describe the solution you'd like**
I want to cover the case when persistence is actually needed (https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/templates/statefulset.yaml#L312..L315) but is meant to be provided by already existing volumes. If we come to an agreement on how to do that (probably `existingVolumes` like in many other charts I saw) I can make a pull request.

**Comment by steven-sheehy** [comment]
Not sure exactly what you're suggesting to change, maybe provide a link to an example? As I understand it, any change to the statefulset spec would be applied to all pods. So you can't reference an existing volume in a statefulset and scale past 1.

Why not just use https://github.com/rancher/local-path-provisioner to create PVCs?

**Comment by Antiarchitect** [comment]
Will think about local-path-provisioner.
