### ISSUE TITLE
[stable/openldap] can't setup LDAP_REPLICATION 

### ISSUE THREAD

**Issue by smirnov-mi** [helm/charts#15293]
Hi guys

I'm trying to create a multi-master setup of the openldap chart on my k8s (v1.14.3) cluster.
It just doesn't work. 

**Version of Helm and Kubernetes**:
k8s: v1.14.3
helm: v2.13.1
chart: openldap 0.2.4

**What happened**:
How-to says "just set LDAP_REPLICATION: "true" and that's it". Doesn't work. Container just won't start. Last entry in the containers log is "slapd crashed with exit code 1". I tried a lot of things, and It looks like the LDAP_REPLICATION_HOSTS" variable is missing. When I define it manually, pods would start, but don't try to sync (as my variable contains dummy names, I don't know how to put newly created pods names in there).
 
Pod'S logs:

*** Running /container/run/process/slapd/run...
5d21c393 @(#) $OpenLDAP: slapd  (Feb  9 2019 17:02:42) $
        Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
5d21c393 read_config: no serverID / URL match found. Check slapd -h arguments.
5d21c393 slapd stopped.
5d21c393 connections_destroy: nothing to destroy.
*** /container/run/process/slapd/run exited with status 1
*** Killing all processes...

**What you expected to happen**:
Few pods (# of replicas) would start and will syncronize LDAP data between themselves.

**How to reproduce it** (as minimally and precisely as possible):
Just set the  replicaCount: 2 , setup some storage and install the chart 

**Anything else we need to know**:
I use persistent volumes on local filesystems. 
I use phpLdapAdmin on the same k8s cluster to access the openldap.
I tried container images: 1.2.2 1.2.4-dev 1.2.4
With "replicaCount: 1" everything is fine, one container starts and works.

**Comment by smirnov-mi** [comment]
Update: I just tried it from the scratch. Just changed the replicaCount=3.   Got three pods started, but they don't replicate anything. Environment in the containers do NOT contain an "LDAP_REPLICATION=true" so I added it to the values.yaml.    In this case pods crash with 
 
 
Link /container/service/:ssl-tools/assets/default-ca/default-ca.pem to /container/service/slapd/assets/certs/ca.crt
Start OpenLDAP...
*** /container/run/startup/slapd failed with status 1

**Comment by abdennour** [comment]
I got the same issue. It works only after `helm install`
But  after the first `helm upgrade`, it crashes `CrashLoopBackOff`

and `k logs -f  ` gives :
```
Link /container/run/service/:ssl-tools/assets/default-ca/default-ca.pem to /container/run/service/slapd/assets/certs/ca.crt
Start OpenLDAP...
Waiting for OpenLDAP to start...
Add TLS config...
Disable replication config...
*** /container/run/startup/slapd failed with status 50

*** Killing all processes...
```
