### ISSUE TITLE
stable/kiam Wrong TSL certificate DNS name

### ISSUE THREAD

**Issue by gerganadzhumerkova** [helm/charts#15313]
In [the template generating the TSL certificate](https://github.com/helm/charts/blob/567501aecfce4924ebc092ad64e5b895f8a7bfbe/stable/kiam/templates/_helpers.tpl#L104), **kiam.name** is used as part of the DNS name.

In [the agent daemonset](https://github.com/helm/charts/blob/567501aecfce4924ebc092ad64e5b895f8a7bfbe/stable/kiam/templates/agent-daemonset.yaml#L93), the server address parameter passed to the container uses **kiam.fullname**.

If these two are different, the agent is not able to connect to the server due to the difference in the DNS name the agent tries and the one in the certificate.

**Comment by belminf** [comment]
@gerganadzhumerkova did this address your issue or am I misunderstanding the problem you're pointing at?

https://github.com/helm/charts/commit/74dbc3ac89a0aa57a3589c8e43a13bafdb8c10ac#diff-209c6256531ff05f567a6bc2055749d1
