### ISSUE TITLE
[stable/concourse] slightly misleading doc on postgres password creation

### ISSUE THREAD

**Issue by aegershman** [helm/charts#15326]
**Describe the bug**

The `postgres.postgresqlPassword` field says...

>[If not set, a random 10 characters password will be used.](https://github.com/helm/charts/blob/master/stable/concourse/values.yaml#L1697)

This feels slightly misleading, as if a unique password will be generated for you if you don't set the field in your own `values.yml`. In reality, if you don't set your own password, it will be `concourse`.

I propose that single line of doc just be straight-up removed. It would bring the doc inline with things like [the `secrets.hostKey` and `sessionKey`, where default vaules are provided](https://github.com/helm/charts/blob/master/stable/concourse/values.yaml#L1787) but should be changed for production deployments. By saying "If not set, a random 10 characters password will be used" for this specific field, it's adds just a bit of doubt that the field will auto-generate something different if you don't explicitly set it (but in reality, it just sets the password to "concourse")

Thoughts?

**Comment by alemorcuq** [comment]
Hi, @aegershman.

In the `values.yaml` file, the default value for the PostgreSQL password is indeed `concourse` and thus, by default it is set. But, if you remove the default and don't set a password (by commenting the line, for example), then PostgreSQL will generate a random alphanumeric 10 character password.

You can see this logic in the [`stable/postgresql` repo](https://github.com/helm/charts/blob/master/stable/postgresql/templates/_helpers.tpl#L77):

```
{{/*
Return PostgreSQL password
*/}}
{{- define "postgresql.password" -}}
{{- if .Values.global.postgresql.postgresqlPassword }}
    {{- .Values.global.postgresql.postgresqlPassword -}}
{{- else if .Values.postgresqlPassword -}}
    {{- .Values.postgresqlPassword -}}
{{- else -}}
    {{- randAlphaNum 10 -}}
{{- end -}}
{{- end -}}
```

If no password is specified, one will be randomly generated using `randAlphaNum 10`.

Regards,
Alejandro
