### ISSUE TITLE
[stable/grafana] slack takes localhost:3000 instead of ingress configured domain name

### ISSUE THREAD

**Issue by Saggi432** [helm/charts#15332]
**Describe the bug**
when we install grafana with tls configs.. the grafana url mentioned in the slack alert still localhost:3000 instead of the domain name mentioned in the ingress config

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

**Which chart**:
grafana-2.2.0

**What happened**:
The grafana URL in the slack alert is not the same as the one configured during the chart installation.

**What you expected to happen**:
The grafana url needs to be the domain name given in the chart instead of localhost.

**How to reproduce it** (as minimally and precisely as possible):
installing the chart by specifying the tls config values as below

`grafana.ingress.hosts
grafana.ingress.tls[0].hosts
grafana.ingress.tls[0].secretName
`

**Anything else we need to know**:

The work around has been to include the domain name in the /etc/grafana/grafana.ini  however we have to give the `https` along with the domain name.

**Comment by segator** [comment]
Same issue, some way to fix this throguh helm values?
