### ISSUE TITLE
[stable/minio] upgrading from chart 1.6.3 to newer fails due to clusterip

### ISSUE THREAD

**Issue by vchrisb** [helm/charts#15341]
**Describe the bug**
Upgrading the minio chart from `1.6.3` to a newer version fails with due to invalid clusterIP

**Version of Helm and Kubernetes**:
helm: 2.14.1
kubernetes: 1.13.5

**Which chart**:
stable/minio

**What happened**:
When upgrading minio with its default values from `1.6.3` to a newer version, the upgrade fails with following message:
```
UPGRADE FAILED
Error: Service "peeking-possum-minio" is invalid: spec.clusterIP: Invalid value: "": field is immutable
Error: UPGRADE FAILED: Service "peeking-possum-minio" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```
This is due to a change in `1.6.4.` https://github.com/helm/charts/commit/43e7da2ef89d6454842a26a0878ae931d5297ce4#diff-d07642008f9bb427a35e5d86bdae6b14

It is possible to configure `service.clusterIP` with `None` to keep using a headless service and succeed the upgrade.

Setting `service.clusterIP` to `null` to indicate helm to remove that property at all does also not work and fail with the same error. (a dry run works, but not the actual upgrade)

**What you expected to happen**:
Upgrade from `1.6.3` to work seamlessly and to allow to switch from `headless mode` to the default one. 

**How to reproduce it** (as minimally and precisely as possible):
Upgrade from default provisioned  minio `1.6.3` to a later version.

**Anything else we need to know**:

**Comment by Routhinator** [comment]
/reopen

This is still an issue with the latest version of the chart.
