### ISSUE TITLE
[ghost] Update Ghost to v1.0.0

### ISSUE THREAD

**Issue by luxas** [helm/charts#1535]
**Version of Helm and Kubernetes**:
helm v2.5
Kubernetes v1.7

**Which chart**:
Ghost

**What happened**:
Ghost v0.11.10 was installed

**What you expected to happen**:
Ghost v1.0.0 would be installed

**How to reproduce it** (as minimally and precisely as possible):
Just run `helm install stable/ghost`

**Anything else we need to know**:
I know Ghost v1.0 was cut yesterday night, so this is just a heads up to bump to v1.0 ASAP the coming week. Always fun to get from v0.x to v1.x

cc @sebgoa (not sure who owns the Bitnami Ghost image)

**Comment by sameersbn** [comment]
@luxas We're working on updating the image to Ghost 1.0.0. 
We'll keep you posted and let you know when the image is release and chart has been updated.

**Comment by luxas** [comment]
Ping @sebgoa @sameersbn 
Any status update on this one?
It'd be very cool to get this functionality :)

**Comment by sameersbn** [comment]
Hi @luxas. We're currently working towards releasing ghost 1.x support. The ghost platform seems to have adopted a more frequent release cycle and that had added to the delay. We hope to have the support released soon and we'll keep you updated on the progress.

**Comment by sameersbn** [comment]
p.s. #1855 upgrades ghost to 1.7.0

**Comment by gyulavoros** [comment]
Hi @sameersbn. I tried the new 1.7.1 chart but having an issue. For some reason, ghost fails to start with the following error:

```
nami    INFO  Initializing ghost
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at {db}:3306
mysql-c INFO  MySQL server listening and working at {db}:3306
ghost   INFO  ==> Creating database...
ghost   INFO  ==> Configuring Ghost...
ghost   INFO  ==> Configuring host...
ghost   INFO  ==> Restarting service...
ghost   INFO  ==> Host configured successfully!
ghost   INFO  ==> Creating admin user...
Error executing 'postInstallation': EACCES: permission denied, open '/bitnami/ghost/config.production.json'
```

I'm on GKE, using persistent volumes. I didn't have the time to look into this but have seen that the [run](https://github.com/bitnami/bitnami-docker-ghost/blob/master/1/rootfs/run.sh) script changed in the new bitnami ghost image. Running `bitnami/ghost:1.7.1-r0` locally works fine.

**Comment by gyulavoros** [comment]
Update, I made a mistake. I used a custom `values.yaml` and messed up something with the `busybox` init container. Now it's working fine.

**Comment by sameersbn** [comment]
The ghost chart has been upgraded to the most recent 1.8 release. Marking this issue as resolved.
