### ISSUE TITLE
[stable/ambassador] Please add me as repo-collaborator

### ISSUE THREAD

**Issue by iNoahNothing** [helm/charts#15369]
I am currently an OWNER of the `stable/ambassador` chart. However, since I am currently not a repo collaborator people are unable to request reviews from me directly.

Could you please add me as a collaborator to resolve this.

Thanks!

**Comment by nbkrause** [comment]
@unguiculus Is there anything you need from me to move forward with this?

**Comment by nbkrause** [comment]
I would still like to be add as a collaborator. Who should I contact about this?

/reopen

**Comment by cpanato** [comment]
I will add you, was checking the contributions.

**Comment by nbkrause** [comment]
I appreciate it! Thanks!
