### ISSUE TITLE
Add stable chart repo link to README

### ISSUE THREAD

**Issue by gyliu513** [helm/charts#1536]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

## How do I enable the Incubator repository?

To add the Incubator charts for your local client, run `helm repo add`:

```
$ helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
"incubator" has been added to your repositories
```

You can then run `helm search incubator` to see the charts.

We should have a section telling customer how to add the stable repo.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by unguiculus** [comment]
The stable repo is added automatically. You just do `helm init` and are good to go.

**Comment by Ciantic** [comment]
Except when it doesn't? Helm 3.

```
$ helm init
...prints just help...
$ helm repo update
Error: no repositories found. You must add one before updating
```

**Comment by pre** [comment]
`helm init` ought to be enough for anybody 🙄

**Comment by morganlaneap** [comment]
Helm init was removed. I feel like @Ciantic has a point with `helm repo add stable https://kubernetes-charts.storage.googleapis.com`

**Comment by scones** [comment]
> `helm init` was removed wasn't it? I feel like @Ciantic has a point with `helm repo add stable https://kubernetes-charts.storage.googleapis.com`

solves `Error: no repositories found. You must add one before updating` after fresh helm 3 install on `helm repo update`
