### ISSUE TITLE
[error] Error: This command needs 1 argument: chart name......

### ISSUE THREAD

**Issue by chenjianxin** [helm/charts#15403]
helm install pingcap/tidb-cluster --name demo --set schedulerName=default-scheduler,pd.storageClassName=standard,tikv.storageClassName=standard,pd.replicas=1,tikv.replicas=1,tidb.replicas=1 --version=v1.0.0-beta.3

**It Return**
Error: This command needs 1 argument: chart name

??? I have give it [--name demo]

**Comment by wtx626** [comment]
I have the same error when i install hadoop. I don't know how to fix it , can anyone help me?
