### ISSUE TITLE
[stable/openvpn] Add {{ .Release.Namespace | quote }} to metadata

### ISSUE THREAD

**Issue by andymeierdev** [helm/charts#15401]
**Is your feature request related to a problem? Please describe.**
_Feature request_: When using `helm template --namespace <my namespace>` the chart does not pick up the namespace flag and a subsequent apply using the templates will install the chart into the default namespace. 

**Describe the solution you'd like**
Add `{{ .Release.Namespace | quote }}` into the metadata field of the templates. See [this PR](https://github.com/helm/charts/pull/13924) for a similar request.

**Describe alternatives you've considered**
I am using pulumi and right now I have to add a custom transformation. See [this issue](https://github.com/pulumi/pulumi-kubernetes/issues/217) for more information.

**Comment by jasongwartz** [comment]
@ameier38 I opened a similar PR about this for openvpn a while back, but it went stale: https://github.com/helm/charts/pull/13068

I’m happy to consider it if you want to reopen a similar PR, knowing now what the motivation is

**Comment by ameier38** [comment]
@jasongwartz sounds good will do
