### ISSUE TITLE
[stable/prometheus] alertmanager Readiness probe failed: HTTP probe failed with statuscode: 404

### ISSUE THREAD

**Issue by danielschlegel** [helm/charts#15419]
**Describe the bug**
After successfully running helm install for stable prometheus prometheus-alertmanager and also prometheus-server is not running. prometheus-server is not running because it cannot connect to alertmanager.
When i connect into the container i see port 9093 is used and i can also connect to it with telnet localhost 9093 but if i try wget to localhost:9093/#/status like rediness probe is doing i also get this 404.

**Version of Helm and Kubernetes**:
Helm v2.12.2
Kubernetes v1.13.5

**Which chart**:
stable/prometheus
version 8.10.2 (also tried version 8.14.2 with same issues)
Version 8.14.2 has alertmanager 0.17.0 configured that did not work so i tried 0.18.0 also.

**What happened**:
Pod is runnig but rediness probe returns 404.

**What you expected to happen**:
Rediness probe should not fail.

**How to reproduce it** (as minimally and precisely as possible):
Normal install of helm install stable/prometheus

in values.yml baseURL is set to external url.

**Anything else we need to know**:
I use rook version 1.0.2. Also with disabled persistanceVolume i have the same issue.

**Alertmanager logs**
level=info ts=2019-07-11T08:25:59.364Z caller=main.go:197 msg="Starting Alertmanager" version="(version=0.18.0, branch=HEAD, revision=1ace0f76b7101cccc149d7298022df36039858ca)"
level=info ts=2019-07-11T08:25:59.365Z caller=main.go:198 build_context="(go=go1.12.6, user=root@868685ed3ed0, date=20190708-14:31:49)"
level=info ts=2019-07-11T08:25:59.369Z caller=cluster.go:623 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2019-07-11T08:25:59.427Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/config/alertmanager.yml
level=info ts=2019-07-11T08:25:59.428Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/config/alertmanager.yml
level=info ts=2019-07-11T08:25:59.436Z caller=main.go:429 msg=Listening address=:9093
level=info ts=2019-07-11T08:26:01.370Z caller=cluster.go:648 component=cluster msg="gossip not settled" polls=0 before=0 now=1 elapsed=2.000229385s
level=info ts=2019-07-11T08:26:09.372Z caller=cluster.go:640 component=cluster msg="gossip settled; proceeding" elapsed=10.001877259s

**Alertmanager config**
cat /etc/config/alertmanager.yml 
global: {}
receivers:
- name: default-receiver
route:
  group_interval: 5m
  group_wait: 10s
  receiver: default-receiver
  repeat_interval: 3h

**Comment by silvermind** [comment]
removing the alertmanager.baseURL fixed the issue for me. see: https://github.com/helm/charts/blob/master/stable/prometheus/templates/alertmanager-deployment.yaml#L54

if  --web.external-url= is set, the Pod does not repsonse to the HealthChecks anymore.. not sure where this is comming from..

          {{- if .Values.alertmanager.baseURL }}
            - --web.external-url={{  .Values.alertmanager.baseURL }}
          {{- end }}

**Comment by amol2311** [comment]
any solution for this issue , with adding baseurl?

**Comment by AlaaAttya** [comment]
i'm facing the same issue also
