### ISSUE TITLE
[stable/airflow] Postgress connection keeps getting disconnected

### ISSUE THREAD

**Issue by ramkrishnan8994** [helm/charts#15436]
`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres-postgresql.production" to address: Name or service not known
`
The above error keeps occurring on a regular basis on the **airflow-web** pod.
As soon as the pod restarts, the **airflow-web** pod starts running without any issues. Around 2-3 restarts per day has been observed.

My Postgres pod is also up and running and has no issues at all. It has 0 restarts as well.

 @stevenmanton @gsemet

**Comment by gsemet** [comment]
hi. Is it the right hostname: postgres-postgresql.production ?

**Comment by ramkrishnan8994** [comment]
> hi. Is it the right hostname: postgres-postgresql.production ?

Yes. As soon as the pod restarts, the service is up and running with the same config.
It just keeps on restarting in between with this error

**Comment by stevenmanton** [comment]
@ramkrishnan8994 it's really hard to say without seeing your `values.yaml`. It sounds like Postgres is trying to connect to a service that doesn't exist. Are you able to see that service running in kubernetes (e.g. `kubectl get svc`)? I'm guessing this was an existing Postgres instance, not one deployed and managed by the chart, right? Also, 2-3 restarts per day implies it's an intermittent issue; if the service really didn't exist you'd have hundreds of restarts per day.

**Comment by ramkrishnan8994** [comment]
@stevenmanton . Yes the service exists. After restarts, the web pod starts working fine without issues

**Comment by ramkrishnan8994** [comment]
@stevenmanton - Please look at this - https://github.com/helm/charts/issues/13262#issuecomment-512809289

Let me know if this setting in postgres would help

**Comment by stevenmanton** [comment]
@ramkrishnan8994 I'm not sure if that setting would help you. Unfortunately, upgrading the posgres subchart is a breaking change.
