### ISSUE TITLE
gitlab-ce chart should support PersistentVolumeClaim selectors

### ISSUE THREAD

**Issue by juliohm1978** [helm/charts#1544]
Looking at the [templates for the gitlab-ce chart](https://github.com/kubernetes/charts/tree/master/stable/gitlab-ce), I noticed that PVCs are created without any options for selectors ([example here](https://github.com/kubernetes/charts/blob/master/stable/gitlab-ce/templates/data-pvc.yaml)).

While planning for a deployment in our infrastructure, my team needs to map specific PVs to Gitlab's expected volume claims. As it stands, when the chart is deployed for the first time, it will randomly pick any PV that matches the size requirements. This makes it difficult to assign specific NFS volumes to each pod.

With that in mind, I propose pvc templates to include options to include selectors, as supported by k8s ([official reference](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector)).

**Comment by grugnog** [comment]
This would also be helpful for restoring a snapshot backup to a new PV - you cannot specify the PV to use with Helm, so end up autoprovisioning a new volume and then updating the PVC config directly which is a bit messy.
