### ISSUE TITLE
[stable/external-dns] PrivateDns azure issue

### ISSUE THREAD

**Issue by aaktaev** [helm/charts#15452]
**Describe the bug**
Trying to configure external-dns chart with azure cloud, and use Private Dns zone for resource group

**Version of Helm and Kubernetes**:

**stable/external-dns**:

**Here is output from external-dns pod**:

```
level=error msg="azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/****/resourceGroups/test/providers/Microsoft.Network/dnsZones?api-version=2016-04-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Identity not found\"}"
```

**What you expected to happen**:
Add record of service to PrivateDns zone

**How to reproduce it** (as minimally and precisely as possible):
azure cloud,
privateDns zone

**Comment by aaktaev** [comment]
as I understand there should be some configuration like type of DNS zone for azure cloud like in AWS

**Comment by juan131** [comment]
Hi @aaktaev 

Could you please share the **values.yaml** you're using to deploy the external-dns chart? 

What configuration options are you missing? Is there anything mentioned in the guide below that can't be configured in **external-dns** with the current chart?

https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/azure.md

**Comment by aaktaev** [comment]
There are two types od DNS zones in Azure cloud: Public and private.

And I've wanted to deploy external-dns on azure cloud, but to use private dns zone.

**Comment by javsalgar** [comment]
Hi,

It would be very helpful to us if you could describe the necessary steps to replicate the configuration you have. With that, we could reproduce the issue.
