### ISSUE TITLE
[stable/wordpress] Cluster went down, once it started up again mariadb gets error Readiness probe failed: mysqladmin: connect to server at 'localhost' failed error: 'Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by donnierisk** [helm/charts#15460]
**Describe the bug**
I get the error when reinstalling helm chart after kubernetes cluster went down:
> Readiness probe failed: mysqladmin: connect to server at 'localhost' failed error: 'Access denied for user 'root'@'localhost' (using password: YES)

I'm not sure which steps to follow to ensure that it'll reconnect again and find the same drive, do I specify a volume?

**Version of Helm**:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

**Version of Kubernetes**
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.13", GitCommit:"fcbc1d20b6bca1936c0317743055ac75aef608ce", GitTreeState:"clean", BuildDate:"2019-06-19T20:50:07Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/wordpress

**What happened**:
I used the following command to install Wordpress on our cluster:
```
helm install stable/wordpress --namespace mynamespace --name myrelease \
 --set service.type=ClusterIP,wordpressUsername=admin,wordpressPassword=password
```
Something went wrong and the cluster's services and workloads were deleted. So I retyped the above command exactly to try bring Wordpress back hoping that it'll be up again. Mariadb doesn't manage to come up again.

**What you expected to happen**:
Wordpress + Mariadb to restart in the same state before the cluster went down.

**How to reproduce it** (as minimally and precisely as possible):
Install stable/wordpres with the command I specified above. once it's up on cluster. delete the workloads + services for wordpress and mariadb. then to try bring it back use the same install command with same release name, user and password for wordpress.

**Anything else we need to know**:
Mariadb pod logs:
```
Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MariaDB setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
INFO  ==> Initializing mariadb database...
INFO  ==> Persisted data detected. Restoring...
INFO  ==> Stopping mariadb...
INFO  ==> ** MariaDB setup finished! **

INFO  ==> ** Starting MariaDB **
2019-07-11 14:31:46 140055210657664 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.40-MariaDB) starting as process 1 ...
2019-07-11 14:31:46 140055210657664 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.

2019-07-11 14:31:46 140055210657664 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2019-07-11 14:31:46 140055210657664 [Note] InnoDB: The InnoDB memory heap is disabled
2019-07-11 14:31:46 140055210657664 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-07-11 14:31:46 140055210657664 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2019-07-11 14:31:46 140055210657664 [Note] InnoDB: Compressed tables use zlib 1.2.8
2019-07-11 14:31:46 140055210657664 [Note] InnoDB: Using Linux native AIO
2019-07-11 14:31:46 140055210657664 [Note] InnoDB: Using SSE crc32 instructions
2019-07-11 14:31:46 140055210657664 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2019-07-11 14:31:46 140055210657664 [Note] InnoDB: Completed initialization of buffer pool
2019-07-11 14:31:46 140055210657664 [Note] InnoDB: Highest supported file format is Barracuda.
2019-07-11 14:31:47 140055210657664 [Note] InnoDB: 128 rollback segment(s) are active.
2019-07-11 14:31:47 140055210657664 [Note] InnoDB: Waiting for purge to start
2019-07-11 14:31:47 140055210657664 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.43-84.3 started; log sequence number 2502954
2019-07-11 14:31:47 140055210657664 [Note] Plugin 'FEEDBACK' is disabled.
2019-07-11 14:31:47 140054508824320 [Note] InnoDB: Dumping buffer pool(s) not yet started
2019-07-11 14:31:47 140055210657664 [Note] Server socket created on IP: '0.0.0.0'.
2019-07-11 14:31:47 140055210657664 [Warning] 'proxies_priv' entry '@% root@cmsresideo1-mariadb-0' ignored in --skip-name-resolve mode.
2019-07-11 14:31:47 140055210657664 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
Version: '10.1.40-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
```

wordpress pod logs:
```
Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
mysql-c INFO  Trying to connect to MySQL server
Error executing 'postInstallation': Failed to connect to cmsresideo1-mariadb:3306 after 36 tries
```

**Comment by juan131** [comment]
Hi @donnierisk 

When you delete a chart (e.g. running the command `helm delete --purge my-release`), you'll find out that some resources aren't removed (for instance the **PVCs** associated to **statefulsets**). That's something very easy to check:

```console
$ helm install stable/wordpress --name my-release
$ kubectl get pvc
NAME                        STATUS   VOLUME                                     ...
data-my-release-mariadb-0   Bound    pvc-a06ed6d7-c1ba-4175-852b-f4e3d7ed2997   ...
my-release-wordpress        Bound    pvc-4da24285-a2a2-430f-9bef-9cb6c1c6d498   ...
$ helm delete --purge my-release
$ kubectl get pvc
NAME                        STATUS   VOLUME                                     ...
data-my-release-mariadb-0   Bound    pvc-a06ed6d7-c1ba-4175-852b-f4e3d7ed2997   ...
```

As you can see, the **PVCs** associated to the MariaDB database, were not removed!! Therefore, if you install the chart again using the same name for the release, MariaDB will attempt to reuse the existing **PVCs** (which has persisted data, including the passwords that were assigned the 1st time). When you do not specify a password for the database, it's randomly created and, therefore, MariaDB won't work as expected since the password in the data data and the password configured in the rest of resources (such as the readiness probes) won't coincide.

Solution: you should always provide the passwords to use in your "install" or "upgrade" helm commands:

```console
$ helm install stable/wordpress --name my-release \
      ... \
      --set mariadb.mariadbRootPassword=my-root-password
      --set mariadb.mariadb.db.password=my-db-password \
```

On the other hand, by default, the **PVCs** that are created are `ReadWriteOnce` and they do not specify any **"StorageClassName"**. It means that MariaDB and WP will use whatever type of PersistentVolume your cluster's storage provisioner generates. Most cluster use a Local Storage Provisioner which generates volumes that will disappear if the cluster node dies. 

To ensure the data isn't lost even if your cluster goes down, you should use a NFS provider or a Cloud storage service (so you can use **PVs** of the type GCEPersistentDisk or AWSElasticBlockStore for instance). Find the whole list of **PV types** in the link below:

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes

**Comment by donnierisk** [comment]
Hi @juan131 Thank you for the help so far. The mariadb issue is sorted out well it seems. I thought I got it fully working last night, but when I retried again this morning the Wordpress pod can't attach to the PVC I get the error:
**Multi-Attach error for volume "pvc-f8a59a0a-a421-11e9-953a-42010a84002b" Volume is already used by pod(s) knotted-umbrellabird-nfs-server-provisioner-0**

in my values-production.yaml I have:
persistence.existingClaim: data-knotted-umbrellabird-nfs-server-provisioner-0

From my understanding the existingClaim should attach the pod to the volume. I'm not sure what i'm doing wrong. Do I need to specify a label so that it doesn't dynamically create them?

**Comment by donnierisk** [comment]
I think I got it working, below were the steps I took:
```
helm install stable/nfs-server-provisioner --name my-provisioner \
  --set persistence.enabled=true,persistence.size=10Gi
```
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cmsresideo1-pvc
  namespace: cmsresideo1
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```
Then create the above PVC in the cluster:
```
$ kubectl create -f pvc.yaml
```
Then installed wordpress, referencing the above PVC in "existingClaim" in the values-production.yaml

```
helm install --name $INSTALLATION_ID --namespace $INSTALLATION_ID  -f ./values-production.yaml stable/wordpress
```

I've deleted the helm release multiple times and brought it back up with the last command above, i changed WordpressSkipInstall to true after the initial release. If I set the storage to 10Gi it is stuck on pending, is that due to the provisioner only granting 10Gi in total for WP + mariadb? If there are any other red flag in what i've done please assist.

Thanks for your time!

**Comment by javsalgar** [comment]
Hi,

Could you use `kubectl describe pod` to see the events that are causing the container to be stuck in pending?

**Comment by donnierisk** [comment]
Hi @javsalgar the logs for mariadb as well as wordpress pod says:

```
Unable to mount volumes for pod "myrelease-wordpress-7f66cd97f-x72nk_myrelease(8cda3a69-a7d9-11e9-953a-42010a84002b)": timeout expired waiting for volumes to attach or mount for pod "myrelease"/"myrelease-wordpress-7f66cd97f-x72nk". list of unmounted volumes=[wordpress-data]. list of unattached volumes=[wordpress-data default-token-jh2md]
```

Is my nfs-server-provisioner possibly not reassigning the pods to their respective PVCs?
