### ISSUE TITLE
[stable/mongodb] "debug" level  logs not showing on pod startup

### ISSUE THREAD

**Issue by tapanhalani** [helm/charts#15484]
**Describe the bug**
I have "mongodbSystemLogVerbosity=5" set in values.yaml file. When I deploy a release, the pod keeps crashing, and when I see the logs, I cannot see any "debug" level logs corresponding to those defined in following file: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.0/debian-9/rootfs/libmongodb.sh . I cannot find the issue in my config that is causing the crashes due to this.

**Version of Helm and Kubernetes**:
Helm:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

Kubernetes:
v 1.15.0

**Which chart**:
stable/mongodb

**What happened**:
When I deploy a release, the pods always crash. I cannot see debug logs and cannot find the issue, even on having maximum log verbosity (mongodbSystemLogVerbosity=5) . Here are the current logs of crashing pods:

```
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MongoDB setup **
INFO  ==> Validating settings in MONGODB_* env vars...
INFO  ==> Initializing MongoDB...
INFO  ==> Deploying MongoDB from scratch...
INFO  ==> No injected configuration files found. Creating default config files...
```

**What you expected to happen**:
I should be able to see all level of logs (including DEBUG/WARN/ERROR) with this setting. Otherwise, the pods keep crashing, but I cannot find the issue and cannot resolve it.

**How to reproduce it** (as minimally and precisely as possible):
Create a helm release using "helm install --name my-mongodb --values ./values.yml --namespace=db stable/mongodb" . Attached file is the values.yml file I use.

**Anything else we need to know**:
[mongodb_values.yml.txt](https://github.com/helm/charts/files/3386474/mongodb_values.yml.txt)

**Comment by alemorcuq** [comment]
Hi, @tapanhalani.

To enable debugging messages for the Bitnami image, you have to set the `image.debug` option to true: https://github.com/helm/charts/blob/master/stable/mongodb/values.yaml#L35

However, I can see there's a bug there, as it should enable the `BITNAMI_DEBUG` environment variable instead of `NAMI_DEBUG`. I will be making a PR fixing this.

In the meantime, you can manually configure the environment variable `BITNAMI_DEBUG=true` to enable logging.

Regards,
Alejandro
