### ISSUE TITLE
[stable/sonarqube] test pod re-created on every run

### ISSUE THREAD

**Issue by willejs** [helm/charts#15486]
**Describe the bug**

The ui test pod is recreated on every apply as it uses a random id to name the pod. 
This causes helm diff to always diff, and also the pod to run every time we do an apply. 
I am curious to know why this even runs when we have liveliness and readiness probes?
Do you think i can just make a PR to delete this @rjkernick ?

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
Sonarqube

**What happened**:
The chart always diffs.

**What you expected to happen**:
The chart should not diff.

**How to reproduce it** (as minimally and precisely as possible):
Try and apply the chart with no changes.

**Anything else we need to know**:

**Comment by rjkernick** [comment]
The purpose of those files is to be able to run the command "helm test". If the issue is the random id, we can change it to a static name.
