### ISSUE TITLE
[stable/gangway] No support for a "trustedCAPath" volume in deployment.yaml

### ISSUE THREAD

**Issue by figaw** [helm/charts#15521]
The Readme specifies the possibility of having a `gangway.trustedCAPath`-variable. But it's only referenced in the `values.yaml` and used as a child of `gangway` in the `templates/configmap.yaml`.

There's no support for adding a `Secret` or `ConfigMap` as a volume and volumeMount in the `templates/deployment.yaml`, so it's not possible to provide the actual file containing the CA Bundle.

Our temporary workaround, is to:
- delete the `gangway`-configmap, as that's mounted on `/gangway/` in the deployment
- recreate the configmap, with a `rootca.crt`-file entry, containing the bundle, and
- set `trustedCAPath` to `/gangway/rootca.crt`

**Comment by figaw** [comment]
This issue is not resolved.

**Comment by figaw** [comment]
This issue is not resolved.

**Comment by holmesb** [comment]
@figaw this is fixed.  See new `trustedCACert` value.  You can close.
