### ISSUE TITLE
Support Redis clusters in Redis chart

### ISSUE THREAD

**Issue by dysinger** [helm/charts#1553]
Redis chart should support master/slave clusters (the underlying docker images does)

**Version of Helm and Kubernetes**: Doesn't matter
**Which chart**: redis
**What happened**: only deploys 1 single stand alone node
**What you expected to happen**: option to deploy a cluster
**How to reproduce it** (as minimally and precisely as possible): <_<
**Anything else we need to know**: Nope

**Comment by ggn06awu** [comment]
@dysinger see #423, there's already some movement, so I'd close this in favour of that ticket. I think it's still waiting on questions around an odd source docker image selection and resource limits. If you wanted to get cracking, the request there looks usable though.
