### ISSUE TITLE
[stable/postgresql] postgresql.conf written in hardcoded location regardless of postgresqlDataDir

### ISSUE THREAD

**Issue by cloud-rocket** [helm/charts#15576]
**Describe the bug**

Cannot modify a default Postgres configuration if alternative `postgresqlDataDir` is set. Or alternatively there should be a way to set a custom `conf` path 

**Which chart**:

`stable/postgresql`

**What happened**:

`postgresql.conf` is written in hardcoded `/bitnami/postgresql/conf/postgresql.conf` path regardless of `postgresqlDataDir` setting

**What you expected to happen**:

Generated configuration values (i.e. `max_connections`) should be written to `{{ .Values.postgresqlDataDir }}/conf/postgresql.conf`

**Comment by rafariossaa** [comment]
Hi @cloud-rocket ,
  The parameter postgresDataDir is to set where to store the data, is not related to config files.

  If you need to set configuration values, you can use `postgresqlConfiguration` or `postgresqlExtendedConf` depending on your needs. 
  Please take a look at them at the values.yaml, and tell me if that will work for you.

**Comment by cloud-rocket** [comment]
Hi @rafariossaa,
Sorry for maybe not so accurate description.
I am setting `postgresqlConfiguration`, but it generates `postgresql.conf` file in `/bitnami/postgresql/conf/` (default) location. Because my `postgresDataDir` is pointing to another location and uses config files in this location also, this file is ignored.

Tnx

**Comment by cloud-rocket** [comment]
@rafariossaa -ping!
