### ISSUE TITLE
Add @xlucas as Trusted Collaborator

### ISSUE THREAD

**Issue by xlucas** [helm/charts#15587]
Hello,

As for #13120 and #13279, I'm also working at Datadog and maintaining the Datadog chart. Therefore I would like to be added as a trusted collaborator as well to take part in the PR lifecycle.

Thanks!

@hkaj

**Comment by hkaj** [comment]
👋 sponsoring this request - @xlucas works at Datadog and contributes to our chart.

**Comment by xlucas** [comment]
Hey @mattfarina could you take a look at this request? 🙏 Thanks a lot!

**Comment by xlucas** [comment]
Can anyone else help on that?

**Comment by maorfr** [comment]
done.
