### ISSUE TITLE
[stable/nginx-ingress] Error: ErrImagePull

### ISSUE THREAD

**Issue by rnkhouse** [helm/charts#15659]
**Describe the bug**

**Version of Helm and Kubernetes**:
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}

**Which chart**:
stable/nginx-ingress

**What happened**:

I am trying to install nginx-ingress using below command.
    helm install stable/nginx-ingress --name nginx \
              --set rbac.create=true \
              --set controller.replicaCount=2 \
              --set controller.stats.enabled=true \
              --set controller.metrics.enabled=true \
              --set controller.service.loadBalancerIP=xx.xx.xx.xx

Error:
Events:
  Type     Reason     Age               From                               Message
  ----     ------     ----              ----                               -------
  Normal   Scheduled  1m                default-scheduler                  Successfully assigned default/nginx-nginx-ingress-controller-6857cc97fd-qkkmx to aks-agentpool-17141372-1
  Normal   Pulling    25s (x3 over 1m)  kubelet, aks-agentpool-17141372-1  pulling image "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.25.0"
  Warning  Failed     25s (x3 over 1m)  kubelet, aks-agentpool-17141372-1  Failed to pull image "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.25.0": rpc error: code = Unknown desc = Error response from daemon: Get https://quay.io/v2/: EOF
  Warning  Failed     25s (x3 over 1m)  kubelet, aks-agentpool-17141372-1  Error: ErrImagePull
  Normal   BackOff    0s (x5 over 1m)   kubelet, aks-agentpool-17141372-1  Back-off pulling image "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.25.0"
  Warning  Failed     0s (x5 over 1m)   kubelet, aks-agentpool-17141372-1  Error: ImagePullBackOff

**What you expected to happen**:
It should install nginx ingress controller.

**Comment by strican** [comment]
Did you ever solve this? I'm currently hitting this same issue. I can pull the image fine manually but it fails when applying the `mandatory.yaml` config.

**Comment by strican** [comment]
Never mind - some of my nodes needed to have some ports opened on their security group and that solved the issue for me.

**Comment by eliaspn** [comment]
On GKE if you're using a private cluster you have to add a NAT Gateway in order to allow you're nodes to talk to talk with outside world https://medium.com/google-cloud/using-cloud-nat-with-gke-cluster-c82364546d9e
