### ISSUE TITLE
[stable/redis] Exporter REDIS_ADDR invalid separator in cluster mode

### ISSUE THREAD

**Issue by a7i** [helm/charts#15658]
**Describe the bug**
Issues with metrics exporter when deploying a Redis chart (v8.1.2) with cluster and metrics enabled. Exporter container logs errors but it does not crash. As a result, metrics are not published.

**Version of Helm and Kubernetes**:
Helm v2.12.2
Kubernetes v1.12.6

**Which chart**:
stable/redis

**What happened**:
In chart upgrade to 8.0.18, metrics image tag was changed to`v1.0.3`. if you have cluster enabled, it attempts to put in a comma-separated value for the REDIS_ADDR val which is not an acceptable argument.

```
        env:
        - name: REDIS_ADDR
          value: "redis-app-master:6379,redis-app-slave:6379"
```

Logs from redis_exporter
```
time="2019-07-17T18:29:25Z" level=debug msg="Trying DialURL(): redis://redis-app-master:6379,redis-app-slave:6379"
time="2019-07-17T18:29:25Z" level=debug msg="DialURL() failed, err: dial tcp: lookup redis-app-master:6379,redis-app-slave:6379: no such host"
time="2019-07-17T18:29:25Z" level=debug msg="Trying: Dial(): tcp redis-app-master:6379,redis-app-slave:6379"
time="2019-07-17T18:29:25Z" level=error msg="Couldn't connect to redis instance"
time="2019-07-17T18:29:25Z" level=debug msg="connectToRedis( redis-app-master:6379,redis-app-slave:6379 ) err: dial tcp: address redis-app-master:6379,redis-app-slave:6379: too many colons in address"
```

**What you expected to happen**:
It should set up the addresses properly with the supplied separator.

**How to reproduce it** (as minimally and precisely as possible):

- Use chart version 8.1.2
- Set cluster to enabled
- Set metrics to enabled, set debug flag as show below
```
  metrics:
    enabled: true
    extraArgs: {
      "debug": "true"
    }
```
- Deploy chart
- Observe metrics logs and error mentioned above

**Anything else we need to know**:

**Comment by javsalgar** [comment]
Hi,

Taking a look at the recent documentation, it seems that they changed the exporter to work as a sidecar. We would need then to remove the metrics deployment and switch it to a sidecar approach. I will update this thread when I have a PR ready

**Comment by javsalgar** [comment]
Hi, I created this https://github.com/helm/charts/pull/15713 to cover this issue
