### ISSUE TITLE
jenkins stable/chart - reverse proxy broken behind ssl

### ISSUE THREAD

**Issue by tnimni** [helm/charts#15672]
**Describe the bug**

Reverse proxy is broken according to jenkins, chart installed on eks behind ALB which route all traffic from 443 to ngnix inside the cluster

**Version of Helm and Kubernetes**:
kubernetes 1.13
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

**Which chart**:
jenkins/stable

**What happened**:
jenkins alert that reverse proxy is broken

**What you expected to happen**:
reverse proxy works as expected

**How to reproduce it** (as minimally and precisely as possible):
install ALB on aws, alb listen on port 443 with valid certificate and redirect traffic to cluster

cluster has ngnix installed and actch all *.Domain taffic and redirect to cluster services

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
You can specify `master.jenkinsUrl` 

https://github.com/helm/charts/blob/master/stable/jenkins/templates/config.yaml#L195

**Comment by torstenwalter** [comment]
@tnimni Did this solve your problem?

**Comment by t451772** [comment]
I am having this issue. 
Kubernetes 1.13.5
My command was:
helm install --name jenkins --namespace jenkins stable/jenkins --set master.ingress.enabled=true --set master.ingress.hostName=fake.node.com --set master.serviceType=ClusterIP --set master.jenkinsUrl=http://fake.node.com
My result is jenkins alert that reverse proxy is broken. Possibly related the Jenkins python API doesn't work for the chart, but does work for a standalone deployment with ingress loadbalancer. 

Did I miss something?

**Comment by torstenwalter** [comment]
@ts4z 

- Which URL are you using when accessing Jenkins?
- Which URL is shows under Jenkins -> Manage Jenkins -> Jenkins Location -> Jenkins URL?
- Are both identical?

**Comment by t451772** [comment]
I am accessing Jenkins on a URL which looks a lot like http://fake.node.com
Under Jenkins -> Manage Jenkins -> Configure System -> Jenkins Location the url is http://fake.node.com/
They are different by a /. I will see if changing that matters

**Comment by tnimni** [comment]
hi all, sorry for the late respone
@torstenwalter i did specify the url and it didn't help it just keep saying it's broken
when i run the test with curl from command line from this page https://wiki.jenkins.io/display/JENKINS/Jenkins+says+my+reverse+proxy+setup+is+broken
it works fine, meaning it's not broken
i specified the url from the ui not from the chart
so i don't understand why it say it's broken from ui

**Comment by torstenwalter** [comment]
@tnimni Did you try the solution @t451772 pointed out?
