### ISSUE TITLE
[stable/sonarqube] Privileged init container needed since 2.1.0?

### ISSUE THREAD

**Issue by mmaier2** [helm/charts#15676]
**Describe the bug**
Not a bug but more a design question:
The privileged init container makes it difficult to install, e.g. on an Openshift environment or other security concerned kubernetes platforms.

**Version of Helm and Kubernetes**:
Not relevant

**Which chart**:
stable/sonarqube >= 2.1.0

**What happened**:
Openshift, e.g. does not allow privileged containers as a default. Is this init container which sets a kernel parameter needed for sonarqube 7.8?

**How to reproduce it** (as minimally and precisely as possible):
Install stable/sonarqube >= 2.1.0 on Openshift etc.

Thanks 
Markus

**Comment by acarsercan** [comment]
This flags up on security checks when running sonarqube in the cluster
