### ISSUE TITLE
[stable/traefik] Enable the dashboard without ingress

### ISSUE THREAD

**Issue by adhodgson1** [helm/charts#15684]
When enabling the dashboard in the Traefik chart (setting dashboard.enabled to True), an ingress rule is always created to allow the dashboard to be available externally. As we access the dashboard via Kubernetes port forwards, I would like the creation of this rule to be skipped if we set a value like dashboard.create_ingress to False. The default values.yaml would set this to true to match the existing behaviour.

**Comment by jonbesga** [comment]
Did this end up being applied? I find myself in the same situation

**Comment by adhodgson1** [comment]
No it hasn't made it through yet unfortunately.
