### ISSUE TITLE
[stable/nginx-ingress] incompatible types for comparison defaultBackend.replicaCount

### ISSUE THREAD

**Issue by rummens** [helm/charts#15691]
**Describe the bug**
Running into incomatible type error when using the default values of chart. 

Command s. below

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.14+unreleased", GitCommit:"ed2373629bb8eccb2c2c663cced6f40e759c7d15", GitTreeState:"clean"}
Server: &version.Version{SemVer:"canary+unreleased", GitCommit:"88bb48bc6f573e21909147792a16daad7665e45f", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/nginx-ingress

**What happened**:
Error: render error in "nginx-ingress/templates/default-backend-poddisruptionbudget.yaml": template: nginx-ingress/templates/default-backend-poddisruptionbudget.yaml:1:7: executing "nginx-ingress/templates/default-backend-poddisruptionbudget.yaml" at <gt .Values.defaultBackend.replicaCount 1.0>: error calling gt: incompatible types for comparison

**What you expected to happen**:
Install without errors

**How to reproduce it** (as minimally and precisely as possible):

helm upgrade --install $ingressName stable/nginx-ingress \
    --namespace $namespace \
    --set controller.replicaCount=$replicationCount \
    --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux \
    --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux \
    --set controller.service.loadBalancerIP="$ip"

**Anything else we need to know**:
Using fresh Azure AKS RBAC enabled cluster.
Following https://docs.microsoft.com/en-us/azure/aks/ingress-tls

Funny thing it worked this morning, on a different cluster from the same VM with the same helm installation.

**Comment by boxidilshan** [comment]
Any resolution for this? I also get this error. Your help is appreciated.

**Comment by rummens** [comment]
I was able to find a workaround, it is not clean but works for now.

1. Fork the repo
2. Change the following files: 
   -controller-poddisruptionbudget.yaml
   -default-backend-poddisruptionbudget.yaml
3. You have to replace 1.0 with "one" in the first line of both files
4. Install this new chart and it works for me. 


But again this is not a good fix, someone should have a look at this. I tried different versions of the helm chart because it worked for me yesterday with the same code (only different cluster).

**Comment by boxidilshan** [comment]
@rummens yes I too got it working using a workaround. IMO this needs to be fixed.

**Comment by patst** [comment]
I got the same error with helm version v2.14.**2**. 
But it seems to be working with helm version v2.14.**1**

**Comment by get2dmathew** [comment]
> I was able to find a workaround, it is not clean but works for now.
> 
>     1. Fork the repo
> 
>     2. Change the following files:
>        -controller-poddisruptionbudget.yaml
>        -default-backend-poddisruptionbudget.yaml
> 
>     3. You have to replace 1.0 with "one" in the first line of both files
> 
>     4. Install this new chart and it works for me.
> 
> 
> But again this is not a good fix, someone should have a look at this. I tried different versions of the helm chart because it worked for me yesterday with the same code (only different cluster).

We can run with the version (--version )  it was using that time , for example 

`helm upgrade  nginx-ingress stable/nginx-ingress  -f values.yaml   --version 1.17.1`
