### ISSUE TITLE
[stable/jenkins] Can't update some plugins

### ISSUE THREAD

**Issue by 23ewrdtf** [helm/charts#15693]
**Describe the bug**
My InstallPlugins section in value file looks like this:

```
InstallPlugins:
      - matrix-auth:2.4.2
      - kubernetes:1.17.2
      - git:3.10.1
      - pipeline:2.5
      - pipeline-utility-steps:2.3.0
      - blueocean:1.17.0
      - bitbucket:1.1.10
      - docker:1.1.7
      - resource-disposer:0.12
```
And I can change the version of each plugin, run below command and all the plugins get updated.

`helm upgrade jenkins stable/jenkins -f values.yaml`

My jenkins 2.176.2-alpine, shows under Manage Jenkins / Manage Plugins / Updates below plugins that needs updating:

```
      - command-launcher
      - jdk-tool
      - trilead-api
```

When I add them to InstallPlugins section as below, they don't get updated and they still appear under Manage Jenkins / Manage Plugins / Updates

```
InstallPlugins:
      - command-launcher:1.3
      - jdk-tool:1.2
      - trilead-api:1.0.3
```

**Version of Helm and Kubernetes**:

Helm
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

Kubernetes
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-12-06T01:33:57Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
Jenkins

**What happened**:
Plugins don't get updated

**What you expected to happen**:
Plugins to get updated

**How to reproduce it** (as minimally and precisely as possible):
Add below section to values file and upgrade jenkins
InstallPlugins:
      - command-launcher:1.3
      - jdk-tool:1.2
      - trilead-api:1.0.3

**Anything else we need to know**:
All other plugins get updated fine.

**Comment by torstenwalter** [comment]
Could it be that you updated the problematic plugins manually?

In that case please have a look at 
https://github.com/jenkinsci/docker/issues/790

**Comment by tretos53** [comment]
Thank you @torstenwalter. This is something I took over so there is a possibility that it's ben built that way. You can close this for now as I need to check those plugins in docker and it might take some time.
