### ISSUE TITLE
[stable/rabbitmq] pvc isn't purged on helm del --purge

### ISSUE THREAD

**Issue by raam86** [helm/charts#15715]
**Describe the bug**
As title suggest, helm del --pruge will not delete the PVCs which means newly generated passwords do not take 
**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Which chart**:
stable/rabbitmq

**What happened**:
returned value from
```
$(kubectl get secret --namespace drone rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"
```
was wrong

**What you expected to happen**:
The password should allow connection even if it's not the first time rabbitmq is installed on the cluster

**How to reproduce it** (as minimally and precisely as possible):
helm del purge leaves all the volume claims

**Comment by tompizmor** [comment]
Hello @raam86,

What you describe is a well-known limitation of Kubernetes statefulsets. 

> Deleting and/or scaling a StatefulSet down will not delete the volumes associated with the StatefulSet. This is done to ensure data safety, which is generally more valuable than an automatic purge of all related StatefulSet resources.

Original site: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations

**Comment by raam86** [comment]
the main problem is that the password seems to be associated with these volumes and del —purge despite its name doesn’t allow a clean helm install
