### ISSUE TITLE
[stable/sonarqube] misspelled Values key reference in pvc.yaml 

### ISSUE THREAD

**Issue by seansund** [helm/charts#15734]
**Describe the bug**
There is a typo in line 11 of the pvc.yaml file where it tries to reference `.Values.persistence.annotations` but instead is using `.Values.presistence.annotations`

**Version of Helm and Kubernetes**:
Helm: v2.14.2
Kubernetes: N/A

**Which chart**:
stable/sonarqube

**What happened**:
Error:
render error in "sonarqube/templates/pvc.yaml": template: sonarqube/templates/pvc.yaml:11:13: executing "sonarqube/templates/pvc.yaml" at <.Values.presistence.annotations>: nil pointer evaluating interface {}.annotations

**What you expected to happen**:
For the template to render

**How to reproduce it** (as minimally and precisely as possible):
Execute `helm template` with the chart using the following settings in values.yaml:

```
persistence:
  enabled: true
  existingClaim: false
```

**Anything else we need to know**:
Nope

**Comment by rjminchuk** [comment]
seeing the same
