### ISSUE TITLE
[meta] Deactive stale bot

### ISSUE THREAD

**Issue by krichter722** [helm/charts#15733]
The project seems to use stale bot which closes important issues which hasn't been dealt with after a certain time (e.g. https://github.com/helm/charts/issues/10949). Issues don't disappear after a time. The have to be resolved or a decision has to be made to close it. Closing them automatically is of no help for no project ever and causes the overhead that one day you have to figure out which issues are still present and need to be reopened.

More examples:
* https://github.com/helm/charts/issues/10275
* https://github.com/helm/charts/issues/11528
* #16079
* #3434
* and of course #15733 as of today :)

**Comment by rudolphjacksonm** [comment]
Here are just two issues that have had a lot of feedback from the community which have been closed by stale bot:
#10949
#1255

**Comment by Aisuko** [comment]
Hello guys, I agree with you guys. But there may a lot of issue for the project. So, we need to close some inactivate status issues. Would you guys like to join our slack channel name "charts", the address you can get in the README.md, and I believe the members and maintainers would be like to feedback some good points for this.

**Comment by pvorb** [comment]
It seems stale bot doesn't want to be deactivated.

**Comment by pvorb** [comment]
:(

**Comment by krichter722** [comment]
This an issue.
