### ISSUE TITLE
[stable/mysql] ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by marcadella** [helm/charts#15751]
**Describe the bug**
I run `helm install --name my-release stable/mysql` and get the root password as described. When I attempt to login as root WITHIN the pod (`kubectl exec -it pod/my-release-mysql-<pod_id> mysql -h 127.0.0.1 -u root -p<ROOT-PASSWORD>`), I get: `ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)`
Note that I do not use any PV as in #9942 and I used a fresh minikube "cluster".

**Version of Helm and Kubernetes**:
Helm:
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

Kubernetes:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/minio

**Comment by kekeliu-whu** [comment]
Same problem here.
