### ISSUE TITLE
[stable/postgresql] initdbScripts executed at each restart

### ISSUE THREAD

**Issue by mfvitale** [helm/charts#15757]
**Describe the bug**
By setting the init script works fine but if the pod is killed and restarted, the script are executed again.  This behavior occurs when 'postgresqlDataDir' and 'persistence.mountPath' are set to a different folder rather than the default.

**Version of Helm and Kubernetes**:
Helm : v2.14.1
Kubernetes: v1.11.0+d4cacc0

**Which chart**:
postgresql

**What happened**:
The file '.user_scripts_initialized' is not created 

**What you expected to happen**:
The file '.user_scripts_initialized' is created and the initscript will not be executed after pod restart.

**How to reproduce it** (as minimally and precisely as possible):
Set 'postgresqlDataDir' and 'persistence.mountPath' to a custom path (different from /bitnami/postgresql)

**Comment by tompizmor** [comment]
Hello @mfvitale,

Thanks for creating the issue. I just want to let you know that I was able to reproduce the issue.
We will work on a fix and update this issue once we have more information.

**Comment by tompizmor** [comment]
@mfvitale The PR is now merged. Can you try again using the latest chart?

**Comment by mfvitale** [comment]
> @mfvitale The PR is now merged. Can you try again using the latest chart?

Hi @tompizmor thanks. All works fine now.
