### ISSUE TITLE
[stable/graylog] Errors in an air-gap environment

### ISSUE THREAD

**Issue by OlliL** [helm/charts#15773]
The initContainer "setup" for Graylog just exits while logging the following:

```
Connecting to storage.googleapis.com (172.217.22.112:443)
wget: can't connect to remote host (172.217.22.112): Connection timed out
chmod: /k8s/kubectl: No such file or directory
```

Then having a look at the helm chart makes it clear:
https://github.com/helm/charts/blob/master/stable/graylog/templates/statefulset.yaml

`wget https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl -O /k8s/kubectl`

Wow - this is crazy - downloading kubectl from google everytime the Pod (re)starts? :(

Could you provide an values.yaml option to override the Download-URL so we could proxy the binary somewhere in our local infrastructure? Our clusters have no direct internet access.

**Comment by OlliL** [comment]
still relevant imho

**Comment by xavierzhao** [comment]
How to get `Init Container` logs? I have similar problems, but I get logs describe below:
```
/entrypoint.sh: line 6: /k8s/kubectl: No such file or directory
Current master is 
Launching graylog-0 as master
/entrypoint.sh: line 11: /k8s/kubectl: No such file or directory
Starting graylog
```

**Comment by OlliL** [comment]
Is there no active maintainer for this chart?
