### ISSUE TITLE
[stable/postgresql] custom metrics are not allowed

### ISSUE THREAD

**Issue by desaintmartin** [helm/charts#15798]
Documentation bug: The documentation (https://github.com/helm/charts/tree/master/stable/postgresql#metrics) states that custom metrics can be enabled. But there is no such parameter.

Is that expected?
cc @ prydonius @tompizmor @sameersbn @carrodher @javsalgar @juan131

**Comment by tompizmor** [comment]
@desaintmartin You are right! Currently the use of customMetrics is not supported so either we update the documentation or we we re-add customMetrics support. Originally it was added in this PR https://github.com/helm/charts/pull/791
