### ISSUE TITLE
Can't create additional dashboard for grafana in prometheus-operator

### ISSUE THREAD

**Issue by krakazyabra** [helm/charts#15811]
Hi! 
I can't add new custom dashboard for grafana. Can't understand, to what section in my values.yaml, put it. 
I'm using stable/prometheus-operator in helm. My values.yaml file is pretty simple and looks like example https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml
Can you, please, explain me with some examples?

**Comment by jnaulty** [comment]
I have tried the following documented steps and it works:
https://github.com/helm/charts/tree/0771fc7e4c3853c0b64e6b4a5ad7b4824d688db9/stable/grafana#sidecar-for-dashboards

**Comment by krakazyabra** [comment]
Thanks a lot! It was what i need! 
I had error while applying this configMap:
```
Error from server (BadRequest): error when creating "grafana-dashboards/alertmanager.yaml": ConfigMap in version "v1" annot be handled as a ConfigMap: v1.ConfigMap.ObjectMeta: v1.ObjectMeta.Namespace: Name: Labels: ReadString: expects "or n, but found 1, error found in #10 byte of ...|shboard":1},"name":"|..., bigger context ...|monitoring\"}}\n"},"labls":{"grafana_dashboard":1},"name":"sample-grafana-dashboard","namespace":"m|...
```
So helped to quote the grafana_dashboard's value. 
Thanks a lot.

**Comment by caarlos0** [comment]
so it seems that it only accepts strings on labels... 

although prometheus accepts things like `page: true` and works fine... is this intended?
