### ISSUE TITLE
Mongodb secondry pod Autometic restart

### ISSUE THREAD

**Issue by babalsurer** [helm/charts#15831]
I have deployed MongoDB and it is automatically restarted after some time and it is continually restarted. but my primary pod is working fine.
I have checked logs I got below error.
mongodb INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
2019-07-24T13:32:55.118+0000 E QUERY    [js] Error: not master and slaveOk=false :
_getErrorWithCode@src/mongo/shell/utils.js:25:13
DB.prototype.getUsers@src/mongo/shell/db.js:1763:1
@(shell eval):1:1

**Comment by miguelaeh** [comment]
Hi @babalsurer ,
Could you detail how did you deploy it?
