### ISSUE TITLE
[stable/grafana] problem with setting environment variable

### ISSUE THREAD

**Issue by smatyas** [helm/charts#15833]
**Describe the bug**

I want to set an evironment variable to grafana, namely **GF_PANELS_DISABLE_SANITIZE_HTML=true**.

When I try to set it through the values.yaml file, the install/upgrade fails like this:

```
UPGRADE FAILED
Error: render error in "prometheus-operator/charts/grafana/templates/deployment.yaml": template: prometheus-operator/charts/grafana/templates/deployment.yaml:249:30: executing "prometheus-operator/charts/grafana/templates/deployment.yaml" at <.Values.env.GF_SECURITY_ADMIN_USER>: can't evaluate field GF_SECURITY_ADMIN_USER in type interface {}
Error: UPGRADE FAILED: render error in "prometheus-operator/charts/grafana/templates/deployment.yaml": template: prometheus-operator/charts/grafana/templates/deployment.yaml:249:30: executing "prometheus-operator/charts/grafana/templates/deployment.yaml" at <.Values.env.GF_SECURITY_ADMIN_USER>: can't evaluate field GF_SECURITY_ADMIN_USER in type interface {}
``` 

As you can see, I actually use grafana through the stable/prometheus-operator chart, but I don't think that would be the issue here.

The interesting part of the values.yaml:
```
grafana:
  env:
    - GF_PANELS_DISABLE_SANITIZE_HTML: true
```

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.25", GitCommit:"d4c79083ab6dea5d26ef4ed8d50b145268349bc3", GitTreeState:"clean", BuildDate:"2019-06-22T16:10:31Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

```

Am I trying to set that env. var. in a wrong way? (Didn't really find an example of that.)
Or maybe these checks should be modified in the `deployment.yaml` in order to work in this case?
```
{{- if not .Values.env.GF_SECURITY_ADMIN_USER }}
...

{{- if not .Values.env.GF_SECURITY_ADMIN_PASSWORD }}
...
```

**Which chart**:

stable/grafana

**What happened**:

update fails

**What you expected to happen**:

set the environment variable

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by smatyas** [comment]
As a workaround, I can use the `envFromSecret` parameter to set the desired env. var.

**Comment by eskp** [comment]
Hey @smatyas get rid of the dashes (-) at the start.
Ps. nice display pic :D

**Comment by smatyas** [comment]
Aaaahhh thanks @eskp I totally missed that! :D 

So for the record, this is a working config:

```
grafana:
  env:
    GF_PANELS_DISABLE_SANITIZE_HTML: true
```
