### ISSUE TITLE
stable/mongodb Specifying mongodbUsername without mongodbDatabase causes primary node to fail during initialization

### ISSUE THREAD

**Issue by david-benes** [helm/charts#15895]
When you specify username but omit databaseName, a node (or the primary node in cluster) fails with non descriptive error:

```
INFO  ==> Validating settings in MONGODB_* env vars...
/libmongodb.sh: line 83: $1: unbound variable
```

Chart: stable/mongodb@6.2.0

I expect either a meaningful error to be logged or least to have a mention in docs about dependency between these two values. It might seem obvious for the values to depend on each other. However, without meaningful error I spent considerable amount of time debugging. I expected the user to be created in database `admin` by default.

How to reproduce:

Deploy the chart with only mongodbUsername value specified. I used this terraform config:

```
resource "helm_release" "mongodb" {
  name       = "my-mongodb"
  repository = data.helm_repository.stable.metadata[0].name
  chart      = "mongodb"

  set {
    name = "mongodbUsername"
    value = "myuser"
  }
}
````

**Comment by juan131** [comment]
Thanks so much for reporting this @david-benes !!! I just created a PR to address this issue

**Comment by juan131** [comment]
Hi @david-benes we just merged the PR addressing this issue.

Please feel free to give it a try and provide us any feedback, thanks in advance!

**Comment by david-benes** [comment]
Great job @juan131. I'll try and report back.
Thanks!

**Comment by david-benes** [comment]
Validation works perfectly. Now I received meaningful validation error.
Thanks again.

**Comment by juan131** [comment]
That's great @david-benes ! I'm glad my PR solved the issue!
