### ISSUE TITLE
Apache Kafka Helm Chart incubator - GKE Internal loadbalancer

### ISSUE THREAD

**Issue by ajayakumar-jayaraj** [helm/charts#15926]
**Describe the bug**
unable to create internal load balancer in GKE for kafka /incubator chart 

**Version of Helm and Kubernetes**:

SemVer:"v2.14.2" and   v1.13.7-gke.8
**Which chart**:
incubator/kafka 

**What happened**:
The internal loadbalancer is not working as intended. for example when we define " annotations:
    cloud.google.com/load-balancer-type: Internal 

Error:
003638a:kafka-qa $ helm install --name kafka-qa -f values.yaml incubator/kafka
Error: failed to parse values.yaml: error converting YAML to JSON: yaml: line 46: mapping values are not allowed in this context

**What you expected to happen**:
should be able to create internal load balancer . 

**How to reproduce it** (as minimally and precisely as possible):
define annotation with following param in values.yaml

annotations:
    cloud.google.com/load-balancer-type: Internal 

**Anything else we need to know**:

**Comment by ajayakumar-jayaraj** [comment]
is there any traction on it ? i still see the same error provisioning internal load balancer from values.yaml.

external:
  type: LoadBalancer
    annotations:
       cloud.google.com/load-balancer-type: Internal
  dns:
    useInternal: false
    useExternal: false



Error:

$ helm install --name kafka-qa -f values-internal.yaml incubator/kafka
Error: failed to parse values-internal.yaml: error converting YAML to JSON: yaml: line 22: mapping values are not allowed in this context

**Comment by viharikrishna** [comment]
How did you resolve this @ajayakumar-jayaraj?
