### ISSUE TITLE
[stable/dashboard] sidecar containers for dashboard

### ISSUE THREAD

**Issue by pierluigilenoci** [helm/charts#15939]
**Is your feature request related to a problem? Please describe.**
Many time I need to deploy the dashboard with a sidecar container (ex: an auth0 proxy like this https://github.com/trondhindenes/Kubernetes-Auth0 )
 
**Describe the solution you'd like**
I want to have the option to specify a sidecar container as a configurable parameter. 

**Describe alternatives you've considered**
No alternative

**Additional context**
Please take a look to Prometheus Helm chart:
https://github.com/helm/charts/blob/master/stable/prometheus/values.yaml#L508
https://github.com/helm/charts/blob/master/stable/prometheus/templates/server-deployment.yaml#L137-L139

Ref: https://github.com/kubernetes/dashboard/issues/4355

**Comment by vittoriocanilli** [comment]
That would be very useful for me as well!

**Comment by mvalenzisiAK** [comment]
I'd love to have this feature too!

**Comment by pierluigilenoci** [comment]
@ChiefAlexander or @taharah do you think that is it doable? Make sense for you?

**Comment by pierluigilenoci** [comment]
@kfox1111 or @desaintmartin do you think that is it doable? Make sense for you?

**Comment by desaintmartin** [comment]
Yes, it would! I think the implementation should be as generic as possible to support other sidecar use cases.

**Comment by pierluigilenoci** [comment]
I understand that if I want this thing I'll have to do it myself 😞

**Comment by desaintmartin** [comment]
Basically, yes, unless you want to pay someone to do it.

**Comment by pierluigilenoci** [comment]
I will do it in the next future...

**Comment by pierluigilenoci** [comment]
Not now... in the future :P

**Comment by pierluigilenoci** [comment]
I'll do, I promise! 😝

**Comment by pierluigilenoci** [comment]
But not now :P

**Comment by pierluigilenoci** [comment]
I don't have time now 😛

**Comment by pierluigilenoci** [comment]
Moved the feature request here https://github.com/kubernetes/dashboard/issues/5125
