### ISSUE TITLE
[stable/drone] sets DRONE_RPC_HOST wrongly

### ISSUE THREAD

**Issue by bokysan** [helm/charts#15965]
**Describe the bug**
The chart has some weird assumptions about `DRONE_RPC_HOST` and connections fail. Consequentially builds stop at `build: pending` stage. Could be linked to  #15381.

While:
- [`DRONE_SERVER_HOST`](https://github.com/helm/charts/blob/master/stable/drone/templates/deployment-server.yaml#L64) is set to `{{ .Values.server.host }}`, 
- [`DRONE_RPC_HOST`](https://github.com/helm/charts/blob/master/stable/drone/templates/deployment-server.yaml#L72) is set to `{{ template "drone.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.httpPort }}`. 

Consequentially, it does not work in my configuration, e.g.:
```
      DRONE_SERVER_HOST:                 drone.prod.example.org
      DRONE_RPC_HOST:                    drone-drone.backend
      DRONE_HOST:                        https://drone-ext.prod.example.org/
```

Because this variable is hard-coded into chart, it's also impossible to override it.

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: `stable/drone`

**What happened**: Drone will go into "building: pending" state because as it can't connect to the RPC URL.

**What you expected to happen**: Drone works.

**How to reproduce it**: 
- Make sure you have ingress enabled
- Make sure you have a host configured

**Anything else we need to know**:
`DRONE_RPC_HOST` should not be set automatically at all (in fact, user documentation states that if not set, `DRONE_SERVER_HOST` will be used) and with that allow the user to override it in the environment variables.

**Comment by hotung1027** [comment]
I have try to override the values in env for both server and agent,
While I also got the build stack in pending state.
Plus,  no agents deployed when I install the chart, I am not sure this is normal state._

**Comment by bokysan** [comment]
Dear stale bot, issue is still pending.

**Comment by grrowl** [comment]
I fixed this by explicitly adding `DRONE_RPC_PROTO: "http"` to the `env`:

```yaml
server:
  env:
    DRONE_RPC_PROTO: "http"
agent:
  env:
    DRONE_RPC_PROTO: "http"
```

now it connects to the in-cluster hostname using http, which works. 

not sure why this doesn't work in the first place, given this section of the chart's `values.yml`:

```yaml
          - name: DRONE_RPC_PROTO
            value: "{{ .Values.server.rpcProtocol }}"
```
