### ISSUE TITLE
[stable/prometheus-operator] Release "prometheus-operator" failed: rpc error: code = Canceled

### ISSUE THREAD

**Issue by rnkhouse** [helm/charts#15977]
**Describe the bug**
When I try to install prometheus operator on AKS with `helm install stable/prometheus-operator --name prometheus-operator -f prometheus-operator-values.yaml` I am getting this error:

>prometheus-operator" failed: rpc error: code = Canceled

I checked with history:

    helm history prometheus-operator -o yaml
    - chart: prometheus-operator-6.3.0
      description: 'Release "prometheus-operator" failed: rpc error: code = Canceled desc
        = grpc: the client connection is closing'
      revision: 1
      status: FAILED
      updated: Tue Jul 30 12:36:52 2019

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
[stable/prometheus-operator]

**Additional Info**
I am using below configurations to deploy a chart:

    kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/alertmanager.crd.yaml
    kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/prometheus.crd.yaml
    kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/prometheusrule.crd.yaml
     kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/servicemonitor.crd.yaml

In values file: `createCustomResource` is set to `false`,

**Comment by vsliouniaev** [comment]
This reads like an issue with Helm rather than the chart

**Comment by mariusv** [comment]
@rnkhouse run helm using `--max` and give it a smaller number like for example 5

**Comment by rnkhouse** [comment]
@mariusv You want me to run this command: `helm install stable/prometheus-operator --name prometheus-operator -f prometheus-operator-values.yaml --max 5`

**Comment by rnkhouse** [comment]
@mariusv 
helm history prometheus-operator --max=4
REVISION        UPDATED                         STATUS  CHART                           DESCRIPTION
1               Tue Jul 30 12:36:52 2019        FAILED  prometheus-operator-6.3.0       Release "prometheus-operator" failed: rpc error: code = C...

**Comment by pyadminn** [comment]
Just came across this error, also linked here: https://github.com/helm/helm/issues/6130
