### ISSUE TITLE
stable/cert-manager include cert-manager CRDs in helm chart

### ISSUE THREAD

**Issue by red8888** [helm/charts#15971]
why is cert-manager CRDs not just included in the chart? 

```
## IMPORTANT: you MUST install the cert-manager CRDs **before** installing the
## cert-manager Helm chart
$ kubectl apply \
    -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.6/deploy/manifests/00-crds.yaml

## IMPORTANT: if you are deploying into a namespace that **already exists**,
## you MUST ensure the namespace has an additional label on it in order for
## the deployment to succeed
$ kubectl label namespace <deployment-namespace> certmanager.k8s.io/disable-validation="true"

## Install the cert-manager helm chart
$ helm install --name my-release stable/cert-manager
```

I dont get it why that cant be included in the chart. This now means I cant just add cert-manager to my helm requirements.yaml for my app deploy- thats how helm is suppose to work right? Ill have to roll my own chart to get what I assume is expected helm behavior ie add dependent charts in requirements.yaml.

**Comment by florianrusch** [comment]
@red8888 can you pls change the title of this issue to `[stable/cert-manager] Include cert-manager CRDs in helm chart`? Properly this issue is then better seen by other devs.

@munnerz @simonswine @kragniz Do you have an explanation for us why we have to install the CRDs separately? I would like to install this helm chart with the helm terraform provider which isn't possible in reason of this. 🙁

**Comment by red8888** [comment]
Now that I understand this better I can see this is really a helm issue. Helm has no way of ordering dependencies so you can't ensure the crd is installed before actually creating resources that use it

Really stinks and limits it's usefulness hopefully they'll fix it

**Comment by florianrusch** [comment]
Helm has already some kind of a solution for that: <https://github.com/helm/helm/blob/master/docs/chart_best_practices/custom_resource_definitions.md#install-a-crd-declaration-before-using-the-resource>

They provide two possible methods of how you can achieve the ordered installation (For details take a look at the link above):
1. Separate Helm Charts
2. Crd-install Hooks

In this use-case, I think it would make sense to use the crd-install hooks. That the CRD's are not deleted, if the helm chart was deleted, can be neglected in my opinion.

**Comment by red8888** [comment]
Right but you still cant order dependancies. So even using those methods if you add this chart as a requirement to a parent chart that needs to use the resource helm wont ensure the crd is installed first- someone can correct me if im wrong

perhaps the current most popular way of working around this helm limitation (till they fix it) is to use separate charts and use helmfile? helmfile can order dependancies right?

**Comment by florianrusch** [comment]
@red8888 I think the idea of the 1. method was to install it manually.
what do you think about the 2. method?

**Comment by iMartyn** [comment]
I would really like to see option 1 implemented.  We use helmfile to deploy our clusters' infrastructure charts and it's not really sensible to "just `kubectl apply` the manifests".  I would appreciate a cert-manager-crds helm chart.

Right now I'm having to create a local helm chart from the existing CRDs, but that's not sensible in the long term.

**Comment by iMartyn** [comment]
For the people who stumble upon this in the future, here's my script to convert the CRDs to a helm chart :
https://gist.github.com/iMartyn/842b8cba758f0a554db87395f84cb9e6
