### ISSUE TITLE
[stable/kube-slack] chart is completely broken

### ISSUE THREAD

**Issue by Simon3** [helm/charts#15988]
**Describe the bugS**
- The chart has been subject to a lot of backward-incompatible changes with no warning at all, even though it is "stable". No major version bump, no message in the README, nothing. 
- The chart is not following helm/charts conventions (e.g. "envVars" instead of "env", no table summarizing configuration values). 
- The README is completely obsolete. It is still talking about variables that are not used anymore, like "--set slackUrl=webhook-url" which is now "--set envVars.SLACK_URL", and it's not talking about the other values that are required to install the chart (and yeah, that were not required in the previous version). 
- NOTES.txt is still using the previous variable, so it will print a warning message if your configuration is correct, but will not print it if you are using the old, incorrect configuration...
- values.yaml has other problems too. Comments are incorrect: username and channel are inverted, and seem broken too: it says "override username to send" while the chart actually doesn't install if you don't specify it. But even if you specify it, the username doesn't seem to be overriden anyway. 
- Using --set envVars.NOT_READY_MIN_TIME doesn't work because """ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found 1""" (I tried with 150000 and "150000" but none of them works). 
- There are probably other bugs and incoherences, I didn't really dig very deep. 

**Version of Helm and Kubernetes**:
Kubernetes 1.14.1, Helm 2.13.0

**Which chart**:
 stable/kube-slack

**What happened**:
The chart is broken

**What you expected to happen**:
It should be easy to install the chart following instructions from README. Currently it's even worse since the README is not juste lacking informations but is also providing wrong informations. 

**How to reproduce it** (as minimally and precisely as possible):
Try to install the chart. 

**Anything else we need to know**:
This chart needs consequent maintenance, and should probably be downgraded to incubator if it can't be fixed quickly because it is currently a mess.

**Comment by PierluigiLenociAkelius** [comment]
@Simon3 feel free to fix it 😘
