### ISSUE TITLE
[stable/velero] Restic daemonset AWS_SHARED_CREDENTIALS_FILE variable 

### ISSUE THREAD

**Issue by paralika** [helm/charts#15998]
**Describe the bug**
`AWS_SHARED_CREDENTIALS_FILE` environment variable should be skipped/removed if we disable `useSecret` in values file. 

**Version of Helm and Kubernetes**:
Helm version - v2.14.3. 
Kubernetes Version - v1.15.1

**Which chart**:
Velero 

**What happened**:
`AWS_SHARED_CREDENTIALS_FILE` environment variable is getting added into restic daemonset even though I disable useSecret `useSecret: false`. 

**What you expected to happen**:
`AWS_SHARED_CREDENTIALS_FILE` environment variable should be skipped/removed if we disable `useSecret` in values file. 

**How to reproduce it** (as minimally and precisely as possible):
1. Disable useSecret - `useSecret: false`.
2. Change directory to Velero charts.
3. Run - `helm template . --output-dir velero_yaml

**Anything else we need to know**:
N/A

**Comment by hectorj2f** [comment]
@paralika Why do we need to skip `AWS_SHARED_CREDENTIALS_FILE` to set this env variable when running on AWS ? Could you explain better the scenario where this could be the case ?

**Comment by paralika** [comment]
@hectorj2f We need to make `useSecret` to `false` to use the KIAM.  In this case, we dont want AWS/GCP creadentials in file. Also it should not initialize `AWS_SHARED_CREDENTIALS_FILE`  (or GCP) environment variable.  In fact  `AWS_SHARED_CREDENTIALS_FILE`  is referring to mount point `/credentials/cloud` which is not getting created if `useSecret` is `false`. 
 
I have observed this behavior in Restic daemonset only.

**Comment by paralika** [comment]
@hectorj2f  Here is environment variable values from restic pod. As I made `useSecret` to `false` it did not mount secret (credential file) at /credentials/cloud but still setting `AWS_SHARED_CREDENTIALS_FILE` variable. 

>kubectl exec -ti restic-48w5j -n velero sh
>>$ env | grep AWS
>>AWS_SHARED_CREDENTIALS_FILE=/credentials/cloud
>>$ ls -l /credentials/cloud
>>ls: cannot access '/credentials/cloud': No such file or directory
>>$ ls -l /credentials
>>ls: cannot access '/credentials': No such file or directory
