### ISSUE TITLE
[stable/rabbitmq-ha] spec.clusterIP: Invalid value: "None": may not be set to 'None' for LoadBalancer services

### ISSUE THREAD

**Issue by cilerler** [helm/charts#16010]
I'm getting an error message below

```
Error: release rabbitmq failed: Service "rabbitmq-rabbitmq-ha" is invalid: spec.clusterIP: Invalid value: "None": may not be set to 'None' for LoadBalancer services
```

when I run the code below

```
helm install stable/rabbitmq-ha --name rabbitmq --namespace default --set image.tag=3.7.17-alpine,ingress.enabled=true,service.ClusterIP="",service.type=LoadBalancer,persistentVolume.enabled=true,replicaCount=1,rabbitmqPassword=test,managementPassword=test;
```

please locate `service.ClusterIP=""` in it which I found it in [here]( https://github.com/helm/charts/issues/14888)

**Comment by steven-sheehy** [comment]
It's `service.clusterIP=""`. Case is important.

**Comment by cilerler** [comment]
@steven-sheehy nice catch.  Thank you

![bitmoji](https://render.bitstrips.com/v2/cpanel/c2b30773-81da-48f8-a618-2ae9193aeb5c-1d989a62-ae8a-48a8-b04f-0f575358153a-v1.png?transparent=1&palette=1&width=246)
