### ISSUE TITLE
[stable/postgresql] pod won't start (not a valid data directory)

### ISSUE THREAD

**Issue by ljohnston** [helm/charts#16022]
**Describe the bug**
With helm chart v6.2.0 and image.tag 10.7.0-ol-7-r78, a new deployment fails.

Here's the pod log:
```
23:05:20.42 Welcome to the Bitnami postgresql container
23:05:20.42 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
23:05:20.42 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
23:05:20.42 Send us your feedback at containers@bitnami.com
23:05:20.42
23:05:20.43 INFO  ==> ** Starting PostgreSQL setup **
23:05:20.48 INFO  ==> Validating settings in POSTGRESQL_* env vars..
23:05:20.49 INFO  ==> Initializing PostgreSQL database...
23:05:20.49 INFO  ==> postgresql.conf file not detected. Generating it...
23:05:20.50 INFO  ==> pg_hba.conf file not detected. Generating it...
23:05:20.51 INFO  ==> Deploying PostgreSQL with persisted data...
23:05:20.51 INFO  ==> Configuring replication parameters
23:05:20.53 INFO  ==> Loading custom scripts...
23:05:20.53 INFO  ==> Enabling remote connections
23:05:20.54 INFO  ==> Stopping PostgreSQL...
23:05:20.55 INFO  ==> ** PostgreSQL setup finished! **

23:05:20.59 INFO  ==> ** Starting PostgreSQL **
2019-07-26 23:05:20.603 GMT [1] LOG:  skipping missing configuration file "/bitnami/postgresql/data/postgresql.auto.conf"
2019-07-26 23:05:20.604 GMT [1] FATAL:  "/bitnami/postgresql/data" is not a valid data directory
2019-07-26 23:05:20.604 GMT [1] DETAIL:  File "/bitnami/postgresql/data/PG_VERSION" is missing.
```

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```
Kubernetes version is 1.14.1

**Which chart**:
stable/postgresql v6.2.0

**What happened**:
The postgresql pod failed to start with the above error message.

**What you expected to happen**:
Expected the pod to start.

**How to reproduce it** (as minimally and precisely as possible):
The simplest `helm install ...` of the specified chart and image version will reproduce the issue.

**Anything else we need to know**:
I worked around the issue by modifying the chart as follows...

In templates/statefulset.yaml I changed this:
```
             mkdir -p {{ .Values.persistence.mountPath }}/data
             chmod 700 {{ .Values.persistence.mountPath }}/data
             find {{ .Values.persistence.mountPath }} -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | \
               xargs chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }}
```
To this:
```
             for f in $(find {{ .Values.persistence.mountPath }} -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found"); do
               chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }} $f
             done
```
Note the following from the log output shown above:
```
23:05:20.51 INFO  ==> Deploying PostgreSQL with persisted data...
```
The docker container entrypoint looks for a directory called `data` at the configured `persistence.mountPath`. If that directory exists, it assumes that a database has already been initialized in that location (and displays the above info message). That directory gets created by the `init-chmod-data` initContainer in the statefulset, but it is an empty directory. At the end of the log, you can see that the error comes from the subsequent postgresql start, which fails due to there being no database initialized in that location.

**Comment by miguelaeh** [comment]
Hi @ljohnston ,
Thank you for reporting and start with a workaround. I have tried your solution but it seem the pod starts but it is never on the ready state:
```
NAME                          READY     STATUS    RESTARTS   AGE
coy-woodpecker-postgresql-0   0/1       Running   0          1h
```

**Comment by ljohnston** [comment]
Hi @miguelaeh ,
No, that is not the behavior I would expect, nor is it what I am seeing. The pod(s) should be ready. Are you using the same chart and image versions?

**Comment by miguelaeh** [comment]
Yes, I deployed using the chart version `6.2.0` and the image tag `10.7.0-ol-7-r78`.

I deployed it on a GKE cluster could you tell me what is your environment?

**Comment by ljohnston** [comment]
Custom built cluster in OCI (Oracle Cloud Infrastructure). What do your pod describes and logs look like?

**Comment by ljohnston** [comment]
@miguelaeh - My apologies... I actually had the issue with the pods being ready, but hadn't seen it because during the time I was working through this, I'd disabled the readiness probe in the chart and forgotten to re-enable it. Once I did, I ended up with the same issue you were seeing.

The following changes should resolve it:

templates/statefuleset.yaml and templates/statefuleset-slaves-yaml:
```
      initContainers:
      - name: init-chmod-data
        image: {{ template "postgresql.volumePermissions.image" . }}
        imagePullPolicy: "{{ .Values.volumePermissions.image.pullPolicy }}"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        command:
          - sh
          - -c
          - |
            for f in $(find {{ .Values.persistence.mountPath }} -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found"); do
              chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }} $f
            done
            if [ -d {{ .Values.persistence.mountPath }}/data ]; then
              chmod  0700 {{ .Values.persistence.mountPath }}/data;
            fi
```

remove the following from templates/_helpers.tpl:
```
{{- if contains "bitnami/" .Values.image.repository }}
  [ -f /opt/bitnami/postgresql/tmp/.initialized ]
{{- end -}}
```

**Comment by miguelaeh** [comment]
Hi @ljohnston ,
Thank you very much for the work around, we have created a PR with your changes that will be reviewed as soon as possible.

**Comment by miguelaeh** [comment]
Hi @ljohnston ,
Why are you interested in use that image version? I checked this problem does not appear with the newest versions and the PR seems to not have to much sense for the latest versions.

**Comment by dNetGuru** [comment]
Running into the same issue here.
