### ISSUE TITLE
[stable/mongodb] initdb.d scripts are not getting executed post container startup

### ISSUE THREAD

**Issue by Srimrao02** [helm/charts#16032]
**Describe the bug**
.js and .sh files are not getting executed post container startup

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

We are using openshift container platform 3.11 with kubernetes version 1.11.0+d4cacc0

**Which chart**:
mongodb chart

**What happened**:
Post container startup, i want to create a new DB and set of users and roles with the scripts i have placed, container starts up but my initdb scripts are not executed.
I have verified by trying to login to new db inside container.

**What you expected to happen**:
DB and user should have been created.

**How to reproduce it** (as minimally and precisely as possible):
Always when I try to deploy with below command

`helm install --name my-updated-mongodb mongodb/ --namespace testdb`

**Anything else we need to know**:

- I have copied mongodb chart locally, modified as per our need.
- Below are 2 scripts i have kept under "files/docker-entrypoint-initdb.d/".
- My container startup and even I can see those 2 files mounted inside my container

> creat-user-roles.js

```
//create new database
db = db.getSiblingDB('configdb');

//create a user with read access
db.createUser(
{
    user: "svc_developer",
    pwd: "test12345",
    roles: [
              { role: "read", db: "configdb" },
           ]
});

//create user with read and write access
db.createUser(
{
    user: "svc_admin",
    pwd: "admin12345",
    roles: [
              { role: "readWrite", db: "configdb" },
           ]
});
```

> configdb.sh

`mongo -u root -p ${MONGODB_ROOT_PASSWORD} < /docker-entrypoint-initdb.d/create-user-roles.js`

**On the container:**

> $ hostname
> my-updated-mongodb-55f5d7f57c-97lln
> $ ls -lrth /docker-entrypoint-initdb.d
> total 0
> lrwxrwxrwx. 1 root root 27 Aug  1 12:21 create-user-roles.js -> ..data/create-user-roles.js
> lrwxrwxrwx. 1 root root 23 Aug  1 12:21 configdb-init.sh -> ..data/configdb-init.sh

If I login to container and execute below command, I can see DB is created and also the users for that DB.

`mongo -u root -p ${MONGODB_ROOT_PASSWORD} < /docker-entrypoint-initdb.d/create-user-roles.js`

Any guidance would be helpful, I'm new to helm.

**Comment by j15r** [comment]
I can confirm this problem:

**Description:**
When trying to initialize the mongodb with an init-script (js-file) an ConfigMap is created and the script is mounted into the mongodb pod, but it is not executed during first boot.

**What happened:**
1. Cloned latest mongodb helm-chart
2. Add init script to /files/docker-entrypoint-initdb.d folder (insert into user collection)
3. Configured values (mainly enabled replicaset, set gp2 storageClass, mongodbUsername, mongodbPassword and mongodbDatabase)
4. Run helm install --name <name> --values ./mongodb/mongo-values.yaml --namespace <namespace> ./mongodb/
5. The collection is empty after connecting to the mongodb via robo3t. When checking inside the container, I can see that the script is copied into the /docker/entrypoint-initdb.d folder, but seems not to be executed by the mongodb.

**Version of Helm and Kubernetes:**
Client: &version.Version{SemVer:“v2.14.2”, GitCommit:“a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:“clean”}
Server: &version.Version{SemVer:“v2.14.2", GitCommit:“a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7”, GitTreeState:“clean”}
Server Version: version.Info{Major:“1”, Minor:“13+“, GitVersion:“v1.13.7-eks-c57ff8”, GitCommit:“c57ff8e35590932c652433fab07988da79265d5b”, GitTreeState:“clean”, BuildDate:“2019-06-07T20:43:03Z”, GoVersion:“go1.11.5”, Compiler:“gc”, Platform:“linux/amd64”}

**Chart:**
stable/mongodb

**Comment by alemorcuq** [comment]
Hi, @Srimrao02, @j15r.

This is a known issue with our container: the feature was left out by mistake when we migrated the scripts to Bash. We are working on bringing it back. 

Sorry for the inconvenience.

**Comment by Srimrao02** [comment]
Thanks for the update @alemorcuq

**Comment by alemorcuq** [comment]
Hi, @Srimrao02, @j15r.

We've released a new bunch of containers that reimplement this feature. They are the following:

- `3.6.13-debian-9-r67`
- `3.6.13-ol-7-r69`
- `4.0.11-debian-9-r14`
- `4.0.11-ol-7-r14`
- `4.1.13-debian-9-r74`
- `4.1.13-ol-7-r77`

Please, let us know if it's working as expected for you.

Regards,
Alejandro

**Comment by j15r** [comment]
Seems to be working now. Thanks for the update.

Regards,
Johannes
