### ISSUE TITLE
[stable/redis] metrics sidecars don't work when using passwordFile and sentinel

### ISSUE THREAD

**Issue by twk3** [helm/charts#16049]
**Describe the bug**

When using a passwordFile for redis, and enabling metrics and sentinel. The following error appears in the metrics sidecar:

```
Redis INFO err: NOAUTH Authentication required.
```

The redis_exporter doesn't support the `REDIS_PASSWORD_FILE` env anymore, so it fails. Related issue here: https://github.com/oliver006/redis_exporter/issues/277

I've tried using `metrics.extraArgs` to cat in the password file, but haven't been able to get it quite working yet. 

**Version of Helm and Kubernetes**:
Helm: v2.12.3
Kubernetes: v1.12.8-gke.10

**Which chart**:

stable/redis

**What happened**:

metrics sidecar is throwing errors

**What you expected to happen**:

metrics sidecar works without throwing errors

**How to reproduce it** (as minimally and precisely as possible):

- `metrics.enabled=true`
- `sentinels.enabled=true`
- `usePasswordFile=true`
- `existingSecret=<your secret with password>`

**Anything else we need to know**:

**Comment by miguelaeh** [comment]
Hi @twk3 ,
Thank you very much for reporting this, we will update the chart as soon as possible, in the meantime you can try using the `extraArgs` section of the `values.yaml` file to pass the password as explained in the issue you referenced.

**Comment by miguelaeh** [comment]
Hi @twk3 ,
That PR should solve the problem you was facing. Let us know if you find more issues.
Thank you very much for reporting it!!!
