### ISSUE TITLE
[stable/prometheus-operator] Upgrade kube-state-metrics to v1.7.1

### ISSUE THREAD

**Issue by wlai-axway** [helm/charts#16056]
The current prometheus-operator installs kube-state-metrics v1.6.0 (chart versuib 2.0.0) which has security vulnerabilities and it's running as root. KSM v1.7.1 have all the issues fixed and is available through chart version 2.1.0 or greater. Can someone upgrade the chart requirement to use version 2.1.*?

**Comment by mitchellmaler** [comment]
kube-state-metrics 1.7.1 was just announced to include a CVE. Now we need the chart updated to  2.2.3 to include version 1.7.2 which has the security fix.
