### ISSUE TITLE
[stable/rabbitmq-ha] Can we bring up the cluster if all nodes go down?

### ISSUE THREAD

**Issue by atmosx** [helm/charts#16053]
If we bring down all nodes simultaneously the cluster cannot get back up because all nodes, old master included, are looking for a cluster node that is up to connect to. I get the idea that this is a known/expected behaviour reading the discussion on https://github.com/helm/charts/issues/7682 .

So in case all nodes go down at the same time, can we somehow restore the cluster without losing data?

**Comment by steven-sheehy** [comment]
You have two options:

1. Use `forceBoot=true` if you don't care about data integrity and prefer availability
2. Use `podManagementPolicy=Parallel` if you don't care about availability and prefer integrity. You can't enable this option on an existing statefulset. You'll have to delete and install chart again.

**Comment by atmosx** [comment]
> You have two options:
> 
> 1. Use `forceBoot=true` if you don't care about data integrity and prefer availability
> 2. Use `podManagementPolicy=Parallel` if you don't care about availability and prefer integrity. You can't enable this option on an existing statefulset. You'll have to delete and install chart again.

Thanks for the reply @steven-sheehy ! Can you please elaborate a bit on (2)? Does the stateful set pod management policy play a role in the way auto-discovery/election works? 

What is the expected behaviour if a launch a cluster with 5 nodes and stateful set pods management policy `podManagementPolicy=Parallel`, then delete all pods at the same time? Will the pods get back in parallel (old master too) and restore the cluster?
