### ISSUE TITLE
stable/external-dns oracle cloud infrastructure (oci) support

### ISSUE THREAD

**Issue by srflaxu40** [helm/charts#16051]
Can we get provider support for OCI?

We are currently utilizing the incubator for deployment to oci, and would like to use the helm chart if possible. Thanks!

**Comment by juan131** [comment]
Sure @srflaxu40 !! Thanks for the suggestion

I guess you're following this guide: https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/oracle.md

Do you want to make the contribution to the chart yourself? I'd be glad to review your PR if you add support for OCI. 

In case you're requesting the community to add it, I'd open a task and we'd try to work on adding this feature as soon as possible.
