### ISSUE TITLE
zipking

### ISSUE THREAD

**Issue by JsanchezPilo** [helm/charts#16072]
**Describe the bug**
when i try to send traces from istio to zipkin port it doesn work 

**Version of Helm and Kubernetes**:
helm version 2.13.1
kubernetes version 1.15.0

**Which chart**:

jaeger collector 

**What happened**:
zipkin port doesnt work even when i used it as nodePort it is closed

**What you expected to happen**:

zipkin port available to send traces

**How to reproduce it** (as minimally and precisely as possible):

i am not really sure 

**Anything else we need to know**:

**Comment by sah4ez** [comment]
Hi, everyone!
Seems that missed `--collector.zipkin.http-port` in args for linux-collector.
If set this values manually, like as `--collector.zipkin.http-port 9411`, the log of collector contains lines with successful start http server on 9411 port.
