### ISSUE TITLE
Chart stable/suitecrm not found

### ISSUE THREAD

**Issue by hwinkel** [helm/charts#1609]
**Is this a request for help?**:

YES

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG

Chart stable/suitecrm not found

**Version of Helm and Kubernetes**:

$ helm version

Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}

$ kubectl version

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

stable/suitecrm

**What happened**:

$ helm search stable/suitecrm
No results found

**What you expected to happen**:

$ helm install stable/suitecrm would install the application

**How to reproduce it** (as minimally and precisely as possible):

$ helm search stable/suitecrm
$ helm install stable/suitecrm

**Anything else we need to know**:

Cloudprovider: GKE

**Comment by unguiculus** [comment]
Works fine for me. The chart is pretty new and your cache is probably outdated. `helm repo update` should fix this.

**Comment by hwinkel** [comment]
@unguiculus hey, of course, after update it appears in the list and deploys. Thanks

But now i have a not bound volume for the mariadb

PersistentVolumeClaim is not bound: "hwi-suitecrm-mariadb" (repeated 3 times)

**Comment by unguiculus** [comment]
Did you wait long enough? It can take some time till the volumes are bound.
