### ISSUE TITLE
[stable/nextcloud] use of configs: section leads to broken permissions of config directory

### ISSUE THREAD

**Issue by himpierre** [helm/charts#16090]
**Describe the bug**
I'm using the rather new feature of a configs: section to configure a few extra settings in nextcloud. But this leads in combination with a mounted persitent volume to broken permissions. This is how it looks without a configs: section:

```
drwxr-xr-x. 42 www-data root  4096 Aug  5 13:55 apps
drwxr-xr-x.  2 www-data root  4096 Aug  5 13:56 config
-rw-r--r--.  1 www-data root  3805 Aug  5 13:55 console.php
```

And this is with a configs: section:

```
drwxr-xr-x. 42 www-data root  4096 Aug  5 13:03 apps
drwxr-xr-x.  2 root     root  4096 Aug  5 13:03 config
-rw-r--r--.  1 www-data root  3805 Aug  5 13:03 console.php
```

So with that permissions nextcloud is not able to finish the setup because it's not able to write to the config directory.
This only happens if persitence.enabled is set to true.

**Version of Helm and Kubernetes**: helm version v2.14.3, kubernetes 1.14.1

**Which chart**: nextcloud/stable

This is the configs: section in question:

```
  configs:
    redis.config.php: |-
      <?php
      $CONFIG = array (
        'memcache.distributed' => '\OC\Memcache\Redis',
        'memcache.locking' => '\OC\Memcache\Redis',
        'memcache.local' => '\OC\Memcache\Redis',
        'redis.cluster' => [
              'seeds' => [
                      'redis-cluster:6379'
              ],
              'timeout' => 0.0,
              'read_timeout' => 0.0,
              'failover_mode' => \RedisCluster::FAILOVER_DISTRIBUTE
              ],
      );
    extra.config.php: |-
      <?php
      $CONFIG = array (
        'overwrite.cli.url' => 'https://mydomain',
        'overwriteprotocol' => 'https',
        #        'installed' => true,
      );
```

It works in general if no persistent volume is mounted.

**Comment by himpierre** [comment]
Adding

```
      securityContext:
        runAsUser: 0
        runAsGroup: 33
        fsGroup: 33
```

to deployment.yaml solves the issue for me now.

**Comment by abheyogy** [comment]
I face the same issue. If I change the configuration via. the values.yaml provided as a official channel to configure mongo, the container fails as it is not having the right permissions to write to the configuration files.

**Comment by chrisingenhaag** [comment]
/assign 
That was fixed in the meantime with adding securityContext.fsGroup: 33 in deployment.

https://github.com/helm/charts/blob/master/stable/nextcloud/templates/deployment.yaml#L248

**Comment by chrisingenhaag** [comment]
related / duplicate by #15741
