### ISSUE TITLE
[stable/postgresql] Kubernetes helm stable postgresql deployment - DB read/write traffic split-up

### ISSUE THREAD

**Issue by erdarun** [helm/charts#16109]
**Version of Helm and Kubernetes**:
Helm - 2.12
Kubernetes - 1.13.2

**Which chart**: 
stable/postgresql

**What happened**:
We have deployed 3 instances of postgresql with the setup of 1 master and 2 slaves

We can see below services up and running,

> pg-ha-v1-postgresql                    5432/TCP
> pg-ha-v1-postgresql-headless   5432/TCP
> pg-ha-v1-postgresql-metrics     9187/TCP
> pg-ha-v1-postgresql-read          5432/TCP

**What you expected to happen**:
As per the bitnami documentation,
https://engineering.bitnami.com/articles/worried-about-big-data-scale-up-with-bitnami-secure-fault-tolerant-postgresql-cluster.html

> Data automatically replicates from the master node to all slave nodes. The master node receives all write operations, while the slave nodes repeat the operations performed by the master node on their own copies of the data set and are used for read operation. This model improves the overall performance of the solution. It also simplifies disaster recovery, because a copy of the data is maintained on each node in the cluster.

**Need to know how the above concept of query parsing implemented using headless service and read service on helm stable/postgresql chart deployment?**

**Expectation is that application read request should be served by slave nodes for performance gain while write operations restricted only to master**

values.yaml: synchronousCommit: "on", numSynchronousReplicas: 1

> pg-ha-v1-postgresql endpoints only to master
> pg-ha-v1-postgresql-read endpoints only to slaves
> pg-ha-v1-postgresql-headless endpoints points to all 3 instances of master & slaves

_**Please share more details on whether read/write traffic split is implemented in helm bitnami postgresql chart if so how it's done to know more background details on the same.**_

**Comment by juan131** [comment]
Hi @erdarun 

I noticed you opened the same issue at https://github.com/bitnami/bitnami-docker-postgresql/issues/161

Please let's continue the discussion there to avoid confusion. Thanks in advance.
