### ISSUE TITLE
[stable/prometheus-operator] collecting same metrics 

### ISSUE THREAD

**Issue by taizoKaneko** [helm/charts#16121]
**Describe the bug**
Prometheus collects the same metric twice.

**Version of Helm and Kubernetes**:
Kubernetes v1.15.1
Helm v2.14.3

**Which chart**:
prometheus-operator

**What happened**:
Two metrics with the similar value can be obtained by executing the following query.
query: 
```
container_memory_rss{pod="prometheus-billowing-duck-prometheus-prometheus-0", container!="POD", container!="prometheus-config-reloader", container!="rules-configmap-reloader"}
```
result:
<img width="886" alt="screenshot" src="https://user-images.githubusercontent.com/35514631/62568212-b10e0700-b8c7-11e9-8431-64cfca2431d8.png">

and grafana shows twice the amount of memory
For reference, query is
```
sum(container_memory_rss{cluster="$cluster", namespace="$namespace", pod_name="$pod", container_name!="POD", container_name!=""}) by (container_name)
```

**What you expected to happen**:
Just one metric should be collected.

**How to reproduce it** (as minimally and precisely as possible):
I could reproduce by installing default values.yaml

**Anything else we need to know**:
Prometheus and Alertmanager has two Endpoints, Headless service and Cluster IP.
In kubernetes_sd_config, `Role` of the job that scrapes the kubelet is `Endpoint`, so I think prometheus may collect it twice.

**Comment by taizoKaneko** [comment]
I just understood that prometheus role and grafana dashboards were copied.
So it was wrong to post here.

**Comment by akrueger0602** [comment]
@taizoKaneko How did you fix this please?
I'm seeing the same thing...memory metrics show up twice and hence the grafana dashboards show twice the memory on pods than the k8s api.

**Comment by taizoKaneko** [comment]
Sorry, I don't know why it was solved in my environment.

As above reference, query should be changed If problems happen.
For example, 
https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml#L439

Or, if you delete the old chart and create a new one,  kubelet service needs to be cleaned up.
> Because the kubelet service has a new name in the chart, make sure to clean up the old kubelet service in the kube-system namespace to prevent counting container metrics twice.

**Comment by vfiset** [comment]
@akrueger0602 what did you end up doing ? 

I don't get what @taizoKaneko and the chart README refer to by`clean up the old kubelet service in the kube-system namespace`. I don't see any service that is duplicated 🤔 

🆘

**Comment by meanwhy** [comment]
In my case. There is an extra exporter endpoint in the namespace "kube-system".
After I delete that, everything works fine.
