### ISSUE TITLE
[stable/fluentd-graylog] Need to a helm chart for fluentd send log to graylog

### ISSUE THREAD

**Issue by thodquach** [helm/charts#16131]
**Is your feature request related to a problem? Please describe.**
Currently, we only have helm chart for fluent send log to elasticsearch [stable/fluentd-elasticsearch].
I see a lot of people using fluent daemondset to send to from k8s-cluster to graylog but we dont have a specific helm chart for this purpose.

**Describe the solution you'd like**
I see fluent already implement docker images for fluent send log to graylog server on their repo:
https://github.com/fluent/fluentd-kubernetes-daemonset
And we already have helm chart for graylog: [stable/graylog]
I want we create a helm chart for fluent send log to graylog server.
Just like [stable/fluentd-elasticsearch], we can create [stable/fluentd-graylog].
And we also can create a stack for logging call graylog-stack combine 2 helm chart:
- [stable/graylog]
- [stable/fluentd-graylog]

Just the same to elastic-stack [stable/elastic-stack]
I think the helm chart [stable/fluentd-graylog] will be very useful and helpful for the one who want to use graylog instead of elastic-stack (ELK)
Hope my idea is cool enough to implement. 👍  🎉

**Comment by oscarlofwenhamn** [comment]
We recently started using something akin to [this setup](https://vzurczak.wordpress.com/2019/02/13/using-graylog-for-centralized-logs-in-k8s-platforms-and-permissions-management/), using the [vincent-zurczak/fluentbit-configuration-for-k8s-and-graylog](vincent-zurczak/fluentbit-configuration-for-k8s-and-graylog) deployment to send logs. Some modification of the ConfigMap was required (add IP of graylog host and potential other customizations) but other than that it seems to be working like a charm. That could potentially be used as a basis for the helm chart.

**Comment by thodquach** [comment]
> We recently started using something akin to [this setup](https://vzurczak.wordpress.com/2019/02/13/using-graylog-for-centralized-logs-in-k8s-platforms-and-permissions-management/), using the [vincent-zurczak/fluentbit-configuration-for-k8s-and-graylog](vincent-zurczak/fluentbit-configuration-for-k8s-and-graylog) deployment to send logs. Some modification of the ConfigMap was required (add IP of graylog host and potential other customizations) but other than that it seems to be working like a charm. That could potentially be used as a basis for the helm chart.

Tks @oscarlofwenhamn ! I will keep it a try :D
Thanks for the thing you suggest I found somethings interest that I could send log to graylog server.

👍

**Comment by thodquach** [comment]
Tks @oscarlofwenhamn , the configmap of 'vincent-zurczak/fluentbit-configuration-for-k8s-and-graylog' is woking for me, and i can using fluent-bit to send log to graylog.

Tks for your kindness
👍
