### ISSUE TITLE
[stable/prometheus-operator] PrometheusRule Admission Webhooks broke Istio support

### ISSUE THREAD

**Issue by r3kzi** [helm/charts#16147]
**Describe the bug**
With https://github.com/helm/charts/commit/b469d491e2cefcfa43b7b2c7c98ebd4259890aa6 new ressources werde added. Especially new `Job` ressources, e.g. https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml.

This breaks support for Istio, since the job will keep running so long as the sidecar proxy is running and eventually the deployment fails. 

See https://github.com/istio/istio/issues/6324.

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**Which chart**:
stable/prometheus-operator

**What you expected to happen**:
Add the possibility to add addition annotations to disable sidecard injection

**Comment by christianwoehrle** [comment]
Could you disable the sidecar for this job with the annotation?
```
sidecar.istio.io/inject
```

**Comment by r3kzi** [comment]
@christianwoehrle sure...i would happily do it :-)

But the `stable/prometheus-operator` Helm chart does not allow to set additional `podMetadata` or `podAnnotations` for the `Job` resources that were created with https://github.com/helm/charts/commit/b469d491e2cefcfa43b7b2c7c98ebd4259890aa6 :-(

The only way it would work is to hack this into after a `helm template` ;-)
