### ISSUE TITLE
[incubator/couchdb] Readiness probe failed

### ISSUE THREAD

**Issue by mojabyte** [helm/charts#16155]
Readiness probe failed and all pods are in CrashLoopBackOff state
Deploying on minikube

**Version of Helm and Kubernetes**:

Helm Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

Kubernetes Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T17:09:13Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}

minikube version: v1.3.0

**Which chart**:
incubator/couchdb/

**What happened**:
Readiness probe failed: Get http://172.17.0.10:5984/_up: dial tcp 172.17.0.10:5984: connect: connection refused
Back-off restarting failed container

**How to reproduce it**:
 helm install incubator/couchdb

**Comment by rkleine** [comment]
Hi @HassanMojab I cant reproduce it. Im using minikube on OS X 10.13.6

*Version of Helm and Kubernetes:*
```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:52:26Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by HassanMojab** [comment]
The connection to the DB was taking more time than probe's FailureThreshold because of my slow system so I've fixed it by setting `initialDelaySeconds` it in the `statefulset.yaml` template file under the `readinessProbe` and `livenessProbe`.
