### ISSUE TITLE
[stable/mongodb-replicaset] readinessProbe error when auth is enabled

### ISSUE THREAD

**Issue by openJT** [helm/charts#16151]
**Describe the bug**
When using the chart and enabling auth, there is a periodic error: Unauthorized: not authorized on admin to execute command { endSessions: [ { id: UUID("f596e869-5cfd-40bb-894d-a63673468896") } ], $db: "admin" }

Seems related to the readinessProbe, I can use the database with user credentials normaly.

**Version of Helm and Kubernetes**:
Kubernetes versions: Client 1.15.2, server 1.13.5
Helm: v2.13.1, also tried 2.14.3

**Which chart**:
stable/mongodb-replicaset

**What happened**:
Getting error:
Unauthorized: not authorized on admin to execute command { endSessions: [ { id: UUID("f596e869-5cfd-40bb-894d-a63673468896") } ], $db: "admin" }

**What you expected to happen**:

ReadinessProbe to be able to connect

**How to reproduce it** (as minimally and precisely as possible):

helm install --name mongo stable/mongodb-replicaset --set auth.enabled=true,auth.adminUser=admin,auth.adminPassword=admin1234,auth.key=test 

**Anything else we need to know**:

Works when auth is not enabled.

**Comment by steven-sheehy** [comment]
Don't know how to fix it. Suggestions?

**Comment by openJT** [comment]
I don't have a suggestion but it still is an issue
