### ISSUE TITLE
[stable/rethinkdb] Storage Class value not being applied to PVCs

### ISSUE THREAD

**Issue by marct83** [helm/charts#1618]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:

Helm:
Client: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}

Kubernetes:
v1.7.2

**Which chart**:

rethinkdb

**What happened**:

Persistent Volume Claims not being created for the Storage Class being set in the values file or by the variable in the --set

**What you expected to happen**:

PVC be created using the storage class speicifed.

**How to reproduce it** (as minimally and precisely as possible):

helm install stable/rethinkdb --set cluster.persistentVolume.storageClass=rook-block

**Comment by zedtux** [comment]
@marct83 please re-open this issue.
