### ISSUE TITLE
[stable/mongodb-replicaset] mongodb-service-client name length

### ISSUE THREAD

**Issue by plod** [helm/charts#16190]
**Describe the bug**
The mongodb-service-client template sets the name sometimes to larger than 63 characters because the truncate happens before appending -client

**Version of Helm and Kubernetes**:
v2.14.3 v1.12.10-eks-2e569f

**Which chart**:
stable/mongodb-replicaset

**What happened**:
When I had a large namespace I was deploying in, I got `value: “*****************-2-mongodb-replicaset-client”: must be no more than 63 characters

**What you expected to happen**:
the service to start

**How to reproduce it** (as minimally and precisely as possible):
deploy the chart in a very long namespace

**Anything else we need to know**:
I don't think so

**Comment by plod** [comment]
If it's okay I'll do a pr to fix it

**Comment by rafariossaa** [comment]
Hi @plod,
   That would be great !
