### ISSUE TITLE
[stable/nginx-ingress] high availability / production configuration

### ISSUE THREAD

**Issue by aegershman** [helm/charts#16192]
**Version of Helm and Kubernetes**:
helm 2.14.x, k8s 1.13.x, latest nginx-ingress (1.13.x)

The default configuration of [`nginx-ingress`](https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L200) will cause an outage during cluster upgrades, chart upgrades, etc.

I'm having difficulty finding info on how people configure `nginx-ingress` *for production purposes*.

So with that said:

## **How should the nginx-ingress be configured for high availability?**

- [By default, nginx-ingress is configured to use 1 pod replica.](https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L198). I presume this should be at least 2? Will 2 give me HA? (How is this affected by [`minAvailable?`](https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L200))

- The [`minAvailable`](https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L200) is set to 1. If you deploy this entirely default (with `replica` to 1), then presumably the pod will never be terminated due to the pod disruption budget? If the `replica` count is `2`, will the PDB of `1` be satisfied? Do I need `3` pods minimum? Should I be concerned if all pods are scheduled on the same node...?

- [There aren't affinity rules by default](https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L142-L165); is this important? Should only one controller pod be scheduled per node? If I leave this blank, is there the possibility of an outage?

- [There is no default update strategy](https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L120-L123) (should it be rolling...?) Does this matter?

- Do most people entirely forego `nginx-ingress` and use a `service: LoadBalancer` for production uses? Do they use a different `Ingress` provider? Considering [`nginx-ingress` is in the `kubernetes/` org](https://github.com/kubernetes/ingress-nginx/issues) I assume it's fairly official, but do people rely on it?

Consider this a "pre-emptive fix to a pre-emptive bug report" 😉 This issue sounded a little complain-y, but I don't mean it that way. I just legitimately need advice and haven't found resources on how people use this in production.

Thanks for your time.

**Comment by marcelomanchester** [comment]
@aegershman it's alredy became an issue for me, do you know how to fix this problem? 
I'm having this problem in production...

**Comment by pranas** [comment]
In short: you should bump the pod replica count to >1 and you should set affinity rules for the replicas to be deployed on other nodes and preferably in other availability zones. Depending on the cluster size you may also want to increase `minAvailable` value so that even during pod updates or node upgrades you would still have at least the `minAvailable` number of pods available (on a small cluster higher `minAvailable` value + pod affinity rules might make it unschedulable during certain situations).
