### ISSUE TITLE
[stable/velero] Using credentials.secretContents

### ISSUE THREAD

**Issue by Thorfinn3** [helm/charts#16198]
**Describe the bug**
I don't found the way to use credentials.secretContents for Velero installation

**Version of Helm and Kubernetes**:
Kubernetes : 1.14.3
Helm: 2.14.3

**Which chart**:
stable/velero

**What happened**:
I can't install velero charts because of the credentials.secretContents and I don't found how to use this parameter, I tried like that : `helm install --namespace velero --set configuration.provider=aws,credentials.secretContents='{ aws_access_key_id : minio,aws_secret_access_key : minio123 }}',configuration.backupStorageLocation.bucket=velero,configuration.backupStorageLocation.name=aws,use-volume-snapshots=false,configuration.backupStorageLocation.config.region=minio,configuration.backupStorageLocation.config.s3ForcePathStyle=true,configuration.backupStorageLocation.config.s3Url=http://127.0.0.1:9000 stable/velero`

Error was : 
`An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = NoCredentialProviders: no valid providers in chain. Deprecated.`

**What you expected to happen**:
Success installation

**Comment by DandyDeveloper** [comment]
@Loken3 You need to use the standard `key: value` but with the value being read as a large string. 

E.G.

```
secretContents:
  cloud: :-
    aws_access_key: <blahblah>
   aws_secret_access_key: <blahblahblah>
```
