### ISSUE TITLE
[stable/prometheus-operator] Cant override alertmanager.config 

### ISSUE THREAD

**Issue by Martinlcksybo** [helm/charts#16202]
Cannot override the value alertmanager.config

**Version of Helm and Kubernetes**:
Helm: v2.14.1
GKE: 1.13.7-gke.8

**Which chart**:
prometheus-operator

**What happened**:
When trying to override the value alertmanager.config I get an error: 

Merging destination map for chart 'prometheus-operator'. Cannot overwrite table item 'config', with non table value: map[global:map[resolve_timeout:5m] receivers:[map[name:null]] route:map[group_by:[job] group_interval:5m group_wait:30s receiver:null repeat_interval:12h routes:[map[match:map[alertname:Watchdog] receiver:null]]]]

It does not make sense, because even if you pass an argument to a file that does not exists, it always spits the same error, like if is trying to use default values or smth

**What you expected to happen**:
I expect to use the values I'm passing

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/prometheus-operator --namespace monitoring --set alertmanager.config={any yaml file}

**Anything else we need to know**:

**Comment by Martinlcksybo** [comment]
Even when I add --set alertmanager.config={"global":{"resolve_timeout":"5m"},"route":{"group_by":["job"],"group_wait":"30s","group_interval":"5m","repeat_interval":"12h","receiver":"null","routes":[{"match":{"alertname":"Watchdog"},"receiver":"null"}]},"receivers":[{"name":"null"}]} 

Which is the default, it does not work

**Comment by vsliouniaev** [comment]
I think your best approach is to use a values file to do overrides - setting complicated values using `set` syntax gets out of hand very quickly

**Comment by ferzescu** [comment]
at least this possibility should exist in case it presented in documentation. I also experience this issue
