### ISSUE TITLE
[stable/mysql] MySQL 5.7.14 crashes/restarts on connection

### ISSUE THREAD

**Issue by tf** [helm/charts#16222]
**Describe the bug**
MySQL pod starts normally and enters ready state. Soon as a connection from another pod is established, the pod restarts. Client prints error of the form:
```
Lost connection to MySQL server at 'reading authorization packet', system error: 0.

```
Changing the MySQL image version to 5.7.15 or above makes the error go away.

**Version of Helm and Kubernetes**:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}                                                                                              
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}   
$ helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}                                                                                                           
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}        
```

**Which chart**:
stable/mysql

**What happened**:
When moving the MySQL pod between nodes, I noticed that my application was no longer able to establish database connections. The MySQL pod would become ready on the new node, but then restart without any error message in the logs (I checked Kubernetes cluster logs, container logs, MySQL error logs and syslog inside the container and syslog on the node).

When new versions of the app pods were deployed as part of the same Helm upgrade, I noticed that the error only happened when the old app pods interacted with MySQL. If there were no requests during deploy, accessing the database from the new pods worked fine.

**What you expected to happen**:
MySQL not to crash. 

**How to reproduce it** (as minimally and precisely as possible):
I tried to find the simplest way to reproduce the problem and was able to strip away most of the complexity of the MySQL chart and my own resources. I still do not understand why this is happening, but removing any of the remaining ingredients makes the problem go away.

I created a [gist containing this minimal setup](https://gist.github.com/tf/cf3e07c8a83f917dc21053dc152b1799).

Changing the image version to 5.7.15 or above makes the error go away.

I was able to reproduce this on both Minikube and an RKE cluster. A lot of other problem descriptions related to MySQL restarts pointed to memory or other resource limit problems. This does not appear to be the case here, though. The nodes always had enough memory and inspecting the stopped Docker container showed that OOM flag was false.

If anybody can shed some light on why this might be happening, I'd be more than interested.

**Anything else we need to know**:

I suggest updating the image version inside this chart to prevent other's from running into similar issues.

**Comment by cwrau** [comment]
Happens to us as well, upgrading to 5.7.27 works

**Comment by salanki** [comment]
Same thing for me. 5.7.27 fixed it.

**Comment by Tarick** [comment]
Same, 5.7.27 fixed the problem. Moreover, chart appVersion is 5.7.27, but imageTag is 5.7.14.
