### ISSUE TITLE
[stable/prometheus] Prometheus-server init container crash loop

### ISSUE THREAD

**Issue by SharaaEsper** [helm/charts#16236]
**Describe the bug**

**Version of Helm and Kubernetes**:
Helm v2.13.1
Kubernetes 1.12.10 on EKS

**Which chart**:
stable/prometheus

**What happened**:
Using a non-default values file to set configurations for alert manager (So either alertmanagerFiles or serverFiles) causes the init container for prometheus-server to go into a crashloop, as it attempts to chown /data and gets permission denied. 

**What you expected to happen**:
The init container to work and then spin up the prometheus-server

**How to reproduce it** (as minimally and precisely as possible):
Take the default values.yaml and modify either alertmanagerFiles or serverFiles with anything.

**Comment by maven2016** [comment]
Same issue/similar

Helm v2.13.1
Kubernetes 1.12.10 on EKS

helm install stable/prometheus --name my-release -f values.yaml

the command above fails with the original values.yaml file.

executing with --set, i.e
helm install stable/prometheus --name my-release --namespace prometheus --set <enter parameters here>
works fine.
