### ISSUE TITLE
nginx-ingress does not provide RBAC support

### ISSUE THREAD

**Issue by rk295** [helm/charts#1623]
**FEATURE REQUEST?**

**Version of Helm and Kubernetes**:

***Kubernetes***:

    Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

***Helm***:

    Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
    Server: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}

**Which chart**:

`nginx-ingress`

**What happened**:

Chart did not deploy a `ServiceAccount`, `ClusterRole` or `Role` on a RBAC enabled cluster.

**What you expected to happen**:

Chart should deploy a `ServiceAccount`, `ClusterRole` or `Role` on a RBAC enabled cluster.

**How to reproduce it**:

`helm install stable/nginx-ingress` - on a RBAC enabled cluster.

**Anything else we need to know**:

The `nginx-ingress` team provide an example of all the required resources [here](https://github.com/kubernetes/ingress/blob/master/examples/rbac/nginx/nginx-ingress-controller-rbac.yml).

**Comment by MarkusTeufelberger** [comment]
should be fixed since https://github.com/kubernetes/charts/pull/1235 got merged, right?

**Comment by unguiculus** [comment]
Alreay fixed.
