### ISSUE TITLE
Prometheus servicemonitor doesn't work out of the box

### ISSUE THREAD

**Issue by psblah** [helm/charts#16250]
the release label needs to be whatever your prometheus deployment is set to look for in servicemonitors (in my case Release: prometheus).

Does this need to be changed to a configurable value instead of just Release.Name?

inside:
charts/stable/nginx-ingress/templates/controller-servicemonitor.yaml

**Comment by vsliouniaev** [comment]
This value is configurable through `prometheus.prometheusSpec.serviceMonitorSelector`
