### ISSUE TITLE
[stable/prometheus-operator] Allow setting annotations for the Prometheus instance

### ISSUE THREAD

**Issue by garo** [helm/charts#16272]
In order to run a Thanos sidecar which uploads data to an S3 bucket with IAM Instance Role it is required that an annotation gets placed to the Prometheus pod (assuming the system is using kube2iam to provide AWS IAM roles).

The prometheus-operator seems to support this with the podMetadata field in PrometheusSpec

**Describe the solution you'd like**
I would like that the chart values.yaml supports defining a podMetadata structure which gets propagated to the created Prometheus pod.

**Comment by OtavioHenrique** [comment]
@garo I'm facing the same problem, do you have any solution?

**Comment by garo** [comment]
@OtavioHenrique I found out that the chart actually supports that already, pretty much just as I described in this issue - I just didn't see it by myself until I wrote this.

Unfortunately I don't have my notes nearby but I think it is/was the prometheus.prometheusSpec.podMetadata in values.yaml

**Comment by OtavioHenrique** [comment]
@garo Thank you very much :)
