### ISSUE TITLE
[stable/postgresql] PVC not deleted even with annotations "helm.sh/resource-policy: delete"

### ISSUE THREAD

**Issue by almahmoud** [helm/charts#16286]
**Describe the bug**
I want to set the data PVC deployed with Postgres to be deleted with the chart. Given that the PVC is not deployed through an explicit manifest, I thought the way to go is adding to annotations:
`helm.sh/resource-policy: delete`, done through `--set "postgresql.persistence.annotations.helm\.sh/resource-policy"="delete"`
However, although the annotation properly appears on the PVC, it is not deleted with the chart (even when using the `--purge` flag).

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/postgresql

**What happened**:
The PVC is not deleted.

**What you expected to happen**:
The PVC should be deleted.

**How to reproduce it** (as minimally and precisely as possible):
```
helm install stable/posgresql --set "persistence.annotations.helm\.sh/resource-policy"="delete" --name test-del
helm del --purge test-del
```

**Anything else we need to know**:
Installing `postresql` as a dependency for another chart.

**Comment by carrodher** [comment]
I think this case is not related to the chart implementation but an issue in the Helm behavior.
This issue is describing something similar: https://github.com/helm/helm/issues/5156, can you confirm if this is your issue?
