### ISSUE TITLE
[stable/grafana] Notification Channels / Notifiers as Secrets

### ISSUE THREAD

**Issue by c089** [helm/charts#16308]
I've been setting up immutable deployments of grafana using the helm chart with and like it a lot so far! A thing that I missed today was the ability to provide notification channel configuration via kubernetes `secret` resources, as they often contain credentials such as passwords or API tokens for notification services.

**Comment by c089** [comment]
And just now I realized it could probably just be done by binding a secret to environment variable and using environment substitution in the provisioning file....

**Comment by wcarlsen** [comment]
We are facing the same issue as @c089 and being able to mount notifiers as a secret would increase security a lot.

**Comment by HenrikStanley** [comment]
My team is also facing a security issue with the token for our slack channel being exposed in the configmap.

Being able to define the notifier as a secret would help mitigate this.
