### ISSUE TITLE
[stable/postgresql] create non admin user

### ISSUE THREAD

**Issue by MarcinGinszt** [helm/charts#16316]
**Describe the bug**
postgresqlUsername creates a user with password stored in the secret normally associated with the user postgres, but the user is not an admin. 
Example:

> helm install stable/postgresql --set postgresqlUsername=example --set postgresqlDatabase=example

> psql -U example
> Password for user example:
> psql (11.5)
> Type "help" for help.
>
> example=> \du
>                                   List of roles
>  Role name |                         Attributes                         | Member of
> -----------+------------------------------------------------------------+-----------
> postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
>  example  | Create DB                                                  | {}

**What you expected to happen**:

User example should have admin permissions. Especially, that there is no possiblity to log to Postgres user to add permissions for the user specified with postgresqlUsername.

**Comment by marcosbc** [comment]
Hi @MarcinGinszt, it seems like you're trying to do advanced customizations (e.g. creating multiple databases, users and so on).

In this case, it is probably better you keep `postgresqlUsername` set to `postgres`, and configure your custom database structure with initdb scripts as mentioned in the [Initialize a fresh instance](https://github.com/helm/charts/tree/master/stable/postgresql#initialize-a-fresh-instance) section in the README.

As for not being able to log in as the `postgres` user, this is explained in the [bitnami/bitnami-docker-postgresql](https://github.com/bitnami/bitnami-docker-postgresql) repository:

>**Note!** When `POSTGRESQL_USERNAME` is specified, the `postgres` user is not assigned a password and as a result you cannot login remotely to the PostgreSQL server as the `postgres` user. If you still want to have access with the user postgres, please set the `POSTGRESQL_POSTGRES_PASSWORD` environment variable (or the content of the file specified in `POSTGRESQL_POSTGRES_PASSWORD_FILE`).

Unfortunately the chart does not support setting the `POSTGRESQL_POSTGRES_PASSWORD` environment variable right now.

**Comment by MarcinGinszt** [comment]
I am afraid, you didn't understand me. I simply want to create an admin user via postgresqlUsername, as specified in the README file. Currently, this variable it just creates a normal user.

**Comment by marcosbc** [comment]
Hi @MarcinGinszt, sorry for the delay. It seems like we lost track of this issue in our GitHub issue tracking system.

As for your issue, like we mentioned currently it's not possible as you can see in the logic: [libpostgresql.sh#L433](https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-9/rootfs/libpostgresql.sh#L433)

We've created an internal task for discussing the current approach, and fixing the current approach if we agree to do so.

We'll keep this ticket updated with any news.

**Comment by sameersbn** [comment]
@MarcinGinszt we are currently exploring the possible solutions to this issue. One of which is to add a new `postgresPostgresPassword` chart parameter that allows you to change the password of the `postgres` user when a custom username  (`postgresqlUsername`) is in use. This can be found at https://github.com/bitnami/charts/pull/1555.

Please take a look and let us know if this addresses the issue you face.
