### ISSUE TITLE
stable/prometheus-operator

### ISSUE THREAD

**Issue by brotherat** [helm/charts#16319]
failed install perform step: timed out waiting for the condition

Adding tiller log:

[tiller] 2019/08/14 12:09:59 preparing install for prometheus-operator
[storage] 2019/08/14 12:09:59 getting release history for "prometheus-operator"
[tiller] 2019/08/14 12:09:59 rendering prometheus-operator chart using values
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/grafana/configmap-dashboards.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/prometheus-operator/cleanup-crds.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/charts/kube-state-metrics/templates/servicemonitor.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/prometheus/additionalAlertRelabelConfigs.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/exporters/kube-scheduler/endpoints.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/exporters/kube-dns/service.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/charts/grafana/templates/ingress.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/prometheus/additionalAlertmanagerConfigs.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/prometheus/ingress.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/prometheus/additionalScrapeConfigs.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/alertmanager/ingress.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/exporters/kube-etcd/endpoints.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/charts/grafana/templates/pvc.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/alertmanager/podDisruptionBudget.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/charts/prometheus-node-exporter/templates/monitor.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/exporters/kube-controller-manager/endpoints.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/prometheus/podDisruptionBudget.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/charts/prometheus-node-exporter/templates/endpoints.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/templates/exporters/kube-dns/servicemonitor.yaml" is empty. Skipping.
2019/08/14 12:10:00 info: manifest "prometheus-operator/charts/grafana/templates/dashboards-json-configmap.yaml" is empty. Skipping.
[tiller] 2019/08/14 12:10:00 performing install for prometheus-operator
[tiller] 2019/08/14 12:10:00 executing 14 crd-install hooks for prometheus-operator
[kube] 2019/08/14 12:10:00 building resources from manifest
[kube] 2019/08/14 12:10:00 creating 1 resource(s)
[kube] 2019/08/14 12:10:01 building resources from manifest
[kube] 2019/08/14 12:10:01 creating 1 resource(s)
[kube] 2019/08/14 12:10:02 building resources from manifest
[kube] 2019/08/14 12:10:02 creating 1 resource(s)
[kube] 2019/08/14 12:10:03 building resources from manifest
[kube] 2019/08/14 12:10:03 creating 1 resource(s)
[kube] 2019/08/14 12:10:04 building resources from manifest
[kube] 2019/08/14 12:10:04 creating 1 resource(s)
[tiller] 2019/08/14 12:10:05 hooks complete for crd-install prometheus-operator
[tiller] 2019/08/14 12:10:05 executing 14 pre-install hooks for prometheus-operator
[tiller] 2019/08/14 12:10:05 deleting pre-install hook prometheus-operator-admission for release prometheus-operator due to "before-hook-creation" policy
[kube] 2019/08/14 12:10:05 Starting delete for "prometheus-operator-admission" ServiceAccount
[kube] 2019/08/14 12:10:05 Waiting for 60 seconds for delete to be completed
[kube] 2019/08/14 12:10:07 building resources from manifest
[kube] 2019/08/14 12:10:07 creating 1 resource(s)
[kube] 2019/08/14 12:10:07 Watching for changes to ServiceAccount prometheus-operator-admission with timeout of 5m0s
[kube] 2019/08/14 12:10:07 Add/Modify event for prometheus-operator-admission: ADDED
[tiller] 2019/08/14 12:10:07 deleting pre-install hook prometheus-operator-admission for release prometheus-operator due to "before-hook-creation" policy
[kube] 2019/08/14 12:10:07 Starting delete for "prometheus-operator-admission" ClusterRoleBinding
[kube] 2019/08/14 12:10:07 Waiting for 60 seconds for delete to be completed
[kube] 2019/08/14 12:10:09 building resources from manifest
[kube] 2019/08/14 12:10:09 creating 1 resource(s)
[kube] 2019/08/14 12:10:09 Watching for changes to ClusterRoleBinding prometheus-operator-admission with timeout of 5m0s
[kube] 2019/08/14 12:10:09 Add/Modify event for prometheus-operator-admission: ADDED
[tiller] 2019/08/14 12:10:09 deleting pre-install hook prometheus-operator-admission for release prometheus-operator due to "before-hook-creation" policy
[kube] 2019/08/14 12:10:09 Starting delete for "prometheus-operator-admission" RoleBinding
[kube] 2019/08/14 12:10:09 Waiting for 60 seconds for delete to be completed
[kube] 2019/08/14 12:10:11 building resources from manifest
[kube] 2019/08/14 12:10:11 creating 1 resource(s)
[kube] 2019/08/14 12:10:11 Watching for changes to RoleBinding prometheus-operator-admission with timeout of 5m0s
[kube] 2019/08/14 12:10:11 Add/Modify event for prometheus-operator-admission: ADDED
[tiller] 2019/08/14 12:10:11 deleting pre-install hook prometheus-operator-admission for release prometheus-operator due to "before-hook-creation" policy
[kube] 2019/08/14 12:10:11 Starting delete for "prometheus-operator-admission" ClusterRole
[kube] 2019/08/14 12:10:11 Waiting for 60 seconds for delete to be completed
[kube] 2019/08/14 12:10:13 building resources from manifest
[kube] 2019/08/14 12:10:13 creating 1 resource(s)
[kube] 2019/08/14 12:10:13 Watching for changes to ClusterRole prometheus-operator-admission with timeout of 5m0s
[kube] 2019/08/14 12:10:13 Add/Modify event for prometheus-operator-admission: ADDED
[tiller] 2019/08/14 12:10:13 deleting pre-install hook prometheus-operator-admission for release prometheus-operator due to "before-hook-creation" policy
[kube] 2019/08/14 12:10:13 Starting delete for "prometheus-operator-admission" Role
[kube] 2019/08/14 12:10:13 Waiting for 60 seconds for delete to be completed
[kube] 2019/08/14 12:10:15 building resources from manifest
[kube] 2019/08/14 12:10:15 creating 1 resource(s)
[kube] 2019/08/14 12:10:15 Watching for changes to Role prometheus-operator-admission with timeout of 5m0s
[kube] 2019/08/14 12:10:15 Add/Modify event for prometheus-operator-admission: ADDED
[tiller] 2019/08/14 12:10:15 deleting pre-install hook prometheus-operator-admission for release prometheus-operator due to "before-hook-creation" policy
[kube] 2019/08/14 12:10:15 Starting delete for "prometheus-operator-admission" PodSecurityPolicy
[kube] 2019/08/14 12:10:15 Waiting for 60 seconds for delete to be completed
[kube] 2019/08/14 12:10:17 building resources from manifest
[kube] 2019/08/14 12:10:17 creating 1 resource(s)
[kube] 2019/08/14 12:10:17 Watching for changes to PodSecurityPolicy prometheus-operator-admission with timeout of 5m0s
[kube] 2019/08/14 12:10:17 Add/Modify event for prometheus-operator-admission: ADDED
[tiller] 2019/08/14 12:10:17 deleting pre-install hook prometheus-operator-admission-create for release prometheus-operator due to "before-hook-creation" policy
[kube] 2019/08/14 12:10:17 Starting delete for "prometheus-operator-admission-create" Job
[kube] 2019/08/14 12:10:17 Waiting for 60 seconds for delete to be completed
[kube] 2019/08/14 12:10:19 building resources from manifest
[kube] 2019/08/14 12:10:19 creating 1 resource(s)
[kube] 2019/08/14 12:10:19 Watching for changes to Job prometheus-operator-admission-create with timeout of 5m0s
[kube] 2019/08/14 12:10:19 Add/Modify event for prometheus-operator-admission-create: ADDED
[kube] 2019/08/14 12:10:19 prometheus-operator-admission-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
[tiller] 2019/08/14 12:15:19 warning: Release prometheus-operator pre-install prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml could not complete: timed out waiting for the condition
[tiller] 2019/08/14 12:15:19 failed install perform step: timed out waiting for the condition

**Comment by vsliouniaev** [comment]
Could you please post the logs from failed job pods?

**Comment by brotherat** [comment]
No pods were deployed at all
Posting additional info for the environment, hope might be useful:

[root@CentosVM ~]# helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

openshift v3.11.104
kubernetes v1.11.0+d4cacc0

**Comment by vsliouniaev** [comment]
This log line indicates there was an issue with some job
```
[tiller] 2019/08/14 12:15:19 warning: Release prometheus-operator pre-install prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml could not complete: timed out waiting for the condition
```

Could you check what's happening with jobs? If pods aren't being created perhaps the job is not able to proceed?

**Comment by brotherat** [comment]
This is the error message received at job creation: 

Warning   FailedCreate   job-controller   Error creating: pods "prometheus-operator-admission-create-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 2000: must be in the ranges: [1000240000, 1000249999]]

**Comment by brotherat** [comment]
It seems, the issue is only OpenShift related. I'll try creating specific SCC that allows runasuser with value 2000

**Comment by vsliouniaev** [comment]
You can submit a pull request that makes this value configurable if this is necessary for your case.
I'm not sure why a low value is common but I've seen it used a bunch of times.

**Comment by brotherat** [comment]
Sending some details on OpenShift SCC and Service Accounts:
https://blog.openshift.com/understanding-service-accounts-sccs/
https://docs.openshift.com/container-platform/3.11/admin_guide/manage_scc.html
Most probably the helm package will not work with OCP >= 3.0 out of the box, few workaround are possible.
