### ISSUE TITLE
facing a not master and slaveOk=false error. 

### ISSUE THREAD

**Issue by haseebnaseem** [helm/charts#1631]
**Is this a request for help?**:
yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

I am facing a `not master and slaveOk=false` error even after executing rs.slaveOk() in the bash terminals of all the nodes on deploying mongodb replicaset. 
Any help would be highly appreciated.

**Comment by Thermi** [comment]
I encounter this, too. This completely breaks the mongodb cluster making it useless.

**Comment by haseebnaseem** [comment]
@Thermi have you been able to resolve this error?

**Comment by Thermi** [comment]
@haseebnaseem No.

**Comment by haseebnaseem** [comment]
@Thermi have you deployed mongodb cluster using some other or are you using any other database now ?

**Comment by Thermi** [comment]
We switched to a SAAS offering that solved seamless up- and downscaling for us, too. It is much better than hosting it yourself.

**Comment by martin-liu** [comment]
Same issue here. See also https://github.com/kubernetes/charts/issues/1569

To work around, I'm using mongo url `mongodb://myns-mongodb-replicaset-0.myns-mongodb-replicaset.myns.svc.cluster.local/mydb,myns-mongodb-replicaset-1.myns-mongodb-replicaset.myns.svc.cluster.local/mydb,myns-mongodb-replicaset-2.myns-mongodb-replicaset.myns.svc.cluster.local/mydb` to let client determine master

**Comment by Mtax** [comment]
Same problem. Any one solved?

**Comment by grantga** [comment]
@Mtax we hit this as well and I believe what happens is that the internal mongo replica set configuration has old pod ips that are no longer valid after a redeploy. 

If you remote into the mongo primary pod you can see the replicat set configuration with:
`cfg = rs.conf()`
which gives:
```   "_id" : "rs0",
   "version" : 1,
   "protocolVersion" : NumberLong(1),
   "members" : [
      {
         "_id" : 0,
         "host" : "mongodb0.example.net:27017",
         "arbiterOnly" : false,
         "buildIndexes" : true,
         "hidden" : false,
         "priority" : 1,
         "tags" : {

         },
         "slaveDelay" : NumberLong(0),
         "votes" : 1
      },
```

In my case all the members were pointing to old IPs. 

I updated them to the current pod IPs as follows:
```
rs0:OTHER> cfg.members[0].host = "10.244.0.116:27017"
10.244.0.116:27017
rs0:OTHER> cfg.members[1].host = "10.244.0.115:27017"
10.244.0.115:27017
rs0:OTHER> cfg.members[2].host = "10.244.0.113:27017"
10.244.0.113:27017
```
Then applied the config with:
rs0:OTHER> rs.reconfig(cfg, {force: true})

And my connections started to work again.

I'm thinking this a bug in the chart where the rs config is setup but have not investigated yet.

**Comment by ath88** [comment]
This was fixed by https://github.com/helm/charts/pull/7096, fyi.
