### ISSUE TITLE
[stable/mongodb] Issue with attempting to enable TLS between nodes in the cluster 

### ISSUE THREAD

**Issue by kwill4026** [helm/charts#16320]
**Describe the bug**:

I am in the process of setting up TLS/SSL into the mongodb helm chart for secure communication between the mongod's and its servers. I am testing using self signed certs. I am aware I must first create a CA and its private key, create the server cert and sign this server cert with the CA cert. I then concatenate it to a pem file for use in all the nodes in the cluster. When running my script, the CA cert changes in each node instead of it being the same CA cert for the primary node and all the secondaries. 

**Version of Helm and Kubernetes**:
```
Helm Version:
 Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

Kubernetes: 
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-29T16:15:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-2e569f", GitCommit:"2e569fd887357952e506846ed47fc30cc385409a", GitTreeState:"clean", BuildDate:"2019-07-25T23:13:33Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: 
```
stable/mongodb
```

**What happened**:
Attempting to create self signed certs to enable TLS support with a init script causes my root CA cert and key to be generated  in all nodes in the cluster but with a different CA instead of it containting the same CA in all nodes. I am able to generate different PEM bundles for each node in the cluster which is fine because that is what we would want with the same CA signing different pem bundles for each node. 

**What you expected to happen**:
I expect the same root CA cert and key to be generated in each node ( the primary node and all secondary nodes). Then the pem files to be different in each node. 
Each node in the cluster will have its own signed PEM file with the CN corresponding to the hostname of that particular node. 
This script is being initiated upon container start time in the /docker-entrypoint-initdb.d directory. My goal was to get the script to produce the CA cert and key into the primary node upon creation and then populate the same CA cert in the secondary nodes when they start up. Meanwhile the remaining portion of the script is creating the signed server certs which will be generated as PEM bundles for all the nodes in the cluster. I am able to do this currently in which all the nodes in the cluster have a different PEM (mongodb.pem) corresponding to their different hostnames, which is fine, but I want the CA to be the same through out all the nodes so I can specify it in the
```
 --sslCAFile=/certificates/mongodb.pem
```
instead when I run the script it generates a different CA in the /certificates directory of each pod. 

**How to reproduce it** (as minimally and precisely as possible):
Run the script. Below is the script I have placed in the /files/docker-entrypoint-initdb.d directory:
```
#certsetup.sh
#creating the Root CA, ca.crt and ca.key


umask 007
my_hostname=$(hostname) && \
openssl req -newkey rsa:2048 -new -x509 -days 365 -nodes -out /opt/bitnami/mongodb/conf/ca.crt -keyout /opt/bitnami/mongodb/conf/ca.key -subj "/C=US/O=Testing/OU=IT/CN=ROOTCA"

my_hostname=$(hostname)
cat >/certificates/openssl.cnf <<EOL
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[v3_req]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment 
subjectAltName = @alt_names
[alt_names]
DNS.1 = $my_hostname
DNS.2 = $MONGODB_ADVERTISED_HOSTNAME
DNS.3 = localhost
DNS.4 = 127.0.0.1
EOL

my_hostname=$(hostname -f)
export RANDFILE=/certificates/.rnd && openssl genrsa -out /certificates/mongo.key 2048

#Create the client/server cert
openssl req -new -key /certificates/mongo.key -out /certificates/mongo.csr -subj "/C=US/O=Testing/OU=IT/CN=$my_hostname" -config /certificates/openssl.cnf

#Signing the server cert with the CA cert and key
openssl x509 -req -in /certificates/mongo.csr -CA /opt/bitnami/mongodb/conf/ca.crt -CAkey /opt/bitnami/mongodb/conf/ca.key -CAcreateserial -out /certificates/mongo.crt -days 3650 -extensions v3_req -extfile /certificates/openssl.cnf

rm /certificates/mongo.csr

#Concatenate to a pem file for use as the client/server PEM file which can be used for both member and client authentication. 

cat /certificates/mongo.crt /certificates/mongo.key > /certificates/mongodb.pem
rm /certificates/mongo.key /certificates/mongo.crt
```

**Anything else we need to know**:
In order to get the root CA cert and key to be generated, in not just the primary node, but in the secondary nodes as well, I had to add this volume mount to to statefulset-secondary-rs.yaml file also since it was already in the statefulset-primary-rs.yaml file:
```
            {{- if  or (.Files.Glob "files/docker-entrypoint-initdb.d/*[sh|js|json]") (.Values.initConfigMap) }}
            - name: custom-init-scripts
              mountPath: /docker-entrypoint-initdb.d
            {{- end }} 
 ```
So both the statefulset-primary-rs.yaml and statefulset-secondary-rs.yaml file looked as the following: 
```
volumeMounts:
            - name: datadir
              mountPath: {{ .Values.persistence.mountPath }}
              subPath: {{ .Values.persistence.subPath }}
            {{- if  or (.Files.Glob "files/docker-entrypoint-initdb.d/*[sh|js|json]") (.Values.initConfigMap) }}
            - name: custom-init-scripts
              mountPath: /docker-entrypoint-initdb.d
            {{- end }} 
            {{- if .Values.configmap }}
            - name: config
              mountPath: /opt/bitnami/mongodb/conf/mongodb.conf
              subPath: mongodb.conf
            {{- end }}
           - name: certificates
              mountPath: /certificates
```
This volume mount was already in the statefulset-primary-rs.yaml file, which enabled my certsetup.sh script to be generated in the primary node but not in the secondary nodes. As a result me adding that volume mount to the statefulset-secondary-rs.yaml file enabled the certsetup.sh script to execute into the secondary node 
I also added another volume mount named "certificates" in order to hold the certs the script would be generating.  
```
 - name: certificates
              mountPath: /certificates
```
This was placed under the **volumeMounts:** section as well as the **volumes:** section in both primary and secondary statefulset yaml files in order to create the empty directory to hold my certs as you can see below.
```
volumes:
        {{- if (.Files.Glob "files/docker-entrypoint-initdb.d/*[sh|js|json]") }}
        - name: custom-init-scripts
          configMap:
            name: {{ template "mongodb.fullname" . }}-init-scripts
        {{- end }}
        {{- if (.Values.initConfigMap) }}
        - name: custom-init-scripts
          configMap:
            name: {{ .Values.initConfigMap.name }}
        {{- end }}
        {{- if .Values.configmap }}
        - name: config
          configMap:
            name: {{ template "mongodb.fullname" . }}
        {{- end }}
        - name: certificates
          emptyDir: {}
```

Once I am successful with the single same CA Cert generated to all nodes and the correct PEM bundles in each node, I will then incorporate the MongoDB config env variables in the values.yaml file and in the statefulset yaml files. The values.yaml file will look like the following:

```
mongodbExtraFlags:
 - "--wiredTigerCacheSizeGB=2"
 - "--sslMode=requireSSL" 
 - "--sslPEMKeyFile=/certificates/mongodb.pem"
 - "--sslClusterFile=/certificates/mongodb.pem"
 - "--sslCAFile=/certficates/ca.crt" 
mongodbClientExtraFlags:
 - "--ssl" 
 - "--sslPEMKeyFile=/certificates/mongodb.pem"
 - "--sslCAFile=/certificates/ca.crt" 
```

**Comment by juan131** [comment]
Hi @kwill4026 

Thanks so much for opening this issue. Could you please format your post? It's really hard to me to follow it since the scripts you're sharing are not well formatted... 

Here you have a quick guide about messaging formatting in GitHub: https://help.github.com/en/articles/basic-writing-and-formatting-syntax

**Comment by kwill4026** [comment]
Hello @juan131 

Sorry its formated now

**Comment by juan131** [comment]
Hi @kwill4026 

Thanks for formatting your question. 

The chart folder `files/docker-entrypoint-initdb.d` is intended to place the scripts that are **meant to be run on the primary node of the cluster.** For instance, you can use this script to populate the database with your own data during the 1st boot of the primary node.

That's why I don't suggest you to use this folder to add scripts you want to be run on every node (primary and secondary ones).

I think the best approach is to adapt the Bitnami MongoDB docker image and this MongoDB chart so it accepts a set of parameters that allows to configure TLS encryption between MongoDB nodes. Sth similar has been recently suggested on the RabbitMQ chart (check this PR: https://github.com/helm/charts/pull/16213)

**Comment by kwill4026** [comment]
Hi @juan131,
Thanks for informing me of this as I was unware that the chart folder **files/docker-entrypoint-initdb.d** scripts were only meant to be ran on the primary node of the cluster only. I will take a look at the RabbitMQ CHART.
