### ISSUE TITLE
[stable/openvpn] dns settings are not propagated (?)

### ISSUE THREAD

**Issue by mhristof** [helm/charts#1632]
possibly a misconfiguration

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-30T09:51:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
https://github.com/kubernetes/charts/tree/master/stable/openvpn

**What happened**:
when starting a `stable/openvpn` container in my kubernetes cluster, i'd expect that when i connected to it via cmd line tool `openvpn` to have the hosts available and resolvable via the DNS.

From the openvpn container i can see that the dns setting is pushed
```
bash-4.3# grep DNS /etc/openvpn/openvpn.conf
push "dhcp-option DNS 100.64.0.10"
```

but when connect to the server (client reports back nothing unusual) i dont have the DNS available
So, if from my local pc i check the available dns servers (not sure if the one added by openvpn should appear here), i get

```
✗ networksetup -getdnsservers Wi-Fi
8.8.8.8
8.8.4.4
```

and the subsequent nslookup fails

```
✗ nslookup heapster.kube-system.svc.cluster.local
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find heapster.kube-system.svc.cluster.local: NXDOMAIN
```

If i add the dns myself in the list

```
✗ networksetup -getdnsservers Wi-Fi
100.64.0.10
8.8.8.8
8.8.4.4
```

then the nslookup is a success

```
✗ nslookup heapster.kube-system.svc.cluster.local
Server:		100.64.0.10
Address:	100.64.0.10#53

Name:	heapster.kube-system.svc.cluster.local
Address: 100.71.187.38
```

**What you expected to happen**:

I'd expect that i'd be able to do `nslookup heapster.kube-system.svc.cluster.local` from my local pc when im vpn connected.

**How to reproduce it** (as minimally and precisely as possible):
I run the default commands listed [here](https://github.com/kubernetes/charts/tree/master/stable/openvpn#usage).

**Anything else we need to know**:

**Comment by jfelten** [comment]
What openvpn client are you using? Tunnelblick? Are you running other vpn/networking software that changes dns settings?  How are you adding the name server?

I suspect something else may be overriding the /etc/resolv.conf.

Verified working for me:
helm version
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by glend** [comment]
Reopening this to clarify, I also cannot access via {svc-name}.{namespace} format, I have to pass full hostname xxx.xxx.svc.cluster.local, this works.

**Comment by kilianc** [comment]
@mhristof did solve this? I have the same problem with tunnelblick
