### ISSUE TITLE
[stable/prometheus-mongodb-exporter] default docker image doesn't have source code publicly

### ISSUE THREAD

**Issue by rafaeljesus** [helm/charts#16330]
Hi peeps,

I wanted to check how I would pass a list of connections string to the values file. The chart uses https://hub.docker.com/r/ssheehy/mongodb-exporter as default docker image, and it turned out I couldn't find its source code nowhere on the internet.

Am I right?

Thx

**Comment by rafaeljesus** [comment]
@steven-sheehy

**Comment by steven-sheehy** [comment]
@rafaeljesus I don't have a separate codebase or even a fork. It's just the code available at https://github.com/percona/mongodb_exporter that I built locally and pushed to Docker Hub since Percona doesn't have official images.

**Comment by rafaeljesus** [comment]
@steven-sheehy thanks for the quick response. It's just scary to not see the code base since someone can easily stream the data to a external server, makes sense my concern?

**Comment by antonu17** [comment]
> I built locally and pushed to Docker Hub 

But that's kind of wrong though. At least should have published Dockerfile or a link to the Dockerfile on the docker hub repo, to show how the image was built. Because the concern is reasonably valid.

**Comment by rafaeljesus** [comment]
I strongly agree with @antonu17 using this helm chart is a massive security risk.

Not even mentioning it doesn't work with TLS 
(https://github.com/helm/charts/tree/master/stable/prometheus-mongodb-exporter#limitations)

Why TLS it's not supported since the official percona does 🤔 https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/mongodb_exporter.go#L58

**Comment by steven-sheehy** [comment]
> But that's kind of wrong though. At least should have published Dockerfile or a link to the Dockerfile on the docker hub repo, to show how the image was built. Because the concern is reasonably valid.

Even if I link to the Dockerfile it may not be the Dockerfile or code that I actually used to build. So in the end it's still about trust. I am the owner of the chart and provide images for use with that chart. If you'd like to build your own from source, you're welcome to as the chart image is customizable. That said, I have added a short description to Docker Hub about the repository's provenance. 

> I strongly agree with @antonu17 using this helm chart is a massive security risk.

That's quite an exaggeration. You could say the same thing about using any docker image that you didn't create yourself.

> Why TLS it's not supported since the official percona does

It's all open source, so PRs welcome

**Comment by antonu17** [comment]
> I have added a short description to Docker Hub about the repository's provenance.

Thank you!

> Even if I link to the Dockerfile it may not be the Dockerfile or code that I actually used to build. So in the end it's still about trust.

That's true, however, docker hub has a concept of "automated" builds, which show up with the corresponding label in the `docker search <image>` output. Also, for automated builds, we can see Dockerfile ([an example](https://hub.docker.com/r/superpaintman/mongodb-exporter/dockerfile)). Which can inspire the others with a bit more trust in the community 🙂

**Comment by rafaeljesus** [comment]
@steven-sheehy thanks for the quick response!

> > I strongly agree with @antonu17 using this helm chart is a massive security risk.
> 
> That's quite an exaggeration. You could say the same thing about using any docker image that you didn't create yourself.

In this particular case is different I'd say, not every image out there has your DB credentials and connects to your DB.

> 
> > Why TLS it's not supported since the official percona does
> 
> It's all open source, so PRs welcome

Absolutely I was just wondering why 🙂

**Comment by steven-sheehy** [comment]
> That's true, however, docker hub has a concept of "automated" builds

I wasn't aware of these. I've switched the repo to use automated builds from my [fork](https://www.github.com/steven-sheehy/mongodb_exporter). You can't build it off someone else's repo, unfortunately. It should build docker tags latest and version tag for any new git tag. It also builds a master tag.
