### ISSUE TITLE
[stable/redis] allow templates in the user supplied conf

### ISSUE THREAD

**Issue by twk3** [helm/charts#16335]
**Describe the solution you'd like**

To be able to specify helm template strings in the user conf values. So have the configmap use the `tpl` function to render the conf settings that the users have passed in values.

**Additional context**

In the GitLab chart, we would like to set the values in our parent chart, to some sane defaults, but we would also like to be able to have users edit the `save` settings without overwriting our defaults. By rendering the settings using tpl, we can have our setting read in some additional user provided config.

**Comment by rafariossaa** [comment]
Hi @twk3,
   Could you provide some examples of the parameters you would like to set ?

**Comment by juan131** [comment]
I guess @twk3 refers to the paramaters `master.configmap` and `slave.configmap` that allows selecting what configuration to use both on Redis master and slave pods. Check:

https://github.com/helm/charts/blob/master/stable/redis/values.yaml#L354
https://github.com/helm/charts/blob/master/stable/redis/values.yaml#L207

Am I right?

**Comment by twk3** [comment]
Yep,  `.configmap` `master.configmap`, `slave.configmap`, and `sentinel.configmap`

I really only need `.configmap` at the moment but getting all of them at the same time makes sense

**Comment by twk3** [comment]
PR at https://github.com/helm/charts/pull/16363

**Comment by juan131** [comment]
Thanks for the PR! I just added a comment
