### ISSUE TITLE
[stable/redis] allow configurable secret password key

### ISSUE THREAD

**Issue by twk3** [helm/charts#16334]
Currently when providing an existing secret, the password must be provided in the `redis-password` key.

**Describe the solution you'd like**

I would like to propose the key expected default to 'redis-password' but be user-configurable in case user's existing secret has the password under a different key.

**Additional context**

We are looking to use this in the GitLab chart, were we want to upgrade the existing redis to this chart, but don't want existing users to need to change the already existing redis secret. https://gitlab.com/charts/gitlab/issues/1221#note_203777943

**Comment by juan131** [comment]
Hi @twk3 

I guess we could create some macro in the `_helpers.tpl` that generates the "key" to use in the secret to populate the **REDIS_PASSWORD** env. variable.

- `statafulset.yaml` manifest:

```diff
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "redis.secretName" . }}
-              key: redis-password
+              key: {{ template "redis.secretPasswordKey" . }}
        {{- end }}
```

- `values.yaml`:

```diff
  ## Use existing secret (ignores previous password)
  ##
  # existingSecret:
+ ## Password key to be retrieved from Redis secret
+ ##
+ # existingSecretPasswordKey:
```

- `_helpers.tpl`:

```diff
+ {{/*
+ Get the password key to be retrieved from Redis secret.
+ */}}
+ {{- define "redis.secretPasswordKey" -}}
+ {{- if and .Values.existingSecret .Values.existingSecretPasswordKey -}}
+ {{- printf "%s" .Values.existingSecretPasswordKey -}}
+ {{- else -}}
+ {{- printf "redis-password" -}}
+ {{- end -}}
+ {{- end -}}
```

What do you think?

**Comment by twk3** [comment]
@juan131 yep, that would work fine. I've gone ahead and thrown up a MR with takes that, and also applies it to the password file volume as well.

https://github.com/helm/charts/pull/16360

**Comment by juan131** [comment]
Great @twk3 !! Taking a look!
