### ISSUE TITLE
[stable/concourse] bump postgres subchart

### ISSUE THREAD

**Issue by aegershman** [helm/charts#16340]
In order to consume the latest version of the postgres chart, the [`requirements.yml`](https://github.com/helm/charts/blob/master/stable/concourse/requirements.yaml) should be bumped to the [latest version of the chart](https://github.com/helm/charts/blob/master/stable/postgresql/Chart.yaml)

NOTE: I haven't tested doing this in our environments, and there's no obvious reason why it *has* to happen, just putting this issue here as a placeholder

**Comment by YoussB** [comment]
nice catch, Thanks @aegershman. I will add this to our backlog.
Might take some time to get to it, as we are currently working on a bunch of stuff.

Would love to see a PR from you, if this is urgent :)
