### ISSUE TITLE
[stable/concourse] NOTES.txt check if workers.enabled

### ISSUE THREAD

**Issue by aegershman** [helm/charts#16341]
Currently we're separating the `web` and `worker`s into separate helm deployments; the `web` has `workers.enabled=false`, but still shows the message about the baggage claim driver even though it's not applicable at all (since workers are turned off entirely in the `web` deployment).

I believe `NOTES.txt` should just check whether `{{- if .Values.worker.enabled }}`
https://github.com/helm/charts/blob/master/stable/concourse/templates/NOTES.txt#L39

Can submit a PR for this, but first wanted to put it into backlog

Thanks for consideration!

**Comment by YoussB** [comment]
Thx @aegershman
