### ISSUE TITLE
[stable/dex] Support complete user-provided config rather than exposing subset of options

### ISSUE THREAD

**Issue by cjheppell** [helm/charts#16351]
**Is your feature request related to a problem? Please describe.**

The introduction of the Dex Chart 2.0.0 (specifically [this PR](https://github.com/helm/charts/pull/15558)) restricted the ability to change the configuration of Dex. Instead of taking a full `config.yaml` configuration as it used to pre V2, it now only exposes a subset of the available configuration options within Dex via `values.yaml`.

This makes it impossible to provide additional Dex configuration such as [`.config.web.allowedOrigins`](https://github.com/dexidp/dex/blob/ab08d7b3a47716122f60522a7a34b20f217414f8/cmd/dex/serve.go#L204), where before this was possible.

**Describe the solution you'd like**

_Accept a full config file as an override_

Create an additional `values.yaml` configuration value for providing a full Dex `config.yaml`.

For example: `.config.file` which, if present, takes precedence over any of the other individual configuration values.

[This is how the chart used to function](https://github.com/helm/charts/pull/15558/files#diff-0e17c94f7b2e909b44a1702797fe8bbcL11), and will minimise overhead when migrating to the V2 chart.

**Describe alternatives you've considered**

_Use `extraVolumeMount` to override the default config_

I guess you can work around this by using an `extraVolumeMount` on the same location the current config gets mounted to. Though that feels a bit nasty, and `extraVolumeMount`'s are not documented on the readme, [even though they're supported](https://github.com/helm/charts/blob/d114d64e3170d9bdc3843747ea96b4d843f2e901/stable/dex/templates/deployment.yaml#L83-L84).

_Add extra `values.yaml` configuration support for all available Dex config options_

We could also add support for every possible configuration option within Dex, but that seems quite impractical.

**Comment by jgielstra** [comment]
Perhaps just support an alternative secret `.Values.configSecret`, that both replaces and suppresses the generation the helm's secret.yaml

**Comment by desaintmartin** [comment]
Hello,
If it worked before, this is a regression. Could you do a PR?

**Comment by cjheppell** [comment]
@desaintmartin 

Yes, I can put a PR together. I'll try and get one submitted soon.

**Comment by cjheppell** [comment]
I've recently been on vacation and haven't had the time to do this yet. Hopefully I'll get the chance soon. Sorry for the delay.
