### ISSUE TITLE
[stable/sonarqube] Elasticsearch not starting - vm.max_map_count is too low

### ISSUE THREAD

**Issue by freddypaxton** [helm/charts#16371]
**Describe the bug**
The default value for vm.max_map_count is 65530, Elasticsearch needs 262144 to start.

**Version of Helm and Kubernetes**:
Helm v2.14.1
Kubectl v1.13.6-gke.13

**Which chart**:
Sonarqube

**What happened**:
`ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
2019.08.16 10:33:47 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 78
2019.08.16 10:33:47 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2019.08.16 10:33:47 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped`

**What you expected to happen**:
I expect the vm.max_map_count to default to 262144 (this seems to be the case in the Elasticsearch chart)

**How to reproduce it** (as minimally and precisely as possible):
Installing the Sonarqube chart

**Anything else we need to know**:
I've also been having issues with Elasticsearch stopping with exit value 1, which seemed to be fixed by adding: `securityContext:
  fsGroup: 999
  runAsUser: 999` to my values file.

**Comment by freddypaxton** [comment]
I've noticed this in my deployment yaml...
```
initContainers:
- command:
  - sysctl
  - -w
  - vm.max_map_count=262144
```

Still getting the error

**Comment by mvz27** [comment]
Same issue here.
Cannot go higher than version 7.7 due to this issue ;-(

**Comment by mvz27** [comment]
This seems to solve the issue:
      initContainers:
        - name: "sysctl"
          image: "busybox"
          imagePullPolicy: "IfNotPresent"
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true

**Comment by freddypaxton** [comment]
So, 7.7-community works fine. 7.8 and 7.9 both give me elasticsearch errors on the sonarqube container, despite the initContainer completing successfully.

**Comment by csharma333** [comment]
> This seems to solve the issue:
> initContainers:
> - name: "sysctl"
> image: "busybox"
> imagePullPolicy: "IfNotPresent"
> command: ["sysctl", "-w", "vm.max_map_count=262144"]
> securityContext:
> privileged: true

This solution is perfect. :)
Thanks.
