### ISSUE TITLE
[incubator/solr] Enabling Authorization in Solr causes Readiness Probe error

### ISSUE THREAD

**Issue by hokm** [helm/charts#16373]
**Describe the bug**
Enabling Authentication & Authorization using Solr security plugins causes Back-off restarting failed container due to:

> Readiness probe failed: HTTP probe failed with statuscode: 401

**Version of Helm and Kubernetes**:
```
λ helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
λ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
incubator/solr

**What happened**:
I edited \security.json file using zkCli Tool. I enabled there Authentication and Authorization plugins and defined some simple rules. Authorization was sucessfully enabled but after a few seconds Kubernetes restarted container due to Readiness probe failed: HTTP probe failed with statuscode: 401.

The problem is, health check endpoint defined in Readiness Probe is affected by Authorization and current version of chart does not allow to define any Authorization headers to Readiness Probe checks. 

```
readinessProbe:
  initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
  periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
  httpGet:
    scheme: "{{ .Values.tls.enabled | ternary "HTTPS" "HTTP" }}"
    path: /solr/admin/info/system
    port: {{ .Values.port }}
```

**What you expected to happen**:
I expect to have running secured Solr which requires Authentication on every endpoint.

**How to reproduce it** (as minimally and precisely as possible):
Use Zookeeper tool zkCli to [Enable Authentication & Authorization plugins](https://lucene.apache.org/solr/guide/6_6/authentication-and-authorization-plugins.html#AuthenticationandAuthorizationPlugins-EnablePluginswithsecurity.json) and define simple rules in /security.json: 
```
{
"authentication":{
   "class":"solr.BasicAuthPlugin",
   "credentials":{"solr":"IV0EHq1OnNrj6gvRCwvFwTrZ1+z1oBbnQdiVC3otuq0= Ndd7LKvVBAaZIF0QAVi1ekCfAJXr1GGfLtRUXhgrF8c="}
},
"authorization":{
   "class":"solr.RuleBasedAuthorizationPlugin",
   "permissions":[{"name":"security-edit",
      "role":"admin"}],
   "user-role":{"solr":"admin"}
}}
```

Wait a few seconds and container will fall into restarting loop.

**Anything else we need to know**:
I am new to Solr and Zookeeper, maybe I am doing something terribly wrong :)

**Comment by JasonHao123** [comment]
I met this issue also, and if you want to upload configset, seems enable authentication is mandatory. anybody will fix it?
