### ISSUE TITLE
[incubator/rundeck] Environmental variables for Deployment not taken from values.yaml  

### ISSUE THREAD

**Issue by mmeer1293** [helm/charts#16385]
**Describe the bug**
The environment variable RUNDECK_GRAILS_URL created in deployment.yaml is not taken from the value listed in values.yaml.
**Version of Helm and Kubernetes**:

**Which chart**:
incubator/rundeck

**What happened**:

**What you expected to happen**:
Deployment.yaml RUNDECK_GRAILS_URL inherited from values.yaml

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by svparijs** [comment]
I have a similar issue with DB connection variables. The chart is not really solid, I might gave a go at it soonish...

**Comment by Smuggla** [comment]
I believe this PR would address the issue you identified.
https://github.com/helm/charts/pull/16007

Thanks!
