### ISSUE TITLE
[stable/prometheus-operator] Custom Grafana dashboard configmaps deployed to many namespaces causes premature delete

### ISSUE THREAD

**Issue by GregHamilton007** [helm/charts#16380]
**Describe the bug**
We are installing chartA (with a configmap containing a label that the grafana dashboard scraper picks up) to 2 different namespaces (namespaceA and namespaceB).  ChartA is installed to namespaceA and the dashboard is picked up correctly by the Grafana Dashboard scraper. When chartA is installed to namespaceB, the scraper detects that the dashboard contained in the configmap is already discovered by Grafana and is not added a second time... **ALL is good until this point**. When namespaceB is wiped of all of its resources the scraper detects that the configmap is deleted, and deletes the Grafana Dashboard contained in chartA deployed to both namespaceA and namespaceB. 

The Scraper doesn't keep track that multiple deployments of chartA are using that custom dashboard. Hence when we go to look for the dashboard containing metrics about chartA, the dashboard is missing despite being contained in a configmap in namespaceA.

This issue has been discovered since we are installing chartA to a namespace that persists and another namespace that is just present while tests are being run against it.

**Version of Helm and Kubernetes**:

Helm:
   Client: v2.12.2
   Server: v2.14.1
Kubernetes:
   Client: v1.13.0
   Server: v1.13.5

**Which chart**:

stable/prometheus-operator

**What happened**:

Custom Grafana dashboard contained in configmap is missing, despite being installed to namespace

**What you expected to happen**:

The Grafana dashboard scraper sidecar would detect and keep track of which releases use the custom dashboard, and only remove the dashboard when all releases using that dashboard are deleted

**How to reproduce it** (as minimally and precisely as possible):

1. Install chart containing configmap describing custom Grafana dashboard, with label detectable by Grafana Dashboard sidecar twice (two seperate releases)

2. Delete one of the releases

**Comment by vsliouniaev** [comment]
Files are created using the name of the file in the configmap.
```
data:
  my Dashboard.json: {}
```
https://github.com/kiwigrid/k8s-sidecar/blob/master/sidecar/resources.py#L100-L106

You can template your filenames to include the namespace, which should help address your issue. I'm not certain of the complete implications of this, since the prometheus-operator chart is just leveraging grafana and I don't maintain that chart

**Comment by GregHamilton007** [comment]
Thanks for your response @vsliouniaev. I have some concerns with that approach. In some cases (such as when you include a legend format such as: "legendFormat": {{pod}} ) the dashboard.json and configmap must be separate files (if in a single file when kubernetes parses the configmap it interprets "{{ }}" as a function and throws an error), and the filename of the dashboard.json is static. Also its not ideal to have replicas of a dashboard, when used in multiple namespaces.

**Comment by vsliouniaev** [comment]
I think your issue is fundamental to how the reloader sidecar behaves. I suggest you raise this issue with the maintainers there to see if they would be open to the enhancement you are looking for.
