### ISSUE TITLE
[stable/jenkins] RBAC deployment with Kubernetes plugin does not use the created service account

### ISSUE THREAD

**Issue by ReSearchITEng** [helm/charts#1643]
**Is this a BUG REPORT

**Version of Helm and Kubernetes**:
helm 2.5.0;  k8s: 1.7

**Which chart**:
[stable/jenkins]

**What happened**:
RBAC deployment with Kubernetes plugin does not use the helm chart created service account (SA).

**What you expected to happen**:
be able to use the service account the helm chart created. 

I did not find the way to specify to  Kubernetes plugin which SA to use. Apparently by default it uses the "default" SA in the specific namespace.
While this helm chart creates and gives perms to a different SA

More than this, I could not find a way to point the kubernetes-plugin to a specific k8s service-account.
It seems that it's always looking to the default service account for that namespace:
```
Error connecting to [edited]: Failure executing: GET at: [edited]/api/v1/namespaces/jenkins/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User "system:serviceaccount:jenkins:default" cannot list pods in the namespace "jenkins".. 
```
while the helm chart creates a service account like: jenkins-jenkins

@carlosedp @lachie83 I see you checked #1092 maybe you can suggest any hints?

**Comment by victortrac** [comment]
@ReSearchITEng You can configure which service account the workers use by going go to "Manage Jenkings" -> "Configure System" -> "Cloud" -> "Images" -> "Advanced" -> "Service Account".

**Comment by ReSearchITEng** [comment]
As the service-account is created during helm install, it was expected that it will also configure the installation to use it. Maybe in future versions.

**Comment by daveamit** [comment]
Created and set Jenkins creds of type kubernetes Service Account
![](https://i.imgur.com/TSjHmz1.png)

I tried setting `Service Account` from pod template,
![](https://i.imgur.com/EOYvvwT.png)

But unfortunately it did not work, I still go same error. As you can see, its was not using "ci-jenkins" sa account, it was still using "default"
![](https://i.imgur.com/KcRWSYm.png)

Then I specified service account in pod definition 
![](https://i.imgur.com/qWdfAXb.png)

After the change, It picked up proper service account (ci-jenkins), and helm was able to access required cluster resources.

![](https://i.imgur.com/2EFt0Qj.png)

I'm not sure why this happened.

Any advice ? I don't want to specify service account in pipeline definition.

**Comment by ReSearchITEng** [comment]
There was such issue with an older version of k8s plugin. I am not aware of
this in the last period.
Alternatively, you create a namespace for jenkins (if you don't do it
already),  you can give the required perms to the default service account.
This works and there is no need to specify it anywhere.
