### ISSUE TITLE
[stable/keycloak] Extend README with an example for custom admin console port

### ISSUE THREAD

**Issue by huschi** [helm/charts#16463]
It would be great to extend the README with an example of how to set a custom admin console port. As I understood it should be possible with the property keycloak.extraPorts but I didn't find a hint in the docs how the settings should look like.

https://github.com/keycloak/keycloak-documentation/blob/master/server_admin/topics/threat/admin.adoc

**Comment by briantopping** [comment]
I ran into this as well. It seems like a good idea to document.
