### ISSUE TITLE
[stable/postgresql] template: postgresql/templates/_helpers.tpl unexpected "=" in operand

### ISSUE THREAD

**Issue by NishikaDeSilva** [helm/charts#16475]
**Describe the bug**
I tried installing stable/postgresql using following command. 

``` helm install --name rdbms-service stable/postgresql ```

However, this generates the following error.

```Error: parse error in "postgresql/templates/_helpers.tpl": template: postgresql/templates/_helpers.tpl:323: unexpected "=" in operand```

I tried this using chart version 6.2.1 and this works fine. 

**Version of Helm and Kubernetes**:
kubernetes: 1.10
Helm: 2.10

**Which chart**:
stable/postgresql

**Comment by melissaettinger** [comment]
**Bug**
Same issue is occurring for me with stable/redis

`helm upgrade --install <mypackage> stable/redis`

Generates the error: 
`Error: parse error in "redis/templates/_helpers.tpl": template: redis/templates/_helpers.tpl:247: unexpected "=" in operand`

**Version of Helm and Kubernetes:**
kubernetes: 1.10.11
helm: 2.9.1

**Chart:**
stable/redis

**Note**
The issue does not occur if I run helm upgrade --install <mypackage> stable/redis --version 7.0.0

**Comment by miguelaeh** [comment]
Hi @NishikaDeSilva @melissaettinger ,

We're unable to reproduce the issue locally.

Could you share with us the version of helm client and tiller you're using? Just provide the output of the command below:

```console
$ helm version
```

Are you using a different **values.yaml** or did you overwrite the `master.persistence` parameter?

**Comment by NishikaDeSilva** [comment]
@miguelaeh I haven't done any changes to the chart.

helm version details:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

```
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

**Comment by miguelaeh** [comment]
Hi,
I created a PR changing the template to not use assignation of variables in different context that is not supported in old helm versions.
