### ISSUE TITLE
Create chart for Apache OpenWhisk

### ISSUE THREAD

**Issue by xingzhou** [helm/charts#1648]
OpenWhisk is an open source Serverless platform under Apache Foundation which is a container-native platform. Deploy OpenWhisk on Kubernetes provides the convenience for the developers to program and run applications based on FaaS scenario, e.g. IoT. 

Here is the official website of OpenWhisk project: http://openwhisk.incubator.apache.org

I'm planning to write a chart for deploying Apache OpenWhisk on K8s. Let me know if you have any comments, thanks

**Comment by viglesiasce** [comment]
Looking forward to it!!!

**Comment by xingzhou** [comment]
Had a WIP prototype here: https://github.com/xingzhou/Deploy_OpenWhisk_with_Helm, now testing it, will submit PR then.
