### ISSUE TITLE
[stable/stolon] Fails to initialize

### ISSUE THREAD

**Issue by ConnorBarnhill** [helm/charts#16516]
**Describe the bug**
Postgres cluster fails to initialize

**Version of Helm and Kubernetes**:
Helm:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

K8s:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
Stolon

**What happened**:
Keepers, proxies, and sentinals all start running but print these logs:
cmd/keeper.go:950	no cluster data available, waiting for it to appear
cmd/proxy.go:193	no clusterdata available, closing connections to master
cmd/sentinel.go:1839	no cluster data available, waiting for it to appear

Looking at the pg-stolon-create-cluster job I see this message:
WARNING: The databases managed by the keepers will be overwritten depending on the provided cluster spec.
failed to unmarshal cluster spec: json: cannot unmarshal number into Go value of type string

This occurs using the default clusterSpec in the values: clusterSpec: {}
Also occurs setting values as : 
clusterSpec:
  synchronousReplication: true
  minSynchronousStandbys: 1
  maxSynchronousStandbys: 1
  initMode: new

**What you expected to happen**:
Startup as expected

**How to reproduce it** (as minimally and precisely as possible):
Follow https://disaev.me/p/how-i-have-set-up-ha-postgresql-on-kubernetes/

**Anything else we need to know**:

**Comment by aianus** [comment]
@ConnorBarnhill you need to pass pgParameters: maxConnections: as a string

```
  pgParameters:
    maxConnections: "200"
```

instead of

```
  pgParameters:
    maxConnections: 200
```

**Comment by aianus** [comment]
Actually, it's "max_connections" not "maxConnections" as noted in #16980 

I was able to initialize the cluster by making these changes

**Comment by the-redback** [comment]
I can verify, the problem gets solved following @aianus's procedure. :+1:
