### ISSUE TITLE
[stable/mongodb] Port configuration option appears to have no effect

### ISSUE THREAD

**Issue by jadesrochers** [helm/charts#16578]
**Describe the bug**
Using the port configuration option did not change the service port, which appears to be what it should do.
#### I condensed it down to this:
helm install -n testdb --set port=38900 stable/mongodb
#### Which results in a service with port 27017:
testdb-mongodb   ClusterIP   10.105.59.139   <none>        27017/TCP   5s

#### Using a config file had the same result
A testconfig.yaml with this content:
```
service:
  annotations: {}
  type: ClusterIP
  # clusterIP: None
  port: 38900
```
#### Tried a variation on the variable name but also same result
helm install -n testdb --set service.port=38900 stable/mongodb

**Version of Helm and Kubernetes**:
Helm: 2.14.3
Kubernetes: 1.14.6

**Which chart**:
stable/mongodb

**What happened**:
The service created for the mongodb pod always uses port 27017, even when a different port is set for this option.

**What you expected to happen**:
If the port option is set the alternate value should be used.

**How to reproduce it** (as minimally and precisely as possible):
helm install -n testdb --set port=38900 stable/mongodb
kubectl get service testdb-mongodb

As ever it could be my mistake, but the other options I was using when I ran into this seemed to work fine.

**Comment by carrodher** [comment]
Thanks for reporting it, I just sent a PR that should fix the issue. Once merged, can you try using this new version?

**Comment by carrodher** [comment]
Happy to help, thanks for reporting this kind of issues
