### ISSUE TITLE
[stable/jenkins] Jenkins jobs specified in master.jobs are not created

### ISSUE THREAD

**Issue by josiahp** [helm/charts#16584]
**Describe the bug**
Starting with chart version 1.5.4, Jenkins jobs as specified in master.jobs are not being created.

**Version of Helm and Kubernetes**:
Helm: 2.14.1
Kubernetes: v1.12.8-gke.10

**Which chart**:
stable/jenkins

**What happened**:
Prior versions of this chart allowed job XML to be specified as master.jobs in values.yaml, but starting with version 1.5.4 jobs are no longer being created.

master.enableXmlConfig was added as configuration value, but even when set to true jobs are not being created.

**What you expected to happen**:
I expected jobs to be created.

**How to reproduce it** (as minimally and precisely as possible):
Install chart version 1.5.4 (or higher?) with master.jobs specified in values.yaml

**Comment by torstenwalter** [comment]
>   # By default, the Jobs Map is only used to set the initial jobs the first time
>   # that the chart is installed.  Setting `overwriteJobs` to `true` will overwrite
>   # the jenkins jobs configuration with the contents of Jobs every time the pod starts.
>   overwriteJobs: false

Have you tried setting `master.overwriteJobs` to `true`? Just pay attention that this is what you want as it overwrites Jenkins job configurations.

**Comment by josiahp** [comment]
Thanks for your reply. The behavior on chart version 1.5.3 is that jobs are created regardless of whether overwriteJobs is set to true or not. Even if overwriteJobs is required from 1.5.4 and onward, it seems like a defect to change default behavior without mentioning it in the documentation.

I just confirmed that jobs are not being created on 1.5.4 even when overwriteJobs is set to true.

**Comment by josiahp** [comment]
However, I've deployed 1.7.2 and confirmed that jobs are being created properly, so I assume the defect was resolved at some point between 1.5.4 and 1.7.2. Since it has been fixed in the latest release, it's probably not worth figuring out why it broke in the first place.

Thanks.
