### ISSUE TITLE
stable/fluentd - Detected ES 7.x or above: `_doc`...

### ISSUE THREAD

**Issue by acarsercan** [helm/charts#16588]
Hi,

Docker image made use by the helm chart is using a plugin which is too old:

```
2019-08-23 07:48:17 +0000 [info]: starting fluentd-1.3.3 pid=1 ruby="2.3.3"
2019-08-23 07:48:17 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby2.3", "-Eascii-8bit:ascii-8bit", "/usr/local/bin/fluentd", "--under-supervisor"]

**2019-08-23 07:48:17 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.0.2'**
```

Latest elasticsearch plugin is 3.5.X

Docker image used by the helm chart hasn't being updated since Jan 2019

Regards

**Comment by DandyDeveloper** [comment]
@acarsercan Shouldn't your template or the default logstash templating solve this problem? 

This should just be a warning at the most and have no direct impact, unless your templates are defined incorrectly in ES/Fluentd configuration.

However, I am in support of upgrading the image version if there is a newer version available.

**Comment by gdoctor** [comment]
I'd recommend reopening this. It looks like all the fluentd components (fluentd + plugins) are all very outdated.

**Comment by DandyDeveloper** [comment]
@gdoctor I agree. Although it's not pressing, it needs doing.

**Comment by pshanoop** [comment]
How those images are created ` gcr.io/google-containers/fluentd-elasticsearch` ?
I was thinking of updating my self to see if it's easy fix or not.

**Comment by davidkarlsen** [comment]
I found this chart a bit outdated and the configuration not so flexible - a good alternative is https://github.com/bitnami/charts/tree/master/bitnami/fluentd
