### ISSUE TITLE
[stable/prometheus-operator] CoreDNSDown alert needs kubeDns to be enabled.

### ISSUE THREAD

**Issue by machine424** [helm/charts#16592]
**Describe the bug**
- A cluster with Coredns pods having the label: `k8s-app: coredns`, after deploying `prometheus-operator`, the rule `CoreDNSDown` (and maybe other things) doesn't get created because it needs `kubeDns` to be enabled in `values.yaml` file. See: https://github.com/helm/charts/blob/f815a594fa5daf91d99fc60937c22b290ad67632/stable/prometheus-operator/templates/prometheus/rules/kubernetes-absent.yaml#L37 and https://github.com/helm/charts/blob/02f24b0e556af7bcd724b3b2811e6fdeacc8b83a/stable/prometheus-operator/hack/sync_prometheus_rules.py#L83

The alert template is generated from here : 
https://github.com/coreos/kube-prometheus/blob/da959c643657c7d2aac6f5ddd68582a949283c49/jsonnet/kube-prometheus/kube-prometheus.libsonnet#L88

- If we enable `kubeDns` (even if kubedns isn't deployed on the cluster), the alert will always fire because there are no pods with the label `k8s-app: kube-dns` in the cluster ( we don't want to alter coredns pods' labels)

**Version of Helm and Kubernetes**:
Kubernetes: v1.13.5
Helm: v2.14.2

**Which chart**:
[stable/prometheus-operator]

**What happened**:
The alert CoreDNSDown isn't added.

**What you expected to happen**:
the alert `CoreDNSDown` in kubernetes-absent.yaml should be added only when we enable coreDns

**How to reproduce it** (as minimally and precisely as possible):
See **Describe the bug**

**Anything else we need to know**:
- We can enable `kubeDns` with `k8s-app: coredns` for the selector but even if that solves the pb, I think it isn't coherent.

**Comment by milesarmstrong** [comment]
We've encountered this issue too, re-linking the relevant lines:

https://github.com/helm/charts/blob/22b6484babdfffa2f34f6ec1ca2ff87c905aa9d4/stable/prometheus-operator/templates/prometheus/rules/kubernetes-absent.yaml#L41-L50
