### ISSUE TITLE
[stable/nginx-ingress] Deploy both deployment and daemonset together

### ISSUE THREAD

**Issue by alantang888** [helm/charts#16604]
**Describe the solution you'd like**
I think should have an option to deploy both deployment and daemonset together.

If we want to get request's real IP address. We need to set `controller.service.externalTrafficPolicy` to `Local`. That will make k8s won't forward traffic to other nodes if the node don't have any nginx-ingress. It only can rely on LB's healthcheck. And LB's healthcheck take time to declare node is unhealth. Which will make request timeout.

So I suggest add an option to deploy both deployment and daemonset together. Then all nodes match node-selector and tolerations will have at least one nginx-ingress running (Sure this will need to control which instance group can run nginx-ingress). And HPA can continue control number of pod for deployment.

**Comment by taharah** [comment]
The proper way to get the request's real IP address would be to use the `X-Forwarded-For` headers or PROXY protocol depending on if you are at L7 or L4 respectively (as well as what any load balancer sitting in front of nginx is capable of supporting). You can enable either option in the [ConfigMap](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/) for nginx. `use-forwarded-headers` or `use-proxy-protocol` are the options you are probably looking for. Let me know if this helps or if you can provide any additional context.

**Comment by alantang888** [comment]
We using L4 GCP loadbalancer. And terminate TLS on nginx-ingress. If do not set `controller.service.externalTrafficPolicy` to `Local`. The source IP address will be the kube-proxy IP address. And L4 GCP loadbalancer can't inject `X-Forwarded-For` header.
And I can't found we can enable PROXY protocol for GCP loadbalancer on K8S service. So `use-proxy-protocol` can't help...

**Comment by taharah** [comment]
Based on the additional context you provided, have you tried setting the value of `healthCheckNodePort` ([stable/nginx-ingress/values.yaml#L246](https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L246))? That seems to provide the functionality you're looking for, i.e., not sending traffic to nodes that do not have any Pods deployed ([https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip)).

**Comment by alantang888** [comment]
When set `controller.service.externalTrafficPolicy` to `Local`. It already auto assign a random port for `healthCheckNodePort` let GCP LB perform health check. As I mention on first message. health check to detect a node don't have nginx-ingress pods take time to declare node is un-health. 

GCP LB default checking interval is 8 secs and declare node un-health on 3 consecutive failures. So best case is 17 secs (1 sec timeout). Worst case is 25 secs. 

If set those value to a lower number (didn't test will k8s override it). When high traffic still can have many request go to a node don't have nginx-ingress. It can cause connection time out. 

That's why I suggest can deploy nginx-ingress on both daemonset and deployment. Daemonset can make sure node at least have 1 nginx-ingress running. And deployment can work with HPA (There still have chance make traffic in-balance. But better than time out).

Please see PR #16624
