### ISSUE TITLE
[stable/redis] Master-Slave with Sentinel deployment issue

### ISSUE THREAD

**Issue by ljohnston** [helm/charts#16638]
**Describe the bug**
A new install of the stable/redis chart, configured for master/slave with sentinel fails with the following log from the master pod's sentinel container:
```
$ kubectl logs dev-tmp-redis-master-0 -c sentinel
Getting information about current running sentinels
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Could not connect to Redis at dev-tmp-redis:26379: Connection refused

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 4
>>> 'sentinel monitor master dev-tmp-redis-master-0.dev-tmp-redis-headless.infraplat-dev.svc.cluster.local 6379 2'
Can't resolve master instance hostname.
```
**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/redis version 9.1.0

**What happened**:
Deployment never completed. The master pod remains in a CrashLoopBackOff state.

**What you expected to happen**:
Deployment to complete successfully.

**How to reproduce it** (as minimally and precisely as possible):
Simply do a new helm install configured for master-slave with sentinel as described here:  https://github.com/helm/charts/tree/master/stable/redis#master-slave-with-sentinel

**Anything else we need to know**:
I was able to get the deployment to work with the following changes to the chart:
```
$ diff ../helm-fetch/redis-9.1.0/templates/headless-svc.yaml redis/templates/headless-svc.yaml
9a10,11
>   annotations:
>     service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
12a15
>   publishNotReadyAddresses: true
```

**Comment by miguelaeh** [comment]
Hi @ljohnston ,
I cannot reproduce that with:
```
$  helm install stable/redis --set sentinel.enabled=true
```
Have in mind the cluster mode is enabled by default. Could you provide the exact way you deployed it please, we would like to reproduce it?
Anyway, It seems by any reason your sentinel container is ready before than the master, so I guess that is why it works with the annotation, because the annotation allows to publish the addresses of not ready containers.

**Comment by muffinrecon** [comment]
@ljohnston @miguelaeh 

This seems to be a NetworkPolicy issue. After I disabled it, everything started working fine.
