### ISSUE TITLE
[stable/sonatype-nexus] Decouple the sonatype-nexus chart from the proxy and backup service

### ISSUE THREAD

**Issue by stevehipwell** [helm/charts#16647]
**Is your feature request related to a problem? Please describe.**
The current _sonatype-nexus_ chart is tightly coupled with a custom proxy and backup agent. The proxy is limiting in the way it is exposed through the values and makes it impossible to set up _Nexus_ with multiple docker registries (as is standard practice when both hosting and proxying) with proxied ports.

**Describe the solution you'd like**
Either rename the existing chart to add the correct context (e.g. _travelaudience-nexus_) or add a new chart (e.g. _nexus_ or _nexus3_).

**Describe alternatives you've considered**
I'm currently running my own *nexus3* chart from a git repository which supports any number of docker hosts being configured with proxied ports.

**Additional context**
I can provide the replacement chart which I've been using, it is based on the current _sonatype-nexus_ chart but uses values to expand the potential service ports. I'm also interested in bootstrapping _Nexus_ with _Groovy_ scripts via a config map (e.g. LDAP config).

**Comment by diasjorge** [comment]
I'd be interested in this chart, could you point somewhere to it?

**Comment by stevehipwell** [comment]
@diasjorge - It's currently on a private repo but I'll try and make it public later today or tomorrow.

**Comment by stevehipwell** [comment]
I'm looking at creating a pull request for this next week.

**Comment by denis111** [comment]
I agree.
First, I find that proxy useless because it only consumes lots of resources, it could be made with something more lightweight or just use ingress rules if you don't need that IAM things.
Second, that travelaudience docker image is not actively mantained and seems abandoned, the latest nexus 3 version is 3.19.1 and we are still on 3.17, I'd prefer official sonatype image then.

**Comment by stevehipwell** [comment]
@denis111 I have a replacement chart but I've been put off getting it onto GitHub due to a lack of interest. If you're interested I'll see if I can get it up?

**Comment by denis111** [comment]
@stevehipwell well, thanks but it would be nice to convince this chart mantainers to make this change or make proxy optional with an "if".

**Comment by Place1** [comment]
i'd be interested in a better chart. improving the configuration would be nice i.e. setting the admin password, provisioning repositories automatically etc.
