### ISSUE TITLE
[stable/redis] Add loadBalancerSourceRanges to master

### ISSUE THREAD

**Issue by pradithya** [helm/charts#16644]
Add `master.service.loadBalancerSourceRanges` option

**Additional context**
When `master.service.type` is set to `LoadBalancer` it will be accessible from all ip ranges 0.0.0.0/0, for security reason we should let user to specify loadBalancerSourceRanges.

**Comment by andresbono** [comment]
Hi @pradithya, sounds like an interesting parameter to implement. Thanks for the suggestion. We will evaluate and open a PR shortly.
