### ISSUE TITLE
[stable/nginx-ingress] UPGRADE FAILED: render error in "nginx-ingress/templates/controller-prometheusrules.yaml"

### ISSUE THREAD

**Issue by lephleg** [helm/charts#16641]
**Describe the bug**
I cannot upgrade an installed release like I used to, about 2 weeks ago (~ August 15th, 2019).

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.25", GitCommit:"d4c79083ab6dea5d26ef4ed8d50b145268349bc3", GitTreeState:"clean", BuildDate:"2019-06-22T16:10:31Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
[stable/nginx-ingress]

**What happened**:
I use the following helm upgrade command to upgrade an already installed release of the chart:
```
bash-4.4# helm upgrade <release-name> stable/nginx-ingress --reuse-values --set controller.config.block-referers=~*click2spam.net
```
The upgrade command fails with the following error:
```
Error: UPGRADE FAILED: render error in "nginx-ingress/templates/controller-prometheusrules.yaml": template: nginx-ingress/templates/controller-prometheusrules.yaml:1:53: executing "nginx-ingress/templates/controller-prometheusrules.yaml" at <.Values.controller.m...>: can't evaluate field enabled in type interface {}
```

I haven't changed anything on my configuration. The initial `values.yml` template I've been using is the following:

```
controller:
  kind: Deployment
  replicaCount: 1
  service:
    enableHttp: true
    externalTrafficPolicy: Local
    loadBalancerIP: XX.XX.XX.XX
rbac:
  create: true
```

Any hints on how to debug this? Could be caused by a recent push on this repo?

Thanks,

**Comment by DandyDeveloper** [comment]
@lephleg 

Do you have metrics enabled or disabled?

By default, the values file has both `metrics` and `prometheusRule` set to `enabled: false` which implies that you're providing the `enabled:` values as empty? 

Can you throw us your values files for `.Values.controller.metrics`?

**Comment by lephleg** [comment]
@DandyDeveloper The metrics are disabled as we are using the defaults. The only values we are overwriting are the ones I've posted above.

**Comment by lephleg** [comment]
This hopefully has been solved by refreshing the `values.yml` file to the `helm upgrade` command instead of the`--reuse-values` flag:

```
helm upgrade <release-name> stable/nginx-ingress -f values.yml --set controller.config.block-referers=~*click2spam.net
```

After the refresh run the command executes properly again with the`--reuse-values` flag.
