### ISSUE TITLE
[stable/postgresql] initDbScripts gets permission error / blocks statefulset/pod from starting

### ISSUE THREAD

**Issue by wpfeiffe-alternate** [helm/charts#16652]
Init sql cause stable/postgres chart to fail startup.

**Version of Helm and Kubernetes**:
docker: 19.03.1
kubernetes: v1.14.3
helm: v2.14.3
windows: 10 Enterprise 1803 

**Which chart**:
stable/postgresql 

**What happened**:
When installing postgresql chart, any attempt at initializing db fails when the helm chart is installed with initDbScripts.  I've tried inlining the script into the valus.yaml, importing the script into a configmap and pointing to it.  In all instances the pod and stateful set never start.  When I check the logs on the pod.  I see this:

`
INSERT 0 1
INSERT 0 1
touch: cannot touch '/bitnami/postgresql/.user_scripts_initialized': Permission denied
[38;5;6m [38;5;5m12:07:09.23 [0m[38;5;2mINFO [0m ==> Stopping PostgreSQL...
2019-08-28 12:07:09.239 GMT [114] LOG:  received smart shutdown request
`

**What you expected to happen**:
I expected init sql to run and postgres to start successfully

**How to reproduce it** (as minimally and precisely as possible):
I'm guessing the issue is specific to docker desktop so just attempting to use init.sql via a config map or inline in values.yaml would reproduce the issue

**Anything else we need to know**:
It appears that the 'files/docker-entrypoint-initdb.d' approach does not run under docker desktop.  It doesn't fail, but any script file within that dir does not get executed either.

**Comment by javsalgar** [comment]
Hi,

I'm sure that it is related to the kind of PVC your platform is using. Could you try deploying the chart with `.Values.volumePermissions.enabled=true`?
