### ISSUE TITLE
stable/concourse no workers

### ISSUE THREAD

**Issue by mutt13y** [helm/charts#16663]
**Describe the bug**
Fresh install trying simple pipeline causes workers to crash and GUI error with "resource type not found: git"

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
**Which chart**:
stable/concourse

**What happened**:
workers crash logs show

```
{"timestamp":"1567011714.043987274","source":"worker","message":"worker.setup.unpacking","log_level":1,"data":{"session":"1"}}
{"timestamp":"1567011719.183004379","source":"worker","message":"worker.setup.done","log_level":1,"data":{"session":"1"}}
{"timestamp":"1567011719.195371628","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"bosh-io-release","session":"2.1.1"}}
{"timestamp":"1567011731.016901970","source":"worker","message":"worker.garden.extract-resources.extract.failed-to-extract-resource","log_level":2,"data":{"error":"exit status 2","output":"/concourse-work-dir/4.2.1/assets/bin/tar: etc/ssl/certs/02265526.0: Cannot utime: No such file or directory\n/concourse-work-dir/4.2.1/assets/bin/tar: etc/ssl/certs/03179a64.0: Cannot utime: No such file or directory\n/concourse-work-dir/4.2.1/assets/bin/tar: etc/ssl/certs/062cdee6.0: Cannot utime: No such file or directory\n/concourse-work-dir/4.2.1/assets/bin/tar: etc/ssl/certs/064e0aa9.0: Cannot utime: No such file or directory\n/concourse-work-dir/4.2.1/assets/bin/tar: etc/ssl/certs/080911ac.0: Cannot utime: No such file or directory\n/concourse-work-dir/4.2.1/assets/bin/tar: etc/ssl/certs/09789157.0: Cannot utime: No such file or directory\n/concourse-work-dir/4.2.1/assets/bin/tar: etc/ssl/certs/0b1b94ef.0: Cannot utime: No such file or directory\n/concourse-work-dir/4.2.1/assets/bin/tar: etc/ssl/certs/0b7c536a.0: Cannot utime: No such file or directory\n/concourse-work-dir/4.2.1/assets/bin/tar: etc/ssl/certs/0c4c9b6c.0: Cannot utime: No such file or directory\n/concourse-work-dir/4.2.1/assets/bin/tar: etc/ssl/certs/106f3e4d.0: Cannot utime: No such file or directory\n/concourse-work-dir/4.2.1/assets/bin/tar:
```

workers do not recover they stay in crashloopbackoff

The error looks like the PVC might have broken but it is bound

```
kubectl get pvc
NAME                                             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
concourse-postgresql                             Bound    pvc-251e6db9-c9b5-11e9-bf41-025000000001   8Gi        RWO            hostpath       34m
concourse-work-dir-concourse-worker-0            Bound    pvc-25399f1d-c9b5-11e9-bf41-025000000001   20Gi       RWO            hostpath       34m
concourse-work-dir-concourse-worker-1            Bound    pvc-2542c3e8-c9b5-11e9-bf41-025000000001   20Gi       RWO            hostpath       34m
```

**What you expected to happen**:
Worker should clone git repo

**How to reproduce it** (as minimally and precisely as possible):
``` 
helm install stable/concourse -n concourse
kubectl expose deployment concourse-web --type=LoadBalancer --name=concourse
fly login -t test -u test -p test -c http://127.0.0.1:8080
fly set-pipeline -t test --pipeline=test --config=git_test.yaml
```

**git_test.yaml**
```
resources:
- name: TEST
  type: git
  source: 
    uri: "REDACTED"
    branch: master
    private_key: |
      REDACTED
jobs:
- name: unit
  plan:
  - get: TEST
    trigger: true
```
**Anything else we need to know**:
I am not very experienced, probably I am doing something stoopid. If that is the case I think perhaps better install documentation or error messages are needed.

Also seems possibly related to 
https://github.com/helm/charts/issues/7781

**Comment by mutt13y** [comment]
I tested the same setup on EKS and it worked. So it looks like some issue with K8s for docker on mac.

**Comment by simonvpe** [comment]
Docker is known to have problems on Mac due to the bsd version of tar doing something different than Gnu tar
