### ISSUE TITLE
[stable/postgresql] how add extension ?

### ISSUE THREAD

**Issue by obeyler** [helm/charts#16667]
**Describe the bug**
I want to use postgresql as external database for github. In this case the postgresql db need pg_trgm extension.

I'm not sure it's a bug or not, I can not be in the right wayto use pg_trgm extension

to do that I add
```initdbScripts:
    init_postgres.sh: |
          #!/bin/bash
          export PGPASSWORD=$(cat /opt/bitnami/postgresql/secrets/postgresql-password);
          /opt/bitnami/postgresql/bin/psql -U gitlab -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;'
```

**Version of Helm and Kubernetes**:
Kubernetes 1.14.1
Helm 2.14.0

**Which chart**:
stable/postgresql
version 5.3.11

**What happened**:
ERROR: permission denied to create extension "pg_trgm"
HINT : must be superuser to create this extension

**What you expected to happen**:
I expect that the extension is accepted

**Comment by alemorcuq** [comment]
Hi, @obeyler.

That should work. However looking at this:

```
ERROR: permission denied to create extension "pg_trgm"
HINT : must be superuser to create this extension
```

It looks like you need to be superuser in order to create the extension. The superuser is the `postgres` user. Have you tried running that command as `postgres`?

Regards,
Alejandro

**Comment by obeyler** [comment]
Hy @alemorcuq As you said I use now postgres user to fix this issue. I'm not completely satisfied as my user is postgres instead of gitlab but it's working.

**Comment by alemorcuq** [comment]
Hi, @obeyler.

I'm not a PostgreSQL so I'm not really sure what else can be done here: if PostgreSQL wants you to be a superuser to create an extension then you have to be a superuser to create the extension. I've found this after a quick search, it may be useful for you: https://dba.stackexchange.com/questions/175319/postgresql-enabling-extensions-without-super-user

On the other hand, I think you could still be using the database as `gitlab`: you just need the `postgres` user to create the extension. Another option would be making the `gitlab` user a superuser, but I wouldn't recommend using the database as a superuser for security reasons.

Hope this helps.

Regards,
Alejandro
