### ISSUE TITLE
[incubator/fluentd-cloudwatch] hostNetwork is not actually configurable

### ISSUE THREAD

**Issue by danieltahara** [helm/charts#16676]
The documentation for the fluentd-cloudwatch chart claims that one can set `hostNetwork` to `true` via configuration.

However, from the initial commit of the chart, `hostNetwork` has been commented out in the config: https://github.com/helm/charts/blame/master/incubator/fluentd-cloudwatch/templates/daemonset.yaml#L39

This prohibits anyone from doing direct writes to fluentd via TCP or HTTP, instead forcing a pull-based model vis-a-vis k8s container logs.

The config line should be uncommented out.

**Comment by scottrigby** [comment]
More recent PR: #18680
