### ISSUE TITLE
[stable/grafana] setting up grafana in AWS EKS with AWS Certificate Manager

### ISSUE THREAD

**Issue by polganesh** [helm/charts#16684]
**Describe the bug**
I am planning to expose  grafana on https with certificate available from Amazon certificate manager (ACM)  
for this i am using documentation available [at ](https://aws.amazon.com/premiumsupport/knowledge-center/terminate-https-traffic-eks-acm/)

but unable to find way to expose this helm chart on https. when looking at service.yaml file of grafana unable to find it is having facility to configure port correctly for https.
it will be great if someone explain me how to use https with certificate from AWS certificate manager. 
**Version of Helm and Kubernetes**:

**Which chart**:
stable/grafana

**What happened**:
unable to find way to run grafana on https

**What you expected to happen**:
run grafana on https

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by runningman84** [comment]
Just use an ingress controller like alb ingress which supports acm. You could also try a nlb with ssl but this could be more difficult to setup.

**Comment by zanhsieh** [comment]
@polganesh Take a look at:
https://medium.com/kokster/how-to-setup-nginx-ingress-controller-on-aws-clusters-7bd244278509
Paid special attention on those under metadata.annotations: service.beta.kubernetes.io/*
