### ISSUE TITLE
[stable/prometheus-operator] Unable to install chart due default Garfana dashboard handling

### ISSUE THREAD

**Issue by ghost** [helm/charts#16680]
**Describe the bug**
While trying to install stable/prometheus-operator the installation fails with the following syntax error.

`Error: validation failed: error validating "": error validating data: ValidationError(ConfigMapList): missing required field "items" in io.k8s.api.core.v1.ConfigMapList`

There was already an PR which should fix this problem but it seems it doesn't work as expected. https://github.com/helm/charts/pull/11034

We could workaround this by setting grafana.defaultDashboardsEnabled to false.

**Version of Helm and Kubernetes**:
**Helm:**
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

**K8s:**

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

stable/prometheus-operator

**What happened**:
Installation fails with

`Error: validation failed: error validating "": error validating data: ValidationError(ConfigMapList): missing required field "items" in io.k8s.api.core.v1.ConfigMapList`

**What you expected to happen**:

Installation should complete with default Grafana dashboards.

**How to reproduce it** (as minimally and precisely as possible):

Install the chart.

**Anything else we need to know**:

**Comment by AndreasMueller-SAP** [comment]
The problem still persists.

**Comment by mohameddahrouj** [comment]
@AndreasMueller-SAP , did you have any luck with this issue last year?

**Comment by AndreasMueller-SAP** [comment]
@mohameddahrouj, well I don't know if the issue still persists, as I was able to install the prometheus-operator even with  `grafana.defaultDashboardsEnabled = true`. From my git history it looks like, I used a newer version of this helm chart.

**Comment by mohameddahrouj** [comment]
Thanks @AndreasMueller-SAP. Going to try installing it today, i'll report back how it went.

**Comment by nickjmv** [comment]
@mohameddahrouj any update? We are having the same issue
