### ISSUE TITLE
stable/postgresql] issue title

### ISSUE THREAD

**Issue by Lebronbingcheng** [helm/charts#16689]
**Describe the bug**
Because my cluster cannot access internet and helm is unavailable, I have to fill in templates and run 'kubectl apply -f' to deploy the postgresql. But  rejecting connections.

**Version of Helm and Kubernetes**:

**Which chart**:
postgresql

**What happened**:
In log of master, it shows  Role "repl_user" and "stolon" does not exist. "repl_user" is POSTGRES_REPLICATION_USER and "stolon" is POSTGRES_USER
'''
kubectl logs -n goharbor postgresql-master-0

 12:28:02.43 Welcome to the Bitnami postgresql container
 12:28:02.43 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
 12:28:02.44 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
 12:28:02.44 Send us your feedback at containers@bitnami.com
 12:28:02.44 
 12:28:02.47 INFO  ==> ** Starting PostgreSQL setup **
 12:28:02.57 INFO  ==> Validating settings in POSTGRESQL_* env vars..
 12:28:02.58 INFO  ==> Initializing PostgreSQL database...
 12:28:02.60 INFO  ==> postgresql.conf file not detected. Generating it...
 12:28:02.62 INFO  ==> pg_hba.conf file not detected. Generating it...
 12:28:02.64 INFO  ==> Deploying PostgreSQL with persisted data...
 12:28:02.64 INFO  ==> Cleaning stale postmaster.pid file
 12:28:02.79 INFO  ==> Configuring replication parameters
 12:28:02.85 INFO  ==> Configuring fsync
 12:28:02.87 INFO  ==> Loading custom scripts...
 12:28:02.88 INFO  ==> Enabling remote connections
 12:28:02.90 INFO  ==> Stopping PostgreSQL...
 12:28:02.91 INFO  ==> ** PostgreSQL setup finished! **

 12:28:03.01 INFO  ==> ** Starting PostgreSQL **
2019-08-29 12:28:03.249 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-08-29 12:28:03.249 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2019-08-29 12:28:03.253 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-08-29 12:28:04.659 GMT [154] LOG:  database system was interrupted; last known up at 2019-08-29 12:27:22 GMT
2019-08-29 12:28:12.040 GMT [163] FATAL:  the database system is starting up
2019-08-29 12:28:22.080 GMT [172] FATAL:  the database system is starting up
2019-08-29 12:28:32.050 GMT [180] FATAL:  the database system is starting up
2019-08-29 12:29:23.821 GMT [154] LOG:  database system was not properly shut down; automatic recovery in progress
2019-08-29 12:29:24.135 GMT [154] LOG:  redo starts at 0/1649C98
2019-08-29 12:29:24.136 GMT [154] LOG:  invalid record length at 0/1649D40: wanted 24, got 0
2019-08-29 12:29:24.136 GMT [154] LOG:  redo done at 0/1649CD0
2019-08-29 12:29:24.635 GMT [253] FATAL:  the database system is starting up
2019-08-29 12:29:25.652 GMT [254] FATAL:  the database system is starting up
2019-08-29 12:29:26.644 GMT [1] LOG:  database system is ready to accept connections
2019-08-29 12:29:27.078 GMT [261] FATAL:  password authentication failed for user "repl_user"
2019-08-29 12:29:27.078 GMT [261] DETAIL:  Role "repl_user" does not exist.
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
2019-08-29 12:29:27.299 GMT [262] FATAL:  password authentication failed for user "repl_user"
2019-08-29 12:29:27.299 GMT [262] DETAIL:  Role "repl_user" does not exist.
	Connection matched pg_hba.conf line 4: "host      replication     all             0.0.0.0/0               md5"
2019-08-29 12:29:28.756 GMT [263] FATAL:  password authentication failed for user "repl_user"
2019-08-29 12:29:28.756 GMT [263] DETAIL:  Role "repl_user" does not exist.
	Connection matched pg_hba.conf line 4: "host      replication     all             0.0.0.0/0               md5"
2019-08-29 12:29:29.789 GMT [264] FATAL:  password authentication failed for user "repl_user"
2019-08-29 12:29:29.789 GMT [264] DETAIL:  Role "repl_user" does not exist.
	Connection matched pg_hba.conf line 4: "host      replication     all             0.0.0.0/0               md5"
2019-08-29 12:29:32.056 GMT [273] FATAL:  password authentication failed for user "stolon"
2019-08-29 12:29:32.056 GMT [273] DETAIL:  Role "stolon" does not exist.
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"

'''

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by Lebronbingcheng** [comment]
But I have config them in yaml files
'''
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: cambricon-postgresql-master
  labels:
    app: postgresql
    release: "cambricon"
spec:
  serviceName: cambricon-postgresql-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: postgresql
      release: "cambricon"
      role: master
  template:
    metadata:
      name: cambricon-postgresql
      labels:
        app: postgresql
        release: "cambricon"
        role: master
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: cambricon-postgresql
        image: docker.cambricon.com/library/goharbor/postgresql:11.4.0-debian-9-r12
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            cpu: 250m
            memory: 256Mi

        securityContext:
          runAsUser: 1001
        env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: POSTGRESQL_PORT_NUMBER
          value: "5432"
        - name: PGDATA
          value: "/bitnami/postgresql/data"
        - name: POSTGRES_REPLICATION_MODE
          value: "master"
        - name: POSTGRES_REPLICATION_USER
          value: "repl_user"
        - name: POSTGRES_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cambricon-postgresql
              key: postgresql-replication-password
        - name: POSTGRES_SYNCHRONOUS_COMMIT_MODE
          value: "on"
        - name: POSTGRES_NUM_SYNCHRONOUS_REPLICAS
          value: "{{harbor_psql_replicas}}"
        - name: POSTGRES_CLUSTER_APP_NAME
          value: my_application
        - name: POSTGRES_USER
          value: "stolon"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cambricon-postgresql
              key: postgresql-password
        ports:
        - name: postgresql
          containerPort: 5432
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U "stolon" -h 127.0.0.1 -p 5432
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              pg_isready -U "stolon" -h 127.0.0.1 -p 5432
              [ -f /opt/bitnami/postgresql/tmp/.initialized ]
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        volumeMounts:
        - name: data
          mountPath: /bitnami/postgresql
          subPath:
      volumes:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: standard
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"

'''

**Comment by alemorcuq** [comment]
Hi, @Lebronbingcheng.

Looking at your log:

```
12:28:02.57 INFO ==> Validating settings in POSTGRESQL_* env vars..
12:28:02.58 INFO ==> Initializing PostgreSQL database...
12:28:02.60 INFO ==> postgresql.conf file not detected. Generating it...
12:28:02.62 INFO ==> pg_hba.conf file not detected. Generating it...
12:28:02.64 INFO ==> Deploying PostgreSQL with persisted data...
```

It looks like you already have data persisted, so PostgreSQL isn't being configured with the environment variables. Probably your persisted data doesn't have either the `repl_user` nor the `stolon` users.

Regards,
Alejandro
