### ISSUE TITLE
Document stable/incubator deprecation timeline

### ISSUE THREAD

**Issue by mattfarina** [helm/charts#16720]
Now that Helm v2 has a deprecation timeline (proposed and we'll need to close out on) at https://github.com/helm/helm/issues/6144 we can talk about a deprecation timeline for the stable and incubator repositories which needs to happen.

For those that don't know there are some reasons for this...

1. These repositories are graciously hosted for us by Google on account created prior to the CNCF. The buckets cannot be moved to new projects so at the very least the bucket names need to be deprecated.
2. The stable and incubator repositories are not available in China and some other territories.
3. These repositories have acted as a sort of central repository even though that was not the original intent. Maintenance and handling of so many charts have become difficult and can be seen in a lack of response to PRs or issues.
4. The Helm Hub now exists to enable federated model of charts. You can think of them as being like packagist for PHP. The federated model was part of the original intent with Helm. Apt, Homebrew, and many other package managers operate on this model. It empowers people to host and share.
5. Storing Helm Charts in OCI registries is coming. This may change the model for distributing them.

I would suggest that the day Helm v2 is no longer supported the stable and incubator repositories become deprecated. We can back them up so that when google reclaims the bucket they are in some state. And, that we target everything moving to a distributed model prior to that. 

This is just a proposal at this point.

cc @helm/charts-maintainers

**Comment by bacongobbler** [comment]
I made a note of this in https://github.com/helm/helm/pull/6695 if any of the chart maintainers would like to have a look.

**Comment by desaintmartin** [comment]
My two cents:

1/ We should clearly stop accepting new charts from now on if it is not already the case. For this, we need...
2/ Clear guides to host helm repositories (stateful using chart-museum, stateless using gh-pages with ready-to-use GitHub Actions, Travis config, etc). 
For now it is still hard to come with something stateless for use cases where a github repository with one project decides to host its helm chart as chart-releaser does not support this use case (yet).
3/ We should actively advocate decentralization for the most-used charts and then create an issue for the remaining charts

As I am moving kubernetes-dashboard into kubernetes/dashboard (so it has to be clean, without hacks), I represent a good guinea pig to experiment with.

**Comment by scottrigby** [comment]
Update: Here is the current plan for this repo (github.com/helm/charts), the source for Helm v2 `stable` and `incubator` repos:

- 1 year deprecation starting the day [Helm 3.0.0 was released](https://helm.sh/blog/helm-3-released/) (Nov 13, 2019). New charts are no longer accepted, but patches can continue to be accepted
- At 6 months (May 13, 2020) – when helm v2 goes security fix only – the stable/incubator repos will be de-listed from the helm hub
- At 1 year (Nov 13, 2020) this repo will be obsolete

This gives the community (chart OWNERS, organizations, groups or individuals, etc) 6 months to move charts to new Helm repos, and list them on https://helm.hub.sh (see https://github.com/helm/hub) before stable/incubator is de-listed from the hub.

**Comment by scottrigby** [comment]
This is in the README now :+1:
