### ISSUE TITLE
[stable/percona-xtradb-cluster] Service type

### ISSUE THREAD

**Issue by hydeenoble** [helm/charts#16751]
**Is your feature request related to a problem? Please describe.**
I want to be able to expose percona-xtradb-cluster so an external client (outside) Kubernetes can connect to it.

**Describe the solution you'd like**
An Option to add a LoadBalancer type to the service should be provided so external clients can connect to it outside Kubernetes - currently, only a cluster IP is provided

**Describe alternatives you've considered**
I have not considered any other alternatives

PS: I would be happy to take this up if my request is granted.

**Comment by HristoA** [comment]
Interested also
