### ISSUE TITLE
[stable/redis] Incomplete network policy

### ISSUE THREAD

**Issue by qbast** [helm/charts#16830]
**Describe the bug**

Network policy included in the helm chart covers only ingress. In case of fully locked down defaults (both egress and ingress) slaves and sentinels cannot connect to master.

**Version of Helm and Kubernetes**:

9.1.5

**Which chart**:

stable/redis

**What happened**:

Deployed redis cluster with following settings:

```
cluster:
  enabled: true
  slaveCount: 2
sentinel:
  enabled: true
networkPolicy:
  enabled: true
  allowExternal: false

```
The namespace has a default network policy with no ingress allowed and only port 53 UDP/TCP for egress.
Both sentinels and slaves encountered timeout when trying to connect to the master.
Manually creating additional policy to allow egress for ports 6379 and 26379 fixed the problem.

**What you expected to happen**:

Created network policy should include 'egress' block matching the ingress one.

**How to reproduce it** (as minimally and precisely as possible):
Create default network policy that forbids any ingress and allows port 53 UDP/TCP to everywhere.
Deploy stable/redis with enabled network policy, cluster and sentinel.
Check logs for redis container on slave pod - it will report timeout while trying to connect to master.

**Comment by juan131** [comment]
Hi @qbast 

Thanks so much for reporting this issue. Checking your PR...
