### ISSUE TITLE
[stable/redis-ha] haproxy unable to set NodePort

### ISSUE THREAD

**Issue by kfkawalec** [helm/charts#16858]
**Describe the bug**
I want to connect to redis (haproxy) outside the kube cluster, so I change the redis port (for example to 30204) and set haproxy.service.type to NodePort.
Then the redis slave device cannot connect to the master device and all redis nodes will restart.
It seems to me that this is because the default redis port has been hardcoded in several files and although I change the pods port it still connects to the default.

**Which chart**:
stable/redis-ha 3.7.3

**What happened**:
Redis wont start 

**How to reproduce it** (as minimally and precisely as possible):
Change default Redis port (for example to 30204) and set haproxy.service.type to NodePort

**Comment by DandyDeveloper** [comment]
@kfkawalec Good suggestion. I hadn't considered people wanting to change the HAProxy exposed port.

The Redis port is hard-coded in the HAProxy configmap right now:

```
    # decide redis backend to use
    frontend ft_redis
      bind *:6379
      use_backend bk_redis
```

We can change it pretty easily to be flexible. I'll have a look see if I can get this in.
