### ISSUE TITLE
[stable/nextcloud] Cannot upload images files when using ingress annotations

### ISSUE THREAD

**Issue by cvandesande** [helm/charts#16860]
**Describe the bug**
In values.yaml, if you use enable ingress and uncomment the annotations, you will not be able to upload image files. (Tested png and jpeg). I suspect the issue is related to this setting:
`location ~ \.(?:png|html|ttf|ico|jpg|jpeg)$ {`
Though I don't know why it's broken

**Version of Helm and Kubernetes**:`
Helm:
```$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
Kubernetes:
```
$ kubectl get nodes
NAME       STATUS   ROLES    AGE   VERSION
kmaster    Ready    master   21h   v1.14.6-k3s.1
kworker1   Ready    worker   21h   v1.14.6-k3s.1

```
**Which chart**:
stable/nextcloud

**What happened**:
"An unknown error has occurred"  message when trying to upload jpg file
Ingress log:
```
2019/09/04 20:17:16 [error] 617#617: *86972 rewrite or internal redirection cycle while internally redirecting to "/index.php/remote.php/webdav/wZAlVrObSUi88xl
```

**What you expected to happen**:
File uploads

**How to reproduce it** (as minimally and precisely as possible):
deploy stable/nextcloud with ingress enabled and the annotation uncommented
[values.yaml.txt](https://github.com/helm/charts/files/3576343/values.yaml.txt)

**Anything else we need to know**:
Example values.yaml attached

**Comment by cvandesande** [comment]
Incidentally image uploads work if I don't use ingress, and expose nextcloud as NodePort

**Comment by chrisingenhaag** [comment]
Yes you´re right. It doesn´t work with this part. Please remove and try without it. I tested it and recognized that nginx-ingress shows errors of infinite redirects.
Without it should work basically but there might be other requests that aren´t working. Please feel free to contact me if there are more things to do.

Indeed I couldn´t just take all nginx config values from nextcloud https://docs.nextcloud.com/server/16/admin_manual/installation/nginx.html?highlight=nginx .  For example the block 

```
    location / {
        rewrite ^ /index.php$request_uri;
    }
```

cannot be used because it´s a default block created from nginx-ingress controller which cannot be overwritten with an annotation.

I´m constantly working on a config which can be taken as default like the ones in the nextcloud docs but I´m happy to get feedback and ideas how to tweak nginx config.

**Comment by cvandesande** [comment]
No worries, your work is well appreciated. I haven't found a solution that supports ingress to fix this but I'll try a few more things. Thanks for the reply!

September 16, 2019 9:42 PM, "Christian Ingenhaag" <notifications@github.com (mailto:notifications@github.com?to=%22Christian%20Ingenhaag%22%20<notifications@github.com>)> wrote:
	Yes you´re right. It doesn´t work with this part. Please remove and try without it. I tested it and recognized that nginx-ingress shows errors of infinite redirects.
Without it should work basically but there might be other requests that aren´t working. Please feel free to contact me if there are more things to do.

	Indeed I couldn´t just take all nginx config values from nextcloud https://docs.nextcloud.com/server/16/admin_manual/installation/nginx.html?highlight=nginx (https://docs.nextcloud.com/server/16/admin_manual/installation/nginx.html?highlight=nginx) . For example the block

	 location / { rewrite ^ /index.php$request_uri; } 

	cannot be used because it´s a default block created from nginx-ingress controller which cannot be overwritten with an annotation.

	I´m constantly working on a config which can be taken as default like the ones in the nextcloud docs but I´m happy to get feedback and ideas how to tweak nginx config.

**Comment by titilambert** [comment]
Hello, I have the same issue with the chart version 1.7.2
I fixed it commenting the following lines in the ingress
```
            #location ~ \.(?:png|html|ttf|ico|jpg|jpeg)$ {
            #  try_files $uri /index.php$request_uri;
            #  # Optional: Don't log access to other assets
            #  access_log off;
            #}
```

**Comment by chrisingenhaag** [comment]
Ok I think we got this done with the current possibilities with nginx-ingress.

/close
