### ISSUE TITLE
[stable/redis-ha] Upgrade from HAProxy exporter to official prometheus exporter

### ISSUE THREAD

**Issue by Raab70** [helm/charts#16861]
**Is your feature request related to a problem? Please describe.**
the stable/redis-ha chart currently uses a [deprecated](https://github.com/prometheus/haproxy_exporter#official-prometheus-exporter) prometheus exporter sidecar container for HAProxy metrics. A prometheus endpoint is available in HAProxy since 2.0.0 (default chart install is 2.0.4) [ref](https://github.com/helm/charts/blob/master/stable/redis-ha/values.yaml#L32)

**Describe the solution you'd like**
The sidecar should be removed in favor of the official exporter. A new configuration `haproxy.metrics.enabled=true` should enable an official prometheus stats endpoint per the [documentation](https://github.com/prometheus/haproxy_exporter#official-prometheus-exporter) and appropriate prometheus scrape annotations.

**Describe alternatives you've considered**
The current exporter setup could be maintained if there is interest from the community in running HAProxy 1.x and using the exporter. Documentation would need to be made clear that the preferred method for enabling prometheus monitoring is the official exporter and the sidecar method should only be used if running HAProxy 1.x.

**Additional context**
None

**Comment by DandyDeveloper** [comment]
@Raab70 I'll be honest, didn't think too much about the exporter at the time. Quick change in theory. I'll look into getting this in asap.

**Comment by Raab70** [comment]
Thanks, I’d also be happy to open a PR for this. Just wasn’t sure of the direction we’d want to go as I mentioned about what we would want to support but it sounds like removing the sidecar in favor of the official endpoint will work so I can go ahead and make that change which would also close #16862.

**Comment by DandyDeveloper** [comment]
@Raab70 From my perspective, removing the sidecar as there's a native endpoint to scrape on the HAProxy version seems like the logical step forward. 

We just need to be careful this doesn't break existing deployments (It shouldn't). 

If you get a chance to make a PR, I'd welcome it for both. If not, I'll get around to it sometime early next week.
