### ISSUE TITLE
[stable/redis-ha] HAProxy does not expose a slave endpoint

### ISSUE THREAD

**Issue by Raab70** [helm/charts#16863]
**Is your feature request related to a problem? Please describe.**
A common use-case for redis sentinel behind HAProxy is to migrate an existing workload to a sentinel controlled redis cluster. To this end if clients are currently connected to redis followers ([formerly known as slaves](https://redis.io/topics/replication)) under the current chart they would be unable to migrate and still get a follower connection as HAProxy only exposes an endpoint for masters. 

**Describe the solution you'd like**
The chart should also allow for the configuration of a follower endpoint on a given port. Something like:

```
haproxy:
 follower:
    enabled: true
    port: 6380
```
Which would provide a single endpoint for applications to connect to a redis follower. 

**Describe alternatives you've considered**
A second HAProxy service could be run that could expose a follower endpoint but it seems wasteful as opposed to just using a different port on the existing HAProxy service. 

**Additional context**
An example can be seen in this chart: https://github.com/prodriguezdefino/charts/tree/master/incubator/haproxy-redis

**Comment by DandyDeveloper** [comment]
This should be resolved with: https://github.com/helm/charts/pull/16824

I'll be reviewing this today and providing some feedback.
