### ISSUE TITLE
[stable/prometheus-operator]helm install prometheus-operator, how use grafana Data persistence

### ISSUE THREAD

**Issue by wangchuang-codes** [helm/charts#16872]
please help me, thanks.

**Comment by vsliouniaev** [comment]
Here is the reference from the grafana chart:
https://github.com/helm/charts/blob/master/stable/grafana/values.yaml#L170-L183

Here is helm documentation on how to set values for a child chart:
https://github.com/helm/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md#overriding-values-of-a-child-chart

**Comment by Eji4h** [comment]
```yaml
grafana:
  persistence:
    enabled: true
```
