### ISSUE TITLE
Add @vishiy as trusted collaborator

### ISSUE THREAD

**Issue by vishiy** [helm/charts#16874]
i own and maintain azuremonitor-containers chart as part of microsoft azure. thanks.
@lachie83

**Comment by lachie83** [comment]
+1

This is the chart he is referencing - https://github.com/helm/charts/tree/master/incubator/azuremonitor-containers

**Comment by zanhsieh** [comment]
@vishiy @ganga1980 
You guys should submit a separate PR, adding yourself into chart OWNERS file, then approach to helm member to add you as member and approved you as one of the chart OWNERs; otherwise nobody will look at this issue nor create PR for you.

**Comment by ganga1980** [comment]
> You guys should submit a separate PR, adding yourself into chart OWNERS file, then approach to helm member to add you as member and approved you as one of the chart OWNERs; otherwise nobody will look at this issue nor create PR for you.

@zanhsieh , Let me get the PR with our names in chart OWNERS. But, appreciate if you can help on getting the current PR since existing chart broken since week also. Lot of people are pinging us about this issue.
