### ISSUE TITLE
MariaDB no resource limits or requests

### ISSUE THREAD

**Issue by chrislovecnm** [helm/charts#169]
https://github.com/kubernetes/charts/blob/master/stable/mariadb/templates/deployment.yaml

No resource usage settings :(

**Comment by lachie83** [comment]
Thanks @chrislovecnm. Would you be interested in submitted a PR with the required changes?

**Comment by lachie83** [comment]
FYI -- This issue looks very similar to #60 which references the same chart

**Comment by lachie83** [comment]
@prydonius I will defer to your experience on some sane resource default for MariaDB

**Comment by chrislovecnm** [comment]
@lachie83 256m .25 cpu on both ... good starting point.  But who knows ...
