### ISSUE TITLE
[stable/redis-ha]:/readonly-config/init.sh: line 84: Could not resolve the announce ip for this pod: not found

### ISSUE THREAD

**Issue by Water0** [helm/charts#16911]
Encounter error with [stable/redis-ha]，detail logs show in config-init pod as :
![config-init](https://user-images.githubusercontent.com/19567488/64401756-ea8f8900-d0a4-11e9-9680-7c4336645218.png)

Rancher: v2.2.5
Kubernetes: v1.14.1
Network: Canal v3.4.0  (with project network isolated disabled)
chart: stable/redis-ha (with redis:5.0.5-alpine)
![node](https://user-images.githubusercontent.com/19567488/64401822-36dac900-d0a5-11e9-8069-4b4fed5933a8.png)

With newly clone charts, I only change the pv size to 2Gi in values.yaml。 

The following are details:
====================
[root@k8s-master01 ~]# kubectl describe pod redis-cluster-redis-ha-server-0 -n redis-ns
Name:               redis-cluster-redis-ha-server-0
Namespace:          redis-ns
Priority:           0
PriorityClassName:  <none>
Node:               k8s-master03/192.168.56.112
Start Time:         Fri, 06 Sep 2019 12:30:47 +0800
Labels:             app=redis-ha
                    controller-revision-hash=redis-cluster-redis-ha-server-cdbf449f9
                    release=redis-cluster
                    statefulset.kubernetes.io/pod-name=redis-cluster-redis-ha-server-0
Annotations:        checksum/init-config: c99d75b4c87b504dd21ea68f78230a354bcac24c4a9bdb88c8eb0d25e150faad
                    cni.projectcalico.org/podIP: 10.42.2.27/32
Status:             Pending
IP:                 10.42.2.27
Controlled By:      StatefulSet/redis-cluster-redis-ha-server
Init Containers:
  config-init:
    Container ID:  docker://d3a5f34505136b9f70eb286b54229f8f7ec9a33464c22d67e3608021033bd6ed
    Image:         redis:5.0.5-alpine
    Image ID:      docker-pullable://redis@sha256:50899ea1ceed33fa03232f3ac57578a424faa1742c1ac9c7a7bdb95cdf19b858
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
    Args:
      /readonly-config/init.sh
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    127
      Started:      Fri, 06 Sep 2019 12:55:30 +0800
      Finished:     Fri, 06 Sep 2019 12:55:50 +0800
    Ready:          False
    Restart Count:  9
    Environment:
      SENTINEL_ID_0:  bb40c01406652e900099be280304149f703d443a
      SENTINEL_ID_1:  b9b0231bb959f53f2dfaa80343c4528e53c42d1c
      SENTINEL_ID_2:  ad93c911889f67ba4cffb5ab91ea6cb2bf4417af
    Mounts:
      /data from data (rw)
      /readonly-config from config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from redis-cluster-redis-ha-token-gs46c (ro)
Containers:
  redis:
    Container ID:  
    Image:         redis:5.0.5-alpine
    Image ID:      
    Port:          6379/TCP
    Host Port:     0/TCP
    Command:
      redis-server
    Args:
      /data/conf/redis.conf
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       tcp-socket :6379 delay=15s timeout=1s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from redis-cluster-redis-ha-token-gs46c (ro)
  sentinel:
    Container ID:  
    Image:         redis:5.0.5-alpine
    Image ID:      
    Port:          26379/TCP
    Host Port:     0/TCP
    Command:
      redis-sentinel
    Args:
      /data/conf/sentinel.conf
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       tcp-socket :26379 delay=15s timeout=1s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from redis-cluster-redis-ha-token-gs46c (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-redis-cluster-redis-ha-server-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      redis-cluster-redis-ha-configmap
    Optional:  false
  redis-cluster-redis-ha-token-gs46c:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  redis-cluster-redis-ha-token-gs46c
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                   From                   Message
  ----     ------            ----                  ----                   -------
  Warning  FailedScheduling  27m (x4 over 28m)     default-scheduler      pod has unbound immediate PersistentVolumeClaims (repeated 2 times)
  Normal   Scheduled         27m                   default-scheduler      Successfully assigned redis-ns/redis-cluster-redis-ha-server-0 to k8s-master03
  Normal   Pulling           27m                   kubelet, k8s-master03  Pulling image "redis:5.0.5-alpine"
  Normal   Pulled            27m                   kubelet, k8s-master03  Successfully pulled image "redis:5.0.5-alpine"
  Normal   Created           24m (x5 over 27m)     kubelet, k8s-master03  Created container config-init
  Normal   Started           24m (x5 over 27m)     kubelet, k8s-master03  Started container config-init
  Normal   Pulled            22m (x5 over 26m)     kubelet, k8s-master03  Container image "redis:5.0.5-alpine" already present on machine
  Warning  BackOff           2m25s (x99 over 26m)  kubelet, k8s-master03  Back-off restarting failed container

====================
[root@k8s-master01 ~]# kubectl logs -f redis-cluster-redis-ha-server-0 -c config-init -n redis-ns
Could not connect to Redis at redis-cluster-redis-ha:26379: Try again
Initializing config..
/readonly-config/init.sh: line 84: Could not resolve the announce ip for this pod: not found
[root@k8s-master01 ~]#

**Comment by Water0** [comment]
I have one master node with two worker node, showing as the picture:
![cluster](https://user-images.githubusercontent.com/19567488/64402280-f11f0000-d0a6-11e9-9df6-d2c41eaa6d17.png)

Anyone can help ? 

Thanks in advance.

**Comment by DandyDeveloper** [comment]
@Water0 Do you have the services deployed successfully with bound IP addresses?

The init container will try to resolve the service IP here. 

`ANNOUNCE_IP=$(getent hosts "$SERVICE-announce-$INDEX" | awk '{ print $1 }')`

**Comment by Water0** [comment]
> @Water0 Do you have the services deployed successfully with bound IP addresses?
> 
> The init container will try to resolve the service IP here.
> 
> `ANNOUNCE_IP=$(getent hosts "$SERVICE-announce-$INDEX" | awk '{ print $1 }')`

I can get the annouce_ip in another running pod with full FQDN name, show as the following pics:

![svc](https://user-images.githubusercontent.com/19567488/64531632-87228700-d342-11e9-8f42-88a4a44546f0.png)
![svc-shell](https://user-images.githubusercontent.com/19567488/64531634-88ec4a80-d342-11e9-8abe-1b07ed389f2a.png)

**Comment by Water0** [comment]
@DandyDeveloper 
Thanks for you reply! I can get the annouce_ip in another running pod with full FQDN name. All of the announce service are type of ClusterIP while the other is of Headless.

![svc](https://user-images.githubusercontent.com/19567488/64531745-c3ee7e00-d342-11e9-93ad-f5357e629435.png)
![svc-shell](https://user-images.githubusercontent.com/19567488/64531748-c4871480-d342-11e9-938c-fe60a1538e5a.png)

**Comment by DandyDeveloper** [comment]
@Water0 Are you running on-prem? Do you have hairpin mode enabled for the networking plugin you have enabled?

Typically, pods cannot communicate with their own services and vice-versa unless you have the hairpin mode enabled for your K8 networking plugin.

That's the only logic reason I can think you'd be having this problem.

**Comment by kish3007** [comment]
I am running into this issue as well, when i tried setting up HPA on redis-ha stateful set , the new pods run into this problem

``` Initializing config..                                                                                                                                                                                                                        │
│ /readonly-config/init.sh: line 84: Could not resolve the announce ip for this pod: not found
```

**Comment by Water0** [comment]
@kish3007, sorry for no updates since I'm busy with other tasks.  Per the reply by @DandyDeveloper,  incorrect network maybe the cause. Following the link:

https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#a-pod-cannot-reach-itself-via-service-ip

I will be back to double check & try it later.  Thanks @DandyDeveloper for your help!

**Comment by kish3007** [comment]
@Water0 i dont think there is a problem with network plugin, its just that we are not able to scale the statefulset redis pods after the helm chart is deployed with replica count, i have a hpa.yaml like below:
```apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-hpa
  namespace: redis
spec:
  maxReplicas: {{ .Values.autoscaling.max_replicas }}
  minReplicas: {{ .Values.autoscaling.min_replicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: redis-redis-ha-server
  targetCPUUtilizationPercentage: 80
```
This didnt work as the stateful set redis pods have dependency to init process and also it needs `redis-redis-ha-announce` service to be up before we scale the actual redis pods, so thats why it needs a feature request to support HPA as part of the helm chart coz right now someone need to manually scale up by overriding the replicaCount in helm upgrade process.

**Comment by mokrinsky** [comment]
I have the same problem with a new deployment on empty kubernetes cluster 1.16. I followed link provided by @Water0 and I have hairpin enabled, so networking probably is not the case. I tried nslookup'ing of service and it's not in DNS.

**Comment by annerajb** [comment]
Still have this issue was it ever found the cause to be network CNI?

**Comment by MirzaSikander** [comment]
I am also running into this issue. Anyone has had any luck fixing this?

**Comment by therealqxing** [comment]
Any updates? I have the same problem with brand new kubernetes v1.17.9 (kubeproxy in ipvs mode), and redis-ha helm version 3.9.2.
