### ISSUE TITLE
[stable/prometheus] alertmanager.configFromSecret does not work when Alertmanager is deployed as a StatefulSet

### ISSUE THREAD

**Issue by petrikero** [helm/charts#16913]
**Describe the bug**

If both alertmanager.statefulSet.enabled is true and alertmanager.configFromSecret is specified, the alertmanager pods look for the config from the default ConfigMap anyway.

Looking at templates/alertmanager-statefulset.yaml, there is no mention of configFromSecret at all (the related configMapOverrideName is supported, though).

**Version of Helm and Kubernetes**: any

**Which chart**: stable/prometheus

**What happened**:

The prometheus-alertmanager-0 pod fails to start due to it being unable to mount the non-existent 'prometheus-alertmanager' ConfigMap.

**What you expected to happen**:

I was expecting the alertmanager to use the specified alertmanager.configFromSecret instead.

**How to reproduce it** (as minimally and precisely as possible):

Create file called `v.yaml`:
```
alertmanager:
  statefulSet:
    enabled: true
  configFromSecret: "my-secret-config"
```

Then deploy the chart:
`helm upgrade --install foo stable/prometheus -f v.yaml`

Now, `kubectl describe pod foo-prometheus-alertmanager-0` tells us:
MountVolume.SetUp failed for volume "config-volume" : configmaps "foo-prometheus-alertmanager" not found

**Anything else we need to know**:

My understanding is that StatefulSets are the way to deploy a highly available Alertmanager. It would be really great if it supported the ability to keep the various Alertmanager secrets (API keys for Slack, PagerDuty, etc.) in a k8s secret.

**Comment by petrikero** [comment]
Does anyone know what is the recommended way to do a highly-available deployment of Prometheus using the chart? Currently, it doesn't seem obvious how it should be done while keeping the secrets safe (ie, in a k8s secret).

**Comment by superawesome** [comment]
This appears to still be the case today: https://github.com/helm/charts/blob/master/stable/prometheus/templates/alertmanager-statefulset.yaml does not reference configFromSecret anywhere.

**Comment by appunni-dishq** [comment]
has this been fixed ?
