### ISSUE TITLE
[stable/mariadb] image tag: 10.2  - ALLOW_EMPTY_PASSWORD: unbound variable

### ISSUE THREAD

**Issue by moconno** [helm/charts#16938]
**Describe the bug**
Installation fails with this error:  /libmysql.sh: line 338: ALLOW_EMPTY_PASSWORD: unbound variable

**Version of Helm and Kubernetes**:
Helm
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}

minikube version
minikube version: v1.2.0

**Which chart**:
stable/mariadb

**What happened**:
ALLOW_EMPTY_PASSWORD is missing in libmysql.sh.  This causes unbound variable exception when the variable is evaluated. 

**What you expected to happen**:
ALLOW_EMPTY_PASSWORD to be set in script 

**How to reproduce it** (as minimally and precisely as possible):
helm install --name mariadb --set image.tag=10.2 stable/mariadb

**Anything else we need to know**:
It looks like the ALLOW_EMPTY_PASSWORD is exported on line 254: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.2/ol-7/rootfs/libmysql.sh.   But when I exec into the slave pod and view the script, the export is missing.  Not sure if the github repo is reflecting the acutal file stoed on docker.io.

**Comment by miguelaeh** [comment]
Hi @moconno ,
Thank you very much for reporting, we did a change last week and the chart image was not update to the latest release. 
It should be solved using the image tag `10.3.17-debian-9-r42`
