### ISSUE TITLE
[stable/jenkins] init.groovy.d configmap value

### ISSUE THREAD

**Issue by jl431** [helm/charts#16947]
**Is your feature request related to a problem? Please describe.**
I haven't been able to find a way of templating the jenkins.initScripts value that ends up in /var/jenkins_home/init.groovy.d/

The advantages would be:
1. Groovy scripts could change dynamically based on user supplied values
2. The values.yaml wouldn't have to get as polluted with the numerous groovy scripts present on heavily preconfigured Jenkins systems
3. We can control the file naming of the init scripts which would give us better control over the execution order of the groovy scripts (executed in alphabetical order)

**Describe the solution you'd like**
If we supply a new values.yaml option E.g. jenkins.initScriptCM, the user could supply their own config map containing each groovy script and name they want for each.

**Describe alternatives you've considered**
I've only thought of two alternatives to this feature.

Keep all scripts in the values.yaml, meaning manually having to change each groovy script for each deployment
Maybe the JCasC option supports groovy scripts but they will be retriggered every time the container starts which isn't always what we want as user configuration is allowed to diverge from the initial configuration in some setups

I would be happy to work on this feature request if this feature sounds like a good idea.

**Comment by torstenwalter** [comment]
Have you tried `master.initScripts` https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml#L180-L182

It's been used to template the scripts here: https://github.com/helm/charts/blob/master/stable/jenkins/templates/config.yaml#L291-L293 which are then copied from `/var/jenkins_config/*.groovy` to `/var/jenkins_home/init.groovy.d/` 
https://github.com/helm/charts/blob/master/stable/jenkins/templates/config.yaml#L255-L267

**Comment by jl431** [comment]
Yes, but by dumping entire groovy scripts into master.initScripts, we can't template because anything in the values file is rendered as is. Using the current method, we must hard code the groovy in its entirety.

For example if in a within the master.initScripts the hard coded version could be:
`
  roleBasedAuthenticationStrategy.assignRole(RoleBasedAuthorizationStrategy.GLOBAL, adminRole, "user1")
  roleBasedAuthenticationStrategy.assignRole(RoleBasedAuthorizationStrategy.GLOBAL, adminRole, "user2")
`

But if we added it via a config map we could use the power of templating within the configmap to assist us on each deployment:
```
# values.yaml
admins:
  - me
  - you
  - user1
  - user2
```
` 
# config map
    {{- range .Values.admins }}
roleBasedAuthenticationStrategy.assignRole(RoleBasedAuthorizationStrategy.GLOBAL, adminRole, "{{ .  }}")
    {{- end }} 
`
This allows us to pass just the admin list in the values file instead of having to maintain and update the same groovy script in different deployments values.yaml files.

**Comment by torstenwalter** [comment]
Now I get your point. If you are going to template config maps within this chart you'll run into templating limitations as well. I mean somehow the logic needs to be put into that file.

Some additional ideas:
- One could add `tpl` support for the existing values. See https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#using-the-tpl-function

- In the past I wrote lot's of grrovy scripts, but migrated most of them to configuration as code via JCasC plugin. With the reload functionality enabled you can also template confimaps outside of this chart and use them for config and config reload as well. The sidecar just looks for configmaps with specific annotations.

That said I would not mind if it was possible to provide a config map with init script, but it should be done in a way which is compatible with the existing mechanism.

**Comment by jl431** [comment]
I feel the configmap logic could be provided by the person using the chart, perhaps via a parent chart using stable/jenkins as a subchart. This way the logic being put into the config map will be the responsibility of the user. The stable/jenkins chart only attaches the configmap if the value is provided by the user within the jenkins-master-deployment.yaml.

```
# parentChart/values.yaml
master:
    initScriptCM: my-config-map
```

```
# parentChart/templates/my-config-map.yaml
...
kind: ConfigMap
metadata:
  name: my-config-map
data:
  script1.groovy: print 'Preconfigure admins'
  script2.groovy: print 'Preconfigure more stuff'
```
Does this sound reasonable?

Regarding the tpl idea, I'm happy to use it but I don't think I understand how it applies in our scenario.
The JCasC plugin looks very useful but I'm unable to force our Jenkins users to maintain their configuration as code after the initial deployment. This means that when the Jenkins container restarts, the JCasC is reapplied which isn't what the users always want.
E.g.
JCasC deployment with user1 added as an admin
user1 adds user2 as an admin via the UI
The container restarts / moves pod
JCasC is reapplied
User 2 notices they have lost admin privileges when they next attempt login

I'll investigate how backwards compatibility can be maintained.

**Comment by torstenwalter** [comment]
> I feel the configmap logic could be provided by the person using the chart, perhaps via a parent chart using stable/jenkins as a subchart. This way the logic being put into the config map will be the responsibility of the user. The stable/jenkins chart only attaches the configmap within the jenkins-master-deployment.yaml if the value (jenkins.master.initScriptCM) is provided by the user.
> 
> ```
> # parentChart/values.yaml
> jenkins:
>   master:
>     initScriptCM: my-config-map
> ```
> 
> ```
> # parentChart/templates/my-config-map.yaml
> ...
> kind: ConfigMap
> metadata:
>   name: my-config-map
> data:
>   script1.groovy: print 'Preconfigure admins'
>   script2.groovy: print 'Preconfigure more stuff'
> ```
> 
> Does this sound reasonable?

Yes it does. 

> Regarding the tpl idea, I'm happy to use it but I don't think I understand how it applies in our scenario.

You can reference other values from within your values.yaml. Here is an example: https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml#L257

> I'll investigate how backwards compatibility can be maintained.

Great! Looking forward to see a PR.

**Comment by jl431** [comment]
So I've had a further play with the role and noticed the jenkins.persistence value. I'm not sure how I managed to overlook it on my first attempt but it looks like it has what I needed.

```
  persistence:
    volumes:
      - name: init-groovy-volume
        configMap:
          name: init-scripts
    mounts:
      - mountPath: /var/jenkins_home/init.groovy.d
        name: init-groovy-volume
```

I've verified this as working and am happy to close.
Hopefully this will serve as useful for anyone else looking to do similar in the future.
