### ISSUE TITLE
[stable/prometheus-operator] Default dashboards are not created using `helm template`

### ISSUE THREAD

**Issue by afirth** [helm/charts#16943]
**Describe the bug**
None of the default dashboards are created

**Version of Helm and Kubernetes**:
Helm 2.14.0, 2.14.3
K8S 1.13.8, 1.14.2

**Which chart**:
stable/prometheus-operator

**What happened**:
No dashboards are created

**What you expected to happen**:
[This configmap](https://github.com/helm/charts/blob/ccfb3d0417487adcb327fb1e6ddf4073dd0a2e49/stable/prometheus-operator/templates/grafana/configmap-dashboards.yaml#L2) should be filled with all the files in [charts/stable/prometheus-operator/templates/grafana/dashboards/](https://github.com/helm/charts/tree/ccfb3d0417487adcb327fb1e6ddf4073dd0a2e49/stable/prometheus-operator/templates/grafana/dashboards)

**How to reproduce it** (as minimally and precisely as possible):
```
helm fetch stable/prometheus-operator --untardir ./charts --untar
helm template charts/prometheus-operator -x templates/grafana/configmap-dashboards.yaml
```
or
```
helm install --name=test stable/prometheus-operator
kubectl get cm | grep grafana
```

**Anything else we need to know**:
[the configmap](https://github.com/helm/charts/blob/ccfb3d0417487adcb327fb1e6ddf4073dd0a2e49/stable/prometheus-operator/templates/grafana/configmap-dashboards.yaml#L2) is looking for json files, while all of the templates are yaml - However changing json -> yaml doesn't fix this at all. I don't really understand how this ever worked, according to [the docs](https://github.com/helm/helm/blob/master/docs/chart_template_guide/accessing_files.md#accessing-files-inside-templates) 

> Some files cannot be accessed through the .Files object, usually for security reasons.
Files in templates/ cannot be accessed.

These values are on by default
`grep dashboard charts/prometheus-operator/values.yaml  -C3 | grep -i enabled`
```
  enabled: true
  defaultDashboardsEnabled: true
      enabled: true
      enabled: true
      defaultDatasourceEnabled: true
```

Many moons ago (~8) there was a reference to dashboards living at `./dashboards` - e.g. 
`git rev-list --all | xargs git grep prometheus-operator/dashboards | grep .` - did they get lost when the chart moved? I'm not really sure how to go about fixing this. Am I missing something obvious?

**Comment by afirth** [comment]
FYI I found out through slack that `helm template --kube-version` can apparently be used for setting this `Capability`. It does not set other things though, see https://github.com/helm/helm/issues/3589. Meanwhile, you can now set the chart value `kubeTargetVersionOverride` to force generation for a target version (#16994)

**Comment by dhristov1** [comment]
Hello, How did u fix the issue?

**Comment by afirth** [comment]
Set `kubeTargetVersionOverride` in your helm values

E.g. `kubeTargetVersionOverride: 1.14.6`
