### ISSUE TITLE
[stable/postgresql] Add a metrics exporter for postgresql slaves

### ISSUE THREAD

**Issue by rjemanuele** [helm/charts#16948]
We use the postgres slaves as read-only databases to reduce the load on the masters.  We'd like to be able monitor the slaves as we do the masters but the metrics exporter is not included in the statefulset for slaves. 

**Is your feature request related to a problem? Please describe.**
Monitoring of postgresql slaves is not available through a metrics exporter.

**Describe the solution you'd like**
Include a metrics exporter container in the slave statefulset for exposing slave stats.

**Describe alternatives you've considered**
None as this makes the most sense to me.

**Additional context**
N/A

**Comment by miguelaeh** [comment]
Hi @rjemanuele ,
Do you know if that metric could be obtained from the master? If not, we can evaluate and implement the metrics to the slaves too.
