### ISSUE TITLE
[stable/rabbitmq] ability to add user after installing

### ISSUE THREAD

**Issue by Leekao** [helm/charts#16956]
The chart allows you to set rabbitmq.username and rabbitmq.password, but after the installation you cannot use these to connect to the rabbit using PLAIN authentication, if I exec into the pod and add these permissions with rabbitctrl I can solve it but fixing this with values passed to the sub-chart is a much better way if possible.

**Comment by marcosbc** [comment]
Hi @Leekao, just wanted to let you know we are looking into this and will get back to you with any update on the issue.

**Comment by jlmurphysa** [comment]
Possibly related, but here is some strange behaviour I'm encountering:
1) setting rabbitmq.username doesn't seem to override the default 'user', and
2) setting rabbitmq.existingPasswordSecret does not seem to have an effect i.e. RABBITMQ_PASSWORD is <set to the key 'rabbitmq-password' in secret '{{ .Release }}-rabbitmq'>

**Comment by marcosbc** [comment]
Hi, 

>The chart allows you to set rabbitmq.username and rabbitmq.password, but after the installation you cannot use these to connect to the rabbit using PLAIN authentication, if I exec into the pod and add these permissions with rabbitctrl I can solve it but fixing this with values passed to the sub-chart is a much better way if possible.

I'm not sure I'm understanding your issue correctly. By default the container already sets proper permissions:

```
$ rabbitmqctl list_permissions
Listing permissions for vhost "/" ...
user	configure	write	read
myuser	.*	.*	.*
```

Could you let us know which command you are executing to fix the issue you're finding? Also, could you give more details on how you are configuring the PLAIN connections to your RabbitMQ instance?

>1. setting rabbitmq.username doesn't seem to override the default 'user', and

We're not sure what you mean by this. If we launch a clean Helm chart we can see it is properly created:

```
$ rabbitmqctl list_users
Listing users ...
user	tags
myuser	[administrator]
```

Please let us know if we're missing anything.

>2. setting rabbitmq.existingPasswordSecret does not seem to have an effect i.e. RABBITMQ_PASSWORD is <set to the key 'rabbitmq-password' in secret '{{ .Release }}-rabbitmq'> (it does this with the existingErlangSecret too)

Keep in mind that it looks for the key `rabbitmq-password` inside the secret definition. For instance, check the example below: 

`name-of-existing-secret.yaml`
```
# Source: rabbitmq/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: name-of-existing-secret
  labels:
    app: rabbitmq
    chart: rabbitmq-6.7.4
    release: "mbrabbit"
    heritage: "Tiller"
type: Opaque
data:
  rabbitmq-password: "UlRqM29zOTkwZWtqanMxNAo="
```

It is important you make sure there are no PVC, which could make the old password being used. Also, keep in mind the password listed there is in base64 format.

Note that we could get it to work properly:

```
$ curl --user myuser:RTj3os990ekjjs14 http://localhost:15672/api/vhosts
[{"cluster_state":{"rabbit@mbrabbit-rabbitmq-0.mbrabbit-rabbitmq-headless.default.svc.cluster.local":"running"},"name":"/","tracing":false}]
```

______

In these examples, we have been using the `values.yaml` file below:

```
diff --git a/stable/rabbitmq/values.yaml b/stable/rabbitmq/values.yaml
index 2a839906c..c19cd5b60 100644
--- a/stable/rabbitmq/values.yaml
+++ b/stable/rabbitmq/values.yaml
@@ -66,13 +66,13 @@ rabbitmq:
   ## RabbitMQ application username
   ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
   ##
-  username: user
+  username: myuser

   ## RabbitMQ application password
   ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
   ##
   # password:
-  # existingPasswordSecret: name-of-existing-secret
+  existingPasswordSecret: name-of-existing-secret

   ## Erlang cookie to determine whether different nodes are allowed to communicate with each other
   ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
```

**Comment by flyte** [comment]
I have this issue as well. The healthchecks don't pass either, so the pods never become ready and are eventually killed and restarted.

It works on the first installation, but deleting the installation and recreating it with a different password does not work. It does work if you recreate it using the original password though.

```
helm install --name rabbitmq-test --namespace mynamespace --set rabbitmq.username=myuser,rabbitmq.password=abcdef stable/rabbitmq
# Works
helm delete --purge rabbitmq-test
helm install --name rabbitmq-test --namespace mynamespace --set rabbitmq.username=myuser,rabbitmq.password=ghijkl stable/rabbitmq
# Does not work
helm delete --purge rabbitmq-test
helm install --name rabbitmq-test --namespace mynamespace --set rabbitmq.username=myuser,rabbitmq.password=abcdef stable/rabbitmq
# Works again
```

**Comment by flyte** [comment]
Solved my issue by deleting the "PVC" Persistent Volumes. I had expected everything created by helm to be removed on delete.
