### ISSUE TITLE
[stable/redis-ha] haproxy exporter

### ISSUE THREAD

**Issue by man4red** [helm/charts#16978]
**Describe the bug**
haproxy_exporter doesn't work as expected

**Version of Helm and Kubernetes**:

**Which chart**:
stable/redis-ha

**What happened**:
error @ kubectl logs -n development dunking-starfish-redis-ha-haproxy-7758ff7b5d-p2ck7 prometheus-exporter

```time="2019-09-09T09:50:55Z" level=error msg="Can't scrape HAProxy: dial unix /run/haproxy/admin.sock: connect: no such file or directory" source="haproxy_exporter.go:305"```

curl -s HAPROXY IP ADDRESS:9101/metrics | grep haproxy_up.[01]
```haproxy_up 0```

**What you expected to happen**:
prometheus-exporter does work

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/redis-ha \
--set haproxy.enabled=true \
--set haproxy.exporter.enabled=true

**Anything else we need to know**:
The issue can be fixed by adding 
```
    global
      stats socket /run/haproxy/admin.sock mode 660 level admin
```
to the configmap (haproxy.cfg)

**Comment by DandyDeveloper** [comment]
I will label this as a duplicate of https://github.com/helm/charts/issues/16862 @man4red 

I think we're better off moving to the built in metric exporter.
