### ISSUE TITLE
[stable/neo4j] Wrong indent in deployment and statefulset

### ISSUE THREAD

**Issue by ppcololo** [helm/charts#16986]
**Describe the bug**
Wrong indent in deployment and statefulset for nodeSelector/affinity/tolerations

**Version of Helm and Kubernetes**:
any

**Which chart**:
stable/neo4j

**What happened**:
some variables doesn't applied because wrong indent

**What you expected to happen**:
nodeSelector/affinity/tolerations must have indent = 8

**How to reproduce it** (as minimally and precisely as possible):
deploy chart with any param: nodeSelector/affinity/tolerations

**Anything else we need to know**:
no

**Comment by ppcololo** [comment]
@voslartomas please fix it

**Comment by maorfr** [comment]
hey @ppcololo,
thanks for creating this issue.

you seem to already have a clear understanding of how to fix this issue, so please submit a PR!
here's how to get started: https://github.com/helm/charts/blob/master/CONTRIBUTING.md

**Comment by ppcololo** [comment]
https://github.com/helm/charts/pull/17137

**Comment by ppcololo** [comment]
I haven't expected this (approve PR) can be so long...

**Comment by ppcololo** [comment]
merged
