### ISSUE TITLE
[stable/opa] Not detecting any configmap

### ISSUE THREAD

**Issue by Docteur-RS** [helm/charts#16997]
**Describe the bug**
When installing OPA using the default helm chart with no arguments it seems that no config map is being detected.  
This results in no policy being enforced...

**Version of Helm and Kubernetes**:
helm 2.13.1
kubernetes 1.14.3

**What happened**:  
*Installing the chart*  
`helm install --name opa stable/opa --set authz.enabled=false --namespace opa`   

*cat of the rego test file*  
```rego
package kubernetes.admission

operations = {"CREATE", "UPDATE"}

deny[msg] {
  input.request.kind.kind == "Pod"
  operations[input.request.operation]
  image := input.request.object.spec.containers[_].image
  contains(image, ":latest")
  msg := "Latest tags are forbidden"
}

deny[msg] {
  input.request.kind.kind == "Pod"
  operations[input.request.operation]
  image := input.request.object.spec.containers[_].image
  not contains(image, ":")
  msg := "Untagged images are forbidden"
}
```
*Creating configmap*  
`kubectl create configmap nolatest --from-file ./no_latest.rego -n opa`  

*checking...*  
` kubectl describe cm nolatest -n opa`  

**No annotations have been written and the policy is not enforced**  

**What you expected to happen**:

Expecting to have this annotation on the config map : `openpolicyagent.org/policy=rego` and the policy to be enforced.

What am I missing ?
thx

**Comment by rkemper** [comment]
There is a section in the values file that by default disables configmapPolicies.  Have you tried the following setting: ```enabled: true```

```
  configmapPolicies:
# NOTE IF you use these, remember to update the RBAC rules below to allow
#      permissions to get, list, watch, patch and update configmaps
    enabled: true
    namespaces: [opa, kube-federation-scheduling-policy]
    requireLabel: true
```

**Comment by Docteur-RS** [comment]
Ok.... I hate myself. @rkemper **THANKS !**
There could be a warning about this in the readme for newbies like me starting with OPA !

---

Next is written that I should update the RBAC section to allow configmaps with the following verbs : [get, list, watch, patch and update].  

Unfortunatly I'm having troubles to add those verbs in the appropriate section of the yaml:
```
    cluster: []
#     - [group/]version/resource
    namespace: []
#     - [group/]version/resource
    path: kubernetes
```

*Where do the given verbs and the configmap kind fit in there ?*

Thx

**Comment by Docteur-RS** [comment]
Found out that there is an another rbac section which I updated as follow:

```yaml
rbac:
  # If true, create & use RBAC resources
  #
  create: true
  rules:
    cluster:
     - apiGroups:
         - ""
       resources:
         - configmaps
       verbs:
         - get
         - list
         - watch
         - patch
         - update
```

So now that I've set the RABC and `configmapPolicies` to true I expect it to be working... Still isn't....  
No annotations appears on my configmaps.  
Really anoying.

**Comment by murarisumit** [comment]
@Docteur-RS were you able to get it working ?

**Comment by DarthVader2409** [comment]
Having the same issue. Did anybody get this to work @Docteur-RS @murarisumit

**Comment by Docteur-RS** [comment]
@murarisumit @DarthVader2409 Nope... This ended with a complete rage quit...

**Comment by DarthVader2409** [comment]
@Docteur-RS I figured out that in configmapPolicies section you have set 
`requireLabel: true`

so you would have to label 
`kubectl label configmap <configmap_name> openpolicyagent.org/policy=rego`

and annotations will apear on configmap

**Comment by Docteur-RS** [comment]
@DarthVader2409 I already tried the `requireLabel`. Now I don't remember if I had set the labels correctly at the time...  
Unfortunatly I don't have the time to check it out. @murarisumit Did it worked for your ?
