### ISSUE TITLE
set up chart contribution

### ISSUE THREAD

**Issue by michelleN** [helm/charts#17]
- [x] remove all current charts (because the format is different from the helm/dm era)
- [x] update readme with contribution process and current links
- [x] set up CI so that a PR is green when charts are linted with no issues. This includes cleaning up `_tests/`
- [ ] on master green build, update google cloud storage bucket for charts with latest using helm sync-repo script

**Comment by baldwinSPC** [comment]
@michelleN What's the status of this repo? Curious as there are zero curated charts and I'm wondering if I'm looking in the right spot :)

**Comment by michelleN** [comment]
Hey @baldwinSPC yes you are in the right place. We are working out the release process. You should see some issues pop up in this queue pretty soon.

**Comment by prydonius** [comment]
Hey @baldwinSPC, we're still in the process of figuring out the release process for curated charts, so we've cleared it out until we have the repository structure defined, and CI running. In the meantime, here are a couple of resources:
- Deis Workflow chart from @kmala https://github.com/kmala/charts/tree/helm/deis-workflow
- Handful of apps/services charts we're testing at Bitnami https://github.com/bitnami/charts/tree/helm-2.0
- Awesome prometheus and grafana charts from @tmc https://github.com/tmc/charts

**Comment by prydonius** [comment]
superseded by #25
