### ISSUE TITLE
Audit of Stable Charts

### ISSUE THREAD

**Issue by chrislovecnm** [helm/charts#170]
So many of the stable charts need some TLC, based on our https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements

For instance, MariaDB does not have resource request and limits :(

**Comment by lachie83** [comment]
These requirements can and will change over time and represent the best-practices at the time of merge. The hope is that these tech requirements will become more stable over time.  I would like to get your thoughts on how we might be able to tackle this.

**Comment by pierreozoux** [comment]
Once we fixed #171, this would be easier!

**Comment by seanknox** [comment]
We've instituted a number of process fixes since this was opened, including fleshing out and enforcing core technical requirements of new charts. Closing.
