### ISSUE TITLE
[stable/redis-ha] haproxy not deploying

### ISSUE THREAD

**Issue by adsail** [helm/charts#17000]
**Describe the bug**

When I attempt to deploy redis-ha with the haproxy enabled, the haproxy does not deploy as I would expect.

**Version of Helm and Kubernetes**:

`helm version --short`
Client: v2.13.1+g618447c
Server: v2.13.1+g618447c

`kubectl version --short`
Client Version: v1.14.3
Server Version: v1.13.5

**Which chart**:

stable/redis-ha

**What happened**:

`helm upgrade -i redis-ha -f ./values.yaml stable/redis-ha` with `haproxy: enabled: true` did not deploy haproxy.

**What you expected to happen**:

Expected haproxy service to deploy with rest of redis-ha artifacts.

**How to reproduce it** (as minimally and precisely as possible):

Modify `values.yaml` to include `haproxy: enabled: true`, deploy via `helm upgrade`.

**Anything else we need to know**:

**Comment by DandyDeveloper** [comment]
@andrewsail 

Was the upgrade successful? 

Do you have any deployments or services related to HAproxy deployed?

Are you certain you've got your dependencies updated and pulled down the latest version of the chart?

**Comment by andrewsail** [comment]
`helm repo update` was required.
