### ISSUE TITLE
[stable/prometheus] unable to add storage.tsdb.wal-compression flag

### ISSUE THREAD

**Issue by eMCeee89** [helm/charts#17038]
Hello,
There is no way to add --storage.tsdb.wal-compression argument with server.extraArgs for stable/prometheus chart.
server.extraArgs expects key:value array but prometheus server expects --storage.tsdb.no-lockfile without any value.

Exactly as it was reported [here](https://github.com/helm/charts/issues/11269) just a different flag.

**Comment by Place1** [comment]
yeah i've got this problem as well.

**Comment by Place1** [comment]
can we reopen?
