### ISSUE TITLE
[stable/openvpn] Please remove `nopass` from `/etc/openvpn/setup/newClientCert.sh` 

### ISSUE THREAD

**Issue by ChikkannaSuhas** [helm/charts#17045]
**Is your feature request related to a problem? Please describe.**
As per best security standards, its even better to have a password with .ovpn client config file.
With all due respect, I think it might be necessary to remove `nopass` from `newClientCert.sh` to make client certificate generated to be more secure by default and provide an option explicitly to the end users to use `nopass` in case they don't want the password for their client certificates.

**Describe the solution you'd like**
Please remove `nopass` from `newClientCert.sh`

**Describe alternatives you've considered**
Maintaining a private helm chart with the above mentioned change.

**Additional context**
As per best security standards, its even better to have a password with .ovpn client config file.

**Comment by jasongwartz** [comment]
I think, at this point, a lot of installations probably depend on this. I’d be happy to make it an option (defaulting to the existing behavior) if that would help you not have to fork the chart. Feel free to open a PR 🙂

**Comment by grapevineai** [comment]
@jasongwartz Could you please recommend a way to add a password to the config file? I can't find any documentation about this...

**Comment by jasongwartz** [comment]
@grapevineai It's not something I've specifically needed to do with my own installations of the stable/openvpn chart. As mentioned above, I'd be happy with any backwards-compatible changes that introduce the ability to add a client password.

**Comment by grapevineai** [comment]
@jasongwartz According to [this commit](https://github.com/OpenVPN/easy-rsa/commit/c794d5e) and [this discussion](https://github.com/angristan/openvpn-install/issues/389), it is now possible to pass the password without interactive prompt to easy-rsa v3.0.7.

I created the following [docker image](https://hub.docker.com/r/grapevineai/openvpn) which includes the latest easy-rsa package v3.0.7.

Running the new client script like this: `/etc/openvpn/setup/newClientCert.sh "$KEY_NAME" "$SERVICE_IP" "$PASSWORD"` and if the password is empty run it as it currently is would be a backwards-compatible change.

**Comment by grapevineai** [comment]
@jasongwartz Or if you want it to be compatible with the original openvpn image (or simply don't want to expose the password in the shell) you can do:

```
if echo $* | grep -e "--protect" -q
  then
    ./easyrsa build-client-full $1
  else
    ./easyrsa build-client-full $1 nopass
fi
```

And add the `--protect` flag in the doc

**Comment by grapevineai** [comment]
@jasongwartz Any comment about this? I'd love to have it merged...
