### ISSUE TITLE
[stable/nginx-ingress] Pods not restarting when ConfigMap changed on RollingUpdate updateStrategy

### ISSUE THREAD

**Issue by islhil** [helm/charts#17041]
**Describe the bug**
Controller pods do not restart when the relevant configmap is changed and the updateStrategy is set up RollingUpdate.

**Version of Helm and Kubernetes**:
Helm client - v2.12.2
Helm Server - v2.14.1
Kubernetes client - v1.13.2
Kubernetes server - v1.13.10

**Which chart**:
nginx-ingress v1.8.2

**What happened**:
I changed `controller.config.enable-modsecurity` from true to false, and deployed the change. The configmap was updated, but the pods didn't restart.

**What you expected to happen**:
As `controller-configmap.yaml` had changed, I would expect the `controller-daemonset.yaml` that references it to recognise this and restart the pods

**How to reproduce it** (as minimally and precisely as possible):
Deploy with controller.config.enable-modsecurity set to true
Redeploy with controller.config.enable-modsecurity set to false

**Anything else we need to know**:

**Comment by taharah** [comment]
The pods do not need to restart. The nginx controller automatically watches for changes to the ConfigMap and reloads the service.
