### ISSUE TITLE
[stable/sumologic-fluentd] add support for DaemonSet annotations

### ISSUE THREAD

**Issue by Constantin07** [helm/charts#17054]
**Is your feature request related to a problem? Please describe.**
https://github.com/SumoLogic/fluentd-kubernetes-sumologic/issues/139

**Describe the solution you'd like**
Add support for DaemonSet annotations.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Constantin07** [comment]
Is there any maintainer/reviewer ?

**Comment by zanhsieh** [comment]
@Constantin07 
If you already had a PR passed on  stable/sumologic-fluentd, please speak out to be the chart OWNER. Thank you. 
See:
https://github.com/helm/charts/issues/13869
