### ISSUE TITLE
[stable/external-dns] Update README.md Add description for `extraArgs.aws-assume-role`

### ISSUE THREAD

**Issue by s2504s** [helm/charts#17069]
**Is your feature request related to a problem? Please describe.**
If we set the option `aws.assumeRoleArn` like:
```
...
aws:
  assumeRoleArn: "arn:aws:iam::1111111111:role/external-dns"
...
```
it will require that AWS credentials (secretKey and accessKey) should be set too, else we will get the error:
```
time="2019-09-11T12:40:37Z" level=fatal msg="SharedConfigAssumeRoleError: failed to load assume role for arn:aws:iam::1111111111:role/external-dns, source profile has no shared credentials"
```
but my suggestion bellow works as expected!

**Describe the solution you'd like**
Could you please add this to the `README`?
`values.yaml`
```
## Extra Arguments to passed to external-dns
extraArgs:
  aws-assume-role: "arn:aws:iam::11111111111:role/external-dns"
```
**Additional context**

**Comment by juan131** [comment]
Hi @s2504s 

There's no `AWS_ACCOUNT_ID` parameter in the **values.yaml** at this very moment. I'm not sure what you mean when you suggest using:

```
  aws-assume-role: "arn:aws:iam::{{ Values.AWS_ACCOUNT_ID }}:role/external-dns"
```

Could you please add more details about this specific parameter?

**Comment by s2504s** [comment]
Hi @juan132

**Comment by s2504s** [comment]
Hi @juan131
Yes, you are right, there should be this string:
```
extraArgs:
  aws-assume-role: "arn:aws:iam::11111111111:role/external-dns"
```

I have also updated issue description

**Comment by juan131** [comment]
Hi @s2504s 

Isn't this the same argument that's is currently being used when the `aws.assumeRoleArn` parameter is set? Check the link below:

https://github.com/helm/charts/blob/master/stable/external-dns/templates/deployment.yaml#L99
