### ISSUE TITLE
what's the difference between rabbitmq and rabbitmq-ha charts?

### ISSUE THREAD

**Issue by duyanghao** [helm/charts#17064]
@matejhasul @miguelaeh  I am confused about the difference between [rabbitmq](https://github.com/helm/charts/tree/master/stable/rabbitmq) and [rabbitmq-ha](https://github.com/helm/charts/tree/master/stable/rabbitmq-ha) charts.
Does it means that `rabbitmq` chart does not support high-availability?

**Comment by matejhasul** [comment]
I'm not much familiar with rabbitmq chart but at first glance there is support for HA. This chart is based on bitnami images unlike rabbitmq-ha. There are many differences for sure. I've seen PR or issue for merging these charts together but cannot find it right now :(

**Comment by dohnto** [comment]
The question is still not answered. I, as a starting user am very confused, and it is worth documenting the reason for having 2 different charts doing the same thing.

**Comment by nikoskip** [comment]
Can any one give us a straightforward answer about this?

**Comment by sshishov** [comment]
Very confusing. Trying to understand differences and prons/cons myself now...

**Comment by rajivml** [comment]
even I am trying to understand the difference between these 2 charts and to add to the confusion there is one more chart on the bitnami github repo and am confused on which of these 3 has to be used to setup both HA and non HA environments
https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/
