### ISSUE TITLE
[stable/minio] allow to enable compat mode in settings

### ISSUE THREAD

**Issue by thewilli** [helm/charts#17075]
**Is your feature request related to a problem? Please describe.**

I am using Minio to (amongst other use-cases) store data of the [GitLab Helm Chart](https://docs.gitlab.com/charts/) components. GitLab - as of now - [relies](https://gitlab.com/gitlab-org/gitlab-workhorse/merge_requests/398) on the `--compat` option of Minio, but I can neither directly enable that option in the Chart, nor can I inject additional CLI arguments.

Because of the missing configuration options, I have to manually patch the Deployment / Daemonset of the Helm Chart, which prevents me from doing simple updates.

**Describe the solution you'd like**

Extend the Minio Chart to either enable the compat mode as a setting or to inject additional CLI arguments for the [standalone](https://github.com/helm/charts/blob/a62d32a/stable/minio/templates/deployment.yaml#L63-L89) and [distributed](https://github.com/helm/charts/blob/a62d32a/stable/minio/templates/statefulset.yaml#L63-L75) setup.

**Comment by echel0n** [comment]
This does not work for enabling compat mode

**Comment by solomson** [comment]
echel0n speaks truth, at least for Azure blob storage through AKS. using --compat under extraArgs seems to have uploaded some files which are corrupted in my case, while changing the deployment.yaml file works.

**Comment by thewilli** [comment]
It did work, but the Minio Dockerfile was changed and the image now ignores additional arguments passed this way. I’ll have a look at it after the holidays. You can use v2.5.15 of the Chart and possibly even later v2.x in the meantime or add the parameter by hand just as you already did.

**Comment by jaygridley** [comment]
@thewilli Any updates on this?

**Comment by thewilli** [comment]
@jaygridley expect a PR within this week

**Comment by thewilli** [comment]
@jaygridley just had some spare time, please follow #19903

**Comment by echel0n** [comment]
thanks!

**Comment by hutr** [comment]
Thanks for the PR @thewilli . I tested with chart version 5.0.4 and the issue still persist.
Even though the argument exists in the deployment and pod (e.g. kubectl describe), but when exec'ing into the pod one can see that the the argument is missing.    

`$ helm install --set extraArgs="{--compat}" stable/minio
`

```
$ kubectl describe pod minio-6d5bd7789-7cbd2

...
Command:
      /bin/sh
      -ce
      /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /export
      --compat
...
```
```
$ kubectl exec -it minio-6d5bd7789-7cbd2 sh

/ # ps
PID   USER     TIME  COMMAND
    1 root      0:06 minio -S /etc/minio/certs/ server /export

```

I am working on a PR and hopefully it's ready by the end of the day.
