### ISSUE TITLE
[stable/rabbitmq] liveness and readiness probes fail with 401

### ISSUE THREAD

**Issue by jsnider-mtu** [helm/charts#17082]
**Describe the bug**

The password created for the user does not successfully log the user in during liveness and readiness probes.

**Version of Helm and Kubernetes**:
$ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-27T14:42:18Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/rabbitmq

**What happened**:
Simple default install results in containers not being ready due to failing the readiness and liveness probes.

**What you expected to happen**:
Containers should become ready.

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/rabbitmq --name rabbitmq --namespace tools

**Anything else we need to know**:
N/A

**Comment by alemorcuq** [comment]
I'm glad this is solved, @jsnider-mtu. If I had to guess, I'd say you already have some persistent volume claim in your `tools` namespace that is getting attached to the pod. Thus, the `rabbitmq` password is already set in there and doesn't match the one that is getting generated by the chart.

Regards,
Alejandro
