### ISSUE TITLE
Linter for enforcing our tech requirements

### ISSUE THREAD

**Issue by chrislovecnm** [helm/charts#171]
I wish I had time to do this, but as we grow we need to have a linter that will enforce https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements

There are multiple things that folks are missing consistently.  A linter would be AWESOME.  Also this project cannot scale without one.

**Comment by lachie83** [comment]
Good suggestion. 

Some other suggestions include a standard base chart that implements current best practices that can be copied or having helm create lay down some commented best-practices? Thoughts?

**Comment by lachie83** [comment]
cc/ @technosophos Have you had any thoughts on this?

**Comment by prydonius** [comment]
cc/ @migmartri

**Comment by chrislovecnm** [comment]
@lachie83 suggestion: improve the helm linter to have a -v option.  Verbose linting recommends best practices.  Thoughts?

**Comment by lachie83** [comment]
Perfect. Sounds almost like what's been suggested in #124 . They've raised issue https://github.com/kubernetes/helm/issues/1501 on the helm side.

**Comment by fhemberger** [comment]
@chrislovecnm Can this issue be closed? `helm lint` is in place and `helm create` should take care of the best practices.

**Comment by chrislovecnm** [comment]
Closing
