### ISSUE TITLE
[stable/postgresql] Replication is broken at #16961

### ISSUE THREAD

**Issue by alexluft** [helm/charts#17111]
**Describe the bug**
Replication is broken with #16961.

**Version of Helm and Kubernetes**:
Helm: v2.14.2
Kubernetes: v1.15.1

**Which chart**:
stable/postgresql v6.3.5

**What happened**:
```diff
-  tag: 11.5.0-debian-9-r26
+  tag: 11.5.0-debian-9-r34
```
makes 
```sql 
CREATE ROLE ...
```
stuck when synchronousCommit: on for a very long time.
When Ctrl+C:
```
WARNING:  canceling wait for synchronous replication due to user request
DETAIL:  The transaction has already committed locally, but might not have been replicated to the standby.
```

**How to reproduce it** (as minimally and precisely as possible):
```diff
-  tag: 11.5.0-debian-9-r34
+  tag: 11.5.0-debian-9-r26
```
Makes it work. Updating to r34 breaks it again.

**Comment by juan131** [comment]
Hi @derverzweifler 

Could you share the **values.yaml** or parameters you're using to deploy the chart?

**Comment by smithb1994** [comment]
Similar issue on our end.  
Changing to r26 fixed it for us too.

**Comment by inhabitech** [comment]
Don't know if this will help, but logs from slaves show

could not connect to the primary server: missing "=" after "subscript" in connection info string

**Comment by muffe** [comment]
We have the same problem, but using `11.5.0-debian-9-r26` still doesn't fix the error for us.

I've used the following command

```
helm upgrade --install --wait postgresql11 stable/postgresql --set replication.enabled=true,replication.user=repl_user,replication.password=repl_password,replication.slaveReplicas=2,replication.synchronousCommit=on,replication.numSynchronousReplicas=1,replication.applicationName=application,image.tag=11.5.0-debian-9-r26
```

**Comment by inhabitech** [comment]
Using 11.5.0-debian-9-r26 didn't work for us either.

>

**Comment by bradsheppard** [comment]
Having the same issue. `11.5.0-debian-9-r26` resolved it for me.

**Comment by juan131** [comment]
Hi @bradsheppard 

We fixed this issue in the revisions below:

- 11.5.0-r59
- 10.10.0-r60
- 9.6.15-r60

We also updated the chart (see https://github.com/helm/charts/pull/17692). Could you give it a try?

**Comment by derverzweifler** [comment]
Thanks! 11.5.0-r60 works fine!

**Comment by walter-csharp** [comment]
> Thanks! 11.5.0-r60 works fine!

I have deployed with this version in openshift but i encountered the same issue
^CCancel request sent
WARNING:  canceling wait for synchronous replication due to user request
DETAIL:  The transaction has already committed locally, but might not have been replicated to the standby.
INSERT 0 1
