### ISSUE TITLE
Add @nckturner as Trusted Collaborator

### ISSUE THREAD

**Issue by nckturner** [helm/charts#17126]
I work at AWS as a maintainer for the following projects, and would like to be a maintainer for their respective charts:

* stable/aws-pod-identity-webhook https://github.com/helm/charts/pull/17099
* stable/aws-iam-authenticator https://github.com/helm/charts/pull/17100

/cc @plumdog @micahhausler

**Comment by plumdog** [comment]
:+1:

**Comment by maorfr** [comment]
done!
