### ISSUE TITLE
[stable/prometheus-operator] serviceMonitorSelector doesn't respect empty list

### ISSUE THREAD

**Issue by baznikin** [helm/charts#17139]
**Describe the bug**
Docs says default value for `prometheus.prometheusSpec.serviceMonitorSelector` is `{}`
However:
`kubectl -n monitoring get Prometheus prometheus-prometheus-oper-prometheus -o yaml`:

```
[...skip...]
   serviceMonitorSelector:
    matchLabels:
      release: prometheus
```

When I try to set it's value to `{}` to catch any ServiceMonitor chart also doesn't respect this value and set `serviceMonitorSelector: matchLabels: release: prometheus`

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

`kubectl get node`
```
NAME                        STATUS   ROLES    AGE    VERSION
cl1f5490vdqdubu1j3md-adab   Ready    <none>   10d    v1.13.10
cl1f5490vdqdubu1j3md-uvaw   Ready    <none>   2d5h   v1.13.10
cl1f5490vdqdubu1j3md-uwem   Ready    <none>   10d    v1.13.10
```

**Which chart**:
`helm list`
```
NAME            REVISION        UPDATED                         STATUS          CHART                           APP VERSION     NAMESPACE
prometheus      8               Sun Sep 15 05:13:18 2019        DEPLOYED        prometheus-operator-6.11.0      0.32.0          monitoring
```

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

`values.yaml`
```
prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
```

**Anything else we need to know**:

**Comment by yantsa** [comment]
I had the same issue. @baznikin did you find a workaround ?

**Comment by baznikin** [comment]
> I had the same issue. @baznikin did you find a workaround ?

I just edit `kubectl -n monitoring edit prometheus prometheus-prometheus-oper-prometheus`:
```
  serviceMonitorSelector: {}
```
`helm upgrade` do not overwrite this edition
