### ISSUE TITLE
mariadb raspberry pi / armv7l support

### ISSUE THREAD

**Issue by jrcichra** [helm/charts#17136]
I would love to see the MariaDB database be supported on arm systems. I tried building all the base images myself, but was unsuccessful. https://github.com/peterhuene/arm-charts has a port of a mariadb chart, but it does not have all the great master/slave features this chart does.

This may be easier now that docker's buildx supports triple architecture builds.

Thanks!

**Comment by miguelaeh** [comment]
Hi @jrcichra ,
At this moment we are not thinking in support arm architecture. I can confirm you that bitnami images don't support arm systems.
