### ISSUE TITLE
[stable/prometheus-operator] adding new grafana plugins with no Internet

### ISSUE THREAD

**Issue by allamand** [helm/charts#17153]
Hi,

I'm trying to automatically deploy my grafana with some plugins and i've been configuring the values.yaml with something similar to :

```
grafana:
  plugins:
  - digrich-bubblechart-panel
  - grafana-clock-panel
```

But this does not works as my grafana does not have internet access to download the plugins.

Is there anotherway I can uses to install the plugins ? like create a ConfigMap with the plugins in it ?

thanks

**Comment by cabrinha** [comment]
Can we re-open this? I just ran into the same issue 😅
