### ISSUE TITLE
stable/nfs-client-provisioner rpc.statd error when deploying

### ISSUE THREAD

**Issue by alexholliz** [helm/charts#17169]
**Describe the bug**
When attempting to deploy the nfs-client-provisioner helm chart on my cluster, I get an error indicating that rpc.statd is not running, and I should run with the nolock option. This same share mounts fine on a generic CentOS 7 vm. I am using nfs.mountOptions to specify the username and password variables. If I try to put in an nfsvers=4.1 argument, I get an error saying the deployment "range cannot iterate over" the nfs.mountOptions values.

For context, the nfs.mountOptions with an nfsvers argument end up looking like:
```
nfs:
       mountOptions: "{nfsvers=4.1,username=foo,password=bar}"
```

**Version of Helm and Kubernetes**:
This cluster is v1.14.6
Helm is v2.10.0-rancher11

**Which chart**:
stable/nfs-client-provisioner

**What happened**:
Mostly stated above, but when trying to deploy the stable nfs-client-provisioner chart for NFS storage PVs in the cluster; I get one of two errors. If I just use the nfs.mountOptions: "{username=blah,password=foo}" as mount Options, then I get a "rpc.statd is not running" error, which indicates I should set nolock as an option.

If I then put nolock, or nfsvers=4.1 (or both) in the same list of arguments, then I get a "range cannot iterate over" and a list of the nfs.mountOptions values.

**What you expected to happen**:
I was hoping I could get either nolock or nfsvers arguments to work. It seems like there must be some kind of syntax problem in the way I am making that argument. 

**How to reproduce it** (as minimally and precisely as possible):
Run the following: 
```
helm install --name nfs-client --set nfs.server=my.nfs.com ==set nfs.path=/kube_nfs_path/dir --set mountOptions="{username=foo,password=bar}
```

**Anything else we need to know**:
It's a rancher managed cluster, but otherwise this thing is fresh. I haven't put any other workloads in this cluster.

**Comment by bbangert** [comment]
I have a similar problem, also using Rancher OS managed cluster. I did get nolock working though with this command:

```
helm install --name=sgbackups --set nfs.server=192.168.2.10 --set nfs.path=/prox-container-backups --set nfs.mountOptions="{nolock,hard}" stable/nfs-client-provisioner
```

In the kubelet logs I see this:
```
{
  "log": "E0929 20:15:13.108062    2209 nestedpendingoperations.go:267] Operation for \"\\\"kubernetes.io/nfs/ce59f601-e2f5-11e9-b02f-062088e73843-pv-sgbackups-nfs-client-provisioner\\\" (\\\"ce59f601-e2f5-11e9-b02f-062088e73843\\\")\" failed. No retries permitted until 2019-09-29 20:15:29.108008661 +0000 UTC m=+448672.777407662 (durationBeforeRetry 16s). Error: \"MountVolume.SetUp failed for volume \\\"pv-sgbackups-nfs-client-provisioner\\\" (UniqueName: \\\"kubernetes.io/nfs/ce59f601-e2f5-11e9-b02f-062088e73843-pv-sgbackups-nfs-client-provisioner\\\") pod \\\"sgbackups-nfs-client-provisioner-7dc5d9dff8-6lvdn\\\" (UID: \\\"ce59f601-e2f5-11e9-b02f-062088e73843\\\") : mount failed: exit status 32\\nMounting command: mount\\nMounting arguments: -t nfs -o hard,nolock 192.168.2.10:/prox-container-backups /opt/rke/var/lib/kubelet/pods/ce59f601-e2f5-11e9-b02f-062088e73843/volumes/kubernetes.io~nfs/pv-sgbackups-nfs-client-provisioner\\nOutput: mount.nfs: mount to NFS server '192.168.2.10:/prox-container-backups' failed: RPC Error: Unable to receive\\n\\n\"\n",
  "stream": "stderr",
  "time": "2019-09-29T20:15:13.108182223Z"
}
```

I can mount this fine everywhere else of course. My googling indicates this is because `portmap` might not be running.
