### ISSUE TITLE
[stable/prometheus] Unable to update server.global.external_labels to dynamic value (pod name)

### ISSUE THREAD

**Issue by vinay2107** [helm/charts#17173]
**Describe the bug**
This is probably me reaching out for some help (not bug).
I am currently running 2 replicas of prometheus servers (having statefulsets enabled) on kubernenets and these servers are federated with an external prometheus running on a VM (considered global). To avoid the global prometheus scrape duplicated metrics, I am adding ```external_label: $POD_NAME``` within the server's ```global``` configuration in values.yml

**Version of Helm and Kubernetes**:
v2.12.2 -Helm
v1.14.2 - k8s

**Which chart**:
prometheus-9.1.0

**What happened**:
    external_labels:
       cluster: dev
       prometheus_replica: $POD_NAME
The configuration does not get updated to the actual pod name as it does in prometheus-operator.

**What you expected to happen**:
    external_labels:
    cluster: dev
    prometheus_replica: prometheus-server-1 
 The configuration on prometheus to be updated.

**How to reproduce it** (as minimally and precisely as possible):
try replacing ```prometheus_replica``` value with 
$POD_NAME, $(POD_NAME), etc..

**Anything else we need to know**:
Not sure how it was implemented in ```stable/prometheus-operator```, but the replica names are automatically updated to the pod names  there.

**Comment by ahmednasir91** [comment]
@vinay2107 were you able to solve it?
