### ISSUE TITLE
[stable/mongodb-replicaset] mongodb-exporter seems wrong.

### ISSUE THREAD

**Issue by fabio-s-franco** [helm/charts#17179]
**Describe the bug**
mongodb-exporter have been giving the following bug after upgrading to mongo 4.0:
panic: runtime error: invalid memory address or nil pointer dereference

Investigating issues I found that we have many different versions of the exporter and the one in the chart does not seem to be the one properly maintained. What we have in the chart is:
ssalaues/mongodb-exporter

Whereas the one properly maintained seem to be from @steven-sheehy :
ssheehy/mongodb-exporter

I am wondering if we should update mongodb-replicaset helm chart to use a maintained version of mongodb-exporter.

**Version of Helm and Kubernetes**:
Helm 2.12.3
Kubernetes 1.13.7-gke.8

**Which chart**:
stable/mongodb-replicaset

**What happened**:
Mongo itself works fine
mongodb-exporter crashes

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Update mongodb version of the chart to 4.0 and install with the following command
helm install ./mongodb-replicaset '--name=mongodb' '--namespace=mongodb' --set auth.adminUser=admin,auth.adminPassword=testpass

**Anything else we need to know**:
This is something experimental I am trying to do. By no means I want to drive this issue to the direction of: "Please use the original version of the chart"

My point being is that we have an unmaintained version of mongodb-exporter in the mongo chart. Is that the way to go?

**Comment by steven-sheehy** [comment]
Once this [PR](https://github.com/helm/charts/pull/16893) is merged it should solve your problem.

**Comment by fabio-510** [comment]
Thanks for pointing it out @steven-sheehy
