### ISSUE TITLE
[stable/sonarqube-2.1.4] read-only file system error for sonar.properties

### ISSUE THREAD

**Issue by jithine** [helm/charts#17199]
**Describe the bug**
Sonarqube 6.7.3 fails to run with `chown` error 

```
chown: changing ownership of '/opt/sonarqube/conf/..2019_09_17_20_40_57.352342021/sonar.properties': Read-only file system
chown: changing ownership of '/opt/sonarqube/conf/..2019_09_17_20_40_57.352342021': Read-only file system
chown: changing ownership of '/opt/sonarqube/conf/sonar.properties': Read-only file system
chown: changing ownership of '/opt/sonarqube/conf/..data': Read-only file system
chown: changing ownership of '/opt/sonarqube/conf': Read-only file system
```

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
sonarqube - https://github.com/helm/charts/tree/master/stable/sonarqube

**What happened**:

Sonarqube application crashes with `Read-only file system` error

`beta-sonarqube-5fb8d56f46-8rwkv        0/1       CrashLoopBackOff   43         3h`

**What you expected to happen**:

Sonarqube should work without crashing

**How to reproduce it** (as minimally and precisely as possible):
Use a sonarqube helm chart to deploy with a custom `sonarProperties` section 

**Anything else we need to know**:
I saw a similar issue reported under https://github.com/helm/charts/issues/11560, but not sure if that is applicable. Since format for `sonarProperties` have changed since.

**Comment by jithin1987** [comment]
Using sonarqube 6.7.6 fixed the issue for me
