### ISSUE TITLE
[stable/traefik] Traefik 2.0

### ISSUE THREAD

**Issue by stevehipwell** [helm/charts#17203]
**Is your feature request related to a problem? Please describe.**
*Traefik* v2 is now GA and it would be good to get it installed via Helm.

**Describe the solution you'd like**
Update `stable/traefik` to v2

**Describe alternatives you've considered**
N/A

**Additional context**
*Traefik* v2 supports TCP connections.

**Comment by dtomcej** [comment]
Hello @stevehipwell,

We have been discussing how we want to handle the `stable/traefik` chart for v2, and we will put a note in the chart readme once we have something working and available!

**Comment by stevehipwell** [comment]
Thank you @dtomcej!

**Comment by stevehipwell** [comment]
@dtomcej have you made any progress on this?

**Comment by Basster** [comment]
Is there already an open WIP:PR where we can help somehow? I'd love to help out, as I already have 2.0 running in local docker-compose dev but k8s still runs on 1.7.

**Comment by Mokto** [comment]
You can check https://github.com/containous/traefik-helm-chart. It seems to be in a really early state though.

**Comment by stevehipwell** [comment]
Is there any more progress on this?

**Comment by Vad1mo** [comment]
@stevehipwell  take a look at https://github.com/containous/traefik-helm-chart, it is usable IMHO. At least for me as it has all the needed options.  You should give it a try.

**Comment by stevehipwell** [comment]
@Vad1mo - Thanks for the link. However I'll be holding off until the chart is at least hosted in a repository. I'd be interested what the plan is for releasing this after the Helm 3 release suggested moving away from this git repo.

**Comment by Vad1mo** [comment]
I guess the chart is going to end up in hub.docker.com where traefik itself is already located. (Thats what I would do without much effort). If you are waiting for helm3 charts, this will take even more time until something going to be available.

**Comment by kachkaev** [comment]
not stale

**Comment by casidiablo** [comment]
By the way, the helm chart at is not even close to be as "professional" https://github.com/containous/traefik-helm-chart as the one you guys have here for 1.7

It has poor documentation and it's not clear to me how to enable acme, etc.

**Comment by casidiablo** [comment]
Go home, stale bot

**Comment by kachkaev** [comment]
not stale

**Comment by ldez** [comment]
More information about the current state of this repo containous/traefik-helm-chart: https://github.com/containous/traefik-helm-chart/issues/92#issuecomment-594664488

To use the helm chart of Traefik v2 https://github.com/containous/traefik-helm-chart/blob/master/README.md#prerequisites

**Comment by prokher** [comment]
There are people who is waiting this to be done. So I don't know whether it is stale or not, but it would be nice to have Traefik 2.0 HELM chart eventually.

**Comment by Vad1mo** [comment]
/close

1. There is an official Helm Chart for Traefik 2 see -> https://github.com/containous/traefik-helm-chart
2. New charts are no longer accepted at [helm/charts](https://github.com/helm/charts) and Traefik 2 would be a new Chart as 1.x is still supported and widly used.

**Comment by DanielHabenicht** [comment]
Can we please add a deprecation Warning or at least a link to the new site? https://github.com/containous/traefik-helm-chart
It really bugs me, because I spend some time figuring out that the settings are not up to date

**Comment by renepardon** [comment]
Is there a migration guide available because it's a different Helm chart and a different version which makes it not that easy. Or is there at least someone who already migrated?

**Comment by Vad1mo** [comment]
There is no automated way of migration AFAIK.

@renepardon, Its fairly easy just deploy traefik 2 next to traefk 1, and start migrating your services one by one. When you are done, you can uninstall traefik 1. Make sure you rename ingress class from traefik to traefik2 to avoid conflicts. If you have certs I would recommend to start using cert-manager and not traefik. Otherwise I don't know how to migrate certs from T1 to T2.
