### ISSUE TITLE
[stable/redis-ha] haproxy deployment sets container hostPort (creates limit of 1 pod per node)

### ISSUE THREAD

**Issue by reubit** [helm/charts#17239]
**Describe the bug**

The optional haproxy deployment sets a `hostPort` for the pods, which means it's only possible to schedule one haproxy pod per node, since the pod needs to exclusively bind to port 6379 on the host.  There's no good reason to set a hostPort, since access should be via the Service endpoint.

This might not be an issue if you have 1 release of redis-ha with a single haproxy replica, but with multiple redis-ha releases with more than 1 haproxy replica, it's starts to become an issue. E.g., 3 redis-ha releases each with 3 haproxy replicas means you need a minimum of 9 nodes on your cluster.

This is obviously an issue, and basically makes this chart unusable in production with the haproxy option enabled.

https://github.com/helm/charts/blob/9968e322f4addbbedcf43b2eeeea3d45123766dd/stable/redis-ha/templates/redis-haproxy-deployment.yaml#L80

```
        ports:
        - name: redis
          containerPort: {{ default "6379" .Values.redis.port }}
          hostPort: 6379
```

**Version of Helm and Kubernetes**:

Not relevant

**Which chart**:

stable/redis-ha

**What happened**:

haproxy pods in Pending state, waiting for the cluster-autoscaler to add more nodes with port 6379 available.

**What you expected to happen**:

Obviously not that... haproxy consumes very little resources, so i wouldn't expect to need a whole new node for a single haproxy pod.

**How to reproduce it** (as minimally and precisely as possible):

enable ha-proxy, and set replicas > number-of-nodes

**Anything else we need to know**:

nope

**Comment by DandyDeveloper** [comment]
@reubit Agreed it should be more flexible. 

I don't agree it makes things unusable in production. It's very rare people will want to expose a specific port over 6379, this is also under the assumption you only have 1 cluster IP/public IP and no ingress which would take the workload away from the public facing side of your cluster.

I definitely get the use case here though, and think it's more appropriate to allow flexibility on the hostPort assignment

**Comment by DandyDeveloper** [comment]
@reubit https://github.com/helm/charts/pull/17269

I've just removed the hostPort entirely, it's just not necessary as all traffic should go through the service.

**Comment by reubit** [comment]
@DandyDeveloper Great, that's perfect, thanks! Appreciate the quick response!

Yes agreed traffic should definitely go through the service, hence no need for the hostPort.

Just to clarify, my comment about it being unusable in production was not about other services requiring port 6379 on the host. I was talking about running many release of this redis-ha chart, where each replica of haproxy across all releases would need to run on separate nodes (since only 1 haproxy pod could run per node due to the hostPort constraint). So if you had a small cluster running only 3 nodes, and wanted to run 10 redis-ha releases each with 2 haproxy replicas, your cluster would need to scale up to 20 nodes just to be able to schedule all haproxy pods (even if your 3 nodes had more than enough resource available).  This would also be a concern when a node dies, as scenarios could arise where the scheduler would have to wait for a new node to come online, rather than simply moving the haproxy pod to another active node, potentially increasing recovery time from seconds to minutes.

Anyway, your PR should definitely resolve these concerns! Thanks again!

**Comment by DandyDeveloper** [comment]
@reubit I had actually misunderstood the original problem. I'm not entirely sure why we're defining hostPorts in the chart deployment. I think I must have just been on autopilot when I built it. 

Since everything is service reliant, makes no sense to have that kind of restriction in place.
