### ISSUE TITLE
[stable/apm-server] apm-server cannot pass healthchecks when configured for HTTPS

### ISSUE THREAD

**Issue by jstaf** [helm/charts#17235]
**Describe the bug**

If apm-server is configured to use HTTPS, the Kubernetes health checks will fail as they are HTTP only in the chart and pods will be stuck in CrashLoopBackOff. The port for the Kubernetes health checks needs to be configurable in the chart.

**Version of Helm and Kubernetes**:

Kubernetes 1.14

```
$ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**Which chart**:

apm-server

**What happened**:

apm-server pods go into CrashLoopBackOff because they fail their liveness/readiness probes (kubernetes performs HTTP healthcheck against HTTPS endpoints)

**What you expected to happen**:

The chart should be able to support apm-server when launched with SSL enabled.

**How to reproduce it** (as minimally and precisely as possible):

Setting up apm-server with SSL enabled will result in pods never passing the Kubernetes readiness/liveness probes:

```
config:
  apm-server:
    host: "0.0.0.0:8200"
    ssl.enabled: true
    ssl.certificate : "/etc/certs/tls.crt"
    ssl.key : "/etc/certs/tls.key"

extraVolumes: 
  - name: elastic-apm-certs
    secret:
      defaultMode: 420
      secretName: elastic-apm-certs
extraVolumeMounts: 
  - name: elastic-apm-certs
    mountPath: /etc/certs
    readOnly: true
```

**Anything else we need to know**:

The following two lines need to be configurable (to allow us to specify `https`): 

https://github.com/helm/charts/blob/master/stable/apm-server/templates/deployment.yaml#L59
https://github.com/helm/charts/blob/master/stable/apm-server/templates/deployment.yaml#L64

**Comment by jstaf** [comment]
Marking as not stale?

**Comment by jstaf** [comment]
Reopen this?

**Comment by Iridescens** [comment]
@jstaf 
> The following two lines need to be configurable (to allow us to specify `https`):
> 
> https://github.com/helm/charts/blob/master/stable/apm-server/templates/deployment.yaml#L59
> https://github.com/helm/charts/blob/master/stable/apm-server/templates/deployment.yaml#L64
 That's not the case here, i got manually edited ds (same for deploy) with replacing HTTP with HTTPS in `scheme` field, which is completely missing in templates for ds and deploy.
`livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: http
    scheme: HTTPS`

Something like 
`livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: http
{{- if eq .Values.config.apm-server.ssl.enabled "true" }}
    scheme: HTTPS
{{- end }}`
