### ISSUE TITLE
[stable/etcd-operator] commandArgs documentation

### ISSUE THREAD

**Issue by sankee168** [helm/charts#17234]
Can someone point me to the documentation regarding `etcdOperator.commandArgs`, `backupOperator.commandArgs` and `restoreOperator.commandArgs`

**Comment by zanhsieh** [comment]
https://github.com/helm/charts/blob/master/stable/etcd-operator/templates/operator-deployment.yaml#L31
https://github.com/helm/charts/blob/master/stable/etcd-operator/templates/backup-operator-deployment.yaml#L30
https://github.com/helm/charts/blob/master/stable/etcd-operator/templates/restore-operator-deployment.yaml#L32
https://github.com/helm/charts/blob/master/stable/etcd-operator/values.yaml#L23
