### ISSUE TITLE
[stable/openvpn] Make readinessProbe configurable

### ISSUE THREAD

**Issue by PosicubeBeege** [helm/charts#17238]
I'd like to see readinessProbe be configurable. 

**Is your feature request related to a problem? Please describe.**
Kubernetes is checking the readiness probe every 5s, generating logs I don't want. I'd like to increase the period to 30s or so.

**Describe the solution you'd like**
Setup readiness probe to be configurable from values.

**Describe alternatives you've considered**
I could just copy the chart and make the value configurable myself... but no. I imagine this change is trivial, and I doubt I'm the only person that wants it.

**Additional context**
Nada

**Comment by dariopedol** [comment]
I would like that too - we have to manually edit the deployment after install to remove the readiness probe as we have security enabled and it would always fail.
