### ISSUE TITLE
[stable/postgresql] failed when recreate worker 

### ISSUE THREAD

**Issue by obeyler** [helm/charts#17249]
**Describe the bug**
I used to have a working Posgresql. I do a recreate of all worker of my K8S  
the Postgresql doesn't restart correctly
The pod of the statefulset has this log

```
postgresql 12:16:04.80 
postgresql 12:16:04.81 INFO  ==> ** Starting PostgreSQL setup **
postgresql 12:16:04.87 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 12:16:04.88 INFO  ==> Loading custom pre-init scripts...
postgresql 12:16:04.88 INFO  ==> Initializing PostgreSQL database...
postgresql 12:16:04.90 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 12:16:04.91 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 12:16:04.92 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 12:16:04.92 INFO  ==> Configuring replication parameters
postgresql 12:16:04.95 INFO  ==> Configuring fsync
postgresql 12:16:04.95 INFO  ==> Loading custom scripts...
postgresql 12:16:04.96 INFO  ==> Enabling remote connections
postgresql 12:16:04.96 INFO  ==> Stopping PostgreSQL...
postgresql 12:16:04.97 INFO  ==> ** PostgreSQL setup finished! **
postgresql 12:16:05.00 INFO  ==> ** Starting PostgreSQL **
2019-09-19 12:16:05.014 GMT [1] FATAL:  data directory "/bitnami/postgresql/data" has invalid permissions
2019-09-19 12:16:05.014 GMT [1] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
``` 

**Version of Helm and Kubernetes**:

helm version --short
Client: v2.14.0+g05811b8
Server: v2.14.0+g05811b8

kubectl version --short
Client Version: v1.14.1
Server Version: v1.14.1

**Which chart**:
I use chart  postgresql-version: 5.3.11
      image:
        registry: docker.io
        repository: bitnami/postgresql
        tag: 11.5.0

**What happened**:
On restart the Postresql failed
May the issue : https://github.com/helm/charts/issues/13651 has occured again

**Comment by obeyler** [comment]
same trouble with image tag 11.4.0

**Comment by miguelaeh** [comment]
Hi @obeyler ,
Could you check if changing `persistence.mountPath` to `/bitnami/postgresql/data` solves the problem?

**Comment by obeyler** [comment]
yes great Thanks
