### ISSUE TITLE
loadbalancer pending

### ISSUE THREAD

**Issue by soheilade** [helm/charts#17243]
Dear All,

I am following the [openvpn ](https://github.com/helm/charts/tree/master/stable/openvpn). After `helm install stable/openvpn` the loadbalancer service stays at pending state. 
`kubectl get pv,pvc` shows that persistence volumes are in pending state. any idea?
Thanks.

**Comment by DandyDeveloper** [comment]
@soheilade It's probably specific to your cluster. You'll need to describe each of the resources and check the reasons why they are not creation.

PV: Is the disk space available?
PVC: If the PV is pending. PVC will be pending too.

LoadBalancer, are you sure you actually have an IP address for the LoadBalancer to bind against?

**Comment by soheilade** [comment]
@DandyDeveloper , thanks for the help, my load balancer has a cluster ip but the external ip is pending. Should I manually create the PV?

**Comment by soheilade** [comment]
fixed by removing `storageClassName: manual` from the pv config.
