### ISSUE TITLE
[stable/prometheus] deprecated APIs removed in k8s 1.16

### ISSUE THREAD

**Issue by oke-py** [helm/charts#17267]
**Describe the bug**
In k8s v1.16 some APIs are deprecated and removed.
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

As a result, installation failed.
```
$ helm3 install --name-template prometheus stable/prometheus
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"]
```

**Version of Helm and Kubernetes**:
```
$ helm3 version
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/prometheus

**What happened**:
Installation failed in k8s 1.16.

**What you expected to happen**:
Prometheus can be successfully installed.

**How to reproduce it** (as minimally and precisely as possible):
- create k8s 1.16 cluster
- install helm3 because helm2 has a problem against k8s 1.16.
- run chart install command above

**Anything else we need to know**:
I'll submit a PR.

**Comment by carlosjgp** [comment]
duplicated https://github.com/helm/charts/issues/17779
