### ISSUE TITLE
[kube-state-metrics] Chart cannot be upgraded

### ISSUE THREAD

**Issue by cknowles** [helm/charts#1726]
When trying to upgrade kube-state-metrics to the latest chart, it won't install due to selector mismatch.

**Version of Helm and Kubernetes**:

k8s 1.7.3, helm 2.5.1

**Which chart**:

kube-state-metrics

**What happened**:

Failed to upgrade from previous chart version

**What you expected to happen**:

Chart upgrade should be available using `helm upgrade` command

**How to reproduce it** (as minimally and precisely as possible):

1. Install older version of the chart, I had 68a232a79413203b7b507ae9a5843b24d18d8146 installed
1. Run a `helm upgrade` against the latest stable

```
helm upgrade kube-state-metrics stable/kube-state-metrics --install \
  --wait --namespace=kube-system --values=kube-state-metrics-values.yml
```

```
UPGRADE FAILED: Deployment.apps "kube-state-metrics-kube-state-metrics" is invalid: 
spec.template.metadata.labels: Invalid value: map[string]string{"release":"kube-state-metrics", 
"version":"v1.0.0", "app":"kube-state-metrics"}: `selector` does not match template `labels`
```

**Anything else we need to know**:

I believe it's because the version of which image is running is in the [deployment.yaml](https://github.com/kubernetes/charts/blob/f3201ee9b6d5c177e9690089689becac6ad82046/stable/kube-state-metrics/templates/deployment.yaml#L16) but the `selector` will by default match that so it's pinned when the chart is first installed. I confirmed this by first removing `spec.selector.matchLabels.version` manually from the Deployment and then re-running the `hel  upgrade` which worked as expected.

The other charts I'm currently using don't have the version in the selector but not sure what accepted practice is.

**Comment by unguiculus** [comment]
IMHO the version should not be in the selector. Our best practices don't recommend this either. Care to create a PR to remove the version label?

**Comment by cknowles** [comment]
@unguiculus PR above. I'm not sure whether to increment the version as a breaking change as I think this won't deploy over the top of existing deployments although the existing version won't anyway so...
