### ISSUE TITLE
[stable/redis] Does not work in k8s 1.16

### ISSUE THREAD

**Issue by rgl** [helm/charts#17260]
**Describe the bug**
Does not work in k8s 1.16

**Version of Helm and Kubernetes**:
Kubernetes 1.16.

**Which chart**:
stable/redis

**What happened**:
```
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
```

**Comment by juan131** [comment]
Thanks for reporting it. I just created a PR to address the issue.
