### ISSUE TITLE
MariaDB dependency should be opt-outable, one should be able to point to an existing DB

### ISSUE THREAD

**Issue by luxas** [helm/charts#1727]
FEATURE REQUEST

**Version of Helm and Kubernetes**:
HEAD

**Which chart**:
Most of them

**What happened**:
Installing a web service that depends on a DB installs the DB unconditionally

**What you expected to happen**:
I would have liked to be able to install the database instance separately in charts like Wordpress, Ghost, Drupal, etc.

**How to reproduce it** (as minimally and precisely as possible):
Deploy any of Wordpress, Ghost, Drupal and try to point it to an existing DB

**Comment by imphasing** [comment]
I thought this would accomplish this: https://github.com/kubernetes/charts/pull/773

but I am probably mistaken.. I am having a hard time getting this configured with the current template

**Comment by prydonius** [comment]
I think #773 gets us some of the way there (@sameersbn correct me if not). Two further changes we need to make:
- make [MARIADB_HOST](https://github.com/kubernetes/charts/blob/master/stable/wordpress/templates/deployment.yaml#L33) configurable, it's currently hardcoded
- add a value for disabling the dependency

**Comment by sameersbn** [comment]
@prydonius yea, maybe we could automatically disable the mariadb dependency if the user specifies a value for `MARIADB_HOST`

**Comment by luxas** [comment]
Can somebody do that for all the charts that link to a MariaDB then please?

**Comment by timothyclarke** [comment]
I've done the wordpress work in PR #2605, Sorry that's the only one I needed
Update: Changes for Wordpress have been merged
