### ISSUE TITLE
[stable kiam] setting iptables: true the agent fails. On selinux enabled systems

### ISSUE THREAD

**Issue by junaid18183** [helm/charts#17276]
**Describe the bug**
On Selinux enabled systems setting the `iptables: true` causing the agent to loop into `CrashLoopBackOff`

**Version of Helm and Kubernetes**:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}```



**Which chart**:
stable kiam 2.5.1

**What happened**:
I have deployed the stable kiam version 2.5.1  with agent iptables: true.  on a RHEL system with SELinux in enabled mode.  but the agent is not starting.

```
[root@ip-10-0-8-141 ~]# k get pods
NAME                  READY   STATUS             RESTARTS   AGE
demo-8c4f9ffb-758cd   1/1     Running            0          19m
kiam-agent-45l2l      0/1     CrashLoopBackOff   7          11m
kiam-server-f6jlg     1/1     Running            0          28m
[root@ip-10-0-8-141 ~]# k logs -f kiam-agent-45l2l
{"level":"info","msg":"configuring iptables","time":"2019-09-20T05:43:16Z"}
{"level":"fatal","msg":"error configuring iptables:running [/sbin/iptables -t nat -C PREROUTING -p tcp -d 169.254.169.254 --dport 80 -j DNAT --to-destination 10.0.8.141:8181 -i cni0 --wait]: exit status 4: Fatal: can't open lock file /run/xtables.lock: Permission denied\n","time":"2019-09-20T05:43:16Z"}```

**What you expected to happen**:
Agent POD should be running

**How to reproduce it** (as minimally and precisely as possible):
Install a helm chart on SElinux enabled machine. with iptables option set to true. 

**Anything else we need to know**:
We can

**Comment by ewbankkit** [comment]
@junaid18183 The kiam chart is now hosted by uSwitch.
Please open the issue in [their repo](https://github.com/uswitch/kiam) and close here.
Thanks.

**Comment by junaid18183** [comment]
Thanks @ewbankkit  I have created the https://github.com/uswitch/kiam/issues/302 for same
