### ISSUE TITLE
[stable/redis-ha] how to connect to redis-ha, redis-cli -h my-redis-redis-ha -p 6379 is ramdon to one of the cluster node,both master and slaver

### ISSUE THREAD

**Issue by 13567436138** [helm/charts#17291]
[stable/redis-ha] how to connect to redis-ha, redis-cli -h my-redis-redis-ha -p 6379 is ramdon to one of the cluster node,both master and slaver

**Comment by DandyDeveloper** [comment]
@13567436138 I'll need a better explanation than this from you. 

It should not be random, it will be whichever of your nodes have nominated themselves as master. The mechanism you are using to connect is correct though.

**Comment by azharullah** [comment]
@13567436138 It is suggested to connect to sentinel since that handles the redis master elections. You can connect to Sentinel using the same redis command, but with 26379 port and then query for the master's address. Refer to: https://redis.io/topics/sentinel-clients

**Comment by RedChops** [comment]
@DandyDeveloper I have noticed this issue as well on my end. What kind of explanation would you need? I have a Redis setup right now that isn't being used, connecting to `redis-ha` three times yields different results:

    /data $ redis-cli -h redis-ha
    redis-ha:6379> set test 1
    OK
    redis-ha:6379>
    /data $ redis-cli -h redis-ha
    redis-ha:6379> set test 1
    (error) READONLY You can't write against a read only replica.
    redis-ha:6379>
    /data $ redis-cli -h redis-ha
    redis-ha:6379> set test 1
    OK
That's within like a minute span and leader election shouldn't be taking place. I have a full application running as well in this namespace which is working just fine, no network connectivity issues. I also haven't really modified the default helm chart values here either.

**Comment by RedChops** [comment]
Sentinel does not appear to be doing anything regularly, see below logs from each:

redis-ha-server-0

    1:X 09 Nov 2019 19:14:18.211 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
    1:X 09 Nov 2019 19:14:18.211 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
    1:X 09 Nov 2019 19:14:18.211 # Configuration loaded
    1:X 09 Nov 2019 19:14:18.212 * Running mode=sentinel, port=26379.
    1:X 09 Nov 2019 19:14:18.212 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
    1:X 09 Nov 2019 19:14:18.213 # Sentinel ID is 79f3945a5a36c7748933e2cf51da3aa6b9e40022
    1:X 09 Nov 2019 19:14:18.213 # +monitor master mymaster 10.109.52.209 6379 quorum 2
    1:X 09 Nov 2019 19:14:18.215 * +slave slave 10.96.36.228:6379 10.96.36.228 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 19:14:18.224 * +slave slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 19:14:18.682 * +sentinel sentinel 930dc785e368d4d0e7a7fd422489df437cdb5255 10.109.52.209 26379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 19:14:18.700 # +new-epoch 3
    1:X 09 Nov 2019 19:14:20.050 * +sentinel sentinel 16f18bf4f68e622c08ce79cce6e1acc8aa39bb92 10.96.36.228 26379 @ mymaster 10.109.52.209 6379

redis-ha-server-1

    1:X 09 Nov 2019 17:58:47.311 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
    1:X 09 Nov 2019 17:58:47.311 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
    1:X 09 Nov 2019 17:58:47.311 # Configuration loaded
    1:X 09 Nov 2019 17:58:47.312 * Running mode=sentinel, port=26379.
    1:X 09 Nov 2019 17:58:47.312 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
    1:X 09 Nov 2019 17:58:47.313 # Sentinel ID is 930dc785e368d4d0e7a7fd422489df437cdb5255
    1:X 09 Nov 2019 17:58:47.313 # +monitor master mymaster 10.106.244.135 6379 quorum 2
    1:X 09 Nov 2019 17:58:47.314 * +slave slave 10.96.36.228:6379 10.96.36.228 6379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 17:58:47.323 * +slave slave 10.109.52.209:6379 10.109.52.209 6379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 17:58:47.353 * +sentinel sentinel 79f3945a5a36c7748933e2cf51da3aa6b9e40022 10.106.244.135 26379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 17:58:47.368 # +new-epoch 2
    1:X 09 Nov 2019 17:58:48.751 * +sentinel sentinel 16f18bf4f68e622c08ce79cce6e1acc8aa39bb92 10.96.36.228 26379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:11.158 # +sdown sentinel 79f3945a5a36c7748933e2cf51da3aa6b9e40022 10.106.244.135 26379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:11.224 # +sdown master mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:11.357 # +new-epoch 3
    1:X 09 Nov 2019 18:17:11.364 # +vote-for-leader 16f18bf4f68e622c08ce79cce6e1acc8aa39bb92 3
    1:X 09 Nov 2019 18:17:12.389 # +odown master mymaster 10.106.244.135 6379 #quorum 2/2
    1:X 09 Nov 2019 18:17:12.389 # Next failover delay: I will not start a failover before Sat Nov  9 18:23:11 2019
    1:X 09 Nov 2019 18:17:12.629 # +config-update-from sentinel 16f18bf4f68e622c08ce79cce6e1acc8aa39bb92 10.96.36.228 26379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:12.629 # +switch-master mymaster 10.106.244.135 6379 10.109.52.209 6379
    1:X 09 Nov 2019 18:17:12.629 * +slave slave 10.96.36.228:6379 10.96.36.228 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 18:17:12.630 * +slave slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 18:17:22.656 # +sdown slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 19:14:22.427 # -sdown slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 19:14:27.446 # -sdown sentinel 79f3945a5a36c7748933e2cf51da3aa6b9e40022 10.106.244.135 26379 @ mymaster 10.109.52.209 6379

redis-ha-server-2

    1:X 03 Nov 2019 20:56:21.341 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
    1:X 03 Nov 2019 20:56:21.341 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
    1:X 03 Nov 2019 20:56:21.341 # Configuration loaded
    1:X 03 Nov 2019 20:56:21.343 * Running mode=sentinel, port=26379.
    1:X 03 Nov 2019 20:56:21.343 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
    1:X 03 Nov 2019 20:56:21.343 # Sentinel ID is 16f18bf4f68e622c08ce79cce6e1acc8aa39bb92
    1:X 03 Nov 2019 20:56:21.343 # +monitor master mymaster 10.106.244.135 6379 quorum 2
    1:X 03 Nov 2019 20:56:21.344 * +slave slave 10.109.52.209:6379 10.109.52.209 6379 @ mymaster 10.106.244.135 6379
    1:X 03 Nov 2019 20:56:21.352 * +slave slave 10.96.36.228:6379 10.96.36.228 6379 @ mymaster 10.106.244.135 6379
    1:X 03 Nov 2019 20:56:22.329 * +sentinel sentinel 79f3945a5a36c7748933e2cf51da3aa6b9e40022 10.106.244.135 26379 @ mymaster 10.106.244.135 6379
    1:X 03 Nov 2019 20:56:22.982 * +sentinel sentinel 930dc785e368d4d0e7a7fd422489df437cdb5255 10.109.52.209 26379 @ mymaster 10.106.244.135 6379
    1:X 03 Nov 2019 21:25:37.630 # +sdown sentinel 930dc785e368d4d0e7a7fd422489df437cdb5255 10.109.52.209 26379 @ mymaster 10.106.244.135 6379
    1:X 03 Nov 2019 21:25:37.713 # +sdown slave 10.109.52.209:6379 10.109.52.209 6379 @ mymaster 10.106.244.135 6379
    1:X 03 Nov 2019 21:25:56.007 * +reboot slave 10.109.52.209:6379 10.109.52.209 6379 @ mymaster 10.106.244.135 6379
    1:X 03 Nov 2019 21:25:56.088 # -sdown slave 10.109.52.209:6379 10.109.52.209 6379 @ mymaster 10.106.244.135 6379
    1:X 03 Nov 2019 21:25:57.129 # -sdown sentinel 930dc785e368d4d0e7a7fd422489df437cdb5255 10.109.52.209 26379 @ mymaster 10.106.244.135 6379
    1:X 03 Nov 2019 21:27:05.214 # +sdown master mymaster 10.106.244.135 6379
    1:X 03 Nov 2019 21:27:05.214 # +sdown sentinel 79f3945a5a36c7748933e2cf51da3aa6b9e40022 10.106.244.135 26379 @ mymaster 10.106.244.135 6379
    1:X 03 Nov 2019 21:27:05.369 # +new-epoch 1
    1:X 03 Nov 2019 21:27:05.375 # +vote-for-leader 930dc785e368d4d0e7a7fd422489df437cdb5255 1
    1:X 03 Nov 2019 21:27:05.631 # +config-update-from sentinel 930dc785e368d4d0e7a7fd422489df437cdb5255 10.109.52.209 26379 @ mymaster 10.106.244.135 6379
    1:X 03 Nov 2019 21:27:05.631 # +switch-master mymaster 10.106.244.135 6379 10.109.52.209 6379
    1:X 03 Nov 2019 21:27:05.632 * +slave slave 10.96.36.228:6379 10.96.36.228 6379 @ mymaster 10.109.52.209 6379
    1:X 03 Nov 2019 21:27:05.632 * +slave slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 03 Nov 2019 21:27:15.648 # +sdown slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 03 Nov 2019 21:30:14.173 # -sdown slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 03 Nov 2019 21:30:14.173 # -sdown sentinel 79f3945a5a36c7748933e2cf51da3aa6b9e40022 10.106.244.135 26379 @ mymaster 10.109.52.209 6379
    1:X 04 Nov 2019 01:47:37.729 # +sdown slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 04 Nov 2019 01:47:37.729 # +sdown sentinel 79f3945a5a36c7748933e2cf51da3aa6b9e40022 10.106.244.135 26379 @ mymaster 10.109.52.209 6379
    1:X 04 Nov 2019 01:47:48.103 # +sdown master mymaster 10.109.52.209 6379
    1:X 04 Nov 2019 01:47:48.103 # +sdown sentinel 930dc785e368d4d0e7a7fd422489df437cdb5255 10.109.52.209 26379 @ mymaster 10.109.52.209 6379
    1:X 04 Nov 2019 01:48:17.509 # +tilt #tilt mode entered
    1:X 04 Nov 2019 01:48:47.565 # -tilt #tilt mode exited
    1:X 04 Nov 2019 01:48:47.565 # -sdown master mymaster 10.109.52.209 6379
    1:X 04 Nov 2019 01:48:47.565 # -sdown slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 04 Nov 2019 01:48:47.565 # -sdown sentinel 930dc785e368d4d0e7a7fd422489df437cdb5255 10.109.52.209 26379 @ mymaster 10.109.52.209 6379
    1:X 04 Nov 2019 01:48:47.565 # -sdown sentinel 79f3945a5a36c7748933e2cf51da3aa6b9e40022 10.106.244.135 26379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:31.536 # +sdown master mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:31.537 # +sdown sentinel 930dc785e368d4d0e7a7fd422489df437cdb5255 10.109.52.209 26379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:31.627 # +odown master mymaster 10.109.52.209 6379 #quorum 2/2
    1:X 09 Nov 2019 17:58:31.628 # +new-epoch 2
    1:X 09 Nov 2019 17:58:31.628 # +try-failover master mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:31.639 # +vote-for-leader 16f18bf4f68e622c08ce79cce6e1acc8aa39bb92 2
    1:X 09 Nov 2019 17:58:31.659 # 79f3945a5a36c7748933e2cf51da3aa6b9e40022 voted for 16f18bf4f68e622c08ce79cce6e1acc8aa39bb92 2
    1:X 09 Nov 2019 17:58:31.740 # +elected-leader master mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:31.741 # +failover-state-select-slave master mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:31.824 # +selected-slave slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:31.824 * +failover-state-send-slaveof-noone slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:31.895 * +failover-state-wait-promotion slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:32.878 # +promoted-slave slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:32.879 # +failover-state-reconf-slaves master mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:32.949 * +slave-reconf-sent slave 10.96.36.228:6379 10.96.36.228 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:33.373 * +slave-reconf-inprog slave 10.96.36.228:6379 10.96.36.228 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:33.792 # -odown master mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:34.435 * +slave-reconf-done slave 10.96.36.228:6379 10.96.36.228 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:34.518 # +failover-end master mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 17:58:34.518 # +switch-master mymaster 10.109.52.209 6379 10.106.244.135 6379
    1:X 09 Nov 2019 17:58:34.518 * +slave slave 10.96.36.228:6379 10.96.36.228 6379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 17:58:34.518 * +slave slave 10.109.52.209:6379 10.109.52.209 6379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 17:58:44.572 # +sdown slave 10.109.52.209:6379 10.109.52.209 6379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 17:58:49.043 # -sdown sentinel 930dc785e368d4d0e7a7fd422489df437cdb5255 10.109.52.209 26379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 17:58:49.771 # -sdown slave 10.109.52.209:6379 10.109.52.209 6379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:11.196 # +sdown sentinel 79f3945a5a36c7748933e2cf51da3aa6b9e40022 10.106.244.135 26379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:11.262 # +sdown master mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:11.334 # +odown master mymaster 10.106.244.135 6379 #quorum 2/2
    1:X 09 Nov 2019 18:17:11.334 # +new-epoch 3
    1:X 09 Nov 2019 18:17:11.334 # +try-failover master mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:11.345 # +vote-for-leader 16f18bf4f68e622c08ce79cce6e1acc8aa39bb92 3
    1:X 09 Nov 2019 18:17:11.363 # 930dc785e368d4d0e7a7fd422489df437cdb5255 voted for 16f18bf4f68e622c08ce79cce6e1acc8aa39bb92 3
    1:X 09 Nov 2019 18:17:11.416 # +elected-leader master mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:11.416 # +failover-state-select-slave master mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:11.487 # +selected-slave slave 10.109.52.209:6379 10.109.52.209 6379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:11.487 * +failover-state-send-slaveof-noone slave 10.109.52.209:6379 10.109.52.209 6379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:11.549 * +failover-state-wait-promotion slave 10.109.52.209:6379 10.109.52.209 6379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:12.540 # +promoted-slave slave 10.109.52.209:6379 10.109.52.209 6379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:12.540 # +failover-state-reconf-slaves master mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:12.627 * +slave-reconf-sent slave 10.96.36.228:6379 10.96.36.228 6379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:12.959 * +slave-reconf-inprog slave 10.96.36.228:6379 10.96.36.228 6379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:12.959 * +slave-reconf-done slave 10.96.36.228:6379 10.96.36.228 6379 @ mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:13.035 # +failover-end master mymaster 10.106.244.135 6379
    1:X 09 Nov 2019 18:17:13.035 # +switch-master mymaster 10.106.244.135 6379 10.109.52.209 6379
    1:X 09 Nov 2019 18:17:13.035 * +slave slave 10.96.36.228:6379 10.96.36.228 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 18:17:13.036 * +slave slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 18:17:23.058 # +sdown slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 19:14:22.216 # -sdown slave 10.106.244.135:6379 10.106.244.135 6379 @ mymaster 10.109.52.209 6379
    1:X 09 Nov 2019 19:14:25.576 # -sdown sentinel 79f3945a5a36c7748933e2cf51da3aa6b9e40022 10.106.244.135 26379 @ mymaster 10.109.52.209 6379
