### ISSUE TITLE
[stable/prometheus-operator] some recorded metrics have no data

### ISSUE THREAD

**Issue by zellerfagyi** [helm/charts#17293]
**Describe the bug**
After upgrading to prometheus-operator 6.8.3 (from 4.6.1), installed from Helm chart, couple of Grafana charts like 'Kubernetes / USE Method / Node' , 'Kubernetes / USE Method / Cluster' are empty and display 'No data points'. 

Checked the metrics behind some of the affected charts and it appears as the affected recorded metrics have 'No datapoints found.', while their 'expr' can correctly evaluate.

Example (from prometheus-operator/templates/prometheus/rules/node.rules.yaml(:
   ` - expr: 1 - avg(rate(node_cpu_seconds_total{job="node-exporter",mode="idle"}[1m])) `[01-expression-ok.png]
`      record: :node_cpu_utilisation:avg1m `[02-recorded_metric-nodatapoints.png]

Please see result in attachment as indicated above. Another example would be:
```

    - expr: |-
        1 - avg by (node) (
          rate(node_cpu_seconds_total{job="node-exporter",mode="idle"}[1m])
        * on (namespace, pod) group_left(node)
          node_namespace_pod:kube_pod_info:)
      record: node:node_cpu_utilisation:avg1m
```

with similar result; as the recorded metric has no data while the exact expression yields data. Please let me know if you need any other inputs.

Could you please give some hints on what the matter might be, why the recorded metric has no data while its query does have ? Also might or might not be related, but around prometheus-operator upgrade we upgraded GKE kube-masters from 1.12 to 1.14.

**Version of Helm and Kubernetes**:
Helm:
`Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}`

Kubernetes (on GKE):
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:21:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.1", GitCommit:"61c30f98599ad5309185df308962054d9670bafa", GitTreeState:"clean", BuildDate:"2019-08-28T11:06:42Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}`

**Which chart**:
prometheus-operator

**What happened**:
Please see bug description

**What you expected to happen**:
I would expect the recorded metrics not to be empty if their 'base' expressions evaluate to something which has value.

**How to reproduce it** (as minimally and precisely as possible):
I'm not sure how to reproduce it, but what I did was
- modify requirements.yaml for the Helm chart to require 6.8.3 instead of 4.6.1
- `helm dependency update`
- `helm upgrade` the chart
- after a while, detect the problem

Thank you !

**Comment by zellerfagyi** [comment]
![01-expression-ok](https://user-images.githubusercontent.com/50657665/65326965-fd30b480-dbb2-11e9-9214-4e4e48dcc87d.png)
![02-recorded_metric-nodatapoints](https://user-images.githubusercontent.com/50657665/65326967-fdc94b00-dbb2-11e9-813b-26bc77db6f7e.png)

**Comment by zellerfagyi** [comment]
any hints on this please ?

**Comment by dszmolka** [comment]
Would really appreciate if anyone could point me to the right direction.
