### ISSUE TITLE
Warning: Merging destination map for chart 'docker-registry'. The destination item 'annotations' is a table and ignoring the source 'annotations' as it has a non-table value of: <nil>

### ISSUE THREAD

**Issue by onjectiondevops** [helm/charts#17348]
We are getting errors while use docker-registry latest chart as dependency for our stack.

I can see it's missing {} brackets in line :`https://github.com/helm/charts/blob/master/stable/docker-registry/values.yaml#L35 `

Please add annotations: {} to fix these warnings

**Comment by angegar** [comment]
Hi i have the same issue which prevent my deployment to finish which is weird as it is just a warning.

In this message what are the source and the destination ?

PS : Hope someone will read it at is  stale :D
