### ISSUE TITLE
[stable/weave-scope] Invalid spec "updateStrategy" in weave-scope-cluster-agent deployment

### ISSUE THREAD

**Issue by rptntobias** [helm/charts#17369]
**Describe the bug**
The most recent update to the deployment in the weave-scope-cluster-agent subchart adds updateStrategy to the spec: https://github.com/helm/charts/blob/5c06d394ac0a4701becd46688d569d24ff1a4593/stable/weave-scope/charts/weave-scope-cluster-agent/templates/deployment.yaml#L17

Per the v1beta1 api specifications, the valid name is "strategy": 
https://v1-13.docs.kubernetes.io/docs/reference/federation/extensions/v1beta1/definitions/#_v1beta1_deploymentspec

kubectl fails to deploy the manifest if rendered with default values.

**Version of Helm and Kubernetes**:
Helm v2.11.0
Kubernetes v1.14.6

**Which chart**:
stable/weave-scope

**What happened**:
kubectl reports and error trying to deploy the rendered manifest:

error validating data: ValidationError(Deployment.spec): unknown field "updateStrategy" in io.k8s.api.extensions.v1beta1.DeploymentSpec

**What you expected to happen**:
The deployment deploys successfully

**How to reproduce it** (as minimally and precisely as possible):
```bash
helm fetch --untar --untardir ./ stable/weave-scope
helm template -n scope ./weave-scope | kubectl apply -f -
```
**Anything else we need to know**:

**Comment by doughoke** [comment]
I can fix it.  @rptntobias You are correct I stumbled on it and ran through "helm template" and modified the manifest before I pushed with a kubectl. Refer to the following - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#deploymentspec-v1-apps  

@Owner of weave-scope chart how would you like me do proceed? I can write to this stable or I can use a supplement repo.

**Comment by spanktar** [comment]
I'm also hitting this now that we're using Helm 3
