### ISSUE TITLE
Fluent-bit chart not pushing logs from kubernetes cron-job pods

### ISSUE THREAD

**Issue by galactus009** [helm/charts#17378]
We have installed fluent-bit as daemon set in our kubernetes cluster for forwarding logs to our centralized logging cluster. Every thing is working fine except some of the pods run as kubernetes jobs. We are not able to see logs of those jobs being forwarded. Please suggest what is the best way/configuration that need to be done at fluent-bit side to get logs of these jobs

**Comment by shyimo** [comment]
@hellobhaskar Hi! 
we are having the same issue on our k8s production clusters. fluentbit is unable to collect cronjob logs. do you add any progress with that ?

**Comment by epicvinny** [comment]
Same here! But with fluentd.

**Comment by dyipon** [comment]
Same here with k3s, fluentd.

**Comment by vsuzdaltsev** [comment]
the same with fluent bit
