### ISSUE TITLE
[incubator/kafka] fail to start metrics sidecar

### ISSUE THREAD

**Issue by zenglian** [helm/charts#17383]
**Describe the bug**
fail to start kafka pod (metrics sidecar), when prometheus.jmx.enabled = true

**Version of Helm and Kubernetes**:
k8s:  1.10
helm: 2.10

**Which chart**:
kafka

**What happened**:
Fail to start kafka pod, when prometheus.jmx.enabled = true

**How to reproduce it** (as minimally and precisely as possible):
set prometheus.jmx.enabled = true and helm create

**Anything else we need to know**:
*metrics* container is started before *broker* container yet pending on *broker*

**Comment by MahajanTushar** [comment]
which among the two brokers of kafka statefulset's pod get ready ? Try checking logs for the container
