### ISSUE TITLE
[stable/prometheus-operator] Error in statefulset dashboard

### ISSUE THREAD

**Issue by tomerleib** [helm/charts#17405]
**Describe the bug**
When accessing the statefulset dashboard, the following error pops out:
`Templating init failed: parse error at char 63: could not parse remaining input ", cluster=\"\""...`

**Version of Helm and Kubernetes**:
helm - 2.143
kubernetes - v1.14.6-eks-5047ed

**Which chart**:

prometheus-operator

**What happened**:
Dashboard for statefulset is useless due to this error. There are no metrics available.

**What you expected to happen**:

Comparing to this dashboard: https://grafana.com/grafana/dashboards/5330 
This dashboard works fine and the statefulset dashboard that is coming from the chart should work the same.

**How to reproduce it** (as minimally and precisely as possible):

Deploy the chart on EKS and check the dashboard.

**Anything else we need to know**:

I've started to compare between the json in the chart and the json from the working dashboard, the main difference is to ommit the cluster variable:

_json_in_chart_ :
```
{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$statefulset.*\"}
```

_working_json_:
```
{namespace=\"$statefulset_namespace\",pod_name=~\"$statefulset_name.*\"}
```

**Comment by rasentry** [comment]
It seems close brace in a wrong position https://github.com/helm/charts/blob/72e4abed62a8001f0850dc838c22f87d4b59fe28/stable/prometheus-operator/templates/grafana/dashboards-1.14/statefulset.yaml#L847

**Comment by tomerleib** [comment]
What about this one?
https://github.com/helm/charts/blob/72e4abed62a8001f0850dc838c22f87d4b59fe28/stable/prometheus-operator/templates/grafana/dashboards-1.14/statefulset.yaml#L873

Which one is the correct way?

**Comment by rasentry** [comment]
> What about this one?

This is correct line

**Comment by tomerleib** [comment]
Thanks, so since the dashboards are forked from kube-prometheus project, I'll submit the issue there as well with your finding.

**Comment by tomerleib** [comment]
I've updated the file:
```
"query": "label_values(kube_statefulset_metadata_generation{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"})",
```

However, the dashboard is now stuck in `services` as it is trying to load something and it stays the same forever

**Comment by rasentry** [comment]
No, correct line should looks like
```
 "query": "label_values(kube_statefulset_metadata_generation{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)",
```

**Comment by tomerleib** [comment]
Got it, thanks.
