### ISSUE TITLE
[stable/chartmuseum] No matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by rafambbr** [helm/charts#17408]
**Describe the bug**
When install: Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

**Version of Helm and Kubernetes**:
Kubernetes V1.16
Helm V2.14.3

**Which chart**:
stable/chartmuseum

**What happened**:
When install: Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

**What you expected to happen**:
Install chartmuseum

**How to reproduce it** (as minimally and precisely as possible):
Just install "stable/chartmuseum" on Kubernetes 1.16

**Anything else we need to know**:
No

**Comment by gwvandesteeg** [comment]
Same here, clean install of minikube to run it on.

**Comment by popsonebz** [comment]
> Same here, clean install of minikube to run it on.
> 
> https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
> 
> Looks like extensions/v1beta1 got deprecated, and there is a missing selector on the Deployment chart.
> 
> Changes needed:
> 
> From `apiVerson: extensions/v1beta1`
> To: `apiVersion: apps/v1`

This works but you need to first install tiller using the yaml file below instead of helm init
`---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: helm
      name: tiller
  template:
    metadata:
      labels:
        app: helm
        name: tiller
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: TILLER_NAMESPACE
          value: kube-system
        - name: TILLER_HISTORY_MAX
          value: "0"
        image: gcr.io/kubernetes-helm/tiller:v2.14.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        name: tiller
        ports:
        - containerPort: 44134
          name: tiller
        - containerPort: 44135
          name: http
        readinessProbe:
          httpGet:
            path: /readiness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        resources: {}
      serviceAccountName: tiller
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  ports:
  - name: tiller
    port: 44134
    targetPort: tiller
  selector:
    app: helm
    name: tiller
  type: ClusterIP
status:
  loadBalancer: {}`

**Comment by Ja-k** [comment]
**After running the command:**

$kubectl apply -f sock-shop-ns.yaml -f .

**I get the following error for all deployments:**

Missing Required Field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by d4nyll** [comment]
@rafambbr This should have been fixed with #17334. Just run `helm repo update` and use the `2.4.0` version of the chart.
