### ISSUE TITLE
[stable/fluent-bit] Unable to generate ServiceMonitor with helm template

### ISSUE THREAD

**Issue by invidian** [helm/charts#17400]
**Describe the bug**

Currently `fluent-bit` helm chart use `.Capabilities.APIVersion.Has` feature of helm to control if ServiceMonitor object should be rendered in addition to `metrics.enabled` and `metrics.serviceMonitor.enabled`: https://github.com/helm/charts/blob/master/stable/fluent-bit/templates/servicemonitor.yaml#L1

When using `helm template` to render helm chart locally (that allows to put additional customization with kustomize without forking the helm chart), this does not work, as `helm template` does not communicate with Kubernetes API. It is currently also not possible to override it either. Upstream issue: https://github.com/helm/helm/issues/3377

The workaround for that is to have ServiceMonitor object deployed separately, which is not ideal. I think there should be a knob to disable this capabilities check (although in other helm charts, setting `metrics.enabled` + `metrics.serviceMonitor.enabled` is usually sufficient.

**Version of Helm and Kubernetes**:
```
$ helm version --client
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**Which chart**:
`stable/fluent-bit`

**What happened**:
`ServiceMonitor` object is not rendered despite having `metrics.enabled` and `metrics.serviceMonitor.enabled` set to `true`.

**What you expected to happen**:
`ServiceMonitor` object should be rendered when having `metrics.enabled` and `metrics.serviceMonitor.enabled` set to `true`.

**How to reproduce it** (as minimally and precisely as possible):
```
$ helm fetch stable/fluent-bit --untar --version 2.7.0
$ helm template --set metrics.enabled=true --set metrics.serviceMonitor.enabled=true fluent-bit
```

**Comment by maarek** [comment]
This issue also expands to producing rbacs using the v1alpha1 api on a v1 kubernetes.

**Comment by invidian** [comment]
Not stale

**Comment by jfassad** [comment]
@invidian 

You must use --api-versions e.g.

helm template -f values.yaml fluent-bit  stable/fluent-bit --namespace logging --api-versions "monitoring.coreos.com/v1"

**Comment by invidian** [comment]
Oh, that's good to know, thanks @jfassad. It seem still like a workaround though, but I'm fine with closing it.
