### ISSUE TITLE
[stable/redis-ha] haproxy serviceaccount "default-haproxy" not found

### ISSUE THREAD

**Issue by kfkawalec** [helm/charts#17414]
**Describe the error**
I want to use Helm v3 with RBAC support. I disable service account for redis pods and everything works.
But when I disable service account for haproxy I have an error:
`Pods "redis-production-haproxy-7c9d595df6-" is forbidden: service account search error redis/default-haproxy: service account" default-haproxy "not found
I cannot use the service accounts because it requires an additional permission which I dont have.

**Which chart:**
redis-ha-3.7.10

**What happened:**
HAProxy has 0 pods

**How to play it (as minimal and precise as possible):**
Deploy with HAProxy and disable all service accounts.

**Comment by DandyDeveloper** [comment]
@kfkawalec PR Pending.
