### ISSUE TITLE
[stable/redis-ha] haproxy init container doesn't wait for service announce

### ISSUE THREAD

**Issue by cschockaert** [helm/charts#17418]
Hello,
Just runned into that bug.

Our config:
```
deploy on GCP K8S (v1.12.7-gke.10)
3 redis instances
1 haproxy pod
```

The haproxy pod is in crashloopbackoff due to : 

```
[ALERT] 267/072039 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:20] : 'tcp-check expect string' expects <string> as an argument.
[ALERT] 267/072039 (1) : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
[ALERT] 267/072039 (1) : Fatal errors found in configuration.
```

After investiguate, seems that the init container of haproxy responsive of making the haproxy.cfg did not wait for the announce service to have an IP
even with 
```
spec:
 publishNotReadyAddresses: true
```

so the line tcp-check expect string REPLACE_ANNOUNCE{{ $i }} is empty (should be the service announce ip)

the init container should at least wait for the service to announce an ip before trying to sed the haproxy.cfg file:

perhaps with something like:

```
until nslookup {{ $fullName }}-announce-{{ $i }}.{{ .Release.Namespace }}.svc.cluster.local
  do echo waiting for service announce to be ready
  sleep 1
done
```

Note that our redis are under toleration and nodeSelector settings that could lead to more time to assign the pod to an available node.

Thanks

**Comment by DandyDeveloper** [comment]
@cschockaert This is a pretty fair race-condition that hasn't been considered. 

That loop would be a nice way around it, but we'd need some form of timeout on that to ensure the container does eventually fail if announce services are not being produced for whatever reason

**Comment by cschockaert** [comment]
Sure, do you want me to make a PR?

**Comment by DandyDeveloper** [comment]
@cschockaert I'd be very grateful for a PR, if not, I'll try and get it done asap

**Comment by cschockaert** [comment]
Ok i'll do it
