### ISSUE TITLE
[stable/datadog] DD_APM_NON_LOCAL_TRAFFIC should be true by default on Kubernetes

### ISSUE THREAD

**Issue by marekaf** [helm/charts#17423]
**Describe the bug**
It is not possible to set `DD_APM_NON_LOCAL_TRAFFIC` in helm chart values and it is false by default. That makes datadog-agent reject all the traces even if `datadog.apmEnabled: true`.

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
`stable/datadog`

**What you expected to happen**:
add datadog.apmNonLocalTraffic to values.yaml and set it to true by default

**Workaround**:
set
```yaml
datadog:
  env:
    - name: DD_APM_NON_LOCAL_TRAFFIC
      value: "true"
```

**Comment by gbergere** [comment]
You should be able to fix that by setting `datadog.nonLocalTraffic` to `True` in helm :)

**Comment by marekaf** [comment]
> You should be able to fix that by setting `datadog.nonLocalTraffic` to `True` in helm :)

I'm pretty sure that doesn't work.  `datadog.nonLocalTraffic` and `DD_APM_NON_LOCAL_TRAFFIC` are two different things. 

I mentioned a workaround that works. But I don't want to use any workarounds. I expect the `DD_APM_NON_LOCAL_TRAFFIC` to be set to true by default when enabling `datadog.apmEnabled`

**Comment by nesl247** [comment]
This seems to have been fixed in https://github.com/helm/charts/pull/17080.
