### ISSUE TITLE
Unable to connect with mongodb from internal kubernetes cluster

### ISSUE THREAD

**Issue by MahajanTushar** [helm/charts#17429]
I tried setting up mongodb via bitnami stable/mongodb helm chart, the helm chart installation command is as follows - 

**helm install --name mongo  --set mongodbRootPassword=mongo,mongodbUsername=mongo,mongodbPassword=mongo,mongodbDatabase=database stable/mongodb**

 after creation of it, I am looking to connect my applications by following format of connection string

**mongodb://[user]:[password]@[service].[namespace].svc.cluster.local:27017/[db]?replicaSet=rs0&authSource=admin**

But I am getting error for this - 

 failed to connect to server [mongo.shift-resourcing.svc.cluster.local:27017] on first connect [MongoNetworkError: Client network socket disconnected before secure TLS connection was established]

**Comment by miguelaeh** [comment]
Hi @MahajanTushar ,
We are not able to replicate it, could you provide more information?
I tested with the `mongo` client from inside the cluster and I can connect properly.
```
 $ mongo mongo-mongodb.<NAMESPACE>.svc.cluster.local
MongoDB shell version: 3.2.11
connecting to: mongo-mongodb.<NAMESPACE>.svc.cluster.local/test
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	http://docs.mongodb.org/
Questions? Try the support group
	http://groups.google.com/group/mongodb-user
>
```

**Comment by MahajanTushar** [comment]
Hi @miguelaeh 

Thanks for sharing this.

With this client I am able to make connection, but while connecting to it one of nodeJS applications resting in the same AKS cluster, I faced the above mentioned issue.

Can you please let me know, how shall I design the connection string here, if the format that I placed above is correct ?

I request you to help me here, as I tried multiple variants as per mongodb official documentation

**Comment by miguelaeh** [comment]
Hi @MahajanTushar ,
I created a simple application on node to test it and in my case I can connect.
Deploying the chart with your command and a nodejs pod to do tests I exec into the nodejs pod and did this:
```
MongoClient.connect("mongodb://mongo:mongo@mongo-mongodb.<NAMESPACE>.svc.cluster.local:27017/database", function (err, db) {
   
     if(err) throw err;

     console.log("I CAN CONNECT!!")
                
});
```

I get this output:
```bash
root@node-pod:/# node
Welcome to Node.js v12.10.0.
Type ".help" for more information.
> var MongoClient = require('mongodb').MongoClient;
> MongoClient.connect("mongodb://mongo:mongo@mongo-mongodb.<NAMESPACE>.svc.cluster.local:27017/database", function (err, db) {
...
...      if(err) throw err;
...
...      console.log("I CAN CONNECT!!")
...
... });
undefined
> Warning: no saslprep library specified. Passwords will not be sanitized
I CAN CONNECT!!
```

**Comment by MahajanTushar** [comment]
Okay I will check that in my library of nodeJS  application. Thanks a lot for help
