### ISSUE TITLE
[charts/incubator/kafka/templates/deployment-kafka-exporter.yaml] Invalid Label Value not matching template spec preventing deployment of kafka-exporter 

### ISSUE THREAD

**Issue by ericbannon** [helm/charts#17434]
**Describe the bug**
helm install --namespace developers --name kafka --set prometheus.jmx.enabled=true,prometheus.kafka.enabled=true,persistence.size=40Gi incubator/kafka

When running the above command and setting the prometheus.kafka.enabled=true flag, I receive the following error. This prevents me from deploying kafka-exporter into the environment which was working 2 days ago. I noticed some changes that were made to labels and wondering if something is off in the config ... please advise 

Error: release kafka failed: Deployment.apps "kafka-exporter" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"kafka-exporter", "release":"kafka"}: `selector` does not match template `labels

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.12.3", 
Server: &version.Version{SemVer:"v2.12.3", 

Kubernetes 1.13.6 running in EC2 ... (upstream) 

**Which chart**:
incubator/kafka

**What you expected to happen**:
Kafka deploys with exporter pod deployed as well 

**How to reproduce it** (as minimally and precisely as possible):
Deploy the helm chart with  prometheus.kafka.enabled=true flag which is supposed to deploy the exporter 

**Anything else we need to know**:

**Comment by MahajanTushar** [comment]
did you check the selector of prometheus that you have integrated in your application, try checking it by getting the service object of prometheus and in the kafka exporter, you can add the same label. Maybe this helps.
