### ISSUE TITLE
Question about recommended wordpress values

### ISSUE THREAD

**Issue by hilt86** [helm/charts#17438]
The stable wordpress chart recommends `service.type: ClusterIP` for production Kubernetes deployments. As far as I can tell service type Loadbalancer is the standard way (see https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types) to publish a resource to the Internet and clusterip would only be reachable from within the cluster.

Can someone explain this choice please?

**Comment by rafariossaa** [comment]
Hi @hilt86,
  Thanks for noticing this. 
  It is a bug in the chart, it should be loadbalancer in both cases.
  We are going to fix it.
