### ISSUE TITLE
Updating adminUser and adminPassword causes login to fail

### ISSUE THREAD

**Issue by imorti** [helm/charts#17431]
**Describe the bug**
For jenkins chart, I added values for adminUser and adminPassword to the values.yaml and while they get applied, I can't login after the upgrade. 

**Version of Helm and Kubernetes**:
Helm: 
Client/Server both v2.14.1 

**Which chart**:
Jenkins 

**What happened**:
For jenkins chart, I added values for adminUser and adminPassword to the values.yaml and while they get applied, I can't login after the upgrade. 

**What you expected to happen**:
I expected to be able to login with the values I put in the values.yml file. 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by MahajanTushar** [comment]
Did you check for the secret in the same namespace that has been generated for jenkins !!
