### ISSUE TITLE
[stable/postgresql] PG can not failover automatically when master node is shutdown

### ISSUE THREAD

**Issue by uddmorningsun** [helm/charts#17442]
**Describe the bug**

When I `shutdown` master node in K8S HA mode, PG can't failover automatically. PG pod status is not healthy and then other services connected PG database will failed

**Version of Helm and Kubernetes**:

```
[root@skyaxe-app-1 tmp]# kubectl  version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
[root@skyaxe-app-1 tmp]# helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**Which chart**:

* postgresql-5.3.0：http://mirror.azure.cn/kubernetes/charts/postgresql-5.3.0.tgz

**What happened**:

We have deployed K8S HA(based on `keepalived VIP`) using `3` APP nodes(`master role`) and other nodes(`non master role`), our service need PG to store data and support HA mode. I have finished to deploy PG with helm in APP node.

* When I delete one of the slave pod or shutdown a node existed slave PG pod manually, PG HA cluster status is OK (It's expected)
* When I delete master pod manually, after waiting a minutes PG master pod recreated and reconnected and then establish new stream replication to backup based on existed data in CephFS, cluster status is also OK finally.

* When I shutdown master node, PG can't failover automatically. PG pod status is not healthy and then other services connected PG database will failed. Shutdown master node, data in CephFS willn't be lost

**What you expected to happen**:

Other PG pod can failover automatically while master pod can't recover forever.

**How to reproduce it** (as minimally and precisely as possible):

About data storage, we utilize CephFS to share data. `helm install` to deploy PG, see `postgresql.yaml`:
```
10.0.30.131,10.0.30.132,10.0.30.133:/ ceph      1.7T  4.1G  1.7T   1% /SkyDiscovery/cephfs
```

```
[root@skyaxe-app-1 ha]# cat postgresql.yaml
image:
  pullPolicy: IfNotPresent
  debug: true
  repository: bitnami/postgresql
  tag: 9.6.15

replication:
  enabled: true
  slaveReplicas: 2
  synchronousCommit: "on"
  numSynchronousReplicas: 1

postgresqlPassword: "password"

persistence:
  enabled: true
  size: 16Gi
  storageClass: harbor-postgresql-data

master:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector: {'matchExpressions': [{'key': 'release', 'operator': 'In', 'values': ['harbor-postgresql']}]}
          topologyKey: kubernetes.io/hostname

  nodeSelector: {"node-role.kubernetes.io/master": ""}
  tolerations: [{"key": "node-role.kubernetes.io/master", "effect": "NoSchedule"}]

slave:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector: {'matchExpressions': [{'key': 'release', 'operator': 'In', 'values': ['harbor-postgresql']}]}
          topologyKey: kubernetes.io/hostname

  nodeSelector: {"node-role.kubernetes.io/master": ""}
  tolerations: [{"key": "node-role.kubernetes.io/master", "effect": "NoSchedule"}]
```
```
[root@skyaxe-app-1 harbor]# helm install --name harbor-postgresql  -f ./values.yaml ./postgresql-helm.tgz 
```

**Anything else we need to know**:

PG will be used by harbor, grafana etc to support HA

**Comment by uddmorningsun** [comment]
PG cluster can also refer to: https://engineering.bitnami.com/articles/create-a-production-ready-postgresql-cluster-bitnami-kubernetes-and-helm.html

**Comment by javsalgar** [comment]
Hi,

The `stable/postgresql` chart does not have HA failover mechanisms. However, we are working on a HA version of the chart that could meet your needs. We will let you know as soon it is published.

cc @juan131

**Comment by kevinscholz** [comment]
Hi @javsalgar,
We would also be interested in the failover functionality. Do you have an ETA for the new version of the chart? Can I do anything to help?

**Comment by javsalgar** [comment]
Hi,

I'm afraid we do not have an ETA, but I can tell you that it's being reviewed for feedback.

**Comment by ccmehk** [comment]
HI @juan131 
Can i know when will you release the new PostgreSQL chart with HA features?

**Comment by juan131** [comment]
Hi @ccmehk 

Sorry, I forgot to give you the good news. We already released this new chart, you can find it in the link below:

- https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha
