### ISSUE TITLE
[incubator/kafka] Topics lost on reboot, possibly related to no Zookeeper volumes being created

### ISSUE THREAD

**Issue by bahaaador** [helm/charts#17468]
**Describe the bug**
Kafka topics are lost on cluster restarts. Persistent volumes created for Kafka but not for Zookeeper (either by using the default flags or explicitly enabling zookeeper persistence and volume size on chart install)

**Version of Helm and Kubernetes**:
Helm v2.14.3
Kubernetes 1.14+

**Which chart**:
incubator/kafka

**What happened**:
Kafka Topics created earlier were lost 
Installing the chart only created persistent volumes for Kafka, based on the description looks like separate PVCs should be created for Zookeeper instances too but none are created which I guess is related

**What you expected to happen**:
Topics to be persisted 

**How to reproduce it** (as minimally and precisely as possible):
A.`helm install --name INSTANCENAME incubator/kafka` does not create zookeeper PVC's

B. Create some topics and restart your cluster (or delete your pods), after pods are reinstantiated, notice that listing topics returns empty result

**Anything else we need to know**:

**Comment by baha2r** [comment]
UPDATE: setting zookeeper.persistence.enabled=true explicitly as part of command seems to make it work and PVCs are being created for zookeeper as well now. but it seems to disregard the volume size settings and only create `5Gi` ones:

`helm install --name tmp-kafka incubator/kafka --set replicas=1,persistence.size='1Gi',zookeeper.enabled=true,zookeeper.persistence.enabled=true,zookeeper.persistence.storage='2Gi'` (or zookeeper.storage='2Gi')

`kubectl get pvc`

_data-tmp-kafka-zookeeper-0                                        Bound    pvc-03c39fe3-e08c-11e9-8da0-0a16dacd566c   5Gi        RWO            gp2            4m30s
data-tmp-kafka-zookeeper-1                                        Bound    pvc-228e4beb-e08c-11e9-8da0-0a16dacd566c   5Gi        RWO            gp2            3m38s
data-tmp-kafka-zookeeper-2                                        Bound    pvc-451a2be6-e08c-11e9-8da0-0a16dacd566c   5Gi        RWO            gp2            2m40s
datadir-tmp-kafka-0                                               Bound    pvc-03cb6c8b-e08c-11e9-8da0-0a16dacd566c   1Gi        RWO            gp2            4m30s_

**Comment by franzmueller** [comment]
This might still be an issue. During maintenance I shut down kafka and zookeeper and when tuning them back on, kafka refused to connect to zk due to a wrong cluster id (id wasn't saved, since zk had no persistent volume). I had to manually change the cluster id for each kafka instance and add storage volumes for zk myself.

I've been using the chart for some time already and can't tell if a fresh install would still face the issue.
