### ISSUE TITLE
charts/stable/mongodb

### ISSUE THREAD

**Issue by ghost** [helm/charts#17480]
Hi,
     A big thanks for the such great helm chart. Am using the charts/stable/mongodb chart to install the mongodb in kubernates. During the installation am keeping the 1 master , 1-arbiter and 3-secondary.  When i enter to a master pod and run the rs.stepDown(), then for few second master will disappear and again it will get created with the same id.
   In my case, when do the rs.stepDown() then, master which is created from slave, i need to retain the until again the master kill. Is that possible here. If possible then please help me here. 
      Thanks

**Comment by rafariossaa** [comment]
Hi @perdoorrajeshnayak ,
  Thanks for you kind words, I am glad you like the chart.

  I am not very sure what you need to achieve. When you run rs.stepdown in the master this node will become a secondary and a secondary will become a master node. This master node is not eligible to become master until the stepDownSecs has passed (by default 60 seconds).

**Comment by perdoorrajeshnayak** [comment]
Thanks Rafael for your reply,
     When i run a rs.staus(2000,5), the primary pod  is going down for 2000 sec and it is showing the the one of the  secondary pod as primary pod ,when i entered to primary pod  then i try to write some thing is  not showing at the master pod when master comes up.. What cloud be the reason. Thanks in advance.
