### ISSUE TITLE
[stable/airflow] No host supplied for Airflow logs

### ISSUE THREAD

**Issue by ramkrishnan8994** [helm/charts#17483]
```
*** Log file does not exist: /usr/local/airflow/logs/<task_name>/2019-09-23T17:02:47+00:00/5.log
*** Fetching from: http://:8793/log/<task_name>/2019-09-23T17:02:47+00:00/5.log
*** Failed to fetch log file from worker. Invalid URL 'http://:8793/log/<task_name>/2019-09-23T17:02:47+00:00/5.log': No host supplied
```
Any idea why this happens? The log is available in the backend though. I exec into the worker pod and I was able to fetch the logs, but it is not available in the Web UI.

@stevenmanton @gsemet @mohannadbanayosi

**Comment by stevenmanton** [comment]
Is that log file available in the web pod? I think the default is to use a PVC for the logs that's mounted on all the pods (web, scheduler, and workers), but maybe that has failed somehow.

**Comment by ramkrishnan8994** [comment]
> Is that log file available in the web pod? I think the default is to use a PVC for the logs that's mounted on all the pods (web, scheduler, and workers), but maybe that has failed somehow.

We've created PVCs only for the Worker pods and not the Scheduler/Web pods as the logs are present on the workers only

**Comment by ramkrishnan8994** [comment]
> Maybe a side effect of the recent rework on the worker's logs. If you can dig into this issue and identify the culprit (maybe a default value not set), that would help us a lot

Can you elaborate more on the work on the worker logs?

**Comment by ramkrishnan8994** [comment]
@stevenmanton @gsemet -
https://www.astronomer.io/blog/7-common-errors-to-check-when-debugging-airflow-dag/

Number 6 in the above link is exactly whats happening. Any thoughts?

**Comment by chuyuou** [comment]
I have came across the issue as well, any thoughts on it?
