### ISSUE TITLE
[stable/mongodb] liveness probe doesn't allow long running recovery

### ISSUE THREAD

**Issue by jonnylangefeld** [helm/charts#17501]
**Describe the bug**
The liveness probe fails if there is a long running recovery (mongodb catching up on the oplog). As a result kubernetes kills the pod, it gets restarted and begins recovery again and gets stuck in an endless cycle. Of course we could just increase `livenessProbe.initialDelaySeconds` but in our case (and I assume others as well) we have rather large production data bases for which we can't predict the recovery duration. We would like the liveness Probe to report liveness even during recovery.

[This issue](https://github.com/bitnami/bitnami-docker-mongodb/issues/87) in the bitnami-docker-mongodb repository is the exact same problem, but there they didn't find a solution, they just closed it because it didn't happen anymore for the issuer.

We found a solution and I'll open up a PR.

**Version of Helm and Kubernetes**:
helm: v2.14.3
kubernetes: v1.14.6

**Which chart**:
stable/mongodb

**What happened**:
endless reboot loop of pod in case of long running recovery

**What you expected to happen**:
liveness probe report liveness even during recovery but readiness only reports readiness after recovery

**How to reproduce it** (as minimally and precisely as possible):
Have a rather large database and a replicaset of mongo instances deployed. Then delete the primary pod, let it respawn and watch it recover. If during that time the liveness probe fails often enough, the pod gets deleted by kubernetes and restarts even though it was healthy

**Anything else we need to know**:

**Comment by carrodher** [comment]
Thanks for the PR, I am reviewing it, as you linked both cases, once the PR is merged this issue will be closed automatically.
