### ISSUE TITLE
Chart request: Clair

### ISSUE THREAD

**Issue by bbriggs** [helm/charts#1750]
FEATURE REQUEST:
  - Helm chart for [CoreOS/Clair](https://github.com/coreos/clair)

Clair is an open source project for the static analysis of vulnerabilities in application containers (currently including appc and docker).

1. In regular intervals, Clair ingests vulnerability metadata from a configured set of sources and stores it in the database.
1. Clients use the Clair API to index their container images; this parses a list of installed source packages and stores them in the database.
1. Clients use the Clair API to query the database; correlating data is done in real time, rather than a cached result that needs re-scanning.
1. When updates to vulnerability metadata occur, a webhook containing the affected images can be configured to page or block deployments.

I am already writing a Clair chart for use internally at work and would like to know if the Charts maintainers feel that the kubernetes/charts repo could benefit from having a Clair chart.

**Comment by unguiculus** [comment]
A Clair chart would be very welcome. Looking forward to it.

**Comment by ghost** [comment]
There is already a Helm chart out there https://github.com/coreos/clair/tree/3617b7a12646d9d5f68ec057ed327b2f16ffeafb/contrib/helm/clair

**Comment by bbriggs** [comment]
Well, I got derailed on the clair chart at work (job change) buuuuuut I can take th existing one that @arno01 helpfully pointed out and adapt it for this package repo.

**Comment by ghost** [comment]
Would not it be an unnecessary effort to maintain a Clair chart additionally here?
I think it is wiser to keep polishing it under an official tree.

Please correct me if I am wrong.

**Comment by bbriggs** [comment]
My only motivation for it would be so that people would be able to do a `helm install ...` from official repos, but if that's not what folks want, then there's no point in it.

**Comment by ghost** [comment]
Well, that would actually be a ``helm install ...`` from the official Clair repo :-)

I think this can be closed and reopened in case someone has a different opinion on that.
