### ISSUE TITLE
prometheus operator persistance volume

### ISSUE THREAD

**Issue by hitesh1907nayyar** [helm/charts#17504]
Hi, 

I am presently using prometheus-operator chart to install prometheus and grafana using helm. I need to attach persistence volume to prometheus pod so that it save data. After modifying the storage spec of Prometheus to the below for azure: 

    ## Prometheus StorageSpec for persistent data
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md
    ##
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: managed-premium
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi 
        selector: {}
Then ran the command :

helm upgrade --install --namespace monitoring prometheus stable/prometheus-operator -f "D:\MACHINE LEARNING\Kubernates Microservices\prometheusoperator.yaml"

i am having problem as i am not able to attach the persistance volume as one of the pod come to pending state:

D:\MACHINE LEARNING\Kubernates Microservices>kubectl get all -n monitoring
NAME                                                         READY   STATUS    RESTARTS   AGE
pod/alertmanager-prometheus-prometheus-oper-alertmanager-0   2/2     Running   0          56s
pod/prometheus-grafana-798d5675bf-r2htt                      3/3     Running   0          62s
pod/prometheus-kube-state-metrics-8d4c686fb-4fn96            1/1     Running   0          62s
pod/prometheus-prometheus-node-exporter-8mscb                1/1     Running   0          62s
pod/prometheus-prometheus-node-exporter-j7stw                1/1     Running   0          62s
pod/prometheus-prometheus-node-exporter-q4vwx                1/1     Running   0          62s
pod/prometheus-prometheus-oper-operator-84c55ddf4-2xwbz      1/1     Running   0          62s
pod/prometheus-prometheus-prometheus-oper-prometheus-0       0/3     Pending   0          46s

Can someone please help me to attach the persistance volume to prometheus-operator for prometheus.

**Comment by MahajanTushar** [comment]
You can firstly create at disk at azure, then create a PV mentioning the URL of the disk you created at azure and then map this volume name to PVC that prometheus-prometheus-prometheus-oper-prometheus pod is looking for

**Comment by jrodguitar** [comment]
I'm experiencing the same issue. No matter how my yml looks, i get the same Pending behaviour. Which is due to the fact that the pod has unbound immedite PersistenVolumeClaims.
But somehow in my nfs share, i can see how the prometheus-db folder gets created

**Comment by jrodguitar** [comment]
There is something about the storageClass that is used.
when i used the efs-provisioner chart (which does a lot of the underlying work for the PVC) things works as expected.

**Comment by jrodguitar** [comment]
Let me explain what might be happening, and why via the efs-provisioner works, and our manual steps didnt work.
The efs-provisioner way works, because 2 reasons:
1) it creates a share which the pod can read/write to. 
2) a gid gets created in the pod, such that members of that group can read/write
this annotation is the trick to it
```yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  annotations:
    pv.beta.kubernetes.io/gid: "40000"
```
more info at: https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#access-control 
So when i specify that annotation, the pod has the proper permissions because the gid 40000 is now in the pod. and the member of the 40000 gid can do what they are allowed to do in the share.

**Comment by Jojoooo1** [comment]
I have the same issue can not attach persistence volume to prometheus either by create PV and PVC as explained in documentation or either by modifying the prometheus.prometheusSpec.storageSpec.volumeClaimTemplate using either selector or volumeName
