### ISSUE TITLE
Kubernetes-Dashboard

### ISSUE THREAD

**Issue by hitesh1907nayyar** [helm/charts#17505]
Hi, 

I am running the kubernetes dashboard chart with the below command:

helm install stable/kubernetes-dashboard --name my-release --set enableInsecureLogin=true --set service.externalPort=8080

It is getting installed properly but when i am running through port forwarding :

kubectl port-forward pod/my-release-kubernetes-dashboard-5f46688c44-2kg2p 8080:8080

and run http://localhost:8080/ui then it is not running and through certificate error:

2019/09/28 08:33:02 Starting overwatch
2019/09/28 08:33:02 Using in-cluster config to connect to apiserver
2019/09/28 08:33:02 Using service account token for csrf signing
2019/09/28 08:33:02 No request provided. Skipping authorization
2019/09/28 08:33:03 Successful initial request to the apiserver, version: v1.12.8
2019/09/28 08:33:03 Generating JWE encryption key
2019/09/28 08:33:03 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2019/09/28 08:33:03 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2019/09/28 08:33:06 Initializing JWE encryption key from synchronized object
2019/09/28 08:33:06 Creating in-cluster Heapster client
2019/09/28 08:33:06 Successful request to heapster
2019/09/28 08:33:06 Auto-generating certificates
2019/09/28 08:33:06 Successfully created certificates
2019/09/28 08:33:06 Serving securely on HTTPS port: 8443
2019/09/28 08:35:08 http: TLS handshake error from 127.0.0.1:52758: remote error: tls: unknown certificate
2019/09/28 08:35:09 http: TLS handshake error from 127.0.0.1:52760: remote error: tls: unknown certificate
2019/09/28 08:35:35 http: TLS handshake error from 127.0.0.1:52986: remote error: tls: unknown certificate
2019/09/28 08:35:35 http: TLS handshake error from 127.0.0.1:52988: remote error: tls: unknown certificate

Can somebody please help as how i can run the kubernates dashboard through port forwarding on localhost through helm.

**Comment by richard-scott** [comment]
Try adding "--namespace kube-system" to your install line. That is the only way I can get mine to start, but then it complains about Heapster not being found.... that is correct, as I don't use Heapster ;-(

To be honest, I've all but given up up on this Chart and now I use this:
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#deploying-the-dashboard-ui
