### ISSUE TITLE
[stable/redis-ha] haproxy - disable exporter

### ISSUE THREAD

**Issue by kfkawalec** [helm/charts#17564]
**Describe the error:**
I do not want to use metrics so I have disabled exporter.
In the case of HAProxy, the conditions are missing and we always has prometheus annotations.

**Which table:**
redis-ha-3.7.13

**What happened:**
Prometheus is always looking for metrics.

**How to play it (as minimal and precise as possible):**
Deploy with HAProxy and disabled indicators. Then check the prometheus scrap status.

**Comment by DandyDeveloper** [comment]
Woops, oversight on my part. Will fix soon.

**Comment by DandyDeveloper** [comment]
Woops, oversight on my part. Will fix soon.

**Comment by kfkawalec** [comment]
Any information about this?

**Comment by DandyDeveloper** [comment]
@kfkawalec Just made a quick fix. Pending someone to approve.

**Comment by kfkawalec** [comment]
Where we can expect approve of this merge request?

**Comment by DandyDeveloper** [comment]
@kfkawalec Should get a lgtm today, hopefully.
