### ISSUE TITLE
[stable/rabbitmq-ha] doesn't start with kubernetes 1.16

### ISSUE THREAD

**Issue by matclab** [helm/charts#17561]
**Describe the bug**

**Version of Helm and Kubernetes**:
- minikube v1.4.0
-  Kubernetes v1.16.0 on Docker 18.09.9
- helm v2.14.3 (0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085)

**Which chart**:
- stable/rabbitmq-ha

**What happened**:
```
helm install --name rabbitmq --set "replicaCount=1" stable/rabbitmq-ha
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"
```

**What you expected to happen**:
A successful launch of rabbitmq.

**How to reproduce it** (as minimally and precisely as possible):
Just use kubernetes 1.16 and the aforementioned helm command

**Anything else we need to know**:
Some api were deprecated : https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by EricLemieux** [comment]
I'll make a pr to update the apiVersion.
