### ISSUE TITLE
[stable/spinnaker] typo issue

### ISSUE THREAD

**Issue by Sluggerman** [helm/charts#17591]
**Describe the bug**
PR introduced a small typo https://github.com/helm/charts/pull/16473 at stable/spinnaker/templates/_helpers.tpl

and breaks helm deployment

**Version of Helm and Kubernetes**:
Helm 2, k8s 1.13

**Which chart**:
stable/spinnaker

**What happened**:
kubeConfig  in values.yaml has been referred as kubeconfig (mind capital C) in stable/spinnaker/templates/_helpers.tpl

**How to reproduce it** (as minimally and precisely as possible):
Deploy chart version 1.16.0 or 1.19.0

**Anything else we need to know**:
As workaround, I had to add new set of values:
`kubeconfig:
  encryptedKubeconfig:
`

**Comment by EricLemieux** [comment]
I'll make a pr
