### ISSUE TITLE
[stable/postgresql] cluster took very long to query

### ISSUE THREAD

**Issue by adhinugroho1711** [helm/charts#17595]
Describe the bug
problem took very long time to query when using value-production.yaml

```
...
slaveReplicas: 2
  ## Set synchronous commit mode: on, off, remote_apply, remote_write and local
  ## ref: https://www.postgresql.org/docs/9.6/runtime-config-wal.html#GUC-WAL-LEVEL
  synchronousCommit: "on"
  ## From the number of `slaveReplicas` defined above, set the number of those that will have synchronous replication
  ## NOTE: It cannot be > slaveReplicas
  numSynchronousReplicas: 1
...
```

Version of Helm and Kubernetes:
Helm 2.14.3, k8s 1.15.4

Which chart:
stable/postgresql

What happened:
took very long time for query, ex: to create database when added numSynchronousReplicas > 0, sometimes we must cancel to get it work again

**Comment by juan131** [comment]
Hi @phenom1711 

Thanks so much for reporting it. This issue was already reported at https://github.com/bitnami/charts/issues/1414

We're working on a solution for it and we hope to have it asap. To avoid confusion, we'll continue the discussion in the original issue.

**Comment by phenom1711** [comment]
thank you..this issue is close now...on values-production.yaml and values.yaml change 
`tag: 11.5.0-debian-9-r34 to tag: 11.5.0-debian-9-r59`
