### ISSUE TITLE
[stable/nfs-server-provisioner] pod using nfs pvc doesn't responds after provisioner crash

### ISSUE THREAD

**Issue by candidoma** [helm/charts#17654]
**Describe the bug**
If nfs-server-provisioner pod crash or restart for some reason, all the pods using the nfs storage class remains stucks and are unresponsive.

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

Kubernetes 1.12.6

**Which chart**:
stable/nfs-server-provisioner

**What happened**:
Pod using nfs storage class are unresponsive

**What you expected to happen**:
When nfs-server-provisioner restart all pods using nfs class should be available and responsive.

**How to reproduce it** (as minimally and precisely as possible):
Kill the nfs-server-provisioner and try to list folder mounted into some pod using nfs storage class

**Comment by walec51** [comment]
so this issue was closed because no developer responded to it?

it still an issue no less
