### ISSUE TITLE
[stable/seq] Rollouts get stuck because LMDB doesn't like concurrent clients

### ISSUE THREAD

**Issue by nightkr** [helm/charts#17737]
**Describe the bug**

Trying to start Seq while the old instance is already running will crash with the following exception:

> LightningDB.LightningException: Resource temporarily unavailable

Seq uses a `Deployment` with no `strategy`, so the default is to do a rolling upgrade with surge pods. This will keep crashing, because the new pod can't start while the old pod has locked the database.

This can be fixed by changing Seq to use a `StatefulSet`, by changing the `strategy.type` to `Recreate`, or by changing the `strategy.rollingUpdate.maxUnavailable` to `0`.

**Version of Helm and Kubernetes**:
Helm:

> Client: &version.Version{SemVer:"v2.14.3", GitCommit:"", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

K8s

> Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

stable/seq

**What happened**:

The rollout gets stuck, because the new pod gets stuck in a `CrashLoopBackOff`.

**What you expected to happen**:

The rollout succeeds, and the new pod starts and replaces the old one.

**How to reproduce it** (as minimally and precisely as possible):

```bash
helm upgrade seq stable/seq --install
# Wait for the initial rollout to succeed
kubectl rollout status deploy/seq
helm upgrade seq stable/seq --set baseURI=https://example.com/
# Wait for the new rollout to succeed, but this never happens
kubectl rollout status deploy/seq 
```

**Anything else we need to know**:

**Comment by teozkr** [comment]
c3e446ff96459e74875475746572fea1662dd376 doesn't touch this, so it still applies.

**Comment by teozkr** [comment]
This is still applicable.

**Comment by nblumhardt** [comment]
Thanks for the report and all of the info, @teozkr 👍 - We're a little behind on issues against the Helm chart, we'll do our best to sort this one out ASAP.
