### ISSUE TITLE
[stable/redis-ha] cannot change master group name and activate haproxy

### ISSUE THREAD

**Issue by f-ld** [helm/charts#17745]
**Describe the bug**

**Version of Helm and Kubernetes**:

All

**Which chart**:

stable/redis-ha

**What happened**:

If one changes the master group name
https://github.com/helm/charts/blob/78d5b612ab5be8b2889303b0b49dd3058ad1d91b/stable/redis-ha/values.yaml#L92
then HAProxy cannot find any available master because of static value in haproxy conf
https://github.com/helm/charts/blob/78d5b612ab5be8b2889303b0b49dd3058ad1d91b/stable/redis-ha/templates/_configs.tpl#L166

**What you expected to happen**:

This line should be parameterized: https://github.com/helm/charts/blob/78d5b612ab5be8b2889303b0b49dd3058ad1d91b/stable/redis-ha/templates/_configs.tpl#L166

I bet something like:
```
      tcp-check send SENTINEL\ get-master-addr-by-name\ {{ .Values.redis. masterGroupName }}\r\n
```
but I haven't checked.

**Comment by DandyDeveloper** [comment]
This is being discussed here: https://github.com/helm/charts/pull/17869
