### ISSUE TITLE
[stable/dex] Cannot override config.connections in subchart

### ISSUE THREAD

**Issue by yamaoto** [helm/charts#17768]
I added dex to requriements.yaml with version 2.3.1

and with values:
like 
```yaml
dex:
  config:
    connectors:
    - ldap:
      type: ldap
      id: ldap
      name: LDAP
      config:
#...
```
and getting warning:

> Merging destination map for chart 'dex'. Cannot overwrite table item 'connectors', with non table value: map[]

In original values.yaml of chart https://github.com/helm/charts/blob/d79753641e01f834cd4a87cddda673587ea62e06/stable/dex/values.yaml#L159
connectors property is set like an object. So i think the problem is in there

**Version of Helm and Kubernetes**:
 helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
 - name: dex
   version: 2.3.1
   repository: https://kubernetes-charts.storage.googleapis.com/

**What happened**:
Warning:
Merging destination map for chart 'dex'. Cannot overwrite table item 'connectors', with non table value: map[]

**What you expected to happen**:
Chart successfully installed

**How to reproduce it** (as minimally and precisely as possible):
1. Create new empty chart and add stable/dex to requirements.yaml
2. helm install . --set dex.config.connectors[0].name=ldap

**Anything else we need to know**:

**Comment by deschmih** [comment]
We have the same problem with helm v3, too.

```
$ helm upgrade dex stable/dex -n epu-system -f vaules.yaml
coalesce.go:186: warning: cannot overwrite table with non table for connectors (map[])
Release "dex" has been upgraded. Happy Helming!
```

In the stable/dex values.yaml file connectors are not a map [] !!!! It would be nice if this could be fixed.
