### ISSUE TITLE
/stable/redis cluster_state:fail

### ISSUE THREAD

**Issue by jianzzz** [helm/charts#17769]
I use the latest version of /stable/redis and simply install it, when I check the cluster state, it always shows failed.
```
127.0.0.1:6379> CLUSTER info
cluster_state:fail
cluster_slots_assigned:0
cluster_slots_ok:0
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:1
cluster_size:0
cluster_current_epoch:0
cluster_my_epoch:0
cluster_stats_messages_sent:0
cluster_stats_messages_received:0
```

**Comment by juan131** [comment]
Hi @jianzzz 

Did you modify the **values.yaml** or are you running a simple `helm install stable/redis`?
Could you run the command below?

```console
$ helm search stable/redis
```

What version of Redis reports the command?
