### ISSUE TITLE
[stable/concourse] failure to clean concourse-work-dir without btrfs disk

### ISSUE THREAD

**Issue by samrees** [helm/charts#17803]
**Chart**
stable/concourse

**The Bug**
Launch the chart on any kubernetes without having a storage provider specify btrfs as the fsType, and the concourse-worker pods will fail to start with a clean disk.

You can't clear the concourse workDir with just rm -rf, as attempted to fix by this previous commit. 
https://github.com/helm/charts/commit/4060f5b566f14724909ae7fdc54b09ea0303269f#diff-33a16a0789cde854c77e65e7774aa2beR61

The problem though is that the previous commit assumes the workDir disk is a btrfs disk. On kubernetes clusters with default, like AWS-EBS gp2, its ext4. So without the attached disk being btrfs, you get this.

On a worker pod:
```
# mount | grep work-dir
/dev/xvdcu on /concourse-work-dir type ext4 (rw,relatime,data=ordered)
/dev/loop0 on /concourse-work-dir/volumes type btrfs (rw,relatime,space_cache,subvolid=5,subvol=/)
```

The concourse-worker-init-rm container:
```
    Command:
      /bin/bash
    Args:
      -ce
      for v in $((btrfs subvolume list --sort=-ogen "/concourse-work-dir" || true) | awk '{print $9}'); do
        (btrfs subvolume show "/concourse-work-dir/$v" && btrfs subvolume delete "/concourse-work-dir/$v") || true
      done
      rm -rf "/concourse-work-dir/*"
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
```

```
# btrfs subvolume list --sort=-ogen "/concourse-work-dir"
ERROR: not a btrfs filesystem: /concourse-work-dir
ERROR: can't access '/concourse-work-dir'
# echo $?
1
```

So while the pod terminated cleanly, it didn't infact delete anything. Concourse doesnt seem to like a new worker joining with old state.

**Work Around**
Confirmed working for us.

Make a new storage class for concourse set to fsType: btrfs ala these docs: https://kubernetes.io/docs/concepts/storage/storage-classes/#parameters
And specify the chart to use that storage class here in the values:
https://github.com/helm/charts/blob/master/stable/concourse/values.yaml#L1733

Make sure the underlying kubernetes node has btrfs-progs installed.

**Background**
What you'll actually see: the concourse workers run out of subnets because they think too many containers are running.

```
> fly -t main workers
name                containers  platform  tags  team  state    version  age
concourse-worker-1  256         linux     none  none  running  2.2      59s
concourse-worker-2  249         linux     none  none  running  2.2      23h1m
```

What you'll see in the logs:

```08T19:18:16.751663080Z","level":"info","source":"guardian","message":"guardian.create.create-failed-cleaningup.destroy.delete.finished","data":{"cause":"insufficient subnets remaining in the pool","handle":"fe03bd40-66fa-4919-6b16-ebb63215dec9","session":"637.8.1.1"}}```

Why does this happen? Because I think somethings broken in concourse baggage-claim related to time jobs, like listed here here. https://github.com/concourse/concourse/issues/847 Thats a separate problem upstream with concourse that for some reason the maintainers may not be seeing, probably because they run much more ephemeral concourse workers than this helm chart. Maybe starting new workers with old state in the workDir is the cause of the whole thing. I'm not sure.

In our case, to fix this bug we should just be able to restart the pod and clear out the persistent disk right? Nope. Thus the bug.

**Why this is an issue and not a PR**

Mostly because I just started working on concourse a few weeks ago and have little idea what I'm doing.

So this link lists the problem that concourse workers need disks or there's a problem with ImageGC. https://github.com/helm/charts/tree/master/stable/concourse#persistence 

Ok so the disks are stateful, but thats a problem. _Because new workers need to come up with no state from the previous run of the worker_, as mentioned 
Here:
https://github.com/helm/charts/blob/5a33da9adf31ee802ca6e1247b0b5fdac2bb9aca/stable/concourse/values.yaml#L1060-L1075
Here:
https://github.com/helm/charts/blob/5a33da9adf31ee802ca6e1247b0b5fdac2bb9aca/stable/concourse/values.yaml#L1538-L1540
and this comment here:
https://github.com/concourse/concourse/issues/1194#issuecomment-303424981

Which would bring me to ask why aren't workers done as a standard deployment where by default, the persistent disk would be attached and then deleted when the pod is cycled? That would still provide separate disks but remove the need of the concourse-worker-init-rm container entirely?

Or based on a conversation in concourse's discord, upstream might change away from btrfs entirely and then everything might work fine? 
https://github.com/concourse/concourse/issues/4071

**Comment by pivotal-bin-ju** [comment]
Hi @samrees ,
We are migrating this chart (stable/concourse) to https://github.com/concourse/concourse-chart
Would you mind to reopen an issue there?
