### ISSUE TITLE
[stable/prometheus-mysqld-exporter] Invalid values.yaml file linked in readme

### ISSUE THREAD

**Issue by ghost** [helm/charts#17815]
**Describe the bug**
The `values.yaml` file linked in the readme is a bad config.

**Version of Helm and Kubernetes**:
n/a

**Which chart**:
n/a

**What happened**:
I tried to get a boilerplate prometheus-mysqld-exporter release up using the `values.yaml` file [linked](https://github.com/kilhyunjun/charts/blob/master/stable/prometheus-mysql-exporter/values.yaml) in the readme. I get the following error:
```
Error: render error in "prometheus-mysql-exporter/templates/deployment.yaml": template: prometheus-mysql-exporter/templates/deployment.yaml:40:30: executing "prometheus-

mysql-exporter/templates/deployment.yaml" at <.>: range can't iterate over --collect.global_status, --collect.global_variables, --collect.info_schema.tables, --collect.slave_status
```

**What you expected to happen**:
I expect to see a new prometheus-mysql-exporter deployment.

**How to reproduce it** (as minimally and precisely as possible):
Follow the readme in the prometheus-mysql-exporter chart using the default `values.yaml` provided.

**Anything else we need to know**:
There doesn't seem to be a good way to add/remove collector flags to the release. Both via the `values.yaml` file or the `--set` flag

**Comment by VihanAgarwal97** [comment]
After editing the deployment manually, it looks to be as if the chart is unable to add the new version of flags as per [this](https://github.com/prometheus/mysqld_exporter#collector-flags)

**Comment by nvtkaszpir** [comment]
try:
```yaml
collectors:
  - "--collect.global_status"
  - "--collect.global_variables"
  - "--collect.info_schema.tables"
  - "--collect.slave_status"
```
or use newer chart
