### ISSUE TITLE
[stable/spinnaker] Chart fails to render with or without encryptedKubeConfig

### ISSUE THREAD

**Issue by jzangari** [helm/charts#17810]
**Describe the bug**
When running a helm install of the stable/spinnaker template with a provided values.yaml the install fails in rendering dude to some problem with encryptedKubeconfig and the spinnaker.kubeconfig helper function. 

> Error: render error in "spinnaker/templates/configmap/halyard-config.yaml": template: spinnaker/templates/_helpers.tpl:63:14: executing "spinnaker.kubeconfig" at <.Values.kubeconfig.encryptedKubeconfig>: nil pointer evaluating interface {}.encryptedKubeconfig

**Version of Helm and Kubernetes**:
Helm: 2.14.3
Kubernetes 1.14

**Which chart**:
[stable/spinnaker]

**What happened**:
I am trying to install the helm chart using my values.yaml, and whether I try to use an Encrypted S3 bucket or Kube Secrets I get the same error. 

> Error: render error in "spinnaker/templates/configmap/halyard-config.yaml": template: spinnaker/templates/_helpers.tpl:63:14: executing "spinnaker.kubeconfig" at <.Values.kubeconfig.encryptedKubeconfig>: nil pointer evaluating interface {}.encryptedKubeconfig

**What you expected to happen**:
Spinnaker to install with the expected behavior based on inputs from values.yaml

**How to reproduce it** (as minimally and precisely as possible):
helm upgrade --install --namespace ci --values values.yaml --wait spinnaker stable/spinnaker with kubeconfig.enabled: true 

**Anything else we need to know**:

**Comment by johnsonvino** [comment]
Hi @jzangari ,
I got the same issue because of values.yaml file having **kubeConfig** instead of **kubeconfig** as it is available in the helm template. I changed the values.yaml file to **kubeconfig** and it worked. Please check if that is the issue.

**Comment by arslanbekov** [comment]
Hi @johnsonvino, if you change this variable, it will be ignored and will not fall into `configMap/halyard-config`

**Comment by arslanbekov** [comment]
Hi @EricLemieux, if I understand correctly, then these changes lead to the error above.
https://github.com/helm/charts/commit/2f4d58c751239796b12e0ff7e90a85ee94cdfa3d

**Comment by arslanbekov** [comment]
Fix: https://github.com/helm/charts/commit/2f4d58c751239796b12e0ff7e90a85ee94cdfa3d
