### ISSUE TITLE
MongoDB ReplicaSet TLS support

### ISSUE THREAD

**Issue by saschagrunert** [helm/charts#1782]
Hey there,

How can we add TLS support via secrets to the MongoDB replicaset chart?

Or is it actually possible?

Best,
Sascha

**Comment by unguiculus** [comment]
It would certainly be possible. I'll be happy to review a PR for this.

**Comment by saschagrunert** [comment]
Hm, I had a look at the implementation and I guess we need to create the certs for the hosts during the init of the replicaset. I will see what I can do here.
