### ISSUE TITLE
[prometheus-operator stable/chart] additionalPrometheusRules failled

### ISSUE THREAD

**Issue by modogo2000** [helm/charts#17839]
Hello,

I have this prometheus value file with somme additional rules : 

additionalPrometheusRules:
  - name: kube-state-metrics
    groups:
      - name: kube-state-metrics
        rules:
          - alert: KubePodCrashLoopingZabbix
            expr: rate(kube_pod_container_status_restarts_total{job="kube-state-metrics",pod=~"zabbix-.*"}[15m]) * 60 * 5 > 0
            for: 1h
            labels:
              severity: critical
              type: availability
            annotations:
              description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} is in a crash loop."
              summary: "Container {{ $labels.namespace }}/{{ $labels.container }} crash loop" 

I have this error since this moning : 

template: prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml:28:28: executing "prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace
Error: UPGRADE FAILED: render error in "prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml": template: prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml:28:28: executing "prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace

I don't see whre the error come from 

Best regards

**Comment by Adeelku** [comment]
Hello,
I have the same error
Error: render error in "prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml": template: prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml:28:28: executing "prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml" at <.Release.Namespace>: can't evaluate field Namespace in type interface {}

Could you please check what has been changed in the last version of the template and provide a workaround, solution?
Thanks

**Comment by modogo2000** [comment]
Hello,

When I look into your chart in the version 6.14.2 you add this  : 

metadata:
  creationTimestamp: null
  name: {{ printf "prometheusrules.%s" (.Values.prometheusOperator.crdApiGroup | default "monitoring.coreos.com") }}
  **namespace: {{ .Release.Namespace }}**
  labels:
    app: {{ template "prometheus-operator.name" . }}-operator
{{ include "prometheus-operator.labels" . | indent 4 }}


This value is empty can you fix this or there is a new wau to install and upgrade ?

**Comment by modogo2000** [comment]
It's  working good until --version 6.14.1 
helm install --name promser1--namespace prometheus stable/prometheus-operator --version 6.14.1 --values prometheus.yaml
