### ISSUE TITLE
Difference between stable/redis and stable/redis-ha?

### ISSUE THREAD

**Issue by reloaded** [helm/charts#17845]
What's the difference between `stable/redis` and `stable/redis-ha` because they both spin up a Redis master with slaves?

**Comment by carrodher** [comment]
Please, take a look at [this case](https://github.com/helm/charts/issues/9185) talking about the same topic where some differences where showed, maybe you find the answer there.

In the same way, shortly we will move towards to use distributed repositories, therefore each maintainer can host all the charts they want, therefore there will be many repeated charts (although not in the same repo).
