### ISSUE TITLE
[stable/prometheus] not ready for k8s v1.16.x

### ISSUE THREAD

**Issue by discostur** [helm/charts#17867]
```
Error: validation failed: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"]
``` 

k8s v1.16.x deprecates some old API endpoints ... stable/prometheus is not ready for it.

**Comment by brokenjacobs** [comment]
This is actually an issue in the node-metrics-exporter dependency, which has multiple open PR's with no response to fix this issue:
https://github.com/helm/charts/issues/17358

**Comment by oke-py** [comment]
duplicates of #17267.
#17268 fixes this.

**Comment by discostur** [comment]
@oke-py ok thanks - just witing for the pull request ;)
