### ISSUE TITLE
[incubator/kafka] BROKER_ID needs to be set with KAFKA_SSL_KEYSTORE_LOCATION

### ISSUE THREAD

**Issue by aodj** [helm/charts#17870]
**Describe the bug**
When using the Helm chart for Kafka, the chart contains it's own override to provide the `BROKER_ID` value to the `KAFKA_ADVERTISED_LISTENERS` variable. When using a certificate per _distinct_ broker, the `KAFKA_SSL_KEYSTORE_LOCATION` value also needs to know which certificate/keystore to load.

**Version of Helm and Kubernetes**:
```bash
$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Error: could not find tiller
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.13", GitCommit:"acdb9a03a6dc0f7f62d7acdda75c9a9faca50fee", GitTreeState:"clean", BuildDate:"2019-09-20T23:13:58Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
incubator/kafka

**What happened**:
When setting the `configurationOverrides` value to anything that requires the BROKER_ID, an error is thrown

**What you expected to happen**:
The value to be picked up and passed to the entrypoint as per `KAFKA_ADVERTISED_LISTENERS`

**How to reproduce it** (as minimally and precisely as possible):
Add the following to the `configurationOverrides`: 
```
"ssl.keystore.location": |-
    /etc/ssl/kafka-$((${KAFKA_BROKER_ID}))-keystore.jks
```

The [example value set for `advertised.listeners`](https://github.com/helm/charts/blob/18e1e219362508f3ff831fc98609e16db9349d8d/incubator/kafka/values.yaml#L193-L194) seems to imply that using `kafka-$((${KAFKA_BROKER_ID}))` would work, but it's not obvious that there's extra handling for that variable elsewhere (see below).

**Anything else we need to know**:
[Relevant chart snippet](https://github.com/helm/charts/blob/18e1e219362508f3ff831fc98609e16db9349d8d/incubator/kafka/templates/statefulset.yaml#L192-L210) that adds a specific hack for `KAFKA_ADVERTISED_LISTENERS` to extract the `BROKER_ID`

**Comment by encryptblockr** [comment]
@aodj 
were you able to setup SSL for your kafka?
there is zero documentation for TLS support for this helm charts and interested in a working solution using TLS

can you share what worked for you?

**Comment by aodj** [comment]
@encryptblockr yes, I managed to setup TLS but I ended up forking the helm chart to make the change to ensure that each node could have separate certificates. I did this by adding the following to the statefulset.yaml:

```
...
export KAFKA_SSL_KEYSTORE_LOCATION=${CERTIFICATES_PATH}/kafka-${KAFKA_BROKER_ID}-keystore.jks && \
...
```

By then setting the `CERTIFICATES_PATH` key in the `envOverrides` dict as part of the values.yaml I could inject the path (ie k8s secret mapping) which contained certificates named in the above format.

I went with this solution because I'm working on integrating more closely with the PKI infrastructure in Hashicorp Vault, allowing me to provision short lived certificates. I think it would also be possible to share a server certificate between nodes, avoiding the need to fork and make changes to the helm chart.

Once you've set the `KAFKA_SSL_KEYSTORE_LOCATION` (or `ssl.keystore.location` value) you need to additionally update the values of `listener.security.protocol.map` to ensure that the protocols use the SSL configuration; set `ssl.keystore.password`, `ssl.truststore.location`, `ssl.truststore.password`, and `ssl.client.auth`.

I think that's all the setting you need; there are plenty of resources available that document setting up SSL/TLS for Kafka. 

Let me know if there's any further questions.

**Comment by encryptblockr** [comment]
> to make the change to ensure that each node could have separate certificates

why are you making each node use a separate cert? isn't the plan to have certs to be used by the whole kafka cluster..so all nodes with same certs and then be able to authenticate to the brokers with the same certs? is your fork public? would love to see what you have as final setup/config

i will try what you have above and see how far i get

thanks a lot for sharing

**Comment by aodj** [comment]
> why are you making each node use a separate cert?
I initially started by researching the use of [vaultbot](https://gitlab.com/msvechla/vaultbot) to provision certificates on demand from Hashicorp Vault; as I recall, the working theory was that each node would start, and subsequently call Vault to acquire a certificate, with each one being different, but still valid. I pivoted from this with that same mindset into working with the Helm chart, hence my (slightly unexpected) solution.

The certificates are valid though, since they are signed by the same CA.

> is your fork public? would love to see what you have as final setup/config
Sorry it isn't. It's basically as described above though.

**Comment by encryptblockr** [comment]
@aodj so how do you connect to the kafka brokers using the ssl certs?
would really appreciate it if you could share how you are able to connect using ssl
