### ISSUE TITLE
[stable/prometheus-operator] AdditionalScrapeConfigsExternal documentation

### ISSUE THREAD

**Issue by JessedeJonge** [helm/charts#17886]
Hi, 

I want to add dynamic additionalscrape config to the operator. I generate a list with the transIP api and to add this to my Prometheus configuration I figured I should use a configmap or secret to supply the config to the prometheus instance. Now I noticed, under Prometheusspec there is a key called 'AdditionalScrapeConfigsExternal'. However, I can't find any documentation about this. Is this supposed to be a secret or configmap? How should the cm or secret look like?
Is there any easier way to supply new scrape configs to the prometheusspec? the best way ofcourse would be to use file_sd_config, but I don't see how I would implement this in the Helm Prometheus Operator. Thanks in advance.

**Comment by vsliouniaev** [comment]
When you use the `additionalScrapeConfigs`, the map you provide is turned into a secret, and the Prometheus object is configured to point at the secret. Prometheus Operator does the rest.

When you use `additionalConfigsExternal` the prometheus object is configured identically but the secret is not created - you must do this yourself. The name of the secret and the key of the configuration in the secret must match the name specified in the prometheus object.
