### ISSUE TITLE
[stable/concourse] Suggestion on how to run workers in production

### ISSUE THREAD

**Issue by lukeplausin** [helm/charts#17888]
I am having a lot of issues running concourse in production. Every day it seems to break for some reason.

Usually killing the pods and clearing up volumes is enough to resolve the issue but I've had 6 outages in the last two weeks. I know that it's because of some kind of misconfiguration but it isn't clear to me what I need to do in order to make it work properly.

The concourse and helm chart documentation are rather vague when it comes to how to operate the workers correctly. I understand that they are deployed as a stateful set with a PVC template for volumes, but this has led to issues in the past with node and volume affinity conflicts. A node was dropped in one zone and recreated in another, which caused an outage (the pod would not start due to the volume being in a different zone to the node).

So I've tried another approach, setting the `ephemeral: true` option on the workers template, and switching off persistence so that I don't have problems with volume / node affinity. Now I have all sorts of problems whenever a pod is recreated because concourse assumes that it is the same worker (the pod has the same name) and tries to find volumes which don't exist on the worker. This invariably leads to half of our pipelines going yellow and me getting it in the neck from our developers.

What is the recommended way of running workers in production? Should we have persistence? Would it be reasonable to use PVCs backed by a service which doesn't have the zone affinity issue? (AWS EFS for example). And is it reasonable to try to have ephemeral workers? If the workers are ephemeral, then shouldn't they be deployed with a `deployment` rather than a `stateful set` so that they have randomised pod names?

**Comment by pivotal-bin-ju** [comment]
Hi @lukeplausin ,
We are migrating this chart (stable/concourse) to https://github.com/concourse/concourse-chart.
Would you mind reopening an issue there?
