### ISSUE TITLE
[stable/rabbitmq] add support of extra NodePort

### ISSUE THREAD

**Issue by michaellee8** [helm/charts#17924]
**Is your feature request related to a problem? Please describe.**
I would like to enable plugins like `rabbitmq_mqtt`. However, despite having a `extraPlugins` field to enable the plugins, I can't see anyways to expose it.

**Describe the solution you'd like**
I believe that we may need a `extraPorts` field in the config so that one can expose extra ports manually. 

**Describe alternatives you've considered**
I have also `stable/rabbitmq-ha` but I believe this chart is better maintained.

**Additional context**
I will try to implement a PR for this.

**Comment by alemorcuq** [comment]
Thank you for reporting this and volunteering for making a PR. We have some charts like [Kibana](https://github.com/bitnami/charts/tree/master/bitnami/kibana) and [Wordpress](https://github.com/helm/charts/tree/master/stable/wordpress) that allow users to expose extra ports, just in case you need some guidance.

Regards,
Alejandro

**Comment by michaellee8** [comment]
@alemorcuq I have just submitted the PR with reference from your wordpress chart. I have tested the new config under my microk8s box to ensure the new config works. Please tell me if it gets any extra issues.
