### ISSUE TITLE
[stable/prometheus] Support hostPath storage-volume

### ISSUE THREAD

**Issue by aquavitae** [helm/charts#17940]
I am migrating a custom-built prometheus setup to this chart, and I've encountered a limitation in the options provided for mounting the storage-volume. We run prometheus is HA mode (i.e. two instances) on dedicated kubernetes nodes mounting the data to a hostPath for performance. As far as I can tell there is no way to replicate this design using the current options since the chart explicitly uses either a persistentVolume or an emptyDir.

In my opinion the best way of supporting this kind of configuration is to add a flag to tell the chart not to configure storage at all, then use extraVolumeHostPath to configure it manually. This would address my use case, plus a bunch of other uncommon setups.

The alternative would be to add support for a hostPath in addition persistentVolume and emptyDir, but it wouldn't be as flexible and would only address what I suspect is a single edge case.

**Comment by jcoeltjen** [comment]
You can create persistentVolumeClaims that point to persistentVolumes that use the hostPath storage class.
Then you can pass in the claims using the matching values (e.g. `server.persistentVolume.existingClaim`).

**Comment by aquavitae** [comment]
I guess that is an alternativem but it seems like quite a bit of extra complexity, and also means maintaining an external PersistentVolumeClaim.

**Comment by jcoeltjen** [comment]
Have you considered to use a wrapper chart for that?
This way you could manage your persistent volume and maybe even the volume claim and then use the claim for the wrappred prometheus chart.
