### ISSUE TITLE
[stable/nginx-ingress] Getting issue while passing headers

### ISSUE THREAD

**Issue by DineshSobi** [helm/charts#17952]
**Version of Helm and Kubernetes**: Client: &version.Version{SemVer:"v2.14.1" and 1.13.7-gke.24

**Which chart**: stable/nginx-ingress [v0.24.1]

**What happened**:  Trying to override headers using--set-string but it does not work as expected. It always gives issues with the parsing

`/usr/sbin/helm install --name cx-nginx-1 --set controller.name=cx-nginx-1 --set controller.kind=Deployment --set controller.service.loadBalancerIP= --set controller.metrics.enabled=true --set-string 'controller.headers={"X-Different-Name":"true","X-Request-Start":"test-header","X-Using-Nginx-Controller":"true"}' .
Error: release cx-nginx-1 failed: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadMapCB: expect { or n, but found [, error found in #10 byte of ...|","data":["\"X-Diffe|..., bigger context ...|{"apiVersion":"v1","data":["\"X-Different-Name\":\"true\"","\"X-Request-Start|...`

**What you expected to happen**: I want to override the header which the there by default in vaules.yam with custom headers

**How to reproduce it** (as minimally and precisely as possible):
I have provided the comment to reproduce, 
`helm install --name cx-nginx-1 --set controller.name=cx-nginx-1 --set controller.kind=Deployment --set controller.service.loadBalancerIP= --set controller.metrics.enabled=true --set-string 'controller.headers={"X-Different-Name":"true","X-Request-Start":"test-header","X-Using-Nginx-Controller":"true"}' .`

Kindly help me to pass the headers on right way.

**Comment by DineshSobi** [comment]
Still, I could not fix this

**Comment by thaniyarasu** [comment]
I don't prefer nginx-ingress in GKE.
use GCLB in GKE
