### ISSUE TITLE
Elastalert-  Load rules from configmap

### ISSUE THREAD

**Issue by smimenon** [helm/charts#17998]
What happened:
How to load rules from configmap rather then polluting values.yaml file? Is there a way?

Created a folder rules and added rule files here and tried something like this
kubectl create configmap elastalert-elastalert-rules --from-file rules/ --namespace platform  -o yaml --dry-run | kubectl apply -f -

But that doesn't work becuase deployment chart in the template has this
- name: rules
          configMap:
            name: {{ template "elastalert.fullname" . }}-rules
            items:
{{- range $key, $value := .Values.rules }}
            - key: {{ $key }}
              path: {{ $key}}.yaml

Is there a cleaner way to do this? When I create a configmap from not using values.yaml, the key and path is not populated since values.yaml doesn't have it. Is there a better solution for this?

**Comment by critaL** [comment]
I'd also like to know this.

**Comment by jdfree** [comment]
I could use it as well.
