### ISSUE TITLE
[stable/concourse] namespace creation is not very optional

### ISSUE THREAD

**Issue by jonkerj** [helm/charts#18008]
**Describe the bug**
When setting `concourse.web.kubernetes.createTeamNamespaces: false`, namespaces are not created. But, `web-rolebindings.yaml` does not contain a proper conditional to survive the absence of team namespaces, thus causing tiller to error:

```
$ helm install --set concourse.web.kubernetes.createTeamNamespaces=false stable/concourse
Error: release concourse failed: namespaces "concourse-main" not found
```

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
`stable/concourse`

**What happened**:
See above

**What you expected to happen**:
Concourse to deploy

**How to reproduce it** (as minimally and precisely as possible):
See above

**Anything else we need to know**:
As the fix is fairly trivial, I'm writing a PR to fix this, hold tight.

**Comment by pivotal-bin-ju** [comment]
Hi @jonkerj  ,
We are migrating this chart (stable/concourse) to https://github.com/concourse/concourse-chart
Would you mind reopening an issue there?

**Comment by jonkerj** [comment]
I already did six days ago: https://github.com/concourse/concourse-chart/issues/3
