### ISSUE TITLE
[stable/chart/jenkins] slave pod creation fails with persistentvolumeclaims is forbidden

### ISSUE THREAD

**Issue by bassplay3r** [helm/charts#18037]
**Describe the bug**

After this commit [stable/jenkins] Add pvc permissions to role (#17973) 

jenkins fails start slave pods with
 
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default/api/v1/namespaces/test/persistentvolumeclaims. Message: Forbidden!Configured service account do
esn't have access. Service account may have been revoked. persistentvolumeclaims is forbidden: User "system:serviceaccount:test:quaffing-arachnid-jenkins" cannot create resource "persistentvolumeclaims" in
API group "" in the namespace "test".

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1",
Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4",
Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
helm/chart/stable/jenkins

**What happened**:
Deployed as I normally do but when a build was created the master is forbidden from creating PVCs so pod creation fails 

**What you expected to happen**:
Slave pods would start

**How to reproduce it** (as minimally and precisely as possible):
See the attached debug log

**Anything else we need to know**:
Cluster is onprem created with kubespray

Attached is a dry-run with debug. 
[debug.log](https://github.com/helm/charts/files/3734441/debug.log)

**Comment by rockernaxo** [comment]
Same issue here. Any suggestions?

**Comment by bassplay3r** [comment]
I just found out that since I'm using the curated chart as a dependency I was pulling an old chart, 1.5.0. Changed my requirements.yaml file to point to the latest version, ran helm dependency update and I can now create slave pods  This was verified by installing a new test instance of Jenkins, I've not tried to do helm upgrade on my production instance

**Comment by torstenwalter** [comment]
@bassplay3r Reading your comment it sounds like we can close the issue or is there anything left to do?

**Comment by torstenwalter** [comment]
@maorfr I think this can be closed.
