### ISSUE TITLE
[stable/prometheus-operator] NetworkTransmitErrors alert potentially too sensitive

### ISSUE THREAD

**Issue by sdanbury** [helm/charts#18032]
**Describe the bug**

Using prometheus-operator helm installation and the following query is triggering an alarm for every node in my cluster:

![image](https://user-images.githubusercontent.com/935985/66906851-42a0a000-f000-11e9-8bb6-bd1aecc659d9.png)

It seems to suggest that there is always going to be a non-0 value returned by this query. So either there is a problem at the networking layer on all of my nodes, or alerting on > 0 might be too restrictive and not allow for a natural/minor level of network transmit errors.

I noticed that there is a node_exporter mixin as well which seems to have the following alert:

https://github.com/prometheus/node_exporter/blob/855a1f1d18b82f24c1e517da44ef36f2ffa35b19/docs/node-mixin/alerts/alerts.libsonnet#L176

Would be good to hear your view on whether we should bump > 0 to > 0.1 or > 0.5 in the query?

**Version of Helm and Kubernetes**:

Kubernetes: 1.10
Helm: 2.10.0

**Which chart**:
stable/prometheus-operator

**Comment by vsliouniaev** [comment]
@sdanbury, all alerts and dashboards are sourced from upstream repos and just synced into the chart. Please raise the relevant issues there. Please see this section: https://github.com/helm/charts/tree/master/stable/prometheus-operator#developing-prometheus-rules-and-grafana-dashboards

**Comment by sdanbury** [comment]
Thanks! Apologies, closing.
