### ISSUE TITLE
[stable/external-dns] Deploying in rancher cluster role function splitn not defined

### ISSUE THREAD

**Issue by MaxDiOrio** [helm/charts#18057]
Just went to re-deploy external-dns using the helm chart within Rancher but get the following error:

Wait helm template failed. Error: parse error in "external-dns/templates/clusterrole.yaml": template: external-dns/templates/clusterrole.yaml:40: function "splitn" not defined : exit status 1

Correlates to this line:
- {{ $api := splitn "/" 2 .Values.crd.apiversion }}{{ $api._0 }}

**Comment by juan131** [comment]
Hi @MaxDiOrio 

Could you share the **values.yaml** or the parameters you're using to deploy the Helm chart through Rancher? 

Could you please also share the version of Helm that Rancher is using to deploy the charts? The `splitn` function is part of the Sprig functions (an extension of Go-templates functions used on Helm) and it has been available in Helm for a while. Therefore, it's likely you're using a very old version of Helm to deploy your charts. More info in the link below: 

http://masterminds.github.io/sprig/string_slice.html

**Comment by MaxDiOrio** [comment]
The values.yaml file is empty, using the answers.yaml file:

I have tried with and without the port on the apiUrl value.

{"pdns.apiKey":"k8s","dns.apiUrl":"http://10.85.160.3:8081","provider":"pdns","rbac.create":"true","registry":"txt","source":"service","txtOwnerID":"infratest"}

 It uses Helm v2.10.0-rancher11

**Comment by armsnyder** [comment]
I installed the v2.6.4 version of the `external-dns` chart as a workaround.

**Comment by juan131** [comment]
> It uses Helm v2.10.0-rancher11

That's a pretty old version of Helm. Please note the latest version of Helm is **2.15.0** (see https://github.com/helm/helm/releases), therefore it's likely to find incompatibilities with some of the features we included in the recent versions of the chart.

**Comment by erictt** [comment]
I have met the same error and have tried with 2.11.0 and 2.16.0. didn't work.
