### ISSUE TITLE
[stable/prometheus] is not compatible with the changes in K8s v1.16

### ISSUE THREAD

**Issue by avarf** [helm/charts#18076]
**Describe the bug**
Prometheus (stable/prometheus) is not compatible with the changes in K8s v1.16. In the past I was able to easily install prometheus via below command:
```
helm install --name prometheus stable/prometheus -f prometheus-values.yaml --namespace monitoring
```
But after migrating to K8s v1.16 I face below error:
```
Error: validation failed: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"]
```
This is an error related to changes in the latest k8s.

**Version of Helm and Kubernetes**:
```
kubectl version

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
```
helm version

Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**Which chart**:

**What happened**:
stable/prometheus

**What you expected to happen**:
I expect that prometheus can be installed on k8s v1.16

**How to reproduce it** (as minimally and precisely as possible):
Try to install it on a cluster with the latest Kubernetes.

**Anything else we need to know**:

**Comment by jingerbread** [comment]
Hi, avarf, also faced this issue. Used hack from [https://github.com/helm/helm/issues/6374 ](Helm init fails on Kubernetes 1.16.0 #6374), see comment: [https://github.com/helm/helm/issues/6374#issuecomment-533853888].

**Comment by avarf** [comment]
Hi jingerbread, thank you for the link, I will try it.

**Comment by oke-py** [comment]
ref: #17267 #17268

**Comment by avarf** [comment]
@oke-py thank you for the links, I used your changes and now I can install the Prometheus.

Another question that maybe you can help me with it too. After installation I also installed Grafana but when I imported the dashboards that are working with older versions of k8s, they showed nothing. I think it is again because of changes in the API that there is no reading for the deployments, statefulsets, etc. Do you know how I can fix that?

**Comment by oke-py** [comment]
@avarf What dashboards aren't working?
I don't know dashboards so much, but in my minikube, `Prometheus 2.0 Stats dashboard` and `Prometheus Stats` are showing metrics.
