### ISSUE TITLE
[stable/mediawiki] Don't force creation of https port

### ISSUE THREAD

**Issue by nesl247** [helm/charts#18087]
**Is your feature request related to a problem? Please describe.**
The https port is always created in the service

**Describe the solution you'd like**
The https port should not always be created. This doesn't service a purpose when using istio, and given istio's issues with Services with the same port name, it may cause a problem.

**Comment by juan131** [comment]
Hi @nesl247 

You're right. There are many scenarios where opening this port doesn't add any value (e.g. when you're handling TLS through an Ingress Controller). Could you please submit a PR addressing this issue? I'll be glad to review it.
