### ISSUE TITLE
Prometheus Operator failed to scrape k8 components 

### ISSUE THREAD

**Issue by cyperplex** [helm/charts#18082]
Hi, ive deployed the Prometheus Operator into my cluster with little changes .  The service discovery  piece for :

- monitoring/prometheus-operator-kube-scheduler/0 
- monitoring/prometheus-operator-kube-etcd/0
- monitoring/prometheus-operator-kube-controller-manager/0

![image](https://user-images.githubusercontent.com/28492556/67023010-02254d00-f0fa-11e9-8973-b4bb6298538b.png)

Im wondering if there is an additional step that is needed to allow the components to discover the services in kube-system correctly?

Ive tested to ensure there are no rbac or network acls that could be blocking the service monitors from finding the target services . 

Any help or guides would be appreciated.

**Comment by nvtkaszpir** [comment]
Please define `my cluster`, like is is a managed service from cloud provider etc.
Why? Some cloud provider will not allow you to access certain components directly (for example GKE will not allow accessing etcd and some other) so you will need ot just disable certain parameters.

**Comment by cyperplex** [comment]
A cluster i built using Kops, its not a cloud provided cluster.

**Comment by viveksatasiya** [comment]
I am also getting same issue & I have also deployed a cluster using kops on aws. @cyperplex have you got it working?

**Comment by cyperplex** [comment]
Hi, yes i did with the following changes to the helm charts: 

global:
  rbac:
    pspEnabled: true

kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    https: true # https://github.com/coreos/prometheus-operator/issues/982
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
    port: https-metrics

kubeControllerManager:
  enabled: true
  insecureSkipVerify: true
  serviceMonitor:
    selector:
      app: prometheus-operator-kube-controller-manager
  service:
    port: 10252
    targetPort: 10252
    selector:
      k8s-app: kube-controller-manager

kubeproxy:
  enabled: false
  namespace: kube-system 
  service:
    port: 10249
    selector:
      k8s-app: kube-proxy

  serviceMonitor:
    insecureSkipVerify: true
    https: false

kubeScheduler:
  enabled: true
  insecureSkipVerify: true
  serviceMonitor:
    https: false
    selector:
      app: prometheus-operator-kube-scheduler
  service:
    selector:
      k8s-app: kube-scheduler

kubeEtcd:
  enabled: true
  service:
    port: 4001
    targetPort: 4001
    selector:
      k8s-app: etcd-manager-main
  serviceMonitor:
    scheme: https
    insecureSkipVerify: true
    endpoints:
    interval: 15s
    port: https-metrics
    caFile: /etc/prometheus/secrets/etcd-certs/etcd-ca.crt
    certFile: /etc/prometheus/secrets/etcd-certs/etcd-client.crt
    keyFile: /etc/prometheus/secrets/etcd-certs/etcd-client.key
    jobLabel: component
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: exporter-kube-etcd
        component: kube-etcd

**Comment by cyperplex** [comment]
Hi, i did need to modify the values in, here is what worked for me
https://github.com/cyperplex/prom-op/blob/master/values.yaml

**Comment by viveksatasiya** [comment]
@cyperplex thanks for your help. Kubelet scrapping was not working due to 401 forbidden error. I have added following configuration in cluster spec of kops & now it is working fine.

  kubelet:
    authenticationTokenWebhook: true 
    authorizationMode: Webhook

Have you opened 4001 port of etcd for worker nodes to enable scrapping for Prometheus deployed on worker node?

& what about dns-controller?

**Comment by cyperplex** [comment]
_Have you opened 4001 port of etcd for worker nodes to enable scrapping for Prometheus deployed on worker node?_

So in KOPS the ETCD instances run on the masters, we needed to grab the certs and create a secret with them using the following bash script in the CI/CD process 

https://github.com/cyperplex/prom-op/blob/master/bash_scripts

You could run this manually with the values i already provided and it would work.

dns-controller should be core-dns and it should be scraped by default if your leaving the defaults set to true in the prometheus operator chart ie 
defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    general: true
    k8s: true
    kubeApiserver: true
    kubeApiserverError: true
    kubePrometheusNodeAlerting: true
    kubePrometheusNodeRecording: true
    kubernetesAbsent: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeScheduler: true
    network: true
    node: true
    prometheus: true
    prometheusOperator: true
    time: true


referenced in
https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml

**Comment by viveksatasiya** [comment]
@cyperplex Thank you so much for your help.
