### ISSUE TITLE
[stable/mediawiki] Database tables are not created

### ISSUE THREAD

**Issue by nesl247** [helm/charts#18094]
**Describe the bug**
The helm chart does not create the database tables on first run.

**Version of Helm and Kubernetes**:
8.2.7
1.14

**Which chart**:
stable/mediawiki

**What happened**:
Database tables are missing so the pod fails

**What you expected to happen**:
The tables should have been run

**How to reproduce it** (as minimally and precisely as possible):
Generic install

**Comment by juan131** [comment]
Hi @nesl247 

Could you share the **values.yaml** you're using to deploy Mediawiki? I'm unable to reproduce that bug.

**Comment by nesl247** [comment]
I'm using pulumi (think terraform) to apply this, so it uses the default values and overrides them with the following:

```
fullnameOverride: config.project,
    mediawikiUser: 'admin',
    mediawikiPassword: config.vault.ADMIN_PASSWORD,
    mediawikiEmail: 'user@example.com',
    mediawikiName: 'User',
    allowEmptyPassword: 'no',
    externalDatabase: {
      host: database.dnsRecord.fqdn,
      user: database.user.name,
      password: database.user.password,
      database: database.database.name
    },
    mariadb: {
      enabled: false
    },
    service: {
      type: 'ClusterIP'
    },
    persistence: {
      storageClass: 'nfs',
      accessMode: 'ReadWriteMany'
    },
    podAnnotations: {
      'ad.datadoghq.com/wiki.check_names': JSON.stringify(['http_check']),
      'ad.datadoghq.com/wiki.init_configs': JSON.stringify([{}]),
      'ad.datadoghq.com/wiki.instances': JSON.stringify([
        [
          {
            name: config.project,
            url: `https://${config.appDnsHost}/`,
            // eslint-disable-next-line @typescript-eslint/camelcase
            disable_ssl_validation: false
          }
        ]
      ]),
      'ad.datadoghq.com/wiki.logs': JSON.stringify([{ source: config.project, service: config.project }])
    },
```

This is being done on GKE using Cloud SQL (MySQL 5.7) for the database. It always fails to create the `interwiki` table it seems.

```

Oct 18 11:00:21.033 | wiki | production | #9 /opt/bitnami/mediawiki/maintenance/install.php(184): require_once(string)
-- | -- | -- | --
  | Oct 18 11:00:21.033 | wiki | production | #8 /opt/bitnami/mediawiki/maintenance/doMaintenance.php(96): CommandLineInstaller->execute()
  | Oct 18 11:00:21.033 | wiki | production | #7 /opt/bitnami/mediawiki/maintenance/install.php(129): CliInstaller->execute()
  | Oct 18 11:00:21.033 | wiki | production | #6 /opt/bitnami/mediawiki/includes/installer/CliInstaller.php(186): Installer->performInstallation(array, array)
  | Oct 18 11:00:21.033 | wiki | production | #5 /opt/bitnami/mediawiki/includes/installer/Installer.php(1596): DatabaseInstaller->populateInterwikiTable(MysqlInstaller)
  | Oct 18 11:00:21.033 | wiki | production | #4 /opt/bitnami/mediawiki/includes/installer/DatabaseInstaller.php(735): Wikimedia\Rdbms\Database->selectRow(string, string, array, string)
  | Oct 18 11:00:21.033 | wiki | production | #3 /opt/bitnami/mediawiki/includes/libs/rdbms/database/Database.php(1875): Wikimedia\Rdbms\Database->select(string, string, array, string, array, array)
  | Oct 18 11:00:21.033 | wiki | production | #2 /opt/bitnami/mediawiki/includes/libs/rdbms/database/Database.php(1784): Wikimedia\Rdbms\Database->query(string, string)
  | Oct 18 11:00:21.033 | wiki | production | #1 /opt/bitnami/mediawiki/includes/libs/rdbms/database/Database.php(1274): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
  | Oct 18 11:00:21.033 | wiki | production | #0 /opt/bitnami/mediawiki/includes/libs/rdbms/database/Database.php(1556): Wikimedia\Rdbms\Database->getQueryExceptionAndLog(string, integer, string, string)
  | Oct 18 11:00:21.033 | wiki | production | Backtrace:
  | Oct 18 11:00:21.033 | wiki | production | Error: 1146 Table 'wiki.interwiki' doesn't exist (db_host)
  | Oct 18 11:00:21.033 | wiki | production | Function: DatabaseInstaller::populateInterwikiTable
  | Oct 18 11:00:21.033 | wiki | production | Query: SELECT 1 FROM `interwiki` LIMIT 1
  | Oct 18 11:00:21.033 | wiki | production | Error executing 'postInstallation': [1a65e6db6ab485591844351b] [no req] Wikimedia\Rdbms\DBQueryError from line 1587 of /opt/bitnami/mediawiki/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading?
  | Oct 18 11:00:20.664 | wiki | production | mysql-c INFO MySQL server listening and working at db_host:3306
  | Oct 18 11:00:20.609 | wiki | production | mysql-c INFO Found MySQL server listening at db_host:3306
  | Oct 18 11:00:20.591 | wiki | production | mysql-c INFO Trying to connect to MySQL server
  | Oct 18 11:00:19.608 | wiki | production | nami INFO Initializing mediawiki
  | Oct 18 11:00:16.235 | wiki | production | nami INFO mysql-client successfully initialized
  | Oct 18 11:00:16.205 | wiki | production | nami INFO Initializing mysql-client
  | Oct 18 11:00:13.672 | wiki | production | nami INFO php successfully initialized
  | Oct 18 11:00:13.672 | wiki | production | nami INFO Initializing php
  | Oct 18 11:00:13.672 | wiki | production | nami INFO apache successfully initialized
  | Oct 18 11:00:13.672 | wiki | production | nami INFO Initializing apache
```

**Comment by juan131** [comment]
Hi @nesl247 

I noticed you're using an external database (instead of using a MariaDB subchart for the database backend). 

Please note that, when using an external db, the user (`externalDatabase.user`) and database (`externalDatabase.database`) **must exists in your MySQL server before installing the chart**. You also need to ensure the user has all privileges granted on that database and the user's password (`externalDatabase.password`) is correct.

When using MariaDB subchart to do so, we're already configuring the MariaDB server to create that user and database during its initialisation (see https://github.com/helm/charts/blob/master/stable/mediawiki/values.yaml#L108)

**Comment by nesl247** [comment]
@juan131 I am aware that the database and user must exist first, and they do. The user is created via GCP, therefore:

> Users created using Cloud SQL have all privileges except FILE and SUPER. If you need to change the privileges for a user, use the GRANT or REVOKE command in the mysql client.

**Comment by nesl247** [comment]
Hey,

Can you point me to the code that performs the database migrations? Has this chart been tested with mysql at all? Because mediawiki themselves do seem to support it. Though looking at the bitnami stuff, it seems you guys may be hard depending upon MariaDB for some reason.

I'll try to use the helm chart and setup MariaDB to test this out for you.

**Comment by juan131** [comment]
Hi @nesl247 

> Has this chart been tested with mysql at all? Because mediawiki themselves do seem to support it. Though looking at the bitnami stuff, it seems you guys may be hard depending upon MariaDB for some reason.

I'm afraid we only test this chart with MariaDB in our pipeline (which is the "default" database use on the chart). It's true that some web apps support different databases but it's really hard for us to test every possible combination you can choose to deploy the app since we're packaging/testing/releasing these assets on a daily basis.

> Can you point me to the code that performs the database migrations?

It's a little bit hidden in the Mediawiki image but you can find it. Mediawiki image uses [Nami](https://github.com/bitnami/nami) to configure/initialize Mediawiki, PHP, Apache, etc. These Nami modules can be found under the `/root/.nami/components/` path in the image. For instance, to find the logic that initializes Mediawiki, check the scripts below:

- /root/.nami/components/com.bitnami.mediawiki/main.js
- /root/.nami/components/com.bitnami.mediawiki/helpers.js

Command:

```console
$ docker run --rm -it bitnami/mediawiki cat /root/.nami/components/com.bitnami.mediawiki/helpers.js
```

**Comment by nesl247** [comment]
I do understand that it can be difficult, but given MySQL is historically the primary database, and also what is generally provided by cloud providers such as AWS and GCP, I would advise testing against it as well.

You also have some big inconsistencies in your code. In some places you refer to stuff as `MARIADB_HOST` and some places you mention `MYSQL_*`.

MariaDB is also not listed as a requirement for this chart. So if it's going to only be tested with MariaDB, or only work with it, the documentation should probably be updated to reflect that.

I'm looking at that code, and it seems like you guys are hardcoding mariadb as the database type. This is likely the reason.

```
'use strict';

const _ = require('lodash');
const handlerSelector = require('./lib/handlers/selector');
const volumeFunctions = require('./lib/volume')($app);
const componentFunctions = require('./lib/component')($app);

$app.postInstallation = function() {
  const webserverHandler = handlerSelector.getHandler('webServer', 'apache', {cwd: $app.installdir});
  webserverHandler.addAppVhost($app.name, {type: 'php'});
  if (!volumeFunctions.isInitialized($app.persistDir)) {
    const databaseHandler = handlerSelector.getHandler('database', {
      variation: 'mariadb', // HERE
      name: $app.databaseName,
      user: $app.databaseUser,
      password: $app.databasePassword,
      host: $app.databaseServerHost,
      port: $app.databaseServerPort,
    }, {cwd: $app.installdir});
    databaseHandler.checkConnection();
    $app.helpers.installApplication(databaseHandler);
    $file.substitute('LocalSettings.php', '$wgScriptPath = "/wiki";', '$wgScriptPath = "";');
    $app.helpers.setAdminMail(databaseHandler);
    $file.substitute('LocalSettings.php', /\$wgEnableUploads\s*=\s*false;/, '$wgEnableUploads = true;');
    $app.helpers.configureSMTP();
    volumeFunctions.prepareDataToPersist($app.dataToPersist);
  } else {
    volumeFunctions.restorePersistedData($app.dataToPersist);
    const databaseInfo = $app.helpers.getDatabaseProperties();
    if (databaseInfo.type === 'mysql') databaseInfo.type = 'mariadb'; // AND HERE
    const databaseHandler = handlerSelector.getHandler('database', {
      variation: databaseInfo.type,
      user: databaseInfo.username,
      password: databaseInfo.password,
      host: databaseInfo.host,
      port: !_.isUndefined(databaseInfo.port) ? databaseInfo.port : $app.databaseServerPort,
    }, {cwd: $app.installdir});
    databaseHandler.checkConnection();
    $app.helpers.updateDatabase();
  }
  $file.delete('mw-config');
  componentFunctions.configurePermissions($app.persistDir, {
    user: webserverHandler.user,
    group: webserverHandler.group,
  });
  componentFunctions.printProperties({
    'Username': $app.username,
    'Password': $app.password,
    'Email': $app.email,
    'Wiki Name': $app.wikiName,
  });
};
```

**Comment by nesl247** [comment]
I think I figured out the problem. Cloud SQL does not support MyISAM. I can't be 100% certain yet that this is the cause, but when I try to load the `tables.sql` in, I get an error about it.

Do you know if anything is done to select the DB engine or if there are any issues with that?

**Comment by juan131** [comment]
Hi @nesl247 

> Do you know if anything is done to select the DB engine or if there are any issues with that?

I don't know what's the `install.php` script doing. The function below is the one that's giving you the error:

```
$app.helpers.installApplication = function(databaseHandler) {
  if ($app.password.length < 10) {
    throw new Error('Application password should be at least 10 characters long.');
  }
  const installationSettings = [
    $app.wikiName,
    $app.username,
    '--pass', $app.password,
    '--dbname', databaseHandler.connection.name,
    '--dbpass', databaseHandler.connection.password,
    '--dbserver', databaseHandler.connection.host,
    '--dbuser', databaseHandler.connection.user,
    '--installdbuser', databaseHandler.connection.user,
    '--installdbpass', databaseHandler.connection.password];
  php.execute('install.php', installationSettings, {cwd: $file.join($app.installdir, 'maintenance')});
};
```

As you can see, it's taking the database settings (and user settings) and invoking the `install.php` script.

**Comment by nesl247** [comment]
Yeah I saw, I found out after my comment that mediawiki does not work with Cloud SQL due to mediawiki requiring MyISAM. I'm going to go ahead and close this ticket out and we're looking into a different wiki solution.

Thanks for your help!
