### ISSUE TITLE
[stable/redmine] Error executing 'postInstallation': Group '99' not found

### ISSUE THREAD

**Issue by eduard0lima** [helm/charts#18118]
**Describe the bug**
I am getting the error "Error executing 'postInstallation': Group '99' not found" on Redmine pod when installing chart.

**Version of Helm and Kubernetes**:
K8s version: v1.11.0 + d4cacc0
Helm version: v2.14.3

**Which chart**:
stable/redmine

**What happened**:
After installing the redmine chart, the installation was successful, madriadb's POD went up successfully, but redmine's POD gives the following error:

`
Welcome to the Bitnami redmine container
--
  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
  |  
  | nami    INFO  Initializing redmine
  | redmine INFO  Redmine has been already initialized, restoring...
  | mysql-c INFO  Trying to connect to MySQL server
  | mysql-c INFO  Found MySQL server listening at redmine-mariadb:3306
  | mysql-c INFO  MySQL server listening and working at redmine-mariadb:3306
  | redmine INFO  Generating new secret...
  | redmine INFO  Migrating database...
  | Error executing 'postInstallation': Group '99' not found

`

**What you expected to happen**:
I hoped that the Redmine POD could create the necessary data structure in the database.

**How to reproduce it** (as minimally and precisely as possible):
Run the following command:
`helm install -f values.yaml --namespace redmine --name redmine stable/redmine`

**Anything else we need to know**:
File "[values.yaml](https://github.com/eduard0lima/charts/blob/master/values.yaml)"

**Comment by javsalgar** [comment]
Hi,

Which kind of storage are you using in your system? It seems to me that the issue comes with an invalid chmod/chown operation.

**Comment by eduard0lima** [comment]
> Hi,
> 
> Which kind of storage are you using in your system? It seems to me that the issue comes with an invalid chmod/chown operation.


Im using NFS with a Storage Class.

**Comment by javsalgar** [comment]
Hi,

Could you confirm that the issue appears in the deployment when persistence is set to false? This way we can confirm that the issue is due to the storage class that has some incompatibility with the chmod/chown operations

**Comment by eduard0lima** [comment]
> Hi,
> 
> Could you confirm that the issue appears in the deployment when persistence is set to false? This way we can confirm that the issue is due to the storage class that has some incompatibility with the chmod/chown operations

Hi,

When persistence is set to false, the error does not occur and Redmine works correctly.

Even without choosing the "storageClass" option we get the error "Group '99' not found".
