### ISSUE TITLE
[stable/rabbitmq] Invalid username, password logging on to management plugin

### ISSUE THREAD

**Issue by mathias-ewald** [helm/charts#18129]
**Describe the bug**
When RabbitMQ starts and I forward a port to the container like `kubectl port-forward -n my-ns my-ns-rabbitmq-0 15672:15672`, I cannot login with the username "user" and password. I take the password from the secret "my-ns-rabbitmq" and base64 decode the password.

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.9-gke.3", GitCommit:"cf98c87ae263ea1b75e03d11251acdb958286c9d", GitTreeState:"clean", BuildDate:"2019-08-12T23:00:17Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/rabbitmq, version 6.8.5

**What happened**:
I noticed I cannot login on the management UI. Checking the logs, I see the following appearing in regular intervals and when I attempt to login on the UI. The health checks fail constantly and cause a restart of the container.

`2019-10-19 10:25:15.680 [warning] <0.687.0> HTTP access denied: user 'user' - invalid credentials`

**How to reproduce it** (as minimally and precisely as possible):
Just start the Helm chart. I changed no configuration.

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue. I just deployed the chart and I was able to log in without issues.

As you can see, there were no restarts

```
❯ kubectl get pods
NAME                    READY   STATUS    RESTARTS   AGE
funny-goat-rabbitmq-0   1/1     Running   0          122m
```

And the interface is available

![image](https://user-images.githubusercontent.com/1133777/67276942-fead0f80-f4c5-11e9-970f-893965f6263b.png)

**Comment by lambohamp** [comment]
Hi @mathias-ewald ,

I've been facing the same issue. Try using a different name for your helm chart. For instance, when I installed it with `helm install --name rabbitmq stable/rabbitmq` - the authentication has always failed. But when I tried `helm install --name queue stable/rabbitmq` - it worked fine. The automatically generated names work fine as well.

Hope it helps.

**Comment by javsalgar** [comment]
Hi,

I tried with name rabbitmq and saw no issues either

![image](https://user-images.githubusercontent.com/1133777/67553181-e1b64d80-f70c-11e9-91e4-108053e59474.png)

```
❯ kubectl get pods
NAME         READY   STATUS    RESTARTS   AGE
rabbitmq-0   1/1     Running   0          106s
```

```
❯ helm ls
NAME    	REVISION	UPDATED                 	STATUS  	CHART         	APP VERSION	NAMESPACE
rabbitmq	1       	Fri Oct 25 09:48:25 2019	DEPLOYED	rabbitmq-6.9.0	3.8.0      	default
```

**Comment by lambohamp** [comment]
Hi,

The issue isn't specific to a particular name. I have a couple of AKS clusters and rabbitmq works fine on one of them and doesn't work on another one using the same name (e.g. --name rabbitmq). I've failed to find a reason for that so for now I just stick with randomly generated names.

Anyway, thanks for your help.

**Comment by leeman24** [comment]
I have the opposite issue where the deployment is not respecting the `rabbitmq.password` or my `rabbitmq.existingPasswordSecret`. It lets me login with my username (admin) and the password (password) even though I had another password set (test123).

```
$     echo "Password      : $(kubectl get secret --namespace dev rabbitmq-dev-shared -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"
Password      : test123
```

**Comment by lotuc** [comment]
Pretty frustrating, I'm facing the same problem. It starts normally which means the user is created. But when it's ready, there lists no user.

```sh
$ cat values.yaml
securityContext:
  enabled: true
  runAsUser: 0
  fsGroup: 2000

rabbitmq:
  username: admin
  password: Ta7nPvbmXW

persistence:
  enabled: true
  existingClaim: ufc-test-rabbitmq

$ helm list
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
$ helm install rabbitmq stable/rabbitmq -f values.yaml
NAME: rabbitmq
LAST DEPLOYED: Wed Jan 15 11:24:04 2020
NAMESPACE: ufc-dev
STATUS: deployed
REVISION: 1
... NOTES
$ k get pods -w
NAME         READY   STATUS    RESTARTS   AGE
rabbitmq-0   0/1     Running   0          5s
rabbitmq-0   1/1     Running   0          21s
rabbitmq-0   0/1     Running   0          110s
$ k describe pod rabbitmq-0
...
Events:
  Type     Reason     Age                From                 Message
  ----     ------     ----               ----                 -------
  Normal   Scheduled  <unknown>          default-scheduler    Successfully assigned ufc-dev/rabbitmq-0 to ufc-master
  Normal   Pulled     3m58s              kubelet, ufc-master  Container image "docker.io/bitnami/rabbitmq:3.8.2-debian-9-r31" already present on machine
  Normal   Created    3m58s              kubelet, ufc-master  Created container rabbitmq
  Normal   Started    3m58s              kubelet, ufc-master  Started container rabbitmq
  Warning  Unhealthy  9s (x7 over 3m9s)  kubelet, ufc-master  Readiness probe failed: curl: (22) The requested URL returned error: 401
  Warning  Unhealthy  1s (x4 over 91s)   kubelet, ufc-master  Liveness probe failed: curl: (22) The requested URL returned error: 401
$ k exec -it rabbitmq-0 rabbitmqctl list_users
Listing users ...
# no user listed
```

**Comment by defyjoy** [comment]
I have been struggling with this in the same thing either way with generated names or given name(rabbitmq) and honestly I have no clue why . 

![image](https://user-images.githubusercontent.com/1047068/72832126-44869900-3caa-11ea-8052-a2886b41eef2.png)
