### ISSUE TITLE
[stable/postgresql] Warning when using extraEnv in helm 2.15

### ISSUE THREAD

**Issue by pitwegner** [helm/charts#18145]
**Describe the bug**
After upgrading to helm version 2.15, the `extraEnv` variable throws a warning when set:
```
2019/10/21 02:28:11 Warning: Merging destination map for chart 'postgresql'. Overwriting table item 'extraEnv', with non table value: [map[name:KEY value:value]]
```

**Version of Helm and Kubernetes**:
Helm 2.15

**Which chart**:
stable/postgresql

**What happened**:
Warning is thrown

**What you expected to happen**:
No Warning

**How to reproduce it** (as minimally and precisely as possible):
Deploy chart with extraEnv

**Comment by juan131** [comment]
Hi @pitwegner 

Thanks so much for reporting this! I just created a PR to address it.
