### ISSUE TITLE
[postgres] creates pod that gets stuck with "chown: changing ownership of ‘/var/lib/postgresql/data/pgdata’: Invalid argument"

### ISSUE THREAD

**Issue by greenenergy** [helm/charts#1814]
**BUG REPORT**

**Version of Helm and Kubernetes**:

**_Helm_**:
  ```
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
```

**_Kubernetes_**:
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Which chart**:
postgres (and also gitlab, where I saw it first).

**What happened**:
After installing & creating a PV for the postgres pod, once it connects its PVC to the PV, the pod falls into a crash loop, with `kubectl logs -f <podname>` returning just:

`chown: changing ownership of ‘/var/lib/postgresql/data/pgdata’: Invalid argument`

Literally nothing else is printed - no history up to that message, nothing.

**What you expected to happen**:
A working pod is installed.

**How to reproduce it** (as minimally and precisely as possible):
Just install postgres or gitlab.

**Anything else we need to know**:

**Comment by malcolmm83** [comment]
I'm seeing the same thing with my pod (not postgres), what was your solution?

**Comment by RahulMahale** [comment]
Facing same issue. It takes minutes to run simple `chown` command. Any fixes?

**Comment by marshallford** [comment]
Same issue but using the `bitnami` container image and mount path.

**Comment by Queetinliu** [comment]
I also face this problme when I deploy postgres use nfs as the storage class provisioner,my storage backend is truenas。I solve it by  
setting truenas For no_root_squash, use -maproot="root":"wheel",then all fine.so I think is the permits cause.
