### ISSUE TITLE
[stable/influxdb] Define startup probe in deployment

### ISSUE THREAD

**Issue by reloaded** [helm/charts#18167]
**Describe the bug**
Please define a startup probe in the deployment file so we can easily control pod startup timeouts. Large Influx DBs take a while to start -- right now my influx DB pod consumes 80GB of memory and takes about 48 minutes to cold-start.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes

**Version of Helm and Kubernetes**:
```
jharris@jharris-XPS-15-9570:~/Repository/helm.influxdb$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

```
jharris@jharris-XPS-15-9570:~/Repository/helm.influxdb$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/influxdb

**What happened**:
pod is prematurely restarted by kubernetes when upgrading/installing influxdb chart with a database >= 80GB

**What you expected to happen**:
helm chart to be configured with deployment startup probe support for large databases

**How to reproduce it** (as minimally and precisely as possible):
install the chart with a large influxdb database

**Anything else we need to know**:

**Comment by reloaded** [comment]
Submitted a PR that adds startup probe.
@jackzampolin 
@Aisuko

**Comment by Aisuko** [comment]
Thanks. I'm going to merge ^.
