### ISSUE TITLE
[stable/redis] Read password from globals

### ISSUE THREAD

**Issue by zbikmarc** [helm/charts#18177]
It would be very useful to allow redis read password from globals in similar way it is done for stable/postgresql This would allow to easier setting of it in case redis is used as child.

This feature would be helpful in our situation when we are creating Redis as optional dependecy in case we want to use local Redis cache and not some external one.

**Describe the solution you'd like**
Simialar approach as it is in stable/postgresql:
- [password defined in helper](https://github.com/helm/charts/blob/master/stable/postgresql/templates/_helpers.tpl#L81-L91)
- [include password from template](https://github.com/helm/charts/blob/master/stable/postgresql/templates/secrets.yaml#L13)

**Describe alternatives you've considered**
Alternatively I would consider approach used in some other charts where databases are optional dependencies and then there is separate set for internal and external database settings, however for consistency above approach would be prefered by us.

**Comment by javsalgar** [comment]
Thanks, I just commented in the PR :)
