### ISSUE TITLE
[stable/airflow] airflow install kubernetes

### ISSUE THREAD

**Issue by devopsdymyr** [helm/charts#18178]
**Version of Helm and Kubernetes**:
helm version: v2.14.3
kubernetes: v1.13.10-gke.0

**Which chart**:
stable/airflow

**What happened**:
Not able to configure ingress and not able to access

**What you expected to happen**:

Using ingress need to access airflow

**Comment by gsemet** [comment]
Sorry, bug descript is too vague. Please read carefully the documentation and the comments in the value file, there are plenty of way to configure your ingress
