### ISSUE TITLE
[stable/airflow] How to configure airflow - ingress

### ISSUE THREAD

**Issue by devopsdymyr** [helm/charts#18181]
**Describe the bug**
I have installed airflow using helm with help of stable repository
helm install --namespace "airflow" --name "airflow" stable/airflow

**Version of Helm and Kubernetes**:
helm:
===
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

Kubernetes:
==========
version: v1.13.10-gke.0

**Which chart**:
stable/airflow

**What happened**:
airflow is running verfiyed by using helm status
![image](https://user-images.githubusercontent.com/41105507/67274844-edbcc800-f4de-11e9-92b4-7863d1a53abb.png)

I have configured ingress separately created ingress file.
![image](https://user-images.githubusercontent.com/41105507/67275009-4e4c0500-f4df-11e9-894e-a63a81defe15.png)

**What you expected to happen**:
expected to access airflow using ingress

**How to reproduce it** (as minimally and precisely as possible):
if it possible to add some example file in the helm repository for the ingress, everyone can deploy airflow easily

**Anything else we need to know**:
if you can add details installation steps or notes which will makes more useful

**Comment by devopsdymyr** [comment]
Tested with accessing port-forwarding.which is working file
![image](https://user-images.githubusercontent.com/41105507/67275441-3fb21d80-f4e0-11e9-996f-79de3055f8ff.png)

**Comment by gsemet** [comment]
Maybe something related to the url prefix stip. See comments in [values.yaml](https://github.com/helm/charts/blob/master/stable/airflow/values.yaml#L356).

Feel free to submit an update in the README when you find your answer !
