### ISSUE TITLE
[stable/traefik]  Helm 2.15 checks for ingress status, traefik publishedService not enabled default

### ISSUE THREAD

**Issue by Exodus** [helm/charts#18206]
**Describe the bug**
Helm as of version 2.15, when you use the `--wait` argument, will now wait for the Ingress object to be ready. src: https://github.com/helm/helm/releases/tag/v2.15.0

> Notable Changes
> ...
> `--wait` now waits for ingress hosts to become ready

Traefik previous to version 1.7 apparently didn't support updating the ingress status, resulting in an empty ingress status, thus, failing your helm upgrade if it contained an ingress object. Tiller just complains that the ingress is not ready (as this is now checked by helm: https://github.com/helm/helm/commit/1d95d8396bd57d26ce98a001526b495c0bb413a5#diff-d18c4d83690679deed0c84f55bf476bdR283)

In traefik 1.7, you should add the publishedService to your traefik configuration so it may be able to update the ingress object and effectively set it's status to ready, so helm doesn't fail. This should be enabled by default now to support the behaviour in helm 2.15

```
[kubernetes]
  [kubernetes.ingressEndpoint]
    publishedService = "traefik/traefik"
```
`traefik/traefik` in publishedService is `<namespace>/<traefik service name>`

This would be in your configMap in kubernetes or values.yaml file:

```
kubernetes:
  ingressEndpoint:
    publishedService: "traefik/traefik"
```

**Version of Helm and Kubernetes**:
Helm 2.15
Kubernetes 1.14.x

**Which chart**:
stable/traefik

**What happened**:
Upgrades started failing since helm 2.15. Install should probably fail as well. Unless publishedService is enabled.

**What you expected to happen**:
publishedService should be enabled default. Logic should be in place to support this.

**How to reproduce it** (as minimally and precisely as possible):
Use helm 2.15, values.yaml should not have publishedService set (as it would appear as a default setting)

**Anything else we need to know**:

**Comment by robbo10** [comment]
Also have this issue, the above suggestion by @Exodus would be great 👍
