### ISSUE TITLE
[stable/grafana] newest chart version 3.12.1 can't create Grafana

### ISSUE THREAD

**Issue by marinakog** [helm/charts#18215]
helm install --wait --name grafana --namespace monitoring --values  values.yaml stable/grafana --version=3.12.1
Error: parse error in "grafana/templates/dashboards-json-configmap.yaml": template: grafana/templates/dashboards-json-configmap.yaml:20: unexpected "=" in operand

**Comment by marinakog** [comment]
here is link to values.yaml ( it works for older releases just fine) https://github.com/oracle/weblogic-monitoring-exporter/blob/master/samples/kubernetes/end2end/grafana/values.yaml

**Comment by powellandy** [comment]
Typo in https://github.com/helm/charts/blob/master/stable/grafana/templates/dashboards-json-configmap.yaml#L20

needs to be:

`{{- $dashboardFound := true }}`

I cloned the repo local, fixed it and installed with

helm install .  --set persistence.enabled=true -n grafana --namespace monitoring

**Comment by marinakog** [comment]
yes I was just about to add it , typo in the line 20, when it will be fixed?

**Comment by berni2288** [comment]
This bug is halting me from updating.

**Comment by jdeprin** [comment]
This bug still exists and prevents updating grafana or the prometheus operator chart.  I see a PR to fix the issue but it was closed without comment?

**Comment by zanhsieh** [comment]
@jdeprin 
You could take @imdevin567 work to re-PR it and link this issue. I will approve it.

**Comment by jdeprin** [comment]
@zanhsieh Thanks. I submitted https://github.com/helm/charts/pull/19683

**Comment by jdeprin** [comment]
Upon putting in a PR and running through the tests I found the actual issue.  It is commented in the original commit: https://github.com/helm/charts/commit/39723f2574290702c0fae03f4573ce31d3707e6c#r35603839

This message suggests it is an issue with helm versions >= 2.12.0.  I was running into this issue in v2.14.3 so it exists at least to that version.
