### ISSUE TITLE
[stable/external-dns] DNS deleted and recreated unnecessarily. 

### ISSUE THREAD

**Issue by richardmatthewsdev** [helm/charts#18210]
**Describe the bug**

External DNS removes and recreates entries that are the same as what are already present in Route 53. 

**Version of Helm and Kubernetes**:

Kubernetes 1.13.10
Helm 2.14.3

**Which chart**:

external dns. 

**What happened**:

During an upgrade of the helm chart nginx-ingress-controller. External DNS has deleted and then re created the DNS entries that were relating to that controller. The Loadbalancer that is used for nginx ingress was unchanged and the DNS entries did not need to be changed. 

**What you expected to happen**:

DNS entries to be unchanged. 

**How to reproduce it** (as minimally and precisely as possible):

I encountered this when upgrading nginx-ingress from 1.17.1 => 1.24.3

**Anything else we need to know**:

**Comment by juan131** [comment]
Hi @Reinkaos 

I don't think this issue is related with the Helm chart but **external-dns** (the application) itself. I suggest you to open an issue describing the same behaviour at https://github.com/kubernetes-incubator/external-dns/issues
