### ISSUE TITLE
[stable/nfs-client-provisioner]Image for Arm doesn‘t work

### ISSUE THREAD

**Issue by hzliangbin** [helm/charts#18231]
I followd the Readme.md to deploy nfs-client-provisioner on my Arm machine. Everything was okay but I found the nfs-client-provisioner pod failed to Error state. kubectl logs pod showed error as follow:
standard_init_linux.go:211: exec user process caused “exec format error”

I checked the image info

![image](https://user-images.githubusercontent.com/9740458/67383354-a0655700-f5c1-11e9-9317-ccb8bb304dea.png)

It seems that the image is not correctly built for Arm. Someone knows how to get the image for Arm?

**Comment by zanhsieh** [comment]
@hzliangbin 
This line?
https://github.com/kubernetes-incubator/external-storage/blob/master/nfs-client/Makefile#L24

**Comment by soapergem** [comment]
@hzliangbin you have to do `--set image.repository=quay.io/external_storage/nfs-client-provisioner-arm` when installing the Helm chart. I believe it mentions this in the Readme. The specific error message you listed is what you see whenever you try to run an amd64 image on an armhf machine. You just need to specify the right image.

**Comment by hzliangbin** [comment]
> @hzliangbin you have to do `--set image.repository=quay.io/external_storage/nfs-client-provisioner-arm` when installing the Helm chart. I believe it mentions this in the Readme. The specific error message you listed is what you see whenever you try to run an amd64 image on an armhf machine. You just need to specify the right image.

thx，I pulled the image quay.io/external_storage/nfs-client-provisioner-arm on a google ecs，and I ran docker inspect to check the image info，it showed amd64 arch。I thongth I would get a arm image, but didn't。
