### ISSUE TITLE
[stable/prometheus-adapter] ConfigMap for custom/external/metrics rules

### ISSUE THREAD

**Issue by dioguerra** [helm/charts#18273]
As it works now, the rules are written and exported from the values.yaml file directly into the
DirectXMan12/k8s-prometheus-adapter.
The only way to not allow this is to have the rules.existing=true.

Though this has some good and bads. All the rules are overwritten and the end user (in our case)
if he uses this might not be made aware of changes made to the other underlying rule vectors, if and when this specific service is updated.

Having the custom/external/metrics be a chart with enable/disable in custom/external/metrics/default the user can modify or overwrite the specific file he wants (for example the custom rule vector). 

An alternative to this would be to make a specific CRD for the rules, as it happens with the
prometheus-operator, though this is much more work. 

Comments welcome!!

**Comment by MrD2** [comment]
Any ideas?
