### ISSUE TITLE
[stable/bookstack] Https mixed content error

### ISSUE THREAD

**Issue by neilcamilleri** [helm/charts#18308]
**Describe the bug**
When using bookstack with Https, browser will throw mixed content error when trying to get assets. Issue also reported here https://github.com/BookStackApp/BookStack/issues/1204
There does not appear to be a helm setting to add this environment variable to set the url

**Version of Helm and Kubernetes**:
Latest

**Which chart**:
https://github.com/helm/charts/tree/master/stable/bookstack

**What happened**:
Same as described in linked issue.

**What you expected to happen**:
Expected to automatically switch urls to https

**How to reproduce it** (as minimally and precisely as possible):
Install helm chart with default settings, use a proxy with https like nginx on kubernetes

I think all that needs to be done is to add an helm setting that modifies the APP_URL env variable on the image.

**Comment by quantactic** [comment]
I have the same issue here after upgrading to the latest helm version.  For testing, if I manually set APP_URL to https://<my bookstack site domain> all works fine until Pod container will be set later to initial state in .env file:  APP_URL=null
