### ISSUE TITLE
"reason":"Validation Failed: 1: type is missing;"}], - on init container elasticsearch-s3-repository

### ISSUE THREAD

**Issue by milangm89** [helm/charts#18327]
**Describe the bug**

>> I wanted to enable ELK snapshot backup to s3 using elasticsearch-curator helm chart.
>> For this, I have downloaded the values.yaml and edited the tail portion for adding s3 details.
>> I am getting the below error in "extraInitContainers" after launching.

++++
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: type is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: type is missing;"},"status":400}%                                                                                                                                                                                
++++

**Version of Helm and Kubernetes**:
Helm: Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Kubernetes: Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1"

**Which chart**:
stable/elasticsearch-curator

**What happened**:
After deploying helm chart with s3 backup enabled, I am getting the below error for init container "elasticsearch-s3-repository".

++++
➜  elk-configs git: ✗ kubectl logs -c elasticsearch-s3-repository elasticsearch-curator-1571927640-4hdj5
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ca-certificates (20161130-r3)
(2/4) Installing libssh2 (1.8.2-r0)
(3/4) Installing libcurl (7.61.1-r2)
(4/4) Installing curl (7.61.1-r2)
Executing busybox-1.26.2-r5.trigger
Executing ca-certificates-20161130-r3.trigger
OK: 5 MiB in 15 packages
2019/10/24 15:22:21 Waiting for: http://elasticsearch-master.default.svc.cluster.local:9200
2019/10/24 15:22:21 Received 200 from http://elasticsearch-master.default.svc.cluster.local:9200
curl: (3) [globbing] unmatched brace in column 1
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: type is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: type is missing;"},"status":400}%
++++

**What you expected to happen**:

Init container should be executed fine and the main container should executed 

**How to reproduce it** (as minimally and precisely as possible):

In the values.yaml file below, I have added enabled the "extraInitContainers" part and uncommented the "elasticsearch-s3-repository" part then executed the helm deployment.

https://github.com/helm/charts/blob/master/stable/elasticsearch-curator/values.yaml
++++
# Add your own init container or uncomment and modify the given example.
extraInitContainers:
  ## Don't configure S3 repository till Elasticsearch is reachable.
  ## Ensure that it is available at http://elasticsearch:9200
  ##
  elasticsearch-s3-repository:
    image: jwilder/dockerize:latest
    imagePullPolicy: "IfNotPresent"
    command:
    - "/bin/sh"
    - "-c"
    args:
    - |
      ES_HOST=elasticsearch
      ES_PORT=9200
      ES_REPOSITORY=backup
      S3_REGION=eu-central-1
      S3_BUCKET=es-curator-backup
      S3_BASE_PATH=elk-backup
      S3_COMPRESS=true
      S3_STORAGE_CLASS=standard
      apk add curl --no-cache && \
      dockerize -wait http://${ES_HOST}:${ES_PORT} --timeout 120s && \
      cat <<EOF | curl -sS -XPUT -H "Content-Type: application/json" -d @- http://${ES_HOST}:${ES_PORT}/_snapshot/${ES_REPOSITORY} \
      {
        "type": "s3",
        "settings": {
          "bucket": "${S3_BUCKET}",
          "base_path": "${S3_BASE_PATH}",
          "region": "${S3_REGION}",
          "compress": "${S3_COMPRESS}",
          "storage_class": "${S3_STORAGE_CLASS}",
          "access_key": "xxxxxxx", 
          "secret_key": "xxxxxxxx"
        }
      }
      EOF

securityContext:
  runAsUser: 0  # run as cron user instead of root
+++

**Anything else we need to know**:

**Comment by swirsky** [comment]
I'm getting the same issue - if I get any answers I'll post them here

**Comment by adithyamenon** [comment]
@milangm89 Were you able to resolve this? 

I am facing the same issue - `extraInitContainers` when uncommented does not start the cronjob pods.
