### ISSUE TITLE
[stable/prometheus-operator] dashboards/alerts not installed

### ISSUE THREAD

**Issue by esvirskiy** [helm/charts#18347]
Default dashboards and alerts are not installed

**Version of Helm and Kubernetes**:
Helm v2.13.1 / Kubernetes v1.16

**Which chart**:
prometheus-operator-6.21.0

This works as expected in Kubernetes v1.15.4

**Comment by asosso** [comment]
Hi @esvirskiy,

I've found a simple workaround: you can set `kubeTargetVersionOverride: "1.15"`.
I've opened a PR for this issue: #18401

**Comment by esvirskiy** [comment]
Hi @asosso -

I had to set the version to 1.15.4 for it to work.

Thank you!
