### ISSUE TITLE
[stable/minio] Support for imagePullSecrets

### ISSUE THREAD

**Issue by ghost** [helm/charts#18344]
**Is your feature request related to a problem? Please describe.**
I checked values.yaml, templates/deployment.yaml, templates/statefulset.yaml and templates/post-install-create-bucket-job.yaml and it is not possible to specify a secret to provide registry-crdentials to pull from a private registry.

**Describe the solution you'd like**
The implementation should be something like what is beeing used in the chart that is created by `helm create <name>`.

Suggestion for values.yaml:

```
imagePullSecrets: []
#  - name: <secret-name>
```
Suggestion for templates/deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
spec:
  ...
  template:
    ...
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    ...
```
**Describe alternatives you've considered**
The described way is the default for specifying imagePullSecrets in helm-charts so this should be used for solving this issue. The suggested solution is applicable to all files mentioned in the description.

**Additional context**
We're running only scanned and signed images in our clusters so we need a way to pull images from our private registry. Also we want to be independent of registries that are not managed in our own infrastructure.

**Comment by jasmdk** [comment]
Could you please make a pull request to get your forked changes into main repo?

**Comment by sankalp-rangare-sap** [comment]
Any updates on this?
