### ISSUE TITLE
[stable/home-assistant] vscode image tag not available

### ISSUE THREAD

**Issue by arodus** [helm/charts#18367]
**Describe the bug**
vscode sidecar fails to start with the default image `codercom/code-server:2.1571-vsc1.38.1` since the tag is not available anymore.

**Which chart**:
stable/home-assistant

**Comment by billimek** [comment]
It appears that the code-server docker images are frequently deleted.  I just submitted #18636 to reference an code-server image that is associated with an actual [release](https://github.com/cdr/code-server/releases/tag/2.1665-vsc1.39.2) which hopefully means that the docker tag won't be removed.
