### ISSUE TITLE
[stable/redis] provide a default/configurable PSP

### ISSUE THREAD

**Issue by yfei1** [helm/charts#18368]
Current Redis chart doesn't contain a default PodSecurityPolicy template. When I tried to install Redis with THP support disabled in my PSP-enabled cluster, I started to see some failures because of the PSP and therefore have to configure the privileged RoleBindings and etc by myself. Would it make sense to provide a configurable PSP template for Redis? It feels a bit off when I tried to write it for Redis as an external dependency.

**Comment by juan131** [comment]
Hi @yfei1 

Thanks so much for the suggestion! I just created a PR to address it.

**Comment by yfei1** [comment]
> Hi @yfei1
> 
> Thanks so much for the suggestion! I just created a PR to address it.

Hi @juan131 

I haven't tested the new chart yet, but the PR got merged seems to create an unprivileged PSP for Redis, which likely wouldn't work if someone tries to create a privileged initContainer in order to disable the THP support in the host kernel. Just to confirm if the new PSP works under such scenario?
