### ISSUE TITLE
[prometheus-operator/stable] Overwriting table item 'extraArgs', with non table value

### ISSUE THREAD

**Issue by adyprico** [helm/charts#18393]
**Describe the bug**
During the deploy of prometheus-operator i receive the bellow warnings. Without the two values  prometheus don't collect very important metrics from my cluster. 
**Version of Helm and Kubernetes**:
* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
`
    

* Helm version information:

    `Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
`
    

**Which chart**:
prometheus-operator/stable

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/prometheus-operator

**Anything else we need to know**:
* Prometheus Operator Logs:

```
2019/10/28 10:21:08 Warning: Merging destination map for chart 'prometheus-node-exporter'. Overwriting table item 'extraArgs', with non table value: [--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/) --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$]
2019/10/28 10:21:08 Warning: Merging destination map for chart 'prometheus-node-exporter'. Overwriting table item 'extraArgs', with non table value: [--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/) --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$]

```

**Comment by yuriipolishchuk-finsight** [comment]
@adyprico I've had the same issue after upgrading to 2.15.2. Reverting helm version to 2.13 helped

**Comment by adyprico** [comment]
Hello , Thank you , i did the same thing and yes it worked. I am waiting for the next release maybe this it will be fixed.

**Comment by peterrosell** [comment]
Upgrading helm from 2.14.1 to 2.15.0 triggers those warnings.

**Comment by zackijack** [comment]
Hi @vsliouniaev thanks for your PR, but I still get this issue

**Comment by patkearney** [comment]
Hi @zackijack, are you installing through the main prometheus-operator chart? I think that needs it's requirements bumped to 1.7.3 for the prometheus-node-exporter dependency to be able to install without issue on 2.15.x helm.

**Comment by vsliouniaev** [comment]
The issue in the underlying chart has been fixed, now we need to bump the prometheus operator chart version. That portion is broken for now because the CI process in this repo is failing for everyone

https://github.com/helm/charts/issues/18584
