### ISSUE TITLE
[stable/redis-ha] sentinel probes for ha-proxy assume fixed masterGroupName "mymaster"

### ISSUE THREAD

**Issue by astmuc** [helm/charts#18409]
**Describe the bug**
sentinel probes signal always failure if masterGroupName is not mymaster

**Version of Helm and Kubernetes**:

**Which chart**:
redis-ha

**What happened**:
i extended the redis-ha-configmap with a section to get the haproxy stats running like this:
    frontend stats
      bind *:8404
      mode http
      stats enable
      stats uri /stats
      stats refresh 10s
      stats admin if LOCALHOST
The stats page showed red for all sentinel backends. After editing the config map again and replacing "mymaster" with the actual group name and restarting haprxy, one probe went green.

**Comment by cschockaert** [comment]
related to #17868
