### ISSUE TITLE
[stable/stolon] does not start

### ISSUE THREAD

**Issue by Axizdkr** [helm/charts#18412]
**When start chart got error:**
Failed to install app stolon. Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]

**Version of Helm and Kubernetes**:
Helm: 2.14.3
Kubernetes Version: v1.16.2

**Which chart**:
Version 1.3.0

**What happened**:

**What you expected to happen**:
Start stolon-cluster

**How to reproduce it** (as minimally and precisely as possible):
It's default values except pass, i'm just started this chart.

**Anything else we need to know**:
I'm use rancher

**Comment by sheremet** [comment]
@Axizdkr PR #18616 was tested on stable Rancher `v2.3.2` and Kubernetes `v1.16.2`.
