### ISSUE TITLE
[stable/nginx-ingress] Enabling controller.scope.enabled will disable ClusterRole creation

### ISSUE THREAD

**Issue by Heathland** [helm/charts#18420]
**Describe the bug**
Enabling controller.scope.enabled in the values will stop creation of the ClusterRole.
Looking at the following lines:
https://github.com/helm/charts/blob/c0a7ce93fe4114a73415e2963989c021610a5fee/stable/nginx-ingress/templates/clusterrole.yaml#L1-L23
The if statement on L23 will never be hit due to it being within an IF statement on L1 which doesn't trigger if the controller.scope.enabled is enabled.

**Version of Helm and Kubernetes**:
Helm: v2.14.3
Kubernetes: v2.14.3

**Which chart**:
stable/nginx-ingress

**What happened**:
No ClusterRole was created after enabling controller.scope.enabled

**What you expected to happen**:
A valid ClusterRole with specific namespaces to to watch

**How to reproduce it** (as minimally and precisely as possible):
Enable: controller.scope.enabled=true

**Anything else we need to know**:
n/a

**Comment by richard-scott** [comment]
ah!, I've just been banging my head against the desk on this one!

**Comment by dariuscernea** [comment]
In addition to the clusterrole.yaml file the fix also has to cover the clusterrolebinsding.yaml file, as this one also contains the flawed logic:
https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-role.yaml#L1-L10

**Comment by dariuscernea** [comment]
@Heathland, as a workaround for this issue you could create the needed cluster role, service account and cluster rolebindings manually and set rbac to _false_ and use the _serviceAccount.name_ variable to tell the chart to use this service account.

**Comment by ingnil** [comment]
This patch has actually made it impossible to install nginx-ingress in a single namespace if you do not have permissions to create cluster-wide resources. I see the problem that you solved, but you also created another one.

I suggest a separate flag to disable creation of cluster roles and cluster role bindings, so that nginx-ingress can be installed in a single namespace without permissions to create cluster-wide resources.
