### ISSUE TITLE
[stable/prometheus-operator] services are hardcoded to run in kube-system namespace in helm chart

### ISSUE THREAD

**Issue by harshavardhanc** [helm/charts#18437]
We started using prometheus-operator by deploying using helm charts and we identified that prometheus-operator helm chart is deploying some services in kube-system namespace which is hardcoded in helm chart.
Below are the services.
```
prometheus-prometheus-oper-coredns
prometheus-prometheus-oper-kube-controller-manager
prometheus-prometheus-oper-kube-etcd
prometheus-prometheus-oper-kube-proxy
prometheus-prometheus-oper-kube-scheduler
prometheus-prometheus-oper-kubelet
```
Is there any reason why this is hardcoded and Is there any issue if we change the namespace?

**Comment by vsliouniaev** [comment]
DNS, controller-manager, etcd, kube-proxy and kube-scheduler run in the kube-system namespace. In order to scrape them, the services / endpoints objects need to exist in the same namespace as the pods.
