### ISSUE TITLE
stable/prometheus-operator Back off limit exceeded

### ISSUE THREAD

**Issue by s3than** [helm/charts#18432]
**Describe the bug**
When installing fresh the admission jobs fail with backoff limit exceeded

**Version of Helm and Kubernetes**:
Helm 

```
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"
```

Kubectl

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-16T17:33:45Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"
```
**Which chart**:

prometheus-operator

**What happened**:

```
Error: Job failed: BackoffLimitExceeded
```

**What you expected to happen**:

For the admission webhooks to install

**How to reproduce it** (as minimally and precisely as possible):

```
helm install --version=7.0.0 --name prometheus stable/prometheus
```

**Anything else we need to know**:

Disabling the webhooks then installing installs the chart however the operator fails to run.

Then running upgrade will install the admission webhook then the chart will fail with

```
Error: Job failed: BackoffLimitExceeded
Error: UPGRADE FAILED: Job failed: BackoffLimitExceeded
```

Deleting the jobCreateSecret.yaml from the chart and then re-running the helm upgrade will finally succeed however reverting the jobCreateSecret.yaml will cause the issue to occur again.

The admission-created job is completed

Pod

```
ca-prometheus-prometheus-o-admission-create-tft4j                 0/1     Completed   0          104s
```

Job

```
ca-prometheus-prometheus-o-admission-create   1/1           2s         77s
```

However it also not being removed

**Comment by s3than** [comment]
I've confirmed in a separate cluster that this doesn't occur all details are the same.

Possibly race condition in the admission create?

**Comment by vsliouniaev** [comment]
Could you please post the logs from job pods?

**Comment by s3than** [comment]
I've been unable to replicate it again. I'll close this off and if it occurs again I'll ensure I have all the appropriate logs.

Thank you
