### ISSUE TITLE
[stable/postgresql] postgresql.conf in files folder not work

### ISSUE THREAD

**Issue by b0nete** [helm/charts#18435]
I need use my custom postgresql.conf in the deployment, but i cant make this work.
The docs say that only there is put a postgresql.conf in files folder and deploy.
For deploy this postgresql i use "helm install --name helmtest stable/postgresql --values values.yaml" command. 
This deploy is succesfull but i get in pod, i do cat to /opt/bitnami/postgresql/conf/postgresql.conf but max_wal_size parameter persist in 400mb. And before i had edited the postgresql.conf to max_wal_size be set in 2GB.

**Describe the bug**
postgresql.conf in files folder not work

**Version of Helm and Kubernetes**:
v2.13.1 - 1.13.10-gke.0 

**What happened**:
I need change the max_wal_size parameter, so i want put my custom postgresql.conf in the deployment but this not work for me.

**What you expected to happen**:
See changes in max_wal_size.

**How to reproduce it** (as minimally and precisely as possible):
- Put postgresql.conf in files folder under root.
- No edit values.yaml
- Deploy with command ""helm install --name helmtest stable/postgresql --values values.yaml"
- Enter to pod and verify that postgresql.conf has not changed

**Anything else we need to know**:
I else i tried put postgresql.con in files/conf.d/ and uncomment postgresqlConfiguration:.

**Comment by alemorcuq** [comment]
Hi, @b0nete.

In order to load a file from the `files/` folder you need to have the chart downloaded in your machine (e.g. by cloning the repo). Then you can go into `stable/postgresql/`, put your configuration file under `files/` and run `helm install --name whatever .`.

Another option is to create a `Config Map` with your `postgresql.conf` file and then pass it to the chart with the `configurationConfigMap` parameter. For example:

```
$ kubectl create ns my-namespace
$ kubectl create configmap my-custom-config --from-file=postgresql.conf --namespace my-namespace
$ helm install --name my-pg --namespace my-namespace stable/postgresql --set configurationConfigMap=my-custom-config
```

Hope this helps.

**Comment by b0nete** [comment]
@alemorcuq I really had downloaded all postgresql folder in my desktop and put postgresql.conf in files folder but i didn't work. 
Maybe this i didn't  works because i deployed with "helm install --name name --values values.yaml". I pass the parameter values.yaml.

Anyway, creating the configmap as you say me, its works perfectly!
