### ISSUE TITLE
[stable/prometheus-operator] crds should be installed by chart

### ISSUE THREAD

**Issue by Morriz** [helm/charts#18451]
I am not sure, but it seems that there is no more hook issue with crd install (your documentation refers to this seemingly fixed issue: https://github.com/helm/helm/pull/5112), so why not fix the chart to install them. Or update the docs if it now works ootb...

**Comment by vsliouniaev** [comment]
The chart has been installing them by default since it was moved to this repository about 1 year ago. This has not changed
