### ISSUE TITLE
[stable/prometheus-operator] Prometheus default rules not generated with helm template command

### ISSUE THREAD

**Issue by mcinquin** [helm/charts#18453]
**Describe the bug**
I use helm template to generate all the manifest files and the prometheus default rules manifest files aren't generated

**Version of Helm and Kubernetes**:
Helm: 2.15.1
Kubernetes: 1.13.11

**Which chart**:
stable/prometheus-operator

**What happened**:
With helm template command, the prometheus default rules manifest files aren't generated

**What you expected to happen**:
With helm template command, the prometheus default rules manifest files have to be generated

**How to reproduce it** (as minimally and precisely as possible):
```
helm fetch --untar stable/prometheus-operator
mkdir prometheus-operator/manifests
helm template prometheus-operator --name test --namespace monitoring --output-dir prometheus-operator/manifests -f prometheus-operator/values.yaml
```

**Anything else we need to know**:

**Comment by vsliouniaev** [comment]
Rules files are different between different versions of Kubernetes, so you must use the `--kube-version` flag

**Comment by Shini31** [comment]
It works, thank you!
BTW, a little explanation about this point in README wouldn't be too much.

**Comment by vsliouniaev** [comment]
Good point - feel free to open a PR to get that information added. It is rather difficult to get this in myself because of the requirements about PR merges in this repo.
