### ISSUE TITLE
[stable/influxdb] Statefulset?

### ISSUE THREAD

**Issue by naseemkullah** [helm/charts#18479]
@Aisuko What are your thoughts converting to a statefulset? Or at least adding the option to use a statefulset instead of a deployment.

**Comment by Aisuko** [comment]
There was a PR #17619, it aims to change the source kind from `deployment` to `statefulset`. In fact, I'd like to make this change.

**Comment by naseemkullah** [comment]
Seems like usage of pre existing volume was removed. Could you please add it back?

**Comment by Aisuko** [comment]
Yes, You are right. I think we should do this and thanks for your advice. After we discussed it with the PR author, we can do this.

**Comment by naseemkullah** [comment]
Any timeline to add back pre existing volume and the`release: "{{ .Release.Name }}` label??
