### ISSUE TITLE
[stable/external-dns] AWS assume role got applied twice

### ISSUE THREAD

**Issue by lich1710** [helm/charts#18474]
**Describe the bug**
When set `aws.assumeRoleArn`, the role will be used to set both the default aws profile, also used in external-DNS argurments `--aws-assume-role`, this will make a situation where you use an assume role to assume that role itself. The error will be similar to this:

```An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::XXX:assumed-role/qbernetes-staging-external-dns is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::XXX:role/qbernetes-staging-external-dns```

**Version of Helm and Kubernetes**:
Helm: v2.14.3
Kubernetes: 1.14

**Which chart**:
external-dns

**What happened**:
```An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::XXX:assumed-role/qbernetes-staging-external-dns/kiam-kiam is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::XXX:role/qbernetes-staging-external-dns```

**What you expected to happen**:
That external-dns can assume the role and use it to create DNS record.

**How to reproduce it** (as minimally and precisely as possible):
Set `aws.credentials.accessKey`, `aws.credentials.secretKey` and `aws.assumeRoleArn` then deploy.

**Anything else we need to know**:
Work around is leave the `aws.assumeRoleArn` empty, and set the extraArgs instead:
```
extraArgs: 
  aws-assume-role: arn:aws:iam::XXXXXXXXXX:role/Route53ReadWriteRole
```

**Comment by juan131** [comment]
Hi @lich1710 

As you mentioned, we're using that parameter twice:

- To setup the `--aws-assume-role` flag. See https://github.com/helm/charts/blob/master/stable/external-dns/templates/deployment.yaml#L99
- To setup the default profile. See https://github.com/helm/charts/blob/master/stable/external-dns/templates/_helpers.tpl#L121

So.. What's your proposal? Avoid using it in the default profile?

**Comment by juan131** [comment]
Hi @lich1710 

I just created a PR to address the issue.
