### ISSUE TITLE
[stable/prometheus] Alertmanager --client.peer isn't set

### ISSUE THREAD

**Issue by dlyle65535** [helm/charts#18496]
**Describe the bug**
The --client-peer flag isn't set correctly when alertmanager.statefulSet.headless.enableMeshPeer=true and alertmanager.replicaCount=2.

helmfile template shows that the correct values are output, but helmfile apply|sync don't actually have the arguments.

**Version of Helm and Kubernetes**:
Helm:
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Kubernetes:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:43:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
Prometheus (alertmanager)

**What happened**:
Stateful spec was as follows:

spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus
      component: alertmanager
      release: monitoring
  serviceName: monitoring-prometheus-alertmanager-headless
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
        chart: prometheus-9.2.0
        component: alertmanager
        heritage: Tiller
        release: monitoring
    spec:
      containers:
      - args:
        - --config.file=/etc/config/alertmanager.yml
        - --storage.path=/data
        - --cluster.advertise-address=$(POD_IP):6783
        - --cluster.listen-address=0.0.0.0:6783
        - --web.external-url=http://localhost:9093/alertmanager
Notice - no client.peer.args.

**What you expected to happen**:
Should have the following args:
args:
            - --config.file=/etc/config/alertmanager.yml
            - --storage.path=/data
            - --cluster.advertise-address=$(POD_IP):6783
            - --cluster.listen-address=0.0.0.0:6783
            - --cluster.peer=monitoring-prometheus-alertmanager-0.monitoring-prometheus-alertmanager-headless:6783
            - --cluster.peer=monitoring-prometheus-alertmanager-1.monitoring-prometheus-alertmanager-headless:6783
            - --web.external-url=http://localhost:9093/opserv-alertmanager

**How to reproduce it** (as minimally and precisely as possible):
Install chart on cluster with:
alertmanager:
    statefulSet:
      enabled: true
      headless:
        enableMeshPeer : true
        annotations: {}
        labels: {}
        servicePort: 80

**Anything else we need to know**:

**Comment by chicken231** [comment]
I can confirm this as well. For now, I'm manually edited the args in the `StatefulSet`.
```
--cluster.peer=prometheus-alertmanager-0.prometheus-alertmanager-headless:6783
--cluster.peer=prometheus-alertmanager-1.prometheus-alertmanager-headless:6783
--cluster.peer=prometheus-alertmanager-2.prometheus-alertmanager-headless:6783
```

**Comment by jpalpant** [comment]
I also observed the same thing! Haven't looked into it at all but I don't want this issue closed unless I'm just doing something wrong
