### ISSUE TITLE
[stable/external-dns] Should not mount /etc/kubernetes if useManagedIdentityExtension=true

### ISSUE THREAD

**Issue by desek** [helm/charts#18494]
**Is your feature request related to a problem? Please describe.**
When running ExternalDNS in Azure together with aad-pod-identity and the deployment option useManagedIdentityExtension=true it's not necessary to mount a hostPath to the pod to get credentials to manage the Azure DNS zone.

**Describe the solution you'd like**
I'd like the chart, when deployed with `azure.useManagedIdentityExtension=true`, to not mount the hostPath /etc/kubernetes. This could be easily implemented by updating the conditional statements for those sections of the depoyment manifest.

**Describe alternatives you've considered**
Pod Security Policies to deny hostPath access.

**Additional context**

**Comment by carrodher** [comment]
Thanks for the PR, we are taking a look
