### ISSUE TITLE
[stable/redis] password not applied to sentinel

### ISSUE THREAD

**Issue by shane-kearns** [helm/charts#18515]
**Describe the bug**
The redis-sentinel container is configured with no password required, even when `usePassword` = `true`.
https://redis.io/topics/sentinel describes under "Configuring Sentinel instances with authentication" that the configuration file should contain `requirepass "your password"`

This report is the same as #14446 though that was retracted by the author.

Thus a configuration variable may be needed to allow an unauthenticated sentinel to be used with an authenticated cluster.

**Version of Helm and Kubernetes**:

Helm 2.15.2
Kubernetes 1.14

**Which chart**:

stable/redis

**What happened**:

The password is applied to redis port 6379, but sentinel port 26379 is unauthenticated

**What you expected to happen**:

Both ports require the same password

**How to reproduce it** (as minimally and precisely as possible):

Starting from `values-production.yaml`, set `sentinel.enabled` = `true` and `usePassword` = `true`.
Connect to the sentinel port, sending an AUTH command.

e.g. using py-redis, this will throw an exception, whereas commenting out the password will succeed:
```
import os;
import redis;
connection = redis.Redis(
    host='redis',
    port=26379,
    socket_connect_timeout=500,
    password=os.environ["REDISCLI_AUTH"],
)
```

**Anything else we need to know**:

As mentioned on #14446, adding `printf "\nrequirepass $REDIS_PASSWORD" >> /opt/bitnami/redis-sentinel/etc/sentinel.conf` to the password enabled section of the sentinel config generation looks likely to fix it.

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. Were you able to check that, when adding that string to the sentinel.conf file, authentication works? It would be very helpful for us to know that. Also, feel free to create a PR with the change if you confirm that it works.

**Comment by shane-kearns** [comment]
Hi,

I've confirmed that sentinel authentication works using python and redis-cli. Python is the better test case, as redis-cli silently ignores the error when sending an AUTH command that was not required.

**Comment by javsalgar** [comment]
Thanks for the PR!
