### ISSUE TITLE
[stable/wordpress] Warning ingress annotations

### ISSUE THREAD

**Issue by v-six** [helm/charts#18532]
**Describe the bug**
When I set an annotation in the `annotations:` field of `ingress:`, helm trigger a `Warning: Merging destination map for chart 'wordpress' . The destination item 'annotations' is a table and ignoring the source 'annotations' as it has a non-table value of: <nil>` on installation.

This issue doesn't occur on the `annotations:` field of `service:`. 

**Version of Helm and Kubernetes**:
- Helm : v2.14.3
- Kubernetes : v1.15.5

**Which chart**:
stable/wordpress

**What happened**:
When I set an annotation in the `annotations:` field of `ingress:`, helm trigger a `Warning: Merging destination map for chart 'wordpress' . The destination item 'annotations' is a table and ignoring the source 'annotations' as it has a non-table value of: <nil>` on installation.

**What you expected to happen**:
Installation of `stable/wordpress` with an ingress annotation does not trigger any warning.

**How to reproduce it** (as minimally and precisely as possible):
Install the chart with a values.yml file containing :
```
ingress:
  annotations:
    kubernetes.io/ingress.class: "nginx"
```

**Anything else we need to know**:
This issue doesn't occur on the `annotations:` field of `service:`.

**Comment by juan131** [comment]
Hi @v-six 

Thanks so much for reporting this! I just created a PR to address it.
