### ISSUE TITLE
concourse fails to install on kubernetes 1.16 and up

### ISSUE THREAD

**Issue by ramonskie** [helm/charts#18547]
the concourse helm chart still lists at deprecated api endpoints.
```
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version 
"extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]
```
w could solved this with backwords compaibility to add the versions in the helper script

**Comment by pivotal-bin-ju** [comment]
Hi @ramonskie ,
We are migrating this chart (stable/concourse) to https://github.com/concourse/concourse-chart
Would you mind reopening an issue there?

**Comment by ramonskie** [comment]
i already created an pr. on this repo.
https://github.com/helm/charts/pull/18557

i can also make the changes on the other repo if you want?

**Comment by ramonskie** [comment]
added the pr
https://github.com/concourse/concourse-chart/pull/10
