### ISSUE TITLE
mongodb pod and pvc status showing pending  pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by veera2019** [helm/charts#18546]
I am installing mongodb using helm command in aws instance i am using below command but mongodb pod and pvc pod status showing pending 

**helm install --set mongodbRootPassword=hello,mongodbUsername=mongo,mongodbDatabase=mydata  --set volumePermissions.enabled=true --name mongo stable/mongodb**

in PVC pod logs showing **no persistent volumes available for this claim and no storage** class is set
 error
in mongodb pod logs showing **pod has unbound immediate PersistentVolumeClaims** error

So can you please suggest me how to resolve this issue.

**Comment by rafariossaa** [comment]
Hi @veera2019 ,
  When I run that command on a AWS kubernetes cluster. Could you run `kubectl describe pod name of the pod` and paste here the result ?
  Could it be that  your user does not have permissions to create a pvc on the kubernetes cluster ?

**Comment by veera2019** [comment]
i have launched volume and attached to ec2 instance master node and created pv from kubernetes master .
i am installing mongodb using below command
helm install --set mongodbRootPassword=###,mongodbUsername=mongo,mongodbDatabase=### --set volumePermissions.enabled=true --name mongo stable/mongodb

After running this command pvc pod running fine and mongodb pod status showing init:0/1
if i describe the mongodb pod i am getting error like

**Warning FailedMount 14m (x18 over 57m) kubelet, ip Unable to mount volumes for pod "mongo-mongodb-7ff758c779_default()": timeout expired waiting for volumes to attach or mount for pod "default"/"mongo-mongodb-7ff758c779". list of unmounted volumes=[data]. list of unattached volumes=[data default-token]

mount: /var/lib/kubelet/pods/b9ce4962-ff8e-11e9-a2d3/volumes/kubernetes.io~aws-ebs/mongo: special device /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-##does not exist.**

Can you give me the solution
