### ISSUE TITLE
[stable/pgadmin] ingress isn't working

### ISSUE THREAD

**Issue by nastrofaction** [helm/charts#18568]
**Describe the bug**
Either with ingress enabled or service type set to LoadBalancer; the webpage fails to render completely on the browser.

**Version of Helm and Kubernetes**:
helm: 2.13.1
Kuberenetes: 1.13

**Which chart**:
stable/pgadmin

**What happened**:
If ingress is enabled; it allows you to login but the landing page does not display completely and no functionality works thereon. If you set service type to LoadBalancer; the login page loads but it doesn't allow you to login and proceed to the next screen.

**What you expected to happen**:
Should work seamlessly. 

**How to reproduce it** (as minimally and precisely as possible):
In values.yaml
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: sample-pgadmin.sample.net
      paths: [/]
```
or
```
service:
  type: LoadBalancer
  port: 80
```
The web page on load starts to throw errors.
![image](https://user-images.githubusercontent.com/5763203/68158471-b3f7b280-ff1d-11e9-8b5e-6f274781dd72.png)

I suspect something is wrong with this block at browser index but I am not a JS expert.
![image](https://user-images.githubusercontent.com/5763203/68158547-d7baf880-ff1d-11e9-952b-3cf7d02cecd0.png)

**Anything else we need to know**:
This on EKS and Nginx ingress.
The ingress works fine as we have other applications on the cluster using it.
Everything works perfectly with NodeType or ClusterIP configuration.

**Comment by AntoineGodeau** [comment]
I have the exact same problem. I'm on gke under an nginx ingress controller

**Comment by AntoineGodeau** [comment]
Is there new version which fix this issue ?

**Comment by alexhowardconga** [comment]
Looks like this is only an issue on Chrome (I'm currently on v 79.0). Tried with Firefox 72.0 and the page load successfully.

**Comment by rowanruseler** [comment]
@nastrofaction I am really unable to reproduce this specific issue. Is it still occurring in the current versions at your side?

**Comment by RachadAbiChahine** [comment]
@AntoineGodeau you can use 1.2.2 it should work now 👯‍♂

**Comment by AntoineGodeau** [comment]
Thanks a lot @RachadAbiChahine. It works very well now. My database management will be really improve thanks to this

**Comment by alexhowardconga** [comment]
I can confirm I am now able to utilize pgadmin in both Firefox and Chrome using version 1.2.3 of the chart in EKS now. Thank you!
