### ISSUE TITLE
[All] Chart merging is blocked - PRs do not get Contribution Allowed label added 

### ISSUE THREAD

**Issue by vsliouniaev** [helm/charts#18584]
Since Monday 2019-Nov-4 no PRs are getting the `Contribution Allowed` label added to them and so cannot be merged.

**Comment by mattfarina** [comment]
Thanks for calling this out. The addition of the label has been fixed for any new commits pushed.

We can close this after we have gone through the backlog of those missing the label and adding it.

**Comment by mattfarina** [comment]
This should now be fixed. The backlog of those missing the label has been processed.
