### ISSUE TITLE
configuring resource limits in values.yaml are only applied on 1 of 2 containers

### ISSUE THREAD

**Issue by stevenderycke** [helm/charts#18585]
#### values.yaml:
<pre>
resources:
    memory: 50Mi
  requests:
    cpu: 50m
    memory: 50Mi
cloudsqlproxy:
  enabled: true
</pre>

#### kubectl.exe get deployment
<pre>
template:
  spec:
    containers:
    - name: prometheus-mysql-exporter
      resources: {}
    - name: cloudsql-proxy
      resources:
        limits:
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
</pre>
I would expect the resource limits applied to both prometheus-mysql-exporter and cloudsql-proxy

**Comment by vsliouniaev** [comment]
@stevenderycke you should follow the guidelines when opening issues if you would like the maintainers of the specific chart to be able to find this issue and reply.

I recommend also @-ing one of the maintainers found in the OWNERS fike in the chart directory
