### ISSUE TITLE
How to run the mongodb chart as statefulset / prevent pvc from being deleted

### ISSUE THREAD

**Issue by dargolith** [helm/charts#18588]
I would like to run a simple mongodb instance in my stack but I want to prevent the pvc from being removed when I run `helm delete --purge` on the release and instead be used again if the same release is deployed.

helm/charts/incubator/orientdb works exactly as I want to, using statefulset instead of deployment. Can I do the same with mongodb. If not, why not?

I'm not interested in extra complexity / load by having multiple replicas, unless you convince me somehow to do so (I saw that replicaSet.enabled: true makes the nodes use statefulsets). For larger scale production the db would probably not be located in the same cluster for us anyways.

If this is not possible to configure, can I make something in my own chart to prevent the pvc from being removed on `helm delete`? I know it's possible to provide your own pvc to the mongodb chart. But how can I create a template for a pvc to prevent it from being deleted? Statefulset should be used on the actual service, not only for the volume, no?

I'm quite new to helm, so I might have missed something.

Oh, I also didn't find a "question" issue type. So if this is the wrong place for questions, please direct me to the right place.

Thanks for any advice on this!

**Comment by juan131** [comment]
Hi @dargolith 

The MongoDB chart supports to be installed as a **statefulset** (indeed three statefulsets: one for primary nodes, one for secondary nodes, and one for arbiter nodes). To do so, you need to ensure the `replicaSet.enabled` parameter is set to`true`.

You can find more information in the link below:

- https://github.com/helm/charts/tree/master/stable/mongodb#replication

> can I make something in my own chart to prevent the pvc from being removed on helm delete?

If you're using a **statefulset** which uses **volumeClaimTemplates**, the `helm delete` command won't remove the generated PVCs.

**Comment by dargolith** [comment]
@juan131 Thanks for your answer! However, as I wrote I'm not interested in the extra complexity, maintenance, increased load, increased cloud storage that replica-sets offer.

In the case I need high availability, I would run a dedicated mongodb cluster, or use some serverless cloud db.

I rather want something that can be included in my application stack for earlier stages of use cases (PoCs, Demos, Early pilots, etc). But even in those cases, I want to prevent accidental loss of data in the case someone wanted to re-deploy (delete / install) the chart.

When reading guidelines for when to use statefulset and when to use deployments, a database service very much sounds like it should use statefulset as default.

I understand the convenience of cleaning up all resources in the case of testing and what not. I would be perfectly fine with an option to use statefulset instead. Even though I would recommend using statefulset as default I'd be happy if I had configure it.

Is there some reasoning behind the choice?

**Comment by dargolith** [comment]
Pull request now available: https://github.com/helm/charts/pull/18669
