### ISSUE TITLE
[stable/redis] metrics.extraArgs ignored

### ISSUE THREAD

**Issue by ggarson** [helm/charts#18582]
**Describe the bug**
When you want to add metrics.extraArgs, they are totally ignored.

**Version of Helm and Kubernetes**:
**Kubernetes** Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.2", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-10-21T20:01:24Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
**Helm**Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

**Which chart**:
stable/redis 5.0.5

**What happened**:
metrics.extraArgs are not used when specified

**What you expected to happen**:
redis_exporter used args provided for exporting key metrics

**How to reproduce it** (as minimally and precisely as possible):
add for example
```  
  extraArgs:
    debug: "true"
```

**Anything else we need to know**:
If the command used in redis-master-statefulset.yaml is reduced to 1 element in array (for example "redis_exporter"), args are not ignored anymore

**Comment by alemorcuq** [comment]
Hi, @ggarson. 

I can confirm this is an issue, and it's caused by the command being `/bin/bash -c ...` instead of `redis-exporter`, as the values defined in `args` are not passed to `redis-exporter` but to bash instead. 

I'm working on a fix.
