### ISSUE TITLE
[stable/anchore-engine] Allow to configure image_analyze_timeout_seconds

### ISSUE THREAD

**Issue by frittentheke** [helm/charts#18580]
**Is your feature request related to a problem? Please describe.**
Currently the chart does not expose _image_analyze_timeout_seconds_ to be configured.
and therefore this defaults to 10 hrs: https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/catalog/__init__.py#L905

**Describe the solution you'd like**
It would be great if the values.yml for the chats would allow this setting to be modified.

**Describe alternatives you've considered**
There was an issue discussed about auto-removal of orphaned services:
https://github.com/anchore/anchore-engine/issues/145

This mechanism would help / fix the issue as well (as jobs are re-scheduled to other Analyzers then, right?), but only cleaning up once per day is not enough.

In either case I still consider a configurable timeout for image scalling a good addition to the chat.

**Additional context**
Espcially in dynamic environments, just as Kubernetes, where pods are moved quite violently (i.e. when doing cluster autoscaling, rolling updates of nodes, ...) the Analyzer pods might go away and then having images not considered to be (re-)scanned for 10 hrs is a little long.

**Comment by Btodhunter** [comment]
@frittentheke thanks for the input! I put in a PR to address this, I'll make sure it gets reviewed & approved asap.
