### ISSUE TITLE
[stable/bookstack] mariadb settings for pvc confusion

### ISSUE THREAD

**Issue by David-Melo** [helm/charts#18609]
**Describe the bug**
The description for the chart says that a PVC for mariadb is enabled by default but in values.yaml the value is set to false. 

**Version of Helm and Kubernetes**:
K8s: 1.16; Helm v2.14.3

**Which chart**:
stable/bookstack

**What happened**:
Default settings in readme description dont match what is in values.yaml

**What you expected to happen**:
A PVC for mariadb to be created by default.

**How to reproduce it** (as minimally and precisely as possible):
Launch the chart with default settings.

**Anything else we need to know**:

**Comment by David-Melo** [comment]
Is this the desired functionality? If not, can I submit a pull request with a fix?

**Comment by noe-charmet** [comment]
Wanted to report the same thing. Learned the hard way that the default value for mariaDB persistence written in the doc was not the same as the one set in values.yaml
