### ISSUE TITLE
[rabbitmq stable/chart] curl healthchecks don't work with special characters password

### ISSUE THREAD

**Issue by kbrown** [helm/charts#18606]
**Describe the bug**

RABBITMQ_PASSWORD with special characters causes healthcheck to fail for non-binami images 

**Version of Helm and Kubernetes**:

current helm (v2.4.0?)

**Which chart**:

rabbitmq/stable

**What happened**:

401 Unauthorized

**What you expected to happen**:

200 ok

**How to reproduce it** (as minimally and precisely as possible):

1) set RABBITMQ_PASSWORD to have an ":" in it
2) be on the non-bitnami image or force the START_FLAG false path below

```
data:
  rabbitmq-health-check: |-
    #!/bin/sh
    START_FLAG=/opt/bitnami/rabbitmq/var/lib/rabbitmq/.start
    if [ -f ${START_FLAG} ]; then
        rabbitmqctl node_health_check
        RESULT=$?
        if [ $RESULT -ne 0 ]; then
          rabbitmqctl status
          exit $?
        fi
        rm -f ${START_FLAG}
        exit ${RESULT}
    fi
    rabbitmq-api-check $1 $2
  rabbitmq-api-check: |-
    #!/bin/sh
    set -e
    URL=$1
    EXPECTED=$2
    ACTUAL=$(curl --silent --show-error --fail "${URL}")
    echo "${ACTUAL}"
    test "${EXPECTED}" = "${ACTUAL}"
```

RABBITMQ_PASSWORD

**Anything else we need to know**:

RABBITMQ_PASSWORD is not urlencoded in the existing code below:

```
- sh
 - -c
 - rabbitmq-api-check "http://{{ .Values.rabbitmq.username }}:$RABBITMQ_PASSWORD@127.0.0.1:{{ .Values.service.managerPort }}/api/healthchecks/node" '{"status":"ok"}'
```

Urlencoding the password using curl (which is already be used) will fix the problem:

```
URLENCODED_PASS=$(echo -n $RABBITMQ_DEFAULT_PASS | curl -Gso /dev/null -w %{url_effective} --data-urlencode @- "" | cut -c 3-) && rabbitmq-api-check "http://{{ .Values.rabbitmq.username }}:$RABBITMQ_PASSWORD@127.0.0.1:{{ .Values.service.managerPort }}/api/healthchecks/node" '{"status":"ok"}'

```

**Comment by rafariossaa** [comment]
Hi @kbrown,
  Thanks for noticing this.
  It would be great if you can send a PR to fix it. Would you mind  ?

Thanks Forehand
