### ISSUE TITLE
stable/nginx-ingress 0.8.1

### ISSUE THREAD

**Issue by agonzalez-tk** [helm/charts#1860]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
platform:GKE
kubernetes: 1.7.3
helm: 2.5.1

**Which chart**:
name: nginx-ingress
version: 0.8.1
appVersion: 0.9.0-beta.11

**What happened**:
Installed nginx controller with helm chart from git.
Then created an ingress of class:nginx and got a IP for this ingress when tried to hit this IP I get connection refused if I hit the LB IP of nginx controller it works.

**What you expected to happen**:
I should be able to hit the IP address of the ingress resource and be delivered to the service

**How to reproduce it** (as minimally and precisely as possible):
Create an ingress on GKE and try to hit the public IP assigned 

**Anything else we need to know**:

**Comment by agonzalez-tk** [comment]
well I was testing using the controller IP and that seemed to work but when using ssl it gets a wrong certificate a self signed one so not sure whats the problem here. Some pointer on how to debug this will be helpful.

**Comment by FossPrime** [comment]
/remove-lifecycle stale

I too am looking for a way to GKE without the GCP Load Balancer... Nginx-ingress seems like the way to do it, but I haven't found anyone successfully going that route for some reason.

My guess is you would need some way to map a secondary static ip to the pod handling the nginx-controller.

https://gitlab.com/gitlab-org/gitlab-ce/issues/42100
