### ISSUE TITLE
[stable/mongodb] initializtion scripts are running every time container starts 

### ISSUE THREAD

**Issue by Art3mK** [helm/charts#18623]
**Describe the bug**

Hey, looks like with default value of `persistence.mountPath` PV for persistence is mounted at `/bitnami/mongodb`, while bitnami's image is [setting](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.0/debian-9/rootfs/libmongodb.sh#L31) `MONGODB_VOLUME_DIR` to `/bitnami` and `mongodb_custom_init_scripts` function in [`libmongodb.sh`](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.0/debian-9/rootfs/libmongodb.sh) [touches](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.0/debian-9/rootfs/libmongodb.sh#L1228) `.user_scripts_initialized` file in `/bitnami` directory after executing init scripts, so after restart there is no that `.user_scripts_initialized` file and init scripts are executed again.

Probably changing default `mountPath` is not possible, as it would break existing installations, but should that issue be described in readme? That took me an hour to investigate why this is happening.

**Which chart**:
stable/mongodb

**What happened**:
init script are executed on every container start, even when DB is already initialized

**What you expected to happen**:
init script are executed only on fresh empty db

**How to reproduce it** (as minimally and precisely as possible):
configure init scripts, deploy, restart container

Thanks!

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. Maybe, what we could do is try to change where the file is created so we break the minimum as possible. I will open a task to investigate this.

**Comment by Art3mK** [comment]
@javsalgar , did you opened task for that?

**Comment by borice** [comment]
I'm also interested in a fix for this.  If I am just starting now with Mongo (so had no existing chart), is it safe to just update the value of `persistence.mountPath` to be `/bitnami`?  I did that on a test minikube deployment and it worked perfectly with no side-effects I could notice.

**Comment by Art3mK** [comment]
I did exactly that, no any issues here ¯\_(ツ)_/¯
