### ISSUE TITLE
[stable/airflow] Airflow not starting

### ISSUE THREAD

**Issue by cyrilbkr** [helm/charts#18624]
Hi,

I can't setup Airflow on my side with the default minimal helm config, i have an error when the scheduler init.
I have previously setup this chart 5 month ago without problems; it seems that something is broken now. 

Helm command : 
helm install --namespace myns  --name "airflow" stable/airflow

Scheduler logs : 

│ waiting 10s...                                                                                                                         │
│ executing initdb                                                                                                                       │
│ Traceback (most recent call last):                                                                                                     │
│   File "/usr/local/bin/airflow", line 21, in <module>                                                                                  │
│     from airflow import configuration                                                                                                  │
│   File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 40, in <module>                                              │
│     from flask_admin import BaseView                                                                                                   │
│   File "/usr/local/lib/python3.6/site-packages/flask_admin/__init__.py", line 6, in <module>                                           │
│     from .base import expose, expose_plugview, Admin, BaseView, AdminIndexView  # noqa: F401                                           │
│   File "/usr/local/lib/python3.6/site-packages/flask_admin/base.py", line 6, in <module>                                               │
│     from flask import Blueprint, current_app, render_template, abort, g, url_for                                                       │
│   File "/usr/local/lib/python3.6/site-packages/flask/__init__.py", line 21, in <module>                                                │
│     from .app import Flask                                                                                                             │
│   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 69, in <module>                                                     │
│     from .wrappers import Request                                                                                                      │
│   File "/usr/local/lib/python3.6/site-packages/flask/wrappers.py", line 14, in <module>                                                │
│     from werkzeug.wrappers.json import JSONMixin as _JSONMixin                                                                         │
│ ModuleNotFoundError: No module named 'werkzeug.wrappers.json'; 'werkzeug.wrappers' is not a package

k8s version : eks 1.14

**Comment by gsemet** [comment]
can you change the image version?

**Comment by cyrilbkr** [comment]
Sure, what image version do you recommend me ?

**Comment by gsemet** [comment]
No idea, puckle image works pretty well there is no reason why there is this missing lib

**Comment by cyrilbkr** [comment]
It work with the previous image 10.0-5 when changing the tags setting in the values.yaml but not with the last one 1.10.4. 

1.10.4 is the default one in values.yaml now :(

**Comment by gsemet** [comment]
Maybe you can raise an issue on puckel github.
