### ISSUE TITLE
[stable/prometheus-operator] duplicate namespace in exporters/core-dns/service.yaml

### ISSUE THREAD

**Issue by haf-afa** [helm/charts#18633]
![prom-op-bug](https://user-images.githubusercontent.com/56340843/68308589-67db7800-00ad-11ea-862d-94250df3160c.PNG)

Only one namespace is allowed, both on a structural YAML level (it's an object after all) and as end k8s resource.

**Comment by haf-afa** [comment]
![prom-op-bug-2](https://user-images.githubusercontent.com/56340843/68309063-2b5c4c00-00ae-11ea-9dde-3e1b78ae4095.PNG)

**Comment by haf-afa** [comment]
![prom-op-bug-3](https://user-images.githubusercontent.com/56340843/68309178-55157300-00ae-11ea-90f3-33a088ab3467.PNG)

**Comment by haf-afa** [comment]
![prom-op-bug-4](https://user-images.githubusercontent.com/56340843/68309260-724a4180-00ae-11ea-9574-e73a6d2fcfdb.PNG)

**Comment by haf-afa** [comment]
![prom-op-bug-5](https://user-images.githubusercontent.com/56340843/68309398-a9b8ee00-00ae-11ea-9cdc-79028d69580a.PNG)

last one?

**Comment by vsliouniaev** [comment]
I believe this had been resolved by https://github.com/helm/charts/pull/18363

**Comment by haf-afa** [comment]
@vsliouniaev Yes it was, thanks
