### ISSUE TITLE
[stable/jenkins] init error "pod has unbound immediate PersistentVolumeClaims"

### ISSUE THREAD

**Issue by cyphercider** [helm/charts#18639]
**Describe the bug**
Jenkins pod fails at initialization with “Pod has unbound PersistentVolumeClaims”.

**Version of Helm and Kubernetes**:
Kubernetes version 1.13.11-gke.9
Helm version 2.14.3

**Which chart**:
stable/jenkins v1.8.2

**What happened**:
Jenkins pod fails initialization with "pod has unbound immediate PersistentVolumeClaims"
![image](https://user-images.githubusercontent.com/17109209/68332447-d831cb80-00a4-11ea-8640-4556187f601c.png)

**What you expected to happen**:
Pod starts successfully

**How to reproduce it** (as minimally and precisely as possible):
Install stable/jenkins in a GKE cluster with default values.

**Anything else we need to know**:
I noticed this related issue, 
https://github.com/helm/charts/issues/14514#issuecomment-499337710, but my error occurs with a vanilla install with default chart values.

**Comment by jeffkhull** [comment]
Please note that querying for pv and pvc show a status of "Bound"

![image](https://user-images.githubusercontent.com/17109209/68333306-4925b300-00a6-11ea-8fae-4aac38306a40.png)

**Comment by jeffkhull** [comment]
To anyone having this issue, to debug further, use this to view the init pod logs:

> kubectl logs [jenkins pod name] -c copy-default-config

My issue turned out to have nothing to do with storage, but rather access to some of the Jenkins mirrors (http://mirrors.jenkins-ci.org/status.html) in my egress firewall rules.

**Comment by jvaidyan** [comment]
Seeing similar issue when trying to install jenkins on a pks cluster.  Error from copy-default-config  is 

Downloading plugin: git from https://updates.jenkins.io/download/plugins/git/4.2.2/git.hpi
cp: overwrite '/var/jenkins_home/config.xml'? cp: overwrite '/var/jenkins_home/jenkins.CLI.xml'? cp: overwrite '/var/jenkins_home/jenkins.model.JenkinsLocationConfiguration.xml'? curl: (28) Connection timed out after 20001 milliseconds
curl18:29:40 Failure (28) Retrying in 1 seconds...
