### ISSUE TITLE
MongoDB additional environment variables

### ISSUE THREAD

**Issue by oktacon95** [helm/charts#18663]
Hello, 

I would like to set additional environment variables, because we need that for Backup purposes. 
I cannot find any way to consume new environment variables, not even with a config map, because these just get consumed as a volume.

Am I missing anything?

Cheers,
Manuel

**Comment by zanhsieh** [comment]
https://github.com/helm/charts/blob/master/stable/mongodb/templates/deployment-standalone.yaml#L90

**Comment by caiohasouza** [comment]
@oktacon95 do you solve this question? I have the same issue..

**Comment by caiohasouza** [comment]
This pr will solve this issue (https://github.com/helm/charts/pull/19434).
