### ISSUE TITLE
[stable/kong] - install fails

### ISSUE THREAD

**Issue by iamdevnull** [helm/charts#18671]
**Describe the bug**
install of kong chart fails

**Version of Helm and Kubernetes**:
Helm Client: v2.11.0
Helm Server: v2.11.0
Kubernetes: v1.14.8-gke.2

**Which chart**:
stable/kong

**What happened**:
`Error: parse error in "kong/templates/_helpers.tpl": template: kong/templates/_helpers.tpl:203: unexpected "=" in operan`

**What you expected to happen**:
install without errors

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/kong --name kong -f values.yaml

**Anything else we need to know**:

**Comment by hbagdi** [comment]
Can you update and to the latest (helm repo update) and try again?

Also, which version of Helm chart do you see this problem in?

**Comment by m-osmani** [comment]
after helm upgrade to 2.15 everything is fine. THX!

Best regards
