### ISSUE TITLE
[stable/influxdb] PR for adding optional support of enterprise

### ISSUE THREAD

**Issue by wgj** [helm/charts#18685]
@jackzampolin 
@aisuko

Would you be interested in a PR for adding in support for InfluxDB Enterprise and replications, perhaps building off of #17619?

**Is your feature request related to a problem? Please describe.**
I plan on writing a chart for this anyways, so it would likely make sense to build off of the existing chart, and be able to contribute it back. 

**Describe the solution you'd like**
Adding in conditional support for meta servers, license configmap, and replication (probably other things)

**Describe alternatives you've considered**
Making a chart based on https://docs.influxdata.com/enterprise_influxdb/v1.7/install-and-deploy/production_installation/meta_node_installation/

**Comment by Aisuko** [comment]
You are welcome. Feel free to make the PR.

**Comment by wgj** [comment]
@Aisuko #19625 for your consideration
