### ISSUE TITLE
Use `StorageClassName` for PV/PVC in charts

### ISSUE THREAD

**Issue by gyliu513** [helm/charts#1869]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

In the Kubernetes 1.6 release, dynamic provisioning has been promoted to stable (having entered beta in 1.4). In 1.6, `StorageClassName` attribute has been added to `PersistentVolume` and `PersistentVolumeClaim` objects and should be used instead of annotation `volume.beta.kubernetes.io/storage-class`.

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by gyliu513** [comment]
```
metadata:
  annotations:
  {{- if .Values.server.persistentVolume.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.server.persistentVolume.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
```

Do we need to maintain the `alpha` and `beta` here? In the Kubernetes 1.6 release, dynamic provisioning has been promoted to stable (having entered beta in 1.4).  In 1.6, `StorageClassName` attribute has been added to `PersistentVolume` and `PersistentVolumeClaim` objects and should be used instead of annotation `volume.beta.kubernetes.io/storage-class`.  The beta annotation is still working in this release, however it will be removed in a future release. Checkout here https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#volumes-2 for detail.

**Comment by unguiculus** [comment]
I agree that we should migrate. However, this is not an automatic process. PRs are welcome.

**Comment by gyliu513** [comment]
@unguiculus why close this one? I may need to reference this if create some PRs.

**Comment by unguiculus** [comment]
Sorry, I reopened it.

**Comment by gyliu513** [comment]
@kubernetes/charts-maintainers I'm going to remove `volume.alpha.kubernetes.io/storage-class` and `volume.beta.kubernetes.io/storage-class` but use `StorageClassName` for all charts, please show your comments if any. Thanks.

**Comment by unguiculus** [comment]
Please make sure you create separate PRs per chart. Thanks.

**Comment by unguiculus** [comment]
Please use #1332 as reference.

**Comment by gyliu513** [comment]
Thanks @unguiculus , also mark https://github.com/kubernetes/helm/issues/2600 as related.

**Comment by gyliu513** [comment]
@prydonius @unguiculus all of the charts are now updated, please help review. Thanks!
