### ISSUE TITLE
[stable/dask] ability to set worker --nthreads and --nprocs independently of cpu resource limit

### ISSUE THREAD

**Issue by skeller88** [helm/charts#18708]
A dask worker node should be able to have --nthreads and --nprocs set via a user-provided helm chart, and have those values be independent of worker cpu resources. One use case is high I/O workloads that benefit from more threads than cores.

[Currently --nthreads is set to the worker cpu resource limit.](https://github.com/helm/charts/search?q=path%3A%2Fstable%2Fdask+nthreads&unscoped_q=path%3A%2Fstable%2Fdask+nthreads)

Aside from limiting dask helm deployment options, this limitation is problematic because [it leads users to believe that there needs to be a 1-1 relationship between cpus and threads](https://github.com/dask/distributed/issues/3205), which is not true. 

A solution is to have a new option in the helm chart:
```
worker:
    args:
        nthreads: 6
        nprocs: 2
```

Other worker command line options could be added in this way.

**Comment by leoxtc** [comment]
So currently I can not explicit set the nthreads from the helm chart config ?

**Comment by skeller88** [comment]
Correct. You can use the feature branch of my fork of this repo in the
meantime:
https://github.com/helm/charts/compare/master...skeller88:add-dask-num-worker-threads?expand=1

Clone my fork of chart repo to [chart-repo-dir] and then to deploy:

helm install -f helm_dask_chart.yaml ~/[chart-repo-dir]/stable/dask
