### ISSUE TITLE
[stable/airflow] unable to see the dags folder in /usr/local/airflow

### ISSUE THREAD

**Issue by prydeep** [helm/charts#18706]
Team,

I deployed helm using airflow helm charts
I don't see dags folder in airflow-web pod, the dags tab in the UI is empty
In the logs I see the "filling dagbag from /usr/local/airflow/dags"
If I do initdb then I see a airflow.db sqlite file created even though postgres is configured.

**Comment by SharanReddyK** [comment]
I still see this issue. Do we need to edit configmap-env.yaml file instead of values.yaml to see our changes?
