### ISSUE TITLE
[stable/prometheus-operator] node-exporter relabelings syntax error

### ISSUE THREAD

**Issue by gelo22** [helm/charts#18725]
**Describe the bug**

I see no 'target_label' in /etc/prometheus/config_out/prometheus.env.yaml which configured by nodeExporter.serviceMonitor.relabelings 

**Version of Helm and Kubernetes**:

Helm: v2.15.1

Kubernetes: v1.14.7-eks-e9b1d0

**Which chart**:

stable/prometheus-operator

**What happened**:

Values added:

~~~~
nodeExporter:
  serviceMonitor:
    relabelings:
      - sourceLabels: [__address__]
        separator: ;
        regex: ^(.*)$
        target_label: cluster_name
        replacement: 'eks_my-dev'
        action: replace
~~~~

Value appeared in config:

~~~~
- job_name: monitoring/prometheus-operator-node-exporter/0
...
  - target_label: endpoint
    replacement: metrics
  - source_labels:
    - __address__
    separator: ;
    regex: ^(.*)$
    replacement: eks_my-dev
    action: replace
- job_name: monitoring/prometheus-operator-operator/0
~~~~

**What you expected to happen**:

Value should be in config:

~~~~
- job_name: monitoring/prometheus-operator-node-exporter/0
...
  - target_label: endpoint
    replacement: metrics
  - source_labels:
    - __address__
    separator: ;
    regex: ^(.*)$
    target_label: cluster_name
    replacement: eks_my-dev
    action: replace
- job_name: monitoring/prometheus-operator-operator/0
~~~~

**How to reproduce it** (as minimally and precisely as possible):

Add example values.

Deploy

Se resulting file in container

alert: PrometheusBadConfig become active

**Anything else we need to know**:

**Comment by DaveSlinn** [comment]
They have modified the Helm chart target_label value to targetLabel (see https://github.com/coreos/prometheus-operator/issues/2503#issuecomment-478520117), but the values.yml comments have not been updated.  I have opened a PR to fix.  It is waiting for approval.
