### ISSUE TITLE
[stable/prometheus-pushgateway] Prometheus pushgateway is not scraped by prometheus by default?

### ISSUE THREAD

**Issue by billtohara** [helm/charts#18738]
Versions:

```bash
$ helm version
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.2", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-10-21T20:01:24Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

Am I correct in assuming that the installing the stable prometheus operator and pushgateway charts, should result in the pushgateway being scraped by default? 

For example, doing this..

Install Prometheus Operator:
```bash
helm install stable/prometheus-operator
```

Install Prometheus Push Gateway:
```bash
helm install stable/prometheus-pushgateway --set serviceMonitor.enabled=true
```

And port-forwarding from my laptop to the kubernetes cluster, I can push a metric to the gateway:

```bash
echo 'test_metric 3.15' | curl --data-binary @- http://localhost:9091/metrics/job/pushgateway/instance/laptoptest
```

And now my test metric correctly shows up on the pushgateway at http://localhost:9091/metrics

However, the pushgateway does not appear in the list of targets in prometheus (in http://localhost:9090/targets ). I assume it should? I also can't see the test_metric data either.

Out of the box, is more configuration needed?

**Comment by gabeduke** [comment]
I am having the same trouble.

**Comment by cstaud** [comment]
hi @billtohara i know this bug and have a pending PR https://github.com/helm/charts/pull/18877
due to the absence of the former owner i took ownership for this PR, unfortunately I cant `/lgtm` my own PRs so as soon I find someone to do so this should be fixed

**Comment by cstaud** [comment]
Should be fixed

**Comment by billtohara** [comment]
Thank you @cstaud 

So I should be able to pick this up from stable, using the same commands? I'm still using helm 2.15.1 and get the errors below. Should I upgrade to 2.16.1 or 3.0.0 to get your fix?

```bash
$ helm install stable/prometheus-operator

Error: release ringed-crocodile failed: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://garish-parrot-prometheus-o-operator.default.svc:443/admission-prometheusrules/mutate?timeout=30s: no endpoints available for service "garish-parrot-prometheus-o-operator"

# Don't expect this to work, but fwiw, it complains about the namespace.
$ helm install stable/prometheus-pushgateway --set serviceMonitor.enabled=true
Error: release youthful-jackal failed: namespaces "monitoring" not found
```

**Comment by cstaud** [comment]
As the error mentions the `monitoring` namespace is missing. The `serviceMonitor` resources needs to be created in the prometheus namespace (this is often monitoring, and used as default) so prometheus can watch for the services to monitor. Eighter you create a serviceMonitor in the desired namespace or you provide an custom namespace ate the values file you provide. 

Have a look at the documentation, `serviceMonitor.namespace`

Note: The prometheus-operator charts also offers a parameter to specify a namespace where it should look for serviceMonitor, I think its called `serviceMonitorNamespaceSelector`

**Comment by prashanth-sams** [comment]
@billtohara you can provision it directly in the `values.yaml` or manually run it during run-time
![image](https://user-images.githubusercontent.com/2948696/74325153-94d0b280-4da1-11ea-8a9a-ff5ebdfd593b.png)

**Comment by prashanth-sams** [comment]
@cstaud @billtohara the below is set by default, still the pushgateway is not scraped by the prometheus server
```
serviceMonitor:
  honorLabels: true
```
