### ISSUE TITLE
[stable/kube-ops-view] Not working with Kubernetes 1.16

### ISSUE THREAD

**Issue by klafbang** [helm/charts#18762]
**Describe the bug**
When upgrading the chart from 1.1.0 to 1.1.1 on a Kubernetes 1.16.2 cluster, I get an error.

**Version of Helm and Kubernetes**:
Kubernetes 1.16.2, Helm 2.14.3

**Which chart**:
kube-ops-view 1.1.0/1.1.1

**What happened**:
`
Error: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

`

**What you expected to happen**:
Upgrade successfully installed

**How to reproduce it** (as minimally and precisely as possible):
Upgrade (or install should also work) on any Kubernetes 1.16

**Anything else we need to know**:
This is known behavior; the deprecated resources with version v1beta1 have been removed from 1.16.  Upgrade the apiVersion to v1.  Might be an issue with other resources as well.

**Comment by Atharex** [comment]
Same problem here.. Please update the chart to support Kubernetes 1.16+

**Comment by klafbang** [comment]
Still not fixed, still a problem.

**Comment by klafbang** [comment]
Still not fixed, still a problem
