### ISSUE TITLE
[stable/redis] Replicas go down if master is unavailable

### ISSUE THREAD

**Issue by zhaakhi** [helm/charts#18772]
**Describe the bug**
The replica pods will take themselves out of service if the master is unhealthy, because both the readiness and liveness check verify master health as well. This means replicas do not increase availability.

**Version of Helm and Kubernetes**:
Tested with Kubernetes v1.16.2 and Helm v2.15.2

**Which chart**:
stable/redis-9.5.2

**What happened**:
Replica pods go down

**What you expected to happen**:
Replica pods should stay up and serve requests even if master pod is unavailable.

Healthchecks should use ping_readiness_local.sh/ping_liveness_local.sh, and not ping_readiness_local_and_master.sh/ping_liveness_local_and_master.sh by default.

**How to reproduce it** (as minimally and precisely as possible):
Verified by installing with default values and scaling down master
```sh
helm --kube-context minikube install stable/redis -n testredis --version 9.5.2
sleep 30
kubectl --context minikube scale statefulset testredis-master --replicas=0
sleep 60
kubectl --context minikube get pods
NAME                READY   STATUS    RESTARTS   AGE
testredis-slave-0   0/1     Running   1          91s
testredis-slave-1   0/1     Running   0          68s
```

**Comment by juan131** [comment]
Hi @zhaakhi 

This concept of running checks which target both local and master nodes was introduced quite a long time ago on this PR bye @jlegrone: https://github.com/helm/charts/pull/7622

The original purpose of this PR was to avoid authentication credentials to become out of sync between master and slave instances when an `existingSecret` reference is specified.

> This means replicas do not increase availability.

Please note this Helm chart does not deploy Redis on a HA architecture (there are no multiple master nodes as you'll find on a [Redis Cluster](https://redis.io/topics/cluster-tutorial) setup).

**Comment by zhaakhi** [comment]
I see. Would it be possible to make this configurable?
We would like to maintain read availability without the extra complexity of a Redis Cluster or Sentinel setup.

**Comment by juan131** [comment]
Hi @zhaakhi 

> I see. Would it be possible to make this configurable?

Sure, please feel free to create a PR to make this configurable and I'll be glad to review it.
