### ISSUE TITLE
[stable/wordpress] catch-22 GKE and https

### ISSUE THREAD

**Issue by hmeerlo** [helm/charts#18779]
I installed the wordpress helm chart with production values on GKE. An ingress is created and 3 pods spin up and do their job. But the load balancer marks the pods as unhealthy because it performs a healt check on '/' which MUST return a 200 according to the Google K8s docs. But the wordpress install insists on redirecting to the https version of the site because the GCLB refuses to send a "x-forwarded-proto: https" header. So now I'm in a catch-22 and I don't see a way out. What can I do?

**Comment by juan131** [comment]
Hi @hmeerlo 

Do you have a NFS provider installed on your GKE cluster? Please note that you cannot run more than a replica with the WordPress chart unless you have a NFS provider and you use a `ReadWriteMany` PVC(s) for your WP deployment. Find more information in the link below:

- https://github.com/helm/charts/tree/master/stable/wordpress#production-configuration

As you can see in the link below, the readiness/liveness probes are done using HTTPS when the parameter `healthcheckHttps` is set to `true`. Could you try to disable it (set it to `false`)?

- https://github.com/helm/charts/blob/master/stable/wordpress/templates/deployment.yaml#L158

**Comment by hmeerlo** [comment]
Hi @juan131 , sorry but I don't see the relation with the NFS provider. But yes, I have a NFS provider and the 3 instances are running succesfully. I tried enabling the healtcheckHttps, but that isn't picked up by the Google load balancer which still performs a http check. And I doubt whether it would work because the SSL is terminated on the load balancer itself.

**Comment by hmeerlo** [comment]
Ok, to prevent someone hitting this issue with a dreadful 'never mind I fixed it':

I worked around it by adding the following customHTAccessCM:
```
ErrorDocument 200 "ok"
RewriteEngine On
RewriteCond %{HTTP_USER_AGENT}  ^GoogleHC(.*)$
RewriteRule "/" - [R=200]
```

**Comment by juan131** [comment]
Hi @hmeerlo 

Sorry but I lost the track of this issue!

Thanks so much for sharing the workaround you used! It'll be extremely useful for other users facing the same issue, we really appreciate it.

**Comment by hmeerlo** [comment]
@juan131 This workaround has stopped working after upgrading to bitnami/wordpress chart. I managed to get the same htaccess file in /bitnami/wordpress/wordpress-htaccess.conf but it seems to be ignored. The GoogleHC user-agent keeps getting the 301 again. Any idea why that could be?
