### ISSUE TITLE
[stable/jenkins] jenkins.kubernetes-version macro doesn't work when kubernetes plugin version not specified

### ISSUE THREAD

**Issue by BryanHunt** [helm/charts#18774]
**Describe the bug**
If you add `kubernetes` to the list of `installPlugins` without a version, the `jenkins.kubernetes-version` macro will fail with the following error:

```
<semverCompare ">=1.20.2" (include "jenkins.kubernetes-version" .)>: error calling semverCompare: Invalid Semantic Version
```

Can the macro be updated to not fail if the version of the kubernetes plugin is not specified since that will install the latest versioin?

**Version of Helm and Kubernetes**:

Helm version
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```
Kubernetes: 1.16.2

**Which chart**:

Jenkins

**What happened**:

Helm failed to deploy chart

**What you expected to happen**:

Helm deployed chart successfully

**How to reproduce it** (as minimally and precisely as possible):

```yaml
  master:
    installPlugins:
    - kubernetes
```

**Anything else we need to know**:

You can work around the problem with:

```yaml
  master:
    installPlugins:
    - kubernetes:1.21.2
```

**Comment by venkatalolla** [comment]
@BryanHunt, I used the above-mentioned steps to reproduced the error and I found it to be working fine. 

This is what I specified in the values.yaml for the stable/Jenkins helm chart,
``` 
# List of plugins to be installed during Jenkins master start
master:
  installPlugins:
    - kubernetes
    - workflow-job:2.33
    - workflow-aggregator:2.6
    - credentials-binding:1.19
    - git:3.11.0
```
In the Jenkins pod,
```
# cat /var/jenkins_home/plugins.txt
kubernetes
workflow-job:2.33
workflow-aggregator:2.6
credentials-binding:1.19
git:3.11.0
```
In Jenkins Console > Plugins,
![Screen Shot 2019-11-11 at 3 09 20 PM](https://user-images.githubusercontent.com/22584063/68617611-a1d5c100-0495-11ea-8811-c8c17eac71b2.png)

Could you provide more insights into the error?
