### ISSUE TITLE
stable/promethues-operator kubelet alert still firing while disabled

### ISSUE THREAD

**Issue by acarsercan** [helm/charts#18799]
Hi,

Running
`prometheus-operator-7.4.0           	0.34.0`

Set kubelet scraping to disabled
``` 
kubelet:
  enabled: false
```
Yet alertmanager is still firing alerts

```
KubeletDown (1 active)
--
alert: KubeletDown expr: absent(up{job="kubelet"}   == 1) for: 15m labels:   severity: critical annotations:   message: Kubelet has disappeared from Prometheus target discovery.   runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletdown                                                                                  Labels                   State                   Active Since                   Value                                                                                                                  alertname="KubeletDown"                                            severity="critical"                                                           firing                   2019-11-11 20:58:18.181974688 +0000 UTC                   1 | 
```
Is this expected?

Regards

**Comment by vsliouniaev** [comment]
Please upgrade to the latest chart version. I believe the alert has been fixed

**Comment by acarsercan** [comment]
Unfortunately no, I'm using the latest Chart 0.34.0 and kubelet alerts are still firing

**Comment by vsliouniaev** [comment]
Sounds like you're using the coreos chart that was removed from the coreos/prometheus-operator repository many months ago and is no longer supported.

**Comment by acarsercan** [comment]
Apologies, I'm not following. I'm using `prometheus-operator-8.1.7` from

`https://console.cloud.google.com/storage/browser/kubernetes-charts?prefix=prometheus-operator`

**Comment by vsliouniaev** [comment]
Looks like these alerts are tied to
```yaml
prometheusOperator:
  kubeletService:
    enabled: true
```

**Comment by acarsercan** [comment]
Apologies, that fixed it

**Comment by vsliouniaev** [comment]
This is definitely not clear from the chart. In reality both of these things need to be turned on/off for the components which monitor the kubelets to be enabled / disabled.
