### ISSUE TITLE
[charts/stable/prometheus-operator] syntax errors

### ISSUE THREAD

**Issue by GoTheExtraMile** [helm/charts#18798]
**Describe the bug**
helm lint prometheus-operator
==> Linting prometheus-operator
[ERROR] templates/: parse error in "prometheus-operator/templates/prometheus-operator/deployment.yaml": template: prometheus-operator/templates/prometheus-operator/deployment.yaml:52: unexpected "=" in operand

**Version of Helm and Kubernetes**:
helm v2.11.0
kubectl v1.12.4

**Which chart**:
stable/prometheus-operator

**What happened**:
==> Linting prometheus-operator
[ERROR] templates/: parse error in "prometheus-operator/templates/prometheus-operator/deployment.yaml": template: prometheus-operator/templates/prometheus-operator/deployment.yaml:52: unexpected "=" in operand

**What you expected to happen**:
No syntax errors

**How to reproduce it** (as minimally and precisely as possible):
helm lint prometheus-operator

**Anything else we need to know**:
stable/prometheus-operator/templates/prometheus-operator/deployment.yaml

**Comment by vsliouniaev** [comment]
Which version of the chart are you using? The chart now requires Helm v2.12+ since version `8.0.0`.

**Comment by GoTheExtraMile** [comment]
Sorry I'm using helm 2.11.0
I will close this
