### ISSUE TITLE
Add @L3n41c as Trusted Collaborator

### ISSUE THREAD

**Issue by L3n41c** [helm/charts#18810]
Hello,

Like, @clamoriniere (#13120), @mfpierre (#13279) or @xlucas (#15587), I’ve joined the DataDog team and I will maintain the datadog chart.
Therefore, I would like to be added as trusted collaborator in order to ease the maintaining work of the datadog chart.

Thanks!

@hkaj

**Comment by hkaj** [comment]
Confirmed we need Lénaïc to have TC access to manage the Datadog chart here 👍

**Comment by L3n41c** [comment]
Hello,
I would still need the trusted collaborator status to work on the `stable/datadog` chart.

**Comment by L3n41c** [comment]
Hello @mattfarina,
Would you have time to have a quick look at this issue ?

Thanks in advance,
Lénaïc.

**Comment by L3n41c** [comment]
Hello @mattfarina,
Would you have a moment to have a look at this issue ?

Thanks!

**Comment by L3n41c** [comment]
Hello @mattfarina ,
Could you please have a look at this issue ?

Cheers,
Lénaïc.

**Comment by mattfarina** [comment]
@L3n41c sorry for the delay. You should have an invitation to collaborate waiting for you.

**Comment by irabinovitch** [comment]
Thans Matt.

**Comment by L3n41c** [comment]
Thanks you very murch @mattfarina.
Sorry as well: I just noticed you sent me the invitation during my holidays and the invitation has now expired. :-(
Would you mind sending me a fresh one ?

Lénaïc.

**Comment by irabinovitch** [comment]
@mattfarina 👋 would love a hand here.

**Comment by mattfarina** [comment]
@L3n41c I've sent you a new invitation

**Comment by L3n41c** [comment]
@mattfarina : I’ve accepted you invitation.
Thanks you very much !
