### ISSUE TITLE
[stable/redis] The containers couldn't start if we put rename-command FLUSHDB "" in redis.conf

### ISSUE THREAD

**Issue by vankhoa011** [helm/charts#18825]
**Describe the bug**
The containers couldn't start if we put `rename-command FLUSHDB ""` in redis.conf

**What happened**:

The containers couldn't start if we put `rename-command FLUSHDB ""` in redis.conf

**What you expected to happen**:

The container should start correctly.

**How to reproduce it** (as minimally and precisely as possible):
Remove 
  - FLUSHDB
  - FLUSHALL
in ` disableCommands` variable . Then, adding `rename-command FLUSHDB ""` and `rename-command FLUSHALL ""` in the configmap of `redis.conf` 

```
configmap: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
  rename-command FLUSHDB ""
  rename-command FLUSHALL ""
```
The logs of container is 
```
 02:29:23.14 INFO  ==> ** Starting Redis **

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 10
>>> 'rename-command FLUSHDB ""'
No such command in rename-command
```

**Comment by juan131** [comment]
Hi @vankhoa011 

This container provides an environment variable that allows you to specify the commands to disable as you can check in the link below:

- https://github.com/bitnami/bitnami-docker-redis/#disabling-redis-commands

You can set that environment variable using the `master.disableCommands` and `slave.disableCommands` parameters as you'll find in the link below:

- https://github.com/helm/charts/blob/master/stable/redis/README.md#parameters

Could you please give these parameters a try?

**Comment by vankhoa011** [comment]
Hi @juan131 
Sorry for late reply . I tested by adding this environment variable

```
        - name: DISABLE_COMMANDS
          value: FLUSHDB,FLUSHALL,CONFIG
``
And it's working.  So will I close the ticket or still keep it open ?

**Comment by juan131** [comment]
Great! I'm glad the environment variable worked for you @vankhoa011 

Please close the ticket if you consider it solved. Thanks in advance!
