### ISSUE TITLE
[stable/postgresql] Help with scripts

### ISSUE THREAD

**Issue by saic-laijw** [helm/charts#18826]
**Describe the bug**
I don't know if this is a bug but I needed some help- please direct me to the correct place as needed. Is there an order to which it is applied?

**Version of Helm and Kubernetes**:
2.11, 1.11

**Which chart**:
PostgreSQL

**What happened**:
I uploaded .sql files but they don't get applied to the postgres Database

**What you expected to happen**:
That the database would be modified by the .sql files.

**How to reproduce it** (as minimally and precisely as possible):
Add .sql

`CREATE USER test0 WITH PASSWORD 'password!';
CREATE USER test1 WITH PASSWORD 'password!';

CREATE TABLESPACE ts_foresight
    OWNER postgres
    LOCATION '/usr/data/tablespace_dir';

ALTER TABLESPACE ts_foresight
    OWNER TO postgres;

CREATE DATABASE foresight WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = ts_foresight
    CONNECTION LIMIT = -1;`

**Anything else we need to know**:

**Comment by juan131** [comment]
Hi @saic-laijw 

Could you please provide more information about how you're adding this `.sql` script?

- Are you locating them under the `files/docker-entrypoint-initdb.d`, using the `initdbScripts` parameter or using the `initdbScriptsConfigMap` (more info at https://github.com/helm/charts/tree/master/stable/postgresql#initialize-a-fresh-instance)?
- Are you installing the chart from scratch or updating an existing release?
- Could you share the PostgreSQL (primary) container logs?
- Did you enable replication (`replication.enabled=true`)?

**Comment by saic-laijw** [comment]
Hi @juan131 ,

I am locating them under the `files/docker-entrypoint-initdb.d` and I do not have replication.enabled=true...

The container logs are as follows, however the scripts don't run I've also attaached the psql when i get inside the container. 

` belligerent-macaw-postgresql postgresql 15:12:07.24                                                                                                                                                                                          │
│ belligerent-macaw-postgresql postgresql 15:12:07.24 Welcome to the Bitnami postgresql container                                                                                                                                              │
│ belligerent-macaw-postgresql postgresql 15:12:07.24 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql                                                                                            │
│ belligerent-macaw-postgresql postgresql 15:12:07.24 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues                                                                                        │
│ belligerent-macaw-postgresql postgresql 15:12:07.24 Send us your feedback at containers@bitnami.com                                                                                                                                          │
│ belligerent-macaw-postgresql postgresql 15:12:07.24                                                                                                                                                                                          │
│ belligerent-macaw-postgresql postgresql 15:12:07.25 INFO  ==> ** Starting PostgreSQL setup **                                                                                                                                                │
│ belligerent-macaw-postgresql postgresql 15:12:07.29 INFO  ==> Validating settings in POSTGRESQL_* env vars..                                                                                                                                 │
│ belligerent-macaw-postgresql postgresql 15:12:07.29 INFO  ==> Loading custom pre-init scripts...                                                                                                                                             │
│ belligerent-macaw-postgresql postgresql 15:12:07.29 INFO  ==> Initializing PostgreSQL database...                                                                                                                                            │
│ belligerent-macaw-postgresql postgresql 15:12:07.30 INFO  ==> postgresql.conf file not detected. Generating it...                                                                                                                            │
│ belligerent-macaw-postgresql postgresql 15:12:07.31 INFO  ==> pg_hba.conf file not detected. Generating it...                                                                                                                                │
│ belligerent-macaw-postgresql postgresql 15:12:08.85 INFO  ==> Starting PostgreSQL in background...                                                                                                                                           │
│ belligerent-macaw-postgresql postgresql 15:12:08.97 INFO  ==> Changing password of postgres                                                                                                                                                  │
│ belligerent-macaw-postgresql postgresql 15:12:08.98 INFO  ==> Configuring replication parameters                                                                                                                                             │
│ belligerent-macaw-postgresql postgresql 15:12:08.99 INFO  ==> Configuring fsync                                                                                                                                                              │
│ belligerent-macaw-postgresql postgresql 15:12:09.00 INFO  ==> Loading custom scripts...                                                                                                                                                      │
│ belligerent-macaw-postgresql postgresql 15:12:09.00 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...                                                                                                               │
│ belligerent-macaw-postgresql postgresql 15:12:09.00 INFO  ==> Starting PostgreSQL in background...                                                                                                                                           │
│ belligerent-macaw-postgresql postgresql 15:12:09.12 INFO  ==> Enabling remote connections                                                                                                                                                    │
│ belligerent-macaw-postgresql postgresql 15:12:09.13 INFO  ==> Stopping PostgreSQL...                                                                                                                                                         │
│ belligerent-macaw-postgresql postgresql 15:12:10.13 INFO  ==> ** PostgreSQL setup finished! **                                                                                                                                               │
│                                                                                                                                                                                                                                              ││ belligerent-macaw-postgresql postgresql 15:12:10.17 INFO  ==> ** Starting PostgreSQL **                                                                                                                                                      │
│ belligerent-macaw-postgresql 2019-11-14 15:12:10.182 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432                                                                                                                            │
│ belligerent-macaw-postgresql 2019-11-14 15:12:10.182 GMT [1] LOG:  listening on IPv6 address "::", port 5432                                                                                                                                 │
│ belligerent-macaw-postgresql 2019-11-14 15:12:10.185 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"                                                                                                                             │
│ belligerent-macaw-postgresql 2019-11-14 15:12:10.198 GMT [218] LOG:  database system was shut down at 2019-11-14 15:12:09 GMT                                                                                                                │
│ belligerent-macaw-postgresql 2019-11-14 15:12:10.202 GMT [1] LOG:  database system is ready to accept connections`


![image](https://user-images.githubusercontent.com/56410341/68870203-8272aa00-06c8-11ea-95d6-0b1a43c29f44.png)

**Comment by saic-laijw** [comment]
@juan131 Maybe if you can give me a sample working SQL script that or .sh script that you test on and I could also test on that would help confirm this...

**Comment by juan131** [comment]
Hi @saic-laijw 

> I am locating them under the files/docker-entrypoint-initdb.d and I do not have replication.enabled=true...

So I guess you cloned the https://github.com/helm/charts/ repo, right?

I don't see any interesting logs after the line below:

```
Loading user's custom files from /docker-entrypoint-initdb.d
```

Could you please enable the "debug logs" by setting the `image.debug` parameter to `true`? Then please share the logs again.

> Please format the logs next time you shared them since it's really hard do read in the current format.

**Comment by saic-laijw** [comment]
@juan131 Thank you, yes I cloned the git repo

Sorry about the logs- I'll format them for you. 

Looks like I'm getting an error on the scripts - Would you be able to provide some guidance? 

`invisible-seahorse-postgresql ERROR:  relation "foresight.woskilljoin" does not exist                                                                                                                     │
│ invisible-seahorse-postgresql LINE 1: INSERT INTO foresight.woskilljoin VALUES (6, 1, 16);                                                                                                                │
│ invisible-seahorse-postgresql                     ^                                                                                                                                                       │
│ invisible-seahorse-postgresql 2019-11-18 16:13:28.328 GMT [173] ERROR:  relation "foresight.woskilljoin" does not exist at character 13                                                                   │
│ invisible-seahorse-postgresql 2019-11-18 16:13:28.328 GMT [173] STATEMENT:  INSERT INTO foresight.woskilljoin VALUES (6, 1, 16);                                                                          │
│ invisible-seahorse-postgresql ALTER SEQUENCE                                                                                                                                                              │
│ invisible-seahorse-postgresql postgresql 16:13:28.33 INFO  ==> Enabling remote connections                                                                                                                │
│ invisible-seahorse-postgresql postgresql 16:13:28.34 INFO  ==> Stopping PostgreSQL...                                                                                                                     │
│ invisible-seahorse-postgresql 2019-11-18 16:13:28.344 GMT [132] LOG:  received smart shutdown request                                                                                                     │
│ invisible-seahorse-postgresql 2019-11-18 16:13:28.348 GMT [132] LOG:  background worker "logical replication launcher" (PID 139) exited with exit code 1                                                  │
│ invisible-seahorse-postgresql 2019-11-18 16:13:28.348 GMT [134] LOG:  shutting down                                                                                                                       │
│ invisible-seahorse-postgresql 2019-11-18 16:13:28.378 GMT [132] LOG:  database system is shut down                                                                                                        │
│ invisible-seahorse-postgresql postgresql 16:13:29.34 INFO  ==> ** PostgreSQL setup finished! **`

**Comment by juan131** [comment]
Hi @saic-laijw 

Sorry I lost the track of this issue. 

It looks like your scripts are failing:

```
invisible-seahorse-postgresql ERROR: relation "test1.mytable" does not exist
invisible-seahorse-postgresql
invisible-seahorse-postgresql 2019-11-18 16:13:28.328 GMT [173] ERROR: relation "foresight.woskilljoin" does not exist at character 13
```

Are you able to reproduce the issue if you launch the database with no initscripts, and you manually do the same queries?
