### ISSUE TITLE
[jenkins] chart broken for k8s v1.5.x

### ISSUE THREAD

**Issue by pswenson** [helm/charts#1882]
**Version of Helm and Kubernetes**:
k8s v1.5.6

**Which chart**:
jenkins

**What happened**:
this commit breaks k8s 1.5.6:  https://github.com/kubernetes/charts/commit/fecc804fc236e26d561711e590a4b5bd0ed55127

error on console:  `invalid field initContainers for v1.PodSpec`

**How to reproduce it** (as minimally and precisely as possible):
deploy master/latest stable jenkins chart to k8s 1.5.6

**Comment by MostAwesomeDude** [comment]
Can we reuse this issue for other broken charts, or should they have their own issues?

stable/mongodb-replicaset fails for me:

```
$ helm --kube-context blanu-dal12 install stable/mongodb-replicaset
Error: error validating "": error validating data: [found invalid field affinity for v1.PodSpec, found invalid field initContainers for v1.PodSpec]
```

stable/mariadb and stable/mysql fail too with a slightly different error:

```
$ helm --kube-context blanu-dal12 install stable/mariadb
Error: error validating "": error validating data: found invalid field initContainers for v1.PodSpec
```

This is on k8s 1.5.6 on Bluemix Containers:

```
$ kubectl --context blanu-dal12 version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6+114f891", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"not a git tree", BuildDate:"2017-08-18T01:05:53Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.6-4+abe34653415733", GitCommit:"abe346534157336e6bd5a70702756cff19d43a49", GitTreeState:"clean", BuildDate:"2017-05-18T16:52:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by unguiculus** [comment]
These charts are not broken. It's just that we cannot support backwards compatibility for any version out there. We decided to support the current and the previous release which would be 1.6 and 1.7. You may try and install older versions.
