### ISSUE TITLE
[stable/influxdb] Documentation: Minimum Kubernetes version

### ISSUE THREAD

**Issue by stickeegreg** [helm/charts#18833]
**Describe the bug**
Prerequisites says `Kubernetes 1.4+` but since stable/influxdb chart version 2.0 I believe this should be 1.14+, since the Ingress is now under `networking.k8s.io/v1beta1`

**Comment by Aisuko** [comment]
Thanks, this will be fixed right now.

**Comment by Aisuko** [comment]
remove label

**Comment by stickeegreg** [comment]
This is still an issue
