### ISSUE TITLE
[stable/velero] Make the velero-restic-restore-helper init-container configurable in values.yaml

### ISSUE THREAD

**Issue by thabach** [helm/charts#18844]
I would like to be able to configure the _velero-restic-restore-helper_ init-container in `values.yaml` as part of the `helm` installation run.

While the `image.repository` setting is taken into account in assembling the velero image path, the _velero-restic-restore-helper_ init-container image name is **not** affected by it. Customisation of the full qualified image name can only be done via a ConfigMap (as described here, https://velero.io/docs/master/restic/) after the fact.

This would simplify the [restic](https://restic.net) based setup significantly.

**Comment by carlisia** [comment]
Requesting this issue be closed, tracking it now here: https://github.com/vmware-tanzu/helm-charts/issues/24
