### ISSUE TITLE
[stable/mongodb] Mongodb won't start when using standalone with enabling persistence

### ISSUE THREAD

**Issue by vincenthodicq** [helm/charts#18854]
**Describe the bug**
Hi team, I am trying to install a standalone version of mongodb with persistence enabled. I am using a kubernetes cluster on IBM Kubernetes Service.

**Version of Helm and Kubernetes**:
Helm client: 2.14.1
Helm server: 2.14.3
Kubernetes 1.15.5

**Which chart**:
stable/mongodb version 7.4.4

**What happened**:
PV is bound to the mongodb POD but POD restarted twice and logs indicated that signal 15 is received and that mongo is shutting down with code:0
See below screenshot for detail:
![Screen Shot 2019-11-13 at 18 00 39](https://user-images.githubusercontent.com/38909011/68786197-a63ddd80-063f-11ea-8e0d-dcde7e805572.png)

**What you expected to happen**:
Expect that the pod is started normally and mongodb is up and running

**How to reproduce it** (as minimally and precisely as possible):
Install helm chart with:
- persistence enabled
- replicaset disabled
- volumePermission enabled
- securityContext enabled
- metrics: disabled
- ingress enabled
My command line with helm is
helm install --version 7.4.4 --name mongo -f mongodb.yaml kubernetes/mongodb

**Anything else we need to know**:
Installation of the same helm chart with persistence disabled works perfectly.

**Comment by rafariossaa** [comment]
Hi @vincenthodicq ,
  That signal 15 could be due to kubernetes killing the pod. Could you try purging the deployment and enabling debug ? Let see what the logs show.
  How long does it take until the pod is up ?

**Comment by vincenthodicq** [comment]
Hi @rafariossaa 
I will do the test next monday and i'll copy/paster the logs right here.
