### ISSUE TITLE
[stable/traefik] storeconfig-job.yaml does not support nodeSelector label

### ISSUE THREAD

**Issue by geekmush** [helm/charts#18865]
**Describe the bug**
templates/storeconfig-job.yaml does not support the nodeSelector label, so when you attempt to enable storeAcme, the storeconfig-job pod may attempt to schedule on a Windows node (in a mixed node pool cluster).
 
**Version of Helm and Kubernetes**:
Helm 2.14.3
Kubernetes 1.14.7

**Which chart**:
stable/traefik

**What happened**:
Enabled storeAcme and the storeconfig-job kept getting scheduled to a Windows node (where it cannot run).  In this case, the Windows nodes had the least load, so the k8s scheduler keeps trying to throw them over there.

**What you expected to happen**:
With template support for nodeSelector, we can push the storeconfig-job pod to a linux node.

**How to reproduce it** (as minimally and precisely as possible):
Enable storeAcme in the values file and attempt to deploy in a mixed OS k8s cluster.

**Anything else we need to know**:
Should be an easy tweak?

**Comment by mullerlele** [comment]
Same here!
