### ISSUE TITLE
stable/sonarqube

### ISSUE THREAD

**Issue by smetal1** [helm/charts#18871]
While installing sonarqube from the helm chart, I am facing issues.

ERROR:
 Error: found in requirements.yaml, but missing in charts/ directory: postgresql, mysql : exit status 1

**Comment by oscarlofwenhamn** [comment]
How are you going about installing the chart, using the cloned `helm/charts` repo or using `helm install stable/sonarqube`?

I believe you can do `helm dependency update stable/sonarqube` or `helm dependency update <path-to-chart>` to make sure the packages found in requirements.yaml are downloaded as required.
