### ISSUE TITLE
[stable/lamp] Not working in Kubernetes 1.16

### ISSUE THREAD

**Issue by klafbang** [helm/charts#18875]
**Describe the bug**
When upgrading the chart from 1.1.1 to 1.1.2 on a Kubernetes 1.16.2 cluster, I get an error.

This is the same issue as #18762 but for a different chart.

**Version of Helm and Kubernetes**:
Kubernetes 1.16.2, Helm 2.14.3

**Which chart**:
lamp 1.1.1/1.1.2

**What happened**:
`
Error: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

`

**What you expected to happen**:
Upgrade successfully installed

**How to reproduce it** (as minimally and precisely as possible):
Upgrade (or install should also work) on any Kubernetes 1.16

**Anything else we need to know**:
This is known behavior; the deprecated resources with version v1beta1 have been removed from 1.16.  Upgrade the apiVersion to v1.  Might be an issue with other resources as well.

**Comment by mirill** [comment]
Not working here. Any ETA?

Thanks in advance.

**Comment by klafbang** [comment]
Still an issue
