### ISSUE TITLE
[stable/coredns] prometheus metrics not reachable

### ISSUE THREAD

**Issue by rio** [helm/charts#1888]
Helm version: `v2.6.0`
Kubernetes version: `v1.5.7`
Chart: `stable/coredns`

Prometheus is not able to scrape the coredns even if `middelware.prometheus.enabled` is set.
A port is missing on the pod and the middleware is only listening on localhost resulting in `connection refused` errors on the prometheus side.

**Comment by mgoodness** [comment]
Fixed by #1748
