### ISSUE TITLE
[stable/airflow] Add Support for KubernetesExecutor

### ISSUE THREAD

**Issue by DP19** [helm/charts#18917]
**Describe the solution you'd like**
I've seen other helm charts for using the KubernetesExecutor but they are not as robust as the current helm chart here. I'd like to have support for using the KubernetesExecutor in place of the CeleryExecutor 

**Describe alternatives you've considered**
I've found another [helm-chart](https://github.com/BrechtDeVlieger/airflow-kube-helm) that has support

**Comment by liorhar** [comment]
Is the KubernetesExecutor supported? I'm getting various errors when changing the executor type to Kubernetes. Same issue as described here - https://stackoverflow.com/questions/60130992/airflow-scheduler-fails-to-start-with-kubernetes-executor
