### ISSUE TITLE
[stable/mariadb] PVCs are not deleted

### ISSUE THREAD

**Issue by v-six** [helm/charts#18916]
**Describe the bug**
When creating a release of the latest `stable/mariadb` all pvcs are correctly created. But when I delete this release with the `--purge` option, all pvcs are still there.

**Version of Helm and Kubernetes**:
Helm : v2.14.3
Kubernetes : v1.15.5

**Which chart**:
`stable/mariadb`

**What happened**:
When creating a release of the latest `stable/mariadb` all pvcs are correctly created. But when I delete this release with the `--purge` option, all pvcs are still there.

**What you expected to happen**:
I expect that all pvcs of the release to be deleted on a `helm delete release --purge`.

**How to reproduce it** (as minimally and precisely as possible):
1. Create a release : `helm install --name my-release stable/mariadb`
2. List all PVCs : `kubectl get pvc` => `data-my-release-mariadb-master-0`, `data-my-release-mariadb-slave-0`
3. Delete the release with purge option : `helmet delete my-release --purge`
4. List all PVCs : `kubectl get pvc` => all previous pvcs are still there.

**Anything else we need to know**:

**Comment by carrodher** [comment]
Hi, thanks for reporting it but this is not an issue, is the way Helm was designed, please take a look at this similar issue in the Helm repository: https://github.com/helm/helm/issues/3313
