### ISSUE TITLE
Cannot deploy the prometheus chart

### ISSUE THREAD

**Issue by achanda** [helm/charts#1891]
**Is this a request for help?**:
Probably yes, but might be a bug.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kubernetes-charts/prometheus

**What happened**:
prometheus server failed to start. A describe on the pod shows this error:
```
AttachVolume.Attach failed for volume "pvc-6e7a71a3-8d82-11e7-a12a-06dcf18a34c1" : Error attaching EBS volume "vol-0b1eab155d8060e87" to instance "i-00f271310bb071941": IncorrectState: vol-0b1eab155d8060e87 is not 'available'.
```
AWS console shows that the volume is available and is mounted on the instance. The volume claim and volume both show up when I query those using kubectl.

**What you expected to happen**:
The pod should start properly

**How to reproduce it** (as minimally and precisely as possible):
- create a k8s cluster on AWS using kops
- initialize helm
- run `helm install --set serverFiles.alerts=./alerts kubernetes-charts/prometheus`

**Anything else we need to know**:

**Comment by chrisfu** [comment]
@achanda Did you create the cluster using Gossip-based discovery, or did you define a Route53 zone using `--dns-zone`?

My statefulsets worked fine when deploying Kops w/ Gossip (default), but unfortunately in two different AWS accounts I was having issues resolving names via Gossip *only* in us-east-1. I switched to defining a `--dns-zone` instead and now I'm seeing this issue.

```
$ helm version
kubeClient: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
cxServer: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-12T00:45:05Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
