### ISSUE TITLE
[stable/prometheus-operator] Upgrade from 6.4.0 to 7.x.x fails with Proxy Authentication Required

### ISSUE THREAD

**Issue by venugopalthati** [helm/charts#18926]
**Describe the bug**
Prometheus Operator helm chart upgrade from 6.4.0 to 7.4.0 version fails with Proxy Authentication Required.

**Version of Helm and Kubernetes**:
Helm Version: 2.14.1
Kubernetes Version: 1.14.3

**Which chart**:
stable/prometheus-operator

**What happened**:
Upgrade to version 7.4.0 from 6.4.0 failed with Proxy Authentication Required.

UPGRADE FAILED
Error: failed to create resource: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://prometheus-operator-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=30s: Proxy Authentication Required
Error: UPGRADE FAILED: failed to create resource: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://prometheus-operator-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=30s: Proxy Authentication Required

**What you expected to happen**:
Successfully upgrade to the version 7.4.0

**How to reproduce it** (as minimally and precisely as possible):

Install Prometheus Operator using helm chart stable/prometheus-operator version 6.4.0, Prometheus Operator image version v0.31.1 and Prometheus version v2.11.1 in the values.yaml file

```helm install --name prometheus-operator --namespace monitoring -f values.yaml --version 6.4.0 stable/prometheus-operator```

Upgrade Prometheus Operator using helm chart stable/prometheus-operator version 7.4.0, Prometheus Operator image version v0.34.0 and Prometheus version v2.14.0 in the values.yaml file

```helm upgrade prometheus-operator --namespace monitoring -f values.yaml --version 7.4.0 stable/prometheus-operator```

upgrade step failed with Proxy Authentication Required issue.

**Log**

UPGRADE FAILED
Error: failed to create resource: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://prometheus-operator-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=30s: Proxy Authentication Required
Error: UPGRADE FAILED: failed to create resource: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://prometheus-operator-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=30s: Proxy Authentication Required

**Anything else we need to know**:
Our Kubernetes cluster is self managed and I was able work around the issue by deleting Webook configurations before the upgrade step. Found one comment in another thread about this work around for different issue: https://github.com/helm/charts/issues/16174#issuecomment-532170555

kubectl delete MutatingWebhookConfiguration prometheus-operator-admission
kubectl delete ValidatingWebhookConfiguration prometheus-operator-admission

**Comment by vsliouniaev** [comment]
Sounds like you have something preventing communication between the API server and the prometheus rules validation endpoint that's part of the prometheus operator pod. Do you have some kind of firewalls / anything else running that could be having an effect?
