### ISSUE TITLE
[stable/mongodb-replicaset] Does not have a valid replica set config

### ISSUE THREAD

**Issue by ghost** [helm/charts#18937]
on Google Kubernets Engine 
kubernets version: v1.13.11-gke.14

"ismaster" : false,
        "secondary" : false,
        "info" : "Does not have a valid replica set config",

**Comment by devjani** [comment]
Did you solved this issue.

**Comment by bruesky** [comment]
> Did you solved this issue?
I just use this.
rs.initiate({_id: "rs0", version: 1, members: [ { _id: 0, host : "pod ip:27017" }, { _id: 1, host : "pod ip:27017" }, { _id: 2, host : "pod ip:27017" } ]});
