### ISSUE TITLE
[stable/spinnaker] No support for ingress paths with Gate and Deck

### ISSUE THREAD

**Issue by darkn3rd** [helm/charts#18939]
**DESCRIPTION**

With spinnaker chart, you cannot specify ingress paths for both endpoints, Gate (API) and Deck (UI), and defaults them to `/` or `/*`.

Strangely, internally, the chart configures internal `overrideBaseUrl` for gate with default `/gate`, so configuring an ingress, will render the solution inoperable.

**SOLUTION**

Allow the user to specify a `path:` for Deck service (UI), which is under `ingress:` key and Gate service (API), which is under `ingressGate`.  

This way a user could specify a single hostname, e.g. `spinnaker.mycompany.com` for both endpoints, but have something like `/gate` (default by the helm chart internally regardless of ingress) or `/api/v1` for gate.

**ALTERNATIVES**

Due to this hard limitation in the helm chart, the only way to achieve this is to configure the Ingress outside of the Helm chart.

**Comment by Hokwang** [comment]
This is very important thing!!

**Comment by darkn3rd** [comment]
Not stale
