### ISSUE TITLE
[nfs-server-provisioner] Can't be installed on Kubernetes 1.16

### ISSUE THREAD

**Issue by RobinJ1995** [helm/charts#18938]
**Describe the bug**
`stable/nfs-server-provisioner` cannot be installed on Kubernetes 1.16.

**Version of Helm and Kubernetes**:
Helm 2.15.1
Kubernetes 1.16.2

**Which chart**:
`stable/nfs-server-provisioner`

**What happened**:
Tried to install `stable/nfs-server-provisioner`.
```
$ helm install stable/nfs-server-provisioner --set persistence.enabled=true,persistence.size=5Gi                                          
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
```

**What you expected to happen**:
`nfs-server-provisioner` to be installed.

**How to reproduce it** (as minimally and precisely as possible):
Run `helm install stable/nfs-server-provisioner --set persistence.enabled=true,persistence.size=5Gi` against a Kubernetes 1.16 cluster.

**Anything else we need to know**:
Some of the APIs got moved around/deprecated in Kubernetes 1.16.

**Comment by toimela** [comment]
Duplicate of #18372

**Comment by toimela** [comment]
Duplicate of: #18372
There is already a PR for this: #18509
