### ISSUE TITLE
[stable/sonarqube] default plugins are always ignored

### ISSUE THREAD

**Issue by jbrekelmans** [helm/charts#18931]
**Describe the bug**
The plugins in the SonarQube image (`sonarqube:7.9.1-community`) are never loaded, regardless of the value of `plugins.deleteDefaultPlugins`. The plugins baked in the image are the following 
(`docker run --entrypoint ls sonarqube:7.9.1-community /opt/sonarqube/extensions/plugins`):
```bash
README.txt
sonar-auth-github-plugin-1.5.0.870.jar
sonar-auth-saml-plugin-1.1.0.181.jar
sonar-csharp-plugin-7.15.0.8572.jar
sonar-css-plugin-1.1.1.1010.jar
sonar-flex-plugin-2.5.1.1831.jar
sonar-go-plugin-1.1.1.2000.jar
sonar-html-plugin-3.1.0.1615.jar
sonar-jacoco-plugin-1.0.2.475.jar
sonar-java-plugin-5.13.1.18282.jar
sonar-javascript-plugin-5.2.1.7778.jar
sonar-kotlin-plugin-1.5.0.315.jar
sonar-ldap-plugin-2.2.0.608.jar
sonar-php-plugin-3.2.0.4868.jar
sonar-python-plugin-1.14.1.3143.jar
sonar-ruby-plugin-1.5.0.315.jar
sonar-scala-plugin-1.5.0.315.jar
sonar-scm-git-plugin-1.8.0.1574.jar
sonar-scm-svn-plugin-1.9.0.1295.jar
sonar-typescript-plugin-1.9.0.3766.jar
sonar-vbnet-plugin-7.15.0.8572.jar
sonar-xml-plugin-2.0.1.2020.jar
```
The main SonarQube containers always has a directory mounted at /opt/sonarqube/extensions/plugins (see https://github.com/helm/charts/blob/edea140d6b10b6338140f95eb4bcc86e887b01bd/stable/sonarqube/templates/deployment.yaml#L196), and the directory is initially empty and only populated from URLs in the `plugins.install` value. This seems like a bug because the value `plugins.deleteDefaultPlugins` can be set, but is useless at the moment.

**Version of Helm and Kubernetes**:
Helm version: 2.16.1
Kubernetes version: 1.10

**Which chart**:
The latest version of the stable/sonarqube chart: 3.2.5

**What happened**:
No plugins are installed in SonarQube when `plugins.deleteDefaultPlugins` is `false`.

**What you expected to happen**:
The default plugins in the SonarQube image are loaded.

**How to reproduce it** (as minimally and precisely as possible):
Manifest the chart with all default values and deploy it to Kubernetes (`plugins.deleteDefaultPlugins` is initially unset/falsy). Observe that the logs say no plugins are loaded and no configuration is available in the User Interface (navigate to Administration).

**Anything else we need to know**:
-

**Comment by jdamour98** [comment]
reopen

**Comment by jdamour98** [comment]
@rjkernick could you please take a look? sorry to @
