### ISSUE TITLE
[stable/chart/redis] Latest stable not working. see the excpetion.

### ISSUE THREAD

**Issue by tehale** [helm/charts#18941]
**Describe the bug**

**Version of Helm and Kubernetes**:

**Which chart**:
 stable/redis

**What happened**:

$ helm install --name redis stable/redis --values redis/values.yaml --namespace redis
Error: render error in "redis/templates/redis-slave-statefulset.yaml": template: redis/templates/redis-slave-statefulset.yaml:87:18: executing "redis/templates/redis-slave-statefulset.yaml" at <eq .Values.securityContext.runAsUser 0.0>: error calling eq: incompatible types for comparison

**What you expected to happen**:
chart get deployed.

**How to reproduce it** (as minimally and precisely as possible):

run : 
helm install --name redis stable/redis --values redis/values.yaml --namespace redis
**Anything else we need to know**:

**Comment by tehale** [comment]
Mine is 9.5.4

**Comment by tehale** [comment]
And I am not using custom values. However version 8.0.18 get deployed
correctly for me.

**Comment by alemorcuq** [comment]
Which Helm version are you using, @tehale? Maybe that way I can reproduce this.

**Comment by guimaluf** [comment]
I'm getting the same error
```
$ helm search stable/redis 
NAME            CHART VERSION   APP VERSION     DESCRIPTION                                    
stable/redis    9.5.5           5.0.7           Open source, advanced key-value store. It is often referr...
stable/redis-ha 4.0.4           5.0.5           Highly available Kubernetes implementation of Redis

$ helm install stable/redis  
Error: render error in "redis/templates/redis-slave-statefulset.yaml": template: redis/templates/redis-slave-statefulset.yaml:87:18: executing "redis/templates/redis-slave-statefulset.yaml" at <eq .Values.securityContext.runAsUser 0.0>: error calling eq: incompatible types for comparison
```

**Comment by alemorcuq** [comment]
Hi, @guimaluf.

Could you please share the command that you are using to install this chart and get this error? I can't reproduce it:

```
❯ helm2.15 install -n redis-amoreno --namespace redis-amoreno stable/redis --version 9.5.5 --set securityContext.runAsUser=0,securityContext.enabled=true
NAME:   redis-amoreno
LAST DEPLOYED: Fri Nov 22 08:11:41 2019
NAMESPACE: redis-amoreno
STATUS: DEPLOYED

❯ helm2.15 version
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

Regards,
Alejandro

**Comment by tehale** [comment]
My helm version is 2.14.3 client and server 2.15.0
I ran it from windows 10

**Comment by tehale** [comment]
My helm version is 2.

**Comment by macropin** [comment]
I've previously deployed `9.5.4` with helm `3.0.0`. Might want to try a newer version.

**Comment by tehale** [comment]
Please close the issue.

**Comment by alemorcuq** [comment]
Did you fix the issue, @tehale ?

**Comment by guimaluf** [comment]
seems to have been fixed
```
20:41 ➜  ~  helm version 
version.BuildInfo{Version:"v3.0", GitCommit:"", GitTreeState:"", GoVersion:"go1.13.6"}
20:41 ➜  ~  minikube version
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty
```

**Comment by alemorcuq** [comment]
That's good to know, @guimaluf! Which version of the chart are you using?

**Comment by guimaluf** [comment]
I'm probably using latest. Just rerun `$ helm install stable/redis` for the sake of this issue and all went smooth. I didn't check any further detail.
