### ISSUE TITLE
[stable/prometheus] <$value.groups>: can't evaluate field groups in type interface {}

### ISSUE THREAD

**Issue by gboor** [helm/charts#18942]
**Describe the bug**
When trying to install Prometheus using a fairly standard config I get the following;

```
Error: render error in "prometheus/templates/server-configmap.yaml": template: prometheus/templates/server-configmap.yaml:17:43: executing "prometheus/templates/server-configmap.yaml" at <$value.groups>: can't evaluate field groups in type interface {}
```

I think this may have something to do with #18112 

**Version of Helm and Kubernetes**:
Helm: v2.16.1
Kubernetes: 1.13.11-gke.14

**Which chart**:
stable/prometheus

**What happened**:
I tried to install it, it cannot render part of the chart and fails to install.

**What you expected to happen**:
Prometheus to be installed

**How to reproduce it** (as minimally and precisely as possible):
Take the basic values file and try to install the chart - that's all.

**Comment by gboor** [comment]
New note; I downloaded the chart and manually reverted the change in #18112 and it installed fine.

**Comment by premkumar-gg** [comment]
Hey @gboor .. here is a PR waiting to be merged that would fix the bug introduced.. [https://github.com/helm/charts/pull/18814](https://github.com/helm/charts/pull/18814)

**Comment by gboor** [comment]
@premkumar-gg that is good news! I'll add a note there. Thanks.
