### ISSUE TITLE
[stable/spinnaker] Doesn't support DockerRegistry password-command req for ECR

### ISSUE THREAD

**Issue by darkn3rd** [helm/charts#18940]
d**DESCRIPTION**

The spinnaker chart allows you to specify a number of Docker Registries, which requires a `password`, and does not support a `password-command` that is required for solutions that need to refresh tokens, such as Amazon's ECR.

**SOLUTION**

The solution would be to support a password-command as an alternative to password:
```
dockerRegistries:
- name: ecr
  username: AWS
  address: XXXXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com
  password-command: >
    aws ecr get-authorization-token
    --region us-west-2
    --output text
    --query 'authorizationData[].authorizationToken' |
    base64 -d | sed 's/^AWS://'
```

**ALTERNATIVES**

Currently exploring possibility of using a shell script to configure DockerRegistry outside of the limited mechanism supported by the Helm chart, e.g. 

```
additionalScripts:
    create: true
    data:
      configure_ecr.sh: > 
        # script goes here
```

Another alternative would be to simply pass the token (but this will expire eventually) and adding  a side car container to refresh the stored secret.

**Comment by mced** [comment]
@darkn3rd Do you think the pr https://github.com/helm/charts/pull/15564 will fit your use case ?

**Comment by camilosantana** [comment]
@darkn3rd perhaps

- add kube2iam to your cluster
- create a role that clouddriver can assume
  - attach respective policies
- add an annotation to clouddriver (noted in the yaml file) that specifies above role

no keys or secrets to handle ever

**Comment by yhware** [comment]
@camilosantana I don't think your approach works. I tried it but even though the IAM role that's been assumed has ECR read privileges, it's still necessary to get login token from ECR hence the need for passwordcommand

**Comment by darkn3rd** [comment]
@mced I think it might indeed.  I have not tried it.  Some test cases would be (1) only password file config, (2) only password-command config, (3) mixed.  The AWS CLI shouldn't be required on halyard.  

My current workaround is with using `halyard.additionalSecrets`, `halyard.additionalConfigMaps`, and `halyard.additionalScripts`, and running the commands in the shell script.

**Comment by darkn3rd** [comment]
@camilosantana FYI. The eks cluster worker nodes (ec2) already policy of `AmazonEC2ContainerRegistryPowerUser`, so all pods on the cluster have access to ECR.  There's no access problems in that scope.

The issues has to do with the [Docker Registry HTTP API V2](Docker Registry HTTP API V2) that requires an access token.  Unlike other Docker registries (e.g. docker hub, quay), ECR rotates the access token, so Clouddriver needs a way to use a new access token.  This was solved with a sidecar container that updates a shared passwordfile, but later Spinnaker contributor added support of `password-command` option, and another PR added aws cli to Clouddriver docker image, both needed to support ECR.  The problem is that the helm chart was also not updated to support this new feature.
