### ISSUE TITLE
[stable/sentry] Add LDAP support to sentry chart

### ISSUE THREAD

**Issue by anitabee** [helm/charts#18953]
@okgolove,
@rothgar 
Would you be interested in a PR for adding LDAP integration for Sentry?

**Is your feature request related to a problem? Please describe.**
I already have chart with this implementation. I want to get rid of my fork and rather than to maintain extra chart it makes more sense to integrate this in official helm's chart, and be able to contribute back. 

**Describe the solution you'd like**
Adding conditional support for LDAP configuration, extra installation tools for Sentry image that support LDAP integration and some other things.

**Comment by okgolove** [comment]
Hi @anitabee. Sounds good to me.
Feel free to create a PR.

**Comment by jlefebure** [comment]
Interested to get the fork implementation
