### ISSUE TITLE
[stable/superset] chart not working for Superset version 0.35.0

### ISSUE THREAD

**Issue by vikram-katkar** [helm/charts#18951]
**Describe the bug**
Pods are crashing for Superset version 0.35.0 with error:
```
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
2019-11-18 11:15:13,132:INFO:root:logging was configured successfully
2019-11-18 11:15:13,335:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
2019-11-18 11:15:13,775:DEBUG:asyncio:Using selector: EpollSelector
Usage: superset [OPTIONS] COMMAND [ARGS]...

Error: No such command "runserver".
Loaded your LOCAL configuration at [/home/superset/superset_config.py]

```

**Version of Helm and Kubernetes**:
Helm: v2.16.1
Kubernetes: 1.13.11-gke.14

**Which chart**:
stable/superset

**What happened**:
Pods crashing repeatedly 

**What you expected to happen**:
Superset to be up and running

**How to reproduce it** (as minimally and precisely as possible):
helm install superset with PV enabled with Loadbalancer on GKE

**Anything else we need to know**:

**Comment by peteryin21** [comment]
Same here. It looks like they removed the `superset runserver` command in: https://github.com/apache/incubator-superset/commit/70be44afe18c577d7da94c3420772000d39c2cb8.
```
"The Gunicorn 'superset runserver' command is deprecated. Please "	
            "use the 'gunicorn' command instead.
```
I'm assuming the "gunicorn" command is something like [this](https://github.com/apache/incubator-superset/commit/70be44afe18c577d7da94c3420772000d39c2cb8#diff-e5e366558367e1f3ee406941f0d903e8L134-L140)

**Comment by skeleton007** [comment]
@peteryin21 
Yes. I found the same. `superset runserver` command is not available anymore.

I'm not a Superset expert but after trial-and-error,
replacing `superset runserver` with `gunicorn superset:app` in values.yaml resolved the issue.

I need an expert advice on this. Any help please?
