### ISSUE TITLE
[incubator/jaeger] query sidecar agent has no resource request

### ISSUE THREAD

**Issue by juliantaylor** [helm/charts#18981]
the sidecar to the jaeger-query deployment has no resource requests:
https://github.com/helm/charts/blob/master/incubator/jaeger/templates/query-deploy.yaml#L112

**Which chart**:
incubator/jaeger

**What you expected to happen**:
All pods should have resource requests so the kubernetes scheduling works correctly.

**Comment by davidkarlsen** [comment]
The chart has been deprecated / moved: https://github.com/helm/charts/commit/42892c2304f89d389ab7cd747d591d876fadb0e5
