### ISSUE TITLE
Adding nodeSelector to charts

### ISSUE THREAD

**Issue by gyliu513** [helm/charts#1899]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:
All

**What happened**:
Kuberntes support x86, POWER, Z, we can use `nodeSelector` to deploy applications using different arch, but now all charts do not have such value, we should add it.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

/cc @kubernetes/charts-maintainers 

Charts need to be updated:
- [ ] incubator/common
- [ ] incubator/docker-registry
- [ ] incubator/elasticsearch
- [ ] incubator/etcd
- [ ] incubator/gogs
- [ ] incubator/istio
- [ ] incubator/kafka
- [ ] incubator/kube-registry-proxy
- [ ] incubator/redis-cache
- [ ] incubator/spring-cloud-data-flow
- [ ] incubator/tensorflow-inception
- [ ] incubator/zookeeper
- [ ] stable/acs-engine-autoscaler
- [ ] stable/artifactory
- [ ] stable/centrifugo
- [ ] stable/chaoskube
- [ ] stable/chronograf
- [ ] stable/cockroachdb
- [ ] stable/concourse
- [ ] stable/consul
- [ ] stable/coredns
- [ ] stable/coscale
- [ ] stable/dask-distributed
- [ ] stable/datadog
- [ ] stable/dokuwiki
- [ ] stable/drupal
- [ ] stable/factorio
- [ ] stable/g2
- [ ] stable/gcloud-endpoints
- [ ] stable/ghost
- [ ] stable/gitlab-ce
- [ ] stable/gitlab-ee
- [ ] stable/influxdb
- [ ] stable/ipfs
- [ ] stable/jasperreports
- [ ] stable/jenkins
- [ ] stable/joomla
- [ ] stable/kapacitor
- [ ] stable/kube-ops-view
- [ ] stable/kube-state-metrics
- [ ] stable/linkerd
- [ ] stable/locust
- [ ] stable/magento
- [ ] stable/mariadb
- [ ] stable/mediawiki
- [ ] stable/memcached
- [ ] stable/minecraft
- [ ] stable/minio
- [ ] stable/mongodb
- [ ] stable/mongodb-replicaset
- [ ] stable/moodle
- [ ] stable/mysql
- [ ] stable/namerd
- [ ] stable/nginx-lego
- [ ] stable/odoo
- [ ] stable/opencart
- [ ] stable/openvpn
- [ ] stable/orangehrm
- [ ] stable/osclass
- [ ] stable/owncloud
- [ ] stable/parse
- [ ] stable/percona
- [ ] stable/phabricator
- [ ] stable/phpbb
- [ ] stable/prestashop
- [ ] stable/rabbitmq
- [ ] stable/redmine
- [ ] stable/rethinkdb
- [ ] stable/risk-advisor
- [ ] stable/rocketchat
- [ ] stable/sapho
- [ ] stable/selenium
- [ ] stable/sensu
- [ ] stable/sentry
- [ ] stable/spark
- [ ] stable/spotify-docker-gc
- [ ] stable/stash
- [ ] stable/sugarcrm
- [ ] stable/suitecrm
- [ ] stable/sumokube
- [ ] stable/sumologic-fluentd
- [ ] stable/sysdig
- [ ] stable/telegraf
- [ ] stable/testlink
- [ ] stable/uchiwa
- [ ] stable/voyager
- [ ] stable/weave-cloud
- [ ] stable/wordpress

**Comment by gyliu513** [comment]
@kubernetes/charts-maintainers any comments for this proposal?

**Comment by prydonius** [comment]
I agree that this should be added, some charts already have this option I believe.

**Comment by gyliu513** [comment]
@prydonius so how about fix those charts one by one or create one PR to fix all charts?

**Comment by prydonius** [comment]
@gyliu513 separate PRs, it would also be useful to have a list in the first comment on this issue (e.g. https://github.com/kubernetes/charts/issues/1785)

**Comment by LeonLiuY** [comment]
In addition to `nodeSelector`, it would be nice if other scheduling control features are also supported.

http://blog.kubernetes.io/2017/03/advanced-scheduling-in-kubernetes.html

For example

- Tolerations
- Affinity/Anti-Affinity

But this require the change of all charts, I think we might need to design another structure of charts or add some features to helm to support this.

**Comment by gyliu513** [comment]
@liuyang1204 good proposal.

@kubernetes/charts-maintainers It is becoming difficult to add new parameters to existing charts, as we request each chart one PR, when we want to add some parameters to those charts, it will be 100+ PRs, seems we need to find a common way for how to add new parameters for all of the charts.

**Comment by unguiculus** [comment]
I appreciate your effort, but the question is: Do we really need to proactively apply this to every chart?

**Comment by gyliu513** [comment]
I think this is needed, as there will be different requirement for the charts when they are going to be deployed, such as node requirement, label requirement etc. @unguiculus

**Comment by william-tran** [comment]
Shouldn't we be using affinities instead?

>`nodeSelector` continues to work as usual, but will eventually be deprecated, as node affinity can express everything that `nodeSelector` can express.

https://github.com/kubernetes/charts/pull/3876#issuecomment-368931064

**Comment by unguiculus** [comment]
A lot of charts already have node selectors. New charts created with `helm create` automatically get them. Since they seem to be deprecated, we shouldn't turn this into a global effort.

**Comment by nick4fake** [comment]
What about tolerations and affinity?

**Comment by gyliu513** [comment]
@nick4fake I think you can open some new issues to trace this requirement.
