### ISSUE TITLE
[stable/mariadb] How to provision a existing PVC for the mariadb Slave containers

### ISSUE THREAD

**Issue by abhi7788** [helm/charts#19015]
**Describe the bug**
Unable to find a way to use existing PVC for the slave containers. Master has a parameter with 
master.persistence.existingClaim which can be used to provision a existing pvc for the master pod, however the same is missing for the mariadb slave

**Version of Helm and Kubernetes**:
helm: 2.14.1
K8: v1.14.7

**Which chart**:
https://github.com/helm/charts/tree/master/stable/mariadb

**What happened**:
Unable to use existing PVC for the slave pods

**What you expected to happen**:
An existing pvc can be used for the slave pod as we are able to do it for master via 
master.persistence.existingClaim parameter. Expecting a similar kind of variable for slave 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by carrodher** [comment]
Thanks for the suggestion, I just created a PR with some changes in the chart to allow this use case.

**Comment by carrodher** [comment]
Apart from the PR, what is the use case to mount an existing PVC in a slave?
AFAIK, slaves copy the data from the master node and they can't be converted into a master node, so although technically it is possible (in the previous PR) I am not sure about the use case where it is useful or functional to add an existing PVC to a slave

**Comment by abhi7788** [comment]
Thanks alot for a quick turnaround. I am somehow not able to dynamically create pvc via this chart it stays in the pending state. I was able to bound the pvc with a seperate yamls and then with this existingpvclaim variable i was able to tie it back to the master pod. Therefore I requested for a additional variable to use an existing pvc in slaves.

**Comment by carrodher** [comment]
It seems there is an issue in the cluster configuration itself instead of the chart. Do you have configured any Volume Provisioner in the cluster? https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/

**Comment by abhi7788** [comment]
Yeah..I agree with that, there is no issues with chart at all..I am using this in my enterprise managed k8 cluster and it seems like they have configured some sort of Volume Provisioner and hence it only provision those volume which comply to that. I will try to reach out to them to confirm this assumption. But yeah having a flexibility to use existing volume in slaves does help in scenarios like this.

I have another question not related to this topic though; Currently this chart is running in Master slave replication mode, I was wondering is there any possibility to run this chart in Master Master replication mode or Is there anyway we can run Master replicas also. I am exploring this for a usecase where I am using my master node as an application database also ; in my case it is Airflow. So if my master goes down it will bring down the airflow along with it. Let me know if you have some details around this.

At last, thank you for such a quick response....really appreciate all your help on this and looking forward for this fix to get merged in the master branch.

**Comment by abhi7788** [comment]
--Update--
I tested few different combinations today with dynamically provisioning the volume with names like test-mariadb-slave-0 and storage type as nfs in chart but none of them worked for me. However when i tried provisioning it through storage type marked as iscsi it worked perfectly. Not sure why it was not working with nfs.

This also helped me to understand how I can run multiple replicas of my master. So far i was using an existing pvc in master, hence spining up multiple master pods was creating an error as they all were attached to the same pvc. attaching individual pvc to each master did the trick for me

**Comment by carrodher** [comment]
> Yeah..I agree with that, there is no issues with chart at all..I am using this in my enterprise managed k8 cluster and it seems like they have configured some sort of Volume Provisioner and hence it only provision those volume which comply to that. I will try to reach out to them to confirm this assumption. But yeah having a flexibility to use existing volume in slaves does help in scenarios like this.

Applying the changes in https://github.com/helm/charts/pull/19018 solve your issue? Did you test it?

> I have another question not related to this topic though; Currently this chart is running in Master slave replication mode, I was wondering is there any possibility to run this chart in Master Master replication mode or Is there anyway we can run Master replicas also. I am exploring this for a usecase where I am using my master node as an application database also; in my case it is Airflow. So if my master goes down it will bring down the airflow along with it. Let me know if you have some details around this.

There is a different solution ([MariaDB Galera](https://mariadb.com/kb/en/library/what-is-mariadb-galera-cluster/)) that is a multi-master database cluster solution for synchronous replication and high availability. Bitnami offers this solution as chart, but due to the Helm charts are moving from this centralized repository to distributed ones, this chart is not present in the `stable` repository, you can find it in the Bitnami one. You can find the chart code in [this GitHub repository](https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera) and you can do a test by running
```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install bitnami/mariadb-galera
```

**Comment by abhi7788** [comment]
Thanks..I completed my test for change #19018 and everything is running as per expectation. Thanks you for making the updates.

I will try the galera cluster also...Thanks for the information
