### ISSUE TITLE
[stable/prometheus-operator] defaultRules.rules.kubernetesSystem in k8s 1.14

### ISSUE THREAD

**Issue by jscheel42** [helm/charts#19033]
**Describe the bug**
Setting `defaultRules.rules.kubernetesSystem = false` does not disable the same alerts in k8s version >= 1.14 as it does in k8s version < 1.14.  I think this is caused by the differences in these 2 files:
* < 1.14: https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/rules/kubernetes-system.yaml
```
{{- if and (semverCompare ">=1.10.0-0" $kubeTargetVersion) (semverCompare "<1.14.0-0" $kubeTargetVersion) .Values.defaultRules.create .Values.defaultRules.rules.kubernetesSystem }}
```
* \>= 1.14: https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
```
{{- if and (semverCompare ">=1.14.0-0" $kubeTargetVersion) (semverCompare "<9.9.9-9" $kubeTargetVersion) .Values.defaultRules.create }}
```

**Version of Helm and Kubernetes**:
Helm: 2.15.1
Kubernetes: 1.14.7-gke.23

**Which chart**:
stable/prometheus-operator

**What happened**:
Alerts in `templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml` are not disabled when `defaultRules.rules.kubernetesSystem: false`

**What you expected to happen**:
Alerts in `templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml` are disabled when `defaultRules.rules.kubernetesSystem: false`

**How to reproduce it** (as minimally and precisely as possible):
Set `defaultRules.rules.kubernetesSystem: false` and view the generated CRDs defined by `prometheus/rules-1.14/kubernetes-system-apiserver.yaml` to verify that they are created.

**Anything else we need to know**:

**Comment by vsliouniaev** [comment]
Thanks for raising this, are you interested in contributing a fix to the scripts that sync the alerts?

**Comment by jscheel42** [comment]
I'm interested.  I could submit a pull request to resolve this issue.  I think the resolution should be straightforward if using `defaultRules.rules.kubernetesSystem` to control alerts in `templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml` is an acceptable solution.

**Comment by vsliouniaev** [comment]
Yes, this sounds right to me!

**Comment by jscheel42** [comment]
I opened #19285 to address this ticket.  I updated the chart version to 8.4.0 because the behavior of .Values.defaultRules.rules.kubernetesSystem changes.  Please let me know if another chart version would be more appropriate.
