### ISSUE TITLE
[stable/openldap] Provide customldif through a configmap

### ISSUE THREAD

**Issue by Joibel** [helm/charts#19039]
As a helm chart designer pulling in the openldap chart I'd like to be able to templatise my customldif file as part of my chart. I can't then provide that to this chart, as the only mechanism this provides is through the values, which are not templatisable.

I'd like to have a new values.yaml entry customLdifMap, which I can provide with the name of a configmap which this chart will consume to setup the initial state of the ldap server, in the same way that the existing customLdifFiles values allows.

I could inject the initial state using an external container, but this is prettier and involves much less duplication as it would perform similar duties to the initContainer in this chart.

My chart is used for demoing our product, and I'd like to allow some values in my chart to drive what users are available to the demo users for differing scenarios of use.

**Comment by Joibel** [comment]
I would still like this to be considered for inclusion. I have heard nothing from any humans. Thanks bot.

**Comment by merlindorin** [comment]
bump +1

**Comment by merlindorin** [comment]
...

**Comment by Joibel** [comment]
The pull request is still open, although no-one appears to be looking at it

**Comment by merlindorin** [comment]
@Joibel we are working at Renault on a fork (with a better kubernetes integration / security best practice) and will open source it in one month. If you are interested, ping me ;)
