### ISSUE TITLE
stable/jenkins helm chart has issue in documentation, ImagePullSecretName is referenced as imagePullSecret

### ISSUE THREAD

**Issue by arunsanna** [helm/charts#19032]
I am using remote repo configured to pull docker hub images. I have to use my secret to pull the images via my artifactory proxy.

stable/jenkins 1.9.4

As per documentation we can provide secret via `imagePullSecret` However as per chart its `imagePullSecretName` for both master and agent images
Please update the reference and also, It is missing how to deploy the chart if there we want to use existing storage class. This will be more helpful to deploy. No code updates necessary just doc updates

**Comment by danielcooperxyz** [comment]
This is still an issue, and it is not that easy to spot.
