### ISSUE TITLE
[stable/airflow] v4.4.1 change hits upstream airflow issue - (Apache Airflow is not at this location)

### ISSUE THREAD

**Issue by arthur-c** [helm/charts#19049]
Hello @omonnier 
The change https://github.com/helm/charts/commit/68dd2c8496d5c47906507a621755942e722dc397#diff-768de33902da0360904f34895d756c3e triggers https://issues.apache.org/jira/browse/AIRFLOW-3084

**Comment by pjaak** [comment]
Yeah i am facing the same issue aswell

**Comment by omonnier** [comment]
Hi. Pull request submitted: https://github.com/helm/charts/pull/19070

**Comment by arthur-c** [comment]
Hi @omonier,

I don't think that solve the issue. I discovered the bug while I was setting  `.Values.ingress.web.host` to a custom domain name. Any other value than http://localhost:8080 will hit the upstream bug.

Maybe it's better to have parameters dedicated for the ingress and ones for the `AIRFLOW__WEBSERVER__BASE_URL` option.

**Comment by arthur-c** [comment]
It might be related to hostname resolution at pod level ? Can you resolve `.Values.ingress.web.host`in the web pod ?

**Comment by omonnier** [comment]
@maver1ck @gsemet Any advice would be welcome about a proper resolution.
- Should we revert https://github.com/helm/charts/commit/68dd2c8496d5c47906507a621755942e722dc397#diff-768de33902da0360904f34895d756c3e ?
- Should we create a specific .Values for `AIRFLOW__WEBSERVER__BASE_URL` as suggested by @arthur-c  ?
- Should we merge https://github.com/helm/charts/pull/19070 ?
Thanks

**Comment by gsemet** [comment]
I prefer a dedicated value for AIRFLOW__WEBSERVER__BASE_URL (option 2)

**Comment by arthur-c** [comment]
I think that's a best option. Today we need to set `.Values.ingress.web.host` to configure `AIRFLOW__WEBSERVER__BASE_URL `, even if we want to keep `.Values.ingress.web.enabled` at `false`

**Comment by gsemet** [comment]
Olivier, can you do this PR?

**Comment by arthur-c** [comment]
I think I found the issue.

We need `http://` in `AIRFLOW__WEBSERVER__BASE_URL`, but we don't need it in the ingress hostname

I'm able to start airflow web with my custom domain with http:// as a prefix in `AIRFLOW__WEBSERVER__BASE_URL`

**Comment by gsemet** [comment]
Ok can you do the PR?

**Comment by arthur-c** [comment]
OK

**Comment by omonnier** [comment]
Thanks to both
