### ISSUE TITLE
[stable/rabbitmq] DNS failure when using k8s_domain

### ISSUE THREAD

**Issue by JPMoresmau** [helm/charts#19054]
**Describe the bug**
RabbitMQ does not start if the kubernetes domain name is not cluster.local

**Version of Helm and Kubernetes**:
Kube v1.16.2, Helm 2.16.1

**Which chart**:
stable/rabbitmq

**What happened**:
RabbitMQ fails to start after setting rabbitmq.clustering.k8s_domain

**What you expected to happen**:
I set  rabbitmq.clustering.k8s_domain to acme.com, since this is the domain of my cluster
It's taken into account if I describe the rabbitmq-0 pod

```
 RABBITMQ_NODENAME:                    rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.acme.com
      K8S_HOSTNAME_SUFFIX:                  .$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.acme.com
```
But the pod fails, the logs just say:
```
ERROR: epmd error for host rabbitmq-0.rabbitmq-headless.namespace.svc.acme.com: nxdomain (non-existing domain)
```
A nslookup of the non headless service works: nslookup rabbitmq-headless.namespace.svc.acme.com gives me an IP address, so the general DNS domain resolution works.

**How to reproduce it** (as minimally and precisely as possible):
Run Kubernetes with a dns domain name (minikube start --dns-domain=acme.com)
Install the helm chart with rabbitmq.clustering.k8s_domain set to acme.com

**Anything else we need to know**:

**Comment by JPMoresmau** [comment]
And I confirm, deleting the cluster, recreating it with cluster.local as the dns domain, rabbit mq starts. So it looks that somewhere we assume cluster.local.

**Comment by juan131** [comment]
Hi @JPMoresmau 

We're not hardcoding  `cluster.local` on any manifest but the **NOTES.txt** (I just sent this PR to fix it: https://github.com/helm/charts/pull/19104)

Did you also update the parameter `rabbitmq.configuration` (see https://github.com/helm/charts/blob/master/stable/rabbitmq/values.yaml#L131)? Please note it's also setting the K8s domain there:

```
    ## Clustering
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    ...
```

**Comment by JPMoresmau** [comment]
I changed the configuration:
```
kubectl describe cm/rabbitmq-config
...
cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
cluster_formation.k8s.host = kubernetes.default.svc.acme.com
```
And I still get the same error. The pod crashes and the log just says: `ERROR: epmd error for host rabbitmq-0.rabbitmq-headless.<namespace>.svc.acme.com: nxdomain (non-existing domain)

**Comment by JPMoresmau** [comment]
Setting image.debug to true gives no more info in the log.

**Comment by JPMoresmau** [comment]
Got it to work!! I added:
```
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
```
on the headless service spec. Probably using `publishNotReadyAddresses`: true would work too. But why do I need this only when changing the dns domain, I don't know....

**Comment by juan131** [comment]
Great @JPMoresmau !! I'm glad you were able to solve it by adding those annotations. Thanks for sharing the workaround since other users may find the same issue when changing the DNS domain in Minikube.

**Comment by DiogoMajela** [comment]
I have the same error, I inserted the annotations how @JPMoresmau said above, but not worked.
