### ISSUE TITLE
Grafana with Persistence enabled is failing on AWS EFS

### ISSUE THREAD

**Issue by guysoft** [helm/charts#19053]
**Describe the bug**
When enabling EFS as the default  then enabling persistence grafana will not start.

Set helm chart with values:
```
persistence:
  type: pvc
  enabled: true
```

**Version of Helm and Kubernetes**:
EKS on AWS, aka 1.14

**Which chart**:
stable/grafana

**What happened**:
``grafana-server`` will not start because it can't write to the data folder.

**What you expected to happen**:
Grafana should load.

**How to reproduce it** (as minimally and precisely as possible):
1. step one:
set up AWS+kubrenets with efs provisioner as the defualt persistence volume storage.
2. ```helm install stable/grafana --set persistence.enabled=true --name grafana```

**Anything else we need to know**:

There was a similar report at  https://github.com/helm/charts/issues/1223 he opens the issue, confirms its an issue with the NFS permission and the closes it with not workaround or any way to solve it.

**Comment by zanhsieh** [comment]
.

**Comment by guysoft** [comment]
I don't think it would be possible to solve this because the ``grafana.db`` sqlite database requires a filesystem fcntl() file locking is broken on many NFS implementations [source](https://www.sqlite.org/faq.html). So the only ways to get it working is to change the storage class to gp2, or [migrate to another database, like mysql](https://community.grafana.com/t/migration-from-sqlite3-to-mysql-database/5319)
