### ISSUE TITLE
[incubator/istio] Upgrade istio to 0.2.x-pre1

### ISSUE THREAD

**Issue by gyliu513** [helm/charts#1909]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:
istio

**What happened**:
istio has just released 0.2.1 https://github.com/istio/istio/releases/tag/0.2.1, we can upgrade to the new version.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by gyliu513** [comment]
/assign

@lachie83

**Comment by lachie83** [comment]
This is still in prerelease. Let's wait until we see the latest release tag

**Comment by gyliu513** [comment]
@lachie83 sure

**Comment by ldemailly** [comment]
yes thanks, let's wait please (or mark it as 0.2.x-pre1)

**Comment by linsun** [comment]
It may be good to re-align the helm chart version to istio version to avoid confusion from our users. :)

**Comment by ldemailly** [comment]
Yes, see #2297, #2110

**Comment by gyliu513** [comment]
@lachie83 shall we update istio helm chart to 0.2.4?

**Comment by linsun** [comment]
+1 @gyliu513 a  lot of users are asking helm chart, it would be great to give a chart based on the release candidate so folks can test it out.

**Comment by gyliu513** [comment]
There are quite a lot of change for istio 0.2.4 compared with istio 0.1.6, do we still need to keep the old version? If we still keep the old version, then we may need to add quite a lot of logic to handle different versions. Such as in 0.2.4, the apiserver was deprecated in pilot etc. @lachie83

**Comment by lachie83** [comment]
the 0.1.6 chart version(s) will still be available to install as it but won't be actively developed.

**Comment by lachie83** [comment]
Here's the PR https://github.com/kubernetes/charts/pull/2369 - I'm having issues rendering CRDs correctly using helm 2.6.1 on a Kubernetes 1.7 cluster. I'm going to raise an issue there.

**Comment by gyliu513** [comment]
#2369 has been merged, thanks @lachie83
