### ISSUE TITLE
[stable/nextcloud] AH00558: apache2: Could not reliably determine the server's fully qualified domain name

### ISSUE THREAD

**Issue by Justluckyg** [helm/charts#19095]
**Describe the bug**
Nextcloud pod keeps on crashing because of this error:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.40.38.25. Set the 'ServerName' directive globally to suppress this message

**Version of Helm and Kubernetes**:

helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

k version --short
Client Version: v1.13.1
Server Version: v1.14.7-gke.23
**Which chart**:

nextcloud          nextcloud-1.6.2                	16.0.3     

**What happened**:
Nextcloud pod keeps on crashing because of this error:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.40.38.25. Set the 'ServerName' directive globally to suppress this message

**What you expected to happen**:

That the pod will have the Service Cluster IP mapped to the service name of my nextcloud and that the pod will not keep on crashing

**How to reproduce it** (as minimally and precisely as possible):
The /etc/hosts contains the endpoint ip and the pod name

```k exec -ti nextcloud-7687b47bb9-mvxrh bash
root@nextcloud-7687b47bb9-mvxrh:/var/www/html# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.40.38.25	nextcloud-7687b47bb9-mvxrh
```
**Anything else we need to know**:

How do I add the FQDN of my public nextcloud in the deployment to get rid of these errors and ensure 100% uptime of my nextcloud deployment?

**Comment by mrtndwrd** [comment]
Are you sure this is the reason for the crash? This is from the logs of my nextcloud which has been running for over the last 5 days (0 restarts since installation):

```
kubectl logs nc-nextcloud-84d7fbb47f-rr42p | grep apache2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.0.25. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.0.25. Set the 'ServerName' directive globally to suppress this message
[Wed Dec 04 15:36:25.359775 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

So I also get the error, but it doesn't cause NC to crash or restart in my case. Does NC get restarted by Kubernetes, or does de container exit? Can you share information about events related to the pod? For example by using `kubectl get events` or `kubectl describe pod`?

**Comment by Justluckyg** [comment]
Hi @mrtndwrd 

When this happened and I described the pod, this is what I am getting. 
```Warning  Unhealthy  5m26s (x43 over 70m)  kubelet, gke-sea-stack-workers-1afff39b-cqh9  Readiness probe failed: Get http://10.40.31.8:80/status.php: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  5m19s (x26 over 76m)  kubelet, gke-sea-stack-workers-1afff39b-cqh9  Liveness probe failed: Get http://10.40.31.8:80/status.php: net/http: request canceled (Client.Timeout exceeded while awaiting headers)```

The container wont go in Running state, doesnt give any Error,  and no matter how many times I restart, it just wont go in Running. And then after some few minutes, longest it happened was 30mins, shortest was like 2 seconds, it will finally go in Running State.

This is a snippet of my GKE Stackdriver logs when container wont Run

https://prnt.sc/q9490m

**Comment by phpdave11** [comment]
I'm noticing the same thing, but it had been working fine for about a month.  It appears that status.php is returning 500, but I'm not sure why.

```
$ kubectl logs nextcloud-c77f44c95-7g7kv -f
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.57.164. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.57.164. Set the 'ServerName' directive globally to suppress this message
[Thu Jan 02 17:30:43.157308 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.11 configured -- resuming normal operations
[Thu Jan 02 17:30:43.157358 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
192.168.45.162 - - [02/Jan/2020:17:31:26 +0000] "GET /status.php HTTP/1.1" 500 211 "-" "kube-probe/1.14+"
192.168.45.162 - - [02/Jan/2020:17:31:27 +0000] "GET /status.php HTTP/1.1" 500 211 "-" "kube-probe/1.14+"
192.168.45.162 - - [02/Jan/2020:17:31:41 +0000] "GET /status.php HTTP/1.1" 500 211 "-" "kube-probe/1.14+"
192.168.45.162 - - [02/Jan/2020:17:31:42 +0000] "GET /status.php HTTP/1.1" 500 211 "-" "kube-probe/1.14+"
192.168.45.162 - - [02/Jan/2020:17:31:56 +0000] "GET /status.php HTTP/1.1" 500 211 "-" "kube-probe/1.14+"
[Thu Jan 02 17:31:56.698317 2020] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully

**Comment by maxirus** [comment]
I've tried setting:
```
  configs:
    nginx.config.php: |-
      <?php
      $CONFIG = array (
        "overwritehost"     => "nextcloud.example.com",
        "overwriteprotocol" => "https",
      );
```

As the Docs suggest but this did not help.

**Comment by MattInternet** [comment]
This is happening to me, I havent let it sit long enough (30 minutes apparently) to see if it fixes itself but either way it seems problematic...

**Comment by juan11perez** [comment]
@Justluckyg 
@maxirus 
@MattInternet 
@phpdave11 

whilst using docker compose, adding the following fixes the error.

`    extra_hosts:
    - "nextcloud.domaint.com:172.15.0.3"`

i assinged a static ip to the docker. in this case 172.15.0.3

**Comment by steled** [comment]
I could fix this problem by addind the following lines to my `values.yam`l file:

```
lifecycle:
  postStartCommand: ["/bin/sh", "-c", "echo \"ServerName 172.16.4.35\" | tee -a /etc/apache2/apache2.conf"]

nextcloud:
  host: 172.16.4.35
```
