### ISSUE TITLE
[incubator/istio] Some secrets will be left when istio was deleted

### ISSUE THREAD

**Issue by gyliu513** [helm/charts#1911]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:
istio

**What happened**:
1) Create an istio application with `helm install`
2) delete the istio application with `helm delete`
3) Check secrets with `kubectl get secrets`,some garbage istio secrets left.

```
root@pc002:~/istio-0.1.6# kubectl get secrets
NAME                                                   TYPE                                  DATA      AGE
admin.registrykey                                      kubernetes.io/dockercfg               1         9h
calico-etcd-secrets                                    Opaque                                3         11h
default-token-lz9dg                                    kubernetes.io/service-account-token   3         11h
istio.dangling-penguin-istio-ca-service-account        istio.io/key-and-cert                 3         7h
istio.dangling-penguin-istio-ingress-service-account   istio.io/key-and-cert                 3         7h
istio.dangling-penguin-istio-pilot-service-account     istio.io/key-and-cert                 3         7h
istio.default                                          istio.io/key-and-cert                 3         7h
```

/cc @lachie83 

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by lachie83** [comment]
Istio creates these and not Helm and hence Helm cannot remove resources it didn't create. The only possible solution is to put a post delete hook that finds all tagged secrets and deletes them. I need to think about whether that's a good idea

**Comment by gyliu513** [comment]
Not sure if we can remove secrets with type as `istio.io/key-and-cert`, I will check how istio itself can help for this.

**Comment by lachie83** [comment]
Any updates on this?

**Comment by gyliu513** [comment]
Sorry @lachie83 , not too much progress due to some other tasks, will try to give some update next week, hope it is OK.
