### ISSUE TITLE
Not able to install graylog using helm 

### ISSUE THREAD

**Issue by rmaheshvarma** [helm/charts#19112]
Hi Team, 
I am trying to install graylog using helm chart, in AKS Kubernetes cluster. While installing I am trying to pass graylog.persistence.storageClass our own class instead of default.  I am not able install , I did not understand, where I have done the mistake, can you please help me to fix this issue. I have used below methods in both the methods it has failed. 

helm install --namespace "graylog-development" --name "graylog" stable/graylog \
  --set graylog.persistence.enabled=true\
  --set graylog.persistence.storageClass= default-retain \
  --set graylog.persistence.accessMode=ReadWriteOnce

Error: failed to download "default-retain" (hint: running `helm repo update` may help)

helm install \
--namespace graylog-development \
--name graylog-development \
stable/graylog \
--set graylog.persistence.enabled=true \
--set graylog.persistence.storageClass= default-retain \
--set graylog.persistence.accessMode=ReadWriteOnce 
Error: unknown flag: --name

Please help me to fix this issue.

**Comment by danielefranceschi** [comment]
helm v3?
```shell
helm install graylog stable/graylog \
     --namespace graylog-development \
     --set graylog.persistence.enabled=true \
     --set graylog.persistence.storageClass=default-retain \
     --set graylog.persistence.accessMode=ReadWriteOnce
```

**Comment by rmaheshvarma** [comment]
Thank you for your reply. Yes Its Helm v3
helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

**Comment by rmaheshvarma** [comment]
helm install graylog stable/graylog \
>      --namespace graylog-development \
>      --set graylog.persistence.enabled=true \
>      --set graylog.persistence.storageClass=default-retain \
>      --set graylog.persistence.accessMode=ReadWriteOnce
Error: failed to download "stable/graylog" (hint: running `helm repo update` may help)

**Comment by danielefranceschi** [comment]
From the helm2/helm3 differences docs: https://helm.sh/docs/topics/v2_v3_migration/ :
> - `local` or `stable` repositories are not set-up by default

The `stable` repo must be added manually.

**Comment by rmaheshvarma** [comment]
Thank you for response. I did not understand, how can I modify my above command?. I am little confuse here.

**Comment by danielefranceschi** [comment]
```shell
helm repo add stable https://kubernetes-charts.storage.googleapis.com/
helm repo update
```
then, `helm install graylog stable/graylog .......`

**Comment by rmaheshvarma** [comment]
Thank you sir your response.

**Comment by rmaheshvarma** [comment]
Hi Sir, 
I have executed the below command, its executing successfully, but pods are creating or I am not able see pods in namespace


helm install --namespace "graylog-development" stable/graylog --generate-name\
>   --set graylog.persistence.enabled=true\
>   --set graylog.persistence.storageClass=default-retain \
>   --set graylog.persistence.accessMode=ReadWriteOnce
NAME: graylog-1574751069
LAST DEPLOYED: Tue Nov 26 06:51:15 2019
NAMESPACE: graylog-development
STATUS: deployed
REVISION: 1
NOTES:
To connect to your Graylog server:

1. Get the application URL by running these commands:

  Graylog Web Interface uses JavaScript to get detail of each node. The client JavaScript cannot communicate to node when service type is `ClusterIP`.
  If you want to access Graylog Web Interface, you need to enable Ingress.
    NOTE: Port Forward does not work with web interface.

2. The Graylog root users

  echo "User: admin"
  echo "Password: $(kubectl get secret --namespace graylog-development graylog-1574751069 -o "jsonpath={.data['graylog-password-secret']}" | base64 --decode)"

To send logs to graylog:

  NOTE: If `graylog.input` is empty, you cannot send logs from other services. Please make sure the value is not empty.
        See https://github.com/helm/charts/tree/master/stable/graylog#input for detail
h@Azure:~$ kubectl get secret --namespace graylog-development
NAME                                                  TYPE                                  DATA   AGE
default-token-ghlzx                                   kubernetes.io/service-account-token   3      4d18h
graylog                                               Opaque                                2      15h
graylog-1574750717                                    Opaque                                2      7m9s
graylog-1574750717-elasticsearch-client-token-ddssk   kubernetes.io/service-account-token   3      7m8s
graylog-1574750717-elasticsearch-data-token-5smlf     kubernetes.io/service-account-token   3      7m8s
graylog-1574750717-elasticsearch-master-token-7mg5j   kubernetes.io/service-account-token   3      7m8s
graylog-1574750717-token-h8cv5                        kubernetes.io/service-account-token   3      7m8s
graylog-1574751069                                    Opaque                                2      77s
graylog-1574751069-elasticsearch-client-token-8dczj   kubernetes.io/service-account-token   3      77s
graylog-1574751069-elasticsearch-data-token-bjblq     kubernetes.io/service-account-token   3      77s
graylog-1574751069-elasticsearch-master-token-pdbvq   kubernetes.io/service-account-token   3      77s
graylog-1574751069-token-n8vq9                        kubernetes.io/service-account-token   3      77s
graylog-development-auditor-token-rc9cl               kubernetes.io/service-account-token   3      4d18h
graylog-development-automation-token-mnvn2            kubernetes.io/service-account-token   3      4d18h
graylog-elasticsearch-client-token-w7r4s              kubernetes.io/service-account-token   3      15h
graylog-elasticsearch-data-token-pvxp7                kubernetes.io/service-account-token   3      15h
graylog-elasticsearch-master-token-lhh4v              kubernetes.io/service-account-token   3      15h
graylog-token-66x5k                                   kubernetes.io/service-account-token   3      15h
sh.helm.release.v1.graylog-1574750717.v1              helm.sh/release.v1                    1      7m10s
sh.helm.release.v1.graylog-1574751069.v1              helm.sh/release.v1                    1      78s
sh.helm.release.v1.graylog.v1                         helm.sh/release.v1                    1      15h
tiller-token-ljwxg                                    kubernetes.io/service-account-token   3      4d18h
h@Azure:~$ kubectl get pods  --namespace graylog-development
No resources found in graylog-development namespace.

Can you please let me know what mistake am I done ?.

**Comment by danielefranceschi** [comment]
First of all, I suggest that you clean up your deployments, as I see that there are two releases (`graylog-1574750717` and `graylog-1574751069`) in the same namespace:
- `helm list -n graylog-development` should show two items
- you can delete them with `helm delete -n graylog-development ....`
- I'd delete the namespace too
- in _testing/debugging mode_ I'd avoid to use `--generate-name ` but instead use a fixed name.

I can't imagine why pods are not present; I suggest to retry in a clean environment.

P.S.: please change the issue title to "[stable/graylog] ...." to follow the standard issue format.

**Comment by rmaheshvarma** [comment]
Thank you for reply sir. I have cleaned the environment and try to reinstall the chart. Again I am facing same issue. Pods are not creating 

kubectl get secret --namespace graylog
NAME                                                  TYPE                                  DATA   AGE
default-token-pn9gm                                   kubernetes.io/service-account-token   3      5m25s
graylog-1574769376                                    Opaque                                2      33s
graylog-1574769376-elasticsearch-client-token-5x68j   kubernetes.io/service-account-token   3      33s
graylog-1574769376-elasticsearch-data-token-nrctc     kubernetes.io/service-account-token   3      33s
graylog-1574769376-elasticsearch-master-token-6hjkb   kubernetes.io/service-account-token   3      33s
graylog-1574769376-token-pzpz5                        kubernetes.io/service-account-token   3      33s
sh.helm.release.v1.graylog-1574769376.v1              helm.sh/release.v1                    1      34s
h@Azure:~$ helm ls -n graylog
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
graylog-1574769376      graylog         1               2019-11-26 11:56:24.250160194 +0000 UTC deployed        graylog-1.3.9   3.1.2-1
h@Azure:~$ kubectl get pods -n graylog
No resources found in graylog namespace.

**Comment by danielefranceschi** [comment]
Have you checked the status of each deployment? `kubectl get deployments` then `kubectl describe deployment/xxxx`
Reasons could be many, starting from disk provisioning to azure-specific, probably not helm or graylog chart related.

**Comment by rmaheshvarma** [comment]
Yes. deployments  and secret files are creating successfully. Only Pods are not creating Danielefranceschi. I did not understand why Pods are not creating.
