### ISSUE TITLE
[stable/mongodb] primary pod is not master sometimes

### ISSUE THREAD

**Issue by viveksinghggits** [helm/charts#19120]
**Describe the bug**
Primary pods is no the msater node sometimes. When I installed mongo db on my k8s cluster it created three statefulsets with name formats primary/secondary and arbiter, and these pods eventually are running pods with the same name format. 
Now my understanding was, the primary pod will always be the master, but sometimes this is not the case. 
Now my question is, is it not guaranteed that the primary pod is going to be master all the time, or I am doing something wrong.

**Version of Helm and Kubernetes**:
Helm Version 
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```
K8S version 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T18:57:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
`stable/mongodb`

**What happened**:
Sometime primary pod is not the master node, which causes issues because I am running all the write operation in the primary pod.

**What you expected to happen**:
My understanding was, primary pod is always going to be Master Node.

**How to reproduce it** (as minimally and precisely as possible):
Install the mongodb chart and randomly try to run write operations from the primary pod, these write operations will fails if at any point of time the primary pod is not the master node.

**Anything else we need to know**:

**Comment by juan131** [comment]
Hi @viveksinghggits 

When you configure MongoDB on "replicaset" mode, one of the **secondary** nodes could eventually be promoted to **primary** node. This happens when the primary node is not responding for any reason. Find more information in the link below:

- https://docs.mongodb.com/manual/core/replica-set-elections/#replica-set-elections

Once the primary node that was not responding recovers back, it should be promoted again as the primary since it has more priority.

- https://docs.mongodb.com/manual/core/replica-set-elections/#member-priority

Let's see how it works:

- Install the chart:

```
$ helm install stable/mongodb --set replicaSet.enabled=true --name mongodb
```

- Let's check the pods

```console
$ kg pods
NAME                  READY   STATUS    RESTARTS   AGE
mongodb-arbiter-0     1/1     Running   0          1m
mongodb-primary-0     1/1     Running   0          1m
mongodb-secondary-0   1/1     Running   0          1m
$ kubectl exec mongodb-primary-0 -- mongo admin --quiet --host 127.0.0.1 --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD --eval 'db.isMaster().ismaster'
true
$ kubectl exec mongodb-secondary-0 -- mongo admin --quiet --host 127.0.0.1 --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD --eval 'db.isMaster().ismaster'
false
```

- Now, let's kill the primary and see what happens:

```console
$ kubectl delete pod mongodb-primary-0
$ kubectl exec mongodb-secondary-0 -- mongo admin --quiet --host 127.0.0.1 --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD --eval 'db.isMaster().ismaster'
true
```

- As you can see, the secondary responds as the master. Once the master is up again:

```console
$ kg pods
NAME                  READY   STATUS    RESTARTS   AGE
mongodb-arbiter-0     1/1     Running   0          5m22s
mongodb-primary-0     1/1     Running   0          10s
mongodb-secondary-0   1/1     Running   0          5m22s
$ kubectl exec mongodb-primary-0 -- mongo admin --quiet --host 127.0.0.1 --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD --eval 'db.isMaster().ismaster'
true
$ kubectl exec mongodb-secondary-0 -- mongo admin --quiet --host 127.0.0.1 --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD --eval 'db.isMaster().ismaster'
false
```

**Comment by viveksinghggits** [comment]
Hi @juan131 
I really appreciate how you explained the things here, that totally makes sense. However in my case I dont think primary was not accessible or had some issues. That's why I thought primary should always be the master.
Here is what I did, installed `mongodb` chart and then `EXEC`ed into the primary pod to run some db command for example inserting documents into collection etc and some of them fail stating `NotMaster`. All this is happening in very short time of span, and again I don't think the primary pod had any issues that why I thought Primary should always be master.
But if you say secondary would only be master if primary had some issues, let me figure that out if primary is facing some issues.
Thanks again.

**Comment by juan131** [comment]
Hi @viveksinghggits 

> Here is what I did, installed mongodb chart and then EXECed into the primary pod to run some db command for example inserting documents into collection etc and some of them fail stating NotMaster. All this is happening in very short time of span, and again I don't think the primary pod had any issues that why I thought Primary should always be master.

That's weird.. Probably the primary node was overwhelmed and it reported an inconsistent status to the replicaset, so one of the secondary replicas took the primary role momentaneously.

> But if you say secondary would only be master if primary had some issues, let me figure that out if primary is facing some issues.

Please do not hesitate to share any insights you discover, it'd be very helpful for other users facing similar issues.

**Comment by viveksinghggits** [comment]
Hi @juan131,
I am seeing another issue with this setup, where if I run 
```
mongo admin --authenticationDatabase admin -u <username> -p <password> --quiet --eval "rs.slaveOk(); db"
```
on the `primary` pod, it runs successfully but if I run below command on the same pod 
```
mongo admin --authenticationDatabase admin -u <username> -p <password> --quiet --eval "db.restaurants.drop()"
```
I get below error
```
2019-11-29T07:22:38.047+0000 I NETWORK  [js] DBClientConnection failed to receive message from 127.0.0.1:27017 - HostUnreachable: Connection reset by peer
```
Now the issue is these commands are being run by a script, and if exec into the pod to run the second command manually I dont get any error. I just get `false` because the collection `restaurants` doesnt exist, which is expected.
Now, I dont know what happened between the first and the second command but this is whats happening. If I see the pods, its restarted even once, if it was, that might have been something to do with the issue.
```
NAME                        READY   STATUS    RESTARTS   AGE
mongo-mongodb-arbiter-0     1/1     Running   0          16m
mongo-mongodb-primary-0     1/1     Running   0          16m
mongo-mongodb-secondary-0   1/1     Running   0          16m

```
