### ISSUE TITLE
[stable/fluentd] Duplicate PVC resource

### ISSUE THREAD

**Issue by Uvedale** [helm/charts#19131]
**Describe the bug**
When autoscaling is disabled and persistence is enable, the chart fails to install because there is a duplicate PVC template in the chart (pvc.yaml and pvc.yml)

**Version of Helm and Kubernetes**:
Kubernetes: 1.14.8
Helm: v2.13.0

**Which chart**:
stable/fluentd

**What happened**:
I tried to install the fluentd chart with autoscaling disabled and persistence enabled

**What you expected to happen**:
The chart to be installed successfully

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/fluentd --set persistence.enabled=true

**Anything else we need to know**:

**Comment by procyclinsur** [comment]
This seems to have been fixed by your MR, but when performing the following command, I still receive both `pvc.y*ml` files.

```bash
helm fetch stable/fluentd --untar
```

**Comment by procyclinsur** [comment]
Never mind!  The below command fixed the issue.  Thanks!

```bash
helm repo update
```
