### ISSUE TITLE
[stable/prometheus-operator] Create CRDs links are broken in README

### ISSUE THREAD

**Issue by dkirrane** [helm/charts#19151]
The links to the CRDs in the README are broken. Looks like the CRD files were renamed in the coreos repo:
https://github.com/coreos/prometheus-operator/tree/master/example/prometheus-operator-crd

**Comment by Dxvid** [comment]
I also saw this problem today.
Not only are the links changed, also the filenames are changed.
This is for example one of the new files:
[https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml](https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml)

**Comment by Morriz** [comment]
Please??

**Comment by GramozKrasniqi** [comment]
Of course its using the master branch we shouldn't expect others to freeze just because someone is referencing them.
Use the latest stable branch as a reference.
