### ISSUE TITLE
[stable/elasticsearch-curator] Hooks broken as Values.command cannot be read in Job chart

### ISSUE THREAD

**Issue by Serk72** [helm/charts#19166]
https://github.com/helm/charts/blob/master/stable/elasticsearch-curator/templates/hooks/job.install.yaml#L52-L54
Values.command is missing '$' before it causing the following error when running with hooks:
<.Values.command>: can't evaluate field Values in type interface {}

**Comment by dojadop** [comment]
In am seeing the same issue so I cannot upgrade to 2.1.2. Missing the '$' in this 
PR:  https://github.com/helm/charts/pull/19090

**Comment by dojadop** [comment]
Fixed by #19186
