### ISSUE TITLE
[stable/mongodb-replicaset] MongoDB replicaset does not update the pod IPs

### ISSUE THREAD

**Issue by alonana** [helm/charts#19179]
There were several issues. For example:

Once a MongoDB pod was added to a ReplicaSet configuration, it was never removed. This causes several problems. For example, inability to get quorum once a pod had been restarted and got a different IP.
In case a MongoDB pod had started, but was not able to communicate with the previous pods, it started its own new ReplicaSet, instead of failing.
A single MongoDB pod, which was restarted, and got a new IP, was not able to start the ReplicaSet, and got error that it is not part of its own replica.

See this link for full description, and solution:
https://runkiss.blogspot.com/2019/11/mongodb-replicaset-on-kubernetes.html

**Comment by juan131** [comment]
Hi @alonana 

Are you using the `stable/mongodb` or the `stable/mongodb-replicaset` chart?

**Comment by juan131** [comment]
I just read your blogpost and you're using `stable/mongodb-replicaset`. Sorry for the noise.

Please update the title of the issue so it starts with chart name (e.g. `[stable/mongodb-replicaset]`). This way, the maintainers of this chart can identify it easily.
