### ISSUE TITLE
[stable/redis] READONLY You can't write against a read only replica.

### ISSUE THREAD

**Issue by msschl** [helm/charts#19183]
**Describe the bug**
When using values.Productions.yaml and trying to write to redis I get the following exception:
```
Message: READONLY You can't write against a read only replica.
```

**Version of Helm and Kubernetes**:
```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

**Which chart**:
[stable/redis]

**How to reproduce it** (as minimally and precisely as possible):
use values.Production.yaml with cluster enabled, two slaves, sentinel enabled, serviceAccount, psp, rbac and metrics (+ metrics servicemonitor) enabled/created

```
cluster:
  enabled: true
  slaveCount: 2

clusterDomain: cluster.company.org

sentinel:
  enabled: true
  masterSet: dp-master

serviceAccount:
  create: true

podSecurityPolicy:
  create: true

rbac:
  create: true

master:
  podLabels:
    version: "1.0.0"
    commit: "unknown"
    tire: "cache"

  persistence:
    size: 1Gi

slave:
  podLabels:
    version: "1.0.0"
    commit: "unknown"
    tire: "cache"

  persistence:
    size: 1Gi

metrics:
  enabled: true

  serviceMonitor:
    enabled: true

  podLabels:
    version: "1.0.0"
    commit: "unknown"
    tire: "monitoring"
```

**Anything else we need to know**:
It's possible the same issue as this issue #12851 in redis-ha

**Comment by alemorcuq** [comment]
Hi, @msschl. Did you fix the issue?

**Comment by msschl** [comment]
Yes and No 😄 
The chart is correct.
I am connection with stackexchange redis to the redis cluster but didn't connect to the sentinel port.

But I haven't quite found out how I can connect with stackexchange redis to a redis sentinel cluster, therefor I had to disable the cluster feature and sentinel feature.

**Comment by funky81** [comment]
Hi @msschl , i have some problems with you. is disable cluster feature and sentinel feature is the only way to solve the problem? It's been several days since i tried to solve this problem.
Main Goals : using Stackexchange redis connect to redis cluster (plus sentinel) in k8s environment

**Comment by msschl** [comment]
Unfortunately for me yes.
The problem is:
I haven’t found an example on how to connect with the C# stackexchange redis client to an sentinel enabled cluster.
Therefore the only way for me was to disable the cluster feature and sentinel and connect directly to redis.

**Comment by msschl** [comment]
I just found an pull request in the StackExchange.Redis repo.
When you are using C# you can try [this](https://github.com/StackExchange/StackExchange.Redis/pull/406). Maybe this works

**Comment by funky81** [comment]
I'll try this. I just wondering why c# don't have good library for redis.
Coz the library that you refer is 3 years old 😅
