### ISSUE TITLE
any docs for how to use replication?

### ISSUE THREAD

**Issue by 34code** [helm/charts#192]
bitnami redis seems to support it..

**Comment by prydonius** [comment]
The plan is to have different charts for standalone and clustered variants. I've been meaning to work on a `redis-cluster` chart that leverages the replication setup available in the `bitnami/redis` image.

If you're looking for replication for other services, there's a [MongoDB petset](https://github.com/kubernetes/charts/tree/master/incubator/mongodb) in incubator, [patroni](https://github.com/kubernetes/charts/tree/master/incubator/patroni) for HA PostgreSQL, and a [clustered MariaDB](https://github.com/bitnami/charts/tree/master/incubator/mariadb-cluster) using two deployments in the `bitnami/charts` repo.

**Comment by 34code** [comment]
very interesting @prydonius  .. thanks for the pointers :)

**Comment by 34code** [comment]
I guess replication is less of an issue if data is not lost and is on a cloud storage since redis can restart with a little downtime and no loss of data.. minimizing downtime would be useful though

**Comment by lachie83** [comment]
Redis-cluster chart in the works #423
