### ISSUE TITLE
stable/jenkins Agent with PVC

### ISSUE THREAD

**Issue by Jdavid7x** [helm/charts#19213]
**Describe the bug**
I'm trying to deploy a jenkins agent with pvc attached.

**Version of Helm and Kubernetes**:
Kubernetes Version: 1.13
Helm Version: 2.12.3

**Which chart**:
jenkins

**What happened**:
When i fill in the values.yaml the properties of a pvc to be attached on the jenkins agent this doesn't create any config inside jenkins master to raise the agent with the pvc.

**What you expected to happen**:
The jenkins master will config the propertie of the pvc to be attached on the agent

**How to reproduce it** (as minimally and precisely as possible):
Put this values in values.yaml 

```values.yaml
agent:
  volumes:
    - type: PersistentVolumeClaim
      mountPath: /var/lib/containers
      claimName: alm-jenkins-slave-images
```

**Anything else we need to know**:

**Comment by lapidus79** [comment]
@Jdavid7x  Did you ever get this to work?
