### ISSUE TITLE
[stable/cerebro] not possible to use elasticsearch clusters with authorization

### ISSUE THREAD

**Issue by psychonaut** [helm/charts#19218]
**Is your feature request related to a problem? Please describe.**
Current cerebro configmap template does not allow to define elasticsearch clusters configured with authorization hence this chart is not usable in our setup.

**Describe the solution you'd like**
Small update will help here, I've pushed commit in our forked repository: https://github.com/egnyte/charts/commit/cb9233792efc84a534209afc7466ddf284d8edac  and I can create a pull request for that.

**Describe alternatives you've considered**
There's always a possibility to create ad-hoc connection string but we'd like to deploy Cerebro with usable configuration.

**Additional context**
The current configuration just create entries like this
```
  {
    host = "http://cluster.address.internal"
    name = "cluster name"
  },
```
but it should be possible to create entries like this:

```
  {
    host = "http://cluster.address.internal"
    name = "cluster name"
    auth = {
      username = "user"
      password = "password"
    }
  },
```

**Comment by mariadb-GrantHolly** [comment]
This is still an issue with this chart.
