### ISSUE TITLE
[stable/redis-ha] Allow to manual set "terminationGracePeriodSeconds"

### ISSUE THREAD

**Issue by kfkawalec** [helm/charts#19230]
One of my nodes (in the kubernetes cluster) died and one of my redis pods was on them. Pod got stuck as "unknown" and did not run on another node.
I can change this behavior by setting tolerances (node.kubernetes.io/unreachable) and terminationGracePeriodSeconds to 0.
But for now it's not possible to set terminationGracePeriodSeconds.

I know that forcing the deletion of a stateful set is not recommended:
https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/
But when one of my nodes is unavailable for some time, I don't want to delete them or do anything manually.
I have redis replica on other nodes, so in this situation I want to force removal stuck podand allow to automatically shedule pod on new node.

**Comment by DandyDeveloper** [comment]
I think this is reasonable, no arguments. I'll see if I can get time to do it (been pretty busy recently).

**Comment by kfkawalec** [comment]
I know that lack of time could be problematic but maybe there is any chance to do this in near future?

**Comment by kfkawalec** [comment]
Maybe now will be possible to do anything with this?
