### ISSUE TITLE
[incubator/patroni] How to use patroni chart to install postgresql 11/12 HA

### ISSUE THREAD

**Issue by wantdrink** [helm/charts#19241]
Hi there,

I changed the image from 
image:
  # Image was built from
  # https://github.com/zalando/spilo/tree/master/postgres-appliance
  repository: registry.opensource.zalan.do/acid/spilo-10
  tag: 1.4-p16

to 

image:
  # Image was built from
  # https://github.com/zalando/spilo/tree/master/postgres-appliance
  repository: registry.opensource.zalan.do/acid/spilo-11
  tag: 1.6-p1

But still don't know how to specify the postgresql version to install. Is there any guidance for this?
Thanks.

**Comment by wantdrink** [comment]
After installing with spilo-11:1.6-p1 I found the postgres version is 11.5. So it looks like the postgres version depends on spilo's image's version and we can only wait for spilo image's updating, right?

**Comment by wolacinio** [comment]
I'm thinking the same. spilo-11 -> postgresql-11, spilo-10 ->postgresql-10 etc.

**Comment by wantdrink** [comment]
@wolacinio All right. Let's wait for spilo's update. Thanks a lot.
