### ISSUE TITLE
[stable/mariadb] Inject passwords from secret via volume

### ISSUE THREAD

**Issue by ghost** [helm/charts#19254]
**Is your feature request related to a problem? Please describe.**
As a DevSecOp, I don't want have administrative private credentials easily discoverable.

See: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/
But more importantly: https://blog.alcide.io/secret-hunting-in-kubernetes
...or: https://sysdig.com/blog/7-docker-security-vulnerabilities/

**Describe the solution you'd like**
Secrets made available to the specific container only via dedicated volume will reduce the risk of leaking sensitive information to a potential attacker.

**Describe alternatives you've considered**
The chart currently employs environment variables, so there is no alternative, yet.

**Additional context**
One way to get the credentials:
```bash
$ docker inspect 01b626b32e19 | jq -r '.[0].Config.Env[]' | grep -i 'password'
MARIADB_MASTER_ROOT_PASSWORD=m3uCM4MakdF645e
MARIADB_REPLICATION_PASSWORD=4c7BY0vKbBwwt61
```
...or:
```bash
$ kubectl exec fxa-db-oauth-mariadb-master-0 -c metrics -- env | grep -i 'password'
MARIADB_ROOT_PASSWORD=YP0QcmIGKNJOG52
```

**Comment by juan131** [comment]
Hi @enote-kane 

We already support this feature on other charts (such as PostgreSQL). As you can see in the link below, there's a parameter named `usePasswordFile` you can use to consume this credentials from files mounted in the container (instead of environment variables)

- https://github.com/helm/charts/tree/master/stable/postgresql/README.md

Would a solution like this work for you?

**Comment by enote-kane** [comment]
Yes, the `usePasswordFile` should yield the desired behavior. However, the naming is somewhat non-intuitive. I would think of a parameter like `injectSecretsAsVolume` which clearly relates to secrets and how to apply them.

**Comment by juan131** [comment]
Hi @enote-kane 

I just created a PR addressing this issue. Please feel free to take a look when you have a chance.
