### ISSUE TITLE
stable/odoo tag: 10.0.20180615-debian-8-r6

### ISSUE THREAD

**Issue by michafn** [helm/charts#19268]
Hello

i am using the stable odo helmchart to set up odoo 10 (tag: 10.0.20180615-debian-8-r6) on our cluster. In general this works, but i do not get wkhtmltopdf installed. 

I downloaded the package: https://github.com/wkhtmltopdf/wkhtmltopdf/releases
version: 0.12.5-1 (flagge to be compatible with odoo 10)

I read through the documentation: https://docs.bitnami.com/bch/apps/odoo/configuration/install-wkhtmltopdf/

the only thing i did different was to install the debian package rather than downloading the source code and compile myself. 

wkhtmltopdf is working in the container, so i can safely assume it is available and in the "path" a well. However odoo keeps telling me that it cannot find wkhtml on the system. No matter what i do or if i set any config paramters within odoo.

This is a pretty essential application to use odoo properly, so it should be added to the image. I did add it though (setting up on this image) and extended the odoo bitnami image, but same issue if i install it in the running container for testing. So I assume there is an issue with the bintami docker image of odoo, but just because i cannot think of any other issue anymore why odoo keep failing to detect wkhtmltopdf.

Any ideas?

**Comment by juan131** [comment]
Hi @michafn 

This is not an issue with the Helm chart but the docker image instead. Could we please move this conversation to the image's repo instead?
There are already issues there to discuss about wkhtmltopdf:

- https://github.com/helm/charts/issues/19268
