### ISSUE TITLE
 stable/chart/pgadmin >> cannot create default server 

### ISSUE THREAD

**Issue by Pigmalion** [helm/charts#19283]
**Describe the bug**
Cannot add default server to values.yaml.

**Version of Helm and Kubernetes**:
helm:v2.14.1
K8s:v1.16.2

**Which chart**:
pgadmin

**What happened**:
tried to add default server to the values.yaml - 

**What you expected to happen**:

When I start the pgadmin page - my default server is already configured. 
**How to reproduce it** (as minimally and precisely as possible):
try to add to values.yaml:
 server: my-server, 
username: username, 
password: password, 
host: uri-service-somthing, 
port:5432 

**Anything else we need to know**:

**Comment by Pigmalion** [comment]
Why no one answers ??? is it still supported?

**Comment by rowanruseler** [comment]
@Pigmalion apologies for the late reply, but `server` is not a value that is provided within the configurable adjustments. I am also unable to find it in the container: https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html

Could you perhaps inform me what you are attempting to do?

**Comment by Pigmalion** [comment]
Thanks for your attention - @rowanruseler , I wish to create a default connection on my pgadmin so the next time I create a new cluster, my pgadmin service will be configured and I will not need to create a connection manually. See, we create clusters like crazy.... Thanks again!

**Comment by rowanruseler** [comment]
@Pigmalion I suppose this can be done by setting up `/pgadmin4/servers.json` within the chart. On the official documentation it states:

> If this file is mapped, server definitions found in it will be loaded at launch time. This allows connection information to be pre-loaded into the instance of pgAdmin in the container. Note that server definitions are only loaded on first launch, i.e. when the configuration database is created, and not on subsequent launches using the same configuration database.

I suppose we can add this config with configmaps, do you perhaps have an servers.json example for me? Else I could perhaps take a look later-on this week to see if I can implement this for you.

**Comment by Pigmalion** [comment]
@rowanruseler , Sorry, but I dont have a server.json, unfortunately, It would be amazing if you could implement such an option ! feel free to take your time :)
Thanks Again !

**Comment by rowanruseler** [comment]
@Pigmalion, I implemented it and it is now in a pull request: https://github.com/helm/charts/pull/20607

When it is merged you are able to use it from the stable repo. Or clone it yourself and try it out! Cheers.

**Comment by rowanruseler** [comment]
@Pigmalion the pull request is merged, and should be available from stable/pgadmin.

Good luck

**Comment by Pigmalion** [comment]
@rowanruseler Thank you very much !
Live long and prosper!

**Comment by Pigmalion** [comment]
@rowanruseler 
Hi, could there be a regression in the behavior due to the last commit? 

`kubectl logs pgadmin-default-67b69898f4-vtzrg
/entrypoint.sh: line 7: can't create /pgadmin4/config_distro.py: Permission denied
Traceback (most recent call last):
  File "run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 108, in <module>
    app = create_app()
  File "/pgadmin4/pgadmin/__init__.py", line 244, in create_app
    create_app_data_directory(config)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 37, in create_app_data_directory
    _create_directory_if_not_exists(os.path.dirname(config.LOG_FILE))
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 16, in _create_directory_if_not_exists
    os.mkdir(_path)
PermissionError: [Errno 13] Permission denied: '/var/log/pgadmin'`

**Comment by rowanruseler** [comment]
@Pigmalion What version of the chart are you using?

**Comment by Pigmalion** [comment]
@rowanruseler Latest, now downgraded to version 1.0.0

**Comment by rowanruseler** [comment]
@Pigmalion I've no version called 'latest', do you mean 1.1.5?

**Comment by Pigmalion** [comment]
I meant the last one. didn't specify the version simply helm installed.... I believe it gives you the last available.
