### ISSUE TITLE
fatal: not a git repository (or any parent up to mount point /) Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

### ISSUE THREAD

**Issue by continuum-akshay-jadhav** [helm/charts#19297]
HI team,

After the recent update for git sync as side car.i tried to use it as below in values.yaml file:

 git:
    ##
    ## url to clone the git repository
    url: https://github.com/apache/airflow
    ##
    ## branch name, tag or sha1 to reset to
    ref: master
    ## pre-created secret with key, key.pub and known_hosts file for private repos
    secret: ""
    ## The host of the repo so for example if a github repo put github.com (Only need if using ssh not https git sync)
    repoHost: ""
    ## The name of the private key in your git sync secret (Only need if using ssh not https git sync)
    privateKeyName: ""
    gitSync:
      ## Turns on the side car container
      enabled: true
      ## Image for the side car container
      image:
        ## docker-airflow image
        repository: alpine/git
        ## image tag
        tag: 1.0.7
        ## Image pull policy
        ## values: Always or IfNotPresent
        pullPolicy: IfNotPresent
      ## The amount of time in seconds to git pull dags
      refreshTime: 60

but dur to this getting below error:
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

but the git repository is public.
what should i do changes to vaules.yaml file or please suggest some ideas.

Thanks in advance

**Comment by krichter722** [comment]
Looks similar to https://github.com/helm/charts/issues/19164, but I can't tell what you're trying to do based on your issue description. Please you proper markdown when editing it.

**Comment by hmike96** [comment]
Were you able to get this working?

**Comment by continuum-akshay-jadhav** [comment]
@hmike96 ,

yes this was test repo....i used my private repo and inserted secrets and then it worked.

**Comment by Raffiki** [comment]
Hi @continuum-akshay-jadhav , how did you get rid of your original bug report regarding `Error: release airflow-t failed: Deployment.apps "airflow-t-scheduler" is invalid: spec.template.spec.containers[0].volumeMounts[0].name: Not found: "git-clone"`?

I'm having one like that as well...

**Comment by hasanghasemi** [comment]
~ $ git status
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by dropdisco** [comment]
just remove yarn.lock/package.lock.json
