### ISSUE TITLE
[stable/sonatype-nexus ] Nexus GUI doesnt load behind the Loadbalancer

### ISSUE THREAD

**Issue by sohnaeo** [helm/charts#19320]
**Describe the bug**

nexus UI doesn't load behind the load balancers because of SSL termination at load balancer. 

**Version of Helm and Kubernetes**:

Helm Version: Client 2.10.0 / Server 2.14.3

Kubernetes version: 1.15.3

**Which chart**:
sonatype-nexus
appVersion: 3.17.0-01
appVersion: 3.17.0-01

**What happened**:

All our  SSL traffic is terminating at ELB/F5 , nexus chart get deployed successfully along with ingress. When we try to access nexus GUI Ingress, it loads but nothing happens. If I see the "View page source" by right clicking on the page, it seems chart is trying to open http:// instead https that cause an issue to open the GUI properly. If I take any http link and open trhough https, it doesnt have any issues. I tried many times but it I couldn't find an issue. 

**What you expected to happen**:
Chart should use https internal links instead http

**How to reproduce it** (as minimally and precisely as possible):

1) SSL termination at F5/ELB

2) Deploy the chart

3) Create ingress definition

4) Browse the ingress link

**Anything else we need to know**:

If I try to create service NodePort and access the port directly on the nodes by passing the load balancer, I can open the Nexus gui fine with http

**Comment by gveltri** [comment]
Looks like you're not the first one to have this issue. I've been trying to find a fix myself.

https://github.com/helm/charts/issues/5385#issuecomment-532895399

**Comment by imdganesan** [comment]
I solved using nginx-configuration to forward the X-Forwarded-Proto
https://github.com/kubernetes/ingress-nginx/issues/3192#issuecomment-483281931
