### ISSUE TITLE
[stable/cockroachdb] make use of jetstack/cert-manager

### ISSUE THREAD

**Issue by paepke** [helm/charts#19333]
Currently the certificate management is based on the k8s internal ca. We'd like to add the posibility to enhance the certificate management to issue certificates by CAs managed via cert-manager.
Cert-Manager can fully automate the process and can use external PKIs like hashicorps vault or self-signed CAs.

We already implemented this based on non-helm deployment files and would like to add this with a feature switch to alternatively use cert-manager.

**Comment by SebJansen** [comment]
Why has this issue been closed? This feature would of great value when starting up a CockroachDB cluster and wanting to use letsencrypt certs

**Comment by razuos** [comment]
Indeed, would be a great feature.
