### ISSUE TITLE
[stable/sentry] Missing documentation for user.password

### ISSUE THREAD

**Issue by fl-max** [helm/charts#19344]
**Describe the bug**

The documentation is missing a callout and description for the `user.password` setting.

**Version of Helm and Kubernetes**:

N/A

**Which chart**:

stable/sentry v3.1.5

**What happened**:

N/A

**What you expected to happen**:

Document the use of setting your own Admin password via `user.password` value.

**How to reproduce it** (as minimally and precisely as possible):

N/A

**Anything else we need to know**:

**Comment by fl-max** [comment]
Go away stale bot

**Comment by OKNoah** [comment]
Also searching for this.
