### ISSUE TITLE
[stable/prometheus-operator] not installing new grafana plugins specified in deployment

### ISSUE THREAD

**Issue by efernandes-dev-ops** [helm/charts#19366]
**Describe the bug**
Grafana plugins specified don't seemed to be installed after grafana is installed.

**Version of Helm and Kubernetes**:
Helm Version: v3.0.0
Kubernetes Version: v1.16

**Which chart**:
stable/prometheus-operator

**What happened**:
Added new Grafana plugin to install. The plugin I'm installing grafana-simple-json-datasource not that it matters which plugin I'm installing.

**What you expected to happen**:
The plugin is installed and able to view the plugin installed in grafana.

**How to reproduce it** (as minimally and precisely as possible):
Set the following in the grafana deployment
`           - name: GF_INSTALL_PLUGINS
              valueFrom:
                configMapKeyRef:
                  name: prometheus-grafana
                  key: plugins`

In the prometheus-grafana config map I've got the following:

`{
  "kind": "ConfigMap",
  "apiVersion": "v1",
  "metadata": {
    "name": "prometheus-grafana",
    "namespace": "metrics",
    "selfLink": "/api/v1/namespaces/metrics/configmaps/prometheus-grafana",
    "uid": "c8776f99-1119-11ea-a723-0a215513d23e",
    "resourceVersion": "390447",
    "creationTimestamp": "2019-11-27T13:28:22Z",
    "labels": {
      "app": "grafana",
      "chart": "grafana-4.0.2",
      "heritage": "Helm",
      "release": "prometheus"
    }
  },
  "data": {
    "grafana.ini": "[analytics]\ncheck_for_updates = true\n[grafana_net]\nurl = https://grafana.net\n[log]\nmode = console\n[paths]\ndata = /var/lib/grafana/data\nlogs = /var/log/grafana\nplugins = /var/lib/grafana/plugins\nprovisioning = /etc/grafana/provisioning\n",
    "plugins": "grafana-simple-json-datasource"
  }
}`

**Anything else we need to know**:

A previous ticket was raised on this https://github.com/helm/charts/issues/10599. Though having followed the workarounds, the plugin isn't installed. Also I don't having to do a helm upgrade should be necessary when installing a new plugin.

**Comment by efernandes-ANDigital** [comment]
Sorry was mistaken, we were referring to the plugin id incorrectly hence why grafana kept throwing the plugin not found error
