### ISSUE TITLE
[stable/velero] CRDs don't get installed in Helm 3

### ISSUE THREAD

**Issue by joschi36** [helm/charts#19387]
**Describe the bug**
I can't install/template the velero chart.
While installing or templating the chart with helm 3 i get the following error and CRDs don't get rendered/installed:
```
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
```

**Version of Helm and Kubernetes**:
Kubernetes: v1.16.3
Helm: v3.0.0

**Which chart**:
stable/velero 2.5.0/2.4.0

**What happened**:
Installation/templating of CRDs failed

**What you expected to happen**:
CRDs get templated

**How to reproduce it** (as minimally and precisely as possible):
`helm template velero stable/velero --version 2.5.0`

**Comment by carlisia** [comment]
Related: https://github.com/vmware-tanzu/velero/issues/2088 - we might need to make this update in conjunction with moving the chart to our repo.

**Comment by jmreicha** [comment]
Just ran into this as well.

**Comment by carlisia** [comment]
Velero doesn't yet have a compatible chart for Helm 3. We are tracking that here: https://github.com/vmware-tanzu/velero/issues/2126

**Comment by carlisia** [comment]
Requesting this issue be closed as the Velero chart has moved to the `vmware-tanzu/helm-charts` repo and we are tracking this issue here: https://github.com/vmware-tanzu/helm-charts/issues/7

/close
