### ISSUE TITLE
[airflow stable/chart] git sync does not sync on non-master branch

### ISSUE THREAD

**Issue by javamonkey79** [helm/charts#19389]
**Describe the bug**
The git sync functionality of airflow chart does not work, when ref is set to anything other than master.

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
airflow

**What happened**:
see description

**What you expected to happen**:
expected changes committed\pushed to branch would propagate to k8s

**How to reproduce it** (as minimally and precisely as possible):
* set git.ref = to a branch that is not master
* make a change in git repo
* watch as git sync updates, but, changes don't propagate

**Anything else we need to know**:

**Comment by javamonkey79** [comment]
@hmike96 here is the issue

**Comment by hmike96** [comment]
Have the fix now will be up by with next couple hour. Thanks @javamonkey79

**Comment by javamonkey79** [comment]
@hmike96 you're fast! Thanks so much! I gather, that if you found a fix, then you were able to reproduce the issue? Thanks again.

**Comment by hmike96** [comment]
No problem! yeah just tried it with a new branch.
