### ISSUE TITLE
[stable/postgresql] throws error when installing chart and using extraEnv

### ISSUE THREAD

**Issue by johnnymetz** [helm/charts#19386]
**Describe the bug**
Whenever I specify `extraEnv` in my `values.yaml` file and attempt to install the chart, I get the following error:

```
Error: YAML parse error on postgresql/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 81: did not find expected '-' indicator
```

values.yaml:
```
extraEnv:
  HELLO: WORLD
```

bash:
```
helm install -n postgresql -f values.yaml stable/postgresql
```

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
```

**Which chart**:
stable/postgresql

**How to reproduce it** (as minimally and precisely as possible):
Create a chart with the `values.yaml` specified above and try to install the chart using the command above.

**Comment by juan131** [comment]
Hi @johnnymetz 

I create a PR to improve the example in the values.yaml so you can understand how to use this parameter.

Basically you need to use:

```yaml
extraEnv:
  - name: FOO
    value: "bar"
```

Instead of:

```yaml
extraEnv:
  HELLO: WORLD
```
