### ISSUE TITLE
[stable/pachyderm] Kubernetes 1.16 support

### ISSUE THREAD

**Issue by AndriiNeverov** [helm/charts#19382]
**Describe the bug**

```
pachyderm/templates/etcd_deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

pachyderm/templates/pachd_deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
```

**Version of Helm and Kubernetes**:

Kubernetes 1.16.3
Helm : 2.13.1

**Which chart**:
stable/pachyderm

**What happened**:
Installation error

**What you expected to happen**:
Chart to be installed with no error

**How to reproduce it** (as minimally and precisely as possible):
Default installation method

**Anything else we need to know**:
apiVersion should be apps/v1

**Comment by donutloop** [comment]
i have the same issue
