### ISSUE TITLE
[stable/prometheus] Failed to pass the flag storage.local.target-heap-size to prometheus

### ISSUE THREAD

**Issue by jinlxz** [helm/charts#19391]
**Describe the bug**
[stable/prometheus] Failed to pass the flag storage.local.target-heap-size to prometheus

I add the flag `storage.local.target-heap-size` in configuration file to limit the memory usage, but it failed to start the POD.
```yaml
server:
    extraArgs: 
        storage.local.target-heap-size: 10GiB
```
**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:04:30Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
[stable/prometheus] 

**What happened**:
Failed to start the POD prometheues, I checked the log ,it said that the flag is invalid.
```shell
kubectl -n test-services log -c prometheus-server prometheus-server-6fdcc66945-n252m
Error parsing commandline arguments: unknown long flag '--storage.local.target-heap-size'
prometheus: error: unknown long flag '--storage.local.target-heap-size'
```

**What you expected to happen**:
the flag should be used to start prometheus server.

**How to reproduce it** (as minimally and precisely as possible):
helm install --namespace shared-services --name my-release -f prometheus.yaml stable/prometheus

[prometheus.yaml](https://github.com/jinlxz/technical_notes/blob/master/software_configuration/helm_install/prometheus_values_issue.yaml) can be found here.

**Anything else we need to know**:

**Comment by jinlxz** [comment]
The flag `storage.local.target-heap-size` is not supported in the latest release.

**Comment by a180285** [comment]
@jinlxz En, yes, after your reply, we know that it's not supported. But what we should use instead?
Can you help point out.

**Comment by Tyrael** [comment]
@jinlxz is there any reason why this change is not documented at all?
no mention in either https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md or https://prometheus.io/docs/prometheus/latest/migration/

**Comment by jinlxz** [comment]
AFAIK, there is NO alternative to the flag.

**Comment by hackaholic** [comment]
you have to use : `--storage.tsdb.path`
