### ISSUE TITLE
Stable/airflow:The scheduler does not appear to be running.

### ISSUE THREAD

**Issue by continuum-akshay-jadhav** [helm/charts#19399]
Hi All,
 i have used stable Airflow and installed it using stable/airlfow helm chart.

when i started airflow web UI got below error:
**The scheduler does not appear to be running. Last heartbeat was received 7 minutes ago.
The DAGs list may not update, and new tasks will not be scheduled**.

Can someone please help

**Comment by WarpRat** [comment]
The same thing was happening to me, it only seems to happen if the schedulerNumRuns is set to something other than "-1" (never restart scheduler). I've tried setting that to 10 and 50 and I get that message with either one of those settings, but I also don't have any dags loaded yet, so the scheduler seems to hit that number of runs right away. We plan to leave it never restarting for now, we roll our k8s cluster on a schedule anyway which will hopefully be enough to head off the issue with long running scheduler processes missing some jobs.

**Comment by jinyyy666** [comment]
Same here.

**Comment by nittugeorge** [comment]
Getting the same message "The scheduler does not appear to be running. Last heartbeat was received....The DAGs list may not update, and new tasks will not be scheduled."

 But everything seems to be working. Getting the above label on the UI now and then.

**Comment by zuk** [comment]
Same here with `LocalExecutor` using a Postgres backend.

Steps we've tried to fix this:

- switch to `CeleryExecutor`
- automatically restart the scheduler every hour
- sacrifice several goats

Nothing has worked so far.

![image](https://user-images.githubusercontent.com/35702/102807583-ec11bd00-438c-11eb-8ec9-4f20baad08b1.png)

**Comment by Murfen** [comment]
I have the same issue on Airflow 1.10.14 using LocalExecutor ans PostgreSQL backed. I run a long time task via BashOperator so the particular airflow worker process is waiting for the child bash complete. No other tasks can run until the long task finish.

**Comment by minnieshi** [comment]
i have the same issue on Airflow 1.10.14 using celeryExecutor and postgresql backend, setup via kubenetes.
and schedulerNumRuns is set to "-1" unintentionally.
when checking log
it has error like this

`[2021-04-16 13:06:36,392] {celery_executor.py:282} ERROR - Error fetching Celery task state, ignoring it:AirflowTaskTimeout('Timeout, PID: 3497')
Celery Task ID: ('XXXXXXXX_YYY_test', 'Task_blahblahblah', datetime.datetime(2021, 4, 15, 3, 0, tzinfo=<TimezoneInfo [UTC, GMT, +00:00:00, STD]>), 1)`
