### ISSUE TITLE
[name of the chart e.g. stable/chart] issue title

### ISSUE THREAD

**Issue by Eptis** [helm/charts#19407]
**Describe the bug**
504 gateway timeout when trying to test/send email. I provided the configuration parameters required in [the Ghost docs](https://github.com/bitnami/bitnami-docker-ghost#smtp-configuration). It seems to hang and then times out. 

**Version of Helm and Kubernetes**:
Helm: 2.16.1 (Client & Server)
Kubernetes: v1.13.11-gke.14

**Which chart**:
stable/ghost

**What happened**:
I tried to send an email using SMTP but the connection hangs and times out.

**What you expected to happen**:
The email would be send, or if the configuration was incorrect an error would be thrown.

**How to reproduce it** (as minimally and precisely as possible):
Install and add any valid SMTP configuration

**Anything else we need to know**:
Could it be that port 25 is not opened by default?

**Comment by alemorcuq** [comment]
Hi, @Eptis.

Have you tried setting up SMTP using the chart parameters? Here's the full list: https://github.com/helm/charts/tree/master/stable/ghost#parameters

| Parameter                           | Description                                                   | Default                                                  |
|-------------------------------------|---------------------------------------------------------------|----------------------------------------------------------|
| `smtpHost`                          | SMTP host                                                     | `nil`                                                    |
| `smtpPort`                          | SMTP port                                                     | `nil`                                                    |
| `smtpUser`                          | SMTP user                                                     | `nil`                                                    |
| `smtpPassword`                      | SMTP password                                                 | `nil`                                                    |
| `smtpFromAddress`                   | SMTP from address                                             | `nil`                                                    |
| `smtpService`                       | SMTP service                                                  | `nil`                                                    |

Regards,
Alejandro
