### ISSUE TITLE
[stable/mariadb] helm 3 config error

### ISSUE THREAD

**Issue by yianni-ververis** [helm/charts#19412]
I cannot install maria db with Helm 3.

 14:46:48.69 Welcome to the Bitnami mariadb container
 14:46:48.69 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
 14:46:48.69 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
 14:46:48.69 Send us your feedback at containers@bitnami.com
 14:46:48.69 
 14:46:48.69 INFO  ==> ** Starting MariaDB setup **
 14:46:48.72 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
 14:46:48.72 INFO  ==> Initializing mariadb database
 14:46:48.72 DEBUG ==> Custom configuration my.cnf detected
 14:46:48.72 DEBUG ==> Ensuring expected directories/files exist
 14:46:48.73 DEBUG ==> Cleaning data directory to ensure successfully initialization
 14:46:48.74 INFO  ==> Installing database
Installing MariaDB/MySQL system tables in '/bitnami/mariadb/data' ...
Aborted (core dumped)

Installation of system tables failed!  Examine the logs in
/opt/bitnami/mariadb/logs/mysqld.log or /bitnami/mariadb/data for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

And here is my custom values.yaml
image:
  debug: true

volumePermissions:
  enabled: true
  
rootUser:
  password: "1234"

replication:
  enabled: false

master:
  persistence:
    enabled: true
    existingClaim: nfs
    subPath: mysql
  extraEnvVars:
    - name: TZ
      value: "America/New_York"

rbac:
  create: true

service:
  type: NodePort
  port: 3306
  nodePort:
    master: 32465

**Comment by alemorcuq** [comment]
Hi, @yianni-ververis.

Have you tried installing the chart without your custom `my.cnf` to see if that is actually the issue?

Regards,
Alejandro

**Comment by yianni-ververis** [comment]
Thats the issue the config is in your chart, I do not pass a value anywhere.

BTW the chart is from bitnami/mariadb
helm install mysql bitnami/mariadb -f ./helm/values/mysql/values-dev.yaml

**Comment by yianni-ververis** [comment]
Closing the issue. It has to do with nfs permissions
