### ISSUE TITLE
[stable/sonarqube] plugins.install causes error with sonarqube:8.0-developer-beta

### ISSUE THREAD

**Issue by jasondamour** [helm/charts#19411]
**Describe the bug**
I deployed [sonarqube:8.0-developer-edition](https://github.com/SonarSource/docker-sonarqube/blob/8ae0fadc72fef64334998e811f1b9cf68a458a2c/8/developer/Dockerfile) using the stable helm chart. 
```
image: 
    tag: 8.0-developer-beta
```
 Worked perfectly (aside from missing default plugins, a la #18931)

Then I added 
```  
plugins:
    install:
    - https://github.com/checkstyle/sonar-checkstyle/releases/download/4.26/checkstyle-sonar-plugin-4.26.jar
```

And now the container fails to start with 

```
/tmp/scripts/copy_plugins.sh: line 14: /opt/sonarqube/bin/run.sh: No such file or directory
```

**Version of Helm and Kubernetes**:
Helm 3.0.0 (but not an issue here)
GKE 1.13.11-gke.14

**Which chart**:
stable/sonarqube

**What happened**:
Pod crashloop. It appears that `install-plugins.yaml` deletes the run.sh script

**What you expected to happen**:
Plugins to be installed, webserver to start successfully

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/sonarqube --set 

**Anything else we need to know**:

Similar to #18931

**Comment by shapeofarchitect** [comment]
This has been fixed by introducing `sonarqubeFolder: /opt/sq`. if you set this in your values you should be able to fix the above. They changed the location in developer beta edition of SONARQUBE_HOME.
