### ISSUE TITLE
Use Existing secret for only RMQ credentials while defnitions.json and erlangcookie from values.yaml

### ISSUE THREAD

**Issue by vkasgit** [helm/charts#19462]
Hi Steven Sheehy,
I am trying to use existing secret to protect my RMQ credentials from being exposed in a git repo on a values.yml while at the same time I do NOT want erlangcookie and definitions.json to go in kubernetes secret. I want erlangcookie and definitions.json to be picked up from values.yml instead of secret.
Is it possible to do that? 
The use case behind this is, my team is RMQ service provider to many customers and we want the definition.json to be managed and configurable by each and every customers like vhost, their queues etc., Our team will create a plain RMQ cluster with minimal config and hand over to our customers...And from values.yaml each team can then modify to update the definitions.json.

Please let us know if there is any solution to this use case. TIA.

**Comment by vkasgit** [comment]
@steven-sheehy ^^

**Comment by steven-sheehy** [comment]
The [secret](https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/templates/secret.yaml) provided by the chart requires the cookie, definitions and user/passes all in the same file. You can either provide all the values via the values.yaml or you supply your own existing secret that you construct on your own. Why don't you just have each customer create their own secret? They can use bitnami's sealed secrets to protect it. Or if you want it in the values.yaml you can use git-crypt or similar.
