### ISSUE TITLE
The mongodb pod has an connection issue

### ISSUE THREAD

**Issue by bjlvfei** [helm/charts#19461]
Hi Team,
I have meet an connection issue when installed the graylog charts. Here was error info about mongodb

NAME                                   READY   STATUS             RESTARTS   AGE
elasticsearch-client-fc8648cf9-fmxhs   1/1     Running            0          17d
elasticsearch-client-fc8648cf9-ldfwv   1/1     Running            0          17d
elasticsearch-data-0                   1/1     Running            0          17d
elasticsearch-data-1                   1/1     Running            0          17d
elasticsearch-master-0                 1/1     Running            0          17d
elasticsearch-master-1                 1/1     Running            0          17d
elasticsearch-master-2                 1/1     Running            0          17d
graylog-0                              0/1     Running            4970       17d
mongodb-mongodb-replicaset-0           1/1     Running            0          16d
**mongodb-mongodb-replicaset-1**           0/1     **CrashLoopBackOff**   6468       16d

Events:
  Type     Reason     Age                    From                    Message
  ----     ------     ----                   ----                    -------
  Normal   Pulled     46m (x6447 over 16d)   kubelet, 10.93.122.232  Container image "mongo:3.6" already present on machine
  Warning  Unhealthy  21m (x33501 over 16d)  kubelet, 10.93.122.232  (combined from similar events): Readiness probe failed: MongoDB shell version v3.6.15
connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
2019-12-09T01:01:17.174+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2019-12-09T01:01:17.174+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:263:13
@(connect):1:6
exception: connect failed
  Warning  BackOff  72s (x92844 over 16d)  kubelet, 10.93.122.232  Back-off restarting failed container

Any solution about this? 

Levi
Thanks!

**Comment by dani8art** [comment]
Hi @bjlvfei 

I am going to try to reproduce the issue on my side in order to identify what it is happening, could you give us a bit more information?

- Could you share with us the type of cluster that you are using (minikube, aws, etc)?
- Could you share with us the `values.yaml` that you used?

Regards,
