### ISSUE TITLE
stable/wordpress should be deprecated

### ISSUE THREAD

**Issue by woodcockjosh** [helm/charts#19469]
stable/wordpress should be deprecated in favor of bitnami/wordpress and readme on hub.helm.sh updated to reflect

**Comment by sameersbn** [comment]
@woodcockjosh Thank you for letting us know. 

Currently the charts in the bitnami repo and the upstream repo are synchronised and I believe will continue to be until helm v2 is completely deprecated. 

We will work on updating the readme so that new users pick the charts from the bitnami repo.
