### ISSUE TITLE
[stable/mssql] Add Prometheus Exporter

### ISSUE THREAD

**Issue by dannyyy** [helm/charts#19492]
**Is your feature request related to a problem? Please describe.**
For monitoring purposes I'd like to propose to extend the current chart with the ability enable / deploy an prometheus exporter.

e.g. https://github.com/awaragi/prometheus-mssql-exporter

**Describe the solution you'd like**
Integration of one of the available prometheus exporter:
e.g. https://github.com/awaragi/prometheus-mssql-exporter

**Describe alternatives you've considered**

**Additional context**

**Comment by salaros** [comment]
+1 Please consider adding chart for mssql exporter
