### ISSUE TITLE
[stable/mcrouter] Support for Kubernetes 1.16

### ISSUE THREAD

**Issue by lambreto** [helm/charts#19507]
The 'apiVersion' of DaemonSet and StatefulSet templates should be changed to 'apps/v1' from currently - 'extensions/v1beta1' and 'apps/v1beta1' according to:[https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/](url)

However this will break support for Kubernetes < 1.9
Maybe a new parameter should be introduced to specify Kubernetes version.

**Comment by NGTOne** [comment]
:+1: for this.
