### ISSUE TITLE
Helm Install for prometheus fails v3.0.1

### ISSUE THREAD

**Issue by Newbie112222** [helm/charts#19505]
Hi, 
trying to install prometheus via helm but keep on getting this error. Any ideas how to fix this?

helm install --generate-name stable/prometheus-operator --namespace monitor
Error: failed to download "stable/prometheus-operator" (hint: running `helm repo update` may help)

helm install --generate-name stable/prometheus --namespace monitor
Error: failed to download "stable/prometheus" (hint: running `helm repo update` may help)

helm repo update
Error: no repositories found. You must add one before updating

helm version
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:05:01Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by dubuc** [comment]
In Helm 3, the stable repository is not set. You have to manually add it.

```
$ helm repo add --help
add a chart repository

Usage:
  helm repo add [NAME] [URL] [flags]

$ helm repo add stable https://kubernetes-charts.storage.googleapis.com

$ helm repo update
```

Then you can use stable charts like `stable/prometheus-operator`. Hope this helps!

**Comment by Soma123** [comment]
I manually added the stable repo but still getting the same error. Any help?

**Comment by Cingulara** [comment]
This helm repo add from @dubuc worked for me thank you! Helm v 3.0.2 on Mac OS X.

**Comment by MattCurryCom** [comment]
Still a no go for me, even after update.

**Comment by tuananh1998hust** [comment]
```
$ helm install [name] stable/prometheus
```

**Comment by kjozsa** [comment]
> I manually added the stable repo but still getting the same error. Any help?

`helm repo update`

**Comment by jaiksolanki** [comment]
#It worked for me and got the result also
 [osboxes@osboxes ~]$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈

**Comment by vadimslu** [comment]
Try running those commands

` helm repo add prometheus-community https://prometheus-community.github.io/helm-charts`
`helm repo add stable https://kubernetes-charts.storage.googleapis.com/`
`helm repo update`

**Comment by maxclac** [comment]
Hello! Same problem here. All the above solutions don't work.

**Comment by SamsonNelson** [comment]
+1

**Comment by Dsiddhesh** [comment]
Tried adding repo as below Still fails.

`D:\Kubernetes>helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
"prometheus-community" has been added to your repositories

D:\Kubernetes>helm repo add stable https://kubernetes-charts.storage.googleapis.com/
Error: repo "https://kubernetes-charts.storage.googleapis.com/" is no longer available; try "https://charts.helm.sh/stable" instead

D:\Kubernetes>helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "prometheus-community" chart repository
Update Complete. ⎈Happy Helming!⎈

D:\Kubernetes>helm install prometheus stable/prometheus-operator
Error: failed to download "stable/prometheus-operator" (hint: running `helm repo update` may help)`

**Comment by Bashayr29** [comment]
helm repo add stable https://charts.helm.sh/stable
helm repo update
then install stable/prometheus-operator (note: this chart is deprecated).

**Comment by raspitakesovertheworld** [comment]
I'm new, so I'm a little confused: Why is it deprecated? Isn't this the stable recommended version of prometheus?

**Comment by franko22** [comment]
@raspitakesovertheworld use this community release

$ helm install [RELEASE_NAME] prometheus-community/kube-prometheus-stack

https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

**Comment by raspitakesovertheworld** [comment]
What is the difference between the community release and the normal one? Is there some documentation about which releases of prometheus exist for Kubernetes and the difference? It is hard to start when you don't know anything about anything about prometheus.
