### ISSUE TITLE
Add celenechang as Trusted Collaborator

### ISSUE THREAD

**Issue by celenechang** [helm/charts#19539]
Hello,

I've recently joined the Datadog team that maintains the stable/datadog chart.

May I please be added as a Trusted Collaborator to take part in the PR lifecycle? (Similar to #18810 .)

Thanks!

cc @hkaj

**Comment by hkaj** [comment]
Confirming that Celene works on the helm chart with us!

**Comment by celenechang** [comment]
Happy New Year @mattfarina! Mind looking at this when you have a chance? Thank you!

**Comment by zanhsieh** [comment]
@celenechang 
Welcome onboard to Datadog team.
How about a PR to OWNER file change in stable/datadog chart? After that, you might get some helm/member to help you out in Kubernetes slack #charts channel, in case @mattfarina is busy on something else.

**Comment by celenechang** [comment]
Thanks @zanhsieh , I've been added to the OWNERS file. I'll give the Kubernetes slack channel a try!

**Comment by celenechang** [comment]
unstale..

**Comment by mattfarina** [comment]
@celenechang sorry for the slow response. You should have an invitation to collaborate. Accept it and you should be good to go.

**Comment by celenechang** [comment]
Got it, thanks!
