### ISSUE TITLE
[stable/prometheus-operator] Fails with mTLS on Istio

### ISSUE THREAD

**Issue by ghost** [helm/charts#19542]
**Describe the bug**
We're running Prometheus-operator-8.3.2 and have istio installed with mTLS enabled. I have also enabled the following in Istio:
```
rewriteapphttpprobe:true
readinessInitialDelaySeconds:10s
```
**What happened**:
When running the prometheus-oper-admission this errors with
> Back-off restarting failed container
> Readiness probe failed: HTTP probe failed with statuscode: 503

**What you expected to happen**:
Installs with Istio mTLS

**How to reproduce it** (as minimally and precisely as possible):
Have istio mTLS enabled and sidecar turned on

**Anything else we need to know**:

**Comment by Kampe** [comment]
Not stale! Still not unable to get prometheus working with mTLS enabled
