### ISSUE TITLE
[stable/prometheus-operator] prometheus-prometheus-oper-operator fails due to missing secret

### ISSUE THREAD

**Issue by ghost** [helm/charts#19541]
We're having an issue where when admissionWebhooks is set to enabled: false prometheus-prometheus-oper-operator then fails to deploy with 
> MountVolume.SetUp failed for volume "tls-proxy-secret" : secret "prometheus-prometheus-oper-admission" not found 

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}

**What happened**:
Deployment for prometheus-prometheus-oper-operator fails with MountVolume.SetUp failed for volume "tls-proxy-secret" : secret "prometheus-prometheus-oper-admission" not found

**What you expected to happen**:
Deployment should still import the secret if required or not use the secret

**How to reproduce it** (as minimally and precisely as possible):
set the following:
` admissionWebhooks:
    enabled: false`

**Comment by mpolednik** [comment]
It seems that by default, the operators TLS proxy sidecar depends on cert that is being generated as a part of admission webhook deployment (that is skipped when admission webhooks are disabled).

It is possible to work around this by disabling TLS proxy:

```
prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  tlsProxy:
    enabled: false
```
