### ISSUE TITLE
[stable/rabbitmq-ha] ClusterIP breaking change

### ISSUE THREAD

**Issue by SamCHogg** [helm/charts#19560]
**Describe the bug**
There is a breaking change due to the introduction of the PR https://github.com/helm/charts/pull/18503 where the `ClusterIP` is modified. The check added results in `ClusterIP` only being set when `.Values.service.type` equals `LoadBalancer`, causing `ClusterIP` to default to `""` for all other service types. The previous default was `"None"` so anyone trying to upgrade to this version with a different service type will be forced to re-deploy the service to fix this.

**Version of Helm and Kubernetes**:
Helm: v2.16.1
Kubernetes: v1.16.2

**Which chart**:
stable/rabbitmq-ha

**What happened**:
When upgrading the patch version I got the following error:
```
Error: UPGRADE FAILED: Service "rabbitmq-ha" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

**What you expected to happen**:
A patch version should upgrade without issues.

**How to reproduce it** (as minimally and precisely as possible):
Upgrade a release from 1.36.2 to 1.36.3 when `.Values.service.type` is set to `ClusterIP`.

**Anything else we need to know**:
It isn't even possible to work around this issue by setting `.Values.service.clusterIP` to `"None"`.

**Comment by amansatija** [comment]
hey i came across the same problem with same chart version 3.80
what should i do ?
