### ISSUE TITLE
[jenkins stable/chart] pod error

### ISSUE THREAD

**Issue by laith-leo** [helm/charts#19572]
**jenkins stable/chart fails with EKS**

With Jenkins stable HELM chart installation with EKS, deployment fails with its POD after a long init status.

 

**Version of Helm and Kubernetes**: 
HELM: v3.0.1
K8s: 1.14 (AWS EKS)

**Which chart**:
jenkins-1.9.9 lts

**What happened**:
With Jenkins stable HELM chart installation with EKS, deployment fails with its POD after a long init status:

The output of `describe pod jenkins-5d7b7568b7-kptxp` is:

`Events:
  Type     Reason                  Age                From                                                    Message
  ----     ------                  ----               ----                                                    -------
  Warning  FailedScheduling        17m (x3 over 17m)  default-scheduler                                       pod has unbound immediate PersistentVolumeClaims (repeated 2 times)
  Normal   Scheduled               17m                default-scheduler                                       Successfully assigned default/jenkins-5d7b7568b7-kptxp to ip-10-0-146.us-west-2.compute.internal
  Normal   SuccessfulAttachVolume  17m                attachdetach-controller                                 AttachVolume.Attach succeeded for volume "pvc-2f8275b2-1d2c-11ea-82ec-0a5c4d1bbb08"
  Warning  BackOff                 18s                kubelet, ip-10-0-122-146.us-west-2.compute.internal  Back-off restarting failed container
  Normal   Pulling                 5s (x3 over 17m)   kubelet, ip-10-0-122-146.us-west-2.compute.internal  Pulling image "jenkins/jenkins:lts"
  Normal   Pulled                  4s (x3 over 17m)   kubelet, ip-10-0-122-146.us-west-2.compute.internal  Successfully pulled image "jenkins/jenkins:lts"
  Normal   Created                 4s (x3 over 17m)   kubelet, ip-10-0-122-146.us-west-2.compute.internal  Created container copy-default-config
  Normal   Started                 3s (x3 over 17m)   kubelet, ip-10-0-122-146.us-west-2.compute.internal  Started container copy-default-config`

`jenkins-5d7b7568b7-kptxp                         0/1     Init:Error   2          26m`

**What you expected to happen**:  I tried the same chart within minikube it worked. I would need to see this chart work in EKS.

**How to reproduce it** (as minimally and precisely as possible):
At any EKS environment, issue: 

`helm install my-release stable/jenkins`

**Anything else we need to know**:

**Comment by bwhicks-colpal** [comment]
I encountered a similar bug on Helm 0.14.1 and EKS (1.14). The error seems to come when the `defaultConfig` init container tries to copy JCaSC files across. When I can spin up a staging Jenkins, I will attempt to reproduce the more details output of the failed copy-over.

**Comment by laith-leo** [comment]
I figured out the issue, the pod has no internet access, so it fails when Jenkins is downloading the plugins from the public internet.
