### ISSUE TITLE
[stable/airflow] Helm install airflow error

### ISSUE THREAD

**Issue by Aya-Yang** [helm/charts#19585]
**Version of Helm and Kubernetes**:
helm: 3.0.1
kubernetes: 1.16.2

**What happened**:
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]

**What you expected to happen**:
Deployment

**How to reproduce it** (as minimally and precisely as possible):
helm install airflow --namespace "airflow" stable/airflow

**Comment by anirudhkm** [comment]
Even, I had the exact same error. Any help is appreciated.

**Comment by arjun921** [comment]
Try using helm2

**Comment by deblasis** [comment]
Hi, I have the same error, it looks like that the referenced dependencies: *redis* and *postgresql* have outdated schemas for **StatefulSet** and **Deployment**
