### ISSUE TITLE
[stable/kong] real_ip_recursive not changing to on with values.yaml

### ISSUE THREAD

**Issue by pyrander** [helm/charts#19596]
[values.txt](https://github.com/helm/charts/files/3962851/values.txt)

**Describe the bug**
installing Kong with helm and values.yaml
real_ip_recursive set to On
```json
helm install kong-api stable/kong -f values.yaml --namespace mynamespace
```
**Version of Helm and Kubernetes**:
helm client: v2.15.1
helm server: v2.15.1
kubernetes: v1.14.8
**Which chart**:
stable/kong, chart  version kong-0.23.0
kong version 1.3

**What happened**:
real_ip_recursive  values still off

**What you expected to happen**:
real_ip_recursive changed to On

**How to reproduce it**
install stable/kong with helm and values.yaml with real_ip_recursive set to On

**Anything else we need to know**:
all other properties changed as expected:
trusted_ips changed OK
real_ip_header changed OK
proxy_listen: changed OK

Attached values.yaml

**Comment by hbagdi** [comment]
Please quote the real_ip_recursive in the YAML: "on".

**Comment by pyrander** [comment]
real_ip_recursive changed to ON as @hbagdi  indicated.
it should be stated that it need quotes on the documentation.

closing the issue
