### ISSUE TITLE
[stable/datadog] `useConfigMap` not used when `useDedicatedContainers` is true

### ISSUE THREAD

**Issue by odannyc** [helm/charts#19602]
**Describe the bug**
When `useDedicatedContainers` is set to true, many containers are spun up for the different agents. Unfortunately when that's set to true `useConfigMap` is no longer considered causing any custom `datadog.yaml` parameters to not be imported into the yaml files.

**Version of Helm and Kubernetes**:
- datadog-1.38.12

**Which chart**:
- datadog-1.38.12

**Comment by matt-canty-dragon** [comment]
Related to my findings in #19373

**Comment by odannyc** [comment]
@hkaj @CharlyF 

Let me know if you guys have any insight on this

**Comment by clamoriniere** [comment]
thanks of opening this issue, I will look at it.
