### ISSUE TITLE
[stable/nginx-ingress] failed to download

### ISSUE THREAD

**Issue by wy193777** [helm/charts#19630]
**Describe the bug**
When I try to install `stable/nginx-ingress`, helm says
`Error: failed to download "nginx-ingress" (hint: running `helm repo update` may help)`

**Version of Helm and Kubernetes**:
```
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

```
stable/nginx-ingress
```

**What happened**:
```
helm install stable/nginx-ingress nginx-ingress \
    --namespace staging \
    --set controller.replicaCount=1 \
    --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux \
    --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux
Error: failed to download "nginx-ingress" (hint: running `helm repo update` may help)
```

**What you expected to happen**:
no error and nginx-ingress get installed.

**How to reproduce it** (as minimally and precisely as possible):

Try the command on **What happened**.

**Anything else we need to know**:

I already tried `helm repo update`. And stable charts are on my repo.

```
helm repo list                                  
NAME    	URL                                              
jetstack	https://charts.jetstack.io                       
stable  	https://kubernetes-charts.storage.googleapis.com/
```

I find that I cannot find `nginx-ingress` on https://kubernetes-charts.storage.googleapis.com/ response.

**Comment by flxs** [comment]
@wy193777 The listing you linked to is just truncated, `nginx-ingress` is present at https://kubernetes-charts.storage.googleapis.com/nginx-ingress-1.26.2.tgz

Are you absolutely positive you don't maybe accidentally not have the stable repo in your helm? Meaning, if you run `helm repo list`, you're not getting this line:

```
stable      	https://kubernetes-charts.storage.googleapis.com/
```

**Comment by wy193777** [comment]
I'm confident the stable repo is there as shown in above. Already tried multiple times.

**Comment by Xorima** [comment]
The cluster is not behind any proxies or other network restricting environment?

**Comment by wy193777** [comment]
OK, I find the problem after install with `--debug`. After helm removed `--name` flag, I need specify name right after `install` instead of after <package-name>.

**Comment by msbond** [comment]
I am finding the same issue with 

helm-release in terraform. Could you help me to find what is wrong here?

```resource "helm_release" "nginx-ingress" {
  count     = "1"
  name      = "nginx-ingress-internal"
  repository = "https://kubernetes-charts.storage.googleapis.com"
  chart     = "stable/nginx-ingress"
  namespace = "${var.namespace}"
  version   = "${var.nginx_ingress_chart_version}"

  values = [
    "${file("${path.module}/ingress.yaml")}",
  ]
}
```

**Comment by quequiere** [comment]
Try
resource "helm_release" "nginx-ingress" {
  name       = "nginx-ingress-internal"
  chart      = "nginx-ingress"
  repository = "https://kubernetes-charts.storage.googleapis.com"
  namespace  = "${var.namespace}"

**Comment by rmasclef** [comment]
@quequiere that one works fine, any idea why ?

I have the same issue with a private repository and couldn't figure out why the helm provider can't find the desired chart.

**Comment by alfonzso** [comment]
so if you try: 
```shell
$ helm fetch stable/nginx-ingress
Error: Failed to fetch https://charts.helm.sh/stable/nginx-ingress-1.41.3.tgz : 404 Not Found
```
so the tar file not here sadly ...

use instead:  
```shell
$ helm fetch stable/nginx-ingress --version 1.34.2
```
or even:
```shell
$ helm upgrade -i --namespace ingress-nginx inng stable/nginx-ingress --version 1.34.2
```

**Comment by jjindrich** [comment]
Follow this https://registry.terraform.io/providers/hashicorp/helm/latest/docs

**Comment by jerrychong25** [comment]
> so if you try:
> 
> ```shell
> $ helm fetch stable/nginx-ingress
> Error: Failed to fetch https://charts.helm.sh/stable/nginx-ingress-1.41.3.tgz : 404 Not Found
> ```
> 
> so the tar file not here sadly ...
> 
> use instead:
> 
> ```shell
> $ helm fetch stable/nginx-ingress --version 1.34.2
> ```
> 
> or even:
> 
> ```shell
> $ helm upgrade -i --namespace ingress-nginx inng stable/nginx-ingress --version 1.34.2
> ```

Thanks! This method works for me 👍

**Comment by IkechukwuAKalu** [comment]
If anyone still experiences this issue and none of the above solutions works for you, you can try the following command:

```
$ helm repo add stable https://charts.helm.sh/stable
```
