### ISSUE TITLE
helm 3.0 upgrade not add new resource

### ISSUE THREAD

**Issue by wu0407** [helm/charts#19653]
change `"prometheus.additionalPodMonitors: []`" to` "prometheus.additionalPodMonitors: somethings"`  in prometheus operator  values.yaml and  `helm upgrade prometheus-operator -n kube-system .` , it not add new podmonitors.
but use `helm upgrade prometheus-operator -n kube-system .  -f values.yaml`, new podmonitors is added.

Output of `helm version`:
test in 3.0.0 and 3.0.1
Output of `kubectl version`:
1.14.4
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
ubuntu 18.04

**Comment by bacongobbler** [comment]
transferring to helm/charts as this is a question about a particular chart's behaviour when modifying its values.

**Comment by wu0407** [comment]
next update some this in  the values.yaml,  it upgrade failed.
```
helm upgrade prometheus-operator -n kube-system .   -f values.yaml 
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: PodMonitor, namespace: kube-system, name: istio-proxy
```

**Comment by wu0407** [comment]
it seem `helm upgrade prometheus-operator -n kube-system .` only update exist object, `helm upgrade prometheus-operator -n kube-system .   -f values.yaml ` update exist object and create new object.

**Comment by wu0407** [comment]
https://github.com/helm/helm/issues/6850

**Comment by lilvyao** [comment]
Still having issues. Has anyone found any workaround yet?
