### ISSUE TITLE
[stable/mongodb-replicaset] Unable to install replica set

### ISSUE THREAD

**Issue by mhdzaid** [helm/charts#19665]
**Describe the bug**
* I tried installing using the command
`helm install --name vjp-mongo --set image.tag=4.0 --set initMongodStandalone="db.adminCommand( { setFeatureCompatibilityVersion: '4.0' } )" --names
pace vijump  stable/mongodb-replicaset
`
* Unfortunately, i got the following error

`Error: parse error in "mongodb-replicaset/templates/_helpers.tpl": template: mongodb-replicaset/templates/_helpers.tpl:65: unexpected "-" in define clause`

**Version of Helm and Kubernetes**:
Helm v2.13.0

**Which chart**:
stable/mongodb-replicaset

**Anything else we need to know**:
* The same command was working a month ago.
* I ran the same command with `incubator/mongodb-replicaset` instead of ` stable/mongodb-replicaset` and it worked.
* I see that a [commit](https://github.com/helm/charts/commit/174269c90b0f143e3f6bd1477721c7a124570284) was made a few hours ago in [_helpers.tpl](https://github.com/helm/charts/blob/master/stable/mongodb-replicaset/templates/_helpers.tpl)
* On line number  65 `{{- define "mongodb-replicaset.connection-string"  -}}` , there are two spaces between `"mongodb-replicaset.connection-string"` and `-`, maybe this could be the problem ?

**Comment by oba11** [comment]
same here

**Comment by blazhemitrev** [comment]
same here

**Comment by mhdzaid** [comment]
Able to get it working by adding `--version 3.10.3` in my `helm install` command. 
But still getting error with any version after `3.10.3`.
