### ISSUE TITLE
[stable/anchore-engine] Allow ingress configuration for enterprise feed service

### ISSUE THREAD

**Issue by signed8bit** [helm/charts#19672]
Description
-----------

Support an ingress configuration for the enterprise feed service in the same manner that the UI and API are configured, e.g.

```
anchore-engine:
  ingress:
  ...
    feedHosts:
      - anchore-feeds.mydomain.com
  ...
```

Problem
--------

In our use of Anchore, we are building a lot of tooling against the API. As such, we often have ephemeral development deployments of Anchore which could benefit from being able to use our master deployment's feed service instead of needing to sync and populate from scratch.

**Comment by Btodhunter** [comment]
This should be easy enough to add. I'll try to get to it ASAP
