### ISSUE TITLE
[stable/mongodb] updating chart fails in standalone deployment

### ISSUE THREAD

**Issue by baumgartnerniels** [helm/charts#19716]
**Describe the bug**
When setting replicaSet.enabled=false and persistence is enabled, after updating the chart, the mongodb pod fails with "Multi-Attach error for volume".

**Version of Helm and Kubernetes**:
Helm v2.14.1
K8S v1.14.5

**Which chart**:
stable/mongodb

**What happened**:
Updating the mongodb chart with a single mongodb instance failed with: "Multi-Attach error for volume".

**What you expected to happen**:
Successful update with all new pods starting.

**How to reproduce it** (as minimally and precisely as possible):

Preconditions: ReadWriteMany not supported by Volume Plugin.

* deploy mongodb chart in [current version -1]
* use helm update to update the chart to the latest version
* see the mongodb pod failing

**Anything else we need to know**:
In `stable/mongodb/templates/deployment-standalone.yaml` the updateStrategy.type parameter is not considered for spec.strategy.type , so it will always be RollingUpdate, which does not work if the Volume Plugin does not support ReadWriteMany.

The Fix would be to allow setting spec.strategy.type to Recreate in the Deployment.

This was already done for the StatefulSets (#12327), looking at the template there seems to be a bug there as well - updateStrategy.type=Recreate is not a valid Setting for StatefulSets so the condition in there is obsolete.

**Comment by baumgartnerniels** [comment]
@donifer just saw your comment on #12327, when opening this bug. We seem to be having the same Issue.

**Comment by javsalgar** [comment]
Hi,

Would the change in #12327 solve the issue then?

**Comment by baumgartnerniels** [comment]
Hello @javsalgar 

Not #12327 directly, as it's already merged, but applying the same change to the file `stable/mongodb/templates/deployment-standalone.yaml` should do the trick.

**Comment by javsalgar** [comment]
Hi,

I just saw that this https://github.com/helm/charts/pull/19720 was already merged. Is that it?

**Comment by baumgartnerniels** [comment]
Hi, sorry for the late response. Yes, that was it, thanks.
