### ISSUE TITLE
stable/sonarqube

### ISSUE THREAD

**Issue by jting111** [helm/charts#19723]
When I attempted to install Chart `stable/sonarqube` using Helm, I get the following error:

```
$ helm install sonarqube2 stable/sonarqube
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```
Versions I'm using:

```
$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

$ kops version
Version 1.16.0-alpha.2 (git-dfaf0b633)
```
Anything wrong by me?  I thought stable/sonarqube could be installed with default `values`.

I know my Kubernetes cluster is working because I already have an unrelated Pod deployed and exposed.

**Comment by srehmanproov** [comment]
any update on this I am getting same issue with stable/sonarqube charts, are these not maintained anymore?

**Comment by jting111** [comment]
No updates from me.  I never got this to work.

**Comment by srehmanproov** [comment]
Seems only way is to downgrade kubernetes version to get it working.

**Comment by michalbehun** [comment]
We still face this issue. We use PG that is bundled with sonarqube by default. I used helm fetch --untar stable/sonarqube and It seems PG chart used as a dependency is still using "extensions/v1beta1" for its deployment.
