### ISSUE TITLE
[stable/rabbitmq] rabbitmq_peer_discovery_k8s.app error

### ISSUE THREAD

**Issue by yxxhero** [helm/charts#19738]
BOOT FAILED
===========

Error description:
   {error,{"no such file or directory","rabbitmq_peer_discovery_k8s.app"}}

Log files (may contain more information):
   tty
   /opt/bitnami/rabbitmq/var/log/rabbitmq/rabbit@rabbitmq-cluster-0.rabbitmq-cluster-headless.xinhuawgs-prd.svc.cluster.local-sasl.log

Stack trace:
   [{app_utils,load_applications,2,[{file,"src/app_utils.erl"},{line,106}]},
    {app_utils,load_applications,1,[{file,"src/app_utils.erl"},{line,39}]},
    {rabbit,start_apps,2,[{file,"src/rabbit.erl"},{line,482}]},
    {rabbit,broker_start,0,[{file,"src/rabbit.erl"},{line,302}]},
    {rabbit,start_it,1,[{file,"src/rabbit.erl"},{line,424}]},
    {init,start_em,1,[]},
    {init,do_boot,3,[]}]

=INFO REPORT==== 22-Dec-2019::00:54:37 ===
Error description:
   {error,{"no such file or directory","rabbitmq_peer_discovery_k8s.app"}}

Log files (may contain more information):
   tty
   /opt/bitnami/rabbitmq/var/log/rabbitmq/rabbit@rabbitmq-cluster-0.rabbitmq-cluster-headless.xinhuawgs-prd.svc.cluster.local-sasl.log

Stack trace:
   [{app_utils,load_applications,2,[{file,"src/app_utils.erl"},{line,106}]},
    {app_utils,load_applications,1,[{file,"src/app_utils.erl"},{line,39}]},
    {rabbit,start_apps,2,[{file,"src/rabbit.erl"},{line,482}]},
    {rabbit,broker_start,0,[{file,"src/rabbit.erl"},{line,302}]},
    {rabbit,start_it,1,[{file,"src/rabbit.erl"},{line,424}]},
    {init,start_em,1,[]},
    {init,do_boot,3,[]}]

**Comment by yxxhero** [comment]
any one can help me?

**Comment by alemorcuq** [comment]
Hi, @yxxhero.

Can you give us some context to help us reproduce the issue? How are you deploying the chart? When are you getting the error? When you create a new ticket there's a template you can fill with useful information for us.

**Comment by alemorcuq** [comment]
Any news on this, @yxxhero ?

**Comment by yxxhero** [comment]
@alemorcuq  I found the answer. thanks  because i use it by error way.

**Comment by suistack** [comment]
@yxxhero hello, how do you deal with it ?
