### ISSUE TITLE
stable/rabbimq External Community Plugins

### ISSUE THREAD

**Issue by anperim** [helm/charts#19733]
I need rabbitmq_delayed_message_exchange external community plugin inside container. Any idea to have this inside the chart?

I´m doing with modified statefulset.yaml in container command section:
...
            {{- if .Values.rabbitmq.externalPlugins }}
            #externalPlugins
            apt-get update
            apt-get -y install wget
            {{- range  .Values.rabbitmq.externalPlugins }}
            wget -P /opt/bitnami/rabbitmq/plugins/ {{ . }}
            {{- end }}
            {{- end }}
...

This requires run securityContext as root and create a new option "externalPlugins"

helm install --set 
rabbitmq.extraPlugins="rabbitmq_delayed_message_exchange",
rabbitmq.externalPlugins[0]="https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.8.0/rabbitmq_delayed_message_exchange-3.8.0.ez",securityContext.runAsUser=0

**Comment by alemorcuq** [comment]
Hi, @anperim. You can use `curl` instead of `wget` so you don't have to run the container as `root`.

```
$ cd /opt/bitnami/rabbitmq/plugins && curl -LO curl -LO https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.8.0/rabbitmq_delayed_message_exchange-3.8.0.ez
```

Maybe we could add some kind of init script to be executed in the command section that you could create or configure in a Config Map. What do you think?

**Comment by alemorcuq** [comment]
Any news on this, @anperim ?
