### ISSUE TITLE
[stable/rabbitmq] Changing user password after install causes error 401

### ISSUE THREAD

**Issue by krisclarkdev** [helm/charts#19759]
**Describe the bug**
If the user password is changed after rabbitmq is installed it will result in pod restarts and a 401 errors

**Version of Helm and Kubernetes**:
Kubernetes version 1.17.0
Helm version 3.0.2

**Which chart**:
stable/rabbitmq

**What happened**:
After changing the password via the UI the result is failing pods that get restarted with the following error

```
  Warning  Unhealthy               7s (x4 over 98s)  kubelet, k8s-02          Readiness probe failed: curl: (22) The requested URL returned error: 401
  Warning  Unhealthy               6s (x4 over 96s)  kubelet, k8s-02          Liveness probe failed: curl: (22) The requested URL returned error: 401
```

**What you expected to happen**:
I would expect being able to use rabbitmq as normal after having changed the user password

**How to reproduce it** (as minimally and precisely as possible):

1. Install the chart

`helm install rabbitmq --set rabbitmq.username=user,rabbitmq.password=password,service.type=LoadBalancer stable/rabbitmq`

2. Wait for the pod to get created

3. Login to |IP or HOSTNAME|:15672

4. Navigate to the user settings in the upper right hand side

5. Change the users password

6. Wait approximately 3 minutes or less for the pod to fail

7. Describe the pod to see the error

**Anything else we need to know**:

**Comment by alemorcuq** [comment]
Hi, @krisclarkdev.

The chart depends on the `$RABBITMQ_PASSWORD` environment variable to perform the liveness and readiness probes, as you can see here: https://github.com/helm/charts/blob/d6f344368fec2fba30d150ad4154b0bb9e898ece/stable/rabbitmq/templates/statefulset.yaml#L147

Maybe you could run `helm upgrade` to update your password after changing it via de UI? Would that help?

**Comment by krisclarkdev** [comment]
For some reason my helm upgrade command isn't working, but I uninstalled and reinstalled with the updated password and it worked.  So I assume the helm upgrade would be the correct solution considering the rabbitmq password is still set in the PVC.

Is this documented somewhere?  I'd think this problem and solution should be in the installation readme

**Comment by alemorcuq** [comment]
I've created #19775 so that a change in the secret recreates all the pods. Previously, running `helm upgrade` to set the new password only updated the secret, while the pods would still be running thinking the password was the previous one.

I've also added a common issues section to the readme with this use case.

**Comment by alemorcuq** [comment]
Did #19775 fix your issue, @krisclarkdev ?
