### ISSUE TITLE
[stable/postgresql] readiness probe fails with 11.1.0-debian-9-r78 image

### ISSUE THREAD

**Issue by fdlk** [helm/charts#19766]
**Describe the bug**
Using the 11.1.0-debian-9-r78 causes the postgres pod's readiness probe to fail because the .initialized file is not where it's supposed to be.

```
> helm version
**Version of Helm and Kubernetes**:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

> kubectl version   
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/postgresql chart

**What happened**:
After upgrading the helm/postgresql chart from 5.2.1 to 8.1.1, and the bitnami/postgres image to te latest 11.1.0 version, the postgres pod keeps failing the readiness check.

**What you expected to happen**:
I expect the postgres pod to become ready and the postgres service to become usable.

**How to reproduce it** (as minimally and precisely as possible):
`> helm install helm/postgresql --generate-name --set image.tag=11.1.0-debian-9-r78`

**Anything else we need to know**:
I've done some debugging and the issue is that the `.initialized` file is not where the readiness probe expects it to be.
As a workaround, I've re-tagged the `bitnami/postgresql` image to `fdlk/postgresql`. The readiness probe then does not expect the .initialized file to be there and everything works like a charm.

**Comment by fdlk** [comment]
Done some more experimenting and it looks like it's the image tag rather than the existing claim that's to blame. Updating the issue accordingly.

**Comment by carrodher** [comment]
Hi @fdlk, thank you for reporting this issue and provide a workaround using your own registry for the image.

I just found the source of the error. The chart includes as part of the readiness probe the following command:
```bash
[ -f /opt/bitnami/postgresql/tmp/.initialized ]
```
this path is valid for images `>11.2.0-r69`.

In previous images, the `.initialized` the file appeared on another path. As you can see in the [image changelog](https://github.com/bitnami/bitnami-docker-postgresql#9612-r70-9612-ol-7-r72-1070-r69-1070-ol-7-r71-1120-r69-and-1120-ol-7-r71), the image was moved from NodeJS to Bash logic in this version (`11.2.0-r69`).
The refactoring, among other changes, modified the mentioned path.
So the readiness probe is not working as expected with old versions (previous to the new bash logic).

I just created a PR including both paths in the probe so the chart should be compatible with the old images.
