### ISSUE TITLE
[couchbase-operator stable/chart] a question related to couchbase charts

### ISSUE THREAD

**Issue by ayoubfaouzi** [helm/charts#19793]
**Describe the question**
I have two questions related to couchbase charts.

1. This Github repo does not have the couchbase-cluster chart (only the couchbase-operator), shall we use the one in couchbase-partners? or you plan to move it here as well ?
2. When we are deploying our helm chart which depends on the couchbase-cluster and operator at the same time, the `helm install` command fails with: 
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CouchbaseCluster" in version "couchbase.com/v1"
```
This happens because helm tries to install the cluster before making sure the operator has been deployed first, is there any workaround for this?

Here is my chart.yaml

```
    - name: couchbase-operator
      version: 0.1.2
      repository: https://couchbase-partners.github.io/helm-charts/
      condition: couchbase-operator.enabled
    - name: couchbase-cluster
      version: 0.1.2
      repository: https://couchbase-partners.github.io/helm-charts/
      condition: couchbase-cluster.enabled
```
**Version of Helm and Kubernetes**:
Helm: 3.0.2
K8s: Client Version: v1.17.0 \ Server Version: v1.15.6

**Which chart**:
Couchbase.

**Anything else we need to know**:
@tahmmee 

Cheers.

**Comment by tahmmee** [comment]
Hi @LordNoteworthy 
Regarding 1st question: You are correct only the operator is published here in the repo.  Currently you will need to use cluster from partners repo but we will be porting that one over as well.

2nd: This is a known issue unfortunately.  The CRD Management is better in helm 3 and we'll be improving this - https://v3.helm.sh/docs/topics/charts_hooks/#the-available-hooks
The current recommendation is to do a 1 time install of the crd.yaml before running umbrella charts like you have there.

**Comment by LordNoteworthy** [comment]
I see, that answers my questions, we can close this one. Thank you.

Just a note, if you port the current couchbase-cluster chart, can you make an option to not have that `default` bucket, please? 

Cheers.
