### ISSUE TITLE
[incubator/solr] Support for Kubernetes 1.16.2

### ISSUE THREAD

**Issue by ashishpahwa7** [helm/charts#19823]
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"

**Version of Helm and Kubernetes**:
Helm: version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
Kubernetes:  1.16.2

**Comment by eyenx** [comment]
The problem comes from `incubator/zookeeper`

**Comment by eyenx** [comment]
Fixing the version of the requirements.txt for incubator/zookeper to `2.1.3` fixes this issue

**Comment by eyenx** [comment]
bump
