### ISSUE TITLE
[stable/prometheus-operator] deployed grafana is missing grafana-piechart-panel plugin

### ISSUE THREAD

**Issue by torlenor** [helm/charts#19825]
**Describe the bug**
The deployed Grafana is missing the plugin grafana-piechart-panel plugin which is used in Networking related dashboards.

![image](https://user-images.githubusercontent.com/14080364/71656537-d0f10c00-2d3b-11ea-9819-90e3b96d5b0a.png)

**Version of Helm and Kubernetes**:

`$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
`

Kubernetes: 1.16.3-00

**Which chart**:
[stable/prometheus-operator]

**What happened**:
Grafana Plugin is missing.

**What you expected to happen**:
Plugin to be included for all delivered Grafana dashboards.

**How to reproduce it** (as minimally and precisely as possible):

1. Deploy the chart (`helm install --name my-release stable/prometheus-operator`)
2. Use a web browser to go to the freshly deployed Grafana instance
3. Navigate to the, e.g., Kubernetes / Networking / Workload dashboard

**Comment by s2504s** [comment]
Hi all!
We faced this issue too
Somebody know/have some work around for this issue?

**Comment by SergeSpinoza** [comment]
Hi. I have the same issue. 
Kubernetes: 1.16.3
Helm version: 3.0.0

**Comment by pnduati** [comment]
@s2504s @SergeSpinoza To install the plugin, pass the plugins you want installed as a comma separated string in the values.yaml file.
```plugins: "grafana-piechart-panel"```

**Comment by SergeSpinoza** [comment]
@pnduati But the is no variable `plugins` - https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml

**Comment by s2504s** [comment]
@SergeSpinoza Yea, you are right. That is a list
I've set up grafana as part of prometheus-operator and this parameter in my values file looks like :
```
grafana:
  enabled: true
    plugins:
      - grafana-piechart-panel
.....
```
