### ISSUE TITLE
Why does rabbit-ha and rabbit use different images?

### ISSUE THREAD

**Issue by wjdavis5** [helm/charts#19824]
This is really just a question. 
Why does the rabbitmq-ha chart use the official rabbitmq image but the rabbitmq chart use the bitnami version?

It would seem to me that we'd want both using the official version since it is well maintained by the creators of the project.

https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/values.yaml#L298
`  repository: rabbitmq`
https://github.com/helm/charts/blob/master/stable/rabbitmq/values.yaml#L16
`  repository: bitnami/rabbitmq`

**Comment by juan131** [comment]
Hi @wjdavis5 

Bitnami is one of the core maintainers of this chart repository and there are several charts maintained by its team.

These charts use Bitnami images and they're compatible with other images. For instance, you can switch to use any other RabbitMQ image on this chart by setting the `image.repository` and `image.tag` parameters.

Bitnami images are secure, well maintained, and up-to-date (more info at https://github.com/bitnami/bitnami-docker-rabbitmq/#why-use-bitnami-images).

**Comment by wjdavis5** [comment]
I'm not questioning whether or not Bitnami is ok, just more curious about the lack of consistency between the two, seemingly related, charts.

**Comment by juan131** [comment]
Hi @wjdavis5 

The main reason is that different teams/developers are maintaining these charts. These teams decided to use different images on their charts (I don't think there's any other reason).

With this chart repository disappearing in a few months (we're moving to distributed repositories), I don't think it's worth to standardise the images used on the charts on the repo.
