### ISSUE TITLE
[stable/minecraft] Add ability to use an Ingress

### ISSUE THREAD

**Issue by jfmatth** [helm/charts#19850]
Allow minecraft to use an ingress controller for it's public traffic.  Right now you have a lot of flexibility around the LB settings, but it would be great to use Ingress.  Using an Ingress allows frugal users to keep costs down for all their public traffic on K8s implementations.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Similar to other HELM charts, provide an Ingress section in the values.yaml file for me to fill in.

**Describe alternatives you've considered**
I found another HELM chart on github that does this, but have not tested.  I'm thinking for forking this one to try out my idea.

**Comment by TJM** [comment]
What was the finding here? We also don't want to use a load balancer for this.
