### ISSUE TITLE
[stable/prometheus-operator] Lots of missing data

### ISSUE THREAD

**Issue by pageanengineer** [helm/charts#19857]
**Describe the bug**
When an installed prometheus operator chart is installed onto a new single master / single worker kops cluster I am unable to see many data points. It says 'No data' in lots of places

**Version of Helm and Kubernetes**:
Helm: version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
K8: v1.15.6
Kops: Version 1.15.0 (git-9992b4055)
**Which chart**:
prometheus operator latest chart

**What happened**:

**What you expected to happen**:
I expected to be able to see all data points for the default charts. 

**How to reproduce it** (as minimally and precisely as possible):
```
kops create cluster --name=k8s.domain.com --master-zones \
 us-east-1a --zones us-east-1a \
 --node-count=1 --node-size=t3.medium --master-size=t3.small \
 --dns-zone=k8s.domain.com --vpc vpc-<ID> --topology public \
 --networking flannel --ssh-public-key "~/.ssh/id_rsa.pub" 
kops update cluster --name k8s.domain.com --yes

helm install monitoring stable/prometheus-operator  --namespace=monitoring

kubectl port-forward -n monitoring prometheus-monitoring-prometheus-oper-prometheus-0 3141
kubectl port-forward -n monitoring monitoring-grafana-69fcf47c7c-dqh8w 3000
```
naviagate to localhost:3000 then see dashboards which lack data - many are lacking in at least one spot

**Anything else we need to know**:

**Comment by jl-ward** [comment]
We are also going seeing this issue in Minikube on chart version 8.2.2.  I would also note that we have been on this version for awhile and it has previously proved to be working.  We also haven't changed our helm/minikube/k8s versions in a few weeks and just a few days ago this was working fine.

**Comment by rjshrjndrn** [comment]
I think lots of metric names changed. I am now figuring out what are the correct metric names for every dashboard. for instace, `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate` there is no such metric in prometheus.

**Comment by jl-ward** [comment]
Just discovered that our issue was based on the Minikube clock falling behind when a machine sleeps.  This results in not being able to interact with Prometheus and/or Grafana from the UI as it measures the discrepancy between the browser clock and the server clock.  At least in the case of Minikube, we are able to stop and start it and everything works again.
