### ISSUE TITLE
[stable/flunetd] Downgrade HPA from autoscaling/v2beta2 to autoscaling/v2beta1

### ISSUE THREAD

**Issue by nvtkaszpir** [helm/charts#19861]
**Is your feature request related to a problem? Please describe.**
Chart version 2.3.2 allows to use fluentd with statefulset with horizontal pod autoscaler.
But unfortunately it uses `autoscaling/v2beta2` which is not available in certain kubernetes instances, especially the managed ones.

I suggest to downgrade it to `autoscaling/v2beta1` which also allows using custom metrics for scaling, as described by [official GKE docs](https://cloud.google.com/kubernetes-engine/docs/tutorials/custom-metrics-autoscaling)

**Describe the solution you'd like**
stable/fluentd/templates/hpa.yaml
Replace `autoscaling/v2beta2` with `autoscaling/v2beta1`

**Describe alternatives you've considered**
Not using autoscaler but using statefulset as proposed in #19668

**Additional context**
If your k8s api does not expose ` autoscaling/v2beta1` helm installation with autoscaling enabled ends with deployment error.

**Comment by nvtkaszpir** [comment]
ping @rendhalver @miouge1 @hectorj2f

**Comment by Miouge1** [comment]
My 2 cents: It looks like `autoscaling/v2beta2` is available since v1.12 that's far back. I don't think that the chart should default to v2beta1 because v2beta2 has been around for so long.

Though there could be a config option to switch between versions.

**Comment by hectorj2f** [comment]
In addition to what @Miouge1 added, we are already using `autoscaling/v1` so downgrading to beta1 version seems wrong to me.

**Comment by nvtkaszpir** [comment]
@Miouge1 
Even though `autoscaling/v2beta2` is in k8s since 1.12 but as alpha feature, unfortunately this is not the case in cloud providers, for example s not available in GKE - they offer only `autoscaling/v2beta1`.

So maybe just adding a switch option to support both would be sufficient.

@hectorj2f downgrade from v2beta2 to v2beta1 is not equal to downgrade to v1 - actually going back to v1 would be real problem for some.

**Comment by nvtkaszpir** [comment]
so what's the update on this? @rendhalver @Miouge1 @hectorj2f

**Comment by Miouge1** [comment]
Nothing to add since my last comment.

**Comment by nvtkaszpir** [comment]
OK, so this is just a known limitation.

This renders that this chart has certain features which are unavailable for certain cloud providers.
The only thing that is left is to make custom fork or wait for cloud provider to support autoscaling/v2beta2.
