### ISSUE TITLE
[stable/kong] - Can't install Kong on Rancher

### ISSUE THREAD

**Issue by minhnnhat** [helm/charts#19868]
Describe the bug
Install of kong chart fails

Version of Helm and Kubernetes:
Helm: v2.14.3-rancher1
Kubernetes: v1.14.5
Version Helm chart: 0.33.1

Which chart:
stable/kong

What happened:
Error: parse error in "kong/templates/NOTES.txt": template: kong/templates/NOTES.txt:10: unexpected "-" in end : exit status 1

What you expected to happen:
install without errors

How to reproduce it (as minimally and precisely as possible):
helm install stable/kong --name kong -f values.yaml

Anything else we need to know:

**Comment by gpabdo** [comment]
This is not specific too Rancher, this is an error in the chart. If someone could remove the extra space here it would fix it. @hbagdi 

https://github.com/helm/charts/blob/f6b1294d00421db8bb438389b9c081ca128aeffc/stable/kong/templates/NOTES.txt#L10
