### ISSUE TITLE
[stable/grafana] helm3 upgrade grafana failed due to PVC is immutable

### ISSUE THREAD

**Issue by latituder** [helm/charts#19870]
**Describe the bug**

**Version of Helm and Kubernetes**:
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
[stable/grafana] 
CHART: grafana-4.0.3
app version: 6.4.2

**What happened**:
changed a value in values.yaml, then tried to use helm upgrade of the version.
not success:
client.go:399: Replaced "scma-grafana" with kind PodSecurityPolicy for kind PodSecurityPolicy
client.go:399: Replaced "scma-grafana" with kind Secret for kind Secret
client.go:399: Replaced "scma-grafana" with kind ConfigMap for kind ConfigMap
client.go:399: Replaced "scma-grafana-clusterrole" with kind ClusterRole for kind ClusterRole
client.go:399: Replaced "scma-grafana" with kind Deployment for kind Deployment
Error: UPGRADE FAILED: failed to replace object: PersistentVolumeClaim "scma-grafana" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims

**What you expected to happen**:
the upgrade keep the PVC, and just update other parts.

**How to reproduce it** (as minimally and precisely as possible):
implement the grafana with a pvc;
change a value (like ingress, or domain_url setting value in values.yaml), then upgrade the chart;

**Anything else we need to know**:

**Comment by silvermind** [comment]
have the same issue, not sure if this is the source of the problem: https://github.com/helm/charts/pull/17806

Setting Values.persistence.storageClassName explicit did't work yet.. any ideas?

**Comment by dkarnutsch** [comment]
The problem is related to https://github.com/helm/helm/issues/6642.

It can be resolved by explicitly setting `persistence.storageClassName` to the default value of your Storage Provisioner. In my case it's GKE which defaults to `standard`.

**Comment by dcherniv** [comment]
@dkarnutsch this is not an option for people who run multiple kubernetes clusters. We have both EKS and GKE. This implies that we need to maintain two separate sets of values for eks and gke one with storageclass: standard another one with storageclass: gp2.

**Comment by villesau** [comment]
This is still a problem. Can this be opened?
