### ISSUE TITLE
[stable/jenkins] Deprecated values are used in templates

### ISSUE THREAD

**Issue by akaRem** [helm/charts#19878]
introduced in https://github.com/helm/charts/pull/19734

https://github.com/helm/charts/blob/9caa79daf6716f4afa6c5c968e5868d8fa44a306/stable/jenkins/templates/config.yaml#L259

`.Values.Master.OverwriteConfig` is used instead of `.Values.master.overwriteConfig` which means that `cp /var/jenkins_config/scriptapproval.xml /var/jenkins_home/scriptApproval.xml;` will be never applied.

**Comment by akaRem** [comment]
cc @heyleke

**Comment by heyleke** [comment]
woops, I'll fix it asap
