### ISSUE TITLE
[stable/jenkins] Render error when setting master.useSecurity to false

### ISSUE THREAD

**Issue by knoppiks** [helm/charts#19896]
Setting `master.useSecurity` to `false` will result in an empty `env` entry within the masters initContainer.

`jenkins-master-deployment.yaml`
```
spec:
[...]
  template:
    [...]
    spec:
    [...]
      initContainers:
        - name: "copy-default-config"
          [...]
          env:
```

**Comment by knoppiks** [comment]
Well. That may be as it is. But the issue persists.

**Comment by torstenwalter** [comment]
@knoppiks Do you want to create a PR to resolve this?
