### ISSUE TITLE
[stable/sonarqube] Custom cacerts is not taken into account by SonarQube

### ISSUE THREAD

**Issue by Thomah** [helm/charts#19894]
**Describe the bug**
Custom cacerts is not taken into account by SonarQube.

**Version of Helm and Kubernetes**:
Helm version : v2.14.3
Kubernetes: 1.14.2

**Which chart**:
stable/sonarqube

**What happened**:
By default, the JVM takes its cacerts from `/usr/local/openjdk-11/lib/security/cacerts` but the chart replace the file at the `/etc/ssl/certs/java/cacerts` location. I had to make the following workaround in the `values.yaml` to make it work :
```yaml
extraEnv: 
  "SONARQUBE_WEB_JVM_OPTS": "-Djavax.net.ssl.keyStore=/etc/ssl/certs/java/cacerts -Djavax.net.ssl.keyStorePassword=<password> -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=<password>"
```

**What you expected to happen**:
The custom cacerts file must be taken into account by the JVM in the container.

**How to reproduce it (as minimally and precisely as possible)**:
Just follow the [Use Custom `cacerts`](https://github.com/helm/charts/blob/master/stable/sonarqube/README.md#use-custom-cacerts) from the `README.md` file.

**Anything else we need to know**:
In my case, the custom cacerts is used by the [OpenID Connect Plugin](https://github.com/vaulttec/sonar-auth-oidc) to communicate with my organization's Keycloak (which has a custom certificate).

Thank you for this amazing work :heart:

**Comment by stevehipwell** [comment]
I'd like to suggest an alternative to the current incomplete implementation would be to support generating the _cacerts_ file dynamically from a secret containing the required additional certificates. I'll try and add a PR later today to support this.
