### ISSUE TITLE
[stable/rabbitmq-ha] Pod probes fail with "connection refused" on any tag except 3.8.0-alpine

### ISSUE THREAD

**Issue by alastairs** [helm/charts#19899]
**Describe the bug**
When using a RabbitMQ Alpine image tag other than `3.8.0-alpine`, the liveness and readiness probes fail with a "Connection refused".

**Version of Helm and Kubernetes**:
Helm 2.14.3 and 2.16.1 (Tiller 2.16.1); Kubernetes 1.12.10-gke.22

**Which chart**: 
stable/rabbitmq-ha 1.38.1

**What happened**:
The Helm install fails as the first RabbitMQ pod never becomes ready. The liveness probe causes Kuberenetes to restart the pod during the Helm install timeout window. 

**What you expected to happen**:
The readiness probe and liveness probes succeed, leading to a successful Helm install. 

**How to reproduce it** (as minimally and precisely as possible):
```bash
$ helm install stable/rabbitmq-ha --set image.tag=3.8.2-alpine --atomic
```

**Anything else we need to know**:
This appears to be the case for any of the Alpine tags except the one used by the chart by default (`3.8.0-alpine`). I have reproduced it with each of `3.8-alpine`, `3.8.2-alpine`, and `3.8-management-alpine`.

(Unrelated, the Alpine images aren't officially supported by the RabbitMQ team. If the supported Ubuntu-based tags are used, the probes fail with "wget not found" 🤷‍♂)

**Comment by sacherus** [comment]
I had this same problem, the issue was that the localhost was resolved as ip6 for some reason. The solution, change definition of the probes for 127.0.0.1 (and readinessProbe as well):
```livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  exec:
    command:
      - /bin/sh
      - -c
      - 'wget -O - -q --header "Authorization: Basic `echo -n \"$RABBIT_MANAGEMENT_USER:$RABBIT_MANAGEMENT_PASSWORD\"
      | base64`" http://127.0.0.1:15672/api/healthchecks/node | grep -qF "{\"status\":\"ok\"}"'```

**Comment by sFrenkie** [comment]
The problem is that RabbitMQ uses **admin** account and password and not **management** account. So the probe example is invalid. 
You can use workaround:
same admin and management name/password
or you can fix propagation of environment variables in chart and add `$RABBIT_USER` `$RABBIT_PASSWORD` to the container and modify probe example.
Good luck.
