### ISSUE TITLE
[stable/nats] api version of template in helm repo outdated

### ISSUE THREAD

**Issue by mgmm13** [helm/charts#19892]
**Describe the bug**
I'm unable to proceed with installation of a default stable/nats (statefulset) due to outdated API version for Statefulset definition as per error message. Possibly not supporting a higher Kubernetes version (1.16) for the api definition.

**Version of Helm and Kubernetes**:
Helm version: v2.11.0
Kubernetes version: v1.16.1

**Which chart**:
stable/nats

**What happened**:
During helm install of NATS, I'm getting the following error: 

```
$ helm install stable/nats
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
```

**How to reproduce it** (as minimally and precisely as possible):
I'm able to deploy successfully using a lower Kubernetes version (1.14). I think the templates from the uploaded helm charts in stable/nats are outdated and needs to be updated. Please refer to the depricated APIs as of Kubernetes 1.16 (https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)

**Comment by juan131** [comment]
Hi @mgmm13 

What version of the NATS chart are you using? That API version was quite a long time ago (see https://github.com/helm/charts/pull/17282)

You can use the command below to update your charts:

```console
$ helm repo update
```

**Comment by mgmm13** [comment]
@juan131 you're right, did that command and it proceeded. I totally forgot that. Thanks!
