### ISSUE TITLE
[stable/neo4j] chart cannot work in k8s 1.16+

### ISSUE THREAD

**Issue by dfateyev** [helm/charts#19934]
**Describe the bug**
Neo4j installation from Helm chart is failed under Kubernetes 1.16+.
```
$ helm install --name neo4j-helm stable/neo4j --set acceptLicenseAgreement=yes --set neo4jPassword=mySecretPassword
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]
```
**Version of Helm and Kubernetes**:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"archive", BuildDate:"2019-12-10T11:28:14Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"archive", BuildDate:"2019-12-11T14:00:15Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
```
$ helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
**Which chart**:
stable/neo4j

**What happened**:
An error during Helm chart installation

**What you expected to happen**:
An installed Neo4j instance from chart

**How to reproduce it** (as minimally and precisely as possible):
Please try to install Neo4j with Helm

**Comment by dave-grix** [comment]
I too have this issue, as well as 

`failed to install app neo4j. Error: validation failed: [unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2", unable to recognize "": no matches for kind "Application" in version "app.k8s.io/v1beta1"]`

**Comment by aoighost** [comment]
I have a similar issue:
 helm install neo4j-helm stable/neo4j --set acceptLicenseAgreement=yes --set neo4jPassword=mySecretPassword
Error: failed to download "stable/neo4j" (hint: running `helm repo update` may help)

**Comment by lovesuper** [comment]
I have faced with this issue too.

**Comment by ruapho** [comment]
Same here:
```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"archive", BuildDate:"2020-02-29T16:37:45Z", GoVersion:"go1.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.14"}
```

Result:
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]

> I am trying to setup neo4j:4.0.1-enterprise btw.

**Comment by stephen-dahl** [comment]
looks like the fix is in pr but not merged yet

**Comment by lovesuper** [comment]
> looks like the fix is in pr but not merged yet

I have tried to install "fixed" version from source. It was installed but does not work anyway.
