### ISSUE TITLE
[stable/sonatype-nexus] Allow GCP service account to be specified via secret for Nexus Backup w/ Bucket

### ISSUE THREAD

**Issue by huang-jy** [helm/charts#19940]
**Describe the bug**
If you specify `nexusBackup.env.targetBucket`, Nexus Backup needs access to Google Storage. However, if the default account doesn't have access to the bucket, the backup will fail:

```
==> Attempting to backup the 'default' blobstore.
tar: removing leading '/' from member names
AccessDeniedException: 403 Primary: /namespaces/XXXXXXXXX.svc.id.goog with additional claims does not have storage.objects.list access to {namespace}.
(!) Couldn't backup the blobstore. Manual intervention is advised.
```

If we can somehow pass in the GCP credentials json of the service account we want Nexus Backup to use, into the chart (e.g. via a secret), we can use that instead. 

**Version of Helm and Kubernetes**:
Helm:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

Kubernetes: GKE

**Which chart**:
OSS 3.17.0-01

**What happened**:
Described above

**What you expected to happen**:
Successful backup using service account specified, not the default account

**How to reproduce it** (as minimally and precisely as possible):
Described above.

**Anything else we need to know**:
N/A

**Comment by huang-jy** [comment]
Okay I found a VERY convoluted workaround.

1. Generate a secret containing your json containing the service account (preferably one that only has access to the one backup bucket)

```
kubectl create secret generic backup-sa \
  --from-file=credentials.json=credentials-key.json \
  --dry-run -o yaml >nexus-backup-sa.yaml
```
2. Add additional values into the values.yaml
```
nexusBackup:
  enabled: true
  secretName: backup-sa
  secretMount: /var/gcp/credentials
  secretKey: credentials-key.json
  env:
    targetBucket: gs://{backup-bucket-name}

```

3. Inject that into the backup pod via the stateful set yaml, and override the entrypoint to activate that service account before starting the entrypoint script:
```
        - name: nexus-backup
          image: {{ .Values.nexusBackup.imageName }}:{{ .Values.nexusBackup.imageTag }}
          imagePullPolicy: {{ .Values.nexusBackup.imagePullPolicy }}
          command: [
            "/bin/bash",
            "-xc",
            "/tmp/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file={{ .Values.nexusBackup.secretMount }}/{{ .Values.nexusBackup.secretKey }} && /docker-entrypoint.sh"
          ]
          .....
          volumeMounts:
            - mountPath: {{ .Values.nexusBackup.secretMount }}
              name: backup-sa
            .....
      volumes:
        - name: backup-sa
          secret:
            secretName: {{ .Values.nexusBackup.secretName }}
```

You should find this in the logs of the backup container:

```
+ /tmp/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=/var/gcp/credentials/credentials-key.json
Activated service account credentials for: [{service-account-key-email}]
+ /docker-entrypoint.sh
==> Monitoring '/nexus-data/backup/.backup'...
```

And the backup should now work.

HOWEVER, since you've modified the chart, you've diverged from the published version.

**Comment by emas80** [comment]
I have this PR open for adding the support
https://github.com/helm/charts/pull/20032
