### ISSUE TITLE
[stable/kong] servicemonitor.yaml: error converting YAML to JSON

### ISSUE THREAD

**Issue by jlentzfl** [helm/charts#19956]
Describe the bug
Tried deploying the latest stable/kong with servicemonitor configured as below:
serviceMonitor:
  enabled: true
  labels:
    release: prometheus-operator

Version of Helm and Kubernetes:
Helm: v2.12.3
Kubernetes: v1.14.8-gke.12

Which chart:
stable/kong version 0.36.1

What happened:
Attempting to deploy resulted in "kong/templates/servicemonitor.yaml: error converting YAML to JSON: yaml: line 10: did not find expected key"

Pulled the chart down locally, then modified servicemonitor.yml line 12 to use nindent instead of indent:
{{ toYaml .Values.serviceMonitor.labels | nindent 4 }}
The generated yaml passed yaml validation while the version with indent did not.

**Comment by hbagdi** [comment]
Could you please PR this to this repository?
We can get it fixed quickly.

**Comment by hbagdi** [comment]
Please close this issue.
