### ISSUE TITLE
[stable/prometheus-operator] Too permissive ClusterRole secret access

### ISSUE THREAD

**Issue by miecio45** [helm/charts#19953]
**Is your feature request related to a problem? Please describe.**
In file `templates/prometheus-operator/clusterrole.yaml` we use very extensive access to secrets, basically we allow any ServiceAccount bound to this ClusterRole to manipulate all secrets.

```
 - apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*' 
```
Do You think it is possible to limit the acess scope? 

**Describe the solution you'd like**
Limit scope of secret access to requied minimum.

**Describe alternatives you've considered**
If this service needs to read all secrets in whole namespace, maybe we can move this part from ClusterRole to Role and add RoleBinding?  I know that k8s do not allow for cross namespace secret/configmap access but having such ClusterRole just do not feel right.

**Additional context**
I do not think that there is anything else.

Thanks!

**Comment by gmartinez-anchor** [comment]
Following https://github.com/helm/charts/pull/20116#issuecomment-626367304, should we re-open this? I'm available to help on this.

**Comment by miecio45** [comment]
I can also help, I just need to know what should I improve in my previous merge request.
