### ISSUE TITLE
[stable/nginx-ingress] least_conn is not supported, falling back to round_robin

### ISSUE THREAD

**Issue by adrian-dinu** [helm/charts#19951]
**Describe the bug**
The logs of nginx-ingress-controller are flooded with the following error:
```
2020/01/08 19:45:28 [warn] 40#40: *3770 [lua] balancer.lua:44: get_implementation(): least_conn is not supported, falling back to round_robin, context: ngx.timer
2020/01/08 19:45:28 [warn] 43#43: *3773 [lua] balancer.lua:44: get_implementation(): least_conn is not supported, falling back to round_robin, context: ngx.timer
2020/01/08 19:45:29 [warn] 42#42: *3776 [lua] balancer.lua:44: get_implementation(): least_conn is not supported, falling back to round_robin, context: ngx.timer
2020/01/08 19:45:29 [warn] 41#41: *3779 [lua] balancer.lua:44: get_implementation(): least_conn is not supported, falling back to round_robin, context: ngx.timer
2020/01/08 19:45:29 [warn] 40#40: *3782 [lua] balancer.lua:44: get_implementation(): least_conn is not supported, falling back to round_robin, context: ngx.timer
2020/01/08 19:45:29 [warn] 43#43: *3785 [lua] balancer.lua:44: get_implementation(): least_conn is not supported, falling back to round_robin, context: ngx.timer
```
Basically 3-4 messages / second, not sure what can I do to fix the warnings (except settings a different loglevel).

**Version of Helm and Kubernetes**:
2.16 / 1.16 

**Which chart**:
nginx-ingress

**What happened**:
Logs get filled with error message.

**What you expected to happen**:
No such messages

**How to reproduce it** (as minimally and precisely as possible):
Did a normal `helm install stable/nginx-ingress`

**Anything else we need to know**:

**Comment by yinjiayi** [comment]
I also find this problem, my version is 0.26.1

**Comment by adrian-dinu** [comment]
I have managed to fix the issue, I found out that you can set the load-balance in any deployment using apps ingress annotation. If you have an app deployed that has it in it's annotations it will cause this issue.

I have installed this plugin https://kubernetes.github.io/ingress-nginx/kubectl-plugin/ and done a 

`kubectl ingress-nginx backends -n <your-namespace> | grep least`

and found the app that was causing the issue.

Make sure you search in all your namespaces.

**Comment by kwaneung** [comment]
> I have managed to fix the issue, I found out that you can set the load-balance in any deployment using apps ingress annotation. If you have an app deployed that has it in it's annotations it will cause this issue.
> 
> I have installed this plugin https://kubernetes.github.io/ingress-nginx/kubectl-plugin/ and done a
> 
> `kubectl ingress-nginx backends -n <your-namespace> | grep least`
> 
> and found the app that was causing the issue.
> 
> Make sure you search in all your namespaces.

I tried the same.

your cmd(kubectl ingress-nginx backends -n <your-namespace> | grep least) is just view lb-method. How did you solve the problem??

**Comment by adrian-dinu** [comment]
I have found the deployment that had the load-balance ingress annotation set to least_conn and fixed it.

**Comment by kwaneung** [comment]
> I have found the deployment that had the load-balance ingress annotation set to least_conn and fixed it.

Can you show yaml file?
