### ISSUE TITLE
[stable/drone] Failed to Gitlab "The redirect URI included is not valid."

### ISSUE THREAD

**Issue by TsixJnineY** [helm/charts#19963]
I can successful deploy with Github, But when I chenged Gitlab, it can't connect with Drone, then I got the issue: The redirect URI included is not valid, my redirect URI is setting host domain of the drone pod and adding a host domain in the Gitlab server /etc/hosts file.
**Describe the bug**

**Version of Helm and Kubernetes**:
I'm on helm 3.0.2 and kubernetes 1.16.4

**Which chart**:
stable/drone

**What happened**:
I got an issue(The redirect URI included is not valid) when I connect drone to Gitlab.

**What you expected to happen**:
It should be directed to the drone page through the Gitlab's application

**How to reproduce it** (as minimally and precisely as possible):
Use kuberbetes 1.16.4 ,Helm3.0.2 and set sourceControl for private gitlab.

**Anything else we need to know**:
Thanks for the nice chart

**Comment by code-chris** [comment]
I have the same issue. Did you find a solution @kyle1739 ?

**Comment by kyle1739** [comment]
HI, you need setting service.host.
