### ISSUE TITLE
[stable/jenkins] custom plugin configuration

### ISSUE THREAD

**Issue by eladazary** [helm/charts#19978]
How can I insert all plugin's configurations to the chart?

Not sure if it's a feature request or already exists, but if it exists please send me an example of it.

**Comment by khande-incomm** [comment]
@eladazary ,

Presuming you want to add/edit the default plugins, you can run following command to get the default `jenkins.value` file :- 
`$helm inspect values stable/jenkins > /PathToFile/jenkins.values`

Then open `jenkins.values` file and edit the plugin section to add your plugins.

then run `$helm install stable/jenkins --values /PathToFile/jenkins.values` to install JENKINS. If all goes well, all your plugins should get installed with JENKINS.

Hope this helps.

Thanks

**Comment by eladazary** [comment]
Hi @khande-incomm, Thanks for the reply.
My meaning here was how can I update the plugin's configuration with my custom values (And not just install them).

E.g: Insert my api token for slack and datadog plugins without changing it manually (Directly from helm install).
