### ISSUE TITLE
[stable/sentry] Update to Sentry 10.0

### ISSUE THREAD

**Issue by hypnoglow** [helm/charts#19981]
Self-hosted Sentry was hugely reworked and now requires much more dependencies: PostgreSQL, Redis, Zookeeper, Kafka, ClickHouse, etc:
- https://blog.sentry.io/2020/01/07/self-hosted-sentry-10-is-ready-to-serve-get-it-while-its-hot/
- https://github.com/getsentry/onpremise

It would be great to keep up and to update Helm chart to Sentry 10 either handling those dependencies as subcharts or providing a way to connect them as external services.

**Comment by Mokto** [comment]
I'm currently working on on Helm3 chart for Sentry.
I don't want to promise anything, but I hope that I will have a usable version next week.

The idea is to have it in a different repo though, as helm charts is being deprecated.

I'll keep you updated ;)

**Comment by Mokto** [comment]
This is REALLY an alpha work but here is the work I've done : https://github.com/sentry-kubernetes/charts

This repo contains 2 charts, sentry and sentry-db, as I think it's really useful to deploy both separately.

Missing :
- [ ] Postgres deployment (we have a standalone one for Sentry where I work)
- [ ] Readme
- [ ] Chart deployed on a repo
- [ ] Auto deployment of the chart (with Github actions)
- [ ] Symbolicator deployment
- [ ] Etc...

But you can have a look already 👍and give me your comments if you can, that would be awesome!

I have a lot of work this week + I'm leaving for vacation, so I probably won't be able to push a workable version before next week.

**Comment by i5okie** [comment]
@Mokto Looks like Sentry has docker-compose for the whole stack (v10.0) https://github.com/getsentry/onpremise. Which includes scripts to get everything setup.

Then I found https://kompose.io/ tool, which can convert docker-compose into manifests. (I've tried it it works). It also has `-c` flag to convert it into helm chart, but of course, it doesn't auto-magically templatize the yaml files :(

Anyway, I hope that helps!

**Comment by natanaelsirqueira** [comment]
@i5okie That works for me. Thanks!

**Comment by Mokto** [comment]
@i5okie I used the docker-compose as a base to build the chart.  But thanks 👍 

I'm happy to say the first version is available now (0.5.0).

It's a beta, so please let me know if anything!

**Comment by loremaps** [comment]
Let's keep it open 😄

**Comment by Mokto** [comment]
Thanks to @DandyDeveloper, we've allowed a smooth transition between this chart and the -sentry 10 compatible- chart, [available here](https://github.com/sentry-kubernetes/charts).

**Comment by max-rocket-internet** [comment]
@Mokto can't we merge that chart back to here?

**Comment by Mokto** [comment]
@max-rocket-internet 

[Helm charts are deprecated.](https://github.com/helm/charts#status-of-the-project)

**Comment by max-rocket-internet** [comment]
I know but we can still merge PRs.

OK, if https://github.com/sentry-kubernetes/charts is the official home of the chart now, then cool.

**Comment by Mokto** [comment]
Sorry, I don't want to waste time moving the code from the new repo to this one.

I'll add a deprecation notice to the current chart when it's fully stable (it's almost there ;))

**Comment by donbeave** [comment]
@Mokto I'll try to use your chart in the production system and give you some feedback.

**Comment by Bessonov** [comment]
further activity occurs

**Comment by Mokto** [comment]
I think we can close this one.

https://github.com/sentry-kubernetes/charts is quite stable now.
