### ISSUE TITLE
Teams for this repository don't have access to the repository

### ISSUE THREAD

**Issue by jackgr** [helm/charts#2]
application-dm-templates-maintainers and application-dm-templates-collaborators have no assigned repositories.
- To correct this problem, visit each team under Teams in the Kubernetes organization.
- On the team page, select the Repositories tab. In the Repositories tab, add this repository to the team, and set the team's permissions appropriately.
  - For application-dm-templates-maintainers the permission should be `Write`.
  - For application-dm-templates-collaborators the permission should be `Read`.

**Comment by vaikas** [comment]
Done, PTAL.
