### ISSUE TITLE
[stable/prometheus-operator] Install fails on helm 3 and Kubernetes 1.16

### ISSUE THREAD

**Issue by jethrogillgren** [helm/charts#20027]
**Describe the bug**
Install fails

**Version of Helm and Kubernetes**:
Helm: v3.0.1
Kubernetes: 1.16
**Which chart**:
stable/prometheus-operator

**What happened**:
`manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(MutatingWebhookConfiguration.webhooks[0].clientConfig): missing required field "caBundle" in io.k8s.api.admissionregistration.v1beta1.WebhookClientConfig`

**What you expected to happen**:
Install

**How to reproduce it** (as minimally and precisely as possible):
The install command used was: `helm install prometheus stable/prometheus-operator`
`helm repo update` also ran. 

**Anything else we need to know**:
The kubernetes insteance was created by KOPS on AWS.

Thanks for any help getting this working!
As Helm 3 has been released, is it worth adding specific steps for Helm 3 on the README? The current command is only valid for helm 2.

**Comment by JethroMV** [comment]
Note that adding `-v 5` gives no further logs, as does using ` --set prometheusOperator.logLevel=all --set prometheus.prometheusSpec.logLevel=all`.  The steps  [here](https://github.com/helm/charts/issues/17511#issuecomment-562578767) did not appear to make any difference.

**Comment by jethrogillgren** [comment]
Note that adding -v 5 gives no further logs, as does using --set prometheusOperator.logLevel=all --set prometheus.prometheusSpec.logLevel=all. The steps here did not appear to make any difference.

**Comment by jethrogillgren** [comment]
https://github.com/helm/charts/issues/17511 seems to cover this in the comments if not the original issue, will delete.
