### ISSUE TITLE
[stable/rabbitmq] additional options for side car container

### ISSUE THREAD

**Issue by Hartorn** [helm/charts#20021]
**Is your feature request related to a problem? Please describe.**

We are using RabbitMQ in our chart, and wanted to use official helm chart as dependency.
But we are using filebeat as sidecar container to centralize the logs towards a logstash.

**Describe the solution you'd like**
An idea would be to add some additional options, such as the ones used in [stable/kibana](https://github.com/helm/charts/tree/master/stable/kibana) or [stable/nginx-ingress](https://github.com/helm/charts/tree/master/stable/nginx-ingress)
* extraContainers
* extraVolumeMounts
* extraVolumes
* extraConfigMapMounts
* ...

That way, a sidecar could be added, with a volume such as an emptyDir between the two containers.

I could make a PR on this if the pattern is ok

**Describe alternatives you've considered**
No idea :(

**Comment by alemorcuq** [comment]
Hi, @Hartorn.

Thank you very much for trying to implement this! I already replied in #20022, so the same applies here! Thanks again!
