### ISSUE TITLE
[stable/datadog] not able to specify resources on init containers

### ISSUE THREAD

**Issue by bkimbrough88** [helm/charts#20035]
**Describe the bug**
When I set daemonset.useDedicatedContainers to true, the helm chart deploys init containers. However there is no way for me to specify the resources for those containers. In my cluster the resources for these containers always defaults to an empty map, but the cluster also has a constraint that all containers must specify resource requests and limits for CPU and memory. This causes the daemonset to fail to deploy.

**Version of Helm and Kubernetes**:
Helm 3.0.2
OpenShift 3.11 (Kubernetes 1.11)

**Which chart**:
stable/datadog

**What happened**:
The daemonset failed to deploy

**What you expected to happen**:
I expect to be able to specify resources so that the daemonset can deploy successfully

**How to reproduce it** (as minimally and precisely as possible):
- Setup cluster to reject any containers that do not have resources specified
- Do not provide default resources for containers
- set daemonset.useDedicatedContainers to true

**Comment by bkimbrough88** [comment]
This is now handled in #18182

**Comment by L3n41c** [comment]
Hello @bkimbrough88,

Resources of init containers are now customisable with [`agents.containers.initContainers.resources.{limits,requests}.{cpu,memory}`](https://github.com/helm/charts/blob/c55ff8eecfc51c3fcc5566cd5fb70971844ecfb8/stable/datadog/values.yaml#L729).
So, can this issue be closed, or is there still a gap ?

**Comment by bkimbrough88** [comment]
@L3n41c Thanks for following up, I actually did find one miss and followed up just now with a PR (#21153). I'm good with closing this issue once that is merged in.
