### ISSUE TITLE
helm fails to install stable/prometheus-operator

### ISSUE THREAD

**Issue by vrathore18** [helm/charts#20085]
helm version 2.12.1

I am getting this issue:
`Error: found in requirements.yaml, but missing in charts/ directory: kube-state-metrics, prometheus-node-exporter, grafana`
I checked for the work around. its saying I need to create the CRDs first
```
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
```
 but do I need to create this in monitoring namespace?

Update: While applying 
`kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml -n monitoring`

I am getting this error

`error: error validating "https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml": error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by ivpusic** [comment]
same here

**Comment by Karnich** [comment]
same.. but with helm 2.16.1

**Comment by dza89** [comment]
The latest version of the prometheus-operator helm chart is not compatible with Kube 1.14. 
You have to use either jsonnet to patch the crds or adjust them yourself manually:

` preserveUnknownFields: null`

**Comment by pmmalinov01** [comment]
> The latest version of the prometheus-operator helm chart is not compatible with Kube 1.14.
> You have to use either jsonnet to patch the crds or adjust them yourself manually:
> 
> ` preserveUnknownFields: null`

Can you elaborate on the jsonnet way to patch it?

**Comment by onyxet** [comment]
We've exprienced same issues during latest chart installation. Can somebody update CRD?
 `kube-prometheus` has already reflected this issue

**Comment by jecnua** [comment]
Please remove the stale label, still valid.

**Comment by jecnua** [comment]
Please remove the stale label, still valid.

**Comment by krichter722** [comment]
Still valid

**Comment by jecnua** [comment]
Still valid unless there is no plan to address it. Please remove the lifecyle label.

**Comment by tobypeschel** [comment]
I don't understand why these CRDs haven't been updated yet; the `kube-prometheus` project has done so, e.g. https://raw.githubusercontent.com/coreos/kube-prometheus/master/manifests/setup/prometheus-operator-0prometheusCustomResourceDefinition.yaml etc.

For now I've just been setting `preserveUnknownFields: null` to get around this issue (or `--validate=false`).
