### ISSUE TITLE
[stable/minio] fix handling of extraArgs

### ISSUE THREAD

**Issue by hutr** [helm/charts#20089]
**Describe the bug**
Additional arguments passed in as values in `extraArgs` is ignored inside the pod even if they are listed in command field. e.g. when describing the pod or deployment.

**Version of Helm and Kubernetes**:
irrelevant for this issue

**Which chart**:
stable/minio v5.0.4

**What happened**:
Additional arguments are not passed to minio binary.

```
$ kubectl describe pod minio-6d5bd7789-7cbd2

...
Command:
      /bin/sh
      -ce
      /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /export
      --compat
...

```
```
$ kubectl exec -it minio-6d5bd7789-7cbd2 sh

/ # ps
PID   USER     TIME  COMMAND
    1 root      0:06 minio -S /etc/minio/certs/ server /export

```

**What you expected to happen**:
Additional arguments to be passed to Minio binary. Arguments should be in the same line as docker-entrypoint.sh, e.g:

```
$ kubectl describe pod <podname>
...
    Command:
      /bin/sh
      -ce
      /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /export --compat
...
```
```
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:08 minio -S /etc/minio/certs/ server /export --compat
```

**How to reproduce it** (as minimally and precisely as possible):
`$ helm install --set extraArgs="{--compat}" stable/minio`

**Anything else we need to know**:
Refer to discussion in #17075

**Comment by gennady-melesh** [comment]
It helped me: 
values.yaml
---------------------------
mountPath:
  /export --compat
---------------------------

**Comment by bad** [comment]
Can some please merge the pull-request?
Running Minio in --compat mode is necessary in order to use it as object storage for Gitlab.

@harshavardhana
