### ISSUE TITLE
Please add @rainest as a trusted collaborater

### ISSUE THREAD

**Issue by hbagdi** [helm/charts#20098]
Hi there,

I'm one of the maintainers of the kong chart. We are in process of moving the chart out of this repository to our own but for the time being, we need another collaborator to handle increased activity on the chart.

Could you please add @rainest as a read only collaborator? 

@shashiranjan84, the other maintainer of Kong chart, can also confirm this.

We have already added him to the OWNERS file of the chart.

Thanks,
Harry

**Comment by shashiranjan84** [comment]
+1

**Comment by scottrigby** [comment]
Just added @rainest as a read-only collaborator 👍

**Comment by hbagdi** [comment]
Thanks, Scott!
