### ISSUE TITLE
Upgrade to Helm 2.0 stable

### ISSUE THREAD

**Issue by lachie83** [helm/charts#201]
@viglesiasce @prydonius Would we like to upgrade?

This may address our delete issues -- https://github.com/kubernetes/helm/releases/tag/v2.0.0-rc.2

**Comment by viglesiasce** [comment]
I just tested and neither of my issues were fixed. Still getting stuck releases and seeing the `Error: deletion completed with 1 error(s): object not found, skipping delete` error.

**Comment by lachie83** [comment]
Doh!

**Comment by lachie83** [comment]
How about stable?

**Comment by lachie83** [comment]
@viglesiasce is upgrading to stable. Closing
