### ISSUE TITLE
Is there any easy way to achieve PostgreSQL instance with available SSL enabled

### ISSUE THREAD

**Issue by muralirm** [helm/charts#20108]
Keywords: PostgreSQL - Linux - How to - Secure Connections (SSL/HTTPS)
Description:
am using the postgres sql by installing through helm chart from your site.
https://github.com/helm/charts/tree/master/stable/postgresql

I have one more micro service which is using postgres and failing to connect database.

time="2020-01-10T13:13:09Z" level=error msg="failed to connect database: pq: SSL is not enabled on the server" type=APPLOG

Could you please help us how we can enable SSL on the postgres

**Comment by javsalgar** [comment]
Hi.

At the moment, we do not have the chart with SSL options. I presume that the easiest way would be to add your own `initDbscript` that modifies the config file and generates the certificates.

https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml#L186

**Comment by jpvillalobos** [comment]
Hello, we do also need this functionality. Surprising it is not already there. Thanks.
