### ISSUE TITLE
Error installing ELK stack in v1.16

### ISSUE THREAD

**Issue by vjrobin** [helm/charts#20101]
Helm chart needs to be updated for v1.16 + K8s as some of the API support has been deprecated

**Comment by alekseydemidov** [comment]
The same issue
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]

Looks like "apps/v1beta1" must be moved to "apps/v1"

**Comment by vjrobin** [comment]
Well i tried it. In fact i downloaded entire ELK stack package, manually updated apiVersion as per "https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/" and it threw different error this time 

Error: release elk-new failed: Deployment.apps "elk-new-elasticsearch-client" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"elasticsearch", "component":"client", "release":"elk-new"}: `selector` does not match template `labels`]

**Comment by vjrobin** [comment]
@alekseydemidov - I have fixed apiVersions and spec definition to match K8s v1.16+. 

Use "https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/" as reference and update all resource kinds with appropriate versions

Update below files with same label name as that of template 

elastic-stack/charts/elasticsearch/templates/master-statefulset.yaml
elastic-stack/charts/elasticsearch/templates/data-statefulset.yaml
elastic-stack/charts/kibana/templates/deployment.yaml
elastic-stack/charts/elasticsearch/templates/client-deployment.yaml
