### ISSUE TITLE
[stable/rabbitmq] change prometheus.io/port annotation in values-production.yaml

### ISSUE THREAD

**Issue by jstudler** [helm/charts#20115]
**Describe the bug**
values-production.yaml has metrics.port set to 9419 (https://github.com/helm/charts/blob/master/stable/rabbitmq/values-production.yaml#L415) but annotation "prometheus.io/port" is set to 9090 (https://github.com/helm/charts/blob/master/stable/rabbitmq/values-production.yaml#L422)

**Version of Helm and Kubernetes**:
2.14.2 / 1.14.5

**Which chart**:
stable & bitnami rabbitmq

**What happened**:
Prometheus could not collect metrics

**What you expected to happen**:
Annotation "prometheus.io/port" is correct in values-production.yaml

**Comment by alemorcuq** [comment]
Thank you for reporting this, @jstudler.
