### ISSUE TITLE
[stable/postgresql] permission denied to create extension "pgcrypto" on complex scenarios

### ISSUE THREAD

**Issue by newtonjose** [helm/charts#20132]
**Describe the bug**
I need the use the complex scenarios, like a sub-chart, https://github.com/helm/charts/tree/master/stable/postgresql#use-of-global-variables. Deploy is working good, but  my other app need create a SQL EXTENSION.

I was passing **postgresqlPostgresPassword** (used when **postgresqlUsername** is not postgres), **postgresqlUsername** (PostgreSQL admin) and too **postgresqlPassword**.

**Version of Helm and Kubernetes**:
helm:v3
k8s:v1.15.2

**Which chart**:
stable/postgresql:v8.1.3

**What happened**:
Give permission error:
```
2020-01-14 21:27:46.244 GMT [380] STATEMENT:  CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA public
2020-01-14 21:28:16.384 GMT [421] ERROR:  permission denied to create extension "pgcrypto"
2020-01-14 21:28:16.384 GMT [421] HINT:  Must be superuser to create this extension.
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by newtonjose** [comment]
Any one can help?

**Comment by newtonjose** [comment]
Hi ALL, Any one can help?

**Comment by logicbomb421** [comment]
This is happening to me too. Upgraded to the most recent version of this chart Friday and suddenly I can't run my migrations which install several extensions. It looks like the 'admin' user created in the chart is never granted superuser permissions.
