### ISSUE TITLE
[stable/prometheus-operator] Missing kubelet relabeling config breaks new rules

### ISSUE THREAD

**Issue by seanson** [helm/charts#20157]
**Describe the bug**
In the new upstream rule updates with #19811 there is a new set of Prometheus rules synced from upstream with a new `metrics_path` parameter passed, such as
`kubelet_volume_stats_capacity_bytes{job="kubelet", metrics_path="/metrics"}`
This silently breaks some alerts and causes false positives with absent alerts. The upstream servicemonitor in kube-prometheus provides this label with their relabelling config:
https://github.com/coreos/kube-prometheus/blob/54c0fda307bde82b40f3d2de886d30df1196106b/manifests/prometheus-serviceMonitorKubelet.yaml#L64

**Version of Helm and Kubernetes**:
Helm 2.11, Kube 1.14

**Which chart**:
prometheus-operator

**What happened**:
Upgraded to new chart version 8.5.8, immediately got "kubeletdown" alert.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Update to new chart with kubelet rules enabled.

**Anything else we need to know**:
There is a temporary workaround by setting:
```
--set "kubelet.serviceMonitor.relabelings[0].sourceLabels[0]=__metrics_path__" \
--set "kubelet.serviceMonitor.relabelings[0].targetLabel=metrics_path" \
--set "kubelet.serviceMonitor.cAdvisorRelabelings[0].sourceLabels[0]=__metrics_path__" \
--set "kubelet.serviceMonitor.cAdvisorRelabelings[0].targetLabel=metrics_path" 
```

**Comment by kyschouv** [comment]
This is breaking us too (or what seems like the same issue at least) - all the the rules deployed have `metrics_path="/metrics/cadvisor"` in our cluster, which filters out all results.

**Comment by alexsn** [comment]
Some issue here, in addition cpu based dashboards are broken in grafana. Issue caused by 71d5b06c1547ed2bf7fa3df17873f1f3f27bf7ef, so reverting to 8.5.6 fixes the issue.
