### ISSUE TITLE
[stable/anchore-engine] envFrom anchore-engine configMap

### ISSUE THREAD

**Issue by masseybradley** [helm/charts#20174]
**Describe the bug**
The deployments set the environment from the `anchore-engine` `configMap`. The `configMap` contains the environment variables as well as the `config.yaml` resulting in the `config.yaml` being set in the environment:
![Screenshot from 2020-01-15 16-10-46](https://user-images.githubusercontent.com/8556522/72445217-aa0ded80-37b1-11ea-98e7-ff560d260ffd.png)

**Version of Helm and Kubernetes**:
`helm` version:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```
`kubectl` version:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.4-gke.22", GitCommit:"a6ba43f5a24ac29e631bb627c9b2a719c4e93638", GitTreeState:"clean", BuildDate:"2019-11-26T00:40:25Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
```
name: anchore-engine
version: 1.4.0
```

**What happened**:
Environment created from `config.yaml` (visible in `env`).

**What you expected to happen**:
`config.yaml` not in the containers environment.

**How to reproduce it** (as minimally and precisely as possible):
`helm install --name anchore-engine --namespace anchore-engine stable/anchore-engine`

**Anything else we need to know**:
Def. not a blocking issue. I [split the environment variable templates into a new `configMap`](https://github.com/masseybradley/charts/commit/3b0f8fd32c029927592e72a0dddb728a722dcdae)
 and using the `envFrom` with that `configMap` which I'd like to PR.

**Comment by masseybradley** [comment]
@zhill would be something of interest? (e.g. got a few things I'd like to do with the ae charts).

**Comment by zhill** [comment]
Thanks @masseybradley, we'll take a look

**Comment by zhill** [comment]
@Btodhunter why is the config in the env to start with? I don't see a reason it needs to be there explicitly? DB creds can be set via secrets and the config yaml is already mounted as a volume.

**Comment by masseybradley** [comment]
@zhill the config.yaml is mounted from the configMap, the “problem” is that the same configMap is used to set the env.

**Comment by masseybradley** [comment]
Oops, fat fingers (on my phone). I can take another stab at it, can move the credentials to secrets, set the env using the secrets and add a helper to generate random string credentials if they are nothing is set during the install.

**Comment by zhill** [comment]
> @zhill the config.yaml is mounted from the configMap, the “problem” is that the same configMap is used to set the env.

Yes, and I can't recall why it was done that way, hence question to @Btodhunter to see if he recalls why that was done.

**Comment by Btodhunter** [comment]
@zhill  I can't recall a specific reason it was done that way either. @masseybradley the fix in your fork looks like a great solution!

**Comment by masseybradley** [comment]
@Btodhunter thanks for the feedback. Note: I removed changes related to the enterprise deployment prior to creating the PR (I don't have a license at the moment, I can't test the changes and would rather not break the deployment for people with a valid subscription).
