### ISSUE TITLE
[stable/redis-ha] Connection closed by server when using password and HAProxy

### ISSUE THREAD

**Issue by EdisonTantra** [helm/charts#20186]
**Describe the bug**
I got this error when deploy stable/redis-ha using HAProxy and auth.
`Error while reading from socket: ('Connection
closed by server.',)`

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

**Which chart**:
redis-ha

**What happened**:
I want to expose redis with loadbalancer and auth. So, another service can push log to this redis. So, I create with this command.

`helm install \
  --set replicas=2 \
  --set haproxy.enabled=true \
  --set auth=true \
  --set redisPassword="verygoodpassword1234567890:@.#" \
  --set redis.port=9376 \
  --set haproxy.service.type="LoadBalancer" \
  --name redis-logs \
    stable/redis-ha`

All the services & pods are up with ok condition. But, I try to send log with rpush to the IP. But, I got this error.

`redis.exceptions.ConnectionError: Error while reading from socket: ('Connection
closed by server.',)`

I using this python script.

`import redis
host = setting.REDIS_HOST
json_data ='{}'
port = 9376
password = 'verygoodpassword1234567890:@.#'
con = redis.Redis(
	host=host,
	port=port,
	password=password,
)
con.rpush(settings.REDIS_LOG_KEY, json_data)`

with telnet.
`Trying 35.2xx.xxx.xxx...
Connected to xxx.xxx.xxx.xxx.bc.googleusercontent.com.
Escape character is '^]'.
Connection closed by foreign host.`

**What you expected to happen**:
I expect I can rpush the log data to redis

**How to reproduce it** (as minimally and precisely as possible):
create redis-ha with HAProxy and auth

**Anything else we need to know**:
When I take out auth and redisPassword like this.

`helm install \
  --set replicas=2 \
  --set haproxy.enabled=true \
  --set redis.port=9376 \
  --set haproxy.service.type="LoadBalancer" \
  --name redis-logs \
    stable/redis-ha`

it's working. Could you help me with this ? 
Thank you.

**Comment by DandyDeveloper** [comment]
@EdisonTantra That's a strange one, I'll investigate further. May take a couple of days due to my schedule.

**Comment by dvianello** [comment]
Seeing a similar issue - @DandyDeveloper, did you manage to get to the cause of it?

**Comment by DandyDeveloper** [comment]
@dvianello Sorry, I haven't had any opportunity to investigate. It's still on my radar just super low priority.

**Comment by dvianello** [comment]
@DandyDeveloper, fair enough - I'd be happy to do some digging on this one, I'm just clueless on how the whole thing is wired up, so any pointer to possible places where to look for issues are welcome!

**Comment by alexmsu** [comment]
Seeing the same issue +1

**Comment by DandyDeveloper** [comment]
Not stale.

**Comment by Mokto** [comment]
In my case it's connecting, but every ~30 seconds, I'm logged out and reconnected automatically. Is that what you're talking about ?

Thanks.

**Comment by alexmsu** [comment]
I also got this error randomly

**Comment by dvianello** [comment]
Not stale :-)

**Comment by dvianello** [comment]
Not stale.

**Comment by cjemison** [comment]
i'm seeing the same.

**Comment by dvianello** [comment]
Not stale.

**Comment by DandyDeveloper** [comment]
@alexmsu @dvianello Can one of you port it to the new official chart please? https://github.com/DandyDeveloper/charts/

**Comment by alexmsu** [comment]
I'm not seeing this issue any more now. It could be a k8s network issue.
