### ISSUE TITLE
stable/spinnaker

### ISSUE THREAD

**Issue by ahmedsmhs** [helm/charts#20191]
**Describe the bug**
Issue with installing spinnaker through helm on minikube

**Version of Helm and Kubernetes**:
Kubernetes:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

Helm:
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

**Which chart**:
stable/spinnaker

**What happened**:
helm install stable/spinnaker --debug
[debug] Created tunnel using local port: '45885'

[debug] SERVER: "127.0.0.1:45885"

[debug] Original chart version: ""
[debug] Fetched stable/spinnaker to /root/.helm/cache/archive/spinnaker-1.23.0.tgz

[debug] CHART PATH: /root/.helm/cache/archive/spinnaker-1.23.0.tgz

Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]

**What you expected to happen**:
Spinnaker to be deployed successfully

**How to reproduce it** (as minimally and precisely as possible):
Set up minikube (minikube version: v1.6.2)
Install helm 2.14.0 
Try running spinnaker from stable chart

**Anything else we need to know**:

**Comment by zdevi** [comment]
Any news on this? This is preventing us from installing spinnaker on latest kubectl versions. Same bug has been fix very quick for certmanager and others.
