### ISSUE TITLE
[stable/influxdb] Missing headless service configuration.

### ISSUE THREAD

**Issue by hydra-bu** [helm/charts#20204]
**Describe the bug**

> https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations
>> StatefulSets currently require a Headless Service to be responsible for the network identity of the Pods. You are responsible for creating this Service.

**Version of Helm and Kubernetes**:

**Which chart**:
stable/influxdb

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by Aisuko** [comment]
keep
