### ISSUE TITLE
[stable/external-dns] add aws-evaluate-target-health flag to chart

### ISSUE THREAD

**Issue by javamonkey79** [helm/charts#20217]
**Is your feature request related to a problem? Please describe.**
Yes. Not having this flag causes route53 entries to intermittently fail, requiring manual modifications to the entries.

**Describe the solution you'd like**
Add the flag for aws-evaluate-target-health to the chart. Seen [https://github.com/kubernetes-sigs/external-dns/pull/628](here).

**Describe alternatives you've considered**
The only alternative right now, is manual modification.

**Comment by juan131** [comment]
Hi @javamonkey79 

Thanks so much for the suggestion!! I agree with you and we should support this flag by default (at this moment the only alternative you have is using the `extraArgs` parameter that allows you adding custom flags)

Please feel free to create a PR adding support for this flag and I'll be glad to review it.

**Comment by javamonkey79** [comment]
Ok, done https://github.com/helm/charts/pull/20254

**Comment by juan131** [comment]
Great @javamonkey79 !! The team will take a look to the PR

**Comment by juan131** [comment]
Hi @javamonkey79 

You PR was accepted and merged. Should we consider this issue solved? Please feel free to close the PR if so

**Comment by javamonkey79** [comment]
@juan131 yes, this is now resolved. Thanks for your help and support.

**Comment by javamonkey79** [comment]
Unfortunately when testing this out today, I found it is buggy :(

I've got it fixed local, I'll put up a pr

**Comment by javamonkey79** [comment]
@juan131 please see my new PR:

https://github.com/helm/charts/pull/20435

I've tested it with my cluster with:
* `.Values.aws.evaluateTargetHealth` not set - does not set the flag (e.g. backwards compatible)
* `.Values.aws.evaluateTargetHealth` set to true - does not set the `no-aws-evaluate-target-health` flag
* `.Values.aws.evaluateTargetHealth` set to false - sets the correct flag `no-aws-evaluate-target-health`

**Comment by javamonkey79** [comment]
Previous PR closed, new one here https://github.com/helm/charts/pull/20448

**Comment by juan131** [comment]
I just saw these comments @javamonkey79 

Your PR https://github.com/helm/charts/pull/20448 was merged so I guess we can considered this issue solved.
