### ISSUE TITLE
[stable/mysql] "development-xyz-mysql" is invalid: spec.clusterIP: Invalid value: ""

### ISSUE THREAD

**Issue by saikatharryc** [helm/charts#20244]
I'm using stable/mysql as one of my dependency,
hence, while doing `helm upgrade *....*`
got an error:
```
Error: UPGRADE FAILED: failed to replace object: Service "development-xyz-mysql" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```
**Helm version: 3.0.1**

**Comment by yelhouti** [comment]
Facing the same issue, why is this closed please? @saikatharryc

**Comment by saikatharryc** [comment]
@yelhouti no action taken on this so I closed this.
even you can check this PR (closed): https://github.com/helm/charts/pull/20378
and here is StackOverflow question: https://stackoverflow.com/questions/60426241/error-upgrade-failed-failed-to-replace-object-service-api-is-invalid-spec
if you use `helm upgrade` without `--force` it supposes to work.
mostly it's because of helm3 I believe.

**Comment by yelhouti** [comment]
In my case not trying to change anything, it is exactly the same chart (as a requirement), I'm indeed using force, and I am not facing this issue with any other chart.

**Comment by saikatharryc** [comment]
@yelhouti  exactly same concern I had, 
even I have no idea, it does work magically when using without force.

**Comment by yelhouti** [comment]
@saikatharryc well sadly --force is in my CI and I can't just turn it off + it is needed for other yaml files and cam't be deactivated just for mysql :s
IMO this still should be investigated/fixed by maintainers of the mysql chart

**Comment by saikatharryc** [comment]
can you look into this PR: #20378 , I'm really not sure if it can resolve this issue, I just raised it by looking at how Nginx chart has resolved.

**Comment by yelhouti** [comment]
I really doubt it, why would it fix this?

**Comment by saikatharryc** [comment]
true, but for my old cluster, it did.  not sure whats causing the issue.

**Comment by yelhouti** [comment]
your old cluster must have an old version of kubernetes (that is what is this PR is for...)
