### ISSUE TITLE
[stable/jenkins] Support multiple ingress host names

### ISSUE THREAD

**Issue by holmesb** [helm/charts#20250]
Jenkins master's ingress template only allows a single host.  The use case for needing multiple: it is the [recommended](https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy) method to securely unrestrict Content Security Policy ("set up a second domain pointing to the same Jenkins instance").

Ingress that supports multiple hosts is the default for new helm charts.  Hopefully this can be added without breaking everyone who currently uses "ingress.hostName", not "ingress.hosts".  I expect the former will have to be deprecated and the template will use its value as the default in ingress.hosts[0].

**Comment by mmiranda** [comment]
we have the same scenario to use multiple hosts: Content Security Policy setting up a Resource root URL which is used to serve static files
