### ISSUE TITLE
Istio Service Monitor

### ISSUE THREAD

**Issue by antonyaugustus** [helm/charts#20268]
Hi,

I am looking to scrape "istio" metrics into existing prometheus operator both running on separate namespaces. I am looking for some service monitor charts/ patterns if anyone have been on this path.

Thanks
AA

**Comment by k911** [comment]
@antonyaugustus 

This might help you
https://github.com/istio/installer/blob/master/istio-telemetry/prometheus-operator/templates/servicemonitors.yaml

**Comment by antonyaugustus** [comment]
@k911

just took one of the servicemonitor and seasoned to taste. To my knowledge the servicemonitor should be enough to start collecting metrics but I don't see any from mixer component.

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-mesh-monitor
  namespace: monitoring
  labels:
    monitoring: istio-mesh
    release: prometheus-operator
spec:
  selector:
    matchExpressions:
      - {key: istio, operator: In, values: [mixer]}
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
  - port: prometheus
    interval: "30"

**Comment by antonyaugustus** [comment]
@k911

just took one of the servicemonitor and seasoned to taste. To my knowledge the servicemonitor should be enough to start collecting metrics but I don't see any from mixer component.

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-mesh-monitor
  namespace: monitoring
  labels:
    monitoring: istio-mesh
    release: prometheus-operator
spec:
  selector:
    matchExpressions:
      - {key: istio, operator: In, values: [mixer]}
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
  - port: prometheus
    interval: "30"
