### ISSUE TITLE
[stable/postgresql] service.annotations for internal LB azure

### ISSUE THREAD

**Issue by ljeromets** [helm/charts#20274]
**Describe the bug**
Unable to write the service.annotations value with helm command line.

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}

**Which chart**:
stable/postgresql

**What happened**:
The error below:
```
##[error]Error: UPGRADE FAILED: v1.Service.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|nternal":true},"crea|..., bigger context ...|beta.kubernetes.io/azure-load-balancer-internal":true},"creationTimestamp":"2020-01-21T16:07:23Z","l|...
```
**What you expected to happen**:
I am expect than it works.

**How to reproduce it** (as minimally and precisely as possible):
Run the command:
``helm upgrade --namespace postgresql-ci --install --set service.type=LoadBalancer,metrics.enabled=true,postgresqlDatabase=BDD,service.loadBalancerIP=10.10.10.10,service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"=true --wait --version 8.1.4 postgresql-release stable/postgresql ``

Thank in advance for your help guys.

**Comment by sameersbn** [comment]
@ljeromets Specifying annotations on the command line can get very tricky and more often than not straight up does not work. You will find a lot of users reporting issue while making `helm` to correct interpret the annotations specified on the command line. Instead of using the command line please consider passing the annotations via the `values.yaml` file.

Having said that can you try replacing `--set service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"=true` with `--set service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"='"true"' \` (source: https://stackoverflow.com/questions/54445011/pass-annotation-to)

**Comment by ljeromets** [comment]
Hello, @sameersbn thank for the reply.
The command line is running successfully now but it create the annotations below which doesn't work:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: '''true'''
  creationTimestamp: "2020-01-21T16:07:23Z"
```
 The 3 quotes breaks the internal-lb annotation and generates the error in azure side:
```
  Type     Reason                      Age                    From                Message
  ----     ------                      ----                   ----                -------
  Warning  CreatingLoadBalancerFailed  8m12s (x12 over 38m)   service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service ci-postgresql: user supplied IP Address xxxxxx was not found in resource group xxxxxxxxxx
```
I succeed to make it work by editing the svc like below:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```

Finaly I will do values.yaml.

**Comment by alemorcuq** [comment]
Let us know if you have any issues with the `values.yaml`, @ljeromets.

**Comment by ljeromets** [comment]
Hello,

I have no issue with the values.yaml, thank for your help.
