### ISSUE TITLE
unable to use tls.enabled=true, node start failed

### ISSUE THREAD

**Issue by pasumarthivijaykumar** [helm/charts#20283]
can you please let me know how to access **tls.enabled**, i did use as below mentioned

PS C:\Users\vpasumar> helm install openldaptest stable/openldap --set configPassword=dconfig --set adminPassword=dmanager --set replicaCount=2 --set env.LDAP_BACKEND=mdb **--set tls.enabled=true**
Error: Deployment.apps "openldaptest" is invalid: [spec.template.spec.volumes[0].secret.secretName: Required value, spec.template.spec.initContainers[0].volumeM**ounts[0].name: Not found: "tls"]**
PS C:\Users\vpasumar> helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS  CHART           APP VERSION
openldaptest    default         1               2020-01-22 12:15:22.7325835 +0530 IST   failed  openldap-1.2.3  2.4.48
PS C:\Users\vpasumar> helm uninstall openldaptest
release "openldaptest" uninstalled
PS C:\Users\vpasumar> helm install openldaptest stable/openldap --set configPassword=dconfig --set adminPassword=dmanager --set replicaCount=2 --set env.LDAP_BACKEND=mdb **--set tls.enabled="true"**
Error: Deployment.apps "openldaptest" is invalid: [spec.template.spec.volumes[0].secret.secretName: Required value, spec.template.spec.initContainers[0].volumeMounts[0**].name: Not found: "tls"]**
PS C:\Users\vpasumar> helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS  CHART           APP VERSION
openldaptest    default         1               2020-01-22 12:15:37.7971259 +0530 IST   failed  openldap-1.2.3  2.4.48

**Comment by laxmanpradhan** [comment]
in order to enable tls, you have to have a tls certificate saved as a kubernetes secret in the same namespace that you are deploying openLDAP. Once you have created the certificate, you have to specify it using '--set tls.secret=<NAME-OF-SECRET>'
