### ISSUE TITLE
[stable/rabbitmq] fails with helm 3 when replicas are configured

### ISSUE THREAD

**Issue by schmid-hanspeter** [helm/charts#20281]
**Describe the bug**
With helm version 3.0.2:
````helm install test  stable/rabbitmq --set replicas=1```` 
fails with the error 
````Error: template: rabbitmq/templates/statefulset.yaml:170:20: executing "rabbitmq/templates/statefulset.yaml" at <gt .Values.replicas 1.0>: error calling gt: incompatible types for comparison````

Note: The same command works with helm 2.

**Version of Helm and Kubernetes**:
helm 3.0.2

**Which chart**:
stable/rabbitmq

**What happened**:
The installation command fails

**What you expected to happen**:
The installation command runs

**How to reproduce it** (as minimally and precisely as possible):
````helm install test  stable/rabbitmq --set replicas=1````

**Anything else we need to know**:

**Comment by sameersbn** [comment]
@towerworks thanks for reporting the issue. A fix for it has been implemented in https://github.com/helm/charts/pull/20282 and should be landing soon.

**Comment by towerworks** [comment]
@sameersbn Thanks for the quick fix! Much appreciated.
