### ISSUE TITLE
Issue with spinnaker installation

### ISSUE THREAD

**Issue by gsund89** [helm/charts#20284]
Have been trying to intsall Spinnaker using Windows CMD. Facing two issues now.

1. Getting error "failed to download spinnaker". Ran "helm repo update" as suggested. Same error. Made sure that "stable" was added to repo.

2. Sometimes installation succeeds. But some of the pods are still "pending". Hence unable to perform port forwarding for Spinnaker dashboard.
![error](https://user-images.githubusercontent.com/24426663/72874436-04f69600-3d18-11ea-85d0-d7f894e1d374.png)

**Comment by josro** [comment]
inactivity
