### ISSUE TITLE
[stable/nextcloud] Use existing secrets for passwords

### ISSUE THREAD

**Issue by rustymunkey** [helm/charts#20292]
We are keeping our Kubernetes deployment files, like the ones from Nextcloud, inside a git repository and sync them with to our Kubernetes cluster.

We try to keep our repository free of plaintext passwords and to achieve this we use the [sealed-secrets](https://github.com/bitnami-labs/sealed-secrets) tool. This allows us to store the encrypted secrets inside the git repository and the sealed-secrets-controller creates the unencrypted secrets inside the cluster.

However, this approach is not working for the nextcloud chart, as there is currently no way to specify already existing secrets, for example for the database password.

**Describe the solution you'd like**

It would be great to have an additional option in the chart, like:

```
externalDatabase.existingSecret   
externalDatabase.userKey
externalDatabase.passwordKey
```

The rendering of the db-secret template should then only be done, if the `externalDatabase.existingSecret` value is *not* specified.

This way it would be possible to use an already existing secret and specify the values inside it.

**Describe alternatives you've considered**

Our current approach for deploying nextcloud is: extracting the chart and have a kustomization.yaml that does not include the templates for secrets and db-secret. These two are then supplied by sealed-secret.

**Comment by Jonher937** [comment]
@rustymunkey how did you end up solving this?
I'm in the same position right now and would like to not clone and modify the chart just to use it with [Zalandos Postgres operator](https://github.com/zalando/postgres-operator)

Making a PR would probably be the right to do at this point unless you know of a good workaround.
Thanks
