### ISSUE TITLE
 stable/traefik- How to change default configuration of traefik installed through helm

### ISSUE THREAD

**Issue by mpsingh10** [helm/charts#20290]
We have installed traefik from stable helm chart using the below command:

helm install --name traefik --set serviceType=LoadBalancer,rbac.enabled=true,loadBalancerIP="X.X.X.X",version=1.85.0,dashboard.enabled=true stable/traefik

To optimize the performance of the traefik, we now want to set the below parameter in the config file:
MaxIdleConnsPerHost = 100000

We see a default config map has been created with the helo deployment named -traefik. If we go and directly edit this configmap and add the parameter, would that change the configuration or do we need to perform some other steps?

 We have already made the change following above step but we are still not seeing any improvement in the performance.

apiVersion: v1
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "info"
    MaxIdleConnsPerHost = 100000
    defaultEntryPoints = ["http", "httpn"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.httpn]
      address = ":8880"
      compress = true
      [entryPoints.traefik]
      address = ":8080"
    [ping]
    entryPoint = "http"
    [kubernetes]
    [traefikLog]
      format = "json"
    [api]
      entryPoint = "traefik"
      dashboard = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-21T07:22:07Z"
  labels:
    app: traefik
    chart: traefik-1.85.1
    heritage: Tiller
    release: traefik
  name: traefik
  namespace: default
  resourceVersion: "7809021"
  selfLink: /api/v1/namespaces/default/configmaps/traefik
  uid: baf84d40-3c1e-11ea-9ea6-760d9b3944f0

**Version of Helm and Kubernetes**:
helm - v2.14.3
kubernetes - 1.14.8

**Which chart**
stable/traefik

**Comment by ManmohitSingh10** [comment]
Team - Any inputs on this?
