### ISSUE TITLE
Sidecar reload URL in Jenkins Helm Chart is not configured correctly if jenkinsUriPrefix is specified

### ISSUE THREAD

**Issue by drspockbr** [helm/charts#20305]
Sidecar auto reload stops to work if `jenkinsUriPrefix` is specified in values.yaml file. So that the sidecar reload URL is fixed without that URI.
The following errors are reported in the jenkins-sc-config pod:
```
File in configmap jcasc-default-config.yaml ADDED
POST request sent to http://localhost:8080/reload-configuration-as-code/?casc-reload-token=acme-provisioner-557895846f-6hrjl. Response: 404 Not Found
Working on configmap sfp-provisioner/acme-provisioner
Working on configmap sfp-provisioner/acme-provisioner-jenkins-config-credentials-config
configmap with label found
File in configmap credentials-config.yaml ADDED
POST request sent to http://localhost:8080/reload-configuration-as-code/?casc-reload-token=acme-provisioner-557895846f-6hrjl. Response: 404 Not Found
```
REQ_URL has value `http://localhost:8080/reload-configuration-as-code/?casc-reload-token=$(POD_NAME)` defined in `jenkins-master-deployment.yaml`. It could be `http://localhost:8080{{ default "" .Values.master.jenkinsUriPrefix }}/reload-configuration-as-code/?casc-reload-token=$(POD_NAME)`. Otherwise, response 404 errors are reported when trying to reload the configuration

**Comment by ls-julien-deruere** [comment]
For me, even with jenkinsUriPrefix not set, the sidecar doesn't start anymore!
