### ISSUE TITLE
[stable/external-dns] Route 53 entries are not being created

### ISSUE THREAD

**Issue by kartik-moolya** [helm/charts#20313]
**Describe the bug**
external-dns does not create Route53 records in AWS.

**Version of Helm and Kubernetes**:
Client: v2.13.1+g618447c
Server: v2.13.1+g618447c
K8s version: 1.13

**Which chart**:
stable/external-dns

**What happened**:
i use kiam to allow my k8s resource to talk to AWS which works fine, I have an nginx ingress controller which has an ELB attached to it ( **internal ELB, and not internet-facing** )
When I deploy this helm chart (values below) i don't see it creating the AWS route 53 records

**What you expected to happen**:
It should have created the route53 entries

**How to reproduce it** (as minimally and precisely as possible):
just create any ingress resource and wait for the resource to be created

**Anything else we need to know**:

hosted zone is **Private**
ELB is **internal**, and services are exposed when the route53 entries are created manually
Also please correct me if I havent used the variables in `values.yaml` properly

**values.yaml**

```sources:
- ingress

provider: aws
aws:
  preferCNAME: "true"
  zoneType: "private"
domainFilters:
  - 'int.xxx.xxxxvices.com'
zoneIdFilters:
  - 'Z1XXXXXXXXMT'
dryRun: false
interval: "1m"
logLevel: panic
logFormat: text
policy: sync
registry: "txt"
replicas: 2
podAnnotations:
  iam.amazonaws.com/role: dev-eks-external-dns-role
service:
  type: ClusterIP
  port: 7979
  annotations: {}
resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    memory: 50Mi
    cpu: 10m

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    selector:
      release: prom 
```

**external-dns pod logs**

$ kubectl logs -n utilities external-dns-597976f4b9-q65vn

```time="2020-01-22T11:52:32Z" level=info msg="config: {Master: KubeConfig: RequestTimeout:30s IstioIngressGatewayServices:[] ContourLoadBalancerService:heptio-contour/contour Sources:[ingress] Namespace: AnnotationFilter: FQDNTemplate: CombineFQDNAndAnnotation:false IgnoreHostnameAnnotation:false Compatibility: PublishInternal:false PublishHostIP:false ConnectorSourceServer:localhost:8080 Provider:aws GoogleProject: GoogleBatchChangeSize:1000 GoogleBatchChangeInterval:1s DomainFilter:[int.xxx.xxxxxxxxes.com] ExcludeDomains:[] ZoneIDFilter:[Z1XXXXXXXXMT] AlibabaCloudConfigFile:/etc/kubernetes/alibaba-cloud.json AlibabaCloudZoneType: AWSZoneType:private AWSZoneTagFilter:[] AWSAssumeRole: AWSBatchChangeSize:1000 AWSBatchChangeInterval:1s AWSEvaluateTargetHealth:true AWSAPIRetries:3 AWSPreferCNAME:true AzureConfigFile:/etc/kubernetes/azure.json AzureResourceGroup: AzureSubscriptionID: AzureUserAssignedIdentityClientID: CloudflareProxied:false CloudflareZonesPerPage:50 CoreDNSPrefix:/skydns/ RcodezeroTXTEncrypt:false InfobloxGridHost: InfobloxWapiPort:443 InfobloxWapiUsername:admin InfobloxWapiPassword: InfobloxWapiVersion:2.3.1 InfobloxSSLVerify:true InfobloxView: InfobloxMaxResults:0 DynCustomerName: DynUsername: DynPassword: DynMinTTLSeconds:0 OCIConfigFile:/etc/kubernetes/oci.yaml InMemoryZones:[] PDNSServer:http://localhost:8081 PDNSAPIKey: PDNSTLSEnabled:false TLSCA: TLSClientCert: TLSClientCertKey: Policy:sync Registry:txt TXTOwnerID:default TXTPrefix: Interval:1m0s Once:false DryRun:false LogFormat:text MetricsAddress::7979 LogLevel:panic TXTCacheInterval:0s ExoscaleEndpoint:https://api.exoscale.ch/dns ExoscaleAPIKey: ExoscaleAPISecret: CRDSourceAPIVersion:externaldns.k8s.io/v1alpha1 CRDSourceKind:DNSEndpoint ServiceTypeFilter:[] CFAPIEndpoint: CFUsername: CFPassword: RFC2136Host: RFC2136Port:0 RFC2136Zone: RFC2136Insecure:false RFC2136TSIGKeyName: RFC2136TSIGSecret: RFC2136TSIGSecretAlg: RFC2136TAXFR:false NS1Endpoint: NS1IgnoreSSL:false TransIPAccountName: TransIPPrivateKeyFile:}" ```

let me know if you need anything else

**Comment by juan131** [comment]
Hi @kartik-tavisca 

Did you follow the instructions below to setup the hosted zone on Route 53?

- https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md#set-up-a-hosted-zone

Could you share the output of running the command below?

```bash
$ kubectl get deploy -n utilities external-dns -o yaml
```

Could you also please format the logs when pasting them? They're pretty hard to read when they're not formatted.
