### ISSUE TITLE
[stable/influxdb] Static NodePort 

### ISSUE THREAD

**Issue by veerappans** [helm/charts#20365]
I changed the service to NodePort, as I could not access it with ClusterIP. But everytime I restart the service, its on a new port. Even when I hard code the port number on values.yaml file it still runs on a random port and I have to keep changing the code everytime to run on the new port. How can I make it stay on port defined in values.yaml (and referred in service.yaml).

Please let me know what I am missing.

Thank
Veera

**Comment by naseemkullah** [comment]
Hi @veerappans , thanks for raising this!

Is this still required? I can look into implementing this, would this be only for the `api` port? Other ports include rpc, collectd, opentsdb, graphite, etc.

**Comment by veerappans** [comment]
Yes please. This will help. Just API port is good. Others will be internal. So its okay.Trying avoid code change with each deployment.
