### ISSUE TITLE
[stable/traefik] No placeholder in Traefix chart "Values.yaml" file to apply 3rd party CA signed TLS certs

### ISSUE THREAD

**Issue by sunnygoel8** [helm/charts#20392]
**Is your feature request related to a problem? Please describe.**
I don't see any placeholder in Values.yaml file for Traefik chart to apply custom TLS cert

**Describe the solution you'd like**
Placeholder to specify the custom public cert, internediate CA and root cert.

**Comment by sunnygoel8** [comment]
Can anyone help us here ?

**Comment by dtomcej** [comment]
Certs should be managed by secret objects in your k8s cluster. Not sure what you are wanting to add?

**Comment by sunnygoel8** [comment]
@dtomcej , Thanks for your response. 

**My question is** - The way Traefik (acting as Ingress controller) lets you generate the self-signed certs for applications sitting behind traefik app on k8s cluster, I didn't see any placeholder to provide 3rd party CA signed custom certs in values.yaml file for Traefik Helm chart. And if that's not the purpose of traefik, then why does it provide capability to leverage self-signed cert ?

**Comment by krancour** [comment]
@sunnygoel8 the usual way of doing certs with ingress is that you make a secret that has the cert in it and then the ingress resource references that secret. Refer directly to k8s documentation for this. Traefik can auto-provision secrets using ACME (Let's Encrypt) for those who are _not_ using that usual approach.
