### ISSUE TITLE
[stable/external-dns] Allow empty cloudflare api key and api token

### ISSUE THREAD

**Issue by timcosta** [helm/charts#20394]
**Is your feature request related to a problem? Please describe.**
Currently when using the cloudflare provider it is required that you supply either an api key or an api token. This requires putting the token in your value.yaml file, which is inherently insecure. https://github.com/helm/charts/blob/master/stable/external-dns/templates/secret.yaml#L24

**Describe the solution you'd like**
According to https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md#creating-cloudflare-credentials it is possible to supply the token via an env var called `CF_API_TOKEN`, however the above required values.yaml value makes this impossible to do because providing a fake one create the secret with bad data, and you then cant create a secret using something like `external-secrets` with the correct token.

**Comment by juan131** [comment]
Hi @timcosta 

Please correct me if I'm wrong but you're requesting to create your own secrets (with your credentials) so you can later user a parameter (something like `cloudflare.existingSecret`) where you indicate the secret that should be used to retrieve the apiKey/apiToken. Am I right?

**Comment by timcosta** [comment]
Yes, that is correct. Right now there no way to use this module without it creating the secret, which blocks something like godaddy/external-secrets from creating a secret.

Tim Costa

**Comment by juan131** [comment]
Hi @timcosta 

I just created a PR to address this request.

**Comment by timcosta** [comment]
@juan131 i super appreciate this, thank you!

**Comment by juan131** [comment]
You're welcome @timcosta 
Please do not hesitate to reach us for any other request you may have
