### ISSUE TITLE
[stable/grafana] Multiple SC Providers

### ISSUE THREAD

**Issue by lukipro** [helm/charts#20418]
**Is your feature request related to a problem? Please describe.**
I would like to be able to collect dashboard ConfigMaps from numerous namespaces and store them in dedicated folders in Grafana.

**Describe the solution you'd like**
I believe that one solution to it is to have multiple SCProvider configurations in the chart. Can we modify the chart to have more than one SCProvider configuration?

**Comment by zifter** [comment]
This feature is nice to have!
Is it possible to reopen?
