### ISSUE TITLE
[stable/cluster_autoscaler] error while installing chart with helm3 

### ISSUE THREAD

**Issue by amitsehgal** [helm/charts#20428]
**Describe the bug**
Trying to create autoscaler using helm chart for eks.

helm_release.cluster_autoscaler: Creating...

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

  on main.tf line 46, in resource "helm_release" "cluster_autoscaler":
  46: resource "helm_release" "cluster_autoscaler" {

**Version of Helm and Kubernetes**:
1.14

**Which chart**:

stable/cluster_autoscaler
**What happened**:

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

chart creation successful

**Anything else we need to know**:

 # helm_release.cluster_autoscaler will be created
  + resource "helm_release" "cluster_autoscaler" {
      + atomic                = false
      + chart                 = "cluster-autoscaler"
      + cleanup_on_fail       = true
      + dependency_update     = false
      + disable_crd_hooks     = false
      + disable_webhooks      = false
      + force_update          = false
      + id                    = (known after apply)
      + max_history           = 0
      + metadata              = (known after apply)
      + name                  = "cluster-autoscaler"
      + namespace             = "kube-system"
      + recreate_pods         = false
      + render_subchart_notes = true
      + replace               = false
      + repository            = "stable"
      + reset_values          = false
      + reuse_values          = false
      + skip_crds             = false
      + status                = "deployed"
      + timeout               = 300
      + verify                = false
      + version               = "6.3.0"
      + wait                  = true

      + set {
          + name  = "rbac.create"
          + value = "true"
        }
      + set {
          + name  = "serviceMonitor.enabled"
          + value = "true"
        }
    }

**Comment by amitsehgal** [comment]
fixed after prometheus operator is installed

**Comment by xposix** [comment]
You may like to close the ticket ;)
