### ISSUE TITLE
stable/mongodb: override namespace for mongo deployment

### ISSUE THREAD

**Issue by benjamin-wright** [helm/charts#20440]
It would be very useful if we could pass a namespace for deployment through to the mongodb chart as a value. This would enable umbrella charts to deploy multi-namespace applications in a declarative manner, i.e. without multiple helm charts or multiple calls to helm install/upgrade with different components enabled / disabled.

The proposed change would add `namespaceOverride` to `values.yaml`, which would default to nil. If supplied, all templates would be deployed into the provided namespace, except for the prometheus service monitor if its own override is also supplied. This would maintain backwards compatibility with the current approach, but would provide the option of changing the deployment namespace when necessary / beneficial.

**Comment by juan131** [comment]
Hi @benjamin-wright 

Thanks so much for opening this issue! I added some comments in the PR you created.

**Comment by benjamin-wright** [comment]
bump

**Comment by juan131** [comment]
Hi @benjamin-wright 

Given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), this Bitnami maintained Helm chart was deprecated and moved to [bitnami/charts](https://github.com/bitnami/charts/) some weeks ago. Please visit the [bitnami/charts](https://github.com/bitnami/charts/) GitHub repository to create Issues or PRs.

In this issue ([#20969](#20969)), we tried to explain more carefully the reasons and motivations behind this transition, please don't hesitate to add a comment in this issue if you have any question related to the migration itself.

**Comment by benjamin-wright** [comment]
Hi @juan131,

Ah, sorry, I either missed the deprecation notice on the mongo chart or hadn't noticed it go up in the mean time. Will transfer my suggestion across, thanks!
