### ISSUE TITLE
Creating a load balancer on wrong VPC

### ISSUE THREAD

**Issue by Yamini-TWG** [helm/charts#20458]
Hello Team, 

**Describe the bug** - 

When I am trying to apply this charts, its deploying all good but for some reason the load balancer it trying to create is falling under different subnet, we have a 3 VPC's anything related to cluster will fall under utility subnet and anything related to pod and services it will fall under different subnets which id default. 
For some reason helm charts are creating load-balancer in utility subnet , we are trying to understand how to deploy the service load balancer indifferent subnet by changing the values file. 

**Version of Helm and Kubernetes**:
helm version - v2.14.3
kubernetes version  - "v1.11.6

**Which chart**: teslink

**Comment by wilinger** [comment]
Not sure if related but when I specify the following in the values.yaml, I am not getting the loadBalancerIP for the service. It's just assigning first available IP from metalLB address pools but there's no way to configure static loadBalancerIP.

`service:
  name: registry
  type: LoadBalancer
  port: 5000
  loadBalancerIP: 10.10.30.235`

**Comment by Yamini-TWG** [comment]
Hey,

I am more about wondering, can I give the VPC-ID to bring upm the load balancer on, rather than giving a static IP I want to mention the VPC ID so that it brings up load balancer in that VPC.

Cheers

Yamini Kondapaturi | Development Ops Engineer | The Warehouse Group
Phone: +6494897000 Ext. 96703 | Mobile: +6421560943
PO Box 33470, Takapuna, Auckland, 0740, New Zealand
Email: Yamini.Kondapaturi@thewarehouse.co.nz <mailto:Yamini.Kondapaturi@thewarehouse.co.nz>
Web: www.twg.co.nz<http://www.twg.co.nz>

**Comment by yamu890** [comment]
#re-open
