### ISSUE TITLE
[stable/jenkins] Download plugins from custom location

### ISSUE THREAD

**Issue by codiophile** [helm/charts#20450]
**Is your feature request related to a problem? Please describe.**
When installing this helm chart on an air gapped Kubernetes cluster (i.e. no Internet), it fails to download the plugins from https://updates.jenkins.io/download/plugins/.

**Describe the solution you'd like**
The location from which the plugins are downloaded from should be configurable. I've checked `values.yaml` and I can't find anything like that.

**Describe alternatives you've considered**
We already have our own custom Helm chart for Jenkins. It works, but new versions of Jenkins and plugins often break our scripts, which is why we want to use the official one. We would be able to stay up to date with latest versions and we wouldn't have to maintain those scripts anymore.

**Additional context**
N/A

**Comment by codiophile** [comment]
I still need this to be able to use this helm chart in our environment. If there is no active maintainer of this helm chart here, maybe someone could tell me where to find one?

**Comment by torstenwalter** [comment]
@codiophile I am also using it in such an environment. I my case we use a custom Jenkins image which already contains all the plugins we need.

It should be possible to use custom update canter locations. It mainly depends on the image you use: https://github.com/jenkinsci/docker/blob/master/README.md#setting-update-centers

**Comment by codiophile** [comment]
Thank you, @torstenwalter! We have a custom Helm chart and image that is working. It commonly breaks for new versions of Jenkins and plugins, so I was hoping to use the official helm chart with the official image, so that we can more easily stay up to date.

Your input is definitely helpful, but it does require us to modify either the helm chart or the image, which is what we want to get away from. This is certainly a much smaller modification than the one we currently have, but if these options were exposed in `values.yaml`, we wouldn't need any modification and the upgrades would be very straight forward.

It would be fairly easy to set these environment variables in the deployment based on `values.yaml`. I could probably make the pull request myself, if I find the time, but it would be nice if I could get some feedback on this feature request, so that I know if it is likely to get merged.

**Comment by torstenwalter** [comment]
I think it's nice functionality to have and I would review that PR. Just mention me when creating it.

**Comment by techlunacy** [comment]
i added this change to the jenkins image that i think addresses part of your problem maybe?
https://github.com/jenkinsci/docker/pull/799
you can do this with the plugin.txt
plugin-id:1.0-version:true:https://internal.url/plugin/1.0-version/plugin.hpi
dont know whether this is helpful

**Comment by torstenwalter** [comment]
@techlunacy Thank you for the hint. That makes usage of self hosted plugins easy.

**Comment by fl-max** [comment]
I think what @codiophile was looking for was a global setting for all Plugin downloads. @techlunacy addition makes it possible to easily install one-off plugins though I think including the version/plugin name is redundant and can instead be inferred by first two params.

After looking over the install-plugins.sh and the chart, I believe this is already possible via:
```yaml
master:
  initContainerEnv:
    - name: JENKINS_UC_DOWNLOAD
      value: "https://example.com/plugins/downloads"
```

**Comment by fl-max** [comment]
Ok, can confirm that you can override the plugin Download URL. I'm using Nexus OSS so I created a new **raw** proxy repo with the _Name_ `jenkins-download` and _Remote Storage Location_ of `https://updates.jenkins-ci.org/download/`.

I then added the following to my values.yaml:
```yaml
master:
  initContainerEnv:
    - name: JENKINS_UC_DOWNLOAD
      value: "https://nexus.example.com/repository/jenkins-download" # NO TRAILING SLASH!
```

**NOTE:** This will force all plugin downloads through your custom endpoint. If you wanted to be able to use custom, "internal plugins", you could expand on the repo layout by making a group repo and then adding a local and proxy repo. Then just point `JENKINS_UC_DOWNLOAD` at your _group_ repo.

If I find some time, I'll open a PR to add these steps to the Docs. Better yet, add a `master.jenkinsUCDownloadUrl` value.

**Comment by codiophile** [comment]
I finally got around to trying this. Unfortunately there is an annoying issue. It seems like the following is used to download the plugins:

    curl --retry 3 --retry-delay 5 -sSL -f "${JENKINS_UC_DOWNLOAD}/plugins/${plugin[0]}/${plugin[1]}/${plugin[0]}.hpi" -o "$REF/${plugin[0]}.jpi"

There is no `/plugins/` in our URL. I'm not an admin of the Jenkins plugins repository, so I might have to set up a mirror of the mirror to make this work, or perhaps a proxy. It's nonetheless quite annoying that this is hardcoded.

**Comment by fl-max** [comment]
`/plugins` would just be a directory inside whatever repository you setup in Artifactory/Nexus.

**Comment by codiophile** [comment]
I suppose this issue can be closed, as it is possible to download plugins from custom location. Only question remaining is whether that should be documented in the README of theHelm chart or not, but I suppose you could argue either way.
