### ISSUE TITLE
[stable/jenkins] error: 'function "required" not defined'

### ISSUE THREAD

**Issue by trahloff** [helm/charts#2046]
**Is this a request for help?** Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?**:
Possible BUG REPORT

**Version of Helm and Kubernetes**:
K8S Client: 1.7.4
K8S Server: 1.7.0 (Minikube) & 1.5.4 (Deployed on Bluemix)
Helm: 2.1.3

**Which chart**:
stable/jenkins

**What happened**:
`helm install stable/jenkins --namespace jenkins` ended with the error: 
`Error: parse error in "jenkins/templates/rbac.yaml": template: jenkins/templates/rbac.yaml:3: function "required" not defined`

**What you expected to happen**:
I expected a clean install on the k8s cluster

**How to reproduce it**:
1. Install Minikube, kubectl and helm
2. `$ minikube start`
3. `$ helm init`
4. `$ helm install stable/jenkins --namespace jenkins`

**Comment by unguiculus** [comment]
Your Helm version is pretty dated. You'll have to update.
