### ISSUE TITLE
[stable/jenkins] new configurable parameter to change nodeUsageMode value

### ISSUE THREAD

**Issue by tomasz-zylka-fluke** [helm/charts#20472]
Currently, the default value of **nodeUsageMode** is set to '**NORMAL**'.
And we cannot change it whatsoever (at least I couldn't have found it for two hours ;) ) via configurable parameters passed to **helm command**, therefore one needs to remember to manually change that parameter in jenkins configuration site (kubernetes component).

This parameter is quite important one, as wrong value of it, can end up with accidental jobs execution on a wrong node - which might be really serious.

So this feature request is simple, I believe/hope, and would require to add new configuration parameter called e.g. **agent.nodeUsageMode** with default value **NORMAL**.

Thanks a lot, 
Cheers
Tomek

**Comment by pt-tomasz-zylka** [comment]
Hi, is anyone able to tell me whether this ticket could be implemented or at least whether this ticket is formally well created?
