### ISSUE TITLE
[stable/prometheus-operator] Grafana sidecar watcher fails to dynamically add new dashboards

### ISSUE THREAD

**Issue by amtux** [helm/charts#20476]
**Describe the bug**
Grafana sidecar watcher fails to automatically pick up new dashboards added via configmap.

**Version of Helm and Kubernetes**:
```
$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/prometheus-operator

**What happened**:
Adding a dashboard configmap in the following manner.
```
kubectl -n logmet create cm gd-pods-consolidated --from-file pods-consolidated.json
kubectl -n logmet label cm gd-pods-consolidated grafana_dashboard="1"
```
Configmap does not get picked up by sidecar. **However, manually running sidecar again does successfully pick up the dashboard**

**What you expected to happen**:
Expected dashboard to automatically show up in Grafana when a dashboard configmap is added.

**How to reproduce it** (as minimally and precisely as possible):
1. Install prometheus-operator with Grafana sidecar enabled: `helm install mon -n logmet stable/prometheus-operator`
2. Once Grafana is initialized, create a configmap for dashboard and label it appropriately.
```
kubectl -n logmet create cm gd-somedash --from-file some-dashboard.json
kubectl -n logmet label cm gd-somedash grafana_dashboard="1"
```
3. Validate in Grafana that the newly added dashboard still doesn't exist.
4. Tail sidecar logs `kubectl logs -f pod/mon-grafana-545d4f86df-xwq5s -n logmet -c grafana-sc-dashboard` and a log for the newly created configmap won't be there.
5. Run `kubectl -n logmet exec -it mon-grafana-545d4f86df-xwq5s python sidecar.py -c grafana-sc-dashboard` to manually run sidecar - and notice that the configmap that was added does get picked up -- and shows up as a dashboard in Grafana.

**Anything else we need to know**:
I also tried adding dashboard json as a configmap as described in [stable/grafana README](https://github.com/helm/charts/tree/0771fc7e4c3853c0b64e6b4a5ad7b4824d688db9/stable/grafana#sidecar-for-dashboards) and doing `kubectl apply -f` on it. Same result.

**Comment by janotav** [comment]
I'm facing similar/same issue. After deploy to multiple (identical) environments, there is usually a couple of them where the dashboard configmap update is not noticed by Grafana. Kubectl logs on the sidecar container shows no output at all when the configmap is modified, i.e. no "Working on configmap foo/bar" lines appear. When this happens it seems to affect all ConfigMap updates. It looks as if the watcher thread died somehow.

After deleting the grafana pod, when the new instance is up the dashboards are up-to-date which I believe rules out the possibility of broken dashboard definition causing this in the first place.
