### ISSUE TITLE
[stable/datadog] Ability set variable to set the tracePort

### ISSUE THREAD

**Issue by bkimbrough88** [helm/charts#20485]
**Is your feature request related to a problem? Please describe.**
I am not able to specify the port that the `tracePort` is setup on like I am able to do with the `dogStatsDPort`. My colleague @johnkost is trying to temporarily deploy a second DaemonSet in a cluster that already contains a DaemonSet for testing purposes. However he cannot setup the second DaemonSet while setting `hostPort` to true as the `tracePort` is currently hardcoded.

**Describe the solution you'd like**
I would like to be able to set a variable that will allow me to specify the port I want to use as the `tracePort`

**Comment by clamoriniere** [comment]
Hi @bkimbrough88,
Thank for opening this issue. We are currently working on a major `stable/datadog` chart upgrade #18182 that is solving your issue.
We should release soon this new version.
