### ISSUE TITLE
[stable/prometheus-operator] pre-upgrade hooks failed with prometheus-operator-admission: dial tcp 172.20.0.1:443: i/o timeout on EKS cluster

### ISSUE THREAD

**Issue by kovalyukm** [helm/charts#20480]
**Describe the bug**
helm upgrade exited with next error

client.go:450: [debug] Add/Modify event for aws-prometheus-operator-admission-create: ADDED
client.go:489: [debug] aws-prometheus-operator-admission-create: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
upgrade.go:280: [debug] warning: Upgrade "aws" failed: pre-upgrade hooks failed: timed out waiting for the condition
Error: UPGRADE FAILED: pre-upgrade hooks failed: timed out waiting for the condition
helm.go:76: [debug] pre-upgrade hooks failed: timed out waiting for the condition
UPGRADE FAILED

Pod prometheus-operator-admission-create-kw96g (create) is restarting with next errors

k logs aws-prometheus-operator-admission-create-b5r8g                                                                                              
{"err":"Get https://172.20.0.1:443/api/v1/namespaces/monitoring/secrets/aws-prometheus-operator-admission: dial tcp 172.20.0.1:443: i/o timeout","level":"fatal","msg":"error getting secret","source":"k8s/k8s.go:104","time":"2020-01-31T15:44:36Z"}

k get svc kubernetes -n default
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   172.20.0.1   <none>        443/TCP   204d

Issue appears after changing rules in additionalPrometheusRulesMap.
When prometheusOperator.admissionWebhooks.enabled=false - no errors with helm upgrade.

It is AWS EKS cluster with private access.
API server endpoint access:
Private access - Enabled
Public access - Disabled
Allowing all traffic between master-api ENIs and worker nodes does not help.

**Version of Helm and Kubernetes**:
helm version 
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Kubernetes version
1.14
Platform version
eks.6
kubernetes_build_info{,gitCommit="c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2",gitTreeState="clean",gitVersion="v1.14.9-eks-c0eccc",goVersion="go1.12.12",job="apiserver",major="1",minor="14+",namespace="default",platform="linux/amd64",service="kubernetes"}

**Which chart**:
stable/prometheus-operator

**What happened**:
There is some issue with accessibility between api-server and prometheus-operator-admission-create pod from job.batch/bit-prometheus-operator-admission-create in EKS Kubernetes cluster.

**How to reproduce it** (as minimally and precisely as possible):
Install prometheus-operator on EKS Kubernetes cluster with additionalPrometheusRulesMap than change/delete these rules and try to upgrade.

**Comment by kovalyukm** [comment]
Also when I updating rules in additionalPrometheusRulesMap nothing happens in prometheus. Rules are updated in prometheusrules resource, but there are no changes in config map prometheus-operator-prometheus-rulefiles-0
Please advise

**Comment by chaos-panda** [comment]
@kovalyukm I am running into the same issue only on AKS. Did you manage to solve it?

**Comment by kovalyukm** [comment]
> @kovalyukm I am running into the same issue only on AKS. Did you manage to solve it?

Seems updating to the latest version of chart somehow helps. I ends up with default values and commented out my:
#      admissionWebhooks:
#        enabled: false
