### ISSUE TITLE
[stable/redis] Support for istio

### ISSUE THREAD

**Issue by glentakahashi** [helm/charts#20481]
**Is your feature request related to a problem? Please describe.**
Right now the Egress rules if you set networkPolicy = true don't work for Istio.

**Describe the solution you'd like**
 I'm not 100% sure what the egress ports needed for istio are, but once I figure them out I can submit another PR. I'm also not sure if we would also maybe want to use a namespace selector for `kube-system` here? Or potentially even blanket allow egress to the `kube-system` egress

**Describe alternatives you've considered**

**Additional context**

**Comment by juan131** [comment]
Hi @glentakahashi 

I guess it could be related with Redis chart services not following the Istio specifications for port names on services.

Check for instance the changes we did on PostgreSQL to comply with [Istio requirements](https://istio.io/docs/ops/deployment/requirements/):

- https://github.com/helm/charts/pull/19249

**Comment by zeph** [comment]
I got it working with Istio https://github.com/istio/istio/issues/8374#issuecomment-586269097 , but... I miserably stumbled on the `cluster-announce-ip` issue:  **there is no way to let SENTINEL announce the `istio-ingressgateway`'s IPs** https://github.com/antirez/redis/issues/2527

even if you hack the redis configuration in a pod... you won't manage to get all the ingressgateways listed, as it is designed for only one IP at a time... so, the only chance would be to have a LB in front

**Comment by zeph** [comment]
p.s. might be that giving an IP/fqdn of a loadbalancer in the configuration, will cause sentinel's designed mechanisms of monitoring and fail over to go wild, @antirez?

**Comment by zeph** [comment]
for everyone else... SENTINEL, if asked about the instances... it won't answer with the IPs the client shall connect to from outside the cluster, but each POD's private IP... which would not be reachable from an application outside the cluster... the logic will fail

```
dst-knode04:26379> SENTINEL slaves mymaster
1)  1) "name"
    2) "172.31.113.123:6379"
    3) "ip"
    4) "172.31.113.123"
    5) "port"
    6) "6379"
``` 

thanks @szottE for guiding me through this ;)

**Comment by zeph** [comment]
@glentakahashi I'm not 100% (re-reading ur ticket) if I tackled your same problem, since you are talking of Egress, instead I have in inbound connectivity/logic issue of the application (redis/sentinel) itself

**Comment by zeph** [comment]
RTFM https://redis.io/topics/sentinel#sentinel-docker-nat-and-possible-issues

**Comment by juan131** [comment]
I would like to mention that this chart has been deprecated and moved to https://github.com/bitnami/charts/tree/master/bitnami/redis

Find more information at https://github.com/helm/charts/tree/master/stable/redis#this-helm-chart-is-deprecated
