### ISSUE TITLE
Meta: split charts out into individual repos

### ISSUE THREAD

**Issue by binoculars** [helm/charts#2048]
These would be much easier to manage if they were in their own repos. I see some limited value in being able to change things all at once, but a lot of that could be automated as well. The biggest issue is PRs tend to go stale, because once they're in stable, it's to update the charts without breaking things.

I'd recommend creating a github org that's something like `kubernetes-charts` and have the individual charts live in repos under that.

**Comment by kachkaev** [comment]
Hi @binoculars! Check out a discussion here: https://github.com/kubernetes/charts/issues/1714.
