### ISSUE TITLE
Chart for Magento 2, the PHP eCommerce framework.

### ISSUE THREAD

**Issue by andrewhowdencom** [helm/charts#205]
There's a few PHP applications in here (Joolma, Wordpress). Another reasonably popular one is Magento, or Magento 2.

Their CE edition could be packaged here.

I can create the package, but it'd be a couple of weeks -- I need to finish both kube-cert-manager, and hashicorp's vault.

Would be submitted to incubator. 

There's no Docker image for Magento 2.x currently; there's a series of issues that would need to be resolved specific to this application. Bitnami have previously created a Magento 1.x image, so I might try and co-ordinate a Magento 2.x image with them. 

Reference: https://github.com/bitnami/bitnami-docker-magento

Let me know!

**Comment by lachie83** [comment]
cc @prydonius

**Comment by prydonius** [comment]
Awesome @andrewhowdencom! Actually the Bitnami image is for 2.x and we have a Magento chart in the Bitnami repository: https://github.com/bitnami/charts/tree/master/incubator/magento.

Would love to work with you on improving that chart and submitting it here! I was working on it a little earlier, but I hit a roadblock with trying to use Magento's production mode by default as it takes a very long time to install.

**Comment by seanknox** [comment]
Thanks for noting this @andrewhowdencom. Feel free to put up a PR for any new charts that would would be useful for the Helm community at large.
