### ISSUE TITLE
[stable/rabbitmq-ha] Unable to upgrade chart - spec.clusterIP: Invalid value: "": field is immutable

### ISSUE THREAD

**Issue by xario** [helm/charts#20510]
**Describe the bug**
Since version 1.36.3 there is no longer a clusterIP set in the service.yaml. The change was introduced in https://github.com/helm/charts/pull/18503, which tried to resolve the issue of not being able to set the clusterIP to an empty string. However this also means that it is no longer possible to set the clusterIP to "None", and when upgrading existing deployments like described below and in this related issue: https://github.com/helm/charts/issues/19560.

**Version of Helm and Kubernetes**:
Helm: 2.16.0
K8S: 1.12.10

**Which chart**:
stable/rabbitmq-ha

**What happened**:
When upgrading from version 1.32.3 to the lastest version 1.38.2, I got the follow error:
`Error: Service "dev-rabbitmq-ha" is invalid: spec.clusterIP: Invalid value: "": field is immutable
`

**What you expected to happen**:
I expected the upgrade to complete without any problems.

**How to reproduce it** (as minimally and precisely as possible):
Install a version of the chart older than 1.36.3, and upgrade to the latest version, using the default values.

**Anything else we need to know**:
It seems like the original PR was a better solution: https://github.com/helm/charts/pull/18503/commits/3e09ab1abbd751de52a06171cc81f30d39add630, as it allows for overwriting clusterIP. 
It will require a change to the service.yaml template:
```
{{- with .Values.service.clusterIP }}
  clusterIP: {{ . | quote }}
{{- end }}
```
It will possibly require a major chart version update as it will prevent upgrading existing deployments, but this can be mitigated by updating your local config to include:
```
service:
  clusterIP: None
```
This could be included in a migration guide for the new major version.

**Comment by xario** [comment]
@steven-sheehy Can you take a look at this? Thanks.

**Comment by steven-sheehy** [comment]
You're right, that PR breaks services that are not type loadbalancer. Sorry, I should've caught that. I would accept a PR backing out that change.
