### ISSUE TITLE
How can I add my custom grafana dashboard?

### ISSUE THREAD

**Issue by vrathore18** [helm/charts#20515]
I am trying to add a new dashboard to the below helm chart
https://github.com/helm/charts/tree/master/stable/prometheus-operator

I am having all my dashboards in .json files. Could you please help me out I can I edit my values.yaml in such a way that everytime I install prometheus-operator I will have my dashboard imported.

P.S I know I have to create a configmap and there is some setting I need to modify in values.yaml. But could some please help me out the the best way to do this?

**Comment by jdomag** [comment]
Hi, 
You don't need to change value file - grafana will pick up automatically all the configmaps that are labeled "grafana_dashboard: 1".
See example below
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard: "1"
  name: grafana-dashboards-configmap
  namespace: monitoring
data:
  my-dashboard.json: |-
    {
      "annotations": {
        "list": [
.
. this is were your dashboard json goes
.  
   }
```
You can have single configmap per dashboard or keep all the dashboard in single configmap by defining multiple json files.

**Comment by geekq** [comment]
Here is the link to the "official" documentation explaining how watch-sidecar for dashboards work
https://github.com/helm/charts/blob/master/stable/grafana/README.md#sidecar-for-dashboards
All the parameters are described in the table above
https://github.com/helm/charts/blob/master/stable/grafana/README.md#configuration
