### ISSUE TITLE
[stable/cluster-autoscaler] lease RBAC settings missing

### ISSUE THREAD

**Issue by NeilW** [helm/charts#20514]
**Describe the bug**
RBAC settings to manipulate the leader lease are missing

**Version of Helm and Kubernetes**:
Helm: 3.03
K8s: 1.17.1

**Which chart**:

stable/cluster-autoscaler

**What happened**:

```
I0203 17:12:27.280579       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/cluster-autoscaler...
E0203 17:12:27.282181       1 leaderelection.go:331] error retrieving resource lock kube-system/cluster-autoscaler: leases.coordination.k8s.io "cluster-autoscaler" is forbidden: User "system:serviceaccount:kube-system:release-brightbox-cluster-autoscaler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
```

**Anything else we need to know**:

AWS example yaml at https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml

has

```
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create"]
  - apiGroups: ["coordination.k8s.io"]
    resourceNames: ["cluster-autoscaler"]
    resources: ["leases"]
    verbs: ["get", "update"]
```

in the ClusterRole rules list

**Comment by sc250024** [comment]
Having the same issue. A simple PR adding these to the chart could work?
