### ISSUE TITLE
[stable/superset] Request to be a trusted collaborator.

### ISSUE THREAD

**Issue by MarcusSorealheis** [helm/charts#20528]
**Is your feature request related to a problem? Please describe.**
I am requesting to be added as a trusted collaborator and chart maintainer for [stable/superset].

**Describe the solution you'd like**
I would like for you to be added to the trusted collaborators list and a maintainer for [stable/superset].

**Describe alternatives you've considered**
I've considered bugging others but this is an open source project, and mostly powered by volunteers or engineers volunteering some of their work time. 

I've considered keeping the improvements that I made in my deployment to myself, but in the end that did not make sense because an open source project is only as strong as its community is empowered. 

Neither of these options struck me as viable alternatives. 

**Additional context**
I have significant knowledge about the project, a passion for helping others, and can help to keep the chart on its fast pace so the community can enjoy it without pain. I have observed developers encountering challenges when seeking to upgrade to the latest versions of Superset because of issues with the chart. 

here are some of my contributions to Superset repo: a few contributions related to wrangling of data and starting the app in the ways you want. I have some more, like minor bugfixes for charts and things but less SRE related.
I bet you aren't using hive in Prod because it won't work: apache/incubator-superset@01689c3
Have lots of tables/data sources, list needs to be refreshable: apache/incubator-superset@56eac68
apache/incubator-superset@f486f43: doc entry for starting an app with modified FAB
Keeping deps docs updated so that production devops teams have good info: apache/incubator-superset@b1269c3
Improving security for production users: apache/incubator-superset@4c35de1
please on't blame devops that you cannot connect to the DB, read the sqlalchemy docs: apache/incubator-superset@83b5dcc
Superset CLI was broken briefly, but not forever: apache/incubator-superset@9ec3e18

I have made other contributions to the ecosystem and hope to make more in the future.

**Comment by maorfr** [comment]
invitation sent!

**Comment by MarcusSorealheis** [comment]
thanks
