### ISSUE TITLE
[stable/rundeck] x-forwarded-proto behind L7 proxy with TLS

### ISSUE THREAD

**Issue by m-garrido** [helm/charts#20532]
**Describe the bug**
X-Forwarded-Proto in nginx, the default value is $scheme which is http.
When using an nginx ingress with tls, rundeck redirect to http://servername:443/user/login because x-forwarded-proto is http.
This configuration results in this error:

> 400 Bad Request
> The plain HTTP request was sent to HTTPS port

**Version of Helm and Kubernetes**:
Helm: 0.1.2
Kubernetes: 1.14.8

**Which chart**:
stable/rundeck

**What happened**:
Cannot login over tls because of an redirect request to http plain text.

**What you expected to happen**:
Before:
`proxy_set_header X-Forwarded-Proto $scheme;`

For example, after:
```
proxy_set_header X-Forwarded-Proto $thescheme;

map $http_x_forwarded_proto $thescheme {
     default $scheme;
     https https;
 }   
```

**How to reproduce it** (as minimally and precisely as possible):
Deploy rundeck helm with kubernetes using nginx ingress with tls enabled.

**Anything else we need to know**:
Nothing

**Comment by rafi-fisker** [comment]
@m-garrido Did you figure out a workaround? I am seeing same issue

**Comment by roko99** [comment]
@rafi-fisker try override nginx conf with:
```
nginxConfOverride: |
  events {
    worker_connections  1024;
  }

  http {
      server {
          location /healthz {
              return 204;
              access_log off;
          }
          location / {
              recursive_error_pages on;
              client_max_body_size 50M; # upload archives (backup/restore)
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
              proxy_set_header User-Agent $http_user_agent;
              proxy_pass http://localhost:4440;
          }
      }
  }
```
By `http_x_forwarded_proto` nginx container in rundeck pod should detect it as https from client.
Or as another solution to fork chart and remove nginx from it (update service rundeck source/target port to 4440; pin ingress to this service on correcter port), because for me it is over-complicated to have nginx behind nginx (ingress) in fact - may be I'm wrong in lack of knowledge of this application/chart.
