### ISSUE TITLE
Automatic Redirect to 443

### ISSUE THREAD

**Issue by hirosato223** [helm/charts#20549]
**Describe the bug**
App automatically redirected to port 443, even when service port set to 80. 

**Version of Helm and Kubernetes:**
helm: 3.0.3
Kuberenetes: 1.14

**Which chart:**
stable/pgadmin

**What happened:**
After installing the helm chart, http://my-pgadmin.domain.com is automatically redirected to http://my-pgadmin.domain.com:443/login?next=%2F. 
This results in "This site can’t be reached".

Manually updating the browser URL to http://my-pgadmin.domain.com/login?next=%2F properly loads the page. However, subsequent requests (ex: login) append :443 to the URL.

**What you expected to happen:**
http://my-pgadmin.domain.com redirects to http://my-pgadmin.domain.com/login?next=%2F, without :443 being added to the URL.

**How to reproduce it (as minimally and precisely as possible):**
In values.yaml

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
  hosts:
    - host: my-pgadmin.domain.com
      paths: [/]

**Anything else we need to know:**
Request is handled by helm/stable NGINX ingress controller

**Comment by rowanruseler** [comment]
@hirosato223 I assume this is an issue at your nginx side and not at the container, since the pod is configured as followed:

```
spec:
  containers:
    image: dpage/pgadmin4:4.17
    name: pgadmin
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
```

You can resolve this by adding: `nginx.ingress.kubernetes.io/ssl-redirect: "false"` if not mistaken. I could be wrong, but look at the documentation.
