### ISSUE TITLE
rabbitmq chart should use builtin prometheus plugin

### ISSUE THREAD

**Issue by jmturwy** [helm/charts#20541]
Please update rabbitmq to use the built-in Prometheus plugin. this plugin has been available since 3.8.0 and there would be no need to run a sidecare deployment

**Comment by andresbono** [comment]
Hi @jmturwy, thanks for suggesting this improvement. I assume you want this for `stable/rabbitmq`, right? Do you know if the exported metrics are equivalent?

Would you be interested on opening a PR addressing this issue? Please, let us know what you think!
