### ISSUE TITLE
[stable/airflow] allow default connections to be removed

### ISSUE THREAD

**Issue by javamonkey79** [helm/charts#20568]
**Is your feature request related to a problem? Please describe.**
When I run the helm chart for airflow, there are default connections that are in place that cannot be removed. To remove them, I've have to run a command like so:

```
airflow connections -d --conn_id databricks_default
```

Further, using an extra container does not seem to work, since it requires setting up and connecting to airflow, which would require resolving helm chart values in the values file itself.

**Describe the solution you'd like**
I would like to see a new value added, that allows init scripts to be run at startup. Alternatively, I'd like an option to remove the default connections.

**Describe alternatives you've considered**
I've tried using the extra-containers option, this did not work. I've also considered replacing the default configuration file with a custom one, since this way I could eliminate the default connections.

**Comment by javamonkey79** [comment]
I will have a PR for this soon, but, if there is a better approach, please lmk.

**Comment by javamonkey79** [comment]
pr created here https://github.com/helm/charts/pull/20593

**Comment by javamonkey79** [comment]
@maver1ck anything else I need to do here?

**Comment by javamonkey79** [comment]
@NBardelot can you help with this?

**Comment by NBardelot** [comment]
Hi, for the moment I'm using this script: 

```
AIRFLOW_DEFAULT_CONN_IDS="
airflow_db
aws_default
azure_container_instances_default
azure_cosmos_default
azure_data_lake_default
beeline_default
bigquery_default
cassandra_default
databricks_default
dingding_default
druid_broker_default
druid_ingest_default
emr_default
fs_default
google_cloud_default
hive_cli_default
hiveserver2_default
http_default
local_mysql
metastore_default
mongo_default
mssql_default
mysql_default
opsgenie_default
pig_cli_default
postgres_default
presto_default
qubole_default
redis_default
segment_default
sftp_default
spark_default
sqlite_default
sqoop_default
ssh_default
vertica_default
wasb_default
webhdfs_default
"

for CONN_ID in ${AIRFLOW_DEFAULT_CONN_IDS}; do echo "airflow connections --delete --conn_id '$CONN_ID'"; airflow connections --delete --conn_id "$CONN_ID"; done
```

I execute it in the webserver using `kubectl exec` after having deployed and started Airflow. 

As the initdb is done *after* the scheduler is started you cannot use initcontainers against the DB to do things like this (the same issue arises would you want to create users...).

**Comment by javamonkey79** [comment]
@NBardelot I like this approach, I will implement it. Thanks.

**Comment by javamonkey79** [comment]
@NBardelot @gsemet [new PR is up](https://github.com/helm/charts/pull/21018), with the simplified "remove default connections" approach described above.

**Comment by NBardelot** [comment]
See also:

https://issues.apache.org/jira/browse/AIRFLOW-6987
https://github.com/apache/airflow/pull/7629
