### ISSUE TITLE
[stable/redis] metric container doesn't connect to redis master

### ISSUE THREAD

**Issue by neodani** [helm/charts#20562]
**Describe the bug**
Pod metrics can't connect to redis.
Redis container is working well but metrics container don't, it can't connect to redis.
My redis work well with password secret. I don't know if they have something to do with my redis password?

**Version of Helm and Kubernetes**:

helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.33", GitCommit:"2c6d0ee462cee7609113bf9e175c107599d5213f", GitTreeState:"clean", BuildDate:"2020-01-15T17:47:46Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**: 
redis-10.3.4 

**What happened**:
Metrics container doesn't connect to redis.

kubectl logs -f redis-master-0 -c metrics
time="2020-02-05T15:47:48Z" level=info msg="Redis Metrics Exporter v1.0.3    build date: 2019-06-21-01:14:12    sha1: ec9e6402eda3ea70583a23858c9e698c4390ba36    Go: go1.12.6"
time="2020-02-05T15:47:48Z" level=info msg="Providing metrics at :9121/metrics"
time="2020-02-05T15:47:58Z" level=error msg="Couldn't connect to redis instance"
time="2020-02-05T15:47:59Z" level=error msg="Couldn't connect to redis instance"
time="2020-02-05T15:48:28Z" level=error msg="Couldn't connect to redis instance"
...

**What you expected to happen**:
No errors in metric container

**How to reproduce it** (as minimally and precisely as possible):
Here you can found my configuration of my custom_values.yml
https://privatebin.net/?f0106c7378edc041#9cFujE9RrX2GeeMjjFKNn2jimJCdF1rNoW7fuqnDbXPb

**Anything else we need to know**:

`helm install --name redis stable/redis -f custom_values-dani.yaml`

`k get secret redis-secret-env -oyaml
apiVersion: v1
data:
  REDIS_PASS: Zmtuc2tmODdUVUpkbWZuCg==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"REDIS_PASS":"Zmtuc2tmODdUVUpkbWZuCg=="},"kind":"Secret","metadata":{"annotations":{},"name":"redis-secret-env","namespace":"default"},"type":"Opaque"}
  creationTimestamp: "2020-01-30T15:44:22Z"
  name: redis-secret-env
  namespace: default
  resourceVersion: "31027"
  selfLink: /api/v1/namespaces/default/secrets/redis-secret-env
  uid: 62bb24cc-4377-11ea-b0bf-42010a140409
type: Opaque
`

**Comment by miguelaeh** [comment]
Hi @neodani ,
In your values you have `metrics.enabled=false` maybe those are not the values you are actually using.
Also I tested the default deployment:
```
helm install stable/redis --set metrics.enabled=true

**Comment by neodani** [comment]
Hi!

I've tested and only happens when password is configured in your own secret.

This "default way" works
```
usePassword: true
#password:
usePasswordFile: false
```

But when you try with your existing secret, metrics doesn't work, could you try?
```usePassword: true
existingSecret: redis-secret-env
existingSecretPasswordKey: REDIS_PASSWORD
usePasswordFile: false
```

Thank you
