### ISSUE TITLE
[stable/rabbitmq  tiller is not found

### ISSUE THREAD

**Issue by cmpmohan** [helm/charts#20571]
**Describe the bug**

**Version of Helm and Kubernetes**:
helm v2.16.0
kubernetes 1.15

**Which chart**:
stable/rabbitm1

**What happened**:

 helm install --kubeconfig=<config file>  -n database stable/rabbitmq
Error: could not find tiller

we are getting tiller error 

**What you expected to happen**:

Is possible to install rabbitmq without tiller?

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by javsalgar** [comment]
Hi,

I presume that you did not execute this command

```
helm init
```

If you do not want to use tiller, you can use helm 3 instead. All of our charts are Helm 3 ready.
