### ISSUE TITLE
unable to fetch pod metrics for pod nginx-ingress/private-ingress-nginx-ingress-controller no metrics known for pod

### ISSUE THREAD

**Issue by ramaprasad434** [helm/charts#20605]
**Describe the bug**
unable to fetch pod metrics for pod nginx-ingress/private-ingress-nginx-ingress-controller. We have metric server installed and it is able to fetch metrics for all the pods except nginx-controller

**Version of Helm and Kubernetes**:
 helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

K8s version:
v1.14.9

private-ingress         1               Wed Feb  5 10:31:51 2020        DEPLOYED        nginx-ingress-1.26.1                    0.26.1          nginx-ingress

**Which chart**:
metrics-server          1               Mon Jan 27 19:42:04 2020        DEPLOYED        metrics-server-2.0.4                    0.3.1           metrics

**What happened**:
metric server unable to fetch metrics for private ingress controller pod

**What you expected to happen**:

Metric server has to collect metrics for private nginx controller

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

Errors in metric server pod logs:
E0205 10:32:16.593112       1 reststorage.go:144] unable to fetch pod metrics for pod nginx-ingress/private-ingress-nginx-ingress-default-backend-7bb69fc58d-rzsnl: no metrics known for pod
E0205 10:32:16.593136       1 reststorage.go:144] unable to fetch pod metrics for pod nginx-ingress/private-ingress-nginx-ingress-controller-f75b4c4bf-7jgbp: no metrics known for pod
E0205 10:32:32.053218       1 reststorage.go:144] unable to fetch pod metrics for pod nginx-ingress/private-ingress-nginx-ingress-controller-f75b4c4bf-7jgbp: no metrics known for pod
E

**Comment by dennybaa** [comment]
Likewise nginx ingress controller is not scaled, but for a random deployment it's okay:
```
3m21s       Normal    SuccessfulRescale              horizontalpodautoscaler/bash   New size: 3; reason: cpu resource utilization (percentage of request) above target
```

**Comment by ramaprasad434** [comment]
@dennybaa  do you mean HPA does not support for nginx controller? Can you please confirm.

**Comment by dennybaa** [comment]
@ramaprasad434 we don't know yet the reasons, but it happens on GKE and suspect the metrics-server and kubelet inconsistency. First I will upgrade the cluster and there might be some updates.

**Comment by dennybaa** [comment]
I guess it has nothing to do with nginx ingress chart and relates more to this https://github.com/kubernetes/kubernetes/issues/79365
