### ISSUE TITLE
[stable/grafana] Unable to configure oauth authentication with github

### ISSUE THREAD

**Issue by gowrisankar22** [helm/charts#20617]
Hi Colleagues, 

I have tried configuring grafan oauth with github but it doesnot seem to work. can someone help ?
```
k logs po/prometheus-operator-grafana-5f89fb54d-tzqlw -c proxy
[error] invalid options, flag provided but not defined: -provider
```

```
+  - name: proxy
+    image: quay.io/gambol99/keycloak-proxy:latest
+    args:
+    - -provider=github.com
+    - -client-id=xxx
+    - -client-secret=xxx
+    - -github-org=org1
+    - -email-domain=*
+    - -cookie-secret=
+    - -http-address=http://0.0.0.0:4181
+    - -upstream-url=http://127.0.0.1:3000
+    ports:
+      - name: proxy-web
+        containerPort: 4181

 ## Enable persistence using Persistent Volume Claims
 ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
@@ -396,9 +396,14 @@ grafana.ini:
     url: https://grafana.net
 ## LDAP Authentication can be enabled with the following values on grafana.ini
 ## NOTE: Grafana will fail to start if the value for ldap.toml is invalid
-  # auth.ldap:
-  #   enabled: true
-  #   allow_sign_up: true
+    auth.github:
+      enabled: true
+      allow_sign_up: true
+      auth_url: https://github.com/login/oauth/authorize
+      token_url: https://github.com/login/oauth/access_token
+      api_url: https://github.com/api/v3/user
+      scopes:  user:email,read:org
+      allowed_organizations: 111
```

**Comment by gowrisankar22** [comment]
@zanhsieh @rtluckie @maorfr could you please help ?

**Comment by juliendangers** [comment]
According to the error, the issue is on keycloak-proxy configuration, not related to grafana. Why do you add keycloak gatekeeper while adding github authentication to Grafana ?

**Comment by ankush-vijay** [comment]
I am getting error as below 

Error:
t=2020-03-27T14:09:33+0000 lvl=eror msg="login.OAuthLogin(get info from github)" logger=context userId=0 orgId=0 uname= error="Error getting user info: invalid character '<' looking for beginning of value"
t=2020-03-27T14:09:33+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=500 remote_addr=10.185.0.4 time_ms=667 size=1743 referer=http://52.147.209.56/login

**Comment by NikoGrano** [comment]
@juliendangers Im not using keycloak and I still get exactly following:
```
lvl=eror msg="login.OAuthLogin(get info from github)" logger=context userId=0 orgId=0 uname= error="Error getting user info: invalid character '<' looking for beginning of value"
```

**Comment by rpeter** [comment]
The helm chart stable/grafana still have the entry "api_url: https://github.com/user"
it will not work, According to the documentation [here](https://grafana.com/docs/grafana/latest/auth/github/#configure-github-oauth-application) and [here](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/) it should be "api_url: https://api.github.com/user" After changing it, it works for me.
