### ISSUE TITLE
[stable/efs-provisioner] efs-provisioner pod keeps restarting a few times a day

### ISSUE THREAD

**Issue by arafatmohammed** [helm/charts#20625]
**Describe the bug**
We installed stable/efs-provisioner chart 6-8 months ago across multiple clusters and all of a sudden there seems to be this new issue where the efs-provisioner container inside the efs-provisioner pod keeps restarting.

**Version of Helm and Kubernetes**:

*Kubernetes Version:*
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-11T03:47:47Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-eb1860", GitCommit:"eb1860579253bb5bf83a5a03eb0330307ae26d18", GitTreeState:"clean", BuildDate:"2019-12-23T08:58:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

*Helm Version:*
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

**Which chart**:
stable/efs-provisioner

**What happened**:
efs-provisioner container inside the efs-provisioner pod keeps restarting with the following error:

```
{"log":"F0204 22:22:36.183767       1 efs-provisioner.go:293] Error getting server version: Get https://<host_ip_address>:443/version?timeout=32s: dial tcp <host_ip_address>:443: i/o timeout\n","stream":"stderr","time":"2020-02-04T22:22:36.184531725Z"}
```

**What you expected to happen**:
We want to know what might have happened to trigger these restarts

**How to reproduce it** (as minimally and precisely as possible):
```
helm install stable/efs-provisioner --name efs-provisioner -f values.yaml --namespace=<desired-namespace>
```

**Anything else we need to know**:

I have a hunch that this could be due to something to do with the system account not having access to host's /versions

**Comment by arafatmohammed** [comment]
NOTE:

I have exactly the same helm chart deployed across three different EKS clusters(each using their own EFS volume) and only 2 of them are seeing this error.

**Comment by arafatmohammed** [comment]
Every time I see these restarts logs pattern is as follows:

I0204 22:23:04.386241       1 controller.go:620] Started provisioner controller dais.com/aws-efs_efs-provisioner-79f5bd6c84-w5bz4_e01a6726-479c-11ea-87ce-662c30e8f5a1!

I0204 22:23:04.286145       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"bravo", Name:"dais.com-aws-efs", UID:"a291e099-a1c0-11e9-aab0-060720ab8a2c", APIVersion:"v1", ResourceVersion:"54880106", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' efs-provisioner-79f5bd6c84-w5bz4_e01a6726-479c-11ea-87ce-662c30e8f5a1 became leader

I0204 22:23:04.286103       1 controller.go:571] Starting provisioner controller dais.com/aws-efs_efs-provisioner-79f5bd6c84-w5bz4_e01a6726-479c-11ea-87ce-662c30e8f5a1!

I0204 22:23:04.285989       1 leaderelection.go:196] successfully acquired lease bravo/dais.com-aws-efs

I0204 22:22:48.852071       1 leaderelection.go:187] attempting to acquire leader lease  bravo/dais.com-aws-efs...

E0204 22:22:48.529271       1 efs-provisioner.go:69]

F0204 22:22:36.183767       1 efs-provisioner.go:293] Error getting server version: Get https://172.20.0.1:443/version?timeout=32s: dial tcp 172.20.0.1:443: i/o timeout

F0204 22:22:05.282873       1 controller.go:646] leaderelection lost

I0204 22:22:05.282827       1 leaderelection.go:231] failed to renew lease bravo/dais.com-aws-efs: failed to tryAcquireOrRenew context deadline exceeded

Now this is when it restarts.

**Comment by wongma7** [comment]
It means the efs provisioner cannot communicate with your apiserver. This is a more generic issue of apiserver (172.20.0.1:443) becoming unavailable, have you noticed other symptoms? It just happens that leader election is always the first thing it tries.
