### ISSUE TITLE
[stable/traefik] transition from acme.staging=true to false doesn't fetch new certificates

### ISSUE THREAD

**Issue by chasebolt** [helm/charts#20647]
**Describe the bug**
I successfully retrieved dummy certs from the staging server with acme.staging=True. Then I changed it to false and upgraded the release. It failed to retrieve new non-staging certs from letsencrypt.

Expected: To be able to practice on staging and when ready to go live flip acme.staging from true to false.

I suspect this might involve deleting the PersistentVolume or a helm delete --purge Release.

**Which chart**: stable/traefik

Duplicate from closed issue #4932

**Comment by tquach** [comment]
The`helm uninstall traefik` worked for me. This will purge the PV and PVC, however be warned that this will also blow away the ELB and if you have anything in terraform it will cause a mess.

Deleting the PV or PVC manually is not recommended as this will cause the PV to be in a Failed state as the volume will still be attached to the node.

It would be great if helm would recreate the PV / PVC when it is redeployed.

**Comment by protometa** [comment]
I've noticed that the storeconfig job doesn't appear to update the CA server field in the kvprovider because setting staging back to false simply means no new value will be loaded. The storeconfig job itself is problematic as it often doesn't get triggered when it needs to be.
