### ISSUE TITLE
[bitnami/redmine] How do I install plugin?

### ISSUE THREAD

**Issue by ranganathabrr** [helm/charts#20658]
Hi,
I installed redmine using helm, Its working fine and I applied ingress file Its working fine.
The below command is used to install redmine: 

helm install  red2 --set redmineUsername=xxxx@gmail.com,redminePassword=password -f values.yaml bitnami/redmine

Question : How do I install new plugin?
![Screenshot from 2020-02-11 15-50-12](https://user-images.githubusercontent.com/11206388/74228400-5f1ac380-4ce6-11ea-93d9-cc19cbdba054.png)

**Comment by andresbono** [comment]
Hi @ranganathabrr, that's currently not supported out-of-the-box. One thing that you can do is to create your custom image that includes the plugin. You have an example on how to do it here: https://github.com/bitnami/bitnami-docker-redmine/issues/115#issuecomment-468231005

Hope this is helpful!

We also have plans to ease the inclusion of plugins: https://github.com/bitnami/bitnami-docker-redmine/issues/118 but that's not yet addressed.
