### ISSUE TITLE
[stable/grafana] disable admin user

### ISSUE THREAD

**Issue by naseemkullah** [helm/charts#20697]
Is there a way to disable the admin user?

We are logging in using 3rd party oauth and do not require the default admin user with basic auth.

**Comment by vivekanandg** [comment]
any update on this?

**Comment by naseemkullah** [comment]
Hi @vivekanandg https://grafana.com/docs/grafana/latest/auth/overview/#automatic-oauth-login is what we wanted as it prevented anyone from logging in with non-oauth (admin account), although that admin account does exist, nobody can use it to log in.

**Comment by aywrite** [comment]
@naseemkullah came here looking for the same thing - but values from the grafana.ini yaml dictionary are just directly mapped into the config, as far as I can tell the following works:
```yaml
grafana.ini:
  security:
    disable_initial_admin_creation: true
```
