### ISSUE TITLE
[stable/nfs-server-provisioner] Fails to provision unless provisionerName is set

### ISSUE THREAD

**Issue by appunni-m** [helm/charts#20701]
```StorageClass "nfs": error getting NFS server IP for volume: service SERVICE_NAME=nfs-data-nfs-server-provisioner is not valid; check that it has for ports map[{111 TCP}:true {111 UDP}:true {662 TCP}:true {662 UDP}:true {875 TCP}:true {875 UDP}:true {2049 TCP}:true {2049 UDP}:true {20048 TCP}:true {20048 UDP}:true {32803 TCP}:true {32803 UDP}:true] exactly one endpoint, this pod's IP POD_IP=10.32.3.33```

This error is thrown in nfs-server-provisioner when  provisionerName is set empty in the helm chart. And it is not noted in documentation that it is not an optional field.  Try default values with 1.13.12-gke.13.

**Comment by cedricve** [comment]
@naseemkullah @lurraca  any help here?

**Comment by naseemkullah** [comment]
cc @kvaps

**Comment by cedricve** [comment]
just tried myself and it looks like, it is not using latest version. When cloning the repo/chart it works.

     helm install stable/nfs-server-provisioner
