### ISSUE TITLE
[stable/redis] Dynamic or NO master/slave component when sentinel enabled

### ISSUE THREAD

**Issue by naseemkullah** [helm/charts#20718]
It is very confusing to have 1 pod labelled as master, when running in sentinel mode and it could very well be a master or a replica depending on who the elected master is.

Possible suggestion:
remove component labels, they are all just redis pods (any can be master or replica at any time).

**Comment by javsalgar** [comment]
Hi,

I agree on this, we should do a major refactor of the chart so it is less confusing for users. However, I cannot provide an ETA on this.

**Comment by javsalgar** [comment]
As soon as we deal with this, I will update this ticket.

**Comment by naseemkullah** [comment]
Great, thanks!

May I suggest there being a clear way to keep data upon updating to this refactored version, if possible?


not to go off topic but will this chart be hosted at redis labs or bitnami  or elsewhere moving forward?

**Comment by miguelaeh** [comment]
Hi @naseemkullah ,
We recently released a new Redis Cluster Helm Chart called `redis-cluster`, you can find it here: https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster
The Helm Chart using Redis Sentinel is not easy to change to avoid that labels inconsistencies, but this new one uses the Redis Cluster topology and all the Pods are deployed with the same labels, and they are in charge of elect the masters in runtime, so there is nothing pre-configured regarding the cluster topology.

**Comment by naseemkullah** [comment]
Thanks for letting me know @miguelaeh , apart from consistent naming/labels is there any other significant advantage of this new chart over using the original chart with sentinel enabled?

**Comment by naseemkullah** [comment]
Also @miguelaeh is this chart for cluster or sentinrl? please see: https://fnordig.de/2015/06/01/redis-sentinel-and-redis-cluster/

**Comment by naseemkullah** [comment]
Thanks @miguelaeh for letting me know, that's great!

If today one wants to deploy redis sentinel (but not cluster), we should continue to use the `redis` chart?
