### ISSUE TITLE
[stable/pgadmin] Update ingress api version to networking.k8s.io

### ISSUE THREAD

**Issue by SkeLLLa** [helm/charts#20714]
**Describe the bug**
This chart using deprecated ingress API that will be removed in v1.18.
See:
https://github.com/kubernetes/kubernetes/pull/74057

And it seems that old api version isn't working well starting from v1.16.

**Which chart**:
<=stable/pgadmin-4.18

**Version of Helm and Kubernetes**:
Helm 3.0
K8s 1.16

**What happened**:
Ingress resource uses `apiVersion: extensions/v1beta1`

**What you expected to happen**:
Ingress resource uses `apiVersion: networking.k8s.io/v1beta1`. Or at least it should be configurable via values.

cc @rowanruseler 

See https://github.com/helm/charts/blob/7693fe1b29192513dc34bf2e16cf22014e02ff02/stable/prometheus-cloudwatch-exporter/templates/_helpers.tpl#L56L64 for example.

Maybe other changes from https://github.com/helm/charts/pull/17764 also make sense for this and other charts.

**Comment by rowanruseler** [comment]
@SkeLLLa thank you for bringing this to my attention. I'll try to take a look this week.
