### ISSUE TITLE
[stable/rabbitmq-ha] RollingUpdate -> federation issue & old queue reappears

### ISSUE THREAD

**Issue by johnniemorrow** [helm/charts#20713]
**Describe the bug**
Hi,

I'm doing a RollingUpdate of a 3-node rabbitmq cluster using rabbitmq-ha. The pods in the cluster do a rolling update but when they come back up there are a couple of issues:

1) An old queue which I'd previously deleted via the management ui, which had 0 messages, keeps reappearing. I've checked in the secrets (k get secrets rabbit-mq-rabbitmq-ha -o yaml | grep definitions.json | awk '{print $2}' | base64 -d) but that old queue isn't listed there, so I don't know where it's getting the definition from to recreate it.

2) I have a federation defined in my values.yaml but it's not starting up correctly. I can see it displayed in the management ui under Federation Upstreams, but it's not listed on the Federation Status. The log for one of the nodes shows an error saying "gen_event handler rabbit_federation_event crashed" with a badmatch badarg error but I'm not sure what the exact problem is (error in section of log below). The federation is defined in definitions-parameters of the values.yaml as:
      {
        "value": {
          "ack-mode": "on-confirm",
          "exchange": "the_upstream_exchange",
          "max-hops": 1,
          "reconnect-delay": 1,
          "trust-user-id": false,
          "uri": "amqp://the_user:the_password@the_upstream_federation"
        },
        "vhost": "/",
        "component": "federation-upstream",
        "name": "documents-federation"
      },

Any idea where the queue definition in 1) is coming from, or what the error in 2) is from?

Thanks in advance,
John.

**Version of Helm and Kubernetes**:
Helm: v2.14.0
Kubernetes: v1.14.9-eks-c0eccc

**Which chart**:
stable/rabbitmq-ha

**Error in rabbit pod log:**
2020-02-12 16:33:25.705 [error] <0.455.0> ** gen_event handler rabbit_federation_event crashed.
** Was installed in rabbit_event
** Last event was: {event,parameter_set,[{component,global},{name,cluster_name},{value,<<"the_rabbitmq_cluster">>},{user_who_performed_action,<<"rmq-internal">>}],none,1581525205685}
** When handler state == []
** Reason == {{badmatch,{error,{{badarg,[{binary,part,[<<87,153,18,71,57,194,112,95,223,166,228,250,96,98,252,59,230,15,103,220,77,74,224,167,209,7,8,93,131,31,130,138,78,13,184,36,138,38,29,217,25,145,191,244,36,24,205,136,115,250,124,93,145,243,246,133,142,50,228,42,242,16,211,11,88,68,142,245,33,171,203,195,61,3,108,154,40,83,108,13,11,185,92,199,18,225,169,60,30,64,89,4,84,239,255,129>>,0,-33],[]},{credentials_obfuscation_pbe,unpad,1,[{file,"src/credentials_obfuscation_pbe.erl"},{line,143}]},
{rabbit_federation_util,'-deobfuscate_upstream/1-lc$^0/1-0-',1,[{file,"src/rabbit_federation_util.erl"},{line,94}]},
{rabbit_federation_util,deobfuscate_upstream,1,[{file,"src/rabbit_federation_util.erl"},{line,94}]},
{rabbit_federation_exchange_link,init,1,[{file,"src/rabbit_federation_exchange_link.erl"},{line,78}]},
{gen_server2,init_it,6,[{file,"src/gen_server2.erl"},{line,565}]},
{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},
{child,undefined,{upstream,[<<"I1o66nTNB9SG25vGbPHeLGjVEmokyXuLPn+UIFVbbyGeUezy90TdXoCO6aMeGv5Rhb8wM2jARM2sdoYnbZamo7btUelh8Yc8/mr0atrvEHy2mQ2t5M6ZzVIqWGHn6Bqd7jBrLGllJcFplhxMpv8ufS49bt0lgm3uyZUBvIaTpZg=">>],
<<"the_upstream_exchange">>,<<"the_local_exchange">>,<<"federation-link-documents-federation">>,1000,1,1,none,none,false,'on-confirm',none,<<"documents-federation">>,false},{rabbit_federation_exchange_link,start_link,[{{upstream,[<<"I1o66nTNB9SG25vGbPHeLGjVEmokyXuLPn+UIFVbbyGeUezy90TdXoCO6aMeGv5Rhb8wM2jARM2sdoYnbZamo7btUelh8Yc8/mr0atrvEHy2mQ2t5M6ZzVIqWGHn6Bqd7jBrLGllJcFplhxMpv8ufS49bt0lgm3uyZUBvIaTpZg=">>],
<<"the_upstream_exchange">>,<<"the_local_exchange">>,<<"federation-link-documents-federation">>,1000,1,1,none,none,false,'on-confirm',none,<<"documents-federation">>,false},{resource,<<"/">>,exchange,<<"the_local_exchange">>}}]},{permanent,1},30000,worker,[rabbit_federation_exchange_link]}}}},[{rabbit_federation_link_sup,'-adjust/3-lc$^1/1-4-',2,[{file,"src/rabbit_federation_link_sup.erl"},{line,36}]},{rabbit_federation_exchange_link_sup_sup,'-adjust/1-lc$^0/1-0-',2,[{file,"src/rabbit_federation_exchange_link_sup_sup.erl"},{line,56}]},{rabbit_federation_exchange_link_sup_sup,adjust,1,[{file,"src/rabbit_federation_exchange_link_sup_sup.erl"},{line,57}]},{rabbit_federation_parameters,adjust,1,[{file,"src/rabbit_federation_parameters.erl"},{line,81}]},{rabbit_federation_event,handle_event,2,[{file,"src/rabbit_federation_event.erl"},{line,48}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,577}]},{gen_event,server_notify,4,[{file,"gen_event.erl"},{line,559}]},{gen_event,server_notify,4,[{file,"gen_event.erl"},{line,561}]}]}

**Comment by austince** [comment]
This is a large issue for us as well!

**Comment by austince** [comment]
Still haven't gotten to the bottom of this.
