### ISSUE TITLE
stable/rabitmq Unable to install in Kubernetes

### ISSUE THREAD

**Issue by VenkateshSrini** [helm/charts#20723]
**Describe the bug**
I'm trying to install the using the command
 `helm install --name rabbitmq --set rabbitmq.username=user,rabbitmq.password=PASSWORD stable/rabbitmq`.
 I have even tried the option
 
`helm install --name rabbitmq --set rabbitmq.username=user,rabbitmq.password=PASSWORD,volumePermissions.enabled=true stable/rabbitmq`

rabbit mq is crashing with error 

**init terminating in do_boot ({error,{could_not_write_file,/opt/bitnami/rabbitmq/var/lib/rabbitmq/mnesia/rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local/cluster_nodes.config,ebusy}})
{"init terminating in do_boot",{error,{could_not_write_file,"/opt/bitnami/rabbitmq/var/lib/rabbitmq/mnesia/rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local/cluster_nodes.config",ebusy}}}**
**Version of Helm and Kubernetes**:
Helm version :- v2.13.1
Kubernetes on Docker for Desktop (windows) :- v1.15.5
**Which chart**:
stabl/rabbitmq

**What happened**:
Rabbitmq pod in crashedback of state

**What you expected to happen**:
rabbitmq pod should be running

**How to reproduce it** (as minimally and precisely as possible):
1) Install the docker for desktop 2.2.03 (42716)
2) Enable Kubernetes in the docker
3) Enable file sharing setting->Resources->File sharing. Then click on apply and restart
4) Try install Rabbit MQ with helm charts. It fails

Please help me to overcome this

**Comment by miguelaeh** [comment]
Hi @VenkateshSrini ,
If I understand it correctly you are trying to share local files with your cluster. Make sure your files have the correct permissions for the Redis pod to write and read from it. Take a look to this section fo the Redis container's READE.md: https://github.com/bitnami/bitnami-docker-redis#persisting-your-database

**Comment by VenkateshSrini** [comment]
Hi @miguelaeh ,
I'm running the Helm chart to install the same. I have tried even giving "**,volumePermissions.enabled=true**". What else additional options should I give in helm chart to install this? Is there any otherway without helm chart that I can install where we will have some options to modify the yaml to suit the needs that you are saying

**Comment by VenkateshSrini** [comment]
Hi any other suggestion please

**Comment by miguelaeh** [comment]
Hi @VenkateshSrini ,
Sorry for the confusion, I updated the link in the comment but the concept is the same.
Could you exec into the Pod and check the volume permissions?
Also, which is the purpose of the following?
> Enable file sharing setting->Resources->File sharing. Then click on apply and restart

If it is to mount your local folder, check that local folder is owned by the user `1001` as commented in the link on my previouse comment.

**Comment by VenkateshSrini** [comment]
@miguelaeh ,
Sorry before you could post the reply I had uninstalled the new Docker version and then went ahead and installed the older version 2.1.X. It was having Kubernetes 1.14.X version of kubernetes. In that I could see this is running with out any issues. I'm not sure whether this an issue from Docker or Kubernetes cluster. Just in case if you can try doing this and check if you are able to simulate it

**Comment by miguelaeh** [comment]
Hi @VenkateshSrini ,
I am afraid I don't have a windows machine to test that, but I would suggest you for the next time to check what I explain in my previous comment.
