### ISSUE TITLE
[stable/airflow] Values.redis.master.port  is compulsory

### ISSUE THREAD

**Issue by appunni-m** [helm/charts#20728]
Workers where failing without Values.redis.master.port

**Comment by javsalgar** [comment]
Hi,

Could you elaborate more on the issue? Weren't you able to install it with the default values?

**Comment by appunni-dishq** [comment]
No it was a mistake with another issue with oassword having '/'  in it  which causes kombu to read charters before that '/' as port number but on cast to int it fails. Check kombu url_to_parts code for it
