### ISSUE TITLE
[stable/jenkins] 1.9.17 plugins not found 404

### ISSUE THREAD

**Issue by brylor** [helm/charts#20738]
Attempting to install jenkins stable 1.9.17 results in 404 when downloading plugins as the plugin repo seem to have moved locations

**Version of Helm and Kubernetes**:

```
➜  ~ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
➜  ~
```

**Which chart**:
stable/jenkins 1.9.17

**What happened**:

404 downloading plugins
Some plugins failed to download! 
Not downloaded: workflow-aggregator
Not downloaded: git
Not downloaded: workflow-job
Not downloaded: credentials-binding
Not downloaded: kubernetes

Pod stuck Init:0/1

**What you expected to happen**:
Helm to install a functioning version of jenkins

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

```
➜  ~ kubectl logs jenkins-85b86ffc5d-h644q -c copy-default-config -f
Creating initial locks...
Analyzing war /usr/share/jenkins/jenkins.war...
Registering preinstalled plugins...
Using version-specific update center: https://updates.jenkins.io/2.204...
Downloading plugins...
Downloading plugin: kubernetes from https://updates.jenkins.io/download/plugins/kubernetes/1.21.2/kubernetes.hpi
Downloading plugin: workflow-job from https://updates.jenkins.io/download/plugins/workflow-job/2.36/workflow-job.hpi
Downloading plugin: workflow-aggregator from https://updates.jenkins.io/download/plugins/workflow-aggregator/2.6/workflow-aggregator.hpi
Downloading plugin: credentials-binding from https://updates.jenkins.io/download/plugins/credentials-binding/1.20/credentials-binding.hpi
Downloading plugin: git from https://updates.jenkins.io/download/plugins/git/4.0.0/git.hpi
cp: overwrite '/var/jenkins_home/config.xml'? cp: overwrite '/var/jenkins_home/jenkins.CLI.xml'? cp: overwrite '/var/jenkins_home/jenkins.model.JenkinsLocationConfiguration.xml'? curl: (28) Connection tim
ed out after 20001 milliseconds
curl: (28) Connection timed out after 20001 milliseconds
curl: (28) Connection timed out after 20001 milliseconds
curlc: u(r2l8:)  (C2o8n)n eCcotnionne cttiimoend  toiumte da fotuetr  a2f0t0e0r1  m2i0l0l0i1s emciolnldiss
econds
18:21:38 Failure (28) Retrying in 1 seconds...
18:21:38 Failure (28) Retrying in 1 seconds...
18:21:38 Failure (28) Retrying in 1 seconds...
18:21:38 Failure (28) Retrying in 1 seconds...
18:21:38 Failure (28) Retrying in 1 seconds...
curl: (2c8)u rClo:n n(e2c8t)i oCno ntniemcetdi oonu tt iamfetde ro u2t0 0a0f1t emri l2l0i0s0e0c omnidlsl
iseconds
curl: (28) Connection timed out after 20001 milliseconds
18:23:53 Failure (28) Retrying in 1 seconds...
18:23:53 Failure (28) Retrying in 1 seconds...
18:23:53 Failure (28) Retrying in 1 seconds...
18:23:53 Failure (28) Retrying in 1 seconds...
18:23:54 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/kubernetes/1.21.2/kubernetes.hpi -o /usr/shar
e/jenkins/ref/plugins/kubernetes.jpi)
18:23:54 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/workflow-job/2.36/workflow-job.hpi -o /usr/sh
are/jenkins/ref/plugins/workflow-job.jpi)
18:23:54 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/credentials-binding/1.20/credentials-binding.
hpi -o /usr/share/jenkins/ref/plugins/credentials-binding.jpi)
18:23:54 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/git/4.0.0/git.hpi -o /usr/share/jenkins/ref/p
lugins/git.jpi)
Downloading plugin: workflow-job-plugin from https://updates.jenkins.io/download/plugins/workflow-job-plugin/2.36/workflow-job-plugin.hpi
Downloading plugin: kubernetes-plugin from https://updates.jenkins.io/download/plugins/kubernetes-plugin/1.21.2/kubernetes-plugin.hpi
Downloading plugin: credentials-binding-plugin from https://updates.jenkins.io/download/plugins/credentials-binding-plugin/1.20/credentials-binding-plugin.hpi
Downloading plugin: git-plugin from https://updates.jenkins.io/download/plugins/git-plugin/4.0.0/git-plugin.hpi
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
18:23:54 Failure (22) Retrying in 1 seconds...
18:23:54 Failure (22) Retrying in 1 seconds...
18:23:54 Failure (22) Retrying in 1 seconds...
18:23:54 Failure (22) Retrying in 1 seconds...
curl: (22) The requested URL returned error: 404 Not Found
18:23:55 Failure (22) Retrying in 1 seconds...
curl: (22) The requested URL returned error: 404 Not Found
18:23:56 Failure (22) Retrying in 1 seconds...
18:23:57 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/git-plugin/4.0.0/git-plugin.hpi -o /usr/share
/jenkins/ref/plugins/git-plugin.jpi)
Failed to download plugin: git or git-plugin
curl: (22) The requested URL returned error: 404 Not Found
18:24:01 Failure (22) Retrying in 1 seconds...
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
18:24:01 Failure (22) Retrying in 1 seconds...
18:24:01 Failure (22) Retrying in 1 seconds...
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
18:24:02 Failure (22) Retrying in 1 seconds...
18:24:02 Failure (22) Retrying in 1 seconds...
curl: (22) The requested URL returned error: 404 Not Found
18:24:02 Failure (22) Retrying in 1 seconds...
18:24:03 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/workflow-job-plugin/2.36/workflow-job-plugin.
hpi -o /usr/share/jenkins/ref/plugins/workflow-job-plugin.jpi)
Failed to download plugin: workflow-job or workflow-job-plugin
18:24:03 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/credentials-binding-plugin/1.20/credentials-b
inding-plugin.hpi -o /usr/share/jenkins/ref/plugins/credentials-binding-plugin.jpi)
Failed to download plugin: credentials-binding or credentials-binding-plugin
18:24:03 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/kubernetes-plugin/1.21.2/kubernetes-plugin.hp
i -o /usr/share/jenkins/ref/plugins/kubernetes-plugin.jpi)
Failed to download plugin: kubernetes or kubernetes-plugin

WAR bundled plugins:


Installed plugins:
*:
Some plugins failed to download! Not downloaded: workflow-aggregator
Not downloaded: git
Not downloaded: workflow-job
Not downloaded: credentials-binding
Not downloaded: kubernetes
cp: -r not specified; omitting directory '/usr/share/jenkins/ref/plugins/credentials-binding.lock'
cp: overwrite '/var/jenkins_plugins/failed-plugins.txt'? cp: -r not specified; omitting directory '/usr/share/jenkins/ref/plugins/git.lock'
cp: -r not specified; omitting directory '/usr/share/jenkins/ref/plugins/kubernetes.lock'
cp: -r not specified; omitting directory '/usr/share/jenkins/ref/plugins/workflow-aggregator.lock'
cp: -r not specified; omitting directory '/usr/share/jenkins/ref/plugins/workflow-job.lock'
```

**Comment by linux0x5c** [comment]
I have same problem.

**Comment by brylor** [comment]
Was able to get it running doing:
helm install jenkins stable/jenkins --set master.installPlugins=

yet I get connect timed out

Caused: java.io.IOException: Failed to load http://updates.jenkins-ci.org/download/plugins/script-security/1.70/script-security.hpi to /var/jenkins_home/plugins/script-security.jpi.tmp
        at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1217)
Caused: java.io.IOException: Failed to download from http://updates.jenkins-ci.org/download/plugins/script-security/1.70/script-security.hpi (redirected to: http://ftp-chi.osuosl.org/pub/jenkins/plugins/scrip
t-security/1.70/script-security.hpi)
        at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1251)
        at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1799)
        at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2070)
        at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1773)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:111)


Try to curl the url from within the pod: 


root@jenkins-6b87869697-4z9bn:/# curl  http://updates.jenkins-ci.org/download/plugins/trilead-api/1.0.5/trilead-api.hpi
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://mirrors.jenkins-ci.org/plugins/trilead-api/1.0.5/trilead-api.hpi">here</a>.</p>
</body></html>
root@jenkins-6b87869697-4z9bn:/# curl http://mirrors.jenkins-ci.org/plugins/trilead-api/1.0.5/trilead-api.hpi
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://ftp-nyc.osuosl.org/pub/jenkins/plugins/trilead-api/1.0.5/trilead-api.hpi">here</a>.</p>
</body></html>
root@jenkins-6b87869697-4z9bn:/# curl http://ftp-nyc.osuosl.org/pub/jenkins/plugins/trilead-api/1.0.5/trilead-api.hpi

... times out... 

I can ping and curl from the pod just fine, but jenkins itself is unable to...

Overall the release seems unusable, is there any stable working version?

**Comment by on4tux** [comment]
same issue here

**Comment by dineshba** [comment]
I also had the same issue. My problem is having a wrong `http_proxy` configuration.

**Comment by torstenwalter** [comment]
You can disable plugin installation on startup by setting plugins to an empty array. Update site configuration depends on the Jenkins image you use.

**Comment by on4tux** [comment]
> same issue here

I had an upstream DNS issue. Once fixed, this chart did work as expected.

**Comment by Vitorspk** [comment]
I also had the same issue. with stable/jenkins version 2.230

**Comment by moriyahazan** [comment]
> Attempting to install jenkins stable 1.9.17 results in 404 when downloading plugins as the plugin repo seem to have moved locations
> 
> **Version of Helm and Kubernetes**:
> 
> ```
> ➜  ~ helm version
> version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
> ➜  ~ kubectl version
> Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
> ➜  ~
> ```
> 
> **Which chart**:
> stable/jenkins 1.9.17
> 
> **What happened**:
> 
> 404 downloading plugins
> Some plugins failed to download!
> Not downloaded: workflow-aggregator
> Not downloaded: git
> Not downloaded: workflow-job
> Not downloaded: credentials-binding
> Not downloaded: kubernetes
> 
> Pod stuck Init:0/1
> 
> **What you expected to happen**:
> Helm to install a functioning version of jenkins
> 
> **How to reproduce it** (as minimally and precisely as possible):
> 
> **Anything else we need to know**:
> 
> ```
> ➜  ~ kubectl logs jenkins-85b86ffc5d-h644q -c copy-default-config -f
> Creating initial locks...
> Analyzing war /usr/share/jenkins/jenkins.war...
> Registering preinstalled plugins...
> Using version-specific update center: https://updates.jenkins.io/2.204...
> Downloading plugins...
> Downloading plugin: kubernetes from https://updates.jenkins.io/download/plugins/kubernetes/1.21.2/kubernetes.hpi
> Downloading plugin: workflow-job from https://updates.jenkins.io/download/plugins/workflow-job/2.36/workflow-job.hpi
> Downloading plugin: workflow-aggregator from https://updates.jenkins.io/download/plugins/workflow-aggregator/2.6/workflow-aggregator.hpi
> Downloading plugin: credentials-binding from https://updates.jenkins.io/download/plugins/credentials-binding/1.20/credentials-binding.hpi
> Downloading plugin: git from https://updates.jenkins.io/download/plugins/git/4.0.0/git.hpi
> cp: overwrite '/var/jenkins_home/config.xml'? cp: overwrite '/var/jenkins_home/jenkins.CLI.xml'? cp: overwrite '/var/jenkins_home/jenkins.model.JenkinsLocationConfiguration.xml'? curl: (28) Connection tim
> ed out after 20001 milliseconds
> curl: (28) Connection timed out after 20001 milliseconds
> curl: (28) Connection timed out after 20001 milliseconds
> curlc: u(r2l8:)  (C2o8n)n eCcotnionne cttiimoend  toiumte da fotuetr  a2f0t0e0r1  m2i0l0l0i1s emciolnldiss
> econds
> 18:21:38 Failure (28) Retrying in 1 seconds...
> 18:21:38 Failure (28) Retrying in 1 seconds...
> 18:21:38 Failure (28) Retrying in 1 seconds...
> 18:21:38 Failure (28) Retrying in 1 seconds...
> 18:21:38 Failure (28) Retrying in 1 seconds...
> curl: (2c8)u rClo:n n(e2c8t)i oCno ntniemcetdi oonu tt iamfetde ro u2t0 0a0f1t emri l2l0i0s0e0c omnidlsl
> iseconds
> curl: (28) Connection timed out after 20001 milliseconds
> 18:23:53 Failure (28) Retrying in 1 seconds...
> 18:23:53 Failure (28) Retrying in 1 seconds...
> 18:23:53 Failure (28) Retrying in 1 seconds...
> 18:23:53 Failure (28) Retrying in 1 seconds...
> 18:23:54 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/kubernetes/1.21.2/kubernetes.hpi -o /usr/shar
> e/jenkins/ref/plugins/kubernetes.jpi)
> 18:23:54 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/workflow-job/2.36/workflow-job.hpi -o /usr/sh
> are/jenkins/ref/plugins/workflow-job.jpi)
> 18:23:54 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/credentials-binding/1.20/credentials-binding.
> hpi -o /usr/share/jenkins/ref/plugins/credentials-binding.jpi)
> 18:23:54 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/git/4.0.0/git.hpi -o /usr/share/jenkins/ref/p
> lugins/git.jpi)
> Downloading plugin: workflow-job-plugin from https://updates.jenkins.io/download/plugins/workflow-job-plugin/2.36/workflow-job-plugin.hpi
> Downloading plugin: kubernetes-plugin from https://updates.jenkins.io/download/plugins/kubernetes-plugin/1.21.2/kubernetes-plugin.hpi
> Downloading plugin: credentials-binding-plugin from https://updates.jenkins.io/download/plugins/credentials-binding-plugin/1.20/credentials-binding-plugin.hpi
> Downloading plugin: git-plugin from https://updates.jenkins.io/download/plugins/git-plugin/4.0.0/git-plugin.hpi
> curl: (22) The requested URL returned error: 404 Not Found
> curl: (22) The requested URL returned error: 404 Not Found
> curl: (22) The requested URL returned error: 404 Not Found
> curl: (22) The requested URL returned error: 404 Not Found
> 18:23:54 Failure (22) Retrying in 1 seconds...
> 18:23:54 Failure (22) Retrying in 1 seconds...
> 18:23:54 Failure (22) Retrying in 1 seconds...
> 18:23:54 Failure (22) Retrying in 1 seconds...
> curl: (22) The requested URL returned error: 404 Not Found
> 18:23:55 Failure (22) Retrying in 1 seconds...
> curl: (22) The requested URL returned error: 404 Not Found
> 18:23:56 Failure (22) Retrying in 1 seconds...
> 18:23:57 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/git-plugin/4.0.0/git-plugin.hpi -o /usr/share
> /jenkins/ref/plugins/git-plugin.jpi)
> Failed to download plugin: git or git-plugin
> curl: (22) The requested URL returned error: 404 Not Found
> 18:24:01 Failure (22) Retrying in 1 seconds...
> curl: (22) The requested URL returned error: 404 Not Found
> curl: (22) The requested URL returned error: 404 Not Found
> 18:24:01 Failure (22) Retrying in 1 seconds...
> 18:24:01 Failure (22) Retrying in 1 seconds...
> curl: (22) The requested URL returned error: 404 Not Found
> curl: (22) The requested URL returned error: 404 Not Found
> 18:24:02 Failure (22) Retrying in 1 seconds...
> 18:24:02 Failure (22) Retrying in 1 seconds...
> curl: (22) The requested URL returned error: 404 Not Found
> 18:24:02 Failure (22) Retrying in 1 seconds...
> 18:24:03 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/workflow-job-plugin/2.36/workflow-job-plugin.
> hpi -o /usr/share/jenkins/ref/plugins/workflow-job-plugin.jpi)
> Failed to download plugin: workflow-job or workflow-job-plugin
> 18:24:03 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/credentials-binding-plugin/1.20/credentials-b
> inding-plugin.hpi -o /usr/share/jenkins/ref/plugins/credentials-binding-plugin.jpi)
> Failed to download plugin: credentials-binding or credentials-binding-plugin
> 18:24:03 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/download/plugins/kubernetes-plugin/1.21.2/kubernetes-plugin.hp
> i -o /usr/share/jenkins/ref/plugins/kubernetes-plugin.jpi)
> Failed to download plugin: kubernetes or kubernetes-plugin
> 
> WAR bundled plugins:
> 
> 
> Installed plugins:
> *:
> Some plugins failed to download! Not downloaded: workflow-aggregator
> Not downloaded: git
> Not downloaded: workflow-job
> Not downloaded: credentials-binding
> Not downloaded: kubernetes
> cp: -r not specified; omitting directory '/usr/share/jenkins/ref/plugins/credentials-binding.lock'
> cp: overwrite '/var/jenkins_plugins/failed-plugins.txt'? cp: -r not specified; omitting directory '/usr/share/jenkins/ref/plugins/git.lock'
> cp: -r not specified; omitting directory '/usr/share/jenkins/ref/plugins/kubernetes.lock'
> cp: -r not specified; omitting directory '/usr/share/jenkins/ref/plugins/workflow-aggregator.lock'
> cp: -r not specified; omitting directory '/usr/share/jenkins/ref/plugins/workflow-job.lock'with 
> ```

same error with cart version 2.5.0
Any idea how solve it?

**Comment by moriyahazan** [comment]
> > same issue here
> 
> I had an upstream DNS issue. Once fixed, this chart did work as expected.

Can you please explain a more about the solution

**Comment by trey2001** [comment]
I also have this problem only I'm getting mixed 403s in there:

[root@ip-10-106-100-111 bin]# kubectl logs dev-jenkins-c49a2bf57-bz6l2 -c copy-default-config -f
applying Jenkins configuration
disable Setup Wizard
download plugins
Creating initial locks...
Analyzing war /usr/share/jenkins/jenkins.war...
Registering preinstalled plugins...
Using version-specific update center: https://updates.jenkins.io/2.235...
Downloading plugins...
Downloading plugin: kubernetes from https://updates.jenkins.io/download/plugins/kubernetes/1.25.7/kubernetes.hpi
Downloading plugin: workflow-job from https://updates.jenkins.io/download/plugins/workflow-job/2.39/workflow-job.hpi
Downloading plugin: workflow-aggregator from https://updates.jenkins.io/download/plugins/workflow-aggregator/2.6/workflow-aggregator.hpi
Downloading plugin: credentials-binding from https://updates.jenkins.io/download/plugins/credentials-binding/1.23/credentials-binding.hpi
Downloading plugin: configuration-as-code from https://updates.jenkins.io/download/plugins/configuration-as-code/1.41/configuration-as-code.hpi
Downloading plugin: git from https://updates.jenkins.io/download/plugins/git/4.2.2/git.hpi
 > workflow-aggregator depends on lockable-resources:2.3,pipeline-stage-view:2.10,workflow-api:2.29,workflow-basic-steps:2.11,workflow-cps-global-lib:2.11,workflow-cps:2.56,workflow-durable-task-step:2.22,workflow-job:2.25,workflow-multibranch:2.20,workflow-scm-step:2.6,workflow-step-api:2.16,workflow-support:2.20,cloudbees-folder:6.6,credentials:2.1.18,git-client:2.7.3,jackson2-api:2.8.11.3,pipeline-build-step:2.7,pipeline-input-step:2.8,pipeline-milestone-step:1.3.1,pipeline-stage-step:2.3,scm-api:2.2.8,structs:1.15,pipeline-model-definition:1.3.2
curl: (22) The requested URL returned error: 403 Forbidden
curl: (22) The requested URL returned error: 403 Forbidden
18:04:10 Failure (22) Retrying in 1 seconds...
18:04:10 Failure (22) Retrying in 1 seconds...
