### ISSUE TITLE
[stable/mongodb] Crash loop when configuring cluster in replica-set mode

### ISSUE THREAD

**Issue by jlmurphysa** [helm/charts#20756]
**Describe the bug**
MongoDB won't start up in my cluster (AWS EKS) - the arbiter pod in my replica set keeps crash-looping. The log from the container is listed below, along with my values.yaml configuration. 

**Version of Helm and Kubernetes**:
Helm versions:
```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
Kubernetes versions:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:
I'm attempting to deploy the chart with my configuration and the arbiter is just restarting over and over again. Here are the logs from the container:
```
10:18:57.47
 10:18:57.69 Welcome to the Bitnami mongodb container
 10:18:57.87 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
 10:18:58.11 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
 10:18:58.47 Send us your feedback at containers@bitnami.com
10:18:58.71
 10:18:59.01 INFO  ==> ** Starting MongoDB setup **
 10:19:01.86 INFO  ==> Validating settings in MONGODB_* env vars...
 10:19:02.37 INFO  ==> Initializing MongoDB...
 10:19:03.05 INFO  ==> No injected configuration files found. Creating default config files...
 10:19:03.43 DEBUG ==> Creating main configuration file...
 10:19:04.52 DEBUG ==> Setting permissions for MongoDB folders
 10:19:05.18 INFO  ==> Deploying MongoDB from scratch...
 10:19:06.14 DEBUG ==> Starting MongoDB in background...
about to fork child process, waiting until server is ready for connections.
forked process: 47
child process started successfully, parent exiting
0:19:21.08 INFO  ==> Creating users...
 10:19:21.08 INFO  ==> Users created
 10:19:21.08 INFO  ==> Writing keyfile for replica set authentication: the_dev_keyfile /opt/bitnami/mongodb/conf/keyfile
 10:19:21.58 INFO  ==> Configuring MongoDB replica set...
 10:19:21.59 INFO  ==> Stopping MongoDB...
 10:19:23.98 DEBUG ==> Starting MongoDB in background...
about to fork child process, waiting until server is ready for connections.
forked process: 124
ERROR: child process failed, exited with error number 1
To see additional information in this output, start without the "--fork" option.
```

**What you expected to happen**:
Replicaset to startup smoothly. This is a very common use case.

**How to reproduce it** (as minimally and precisely as possible):

Here are my values (combined from a base `values.yaml`, and an overriding `values.dev.yaml`):
```
mongodb:
  enabled: true
  image:
    debug: true
  usePassword: true
  mongodbUsername: companyname
  mongodbDatabase: companyname
  existingSecret: mongodb
  persistence:
    enabled: true
    size: 8Gi
    storageClass: fast
    accessModes: [ "ReadWriteOnce" ]
  replicaSet:
    enabled: true
    replicas:
      secondary: 1
      arbiter: 1
    pdb:
      enabled: true
      minAvailable:
        secondary: 1
        arbiter: 1
  volumePermissions:
    enabled: true # thought this may be needed, but doesn't seem to make any difference
  nodeSelector:
    node-class: "infra-node"  
  resources:
    requests:
      memory: 1Gi
      cpu: 300m
    limits:
      memory: 2Gi
      cpu: 1
```

**Anything else we need to know**:

Inside the `mongodb` secret, I have set the following: `mongodb-password`, `mongodb-root-password` and `mongodb-replica-set-key`.

I understand this is almost certainly user error, but I've been tweaking these values for the past few hours and absolutely cannot figure out what is going wrong.

So I'd really appreciate input from more experienced members of the community...

**Comment by juan131** [comment]
Hi @jlmurphysa 

It seems it's failing while restarting MongoDB:

```console
 10:19:21.58 INFO  ==> Configuring MongoDB replica set...
 10:19:21.59 INFO  ==> Stopping MongoDB...
 10:19:23.98 DEBUG ==> Starting MongoDB in background...
about to fork child process, waiting until server is ready for connections.
forked process: 124
ERROR: child process failed, exited with error number 1
```

See: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.2/debian-10/rootfs/libmongodb.sh#L934

It could be related to credentials issues, see:

- https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.2/debian-10/rootfs/libmongodb.sh#L944
- https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.2/debian-10/rootfs/libmongodb.sh#L845

How did you create the MongoDB secret? Did you see any similar error in the secondary nodes?

But it looks to me like it's something failing restarting MongoDB.

**Comment by jlmurphysa** [comment]
Hi @juan131,

Thanks for checking out the issue.

> How did you create the MongoDB secret? 

Here is the yaml for the secret:

```
apiVersion: v1
data:
  mongodb-conn-string: <b64-enc-non-null-value>
  mongodb-password: <b64-enc-non-null-value>
  mongodb-replica-set-key: <b64-enc-non-null-value>
  mongodb-root-password: <b64-enc-non-null-value>
kind: Secret
metadata:
  creationTimestamp: "2020-02-14T08:50:31Z"
  name: mongodb
  namespace: dev
  resourceVersion: "332117"
  selfLink: /api/v1/namespaces/dev/secrets/mongodb
  uid: 0e618094-4f07-11ea-bfa9-0653abf15c2a
type: Opaque
```

Maybe I'm missing a key or something, but surely there would be a warning for that? 

> Did you see any similar error in the secondary nodes?

The secondary containers are still Pending. I believe they're waiting for the arbiter to startup

**Comment by jlmurphysa** [comment]
Okay, I've made some progress here...

I was making the assumption that `primary` and `secondary` were waiting for the `arbiter`

This was incorrect... the reason they were `Pending` was because I hadn't created the `StorageClass` on my cluster yet.

After I resolved that, I needed to change my `replica-set-key`, because I had includes hyphens (illegal characters)

After that, my `primary` and `secondary` containers started up successfully, but the `arbiter`  is still crash-looping:
```
0:09:52.45 INFO  ==> Trying to connect to MongoDB server infra-mongodb...
 10:09:52.46 INFO  ==> Found MongoDB server listening at infra-mongodb:27017 !
 10:12:51.55 ERROR ==> Node infra-mongodb did not become available
 10:12:51.56 INFO  ==> Stopping MongoDB...
```

It looks like the `arbiter` is managing to connect. Here is a log from the `primary` container:
```
2020-02-18T10:16:49.599+0000 I  ACCESS   [conn385] Successfully authenticated as principal root on admin from client 192.168.182.145:43116
```

**Comment by jlmurphysa** [comment]
The arbiter is deciding to shutdown here: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.2/debian-10/rootfs/libmongodb.sh#L749

I logged into the primary node and executed the following:
```
> db.getUsers()
2020-02-18T10:35:10.241+0000 E  QUERY    [js] uncaught exception: Error: not master and slaveOk=false :
_getErrorWithCode@src/mongo/shell/utils.js:25:13
DB.prototype.getUsers@src/mongo/shell/db.js:1638:15
@(shell):1:1
>
```

This points me in a new direction.
Shouldn't be too far from a working cluster now...

**Comment by jlmurphysa** [comment]
One issue after another...

```
> rs.slaveOk()
> db.getUsers()
2020-02-18T10:44:06.973+0000 E  QUERY    [js] uncaught exception: Error: not master or secondary; cannot currently read from this replSet member :
_getErrorWithCode@src/mongo/shell/utils.js:25:13
DB.prototype.getUsers@src/mongo/shell/db.js:1638:15
@(shell):1:1
```

**Comment by jlmurphysa** [comment]
Finally resolved. 

I removed the existing PVC before re-deploying and everything spun up without hassle.
