### ISSUE TITLE
[stable/mongodb] Ability to add labels to service 

### ISSUE THREAD

**Issue by JTarball** [helm/charts#20758]
**Is your feature request related to a problem? Please describe.**
 There is no way to add a custom label to the statefulset service 

**Describe the solution you'd like**
 Add helm value + template to allow custom labels

**Comment by juan131** [comment]
Hi @JTarball 

Thanks so much for the suggestions! It would be great if you could create a PR adding this feature! I'd be glad to review it.

**Comment by evalsocket** [comment]
@juan131 @JTarball Would like to work on this. Can this be assigned to me.

**Comment by juan131** [comment]
sure @evalsocket
