### ISSUE TITLE
[stable/external-dns] Allow CAs for any provider in the ConfigMap

### ISSUE THREAD

**Issue by NickLarsenNZ** [helm/charts#20796]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to supply CA chains for providers other than designate:

https://github.com/helm/charts/blob/275d0344f38ae4d6626464c02f6869d9c56f4e55/stable/external-dns/templates/configmap.yaml#L7-L9

This means customising the chart for internal use, modifying the provider container to have the certificate chain baked in, or worse IMO: patch the deployment to mount the certificate chain file.

**Describe the solution you'd like**
Allow the ConfigMap <charts/stable/external-dns/templates/configmap.yaml> to contain a generic list of trusted CAs, not specific to a provider.

**Describe alternatives you've considered**
If different provider's TLS verification process works different (eg: can only check one cert, or must contain the full chain), then perhaps extend the current configuration to other providers.

Eg:

```yml
data:
  {{ .Values.designate.customCA.filename }}: |
{{ .Values.designate.customCA.content | indent 4 }}
  {{ .Values.infoblox.customCA.filename }}: |
{{ .Values.infoblox.customCA.content | indent 4 }}
```

**Comment by NickLarsenNZ** [comment]
As per contributing guidelines, I must test this before raising a PR. I will try to do this over the next few days.

**Comment by juan131** [comment]
Hi @NickLarsenNZ 

IMHO, a generic list of trusted CA(s), not specific by provider, it's simpler and it wouldn't add more complexity to the chart. 

However, if you take a look to the current structure followed in this chart, you'll see that each provider has its own configuration parameters... For instance, take a look to `coredns`, it uses a different way to provide the CA(s). 

Therefore, I'd say that, to avoid introducing backwards incompatibilities due to refactoring the values structure, we should take the 2nd approach.

**Comment by NickLarsenNZ** [comment]
Yeah, I noticed designate uses an env var, while others used a command line option. The commits above make the minimum amount of change, and default the customCA chain to be stored where golang defaults to in Alpine.

We can keep morphing this to get closer to an ideal state while not breaking anything. I need to get a testing environment setup at work so I can raise an honest PR.

**Comment by NickLarsenNZ** [comment]
I adjusted the default CA path for Alpine based on: https://golang.org/src/crypto/x509/root_linux.go

**Comment by juan131** [comment]
Hi @NickLarsenNZ 

It looks like you submitted some commits to your fork repository, but I don't see any PR associated. Do you plan to create one for us to review?

**Comment by NickLarsenNZ** [comment]
Hi @juan131, I do intend to raise a PR (and wanted to last night), but the PR template states:

> Please make sure you test your changes before you push them. Once pushed, a CircleCI
will run across your changes and do some initial checks and linting. These checks run
very quickly. Please check the results. We would like these checks to pass before we
even continue reviewing your changes.

Unfortunately I didn't get time to try this out today. I'm happy to raise the PR anyway (if that's ok?)

**Comment by juan131** [comment]
Yes, that's okay! Don't worry about CircleCI @NickLarsenNZ

**Comment by NickLarsenNZ** [comment]
Cool, I'll raise a PR. I tested yesterday, and although I still have TLS trust issues, I found some surprising code in the infoblox client which is specific to the problem that caused me to raise this issue:

https://github.com/infobloxopen/infoblox-go-client/blob/master/connector.go#L39-L43

Turns out the infoblox client takes a string which can be `"true"`, `"false"`, or a path to the CA cert file - so the Go default locations don't apply in this case.

**Comment by NickLarsenNZ** [comment]
@juan131 this should be good to go

**Comment by juan131** [comment]
Hi @benjamin-wright 

Given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), this Bitnami maintained Helm chart was deprecated and moved to [bitnami/charts](https://github.com/bitnami/charts/) some weeks ago. Please visit the [bitnami/charts](https://github.com/bitnami/charts/) GitHub repository to create Issues or PRs.

In this issue ([#20969](#20969)), we tried to explain more carefully the reasons and motivations behind this transition, please don't hesitate to add a comment in this issue if you have any question related to the migration itself.
