### ISSUE TITLE
[stable/external-dns] Issues with azure.json config after upgrading helm chart to latest

### ISSUE THREAD

**Issue by audunsolemdal** [helm/charts#20816]
**Describe the bug**

**Version of Helm and Kubernetes**:
Helm 2.16.3
Kubernetes 1.16.4 (AKS)

**Which chart**:
 2.16.1

**What happened**:
I upgraded my cluster from version 1.14.8 to 1.16.4. During this I had to update the external-dns chart from version 1.7.0 to 2.16.1 due to API deprecations.

After the upgrade the helm chart is not able to use the secretName config.

We've used this in the past:

```
    provider: azure
    azure: 
      secretName: azure-dns-config-file
```

the secret exists in the namespace and has the expected format as described here:
https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/azure.md#creating-configuration-file

From the parameter reference  https://github.com/helm/charts/tree/master/stable/external-dns#parameters
I would assume that this should still work.

**What you expected to happen**:
No issues

**How to reproduce it** (as minimally and precisely as possible):

Upgrade helm chart from 1.7.0 to 2.16.1
azure.json secret fails.

**Anything else we need to know**:

```
release error="Chart release failed: external-dns: &status.statusError{Code:2, Message:\"render error in \\\"external-dns/templates/NOTES.txt\\\": template: external-dns/templates/NOTES.txt:7:3: executing \\\"external-dns/templates/NOTES.txt\\\" at <include \\\"external-dns.validateValues\\\" .>: error calling include: template: external-dns/templates/_helpers.tpl:208:51: executing \\\"external-dns.validateValues\\\" at <fail>: error calling fail: \\nVALUES VALIDATION:\\nexternal-dns: azure.resourceGroup\\n    You must provide the Azure Resource Group when provider=\\\"azure\\\".\\n    Please set the resourceGroup parameter (--set azure.resourceGroup=\\\"xxxx\\\")\", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}"
```

**Comment by miguelaeh** [comment]
Hi @solomson ,
How did you upgrade the Helm Chart? Did you uninstall and install it again or did you use `helm upgrade`?
If you used Helm Updagre take into account that they are different major version, that means that it will be incompatibilities.

**Comment by solomson** [comment]
Hello.
I did a fresh install onto a new cluster.

**Comment by miguelaeh** [comment]
Hi @solomson ,
As you can see in the log:
```
You must provide the Azure Resource Group when provider=\\\"azure\\\".\\n    Please set the resourceGroup parameter (--set azure.resourceGroup=\\\"xxxx\\\")\"
```
The failure reason is you didn't provide the `azure.resourceGroup` parameter, try providing that parameter. It is a validation we are doing in the `_helpers.tpl` to ensure the parameters are the correct one for every provider.

**Comment by solomson** [comment]
Ok fair enough, but this seems like a regression, as in previous versions all you need is to provide a secret flle formatted like this

```
{
  "tenantId": "b",
  "subscriptionId": "z",
  "aadClientId": "x"
  "aadClientSecret": "y",
  "resourceGroup": "..."
}
```

Which contains all relevant details. What is the point of this secret if we also have to explicitly type in other fields?
