### ISSUE TITLE
[stable/rabbitmq] set a sane default for RABBITMQ_DISK_FREE_LIMIT

### ISSUE THREAD

**Issue by mlaccetti** [helm/charts#2082]
The bitnami rabbitmq image sets a default value of `RABBITMQ_DISK_FREE_LIMIT="{mem_relative, 1.0}"` 
 - Having to provision a PVC (EBS) that is greater than the RAM size of the node is pretty brutal.  Pretty please add this to the chart.

**Comment by hairyhum** [comment]
Please note that setting disk limit smaller then RAM can be dangerous. If RabbitMQ runs out of disk space it can crash and be come almost unrecoverable. Messages held in RAM can be flushed to disk even if they are transient.
