### ISSUE TITLE
[stable/moodle] Values for Mariadb master persistence accessmode incorrect name/type

### ISSUE THREAD

**Issue by pickettd** [helm/charts#20827]
**Describe the bug**
The Moodle chart values.yaml file has the wrong parameter name/type for Mariadb master persistence accessmode

**Version of Helm and Kubernetes**:
Helm:
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}

Kubectl:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
[stable/moodle]

**What happened**:
I wanted to try installing the Moodle chart using ReadWriteMany access modes for both Moodle's persistence and Mariadb's persistence. I noticed that when I set mariadb.master.persistence.accessmode to "ReadWriteMany" as indicated in [the Moodle chart values](https://github.com/helm/charts/blob/master/stable/moodle/values.yaml) it still setup a PV with Mariadb's default ReadWriteOnce accessmode.

I looked at the values in [the Mariadb chart](https://github.com/helm/charts/tree/master/stable/mariadb) and found that the parameter is actually supposed to be mariadb.master.persistence.accessmodes = [ReadWriteMany] (note that accessmodes is plural and expects an array type).

**What you expected to happen**:
I expected that using the Moodle chart, I should be able to set the Mariadb master persistence accessmode parameter.

**How to reproduce it** (as minimally and precisely as possible):
Look at the mariadb.master.persistence.accessmode parameter of [the Moodle chart values](https://github.com/helm/charts/blob/master/stable/moodle/values.yaml) (note that the parameter name is singular and appears to be a string type) and compare to the 
master.persistence.accessmodes parameter of [the Mariadb chart](https://github.com/helm/charts/tree/master/stable/mariadb) (note that accessmodes is plural and expects an array type).

**Anything else we need to know**:
I found this issue through using Kubeapps and Rancher.

**Comment by miguelaeh** [comment]
Hi @pickettd ,
Thank you very much for reporting this issue, we will take care of it.
