### ISSUE TITLE
[stable/airflow] airflow web has no /admin/metrics API

### ISSUE THREAD

**Issue by vivianforzj** [helm/charts#20830]
I installed airflow, and set serviceMonitor true. I wished that I can monitor airflow by prometheus, but when I opened prometheus web and choose status->targets->unhealthy, I found that it reported server returned HTTP status 404 NOT FOUND for accessing airflow-web-IP:port/admin/metrics.

So I want to know if airflow web has the /admin/metrics API. If no, can I install the airflow plugin as https://github.com/airflow-plugins/airflow-exporter to get the API?  Thanks

**Comment by PierreC1024** [comment]
Airflow does not have by default a metrics exporter. f you want to use it, you have to install [airflow-exporter](https://github.com/airflow-plugins/airflow-exporter ) then you could have metrics on  /admin/metrics.
