### ISSUE TITLE
[stable/metabase] Add {} after annotations in values.yaml to avoid "warning: destination for annotations is a table. Ignoring non-table value <nil>"

### ISSUE THREAD

**Issue by LucaPrete** [helm/charts#20833]
**Describe the bug**
When using metabase as a chart dependency, the following warning is displayed during the chart installation/upgrade: "warning: destination for annotations is a table. Ignoring non-table value <nil>"

**Version of Helm and Kubernetes**:
helm 3.0.3
kubernetes 1.14.2

**Which chart**:
stable/metabase

**What happened**:
When using metabase as a chart dependency, the following warning is displayed during the chart installation/upgrade: "warning: destination for annotations is a table. Ignoring non-table value <nil>". This is not just something annoying, but it also causes CI/CD pipelines to fail

**What you expected to happen**:
The warning shouldn't be displayed.

**How to reproduce it** (as minimally and precisely as possible):
Use metabase as a chart dependency and install the chart with helm3

**Anything else we need to know**:
To solve the issue, it's simply needed to add `{}` after every annotation tag in the values.yaml, instead of leaving it empty.
I'm going to send a PR to fix this.

**Comment by LucaPrete** [comment]
Hello @pmint93 I still see the 0.10.3 version as the latest one available in the list of charts. Do you know when the 0.10.4 will be available for download from the helm cli?

**Comment by pmint93** [comment]
@LucaPrete  Run `helm repo update` 👍

**Comment by LucaPrete** [comment]
Ahhhhh, damn sorry :)

-Luca

Il giorno mer 19 feb 2020 alle ore 11:13 pmint93 <notifications@github.com>
ha scritto:

**Comment by pmint93** [comment]
@LucaPrete No problem, don't be sorry ;)
