### ISSUE TITLE
stable/datadog Parsing issue when applying multiple tags

### ISSUE THREAD

**Issue by richerlariviere** [helm/charts#20842]
**Describe the bug**

**Version of Helm and Kubernetes**:

Helm:
```
GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/datadog Latest version (1.39.9)

**What happened**:

I wanted to attach multiple tags to every metrics coming from a specific Kubernetes cluster. To do so, I added the following tags in my helm chart:
```
  tags:
    - environment: staging
    - env: staging
```
But when I deploy Datadog, I can see an issue with the parsing of the yaml map. You can see the screenshot that something is wrong and it's causing Datadog to read tags in a wrong way.

<img width="1409" alt="Screen Shot 2020-02-07 at 11 32 58 AM" src="https://user-images.githubusercontent.com/5884148/74744214-db099400-522f-11ea-8efb-0931e6c5c4b2.png">

With that current setup, Datadog will read the tags but will append `map_` before a tag name.

![Screen Shot 2020-02-18 at 8 58 50 AM](https://user-images.githubusercontent.com/5884148/74744707-b19d3800-5230-11ea-8723-5d14b09979b3.png)

**What you expected to happen**:

I expect Datadog to display tag names without the `map_` prefix.

**How to reproduce it** (as minimally and precisely as possible):

Deploy a datadog helm chart with more than 2 tags (in [this part](https://github.com/helm/charts/blob/master/stable/datadog/values.yaml#L131) of the yaml)

Datadog will display your tags with `map_<tag name>`

**Anything else we need to know**:

This is a bug in the helm chart. Currently, the chart is parsing tags like this:
```yaml
    - name: DD_TAGS
      value: {{ .Values.datadog.tags | quote }}
```

I know how to fix this issue and I will link a PR soon as I am testing a working patched chart.

**Comment by clamoriniere** [comment]
Hi @richerlariviere 

Thanks for opening this issue. 
We didn't use a "map" here because we want to have the possibility to add several times the same "key" in tags; for example: `service:booking` and `service:shopping`. that is why we are using a "list". 
Also due to YAML limitations. you need to force the type in the list by adding `"environment:staging"`

so the correct way to add several tags in the values file is:

```yaml
   tags:
     - "environment:staging"
     - "env:staging"
```

or maybe a bit clearer to understand that we are waiting for a list of string:

```yaml
   tags: ["environment:staging","env:staging"]
```

We will try to improve the documentation for `datadog.tags` field to better explain what is the attended value.

Let me know if I gave you enough details about the current behavior. 

Cheers
Cedric

**Comment by richerlariviere** [comment]
Hi @clamoriniere, thank you for your answer. I understand your point. I will then close my issue and my PR.

**Comment by bkruger99** [comment]
This is still broken though, no? 

clusterName is a tag and if you have it set, it will invalidate the rest of your yaml and your tags end up messed up?

Here's my example: 
https://github.com/DataDog/datadog-agent/issues/4982#issuecomment-600990057

I've revised my tags to the tag format of `tags: ["environment:staging","env:staging"]` and it's still broken by the chart.
