### ISSUE TITLE
[stable/rabbitmq-ha] vHost not found even though vHost exist in UI and is properly configured in chart

### ISSUE THREAD

**Issue by mrkcmo** [helm/charts#20877]
**Describe the bug**
Deploying the RabbitMQ or RabbitMQ-HA charts into a Kubernetes cluster (1.17.0) with multiple vhosts configured  (in my case 2 extra defined) deploys without error. You can see the vHosts in the UI and configuration of the rabbitmqctl command. However when you try and connect via AMQP too one the vHost you get a failure of "vHost (name of vhsost) not found" in the server log. The vHosts exist and all permission have been set and verified. 

**Version of Helm and Kubernetes**:
helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-27T21:11:27Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
RabbitMQ and RabbitMQ-HA - Tried both

**What happened**:
Configured both and deployed. Verified vHosts were created with all correct users and permissions. However when connecting via AMQP the user is authenticated but then you see an error in the server log that the vHosts is not found. Ran the images in straight Docker and Kubernetes without the helm chart and everything works correctly. 

I also tried different versions of RabbitMQ (3.8.2, 3.7.14, 3.7.24)  and all have the same failure in the server log when deployed via the Helm Chart. 

**What you expected to happen**:
I expect the vHost to work when deployed via the chart.

**How to reproduce it** (as minimally and precisely as possible):
Install via Helm Chart with a vhost other than "/" defined and try and connect to the vHost via the AMQP. It will fail with error in the server log.

**Anything else we need to know**:
I am running this in AKS in Azure. But have tried locally as well with same results. Works perfectly if you just use the default vHost "/".

**Comment by juan131** [comment]
Hi @mrkcmo 

Could you please share the commands you used to deploy the RabbitMQ chart and configure the vhosts? Please also share the exact **values.yaml** you're using in case you're overwriting the default one.

Thanks in advance

**Comment by mrkcmo** [comment]
I packaged and deployed:
helm package (folder_name)
helm install rabbitmq (package_name) --namespace (namespace)
[values.yaml.txt](https://github.com/helm/charts/files/4226508/values.yaml.txt)

**Comment by juan131** [comment]
Hi @mrkcmo 


This is the **values.yaml** for RabbitMQ HA, isn't it? I am maintainer of the [RabbitMQ chart](https://github.com/helm/charts/blob/master/stable/rabbitmq). I am afraid I won't be able to help you with RabbitMQ HA

**Comment by mrkcmo** [comment]
@juan131 I tried both and see the same issue just FYI.

**Comment by juan131** [comment]
Hi @mrkcmo 

Could you please share the **values.yaml** you were using with the [RabbitMQ chart](https://github.com/helm/charts/blob/master/stable/rabbitmq)? Please note that I don't need the whole **values.yaml** but just the values that you modified (instead of using the default ones)

**Comment by mrkcmo** [comment]
For anyone else that runs into this issue I was able to resolve it. In the Celery broker URL you have to add the vhost name with two // instead of the normal one /.

IE:  broker = 'amqp://hostname//name_of_vhost'
