### ISSUE TITLE
[stable/elasticsearch-curator] load env variables from secrets first to allow env composition

### ISSUE THREAD

**Issue by embik** [helm/charts#20872]
**Is your feature request related to a problem? Please describe.**
`stable/elasticsearch-curator` allows to load environment variables from secret keys via its `envFromSecrets`. This is nice to load elasticsearch basic auth passwords from a `Secret`, for example when using [ECK](https://www.elastic.co/guide/en/cloud-on-k8s/current/index.html).

Unfortunately, elasticsearch-curator only has limited support for environment variables (see [this documentation](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/envvars.html) for the limitations). You can only reference an environment variable and not do composition when creating the configuration file (`http_auth: username:${ELASTIC_PASSWORD}` does not work, `http_auth: ${ELASTIC_CREDENTIALS}` would work).

Now the secret key that I want to load from a authentication secret generated by ECK does only provide the password, not the username and therefore is not suitable for the `http_auth` key in [elasticsearch-curator configuration](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html#http_auth) (which requires `user:password`).

Kubernetes has a nice feature to composite existing environment variables into a new environment variable (see [the Kubernetes reference for env vars](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#envvar-v1-core)). But this only works if the referenced environment variable is _before_ the composite variable in the `env` YAML list.

Because of how the chart template is written, the environment variables from secrets are added last, which means I cannot reference them in environment variables.

**Describe the solution you'd like**
Move the template block for `envFromSecrets` in [the CronJob template](https://github.com/helm/charts/blob/master/stable/elasticsearch-curator/templates/cronjob.yaml) in front of the normal `env` templating block to process them first and allow composition in the normal environment variables.

**Describe alternatives you've considered**
I have considered writing an init container that rewrites the config and puts it in a `emptyFolder` volume, but this is a lot of work and the fix proposed is quite simple.

**Additional context**
-

**Comment by bastienbc** [comment]
I have a similar issue, and I am looking forward for this.
