### ISSUE TITLE
[Incubator] Add Ethereum private chain Helm chart

### ISSUE THREAD

**Issue by kairen** [helm/charts#2088]
**Is this a request for help?**:
Could I add a blockchain chart to run the Ethereum private chain cluster on Kubernetes? It will be like this repos [Kubereum](https://github.com/kairen/kubereum). Currently Helm chart work in process.

---
**Version of Helm and Kubernetes**:
Any version.

**Which chart**:
Add new chart to incubator.

**What you expected to happen**:
Deploy Ethereum blockchain on Kubernetes via Helm.

**Comment by mattfarina** [comment]
/remove-lifecycle stale

since #3220 is now open
