### ISSUE TITLE
[stable/postgresql] Admin user is not created

### ISSUE THREAD

**Issue by jayar** [helm/charts#20890]
**Describe the bug**
During initial load of database, an error occurs so the admin user is not created with the stored password.

**Version of Helm and Kubernetes**:
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}

Rancher v 2.3.5

**Which chart**:
Chart: stable/postgresql-8.3.4            	
app version: 11.7.0 

**What happened**:
When installing the chart a volume is created, using the storage class nfs-client. A new workload is also created and the initial load is starting. After a bit of time, the container restarts. See log for the first container her:
[postgresql_first_container_log.log](https://github.com/helm/charts/files/4227509/postgresql_first_container_log.log)
After the restart, the container continues the initial load of the database and states that the database was interrupted but continues the load and states that the database is ready. But the password for the admin user doesn't work, which is also stated in healthcheck. See log here: 
[postgresql_after_container_restart.log](https://github.com/helm/charts/files/4227510/postgresql_after_container_restart.log)

After each try I have removed the volume as stated in other questions.
  
**What you expected to happen**:
That the chart would create a volume, start the database and then I would be able to login using the admin user.

**How to reproduce it** (as minimally and precisely as possible):
Run `helm install my-release424 stable/postgresql  -f postgres-values.yaml`
Content of postgress-values.yaml:
postgresqlPassword: keycloak34eOk
postgresqlDatabase: keycc
postgresqlUsername: keyAdminUser
persistence:
    enabled: true
    storageClass: nfs-client

**Anything else we need to know**:
I have tried to install Mariadb using the storage class nfs-client, and there it is working.

**Comment by miguelaeh** [comment]
Hi @jayar ,
I am afraid we have an issue in the PostgreSQL image that we detected last week. It seems that when providing the username the password is not correctly set. Give a try to not create a user and just change the password.

**Comment by jayar** [comment]
Hi @miguelaeh I have just tried removing postgresqlDatabase and postgresqlUsername, and then only having postgresqlPassword, but it gives the same output. 
I have also tried to remove postgresqlPassword, so it is set by default setup but still no success.

**Comment by miguelaeh** [comment]
Hi @jayar, 
We checked again and the image issue was actually a misunderstand to of how to connect to Postgresql.
Regarding your issue, I deployed the Helm Chart with your parameters except for the NFS storage class and seems to be working. Could you test it using a different storage class to check if it an issue with NFS?

**Comment by jayar** [comment]
Hi @miguelaeh,
I had another deployment giving some issues, where it didn't have time enough for loading the data scripts, so I changed the liveness probes initial delay.  
So I tried the the same for postgresql and set it to 90 sec, and it worked.
Thanks for the quick reply and good suggestions... I suspect it is the NFS which is the reason for the slow load time.
