### ISSUE TITLE
[stable/prometheus-operator] Lack of resources configuration in values.yaml for grafana and node exporter

### ISSUE THREAD

**Issue by dogzzdogzz** [helm/charts#20920]
**Describe the bug**
I can't find the resources configuration in values.yaml for grafana and node exporter but there is one in prometheus and alerManager, so when I deploy prometheus-operater chart, pods of these grafana and node exporter have no requested/limited resource. Wondering if lack of resources config for these two components is intentional ?

**Version of Helm and Kubernetes**:
8.7.0

**Comment by MaksymDolgykh** [comment]
You can define resources for grafana with`grafana.resources`. The defaults are defined in [grafana chart](https://github.com/helm/charts/tree/master/stable/grafana)
