### ISSUE TITLE
[stable/gitlab-ee] Liveness Probe Should Be Optional

### ISSUE THREAD

**Issue by rawkode** [helm/charts#2092]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
1.7

**Which chart**:
gitlab-ee

**What happened**:
During GitLab restore process, pod is killed due to liveness-probe

**What you expected to happen**:
Probes should be optional, so we can  `helm update` to remove the probe and perform maintenance tasks

**How to reproduce it** (as minimally and precisely as possible):
`helm install` and then follow GitLab restore process, which involves stopping unicorn and thus fails probes.

**Comment by mattfarina** [comment]
@rawkode the gitlab-ee chart is deprecated and isn't going to be getting further updates. gitlab now maintains their own charts.
