### ISSUE TITLE
[stable/redis] Helm3 Upgrade Failing

### ISSUE THREAD

**Issue by dominik-bln** [helm/charts#20921]
**Describe the bug**

When trying to upgrade a `stable/redis` release from Helm 2 to Helm 3, the initial conversion is working, but the next release fails due to an immutable statefulset issue.

**Version of Helm and Kubernetes**:

Helm v3.0.3
Kubernetes 1.17.2

**Which chart**:

`stable/redis`

**What happened**:

 `The StatefulSet "review-helm3-7yge49-redis-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

**What you expected to happen**:

The deploy should pass.

**How to reproduce it** (as minimally and precisely as possible):

Install a redis release with Helm2, use helm3 with the `2to3` plugin to convert the release and do a deploy with helm3.

**Anything else we need to know**:

My best guess is that this is a similar issue to #7803 and happening due to the fact that Helm3 changes `heritage` from `Tiller` to `Helm`, which in turn updates the volume claim template:

https://github.com/helm/charts/blob/9977a782e401b84e486d32742c54f942a111964f/stable/redis/templates/redis-master-statefulset.yaml#L389

**Comment by dominik-bln** [comment]
Looks like there is a proposal on the Helm repo that could also fix this problem for us:

https://github.com/helm/helm/issues/7211

**Comment by juan131** [comment]
Hi @dominik-bln 

This issue was already reported for other chart and it's related to the label below which solves to `Tiller` in Helm2, and `Helm` in Helm3:

```yaml
heritage: {{ .Release.Service | quote }} 
```

See:

- https://github.com/helm/helm/issues/7211
- https://github.com/helm/charts/issues/19231

**Comment by dominik-bln** [comment]
This issue is not stale. Still a blocker for the Helm3 update for us.
