### ISSUE TITLE
Add tezos chart

### ISSUE THREAD

**Issue by noeRls** [helm/charts#20937]
**Describe the solution you'd like**
I would like to add a chart for tezos blockchain. This chart would start tezos and init them with fresh new peers. With values you could select weather run it on mainnet / betanet / alphanet / zeronet.

**Describe alternatives you've considered**
Having my own chart without sharing it.

**Additional context**
I'm going to develop a complete tezos chart. I was thinking about adding it to this repository to share it. What do you think about this?

**Comment by arnaud-skillz** [comment]
Great initiative @noeRls !

**Comment by arnaud-skillz** [comment]
Any update on this topic ?
