### ISSUE TITLE
[stable/influxdb] add backup support in aws s3 buckets.

### ISSUE THREAD

**Issue by aliartiza75** [helm/charts#20945]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to add aws s3 backup support for influxdb helm chart.

**Describe alternatives you've considered**
nil

**Additional context**
nil

**Comment by aliartiza75** [comment]
Hi @Aisuko, kindly add your thoughts about this feature. Thank you

**Comment by aliartiza75** [comment]
hi @naseemkullah, if found out that currently backups are only supported for azure and gcs, I was thinking about to add support for aws s3. what do you think?

**Comment by naseemkullah** [comment]
That would be great!

**Comment by aliartiza75** [comment]
as influx db helm chart is moved under influxdb helmChart, so a [issue](https://github.com/influxdata/helm-charts/issues/30) has been created there

**Comment by aliartiza75** [comment]
closing this issue, for now, track it on this [link](https://github.com/influxdata/helm-charts/issues/30)
