### ISSUE TITLE
[bitnami/wordpress] wrong allowEmptyPassword value

### ISSUE THREAD

**Issue by sorleone** [helm/charts#20954]
Is this line correct? Shouldn't that be `false`?

https://github.com/helm/charts/blob/65f1f381e293974b25e0903a45f395892f7bda7f/stable/wordpress/values-production.yaml#L98

Here it says the opposite:

https://github.com/bitnami/bitnami-docker-wordpress#environment-variables

ALLOW_EMPTY_PASSWORD: It can be used to allow blank passwords. Default: no

**Comment by carrodher** [comment]
Hi,

This doc is referring to the Docker image where the env. variable has a different default value.

In the case of charts, you can find the [default parameters in the chart README](https://github.com/helm/charts/tree/master/stable/wordpress#parameters), [in this case](https://github.com/helm/charts/blame/master/stable/wordpress/README.md#L73):

| `allowEmptyPassword`                      | Allow DB blank passwords                                                                               | `true`                                                       |

**Comment by sorleone** [comment]
@carrodher Hello, thank you for your reply. Isn't the chart sending that value to the Docker image anyway? Why would we want to allow empty passwords when using the Docker image in a chart?
