### ISSUE TITLE
[stable/nfs-server-provisioner] Why was the NFS version decreased?

### ISSUE THREAD

**Issue by sorleone** [helm/charts#20961]
I have noticed you modified the values of the Chart in the[ last commit](https://github.com/helm/charts/commit/6bd9551d39739a6a3564c8f9b666480921e8c1de#diff-63df78371422b655c0b2be69da8fbd34), from this

```yaml
  mountOptions:
    - vers=4.1
    - noatime
```

to

```yaml
  mountOptions:
    - vers=3
```

why is that? And what kinds of differences would I get with these two types of mount options?

**Comment by cedricve** [comment]
better support for kubernetes, many issues where opened in the past to increase usability and availability in a cluster.
