### ISSUE TITLE
[stable/rabbitmq] Support for `loadBalancerIP`

### ISSUE THREAD

**Issue by anton-johansson** [helm/charts#20973]
**Is your feature request related to a problem? Please describe.**

I'm using MetalLB to provide external IP addresses for `LoadBalancer` services. I like to be in control of my `LoadBalancer` services. Therefore, I really like using the `loadBalancerIP` to force which IP that MetalLB assigns. This is not possible with the current chart, but it should be really easy to fix.

**Describe the solution you'd like**
Simply accept a `service.loadBalancerIP` field through values and set it on the service (not the headless one).

**Comment by miguelaeh** [comment]
Hi @anton-johansson ,
Thank you for the request we will add it when we have the chance

**Comment by anton-johansson** [comment]
Great, thanks for the quick response. I see you already created a PR for it. :+1:
