### ISSUE TITLE
stable/concourse-0.5.0  "unknown capability \"CAP_AUDIT_READ\""

### ISSUE THREAD

**Issue by mf-eri** [helm/charts#2097]
BUG REPORT:

Chart : stable/concourse-0.5.0

https://concourse.ci/hello-world.html

Tried Hello World example above, but receives: 
runc create: exit status 1: container_linux.go:264: starting container process caused "unknown capability \"CAP_AUDIT_READ\""

**Comment by matthope** [comment]
From the error message, this may have a similar root-cause as https://github.com/concourse/concourse/issues/488

**Comment by nexeck** [comment]
Yes, this is a problem with old Kernels and Containers which need to run with privileged and this special capability.
Your Kernel needs to support: CAP_AUDIT_READ: http://man7.org/linux/man-pages/man7/capabilities.7.html
