### ISSUE TITLE
[bitnami/redmine] enabling mailReceiver issue

### ISSUE THREAD

**Issue by ranganathabrr** [helm/charts#20979]
**Describe the bug**
I can able to create redmine application and its working, adding to this i am trying with create a task from email functionality. I set up i map host name and configuration stuff. If I make
 mailReceiver 
       enabled:true
throwing some error. 

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CronJob.spec.jobTemplate.spec.template.spec): unknown field "concurrencyPolicy" in io.k8s.api.core.v1.PodSpec, ValidationError(CronJob.spec.jobTemplate.spec.template.spec): unknown field "imagePullPolicy" in io.k8s.api.core.v1.PodSpec]

**Version of Helm and Kubernetes**:
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

**What happened**:
mailReceiver
   enabled:true
returns an error.

**What you expected to happen**:
It should create an issue.

**Comment by dani8art** [comment]
Hi @ranganathabrr ,

Thank you for reporting this issue, I've just created a PR in order to fix it.

Regards.
