### ISSUE TITLE
[ incubator/fluentd-cloudwatch ] inconsistent logs upload to cloudwatch 

### ISSUE THREAD

**Issue by rishiraaz** [helm/charts#20974]
**Describe the bug**
We have noticed that the logs upload to cloudwatch is very inconsistent, some time logs are uploaded, some times not. The issue keeps on happening on different nodes with different set of pods.

**Version of Helm and Kubernetes**: 
Kubernetes: 1.15.7 (issue has been noticed on 1.14.8 too)
Helm version: 2.14.3
**Which chart**:
incubator/fluentd-cloudwatch 

**What happened**:
We have noticed that the logs upload to cloudwatch is very inconsistent, some time logs are uploaded, some times not. The issue keeps on happening on different nodes with different set of pods.

**What you expected to happen**:
There should be consistency in logs upload.

**How to reproduce it** (as minimally and precisely as possible):
We have simply installed the chart, there are hardly any changes to the default values file.

**Anything else we need to know**:

**Comment by johnzheng1975** [comment]
Not sure this is caused by client side bottleneck, or server side bottleneck.
If it is server side bottleneck,  can we try forward logs to different cloudwatch group (or ask AWS support to improve).
Or we can use fluend file buffer to make logs forward consistence.

**Comment by rishiraaz** [comment]
@johnzheng1975 one suspect is cloudwatch putevents has a limit of 1 mb per sec but not sure on that.
I have made below config change, will check how this goes.
enable_watch_timer false
 enable_stat_watcher true
