### ISSUE TITLE
mongodb-replicaset -- Backup to S3

### ISSUE THREAD

**Issue by jtsoftex** [helm/charts#20986]
Hi, Is there any possibility we can add a feature like taking backup of all mongo db's and upload it on s3, may be using some k8 crons ?

Also, if not possible here, anyone know how can I achieve it on k8 ?

**Comment by rafariossaa** [comment]
Hi,
   Sorry, but for now that is not on our roadmap.
   You can launch other mongodb container (or get into one of the pods) and there use the mongo tools to do the [backup](https://docs.mongodb.com/manual/tutorial/backup-and-restore-tools/).

**Comment by rafariossaa** [comment]
Hi again,
We have this [guide]( https://docs.bitnami.com/tutorials/backup-restore-bitnami-deployments-velero/) to use velero for backing up a WP, maybe you can use it to do a similar thing for mongodb.
