### ISSUE TITLE
Add ahmed-mez as Trusted Collaborator

### ISSUE THREAD

**Issue by ahmed-mez** [helm/charts#20993]
Hello,

I'm member of the Datadog team that maintains the stable/datadog chart.

May I please be added as a Trusted Collaborator to take part in the PR lifecycle? (Similar to #18810 .)

Thanks!

cc @clamoriniere @CharlyF

**Comment by irabinovitch** [comment]
Approved from Datadog.

**Comment by irabinovitch** [comment]
Approved from Datadog.

**Comment by irabinovitch** [comment]
Approved from Datadog.

**Comment by mattfarina** [comment]
@ahmed-mez you should have an invitation waiting for you.

**Comment by ahmed-mez** [comment]
Hi @mattfarina 
I didn't receive any invitation, could you please try to send it again?
Thanks!

**Comment by irabinovitch** [comment]
@mattfarina 👋 would love a hand here.

**Comment by mattfarina** [comment]
There is a pending invitation, that has not yet been accepted on this.

**Comment by ahmed-mez** [comment]
Found it, thanks!
