### ISSUE TITLE
Storage Class is a moving target

### ISSUE THREAD

**Issue by TerraTech** [helm/charts#210]
I'm currently running CoreOS-1185.3.0 and hyperkube-v1.4.5_coreos.0

The charts are unable to start due to the PVCs not being able to claim the PVs.  This is due to the 'volume.alpha.kubernetes.io/storage-class' plugin not being available.  Also, there is no implied promotion from 'alpha' ==> 'beta' level.  From the code, it would seem that 'alpha' support will be dropped from the code in:
https://github.com/kubernetes/kubernetes/pull/29006/files#diff-19005c632cb9e1783ab407d1c09af709R1410

Are there any objections for a PR with a mass search-n-replace to upgrade the storage class annotation to beta level?  Otherwise, if backwards compatibility is a desire, then annotations like this should be parameterized and set it in a global config with a reasonable default.

In all honesty, I'd like to have the option to drop the storage-class annotation entirely and let it pull from our default persistent storage pool.

**Comment by lachie83** [comment]
Let's move them all to beta

**Comment by TerraTech** [comment]
@lachie83 PR #213 created

**Comment by prydonius** [comment]
@TerraTech @lachie83 see https://github.com/kubernetes/charts/issues/116#issuecomment-261433060

Would you be able to update #213 with the information from that comment? Also any objections to closing this issue in favour of #116?

**Comment by TerraTech** [comment]
@prydonius In light of https://github.com/kubernetes/charts/issues/116#issuecomment-254975483 and the comments about cluster portability, I have no problem with having https://github.com/kubernetes/charts/issues/116 supercede this, as well as #213 being closed out.  That PR was just a fast way to fixup the alpha. to beta. StorageClass problem we were having and we surmised that others were hitting it too.  I would rather see this solved in a portable way since Charts are going to be installed in just about every environment you can think of.  Ours is a bare-metal cluster.

**Comment by prydonius** [comment]
Great, I've closed out this and #213 for the time being - thanks for bringing up the issue @TerraTech - if you have the time to implement the suggested change in #116, that would be great, but if not I'll try to get round to it within the next week.
