### ISSUE TITLE
Add vboulineau as Trusted Collaborator

### ISSUE THREAD

**Issue by vboulineau** [helm/charts#21003]
Hello,

I've recently joined the Datadog team that maintains the stable/datadog chart.

May I please be added as a Trusted Collaborator to take part in the PR lifecycle?

Thanks!

cc @clamoriniere

**Comment by irabinovitch** [comment]
Approved from Datadog

**Comment by irabinovitch** [comment]
@mattfarina 👋 would love a hand here.

**Comment by mattfarina** [comment]
Invited. Sorry for the delay

**Comment by vboulineau** [comment]
Thank you!
