### ISSUE TITLE
[incubator/msyqlha] Slave containers fail due clone-mysql failing busy resource

### ISSUE THREAD

**Issue by Cagrosso** [helm/charts#21011]
**Describe the bug**
With no additional configuration of the chart, slave pods fail after roughly 20 minutes of deploying mysqlha to a cluster due to /var/lib/mysql/mysql/... resource being busy

**Version of Helm and Kubernetes**:
kubernetes 1.15.5
rancher 2.3.5
helm v2.14.3-rancher1

**Which chart**:
incubator/mysqlha

**What happened**:

<img width="640" alt="Screen Shot 2020-02-25 at 10 46 57 AM" src="https://user-images.githubusercontent.com/5542857/75268590-af555380-57c5-11ea-8a8b-fe3152eaa70d.png">

**What you expected to happen**:
I expect the unmodified helm chart to deploy and run on the cluster.

**How to reproduce it** (as minimally and precisely as possible):
Deploy helm chart to a cluster with no modifications.

**Anything else we need to know**:

**Comment by pentago** [comment]
a PVC/PV issue?
