### ISSUE TITLE
Concourse workers should be restarted if their file system panics

### ISSUE THREAD

**Issue by william-tran** [helm/charts#2104]
**FEATURE REQUEST**

Concourse users have 3 baggageclaim FS drivers to choose from: `naive`, `btrfs`, or `overlay`. For any serious deployment of Concourse, `naive` can't be used, and `overlay` might not be available on the Linux kernel that your cluster is running (see https://github.com/concourse/concourse/issues/1230). `btrfs` is not rock-solid but might be the only choice for some users. 

When the worker's file system panics, it switches to read only mode, resulting in errors that look like 

```
runc create: exit status 1: container_linux.go:264: starting container process caused "process_linux.go:261: applying cgroup configuration for process caused \"mkdir /sys/fs/b1e5491a-451b-4a6c-57b7-78caa9de79b8: read-only file system\""
```

There is currently no liveness check, but one could check the ability to write to the FS, and if that fails, restart the pod. This also depends on the ability to get a worker to run again after restart, see https://github.com/kubernetes/charts/issues/2103

**Comment by adarshaj** [comment]
Just want to make a note here that #2109 did not work for me (twice so far), I had to explicitly do the scaling to 0 then prune with worker using `fly` and scale back workers to 3.
