### ISSUE TITLE
[stable/spinnaker] unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"

### ISSUE THREAD

**Issue by rrneuron** [helm/charts#21054]
**Describe the bug**
helm install spnkr stable/spinnaker --timeout 300s
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]
**Version of Helm and Kubernetes**:
kubernetes/minikube version: v1.7.3
Helm:
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

**Which chart**:
Stable/Spinnaker

**What happened**:
When i try to install this chart with the following command I get the error I mentioned. values.yaml is unchanged from what I downloaded from github repo.
 helm install spnkr-01 -f values.yaml stable/spinnaker --timeout 300s

**What you expected to happen**:
I expected to have it run with no errors.

**How to reproduce it** (as minimally and precisely as possible):
Install minikube with 
$ minikube config get cpus
4
$ minikube config get memory
4096

Install helm
run the install command.

**Anything else we need to know**:
n/a

**Comment by karlkfi** [comment]
AFAICT this is because of the minio dependency.
The minio chart has an if statement to check which version to use, but it seems to not work properly.
https://github.com/helm/charts/blob/master/stable/minio/templates/_helpers.tpl#L48-L54

**Comment by karlkfi** [comment]
Correction: both minio and redis do the same thing, and both have been moved to the new bitnami helm repo. So Spinnaker probably needs to be updated to not depend on these stale ones.

```
$ helm template spinnaker . --dependency-update | grep apps/v1beta2 -A3 -B1
# Source: spinnaker/charts/minio/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spinnaker-minio
--
--
# Source: spinnaker/charts/redis/templates/redis-master-statefulset.yaml
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: spinnaker-redis-master
```

**Comment by karlkfi** [comment]
It looks like `helm template` doesn't have any capabilities metadata from a K8s cluster. So it defaults to the older version, but i would expect helm install to work...

Other charts, like cluster-autoscaler, have a variable to override this:
```
# Allow overridding the .Capabilities.KubeVersion.GitVersion (useful for "helm template" command)
kubeTargetVersionOverride: ""
```
https://github.com/helm/charts/blob/master/stable/cluster-autoscaler/values.yaml#L202-L203

The stable minio & redis charts here do not have this.

It looks like the latest minio & redis charts from bitnami no longer fall back to v1beta2.
https://github.com/bitnami/charts/tree/master/bitnami/redis
https://github.com/bitnami/charts/tree/master/bitnami/minio

**Comment by karlkfi** [comment]
Bonus problem:
Even if you update the dependencies to use the newer bintami redis & minio AND update the values.yaml to match the reverse incompatible chart changes AND update the halyward config to match the new values...

It's still installing an old version of halyard which uses apps/v1beta2 when creating the Spinnaker deployment in the `spinnaker-install-using-hal` job. So Halyard probably also needs updating.

**Comment by karlkfi** [comment]
This issue should be fixed by one of these dependency update PRs:
https://github.com/helm/charts/pull/20917
https://github.com/helm/charts/pull/18545

Unfortunately, I don't think either of them works as-is, due to chart changes that require value changes that require spinnaker chart changes...

I'm tempted to make my own PR, but they don't seem to be moving very fast...

@viglesiasce Is this something you can look into?

**Comment by JuergenSimon** [comment]
Any new on this? This is a complete showstopper!

**Comment by rrneuron** [comment]
Please let me know if this issue has moved to a better state ?

**Comment by karlkfi** [comment]
Two PRs should have fixed this:
https://github.com/helm/charts/pull/20917 (changed dependencies)
https://github.com/helm/charts/pull/21987 (bumped versions)

To pull them, you'll need to specify version 2.0.0-rc1, 2.0.0-rc2, or 2.0.0-rc3.
No official version release has been cut, and these changes are reverse incompatible.

**Comment by brunobertechini** [comment]
Auto closing an issue that was not fixed is really weird.

Still facing this issue with helm3 and stable/spinnaker clean install

**Comment by seperman** [comment]
I agree with @brunobertechini 
The stale robot thing is lame.
All I'm doing is `helm install minio stable/minio` and get this error. So what are we supposed to do exactly to get it installed?

**Comment by seperman** [comment]
Is this how it is supposed to work for now? `helm install minio stable/minio --version "v2.0.0-rc3"`
When I run that, it gives me `Error: failed to download "stable/minio" (hint: running `helm repo update` may help)`

**Comment by seperman** [comment]
@karlkfi  could you please post how to set the version to `v2.0.0-rc3` that you have mentioned?

**Comment by karlkfi** [comment]
Should be: 
```
helm install stable/spinnaker --namespace spinnaker --version 2.0.0-rc9
```

Latest version can be seen on master: https://github.com/helm/charts/blob/master/stable/spinnaker/Chart.yaml#L4

**Comment by jgworks** [comment]
I am having the same issue outlined here. I tried using `--version 2.0.0-rc9` and `--version 2.1.0-rc.1` but I get the error below:

```
$ helm install -n my-spinnaker spinnaker stable/spinnaker --version 2.0.0-rc9

Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
```

**Comment by somyagarg94** [comment]
Is there any update on this? I am having the same issue when using `--version 2.0.0-rc9`
`✗ helm install spinnaker stable/spinnaker --version 2.0.0-rc9  -f values.yaml -n spinnaker
Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled`

**Comment by lsarangi1** [comment]
Any updates on this ? I'm seeing the same issue..

helm install cm-spinnaker stable/spinnaker --timeout 600s --namespace spinnaker --version 2.1.0-rc.1
Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled

**Comment by lsarangi1** [comment]
Found a workaround for this issue.Posting here for anyone else facing this. 

`git clone https://github.com/helm/charts.git
cd charts/stable/spinnaker/


update the minio chart version to 5.0.33 in requirements.yaml 

helm dependency update
helm install spinnaker . --timeout 15m --namespace spinnaker`

**Comment by giotab** [comment]
I get the error as well with a new installation.
Does anyone have a final command to successfully install spinnaker?

**Comment by gauravkhare** [comment]
> Found a workaround for this issue.Posting here for anyone else facing this.
> 
> `git clone https://github.com/helm/charts.git
> cd charts/stable/spinnaker/
> 
> update the minio chart version to 5.0.33 in requirements.yaml
> 
> helm dependency update
> helm install spinnaker . --timeout 15m --namespace spinnaker`

Is this working for anyone else?

**Comment by hiddenrebel** [comment]
it's deprecated as Nov 13, 2020
https://github.com/helm/charts/tree/master/stable/spinnaker
