### ISSUE TITLE
[stable/mariadb] helm update removes service from live services

### ISSUE THREAD

**Issue by rjksn** [helm/charts#21052]
**Describe the bug**

When running helm install the database service is created.

    $ helm install database stable/mariadb -f ./mariadb-production.yaml --set rootUser.password='...' --set replication.password='...'

When running helm update the service disappears from Kubernetes but helm tells me it was successful. 

    $ helm upgrade database stable/mariadb -f ./mariadb-production.yaml
    > Release "database" has been upgraded. Happy Helming!

**Version of Helm and Kubernetes**:

Helm
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.8"}

Kubectl
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

DO
Dashboard v2.0.0-beta8+0.g4275399

**Which chart**:

stable/mariadb

**What happened**:

The service was deleted from kubernetes

**What you expected to happen**:

The service gets updated with the new settings.

**How to reproduce it** (as minimally and precisely as possible):

Install the chart, "upgrade" the chart. 

**Anything else we need to know**:

Digital Ocean

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue

```
 1 ❯ helm upgrade database .
Release "database" has been upgraded. Happy Helming!
NAME: database
LAST DEPLOYED: Fri Feb 28 12:27:54 2020
NAMESPACE: default
STATUS: deployed
REVISION: 2
NOTES:
Please be patient while the chart is being deployed

Tip:

  Watch the deployment status using the command: kubectl get pods -w --namespace default -l release=database

Services:

  echo Master: database-mariadb.default.svc.cluster.local:3306
  echo Slave:  database-mariadb-slave.default.svc.cluster.local:3306

Administrator credentials:

  Username: root
  Password : $(kubectl get secret --namespace default database-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)

To connect to your database:

  1. Run a pod that you can use as a client:

      kubectl run database-mariadb-client --rm --tty -i --restart='Never' --image  docker.io/bitnami/mariadb:10.3.22-debian-10-r27 --namespace default --command -- bash

  2. To connect to master service (read/write):

      mysql -h database-mariadb.default.svc.cluster.local -uroot -p my_database

  3. To connect to slave service (read-only):

      mysql -h database-mariadb-slave.default.svc.cluster.local -uroot -p my_database

To upgrade this helm chart:

  1. Obtain the password as described on the 'Administrator credentials' section and set the 'rootUser.password' parameter as shown below:

      ROOT_PASSWORD=$(kubectl get secret --namespace default database-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)
      helm upgrade database stable/mariadb --set rootUser.password=$ROOT_PASSWORD
  master → origin {1}  ~/projects/bitnami-charts/upstreamed/mariadb                                   12:27:57  jsalmeron
❯ kubectl get svc
NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
database-mariadb         ClusterIP   10.102.26.173   <none>        3306/TCP   2m3s
database-mariadb-slave   ClusterIP   10.100.43.246   <none>        3306/TCP   2m3s
kubernetes               ClusterIP   10.96.0.1       <none>        443/TCP    17m
```

I don't see a reason why the service object would disappear. Maybe you mean the containers that disappear?
