### ISSUE TITLE
[sable/nextcloud] cannot access web UI when deployed on minikube

### ISSUE THREAD

**Issue by spotlesscoder** [helm/charts#21073]
**Describe the bug**
Nextcloud is not locally accessible via the browser

**Version of Helm and Kubernetes**:
minikube version: v1.7.3
commit: 436667c819c324e35d7e839f8116b968a2d0a3ff

helm version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

**Which chart**:
stable/nextcloud

**What happened**:
```
sudo minkube start --vm-driver=none
helm install nextcloud stable/nextcloud
```
Looked up the pod IP through minikube dashboard.
IP was 172.17.0.4.
Accessed this via HTTP in the browser
The following error message is shown
![image](https://user-images.githubusercontent.com/25173078/75383668-b0c17180-58d4-11ea-8f50-27efe3a8a594.png)

**What you expected to happen**:
It should work in the default deployment

**How to reproduce it** (as minimally and precisely as possible):
See "what happened"

**Comment by skidpa** [comment]
nextcloud will listen for trusted connections on a host. so you'll need to specify that host in the values.yaml file (nextcloud.host)
so `helm install nextcloud stable/nextcloud --set nextcloud.host=172.17.0.4`
although setting a hostname would probably be better

**Comment by CodingSpiderFox** [comment]
Can't it determine the IP and trust it automatically by default?

**Comment by skidpa** [comment]
not as far as i know. guess the reasoning would be something along the lines of that access to the cloud would be through some fqdn or if someone decided to just run it locally something along the lines of nextcloud.local

**Comment by CodingSpiderFox** [comment]
Anyway, your fix works for me, thanks :)
