### ISSUE TITLE
[stable/chart/airflow] airflow.cfg configs are not updated.

### ISSUE THREAD

**Issue by sk2991** [helm/charts#21077]
**Describe the bug**
Postgress connection is not applied in the airflow.cfg, I see the airflow.cfg is still having the default values, env has the values supplied through values.yml file.
How to create/edit the airflow.cfg so that the configs are present in the file on the node and in the UI?
I have exported the webUI using Nodeport

**Version of Helm and Kubernetes**:
Kubernetes:1.11.5
Helm:v2.16.1

**Which chart**:
Airflow

**How to reproduce it** (as minimally and precisely as possible):
helm install --namespace "airflow" --name "airflow" -f values.yaml .
kubectl exec -it <web_container> sh
cat airflow.cfg
env | grep -i postgres

**Comment by seifghazi** [comment]
Hey @SharanReddyK, any luck with this?

**Comment by SinaRex** [comment]
Yes, I have the same problem!

**Comment by PierreC1024** [comment]
You can override airflow.cfg  configs to define environment variables in your pods with [this syntax](https://airflow.readthedocs.io/en/1.9.0/configuration.html#setting-configuration-options).

So, you for example, if you want to override the UI navbar color your values has to be:
```yaml
airflow: 
  config:
    AIRFLOW__WEBSERVER__NAVBAR_COLOR: '#0022b8'
```

**Comment by seifghazi** [comment]
Thanks for the quick reply @PierreC1024 . I tried deploying with the following:
```
config:
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 60
```
The config remained at the default time of 300 seconds. 

Any tips as to how to move forward with this?

**Comment by PierreC1024** [comment]
How do you know that the config remained at the default time ? If you read in the UI, it is the value in the airflow.cfg not the current value. 

![image](https://user-images.githubusercontent.com/20433878/78154727-e3630a80-743c-11ea-9ae9-c3bacadce533.png)

**Comment by seifghazi** [comment]
I ssh'ed into the pod itself and checked the config value.
![image (1)](https://user-images.githubusercontent.com/36180081/78155602-ab8f9f00-740b-11ea-9598-baa5c619b47a.png)

**Comment by seifghazi** [comment]
I also checked the logs for the pod and it showed that it was syncing from the dags dir every 5 minutes (ie 300 secs)

**Comment by PierreC1024** [comment]
Sorry, it works for me for all my configs. 

As I mentioned the config file is not override but you can see the environment variable in your pods with the value you specified. These values are take into account when the airflow commands are running as mentioned in the airflow documentation.

**Comment by SharanReddyK** [comment]
@seifghazi - Configs in airflow WebUI - /usr/local/airflow/airflow.cfg cannot be override. 
If you scroll down, you will see a Running Configuration section that has all the values you have exposed through the config section of values.yml.
