### ISSUE TITLE
Grafana nodeselector issue

### ISSUE THREAD

**Issue by doryanmzr** [helm/charts#21090]
**Describe the bug**
When I deploy the helm chart of grafana using helm, it schedule the pod on windows node although i set the nodeselector to linux in values.yaml

```shell
nodeSelector: {"beta.kubernetes.io/os":"linux"}

```

**Version of Helm and Kubernetes**:
kubectl version
```shell
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
helm version
```shell
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

**Which chart**:
grafana

**What happened**:
grafana was scheduled on windows node

**What you expected to happen**:
grafana should be scheduled on linux node

**How to reproduce it** (as minimally and precisely as possible):
```shell
helm install grafana stable/grafana
```

**Comment by maxisam** [comment]
@doryanmzr do you figure out how to use it correctly?
use matchExpressions?

**Comment by doryanmzr** [comment]
@maxisam , it's working now with nodeSelector: {"beta.kubernetes.io/os": "linux"}
try to deploy the latest chart
