### ISSUE TITLE
When S3 enabled and Minio disabled, Helm install times out

### ISSUE THREAD

**Issue by techd1984** [helm/charts#21102]
Here is the changes in default values.yaml

minio:
  enabled: false
  image:
    tag: RELEASE.2018-08-25T01-56-38Z
  serviceType: ClusterIP
  accessKey: spinnakeradmin
  secretKey: spinnakeradmin
  bucket: "spinnaker"
  nodeSelector: {}

# AWS Simple Storage Service
s3:
  enabled: true
  bucket: "abcdef"
  rootFolder: "front50"
  #region: "us-east-1"
  # endpoint: ""
  # accessKey: ""
  # secretKey: ""
  assumeRole: "arn:aws:iam::123456789:role/SpintestInt"
  ## Here you can pass extra arguments to configure s3 storage options
  #extraArgs: []
  #  - "--path-style-access true"

helm install spinnaker -f values.yaml stable/spinnaker -n spinnaker
Error: failed post-install: timed out waiting for the condition.
If S3 and Minio both leave enabled: true then it installs fine.

**Comment by techd1984** [comment]
Helm Install times out but leaves 2 pods running in the namespace
spinnaker$ kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
spinnaker-redis-master-0        1/1     Running   0          9m36s
spinnaker-spinnaker-halyard-0   1/1     Running   0          9m36s

**Comment by ysennoun** [comment]
When I active TLS for Minio, I got the same error:
"Error: failed post-install: timed out waiting for the condition"
