### ISSUE TITLE
[stable/cert-manager] install fails on kubernetes v1.17.0

### ISSUE THREAD

**Issue by c4m4** [helm/charts#21107]
**Version of Helm and Kubernetes**:
helm: v2.16.1
kubernetes: v1.17.0

**Which chart**:
stable/cert-manager

**What happened**:
helm install stable/cert-manager --name cert-manager --namespace kube-system --version v0.6.0 --set createCustomResource=true
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1"

**What you expected to happen**:
Installation without errors

**How to reproduce it** (as minimally and precisely as possible):
create a kubernetes cluster version v1.17.0

**Anything else we need to know**:

kubectl proxy
Starting to serve on 127.0.0.1:8001

 curl -s localhost:8001/ | grep "apps"  
    "/apis/apps",
    "/apis/apps/v1",

From my point of view, v1beta1 was removed but 

helm fetch --untar stable/cert-manager
grep -Rn 'apps/v1beta1'  cert-manager
cert-manager/webhook/templates/deployment.yaml:1:apiVersion: apps/v1beta1
cert-manager/charts/webhook/templates/deployment.yaml:1:apiVersion: apps/v1beta1
cert-manager/templates/deployment.yaml:1:apiVersion: apps/v1beta1

**Comment by ppwfx** [comment]
encountered the issue as well
