### ISSUE TITLE
Where are Helm 3 charts going to be stored?

### ISSUE THREAD

**Issue by AceHack** [helm/charts#21100]
I see

> Status of the Project
> Similar to the Helm 2 Support Plan, this GitHub project has begun transition to a 1 year "maintenance mode" (see Deprecation Timeline below). Given the deprecation plan, this project is intended for apiVersion: v1 Charts (installable by both Helm 2 and 3), and not for apiVersion: v2 charts (installable by Helm 3 only).
> 

So where is the "new" location for Helm 3 charts?

Thanks.

**Comment by AceHack** [comment]
Anyone know?

**Comment by AceHack** [comment]
Bump

**Comment by zanhsieh** [comment]
@AceHack 
Short answer: distributed.
https://hub.helm.sh/charts

**Comment by codiophile** [comment]
The README should really be more clear about this. When something is deprecated, you're normally pointed to what you're supposed to use instead. I definitely think that each helm chart should have its own repository to make maintenance easier, but I don't see any effort being made to point users to the corresponding v2 chart. In fact, it seems like in most cases there is no corresponding v2 chart, nor is there an alternative v1 chart hosted elsewhere.

Apart from the `stable` charts, the hub seems to mostly have charts by vendors with the purpose of bringing people into their eco systems. It seems like some open source projects have their own official charts, but most of the time `stable` seems to be the only neutral and most official looking chart.

On Docker Hub it is very easy to identify official images. I think a similar system needs to be established on Helm Hub, before de-listing the `stable` repository. There should also be a clear migration path for chart owners in this repository, to convert their charts to official Helm charts. On Docker Hub, official images are in the root of the repository. I don't know how easy that would be to implement for Helm Hub, but it seems advantageous to use the same pattern as Docker Hub.
