### ISSUE TITLE
[stable/nginx-ingress] Deployments are targeting wrong pods

### ISSUE THREAD

**Issue by calind** [helm/charts#21111]
**Describe the bug**
The controller and default-backend deployments are targeting the same pods (eg. the controller is targeting both the controller pods and default backend pods. The same goes for the default-backend deployment).

They are both missing the `component` label from their respective `.spec.selector.matchLabels`

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by rslinckx** [comment]
Both 1.34.0 and 1.34.1 are presenting the issue, resulting in no apparent failure, but making the service unavailable because no pods are matching the selector. That happens even when setting useComponentLabel: false although this was supposed to preserve old behavior.
