### ISSUE TITLE
Ran install, everything seems up and running but can't access in browser

### ISSUE THREAD

**Issue by ghost** [helm/charts#21126]
I ran the install, everything seems fine, but can't access in browser, as a test I tried the jenkins/stable which did work and was accessible but there was an extrta port forward bit which made it work, I wonder if this is missing?

`helm install drupal stable/drupal 
NAME: drupal
LAST DEPLOYED: Fri Feb 28 10:42:14 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
*******************************************************************
*** PLEASE BE PATIENT: Drupal may take a few minutes to install ***
*******************************************************************

1. Get the Drupal URL:

  You should be able to access your new Drupal installation through

  http://drupal.local/

2. Login with the following credentials

  echo Username: user
  echo Password: $(kubectl get secret --namespace default drupal -o jsonpath="{.data.drupal-password}" | base64 --decode)
`
This step made jenkins work:
`2. Get the Jenkins URL to visit by running these commands in the same shell:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/component=jenkins-master" -l "app.kubernetes.io/instance=myjenkins" -o jsonpath="{.items[0].metadata.name}")
  echo http://127.0.0.1:8080
  **kubectl --namespace default port-forward $POD_NAME 8080:8080**`

I'm a drupal developer but new to kubernetes/helm, strange jenkins worked out of the box, this didnt, thanks for any help/advice.

**Comment by andresbono** [comment]
Hi @timrabbetts, the Drupal chart deploys a service of type LoadBalancer:
https://github.com/helm/charts/blob/958e01a4d70d8739003c24dd132d47ec2d359b46/stable/drupal/values.yaml#L130-L135

You should be able to access it through ports 80 or 443.

If you want to do something similar to what you did for Jenkins and `port-forward`, you can do:

```
export POD_NAME=$(kubectl get pods --namespace default -l "app=drupal" -o jsonpath="{.items[0].metadata.name}")

echo URL: http://127.0.0.1:8080
echo Username: user
echo Password: $(kubectl get secret --namespace default drupal -o jsonpath="{.data.drupal-password}" | base64 --decode)

kubectl --namespace andresbono port-forward $POD_NAME 8080:80
```

Let us know if it works for you.

**Comment by timrabbetts** [comment]
I tried again, fresh install tried port stuff still not loading in browser, could you confirm that you run this command and then access drupal.local in browser and the site is there?
helm install drupal stable/drupal
also nothing running on port 80 as far as I can see:
tcp        0      0 127.0.0.1:39037         0.0.0.0:*               LISTEN      850/kubectl         
tcp        0      0 127.0.0.1:45003         0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      1585/kubectl        
tcp        0      0 0.0.0.0:8084            0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN      -                   
tcp6       0      0 ::1:8080                :::*                    LISTEN      1585/kubectl        
tcp6       0      0 ::1:631                 :::*                    LISTEN      -                   
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           6692/chrome --type= 
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           6652/chrome         
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           6652/chrome         
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           6692/chrome --type= 
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           6692/chrome --type= 
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -                   
udp        0      0 127.0.0.53:53           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:631             0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:53234           0.0.0.0:*                           -                   
udp6       0      0 :::5353                 :::*                                -                   
udp6       0      0 :::35875                :::*                                -    
thanks for your help

**Comment by timrabbetts** [comment]
kube dashboard is all green it looks like its all up and running just the port stuff isnt working or maybe the domain isnt setup right? I tried adding 127.0.0.1 drupal.local to /etc/hosts. OH WOW ITS WORKING so now I edited my /etc/hosts and change browser to http://drupal.local:8080/ I have a site loading.  So my question is should I need to do all this, do the docs need updating amd I doing something wrong?  Thanks again

**Comment by timrabbetts** [comment]
If I stop the forward command it doesnt load.

**Comment by timrabbetts** [comment]
I've got this working now consistently, written a bash script however, I really dont understand why I need to do this surely the idea is i run command [helm install tim-rabbetts bitnami/drupal] then go to drupal.local in browser and its there, why do I need to do this work around? `#!/bin/bash
export POD_NAME=$(kubectl get pods --namespace default -l "app=drupal" -o jsonpath="{.items[0].metadata.name}")

echo URL: http://127.0.0.1:8080
echo Username: user
echo Password: $(kubectl get secret --namespace default drupal -o jsonpath="{.data.drupal-password}" | base64 --decode)

kubectl --namespace default port-forward $POD_NAME 8080:80`
