### ISSUE TITLE
How to supply Extra Arguements to the stable/cluster-autoscaler?

### ISSUE THREAD

**Issue by pluttrell** [helm/charts#2112]
For the `stable/cluster-autoscaler` chart, how do you supply additional arguments to the container command?

In specific I want to add `--stderrthreshold=info` because this chart isn't logging anything by default (and isn't working). I'm hoping to get it to appear as [these docs](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md) suggest:

```
         command:
            - ./cluster-autoscaler
            - --stderrthreshold=info
```

The [chart docs](https://github.com/kubernetes/charts/tree/master/stable/cluster-autoscaler) does list `extraArgs`, however when I tried the following in my `values.yaml` supplied to the `helm install` command:

```
extraArgs: 
  - --stderrthreshold=info
```

The container failed to start because it generated this (other items omitted for brevity):

```
./cluster-autoscaler
--0=--stderrthreshold=info
```

**Comment by FilipNikolovski** [comment]
You can supply extra args like this:

```
extraArgs:
  key: "val"
```

Example:

```
extraArgs:
  stderrthreshold: "info"
  skip-nodes-with-local-storage: "false"
  skip-nodes-with-system-pods: true
```

**Comment by afirth** [comment]
This is really annoying, because if you specify e.g. `---set extraArgs={"foo":"bar", "baz":"xyz"}` you get --0=-foo=bar --1=-baz=xyz as @pluttrell says, and the container won't start.

As documented [here](https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/values.md#consider-how-users-will-use-your-values) the solution is to put the key before the `=`. e.g.

```
helm install \
  --name cluster-autoscaler \
  --set autoscalingGroups[0].name=worker.${K8S_NAME} \
  --set autoscalingGroups[0].maxSize=6 \
  --set autoscalingGroups[0].minSize=1 \
  --set awsRegion=us-east-1 \
  --set extraArgs.v=4 \
  --set extraArgs.stderrthreshold=info \
  --set extraArgs.expander=least-waste \
  --set image.tag=v1.1.1 \
  stable/cluster-autoscaler
```
results in

```
    Port:          8085/TCP
    Command:
      ./cluster-autoscaler
      --cloud-provider=aws
      --namespace=default
      --nodes=1:6:worker.superdupercluster
      --expander=least-waste
      --stderrthreshold=info
      --v=4
    State:          Running
```
