### ISSUE TITLE
[stable/redmine] Plugins installation

### ISSUE THREAD

**Issue by saine1991** [helm/charts#21122]
**Describe the bug**
Unable to install some plugins (example: redmine_contacts).

**Version of Helm and Kubernetes**:
helm: 2.16.1
kube: 15.3

**Which chart**:
stable/redmine

**What happened**:
I've created docker image basing on bitnami/redmine:4.1.0-debian-10-r0 with some plugins attached. 

Here is what I added to Dockerfile:
-------------------------------------------------------------------------------------------
COPY plugins /opt/bitnami/redmine/plugins
RUN apt-get update -y && apt-get install -y make gcc libmariadb-dev libpq-dev
RUN gem install ox -v '2.13.2' --source 'https://rubygems.org/'
RUN cd /opt/bitnami/redmine && bundle config unset deployment
RUN bundle install --gemfile=/opt/bitnami/redmine/Gemfile
-------------------------------------------------------------------------------------------

After deploying it to my k8s cluster I see these logs in redmine pod:
-------------------------------------------------------------------------------------------
nami    INFO  Initializing redmine
redmine INFO  Configuring Redmine database...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at redmine-mariadb:3306
mysql-c INFO  MySQL server listening and working at redmine-mariadb:3306
redmine INFO  Preparing Redmine environment...
redmine INFO  Generating new secret...
redmine INFO  Migrating database...
Error executing 'postInstallation': rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'bitnami_redmine.users' doesn't exist: SHOW FULL FIELDS FROM `users`...
-------------------------------------------------------------------------------------------

It looks like one of the plugins is trying to query on DB which is in migrating/creating phase.

Is it any way to handle this case? Disable it somehow? Or give it time to migrate DB before installing plugins?

**What you expected to happen**:
Install plugins without any errors and run stable redmine

**How to reproduce it** (as minimally and precisely as possible):
Install stable/redmine with redmine_contacts plugin

**Anything else we need to know**:
No

**Comment by andresbono** [comment]
Hi @saine1991, can you confirm that without adding the plugin, the deployment works fine in your environment?

Also, here you can find how we recommend installing plugins:

https://github.com/bitnami/bitnami-docker-redmine/issues/115#issuecomment-468231005

**Comment by saine1991** [comment]
Hello @andresbono, thanks for reply. Yes everything works fine without plugins.
I think my solution is quite similar to mentioned one, but still it doesn't resolve my problem.

**Comment by andresbono** [comment]
Hi @saine1991, can you share the plugins that you are trying to install so we can try to reproduce your issue?

**Comment by saine1991** [comment]
@andresbono,
https://www.redmine.org/plugins/redmine_contacts
