### ISSUE TITLE
[stable/prometheus-operator] disableCompaction not working

### ISSUE THREAD

**Issue by test-account-0** [helm/charts#21135]
**Describe the bug**
Option `prometheus.prometheusSpec.disableCompaction` is not working when creating new prometheus instance.

**Version of Helm and Kubernetes**:
It is probably not important.

**Which chart**:
stable/prometheus-operator

**What happened**:
`prometheus.prometheusSpec.disableCompaction` is not referenced in `templates/prometheus/prometheus.yaml` so there is not way for it to work (or am I missing some magic?)

**What you expected to happen**:
I wanted prometheus to have option ` --storage.tsdb.max-block-duration=2h`

**How to reproduce it** (as minimally and precisely as possible):
Just set `prometheus.prometheusSpec.disableCompaction` to `true` and check that prometheus doesn't have ` --storage.tsdb.max-block-duration=2h` as argument.

**Anything else we need to know**:
You can probably fix it by adding:
```
{{- if .Values.prometheus.prometheusSpec.disableCompaction }}
  disableCompaction: {{ .Values.prometheus.prometheusSpec.disableCompaction }}
{{- end }}
```
at line 30 of `templates/prometheus/prometheus.yaml`.

Also it should be added when thanos is configured as `values.yaml` says.

**Comment by gracedo** [comment]
Fixed by https://github.com/helm/charts/pull/21462
