### ISSUE TITLE
Expose the comment out values in `values.yaml`

### ISSUE THREAD

**Issue by gyliu513** [helm/charts#2116]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:
Charts which have some comment out parameters, such as stable/grafana, stable/prometheus etc.

**What happened**:
Take grafana as an example, it is defining the `storageClass` as comment out here https://github.com/kubernetes/charts/blob/master/stable/grafana/values.yaml#L87

```
    ## grafana data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
```

And the pvc just checking the logic as this https://github.com/kubernetes/charts/blob/master/stable/grafana/templates/pvc.yaml#L25-L31
```
{{- if .Values.server.persistentVolume.storageClass }}
{{- if (eq "-" .Values.server.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.server.persistentVolume.storageClass }}"
{{- end }}
```

If someone want to develop a dashboard for those helm charts and get values from `values.yaml`, it may got some problem for those comment out parameters, as those parameters cannot be got from the `values.yaml` and thus cannot be listed on the customized dashboard, this caused the end user cannot customize those parameters.

After some discussion with @prydonius , we want to remove the comment for the commented out parameters and expose them, so that they can be get by some 3rd party clients.

**What you expected to happen**:
Do not comment out parameters in `values.yaml` but always give some default parameters instead.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by scottrigby** [comment]
Noted during the Apps SIG call today. I said I'd cross-reference this somewhat related discussion: https://github.com/kubernetes/helm/issues/2399

**Comment by gyliu513** [comment]
@scottrigby this is a great feature, and can definitely help for this issue. But for now, I think we still need this to fix this issue soon. ;-)

**Comment by bgrant0607** [comment]
See also https://github.com/kubernetes/helm/issues/2431
