### ISSUE TITLE
[stable/jenkins] plugin folder as persistence volume

### ISSUE THREAD

**Issue by shurikg** [helm/charts#21167]
I'm using the stable helm chart in order to deploy it in my OCP environment.

I activate the persistence volume where jenkins save the **jenkins_home** folder.

I found that the helm chart define the plugin and plugin-dir folder as empty volume folder.

It's cause to download the plugins every time when pod is restarted.

How can I configure it that plugin dir will be also configured as persistence volume?

**Comment by maciejj04** [comment]
Hi

I've faced the same issue and as far as I'm aware it's not possible with the current version of the chart. I attempted to address this, so I've forked the repo and prepared fix to support the scenario You asked :)

If You're still interested please take a look at [these](https://github.com/maciejj04/charts/commit/c0184c93e2ed4b9d1851c559e0398d6c3fb9d168) changes

Any feedback is welcome :)
