### ISSUE TITLE
Secondary pod memory reaching limit at off peak. 

### ISSUE THREAD

**Issue by LachlanGardner1** [helm/charts#21161]
I have set a request of 4gb and limit of 8gb for my mongodb statefulset. Overnight the pod seems to be reaching the max limit until we start another environment on the same cluster at which the memory drops about 3gb. Not sure why the pod is using so much memory overnight off peak and dropping when another environment is started.

**Comment by javsalgar** [comment]
Hi,

Do the logs show any meaningful information? Did you perform any change in the configuration? Not sure if there is a maintenance setting/task that could explain that memory increase.
