### ISSUE TITLE
Weave scope chart

### ISSUE THREAD

**Issue by gyliu513** [helm/charts#2118]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:
Weave Scope, checkout more detail from https://console.bluemix.net/docs/containers/cs_cluster.html#bx_registry_other, with weave scope, we can visualizing Kubernetes cluster resources as follows:

![image](https://user-images.githubusercontent.com/4461983/30440505-5687163a-99a9-11e7-8f3b-ac5027bd65e6.png)

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by mattfarina** [comment]
Are you suggesting a chart to install Weave scope or a feature that lets you use Weave scope to visualize existing charts (in something like Monocular)?

**Comment by gyliu513** [comment]
I was suggesting a chart to install weave scope to view resources in kubernetes @mattfarina

**Comment by unguiculus** [comment]
See #1719.
