### ISSUE TITLE
[stable/airflow] git sync failure causes pod restart

### ISSUE THREAD

**Issue by javamonkey79** [helm/charts#21199]
**Describe the bug**
When the git sync process fails, the pod restarts. 

**Version of Helm and Kubernetes**:
```
➜  ~ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
helm/airflow

**What happened**:
The git sync container failed causing the pod to restart.

**What you expected to happen**:
I would expect the container to fail, but not restart the pod. 

**How to reproduce it** (as minimally and precisely as possible):
Set the refresh time to a low amount (we have ours on 1 minute); the error will likely show up in time, but, I'm not sure how to force it to happen.

**Anything else we need to know**:

This is the error from the log:
```
Tue Mar  3 01:37:34 UTC 2020
From https://gitlab.company.com/repo/my-dags
 * branch            dev        -> FETCH_HEAD
fatal: Unable to create '/dags/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

Here is a bit from the describe pod:
```
  git-sync:
    Container ID:  docker://4dbab7ff4df0be83e86d3115603b8071f97b78c0307c304de9d00f2c8d16c20e
    Image:         alpine/git:1.0.7
    Image ID:      docker-pullable://alpine/git@sha256:8f5659025d83a60e9d140123bb1b27f3c334578aef10d002da4e5848580f1a6c
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/git/git-sync.sh
    Args:
      https://123@gitlab.company.com/repo/my-dags.git
      dev
      /dags


      60
    State:          Running
      Started:      Mon, 02 Mar 2020 17:38:35 -0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    128
      Started:      Mon, 02 Mar 2020 17:16:32 -0800
      Finished:     Mon, 02 Mar 2020 17:38:34 -0800
    Ready:          True
    Restart Count:  46
```

**Comment by javamonkey79** [comment]
@hmike96 can you take a look at this one?

**Comment by javamonkey79** [comment]
> to the git-sync container in the two deployments again.

> I'm not using the workers, but I think you'd have to do the same thing to workers too.

> Hope this helps 😸

@cccs-cat001 thank you, but, I'm not sure how this solves the problem, can you elaborate a bit on how it fixes it? Sorry if it is obvious... 

Seems the issue is multiple containers are trying to access the same folder at the same time... it seems there needs to be a time wait in the git-sync script, but, maybe what you did fixes it... somehow?

**Comment by cccs-cat001** [comment]
Sorry, I guess I was mistaken. It didn't crash for me when I was testing it before commenting. I came in to work this morning and the pod had crashed 90 times. Sorry..

**Comment by javamonkey79** [comment]
> Sorry, I guess I was mistaken. It didn't crash for me when I was testing it before commenting. I came in to work this morning and the pod had crashed 90 times. Sorry..

That's ok, I appreciate the attempt :)

**Comment by kushmangal** [comment]
Any update on this issue?

**Comment by leoblanc** [comment]
I'm facing the same problem. The Airflow containers are restarted due to git-sync:

```
Containers:
  git-sync:
    Container ID:  docker://fa99661e68b7b8a66525bcc61c6f394d37c35bbcf65b25709ba239d3d00ad05f
    Image:         alpine/git:latest
    Image ID:      docker-pullable://alpine/git@sha256:23618034b0be9205d9cc0846eb711b12ba4c9b468efdd8a59aac1d7b1a23363f
    Port:          <none>
    Host Port:     <none>
    Command:
      /home/airflow/git/git-sync.sh
    Args:
      ssh://git@obfuscated.com/dags.git
      master
      /dags
      obfuscated.com
      22
      id_rsa
      60
    State:          Running
      Started:      Mon, 21 Dec 2020 19:09:05 -0300
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 21 Dec 2020 19:08:24 -0300
      Finished:     Mon, 21 Dec 2020 19:08:49 -0300
```

**Comment by kshrest** [comment]
I think [https://github.com/apache/airflow/blob/d25854dd413aa68ea70fb1ade7fe01425f456192/chart/templates/_helpers.yaml#L133](url) might be problematic. The git-sync user may not be able to read the private key. Perhaps set to 0644?
