### ISSUE TITLE
[stable/oauth2-proxy] Upgrade to 5.0+ to resolve security issue

### ISSUE THREAD

**Issue by jeremyolliver** [helm/charts#21198]
Hi, I noticed on the README at https://github.com/pusher/oauth2_proxy#security that there's an [open redirect vulnerability](https://github.com/pusher/oauth2_proxy/security/advisories/GHSA-qqxw-m5fj-f7gv) which requires running oauth2-proxy 5.0+ to resolve. The latest version in this chart to date runs 4.0 - I'd like to continue running the official stable helm chart that packages this, but it's important that this contains available security fixes. I'm not yet sure if I'll have time to submit a PR, so I wanted to file this to track the issue first.

**Comment by abdennour** [comment]
Not sure why these bots are closed many valid issues.

@jeremyolliver do you get any workaround ?
Many things are outdated when we check the [official software doc](https://oauth2-proxy.github.io/oauth2-proxy/auth-configuration)
- The image repo is now `quay.io/oauth2-proxy/oauth2-proxy`, and No more `quay.io/pusher/oauth2-proxy`
- processing `.Values.extraArgs` in `templates/deployment.yam` is outdated.
  Indeed, All args are now started by `-` not `--`.

....
