### ISSUE TITLE
Use operators for etcd and prometheus

### ISSUE THREAD

**Issue by F21** [helm/charts#212]
CoreOS just opensourced their operators for etcd and prometheus. When they become stable, it would be nice if the etcd and prometheus charts can be updated to use them.

Operators are extremely useful, because they encapsulate a lot of domain knowledge for operating a piece of software. For example, scaling etcd by adding an extra node will require some configuration and upgrading to the next version will require specific procedures.

See:
https://github.com/coreos/etcd-operator
https://github.com/coreos/prometheus-operator

**Comment by mgoodness** [comment]
I plan on digging into the Prometheus Operator with an eye toward making this happen.

**Comment by lachie83** [comment]
Great suggestion. I have an etcd-operator chart that I will submit in the next few days

**Comment by mgoodness** [comment]
I'm maintaining a prometheus-operator chart as part of my own [kube-prometheus-chart](https://github.com/mgoodness/kube-prometheus-chart) repo. Still very much a work-in-progress, as there's quite a bit I'd like to figure out in terms of operating (heh) the operator. My intent is to submit it here once it's more stable. Input welcome!

**Comment by seanknox** [comment]
Many of us love the operator pattern (and I think it's a great fit for etcd and prometheus in particular). Closing this as this is not an issue with any particular chart or helm.
