### ISSUE TITLE
FEATURE REQUEST: [MongoDB] Enable memory volume

### ISSUE THREAD

**Issue by jamorales-bsft** [helm/charts#2120]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

I would like to the ability to specify the medium for the mounted /data/db directory. We are currently using the medium Memory since we do not need persistent data with our mongodb deployment.

**Comment by bridgetkromhout** [comment]
Closing this old issue. This repo is deprecated; for any further questions on this topic, refer to https://github.com/bitnami/charts/tree/master/bitnami/mongodb.
