### ISSUE TITLE
[stable/fluentd] Error when autoscaling is enabled

### ISSUE THREAD

**Issue by jmthvt** [helm/charts#21201]
**Describe the bug**
When installing the chart with:

`helm install fluentd stable/fluentd  --set autoscaling.enabled=true`

I get the following error:

`error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec`

**Version of Helm and Kubernetes**:
```
$ helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```
EKS 1.14

**Which chart**:
https://github.com/helm/charts/tree/master/stable/fluentd

**What happened**:
Can't install chart with HPA enabled.

**What you expected to happen**:
Can install chart with HPA enabled.

**How to reproduce it** (as minimally and precisely as possible):

`helm install fluentd stable/fluentd  --set autoscaling.enabled=true`

**Comment by jeyglk** [comment]
Just amended the PR.

**Comment by eaterm** [comment]
We have had no issues with the chart until this got merged:
Now we see the following when the HPA is enabled

`unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(HorizontalPodAutoscaler.spec.scaleTargetRef): unknown field "serviceName" in io.k8s.api.autoscaling.v2beta2.CrossVersionObjectReference`
