### ISSUE TITLE
[stable/prometheus-operator] Add a Changelog.md

### ISSUE THREAD

**Issue by alinoekialo** [helm/charts#21212]
Hi,
I'm using the prometheus-operator and it is great. Thanks for the great work. However, the update process can be a bit painful given there is no Changelog. There is now an upgrade path in the Readme.md and a request for this feature was previously opened here: https://github.com/helm/charts/issues/10669.

**Is your feature request related to a problem? Please describe.**
The number of releases has increased a bit since and the versions are not specified in the commit message making it hard to filter the features and bug fixes especially when coming from an old version.

**Describe the solution you'd like**
I'd love to see a Changelog to ease this process and I'd even be willing to contribute one if someone has the time to review it before getting it integrated. I would also need help regarding the integration process since that would be my first time working in this repository.

**Describe alternatives you've considered**
I am currently trying to implement a local Changelog to keep track of our versions but it is not in sync with the repository and it feels like the community could benefit from that work.

**Additional context**
None.

**Comment by k1rk** [comment]
so is there any plans to add changelog?
