### ISSUE TITLE
Actually Use SemVer

### ISSUE THREAD

**Issue by mattfarina** [helm/charts#2121]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT?

**Version of Helm and Kubernetes**:

N/A (or, yes, all of them, this is about charts)

**Which chart**:

A lot of them

**What happened**:

According to the helm [chart docs](https://docs.helm.sh/developing_charts/#the-chart-yaml-file), the charts are supposed to use [SemVer 2](http://semver.org). SemVer is a spec that you can write consistent tools against.

* Charts are often not using SemVer correctly per the spec. Some examples,
 Shouldn't they should start with a number > 0 if they are stable. Note, according to the spec:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

* Increment in order. For example, a change from 0.2.1 should increment to 0.3.0 for the next version with new features. Yet, there are cases where it may have incremented to 0.3.1. [Here's an example](https://github.com/kubernetes/charts/commit/4b7eb100302bd8a7be4f10cf53485b951d537325#diff-459fb13dcf5560eb0c9f742a9d5109de).

**What you expected to happen**:

I expected SemVer was being followed

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

As I was thinking about it... an example came to mind. Anytime a stable chart changed the values.yaml file in a backwards incompatible manner it would be a major version change.

**Comment by matthope** [comment]
Would this be best served by using tooling to increment versions (with a major/minor/patch hint) instead of relying on humans to do the right thing?

**Comment by mattfarina** [comment]
@matthope major is API breaking changes, minor is API additions, and patch is bug fix/minor issue. How would you automate that on a chart? I love automation but have not had inspiration on how to detect the types of changes.
