### ISSUE TITLE
[stable/datadog] Docker integration broken when running in Kubernetes

### ISSUE THREAD

**Issue by tylermarien** [helm/charts#21223]
**Describe the bug**
After upgraded to version 2.0.1 of the Datadog chart, container stats are no longer reporting to Datadog. You can view the issue in this screenshot. All the containers for one of our k8s clusters stopped reporting to Datadog.

![Screen Shot 2020-03-03 at 11 31 33 AM](https://user-images.githubusercontent.com/897223/75802740-d4584200-5d42-11ea-9cb4-591aa7b62421.png)

**Version of Helm and Kubernetes**:
Helm Version: 3.0.3
Kubernetes Version: 1.15.9

**Which chart**:
stable/datadog

**What happened**:
After upgrading to version 2.0.1 of the chart, Docker statistics stopped reporting to Datadog.

**What you expected to happen**:
The Docker statistics to continue reporting to Datadog.

**How to reproduce it** (as minimally and precisely as possible):
Upgrade to version 2.0.0 or greater of the Datadog chart.

**Anything else we need to know**:
After doing some investigation, it looks like criSocketPath is now prepended with `/host/` by the chart. https://github.com/helm/charts/blob/1388bd56630f4f85ebfee0c090f6b31b02b7b606/stable/datadog/templates/container-agent.yaml#L90

When the Datadog init runs, it looks for the socket in `/var/run/` (without the prefix `/host/`). This causes it to load the wrong config file (datadog-kubernetes.yaml instead of datadog-k8s-docker.yaml). https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/entrypoint/50-kubernetes.sh#L10

**Comment by jshrack-ssi** [comment]
Agree. We too have observed this same issue. Please fix ASAP.

**Comment by L3n41c** [comment]
I’ll have a look.
What will most probably happen is that the change on the CRI socket path will be reverted until the startup script honors DD_CRI_SOCKET_PATH.
