### ISSUE TITLE
[name of the chart e.g. stable/prometheus] no longer updates, but only on linux

### ISSUE THREAD

**Issue by vchan2002** [helm/charts#21229]
I have a Jenkins CI running on CentOS to update the helm chart as I add alerts, etc... As of today, the automated process no longer runs.

./helm upgrade prometheus stable/prometheus --install --values ../values.yaml -n=prometheus

coalesce.go:199: warning: destination for env is a table. Ignoring non-table value []
coalesce.go:199: warning: destination for env is a table. Ignoring non-table value []

Error: UPGRADE FAILED: cannot patch "prometheus-kube-state-metrics" with kind Service: Service "prometheus-kube-state-metrics" is invalid: spec.clusterIP: Invalid value: "": field is immutable && cannot patch "prometheus-kube-state-metrics" with kind Deployment: Deployment.apps "prometheus-kube-state-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"kube-state-metrics"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

The strange thing is this... the exact same command... if I run this on my Mac, it works fine.  I also do not get those two warnings in regards to destination for env is a table.

After doing more testing, it would seem that, as a workaround, I can set kubeStateMetrics.enabled to false, run it, set it back to true, and run it again.  It seems that it would reset kube-state metrics service, but this time, with a ClusterIP.  Still... very strange

**Comment by zanhsieh** [comment]
@vchan2002 
The dependent chart, prometheus-kube-state-metrics, has been moved. Now it binds to the native chart (previous this chart has its own). You might update the dependency (`helm dep up` or other commands mentioned in the official helm chart)

**Comment by jaksky** [comment]
How did you resolved this? Do you need to download chart locally?
