### ISSUE TITLE
[stable/minecraft] Should be a statefulset, not a deployment

### ISSUE THREAD

**Issue by TJM** [helm/charts#21230]
As per issue #1863 the storage is RWO, which means that a deployment is not good, it should be a statefulset.

**Version of Helm and Kubernetes**: 

* helm 3.1.1
* kube vanilla 1.16.3

**Which chart**: stable/minecraft

**What happened**: upgrades (changing config) fails due to deployment trying to mount the storage twice.

**What you expected to happen**: It should stop the old pod, then start the new one. Apparently thats a statefulset?

**How to reproduce it** (as minimally and precisely as possible):
helm upgrade --install mc stable/minecraft --set eula=true
helm upgrade --install mc stable/minecraft -f values.yaml #(with other settings)

**Anything else we need to know**:
See #1863 for details

CC: @itzg

**Comment by billimek** [comment]
There is a lot of history and controversy about Deployment vs StatefulSet for helm charts and some strong opinions on both sides.

To work around this specific issue with multi-attached storage, we can solve it by changing the update strategy to `Recreate` instead of using the default of `RollingUpdate`.  See the [unifi chart](https://github.com/helm/charts/blob/master/stable/unifi/values.yaml#L6) as an example about how this is done.

I'm happy to work-up a quick PR to make this change.  It should alleviate the immediate problem with upgrades and we can continue to talk though Deployment vs Statefulset.

What do you think?

**Comment by itzg** [comment]
That works for me @billimek . Yeah, I skimmed that issue about the Deployment vs StatefulSet and IMHO the choice is fairly arbitrary since both strategies in the general kubernetes-sence equally support persistent volumes.

**Comment by billimek** [comment]
#21272 raised for this.

**Comment by TJM** [comment]
I think changing the strategy to restart will help, and will effectively work the same. The main thing is we don't want two minecraft's running using the same PVC, which shouldn't be possible, but...

```
minecraft-minecraft-576c675b66-bsgk5:minecraft-minecraft [23:48:02] [Server thread/ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
minecraft-minecraft-576c675b66-bsgk5:minecraft-minecraft bjy: The save is being accessed from another location, aborting
```

**Comment by TJM** [comment]
> Yeah, I skimmed that issue about the Deployment vs StatefulSet and IMHO the choice is fairly arbitrary since both strategies in the general kubernetes-sence equally support persistent volumes.

@itzg I think PVCs for deployments would usually be RWX (ReadWriteMany), like NFS. However, as per my error above, that would be bad for MC

**Comment by billimek** [comment]
I think we can all agree that workloads like minecraft or similar things should never leverage shared storage or multiple replicas accessing the same storage.

Assuming this is a truth, it begs the question why not run as a statefulset which will, using defaults, protect against the above situation.

**Comment by TJM** [comment]
I though this was resolved, or are we still on the fence as to whether to change from deployment/replicaset to statefulset?
