### ISSUE TITLE
[stable/sematext-agent] Make tokens optional

### ISSUE THREAD

**Issue by dibi-codes** [helm/charts#21249]
**Is your feature request related to a problem? Please describe.**
We deploy our secrets seperately via sealed secrets. This is currently not possible with sematext-agent because its tied to the helm values `infraToken`, `logsToken`, `containerToken` and overrides our seperatly deployed secrets every time on automated deployments.

```
deamonSet.yaml:1:
{{- if or (.Values.infraToken) (.Values.logsToken) (.Values.containerToken) }}
```
**Describe the solution you'd like**
I would like to be able to provide the secret as standalone file and get the helm chart deployed nevertheless.

**Comment by dabeck** [comment]
Even though this might be a problem for other people. I found a workaround and will close this issue for know.
