### ISSUE TITLE
[stable/grafana] no ingress created

### ISSUE THREAD

**Issue by hazcod** [helm/charts#21242]
**Describe the bug**
Altough I set the values, no ingress is created for grafana.

**Version of Helm and Kubernetes**:
latest, chart version 5.0.3

**Which chart**:
stable/grafana

**How to reproduce it** (as minimally and precisely as possible):
```hcl
resource "helm_release" "loki_grafana" {
  name        = "grafana"
  repository  = data.helm_repository.stable.metadata[0].name
  chart       = "stable/grafana"
  version     = var.grafana_version
  namespace   = var.loki_namespace
  
  #atomic          = true
  #cleanup_on_fail = true
  recreate_pods   = true
  verify          = false
  
  set { # grafana should store some cached data
    name  = "persistence.enabled"
    value = "true"
  }
  set { # 10Gbit should be more than enough
    name  = "persistence.size"
    value = "10Gi"
  }
  set { # use k8s native storage
    name  = "persistence.type"
    value = "pvc"
  } 
  set {
    name  = "ingress.enabled"
    value = true
  }
  set {
    name  = "ingress.hosts[0]"
    value = "nginx-ingress-nginx-controller.kube-system"
  }
  set_string {
    name  = "ingress.annotations.nginx\\.ingress\\.kubernetes\\.io/app-root"
    value = "/logs"
  }
}
```

Running pods:
```
% kubectl --kubeconfig=kubeconfig -n=logging get pods
NAME                       READY   STATUS    RESTARTS   AGE
grafana-65fdf96c94-qw55t   1/1     Running   0          5m2s
loki-0                     1/1     Running   0          24h
loki-promtail-sgggn        1/1     Running   0          24h
```

**Comment by davidh83110** [comment]
Hi @hazcod 

May I know how you solve this issue? Because I just encountered the same problem when I using this Helm Chart with latest version. Thanks.

**Comment by hazcod** [comment]
HI @davidh83110 , i'm rewriting my k8s/helm config atm at https://github.com/ironpeakservices/infrastructure , but I think it was something about bad annotations. Might be handy to look through my commits.

**Comment by davidh83110** [comment]
Hi @hazcod, Yes I agree with that was something bad annotations and thanks for sharing the repository.

I wrote my own Ingress Yaml afterward, even though it was not a good solution, better than struggling with it.
