### ISSUE TITLE
[grafana 6.3.2-6.7.1] Persistence and Stateless config map loading on startup conflicting

### ISSUE THREAD

**Issue by asafdl** [helm/charts#21244]
Problem:
If you have persistence enabled for grafana, and also are loading dashboards/datasources/initial admin password from secret/ config maps
Any changes done to config map / secret will not be updated anywhere since grafana is maintaining statefulness via persistent volume.

**Version of Helm and Kubernetes**:
15.9 (installing using argocd 1.12)

**Which chart**:
Grafana 6.3.2-6.7.1

**What happened**:
Changes to configmaps such as dashboard configmaps are not updated in grafana with persistence enabled.

**What you expected to happen**:
Like prometheus has a config-reloader I would expect grafana to maintain a persistent state while also monitoring changes in configmaps and updating accordingly. 

**How to reproduce it** (as minimally and precisely as possible):
Install grafana chart with persistence enabled (default strorageClass) and after grafana is up change any of the starting dashboard/admin secret. 
You will see that grafana will not update to accommodate changes, in some cases even pod restart will not reflect changes (like admin password).

**Comment by astrixj** [comment]
Any news? as we are facing the same issue with version 6.3.0

**Comment by asafdl** [comment]
Hi I just validated this issue is the same in latest grafana 6.7.1

**Comment by yli186** [comment]
Facing the same issue with 6.3.5. The only way for grafana to take in the rotated credentials in configmap was to delete the pvc (which loses the point of going persistence) then re-deploy the chart, else grafana uses the old credentials.

**Comment by kuldeeps88** [comment]
Facing the same issue with Grafana 6.3.5. I had to change Grafana from statefulset to deployment in order to use password rotation.
Since I am deploying all the dashboards using Kubernetes watcher I am good with running Grafana as a deployment.
It will be good if we have the fixes or we can use preStop hook to delete the old credentials, So that when it comes it loads the new one.
