### ISSUE TITLE
[stable/jenkins] slaves with iam role

### ISSUE THREAD

**Issue by ofirshtrull** [helm/charts#21266]
Hello,
is there a way to add an annotation for slaves to run with kube2im automatically from the deployment?
like we have with the backup section

Thanks

**Comment by myspotontheweb** [comment]
You could specify your own work pod YAML and include the annotation.

```
pipeline {
  agent {
    kubernetes {
      label 'my-build-pod1'
      defaultContainer 'jnlp'
      yamlFile 'jenkins/KubernetesWorkerPod1.yaml'
    }
  }
```

It's also possible to [specify a podTemplate](https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml#L481), but I'm struggling with the syntax at the moment.
