### ISSUE TITLE
[stable/minecraft] Add startupProbe to account for longer startup times in v1.15.x

### ISSUE THREAD

**Issue by TJM** [helm/charts#21284]
As per my issue that was incorrectly filed https://github.com/itzg/docker-minecraft-server/issues/445 . 

I am seeing an issue where the Minecraft pod is not given long enough to start up the first time, causing more delay in coming online. I realize the parameters are tunable thorough values.yaml, but maybe we should add a startup probe as per: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes

That might provide better response to an actual hang, while still providing enough time to startup?

**Additional context**

```
minecraft-minecraft-8b48b7956-tp7v2:minecraft-minecraft [18:03:40] [Server-Worker-1/INFO]: Preparing spawn area: 91%
minecraft-minecraft-8b48b7956-tp7v2:minecraft-minecraft [18:03:40] [Server-Worker-1/INFO]: Preparing spawn area: 93%
minecraft-minecraft-8b48b7956-tp7v2:minecraft-minecraft [18:03:41] [Server-Worker-1/INFO]: Preparing spawn area: 96%
minecraft-minecraft-8b48b7956-tp7v2:minecraft-minecraft 2020/03/05 18:03:41 Stopping with rcon-cli
minecraft-minecraft-8b48b7956-tp7v2:minecraft-minecraft 2020/03/05 18:03:41 ERROR Failed to stop using rcon-cli exit status 1
minecraft-minecraft-8b48b7956-tp7v2:minecraft-minecraft 2020/03/05 18:03:41 Sending 'stop' to Minecraft server...
minecraft-minecraft-8b48b7956-tp7v2:minecraft-minecraft 2020/03/05 18:03:41 Waiting for completion...
```

**Comment by TJM** [comment]
For what its worth, I added the following to my values.yaml to workaround this for now...

```
livenessProbe:
  initialDelaySeconds: 300
```

Maybe a startup probe is not needed. I am not really sure what the different implications are, maybe there didn't used to be an initialDelay?

**Comment by TJM** [comment]
I am also not sure whether this qualifies as a bug or a feature... is this helm chart going to be deprecated and moved over to a private repo at some point?

**Comment by 01000001-01001110** [comment]
Same issue. 
2021-04-08T19:44:41.150Z	ERROR	mc-server-runner	ERROR Failed to stop using rcon-cli	{"error": "exit status 1"}
