### ISSUE TITLE
[stable/postgresql] Error installing chart

### ISSUE THREAD

**Issue by baniol** [helm/charts#21296]
Trying to install postgresql after the [latest commit](https://github.com/helm/charts/commit/6b848abd21a2c8fd0acfba751282f404162a30e5), version 8.6.0, renders an error:
```
Error: parse error in "postgresql/templates/_helpers.tpl": template: postgresql/templates/_helpers.tpl:43: illegal number syntax: "-"
```

**Comment by anirban99** [comment]
Hi @baniol, I also have the similar issue. However you can also use an older version of helm charts to install postgres and it works. 

helm install stable/postgresql --version 8.0.0

**Comment by baniol** [comment]
Hi, this is what I did, thanks

**Comment by javsalgar** [comment]
Hi,

This PR https://github.com/helm/charts/pull/21308 fixed the issue
