### ISSUE TITLE
[stable/chart] Prometheus not able to scrape metrics from different namespaces

### ISSUE THREAD

**Issue by vaishali-prophecy** [helm/charts#21323]
I have serviceMonitorSelector and serviceMonitorNamespaceSelector configured in values.yml for prometheus like below - 

```
  prometheus-operator:
     prometheusSpec:
       serviceMonitorSelector:
         matchLabels:
           name: prophecy-operator
       serviceMonitorNamespaceSelector:
         matchLabels:
           prometheus: front-end-team
``` 

Namespace where servicemonitor is running has been labelled as- 

```
 apiVersion: v1
 kind: Namespace
 metadata:
   creationTimestamp: "2020-03-02T12:33:53Z"
   labels:
     prometheus: front-end-team
     tag: abcd
   name: visa
   resourceVersion: "2069386"
   selfLink: /api/v1/namespaces/visa
   uid: 139112ef-5c82-11ea-9e6e-42010a8001b3
 spec:
   finalizers:
   - kubernetes
 status:
   phase: Active
```

Still, in service discovery, the service monitor running in this namespace are not listed and hence metrics are not scraped.

**Comment by Anishmourya** [comment]
webservice_discovery.yaml
<pre>
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: web_service
  name: web-service-discovery
  namespace: monitoring
spec:
  endpoints:
    - interval: 10s
      port: http
      path: /metrics/
  jobLabel: web-service discovery
  namespaceSelector:
    matchNames:
      - {{namespace_name}}
  selector:
    matchLabels:
      app.kubernetes.io/instance: web_service
</pre>
----
<pre>kubectl create -f webservice_discovery.yaml</pre>
------
<pre>
helm install --namespace monitoring stable/prometheus-operator \
--set kubelet.serviceMonitor.https=true \
--set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false
</pre>
already discussed issue for namespaces :- https://github.com/helm/charts/issues/11310

**Comment by vaishali-prophecy** [comment]
But this is to select all service monitors in all namespaces and not for filtering by labels. What do I do for that?
