### ISSUE TITLE
[stable/jenkins] Using master.fsGroup and master.runAsUser gives "at <eq .Values.master.runAsUser 0.0>: error calling eq: incompatible types for comparison"

### ISSUE THREAD

**Issue by marklinders-planon** [helm/charts#21358]
**Describe the bug**
When using master.fsGroup and master.runAsUser with a value of 1000 for the helm release an error is returned.:

`Error: template: jenkins/templates/jenkins-master-deployment.yaml:69:12: executing "jenkins/templates/jenkins-master-deployment.yaml" at <eq .Values.master.runAsUser 0.0>: error calling eq: incompatible types for comparison`

**Version of Helm and Kubernetes**:
helm v3.1.1
Kubernetes = latest EKS version

**Which chart**:
stable/jenkins

**What happened**:
I tried to update an ingress hostname, but got presented with the error on runAsUser

**What you expected to happen**:
The run to succeed

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by chrisLeeTW** [comment]
I can also reproduce this error with simple command
`helm install --set master.runAsUser=1000,master.fsGroup=1000 my-release stable/jenkins`

**Comment by torstenwalter** [comment]
This one should be solved now.
