### ISSUE TITLE
stable/rabbitmq extra ports not working

### ISSUE THREAD

**Issue by embcla** [helm/charts#21352]
Uncommenting the "extraports" and "extracontainerports" in the values.yaml results in intepretation errors at various points of templates/svc.yaml

**Version of Helm and Kubernetes**:
Helm 3.0.2
Kube 1.17.3+k3s1

**Which chart**:
rabbitmq

**What happened**:
I tried to add port 1883 which is necessary for plugin mqtt 

**What you expected to happen**:
an additional port made available

**How to reproduce it** (as minimally and precisely as possible):
enter this

```
  ## Extra ports to expose 
  extraPorts: 
    1883 
 
  ## Extra ports to be included in container spec, primarily informational 
  extraContainerPorts: 
    1883 
```
or this
```
  ## Extra ports to expose 
  extraPorts: 1883 
 
  ## Extra ports to be included in container spec, primarily informational 
  extraContainerPorts: 1883 
```
and helm will quit with a yaml parse error

**Comment by carrodher** [comment]
Hi @embcla,

Taking into account the [stable deprecation timeline](https://github.com/helm/charts#deprecation-timeline), we have been started the process of moving the Bitnami Helm Charts to the Bitnami repository, see helm/charts#20969 for more details.

The Helm Chart tgz continues existing in the stable repo but it would not get new updates. We also added more info and the upgrade process to start using the new repo in the _README.md_ and _NOTES.txt_ file helm/charts#21310.

As the RabbitMQ chart is marked as deprecated in this repository, please, can you [open the issue in the bitnami charts repository](https://github.com/bitnami/charts/issues/new)?

Thanks

**Comment by embcla** [comment]
Ok will do

**closed as chart is obsolete**
