### ISSUE TITLE
[stable/redis] Dependency on bitnami image, probes can not be configured to match rhscl/redis-32-rhel7 rhscl/redis-5-rhel7

### ISSUE THREAD

**Issue by kremers** [helm/charts#21355]
**Describe the bug**
The chart does not passtrough livenessProbe or readinessProbe. See https://github.com/helm/charts/blob/1488955c16e818240b7de96c644d52206f428951/stable/redis/templates/redis-master-statefulset.yaml#L151

That makes it impossible to work with other redis images such as the redhat images rhscl/redis-32-rhel7 & rhscl/redis-5-rhel7 that do not have the same healthchecks included.

**Version of Helm and Kubernetes**:
Helm 3, Openshift 3

**Which chart**:
stable/redis

**What happened**:
Probes fail since only the bitnami image is containing the check scripts used by the chart

**What you expected to happen**:
Working chart with all redis "standard" installations, no dependencies on scripts in the image.

**Comment by carrodher** [comment]
Hi,

Given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), the Bitnami maintained Redis Helm chart is now located at [bitnami/charts](https://github.com/bitnami/charts/). Please visit the [bitnami/charts](https://github.com/bitnami/charts/) GitHub repository to create Issues or PRs.

This is the PR with the deprecation changes: https://github.com/helm/charts/pull/21333, in the description you can find a link to another issue explaining more carefully the reasons and motivations behind this transition.

**Comment by kremers** [comment]
I've created a PR there, thx
