### ISSUE TITLE
no persistent volumes available for this claim and no storage class is set - helm 3 

### ISSUE THREAD

**Issue by san2406** [helm/charts#21363]
kubectl describe pod   current-gen-pvgd-live-web-tomcat-deployment-84699dc8b-j6tsx
Name:           current-gen-pvgd-live-web-tomcat-deployment-84699dc8b-j6tsx
Namespace:      cmecf-databases
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/instance=current-gen
                app.kubernetes.io/name=currentgen
                pod-template-hash=84699dc8b
                tier=currentgen
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/current-gen-pvgd-live-web-tomcat-deployment-84699dc8b
Containers:
  web:
    Image:      cmso-cmecf-docker-dev.cfar.nsapps.dcn/cmecf-dc-inside-web:6.3
    Port:       8443/TCP
    Host Port:  0/TCP
    Command:
      /startup.sh
    Limits:
      memory:  1Gi
    Requests:
      memory:   1Gi
    Readiness:  http-get https://:8443/cgi-bin/login.pl delay=15s timeout=10s period=10s #success=1 #failure=3
    Environment Variables from:
      current-gen-pwd-secret            Secret     Optional: false
      current-gen-currentgen-configmap  ConfigMap  Optional: false
    Environment:                        <none>
    Mounts:
      /data/docs0 from current-gen-docs-vol (rw)
      /opt/ssl/ from current-gen-currentgen-ssl-vol (ro)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2scqc (ro)
  tomcat:
    Image:       cmso-cmecf-docker-dev.cfar.nsapps.dcn/cmecf-dc-inside-tomcat:6.3
    Ports:       8000/TCP, 9080/TCP
    Host Ports:  0/TCP, 0/TCP
    Command:
      /startup.sh
    Limits:
      memory:  1Gi
    Requests:
      memory:  1Gi
    Environment Variables from:
      current-gen-pwd-secret            Secret     Optional: false
      current-gen-currentgen-configmap  ConfigMap  Optional: false
    Environment:                        <none>
    Mounts:
      /data/docs0 from current-gen-docs-vol (rw)
      /opt/ssl/ from current-gen-currentgen-ssl-vol (ro)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2scqc (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  current-gen-docs-vol:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  current-gen-docs-claim
    ReadOnly:   false
  current-gen-currentgen-ssl-vol:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  current-gen-ssl-secret
    Optional:    false
  default-token-2scqc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2scqc
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  60m (x63 over 151m)  default-scheduler  error while running "VolumeBinding" filter plugin for pod "current-gen-pvgd-live-web-tomcat-deployment-84699dc8b-j6tsx": pod has unbound immediate PersistentVolumeClaims

**Comment by sada2406** [comment]
Below is our deployment yaml file under helm charts 


cat deployment.yaml
{{- if eq .Values.global.deploymentPlatform "ocp" }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.courtName }}-{{ .Values.global.courtInstance }}-web-tomcat-deployment
  {{- template "currentgen.labels" . }}
spec:
  replicas: 1
  selector:
{{- if eq .Values.global.deploymentPlatform "ocp" }}
    deploymentconfig: {{ .Release.Name }}-{{ .Values.global.courtName }}-{{ .Values.global.courtInstance }}-web-tomcat-deployment
{{- else }}
    matchLabels:
      app.kubernetes.io/name: {{ include "currentgen.name" . }}
      tier: currentgen
{{- end }}
  strategy:
   # resources: {}
    type: Rolling
{{- if eq .Values.global.deploymentPlatform "ocp" }}
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 6000
      maxUnavailable: 25%
      maxSurge: 25%
    activeDeadlineSeconds: 21600
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - web
        from:
          kind: ImageStreamTag
          name: cmecf-{{- include "cmecf-helm.imageSuffix" . }}{{- include "cmecf-helm.courtTypeShort" . }}-inside-web:{{ .Values.versionTag }}
          namespace: {{ .Values.namespace }}
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - tomcat
        from:
          kind: ImageStreamTag
          name: cmecf-{{- include "cmecf-helm.imageSuffix" . }}{{- include "cmecf-helm.courtTypeShort" . }}-inside-tomcat:{{ .Values.versionTag }}
          namespace: {{ .Values.namespace }}
      type: ImageChange
{{- else }}
    type: RollingUpdate
{{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "currentgen.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if eq .Values.global.deploymentPlatform "ocp" }}
        deploymentconfig: {{ .Release.Name }}-{{ .Values.global.courtName }}-{{ .Values.global.courtInstance }}-web-tomcat-deployment
{{- else }}
        tier: currentgen
{{- end }}
    spec:
      {{- include "currentgen.initContainer" . }}
      containers:
      - name: web
        command:
        - /startup.sh
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-pwd-secret
        - configMapRef:
            name: {{ .Release.Name }}-currentgen-configmap
{{- if eq .Values.global.deploymentPlatform "ocp" }}
        image:
{{- else }}
        image: {{ .Values.imageRepo }}/cmecf-{{- include "cmecf-helm.imageSuffix" . }}{{- include "cmecf-helm.courtTypeShort" . }}-inside-web:{{ .Values.versionTag }}
{{- end }}
        resources:
          limits:
            memory: 1Gi
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
          protocol: TCP
        readinessProbe:
          httpGet:
            path: "{{- include "currentgen.readinessProbePath" . }}"
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 10
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /tmp
          name: tmp
{{- if .Values.global.docs.usePV }}
        - mountPath: {{ .Values.global.docs.mountPath }}
          name: {{ .Release.Name }}-docs-vol
{{- end}}
        - mountPath: /opt/ssl/
          name: {{ .Release.Name }}-currentgen-ssl-vol
          readOnly: true
      - name: tomcat
        command:
        - /startup.sh
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-pwd-secret
        - configMapRef:
            name: {{ .Release.Name }}-currentgen-configmap
{{- if eq .Values.global.deploymentPlatform "ocp" }}
        image:
{{- else }}
        image: {{ .Values.imageRepo }}/cmecf-{{- include "cmecf-helm.imageSuffix" . }}{{- include "cmecf-helm.courtTypeShort" . }}-inside-tomcat:{{ .Values.versionTag }}
{{- end }}
        resources:
          limits:
            memory: 1Gi
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 9080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /tmp
          name: tmp
{{- if .Values.global.docs.usePV }}
        - mountPath: {{ .Values.global.docs.mountPath }}
          name: {{ .Release.Name }}-docs-vol
{{- end}}
        - mountPath: /opt/ssl/
          name: {{ .Release.Name }}-currentgen-ssl-vol
          readOnly: true
      dnsPolicy: ClusterFirst
      hostAliases:
        - hostnames:
            - ecf-{{ .Values.global.courtName }}
            - ecf-{{ .Values.global.courtName }}.{{- include "cmecf-helm.domain" . }}
          ip: 127.0.0.1
      restartPolicy: Always
      {{ include "cmecf-helm.nodeSelector" . }}
      volumes:
      - emptyDir: {}
        name: tmp
{{- if .Values.global.docs.usePV }}
      - name: {{ .Release.Name }}-docs-vol
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-docs-claim
{{- end}}
      - name: {{ .Release.Name }}-currentgen-ssl-vol
        secret:
          secretName: {{ .Release.Name }}-ssl-secret
[ansadmin@kubeconsole templates]$
