### ISSUE TITLE
stable/rabitmq Health checks fails when management ui deploy with path_prefix

### ISSUE THREAD

**Issue by Mr-Wouter** [helm/charts#21364]
**Describe the bug**
Health checks on wrong URL if RabbitMQ deployed with path_prefix setting for management UI.

I'm deploying rabbit mq with a management prefix. 
```
rabbitmq:
    extraConfiguration: |-
      management.path_prefix = /RabbitMQ
```

And and then making it available with a ingress rule on /RabbitMQ.

Why I am doing this? 
I want RabbitMQ management to be available on the same URL as the app (and same port). 
Im not using a URL rewrite as the URL rewrite with NGINX will URL decode and that causes in issue upstream. So not using a URL rewrite solves this problem, but the prefix must be used.

But with this setup, using the path_prefix, the api and health checks fail. If I disable them (by changing to "exit 0") then everything works fine. 

**Version of Helm and Kubernetes**:
Client: 1.15.5
Server: 1.15.7

**Which chart**:
stable/rabbitmq

**What happened**:
RabbitMQ health checks keep failing and pod get restarted

**What you expected to happen**:
RabbitMQ health checks to be successful

**How to reproduce it** (as minimally and precisely as possible):
See above

**Anything else we need to know**:
I've already investigate why this fails, this is because the health check URL is called like this:
"rabbitmq-api-check \"http://user:$RABBITMQ_PASSWORD@127.0.0.1:15672/api/healthchecks/node\" '{\"status\":\"ok\"}'"

But in my case the URL should have contained":15672**/RabbitMQ**/api/"
I've also investigate the HELM template and found that the file statefulset.yaml contains the following:

`- rabbitmq-api-check "http://{{ .Values.rabbitmq.username }}:$RABBITMQ_PASSWORD@127.0.0.1:{{ .Values.service.managerPort }}/api/healthchecks/node" '{"status":"ok"}'`

So it seams there is not way to insert the require prefix.
The above case is for the api-check but the case is the same for the health-check.

**Comment by carrodher** [comment]
Hi,

Given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), the Bitnami maintained RabbitMQ Helm chart is now located at [bitnami/charts](https://github.com/bitnami/charts/). Please visit the [bitnami/charts](https://github.com/bitnami/charts/) GitHub repository to create Issues or PRs.

This is the PR with the deprecation changes: https://github.com/helm/charts/pull/21310, in the description you can find a link to another issue explaining more carefully the reasons and motivations behind this transition.
