### ISSUE TITLE
[stable/prometheus-operator] Cluster-autoscaler down-scaling events causes KubeNodeUnreachable alerts

### ISSUE THREAD

**Issue by sdavids13** [helm/charts#21371]
**Describe the bug**
When a cluster autoscaling scale-down event occurs it causes a KubeNodeUnreachable alert to be fired. This is described in-depth in here: https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/300 (and should be mimicked here as well)

**Version of Helm and Kubernetes**:
2.x, 1.14.x

**Which chart**:
stable/prometheus-operator 

**What happened**:
Alert is fired in the shutdown phase of the Node

**What you expected to happen**:
When a node is being scaled-down an alarm isn't fired.

**How to reproduce it** (as minimally and precisely as possible):
Scale down your k8s cluster

**Anything else we need to know**:
See discussion here: https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/300

**Comment by AXington** [comment]
Would be really wonderful to be able to have a parameter to modify this easily.

**Comment by cablespaghetti** [comment]
This has been fixed in the kubernetes-mixin project. I'll make a PR to update it here too. https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/415
