### ISSUE TITLE
Add xornivore as Trusted Collaborator

### ISSUE THREAD

**Issue by xornivore** [helm/charts#21388]
Hello,

I'm a member of the Datadog team that maintains the stable/datadog chart.

May I please be added as a Trusted Collaborator to take part in the PR lifecycle? (Similar to #20993)

Thank you!

cc @clamoriniere @CharlyF

**Comment by clamoriniere** [comment]
Approved from Datadog.

**Comment by irabinovitch** [comment]
@mattfarina 👋 would love a hand here.

**Comment by irabinovitch** [comment]
@mattfarina let us know if you need any more info for this or #21003?
