### ISSUE TITLE
[stable/external-dns] AAD used incorrectly in chart

### ISSUE THREAD

**Issue by lindhe** [helm/charts#21382]
**Describe the bug**
In `values.yaml`, one can provide `azure.aadClientId` and `azure.aadClientSecret`. As far as I can tell, it's meant to be the `appId` of the relevant service principal. Since AAD is a common abbreviation for Azure Active Directory, it's pretty  confusing to see `aad` in the variable names. Please explain to me if I've misunderstood.

**Which chart**:
stable/external-dns

**Comment by rafariossaa** [comment]
Hi, 
  We are keeping the same environment variables that the creators of external-dns, so this way is not misleading for the users.
  Maybe you would like to check the azure documentation provided by them [here](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/).

**Comment by lindhe** [comment]
Alright, thanks for the reply. I guess I'll bring up the question in https://github.com/kubernetes-sigs/external-dns instead.
