### ISSUE TITLE
[stable/superset] init_superset.sh initfile is no longer run.

### ISSUE THREAD

**Issue by geedoubleya** [helm/charts#21421]
**Describe the bug**
Since the entrypoint / args was changed from init_superset.sh to use gunicorn (c56f4d4ad95917b6736c25cd9120944e85a83d18) I cannot see any evidence that ini_superset.sh is being run.
I deployed the helm chart and the superset app ran fine and is accessible via the host address, but the user does not exist.
Checking the k8s logs there is no output from the superset init script.

**Version of Helm and Kubernetes**:
Helm 2.14.3 / 2.14.3
Kubernetes 1.16 / 1.14

**Which chart**:
stable/superset

**What happened**:
Using helm install I installed the chart (with host address changed) and I can access the superset app but cannot login. gunicorn is running fine.
If I shell onto the pod and run the init script (init_superset.sh) then the account / db is created and I can log in.

**What you expected to happen**:
The app should be running and the username and password that are specified in the initFile config should be created to log in with.

**How to reproduce it** (as minimally and precisely as possible):
Change the hosts address and helm install the chart. Try to log in with the default admin/admin account.

**Anything else we need to know**:

I have since reverted the entrypoint / args to the init_superset.sh script and replaced the superset run line in initFile to be:
/usr/bin/env python /usr/local/bin/gunicorn -b 0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 superset:app

And this is initialising / creating the user and running as expected.

**Comment by danjo133** [comment]
Is there any way to get traction on this? Do you want a pull request?

**Comment by geedoubleya** [comment]
Well I did configure a workaround that works for me, but I am not sure it is fit for production as the idempotency element that I also added to work with already configured pvc's is not best practice. So I don't want to submit it as a solution.

**Comment by danjo133** [comment]
Ok, I can work with the existing chart (Adding extra config for extra ingresses and network policies outside), except that I need to control the start up of superset. So I basically just want this particular bug fixed. I fixed it like this:

```
diff --git a/stable/superset/templates/deployment.yaml b/stable/superset/templates/deployment.yaml
index c10422918..c632102ed 100644
--- a/stable/superset/templates/deployment.yaml
+++ b/stable/superset/templates/deployment.yaml
@@ -49,8 +49,12 @@ spec:
         - name: {{ .Chart.Name }}
           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
           imagePullPolicy: {{ .Values.image.pullPolicy }}
-          command: ["/usr/bin/env"]
-          args: ["python", "/usr/local/bin/gunicorn", "-b", "0.0.0.0:8088", "--limit-request-line", "0", "--limit-request-field_size", "0", "superset:app"]
+          command: ["/bin/bash"]
+          args:
+          - /home/superset/init_superset.sh
+          {{- range .Values.extraArguments }}
+          - {{ . }}
+          {{- end }}
           volumeMounts:
             - name: superset-configs
               mountPath: /home/superset
```
