### ISSUE TITLE
[stable/neo4j] allow custom configuration of neo4j

### ISSUE THREAD

**Issue by javamonkey79** [helm/charts#21439]
**Is your feature request related to a problem? Please describe.**
I need to be able to provide custom configuration to neo4j, such as enabling apoc. I cannot seem to do this with the existing chart.

**Describe the solution you'd like**
I would like an optional configmap added, that if present is mounted and used.

**Describe alternatives you've considered**
I don't think there is an alternative.

**Additional context**
This blocks us on https://github.com/lyft/amundsen/issues/327

**Comment by javamonkey79** [comment]
cc @helm/charts-maintainers I would like to submit a PR, but, there is no owner for this chart. How would I got about getting it approved?

**Comment by javamonkey79** [comment]
possible duplicate of https://github.com/helm/charts/issues/19187

**Comment by prashantgupta24** [comment]
@javamonkey79 For enabling `APOC`, they have commented code here, which let me enable APOC. 
https://github.com/helm/charts/blob/master/stable/neo4j/values.yaml#L86

Let me know if that helps!

**Comment by javamonkey79** [comment]
hi @prashantgupta24 and thank you! Don't you have to add this to the config?

> dbms.security.procedures.unrestricted=algo.*,apoc.*

I've seen it in a few articles on the setup like [this one](https://medium.com/@vinay26k/install-apoc-library-for-neo4j-server-ed87d9d5ddb3)

**Comment by prashantgupta24** [comment]
I didn't have to, for some reason. Just uncommenting out that section made APOC work for me.

Also there's a way you can add env variables to the neo4j conf file here, https://github.com/helm/charts/blob/master/stable/neo4j/values.yaml#L75

Something like this:
```
extraVars:
  - name: NEO4J_apoc_export_file_enabled
    value: "true"
  - name: NEO4J_apoc_import_file_enabled
    value: "true"
```

adds 

```
apoc.import.file.enabled=true
apoc.export.file.enabled=true
```

 to the `/var/lib/neo4j/conf/neo4j.conf` file automatically

**Comment by javamonkey79** [comment]
Yes, I see. If all env vars will take precedence (and I think they do), then this solution will work. Thanks!

**Comment by moxious** [comment]
I'm working on a PR right now which will include Neo4j 4.0 support.  A thing I'm going to do to try to address this is refactor all of the pod configs into two config maps, one for cores, one for read replicas.  Then with values, you'll be able to specify which configmap you want your properties out of.  This way, you can ignore the one that comes with the helm chart and specify your own at install time if you wish.

Stay tuned, it will be appearing here: https://github.com/helm/charts/pull/21896
