### ISSUE TITLE
[stable/datadog] disabling CRI also disables log collection for docker runtime

### ISSUE THREAD

**Issue by dagvl** [helm/charts#21461]
In the README.md, it says:
```
CRI integration

As of the version 6.6.0, the Datadog Agent supports collecting metrics from any container runtime interface used in your cluster. Configure the location path of the socket with datadog.criSocketPath; default is the Docker container runtime socket. To deactivate this support, you just need to unset the datadog.criSocketPath setting. Standard paths are:

    Docker socket: /var/run/docker.sock
    Containerd socket: /var/run/containerd/containerd.sock
    Cri-o socket: /var/run/crio/crio.sock
```
However, when disabling this with  `datadog.criSocketPath: ""`this also disables log collection by removing the mount for the log volume due to this in the template:
https://github.com/helm/charts/blob/master/stable/datadog/templates/container-agent.yaml#L136
```
    {{- if regexFind "^.*docker.*$" $.Values.datadog.criSocketPath }}
    - name: logdockercontainerpath
      mountPath: /var/lib/docker/containers
      readOnly: true
    {{- end }}
```
The volume definition is also removed: https://github.com/helm/charts/blob/master/stable/datadog/templates/daemonset.yaml#L115
```
        {{- if regexFind "^.*docker.*$" $.Values.datadog.criSocketPath }}
        - hostPath:
            path: /var/lib/docker/containers
          name: logdockercontainerpath
        {{- end }}
```
Additionally, I was told by datadog support
>  The CRI check is intended for runtimes other than Docker, so if you're using Docker then this check failing would be expected behavior.

But the default in the chart is to have it turned on and to connect it to the docker socket.

**Comment by L3n41c** [comment]
Hello @dagvl,

Thanks for reporting this issue.
In #21476, I fixed the mix between `cri` and `docker` and the fact that they were both controlled with the same `criSocketPath` parameter.
With that change, there are two parameters `dockerSocketPath` and `criSocketPath`.
If one of the two is specified, it enables only the corresponding check (i.e.: either only `docker`, or only `cri`).
If none of them are specified, it defaults to `docker` check with `/var/run/docker`.

So, with #21476 and the default values, you will **not** have the `cri` check triggered and you will collect docker logs.
Could you please confirm that the latest version of the chart works as described and that it fixes your issue ?

**Comment by dagvl** [comment]
Hi @L3n41c ,

I've tested version 2.0.14 of the chart now and it works as intended with the default settings.

Thanks!
