### ISSUE TITLE
[incubator/gogs] error: failed to download

### ISSUE THREAD

**Issue by linker-err0r** [helm/charts#21468]
**Describe the bug**
Attempting to install `incubator/gogs` results in a download error.

**Version of Helm and Kubernetes**:
Helm: version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.14"}

Kubernetes: 1.15.5

**Which chart**:
incubator/gogs

**What happened**:
```shell
Error: failed to download "incubator/gogs" (hint: running `helm repo update` may help)
```
Obviously, running `helm repo update` did not help. 

**What you expected to happen**:
Helm should install gogs into my Kubernetes node.

**How to reproduce it** (as minimally and precisely as possible):
```shell
$ helm install incubator/gogs
```

**Anything else we need to know**:
Following the instructions available in `helm/charts` repository.  They appear to be out of date?

**Comment by deathgaze** [comment]
This is still happening.
