### ISSUE TITLE
Getting Issue While Making API Call To Druid Overload

### ISSUE THREAD

**Issue by V-Bhadauriya** [helm/charts#21477]
**Describe the bug**
I am making a posting a JSON to Druid Overload to this endpoint:
http://[druid-overload]/druid/indexer/v1/supervisor but its redirecting to druid broker.

**Version of Helm and Kubernetes**:

**Which chart**:
How To Add router to access UI for Druid Component.

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by TerryTab** [comment]
any updates?

**Comment by AWaterColorPen** [comment]
@V-Bhadauriya [incubator/druid] chart? Please rename the issue title. BTW what is your problem?
