### ISSUE TITLE
Unknown field "type" in io.k8s.api.core.v1.ConfigMap

### ISSUE THREAD

**Issue by weishiuchang** [helm/charts#21479]
https://github.com/helm/charts/blob/84f684d6a5cfb1c3c8cd6de7c5715bc950cfe58c/stable/traefik/templates/client-ca-configmap.yaml#L12

Should this be changed to a "kind: Secret" as "type: Opaque" is not applicable for a "kind: ConfigMap"?

**Comment by aescanero** [comment]
Please reopen it, is not fixed.

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ConfigMap): unknown field "type" in io.k8s.api.core.v1.ConfigMap

**Comment by guptthha** [comment]
There must be a space in the one of the yaml file where the type filed is
