### ISSUE TITLE
[stable/postgresql] Add eneable pg_stat_statements extension in values file.

### ISSUE THREAD

**Issue by heckad** [helm/charts#21486]
Need to add `extension.pg_stat_statements : bool` with default false to values file and add support this extension. In the future, by the same principle, you can add the inclusion of other extensions. What needs to do for implementing this feature?

**Comment by javsalgar** [comment]
Hi,

This repository is deprecated. We now provide support for the postgresql chart in the bitnami/charts repository. I created this ticket so we can continue the conversation here https://github.com/bitnami/charts/issues/2067
