### ISSUE TITLE
[stable/kong] Failed to list *v1.Secret: Unauthorized

### ISSUE THREAD

**Issue by parmarnikunj** [helm/charts#21497]
**Describe the bug**
When ever I redeploy my umbrella chart, with following proxy values of kong chart, I always get following errors in kong pod.

`E0317 14:20:30.401902       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Secret: Unauthorized
E0317 14:20:31.064843       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Unauthorized
E0317 14:20:31.168397       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Service: Unauthorized
E0317 14:20:31.405330       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Secret: Unauthorized
E0317 14:20:32.068757       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Unauthorized
E0317 14:20:32.172027       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Service: Unauthorized
E0317 14:20:32.409029       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Secret: Unauthorized
E0317 14:20:33.071959       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Unauthorized
E0317 14:20:33.175900       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Service: Unauthorized
E0317 14:20:33.412757       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Secret: Unauthorized
E0317 14:20:34.075956       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Unauthorized
E0317 14:20:34.179416       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Service: Unauthorized
E0317 14:20:34.416556       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Secret: Unauthorized
E0317 14:20:35.081230       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Unauthorized
E0317 14:20:35.183160       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Service: Unauthorized
E0317 14:20:35.420634       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Secret: Unauthorized`

**Version of Helm and Kubernetes**:

Helm version: 3.1.1
Kubernetes version: 1.12.10

**Which chart**:
stable/kong version 0.36.6

**What happened**:

Authorization Errors

**What you expected to happen**:

No Exceptions should occur and routing should function as normal.

**How to reproduce it** (as minimally and precisely as possible):

redeploy umbrella chart as below:
helm upgrade release-name release-version.tgz --install --force --timeout 900s --set global.host=test.example.com  --namespace default --set kong-chart-name.kong.proxy.clusterIP=100.66.241.169 --set kong-chart-name.kong.proxy.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-ssl-cert=arn:to:aws:certificate

**Comment by hbagdi** [comment]
Please move this issue to https://github.com/kong/charts
