### ISSUE TITLE
[stable/prometheus-operator] no route to host for default datasource in Grafana

### ISSUE THREAD

**Issue by guthrey-coy** [helm/charts#21509]
**Describe the bug**

After updating the prometheus-operator helm chart from version 8.5.0 -> 8.5.4 the default grafana datasource started encountering an issue on every dashboard. I also encountered this issue when deploying on a brand new cluster with version 8.12.1

![image](https://user-images.githubusercontent.com/52211074/76908437-47e36e80-686e-11ea-8fe9-7ca7946cabaa.png)

When looking at the errors in the grafana container logs, I see several proxy error's associated with the service IP for the prometheus datasource. Like so:

```
2020/03/17 22:42:11 http: proxy error: dial tcp 10.233.49.33:9090: connect: no route to host
```

I have gone through the service debugging described [here](https://v1-16.docs.kubernetes.io/docs/tasks/debug-application-cluster/debug-service/)

and found the following...

From a pod within the same namespace, the Prometheus servers IP returns unreachable and the Prometheus server pod is reachable.

Service IP:
```
/ # wget -qO- 10.233.49.33:9090
wget: can't connect to remote host (10.233.49.33): Host is unreachable
/ # wget -qO- 10.233.49.33
wget: can't connect to remote host (10.233.49.33): Host is unreachable
```

Pod IP:
```
/ # wget -qO- 10.233.82.7:9090
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="robots" content="noindex,nofollow">
        <title>Prometheus Time Series Collection and Processing Server</title>
...
```
 
nslookup from within a pod in the same namespace does find the service...

```
/ # nslookup 10.233.49.33
...
33.49.233.10.in-addr.arpa       name = prometheus-prometheus-oper-prometheus.prometheus.svc.cluster.local
```

The service does have the correct endpoints as well.

```
# kubectl -n prometheus get endpoints prometheus-prometheus-oper-prometheus
NAME                                    ENDPOINTS          AGE
prometheus-prometheus-oper-prometheus   10.233.82.7:9090   84d
```

The ipvs tables on the nodes do have the correct entries for the service and the pod as well.

```
# ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
...
TCP  10.233.49.33:9090 rr
  -> 10.233.82.7:9090             Masq    1      0          0
```

and curl from the node to the service IP does resolve...

```
# curl 10.233.49.33:9090
<a href="/prometheus">Found</a>.
```

I also see no issues with kube-proxy and see that the endpoint was added correctly

```
endpoints.go:342] Setting endpoints for "prometheus/prometheus-prometheus-oper-prometheus:web" to [10.233.82.7:9090]
```

Here is the url what is used for the datasource:

```
http://prometheus-prometheus-oper-prometheus:9090/prometheus/
```

**Version of Helm and Kubernetes**:
Helm Version
```
# helm3 version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

Kubernetes Version
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

[stable/prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) version 8.12.1

**What happened**:

Described above...

**What you expected to happen**:

Connection to the Prometheus data source is successful when the helm chart is deployed and the grafana dashboards load properly.

**How to reproduce it** (as minimally and precisely as possible):

Deploy from helm chart 8.12.1
kube-proxy in ipvs mode
CNI = calico

**Anything else we need to know**:

Here is the yaml from the prometheus server's service

```
# kubectl get svc -n prometheus prometheus-prometheus-oper-prometheus -o yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-operator-prometheus
    chart: prometheus-operator-8.5.4
    heritage: Helm
    release: prometheus
    self-monitor: "true"
  name: prometheus-prometheus-oper-prometheus
  namespace: prometheus
spec:
  clusterIP: 10.233.49.33
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    prometheus: prometheus-prometheus-oper-prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by Guthrey** [comment]
Solved!This issue was solved by flushing IP tables on the hosts. There were stale records there after we fixed kube-proxy to use ipvs.
