### ISSUE TITLE
Please sync the selector of the service with the deployment descriptor

### ISSUE THREAD

**Issue by Sam123ben** [helm/charts#21514]
The selector doesn't match the label in the deployment descriptor for the reason it was not able to assign the right loadbalancer to the service endpoints and throwing exceptions.
I updated the service selector manually to the below and it worked then:

`app.kubernetes.io/component: "{{ .Values.controller.name }}"`

**Comment by skomma** [comment]
Is this fixed in #21512?
This PR has fixed to match Service selector with controller's Pod labels.

**Comment by Ranger-X** [comment]
> Is this fixed in #21512?
> This PR has fixed to match Service selector with controller's Pod labels.

Could you make same fix also in controller-metrics-service.yaml and controller-servicemonitor.yaml please?
