### ISSUE TITLE
[stable/jenkins] Error: timed out waiting for the condition

### ISSUE THREAD

**Issue by arjunrv88** [helm/charts#21516]
**Describe the bug**
A clear and concise description of what the bug is. We are trying to assign IAM role to worker/slave pods and when we try to deploy the terraform file, it throws an error saying timed out waiting for the condition

**Version of Helm and Kubernetes**:

**Which chart**: jenkins v 1.9.19

**What happened**: Error: timed out waiting for the condition

**What you expected to happen**: To deploy successfuly

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**: Attaching the error log

`running "/home/atlantis/.atlantis/bin/terraform0.12.17 apply -input=false -no-color \"/home/atlantis/.atlantis/repos/infoscout/nmr-dsml-terraform/8/default/jenkins/jenkins-default.tfplan\"" in "/home/atlantis/.atlantis/repos/***/default/jenkins": exit status 1
helm_release.jenkins: Modifying... [id=jenkins]
helm_release.jenkins: Still modifying... [id=jenkins, 10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 1m0s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 1m10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 1m20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 1m30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 1m40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 1m50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 2m0s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 2m10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 2m20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 2m30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 2m40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 2m50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 3m0s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 3m10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 3m20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 3m30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 3m40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 3m50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 4m0s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 4m10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 4m20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 4m30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 4m40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 4m50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 5m0s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 5m10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 5m20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 5m30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 5m40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 5m50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 6m0s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 6m10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 6m20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 6m30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 6m40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 6m50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 7m0s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 7m10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 7m20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 7m30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 7m40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 7m50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 8m0s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 8m10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 8m20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 8m30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 8m40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 8m50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 9m0s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 9m10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 9m20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 9m30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 9m40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 9m50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 10m0s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 10m10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 10m20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 10m30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 10m40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 10m50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 11m0s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 11m10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 11m20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 11m30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 11m40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 11m50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 12m0s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 12m10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 12m20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 12m30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 12m40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 12m50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 13m0s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 13m10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 13m20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 13m30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 13m40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 13m50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 14m0s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 14m10s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 14m20s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 14m30s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 14m40s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 14m50s elapsed]
helm_release.jenkins: Still modifying... [id=jenkins, 15m0s elapsed]

Error: timed out waiting for the condition

  on jenkins.tf line 16, in resource "helm_release" "jenkins":
  16: resource "helm_release" "jenkins" {`

**Comment by torstenwalter** [comment]
Without logs from Jenkins or any other information I suspect that it will be hard to help.

**Comment by arjunrv88** [comment]
We were actually able to solve it. Turns out it was the problem JCasC file parameter configuration.

**Comment by Spritekin** [comment]
Sorry would you please tell me what was the solution? I found the same problem but can't see how to solve this.

**Comment by arjunrv88** [comment]
In our case it was in the JCasC file. One of the parameter defined in the file was not set correctly. You might want to check the file and verify
