### ISSUE TITLE
[stable/nginx-ingress] Selector in service not match deployment in controller

### ISSUE THREAD

**Issue by SpikeW15** [helm/charts#21515]
Today my ingress-controller did not work. I checked the log and found following message:

```
Service "nginx-ingress-default-backend" does not have any active Endpoint
```

There was no IP in endpoint of controller service, and I found that the label in service didn't match deployment. 

Controller selector in service: 
https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-service.yaml#L91

Label in deployment: 
https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-deployment.yaml#L20

**Comment by Sam123ben** [comment]
edit the sevice yaml and update the below:

app.kubernetes.io/component: "{{ .Values.controller.name }}"

**Comment by Sam123ben** [comment]
I raised a feature request

https://github.com/helm/charts/issues/21514

**Comment by SpikeW15** [comment]
Thanks for reply.
