### ISSUE TITLE
stable/mediawiki smtpusername is wrong configured

### ISSUE THREAD

**Issue by xvrlee** [helm/charts#21528]
**Describe the bug**
 Smtp username configuration is not configured correctly.

**Which chart**:
mediawiki

**What happened**:
$wgSMTP = array(
        'host' => 'testidhost',
        'IDHost' => 'testidhost',
        'port' => '**testport**',
        'username' => '**testport**',
        'password' => 'testpass*',
        'auth' => true
); 

**What you expected to happen**:
$wgSMTP = array(
        'host' => 'testidhost',
        'IDHost' => 'testidhost',
        'port' => '**testport**',
        'username' => '**testusername**',
        'password' => 'testpass*',
        'auth' => true
);

**Comment by carrodher** [comment]
Hi,

Given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), this Bitnami maintained Helm chart is now located at [bitnami/charts](https://github.com/bitnami/charts/). Please visit the [bitnami/charts](https://github.com/bitnami/charts/) GitHub repository to create Issues or PRs.

In [this issue](https://github.com/helm/charts/issues/20969) we tried to explain more carefully the reasons and motivations behind this transition, please don't hesitate to add a comment in this issue if you have any question related to the migration itself.
