### ISSUE TITLE
[percona-xtradb-cluster] Kubernetes v1.16 compatibilty

### ISSUE THREAD

**Issue by iben12** [helm/charts#21538]
**Is your feature request related to a problem? Please describe.**

Percona XtraDB Cluster cannot be installed on Kubernetes v1.16+ because of the StatefulSet api version. You get the error message:
`Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"`

**Describe the solution you'd like**
The `templates/statefulset.yaml` template should be updated to use `apiVersion: apps/v1`.

**Describe alternatives you've considered**
Copy the chart and serve from private repo.

**Additional context**
https://v1-16.docs.kubernetes.io/docs/setup/release/notes/#deprecations-and-removals

**Comment by gaghan430** [comment]
can you guys pls update this

**Comment by libardolara** [comment]
Any plan tu update this issue?
