### ISSUE TITLE
[stable/gocd] Latest gocd ssl changes in version 20.2.0 breaking the chart

### ISSUE THREAD

**Issue by artushin** [helm/charts#21544]
**Describe the bug**
GoCD is not listening on port 8145 any long as of the latest release: https://github.com/gocd/gocd/issues/7872

`GoCD Server's Jetty instance will stop listening on the SSL/TLS endpoint (port 8154) going forward.`

**Version of Helm and Kubernetes**:
helm: 2.14.2
k8s: 1.14.10

**Which chart**:
github.com/helm/charts/tree/master/stable/gocd

**What happened**:
Version incompatible with chart

**What you expected to happen**:
gocd server to run on port 8145

**How to reproduce it** (as minimally and precisely as possible):
run the chart with no values changes

**Anything else we need to know**:

**Comment by arvindsv** [comment]
Thanks, @artushin. #21548 should make it work out of the box now.
