### ISSUE TITLE
 FailedBinding  78s (x63 over 16m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

### ISSUE THREAD

**Issue by veera2019** [helm/charts#21573]
Hi Team,

I have created PV in linux ec2 instance and i tried to install mongodb using helm 
helm install --name my-release stable/mongodb 
so my pvc status showing pending if i describe pvc i am getting below error
  **Normal     FailedBinding  78s (x63 over 16m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set**

if i describe mongodb pod it was showing below error
  **Warning  FailedScheduling  79s (x13 over 19m)  default-scheduler  pod has unbound immediate PersistentVolumeClaims**

my helm version is 
**Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}**

kube version: 1.14.6

so please suggest me where is the issue.

**Comment by veera2019** [comment]
it's working fine it was failing because of less volume size.

**Comment by carrodher** [comment]
I'm glad that you were able to fix the issue. In the same way, I would like to mention that given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), this Bitnami maintained Helm chart is now located at [bitnami/charts](https://github.com/bitnami/charts/). Please visit the [bitnami/charts](https://github.com/bitnami/charts/) GitHub repository to create Issues or PRs.

In [this issue](https://github.com/helm/charts/issues/20969), we tried to explain more carefully the reasons and motivations behind this transition, please don't hesitate to add a comment in this issue if you have any question related to the migration itself.
