### ISSUE TITLE
stable/prometheus-operator Bug k8s status elements should not be included in CRD (bug introduced in #20419)

### ISSUE THREAD

**Issue by ErikLundJensen** [helm/charts#21575]
**Describe the bug**
The code changes in issue #20419 added Kubernetes status elements to the CRD files. When using GitOps engine like Argocd this gives synchronization warnings as the values of the status elements in the chart does not match the deployed CRD status elements in Kubernetes.

The CRD files (or any other yaml file) should not contain the status elements.
See also my comment here:
https://github.com/helm/charts/pull/20419#discussion_r396422489

**Version of Helm and Kubernetes**:
Not relevant for the bug. Applies to any version.

**Which chart**:
stable/prometheus-operator

**What happened**:
When Argocd compares the status element in the CRD files with Kubernetes status then they do not match.

**What you expected to happen**:
status element should no be hard-coded in the CRD field and we should not see a change of the yaml after deployment.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
See also Kubernetes definition of status element in objects:
https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#object-spec-and-status

**Comment by yann-soubeyrand** [comment]
@ErikLundJensen I think it's fixed: https://github.com/helm/charts/pull/21824.
