### ISSUE TITLE
[stable/datadog] v2 of chart no longer supports unix socket trace agent

### ISSUE THREAD

**Issue by cep21** [helm/charts#21586]
I use unix sockets for my APM to keep ports private. This is supported by the agent with `DD_APM_RECEIVER_SOCKET` set to something like `"/var/run/datadog/apm.socket"`

The v2 of the chart no longer supports volume mounts for the APM agent.  Please modify [container-trace-agent.yaml](https://github.com/helm/charts/blob/master/stable/datadog/templates/container-trace-agent.yaml) to allow volume mounts, similar to how container agent has
```
{{- if .Values.agents.volumeMounts }}
{{ toYaml .Values.agents.volumeMounts | indent 4 }}
{{- end }}
```

**Comment by cep21** [comment]
I believe this was removed by @clamoriniere  in #18182

**Comment by clamoriniere** [comment]
Hi @cep21, 
Sorry about the issue, I will work on a fix to allow `volumeMount` in the "trace-agent" container

**Comment by cep21** [comment]
I modified container-trace-agent.yaml with the following code, which seems to work for my case
```
+    {{- if .Values.datadog.dogstatsd.useSocketVolume }}
+    - name: dsdsocket
+      mountPath: "/var/run/datadog"
+    {{- end }}
```

This works since the APM socket is in the same directory path as the DSD socket.  You could also have a new helm variable `apm.useSocketVolume` (I wasn't sure which way you wanted to go).

**Comment by cep21** [comment]
Not stale
