### ISSUE TITLE
Helm chart for BOINC?

### ISSUE THREAD

**Issue by mcandre** [helm/charts#21580]
BOINC has Docker images for finding a COVID-19 vaccine (Rosetta@Home project).

https://hub.docker.com/u/boinc

Can we get a Helm chart for Kubernetes admins to deploy this more easily?

**Comment by bacongobbler** [comment]
feel free to reach out to the BOINC community about this proposal. I'm sure they'd be interested.

transferred to helm/charts as this is a request for a new chart rather than a feature request for helm.
