### ISSUE TITLE
[stable/mongodb] MongoDB root password configmap changes on helm upgrade

### ISSUE THREAD

**Issue by devgibsonsp** [helm/charts#21583]
**Describe the bug**
When running helm upgrade on mongodb helm chart. The upgrade replaces the configmap with a new configmap for the root user password. This configmap password does not actually update the root user (thank god) but it replaces the actual root user configmap password

**Version of Helm and Kubernetes**:
Kubernetes: v1.14.6
Helm: v2.14.3

**Which chart**:
stable/mongodb

**What happened**:
helm chart replaced the configmap mongodb-root-password when running a helm upgrade

**What you expected to happen**:
I expect if a configmap already exists, that it wouldn't replace the value in it

**How to reproduce it** (as minimally and precisely as possible):
Run a helm upgrade on an existing stable/mongodb helm chart

**Comment by carrodher** [comment]
Hi,

Given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), this Bitnami maintained Helm chart is now located at [bitnami/charts](https://github.com/bitnami/charts/). Please visit the [bitnami/charts](https://github.com/bitnami/charts/) GitHub repository to create Issues or PRs.

In [this issue](https://github.com/helm/charts/issues/20969) we tried to explain more carefully the reasons and motivations behind this transition, please don't hesitate to add a comment in this issue if you have any question related to the migration itself.
