### ISSUE TITLE
[stable/minio] Remove rollme: randAlphaNum for deployment and stateful set

### ISSUE THREAD

**Issue by bradsheppard** [helm/charts#21590]
**Describe the bug**
The `rollme` attributes of `deployment.yaml` and `statefulset.yaml` causes the deployment to be updated on every invocation of `helm upgrade ...` regardless of whether or not there were any changes to the Minio configuration. I realize most people probably install the Minio Chart using
```
helm install stable/minio
```
and will hence not encounter this often, however when using this chart as a sub-chart, this issue arises more often.

**Version of Helm and Kubernetes**:
- Helm 3.1.2
- Kubernetes 1.13.12

**Which chart**:
- stable/minio version 5.0.16

**What happened**:
Deployment is updated on every invocation of `helm upgrade...`

**What you expected to happen**:
Deployment is only updated when there is a change to the configuration in the Minio subchart.

**How to reproduce it** (as minimally and precisely as possible):
- Create a new Helm chart (using `helm create`) for example.
- Add this chart as a dependency by adding the following to `Chart.yaml`
```
dependencies:
  - name: minio
    version: 5.0.16
    repository: https://kubernetes-charts.storage.googleapis.com
```
- Run `helm install ...` to install the chart.
- Run `helm upgrade ...` to upgrade the chart.
- Verify that on the `upgrade` invocation that the Minio pod is recreated.

**Anything else we need to know**:

**Comment by iirekm** [comment]
I have the same issue with minio, why this rollme was added? 
checksum/secrets checksum/config shouldn't be enough?

**Comment by acim** [comment]
It restarts the service for no obvious reason.

**Comment by hnicke** [comment]
FYI, this issue got fixed by https://github.com/helm/charts/commit/e4af2eea39bbead7ec266e2c7f14fadf436abdc6.
