### ISSUE TITLE
[stable/apm-server]failed to create Secret 

### ISSUE THREAD

**Issue by wajika** [helm/charts#21612]
Why does secret need version number v1 [apmserver.v1]?

[root@k8s-test-1 linux-amd64]# helm3 install name=apmserver \
> --set rbac.create=true \
> --set service.nodePort=8200 \
> --set service.type=nodePort \
> --set image.tag=7.6.1 \
> --set image.repository=docker.elastic.co/apm/apm-server \
>     stable/apm-server
Error: create: failed to create: Secret "sh.helm.release.v1.name=apmserver.v1" is invalid: [metadata.name: Invalid value: "sh.helm.release.v1.name=apmserver.v1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "name=apmserver": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]

**Comment by victorBychinski** [comment]
The same problem when running
 helm install --wait selenium_hub --set chrome.enabled=true --set chrome.replicas=10 stable/selenium

> Error: create: failed to create: Secret "sh.helm.release.v1.selenium_503.v1" is invalid: metadata.name: Invalid value: "sh.helm.release.v1.selenium_503.v1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**Comment by wajika** [comment]
The problem has been solved.
Do not use "name=apmserver"
