### ISSUE TITLE
stable/nginx-ingress upgrade from 1.7.0 to 1.34.2 fail

### ISSUE THREAD

**Issue by rj03hou** [helm/charts#21632]
**Describe the bug**
stable/nginx-ingress upgrade from 1.7.0 to 1.34.2 fail

helm ls|grep nginx-ingress
test-nginx-ingress                      1           Mon Sep  2 17:56:22 2019    DEPLOYED    nginx-ingress-1.7.0                     0.24.1      nginx-controller

helm upgrade test-nginx-ingress stable/nginx-ingress --reuse-values  --version 1.34.2
Error: UPGRADE FAILED: render error in "nginx-ingress/templates/admission-webhooks/job-patch/serviceaccount.yaml": template: nginx-ingress/templates/admission-webhooks/job-patch/serviceaccount.yaml:1:18: executing "nginx-ingress/templates/admission-webhooks/job-patch/serviceaccount.yaml" at <.Values.controller.a...>: can't evaluate field enabled in type interface {}

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-aae39f", GitCommit:"aae39f4697508697bf16c0de4a5687d464f4da81", GitTreeState:"clean", BuildDate:"2019-12-23T08:19:12Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

stable/nginx-ingress

**What happened**:

upgrade from 1.7.0 to 1.34.2 fail

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

helm install stable/nginx-ingress --version 1.7.0 --name test-nginx-ingress
helm upgrade test-nginx-ingress stable/nginx-ingress --reuse-values  --version 1.34.2

**Anything else we need to know**:

**Comment by achevalet** [comment]
same issue here when updating from 0.26.0 to 1.39.1

```
#  helm version 
Client: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}

# helm ls
NAME            	REVISION	UPDATED                 	STATUS  	CHART               	APP VERSION	NAMESPACE   
nginx-ingress   	2       	Mon Jun 22 16:43:34 2020	FAILED  	nginx-ingress-1.39.1	0.32.0     	kube-system 
```

**Comment by logicbomb421** [comment]
same issue when upgrading from `1.4.0` to `1.40.1`:

```
Client: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
```
