### ISSUE TITLE
[stable/datadog] DD_TAGS is generated with `[]` surrounding the values

### ISSUE THREAD

**Issue by nesl247** [helm/charts#21663]
**Describe the bug**
`DD_TAGS` is expected to be of the format `value: "key:value key2:value2"`, instead it is `value: "[key:value key2:value2]"`.

**Version of Helm and Kubernetes**:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

**Which chart**:
stable/datadog

**Comment by clamoriniere** [comment]
Hi @nesl247 

Thank you for reporting this issue. We have included a fix in the pull request #22006.

Cedric
