### ISSUE TITLE
[stable/rabbitmq-ha] Deprecate rabbitmq-ha in favor of rabbitmq

### ISSUE THREAD

**Issue by lwj5** [helm/charts#21665]
**Which chart**:
stable/rabbitmq-ha

**What happened**:
rabbitmq-ha has replication abilities from version 0.7.1. It would be better if efforts were taken to focus on a single chart than having 2 forks with almost the same capabilities.

There are minimal differences between the two charts now.

**What you expected to happen**:
deprecate rabbitmq-ha in favor of bitnami/rabbitmq

**Anything else we need to know**:
What do you think @steven-sheehy

**Comment by steven-sheehy** [comment]
Does it matter? This entire repository is being [deprecated](https://github.com/helm/charts#deprecation-timeline) in a couple months.

**Comment by lwj5** [comment]
There are still 2 months to de-listing, which means new users could be launching this chart.

I see that there are still PRs for new features, some of which could have gone to the bitnami/rabbitmq. For new features that are not available on bitnami/rabbitmq, when users migrate they will need to create new PR on that chart to get these features. This means extra work.

Why not just do it right now? or at least put a note that this chart is chart will not be maintained after May and refer people to use bitnami/rabbitmq which has HA abilities now as well.
