### ISSUE TITLE
[stable/prometheus-operator] Thanos sidecar unable to connect to prometheus

### ISSUE THREAD

**Issue by bcochofel** [helm/charts#21674]
Hi all,

I'm trying to deploy the prometheus-operator with custom values for thanos sidecar. I'm usign the following configuration for prometheus:

`
prometheus:

  prometheusSpec:

    disableCompaction: true

    listenLocal: true

    image:

      repository: quay.io/prometheus/prometheus

      tag: v2.16.0

    externalUrl: "http://localhost:9090"

    thanos:

      baseImage: quay.io/thanos/thanos

      version: v0.11.0

      objectStorageConfig:

        key: thanos.yaml

        name: thanos-objstore-config
`

no matter what the values of "listenLocal" or "externalUrl" I put in I keep getting this error message on the logs of thanos sidecar

`level=warn ts=2020-03-29T13:13:20.670607788Z caller=sidecar.go:367 msg="failed to get Prometheus flags. Is Prometheus running? Retrying" err="request config against http://127.0.0.1:9090/api/v1/status/flags: Get http://127.0.0.1:9090/api/v1/status/flags: dial tcp 127.0.0.1:9090: connect: connection refused"
level=info ts=2020-03-29T13:13:22.731270438Z caller=sidecar.go:219 msg="successfully loaded prometheus external labels" external_labels="{prometheus=\"monitoring/k8s-prometheus\", prometheus_replica=\"prometheus-k8s-prometheus-0\"}"
level=info ts=2020-03-29T13:13:22.731761917Z caller=intrumentation.go:52 msg="changing probe status" status=ready`

Anyone using this to deploy thanos sidecar?

Thanks,
Bruno

**Comment by MakeshKathirvel** [comment]
I'm getting the same error.
Did you find any workaround @bcochofel

**Comment by bcochofel** [comment]
Hi, I think this error happens only in the beginning because after a while it works.

Bruno
