### ISSUE TITLE
[stable/nextcloud] Upgrade to latest version

### ISSUE THREAD

**Issue by msoderberg** [helm/charts#21683]
The latest chart version (1.9.2) deploys app version 17.0.0. Any ETA on when a new chart version will be released that deploys the latest version of nextcloud (18.0.3)?

One option would be to just set `image.tag` to the latest version, but since this is a major release we're a bit cautious. If this is the recommended way of upgrading it'd be nice to have an `Upgrade` section in the readme about it.

**Comment by thannaske** [comment]
Just upgrade your image's tag and the upgrade will be performed automatically using Nextcloud's `occ` utility inside the container. Read more at the Nextcloud's Docker image documentation: https://github.com/nextcloud/docker
