### ISSUE TITLE
[stable/postgresql] Permission's error installing chart 8.6.3 and warning

### ISSUE THREAD

**Issue by mkanakis** [helm/charts#21689]
**Describe the bug**
I have been using version 8.4.3 for a while now. Today I attempted to install 8.6.3 which led to a **chmod** permissions error. 

After removing the chart and re-installing it with:

`
volumePermissions:        
  enabled: "true"
`

It deployed successfully with an init Container as well but also gave the following warning:

`postgresql 14:44:14.25 WARN ==> Data directory is set with a legacy value, adapting POSTGRESQL_DATA_DIR...`
`
postgresql 14:44:14.25 WARN ==> POSTGRESQL_DATA_DIR set to "/var/lib/bitnami/postgresql/data"!!
`

I don't mind having an init container running, however I am worried to upgrade the rest of the containers due to this warning. Should I be worried upgrading from 8.4.3 to 8.63? Will this affect existing data somehow?

**Version of Helm and Kubernetes**:
Helm Version -> v2.14.3-rancher1
Kubernetes Version -> 1.17.4

Thanks.

**Comment by carrodher** [comment]
Hi,

Given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), this Bitnami maintained Helm chart is now located at [bitnami/charts](https://github.com/bitnami/charts/). Please visit the [bitnami/charts](https://github.com/bitnami/charts/) GitHub repository to create Issues or PRs.

In [this issue](https://github.com/helm/charts/issues/20969) we tried to explain more carefully the reasons and motivations behind this transition, please don't hesitate to add a comment in this issue if you have any question related to the migration itself.

**Comment by mkanakis** [comment]
Thanks, I will post it there.
