### ISSUE TITLE
stable/jenkins Make isn't included in workers

### ISSUE THREAD

**Issue by krisclarkdev** [helm/charts#21691]
**Describe the bug**
When running a jenkins job that requires make the worker node that is spun up doesn't include make and errors out

**Version of Helm and Kubernetes**:
Helm v3.0.2
Kubernetes 1.17.0

**Which chart**:
stable/jenkins

**What happened**:
`/tmp/jenkins5831475746285654417.sh: 2: /tmp/jenkins5831475746285654417.sh: make: not found
Build step 'Execute shell' marked build as failure
Finished: FAILURE`

**What you expected to happen**:
This should have compiled my Go project

**How to reproduce it** (as minimally and precisely as possible):

- Install stable/jenkins
- Create a freestyle project
- Install and configure both git and Go plugins
- Pull source from git, any source will do, I'm testing this with telegraf
- Add an "execute bash" build step with the command "make"
- Build the project

**Anything else we need to know**:
No

**Comment by njtman** [comment]
Why not just spin up an ephemeral build pod with `make` installed on one of the containers?
You can use the Kubernets plugin to achieve this https://github.com/jenkinsci/kubernetes-plugin

Also this issue isn't specific to the Jenkins Helm chart so this probably isn't the best place to open such a ticket.
