### ISSUE TITLE
Grafana - MySQL backend support

### ISSUE THREAD

**Issue by hzproe** [helm/charts#21696]
Deploying Grafana on my Kubernetes environment using the Helm Chart.

Feature:

currently there is no possibility to define MySQL as database backend for a Grafana deployment using helm. It would be very much appreciated if this could be enabled.

Currently I am manually adopting the configmap "grafana" by adding the section database. But on Upgrade f.e. installing a new plugin, this gets overwritten which results in manual fixing after the installation of a plugin.

  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    **[database]
    type = mysql
    host = <somehost>
    name = grafana
    user = grafana
    password = <somepassword>**

**Comment by DrDonoso** [comment]
You can override this with environment variables. Take a look: https://grafana.com/docs/grafana/latest/installation/configuration/#configure-with-environment-variables
