### ISSUE TITLE
[stable/elasticsearch-curator] add startingDeadlineSeconds in cronjob spec

### ISSUE THREAD

**Issue by ruccoon** [helm/charts#21699]
**Is your feature request related to a problem? Please describe.**
The current stable/elasticsearch-curator chart doesn't support  **startingDeadlineSeconds** spec in curator cronjob

**Describe the solution you'd like**
https://github.com/helm/charts/blob/master/stable/elasticsearch-curator/templates/cronjob.yaml
in **spec** block, add the followings:
```
  {{- with .Values.cronjob.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
  {{- end }}
```

**Comment by mihau** [comment]
Need the exact same thing. Your solution seems ok. I think you should go ahead and create a merge request.

**Comment by ruccoon** [comment]
> Need the exact same thing. Your solution seems ok. I think you should go ahead and create a pull request.

hi @mihau , thanks for your reply. I don't have permission to create new branch and PR in this repo
