### ISSUE TITLE
Use `sh` instead of `bash` so that users could run with alpine images, which is lighter.

### ISSUE THREAD

**Issue by xinxiao** [helm/charts#21695]
https://github.com/helm/charts/blob/5a8cfbe5729cb64cc2995326769de89246e37809/stable/redis/templates/redis-master-statefulset.yaml#L78

**Comment by juan131** [comment]
Hi @xinxiao 

Given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), this Bitnami maintained Helm chart is now located at [bitnami/charts](https://github.com/bitnami/charts/). Please visit the [bitnami/charts](https://github.com/bitnami/charts/) GitHub repository to create Issues or PRs.

In [this issue](https://github.com/helm/charts/issues/20969) we tried to explain more carefully the reasons and motivations behind this transition, please don’t hesitate to add a comment in this issue if you have any question related to the migration itself.
