### ISSUE TITLE
MySQL root password no longer valid after upgrade

### ISSUE THREAD

**Issue by mstrzele** [helm/charts#217]
It's because the password is random generated inside the template of a secret and after each upgrade it is changed.

```
$ helm install stable/mysql -n foo
# ...
To get your root password run:

    printf $(printf '\%o' `kubectl get secret --namespace default foo-mysql -o jsonpath="{.data.mysql-root-password[*]}"`);echo
# ...
$ printf $(printf '\%o' `kubectl get secret --namespace default foo-mysql -o jsonpath="{.data.mysql-root-password[*]}"`);echo
SpeSUQshnK
$ helm upgrade foo stable/mysql
$ printf $(printf '\%o' `kubectl get secret --namespace default foo-mysql -o jsonpath="{.data.mysql-root-password[*]}"`);echo
EiKA8TDMp9
```

**Comment by viglesiasce** [comment]
I opened the issue above which will need to be fixed before we can react to this. 

@prydonius @lachie83 any ideas on other workarounds?

**Comment by prydonius** [comment]
@viglesiasce currently the only workaround would be to explicitly set the same password as a value when upgrading.

**Comment by sstarcher** [comment]
@viglesiasce with the above Issue linked from helm is the intention to wrap the secret yaml in a 
{{ if .Release.IsInstall }}

{{ end }}

Sensu has this same problem on upgrades as it uses the Redis chart.

**Comment by sstarcher** [comment]
and if we did the above it would delete the secrets object entirely

**Comment by prydonius** [comment]
Thanks @sstarcher. I wonder if there's a way to tell Helm not to remove the secret on upgrade?

**Comment by mikesplain** [comment]
Wouldn't it also be possible to use a job to create the secret and only run that job at install?  You could use a hook to run the job before everything else too.  I know it's ugly but could work?

**Comment by prydonius** [comment]
@mikesplain hmm, you can also actually mark Secrets themselves as pre-install hooks, so you might not need a job to do that.

**Comment by mikesplain** [comment]
@prydonius right but wouldn't that still have the above problem of overriding each time?

**Comment by sstarcher** [comment]
Per the documentation and a test it looks like pre-install hooks are ran every time even on upgrades.

https://github.com/kubernetes/helm/blob/9665db7d165cc4129bea2456fffa53aaed34af41/docs/charts_hooks.md#the-available-hooks

**Comment by gmistick** [comment]
this just happened to us, how do we prevent this?

**Comment by andrewhowdencom** [comment]
For Googles et. al; to prevent this, specify a root (and user) password that overrides the default (random) root password.

**Comment by gmistick** [comment]
@andrewhowdencom - That didn't work on upgrade attempts. (Tried to remove grants table but that also didnt last... )
The solution for us was to:
1. Upgrade values to have skip-grant-tables
2.backup db
3. Delete and purge the helm chart.
4. Re install with those values, and not use the ROOT creds.


Will that solve my existing deployment issue or i need to reinstall ?
