### ISSUE TITLE
[stable/prometheus-adapter] Documentation: logLevel parameter information

### ISSUE THREAD

**Issue by calebwoofenden** [helm/charts#21701]
**Is your feature request related to a problem? Please describe.**
The documentation for this chart specifies that you can give it a `logLevel` parameter that has a default value of `4`. It's not immediately obvious to me what this number means or what other numbers I could give to this parameter.

**Describe the solution you'd like**
It would be nice to enumerate on the documentation what values this parameter recognizes and what each value represents to this parameter.

**Comment by metost** [comment]
bump
