### ISSUE TITLE
Invalid security context for initContainer

### ISSUE THREAD

**Issue by caiges** [helm/charts#21739]
**Describe the bug**
The security context for the init container contains `fsGroup` which isn't valid.

**Version of Helm and Kubernetes**:
`v3.1.2`

**Which chart**:
rabbitmq-ha

**What happened**:
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.initContainers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext`

**What you expected to happen**:
The chart to install successfully.

**How to reproduce it** (as minimally and precisely as possible):
Try installing it.

**Anything else we need to know**:
It was related to #21344, specifically: https://github.com/helm/charts/pull/21344/files#diff-e00e6fcd2c8b56c1bd9161e193b126fdR72

**Comment by Doqnach** [comment]
Is there any work-around for now, till the PR gets merged & released?
