### ISSUE TITLE
[stable/cluster-autoscaler] the chart has defined a .Values.rbac.serviceAccount.name, but it's not used

### ISSUE THREAD

**Issue by gazal-k** [helm/charts#21743]
**Describe the bug**

**Version of Helm and Kubernetes**:
helm v3.1.2
kubernetes v1.14.9

**Which chart**:
stable/cluster-autoscaler

**What happened**:
The chart has defined `.Values.rbac.serviceAccount.name`, but it's not used in the SA. Instead it just uses named template `cluster-autoscaler.fullname`. There's also a named template `serviceaccount.name` which mostly defaults to `cluster-autoscaler.fullname` instead of using `.Values.rbac.serviceAccount.name`

**What you expected to happen**:
If `.Values.rbac.serviceAccount.name` is set, I think it should be used for the name of SA.

**How to reproduce it** (as minimally and precisely as possible):
```sh
helm install --set rbac.serviceAccount.name=cluster-autoscaler \
cluster-autoscaler stable/cluster-autoscaler
```

**Anything else we need to know**:

**Comment by andrewkaczynski** [comment]
There is something wrong with a new chart... I'm trying to install cluster auto scaler today, here is an excerpt from my values.yaml

`rbac:
  create: true
  serviceAccount:
    create: true
    name: cluster-autoscaler
`
I'm getting this error on Helm v3.1.2

`Error: template: cluster-autoscaler/templates/_helpers.tpl:79:14: executing "cluster-autoscaler.serviceAccountName" at <.Values.serviceAccount.create>: nil pointer evaluating interface {}.create`

@gazal-k can you check it again ??
