### ISSUE TITLE
[stable/grafana] dashboard sidecard doesn't delete removed dashboard in HA mode

### ISSUE THREAD

**Issue by maxkokocom** [helm/charts#21765]
**Describe the bug**
While running grafana in HA mode (3 replicas with Postgres) you can not delete the provisioned dashboard manually or automatically. Sidecar is deleting them only from one pod. For example with 3 pods two out of three times you connect to grafana there are still all of the old dashboards.

**Which chart**:
[stable/grafana]

**What you expected to happen**:
I expect sidecar to remove dashboards from all replicas.

**How to reproduce it** (as minimally and precisely as possible):
1.) set grafana replicas to 3, 
2.) add postgress settings, 
3.) enable sidecar for dashboards, 
4.) create some configmaps with few dashbords
5.) delete those configmaps and refresh grafana page few times to see were they deleted from all grafanas pods

**Comment by ksiadz** [comment]
Any update on that? It's still an issue.
