### ISSUE TITLE
[stable/anchore-engine] Using anchoreGlobal.existingSecret doesn't work since 1.4.3

### ISSUE THREAD

**Issue by jujugrrr** [helm/charts#21763]
**Describe the bug**
Using anchoreGlobal.existingSecret doesn't work since 1.4.3

**Version of Helm and Kubernetes**:
3, 1.14

**Which chart**:

1.4.3

**What happened**:

Chart apply succeeded, but pod fails to start

**What you expected to happen**:

All pod starting

**How to reproduce it** (as minimally and precisely as possible):

Set: 
```
anchoreGlobal:
  existingSecret: anchore-passwords
```

the engine-api pod will return an error: 
```
 Error: secrets "release-name-anchore-engine" not found
```
@masseybradley It was introduced in https://github.com/helm/charts/pull/20524#issuecomment-608737246.

Should https://github.com/helm/charts/blob/master/stable/anchore-engine/templates/api_deployment.yaml#L94 not fall back to the parameter above like https://github.com/helm/charts/blob/master/stable/anchore-engine/templates/api_deployment.yaml#L77.

Because the default secret will not exist otherwise https://github.com/helm/charts/blob/master/stable/anchore-engine/templates/secrets.yaml#L1

**Comment by masseybradley** [comment]
Hi @jujugrrr - what version are you upgrading from?

**Comment by masseybradley** [comment]
Yeah, had a look at it, seems correct. Thanks for the investigation. Should be fixed if / when the PR is merged :+1:

**Comment by jujugrrr** [comment]
Thanks for the quick fix 👍
