### ISSUE TITLE
[stable/nfs-client-provisioner] What format do you expect nfs.mountOptions?

### ISSUE THREAD

**Issue by auras** [helm/charts#21768]
I tried adding `uid=501,gid=1000`

But this happens: `Error: render error in "nfs-client-provisioner/templates/storageclass.yaml": template: nfs-client-provisioner/templates/storageclass.yaml:22:19: executing "nfs-client-provisioner/templates/storageclass.yaml" at <.Values.nfs.mountOptions>: range can't iterate over uid=501,gid=1000 : exit status 1`

**Comment by spyle** [comment]
https://github.com/helm/charts/issues/21731
$ helm install stable/nfs-server-provisioner --name my-release \
  --set=image.tag=v1.0.8,resources.limits.cpu=200m,storageClass.mountOptions="{vers=4.1,noatime}"

**Comment by auras** [comment]
Thank you!
