### ISSUE TITLE
Deprecation notice of MongoDB says about Redis.

### ISSUE THREAD

**Issue by michael-l-a** [helm/charts#21770]
https://github.com/helm/charts/blob/82cd67703a8034bd25bd80cb8c36d1e7154d9042/stable/mongodb/Chart.yaml#L5

There is a deprecation notice. And it says that Redis is deprecated. Right in the MondoDB chart. I guess, it was just copied as is from Redis.

**Comment by carrodher** [comment]
Thanks, it was a copy/paste error, I just created a PR fixing it
