### ISSUE TITLE
stable/anchore-engine HELM3 issue on K8s 1.17

### ISSUE THREAD

**Issue by texanraj** [helm/charts#21785]
The following command does not work. Should be a straightforward install.

helm install anchore -f anchore_values.yaml stable/anchore-engine -n anchore
Error: unable to build kubernetes objects from release manifest: unable to recognize "": **### no matches for kind "Deployment" in version "extensions/v1beta1"**

I'm running on Minikube v1.6.2

**Comment by xforze** [comment]
Seems to be that the chart is no longer compatible with newer Versions of K8S :-(
Deployment moved to API Group apps/v1

**Comment by zhill** [comment]
This is a known issue that we're working on and trying to keep as smooth an upgrade process as possible. Note that the issue you're hitting is for the deployment of the postgres db, and there are workarounds for that if you're able to use an external DB such as RDS/Cloud SQL, which we highly recommend for production environments.

**Comment by texanraj** [comment]
I was able to fix this by doing the following to my minikube cluster. Note: I'm running 1.17 K8s. Your mileage might vary.

1) Login to the minikube node - minikube ssh -p <name of your cluster>

2) Add the following argument to /etc/kubernetes/manifest/kube-apiserver.yaml  if you are running Kubernetes 1.16 or 1.17  - add the following line 
--runtime-config=apps/v1beta1=true,apps/v1beta2=true,extensions/v1beta1/daemonsets=true,ex
