### ISSUE TITLE
Installing rabbitmq-ha chart is failing with unknown field "fsGroup"

### ISSUE THREAD

**Issue by gangadharmgithub** [helm/charts#21790]
NAME              	CHART VERSION	APP VERSION	DESCRIPTION                                       
stable/rabbitmq-ha	1.44.0       	3.8.0      	Highly available RabbitMQ cluster, the open sou...

Kubernetes version
{
  "clientVersion": {
    "major": "1",
    "minor": "16",
    "gitVersion": "v1.16.0",
    "gitCommit": "2bd9643cee5b3b3a5ecbd3af49d09018f0773c77",
    "gitTreeState": "clean",
    "buildDate": "2019-09-18T14:36:53Z",
    "goVersion": "go1.12.9",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "serverVersion": {
    "major": "1",
    "minor": "17",
    "gitVersion": "v1.17.3",
    "gitCommit": "13db51798ca68c34fddd26afb9cb27eab016e488",
    "gitTreeState": "clean",
    "buildDate": "2020-02-21T11:07:44Z",
    "goVersion": "go1.13.6",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}

 helm  install --set rabbitmqUsername="rmq_user1" \
         --set rabbitmqPassword="rmq_user1" \
         --set managementUsername="rmq_mgr1" \
         --set managementPassword="rmq_mgr1"\
         "test_rmq_ha" stable/rabbitmq-ha  --namespace "production"

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.initContainers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext

**Comment by gangadharmgithub** [comment]
I see that the below pull request is introducing fsGroup at the container level. fsGroup is valid only at the pod level.

https://github.com/helm/charts/pull/21344
This 

A similar issue is fixed for postgresql helm chart. https://github.com/helm/charts/pull/11406

**Comment by iirekm** [comment]
+1

**Comment by iirekm** [comment]
does anybody ever test this chart? other issues happen in recent versions like  no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"

1.44.1 worked for me

**Comment by michelefa1988** [comment]
+1
When will it be fixed?

**Comment by samuelfischerscandio** [comment]
This also a problem on the 
**stable/mongodb-replicaset** 
Helm Chart. 

If the metrics are enabled and a contianer securityContext is created for that mongodb-exporter the "fsGroup unknown field" error comes up.

**Comment by steven-sheehy** [comment]
This was fixed by #21740 and available in version 1.44.1+. Please confirm and close this issue.

**Comment by gangadharmgithub** [comment]
Verified the fix in the latest version. Thanks for fixing it.
