### ISSUE TITLE
[stable/prometheus-blackbox-exporter] DaemonSet template is wrong

### ISSUE THREAD

**Issue by marin-ante** [helm/charts#21811]
**Describe the bug**
DaemonSet template for Blackbox is wrong: contains "replicas" and "strategy" fields, which are not part of DaemonSet spec (guessing c/p error) and should be removed.

**Version of Helm and Kubernetes**:
K8S   v1.15.3
Helm v3.1.2

**Which chart**:
stable/prometheus-blackbox-exporter v.3.4.0 (latest as of writing)

**What happened**:
Error templating Chart

**What you expected to happen**:
Clean install

**How to reproduce it** (as minimally and precisely as possible):
Deploy Blackbox chart as DaemonSet

**Anything else we need to know**:

**Comment by Maxpain177** [comment]
This is still not fixed
