### ISSUE TITLE
[stable/nginx-ingress] Allow use of container image digest in tag for nginx-ingress

### ISSUE THREAD

**Issue by jeffb4** [helm/charts#21821]
**Is your feature request related to a problem? Please describe.**
I am unable to specify the tag of the nginx-ingress controller image to use with a sha digest value.

**Describe the solution you'd like**
I'd like the semver check to manipulate the string for tag to exclude a digest

**Describe alternatives you've considered**
Alternatively, a flag value or way to pass an explicit version of the container image would suffice

**Comment by jeffb4** [comment]
Not knowing if this repo auto-notifies owners, this is for @ChiefAlexander and @taharah

**Comment by ChiefAlexander** [comment]
This should probably work...

You can change the image repo to:
```
controller.image.repository=quay.io/kubernetes-ingress-controller/nginx-ingress-controller@sha256
```

Then set image tag to your sha value:
```
controller.image.tag=b312c91d0de688a21075078982b5e3a48b13b46eda4df743317d3059fc3ca0d9
```

**Comment by jeffb4** [comment]
you do a semverCompare check against the tag that fails with the sha sum, though

**Comment by ChiefAlexander** [comment]
Ah yes, you are correct... This chart is being moved to the upstream ingress-nginx repo. I think it would be good to have this there as the chart in this repo is being deprecated.
