### ISSUE TITLE
[stable/grafana] hostAliases support

### ISSUE THREAD

**Issue by alexandrud** [helm/charts#21835]
Hi,

I would like to request hostAliases support for the grafana helm chart. The change should be trivial.  Bellow you have a diff output for _pod.yaml.

```
***************
*** 13,18 ****
--- 13,22 ----
  {{- if .Values.priorityClassName }}
  priorityClassName: {{ .Values.priorityClassName }}
  {{- end }}
+ {{- if .Values.hostAliases }}
+ hostAliases:
+ {{ toYaml .Values.hostAliases | indent 2 }}
+ {{- end }}
  {{- if ( or .Values.persistence.enabled .Values.dashboards .Values.sidecar.datasources.enabled .Values.extraInitContainers) }}
  initContainers:
  {{- end }}
```

In the example "values.yaml"  I've added something like this: 
```
hostAliases:
- hostnames:
  - fqdn.example.com
  ip: 1.2.3.4
```

This can be useful in certain cases and I'd really like to use the helm chart in stable instead of keeping a branched out version in my own chart repository.

Thank you!

**Comment by alequadro** [comment]
this would be very useful for me since i have Traefik on my cluster and I still have to figure out how to communicate with Prometheus
