### ISSUE TITLE
[stable/kube-state-metrics] clusterrole and binding use wrong rbac key for enabling

### ISSUE THREAD

**Issue by david-curran-90** [helm/charts#21834]
**Describe the bug**
templates/psp-clusterole.yaml and templates/psp-clusterrolebinidng.yaml check fro rbac.enabled to test if they should be created. Values.yaml specifies rbac.create but no rbac.enable.

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
kube-state-metrics

**What happened**:
cluster role and binding created even when not required

**What you expected to happen**:
cluster role and binding should not be created

**How to reproduce it** (as minimally and precisely as possible):
Deploy chart without rbac enabled

rbac.enable: false

**Anything else we need to know**:
I encountered this issue when providing my own values.yaml to the prometheus-operator chart.

**Comment by maci0** [comment]
ran into the same issue. workaround for me was to add another key to my local values file.

**Comment by mrueg** [comment]
I believe this is fixed in d155361800d4a005080f6dfaa5afba8998f1ede8
