### ISSUE TITLE
[stable/verdaccio] spec.clusterIP: Invalid value: "": field is immutable

### ISSUE THREAD

**Issue by himanshumehta1114** [helm/charts#21840]
**Describe the bug**
When I run helm upgrade <release> stable/verdaccio --install -f values.yaml --wait

**Version of Helm and Kubernetes**:
Helm- v2.16.1
Kubectl- v1.16.1

**Which chart**:
stable/verdaccio

**What happened**:
I'm not able to upgrade helm with configuration present in values.yaml.
when running helm upgrade <release> stable/verdaccio --install -f values.yaml --wait

I get `spec.clusterIP: Invalid value: "": field is immutable` error

**What you expected to happen**:
helm should upgrade successfully

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by juanpicado** [comment]
@himanshumehta1114 be aware of 
https://github.com/verdaccio/verdaccio/issues/1767
https://github.com/verdaccio/charts

**Comment by himanshumehta1114** [comment]
@juanpicado Deleting the verdaccio service and running `helm upgrade` fixed this issue.

Hence closing this issue.
