### ISSUE TITLE
[stable/atlantis] Most recent version breaks multiline values in AWS credentials

### ISSUE THREAD

**Issue by bmckalla** [helm/charts#21855]
**Describe the bug**
On the most recent commit/version update, [toYaml was used](https://github.com/helm/charts/commit/576f42c8a24de64b11fd8c90cebd2369608b2580#diff-fea0c6ef0fc136a6896aede527794786R13) which broke multiline strings.

**Version of Helm and Kubernetes**:
Helm: client v2.16.5 - server v2.16.1
Kube: client v1.17.2 - server v1.14.9-eks-502bfb

**Which chart**:
[stable/atlantis] secret-aws.yaml

**What happened**:
If you do something like:
```
aws:
    credentials: |
        [default]
        aws_access_key_id=SOME_ACCESS_KEY
        aws_secret_access_key=SOME_SECRET
        region=REGION
```
It will then format the `/home/atlantis/.aws/config` as:

```
 |
        [default]
        aws_access_key_id=SOME_ACCESS_KEY
        aws_secret_access_key=SOME_SECRET
        region=REGION
```

**What you expected to happen**:
It should be formatted as:

```
[default]
aws_access_key_id=SOME_ACCESS_KEY
aws_secret_access_key=SOME_SECRET
region=REGION
```

I think if you remove `toYaml` it should resolve the issue.

**How to reproduce it** (as minimally and precisely as possible):
See above

**Anything else we need to know**:
The [values.yaml](https://github.com/helm/charts/blob/master/stable/atlantis/values.yaml#L61) for Atlantis also specify to format it the way that I did

**Comment by KernCheh** [comment]
https://github.com/helm/charts/pull/21554
