### ISSUE TITLE
[stable/datadog] Not all APM env variable values will resolve to strings, resulting in an error

### ISSUE THREAD

**Issue by lucasreed** [helm/charts#21853]
**Describe the bug**

As [documented here](https://docs.datadoghq.com/agent/docker/apm/?tab=java#docker-apm-agent-environment-variables) some of the APM values should be a quoted integer. For example when setting `DD_APM_MAX_EPS` to an integer, the way the chart is currently written will result in:
```yaml
env:
  DD_APM_MAX_EPS: 400,
...
```

But it should be:
```yaml
env:
  DD_APM_MAX_EPS: "400",
...
```

Kubernetes requires any environment variable in a container spec to be a string. The `toYaml` function in helm converts this to an integer.

We are using an older version of the chart (1.39.9), but I can see similar usage of `toYaml` throughout the templates. [See this template as an example that is used in all containers](https://github.com/helm/charts/blob/master/stable/datadog/templates/containers-common-env.yaml#L34)

**Version of Helm and Kubernetes**:
Any version of helm that supports the `toYaml` function (essentially any recent version) and any version of kubernetes will have this issue

**Which chart**:
stable/datadog

**What happened**:
In our values file we set this:

```yaml
      datadog:
        env:
          - name: DD_APM_MAX_EPS
            value: "400"
```

This error happened (the release name is datadog-statsd):
```
cannot patch "datadog-statsd" with kind Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 4, error found in #10 byte of ...|,"value":400}],"imag|..., bigger context ...|ess.request=1"},{"name":"DD_APM_MAX_EPS","value":400}],"image":"datadog/agent:7","imagePullPolicy":"|...
```

**What you expected to happen**:

The chart should set any environment variables from `datadog.env` as a string explicitly by quoting it. This would prevent the usage of the `toYaml` function like it is currently written as far as I know.

**How to reproduce it** (as minimally and precisely as possible):

Set any environment variable that expects an integer with a quoted int in the values section:
`datadog.env`

**Anything else we need to know**:
As an example of a fix, I am imagining something like this iterating over the extra env variables provided in a values file:
```
      env:
      {{- range $index, $value := .Values.datadog.env }}
        {{ $index}}: {{ $value | quote}}
      {{- end }}
```

Either that or make sure every env variable is represented in the default `values.yaml` so it can explicitly be set and then quoted by the chart.

**Comment by clamoriniere** [comment]
Hi @lucasreed  

Thank you for reporting this issue. We have included a fix in the pull request #22006.

Cedric
