### ISSUE TITLE
Storage is filled up with crash log files(ex: core.1160) 

### ISSUE THREAD

**Issue by amunaf** [helm/charts#21891]
I had a three node setup cluster of patroni with kuberenetes. Successfully created postgres cluster. Within 15-20 mins of cluster creation 200gb storage is filling up. Below are the files in pv disk:

[root@vitest-pg-ha1 data]# df -h .
Filesystem Size Used Avail Use% Mounted on
/dev/vdc1 200G 200G 24K 100% /mnt/postgresdb

[root@vitest-pg-ha1 data]# ls
base core.1358 core.1761 core.4592 core.850 patroni.dynamic.json pg_ident.conf.backup pg_snapshots PG_VERSION postgresql.conf
core.1053 core.1397 core.1854 core.4682 core.926 pg_commit_ts pg_logical pg_stat pg_wal postgresql.conf.backup
core.1160 core.1457 core.1957 core.471 core.951 pg_dynshmem pg_multixact pg_stat_tmp pg_xact postmaster.opts
core.1183 core.1460 core.4297 core.4768 core.983 pg_hba.conf pg_notify pg_subtrans postgresql.auto.conf recovery.conf
core.1259 core.1553 core.4389 core.4808 current_logfiles pg_hba.conf.backup pg_replslot pg_tblspc postgresql.base.conf recovery.done
core.1320 core.1660 core.4481 core.701 global pg_ident.conf pg_serial pg_twophase postgresql.base.conf.backup

[amunaf@vitest-pg-cluster ~]$ kubectl get pods -L spilo-role
NAME                 READY   STATUS    RESTARTS   AGE    SPILO-ROLE
postgres-patroni-0   1/1     Running   0          156m
postgres-patroni-1   1/1     Running   0          156m
postgres-patroni-2   1/1     Running   0          156m

Please help me on this.

**Comment by carrodher** [comment]
Hi,

Given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), this Bitnami maintained Helm chart is now located at [bitnami/charts](https://github.com/bitnami/charts/). Please visit the [bitnami/charts](https://github.com/bitnami/charts/) GitHub repository to create Issues or PRs.

In [this issue](https://github.com/helm/charts/issues/20969) we tried to explain more carefully the reasons and motivations behind this transition, please don't hesitate to add a comment in this issue if you have any question related to the migration itself.

Please, take into account that in the Bitnami catalog also a PostgreSQL HA chart exists that was based on the regular PostgreSQL chart but adding some features to guarantee high availability:

- A new deployment, service and ingress have been added to deploy [Pgpool-II](Pgpool-II) to act as proxy for PostgreSQL backend. It helps to reduce connection overhead, acts as a load balancer for PostgreSQL, and ensures database node failover.
- Replacing `bitnami/postgresql` with `bitnami/postgresql-repmgr` which includes and configures [repmgr](https://repmgr.org/). Repmgr ensures standby nodes assume the primary role when the primary node is unhealthy.
