### ISSUE TITLE
[stable/jenkins] Adding custom plugin and it's configuration

### ISSUE THREAD

**Issue by dkhode** [helm/charts#21898]
**Is your feature request related to a problem? Please describe.**
Does Jenkins helm chart has an option to add custom plugin, which is not available by default in plugins?
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I had to build the plugin using the codebase https://github.com/newrelic/nr-jenkins-plugin . Just wondering how I can upload this plugin in to the helm chart. And also I have to add it's configuration(as shown below)

**com.newrelic.experts.jenkins.extensions.NewRelicGlobalConfiguration.xml**
```
<?xml version='1.1' encoding='UTF-8'?>
<com.newrelic.experts.jenkins.extensions.NewRelicGlobalConfiguration plugin="new-relic@1.0.1">
  <insightsInsertCredentialsId>insights-insert-key</insightsInsertCredentialsId>
</com.newrelic.experts.jenkins.extensions.NewRelicGlobalConfiguration>
```

**Comment by torstenwalter** [comment]
You could use an init container to copy it to the persistent volume.
