### ISSUE TITLE
[stable/graylog] Allow liveness and readiness probes to be adjusted in values.yaml

### ISSUE THREAD

**Issue by juliohm1978** [helm/charts#21902]
Current Graylg chart parameters are already quite flexible.

However, one additional group of values would be great to have included in `values.yaml`. Today, `livenessProbe` and `readinessProbe` values for the Graylog server are hardcoded in the StatefulSet template.

![image](https://user-images.githubusercontent.com/4145456/79145716-800b9d80-7d97-11ea-9838-818cbf6999f9.png)

My current installation is having a hard time keeping up with the large ammounts of logs injested from our Nginx frontend. We've already scaled Graylog vertically and horizontally, even incrased the journal and processing buffers significantly. But before adding more nodes to a cluster that already has 5 large Graylog server instances, we'd like to be able to change the default probe values.

The idea is to basically relax the livenessProbe a little bit because we've noticed this one, in particular, seems very sensitive.

We don't mind having a reasonable number of messages wait in the journal before being processed during high peak hours, but while they are being processed under high load, the default livenessProbe is "_flaky_". It will fail rapidly as nodes are taken off the Kubernetes service load balance. Graylog master itself notices and we can see nodes coming and going out of the load balance. Eventually, a full pod restart happens with 3 failues in a short 30s window.

In such scenarios, it would be interesting to allow more failures to pile up in the `livenessProbe` before a full pod restart. That would give Graylog a larger recovery window to dump messages accumulated in the journal.

I'll manage to send PR later on, but I would love some feedback to make sure this sounds like a resonable setting to have.

**Comment by ilyesAj** [comment]
@juliohm1978 We're having the same issue on our graylog cluster , Did you manage to solve the problem by increasing periodSeconds on liveness probe ?  
What we really want is to stop traffic to pods when Graylog's LB status is "throttled" (the normal behavior of k8s is restarting the stack )
