### ISSUE TITLE
[stable/datadog] missing info in 1.x -> 2.x migrations

### ISSUE THREAD

**Issue by thomas-riccardi** [helm/charts#21920]
I recently updated from 1.39.6 to 2.2.1 by following https://github.com/helm/charts/blob/master/stable/datadog/docs/Migration_1.x_to_2.x.md

What was missing:
- `datadog.processAgentEnabled -> datadog.processAgent.enabled` in fact, also need to set `datadog.processAgent.processCollection: true` otherwise the process info is not collected
-  old `logsEnabled` and `logsConfigContainerCollectAll` (and corresponding new `logs.*`): they are in fact *not* in the root values, but inside of `datadog`.

**Comment by clamoriniere** [comment]
Hi @thomas-riccardi 

Thank you for reporting this issue. We have included a fix in the pull request #22006.

Cedric

**Comment by thomas-riccardi** [comment]
@clamoriniere thank you!

The related PR (#22006) wrongly uses the github keyword `fixes` to auto close related issues: it seems we need to repeat `fixes` before each issue id: `fixes #foo, fixes #bar, fixes #baz`, etc...

@clamoriniere maybe update your PR to mark all related issues as closed (at least for future PRs ?)
