### ISSUE TITLE
[stable/postgresql] Wrong fullname template

### ISSUE THREAD

**Issue by v-mihaylov** [helm/charts#21933]
The fullname computation in many charts is broken.
The line referenced below should read:
{{- $name | trunc 63 | trimSuffix "-" -}}

https://github.com/helm/charts/blob/69fd2819607dc21cd95af7aac3524a757e03f594/stable/postgresql/templates/_helpers.tpl#L19

The issue if valid affects many other charts.

**Comment by dani8art** [comment]
Hi @v-mihaylov, thank you for your feedback, I have to say that we are in the process of standardize this kind of mistake using [1], we will fix it sooner than later. However, we are open to contribution and if you have a chance to open a PR we will be so happy to handle it. 

1. https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_names.tpl#L21

**Comment by carrodher** [comment]
In addition to that, given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), this Bitnami maintained Helm chart is now located at [bitnami/charts](https://github.com/bitnami/charts/). Please visit the [bitnami/charts](https://github.com/bitnami/charts/) GitHub repository to create Issues or PRs.

In [this issue](https://github.com/helm/charts/issues/20969) we tried to explain more carefully the reasons and motivations behind this transition, please don't hesitate to add a comment in this issue if you have any question related to the migration itself.
