### ISSUE TITLE
[stable/sentry] Convenient way to install plugins

### ISSUE THREAD

**Issue by tyranron** [helm/charts#21937]
**Is your feature request related to a problem? Please describe.**
In some workloads additional plugins are required for Sentry, like [`sentry-telegram`](https://pypi.org/project/sentry-telegram/), which may be absent in official Docker image.

**Describe the solution you'd like**
It would be nice to have a convenient way to install required plugins on container startup, like [`grafana` does](https://github.com/helm/charts/blob/f2fcadaa5a1af57bbdf2e49a99f25c9589d5b540/stable/grafana/values.yaml#L292-L296).

**Describe alternatives you've considered**
It always possible to create a custom Docker image. However, maintaing it and keeping up-to-date with upstream _just to_ contain some additional plugin may be quite overkilling.

**Comment by dragon-yuan** [comment]
+1

**Comment by sergiochoo** [comment]
+1
