### ISSUE TITLE
[stable/prometheus-operator] NodeClockSkewDetected

### ISSUE THREAD

**Issue by ymettier** [helm/charts#21941]
**Describe the bug**

Got NodeClockSkewDetected alerts

**Which chart**:

Prometheus-operator

**What happened**:

Got alerts

**What you expected to happen**:

Should not get alert

**Anything else we need to know**:

https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/rules-1.14/node-exporter.yaml#L186

```
node_timex_offset_seconds < 0.05
```

Please fix with 
```
node_timex_offset_seconds < -0.05
```

**Fix suggestion**

Important note : this is already fixed upstream : https://raw.githubusercontent.com/coreos/kube-prometheus/master/manifests/prometheus-rules.yaml

So the only thing to do is to run `sync_prometheus_rules.py` from https://github.com/helm/charts/tree/master/stable/prometheus-operator/hack

**Comment by estei** [comment]
There is already a pull request that takes care of this, that just needs to be merged.
https://github.com/helm/charts/pull/21899

I guess we just have to arm ourselves with a bit of patience.

**Comment by smoke** [comment]
The https://github.com/helm/charts/pull/21899 is merged and released, so this issue can be closed.
