### ISSUE TITLE
[stable/airflow] preinit init container is not properly calling the puckel/airflow docker

### ISSUE THREAD

**Issue by PoulpiFr** [helm/charts#21951]
**Describe the bug**
We're not running `airflow initdb` against the proper database when using `airflow.preinitdb=true`.
 
**Version of Helm and Kubernetes**:
```
helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
kubectl version     
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-14T18:02:25Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
[stable/airflow]

**What happened**:
When `airflow.preinitdb` is set to true, the `airflow-preinitdb` initContainer is running `airflow initdb` on a SQLite context instead of running it against the PostgreSQL database configured in the chart.

```
*** Waiting 10s for postgres
*** Initializing airflow db
[2020-04-15 21:25:42,740] {{settings.py:212}} DEBUG - Setting up DB connection pool (PID 7)
[2020-04-15 21:25:42,982] {{cli_action_loggers.py:42}} DEBUG - Adding <function default_action_log at 0x7f6d06d51b00> to pre execution callback
DB: sqlite:////usr/local/airflow/airflow.db
[2020-04-15 21:25:43,629] {{db.py:368}} INFO - Creating tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
```

**What you expected to happen**:
The initdb operation should be run over the configured PostgreSQL database.

**How to reproduce it** (as minimally and precisely as possible):
Set airflow.preinitdb to true with an external postgreSQL database configured in the Helm Chart vlaues.

**Anything else we need to know**:
The initContainer triggered by `airflow.preinitdb=true` configuration is improperly calling the puckel/docker-airflow Docker image with:
```
command:
            - "/bin/bash"
            - "-c"
            - "/usr/local/scripts/preinit-db.sh"
```

[As the doc says](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/):
> If you supply a command but no args for a Container, only the supplied command is used. The default EntryPoint and the default Cmd defined in the Docker image are ignored.

Hence the ENTRYPOINT of the puckel/docker-airflow docker is overridden: https://github.com/puckel/docker-airflow/blob/master/Dockerfile#L85

But this ENTRYPOINT is very useful to build Airflow specific env variables from env variables built in this Helm chart. See: https://github.com/puckel/docker-airflow/blob/master/script/entrypoint.sh

For example, the `AIRFLOW__CORE__SQL_ALCHEMY_CONN` env variable is not properly set (as it's built by the default ENTRYPOINT), and the `airflow initdb` is then run on a local SQLite database instead of the PostgreSQL database configured in this Helm Chart.

To fix the issue, the `command:`simply has to be renamed `args` as done in other place in the Chart when running `airflow initdb`

Ex. https://github.com/helm/charts/blob/master/stable/airflow/templates/deployments-scheduler.yaml#L208

**Comment by PoulpiFr** [comment]
ping @memory

**Comment by memory** [comment]
How embarrassing!  I'll try to get a pr together tomorrow.  cc @gsemet

**Comment by PoulpiFr** [comment]
@memory > I did a PR if you want =)
