### ISSUE TITLE
[stable/prometheus-operator] Specify additional labels for service discovery

### ISSUE THREAD

**Issue by LucaPrete** [helm/charts#21968]
Hello everyone,

I'm trying to integrate the servicemonitor created by the [elasticsearch-exporter](https://github.com/helm/charts/tree/master/stable/elasticsearch-exporter).

As you can see below, the service monitor gets correctly created in the monitoring namespace, where my prometheus installation lives.

```
$ kubectl get servicemonitor -n monitoring
NAME                                            AGE
elasticsearch-exporter                          6d
prometheus-prometheus-oper-alertmanager         7d22h
prometheus-prometheus-oper-apiserver            7d22h
prometheus-prometheus-oper-coredns              7d22h
prometheus-prometheus-oper-grafana              7d22h
prometheus-prometheus-oper-kube-state-metrics   7d22h
prometheus-prometheus-oper-kubelet              7d22h
prometheus-prometheus-oper-node-exporter        7d22h
prometheus-prometheus-oper-operator             7d22h
prometheus-prometheus-oper-prometheus           7d22h
```

Now, as far as I understood, servicemonitor get discovered using labels.

If I do a `kubectl describe servicemonitor elasticsearch-exporter -n monitoring` I do see some labels, reported below:

```
Labels:       app=elasticsearch-exporter
              chart=elasticsearch-exporter-3.0.0
              heritage=Helm
              release=elasticsearch-exporter
```

Now I need to inform prometheus to look ALSO for a service monitor with a label `app=elasticsearch-exporter` (together with the default ones used by default for the default exporters).

I'm struggling to read through the documentation to find a way to do this. Could you please guide me? Not really sure if I've missed anything here...

Thanks

**Comment by estei** [comment]
By default the `prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues` setting in values makes it so that prometheus will only pick up servicemonitors that are labeled with the same `release` tag as the prometheus-operator release. 

https://github.com/helm/charts/blob/402a220fe1ef7ff83a80e84005e2edf0dcf8f73c/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L98-L107

If you set it to false, I think it should pick all servicemonitors in your monitoring namespace.

**Comment by LucaPrete** [comment]
Ahhh....that was it!

If I may, I'd suggest to make this more clear in the documentation, maybe
creating a short, dedicated paragraph.
I can submit a PR if you wish...

-Luca

Il giorno ven 17 apr 2020 alle ore 09:56 Rasmus Lauridsen <
notifications@github.com> ha scritto:

**Comment by estei** [comment]
Glad you got it working. :smiley: 
I am just an interested third party, but I am sure that the project will be interested in bettering the documentation :-)

**Comment by LucaPrete** [comment]
Here is the PR ;)

https://github.com/helm/charts/pull/21982
