### ISSUE TITLE
[stable/prometheus-operator] Allow for tolerations in values to be passed to prometheus-node-exporter

### ISSUE THREAD

**Issue by hbuttguavus** [helm/charts#21977]
I would like to have tolerations in values for nodeExporter. This will allow me to deploy node-exporter pods on my k8s master nodes which have the NoExecute taint. This taint is there by default from the rke install. I am currently manually removing it and running this helm chart to get around the problem. Would be nice to instead make it part of the values that I can enter in the prometheus-operator helm chart.

**Is your feature request related to a problem? Please describe.**
I am unable to deploy node-exporter pods on my master nodes because they have the NoExecute taint. By default prometheus-node-exporter has tolerations for NoSchedule only. Unable to monitor any k8s master nodes. I am using RKE to bring up my K8s cluster which has the NoExecute taint on all etcd nodes.

**Describe the solution you'd like**
I would like to be able to add tolerations as part of nodeExporter values.

**Describe alternatives you've considered**
Currently I am manually removing the taint and using the helm chart.

**Comment by guillomep** [comment]
Hello,

I was facing the same problem and I find the way to do it.
If you look at the chart, it requires another chart for node-exporter. In the node-exporter chart you can add tolerations.
So inside your values file of prometheus-operator you can write something like:

```
prometheus-node-exporter:
  tolerations:
  - effect: [..]
```
