### ISSUE TITLE
[stable/airflow] git-clone, git-sync - race conditions

### ISSUE THREAD

**Issue by cr1st1p** [helm/charts#21972]
**Describe the bug**
If you're using the automatic git clone and/or git sync features, there are race conditions issues.

a) if using persistence enabled (with a *shared* type of PVC), then you'll end up with multiple pods simultaneously doing the same process of cleaning and updating the dags directory.
 You can have this situation:
1) pod A cleans up
2) pod A git clone
3) pod B starts, cleans up
3) pod A has the rest of the container started, will not see any Dags or partial ones
4) pod B does git clone
5) pod B starts, sees all dags

I think #20722 is talking about the same situation as well.

b) even if not using shared data, but if using git-sync, there could be a problem with the fact that git-sync can update the dags directory (initially or if set to periodically refresh) in a non atomic way.

Mind you, I am new to airflow, so I am not sure how (well) it handles the following possible flow:
1) git-sync/git-clone updated initially the dags
2) airflow reads and uses them
3) git-sync is set to refresh and starts updating them. First, it cleans things up.
4) assume maybe a slow git connection
5) airflow checks the dags directory, finds it empty, shows no dags, takes decision to not run anything
6) git-sync updates some of the files
7) airflow now sees parts of the dag files. takes decisions.
8) git-sync finishes
9) airflow sees all the dags, takes decisions.

**Version of Helm and Kubernetes**:
no helm;
 kubernetes 1.13

**Which chart**:
stable/airflow

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
Suggestions:
a) change chart so that you can mount a PVC as 'dag-data' somewhere, *but* have configuration (i.e. configmap's AIRFLOW__CORE__DAGS_FOLDER) set to a subfolder.
  This would allow people to implement their own atomic updates if they want
b)  have a single dedicated pod doing the git-clone and git-sync.
c) depending on how airflow behaves: make that dedicated pod from a) do the update in an atomic way (using directories and symlinks) and using change from a)

**Comment by thesuperzapper** [comment]
It it NOT intended for people to set `dags.persistence.enabled` to true while using git-sync. Please see the updated docs in v7.0.0
