### ISSUE TITLE
[stable/prometheus-node-exporter] metricRelabelings in ServiceMonitor

### ISSUE THREAD

**Issue by ikarlashov** [helm/charts#21984]
**Is your feature request related to a problem? Please describe.**
I would like to skip metrics ingestion for servicemonitor entity. 

**Describe the solution you'd like**
There should be possibility to use the metricRelabelings field in the ServiceMonitor to drop metrics at ingestion time.

**Comment by benibr** [comment]
As mentioned in https://github.com/helm/charts/issues/22040#issuecomment-617202110 this issues are very similar.
I can offer to try implementing this one when the relabelings PR has bee succeccfully merged.
