### ISSUE TITLE
[stable/datadog] Trace-agent missing podLabelsAsTags

### ISSUE THREAD

**Issue by pgiles** [helm/charts#21991]
**Is your feature request related to a problem? Please describe.**

While the podLabelsAsTags (resulting in an envar DD_KUBERNETES_POD_LABELS_AS_TAGS) provides a mapping of Kubernetes Labels to Datadog Tags in the *Logs* section of DataDog, it does not provide a mapping of Kubernetes Labels to Datadog Tags in the *APM* section.  Hence you can not, for example, filter your Traces by label. 

**Describe the solution you'd like**

In essence, copying the code found in 
https://github.com/helm/charts/blob/master/stable/datadog/templates/container-agent.yaml#L76-L79
```
    {{- if .Values.datadog.podLabelsAsTags }}
    - name: DD_KUBERNETES_POD_LABELS_AS_TAGS
      value: '{{ toJson .Values.datadog.podLabelsAsTags }}'
    {{- end }}
```
into the trace-agent 
https://github.com/helm/charts/blob/master/stable/datadog/templates/container-trace-agent.yaml

**Describe alternatives you've considered**

This was told to us in a phone call we had with DataDog support.  It is required for this feature to work.  The work-around, obviously, is to add the environment variable to the datadog.apm.env property.

**Additional context**

**Comment by clamoriniere** [comment]
Hi @pgiles 

Thank you for reporting this issue. We have included a fix in the pull request #22006.

Cedric
