### ISSUE TITLE
[stable/prometheus] - --set wrong behaviour 

### ISSUE THREAD

**Issue by nnsense** [helm/charts#21994]
Hi

Reading repo's readme the option `serverFiles.alerting_rules.yml` should set **Prometheus server alerts configuration**
I'm expecting the same behaviour as if I was adding a new file into values's `serverFiles`.

So when I'm running this
```
helm install prometheus stable/prometheus --namespace monitoring --set serverFiles.alerting_rules.yml='testing'
```

Running `kubectl describe cm prometheus-server -n monitoring` I'm expecting this
```
alerting_rules.yml:
----
testing
```

Instead, I have this
```
alerting_rules.yml:
----
{}

alerting_rules:
----
yml: testing
```

Basically the file is created into `/etc/config` as expected, but it has no extension. The extension (yml) ends up into the file. I've tried to escape the dot, to remove it, I can't figure out how to add my alerts by using `--set` (actually, `--set-file`) correctly.

helm version
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

kubectl
```
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-21T23:37:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

Thanks

**Comment by nnsense** [comment]
Any htoughts?

**Comment by nnsense** [comment]
Not even a comment on this? The `--set-file` option is quite important and commonly used I suppose, odd no one else noticed it. Maybe I'm just doing something wrong?

**Comment by karthikeayan** [comment]
Can you try 

```
serverFiles:
  alerts:
  ----
  testing
```
instead of

```
serverFiles:
  alerting_rules.yml:
  ----
  testing
```
?

**Comment by nnsense** [comment]
Hi @karthikeayan 
Thanks for helping me

The command I'm running is 
```
helm install prometheus stable/prometheus --namespace monitoring --set serverFiles.alerting_rules.yml='testing'
```

So I think you mean to try
```
helm install prometheus stable/prometheus --namespace monitoring --set serverFiles.alerting_rules.yml='testing'
```

which I did, it results in:
```
alerting_rules.yml:
----
{}

alerting_rules:
----
testing
```

Basically helm is taking the extension `.yml` as a further key nested under the file name, instead of the file extension.

Bear in mind that the above output is from
```
kubectl describe cm prometheus-server -n monitoring
```

**Comment by karthikeayan** [comment]
No, can you try this?

```
helm install prometheus stable/prometheus --namespace monitoring --set serverFiles.alerts='testing'
```

**Comment by nnsense** [comment]
Apparently that's deprecated, it results in 
```
coalesce.go:196: warning: cannot overwrite table with non table for alerts (map[])
coalesce.go:196: warning: cannot overwrite table with non table for alerts (map[])
Error: template: prometheus/templates/server-configmap.yaml:26:45: executing "prometheus/templates/server-configmap.yaml" at <$value.groups>: can't evaluate field groups in type interface {}
```

**Comment by karthikeayan** [comment]
From this what I am guessing is that, serverFiles.alerts needs to have a groups inside it. May be just setting it to "testing" makes it a invalid rule.

https://github.com/helm/charts/blob/master/stable/prometheus/values.yaml#L1142

**Comment by nnsense** [comment]
I've just cleaned up the output leaving just "testing", to focus on the real issue but yes, can be misleading. On my deployment there's a group and many entries not just "testing", apparently whatever I write it always end up with a single file, without any extension, while the right one (defined into prometheus config yaml file) is left empty.

**Comment by willemm** [comment]
This is more of a helm issue.  Have you tried putting quotes around the filename in the --set ?

Like this:
```
helm install prometheus stable/prometheus --namespace monitoring --set serverFiles.'alerting_rules\.yml'='testing'
```

Also see: https://stackoverflow.com/questions/49522776/helm-how-to-override-value-with-periods-in-name

**Comment by Andre448** [comment]
You can add a "\" to make it work

`--set-file serverFiles.alerting_rules\.yml=alerting_rules.yml`

The downside of this solution is that the file content is passed as string and not as map. Therefore your result will look like this:

> alerting_rules.yml: |
    "   groups:\r\n     - name: Instances\r\n       rules:\r\n         - alert: InstanceDown\r\n
      \          expr: up == 0\r\n           for: 5m\r\n           labels:\r\n             severity:
      page\r\n           annotations:\r\n             description: '{{ $labels.instance
      }} of job {{ $labels.job }} has been down for more than 5 minutes.'\r\n             summary:
      'Instance {{ $labels.instance }} down'"


I could not find a way to fix it yet.

**Comment by altinoren** [comment]
I'm having the same issue. Can't find a way to supply alert rules.
