### ISSUE TITLE
[stable/ethereum] Not updated

### ISSUE THREAD

**Issue by edisinovcic** [helm/charts#22009]
**Chart is not maintained anymore**
If needed I can help with updating chart if none of the original contributors are able to do so. 

I'm working on some projects for EF as can be seen on my Github and could help with this being maintained.

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi @edisinovcic I am not from the Helm Team. 

I will help you with full force working on  Ethereum : 
* I have tried may times to bring up an Ethereum Blockchain. It always ended up with an endless sequence of bugs, and me wondering : Has _anyone_ ever installed an Ethereum Blockchain on premises ? 
* I also have dared all the engineers I cross roads with, to show me any recipe, on any repo in the world, which successfully provisions a fully private Ethereum Blockchain.
* I also dare you, and any engineer reading this, and propose you my full help to defeat me, 
* I have opened an issue on the current top bug on ethereum helm chart https://github.com/helm/charts/issues/22233
