### ISSUE TITLE
[stable/jenkins] configuration-as-code plugin not installed

### ISSUE THREAD

**Issue by fl-max** [helm/charts#22025]
**Describe the bug**
If any of these plugins are added to  `master.installPlugins`
- configuration-as-code-support
- configuration-as-code-groovy
- configuration-as-code-secret-ssm
it will cause the `configuration-as-code` plugin to be skipped. 

The issue is with [this line here](https://github.com/helm/charts/blob/master/stable/jenkins/templates/config.yaml#L254). The `contains` function returns true for any of the above plugins, resulting in the `configuration-as-code` plugin to not be added to the `plugins.txt` file.

**Version of Helm and Kubernetes**:
Helm: `v3.0.3`
Kubernetes: `v1.16.7`

**Which chart**:
stable/jenkins `v1.15.0`

**What happened**:

`configuration-as-code` plugin not installed.

**What you expected to happen**:

`configuration-as-code` plugin to be installed.

**How to reproduce it** (as minimally and precisely as possible):

Run helm install with the following:
```yaml
master:
  JCasC:
    enabled: true
  installPlugins:
  - configuration-as-code-support:1.18
```

Go to *Manage Jenkins* and observe that the Configuration as Code plugin is not installed.

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
Thank you that's a great bug report. Would you like to create a PR which solves this?

**Comment by fl-max** [comment]
@torstenwalter Yes, when I can find some spare time. 

Wanted to at least open the issue so I don't lose track of it or if someone else wants to contribute.
