### ISSUE TITLE
[stable/prometheus-operator] CoreDNS dashboard hardcoded datasource 

### ISSUE THREAD

**Issue by vanneback** [helm/charts#22024]
**Describe the bug**
The CoreDNS default dashboard only works if the datasource is named prometheus. Otherwise:
![coreDns-dash](https://user-images.githubusercontent.com/15668291/79767101-296b0a00-8329-11ea-8b85-3edfae19750d.png)

This is also clear in https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-coredns.yaml#L44 that the datasource value is hardcoded to `Prometheus`

**Which chart**:
Prometheus-operator version 8.12.13

**Comment by den-is** [comment]
this is the latest prometheus-operator chart 8.13.0
<img width="1357" alt="Screen Shot 2020-04-21 at 10 12 16" src="https://user-images.githubusercontent.com/5287237/79832060-ab0a7880-83b9-11ea-88b4-56f5e199ccb3.png">

**Comment by vanneback** [comment]
I am having the same problem with the newest version aswell. It is just if your datasource is not named `prometheus`. But this should not be hardcoded.  https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-coredns.yaml#L44. The other dashboards have dynamic datasource

**Comment by den-is** [comment]
@vanneback would you like to make PR?

**Comment by vanneback** [comment]
Okej, I will when i get the time for it. Might be next week,
