### ISSUE TITLE
[stable/nginx-ingress] Allow more items to be configured in the Container securityContext

### ISSUE THREAD

**Issue by ajchiarello** [helm/charts#22038]
In the helm templates for the controller and default-backend deployments, you can set an arbitrary set of parameters for podSecurityContext, but not for the contaner securityContext. The controller deployment allows more options, but the default-backend only adds runAsUser to this context. I would like to be able to set more options, particularly on the default-backend (such as privileged: false), which are not supported in the podSecurityContext. 

**Is your feature request related to a problem? Please describe.**
I am tasked with setting all our helm charts to have the correct securityContext at install, and would like to be able to do so.

**Describe the solution you'd like**
The helm template for the securityContext to support an arbitrary block, like podSecurityContext does.

**Describe alternatives you've considered**
Patching all the installations after installation is something I have set up, but it is not ideal.

**Comment by akohlislb** [comment]
The same request for Airflow as well. values.yaml file is not supporting passed securityContext values - privileged:true to Deployments and Pods. After deployment, I have to manually edit the Deployment. Should come up with deployment options.
