### ISSUE TITLE
[incubator/druid] coordinator uses mysql which is already exists.

### ISSUE THREAD

**Issue by jinleileiking** [helm/charts#22037]
By default, the helm will setup a mysql in k8s. 

This can set the mysql info in the values.yaml. It can use the mysql server which is created on AWS   / Kingsoft Cloud/Google cloud.

**Comment by AWaterColorPen** [comment]
@jinleileiking 
you can try [incubator/druid] chart version 0.2.0+

**Comment by jinleileiking** [comment]
I am now using druid-operator, druid helm charts is not good. CONSIDER DO NOT USE IT use operator
