### ISSUE TITLE
[stable/prometheus-pushgateway] allow configuration of RelabelConfig in ServiceMonitor Endpoint

### ISSUE THREAD

**Issue by benibr** [helm/charts#22040]
Setup: We're using a prometheus-pushgateway ServiceMonitor which is automatically scraped by prometheus-operator which works fine, but is not fully configurable.

**Is your feature request related to a problem? Please describe.**
The problem is that a `pod` label is added which contains the name of the prometheus-pushgateway pod and therefore multiples the number of metrics by the number of prometheus-pushgateway pods.
Example:
```
{endpoint="http",job="backup-job",namespace="monitoring",pod="prom-prometheus-pushgateway-0123456789-fffff",service="prom-prometheus-pushgateway"}
{endpoint="http",job="backup-job",namespace="monitoring",pod="prom-prometheus-pushgateway-0987654321-abcdef",service="prom-prometheus-pushgateway"}
```

**Describe the solution you'd like**
In https://github.com/helm/charts/blob/master/stable/prometheus-pushgateway/templates/servicemonitor.yaml#L17 the serviceMonitor created by the prometheus-pushgateway helmchart is described an contians an prometheus endPoint.
According to https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint its is possible to add a RelabelConfig here (https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#relabelconfig) which can be used to drop certain labels.
It would be great to be able to configure the relabelConfig via the prometheus-pushgateway serviceMonitor.

**Describe alternatives you've considered**
When using additionalScrapeConfigs in  prometheus-operator dropping labels an metrics is possible but that would mean to quit the use of the serviceMonitor and hardcode the endpoints in the config.

**Additional context**
I try to submit a PR this week

**Comment by benibr** [comment]
I guess this is a very similar issue: #21984

**Comment by ikarlashov** [comment]
Bump

**Comment by benibr** [comment]
I'd love to resolve this issue with #22066 but I need someone to merge it.
