### ISSUE TITLE
[incubator/kafka] Add MirrorMaker Support

### ISSUE THREAD

**Issue by iAnomaly** [helm/charts#22050]
**Is your feature request related to a problem? Please describe.**
Support for Kafka MirrorMaker.

**Describe the solution you'd like**
I'm on the fence if this makes the most sense to be added to the existing incubator/kafka chart as a flagged feature or deserves its own chart such as incubator/zookeeper has done.

**Describe alternatives you've considered**
A formal submission of a separate mirrormaker chart.

**Additional context**
I am happy to submit this chart or templates to incubator/kafka via PR once guidance for the desired location is provided.

**Comment by iAnomaly** [comment]
@benjigoldberg Can you help assign the appropriate individual to provide guidance here?

**Comment by benjigoldberg** [comment]
Hi @iAnomaly I would think this makes sense as a standalone chart. We've taken a similar approach with Schema Registry, for example.

**Comment by iAnomaly** [comment]
Scratch that. The Strimzi Kafka Operator has already built a [CRD for MirrorMaker 2](https://github.com/strimzi/strimzi-kafka-operator/blob/master/helm-charts/strimzi-kafka-operator/templates/048-Crd-kafkamirrormaker2.yaml) and I don't think it makes sense to duplicate that work here.
