### ISSUE TITLE
[stable/jenkins] jenkinsUriPrefix: "/jenkins" by CasC

### ISSUE THREAD

**Issue by ruaridhangus-fbr** [helm/charts#22060]
**Describe the bug**
The Config as Code plugin seems to not be respecting the jenkinsUriPrefix and as such is getting a 404 not found.

**Version of Helm and Kubernetes**:
Helm
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
Kubernets
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
Stable Jenkins

**What happened**:
Logs for jenkins-sc-config container show:

```
2020-04-22 12:02:03,051 WARNING Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f28fe4f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /reload-configuration-as-code/?casc-reload-token=jenkins-57b8d86c9-687xg
```

```
POST request sent to http://localhost:8080/reload-configuration-as-code/?casc-reload-token=jenkins-57b8d86c9-687xg. Response: 404 Not Found
```

**What you expected to happen**:
Successful call to either the Jenkins URL or Localhost with the correct prefix.

Seems to be similar to the issue reported here: #20305 which has since been closed to inactivity

**Comment by wilinger** [comment]
Have this issue too

**Comment by SomaSharathSurya** [comment]
Hey Team , I’m facing the same issue , can I know if there’s a solution for  it ? 

@wilinger Any luck on this ?

**Comment by wilinger** [comment]
@SomaSharathSurya I believe I reverted back to an older helm chart version until the problem didn't occur

**Comment by SomaSharathSurya** [comment]
@wilinger Thanks for your reply.

My bad I’ve actually made a typo and updated JenkinsUriPrefix => jenkinsUriPrefix, it’s all good now after this change.
