### ISSUE TITLE
Rabbitmq Unable to add podAnnotations

### ISSUE THREAD

**Issue by kferrone** [helm/charts#22087]
**Describe the bug**
I am unable to add any podAnnotations to the RabbitMQ chart. 

**Version of Helm and Kubernetes**:
helm: 3.2.0
k8s: 1.15 eks

**Which chart**:
rabbitmq

**What happened**:

Here is the error I get when I add any kind of annotations to the pods:

> Error: YAML parse error on rabbitmq/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 29: mapping values are not allowed in this context
helm.go:84: [debug] error converting YAML to JSON: yaml: line 29: mapping values are not allowed in this context

**What you expected to happen**:

Add the pod annotations with no fuss

**How to reproduce it** (as minimally and precisely as possible):

A simple example of what I tried in myValues.yaml:
```yaml
podAnnotations:
  foo: bar
```
This was the only value I used. I deleted all the rest of them until I discovered this was the failing value. 

**Anything else we need to know**:

Annotations in other parts of the chart did work. e.g. the ingress annotations

**Comment by carrodher** [comment]
Hi,

Given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), this Bitnami maintained Helm chart is now located at [bitnami/charts](https://github.com/bitnami/charts/). Please visit the [bitnami/charts](https://github.com/bitnami/charts/) GitHub repository to create Issues or PRs.

In [this issue](https://github.com/helm/charts/issues/20969) we tried to explain more carefully the reasons and motivations behind this transition, please don't hesitate to add a comment in this issue if you have any question related to the migration itself.

**Comment by kferrone** [comment]
Oh I feel kinda silly right now. I am actually using the Bitnami chart and this issue should have been posted with Bitnami.
