### ISSUE TITLE
[stable/locust] tests does not stop, status never goes to Stopped.

### ISSUE THREAD

**Issue by vidhyapg** [helm/charts#22080]
**Describe the bug**
Tried to Stop a running test from web UI accessed from master service. The test never stops. 

**Version of Helm and Kubernetes**:
Helm v2.14.3
Kubernetes: v1.15.3
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
**Which chart**:
stable/locust

**What happened**:
The test once started can never be stopped. Not from the WebUI or by curl $LOCUST_URL/stop

**What you expected to happen**:
That the test stops upon pressing stop button. 

**How to reproduce it** (as minimally and precisely as possible):
Start a test
See the charts updating
Stop the test
You can see the status never goes to Stopped. Instead stays at Hatching. 
The chart also shows the test is still running. 

**Anything else we need to know**:
This does not happen with locally running locust. Only in the kubernetes with this helm chart this issue happens.

**Comment by Fitz7** [comment]
I have this issue also, seems it is fixed in later versions however the chart does not work on the latest version.

If I make progress and get it working I'll update and possibly make a PR
