### ISSUE TITLE
[stable/nfs-client-provisioner: run as nobody] NFS mounts are mounting as NOBODY

### ISSUE THREAD

**Issue by icsy7867** [helm/charts#22085]
**Describe the bug**
The mounts are being listed as 4294967294:4294967294.

**Version of Helm and Kubernetes**:
latest

**Which chart**:
stable/nfs-client-provisioner

**What happened**:
Mounting correctly

**What you expected to happen**:
mounting as the root user after running runasuser: 0 and runasgroup:0

Perhaps this is an issue with my NFS server, however my other VMs and servers are able to mount as root:root without issue. 

I also changed the owner of the folder being mounted to 1000:1000 and tried runAsUser: 1000 and runAsGroup: 1000

Howver, when i did this the POD failed to start altogether.

**Comment by icsy7867** [comment]
This is resolved.

I added flags on the server to adopt the nfs3 permission model, and allowed for non-root users to mount.  That seemed to solve it.

**Comment by stubclan** [comment]
@icsy7867 I am having same issue and was wondering what exactly you added that solved the issue. 

quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11 is the image I am using
