### ISSUE TITLE
stable/prometheus-adapter missing dnsPolicy option

### ISSUE THREAD

**Issue by ghost** [helm/charts#22094]
**Is your feature request related to a problem? Please describe.**
Control plane is unable to request URL

**Describe the solution you'd like**
Add an option to values to enable dnsPolicy

**Describe alternatives you've considered**
I have a work-around: pull out the current deployment yaml with kubectl, add the dnsPolicywith a sed replace and apply the update manifest:
kubectl -n kube-system get deployment prometheus-adapter -o yaml > /tmp/prometheus-adapter.yaml
sed -i "s|dnsPolicy: .*$|dnsPolicy: ClusterFirstWithHostNet|g" /tmp/prometheus-adapter.yaml
kubectl -n kube-system apply -f /tmp/prometheus-adapter.yaml

**Additional context**
dnsPolicy : ClusterFirstWithHostNet is required to work in an EKS cluster

**Comment by omesser** [comment]
This should be reopened IMO
