### ISSUE TITLE
[stable/jenkins]  ERROR: Cannot run program "docker"

### ISSUE THREAD

**Issue by cloud-arrow** [helm/charts#22125]
**Describe the bug**
ERROR: Cannot run program "docker"
**Version of Helm and Kubernetes**:
Helm v3.1.2
Kubernetes v1.18.0

**Which chart**:
[stable/jenkins]

**What happened**:
Already installed CloudBees Docker Build and Publish plugin  ，build, I get the following error

```
[jenkins-k8s-demo] $ docker build -t registry-vpc.cn-shanghai.aliyuncs.com/fzzxwl/k8s-demo:master --pull=true /home/jenkins/workspace/jenkins-k8s-demo
ERROR: Cannot run program "docker" (in directory "/home/jenkins/workspace/jenkins-k8s-demo"): error=2, No such file or directory
java.io.IOException: Cannot run program "docker" (in directory "/home/jenkins/workspace/jenkins-k8s-demo"): error=2, No such file or directory
```

**Anything else we need to know**:
<img width="933" alt="截屏2020-04-25上午4 42 48" src="https://user-images.githubusercontent.com/52516729/80278948-3aac7180-86af-11ea-8fb7-4ea6aabd4fd5.png">
I have mounted docker to agent why???

**Comment by alizarion** [comment]
I encountered the same issue that I solved by deleting the config.xml in Jenkins volume, I think it is not dynamically updated by the chart
