### ISSUE TITLE
[stable/jenkins] Kubernetes Plugin Does Not Use jenkinsUriPrefix value

### ISSUE THREAD

**Issue by lilleswing** [helm/charts#22133]
**Describe the bug**
With jenkinsPrefixUri set the stable/jenkins chart is unable to start/connect to new pods to execute jenkins jobs.  Pods are successfully started in Kubernetes but then quickly destroyed by jenkins-master as the agents cannot connect to jenkins-master via http.

`SEVERE: http://master-jenkins2.default.svc.cluster.local:8080/tcpSlaveAgentListener/ is invalid: 404 Not Found`

**Version of Helm and Kubernetes**:
Helm Version
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

Kubernetes is microk8s on Ubuntu 18.04 (Don't know how to get a more precise version).

**Which chart**:
stable/jenkins

**What happened**:
Agent pods come up and are killed fairly quickly.
```
SEVERE: http://master-jenkins2.default.svc.cluster.local:8080/tcpSlaveAgentListener/ is invalid: 404 Not Found
java.io.IOException: http://master-jenkins.default.svc.cluster.local:8080/tcpSlaveAgentListener/ is invalid: 404 Not Found
	at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:201)
	at hudson.remoting.Engine.innerRun(Engine.java:523)
	at hudson.remoting.Engine.run(Engine.java:474)

Error in provisioning; agent=KubernetesSlave name: default-z7tc7, template=PodTemplate{inheritFrom='', name='default', namespace='', hostNetwork=false, label='master-jenkins2-jenkins-slave', serviceAccount='default', nodeSelector='', nodeUsageMode=NORMAL, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], containers=[ContainerTemplate{name='jnlp', image='jenkins/jnlp-slave:3.27-1', workingDir='/home/jenkins', command='', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='512m', resourceRequestMemory='512Mi', resourceLimitCpu='512m', resourceLimitMemory='512Mi', envVars=[ContainerEnvVar [getValue()=http://master-jenkins2.default.svc.cluster.local:8080, getKey()=JENKINS_URL]], livenessProbe=org.csanchez.jenkins.plugins.kubernetes.ContainerLivenessProbe@1358ba72}]}
java.lang.IllegalStateException: Agent is not connected after 4 seconds, status: Failed
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:208)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:292)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**What you expected to happen**:
Agent pods start and execute jenkins jobs.

**How to reproduce it** (as minimally and precisely as possible):
1. Install Most Recent Helm Chart With jenkinsUriPrefix to `/jenkins` and ingress enabled and pointing to `/jenkins`
```
# values.yml
master:
  jenkinsUriPrefix: "/jenkins"
  ingress:
    kubernetes.io/ingress.class: nginx
    path: "/jenkins"
```
`helm install -f jenkins-values.yaml master-jenkins stable/jenkins`
Create a new Freestyle Jenkins Job which runs the shell
`echo "Hello World`

View The Jenkins System Log -- Repeated Error In Provisionings appear.

**Anything else we need to know**:

I suspect the correct URL to hit for tcpSlaveAgentListener has to respect the jenkinsPrefixUri and be at 
`http://master-jenkins.default.svc.cluster.local:8080/jenkins/tcpSlaveAgentListener/ `

**Comment by juliensap1** [comment]
Hello @lilleswing,
i have the same issue and i'm struggling to fix it. You know how to fix it?
The set is composed with Jenkins running beyond a nginx ingress with a valid ssl certificate and i've set JENKINS_OPTS to add a prefix. If i remove the prefix jenkins works fine, if i add te prefix i got the same error:
SEVERE: http://xxxxxx.svc.cluster.local:8080/tcpSlaveAgentListener/ is invalid: 404 Not Found
Best Regards
