### ISSUE TITLE
[stable/prometheus-operator] admission-create pod keeps crashing

### ISSUE THREAD

**Issue by tommazzo89** [helm/charts#22153]
Hi everyone,

**Describe the bug**
When I try to install the current version of the prometheus operator on a Kubernetes cluster for the first time, helm times out, because the `prometheus-operator-xyz-admission-create-xy` pod keeps crashing an restarting.

When I run `kubectl logs` on that pod I get the following:
```
{"err":"Get https://10.96.0.1:443/api/v1/namespaces/default/secrets/prometheus-operator-158800-admission: dial tcp 10.96.0.1:443: i/o timeout","level":"fatal","msg":"error getting secret","source":"k8s/k8s.go:104","time":"2020-04-27T17:09:36Z"}
```

I ran `kubectl get secrets` and I can see a secret called `prometheus-operator-158800-admission-token-9mj7k`. So, basically the `-token-9mj7k` suffix seems to be missing from the GET request in the error log. How can I fix this?

**Version of Helm and Kubernetes**:
Helm: 3.2.0
Kubernetes: 1.18.0

**Which chart**:
stable/prometheus-operator v8.13.2 

**What happened**:
`helm install` went into a timeout.

**What you expected to happen**:
prometheus-operator should have been installed correctly.

**How to reproduce it** (as minimally and precisely as possible):
On a Kubernetes cluster without an existing installation of prometheus-operator, run
```
helm install stable/prometheus-operator --generate-name --debug
```

Best regards,
Thomas

**Comment by tommazzo89** [comment]
Today I tried installing the stable/prometheus-operator chart v8.13.4, but it still fails on our test cluster for the same reason.

I also tried installing it locally on my laptop in a new Minikube 1.9.2 VM with Kubernetes 1.18.0. There it worked without problems. After the installation succeeded, I listed the secrets and found one with the name `prometheus-operator-158818-admission`, but none with a `-token-xyz` suffix, which I guess is the reason why the installation has worked in this case.

What could be the reason why there is no suffix for this admission secret on my Minikube, but one on the test cluster, which apparently causes the problems?

**Comment by tommazzo89** [comment]
We have found the issue and fixed it. It was actually not related to the prometheus-operator, but to a misconfiguration of iptables, which was hindering the communication between the nodes.

**Comment by bhandari8sujit** [comment]
> We have found the issue and fixed it. It was actually not related to the prometheus-operator, but to a misconfiguration of iptables, which was hindering the communication between the nodes.

Hey, could you please elaborate on this?

**Comment by tommazzo89** [comment]
Hi,
The problem was just a misconfiguration of our cluster setup. It was not related to the helm chart at all.

**Comment by ajay1206** [comment]
Hi,
still get the issue while helm install promprom prometheus-community/kube-prometheus-stack

using Helm 3.1.1 and AKS 1.18.8

**Comment by ajay1206** [comment]
@tommazzo89 
Can you elaborate on what cluster configuration was different please?

**Comment by tommazzo89** [comment]
Hi @yaja0612,

Sorry for my late reply. I hope that you were able to fix the problem in the meantime.

Our issue was that, after setting up our Kubernetes cluster, one of the iptables forward side chains looked like this on all our nodes:
```
Chain KUBE-FORWARD (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
```

Since this is just an internal testbed, we used a rather quick fix:
```
iptables -I KUBE-FORWARD -j ACCEPT
```

But this is of course nothing that you would want to do on a production system or even a test system that is publicly available.
