### ISSUE TITLE
[stable/prometheus-snmp-exporter] Enable use of externally-provided configuration ConfigMap

### ISSUE THREAD

**Issue by alexbarcelo** [helm/charts#22180]
It's very cumbersome to configure the snmp-exporter with a proper `snmp.yml` configuration, given that puting it inline in the values of the Helm is inappropriate as it is (typically) a generated file.

A simple way to improve this would be to allow the use of an external ConfigMap resource, which can be provided out-of-band, allowing the administrators to update their generate.yml, generate a new snmp.yml, fix all the potential MIB file problems, and then update the ConfigMap resource in the kubernetes cluster.

To allow this the chart could have some additional field, e.g. externalConfig which pointed to a ConfigMap resource, and the configMapReload could track that ConfigMap (just as it seems to be doing now).

I hope it is an easy and versatile feature which will improve the usefulness of the chart, because right now it is not an easy to maintain deployment --or maybe I don't know how to properly use it, but there are no examples or documentation on that topic.

**Comment by kbreit** [comment]
I’d like to see this as well.
