### ISSUE TITLE
Stable/Jenkins fails to deploy on bootstrapped cluster - security error

### ISSUE THREAD

**Issue by sputnick** [helm/charts#222]
Jenkins fails to deploy on bootstrapped cluster.

The yaml:
https://github.com/kubernetes/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml
has this parameter set.
```
 securityContext:
        runAsUser: 0`
```

This causes the Pod to fail on creation at least on Kube-Solo 1.0.

The error message is:
```Error creating: pods "" is forbidden: pod.Spec.SecurityContext.RunAsUser is forbidden```

**Comment by kingdonb** [comment]
https://github.com/TheNewNormal/kube-cluster-osx/pull/108 fixed it for me

**Comment by kingdonb** [comment]
If you're not using kube-cluster, maybe you can submit this PR to your kube upstream

**Comment by lachie83** [comment]
@sputnick - Have you been able to update the admission control settings to fix this?

**Comment by ghost** [comment]
I ran into the same error message using an own chart and adjusting admission-control on the api-server solved the problem.
