### ISSUE TITLE
[stable/kube-state-metrics] Release patch for older version

### ISSUE THREAD

**Issue by burimkameri** [helm/charts#22200]
I would like to provide a PR for kube-state-metrics for an older version (kube-state-metrics helm chart release 2.4.1, commit 09daf199a) but since there are no particular branches for the versions of each helm charts I am not sure how to provide such PR. Is that in general possible or do I have to provide that only for the latest version?

Thanks in advance for your help.

**Comment by mrueg** [comment]
I don't think this is easily possible, you can fork it and point helm to your repository though.
