### ISSUE TITLE
[stable/nextcloud] Error 500 accessing images

### ISSUE THREAD

**Issue by jowi24** [helm/charts#22207]
**Describe the bug**
Setting up nextcloud with nginx ingress proxy. Using default value for `ingress.annotations.nginx.ingress.kubernetes.io/server-snippet`. Getting server error `500` trying to access images stored in the nextcloud. All other functions work smoothly.

**Version of Helm and Kubernetes**:
Helm 2.16.3 / Kubernetes 1.18.2

**Which chart**:
stable/nextcloud

**What happened**:
Server error 500. Error message in proxy:
```
rewrite or internal redirection cycle while internally redirecting to "/index.php/remote.php/dav/files/jo/Photos/Coast.jpg",
```

**What you expected to happen**:
Server responds with 200 and the image

**How to reproduce it** (as minimally and precisely as possible):
Set up nextcloud 18.0.4 fpm/alpine flavour. Enable ingress with default server-snippet.

**Anything else we need to know**:
Removing the following part from the server-snippet resolves the issue:
```
      location ~ \.(?:png|html|ttf|ico|jpg|jpeg)$ {
      try_files $uri /index.php$request_uri;
      # Optional: Don't log access to other assets
      access_log off;
      }
```

**Comment by bklang** [comment]
@jowi24 see #22197

**Comment by jowi24** [comment]
@bklang great, thank you!
