### ISSUE TITLE
[stable/prometheus] Alertmanagert advertise-address is broken for statefulset

### ISSUE THREAD

**Issue by sshishov** [helm/charts#22229]
**Describe the bug**
Alertmanages is broken after this PR: https://github.com/helm/charts/pull/21617
The following error is observed in logs:
```
level=warn caller=cluster.go:154 component=cluster err="couldn't deduce an advertise address: no private IP found, explicit advertise addr not provided"
level=error caller=main.go:256 msg="unable to initialize gossip mesh" err="create memberlist: Failed to get final advertise address: No private IP address found, and explicit IP not provided"
```
Also, services `alert-manager` and `alert-manager-headless` do not have any Endpoints set

**Version of Helm and Kubernetes**:
Does not matter

**Which chart**:
stable/prometheus

**What happened**:
Alertmanager is failing after upgrade

**What you expected to happen**:
Alertmanager is started

**How to reproduce it** (as minimally and precisely as possible):
Use Alertmanager as statefulset with minimum configuration
```
alertmanager:
  statefulSet:
    enabled: true
```

**Anything else we need to know**:

**Comment by ali-sattari** [comment]
Are you aiming to run Alertmanager with just one replica in non HA mode?

I see two issues:
* The default value for `enableMeshPeer` is commented in values file so if you need to run in HA mode (more than one replica) it should be explicitly set to true
* For non HA mode [AM expects](https://github.com/prometheus/alertmanager/blob/master/README.md#high-availability) `--cluster.listen-address` value to be empty string, this should be reflected in the chart. Although there is a workaround to set `enableMeshPeer` to `false` and use `extraArgs` to set `--cluster.listen-address=""` to disable HA

**Comment by sshishov** [comment]
Hello @ali-sattari . You are correct, I wanted to run without HA and before it was working without any overrides. Now I had to specify my config like this:
```
alertmanager:
    extraArgs:
    # We are not using HA mode for alert-manager: https://github.com/prometheus/alertmanager#high-availability
    cluster.listen-address: ""
```

In my opinion it should be by default to overcome this strange security policy

**Comment by ali-sattari** [comment]
@sshishov yes setting it to empty if `enableMeshPeer: false` would be the correct approach in the chart, care to PR it?
