### ISSUE TITLE
[stable/rabbitmq-ha] The readiness and aliveness check fails when there is memory or disk pressure

### ISSUE THREAD

**Issue by HansK-p** [helm/charts#22237]
**Describe the bug**
Ref https://www.rabbitmq.com/alarms.html, RabbitMQ will block publishers, but allow consumers to continue consuming messages when there is memory or disk pressure. This is a sound design as it makes it possible to recover from disk pressure and is probably also a good design to follow when there is memory pressure (usually RabbitMQ consuming more than 40% of available memory).

The Helm chart produces an aliveness and readiness probe which fails when there is memory or disk pressure. As a result both publishers and consumers are denied access and the RabbitMQ pod is restarted. In case of disk pressure I assume this might result in an endless loop. In case of memory pressure I assume a restart will usually not be a problem.

Is it an option to replace the current liveness and readiness checks with scripts (configmaps) with logic so that the RabbitMQ queue isn't restarted when there is memory or disk pressure? I assume it can be a deployment parameter which decides what should happen during disk or memory pressure. Possibly by setting an environment variable in the pod which the liveness and readiness check can use when doing health checks.

**Version of Helm and Kubernetes**:
Helm v2.16.1
K8s v1.15.10 (AKS)

**Which chart**: rabbitmq-ha-1.44.3

**What happened**: RabbitMQ pods restarted due to memory pressure when it would have been better if RabbitMQ logic would have been better to solve the solution (block publishers, let consumers consume).

**What you expected to happen**: RabbitMQ is assumed to be Ready and Alive even when there is disk or memory pressure.

**How to reproduce it** (as minimally and precisely as possible): Generate disk and/or memory pressure by pushing sufficient messages.

**Anything else we need to know**:
When writing the bug report I understood that this might be as much a feature request as a bug report.

In a HA cluster it might be beneficial if clients don't connect to a nodes with memory or disk pressure as long as there are nodes available which are operative. At least if there are mechanisms that will solve the disk pressure issue. My problem has been with a single node install using the rabbitmq-ha chart. I prefer this chart for both single-node and multi-node installs and it's only been used for test/dev/qa scenarios so far.

**Comment by steven-sheehy** [comment]
Yes, what you say is correct and I've experienced it in the past. The liveness and readiness probes are [customizable](https://github.com/helm/charts/blob/39777352ebc9085cd0d4ed928d4b173f26244c7f/stable/rabbitmq-ha/values.yaml#L491) so you're welcome to change it to a different command that suites your needs. But the real solution is to request RabbitMQ to provide an alternative health check for liveness probe that does not take into account alarms. For readiness probe, I think the current approach is suitable.

**Comment by HansK-p** [comment]
I've considered replacing those health check using a bash script mounted as a configmap. I'll probably do something like that if we start running RabbitMQ in K8s "for real".

And I've got a feeling that it might be difficult to create a "perfect" health check that handles all situations in a good way.  Like consumers/producers should only be allowed to connect to perfectly healthy cluster members - unless all cluster members have a disk/memory pressure. In such cases at least consumers (which also would mean publishers I assume) should also be allowed to connect to cluster members with memory/disk pressure. One option might be to check the api - as is done today. But dig into "rabbitmqctl cluster_health" output - when it's detected that the cluster member has a memory/disk pressure issue.

Or maybe even write a small helper utility used when doing health checks (golang based?)

**Comment by AndrewBedscastle** [comment]
Hello @HansK-p 

we recently experienced the same problem. What solution did you come up with?
We use a HA-Queue Setup, so liveness and readiness check failed for us while the system is under memory pressure (as all systems pods have the same amount of memory)

Our cluster was completely down that way. A worst case scenario!

We consider changing the current solution from the values.yaml file

`'timeout 5 wget -O - -q --header "Authorization: Basic `echo -n \"$RABBIT_MANAGEMENT_USER:$RABBIT_MANAGEMENT_PASSWORD\" | base64`" http://127.0.0.1:15672/api/healthchecks/node | grep -qF "{\"status\":\"ok\"}"'`

to just check for HTTP 200

What do you think about that?

**Comment by HansK-p** [comment]
Hello

I haven't really looked further into the problem. We have simply concluded that for now we'll continue running critical workload on VMs.

I would probably have created a bash script, made it available in the RabbitMQ cluster namespace as a configmap, mounted it in the pod and used it for liveness and availability checks. This makes it a lot easer to construct a more complex livenes and readiness check.

If this isn't supported "out of the box" using the Helm Chart - it should be possible to use the Helm Chart + kustomize in order to make this work as expected (at least we use this pattern for some deployments).

Br

Hans K.
