### ISSUE TITLE
[stable/prometheus] Add support for 2.17.2

### ISSUE THREAD

**Issue by ericsuhong** [helm/charts#22240]
**Is your feature request related to a problem? Please describe.**
Prometheus has recently released 2.17.2 which includes a multitude of bug fixes since 2.16.0.

It would be nice if prometheus Helm chart comes with the latest 2.17.2 prometheus appVersion.

**Describe the solution you'd like**
Increase appVersion to 2.17.2

**Describe alternatives you've considered**
Directly install prometheus without relying on helm chart, but we would like to continue to use helm chart for installing prometheus

**Comment by marado00** [comment]
I was having the same problem , I wanted to test "selectors". 
Just did (with helm 3):
helm3 upgrade --install --namespace=monitoring prometheus stable/prometheus-operator -f values.prometheus.yaml --set prometheus.prometheusSpec.image.tag="v2.17.2"

This is redundant, you can do "--set ..." or define the desired version on the values yaml file.

Prometheus version was upgraded and everything looks fine, nevertheless, this is not a production cluster, I can't guarantee it won't break something.
