### ISSUE TITLE
[stable/nfs-server-provisioner]  mount.nfs: Protocol not supported 

### ISSUE THREAD

**Issue by hatharom** [helm/charts#22250]
**Describe the bug**
Using the default configuration on minikube and creating a PVC as described here: 
https://github.com/helm/charts/blob/master/stable/nfs-server-provisioner/templates/NOTES.txt

The pod to which I try to bind the PVC stucks in 'ContainerCreating' stage and gives this error (in kubectl describe pods xyz) :

<details>
Warning  FailedMount       5m38s      kubelet, minikube  MountVolume.SetUp failed for volume "pvc-accf2a00-3ddf-4f7e-91e8-37cbd35b20e3" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/1d1871a2-6954-49df-bb38-f5bb82db91ee/volumes/kubernetes.io~nfs/pvc-accf2a00-3ddf-4f7e-91e8-37cbd35b20e3 --scope -- mount -t nfs -o vers=3 10.109.85.240:/export/pvc-accf2a00-3ddf-4f7e-91e8-37cbd35b20e3 /var/lib/kubelet/pods/1d1871a2-6954-49df-bb38-f5bb82db91ee/volumes/kubernetes.io~nfs/pvc-accf2a00-3ddf-4f7e-91e8-37cbd35b20e3
Output: Running scope as unit: run-radfcacd2775e4143b2c048ec8b62d417.scope
mount.nfs: Protocol not supported
</details>

**Version of Helm and Kubernetes**:
Helm:
Client: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}

Kubectl
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

minikube
minikube version: v1.9.2

**Which chart**:
nfs-server-provisioner

**What you expected to happen**:
To starup and bind the volume

**Additional info**
At first start up I got an error like this:
(https://kb.netapp.com/app/answers/answer_view/a_id/1093853/~/mount%3A-%2Fpath%2Fto%2Fdir%3A-bad-option%3B-for-several-filesystems-%28e.g.-nfs%2C-cifs%29-you)
So I installed nfs-common manually into minikube.
 version: nfs-common        1:1.3.4-2.5ubuntu2

**Comment by ChrisTomAlx** [comment]
I have this same issue.. It works the first time.. But if I redeploy I get this error. Even if I scale down to 0 and then scale up I have the same issue. . Not sure what is happening

**Comment by jgato** [comment]
I have the same, from one of my hosts, when try to make a PVC and mounting the NFS resource. Should I install manually nfs-common in all hosts?

**Comment by jgato** [comment]
The problem seems to be, that the provider works in nfsv4 and my host supports nfsv3. Is it possible to configure the provisioner to also support the v3?

**Comment by bobleujr** [comment]
I am also getting this error. @jgato to answer you, I tried manually installing nfs-common across my nodes and the problem continues
