### ISSUE TITLE
[stable/anchore-engine] Certificates in secret don't get applied

### ISSUE THREAD

**Issue by FOTempel** [helm/charts#22255]
Describe the bug
Using an existing configuration for values.yaml I used before (succesfully on the same cluster) I installed the 1.6.0 version of the chart. This installs 0.7.1 of anchore-engine. Upon starting the engine, the catalog component didn't want to start because of certification verification errors for the S3 archive storage. This storage is a private S3 instance with company signed certificates.

I solved this in the previous version of the chart (1.3.7, anchore-engine 0.5.2) by including a secret with the root- and intermediate certificate of the CA with anchoreGlobal:certStoreSecretName. This worked great. However, this doesn't work anymore. The secret is there and gets mounted in the pod to /home/anchore/certs/ just fine. It turns out that there's logic in the container (/docker-entrypoint.sh) which handles these custom certificates. But when I look in the deployment which this chart generates I see that both "command" and "args" are defined, which according to https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes will cause ENTRYPOINT to be ignored. This means /docker-entrypoint,sh never gets called. Compiling all this leaves me with a couple of questionmarks. First, how has this ever been able to work at all as I don't see any recent changes to either the chart or the container which touch this mechanism. Second: how do I inject my intermediate certificates into anchore-engine as using anchoreGlobal:certStoreSecretName cannot work.

Version of Helm and Kubernetes:
Kubernetes : 1.15.3
Helm : 2.16.5

Which chart: 
stable/anchore-engine

What happened:
SSL validation errors for external services due to private CA SSL certificates missing despite being added with anchoreGlobal:certStoreSecretName

What you expected to happen:
anchore-engine to work with custom private CA certificates

How to reproduce it (as minimally and precisely as possible):
Try to use anchoreGlobal:certStoreSecretName to inject custom CA certificates, see if they get added properly (see: https://github.com/anchore/anchore-engine/blob/master/docker-entrypoint.sh). If in the container /docker-entrypoint gets executed by hand, everything works as expected. Ergo, in containers deployed with the chart the ENTRYPOINT gets ignored.

Anything else we need to know:
Probably.

**Comment by Btodhunter** [comment]
@FOTempel - thanks for pointing this out. I'm working on a fix right now to prevent the chart from overriding the entrypoint. I will try to get it pushed ASAP.

**Comment by FOTempel** [comment]
> 
> 
> @FOTempel - thanks for pointing this out. I'm working on a fix right now to prevent the chart from overriding the entrypoint. I will try to get it pushed ASAP.

Thanks for looking into this, did you make any progress yet? Is there anything I can do to help?

**Comment by Btodhunter** [comment]
I made some changes to the chart in our fork that I think will address this issue, I just need to find some time to test that it works as expected. Hopefully I'll be able to get that done early this week. If you want to check out my attempt at a fix, you can see it [here](https://github.com/anchore/charts/tree/anchore-issue-22255/stable/anchore-engine)

**Comment by d3vdr3y** [comment]
Tested the updated chart with the above use-case. 
Steps to validate success:
- Created a secret pointing to the cert key in the namespace: kubectl create secret <cert_name> --from-file=<cert_file>
- Added secret name to **_anchoreGlobal.dbConfig.sslRootCertName_** and **_anchoreGlobal.certStoreSecretName_** and enabled ssl **ssl=true**
- Deployed the helm chart and verified all pods enter running state
- Confirmed in the logs that the services are able to communicate with external postgres using the certificate

**Comment by FOTempel** [comment]
Works great, thank you!
