### ISSUE TITLE
[stable/falco] Enable using Falco minimal image with EBPF

### ISSUE THREAD

**Issue by arminc** [helm/charts#22268]
Before making changes I wanted to hear your opinion on the following: I would like to use the Falco minimal image and to do so I need to fetch the EBPF probe because the minimal image doesn't do that by itself. Besides that, I need to mount the correct folder (kernel debug) for Falco to work. Currently, this is not possible without manually changing the chart. 

I would propose to allow extra init container(s) to be added, as Grafana does https://github.com/helm/charts/pull/12343. This allows anyone to add an init container, for example, to fetch the correct EBPF probe and place it in "/root/.falco" so Falco can find it. Besides that, I would propose doing the same thing with the volumes for Falco allowing people to add for example "/sys/kernel/debug". Or because the necessity to add volumes is small we could make "/sys/kernel/debug" enabled or disabled with a flag as part of enabling EBPF.

@bencer 
@nestorsalceda

**Comment by leodido** [comment]
For your init container you could use the new `falcosecurity/driverloader` image

/cc @leogr

**Comment by leogr** [comment]
Hi @arminc ,

the feature you described is almost similar to what we are trying to achieve in the next Falco release. Basically, we want to provided all pieces and fixes needed to let third-party integrations - like the helm chart - implement the "init container approach" easily. 

As @leodido said we are preparing a new image for this purpose. 
But, note that: 
- `falcosecurity/driverloader` is not yet released, we're going to rename it soon (maybe it will be `falcosecurity/falco-driver-loader`
- `minimal` vs. `slim`: we would like to keep just one of them, and I hope that will be decided soon
- the next Falco release should happen in less than 2 weeks 

Thus I would ask you to wait a bit until these pieces are ready if you don't mind.

Furthermore, we will have our [community call](https://github.com/falcosecurity/community#falco-community-calls) later today and we will talk about this topic. I would be happy to hear your opinions!

**Comment by arminc** [comment]
Thanks for the quick replies. My understanding is that the falco-driver-loader is still creating the eBPF module (as init container). We use the falco-driver-loader to create the eBPF module while creating (hardening) the AMI. Then we just download the module with the init container which means the init container is simple as well.

I will join the call later
