### ISSUE TITLE
[stable/rocketchat] Add option to use existing PVC

### ISSUE THREAD

**Issue by varac** [helm/charts#22262]
**Is your feature request related to a problem? Please describe.**

We want to provide human redeable PV names and therefor create persistant volumes + claims ourselves, and need to use these for this chart. But there's no  `existingClaim` option for rocketchat so far.

**Describe the solution you'd like**

Add an `persistence.existingClaim` value to the chart.

**Describe alternatives you've considered**

None.

**Additional context**

Many other helm charts allow the usage of existing claims.

**Comment by mrtndwrd** [comment]
This issue is still relevant

**Comment by varac** [comment]
Please merge #22994 !
