### ISSUE TITLE
[stable/efs-provisioner] podLabels support

### ISSUE THREAD

**Issue by rvolykh** [helm/charts#22289]
**Is your feature request related to a problem? Please describe.**
stable/efs-provisioner currently only allows setting podAnnotations but not podLabels.
While I'm trying to collect metrics for services grouped by labels with Prometheus. `kube-state-metrics` which I use to collect metrics does not allow to select metrics by annotations.

**Describe the solution you'd like**
I would like to have the ability to set additional pod labels, by specifying them on values.yaml `podLabels`.

**Describe alternatives you've considered**
To do custom kubectl label after helm is installed.

**Additional context**
e.g. https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L79

**Comment by rvolykh** [comment]
Hello @hareku, @srueg , @mariusv,

1. Could you please review the issue?
2. Could I contribute to efs-provisioner helm chart with the proposed solution?

**Comment by mariusv** [comment]
Heya @rvandegrift , your proposal is great and please feel free to PR it and we will review.
Thanks a lot for the proposal and future PR
