### ISSUE TITLE
[stable/jenkins] Auto-determine Ingress API Version

### ISSUE THREAD

**Issue by fl-max** [helm/charts#22280]
The API Version for the ingress can be automatically determined in Helm.

**Is your feature request related to a problem? Please describe.**
Defaulting the ingress API Version to `extensions/v1beta1` will eventually break deployments on new K8s releases.

**Describe the solution you'd like**
We can automatically determine the correct API Version by checking the kubernetes version.

Replace [this line](https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-ingress.yaml#L2) with:

```yaml
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
```

Then remove [this line](https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml#L351).

**Describe alternatives you've considered**
Setting in `values.yaml` but this doesn't scale well.

**Additional context**

**Comment by torstenwalter** [comment]
@fl-max Could you create a PR for this?

**Comment by fl-max** [comment]
Added in `v1.23.1`. Closing
