### ISSUE TITLE
[stable/prometheus] nodeexporter only deployed on 2 of 3 nodes in cluster.

### ISSUE THREAD

**Issue by BMonsalvatge** [helm/charts#22296]
**Describe the bug**
Node Exporter pods only exist on 2 of the 3 nodes.

**Version of Helm and Kubernetes**:
Helm: version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
Kubernetes: 1.15

**Which chart**:
stable/prometheus

**What happened**:
When deploying the chart node exporter is only deployed on two out of the 3 nodes in the cluster and is only reporting metrics for those two.

**What you expected to happen**:
A node exporter should be deployed on each node.

**How to reproduce it** (as minimally and precisely as possible):
helm install with the default values.yaml

**Anything else we need to know**:
I am using EKS.

**Comment by tuananhnguyen-ct** [comment]
Can you list the status of your node-exporter pods? There might be some other reasons that the pod cannot be deployed to a node (limited resource?).

**Comment by BMonsalvatge** [comment]
I get the following when I describe the daemonset:
`k describe daemonset.apps/prometheus-node-exporter`
```
Name:           prometheus-node-exporter
Selector:       app=prometheus,component=node-exporter,release=prometheus
Node-Selector:  <none>
Labels:         app=prometheus
                chart=prometheus-11.0.4
                component=node-exporter
                heritage=Helm
                release=prometheus
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 2
Current Number of Nodes Scheduled: 2
Number of Nodes Scheduled with Up-to-date Pods: 2
Number of Nodes Scheduled with Available Pods: 2
Number of Nodes Misscheduled: 0
Pods Status:  2 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=prometheus
                    chart=prometheus-11.0.4
                    component=node-exporter
                    heritage=Helm
                    release=prometheus
  Service Account:  prometheus-node-exporter
  Containers:
   prometheus-node-exporter:
    Image:      prom/node-exporter:v0.18.1
    Port:       9100/TCP
    Host Port:  9100/TCP
    Args:
      --path.procfs=/host/proc
      --path.sysfs=/host/sys
    Environment:  <none>
    Mounts:
      /host/proc from proc (ro)
      /host/sys from sys (ro)
  Volumes:
   proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc
    HostPathType:
   sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:
Events:            <none>
```

Seems like its only trying to schedule 2 pods, unsure if there's a way to specify to run a pod per node in the cluster in the helm chart?

**Comment by BMonsalvatge** [comment]
Just checking back if anyone had any other thoughts on this, or needed additional output from the cluster.

**Comment by tuananhnguyen-ct** [comment]
Can you check if you can deploy any other daemonset (just use an example one) without any issue? Have you checked the node that is not schedulable for any event and/or tried rolling it? I'm having the same deployment on EKS and it works just fine.

**Comment by BMonsalvatge** [comment]
Thanks, restarting the node did the trick.  Appreciate the help!
