### ISSUE TITLE
[charts/stable/airflow v5.2.5] KubernetesExecutor S3 logs issue

### ISSUE THREAD

**Issue by aarrtteemmuuss** [helm/charts#22294]
**Describe the bug**
I use puckel/airflow 1.10.7 image and version 5.2.5 of airflow chart. I have enabled KubernetesExecutor but not able to make it work with S3 logging. 

Do I miss something in my configuration? 

I have following config: 

`AIRFLOW__CORE__REMOTE_LOGGING: True`
`AIRFLOW__CORE__REMOTE_LOG_CONN_ID: S3Connection`
`AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: s3://bucket/logs`
`AIRFLOW__CORE__ENCRYPT_S3_LOGS: False`

`AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__FERNET_KEY: "xxx"`
`AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__REMOTE_LOGGING: True`  `AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__REMOTE_LOG_CONN_ID: S3Connection` `AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: s3://bucket/logs`
`AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__ENCRYPT_S3_LOGS: False`

S3Connection created in admin UI and is S3 type with following settings: 
`{"aws_access_key_id":"xxx", "aws_secret_access_key": "xxx"}`

Log persistence is off:
logsPersistence:
  enabled: false
  existingClaim: logs-data

Logs path is left default:
logs:
  path: /usr/local/airflow/logs

**Version of Helm and Kubernetes**:
Helm 3
Kubernetes 1.14

**Which chart**:
stable/airflow v5.2.5

**What happened**:
When LocalExecutor starts on task pods it works as expected. But no logs go to S3, and when I try to pull logs for any task in UI I get something like this: 

*** Log file does not exist: /usr/local/airflow/logs/xxx/xxx/2020-05-07T17:10:34.054370+00:00/1.log
*** Fetching from: http://task-id-65d125b20e11:8793/log/xxx/xxx/2020-05-07T17:10:34.054370+00:00/1.log
*** Failed to fetch log file from worker. HTTPConnectionPool(host='task-id-65d125b20e11', port=8793): Max retries exceeded with url: /log/xxx/xxx/2020-05-07T17:10:34.054370+00:00/1.log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5b181ea50>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**What you expected to happen**:

Expected worker pod to write logs to S3 and UI admin being able to pull it for specific task. 

**How to reproduce it** (as minimally and precisely as possible):

Use same configuration as above with KubernetesExecutor and S3 logging enabled.

**Comment by thesuperzapper** [comment]
Please give this a go on v7.0.0 of the chart.
