### ISSUE TITLE
[stable/prometheus] imagePullSecrets not supported

### ISSUE THREAD

**Issue by DavidParks8** [helm/charts#22299]
The prometheus chart does not seem to support custom image pull secrets.

**Is your feature request related to a problem? Please describe.**
I need to be able to pull the prometheus containers from a private registry hosted behind a firewall.

**Describe the solution you'd like**
I would like to see imagePullSecrets as a supported value just like in [stable/nginx-ingress](https://github.com/helm/charts/tree/master/stable/nginx-ingress).

**Describe alternatives you've considered**
I've considered patching various service accounts with image pull secrets, but this seems very hacky.

**Comment by tuananhnguyen-ct** [comment]
Prometheus chart does support imagePullSecrets https://github.com/helm/charts/blob/3e262279b2abd4745a6e8b09c321ba4849003308/stable/prometheus/values.yaml#L7

**Comment by DavidParks8** [comment]
Thank you! I missed that when scanning the file.
