### ISSUE TITLE
[incubator/druid] data can only be queried within couple minutes  after loaded from kafka

### ISSUE THREAD

**Issue by StardustXiaoT** [helm/charts#22334]
I was follow https://druid.io/docs/0.12.3/tutorials/tutorial-kafka.html
to load streaming data from kafka.

Data can only be queried within couples minutes after I load data into kafka. 

the version is 0.12.3-2

I expected it be persistent into segments once I successfully run the supervisor. 

Middle manage has segments folder under /var/druid/
while historial statefulset only has segment-cache under /var/druid

Any thing I missed? or is there a way i can share volumes between statefulset?

BTW the only thing I changed was that I rebuild docker image to replace start-druid.sh to get rid of s3-extension on loadlist in common.runtime.properties.

**Comment by dlqwowo** [comment]
I have same problem.

**Comment by AWaterColorPen** [comment]
@StardustXiaoT @dlqwowo 
you can try [incubator/druid] chart version 0.2.0+
