### ISSUE TITLE
[stable/openldap] Custom OpenLDAP Configuration File Mount Does Not Work

### ISSUE THREAD

**Issue by chirangaalwis** [helm/charts#22343]
**Describe the bug**
The $subject is experienced (i.e. property `customLdifFiles`) when running this Helm chart with Docker image `osixia/openldap` version `1.3.0`. The same option when using the Docker image to build a simple Docker container works fine (outside of Kubernetes).

**Version of Helm and Kubernetes**:
Helm version: 3.1.2
GKE based Kubernetes Server version: 1.14+, Git Version: `v1.14.10-gke.27`

**Which chart**:
stable/openldap Helm chart version `1.2.3`

**What happened**:
The custom LDIF files were not executed during the initialization.

**What you expected to happen**:
The custom LDIF files being executed during the initialization.

**How to reproduce it** (as minimally and precisely as possible):
Set custom LDIF file to `customLdifFiles`.

**Anything else we need to know**:
Used the existing Helm chart few days back, with `osixia/openldap` Docker image version `1.3.0` image and this feature worked. But when running with the latest version `1.3.0` tagged image (as of 2020/05/10), it did not work.

**Comment by kyounger** [comment]
Might want to double-check that the ldif file can be imported via another means. I ran into what I thought was this issue, but it turned out to just be an invalid ldif file.

I will note there was zero indication anywhere that it failed, which was frustrating.

**Comment by chirangaalwis** [comment]
> Might want to double-check that the ldif file can be imported via another means. I ran into what I thought was this issue, but it turned out to just be an invalid ldif file.
> 
> I will note there was zero indication anywhere that it failed, which was frustrating.

@kyounger the same LDIF files work fine when using with a plain Docker image of version `1.3.0` to create a simple container. That means this issue seems to pop up when using it within the Helm chart.

**Comment by chirangaalwis** [comment]
Any update on this?

**Comment by jl-gogovapps** [comment]
I'm facing a similar issue.  During pod initialization:
```
Unable to mount volumes for pod "openldap-9dfc57484-kzm9w_default(449a
fcd9-b710-11ea-834c-02fde0f44a9d)": timeout expired waiting for volumes to attach or mount for pod "default"/"openldap-9dfc57484-kzm9w". list of unmounted vol
umes=[data]. list of unattached volumes=[customldif ldifworkingdir certs data default-token-4t6sl
```

Pod logs:
```
k logs -f openldap-9dfc57484-kzm9w
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Copy /container/service to /container/run/service
*** Search service in CONTAINER_SERVICE_DIR = /container/run/service :
*** link /container/run/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/run/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/run/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.startup.yaml
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
*** An error occurred. Aborting.
*** Shutting down /container/run/startup/slapd (PID 10)...
*** Init system aborted.
*** Killing all processes...
```

I tried without persistent storage also, but that didn't seem to work either.  I've been able to use the ldif through phpldapadmin without issue, but trying to tie that into the bootstrap prcess

**Comment by jl-gogovapps** [comment]
```
ldapadd -x -D cn=admin,dc=example,dc=org -f /container/service/slapd/assets/config/bootstrap/ldif/custom/01-default-users.ldif -W
```

This command seemed to work for me post pod initialization.  Also tried to find the init-container logs but no luck

**Comment by chirangaalwis** [comment]
Any update on this? Is this issue fixed?

**Comment by dclarke** [comment]
Also had a problem with this scenario: If i take the same ldif file in a docker image, and do not mount volumes for /var/lib/ldap, it works, the moment I mount volumes for data. The helm chart does not run the custom Ldif file, and this is because the /var/lib/ldap directory and the config directory are not empty on the second start of ldap.  Somehow data is written into those directories when i use a volume mount, vs when I don't.
if there is data in those directories, then the custom Ldif does not run. 
My question is how / why would this be occurring. ?
