### ISSUE TITLE
unable to build kubernetes objects from release manifest on stable/rabbitmq-ha

### ISSUE THREAD

**Issue by wawashra** [helm/charts#22346]
**Describe the bug**
when trying install "rabbitmq-ha" I have an error
Error: unable to build kubernetes objects from release manifest

**Version of Helm and Kubernetes**:
Version of Helm : "v3.2.1"
Version of Kubernetes : "v1.17.5-0"

**Which chart**:
stable/rabbitmq-ha

**What happened**:
$ helm install rabbitmq stable/rabbitmq-ha
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"

**Comment by armab** [comment]
Confirming the bug too.
This is caused by the following PR: https://github.com/helm/charts/pull/21274#issuecomment-628279559

The regression was released in `rabbitmq-ha` chart version `1.44.2`.
`1.44.1` works OK.

**Comment by xpicio** [comment]
I have the same problem, the `1.44.1` it's ok

**Comment by fowlmouth** [comment]
This is still a problem for 1.46.4

**Comment by subravi92** [comment]
Still the issue persists in 1.46.4.

**Comment by JamesDowning** [comment]
Also experiencing the issue in 1.46.0

**Comment by katmai** [comment]
1.46.5 has it as well. just tried now.

**Comment by evanniedojadlo** [comment]
Confirming this issue on my end as well. I attempted `helm install rabbitmq-ha stable/rabbitmq-ha` on a local KinD cluster and returned the following: `Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"` 

as mentioned above, `1.44.1` installed without any issue

**Comment by t0k4rt** [comment]
Confirming issue for version 1.47.0
