### ISSUE TITLE
[stable/mongodb-replicaset] Upgrade to MongoDB 4.2 ?

### ISSUE THREAD

**Issue by olivierboudet** [helm/charts#22352]
The chart mongodb-replicaset is currently supporting mongodb 3.6. May it be upgraded to 4.2 ?

**Comment by dgdevops** [comment]
Hello @olivierboudet ,
Today I tested the original mongodb-replicaset chart (that uses MongoDB 3.6 by default) and I managed to upgrade it to 4.2.7 successfully. I just changed the image tag in the chart to 4.2.7 and installed the modified chart. In case you currently have the chart installed with version 3.6 on persistentVolume its necessary to change the featureCompatibilityVersion before you go for the upgrade.

Dan

**Comment by olivierboudet** [comment]
Hello, 
Yes it works, I use it also with image tag 4.2.5 but there is some deprecated server options (mostly ssl options) which may be updated.

**Comment by PierreBrisorgueil** [comment]
hello, quick example if someone has time.  https://github.com/weareopensource/rancher-catalog/tree/master/charts/mongodb-replicaset/4.2

Just ssl migration, adding this forgotten PR https://github.com/helm/charts/issues/12954, and rancher catalog

I'm sorry, not an expert and lack of time for PR, I had to make a repo for my need today, sticking to the Mongodb release. I would try to PR later asap.
