### ISSUE TITLE
 minio chart doesn't work with mode: distributed 

### ISSUE THREAD

**Issue by iirekm** [helm/charts#22354]
```
    Command:
      /bin/sh
      -ce
      /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server  http://minio-{0...0}.minio-svc.default.svc.cluster.local/export
```

What the hell is that 0...0????!!!!

**Comment by TreeKat71** [comment]
Hi iirekm,
No quite sure which way you use to deploy the cluster, could you provide more informations?
If you use helm chart please provide the minio image tag in the chart.
