### ISSUE TITLE
[stable/rabbitmq-ha] Unable to scale the replicasCount

### ISSUE THREAD

**Issue by rakeshnambiar** [helm/charts#22363]
**Describe the bug**
Unable to scale-up or scale-down the default replica count which is 3 by default.

**Version of Helm and Kubernetes**:
Helm -` v3.0.2`
K8s - `v1.17.0`

**Which chart**:
stable/rabbitmq-ha

**What happened**:
```
Error: UPGRADE FAILED: cannot patch "dev-rb-release-rabbitmq-rabbitmq-ha" with kind StatefulSet: StatefulSet.apps "dev-rb-release-rabbitmq-rabbitmq-ha" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```
**What you expected to happen**:
Additional 1 POD must be created

**How to reproduce it** (as minimally and precisely as possible):
`helm upgrade -name dev-rb-release-rabbitmq --set replicaCount=4,prometheus.operator.enabled=false stable/rabbitmq-ha`

**Anything else we need to know**:
N/A

**Comment by steven-sheehy** [comment]
You must've set some other value during your initial install (or previous upgrade) that you're not carrying over for your most recent upgrade. You can try adding --reuse-values to your upgrade command.

Or try install the [helm diff](https://github.com/databus23/helm-diff) plugin and seeing what is actually changing.
