### ISSUE TITLE
[stable/datadog] unknown field "seLinuxLabel"

### ISSUE THREAD

**Issue by monganai** [helm/charts#22374]
**Describe the bug**
seLinuxLabel is currently not recognised when using the sample configuration within `values.yaml`.

When implementing the standard configuration for systems with selinux in enforcing mode:

```
  securityContext:
    seLinuxOptions:
      seLinuxLabel: "spc_t"

```

The following error is thrown when deploying the chart with `values.yaml` :

```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(DaemonSet.spec.template.spec.securityContext.seLinuxOptions): unknown field "seLinuxLabel" in io.k8s.api.core.v1.SELinuxOptions
```

**Version of Helm and Kubernetes**:

Helm version:
```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

```
Agent image:
```
7.19.0
```

**Which chart**:

```
NAME        	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART        	APP VERSION
agent	default  	5       	2020-05-13 09:10:22.943186 +0100 IST	deployed	datadog-2.2.9	7          
```

**What happened**:

When attempting to use the provided example options in `values.yaml` [Link](https://github.com/helm/charts/blob/master/stable/datadog/values.yaml#L50-L52), the file fails to validate and the agent cannot be deployed.

**What you expected to happen**:
I expected the agent to be deployed with elevated SELinux permissions.

**How to reproduce it** (as minimally and precisely as possible):

- install Helm and get the latest `values.yaml` from the documentation.
- Uncomment the default options for security context to enable them.
- Deploy the agent using `values.yaml`
- The result is the issue mentioned 

**Anything else we need to know**:

This has been replicated in multiple setups in the past few days

**Comment by vamshisiddarth** [comment]
seLinuxLabel is not expected here. Security context should be as follows:

```
securityContext:
    seLinuxOptions:
      user: system_u
      role: system_r
      type: spc_t
      level: s0
```

This scenario is applicable whenever the SELinux is "enforcing". `ps -efZ | grep docker` or `ps -efZ | grep kubelet` will give you the output with all the seLinuxOptions. Configure your security context accordingly.
