### ISSUE TITLE
Should incubator/oauth-proxy be dropped

### ISSUE THREAD

**Issue by steakunderscore** [helm/charts#22370]
**Describe the bug**

Currently there is two charts for oauth2-proxy:
- incubator/oauth-proxy
- stable/oauth2-proxy

The incubator chart is using the original upstream of [oauth2-proxy which was archived by Bitly at the end of September 2018](https://github.com/bitly/oauth2_proxy).
The stable chart is using [oauth2-proxy/oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy). This was shifted from pusher/oauth2_proxy by the maintainers early 2020.

Since the incubator version is very out of date, and duplicates the stable copy. I would suggest that incubator/oauth-proxy be dropped.

**Version of Helm and Kubernetes**:

This is the case on master

**Anything else we need to know**:

**Comment by amnk** [comment]
I'm confused, because stable uses `pusher` repo everywhere: https://github.com/helm/charts/blob/137c7d41475af2bec795c7b48f80b2fad9e627a4/stable/oauth2-proxy/Chart.yaml

or I am missing something?

**Comment by steakunderscore** [comment]
Take a look at the chart in incubator. It doesn't use pusher/oauth2_proxy: https://github.com/helm/charts/blob/master/incubator/oauth-proxy/Chart.yaml

**Comment by amnk** [comment]
Incubator one is outdated, because Bitly archived their repo, as stated by the author of this issue.
