### ISSUE TITLE
[stable/nginx-ingress] Add support for Nginx 0.32.0

### ISSUE THREAD

**Issue by ericsuhong** [helm/charts#22404]
**Is your feature request related to a problem? Please describe.**
Nginx has recently released 0.32.0 which includes a multitude of bug fixes since 0.30.0

It would be nice if nginx-ingress Helm chart support the latest 0.32.0 nginx appVersion.

**Describe the solution you'd like**
Increase nginx appVersion to 0.32.0

**Describe alternatives you've considered**
Directly install nginx-ingress without relying on helm chart, but we would like to continue to use helm chart for installing nginx

**Comment by tuananhnguyen-ct** [comment]
It might be more convenient to switch to https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx instead.
