### ISSUE TITLE
[stable/prometheus-operator] grafana.ini values won't get picked up with the helm command

### ISSUE THREAD

**Issue by andyadamides** [helm/charts#22401]
**Describe the bug**
Attempting to configure `grafana.ini` properties won't get picked up with helm command through `--set`.

**Version of Helm and Kubernetes**:
helm version: 2.16.1
k8 version: 1.15.10

**Which chart**:
stable/prometheus-operator

**What happened**:
I need to configure the `grafana.ini` property of [client_secret](https://grafana.com/docs/grafana/latest/auth/generic-oauth/)(parent=auth.generic_oauth) as a `--set` value. Having tried various combinations the client_secret will not get picked up. What is the correct way to pass it through?

The full path in the `.yaml` is as follows:

```
grafana:
   grafana.ini:
       auth.generic_oauth:
             client_secret:""
```
**What you expected to happen**:
Configure the value for `client_secret` through `helm --set` instead of in the `yaml` file.

**How to reproduce it** (as minimally and precisely as possible):
```
helm upgrade \
prometheus-operator \
stable/prometheus-operator \
--install \
--version=8.1.2 \
-f config.yaml 
```

**Anything else we need to know**:
Failed attempts include:
```
--set 'grafana\.ini'.auth.generic_oauth.client_secret=xxx \
--set grafana.'grafana\.ini'.auth.generic_oauth.client_secret=xxx \ 
--set grafana.grafana.ini.auth.generic_oauth.client_secret=xxx \
--set grafana.auth.generic_oauth.client_secret=xxx \
--set grafana\.ini.auth.generic_oauth.client_secret=xxx \
--set grafana.grafana.ini={auth.generic_oauth.client_secret=xxx}
```

**Comment by andyadamides** [comment]
Any update on this?

**Comment by piraces** [comment]
Have you tried using the following?

`--set grafana.grafana\.ini.auth\.generic_oauth.client_secret=xxx`

You must escape all dots which takes part of a parameter.

**Comment by andyadamides** [comment]
Thanks @piraces - ```--set grafana."grafana\.ini"."auth\.generic_oauth".client_secret=xxx``` worked.
