### ISSUE TITLE
stable/lamp relies on maintenance-only Lego for SSL

### ISSUE THREAD

**Issue by karllhughes** [helm/charts#22415]
**Is your feature request related to a problem? Please describe.**
The [SSL option](https://github.com/helm/charts/tree/master/stable/lamp#network) in the `stable/lamp` chart uses [kube-lego](https://github.com/jetstack/kube-lego), which is now no longer being updated.

**Describe the solution you'd like**
It would be great to upgrade the chart to rely on the suggested successor to lego: [cert-manager](https://github.com/jetstack/cert-manager/). There is a [Migration Guide here](https://cert-manager.io/docs/tutorials/acme/migrating-from-kube-lego/).

**Describe alternatives you've considered**
If you're using K8s < 1.8, using lego seems to be fine, but this will eventually be a problem as newer versions of Kubernetes show up.

**Additional context**
I have never built a custom Helm chart, so I'm probably not the best person to take this on, but I'm happy to help out if I can. Just wanted to make sure it wasn't already being worked on before I dug in further.

**Comment by mortenbirkelund** [comment]
Any news regarding this? @AndyMardell and @karllhughes

**Comment by karllhughes** [comment]
I got no reply so I sort of assumed this is not of interest to anyone. Maybe I didn't tag the right person?
