### ISSUE TITLE
[stable/airflow] Unable to update airflow postgres creds

### ISSUE THREAD

**Issue by karadia10** [helm/charts#22429]
Hi, 
When I try to provide my custom postgres credentials to [stable/airflow] it gets ignored and default postgres is used

**Comment by volnt** [comment]
Hello,

I faced the same issue but found a solution. 

In order for the postgres connection to use a given password a kubernetes secret should be created accordingly. See the [doc](https://hub.helm.sh/charts/stable/airflow) :

![image](https://user-images.githubusercontent.com/2411932/82412267-a649ea80-9a73-11ea-99d7-63adeb9e3846.png)

I think the documentation should be more explicit about this. Right now the `Helm chart Configuration` makes the user think that setting `postgresql.postgresqlPassword` should work (and maybe it really should, but this I don't know).

**Comment by thesuperzapper** [comment]
This issue has been fixed as of 7.0.0

**Comment by volnt** [comment]
The documentation is much better with the 7.0.0, thanks for the update :)
