### ISSUE TITLE
[stable/fluent-bit] Improve extensibility of fluent-bit chart for sub-chart usage.

### ISSUE THREAD

**Issue by frankreno** [helm/charts#22441]
This an issue related to https://github.com/helm/charts/issues/14494.

I work at Sumo Logic and we package the Fluent-bit helm chart as a sub chart with our main chart for our Kubernetes collection.

https://github.com/SumoLogic/sumologic-kubernetes-collection

The inability to do what this PR was trying to forces us to use `rawConfig` section and override just to add the rotate_wait property.  The problem is the current `extraEntries` solution can only be used to add additional input plugins, but not extra configuration for an input plugin. When the SystemD option is enabled, you cannot extend the config of the tail section. The challenge of using `rawConfig` is we lose the benefit of the community contributions when we upgrade.  We must always upgrade our values.yaml overrides which is also difficult for customers. We also have customers with very high volume logging that require changes to rotate_wait and refresh_interval.

I was wondering if you would be more open to accepting a PR with the following change instead:

  * Add `input.tail.refresh_interval` with a default of 5, so that it can be configurable instead of hardcoded.
  * Add the following properties that enable users to customize the configuration of a given input.
    * `input.tail.extraConf`
    * `input.systemd.extraConf`
    * `audit.input.extraConf`

Now users can fine-tune each input as needed, with the limited overhead of the chart and the chart still retains sensible defaults.  Users can also leverage `extraEntries.input` to add additional Input sections if they have a need to.

If you are open to this kind of a PR instead, the Sumo team would be happy to contribute this back as we (and all of our Kubernetes customers) are consumers of the helm chart.

**Is your feature request related to a problem? Please describe.**
It is a maintenance problem when it comes to maintaining this chart as part of our sub chart. It has been suggested in other issues and PRs and issues to use extraEntries, however that only works when systemd is not enabled.

**Describe the solution you'd like**
Described above.

**Describe alternatives you've considered**
rawConfig is what we have been using but it creates a lot of friction. I believe the proposed solution reduces friction and exposes enough that users retain control.

**Comment by Towmeykaw** [comment]
Hi! We are trying to focus our efforts on improving the official chart https://github.com/fluent/helm-charts/tree/master/charts/fluent-bit, since the stable repo will be depricated soon. Could you check if it would work to use that chart instead?
