### ISSUE TITLE
stable/fluent-bit not working with logstash_dateformat attribute for ES

### ISSUE THREAD

**Issue by ghost** [helm/charts#22465]
**Describe the bug**
When using logstash_dateformat in the values.yaml file set to %Y%m it is not working

**Version of Helm and Kubernetes**:
Kubernetes 1.15.10 and helm 2.14.3

**Which chart**:
stable/fluent-bit

**What happened**:
Logs are using the default index date pattern of year month and date

**What you expected to happen**:
Logs just use year and month

**How to reproduce it** (as minimally and precisely as possible):
set logstash_dateformat to %Y%m

**Anything else we need to know**:
No

**Comment by Towmeykaw** [comment]
This should be fixed by https://github.com/helm/charts/pull/22485

**Comment by andrea-82** [comment]
Unless I'm missing something else, this does not work for me yet, even after upgrading to fluent-bit "2.8.14".

These are the settings I applied to the chart:

# helm -n admin get values fluent-bit
USER-SUPPLIED VALUES:
backend:
  es:
    host: elasticsearch.k8s.master.something.int
	logstash_dateformat: '%Y.%m.%d-00001'
	logstash_format: "On"
	logstash_prefix: k8s-master
	port: 80
	type: _doc
  type: es
filter:
  mergeLogKey: appLog
service:
  logLevel: info

All my indices are getting called "k8s-master-%Y.%m.%d" (eg "k8s-master-2020.04.27"), which is the default, no matter what I change.

Any clue?

**Comment by Towmeykaw** [comment]
What is the -00001 at the end supposed to do? Im not very familiar with strftime.

**Comment by boxcee** [comment]
Same problem here:

`values.yaml`
```
backend:
  es:
    host: "logging-elasticsearch"
    index: logstash
    logstash_prefix: logstash
    time_key: '@fluent_timestamp'
  retry_limit: 5
  type: es
  logstash_dateformat: '%Y-%m-%d'
```
`curl "http://localhost:9200/_aliases"` to ElasticSearch cluster shows me:
```
{
  "logstash-2020.06.25": {
    "aliases": {}
  },
  "logstash-2020.06.26": {
    "aliases": {}
  },
  "logstash-2020.06.27": {
    "aliases": {}
  },
  "logstash-2020.06.28": {
    "aliases": {}
  },
  "logstash-2020.06.29": {
    "aliases": {}
  },
  "logstash-2020.06.30": {
    "aliases": {}
  }
}
```

**Comment by boxcee** [comment]
Ooopsy, the `logstash_dateformat` is on the wrong level. Maybe you have the same problem @andrea-82?
