### ISSUE TITLE
[stable/airflow]  variable invalid

### ISSUE THREAD

**Issue by superbeer** [helm/charts#22522]
**Describe the bug**

**Version of Helm and Kubernetes**:

**Which chart**:
airflow-7.1.0

**What happened**:
variable invalid

**What you expected to happen**:
variable have value

**How to reproduce it** (as minimally and precisely as possible):

values.yaml
```
scheduler:
  variables: |
    { "environment": "dev" }
```
![image](https://user-images.githubusercontent.com/20677737/82850027-e6521700-9f24-11ea-89e0-5f642fbbbdda.png)

**Anything else we need to know**:

**Comment by thesuperzapper** [comment]
@superbeer You probably need to configure a fernet key, please use `airflow.fernetKey` or `airflow.extraEnv`.

**Comment by thesuperzapper** [comment]
@gsemet, this is why I am not sure about including a default fernet key value, while it may reduce security as users don't change it, at least their deployment will work correctly.

**Comment by gsemet** [comment]
I think it is a good idea not to force people to do boring stuff when they just want to try airflow. A default unsecured key is ok for me
