### ISSUE TITLE
[stable/airflow] KubernetesExecutor ConfigMap is missing when worker runs on a different namespace

### ISSUE THREAD

**Issue by liorhar** [helm/charts#22533]
**Describe the bug**
When setting AIRFLOW__KUBERNETES__NAMESPACE to a different namespace than the web/scheduler pods the workers fail to create with `CreateContainerConfigError` due to missing ConfigMap. 
I believe the airflow-env ConfigMap is only created in the release namespace.

**Version of Helm and Kubernetes**:
helm 2.4.3
Kubernetes 1.14

**Which chart**:
airflow 7.1.1

**What happened**:
Pods fail to create when configured to run in a namespace other than the release namespace

**What you expected to happen**:
Pods run and configured properly

**How to reproduce it** (as minimally and precisely as possible):
KubernetesExecutor with env AIRFLOW__KUBERNETES__NAMESPACE set to a namespace other than the release.

**Anything else we need to know**:

**Comment by thesuperzapper** [comment]
What are you trying to achieve by settings a differnt `AIRFLOW__KUBERNETES__NAMESPACE`, and what error are you getting, can you provide logs?
