### ISSUE TITLE
[stable/airflow] Enable RBAC on airflow

### ISSUE THREAD

**Issue by sk2991** [helm/charts#22560]
We are trying to enable RBAC on Airflow using links 
https://github.com/apache/airflow/pull/3015
https://github.com/apache/airflow/issues/8179

We are not sure on how to create webserver_config.py
1) Do we need to create it as a config map?
2) Are there any runtime configurations that we can set? We were looking at the airflow documentation and couldn't find any.

**Version of Helm and Kubernetes**:
Helm: v2.16
Kubernetes: 1.16

**Which chart**:
Chart version: 6.x

**What you expected to happen**:
Enable RBAC on airflow

**How to reproduce it** (as minimally and precisely as possible):
In values.yml - add
AIRFLOW__WEBSERVER__RBAC: "true"

**Comment by thesuperzapper** [comment]
In terms of using LDAP for role binding in FlaskAppBuilder, I am still working on the [that PR](https://github.com/dpgaspar/Flask-AppBuilder/pull/1374).

To set a `webserver_config.py` please view the the [`ConfigMap/airflow-cluster1-webserver-config`](https://github.com/helm/charts/blob/master/stable/airflow/examples/google-gke/k8s_resources/configmap-webserver.yaml) inside the [google gke example](https://github.com/helm/charts/blob/master/stable/airflow/examples/google-gke/custom-values.yaml).

**Comment by sk2991** [comment]
Thanksfor the update. I have tried with the suggested approach:

In values.yml
airflow:
  extraConfigmapMounts: 
  - name: airflow-webserver-config
    mountPath: /usr/local/airflow/webserver_config.py
    configMap: airflow-webserver-config
    readOnly: true
    subPath: webserver_config.py

Configmap-webserver.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-webserver-config
  labels:
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  webserver_config.py: |
    import os
    from airflow.configuration import conf
    from flask_appbuilder.security.manager import AUTH_LDAP
    basedir = os.path.abspath(os.path.dirname(__file__))
    # The SQLAlchemy connection string.
    SQLALCHEMY_DATABASE_URI = conf.get("core", "SQL_ALCHEMY_CONN")
    # Flask-WTF flag for CSRF
    CSRF_ENABLED = True
    #LDAP configurations
    AUTH_TYPE = AUTH_LDAP
    AUTH_ROLE_ADMIN = "Admin"
    AUTH_LDAP_SERVER = "ldap://<ldap_url>:389"
    AUTH_LDAP_BIND_USER = "CN=<user>,DC=<company>,DC=com"
    AUTH_LDAP_BIND_PASSWORD = "<password>"
    AUTH_LDAP_UID_FIELD = "sAMAccountName"
    AUTH_LDAP_SEARCH = "DC=<company>,DC=com"
    AUTH_LDAP_USE_TLS: "false"
    AUTH_LDAP_ALLOW_SELF_SIGNED: "false"
    AUTH_LDAP_TLS_CA_CERTIFICATE: ""

I see access denied error, without providing any credentials.
![Screen Shot 2020-05-28 at 9 29 02 PM](https://user-images.githubusercontent.com/20148995/83215671-2257c880-a12d-11ea-939f-6a4b5d3edfd6.png)

**Comment by thesuperzapper** [comment]
Check the logs of your web pod, and you will be able to resolve your own issue.

I also recommend trying to get it connecting to the LDAP from your local machine first, and then copying the `webserver_config.py` into your secret.

However, in this case you probably are just missing the `Flask-OAuthLib` library, which is a dependency of `AUTH_LDAP` as described in the [flask docs](https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth).

You can use the `web.extraPipPackages` to add it:
```yaml
web:
  extraPipPackages:
    - "apache-airflow[google_auth]==1.10.10"
```
