### ISSUE TITLE
[stable/airflow] externalDatabase.passwordSecret ignored

### ISSUE THREAD

**Issue by dnishimura** [helm/charts#22614]
**Describe the bug**
Unable to set `externalDatabase.passwordSecret`

**Version of Helm and Kubernetes**:
helm v3.2.0
k8s 1.17.0

**Which chart**:
stable/airflow 7.1.3

**What happened**:
I am trying to use my own external postgres database. I set `postgresql.enabled=false` and then set `externalDatabase.passwordSecret=my-airflow-postgres-password`, but it keeps defaulting to `<namespace>-externaldb`

**What you expected to happen**:
I expect `externalDatabase.passwordSecret` to be set to the secret that I specify

**How to reproduce it** (as minimally and precisely as possible):
Set `postgresql.enabled=false` and set `externalDatabase.passwordSecret=<postgres secret>`. Run the helm install command with the --dry-run flag with the custom-values.yaml that contain the above fields set as described.

**Anything else we need to know**:

**Comment by thesuperzapper** [comment]
Are you sure you are not also passing a custom `--values` file in with some override for `externalDatabase.passwordSecret`, because I just checked, and this feature works for me?

**Comment by dnishimura** [comment]
@thesuperzapper - thank you for the prompt response. My apologies for wasting some of your time. I realized my mistake after some sleep. It turned out I was running the bitnami/airflow chart, not the stable/airflow chart. Sorry about that!
