### ISSUE TITLE
[stable/sonarqube] Loading Loop page

### ISSUE THREAD

**Issue by bubilla** [helm/charts#22621]
Hello everyone.
Currently I made the installation of SonarQube through Helm 3.0
I have seen the service and it is running correctly.
I have exposed the service through a Gateway in Istio for ingress configuration.
However, when trying to access through the url, I receive these messages when inspecting the page, and the page does not stop loading.

![image](https://user-images.githubusercontent.com/39936294/83419265-d2aa2300-a3f2-11ea-90d4-c1efb46fc428.png)

**Comment by bubilla** [comment]
VirtualService

- match:
    - uri:
        exact: /sonar
    - uri:
        prefix: /sonar/
    rewrite:
      uri: "/"
    route:
    - destination:
        host: sonarqube-sonarqube.default.svc.cluster.local
        port:
          number: 9000

**Comment by darede-git** [comment]
any success @bubilla ? I think it`s something related with SONAR_WEB_CONTEXT

**Comment by bubilla** [comment]
I had to create an ExternalIP type microservice to be able to work from the root of the project, it was the only way to access it.


I was trying to access the ClusterIP service in this way, but it was not successful, presenting the initial problem.

- match:
    - uri:
        exact: /sonar
    - uri:
        prefix: /sonar/
    rewrite:
      uri: "/"
    route:
    - destination:
        host: sonar.default.svc.cluster.local
        port:
          number: 9000
