### ISSUE TITLE
[stable/prometheus-operator] Upgrade Grafana version

### ISSUE THREAD

**Issue by kbreit** [helm/charts#22643]
Grafana 7.0 is out and the prometheus-operator chart locks the version at 6.x. Please update the chart to use 7.0.

**Comment by cpumanaz** [comment]
The code change is easy. Bump version to 5.1.* from 5.0.*

How is this tested, is there automated testing to ensure the chart works 100% like it would after the change, or can effort be spent to perform manual testing on this?

`  - name: grafana
    version: "5.1.*"
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: grafana.enabled`
