### ISSUE TITLE
[stable/prometheus-operator] doesn't use multi-arch images

### ISSUE THREAD

**Issue by ruckc** [helm/charts#22644]
**Describe the bug**
When `helm install stable/prometheus-operator` 2 of the pods don't start due to `exec format error` which is an architecture incompatibility.

```
$ kubectl get pods --namespace monitoring
NAME                                                   READY   STATUS                  RESTARTS   AGE
monitoring-grafana-5c4dbdb56b-fwqmg                    0/2     Init:CrashLoopBackOff   10         29m
monitoring-kube-state-metrics-96f87d848-9ct98          0/1     CrashLoopBackOff        10         29m
monitoring-prometheus-node-exporter-gf44v              1/1     Running                 0          29m
monitoring-prometheus-node-exporter-jbb7k              1/1     Running                 0          29m
monitoring-prometheus-node-exporter-jlczk              1/1     Running                 0          29m
monitoring-prometheus-node-exporter-nm62p              1/1     Running                 0          29m
monitoring-prometheus-node-exporter-qvx8k              1/1     Running                 0          29m
monitoring-prometheus-node-exporter-rfvkc              1/1     Running                 0          29m
monitoring-prometheus-node-exporter-rk8js              1/1     Running                 0          29m
monitoring-prometheus-node-exporter-rtzql              1/1     Running                 0          29m
monitoring-prometheus-node-exporter-twh92              1/1     Running                 0          29m
monitoring-prometheus-node-exporter-xfmrt              1/1     Running                 0          29m
monitoring-prometheus-oper-operator-6bffc487c5-xqdzl   0/2     CrashLoopBackOff        20         29m

$ kubectl logs --namespace monitoring monitoring-prometheus-oper-operator-6bffc487c5-xqdzl --all-containers
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"

$ kubectl logs --namespace monitoring monitoring-kube-state-metrics-96f87d848-9ct98 --all-containers
standard_init_linux.go:211: exec user process caused "exec format error"

$ kubectl logs --namespace monitoring monitoring-grafana-5c4dbdb56b-fwqmg  --all-containers
standard_init_linux.go:211: exec user process caused "exec format error"
Error from server (BadRequest): container "grafana-sc-dashboard" in pod "monitoring-grafana-5c4dbdb56b-fwqmg" is waiting to start: PodInitializing

```

**Version of Helm and Kubernetes**:
$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm64"}

**Which chart**:
stable/prometheus-operator 0.38.1

**What happened**:
Didn't fully start, because it pulled x86_64 containers.

**What you expected to happen**:
It to use the arm64 containers

**How to reproduce it** (as minimally and precisely as possible):
Take a raspberry pi 4, install ubuntu server 64-bit, install kubernetes from kubernetes.io instructions, install helm, helm install stable/prometheus-operator

**Comment by cablespaghetti** [comment]
Can we reopen closed issues or do I need to make a new issue? I am interested in trying to resolve this.
