### ISSUE TITLE
[incubator/sparkoperator] Unable to upgrade release between operator versions

### ISSUE THREAD

**Issue by hagaibarel** [helm/charts#22645]
**Describe the bug**
Can't upgrade a release of the spark operator chart when there's a version change for the operator version

**Version of Helm and Kubernetes**:
```
helm version:
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

kubernetes version:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-21T01:25:41Z", GoVersion:"go1.13.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
incubator/sparkoperator

**What happened**:
While trying to upgrade a release to a newer version (0.7.0 -> 0.7.1), the upgrade failed with the following error - 

```
Error: UPGRADE FAILED: cannot patch "sparkopertor-sparkoperator" with kind Deployment: Deployment.apps "sparkopertor-sparkoperator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"sparkoperator", "app.kubernetes.io/version":"v1beta2-1.1.2-2.4.5"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**What you expected to happen**:
The upgrade process should complete succesfuly

**How to reproduce it** (as minimally and precisely as possible):

```
helm install sparkopertor incubator/sparkoperator --version 0.7.0

helm upgrade sparkopertor incubator/sparkoperator
```

**Anything else we need to know**:
The problem seems to come from here: https://github.com/helm/charts/blob/88a5176022e8dda60a498d2b8953a9feb3d13b0b/incubator/sparkoperator/templates/spark-operator-deployment.yaml#L19-L22

Since the deployment selector labels is immutable it causes changes to fail

**Comment by infa-ssaurabh** [comment]
I am also facing this issue, how to upgrade successfully?

**Comment by infa-ssaurabh** [comment]
/
