### ISSUE TITLE
[stable/datadog] Resources are not enabled as documented

### ISSUE THREAD

**Issue by InAnimaTe** [helm/charts#22661]
**Describe the bug**
As per https://github.com/helm/charts/blob/master/stable/datadog/values.yaml#L467, Resources for each agent container are commented out instead of being enabled as eluded to in the docs (under [configuration options](https://github.com/helm/charts/blob/master/stable/datadog/README.md#all-configuration-options))

**Which chart**:
`2.3.8` of the datadog chart

@xlucas @clamoriniere Please halp! Thanks!

PS: Any insight/links on how these values were derived and how accurate they are would be in larger clusters would be much appreciated!

**Comment by xlucas** [comment]
Well, sorry for the late reply.

I don't see the issue 🤔 

Values commented out in the helm chart are there for documentation purposes so you have an example of how to use them.

**Comment by xlucas** [comment]
Sorry for the late reply, yeah there's an issue indeed default resource limits were removed by https://github.com/helm/charts/pull/13138 (and that makes sense) but the README wasn't updated accordingly 🤔
