### ISSUE TITLE
[stable/openvpn] no working with Istio 1.6

### ISSUE THREAD

**Issue by dg-jwmera** [helm/charts#22695]
**Describe the bug**
stable/openvpn does not work correctly with Istio 1.6, since Istio has changed the ports on which Envoy manages traffic (15001 y 15006).

**Version of Helm and Kubernetes**:
Helm v2.16.1
Kubernetes v1.14.10-gke.36

**Which chart**:
stable/openvpn

**What happened**:
The vpn connects to the cluster of kubernetes, but cannot access any pod or service, it shows an error 503 "upstream connect error or disconnect / reset before headers. Reset reason: connection failure"

**What you expected to happen**:
Istio 1.6 has changed the ports on which Envoy manages traffic (15001 y 15006).

**How to reproduce it** (as minimally and precisely as possible):
Install Istio 1.6 with demo profile
Activate istio for the default namespace (kubectl label namespace default istio-injection = enabled)
Install chart stable / openvpn in the default namespace
Try to access a pod through the VPN

**Anything else we need to know**:
Istio 1.6 has changed the ports on which Envoy manages traffic (15001 y 15006).

**Comment by jasongwartz** [comment]
Hi @dg-jwmera - thanks for reporting this. I'm not an Istio/Envoy user, but I'd be happy to see a PR if you have an idea of how to address this.

**Comment by dg-jwmera** [comment]
Hi @jasongwartz , I have no idea how to deal with this problem, I tried several things but none worked, so I am asking for help with this problem.

**Comment by jasongwartz** [comment]
@dg-jwmera no worries. Since I don’t use Istio or Envoy I don’t think I’ll be much help, but I’m happy to leave the issue open in case anyone sees this who wants to chime in.

**Comment by dg-jwmera** [comment]
Help !!
