### ISSUE TITLE
Prometheus chart fails to initialize on GKE

### ISSUE THREAD

**Issue by vishh** [helm/charts#227]
`helm install stable/prometheus` fails on GKE version v1.4.5

```shell
$ k version
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

I probed further and pvc are not being provisioned. 

```shell
$ k describe pvc
Name:		iron-rattlesnake-alerts
Namespace:	default
StorageClass:	standard
Status:		Pending
Volume:		
Labels:		app=iron-rattlesnake-prometh
		chart=prometheus-1.3.1
		component=alertmanager
		heritage=Tiller
		release=iron-rattlesnake
Capacity:	
Access Modes:	
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  4m		8s		19	{persistentvolume-controller }			Warning		ProvisioningFailed	StorageClass "standard" not found


Name:		iron-rattlesnake-server
Namespace:	default
StorageClass:	standard
Status:		Pending
Volume:		
Labels:		app=iron-rattlesnake-prometh
		chart=prometheus-1.3.1
		component=server
		heritage=Tiller
		release=iron-rattlesnake
Capacity:	
Access Modes:	
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  4m		9s		19	{persistentvolume-controller }			Warning		ProvisioningFailed	StorageClass "standard" not found
```

cc @erictune

**Comment by lachie83** [comment]
cc @mgoodness

**Comment by viglesiasce** [comment]
This is because GKE does not currently provide a default storage class. It slipped from the last release but @saad-ali said it shouldnt in the next.

Create a storage class in your namespace and then refer to it here:
https://github.com/kubernetes/charts/blob/master/stable/prometheus/values.yaml#L59
https://github.com/kubernetes/charts/blob/master/stable/prometheus/values.yaml#L171

**Comment by erictune** [comment]
I asked @saad-ali and he said it is not going to be in 1.5.  😠 

So, either charts keep using alpha, or else we have instructions on how to install your own storage class.  This is not hard.  Is there a way to detect a missing prereq before or during chart installation and tell the user to do something out-of-band to correct it?

**Comment by viglesiasce** [comment]
<rant>
BOOOOOOOOOOOOOOOO
</rant>

Okay. The other thing we could do is create a storage class as part of charts although that makes this whole thing a real pain. We could have values that say "createStorageClass: true/false". 

OTOH creating the storage class is a one time operation per namespace so it might be nice to just add something in the notes to have the user ensure that the storage class is created, if not create it.

**Comment by mgoodness** [comment]
I'm not a fan of creating a StorageClass from the chart. They're defined at the cluster level, and we risk stomping on an existing one. Really feels like it's something the operator should do.

**Comment by prydonius** [comment]
See #116, I think we should conditionally switch between the alpha and beta annotation based on if a storage class is provided.

**Comment by seanknox** [comment]
Is this still an issue on GKE?
