### ISSUE TITLE
[stable/jenkins] a typo in file: https://github.com/helm/charts/blob/master/stable/jenkins/templates/_helpers.tpl

### ISSUE THREAD

**Issue by guanwei** [helm/charts#22708]
**Describe the bug**
file: https://github.com/helm/charts/blob/master/stable/jenkins/templates/_helpers.tpl
line: 106
```
 jenkinsUrl: "{{ tpl .Values.master.slaveJenkinsUrl }}"
```

if `master.slaveJenkinsUrl` is not empty, will throw below error:
```
 template: jenkins/templates/_helpers.tpl:106:22: executing \"jenkins.casc.defaults\" at <tpl>: wrong number of args for tpl: want 2 got 1
```

i think need add dot in the expression as below:
```
 jenkinsUrl: "{{ tpl .Values.master.slaveJenkinsUrl . }}"
```

**Comment by drewripa** [comment]
I've got the same error. I have specific infrastructure configuration with external Proxy/Loadbalancer so I need to use slaveJenkinsUrl. @guanwei did you found any workaround?

**Comment by tiagomistral** [comment]
I'm facing the same issue

**Comment by torstenwalter** [comment]
@guanwei Thank you for reporting this. #23176 fixes it.
