### ISSUE TITLE
[stable/prometheus-operator/] Unable to create ingress for grafana 

### ISSUE THREAD

**Issue by dpewsey** [helm/charts#22711]
**Describe the bug**
Getting issues creating grafana ingress 
```helm2.14 install stable/prometheus-operator --name prometheus-operator --namespace prom-test --set alertmanager.enabled=false --set grafana.ingress.enabled=true,ingress.backend.serviceName=prometheus-operator-grafana,ingress.backend.servicePort=80
Error: release prometheus-operator failed: Ingress.extensions "prometheus-operator-grafana" is invalid: spec: Invalid value: []networking.IngressRule(nil): either `backend` or `rules` must be specified
```
**Version of Helm and Kubernetes**:
```Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```
```k version                                                                                                                                        1 ↵
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-21T01:25:41Z", GoVersion:"go1.13.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.15", GitCommit:"8ce551a0c972a9f113e326df0537aa3f1798d93e", GitTreeState:"clean", BuildDate:"2020-05-05T18:38:03Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"} 
```

**Which chart**:
Prometheus-Operator

**What happened**:
When installing the operator with grafana enabled the bug occurs

**What you expected to happen**:
The Ingess for grafana is created

**How to reproduce it** (as minimally and precisely as possible):
`helm install stable/prometheus-operator --name prometheus-operator --namespace prom-test --set alertmanager.enabled=false --set grafana.ingress.enabled=true`

**Anything else we need to know**:

Works perfectly fine for `prometheus.ingress.enabled=true` and can deploy and change service backend to prometheus-operator-grafana which works correct.

**Comment by zzhao2010** [comment]
Hi Dave,
After prometheus.ingress.enabled=true is set to true, what url shall I use to login Prometheus? I still had to use ip and port to login.

This is my custom values.yaml file for overriding the default config. I enabled ingress. 
prometheus:
  ingress:
    enabled: true
  prometheusSpec:
    replicas: 1
    retention: 24h
    image: 
      tag: v2.18.1



zz@ZhangsodMacBook Prometheus-operator % kubectl get po
NAME                                                   READY   STATUS    RESTARTS   AGE
alertmanager-demo-prometheus-operator-alertmanager-0   2/2     Running   1          83m
demo-grafana-78bc94db5-vnsng                           2/2     Running   0          83m
demo-kube-state-metrics-5b9db77dc-5pxv4                1/1     Running   2          83m
demo-prometheus-node-exporter-q6dh9                    1/1     Running   1          83m
demo-prometheus-operator-operator-7fd745b994-sggf5     2/2     Running   0          83m
prometheus-demo-prometheus-operator-prometheus-0       3/3     Running   2          56m



Zhang

**Comment by gleichda** [comment]
I can confirm this issue.
Using GKE
Kubernetes Version:
``` 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-gke.15", GitCommit:"9cabee15e0922c3b36724de4866a98f6c2da5e6a", GitTreeState:"clean", BuildDate:"2020-05-01T21:47:04Z", GoVersion:"go1.13.8b4", Compiler:"gc", Platform:"linux/amd64"}
``` 

Helm Version: 
```
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

From my investigation this seems to be caused by the used Grafana Chart with the ingress.hosts being an empty list. There I can reproduce the same behaviour:

```bash
$ helm install grafana stable/grafana -f grafana.yaml                                                                                               
Error: Ingress.extensions "grafana" is invalid: spec: Invalid value: []networking.IngressRule(nil): either `backend` or `rules` must be specified
```

with grafana.yaml:

```yaml
ingress:
  enabled: true
  hosts: []
```

Which is the default: https://github.com/helm/charts/tree/master/stable/prometheus-operator#grafana
