### ISSUE TITLE
[incubator/druid] Druid using gcs still not work

### ISSUE THREAD

**Issue by rizkyekoputra** [helm/charts#22735]
I have seen in `https://github.com/helm/charts/blob/master/incubator/druid/templates/secrets.yaml` if we enable `gCloudStorage.enabled` than key.json on data will use `.Values.google.gcsAPIKey`... but in`values.yaml` file I cant find this one `google.gcsAPIKey`

**Comment by AWaterColorPen** [comment]
@rizkyekoputra 
you can add `google.gcsAPIKey` into your values by `---set google.gcsAPIKey=balabala`
