### ISSUE TITLE
[stable/nginx-ingress] Cannot create an ALB

### ISSUE THREAD

**Issue by c4urself** [helm/charts#22748]
**Describe the bug**
Cannot create an AWS ALB-type load-balancer with nginx-ingress.

**Version of Helm and Kubernetes**:
3.2.3 and 1.14

**Which chart**:
stable/nginx-ingress

**What happened**:
I alternatively tried using 
nginx-ingress.controller.ingressClass: "alb"
nginx-ingress.controller.service.annotations.kubernetes.io/ingress.class: "alb"
nginx-ingress.controller.service.annotations.service.beta.kubernetes.io/aws-load-balancer-type: "alb

**What you expected to happen**:
A "application" load balancer (ALB) is created instead of a "classic" load balancer (ELB).

**How to reproduce it** (as minimally and precisely as possible):
Use one of the above annotations (whichever is correct) and see that an ALB doesn't get created (but an ELB does in its stead)

**Anything else we need to know**:
The documentation is unclear if this is possible and what annotation should be used. Maybe a small section describing how to use nginx-ingress with ALB // or a section saying that ALBs are not compatible with nginx-ingress would be amazing.

**Comment by venkatalolla** [comment]
I don't think you can create an Nginx ingress controller with ALB load balancer type. Instead, you need to use the alb-ingress-controller which is an incubator project maintained by Kubernetes-sigs [here](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/).

**Comment by scottrigby** [comment]
`stable/nginx-ingress` has been deprecated in favor of the upstream `ingress-nginx` repo. See https://github.com/helm/charts/pull/22823. Issues if still applicable can be re-opened there. Thanks 😊
