### ISSUE TITLE
[incubator/druid] Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"

### ISSUE THREAD

**Issue by asdf2014** [helm/charts#22753]
**Describe the bug**

```bash
$ helm install incubator/druid --version 0.2.0 --generate-name

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
```

**Version of Helm and Kubernetes**:

```bash
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

https://hub.helm.sh/charts/incubator/druid

**What happened**:

Unable to install incubator/druid

**What you expected to happen**:

No error appears when install incubator/druid 

**How to reproduce it** (as minimally and precisely as possible):

```bash
helm install incubator/druid --version 0.2.0 --generate-name
```

**Anything else we need to know**:

None

**Comment by asdf2014** [comment]
@maver1ck @AWaterColorPen PTAL

**Comment by AWaterColorPen** [comment]
What's your kubernetes version?

**Comment by asdf2014** [comment]
@AWaterColorPen v1.16.5

```bash
$ helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by AWaterColorPen** [comment]
https://github.com/kubernetes/website/issues/17396

**Comment by asdf2014** [comment]
@AWaterColorPen Thanks for your comments. But I didn't find any usage of `apps/v1beta2` in the `incubator/druid` chart..

**Comment by AWaterColorPen** [comment]
It seems that the dependency postgresql chart package use the `apps/v1beta2`.

**Comment by maver1ck** [comment]
I think we can add some variables to Postgresql to change this.

**Comment by asdf2014** [comment]
@AWaterColorPen Yep, you are right, we should bump these dependencies to higher version. FYI, I collected these correct versions of these components: 

- Zookeeper: 3.4.14
- MySQL: 5.1.48
- PostgreSQL: 42.2.8

**Comment by maver1ck** [comment]
@AWaterColorPen 
Could you provide PR ? I will accept it.
Maybe you also interested to be one of charts maintainers ?

**Comment by asdf2014** [comment]
@maver1ck Sorry, It was you. :sweat_smile:

**Comment by maver1ck** [comment]
PR please.
I can't lgtm on own PRs.

**Comment by asdf2014** [comment]
@maver1ck @AWaterColorPen That would be nice. I am new to helm and still learn on it. I wish I could help to fix this.

**Comment by AWaterColorPen** [comment]
@asdf2014  @maver1ck  I will PR soon to fix this issue.
