### ISSUE TITLE
[stable/prometheus-operator] JAEGER_AGENT_PORT invalid syntax

### ISSUE THREAD

**Issue by boxcee** [helm/charts#22769]
**Describe the bug**
See report here: https://github.com/prometheus/prometheus/issues/7286.

```
level=error ts=2020-05-23T09:56:29.187Z caller=main.go:508 msg="Unable to init tracing" err="unable to get tracing config from environment: cannot obtain reporter config from env: cannot parse env var JAEGER_AGENT_PORT=udp://10.192.96.169:5775: strconv.ParseInt: parsing \"udp://10.192.96.169:5775\": invalid syntax"
```

**Version of Helm and Kubernetes**:
helm 3.2.1
kubernetes 1.15.9

**Which chart**:
`stable/prometheus-operator`

**What happened**:
Installed latest version of chart and `prometheus-operator` could not start.

**What you expected to happen**:
No problems with startup after upgrading to latest chart.

**How to reproduce it** (as minimally and precisely as possible):
Install `jaegertracing/jaeger` with name `jaeger`. Then install latest `stable/prometheus-operator`. Log startup of `prometheus-operator`.

**Anything else we need to know**:
Seems to be a bug with `jaeger`, but it would be nice to have an option to disable the `jaeger` tracing then.

**Comment by sharkymcdongles** [comment]
Problem is related to jaeger injecting envrionment variables into the prometheus pod.

https://github.com/prometheus/prometheus/issues/7286

It is fixable by adding this to values:

```yaml
prometheusSpec:
        containers:
        - name: prometheus
          env:
          - name: JAEGER_AGENT_PORT
            value: "5755"  
```
