### ISSUE TITLE
[stable/spinnaker] Do not expect volume mount for kubeconfig when using encrypted s3 bucket

### ISSUE THREAD

**Issue by Karthik-13** [helm/charts#22765]
**Describe the bug**
When installing the spinnaker helm chart with kubeconfig configured to use encrypted s3 bucket, the halyard pod fails still expecting the kubeconfig as kubernetes secret

> MountVolume.SetUp failed for volume "kube-config" : secret "my-kubeconfig" not found

Helm Version: v3.0.2
Kubernetes version: v1.15.11

Chart: stable/spinnaker

**What happened**:
When choosing kubeconfig source as encrypted s3 bucket, the spinnaker installation fails expecting the kubernetes secret for kubeconfig

**What you expected to happen**:
The spinnaker installation should use the s3 bucket to fetch kubeconfig and not expect k8s secret to provide the configuration

**How to reproduce it** (as minimally and precisely as possible):
Add the following kubeconfig configuration to values yaml and install the spinnaker helm chart. 

```
kubeConfig:
  enabled: true
  encryptedKubeconfig: encrypted:s3!r:us-east-1!b:mybucket!f:kubeconfig
```

**Anything else we need to know**:
This is due to an issue in the helm template which only checks `.Values.kubeConfig.enabled` to identify the source for kubeconfig as k8s secret. It should also check `.Values.kubeConfig.secretName` and this value should not be provided by default.

**Comment by owenmonagan** [comment]
experiencing this issue
