### ISSUE TITLE
[stable/jenkins] Jenkins not responding when setting serviceType: LoadBalancer

### ISSUE THREAD

**Issue by laurentgrangeau** [helm/charts#22779]
**Describe the bug**
When setting the serviceType as LoadBalancer, Jenkins isn't responding anymore. When looking at logs, jenkins-sc-config is getting an error : 
POST request sent to http://localhost:8080/reload-configuration-as-code/?casc-reload-token=jenkins-1592059639-86d74678b5-km2qh. Response: 500 Server Error

**Version of Helm and Kubernetes**:
kubectl :
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-gke.15", GitCommit:"9cabee15e0922c3b36724de4866a98f6c2da5e6a", GitTreeState:"clean", BuildDate:"2020-05-01T21:47:04Z", GoVersion:"go1.13.8b4", Compiler:"gc", Platform:"linux/amd64"}

helm : 
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}

**Which chart**:
jenkins-2.0.1

**What happened**:
I have set serviceType: LoadBalancer in the master section and I can't access it with the LoadBalancer public IP

**What you expected to happen**:
Have access to Jenkins admin page

**How to reproduce it** (as minimally and precisely as possible):
Setup the serviceType as LoadBalancer, install the helm chart on GKE

**Anything else we need to know**:

**Comment by tbutkiewicz** [comment]
Adding that I'm getting the same exact error on AWS EKS using `aws-alb-ingress-controller` and `serviceType: NodePort`.

Everything else works as intended other than the auto reload of casc configs (500 error), currently working around this by disabling the sidecar entirely via:
```
    sidecars:
      configAutoReload:
        enabled: false
```

**Comment by torstenwalter** [comment]
Which versions of the configuration as code plugin are you using?

**Comment by olawaleadenagbe** [comment]
We also have the same issue and I found that it's because the sidecar container has the wrong value set for `REQ_URL` in `jenkins-master-deployment.yaml`.

```
            - name: REQ_URL
              value: "http://localhost:8080{{- .Values.master.jenkinsUriPrefix -}}/reload-configuration-as-code/?casc-reload-token=$(POD_NAME)"
```
It works if `localhost` is replaced with the name of the Service for the Jenkins deployment. I believe the template at https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml need to be changed to reflect this.
