### ISSUE TITLE
[stable/minio] Readiness probe failed in distributed mode with TLS enabled

### ISSUE THREAD

**Issue by yap-studios** [helm/charts#22777]
**Describe the bug**
Minio in standalone mode with TLS enabled runs fine. As soon as I enable distributed mode, I get the following:

```
Warning   Unhealthy   pod/minio-0 Readiness probe failed: HTTP probe failed with status code: 503
```

**Version of Helm and Kubernetes**:
Helm v3 and Kubernetes v1.16.9

**Which chart**:
Version 5.0.26

**What happened**:
I enabled TLS in distributed mode.

**What you expected to happen**:
I don't expect readiness checks to be performed in distributed mode as per the following documentation:
https://docs.min.io/docs/deploy-minio-on-kubernetes.html

```
Note : Readiness check is not allowed in distributed MinIO deployment. This is because Kubernetes doesn't allow any traffic to containers whose Readiness checks fail, and in a distributed setup, MinIO server can't respond to Readiness checks until all the nodes are reachable. So, Liveness checks are recommended native Kubernetes monitoring approach for distributed MinIO StatefulSets.
```

Unless the warning is for something else entirely.

**How to reproduce it** (as minimally and precisely as possible):
```
helm install minio \
--set mode=distributed \
--set tls.enabled=true \
--set tls.certSecret=secret-minio-prod-tls \
--set tls.publicCrt=tls.crt \
--set tls.privateKey=tls.key \
stable/minio
```

**Anything else we need to know**:
This works:
```
single mode + no tls
```
```
single mode + tls enabled
```
```
distributed mode + no tls
```
This does not work:
```
distributed + tls enabled
```
I'm using cert-manager for the certificates.

**Comment by TreeKat71** [comment]
Hi yap-studios,
That note about readiness probe is quite confusing. But I am fine to deploy in distributed + tls enabled. 
Could you provide more information about your tls setting?

**Comment by yap-studios** [comment]
Hi @TreeKat71,

Yes I found it very confusing. In addition to the above settings, I have the following tls settings:

```
--set ingress.tls[0].secretName=secret-minio-prod-tls \
--set ingress.tls[0].hosts[0]=www.example.com \
--set ingress.tls[0].hosts[1]=example.com\
--set ingress.annotations.nginx.ingress.kubernetes.io/backend-protocol=HTTPS \
--set ingress.annotations.nginx.ingress.kubernetes.io/secure-backends=true \
--set ingress.annotations.kubernetes.io/tls-acme=true \
--set ingress.annotations.cert-manager.io/issuer=letsencrypt-prod-minio\
```
These are all the tls settings I have. Am I missing something?
If you don't mind, could you please share your tls settings as well so I see where I'm going wrong? Thanks.
