### ISSUE TITLE
[stable/airflow] Google Cloud Platform Credentials Error

### ISSUE THREAD

**Issue by AETDDraper** [helm/charts#22772]
Hi Currently getting the following error in airflow using airflow HELM.

Any ideas on this?

```The private_key argument is deprecated. Construct a credentials object, instead, by using the google.oauth2.service_account.Credentials.from_service_account_file or google.oauth2.service_account.Credentials.from_service_account_info class method from the google-auth package.```

**Comment by thesuperzapper** [comment]
This is not related to the airflow chart.
