### ISSUE TITLE
[stable/airflow] SMTP User and Password

### ISSUE THREAD

**Issue by AETDDraper** [helm/charts#22780]
currently getting this error on lastest stable/airflow 

WARNING - section/key [smtp/smtp_user] not found in config

I've added the following to the values.yaml file. any ideas how I can get this working? 

     AIRFLOW__EMAIL__EMAIL_BACKEND: "airflow.utils.email.send_email_smtp"
     AIRFLOW__SMTP__SMTP_HOST: "smtp.gmail.com"
     AIRFLOW__SMTP__SMTP_STARTTLS: "True"
     AIRFLOW__SMTP__SMTP_SSL: "False"
     AIRFLOW__SMTP__SMTP_PORT: "587"
     AIRFLOW__SMTP__SMTP_MAIL_USER: "email@google.com"
     AIRFLOW__SMTP__SMTP_MAIL_PASSWORD: "xxxx"
     AIRFLOW__SMTP__SMTP_MAIL_FROM: "email.google.com"

**Comment by thesuperzapper** [comment]
This is not the place to ask for Airflow help.

I recommend getting stuff working locally before trying to introduce Kubernetes, as it is clearly causing you some trouble (given how many issues you have raised recently).

---

But for this one time, I will help you:

That's a warning, not an error, you probably need to specify `AIRFLOW__SMTP__SMTP_USER`.
