### ISSUE TITLE
prometheus blackbox exporter cannot works well when mtls enabled.

### ISSUE THREAD

**Issue by johnzheng1975** [helm/charts#22796]
**Describe the bug**
prometheus blackbox exporter cannot works well when mtls enabled.

 I enabled istio mtls. However, something wrong with my prometheus blackbox exporter, since my prometheus is in monitoring namespace which is not istio-injected.  Any suggestion for this? Should I istio inject monitoring namespace? Or best practice? Thanks! 

**Version of Helm and Kubernetes**:
helm2
k8s 1.5

**Comment by johnzheng1975** [comment]
After investigation, the best practice is:
Using prometheus outside the mesh, assign k8s secect with certs, let it can access the istio mesh.
Latest Prometheus operator already support this.

**Comment by jorotg** [comment]
John, just curios how do use that k8s secret and why? Prometheus operator is deprecated for quite some time now. Do you mean Prometheus community helm chart https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus ?
