### ISSUE TITLE
Not able to deploy grafana using latest helm charts.

### ISSUE THREAD

**Issue by udaymadu** [helm/charts#22826]
**Describe the bug**

**Version of Helm and Kubernetes**: version.BuildInfo{Version:"v3.0.2",

**Which chart**:helm grafna

**What happened**: while deploying new helm charts, getting template error 

coalesce.go:196: warning: cannot overwrite table with non table for image (map[repository:kiwigrid/k8s-sidecar tag:0.1.151])
 Error: template: grafana/templates/deployment.yaml:43:10: executing "grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error calling include: template: grafana/templates/_pod.tpl:99:22: executing "grafana.pod" at <.Values.sidecar.image.repository>: can't evaluate field repository in type interface {}

**What you expected to happen**:
    
should deploy successfully in k8s

**How to reproduce it** (as minimally and precisely as possible):

download latest helm charts from github and try to deploy to k8s using helm install

**Anything else we need to know**:

**Comment by udaymadu** [comment]
added custom values and started working

**Comment by mburke-rockstar** [comment]
where did you add the custom values?

**Comment by udaymadu** [comment]
Please try to change sidecar container configuration as per template in your values file. or take values file and change as per req and deploy it.

**Comment by kartik-moolya** [comment]
> Please try to change sidecar container configuration as per template in your values file. or take values file and change as per req and deploy it.

Hey, I' struggling to figure this out. Could you show me where exactly have you used the custom value. I'm currently using this deprecated chart (8.15.1) and keep getting this error
