### ISSUE TITLE
[stable/rabbitmq-ha]  unable to upgrade chart from 1.45.0 to 1.46.0 - nil pointer evaluating interface {}.annotations

### ISSUE THREAD

**Issue by lancez77** [helm/charts#22833]
helm upgrade --set rabbitmqErlangCookie=$ERLANGCOOKIE  rabbitmq-ha stable/rabbitmq-ha --reuse-values  --version 1.46.0  

Error: UPGRADE FAILED: template: rabbitmq-ha/templates/service-discovery.yaml:4:14: executing "rabbitmq-ha/templates/service-discovery.yaml" at <.Values.service.discovery.annotations>: nil pointer evaluating interface {}.annotations

There's new attributes in v1.46.0

  discovery:
    separateAnnotations: false
    annotations: {}

If we try to add the new attributes, we will get an error like
"Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"

What must we do to successfully update the chart from 1.45 to 1.46.x ?

**Comment by steven-sheehy** [comment]
Not enough info. Try installing the helm diff plugin to see what's being changed and ensure nothing in statefulset is changing besides those fields.
