### ISSUE TITLE
[stable/kube-state-metrics] config option changed to namespaces

### ISSUE THREAD

**Issue by KlavsKlavsen** [helm/charts#22840]
**Describe the bug**
According to git - option --namespace was changed to be: namespaces back in march.
https://github.com/kubernetes/kube-state-metrics/blob/master/docs/cli-arguments.md

This chart still uses --namespace, which is wrong.

**Which chart**:
stable/kube-state-metrics

**Comment by mrueg** [comment]
This is currently only in the project's master and not in the 1.9 branch which the current releases are from.
Once kube-state-metrics 2.0 is released, we will update it. See also: https://github.com/kubernetes/kube-state-metrics/blob/release-1.9/docs/cli-arguments.md
