### ISSUE TITLE
[stable/airflow] In kubernetes mode the following must be set in the `kubernetes` config section: `dags_volume_claim

### ISSUE THREAD

**Issue by KIRY4** [helm/charts#22848]
**Describe the bug**

**Version of Helm and Kubernetes**:
Helm 3.0, AKS 1.16.7

**Which chart**:
stable/airflow

**What happened**:
airflow.exceptions.AirflowConfigException: In kubernetes mode the following must be set in the `kubernetes` config section: `dags_volume_claim` or `dags_volume_host` or `dags_in_image` or `git_repo and git_branch and git_dags_folder_mount_point`

**What you expected to happen**:
I want to use KubernetesExecutor

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
Here is my values.yaml:
---
airflow:
  executor: KubernetesExecutor

workers:
  enabled: false

flower:
  enabled: false

  config:
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: apache/airflow
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: 1.10.10-python3.6
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: IfNotPresent
    AIRFLOW__KUBERNETES__WORKER_PODS_CREATION_BATCH_SIZE: 10
    AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: airflow
    AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: airflowdags-pvc
    AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: airflowlogs-pvc
    AIRFLOW__KUBERNETES__NAMESPACE: airflow
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: True
    AIRFLOW__CORE__LOAD_EXAMPLES: True

scheduler:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
              - toolset
  
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "toolset"
    effect: "NoSchedule"

web:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
              - toolset
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "toolset"
    effect: "NoSchedule"

logs:
  path: /opt/airflow/logs
  persistence:
    enabled: true
    existingClaim: airflowlogs-pvc
    accessMode: ReadWriteMany
    size: 10Gi

dags:
  path: /opt/airflow/dags
  persistence:
    enabled: true
    existingClaim: airflowdags-pvc
    accessMode: ReadWriteMany
    size: 10Gi

k get pvc -n airflow                                                                                 
NAME                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
airflowdags-pvc             Bound    airflowdags-pv                             10Gi       RWX                           148m
airflowlogs-pvc             Bound    airflowlogs-pv                             10Gi       RWX                           148m

**Comment by deltawi** [comment]
I am having the same issue by changing CeleryExecutor to KubernetesExecutor.

**Comment by mrafayaleem** [comment]
Exactly the same issue. What's the resolution for this?

**Comment by KIRY4** [comment]
Hey guys @deltawi @mrafayaleem honestly I can't remember what exactly I changed but I can provide my whole values.yaml which working for me!! Only one thing I switched from fileshare for dags to gitsync but I think you can disable gitsync and enable fileshare for dags. 
`airflow:
  ## configs for the docker image of the web/scheduler/worker
  ##
  image:
    repository: apache/airflow
    tag: 1.10.10-python3.6
    ## values: Always or IfNotPresent
    pullPolicy: IfNotPresent
    pullSecret: ""
  executor: KubernetesExecutor

  config:
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "1.10.10-python3.6"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: "IfNotPresent"
      AIRFLOW__KUBERNETES__WORKER_PODS_CREATION_BATCH_SIZE: "10"
      # AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: "airflowdags-pvc"
      AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: "airflowlogs-pvc"
      AIRFLOW__KUBERNETES__GIT_REPO: "git@git.my.repo.com"
      AIRFLOW__KUBERNETES__GIT_BRANCH: "master"
      AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "/opt/airflow/dags"
      AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: "repo/"
      AIRFLOW__KUBERNETES__GIT_SSH_KEY_SECRET_NAME: "airflow-gitsync"
      AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
      AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
      AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"
      AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: "airflow"

  extraEnv:
    - name: AIRFLOW__KUBERNETES__TOLERATIONS
      valueFrom:
        configMapKeyRef:
          name: airflow-configmap
          key: k8spodstolerations
    - name: AIRFLOW__KUBERNETES__AFFINITY
      valueFrom:
        configMapKeyRef:
          name: airflow-configmap
          key: k8spodsaffinity

scheduler:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
              - tools

  tolerations:
  - key: "type"
    operator: "Equal"
    value: "tools"
    effect: "NoSchedule"

web:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
              - tools

  tolerations:
  - key: "type"
    operator: "Equal"
    value: "tools"
    effect: "NoSchedule"

logs:
  path: /opt/airflow/logs
  persistence:
    enabled: true
    existingClaim: airflowlogs-pvc
    accessMode: ReadWriteMany
    size: 10Gi

dags:
  path: /opt/airflow/dags
  persistence:
    enabled: false
    existingClaim: airflowdags-pvc
    accessMode: ReadWriteMany
    size: 10Gi

  git:
    url: "git@git.mgmt.ocp.bawag.com:ocp/aks/templates/general-cluster/airflow-dags.git"
    ref: master
    secret: "airflow-gitsync"
    sshKeyscan: true
    privateKeyName: id_rsa
    repoHost: "git@git.my.repo.com"
    repoPort: 22
    gitSync:
      enabled: true
      resources: {}
      image:
        repository: alpine/git
        tag: latest
        pullPolicy: Always
      refreshTime: 60
  initContainer:
    enabled: true
    resources: {}
    image:
      repository: alpine/git
      tag: latest
      pullPolicy: Always
    mountPath: "/opt/airflow/dags"
    syncSubPath: ""

ingress:
  enabled: true
  web:
    annotations:
      kubernetes.io/ingress.class: nginx
    path: ""
    host: myhost.com
    tls:
      enabled: false

rbac:
  create: true

serviceAccount:
  create: true
  name: airflow

postgresql:
  enabled: true
  postgresqlDatabase: myairflowuser
  postgresqlUsername: mypostgresdb
  postgresqlPassword: myairflowuser
  persistence:
    enabled: true
    storageClass: "default"
    accessModes:
      - ReadWriteOnce
    size: 8Gi

redis:
  enabled: true < ---------- Should be false but chart crashing during deployment. So I was forced to stay with true.

workers:
  enabled: false

flower:
  enabled: false
`

**Comment by mrafayaleem** [comment]
I set `AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"` and that resolved it for me.
