### ISSUE TITLE
[stable/rabbitmq-ha] How to install / where is this repo going to live

### ISSUE THREAD

**Issue by pmorelli92** [helm/charts#22855]
**Describe the bug**

```
helm install rb stable/rabbitmq-ha
Error: failed to download "stable/rabbitmq-ha" (hint: running `helm repo update` may help)
```

**Version of Helm and Kubernetes**:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

`stable/rabbitmq-ha`

**What happened**:

I cannot find a repository that points to a dedicate site where this chart should live.

**What you expected to happen**:

Contributors to align on where to put this chart for helm 3.X users to be able to use it.

**How to reproduce it** (as minimally and precisely as possible):

```
(having helm 3.2)
helm install rb stable/rabbitmq-ha
```

**Comment by pmorelli92** [comment]
@steven-sheehy may I have your input please?

**Comment by steven-sheehy** [comment]
In Helm 3 I believe the stable repository is no longer is added by default, so you just need to add it then your helm install command should work:
```
helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm install rb stable/rabbitmq-ha
```

There is no dedicated site for rabbitmq-ha, it lives in helm/charts repo. After this repo is deprecated I would suggest you transition your deployments to the Bitnami supported [RabbitMQ chart](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq).

**Comment by pmorelli92** [comment]
Thanks a lot for the information!
