### ISSUE TITLE
[stable/jenkins] support remote jcasc files for configAutoReload

### ISSUE THREAD

**Issue by techlunacy** [helm/charts#22853]
I would like the configAutoReload structure to support a URL for the jcasc configuration,
currently it does not.

i cannot use a remote configuration and enable config auto reload

Setting the folder to a url breaks because it tries to mount it as a file

**Comment by torstenwalter** [comment]
How could we tell if the content for a remote URL changed? auto reload works by watching for ConfigMap changes. If you point to a remote URL then there is no ConfigMap which would trigger that changed.

**Comment by techlunacy** [comment]
i don't really have a answer for that one. maybe some sort of cron?
