### ISSUE TITLE
Prometheus StatsD exporter chart is gone. cannot find removal in commits

### ISSUE THREAD

**Issue by iftachsc** [helm/charts#22887]
**Is your feature request related to a problem? Please describe.**
we are in the middle of a project using the chart of prometheus statsd exporter. and all of a sudden its gone from the stable repo.

**Describe the solution you'd like**
we want it back or understand if there is a good reason its gone e.g. not maintained anymore.

**Describe alternatives you've considered**
Create our own chart? we rather not.

**Additional context**

**Comment by eladRabinovich** [comment]
+1
