### ISSUE TITLE
[stable/prometheus-operator] python sync scripts are missing latest namespace configuration update

### ISSUE THREAD

**Issue by den-is** [helm/charts#22892]
**Describe the bug**
The recent addition of namespace override by https://github.com/helm/charts/pull/22288 conceals a threat!
The next sync of rules with upstream will override that change.

Apparently, reviewers/owners have missed the fact that all those files were edited manually, instead of using provided scripts in the hack directory.

Here https://github.com/helm/charts/blob/88a5176022e8dda60a498d2b8953a9feb3d13b0b/stable/prometheus-operator/hack/sync_prometheus_rules.py#L123-L148

Namespace is declared the old way https://github.com/helm/charts/blob/88a5176022e8dda60a498d2b8953a9feb3d13b0b/stable/prometheus-operator/hack/sync_prometheus_rules.py#L135

Same for grafana dashboards.

**Which chart**:
stable/prometheus-operator

**What happened**:
Not what happened, but what will happen ...

**What you expected to happen**:
New Namespace declaration should be depicted in python scripts and rules generated using them, but not manually.

**Comment by yoninl2** [comment]
I updated the hack scripts, didn't aware that some files are generated from them, I also noticed some rules are updated after I re-run the scripts, please feel free to update them or ask me to update my PR to include that if it's necessary, thanks.

**Comment by den-is** [comment]
fixed via https://github.com/helm/charts/pull/23325
