### ISSUE TITLE
[stable/airflow] not able to use RBAC with Azure OAuth

### ISSUE THREAD

**Issue by sk2991** [helm/charts#22904]
I'm working on enbaling RBAC for airflow using OAuth.I was able to get to my Organization sso page. After i provide my credentials - it redirects me to Airflow login UI stating invalid login. I have tried using custom application Oauth and Azure OAuth
config used in webserver_config.py
import os
    from airflow.configuration import conf
    from flask_appbuilder.security.manager import AUTH_OAUTH
    basedir = os.path.abspath(os.path.dirname(_file_))
    SQLALCHEMY_DATABASE_URI = conf.get("core", "SQL_ALCHEMY_CONN")
    CSRF_ENABLED = True
    AUTH_TYPE = AUTH_OAUTH
    AUTH_USER_REGISTRATION_ROLE = "Admin"
    OAUTH_PROVIDERS = [
    {
        "name": "azure",
        "icon": "fa-windows",
        "token_key": "access_token",
        "remote_app": {
            "consumer_key": "",
            "consumer_secret": "",
            "base_url": "https://login.microsoftonline.com/{TENANT_ID}oauth2",
            "request_token_params": {
                "scope": "User.read name preferred_username email profile",
                "resource": "",
            },
            "request_token_url": None,
            "access_token_url": "https://login.microsoftonline.com/{TENANT_ID}/oauth2/token",
            "authorize_url": "https://login.microsoftonline.com/{TENANT_ID}/oauth2/authorize",
        },
    },
    ]

**Comment by dchen71** [comment]
I was wondering if you had more information about this method and what you did to fix it. I am looking to Airflow RBAC and Azure OAuth could be a good solution for me but I am also looking into Github Enterprise authentification module as an alternative. With flask, are you additionally able to pull AD groups using Azure OAuth? For instance, only people with a specific AD group can access Airflow or everyone in a specific group are all admins by default.

**Comment by sk2991** [comment]
I was able to get the Authentication piece of it working. I was not able to get any info/documentation on how to implement Authorization using AD groups.
