### ISSUE TITLE
[stable/prometheus_operator] alertmanager does not support volumes/volumeMounts

### ISSUE THREAD

**Issue by BryanEllington** [helm/charts#22939]
**Describe the bug**
alertmanager does not support volumes or volumeMounts as prometheus does even though both AlertManagerSpec contains volumes/volumeMounts. The prometheus part of the chart supports volumes/volumeMounts (see https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L242)

**Version of Helm and Kubernetes**:
Neither version matters. Issue with missing functionality in the chart.

**Which chart**:
stable/prometheus_operator
Specifically here: https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/alertmanager/alertmanager.yaml

**What happened**:
volumes specified under alertmanagerSpec were not added to the alertmanager resource which caused an error when the prometheus operator created the pod from the faulty alertmanager resource.

Specifically, the error seen was:
`Warning   FailedCreate   statefulset/alertmanager-prometheus-operator-alertmanager   create Pod alertmanager-prometheus-operator-alertmanager-0 in StatefulSet alertmanager-prometheus-operator-alertmanager failed error: Pod "alertmanager-prometheus-operator-alertmanager-0" is invalid: spec.containers[2].volumeMounts[0].name: Not found: "tls-proxy-secret"`

tls-proxy-secret here was specified as a volume under alertmanagerSpec. The same definition worked under prometheusSpec. The CRDs are similar, but volumes/volumeMounts are simply not supported for alertmanager by this chart.

AlertManagerSpec CRD:
https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec

**What you expected to happen**:
The chart should honor volumes/volumeMounts under alertmanagerSpec

**How to reproduce it** (as minimally and precisely as possible):
Specify any volume under alertmanagerSpec

**Anything else we need to know**:
Solution should be as simple as adding a similar section to 'volumes' and 'volumeMounts' section from https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L242

**Comment by BryanEllington** [comment]
I don't have an update other than to ask for an acknowledgment that this is a valid issue. Should I just go ahead and create a pull request?

**Comment by BryanEllington** [comment]
Fixed in https://github.com/helm/charts/pull/23047. Closing.

**Comment by BryanEllington** [comment]
Reopening issue. The fix in [#23047](https://github.com/helm/charts/pull/23047) does not appear to be correct.

When volumes/volumeMounts are specified, you get:

Error: UPGRADE FAILED: YAML parse error on prometheus-operator/templates/alertmanager/alertmanager.yaml: error converting YAML to JSON: yaml: line 71: did not find expected ',' or ']'

One fix is to put the values on the next line:

**Before** (https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/alertmanager/alertmanager.yaml#L110):

`{{- if .Values.alertmanager.alertmanagerSpec.volumes }}
  volumes: {{.Values.alertmanager.alertmanagerSpec.volumes }}
{{- end }}
{{- if .Values.alertmanager.alertmanagerSpec.volumeMounts }}
  volumeMounts: {{.Values.alertmanager.alertmanagerSpec.volumeMounts }}
{{- end }}`

**After**
`{{- if .Values.alertmanager.alertmanagerSpec.volumes }}
  volumes:
{{ toYaml .Values.alertmanager.alertmanagerSpec.volumes | indent 4 }}
{{- end }}
{{- if .Values.alertmanager.alertmanagerSpec.volumeMounts }}
  volumeMounts:
{{ toYaml .Values.alertmanager.alertmanagerSpec.volumeMounts | indent 4 }}
{{- end }}`

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated in the `stable` repo.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
