### ISSUE TITLE
[stable/jenkins] Chart does not support Traefik 2.x IngressRoute 

### ISSUE THREAD

**Issue by peterloron** [helm/charts#22940]
As of version 2.0.1, the chart allows for enabling an ingress resource. However, this is not compatible with the current (>= 2.0) Traefik IngressRoute resource. Please fix this...Traefik 2 has been out for a long time.

**Comment by torstenwalter** [comment]
@peterloron Can you be more specific here? Could you create PR which adds the functionality you would like to see.

**Comment by peterloron** [comment]
Yeah, I should have done that originally. Let me take a poke at it. Thanks.
