### ISSUE TITLE
[stable/jenkins] Different serviceAccount for additionalAgents

### ISSUE THREAD

**Issue by arogarth** [helm/charts#22957]
The jenkins chart provides to define additional agents - but it is not possible to define a seriveAccount for it...

The template helper alwas redered the value .Values.serviceAccountAgent but only overrides .Values.agent - there is no way to override the used service-account for some agent.

Use case:
I want use diffenrent podTemplates for different jobs - such as deploy as default pod Template - but some jobs must have another service-account with higher privileges in the cluster.

**Comment by torstenwalter** [comment]
Did you try `additionalAgents` to configure agents? Via `agent.yamlTemplate` zou should be able to configure anything you can do in plain Kubernetes.
