### ISSUE TITLE
istio helm chart: can we delete the confusing old versions

### ISSUE THREAD

**Issue by ldemailly** [helm/charts#2297]
**Is this a request for help?**:
sort of

**Which chart**:
incubator/istio

**What happened**:
https://kubeapps.com/charts/incubator/istio/
shows a lot of versions that need to be deleted (everything > 0.1.6)
leaving 0.1.6-chart6 as the latest/top one

**What you expected to happen**:
not seeing 0.3.0 or 0.1.7 or 0.2.6...

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
is it possible to delete/hide those other versions ?

**Comment by ldemailly** [comment]
this is related to https://github.com/kubernetes/charts/issues/1501

**Comment by lachie83** [comment]
@viglesiasce is there anyway we can nuke the old versions under the current repo?

**Comment by viglesiasce** [comment]
There is no automated process afaik but I can try to figure it out today.

**Comment by viglesiasce** [comment]
Should be fixed now pending the flush of any caches.

**Comment by ldemailly** [comment]
thanks so much Vic !

**Comment by lachie83** [comment]
Thanks Vic
