### ISSUE TITLE
[stable/grafana] Add image renderer container as chart option

### ISSUE THREAD

**Issue by via-jordan-sokolic** [helm/charts#22979]
**Is your feature request related to a problem? Please describe.**
Image rendering is now handled by an external container in Grafana 7.0. Listing the `grafana-image-renderer` plugin under the `plugins` directive in the current chart results in a crash loop with the following log output:
```
t=2020-06-28T11:23:27+0000 lvl=eror msg="A service failed" logger=server err="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
```

Issue links: 
* https://github.com/grafana/grafana/issues/25180
* https://github.com/helm/charts/issues/21959

**Describe the solution you'd like**
A chart option to easily enable the image renderer sidecar container as describe in https://grafana.com/blog/2020/05/07/grafana-7.0-preview-new-image-renderer-plugin-to-replace-phantomjs/ which embeds the solution below into the chart. Something like `sidecar.imageRenderer.enabled: true`

**Describe alternatives you've considered**
Currently using the solution outlined below.

**Additional context**

> In case someone else is stumbling across this and needs a quickfix with the current chart:
> 
> ```
>     extraContainers: |
>       - name: renderer
>         image: grafana/grafana-image-renderer:latest
> 
>     env:
>       GF_RENDERING_SERVER_URL: http://localhost:8081/render
>       GF_RENDERING_CALLBACK_URL: http://localhost:3000/
> 
> ```
> 
> _Originally posted by @languitar in https://github.com/helm/charts/issues/21959#issuecomment-640653320_

**Comment by attackercan** [comment]
Bumping issue
