### ISSUE TITLE
[stable/sealed-secrets] Should use same default Service name as the official non-helm installation.

### ISSUE THREAD

**Issue by rally25rs** [helm/charts#22996]
**Describe the bug**

The chart defaults the `Service` name to:

https://github.com/helm/charts/blob/master/stable/sealed-secrets/templates/service.yaml#L5
```
name: {{ template "sealed-secrets.fullname" . }}
```

Which is

```
{{- define "sealed-secrets.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

Which by default will use the `.Chart.Name`, which is `sealed-secrets`, which is wrong. The client tool `kubeseal` looks for `sealed-secrets-controller`

-----

As a workaround for those that get here from a search, you should be able to use the `kubeseal --controller-name` parameter.

```
$ kubeseal <secrets.yaml >sealedsecrets.yaml --controller-name sealed-secrets
```

**Version of Helm and Kubernetes**:

**Which chart**:

`stable/sealed-secrets`

**What happened**:

Service is named `sealed-secrets` which is not the same as the default `sealed-secrets-controller` for the non-helm method of installation, and is not what the cli tool `kubeseal` uses by default.

**What you expected to happen**:

Service to be named `sealed-secrets-controller` as is the default for the official non-helm installation:
```
kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.12.4/controller.yaml
```
That `controller.yaml` sets the Service name to `sealed-secrets-controller`

**How to reproduce it** (as minimally and precisely as possible):

helm install the chart with default values, then try to use`kubeseal` cli tool against it.

**Comment by VihanAgarwal97** [comment]
I was just hit by this. Thanks for the workaround!
