### ISSUE TITLE
[stable/rabbitmq-ha] Image upgrade not working with latest charts.

### ISSUE THREAD

**Issue by rahulsadanandan** [helm/charts#22993]
**Describe the bug**
image upgrade is not working with the charts

**Version of Helm and Kubernetes**:
helm Version:"v3.2.1"
k8 version - v1.14.9-eks-f459c0

**Which chart**:
rabbitmq-ha-1.46.4

**What happened**:
Image version not getting updated 

**What you expected to happen**:
Chart should get updated with latest image

**How to reproduce it** (as minimally and precisely as possible):
Install chart with old image version
`helm upgrade --install rha1 -n art --set image.tag=3.7.21-alpine --set rabbitmqErlangCookie=MykgcjnarEJSeVxx8of0Qi3GIC1CVMva --set prometheus.operator.enabled=false stable/rabbitmq-ha`
and then upgrade to new image version
`helm3 upgrade --install rha1 -n art --set image.tag=3.8.5-alpine --set rabbitmqErlangCookie=MykgcjnarEJSeVxx8of0Qi3GIC1CVMva --set prometheus.operator.enabled=false stable/rabbitmq-ha`

**Anything else we need to know**:
No.

**Comment by chukka** [comment]
Tagging @steven-sheehy  :)

**Comment by chukka** [comment]
@steven-sheehy  Any updates ?

**Comment by rahulsadanandan** [comment]
@steven-sheehy , any updates regarding this?

**Comment by steven-sheehy** [comment]
This chart has been deprecated and is no longer maintained. It is recommended to use the Bitnami maintained [RabbitMQ chart](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq) which has a similar feature set, including high availability. See #23746 and #21103. Can you please close. Thanks!
