### ISSUE TITLE
[stable/mysql] Not possible to specify an AKS-valid PVC name due to regex validation

### ISSUE THREAD

**Issue by GimmeDaKitty** [helm/charts#23010]
**Describe the bug**
I cannot specify a Persistent Volume Claim name that is acceptable for Azure (see here for the list of valid storage classes: https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-disk

**Version of Helm and Kubernetes**:
Helm version:
```
Client: v2.9.1+g20adb27
Server: v2.15.1+gcf1de4f
```

Kubernets version:
```
Client Version: v1.14.3
Server Version: v1.11.10
```

**Which chart**:
stable/mysql

**What happened**:
Trying to install mysql helm chart on AKS cluster with this command:

```
helm install --name somename-mysql --namespace default --set mysqlDatabase=somename-database,livenessProbe.initialDelaySeconds=60,livenessProbe.periodSeconds=60,persistence.enabled=true,**persistence.storageClass=Standard_LRS** stable/mysql
```

The following validation error appears:
_Error: release somename-mysql failed: PersistentVolumeClaim "somename-mysql" is invalid: spec.storageClassName: Invalid value: "Standard_LRS": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')_

**What you expected to happen**:
PVC is created

**How to reproduce it** (as minimally and precisely as possible):
Run install command mentioned above above on an Azure Kubernetes Cluster

**Anything else we need to know**:
When I install the chart with default value for `persistence.storageclass` (default), PVC cannot be created due to this error:
```
Events:
  Type       Reason              Age               From                         Message
  ----       ------              ----              ----                         -------
  Warning    ProvisioningFailed  1s (x4 over 46s)  persistentvolume-controller  Failed to provision volume with StorageClass "default": azureDisk - StandardSSD_LRS is not supported sku/storageaccounttype. Supported values are [Premium_LRS Standard_GRS Standard_LRS Standard_RAGRS]
Mounted By:  somename-mysql-967b9c54f-zkf2f
```

**Comment by bdelsaz** [comment]
Turned out this is not a helm chart problem. 
AKS cluster version  `1.11.10` is deployed with already 'predefined' storage classes as shown with `kubectl get storageclasses`:
```
azurefile           kubernetes.io/azure-file   94d
azurefile-premium   kubernetes.io/azure-file   94d
default (default)   kubernetes.io/azure-disk   19h
managed-premium     kubernetes.io/azure-disk   19h
```
'default' (the default value of the helm chart) exists, but it gives an error. I think this is more a problem of AKS.
Will close this issue
