### ISSUE TITLE
[stable/jenkins] chart YAML parse error

### ISSUE THREAD

**Issue by zsjohny** [helm/charts#23078]
**Describe the bug**

**Version of Helm and Kubernetes**:

helm v3.2.1 k8s: 1.16

**Which chart**:
chart version 2.1.1 is ok 
chart version 2.2.0 is broken

**What happened**:

Error: YAML parse error on jenkins/templates/config.yaml: error converting YAML to JSON: yaml: line 189: could not find expected ':'

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
@zsjohny Can you provide a `values.yaml` file which can be used to reproduce this error?

**Comment by scottrigby** [comment]
📢 `stable/jenkins` has moved to https://github.com/jenkinsci/helm-charts. If still applicable, please reopen the issue there. Thanks!

/close
