### ISSUE TITLE
[stable/datadog] unknown field "rule" in io.k8s.api.core.v1.PodSecurityContext

### ISSUE THREAD

**Issue by fbeauche** [helm/charts#23084]
**Describe the bug**

When upgrading the chart to the latest version i get this error :  
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(DaemonSet.spec.template.spec.securityContext): unknown field "rule" in io.k8s.api.core.v1.PodSecurityContext

**Version of Helm and Kubernetes**:
`
 kubectl version                                                                                                                                                                       Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a2cfecc33f6911261fb8a670d2df2714094002a6", GitTreeState:"clean", BuildDate:"2020-05-29T21:50:25Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
`

` helm  version                                                                                                                                                                         francois.beauchemin@MacBook-Pro
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}`
**Which chart**:

stable/datadog 

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

Seems to have been introduced in 2.3.23 ?

**Comment by SychevIgor** [comment]
Looks like issue need to be reopen after yesterday commit with update for windows agent
