### ISSUE TITLE
Chart concourse 0.5.0 not working with storageclass nfs!

### ISSUE THREAD

**Issue by mf-eri** [helm/charts#2312]
**Version of Helm and Kubernetes**:
Helm v2.1.2
Kubernetes 1.6.4

**Which chart**:
stable/concourse/0.5.0

**What happened**:

**What you expected to happen**:
Tried the helm chart for concourse (0.5.0) in minikube and it worked fine (with default storage class), when trying the chart in another K8S installation with a nfs storage class, also updated the storageclass 
values in the chart), and the concourse starts, but fails
when running a pipline….

Fails when trying to fetch via resources type:git ….

Also tried to change the different baggageclaimDrivers:

baggageclaimDriver: naive
runc create: exit status 1: container_linux.go:264: starting container process caused "process_linux.go:247: running exec setns process for init caused \"exit status 38\""
next time checking for hash..
Handle 'ae19ae43-dceb-474b-77b6-dc49493e4a12' already in use

baggageclaimDriver: btrfs
runc create: exit status 1: container_linux.go:264: starting container process caused "process_linux.go:247: running exec setns process for init caused \"exit status 38\""
next time checking for hash..
Handle 'ae19ae43-dceb-474b-77b6-dc49493e4a12' already in use

baggageclaimDriver: overlay
base resource type not found

**Comment by william-tran** [comment]
Do you need to use nfs? What infra are you running on?
