### ISSUE TITLE
[stable/nginx-ingress] Metric service name is not truncated to 63 chars

### ISSUE THREAD

**Issue by wasfree** [helm/charts#23148]
**Describe the bug**
As per _helpers.tpl in nginx-ingress names are truncate to 63 chars, reasons for this are known. But this seems not to be the case for [controller-metrics-service](https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-metrics-service.yaml), there is a suffix `"-metrics"` added. This suffix leads to 71 chars for releases with long name and cause the following issue:

```
2020-07-10T07:33:14.6835926Z Error: UPGRADE FAILED: failed to create resource: Service "internal-ingress-controller-nginx-ingress-foo-internal-ingress-metrics" is invalid: metadata.name: Invalid value: "internal-ingress-controller-nginx-ingress-foo-internal-ingress-metrics": must be no more than 63 characters
2020-07-10T07:33:14.6896185Z ##[error]Error: UPGRADE FAILED: failed to create resource: Service "internal-ingress-controller-nginx-ingress-foo-internal-ingress-metrics" is invalid: metadata.name: Invalid value: "internal-ingress-controller-nginx-ingress-foo-internal-ingress-metrics": must be no more than 63 characters
```
There is a legit reason for `"-metrics"` suffix to prevent naming collisions with other services in  `stable/nginx-ingress` chart.

**Version of Helm and Kubernetes**:
Helm `v3.2.0`
K8s `v1.16.10`

**Which chart**:
`stable/nginx-ingress`

**What happened**:
Release failed due to chars transgression in resource naming

**What you expected to happen**:
resource names are truncated to 63 chars

**How to reproduce it** (as minimally and precisely as possible):
Create a release with long name and enable metrics

**Possible fix**
We could truncate "nginx-ingress.controller.fullname" to 53 chars, similar issue applys to other resource.

- name: {{ template "nginx-ingress.controller.fullname" . }}-metrics
- name: {{ template "nginx-ingress.controller.fullname" . }}-admission
- name: {{ template "nginx-ingress.controller.fullname" . }}-internal

```
Create a default fully qualified controller name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "nginx-ingress.controller.fullname" -}}
{{- printf "%s-%s" (include "nginx-ingress.fullname" .) .Values.controller.name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```

**Comment by scottrigby** [comment]
`stable/nginx-ingress` has been deprecated in favor of the upstream `ingress-nginx` repo. See https://github.com/helm/charts/pull/22823. Issues if still applicable can be re-opened there. Thanks 😊
