### ISSUE TITLE
[stable/nginx-ingress] update image repo to gcr 

### ISSUE THREAD

**Issue by garethmorris78** [helm/charts#23152]
**Describe the bug**
Helm Chart default value for "repository" is using quay.io

**Which chart:**
stable/nginx-ingress

**What happened:**
Read Nginx Release notes. 

**Breaking Changes:**
The repository https://quay.io/repository/kubernetes-ingress-controller/nginx-ingress-controller is deprecated and read-only for historical purposes.
See https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.34.0

**Possible fix**
Recommend updating the value and/or guidance to recommend to gcr.io as per breaking change above.

**Comment by scottrigby** [comment]
`stable/nginx-ingress` has been deprecated in favor of the upstream `ingress-nginx` repo. See https://github.com/helm/charts/pull/22823. Issues if still applicable can be re-opened there. Thanks 😊
