### ISSUE TITLE
[stable/elastic-stack/] how do i set or rotate log size?

### ISSUE THREAD

**Issue by encryptblockr** [helm/charts#23155]
how do i set a log size to avoid getting storage used up?
i don't need to persist all logs and will like to set a limit to log size or find a way to delete old logs

anyway to set this up?

**Comment by andelhie** [comment]
I am looking in to this too.  It looks like you have to setup the elasticsearch yaml file and it spelled out there.

**Comment by encryptblockr** [comment]
@andelhie 
any luck? will like a way to rotate the logs to like 2 weeks or something like that? i don't need logs to persist

**Comment by andelhie** [comment]
So this is the yaml file for ES https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.htmlhttps://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html
You have to build it then pass it to helm.  It will then be loaded up in to the pods.
