### ISSUE TITLE
stable/jenkins - no able to add annotations

### ISSUE THREAD

**Issue by thepostgresguy** [helm/charts#23157]
**Describe the bug**

**Version of Helm and Kubernetes**:

**Which chart**: stable/jenkins

**What happened**: cannot add needed annotations

**What you expected to happen**: to execute helm with the annotation for load balancer service

**How to reproduce it** (as minimally and precisely as possible): helm install cicd stable/jenkins --set rbac.create=true,master.servicePort=80,master.serviceType=LoadBalancer,master.serviceAnnotations={"service.beta.kubernetes.io/aws-load-balancer-internali: true"}

**Anything else we need to know**:
Cannot add this annotation.

**Comment by torstenwalter** [comment]
@pgvirtuoso Where would you expect the annotations to be added? `master.serviceAnnotations` is added here
https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-svc.yaml#L15-L17
