### ISSUE TITLE
[stable/airflow] pip install timed out..

### ISSUE THREAD

**Issue by hyungryuk-zz** [helm/charts#23163]
**Describe the bug**
timeout occurred when pip install 

**Version of Helm and Kubernetes**:

**Which chart**:
stable/airflow

**What happened**:
when dags are sync with git repository (git-sync), try to install packages which are inside requirements.txt.
but every pip packages are timed out

**What you expected to happen**:
connected well

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I'm a new bie on k8s and helm chart. so that it might be a problem about k8s settings or else..

**Comment by thesuperzapper** [comment]
Can you please post the logs?
