### ISSUE TITLE
RabbitMQ deploy/update fails with chart stable/rabbitmq-ha

### ISSUE THREAD

**Issue by vap78** [helm/charts#23167]
**Describe the bug**

Update and fresh installation of RabbitMQ fails with chart stable/rabbitmq-ha.
We have been using the chart for some time and the last successful deployment with it was on 16.06.2020. Today we tried to execute the chart and helm update fails. 

**Version of Helm and Kubernetes**:
Helm version 2.16.1
Kubernetes version: 1.15.7 (update attempted)
Kubernetes version 1.18.2 (clean install)

**Which chart**:
rabbitmq-ha
I tried with versions 1.46.4 down to 1.45.0 - all fail with the same error.

**What happened**:
Update fails with:

> 2020-07-13T12:26:50.3533239Z [command]/usr/local/bin/helm upgrade --namespace rabbitmq --install --values values.yaml --wait --tiller-namespace rabbitmq --dry-run --debug rabbitmq-t stable/rabbitmq-ha --version 1.45.0
> 2020-07-13T12:26:54.0434805Z [debug] Created tunnel using local port: '43511'
> 2020-07-13T12:26:54.0436024Z 
> 2020-07-13T12:26:54.0436448Z [debug] SERVER: "127.0.0.1:43511"
> 2020-07-13T12:26:54.0436750Z 
> 2020-07-13T12:26:54.0437425Z [debug] Fetched stable/rabbitmq-ha to /home/agent/.helm/cache/archive/rabbitmq-ha-1.45.0.tgz
> 2020-07-13T12:26:54.0438219Z 
> 2020-07-13T12:26:54.0438842Z UPGRADE FAILED
> 2020-07-13T12:26:54.0439285Z Error: unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
> 2020-07-13T12:26:54.0455226Z Error: UPGRADE FAILED: unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
> 2020-07-13T12:26:54.0457153Z ##[error]Error: UPGRADE FAILED: unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"

The command was attempted without --dry-run parameter too - same result. 

**What you expected to happen**:
Successful installation/update. This chart worked before on the same Kubernetes cluster.

**How to reproduce it** (as minimally and precisely as possible):
This is a private installation and I cannot provide access to it. 

**Anything else we need to know**:
There is no Prometheus configuration in values.yaml. There was no Prometheus installation on this Kubernetes cluster when the chart worked. We attempted to explicitly disable Prometheus but without success.

Here are the Tiller logs for the execution:

> [tiller] 2020/07/13 12:13:45 getting history for release rabbitmq-a
> [storage] 2020/07/13 12:13:45 getting release history for "rabbitmq-a"
> [tiller] 2020/07/13 12:13:45 preparing install for rabbitmq-a
> [storage] 2020/07/13 12:13:45 getting release history for "rabbitmq-a"
> [tiller] 2020/07/13 12:13:45 rendering rabbitmq-ha chart using values
> 2020/07/13 12:13:45 info: manifest "rabbitmq-ha/templates/pdb.yaml" is empty. Skipping.
> 2020/07/13 12:13:45 info: manifest "rabbitmq-ha/templates/ingress.yaml" is empty. Skipping.
> 2020/07/13 12:13:45 info: manifest "rabbitmq-ha/templates/servicemonitor.yaml" is empty. Skipping.
> [tiller] 2020/07/13 12:13:45 performing install for rabbitmq-a
> [tiller] 2020/07/13 12:13:45 executing 0 crd-install hooks for rabbitmq-a
> [tiller] 2020/07/13 12:13:45 hooks complete for crd-install rabbitmq-a
> [tiller] 2020/07/13 12:13:47 failed install perform step: validation failed: unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"

Any further hints on how to investigate the issue are very welcome. The error message looks very cryptic. Looking it up on the internet yielded no results that make sense. There were some issues with Prometheus deployment back in 2018 with this error but again - we don't have/want to have Prometheus for this installation. 

Thank you
Vasil

**Comment by akostic-kostile** [comment]
It seems that this bug was introduced in version 1.44.2 and it's still there. This is the bug report I found that was autoclosed due to inactivity https://github.com/helm/charts/issues/22346.

This is the actual PR that caused the issue:
https://github.com/helm/charts/pull/21274#issuecomment-628279559

I can personally confirm that every version after 1.44.1 fails with the same message(unless you have prometheus-operator installed):

`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"`

Chart 1.44.1 is coming with v3.8.0 or RabbitMQ so, as a temporary workaround, I suggest you use this command to install:

`helm install rabbitmq-ha stable/rabbitmq-ha --set prometheus.operator.enabled=false`

**Comment by vap78** [comment]
Thanks a lot! The workaround works perfectly. 

What can we do so that the issue does not get closed automatically?

Although there is a workaround, the error message does not hint to it and for an odd reason the Google search did not return the closed issue although the content is more or less the same.

**Comment by akostic-kostile** [comment]
The issue does show up in search, that's how I managed to find it, I was having the same problem as you an hour before :)

As for actually fixing this issue that's a more complicated thing, first I thought this might be the best way to solve things:

`.Capabilities.APIVersions.Has "monitoring.coreos.com/v1"` however there seems to be the bug if you're using Helm v3 with v2 charts, like here, this option just gets ignored. So it would solve the problem for anyone using Helm v2 but not for the others. Here's a bug report detailing this behavior https://github.com/argoproj/argo-cd/issues/3631

 So I guess there are basically 3 options here:
1) Easy. Set prometheus.operator.enabled=false in the values.yaml, default installation will start working if the user is not running prometheus-operatior in the cluster, and those that do run it will have to set prometheus.operator.enabled=true themselves
2) Slow. Change templates/alerts.yaml to look like this and wait for the Helm v3 incompatibility to be resolved:
`{{ if and .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" .Values.prometheus.operator.enabled .Values.prometheus.operator.alerts.enabled }}`
3) Hardest, but probably best in the long run. Update chart to v2 apiVersion and moving the requirements to requirements.yaml
