### ISSUE TITLE
stable/datadog: acInclude does not work

### ISSUE THREAD

**Issue by bakayolo** [helm/charts#23179]
**Describe the bug**
I have configure datadog agent to only watch specific namespaces (using `acInclude: "kube_namespace:kinto-*"`) but it is currently watching all.

**Version of Helm and Kubernetes**:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.10-gke.8", GitCommit:"fd29f95f189cb16dd8fe0bd5dc8b485dfd049d2c", GitTreeState:"clean", BuildDate:"2020-06-23T23:44:30Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**Which chart**:
stable/chart

```
dependencies:
- name: datadog
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 2.3.10
digest: sha256:d85b890debf79dd9b57a34ea8900556a6f03c357ddfea566415a3fe300297da1
generated: "2020-06-22T10:36:14.586045+08:00"
```

**What happened**:
Datadog is watching and sending logs from all my namespaces.

**What you expected to happen**:
It should only send the logs from namespace starting with `kinto-`.

**How to reproduce it** (as minimally and precisely as possible):
Here is my `values.yaml` file.

```
datadog:
  enabled: false

  datadog:
    apiKeyExistingSecret: datadog

    clusterName: cluster-name

    logLevel: INFO

    kubeStateMetricsEnabled: false

    logs:
      enabled: false
      containerCollectAll: true
    
    acInclude: "kube_namespace:kinto-*"
    
    processAgent:
      enabled: false

  agents:
    enabled: false

    containers:
      agent:
        logLevel: INFO
```

**Anything else we need to know**:
I can confirm the environment variable

```
- name: DD_AC_INCLUDE
   value: kube_namespace:kinto-*
```

is on each pod.

**Comment by a7i** [comment]
@bappr I believe you need to fix your regex to `kinto-.*` (notice the `.` to indicate match any character).

By the way, based on their [doc here](https://docs.datadoghq.com/agent/kubernetes/?tab=helm#ignore-containers), this is now deprecated.

**Comment by bappr** [comment]
@a7i thanks for the feedback, I did not see it deprecated. I am gonna still test the `.*`, did not see the `.` before the wildcard but it actually makes totally sense.
Do you why it has been deprecated and what would be the replacement by any change?

**Comment by a7i** [comment]
@bappr it is being replaced by `DD_CONTAINER_INCLUDE`

**Comment by bappr** [comment]
Thanks!
