### ISSUE TITLE
[stable/jenkins] Error: YAML parse error on jenkins/templates/config.yaml: error converting YAML to JSON: yaml: line 252: could not find expected ':'

### ISSUE THREAD

**Issue by rnkhouse** [helm/charts#23171]
I am getting below error when I add scriptApproval:

Error: YAML parse error on jenkins/templates/config.yaml: error converting YAML to JSON: yaml: line 252: could not find expected ':'

**Describe the bug**
I have values.yaml file with below values:

    master:
        scriptApproval:
            - "field groovy.util.Node name"

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"ec831747a3a5896dbdf53f259eafea2a2595217c", GitTreeState:"clean", BuildDate:"2020-05-29T19:56:10Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
Jenkins

**What you expected to happen**:
It should deploy Jenkins successfully with scriptApproval.

**How to reproduce it** (as minimally and precisely as possible):
Install helm chart with given values.yaml file configs.

**Anything else we need to know**:
It was working fine before. Suddenly, stopped working.

**Comment by torstenwalter** [comment]
@rnkhouse This should be fixed by #23175

https://github.com/helm/charts/blob/master/stable/jenkins/ci/other-values.yaml#L20-L22 should verify that it works.

**Comment by rnkhouse** [comment]
@torstenwalter It's working now. Thanks!
