### ISSUE TITLE
[stable/prometheus-operator] Grafana dashboards timezone should not be hardcoded to UTC

### ISSUE THREAD

**Issue by acondrat** [helm/charts#23180]
**Describe the bug**
Seems like https://github.com/helm/charts/pull/22900/files set the timezone on all dashboards to UTC. This is not ideal as can't be changed unless one wants to edit and save a copy of the dashboard.

**Which chart**: prometheus-operator

As suggested in https://github.com/coreos/prometheus-operator/issues/1807#issuecomment-417759647 it is better to se the timezone to "default" so that dashboards will use the global setting defined in preferences.

**Comment by chrishatfield86** [comment]
Agreed, this is a very frustrating change!

**Comment by iaas365-dev** [comment]
Just in case it helps this is the workaround we applied:

PODS=$(kubectl -n monitoring get cm -o json | jq -r '.items[].metadata.name | select(.|test("^prom-prometheus-operator-"))')
kubectl -n monitoring get cm $PODS -o yaml > workaround.yaml
Replace with vi `:%s/"timezone":.*/"timezone": "browsertime",/g`
kubectl -n monitoring replace -f workaround.yaml
kubectl -n monitoring delete pod/prom-grafanaXXXX

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
