### ISSUE TITLE
[incubator/schema-registry] The chart will not work on kubernetes v1.16

### ISSUE THREAD

**Issue by ElenaForester** [helm/charts#23198]
**Describe the bug**
When try to install latest version (1.1.9) `schema-registry` chart on Kubernetes 1.16 getting an error:
```
helm install --name mysr incubator/schema-registry --dry-run
Error: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"
```
**Version of Helm and Kubernetes**:
Helm:
```
> helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
Kubernetes v1.16.8

**Which chart**:
schema-registry

**What happened**:
Fails with error `Error: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"`

**What you expected to happen**:
Chart succesfully installed

**How to reproduce it** (as minimally and precisely as possible):
Try to install `schema-registry` v1.1.9 (latest) in kubernetes v1.16

**Anything else we need to know**:
Need to update version of kafka in requirements.yaml to version which supports kubernetes v1.16

**Comment by a7i** [comment]
@ElenaForester This was fixed in PR https://github.com/helm/charts/pull/19983

**Comment by ElenaForester** [comment]
> @ElenaForester This was fixed in PR https://github.com/helm/charts/pull/19983

No, it was not.
This PR fixes schema-registry chart itself but not dependent kafka chart. My issue is because of kafka chart.

**Comment by a7i** [comment]
@ElenaForester Thanks for the additional data point. I have created a mini PR to address the issue mentioned.
