### ISSUE TITLE
Will helm charts become unusable?

### ISSUE THREAD

**Issue by hatharom** [helm/charts#23205]
Hi!

Some question about the deprecation timeline.

`At nov of 2020: "At 1 year, support for this project will formally end, and this repo will be marked obsolete"`

`"This timeline gives the community (chart OWNERS, organizations, groups or individuals who want to host charts) 9 months to move charts to new Helm repos, and list these new repos on the Helm Hub before stable and incubator are de-listed"`

For me this means that the charts will be removed and no longer available.

However as I am browsing through the charts I realize that most of them doesn't mention anything about their new repo neither in their github README nor in their helm hub description. This calmness of the different projects makes me unsure.
Maybe the charts will be able to be used after that?
Or should I avoid this repository as plague because huge amount of the chart will be deleted at Nov?
And write my own charts by hand(if no other exists for the given image I needed)?

Some clarification please :)

**Comment by fliphess** [comment]
Anyone?
