### ISSUE TITLE
Tasks failed on Apache Druid 

### ISSUE THREAD

**Issue by MateusHenriqueOliveira** [helm/charts#23201]
Hello, I'm using helm chart incubator/druid and when I submit any ingestion he fail the task, even when I try to use sample data wikipedia gets the same error:

K8s: minikube

Erro message in task log tab:
Request failed with status code 404

Helm install:
helm install druid -f /home/mateus_oliveira/druid-values.yaml incubator/druid --version 0.2.8 --set overlord.enabled=true 

Druid-value.yaml (just enable kafka ingestion)

 druid_extensions_loadList: '["druid-histogram", "druid-datasketches", "druid-avro-extensions","druid-kafka-indexing-service","druid-lookups-cached-global", "postgresql-metadata-storage"]'

**Comment by AWaterColorPen** [comment]
#22911
The default `druid_storage_type` value is `local`. you have to set the your deep storage for the Apache Druid cluster
