### ISSUE TITLE
[stable/jenkins] /bin/sh -c injected into container template for pod template

### ISSUE THREAD

**Issue by neilmfrench** [helm/charts#23203]
**Describe the bug**
When leaving agent.command blank, "/bin/sh -c" is injected into the command field in the container template for the default pod template. If I change agent.command to include something, then that command is correctly inputted, but I do not want to run any commands on pod startup.

**Version of Helm and Kubernetes**:
Helm v3.2.3
Kubernetes Server v1.15.9

**Which chart**:
Stable/Jenkins

**What happened**:
agent.command gets filled with "/bin/sh -c"

**What you expected to happen**:
agent.command should be empty 

**How to reproduce it** (as minimally and precisely as possible):
Leave agent.command blank

**Comment by torstenwalter** [comment]
It's nothing we configure. It seems to be the default from the configuration-as-code-pluigin.

See https://github.com/helm/charts/blob/fd67b6f09a2677303d864514974de2cd3e82eaa6/stable/jenkins/templates/_helpers.tpl#L174-L176

```
    {{- if .Values.agent.command }}
    command: {{ .Values.agent.command }}
    {{- end }}
```

**Comment by scottrigby** [comment]
📢 `stable/jenkins` has moved to https://github.com/jenkinsci/helm-charts. If still applicable, please reopen the issue there. Thanks!
