### ISSUE TITLE
[stable/prometheus-operator] failed to join cluster,unable to join gossip mesh

### ISSUE THREAD

**Issue by lianfulei** [helm/charts#23246]
pod logs
alertmanager-po-prometheus-operator-alertmanager-0

level=warn ts=2020-07-18T03:21:59.842Z caller=cluster.go:228 component=cluster msg="failed to join cluster" err="1 error occurred:\n\t* Failed to resolve alertmanager-po-prometheus-operator-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-po-prometheus-operator-alertmanager-0.alertmanager-operated.monitoring.svc on 10.64.0.10:53: no such host\n\n"

level=info ts=2020-07-18T03:21:59.842Z caller=cluster.go:230 component=cluster msg="will retry joining cluster every 10s"
level=warn ts=2020-07-18T03:21:59.842Z caller=main.go:322 msg="unable to join gossip mesh" err="1 error occurred:\n\t* Failed to resolve alertmanager-po-prometheus-operator-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-po-prometheus-operator-alertmanager-0.alertmanager-operated.monitoring.svc on 10.64.0.10:53: no such host\n\n"

**Comment by lianfulei** [comment]
i have slove it
Error reporting is normal

**Comment by arunkumarrspl** [comment]
Hi @lianfulei , 

could you please let me know how it was fixed? We have been getting the same error. Tried with two different versions of the alertmanager image **v0.21.0** and **v0.20.0**. 


`level=warn ts=2020-11-11T14:39:20.856Z caller=main.go:307 msg="unable to join gossip mesh" err="1 error occurred:\n\t* Failed to resolve alertmanager-prometheus-operator-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-prometheus-operator-alertmanager-0.alertmanager-operated.monitoring.svc on 100.64.0.10:53: no such host\n\n"`
