### ISSUE TITLE
nginx-ingress "default backend - 404" in version 1.41.0 of helm chart

### ISSUE THREAD

**Issue by davejhahn** [helm/charts#23267]
**Describe the bug**
I am receiving "default backend - 404" on version 1.41.0 of nginx-ingress.   I haven't changed anything else, just deployed the latest version and started getting this.

**Version of Helm and Kubernetes**:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"89d8075525967c7a619641fabcb267358d28bf08", GitTreeState:"clean", BuildDate:"2020-06-23T02:52:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**Which chart**:
stable/nginx-ingress 
version: 1.41.0

**What happened**:
Deployed version 1.41.0 and started receiving "default backend - 404".   Deployed back to version I had prior, 1.40.3, and it works fine.

**What you expected to happen**:
Route correctly.

**How to reproduce it** (as minimally and precisely as possible):
Install 1.41.0 version of helm chart

**Comment by WoopsDoops** [comment]
Hi,
I faced very similar issue, and I have returned back version 1.40.3 to make my ingress work again. In my case, ingress ignores annotation:
`nginx.ingress.kubernetes.io/rewrite-target: /$2`

Nevertheless, other rewrite annotations works perfectly fine:

```
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite ^/test/it$ /test/it/ permanent;
        rewrite ^/$ /test/it permanent;
```

I believe that it is bug, or breaking change, which should be announced before implementation.

**Comment by davejhahn** [comment]
@WoopsDoops  thanks for the info + confirmation, yeah I am using the same annotation:
nginx.ingress.kubernetes.io/rewrite-target: /$1

**Comment by a7i** [comment]
There is a 1.41.1 out that should address this. The underlying issue is related to an upstream change that was introduced in that release.

**Comment by davejhahn** [comment]
This was resolved with the updated version mentioned above.  Thanks.
