### ISSUE TITLE
[stable/jenkins] backup add activeDeadlineSeconds

### ISSUE THREAD

**Issue by Giancarlo1974** [helm/charts#23271]
**Is your feature request related to a problem? Please describe.**

https://github.com/helm/charts/issues/23270

**Describe the solution you'd like**

force the backup pod to close after a maximum of 23 hours

**Describe alternatives you've considered**

put in cronjob yaml
          activeDeadlineSeconds: 10800

for example

spec:
  schedule: 0 2 * * *
  startingDeadlineSeconds: 120
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          activeDeadlineSeconds: 10800
          containers:
            - name: jenkins-backup

**Additional context**

**Comment by scottrigby** [comment]
📢 `stable/jenkins` has moved to https://github.com/jenkinsci/helm-charts. If still applicable, please reopen the issue there. Thanks!
