### ISSUE TITLE
[stable/jenkins] Backup/restore the pod does not end

### ISSUE THREAD

**Issue by Giancarlo1974** [helm/charts#23270]
**Describe the bug**
The job starts the pod for backup to S3

if the job fails, the pod remains in running status

**Version of Helm and Kubernetes**:

$ helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

**Which chart**:

template Jenkins 2.4

**What happened**:

The job starts the pod for backup to S3

yesterday in the pos logs, I saw error exit code 1
but the pod remained in running status

today the second pod should have started,
but it didn't start because there was already an active pod

**What you expected to happen**:

pod status terminated

**How to reproduce it** (as minimally and precisely as possible):

Perhaps by disconnecting the network, the backup to S3 goes wrong

**Anything else we need to know**:

backup:
  enabled: true
  schedule: "0 2 * * *"
  existingSecret:
    jenkins-secrets:
      awsaccesskey: "SECRET_MY_JENKINS_BACKUP_ACCESS_KEY"
      awssecretkey: "SECRET_MY_JENKINS_BACKUP_SECRET_KEY"
  destination: "s3://my-jenkins-backup/test"
  env:
    - name: "AWS_REGION"
      value: "eu-west-1"

persistence:
  existingClaim: "jenkins"

**Comment by torstenwalter** [comment]
@Giancarlo1974 Could you create a PR to solve your issue?

**Comment by scottrigby** [comment]
📢 `stable/jenkins` has moved to https://github.com/jenkinsci/helm-charts. If still applicable, please reopen the issue there. Thanks!
