### ISSUE TITLE
[stable/grafana] During upgrade, password changes in secret but not in grafana

### ISSUE THREAD

**Issue by antonincms** [helm/charts#23272]
Hello,

**Describe the bug**
When we upgrade grafana (with helm upgrade --install stable/grafana) the secret changes but if the release is not new, the new password is not taken into account.

**Version of Helm and Kubernetes**:
Helm : v3.2.0 
Kubernetes : Client v1.18.3 Server v1.14.10-gke.36

**Which chart**:
stable/grafana, chart version 5.3.5

**What happened**:
The secret that we can retrieve with `kubectl get secret --namespace monitoring grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo` from the printed message changed, but grafana only accepted the old password...not retrievable anymore.

**What you expected to happen**:
The password should probably not change during upgrade, so the secret should stay the same.

**How to reproduce it** (as minimally and precisely as possible):
- Install grafana
- Write down output of `kubectl get secret --namespace monitoring grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo`, you should be able to connect with it
- Upgrade grafana
- `kubectl get secret --namespace monitoring grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo` will give you a different result, and the old one is still the valid password.

Best regards, Antonin

**Comment by NikolaeVarius** [comment]
Im also seeing the same behavior

**Comment by scottrigby** [comment]
📢 This chart is deprecated: https://github.com/helm/charts/pull/23662
If still applicable, please re-open issues at: https://github.com/grafana/helm-charts
