### ISSUE TITLE
[stable/prometheus-operator] non-functioning alertmanager template files

### ISSUE THREAD

**Issue by alexanderursu99** [helm/charts#23287]
**Describe the bug**
Trying to use template files in Alertmanager, but there appears to be some odd errors when trying to send the alerts.

**Version of Helm and Kubernetes**:
Helm: 3.2.4
Kubernetes: 1.16

**Which chart**:
stable/prometheus-operator 8.15.4

**What happened**:

With the following config, I see errors regarding the value of `.Status`.

```
alertmanager:
  config:
    global:
      ...
    route:
      ...
      receiver: my-receiver
    receivers:
    - name: my-receiver
      slack_configs:
      - ...
        title: '{{ template "slack.myorg.title" }}'
        text: '{{ template "slack.myorg.text" }}'
    templates:
    - '/etc/alertmanager/config/template*.tmpl'
  templateFiles:
    template_basic.tmpl: |-
      {{ define "slack.myorg.title" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}{{ end }}

      {{ define "slack.myorg.text" }}
      {{ range .Alerts -}}
        *{{ .Status }}:* `{{ .Labels.severity }}` - {{ .StartsAt }}

        {{ range .Annotations.SortedPairs }} • *{{ .Name }}:* {{ .Value }}
        {{ end }}
      {{ end }}
      {{ end }}
```

```
level=error ts=2020-07-21T23:23:25.236Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"slack\" due to unrecoverable error: template: template_basic.tmpl:2:14: executing \"slack.myorg.title\" at <toUpper>: invalid value; expected string" context_err=null
level=error ts=2020-07-21T23:23:25.236Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"slack\" due to unrecoverable error: template: template_basic.tmpl:2:14: executing \"slack.myorg.title\" at <toUpper>: invalid value; expected string"
```

This also seems to happen when `toUpper` is removed from the title, and then there are issues with `eq .Status "firing"`.

I copied the definition of the title template back into the `title:` key of `slack_configs:`, and then it worked just fine, although the messages came with no text, only title. I then also copied the definition of the text template back into the `text:` key of `slack_configs:` and only then do I get alerts sent properly.

**What you expected to happen**:

For alerts to be sent to the slack channel.

**How to reproduce it** (as minimally and precisely as possible):

Run version 8.15.4 of the Helm chart with a similar alertmanager config.

**Comment by bridgetkromhout** [comment]
Hi, @Alxander64 - This repo has no support available. For your question, I suggest https://github.com/prometheus-community/helm-charts - cheers.
