### ISSUE TITLE
Update name truncation in charts to 63 char limit

### ISSUE THREAD

**Issue by prydonius** [helm/charts#233]
# Problem
Helm release names are often cut-off due to the 24 character limit. In some cases this can lead to invalid names being generated (#246).
See https://github.com/kubernetes/helm/issues/1528

# Proposal
Service names up to 63 are now allowed, so charts that are currently truncating names to 24 chars should be updated for the new limit.

# Affected charts

## Incubator
- [ ] artifactory
- [ ] consul #361
- [ ] elasticsearch
- [ ] etcd
- [ ] mongodb-replicaset
- [ ] patroni
- [ ] zookeeper

## Stable
- [x] chronograf
- [ ] datadog
- [x] dokuwiki
- [ ] etcd-operator
- [x] factorio
- [x] ghost
- [x] gitlab-ce
- [x] influxdb
- [x] jasperreports
- [x] jenkins
- [x] joomla
- [x] kapacitor
- [ ] kube2iam
- [ ] linkerd
- [x] magento
- [x] mariadb
- [x] mediawiki
- [ ] memcached
- [x] minecraft
- [x] minio (#480)
- [x] mongodb
- [x] mysql (#479)
- [x] nginx-lego (#339)
- [x] odoo
- [x] opencart
- [ ] openvpn
- [x] orangehrm
- [x] owncloud (#417)
- [x] phabricator
- [x] phpbb
- [x] postgresql
- [x] prestashop
- [x] rabbitmq
- [x] redis
- [x] redmine
- [x] sapho
- [ ] sensu
- [ ] spark
- [ ] spartakus
- [ ] sumokube
- [ ] telegraf
- [x] testlink
- [x] traefik
- [ ] uchiwa

**Comment by rio** [comment]
mysql chart has been updated in #456. Nice list!

**Comment by prydonius** [comment]
Thanks @Rio, I've updated the list!

**Comment by cknowles** [comment]
All of these seem to be done now:
* incubator - etcd/patroni/zookeeper
* stable - artifactory/consul/datadog/elasticsearch/etcd-operator/kube2iam/memcached/mongodb-replicaset/sensu/spartakus/uchiwa

Plus telegraf seems to be deprecated https://github.com/kubernetes/charts/pull/823.

**Comment by prydonius** [comment]
Indeed, thanks. Closing.
