### ISSUE TITLE
[stable/jenkins] Make PrometheusRule Namespace configurable

### ISSUE THREAD

**Issue by fl-max** [helm/charts#23306]
**Is your feature request related to a problem? Please describe.**
By default, and without customizations, Prometheus only looks for PrometheusRules and ServiceMonitors in its own Namespace. Currently, the ServiceMonitor Namespace is configurable but the [PrometheusRule](https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-alerting-rules.yaml#L7) is not.

**Describe the solution you'd like**
Add support to allow PrometheusRule to be configured via `.Values.master.prometheus.prometheusRuleNamespace`

**Example:**
```helm
{{- if .Values.master.prometheus.prometheusRuleNamespace }}
  namespace: {{ .Values.master.prometheus.prometheusRuleNamespace }}
{{- else }}
  namespace: {{ template "jenkins.namespace" . }}
{{- end }}
```

Also, add these to the `values.yaml` file and Document them.

**Describe alternatives you've considered**
Modifying Prometheus to scan other Namespaces

**Additional context**

**Comment by torstenwalter** [comment]
@fl-max I like you suggestion. Could you create a PR for that?

**Comment by scottrigby** [comment]
📢 `stable/jenkins` has moved to https://github.com/jenkinsci/helm-charts. If still applicable, please reopen the issue there. Thanks!
