### ISSUE TITLE
[stable/graylog] one-liner - init container does work behind proxy

### ISSUE THREAD

**Issue by h4wkmoon** [helm/charts#23310]
**Describe the bug**
The init container does work well with containers beause of the use of busybox wget.

**Version of Helm and Kubernetes**:
kube 1.11 (yes, I know)
heml 3

**Which chart**:
stable/graylog

**What happened**:
Unable to download kubectl from internet

**What you expected to happen**:
Be able to download kubectl from internet

**How to reproduce it** (as minimally and precisely as possible):
Install chart behind a proxy

**Anything else we need to know**:
`apk add wget` before using the command wget does the trick.
https://github.com/helm/charts/blob/master/stable/graylog/templates/statefulset.yaml#L63

**Comment by mattfarina** [comment]
This should be listed as a bug. Charts should be portable and not require internet access. The elements referenced should be able to be pointed to other locations. Air gapped environments should be possible.
