### ISSUE TITLE
[stable/oauth2-proxy] migrate to v6.0.0

### ISSUE THREAD

**Issue by Morriz** [helm/charts#23315]
Any plans on releasing a chart that matches v6?

I will try to user the v6 image and see if it works...

**Comment by mattfarina** [comment]
@Morriz if you are able to get it working would you be interested in a pull request to update the chart?

/cc @desaintmartin @miouge1

**Comment by Morriz** [comment]
It works out of the box with v6 :)

cookie-domain is now a comma separated list btw

**Comment by Morriz** [comment]
The release logs mentioned it became cookie-domains but that seems not true
