### ISSUE TITLE
[stable/airflow] inconsistent `extraConfigmapMounts` settings

### ISSUE THREAD

**Issue by fengsi** [helm/charts#23338]
**Is your feature request related to a problem? Please describe.**
Currently, there are [two ways](https://github.com/helm/charts/blob/master/stable/airflow/templates/deployments-web.yaml#L181-L191) to apply `extra*` settings in templates:
```
{{- range .Values.airflow.extraConfigmapMounts }}
- name: {{ .name }}
  mountPath: {{ .mountPath }}
  readOnly: {{ .readOnly }}
  {{- if .subPath }}
  subPath: {{ .subPath }}
  {{- end }}
{{- end }}
{{- if .Values.airflow.extraVolumeMounts }}
{{- toYaml .Values.airflow.extraVolumeMounts | nindent 12 }}
{{- end }}
```
IMHO, there is little benefit wrapping `extraConfigmapMounts` than simply `toYaml` the raw content.  Even worse, the two methods are mixed in the **same file** with the **same naming pattern**.
Why do we need to remember `extraConfigmapMounts` is a wrapper but `extraVolumeMounts` is raw YAML?  This is **extremely confusing**.

**Describe the solution you'd like**
We may want to have all `extra*` settings to be raw YAML.  This will give the user more control over these hooks.
Something like:
```
{{- if .Values.airflow.extraConfigmapMounts }}
{{- toYaml .Values.airflow.extraConfigmapMounts | nindent 12 }}
{{- end }}
{{- if .Values.airflow.extraVolumeMounts }}
{{- toYaml .Values.airflow.extraVolumeMounts | nindent 12 }}
{{- end }}
```

**Comment by thesuperzapper** [comment]
@fengsi 

I am fairly sure the reason we are not using `toYaml` is because the `airflow.extraConfigmapMounts` value is that different components are used under `volumeMounts:` and `volume:`.

Is there anything you are unable to do in the current setup?
