### ISSUE TITLE
Nextcloud securityContext and rootlessness

### ISSUE THREAD

**Issue by BobyMCbobs** [helm/charts#23344]
# Goal
securityContext should be able to be configured in a _values.yaml_ file.  

With the configuration available, there should be default rules to secure the container to make it run as _www-data_ instead of root (this may require running on a different port).

**Comment by billimek** [comment]
@BobyMCbobs the nextcloud chart has migrated to a new repo.  Can you please raise that issue over there?  https://github.com/nextcloud/helm

**Comment by BobyMCbobs** [comment]
Superseded by https://github.com/nextcloud/helm/issues/9
