### ISSUE TITLE
[stable/prometheus-operator] "Compute Resources / Pod dashboard" per container

### ISSUE THREAD

**Issue by orifito** [helm/charts#23355]
**Is your feature request related to a problem? Please describe.**
I'm running k8s 1.14.10 and, after upgrading the prometheus-operator chart to 9.x.x, noticed that on the "Compute Resources/Pod" dashboard resources requests/limits are graphed per pod, instead of per container as it used to be (while the current CPU and memory usage are still graphed per container).

I find this quite misleading for pods with more than one container.

**Describe the solution you'd like**
Resources requests/limits graphed per container.

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
