### ISSUE TITLE
[stable/minio] allows to update admin credentials

### ISSUE THREAD

**Issue by sushiMix** [helm/charts#23351]
I'd like to be able to update the password using a secure way:
Two env var exists: MINIO_ACCESS_KEY_OLD and MINIO_SECRET_KEY_OLD and shall be set like MINIO_ACCESS_KEY and  MINIO_SECRET_KEY

**Is your feature request related to a problem? Please describe.**
I used the functionality to update the admin password (renewal)

**Describe the solution you'd like**
Add old secret like current secret.

**Describe alternatives you've considered**
Using hard coded env in pod to perform the update but it requires to make it more visible than secret.

**Additional context**

**Comment by johny-mnemonic** [comment]
Any progress here?
