### ISSUE TITLE
Bot did not add labels

### ISSUE THREAD

**Issue by calvinbui** [helm/charts#23368]
**What happened**: The k8s-ci-robot did not add the necessary `Contributions Allowed` label to my PR @ https://github.com/helm/charts/pull/23292. It also missed the `size/M` label.

**What you expected to happen**: The `Contributions Allowed` and `size/M` labels to be added after the PR is created

**How to reproduce it (as minimally and precisely as possible)**: Created a PR from my fork to the Helm Charts repo. Nothing special.

**Please provide links to example occurrences, if any**: 
- Faulty PR: https://github.com/helm/charts/pull/23292
- Good PR: https://github.com/helm/charts/pull/23352
- PR Status: https://prow.k8s.io/pr?query=is%3Apr%20repo%3Ahelm%2Fcharts%20author%3Acalvinbui%20head%3Amysql-metricRelabelings

**Anything else we need to know?**: I opened an [issue over in the kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/18482) repo but was forwarded back here

**Comment by mattfarina** [comment]
@calvinbui This is added by a bot run by Helm. If there was a failure you can file an issue here. If the bot is having an outage we can fix it. If there was some blip, as happens with webhooks sometimes, the repo (charts) maintainers can manually apply the label.

**Comment by calvinbui** [comment]
No worries. I didn't know who I could've pinged though. I assume any of the approvers in this list next time? https://github.com/helm/charts/blob/master/OWNERS
