### ISSUE TITLE
[incubator/druid] fails with containerd 1.12.3 -- mkdir: can't create directory 'var/[tmp,druid]': Permission denied

### ISSUE THREAD

**Issue by svilcu** [helm/charts#23373]
**Describe the bug**
When using "containerd" as container runtime, Zookeeper and Postgresql are running fine, however... all the druid pods Error.

**Version of Helm and Kubernetes**:
helm version: 3.2.3
Kubernetes version: 1.18.6
minikube version: v1.12.1

**Which chart**:
incubator/druid 

**What happened**:
$ kubectl get pods -n druid
NAME                                                 READY    STATUS                RESTARTS   AGE
druid-broker-6574f9468b-f4bl8                  0/1     CrashLoopBackOff     10         30m
druid-coordinator-7b6cb89658-lmq2q       0/1     CrashLoopBackOff   10         30m
druid-historical-0                                        0/1     CrashLoopBackOff   10         30m
druid-middle-manager-0                            0/1     CrashLoopBackOff   10         30m
druid-postgresql-0                                     1/1     Running            0          30m
druid-router-b7b54874-kr8tt                      0/1     CrashLoopBackOff   10         30m
druid-zookeeper-0                                     1/1     Running            1          30m
druid-zookeeper-1                                     1/1     Running            0          29m
druid-zookeeper-2                                     1/1     Running            0          28m

All druid pods Error then enter in a CrashLoopBackOff status with the following log messages:
$ kubectl logs -n druid druid-historical-0
[...]
mkdir: can't create directory 'var/tmp': Permission denied
mkdir: can't create directory 'var/druid/': Permission denied
[...]

This seems to be related to the fact that the securityContext is not set in the druid chart, as it is set in the postgresql, mysql and zookeeper ones.

**What you expected to happen**:
I am expecting to have the druid pods with status "Running" 

**How to reproduce it**:
# Minikube is installed on Fedora 32 with kernel 5.7.10-201.fc32.x86_64 from the  package:
# rpm -i docker-machine-driver-kvm2-1.12.1-0.x86_64.rpm minikube-latest.x86_64.rpm

minikube start --cpus=6 --memory=24g --container-runtime='containerd' --kubernetes-version='1.18.6'
kubectl create ns  druid  
helm install druid incubator/druid -n druid

**Anything else we need to know**:
using "docker" or "crio" instead of "containerd" leads to Druid running with no error. 

Thank you!

**Comment by AWaterColorPen** [comment]
It seem the `securityContext` issue. the fix PR https://github.com/helm/charts/pull/23069 blocked.
