### ISSUE TITLE
[stable/nginx-ingress] Deployment apiVersion set to extensions/v1beta1 with Helm 3

### ISSUE THREAD

**Issue by BHeinson-rms** [helm/charts#23377]
**Describe the bug**
When deploying nginx-ingress with Helm 3.2.4 the deployment `apiVersion` is set to `extensions/v1beta1`. Per the function below it should be `apps/v1`. It appears `.Capabilities.KubeVersion.GitVersion` doesn't work with Helm 3

`{{/*`
`Return the appropriate apiVersion for deployment.`
`*/}}`
`{{- define "deployment.apiVersion" -}}`
`{{- if semverCompare ">=1.9-0" .Capabilities.KubeVersion.GitVersion -}}`
`{{- print "apps/v1" -}}`
`{{- else -}}`
`{{- print "extensions/v1beta1" -}}`
`{{- end -}}`
`{{- end -}}`

**Version of Helm and Kubernetes**:
Helm 3.2.4
Kubernetes 1.15

**Which chart**:
stable/nginx-ingress

**What happened**:
This is causing a mismatch with `kind` in `scaleTargetRef` in HPA, which is `apps/v1`. HPA is not working and is throwing errors `missing request for cpu` and `missing request for memory`.

**What you expected to happen**:
Deployment `apiVersion` set to `apps/v1` and HPA works.

**How to reproduce it** (as minimally and precisely as possible):
Install nginx-ingress with the following controller options:

`  resources:`
`    limits:`
`      cpu: "4"`
`      memory: 512Mi`
`    requests:`
`      cpu: "2"`
`      memory: 256Mi`
`  autoscaling:`
`    enabled: true`
`    minReplicas: 8`
`    maxReplicas: 20`
`    targetCPUUtilizationPercentage: 50`
`    targetMemoryUtilizationPercentage: 50 `

**Anything else we need to know**:

**Comment by javajon** [comment]
Related, with Kubernetes 1.18 there are a few deprecations that impact this chart.

> kube-apiserver no longer serves the following deprecated APIs: (#85903, @liggitt) * All resources under apps/v1beta1 and apps/v1beta2 - use apps/v1 instead * daemonsets, deployments, replicasets resources under extensions/v1beta1 - use apps/v1 instead * networkpolicies resources under extensions/v1beta1 - use networking.k8s.io/v1 instead * podsecuritypolicies resources under extensions/v1beta1 - use policy/v1beta1 instead

Kubeless chart 2.1.1 installation fails with the following
```bash
$ helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com
$ helm version --short
v3.1.2+gd878d4dcontrolplane 

$ kubectl version --short
Client Version: v1.18.0
Server Version: v1.18.0

controlplane $ helm install my-kubeless incubator/kubeless --version 2.1.1 --namespace kubeless --set ui.enabled=true --set rbac.create=true
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install
"Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```

**Comment by scottrigby** [comment]
`stable/nginx-ingress` has been deprecated in favor of the upstream `ingress-nginx` repo. See https://github.com/helm/charts/pull/22823. Issues if still applicable can be re-opened there. Thanks 😊
