### ISSUE TITLE
[jenkins/stable] Trouble with self-signed ca-certificate

### ISSUE THREAD

**Issue by MadEngineX** [helm/charts#23375]
**Describe the bug**

Hello! I need Jenkins and Gitlab integration for CI/CD.
Due to Gitlab communicates via HTTPS, I need to put my self-signed root-ca certificate into the Jenkins pod.
But it doesn't works.

**Version of Helm and Kubernetes**:

Helm v3.2.1, Kubernetes v1.17.5

**Which chart**:

jenkins/stable

**What happened**:

The first thing I did was describe the certificate as a secret in the namespace and mounted it in the etc/ssl/certs directory,
In response, I got an error in Jenkins app:

![image](https://user-images.githubusercontent.com/67797566/88657347-7570dc00-d0da-11ea-9052-9e9fe1448fd5.png)
And curl of my https gitlab link from jenkins-pod gave the following answer:

![image](https://user-images.githubusercontent.com/67797566/88673901-cfc96700-d0f1-11ea-8ac5-020f5b386a61.png)

After that I took the Jenkins Docker and Debian Docker images and tried to update the certificate at the image level.
```
FROM debian:latest

WORKDIR /
USER root
RUN mkdir -p /usr/share/ca-certificates/extra/
COPY ca-root.crt /usr/local/share/ca-certificates/

RUN apt-get update && apt-get install -y curl
RUN apt-get install -y ca-certificates 
RUN update-ca-certificates -f
```
Response was same: 

> root@3a7b187df1ea:/# curl https://gitlab.k8s-stage.mybank
curl: (60) SSL certificate problem: unable to get issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

I suppose the problem may be at the level of Debian image, cause curl on Ubuntu-container with my root-ca works fine:

![image](https://user-images.githubusercontent.com/67797566/88674202-3484c180-d0f2-11ea-8c7a-746b248b7d2c.png)

**What you expected to happen**:
I expect it is possible to add a certificate at the Helm chart level.

**How to reproduce it** (as minimally and precisely as possible):
Have no ideas.

**Anything else we need to know**:

I understand, that only curl gives not too much, so i did
` openssl s_client -showcerts -connect gitlab.k8s-stage.mybank:443`
From Debian container with ca-cert, this is response:

```CONNECTED(00000003)
depth=1 DC = mybank, CN = MY Bank Class II CA 01
verify error:num=2:unable to get issuer certificate
issuer= CN = MY-POL-CA-INT
verify return:1
depth=0 C = RU, ST = Some-State, L = Moscow, O = MY Group, OU = IT Dept, CN = *.k8s-stage.mybank
issuer= DC = mybank, CN = MY Bank Class II CA 01
verify return:1
---
Certificate chain
 0 s:C = RU, ST = Some-State, L = Moscow, O = MY Group, OU = IT Dept, CN = *.k8s-stage.mybank
   i:DC = mybank, CN = MY Bank Class II CA 01
-----BEGIN CERTIFICATE-----
**cert**
-----END CERTIFICATE-----
---
Server certificate
subject=C = RU, ST = Some-State, L = Moscow, O = MY Group, OU = IT Dept, CN = *.k8s-stage.mybank

issuer=DC = mybank, CN = MY Bank Class II CA 01

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2321 bytes and written 409 bytes
Verification error: unable to get issuer certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: ***
    Session-ID-ctx:
    Master-Key: ***
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 600 (seconds)
    TLS session ticket:
	**ticket**	

    Start Time: 1595935227
    Timeout   : 7200 (sec)
    Verify return code: 2 (unable to get issuer certificate)
    Extended master secret: yes
---
closed```

**Comment by wbe7** [comment]
I have the same problem with jenkins in my private infrastructure.

**Comment by MadEngineX** [comment]
I also must add, that when i use curl with --cacert key it's works:

```root@705d136dee91:/# curl https://gitlab.k8s-stage.mybank --cacert etc/ssl/certs/ca-k8s-stage.crt```
```<html><body>You are being <a href="https://gitlab.k8s-stage.mybank/users/sign_in">redirected</a>.</body></html>root@705d136dee91:/#```

Do somebody haves any ideas, how to add my cert correctly?

**Comment by torstenwalter** [comment]
Did you any of you tried if https://github.com/helm/charts/tree/master/stable/jenkins#https-keystore solves your issue? I haven't used it myself, but it looks as if it allows you to configure a key store used by Jenkins.

**Comment by MadEngineX** [comment]
We have a temporary solution.

Firstly, we had problems with certificates.
If someone has a situation where the local CA will give you several certificates instead of the assembled chain, you can do the following:
1) you need to have all certificates in .crt format, you can use the command
`openssl x509 -in root_ca.cer -out root_ca.crt -inform DER -outform PEM`
3) put all certificates (intermediate, server, root) in /usr/local/share/ca-certificates/
3) run `update-ca-certificates` or use `dpkg-reconfigure ca-certificates`

However, for such a solution, you need to rebuild the docker image and I would like to be able to add certificates at the Helm chart level.

**Comment by scottrigby** [comment]
📢 `stable/jenkins` has moved to https://github.com/jenkinsci/helm-charts. If still applicable, please reopen the issue there. Thanks!
