### ISSUE TITLE
[stable/prometheus-operator] generated pvc names are excessively verbose

### ISSUE THREAD

**Issue by TJM** [helm/charts#23376]
**Describe the bug**
The dynamically generated names of the pvc(s) are excessively verbose.

**Version of Helm and Kubernetes**:

```
$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T23:30:39Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
`stable/prometheus-operator` - so far the same pattern has occurred for alertManager and prometheus itself

**What happened**:

```
$ kubectl get pvc
NAME                                                                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
alertmanager-prometheus-operator-alertmanager-db-alertmanager-prometheus-operator-alertmanager-0   Bound    pvc-8e4514bc-9d4b-4c4d-9094-01ce59d049e4   10Gi       RWO            vsphere-pure-02   31s
prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0           Bound    pvc-d85b330c-f945-47cc-b7a5-1a01ef10694d   100Gi      RWO            vsan-default      6d19h
```

**What you expected to happen**:

The dynamically generated names should be shortened, they contain redundant information.

They should really only need `DEPLOYMENT_NAME`-`VOL_NAME`-`INSTANCE` ?

For example:

* `prometheus-operator-alertmanager-db-0`
* `prometheus-operator-prometheus-db-0`

(although the use of "db" even seems excessive)

**How to reproduce it** (as minimally and precisely as possible):

* values.yaml
```
alertmanager:
  alertmanagerSpec:
    replias: 2 # does not appear to work
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          # storageClassName: vsan-default
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi
```

**Anything else we need to know**:
I am betting the grafana chart works the same, but we are not currently using that.

**Comment by TJM** [comment]
That is very annoying.

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
