### ISSUE TITLE
[stable/prometheus-operator] Allow list of ports for prometheus service

### ISSUE THREAD

**Issue by janlud** [helm/charts#23381]
**Is your feature request related to a problem? Please describe.**
I have Thanos sidecar running in the prometheus pod and I want to use Thanos Query in the same cluster to query the service on port 10901 (thanos grpc port). I cannot add that in the prometheus chart as the port is a single value and not a list.

**Describe the solution you'd like**
Iterate over a list/map of ports for the service here: https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/service.yaml#L35

**Describe alternatives you've considered**
None at this point, adding second port to the service in the chart is cleanest solution by far.

**Additional context**
Verified this works for Thanos integration by manually editing the service.

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
