### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ryankiki86** [helm/charts#23393]
Error: YAML parse error on mongodb-replicaset/templates/mongodb-statefulset.yaml: error converting YAML to JSON: yaml: line 123: mapping values are not allowed in this context

**Comment by kaykhancheckpoint** [comment]
having the same problem did u find a fix?

**Comment by ryankiki86** [comment]
Yeah,I change another version of mongodb-replicaset,I do it like this:
wget http://mirror.azure.cn/kubernetes/charts/mongodb-replicaset-3.9.6.tgz
tar -zxvf mongodb-replicaset-3.9.6.tgz
configure some value in mongodb-replicaset/values.yaml if you need to do
kubectl create ns mongodb
helm install mongodb-replicaset -n mongodb ./mongodb-replicaset

**Comment by ryankiki86** [comment]
> having the same problem did u find a fix?

Yeah,I change another version of mongodb-replicaset,I do it like this:
wget http://mirror.azure.cn/kubernetes/charts/mongodb-replicaset-3.9.6.tgz
tar -zxvf mongodb-replicaset-3.9.6.tgz
configure some value in mongodb-replicaset/values.yaml if you need to do
kubectl create ns mongodb
helm install mongodb-replicaset -n mongodb ./mongodb-replicaset

**Comment by kaykhancheckpoint** [comment]
Ye i saw there was a pull request to fix this issue, apparently its something to do with indentation. https://github.com/helm/charts/pull/23345

Anyway i think these stable/charts are being slowly deprecated so im now looking at the original maintaners of the mongodb chart 

https://github.com/bitnami/charts/tree/master/bitnami/mongodb
