### ISSUE TITLE
[incubator/druid] placing proto descriptor

### ISSUE THREAD

**Issue by kentakozuka** [helm/charts#23391]
I am trying to use druid-protobuf-extensions with reading the instruction [here](https://druid.apache.org/docs/latest/development/extensions-core/protobuf.html). To use the proto extension, we need to place a proto descriptor file somewhere that is accessible from the Overlord (or Coordinator?). Is there a good way to do this with the helm chart? Or do we need to enable overlord to mount configmap to read the descriptor file?

**Comment by AWaterColorPen** [comment]
Maybe it is necessary to support a generic way to mount customer files into containers.

Now you can build a new image with office druid base image and your descriptor file.😰

**Comment by kentakozuka** [comment]
> Now you can build a new image with office druid base image and your descriptor file.

Thanks! I was searching for an easy and dynamic way to add/change descriptors but it seems this is the only option I should do :(
