### ISSUE TITLE
[stable/jenkins] set SECRETS environment variable for JCasC

### ISSUE THREAD

**Issue by oofnikj** [helm/charts#23410]
**Is your feature request related to a problem? Please describe.**
Using Jenkins Configuration as Code, it's unclear from both the chart documentation and the JCasC docs how to define secrets to be consumed in the configuration.

**Describe the solution you'd like**
Setting secrets into the JCasC configuration through the Helm chart should be easy and well-documented. In addition, setting `master.secretsFilesSecret` should configure JCasC to automatically point to `/var/jenkins_secrets` for loading secrets.

Perhaps a fully documented example can be helpful:
> Add the following values to Helm (**`SECRETS` env should not be necessary; it should be the default**):
> ```yaml
> master:
>   secretsFilesSecret: jenkins-secrets
>   containerEnv:
>   - name: SECRETS
>     value: /var/jenkins_secrets
> ```
> 
> Create a Kubernetes secret:
> ```yaml
> apiVersion: v1
> kind: Secret
> metadata:
>   name: jenkins-secrets
> data:
>   okta-client-id: c3VwZXI=
>   okta-client-secret: c2VjcmV0
> ```
> Consume the secrets in JCasC config:
> ```yaml
> master:
>   JCasC:
>     configScripts:
>       security: |
>         jenkins:
>           securityRealm:
>             oic:
>               clientId: ${okta-client-id}
>               clientSecret: ${okta-client-secret}
> ```

**Additional context**
JCasC secrets documentation: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc#kubernetes-secrets

**Comment by torstenwalter** [comment]
`master.secretsFilesSecret` is for configuring secrets via XML configuration. That has nothing to do with JCasC.

**Comment by oofnikj** [comment]
Hi @torstenwalter , maybe I misunderstood this function in the chart or found an alternative use for it that wasn't the original intention.

I wanted a way to mount a secret file inside the Jenkins container and have it be included in the JCasC config rather than Jenkins directly. I suppose this could have also been done with `persistence.volumes` and `persistence.mounts`, but the plumbing was already there with `master.secretsFilesSecret`.

May I suggest to "re-brand" this key so that it may be used for JCasC secrets too as outlined above?

**Comment by scottrigby** [comment]
📢 `stable/jenkins` has moved to https://github.com/jenkinsci/helm-charts. If still applicable, please reopen the issue there. Thanks!

**Comment by torstenwalter** [comment]
I would prefer to have a new key as someone might use it with XML content in it.
