### ISSUE TITLE
[stable/airflow] Flower deployment not getting extraPipPackages

### ISSUE THREAD

**Issue by ghost** [helm/charts#23424]
**Describe the bug**:

Adding items to `extraPipPackages` will not force pip to install them into pods related Flower but only web, scheduler and worker ones.

**Version of Helm and Kubernetes**:

Not related a specific version

**Which chart**:

stable/airflow

**What happened**:

Tried to install `flask_bcrypt` just to have authentication on but airflow-flower pods are not getting it installed so they go in crashloopback.

**What you expected to happen**:

Have `flask_bcrypt` or any other pip package installed in Flower pods too.

**How to reproduce it** (as minimally and precisely as possible):

Setting this in `values.yaml`:
```
airflow:
      extraPipPackages:
        - "flask-bcrypt~=0.7.1"
```
then check aiflow-flower pods that will not contain this installation completed.

**Anything else we need to know**:

Will try to issue a PR soon.

**Comment by valeriano-manassero** [comment]
I'm still waiting for review/approval of related PR

**Comment by MingLunWu** [comment]
Hi, I ran into a similar problem: 

Tried to install flask_bcrypt just to have authentication on but airflow-flower pods are not getting it installed so they go in crashloopback. 

Did you have any workaround?
