### ISSUE TITLE
[stable/prometheus-operator] https://github.com/helm/charts#status-of-the-project EOL

### ISSUE THREAD

**Issue by todd-berger** [helm/charts#23432]
**Describe the bug**
According to https://github.com/helm/charts#status-of-the-project stable is going EOL and repo owners are required to migrate to their own repo by august 13.

**Which chart**:
stable/prometheus-operator

**What happened**:
There's no update as to the progress of this or where/if it's being moved to another repo.

**What you expected to happen**:
New repo location 🤞

**Comment by todd-berger** [comment]
Not sure if this https://github.com/coreos/prometheus-operator/releases/tag/v0.41.0 indicates the final location as prometheus-operator/prometheus-operator?

**Comment by yoan-adfinis** [comment]
It looks like it.

**Comment by xmath279** [comment]
This seems to indicate the new repo for Prometheus Operator, but this helm chart is not managed by them as indicated in the README of the repository.

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
