### ISSUE TITLE
[stable/grafana] when persistence enabled pod is not running

### ISSUE THREAD

**Issue by muradheydarov** [helm/charts#23442]
I want to persist grafana. But when I enable persistence, can not start pod. I was tried both dynamic provisioner (nfs-dynamic-provisioner) and manually created persistence volume. But result is same 

`helm install grafana \
--namespace test \
--set persistence.enabled=true \
--set persistence.size=1Gi \
--set persistence.storageClassName=default \
stable/grafana`

After this command pvc and pv created and bounded. But I think application can not store their data this storage. And I am getting:

`Error from server (BadRequest): container "grafana" in pod "grafana-85f56cf56f-545hd" is waiting to start: PodInitializing`

OS: Centos 7
Helm: v3.2.1
K8s: v1.18.2

**Comment by scottrigby** [comment]
📢 This chart is deprecated: https://github.com/helm/charts/pull/23662
If still applicable, please re-open issues at: https://github.com/grafana/helm-charts
