### ISSUE TITLE
[stable/prometheus-operator] Issue with kubernetes-mixin workload dashboards after recent release

### ISSUE THREAD

**Issue by jessebye** [helm/charts#23447]
**Describe the bug**
After the release of chart version 9.2.2 (which synced a bunch of changes into the grafana dashboards), the "workload" dashboards are not displaying any data:

![image](https://user-images.githubusercontent.com/8467862/89351833-a8c9e280-d667-11ea-8953-a70e93a96222.png)

**Version of Helm and Kubernetes**:
helm 3.x
kubernetes 1.17 (EKS)

**Which chart**:
stable/prometheus-operator

**What happened**:
A few dashboards are not displaying any data.

**What you expected to happen**:
The dashboards should display the correct data.

**How to reproduce it** (as minimally and precisely as possible):
1. Install prometheus-operator 9.2.2 or later
2. Not sure if this is relevant, but we set the Grafana tag to `7.1.1`
3. View a workload dashboard, such as Compute Resources / Workload
4. Observe the empty result.

**Anything else we need to know**:

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
