### ISSUE TITLE
Jenkins/Values.yaml - kuberentes new pod templates are not stable

### ISSUE THREAD

**Issue by Jsred-cloud** [helm/charts#23466]
Using the https://raw.githubusercontent.com/kubernetes/charts/master/stable/jenkins/values.yaml file

jenkins is booting up with Defalt pod template &  container asin the yaml file, when we add more containers in url it will stay until the job gets completed.

How can we have changes persistent in cloud configuration.

any change is required in yaml file.

**Comment by scottrigby** [comment]
📢 `stable/jenkins` has moved to https://github.com/jenkinsci/helm-charts. If still applicable, please reopen the issue there. Thanks!
