### ISSUE TITLE
stable/nginx-ingress `annotations` is not present for https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-configmap.yaml

### ISSUE THREAD

**Issue by abhianand09** [helm/charts#23476]
Hi,

We want to deploy nginx-ingress helm chart through spinnaker. Whatever configs we passed in "config:" field in values.yaml it doesn't show up in nginx-ingress-controller-pod.

Spinnaker always append versions in configmap name (https://github.com/spinnaker/spinnaker/issues/3506) which is causing issue as nginx-ingress-controller is not picking the configmap properly as is name is being changed by spinnaker.

We also tried with below option in values.yaml but that didn't work:
```
"## Override NGINX template
  customTemplate:
    configMapName: "
```

Also when we try to do changes in this helm chart stable/nginx-ingress we couldn't find any suitable place where we could add below in "controller-configmap" which can fix spinnaker issue
```
strategy.spinnaker.io/versioned: false

```

Please add a way to the helm chart so that we can add the annotations easily to "controller-configmap".

Like controller-configmap.yaml can have below field for annotations support:
```
{{- if or .Values.controller.config (or (or .Values.controller.proxySetHeaders .Values.controller.headers) .Values.controller.addHeaders) }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "nginx-ingress.name" . }}
    chart: {{ template "nginx-ingress.chart" . }}
    component: "{{ .Values.controller.name }}"
    heritage: {{ .Release.Service }}
    release: {{ template "nginx-ingress.releaseLabel" . }}
  {{- if .Values.configmap.annotations }}
  annotations:
{{ toYaml .Values.configmap.annotations | indent 4 }}
{{- end }}
  name: {{ template "nginx-ingress.controller.fullname" . }}
 
data:
{{- if .Values.controller.addHeaders }}
  add-headers: {{ .Release.Namespace }}/{{ template "nginx-ingress.fullname" . }}-custom-add-headers
{{- end }}
{{- if or .Values.controller.proxySetHeaders .Values.controller.headers }}
  proxy-set-headers: {{ .Release.Namespace }}/{{ template "nginx-ingress.fullname" . }}-custom-proxy-headers
{{- end }}
{{- if .Values.controller.config }}
{{ toYaml .Values.controller.config | indent 2 }}
{{- end }}
{{- end }}


```

Thanks

**Comment by scottrigby** [comment]
`stable/nginx-ingress` has been deprecated in favor of the upstream `ingress-nginx` repo. See https://github.com/helm/charts/pull/22823. Issues if still applicable can be re-opened there. Thanks 😊
