### ISSUE TITLE
[stable/prometheus-operator] Coredns dashboard failed to retrieve metrics due to the breaking change of coredns metrics naming

### ISSUE THREAD

**Issue by dogzzdogzz** [helm/charts#23474]
**Describe the bug**
Coredns dashboard failed to retrieve metrics of coredns 1.7.0 whose name contains ```count_total``` due to the breaking change of coredns metrics naming

https://github.com/helm/charts/blob/4addcad1ea11d0822ea22a6fb60d52ecf54e9235/stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-coredns.yaml#L85

https://github.com/coredns/coredns/pull/3671

**Version of Helm and Kubernetes**:
prometheus-operator 9.3.1

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
