### ISSUE TITLE
stable/airflow - Include option to use RabbitMQ for Celery Broker

### ISSUE THREAD

**Issue by snevilleshinn** [helm/charts#23481]
**Is your feature request related to a problem? Please describe.**
I would like the option use RabbitMQ as the broker queue instead of having to deploy a new DB server when I already use RabbitMQ.

**Describe the solution you'd like**
Add values section to specify to use RabbitMQ and to provide connection information to an already running RabbitMQ.

**Describe alternatives you've considered**

**Additional context**

**Comment by thesuperzapper** [comment]
We welcome any contributions, since I don't have a RabbitMQ setup, I cant create this.

**Comment by snevilleshinn** [comment]
I am happy to help contribute to this request.  I might need some help getting started as this is will be my first PR with helm charts.
