### ISSUE TITLE
[stable/prometheus-operator] prometheus.prometheusSpec.podMetadata's link is dead

### ISSUE THREAD

**Issue by pmalek-sumo** [helm/charts#23491]
**Describe the bug**
`prometheus.prometheusSpec.podMetadata`'s link - https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#metadata - is dead

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
https://github.com/helm/charts/tree/master/stable/prometheus-operator

**What happened**:
dead link

**What you expected to happen**:
working link

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
