### ISSUE TITLE
[stable/jenkins] Incorrect indentation, blocks normal usage of javaOps

### ISSUE THREAD

**Issue by akaRem** [helm/charts#23492]
**Describe the bug**
Here https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml#L187 
you have a space inside "if" block which introduces extra indentation

if in variables

```
...
  javaOpts: >
    -server -XX:+AlwaysPreTouch    
    -Xloggc:$JENKINS_HOME/gc-%t.log   
    -XX:NumberOfGCLogFiles=5
...
```
then it will create something like 
```
...
            - name: JAVA_OPTS
              value: >
                -server -XX:+AlwaysPreTouch    
                -Xloggc:$JENKINS_HOME/gc-%t.log   
                -XX:NumberOfGCLogFiles=5                
                 -Dcasc.reload.token=$(POD_NAME)
```
which can't be parsed

possible workaround:

```
...
  # THE LEADING SPACE IS IMPORTANT!
  javaOpts: " -server -XX:+AlwaysPreTouch -Xloggc:$JENKINS_HOME/gc-%t.log -XX:NumberOfGCLogFiles=5"
...
```

Which makes it ugly and unmanageable with 15+ java opts

**Version of Helm and Kubernetes**:

**Which chart**:
stable/jenkins starting from 1.8.0

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
provide any java opts

**Anything else we need to know**:

**Comment by scottrigby** [comment]
📢 `stable/jenkins` has moved to https://github.com/jenkinsci/helm-charts. If still applicable, please reopen the issue there. Thanks!
