### ISSUE TITLE
[stable/jenkins] Prometheus Servicemonitor issue with several Helm releases

### ISSUE THREAD

**Issue by truealex81** [helm/charts#23494]
When trying to install 2 helm releases with same name (e.g. jenkins) in different namespaces (e.g. jenkins-dev & jenkins-prod) with values:
  prometheus.enabled: true

Helm fails with message:
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceMonitor "jenkins" in namespace "monitoring" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "jenkins-prod": current value is "jenkins-dev"

Seems that chart should have value like prometheus.serviceMonitorName

**Comment by scottrigby** [comment]
📢 `stable/jenkins` has moved to https://github.com/jenkinsci/helm-charts. If still applicable, please reopen the issue there. Thanks!
