### ISSUE TITLE
stable/prometheus-operator Upgrading from 7.4.0

### ISSUE THREAD

**Issue by txynidakis** [helm/charts#23498]
**Describe the bug**
We're trying to upgrade prometheus-operator from 6.18.0 to the latest. We've been following the upgrade instructions and have successfully upgraded 
**Version of Helm and Kubernetes**:
Kubernetes: EKS V1.15
Helm Version: Client: v2.16.6+gdd2e569
                       Server: v2.16.6+gdd2e569

**Which chart**:
stable/prometheus-operator

**What happened**:
Failed to upgrade from 7.4.0 to 8.0.0

```
Error: 
Error: kind ConfigMap with the name "grafana-prometheus-operato-cluster-total" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
Error: UPGRADE FAILED: kind ConfigMap with the name "grafana-prometheus-operato-cluster-total" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart

$ kubectl -n monitor get configmaps grafana-prometheus-operato-cluster-total
NAME                                       DATA   AGE
grafana-prometheus-operato-cluster-total   1      3m35s
```
We've got other EKS Clusters and the grafana-prometheus-operato-cluster-total doesn't exist, it seems to be introduced in chart version 8.0.0

We've tried to upgrade from 7.4.0 to the latest and come up with the same issue 

**What you expected to happen**:
We could like to upgrade to the latest version successfully 

**How to reproduce it** (as minimally and precisely as possible):
Command that was executed 
`#  helm upgrade grafana stable/prometheus-operator -f prometheus-helm-values.yaml --version 8.0.0`

**Anything else we need to know**:

**Comment by txynidakis** [comment]
Are there any other references that someone can post that I can read up on?

**Comment by gw0** [comment]
The error describes your options. First, check the applied ConfigMap and check what the new version produces with `helm install --dry-run --debug`. If it is the same, just delete the applied ConfigMap, otherwise merge them manually after successfully applying the new version.

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
