### ISSUE TITLE
stable/promethus-operator 

### ISSUE THREAD

**Issue by matty1979** [helm/charts#23505]
**Describe the bug**
Installing prometheus-operator helm chart errors out during installation part, even when including the CRDs as outlined on their repo. 

**Version of Helm and Kubernetes**: `helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}`
`kubectl version 
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"} `

**Which chart**:
stable prometheus-operator

**What happened**:

`Error: failed pre-install: timed out waiting for the condition`
**What you expected to happen**:
Install correctly 

**How to reproduce it** (as minimally and precisely as possible):
`helm install  prom-operator stable/prometheus-operator --set prometheusOperator.createCustomResource=false --namespace monitoring`

**Anything else we need to know**:

**Comment by si458** [comment]
have you checked the monitoring namespace exists? (must be created first with helm 3)
ive just used the chart on my k3s cluster with no issues

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
