### ISSUE TITLE
[prometheus-operator] grafana servicemonitor label is hardcoded to "grafana"

### ISSUE THREAD

**Issue by Morriz** [helm/charts#23513]
this prevents multiple grafana instances deployed with this chart to not have their own servicemonitor....

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
