### ISSUE TITLE
[stable/graylog] Still broken, self-link references incorrect

### ISSUE THREAD

**Issue by gustaveherbst** [helm/charts#23524]
This issue was closed without investigation. This issue still exist:
self-links broken to web-interface #21469

A simple curl will show this...
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="robots" content="noindex, nofollow">
    <meta charset="UTF-8">
    <title>Graylog Web Interface</title>
    <link rel="shortcut icon" href="http://graylog-0.graylog.graylog.svc.cluster.local:9000/assets/favicon.png">

  </head>
  <body>
    <script src="http://graylog-0.graylog.graylog.svc.cluster.local:9000/config.js"></script>

    <script src="http://graylog-0.graylog.graylog.svc.cluster.local:9000/assets/vendor.043dd426065882df527b.js"></script>

    <script src="http://graylog-0.graylog.graylog.svc.cluster.local:9000/assets/polyfill.e9f6bfe0ff08cc899d0f.js"></script>

    <script src="http://graylog-0.graylog.graylog.svc.cluster.local:9000/assets/builtins.e9f6bfe0ff08cc899d0f.js"></script>

    <script src="http://graylog-0.graylog.graylog.svc.cluster.local:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.5f09b13f39f1c48c02c0.js"></script>

    <script src="http://graylog-0.graylog.graylog.svc.cluster.local:9000/assets/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.914a65ab204f2a6480f5.js"></script>

    <script src="http://graylog-0.graylog.graylog.svc.cluster.local:9000/assets/plugin/org.graylog.aws.AWSPlugin/plugin.org.graylog.aws.AWSPlugin.3e8752c43ac22ac69cd1.js"></script>

    <script src="http://graylog-0.graylog.graylog.svc.cluster.local:9000/assets/app.e9f6bfe0ff08cc899d0f.js"></script>

  </body>
</html>

When using either ClusterIP or LoadBalancer (suspect NodePort as well) this will simply not work in a browser for the web interface.

For those that wish to adopt Graylog, it's a no-go as I suspect most will not try to spend hours trying to get this to work.

This issue exist in 3.1, 3.2, 3.3.4, that said it has become obvious no one has looked in to this since the original issue was stated (see top of this issue)

DB

**Comment by DarkBlaez** [comment]
For those that are deploying in to Kubernetes, make sure you set the following in the helm chart. That is the only requirement if exposing via LoadBalancer for the web ui.
 
## Additional environment variables to be added to Graylog pods
  ##
  env: {
    "GRAYLOG_HTTP_EXTERNAL_URI": "http://<your url>:<port>/"  <-- Do not forget the slash
  }

DB
