### ISSUE TITLE
stable/elastic-stack

### ISSUE THREAD

**Issue by melissajenner22** [helm/charts#23526]
**Describe the bug**

**Version of Helm and Kubernetes**:

helm version:

v3.3.0-rc.1

Kubernetes version: 1.16

**Which chart**:

stable/elastic-stack

**What happened**:

I would like to deploy elastic-stack into Kubernetes cluster. I git clone the chart, use default settings. But, I got errors.

1. git clone https://github.com/helm/charts

2. Create namespace

   kubectl create namespace elastic-stack

3. At $HOME/charts

$ helm install elastic-stack stable/elastic-stack --namespace=elastic-stack

Error: found in Chart.yaml, but missing in charts/ directory: elasticsearch, kibana, filebeat, logstash, fluentd, fluent-bit, fluentd-elasticsearch, nginx-ldapauth-proxy, elasticsearch-curator, elasticsearch-exporter

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by scottrigby** [comment]
You need to run the `helm dependency` commands to install the chart's dependencies. See https://helm.sh/docs/helm/helm_dependency/
