### ISSUE TITLE
Rabbitmq-ha's suggested improvements in servicemonitor

### ISSUE THREAD

**Issue by huisebug** [helm/charts#23529]
A kube-prometheus-based rbac should be added to the template, so that servicemonitor can be added to kube-prometheus
Each user uses a different namespace when creating rabbitmq-ha. The default rbac of kube-prometheus is only the rbac of the default, kube-system, and monitoring namespaces.
Reference url: https://github.com/prometheus-operator/kube-prometheus/blob/master/manifests/prometheus-roleSpecificNamespaces.yaml
I think the namespaceSelector: of servicemonitor should not use any: true, because the rbac of kube-prometheus only authorizes the default, kube-system, and monitoring namespaces. You should select the namespace when the user installs

Below are the additional rbac and modified servicemonitor I added

**Comment by huisebug** [comment]
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: rabbitmq-ha
    meta.helm.sh/release-namespace: rabbitmq
  labels:
    app.kubernetes.io/managed-by: Helm
    prometheus: kube-prometheus
  name: rabbitmq-ha
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    port: metrics
  #namespaceSelector:
    #any: true
  namespaceSelector:
    matchNames:
    - rabbitmq
  selector:
    matchLabels:
      app: rabbitmq-ha
      release: rabbitmq-ha

**Comment by huisebug** [comment]
apiVersion: rbac.authorization.k8s.io/v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: prometheus-k8s
    namespace: rabbitmq
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
kind: RoleList

---
apiVersion: rbac.authorization.k8s.io/v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: prometheus-k8s
    namespace: rabbitmq
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-k8s
  subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
kind: RoleBindingList

**Comment by huisebug** [comment]
And the rule is in the label selector of kube-prometheus, there are 2 labels by default,
       prometheus: k8s
       role: alert-rules
The tag in your generated prometheusrule is missing, refer to the address
https://github.com/prometheus-operator/kube-prometheus/blob/master/manifests/prometheus-prometheus.yaml

**Comment by steven-sheehy** [comment]
This chart has been deprecated and is no longer maintained. It is recommended to use the Bitnami maintained [RabbitMQ chart](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq) which has a similar feature set, including high availability. See #23746 and #21103. Can you please close. Thanks!
