### ISSUE TITLE
[stable/prometheus-blackbox-exporter] Wrong configuration default for config.modules.http_2xx.http.valid_http_versions

### ISSUE THREAD

**Issue by leahneukirchen** [helm/charts#23535]
**Describe the bug**

Wrong configuration default for `config.modules.http_2xx.http.valid_http_versions`.

**Version of Helm and Kubernetes**:

version.BuildInfo{Version:"v3.2", GitCommit:"", GitTreeState:"", GoVersion:"go1.14.3"}
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"archive", BuildDate:"2020-07-20T23:19:14Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

`stable/prometheus-blackbox-exporter`

**What happened**:

Probing HTTP/2.0 sites results in failures.

**What you expected to happen**:

Probing HTTP/2.0 sites should work.

**How to reproduce it** (as minimally and precisely as possible):

Run the default setup against any HTTP/2.0 site.

**Anything else we need to know**:

This can be fixed by replacing `valid_http_versions: ["HTTP/1.1", "HTTP/2"]` with `valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]`.
See https://github.com/prometheus/blackbox_exporter/issues/658

**Comment by gkarthiks** [comment]
Hi @leahneukirchen  the `stable/prometheus-blackbox-exporter` chart has been deprecated effectively as per this PR https://github.com/helm/charts/pull/23695 on Sep 5, 2020 and moved to https://github.com/prometheus-community/helm-charts.

Please close this Issue and re-open against the prometheus-community/helm-charts repo. Here's a friendly link for [new issue](https://github.com/prometheus-community/helm-charts/issues/new/choose)

We hope to see you there. 👋
