### ISSUE TITLE
[stable/kube2iam] daemonset not updating after upgrade

### ISSUE THREAD

**Issue by spommerening** [helm/charts#23537]
**Describe the bug**
After upgrading kube2iam using Helm 3 the daemonset was not updating:

```
$ helm history kube2iam -n kube-system
REVISION	UPDATED                 	STATUS    	CHART         	APP VERSION	DESCRIPTION
1       	Mon Mar 30 09:54:03 2020	superseded	kube2iam-2.1.0	0.10.7     	Install complete
2       	Tue Mar 31 17:58:09 2020	superseded	kube2iam-2.1.0	0.10.7     	Upgrade complete
3       	Fri May 29 16:06:48 2020	superseded	kube2iam-2.1.0	0.10.7     	Upgrade complete
4       	Tue Jun 23 17:18:22 2020	superseded	kube2iam-2.1.0	0.10.7     	Upgrade complete
5       	Thu Aug 13 15:23:53 2020	deployed  	kube2iam-2.5.1	0.10.9     	Upgrade complete
```
Wait a couple of minutes (20 minutes should be enough to be sure...) and ... 
```
$ k get daemonset kube2iam -n kube-system
NAMESPACE     NAME                                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR       AGE
kube-system   daemonset.apps/kube2iam                   7         7         7       0            7           specialty=default   136d
```
No pod was updated. 

**Version of Helm and Kubernetes**:
```
$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
$ k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kube2iam-2.5.1

**What happened**:
Pod were not updated after deployment of a new chart version although kube2iam image was bumped from 0.10.7 to 0.10.9.

**What you expected to happen**:
All pods being restarted / updated and new kube2iam version being deployed.

**How to reproduce it** (as minimally and precisely as possible):
Deploy kube2iam-2.1.0 to a cluster and then upgrade to kube2iam-2.5.1

**Anything else we need to know**:
I tried this on 2 different EKS clusters (v1.16.8-eks-e16311 and v1.16.13-eks-2ba888) with different worker instance nodes. Same result. 

I also checked for missing resources, but that wasn't the reason (example of one node, not updating kube2iam):
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests      Limits
  --------                    --------      ------
  cpu                         2200m (56%)   4970m (126%)
  memory                      4676Mi (32%)  5480Mi (37%)
```

A work-around is to delete every old pod manually. They come back online with the new spec.

**Comment by elordahl** [comment]
@spommerening The chart's default `updateStrategy` is **onDelete**, which differs from the kube default of **RollingUpdate**.

From [kube docs](https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-update-strategy):
>With OnDelete update strategy, after you update a DaemonSet template, new DaemonSet pods will only be created when you manually delete old DaemonSet pods

You can see the setting [here](https://github.com/helm/charts/blob/master/stable/kube2iam/values.yaml#L100).  Changing it to `updateStrategy: RollingUpdate` should get you the behavior you're looking for.

**Comment by spommerening** [comment]
@elordahl Thanks a lot! 

Sometimes it helps when you know where you have to look. Thanks to you I learned something new. Very thankful!
