### ISSUE TITLE
stable/prometheus-operator prometheus-node-exporter ignores taints

### ISSUE THREAD

**Issue by kevin-shelaga** [helm/charts#23542]
**Describe the bug**
prometheus-node-exporter ignores taints

**Version of Helm and Kubernetes**:
helm 3, k8s 1.16.3

**Which chart**:
stable/prometheus-operator

**What happened**:

Taints:             node.kubernetes.io/os=windows:NoSchedule
Taints:             search=true:NoSchedule

the above taints are being ignored and the node-exporter is scheduled regardless on nodes, get stuck at container creating

```
prometheus-operator-prometheus-node-exporter-7j6tc        0/1     ContainerCreating   0          7m19s
prometheus-operator-prometheus-node-exporter-88j8f        1/1     Running             0          7m19s
prometheus-operator-prometheus-node-exporter-d5tdw        1/1     Running             0          7m19s
prometheus-operator-prometheus-node-exporter-hfktz        0/1     ContainerCreating   0          7m20s
prometheus-operator-prometheus-node-exporter-km27f        1/1     Running             0          7m19s
prometheus-operator-prometheus-node-exporter-lxdn8        1/1     Running             0          7m19s
prometheus-operator-prometheus-node-exporter-mr6h5        1/1     Running             0          7m19s
```

**What you expected to happen**:
node-exporter should not be scheduled on windows nodes

**How to reproduce it** (as minimally and precisely as possible):
1. setup a cluster with taints
2. helm install prometheus-operator stable/prometheus-operator

**Anything else we need to know**:
nope

edit: updated to reflect all taints

**Comment by VasylSamoilov** [comment]
I can confirm that - seeing exactly the same. node-exporter should respect NoSchedule taint.

**Comment by Extant-1** [comment]
Can also confirm this. The node exporter subchart will add a ":NoSchedule" tolerance by default, meaning it can be scheduled on all nodes regardless of the NoSchedule taint key. This tolerance value cannot be overridden in the Prometheus operator.

**Comment by eNettMattD** [comment]
Same problem for us. We currently can't use the Prometheus operator because we need to add some windows nodes to our cluster.

**Comment by kevin-shelaga** [comment]
@eNettMattD you can get around the windows taint issue by forcing a linux node selector.
This unfortunately doesnt help for linux taints.

```
helm install prometheus-operator stable/prometheus-operator --namespace monitoring --set prometheus-node-exporter.nodeSelector."beta\.kubernetes\.io/os"=linux
```

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!

**Comment by kevin-shelaga** [comment]
https://github.com/prometheus-community/helm-charts/issues/86
