### ISSUE TITLE
[stable/prometheus-adapter] Remove colons from the ClusterRoleBinding resource name

### ISSUE THREAD

**Issue by kofan** [helm/charts#23547]
**Describe the bug**

The helm lint (for Helm 3.3) fails for the `prometheus-adapter` Helm chart because of the invalid resource name that is not compliant with [Kubernetes name requirements](prometheus-adapter). The error is the following:

```
templates/custom-metrics-apiserver-auth-delegator-cluster-role-binding.yaml: object name does not conform to Kubernetes naming requirements: "prometheus-adapter:system:auth-delegator"
```

Particularly, it does not like the colons in the resource name.
Helm uses the following regular expression to check the validity of a resource name:

`^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$`

I believe the name should become: `prometheus-adapter-system-auth-delegator`

**Version of Helm and Kubernetes**:

Helm: **3.3.0**
Kubernetes: **1.18.7**

**Which chart**:

[stable/prometheus-adapter](https://github.com/helm/charts/tree/master/stable/prometheus-adapter)

**What happened**:

`helm lint` command fails

**What you expected to happen**:

`helm lint` command passes

**How to reproduce it** (as minimally and precisely as possible):

Using Helm 3.3 run the following commands:

```bash
helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm pull stable/prometheus-adapter --untar
helm lint stable/prometheus-adapter
```

The output is:

```
==> Linting stable/prometheus-adapter
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/custom-metrics-apiserver-auth-delegator-cluster-role-binding.yaml: object name does not conform to Kubernetes naming requirements: "prometheus-adapter:system:auth-delegator"

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Comment by gkarthiks** [comment]
Hi @kofan   the `stable/prometheus-adapter` chart has been deprecated effectively as per this PR https://github.com/helm/charts/pull/23694 on Sep 5, 2020 and moved to https://github.com/prometheus-community/helm-charts.

Please close this Issue and re-open against the prometheus-community/helm-charts repo. Here's a friendly link for [new issue](https://github.com/prometheus-community/helm-charts/issues/new/choose)

We hope to see you there. 👋

**Comment by kofan** [comment]
Re-opened here: https://github.com/prometheus-community/helm-charts/issues/88
