### ISSUE TITLE
[incubator/zookeeper] plans to migrate zookeeper chart to its own repo?

### ISSUE THREAD

**Issue by pdmars** [helm/charts#23554]
**Is your feature request related to a problem? Please describe.**

Are there any plans to migrate the incubator/zookeeper chart to its own repository to list on Helm Hub once these charts are deprecated and removed? If these charts are going to be migrated I have some fixes I'd like to PR and have considered, if not, I can work on finding another solution. Thanks.

Apologies if this is obvious and I've just missed it, but I've searched around a bit and haven't found any suggestions as to the future of these charts.

**Comment by lwj5** [comment]
Just fyi, bitnami has one that's similar. Not sure if there's any point in maintaining another one

**Comment by pdmars** [comment]
Yeah I've seen those before but these work with ZK 3.4.x and non-beta k8s APIs which is why I've been using them. Hoping either @lachie83 or @kow3ns might be able to provide some guidance for the plans with these charts.

**Comment by hhaslam11** [comment]
Also wondering what the status of this is.
