### ISSUE TITLE
[stable/grafana] Dashboard sidecar stops working after 10 minutes

### ISSUE THREAD

**Issue by PeterGerrard** [helm/charts#23565]
**Describe the bug**
https://github.com/kiwigrid/k8s-sidecar/issues/85
After 10 minutes the dashboard sidecar stops receiving watch notifications

**Version of Helm and Kubernetes**:
Helm version N/A
Kubernetes 1.16.10

**Which chart**:
stable/grafana

**What happened**:
After 10 minutes the dashboard sidecar stops receiving watch notifications

**What you expected to happen**:
The sidecar to always pick up new dashboards

**How to reproduce it** (as minimally and precisely as possible):
See https://github.com/kiwigrid/k8s-sidecar/issues/85

**Comment by scottrigby** [comment]
📢 This chart is deprecated: https://github.com/helm/charts/pull/23662
If still applicable, please re-open issues at: https://github.com/grafana/helm-charts
