### ISSUE TITLE
[stable/jenkins] Migration to new location

### ISSUE THREAD

**Issue by torstenwalter** [helm/charts#23562]
Quote from #21103 as it provides the context:
> Given the stable and incubator [support plan](https://github.com/helm/charts/blob/master/README.md#status-of-the-project) and [Deprecation Timeline](https://github.com/helm/charts/blob/master/README.md#deprecation-timeline), the community (chart OWNERS, organizations, groups or individuals who want to host charts) are moving charts to new Helm repos, and will list these new repos on the [Helm Hub](https://hub.helm.sh/) before stable and incubator are de-listed there. This issue is to help the community track this migration.

I propose to also move the `stable/jenkins` chart to a new location. From a context perspective it would be great if we could move it to https://github.com/jenkinsci, which also hosts the majority of Jenkins plugins. That would make it easier for people to find it and it could also encourage contributions from the community.

As far as I can tell there is no Jenkins chart. There is however a [kubernetes-operator](https://github.com/jenkinsci/kubernetes-operator), which provides similar functionality.

A Kubernetes operator can offer more functionality than a plain helm chart on the other hand installing an operator requires more privileges within a cluster which can make it hard to use in certain environments.

For migrating the chart I suggest the following
- a new repo which tries to keep the git history
- CI pipeline using GitHub actions provided by the helm community so that we could still benefit from chart-testing tool etc.

**Comment by scottrigby** [comment]
As we discussed happy to collaborate as well just ping me 😄

**Comment by torstenwalter** [comment]
@lachie83 @viglesiasce @maorfr @mogaal @wmcdona89 I create a [temporary repository](https://github.com/torstenwalter/helm-charts) for the Jenkins chart similar to what @scottrigby did for [prometheus](https://github.com/scottrigby/prometheus-helm-charts).

For this I cloned this repository and filtered only jenkins chart itself.

`git filter-repo --path-glob 'incubator/jenkins/*' --path-rename incubator/:charts/ --path-glob 'stable/jenkins/*' --path-rename stable/:charts/ --path LICENSE --path code-of-conduct.m`


CI pipeline is using GitHub actions:
- [lint and test](https://github.com/torstenwalter/helm-charts/pull/3/checks?check_run_id=1021537128)
- [release](https://github.com/torstenwalter/helm-charts/runs/1021533480?check_suite_focus=true)

You can test it via:

```
helm repo add jenkinsci-torsten https://torstenwalter.github.io/helm-charts
helm search repo jenkinsci-torsten
```

Next I'll invite you as collaborator and start a discussion in the Jenkins community if it's possible to get a repository in https://github.com/jenkinsci GitHub org.

I'd love to get your feedback on https://github.com/torstenwalter/helm-charts/pull/1, where I added a README and contributing guidelines.
@scottrigby Thank you for what you did for the prometheus charts. You'll notice where this is coming from ;-)

For the code of conduct I pointed to [Jenkins Code of Conduct](https://www.jenkins.io/project/conduct/).

**Comment by torstenwalter** [comment]
[Hosting request](https://issues.jenkins-ci.org/browse/HOSTING-1015) was approved and the repository is now hosted in https://github.com/jenkinsci/helm-charts/. I will delete https://github.com/torstenwalter/helm-charts and create PR in the new location.

**Comment by torstenwalter** [comment]
As we now have a new repository we can track tasks which are required to do the migration in there https://github.com/jenkinsci/helm-charts/projects/2
