### ISSUE TITLE
stable/mongodb-replicaset not able to install with default values

### ISSUE THREAD

**Issue by ashokspeelyaal** [helm/charts#23564]
**Describe the bug**
Not able to install mongodb-replicaset latest chart

`helm install mongodb-test stable/mongodb-replicaset
Error: YAML parse error on mongodb-replicaset/templates/mongodb-statefulset.yaml: error converting YAML to JSON: yaml: line 123: mapping values are not allowed in this context`

**Version of Helm and Kubernetes**:
helm version: 3.2.4
kubernetes: 1.18.5

**Which chart**:

mongodb-replicaset  (3.17.0)

**What happened**:
Getting an error as mentioned about

However, the previous version works 
`helm install mongodb-test --version 3.16.2 stable/mongodb-replicaset`

**What you expected to happen**:
Install replicaset with default count 3

**How to reproduce it** (as minimally and precisely as possible):
helm install mongodb-test stable/mongodb-replicaset

**Anything else we need to know**:

**Comment by toddward** [comment]
Also having this issue.

**Comment by insta-code1** [comment]
```
$ helm install --name my-release stable/mongodb-replicaset

Error: YAML parse error on mongodb-replicaset/templates/mongodb-statefulset.yaml: error converting YAML to JSON: yaml: line 127: mapping values are not allowed in this context
```
I'm also getting this issue.
