### ISSUE TITLE
[stable/nginx-ingress] TF apply error `no ServiceAccount` when upgrading chart version

### ISSUE THREAD

**Issue by gordon-rennie** [helm/charts#23569]
**Describe the bug**

I am experiencing errors when applying an update to an nginx ingress controller, changing chart version from `1.4.0` to `1.26.2` and `1.41.2` --- I've tried both. Error:

`Error: rpc error: code = Unknown desc = no ServiceAccount with the name "public-nginx-ingress-backend" found`

**Version of Helm and Kubernetes**: Helm `2.16.9`, k8s cluster `v1.14.10`

**Which chart**: `stable/nginx-ingress`

**What happened**:

* Initial state: a stable and healthy nginx ingress controller deployed with chart version `1.4.0`. 
* Bumped version to latest `1.41.2`. TF plan was healthy. 
* Errors occurred on TF apply, including [documented pre-1.26 bug](https://github.com/helm/charts/tree/master/stable/nginx-ingress#helm-error-when-upgrading-specclusterip-invalid-value-) `spec.clusterIP: Invalid value: ""`
* Implemented workaround (set `controller.service.omitClusterIP` and `defaultBackend.service.omitClusterIP` to `true`). TF plan still healthy after change.
* One error remains on TF apply, `Error: rpc error: code = Unknown desc = no ServiceAccount with the name "public-nginx-ingress-backend" found`
* Rolled back to `1.4.0` and repeated process with upgrade to `1.26.2` - same `no ServiceAccount` error occurred.

Note: the not-found service account actually exists. A `kubectl describe serviceaccounts public-nginx-ingress-backend` showed it had been created by the chart.

**What you expected to happen**:

`terraform apply` applies successfully and updates nginx ingress chart and resources.

**How to reproduce it** (as minimally and precisely as possible):
* apply chart version 1.4.0
* attempt to apply upgrade to chart version `1.26.2` or `1.41.2`

**Anything else we need to know**:

I have been able to upgrade successfully by setting the flag `force_update = true`, which I understand tears down and recreates all chart resources. However I require a seamless, downtime-free upgrade path for applying to a prod environment.

In case it's relevant, other parameters set in the chart definition include:
```
  name     = "public-nginx-ingress"

  set {
    name  = "controller.minAvailable"
    value = 3
  }

  set {
    name  = "controller.replicaCount"
    value = 5
  }

  values = [
    file("./redacted-dirs/nginx_values.yaml"),
  ]

  set {
    name  = "controller.service.externalTrafficPolicy"
    value = "Local"
  }

  set {
    name  = "controller.service.loadBalancerIP"
    value = google_compute_address.nginx-ip.address
  }

  set {
    name  = "controller.service.omitClusterIP"
    value = true
  }

  set {
    name  = "defaultBackend.service.omitClusterIP"
    value = true
  }

  set {
    name  = "controller.ingressClass"
    value = "nginx-public"
  }

  set {
    name  = "controller.service.enableHttp"
    value = false
  }
```

**Comment by scottrigby** [comment]
`stable/nginx-ingress` has been deprecated in favor of the upstream `ingress-nginx` repo. See https://github.com/helm/charts/pull/22823. Issues if still applicable can be re-opened there. Thanks 😊
