### ISSUE TITLE
[stable/airflow] mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied

### ISSUE THREAD

**Issue by axk7812** [helm/charts#23570]
**Describe the bug**

**Version of Helm and Kubernetes**:
Helm: v3.2.0
Minikube: 1.9.2
Kubernetes: v1.18.0
Docker v19.03.2

**Which chart**:
stable/airflow

**What happened**:
After running Helm install postgres container is throwing "permission" errors as well as other containers because they cannot connect to the container.

Error in postgres container:
> "mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied "

Error in scheduler container: 
> sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
>         Is the server running on host "airflow-postgresql" (10.103.222.26) and accepting
>         TCP/IP connections on port 5432?

**What you expected to happen**:
No errors/no container restarts. There shouldn't be a permissions issue.

**How to reproduce it** (as minimally and precisely as possible):
`helm pull stable/airflow --untar=true`
`helm install airflow airflow/`
`kubectl logs -f <postgres container>`

**Anything else we need to know**:

**Comment by thesuperzapper** [comment]
I expect its because something was already in the namespace you deployed into. 
(Likley a PVC called something like `*postgress*`)

This is why we recommend you create a new namespace for airflow if possible.

**Comment by axk7812** [comment]
@thesuperzapper that looks like the issue. Thanks for pointing out this mistake.

**Comment by jameswynn** [comment]
It sounds like it may be related to an error I recently encoutnered as well. PodSecurityPolicies were interfering with the permissions expected by the container.

https://github.com/bitnami/bitnami-docker-postgresql/issues/242
