### ISSUE TITLE
[stable/airflow] Airflow Flower instance hangs when connecting to Redis instance, flower instance keeps restarting

### ISSUE THREAD

**Issue by sk2991** [helm/charts#23572]
**Describe the bug**
Airflow Flower instance hangs when connecting to Redis instance, flower instance keeps restarting

$ kubectl logs -f airflow-flower-5tddxf32d-5qbzt
*** running flower...
[I 200819 00:42:34 command:136] Visit me at http://0.0.0.0:5555
[I 200819 00:42:34 command:141] Broker: redis://:**@test.redis.cache.windows.net:6379/0
[I 200819 00:42:34 command:144] Registered tasks: 
  ['celery.accumulate',
   'celery.backend_cleanup',
   'celery.chain',
   'celery.chord',
   'celery.chord_unlock',
   'celery.chunks',
   'celery.group',
   'celery.map',
   'celery.starmap']

Any idea on how to debug this issue.

**Version of Helm and Kubernetes**:
Helm: 2.x
Kubernetes: 1.16

**Which chart**:
stable/airflow - 7.3.x

**How to reproduce it** (as minimally and precisely as possible):
Use external Redis instance (Azure Redis cache), update values in values.yaml and redeploy

**Comment by thesuperzapper** [comment]
Can you include the actual error log?

And are you able to connect to the Redis instance (with the connection details you are giving airflow) through your bash terminal?

**Comment by sk2991** [comment]
That's the only error log I see within the flower. 

I'm able to connect using the redis-cli
$ redis-cli -u redis://:***@test.redis.cache.windows.net:6379/1
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
test.redis.cache.windows.net:6379[1]>
