### ISSUE TITLE
[stable/prometheus-operator] Add Alertmanager `cluster.reconnect-timeout` option support

### ISSUE THREAD

**Issue by atmosx** [helm/charts#23575]
When running an alertmanagerHA setup there are two or more alertmanager instances talking to each other to ensure high availability. AlertManager by default caches peer IP address for 6 hours. Since rolling upgrading or pod re-allocation are fairly common in kubernetes environments, the HA setup breaks firing alerts. The `--cluster.reconnect-timeout` flag can be used to reduce cache expiration.

Prometheus operator does not support the `--cluster.reconnect-timeout` flag and we'd love to add it! :D 

**Is your feature request related to a problem? Please describe.**
Our system fires critical alerts when the high availability is broken eating our error budget ^_^

**Describe the solution you'd like**
Adding the `--cluster.reconnect-timeout` flag will allow us to expire the cache to 5m instead of 6h. Then we can adjust the alert to fire if HA is lost for more than 15m for example and sleep at night, as we don't risk breaking the _mean time to detect_ issues.

**Describe alternatives you've considered**
The alternative would be to to modify alertmanager's code, turning cache optional and/or using a reasonable default e.g. 5m.

**Additional context**

The problem has been discussed to some extend here, as the default value doesn't make sense in a dynamic environment: https://github.com/prometheus/alertmanager/issues/2250

**Comment by hwoarang** [comment]
@atmosx this is being addressed on the operator directly https://github.com/prometheus-operator/prometheus-operator/pull/3436 so no need to make any changes to the chart imho.
