### ISSUE TITLE
Can hubot-help be optional in helm-chart?

### ISSUE THREAD

**Issue by Jenniferstrej** [helm/charts#23578]
https://github.com/helm/charts/blob/049de40813a86092104e8968147ed40bd8c9c7fc/stable/hubot/templates/external-scripts-cm.yaml#L17

**Comment by Jenniferstrej** [comment]
At the moment hubot-help gets installed by default. Wouldn't it be better that we had the choice to use it or not? e.g. I am implementing my own help command, without relying on comments. I would like to add hubot-help in externalScripts if I want it.

**Comment by mattfarina** [comment]
@Jenniferstrej it definitely could.

That chart has not been updated in 10 months. When the stable repository is shut down in a few months it will go away if no one has moved it. There is another chart at https://hub.helm.sh/charts/halkeye/hubot but it needs some work (see no README).

If you are using the hubot chart you could make changes and publish it for others to consume and help you with.
