### ISSUE TITLE
Update redis to 4.0.2

### ISSUE THREAD

**Issue by whs** [helm/charts#2359]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
redis

**What happened**:
Redis chart currently install [version 3.2.9](https://github.com/kubernetes/charts/blob/master/stable/redis/values.yaml#L4)

**What you expected to happen**:
Redis chart should install verison 4.0.2

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:

**Comment by prydonius** [comment]
Strange, a PR should have automatically been submitted. /cc @sameersbn @tompizmor

**Comment by sameersbn** [comment]
@whs @prydonius The updates were temporarily disabled for internal testing. We're in the process of restoring the updates. Will keep you updated

**Comment by sameersbn** [comment]
@whs p.s. PR #2380 upgrades to redis 4.0.
