### ISSUE TITLE
[stable/airflow] Airflow authentication using Azure Active Directory

### ISSUE THREAD

**Issue by SilpaSuresh1513** [helm/charts#23594]
I am trying to configure Azure Active Directory to the Apache Airflow instance that I have deployed in my AKS cluster.

I was trying to replace the azure authentication with google authentication via OAuth Authentication method as per the following document:
https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth

Adding the following environment variables in Values.yml added the webserver_config.py file in AIRFLOW_HOME directory within the cluster where I have airflow.cfg file.
    AIRFLOW__WEBSERVER__RBAC: 'True'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'

But I am unable to make any changes in the created webserver_config.py file through environment variables in values.yml file:
https://flask-appbuilder.readthedocs.io/en/latest/config.html?highlight=oauth#using-config-py

Attached the configuration files (airflow.cfg and webserver_config.py):
[airflow_config.txt](https://github.com/helm/charts/files/5108984/airflow_config.txt)
[webserver_config.txt](https://github.com/helm/charts/files/5108986/webserver_config.txt)

I would like to understand the better way to configure Azure AD with Airflow.

**Comment by thesuperzapper** [comment]
See the example in `values.yaml` for the `airflow.extraConfigmapMounts` value.

**Comment by SilpaSuresh1513** [comment]
@thesuperzapper Tried enabling the volume mounts for configmap airflow-webserver-config. But unfortunately unable to change the created webserver_config.py file.
And the changes that I am trying to make provided the environment variables is not being reflected in the pod.

**Comment by thesuperzapper** [comment]
Why do you want to change it?

Just make a `ConfigMap` with the `webserver_config.py` you want, and use `airflow.extraConfigmapMounts` to mount it?

**Comment by SilpaSuresh1513** [comment]
@thesuperzapper, Thanks for the information.

Enabling the volume mount using airflow.extraConfigmapMounts with the environment variable "AIRFLOW__WEBSERVER__RBAC: 'True'" is causing the pod to CrashLoopBackOff error. 

When I removed the environment variables I could get the pod up and running. But the authentication is not happening and the webserver_config.py file in cluster is updated with the values from configmap.

**Comment by thesuperzapper** [comment]
Are you using the `airflow.config` in value.yaml? Or are you trying to mount your own airflow.cfg (that is not supported)

**Comment by SilpaSuresh1513** [comment]
First, deployed the airflow-webserver-config configmap as:
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-webserver-config
  labels:
    app: airflow
data:
  webserver_config.py: |
    import os
    from flask import session
    from flask_appbuilder.security.manager import (
        AUTH_OAUTH
    )
    CSRF_ENABLED = True
    AUTH_TYPE = AUTH_OAUTH
    OAUTH_PROVIDERS = [
        {
            "name": "azure",
            "icon": "fa-windows",
            "token_key": "access_token",
            "remote_app": {
                "client_id": "<redacted>",
                "client_secret": "<redacted>",
                "api_base_url": "https://login.microsoftonline.com/<redacted>/oauth2",
                "client_kwargs": {
                    "scope": "User.read name preferred_username email profile upn",
                    "resource": "<redacted>",
                },
                "request_token_url": None,
                "access_token_url": "https://login.microsoftonline.com/<redacted>/oauth2/token",
                "authorize_url": "https://login.microsoftonline.com/<redacted>/oauth2/authorize",
            },
        },
    ]
Secondly, updated airflow section in values.yml as:
airflow:
  image:
    repository: apache/airflow
    tag: 1.10.10-python3.6
    pullPolicy: IfNotPresent
    pullSecret: ""

  executor: KubernetesExecutor

  fernetKey: <redacted>

  config:
  ## Security
  AIRFLOW__CORE__SECURE_MODE: "True"
  AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF: ""
  AIRFLOW__WEBSERVER__BASE_URL: http://localhost:8080/
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  AIRFLOW__WEBSERVER__RBAC: "True"

  podAnnotations: {}

  extraEnv: []

  extraConfigmapMounts:
    - name: airflow-webserver-config
      mountPath: /opt/airflow/webserver_config.py
      configMap: airflow-webserver-config
      readOnly: false
      subPath: webserver_config.py

  extraContainers: []

Updated the web section as:
web:
  extraPipPackages: 
    - "apache-airflow[google_auth]==1.10.10"

Not able to figure out where did I went wrong.

Appreciate your help.

**Comment by thesuperzapper** [comment]
@SilpaSuresh1513 this is not an issue with the chart, try using a local version of airflow until you manage to get your `webserver_config.py` to be correct. 

It probably has a syntax error.

**Comment by SilpaSuresh1513** [comment]
@thesuperzapper, thanks for the note. The issue was with the webserver_config.py file.
It worked for me.
The webserver_config.py file is used as:
import os
from airflow.configuration import conf
from flask_appbuilder.security.manager import AUTH_OAUTH
basedir = os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir))
SQLALCHEMY_DATABASE_URI = conf.get("core", "SQL_ALCHEMY_CONN")
CSRF_ENABLED = True
AUTH_TYPE = AUTH_OAUTH
AUTH_USER_REGISTRATION_ROLE = "Admin"
OAUTH_PROVIDERS = [
{
"name": "azure",
"icon": "fa-user-o",
"token_key": "access_token",
"remote_app": {
"consumer_key": "<redacted>",
"consumer_secret": "<redacted>",
"base_url": "https://login.microsoftonline.com/<redacted>/oauth2",
"request_token_params": {
"scope": "User.read name preferred_username email profile",
"resource": "",
},
"request_token_url": None,
"access_token_url": "https://login.microsoftonline.com/<redacted>/oauth2/token",
"authorize_url": "https://login.microsoftonline.com/<redacted>/oauth2/authorize",
},  
},
]

**Comment by cyeruban** [comment]
Hi @thesuperzapper @SilpaSuresh1513 

I have the same requirement to configure an Apachie Airflow with Azure AD. I am unable to reach you from git. Please let.me.know how.we can contact. I tried from all.sources, still unable to complete this action

**Comment by thesuperzapper** [comment]
@cyeruban please raise this issue on the new repo for the airflow helm chart (the `helm/charts` repo is deprecated):
https://github.com/airflow-helm/charts/tree/main/charts/airflow

Also, you can find a description of how to mount a `webserver_config.py` in the README new repo:
https://github.com/airflow-helm/charts/tree/main/charts/airflow#docs-airflow---configmaps
