### ISSUE TITLE
[stable/etcd-operator] Upgrading from 0.4.3 to 0.5.0 breaks cluster

### ISSUE THREAD

**Issue by bspaans** [helm/charts#2360]
**Version of Helm and Kubernetes**:

Helm 2.6.1
Kubernetes 1.6.10

**Which chart**:

stable/etcd-operator-0.5.0

**What happened**:

When upgrading from 0.4.3 to 0.5.0: 

```
UPGRADE FAILED: apiVersion "etcd.database.coreos.com/v1beta2" in etcd-operator/templates/cluster.yaml is not available
```

Trying to reinstall 0.4.3:

```
UPGRADE FAILED: Deployment.apps "etcd-operator-etcd-operator" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"etcd-operator-etcd-operator", "chart":"etcd-operator-0.4.3", "heritage":"Tiller", "release":"etcd-operator"}: `selector` does not match template `labels`
```

**What you expected to happen**:

I didn't expect to break my cluster, but at the root this is my mistake for not pinning the version. Some improvements that could help debug and avoid this issue:

- Output what version the "latest" chart resolves to (couldn't find this in my CI output)
- Document upgrade path when introducing a breaking change
- Release notes for charts

**How to reproduce it** (as minimally and precisely as possible):

(untested) something like this:

```
helm install --name deployment-name stable/etcd-operator --version 0.4.3
# enable the cluster (probably not necessary)
helm upgrade deployment-name stable/etcd-operator --version 0.4.3 --set cluster.enabled=true
helm upgrade deployment-name stable/etcd-operator --version 0.5.0
```

**Comment by bspaans** [comment]
I think the problem is that #1795 updated the chart based on the latest etcd-operator (0.6.x) docs (https://github.com/coreos/etcd-operator/blob/master/doc/user/upgrade/upgrade_guide.md), but the etcd-operator used is still at 0.3.3 in values.yaml.

**Comment by Markbnj** [comment]
We ran into this same issue upgrading to the 0.5.0 version of the chart in order to migrate to custom resource definitions. The workaround for us was to pass `--set image.tag=v.0.6.1` (or whatever version you like > 0.5.0) to helm during installation.

**Comment by ScottMorris** [comment]
I'm seeing this issue when trying to use tag v0.7.0.

**Comment by gopinatht** [comment]
Hey Guys,

Is there any guidance on this issue? I am continuing to see this `0.7.3`. What is the undelying cause of this problem?
