### ISSUE TITLE
[stable/airflow] Kubernetes executor is not being able to execute tasks

### ISSUE THREAD

**Issue by hussainsaify** [helm/charts#23605]
Hi Team,

I have installed the latest helm chart with the Kubernetes executor as the default executor. After configuring the necessary configurations, tasks are launching, but they are failing with below error-

Helm Chart Version- 7.5.0
Kubernetes- AWS EKS(1.15.11)

```
[2020-08-24 12:50:17,787] {__init__.py:51} INFO - Using executor LocalExecutor
[2020-08-24 12:50:17,788] {dagbag.py:396} INFO - Filling up the DagBag from /opt/airflow/dags/repo/test-kube-exporter.py
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 37, in <module>
    args.func(args)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 523, in run
    dag = get_dag(args)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 149, in get_dag
    'parse.'.format(args.dag_id))
airflow.exceptions.AirflowException: dag_id could not be found: kubernetes_etl_sample. Either the dag did not exist or it failed to parse.
```
Below are the properties I am configuring in values.yaml for Kubernetes executor

```
        AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
        AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "1.10.10-python3.6"
        AIRFLOW__KUBERNETES__NAMESPACE: "airflow-etl"
        AIRFLOW__KUBERNETES__KUBE_CLIENT_REQUEST_ARGS: '{\"_request_timeout\":[60,60]}'
        AIRFLOW__KUBERNETES__GIT_REPO: "git@github.com:*************/airflow-etl.git"
        AIRFLOW__KUBERNETES__GIT_BRANCH: "master"
        AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "/opt/airflow/dags"
        AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: "repo/"
        AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
        AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE: "False"
        AIRFLOW__KUBERNETES__GIT_SSH_KEY_SECRET_NAME: "airflow-secrets"
        AIRFLOW__KUBERNETES__GIT_SSH_KNOWN_HOSTS_CONFIGMAP_NAME: "airflow-git-knownhosts"
        AIRFLOW__KUBERNETES__GIT_SYNC_ROOT: "/dags"
        AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "False"
        AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
        AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
```

Sample DAG-

```
from airflow import DAG
from datetime import datetime, timedelta
from airflow.contrib.operators.kubernetes_pod_operator import KubernetesPodOperator
from airflow.operators.dummy_operator import DummyOperator
from airflow.utils.dates import days_ago

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': days_ago(0),
    'retries': 1,
    'retry_delay': timedelta(minutes=5)
}

dag = DAG(
    'kubernetes_etl_sample', default_args=default_args, schedule_interval=None)


start = DummyOperator(task_id='run_this_first', dag=dag)

passing = KubernetesPodOperator(namespace='airflow-etl',
                          image="ubuntu:16.04",
                          cmds=["bash", "-cx"],
                          arguments=["echo", "10"],
                          in_cluster=True,      
                          labels={"foo": "bar"},
                          name="passing-test",
                          task_id="passing-task",
                          get_logs=True,
                          dag=dag
                          )

passing.set_upstream(start)
```
Can you please look into this and suggest a proper solution?

Note- It is working fine with CeleryExecutor.

Thanks,
Hussain

**Comment by hussainsaify** [comment]
Ok, I found the issue. My worker image doesn't have the appropriate pip packages to run the dags. Is there a way to alter the command for the worker to first install python dependencies and then run the airflow task in the case of Kubernetes executor?

Similar to this-

`echo 'waiting 60s...' && sleep 60 && echo 'installing requirements...' && mkdir -p /usr/local/airflow/.local/bin && export PATH=/usr/local/airflow/.local/bin:$PATH && /usr/local/scripts/install-requirements.sh && airflow run Test run_this_first 2020-08-25T09:32:53.057962+00:00 --local --pool default_pool -sd /usr/local/airflow/dags/repo/test_dag.py'`

**Comment by nguyenkien1402** [comment]
Hi @hussainsaify , did you solve the issue yet? I have the same issue too

**Comment by rsotogar** [comment]
Hi @hussainsaify @nguyenkien1402 did you guys solve this? I'm having the same issue.

**Comment by hussainsaify** [comment]
@rsotogar I was able to fix that, there were 2 issues on my end, 

1.) Some packages were not installed that I was using so I baked it into the image.

2.) It was not able to find the dags in the correct path so I corrected the path.

**Comment by rsotogar** [comment]
I'm using git-sync via SSH into my Github repo. When a worker pod starts, a container that clones the dags from the repo fails to access them for some reason, but the dags were synced correctly in the other pods (scheduler, webserver, etc). Not sure what the error is, I assumed the packages were installed correctly otherwise the DAGs would not have been imported...

**Comment by hussainsaify** [comment]
The dags should be present on worker pods as well otherwise it will fail. Once your repo clone issue is fixed, this would start working

**Comment by rsotogar** [comment]
These are the logs from the dag-clone container on the scheduler (same for webserver):

I1223 11:08:46.575618      19 main.go:694]  "level"=0 "msg"="cloning repo"  "origin"="git@github.com:zizooboats/dwh.git" "path"="/dags"

I1223 11:09:47.037014      19 main.go:586]  "level"=0 "msg"="syncing git"  "hash"="3fe309abb6cd3a50f43ba5c9354d98b47453f008" "rev"="HEAD"

I1223 11:09:55.660337      19 main.go:607]  "level"=0 "msg"="adding worktree"  "branch"="origin/airflow-testing" "path"="/dags/rev-3fe309abb6cd3a50f43ba5c9354d98b47453f008"

I1223 11:09:56.186915      19 main.go:630]  "level"=0 "msg"="reset worktree to hash"  "hash"="3fe309abb6cd3a50f43ba5c9354d98b47453f008" "path"="/dags/rev-3fe309abb6cd3a50f43ba5c9354d98b47453f008"

I1223 11:09:56.187045      19 main.go:635]  "level"=0 "msg"="updating submodules"

These are the logs when a worker pod is initialized and the same container runs:

I1223 11:36:30.684897      11 main.go:430]  "level"=0 "msg"="starting up"  "args"=["/git-sync"] "pid"=11
I1223 11:36:30.687604      11 main.go:694]  "level"=0 "msg"="cloning repo"  
"origin"="git@github.com:zizooboats/dwh.git" "path"="/dags"

E1223 11:41:09.147067      11 main.go:455]  "msg"="too many failures, aborting" "error"="Run(git clone --no-checkout -b airflow-testing --depth 1 git@github.com:zizooboats/dwh.git /dags): context deadline exceeded: { stdout: \"\", stderr: \"Cloning into '/dags'...\\nfatal: early EOF\\n\" }"  "failCount"=0

It makes no sense that the repo can be accessed in scheduler and webserver but not in worker pods. I also had similar errors yesterday in scheduler, but was fixed after a while...
