### ISSUE TITLE
[stable/prometheus-operator] Chart download checksum mismatch

### ISSUE THREAD

**Issue by GMartinez-Sisti** [helm/charts#23618]
**Describe the bug**
Hi!

I’m trying to get some confidence while downloading charts in CI pipelines by validating the checksum of the downloaded chart file. In theory this should be a no brainer, but I’m getting different checksums on every few downloads. The download is being performed from the same source (https://kubernetes-charts.storage.googleapis.com) so it was supposed to be the same.

I know this might not be related to this chart, but I'm experiencing this issue with it.

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
stable/prometheus-operator

**What happened**:
`helm dependency update` ocasionally gets a chart file with different checksum. I'd say 1/10 times the file is different. This happens the most when downloading from a London IP.

**What you expected to happen**:
The checksum needs to be the same every time, otherwise the chart might've be tampered with.

**How to reproduce it** (as minimally and precisely as possible):
Examples of different content for same download. Please check etag/x-goog-hash:
```sh
> curl -I https://kubernetes-charts.storage.googleapis.com/prometheus-operator-9.3.1.tgz
HTTP/2 200
x-guploader-uploadid: AAANsUmA1ljWnKkGkm2IV1DmmkSerP7MuJ0Uca1rSbcfiz8NYql3JTuZOhpLfQHw1nO6jU-eKN5x6h2nLgnxzAsWftO0suy6BA
expires: Mon, 24 Aug 2020 10:23:37 GMT
date: Mon, 24 Aug 2020 09:23:37 GMT
last-modified: Mon, 24 Aug 2020 08:59:43 GMT
etag: "14b108aad8486915b0afb89da88e60a6"
x-goog-generation: 1598259583787258
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 313703
x-goog-meta-goog-reserved-file-mtime: 1598259468
content-type: application/x-tar
x-goog-hash: crc32c=V+b+tw==
x-goog-hash: md5=FLEIqthIaRWwr7idqI5gpg==
x-goog-storage-class: STANDARD
accept-ranges: bytes
content-length: 313703
server: UploadServer
cache-control: public, max-age=3600
age: 1314
```
```sh
> curl -I https://kubernetes-charts.storage.googleapis.com/prometheus-operator-9.3.1.tgz
HTTP/2 200
x-guploader-uploadid: AAANsUkj3Gg_Wtf5ItBrU33WG_m2jV9zpeMnjcvaB2Z3SRR365ayl9aE8iaZGenjZltLG1OH9DnhuDSX0_PjwzwmFNBe2vWAwA
expires: Mon, 24 Aug 2020 10:45:32 GMT
date: Mon, 24 Aug 2020 09:45:32 GMT
cache-control: public, max-age=3600
last-modified: Mon, 24 Aug 2020 09:29:19 GMT
etag: "d057a83b5ddafe8319b21eeb5ab42220"
x-goog-generation: 1598261359992938
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 313617
x-goog-meta-goog-reserved-file-mtime: 1598261248
content-type: application/x-tar
x-goog-hash: crc32c=Wu0yPg==
x-goog-hash: md5=0FeoO13a/oMZsh7rWrQiIA==
x-goog-storage-class: STANDARD
accept-ranges: bytes
content-length: 313617
server: UploadServer
```
**Anything else we need to know**:
Thanks

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
