### ISSUE TITLE
[stable/rabbitmq-ha] Changelog for Charts

### ISSUE THREAD

**Issue by maunzCache** [helm/charts#23637]
**Is your feature request related to a problem? Please describe.**
My coworker installed a very old Snapshot version of the chart and i may want to upgrade it. I have no way to find out what changed in the chart due to missing changelogs. I could crawl through the git commits but that is not very productive.

**Describe the solution you'd like**
Well, manage a Changelog which describes updates in the chart.

**Describe alternatives you've considered**
See description of the problem.

**Additional context**
None.

**Comment by steven-sheehy** [comment]
This chart has been deprecated and is no longer maintained. It is recommended to use the Bitnami maintained [RabbitMQ chart](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq) which has a similar feature set, including high availability. See #23746 and #21103. Can you please close. Thanks!
