### ISSUE TITLE
[stable/rabbitmq-ha] changing definitions (users,vhosts,permissions) is not working when upgrading

### ISSUE THREAD

**Issue by SpikePy** [helm/charts#23639]
**Describe the bug**
I want to change my configuration of users/vhosts/permissions on an already running rabbitmq-ha. If I change them in my **values.yml** and apply it with **helm upgrade** they don't change the configuration of rabbitmq. I have to uninstall the chart first and reinstall it to apply my changes.

**Version of Helm and Kubernetes**:
helm: 3.3.0
k8s: 1.17.9

**Which chart**:
stable/rabbitmq-ha

**What happened**:
configuration change is not applied

**What you expected to happen**:
changed configuration is applied when doing an **helm upgrade**

**How to reproduce it** (as minimally and precisely as possible):
1. install stable/rabbitmq-ha helm chart
2. add a vhost via values.yml `definitions.vhosts: '{"name": "test"}'`
3. helm upgrade with values.yml
4. check if the changes are applied

**Comment by gboor** [comment]
I just ran into this as well and I can see that the secret with the definitions IS updated, however, that does nothing for the live running pods. The definitions.json needs to be pushed on startup.

Destroying all the pods also works; they get restarted with the new definitions. Still not ideal.

It would be best if the definitions can be live applied, but that would require changes to RabbitMQ itself. As for this helm chart; it is not too difficult to cycle pods when a configmap or secret changes, maybe that is a good intermediate solution.

**Comment by steven-sheehy** [comment]
This chart has been deprecated and is no longer maintained. It is recommended to use the Bitnami maintained [RabbitMQ chart](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq) which has a similar feature set, including high availability. See #23746 and #21103. Can you please close. Thanks!
