### ISSUE TITLE
[stable/prometheus] prometheus-server continually restarting after SIGTERM

### ISSUE THREAD

**Issue by ellenemerson** [helm/charts#23649]
**Describe the bug**
Prometheus server container continually restarts after receiving SIGTERM.  Container will be up for a few minutes, receive SIGTERM, go down for a few minutes, restart, repeat.

**Version of Helm and Kubernetes**:
Helm: 
```
helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
```
Kubernetes: 
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"fdba62c353cc548995bbe730321f64176e4f6e4b", GitTreeState:"clean", BuildDate:"2020-04-08T18:15:19Z", GoVersion:"go1.13.8 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/prometheus

**What happened**:
The prometheus-server container regularly restarts after receiving SIGTERM and prometheus is unavailable for several minutes at a time.

**What you expected to happen**:
Prometheus to continue running while my workflows are running.

**How to reproduce it** (as minimally and precisely as possible):
Happened after installing helm using homebrew (`brew install helm`), then prometheus (`helm install prometheus stable/prometheus`).  Installation and initial setup works fine, but restarting problems occur several minutes after installation.  

**Anything else we need to know**:
I've tried other suggestions mentioned in other GitHub issues (increasing memory allocated to prometheus-server, increasing initial delay for liveness/readiness checks) and so far nothing has helped.  

My apologies if this issue is with my own cluster configuration rather than the helm chart, but any suggestions would be greatly appreciated.

Thanks!

**Comment by gkarthiks** [comment]
Hi @ellenemerson  the `stable/prometheus` chart has been deprecated effectively as per this PR https://github.com/helm/charts/pull/23692 on Sep 5, 2020 and moved to https://github.com/prometheus-community/helm-charts.

Please close this Issue and re-open against the prometheus-community/helm-charts repo. Here's a friendly link for [new issue](https://github.com/prometheus-community/helm-charts/issues/new/choose)

We hope to see you there. 👋

**Comment by ellenemerson** [comment]
As instructed, closing this issue in favor of https://github.com/prometheus-community/helm-charts/issues/70.
