### ISSUE TITLE
[stable/grafana] Can't use the sidecar to import a dashboard by gnetId

### ISSUE THREAD

**Issue by cyrilcros** [helm/charts#23650]
**Describe the bug**
After I add a configMap with gnetId /revision /datasource, the matching dashboard is not present.

_ Or I don't know the right syntax, the README glosses over the configuration section for the dashboard sidecar [here](https://github.com/helm/charts/blob/master/stable/grafana/README.md#sidecar-for-dashboards) _

**Version of Helm and Kubernetes**:
1.18.8 server version, Helm v3 (from Argocd 1.7.1)

**Which chart**:
Grafana 5.5.5

**What happened**:

No dashboard import, but the side car grafana-sc-dashboard container loads the configMap.

**What you expected to happen**:

The dashboard is added.

**How to reproduce it** (as minimally and precisely as possible):
I enabled the sidecar for datasources / dashboards, all other sidecar options are default and there is no other dashboard provider. The datasource is correctly configured via the sidecar.

I add a configMap like this:

`
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-node-exporter
  namespace: monitoring
  labels: 
    grafana_dashboard: "1"   
data:
  prometheus-node-exporter: | 
   gnetId: 1860
   datasource: Prometheus
   revision: 21 
`

**Comment by thiagonache** [comment]
I had the same issue. After reading resources.py, sidecar.py, and helm templates I believe gnetId dashboards only work with non-sidecar configuration.

**Comment by scottrigby** [comment]
📢 This chart is deprecated: https://github.com/helm/charts/pull/23662
If still applicable, please re-open issues at: https://github.com/grafana/helm-charts
