### ISSUE TITLE
Ingress issue 

### ISSUE THREAD

**Issue by akai257** [helm/charts#23680]
I was able to expose the URL using path 
While it is returing it is not going to path - it is going back to server.example.com instead of server.example.com/path1

**Comment by EricLemieux** [comment]
Can you fill out the bug report template so it's easier to replicate the problem you are having

```
Describe the bug A clear and concise description of what the bug is.

Version of Helm and Kubernetes:

Which chart:

What happened:

What you expected to happen:

How to reproduce it (as minimally and precisely as possible):

Anything else we need to know:
```
