### ISSUE TITLE
[stable/prometheus-cloudwatch-exporter] serviceMonitor.enabled=true doesn't works

### ISSUE THREAD

**Issue by hoonahn** [helm/charts#23711]
**Describe the bug**

I'm trying to deploy [stable/prometheus-cloudwatch-exporter](https://github.com/helm/charts/tree/master/stable/prometheus-cloudwatch-exporter) through helm chart.

However helm does not generates serviceMonitor when using next commands.

```
helm install my-cloudwatch-exporter stable/prometheus-cloudwatch-exporter --set serviceMonitor.enabled=true
```

nor when using `helm template`

```
helm template my-cloudwatch-exporter stable/prometheus-cloudwatch-exporter --set serviceMonitor.enabled=true
```

**Version of Helm and Kubernetes**:

helm version: v3.2.3
kubectl version: v1.18.6

**Which chart**:

[stable/prometheus-cloudwatch-exporter](https://github.com/helm/charts/tree/master/stable/prometheus-cloudwatch-exporter)

**What happened**:

serviceMonitor is not deployed with enable option.

**What you expected to happen**:

serviceMonitor should be deployed when installation or generated when using template cmd.

**How to reproduce it** (as minimally and precisely as possible):

```
helm install my-cloudwatch-exporter stable/prometheus-cloudwatch-exporter --set serviceMonitor.enabled=true
helm template my-cloudwatch-exporter stable/prometheus-cloudwatch-exporter --set serviceMonitor.enabled=true
```

**Anything else we need to know**:

Upper options works with stable/prometheus-blackbox-exporter.

**Comment by gkarthiks** [comment]
Hi @hoonahn   the `stable/prometheus-cloudwatch-exporter` chart has been deprecated effectively as per this PR https://github.com/helm/charts/pull/23696 on Sep 5, 2020 and moved to https://github.com/prometheus-community/helm-charts.

Please close this Issue and re-open against the prometheus-community/helm-charts repo. Here's a friendly link for [new issue](https://github.com/prometheus-community/helm-charts/issues/new/choose)

We hope to see you there. 👋
