### ISSUE TITLE
additionalScrapeConfigs not working 

### ISSUE THREAD

**Issue by KR411-prog** [helm/charts#23718]
I am trying to add a new label called "teamname" to the metrics scraped on kube-state-metrics.So my objective is to add teamname as an additional label to the metrics scraped at kube-state-metrics so in the PrometheusRule we can set the specific team name on the label.
So tried with the below config.But I dont see this new label being added to the kube-state-metrics in Prometheus Service Discovery page.Please let me know whats the correct method to do this.
Objective: is to add new label named "teamname" so based upon the metrics,the team name has to be set.

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: kube-state-metrics
      relabel_configs:
      - separator: ;
        regex: (.*)
        target_label: teamname
        replacement: "myteam"
        action: replace

Prometheus Operator chart version: 9.3.1

Insert image tag or Git SHA here

quay.io/coreos/prometheus-operator:v0.38.1

Kubernetes version information:

kubectl version 1.15

Kubernetes cluster kind: EKS

**Comment by gkarthiks** [comment]
Hi @KR411-prog   the `stable/prometheus` chart has been deprecated effectively as per this PR https://github.com/helm/charts/pull/23692 on Sep 5, 2020 and moved to https://github.com/prometheus-community/helm-charts.

Please close this Issue and re-open against the prometheus-community/helm-charts repo. Here's a friendly link for [new issue](https://github.com/prometheus-community/helm-charts/issues/new/choose)

We hope to see you there. 👋

**Comment by KR411-prog** [comment]
Thankyou..I have raised issue in the link you specified.https://github.com/prometheus-community/helm-charts/issues/62
