### ISSUE TITLE
OrientDB ingress refers to non exising service

### ISSUE THREAD

**Issue by johannes-darms** [helm/charts#23712]
https://github.com/helm/charts/blob/99805df25da220c379ad609fcb7cf20e5e0d4fc0/incubator/orientdb/templates/ingress.yaml#L36

There are no services with `{{ $fullName }}` registerd only `{{ $fullName }}-svc` and `{{ $fullName }}-headless` are there (cf. https://github.com/helm/charts/blob/99805df25da220c379ad609fcb7cf20e5e0d4fc0/incubator/orientdb/templates/service.yaml).

**Comment by brucetony** [comment]
Would love for this pull request to go through soon!
