### ISSUE TITLE
[stable/airflow] issue : can support custom plugins folder

### ISSUE THREAD

**Issue by superbeer** [helm/charts#23727]
can support custom plugins folder ?
 example follow url
https://airflow.apache.org/docs/stable/plugins.html

**Comment by thesuperzapper** [comment]
You can use the value: `airflow.extraConfigmapMounts` with a custom `ConfigMap` in your Kubernetes cluster.

See `values.yaml` for an example.

**Comment by superbeer** [comment]
please more detail to config file webserver_config.py for custom plugins

**Comment by thesuperzapper** [comment]
@superbeer you can do something very similar to: https://github.com/helm/charts/tree/master/stable/airflow#docs-airflow---configmaps

Except you will need to use `/opt/airflow/plugins/MY_PLUGIN.py` as the `mountPath`.

**Comment by thesuperzapper** [comment]
@superbeer If this is still an issue, please raise it on the new repo: https://github.com/airflow-helm/charts/tree/main/charts/airflow

The `helm/charts` repo is being archived soon.

**Comment by superbeer** [comment]
i'm re install . it is work for custom plugins . It is do not specific  config . thank you
