### ISSUE TITLE
Collect PR review rules for documentation and automation

### ISSUE THREAD

**Issue by mattfarina** [helm/charts#2373]
When a chart PR is reviewed there are common items reviewers check for. I would like to collect those to document and try to automate them. Can we get a list?

/cc @unguiculus @viglesiasce

**Comment by unguiculus** [comment]
You should start looking at best practices.

https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

One of the first things I look at is resource names and standard labels.

**Comment by viglesiasce** [comment]
For me:

1. Version bump for updates to existing charts
2. Chart.yaml has a github ID for name (in transition)
3. Images are all configurable
4. NOTES.txt is present and accurate/useful

Also:
https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements

**Comment by prydonius** [comment]
There are a couple of things we can add to Helm lint, and other things that are more specific to k8s/charts, so we should figure out what fits where. Off the top of my head:

Linter:
- naming conventions for chart names, resources, namespaced template names etc.
- semver versions (I believe this is already implemented)
- YAML formatting (e.g. 2 space indentation)
- Images are all configurable
- Chart.yaml fields (should fail on "strict"): home, sources, icons, appVersion

k8s/charts specific:
- ensure version bump
- GitHub ID for maintainer name
- NOTES.txt present
- check that requirements.yaml only references charts in the stable repo (or also incubator only if the chart itself is in incubator)

Not sure:
- Labels - whilst the chart best practices define a set of standard labels, I'm not sure that the linter should necessarily enforce this. I think we have the choice here of whether it's a "strict" linter rule (Info/Warning) or whether we only implement this as a check for k8s/charts only.

Things that probably still need to be manual:
- Version bump appropriate
- NOTES.txt accurate/useful

**Comment by mattfarina** [comment]
@unguiculus @viglesiasce @prydonius For charts in the stable directory, should their chart version be > 0. Note, the semver spec makes note of versions starting with 0.x.y at http://semver.org/#spec-item-4.

**Comment by unguiculus** [comment]
Maybe we should work on a clear definition for stable and incubator first.

**Comment by unguiculus** [comment]
Now that https://github.com/kubernetes/helm/pull/2845 has been merged, I'd suggest to check for namespaced templates for new charts once Helm 2.7 is out. However, `helm lint` is not configurable. What about making it configurable with linting rules as other linters do? This would allow us to apply different rules for new and for existing charts.

**Comment by mattfarina** [comment]
@unguiculus isn't everything in the stable directory supposed to be stable? And stable in SemVer gets a `>=1.0.0` version. Are there things in stable that aren't considered stable.

I understand a lack of formal definition. But, from the perspective of a consumer... stable is stable.

**Comment by mattfarina** [comment]
Folks, any thoughts on #2528? I could automate some of those.
