### ISSUE TITLE
Question: Complete removal of old stable repo?

### ISSUE THREAD

**Issue by mitsos1os** [helm/charts#23742]
Hi everyone,

I opened this issue to just get a clarification regarding the stable repo deprecation.

In case I am using the latest available version of the charts in the stable repo for some deployments and do not want to use any upgrades from the new migrated repositories, will I still be able to use them after final deprecation of stable repo? This includes manually adding the repo to Helm 3 helm repo add stable https://kubernetes-charts.storage.googleapis.com

Or will this also stop being available and I have to switch to the new repos no matter what?

Thanks!

**Comment by abatilo** [comment]
I'd love some clarification as well if the googleapis link will still work or will that go away? The wording isn't exactly clear.

**Comment by abatilo** [comment]
Maybe @scottrigby knows? Looks like he's the author for the issue that's tracking all of the other charts.

**Comment by mitsos1os** [comment]
After some searching around, in Helm depreciation [docs](https://helm.sh/blog/helm-v2-deprecation-timeline/#helm) in the section about November 13 changes, the Google buckets for stable and incubator repos are mentioned under **To be removed** column....  So maybe this means that they will be actually deleted?

**Comment by bacongobbler** [comment]
Yes. The cloud storage bucket hosting the stable and incubator repositories will be removed in November.

Further clarification: the operating costs of the stable and incubator repositories are a significant contributing factor. It has come to the point that it is too cost-prohibitive to host.

helm/charts will still be available as a got repository, and vendors of many of these repositories have agreed to host their charts at their own chart repositories.

See also https://github.com/helm/charts#status-of-the-project.

**Comment by mitsos1os** [comment]
I see...
@bacongobbler thanks for the clarification...!
