### ISSUE TITLE
[stable/prometheus-operator] manifest_sorter.go:192: info: skipping unknown hook: "crd-install"

### ISSUE THREAD

**Issue by pratikbin** [helm/charts#23745]
**Describe the bug**
Deployment of Prometheus-operator become successful but still getting warning/error of `manifest_sorter.go:192: info: skipping unknown hook: "crd-install"`

**Version of Helm and Kubernetes**:
Helm Version
`version.BuildInfo{Version:"v3.3.0", GitCommit:"***", GitTreeState:"dirty", GoVersion:"go1.14.7"}`

Kubectl Version
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"***", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8+k3s1", GitCommit:"***", GitTreeState:"clean", BuildDate:"2020-08-14T20:42:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

k3s Version
`k3s version v1.18.8+k3s1 (6b595318)`

**Which chart**:
Stable release of prometheus-operator version 9.3.1

**What happened**:
Getting Warning/error of `manifest_sorter.go:192: info: skipping unknown hook: "crd-install"`

```
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
NAME: prometheus-operator
LAST DEPLOYED: Thu Sep 10 18:49:12 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
The Prometheus Operator has been installed. Check its status by running:
  kubectl --namespace default get pods -l "release=prometheus-operator"

Visit https://github.com/coreos/prometheus-operator for instructions on how
to create & configure Alertmanager and Prometheus instances using the Operator.
```
i know it's successfully installed but cant figure out which crd is not installing
```
NAME                                    CREATED AT
addons.k3s.cattle.io                    2020-08-30T14:00:47Z
helmcharts.helm.cattle.io               2020-08-30T14:00:47Z
aplogconfs.appprotect.f5.com            2020-09-02T11:25:37Z
appolicies.appprotect.f5.com            2020-09-02T11:25:37Z
globalconfigurations.k8s.nginx.org      2020-09-02T11:25:37Z
policies.k8s.nginx.org                  2020-09-02T11:25:37Z
transportservers.k8s.nginx.org          2020-09-02T11:25:37Z
virtualservers.k8s.nginx.org            2020-09-02T11:25:37Z
virtualserverroutes.k8s.nginx.org       2020-09-02T11:25:37Z
alertmanagers.monitoring.coreos.com     2020-09-09T12:49:09Z
thanosrulers.monitoring.coreos.com      2020-09-09T12:49:10Z
prometheuses.monitoring.coreos.com      2020-09-09T12:49:09Z
servicemonitors.monitoring.coreos.com   2020-09-09T12:49:09Z
podmonitors.monitoring.coreos.com       2020-09-09T12:49:09Z
prometheusrules.monitoring.coreos.com   2020-09-09T12:49:09Z
```

**What you expected to happen**:
install chart without any warnings/errors. and can't figure out which crd is not installing?

**How to reproduce it** (as minimally and precisely as possible):
I am using k3s on my Majaro 20.0.3-gnome-200606 Arch Linux on i5-6200U with 8GB RAM. and `export KUBECONFIG=/etc/rancher/k3s/k3s.yaml` cause using k3s and kubectl so its same after KUBECONFIG env.

**Anything else we need to know**:
i don't think of anything else

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated in the `stable` repo.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
