### ISSUE TITLE
istio should have auto-inject flag

### ISSUE THREAD

**Issue by Morriz** [helm/charts#2376]
the istio project provides for auto-inject of sidecars, but the chart does not use this...

**Comment by gyliu513** [comment]
Duplicate with https://github.com/kubernetes/charts/issues/1909

/cc @lachie83

**Comment by gyliu513** [comment]
@Morriz can you please help close this one as https://github.com/kubernetes/charts/issues/1909 has been closed and now you can use the auto-inject feature of istio now.

**Comment by Morriz** [comment]
Yes. Tnx!
