### ISSUE TITLE
Not able to deploy grafana using latest helm charts

### ISSUE THREAD

**Issue by mkeerthy** [helm/charts#23782]
**Describe the bug**

**Version of Helm and Kubernetes**:
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-658790", GitCommit:"6587900c2b7bd83f0937204894202c93a1ecfb5f", GitTreeState:"clean", BuildDate:"2020-07-16T01:29:42Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
helm grafana

**What happened**:
While deploying kube-prometheus-stack helm charts,  getting template error as follows

helm install --debug kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring -f ./helm/kube-prometheus-stack/values.yaml --set prometheusOperator.createCustomResource=false

client.go:108: [debug] creating 1 resource(s)
install.go:141: [debug] CRD alertmanagers.monitoring.coreos.com is already present. Skipping.
client.go:108: [debug] creating 1 resource(s)
install.go:141: [debug] CRD podmonitors.monitoring.coreos.com is already present. Skipping.
client.go:108: [debug] creating 1 resource(s)
install.go:141: [debug] CRD prometheuses.monitoring.coreos.com is already present. Skipping.
client.go:108: [debug] creating 1 resource(s)
install.go:141: [debug] CRD prometheusrules.monitoring.coreos.com is already present. Skipping.
client.go:108: [debug] creating 1 resource(s)
install.go:141: [debug] CRD servicemonitors.monitoring.coreos.com is already present. Skipping.
client.go:108: [debug] creating 1 resource(s)
install.go:141: [debug] CRD thanosrulers.monitoring.coreos.com is already present. Skipping.
coalesce.go:196: warning: cannot overwrite table with non table for image (map[repository:kiwigrid/k8s-sidecar sha: tag:0.1.151])
coalesce.go:196: warning: cannot overwrite table with non table for image (map[repository:kiwigrid/k8s-sidecar sha: tag:0.1.151])
coalesce.go:196: warning: cannot overwrite table with non table for image (map[repository:kiwigrid/k8s-sidecar sha: tag:0.1.151])
Error: template: kube-prometheus-stack/charts/grafana/templates/deployment.yaml:46:10: executing "kube-prometheus-stack/charts/grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error calling include: template: kube-prometheus-stack/charts/grafana/templates/_pod.tpl:75:18: executing "grafana.pod" at <.Values.sidecar.image.sha>: can't evaluate field sha in type interface {}
helm.go:94: [debug] template: kube-prometheus-stack/charts/grafana/templates/deployment.yaml:46:10: executing "kube-prometheus-stack/charts/grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error calling include: template: kube-prometheus-stack/charts/grafana/templates/_pod.tpl:75:18: executing "grafana.pod" at <.Values.sidecar.image.sha>: can't evaluate field sha in type interface {}

**What you expected to happen**:
should deploy successfully in k8s

**How to reproduce it** (as minimally and precisely as possible):
download latest helm charts from github and try to deploy to k8s using helm install

**Anything else we need to know**:

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated in the `stable` repo.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!
