### ISSUE TITLE
[stable/chart] add activeDeadlineSeconds to backup cron job spec

### ISSUE THREAD

**Issue by dex80526** [helm/charts#23791]
There is no way to specify "activeDeadlineSeconds" for the backup cronjob. Without that parameter specified, some backup jobs are never got marked complete or failed, hence no new scheduled job is got kicked off.

**Is your feature request related to a problem? Please describe.**
Backup jobs could be going on (active) forever, and no new scheduled jobs are kicked off.

**Describe the solution you'd like**
Add "activeDeadlineSeconds" to jenkins-backup-cronjob.yaml

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated in the `stable` repo.

Further development has moved to [jenkinsci/helm-charts](https://github.com/jenkinsci/helm-charts).

If applicable, please re-open this issue there. Thanks!
