### ISSUE TITLE
mysql dump restore has ERROR, "You can't use locks with log tables"

### ISSUE THREAD

**Issue by ganchandrasekaran** [helm/charts#23819]
**Describe the bug**
Backing up Galera MariaDB:
When I take backup and restore manually using the command below command it SUCCEEDS
On my UNIX machine.. 
$ mysqldump --single-transaction --all-databases -h 10.251.205.11 -P 32741 -u root  > ssinside_common.sql
$ mysql -u root --host 10.251.205.11 --port 30188 -p < ssinside_common.sql

However, when same is done inside the mysqldump chart using the CronJob or EXEC into the container with same command below, it FAILS
$ mysqldump --single-transaction --all-databases -h 10.251.205.11 -P 32741 -u root  > ssinside_common.sql
$ mysql -u root --host 10.251.205.11 --port 30188 -p < ssinside_common.sql
ERROR 1556 (HY000) at line 1208: You can't use locks with log tables

Based on bug report this should fix the error: https://bugs.mysql.com/bug.php?id=37748
I tried using below flags with mysqldump, but still same error:
--lock-tables=0 --skip-lock-tables

Reason:
One reason might be the difference in the Version  of Mysqldump:

Manual UNIX machine Version: (NO ERROR)
$ mysqldump --version
mysqldump  Ver 10.16 Distrib 10.3.10-MariaDB, for Linux (x86_64)
$ mysql --version
mysql  Ver 15.1 Distrib 10.3.10-MariaDB, for Linux (x86_64) using  EditLine wrapper

Another docker container with high version: (NO ERROR)
$ mysqldump --version
mysqldump  Ver 10.17 Distrib 10.4.12-MariaDB, for Linux (x86_64)
$ mysql --version
mysql  Ver 15.1 Distrib 10.4.12-MariaDB, for Linux (x86_64) using readline 5.1

mysqlDump chart container version: (ERROR)
$ mysqldump --version
mysqldump  Ver 10.16 Distrib 10.2.15-MariaDB, for Linux (x86_64)
$ mysql --version
mysql  Ver 15.1 Distrib 10.2.15-MariaDB, for Linux (x86_64) using readline 5.1

**Which chart**:
charts/stable/mysqldump/

**Anything else we need to know**:
Bumping the version up can fix the issue. 
Not sure why the, skip-lock-tables flag wont work.

**Comment by m0rtalis** [comment]
@ganchandrasekaran I'm having the same issue. Did you manage to fix it?

**Comment by claudioabreu** [comment]
I had the same problem. As a workaround, I suggest you remove the LOCK/UNLOCK commands from the SQL file:

cat ssinside_common.sql | grep -v LOCK | grep -v UNLOCK > ssinside_common_NoLock.sql

Then you can import the ssinside_common_NoLock.sql with no errors.

**Comment by ganchandrasekaran** [comment]
> @ganchandrasekaran I'm having the same issue. Did you manage to fix it?

In my case, I had changed the version of mysqldump and started working with it.
