### ISSUE TITLE
[incubator/druid] Adding Kerberos credentials for Kafka and HDFS to druid charts

### ISSUE THREAD

**Issue by jpmantuano** [helm/charts#23815]
Trying to add kerberos authentication to incubator/druid;
 - for the druid hdfs storage to access HDFS
 - for the kafka indexing service to read from kafka

I can only see that it has google cloud storage configured. Any chance someone is working to add kerberos authentication details?

**Comment by AWaterColorPen** [comment]
@jpmantuano cloud you provide some detailed examples about using kerberos to access hdfs or kafka?

**Comment by jpmantuano** [comment]
@AWaterColorPen I want to use HDFS as the DeepStorage for druid historical node, and source data from Kafka

I was already to test druid out to use hdfs as a deepstorage using a basic HDFS cluster by changing variables below on the values.yml
```
  druid_storage_type: hdfs
  druid_storage_storageDirectory: hdfs://192.168.122.1:9000/var/druid/data
```
But the environment I'll be putting druid on for the longer term will have a secured HDFS and Kafka clusters.
Right now I working on having druid connect to a Kerberized HDFS following this [documentation](https://druid.apache.org/docs/latest/tutorials/tutorial-kerberos-hadoop.html) and working out how to map the instructions to the helm chart.

**Comment by AWaterColorPen** [comment]
@jpmantuano for my understanding, we have to support the following features.
1. [copying the required configurations files over to Druid conf folders](https://druid.apache.org/docs/latest/tutorials/tutorial-kerberos-hadoop.html#hadoop-setup)
2. place the customer files, example `/etc/security/keytabs/hdfs.headless.keyta`, into container.
```
druid.hadoop.security.kerberos.principal=hdfs-test@EXAMPLE.IO
druid.hadoop.security.kerberos.keytab=/etc/security/keytabs/hdfs.headless.keytab
```
