### ISSUE TITLE
[stable/fluentd] New chart repo location?

### ISSUE THREAD

**Issue by acarsercan** [helm/charts#23824]
Hi,

Does stable fluentd helm chart have a new repository location? 

Regards

**Comment by EricLemieux** [comment]
Based on https://github.com/helm/charts/issues/21235#issuecomment-699705923 it appears that stable/fluentd is still in the process of being migrated to https://github.com/fluent/helm-charts.
The bitnami chart is also another option https://github.com/bitnami/charts/tree/master/bitnami/fluentd
