### ISSUE TITLE
Graylog (stable/graylog) volume error

### ISSUE THREAD

**Issue by ghost** [helm/charts#23833]
When following the example on https://hub.helm.sh/charts/stable/graylog/1.6.10, the containers remain in pending state. We do have K8s 1.19.2, Helm v3.3.4 and Longhorn v1.0.2 as the default storage provider.

When I check the log of the graylog-0 container I do see these errors:

Warning  FailedScheduling    5m20s                  default-scheduler        0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling    5m20s                  default-scheduler        0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled           5m4s                   default-scheduler        Successfully assigned graylog/graylog-0 to k8s-facility01-dta-worker01
  Warning  FailedAttachVolume  5m4s (x2 over 5m5s)    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-ee6d5ab4-1607-4c83-8e34-88cb9ca3ec02" : rpc error: code = Internal desc = Action [attach] not available on [&{pvc-ee6d5ab4-1607-4c83-8e34-88cb9ca3ec02 volume map[self:http://longhorn-backend:9500/v1/volumes/pvc-ee6d5ab4-1607-4c83-8e34-88cb9ca3ec02] map[]}]
  Warning  FailedAttachVolume  4m49s (x2 over 4m57s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-ee6d5ab4-1607-4c83-8e34-88cb9ca3ec02" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to attach volume pvc-ee6d5ab4-1607-4c83-8e34-88cb9ca3ec02 to k8s-facility01-dta-worker01: volume pvc-ee6d5ab4-1607-4c83-8e34-88cb9ca3ec02 not scheduled, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes/pvc-ee6d5ab4-1607-4c83-8e34-88cb9ca3ec02?action=attach]
  Warning  FailedMount         3m2s                   kubelet                  Unable to attach or mount volumes: unmounted volumes=[journal], unattached volumes=[kubectl graylog-token-v78w9 config entrypoint journal]: timed out waiting for the condition
  Warning  FailedAttachVolume  55s (x6 over 5m3s)     attachdetach-controller  AttachVolume.Attach failed for volume "pvc-ee6d5ab4-1607-4c83-8e34-88cb9ca3ec02" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [detail=, message=unable to attach volume pvc-ee6d5ab4-1607-4c83-8e34-88cb9ca3ec02 to k8s-facility01-dta-worker01: volume pvc-ee6d5ab4-1607-4c83-8e34-88cb9ca3ec02 not scheduled, code=Server Error] from [http://longhorn-backend:9500/v1/volumes/pvc-ee6d5ab4-1607-4c83-8e34-88cb9ca3ec02?action=attach]
  Warning  FailedMount         48s                    kubelet                  Unable to attach or mount volumes: unmounted volumes=[journal], unattached volumes=[entrypoint journal kubectl graylog-token-v78w9 config]: timed out waiting for the condition

How can I get this up and running?

**Comment by justinmchase** [comment]
what was your solution?

**Comment by ws-way** [comment]
I just reinstalled the cluster and the problem was gone.
