### ISSUE TITLE
nginx-ingress does not apply values.yaml

### ISSUE THREAD

**Issue by ghost** [helm/charts#2383]
**Is this a request for help?**:
Help
---

**Which chart**:

nginx-ingress

**What happened**:

When  I create the chart nginx-ingress and pass my custom values so this values does not applies when the chart are deployed.

helm install -f values.yaml stable/nginx-ingress

I modify namespace, ports, etc and values are not applied

**What you expected to happen**:

Apply my custom values

**How to reproduce it** (as minimally and precisely as possible):
helm install -f values.yaml stable/nginx-ingress

**Anything else we need to know**:

**Comment by onlydole** [comment]
Hello @felixPG - Are you able to share your `values.yaml` file or do you get any error message when trying to install that chart?

**Comment by ghost** [comment]
Hi @onlydole , was a mistake for me, that not pass the correct format like param,subparam=vale
thanks

**Comment by onlydole** [comment]
Oh shoot! Glad to hear you have it working now, felixPG! 👍
