### ISSUE TITLE
[stable/stackdriver-exporter] request for migration

### ISSUE THREAD

**Issue by torstenwalter** [helm/charts#23859]
**Is your feature request related to a problem? Please describe.**

This repository will be deprecated soon (#21103). It would be a pity of charts in here could no longer be downloaded.
I therefor suggest to find a new home for `stable/stackdriver-exporter` chart.

As it's a prometheus exporter the most fitting repository from my point of view would be https://github.com/prometheus-community/helm-charts.

To support in the migration I create a PR, which transfers the history of the existing chart over there https://github.com/prometheus-community/helm-charts/pull/183

@apenney Would that migration be ok for you? Would you like to continue maintaining that chart?

@monotek mentioned that they have a stackdriver-exporter chart as well. Could make sense to join forces and combine both into one chart.

@monotek @apenney I would leave that discussion up to you.

**Comment by monotek** [comment]
I was tralking about: https://github.com/kiwigrid/helm-charts/tree/master/charts/stackdriver-exporter

@rpahli is the maintainer.

He would support you to maintain the chart if its moved, beeing a co maintainer, no matter if you merge both charts or use the one from stable as base for the new one.

**Comment by torstenwalter** [comment]
Chart was moved to https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-stackdriver-exporter
