### ISSUE TITLE
[stable/elasticsearch-exporter] chart migration

### ISSUE THREAD

**Issue by torstenwalter** [helm/charts#23860]
**Is your feature request related to a problem? Please describe.**

This repository will be deprecated soon (#21103). It would be a pity of charts in here could no longer be downloaded.
I therefor suggest to find a new home for `stable/elasticsearch-exporter chart.

As it's a prometheus exporter the most fitting repository from my point of view would be https://github.com/prometheus-community/helm-charts.

To support in the migration I create a PR, which transfers the history of the existing chart over there https://github.com/prometheus-community/helm-charts/pull/183

@desaintmartin @svenmueller @caarlos0 Would that migration be ok for you? Would you like to continue maintaining that chart over there?

**Comment by desaintmartin** [comment]
Great idea. I approve and i'll continue to maintain it there.

**Comment by caarlos0** [comment]
Awesome! I'll continue to maintain there as well, no problem.

**Comment by torstenwalter** [comment]
Chart was moved to https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter
