### ISSUE TITLE
[stable/prometheus-pushgateway] Support for specifying priorityClassName

### ISSUE THREAD

**Issue by AshutoshNirkhe** [helm/charts#23899]
**Is your feature request related to a problem? Please describe.**
Currently we can't set priority for the prometheus pushgateway deployment which sometimes caus issues in scheduling pushgateway pod.

**Describe the solution you'd like**
We should have a way to specify the priority for the pod by means of 'priorityClassName' for stable/prometheus-pushgateway deployment file. So it should be configurable via values.yaml file.

**Describe alternatives you've considered**

**Additional context**

**Comment by Deusald** [comment]
Hello, I see that this request is almost done. When it will be merged to master?
