### ISSUE TITLE
[stable/jaeger-operator] Add support for specifying priorityClassName in deployment

### ISSUE THREAD

**Issue by AshutoshNirkhe** [helm/charts#23908]
**Is your feature request related to a problem? Please describe.**
Because of some other high priority pods, this pod won't get scheduled. So we need to bump priority for this pod.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Add support to specify the priorityClassName in values.yaml and in deployment template file.

**Additional context**

**Comment by blame19** [comment]
I have PR solving this issue here: https://github.com/helm/charts/pull/24488
Can a reviewer give a look?

**Comment by blame19** [comment]
Review is still needed.
