### ISSUE TITLE
stable/airflow support Flower oauth configuration

### ISSUE THREAD

**Issue by caddac** [helm/charts#23918]
I would like the flower installation to support google oauth as described in https://flower.readthedocs.io/en/latest/auth.html#google-oauth-2-0

**Is your feature request related to a problem? Please describe.**
I need to be able to secure the flower UI, or else I can't publish it at all

**Additional context**
I think all this needs is a flag on the startup command to support `--auth=.*@example\.com` as the other keys can be set via env vars

@thesuperzapper

**Comment by thesuperzapper** [comment]
Do you want to contribute this feature?

**Comment by caddac** [comment]
I'll try to take a stab at it
