### ISSUE TITLE
[stable/airflow] Support for custom operators

### ISSUE THREAD

**Issue by kishore25kumar** [helm/charts#23939]
Airflow provides a way to add custom operators which can be added to specific folder location. Currently there is a way to mount a volume into airflow where DAGs can be added which are picked up by airflow. Similar behavior is not supported for custom operators or hooks

**Is your feature request related to a problem? Please describe.**
There is no support to add custom operators which are picked up by airflow

**Describe the solution you'd like**
Provide a way to mount a volume where custom operators can be added, and airflow can be used in DAGs.

**Describe alternatives you've considered**

**Additional context**

**Comment by thesuperzapper** [comment]
@kishore25kumar If this is still an issue, please raise it on the new repo: https://github.com/airflow-helm/charts/tree/main/charts/airflow

The `helm/charts` repo is being archived soon.
