### ISSUE TITLE
Update redis-ha chart image

### ISSUE THREAD

**Issue by monotykamary** [helm/charts#2394]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
redis-ha

**What happened**:
gcr.io/google_containers/redis:v1 refers to redis `2.8.19`

**What you expected to happen**:
A later version like `4.0.2`

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:
When using official docker images of redis `3.2.11` and `4.0.2`, the chart will fail to load the `sentinel` container of StatefulSet pod `redis-master-0`. Logs for the `sentinel` container in StatefulSet pod `redis-master-0` holds:

```

1:C 04 Oct 12:27:19.102 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
--
  | 1:C 04 Oct 12:27:19.102 # Redis version=4.0.2, bits=64, commit=00000000, modified=0, pid=1, just started
  | 1:C 04 Oct 12:27:19.102 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
  | 1:M 04 Oct 12:27:19.103 # Creating Server TCP listening socket *:6379: bind: Address in use


```

**Comment by tuananh** [comment]
What's difference between google/redis image and official redis image?

**Comment by smileisak** [comment]
@tuananh look at my comment in #2527

**Comment by tuananh** [comment]
@smileisak will you update the chart to latest redis please?

**Comment by smileisak** [comment]
@tuananh i've added a PR (https://github.com/kubernetes/charts/pull/2543)
