### ISSUE TITLE
Charts Repo Deprecation Plan and Timeline

### ISSUE THREAD

**Issue by mattfarina** [helm/charts#23944]
On Nov 13, 2020 this git repository will be deprecated and obsolete. The Helm repositories it generates will become archives rather than actively maintained.

Here is a proposed timeline and events...

- Monday Nov 2nd all non-deprecated charts get a message in the README and notes stating that it will become an archive on Nov 13th. The message will point people to the Artifact Hub to find a replacement. The message should remind people that the deprecation window was first announced in 2019.
- Friday Nov 6th the stable and incubator charts repos are removed from the Artifact Hub. This provides one working week of the archive messages showing up on the Artifact Hub for people to notice.
- Friday Nov 13th CI is turned off so that no new updates can happen to the charts, OWNERS files are removed, and k8s CI is removed (this enabled the OWNERS files to work).
- After the 13th we work through the open issues and PRs to point people to constructive next steps and actions.
- After the 13th we work out the plan to mark the repo as archived in GitHub. Note, we have to figure out where the list of charts maintainers lives after the fact as we maintain multiple repos.
- At some point (after the holidays) the charts repo is archived.

Note, it is intentional to not mark charts as deprecated so that they can be found and used in an archive state.

**Comment by viglesiasce** [comment]
Adding this issue as a reference for the tasks needed to migrate folks from the existing URLs to the new ones in a graceful manner:
https://github.com/helm/charts/issues/23850

**Comment by kachkaev** [comment]
This repo is such an important part of the CNCF history. Imagine how many human hours it has saved over its lifespan!

Goodbye Helm 2 charts.

![5Lwi](https://user-images.githubusercontent.com/608862/99115735-cbff1900-25ea-11eb-8582-22b6e6d26ae4.gif)

Long live Helm 3 and the [Artifact Hub](https://artifacthub.io) 🚀
