### ISSUE TITLE
Improve documentation about 'Status of the Project' section

### ISSUE THREAD

**Issue by hatharom** [helm/charts#23963]
I have read through it multiple times, but still unclear what will happen on 13.Nov.

`"this GitHub project has begun transition to a 1 year maintenance mode"`
So this github project will cease, it is clear.

`"move charts to new Helm repos, and list these new repos on the Helm Hub before stable and incubator are de-listed."`
If only the git repo will be obsolete, then the  'https://kubernetes-charts.storage.googleapis.com/' repo will still work. Isn't it?

Or the repo will be ceased also on Nov13?

So if at the helm hub someone lists 'https://kubernetes-charts.storage.googleapis.com/' as his repo ,then it won't work anymore after Nov13?

For example take this:
https://artifacthub.io/packages/helm/helm-stable/mysql
It shows the above mentioned  URL as his repo. Will it work or not?

**Comment by hatharom** [comment]
https://github.com/helm/charts/issues/23205

**Comment by fliphess** [comment]
would love to have an answer to these questions... The readme is quite vague about this....

**Comment by fliphess** [comment]
it's not stale it's idle......
