### ISSUE TITLE
[stable/metabase] Deprecation timeline

### ISSUE THREAD

**Issue by tijmenstor** [helm/charts#23974]
**Is your feature request related to a problem? Please describe.**
As the helm/charts repository is coming close to its deprecation soon, might it be time to move the Metabase chart to its own repository soon? I was not sure if there were already plans for this, but I would love to help with this if possible (as I actively use Metabase and would learn a lot from it).

**Describe the solution you'd like**
The repository should be moved to its own repository, where it should be maintained and served from.

**Describe alternatives you've considered**
n.a.

**Additional context**
n.a.

**Comment by pmint93** [comment]
@Tijmen34 
As I know there is no plan for now metabase/metabase#13581
To continue to work with metabase chart, we may host it by our own
