### ISSUE TITLE
Sentry user-create-job never start

### ISSUE THREAD

**Issue by makcumka2000** [helm/charts#2401]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm - v2.6.1, 
Kubernates: Major:"1", Minor:"7", GitVersion:"v1.7.0" (I am using minikube)

**Which chart**:
https://github.com/kubernetes/charts/tree/master/stable/sentry

**What happened**:
When I try to install it:
 helm install --name sentry --wait stable/sentry  --set service.type="NodePort"
After some time I got an error:
"Error: timed out waiting for the condition"
When I look in dashboard, I see that db init job complete, but user-create-jon did not launch.
When I try to access to Sentry via browser with default User - I can not do it(wrong login or password).
Sentry be accessible after I connect to web pod:
kubectl exec -it <podname> bash
And exec sentry createuser command

**What you expected to happen**:
user-create-job completed and I can login to sentry via browser with admin@sentry.local and password from kubernates secret

**How to reproduce it** (as minimally and precisely as possible):
helm install --name sentry --wait stable/sentry  --set service.type="NodePort"
I try it on window 7 and debian. The same problem.

**Anything else we need to know**:

**Comment by makcumka2000** [comment]
I resolved my problem. Because sentry db migrations exec so long, the second job(for create user) never launch, because helm drop with "Error: timed out waiting for the condition".
Decision: launch helm install command with flag --timeout=600 (10 minutes for example)
my working version:
helm install --name sentry --wait stable/sentry --timeout=600 --set service.type="NodePort"

**Comment by tendou996** [comment]
I met same issue but for db-init job, actually I think it not start, the migration command not run and I saw error when query in postgres pods. Anyone have the same problem ???
And my node have 2 cores and 4GB ram, i think it enough resource to run migration.
