### ISSUE TITLE
[incubator/druid] Remove HPA on MM, BUG

### ISSUE THREAD

**Issue by AdheipSingh** [helm/charts#24025]
**Describe the bug**
1. If a user implements these MM autoscaling supported in charts they'll  end up screwing cluster
2. Their are issues opened in apache druid, plus druid-operator, reviewed PMC  who are working on these.
3. Scaling down MM will end up killing tasks. 

Kindly dive deep into these issues
1. https://github.com/apache/druid/issues/8801#issuecomment-664020630
2. https://github.com/apache/druid/issues/8801#issuecomment-664648399
3.. https://github.com/druid-io/druid-operator/issues/85
4. https://www.slideshare.net/Hadoop_Summit/apache-druid-auto-scaleoutin-for-streaming-data-ingestion-on-kubernetes

 
Kindly
**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
- scale down will end up killing tasks

**Comment by AWaterColorPen** [comment]
@AdheipSingh thanks for mentioning the autoscaling issues.
1. For my understanding, `scale down will end up killing tasks` is a BUG of druid MM on k8s. **It is not a BUG of druid helm chart !!!**
2. For the users who can stand batch tasks restarting, HPA is a good feature now.
3. **HPA on MM is disabled by default**, if a user don't want it. It is not necessary to remove it from `druid helm chart`

BTW please rename the title with [incubator/druid]

**Comment by AdheipSingh** [comment]
What i meant is that is  **not the right way of running MM using HPA** ( their is 100% possibilty of a running ingestion task getting killed when HPA scales down pod, regardless of the user using whatever metric ), since it was an issue which was under the notice of druid PMC and has a lot of important discussions and in depth too, i felt that adding MM HPA in these helm charts might confuse or mislead the user believing that he can scale MM using HPA.

I just wanted to highlight, rest is your call whether you keep or remove or doc these :)

**Comment by AWaterColorPen** [comment]
Yes, some running ingestion task will get killed when HPA scaling-down. 

We would like to apply the solution better than `statefulset with HPA`. But there is no other charts using `CloneSet` and `CloneSet` is no a k8s native feature.  It is hard to use the `CloneSet` solution.
