### ISSUE TITLE
stable/airflow kubernetes executor worker pods are not having additional volume mounts configured in values.yaml

### ISSUE THREAD

**Issue by jineshmathewt** [helm/charts#24020]
**Describe the bug**
kubernetes executor worker pods are not mounting additional volume mounts configured in values.yaml

Below is my values.yaml configuration for Kubernetes executor and additional volume mounts. I want my executor worker pods to share a PVC for data file access. airflow scheduler pod and airflow webserver pods are mounting the PVC correctly but worker pods are not mounting the PVC. As per documentation in values.yaml, extraVolumeMounts and extraVolumes are for the **web/scheduler/worker** Pods

values.yaml
------------
executor: KubernetesExecutor

config: { "AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM": "dagpvc","AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY": "airflowjava", "AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG": "1.0", "AIRFLOW__KUBERNETES__DELETE_WORKER_PODS": "True", "AIRFLOW__API__AUTH_BACKEND" : "airflow.api.auth.backend.default" }

extraVolumeMounts: [ { "name" : "batchdata", "mountPath" : "/tmp/data" } ]
extraVolumes: [ {"name" : "batchdata", "persistentVolumeClaim" : {"claimName": "batchpvc"} } ]

**Version of Helm and Kubernetes**:
Helm: v3.3.4
K8: 1.18

**Which chart**:
stable/airflow

**What happened**:
worker pods are not having extra volume and volume mounts specified in values.yaml

**What you expected to happen**:
Each worker pod should have the volume mount 

**How to reproduce it** (as minimally and precisely as possible):
Create a PVC and PV
Set executor as kubernetesexecutor
Modify values.yaml to have extra volume and volumemount as mentioned
Check worker pod to see volume mount while running

**Anything else we need to know**:
No

**Comment by thesuperzapper** [comment]
can you please post the YAML of the running worker pods, using something like: `kubectl get Pod/XXXXX --namespace YOUR_NAMESPACE -o yaml`

**Comment by jineshmathewt** [comment]
Thanks for the reply. Below is an executor pod YAML

ubuntu@master-node:~$ k get pod kubexecutorbranchtask-09007d64c0ca4d449ba357d8ba234b58 -o yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-11-06T18:36:11Z"
  labels:
    airflow-worker: 529ff5e1-fd26-4b7c-8e31-19af74d8345e
    airflow_version: 1.10.12
    dag_id: kubexecutor
    execution_date: 2020-11-06T18_36_04.231910_plus_00_00
    kubernetes_executor: "True"
    task_id: branch_task
    try_number: "1"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:airflow-worker: {}
          f:airflow_version: {}
          f:dag_id: {}
          f:execution_date: {}
          f:kubernetes_executor: {}
          f:task_id: {}
          f:try_number: {}
      f:spec:
        f:affinity: {}
        f:containers:
          k:{"name":"base"}:
            .: {}
            f:command: {}
            f:env:
              .: {}
              k:{"name":"AIRFLOW__CORE__EXECUTOR"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"AIRFLOW__CORE__SQL_ALCHEMY_CONN"}:
                .: {}
                f:name: {}
                f:value: {}
            f:envFrom: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/opt/airflow/dags"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
              k:{"mountPath":"/opt/airflow/logs"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext:
          .: {}
          f:runAsUser: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"airflow-dags"}:
            .: {}
            f:name: {}
            f:persistentVolumeClaim:
              .: {}
              f:claimName: {}
          k:{"name":"airflow-logs"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
    manager: OpenAPI-Generator
    operation: Update
    time: "2020-11-06T18:36:11Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.244.1.204"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2020-11-06T18:36:22Z"
  name: kubexecutorbranchtask-09007d64c0ca4d449ba357d8ba234b58
  namespace: default
  resourceVersion: "3606478"
  selfLink: /api/v1/namespaces/default/pods/kubexecutorbranchtask-09007d64c0ca4d449ba357d8ba234b58
  uid: 37aad859-95dc-4049-879f-406bc737f37c
spec:
  affinity: {}
  containers:
  - command:
    - airflow
    - run
    - kubexecutor
    - branch_task
    - "2020-11-06T18:36:04.231910+00:00"
    - --local
    - --pool
    - default_pool
    - -sd
    - /opt/airflow/dags/branchflow.py
    env:
    - name: AIRFLOW__CORE__EXECUTOR
      value: LocalExecutor
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      value: postgresql+psycopg2://postgresadmin:admin123@10.114.23.215:30883/postgresdb
    envFrom:
    - configMapRef:
        name: platform-env
    image: airflowjava:1.0
    imagePullPolicy: IfNotPresent
    name: base
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    **volumeMounts:
    - mountPath: /opt/airflow/dags
      name: airflow-dags
      readOnly: true
    - mountPath: /opt/airflow/logs
      name: airflow-logs
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: platform-token-sdgwn
      readOnly: true**
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker01
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    runAsUser: 50000
  serviceAccount: platform
  serviceAccountName: platform
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: airflow-dags
    persistentVolumeClaim:
      claimName: dagpvc
  - emptyDir: {}
    name: airflow-logs
  - name: platform-token-sdgwn
    secret:
      defaultMode: 420
      secretName: platform-token-sdgwn
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-06T18:36:11Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-06T18:36:22Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-06T18:36:22Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-06T18:36:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://ebf139bbdad0ffe459a068e6c48d030695a7dd4c1a745fc1807efb22a35fde4f
    image: airflowjava:1.0
    imageID: docker://sha256:cf99ee12c33a11a34f4c6f4a4a13bf8576e2a82e9b3e6bb54e7ffed7c7c1a5dc
    lastState: {}
    name: base
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://ebf139bbdad0ffe459a068e6c48d030695a7dd4c1a745fc1807efb22a35fde4f
        exitCode: 0
        finishedAt: "2020-11-06T18:36:21Z"
        reason: Completed
        startedAt: "2020-11-06T18:36:12Z"
  hostIP: 10.114.23.215
  phase: Succeeded
  podIP: 10.244.1.204
  podIPs:
  - ip: 10.244.1.204
  qosClass: BestEffort
  startTime: "2020-11-06T18:36:11Z"


AIRFLOW Scheduler YAML file has the mount as shown below

ubuntu@master-node:~$ k get pod platform-scheduler-77ffc7869b-t9qwz -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/config-env: 422a2f569d3be85f428527275ad25f976b77794bbb8e9ffb3ceab7185ce84dd5
    checksum/config-git-clone: 8797ee2d9bff73e4a6b622b5c36c4262c75412bd85a5efa13bc4f5820de01724
    checksum/config-scripts: 0ce64e792417406487fbc7b269c8690ea5a29e10c998370fb24657bb6bf7e443
    checksum/config-variables-pools: baf3d449329b72323050dc67ba43da3118e2a707d38fc95888afeb32a40d1b78
    checksum/secret-connections: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  creationTimestamp: "2020-11-06T18:29:36Z"
  generateName: platform-scheduler-77ffc7869b-
  labels:
    app: airflow
    component: scheduler
    pod-template-hash: 77ffc7869b
    release: platform
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:checksum/config-env: {}
          f:checksum/config-git-clone: {}
          f:checksum/config-scripts: {}
          f:checksum/config-variables-pools: {}
          f:checksum/secret-connections: {}
          f:cluster-autoscaler.kubernetes.io/safe-to-evict: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:component: {}
          f:pod-template-hash: {}
          f:release: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"f7daa5cb-eb83-44a2-9917-1a6ecc24233b"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:containers:
          k:{"name":"airflow-scheduler"}:
            .: {}
            f:args: {}
            f:command: {}
            f:env:
              .: {}
              k:{"name":"DATABASE_PASSWORD"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:secretKeyRef:
                    .: {}
                    f:key: {}
                    f:name: {}
            f:envFrom: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:livenessProbe:
              .: {}
              f:exec:
                .: {}
                f:command: {}
              f:failureThreshold: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:name: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/home/airflow/scripts"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/home/airflow/variables-pools/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/opt/airflow/dags"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/tmp/data"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"batchdata"}:
            .: {}
            f:name: {}
            f:persistentVolumeClaim:
              .: {}
              f:claimName: {}
          k:{"name":"dags-data"}:
            .: {}
            f:name: {}
            f:persistentVolumeClaim:
              .: {}
              f:claimName: {}
          k:{"name":"scripts"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
          k:{"name":"variables-pools"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-11-06T18:29:36Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.244.1.195"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2020-11-06T18:29:39Z"
  name: platform-scheduler-77ffc7869b-t9qwz
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: platform-scheduler-77ffc7869b
    uid: f7daa5cb-eb83-44a2-9917-1a6ecc24233b
  resourceVersion: "3605473"
  selfLink: /api/v1/namespaces/default/pods/platform-scheduler-77ffc7869b-t9qwz
  uid: 478819c9-84b3-4475-92bf-d43ed6823329
spec:
  containers:
  - args:
    - bash
    - -c
    - |
      true \
       && mkdir -p /home/airflow/.local/bin \
       && export PATH="/home/airflow/.local/bin:$PATH" \
       && echo "*** executing Airflow initdb..." \
       && airflow initdb \
       && echo "*** adding Airflow variables..." \
       && airflow variables -i /home/airflow/variables-pools/variables.json \
       && echo "*** adding Airflow pools..." \
       && airflow pool -i /home/airflow/variables-pools/pools.json \
       && echo "*** running scheduler..." \
       && exec airflow scheduler -n -1
    command:
    - /usr/bin/dumb-init
    - --
    env:
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: passwordsecret
    envFrom:
    - configMapRef:
        name: platform-env
    image: apache/airflow:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - python
        - -Wignore
        - -c
        - |
          import os
          os.environ['AIRFLOW__CORE__LOGGING_LEVEL'] = 'ERROR'
          os.environ['AIRFLOW__LOGGING__LOGGING_LEVEL'] = 'ERROR'
          from airflow.jobs.scheduler_job import SchedulerJob
          from airflow.utils.net import get_hostname
          import sys
          job = SchedulerJob.most_recent_job()
          sys.exit(0 if job.is_alive() and job.hostname == get_hostname() else 1)
      failureThreshold: 5
      initialDelaySeconds: 300
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 1
    name: airflow-scheduler
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/airflow/scripts
      name: scripts
    - mountPath: /opt/airflow/dags
      name: dags-data
    - mountPath: /home/airflow/variables-pools/
      name: variables-pools
    **- mountPath: /tmp/data
      name: batchdata**
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: platform-token-sdgwn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker01
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: platform
  serviceAccountName: platform
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 493
      name: platform-scripts
    name: scripts
  - name: dags-data
    persistentVolumeClaim:
      claimName: dagpvc
  - configMap:
      defaultMode: 493
      name: platform-variables-pools
    name: variables-pools
  - name: batchdata
    persistentVolumeClaim:
      claimName: batchpvc
  - name: platform-token-sdgwn
    secret:
      defaultMode: 420
      secretName: platform-token-sdgwn
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-06T18:29:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-06T18:29:39Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-06T18:29:39Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-06T18:29:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://371bfc9cef4a024f99c9c571241f18dd05498799ac09619ffa080c7285205e55
    image: apache/airflow:1.10.12-python3.6
    imageID: docker-pullable://apache/airflow@sha256:9ea9e5ca66bd17632241889ab248fe3852c9f3c830ed299a8ecaa8a13ac2082f
    lastState: {}
    name: airflow-scheduler
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-06T18:29:38Z"
  hostIP: 10.114.23.215
  phase: Running
  podIP: 10.244.1.195
  podIPs:
  - ip: 10.244.1.195
  qosClass: BestEffort
  startTime: "2020-11-06T18:29:36Z"

**Comment by penolove** [comment]
same issue here, are there ways to mount volume into the worker pod via values.yml?

**Comment by penolove** [comment]
as checked the default setting of 1.10.12, seems that there is no flexible endpoint to fetching additional volume
https://github.com/apache/airflow/blob/1.10.12/airflow/kubernetes/worker_configuration.py#L289

but while current airflow master (v2-0-stable)
https://github.com/apache/airflow/blob/v2-0-stable/tests/kubernetes/pod_generator_base_with_secrets.yaml
provides more flexible way to create worker node.

**Comment by thesuperzapper** [comment]
@penolove this repo (helm/charts) is going away in a few days, can you please raise this issue in the new home:

https://github.com/airflow-helm/charts/tree/main/charts/airflow

**Comment by kirancodify** [comment]
facing the same issue .. any updates on this ?

**Comment by thesuperzapper** [comment]
@kirancodify @penolove @jineshmathewt if you are facing an issue, please raise it on the new github repo, as we are no longer tracking this repo.

See here: https://github.com/airflow-helm/charts/tree/main/charts/airflow
