### ISSUE TITLE
[stable/fluent-bit] Support SELinux

### ISSUE THREAD

**Issue by beyondbill** [helm/charts#24027]
Fluent-bit Helm chart, which collects our k8s container and system logs, seems [not compatible](https://github.com/helm/charts/blob/e53d7072b97b5efbe2ef8f9f931920256f7252ed/stable/fluent-bit/templates/psp.yaml#L44-L46) with SELinux. For example, we've seen file permission issues to read container log files on the hosts

```
[2020/11/05 23:32:16] [error] [input:tail:tail.0] read error, check permissions: /var/log/containers/*.log
[2020/11/05 23:32:16] [ warn] [input:tail:tail.0] error scanning path: /var/log/containers/*.log
```

We have turned off SELinux as a workaround. But for better security, we would like to see a PodSecurityPolicy from fluent-bit to support SELinux. Thank you!

**Comment by pinsker88** [comment]
What about selinux's volume mounts in helm?
Its just chcon -R -t svirt_sandbox_file_t /SOURCEDIR on the persistentVolume
