### ISSUE TITLE
Istio chart promotion to stable repo

### ISSUE THREAD

**Issue by lachie83** [helm/charts#2406]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**: 

**Which chart**: Istio

I would like to promote Istio to the stable repo. Here's what needs to happen.

https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements

Additionally I would like the following to happen to the chart. Feel free to action if you have time
* Enable optional customConfigmaps @lachie83
* Healthchecks
* Updated documentation @lachie83
* Helm tests @lachie83

**Comment by lachie83** [comment]
cc @gyliu513, @viglesiasce @unguiculus  What else would you like to see? I will take the customConfigmaps and documentation.

**Comment by rimusz** [comment]
istio is not really ready for stable repo yet, it is changing a lot.

**Comment by lachie83** [comment]
Thanks @rimusz in the interim. Is there anything else we should be adding to this chart?

**Comment by rimusz** [comment]
I would really wait till istio guys release stable v0.2.x, I spent half day with them last week (they there in London to too meet users and get feedback), so every one major version bump will bring new functionality, depreciating some old.
