### ISSUE TITLE
Can not install istio via helm

### ISSUE THREAD

**Issue by wesnigk-espirit** [helm/charts#2413]
$ helm install incubator/istio --debug
[debug] Created tunnel using local port: '50024'
[debug] SERVER: "localhost:50024"
[debug] Original chart version: ""
Error: chart "istio" matching  not found in incubator index. (try 'helm repo update'). No chart version found for istio-

**Comment by onlydole** [comment]
Hey @mikula-espirit! Have you tried adding the incubator repo before trying to install that chart? 

```
helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com
```

**Comment by wesnigk-espirit** [comment]
of course  i added the repo and updated it. I'm using minikube@win10
also i made a pull request because the readme.md points to another repository.

**Comment by onlydole** [comment]
Were you able to get it to work in that case?

I was able to get it running on my cluster with:

```
helm install incubator/istio --version 0.2.7-chart2
```

Without the version, I got a similar result to you.

**Comment by wesnigk-espirit** [comment]
Well yes and no i also had to specify the version:

`helm install --name istio-${NAMESPACE} --namespace ${NAMESPACE} incubator/istio --home ~/.helm --set rbac.install=false --version 0.2.7-chart2`

But this did not "install/create" any container -> because of "reasons"
so i had to work around this issue using: 

`helm upgrade istio-${NAMESPACE} incubator/istio --version 0.2.7-chart2 --reuse-values --set istio.install=true`

**Comment by onlydole** [comment]
Oh good! Glad that it's working now, I'd recommend pulling down the Istio values and setting that up a local `values.yaml` so you can tweak and upgrade those as needed - https://github.com/kubernetes/charts/blob/master/incubator/istio/values.yaml

Then apply with `helm install istio-${NAMESPACE} incubator/istio -f path/to/values.yml --version 0.2.7-chart2`

**Comment by Morriz** [comment]
Is this resolved? Seems like a big blocker to not be able to install with default instructions.

**Comment by iamrandys** [comment]
Yes, this is a blocker. I had to use the version as well.  I'm sure it's from the strange "-chart2" version.  The docs should at least be updated.

Helm v2.7.2

helm install --name istio incubator/istio --namespace istio-system --version 0.2.8-chart2


0.2.8-chart2 is also not working.  It looks like a few of the docker images are missing for 0.2.8. For example for Grafana, I see version 0.2.6, 0.2.7, 0.2.9 and 0.2.10 but no 0.2.8.

https://hub.docker.com/r/istio/grafana/tags/


Istio chart 0.2.7-chart7 seems to work just fine.

--version 0.2.7-chart7
