### ISSUE TITLE
[stable/aws-cluster-autoscaler] Error from server (Invalid): error when applying patch:

### ISSUE THREAD

**Issue by rampatnaik** [helm/charts#24428]
I am getting 2 error

1.  error: unable to recognize "STDIN": no matches for kind "Deployment" in version "extensions/v1beta1"

`fix : I changed the apiVersion: apps/v1 on aws-cluster-autoscaler/templates/deployment.yaml`

2.  error: error validating "STDIN": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec;

```
fix :  spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}

aws-cluster-autoscaler/templates/deployment.yam
```

3.  The Service :name" is invalid: spec.clusterIP: Invalid value: "": field is immutable

> Can I get fixes

**Comment by bacongobbler** [comment]
FYI: https://github.com/helm/charts/pull/24285

**Comment by rampatnaik** [comment]
any update with fix
