### ISSUE TITLE
[stable/hadoop] datanode can't scale to larger than 2

### ISSUE THREAD

**Issue by lx308033262** [helm/charts#24427]
**Describe the bug**
when datanode scale to 2 or larger than 2,then use same pvc

**Version of Helm and Kubernetes**:

**Which chart**:
hadoop

**What happened**:

2020-11-17 09:15:59,469 ERROR org.apache.hadoop.hdfs.server.common.Storage: It appears that another node  46@hadoop-hadoop-hdfs-dn-0.hadoop-hadoop-hdfs-dn.default.svc.cluster.local has already locked the storage directory: /root/hdfs/datanode

**What you expected to happen**:
datanode scale to 2 or larger than 2

**How to reproduce it** (as minimally and precisely as possible):
vim values.yaml 
  dataNode:
    replicas: 2

**Anything else we need to know**:

**Comment by lx308033262** [comment]
i just did resolve this problem
1.delete hadoop already exists  (backup your data)
helm delete hadoop --purge

2.delete the pvc template
 mv hadoop/templates/hdfs-dn-pvc.yaml  /tmp

3.modify hdfs-dn-statefulset.yaml
vim hadoop/templates/hdfs-dn-statefulset.yaml 

delete below content (format maybe not correct)
      {{- if .Values.persistence.dataNode.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "hadoop.fullname" . }}-hdfs-dn
      {{- else }}
        emptyDir: {}


add blow content(format maybe not correct)
  volumeClaimTemplates:
    - metadata:
        name: hdfs-datanode-data
      spec:
        accessModes:
          - {{ .Values.persistence.dataNode.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.dataNode.size | quote }}
      {{- if .Values.persistence.dataNode.storageClass }}
        {{- if (eq "-" .Values.persistence.dataNode.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.dataNode.storageClass }}"
        {{- end }}
      {{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}

**Comment by bacongobbler** [comment]
https://github.com/helm/charts/pull/24320
