### ISSUE TITLE
Broken redirect from deprecated kubernetes-charts.storage.googleapis.com repo to new charts.helm.sh repo

### ISSUE THREAD

**Issue by mathieusama** [helm/charts#24432]
**Describe the bug**
The deprecated https://kubernetes-charts.storage.googleapis.com/ server seems to have a broken redirect to https://charts.helm.sh/stable/

**What happened**:
Trying to pull (possibly any?) chart from deprecated server redirects to incorrect path in new server.

**What you expected to happen**:
Redirect to proper path in new server.

**How to reproduce it**
```
$ helm repo add stable https://kubernetes-charts.storage.googleapis.com/
"stable" has been added to your repositories
$ helm pull stable/cluster-autoscaler
Error: failed to fetch https://charts.helm.sh/stable/cluster-autoscaler-8.0.0.tgz : 404 Not Found
```
And when we look at the repo’s manifest here https://charts.helm.sh/stable/index.yaml, we can see that the actual URL where that chart is hosted is https://charts.helm.sh/stable/packages/cluster-autoscaler-8.0.0.tgz. Notice the extra `/packages` in path.

However, curl'ing the chart directly from that url works fine. And directly referencing the https://charts.helm.sh/stable repo also works fine.

**Comment by bacongobbler** [comment]
Please migrate to the new mirror repository at https://charts.helm.sh/stable. The old system is no longer supported. It is expected that the storage bucket supporting the old location could be removed at any time now, so there's no real point in trying to address this assuming the old location will be removed shortly.

Thanks for the report.
