### ISSUE TITLE
[stable/nfs-server-provisioner] where it will hosted after deprication

### ISSUE THREAD

**Issue by nagasitaramthigulla** [helm/charts#24436]
[stable/nfs-server-provisioner] where it will hosted after deprication

**Comment by scottrigby** [comment]
The chart is no longer being maintained. You can see the former maintainers in this PR diff: https://github.com/helm/charts/pull/24367/files perhaps it would be good to have a conversation about it with them. We could use this issue to discuss it.

The original k8s incubator application has moved here: https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner. And it looks like the chart has moved there as well: https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/tree/master/deploy/helm though the instructions are incorrect.

Cross-linking https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/issues/25

Let's get this sorted out and we can update https://github.com/helm/charts/issues/21103 to reflect the new location.

Does someone want to take the lead on that?

**Comment by scottrigby** [comment]
CC @kiall @kvaps @joaocc @naseemkullah

**Comment by naseemkullah** [comment]
I've made a PR to remove myself as a maintainer for this chart: https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/28 🪂

**Comment by kvaps** [comment]
Helm chat source code was moved to the new repository
https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner

**Comment by KamalAman** [comment]
Found it here hosted `https://kvaps.github.io/charts` 

https://artifacthub.io/packages/helm/kvaps/nfs-server-provisioner
