### ISSUE TITLE
Deprecation => add proposal chart

### ISSUE THREAD

**Issue by TOTOleHero** [helm/charts#24446]
Hello, 

All charts are deprecated, but in many of them, there no alternative in documentation.

Could you add proposals with the most compatible chart to replace it ?

Thank's you

**Comment by scottrigby** [comment]
This pinned issue is the place to do it: https://github.com/helm/charts/issues/21103

Specifically, see https://github.com/helm/charts/issues/21103#issuecomment-732992002. We still have yet to resolve how to best deliver this info now that the repo is read-only. Please comment any suggestions on that issue. 

Also if you know of other charts that have moved but info has not yet been updated in the table on that issue, please link the issue from any other relevant github issue or PR (so they appear in the automatic github issue references list), or else please just comment on this issue so it doesn't get lost.
