### ISSUE TITLE
[stable/rocketchat] is deprecated but no alternatives

### ISSUE THREAD

**Issue by abdennour** [helm/charts#24450]
**Is your feature request related to a problem?**
Rocketchat helm chart is deprecated in stable repo however, the README does not mention any other alternative.

**Describe the solution you'd like**
I wanna to know a clear meaning for deprecation for charts that no alternative repos are mentioned.

**Additional context**
[Official documentation](https://docs.rocket.chat/installation/automation-tools/helm-chart) is still referring stable/rocketchat as the official chart :

**Comment by philtweir** [comment]
I'm guessing this is the future destination : https://github.com/RocketChat/helm-charts but just not good to go yet
