### ISSUE TITLE
[Incubator/rundeck] Rundeck doesn't work with SSL (https url)

### ISSUE THREAD

**Issue by ravin9249** [helm/charts#24495]
Tried to deploy Rundeck helm in Openshift but Rundeck not working with SSL.
Wanted to know, is rundeck support with SSL as docker/openshift/kubernetes deployment? If yes then please let me know the changes needed in helm.
Thanks in advance!

**Comment by roko99** [comment]
Hello @ravin9249 
At least it works somehow in kubernetes - please check [this](https://github.com/helm/charts/issues/20532#issuecomment-874972710) may be it helps.

**Comment by bridgetkromhout** [comment]
As this repo is no longer maintained, please work with the [rundeck community](https://github.com/rundeck/rundeck/issues/6619) on helm charts for Rundeck. Thanks.
