### ISSUE TITLE
How to enable the nfs security with NFS client provisioner plugin

### ISSUE THREAD

**Issue by balajir24** [helm/charts#24508]
Hi Team,

We have configured one-premise k8s cluster and enabled NFS client provisioner plugin for dynamic PVC provisioning with NFS.

We need to enable NFS security as well. so that only k8s applications will able to use that NFS share. Please suggest/help on this.

**Comment by bridgetkromhout** [comment]
Hi, @balajir24 - we're not able to answer this question here; I suggest trying https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.
