### ISSUE TITLE
Run Jenkins as non-root user

### ISSUE THREAD

**Issue by roeeni** [helm/charts#24507]
I want to run Jenkins with non root user.
how can I do that?

**Comment by m3llo96** [comment]
![image](https://user-images.githubusercontent.com/66171850/127781711-26d01e10-ab32-40e9-91ba-fae632206c80.png)


This should help me?

**Comment by bridgetkromhout** [comment]
Hi, @m3llo96 - This repo is being archived and no help is available here.

You may want to look at https://github.com/jenkinsci/helm-charts, which is active and more likely to have people who can help with Jenkins & Helm questions. Thanks.
