### ISSUE TITLE
[incubator/rundeck] aws secret volume mount is not defined correctly (aws-config)

### ISSUE THREAD

**Issue by cscotti** [helm/charts#24500]
**Describe the bug**
If we set aws-config we get this error

```
Error: UPGRADE FAILED: cannot patch "myrundeck" with kind Deployment: Deployment.apps "myrundeck" is invalid: spec.template.spec.containers[1].volumeMounts[2].name: Not found: "aws-config"
```

This volume is missing in templates/deployment.yaml 

```
        {{- if .Values.rundeck.awsConfigSecret }}
        - name: aws-config
          secret:
            secretName: {{ .Values.rundeck.awsConfigSecret}}
        {{- end }}
```

**Version of Helm and Kubernetes**:

Helm
```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}
```
Kubernetes
```
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
incubator/rundeck

**What happened**:
Helm cannot deploy deploment.yaml

**What you expected to happen**:
Mount aws credential in folder /home/rundeck/.aws/

**How to reproduce it** (as minimally and precisely as possible):

Apply before the aws credential secret
```
echo "apiVersion: v1
data:
  config: XXXXXXXX
  credentials: XXXXXXXXX
kind: Secret
metadata:
  creationTimestamp: null
  name: aws-secret" kubectl apply -f -
```

Activate this part in the values.yaml (https://github.com/helm/charts/blob/master/incubator/rundeck/values.yaml).
```
  # Name of secret containing to mount under ~/.aws/
  # awsConfigSecret: "aws-secret"
  awsConfigSecret: "aws-secret"
```

Deploy with helm

**Anything else we need to know**:
When rundeck chart will be stable ? Where Is the last repo for Rundeck chart project located ?

**Comment by cscotti** [comment]
This issue is related to https://github.com/helm/charts/pull/23969

**Comment by bridgetkromhout** [comment]
Hi, @cscotti - As this repo is no longer maintained, please work with the [rundeck community](https://github.com/rundeck/rundeck/issues/6619) on helm charts for Rundeck. Thanks.
