### ISSUE TITLE
[stable/jenkins]

### ISSUE THREAD

**Issue by usuryadevara** [helm/charts#24509]
**Describe the bug**

**Version of Helm and Kubernetes**:
helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}

**Which chart**:
jenkins stable

**What happened**:
I am using this https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml to deploy in Kubernetes AWS. 

helm install jenkins stable/jenkins -f jenkins-values.yaml                                                                                      
WARNING: This chart is deprecated
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "jenkins" in namespace "default" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: key "app.kubernetes.io/managed-by" must equal "Helm": current value is "eksctl"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "jenkins"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"

Then i updated 'serviceAccount: create: false' , 'serviceType:LoadBalancer' and deploy it, it created Class LB but instances shows outofservice on Loadbalancers.

kubectl get pods                                          
NAME                        READY   STATUS    RESTARTS   AGE
jenkins-75fcd4767-sr96q     1/2     Running   0          70s

kubectl logs jenkins-75fcd4767-sr96q                                                                                                            
error: a container name must be specified for pod jenkins-75fcd4767-sr96q, choose one of: [jenkins jenkins-sc-config] or one of the init containers: [copy-default-config]

**What you expected to happen**:
A login page with jenkins.

**How to reproduce it** (as minimally and precisely as possible):
I am using the default configuration (without service account and Loadbalancer settings)

**Anything else we need to know**:

How can i fix this issue with Loadbalancer?

**Comment by bridgetkromhout** [comment]
Hi, @usuryadevara - this repo is being archived and no support is available here. 


You may want to look at https://github.com/jenkinsci/helm-charts, which is active and more likely to have people who can help with Jenkins & Helm questions. Thanks.
