### ISSUE TITLE
include blackbox exporter yaml templates in stable/prometheus

### ISSUE THREAD

**Issue by ghost** [helm/charts#2451]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.

Prometheus configuration for kubernetes use blackbox exporter when scrape for kubernetes-service, but the blackbox exporter yaml files are not present in charts template. As alertmanager or kube-state-metrics, blackbox exporter should be added to values.yaml allowing users to select if is installed or not.

**Version of Helm and Kubernetes**:
All

**Which chart**:
Prometheus

**Comment by snebel29** [comment]
Looks like there is a PR to get this done #2906
