### ISSUE TITLE
Liveless and Readyness proble failing for the cluster agent

### ISSUE THREAD

**Issue by surajtikoo** [helm/charts#24518]
**Describe the bug**

**Version of Helm and Kubernetes**:datadog-2.3.11/2.10.13

**Which chart**: Helm

**What happened**:
    3m36s       Warning   Unhealthy           pod/datadog-agent-cluster-agent-b89d4f85c-c2htq    Readiness probe failed: HTTP probe failed with statuscode: 500
3m36s       Warning   Unhealthy           pod/datadog-agent-cluster-agent-b89d4f85c-

All the order datadog agent pods are failing to start. No logs other than this

**What you expected to happen**:
   Datadog agent should be running with the cluster agent

**How to reproduce it** (as minimally and precisely as possible):
   

**Anything else we need to know**:

**Comment by bridgetkromhout** [comment]
Hi, @surajtikoo - no support is available in this repo. You could ask in https://github.com/DataDog/helm-charts.
