### ISSUE TITLE
stolon/postgres deployment not working on IPv6 and istio 1.5.7 service mesh

### ISSUE THREAD

**Issue by kd-nuance** [helm/charts#24517]
1. Deploy the chart.
postgres-stolon-create-cluster-5sqn8                  0/1     Completed   0          77s
postgres-stolon-keeper-0                                     2/2     Running     0          77s
postgres-stolon-proxy-5b7ffb5587-kkcxr              2/2     Running     0          77s
postgres-stolon-sentinel-6b8d8b4b6-w4ptz         2/2     Running     0          77s

2. Open shell
k exec -it postgres-stolon-keeper-0 -- sh

3. type psql and submit
# psql
psql: error: could not connect to server: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

4. the chart works fine on ipv6 but not on istio mesh. (istio mtls is mandatory for us)
5. initDb scripts job also goes into error state.
6. Pods have no error in their logs.

Please help.

**Comment by bridgetkromhout** [comment]
Hi, @kd-nuance - This repo (the old helm charts repo) is deprecated and does not offer support. You could try checking with https://github.com/sorintlab/stolon or https://github.com/istio/istio.
