### ISSUE TITLE
.Capabilities.HelmVersion.Version built-in object is not working with helm 3.4.1

### ISSUE THREAD

**Issue by pratikshavyas** [helm/charts#24511]
I was trying to use built in object ".Capabilities.HelmVersion.Version", however it is giving an empty string as output and not giving the expected result. 
Please have a look and suggest.

**Comment by bridgetkromhout** [comment]
Hi, @pratikshavyas - no support is available in this repo. If https://helm.sh/docs/chart_template_guide/builtin_objects/ does not answer this question, then please open an issue in helm/helm: https://github.com/helm/helm/issues/new
