### ISSUE TITLE
stable/prometheus-node-exporter daemonset tolerations

### ISSUE THREAD

**Issue by spothound** [helm/charts#24519]
Hello there,

I have some nodes in my K8s cluster with `NoExecute` taints. This prevents my `kube-prometheus-stack-prometheus-node-exporter` daemonset pods from being scheduled in those nodes.

I was looking for a way to add a toleration for those pods and I found that there is already a generic toleration:

```
tolerations:
  - effect: NoSchedule
    operator: Exists
```

This is OK but to ignore all `NoSchedule` taints but won't be enough for `NoExecute` taints. I think that the chart should have an option to ignore all taints or to add custom tolerations, or maybe the mentioned toleration should be updated to:

```
tolerations:
  - operator: Exists
```
Thanks!

**Comment by bridgetkromhout** [comment]
Hi, @spothound - Please see https://github.com/prometheus-community/helm-charts/ for any input you'd like to make to the community-maintained Prometheus charts - thanks.
