### ISSUE TITLE
Deleting the Prometheus statefulset recreating itself

### ISSUE THREAD

**Issue by jaisegrg** [helm/charts#24514]
Hi,

I tried to stop/delete the Prometheus pods and statefulset to increase PVC disk size, but the statefulset/pods getting recreated automatically.

I am using "stable/prometheus-operator" chart.

Could you please share the steps to permanently stop pods/statefulset without automatic restart?

**Comment by bridgetkromhout** [comment]
Hi, @jaisegrg - This repo has no support available. For your question, I suggest https://github.com/prometheus-community/helm-charts - cheers.
