### ISSUE TITLE
add arm64 support to external-dns 

### ISSUE THREAD

**Issue by thiagosantosleite** [helm/charts#24521]
Add arm64 support to external-dns 

```
kubectl logs external-dns-85d8669d46-9t68s -n external-dns --context=sbox
standard_init_linux.go:219: exec user process caused: exec format error
```

**Comment by aRobinson-R7** [comment]
These Helm charts are no longer supported
We use the Bitnami chart 
- https://github.com/bitnami/charts/tree/master/bitnami/external-dns
- https://charts.bitnami.com/bitnami
with the image: k8s.gcr.io/external-dns/external-dns:v0.9.0
which does support ARM

**Comment by thiagosantosleite** [comment]
Wonderful! it's working in arm64 now.

thanks @aRobinson-R7
