### ISSUE TITLE
stable/prometheus-operator  issue : getting the below issue while try to install prometheus-operator on my EC2 instance using Minikube

### ISSUE THREAD

**Issue by Mjahannivas** [helm/charts#24526]
helm install prometheus stable/prometheus-operator -n prometheus

**Error: INSTALLATION FAILED: failed to install CRD crds/crd-alertmanager.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"**

**Comment by bridgetkromhout** [comment]
Hi, @Mjahannivas - This repo has no support available. For your question, I suggest https://github.com/prometheus-community/helm-charts - cheers.
