### ISSUE TITLE
Need help with configuring jenkins proxy which is running inside pod deployed via helm

### ISSUE THREAD

**Issue by rg13567** [helm/charts#24527]
I have a kubernetes cluster setup with master and worker nodes
I deployed jenkins on my worker node with helm chart. I want to configure jenkins proxy as part of deployment so that once my jenkins pod comes up it already has my proxy configured in order to install plugins.
Can anyone suggest how this can be done?

**Comment by bridgetkromhout** [comment]
Hi, @rg13567 - This repo is being archived and no help is available here.

You may want to look at https://github.com/jenkinsci/helm-charts, which is active and more likely to have people who can help with Jenkins & Helm questions. Thanks.
