### ISSUE TITLE
 stable/chart  Support for IngressClassName for EKS Ingress

### ISSUE THREAD

**Issue by mbig** [helm/charts#24534]
**Is your feature request related to a problem? Please describe.**

We are implementing ingress controller v1.x.x and support for kubernetes.io/ingress.class: "nginx" has been deprecated.
**Describe the solution you'd like**

className option should be added to values file ingress: section
**Describe alternatives you've considered**

A workaround is to patch ingress with spec.IngressClassName
**Additional context**

**Comment by mimmus** [comment]
We need to upgrade our Nginx IngressController from 0.x to 1.x and kubernetes.io/ingress.class has been deprecated, in favour of spec.ingressClassName.
Unfortunately, there is no backward compatibility.

Patching ChartMuseum Ingress template in the chart should not be difficult.

**Comment by bridgetkromhout** [comment]
Hi, @mimmus - this repo is deprecated. You may want to check https://github.com/nginxinc/helm-charts for help with Nginx IngressController.
