### ISSUE TITLE
[postgresql] issue with replica creation when database is large

### ISSUE THREAD

**Issue by leforthomas** [helm/charts#24537]
**Describe the bug**

The creation of a new replica fails when the database to replicate is very large. It seems that the pod is restarted by the readiness probe whilst importing the data into the database. As the import and setup are not yet finished the next start fails.

**Version of Helm and Kubernetes**:

Kubernetes 1.18

**Which chart**:

Postgres

**What happened**:

Database creation/import for slave is interrupted because of readiness probe restarting the pod. When the pod has restarted it complains the postgres folder is corrupted (missing postgres version).

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

Primary with a very large database and add a replica, log follow and see the process being interrupted.

**Anything else we need to know**:

**Comment by bridgetkromhout** [comment]
Hi, @leforthomas!

I suggest checking with the current maintainers of the Helm chart you're using if you believe something in the chart is causing this behavior. This repo is the former home of helm charts which are now found at [Artifact Hub](https://artifacthub.io/). Project support is not available in this repo. Thanks!
