### ISSUE TITLE
need suggestion on jenkins plugins in helm

### ISSUE THREAD

**Issue by rg13567** [helm/charts#24533]
is there any way to not use installPlugins in values.yaml while deploying jenkins with helm but instead provide plugins.txt as a parameter to install the list of plugins I need.

Or, any way to refer a file inside helm for list of plugins to be installed as part if deployment instead of hard coding the plugins name in values.yaml

**Comment by bridgetkromhout** [comment]
Hi, @rg13567 - This repo is being archived and no help is available here.

You may want to look at https://github.com/jenkinsci/helm-charts, which is active and more likely to have people who can help with Jenkins & Helm questions. Thanks.
