### ISSUE TITLE
[Mattermost Team Edition] Various custom config.json options missing in helm's configJson

### ISSUE THREAD

**Issue by lfvjimisola** [helm/charts#24535]
It seems as if various [custom config.json options](https://docs.mattermost.com/configure/configuration-settings.html#load-custom-configuration-defaults) are missing in the helm chart (ref [values.yml](https://github.com/helm/charts/blob/master/stable/mattermost-team-edition/values.yaml).

For example:

- TeammateNameDisplay
- ReplyToAddress
- EnableEmailInvitations

**Comment by bridgetkromhout** [comment]
Hi, @lfvjimisola - this repo is being archived and no help is available here. I suggest checking https://github.com/mattermost/mattermost-helm. Thanks!
