### ISSUE TITLE
elastic curator is not deleting indices of other two statefulsets replicas.

### ISSUE THREAD

**Issue by surajmachamasi** [helm/charts#24536]
i have deployed elastic search via helm 1 master and 2 slave elasticsearch.   the elasstic curator is deleting only indices of  elasticsearch-master-2 only. other two elastic search indices are not deleted.  

pod list. 

    elasticsearch-master-0                           1/1     Running   0          5d2h
    elasticsearch-master-1                           1/1     Running   0          5d2h
    elasticsearch-master-2                           1/1     Running   0          16h

elastic curator config yaml.   

    client:
      hosts:
        - elasticsearch-master.logging
      port: 9200
      master_only: False

**Comment by bridgetkromhout** [comment]
Hi, @surajmachamasi - this repo is deprecated and provides no support.

Perhaps check https://github.com/elastic/curator for assistance.
