### ISSUE TITLE
Stable/Spark-history-server - completed spark jobs url redirecting  https --> http and timing out in chrome/Mozilla

### ISSUE THREAD

**Issue by mshilamk8s** [helm/charts#24542]
Deployed Spark-history-server
version: 1.4.3
appVersion: 2.4.0

While accessing completed jobs in spark history server UI:
Completed spark jobs url redirecting from https --> http and timing out in Chrome/Mozilla. Where as the redirect to http is not happening in Safari and able to navigate through completed spark job in Spark history server.

Any one experienced this issue and any possible solutions?

**Comment by bridgetkromhout** [comment]
Hi, @mshilamk8s - you're asking this question in a deprecated repo for helm charts, so you probably want to ask elsewhere. I suggest starting with https://stackoverflow.com/questions/61218954/when-ssl-is-enabled-spark-ui-doesnt-use-https-but-forwards-to-port-0-over-htt and seeing if that helps; if it does not, then stackoverflow is likely a better place to ask. Best of luck.
