### ISSUE TITLE
stable/traefik: Not possible to use with SSL disabled on 1.8 cluster

### ISSUE THREAD

**Issue by colemickens** [helm/charts#2472]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
latest Helm, Kubernetes 1.8

**Which chart**:
traefik

**What happened**:
It fails to deploy if ssl is disabled, due to this issue and the fix: https://github.com/kubernetes/kubernetes/issues/47222. If SSL is not enabled the chart currently targets 443 to 80, which is affected by that change.

**Comment by hlascelles** [comment]
We're seeing the same issue. Our use case is an ELB with an AMC, so SSL termination is happening at the ELB level. If we patch the service yml to remove the 80 listener from the ELB then our site works on https, but we can't take advantage of traefik performing the http => https redirect for us.

And, reading that kubernetes issue link, it appears we aren't the only one.

**Comment by krancour** [comment]
#2644 is a duplicate of this issue. Even though this one came first, I propose we close this one because #2644 already has a PR associated with it.

**Comment by hlascelles** [comment]
I'll add my comments to that issue...

**Comment by krancour** [comment]
cc @prydonius @viglesiasce 

Can one of you close this issue please?
