### ISSUE TITLE
[incubator/istio] istio request two steps to install now

### ISSUE THREAD

**Issue by gyliu513** [helm/charts#2486]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:
istio

**What happened**:
It request two steps to install istio now which is different with 1.6 https://github.com/kubernetes/charts/tree/master/incubator/istio#installing-the-chart

If someone call `helm install` from dashboard, then once the first step finished, the istio cannot be installed.

@lachie83 can you please share more detail for why need two steps to install istio, is it possible to install it in one step? Thanks!

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by lachie83** [comment]
This is because I need to lay down the CRDs before creating resources of those custom types. This should be doable using Helm pre-install hooks but they don't currently work with CRDs. This will be fixed in 2.7 release of helm

**Comment by gyliu513** [comment]
Good to know, thanks @lachie83 . Just want to get more, so if the CRD is not ready, then all of the deployment will be failed?

**Comment by lachie83** [comment]
Yes everything in this file will break -- https://github.com/kubernetes/charts/blob/master/incubator/istio/templates/custom-resources/custom-resources.yaml. See how they are custom kinds. The need CRDs to be created beforehand

**Comment by gyliu513** [comment]
I see, thanks @lachie83 , then I think that we can keep this issue open till we fix this by helm 2.7

**Comment by gyliu513** [comment]
Helm 2.7 is ready https://github.com/kubernetes/helm/releases/tag/v2.7.0 and also the CRD fix was also there https://github.com/kubernetes/helm/issues/2925 @lachie83

**Comment by sslavic** [comment]
Even with

- helm/tiller 2.7.2 and
- all
```
{{- if and .Values.istio.install (not .Release.IsInstall) -}}
```
and matching ends removed as well as
- ```istio.install``` removed from values.yaml and
- NOTES.txt adjusted
trying to helm install still gives an error
```
Error: apiVersion "config.istio.io/v1alpha2" in istio/templates/custom-resources/custom-resources.yaml is not available
```
I must be doing something wrong.

EDIT:
Adding to all CRDs in custom-resources/ mixer.yaml and pilot.yaml
```
  annotations:
    "helm.sh/hook": pre-install
```
didn't help.
