### ISSUE TITLE
Running redis without a password - discussion or PR?

### ISSUE THREAD

**Issue by rileylark** [helm/charts#249]
Ahoy! 

I want to run redis in my trusted network, not exposed to the internet, and I think that [the redis docs](http://redis.io/topics/security) imply that that is the primary way that redis was designed to be used. Unfortunately, I think the stable helm chart here does not expose a way to configure redis without a password.

I'm not sure what the process is like in this repo for suggesting changes. Would you all be interested in further discussion about this? I'd be happy to work on a PR for making passwords optional, but I'm not sure that a) that change would be welcome or b) what style of configuration is conventional for turning _off_ security in an official Helm chart.

I hope this makes sense! Please let me know if I can clarify or if I'm misunderstanding something.

**Comment by lachie83** [comment]
#378 Handles this requirement

**Comment by seanknox** [comment]
Closing in favor of #378.
