### ISSUE TITLE
[stable/prometheus] Spaces in program argument storage.retention

### ISSUE THREAD

**Issue by totemcaf** [helm/charts#2506]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
Helm Client: v2.6.2+gbe3ae4e
Helm Server: v2.6.2+gbe3ae4e

Kubernetes Client Version: v1.8.0
Kubernetes Server Version: v1.7.8

**Which chart**:
stable/prometheus

**What happened**:
If you configure the paramerer `server.retention` the server pod fails to start with the following message:

    flag provided but not defined: -storage.local.retention 

**What you expected to happen**:

Pos starts normally.

**How to reproduce it** (as minimally and precisely as possible):

execute:

    helm install --name someName --set server.retention=360h stable/prometheus

**Anything else we need to know**:
The Deployument is created with the following lines:

    args:
      - --alertmanager.url=http://monitor-prd-prometheus-alertmanager:80
      - --storage.local.retention = 360h
      - --config.file=/etc/config/prometheus.yml
      - --storage.local.path=/data
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles

You can see the second line has spaces between the "=".

**Comment by rio** [comment]
fixed in #2515
