### ISSUE TITLE
[stable/openvpn] - Dashboard or Admin UI

### ISSUE THREAD

**Issue by neumachen** [helm/charts#2507]
**Is this a request for help?**:
This is a request

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

If this is a FEATURE REQUEST, please:
  - It would be nice if we can also include a dashboard or admin UI for OpenVPN.

**Version of Helm and Kubernetes**:
Kubernetes - latest
Helm - latest

**Which chart**:
stable/openvpn

**What happened**:
A bit hard to manage certificates and users for OpenVPN.

**What you expected to happen**:
Have a dashboard or admin UI

**Comment by mattfarina** [comment]
cc: @jfelten

**Comment by jfelten** [comment]
good idea - what did you have in mind? https://sourceforge.net/projects/openvpncertmgmt/#screenshots ?

**Comment by neumachen** [comment]
I think this one is nice, [openvpn-web-ui](https://github.com/adamwalach/openvpn-web-ui). What do you think @jfelten? Here are some [screenshots](https://github.com/adamwalach/openvpn-web-ui/blob/master/docs/screenshots.md)?

**Comment by robhunt3r** [comment]
bump as I think it is a nice optional feature.
