### ISSUE TITLE
Spinnaker chart installation times out

### ISSUE THREAD

**Issue by shimmerjs** [helm/charts#2510]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Version of Helm and Kubernetes**: 

**helm**:
```
Client: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
```

**kubernetes**:
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-17T20:48:54Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.4-1+1540c973d4ff9d", GitCommit:"1540c973d4ff9da2d6a204a7709084488a459ed4", GitTreeState:"clean", BuildDate:"2017-10-06T15:08:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
``` 

**Which chart**:

Spinnaker

**What happened**:

When installing 0.3.5 Spinnaker chart, as well as direct from source, the installation times out because of ```Error: timed out waiting for the condition```.  When I check the dashboard, it shows that the minio job is in an Error/Crash Backoff Loop, with the following logs on the job:

```
mc: Configuration written to ‘/root/.mc/config.json’. Please update your access credentials.
mc: Successfully created ‘/root/.mc/share’.
mc: Initialized share uploads ‘/root/.mc/share/uploads.json’ file.
mc: Initialized share downloads ‘/root/.mc/share/downloads.json’ file.
Added ‘spinnaker-minio’ successfully.
mc: <ERROR> Unable to make bucket ‘spinnaker-minio/spinnaker’. Your previous request to create the named bucket succeeded and you already own it.
```

Sometimes it say something about not being able to access the minio service.

Despite that, it seems like Spinnaker is otherwise functional, and the minio service is indeed up and happily running (based on the logs).  After forwarding Deck and Gate ports, I can load the Spinnaker web app.

**What you expected to happen**:

A successful installation.

**How to reproduce it** (as minimally and precisely as possible):

`helm install --name spinnaker stable/spinnaker`

**Comment by afirth** [comment]
I experienced the same problem on my test cluster but resolved it by increasing the node size. `Error: timed out waiting for the condition` (what condition) seems like a bug though. spinnaker docs say 8gb of ram in your nodes so... yeah.

**Comment by afirth** [comment]
digging in, when this happens I am getting a crashloopbackoff from minio
```
Logs from 
post-install-job
 in 
spinnaker-create-bucket-79nfz
 format_color_text  text_fields  timer_off  exposure_zero  file_download
mc: Configuration written to ‘/root/.mc/config.json’. Please update your access credentials.
mc: Successfully created ‘/root/.mc/share’.
mc: Initialized share uploads ‘/root/.mc/share/uploads.json’ file.
mc: Initialized share downloads ‘/root/.mc/share/downloads.json’ file.
Added ‘spinnaker-minio’ successfully.
mc: &lt;ERROR&gt; Unable to make bucket ‘spinnaker-minio/spinnaker’. Your previous request to create the named bucket succeeded and you already own it.
```

presumably caused by redis not starting:
```
PersistentVolumeClaim is not bound: "spinnaker-redis" (repeated 3 times)
AttachVolume.Attach failed for volume "pvc-[...]" : Error attaching EBS volume "vol-0ee2b42ccdafcb3a9" to instance "i-foo": IncorrectState: vol-0ee2b42ccdafcb3a9 is not 'available'. status code: 400, request id: 8f121942xx
```

**Comment by mickengland** [comment]
I was getting the same issue and discovered it could not bind the persistent volume claims because I did not have a default storage class set.

```
$> kubectl get pvc
spinnaker-jenkins    Pending                12m
spinnaker-minio      Pending                 12m
spinnaker-redis      Pending                  12m

$ kubectl describe pvc spinnaker-redis
Name:          spinnaker-redis
Namespace:     default
StorageClass:
Status:        Pending
Volume:
Labels:        app=spinnaker-redis
               chart=redis-0.9.0
               heritage=Tiller
               release=spinnaker
Annotations:   volume.alpha.kubernetes.io/storage-class=default
Capacity:
Access Modes:
Events:
  Type    Reason         Age                From                         Message
  ----    ------         ----               ----                         -------
  Normal  FailedBinding  2m (x42 over 13m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```           
After setting this according to the instructions at https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/ The volumes were correctly bound.

**Comment by grizzthedj** [comment]
@mickengland: Having this issue as well. In my case, I have no storage classes listed at all. I can easily add one, and set it to `default`, but which `provisioner` should be used for spinnaker storage?

**Comment by mickengland** [comment]
The storage class to use depends on where your kubernetes is hosted. I'm in AWS so I used kubernetes.io/aws-ebs.

**Comment by grizzthedj** [comment]
@mickengland: We are hosting our k8s cluster in our data center.

**Comment by mickengland** [comment]
@grizzthedj Here's a list of available storage classes with some configuration examples https://kubernetes.io/docs/concepts/storage/storage-classes/

**Comment by sylus** [comment]
Having this issue as well, on a 2 node cluster with Azure, each node has 16gb RAM. Oddly it does look like everything came up correctly.

**Comment by agnnn** [comment]
@sylus Any updates on the spinnaker deployment on Azure AKS ?? I am having the same issue with Azure.

**Comment by mattfarina** [comment]
cc @viglesiasce

**Comment by sylus** [comment]
@agnnn I noticed that everything still came up except for the create_bucket which stalled out. Unfortunately there was a larger bug with the Bake (Packer) option not working with the install. Still trying to work past that ^_^

**Comment by agnnn** [comment]
@sylus Can you share the vaules.yaml file which you used it to configure helm to use Azure storage. I am stuck at this point. :/

**Comment by davesykeselateral** [comment]
@agnnn - did you manage to get the right settings for the values.yaml for azure storage? Trying to do the same here now.

**Comment by mercantiandrea** [comment]
I have the same issue.
K8s 1.9.8 with kops on AWS. I have the default storage and the volumes are created.
Also on AWS console I can see the volumes created and correctly attached.

I have this error: 

PersistentVolumeClaim is not bound: "xxx-xxx-cicd" (repeated 4 times)
AttachVolume.Attach failed for volume "pvc-fb67c344-74d6-11e8-9fb8-02b1253df3ac" : "Error attaching EBS volume \"vol-066f56522a1806716\"" to instance "i-02149db619a239223" since volume is in "creating" state
