### ISSUE TITLE
superfluos slash

### ISSUE THREAD

**Issue by martinitus** [helm/charts#2517]
https://github.com/kubernetes/charts/blob/ec99fad17ec5f0764b6712237d3e6b9474581b52/incubator/kafka/templates/statefulset.yaml#L49

hey guys,
 nice work!
I was able to partially run this with minikube. I'm kind of a newb to kafka/helm and had to mess around with the statefull sets a little until it was working. 
One thing was removing this slash behind the zookeeper dns....
 no idea whether it is actually relevant 🗡 
hth Martin

**Comment by unguiculus** [comment]
The chart has changed a lot in the meantime. Feel free to create another issue if you still have problems.
