### ISSUE TITLE
reloading grafana when config changes

### ISSUE THREAD

**Issue by rileytg** [helm/charts#2522]
**Is this a request for help?**: no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Documentation of restarting stable/grafana when configmap changes OR use the same reloader that stable/prometheus is using.

**Version of Helm and Kubernetes**:
n/a

**Which chart**:
stable/grafana

**What happened**:
changed configmap

**What you expected to happen**:
it restarts the service (instead i kill the pod, wait for a new one)

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by PicoSushi** [comment]
Are there any updates for this?

**Comment by michalpiasecki1** [comment]
that  could be useful

**Comment by zanhsieh** [comment]
Either you guys use reloader:
https://github.com/stakater/Reloader

Or take the new feature from k8s 1.15 `rollout restart`
https://blog.questionable.services/article/kubernetes-deployments-configmap-change/

Helm chart does not have this feature.

**Comment by michalpiasecki1** [comment]
thanks, I did not know about this feature
