### ISSUE TITLE
Every chart should have some common values as requirement (Feature Suggestion)

### ISSUE THREAD

**Issue by jalberto** [helm/charts#2528]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

I suggest to require a minimum set of configurable attributes in every chart. This will make every chart configuration more familiar and every char more feature-complete.

Suggestions:
- affinity (pod and node)
- namespace
- resources

probably a common values.yml structure will be great too.

**Comment by dfcowell** [comment]
Namespace can be specified as part of the `helm install` command. The others would certainly be good though!
