### ISSUE TITLE
CI failing due to namespace name being > 63 chars

### ISSUE THREAD

**Issue by prydonius** [helm/charts#256]
The CI is currently failing because the `ghprbPullId` env var used in https://github.com/kubernetes/charts/blob/master/test/changed.sh#L23 is a large hash and causes the namespace name to be greater than 63 characters.

Example failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/charts/252/pull-charts-e2e/254/

I'm assuming the value of this env var changed recently. Should we truncate the value, or see if there is another env var we can use?

cc @viglesiasce @lachie83

**Comment by viglesiasce** [comment]
Yep being tracked here:
https://github.com/kubernetes/test-infra/issues/1202

First noticed in #223, once that goes through will switch to PULL_NUMBER.
