### ISSUE TITLE
[stable/locust] Chart not useful in current form - should there be a usefulness requirement for stable charts?

### ISSUE THREAD

**Issue by dfcowell** [helm/charts#2560]
I'll prefix this by saying that I might have missed something really obvious about Helm, but I've been reading docs and searching extensively for the past few hours and I've come up empty.

I guess this is part of a broader discussion around the purpose of this repo; namely, should charts be useful?

**Is this a request for help?**: No, unless I'm missing something...

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request? Open discussion?

**Which chart**: Specifically `stable/locust` but I've seen a similar issue with other charts.

The chart installs and runs with the default, bundled configuration but is absolutely useless because the behaviour of the packaged application is defined by files that are built into a ConfigMap and installed as part of the chart, when the whole point of the application is for the user to define their own behaviour via Python.

The only options that I can find for making the chart useful are:

- Maintain my own copy of the chart in a fork of this repo, which seems to defeat the purpose of Helm as a package manager,
- Create a subchart which removes and replaces the configMap with my own version, which seems hacky and could mess with upgrades, or
- Remove and replace the configMap on the cluster after installation which will **definitely** break after upgrades.

In my opinion, charts that make it to "stable" status should not just run, but also be able to support useful baseline functionality of the applications they install - otherwise what's the point?

Again, if I've missed something obvious, I apologise and would welcome a pointer in the right direction. :)

**Comment by adamresson** [comment]
Yeh I don't get this at all. Did you ever find a solution @dfcowell ?

**Comment by dfcowell** [comment]
I used the templates to produce my own manifests manually. After many cases
like this I'm very tempted to fork the repo and maintain my own charts,
bringing them in line with a usefulness standard on an as-I-need-it basis.

It seems like the Kubernetes charts project is more interested in ticking
boxes than providing actual utility, which is unfortunate.

Another issue I have is with bad legacy implementations (Deployments
instead of StatefulSets or DaemonSets) but that's another issue entirely.

**Comment by rdkr** [comment]
Just checking if anyone has an update on how they implemented the functionality this chart should provide? @dfcowell @adamresson 

I'm currently planning to see if I can make this useful and PR it or, failing that, to copy this over to my own repo and modify the tasks as needed.

Perhaps the original author, @so0k, can provide some further insight on this issue?

Cheers

**Comment by so0k** [comment]
What is blocking you?

**Comment by so0k** [comment]
Oh, I see, I'll read through this

**Comment by so0k** [comment]
Right, the files holding the Python scripts are part of the chart and I see now this only works when forked, I will look into making this more generic as this chart was created a Long time ago. Thanks for tagging me as I was not aware of any issues

**Comment by so0k** [comment]
I'd need to base off https://github.com/kubernetes/charts/pull/3288 I assume @haad @jdumars @unguiculus

**Comment by haad** [comment]
Yes that would be perfect.

**Comment by so0k** [comment]
After internal discussion within Honestbee, @joerx and I agree it would make more sense if the Locust tasks are part of the image provided by the user and not in a configmap. 

The way forward seems simply to remove the configmap (or make a configmap reference optional and external to the chart)

**Comment by dfcowell** [comment]
Personally my suggestion would be to ask for a configmap **name** which gets merged into the chart.

From there, people wanting to use the chart could just create their own configmap and reference it by name in `values.yml` when installing the chart.

That might be what you're talking about?

**Comment by ryandawsonuk** [comment]
The suggestion from @dfcowell would make sense to me as it would be in line with other charts such as how the keycloak chart allows a custom realm to be referenced

**Comment by ryandawsonuk** [comment]
The suggestion from @dfcowell would make sense to me as it would be in line with other charts such as how the keycloak chart allows a custom realm to be referenced. Would be great to get this reopened as there is demand to address this - https://stackoverflow.com/questions/53932412/how-to-integrate-custom-scripts-into-locust-helm-chart-stable-locust/53932594#53932594

**Comment by ryandawsonuk** [comment]
The suggestion from @dfcowell would make sense to me as it would be in line with other charts such as how the keycloak chart allows a custom realm to be referenced. Would be great to get this reopened as there is demand to address this - https://stackoverflow.com/questions/53932412/how-to-integrate-custom-scripts-into-locust-helm-chart-stable-locust
