### ISSUE TITLE
[stable/openvpn] Client configuration not compatible with NetworkManager

### ISSUE THREAD

**Issue by jalberto** [helm/charts#2561]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
2.6 & 1.7

**Which chart**:
openvpn

**What happened**:
Clint configuration is not compatible with NetworkManager import

**What you expected to happen**:
To import the file correctly

**How to reproduce it** (as minimally and precisely as possible):
just run suggested script

**Anything else we need to know**:
`dh` and `remote` tags are rejected, `remote` line needs to be split in `remote`, `proto`, `port`

**Comment by jakemccloskey** [comment]
This is still an issue. I currently have to manually extract the `dh` tag into a separate file and split out the `proto` into a separate line.
