### ISSUE TITLE
[stable/gitlab-ce] Gitlab won't initialize/start without a cert with https externalURL

### ISSUE THREAD

**Issue by andor44** [helm/charts#2579]
**Is this a request for help?**:
no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug (?)

**Version of Helm and Kubernetes**:
```
$ helm version; kubectl version
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-09-29T05:56:06Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0+coreos.0", GitCommit:"a65654ef5b593ac19fbfaf33b1a1873c0320353b", GitTreeState:"clean", BuildDate:"2017-09-29T21:51:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/gitlab-ce

**What happened**:
Specified an `externalUrl` with protocol `https`. The internal nginx couldn't start with error message: 
```
2017/10/24 12:07:21 [emerg] 970#0: BIO_new_file("/etc/gitlab/ssl/gitlab-test.preprod-local.ch.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/gitlab/ssl/<MY DOMAIN NAME HERE>.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

**What you expected to happen**:
The container to start correctly, or at the very least get a warning. I think giving a warning in NOTES.txt in case the user specifies a HTTPS URL is probably a good middle ground.

**How to reproduce it** (as minimally and precisely as possible):
```
$ helm install stable/gitlab-ce --values externalUrl=https://foo.bar
...
$ kubectl logs <pod name of gitlab instance>
```

**Anything else we need to know**:
Relevant issue on Gitlab's tracker: https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1509

**Comment by dodwyer** [comment]
@andor44 Have you followed the instructions here? : https://docs.gitlab.com/ee/install/kubernetes/gitlab_chart.html#https-configuration

I needed to add the following to `configmap.yaml`

```
  nginx['listen_port'] = 80
  nginx['listen_https'] = false
  nginx['proxy_set_headers'] = {
    "X-Forwarded-Proto" => "https",
    "X-Forwarded-Ssl" => "on"
  }
```

**Comment by andor44** [comment]
Now I know, but I think this should be documented on the chart, as it wasn't immediately obvious to me why it wouldn't initialize with a seemingly valid configuration.
