### ISSUE TITLE
Airflow Chart

### ISSUE THREAD

**Issue by gsemet** [helm/charts#2591]
Hello

I am working on an Helm Chart for Kubernetes. You can find my proposal on [kube-airflow#16](https://github.com/mumoshu/kube-airflow/pull/16). I plan to use this project to land it first, and then prepare a clean Helm chart here if you agree. I see plenty of pending Pull Request on this project, can I get some hints on how to help the integration ?

**Comment by unguiculus** [comment]
Don't hesitate to create a PR for a new chart. Make sure you follow best practices. If you use `helm create` with Helm 2.7+ you'll get an initial experience with current best practices applied.

https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md
https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

**Comment by gsemet** [comment]
I still want to work on it. The change I needed has been integrated into airflow mainline, so I can now make the official PR to helm :)

**Comment by gsemet** [comment]
damned! Please so not close it yet, we are almost ready to publish :)

**Comment by knuckolls** [comment]
fwiw i am willing to be a beta tester of this helm chart as we are likely about to go all in on an airflow / kube stack.

**Comment by gsemet** [comment]
Hi. You can have a look at this version: [gh:gsemet/kube-airflow@helm_chart](https://github.com/gsemet/kube-airflow/tree/helm_chart).

**Comment by gsemet** [comment]
I am aligning the Helm chart in [gh:gsemet/kube-airflow](https://github.com/gsemet/kube-airflow) (master branch) with the WIP I am submitting here in #3959. Still some work to do.

**Comment by techdiverdown** [comment]
I would be interested in testing as well as we are moving to airflow on K8.

**Comment by gsemet** [comment]
Feel free to test and give me your feedback !

**Comment by maver1ck** [comment]
Same in my situation.

**Comment by gsemet** [comment]
For me the mergerequest is ready to merge. Need an approver

**Comment by maver1ck** [comment]
Are we going to merge this ?

**Comment by timshoaf** [comment]
Would really love to see this included.

**Comment by maver1ck** [comment]
@unguiculus ?

**Comment by gsemet** [comment]
Hello. Can you please reopen it ? This pull request is pretty stable and used in production, and is ready to be merged. Please someone review it ?

**Comment by maver1ck** [comment]
@rolanddb  ?

**Comment by rolanddb** [comment]
Not sure if this will work.

I am not in a position to merge this or reopen it. I do not maintain this repo.

I've personally put quite some effort in the chart and would like to see it merged. But I'm not sure what it will take to convince someone to merge it.

**Comment by gsemet** [comment]
sadly i do not get anyone to review this pull request :(

**Comment by ttelfer** [comment]
Our company is interested in pursuing Airflow+kubernetes. Could someone describe to me how I would got about testing this branch?

**Comment by gsemet** [comment]
Hi. You can download (git clone) it and use with helm directly (as I do in my compagny)

**Comment by ttelfer** [comment]
@gsemet Would you be able to describe how to get helm to install airflow from the repo that was cloned. I attempted to run from the root of your cloned repo:

`helm install --namespace "airflow" --name "airflow" incubator/airflow`

and received the error:

`Error: found in requirements.yaml, but missing in charts/ directory: postgresql, redis`

Any suggestions?

**Comment by gsemet** [comment]
it it not yet merged so it is not in incubator/airflow.

You need to clone and then use helm install ... ./charts/incubator/airflow/

**Comment by gsemet** [comment]
+1

**Comment by barakyo** [comment]
+1

**Comment by paulyhedral** [comment]
+1

**Comment by StraylightSky** [comment]
+1

**Comment by gsemet** [comment]
Please vote on the MR, it is almost ready :) do not hesitate to test latest version and tell if you use it in production !

**Comment by luthes** [comment]
I'm having an issue with this where I'm getting not getting the output from the NOTES.txt, looks like the templated values aren't populating. 
```
Congratulations. You have just deployed Apache Airflow
   export POD_NAME=$(kubectl get pods --namespace airflow1 -l "component=" -o jsonpath="{.items[0].metadata.name}")
   echo http://127.0.0.1:
   kubectl port-forward --namespace airflow1 $POD_NAME :

2. Open Airflow in your web browser
```

I can get the first one to populate this command: `kubectl get pods --namespace airflow1 -L "component" -o jsonpath="{.items[0].metadata.name}"`

Unless I'm mistaken, `.Values.airflow.name` doesn't exist in the values.yaml, if that's where it should come from. Is there some updating that needs done to the NOTES.txt file?

I'm running this on AWS EKS, so k8s 1.10.3.

Thanks.

**Comment by limnick** [comment]
+1

**Comment by tedohayer** [comment]
+1 we have been running this PR in prod since October and its been great

**Comment by gsemet** [comment]
Chart is now merged :) Thanks for all your help !
