### ISSUE TITLE
Create Infrastructure for Charts CI

### ISSUE THREAD

**Issue by viglesiasce** [helm/charts#26]
The infrastructure will consist of:
- [x] An autoscaled GKE cluster for running jobs, running the latest 
- [ ] Jenkins instance that monitors PRs on this repo and runs them through a predefined pipeline of tests
- [x] A GCS bucket for storing the the chart tarballs

**Comment by chrislovecnm** [comment]
Where are we going to maintain the Jenkins pipeline from?  Jenkins file in this repo??

**Comment by viglesiasce** [comment]
Yep that is the current plan.

**Comment by viglesiasce** [comment]
Closing this as we will leverage the main Kubernetes CI infra.
