### ISSUE TITLE
clusterIP: "" should not be generated in services

### ISSUE THREAD

**Issue by mooperd** [helm/charts#2607]
@aledbf asked me to create this ticket. - https://github.com/kubernetes/ingress-nginx/issues/1612
It seems that `clusterIP: ""` is an internally generated, immutable value.

**Comment by denis111** [comment]
I have the same issue. It's impossible to just upgrade nginx-ingress chart. I always have to delete and create new one. Please /reopen ;)

**Comment by matthias-k** [comment]
Same here

**Comment by matthias-k** [comment]
Interestingly, when upgrading I get the error message `Error: UPGRADE FAILED: Service "killer-gnat-nginx-ingress-controller" is invalid: spec.clusterIP: Invalid value: "": field is immutable`. However, in the service `...-nginx-ingress-controller`, `spec.clusterIP` is not rendered at all, as visible via `helm template`. It is specified in the service  `...-nginx-ingress-default-backend`, which doesn't give an error. I just adapted the chart to remove it from the default backend as well and now `helm upgrade` complains about both services.

**Comment by matthias-k** [comment]
yes, I just confirmed: When I remove [this check](https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-service.yaml#L21), then the empty `clusterIP` *is* rendered into the service and the upgrade completes. This contradicts the error message... Also, I'm not sure wheter the check still should be there and maybe check for `nil`.

**Comment by JessieAMorris** [comment]
Confirmed that I'm seeing that same issue. Reverting to 0.30.0 chart version fixes this issue for me.

**Comment by nseyvet** [comment]
Same problem here.
