### ISSUE TITLE
OpenVPN and Minikube

### ISSUE THREAD

**Issue by rroopreddy** [helm/charts#2613]
**Request for help:**

What is the best way to configure OpenVPN chart for Minikube

1. Started the OpenVPN with

    helm install --set service.type=NodePort stable/openvpn

2. Need to expose the both `pod cidr (172.17.0.0/24) and service cidr (10.0.0.0/24 )` through VPN. What is the best way to pass these parameters

Thank you!
Ravi R

**Comment by bbakersmith** [comment]
+1
