### ISSUE TITLE
[jenkins] Support for multiple ingress

### ISSUE THREAD

**Issue by marckhouzam** [helm/charts#2617]
FEATURE REQUEST:

It would be useful for the stable/jenkins chart to support multiple ingress host entries.
There are scenarios where multiple host names can be used to reach the same Jenkins.

**Comment by timothyclarke** [comment]
Jenkins itself doesn't work well with this. 
While you can map multiple vhosts, jenkins itself has "Jenkins Location / Jenkins URL" within it's own config. When it generates links to jobs it will use that configured value so will cause issues with the above.
There's also issues if you're using JNLP clients

**Comment by orco49** [comment]
> Jenkins itself doesn't work well with this.
> While you can map multiple vhosts, jenkins itself has "Jenkins Location / Jenkins URL" within it's own config. When it generates links to jobs it will use that configured value so will cause issues with the above.
> There's also issues if you're using JNLP clients

Hey,
Was this problem solved?

**Comment by timothyclarke** [comment]
@orco49 I don't know if anyone has raised this with the upstream project. From my previous use of jenkins, it's designed to live on one url.

**Comment by marckhouzam** [comment]
We've been using two URLs for Jenkins at work for a while now.  It would be nice if the chart supported it.
