### ISSUE TITLE
[redis] Add inital pod to configure system

### ISSUE THREAD

**Issue by jalberto** [helm/charts#2633]
**Is this a request for help?**:
no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
feature request

**Version of Helm and Kubernetes**:
2.6 & 1.7

**Which chart**:
redis

**What happened**:
After install this is in logs:

```
WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled
```

**What you expected to happen**:
Redis chart should have an InitContainer to prepare system for deploy

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by desaintmartin** [comment]
I would like to reopen this bug.
@prydonius @tompizmor @sameersbn @carrodher @juan131 would you consider merging a PR with an initContainer in privileged mode that does this? If so it can easily be done.

**Comment by Sceat** [comment]
@prydonius @tompizmor @sameersbn @carrodher @juan131 can you take a look to this issue ? i just installed the chart and it's still hapenning
