### ISSUE TITLE
Jenkins with nginx ingress

### ISSUE THREAD

**Issue by kaosmonk** [helm/charts#2635]
Hi,

I am trying to run jenkins with nginx cluster and with TLS enabled in k8s that I am running in GCE. The main changes I did to `values.yaml` file are:
- I have set `ServiceType` to `ClusterIp`
- also have specified the `HostName`
- have enabled `Ingress` part, including `Annotations` and `TLS` and set the same value for `secretName` and `hosts` under `TLS` as I did set for `HostName`

So this is how (relevant part of) my config looks like:
```
  ServiceType: ClusterIP
  HostName: jenkins-in-the-kube.int.example.net
  Ingress:
    Annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"

    TLS:
      - secretName: jenkins-in-the-kube.int.example.net
        hosts:
          - jenkins-in-the-kube.int.example.net
``` 

Everything seems to work when it comes to deploying it all with `helm` but for some reason my ingress doesn't get the public IP assigned for some reason. Here are some of the outputs that might be helpful with troubleshooting this:

```
$ kubectl -n jenkins-test describe services
Name:			pipelines-gce-test-jenkins
Namespace:		jenkins-test
Labels:			app=pipelines-gce-test-jenkins
			chart=jenkins-0.1.0
			component=pipelines-gce-test-jenkins-master
			heritage=Tiller
			release=pipelines-gce-test
Annotations:		<none>
Selector:		component=pipelines-gce-test-jenkins-master
Type:			ClusterIP
IP:			10.31.240.6
Port:			http	8080/TCP
Endpoints:		10.28.2.15:8080
Session Affinity:	None
Events:			<none>


Name:			pipelines-gce-test-jenkins-agent
Namespace:		jenkins-test
Labels:			app=pipelines-gce-test-jenkins
			chart=jenkins-0.1.0
			component=pipelines-gce-test-jenkins-master
Annotations:		<none>
Selector:		component=pipelines-gce-test-jenkins-master
Type:			ClusterIP
IP:			10.31.241.63
Port:			slavelistener	50000/TCP
Endpoints:		10.28.2.15:50000
Session Affinity:	None
Events:			<none>
```

```
$ kubectl get services --namespace jenkins-test
NAME                               CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE
pipelines-gce-test-jenkins         10.31.240.6    <none>        8080/TCP    35m
pipelines-gce-test-jenkins-agent   10.31.241.63   <none>        50000/TCP   35m
```

```
$ kubectl describe ing pipelines-gce-test-jenkins -n jenkins-test
Name:			pipelines-gce-test-jenkins
Namespace:		jenkins-test
Address:
Default backend:	default-http-backend:80 (10.28.1.5:8080)
TLS:
  jenkins-in-the-kube.int.example.net terminates jenkins-in-the-kube.int.example.net
Rules:
  Host					Path	Backends
  ----					----	--------
  jenkins-in-the-kube.int.example.net
    					 	pipelines-gce-test-jenkins:8080 (<none>)
Annotations:
Events:	<none>
```

```
$ kubectl -n jenkins-test get ing
NAME                         HOSTS                                  ADDRESS   PORTS     AGE
pipelines-gce-test-jenkins   jenkins-in-the-kube.int.example.net             80, 443   31m
```

In the last output for ingress I'm not getting any public IP assigned. IF I for example go with `LoadBalancer` instead of `ClusterIP` for `ServiceType` I get the public IP assigned and I am able to access my Jenkins setup on port 8080.

So what am I doing wrong and what am I missing here?

Cheers!

**Comment by techgeek03** [comment]
Having the same issue, how did you resolve it?

**Comment by kaosmonk** [comment]
One thing I haven't noticed is that I've had an issue with nginx ingress controller in my env - as soon as I've fixed it, my jenkins ingress got the public IP address.

**Comment by sellers** [comment]
If you set the ServiceAnnocations:  to add   
    service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"

it creates an internal load balancer in your VPC.

**Comment by jderuere** [comment]
@kaosmonk What do you mean by having an issue. I have the same problem and don't know how to fix it.
