### ISSUE TITLE
stable/traefik: support Traefik HTTPS SNI

### ISSUE THREAD

**Issue by javefang** [helm/charts#2637]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

This is a feature request. I'm happy to provide a PR if the proposal looks OK.

We have an on-permise deployment of Kubernetes which uses Traefik as the cluster edge routers. In our case we have 2 dedicated worker node in the cluster which is tainted to allow only Traefik to run on them. We then point the hardware load balancer (TCP) to the node port (30433) of both nodes for resilience.

In case we need to expose Kube services via Ingress. We create CNAMEs which points to the DNS name of the hardware load balancer, then rely on Traefik's SNI (https://docs.traefik.io/configuration/entrypoints/#redirect-http-to-https) to decides how to route the requests. Here Traefik performs the SSL termination.

This set up works well for us. To achieve this, we need to add a section in the configmap template to populate a list of `[[entryPoints.https.tls.certificates]]` section with list of certificates to load, a Secret to store the certificates, and chart options to enable SNI and to provide the certs. For example:

Currently, to use a default cert, we have
```
ssl:
  enabled: true
```

To support SNI for cert signed for DNS name "foo" and "bar", it can be
```
ssl:
  enabled: true
  certificates:
    foo:
      cert: <cert_foo_content>
      key: <key_foo_content>
    bar:
      cert: <cert_bar_content>
      key: <key_bar_content>
```

This should then populate 3 `[[entryPoints.https.tls.certificates]]` section in the Traefik config where the first one will be the default cert, and the other two for "foo" and "bar". This should make sure the behaviour is backward compatible to the current chart.

**Version of Helm and Kubernetes**:
Helm 2.7.0
Kubernetes 1.8.2

**Which chart**:
stable/traefik

**Comment by javefang** [comment]
PR submitted

**Comment by krancour** [comment]
@javefang I'm reasonably certain you don't need to make _any_ changes to this chart to accomplish what it is you're looking to do. If you add secrets in Kubernetes that contain your certs, you can reference those secrets from your ingress resources and Traefik should seamlessly handle the rest.

https://kubernetes.io/docs/concepts/services-networking/ingress/#tls

**Comment by javefang** [comment]
@krancour I'm under the impression that this feature hasn't been implemented yet (https://github.com/containous/traefik/issues/378). Have you had a chance to try the method proposed?

**Comment by The-Loeki** [comment]
It was merged in https://github.com/containous/traefik/pull/2439 (due for 1.6)

**Comment by javefang** [comment]
Thanks! Can't wait to see it merged :) I'll close this one.
