### ISSUE TITLE
[stable/heapster] typo in NOTES.txt causing error when a command is copy-pasted

### ISSUE THREAD

**Issue by kachkaev** [helm/charts#2653]
**Version of Helm and Kubernetes**:

```
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/heapster

**What happened**:

After running helm install, I saw the following notes in the output:

```
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace kube-system -l "app=heapster" -o jsonpath="{.items[0].metadata.name}")
  kubectl --namespace kube-system port-forward $POD_NAME 8082
```

However, copying and pasting these notes to the terminal caused:

```bash
export POD_NAME=$(kubectl get pods --namespace kube-system -l "app=heapster" -o jsonpath="{.items[0].metadata.name}")
# error: error executing jsonpath "{.items[0].metadata.name}": array index out of bounds: index 0, length 0
kubectl --namespace kube-system port-forward $POD_NAME 8082
# Error from server (NotFound): pods "Error" not found
```

I guess the error happens because the first command mentiones  `"app=heapster"` instead of `"app=heapster-heapster"`, which is assigned to the pod. I suspect that the only thing that needs to be done is replacing ` template "heapster.service.fullname"` with `template "heapster.fullname"` in [NOTES.txt](https://github.com/kubernetes/charts/blob/8f1078864a467548fb21f25e84b1de3d0ddda716/stable/heapster/templates/NOTES.txt), but I'd like to discuss this first since I'm new to the chart.

/cc @jose5918 @kevinschumacher @thedebugger

**Comment by satishsudini** [comment]
Same issue i am facing when i am port forwarding my spinnaker . 

error: error executing jsonpath "{.items[0].metadata.name}": array index out of bounds: index 0, length 0
