### ISSUE TITLE
Grafana LDAP config

### ISSUE THREAD

**Issue by randrewedwards** [helm/charts#2656]
**Is this a request for help?**: Yes

What's the best way to upload the ldap.toml file for grafana? I see it's referenced in grafana.ini as a serverConfigFile. I've tried creating an additional config file but to no success.

Anyone tried this and been successful?

**Comment by jhdehart** [comment]
Not the best solution, but you can create a ConfigMap with the configuration files and add them to the deployment after your initial chart installation.  This worked for me.

**Comment by audip** [comment]
Yes, we are doing ConfigMap for defaults.ini and ldap.toml and it works.

**Comment by marckhouzam** [comment]
When you override `serverConfigFile:` to add your own grafana.ini, you can also put an entry for ldap.toml with all the text following it.  Both files, grafana.ini and ldap.toml, will be injected into the configmap of the helm chart, and both files will appear under /etc/grafana. 

So, my override file looks like this:
```
serverConfigFile:
  grafana.ini: |
    ; instance_name = ${HOSTNAME}
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins

    [auth.ldap]
    enabled = true
    config_file = /etc/grafana/ldap.toml

[ the rest of the grafana.ini file ]

  ldap.toml: |
    # Set to true to log user information returned from LDAP
    verbose_logging = false

    [[servers]]
    # Ldap server host (specify multiple hosts space separated)
    host = "127.0.0.1"

[ the rest of the ldap.toml file ]
```

**Comment by rr-paras-patel** [comment]
@marckhouzam have you tested that development around  serverConfigFile ?

**Comment by marckhouzam** [comment]
@PatelParas I've been using it for three months. Works great.
