### ISSUE TITLE
[stable/prometheus] Consider splitting global section of alermanager config

### ISSUE THREAD

**Issue by olvesh** [helm/charts#2667]
**Is this a request for help?**:
---
yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
1.8.2
2.7.0

**Which chart**:
stable/prometheus

**What happened**:
As alertmanager does not support handling configuration elements as environment variables (https://github.com/prometheus/alertmanager/issues/504#issuecomment-246761308), secrets handling is a bit cumbersome since the alertmanager config-map is stored in a text blob, and both the configuration and the API keys would have to be encrypted together. 
To be able to store secrets for APIs used separately you have to use a custom config map and split the global section of alertmanager and assemble in the custom config map.. 

**What you expected to happen**:
If the global section of alertmanager config was a separate entity in the config values it would be easy to put the secret values in a separate (possibly encrypted) values.yaml file without introducing a custom configmap. 

As the global section mainly deals with integration towards [external APIs](https://prometheus.io/docs/alerting/configuration/#configuration-file) it shoudl be fairly easy to hva that as a separate section.
 
**How to reproduce it** (as minimally and precisely as possible):
Separate API secrets from configuration of alertmanager

**Anything else we need to know**:

**Comment by balboah** [comment]
Another idea I haven't thought through in detail but that could also solve this is to be able to merge multiple config files, so you could split them in any way you like. I mean something like `conf.d/slack.yaml` and `conf.d/global.yaml` to be merged together as one.

**Comment by olvesh** [comment]
True, that might work as well.  A bit more involved setup though. 

I am currently trying to make an umbrella chart to solve this now, having a base chart depending on this (prometheus) + a chart setting only the configmap as I want it.

I hit a wall on that approach since the `.Release.Name` is used when creating a config map from a chart, and I have to specify the same `.Release.Name` into the `.Values.alertmanager.configMapOverrideName` variable to hook them together. Since the `values.yaml` can't be templated I can't access  that value (I think). OR i have to drop the `.Release.Name` from my separate config chart.

 I'll see if I can add a PR for my current work.

**Comment by olvesh** [comment]
Doesn't help me to split the global section anyway, as Pagerduty (and OpsGenie for that sake) has the api-key as part of the specific config and not in the global section as most other integrations.

**Comment by olvesh** [comment]
If only Brian Brazil would change his mind :-) https://github.com/prometheus/alertmanager/issues/504#issuecomment-342148260
