### ISSUE TITLE
[incubator/kafka] Kafka terminated by liveness probe on network glitch, index corrupted

### ISSUE THREAD

**Issue by valer-cara** [helm/charts#2682]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}

$ k version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
incubator/kafka

**What happened**:
The liveness probe failed to resolve the zookeeper service's hostname when trying to list the kafka topics. Kafka was running without an issue, but still due to the probe failure, it was terminated (quite abruptly since on restart there were some corrupted indexes)

The NS issue lasted a bit so the logs below are from a subsequent restart, failing on the readiness probe in the same manner.
```
  FirstSeen	LastSeen	Count	From				SubObjectPath			Type		Reason		Message
  ---------	--------	-----	----				-------------			--------	------		-------
  17m		17m		1	kubelet, k8s-agent-29113125-0	spec.containers{kafka-broker}	Warning		Unhealthy	Readiness probe failed: [2017-11-07 12:36:49,164] WARN Client session timed out, have not heard from server in 30004ms for sessionid 0x0 (org.apache.zookeeper.ClientCnxn)
Exception in thread "main" org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server 'kafka-zookeeper:2181' with timeout of 30000 ms
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:103)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:85)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:55)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
```

I'm still tracking down the name resolution problem, I think it's actually a network glitch since the kube-dns pods are running w/o issues.

**What you expected to happen**:
The liveness probe should pass while kafka is running without issues. What if it'd use `./bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092` instead, so it only relies on the running kafka? (I'm not sure if this is a suitable readiness probe, just a thought.)

Second, the shutdown should be graceful, perhaps by using `./bin/kafka-server-stop.sh` like:
```
lifecycle:
  preStop:
    exec:
      command: ["./bin/kafka-server-stop.sh"]
```

**How to reproduce it** (as minimally and precisely as possible):
Force a DNS outage :boom: `kubectl scale deploy --namespace kube-system -l k8s-app=kube-dns --replicas=0`

**Anything else we need to know**:

**Comment by benjigoldberg** [comment]
@valer-cara can you check now that this issue is resolved? The liveness probe now uses a proper TCP check instead of the heavier check that would have required DNS

**Comment by valer-cara** [comment]
@benjigoldberg - Cool! As stated, that's a rare network glitch which I wasn't able to track down, but this _should_ resolve those situations. Thank you for the fix! :100:

**Comment by t-d-d** [comment]
@valer-cara I ran into a problem with the tcp check - after a broker restart it can take a long time fixing up corrupted indexes and the port isn't open until it is done.  This means it gets stuck in a restart loop.

The below seems to work OK for me.  Also, isn't the socket check more appropriate for the readiness probe?
```
        livenessProbe:
          exec:
            command:
              - sh
              - -ec
              - /usr/bin/jps | /bin/grep -q SupportedKafka
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          timeoutSeconds: 5
```

 If you agree I can raise a PR.

**Comment by valer-cara** [comment]
@t-d-d i'm not sure _when_ exactly kafka opens up the socket and whether that's a reliable way to determine readiness. Do all versions behave the same? (not sure if that's documented behavior to rely on)

Re. the liveness probe killing the container, there's some debate whether to make liveness probes execute after container is ready (https://github.com/kubernetes/kubernetes/issues/27114), which would solve your problem, but that's still open.

**Comment by t-d-d** [comment]
@valer-cara @benjigoldberg  I don't know when the socket gets opened either - I'm no Kafka expert.  But I do know that in the current version of Kafka included in the chart, it gets opened only _after_ indexes rebuilding which is a big problem.

https://github.com/kubernetes/kubernetes/issues/27114 would help if we had a robust Readiness probe.  But the current implementation is just testing Zookeeper, isn't it?  I don't see how that is helpful.

There may not be a perfect solution right now but I think the current implementation needs to change.

Also see related https://github.com/kubernetes/charts/issues/3697 about how expensive the current readiness check is.

**Comment by benjigoldberg** [comment]
@t-d-d I like the idea of the liveness check change. The usage of jps to find the running process seems like a good way to get a good heads/tails on whether or not the pod is alive. What I'm somewhat less sure about is whether the readiness probe is really enough. Like @valer-cara I'm not sure where in the lifecycle kafka binds to 9092... that being said I also agree with you that the kafka topic list is not necessarily the best choice either, since it does essentially just talk w/ zookeeper. 

Can you open a PR with your changes? I would love to play around with this, and there may be a few others who would as well. I'll read up more on the tcp portion to see if thats acceptable.
