### ISSUE TITLE
[incubator/istio] Status of istio 0.2.7-chart5; chart plans for 0.2.7 and later istio versions

### ISSUE THREAD

**Issue by tjquinno** [helm/charts#2689]
**Is this a request for help?**:
Request for clarification.

This page https://kubeapps.com/charts/incubator/istio lists various versions for the Istio 0.2.7 chart (`chart-1` through `chart-5` currently) with dates next to each.

On that page it seems that `chart-5` is refreshed daily, more like a maven-style SNAPSHOT than an identifiable stable version, and this is borne out by the entry for the chart in the `index.yaml` here: https://kubernetes-charts-incubator.storage.googleapis.com

Earlier `chart-x` entries seem more stable, at least with respect to their dates.

Some questions:

1. Is the `chart-5` behavior intentional, meaning we should treat it as a SNAPSHOT, with `chart-4` the most recent identifiable build?

2. Is there an ETA for a stable Istio 0.2.7 chart without the `chart-x` suffix?

3. Istio itself is up to 0.2.12 as of today. What are the plans for the public Istio Helm charts tracking those later Istio versions?

I apologize if this information is posted somewhere. I've looked for it and would welcome a link to it.

Thanks.

**Comment by tjquinno** [comment]
Interestingly, today (Nov. 9) there is a 0.2.7-chart5 dated today and now a new 0.2.7-chart6 (also dated today).

Can someone help us understand the overall plan for the istio chart?

**Comment by oemdaro** [comment]
I see all Charts not just istio in [kubeapps.com](https://kubeapps.com) update released date to current date every day. This is a bug of [kubeapps.com](https://kubeapps.com) ?
