### ISSUE TITLE
[incubator/kafka] offsets and transaction log topics' replication factor hardcoded to 1

### ISSUE THREAD

**Issue by charlesverdad** [helm/charts#2697]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
helm: 2.6.2
k8s: 1.7.5

**Which chart**:
incubator/kafka

**What happened**:

Inside the docker image, the file `/opt/kafka/config/server.properties` contain:

```
############################# Internal Topic Settings  #############################
# The replication factor for the group metadata internal topics "__consumer_offsets" and "__transaction_state"
# For anything other than development testing, a value greater than 1 is recommended for to ensure availability such as 3.
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
```
Both replication factors are hardcoded to 1 and is not being replaced by the "Replicas" variable in values.yaml

**What you expected to happen**:

I expect the replication factor to be changed depending on the value I assign to the variable `Replicas` (or some other variable).

**Anything else we need to know**:

Normally the settings are being overriden in the command part of `statefulset.yaml`

```
        command:
        - sh
        - -c
        - "./bin/kafka-server-start.sh config/server.properties --override zookeeper.connect={{ .Release.Name }}-zookeeper:2181/ --override log.dirs={{ printf "%s/logs" .Values.DataDirectory }} --override broker.id=${HOSTNAME##*-}"
```

It would be great if there's an "additionalParameters" variable to append to the command.

**Comment by benjigoldberg** [comment]
@charlesverdad we've provided the ability to set configuration overrides in the chart now which should allow you to change these values -- can you check that it satisfies the concerns you've posted here?
