### ISSUE TITLE
Create pipeline for testing charts periodically and on PR submission

### ISSUE THREAD

**Issue by viglesiasce** [helm/charts#27]
The pipeline will need to do the following (at a minimum):
- [x]  Check out the code
- [x]  Run the helm linter against the chart under test
- [x] Deploy the chart in its own namespace
- [x] Validate that the chart is up and running
- [x] Push the chart to the storage bucket once it has been validated

The validation step can be very simple to begin with and get more complex as we coordinate the interface between what CI needs to implement and what Helm CLI can do (ie post install scripts/checks).

**Comment by chrislovecnm** [comment]
Do we want to pull our of docker hub or have the images in gcr.io.  At times dockerhub is not reliable, and has borked the e2e testing with k8s.  I would rather run the images out of gcr.io.

**Comment by viglesiasce** [comment]
I don't think we can/should _require_ a particular registry for now. We could certainly recommend one though.

**Comment by chrislovecnm** [comment]
Can gcr.io proxy / cache DockerHub?

**Comment by viglesiasce** [comment]
GCR does not currently implement DockerHub caching.

This will need to be implemented in the test folder (which is added in #45) as a bash script in order to fit nicely with the main Kubernetes CI infra.

**Comment by viglesiasce** [comment]
Closing as this is now in place.
