### ISSUE TITLE
[stable/prometheus] Upgrade to Prometheus 2

### ISSUE THREAD

**Issue by jpds** [helm/charts#2712]
The stable/prometheus chart needs to be upgraded to Prometheus 2, I've tried to do this myself, however here's a list of interesting things that broke:

 * Alertmanagers are now configured in the Prometheus config, not via command line options. `prometheus-server` logs:

```
Error parsing commandline arguments: unknown long flag '--alertmanager.url'
prometheus: error: unknown long flag '--alertmanager.url'
```

 * `storage.local.path` is no longer a prometheus-server option:

```
Error parsing commandline arguments: unknown long flag '--storage.local.path'
prometheus: error: unknown long flag '--storage.local.path'
```

**Comment by jpds** [comment]
@mgoodness This may be useful to you.

**Comment by thuandt** [comment]
Prometheus 2.0 has new storage data format which can't migrate from Prometheus 1.x.

2.0 version use kingpin so args is total different. see `prometheus --help`

As i known, we can't just `helm upgrade` to 2.0, we must create new one.

**Comment by jurgenweber** [comment]
I agree with @thuandt we need to create a new prometheus2.0 chart so prometheus 1 and 2 can be run in parrallel. Options should also be made avilable so you can do a migration from 1 to 2.

https://prometheus.io/blog/2017/11/08/announcing-prometheus-2-0/
https://prometheus.io/docs/prometheus/2.0/migration/

**Comment by benmathews** [comment]
I'm getting started w/ prometheus and want both 2.0 and helm. I'll work on the new chart in my fork. I assume it should go into the incubator?

**Comment by benmathews** [comment]
This is still a work in progress. I'm running going to run it in our prod cluster and see if anything breaks. I've no intention of polishing it beyond what I need. Hopefully it can serve as a foundation for others to improve on though. I'll file a pull request once I've done as much as I intend to.
https://github.com/benmathews/charts/tree/prometheus2.0/incubator/prometheus

**Comment by benmathews** [comment]
I didn't realize that there was another pr that is active. This should be closed.

**Comment by thuandt** [comment]
FYI, new version of AlertManager has been released which use kingpin like Prometheus Server.

https://github.com/prometheus/alertmanager/releases/tag/v0.13.0

**Comment by jstoja** [comment]
https://github.com/kubernetes/charts/pull/2767 is already in progress and working our tests envs.

**Comment by thuandt** [comment]
This issue should be close because #2767 already merged
