### ISSUE TITLE
[incubator/vault]

### ISSUE THREAD

**Issue by lvicentesanchez** [helm/charts#2716]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST.

**Version of Helm and Kubernetes**:
Helm: 2.7.0
Kubernetes: 1.6.2

**Which chart**:
charts/incubator/vault

**What happened**:
You can't configure HA using forwarding (no easy way to provide a cluster_addr for each pod)

**What you expected to happen**:
I should be able to configure HA using forwarding.

**How to reproduce it** (as minimally and precisely as possible):
Deploy a 3 node vault with an ingress name and after unsealing all nodes try to create or read any value.

**Anything else we need to know**:
No.

**Comment by jacobkiers** [comment]
It seems this would be solved with #2739.

**Comment by sfrique** [comment]
I've also proposed a few changes.
But i got no answer at that PR.

@lvicentesanchez I have a working vault cluster configured with HA and forwarding mode.

It seems there was a few other changes to the vault chart after the PR, but doesn't solve the issues.

**Comment by lvicentesanchez** [comment]
yes, that PR would do the job

**Comment by lvicentesanchez** [comment]
@sfrique do you have the helm chart in any github repo/gist that I could use as a reference?

**Comment by sfrique** [comment]
My repo is private.

Just the differences i comment there!

All other differences are at `values.yml` but you should use your own.
Basic differences at values: 
replica to 3
enable ingress and set it up
dev: false
consul as a backend. (also at kubernetes)

OBS: Do mind that my diff need to have ingress enabled.

```
$ diff -r /home/sfrique/Git-Projects/SonicCloud/devops2/kubernetes/vault incubator/vault
diff -r mine/incubator/vault/templates/deployment.yaml incubator/vault/templates/deployment.yaml
31c31,33
<         command: ["vault", "server", "-config", "/vault/config/config.json"]
---
>         command: ["sh", "-c"]
>         args:
>           - export VAULT_CLUSTER_ADDR="http://$POD_IP:8201"; vault server -config /vault/config/config.json
40c42
<               path: /v1/sys/health?standbycode=299
---
>               path: /v1/sys/health
52,55d53
<           - name: VAULT_CLUSTER_ADDR
<             value: "http://$(POD_IP):8201"
<           - name: VAULT_API_ADDR
<             value: "https://{{ index .Values.ingress.hosts 0 }}"
```

**Comment by lvicentesanchez** [comment]
Thank you very much! That's indeed helpful.

**Comment by sfrique** [comment]
If it works for you, You may close the issue.

Hopefully that PR will be updated. If i don't get answer for the next few days, I will probably make a new PR for it.

**Comment by lvicentesanchez** [comment]
@sfrique it worked, but I had to use this as the livenessProbe endpoint `/v1/sys/health?sealedcode=204&standbycode=204&uninitcode=204`.

**Comment by sfrique** [comment]
I've comment at PR! 
If I understood correctly, it was at readynessProbe.
