### ISSUE TITLE
[stable/sonatype-nexus] pod resources mentioned in values.yaml take no effect

### ISSUE THREAD

**Issue by kachkaev** [helm/charts#2731]
**Which chart**:

[sonatype-nexus](https://github.com/kubernetes/charts/tree/master/stable/sonatype-nexus)

**What happened**:

Looking into [`values.yaml`](https://github.com/kubernetes/charts/blob/38ff2dfcdaf020a2cc09a9e477ecb830d278bb7b/stable/sonatype-nexus/values.yaml) suggests that pod resources can be configured, however they [take no effect](https://github.com/kubernetes/charts/blob/38ff2dfcdaf020a2cc09a9e477ecb830d278bb7b/stable/sonatype-nexus/templates/deployment.yaml).

**What you expected to happen**:

I expected to look into `values.yaml`, uncomment `limits` or `requests` and see `cpu` and `memory` values assigned to the pod.

**Anything else we need to know**:

@rjkernick would you like to submit a PR for that?

**Comment by rjkernick** [comment]
I can definitely look into that and put a pull request in.

Rob
