### ISSUE TITLE
Facing issue while deploying Redis chart

### ISSUE THREAD

**Issue by spurti-chopra** [helm/charts#2755]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): No

**Version of Helm and Kubernetes**:
We are facing issue while deploying Redis chart on an all-in-one setup of Kubernetes cluster using helm
RAM: 7GB
Disk: 50 GB
**Kubernetes installed via source using “hack/local-up-cluster.sh”**
**Client Version:** version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a",  BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
**Server Version**: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", BuildDate:"2017-11-14T09:59:57Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Helm:
**helm version**
**Client:** &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4"}
**Server:** &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4"}

**Which chart**: stable/redis

**What happened**:
While deploying the chart pods are not getting created, looking at the logs of replica set associated with Redis, found out the following error
**_Error creating: pods "" is forbidden: pod.Spec.SecurityContext.RunAsUser is forbidden_**
Based on the above error, we suspect the issue to be related to below section in “redis/templates/deployment.yaml”
**spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001**
                                
**What you expected to happen**:
Pods should be created and should be in running state

**How to reproduce it** (as minimally and precisely as possible):
helm install redis

**Anything else we need to know**:

Alternatives Tried out:
a) **Creating a new pod security policy**

NOTE: For the kuberenetes cluster pod security policies enabled.
**kubectl get psp**
No resources found.

Used the following PSP definition
**_apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restrict-root
spec:
  privileged: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny_**
 
This did not help in resolving the issue and pods were still not created
  
b) **Setup the kubernetes cluster again by disabling security_admission in “hack/local-up-cluster.sh”**

Updated below line to remove $(securtity_admission) ADMISSION_CONTROL=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount${security_admission},DefaultStorageClass,DefaultTolerationSeconds,ResourceQuota

After this pods are getting created but finally landing into CrashLoopBackOff due to following failure
**_Readiness probe failed: Could not connect to Redis at 127.0.0.1:6379: Connection refused_**

Please let us know what is the best way to handle "securitycontext" in the Redis chart

**Comment by Mtax** [comment]
I got same problem
