### ISSUE TITLE
[stable/rabbitmq] Support config file or extra environment variables

### ISSUE THREAD

**Issue by thomas-riccardi** [helm/charts#2784]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  FEATURE REQUEST

**Version of Helm and Kubernetes**:
- helm `v2.7.2`
- kubernetes `v1.8.3`

**Which chart**:
`stable/rabbitmq`

**What happened**:
Could not configure all rabbitmq parameters. Only a subset of parameters are exposed in `values.yaml`, limited to what the docker image documents as environment variables (https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables).

**What you expected to happen**:
I expected to be able to configure any rabbitmq parameter (https://www.rabbitmq.com/configure.html#config-items).

**Anything else we need to know**:
It could be done by allowing an extra `rabbitmq.conf` file (https://github.com/bitnami/bitnami-docker-rabbitmq#configuration-file), or by exposing the `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` env var (see in https://www.rabbitmq.com/configure.html#define-environment-variables and https://hub.docker.com/_/rabbitmq/).

**Comment by alseddnm** [comment]
Is it possible to configure SSL for rabbitmq helm chart, and if so what is/are the config parameters?
I deployed a service which talk to  rabbitmq , am getting this error **Error injecting constructor, javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection**
Look like am sending my message over SSL and rabbitmq does not has it enabled ( the helm chart does not have any config parameter such as **RABBITMQ_SSL_CERTFILE**)

**Comment by thomas-riccardi** [comment]
@alseddnm I don't have a solution for your scenario; this seems to be another use-case for supporting extra config files indeed.
