### ISSUE TITLE
Need a golden chart to begin testing

### ISSUE THREAD

**Issue by viglesiasce** [helm/charts#28]
In order to properly implement the CI process we will need at least 1 "golden" chart to use as a guinea pig.

**Comment by prydonius** [comment]
:+1: We have a MariaDB chart https://github.com/bitnami/charts/tree/helm-2.0/mariadb in good shape that we can use as a guinea pig. @sameersbn do you think you'd be able to submit a PR for that?

**Comment by sameersbn** [comment]
Submitted via PR #29

**Comment by chrislovecnm** [comment]
Should we start with something simple ... MariaDB is awesome, but not quite as simple.  Like a Hello world golang app?  Just throwing ideas out there.

**Comment by viglesiasce** [comment]
The charts here should not be examples. They should be either full useful applications or components of such (like databases).

**Comment by chrislovecnm** [comment]
I understand ... Nginx? Simple ... I don't know ;)
