### ISSUE TITLE
Traefik: Add support for ACME DNS challenge

### ISSUE THREAD

**Issue by krancour** [helm/charts#281]
This feature was recently added to Traefik: https://github.com/containous/traefik/pull/738

I believe the chart should offer this as an opt-in. It's useful for anyone who wants to use Let's Encrypt to obtain certs for intranet applications, but more importantly (from my own perspective, at least), this might offer a slick method for avoiding the chicken and egg problem mentioned in #266

**Comment by lachie83** [comment]
Assigning to @krancour as requested.

**Comment by krancour** [comment]
Ref #1299

**Comment by kachkaev** [comment]
@krancour do you think this can be closed given that #1299 is merged now?

**Comment by krancour** [comment]
Yes.
