### ISSUE TITLE
[stable/sentry]

### ISSUE THREAD

**Issue by whs** [helm/charts#2827]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**: Helm 2.7.0, Kubernetes 1.7.8

**Which chart**: stable/sentry

**What happened**:

The Sentry chart has its disk mounted only to the Sentry web pod, and not workers. This will cause source maps resolving to fail (unless the source maps can be fetched from URL) as this is done on the worker

**What you expected to happen**:

The Sentry PD should be mounted on both web (for uploading) and worker (for processing).

This could be hard, as many PD doesn't support multi mounting. One possible solution is to use the S3 backend with minio.

**How to reproduce it** (as minimally and precisely as possible):

Upload a JavaScript source map to Sentry, remove publicly-accessible source map from your site, make your app crash and observe that Sentry/Internal will log an error.

**Anything else we need to know**:

**Comment by jmealo** [comment]
Any news on this? Not having source maps would greatly reduce the usefulness of Sentry.

**Comment by couds** [comment]
any news about this?
