### ISSUE TITLE
[incubator/istio] install instructions not working

### ISSUE THREAD

**Issue by Morriz** [helm/charts#2842]
After following instructions which are incomplete I managed to figure out how to launch istio with helm. I first set `istio.install: true` and then had to run this command twice: 
```
helm upgrade --install --version 0.2.8-chart2 incubator/istio values.yaml
``` 
which made it work (but then the 0.2.8 images were not found in the repo, I will create a seperate issue for that).

Now, I remember reading somewhere in some comment that the helm chart maintainer could not figure out how to install the CRD's with everything else in one go, and the `values.yaml` resembles that effort, but I notice other charts do it correctly by running a job to load them first, before the rest of the installer finishes. Take a look at [coreos/prometheus-operator](https://github.com/coreos/prometheus-operator).

**Comment by mumoshu** [comment]
Perhaps we could make all the k8s resources currently created by setting `istio.install: true` to be [helm's `post-install` hooks](https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md), to make istio installation one-shot?

**Comment by mumoshu** [comment]
I'm not an expert in this area but it seems like prometheus-operator is utilizing post-install hooks to create prometheus monitors from CRDs - and it seems to happen in one `helm install` command.

Ref: https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus-operator/templates/create-servicemonitor-job.yaml#L5-L6

**Comment by mumoshu** [comment]
> I first set `istio.install: true` and then had to run this command twice:

@Morriz Anyway, as far as I see from README, you need to run `helm install` with `--set istio.install=true` for the second step, in case it was your point.

FYI regarding installing istio in oneshot with helm, there seems to be an existing issue #2486 for that.

**Comment by Morriz** [comment]
The install=true does make a difference when set on both runs, the first time it notices it is not installed and only installs the crds. Again, not well designed nor documented. That flag can be removed from the chart.

And where in the readme did you find those instructions anyway? I don’t see them anymore. Time to straighten out this chart ;)

**Comment by mumoshu** [comment]
@Morriz I'm afraid I'm missing something but those instructions are in https://github.com/kubernetes/charts/tree/master/incubator/istio#installing-the-chart !

**Comment by mumoshu** [comment]
> The install=true does make a difference when set on both runs, the first time it notices it is not installed and only installs the crds.

Wow, surprised to know that! I have never tried doing that. Thanks for clarifying.

**Comment by Morriz** [comment]
Oh my, I am getting old, and blind :]
