### ISSUE TITLE
incubator/docker-registry release name is backwards

### ISSUE THREAD

**Issue by raykrueger** [helm/charts#2861]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes 1.8.0 (minikube)
Helm 2.7.0
Tiller 2.7.0

**Which chart**:
incubator/docker-registry

**What happened**:
The naming is backwards
docker-registry-exciting-greyhound

**What you expected to happen**:
exciting-greyhound-docker-registry

**How to reproduce it** (as minimally and precisely as possible):
git clone https://github.com/kubernetes/charts.git
cd charts/incubator/docker-registry
helm install .

**Anything else we need to know**:
I'll try to open a PR to fix this myself soon.

**Comment by rendhalver** [comment]
This has been resolved so you can close this @raykrueger.
Docker-registry has also been moved to stable.

**Comment by raykrueger** [comment]
Thanks, I never did get around to looking at it myself :(
