### ISSUE TITLE
[incubator/kafka] expose JMX_PORT

### ISSUE THREAD

**Issue by m-sp** [helm/charts#2894]
**FEATURE REQUEST**

kafka exposes a lot of metrics via jmx. I would be great to have a values switch to enable exposing jmx on a port

**Comment by AmundsenJunior** [comment]
This is available in values.yaml as option to expose the given port and assign to the KAFKA_JMX_PORT env var. Issue should be closed, then?

**Comment by m-sp** [comment]
Yes thanks, it seems this was done with https://github.com/kubernetes/charts/pull/4072
