### ISSUE TITLE
[BUG] lint.sh breaks on charts with dependencies

### ISSUE THREAD

**Issue by jdolitsky** [helm/charts#2896]
Please see this CircleCI run: https://circleci.com/gh/kubernetes/charts/1156

The chart (chartmuseum) has a dependency on the common chart, and lint no likey:
```
Runing helm lint on the chart at incubator/chartmuseum
==> Linting incubator/chartmuseum
[ERROR] templates/: render error in "chartmuseum/templates/service.yaml": template: chartmuseum/templates/service.yaml:4:11: executing "chartmuseum/templates/service.yaml" at <include "common.full...>: error calling include: template: no template "common.fullname" associated with template "gotpl"

Error: 1 chart(s) linted, 1 chart(s) failed
```

I fixed this problem a while ago, but it appears that the CI scripts run have changed since?
https://github.com/kubernetes/charts/pull/2313

**Comment by jdolitsky** [comment]
Discovered on PR #2746

**Comment by unguiculus** [comment]
The problem was fixed in `changed.sh`. Linting was moved to CircleCI. That's different scripts.

`lint.sh` needs to run `helm dep build`.

cc @mattfarina

**Comment by mattfarina** [comment]
Merged.

Note, this will also catch when a requirementes.lock file is out of sync with a requirements.yaml file, too.

**Comment by mattfarina** [comment]
Re-opening as the merged fix had a bug. Helm needs to be setup for both stable and incubator repos
