### ISSUE TITLE
incubator/docker-registry chart version 0.2.3 not exposing port 5000

### ISSUE THREAD

**Issue by ghost** [helm/charts#2898]
**Version of Helm and Kubernetes**:
demouser@loadbalancer:~$ helm version
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}

demouser@loadbalancer:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
**Which chart**:

**What happened**:
The chart installed and the pod is running but no open port 5000.

**What you expected to happen**:
I installed the registry chart and am expecting to see port localhost:5000 open on k8 master and my 2 nodes. 

**How to reproduce it** (as minimally and precisely as possible):
helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
helm install --name registry incubator/docker-registry

**Anything else we need to know**:
Here is the pod describe log for the registry pod. 
```
demouser@loadbalancer:~$ kubectl describe pod funny-pug-docker-registry-108772187-19kx0
Name:		funny-pug-docker-registry-108772187-19kx0
Namespace:	default
Node:		loadbalancer/192.168.2.117
Start Time:	Thu, 30 Nov 2017 09:26:04 -0800
Labels:		app=docker-registry
		pod-template-hash=108772187
		release=funny-pug
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"funny-pug-docker-registry-108772187","uid":"8b3ef1a0-d5f3-11e7-9...
Status:		Running
IP:		10.32.0.4
Created By:	ReplicaSet/funny-pug-docker-registry-108772187
Controlled By:	ReplicaSet/funny-pug-docker-registry-108772187
Containers:
  docker-registry:
    Container ID:	docker://5c9265e1b3c7d409aa129c81ce72a14c25d352e16e0c3961ac1d59bdf051482e
    Image:		registry:2.6.2
    Image ID:		docker-pullable://registry@sha256:d837de65fd9bdb81d74055f1dc9cc9154ad5d8d5328f42f57f273000c402c76d
    Port:		5000/TCP
    State:		Running
      Started:		Thu, 30 Nov 2017 09:26:05 -0800
    Ready:		True
    Restart Count:	0
    Liveness:		http-get http://:5000/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:		http-get http://:5000/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:	<none>
    Mounts:
      /var/lib/registry/ from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tntvf (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  data:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
  default-token-tntvf:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-tntvf
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath				Type		Reason			Message
  ---------	--------	-----	----			-------------				--------	------			-------
  8m		8m		1	default-scheduler						Normal		Scheduled		Successfully assigned funny-pug-docker-registry-108772187-19kx0 to loadbalancer
  8m		8m		1	kubelet, loadbalancer						Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "data" 
  8m		8m		1	kubelet, loadbalancer						Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-tntvf" 
  8m		8m		1	kubelet, loadbalancer	spec.containers{docker-registry}	Normal		Pulled			Container image "registry:2.6.2" already present on machine
  8m		8m		1	kubelet, loadbalancer	spec.containers{docker-registry}	Normal		Created			Created container
  8m		8m		1	kubelet, loadbalancer	spec.containers{docker-registry}	Normal		Started			Started container
```

**Comment by jascott1** [comment]
This is broken for me even after changing type to NodePort and restoring the previous port of 30400. As a workaround you can install the previous version with
`helm install incubator/docker-registry --version 0.2.2` which will produce a registry accessible from all nodes in the cluster.

@jpds Any reason this breaking change was necessary?

**Comment by rwenz3l** [comment]
The docker-registry has been moved to stable so this issue is kinda closed now - the initial problem is not resolved though. Even with port-forwarding via kubectl I'm unable to push images into the private registry here. Please see the referenced bug (#2991) for further attempts to resolve this.
