### ISSUE TITLE
Unable to start Elasticsearch

### ISSUE THREAD

**Issue by mikesplain** [helm/charts#290]
When I start up a fresh ES cluster from incubator/elasticsearch v0.1.2 the nodes never pass their healthcheck and loop through ChrashLoopBackOff.  Tested on both minikube and a real k8s cluster in AWS.  Logs show little detail and K8s events show 503 response for liveliness and readiness probes.  PVC's are properly mounted into containers, however the rest of the PetSets never come up.

Also tested on a fresh GCE cluster with no luck.

I was able to get the following error from the master:

https://gist.github.com/mikesplain/dc245ba62fc025255c90f0893c4a4361

I'm going to try to debug further. If anyone has seen this before please let me

**Comment by mikesplain** [comment]
I was able to get it starting up if I adjust a few things. If I increase the `initialDelaySeconds` to a higher value it successfully starts up.  It appears to me, it's impossible to run this without change in minikube (for example, increase memory/cpu).  Is there a standard for what the expectations of state of the initial values are (e.g. prod config vs test config)?  

The memory and CPU constraints of running 2 masters, 3 data nodes and 2 clients is too much for something like minikube but obviously very realistic for a prod setup.  I'll look into it more tomorrow but what's the expectation for official helm charts in regards to testability with their default values?

**Comment by viglesiasce** [comment]
@mikesplain the official charts (esp stable) should be installable in Minikube when possible  but some applications are simply too hungry to fit inside the default values. In this case i think increasing initialDelaySeconds is innocuous enough of a change that it could work as a fix. What value did you set it to?

**Comment by saidimu** [comment]
@viglesiasce I had a similar issue to @mikesplain but with mixed results after messing with the probes.

Setting `initialDelaySeconds` to `60` and `timeoutSeconds` to `10` for both `livenessProbe` and `readinessProbe` somewhat  helped but ultimately I had to wait it out and repeatedly manually delete the `master` and `client` pods and let their respective replicasets create new ones until successful start.

Far from ideal but it's unclear what the magic probe numbers are.

**Comment by seanknox** [comment]
Hi @mikesplain @saidimu is this still an issue with an out of the box install?

**Comment by saidimu** [comment]
@seanknox @mikesplain healthcheck now works out of the box, it takes a few tries but works reasonably well. I tested on both bare-metal and clusters.

**Comment by killfill** [comment]
May this be somehow related to https://github.com/fabric8io/elasticsearch-cloud-kubernetes/issues/90 ?
