### ISSUE TITLE
[incubator/cassandra] PersistentVolumeClaim is not bound...

### ISSUE THREAD

**Issue by costa** [helm/charts#2941]
**Is this a request for help?**:
Sure
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
This a BUG REPORT

**Version of Helm and Kubernetes**:
All latest as of today.

**Which chart**:
incubator/cassandra

**What happened**:
I've just started a fresh cluster on GKE, followed [the helm tutorial](https://docs.bitnami.com/kubernetes/get-started-kubernetes/#k8_tutorial_step1) (installed and tested 
the redis chart successfully), but
`$ helm install --namespace "cassandra" -n "cassandra" incubator/cassandra`
yielded `PersistentVolumeClaim is not bound: "data-cassandra-cassandra-0" (repeated 3 times)` in the Kubernetes Dashboard.

**What you expected to happen**:
All the same, but with Cassandra up and working.

**How to reproduce it** (as minimally and precisely as possible):
Just do what I did.

**Anything else we need to know**:
I really hope this resolves soon.

**Comment by znorris** [comment]
When you request a PersistentVolumeClaim (PVC) from google it takes a while for the platform to create that physical resource. The pod is attempting to bind a resource that does not exist yet. If it stopped at "repeated 3 times" and did not continue to increase, that likely means the volume is bound. To verify this run `kubectl get pvc/data-cassandra-cassandra-0` and look at the "STATUS" column.

**Comment by costa** [comment]
@znorris Thanks for your response.

I've done the [data persistence config](https://github.com/kubernetes/charts/tree/master/incubator/cassandra#persist-data) and got it working.

No, **3** is probably the default number of retries, since after doing config above, it complained about CPU and memory — 3 times as well — and I don't think it settled for less CPU & memory or anything, and then after I upgraded the node pool, all seemed working.

This issue can be closed as soon as README is fixed per above

p.s. The config table in README needs some love too.
