### ISSUE TITLE
[stable/redis] inclusion of ingress

### ISSUE THREAD

**Issue by AlecTroemel** [helm/charts#2949]
**FEATURE REQUEST**:

**Version of Helm and Kubernetes**:  
Helm 2.7.2 
Kubernetes 1.8

**Which chart**:
stable/redis

**description**:
It would be useful to include an optional ingress in the redis helm chart. This would allow a slick way to expose the redis cluster outside the kuberentes cluster

**Comment by bencoughlan** [comment]
👍  I could really use this in the redis-ha side too.

**Comment by plantfansam** [comment]
I'm interested in this functionality as well!

**Comment by govindkailas** [comment]
I would love to have ingress support added to redis.
/reopen
/remove-lifecycle rotten
