### ISSUE TITLE
[stable/openvpn] add support for existing claim

### ISSUE THREAD

**Issue by acartapanis** [helm/charts#2951]
**FEATURE REQUEST?**:

**Version of Helm and Kubernetes**:
Helm 2.7.2
Kubernetes 1.8.3

**Which chart**:
stable/openvpn

**Description**:
It would be great if the persistent volume can use an existing claim if available.

**Comment by neumachen** [comment]
This should be closed, right?

**Comment by acartapanis** [comment]
Ok to me, closing it.

**Comment by neumachen** [comment]
So, should I make a PR against here?

**Comment by acartapanis** [comment]
Why do you want to make an other PR ? Is there a bug with this one ?
