### ISSUE TITLE
sentry del --purge does not delete the created jobs

### ISSUE THREAD

**Issue by marekaf** [helm/charts#2972]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT
**Version of Helm and Kubernetes**:
```
# helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
# kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4-gke.0", GitCommit:"04502ae78d522a3d410de3710e1550cfb16dad4a", GitTreeState:"clean", BuildDate:"2017-11-27T19:19:56Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
sentry

**What happened**:
`helm  del --purge` does not delete created jobs, so I need to run manually `kubectl delete jobs --all` to cleanup

**What you expected to happen**:
I expect `helm del --purge` to delete the jobs

**How to reproduce it** (as minimally and precisely as possible):
```
helm install --name sentry --wait stable/sentry
helm del --purge sentry
helm install --name sentry --wait stable/sentry
```

**Comment by edmondo1984** [comment]
@marekaf is there a workaround for this?

**Comment by marekaf** [comment]
> @marekaf is there a workaround for this?

not sure if this is still a problem, this issue is old more than a year now:)

**Comment by edmondo1984** [comment]
We are trying to install sentry through hell and because of this it is not
a repeatable process, it’s annoying

Il giorno ven 18 gen 2019 alle 22:43 Marek Bartík <notifications@github.com>
ha scritto:

**Comment by edmondo1984** [comment]
There is a very simple solution as documented here: https://github.com/helm/helm/blob/49fc49ecb82a8cd9cbb9d8ba7ce85db2fc355893/docs/charts_hooks.md#hook-resources-are-not-managed-with-corresponding-releases

One can simple annotate the jobs  with

`"helm.sh/hook-delete-policy": "before-hook-creation"`

what is unclear though it's whether it is a good idea as described in the chapter here: "Automatically delete hook from previous release"
