### ISSUE TITLE
default ssl certificate is not use in the nginx-ingress  helm chart

### ISSUE THREAD

**Issue by phoppe93** [helm/charts#2974]
Hello,

in values.yaml file is the variable   

// Optionally specify the secret name for default SSL certificate
 //  Must be <namespace>/<secret_name>
  
  defaultSSLCertificate: ""

but in the templates there as no define for this variable and its never use.

is it so correctly ????

**Comment by unguiculus** [comment]
Can be configured via `extraArgs`. See https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/values.yaml#L61-L65
