### ISSUE TITLE
How to get events into data dog in kubernetes ( was not working ) 

### ISSUE THREAD

**Issue by chris530** [helm/charts#2993]
I installed the datadog agent using the following command 

helm install --namespace kube-system --name datadog --set datadog.apiKey=<removed>  --set kubeStateMetrics.enabled=true  stable/datadog

But no events were coming in.

Running the following commands,  I was able to get events coming in.

helm fetch stable/datadog

tar -xvzf datadog-0.8.0.tgz

open values.yaml

To grab deployments

deployment:
  enabled: true
  replicas: 1

To grab events

collectEvents: True

Save values.yaml

Upgrade helm deployment

helm upgrade datadog .

Now events are coming in

**Comment by xvello** [comment]
Hello @chris530 ,

We added a [leader election mechanism](https://github.com/kubernetes/charts/tree/master/stable/datadog#leader-election) in 5.17 that should address your use case while only deploying a single daemonset.

Could you please confirm this issue can be closed?


Regards
