### ISSUE TITLE
Remove required review

### ISSUE THREAD

**Issue by mattfarina** [helm/charts#2994]
PR's currently have a message that says "At least one approved review is required by reviewers with write access." To start using OWNERS files we'll need to turn this off. The reason is that we won't be using the reviews system on GitHub as a requirement. Instead, we'll be using comments on issues and prow will handle the reviews.

/cc @kubernetes/charts-maintainers

**Comment by prydonius** [comment]
@mattfarina I mistakenly enabled that in addition to making sure status checks were required. Updated it now so that only status checks (CI) are required.
