### ISSUE TITLE
List of established examples / charts in order of priority to pull here

### ISSUE THREAD

**Issue by paralin** [helm/charts#30]
I thought I'd make a list here we can keep up to date of stuff to pull to this repository.
- [x] MariaDB: by @sameersbn / http://bitnami.com, repo: #29
- [ ] Cassandra petsets: by @chrislovecnm, repo: ?
- [ ] Rethinkdb petset: by @paralin, repo: https://github.com/paralin/kubernetes-rethinkdb-cluster
- [ ] Crunchy Postgres: by @jmccormick2001, repo: #22 

Feel free to add, or kill this issue if you think it's a bad idea to keep track of this here.

**Comment by chrislovecnm** [comment]
@erictune I think this is a good way to start this organizing, ounce we have the acceptance process down.  Thoughts?

**Comment by prydonius** [comment]
I think this is a great idea! One thing to note R.E. some of the ones @paralin mentioned, is that Charts in this repository shouldn't be using any alpha Kubernetes features, so PetSets, for example, should not be used. I've outlined some of the early acceptance criteria we've drawn up here: https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements

**Comment by paralin** [comment]
Can we make a alpha branch that includes petsets. Some of us are using them pretty heavily now in practice.

**Comment by prydonius** [comment]
We've talked about having a separate `charts-contrib` repository to host Charts that are using alpha features or are examples/scaffolds. Then as Charts mature in that repository, there could be a path for them to be added to the official repository.

**Comment by viglesiasce** [comment]
@paralin we now have the incubator folder for all charts that use alpha features.

**Comment by paralin** [comment]
Sounds good to me, can move in the petset stuff probably

**Comment by prydonius** [comment]
Now that we've got a structure in place, I think we can close this issue. @paralin and @chrislovecnm it would be great to see PRs for RethinkDB and Cassandra!

Feel free to re-open if anyone disagrees.
