### ISSUE TITLE
[prometheus] use other endpoints for readiness/liveness

### ISSUE THREAD

**Issue by YouriT** [helm/charts#3000]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: v2.7.0 / v1.7.8-gke.0

**Which chart**: Prometheus

**What happened**: the readinessProbe is set on the `/status` endpoint

**What you expected to happen**: the readinessProbe to be set on `/-/ready` endpoint

**How to reproduce it** (as minimally and precisely as possible): -

**Anything else we need to know**: There is also another endpoint: `/-/healthy` that might be useful.

See [prometheus/prometheus#2831](https://github.com/prometheus/prometheus/issues/2831) for details.

**Comment by thuandt** [comment]
I created PR using `livenessProbe` with `/-/healthy` and `readinessProbe` with `/-/ready` follow https://github.com/coreos/prometheus-operator/pull/675/files
