### ISSUE TITLE
string compare of version number may lead to unexpected behavior

### ISSUE THREAD

**Issue by chenzhiwei** [helm/charts#3002]
When I build Kubernetes, I added a suffix to the version string such as `v1.8.3-xxx` which leads the versionInfo Minor is `8+`. (I already `export KUBE_GIT_MINOR=8` before compiling Kubernetes, but the Minor version is still `8+`)

I checked some of the charts, they are using string compare of the versionInfo, like following:

```
{{- if and (eq .Capabilities.KubeVersion.Major "1") (gt .Capabilities.KubeVersion.Minor "7") }}
```

But when Kubernetes version is upgraded to `v1.10.1`, so the string compare may lead to unexpected behavior.

Is there a way to handle such case?

**Comment by mattfarina** [comment]
@chenzhiwei A couple things...

1. You might want to ask this question on [helm](https://github.com/kubernetes/helm) as this is a feature of helm. You may get more to your answer there.
2. Have you tried using a version like `v1.8.3+xxx` instead? In semantic versioning the `-` is the separator for a prerelease while the `+` is the separator to distinguish the same version but a different build (consider the `+` the separator for build metadata). Note, I've not tested this myself so I'd be curious if you do and have feedback.

Why would `v1.10.1` cause an unexpected behavior?

**Comment by chenzhiwei** [comment]
@mattfarina In string compare, `v1.10.1` is less than `v1.8.1`, but actually not.

**Comment by mattfarina** [comment]
We should start to use the semver functions instead of string comparison ones. See https://masterminds.github.io/sprig/semver.html

**Comment by mattfarina** [comment]
/cc @kubernetes/charts-maintainers 

An example of this problem at https://play.golang.org/p/u6mKXex4O7_y

**Comment by mattfarina** [comment]
We need to go through the charts and fix this prior to 1.10 and we'll need to document this.

**Comment by mattfarina** [comment]
Note, what we need for this is in Helm 2.8 but there is a pending bug to deal with prior to upgrading to that. This is still tracking.

**Comment by ReSearchITEng** [comment]
Just migrated to k8s 1.10 and this si critical. Many issues in all charts due to this compare, including nginx-ingress.

**Comment by unguiculus** [comment]
@ReSearchITEng Most charts should have been fixed including nginx-ingress. Can you name charts that still have this issue? Also, we'll be happy to accept PRs fixing this.

**Comment by ReSearchITEng** [comment]
I tested latest nginx-ingress (nginx-ingress-0.11.3) few hours back, and I
can confirm it was not ok.
More exactly, controller.service.externalTrafficPolicy=Local  is not
getting set on a k8s 1.10 cluster, while works perfectly on a 1.9.6.
Checking the helm chart, the issue comes from the comparison of versions.

**Comment by ReSearchITEng** [comment]
I confirm the newly fixed nginx-ingress 0.12.2 works fine.

**Comment by ReSearchITEng** [comment]
By searching for KubeVersion in all charts shows 14 charts affected by this issue.

**Comment by mattfarina** [comment]
@ReSearchITEng I didn't find 14 charts but I think I got them all. Did I miss any you are aware of?

**Comment by bridgetkromhout** [comment]
Today, Helm uses semver comparison: https://helm.sh/docs/topics/charts/#charts-and-versioning

If any questions remain, please open an issue in helm/helm: https://github.com/helm/helm/issues/new
