### ISSUE TITLE
Enable prow merging based on OWNERS files

### ISSUE THREAD

**Issue by mattfarina** [helm/charts#3006]
This issue is to track the status of enabling prow so that those in the OWNERS files who are collaborators on the repo can use prow commands to initiate a merge.

cc: @kubernetes/charts-maintainers

**Comment by 0xmichalis** [comment]
You will need to change [maintainers](https://github.com/kubernetes/charts/blob/bfd531cfa1ad85de2d29c8953201ad7000000d78/OWNERS#L1) to approvers in your OWNERS files I think.

cc: @cjwagner

**Comment by mattfarina** [comment]
@kargakis Created a PR for that in #3014

**Comment by scottrigby** [comment]
Just merged #3014. [prow](https://github.com/kubernetes/test-infra/blob/master/commands.md) looks excellent BTW!

**Comment by mattfarina** [comment]
@kubernetes/charts-maintainers We have a detail we need to work out.... do we want to require `/lgtm` and `/approve` or just `/approve`. Any thoughts?

**Comment by viglesiasce** [comment]
I think just `/approve`

**Comment by mattfarina** [comment]
@viglesiasce or just `/lgtm`? That's an option too.

**Comment by scottrigby** [comment]
I see that `/lgtm` adds the label, so that's a functional difference, but is there any semantic difference between the two?

**Comment by viglesiasce** [comment]
What is the standard if any for other projects? Is there a definition of what /lgtm means vs /approve?

**Comment by 0xmichalis** [comment]
Yeah, there is no such thing as just `/approve`. You either `/lgtm` and approval is implicit if you are listed as an approver, or you need to `/approve` explicitly.

**Comment by viglesiasce** [comment]
In that case i say just `/lgtm`

**Comment by 0xmichalis** [comment]
`/lgtm` is meant to be added by a code reviewer and `/approve` is meant to be added by a code owner as a high level approval for the change.

**Comment by scottrigby** [comment]
@kargakis does `/approve` add a `/lgtm` label? I ask because charts README currently specifies this as part of the review process.

**Comment by scottrigby** [comment]
Ah gotcha 👍  Can anyone run `/lgtm` command then?

**Comment by 0xmichalis** [comment]
@scottrigby `/approve` should add an `approved` label.

**Comment by 0xmichalis** [comment]
`/lgtm` with implicit approval should also add an `approved` label.

**Comment by 0xmichalis** [comment]
Anyone with access to the Kubernetes org can `/lgtm` and add the `lgtm` label but the `approved` label is added based on OWNERS files.

**Comment by scottrigby** [comment]
ok so we should also make sure to update that section of the README. Is there a standard k8s project workflow for these prow commands/labels written up somewhere?

**Comment by mattfarina** [comment]
See #3008 For an example of using the commands and adding the labels.

I get it enough to do the test-infra config now.

**Comment by 0xmichalis** [comment]
Plugin help is served by prow [here](http://prow.k8s.io/plugin-help.html). 

Plugin help specific to charts is [here](http://prow.k8s.io/plugin-help.html?repo=kubernetes%2Fcharts).

**Comment by scottrigby** [comment]
PS, I'm loving looking through these self-documenting [prow commands](https://github.com/kubernetes/test-infra/tree/master/prow/plugins) 💯

**Comment by cblecker** [comment]
This is great :)
