### ISSUE TITLE
nodeSelector for rabbitMQ

### ISSUE THREAD

**Issue by m1t1l** [helm/charts#3040]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
any

**Which chart**:
rabbitmq

**What happened**:
Add nodeSelector to stable\RabbitMQ, please.
Make it as resources, like this:
        resources:
{{ toYaml .Values.resources | indent 10 }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 9 }}

**What you expected to happen**:
Easy way to specify needed pools and nodes

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by mattfarina** [comment]
@m1t1l Thank you for the feature request. The charts maintainers have been cc'd (below). Pull requests are welcome to add features.

cc: @prydonius @tompizmor @sameersbn
