### ISSUE TITLE
[stable/redis] feature request to add imagePullSecrets to the chart

### ISSUE THREAD

**Issue by ghost** [helm/charts#3049]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm 2.7.2
K8S 1.8.5

**Which chart**:
stable/redis

**What you expected to happen**:
When I provide `.Values.imagePullSecrets` it should render into the deployments.

**Comment by mattfarina** [comment]
cc: @prydonius @tompizmor @sameersbn

**Comment by rhibiscusc** [comment]
I followed the following tip related to adding image pull secrets in helm chart in:

https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md#creating-image-pull-secrets

but I got the following error after doing exactly the same as described above:

Events:
  Type     Reason                 Age               From               Message
  ----     ------                 ----              ----               -------
  Normal   Scheduled              27s               default-scheduler  Successfully assigned iron-fish-test-app-67b9f8cf78-dvtp6 to minikube
  Normal   SuccessfulMountVolume  27s               kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-frngw"
  Normal   BackOff                25s               kubelet, minikube  Back-off pulling image "docker.xxxx.com/usr/app:0.4.0-SNAPSHOT"
  Warning  Failed                 25s               kubelet, minikube  Error: ImagePullBackOff
  Normal   Pulling                9s (x2 over 27s)  kubelet, minikube  pulling image "docker.xxxx.com/usr/app:0.4.0-SNAPSHOT"
  Warning  Failed                 9s (x2 over 26s)  kubelet, minikube  Failed to pull image "docker.xxxx.com/rong-chen/credential:0.4.0-SNAPSHOT": rpc error: code = Unknown desc = Error response from daemon: Get https://docker.xxxx.com/v2/usr/app/manifests/0.4.0-SNAPSHOT: unauthorized: BAD_CREDENTIAL
  Warning  Failed                 9s (x2 over 26s)  kubelet, minikube  Error: ErrImagePull

Have you tried the same tip successfully?

(I certainly can use the same registry, username and password with docker login to pull the image with docker cli)

Thanks for any earlier response.
