### ISSUE TITLE
Questions: Squash and Merge or a normal Merge

### ISSUE THREAD

**Issue by mattfarina** [helm/charts#3051]
/cc @kubernetes/charts-maintainers 

For some time the charts repo used squash and merge as the merge method. When we switched to Kubernetes automation for merging (commands like `/lgtm`) it went to a normal merge and we lost squash and merge. As it looks like we will soon have the choice again (with the automation) I wanted to ask the question....

**Do we go back to "squash and merge" or stay with "merge"**?

The pros/cons to "squash and merge":

* Pro: Shorter history where a chart change is a single commit
* Con: Loose the details about the change and the breakdown as it was built
* Con: Loose PGP signing if a committer uses that

The pros/cons to "merge":

* Pro: Retain PGP signing for people who care about that
* Pro: Have the detail about the change via multiple commits as it was being written
* Con: An individual change can be scattered through the commit history
* Con: Reverting the change may be more difficult (though github has tools to try and make that easier)

Any other thoughts?

Note, if the PR to add different merge types lands in test-infra it, as of this moment, will also restore "squash and merge" here.

**Comment by unguiculus** [comment]
I prefer squashing for a nice and linear history. I don't see losing details as a con. In fact, I think it is much better to have a PR in one commit instead of having lots of intermediate commits with funny messages that don't add any value. These commits usually are only there to fix things during the review process. And as you said, reverting is also easier with squashed PRs.

**Comment by viglesiasce** [comment]
I preferred squash in theory but in practice never really needed to look back at chart commit history.

**Comment by prydonius** [comment]
From the commit log, it looks like the automation is doing squash and merge. Going to close this out as it looks like this is what we want. Feel free to reopen if that's not the case @mattfarina.
