### ISSUE TITLE
etcd-operator helm chart doesn't work with etcd-operator 0.7.2

### ISSUE THREAD

**Issue by bryanlarsen** [helm/charts#3052]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
Helm 2.7.2, Kubernetes 1.8.0

**Which chart**:
stable/etcd-operator

**What happened**:
operator pod fails to start with error: `flag provided but not defined: -pv-provisioner` when trying to start 

**What you expected to happen**:
The pod to run

**How to reproduce it** (as minimally and precisely as possible):
helm install --version 0.5.2 --namespace kube-system --name etcd-operator stable/etcd-operator --set=rbac.install=true,cluster.version=3.2.11,image.tag=v0.7.2

**Anything else we need to know**:
Backup/restore options have changed significantly in 0.7; rather than a backup section in the cluster definition, it's an EtcdBackup resource.   I don't have the capability to test backup/restore, so I cannot create a PR.

**Comment by mattfarina** [comment]
cc: @chancez @lachie83

**Comment by raoofm** [comment]
cc: @alejandroEsc Latest version is 0.8.1. Are you actively maintaining it as you are listed on etcd-operator as a contributor.

@mattfarina @bryanlarsen Is it ok to update the title with the latest version.

**Comment by bryanlarsen** [comment]
Fine with me

**Comment by alejandroEsc** [comment]
Interesting. Thought this was looked at. Will look at this asap.
