### ISSUE TITLE
SolrCloud Helm Chart

### ISSUE THREAD

**Issue by AceHack** [helm/charts#3058]
This is a feature request for a SolrCloud Helm chart.

If an official one does not exist are there any out there in the wild that anyone is aware of?

Also It would be great if it was able to have easy elastic scaling.

Thanks.

**Comment by mattfarina** [comment]
@AceHack The charts that live here are contributed by people in the community. No one has contributed one, yet. If you would like to contribute one we'd be happy to take a look at it.

**Comment by AceHack** [comment]
I found this, starting to dig into it now.

https://github.com/guigo2k/helm-solr

**Comment by sylus** [comment]
This chart works but I noticed a few things that should be mentioned:

1) Don't name your chart solr, or will cause problems with launching solr itself as the XML will be invalid and list tcp://XXX.XXX.XXX.XXX:2181 as invalid

2) The ingress i think needs to be port 80 not 8983:

```sh
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: 80
```

Otherwise everything works nicely!

**Comment by sylus** [comment]
@AceHack can we re-open this issue?

**Comment by AceHack** [comment]
@sylus, I have no ability to do that

**Comment by thomasliddledba** [comment]
I believe only a member can do that, unfortunately.   As you can see I've tried once.

**Comment by thomasliddledba** [comment]
> This chart works but I noticed a few things that should be mentioned:
> 
> 1. Don't name your chart solr, or will cause problems with launching solr itself as the XML will be invalid and list tcp://XXX.XXX.XXX.XXX:2181 as invalid
> 2. The ingress i think needs to be port 80 not 8983:
> 
> ```shell
>         paths:
>           - path: {{ $ingressPath }}
>             backend:
>               serviceName: {{ $fullName }}
>               servicePort: 80
> ```
> 
> Otherwise everything works nicely!

@sylus - Point 2 makes sense and that I can fix.  However, I'm not sure I completely understand the first point?  Could you provide an example on this or some more detail?

**Comment by sylus** [comment]
@thomasliddledba sorry about that I meant if you run helm don't run with:

```sh
helm install --name solr -f values.yaml .
```

Since will override needed environment variables in the container as solrconfig.xml reads from `solr_*` envvars.

Also was thinking would be neat if can add the following:

```sh
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "solr.fullname" . }}
  labels:
    app: {{ template "solr.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  security.json: |
    {
      "authentication": {
        "class":"solr.BasicAuthPlugin",
        "credentials":{"solr":"IV0EHq1OnNrj6gvRCwvFwTrZ1+z1oBbnQdiVC3otuq0= Ndd7LKvVBAaZIF0QAVi1ekCfAJXr1GGfLtRUXhgrF8c="},
        "blockUnknown": true
      },
      "authorization": {
        "class":"solr.RuleBasedAuthorizationPlugin",
        "user-role": {"solr":"admin"},
        "permissions":[{"name":"all", "role":"admin"}]
      }
    }
```

```
          volumeMounts:
          - name: security.json
            mountPath: /opt/solr/server/solr
            subPath: solr
    ...
    volumes:
      - name: security
        configMap:
          name: {{ template "solr.fullname" . }}
```

I can submit a P.R. just testing it out first.

**Comment by thomasliddledba** [comment]
@sylus - ah.  That makes sense.  It could be handled two ways.  1 - I could rename the chart to something like `apache-solr`, however, I was attempting the keep the theme of the other apache projects (i.e `zookeeper`...etc) that are just named after the product.  2 - We could add a section in the README.md that states exactly what you found and discourage users against doing that.  Thoughts?

As for the `ConfigMap` I can add that as part of my original PR.  However, I would want to change it from a `ConfigMap` to a secret.  Thoughts?

**Comment by sylus** [comment]
Hey I noticed one thing with the chart and that is i lose my cores on restart of the node.

<img width="466" alt="screen shot 2018-11-13 at 3 00 49 pm" src="https://user-images.githubusercontent.com/984304/48439859-5b039d00-e755-11e8-8675-e98433e06ba1.png">

<img width="868" alt="screen shot 2018-11-13 at 3 03 43 pm" src="https://user-images.githubusercontent.com/984304/48439863-5dfe8d80-e755-11e8-93e6-b714c1d25e24.png">

How does the shars replica folder persist on restart?

**Comment by sylus** [comment]
@thomasliddledba

**Comment by sylus** [comment]
@AceHack wondering if u knew about issue above?

**Comment by AceHack** [comment]
@sylus I do not

**Comment by sylus** [comment]
Ah I got it working by setting the volume mount to /opt/solr/server/solr and then providing the solr.xml, zoo.cfg, etc as config maps, then the shard replica which is placed in Solr home state is kept in pvc. ^_^

**Comment by thomasliddledba** [comment]
@sylus - Sorry for the long delay.  How did you get this working?  Could you share the solution?  I can put it into the PR that I have open?
