### ISSUE TITLE
[helm/redis-cache] service not routed to master

### ISSUE THREAD

**Issue by Perfect-Web** [helm/charts#3062]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
latest

**Which chart**:
redis-cache

**What happened**:
in my app i use the dns endpoint, if the elected master goes down, the connection is routed to another instance that is slave

**What you expected to happen**:
the service should route to the new elected master

**How to reproduce it** (as minimally and precisely as possible):
deploy a 3 replicas, add some data, and kill the master

**Anything else we need to know**:

**Comment by mattfarina** [comment]
cc: @dhilipkumars

**Comment by dhilipkumars** [comment]
@Perfect-Web We should figure that out from the redis client.  I don't think there is a way to re-direct connections automatically to just one particular replica in a Statefulset.
