### ISSUE TITLE
Set imagePullPolicy in init-containers in charts

### ISSUE THREAD

**Issue by prydonius** [helm/charts#307]
In K8S 1.5, the default value for imagePullPolicy was removed, so charts that are skipping this setting are failing to be installed.

Since imagePullPolicy is a configurable value, we should be respecting it in init-containers as well.

Affected charts:
- [x] ghost #419
- [ ] jasperreports #518
- [x] joomla #488
- [x] magento #418
- [x] mediawiki #496
- [x] opencart #497 
- [x] owncloud #417
- [x] phabricator #426
- [ ] phpbb #519
- [x] prestashop #492 
- [ ] redmine #515
- [x] testlink #493 
- [ ] sapho #514

**Comment by sputnick** [comment]
I'll give this a shot

**Comment by viglesiasce** [comment]
Thanks @sputnick!!! Just a note that we'd appreciate if you can keep the PRs for each chart separate so that we can easily test and merge them.

**Comment by sputnick** [comment]
ok @viglesiasce I was just wondering about that. I have to get the CNCF stuff signed as well in-house. Might not be done today because of that.

**Comment by kingdonb** [comment]
https://github.com/kubernetes/charts/pull/295 (same issue) was closed because kubernetes/kubernetes#38542

**Comment by prydonius** [comment]
Looks like cockroachdb is the only one not updated for 1.5 yet cc @a-robinson

**Comment by prydonius** [comment]
also zookeeper @lachie83

**Comment by a-robinson** [comment]
Ack, thanks for the ping. Sent out #338

**Comment by viglesiasce** [comment]
looks like owncloud hit this #406

**Comment by prydonius** [comment]
Charts still affected by this through their dependency
- [ ] ghost
- [ ] jasperreports
- [ ] joomla
- [ ] magento
- [ ] mediawiki
- [ ] opencart
- [ ] owncloud
- [ ] phabricator
- [ ] phpbb
- [ ] prestashop
- [ ] redmine
- [ ] testlink
- [ ] sapho

**Comment by sebgoa** [comment]
confirm, `stable/joomla` fails in minikube (1.5.1)

**Comment by rosskukulinski** [comment]
stable/postgresql also effected
