### ISSUE TITLE
Unable to install sentry on minikube

### ISSUE THREAD

**Issue by marcuslindfeldt** [helm/charts#3071]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Running on OSX with minikube
```
$ helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T18:09:07Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

$ minikube version
minikube version: v0.24.1
```

**Which chart**: stable/sentry 0.1.6

**What happened**:
Postgres pod won't start. Logs give the following output.
```
Error from server (BadRequest): container "sentry-postgresql" in pod "sentry-postgresql-55574f87c9-9w4n2" is waiting to start: CreateContainerConfigError
```

**What you expected to happen**:
Sentry should install successfully

**How to reproduce it** (as minimally and precisely as possible):
Try to run the install command `helm install --name sentry --wait stable/sentry`

**Anything else we need to know**:

**Comment by mattfarina** [comment]
cc: @rothgar

**Comment by rothgar** [comment]
Do you have a default storage provider for the cluster? Minikube doesn't provide one by default.
Some info in the prerequisites https://github.com/kubernetes/charts/tree/master/stable/sentry#prerequisites
or you can disable persistence here https://github.com/kubernetes/charts/blob/master/stable/sentry/values.yaml#L69-L70 If your postgres pod is restarted all data will be lost.

You can try rook for persistent storage https://rook.github.io/docs/rook/master/helm-operator.html YMMV I couldn't get rook to install in minikube 1.7.0

**Comment by marcuslindfeldt** [comment]
@rothgar The `default-storageclass` and `storage-provisioner` minikube addons are enabled. 

```
$ minikube addons list
- kube-dns: enabled
- heapster: disabled
- registry-creds: disabled
- default-storageclass: enabled
- storage-provisioner: enabled
- coredns: disabled
- ingress: enabled
- registry: disabled
- addon-manager: enabled
- dashboard: enabled
- efk: disabled
```

Does that not enable a default storage provider? 
I tried to disable persistance but no luck unfortunately. Same error.

**Comment by rothgar** [comment]
Are you able to install the postgres chart on its own? Sentry is dependent on that.

```
helm install stable/postgresql
```

I can try to reproduce the problem but I may not have time until after the holiday break.

**Comment by marcuslindfeldt** [comment]
That doesn't work either. Found the following error from a `kubectl describe pod` command.
```
Error: lstat /tmp/hostpath-provisioner/pvc-6319bf22-e4f4-11e7-8995-08002754c7c7: no such file or directory
```

Some googling resulted in this open github issue https://github.com/kubernetes/minikube/issues/2256
