### ISSUE TITLE
Spinnaker is unable to view k8s resources

### ISSUE THREAD

**Issue by cvieri** [helm/charts#3072]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:

Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2+coreos.0", GitCommit:"4c0769e81ab01f47eec6f34d7f1bb80873ae5c2b", GitTreeState:"clean", BuildDate:"2017-10-25T16:24:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2+coreos.0", GitCommit:"4c0769e81ab01f47eec6f34d7f1bb80873ae5c2b", GitTreeState:"clean", BuildDate:"2017-10-25T16:24:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
Clouddriver ?

**What happened**:
Charts are deployed but I get:

No server groups match the filters you've selected. And cannot create any Server Group(no pop-up window).

**What you expected to happen**:
All k8s resources are visible in UI, can create Server Group.

**How to reproduce it** (as minimally and precisely as possible):
Deploy latest images from quay.io/spinnaker/

**Anything else we need to know**:
Everything works well with default chart images.

In logs I get:
java.io.FileNotFoundException: /root/.kube/config (No such file or directory)

**Comment by viglesiasce** [comment]
The latest images dont work due to a bug in service account handling. When 1.6.0 or 1.5.2 is released it will have the fix. I will update them then:

https://github.com/spinnaker/clouddriver/pull/2178

**Comment by taylorsmithgg** [comment]
@viglesiasce Any update on this?

**Comment by viglesiasce** [comment]
1.5.2 did not include the fix so we'll have to wait for 1.6.0

**Comment by el-sai** [comment]
@viglesiasce I think this issue can be closed since 1.6.0 is released and the above mentioned  issue doesnt happen anymore.
