### ISSUE TITLE
move testing from jenkins to prow

### ISSUE THREAD

**Issue by BenTheElder** [helm/charts#3080]
**Is this a request for help?**: Yes? (ish)

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

/kind bug

**Version of Helm and Kubernetes**: n/a

**Which chart**: n/a

**What happened**: The Google test-infra team's Jenkins is going away in favor of Prow which has less maintenance and runs / tests on Kubernetes natively https://github.com/kubernetes/test-infra/issues/3778, this repo is one of the last places Jenkins-based presubmits still run for.

**What you expected to happen**: These tests should be able to run in a kubernetes pod on prow which has better integration for e2e testing etc.

**How to reproduce it** (as minimally and precisely as possible): n/a

**Anything else we need to know**: I'm willing to help with this, but I'd rather not have to do everything (I at least would like help knowing what environment / binaries the presubmit depends on) and Jenkins is going away soon.

**Comment by BenTheElder** [comment]
Ideally both the presubmit and periodic/CI/postsubmit jobs should be moved, but the presubmit Jenkins will be going away before the CI Jenkins.

**Comment by mattfarina** [comment]
@BenTheElder Is there documentation on how to migrate this?

**Comment by BenTheElder** [comment]
@mattfarina I don't think there is any in particular, it's just adding a new prow job (which there are docs for) that runs the same tests in a new environment. For some of the other repos we definitely can't have a guide because someone along the way setup snowflake VMs just for those jobs...

If someone can tell me what the job needs at runtime I can work on creating jobs for it if nobody else does first. 
It doesn't take long to switch to a prow job but we need an image / pod that will provide the right tools etc and since Jenkins jobs typically weren't containerized I don't know what this repo uses.

**Comment by mattfarina** [comment]
@BenTheElder The entry point for Jenkins is https://github.com/kubernetes/charts/blob/master/test/e2e.sh. You'll notice it runs another one of the scripts from within a container.

If you beat us to it that would be great. Being that it's the holidays it might take us a few weeks to jump on this. Is that ok?

cc: @viglesiasce

**Comment by BenTheElder** [comment]
Thanks.

> If you beat us to it that would be great. Being that it's the holidays it might take us a few weeks to jump on this. Is that ok?

I'm not personally planning to turn off anything, but I know we'd like to get rid of Jenkins sooner rather than later just to reduce the number of things we maintain. Nearly everything runs on kubernetes now. I'll try to get back to this one soon myself.

**Comment by BenTheElder** [comment]
/close
There hasn't been any Jenkins for a long time, but charts does have Prow job(s) on kubernetes.
