### ISSUE TITLE
Liveness / readiness probe for charts/stable/openvpn

### ISSUE THREAD

**Issue by foklepoint** [helm/charts#3081]
**Is this a request for help?**:
Request
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Version of Helm and Kubernetes**:
Helm 2.7, Kubernetes 1.8.3

**Which chart**:
charts/stable/openvpn

**Describe *in detail* the feature/behavior/change you'd like to see**
I'd love to see a liveness / readiness probe added to the chart. With netcat installed in the docker image, we could exec this inside the container to check the the status of openvpn server on the pod.
```shell
echo -e "8\x01\x00\x00\x00\x00\x00\x00\x00" | nc -w10 -u 10.240.0.1 443
```

**Comment by mattfarina** [comment]
cc: @jfelten
