### ISSUE TITLE
WAF funcitonality in Nginx Ingress Controller

### ISSUE THREAD

**Issue by bramvdklinkenberg** [helm/charts#3087]
If this is a FEATURE REQUEST, please:

I would like to see the WAF functionality (https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/modsecurity.md) in the ingress controller installed via helm

**Version of Helm and Kubernetes**: 
Helm -> 2.6.2
Kubernetes -> 1.7.7 

**Which chart**: Nginx ingress controller

**Comment by mattfarina** [comment]
cc: @jackzampolin @mgoodness @chancez

**Comment by bramvdklinkenberg** [comment]
Any update on this?

**Comment by bramvdklinkenberg** [comment]
@jackzampolin @mgoodness @chancez do you know if this is something that will be picked up?
with kind regards,
Bram

**Comment by jackzampolin** [comment]
I personally don't have bandwidth to take this up right now.

**Comment by abdennour** [comment]
any update?
