### ISSUE TITLE
Please update prometheus chart to use prometheus operator

### ISSUE THREAD

**Issue by AceHack** [helm/charts#3096]
This is a feature request

https://github.com/coreos/prometheus-operator

**Comment by mattfarina** [comment]
cc: @mgoodness

**Comment by ant31** [comment]
I second this request and can help.
 cc @gianrubio

**Comment by gianrubio** [comment]
I'll do that during this week

**Comment by gianrubio** [comment]
linking this issue with my explanation on how I'll work on it https://github.com/kubernetes/charts/pull/3490#issuecomment-363899621
