### ISSUE TITLE
What is the release cycle of source to packaged helm charts?

### ISSUE THREAD

**Issue by AceHack** [helm/charts#3098]
I've noticed recent changes in git and sometimes complete charts are missing in the helm command line?  How do I know what version of source is in the helm chart?  Does source get tagged?  What's the release schedule?

**Comment by timothyclarke** [comment]
From having a pull request merged, it seems that there is an hour or so after the merge is done before the updated content is public. Try giving it a few hours and doing a `helm repo up`

**Comment by mattfarina** [comment]
@AceHack Continuous deployment is used to build and deploy the helm charts to object storage where it is then consumed. From commit landing to a build can take a little time.

Charts are now immutable. If you use a chart version and go back to the source you should be able to find the version in the `Chart.yaml`. The version there is what you're getting.

**Comment by unguiculus** [comment]
Closing as solved.
