### ISSUE TITLE
OWNERS files do not specify reviewers for every file.

### ISSUE THREAD

**Issue by cjwagner** [helm/charts#3106]
Prow's blunderbuss plugin has been enabled on this repo and attempts to automatically request reviews based on the `reviewers` section of OWNERS files.
Blunderbuss failed to automatically request reviews for PR #3105 because there were no OWNERS files specifying reviewers for any of the files. This appears to apply to most of the PRs in the repo.

Typically every file in the repo should have at least one reviewer specified in an OWNERS file somewhere above it in the directory hierarchy. If you want to avoid adding reviewer to the root OWNERS file you may want to define reviewers in OWNERS files in each of the directories under root.

**Comment by mattfarina** [comment]
@cjwagner if there is no one as an option to review can blunderbuss silently not take any action? We didn't want to have reviewers at the top level and it will be awhile before we have reviewers files for all the charts. A handful of the approvers in the owners files will look over the PRs in a given week.

**Comment by mattfarina** [comment]
@cjwagner we'd like to get reviewers if there is an option for them and otherwise skip adding reviewers. If this requires a change I'm happy to craft a PR.

**Comment by cjwagner** [comment]
We currently log an error when we can't find enough reviewers for a PR: 
https://github.com/kubernetes/test-infra/blob/c81a79dd0d6cff7f44c4f2cc60ace1d73813d435/prow/plugins/blunderbuss/blunderbuss.go#L92-L94
so this is causing some log spam.
Changing this logging call from an `Errorf` to a `Warnf` would let us filter out these warnings more easily which is probably sufficient for now. I don't want to get rid of the warning altogether because it is typically helpful to be warned when reviewer coverage is insufficient. I'll make a PR.
