### ISSUE TITLE
[incubator/elasticsearch] unsupported logging configuration file logging.yml

### ISSUE THREAD

**Issue by tmaier** [helm/charts#3110]
**Is this a request for help?**: No

---

**BUG REPORT**

**Version of Helm and Kubernetes**:

```text
$ helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T18:09:07Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

incubator/elasticsearch

**What happened**:

The helm chart provides a [custom logging configuration](https://github.com/kubernetes/charts/blob/master/incubator/elasticsearch/templates/configmap.yaml#L65-L80).

The pod shows in the very first line an error message.

```text
[2017-12-20T00:32:23,537][WARN ][o.e.c.l.LogConfigurator  ] ignoring unsupported logging configuration file [/usr/share/elasticsearch/config/logging.yml], logging is configured via [/usr/share/elasticsearch/config/log4j2.properties]
```

This means the log configuration does not work

**What you expected to happen**:

Log configuration is meaningful and loads.

**How to reproduce it** (as minimally and precisely as possible):

Just run `helm install incubator/elasticsearch` and see the log output of the client pod

**Anything else we need to know**:

I am using Elasticsearch 5.4

**Comment by mattfarina** [comment]
cc @simonswine @icereval

**Comment by icereval** [comment]
@tmaier, thanks for the detailed report!

PR #3257 should correct for this deficiency.
