### ISSUE TITLE
[incubator/kafka] Use RollingUpdate updateStrategy

### ISSUE THREAD

**Issue by ginkel** [helm/charts#3112]
**FEATURE REQUEST**

**Version of Helm and Kubernetes**:

* Helm v2.7.2
* Kubernetes v1.8.4-gke.1

**Which chart**: incubator/kafka v0.2.7

**What happened**:

When upgrading the incubator/kafka release, e.g., with changed resource constraints, those do not become effective until pods are manually deleted.

**What you expected to happen**:

Would it be an option to specify an `updateStrategy` of `RollingUpdate` instead so this happens in an automated fashion?

**Comment by mattfarina** [comment]
@ginkel pull requests are welcome for feature additions

cc @faraazkhan @h0tbird @benjigoldberg

**Comment by benjigoldberg** [comment]
@ginkel @mattfarina I can add this to the chart -- PR incoming

**Comment by ginkel** [comment]
Excellent, thanks! :-)
