### ISSUE TITLE
[stable/telegraf] telegraf-ds & telegraf-s charts missing

### ISSUE THREAD

**Issue by southwolf** [helm/charts#3113]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Which chart**:

telegraf-ds & telegraf-s

**What happened**:

telegraf chart says it was deprecated (by #823) , suggests using `telegraf-ds` and `telegraf-s`, these two charts were added in March (#742, #822) but never get merged.

**Comment by ThinkBriK** [comment]
Basically you should remove the deprecation warning as both PR are marked closed and were never merged !

**Comment by southwolf** [comment]
@jackzampolin Any plans on updating `telegraf-ds`  and `telegraf-s` ?

**Comment by jackzampolin** [comment]
@southwolf I'm working with @gunnaraasen to find a better place for these. I know there are working versions here: https://github.com/influxdata/tick-charts
