### ISSUE TITLE
[stable/datadog] Checking minor kubernets version breaks our deployment

### ISSUE THREAD

**Issue by jewilmeer** [helm/charts#3121]
**Is this a request for help?**:
Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

**Version of Helm and Kubernetes**:
1.8.3 GKE

**Which chart**:
datadog

**What happened**:

While applying the latest chart to our cluster we saw the following error:

```
chart parsing error: render error in "datadog/templates/clusterrolebinding.yaml": template: datadog/templates/_helpers.tpl:46:23: executing "rbac.apiVersion" at <.Capabilities.KubeVe...>: can't evaluate field Minor in type *version.Info
```

Which originated [here](https://github.com/kubernetes/charts/blob/5df19bb404e27fb3e6199afd6aa808749aeb3263/stable/datadog/templates/_helpers.tpl#L46)

**What you expected to happen**:

A successful deployment

**How to reproduce it** (as minimally and precisely as possible):

We use a small wrapper around helm, to deploy without tiller, so our resource files are generated before being applied to the cluster. That's probably what breaks our deployment right now.

If this version constraint can be templated / ignored our deployments would work again. 

**Anything else we need to know**:

We use https://github.com/blendle/kubecrt to deploy our resources.

**Comment by jewilmeer** [comment]
cc: @cw-sakamoto

**Comment by mattfarina** [comment]
@jewilmeer did you use `helm template` to generate the resource files? If so, what version of helm are you using.

**Comment by cw-sakamoto** [comment]
@jewilmeer Thanks for the report!

Since ```.Capabilities.KubeVersion``` method requires revision for each kube release, I will change it to specified apiversion in values.yaml.

FYI 
- https://github.com/kubernetes/charts/blob/master/stable/concourse/values.yaml#L595
- https://github.com/kubernetes/charts/blob/master/stable/concourse/templates/worker-rolebinding.yaml#L2

**Comment by jewilmeer** [comment]
@mattfarina No, `kubecrt` uses the helm api, but it's generated on the client before being applied to the server.

@cw-sakamoto That would be great. Tnx!
