### ISSUE TITLE
minio fails to create default bucket

### ISSUE THREAD

**Issue by stela** [helm/charts#3128]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm and tiller version 2.7.2. Kubernetes version 1.8.4.

**Which chart**:
minio

**What happened**:
The configured default bucket wasn't created. The software accessing it reports
`Error: com.amazonaws.services.s3.model.AmazonS3Exception The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 3L137; S3 Extended Request ID: 3L137)` and `mc ls myminio` fails to list any buckets. My chart which in turn depends on minio is called "storage", that's why the "storage-" prefixes below come from.

Even though the storage-minio-create-bucket pod is deleted after running, I was able to get logs from it while it was running using `while true; do kubectl logs -f storage-minio-create-bucket; done`, it outputs (some newlines added for readability):
```
Error from server (NotFound): pods "storage-minio-create-bucket" not found
...
Error from server (NotFound): pods "storage-minio-create-bucket" not found
Error from server (BadRequest): container "minio-mc" in pod "storage-minio-create-bucket" is waiting to start: ContainerCreating
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
Error from server (NotFound): pods "storage-minio-create-bucket" not found
...
```

Meanwhile tiller logged this:
```
[tiller] 2017/12/21 12:57:21 preparing install for storage
...
[tiller] 2017/12/21 12:57:22 performing install for storage
[tiller] 2017/12/21 12:57:22 executing 1 pre-install hooks for storage
[tiller] 2017/12/21 12:57:22 hooks complete for pre-install storage
...
[kube] 2017/12/21 12:57:23 creating 18 resource(s)
[kube] 2017/12/21 12:57:23 beginning wait for 18 resources with timeout of 5m0s
...
[kube] 2017/12/21 12:57:38 Pod is not ready: mynamespace/storage-memcached-0
[tiller] 2017/12/21 12:57:39 executing 1 post-install hooks for storage
[kube] 2017/12/21 12:57:39 building resources from manifest
[kube] 2017/12/21 12:57:40 creating 1 resource(s)
[kube] 2017/12/21 12:57:40 Watching for changes to Pod storage-minio-create-bucket with timeout of 5m0s
[kube] 2017/12/21 12:57:40 Add/Modify event for storage-minio-create-bucket: ADDED
[tiller] 2017/12/21 12:57:40 hooks complete for post-install storage
[tiller] 2017/12/21 12:57:40 deleting post-install hook storage-minio-create-bucket for release storage due to "hook-succeeded" policy
[kube] 2017/12/21 12:57:40 Starting delete for "storage-minio-create-bucket" Pod
[kube] 2017/12/21 12:57:40 Using reaper for deleting "storage-minio-create-bucket"
[storage] 2017/12/21 12:57:40 updating release "storage.v1"
...
[kube] 2017/12/21 12:57:41 Doing get for Secret: "storage-minio-user"
[kube] 2017/12/21 12:57:41 get relation pod of object: mynamespace/Secret/storage-minio-user
...
[kube] 2017/12/21 12:57:41 Doing get for PersistentVolume: "storage-minio"
[kube] 2017/12/21 12:57:41 get relation pod of object: /PersistentVolume/storage-minio
...
```

**What you expected to happen**:
When `speficying minio.defaultBucket.enabled=true` and `minio.defaultBucket.name=files`, the `files` bucket should be created.

**How to reproduce it** (as minimally and precisely as possible):
I created a chart which in turn requires the minio 0.4.2 chart. Its values.yaml contains:
```yaml
minio:
  mode: standalone
  accessKey: Secret...
  # On AWS, SecretAccessKey example has 41 chars
  secretKey: Secret...
  persistence:
    size: 256Mi
    storageClass: "storage-minio"
  serviceType: ClusterIP
  defaultBucket:
    enabled: true
    name: files
    policy: none
```

**Anything else we need to know**:
I suspect this might happen due to minio-create-bucket running too early before minio itself is fully started up and ready to create a bucket. Maybe https://github.com/kubernetes/helm/issues/3282 (helm post-ready hook feature proposal) or manually awaiting minio startup in the pod would help?

**Comment by stela** [comment]
Manually creating the minio-create-bucket pod, using a pod definition as output by `helm install --debug` afterwards results in the bucket being created.

**Comment by mattfarina** [comment]
cc: @nitisht

**Comment by nitisht** [comment]
thanks @mattfarina will take a look

**Comment by WarheadsSE** [comment]
We (GitLab) are modifying the stable chart (`v0.4.3`) slightly for our needs, but saw this as well. To address this, we've added a shell loop pending a successful connection to the Minio server pod [here](https://gitlab.com/charts/helm.gitlab.io/blob/master/charts/minio/templates/_helper_create_buckets.sh)

**Comment by nitisht** [comment]
Thanks for the idea @WarheadsSE I used the same approach. @stela I have sent a PR https://github.com/kubernetes/charts/pull/3470 , on local testing I see it fixes this issue
