### ISSUE TITLE
[stable/jenkins] config.xml isn't updated when persistence is enabled

### ISSUE THREAD

**Issue by switchboardOp** [helm/charts#3133]
**Is this a request for help?**: yes
---

BUG REPORT

**Version of Helm and Kubernetes**:
Helm Client & Server: v2.7.0
kubectl: v1.8.2
Kubernetes: v1.7.5+coreos.1

**Which chart**:
stable/jenkins

**What happened**:
When persistence is enabled and PVC is bound to an NFS share, `helm upgrade` will update the config map but not the config.xml that persists. Specifically I was trying to edit resource limits for the agent pods.

**What you expected to happen**:
Expect help upgrade to apply config changes to the persistent deployment.

**How to reproduce it** (as minimally and precisely as possible):
- create a PV and PVC for the deployment
- release a persistent Jenkins Deployment using stable/jenkins
- edit the Agent.Memory value and upgrade the release
- check value of container `<resourceRequestMemory>` in your config.xml

**Anything else we need to know**:
Before upgrading my release I did add some config through the Jenkins UI. Added added kube service account, added host volume mount to Kubernetes plugin config etc.

**Comment by mattfarina** [comment]
cc: @lachie83 @viglesiasce

**Comment by lsowen** [comment]
I've run into this same issue.  It is because `apply-config.sh` does not copy over the `config.xml` in `/var/jenkins_home`.  https://github.com/helm/charts/blob/89b323a6e5a35bad291050e9c41f936d21c3e641/stable/jenkins/templates/config.yaml#L195-L197

(The `-n` option to `cp` is `--no-clobber`).

**Comment by lsowen** [comment]
Similar issue was already addressed with the installed plugins: https://github.com/helm/charts/issues/970
