### ISSUE TITLE
[stable/concourse] Installation failed

### ISSUE THREAD

**Issue by cherwin** [helm/charts#3135]
BUG REPORT
```
$ helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/concourse 0.10.6

**What happened**:
The concourse installation failed with the following error message.
```
Error: release funny-toad failed: roles.rbac.authorization.k8s.io "funny-toad-worker" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["podsecuritypolicies"], ResourceNames:["privileged"], APIGroups:["extensions"], Verbs:["use"]}] user=&{system:serviceaccount:kube-system:default ff3d9529-e676-11e7-82c3-064f82fd8be0 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
```

**What you expected to happen**:
A successful installation

**How to reproduce it** (as minimally and precisely as possible):
```
helm install stable/concourse
```

**Anything else we need to know**:
Kubernetes is installed with kops 1.8.0 on AWS by a user associated with the following IAM permissions
```
AmazonEC2FullAccess
AmazonRoute53FullAccess
AmazonS3FullAccess
IAMFullAccess
AmazonVPCFullAccess
```

**Comment by mattfarina** [comment]
cc: @frodenas @viglesiasce @william-tran @nexeck

**Comment by mattfarina** [comment]
@cherwin It appears your Kubernetes cluster has RBAC setup for applications running in it. The RBAC access does not have the needed permissions. This is different from the permissions needed for Kuberentes to run in AWS. You can learn more about RBAC at https://kubernetes.io/docs/admin/authorization/rbac/

A kops user may be able to provide you with some more help as I'm not currently familiar with the way it configures a cluster.

**Comment by cherwin** [comment]
Thank you @mattfarina, I'll investigate further.

**Comment by cherwin** [comment]
I should have added `--authorization=RBAC` to `kops create`.
