### ISSUE TITLE
Redis persistence disabled (MISCONF Redis is configured to save RDB snapshot)

### ISSUE THREAD

**Issue by md-mq** [helm/charts#3143]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
maybe a bug

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```

**Which chart**:
`stable/redis`

**What happened**:
Although I have `persistence` disabled, I am facing an issue with redis trying to make snapshots:

```
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```

**What you expected to happen**:
I know that `redis-cli` could be used to disable the snapshots, but I was expecting that this behavior should the default when you opt for `no persistence`

**How to reproduce it** (as minimally and precisely as possible):
```
redis:
 ...
  persistence:
    enabled: false
  ...
```

After running deploying my helm chart, the app won't anymore because redis tries to make snapshots.

**Anything else we need to know**:

**Comment by mattfarina** [comment]
cc: @prydonius @tompizmor @sameersbn

**Comment by tetafro** [comment]
Comment in config file says: "Enable persistence using Persistent Volume Claims". So it's only about PVC (very misleading, I agree).

To disable RDB snapshots you can configure Redis using CLI flag, and pass them using `arg` value like this:
```
helm install \
    --set args={"--save ''"} \
    --set persistence.enabled=false \
    --name my-release stable/redis
```

**Comment by prydonius** [comment]
Thanks @tetafro. I agree that the name of that setting is a bit confusing in this case, but it's a common practice across different charts.

Given the flag makes Redis use an ephemeral volume anyway, I think it makes sense to actually configure Redis to not save snapshots when persistence is disabled. WDYT @sameersbn?

**Comment by md-mq** [comment]
@prydonius I think disabling snapshots when persistence is disabled could be a valid approach, I had to patch the redis chart to add a [ConfigMap](https://github.com/polyaxon/polyaxon-chart/blob/master/polyaxon/charts/redis/templates/cm.yaml) to do that.

Edit @tetafro's approach seems better than creating a config map, I am not sure why it did not work for me when I tried it. I will give it another try.

**Comment by coderroggie** [comment]
@tetafro @prydonius @mouradmourafiq I attempted to use the install command @tetafro  mentioned above to disable all persistence but i end up with the following as output for the config indicating that it is still saving things to disk for the RDB snapshots:

```
redis-master:6379> config get *
... 
167) "save"
168) "900 1 300 10 60 10000"
...
```

Seems to be related to https://github.com/antirez/redis/issues/2366 where the number of arguments is wrong for for the save command being passed as an argument.  https://stackoverflow.com/a/41238678/266426 also seems to suggest that this should be possible, but I could not get this option to work in various configurations and modifications to the helm chart.

I was finally able to get the following hacky way to work but was curious if you were able to get a better option to work.  If not, I can submit this as a PR but it really doesn't seem like the best option.

Excerpt from redis-master-statefulset.yaml and redis-slave-deployment.yaml files (both have the same in them):
```
      containers:
...
        {{- if not .Values.master.persistence.enabled }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "sleep 10; /opt/bitnami/redis/bin/redis-cli config set save ''"]
        {{- end }}
...
```
