### ISSUE TITLE
[stable/jenkins] In jnlp-slave pod docker daemon is not running

### ISSUE THREAD

**Issue by gaurav8297** [helm/charts#3145]
I am using jenkins chart .In that using an image of jnlp slave with docker client installed but every time i use docker command inside slave container get an error of docker daemon not running.

When i started the daemon manually using dockerd command getting an error.

![screenshot from 2017-12-24 01-16-58](https://user-images.githubusercontent.com/20029138/34322311-c2a08524-e849-11e7-9ead-a20711387f47.png)

I'm trying to run docker client in jenkins slave to automate my deploy process to GCR.

**Comment by mattfarina** [comment]
@dggs123 Errors you are getting are related to docker (more specifically containerd) and not to Kubernetes, charts, or helm. I'm not sure we can help you with that.
