### ISSUE TITLE
[stable/prometheus] Add option server.enabled

### ISSUE THREAD

**Issue by StianOvrevage** [helm/charts#3149]
**Is this a request for help?**: No
---
**FEATURE REQUEST**:
**Version of Helm and Kubernetes**: K8s 1.8.2. Helm 2.7.2.
**Which chart**: https://github.com/kubernetes/charts/tree/master/stable/prometheus

I want Helm to manage node_exporter on my cluster. But since there is no chart for https://github.com/prometheus/node_exporter , but node_exporter is included in the prometheus chart I thought about installing the prometheus chart but disabling everything except node_exporter:

`--set alertmanager.enabled=false,kubeStateMetrics.enabled=false,pushgateway.enabled=false`

There is however no option to not install the Prometheus server itself. I realize this might seem counter-intuitive, but it's just an option for those who know what they are doing. Another way would be to move node_exporter out to a separate chart and reference that chart from the prometheus chart. But I imagine that is much more work and less likely to get done.

So, I would really like an **server.enabled** option on the chart that I then can disable :)

**Anything else we need to know**: Happy holidays!

**Comment by mattfarina** [comment]
cc: @mgoodness

**Comment by hairyhenderson** [comment]
did #4260 resolve this?

**Comment by StianOvrevage** [comment]
I just looked at the new parameters added in the changed files and it does not appear any new parameter that would disable/enable the prometheus server itself were added.

**Comment by hairyhenderson** [comment]
@StianOvrevage what I meant was that there is now a separate `prometheus-node-exporter` chart - based on your original description:

> Another way would be to move node_exporter out to a separate chart and reference that chart from the prometheus chart. But I imagine that is much more work and less likely to get done.

Looks like it was done, despite the work 😉

**Comment by StianOvrevage** [comment]
Ahh, I forgot and missed that part!

Awesome stuff anyhow! 

🥇
