### ISSUE TITLE
Jenkins chart when persistence enabled, it installs fine POD stuck in " Init:0/1" state (PodInitializing).

### ISSUE THREAD

**Issue by anilreddyv** [helm/charts#3154]
on stable/jenkins chart when persistence enabled, it installs fine POD stuck in " Init:0/1" state (PodInitializing).

$ kubectl get pods -l app=invinvible-turkey-jenkins
NAME                                         READY     STATUS     RESTARTS   AGE
invinvible-turkey-jenkins-3987725818-mjp0l   0/1       Init:0/1   4          14m

$ kubectl logs invinvible-turkey-jenkins-3987725818-mjp0l
Error from server (BadRequest): container "invinvible-turkey-jenkins" in pod "invinvible-turkey-jenkins-3987725818-mjp0l" is waiting to start: PodInitializing

$ kubectl get pv
NAME         CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                               STORAGECLASS   REASON    AGE
jenkins-pv   9Gi        RWO           Delete          Bound     default/invinvible-turkey-jenkins   jenkins-pv               11m

$ kubectl get pvc
NAME                        STATUS    VOLUME       CAPACITY   ACCESSMODES   STORAGECLASS   AGE
invinvible-turkey-jenkins   Bound     jenkins-pv   9Gi        RWO           jenkins-pv     15m

$ kubectl describe pod invinvible-turkey-jenkins-3987725818-mjp0l
Name:   invinvible-turkey-jenkins-3987725818-mjp0l
Namespace:  default
Node:   x.x.x.x

Status:   Pending
IP:   x.x.x.x

    Mounts:
      /usr/share/jenkins/ref/plugins/ from plugin-dir (rw)
      /usr/share/jenkins/ref/secrets/ from secrets-dir (rw)
      /var/jenkins_config from jenkins-config (rw)
      /var/jenkins_home from jenkins-home (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from invinvible-turkey-jenkins-token-kv8zd (ro)
Containers:
    Ports:    8080/TCP, 50000/TCP
    Args:
      --argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)
      --argumentsRealm.roles.$(ADMIN_USER)=admin
    State:    Waiting
      Reason:   PodInitializing
    Ready:    False
    Restart Count:  0
    Requests:
      cpu:  200m
      memory: 256Mi
    Environment:
      JAVA_OPTS:
      JENKINS_OPTS:
      ADMIN_PASSWORD: <set to the key 'jenkins-admin-password' in secret 'invinvible-turkey-jenkins'> Optional: false
      ADMIN_USER: <set to the key 'jenkins-admin-user' in secret 'invinvible-turkey-jenkins'> Optional: false
    Mounts:
      /usr/share/jenkins/ref/plugins/ from plugin-dir (rw)
      /usr/share/jenkins/ref/secrets/ from secrets-dir (rw)
      /var/jenkins_config from jenkins-config (ro)
      /var/jenkins_home from jenkins-home (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from invinvible-turkey-jenkins-token-kv8zd (ro)
Conditions:
  Type    Status
  Initialized   False
  Ready   False
  PodScheduled  True
Volumes:
  jenkins-config:
    Type: ConfigMap (a volume populated by a ConfigMap)
    Name: invinvible-turkey-jenkins
    Optional: false
  plugin-dir:
    Type: EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  secrets-dir:
    Type: EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  jenkins-home:
    Type: PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  invinvible-turkey-jenkins
    ReadOnly: false
  invinvible-turkey-jenkins-token-kv8zd:
    Type: Secret (a volume populated by a Secret)
    SecretName: invinvible-turkey-jenkins-token-kv8zd
    Optional: false
QoS Class:  Burstable
Node-Selectors: <none>
Tolerations:  <none>
Events:
  FirstSeen LastSeen  Count From          SubObjectPath         Type    Reason      Message
  --------- --------  ----- ----          -------------         --------  ------      -------
  2m    2m    1 kubelet, worker-cls2-03             Normal    SuccessfulMountVolume MountVolume.SetUp succeeded for volume "secrets-dir"
  2m    2m    1 default-scheduler                 Normal    Scheduled   Successfully assigned invinvible-turkey-jenkins-3987725818-mjp0l to worker-cls2-03.container.com
  2m    2m    1 kubelet, worker-cls2-03             Normal    SuccessfulMountVolume MountVolume.SetUp succeeded for volume "jenkins-config"
  2m    2m    1 kubelet, worker-cls2-03             Normal    SuccessfulMountVolume MountVolume.SetUp succeeded for volume "jenkins-pv"
  2m    2m    1 kubelet, worker-cls2-03             Normal    SuccessfulMountVolume MountVolume.SetUp succeeded for volume "invinvible-turkey-jenkins-token-kv8zd"
  2m    2m    1 kubelet, worker-cls2-03 spec.initContainers{copy-default-config}  Normal    Pulling     pulling image "sc73registry01.container.com/jenkins/jenkins:lts"
  2m    2m    1 kubelet, worker-cls2-03 spec.initContainers{copy-default-config}  Normal    Pulled      Successfully pulled image "sc73registry01.container.com/jenkins/jenkins:lts"
  2m    2m    1 kubelet, worker-cls2-03 spec.initContainers{copy-default-config}  Normal    Created     Created container
  2m    2m    1 kubelet, worker-cls2-03 spec.initContainers{copy-default-config}  Normal    Started     Started container

-->

**Version of Helm and Kubernetes**:
K8: v1.7.9+coreos.0

$ helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

**Which chart**:
jenkins-0.10.2

**Comment by anilreddyv** [comment]
Changing initContainers to containers in following two template files, helped to deploy jenkins sucessfully. Not sure what is causing with initContainers?

$ grep -ri initcontainer *
templates/jenkins-master-deployment.yaml:      initContainers:
templates/jenkins-test.yaml:  initContainers:

**Comment by mattfarina** [comment]
cc: @lachie83 @viglesiasce

**Comment by djsly** [comment]
Having the same problem. the init container doesn't seem to have access to the PVC mounts.

```
kubectl -n jenkins-cd-test logs jk-jenkins-650608886-f0bq6 -c copy-default-config
cp: cannot create regular file '/var/jenkins_home/config.xml': Permission denied
cp: cannot create regular file '/var/jenkins_home/plugins.txt': Permission denied
cat: /var/jenkins_home/plugins.txt: No such file or directory
Creating initial locks...
Analyzing war...
Registering preinstalled plugins...
Using version-specific update center: https://updates.jenkins.io/2.89...
Downloading plugins...

WAR bundled plugins:


Installed plugins:
*:
Cleaning up locks
rm: cannot remove '/usr/share/jenkins/ref/plugins/*.lock': No such file or directory
```

```
kubectl -n jenkins-cd-test describe pod  jk-jenkins-650608886-f0bq6
Name:		jk-jenkins-650608886-f0bq6
Namespace:	jenkins-cd-test
Node:		kn-default-115/<ip>
Start Time:	Tue, 30 Jan 2018 14:44:14 +0000
Labels:		app=jk-jenkins
		chart=jenkins-0.11.0
		component=jk-jenkins-master
		heritage=Tiller
		pod-template-hash=650608886
		release=jk
Annotations:	checksum/config=faf30dcfac89ccaecb53f47fc76cdb4668e677629980b691303f25bb3aeae76a
		kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"jenkins-cd-test","name":"jk-jenkins-650608886","uid":"a8bd1b44-04fa-11e8-85f2-000...
		kubernetes.io/psp=privileged
Status:		Pending
IP:		<ip>
Created By:	ReplicaSet/jk-jenkins-650608886
Controlled By:	ReplicaSet/jk-jenkins-650608886
Init Containers:
  copy-default-config:
    Container ID:	docker://9348294598de765652d4802caf1ffe78131080d67a46702ba81e248430823970
    Image:		jenkins/jenkins:lts
    Image ID:		docker-pullable://jenkins/jenkins@sha256:3fc5ccef3d5851b61a5e9b850c338b03ec1b61c8a830d280b111fef229d1e847
    Port:		<none>
    Command:
      sh
      /var/jenkins_config/apply_config.sh
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Tue, 30 Jan 2018 14:55:22 +0000
      Finished:		Tue, 30 Jan 2018 14:55:23 +0000
    Ready:		False
    Restart Count:	7
    Environment:	<none>
    Mounts:
      /usr/share/jenkins/ref/plugins/ from plugin-dir (rw)
      /usr/share/jenkins/ref/secrets/ from secrets-dir (rw)
      /var/jenkins_config from jenkins-config (rw)
      /var/jenkins_home from jenkins-home (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-1n6mj (ro)
Containers:
  jk-jenkins:
    Container ID:	
    Image:		jenkins/jenkins:lts
    Image ID:		
    Ports:		8080/TCP, 50000/TCP
    Args:
      --argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)
      --argumentsRealm.roles.$(ADMIN_USER)=admin
    State:		Waiting
      Reason:		PodInitializing
    Ready:		False
    Restart Count:	0
    Requests:
      cpu:	200m
      memory:	256Mi
    Environment:
      JAVA_OPTS:	
      JENKINS_OPTS:	
      ADMIN_PASSWORD:	<set to the key 'jenkins-admin-password' in secret 'jk-jenkins'>	Optional: false
      ADMIN_USER:	<set to the key 'jenkins-admin-user' in secret 'jk-jenkins'>		Optional: false
    Mounts:
      /usr/share/jenkins/ref/plugins/ from plugin-dir (rw)
      /usr/share/jenkins/ref/secrets/ from secrets-dir (rw)
      /var/jenkins_config from jenkins-config (ro)
      /var/jenkins_home from jenkins-home (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-1n6mj (ro)
Conditions:
  Type		Status
  Initialized 	False 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  jenkins-config:
    Type:	ConfigMap (a volume populated by a ConfigMap)
    Name:	jk-jenkins
    Optional:	false
  plugin-dir:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
  secrets-dir:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
  jenkins-home:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	jk-jenkins
    ReadOnly:	false
  default-token-1n6mj:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-1n6mj
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	kubernetes.io/hostname=kn-default-115
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath					Type		Reason			Message
  ---------	--------	-----	----			-------------					--------	------			-------
  14m		14m		1	default-scheduler							Normal		Scheduled		Successfully assigned jk-jenkins-650608886-f0bq6 to kn-default-115
  14m		14m		1	kubelet, kn-default-115							Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "secrets-dir" 
  14m		14m		1	kubelet, kn-default-115							Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "plugin-dir" 
  14m		14m		1	kubelet, kn-default-115							Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "jenkins-config" 
  14m		14m		1	kubelet, kn-default-115							Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-1n6mj" 
  14m		14m		1	kubelet, kn-default-115							Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "pvc-bd74bc88-04f9-11e8-a083-000d3a050574" 
  14m		3m		8	kubelet, kn-default-115	spec.initContainers{copy-default-config}	Normal		Pulling			pulling image "jenkins/jenkins:lts"
  14m		3m		8	kubelet, kn-default-115	spec.initContainers{copy-default-config}	Normal		Pulled			Successfully pulled image "jenkins/jenkins:lts"
  14m		3m		8	kubelet, kn-default-115	spec.initContainers{copy-default-config}	Normal		Created			Created container
  14m		3m		8	kubelet, kn-default-115	spec.initContainers{copy-default-config}	Normal		Started			Started container
  14m		2s		85	kubelet, kn-default-115							Warning		FailedSync		Error syncing pod
  14m		2s		78	kubelet, kn-default-115	spec.initContainers{copy-default-config}	Warning		BackOff			Back-off restarting failed container
```


```
kubectl -n jenkins-cd-test get pvc
NAME         STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS                  AGE
jk-jenkins   Bound     pvc-bd74bc88-04f9-11e8-a083-000d3a050574   32Gi       RWO           azure-disk-managed-standard   1d
```

```
kubectl -n jenkins-cd-test get pv
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                            STORAGECLASS                  REASON    AGE
pvc-bd74bc88-04f9-11e8-a083-000d3a050574   32Gi       RWO           Delete          Bound     jenkins-cd-test/jk-jenkins       azure-disk-managed-standard             1d
```

**Comment by coderiseio** [comment]
@djsly  check last para in README titled - "Run Jenkins as non root user".

You will need this in your values.yaml:
jenkins:
  Master:
    RunAsUser: 1000
    FsGroup: 1000

IMP: You have to grant uid:group access to volume i.e. chown -R 1000:1000 /var/jenkins_home  before running helm. You can do it by mounting the volume to a busybox container as initContainer commands doesn't seem to work.

**Comment by holmesb** [comment]
I'm having this podinitialising problem too.  Tried changing RunAsUser & FsGroup to 1000, mounting in another container and re-permissioning jenkins_home to 1000:1000.  No dice.
Also failed to install helm chart after changing "initContainers" to "containers" in jenkins-master-deployment.yaml and jenkins-test.yaml template files:
```
$ helm install ./
Error: release smelly-bronco failed: Service in version "v1" cannot be handled as a Service: v1.Service: Spec: v1.ServiceSpec: Ports: []v1.ServicePort: v1.ServicePort: Port: readUint32: unexpected character: �, parsing 297 ...","port":n... at {"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"smelly-bronco-jenkins","chart":"jenkins-0.16.1","component":"smelly-bronco-jenkins-master","heritage":"Tiller","release":"smelly-bronco"},"name":"smelly-bronco-jenkins","namespace":"default"},"spec":{"ports":[{"name":"http","port":null,"targetPort":8080}],"selector":{"component":"smelly-bronco-jenkins-master"},"type":"ClusterIP"}}
```

**Comment by brycesteinhoff** [comment]
Same problem. Is this Helm chart broken for all users?

**Comment by crbichler** [comment]
For us, it was basically an issue with newer aws instances (c5,m5, etc) that utilize nvme storage.   See: 

https://github.com/kubernetes/kubernetes/issues/49926

resolved by using c4 or m4 instances.
