### ISSUE TITLE
Wrong indentation in config.yaml 

### ISSUE THREAD

**Issue by kmaiti** [helm/charts#3157]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Version of Helm and Kubernetes**:
Client: Version v2.7.1
Server: Version "v2.7.2
k8s 1.8.1

**Which chart**: sonarqube

**What happened**:
Getting error 
Error: YAML parse error on sonarqube/templates/config.yaml: error converting YAML to JSON: yaml: line 12: did not find expected key

**What you expected to happen**:
It shouldn't throw error.

Fix:
Remove all prepend space at line containing " {{ toYaml .Values.sonarProperties | indent 4}}" in sonarqube/templates/config.yaml:

**How to reproduce it** (as minimally and precisely as possible):
put values in Values.yaml for "sonarProperties"

sonarProperties:
  sonar.security.realm: LDAP
  
and execute 

helm install --debug --dry-run --name code-quality  stable/sonarqube --values=sonarqube_vars.yaml 

**Anything else we need to know**:

**Comment by mattfarina** [comment]
cc @rjkernick
