### ISSUE TITLE
Capture pod logs for statefulsets when there's a test failure

### ISSUE THREAD

**Issue by mattfarina** [helm/charts#3172]
If you look at the `helm status` for a statefulset you'll notice no pods are captured. For example,

```
RESOURCES:
==> v1/ConfigMap
NAME                                   DATA  AGE
bailing-mole-mongodb-replicaset        1     17m
bailing-mole-mongodb-replicaset-tests  1     17m

==> v1/Service
NAME                             TYPE       CLUSTER-IP  EXTERNAL-IP  PORT(S)    AGE
bailing-mole-mongodb-replicaset  ClusterIP  None        <none>       27017/TCP  17m

==> v1beta1/StatefulSet
NAME                             DESIRED  CURRENT  AGE
bailing-mole-mongodb-replicaset  3        3        17m
```

This is because they are under the statefulset. To find the pods we need to use the selector (see [this](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-identity) for more detail)

Once we have a selector we can use the labels in it to craft a kubectl query to list the pods (like `kubectl get pods -l app=mongodb-replicaset -l release=bailing-mole`).  kubectl can be used to find the selector programatically with json or yaml output. Once we have the pod names we can iterate over them to get the logs.

cc @viglesiasce @prydonius 

Any feedback on this plan is appreciated.

/assign

**Comment by prydonius** [comment]
I'm a little confused about the aim of this, I'm assuming this is related to printing pod logs (https://github.com/kubernetes/charts/blob/master/test/changed.sh#L39). Can I suggest we simplify this and just print logs from every pod in the release namespace? There shouldn't be any pods that aren't related to the chart in this namespace.

**Comment by mattfarina** [comment]
@prydonius That is a good idea. This is why I filed the issue before I started work.... hoping someone would have a simpler idea. Thanks.

**Comment by mattfarina** [comment]
Closing as this has not been implemented.

The way this was solved is that all pod logs in the namespace, which was created just for the PR review, have their logs displayed. It looks for all the logs in all containers in all pods.
