### ISSUE TITLE
helm install stable/traefik fails

### ISSUE THREAD

**Issue by sathishningaiah** [helm/charts#3174]
**Is this a request for help?**:
Yes.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 

**Version of Helm and Kubernetes**:
**Helm**
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

**Kuberenetes**
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
[sathish@k8sManager ~]$ helm search | grep trae
stable/traefik                  1.14.5  A Traefik based Kubernetes ingress controller w...

**What happened**:
[sathish@k8sManager ~]$ helm install stable/traefik
Error: no available release name found

**What you expected to happen**:
Install to proceed without errors.

**How to reproduce it** (as minimally and precisely as possible):
 helm install stable/traefik 

**Anything else we need to know**:

**Comment by mattfarina** [comment]
@sathishningaiah I understand your frustration at that. This is related to [helm](https://github.com/kubernetes/helm) rather than the charts. What's happening here is that helm tried to auto-generate a release name and found the names it tried were taken. It tries 5 times to generate a name so I'm surprised it could not find one already in use.

Can you run:
```
helm --debug install stable/traefik
```

This will provide more verbose output and display what's actually going on.

**Comment by sathishningaiah** [comment]
Matt, Thanks for the response. Ran with debug flag with no additional information that I could decipher. Attaching output
Thank you


[sathish@k8sManager ~]$ helm --debug install stable/traefik
[debug] Created tunnel using local port: '37585'

[debug] SERVER: "127.0.0.1:37585"

[debug] Original chart version: ""
[debug] Fetched stable/traefik to /home/sathish/.helm/cache/archive/traefik-1.14.5.tgz

[debug] CHART PATH: /home/sathish/.helm/cache/archive/traefik-1.14.5.tgz

Error: no available release name found

[sathish@k8sManager ~]$ kubectl get deployments --all-namespaces
NAMESPACE     NAME                         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   heapster                     1         1         1            1           1d
kube-system   kube-dns                     1         1         1            1           3d
kube-system   kubernetes-dashboard         1         1         1            1           3d
kube-system   monitoring-grafana           1         1         1            1           1d
kube-system   monitoring-influxdb          1         1         1            1           1d
kube-system   tiller-deploy                1         1         1            1           17h
kube-system   traefik-ingress-controller   1         1         1            1           17h
[sathish@k8sManager ~]$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                          READY     STATUS    RESTARTS   AGE
kube-system   etcd-k8s03.hra.nycnet                         1/1       Running   4          3d
kube-system   heapster-dfd674df9-qmggz                      1/1       Running   0          1d
kube-system   kube-apiserver-k8s03.hra.nycnet               1/1       Running   5          3d
kube-system   kube-controller-manager-k8s03.hra.nycnet      1/1       Running   5          3d
kube-system   kube-dns-6f4fd4bdf-jd7t6                      3/3       Running   29         3d
kube-system   kube-flannel-ds-gprlh                         1/1       Running   1          3d
kube-system   kube-flannel-ds-p68wh                         1/1       Running   5          3d
kube-system   kube-flannel-ds-qtsww                         1/1       Running   1          3d
kube-system   kube-flannel-ds-rgxf9                         1/1       Running   0          2d
kube-system   kube-flannel-ds-x2mdh                         1/1       Running   1          2d
kube-system   kube-proxy-jcr5g                              1/1       Running   1          3d
kube-system   kube-proxy-jctcs                              1/1       Running   0          2d
kube-system   kube-proxy-jqdxh                              1/1       Running   1          3d
kube-system   kube-proxy-s2ktw                              1/1       Running   5          3d
kube-system   kube-proxy-zth6s                              1/1       Running   0          2d
kube-system   kube-scheduler-k8s03.hra.nycnet               1/1       Running   5          3d
kube-system   kubernetes-dashboard-7b7b5cd79b-kqw5v         1/1       Running   0          3d
kube-system   monitoring-grafana-76848b566c-xx4bv           1/1       Running   0          1d
kube-system   monitoring-influxdb-6c4b84d695-m6w6j          1/1       Running   0          1d
kube-system   tiller-deploy-587df449fb-9xr7s                1/1       Running   0          17h
kube-system   traefik-ingress-controller-77ffbd95b8-q4bbx   1/1       Running   0          17h
[sathish@k8sManager ~]$ kubectl get services  --all-namespaces
NAMESPACE     NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                       AGE
default       kubernetes                ClusterIP   10.96.0.1        <none>        443/TCP                       3d
kube-system   heapster                  ClusterIP   10.102.79.16     <none>        80/TCP                        1d
kube-system   kube-dns                  ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP                 3d
kube-system   kubernetes-dashboard      ClusterIP   10.111.235.207   <none>        443/TCP                       3d
kube-system   monitoring-grafana        NodePort    10.111.173.129   <none>        80:32004/TCP                  1d
kube-system   monitoring-influxdb       ClusterIP   10.97.232.193    <none>        8086/TCP                      1d
kube-system   tiller-deploy             ClusterIP   10.98.173.20     <none>        44134/TCP                     17h
kube-system   traefik-ingress-service   NodePort    10.109.192.162   <none>        80:30524/TCP,8080:30881/TCP   17h
[sathish@k8sManager ~]$

Regards,
Sathish Ningaiah
Director, Network Integrity

**Comment by sathishningaiah** [comment]
Some additional info


[sathish@k8sManager ~]$ helm install --debug stable/traefik --name my-release --namespace kube-system
[debug] Created tunnel using local port: '46086'

[debug] SERVER: "127.0.0.1:46086"

[debug] Original chart version: ""
[debug] Fetched stable/traefik to /home/sathish/.helm/cache/archive/traefik-1.14.5.tgz

[debug] CHART PATH: /home/sathish/.helm/cache/archive/traefik-1.14.5.tgz

Error: release my-release failed: namespaces "kube-system" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "kube-system"
[sathish@k8sManager ~]$ helm install --debug stable/traefik --name my-release --namespace
Error: flag needs an argument: --namespace
[sathish@k8sManager ~]$ helm install --debug stable/traefik --name my-release
[debug] Created tunnel using local port: '40476'

[debug] SERVER: "127.0.0.1:40476"

[debug] Original chart version: ""
[debug] Fetched stable/traefik to /home/sathish/.helm/cache/archive/traefik-1.14.5.tgz

[debug] CHART PATH: /home/sathish/.helm/cache/archive/traefik-1.14.5.tgz

Error: release my-release failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "default"
[sathish@k8sManager ~]$ helm install --debug stable/traefik
[debug] Created tunnel using local port: '34456'

[debug] SERVER: "127.0.0.1:34456"

[debug] Original chart version: ""
[debug] Fetched stable/traefik to /home/sathish/.helm/cache/archive/traefik-1.14.5.tgz

[debug] CHART PATH: /home/sathish/.helm/cache/archive/traefik-1.14.5.tgz

Error: no available release name found
[sathish@k8sManager ~]$ cat tilrbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""

Regards,
Sathish Ningaiah
Director, Network Integrity

**Comment by sathishningaiah** [comment]
fixed with rbac from
http://jayunit100.blogspot.com/2017/07/helm-on.html
