### ISSUE TITLE
Unable to install MongoDB ReplicaSet

### ISSUE THREAD

**Issue by sidguptajhs** [helm/charts#3194]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.7.2. ; Kubernetes 1.8.5

**Which chart**:
mongodb-replicaset

**What happened**:
I'm unable to install the chart on my Kubernetes cluster in AWS. I'm getting an error:

> Unable to mount volumes for pod "mongox2-mongodb-replicaset-0_default(c47e2201-ef0d-11e7-8b1b-124aed2830ba)": timeout expired waiting for volumes to attach/mount for pod "default"/"mongox2-mongodb-replicaset-0". list of unattached/unmounted volumes=[datadir]

The persistent volume is getting created and its status shows 'BOUND' but the pod is stuck in 'Init:0/2' stage.

**What you expected to happen**:
I expected to have a working Mongo installation

**How to reproduce it** (as minimally and precisely as possible):
In an AWS based cluster (created with kops), Just do:
helm install --name mongo stable/mongodb-replicaset 

**Anything else we need to know**:

**Comment by mattfarina** [comment]
cc @foxish

**Comment by foxish** [comment]
@sidguptajhs, can you `kubectl describe` the PV, PVC and the pods? Do they have any additional interesting logging info?

**Comment by sidguptajhs** [comment]
**PV:**

> Name:            pvc-4d7d7ab5-f259-11e7-8119-06f8875f2192
> Labels:          failure-domain.beta.kubernetes.io/region=us-east-1
>                  failure-domain.beta.kubernetes.io/zone=us-east-1c
> Annotations:     kubernetes.io/createdby=aws-ebs-dynamic-provisioner
>                  pv.kubernetes.io/bound-by-controller=yes
>                  pv.kubernetes.io/provisioned-by=kubernetes.io/aws-ebs
> StorageClass:    gp2
> Status:          Bound
> Claim:           default/datadir-mongoha-mongodb-replicaset-0
> Reclaim Policy:  Delete
> Access Modes:    RWO
> Capacity:        10Gi
> Message:         
> Source:
>     Type:       AWSElasticBlockStore (a Persistent Disk resource in AWS)
>     VolumeID:   aws://us-east-1c/vol-0d8a30e158b7d4aaf
>     FSType:     ext4
>     Partition:  0
>     ReadOnly:   false
> Events:         <none>
> 

**PVC:**

> Name:          datadir-mongoha-mongodb-replicaset-0
> Namespace:     default
> StorageClass:  gp2
> Status:        Bound
> Volume:        pvc-4d7d7ab5-f259-11e7-8119-06f8875f2192
> Labels:        app=mongodb-replicaset
>                release=mongoha
> Annotations:   pv.kubernetes.io/bind-completed=yes
>                pv.kubernetes.io/bound-by-controller=yes
>                volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/aws-ebs
> Capacity:      10Gi
> Access Modes:  RWO
> Events:
>   Type    Reason                 Age   From                         Message
>   ----    ------                 ----  ----                         -------
>   Normal  ProvisioningSucceeded  7m    persistentvolume-controller  Successfully provisioned volume pvc-4d7d7ab5-f259-11e7-8119-06f8875f2192 using kubernetes.io/aws-ebs

**POD:**

> Name:           mongoha-mongodb-replicaset-0
> Namespace:      default
> Node:           ip-172-20-71-110.ec2.internal/172.20.71.110
> Start Time:     Sat, 06 Jan 2018 02:15:05 +0530
> Labels:         app=mongodb-replicaset
>                 controller-revision-hash=mongoha-mongodb-replicaset-cf654c974
>                 release=mongoha
> Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"default","name":"mongoha-mongodb-replicaset","uid":"4d76d8ec-f259-11e7-8119-06f8...
>                 kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container mongodb-replicaset; cpu request for init container install; cpu request for init container bootstrap
> Status:         Pending
> IP:             
> Created By:     StatefulSet/mongoha-mongodb-replicaset
> Controlled By:  StatefulSet/mongoha-mongodb-replicaset
> Init Containers:
>   install:
>     Container ID:  
>     Image:         gcr.io/google_containers/mongodb-install:0.5
>     Image ID:      
>     Port:          <none>
>     Args:
>       --work-dir=/work-dir
>     State:          Waiting
>       Reason:       PodInitializing
>     Ready:          False
>     Restart Count:  0
>     Requests:
>       cpu:        100m
>     Environment:  <none>
>     Mounts:
>       /config from config (rw)
>       /var/run/secrets/kubernetes.io/serviceaccount from default-token-64chn (ro)
>       /work-dir from workdir (rw)
>   bootstrap:
>     Container ID:  
>     Image:         mongo:3.4
>     Image ID:      
>     Port:          <none>
>     Command:
>       /work-dir/peer-finder
>     Args:
>       -on-start=/work-dir/on-start.sh
>       -service=mongoha-mongodb-replicaset
>     State:          Waiting
>       Reason:       PodInitializing
>     Ready:          False
>     Restart Count:  0
>     Requests:
>       cpu:  100m
>     Environment:
>       POD_NAMESPACE:  default (v1:metadata.namespace)
>       REPLICA_SET:    rs0
>     Mounts:
>       /config from config (rw)
>       /data/db from datadir (rw)
>       /var/run/secrets/kubernetes.io/serviceaccount from default-token-64chn (ro)
>       /work-dir from workdir (rw)
> Containers:
>   mongodb-replicaset:
>     Container ID:  
>     Image:         mongo:3.4
>     Image ID:      
>     Port:          27017/TCP
>     Command:
>       mongod
>       --config=/config/mongod.conf
>     State:          Waiting
>       Reason:       PodInitializing
>     Ready:          False
>     Restart Count:  0
>     Requests:
>       cpu:        100m
>     Liveness:     exec [mongo --eval db.adminCommand('ping')] delay=30s timeout=5s period=10s #success=1 #failure=3
>     Readiness:    exec [mongo --eval db.adminCommand('ping')] delay=5s timeout=1s period=10s #success=1 #failure=3
>     Environment:  <none>
>     Mounts:
>       /config from config (rw)
>       /data/db from datadir (rw)
>       /var/run/secrets/kubernetes.io/serviceaccount from default-token-64chn (ro)
>       /work-dir from workdir (rw)
> Conditions:
>   Type           Status
>   Initialized    False 
>   Ready          False 
>   PodScheduled   True 
> Volumes:
>   datadir:
>     Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
>     ClaimName:  datadir-mongoha-mongodb-replicaset-0
>     ReadOnly:   false
>   config:
>     Type:      ConfigMap (a volume populated by a ConfigMap)
>     Name:      mongoha-mongodb-replicaset
>     Optional:  false
>   workdir:
>     Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
>     Medium:  
>   default-token-64chn:
>     Type:        Secret (a volume populated by a Secret)
>     SecretName:  default-token-64chn
>     Optional:    false
> QoS Class:       Burstable
> Node-Selectors:  <none>
> Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
>                  node.alpha.kubernetes.io/unreachable:NoExecute for 300s
> Events:
>   Type     Reason                 Age              From                                    Message
>   ----     ------                 ----             ----                                    -------
>   Warning  FailedScheduling       8m (x3 over 8m)  default-scheduler                       PersistentVolumeClaim is not bound: "datadir-mongoha-mongodb-replicaset-0" (repeated 8 times)
>   Normal   Scheduled              8m               default-scheduler                       Successfully assigned mongoha-mongodb-replicaset-0 to ip-172-20-71-110.ec2.internal
>   Normal   SuccessfulMountVolume  8m               kubelet, ip-172-20-71-110.ec2.internal  MountVolume.SetUp succeeded for volume "workdir"
>   Normal   SuccessfulMountVolume  8m               kubelet, ip-172-20-71-110.ec2.internal  MountVolume.SetUp succeeded for volume "config"
>   Normal   SuccessfulMountVolume  8m               kubelet, ip-172-20-71-110.ec2.internal  MountVolume.SetUp succeeded for volume "default-token-64chn"
>   Warning  FailedMount            8m               attachdetach                            AttachVolume.Attach failed for volume "pvc-4d7d7ab5-f259-11e7-8119-06f8875f2192" : Error attaching EBS volume "vol-0d8a30e158b7d4aaf" to instance "i-0bf0cdb023eb8605c": "IncorrectState: vol-0d8a30e158b7d4aaf is not 'available'.\n\tstatus code: 400, request id: 5e0aa98f-5b6a-4bfe-9d3b-5ead8b6b7371"
>   Warning  FailedMount            1m (x3 over 6m)  kubelet, ip-172-20-71-110.ec2.internal  Unable to mount volumes for pod "mongoha-mongodb-replicaset-0_default(4d7f9275-f259-11e7-8119-06f8875f2192)": timeout expired waiting for volumes to attach/mount for pod "default"/"mongoha-mongodb-replicaset-0". list of unattached/unmounted volumes=[datadir]
>   Warning  FailedSync             1m (x3 over 6m)  kubelet, ip-172-20-71-110.ec2.internal  Error syncing pod

**Comment by sidguptajhs** [comment]
Nevermind, I figured out the problem. This most likely lies outside the scope of kubernetes charts.
So I was using an m5.large instance which uses NVME disks. Mounting of persistent volumes is not supported on KOPS 1.8 based Clusters. The feature is expected to be released in 1.9.

**Comment by toddams** [comment]
I'm using m4.large and still experiencing this issue :(

**Comment by madhifallah** [comment]
In my case I found that iscsid process was at 100% of cpu usage in the node where the volume was supposed to be mounted, thus it was impossible to mount it.
