### ISSUE TITLE
[incubator/elasticsearch] not ready for fullname with 63 chars

### ISSUE THREAD

**Issue by tmaier** [helm/charts#3195]
**Is this a request for help?**: No

---

**BUG REPORT**

**Version of Helm and Kubernetes**:

```text
$ helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T18:09:07Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4-gke.1", GitCommit:"04502ae78d522a3d410de3710e1550cfb16dad4a", GitTreeState:"clean", BuildDate:"2017-12-08T17:24:53Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

incubator/elasticsearch

**What happened**:

Scenario: very long release name --> leading to hit the 63 chars limit of `elasticsearch.fullname`

StatefulSet are unable to create the Pods.

Following error message is being shown:

`$ kubectl describe -n librario-dev statefulsets/<my-release-name>-bkfs61-elasticsearch-master`

> create Pod librario-library-feature-kubernete-bkfs61-elasticsearch-master-0 in StatefulSet <my-release-name>-bkfs61-elasticsearch-master failed error: Pod "<my-release-name>-bkfs61-elasticsearch-master-0" is invalid: [metadata.labels: Invalid value: "<my-release-name>-bkfs61-elasticsearch-master-76c747f7b6": must be no more than 63 characters, spec.hostname: Invalid value: "<my-release-name>-bkfs61-elasticsearch-master-0": must be no more than 63 characters]

`<my-release-name>-bkfs61-elasticsearch-master-76c747f7b6` is 74 characters
`<my-release-name>-bkfs61-elasticsearch-master-0` is 65 characters

**What you expected to happen**:

* StatefulSet is able to create Pods when the release name hits the limits
* Names and labels get truncated as appropriate

**How to reproduce it** (as minimally and precisely as possible):

`$ helm install --name asdfghjkloasdfghjkloasdfghjkloasdfghjklas incubator/elasticsearch`

Name had in my case 42 characters (autogenerated by CI pipeline)

**Anything else we need to know**:

N/A

**Comment by mattfarina** [comment]
cc @icereval

**Comment by icereval** [comment]
@tmaier, this issue appears to be a `_helpers.tpl` pattern issue with combining more than two strings to build the a statefulset pod name.

This is probably best left for consideration with Helm v3, as name definitions are in need of a standardizing template naming library/function call throughout the charts repo.

Thanks for reporting the issue though! If you'd like to apply a local workaround, this might work.

WORKAROUND:

```
{{/*
Create a default fully qualified data name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).

release name
(dash)
chart name
(dash)
pod name
(dash)
controller-revision-hash (10 digit hash)

*/}}
{{- define "elasticsearch.data.fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- $trunc := sub 63 (len .Values.data.name | add 12) | int -}}
{{- $truncName := printf "%s-%s" .Release.Name $name | trunc $trunc | trimSuffix "-" -}}
{{- printf "%s-%s" $truncName .Values.data.name -}}
{{- end -}}
```
