### ISSUE TITLE
[stable/concourse] Clean up env var mappings using envFrom

### ISSUE THREAD

**Issue by william-tran** [helm/charts#3208]
The configmap template for concourse only serves to map values to env vars, but why can't we just do this directly? I haven't seen a chart that does this as extensively, and it seems like needless repetition each time we add a new value that needs to end up as an env var. Are there advantages to this technique that I'm missing?

Paging @mattfarina @viglesiasce @nexeck for your opinion

**Comment by viglesiasce** [comment]
Great point @william-tran!

This is because the chart was originally written before the ability to [map an entire config map in as env variables](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-a-pod-environment-variable-with-data-from-a-single-configmap).

I think switching to that would be the best case scenario. 

Would you be able to do a PR?

**Comment by nexeck** [comment]
So instead of getting rid of the hole configmap, we could just use envFrom?

**Comment by william-tran** [comment]
@viglesiasce thanks for pointing me to the `envFrom` solution. I'd also like to take the same approach for secrets, and additionally make the management of secrets using helm optional with `secrets.create: false` and wrap the secrets template in an `{{- if .Values.secrets.create -}}`. I've found having helm manage all the secrets problematic as I've needed to keep a `secret-values.yaml` file around and use it each time I helm upgrade. This can also get around the whole issue of Helm knowing all your secrets (see https://github.com/kubernetes/helm/issues/2196). It's great for getting up and running right out of the box, but charts need a way to transition off having secrets managed by Helm so you can do it your self out of band; I'd like to try that approach with this chart. 

This is a breaking change but I'm happy to take this on, along with the breaking change I'm proposing in #2911

**Comment by nexeck** [comment]
@william-tran Would be great to see the secrets optional.

**Comment by william-tran** [comment]
Addressed in #3254
