### ISSUE TITLE
[stable/mysql] Typo in README.md

### ISSUE THREAD

**Issue by shal** [helm/charts#3216]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Doesn't matter

**Which chart**:
[`stable/mysql`](https://github.com/kubernetes/charts/tree/master/stable/mysql)

**What happened**:
mysql configuration file extension typo in `README.md`

**What you expected to happen**:
Fix typo in README.md

**How to reproduce it** (as minimally and precisely as possible):
Fix typo in README.md

**Anything else we need to know**:
`.cfn` is wrong, `.cnf` is right name

**Comment by sameersbn** [comment]
Resolved in https://github.com/kubernetes/charts/pull/3217
