### ISSUE TITLE
[stable/nginx-ingress] Prometheus metrics, why is the statsExporter sidecar needed?

### ISSUE THREAD

**Issue by dannyk81** [helm/charts#3290]
**Is this a request for help?**: Yes

We are working on moving the deployment of our nginx ingress controller to use the stable Helm chart, but I have some doubts about the stats/metrics.

AFAIK (and according to [docs](https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/customization/custom-vts-metrics-prometheus#prometheus-metrics-output)) the controller already exposes the vts metrics on `:10254/metrics` if the `enable-vts-status: "true"` config option is provided in the ConfigMap and in fact we have been using it thus far to scrape the metrics with Prometheus.

However, the Chart is deploying an additional sidecar (`stats-exporter`) that queries the `vts` status page and exposes the metrics in Prometheus format using the `nginx-vts-exporter`.

Why is the above required? why not simply scrape the metrics that are exposed by the controller itself?

**Comment by mattfarina** [comment]
cc @jackzampolin @mgoodness @chancez

**Comment by jackzampolin** [comment]
@mgoodness Added that feature. I'm not quite sure.

**Comment by dannyk81** [comment]
Thanks @jackzampolin, I just deployed this Chart in our test cluster and slightly modified the daemonset annotations so that Prometheus will scrape the metrics from the pods on `:10254/metrics` endpoints and it just works.

Perhaps the statsExporter sidecar is more advanced? provides more metrics?

Anyhow, hope to hear some feedback from @mgoodness.

**Comment by jackzampolin** [comment]
Thats the way I'm getting stats out of it in my cluster. I haven't set up the side car yet 🙊

**Comment by chancez** [comment]
I have no idea, but I'm willing to bet that metrics gathering was added to nginx-ingress sometime after the helm chart got the sidecar added. It would make sense, but I'm too lazy to check git to verify.

The biggest thing we have to considering is backwards compatibility. I'm looking at the two, and I think they might have different metrics labels, so we can probably make metrics available by default using the built-in nginx ingress, unless the sidecar is enabled, then we should prefer that. Maybe after 1 release we can then remove the side-car option, or something.

I don't think most users are upgrading their nginx-ingress chart super frequently, but I know removing the sidecar entirely is likely to prompt some issue at least for a few people, so leaving it as option probably makes sense for a little, but preferring the nginx-ingress built-in exporter is probably a good thing.

**Comment by dannyk81** [comment]
Thanks @chancez 

Your approach sounds reasonable, currently the side-car is tightly coupled with enabled vts in nginx, so a first step to allow enabling just one of the options would be great, in fact it's what I'm doing now with my "custom" version of the Chart.

Going forward, I see no reason to use the side-car except for backward-compatability.

**Comment by lambertjosh** [comment]
This would really clean things up, now that 0.9.0 has embedded metrics. +1.

**Comment by kfox1111** [comment]
When the chart was added, there was no built in support for prometheus. it is supoprted now, so I agree the sidecar should be dropped. I don't think anyone is running 0.8 anymore? It was fairly buggy. :(

also, though, the :10254/metrics endpoint is not available to prometheus if it isn't listed in the pods ports list, so it is currently inaccessable without patching. Can that be added please?

**Comment by monotek** [comment]
Seems the sidecar is away in current version (helm chart 0.14.1)?
At least its not started anymore. 
Unfortunately with the included endpoint my dashboard (https://grafana.com/dashboards/2949) does not work anymore.

**Comment by unguiculus** [comment]
The sidecar is no longer necessary and was removed. The ingres controller itself exports Prometheus metrics.

@monotek You'll have to update the dashboard.

**Comment by monotek** [comment]
I know. This one works: https://grafana.com/dashboards/3050

**Comment by shinebayar-g** [comment]
Sorry for reviving old issue, @monotek Dashboard 3050 is not working for me.
Because nginx ingress is exposing only those metrics for me, I'm not seeing any nginx_* metrics. Am I doing anything wrong?
![image](https://user-images.githubusercontent.com/3091558/48929785-b9cfd000-ef26-11e8-9196-0983d04560eb.png)

**Comment by monotek** [comment]
You have to enable the metrics in nginx helm chart: https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L238-L263

But i guess the 3050 chart will not work anyway as the metric names changed...

**Comment by shinebayar-g** [comment]
I've enabled metrics on helm yaml here is the part:
```YAML
metrics:
    enabled: true
    service:
      annotations: {}
      prometheus.io/scrape: "true"
      prometheus.io/port: "10254"
```

and if I access my nginx ingress /metrics endpoint it returns prometheus metrics, thus resulting Prometheus reports nginx is UP and I'm seeing those exposed metrics on nginx job.
But those exposed metrics are not familiar to me, can you confirm that those metrics are really the right ones?

**Comment by shinebayar-g** [comment]
Ah I see, I've just enabled
```YAML
  stats:
      enabled: true
```
and upgraded helm chart.
But prometheus didn't get any new metrics from nginx..

This is my prometheus.yaml job for nginx:
```YAML
- job_name: nginx-ingress
  metrics_path: /metrics
  static_configs:
    - targets:
      - nginx-ingress-controller:80
```
If I go to my nginx ingress IP address' `/metrics` endpoint I can check prometheus exposed metrics.

**Comment by hamdifourati** [comment]
@shinebayar-g probably this too late but I believe you are not configuring the annotations properly. So instead of:
```
service:
  annotations: {}
   prometheus.io/scrape: "true"
   prometheus.io/port: "10254"
```  
Use:
```
service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
```

**Comment by shinebayar-g** [comment]
I've got that, thank you :+1:
