### ISSUE TITLE
[redis-ha] Add support for RBAC

### ISSUE THREAD

**Issue by gtie** [helm/charts#3305]
**Is this a request for help?**:

---

BUG REPORT:

**Version of Helm and Kubernetes**:
Kubernetes v1.8.6
Helm v.v2.7.2

**Which chart**:
redis-ha

**What happened**:
After installing the redis-ha chart with Helm (with all default values) on a cluster with enabled Authorization (RBAC), the reedis server is not available. The logs read:
```
Starting redis launcher       
Setting labels               
Selecting proper service to execute           
podIP 100.96.3.4                         
Looking for pods running as master
Error from server (Forbidden): pods is forbidden: User "system:serviceaccount:default:default" cannot list pods in the namespace "default"
Error from server (Forbidden): pods "redisha-redis-ha-server-75c6b89cdc-bzmxm" is forbidden: User "system:serviceaccount:default:default" cannot get pods in the namespace "default"
No masters found: "" Electing first master...
Could not connect to Redis at 127.0.0.1:6379: Connection refused                        
Error from server (Forbidden): pods is forbidden: User "system:serviceaccount:default:default" cannot list pods in the namespace "default"
Electing  master 
Error from server (Forbidden): pods "redisha-redis-ha-server-75c6b89cdc-bzmxm" is forbidden: User "system:serviceaccount:default:default" cannot get pods in the namespace "default"

```

**What you expected to happen**:
The redis service to be available.

**How to reproduce it** (as minimally and precisely as possible):
Against an RBAC-enabled (https://kubernetes.io/docs/admin/authorization/rbac/) cluster
`helm install redis-ha`

**Comment by bzumhagen** [comment]
@ianmaddox @viglesiasce

Can you guys take a look?
