### ISSUE TITLE
Jenkins kubernetes-plugin:v0.10

### ISSUE THREAD

**Issue by kingdonb** [helm/charts#331]
Filed as #328 but I haven't signed a CLA yet

The latest version of the kubernetes-plugin for Jenkins expects a container named "jnlp" or it will create one for you.  This is bad because it results in your jobs sometimes running against the wrong container.  Not sure how it chooses or what was intended by this change.

This version of the plugin is not installed by the chart (still on v0.8 as of the last chart update) but you still wind up with this version installed if you follow the auto-upgrade prompts presented by Jenkins admin console.  I rebuilt the master-image for myself and upgraded that way instead.

Confusingly, setting the name of the PodTemplate in values.yaml also sets the name of the container.  Not sure what a PodTemplate with multiple containers or separate jnlp container would look like.  I like the idea of separating the JNLP service, but I'm not sure putting it in a separate container is the best way.

Docker Slaves plugin uses Compose in an interesting way to accomplish what I assume is the same goal... but I digress!  This appears to be a breaking change coming down the pipe, heads-up.

**Comment by kingdonb** [comment]
Just read over #315, looks like exactly the hero we need

I will clone that and give it a try.

**Comment by viglesiasce** [comment]
Looks like we are all set
