### ISSUE TITLE
[stable/nginx-ingress] RBAC option not being honored

### ISSUE THREAD

**Issue by galbacarys** [helm/charts#3321]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Version of Helm and Kubernetes**: Helm: v2.7.2; Kubernetes: v1.7.0

**Which chart**: stable/nginx-ingress

**What happened**: RBAC objects are not created when rbac.create set to `true`. This causes the nginx-ingress pod to fail upon starting.

**What you expected to happen**: RBAC objects (service account, roleclusterbinding, etc.) should be created.

**How to reproduce it** (as minimally and precisely as possible): I have a vars.yaml file with the following contents:
```yaml
rbac:
  create: true
```
When I run `helm install stable/nginx-ingress -f ./vars.yaml --name nginx-ingress --namespace nginx-ingress --dry-run --debug` and dump the output to a file, the service account and related RBAC objects do not show up in the manifest. Alternately, running the above command without `--dry-run` causes the chart to successfully deploy, but then the pod to fail when it cannot access the required K8s APIs. I get the following error message in the pod itself:

```
[dumb-init] setsid complete.
I0112 20:25:30.002049       6 launch.go:105] &{NGINX 0.9.0-beta.11 git-a3131c5 https://github.com/kubernetes/ingress}
I0112 20:25:30.002136       6 launch.go:108] Watching for ingress class: nginx
I0112 20:25:30.002205       6 nginx.go:182] starting NGINX process...
I0112 20:25:30.002595       6 launch.go:262] Creating API server client for https://100.64.0.1:443
F0112 20:25:30.013845       6 launch.go:122] no service with name nginx-ingress/nginx-ingress-nginx-ingress-default-backend found: User "system:serviceaccount:nginx-ingress:default" cannot get services in the namespace "nginx-ingress". (get services nginx-ingress-nginx-ingress-default-backend)
[dumb-init] Received signal 17.
[dumb-init] A child with PID 6 exited with exit status 255.
[dumb-init] Forwarded signal 15 to children.
[dumb-init] Child exited with status 255. Goodbye.
```

**Anything else we need to know**: I am by no means a helm expert, but I'm happy to submit any more information that might be useful to debugging this issue.

**Comment by GJKrupa** [comment]
I'm seeing exactly the same issue.  It also doesn't seem to be honouring the rbac.serviceAccountName setting as well.  This is causing issues as the kube-system:default service.  I'm running k8s 1.10.2 and helm 2.9.0.

Attached is the output from running:
helm install stable/nginx-ingress \
        --name ingress \
        --set controller.hostNetwork=true \
        --set controller.kind=DaemonSet \
        --set rbac.serviceAccountName=tiller --dry-run --debug > ~/Desktop/nginx.txt

[nginx.txt](https://github.com/kubernetes/charts/files/1983997/nginx.txt)

/remove-lifecycle stale
