### ISSUE TITLE
[stable/ghost] Fails to install with default arguments

### ISSUE THREAD

**Issue by grantbachman** [helm/charts#3327]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**: Helm v2.7.2, Kubernetes v1.8.4

**Which chart**: stable/ghost

**What happened**: Ghost pod fails to start with default ghost docker image

**What you expected to happen**: Ghost pod to start successfully.

**How to reproduce it** (as minimally and precisely as possible): `helm install stable/ghost --set serviceType=ClusterIP`. This yields the following logs from the ghost pod:
```
Welcome to the Bitnami ghost container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues
Send us your feedback at containers@bitnami.com

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing ghost
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at blog-mariadb:3306
mysql-c INFO  MySQL server listening and working at blog-mariadb:3306
ghost   INFO  ==> Configuring Database...
ghost   INFO  ==> Configuring Ghost...
Error executing 'postInstallation': Message: Prompts have been disabled, please provide options via command line flags
```

**Anything else we need to know**: The most recent Bitnami Ghost Docker image that works with the default setup is the 1.18.4-r0 release. We may want to set this as the default image until the problem is fixed upstream in the Ghost CLI. I can submit a PR if needed.

**Comment by grantbachman** [comment]
PR #3332 will resolve this issue.

**Comment by sameersbn** [comment]
The referenced PR has been merged.
