### ISSUE TITLE
[stable/rabbitmq] Expose affinity, nodeSelector, and tolerations on rabbitmq

### ISSUE THREAD

**Issue by md-mq** [helm/charts#3335]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

It would be nice to have more control over the deployment's behavior of rabbitmq by exposing/templating affinity, nodeSelector, and tolerations:

variable | description | default
-- | -- | --
nodeSelector | Node labels for pod assignment | {}
affinity | Affinity settings for pod assignment | {}
tolerations | Toleration labels for pod assignment | []

**Version of Helm and Kubernetes**:

**Which chart**:

rabbitmq

**What happened**:

**What you expected to happen**:

more control over the pods behaviour

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by Antiarchitect** [comment]
You can close it now :)

**Comment by md-mq** [comment]
Great! thank you for the reactivity 👍
