### ISSUE TITLE
Allow traefik Service to be configured with the annotations necessary for AWS ELB

### ISSUE THREAD

**Issue by itamarst** [helm/charts#334]
As documented here - https://github.com/kubernetes/kubernetes/blob/master/docs/design/aws_under_the_hood.md#nodeport-and-loadbalancer-services - if you want AWS ELB configured you need to add certain annotations to the service.

The `Service` in the Traefik chart should allow setting these via `values.yaml` overrides.

Thank you!

**Comment by itamarst** [comment]
More broadly this may be good best practice for all things likely to be hooked up to external cloud loadbalancer.

**Comment by viglesiasce** [comment]
Thanks @itamarst!

cc @krancour the chart maintainer
