### ISSUE TITLE
[stable/jenkins] external backup and restore of job history

### ISSUE THREAD

**Issue by antoniaklja** [helm/charts#3344]
**Is this a request for help?:**
No

**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

Current version of jenkins helm chart doesn't support external backup and restore mechanism for job history (some people use it for apps versioning). 

For temporary solution I have `init-container` running along with `jenkins-master` which backups in some period of time.

```
tar -C /var/jenkins_home -z --exclude jobs/*/config.xml --exclude jobs/*/workspace* --exclude jobs/*/simulation.log -c config-history jobs -f backup
```
then `backup` can be uploaded e.g. to s3 bucket and restored during jenkins startup.

But there are some limitation of this approach.

**Which chart**:
`stable/jenkins`

**Comment by svyotov** [comment]
This might be relevant: https://github.com/artsy/jenkins-backup-s3

**Comment by muehlburger** [comment]
I would vote for this feature. It would be of great interest to have a way to restore the job history. Even on an chart upgrade.

**Comment by antoniaklja** [comment]
@svyotov @muehlburger ok guys, if you want I can make a PR with automated backup and restore in place :)
but the question is - will it be accepted as a solution?
