### ISSUE TITLE
Allow traefik to configure number of replicas

### ISSUE THREAD

**Issue by itamarst** [helm/charts#335]
Without only 1 replica, as hardcoded, upgrading traefik chart results in downtime. 2 or more replicas allows for rolling updates with no downtime.

**Comment by viglesiasce** [comment]
cc @krancour

**Comment by lachie83** [comment]
Looks like this can be done but will require other changes to the chart. 

https://docs.traefik.io/user-guide/cluster/

@itamarst Are you interested in updating the chart to support HA?

**Comment by cknowles** [comment]
@lachie83 is the master election required for this? The config is already shared via ConfigMap. I updated the chart locally and traffic seems to be balancing between the replicas as expected.

**Comment by lachie83** [comment]
@c-knowles I believe so if you don't want to be requesting the same certificate on all replica members.

**Comment by cknowles** [comment]
@lachie83 understood, I may take a look at that once I start to setup Let's Encrypt.

**Comment by krancour** [comment]
This should have been closed by #431

**Comment by seanknox** [comment]
Closing per #431. Feel free to re-open if this is still an issue.
