### ISSUE TITLE
unable to install consul on minikube

### ISSUE THREAD

**Issue by muniyalr** [helm/charts#3362]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Help required

**Version of Helm and Kubernetes**:

Helm version
`Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}`

`kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:15:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}`
**Which chart**:
stable/consul

**What happened**:
pod is in pending state
`my-release-consul-0               1/1       Running   0          5m
my-release-consul-1               0/1       Pending   0          5m`

**What you expected to happen**:

pods in running state

**How to reproduce it** (as minimally and precisely as possible):

`helm install --name my-release stable/consul`

**Anything else we need to know**:
helm ls
NAME          REVISION    UPDATED                     STATUS      CHART           NAMESPACE
my-release    1           Wed Jan 17 16:27:40 2018    DEPLOYED    consul-1.1.2    default

kubectl get pods
NAME                              READY     STATUS    RESTARTS   AGE
my-release-consul-0               1/1       Running   1          10m
my-release-consul-1               0/1       Pending   0          10m

`kubectl logs my-release-consul-0
Waiting for my-release-consul-0.my-release-consul to come up
Waiting for my-release-consul-1.my-release-consul to come up
ping: bad address my-release-consul-1.my-release-consul.default.svc
Waiting for my-release-consul-1.my-release-consul to come up`

Logs suggests that `No nodes are available that match all of the predicates: MatchInterPodAffinity (1).`

Any values needs to be passed when installing the consul chart.  Please advice if I am missing anything with the install of consul.

**Comment by jonstacks** [comment]
Hi @muniyalr,

Can you give me the output of `kubectl get nodes`? My thought is you might not be running enough nodes to schedule the default of 3 replicas with hard anti-affinity. If you want, there are several different ways you could deploy on minikube:

1. Drop the hard anti-affinity setting(which should be used in production) and use soft. This could schedule all of the replicas on the same node.
   
   ```
   helm install --name my-release stable/consul --set antiAffinity=soft
   ```

2. Run a single consul Replica:

   ```
   helm install --name my-release stable/consul --set Replicas=1
   ```

**Comment by muniyalr** [comment]
Thanks @jonstacks with soft antiAffinity i was able to install and test consul
