### ISSUE TITLE
[stable/sentry] add external db support

### ISSUE THREAD

**Issue by jalberto** [helm/charts#3372]
**Is this a request for help?**:
no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
feature request

**Version of Helm and Kubernetes**:
1.7.2 / 1.8.1

**Which chart**:
sentry

**What happened**:
Will like to use an external DB, it just requires a new attribute in `values.yml` and an addition to this line: https://github.com/kubernetes/charts/blob/master/stable/sentry/templates/hooks/db-init.job.yaml#L45

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by jalberto** [comment]
it was more intrusive than I expected, but here is a PR: #3376

**Comment by robdefeo** [comment]
This would be important feature to use sentry :)
