### ISSUE TITLE
[incubator/zookeeper] PV and PVC not removed when chart is deleted

### ISSUE THREAD

**Issue by jar349** [helm/charts#3381]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```
my kubernetes is a minikube, btw, but:
```
$ kl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:15:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: incubator/zookeeper

**What happened**: installed the chart and then deleted it and everything went away except the PersistentVolume and the PersistentVolumeClaim

**What you expected to happen**: The PV and PVC should also have been removed

**How to reproduce it** (as minimally and precisely as possible):
1. install the chart
2. delete the chart

**Anything else we need to know**:

**Comment by ghost** [comment]
We should not destroy data when chart is deleted (even with purge).  Data is precious and charts change, so deleting PVCs should be a very-guarded action.  Deleting PVCs can usually be easily done though with `kubectl delete pvc -l release=$ReleaseName`.
