### ISSUE TITLE
[incubator/kafka] "found invalid field updateStrategy for v1beta1.StatefulSetSpec" on install

### ISSUE THREAD

**Issue by nhjiejan** [helm/charts#3396]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

this is with a plain instal, no options. I have also tried adding more options in the values.yaml file.

**Version of Helm and Kubernetes**:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
[incubator/kafka]

**What happened**:
helm install incuabor/kafka gives the following error:
```
Error: error validating "": error validating data: found invalid field updateStrategy for v1beta1.StatefulSetSpec
```

**What you expected to happen**:
char will install with default config

**How to reproduce it** (as minimally and precisely as possible):
```
$ helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
$ helm install --name my-kafka incubator/kafka
```

**Anything else we need to know**:

**Comment by eicnix** [comment]
You need at least Kubernetes 1.7 to use this Chart. Officially only the current and the last minor version(1.8) is supported.
