### ISSUE TITLE
[stable/redis-ha] PVC possibility was removed, why?

### ISSUE THREAD

**Issue by fiksn** [helm/charts#3403]
By looking at git history I can just see "Removing PVC per PR". It is unclear however what the motivation for this was or what users can do about it. I would like to mount a persistent volume for redis data. So I am tempted to bring back the old commit in my fork, but of course I have to ask first what the motivation for this change on stable was in first place.  

Yes, redis is usually used only as a cache and you don't need persistence. And also if you do, you should store an external .rdb backup or something. Still there are cases where persistent volume might makes sense. (I guess it is unnecessary to dive into the specifics on my use-case here)

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request (I suppose)

**Version of Helm and Kubernetes**:
Helm: Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Kubernetes: Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/redis-ha

**What happened**:
PVC feature was present, but got removed in last version

**What you expected to happen**:
Alternative mentioned in documentation or PVC configuration still existing

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/redis-ha or just looking into values.yaml

**Comment by j-kaplan** [comment]
@fiksn I was wondering this myself and I did some digging and I found this comment on the PR about the switch from statefulset to deployments: https://github.com/kubernetes/charts/pull/2977#discussion_r156799703. Perhaps @ianmaddox can elaborate further, since I'm not entirely clear on the answer myself.

**Comment by Howard3** [comment]
This is critical and would lead to a potential loss of data, as such we're moving back to v1.0.2 until some clarity is made here (https://hub.kubeapps.com/charts/stable/redis-ha/1.0.2)

**Comment by zetaab** [comment]
@ianmaddox so statefulsets was removed because of scaling problems in pod level. I have used statefulsets for a while, and yes that is problem. Lets say that I have 3 pod cluster with statefulset, first pod does not start -> the whole cluster does not start. Do you have any idea is there going to be improve in this? I am hunting solution like Deployment+persistentvolumeclaim for this.

**Comment by zetaab** [comment]
I am thinking that could we use statefulset with https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#parallel-pod-management ? Or what is the main problem here?

Ah the main problem might be relabeling pod labels? What about if we create 3(or x) normal deployments with pvcs? Could that work?

**Comment by pswenson** [comment]
Has anyone come up with a work around for not having PVCs in redis-ha?

I tried going back to v1.0.2 but it didn't seem to work correctly.  The release name environment variable naming scheme conflicted with the image (image assumed no release name prefix).  I resolved that but during my testings scaling the master down to 0 did not result in a slave being promoted to master.....

seems like the path forward is to modify the latest to use PVCs.

**Comment by dradux** [comment]
This is an issue for me as well. Any solutions, workarounds, or ideas?

**Comment by dradux** [comment]
No consolation but my "solution" has been to not use redis-ha and instead use an external redis+sentinel instance where data persistence is required.

**Comment by chainlink** [comment]
Any update on this?

**Comment by RaymondArias** [comment]
pr #4038 makes the pods in a stateful again. While there is no pvc with this pull request I think It would be pretty easy to add the option for a pvc deployment, at least for the redis pod
