### ISSUE TITLE
[stable/concourse] Documented default for concourse.allowSelfSignedCertificates is incorrect

### ISSUE THREAD

**Issue by madmod** [helm/charts#3407]
**Is this a request for help?**:

No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.7.2
Kubernetes 1.8

**Which chart**:
stable/concourse

**What happened**:
The documented default for `concourse.allowSelfSignedCertificates` in `README.md` does not match the actual default in `values.yaml`.

**What you expected to happen**:
The documented default should match the actual default.

**How to reproduce it** (as minimally and precisely as possible):
See [README.md](https://github.com/kubernetes/charts/blame/master/stable/concourse/README.md#L82) (Link is likely to break later because I can't find a way to link to a Markdown source line with a specific commit.) and [values.yaml](https://github.com/kubernetes/charts/blob/1362b960756ed23b91c4192362d052ee86394284/stable/concourse/values.yaml#L154) and note that the values do not match.

**Anything else we need to know**:
I'm unsure what the correct value is, but I would assume that keeping the actual values stable takes priority over keeping the documentation stable.

**Comment by william-tran** [comment]
Thanks, will address in the mega PR #3254
