### ISSUE TITLE
[stable/nginx-ingress] Fix for version 0.10

### ISSUE THREAD

**Issue by Teddy-Schmitz** [helm/charts#3410]
Bug Report

**Version of Helm and Kubernetes**:
Helm 2.50 K8s: 1.8.5

**Which chart**:
stable/nginx-ingress 0.8.26

**What happened**:
Changed image to tag 0.10.0  it then failed to start because the chart set --nginx-configmap instead of --configmap

**What you expected to happen**:
The image to start up properly.

**How to reproduce it** (as minimally and precisely as possible):
Change image tag to 0.10.0

**Anything else we need to know**:
The fix in

https://github.com/kubernetes/charts/commit/e4b2d1e4416bbf3a58a1f532172eaf80874488f0

only checks if the tag contains 0.9.0, now that we are at 0.10.0 this breaks and will for all future versions.  This needs to be changed to some other logic so future versions aren't broken.

**Comment by afirth** [comment]
Resolved by #3462 ?

**Comment by Teddy-Schmitz** [comment]
I havent tested it but i would imagine so, thanks
