### ISSUE TITLE
[stable/fluent-bit] Add more input/filter/output plugin config options support

### ISSUE THREAD

**Issue by louz** [helm/charts#3412]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm: v2.7.2
Kubernetes: 1.8.0

**Which chart**:
stable/fluent-bit

**What happened**:

**What you expected to happen**:
Would like more fluent-bit plugins support, like input(systemd/syslog), filter(enable/disable kubernetes), output(kafka-rest). And more plugin options can be configed, like the DB options in tail/systemd plugin, Refresh_Interval/Mem_Buf_Limit in tail plugin etc. 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
When the 2nd release install, it will fail because of then daemonset name is the same "fluent-bit".

 @kfox1111 @edsiper

**Comment by sagikazarmark** [comment]
I believe a better solution would be to provide a configMapOverrideName option and create a config map manually. That way you can create your own configuration options. It's unrealistic to support all fluent-bit options.

**Comment by louz** [comment]
That's A good idea! But some options should also be configed in daemonset.yaml, for example, when  config the systemd input, it should mount the /run/log dir

**Comment by sagikazarmark** [comment]
Hm, that's true. Those settings probably require an entry in values.yaml. Anyway, see the linked PR.

**Comment by kfox1111** [comment]
is there some 1:1 mapping between yaml and the fluent-bit config file format? It would be really nice if you could just specify the config in the values and dump it into the fluent-bit config file.
