### ISSUE TITLE
[MySQL] Fails to start complaining about a non-empty database dir

### ISSUE THREAD

**Issue by jtgans** [helm/charts#3413]
**Is this a request for help?**:
No.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm: 2.7.2
Kubernetes: 1.8.5 w/ RBAC

**Which chart**:
MySQL v5.7.14

**What happened**:
The pod failed repeatedly with the following error:

```
 Initializing database
2018-01-23T06:35:51.140578Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2018-01-23T06:35:51.147754Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2018-01-23T06:35:51.147838Z 0 [ERROR] Aborting 
```

**What you expected to happen**:
Database initialization and pod to start with no problems.

**How to reproduce it** (as minimally and precisely as possible):
  1. Configure kubernetes with a glusterfs storage cluster using heketi for dynamic provisioning.
  2. Register a storage class for the glusterfs filesystem.
  3. Configure your `values.yaml` to use the storage class.
  4. Install the helm chart using the values.
  5. Note the crashing pod with the above log.

**Anything else we need to know**:

**Comment by qinzhonghe** [comment]
Hi, @jtgans ,I have encountered the same problem,and the steps of recurring are the same.Do you have any suggestions or solutions?

**Comment by antonmarin** [comment]
Hi, @geebytes! You can use initContainer as here. I used arg
```
...
args:
  - "--ignore-db-dir=lost+found"
...
```
