### ISSUE TITLE
[stable/concourse] Allow to set log level env variables

### ISSUE THREAD

**Issue by angelo-v** [helm/charts#3414]
**Version of Helm and Kubernetes**:
Helm 2.7.0
Kubernetes 1.7.11-gke.1

**Which chart**:
stable/concourse

**What happened**:
It is not possible to configure the LOG_LEVEL and CONCOURSE_GARDEN_LOG_LEVEL environment variables to adjust the log level of concourse.

**What you expected to happen**:
It should be able to affect both variables by setting chart values.

**Comment by william-tran** [comment]
Would these be on the web pods? There is already support for setting arbitrary env vars for workers: https://github.com/kubernetes/charts/blob/master/stable/concourse/values.yaml#L415-L417

**Comment by angelo-v** [comment]
Yes you are right! Thanks.
