### ISSUE TITLE
[stable/jenkins] Chart version v0.13.0 Pipeline plugin issue

### ISSUE THREAD

**Issue by wbauern** [helm/charts#3431]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm: v2.7.2
K8s: v1.8.4

**Which chart**:
stable/jenkins v0.13.0

**What happened**:
There are dependency errors loading some plugins.
Pipeline v2.5
Pipeline: Multibranch v2.17 failed to load. Fix this plugin first.
Pipeline: Declarative v1.2.6
Pipeline: Multibranch v2.17 failed to load. Fix this plugin first.
Pipeline: Multibranch v2.17
Pipeline: Job v2.15 is older than required. To fix, install v2.17 or later.

**What you expected to happen**:
The Pipeline plugins to work.

**How to reproduce it** (as minimally and precisely as possible):
helm install --version 0.13.0 stable/jenkins
or
helm install --version 0.13.0 --set Master.ImageTag=latest stable/jenkins

Then go to the Manage Jenkins screen on the Jenkins Dashboard.

**Anything else we need to know**:
I was going to try to update the plugin through the Jenkins Plugin Manager but no plugins show up on the Updates and Available tabs and when I click on the "Check Now" button it gives me the following exception:

java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
Caused: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

**Comment by wbauern** [comment]
Just tried v0.13.1 of the chart and I'm having the same issue.  Anything I should be looking at to get Pipelines working with this chart?

**Comment by bjaworski3** [comment]
I was able to fix this by updating the workflow-job plugin to 2.17 in values.yaml

InstallPlugins:
      - kubernetes:1.1
      - workflow-aggregator:2.5
      **- workflow-job:2.17**
      - credentials-binding:1.13
      - git:3.6.4
