### ISSUE TITLE
RBAC Setup Failed In GKE For stable/etcd-operator

### ISSUE THREAD

**Issue by brockwood** [helm/charts#3432]
**Is this a request for help?**:
Request for help
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm:
```
% helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

Kubernetes:
```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.6-gke.0", GitCommit:"ee9a97661f14ee0b1ca31d6edd30480c89347c79", GitTreeState:"clean", BuildDate:"2018-01-05T03:36:42Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/etcd-operator v0.6.2

**What happened**:
The chart deploys but the etcd operator log is filled with the following:

```
E0124 16:52:05.701961       1 leaderelection.go:224] error retrieving resource lock kube-system/etcd-operator: endpoints "etcd-operator" is forbidden: User "system:serviceaccount:kube-system:etcd-operator-etcd-operator-etcd-operator" cannot get endpoints in the namespace "kube-system": Unknown user "system:serviceaccount:kube-system:etcd-operator-etcd-operator-etcd-operator"
```

**What you expected to happen**:
The etcd-operator should function without error in GKE.

**How to reproduce it** (as minimally and precisely as possible):
1. Create a cluster in GKE with default settings except the following:  Cluster Version is set to 1.8.6-gke.0 and Legacy Authorization is disabled.
2. Once the cluster is up and running, setup kubectl to access the cluster.
3. Once kubectl access is setup, run the following command to setup your account as cluster admin:
```
kubectl --username=admin --password=***** create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=$(gcloud config get-value account)
```
with the password obtained from the Google Kubernetes Web Console __Cluster -> Endpoint -> Show Credentials__

4. Now setup helm:
```
kubectl -n kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account=tiller
```

5. Install the etcd-operator chart:
```
helm install stable/etcd-operator --name my-release
```

**Anything else we need to know**:
When running this with a local minikube v1.8.0 with RBAC enabled, and helm setup as above, the chart works properly.  This seems to only happen in GKE.

**Comment by brockwood** [comment]
cc: @chancez @lachie83 @alejandroEsc

**Comment by alejandroEsc** [comment]
can you add --debug output, specifically that the pertains to rbac, Im not sure i can deploy to gke, but can try to help investigate.
