### ISSUE TITLE
[meta] Publishing charts with an existing upstream here

### ISSUE THREAD

**Issue by yuvipanda** [helm/charts#3434]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Community request!

---

@mattfarina asked me to open this, so I am!

We ([Project Jupyter](http://jupyter.org/)) have a somewhat popular helm chart that is developed at https://github.com/jupyterhub/zero-to-jupyterhub-k8s. That repo contains:

1. Docs (released at https://z2jh.jupyter.org)
2. A helm chart
3. Images to be built
4. (Some) code for images to be built (see https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/master/images/pre-puller for example)

We also have a good number of contributors, and it operates pretty well under the existing Project Jupyter umbrella community.

Currently we make releases of our chart every few months, and people use those from our repo at http://jupyterhub.github.io/helm-chart. We also build and push charts + images at every commit to http://jupyterhub.github.io/helm-chart for people who wanna live on the edge.

We would love to also be in this repo for the following reasons:

1. Better visibility, allows users to install easier
2. Forces us to follow best practices, and accept contributions from the wider helm community

However, there is not too much overlap between the Helm community and Jupyter communites, and us sending people directly here might be confusing and overwhelming. Plus, I don't think this repo wants to host our docs + images + (some) code. 

How would we possibly go about doing this? The first thought that comes to mind is we just publish our charts here for every point release we make, rather than every commit. That way, the images and docs don't need to be here. However, this causes the problem of 'how to accept contributions to the chart here', since any contribution might already be fixed upstream, or the patch might not apply cleanly anymore. Issues raised here might also be lost, since not as many Jupyter folks would be watching this as the upstream repo.

I am sure we won't be the only community with this sortof situation, so would love to hear y'all's thoughts on this!

**Comment by munnerz** [comment]
I'm maintaining [cert-manager](https://github.com/jetstack/cert-manager) and have a similar requirement.

We maintain our own Helm chart, which is actually used as part of our end-to-end test suite. As a result, I've opted to not make changes to our chart downstream (i.e. in this repository) in favour of making them upstream in cert-manager before manually copying and creating a pull request to get the changes downstream. This can be tedious and result in some back-and-forth as my PRs go through review in kubernetes/charts.

I've considered making some kind of a periodic CI task that automatically publishes changes to the chart, if detected, to `stable/charts`. I'm not sure if there are any other existing charts that have a similar requirement?

**Comment by unguiculus** [comment]
Maybe we could add an additional field to Chart.yaml that denotes whether a chart is maintained upstream. CI could check this field and close PRs with a comment directing folks to the upstream repo.

@mattfarina Can this be done with Prow?
