### ISSUE TITLE
[stable/traefik] Extra ACME options for Traefik chart

### ISSUE THREAD

**Issue by DirkWolthuis** [helm/charts#3437]
**Is this a ~~BUG REPORT~~ or **FEATURE REQUEST**?** 

**Version of Helm and Kubernetes**:
Helm: v2.7.2
Kubernetes: v1.9.1
Traefik: 1.5.0

**Which chart**:
/stable/traefik/

**What happened**:
Let's Encrypt throws a error when getting the certs for my domains. The error is:

```
Error getting ACME certificates [lb.ikbendirk.nl] : cannot obtain certificates map[lb.ikbendirk.nl:[lb.ikbendirk.nl] acme: Could not determine solvers]
```

This is described in issue [#2681](https://github.com/containous/traefik/issues/2691) of Traefik. 
**What you expected to happen**:
The solution to this problem, that is caused by a change by Let's Encrypt, is described in PR [#2701](https://github.com/containous/traefik/pull/2701) in the Traefik repo. To make auto certificates via Let's Encrypt work again, we need to set a setting in the .toml config file that is generated by Helm. 

```
[acme.httpChallenge]
entryPoint = "http"
```

This option is not settable with the current option that the chart provides

**How to reproduce it** (as minimally and precisely as possible):
Using the versions as describe above, and setting the ACME options to true in de values.yml used by helm to deploy traefik. 

**Anything else we need to know**:

**Comment by ramontayag** [comment]
See https://github.com/kubernetes/charts/pull/3347
