### ISSUE TITLE
Redis fails to run on minikube with error on access permission to a PVC

### ISSUE THREAD

**Issue by leopoldodonnell** [helm/charts#3441]
`minikube` is an important tool. Stable charts should work 'out of the box' or provide documentation on how to run on this platform.

Steps to reproduce:

Using chart stable/redis version 1.1.9

```bash
$ helm install stable/redis --name my-redis
NAME:   redis
LAST DEPLOYED: Thu Jan 25 09:37:31 2018
NAMESPACE: default
STATUS: DEPLOYED
...
$ 
```
A quick look via the dashboard or from `kubectl` will reveal that the `redis` pod is stuck in `crashLoopBackOff`.

Taking a closer look at the logs we see:

```
$ kubectl logs redis-redis-74cb746d9f-gc27v

Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing redis
redis   INFO  ==> Validating inputs...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis'
```

**Comment by muniyalr** [comment]
@sameersbn Is this related to the same issue https://github.com/bitnami/bitnami-docker-redis/issues/87

which you had provided a fix
```
+      initContainers:
+      - name: "fix-permissions"
+        image: "busybox"
+        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
+        command: ["sh", "-c", "chown -R 1001:1001 /bitnami"]
+        volumeMounts:
+        - name: redis-data
+          mountPath: /bitnami
```

and we have to wait for the upstream - fix 
https://github.com/kubernetes/minikube/issues/1990

**Comment by krancour** [comment]
@leopoldodonnell, this appears to be a know issue with minikube itself: https://github.com/kubernetes/minikube/issues/1990

**Comment by leopoldodonnell** [comment]
I’ll check this out ASAP - would there be any objection to adding a note to
the chart’s Readme in a PR if this proves to be the case?

**Comment by leopoldodonnell** [comment]
Submitted a PR that provides a Note to minikube users. For the time being, avoid pvc's or engineer redis to run as root.
