### ISSUE TITLE
[stable/rabbitmq-ha] file not found

### ISSUE THREAD

**Issue by TacticalSlothmaster** [helm/charts#3444]
I can't install stable/rabbitmq-ha. Is it not available anymore?
Executing the command:

> $ helm install stable/rabbitmq-ha

leads to: 

> Error: file "stable/rabbitmq-ha" not found

I installed stable/rabbitmq with helm before and now I want to switch to stable/rabbitmq-ha

**Comment by nawaitesidah** [comment]
Update your repo before installing it

`helm repo update`
