### ISSUE TITLE
[stable/traefik] externalTrafficPolicy should be customizable

### ISSUE THREAD

**Issue by krancour** [helm/charts#3458]
This is meant to complement #3215 

#3215 adds support for PROXY protocol. When an L4 load balancer and the Traefik ingress controller mutually agree to use PROXY protocol, the end user's IP address becomes available to Traefik and can be captured in access logs.

The above is quite applicable to AWS ELBs, for instance. On other cloud platforms, however (GKE and Azure), L4 load balancers only forward packets. Since no source NATing is performed, packets arrive at Kubernetes nodes with the original source IP intact / unaltered. In a case such as this, PROXY protocol is _not_ needed to make the source IP accurately reflect the end user IP...

However, kube-proxy _does_ perform source NATing. To stop this from happening, the `Service` managed by this chart should have a customizable / overridable `externalTrafficPolicy`. When set to `local`, this will force all nodes _not_ hosting one or more Traefik pods to deliberately fail the health check that the load balancer performs. This will effectively eliminate the scenario where inbound traffic might flow through a kube-proxy. That, in turn, will guarantee no source NATing is performed, which in turn, guarantees preservation of the source IP.

**Comment by timstoop** [comment]
I've been looking at this and thinking it over. Is there any reason to not set this by default to `local` on all clusters?

**Comment by krancour** [comment]
> Is there any reason to not set this by default to local on all clusters?

It would change existing behavior. Without this set, there are certainly a large number of users who see internal IPs in their access logs and in `X-Forwarded-For` headers in the HTTP requests arriving to their applications. While seeing internal IPs in those scenarios seems like it's less useful than seeing the real end-user IPs, we cannot discount the possibility that some people expect or rely on the existing behavior. i.e. Changing it represents a breaking change.

So I do believe the right thing to do is put this behind a feature flag.

**Comment by santinoncs** [comment]
Hi!
I am using traefik's chart and also I need the externalTrafficPolicy parameter set to local.
IMHO, Why you just don't set the default value and do it customizable. 
Maybe this is the thing you want to do...

thx!!

**Comment by timstoop** [comment]
Took me a bit longer than expected (busy busy busy) but here it is.
