### ISSUE TITLE
redis-ha sentinel.conf not writeable

### ISSUE THREAD

**Issue by madhakish** [helm/charts#3464]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm client v2.7.2
OpenShift Origin 3.6

**Which chart**:
stable/redis-ha

**What happened**:
Sentinel pods fail with the following error:
59:X 26 Jan 19:42:36.481 # Sentinel config file /etc/redis/sentinel.conf is not writable: Permission denied. Exiting...

**What you expected to happen**:
Expect /etc/redis/sentinel.conf to be writeable by the sentinel process. This is mandatory for sentinel to operate correctly. Sentinel processes update this config according to cluster change events.

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/redis-ha --namespace <your_namespace> --tiller-namespace <tiller_namespace> --name <your_redis_name>

**Anything else we need to know**:
This may be a result of an ill-configured Dockerfile or default permissions in the quay.io/smile/redis:v4.0.6r2 image

I'll be retrying with a different docker image of my own build and Dockerfile, but this should fixed in the upstream redis image most likely.

**Comment by roychri** [comment]
@madhakish Which version of the chart are you using? I have been using this chart since 2.0.0 and I have not experienced this problem. Could it be related to OpenShift or maybe some configuration of your cluster? Disclaimer: I know nothing of OpenShift

**Comment by SLionB** [comment]
same problem with
quay.io/smile/redis:4.0.8r0
and
quay.io/smile/redis:latest

**Comment by andersflemmen** [comment]
@SLionB Have you tried this?
https://docs.openshift.com/enterprise/3.2/admin_guide/manage_scc.html#enable-dockerhub-images-that-require-root

**Comment by SLionB** [comment]
@andersflemmen 
Adding the service account to the anyuid did the trick !
