### ISSUE TITLE
[stable/jenkins] no plugins installed after deploy 

### ISSUE THREAD

**Issue by dolv** [helm/charts#3468]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.9", GitCommit:"19fe91923d584c30bd6db5c5a21e9f0d5f742de8", GitTreeState:"clean", BuildDate:"2017-10-19T16:55:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}

**Which chart**:
[stable/jenkins]

**What happened**:
no plugins installed after deploy 

**What you expected to happen**:
we expected the following list of plugins be automatically installed. 
this is extract from values.yaml
\# List of plugins to be install during Jenkins master start
  InstallPlugins:
    - kubernetes:1.1
    - workflow-aggregator:2.5
    - workflow-job:2.15
    - credentials-binding:1.13
    - git:3.6.4
    - greenballs
    - pipeline-stage-view
    - extended-choice-parameter
    - uno-choice
    - workflow-aggregator
    - pipeline-utility-steps
    - ws-cleanup
    - windows-azure-storage
    - thinBackup
    - slack
    - skype-notifier
    - show-build-parameters
    - role-strategy
    - rebuild
    - nodelabelparameter
    - nexus-artifact-uploader
    - maven-artifact-choicelistprovider
    - mask-passwords
    - kubernetes
    - jira-steps
    - envinject
    - docker-slaves
    - docker-plugin
    - categorized-view
    - build-pipeline-plugin
    - bitbucket
    - ansicolor
    - active-directory
**How to reproduce it** (as minimally and precisely as possible):
helm upgrade --install jenkins -f ./jenkins-chart-values.yaml stable/jenkins
log in to jenkins; go to manage jenkins-> manage plugins-> installed.
there you'll see message "No plugins installed"

**Anything else we need to know**:

**Comment by sloooomo** [comment]
@dolv I am having the same issue. Were you able to figure anything out, or waiting on a response?

**Comment by dolv** [comment]
Hi, my name is Oleksandr actually :)
No, I tried to look into their scripts but was lack of time. Thus I'm
waiting for the response.
All in All the chart choud be reviewed and corrected. The issue is in
value.yaml where the script itself described.

30 січ. 2018 р. 19:43 "jbounds83" <notifications@github.com> пише:

**Comment by blaw2422** [comment]
I was having the same problem.  I logged into the node running the init container and was able to look at the logs.  I was having problems with my network downloading the plugins.  Not sure if this would help, but the init container will still be on the node for a little while. 

Maybe go try looking at the logs for it.
