### ISSUE TITLE
OpenVPN running on custom cluster

### ISSUE THREAD

**Issue by dbogatov** [helm/charts#3471]
**Is this a request for help?**:

Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

**Version of Helm and Kubernetes**:

Kubernetes 1.9.1
Helm 2.8.0

**Which chart**:

openvpn

**What happened**:

I followed README instructions.
Two things went wrong:

- Volume issue `Unable to mount volumes for pod`.
I guess it is because a volume has to be created manually in advance (am I right?).
If yes, it should be clearly stated in docs (preferably with an example command to create such volume).
If no, it is a clear bug.
Anyway, flag `--set persistence.enabled=false` fixed the issue, but persistence is still important to me.

- Service is forever in pending state.
I guess it is because I am not using AWS or GKE which have their own load balancers, so my services do not get external IPs.
Still, documentation should clearly say what I need to do in this case.
Maybe, ingresses or manual check for IP?

**What you expected to happen**:

Follows from the previous sections.
I expected a working OpenVPN installation right after `helm install` command.

**How to reproduce it** (as minimally and precisely as possible):

Have a custom cluster.
I created mine using [Typhon](https://typhoon.psdn.io) for DigitalOcean.
Follow RAEDME instructions.

**Anything else we need to know**:

I am pretty new to Kubernetes, so forgive me for possibly silly questions.

**Comment by kriptontr** [comment]
same problem here. I know LoadBalancer service type is for cloud providers. But how to act when working with custom clusters ?

**Comment by lvthillo** [comment]
Same question. Tried to start it with type NodePort but I'm not able to get further
