### ISSUE TITLE
All Bitnami charts require the use of a LoadBalancer service, and don't support Ingresses

### ISSUE THREAD

**Issue by kminehart** [helm/charts#3479]
**BUG REPORT**

**Version of Helm and Kubernetes**:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-gke.0", GitCommit:"2c2a807131fa8708abc92f3513fe167126c8cce5", GitTreeState:"clean", BuildDate:"2017-12-19T20:05:45Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Helm:

```
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

**Which chart**:

Pretty much all Bitnami charts. Phabricator, Ghost, Odoo...

**What happened**:

I use [nginx-ingress-controller](https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress) combined with [kube-lego](https://github.com/kubernetes/charts/tree/master/stable/kube-lego) for free automatically renewed SSL certificates.

This requires using an Ingress to expose a service externally.

Bitnami charts expect you to use a LoadBalancer service to expose the service. If you try to use an ingress, the application tries to build links using `127.0.0.1`.

Example with Ghost can be seen here, where `Latest Posts` at the bottom links to `http://127.0.0.1`.

https://blog.runecms.io/

**What you expected to happen**:

I expect charts to have the ability to be exposed via. Ingresses, especially for HTTPS.  HTTPS / Let's Encrypt on `ServiceType: LoadBalancer` is an unbelievable pain, and since almost all of these services have authentication of some kind, I expect HTTPS to be used.

**How to reproduce it** (as minimally and precisely as possible):

Just use the default `values.yaml`, set `serviceType` to `ClusterIP` and expose it via. an ingress resource; the links won't be right.

**Anything else we need to know**:

**Comment by kminehart** [comment]
Actually that's not true. Ghost includes that setting in its values.yaml, can't believe I missed it.  I did have issues with Phabricator though.

**Comment by ghost** [comment]
@kminehart I'm not seeing ingress in Ghost `values.yaml`.. .Did it get PR'ed out? https://github.com/kubernetes/charts/blob/master/stable/ghost/values.yaml

I'm all for flexibility to create ingress myself, but I think charts should be idiomatic about it.  By that I mean that they should practice the patterns set forth by `helm create`. 

If you agree, please reopen this.

**Comment by kminehart** [comment]
I created the ingress myself. The issue was that things like phabricator and I think odoo don't let you configure the external URL, so if you use an ingress with tls, all of the links on the app will be broken.
