### ISSUE TITLE
Docker-registry chart in both Stable and Incubator repos

### ISSUE THREAD

**Issue by cten** [helm/charts#3488]
While searching through charts at the commandline I noticed that the 'docker-registry' chart is listed in both the stable and incubator repos. The APP VERSIONs are the same but the CHART VERSIONs differ. Maybe whomever promoted it to stable forgot to remove it from the incubator repo, it doesn't exist in the incubator directory on github. 

Thanks

**Comment by rwenz3l** [comment]
Maybe that's because the older versions are still being tracked for helm. It's kinda useful, since the nodeport is broken and the "stable" registry does not work, but the old incubator version does.
