### ISSUE TITLE
[stable/prometheus] vague error on upgrade "unrecognized type: string"

### ISSUE THREAD

**Issue by jalberto** [helm/charts#3496]
**Is this a request for help?**:
no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

**Version of Helm and Kubernetes**:
1.7.2 / 1.8.1

**Which chart**:
prometheus

**What happened**:
on upgrade got this error:

`Error: UPGRADE FAILED: unrecognized type: string`

**What you expected to happen**:

clean upgrade

**How to reproduce it** (as minimally and precisely as possible):

try to upgrade an already installed prometheus

**Anything else we need to know**:

**Comment by icecream2368** [comment]
try: helm upgrade -f values.yaml <your-release-name> /<local-path-to-repo>/charts/stable/prometheus ?

**Comment by jalberto** [comment]
solved, was a typo in my values.yaml

still the error is too vague, a line number and filename will be great (I
know is on helm not this chart)
