### ISSUE TITLE
Elastalert chart references unmaintained docker image

### ISSUE THREAD

**Issue by jlk** [helm/charts#3503]
Preface on the below - I'm not sure if maybe there's a reason the chart is referencing the image mentioned below. I know I can override and will be testing something more modern this week.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Which chart**:
stable/elastalert

**What happened**:
This chart is currently using quay.io/pickledrick/elastalert:
```
image:
  # docker image
  repository: quay.io/pickledrick/elastalert
  # docker image tag
  tag: stable
```
pickledrick/elastalert hasn't been updated since November 17, 2017, and it's source repo claims it's no longer supported. The upstream `github.com/Yelp/elastalert` has had 20+ merges since then.

**What you expected to happen**:
Use a more up-to-date repo like https://hub.docker.com/r/bitsensor/elastalert/

**Comment by jlk** [comment]
cc @pickledrick 

I'm happy to send a PR on this after testing...

**Comment by poidag-zz** [comment]
@jlk happy for it to go back to to original, I forked and tagged 'stable' as a requirement to get this PR through. I can't fully remember why but I think it's because this tag didn't exist at the time.

**Comment by jlk** [comment]
Aaah...yeah that makes sense.

**Comment by jlk** [comment]
Will ponder this for a day or so and update or close.

**Comment by jlk** [comment]
I [asked](https://github.com/Yelp/elastalert/issues/1535) the yelp/elastalert folks to see if they'd maintain an "official" image. Will see if it goes anywhere...
