### ISSUE TITLE
[stable/cert-manager] make the README more helpful

### ISSUE THREAD

**Issue by jeff-knurek** [helm/charts#3513]
the `cert-manager` chart's README could use some improvement
https://github.com/kubernetes/charts/blob/master/stable/cert-manager/README.md

* the install/uninstall doesn't mention the chart name, so doesn't actually work as described (_unless of course someone pulls the chart repo and `cd`'s into this directory, but no other chart expects that in their install/uninstall descriptions so it'd be better to be consistent_)
* the `tl/dr` and `introduction` sections are a bit redundant 
* but **most importantly**, the details here about configuring are much more relevant and helpful than anything else in this README: https://github.com/jetstack/cert-manager/blob/master/docs/user-guides/deploying.md#addendum
Maybe it's better to link to this doc from the the helm README, so not creating two locations to maintain. I guess that's a decision for @munnerz who wrote both

**Comment by munnerz** [comment]
I've opened https://github.com/jetstack/cert-manager/pull/290 upstream to resolve this.
Namely:

* I've added some notes to the README that link to how to set up an issuer, as well as configuring ingress-shim
* I've included those same notes as part of the NOTES.txt too
* Removed 'tl;dr' and introduction sections from README
* Updated chart name so we don't advise `helm install .`
