### ISSUE TITLE
Chart Prometheus Node exporter enable collector fail

### ISSUE THREAD

**Issue by ghost** [helm/charts#3519]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Which chart**:
Prometheus node exporter

**What happened**:
Node exporter fail to enable a collector that is disabled by default.

**What you expected to happen**:

Node exporter has enabled by default some collector and add the posibility to enable the other collector over a flag passed to the exporter command, for example:

docker run --rm -ti prom/node-exporter:v0.15.2 **--collector.mountstats** enable the collector **mountstats** that is disabled by default **and work as expected**.

In the prometheus node exporter chart this flag **DOES NOT WORK** because the daemonset definition are WRONG: **https://github.com/kubernetes/charts/blob/master/stable/prometheus/templates/node-exporter-daemonset.yaml**

In values .yaml of prometheus chart you can pass the flag to node exporter in the directive extraArgs: {}
but the definition of the flags are wrong:

 **{{- range $key, $value := .Values.nodeExporter.extraArgs }}**
  **- --{{ $key }}={{ $value }}**

The above produce as a result for example **collector=mountstats** and are a wrong flag that produce the exit of the container with crashloopback error.

**How to reproduce it** (as minimally and precisely as possible):

Modify the values.yaml of prometheus chart and add a custom value to extraArgs of Node Exporter.

Please, fix it!

**Comment by djsly** [comment]
the problems started when the node_exporter moved from `-collectors.enabled=[]` to boolean flags.
e.g.
```
--collector.systemd
```
the kingpin lib doesn't like `=` sign for boolean args.
so both
```
--collector.systemd=
--collector.systemd=true
```
will result in an error
`node_exporter: error: unexpected true , try --help`

The chart template logic needs to be updated

**Comment by charlspjohn** [comment]
--no-collector.systemd worked for me
