### ISSUE TITLE
[stable/buildkite] ERROR: mkdir /buildkite: read-only file system

### ISSUE THREAD

**Issue by nhamidjaja** [helm/charts#3526]
**Version of Helm and Kubernetes**:

```
$ helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-gke.0", GitCommit:"2c2a807131fa8708abc92f3513fe167126c8cce5", GitTreeState:"clean", BuildDate:"2017-12-19T20:05:45Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/buildkite

happens to both:
buildkite-agent v2.6.9
buildkite-agent v3.0

**What happened**:

```
$ docker-compose -f docker-compose.yml -p buildkite553dae3879b24dc6beabd5e2521ee974 run api ./.buildkite/run_tests.sh
...
ERROR: Cannot start service api: error while creating mount source path '/buildkite/builds/bk-agent-buildkite-7bbdfd46-psrln/...': mkdir /buildkite: read-only file system
```

**What you expected to happen**:

Should be able to execute test script.

**How to reproduce it** (as minimally and precisely as possible):

```
$ helm install stable/buildkite --name bk-agent --namespace buildkite \
  --set agent.token="$(cat buildkite.token)",agent.meta="role=production",privateSshKey="$(cat buildkite.key)"
```

Run a buildkite job

**Anything else we need to know**:

I've tried installing without the ssh key:

```
$ helm install stable/buildkite --name bk-agent --namespace buildkite \
  --set agent.token="$(cat buildkite.token)"
```

And then manually setting the ssh key in the pod via bash. This method was successful.

**Comment by arikkfir** [comment]
Happens to us too, in builds using the BuildKite docker plugin (normal steps run fine inside the agent pod).
We're using the v3 agent.

**Comment by torbjornvatn** [comment]
Same here when using the `docker-compose` plugin. 
I also tried adding the ssh key manually as @nigorice did, but it still fails

**Comment by lox** [comment]
The issue is that `/buildkite` doesn't exist on the host system, but buildkite-agent is using the host's docker socket. 

See https://github.com/buildkite/agent/issues/729#issuecomment-381397937 for more details.
