### ISSUE TITLE
Make it possible to collect cadvisor stats from /metrics/cadvisor in 1.8+

### ISSUE THREAD

**Issue by janssk1** [helm/charts#3547]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes 1.8.3 and helm 2.7.2

**Which chart**:
prometheus

**What happened**:
Container statistics (CPU/network/..) are not available in prometheus

**What you expected to happen**:
Container stats should be available irrespective of how cadvisor is configured on KS1.8+. 

**How to reproduce it** (as minimally and precisely as possible):
Install kubernetes 'securely' by disabling the cadvisor unsecured port. This is the recommended way these days (more info on that: https://github.com/kubernetes/kubernetes/issues/53615). 
Now, prometheus does not find stats, although they are still available at /metrics/cadvisor

**Anything else we need to know**:
The correct fix for this is already mentioned in the comments of https://github.com/kubernetes/charts/pull/2700

**Comment by mcwienczek** [comment]
Perhaps fixed by #3684?

**Comment by gyliu513** [comment]
+1 to @mcanevet , I think this has been fixed in #3684
