### ISSUE TITLE
Postgres password secret regenerated on upgrade but not updated in postgres server

### ISSUE THREAD

**Issue by alexjg** [helm/charts#362]
Not specifying the password for the postgres password secret causes a random alphanumeric value to be generated for the password, this works fine the first time the chart is installed but when the chart is run again (in my case as part of a `helm upgrade` of a chart depending on the postgres chart) the secret is regenerated but not updated in the postgres DB, making it impossible to log in using the secret. Setting a password in `Values.postgresPassword` fixes the issue.

This looks like it's because the `POSTGRES_PASSWORD` environment variable is only used by the postgres container to set the password if the data directory has not been created (i.e the container is starting up for the first time) see https://github.com/docker-library/postgres/blob/a00e979002aaa80840d58a5f8cc541342e06788f/9.6/docker-entrypoint.sh#L40

**Comment by pierreozoux** [comment]
Hitting the same issue.

Yes indeed, the `POSTGRES_PASSWORD` is only used the first time.
But this is not the issue, we should find a way to not rerun the `rand` in every upgrade.
I'd say it is a bug, and we should find a solution.

This way, it is not usable, and then, we shouldn't use rand at all.

**Comment by seanknox** [comment]
Hey folks, is this still an issue?

**Comment by sstarcher** [comment]
It's still an issue.

It's pretty much a problem for every chart that generates a secret.  https://github.com/kubernetes/charts/blob/89f291797efeeb8668da0007a04871611555de04/stable/postgresql/templates/secrets.yaml#L15

**Comment by kojiDev** [comment]
No solution so far? PostgreSQL Chart is unusable.

**Comment by iczman** [comment]
Just bumped into this as well.

**Comment by JuergenSimon** [comment]
Same here. This is messed up for sure. Please fix!
