### ISSUE TITLE
 traefik vs ngnix-lego

### ISSUE THREAD

**Issue by wclr** [helm/charts#363]
If I get it correct those two chart are supposed to solve the same problem, can someone give a comment on pros and cons using one versus another? I think this would be valuable to place this info in the charts's docs.

**Comment by pierreozoux** [comment]
I'd say that nginx is more battle tested than traefik as a load balancer.

**Comment by pierreozoux** [comment]
@whitecolor Can we close the issue? (Just to keep it clean :) )

**Comment by wclr** [comment]
Ok, I just thought that it could be mentioned in docs of both things.
