### ISSUE TITLE
rabbitmq charts don't expose STOMP port

### ISSUE THREAD

**Issue by ryandawsonuk** [helm/charts#3653]
We'd like to be able to use the rabbitmq and rabbitmq-ha charts with the STOMP plugin enabled. To do that we would need the 61613 port available in the service and the deployment. We can do this using a deployment descriptor (https://github.com/Activiti/activiti-cloud-examples/blob/c44263b006c748999bb54297cdff12506b8a0c2b/kubernetes/aws-deployment/infrastructure/templates/infrastructure.yml#L334) but we want to use the official helm chart.

The official rabbitmq charts don't seem to make any option available for this:

https://github.com/kubernetes/charts/blob/master/stable/rabbitmq-ha/templates/service.yaml#L27
https://github.com/kubernetes/charts/blob/master/stable/rabbitmq-ha/templates/service.yaml#L36

(note epmd is not related to stomp and normally runs on a different port - https://www.rabbitmq.com/networking.html#selinux-ports)

In the case of the rabbitmq chart I think it's necessary to override the image to enable the stomp plugin. With rabbitmq-ha I'm not sure (https://github.com/kubernetes/charts/blob/master/stable/rabbitmq-ha/templates/configmap.yaml#L13) but either way we'll need that port exposed - the rabbitmq-ha doesn't simply work out of the box (we've tried that and the port is indeed not available).

Is there a different path available or would it be best to add this to the chart?

**Comment by etiennetremel** [comment]
Hi @ryandawsonuk, what's about adding conditions to enable mqtt and stomp plugins independently and expose the following ports on the service:

- rabbitmqSTOMPPlugin.enable=true, rabbitmqSTOMPPlugin.ports=[61613, 61614]
- rabbitmqWebSTOMPPlugin.enable=true, rabbitmqWebSTOMPPlugin.port=15674
- rabbitmqMQTTPlugin.enable=true, rabbitmqMQTTPlugin.ports=[1883, 8883]
- rabbitmqWebMQTTPlugin.enable=true, rabbitmqWebMQTTPlugin.port=15675

other thought?

**Comment by yurrriq** [comment]
@etiennetremel, that would work for me. I specifically need Web STOMP.

**Comment by ryandawsonuk** [comment]
Sounds good to me too

**Comment by yurrriq** [comment]
As far as I'm concerned, this issue is not fully resolved. #3759 only updates the HA chart. I'd like similar support in the non-HA chart too. **Edit**: Thanks for HA chart update though. That looks great.

**Comment by tryhardest** [comment]
Hi @etiennetremel @yurrriq we are trying to expose port 15674 from Rancher but it's not working for rabbitmqWebSTOMPPlugin.enable=true, rabbitmqWebSTOMPPlugin.port=15674

May I kindly ask how you guys did it? We just can't get the port to open.

**Comment by yurrriq** [comment]
I use the HA chart these days, which works great.

**Comment by ryandawsonuk** [comment]
Yeah I used the HA too
