### ISSUE TITLE
NOTES.txt commands for printing passwords not working with kubectl 1.5.1

### ISSUE THREAD

**Issue by prydonius** [helm/charts#366]
```
$ echo $(printf $(printf '\%o' `kubectl get secret --namespace wp solemn-narwhal-redis -o jsonpath="{.data.redis-password[*]}"`))
error: error executing jsonpath "{.data.redis-password[*]}": string is not array or slice
zsh: bad math expression: operand expected at end of string
zsh: bad floating point constant
zsh: bad math expression: operand expected at end of string
zsh: bad math expression: operand expected at end of string
zsh: bad math expression: illegal character: {
zsh: bad math expression: operand expected at end of string
zsh: bad math expression: operator expected at `interface'
zsh: bad math expression: illegal character: {
zsh: bad math expression: illegal character: {
zsh: bad math expression: illegal character: {
zsh: bad math expression: illegal character: {
```

Firstly, kubectl now complains about using `[*]` for strings and secondly the base64 encoded secret now gets returned so it needs to be decoded. For example:

```
echo $(kubectl get secret --namespace wp solemn-narwhal-redis -o jsonpath="{.data.redis-password}" | base64 --decode)
```

Kubectl version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-22T13:59:22Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

cc @viglesiasce @lachie83

**Comment by pwittrock** [comment]
cc @kubernetes/sig-cli-misc

**Comment by viglesiasce** [comment]
@pwittrock Is this a bug or a feature? Any recommendations on how to work around it in the short term?

**Comment by pwittrock** [comment]
@viglesiasce I am not sure, need to dig into it a bit more.  At a glance, this seems like something that should not have broken, and should have at least been clear in the 1.5 release notes.

**Comment by pwittrock** [comment]
Looks like a workaround maybe posted in the issue (don't use [*] and decode the base 64)

**Comment by viglesiasce** [comment]
@pwittrock issue is that we want a way to support both 1.4 and 1.5 clusters.

**Comment by pwittrock** [comment]
Is this an issue with the client or the server?  Do we get the old behavior with a 1.4 client and 1.5 server?

**Comment by mengqiy** [comment]
@prydonius Does `kubectl` support `[*]` for strings in 1.4?

**Comment by viglesiasce** [comment]
@yifan-gu yes these instructions (NOTES.txt) worked in the 1.4 release.

**Comment by viglesiasce** [comment]
@pwittrock Downgrading kubectl to 1.4.x fixed it for me

**Comment by pwittrock** [comment]
Is there a link to NOTES.txt?

**Comment by pwittrock** [comment]
@ymqytw Would you file an issue for this in the main repo?

**Comment by viglesiasce** [comment]
Here is the one from the redis chart:
https://github.com/kubernetes/charts/blob/master/stable/redis/templates/NOTES.txt

**Comment by mengqiy** [comment]
Created kubernetes/kubernetes#39500

**Comment by pwittrock** [comment]
Thx

**Comment by iamzhout** [comment]
Per my test on [stable/mysql chart](https://github.com/kubernetes/charts/tree/master/stable/mysql), kubectl v1.4.8 will not complain about the jsonpath, and the result is decimal chars as below,
```
v1.4.8 >kubernetes/client/bin/kubectl get secret filled-otter-mysql -o jsonpath="{.data.mysql-root-password[*]}"
118 54 81 107 104 68 116 113 56 118%
```

while for kubectl v1.5.2, it will report error.

**Comment by iamzhout** [comment]
I suspect the problem is caused by different go version used to compile code.
k8s 1.4.x uses go1.6.3 to do compilation, while k8s 1.5.x uses go1.7.4.

and there do have some changes on golang for template processing on Oct 19, 2016, by commit [5378dd](https://github.com/golang/go/commit/5378dd77684e2eee5f05aab4b77497bb635fd544), there are some changes on template processing, maybe have some relation on this issue. (Though have not checked the logic further)
```
...
 func (t *Template) execute(wr io.Writer, data interface{}) (err error) {
        defer errRecover(&err)
-       value := reflect.ValueOf(data)
+       value, ok := data.(reflect.Value)
+       if !ok {
+               value = reflect.ValueOf(data)
+       }
...
```

**Comment by seanknox** [comment]
Hey folks, is this still an issue? I haven't seen this problem in awhile.

**Comment by mengqiy** [comment]
If this issue is verified to have been fixed by golang, we can close this issue.
