### ISSUE TITLE
[incubator/cassandra] cassandra cannot be upgraded from 0.2.0 to 0.2.1

### ISSUE THREAD

**Issue by galuszkak** [helm/charts#3672]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** 

BUG REPORT

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
incubator/cassandra

**What happened**:
I cannot upgrade cassandra via helm.
```
$ helm upgrade cassandra-prod incubator/cassandra
Error: UPGRADE FAILED: StatefulSet.apps "cassandra-prod-cassandra" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```

**What you expected to happen**:
I expect to have working upgrade of cassandra via helm.

**How to reproduce it** (as minimally and precisely as possible):
Install cassandra chart version 0.2.0 and try to upgrade to 0.2.1

**Comment by cscetbon** [comment]
Same issue here. The sample command provided in the documentation simply doesn't work :

```
helm upgrade --set config.cluster_size=4 cluster1 cassandra
Error: UPGRADE FAILED: StatefulSet.apps "cluster1-cassandra" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```

**Comment by cscetbon** [comment]
I found that the only way to make the upgrade works is by using `--reuse-values` even if they don't change. Tiller is supposed to compare the old chart version and the new one, which should be the same even if I don't use `--reuse-values` as I didn't change anything except the one that I pass to the command.

**Comment by sumsuns** [comment]
was this resolved? .. i have similar issue with upgrade with the chart version change .. if the version is same and image is updated locally  it works.. but not chart version change

**Comment by sumsuns** [comment]
@galuszkak : I am struggling to make it happen . did you find a solution ?
