### ISSUE TITLE
[stable/concourse] Add support for loadBalancerIP

### ISSUE THREAD

**Issue by wanderanimrod** [helm/charts#3682]
**FEATURE REQUEST**

**Which chart**:
`stable/concourse`

**Description**:
The chart already allows the user to set `web.service.type: LoadBalancer`. However, it does not allow the user to specify the `web.service.loadBalancerIP` setting. 

**Use case**
This setting is useful for cases where the user already has a static IP they want to assign to concourse web. 

If this is not a deliberate choice, I would like to add that feature. 

Please let me know if I should submit a PR to this effect.

**Comment by william-tran** [comment]
@wanderanimrod I'm happy to approve a PR for this, I don't think that's a deliberate choice.
