### ISSUE TITLE
RabbitMQ does not allow specifying config file

### ISSUE THREAD

**Issue by Nopik** [helm/charts#3706]
Currently the only way to replace default RMQ config file is to manually copy the file to the mounted directory. If, however, the chart would allow mounting specified file as configmap (e.g. as specified here: https://github.com/kubernetes/kubernetes/issues/44815#issuecomment-297077509), it would be possible to use config map and all its goodies (e.g. value expansion).

**Comment by etiennetremel** [comment]
If you use th rabbitmq-ha chart, it does allow you to create your own configmap:
https://github.com/kubernetes/charts/blob/master/stable/rabbitmq-ha/values.yaml#L114

Which could be used to inject definitions similar to this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-release-rabbitmq-ha
data:
  enabled_plugins: |
    [rabbitmq_consistent_hash_exchange,rabbitmq_federation,rabbitmq_federation_management,rabbitmq_management,rabbitmq_mqtt,rabbitmq_peer_discovery_k8s,rabbitmq_shovel,rabbitmq_shovel_management,rabbitmq_stomp,rabbitmq_web_stomp,rabbitmq_delayed_message_exchange].
  rabbitmq.conf: |
    # ....
    management.load_definitions = /etc/rabbitmq/definitions.json
  definitions.json: |
    {
      "permissions": [],
      "users": [],
      "policies: []
    }
```

**Comment by marcoskichel** [comment]
This don't actually works.

I get this error:
`Error: release condohub failed: configmaps "condohub-rabbitmq-ha" already exists`

**Comment by techdragon** [comment]
/remove-lifecycle stale 

If its supported, then it should at least be documented how to use it. At the moment that file merely has a spot for saying `true` or `false` for an existing configmap. Without documentation how to use this and, in an ideal world, an example of using it to specify a user, a vhost and some permissions for the user+vhost combination, this remains a major stumbling block for potential new users.

**Comment by yurrriq** [comment]
@techdragon, agreed.

@marcoskichel, you need to set `existingConfigMap: true` as well, so the chart doesn’t try to create one.

**Comment by yurrriq** [comment]
IMO this issue ought to be closed.
