### ISSUE TITLE
RabbitMQ does not allow specifying enabled plugins

### ISSUE THREAD

**Issue by Nopik** [helm/charts#3707]
It would be great if the RabbitMQ chart would allow specifying the list of enabled plugins, so manual filesystem modifications wouldn't be necessary.

**Comment by etiennetremel** [comment]
Hi @Nopik, which of the RabbitMQ chart are you referring to? If this is about the rabbitmq-ha, we could add conditions as I mentioned on this comment: https://github.com/kubernetes/charts/issues/3653#issuecomment-366076754

Maybe improve this type of configuration to be like:

```
## LDAP Plugin
## Ref: http://www.rabbitmq.com/ldap.html
rabbitmqLDAPPlugin:
  enabled: false

  ## LDAP configuration:
  # config: 
  #   auth_backends.1 = ldap
  #   auth_backends.2 = internal
```

What do you think?

**Comment by Nopik** [comment]
It seems that `rabbitmq.plugins` value appeared recently, which solves the problem. Closing this issue.
