### ISSUE TITLE
Wordpress chart on bare metal

### ISSUE THREAD

**Issue by nordri** [helm/charts#372]
Hello,

I'm trying to install stable/wordpress chart in a bare metal installation of kubernetes and I'm getting this message:

`19s        5s        3    {kubelet minion1}   Warning        FailedSync    Error syncing pod, skipping: failed to "StartContainer" for "exasperated-quokka-wordp" with RunContainerError: GenerateRunContainerOptions: secrets \"exasperated-quokka-maria\" not found"`

I configure persistence as false and service type as Node port. 

Those are the available secrets:

```NAME                       TYPE                                  DATA      AGE
default-token-ecxnm        kubernetes.io/service-account-token   3         14d
exasperated-quokka-wordp   Opaque                                2         18h
jittery-fly-secret         Opaque                                2         14d
masked-shrimp-secret       Opaque                                2         14d
mewing-narwhal-secret      Opaque                                2         14d
```

There is no mariadb secrets because there is no mariadb charts installed. I thought charts dependencies should be included, doesn't it?

Am I missing something?

I followed the kubernetes start guide with ubuntu xenial and kubeadm with flannel network overlay. It is a quite standard installation of Kubernetes.

**Comment by prydonius** [comment]
Hey @nordri, if you're installing from a local directory, you need to run `helm dep update ./wordpress` to fetch the MariaDB dependency. You should then be able to run `helm upgrade exasperated-quokka ./wordpress` or delete and re-deploy to fix your issue.
