### ISSUE TITLE
[stable/cluster-autoscaler] fix defaults to pass CI tests

### ISSUE THREAD

**Issue by prydonius** [helm/charts#3724]
For a next rev (v1.0.0), the provider should be unset and the chart should show users how to set it appropriately via NOTES without applying the deployment.

cc @viglesiasce @mgoodness 

EDIT: we will now configure the autodiscovery by default which should allow the controller to start up successfully.

**Comment by afirth** [comment]
Will it be possible to pass the pull-charts-e2e test with this change? What's the advantage?

**Comment by prydonius** [comment]
I think that was the idea @afirth, but your PR is a better solution.
