### ISSUE TITLE
[stable/concourse] PR #2983 may have broken deployment on k8s version 1.6

### ISSUE THREAD

**Issue by jammm** [helm/charts#3761]
Context:

In the PR https://github.com/kubernetes/charts/pull/2983, this change was made: https://github.com/kubernetes/charts/pull/2983/commits/f660448745e48607f3f4f47e016cb16c90cfaeb3

This caused deployment of this chart to be unstable for kubernetes 1.6. The error message is:
`Error: error validating "": error validating data: found invalid field podManagementPolicy for v1beta1.StatefulSetSpec`

`v1beta1.StatefulSetSpec` doesn't support podManagementPolicy.

**Comment by william-tran** [comment]
Thanks @jammm for the report, @unguiculus you had suggested to remove the conditional in this comment https://github.com/kubernetes/charts/pull/2983#discussion_r157244764, and I see that charts should be compatible with the current and previous version: https://github.com/kubernetes/charts#supported-kubernetes-versions. Should charts strive to drop support for older-than-previous versions?
