### ISSUE TITLE
[stable/kube-state-metrics] 

### ISSUE THREAD

**Issue by bbzg** [helm/charts#3771]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm v2.8.1 Kubernetes 1.8.6

**Which chart**:
stable/kube-state-metrics

**Feature request**:
kube-state-metrics is deployed to the `default` namespace - it would be nice to be able to specify which namespace it is deployed into, to avoid polluting the default namespace.

(There is an undocumented namespace flag in the chart, but that one is for managing which namespace kube-state-metrics monitors, not where it is deployed)

Thank you!

**Comment by eicnix** [comment]
Helm allows you to specify a namespace during the chart installation: `helm install kube-state-metrics --namespace my-namespace`.

**Comment by bbzg** [comment]
Hi! Thanks for the suggestion.

That works for single-namespace deployments, but I am unfortunately using kube-state-metrics as a sub-chart in a more complex deployment that deploys to multiple namespaces.
