### ISSUE TITLE
[stable/sonatype-nexus] image repository deprecated

### ISSUE THREAD

**Issue by bcg62** [helm/charts#3782]
image repository `clearent/nexus` is deprecated and needs to be updated to `cavemandaveman/nexus` 

most recent tag is `3.8.0-02`

https://github.com/cavemandaveman/nexus/pull/7

**Comment by CMYanko** [comment]
is there a reason not to use the official image?

**Comment by feluxe** [comment]
I managed to get this chart running with the [official image](https://hub.docker.com/r/sonatype/nexus3/).

Git clone this chart and add this to `templates/deployment.yaml` under `template: > spec: `

      securityContext:
        fsGroup: 2000

Comment out `livenessProbe` and `readinessProbe` sections (also in `templates/deployment.yaml`)

Then you can change the imagename in `values.yaml` to `sonatype/nexus3` and install via helm.

**Comment by cilindrox** [comment]
@feluxe you can use the `nexus.securityContext` value too, eg: `--set nexus.securityContext=2000`

**Comment by rjkernick** [comment]
Image has been migrated from that repo
/close
