### ISSUE TITLE
[stable/elasticsearch-exporter] Add annotation to pod and service spec

### ISSUE THREAD

**Issue by olemarkus** [helm/charts#3786]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE

The prometheus chart defines some handy annotations for discovering scrape targets. It would be really useful to be able to add these annotations to resources created by this chart.

**Which chart**:
stable/elasticsearch-exporter

**What happened**:
Not able to add annotations to resources created by this 

**What you expected to happen**:
Be able to add annotations, especially the prometheus.io annotations

**Comment by davidkarlsen** [comment]
@olemarkus you can use service.annotations for this.
