### ISSUE TITLE
Rabbitmq HA custom configmap issue

### ISSUE THREAD

**Issue by abdul-basith-git** [helm/charts#3847]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 
Helm version: 2.8.1
Kubectl client version: v1.10.0-alpha.1
Kubectl server version: v1.8.6

**Which chart**: stable/rabbitmq-ha

**What happened**: I am using custom configmap with a parent/child chart relationship. I am defining the name of the chart in Chart.yaml to be "custom-rabbitmq". When I run a helm install dry-run, under the volumes section of stateful set, the configmap refers to the child chart name rather than the parent one. So when I run a helm install, the deployment fails. The configmap name in volumes should refer to the parent chart rather than the child one. Only when I rename the parent chart to 'rabbitmq', the deployment works.

**What you expected to happen**: Helm install/deployment to work with a custom configmap.

**How to reproduce it** (as minimally and precisely as possible):
Create a folder with Chart.yaml, values.yaml and requirements.yaml. Have rabbitmq-ha as the name of the dependency in requirements.yaml. Run the chart using 'helm install'.

**Anything else we need to know**: None

Please pardon me if this issue is already resolved - in that case, could you please point me in the right direction. Thanks.

**Comment by marcoskichel** [comment]
I am facing the exact same issue, any workaround?

**Comment by estahn** [comment]
The only workaround I came up with was naming the parent chart `rabbitmq-ha`.

The issue is here: https://github.com/kubernetes/charts/blob/master/stable/rabbitmq-ha/templates/statefulset.yaml#L176

**Comment by abdul-basith-git** [comment]
Thanks @estahn 

@marcoskichel : Workaround proposed by Enrico above is good for now. Otherwise worse case, you can extract the rabbitmq-ha chart, not have the parent-child relationship, rather edit the rabbitmq-ha chart directly to fit your preferences (as said, only in the worst case).

**Comment by estahn** [comment]
A possible fix would be to add a variable like `customConfigMapChartName` to `values.yaml` which will need to be set in the parent chart.
