### ISSUE TITLE
How to handle failover on incubator/redis-cache

### ISSUE THREAD

**Issue by ArchiFleKs** [helm/charts#3849]
**Is this a request for help?**:

Yes

**Version of Helm and Kubernetes**:

2.8.1

**Which chart**:

incubator/redis-cache

**What happened**:

When deploying redis-cache, you get a statefulset, for example with 3 Redis server, and a Kubernetes service headless, so you have for example redis-0,1,2. 

Then a master gets elected, for exemple the 0. The problem is that the slave do not accept writes, so if you use the service, you get randomly redirected to a master or a slave and slave does not accept writes. If you specified the FQDN of the master (redis-0.redis.default.local)  it is alright. 

But I'm wondering how do you handle Master failover ? Is this something you do on the application level ? By specifying an array of redis server ? 

Is there a way for the slave to redirect the write to the master. I don't really know redis and I'd like to know the proper way to handle this. Without having to modify config each time the master changes for any reason.

Thanks.

**Comment by yinzara** [comment]
If you know that your stateful set will always have 3 nodes and they will be named:
redis-0.redis
redis-1.redis
redis-2.redis

You can configure your application to use RedisCluster instead of Redis and specify all 3 hosts.  That will allow it gracefully handle changes.
