### ISSUE TITLE
nginx-lego: kube-lego doesn't work

### ISSUE THREAD

**Issue by mgoodness** [helm/charts#385]
Due to an [upstream bug](https://github.com/jetstack/kube-lego/issues/78), setting `lego.enabled` in the `nginx-lego` chart does not result in the retrieval & application of SSL certs. Currently the only fix would be to hard-code the kube-lego pods' `app` label to `kube-lego`.

Kinda related, I propose splitting the kube-lego functionality into its own chart, possibly with this one as a dependency. Even if that's not done (but especially if it is), I think this chart would be more appropriately named `nginx-ingress` or something similar. Doesn't seem right to have `lego` in the name when it's optional functionality.

I was actually going to submit a PR with other changes (labels, health checks, flexible config), but will hold off pending discussion of the above topics.

@jackzampolin @prydonius @viglesiasce

**Comment by jackzampolin** [comment]
@mgoodness I've got this running in a personal cluster and I'm not running into this. As far as splitting the chart into two, I think that would be a more appropriate way to handle the potential dependancy.

Thank you for taking some time to work on that.

**Comment by mgoodness** [comment]
@jackzampolin I just installed it again into an otherwise completely fresh & empty cluster and no dice.

Is it possible you have kube-lego running elsewhere in your cluster, and that's what is handling cert retrieval? If you're willing, run `kubectl describe ing kube-lego-nginx` in each of your namespaces. That's the Ingress that kube-lego creates to handle the ACME challenge for every other Ingress.

In my case there's only one, and it returns:
```
Name:			kube-lego-nginx
Namespace:		default
Address:		10.150.20.170
Default backend:	default-http-backend:80 (<none>)
Rules:
  Host				Path	Backends
  ----				----	--------
  k8s-dashboard.test.yden.us
    				/.well-known/acme-challenge 	kube-lego-nginx:8080 (<none>)
```
As you can see, it wants to route the ACME challenge to the service that kube-lego automatically creates (`kube-lego-nginx`), _not_ the service that Helm created (`flabby-quetzal-nginx-leg-lego`). But `kube-lego-nginx` has no endpoints because the selector doesn't match my pods:
```
⟩ kubectl get ep kube-lego-nginx
NAME              ENDPOINTS   AGE
kube-lego-nginx   <none>      38m

⟩ kubectl describe svc kube-lego-nginx
Name:			kube-lego-nginx
Namespace:		default
Labels:			<none>
Selector:		app=kube-lego

⟩ kubectl describe po flabby-quetzal-nginx-leg-lego-1725604974-cdn0x
Name:		flabby-quetzal-nginx-leg-lego-1725604974-cdn0x
Namespace:	default
Node:		ip-10-150-20-170.ec2.internal/10.150.20.170
Start Time:	Wed, 11 Jan 2017 19:03:51 -0600
Labels:		app=flabby-quetzal-nginx-leg-lego
		pod-template-hash=1725604974
```
The ACME challenge is never answered, so I never get any certs from LetsEncrypt.

Not sure how this could be working in a cluster that doesn't also have a non-Helm deployed instance of kube-lego running.

**Comment by jackzampolin** [comment]
@mgoodness Thank you for explaining that.

Sounds like we could change the `spec.selector.app` in the `lego-service.yaml` from `{{ template "fullname . }}-lego` to `kube-lego` or change the name `spec.template.metadata.labels.app` in `lego-deployment.yaml` to `kube-lego`?

Do you see tradeoffs with either of these solutions?

**Comment by jackzampolin** [comment]
@mgoodness Got it working (responding to `/.well-known/acme-challenge/_selftest` without modification) by removing the `lego-service.yaml` file and changing the `spec.selector.app` in `lego-deployment.yaml` to `kube-lego`.

I'll put it up in a PR.

**Comment by mgoodness** [comment]
@jackzampolin I think that (setting `app: kube-lego`) is the best solution unless/until it's addressed upstream.
