### ISSUE TITLE
Problems with "helm.sh/created" annotation

### ISSUE THREAD

**Issue by unguiculus** [helm/charts#386]
It is quite common to use an annotation "helm.sh/created" that stores a timestamp. This is problematic because resources are updated even if no change was made when you run "helm upgrade". However, some resource types do not allow updates or only to specific fields, e. g. StatefulSets.

One example is `incubator/mongodb-replicaset` (
[incubator/mongodb-replicaset/templates/mongodb-petset.yaml#L58](https://github.com/kubernetes/charts/blob/master/incubator/mongodb-replicaset/templates/mongodb-petset.yaml#L58)). I installed it successfully. I then made changes to the ConfigMap containing the mongod.conf and tried to upgrade the chart. The result was this:

> Error: UPGRADE FAILED: StatefulSet.apps "mongo-mongodb-replicaset" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas' are forbidden.

The only thing that I had changed was the ConfigMap. The docs state that Helm only updates things that have changed since the last release. The ConfigMap was actually updated correctly even though the above error was the only output. While the Helm output is not ideal (https://github.com/kubernetes/helm/issues/1781). I'd suggest to not use timestamped values. I don't see why this is useful anyways. How about having `helm lint`check for this?

**Comment by viglesiasce** [comment]
Thanks for this @unguiculus!!

I think you are right that the annotation is not providing any obvious value. 

@prydonius, @lachie83  what do you think? Do you know where that pattern came from? What is its origin?

**Comment by lachie83** [comment]
@viglesiasce I can be safely removed. It's from Helm Classic.

**Comment by unguiculus** [comment]
Created PR #425.
