### ISSUE TITLE
Dependency is not getting resolved while using with Helm install

### ISSUE THREAD

**Issue by ymallipe** [helm/charts#3875]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Serv
![kakfa_chart](https://user-images.githubusercontent.com/5363603/36669898-80a19054-1b1c-11e8-89f0-f6962c865c6c.PNG)
er: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

**Which chart**:
incubator/kafka

**What happened**:
Installing using below command say missing charts in requirements.yaml
helm install --name myzk incubator/kafka
Error: found in requirements.yaml, but missing in charts/ directory: zookeeper, schema-registry

**What you expected to happen**:
Install Kafka with Zookeeper dependency charts.

**How to reproduce it** (as minimally and precisely as possible):
Installed GKE and using Helm tarball, Added repo executed kafka charts.

**Anything else we need to know**:
NA

**Comment by JMLizano** [comment]
Hi, 

I think this isn't bug, but one of the following scenarios:

1.  You are trying to install the kafka chart from source code, instead from the release in the helm repo. If you want to this you have to run 'helm dependency update kafka' before installing.

2. You added the repo as stated in the README.md and you are trying to install from it, but since you are in /charts dir, helm first evaluates 'incubator/kafka' to the local source code directory, and thus failing for the same reason as 1. In this case you should try installing from another directory.

**Comment by dove-young** [comment]
I got the same error when I tried to add one more sub-chart to a Helm chart


It says `Error: found in requirements.yaml, but missing in charts/ directory: local-volume-provisioner`, but this directory does exist and contains the sub-chart there. 

```
helm version --tls
Client: &version.Version{SemVer:"v2.7.3", GitCommit:"27442e4cfd324d8f82f935fe0b7b492994d4c289", GitTreeState:"dirty"}
Server: &version.Version{SemVer:"v2.7.3", GitCommit:"27442e4cfd324d8f82f935fe0b7b492994d4c289", GitTreeState:"dirty"}
```


```
[root@test ]# ls
additionalFiles  david.install.log  README.md          templates             values.yaml
charts           LICENSE            requirements.lock  test.values.yaml
Chart.yaml       LICENSES           requirements.yaml  values-metadata.yaml
[root@test]# ls charts/local-volume-provisioner/
charts  Chart.yaml  local-storage-class.yaml  provisional_local_ssd_volumes.yaml  templates
[root@test]# helm install --debug . --tls -n test --values /tmp/test.values.yaml
[debug] Created tunnel using local port: '36996'

[debug] SERVER: "127.0.0.1:36996"

[debug] Original chart version: ""
[debug] Key="/root/.helm/key.pem", Cert="/root/.helm/cert.pem", CA="/root/.helm/ca.pem"

[debug] CHART PATH: /root/charts/test

Error: found in requirements.yaml, but missing in charts/ directory: local-volume-provisioner
[root@test ]#
```
