### ISSUE TITLE
Possible Bucket Squatting Vulnerability?

### ISSUE THREAD

**Issue by osterman** [helm/charts#391]
## what
* This bucket has not been claimed, which means it's available for the taking
* A person with malicious intent could capitalize on someone like me who tried to use that bucket and it didn't exist to serve charts with backdoors

```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist.</Message>
</Error>
```

## why
* The advertised incubator bucket is:  https://kubernetes-charts-incubator.storage.googleapis.com/  (per the `README.md`)
*  A reasonable person might assume the stable bucket for Kubernetes charts is: https://kubernetes-charts-stable.storage.googleapis.com/; I believe this is essentially the same as `<bucket-name>.s3.amazonaws.com`, which is a public object storage service (s3)

## suggestion
* Do not advertise/promote direct bucket names in a *public* namespace
* Use trusted hostnames; e.g.  `incubator.charts.kubernetes.io`

**Comment by viglesiasce** [comment]
Thanks @osterman!! I'll dig in with the folks that own the kubernetes.io domain and see if we can fix this.
