### ISSUE TITLE
RabbitMQ HA Chart SSL Issue

### ISSUE THREAD

**Issue by iherbmatt** [helm/charts#3915]
Hello,

Is there an easy way to implementing SSL/amqps on the rabbitmq ha chart? I was able to do so with the console by itself, but I was unable to configure amqps for use on port 5671. This appears to cause instability in the application resulting in pod errors and crash loops.

Any thoughts?

Thank you,

Matt

**Comment by laghoule** [comment]
Check pull request [#3944](https://github.com/kubernetes/charts/pull/3944)

**Comment by laghoule** [comment]
pull request [#3944](https://github.com/kubernetes/charts/pull/3944) now merge in master.
