### ISSUE TITLE
[stable/traefik] add optional path for dashboard

### ISSUE THREAD

**Issue by moneydance** [helm/charts#3919]
It would be nice if we could specify a path on the domain to access the dashboard. I attempted to modify the chart but I'm new at kubernetes helm and traefik so didn't have much luck. 

if my domain is:

    example.com

it would be nice if the dashboard could be accessed at

    example.com/traefik/dashboard/#/

a value could be specified like so

    dashboard:
      domain: example.com
      path: /traefik

I know the ingress itself supports path and the web backend has a path variable as well
https://docs.traefik.io/configuration/backends/web/#path

I can submit a PR if someone gives me some guidance.

**Comment by ferrarimarco** [comment]
@moneydance one way could be what grafana chart is doing: https://github.com/kubernetes/charts/blob/master/stable/grafana/templates/ingress.yaml
