### ISSUE TITLE
grafana version pinning

### ISSUE THREAD

**Issue by kfox1111** [helm/charts#3926]
The chart for grafana uses the :latest tag. They just started tagging their 5.x beta's as :latest in the repo and it has breaking changes around the dashboard importing.

The chart should pin back to 4.x until the chart supports 5.x, and should bump the chart major version then, as it will be upgrade incompatible at that time.

**Comment by sstarcher** [comment]
Looks like it's pinned - https://github.com/kubernetes/charts/blob/master/stable/grafana/values.yaml#L9
