### ISSUE TITLE
[Prometheus] Non official image used

### ISSUE THREAD

**Issue by alexppg** [helm/charts#3932]
**Is this a request for help?**: No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Which chart**:
Prometheus

**What happened**:
The image for the configmapReload is a non-standard one (it points to [this image](https://hub.docker.com/r/jimmidyson/configmap-reload/)). I don't think it's apropiate to use an image from a personal docker repository. There's a some precedences showing is not a good idea to do this, the biggest one is the one about [leaf-pad and NPM](https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/).

**What you expected to happen**:
This image should be pushed to some official repository.

**Comment by gadelkareem** [comment]
there should also be a way to disable it if we dont need it
