### ISSUE TITLE
Proposal: Enable testing and linting charts with test values.

### ISSUE THREAD

**Issue by unguiculus** [helm/charts#3943]
Currently, we can only test charts with their default values. There are certain cases when this is not ideal:

* Charts cannot use the `required` function without providing a default value.
* Some charts need key files (e. g. #3220). Adding keys to the chart is a security risk, even if we document that the user is supposed to provide their own keys. In such a case we could create keys for the tests only. for a real installation the user would be required to specify their own.

I propose that a chart can have a `ci` folder. Any file in this folder that ends with `-values.yaml` is considered a values file for testing. Linting and tests are run with each of these files. If no test values are found, the chart is installed with defaults.

Here's some bash code that illustrates this.

```bash
#!/usr/bin/env bash

shopt -s nullglob
has_test_values=

for values_file in ./ci/*-values.yaml; do
    echo "Testing chart with values file: $values_file..."

    helm lint stable/mychart --values "$values_file"
    helm install stable/mychart --values "$values_file"
    has_test_values=true
done

if [[ -z "$has_test_values" ]]; then
    echo "Chart does not provide test values. Testing installation with defaults..."

    helm lint stable/mychart
    helm install stable/mychart
fi
```

**Comment by prydonius** [comment]
+1 from me

**Comment by sameersbn** [comment]
sgtm!

**Comment by jpoon** [comment]
Having this ability would be awesome. I've been hesitant/lazy to update https://github.com/kubernetes/charts/pull/3220 to pass the tests as it would mean updating all the start-up scripts to include "if no keys included, NOP" which is such an ugly hack to get around requiring keys.

**Comment by viglesiasce** [comment]
This is awesome! +1 from me.
