### ISSUE TITLE
Mariadb upgrade fails on chart version change 

### ISSUE THREAD

**Issue by sumsuns** [helm/charts#3982]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm - v2.8.1
kuberentes - "v1.8.3"

**Which chart**:
mariadb 
https://github.com/openstack/openstack-helm/tree/master/mariadb

**What happened**:
upgrade of the mariadb with the chart version change fails

**What you expected to happen**:
upgrade should happen successfully .. pods should be restarted .. and new image should be reflected

**How to reproduce it** (as minimally and precisely as possible):
install previoius version of mariadb  and upgrade to new version of maria db .

**Anything else we need to know**:
 i have the mariadb new image checked in and using it in new chart. 

$ sdiff -s -w 80 <(helm get bilging-donkey --revision 1 ) <(helm get bilging-donkey --revision 5 )
REVISION: 1                           | REVISION: 5
RELEASED: Mon Mar  5 14:09:31 2018    | RELEASED: Mon Mar  5 14:13:56 2018
CHART: cmdb-2.4.3-17.12               | CHART: cmdb-2.4.4-17.12
imageTag: 17.12-1.194                 | imageTag: 17.12-2.201
    chart: "cmdb-2.4.3-17.12"         |     chart: "cmdb-2.4.4-17.12"
    chart: "cmdb-2.4.3-17.12"         |     chart: "cmdb-2.4.4-17.12"
    chart: "cmdb-2.4.3-17.12"         |     chart: "cmdb-2.4.4-17.12"
    chart: "cmdb-2.4.3-17.12"         |     chart: "cmdb-2.4.4-17.12"
        image: "csf-docker-delivered. |         image: "csf-docker-delivered.
        image: "csf-docker-delivered. |         image: "csf-docker-delivered.
       chart: "cmdb-2.4.3-17.12"      |        chart: "cmdb-2.4.4-17.12"

**Comment by bacongobbler** [comment]
Sorry @sumsuns, I redirected you to the wrong ticket queue. I did not realize this was an issue with openstack's mariadb chart rather than the community's mariadb chart.

Because it's from openstack-helm, you should probably follow up at https://github.com/openstack/openstack-helm on their launchpad: https://bugs.launchpad.net/openstack-helm
