### ISSUE TITLE
[incubator/chartmuseum] is disabling the API a poor default?

### ISSUE THREAD

**Issue by krancour** [helm/charts#3993]
I was initially very confused at why the following command for uploading a chart didn't work:

```
$ curl --data-binary "@foo-0.1.0.tgz" http://($mk ip):32392/api/charts
```

It took a few minutes of investigation to determine that the API was disabled by default.

I want to humbly propose that default values should be optimized for naive, but curious users who are kicking the tires for the first time and that disabling the API by default isn't something such a user would intuitively expect.

@jdolitsky, any thoughts on this? I do realize this would be a BC, but this chart is also still in incubator status. Does that give it license to make BCs?

/assign jdolitsky

**Comment by jdolitsky** [comment]
@krancour this actually came up today. The solution we came up was to put this in bold in the README: https://github.com/kubernetes/charts/pull/3987

**Comment by krancour** [comment]
@jdolitsky got it.

From the PR:

> This protects against unauthorized access to the API with default configuration values.

Knowing now that the default is based on a more-secure-by-default approach, the decision makes sense. Thanks.

Big +1 from me on putting this detail in bold!

/close
