### ISSUE TITLE
Setup a contrib charts repo

### ISSUE THREAD

**Issue by prydonius** [helm/charts#40]
As discussed previously (in charts chats and Helm developer calls), we'd like to setup a separate GitHub and Chart repository for charts that may not meet the bar for this repository. These could include charts that are:
- Examples for new features, ideas
- Scaffolds that may require editing the chart templates to get started
- Using alpha Kubernetes features, or third-party extensions

/cc @erictune @viglesiasce @michelleN

**Comment by prydonius** [comment]
There are currently a few charts awaiting review that would need to be moved to this new repository: #37 and #38 (using PetSets).

**Comment by erictune** [comment]
Contrib implies to me that someone wrote it and contributed it and that was the end.   This sometimes happens with "contrib" directories on other projects.

Can we pick a name which implies that there is an intent to continue to grow and support the thing?

The name "incubator" would match the apache incubator model and the [kubernetes incubator model](https://github.com/kubernetes/community/blob/master/incubator.md).
Alternatively, the name "alpha" would correspond to the fact that it includes alpha features, and the kubernetes [alpha/beta/stable levels](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api_changes.md#alpha-beta-and-stable-versions)

**Comment by viglesiasce** [comment]
Closing this as we now have an incubator directory.
