### ISSUE TITLE
CustomConfigMap option yields error with override_config_map missing

### ISSUE THREAD

**Issue by sellers** [helm/charts#4040]
**Is this a request for help?**: Yes?

---

**Version of Helm and Kubernetes**: 1.8

**Which chart**: jenkins

**What happened**: config_map_override did not override based on docs

**What you expected to happen**: override of configmap created

**How to reproduce it** (as minimally and precisely as possible): following https://github.com/kubernetes/charts/blob/master/stable/jenkins/README.md#custom-configmap
* create a templates dir
* copy the config.yaml file into the templates dir as config.tpl
* run helm

**Anything else we need to know**:

The results are:

```
+ helm install --name jenkins-xxx stable/jenkins -f ./jenkins-values.yaml -f xxx/jenkins-values.xxx.yaml --namespace kangaroo
Error: render error in "jenkins/templates/jenkins-master-deployment.yaml": template: jenkins/templates/jenkins-master-deployment.yaml:26:28: executing "jenkins/templates/jenkins-master-deployment.yaml" at <include (print $.Tem...>: error calling include: template: jenkins/templates/config.yaml:182:3: executing "jenkins/templates/config.yaml" at <include "override_co...>: error calling include: template: no template "override_config_map" associated with template "gotpl"
```

**Comment by EamonKeane** [comment]
Did you wrap the config.tpl with define as shown below?

`{{- define "override_config_map" }}
   "Config.yaml content"
{{ end }}`

**Comment by noreilly** [comment]
The reason for this looks to be that the public distribution repo (https://kubernetes-charts.storage.googleapis.com/) is behind the github source.

jenkins-0.9.4.tgz appears to be the latest but it does not include these lines at end of config.yaml.

`
{{ else }}
{{ include "override_config_map" . }}
{{- end -}}
`
Adding these locally appears to make it work

**Comment by fdlk** [comment]
It helped me to run `helm lint my-chart` to figure out how many brackets I needed.
It's
```
{{- define "override_config_map" }}
apiVersion: v1
kind: ConfigMap
[...]
  plugins.txt: |-
{{- if .Values.Master.InstallPlugins }}
{{- range $index, $val := .Values.Master.InstallPlugins }}
{{ $val | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
```
