### ISSUE TITLE
Postgresql deleting of lost+found looks dodgy

### ISSUE THREAD

**Issue by wstrange** [helm/charts#405]
@swordbeta  @databus23 

The postgresql  init container removes the lost+found directory:

"rm", "-fr", "/var/lib/postgresql/data/pgdata/lost+found"

Is this really necessary for proper operation of postgres? 

This seems like it could *possibly* be detrimental to data integrity on the host file system. (It looks like fsck will recreate it, so this may not be a huge deal, but I have never seen the need to delete this directory)

**Comment by wstrange** [comment]
Somewhat relevant discussion at: http://postgresql.nabble.com/Ignore-lost-found-when-checking-if-a-directory-is-empty-td4683343.html 

" Better practice is to make a postgres-owned directory just  underneath the mount point."

**Comment by databus23** [comment]
@wstrange Yeah I thought so too when I saw it. The problem with changing it now is that it can break exiting users of this chart when suddenly postgres expects the `PGDATA` in a subdirectory of their exiting PVCs.

**Comment by wstrange** [comment]
I think the semantic version of the of the chart would need to be bumped due to the breaking change. 

The possible data loss scenario that could happen:   Host comes up and fsck's the file system, and there is data corruption, so it moves the files into lost+found.  Then the container starts up, and blows those recovered files away.

**Comment by viglesiasce** [comment]
We have a PR for this over in #416

**Comment by ravishivt** [comment]
#416 was merged.  This can probably be closed.
