### ISSUE TITLE
Installing stable/owncloud fails

### ISSUE THREAD

**Issue by jason-riddle** [helm/charts#406]
Just tried to use the owncloud chart and it fails with the following.

```bash
$ helm install stable/owncloud
Error: release nonexistent-owl failed: Deployment.extensions "nonexistent-owl-mariadb" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
```

**Comment by jason-riddle** [comment]
Looks like the problem lies with the mariadb deployment file.

https://github.com/kubernetes/charts/blob/master/stable/mariadb/templates/deployment.yaml#L21

```
"imagePullPolicy": {{ .Values.imagePullPolicy | quote }},
```

I'm a little confused because I already tried running this

```
helm install \
    --set imagePullPolicy=Always stable/owncloud
```

which fails as well so I guess the `imagePullPolicy` for Mariadb has to be set another way?

**Comment by sameersbn** [comment]
@jason-riddle Can you apply the changes from #417 and confirm if it resolves the issue for you? Your confirmation will help land the changes faster.

**Comment by jason-riddle** [comment]
Sorry, probably won't be able to look at this until the weekend.
