### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by jason-riddle** [helm/charts#407]
I tried to install a chart with the following command.

```bash
$ helm install stable/owncloud
```

and it failed. I opened up a separate issue for this (#406) and it would be nice to have some tests to catch an issue like this.

**Comment by jason-riddle** [comment]
Ah sorry, didn't see there were tests already available. However, it doesn't look like there is a test that covers actually just trying to install a chart.

**Comment by viglesiasce** [comment]
Hey @jason-riddle!

We have some very very generic tests that run on PRs and will be working over the next few months to add more specific per chart tests. We will be leveraging the `helm test` work:
https://github.com/kubernetes/helm/pull/1777

With @foxish we are looking at ways to do continous testing against various versions of Kubernetes which would have caught this issue early on.

**Comment by seanknox** [comment]
Closing due to suggestions from Vic. Feel free to re-open if needed.
