### ISSUE TITLE
[stable/traefik] Allow configuration of defaultEntryPoints

### ISSUE THREAD

**Issue by Luciam91** [helm/charts#4099]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature Request

**Version of Helm and Kubernetes**:

**Which chart**:
`stable/traefik`

**What happened**:

**What you expected to happen**:

When using Traefik as the ingress to route traffic we need to be able to manage WebSockets as well to backend services, my understanding (and this could be off) is that for this to be the case the `defaultEntryPoint` needs to include `ws, wss` in the `traefik.toml` file (Reference: https://github.com/containous/traefik/issues/1327).

This could either be done as an extension of the current `if...else` block, simply adding `ws` or `wss` where required, but it would be more extensible if this was configurable by the end-user, with defaults matching the current provided template.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by rememe** [comment]
Still not resolved, we need to use web sockets! ;)
