### ISSUE TITLE
[stable/nginx-ingress] Validate externalTrafficPolicy/controller.kind

### ISSUE THREAD

**Issue by mausch** [helm/charts#4112]
**Is this a request for help?**: YES

**Version of Helm and Kubernetes**:
Helm 2.8.1
Kubernetes 1.8.6

**Which chart**: stable/nginx-ingress

**What happened**: 

I installed this chart with:
* controller.service.externalTrafficPolicy=Local
* controller.service.healthCheckNodePort=31000

This led to a cluster where the nginx-ingress ran one pod only (since controller.kind=Deployment and controller.replicaCount=1 by default) so only the host where the pod was running was healthy according to the ELB since it uses http://node:31000/healthz as health check.
I then set controller.kind=DaemonSet which fixed the issue.
Is my understanding correct here? I'm not entirely sure this is the right explanation as I'm not too familiar with externalTrafficPolicy=Local

**What you expected to happen**:

The chart should have validated this incoherent configuration before applying anything. 
Is it even possible for charts to do that? I've not seen any examples of it, but with charts like this that have so many components and settings without a higher-level validation it becomes too easy to create invalid configurations.

**How to reproduce it** (as minimally and precisely as possible):

as described in the "What happened" section

Thanks

**Comment by luisyonaldo** [comment]
That's the expected behavior. When you set `externalTrafficPolicy=Local` it made the service accessible (by `NodePort`) only on the nodes that have an endpoint running.
