### ISSUE TITLE
[stable/consul] Add resource limits

### ISSUE THREAD

**Issue by ReillyTevera** [helm/charts#4122]
FEATURE REQUEST

Can we add support for resource/request limits to the Consul chart? I don't mind adding a PR for it myself if that is acceptable to the chart maintainers.

**Version of Helm and Kubernetes**:
Kubernetes 1.8.7
Helm 2.8.1

**Which chart**:
Stable/Consul

**Comment by unguiculus** [comment]
You're welcome to create a PR.

**Comment by ReillyTevera** [comment]
I'm not sure how I missed it but the chart does in fact already support that. Closing.
