### ISSUE TITLE
Feature request for solving no space left on device

### ISSUE THREAD

**Issue by pontusarfwedson** [helm/charts#4127]
**FEATURE REQUEST**

**Version of Helm and Kubernetes**:
v2.8.1 and 1.9.2

**Which chart**:
Concourse 1.0.2

**What happened**:
Got `no space left on device` when initializing multiple builds at the same time. This caused most of them to fail.

**What you expected to happen**:
Expect the tasks to pass without the errors.

**How to reproduce it** (as minimally and precisely as possible):
Run the Concourse chart as is and run multiple tasks with dcind-image as base image and make them consume the existing space.

**REQUESTED FEATURE**:
In multiple places I have seen people say that one should increase the `btrfs_store_size_mb` in the garden containers. Is this in any way possible when running Concourse through the Helm chart rather than when deploying with BOSH? And are they referring to the btrfs size of our baggageclaim or the one in `garden`? Hard to keep track of what does what when only being a user of the Helm chart. When setting the filesystem type of baggageclaim we provide the environment variable `CONCOURSE_BAGGAGECLAIM_DRIVER`. I assume this goes into https://github.com/concourse/baggageclaim/blob/master/baggageclaimcmd/command.go where it is used. In the same file we can also provide the path to our mkfs binary. Is this something that can be done through helm to set the desired variable `btrfs_store_size_mb`? Or could another command be added to more easily allow a user to set that btrfs parameter? Anything to solve the issues with `no space left on device` would actually do.

**Comment by william-tran** [comment]
We provision 50GB PVs for each worker and I only occasionally run into out of disk issues, unfortunately, possibly due to https://github.com/kubernetes/kubernetes/issues/33084, when the worker restarts the space isn't reclaimed and I have to throw away the PV. If you need to set env vars that the worker runs with, which aren't directly supported by specific chart values, that can be done here: https://github.com/kubernetes/charts/blob/master/stable/concourse/values.yaml#L306.

**Comment by pontusarfwedson** [comment]
Thanks for reply! Yes, but there's no point in me setting env vars for the docker image if the container wont consider them? Which I guess more comes down to a specific feature in the concourse docker image. But since deployment with BOSH seems to have a quite straight forward way of setting the `btrfs_store_size_mb`for garden, then maybe a similar feature (as an env var for the docker image) would be nice!

**Comment by pontusarfwedson** [comment]
Is there any proper documentation of what env vars are considered for the concourse docker image? `https://github.com/concourse/concourse-docker` doesnt give me much

**Comment by william-tran** [comment]
Try exec-ing into any concourse pod and run `concourse worker --help` to see all the options
