### ISSUE TITLE
[stable/*] + [incubator/*] Add app description

### ISSUE THREAD

**Issue by scottrigby** [helm/charts#4140]
Note this is dependent on https://github.com/kubernetes/website/pull/7695, so these PRs are on hold until that is resolved. Once this is resolved, all charts in this repo should have PRs to add this. 

Here are the open PRs thus far:
- #2786
- #2787 
- #2788
- #2789 
- #2790  
- #2791  
- #2792 
- #2793 
- #2794 
- #2795 
- #2796 
- #2797 
- #2798

**Comment by scottrigby** [comment]
Also see https://github.com/kubernetes/dashboard/issues/2891

**Comment by prydonius** [comment]
cc @zouyee
