### ISSUE TITLE
postgresql chart fails when PVC is backed by glusterfs

### ISSUE THREAD

**Issue by ravishivt** [helm/charts#415]
When using glusterfs backed PVC, the gluster volumes automatically have two hidden directories: `.glusterfs` and `.trashcan`.  This causes the postgresql `initdb` task to fail because it wants an empty directory.  The postgresql pod will crash loop due to it.

Logs from postgresql container:

```
initdb: directory "/var/lib/postgresql/data/pgdata" exists but is not empty
It contains a dot-prefixed/invisible file, perhaps due to it being a mount point.
Using a mount point directly as the data directory is not recommended.
Create a subdirectory under the mount point.
```

**Comment by viglesiasce** [comment]
cc @databus23 

I hit this with PVCs that have [lost+found directories](https://github.com/kubernetes/charts/blob/master/stable/postgresql/templates/deployment.yaml#L21) as well but not sure if that is the right approach for .glusterfs and .trashcan.
