### ISSUE TITLE
nonLocalTraffic modifies the wrong environment variable

### ISSUE THREAD

**Issue by dustinphipps** [helm/charts#4160]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm v2.8.1, K8s v1.9.2

**Which chart**: stable/datadog

**What happened**: Setting `nonLocalTraffic` modifies the value of a variable inside the dd-agent container named `NON_LOCAL_TRAFFIC`. This has no effect whatsoever and the agent still refuses non-local traffic.

**What you expected to happen**: When using version 6 of the agent, the variable that *should* be set is `DD_DOGSTATSD_NON_LOCAL_TRAFFIC` as per the DataDog/datadog-agent [documentation](https://github.com/DataDog/datadog-agent/tree/master/Dockerfiles/agent#dogstatsd-custom-metrics).

**How to reproduce it** (as minimally and precisely as possible): Manually setting `DD_DOGSTATSD_NON_LOCAL_TRAFFIC` results in the expected behavior, as the agent will accept non-local traffic.

**Anything else we need to know**: I'm assuming this problem began happening after the switch to version 6 of the agent.

**Comment by c-knowles** [comment]
This was already resolved in https://github.com/kubernetes/charts/pull/3938.
