### ISSUE TITLE
[stable/traefik] metrics port/endpoint should not be exposed in traefik service

### ISSUE THREAD

**Issue by jalberto** [helm/charts#4236]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
2.7.2 & 1.8

**Which chart**:
traefik

**What happened**:
When `metrics.prometheus.enabled` this chart add access to metrics endpoint and port in main service, so it get exposed to internet.
The metrics endpoint should only be exposed in dashboard service, so it can be protected.

**What you expected to happen**:
Not to expose metrics to internet

**How to reproduce it** (as minimally and precisely as possible):
A vanilla install with prometheus metrics enbaled

**Anything else we need to know**:

**Comment by ajaegle** [comment]
See #4473 for more details. It's not only about metrics but the whole web-ui (dashboard) which is exposed as soon as metrics are enabled.

**Comment by jalberto** [comment]
so no one thinks this is important?
