### ISSUE TITLE
Grafana helm chart pod failing

### ISSUE THREAD

**Issue by gabeduke** [helm/charts#4267]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug Report

**Version of Helm and Kubernetes**:
Helm version: 2.8.2
Kuernetes Version: 1.9.4

**Which chart**: stable/grafana

**What happened**: grafana pod fails to start with the following error.This was previously working, and discussion in the rook.io slack with @galexrt turned up that this may be related to a recent [security patch](https://groups.google.com/forum/#!topic/kubernetes-announce/6sNHO_jyBzE) in kubernetes.

```chown: changing ownership of '/var/lib/grafana/dashboards/..2018_03_18_19_41_11.395501594': Read-only file system
chown: changing ownership of '/var/lib/grafana/dashboards/..data': Read-only file system
chown: changing ownership of '/var/lib/grafana/dashboards': Read-only file system
```

**How to reproduce**: Install the helm chart with default configurations on a node running 1.9.4

**Comment by svmaris** [comment]
I've submitted a PR with the same strategy I used with the rabbitmq-ha chart.

It still feels a little clunky to do this, but unless containers stop writing to their configdirs or Kubernetes allows writing to ConfigMaps again (or adds some primitives to do what I did in this PR automatically), I don't see any other way.

**Comment by Yitaek** [comment]
For a temporary workaround, you can add the following command for the docker container in the deployment.yaml (taken from the init script) 

command: ["/bin/bash", "-c", "chmod 777 /var/lib/grafana/ && gosu grafana /usr/sbin/grafana-server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini cfg:default.paths.provisioning=/etc/grafana/provisioning cfg:default.log.mode=console cfg:default.paths.data=/var/lib/grafana/ cfg:default.paths.logs=/var/lib/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins"]

**Comment by svmaris** [comment]
Related: https://github.com/grafana/grafana-docker/issues/141

**Comment by csabakollar** [comment]
alternative workaround: 

uncomment and modify the dashboardLocalPath value in the server object:
`  dashboardLocalPath: /var/lib/grafana-dashboards`

modify in grafana.ini the path value:
`[dashboards.json]
    enabled = true
    path = /var/lib/grafana-dashboards`

**Comment by csabakollar** [comment]
but looks like the fix is on its way:
https://github.com/grafana/grafana-docker/blob/master/run.sh#L9

**Comment by csabakollar** [comment]
alternative workaround:

in server object:

```yaml
  extraEnv:
  - name: GF_PATHS_CONFIG
    value: /etc/grafana-cm/grafana.ini
  
  configLocalPath: /etc/grafana-cm
  dashboardLocalPath: /var/lib/grafana-dashboards
```

and modify grafana.ini cm:

```yaml
    [dashboards.json]
    enabled = true
    path = /var/lib/grafana-dashboards
```

edit: i hate md

**Comment by mikesplain** [comment]
Thanks @csabakollar and all for the tips. I've been banging my head with this for a few hours.  I was able to just switch my image to `grafana/grafana:master` for now to solve the issue.
