### ISSUE TITLE
Gogs does not meet guidelines

### ISSUE THREAD

**Issue by cdrage** [helm/charts#4280]
I've been working on https://github.com/kubernetes/charts/pull/3408 on the basis of the `Gogs` chart that's been used and is located here: https://github.com/kubernetes/charts/tree/master/incubator/gogs

@unguiculus commented that my PR doesn't meet the current guidelines, thus Gogs does not actually meet the guidelines either. 

For example:
 https://github.com/kubernetes/charts/blob/380c858bbde554a02e6525667676ebe63d4f19cc/incubator/gogs/templates/configmap-tcp.yaml#L5

Should be using: `{{ template "gogs.fullname" . }}` instead.

**Comment by unguiculus** [comment]
You should always use `helm create` when creating a new chart. Existing charts may not always fully meet the guidelines. Guidelines evolve and are improved over time. This does not automatically mean all charts are updated. That being said we'd appreciate a PR that updates the Gogs chart with current best practices.
