### ISSUE TITLE
[incubator/zookeeper]StatefullSet Desired=3 Current=1 and Pod status stays "Pending"

### ISSUE THREAD

**Issue by tesujiro** [helm/charts#4305]
**Is this a request for help?**:
YES

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm v2.8.2
Kubernetes v1.9.2  - Docker for Mac with Kubernetes 

**Which chart**:
incubator/zookeeper

**What happened**:
I installed incubator/zookeeper without error , but the pod status stays "Pending" and the number of stateful set does not increase. 

```
$> kubectl get po
NAME                     READY     STATUS    RESTARTS   AGE
myzk-zookeeper-0         0/1       Pending   0          23m
$> kubectl get sts
NAME             DESIRED   CURRENT   AGE
myzk-zookeeper   3         1         25m
$>kubectl logs myzk-zookeeper-0  
$>kubectl logs sts/myzk-zookeeper
$>
```
**What you expected to happen**:
ZooKeeper starting up correctly

**How to reproduce it** (as minimally and precisely as possible):
helm install incubator/zookeepe

**Anything else we need to know**:

**Comment by ebabani** [comment]
What does `kubectl describe` show for the pod?

**Comment by tesujiro** [comment]
`kubectl describe po XXXX` showed below , and changed configuration.

```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  19h (x1114 over 1d)  default-scheduler  0/1 nodes are available: 1 Insufficient memory.

```
Now it is working perfectly.
Thank you!
