### ISSUE TITLE
Official docker image with source dockerfile for danisla/hadoop

### ISSUE THREAD

**Issue by sylus** [helm/charts#4370]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Version of Helm and Kubernetes**: 2.6.1 and 1.9.4

**Which chart**: Hadoop

**What happened**:

I would like to have the official source of the docker image that is used for Hadoop, the docker hub registry isn't linked to the actual Dockerfile. For us to use charts we need to have provenance and no the exact lines run in the dockerfile.

**What you expected to happen**:

That there would be an accessible github url for danisla/hadoop

**How to reproduce it** (as minimally and precisely as possible): N/A

**Anything else we need to know**: N/A

**Comment by sylus** [comment]
Just pinging @danisla directly.

Would it be possible to get the source dockerfile for what is run in docker hub?

**Comment by danisla** [comment]
Here is the location of the Dockerfile for the image: https://github.com/Comcast/kube-yarn/tree/master/image

I added it to the [dockerhub page](https://hub.docker.com/r/danisla/hadoop/) as well.

**Comment by sylus** [comment]
Ah thanks so much for this, I saw that repo but wasn't sure. Thanks again for the amazing work you have done. If helps I have talked to @kimoonkim and looking to eventually add his HDFS work here into official: https://github.com/kimoonkim/kubernetes-HDFS

Includes data locality fix. I'll ping you when open new issue for that :)
