### ISSUE TITLE
Redis chart service deployment no longer appends chart and release name

### ISSUE THREAD

**Issue by nsvora** [helm/charts#4375]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 

**Version of Helm and Kubernetes**:
 helm version
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.2", GitCommit:"63dad40a0391b7af32c34fdbf41fa199c3b247ad", GitTreeState:"clean", BuildDate:"2018-03-07T20:30:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/redis

**What happened**:
Installed latest helm chart (1.1.20):
helm install stable/redis --name redis --namespace lucy --set redisPassword=test --debug

Executed following commands on kubernetes cluster after install
kubectl get deployment 
kubectl get services

Both of the above commands used to have chart and release until chart version 1.1.17.
Output of above commands used to have redis-redis as service and deployment names.

On further investigation found that this is broken since 1.1.19, only redis is showing up in above commands. Chart name is not being appended to release name.

**What you expected to happen**:
Both of the above commands used to have chart and release names appended until chart version 1.1.17.
Output of above commands used to have redis-redis as service and deployment names.

However since 1.1.19, only redis is showing up in above commands. Chart name is not being appended.

**How to reproduce it** (as minimally and precisely as possible):
Refer above to reproduce the issue

**Anything else we need to know**:
None

**Comment by unguiculus** [comment]
This works as intended with the updated `_helpers.tpl`. Check out the source to find out how to adapt the fullname.

https://github.com/kubernetes/charts/blob/master/stable/redis/templates/_helpers.tpl#L14
