### ISSUE TITLE
Bitcoind failing on 1.9.4

### ISSUE THREAD

**Issue by raybotha** [helm/charts#4407]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Helm 2.8.2
1.9.4-gke.1

**Which chart**:
stable/bitcoind

**What happened**:
CrashLoopBackOff on a clean helm install
kubectl logs just show:
`chown: changing ownership of './.bitcoin/bitcoin.conf': Read-only file system`

**How to reproduce it** (as minimally and precisely as possible):
Run `helm install stable/bitcoind` on 1.9.4

I suspect this is another issue with 1.9.4 treating configmaps as read-only.

**Comment by raybotha** [comment]
Yep, it's another configmap read-only mount issue. Opened PR to fix https://github.com/kubernetes/charts/pull/4411

**Comment by i-am-logger** [comment]
I get the following error: 
```chown: cannot read directory '.': Permission denied```
