### ISSUE TITLE
[stable/postgresql] Add annotations to pod

### ISSUE THREAD

**Issue by jalberto** [helm/charts#4418]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
1.7/1.8

**Which chart**:
postgresql

**What happened**:
When deployed with metrics enabled, is expected to modify prometheus configuration manually, instead just add this annotations will simplify deployment:

```
prometheus.io/scrape: true
prometheus.io/port: 9138
```

**Comment by mattjmcnaughton** [comment]
I will put a pr out for this rn :)
