### ISSUE TITLE
Traefik connection refused

### ISSUE THREAD

**Issue by joshuacox** [helm/charts#4446]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
kubernetes 1.8.4-1.9.3

**Which chart**:
stable/traefik

**What happened**:

Installed traefik using helm then connection refused

```
[node1 /]$ curl 172.29.0.3
curl: (7) Failed connect to 172.29.0.3:80; Connection refused
```

**What you expected to happen**:

When following the [official guide](https://docs.traefik.io/user-guide/kubernetes/), before submitting an ingress but after deploying the service I can query a node and get a 404 back.

```
curl 172.22.0.3
404 page not found
```

**How to reproduce it** (as minimally and precisely as possible):

spin up an instance at:
https://labs.play-with-k8s.com/

```
curl https://gist.githubusercontent.com/joshuacox/ed8173a43659f01ede983fcbaa0dafe2/raw/4b4de85d6528d7533a8adf720982d99cea16536f/kubestart.sh | bash
```

run the kubeadm join command on a second node

Then back on the master node label it, and install traefik

```
kubectl  label --overwrite node node2 node-role.kubernetes.io/node=
helm install stable/traefik
```

then curl port 80 on the second node:

```
[node1 /]$ curl 172.29.0.3
curl: (7) Failed connect to 172.29.0.3:80; Connection refused
```

**Anything else we need to know**:

When trying to match the NodePort of the official guide helm returns the error:
```
Error: release traefik failed: Service "traefik-traefik" is invalid: spec.ports[0].nodePort: Invalid value: 80: provided port is not in the valid range. The range of valid ports is 30000-32767
```
yet on the same cluster when I apply the yaml files from the official guide I can assign port 80 no problem

To replicate this condition on https://labs.play-with-k8s.com/ start up your first instance and:

```
curl https://gist.githubusercontent.com/joshuacox/ed8173a43659f01ede983fcbaa0dafe2/raw/8faf3eca30cff2cbc319b67e8fc420f5eea084b7/kubestart.sh | bash
```

create a second instance and run the kubeadm join command on it then label it.

```
kubectl  label --overwrite node node2 node-role.kubernetes.io/node=
```

then test by curling port 80 on node2

```
[node1 /]$ curl 172.30.0.3
404 page not found
```

**Comment by krancour** [comment]
@joshuacox, I don't believe there's any bug here. I think there might be a misunderstanding of how connectivity from outside your cluster works.

When you install this chart, the default is that you get a service of type `LoadBalancer`. This can be overridden with another type-- `NodePort`, for instance-- if you're not in an environment with a cloud provider that can provision an external load balancer for you. In _both_  of these common cases-- `LoadBalancer` or `NodePort`-- the ports _within_ the container  are mapped to _non-privileged_ ports on the nodes(s)-- all in the range 30000-32767. 80 is not only _not_ in that range, but is also a privileged port.

It seems you've attempted to override some of the chart's default values to request a mapping to port 80, but Kubernetes doesn't let you do that-- hence the error message you got:

> Error: release traefik failed: Service "traefik-traefik" is invalid: spec.ports[0].nodePort: Invalid value: 80: provided port is not in the valid range. The range of valid ports is 30000-32767

The way this is supposed to work is that port 80 _on your load balancer_ gets mapped to the dynamically assigned node port on your node(s), which (via the kube-proxy and your `Service`) is mapped to port 80 of the endpoint(s) (pods) that are running a Traefik container.

So... if you have a load balancer in play here, `curl` _its_ public IP; not the public IP of a k8s node.

No doubt, at this point, you're wondering how this ever could have worked in the [official guide](https://docs.traefik.io/user-guide/kubernetes/) you linked to. It seems that guide offers two distinct options for how to deploy this. In one model, they use a `Deployment` (which is what this chart does) and in the other, they use a `DaemonSet` (this chart doesn't do that yet, but I believe there's an open PR to make that an option). In that latter example (using a `DaemonSet`), the pod templates they use directly specify a `hostPort` of 80. _This is different than using a service._ This makes it a _requirement_ that the scheduler only schedules your Traefik pod(s) to node(s) where port 80 is available.

I have a feeling you were using that second option when following their guide.

Anyway-- try `curl`ing your load balancer and see what happens. Hope this helps. Let me know if you have any questions.

**Comment by joshuacox** [comment]
Ya I think that is the issue, I'm doing this on on-premise with bare-metal and I was thinking traefik would be my load-balancer.  It's entirely possibly that traefik could do that (I certainly had it doing that for http/s services when using rancher+traefik on bare-metal).

I'd gladly try any out some different methods to that effect, but it seems at the moment I'm attempting to do the same with voyager instead:

https://github.com/appscode/voyager

closing here, feel free to re-open and ask me to try out something different.  The above gists + the PWK K8S playground can duplicate my attempts if anyone cares to.

**Comment by krancour** [comment]
> I was thinking traefik would be my load-balancer.

That really is not it's role. It's role is to direct traffic coming into the cluster to an appropriate service. The services themselves, internally, can be thought of as internal load balancers, in manner of speaking.

Assuming you have more than one Traefik pod, you need need a load balancer in front of _that_. i.e. An _external_ load balancer. In the cloud, this would be an ELB or similar. On bare metal, you need to provide something similar yourself.

The poor man's option is to use DNS round robining to distribute traffic across all your Kubernetes nodes (or across all the nodes that are running a Traefik pod).
