### ISSUE TITLE
[stable/oauth2-proxy]

### ISSUE THREAD

**Issue by goruha** [helm/charts#4452]
There is info about incompatibility between oauth2-proxy and nginx-ingress nginx-ingress versions >= 0.9beta12.

What type of incompatibility it is? 
Where can I find a link with description?

**Comment by bhack** [comment]
On the other side the repo seems not maintained. Check https://github.com/bitly/oauth2_proxy/issues/594

**Comment by compleatang** [comment]
There's a few competing PRs for the fix that haven't been merged upstream. There are some work arounds in various places but I haven't had time to test or document them and we aren't using the chart internally any longer. 

A few links:

https://github.com/bitly/oauth2_proxy/pull/461
https://github.com/bitly/oauth2_proxy/pull/490
https://github.com/bitly/oauth2_proxy/pull/427

**Comment by bhack** [comment]
The upstream repo will be put in read only mode https://github.com/bitly/oauth2_proxy/issues/628

**Comment by apriendeau** [comment]
We recommend looking into "buzzfeed/sso" which is better maintained.

**Comment by compleatang** [comment]
I'm deprecating the chart as we're no longer using it internally and it's outside my scope of expertise to properly vet whatever happens from the community. If another maintainer would like to pick it up they should feel free. https://github.com/helm/charts/pull/7454
