### ISSUE TITLE
[incubator/logstash] toggling persistence

### ISSUE THREAD

**Issue by messiahUA** [helm/charts#4471]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: 2.8.1 and 1.8.10

**Which chart**: incubator/logstash

**What happened**: chart has a parameter "persistence.enabled" which is not used anywhere and it's actually not possible to disable persistence.

**What you expected to happen**: it should be possible to completely disable persistence with "persistence.enabled" set to false

**Comment by Reasno** [comment]
run into the same problem today. Can any one provides instruction on how to manually disable persistence?
