### ISSUE TITLE
[stable/redis] helm upgrade change password secret

### ISSUE THREAD

**Issue by maver1ck** [helm/charts#4472]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:

Helm: v2.8.2
K8s: v1.9.3

**Which chart**:
stable/redis

**What happened**:
After helm upgrade secret with password has changed but redis password remains the same.

**What you expected to happen**:
Helm upgrade shouldn't change redis password secret

**How to reproduce it** (as minimally and precisely as possible):
1. Create stable/redis deployment.
``` helm install stable/redis```
2. Save password
3. Upgrade it
``` helm upgrade NAME stable/redis```
4. Try to log in to redis with new password
5. Try to log in to redis with old password.

**Anything else we need to know**:

**Comment by Miouge1** [comment]
I think this happens only if you have persistence enabled.
See #4965

**Comment by mikberg** [comment]
Similar: #2538
