### ISSUE TITLE
[stable/openvpn] upgrade image

### ISSUE THREAD

**Issue by jalberto** [helm/charts#4569]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feautre Request

**Which chart**:
openvpn

This chart use a 1yr old image (tag 1.1.0) current opvpn version is 2.5

**Comment by a7i** [comment]
I've created a Pull Request for the base repo: https://github.com/jfelten/openvpn-docker/pull/1
Once merged, will need to create a Pull Request for the Charts repo from fork: https://github.com/a7i/charts

**Comment by oded-dd** [comment]
+1
