### ISSUE TITLE
[stable/rabbimq-ha] pod unable to rejoin cluster after crashing

### ISSUE THREAD

**Issue by gorille** [helm/charts#4685]
**Is this a request for help?**: 
NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  
BUG REPORT

**Version of Helm and Kubernetes**: 
helm 2.8.2, kubernetes 1.8.1

**Which chart**: 
stable/rabbitmq-ha

**What happened**:
when you kill a pod in the statefull set, it is unable to re-join the cluster

**What you expected to happen**:
It should be able to rejoin the cluster without issue.

**How to reproduce it** (as minimally and precisely as possible):

- enable the pvc inside value.yml
- helm install stable/rabbitmq-ha
- wait for it to come online
- kill a pod
- watch the log

**Anything else we need to know**:
the issues comes from  [here](https://github.com/kubernetes/charts/blob/master/stable/rabbitmq-ha/templates/configmap.yaml#L60) 
The pod is no longer reachable so the node cleanup which fires every 10 sec as per config will remove this node from the cluster, because it takes more than 10 sec for it to come back online

When the nodes comes back online, the cluster rejects it, as it has been evicted by the cleanup process

**Comment by etiennetremel** [comment]
Hi @gorille, PR https://github.com/kubernetes/charts/pull/4610 should fix it, can you try with a brand new RabbitMQ cluster running the latest version of the chart?

**Comment by gorille** [comment]
Hi @etiennetremel !
Sorry for the delay, I had to break my test install to be able to test that.
I do confirm that this solves the issue, thank you for your help
