### ISSUE TITLE
[stable/consul] failure during `helm upgrade`

### ISSUE THREAD

**Issue by rvandegrift** [helm/charts#4746]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
helm v2.8.2
kubernetes: 1.8.8-gke.0

**Which chart**:
stable/consul

**What happened**:
I would like to update my consul servers with a new parameter.  So I modified my yaml file and tried to run `helm upgrade`:
```
$ helm upgrade -f consul-params.yml consul stable/consul
Error: UPGRADE FAILED: Service "consul-consul" is invalid: [spec.ports[3].name: Duplicate value: "serflan-udp", spec.ports[3]: Duplicate value: api.ServicePort{Name:"", Protocol:"UDP", Port:8301, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:""}, NodePort:0}]
```

**What you expected to happen**:
consul to be updated with the new parameters

**How to reproduce it** (as minimally and precisely as possible):
```sh
cat > consul-params.yml << EOF
ImageTag: 1.0.6
EOF
helm install --name testing -f consul-params.yml stable/consul
sleep 30  # or until the cluster is up
echo "ConsulDnsPort: 53" >> consul-params.yml
helm upgrade -f consul-params.yml testing stable/consul
```

**Comment by nikh1508** [comment]
We faced a similar issue on our staging Kubernetes cluster. We were able to fix it by removing the duplicate keys in the StatefulSet YML config from the Kubernetes dashboard.
For this go to "Stateful Sets" on the left panel on the dashboard and edit YML for consul, remove the duplicate keys and then apply.
