### ISSUE TITLE
etcd service (deployed using incubator/etcd chart) is not coming up after restart or failure

### ISSUE THREAD

**Issue by gaurav-dalvi** [helm/charts#4883]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
https://github.com/kubernetes/charts/tree/master/incubator/etcd

**What happened**:
deploy this chart using helm install. (I am using local dir for pv).
delete etcd pod 
etcd pod never comes up
shows this error : 
```
Re-joining etcd member
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp: lookupxyz-etcd-0.xyz-etcd on 10.96.0.10:53: no such host

error #0: dial tcp: lookup xyz-etcd-0.xyz-etcd on 10.96.0.10:53: no such host
```

**What you expected to happen**:
etcd should come up properly without any issues.

**How to reproduce it** (as minimally and precisely as possible):
0: use local / hostpath volume for statefulset
1: helm install <this chart>
2: helm delete 
3: helm install <this chart>

**Anything else we need to know**:
I am using this etcd image : 
Image: k8s.gcr.io/etcd-amd64
ImageTag: 3.1.11
StorageClass: standard
Replicas: 1 (tested with 3 as well, same issue)

**Comment by gaurav-dalvi** [comment]
Any reply on this one ?

**Comment by peternavr** [comment]
Same issue here.

**Comment by stephan2012** [comment]
Same here. In two cases the shell script tries to update the hostname for the member (peerURLs) although the etcd cluster is not running and has thus no valid endpoints:

- The cluster is a single-member cluster
- The initial size of the cluster is 1 and the first member is offline

```
+ hostname
+ HOSTNAME=etcd-0
+ '[' -e /var/run/etcd/default.etcd ]
+ echo 'Re-joining etcd member'
Re-joining etcd member
+ cat /var/run/etcd/member_id
+ member_id=2e80f96756a54ca9
+ eps
+ EPS=
+ seq 0 0
+ EPS=http://etcd-0.etcd:2379
+ echo http://etcd-0.etcd:2379
+ ETCDCTL_ENDPOINT=http://etcd-0.etcd:2379 etcdctl member update 2e80f96756a54ca9 http://etcd-0.etcd:2380
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp: lookup etcd-0.etcd on 10.188.16.10:53: no such host

error #0: dial tcp: lookup etcd-0.etcd on 10.188.16.10:53: no such host
```

The shell runs with the `-e` flag set so it terminates execution on the first error which prevents etcd from starting.

For Stateful Sets the container hostname is stable (e.g., `etcd-0` for the first container) so there is no need to update it.

For me the solution would be to just drop the line

```bash
ETCDCTL_ENDPOINT=$(eps) etcdctl member update ${member_id} http://${HOSTNAME}.${SET_NAME}:2380
```
