### ISSUE TITLE
Version of stable/nginx-ingress doesn't match version in official repo

### ISSUE THREAD

**Issue by Sennahoi** [helm/charts#4912]
**Is this a request for help?**:
I think so.

The readme.md states that
> The Charts in the stable/ directory in the master branch of this repository match the latest packaged Chart in the Chart Repository, though there may be previous versions of a Chart available in that Chart Repository.

The version in the master branch of stable/nginx-ingress is 0.13.1, but when I check helm, I get the following version:

`jtonn@k8s-master-13517872-0:~$ helm search stable/nginx-ingress
NAME                	CHART VERSION	APP VERSION	DESCRIPTION
stable/nginx-ingress	0.11.1       	0.11.0     	An nginx Ingress controller that uses ConfigMap...`

Why do the versions differ?

**Comment by jaredallard** [comment]
Have you tried running `helm repo up`?

```bash
jaredallard/develop ❯ helm search stable/nginx-ingress
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
stable/nginx-ingress    0.13.1          0.12.0          An nginx Ingress controller that uses ConfigMap...
```

**Comment by Sennahoi** [comment]
Can't believe I didn't see this one when I wrote this issue. Thanks and sorry.
