### ISSUE TITLE
[incubator/keycloak] Need to expose infinispan port for replication

### ISSUE THREAD

**Issue by gregdurham** [helm/charts#4914]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Version of Helm and Kubernetes**: 1.9

**Which chart**: incubator/keycloak

**What happened**: When setting keycloak replicas > 1 I do not believe the containers actually replicate their cache

**What you expected to happen**: I would expect that we would need to expose minimally port 7600 for infinispan to replicate cache amongst the cluster. I see that the only port exposed is 8080. When using replicas, it configures jgroups, using JDBC ping to add hosts to the db table for discovery, however I do not beleive the containers can talk to one another. 

**How to reproduce it** (as minimally and precisely as possible): Set replicas > 1, monitor logs on each, and see if the instances can talk to one another. 

**Anything else we need to know**:

**Comment by unguiculus** [comment]
Did you run any tests or are you just guessing?

The logs suggest that it works and I did successfully test it. Feel free to open a PR if you think this needs to be improved.
