### ISSUE TITLE
semverCompare error installing nginx-ingress

### ISSUE THREAD

**Issue by alinnow** [helm/charts#4953]
**Is this a request for help?**: probably

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Version of Helm and Kubernetes**: helm: 2.8.1, kubernetes: Open Telekom Cloud CCE `Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"cce-1.7.3.17+8857de1a267f8f-dirty", GitCommit:"8857de1a267f8fa8075caccf446b2327ed76435c", GitTreeState:"dirty", BuildDate:"2017-09-15T02:03:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

**Which chart**: stable/nginx-ingress 0.13.0

**What happened**: Installation fails:
> Error: render error in "nginx-ingress/templates/controller-service.yaml": template: nginx-ingress/templates/controller-service.yaml:28:12: executing "nginx-ingress/templates/controller-service.yaml" at <semverCompare ">=1.7...>: error calling semverCompare: Invalid Semantic Version

**What you expected to happen**: Successful installation using logic for k8s 1.7.3

**How to reproduce it** (as minimally and precisely as possible): 
- Create a cluster in Open Telekom Cloud and configure access to it.
- `helm init`
- `helm install stable/nginx-ingress`

**Anything else we need to know**:

Works fine on a minikube with version: 
`Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}`

I guess this is probably caused by the strange version string returned in OTC CCE ("cce-1.7.3.17+8857de1a267f8f-dirty"). As it's a cloud offering, I can't do anything about it.

**Comment by unguiculus** [comment]
cc @mattfarina 

Yet another weird versioning scheme. You may want to open a ticket with your provider and request semver-compatible versions.

**Comment by jwilander** [comment]
FWIW I've just run into this using a Kubes cluster set-up on AWS using kops

```bash
$ helm version
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

```bash
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**EDIT: Might not actually be an issue for me. Only seems to complain on `helm lint`, installing seems to work fine.**

**Comment by mattfarina** [comment]
`cce-1.7.3.17+8857de1a267f8f-dirty` is not a valid semantic version and is likely causing the error.

**Comment by nick4fake** [comment]
Why do we even have this requirement? It doesn't make sense, docker tags can be any string
