### ISSUE TITLE
[stable/nginx-ingress] Incorrect documentation of options

### ISSUE THREAD

**Issue by nrmitchi** [helm/charts#4977]
The README and documentation currently includes an option:

`controller.metrics.service.targetPort` with the default of port `10254` (which appears as if it's supposed to be separate from the `controller.metrics.service.servicePort`, which defaults as `9913`.

This values does not actually appear to be used anywhere though, or present in the default `values.yaml`. This seems like an oversight at some point, but I'm not sure what the correct usage/documentation is supposed to be.

**Comment by Jokero** [comment]
Actually documentation is bad part of charts. I usually do not trust it and only read `values.yaml`

**Comment by unguiculus** [comment]
@Jokero We do our best to look at such things when reviewing and contributing to charts. Nobody's perfect, though. Instead of just complaining, how about creating a PR instead?

**Comment by Jokero** [comment]
@unguiculus Do not consider my comment as complaint, this is like statement of the fact. Maybe configuration table should be generated automatically based on `values.yaml` content. I agree that current approach for manual writing of readme is really not perfect and you can easily forget something or make an mistake. We need some general solution.
