### ISSUE TITLE
Telegraf chart deprecation

### ISSUE THREAD

**Issue by Flowkap** [helm/charts#5006]
Request for help!

I'm confused as the telegraf charts states: 

"This chart has been deprecated as of version 0.2.1 and will not be updated. Please use the telegraf-s and telegraf-ds charts instead." 

These two do not exists AND the version is 0.3.3 in the meantime. Whats now right? 

**Which chart**:

stable/telegraf 

**What happened**:

Documentation confusing (deprecation warning)

**Comment by unguiculus** [comment]
It looks like they have the charts in their own repo.

https://github.com/influxdata/tick-charts
