### ISSUE TITLE
Keycloak Administrator Port 9993

### ISSUE THREAD

**Issue by joshskains** [helm/charts#5014]
**Is this a request for help?**: Possibly

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

It's a needed feature

**Version of Helm and Kubernetes**:

Helm Client/Server 2.8.2 Kube 1.9

**Which chart**:

keycloak

**What happened**:

Need to access keycloak port 9993 for API calls

**What you expected to happen**:

Simple way to know how to access 9993

**How to reproduce it** (as minimally and precisely as possible):

Well, try to access port 9993? :)

**Anything else we need to know**:

Also would like to know the process to update things like themes in this design. Is there an easy way, or do we have to fork the docker container?

**Comment by unguiculus** [comment]
The API port is not exposed. would you like to create a PR for this?

For custom themes you can create your own Docker image based on the official image and add your theme module. The chart has support for a custom CLI script which should allow you to install the theme.

**Comment by joshskains** [comment]
I think we could also use a PV and attach it. Let me make a specific PR for the port. Thank you.

**Comment by unguiculus** [comment]
See #5887 #5950
