### ISSUE TITLE
using external.enabled=true, does not work

### ISSUE THREAD

**Issue by parmarnikunj** [helm/charts#5017]
i want to enable kafka cluster using external.enabled=true in minikube. Unfortunately even after enabling this I cannot run my kafka-console-producer against it. Kafka is not reachable using minikube_ip:external_port. I tried using 192.168.99.100:31090. Is there any extra settings needs to be done, like adjusting advertised.listeners ? If yes can I get an example configuration values for it?

**Comment by ghost** [comment]
Hi @parmarnikunj .

Please see the guidance at https://github.com/kubernetes/charts/pull/4400

Let me know if it helps fix the issue you're facing.

**Comment by parmarnikunj** [comment]
Thanks it works now

**Comment by skullmaggots** [comment]
@parmarnikunj - Could you be clear on what you did differently this time? I've been struggling to get external access working for 2 days and am stuck with the init container failing due a 403 forbidden error. 

Thanks.

**Comment by ghost** [comment]
@skullmaggots My intuition is that your issue is related to RBAC somehow. I developed the external access patch in clusters without RBAC. Can you confirm?

Related: https://github.com/fluent/fluentd-kubernetes-daemonset/issues/14

**Comment by skullmaggots** [comment]
I'm using minikube locally which AFAIK doesn't enable RBAC by default.

Here's the details of the issue I raised previously #5058

**Comment by parmarnikunj** [comment]
hi @skullmaggots these are the steps I followed which were different than previously.

- change the graph version to 0.5.1
- adjust external configuration as below:
external:
      domain: 192.168.99.100
      enabled: true
      firstListenerPort: 31090
      servicePort: 19092
- adjust the configurationOverrides as below:
configurationOverrides:
      advertised.listeners : EXTERNAL://192.168.99.100:$((31090 + ${KAFKA_BROKER_ID}))
      listener.security.protocol.map: PLAINTEXT:PLAINTEXT, EXTERNAL:PLAINTEXT
      auto.create.topics.enable: "true"
- made zookeeper creation also by this chart:
zookeeper:
  servers: 1

And I could send messages to 192.168.99.100:31090.

**Comment by thiennhan2310** [comment]
Hi I have the same issue when external.enabled = true
I have follow @parmarnikunj configure but kafka pods still CrashLooback
<img width="630" alt="screen shot 2018-09-05 at 9 47 35 pm" src="https://user-images.githubusercontent.com/12071356/45101306-60d97280-b155-11e8-8d21-c2b05da9a53c.png">
