### ISSUE TITLE
Grafana Version Incorrect

### ISSUE THREAD

**Issue by mjallday** [helm/charts#5022]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"
```

**Which chart**:
[stable/grafana](https://github.com/kubernetes/charts/tree/master/stable/grafana)

**What happened**:

Installing without any arguments installs an older version (4.6.3) than what is defined in the [`Values.yml`](https://github.com/kubernetes/charts/blob/master/stable/grafana/values.yaml#L3-L6)

```
helm install --name grafana-vgs stable/grafana --dry-run --debug | grep grafana/grafana
  image: grafana/grafana:4.6.3
          image: "grafana/grafana:4.6.3"
```

**What you expected to happen**:
Values contains 5.0.4 so I would expect it to install that version

https://github.com/kubernetes/charts/blob/master/stable/grafana/values.yaml#L3-L6

**How to reproduce it** (as minimally and precisely as possible):
`helm install --name grafana-vgs stable/grafana --dry-run --debug | grep grafana/grafana`

**Anything else we need to know**:
Overriding the value does not appear to work. E.g.

`helm install --name grafana-vgs stable/grafana --dry-run --debug --set image.tag=5.0.4 | grep 5.0.4` returns nothing

i can override it by doing

`helm install --name grafana-vgs stable/grafana --dry-run --debug --set server.image=grafana/grafana:5.0.4`

**Comment by ghost** [comment]
cc: @rtluckie

**Comment by unguiculus** [comment]
Is your cache up to date?

Do `helm repo up`

**Comment by mjallday** [comment]
thanks @unguiculus. 

```
➜  jenkins-pipelines git:(master) helm install --name grafana-vgs stable/grafana --dry-run --debug | grep grafana/grafana
  image: grafana/grafana:4.6.3
          image: "grafana/grafana:4.6.3"
➜  jenkins-pipelines git:(master) helm repo up
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
➜  jenkins-pipelines git:(master) helm install --name grafana-vgs stable/grafana --dry-run --debug | grep grafana/grafana
  repository: grafana/grafana
          image: "grafana/grafana:5.0.4"
              mountPath: "/etc/grafana/grafana.ini"
➜  jenkins-pipelines git:(master)
```

looks like that solved the issue.

/cc @srhopkins
