### ISSUE TITLE
[tensorflow-serving] Image in NOTES.txt not available

### ISSUE THREAD

**Issue by thomasliddledba** [helm/charts#5040]
Version of Helm and Kubernetes:
Helm Version

Client 2.7.0
Server 2.70

Which chart:
[tensorflow-serving]

What happened:
Performing the following command gets error with image ErrImagePull
```
echo docker run -it --rm cheyang/tf-mnist:grpcio_upgraded /serving/bazel-bin/tensorflow_serving/example/mnist_client --num_tests=1000 --server=$TF_SERVING_SERVICE_IP:9090`
```

I don't see this image in the cheyang dockerhub repository.

**Comment by thomasliddledba** [comment]
cc @cheyang

**Comment by cheyang** [comment]
Please try again. I've pushed the docker image. Thanks for reporting it.
