### ISSUE TITLE
system:serviceaccount:default:default" cannot get pods in the namespace "default"

### ISSUE THREAD

**Issue by skullmaggots** [helm/charts#5058]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

minikube version: v0.26.0

**Which chart**:
incubator/kafka

**What happened**:
install a single node kafka + zookeeper with the following values (trying to configure it to allow access locally whilst developing)

`replicas: 1
external:
    enabled: true
    firstListenerPort: 31290
configurationOverrides:
  "offsets.topic.replication.factor": 1

zookeeper:
  servers: 1
  heap: 256m
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi`

Running the above will cause the kafka pod init container to fail/crash and it will get into a continuous CrashBackOffLoop. 

Investigating further I find the init container fails with...

gl02829m:kafka jeff.bannister$ kubectl logs -p offer2-kafka-kafka-0 -c init-ext
+ kubectl label pods offer2-kafka-kafka-0 --namespace default pod=offer2-kafka-kafka-0
Error from server (Forbidden): pods "offer2-kafka-kafka-0" is forbidden: User "system:serviceaccount:default:default" cannot get pods in the namespace "default"

Looks like a permission issue with the serviceaccount user. However I've got a basic install of helm with no RBAC configured so surprised to receive such an error.

**What you expected to happen**:
Pods start correctly. 

**How to reproduce it** (as minimally and precisely as possible):
helm install --name offer2-kafka -f local-kafka-values.yaml incubator/kafka

where local-kafka-values contains...

`replicas: 1
external:
    enabled: true
    firstListenerPort: 31290
configurationOverrides:
  "offsets.topic.replication.factor": 1

zookeeper:
  servers: 1
  heap: 256m
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi`

**Anything else we need to know**:

**Comment by skullmaggots** [comment]
Tried again this time with a different docker cluster, in this case kubernetes running in docker community edition (edge channel) and it works as expected. Seem like some weird perms are getting set when using minikube. I'd imagine this will trip quite a few up as AFAIK using minikube is a standard/typical way of developing kubernetes based apps.

**Comment by maximmass** [comment]
Also running into this with AWS EKS only with external.enabled=true
