### ISSUE TITLE
Bug: Incorrect value in the stable/rabbitmq chart

### ISSUE THREAD

**Issue by afrocircus** [helm/charts#5078]
---

**BUG REPORT**:

**Version of Helm and Kubernetes**:
Helm: v2.8.2
Kubernetes: v1.10.0
Minikube: v0.26.0

**Which chart**:
stable/rabbitmq

**What happened**:
I tried to install rabbitmq using helm with RBAC enabled in the helm charts. 
However, the readiness probe fails when deployed to the cluster.
On inspecting the logs, I see the error: Failed to get nodes from k8s - 403

**What you expected to happen**:
For kubernetes 1.6 and above RBAC is enabled by default. So when I enable RBAC in the rabbitmq chart, I expect the rabbit-peer-discovery-k8s plugin to work and not return a 403 error.

**How to reproduce it** (as minimally and precisely as possible):
Using the specified versions of minikube, kubernetes and helm:
Set rbacEnabled: true
$ minikube start
$ helm install stable/rabbitmq

**Anything else we need to know**:
In templates/rolebinding.yaml the service account name is set to 'rabbitmq'
Changing this value to {{ template "rabbitmq.fullname" . }} fixes the problem as that is the value specified in templates/serviceaccount.yaml

File: templates/rolebinding.yaml
```
subjects:
   - kind: ServiceAccount
-    name:  rabbitmq
+    name:  {{ template "rabbitmq.fullname" . }} 
```

**Comment by rjkernick** [comment]
fixed by #5158 
/close
