### ISSUE TITLE
[stable/ingress-nginx] api version v1beta1 for daemonset not supported in newer version of k8s

### ISSUE THREAD

**Issue by laurent-perrin** [helm/charts#5079]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Version of Helm and Kubernetes**: helm 2.8.1, kubernetes 1.9.5 (deployed with kubespray)

**Which chart**: stable/nginx-ingress 0.13.0

**What happened**: installation failed because of api version not supported
```
helm install stable/nginx-ingress --name ingress-nginx --set rbac.create=true --set controller.service.type=LoadBalancer --set controller.nodeSelector=node-role.kubernetes.io/ingress=true --set controller.service.nodePorts.http=80 --set controller.service.nodePorts.https=443  --set controller.kind=DaemonSet --namespace ingress-nginx 
Error: release ingress-nginx failed: DaemonSet in version "v1beta1" cannot be handled as a DaemonSet: v1beta1.DaemonSet: Spec: v1beta1.DaemonSetSpec: Template: v1.PodTemplateSpec: Spec: v1.PodSpec: NodeSelector: ReadMapCB: expect { or n, parsing 1697 ...elector":"... at {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"labels":{"app":"nginx-ingress","chart":"nginx-ingress-0.13.2","component":"controller","heritage":"Tiller","release":"ingress-nginx"},"name":"ingress-nginx-nginx-ingress-controller","namespace":"ingress-nginx"},"spec":{"minReadySeconds":0,"revisionHistoryLimit":10,"template":{"metadata":{"annotations":{"checksum/config":"6341b8c0286e4d28ed45b77075d3c6fd2b35221473f2529fa3819d23e81bd20b"},"labels":{"app":"nginx-ingress","component":"controller","release":"ingress-nginx"}},"spec":{"containers":[{"args":["/nginx-ingress-controller","--default-backend-service=ingress-nginx/ingress-nginx-nginx-ingress-default-backend","--election-id=ingress-controller-leader","--ingress-class=nginx","--configmap=ingress-nginx/ingress-nginx-nginx-ingress-controller"],"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.12.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":10254,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"nginx-ingress-controller","ports":[{"containerPort":80,"name":"http","protocol":"TCP"},{"containerPort":443,"name":"https","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":10254,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{}}],"dnsPolicy":"ClusterFirst","hostNetwork":false,"nodeSelector":"node-role.kubernetes.io/ingress=true","serviceAccountName":"ingress-nginx-nginx-ingress","terminationGracePeriodSeconds":60}},"updateStrategy":{}}}
```

**What you expected to happen**: install successfully nginx chart with daemonset 

**How to reproduce it** (as minimally and precisely as possible):
* install cluster with kubespray (1.9.5) and helm support
* ```helm init --client-only```
* ```helm install stable/nginx-ingress --name ingress-nginx --set rbac.create=true --set controller.service.type=LoadBalancer --set controller.nodeSelector=node-role.kubernetes.io/ingress=true --set controller.service.nodePorts.http=80 --set controller.service.nodePorts.https=443  --set controller.kind=DaemonSet --namespace ingress-nginx```

**Comment by ams0** [comment]
Confirmed on 1.10 too.

**Comment by shurshun** [comment]
Confirmed on 1.10 too

**Comment by antonkovach** [comment]
The problem is with "--set controller.nodeSelector=node-role.kubernetes.io/ingress=true". It is not a bug because without this setting it works fine.
The possible solution is to use --set controller.nodeSelector."node-role\\\.kubernetes\\\.io/ingress"=true

The first issue was that the . (dot) was not escaped in the string properly. The second thing - as a suggestion - is to avoid using "true" as it is interpreted as a string and not as a boolean value. I usually do it like this. The simple existence (or non existence) of the label determines the "true" or "false" boolean value  for the nodeSelector. 

More information about the format limitation of --set in helm can be found at 
https://github.com/kubernetes/helm/blob/master/docs/using_helm.md On this page search for the string "nodeSelector" to find out more.

**Comment by wwyhy** [comment]
@chewdevs

**Comment by wwyhy** [comment]
@chewdevs 

I met same issue with controller.nodeSelector, How did you solved this?

I tried set a new label "master=true", the --set controller.nodeSelector.master=true does not work. 
and also tried @antonkovach's suggestion, it still does not work.

Thanks!

**Comment by wwyhy** [comment]
solved by --set nodeSelector."master"=true, but not --set controller.nodeSelector.master=true.
