### ISSUE TITLE
Requires indentation

### ISSUE THREAD

**Issue by jaredbischof** [helm/charts#5095]
The following lines in the deployment chart should be moved back one indentation as they are parameters of the readinessProbe field, not the httpGet field.

https://github.com/kubernetes/charts/blob/d170629cc67d25c8528152348f027d64a4763414/stable/grafana/templates/deployment.yaml#L107-L110

Without this change the chart failed to deploy in my environment.

**Comment by perryao** [comment]
I can confirm that this is an issue. @jaredbischof do you want to submit a PR?

**Comment by perryao** [comment]
Scratch that. here it is: https://github.com/kubernetes/charts/pull/5108
