### ISSUE TITLE
[stable/grafana] Documentation on default persistence values is incorrect

### ISSUE THREAD

**Issue by htuomola** [helm/charts#5102]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm 2.8.1, Kubernetes 1.9.6

**Which chart**:
stable/grafana

**What happened**:
Tried to enable persistence by setting `persistence.enabled: true` and `persistence.storageClass`.  Rest of the values seem to have sensible defaults according to the documentation. Helm install fails with:
```
Error: release grafana failed: PersistentVolumeClaim "grafana" is invalid: spec.resources[storage]: Invalid value: "0": must be greater than zero
```

**What you expected to happen**:
Resources are created successfully.

**How to reproduce it** (as minimally and precisely as possible):
Create values file with `persistence.enabled: true` and `persistence.storageClass: <valid class name>`. Run `helm install stable/grafana -f values.yaml --version 1.0.2`. I had also specified accessModes but that is not so relevant.

**Anything else we need to know**:
Seems that the values in values file are commented out but documentation mentions them as defaults. Probably should remove commenting from here: 
https://github.com/kubernetes/charts/blob/c720b399440a4b253a8dc92e6a2eb261b3db3742/stable/grafana/values.yaml#L62-L68

**Comment by southwolf** [comment]
@htuomola The problem is just as you described, if your try this you'll see it created successfully.
The default size is not set, but needed [here](https://github.com/kubernetes/charts/blob/9cb90e68204714bdebfc0c294281eab4cfb9d027/stable/grafana/templates/pvc.yaml#L22). A zero would come up when you didn't set the value.


`helm install stable/grafana --set persistence.enabled=true --set persistence.accessModes={ReadWriteOnce} --set persistence.size=8Gi -n grafana --namespace infrastructure`

**Comment by bibincatchme** [comment]
> @htuomola The problem is just as you described, if your try this you'll see it created successfully.
> The default size is not set, but needed [here](https://github.com/kubernetes/charts/blob/9cb90e68204714bdebfc0c294281eab4cfb9d027/stable/grafana/templates/pvc.yaml#L22). A zero would come up when you didn't set the value.
> 
> `helm install stable/grafana --set persistence.enabled=true --set persistence.accessModes={ReadWriteOnce} --set persistence.size=8Gi -n grafana --namespace infrastructure`

Yes its working, but why it's not fetching data from values.yml ?
Also the Persistent volume is deleted once I delete the Grafana helm
