### ISSUE TITLE
[incubator/keycloak] DB and Admin user secrets overwritten when upgrading

### ISSUE THREAD

**Issue by davoustp** [helm/charts#5129]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Version of Helm and Kubernetes**: Helm v2.8.2 , Kubernetes v1.10.0

**Which chart**: incubator/keycloak

**What happened**:

When using the chart-managed Postgres deployment, the Kubernetes secrets (for the administrator 'keycloak' user and password to connect to the Postgres DB) are generated again and overwritten when upgrading the chart.

As a result, the keycloak pods cannot connect to the database any more, because the password they get from the kube secret is different from the one registered by the DB engine during the initial startup.

The password to connect as a Keycloak admin is also lost and cannot be recovered from the kube secret.

**What you expected to happen**:

Once (and if) generated during the initial run, the secrets stored in Kube must be left alone and not overwritten. In other words, the secrets must be immutable as far as the chart is concerned.

**How to reproduce it** (as minimally and precisely as possible):

Install the chart:
`helm install --name keycloak incubator/keycloak`

Retrieve the secrets from Kube:
`kubectl get secret keycloak-postgresql -o jsonpath="{.data.postgres-password}" | base64 --decode; echo`
`kubectl get secret keycloak-keycloak-http -o jsonpath="{.data.password}" | base64 --decode; echo`

Upgrade the chart:
`helm upgrade keycloak --set keycloak.replicas=2 incubator/keycloak `

Retrieve the secrets from Kube: they have changed.

Looking at the keycloak logs shows connnection errors to the DB:
`kubectl logs keycloak-keycloak-0`

**Anything else we need to know**: -

**Comment by briantopping** [comment]
I'm not going to "maintain" this and assume it would be marked complete if it was resolved. Leaving this note for those that come afterwards...

**Comment by MarianSaeger** [comment]
As far as i can see, this is actually documented behaviour of the postgresql-Chart and can be circumvented by the correct configuration: https://github.com/helm/charts/tree/master/stable/postgresql#persistence

> Note: When using persistence ensure that you either provide a postgresPassword or use existingSecret, otherwise helm update will generate a new random password which is ignored by postgres. That will cause confusing behaviour especially if services depend on the secret

**Comment by davoustp** [comment]
Ok, it starts to make sense.
So when deploying with `keycloak.persistence.deployPostgres=true`, the keys such as `keycloak.persistence.existingSecret` are just ignored and we should drive the Postgres chart directly using the prefixed `postgres` properties, such as `postgresql.existingSecret`.

This is the actual meaning of the puzzling comment in various properties description below:
> (if deployPostgres=false)

Correct?

**Comment by MarianSaeger** [comment]
I can't tell for sure, as i'm not the maintainer, i'm afraid. I just experienced the same behaviour as described in this issue and wanted to add some insights. For my case, i solved it by explicitly specifying the same password for `keycloak.persistence.dbPassword` and `postgresql.postgresPassword`

**Comment by davoustp** [comment]
@MarianSaeger thanks a lot!
We will attempt what I described (using the included Postgres chart properties) and report back here.

**Comment by unguiculus** [comment]
This only applies to the Postgres chart. Keycloak is not affected. Anyways, I'd suggest you specify your own passwords to avoid the issue.
