### ISSUE TITLE
[couchdb] make ./etc/local.d persistent

### ISSUE THREAD

**Issue by joaocc** [helm/charts#5148]
BUG_REPORT

Kubernetes 1.9.6

Current chart (0.1.1) doesn't persist ./etc/local.d
check https://github.com/apache/couchdb/issues/1033

**Comment by joaocc** [comment]
When a new couchdb pod is restarted, the following content of ```./etc/local.d/local.ini``` is changed:
```
[admins]
adminacctname = -pbkdf2-THIS_CHANGES_EVERY_RESTART,10

[couchdb]
uuid = THIS_ALSO_CHANGES_EVERY_RESTART
```

**Comment by kocolosk** [comment]
Hi @joaocc thanks for this report. I intentionally configured `local.d` settings to not be persistent but maybe I didn't anticipate the right use cases here. I think the Helm-native way to set `[couchdb] uuid` consistently for all members of a StatefulSet would be to use the capability in values.yaml:

```
couchdbConfig:
  couchdb:
    uuid = THIS_WILL_BE_INHERITED_EVERYWHERE
```

The admin username and password can be defined similarly or can be inserted into a Secret as described here:

https://github.com/kubernetes/charts/blob/960eb5a/incubator/couchdb/values.yaml#L12-L26

All that being said, I can definitely see where it would be good to have custom configuration values for a particular member of a StatefulSet travel with the Pod when it gets re-scheduled. We should probably at least add the option to have local.d backed by a persistent volume.

**Comment by joaocc** [comment]
Thx for the suggestion. We hadn't thought of it before.

We ended up having the following:
* forking the docker image with some slight changes (https://github.com/apache/couchdb-docker/compare/master...hsz-devops:master) to prevent chmod/chown from dying (with ||true)
* local.d is backed by a persistent volume (in this case, a subfolder inside a volume)
* creating a customized version of the chart with some not-so-small changes, which include init-containers to initialize the local.d (mentioned above) only once, and deal with uid/guid (5894) issues.
* making sure we create a file starting with "zz" or something (`./etc/local.d/zzzz-writeable-configs.ini`) to be where couchdb writes it's config changes, as the current config file seemed to be overwritten everytime the container restarts, causing some non-trivial issues.

**Comment by kocolosk** [comment]
Thanks @joaocc. Can you say a little more about the UID / GUID issues? Are your updates to the chart posted somewhere so we can see what's appropriate to pull upstream?

**Comment by joaocc** [comment]
Sorry for not having answered before.
In case this is still relevant, pls check https://github.com/hsz-devops/apache--couchdb-docker.
Our changes were made to the 2.1.1 folder only (pls ignore the other folders as they have not received any updates).
Hope this helps
