### ISSUE TITLE
[stable/consul] Consul pods cannot connect to each other

### ISSUE THREAD

**Issue by luther7** [helm/charts#5152]
**Is this a request for help?**:

Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

Chart version 1.3.1.
Kubernetes version 1.9.1

**Which chart**:

stable/consul

**What happened**:

After deploying the chart, once all (three) pods started, Consul could not continue as the pods cannot connect to each other on port 8301.

```
2018/04/20 03:23:30 [INFO] agent: (LAN) joining: [consul-consul-1.consul-consul.consul.svc consul-consul-2.consul-consul.consul.svc]
    2018/04/20 03:23:30 [INFO] agent: (LAN) joined: 0 Err: 2 error(s) occurred:

* Failed to join 10.233.69.91: dial tcp 10.233.69.91:8301: connect: connection refused
* Failed to join 10.233.68.42: dial tcp 10.233.68.42:8301: connect: connection refused
    2018/04/20 03:23:30 [WARN] agent: Join LAN failed: <nil>, retrying in 30s
    2018/04/20 03:23:31 [ERR] agent: Coordinate update error: No cluster leader
    2018/04/20 03:23:55 [ERR] agent: failed to sync remote state: No cluster leader
    2018/04/20 03:23:59 [ERR] agent: Coordinate update error: No cluster leader
```

**What you expected to happen**:

Pods could communicate on port 8301.

**How to reproduce it** (as minimally and precisely as possible):

Deploy the chart.

**Anything else we need to know**:

**Comment by chrisleekr** [comment]
+1
