### ISSUE TITLE
[stable/mysql] Change Deployment strategy to 'recreate'

### ISSUE THREAD

**Issue by whereisaaron** [helm/charts#5154]
**FEATURE REQUEST**

**Version of Helm and Kubernetes**:

helm 2.8.2, k8s 1.8.11

**Which chart**:

stable/mysql

**What happened**:

Deployment doesn't specify a strategy, and so defaults to 'spec.strategy: rolling-update' which allows new pods to possibly overlap existing pods. But MySQL should not have two instances sharing the same files. So it seems better/important to specify the 'recreate' strategy.

**What you expected to happen**:

Expect Deployment templates to have 'spec.strategy: recreate'.

**Comment by whereisaaron** [comment]
/remove-lifecycle stale

Still an issue.

**Comment by whereisaaron** [comment]
This problem is still present in the MySQL chart 0.9.1 and is not fixed.

ref: @viglesiasce

**Comment by janario** [comment]
Created a PR https://github.com/helm/charts/pull/19201

But I can not reopen this one
