### ISSUE TITLE
Add NATS (gnatsd) helm charts

### ISSUE THREAD

**Issue by koalalorenzo** [helm/charts#5176]
---

**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Any

Is there any plan to add [NATS](https://nats.io) in the charts? What is the process in case I would like to contribute with a new chart? (I am currently reading the CLA 😀 ).

**Comment by unguiculus** [comment]
We're happy to accept a PR once you've signed the CLA.

Make sure you start off with `helm create` with the latest Helm version and follow our guidelines.
https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md
https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

**Comment by maxekman** [comment]
Info about NATS on Kubernetes:
- https://nats.io/documentation/tutorials/nats-kubernetes/
- https://github.com/pires/kubernetes-nats-cluster

**Comment by kevinfrommelt** [comment]
Looks like this issue can be closed. https://github.com/helm/charts/tree/master/stable/nats
