### ISSUE TITLE
[incubator/keycloak] Provide a way to override the keycloak.sh file

### ISSUE THREAD

**Issue by julianxhokaxhiu** [helm/charts#5222]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Version of Helm and Kubernetes**:
Helm v2.8.2
Kubernetes 1.8.10

**Which chart**:
incubator/keycloak

**What happened**:
At the current status I have a need to override the [keycloak.sh](https://github.com/kubernetes/charts/blob/master/incubator/keycloak/templates/configmap.yaml#L40) file in order to provide some custom scripts to be executed before keycloak starts. In a specific case, I need a trust store set, which for some reasons is not provided by default on the JBoss image.

**What you expected to happen**:
Would be nice if this script could be overridden through the chart values.yaml entry

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:
Feel free to approach me if you have any question.

**Comment by unguiculus** [comment]
Would it work for you if you can configure a script that can be run before `keycloak.sh`?

**Comment by julianxhokaxhiu** [comment]
Yes, that would work too. I just need an entry point before Keycloak starts. Thank you in advance.

**Comment by unguiculus** [comment]
Care to review?
#5372

**Comment by julianxhokaxhiu** [comment]
Awesome! Took a look at it now, and I really appreciate the features you added on it. Some of them actually was also in my radar, but you covered them already ( like the extraVolumes mount and the PodDisruptionBudget ).

Thank you, Really appreciated :) feel free to close this issue as soon as your PR gets merged!
