### ISSUE TITLE
Jenkins Master.InitScripts usage

### ISSUE THREAD

**Issue by angegar** [helm/charts#5248]
**Is this a request for help?**: Yes
I am trying to use the Jenkins Charts but i don't understand how to configure the plugins in using Master.InitScripts. Do you have an example ?

Thank you for your help.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by a1dutch** [comment]
in your values.yaml file just add one or more named init scripts under the InitScripts field

e.g. 

```yaml
InitScripts:
      credentials: |-
        import jenkins.model.*
        import com.cloudbees.plugins.credentials.*
        import com.cloudbees.plugins.credentials.common.*
        import com.cloudbees.plugins.credentials.domains.*
        import com.cloudbees.plugins.credentials.impl.*
        import com.cloudbees.jenkins.plugins.sshcredentials.impl.*
        import hudson.plugins.sshslaves.*;

        domain = Domain.global()
        store = Jenkins.instance.getExtensionList('com.cloudbees.plugins.credentials.SystemCredentialsProvider')[0].getStore()
        privateKey = new BasicSSHUserPrivateKey(CredentialsScope.GLOBAL,"jenkins-slave-key","root",new BasicSSHUserPrivateKey.UsersPrivateKeySource(),"","")
        store.addCredentials(domain, privateKey)
```

**Comment by angegar** [comment]
Thank you for your help. I don't really like this approach to push my script in a configMap file. Is there another way ?

**Comment by a1dutch** [comment]
Not without changes to the chart, helm seems to support putting these in files (https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/accessing_files.md) but not actually tried these functions.

**Comment by angegar** [comment]
Indeed i also found this syntax
```
 myfile: |
{{ .Files.Get "myfile.txt" | indent 2 }}
```
into the helm documentation : 
https://docs.helm.sh/chart_template_guide/#getting-started-with-a-chart-template
