### ISSUE TITLE
[stable/consul] Chart upgrade failed

### ISSUE THREAD

**Issue by asiragusa** [helm/charts#5267]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
Helm 2.8.2
GKE 1.8.9-gke.1

**Which chart**:
stable/consul

**What happened**:
```
$ helm upgrade consul stable/consul
Error: UPGRADE FAILED: StatefulSet.apps "consul-consul" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"release":"consul", "chart":"consul-1.3.5", "component":"consul-consul", "heritage":"Tiller"}: `selector` does not match template `labels`
```

**What you expected to happen**:
The chart to be upgraded

**How to reproduce it** (as minimally and precisely as possible):
Install an old release and try to upgrade

**Anything else we need to know**:
This is related to https://github.com/kubernetes/helm/issues/2494
The following line should be removed from the chart https://github.com/kubernetes/charts/blob/master/stable/consul/templates/consul-statefulset.yaml#L21

**Comment by maxfrigge** [comment]
Same here. How did you manage to resolve the issue @asiragusa ?

**Comment by asiragusa** [comment]
I didn't have the time to solve this issue still, but you can try to delete the chart and create it once again if you can tolerate downtime. Btw if you have time to create a PR to fix the chart I will appreciate it :)
