### ISSUE TITLE
Cant get PVC working with NFS provisioner

### ISSUE THREAD

**Issue by vtuson** [helm/charts#5271]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug (i think)

**Version of Helm and Kubernetes**:
helm v2.8.2
minikube 1.10 
**Which chart**:
nfs-server-provisioner

**What happened**:
tried in minikube and I cant get the sample PVC provisioned then create the PVC suggested.
The PVC is displayed as pending, doing describe on it says:

 16m		1m		268	{persistentvolume-controller }															Normal		ExternalProvisioningwaiting for a volume to be created, either by external provisioner "cluster.local/precise-pike-nfs-server-provisioner" or manually created by system administrator
  16m		1m		14	{cluster.local/precise-pike-nfs-server-provisioner precise-pike-nfs-server-provisioner-0 5dc91f81-4965-11e8-b4f7-0242ac110009 }			Normal		Provisioning		External provisioner is provisioning volume for claim "default/test-dynamic-volume-claim"
  16m		1m		14	{cluster.local/precise-pike-nfs-server-provisioner precise-pike-nfs-server-provisioner-0 5dc91f81-4965-11e8-b4f7-0242ac110009 }			Warning		ProvisioningFailed	Failed to provision volume with StorageClass "nfs": error getting NFS server IP for volume: error getting service SERVICE_NAME=nfs-server-provisioner in namespace POD_NAMESPACE=default

**What you expected to happen**:
PVC to be provisioned

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/nfs-server-provisioner --set persistence.enabled=true,persistence.size=20Gi
kubectl create -f PVC --> pvc contains example displayed

**Anything else we need to know**:

**Comment by Flowkap** [comment]
You need to provide the nfs providers storage class. default is not working for me either!

**Comment by vtuson** [comment]
@Flowkap my issue was due to the statefulset being given the wrong service name to look up the ip address. I submitted a small fix

**Comment by kiall** [comment]
Thanks @vtuson - I must have missed that in the original PR ... I suspect this can be closed now?

**Comment by amir-hadi** [comment]
@kiall @vtuson I still experience this issue when I deploy the nfs-server-provisioner chart with more than one replica. Do you have an idea why this might be the case?

**Comment by horsen689** [comment]
me too，so  tired

**Comment by bansalrajat** [comment]
any update on this issue?
