### ISSUE TITLE
Prometheus does not support Role and RoleBindings

### ISSUE THREAD

**Issue by derekbassett** [helm/charts#5276]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE

**Version of Helm and Kubernetes**: Helm 2.8.2 Kubernetes 1.9.2

**Which chart**: prometheus

**What happened**: I'm a tenet on a Bare Metal Cluster of Kubernetes.  I'm using Prometheus to monitor my software inside a single Namespace.  My account has not been given permission to create Cluster Roles/Cluster Role Bindings but can generate Roles and Role Bindings.

**What you expected to happen**: I would like to have the ability to use Roles and Role Bindings instead of Cluster Role and Cluster Role Bindings.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I will try and generate a PR capturing the work I have done.

**Comment by David-Ray1** [comment]
I have also hit this problem. I worked around it by disabling rbac and adding Role and RoleBindings to the promethues helm chart and I then had to add a extra job to scrape metrics on a given namespace. This meant I had to copy the prometheus helm chart and make changes directly, so Prometheus supporting Role and Rolebindings would be much nicer.
