### ISSUE TITLE
[stable/fluent-bit] Unable to send logs to an open AWS elasticsearch cluster

### ISSUE THREAD

**Issue by ghost** [helm/charts#5278]
**Is this a request for help?**:
Request/Bug
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Version of Helm and Kubernetes**:
Helm: 2.8.2
Kubernetes 1.8.7

**Which chart**:
stable/fluent-bit

**What happened**:
Attempt to use es backend type to send logs to an AWS backed elasticsearch cluster.
Upon filling in the values, the pods created outport no logs 
`backend:
  type: es
  forward:
    host: fluentd
    port: 24284
  es:
    host: URL_OF_ELASTICSEARCH_CLUSTER
    port: 443
    # Elastic Index Name
    index: kubernetes_cluster
    type: flb_type
    logstash_prefix: kubernetes_cluster
    # Optional username credential for Elastic X-Pack access
    http_user:
    # Password for user defined in HTTP_User
    http_passwd:
    # Optional TLS encryption to ElasticSeaarch instance
    tls: off
    tls_verify: on
    # TLS certificate for the Elastic (in PEM format). Use if tls=on and tls_verify=on.
    tls_ca: ""
    # TLS debugging levels = 1-5
    tls_debug: 1
`
**What you expected to happen**:
I would expect the logs to forward to my ES cluster

**How to reproduce it** (as minimally and precisely as possible):
Install chart with es as backend type and point host to an AWS ES cluster

**Anything else we need to know**:
ES cluster is currently set to open access policy, so it cannot be an IAM issue, and I would expect there to be error logs at the very least

**Comment by pharindoko** [comment]
Hey,
I have the same issue.
Did you solve it or do you have a clue what‘s wrong ?
