### ISSUE TITLE
Chart specific labels for isuess in the repo

### ISSUE THREAD

**Issue by wclr** [helm/charts#528]
I think it is reasonable to add labels to be able to classify each issue to what chart it refers.

**Comment by seanknox** [comment]
Closing in favor of issues template submitted here: https://github.com/kubernetes/charts/pull/1155

**Comment by wclr** [comment]
What issue request template has to with labels? Labels are very useful, it makes everything more visually observable, you can filter by labels, for example to get all issues related to partcular chart, how would you do this without lables? Labels usually assigned not by issue author, but by owners/collaborators, so users will not mess with them.

Not using labels for monorepos and complex project is a very big omission.
