### ISSUE TITLE
[stable/traefik]: Insufficient permissions to use ingress on K8s v1.10

### ISSUE THREAD

**Issue by seamusfoley** [helm/charts#5310]
BUG REPORT

**Version of Helm and Kubernetes**:
Helm v2.8.2
Kubernetes v1.10
Running in Minikube

**Which chart**:

stable/traefik

**What happened**
Installing from helm in default namespace.

```
helm init
helm install --name=traefik --set dashboard.enabled=true,dashboard.domain=traefik-ui.minikube dashboard.enabled stable/traefik
echo "$(minikube ip) traefik-ui.minikube" | sudo tee -a /etc/hosts
```  
Results in 404 when accessing traefik-ui.minikube:\<NodePort\>.

Running
```
kubectl logs pod <traefik pod name>
```
results in
```
Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User "system:serviceaccount:default:default" cannot list ingresses.extensions at the cluster scope
```

**What you expected to happen**:

Accessing traefik-ui.minikube:\<NodePort\> to return dashboard ui

**How to reproduce it** 

```
helm init
helm install --name=traefik --set dashboard.enabled=true,dashboard.domain=traefik-ui.minikube stable/traefik
echo "$(minikube ip) traefik-ui.minikube" | sudo tee -a /etc/hosts
```  
Access traefik-ui.minikube:\<NodePort\>

**Comment by russellseymour** [comment]
Hello @seamusfoley , I too had this issue the other day.

I solved it by adding `rbac.enabled=true` to the parameters when running the helm install command. This then creates the necessary account that Traefik needs to run in the `kube-system` namespace.

Hope this helps.

**Comment by seamusfoley** [comment]
Thanks. That's worked a treat

**Comment by krancour** [comment]
Did minikube recently start enabling RBAC by default? That would explain this.

At any rate. Sounds like you are all set, so I am closing.

/close

**Comment by framled** [comment]
I have the exactly same problem but with `rbac.enabled = true`

`v1.Service: services is forbidden: User "system:serviceaccount:kube-system:traefik-ingress"`

**Comment by krancour** [comment]
Have you done a debug/dry-run to verify things are configured as you think they are?

**Comment by framled** [comment]
No, but i just apply
```bash
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
```

and now, works great.
