### ISSUE TITLE
PersistentVolumeClaim is not bound: "prometheus-server"...AttachVolume.Attach failed for volume "pvc-...Error attaching EBS volume \"vol-...to instance "i-...since volume is in "creating" state \ Back-off restarting failed container \ POD Status: Waiting: CrashLoopBackOff

### ISSUE THREAD

**Issue by vadimprt** [helm/charts#5313]
**Is this a request for help?**:

yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by JayBee6** [comment]
@vadimprt I am getting the same error have you managed to fix this?
