### ISSUE TITLE
[incubator/jaeger] Retire old data for Elasticsearch backend

### ISSUE THREAD

**Issue by aleerizw-zz** [helm/charts#5317]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST
Currently the chart does not include a way to automatically retire old data for the elasticsearch backend. I found the clean script for ES backend:

https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/esCleaner.py

Can this be added as a cronjob in the chart if the backend is set to elasticsearch?
A docker is already created for the script:
https://hub.docker.com/r/jaegertracing/jaeger-es-index-cleaner/
**Which chart**:
incubator/jaeger

**Anything else we need to know**:
Please let me know if this is something that can be supported and I will try to add the support in the chart.

**Comment by aleerizw-zz** [comment]
@pavelnikolov @mikelorant Please let me know what you think

**Comment by cliedeman** [comment]
@aleerizw Have you looked at [curator](https://github.com/elastic/curator)? But this most likely belongs in the elasticsearch chart

**Comment by pavelnikolov** [comment]
@aleerizw you can just have [daily indices](https://www.elastic.co/guide/en/elasticsearch/guide/current/time-based.html) and have a cronjob that deletes them after a given period of time... You might as well be interested in this article about [rolling indices](https://www.elastic.co/blog/managing-time-based-indices-efficiently).
I agree with @cliedeman  that most probably this needs to be added to the Elasticsearch chart. I guess each team is using different tools to maintain their data. This is a very specific solution. Some teams might want to archive the data before deleting it or generate some analytics/dependency graphs out of it.

**Comment by aleerizw-zz** [comment]
Yeah that makes sense. I will close the issue.
