### ISSUE TITLE
mongodb-replicaset: Access it from within the Cluster

### ISSUE THREAD

**Issue by blissi** [helm/charts#5319]
Hallo,
I installed the mongodb-replicaset, but there is no cluster IP address on the service. How would one connect to it from another application within the cluster?

Thanks,
Steven

**Comment by unguiculus** [comment]
It's a headless service governing the statefuleset, thus no cluster ip. You need to construct a connect string containing urls to all replicas (pods). You don't access it via service. Check the MongoDB docs for connecting to a replica set:

https://docs.mongodb.com/manual/reference/connection-string/

**Comment by blissi** [comment]
Thanks, got it!
