### ISSUE TITLE
[stable/etcd-operator]: Error: apiVersion "etcd.database.coreos.com/v1beta2" in templates/etcd-cluster-crd.yaml is not available

### ISSUE THREAD

**Issue by gopinatht** [helm/charts#5328]
**Is this a request for help?**: No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm version: v2.8.2
Kubernetes version: v1.9.2+coreos.0

**Which chart**:
etcd-operator

**What happened**:
When using etcd-operator as a sub-chart in a custom chart, I get this error during install:
```Error: apiVersion "etcd.database.coreos.com/v1beta2" in voltha/charts/etcd-operator/templates/etcd-cluster-crd.yaml is not available``` 
I tried looking for info on this error and found this [bug](https://github.com/kubernetes/charts/issues/2360). But it is light on detail about what the actual problem is.
I found a less than ideal solution by installing my helm chart with this etcd variable set to false first: `--set etcd-operator.customResources.createEtcdClusterCRD=false`
I then delete the helm release and re install it by setting it to true
For some reason when this variable is set to false, somehow the `v1beta2` api version becomes available

**What you expected to happen**:
etcd-operator installs without errors.

**How to reproduce it** (as minimally and precisely as possible):
- Make etcd-operator a subchart to a custom helm chart
- Assuming you name the subchart `etcd-operator`, set the `etcd-operator.customResources.createEtcdClusterCRD=true` in your custom helm chart values.yaml file.
- `helm install <custom-chart>`

**Anything else we need to know**:
Etcd-operator Chart version: 0.7.3

**Comment by gopinatht** [comment]
Hey Guys, any news on this? We are really stuck with this problem

**Comment by gopinatht** [comment]
@alejandroEsc Any insights into this issue? Any help appreciated.

**Comment by alejandroEsc** [comment]
Oh ill have to double check, could be that internally CRDs are created and we may no longer need to create the resource or it could be causing a conflict.

**Comment by gopinatht** [comment]
@alejandroEsc Thanks! Does the operator need to be created before CRD resource?

**Comment by alejandroEsc** [comment]
Thats partially what will have to be checked. Could be that we no longer need these CRDs, or we have to create them in the right order.

**Comment by gopinatht** [comment]
@alejandroEsc FWIW, I tried the steps to create RBAC and Operator as mentioned [here](https://github.com/coreos/etcd-operator/blob/master/doc/user/install_guide.md):
- `example/rbac/create_role.sh`
- `kubectl create -f example/deployment.yaml`

I then ran the command `kubectl api-versions` and I am able to see `etcd.database.coreos.com/v1beta2` in the list. I also ran `kubectl get customresourcedefinitions` as suggested in that doc and see this:

```
NAME                                    AGE
etcdclusters.etcd.database.coreos.com   3m
```

So I think you are right. We might not need the CRD.

**Comment by alejandroEsc** [comment]
@gopinatht will try to get something solid for you by the end of this week. Feel free to ping me/email me if you want.

**Comment by gopinatht** [comment]
@alejandroEsc Do you have any updates? While I see CRD created with `v0.9.2` version of the operator container, we still need the CRD service for this helm chart to work. So it is definitely an ordering issue.

**Comment by gopinatht** [comment]
The operator deployment has to come before the CRD deployment

**Comment by alejandroEsc** [comment]
Hey there, sorry havent responded, a few deadlines here are keeping me
busy. Should be ready to get at this in the coming week. Sorry about the
delay :/

**Comment by alejandroEsc** [comment]
@gopinatht working on it. Yes seems to be an ordering issue, trying to address it.

**Comment by alejandroEsc** [comment]
fyi https://github.com/kubernetes/helm/issues/2994

**Comment by alejandroEsc** [comment]
Ok i believe the problem is solved now. Had to use pre-install hooks on deployments but i think that takes care of it. PR with additional small changes coming up in a bit.

**Comment by alejandroEsc** [comment]
@gopinatht please let me know if this fixes things on your end, thanks!

**Comment by gopinatht** [comment]
Hi @alejandroEsc Many thanks for looking at this. I think this is a reasonable solution. One thing to keep in mind though is that with helm hooks, they do not participate in versioning or lifecycle management of resources by helm. i.e., once installed, `helm delete` will not delete the etcd operator as it is installed as a helm hook now. 

We will have to delete it manually using kubectl or jump through some other hoops like creating another job app that runs as post delete hook that manually uninstalls the pre-install hooks.

**Comment by alejandroEsc** [comment]
@gopinatht yep. may have to update the readme docs, for now this seems to be the only solution that makes sense to me though. In the meantime ill consider if other options are avaialble.

**Comment by alejandroEsc** [comment]
@gopinatht  Would you prefer to have the crds run in post hooks, that cleanup may be easier?

**Comment by alejandroEsc** [comment]
So I have instead chosen to do the hooks on the CRDs since these are more sample CRDs than anything else and it would be advised to create your own anyway. In that case the functionality of installing and deleting the operator with default values is preserved.

**Comment by gopinatht** [comment]
@alejandroEsc Thanks for asking. I am ambivalent either way but I do slightly prefer the operator being the hook than the CRD. That way when we upgrade or change the CRD, it is tracked and managed. 

Stepping back a little, the crux of the issue is that we need to install the operator without the CRD first and then the CRD itself. i.e.,
- `helm install -n etcdOp --set customResources.createEtcdClusterCRD=false stable/etcd-operator`
- `helm upgrade --set customResources.createEtcdClusterCRD=true etcdOp stable/etcd-operator` 

If we can find a way to automate the `upgrade` step to happen after the install step, our problem is solved. I remember reading somewhere vaguely that this is possible but for the life of me, I am not able to find that documentation for it.

**Comment by alejandroEsc** [comment]
So for now at least you are unblocked and can proceed to create the operators as needed. Second, what do you mean by automate? You could write a script that does these sequentially checking each step if a non-zero return value is obtained. But maybe you mean something that helm could do itself?

**Comment by gopinatht** [comment]
Yeah, when I was first learning about helm, I remember reading that helm itself allows us to run upgrade automatically after install. Maybe I was hallucinating. 

Thanks for your effort by the way. I really do appreciate it.

**Comment by alejandroEsc** [comment]
i just read something about that, but may not be what you think, hmm ill check and get back to you asap.

**Comment by gopinatht** [comment]
Hi @alejandroEsc, can you point me to what you are reading?

**Comment by alejandroEsc** [comment]
@gopinatht i saw this issue https://github.com/kubernetes/helm/issues/3353 and looked up https://docs.helm.sh/helm/#helm-upgrade with the install flag, havent tried it, have you?
