### ISSUE TITLE
[Feature request] Allow custom volumeMounts in elasticsearch chart

### ISSUE THREAD

**Issue by jtschulz** [helm/charts#5331]
In order to use the GCS storage backend for snapshots, ES can use a credentials.json file (we'd rather not use the default service account if we can avoid it) to authenticate with the service account, [as described here](https://www.elastic.co/guide/en/elasticsearch/plugins/5.4/repository-gcs-repository.html). The chart currently exposes no straightforward way to add a volumeMount to the container spec. If you're amenable to this, I would be happy to produce a PR to support this feature.

Thank you!

**Which chart**:
[elasticsearch v0.4.9](https://github.com/kubernetes/charts/tree/master/incubator/elasticsearch)

**Comment by jtschulz** [comment]
cc: @simonswine @icereval If you're interested in supporting this, it's something I'd be happy to work on.

**Comment by PepperTeasdale** [comment]
Bump on this. Are @simonswine and @icereval still maintaining the ES chart?
