### ISSUE TITLE
[stable/mongodb-replicaset] Unable to scale down my replica.

### ISSUE THREAD

**Issue by kgujral** [helm/charts#5353]
Hi Guys,

I am unable to scale down my replica. I initially created a mongodb-replicaset with 4 replicas. Then I used `helm upgrade mongo stable/mongodb-replicaset --reuse-values --set replicas=2 --version 3.0.0` to scale down to 2 replicas. It successfully terminated my 2 pods (`mongo-mongodb-replicaset-2` and `mongo-mongodb-replicaset-3` were terminated) but none of the pods were master anymore. Running `for ((i = 0; i < 2; ++i)); do kubectl exec --namespace default mongo-mongodb-replicaset-$i -- sh -c 'mongo --eval="printjson(rs.isMaster())"'; done` still displayed the old 4 pods in hosts config.
```
"hosts" : [
		"mongo-mongodb-replicaset-0.mongo-mongodb-replicaset.default.svc.cluster.local:27017",
		"mongo-mongodb-replicaset-1.mongo-mongodb-replicaset.default.svc.cluster.local:27017",
		"mongo-mongodb-replicaset-2.mongo-mongodb-replicaset.default.svc.cluster.local:27017",
		"mongo-mongodb-replicaset-3.mongo-mongodb-replicaset.default.svc.cluster.local:27017"
	],
```

Is there something I'm missing ??

**Comment by jamesholcomb** [comment]
I'm experience the same issue trying to scale from 3 to 1

````
helm upgrade db stable/mongodb-replicaset \
  --reuse-values \
  --set replicas=1 \
  --version 2.1.5
````

It scales down to replicaset-0 but it's a secondary (it was the primary before scaling down).

Scaling back up to 3 is fine and `0` becomes the primary again.

**Comment by kgujral** [comment]
I'm facing the same issue. Forced to run a replica of 3 as of now. Let me know too in case you find a solution @jamesholcomb.
Thanks
