### ISSUE TITLE
minio charts uses image tag latest.

### ISSUE THREAD

**Issue by sebgoa** [helm/charts#536]
I thought the best practice was to put a real semver number for the image tag.

The minio chart uses :latest as a tag.

I think we should point to a specific tag.

**Comment by viglesiasce** [comment]
I agree. @NitishT can you make that happen?

**Comment by nitisht** [comment]
Thanks @viglesiasce @sebgoa I will change the default.

**Comment by nitisht** [comment]
Update https://github.com/kubernetes/charts/pull/534 with fix for this.
