### ISSUE TITLE
[stable/traefik] ACME wildcard certificate support

### ISSUE THREAD

**Issue by farfeduc** [helm/charts#5379]
**Is this a request for help?**:
Yes
---

**FEATURE REQUEST**:
I want support of wildcard certificates as described in traefik documentation here : https://docs.traefik.io/v1.6/configuration/acme/#wildcard-certificates
I think the modifications are not that complicated (bump traefik version + add optional values in configmap template).

**Version of Helm and Kubernetes**:
Helm v2.9.0
Kubernetes v1.9.6
On-premise install

**Which chart**:
stable/traefik

**What you expected to happen**:
Be able to set the acme.domains.main option as detailled in traefik 1.6 documentation for wildcard certificate generation.

**Anything else we need to know**:
I have done a fork : https://github.com/farfeduc/charts with some modification that might resolve the issue but as I created a new pull request I became overwhelmed with the requirements. 
So instead I thought it would be better to fill an issue with some work already done to ask if my modifications are correct.

@krancour If you have some time I would really appreciate some pointers on what I might have done wrong 😄  Thanks in advance.

**Comment by krancour** [comment]
@farfeduc I made a few comments on the last commit to your fork.
