### ISSUE TITLE
best way to update the minio config.json 

### ISSUE THREAD

**Issue by sebgoa** [helm/charts#538]
HI,

The minio charts, sets the keys to access the server, but there are other configurations that one may want to change. The configmaps does not represent the complete config.json that we could customized.

So what is the best way to change the config of a running release of the minio chart ?

cc/ @NitishT

**Comment by nitisht** [comment]
Hey @sebgoa 

Can you please elaborate the Minio settings that you'd like to customize? 

I can help you add the configuration and if useful enough, we can add it to the official chart itself. Also, Minio server reads the config during startup, so for any config changes to be effective the pods need to be restarted. 

cc @harshavardhana

**Comment by sebgoa** [comment]
I would like to be able to turn on the kafka notification.

I was expecting the config.json to be defined as a configmap. but it looks like the keys are stored in a secret and loaded as env variables automatically when minio server starts.

**Comment by sebgoa** [comment]
and yes I understand the pod would need to be restarted, but the config.json is not stored in a configmap...

**Comment by harshavardhana** [comment]
> and yes I understand the pod would need to be restarted, but the config.json is not stored in a configmap...

Thanks for the heads up we will explore this @sebgoa

**Comment by nitisht** [comment]
Updated https://github.com/kubernetes/charts/pull/534 with fix for this. @sebgoa please take a look.

**Comment by devth** [comment]
Minio's `region` attribute also needs to be parameterized / settable via `--set`.

**Comment by lachie83** [comment]
Closing. Please submit a PR for setting the region
