### ISSUE TITLE
[stable/rabbitmq] no longer works on k8s 1.5--1.7 because apps/v1beta2 StatefulSet is not available

### ISSUE THREAD

**Issue by thomas-riccardi** [helm/charts#5388]
**Is this a request for help?**: no

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

**Which chart**:
stable/rabbitmq 0.8.1

**What happened**:

```
Error: apiVersion "apps/v1beta2" in rabbitmq/templates/statefulset.yaml is not available
```

**What you expected to happen**:
Successful `helm install`.

**How to reproduce it** (as minimally and precisely as possible):
Install stable/rabbitmq chart verson 0.8.1 on k8s 1.7

**Anything else we need to know**:

Since #4591 the stable/rabbitmq chart uses StatefulSet instead of Deployment. This is available in beta since k8s 1.5 (via `apps/v1beta1`, see https://v1-5.docs.kubernetes.io/docs/concepts/workloads/controllers/statefulset/).
- #4591 used `apps/v1`, which requires k8s >=1.9, this issue was reported by #4908 
- #4909 switched to use `apps/v1beta2`, which  requires k8s >=1.8.

In this issue I propose to use `Capabilities.APIVersions.Has` to support k8s >=1.5 and still use the latest available apiVersion.

Use-case: redhat openshift 3.9 (~k8s 1.9) was only released ~1month ago, and the previous version is 3.7 (~k8s 1.7): there is no `apps/v1beta2`.

I can work on a PR to implement that if my proposal is accepted.

**Comment by thomas-riccardi** [comment]
The readme is outdated too: https://github.com/cheyang/charts/tree/master/stable/rabbitmq#prerequisites
> Kubernetes 1.4+ with Beta APIs enabled

**Comment by mattjmcnaughton** [comment]
That sounds like a good plan to me (although I'm not a maintainer on the chart or anything...). I see a similar strategy in use in other parts of the code base. Happy to serve as a reviewer if you want :)

**Comment by mattjmcnaughton** [comment]
(Also happy to do a pr if you're too busy :) - I know its been a while since you originally filed the issue!)

**Comment by thomas-riccardi** [comment]
@mattjmcnaughton It's not my priority; I probably won't work on it in the coming weeks. So feel free to do the PR yourself !

**Comment by mattjmcnaughton** [comment]
Sounds good!

**Comment by thomas-riccardi** [comment]
@mattjmcnaughton in this issue description I proposed to support kubernetes 1.7 as it is easy to do and useful for redhat openshift users. I assumed you'd support kubernetes 1.7 and not just update the requirements...

Could someone re-open this issue?

**Comment by mattjmcnaughton** [comment]
@thomas-riccardi my mistake, I apologize! I'd spoken with a couple members of the project about how helm only technically supports the latest, and second-to-latest k8s versions. But I didn't realize the openshift component. Apologies!

**Comment by mattjmcnaughton** [comment]
@prydonius are you ok with falling back to an older api if the previous one doesn't exist?

@timstoop also, who I think is pretty familiar with how version upgrades are typically handled.

Thanks all :) If all is good with this plan, happy to make a pr.
