### ISSUE TITLE
[stable/rabbitmq] add back `rabbitmq.vhost` value

### ISSUE THREAD

**Issue by thomas-riccardi** [helm/charts#5394]
**Is this a request for help?**: no

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

Since #4591 the stable/rabbitmq changed values: de-flattened them, and dropped some:
- `rabbitmqNodeType`
- `rabbitmqNodeName`
- `rabbitmqClusterNodeName`
- `rabbitmqVhost`

In exchange, it added `rabbitmq.configuration` which can define any `rabbitmq.conf` config.

**Issue**:
`rabbitmqVhost` was useful as a value: although we can now apply it via `rabbitmq.configuration`, we cannot access its value anymore from templates.
Use-case: a template that generates the full amqp URI:
```
{{/*
Create RabbitMQ URL. Requires some rabbitmq chart Values setting (some defaults are missing)
*/}}
{{- define "vesta.rabbitmq.url" -}}
{{- $hostname := include "vesta.rabbitmq.fullname" . -}}
{{- with .Values.rabbitmq -}}
    {{- $username := .rabbitmqUsername -}}
    {{- $password := required ".Values.rabbitmq.rabbitmqPassword is required" .rabbitmqPassword -}}
    {{- $port := int .rabbitmqNodePort -}}
    {{- printf "amqp://%s:%s@%s:%d/" $username $password $hostname $port | quote -}}
{{- end -}}
{{- end -}}
```
This worked great with 0.6.x chart, but cannot be ported to 0.8.x, unless if we define the vhost both in `rabbitmq.configuration` and in a new value only used by this template and not the rabbitmq template: `rabbitmq.vhost`.

**Proposed action**:
- Add back vhost config at `rabbitmq.vhost`, with default value `/`
- Not sure about the other disappeared values: I don't use them
- This should be a retro-compatible change: rabbitmq.conf supports 2 definitions of the same key: it takes the last one into account
- This is a new feature: should bump semver minor, but since we have major=0 I'm not sure what to do: bump patch?

I can write a PR with that if the maintainers are OK with my proposal.

**Comment by yurrriq** [comment]
I'd like vhost back too.

**Comment by yurrriq** [comment]
Is there a PR for this?

**Comment by macropin** [comment]
Yes, why was this removed?! Please add it back.

**Comment by macropin** [comment]
Oh great!

**Comment by thomas-riccardi** [comment]
:/
How do we reopen the issue?

We can't just add back the `RABBITMQ_VHOST` env var (see https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/README.md#environment-variables) (see #8901) : 
#4591 skips the default bitnami command from the bitnami rabbitmq docker image, resulting in most of the bitnami env vars being ignored. 
Some features are re-implemented one by one in the ever increasing `command` (#8140, #8337 ..):
https://github.com/helm/charts/blob/a5f1edeef2029baa00bd1c577a805139a14e7e77/stable/rabbitmq/templates/statefulset.yaml#L57-L77

More generally, do we really want to go down that road and re-implement the bitnami features in `command`? If we do, maybe we don't need to use the bitnami docker image.


A (not yet tested) workaround may be to add `default_vhost` to `rabbitmq.configuration` value (this is not great as we can't easily append configuration without duplicating the default value which is not future-proof...).

ping (some) chart maintainers @desaintmartin @carrodher @juan131

**Comment by wayne-o** [comment]
This stale bot seems to be a complete pain! Also - is there a work around for this yet?
