### ISSUE TITLE
mino make bucket job crashloop

### ISSUE THREAD

**Issue by cehoffman** [helm/charts#5403]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:
1.8.9

**Which chart**:
stable/minio

**What happened**:
Fails to install due to crashlooping make bucket job due to missing initialize script.

**What you expected to happen**:
Successful deployment with created bucket.

**How to reproduce it** (as minimally and precisely as possible):
Install chart with an autocreated bucket

**Anything else we need to know**:
This was broken in #4277 when the configmap holding the initialize script was removed.

**Comment by csvn** [comment]
Nice! Saw that a fix has been merged for this issue. Any idea when a patch with this fix will be released?

**Comment by jspiro** [comment]
@csvn Do we know that it wasn't released, know where it is released? Unsure if we're seeing the same issue; we see a `stat` of `/exports/bucket` which doesn't exist. But we are able to upload files, and the bucket does exist. My guess is the default bucket isn't created at the mount point.

**Comment by csvn** [comment]
@jspiro If I run the following bash command with the below configuration, the "create bucket" job will fail.

```bash
helm upgrade -i --namespace test -f minio-config.yml minio stable/minio
# => Release "minio" does not exist. Installing it now.
# => Error: timed out waiting for the condition
```

```yaml
// minio-config.yml
persistance:
  size: 20Gi
defaultBucket:
  enabled: true
service:
  clusterIP: ""
```
![image](https://user-images.githubusercontent.com/8770194/41144612-c6ef7d1a-6afd-11e8-8d5f-f9d102d05d24.png)

If I remove the `defaultBucket.enabled`, it deploys without issues. The linked PR and the descriptions above made it seem likely this was the same issue.

Though it seems [this fix should have been released 14 days ago](https://github.com/kubernetes/charts/commits/master/stable/minio/Chart.yaml) (before my post) according to git history for `Chart.yaml`...

Maybe I missed something in my config *\*shrugs\*.*

**Comment by csvn** [comment]
My bad, I had missed doing `helm update`, so I think I was running an old version of this chart. Just made a deployment that worked correctly with `defaultBucket.enabled: true`
