### ISSUE TITLE
[stable/prometheus]  prometheus-server configmap is not generated properly

### ISSUE THREAD

**Issue by HaveFun83** [helm/charts#5423]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.9.0"
Server: &version.Version{SemVer:"v2.9.0"
```
K8s 1.10.0

**Which chart**:
stable/prometheus

**What happened**:
prometheus-server configmap is not generated properly which crashloopback the prometheus-server pod
```
`level=error ts=2018-05-07T15:38:57.406070309Z caller=main.go:582 err="Error loading config couldn't load configuration (--config.file=/etc/config/prometheus.yml): parsing YAML file /etc/config/prometheus.yml: yaml: line 160: mapping values are not allowed in this context"`

```
The prometheus-server config-map looks so
```
....
        target_label: kubernetes_pod_namealerting:
      alertmanagers:
      - kubernetes_sd_configs:
....
```
but it should look so
```
....
        target_label: kubernetes_pod_name
    alerting:
      alertmanagers:
      - kubernetes_sd_configs:
....
```

**What you expected to happen**:
The config-map should generated properly and start the Prometheus server without issues

**How to reproduce it** (as minimally and precisely as possible):
`helm install stable/prometheus`

**Anything else we need to know**:

**Comment by chetanv-oi** [comment]
I can confirm - I get exactly the same error

**Comment by mdgreenwald** [comment]
https://github.com/kubernetes/charts/issues/5425

I'm getting the same thing.

**Comment by HaveFun83** [comment]
@mdgreenwald  Thanks for the PR. Hope this will be fixed soon.
Close this now. Please continue the discussion here: #5425
