### ISSUE TITLE
Kafka & Zookeeper Stateful Sets don't use anti-affinities by default (resulting in pod-node overlap)

### ISSUE THREAD

**Issue by alexvicegrab** [helm/charts#5426]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm v2.9.0
Kubernetes 1.9.6

**Which chart**:
Kafka & ZooKeeper

**What happened**:
There are no anti-affinities defined on either Kafka or Zookeeper, which is problematic, since I end up having multiple Zookeeper and/or Kafka instances on the same node.

**What you expected to happen**:
I'd expect that by default all Kafka and Zookeeper instances would end up on different nodes (by making use of anti-affinities).

**How to reproduce it** (as minimally and precisely as possible):
Just install the default Kafka Helm Chart.

**Anything else we need to know**:
No

**Comment by ghost** [comment]
See: https://github.com/kubernetes/charts/pull/4931

In general, flexibility in affinity definition is a good thing.  I for instance like to anti-affine by both Availability Zone as well as Node.

**Comment by alexvicegrab** [comment]
Fair point, the current state of my pull request is to add some commented examples of typical antiAffinities and affinities (all Kafka pods on separate nodes, but attempt to collocate with a Zookeeper node where possible)

**Comment by alexvicegrab** [comment]
P.S. @josdotso, nice pull request. I also updated the Zookeeper and Kafka charts in mine a bit, but have been using a consistent "include" rather than "template" (which are a bit mixed in the original chart), since it appears to be the recommended way:

https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/named_templates.md

**Comment by ghost** [comment]
Thanks @alexvicegrab  .. My ZK PR merged earlier today.  In the next week, I'll PR similar advancements (where gap exists) to Kafka.

**Comment by alexvicegrab** [comment]
Great, @josdotso I look forward to your updated Kafka chart!
