### ISSUE TITLE
Updating cluster size for incubator/cassandra fails

### ISSUE THREAD

**Issue by vatsalshah1990** [helm/charts#5431]
**Version of Helm and Kubernetes**:
1.9.6-gke.1

**Which chart**:
incubator/cassandra

**What happened**:

Running the following command fails:
`helm upgrade --set config.cluster_size=5 cassandra incubator/cassandra`

`Error: UPGRADE FAILED: StatefulSet.apps "cassandra" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.`

**What you expected to happen**:

Increase/Decrease the cluster size with the specified number of nodes

**How to reproduce it** (as minimally and precisely as possible):

Run the following command post successful deployment of incubator/cassandra with 3 node cluster:
`helm upgrade --set config.cluster_size=5 cassandra incubator/cassandra`

**Anything else we need to know**:

**Comment by karthimohan** [comment]
I created the cluster by setting the persistence.storageClass. So when i scale up the cluster i had to pass that as well 

helm install --namespace "cassandra" -n "cassandra" incubator/cassandra --set persistence.storageClass=standard

helm upgrade --set config.cluster_size=5 cassandra incubator/cassandra --set persistence.storageClass=standard

Give this a try
