### ISSUE TITLE
[stable/prometheus] pod has unbound PersistentVolumeClaims (repeated 2 times)

### ISSUE THREAD

**Issue by vadimprt** [helm/charts#5433]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

**kubernetes version:** v1.10.2

**helm version:**
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}

**Which chart**:

**chart:** prometheus-6.3.2

**What happened**:

prometheus-server in error state "pod has unbound PersistentVolumeClaims (repeated 2 times)"

**What you expected to **happen**:**

prometheus-server to be runing

**How to reproduce it** (as minimally and precisely as possible):

helm install --namespace kube-system --name monitor stable/prometheus --set server.ingress.enabled=true --set server.ingress.hosts[0]=example.domain.com

**Anything else we need to know**:

kubernetes running on aws cloud using kops version 1.9.0 in private topology

**Comment by cmorent** [comment]
I'm also having this issue !

**Comment by jonathanschwarze** [comment]
Check your storage and CPU capacity! I got the same error and figured out that I had not enough storage left. After increasing it everything works well!

**Comment by damascenorakuten** [comment]
+1

**Comment by maxsarath** [comment]
facing same issue.
+1

**Comment by maxsarath** [comment]
i was able to fix this issue for my cluster. The issue was, i had not created the storage class. so when i did it, i can see pods running.

https://docs.aws.amazon.com/eks/latest/userguide/storage-classes.html

kubectl get sc
NAME            PROVISIONER             AGE
gp2 (default)   kubernetes.io/aws-ebs   4s

**Comment by nightcatnl** [comment]
+1

**Comment by Mrcampbell** [comment]
Got it.

When I was using helm to install it, I was putting prometheus in a different namespace (`monitoring`), but the volumes are added in the default namespace. 

Copy the volumes in the default namespace into the namespace where the app is running and you'll be good.

**Comment by vishnujanardhanan** [comment]
I had the same issue and fixed it by using the right storage class for the cloud provider. Though it is late it'll be helpful for someone.
