### ISSUE TITLE
Templatize Prometheus ConfigMaps

### ISSUE THREAD

**Issue by ravishivt** [helm/charts#544]
Currently, the prometheus chart has a static ConfigMap for alertmanager and server in values.yaml.  I could submit a PR to move the configs into the templates/ directory and make a few options parameterized but the drawback of that is the inability for users to rip and replace the templated version with their own configs.  i.e. Only the supported parameters in the configmap could be modified.  So I'd like the best of both: use the templated configmaps if and only if there is no associated configmap defined in values.yaml.

Before doing this, I'd like to check if this is wanted.  I looked through a few other charts and couldn't find this workflow.

BTW, the motivation behind this is to set `insecure_skip_verify: true` to get local cluster monitoring working as per #229.

**Comment by mgoodness** [comment]
@ravishivt I like the idea of providing templating options in the example config, yet maintaining the ability to replace it completely. Seems like a good compromise. Have at it! I'm also happy to bounce ideas back-and-forth if you want.

**Comment by kenden** [comment]
It might be confusing to mix kubernetes configuration elements and prometheus configuration elements in the templates.
Maybe templating should be limited to kubernetes yaml files. (deployment.yaml, service.yaml....)
It should be clearer if Kubernetes and Prometheus configuration were more separate, by importing them from external files. See https://github.com/kubernetes/charts/issues/922

With this, Prometheus templating would then have to be done somewhere else,so:
1. create the Prometheus config files (some ideas [[here]](https://prometheus.io/docs/visualization/template_examples/) maybe?). 
2. include them with Helm using `{{ $files.Get . }}`
