### ISSUE TITLE
After deploying REDIS-HA chart, there is more than 1 master. After killing master(s), no new master is getting elected (none of pods get labeled as master), so there is no HA.

### ISSUE THREAD

**Issue by uxon123** [helm/charts#5441]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
kubectl version 1.9.0
helm version 2.8.2

**Which chart**:
redis-ha

**What happened**:
1. After deploying a chart with configured 2 servers, both server pods became MASTERS (both server pods got 'redis-role: slave' label). At the moment I have 2 pods behind redis-master service (one of which is redis master and second is a redis slave).
2 After killing these pods (or any following pods), replica set created 2 new pods, but both of them became SLAVES (none of existing server pods got  'redis-role: master' label. So after master crashes, the new master is not reachable through redis-master service.

**What you expected to happen**:
1. As this chart's documentation (and redis documentation) describes, there should be only one master. 
2. After killing a master, a new master should be elected by sentinels (and this probably works fine) and pod with running redis master should get  'redis-role: master' label. Because none of the pods got it, redis master service had no pods to respond to requestes.
I looked at smileisak/docker-images/redis/alpine docker image which seems to be used underneath and I see no logic there to automatically reassign labels on sentinels reelections (there is only logic which run on new pod startup).

**How to reproduce it** (as minimally and precisely as possible):
Deploy redis-ha with number of servers set to 2. You should see both server pods labeled as 'redis-role: master'.
Kill both server pods. New pods are created, but none of them has 'redis-role: master' label.

**Anything else we need to know**:

**Comment by tdcox** [comment]
Seeing the same problem of no pods being labelled as 'master' here.

**Comment by varunpalekar** [comment]
I also face this kind of problem, When I deploy Redis-HA it deploys two master. This happens very rarely. Problem may be due to both redis-server get from kubernetes API about master and got no master so both become master due to exact same time query. 

We can use statefulset to control creation of pod one after the another. 

I guess we need to revert to statefulset again 
https://github.com/kubernetes/charts/pull/5739

**Comment by KoviaX** [comment]
I think you are correct varunpalekar, PR #4038 has been opened some time ago but the user @bzumhagen does not seem to manitain it anymore, maybe give #6706 a try?
