### ISSUE TITLE
Multiple AZ-agnostic persistent volumes

### ISSUE THREAD

**Issue by mgoodness** [helm/charts#546]
Just ran into an interesting problem while testing #393. If persistence is enabled, the chart provisions two volumes - one for wordpress data, and another for apache data. But if the specified (or default) StorageClass doesn't specify a GKE/AWS zone in which to create volumes, one is selected at random ([ref](https://kubernetes.io/docs/user-guide/persistent-volumes/#storageclasses)). This could (and in my case, did) result in the two volumes being provisioned in different zones, preventing the cluster from scheduling the pod.

AFAIK there's nothing we can technically do at the chart level to avoid this scenario, other than mandating one pod-one volume. But it's probably something we want to mention somewhere, as it complicates our goal of easy out-of-the-box persistence.

**Comment by redbaron** [comment]
this one should probably be reported to kubernetes, as it is something which should be addressed there

**Comment by mgoodness** [comment]
@redbaron I don't think of it as a bug, though. Zone can be part of the StorageClass definition, but it's not (and, IMHO, shouldn't be) required.

**Comment by redbaron** [comment]
it can be,but it doesn't help if you want to run multi-AZ StatefulSet

**Comment by bcorijn** [comment]
I ran into this as well and created a PR for it, as I had not searched deep enough for issues to come across this one. In the case of the wordpress chart both volumes are mounted under the same parent folder, so it's an easy fix to just combine it into one volume.  
Issue is discussed in the context of petsets here in kubernetes core: https://github.com/kubernetes/kubernetes/issues/35695

**Comment by kow3ns** [comment]
@mgoodness given that we have addressed this in provisioner can we close this issue. Also, FWIW we have opened a larger issue to deal with scheduling and provisioning zonal resources. https://github.com/kubernetes/kubernetes/issues/41598

**Comment by bcorijn** [comment]
@kow3ns as I remarked in the issue you linked, the talk is all about StatefulSets but this issue can just as wel hit Deployment such as in the Wordpress chart.
