### ISSUE TITLE
[Incubator/kafka] Configuration typo about `heapOptions`

### ISSUE THREAD

**Issue by Xuhao** [helm/charts#5466]
**Is this a request for help?**: no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 

BUG REPORT

**Version of Helm and Kubernetes**: 

kubernetes: 1.9.3, helm: 2.8.2

**Which chart**: 

Incubator/kafka

**What happened**:

config `kafkaHeapOptions` in values.yaml and described in README.md, but used as `.Values. heapOptions` in: 

https://github.com/kubernetes/charts/blob/fd93bff82fc18c33dc21e46848af9556c298af1d/incubator/kafka/templates/statefulset.yaml#L137

**What you expected to happen**:

Used  as `{{ .Values. kafkaHeapOptions }}`

**How to reproduce it** (as minimally and precisely as possible):

run `helm install --dry-run --debug` to see kafkaHeapOptions not used.

**Anything else we need to know**:

no

**Comment by Dean-Coakley** [comment]
I've opened a PR @Xuhao . Thanks for the awesome detail on this bug report
