### ISSUE TITLE
[stable/rabbitmq] Version 0.7.7 (and forth) breaks serviceType: 'NodePort' with PR #5200

### ISSUE THREAD

**Issue by Flowkap** [helm/charts#5479]
BUG REPORT

**Version of Helm and Kubernetes**:
All

**Which chart**:
stable/rabbitmq

**What happened**:
Since version 0.7.7 ServiceType: NodePort is broken due to PR https://github.com/kubernetes/charts/pull/5200

**What you expected to happen**:
That deploy works and ServiceType is properly adopted

**How to reproduce it** (as minimally and precisely as possible):
Just install the chart with version 0.7.7 to 0.8.1 (current latest) with serviceType: NodePort enabled 

**Anything else we need to know**:
https://github.com/kubernetes/charts/blob/193ac34b65a564f80a3b3cc580757a772369b512/stable/rabbitmq/values.yaml#L49 is basically the issue.  

The value isn't the nodePort in K8 terms but rabbitmq terminology. By setting the serviceType NodePort
  
https://github.com/kubernetes/charts/blob/193ac34b65a564f80a3b3cc580757a772369b512/stable/rabbitmq/templates/svc.yaml#L20

gets set to the same port (default 5672) which is not allowed (>30000) 

and produces the error:

`Service "broker-rabbitmq" is invalid: spec.ports[1].nodePort: Invalid value: 5672: provided port is not in the valid range. The range of valid ports is 30000-32767`

**Suggestion**: 

Rename the port to amqpPort (which it basically is) and make the nodePort default to nil
So it's possible to enter a custom nodePort for amqp. 

Also add possible NodePorts for the other services as well. 

I try to create a PR next week (holiday from tomorrow)

**Comment by nerumo** [comment]
Sorry for the bug. The variable name was confusing me. I didn't have the bug on my cluster since the port range was configured without me knowing it. I agree with your solution approach.
