### ISSUE TITLE
Add support for advanced config in rabbitmq chart

### ISSUE THREAD

**Issue by Nopik** [helm/charts#5491]
With the recent RabbitMQ 3.7 series, they introduced new, simpler configuration file format. It, however, doesn't support setting all values (e.g. `ssl_options.ciphers`) - some values must still be configured using old file format. While the chart is using the new file format, it gets tricky. RabbitMQ, however, does support concept of 'advanced' config file, which is in old format, and its content gets merged with the main config file. So, adding extra file on filesystem + setting `RABBITMQ_ADVANCED_CONFIG_FILE` seem to work around the current limitations.

**Comment by vmrm** [comment]
you can use configmap and mount it in /etc/rabbitmq - it works perfectly

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  advanced.config: |
      [
        {rabbitmq_management,
          [{listener, [{port, 15672}]}]
        }
      ].
```

**Comment by Nopik** [comment]
Yeah, thanks.
