### ISSUE TITLE
[incubator/fluentd-cloudwatch] Encoding errors causes Fluentd to stop processing logs. Fixed in upstream

### ISSUE THREAD

**Issue by mfornasa** [helm/charts#5514]
**Is this a request for help?**: No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:  Kubernetes 1.8, Helm 2.6.2

**Which chart**: incubator/fluentd-cloudwatch

**What happened**:
Fluentds starts logging the following error message every 10 seconds:

```
2018-05-10 12:55:34 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-05-10 12:55:36 +0000 error_class="Encoding::UndefinedConversionError" error="\"\\xC3\" from ASCII-8BIT to UTF-8" plugin_id="object:2ab38b4cedd4"
```
and it stops processing logs.

This bug makes the chart unusable.

**What you expected to happen**:
Fluentd should not hang.

**Anything else we need to know**:
The bug has been fixed in upstream  (https://github.com/fluent/fluentd-kubernetes-daemonset/issues/13 and https://github.com/fluent/fluentd-kubernetes-daemonset/pull/44). I fixed on my system by upgrading to v.1 version, which is marked as stable:

```
imageTag: v1.1-debian-cloudwatch
```

**Comment by mfornasa** [comment]
@unguiculus I saw that you're working on `fluentd-cloudwatch` so you may be interested in reviewing this. I could provide a PR, but I need to understand if we are willing to switch from version v0.12.33 to v1 of [fluentd-kubernetes-daemonset ](https://github.com/fluent/fluentd-kubernetes-daemonset).
I suggest to do so as v0.12 is `old stable` and v1 is `stable`. For what it is worth, I have been running v1 on two kube cluster for ~2 weeks without issues.

@jmcarp @icereval @kenden can chime in maybe?

**Comment by whereisaaron** [comment]
I just tried switching from v0.12 to v1.2. That was very [unsuccessful](https://github.com/fluent/fluentd-kubernetes-daemonset/issues/150), the Pods just crash about ~1 minutes. Switching back to v0.12 all is fine again. https://github.com/fluent/fluentd-kubernetes-daemonset/issues/150

Maybe this is a v1.2 problem and v1.1 is okay? I'll try later.

There was a related fix to the chart recently for hanging logs, not sure if this is the same as your issue: https://github.com/kubernetes/charts/pull/5511

**Comment by mfornasa** [comment]
@whereisaaron : #5511  is my patch for a different bug, which is unrelated to this. I needed to apply both #5511 and upgrade to v1.1 to achieve stable operations. Please let me know about your test with 1.1.

**Comment by hemantseth0210** [comment]
I was getting the same issue with fluent/fluentd-kubernetes-daemonset `v0.12.43-cloudwatch`. I changed it to `v0.12-debian-cloudwatch` to resolve the issue on my local. 

Can we please have this fixed?

**Comment by idavidmcdonald** [comment]
We had the same issue with v0.12.43-cloudwatch and upgraded to the `v1.3.2-debian-cloudwatch` image which fixed our problems. Would be happy to put in a PR to bump the default version if useful.
