### ISSUE TITLE
[stable/grafana] Typo in deployment.yaml

### ISSUE THREAD

**Issue by ghost** [helm/charts#5549]
**Version of Helm and Kubernetes**:
Helm 2.8.2, Kubernetes 1.9.7

**Which chart**:
Grafana chart v1.8.0

**What happened**:
Typo in deployment.yaml:131 causes:
```
Error: UPGRADE FAILED: Deployment.apps "grafana" is invalid: spec.template.spec.containers[0].envFrom: Invalid value: "": must specify one of: `configMapRef` or `secretRef`
```

I believe `secretKeyRef` should be `secretRef`.

**What you expected to happen**:
Succesful helm deployment

**How to reproduce it** (as minimally and precisely as possible):
Use envFromSecret in values file.

**Comment by mattjmcnaughton** [comment]
Happy to fix this, thanks for reporting! PR incoming :)
