### ISSUE TITLE
[stable/influxdb] unable to install on arm

### ISSUE THREAD

**Issue by dsvensson** [helm/charts#5566]
**BUG REPORT**:

```
Events:
  Type     Reason                 Age                From                  Message
  ----     ------                 ----               ----                  -------
  Normal   Scheduled              43s                default-scheduler     Successfully assigned influxdb-influxdb-76fbdc9f4b-m5cb2 to raspberrypi
  Normal   SuccessfulMountVolume  43s                kubelet, raspberrypi  MountVolume.SetUp succeeded for volume "data"
  Normal   SuccessfulMountVolume  43s                kubelet, raspberrypi  MountVolume.SetUp succeeded for volume "config"
  Normal   SuccessfulMountVolume  43s                kubelet, raspberrypi  MountVolume.SetUp succeeded for volume "default-token-4tbmf"
  Normal   Pulling                25s (x2 over 41s)  kubelet, raspberrypi  pulling image "influxdb:1.4-alpine"
  Warning  Failed                 23s (x2 over 40s)  kubelet, raspberrypi  Failed to pull image "influxdb:1.4-alpine": rpc error: code = Unknown desc = no matching manifest for linux/arm in the manifest list entries
  Warning  Failed                 23s (x2 over 40s)  kubelet, raspberrypi  Error: ErrImagePull
  Normal   BackOff                11s (x2 over 38s)  kubelet, raspberrypi  Back-off pulling image "influxdb:1.4-alpine"
  Warning  Failed                 11s (x2 over 38s)  kubelet, raspberrypi  Error: ImagePullBackOff
```

**Version of Helm and Kubernetes**:

```
$ helm version
Client: &version.Version{SemVer:"v2.8+unreleased", GitCommit:"5f4b260ae50544c6565f68db7079d8ce55c35b6e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8+unreleased", GitCommit:"5f4b260ae50544c6565f68db7079d8ce55c35b6e", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/arm"}
```

**Which chart**:

stable/influxdb

**What happened**:

It didn't find the arm image.

**What you expected to happen**:

That it found the arm image.

**How to reproduce it** (as minimally and precisely as possible):

Install Kubernetes and Helm/Tiller (latter from source as no binaries are available) on Raspberry Pi 3, and then:

`helm install stable/influxdb --name influxdb`

**Anything else we need to know**:

"all of the InfluxData products now support running them with Docker on ARM"
https://www.influxdata.com/blog/influxdata-docker-arm/

"Supported architectures: amd64, arm32v7, arm64v8"
https://hub.docker.com/_/influxdb/

**Comment by mattjmcnaughton** [comment]
I believe the issue is that the helm chart is using the `influxdb:1.4-alpine` image, which only supports `linux/amd64`. The `influxdb:1.4 `image (based on debian stretch), supports `arm`.

I determined this by running `docker run stefanscherer/mquery influxdb:1.4-alpine` and `docker run stefanscherer/mquery influxdb:1.4`, and comparing the output.

I believe that you can fix this with `helm install stable/influxdb --name influxdb --set image.tag=1.4`.

If you can get consensus, I'm happy to submit a pr to make `influxdb:1.4` the default image instead of `influxdb:1.4-alpine`, but tbh I'm not sure I have the context on why alpine was used initially and how strongly people feel about it.

**Comment by dsvensson** [comment]
I can confirm this works, thanks!

```
$ helm install stable/influxdb --name influxdb --set image.tag=1.4
...
$ kubectl get pods
NAME                                 READY     STATUS    RESTARTS   AGE
influxdb-influxdb-765d686858-4j65h   1/1       Running   0          1m
```

As for Alpine vs Debian-Slim, the obvious difference is the size:

```
1.4-alpine  25 MB
1.4         82 MB
```

Is it possible to prefer the non-Alpine version on ARM, while keeping Alpine on platforms where it's supported?
