### ISSUE TITLE
[stable/openvpn] sysctl ipv4 ip forward should be enabled

### ISSUE THREAD

**Issue by k8w** [helm/charts#5572]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
1.10

**Which chart**:
stable/openvpn

**What happened**:
sysctl ipv4 ip forward is 0 (disabled)
It result in package from tun0 can not reach eth0.
So that client can not get in pod network.

**What you expected to happen**:
sysctl ipv4 ip forward should be enabled

**How to reproduce it** (as minimally and precisely as possible):
1. Deploy a new [stable/openvpn]
1. Connect the OpenVPN
1. Client can ping OpenVPN pod, but cannot ping other pod

**Anything else we need to know**:

**Comment by neyz** [comment]
Did you manage to change this option in the image ? I keep getting a "read only file system" when doing it on the fly ?
thanks !
