### ISSUE TITLE
Ingress not working post RBAC version install

### ISSUE THREAD

**Issue by c-mccutcheon** [helm/charts#5593]
Request for help: Yes

**Version of Helm and Kubernetes**:
Helm 2.9.1, Kubernetes 1.9.2 (Azure AKS)

**Which chart**:
Nginx-ingress

**What happened**:
Our previous installation of nginx-ingress (tag 0.13.0 in the values file) worked perfectly with Ingress inside Azure AKS, forwarding to our web application pod via a hostname. We upgraded to the latest chart and had to disable RBAC (as opposed to the default in the values.yml file) due to AKS not supporting it yet, so we installed it with RBAC turned off entirely.

**What you expected to happen**:
Ingress should continue to work as it did previously, with traffic routing correctly.

**How to reproduce it** (as minimally and precisely as possible):
We are simply trying to do basic host-name routing via nginx-ingress, we reproduce it in our system by there being a timeout and no logs in the nginx-controller pod to suggest it attempted to route traffic, we also get the following error logs which did not happen before:

I0516 09:21:02.507860       5 status.go:356] updating Ingress default/my-web status to [{ }]
I0516 09:21:02.508848       5 status.go:356] updating Ingress default/kube-lego-nginx status to [{ }]
I0516 09:21:02.516179       5 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"vanquis-web", UID:"25f40927-58dc-11e8-ac5d-0a58ac1f0ce3", APIVersion:"extensions", ResourceVersion:"121858", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress default/my-web
W0516 09:21:02.516777       5 controller.go:700] error obtaining service endpoints: error getting service default/vanquis-web from the cache: service default/my-web was not found
I0516 09:21:02.567789       5 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"kube-lego-nginx", UID:"9956f045-582c-11e8-a826-0a58ac1f0cdc", APIVersion:"extensions", ResourceVersion:"121859", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress default/kube-lego-nginx

**Anything else we need to know**:
It looks like ingress rules are never executed, so nginx never routes the traffic? We cannot even hit default backend either.

We have RBAC turned off and never used to see log entries suggesting that we couldn't obtain service endpoints until upgrading to the latest version.

**Comment by alexvicegrab** [comment]
Ingress RBAC was reactivated by default:

https://github.com/kubernetes/charts/commit/c60086ec0b260996281d337d67f2361f826f7029
