### ISSUE TITLE
[stable/hadoop] Multi-Attach error for volume when replicas > 1

### ISSUE THREAD

**Issue by kikulikov** [helm/charts#5595]
BUG REPORT

**Version of Helm and Kubernetes**:

```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:29:03Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

`stable/hadoop`

**What happened**:

Getting this error when `hdfs.dataNode.replicas=2`. The first instance is fine.

```
Multi-Attach error for volume "pvc-2ab6c3a0-58ed-11e8-8613-06438f445520" Volume is already exclusively attached to one node and can't be attached to another
Unable to mount volumes for pod "hadoop-hadoop-hdfs-dn-1_hadoop(4823d80a-58ed-11e8-8613-06438f445520)": timeout expired waiting for volumes to attach/mount for pod "hadoop"/"hadoop-hadoop-hdfs-dn-1". list of unattached/unmounted volumes=[dfs]
```

**What you expected to happen**:

No errors. Volumes attached as required.

**How to reproduce it** (as minimally and precisely as possible):

```
helm install --name hadoop --namespace hadoop \
--set persistence.nameNode.enabled=true --set persistence.nameNode.storageClass=gp2 \
--set persistence.dataNode.enabled=true --set persistence.dataNode.storageClass=gp2 \
--set hdfs.dataNode.replicas=2 stable/hadoop
```

**Anything else we need to know**:

Run it on AWS

**Comment by juv** [comment]
The documentation says 

> This chart is **primarily intended to be used for YARN and MapReduce job execution where HDFS is just used as a means to transport small artifacts within the framework and not for a distributed filesystem**. Data should be read from cloud based datastores such as Google Cloud Storage, S3 or Swift.

Your error occurs because there is a single `persistentVolumeClaim` for the data node in the chart, within file hdfs-dn-pvc.yaml. One could use a `volumeClaimTemplates` instead of the `persistentVolumeClaim` within the data nodes StatefulSet (hdfs-dn-statefulset.yaml) to make the volume claims scale with the amount of replicas you add. The PersistentVolume Provisioner will then dynamically provide stable storage for each replica.

**Comment by kikulikov** [comment]
@juvlarN Thank you for the clarification. Yes, `volumeClaimTemplate` would make more sense there.
