### ISSUE TITLE
[stable/concourse] set env vars on web deployment

### ISSUE THREAD

**Issue by maxfrigge** [helm/charts#5597]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Right now it's only possible to configure `worker.env`. I would like to suggest to also allow setting `web.env` in order to e.g. set `CONCOURSE_LOG_LEVEL`.

**Comment by mattjmcnaughton** [comment]
Makes sense to me! Working on a pr for this right now :)
