### ISSUE TITLE
[couchdb] `helm delete` fails to delete couchdb pods

### ISSUE THREAD

**Issue by flimzy** [helm/charts#5605]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

**Version of Helm and Kubernetes**:

    $ kubectl version
    Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.8-gke.0", GitCommit:"6e5b33a290a99c067003632e0fd6be0ead48b233", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

    $ helm version --tls
    Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
    Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

**Which chart**:

incubator/couchdb

**What happened**:

I installed the chart, then removed it, but the chart pods persist, in a broken state.

    $ helm install incubator/couchdb --name couchdb --set ingress.enabled=true --set ingress.hosts[0]=$URL --tls
    $ helm ls --tls
    NAME            REVISION        UPDATED                         STATUS          CHART                   NAMESPACE
    couchdb         1               Wed May 16 18:33:41 2018        DEPLOYED        couchdb-0.1.2           default  
    nginx-ingress   1               Wed May 16 18:33:38 2018        DEPLOYED        nginx-ingress-0.17.2    default

< wait for pods to come up, verify they are functioning by visiting the ingress URL >

    $ helm delete couchdb --tls
    release "couchdb" deleted
    $ helm ls --tls            
    NAME            REVISION        UPDATED                         STATUS          CHART                   NAMESPACE
    nginx-ingress   1               Wed May 16 18:33:38 2018        DEPLOYED        nginx-ingress-0.17.2    default  

< 10 minutes later >

    $ kubectl get pods
    NAME                                             READY     STATUS                       RESTARTS   AGE
    couchdb-couchdb-0                                0/2       CreateContainerConfigError   0          12m
    couchdb-couchdb-1                                0/2       CreateContainerConfigError   0          12m
    couchdb-couchdb-2                                0/2       CreateContainerConfigError   0          12m
    nginx-ingress-controller-5644dd49d-kqj7s         1/1       Running                      0          12m
    nginx-ingress-default-backend-58bf6f478b-mjw6m   1/1       Running                      0          12m

    $ kubectl describe pod couchdb-couchdb-0
    < snip >
      Warning  FailedMount            11m (x5 over 12m)  kubelet, gke-test-default-pool-5491ccfd-84wv  
MountVolume.SetUp failed for volume "config" : configmaps "couchdb-couchdb" not found
      Normal   Pulled                 2m (x42 over 12m)  kubelet, gke-test-default-pool-5491ccfd-84wv  Container image "couchdb:2.1.1" already present on machine

**What you expected to happen**:

I expected the `couchdb-couchdb-*` pods to terminate.

**How to reproduce it** (as minimally and precisely as possible):

See above.

**Anything else we need to know**:

Running on GKE.

**Comment by kocolosk** [comment]
Curious ... why would it be trying to create the containers as the release is being deleted? I wasn't able to repro on my test clusters on IBM Cloud, I will see if I can on GKE.

**Comment by flimzy** [comment]
In case it matters, my test cluster on GKE is built of 6 f1-micro instances.  I can provide complete configuration details if it would be useful.

**Comment by kocolosk** [comment]
OK I have managed to reproduce this although not sure of a root case yet. What I'm seeing is that the statefulset is still around, and I get a 404 when trying to delete it:

```
✗ kubectl get statefulset
NAME                   DESIRED   CURRENT   AGE
amber-dragon-couchdb   3         3         25m
iced-vulture-couchdb   3         3         1h
✗ kubectl delete statefulset amber-dragon-couchdb
Error from server (NotFound): the server could not find the requested resource
```

Not sure what to make of that but will keep digging.

**Comment by flimzy** [comment]
ping?
