### ISSUE TITLE
unexpected error creating file watcher: no space left on device

### ISSUE THREAD

**Issue by gyurobenjamin** [helm/charts#5615]
**Is this a request for help?**:
Maybe
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
K8S
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:06Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.9", GitCommit:"19fe91923d584c30bd6db5c5a21e9f0d5f742de8", GitTreeState:"clean", BuildDate:"2017-10-19T16:55:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Helm
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

**Which chart**:
stable/nginx-ingress

**What happened**:
Ingress controller failing:

I0517 12:57:08.746062     100 flags.go:162] Watching for ingress class: nginx
W0517 12:57:08.746614     100 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0517 12:57:08.746930     100 main.go:181] Creating API client for https://10.0.0.1:443
I0517 12:57:08.777747     100 main.go:225] Running in Kubernetes Cluster version v1.7 (v1.7.9) - git (clean) commit 19fe91923d584c30bd6db5c5a21e9f0d5f742de8 - platform linux/amd64
I0517 12:57:08.782598     100 main.go:84] validated kube-system/austere-bobcat-nginx-ingress-default-backend as the default backend
I0517 12:57:09.045420     100 stat_collector.go:77] starting new nginx stats collector for Ingress controller running in namespace  (class nginx)
I0517 12:57:09.045479     100 stat_collector.go:78] collector extracting information from port 18080
F0517 12:57:09.062095     100 nginx.go:190] unexpected error creating file watcher: no space left on device

**What you expected to happen**:
See it running: )

**How to reproduce it** (as minimally and precisely as possible):
I just installed with helm on azure: helm install stable/nginx-ingress --namespace kube-system

**Anything else we need to know**:

**Comment by fpytloun** [comment]
We are seeing the same issue on Azure (not using Helm anyway). It's related to https://github.com/kubernetes/ingress-nginx/issues/1397
It happens here in the ingress-nginx code: https://github.com/kubernetes/ingress-nginx/blob/a30b96bcce63dcd64f62301665a9c6ebf775e9e5/internal/ingress/controller/nginx.go#L190

**Comment by vgopal** [comment]
Notice same error.. 
```
+ exec /usr/bin/dumb-init /nginx-ingress-controller --force-namespace-isolation --watch-namespace infra --election-id=infra-mariadb --ingress-class=infra-mariadb-mariadb-ingress --default-backend-service=infra/mariadb-ingress-error-pages --tcp-services-configmap=infra/mariadb-services-tcp

-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:    0.9.0
  Build:      git-6816630
  Repository: https://github.com/kubernetes/ingress-nginx
-------------------------------------------------------------------------------

I0730 20:28:38.058381       7 flags.go:151] Watching for ingress class: infra-mariadb-mariadb-ingress
W0730 20:28:38.058420       7 flags.go:154] only Ingress with class "infra-mariadb-mariadb-ingress" will be processed by this ingress controller
I0730 20:28:38.058886       7 main.go:227] Creating API client for https://10.96.0.1:443
I0730 20:28:38.071967       7 main.go:239] Running in Kubernetes Cluster version v1.10 (v1.10.2) - git (clean) commit 81753b10df112992bf51bbc2c2f85208aad78335 - platform linux/amd64
I0730 20:28:38.074409       7 main.go:83] validated infra/mariadb-ingress-error-pages as the default backend
I0730 20:28:38.409008       7 stat_collector.go:77] starting new nginx stats collector for Ingress controller running in namespace infra (class infra-mariadb-mariadb-ingress)
I0730 20:28:38.409031       7 stat_collector.go:78] collector extracting information from port 18080
F0730 20:28:38.421717       7 nginx.go:178] unexpected error watching template /etc/nginx/template/nginx.tmpl: no space left on device
```

**Comment by claudod** [comment]
Hi all, I encountered the same issue on AKS, and it looks like I found the root cause thanks to the clue given in https://github.com/kubernetes/ingress-nginx/issues/1965 : need to increase inotify/max_user_watches. 
On my AKS cluster kubelet had ~7000 inotify file descriptors opened, with a sys limit of ~8000 limit. I increased the limit to x5.

Useful commands to debug :
`lsof -K | grep inotify | grep kubelet | wc -l`
`journalctl -u kubelet -f -n 1000 | grep inotify``

Fix : 
`echo 40960 > /proc/sys/fs/inotify/max_user_watches`
`echo fs.inotify.max_user_watches=40960 >> /etc/sysctl.conf`
