### ISSUE TITLE
[stable/traefik] acme / DNS / gcloud / Ability to specify GCE_SERVICE_ACCOUNT_FILE

### ISSUE THREAD

**Issue by jacobsvante** [helm/charts#5617]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

Setup of ACME for `gcloud` is different from the other DNS providers in that it needs a file to be accessible in the file system. Currently there is no easy way to configure `GCE_SERVICE_ACCOUNT_FILE` when using the chart.

One approach that I can verify as working is the one provided by @Azuka in the initial DNS-01 implementation here: https://github.com/kubernetes/charts/pull/1299#issuecomment-361450527. (`GCE_SERVICE_ACCOUNT_FILE` works today, `GOOGLE_APPLICATION_CREDENTIALS` is not needed anymore)

What would be a good way to implement this? @krancour @emilevauge @dtomcej @ldez

I'd gladly do an implementation for it as long as we can come to terms with what would be the best way forward.

**Comment by jacobsvante** [comment]
Took a stab at it in the referenced PR. I'd love to get some feedback, so please feel free to leave a comment.

**Comment by kunickiaj** [comment]
Any update on this? Definitely a blocker for Google CloudDNS

**Comment by jmagnusson** [comment]
@krancour @emilevauge @dtomcej @ldez Any chance we could get this merged?

Google Cloud DNS can basically not be set up without modifying the code as it currently stands.

**Comment by nreisbeck** [comment]
Just ran into this same issue today, would be great to get this merged in 👍

**Comment by Azuka** [comment]
For everyone else experiencing this, `http-01` works just fine as long as you point an A record for the wildcard `*.your-domain.tld` to the load balancer ip being used by traefik.

**Comment by kunickiaj** [comment]
I'm using dns-01 mostly for privately networked clusters, where I still want public CA signed certs.

**Comment by Azuka** [comment]
Ah. That makes sense.
