### ISSUE TITLE
Help needed Install jenkins offline

### ISSUE THREAD

**Issue by krishshenoy** [helm/charts#5626]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Kubernetes 1.9.6-21
Helm 
{Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
**Which chart**:
Stable/jenkins jenkins-0.13.2

**What happened**:
I wanted to have a reliable way of deploying jenkins into a cluster. I did not want to always fetch the latest version since it might break whenver there is an update. 
I tried "helm fetch stable/jenkins"
and install the chart from the stable location
by running 
helm install ./jenkins-0.13.2.tgz
I also disabled all plugins in the jenkins helm chart by modifying the jenkins.yaml manifest.
Specifically commented out the following
  #InstallPlugins:
  #  - kubernetes:1.1
  #  - workflow-aggregator:2.5
  #  - workflow-job:2.15
  #  - credentials-binding:1.13
  #  - git:3.6.4
The problem I have is that sometimes the jenkins install fails because the container cannot fetch the data from the jenkins repo. 

**What you expected to happen**:
Jenkins install does not try to fetch any thing from the online jenkins repo. Everything is installed using data stored in the local file system

**How to reproduce it** (as minimally and precisely as possible):
helm fetch stable/jenkins
helm install ./jenkins-0.13.2.tgz

Is there a way to install jenkins only using local files

**Anything else we need to know**:

**Comment by beanallergy** [comment]
Any update on this issue? I have a similar problem.

**Comment by longfei-zhang** [comment]
face the same issue
