### ISSUE TITLE
CockroachDB isn't abiding by the resource limits set in the values.yaml. 

### ISSUE THREAD

**Issue by peternavr** [helm/charts#5628]
**Is this a request for help?**: Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

In the example values.yaml you have the structure:
```
Resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
```

In the file ```templates/cockroachdb-statefulset.yaml``` you have the following:
```{{ toYaml .Values.resources | indent 10 }}```

The case on the resources is wrong, but even with that resolved in the values, you never add in the requested resources. It's just blank on the StatefulSet.

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.0", GitCommit:"1883ce4eb0e057cfc2439ebeb9822da0a9d40405", GitTreeState:"clean", BuildDate:"2018-04-19T17:08:34Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/cockroachdb

**What happened**:
The resources requested in values isn't added into the statefulset / pods. By default it's requesting 100m of CPU.

**What you expected to happen**:
Inject the resources I've requested.

**How to reproduce it** (as minimally and precisely as possible):
Try to use the resources and your own custom file.

**Anything else we need to know**:

**Comment by mattjmcnaughton** [comment]
Good catch @clanstyles ! Putting out a pr to fix this rn :)
