### ISSUE TITLE
Unable to create a bucket while deploying the Minio Helm chart

### ISSUE THREAD

**Issue by anshumanbh** [helm/charts#5653]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug Report in the helm chart for minio cc: @diwakar-s-maurya 

The minio helm chart refuses to create a bucket when the following command was run: 

```
helm install --tiller-namespace $tiller_namespace --namespace $namespace --name $minio_svc_name --set "accessKey=$minioaccesskey,secretKey=$miniosecretaccesskey,defaultBucket.enabled=true,defaultBucket.name=$minio_bucket_name,defaultBucket.purge=true" stable/minio. 
```

I even made sure the tiller-manage role has permissions to all api groups (*). It would just get stuck on running this command. It would install minio and set the access key and secret access key correctly but would not create a bucket. I am not exactly sure how to debug this as to whats causing this.

**Version of Helm and Kubernetes**:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.0", GitCommit:"1883ce4eb0e057cfc2439ebeb9822da0a9d40405", GitTreeState:"clean", BuildDate:"2018-04-19T17:08:34Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

```
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

**Which chart**:
Minio

**What happened**:

Running this:
```
helm install --tiller-namespace $tiller_namespace --namespace $namespace --name $minio_svc_name --set "accessKey=$minioaccesskey,secretKey=$miniosecretaccesskey,defaultBucket.enabled=true,defaultBucket.name=$minio_bucket_name,defaultBucket.purge=true" stable/minio. 
```
doesn't create a bucket while deploying the minio chart. It just gets stuck. 

**What you expected to happen**:

A bucket should have been created and the helm chart should have been successfully deployed

**How to reproduce it** (as minimally and precisely as possible):

Command given above to reproduce.

**Anything else we need to know**:

N/A

**Comment by mattjmcnaughton** [comment]
Great catch @anshumanbh ! I'm getting the error message `can't open '/config/initialize'`. I believe some configuration was deleted which is causing this script to not be found.

I'll work on a pr to fix this rn!

**Comment by mattjmcnaughton** [comment]
Looking back at some further issues, I think this is a duplicate of #5403. Mind closing in favor of that issue?

**Comment by anshumanbh** [comment]
Will do. Thanks!
