### ISSUE TITLE
Changes to Sonarqube helm chart to add MySQL support instead of Postgres.

### ISSUE THREAD

**Issue by irajdeep** [helm/charts#5654]
So I made few changes to the Sonarqube base chart to add MySQL support , currently we have Postgres as the database in Sonarqube chart.
Wondering if this could be a new chart in the chart repo ?

**Comment by mattjmcnaughton** [comment]
Hi @irajdeep ! Do you mind explaining a little bit more about the nature of the change that you made? I'm wondering if instead of a new chart, it would make the most sense to use `values.yml` to allow the user to control whether they wanted to use `postgres` or `mysql` in the `sonarqube` chart?

**Comment by irajdeep** [comment]
Hi @mattjmcnaughton ! Sure. So the changes are primarily in `values.yml` file and a few changes in `deployment.yaml` and `requirements.yaml`. We can go ahead with adding the `mysql` support in the same `helm` chart but what I am concerned about is that it will cause a bunch of `if/else` statements in couple of file. 
So primarily there would be 4 cases , if we decide to go with the same helm chart.
1. `postgres` : `external` / `internal`
2. `mysql` : `external` / `internal` 
I feel adding both the options in the same chart might create confusion ( Something like turning on both the database options which might lead to inconsistent sonarqube behavior)  to the users of the chart in addition to introducing a bunch more of logic in the existing chart .  What would you suggest ?

**Comment by irajdeep** [comment]
@rjkernick your views ?

**Comment by rjkernick** [comment]
I would rather some if statements than a separate chart that will need managed. It's easy enough to follow the pattern that is there for postgres and add some templating for mysql.

**Comment by irajdeep** [comment]
Alright, So just to clear we are on the same page , a given release could have either `Postgres database (internal / external)` or `MySQL database (internal / external)` right ?

**Comment by rjkernick** [comment]
Yep. Sounds good. Look forward to seeing it in action.
