### ISSUE TITLE
Accept ConfigMap to bootstrap Artifactory configuration

### ISSUE THREAD

**Issue by gintautassulskus** [helm/charts#5676]
**FEATURE REQUEST**

**Which chart**:
Artifactory

**What happened**:

At the moment there is no way to bootstrap artifactory configuration. I suggest to add a configuration option to bootstrap `artifactory.config.import.xml` and `security.import.xml` configuration files. The bootstrapping of these files is described on [jfrog website](https://www.jfrog.com/confluence/display/RTF/Configuration+Files).

Artifactory helm chart would accept a name of the ConfigMap containing the configuration files. The ConfigMap would then be mounted on the target pod. Jenkins chart uses this approach to bootstrap its configuration.

For now, as a workaround, I have copied the charts and added the following code snippets to the `artifactory-deployment.yaml` file:

Config volume (missing helm control structures):
```
      - name: config-volume
        configMap:
          name: some-custom-artifactory-configmap
```

Config volume mount.
Artifactory fails if it cannot modify mounted files, whcih are read-only. 
To remedy this I mount config files to a different directory...
```
        - name: config-volume
          mountPath: /var/run/artifactory/etc
```

...and then copy these files to `$ARTIFACTORY_HOME/etc` directory:
```
        command:
        - 'sh'
        - '-c'
        - 'cp /var/run/artifactory/etc/* {{ .Values.artifactory.persistence.mountPath }}/etc/. && /entrypoint-artifactory.sh'
```

Example ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-custom-artifactory-configmap
data:
  artifactory.config.import.xml: |
    <config contents>
```

**Comment by jainishshah17** [comment]
@gintautassulskus Thanks for opening Feature request. We will work on adding configmap. Meanwhile I recommend to mount your configmap to 
```
- name: config-volume
          mountPath: /artifactory_extra_conf
``` 
entrypoint-artifactory.sh will cp it to $ART_HOME/etc dir

**Comment by gintautassulskus** [comment]
Thanks, @jainishshah17.

**Comment by sylus** [comment]
I don't think the addExtraConfFiles will work for files brought in via configmap. The following needs to be adjusted to take into account symbolic links or won't actually copy the file.

```sh
# Add additional conf files that were mounted to ARTIFACTORY_EXTRA_CONF
addExtraConfFiles () {
    logger "Adding extra configuration files to ${ARTIFACTORY_HOME}/etc if any exist"

    # If directory not empty
    if [ -d "${ARTIFACTORY_EXTRA_CONF}" ] && [ "$(ls -A ${ARTIFACTORY_EXTRA_CONF})" ]; then
        logger "Adding files from ${ARTIFACTORY_EXTRA_CONF} to ${ARTIFACTORY_HOME}/etc"
        cp -rfv ${ARTIFACTORY_EXTRA_CONF}/* ${ARTIFACTORY_HOME}/etc || errorExit "Copy files from ${ARTIFACTORY_EXTRA_CONF} to ${ARTIFACTORY_HOME}/etc failed"
    fi
}
```

The cp logic needs to change to `cp -Lrfv` I think

**Comment by jainishshah17** [comment]
https://github.com/kubernetes/charts/pull/6010

**Comment by jainishshah17** [comment]
This PR is merged. @gintautassulskus @sylus. Please feel free to test and close this issue.

**Comment by gintautassulskus** [comment]
Does this fix work with the `docker.bintray.io/jfrog/artifactory-oss`? I do not see the `addExtraConfFiles` bit in the image.

**Comment by jainishshah17** [comment]
@gintautassulskus We support this only on Pro/Enterprise.

**Comment by gintautassulskus** [comment]
I can't seem to find a repository for `artifactory-oss` - is there such?

**Comment by jainishshah17** [comment]
What do you mean by "I can't seem to find a repository for artifactory-oss - is there such?"

**Comment by jainishshah17** [comment]
@gintautassulskus Are you looking for https://bintray.com/jfrog/reg2/jfrog:artifactory-oss

**Comment by jainishshah17** [comment]
@gintautassulskus  The source code is not public. It's more like a community edition.

**Comment by gintautassulskus** [comment]
That is unfortunate. I will have to stick to my original workaround then. 

In regards to this fix, I cannot confirm that it works because I am using the community edition of artifactory.

**Comment by jainishshah17** [comment]
Can you please close this issue?

**Comment by gintautassulskus** [comment]
The [Artifactory chart documentation](https://hub.kubeapps.com/charts/stable/artifactory) gives the impression that Artifactory OSS is fully supported and even provides a dedicated section with the instructions on how to deploy it - `Deploying Artifactory OSS`.

I will close the issue, but please first either fix this issue for the artifactory-oss or update the documentation indicating which configuration options are UNavailable with the OSS image.

I feel that I have been mislead (I am sure - unintentionally) on two accounts here:
* I thought that the chart fully supports and/or is supported by all editions of artifactory;
* artifactory-oss image is in fact a closed source docker assembly that contains open source version of artifactory

**Comment by jainishshah17** [comment]
@gintautassulskus I totally understand things from your perspective. I will update the documentation to avoid unintentional mislead.
