### ISSUE TITLE
[incubator/zookeeper] [incubator/kafka]: using different docker images for sidecar

### ISSUE THREAD

**Issue by bradenwright** [helm/charts#5691]
**Is this a request for help?**:
No, its a discussion to decide how to move forward, which docker image should be used
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT
Not sure this is really a bug, but anyways.  The ZooKeeper chart and the Kafka chart are using different docker images for jmx exporter.  Both are doing the same thing, I don't really care which one is used but I feel that it would be better to be consistent and @benjigoldberg did too.

**Which chart**:
incubator/zookeeper
incubator/kafka

**Anything else we need to know**:
zookeeper chart is using sscaling/jmx-prometheus-exporter
kafka chart is using solsson/kafka-prometheus-jmx-exporter@sha256

@lachie83 @kow3ns @benjigoldberg @josdotso @nrmitchi @t-d-d  @unguiculus please call out anyone I may have missed, I tried to get the owners and people who were on related PRs.  Anyways just figured this warranted a discussion.

**Comment by ghost** [comment]
Hi @bradenwright. I've been working on rebasing my revisions to the Kafka chart to follow the 1.0 chart pattern I put forth in my recent PR to Zookeeper. I hope to address the gap in that upcoming PR.

Here is a preview of what I'll PR, but it's not recently been rebased, so much will need to change. https://github.com/cisco-sso/charts/tree/master/src/kafka

EDIT: Preview also lacks updated docs IIRC, so beware of that too.
