### ISSUE TITLE
[stable/schema-registry-ui] can't connect to kafka cluster in k8s

### ISSUE THREAD

**Issue by bradenwright** [helm/charts#5729]
**Is this a request for help?**:
Yes

If this is a BUG REPORT, please:
  - Fill in as much of the template below as you can.  If you leave out
    information, we can't help you as well.

**Which chart**:
stable/schema-registry-ui version 0.1.0

**What happened**:
Pod starts gui shows error CONNECTIVITY ERROR

**What you expected to happen**:
It to properly connect to schema-registry

**How to reproduce it** (as minimally and precisely as possible):
Install incubator/schema-registry and use service url for example whimsical-angelfish was the schema-registry release name in default namespace so:

```
schemaRegistry:
  url: "http://wanton-angelfish-schema-registry.default.svc.cluster.local"
```

**Anything else we need to know**:
I can curl the endpoint successfully from schema-registry-ui pod:
```
curl  http://whimsical-angelfish-schema-registry.ops.svc.cluster.local:8081/subjects
["connect-jdbc-hours-value","connect-jdbc-reservation-value"]
```
So schema-registry seems to be working properly.

Logs aren't showing much:
```
$ kubectl logs roiling-cheetah-schema-registry-ui-7c49d7557b-6c6wx -n ops
Setting Schema Registry URL to http://whimsical-angelfish-schema-registry.ops.svc.cluster.local:8081.

Activating privacy features... done.
http://0.0.0.0:8000
```

@cristian04 any ideas, has schema-registry-ui chart been tested with incubator/schema-registry chart?

**Comment by cmarquezrusso** [comment]
Hi @bradenwright,
Requests to `schema-registry` are sent from your browser, which cannot resolve `.ops.svc.cluster.local` 

We may need to open a defect under https://github.com/Landoop/schema-registry-ui to change this.

**Comment by bradenwright** [comment]
Got it, at least with the info I can setup an ingress that's accessible from my browser and use that.  Thanks for the reply, I'll be out of town for a few days so if I don't have time to test tonight I will early next week.

**Comment by bradenwright** [comment]
@cristian04 unfortunately that didn't seem to work, I have an ingress setup and if I browse to: `http://schema-registry.staging.local/` I get `{}` if I browse to `http://schema-registry.staging.local/subjects` I get `[["connect-jdbc-hours-value","connect-jdbc-reservation-value"]`

And those are from my web browser so its working from my browser

**Comment by squ1d123** [comment]
Make sure you have CORS enabled.
https://github.com/Landoop/schema-registry-ui#prerequisites

**Comment by bradenwright** [comment]
That worked, thank you kindly!  When I get back next week I'll try to add some info to the docs, and correct a few things I noticed in docs.
