### ISSUE TITLE
[stable/superset] Unable to set env vars

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [helm/charts#5736]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: Any

**Which chart**: stable/superset

**What happened**: It's impossible to set env vars to use them in the config file.

**What you expected to happen**: To be able to set env vars from secret, configMap, value file

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by mattjmcnaughton** [comment]
Happy to add this feature @SharpEdgeMarshall! Will submit a pr soon :)

**Comment by SharpEdgeMarshall** [comment]
I'm making it now 😂

**Comment by mattjmcnaughton** [comment]
Oh haha, great! Happy to review :)
