### ISSUE TITLE
[stable / percona-xtradb-cluster] default failureThreshold in probes causes SST to never complete (CrashLoopBackOff)

### ISSUE THREAD

**Issue by isaldarriaga** [helm/charts#5762]
**Is this a request for help?**:
no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

K8s: 1.10 (CDK)

**Which chart**:
stable/percona-xtradb-cluster

**What happened**:
Cluster nodes go into an inconsistent state (CrashLoopBackOff) after they are restarted by the liveness probes in the middle of an SST. 

The cause: every time a node starts the initialization process will check for the existence of /var/lib/mysql/.sst/
if the folder exists it will loop over the database folders (/var/lib/mysql/.sst/my-database) and synchonize any table file into that folder. 

At this point the "database" container has not started yet. the "logs" container show the system is "waiting for the streaming to complete".

this process can take long depending on the size of the database(s).

The readiness probe fires (after 30 second delay) and if the probe command doesn't complete without error it will restart the pod after the 3rd attempt (default failureThreshold). since the container is initializing, this always evaluates to an error state.

the pod is recreated, the database container is reinitialized, the .sst folder is wiped out and the SST start over again.

any of the nodes can easily go into this CrashLoopBackOff.

I saw it on a 3M+ records database.

**What you expected to happen**:

The liveness probe to give more room before restarting the pod.
the readiness probe to give more room for the SST to complete.

**How to reproduce it** (as minimally and precisely as possible):

FAILURE
3 node cluster
1 database
1 table (1M+ records)
perform insertions over node 1
watch for the /var/lib/mysql/.sst folder to appear in node 2 or 3
delete the pod 2 or 3
wait for the statefulset to spawn the new pod
monitor the /var/lib/mysql/.sst/my-database folder's content in the new spawned pod
after 30 secs the readiness probe will fire, will retry 3 times and restart the pod
see how .sst folder is wiped out upon pod recreation
see how pod goes into CrashLoopBackOff state

SUCESS
set failureThreshold = 50
repeat the test
SST completes
node/cluster goes up

**Anything else we need to know**:
no

**Comment by pentago** [comment]
Is this triaged?

**Comment by twarkie** [comment]
Same problem for my setup. Any ideas how to handle this in a good way?

**Comment by tmirks** [comment]
@twarkie see #12912.
