### ISSUE TITLE
Explicitly set namespace in charts

### ISSUE THREAD

**Issue by wwsean08** [helm/charts#5777]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Helm charts should contain a namespace in order to avoid applying them to the wrong namespace based on the context that is set, especially if you render the helm charts to kubernetes templates locally and apply them (like I am doing).  This would require a few new values as well as a namespace object probably.

**Version of Helm and Kubernetes**:
not really applicable but:
Helm 2.9.1
Kubernetes: 1.8.x

**Which chart**: 
Mission Control (though probably others, I just haven't used them/checked to verify)

**What happened**:
Namespace is not explicitly set in the various objects

**What you expected to happen**:
Namespace is explicitly set in the metadata of the objects

**How to reproduce it** (as minimally and precisely as possible):
```
mkdir tmp
helm template --output-dir=tmp mission-control/
grep -ir namespace tmp/
# see there are no results
```

**Anything else we need to know**:
See also support case 82862
Willing to submit a pull request as I've already implemented this for work.

**Comment by wwsean08** [comment]
Ignore this, I just realized JFrog support sent me here but they don't have their charts here

**Comment by krancour** [comment]
fwiw, the lack of namespaces in Helm chart templates is quite deliberate. Helm itself allows you to specify a namespace at the time of installation using a command line flag. When you do that Helm automatically adds the desired namespace to every manifest as templates are rendered.

**Comment by wwsean08** [comment]
That makes sense, my knowledge of helm is minimal as we aren't able to run it where I work so I just have to render the templates locally using helm template which I didn't realize before just now when I checked has a namespace option
