### ISSUE TITLE
Spark 2.3.0 Image

### ISSUE THREAD

**Issue by sudhanshu-dev** [helm/charts#5799]
**Is this a request for help?**:

I am using spark chart for spark cluster. 
Current Chart deploy spark version 1.5.1 but I wanted to deploy 2.3.0.
How can I build docker image with latest spark?

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by mhamilton723** [comment]
Can this be repopened please. I can help if someone can share the dockerfile used to create the 1.5.1 version
