### ISSUE TITLE
How to use H2 and not install postgres?

### ISSUE THREAD

**Issue by jasoncarreira** [helm/charts#5835]
**Is this a request for help?**:

Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:

kubernetes cluster v1.9.3
kubectl            v1.10.3
helm client        v2.8.2+ga802316
helm server        v2.9.0+gf6025bb

**Which chart**:

Keycloak 0.4.0

**What happened**:

Trying to get a test version of Keycloak up and running against H2 for integration tests. I put `keycloak.persistence.dbVendor` to `H2` and `keycloak.persistence.deployPostgres` to `false`. It fails with

```Error: render error in "preview/charts/keycloak/templates/statefulset.yaml": template: preview/charts/keycloak/templates/_helpers.tpl:39:12: executing "keycloak.postgresql.fullname" at <{{template "postgres...>: template "postgresql.fullname" not defined```

If I don't put `keycloak.persistence.deployPostgres` to `false` it deploys Postgres.

**What you expected to happen**:

I want it to bring up Keycloak running against an embedded H2

**How to reproduce it** (as minimally and precisely as possible):
Here's my values.yaml:
```
keycloak:
  persistence:
    deployPostgres: false
    dbVendor: H2
```

**Anything else we need to know**:

I also have a `keycloak.username`, `keycloak.password`, and `keycloak.preStartScript` defined

**Comment by unguiculus** [comment]
The chart does not support H2. I can deploy Postgres or you can use a separate Postgres or MySQL database.
