### ISSUE TITLE
[stable/prometheus]: Ingress template gives error

### ISSUE THREAD

**Issue by JanetPost** [helm/charts#5858]
**Is this a request for help?:** Yes

---

**Is this a BUG REPORT or FEATURE REQUEST? (choose one):** Bug report

**Version of Helm and Kubernetes:**

Helm:  2.7.2
Kube:  1.9.5

helm version --tiller-namespace kube-system
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart:**  stable/prometheus

**What happened:**

When trying to run the chart (with ingresses set to true), I received a template error on the hosts: list entries.

helm install stable/prometheus --name monitoring -f testfile.yaml --tiller-namespace kube-system --namespace monitoring
Error: render error in "prometheus/templates/alertmanager-ingress.yaml": template: prometheus/templates/alertmanager-ingress.yaml:26:21: executing "prometheus/templates/alertmanager-ingress.yaml" at <$url>: wrong type for value; expected []interface {}; got []string

**What you expected to happen:**  

If I set ingress to false and comment out the host, than the chart installs properly.

**How to reproduce it (as minimally and precisely as possible):**

In the values.yaml file (which I copied to testfile.yaml), make the following changes.  (Comments and extrenuous settings removed:

```
alertmanager:
  ingress:
    enabled: true
    hosts:
       - alertmanager.redacted.domain.com
```

I get the same error with this change as well:

```
server:
  ingress:
    enabled: true
    hosts:
       - prometheus.redacted.domain.com
```

I did not test other ingresses.

**Anything else we need to know:**

Not that I'm aware of....

**Comment by eloo** [comment]
same for me..
maybe it has something to do with
https://github.com/kubernetes/charts/commit/f9cad1de7afcf8fce054f2719c90f06f00480c2e#diff-df2ae7eac33e8bdd2087f7c23127bf4b
?

**Comment by eloo** [comment]
@HaveMyIcingAndEatItToo 
have solved this for me. it was the tiller & helm version. looks like you need at least version 2.8 of both
