### ISSUE TITLE
[stable/rabbitmq-ha] High CPU usage at "idle" from livelinessProbe and readinessProbe

### ISSUE THREAD

**Issue by mjrsnyder** [helm/charts#5873]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
helm: 2.7.2
kubernetes: 1.9.6

**Which chart**:
stable/rabbitmq-ha

**What happened**:
After running `helm install` the running pod consumes ~100% of a cpu core.

![image](https://user-images.githubusercontent.com/2317378/40859949-843cd6bc-65b1-11e8-9ca7-f6262fc919e3.png)

Removing the `livelinessProbe` and `readinessProbe` after helm finishes the deployment and restarting the rabbitmq pod reduces the cpu usage dramatically.  I think this issue is related to #3855 in [stable/rabbitmq]

The issue seems to stem from a high max number of processes.  Adding an option to set `ulimit -n {{ .Values.processesUlimit }}` in the container command may provide a temporary solution.  Here's a link to a report of this issue (it is rather old) https://groups.google.com/forum/#!topic/rabbitmq-users/hO06SB-QBqc

**What you expected to happen**:
not use 100% cpu

**How to reproduce it** (as minimally and precisely as possible):
``` shell
helm install --name hungry-rabbit \ 
stable/rabbitmq-ha \
--set rbac.create=false \
--set replicaCount=1 
```

**Anything else we need to know**:
I am running helm from a Windows machine.
RabbitMQ functions fine, it just consumes way more resources than necessary.

**Comment by thomas-riccardi** [comment]
Related to https://github.com/kubernetes/charts/issues/3855 ? In the end, even with the ulimit applied, I still had high CPU usage on probes: `rabbitmqctl status` is slow (see https://github.com/kubernetes/charts/issues/3855#issuecomment-398766098)

**Comment by mjrsnyder** [comment]
I'm still having this issue
