### ISSUE TITLE
[stable/rabbitmq-ha] RabbitMQ does not deploy successfully

### ISSUE THREAD

**Issue by ghost** [helm/charts#5879]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Helm
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Kubernetes
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/rabbitmq-ha

**What happened**:
The first node appeared with status Running, nothing in the logs indicated an issue however the status did not progress beyond this point. After a few minutes, it's reported as unhealthy with the message **Readiness probe errored: rpc error: code = DeadlineExceeded desc = context deadline exceeded**.

**What you expected to happen**:
It to deploy

**How to reproduce it** (as minimally and precisely as possible):
I used the following command to deploy the chart:

```bash
helm install --name rabbitmq stable/rabbitmq-ha \
  --set rabbitmqErlangCookie=SNIP \
  --set persistentVolume.enabled=true \
  --set persistentVolume.name=rabbitmqdata \
  --set persistentVolume.size=5Gi \
  --set rabbitmqPassword=SNIP \
  --set rabbitmqUsername=SNIP \
  --set replicaCount=3 \
  --set rabbitmqMemoryHighWatermark=256MB \
  --set resources.limits.memory="256Mi" \
  --set resources.limits.cpu="100m" \
  --set persistentVolume.storageClass="rook-ceph-block" \
  --set prometheus.enabled=true
```

**Anything else we need to know**:
The following is the output from describing the unhealthy pod:

```
Name:           rabbitmq-rabbitmq-ha-0
Namespace:      default
Node:           kubernetes-node-3/10.3.0.22
Start Time:     Sat, 02 Jun 2018 13:11:15 +0100
Labels:         app=rabbitmq-ha
                controller-revision-hash=rabbitmq-rabbitmq-ha-9dd66bd57
                release=rabbitmq
                statefulset.kubernetes.io/pod-name=rabbitmq-rabbitmq-ha-0
Annotations:    checksum/config=e4abde45f623e231e1aa59428ed8721fd49942a68fbfa7ee1552a3d1266a2aea
Status:         Running
IP:             10.233.114.141
Controlled By:  StatefulSet/rabbitmq-rabbitmq-ha
Init Containers:
  copy-rabbitmq-config:
    Container ID:  docker://33a84ab40238092bc657ae95cba9d47813ddb3242cf6a4558fd1ec89166d2f1b
    Image:         busybox
    Image ID:      docker-pullable://busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      cp /configmap/* /etc/rabbitmq; rm -f /var/lib/rabbitmq/.erlang.cookie
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 02 Jun 2018 13:11:53 +0100
      Finished:     Sat, 02 Jun 2018 13:11:54 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /configmap from configmap (rw)
      /etc/rabbitmq from config (rw)
      /var/lib/rabbitmq from rabbitmqdata (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rabbitmq-rabbitmq-ha-token-fpx64 (ro)
Containers:
  rabbitmq-ha:
    Container ID:   docker://0a85a77cae92104d7ae0f455ecf87b7c52323c1035a801751f2da7a5d9ec0332
    Image:          rabbitmq:3.7-alpine
    Image ID:       docker-pullable://rabbitmq@sha256:8e98b9ca42b6afe78e89dc80a9328354198feeda90bb5f28d7e44f479900d0b1
    Ports:          4369/TCP, 5672/TCP, 15672/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Sat, 02 Jun 2018 13:12:02 +0100
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     50m
      memory:  256Mi
    Requests:
      cpu:      50m
      memory:   256Mi
    Liveness:   exec [rabbitmqctl status] delay=120s timeout=5s period=10s #success=1 #failure=6
    Readiness:  exec [rabbitmqctl status] delay=10s timeout=3s period=5s #success=1 #failure=3
    Environment:
      MY_POD_NAME:             rabbitmq-rabbitmq-ha-0 (v1:metadata.name)
      RABBITMQ_USE_LONGNAME:   true
      RABBITMQ_NODENAME:       rabbit@$(MY_POD_NAME).rabbitmq-rabbitmq-ha-discovery.default.svc.cluster.local
      K8S_HOSTNAME_SUFFIX:     .rabbitmq-rabbitmq-ha-discovery.default.svc.cluster.local
      K8S_SERVICE_NAME:        rabbitmq-rabbitmq-ha-discovery
      RABBITMQ_ERLANG_COOKIE:  <set to the key 'rabbitmq-erlang-cookie' in secret 'rabbitmq-rabbitmq-ha'>  Optional: false
      RABBITMQ_DEFAULT_USER:   SNIP
      RABBITMQ_DEFAULT_PASS:   <set to the key 'rabbitmq-password' in secret 'rabbitmq-rabbitmq-ha'>  Optional: false
      RABBITMQ_DEFAULT_VHOST:  /
    Mounts:
      /etc/rabbitmq from config (rw)
      /var/lib/rabbitmq from rabbitmqdata (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rabbitmq-rabbitmq-ha-token-fpx64 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  rabbitmqdata:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  rabbitmqdata-rabbitmq-rabbitmq-ha-0
    ReadOnly:   false
  config:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  configmap:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rabbitmq-rabbitmq-ha
    Optional:  false
  rabbitmq-rabbitmq-ha-token-fpx64:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rabbitmq-rabbitmq-ha-token-fpx64
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age               From                        Message
  ----     ------                 ----              ----                        -------
  Normal   Scheduled              13m               default-scheduler           Successfully assigned rabbitmq-rabbitmq-ha-0 to kubernetes-node-3
  Normal   SuccessfulMountVolume  13m               kubelet, kubernetes-node-3  MountVolume.SetUp succeeded for volume "configmap"
  Normal   SuccessfulMountVolume  13m               kubelet, kubernetes-node-3  MountVolume.SetUp succeeded for volume "rabbitmq-rabbitmq-ha-token-fpx64"
  Normal   SuccessfulMountVolume  13m               kubelet, kubernetes-node-3  MountVolume.SetUp succeeded for volume "config"
  Normal   SuccessfulMountVolume  13m               kubelet, kubernetes-node-3  MountVolume.SetUp succeeded for volume "pvc-0c7fff56-665e-11e8-a6dd-de1a1825d013"
  Normal   Pulling                13m               kubelet, kubernetes-node-3  pulling image "busybox"
  Normal   Started                13m               kubelet, kubernetes-node-3  Started container
  Normal   Pulled                 13m               kubelet, kubernetes-node-3  Successfully pulled image "busybox"
  Normal   Created                13m               kubelet, kubernetes-node-3  Created container
  Normal   Pulling                13m               kubelet, kubernetes-node-3  pulling image "rabbitmq:3.7-alpine"
  Normal   Pulled                 13m               kubelet, kubernetes-node-3  Successfully pulled image "rabbitmq:3.7-alpine"
  Normal   Created                13m               kubelet, kubernetes-node-3  Created container
  Normal   Started                13m               kubelet, kubernetes-node-3  Started container
  Warning  Unhealthy              4m                kubelet, kubernetes-node-3  Liveness probe errored: rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  Unhealthy              44s (x2 over 6m)  kubelet, kubernetes-node-3  Readiness probe errored: rpc error: code = DeadlineExceeded desc =context deadline exceeded
```

**Comment by maran-maran** [comment]
I tried to deploy rabbitmq-ha chart to. And **FAILED to**..

Reason: rediness probe failed because of nonexistent hostname.

In our k8s cluster: a headless service DNS name isn't created until a readiness probe pass true.
- DNS hostname would exist only if the readiness probe pass true!
- The readiness probe would pass true only if DNS hostname exist.

workaround:
I had to add the annotation "service.alpha.kubernetes.io/tolerate-unready-endpoints: "true" to the service "rabbitmq-ha-discovery"

**Comment by gdmello** [comment]
@lyptt - can you list the rabbitmq container logs?

**Comment by maran-maran** [comment]
I guess that @lyptt had the same problem as me..
And as I described the problem was in nonexistent DNS name.. 

Container log:
ERROR: epmd error for host openstack-rabbitmq-ha-0.openstack-rabbitmq-ha-discovery.ourdomain.sandbox.svc: nxdomain (non-existing domain)

**Comment by ghost** [comment]
@gdmello apologies for the late response. Fetching the logs results in nothing being returned with the following command:

```bash
kubectl -n my_namespace logs rabbitmq-rabbitmq-ha-0 -c rabbitmq-ha
```

There's no logs on the pod either.

**Comment by harishreddy-m** [comment]
Even basic install step is failing to deploy. Are there any undocumented steps to perform to install this chart?
### Environment
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

### Output
$ helm install stable/rabbitmq
Error: release pondering-panda failed: roles.rbac.authorization.k8s.io "pondering-panda-rabbitmq-endpoint-reader" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["get"]}] user=&{system:serviceaccount:kube-system:default d7811587-72f4-11e8-805b-0800274a0c0b [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]

$ helm install stable/rabbitmq-ha
Error: release harping-ant failed: roles.rbac.authorization.k8s.io "harping-ant-rabbitmq-ha" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["get"]}] user=&{system:serviceaccount:kube-system:default d7811587-72f4-11e8-805b-0800274a0c0b [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]

**Comment by gdmello** [comment]
@harishreddy-m - Yours is a different issue that the one originally reported here.

The serviceaccount by your Tiller pod, (configured via your local `helm` cli) does not have permissions to `GET /endpoints` on the apiserver. This is required for the pods to be able to discover themselves. Just use a SA with those permissions and your deployment will proceed.

**Comment by harishreddy-m** [comment]
If some one is facing similar error. This is the solution.
I am trying the approach explained in https://github.com/kubernetes/helm/blob/master/docs/rbac.md#example-deploy-tiller-in-a-namespace-restricted-to-deploying-resources-only-in-that-namespace

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: my-local
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-manager
  namespace: my-local
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["endpoints"]
  verbs: ["get"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-binding
  namespace: my-local
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: my-local
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
```

`helm init --service-account tiller --tiller-namespace my-local`

` helm install stable/rabbitmq-ha --namespace my-local --tiller-namespace my-local`

**Comment by damienbenon** [comment]
@sznmaran took a long time for me to see the logs but you aimed well. This can happen when coredns is used in place of kube-dns and this annotation is required for the first node to start successfully.

Thanks for pointing that!

**Comment by chenww** [comment]
@sznmaran did you fix the issue as I am facing the same?

**Comment by damienbenon** [comment]
@chenww adding annotation `service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"` on the rabbitmq discovery service from @sznmaran [workaround] (https://github.com/helm/charts/issues/5879#issuecomment-394438047) fixed the issue for me.

**Comment by phlegx** [comment]
I still have this message with rabbitmq-ha helm version `1.27.1` Any ideas?

**Comment by phlegx** [comment]
`Version 1.29.0` still has this issue.

**Comment by MrAmbiG** [comment]
i am using bitnami/charts, 1.41.1 worked for me. Latest version has the same issue.
