### ISSUE TITLE
Kubeless UI + Ingress is alive but it does not display Kubeless functions

### ISSUE THREAD

**Issue by ghost** [helm/charts#5881]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm v2.8.0  / Kubernetes v1.10.1

**Which chart**: kubeless

**What happened**: Ingress for UI works but can't see Kubeless functions in it.

**What you expected to happen**: Should see functions in the UI just as I do with `kubeless function ls`.

**How to reproduce it** (as minimally and precisely as possible): Enable ingress, set service type to ClusterIP.

**Anything else we need to know**: Using nginx-ingress, TLS, basic auth.

Ingress annotations are:

```
    external-dns.alpha.kubernetes.io/hostname: kubeless.my.cluster.fqdn.example.org
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: basic-auth-secret
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
```

```
$ kubeless function ls
NAME 	NAMESPACE	HANDLER   	RUNTIME  	DEPENDENCIES	STATUS
hello	default  	test.hello	python2.7	            	1/1 READY
```
<img width="669" alt="screen shot 2018-06-02 at 4 58 02 pm" src="https://user-images.githubusercontent.com/13571670/40880833-35f33bf6-6686-11e8-8eff-26097a518f85.png">

ref: https://github.com/kubernetes/charts/pull/5623   @alexvicegrab

**Comment by alexvicegrab** [comment]
Not sure this is an issue with the Ingress...

Could you try to port-forward the pod directly to your machine by something like:

```
kubectl -n kubeless port-forward kubeless-kubeless-ui-<ETC> 4000:3000
```

And access http://localhost:4000 on your own machine to see if the functions are displayed?

**Comment by alexvicegrab** [comment]
I think the most likely issue is something in the communication of the Kubeless UI with the system, as in my case the Ingress works well, and reflects all Kubeless functions I made, regardless of whether I created them via the ingress or via the CLI.

Perhaps the Kubeless-UI logs might shed some light?

**Comment by ghost** [comment]
Thanks @alexvicegrab . You're right the ingress isn't the issue. Portforwarding the service and the pod gives the same result.  I think my issue is that I'm deploying the chart to the `default` namespace not `kubeless`.

**Comment by alexvicegrab** [comment]
Yes, the namespace definitely needs to be `kubeless`, let me know if changing the namespace does not work.

**Comment by ghost** [comment]
Thanks @alexvicegrab. Unfortunately, I won't be able to use kubeless in an alternative namespace right now. I'll close this accordingly.
