### ISSUE TITLE
Pulling Popularity / Downloads for stable charts

### ISSUE THREAD

**Issue by hh** [helm/charts#5899]
It would be useful to know which charts are heavily used.

/cc @viglesiasce

**Comment by hh** [comment]
Reached out to @mattfarina for acess to the helm chart log bucket?

**Comment by mattfarina** [comment]
@hh Sorry this fell to the wayside. Do you have what you need now?

**Comment by almazik** [comment]
it would definitely be useful to see the download/usage statistics for helm charts

**Comment by hh** [comment]
I'd like to get access to the correct bucket for processing.
Are there any other efforts using the data? @mattfarina

**Comment by hh** [comment]
@viglesiasce can I get access to the helm log bucket? hh@ii.coop

**Comment by viglesiasce** [comment]
Hey folks!!

Sorry that I have been remiss in responding. I'll figure out the right way to make the info public. I believe there are a few hoops I need to jump through on my end but will start the process of figuring it out.

**Comment by gerred** [comment]
Hi @viglesiasce have you had any time for this? Thanks!
