### ISSUE TITLE
Zookeeper consider not using init containers

### ISSUE THREAD

**Issue by chrislovecnm** [helm/charts#59]
Hey all

In order to simplify the zookeeper example a bit, should we consider not using init containers?  Seems a bit complicated, and I am not sure if it is adding value.

**Comment by viglesiasce** [comment]
If we can come up with a simpler way that does not involve init containers I'm all for it.

**Comment by lachie83** [comment]
@chrislovecnm Thanks for filling an issue. Definitely something that I would like to achieve if possible. 

I've given this a little further thought -- The only other way would to be to put this logic into an entrypoint which yields the same result under although it would be under a user-built container which is what we were trying to avoid. 

Reading the documentation out there and the current stance, init-containers don't see like a bad way of doing things. In saying that, I would be excited to see a simpler solution. I'd be interested to hear what you had in mind @chrislovecnm.

For reference. Init-containers or entrypoint discussion.
http://kubernetes.io/docs/user-guide/production-pods/#handling-initialization
http://kubernetes.io/docs/user-guide/petset/bootstrapping/#overview

**Comment by lachie83** [comment]
Resolved as part of #359
