### ISSUE TITLE
[incubator/elasticsearch] health check fails on minikube

### ISSUE THREAD

**Issue by AmazingTurtle** [helm/charts#5909]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-04-10T12:46:31Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

**Which chart**:
incubator/elasticsearch

**What happened**:
Health check fails for all pods (client, master, data)

**What you expected to happen**:
Health check succeeds

**How to reproduce it** (as minimally and precisely as possible):
Just repeat steps from https://github.com/kubernetes/charts/issues/5891 since this issue here is what happened right after I fixed DNS in minikube.

**Anything else we need to know**:
`kubectl logs` says that everything's up. From within minikube I'm able to curl the ip of the pod (which is exactly the same as the health check one) successfully. This maybe relates to a minikube issue. However  the health check for `stable/postgresql` succeeds, maybe because it's a different one (exec inside pod instead of http).

**Comment by oleksiSh** [comment]
Have same in docker-for-desktop.
For me it happens if I try to use one of latest elasticsearch charts (have tried 1.4.0, 1.3.0, 1.2.1).
