### ISSUE TITLE
[stable/minio] GCS Gateway Credentials not passed correctly

### ISSUE THREAD

**Issue by chrisatomix** [helm/charts#5911]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**: Helm 2.9.1, Kubernetes 1.10.2-gke.3 (running on GKE)

**Which chart**: stable/minio

**What happened**: Attempted to deploy Minio chart using GCS as backend gateway, credentials are not passed. Pods exited with error:
`Error: Unable to initialize gateway layer`

**What you expected to happen**:
Minio pod should start with GCS bucket as storage backend

**How to reproduce it** (as minimally and precisely as possible):
1. Download GCS service account credentials to JSON file (eg `our-project-credentials.json`)
2. Download default `values.yaml` file and apply the following changes:
```yaml
# values.yaml
persistence:
  enabled: false

gcsgateway:
  enabled: true
  # credential json file of service account key
  gcsKeyJson: "./our-project-credentials.json"
  # Google cloud project-id
  projectId: "our-project-123456"
```
3. Deploy helm chart:
```bash
helm install --name minio-production -f values.yaml stable/minio
```

```bash
$ kubectl get pods
NAME                                                    READY     STATUS    RESTARTS   AGE
minio-production-8498712-qjf99                        0/1       Error     0          11s

$ kubectl logs minio-production-8498712-qjf99
Created minio configuration file successfully at /root/.minio
Error: Unable to initialize gateway layer
```

**Anything else we need to know**:
* The README file is improperly formatted (last row in table is broken)
* Our GCS credentials work perfectly via a standard Kubernetes deployment of minio (we have rolled back to using this for now)
* When viewing the secret, it looks like it's only storing the JSON filename, not the contents of it
* It isn't clear exactly how to pass the JSON file (or its contents) to the Helm chart (via values or a helm `--set` argument), I have been unable to find a similar example to get this working

At a guess, I'm wondering if the `secrets.yaml` file shouldn't be this:
```yaml
{{- if .Values.gcsgateway.enabled }}
  gcs_key.json: {{ .Values.gcsgateway.gcsKeyJson | b64enc }}
{{- end }}
```
but instead something like this:
```yaml
{{- if .Values.gcsgateway.enabled }}
  gcs_key.json: {{ .Files.Get .Values.gcsgateway.gcsKeyJson | b64enc }}
{{- end }}
```

I spent longer than I would have liked trying to get this working, I assumed it was my own lack of understanding but now I'm thinking it might be that this was merged without testing?

Thanks

**Comment by shootmenow13** [comment]
I'm having the same exact issue. I created a secret with the JSON file and used it in a Kubernetes deployment without issue. However, the chart does not work.

**Comment by halbritt** [comment]
This is still a problem.  Wondering if anyone has a workaround?

**Comment by dennybritz** [comment]
/remove-lifecycle stale

I can confirm there is an issue with this chart. There are two problems:

1. The environment variable `GOOGLE_APPLICATION_CREDENTIALS` is set to the JSON content in the secret, but it should be set to the path to the JSON file.
2. Even if the above is solved there seems to be an issue with newlines in the json config. The original config from Google has newlines characters escaped, but it seems like when the base64 is decoded by Kubernetes the newlines are no longer escaped but are in the decoded JSON. This causes the gcloud libraries to fail on parsing the config.

I don't have time to submit a PR, but I got it to work on my deployment using the following. It's quite ugly so there probably is a better way, but I'm not an expert.

In the deployment, change the env variable:

```yaml
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/tmp/credentials.json"
```

And change the command:

```yaml
          command: [ "/bin/sh", 
          "-ce", 
          "cat /etc/credentials/gcs_key.json | sed ':a;N;$!ba;s/\\n/\\\\n/g' > /tmp/credentials.json &&
          cp /tmp/config.json {{ .Values.configPath }} && 
          /usr/bin/docker-entrypoint.sh minio -C {{ .Values.configPath }} gateway gcs {{ .Values.gcsgateway.projectId }}"]
          {{- else }}
```

**Comment by SubatomicHero** [comment]
Still a problem for me too. I think the solution needs a couple of approaches:

- `gcsgateway.encodedJson` should be an already base64 encoded json file that the chart then decodes
- `gcsgateway.fileJson` should be a link to the file as already mentioned by @chrisatomix 

This provides multiple approaches as to how to pass in the file which should then be copied to the correct location

**Comment by ChethanUK** [comment]
> how to pass

@SubatomicHero were you able to deploy?

**Comment by yartem** [comment]
I'm observing the same issue

**Comment by yartem** [comment]
As I can see, both PRs listed in current issue are closed:
- https://github.com/helm/charts/pull/9477/files
- https://github.com/helm/charts/pull/9869/files

Should we re-open this issue ?

**Comment by yartem** [comment]
Oh wow I just learned this project is no longer supported :/
