### ISSUE TITLE
[stable/traefik] service type ClusterIP does not work with externalTrafficPolicy

### ISSUE THREAD

**Issue by gmorse81** [helm/charts#5949]
I have an internal instance of the traefik chart and i have the service type set to ClusterIP. Because of this, i get an error when attempting to deploy traefik.

"Invalid value: "Cluster": ExternalTrafficPolicy can only be set on NodePort and LoadBalancer service"

Should the condition for externalTrafficPolicy be changed to only be added if the service type is not ClusterIP?

**Comment by krancour** [comment]
Sound like it, yes. Although I can't quite understand the use case that would lead one to select ClusterIP as the service type. The point of an ingress controller (as the "ingress" in its name would imply) is to route traffic coming _into_ the cluster. If you're using Traefik with service type ClusterIP, it sounds like you're using it to route traffic _within_ the cluster instead. That sounds odd and inefficient.

But again, yes. If there's a legitimate use case for this, then it sounds like setting or not setting `ExternalTrafficPolicy` on the basis of the service type is necessary.

**Comment by gmorse81** [comment]
An Ingress (object) is really just a way to define configuration for a reverse proxy (ingress controller). in my use case I have an external ingress controller which handles traffic coming into the cluster. The external ingress controller routes most of the traffic (but not all) to a couple middleware services. Those middleware services are not smart enough to route traffic based on path, so they blindly forward the traffic to the internal ingress (running as ClusterIP). The internal ingress routes to the correct service based on path.

**Comment by Tawmu** [comment]
Yup - still an issue. It seems like setting `--set externalTrafficPolicy=` will fix it
