### ISSUE TITLE
Invalid image name for mariadb

### ISSUE THREAD

**Issue by giggio** [helm/charts#5972]
**Is this a request for help?**:
No.

**Is this a BUG REPORT or FEATURE REQUEST?**
Bug report.

**Version of Helm and Kubernetes**:
Helm:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

k8s:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
mariadb

**What happened**:
The latest mariadb chart produces the incorrect image name. With debug, this is the image created:

````yaml
image: "map[pullPolicy:IfNotPresent repository:bitnami/mariadb tag:10.1]"
````

**What you expected to happen**:
Release created successfully

**How to reproduce it** (as minimally and precisely as possible):
This yaml:
````yaml
image:
  repository: bitnami/mariadb
  tag: '10.1'
  pullPolicy: IfNotPresent
rootUser:
  password: pwd
  forcePassword: true
db:
  user: user
  password: pwd2
  name: db
  forcePassword: true
````

Run:

````bash
helm install --name mariadb-release -f values.yaml --debug stable/mariadb
````

**Anything else we need to know**:
It works perfectly with version 4.1.1.

Here are the events from pod describe:
````
Events:
  Type     Reason                 Age               From                               Message
  ----     ------                 ----              ----                               -------
  Warning  FailedScheduling       2m (x7 over 2m)   default-scheduler                  PersistentVolumeClaim is not bound: "oh-mariadb-release-mariadb"
  Normal   Scheduled              1m                default-scheduler                  Successfully assigned oh-mariadb-release-mariadb-78d444799f-tzrzr to aks-agentpool-95095170-0
  Normal   SuccessfulMountVolume  1m                kubelet, aks-agentpool-95095170-0  MountVolume.SetUp succeeded for volume "config"
  Normal   SuccessfulMountVolume  1m                kubelet, aks-agentpool-95095170-0  MountVolume.SetUp succeeded for volume "default-token-7cxgz"
  Normal   SuccessfulMountVolume  20s               kubelet, aks-agentpool-95095170-0  MountVolume.SetUp succeeded for volume "pvc-a7085792-69b6-11e8-9ed1-0a58ac1f09f2"
  Normal   Pulled                 19s               kubelet, aks-agentpool-95095170-0  Container image "busybox" already present on machine
  Normal   Created                19s               kubelet, aks-agentpool-95095170-0  Created container
  Normal   Started                19s               kubelet, aks-agentpool-95095170-0  Started container
  Warning  InspectFailed          2s (x3 over 18s)  kubelet, aks-agentpool-95095170-0  Failed to apply default image tag "map[pullPolicy:IfNotPresent repository:bitnami/mariadb tag:10.1]": couldn't parse image reference "map[pullPolicy:IfNotPresent repository:bitnami/mariadb tag:10.1]": invalid reference format
  Warning  Failed                 2s (x3 over 18s)  kubelet, aks-agentpool-95095170-0  Error: InvalidImageName
````

**Comment by mattjmcnaughton** [comment]
Hmm, I'm not seeing this error when I try and install the latest `mariadb` release. What happens if you run `helm repo update` and then try again?

**Comment by giggio** [comment]
Yes, I tried after a `helm repo update` and `4.2.1`, which I was using a week ago, is now working. I also tested `4.2.2` and `4.2.3` and they all work. Thanks.
