### ISSUE TITLE
[stable/redis] The current architecture can not collect metrics from multiple slaves.

### ISSUE THREAD

**Issue by 7CHANHO** [helm/charts#5977]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**Version of Helm and Kubernetes**: 
- Kubernetes: v1.9.7_1510
- Helm: v2.9.1

**Which chart**: stable/redis

**What happened**:
The current architecture can not collect metrics from multiple slaves.
Because, the redis-exporter collects metrics from the service.
Even if there are multiple slaves, the instance collected in the Promethean will still be one.
```
[Prometheus] ---> [Redis-Exporter] ---> [Service of Master Node] ---> [Master Node Pod]
                                     └> [Service of Slave Node]  ---> [Slave Node Pod 1]
                                                                   └> [Slave Node Pod 2]
```
If the Redis exporter is deployed as a sidecar, we can use the discovery feature of Kubernetes.
Also, we can collect metrics from multiple slaves.
```
[Prometheus] ---> [Master Node Pod]  ---> [Redis-Exporter of Master Node]
               └> [Slave Node Pod 1] ---> [Redis-Exporter of Slave Node 1]
               └> [Slave Node Pod 2] ---> [Redis-Exporter of Slave Node 2]
```

**What you expected to happen**: 

**How to reproduce it** (as minimally and precisely as possible):
You can reproduce it by helm install with stable/redis.

**Anything else we need to know**:
If you agree with my opinion, I will pr a chart to deploy Redis-exporter as a sidecar.

**Comment by varunpalekar** [comment]
I am also agree with @7CHANHO . We should add redis exporter as sidecar as this is prometheus way to monitor. We can also add this to stable/redis-ha chart

**Comment by mattnenterprise** [comment]
Was anyone going to set this up ?
