### ISSUE TITLE
[stable/anchore-engine] Unable to run in minikube

### ISSUE THREAD

**Issue by MMartyn** [helm/charts#5988]
**Is this a request for help?**: 
Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
BUG REPORT

**Version of Helm and Kubernetes**: 
Helm: 2.9.1,
Kubernetes: 1.10
Minikube: 0.27.0

**Which chart**: 
stable/anchore-engine

**What happened**:
The engine core deployment never completely comes up. The logs for the core engine either repeatedly says "[WARN] required service (policy_engine) is not (yet) available" or "[WARN] required service (simplequeue) is not (yet) available"

**What you expected to happen**:
I would expect that it eventually comes up and can be interacted with via anchore-cli.

**How to reproduce it** (as minimally and precisely as possible):
Install the helm chart into the latest minikube.

**Anything else we need to know**:
If it isn't expected to work in minikube that's fine, but would like confirmation.

Thanks.

**Comment by zhill** [comment]
hi @MMartyn , I'll take a look at the minikube process. I've had issues with some networking configuration in the past due to the way minikube sets up the network and that anchore-engine interacts with both other pods as well as its own pod (for local services). I'm getting ready to roll and upgrade for the helm chart so I'll double-check minikube compatibility as well. We definitely expect minikube to be able to run the chart.

**Comment by zhill** [comment]
@MMartyn I ran into the issue, which is https://github.com/kubernetes/minikube/issues/1568, where pods that are part of a service cannot reach each other via the service dns name (but localhost works if in same pod). So this looks to be a minikube issue independent of the anchore chart itself.

You can verify by exec into the anchore-engine core pod and trying to curl from the service name:
`curl http://<releasename>-anchore-engine:8083/v1/status`

You should get a 401 on that call, but if it hangs then it is probably the issue I mentioned above. For me it worked to use the workaround in that issue:
`minikube ssh`
`sudo ip link set docker0 promisc on`

Then, the anchore services are able to reach each other using the k8s service endpoint defined in the chart.

**Comment by MMartyn** [comment]
@zhill That was totally it. Thanks for the help. Much appreciated.
