### ISSUE TITLE
[stable/minecraft] Kubernetes Helm external-ip address pending stuck need resolution 

### ISSUE THREAD

**Issue by quantum-fusion** [helm/charts#5991]
**Is this a request for help?**:

This is a problem with kubernetes not issuing a public external IP address on this cluster.

I need to know the command to help issue the external ip address of the service for the minecraft example.

I also need the proper full path URL for the service at http://localhost:25565 , because it will not come up in Safari.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT.

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-07-26T00:12:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
https://hub.kubeapps.com/charts/stable/minecraft

**What happened**:

NAME                      CLUSTER-IP   EXTERNAL-IP   PORT(S)           AGE
awesomeserver-minecraft   10.0.0.247   <pending>     25565:32279/TCP   26m

**What you expected to happen**:

NAME                                  TYPE                 CLUSTER-IP   EXTERNAL-IP   PORT(S)           AGE
awesomeserver-minecraft LoadBalancer   10.0.0.247   13.90.155.253     25565:32279/TCP   26m

**How to reproduce it** (as minimally and precisely as possible):

% helm install --name awesomeserver     --set minecraftServer.eula=true,minecraftServer.Difficulty=hard     stable/minecraft --namespace minecraft

% kubectl get svc --namespace minecraft -w awesomeserver-minecraft

**Anything else we need to know**:

**Comment by quantum-fusion** [comment]
@AdamDang Please help with the command to expose the external ip address for minecraft to kubernetes, please provide example to get this example working.

**Comment by quantum-fusion** [comment]
kubectl logs deployment/awesomeserver-minecraft --namespace minecraft --follow=true
ERROR: unable to write eula to /data. Please make sure attached directory is writable by uid=1000
/start: line 10: eula.txt: Permission denied
/start: line 11: eula.txt: Permission denied

**Comment by c-lliope** [comment]
I get the same error,

```
ERROR: unable to write eula to /data. Please make sure attached directory is writable by uid=1000
/start: line 10: eula.txt: Permission denied
/start: line 11: eula.txt: Permission denied
```

It seems like this might be a problem with the Persistent Volume?

I'm very new to Kubernetes, so I'm not sure how to dig deeper. Any suggestions?

**Comment by c-lliope** [comment]
I think my issue is a duplicate of #5300. The external IP issue is likely separate, because I get an external IP for my deployment despite the PV issue.

**Comment by quantum-fusion** [comment]
@graysonwright I am using minikube version minikube version: v0.21.0 , I am wondering which commands did you use in order to issue the external ip address?  I was able to get past the persistent volume storage error, by using the values.yaml file to initialize.

**Comment by quantum-fusion** [comment]
First try creating the values.yaml file with the one stored in the zip file attached, and then run the helm command to install the package using the values.yaml file.

[values.yaml.zip](https://github.com/kubernetes/charts/files/2087199/values.yaml.zip)

% helm install --name awesomeserver  -f values.yaml  stable/minecraft --namespace minecraft

Please let me know if this works, and let me know what you did if you are using minikube to create the external ip address. Let me know if you are running on MACOS.

**Comment by c-lliope** [comment]
@quantum-fusion ah, okay. I got past the error by applying the patch in #5300.

As for the external IP problem, I'm running on a Google Cloud Kubernetes instance. The IP hasn't been giving me problems on there, so I think there's a Minikube-specific problem at play.

Sorry I can't be more help!

**Comment by quantum-fusion** [comment]
@graysonwright how is the cost of running the google cloud kubernetes instances?  I am curious, because I have not yet tried this.  Were you able to get the minecraft user interface up and running?  It asks for login and password.

**Comment by c-lliope** [comment]
So far, I've been using the $300 free credit that Google gives to new users. It seems like it'll last about a month or so, and by then I want to move the cluster onto my own machines.

It's worth trying out, if only to see if it fixes the External IP issue.

**Comment by quantum-fusion** [comment]
@graysonwright Can you tell me line for line the commands that you are executing to get the minecraft example to work using google cloud kubernetes?  I want to see it actually work in action.

**Comment by quantum-fusion** [comment]
https://stackoverflow.com/questions/50750830/stable-minecraft-helm-chart-will-not-expose-external-ip-address-need-helm-or-kub?noredirect=1#comment88530873_50750830

**Comment by talbenari1** [comment]
@quantum-fusion You said you're running in minikube, which I don't believe has a LoadBalancer built into it. Did you set one up before installing the chart?
