### ISSUE TITLE
incubator/vault Vault Seal Status Unstable?

### ISSUE THREAD

**Issue by devinatencio** [helm/charts#5992]
**Is this a request for help?**:

Yes request for help.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT, FEATURE REQUEST (BOTH?)

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
incubator/vault

**What happened**:
I installed vault chart onto Kubernetes, and when I unsealed the container the health status inside Consul FLAPS between PASSING and CRITICAL. I am guessing it is because maybe the TTL isn't set or something else isn't happening fast enough to keep the status PASSING.

From what I can tell everything is configured right, it is possible I missed something. Hoping you can shed light on this?

**What you expected to happen**:
Status of Vault stays PASSING and healthy in Consul.

**How to reproduce it** (as minimally and precisely as possible):
Just deploy vault helm chart and inside a container unlock the vault and then go to consul and watch the status of "Vault Sealed Status".

**Anything else we need to know**:

Example just running this check over and over the status flaps.

[root@ip-10-134-0-64 ~]# curl http://localhost:8500/v1/agent/checks | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   452  100   452    0     0  89064      0 --:--:-- --:--:-- --:--:--  110k
{
  "vault:10.134.0.64:8200:vault-sealed-check": {
    "Node": "ip-10-134-0-64.ec2.internal",
    "CheckID": "vault:10.134.0.64:8200:vault-sealed-check",
    "Name": "Vault Sealed Status",
    "Status": "critical",
    "Notes": "Vault service is healthy when Vault is in an unsealed status and can become an active Vault server",
    "Output": "Vault Sealed",
    "ServiceID": "vault:10.134.0.64:8200",
    "ServiceName": "vault",
    "ServiceTags": [
      "active"
    ],
    "Definition": {},
    "CreateIndex": 0,
    "ModifyIndex": 0
  }
}
[root@ip-10-134-0-64 ~]# curl http://localhost:8500/v1/agent/checks | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   453  100   453    0     0  90473      0 --:--:-- --:--:-- --:--:--  110k
{
  "vault:10.134.0.64:8200:vault-sealed-check": {
    "Node": "ip-10-134-0-64.ec2.internal",
    "CheckID": "vault:10.134.0.64:8200:vault-sealed-check",
    "Name": "Vault Sealed Status",
    "Status": "passing",
    "Notes": "Vault service is healthy when Vault is in an unsealed status and can become an active Vault server",
    "Output": "Vault Unsealed",
    "ServiceID": "vault:10.134.0.64:8200",
    "ServiceName": "vault",
    "ServiceTags": [
      "active"
    ],
    "Definition": {},
    "CreateIndex": 0,
    "ModifyIndex": 0
  }
}

**Comment by kujenga** [comment]
I ran into what I believe was the same issue, and I was able to resolve it by setting `vault.readiness.readyIfSealed` to `true` in my installed release of the chart.

https://github.com/kubernetes/charts/blob/3168f8bba6ebd3284c84d45a3e670c414d771499/incubator/vault/values.yaml#L129

I'm not sure why this is off by default, since when the vault is sealed it then becomes unreachable through the service, making it difficult to go ahead and unseal.
