### ISSUE TITLE
Using Prometheus with the Kafka Chart

### ISSUE THREAD

**Issue by 1mihirpandya** [helm/charts#5993]
Hi! I am trying to use prometheus (via the Kafka chart), and am unsure of how to go about it. The config file and jar file necessary to access the metrics seem to have been made, but I'm not able to access them. What should I do?

**Is this a request for help?**:
Yes

**Comment by benjigoldberg** [comment]
Hi @1mihirpandya if you check out the [Kafka chart values file](https://github.com/helm/charts/tree/master/incubator/kafka#installing-the-chart) you can see we have two settings which should help you out:

`prometheus.jmx.enabled` and `prometheus.kafka.enabled` if you enable both of these features, both the JMX exporter and the Kafka Prometheus exporter will be installed and emit metrics for your Kafka cluster.

If you are using the Prometheus Operator (which we _strongly_ recommend you do) you will also want to enable that by setting the following to `true` as well: `prometheus.operator.enabled`

**Comment by benjigoldberg** [comment]
@1mihirpandya let me know if that addresses your question!

**Comment by ashishxooa** [comment]
@benjigoldberg, I have done exactly what you have mentioned, still it doesn't work for me. 

Details here. https://github.com/helm/charts/issues/15056

**Comment by nitishpt** [comment]
Hi @benjigoldberg I am trying to use the incubator/kafka chart with the configs as you have mentioned above. I have enabled `prometheus.jmx.enabled`, `prometheus.kafka.enabled` and `prometheus.operator.enabled`

But I am only able to find the `kafka_exporter` metrics in prometheus and there are no `jmx_exporter` metrics being exposed. I am not sure why that would be helping. Is there anything I am missing? Thanks!
