### ISSUE TITLE
[incubator/kafka] Kafka chart should use vanilla Kafka not confluent 

### ISSUE THREAD

**Issue by arianitu** [helm/charts#5996]
**Which chart**:
incubator/kafka

**What happened**:
incubator/kafka uses confluentinc/cp-kafka for its image which is not a standard vanilla kafka install

**What you expected to happen**:
incubator/kafka should use a Docker image that utilizes https://kafka.apache.org/downloads for its JARs instead of Confluents binaries. 

Just look at the tags for confluentinc/cp-kafka, what is 4.1.1. The latest Kafka version is 1.1.0, I don't want to push Confluent kafka 4.1.1, whatever that is.

**Anything else we need to know**:
incubator/kafka should be renamed to incubator/confluent-kafka and the eventual stable/kafka should be a vanilla Kafka installation with a vanilla ZooKeeper installation.

**Comment by cemsbr** [comment]
Confluent added the bug #7730.
