### ISSUE TITLE
helm install spinnaker failed

### ISSUE THREAD

**Issue by wtwde** [helm/charts#5999]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm: v2.9.1
Kubernetes version： v1.10.2

**Which chart**:
spinnaker

**What happened**:
"#helm install --name my-spinnaker stable/spinnaker"
log Error: timed out waiting for the condition 

#kubectl get pod
my-spinnaker-create-bucket-h676p                     0/1       CrashLoopBackOff    25         2h
my-spinnaker-jenkins-9b887f88b-gl4j7                 0/1       Init:0/1            0          2h
my-spinnaker-minio-66f4bbff45-8cfpl                  0/1       ContainerCreating   0          2h
my-spinnaker-redis-7b8978889d-5tgqp                  0/1       ContainerCreating   0          2h
my-spinnaker-spinnaker-clouddriver-64f597b7f-flw4b   1/1       Running             0          2h
my-spinnaker-spinnaker-deck-5698c5bf5c-4hmf6         1/1       Running             0          2h
my-spinnaker-spinnaker-echo-6c7bbc6db-vjhgd          0/1       Running             0          2h
my-spinnaker-spinnaker-front50-d99cb79f4-tmkmh       0/1       CrashLoopBackOff    24         2h
my-spinnaker-spinnaker-gate-759fc6d46f-gngjd         1/1       Running             41         2h
my-spinnaker-spinnaker-igor-979965d65-jkj6z          0/1       Running             0          2h
my-spinnaker-spinnaker-orca-559889df65-f6qlv         0/1       Running             0          2h
my-spinnaker-spinnaker-rosco-6dc547549-pt9gq         0/1       Running             0          2h

#kubectl describe pod my-spinnaker-redis-7b8978889d-5tgqp
there are issue
  Warning  FailedMount  6m (x51 over 1h)  kubelet, host2  Unable to mount volumes for pod "my-spinnaker-redis-7b8978889d-5tgqp_spinnaker(e2bd9567-6ad1-11e8-9b91-000002e9e1fc)": timeout expi
red waiting for volumes to attach/mount for pod "spinnaker"/"my-spinnaker-redis-7b8978889d-5tgqp". list of unattached/unmounted volumes=[redis-data]

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
1. deploy kubernetes by kubespray
2. install helm
3. run helm install --name my-spinnaker stable/spinnaker"

**Anything else we need to know**:

**Comment by vasya10** [comment]
@wtwde did you find a solution for this?
