### ISSUE TITLE
use official elasticsearch image

### ISSUE THREAD

**Issue by davidkarlsen** [helm/charts#6025]
feature-request:
  - Would it not be better to use the official elastic.inc image for elasticsearch?
https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
incubator/elasticsearch

**What happened**:
it uses  centerforopenscience/elasticsearch v5.x

**What you expected to happen**:
use official image

**Comment by davidkarlsen** [comment]
I see now that the image in use derives from the official upstream image but adding a plugin for discovery.

On the other side it looks like the plugin has been replaced with a "headless service":
https://github.com/fabric8io/elasticsearch-cloud-kubernetes#kubernetes-cloud-plugin-for-elasticsearch.

Maybe it makes sense to use a vanilla image, but add this service to the helm-chart?

**Comment by monotek** [comment]
There are already several pull requests available for this. This one for example: https://github.com/kubernetes/charts/pull/5663

Just use the search ;-)

**Comment by monotek** [comment]
And #5663 is merged. 
Please close...

**Comment by davidkarlsen** [comment]
Obsoleted by #5663
