### ISSUE TITLE
[stable/redis-ha] can't connect\resolve service endpoint provided after chart deployment

### ISSUE THREAD

**Issue by str1k3r** [helm/charts#6026]
**Is this a request for help?**:
Possible
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
K8S
1.10.2-gke.3

**Which chart**:
stable/redis-ha

**What happened**:
service endpoint DNS name, which was provided after chart deployment can't be resolved or connected 

**What you expected to happen**:
can connect to the redis instance\resolve it by DNS name

**How to reproduce it** (as minimally and precisely as possible):
1) helm install stable/redis-ha
2) try to connect using provided helm post-installation information:
    a) kubectl exec -it honking-woodpecker-redis-ha-master-0 bash
    b) using busybox instance and do nslookup of honking-woodpecker-redis-ha.default.svc.cluster.local DNS name

**Comment by thecodeassassin** [comment]
Duplicate of https://github.com/kubernetes/charts/issues/3197
