### ISSUE TITLE
Expose a way to control log levels 

### ISSUE THREAD

**Issue by lakarchitect** [helm/charts#6086]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

 FEATURE REQUEST

**Version of Helm and Kubernetes**:

Kubernetes 1.3 
Helm v2.9.0

**Which chart**:
Kafka Helm Chart

https://github.com/kubernetes/charts/tree/master/incubator/kafka

**What happened**:
Unable to change Kafka log levels, currently once helm chart is installed, it is writing TRACE level logs and unable to change this to higher level like debug or Info 

**What you expected to happen**:
Should be able to provide logging.properties location or logLevel=INFO .

**How to reproduce it** (as minimally and precisely as possible):
Deploy the Kafka Helm chart and check the logs, it prints the TRACE level debugging and there is no option to change it.

**Anything else we need to know**:
In general how do we control things like helm chart not provided but the underlying software provides those options to modify.

**Comment by benjigoldberg** [comment]
Thanks for the feature request @lakarchitect -- I will work on this shortly. 

As far as your last question, regarding how to control things that the chart doesnt expose -- as of now there is no real way to get at that information. The best bet is to submit a PR to expose the functionality or file a feature request as you have here.

**Comment by jfriedenstab** [comment]
Maybe it's still helpful:
You can control Kafka log levels by providing environment variables as described here:
https://docs.confluent.io/current/installation/docker/docs/operations/logging.html
You can set these environment variables for the Kafka Helm chart via `envOverrides` (see https://github.com/helm/charts/tree/master/incubator/kafka#installing-the-chart), e.g.:
```yaml
envOverrides:
  kafka.log4j.root.loglevel: INFO
  kafka.log4j.loggers: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
```
