### ISSUE TITLE
[stable/cockroachdb] Fails with --wait

### ISSUE THREAD

**Issue by Miouge1** [helm/charts#6096]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

**Which chart**:
stable/cockroachdb

**What happened**:
When installing with `--wait` the cluster is stuck in a `notReady` state, waiting for `cockroach init` post-install hook.

**What you expected to happen**:
I expected the `--wait` to work with that chart.

**How to reproduce it** (as minimally and precisely as possible):
Install cockroach chart with `--wait`

**Anything else we need to know**:

**Comment by dvasdekis** [comment]
Duplicate of #5266
