### ISSUE TITLE
[stable/nginx-ingress] Add autoscaler for default-backend

### ISSUE THREAD

**Issue by frasern** [helm/charts#6109]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

The default-backend deployment can have a `replicaCount` configured to control the number of running pods.

It would be nice if the chart also allowed a HorizontalPodAutoscaler to be configured for the default-backend so that it can be automatically scaled up should its load increase.

There is already a HPA for the nginx controller itself, which is disabled by default. I would suggest a HPA for the default-backend should work in much the same way

**Which chart**:
stable/nginx-ingress

**Comment by wreed4** [comment]
Why did this get no traction?? This seems like a pretty obvious enhancement.
