### ISSUE TITLE
Keycloak chart doesn't create user when using external Postgres

### ISSUE THREAD

**Issue by jasoncarreira** [helm/charts#6118]
**Is this a request for help?**:

Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

kubernetes cluster v1.9.3
kubectl            v1.10.1
helm client        v2.9.0+gf6025bb
helm server        v2.9.0+gf6025bb

**Which chart**:

Keycloak 1.2.0 & 2.0.0

**What happened**:

When I release the keycloak chart for my integration tests in a preview environment I use H2 and it creates the user using the keycloak.username and keycloak.password I supply in values.yaml. My build script uses kcadm.sh to config the credentials using these and it works.

Now I'm setting it up to release to my staging environment and I'm pointing it at an external Postgres that's service linked using an ExternalName to the service name postgres in my staging environment. Keycloak is coming up and is using my postgres database (i.e. I can see all of the tables it created and after I create the admin user I can log in, etc)

**What you expected to happen**:

I expected it to create the admin user so I can use it immediately.

**How to reproduce it** (as minimally and precisely as possible):

See above. The only difference between the chart releases is using the external postgres.

**Anything else we need to know**:

This is happening as part of a Jenkins-X managed pipeline.

**Comment by unguiculus** [comment]
Did you change the database and upgrade the chart? That would explain it. The user is only created when the chart is first installed.
