### ISSUE TITLE
Query # Kubernetes Charts # Support ppc64le (IBM Power)

### ISSUE THREAD

**Issue by snehlatamohite** [helm/charts#6137]
Hi,

1.	We have started validating helm charts from Kubernetes charts repository on ppc64le architecture. We validated a few  of helm charts (like consul, influxDB, Prometheus, kibana, nginx-ingress etc.) successfully on power by changing image to equivalent ppc64le image. We had to create multi-arch image and update helm charts to point to multi-arch manifests in order to make them available on Power. We feel that this approach is more portable. Please suggest if this approach is acceptable to the community.

2.	We modified docker-registry, ghost, odoo, owncloud, redmine charts locally in order to make them work on power. This was required mainly due to different PATH conventions used by Intel/Bitnami docker images and ppc64le images. For example, bitnami images use hardcoded /bitnami in PATH whereas ppc64le images use a different PATH convention.

There may be couple of approaches to handle this situation. One way is to update charts and make them conditional in order to support Power.  We would like to know which approach will be most preferred by the community.

Please suggest.

Thanks,
Snehlata Mohite.

**Comment by patlachance** [comment]
@snehlatamohite: could you please share your work?
