### ISSUE TITLE
[stable/grafana] clusterrolebinding specifies incorrect namespace for serviceaccount

### ISSUE THREAD

**Issue by matthew-walters** [helm/charts#6142]
Upon installing the chart with rbac enabled and sidecar.dashboards.enabled, 
the grafana-sc-dashboards container logs error 

`kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Fri, 15 Jun 2018 18:41:55 GMT', 'Content-Length': '266'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \\"system:serviceaccount:esi-monitoring:someserviceaccount\\" cannot watch configmaps at the cluster scope","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}\n'
`

I noticed the clusterrolebinding.yaml in specifying _default_ namespace for the serviceaccount:
https://github.com/kubernetes/charts/blob/master/stable/grafana/templates/clusterrolebinding.yaml#L18

I believe this line should be `namespace: {{ .Release.Namespace }}`

I've verified in minikube that this change fixes the issue

**Comment by amartorelli** [comment]
Hi,
I think this has broken something somehow. I've deployed grafana on Friday and everything worked fine, but I'm now seeing this message:
```
helm install --name grafana stable/grafana
Error: release grafana failed: ClusterRoleBinding.rbac.authorization.k8s.io "grafana-clusterrolebinding" is invalid: subjects[0].namespace: Required value
```
Do I need to specify something explicitly now?

**Comment by matthew-walters** [comment]
There is an issue with the fix.

It should be `{{ .Release.Namespace }} `  not   `{{ .Release.namespace }}`

**Comment by davidkarlsen** [comment]
See https://github.com/kubernetes/charts/pull/6158
