### ISSUE TITLE
add kibana health checks

### ISSUE THREAD

**Issue by davidkarlsen** [helm/charts#6150]
** FEATURE REQUEST** 

Implement readiness and liveliness probes for kibana.
use /status

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
kibana

**What happened**:
No health check, hence pods might be removed before the updates one is actually properly up.

**What you expected to happen**:
Have readiness probe, in order to check that pod is ready to serve traffic and kibana is up.

**How to reproduce it** (as minimally and precisely as possible):
do an upgrade, on a slow box there will be a window where kibana is not available because the new pod is not properly up, but the old is deleted.

**Anything else we need to know**:

**Comment by monotek** [comment]
done in: https://github.com/helm/charts/pull/6827
