### ISSUE TITLE
namespace problem

### ISSUE THREAD

**Issue by miramar-labs** [helm/charts#6153]
I'm creating a namespace 'kafka' and then doing this:

helm install --name my-kafka --set global.namespace=kafka incubator/kafka

didn't seem to place the pods in the kafka namespace .. they end up in the default namespace...

**Comment by Nodraak** [comment]
Hi

You should use the `helm install` flag `--namespace` instead

**Comment by Hermain** [comment]
The documentation states to do `helm install --name my-kafka --set global.namespace=kafka incubator/kafka` so it should be updated to prevent other newbies like me doing the thing.

**Comment by Nodraak** [comment]
PR welcome ;)
