### ISSUE TITLE
[stable/redis] Upgrade from 3.3.0 to 3.3.1 gives "Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden."

### ISSUE THREAD

**Issue by jacobsvante** [helm/charts#6170]
**Is this a request for help?**: Kind of

---

**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Version of Helm and Kubernetes**: v2.9.1 / v1.10.2

**Which chart**: stable/redis

**What happened**:
Getting this when upgrading from `3.3.0` to `3.3.1`:
> Error: UPGRADE FAILED: StatefulSet.apps "redis-test-redis-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.

**What you expected to happen**:
It should update smoothly

Might be related to https://github.com/kubernetes/charts/issues/3672.

**How to reproduce it** (as minimally and precisely as possible):

```
helm install --version 3.3.0 --name redis-test stable/redis
helm upgrade --version 3.3.1 redis-test stable/redis
```

Changed in v3.3.1:
https://github.com/kubernetes/charts/commit/6aba2d6e0e55551c1c4fd80ec4905565b8ed1c86#diff-b0a41cd32d00f359018fe75a301e4361

I fail to see how that can cause the problem, but my knowledge surrounding StatefulSets is quite limited.

Seems that this has been an issue with other charts as well:
https://github.com/kubernetes/charts/issues?utf8=%E2%9C%93&q=updates+to+statefulset+spec+for+fields+other+than+%27replicas%27%2C+%27template%27%2C+and+%27updateStrategy%27

**Comment by jacobsvante** [comment]
*Update*

Did some additional testing and this seems to effect other version upgrades as well, for example:

* 3.2.0 -> 3.2.1
* 3.3.1 -> 3.3.2

**Comment by mtparet** [comment]
Same issue on my side, cannot update redis chart..
