### ISSUE TITLE
Support external-dns 0.5.4

### ISSUE THREAD

**Issue by quater** [helm/charts#6174]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

External-DNS version 0.5.3 has been released, which now supports NodePort. In order for this version to work with NodePort, the RBAC permissions need to be extended in order to permit listing nodes.

https://github.com/kubernetes-incubator/external-dns/releases

**Version of Helm and Kubernetes**: N/A

**Which chart**: external-dns

**What happened**: New feature introduced (i.e. NodePort support) require changes to existing RBAC.

**What you expected to happen**: I will file a PR shortly.

**How to reproduce it** (as minimally and precisely as possible): N/A

**Anything else we need to know**: N/A

**Comment by quater** [comment]
Created this https://github.com/kubernetes/charts/pull/6176 PR, which requires the Zolando Docker image to be upgraded first before this can be merged...

**Comment by quater** [comment]
The previous PR got deleted. The new PR is https://github.com/helm/charts/pull/6855.

**Comment by davidkarlsen** [comment]
@quater That one got merged - please /close this one as #fixed

**Comment by linki** [comment]
@quater would you mind closing the issue?
