### ISSUE TITLE
[stable/prometheus] Use git-sync for alert rules

### ISSUE THREAD

**Issue by andrein** [helm/charts#6177]
**Is this a request for help?**: No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

Hello, I'm investigating ways to make it easier for our teams to set up their own alerts in prometheus. I know we can use extraConfigMapMounts, but I would like a little more flexibility. 

I've been thinking of configuring [git-sync](https://github.com/kubernetes/git-sync) as a sidecar container and store the alerting rules in a git repo. Is this a good approach? Would this feature be accepted upstream?

**Comment by davidkarlsen** [comment]
Another (could complement each other) approach could be the sidecar concept and configmaps with given annotations, like for dashboards and datasources in grafana: https://github.com/kubernetes/charts/tree/master/stable/grafana

**Comment by andrein** [comment]
I like the way grafana does it, and also found [git2kube](https://github.com/WanderaOrg/git2kube).  

Judging by the [example](https://github.com/WanderaOrg/git2kube/blob/master/example/watcher.yaml) this tool was written for this exact purpose. I'll try to integrate the k8s-sidecar container with the prometheus chart in the following days.

**Comment by davidkarlsen** [comment]
The sidecar is a better way because then different teams can publish their rules (with for instance helm for their app) but get it in centrally, rather than having to rely on ONE git repo which can have an organizational burden and is disconnected from the app

**Comment by andrein** [comment]
I tried to implement the sidecar concept from the grafana chart, but I've hit a few issues:
* Can't trigger a prometheus reload through the configmap-reload container because there's no [..data](https://github.com/jimmidyson/configmap-reload/blob/master/configmap-reload.go#L48) directory because I'm not mounting the configmap directly.
* Rules aren't always loaded at startup, I suspect it's because both the prometheus-server and sidecar containers start up at the same time.

The code is in https://github.com/codertux/charts/tree/prometheus-sidecar if anyone wants to take a look. I'm open to suggestions / ideas.

**Comment by davidkarlsen** [comment]
Is it possible to get a hook/callback triggered when new rules are written? Look at https://github.com/prometheus/prometheus/issues/1866 / https://www.robustperception.io/reloading-prometheus-configuration/

**Comment by codertux** [comment]
I was hoping that the configmap-reload container would use the HTTP api to reload prometheus, but it's not detecting the changes because the directory is not actually a configmap mount.
