### ISSUE TITLE
[stable/burrow] Hyperledger Burrow chart should be using Burrow icon.

### ISSUE THREAD

**Issue by alexvicegrab** [helm/charts#6203]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

N/A

**Which chart**:

Hyperledger Barrow

**What happened**:

While discussing using the Hyperledger Fabric chart icon with the trademark team at Hyperledger, it was suggested to me that the Barrow icon should be updated to the one specific to it, by `mbennett AT linuxfoundation DOT org`.

I mentioned I was not the author, but thought it might be helpful to ping you to liaise with her and update the icon to the correct one.

**What you expected to happen**:

The icon for the Burrow chart should be updated.

**How to reproduce it** (as minimally and precisely as possible):

N/A

**Anything else we need to know**:

No

**Comment by alexvicegrab** [comment]
@compleatang, @AdamDang

**Comment by alexvicegrab** [comment]
Ended up implementing in https://github.com/kubernetes/charts/pull/6207

**Comment by compleatang** [comment]
Thanks!
