### ISSUE TITLE
More explicit error handling for Telegraf

### ISSUE THREAD

**Issue by mgoodness** [helm/charts#622]
IMHO the telegraf chart should be more explicit in its `NOTES.txt` when reporting unset values. Specifically, I'd like to see the existing
```
{{- if empty .Values.single.config.outputs.influxdb.urls }}
{{- if empty .Values.daemonset.config.outputs.influxdb.urls }}

Need to set an InfluxDB url for either single or daemonset to deploy this instance:

.Values.daemonset.config.outputs.influxdb.urls
.Values.single.config.outputs.influxdb.urls

{{- end }}
{{- end }}
```
broken up into separate conditionals, so the user knows exactly which value needs to be set.

It should also be made clearer that while deployment succeeded, an error condition exists because pods are not running. We could also provide upgrade instructions for resolving the error. See the [datadog NOTES.txt](https://github.com/kubernetes/charts/blob/master/stable/datadog/templates/NOTES.txt) for an example.

Reporting due to test failure in #577 and to fulfill requirements of #558.

cc @jackzampolin

**Comment by jackzampolin** [comment]
I'm working on splitting the telegraf chart up into a couple of separate charts. Planning on 3 different charts. 

* The `daemonset` for host monitoring
* The `single` for polling pieces of infrastructure or APIs
* Ther `service` for managing database ingress.

I will incorporate this in the rewrite and CC you (@mgoodness) on the PRs if thats OK!

Sorry for the late response on this I've been on vacation! 🏄
