### ISSUE TITLE
[Stable/Datadog] `ServiceAccount` should be `ServiceAccountName`

### ISSUE THREAD

**Issue by timfallmk** [helm/charts#6254]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**:
Kubernetes: `1.10.1`
Helm: `2.9.1`
(Rancher): `2.0.2`

**Which chart**:
`stable/datadog`

**What happened**:
Set `datadog.serviceAccount` or `kube-state-metrics.rbac.serviceAccount` to a non-default value. Values not set or error displayed.

**What you expected to happen**:
Values are overridden and persist through to deployment

**How to reproduce it** (as minimally and precisely as possible):
1. Override values
2. Deploy chart

**Anything else we need to know**:
It looks like the README documentation is out of date. Both `datadog` and the subchart `kube-state-metrics` use the `serviceAccountName` variable to specify a non-default service account to use. The documentation for both says `serviceAccount`.

**Comment by timfallmk** [comment]
Still an issue

**Comment by davidkarlsen** [comment]
@timfallmk Care to do a PR?
