### ISSUE TITLE
Please upgrade traefik to 1.6.4 for ACME fixes

### ISSUE THREAD

**Issue by robbyt** [helm/charts#6293]
**Is this a request for help?**:
no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:

**Which chart**:
Traefik

**What happened**:
Traefik 1.6.2 has a bug with ACME headers to the v2 endpoint, which was fixed in v1.6.4.

**What you expected to happen**:
ACME to get a cert.

**How to reproduce it** (as minimally and precisely as possible):
Deploy the traefik chart, use the staging backend, and you'll receive the error:
`time="2018-06-25T02:46:41Z" level=error msg="Unable to obtain ACME certificate for domains \"foo.com\" detected thanks to rule \"Host:foo.com\" : cannot obtain certificates: acme: Error 400 - urn:ietf:params:acme:error:malformed - KeyID header contained an invalid account URL: \"https://acme-v02.api.letsencrypt.org/acme/acct/12341234\""`

Here's the helm cmd I'm using:
```
helm install stable/traefik \
    --name <LB NAME> \
     --namespace kube-system \
    --set \
loadBalancerIP=<YOUR IP>,\
rbac.enabled=true,\
ssl.enabled=true,\
acme.enabled=true,\
acme.email=root@houselogic.com,\
acme.staging=true,\
acme.challengeType=http-01,\
acme.persistence.storageClass=standard
```

**Anything else we need to know**:
https://community.letsencrypt.org/t/acme-v2-strict-jws-kid-header-processing/63321

**Comment by maver1ck** [comment]
You don't need to update chart for that.
Change only imageTag in configuration to 1.6.4.

**Comment by kachkaev** [comment]
Default image tag in the latest chart version is 1.6.5 now (see [values.yaml](https://github.com/helm/charts/blob/4689b66d9092856ae3f826b144a328bcf21723da/stable/traefik/values.yaml)). @maver1ck is right – you can pick any traefik image tag you want, so there is no need to wait for chart updates (although life is abit easier when the chart includes the latest traefik by default). All you need to do is `--set imageTag=1.x.x`.

@robbyt will you be happy to close this issue?
