### ISSUE TITLE
POD is stuck initializing for ever

### ISSUE THREAD

**Issue by vjroxvijay1** [helm/charts#6309]
**Is this a request for help?**:
YES
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

**Which chart**:
mongodb-replicaset

**What happened**:

**What you expected to happen**:
helm install --name test  stable/mongodb-replicaset --set persistentVolume.storageClass=nfs.

I run the above command and I verify that PVC is bound to the replica-0.
NAME                                STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
datadir-test-mongodb-replicaset-0   Bound     pvc-8417b31c-78b1-11e8-b6ef-005056b2c7b4   10Gi       RWO            nfs            40m

But the POD is always stuck in intialiazing and it never starts.
Error from server (BadRequest): container "mongodb-replicaset" in pod "test-mongodb-replicaset-0" is waiting to start: PodInitializing.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by sonaikar** [comment]
I am facing the same issue. Is there any solution to this problem?

Unable to mount volumes for pod "mongo-dev-1-mongodb-replicaset-0_mongo-dev(xxx)": timeout expired waiting for volumes to attach/mount for pod "mongo-dev"/"mongo-dev-1-mongodb-replicaset-0". list of unattached/unmounted volumes=[datadir config init keydir workdir configdir default-token-q8gds]

**Comment by Jianyi-Ren** [comment]
same issue. no log was provided except for the 'is waiting to start: PodInitializing' message

**Comment by Jianyi-Ren** [comment]
try `kubectl logs {{pod_name}} -c init-config` to check the message

**Comment by Aisuko** [comment]
Is there any solution to fix this?

**Comment by arunkumarrspl** [comment]
> try `kubectl logs {{pod_name}} -c init-config` to check the message

I got this error: ```Error from server (BadRequest): container init-config is not valid for pod

**Comment by hanusiakl** [comment]
@arunkumarrspl To be sure that your pod has '**init-config"** inside "**Init Continers**" section, just run `kubectl describe pod "your pod name"` and read first child from **Init Conteiners** section. In my case it was copy-default-config. So instead of  `kubectl logs {{pod_name}} -c init-config` I run  `kubectl logs {{pod_name}} -c copy-default-config`
