### ISSUE TITLE
[incubator/elasticsearch] Update to StatefulSet

### ISSUE THREAD

**Issue by mgoodness** [helm/charts#632]
n/t

**Comment by vise890** [comment]
Is this up for grabs?

**Comment by mgoodness** [comment]
@vise890 It's yours for the taking! Want me to assign you?

**Comment by vise890** [comment]
sure, so we're happy upping the requirement in the `README` to k8s 1.5?

**Comment by mgoodness** [comment]
Looks like I can only assign members of the Kubernetes org. Oh well, you've claimed it.

I have no problem updating the K8s version requirement to 1.5.

**Comment by prydonius** [comment]
We can bump the requirement, yeah. We want to support current stable release, and the previous release, but the changes from 1.4 -> 1.5 have made that a bit difficult.

**Comment by mattbates** [comment]
I have a PR pretty much ready to share and I was just alerted to this issue. Good work @vise890 on getting this started - let's collaborate.

In my update, I used the new Helm 2.2 `Capabilities` to determine API version and hence whether to use `PetSet` or `StatefulSet`, addressing @prydonius comment about wishing to support current stable (1.5.x) and the previous release (1.4.x).

**Comment by vise890** [comment]
Oh, right. That seems like a much better solution than the one I have in #641 . 
Does it deploy fine for you? I cannot get the elasticsearch readiness probe to pass (in the `StatefulSet`) ...

**Comment by mattbates** [comment]
@vise890 We also found the same with the probes and had to increase `initialDelaySeconds` much higher. We've readying the PR and should be in a position to share this coming week. /cc @munnerz

**Comment by kujenga** [comment]
@mattbates I'm interested getting the elasticsearch chart updated as well. What's the status of your PR? I'd be more than happy to assist if I can be helpful in any way!

**Comment by ReSearchITEng** [comment]
@mattbates : Can you share your work, even if it's unfinished?

**Comment by icereval** [comment]
FYI, this should be g2g w/ https://github.com/kubernetes/charts/pull/1794
