### ISSUE TITLE
[stable/sentry] Support specifying resources for jobs

### ISSUE THREAD

**Issue by ananace** [helm/charts#6321]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm: v2.9.1
Kubernetes: v1.10.1

**Which chart**:
stable/sentry

**What happened**:
When installing stable/sentry on a cluster with the LimitRanger admission controller, the database seed and user creation jobs both failed to launch due to missing `limit.cpu` and `limit.memory` values.

There are no methods to provide said limits through the provided values in the chart.

**What you expected to happen**:
The available values should contain settings to let you specify resource requirements / limits for the db-init and user-create jobs.

**How to reproduce it** (as minimally and precisely as possible):
```
helm install stable/sentry --set <no parameter for job resources>
```

**Anything else we need to know**:
While LimitRange objects can provide some defaults for the resources, they are *not* a solution to the issue, especially since the db-init job seems to require quite a chunk of RAM - it would OOM until I gave it 2GB of memory.

**Comment by insertjokehere** [comment]
This PR is important to me. I run a cluster that has a mix of amd64 and arm nodes, and sometimes the jobs will get deployed to arm nodes which cannot run the container. This causes helm to declare that the deploy has failed

**Comment by ananace** [comment]
This is just waiting for the PR #7249 at the moment.

**Comment by ananace** [comment]
Still waiting on the PR to be reviewed / accepted.

**Comment by ananace** [comment]
*Still* waiting on review responses the PR.
