### ISSUE TITLE
[stable/mongdo] Standalone deployment does not respect existingSecret value

### ISSUE THREAD

**Issue by grantga** [helm/charts#6340]
**Is this a request for help?**: No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.9.1

**Which chart**:
stable/mongodb

**What happened**:
The standalone deployment does not respect the `existingSecret` value if replicaSet is not enabled

**What you expected to happen**:
The existing secret should be used as it is when `replicaSet.enabled=true`

**How to reproduce it** (as minimally and precisely as possible):
Deploy stable/mongodb with an existing secret and leave `replicaSet.enabled=false`

**Anything else we need to know**:

**Comment by grantga** [comment]
This is still an issue and should be fixed I believe.

**Comment by dehypnosis** [comment]
Same to postgres, i wasted a day of my life :(
I couldn't even think about this case.

**Comment by grantga** [comment]
This is fixed by #7839
