### ISSUE TITLE
[stable/keycloak] Bad example value for extraEnv in values.yaml

### ISSUE THREAD

**Issue by groundnuty** [helm/charts#6346]
The example in values is wrong:
- it cannot be a list as an empty value suggests
- and example commented envs are also wrong 

https://github.com/kubernetes/charts/blob/22ba1746211dca83ea0de67101eb73ac352ff64e/stable/keycloak/values.yaml#L47-L50

The template function that processes it accepts strings not maps:
https://github.com/kubernetes/charts/blob/master/stable/keycloak/templates/statefulset.yaml#L68

I managed to get it working with by specifying in `values.yaml`:
```
    extraEnv: |-
        - name: HOSTNAME
          value: keycloak
```

I belive you guys @unguiculus @ryandawsonuk are maintaining this.

**Comment by ryandawsonuk** [comment]
I think https://github.com/kubernetes/charts/pull/6350 addresses this
