### ISSUE TITLE
Postgres chart appears to have compatibility issues with Postgres 10

### ISSUE THREAD

**Issue by ghost** [helm/charts#6353]
**Is this a request for help?**:
Nope

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Helm
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Kubernetes
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/postgresql

**What happened**:
I was testing failover by terminating Postgres pods and when inspecting the logs I saw a few failures.

Initially, it stated `database INSERT_POSTGRES_USER_HERE not found`, which is probably due to me making the default created database not be the same as the user's name. I inserted a DB for the user to silence this issue.

Next, it started complaining about being unable to call `pg_last_xlog_receive_location`, which has apparently changed / been removed in Postgres 10.

**What you expected to happen**:
No errors to happen.

**How to reproduce it** (as minimally and precisely as possible):
I used the following helm command to install the chart:

```bash
helm install --name postgres stable/postgresql \
  --namespace fooapp \
  --set image=mdillon/postgis \
  --set imageTag=10 \
  --set postgresUser=foo \
  --set postgresPassword=foofoo \
  --set postgresDatabase=foodb \
  --set persistence.size=10Gi \
  --set resources.requests.memory=256Mi \
  --set resources.requests.cpu=200m \
  --set resources.limits.memory=1024Mi \
  --set resources.limits.cpu=1000m \
  --set metrics.enabled=true \
  --set metrics.resources.requests.memory=50Mi \
  --set metrics.resources.requests.cpu=30m \
  --set metrics.resources.limits.memory=128Mi \
  --set metrics.resources.limits.cpu=50m
```

**Anything else we need to know**:
I'm using a postgis-enabled docker image, rather than any library based one as I need the PostGIS extensions to be present. Not sure if this contributes to the issue, but it *does* inherit from the library/postgres Dockerfile so it shouldn't be much of an issue.

**Comment by giorgiosironi** [comment]
May be related to https://github.com/helm/charts/issues/8735 where the default `postgres` image doesn't work, hence a derived image also wouldn't work.

**Comment by naxaamulya** [comment]
@lyptt how do you solve this??
