### ISSUE TITLE
Wondering why the percona mongodb exporter was reverted. 

### ISSUE THREAD

**Issue by kwill4026** [helm/charts#6357]
**Is this a request for help?**: Yes in regards to a revert of commit 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): None

**Version of Helm and Kubernetes**: 1.9

**Which chart**: mongodb replicaset

**What happened**: I wanted to know why the Percona MongoDB Exporter was added to the chart then reverted. I was interested in testing it with the mongodb replica set but was unsure since I see it was reverted. Any issue we should know about?

**What you expected to happen**: To have a mongodb replicaset helm chart with percona mongodb exporter for metrics, etc. 

**How to reproduce it** (as minimally and precisely as possible): n/a

**Anything else we need to know**: n/a

**Comment by kwill4026** [comment]
any update on this?

**Comment by unguiculus** [comment]
There was an issue with the initial PR. The exporter is back now.
