### ISSUE TITLE
[stable/jenkins] Question on user access after install

### ISSUE THREAD

**Issue by hooligan495** [helm/charts#6359]
This issue is more a Request for Help/Guidance:

I'm using the jenkins chart and I'd like it to start up with the the Security set to using the Jenkins user database.  Can the admin user that's created as part of the current database be added as part of the chart? (I'm happy to try and make it so myself and submit a PR.. .but before I spend too much time, it would be nice to know if it's just not possible first (if it isn't ))

Thanks

**Comment by Nodraak** [comment]
Hi ! I don't really understand your question, could your rephrase it?

**Comment by hooligan495** [comment]
Sure! 

So when I use this chart, the config file specifies the LegacySecurityRealm and it looks like a User (admin) is created in the container and passed through to jenkins.  I would like to have the chart leave us with: HudsonPrivateSecurityRealm and a user created somehow in the jenkins user database.  I'm not sure if that is possible or not

Is this clearer?  I'm not a jenkins expert so I'm not sure I'm asking the questions in the right way
