### ISSUE TITLE
stable/rabbitmq-ha 

### ISSUE THREAD

**Issue by u2bo** [helm/charts#6388]
helem version
'''
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

'''

kuberntes version
'''
1.10

'''

rabbitmq delpoy error!
log:
sed: can't create temp file '/etc/rabbitmq/rabbitmq.confXXXXXX': Read-only file system

**Comment by ygqygq2** [comment]
@swqmaven How did you fix it?
