### ISSUE TITLE
[incubator/jaeger] Hotrod example does not work

### ISSUE THREAD

**Issue by wonderb0lt** [helm/charts#6421]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 
Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

Helm: 
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```` 

**Which chart**:
incubator/jaeger

**What happened**:

I installed the chart with hotrod enabled using `hotrod.enabled=true`. I opened the Hotrod UI and clicked 10-15 times on the various buttons, and then browsed to the Jaeger UI. There were no traces available. The Hotrod log contains a bunch of error messages:

```
2018-07-02T13:40:12.985Z	ERROR	log/logger.go:42	error when flushing the buffer: write udp 127.0.0.1:42074->127.0.0.1:6831: write: connection refused	{"service": "frontend"}
github.com/jaegertracing/jaeger/examples/hotrod/pkg/log.logger.Error
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/pkg/log/logger.go:42
github.com/jaegertracing/jaeger/examples/hotrod/pkg/tracing.jaegerLoggerAdapter.Error
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/pkg/tracing/init.go:61
github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:257
github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:267
```

**What you expected to happen**:
When using the "HotROD" sample application, generated traces end up in the jaeger-query UI interface

**How to reproduce it** (as minimally and precisely as possible):
1. `helm install incubator/jaeger --name past-jaeger --namespace past-jaeger --set "hotrod.enabled=true"`
2. Connect to the cluster somehow (using either telepresence or port-forwarding)
3. Open http://past-jaeger-hotrod/ and click a bunch of buttons a bunch of times
4. Open http://past-jaeger-query/search and try to find some traces

**Anything else we need to know**:

I'm very sorry if I'm misconfiguring Hotrod or misunderstanding something about Jaeger. Do I still need to enable something for traces to appear?

**Comment by J-Ha** [comment]
ill ran into the same problem and found a solution.
the hotrod container needs to be startet with this commands
```
        - command:
          - /all
          -  --jaeger-agent.host-port=jaeger-agent:6831```

there could and should be some "magic" with the helm chart be possbile.

**Comment by dvonthenen** [comment]
I can take a look at adding this... seems simple enough.

**Comment by dvonthenen** [comment]
Still trying to debug this... I found a couple of errors, but still having problems getting this to work.

**Comment by dvonthenen** [comment]
PR https://github.com/helm/charts/pull/6872 submitted
