### ISSUE TITLE
[stable/ark] support ark-config.yaml updates

### ISSUE THREAD

**Issue by magowant** [helm/charts#6438]
FEATURE REQUEST:

I may have got this wrong, but I don't see how the stable/ark chart supports updating the `ark-config.yaml` via a helm upgrade.

The ark config is applied by a post-install hook that runs  `kubectl create -f ark-config.yaml`. Therefore the config is only created for a helm install, and will never be run for a helm upgrade. 

Is it possible to make the hook run for `post-upgrade` as well as `post-install`, and modify the command to be `kubectl apply -f ark-config.yaml`?

**Comment by plumdog** [comment]
I think the full solution here might be to make use of the new `crd-install` helm hook, which will be part of 2.10, but is not released yet.

Then the hack to create custom the custom resource from the confimap can go away, and we can just use helm for everything. This will then handle resources being deleted too.
