### ISSUE TITLE
[stable/ark] optional backup schedule

### ISSUE THREAD

**Issue by magowant** [helm/charts#6448]
FEATURE REQUEST:

I would like to automatically create an ark backup schedule when installing the chart. The schedule would not be created by default, but there would a Helm property to enable the creation of the schedule and properties to define the various schedule parameters.

**Comment by plumdog** [comment]
See https://github.com/helm/charts/issues/6438#issuecomment-412560311 - will be much cleaner to implement once helm 2.10 is released.
