### ISSUE TITLE
Consul Chart Improvements

### ISSUE THREAD

**Issue by chrislovecnm** [helm/charts#65]
Since we are running a Petset should we include notes about deleting storage when we delete the Petset?

**Comment by lachie83** [comment]
I have confirmed that the default reclaim policy is Delete and that volumes are being cleaned up on AWS. This should also work for GCE and Cinder. http://kubernetes.io/docs/user-guide/persistent-volumes/#reclaiming.

I would be more than happy to update the README to call out that volume delete may not work if you're using something other than the above. Thoughts?

**Comment by chrislovecnm** [comment]
The PetSet docs have a create example with a timeout. Please update the readme in the chart

**Comment by lachie83** [comment]
Could you please point me at the example you are referring to as I would really like to make sure I address this issue correctly. I'd also be happy to review a PR with the stated changes if you're happy to work on it.

**Comment by chrislovecnm** [comment]
http://kubernetes.io/docs/user-guide/petset/#deleting-a-petset

Look for the section that has a grace ENV variable. Those commands allow for the full delete of a PetSet and storage. Current alpha limitation for PetSet.

**Comment by chrislovecnm** [comment]
Btw thanks for the help!!!!!

**Comment by lachie83** [comment]
Documented PV cleanup steps assuming that you've already removed the Helm release.
