### ISSUE TITLE
[stable/jenkins] Agent service does not support NodePort at deployment time

### ISSUE THREAD

**Issue by rbutcher** [helm/charts#6506]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Version of Helm and Kubernetes**:
Helm: 
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```
Kubernetes: 
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/jenkins

**What happened**:
When creating a new deployment using ```helm upgrade -i -f ./some-values stable/jenkins``` with ```Master.SlaveListenerServiceType=NodePort``` the service is created with the external port using a randomized value. Jenkins has no knowledge of what this value should be and will continue using its default ```SlaveListenerPort=50000```. This results in an agent external to the cluster being unable to connect without manually configuring the JNLP port to match the randomized service port.

**What you expected to happen**:
To be able to configure the ```nodePort``` on the service at install time.

**How to reproduce it** (as minimally and precisely as possible):
1. Install the stable/jenkins chart setting ```Master.SlaveListenerServiceType=NodePort```
2. Observe the creation of the agent service with the external port getting set to a random value.
3. Attempt to attach a external "Permanent Agent" to the newly create Jenkins instance.
4. Observe failure to connect due to dialing into the wrong port.

**Anything else we need to know**:
I have a proposed minimalist fix for this but I am waiting on my org to accept the CLA. Basically it's checking if the ```Master.SlaveListenerServiceType=NodePort``` and that ```Master.SlaveListenerPort``` is set and then setting the service's ```nodePort=Master.SlaveListenerPort```.

This is an on-prem installation and to my knowledge is the only way to get something like this to work. I have an ingress configured on the master but I don't believe it's possible to configure multiple back-ends on the ingress without different subpaths.

**Comment by garygithub1** [comment]
Please provide a temp detail solution until the issue resolved  i.e. how to "manually configuring the JNLP port to match the randomized service port"
