### ISSUE TITLE
prometheus chart can not be installed

### ISSUE THREAD

**Issue by deruizhu** [helm/charts#6530]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

**Version of Helm and Kubernetes**:

Helm version:
Client: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}

minikube version
minikube version: v0.28.0

**Which chart**:
prometheus

**What happened**:
can not be installed

**What you expected to happen**:
be installed successfully

**How to reproduce it** (as minimally and precisely as possible):
just type 'helm install stable/prometheus' inside the folder charts

**Anything else we need to know**:

**Comment by alexvicegrab** [comment]
Could you provide some more detail, such as the exact error message?

**Comment by xtal0** [comment]
I am seeing the same thing with the error "Error: no available release name found".

**Comment by deruizhu** [comment]
hi, thanks. when I downgrade my helm version, the problem is fiexed.

  On July 11, 2018 at 6:35 PM Crystal Barnes <notifications@github.com> wrote:
 
 
 I am seeing the same thing with the error "Error: no available release name found".

**Comment by davidkarlsen** [comment]
@deruizhu You can only close it yourself. Please do so.
