### ISSUE TITLE
openfaas operator

### ISSUE THREAD

**Issue by bhack** [helm/charts#6563]
What about adding  [openfaas-operator](https://github.com/openfaas/faas-netes/tree/master/chart/openfaas#openfaas-operator--crd-controller)?

/cc @alexellis

**Comment by alexellis** [comment]
Hi thanks for the ping.

We have a chart repo on GitHub pages for OpenFaaS, perhaps this repo could sync from our upstream? 

https://github.com/openfaas/faas-netes/tree/master/chart/openfaas

Cc @stefanprodan

**Comment by bhack** [comment]
@alexellis Yes could be ideal.

**Comment by bhack** [comment]
Any news?

**Comment by alexellis** [comment]
What would you like to ask me?

**Comment by bhack** [comment]
Can you PR your chart?
