### ISSUE TITLE
Prometheus Helm rule_files does not load alert into prometheus server

### ISSUE THREAD

**Issue by ohmanandam** [helm/charts#6564]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG Report

**Version of Helm and Kubernetes**:
Helm: 2.9.1
Kubernetes: v1.10

**Which chart**:
stable/Prometheus

**What happened**:
I am able to bring up Prometheus, Alertmanager, Node exporter, Push Gateway and Kube State matrix containers via this chart and able to scrape my prometheus endpoints.
However my alert configuration in values.yaml via rule_files are not loaded
The same rule_files configuration work on a standalone prometheus server and able to generate alerts.

rule_files:
  - /etc/config/rule1.yaml

**What you expected to happen**:
I expect the prometheus server started via stable/prometheus helm chart to load the alert definition and then hook this alert with alert manager

**How to reproduce it** (as minimally and precisely as possible):
basic configuration of stable/prometheus helm chart

**Anything else we need to know**:
I am hoping this is a simple configuration issue. I do not see any errors in the container log

**Comment by sandeepmendiratta** [comment]
Can you try rules like that?
``` - name: example.rules
  rules:
  - expr: histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket[1m]))
       BY (le, job)) 
     record: job:request_duration_seconds:histogram_quantile99
```

**Comment by ohmanandam** [comment]
I had a similar alert  rule config defined in my rule_files
rule_files:
- /home/ohm/work/rules1.rules

The Alert rule file contains the latest yaml spec from Prometheus as below

groups:
- name: example
  rules:
  - alert: HighErrorRate
    expr: Success_Count > 1
    for: 10s
    labels:
      severity: critical
    annotations:
      summary: High request latency

I tried your recommended recording rule as well, but that rule also does not get picked by helm install.

The Helm chart brings up all the prometheus server, alertmanager, node exporter, push gateway, kube-state metrics instanes fine, and prometheus serves dynamically  scrapes my end points as well, however the alert and rule configuration are not picked by prometheus server from values.yaml configuration of **rule_files**. Please note that alertmanager comes up fine with its config.

NAME                                                                 READY     STATUS    RESTARTS   AGE
pod/eloping-buffoon-prometheus-alertmanager-68cc78f756-x2n79         2/2       Running   0          46s
pod/eloping-buffoon-prometheus-kube-state-metrics-64c968795f-h5dms   1/1       Running   0          46s
pod/eloping-buffoon-prometheus-node-exporter-b4xkh                   1/1       Running   0          46s
pod/eloping-buffoon-prometheus-pushgateway-5455f65ffb-jr89j          1/1       Running   0          46s
pod/eloping-buffoon-prometheus-server-7d5fc864f7-b8qrz               2/2       Running  
![screenshot from 2018-07-12 22-38-09](https://user-images.githubusercontent.com/36752092/42674385-563a7600-8624-11e8-903e-01dde1950de8.png)
 0

**Comment by ohmanandam** [comment]
I have also tried adding this alert rule in serverFiles: alerts section, and this also does not get picked by prometheus server when the helm chart is installed.

serverFiles:
  alerts:
    groups:
    - name: example
      rules:
      - alert: HighErrorRate
        expr: Success_Count > 1
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: High request latency

**Comment by ohmanandam** [comment]
I am unable to make the current helm chart work with any rules/alerts configured either via serverFiles or rule_files. I also could not find enough documents that demonstrate a working end to end configuration of  stable/prometheus charts, it seems that this version is not supported enough.
