### ISSUE TITLE
[stable/wordpress] Image uploads over 1MB fail when using NFS Persistent Volumes

### ISSUE THREAD

**Issue by chrisatomix** [helm/charts#6566]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT?**
Yes

**Version of Helm and Kubernetes**:
Helm 2.9.1
Kubernetes v1.10.4-gke.0 (Google Kubernetes Engine)

**Which chart**:
stable/wordpress (2.1.1)

**What happened**:
After deploying the WordPress Helm Chart on a Kubernetes Cluster with a single Replica and a standard PersistentVolume, I was able to upload as many files/images as I needed to without any issues.

When I increased the number of Replicas to 3 and swapped to NFS (as documented), everything seemed to work except images over 1MB would not upload successfully.
* :heavy_check_mark: Uploading a 300KB PNG worked fine
* :heavy_check_mark: Uploading a 900KB JPG worked fine
* :heavy_check_mark: Uploading a 3MB ZIP file worked fine
* :heavy_check_mark: Uploading a 1.6MB PDF worked fine
* :x: Uploading a 1.1MB JPG failed
* :x: Uploading a 2MB PNG failed

When a large image fails to upload, the thumbnail is blank and the file itself is 0 bytes.
The reported max upload size is 40MB.
Disabling all thumbnail resizing and commenting out any thumbnail sizes in the theme doesn't resolve this, but I assume there's something in the WordPress core which handles image mimetypes differently even if all thumbnailing has been disabled.

![image](https://user-images.githubusercontent.com/1768449/42495942-aedaaf0e-8463-11e8-9f88-ad05d3100c15.png)
(shuttle.jpg is a 1.7MB JPG image which failed, this also shows a 3MB zip file and a 300KB PNG which both worked)

Editing the failed media file returns an "Image data does not exist. Please re-upload the image" error.

There are no errors during/after upload, everything seems to be successful.

I've tried 15-20 different images in different formats and of different sizes, only those over around 1MB fail.

Swapping back from NFS to a standard PVC fixes everything, this seems to be an issue specifically with the NFS PVC.

I don't see anything in the Bitnami image or this Chart which would restrict image uploads to 1MB.

There are no plugins active on this installation, and the same issue occurs with both the TwentySeventeen and TwentyFifteen themes.

The same issue occurs even when the replicaCount is set to "1".

**What you expected to happen**:
Images larger than 1MB should upload and be resized/thumbnailed successfully.

**How to reproduce it** (as minimally and precisely as possible):
Follow the instructions in the README to install the NFS Provisioner:
```
helm install stable/nfs-server-provisioner --set persistence.enabled=true,persistence.size=10Gi
```

Download the `values-production.yaml` file (you may need to change the serviceType from ClusterIP to LoadBalancer so you can access externally).

Deploy via Helm:
```
helm upgrade --install \
-f values-production.yaml \
--set persistence.storageClass=nfs \
--set mariadb.enabled=false \
--set wordpressEmail="test@fake.com" \
--set wordpressPassword="secret-password" \
--set externalDatabase.host="mysql-server" \
--set externalDatabase.user="mysqluser" \
--set externalDatabase.password="mysql-password" \
--set externalDatabase.database="demo-db" \
--set externalDatabase.port=3306 \
demo-wordpress stable/wordpress
```

Login to the WordPress admin and upload files/images to test.
Files of any size appear to upload successfully, except for images over 1MB which will fail.

**Anything else we need to know**:
Related to functionality introduced in https://github.com/kubernetes/charts/pull/5286

**Comment by xblaster** [comment]
Same issue for me on my side
