### ISSUE TITLE
spinnaker-create-bucket-sfb8s Startup failure

### ISSUE THREAD

**Issue by guleng** [helm/charts#6570]
###Issue Summary:
helm install spinnaker after spinnaker-create-bucket-sfb8s Startup failure

###Cloud Provider(s):
local kubernetes cluster

###Environment:
kubernets 1.9.1
helm 2.8.1

###Feature Area:
China、

###Description:
kubectl get pod -n spinnaker -o wide
NAME READY STATUS RESTARTS
spinnaker-create-bucket-sfb8s 0/1 CrashLoopBackOff 10
kubectl logs -n spinnaker spinnaker-create-bucket-sfb8s
mc: Configuration written to root/.mc/config.json Please update your access credentials.
mc: Successfully created root/.mc/share
mc: Initialized share uploads root/.mc/share/uploads.jsonfile.
mc: Initialized share downloads root/.mc/share/downloads.jsonfile.
Added pinnaker-miniosuccessfully.
mc: Unable to make bucket pinnaker-minio/spinnaker Your previous request to create the named bucket succeeded and you already own it.

###Steps to Reproduce:
It is normal for me to check minio, and the status and log are all right.

###Additional Details:
After each installation of spinnaker, both gate and front50 are restarted, and then normal.

**Comment by vasya10** [comment]
I am running into same issue, but my versions are slightly different. My setup is on AWS EKS (K8S 1.10, Helm 2.9.1). After I ran helm install -n myspinnaker stable/spinnaker, every thing started except create-bucket, front50 and gate. They keep restarting and end up in CrashLoopBackOff. Any pointers?
