### ISSUE TITLE
[stable/datadog] error while creating mount source path '/opt/datadog-agent/run': mkdir /opt/datadog-agent: read-only file system

### ISSUE THREAD

**Issue by guizmaii** [helm/charts#6572]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

Helm v2.9.1
k8s 1.9.7-gke.3
 
**Which chart**:

stable/datadog

**What happened**:

Since this commit: https://github.com/kubernetes/charts/commit/ebfd2957a94d4c7f70ef69deb29c43a2813f9794#diff-e329e0fe977392337a5d8ded00798a9a

there're 2 new config keys:
  - `datadog.logsEnabled`
  - `datadog.logsConfigContainerCollectAll`

allowing us to activate the logs collection.

Setting `datadog.logsEnabled` to true will mount a new volume as we can see here: https://github.com/kubernetes/charts/commit/ebfd2957a94d4c7f70ef69deb29c43a2813f9794#diff-c5ed47d16bb168ac09be3d6cdf6b4abaR177

and then logs will be written in this volume.

But when the DeamonSet is starting its nodes, the nodes fail to boot with the following error:

```
Error: failed to start container "datadog": Error response from daemon: error while creating mount source path '/opt/datadog-agent/run': mkdir /opt/datadog-agent: read-only file system
Back-off restarting failed container
```

**What you expected to happen**:

The nodes boot and logs begin to arrive in the Datadog dashboard.

**How to reproduce it** (as minimally and precisely as possible):

  - Install Helm
  - Init Helm:
```
$ helm init || echo 0
$ helm init --upgrade || echo 0
$ helm repo update
```
  - Create a local copy of this file: https://github.com/kubernetes/charts/blob/master/stable/datadog/values.yaml
  - In this file, uncomment the following lines:
    - https://github.com/kubernetes/charts/blob/master/stable/datadog/values.yaml#L117
    - https://github.com/kubernetes/charts/blob/master/stable/datadog/values.yaml#L118 
  - in this file, set an api key here: https://github.com/kubernetes/charts/blob/master/stable/datadog/values.yaml#L83
  - finally, install the agent thanks to this command line: 
```
$ helm upgrade -i -f path/to/your/values.yaml dd-agent stable/datadog
```

**Anything else we need to know**:

Do we really need this volume ?

**Comment by xvello** [comment]
Hello @guizmaii,

This volume is currently needed for persisting the tailing state of log files and container logs. Without it, an agent restart would throw duplicate data into the log stream. We'd welcome a PR to make the path configurable it that can help.


Regards

**Comment by guizmaii** [comment]
> I think we should move the default to /var/lib/datadog-agent/logs, as /var/lib is writable on all mainstream container host OSes. WDYT?

Good idea.

I can try to make a PR for that. Or, maybe, you prefer to do it yourself ?

**Comment by guizmaii** [comment]
Here's the PR: https://github.com/kubernetes/charts/pull/6695 😉

**Comment by so0k** [comment]
Wouldn't it make more sense to use `/var/log` on the host instead of `/var/bin/` for the log cursors?

see https://github.com/honeycombio/honeycomb-kubernetes-agent/issues/29#issuecomment-438553965
