### ISSUE TITLE
Neo4j replica deployment should include NEO4J_ACCEPT_LICENSE_AGREEMENT variable 

### ISSUE THREAD

**Issue by tomahawk28** [helm/charts#6577]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
Kubernetes: 
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
`stable/neo4j`

**What happened**:
if you scale `neo-helm-neo4j-replica` after installing stable/neo4j chart(initially size=0), all replica pods are crashed since NEO4J_ACCEPT_LICENSE_AGREEMENT are not set. 
```
shell> helm install stable/neo4j --debug --wait --name neo-helm --wait --set authEnabled=false --set acceptLicenseAgreement=yes
...

shell> kubectl scale deployment neo-helm-neo4j-replica  --replicas=3
deployment "neo-helm-neo4j-replica" scaled

shell> kubectl get po
NAME                                      READY     STATUS    RESTARTS   AGE
neo-helm-neo4j-core-0                     1/1       Running   0          1m
neo-helm-neo4j-core-1                     1/1       Running   0          1m
neo-helm-neo4j-core-2                     1/1       Running   0          1m
neo-helm-neo4j-replica-5856bf55dc-4kvdh   0/1       Error     1          10s
neo-helm-neo4j-replica-5856bf55dc-7ldxx   0/1       Error     1          10s
neo-helm-neo4j-replica-5856bf55dc-splm8   0/1       Error     1          10s
source-ip-app-8687dbf9f-p6wz6             1/1       Running   1          6d

shell> kubectl logs neo-helm-neo4j-replica-5856bf55dc-4kvdh

In order to use Neo4j Enterprise Edition you must accept the license agreement.

(c) Network Engine for Objects in Lund AB.  2017.  All Rights Reserved.
Use of this Software without a proper commercial license with Neo4j,
Inc. or its affiliates is prohibited.

Email inquiries can be directed to: licensing@neo4j.com

More information is also available at: https://neo4j.com/licensing/


To accept the license agreement set the environment variable
NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

To do this you can use the following docker argument:

        --env=NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

```
**What you expected to happen**:
env variable named `NEO4J_ACCEPT_LICENSE_AGREEMENT` should be existed inside replica pods as well. 
To fix it *manually*, you have to patch the deployment as below
```
shell> kubectl patch deploy neo-helm-neo4j-replica -p '{"spec":{"template":{"spec":{"containers":[{"name":"neo4j", "env": [{"name": "NEO4J_ACCEPT_LICENSE_AGREEMENT", "value": "yes"}]}]}}}}'
deployment "neo-helm-neo4j-replica" patched
```
and check, 
```
shell> kubectl get po neo-helm-neo4j-replica-56dfddbdd6-h9z9j -o yaml | grep -A 3 ACCEPT
    - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
      value: "yes"
```

After that, all replica pods are running w/o problem.
```
shell> kubectl get po -l app=neo4j
NAME                                      READY     STATUS    RESTARTS   AGE
neo-helm-neo4j-core-0                     1/1       Running   0          38m
neo-helm-neo4j-core-1                     1/1       Running   0          38m
neo-helm-neo4j-core-2                     1/1       Running   0          38m
neo-helm-neo4j-replica-56dfddbdd6-h9z9j   1/1       Running   0          14m
neo-helm-neo4j-replica-56dfddbdd6-qvvbg   1/1       Running   0          14m
neo-helm-neo4j-replica-56dfddbdd6-xlkjr   1/1       Running   0          14m
```

**How to reproduce it** (as minimally and precisely as possible):

I described in `What happened` already :)

**Comment by mneedham** [comment]
Hey,

It's deliberately like that so that users would explicitly set that flag indicating that they accept the license. There was a long discussion thread about that variable somewhere on GitHub but I can't seem to find it at the moment.

@moxious can you remember the thread?

**Comment by tomahawk28** [comment]
Do you mean, even if user set an agreement variable during helm install,
you should do that again when you scale up your replicated neo4j?

**Comment by moxious** [comment]
Hi guys -- yes a while back I tried to introduce a change into the public helm chart to auto-accept the license.  That got fairly substantial pushback, and I ended up closing the PR for this and other reasons.   That full thread can be found here: https://github.com/kubernetes/charts/pull/4460

In general, the thinking is that because the underlying docker container requires explicit "yes" on the license, that usages of it shouldn't hardware the yes.  Honestly this is something I think neo4j could reconsider about its docker container though, as for example if you installed neo4j via dpkg or RPM, you wouldn't have to explicitly accept.  So it's either a peculiarity of docker, or a feature that you know you're accepting a license, depending on how you look at it.

I haven't dove into the specifics on this report though -- it should be that if the replica set has a certain configuration (including acceptance of license) that scaling the replica set should keep that configuration.

**Comment by tomahawk28** [comment]
Hi, @moxious 
For this problem, 
> I haven't dove into the specifics on this report though -- it should be that if the replica set has a certain configuration (including acceptance of license) that scaling the replica set should keep that configuration.

Could we simply put the same env variable in `stable/neo4j/templates/readreplicas-deployment.yaml`
```diff
diff --git a/stable/neo4j/templates/readreplicas-deployment.yaml b/stable/neo4j/templates/readreplicas-deployment.yaml
index 161013f7..49dd78f8 100644
--- a/stable/neo4j/templates/readreplicas-deployment.yaml
+++ b/stable/neo4j/templates/readreplicas-deployment.yaml
@@ -22,6 +22,8 @@ spec:
         image: "{{ .Values.image }}:{{ .Values.imageTag }}"
         imagePullPolicy: "{{ .Values.imagePullPolicy }}"
         env:
+          - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
+            value: "{{ .Values.acceptLicenseAgreement }}"
           - name: NEO4J_dbms_mode
             value: READ_REPLICA
           - name: NEO4J_dbms_security_auth__enabled
```
I double-checked it solves my problem.
