### ISSUE TITLE
Compute Resources for existing charts

### ISSUE THREAD

**Issue by chrislovecnm** [helm/charts#66]
I know I am beating this dead horse just a bit, but we need to go through the existing charts and get http://kubernetes.io/docs/user-guide/compute-resources/ laid out.  Probably should update any standards docs / guidelines that we have.

**Comment by viglesiasce** [comment]
No best practices doc but we have an issue open, can you migrate your suggestion there? #44

**Comment by chrislovecnm** [comment]
will do

**Comment by chrislovecnm** [comment]
Closed and migrated to #44
