### ISSUE TITLE
Deploying applications with Prometheus sidecars

### ISSUE THREAD

**Issue by andrewhowdencom** [helm/charts#663]
Hola All, 

When designing charts (more particularly the pod spec), how do you feel them being designed to include Prometheus sidecars where possible?

While supporting ${ALL_METRICS_SYSTEMS} is a huge ask and way beyond the scope of this project, prometheus is a little unique in that Kubernetes is already building in support for Prometheus formatted metrics. 

The resolution for this issue would just be to add a note saying "prometheus sidecards are fine" in the Contributor Guidelines document.

Cheers!

**Comment by mgoodness** [comment]
Good suggestion/question! My personal opinion is that we should accept any monitoring/logging sidecars provided they're individually toggleable. See the (PR-pending) nginx-ingress chart for an example.

**Comment by andrewhowdencom** [comment]
Mental sketching for my current chart development: 

- Allow sidecars, but make them disabled by default.
- Enable them based on some option in values.yml
- Presume "dumb" sidecars that just need to query the application over localhost. Reading state out  of the FS is arbitrarily complex. unsure how this will hold up, but intuitively seems reasonable -- lots of applications can output state over network, just perhaps not in a way ${MONITORING_TOOL} expects them to (thus the need for the sidecar)
- Allow changing of the monitoring container but default to Prometheus where possible / known. 
- Allow changing / disabling of monitoring container exposed port. 

Note: this doesn't solve the problem of reading logs in sidecars, unless the application is able to be configured to push logs through syslog over port (rather than /dev/whatever), such as fluentd/nginx. 

The notes above are just sketches as I don't have time allocated to this right now, but I wanted to write it up while it's fresh in my mind.  

NGINX PR https://github.com/kubernetes/charts/pull/399
