### ISSUE TITLE
[incubator/jaeger] No way to alter default remote sampler configuration

### ISSUE THREAD

**Issue by nickrobertssky** [helm/charts#6631]
**Is this a request for help?**: Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm 2.8.2
Kubernetes v1.10.3

**Which chart**:
incubator/jaeger

**What happened**:
The agent-sampling port on the jaeger-agent service returns the following default configuration: 
```
{"strategyType":0,"probabilisticSampling":{"samplingRate":0.001}}
```
I can't find a way to change this when installing Jaeger through Helm.

**What you expected to happen**:
Jaeger allows the sampler configuration to be controlled centrally using the option
```--sampling.strategies-file```
https://www.jaegertracing.io/docs/sampling/

I would expect the file to be included as a config map or similar when using the incubator/jaeger chart so that we can edit the contents of this file.

**How to reproduce it** (as minimally and precisely as possible):
```
helm install incubator/jaeger -n jaeger
```

**Anything else we need to know**:

**Comment by dvonthenen** [comment]
I can take a look at adding this... seems simple enough.

**Comment by dvonthenen** [comment]
PR https://github.com/helm/charts/pull/6926

@nickrobertssky if you can give me a hand testing this, I would appreciate it!
