### ISSUE TITLE
[stable/datadog] Direct support for DogStatsD unix socket collection

### ISSUE THREAD

**Issue by cknowles** [helm/charts#6645]
Ingestion of DogStatsD metrics via a Unix Domain Socket instead of UDP, holds [a few advantages](https://docs.datadoghq.com/developers/dogstatsd/unix_socket/).

It would be good to add direct support via a flag rather than having to figure out which options to override and if they are set correctly. It can be done today by adding the env vars, mount overrides plus `useHostPID ` just it'd be neater to have an option. It would also be more automated for users upgrading chart versions so they can easily stick with the latest recommendations.

A prime example of this is I only just saw the `useHostPID` has been added but it wasn't so easy to track down why we might need that. I since found [these docs](https://docs.datadoghq.com/developers/dogstatsd/unix_socket/#using-origin-detection-for-container-tagging). That seems to be a new recommendation but upgrading chart version doesn't fix that automatically, a user has to go though all the configuration options and datadog website each time to check if they are following the latest recommendations. It's super easy to miss things!

The flag would need to setup [the mounts](https://docs.datadoghq.com/developers/dogstatsd/unix_socket/#kubernetes-hostpath-volume), [origin detection](https://docs.datadoghq.com/developers/dogstatsd/unix_socket/#using-origin-detection-for-container-tagging) and the `hostPID` plus any future options required for unix socket collection to fully function.

**Comment by c-knowles** [comment]
@hkaj @xvello I might submit a PR for this, would like to know your thoughts first?

**Comment by benwilson512** [comment]
I realize this has been closed but a flag here would be very nice. For example, I'm still pretty unclear on how to set the `dogstatsd_socket` option within `datadog.yaml`.

**Comment by xvello** [comment]
@benwilson512  Adding it to the chart is in our backlog. In the meantime https://docs.datadoghq.com/developers/dogstatsd/unix_socket/ explains our recommended paths and mount configurations for using unix sockets for dogstatsd in kubernetes
