### ISSUE TITLE
Error: failed to download "incubator/fluentd-cloudwatch"

### ISSUE THREAD

**Issue by ghost** [helm/charts#6655]
please help to fix!
buntu@ip-10-0-x-x:~$ helm install --name fluentd-cloudwatch \
>   --set awsRegion=ap-south-1 \
>   --set awsRole=CloudwatchPodLogs \
>     incubator/fluentd-cloudwatch
Error: failed to download "incubator/fluentd-cloudwatch" **(hint: running `helm repo update` may help)**

**Comment by rajkumar49** [comment]
I can able to successfully update the helm repo and download the redis from the repo. but not able to download the **incubator/fluentd-cloudwatch**

**Comment by rajkumar49** [comment]
added the incubator repo to helm, fixed the issue.

**Comment by djsd123** [comment]
Glad you got it sorted.  Anyone viewing this in the future can find the instructions [here](https://github.com/kubernetes/charts#how-do-i-enable-the-incubator-repository)

Essentially, just run:
`helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/`
