### ISSUE TITLE
[stable/grafana] DataSource provising using config-map is buggy

### ISSUE THREAD

**Issue by eloo** [helm/charts#6673]
**Version of Helm and Kubernetes**:
Using minikube (but also reproducable in real k8s cluster)
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

**Which chart**:
Grafana 1.12.0

**What happened**:
When changing datasources for provisioning the changes are not applied in grafana

**What you expected to happen**:
When i change my datasources config map the changes should be applied in grafana

**How to reproduce it** (as minimally and precisely as possible):
* Deploy a grafana chart with configmaps for datasources. 
* Then check grafana -> datasource is configured
* Update datasources configmap
* Then check grafana -> datasource has not changed (This is normal because grafana seems to do provisioning of datasources only at startup
* Restart/kill grafana pod so it will come up again
* Check grafana -> datasource still not changes or even not there

**Anything else we need to know**:
I've figured out a workaround for this issue.
Exec into the grafana container and kill grafana (kill 1). Then only the grafana container will be recreated. And afterwards the datasource config map changes are applied.

So i guess there is an timing issue when the sidecar for datasources and grafana are starting in parallel. Maybe the sidecar needs to be enforced to start first and only when this sidecar is running grafana will start? 
Or can the sidecar trigger a restart of grafana when changes are found?

Thanks

**Comment by eloo** [comment]
Maybe it would be enough to not use a sidecar for datasources but use a configmapoverride like the prometheus chart has?

**Comment by johnharris85** [comment]
Necromancing this. The sidecar for datasources shouldn't be an init-container, it doesn't support the use case above, and is open to race conditions if the configmap doesn't exist. Ideally I guess it should be implemented as a permanent container / sidecar as the dashboards one is?
