### ISSUE TITLE
repo incubator/elastic-stack kibana not able to resolve to elastic-search 

### ISSUE THREAD

**Issue by ghost** [helm/charts#6674]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
 
**Which chart**:
incubator/elastic-stack

**What happened**:
from Kibana:
plugin:elasticsearch@6.0.0 | Unable to connect to Elasticsearch at http://http.default.svc.cluster.local:9200.
-- | --

**What you expected to happen**:
connected to elastic-search 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by rajkumar49** [comment]
I have even upgraded kubernetes to version 1.9.9 . but still same issue 
![image](https://user-images.githubusercontent.com/16345902/42824304-341c0f3e-89fd-11e8-8307-b634a06ca1c9.png)


$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:07:01Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by monotek** [comment]
Please check your config of the Elasticsearch url in Kibana.
If your using the Elasticsearch chart it will probably look like:
```
  env:
    ELASTICSEARCH_URL: http://elasticsearch-client:9200
```

**Comment by rajkumar49** [comment]
hi , @monotek , have a good day  and thanks for your response.  
if i change the Elastic-search URL in Kibana , i also need to change it in the logstash pod which also unable to access the elasticsearch URL (http://http.default.svc.cluster.local:9200), i think the helm chart is buggy or kubernetes v1.8.6 and 1.9.9 are buggy.

**Comment by rajkumar49** [comment]
hi @monotek , i got the below error in the logstash pod , ( FYI: i am using the helm chart)
 
[elkstack-logstash-0] [2018-07-23T08:24:51,553][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://elasticsearch-client.default.svc.cluster.local:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://elasticsearch-client.default.svc.cluster.local:9200/][Manticore::ResolutionFailure] elasticsearch-client.default.svc.cluster.local"}

**Comment by rajkumar49** [comment]
Any update ?

**Comment by rajkumar49** [comment]
hi

**Comment by Fgruntjes** [comment]
Having the exact same issue here

**Comment by yregaieg** [comment]
@Fgruntjes I am kind of noob in this area, but I managed to workaround this issue by :
1- access kubernetes dashboard
2- point to the namespace I deployed the chart to
3- access the deployments section
4- update it to have the elastic url points to <release-name>-elasticsearch-client.<namespace>.svc.cluster.local
And that seems to have done the trick !
