### ISSUE TITLE
Expose the Spinnaker UI via LoadBalancer

### ISSUE THREAD

**Issue by pluttrell** [helm/charts#669]
Is there a way to get the spinnaker chart to expose the UI (deck) via a LoadBalancer instead of ClusterIP?

**Comment by viglesiasce** [comment]
Yes but currently no auth is implemented so you would be opening up your cluster to the world. Once auth (fiat) is baked in sensibly I think making that configurable makes sense.

**Comment by pluttrell** [comment]
Oh, I wasn't aware that auth hadn't been integrated yet. I don't see another ticket for that, so I just added [one](https://github.com/kubernetes/charts/issues/673).

What's the timeframe for implementing these changes? We'd love to be able to use the Spinnaker chart for out Spinnaker install, but in its current state - forcing users to setup port forwarding and use the local proxy every time they want to use Spinnaker is a nonstarter.

**Comment by viglesiasce** [comment]
More info on implementing auth is available here:

http://www.spinnaker.io/docs/securing-spinnaker

Once it is out of alpha we can implement the changes in the chart.

**Comment by seanknox** [comment]
Closing per Vic's comments.
