### ISSUE TITLE
MariaDB: Add persistence by default support using PVCs

### ISSUE THREAD

**Issue by chrislovecnm** [helm/charts#67]
Should Mariadb have PV storage?  If I have reading it correctly it is using a emptydir.

https://github.com/kubernetes/charts/blob/master/stable/mariadb/templates/deployment.yaml

**Comment by viglesiasce** [comment]
Check out https://github.com/kubernetes/charts/pull/43

**Comment by prydonius** [comment]
Once Kubernetes 1.4 is released, I can add PVC provisioning support to the MariaDB chart

**Comment by prydonius** [comment]
Implemented in #90
