### ISSUE TITLE
Allow Filebeat to pass in annotations to the daemonset

### ISSUE THREAD

**Issue by jimbeck** [helm/charts#6700]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
**FEATURE REQUEST**

We want to be able to pass in configurable annotations to the filebeat daemonset.<br>
Our use case is that we need filebeat to write to aws elasticsearch service. We have kube2iam configured and need to add an annotation to the filebeat daemonset so that it can assume an iam role to have access to write to elasticsearch.

**Version of Helm and Kubernetes**:
helm - 2.9.1
k8s - 1.10

**Which chart**:
Filebeat

**What happened**:
Cannot configure annotations on the filebeat daemon set

**What you expected to happen**:
We can configure annotations on the filebeat daemon set

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by monotek** [comment]
added a pr for this: https://github.com/helm/charts/pull/6751
