### ISSUE TITLE
[stable/traefik] option to configure tls for ingress

### ISSUE THREAD

**Issue by maver1ck** [helm/charts#6727]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm v2.9.1
Kubernetes v1.9.6

**Which chart**:
Traefik

**What happened**:
There is no possibility to configure tls section in ingress

**What you expected to happen**:
TLS section can be configured

**Anything else we need to know**:
Example chart with TLS:
https://github.com/helm/charts/blob/master/stable/kubernetes-dashboard/templates/ingress.yaml
spec.tls section

**Comment by dtomcej** [comment]
@maver1ck The chart has been updated to include a much newer version of Traefik. Ingress TLS is fully supported.

Do you feel this is still an issue?

**Comment by maver1ck** [comment]
@dtomcej 
Yes.
There is still no TLS section in:
https://github.com/helm/charts/blob/master/stable/traefik/templates/dashboard-ingress.yaml

**Comment by dtomcej** [comment]
Feel free to contribute to add the feature in!

**Comment by tlmiller** [comment]
Would also be great to see this merged. Need this to allow cert-manager to generate certs automagically.
