### ISSUE TITLE
incubator/Kafka support for additional clouds

### ISSUE THREAD

**Issue by drekle** [helm/charts#6739]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-rc.1", GitCommit:"2106a5910f6de3c07b8f329c7adaca38a0d3f825", GitTreeState:"clean", BuildDate:"2018-03-19T23:38:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kafka

**What happened**:
kafka makes the assumption that you are running on aws and have deployed using kops.
because the following file:
https://github.com/helm/charts/blob/master/incubator/kafka/templates/service-brokers-external.yaml
uses the annotation `dns.alpha.kubernetes.io/internal` which is a kops specific dns controller documented here...
https://github.com/kubernetes/kops/tree/master/dns-controller

**What you expected to happen**:
kafka should be more cloud agnostic

**How to reproduce it** (as minimally and precisely as possible):
deploy on anything other than a aws kops deployment

**Anything else we need to know**:
no

**Comment by benjigoldberg** [comment]
Thanks for the issue submission and PR @drekle -- excited to get this out and correct my oversight on this one!
