### ISSUE TITLE
[incubator/kafka] KAFKA_ADVERTISED_LISTENERS should use hostname instead of IP

### ISSUE THREAD

**Issue by Chehai** [helm/charts#6754]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
incubator/kafka

**What happened**:
After a Kafka pod is restarted, applications cannot reconnect to the pod. The pod advertises its IP to applications, but after restart, the pod gets a new IP after restart, so applications cannot reconnect to the pod using the old IP.

**What you expected to happen**:
When a Kafka pod is restarted, applications can reconnect to the pod.

**How to reproduce it** (as minimally and precisely as possible):
1. Run Kafka with this chart with 1 Kafka pod.
2. Start an application pod that connects to Kafka.
3. Delete kafka-0 pod
4. Application pod cannot connect to Kafka anymore.

**Anything else we need to know**:

Changing https://github.com/helm/charts/blob/master/incubator/kafka/templates/statefulset.yaml#L186 to use something like `PLAINTEXT://${POD_NAME}.{{ include "kafka.fullname" . }}-headless:9092`

**Comment by benjigoldberg** [comment]
@Chehai have you tried using the headless service names instead of IP address in your application pod? Eg conecting to `<statefulset>-<pod-number>` instead of IP?

**Comment by Chehai** [comment]
I did try having my Kafka client connecting to the headless service (like setting bootstrap.servers = kafka-headless:9092). However, I had the same problem. When the Kafka client was reconnecting to Kafka, it tried to use the addresses from `KAFKA_ADVERTISED_LISTENERS` (returned from Zookeeper) instead of addresses listed in `bootstrap.servers`. `KAFKA_ADVERTISED_LISTENER` had the old pod IP, so the Kafka client still could not connect.

**Comment by gallolp** [comment]
Hi @Chehai just in case you are still dealing with the problem this did the trick for me: https://github.com/gallolp/charts/commit/0984cd4552690cbbbe56454ce26b39fae45faeab

I added .POD_NAMESPACE to your suggestion in order to be able to access the cluster from a different namespace (for example I'm using kubeless)

**Comment by Chehai** [comment]
Cool! Thank you, @gallolp 

Hopefully, the official chart can get your fix soon.

**Comment by benjigoldberg** [comment]
not stale

**Comment by sundhar010** [comment]
not stale

**Comment by vemv** [comment]
not stale

**Comment by vemv** [comment]
not stale
