### ISSUE TITLE
Can't get internet from fresh install of Kubertnetes and OPENVPN

### ISSUE THREAD

**Issue by spiderSorus** [helm/charts#6755]
**Is this a request for help?**:

yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:03:09Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
OpenVPN

**What happened**:
Can't get internet from newly installed VPN once connected - a

**What you expected to happen**:
Create cluster - install helm, install openvpn - connect - internet!

**How to reproduce it** (as minimally and precisely as possible):
https://s3.amazonaws.com/quickstart-reference/heptio/latest/doc/heptio-kubernetes-on-the-aws-cloud.pdf follow this guide, 
Install helm
helm install stable/openvpn --name=whatever

**Anything else we need to know**:
Tried troubleshooting on many layers - comes back to openvpn - doesn't look like routes are correct.

**Comment by dangersorus** [comment]
logs from the pod once it is up: Sat Jul 21 21:37:43 2018 192.168.202.64:36798 Connection reset, restarting [0]
Sat Jul 21 21:37:43 2018 192.168.202.64:36798 SIGUSR1[soft,connection-reset] received, client-instance restarting
Sat Jul 21 21:37:43 2018 192.168.11.192:20849 Connection reset, restarting [0]
Sat Jul 21 21:37:43 2018 192.168.11.192:20849 SIGUSR1[soft,connection-reset] received, client-instance restarting
Sat Jul 21 21:37:43 2018 TCP connection established with [AF_INET]192.168.104.64:24444
Sat Jul 21 21:37:43 2018 192.168.104.64:24444 Connection reset, restarting [0]
Sat Jul 21 21:37:43 2018 192.168.104.64:24444 SIGUSR1[soft,connection-reset] received, client-instance restarting
Sat Jul 21 21:37:44 2018 TCP connection established with [AF_INET]192.168.11.192:20851
Sat Jul 21 21:37:44 2018 192.168.11.192:20851 Connection reset, restarting [0]
Sat Jul 21 21:37:44 2018 192.168.11.192:20851 SIGUSR1[soft,connection-reset] received, client-instance restarting
Sat Jul 21 21:37:49 2018 TCP connection established with [AF_INET]10.0.2.177:22741
Sat Jul 21 21:37:49 2018 10.0.2.177:22741 Connection reset, restarting [0]
Sat Jul 21 21:37:49 2018 10.0.2.177:22741 SIGUSR1[soft,connection-reset] received, client-instance restarting
