### ISSUE TITLE
Redis-Ha doesn't elect a new master after deleting the master pod.

### ISSUE THREAD

**Issue by evhfla-zz** [helm/charts#6757]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Helm Version 2.9.1
Kubernetes Version 1.93 with RBAC Enabled

**Which chart**:
Redis-ha

**What happened**:
If I delete the master pod to check Ha....No new pod every gets elected as a new master....When, the new pod starts, it sees that there is no master, and then it proceed on electing another pod as master, but that pod never gets labeled as master.....Therefore, the new pod starts over and over again and never gets a new master.

**What you expected to happen**:
The different pod elected as master gets it role change, which should result in a new master.

**How to reproduce it** (as minimally and precisely as possible):
Deployed Redis-HA chart, and delete the master pod.  See the new pod starts, and says it is electing an existing pod as a new master, but that pod never gets updated with the "redis-role" of master.

**Anything else we need to know**:

**Comment by KoviaX** [comment]
It seems to be caused by the same issue mentioned in #5441. If during start-up multiple servers received the master label, the sentinels never get a correct configuration, thus try to elect a non-existing pod as master.

**Comment by str1k3r** [comment]
same here. faced with that during chart upgrade.

**Comment by evhfla** [comment]
Is there an older chart that still works?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by brianbaquiran** [comment]
I'm seeing this problem now as well, in a staging environment. The chart version installed was 2.0.0, and upgrading to later charts doesn't work:

```
$ helm upgrade  staging-redis stable/redis-ha
Error: UPGRADE FAILED: Deployment.apps "staging-redis-redis-ha-sentinel" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"redis-ha", "component":"sentinel", "name":"staging-redis-redis-ha-sentinel", "release":"staging-redis"}: `selector` does not match template `labels` && Deployment.apps "staging-redis-redis-ha-server" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"redis-node":"true", "release":"staging-redis", "app":"redis-ha", "component":"server", "name":"staging-redis-redis-ha-server"}: `selector` does not match template `labels```

Any recommended course of action? I would like to preserve the data already in redis.

**Comment by michaeleino** [comment]
I think there is an issue detecting the failed/running pods from the docker container image!

This pr should fix this issue...
https://github.com/smileisak/docker-images/pull/17
I have created it a few days, but there is no action taken yet :/

**Comment by SLionB** [comment]
Great job Michael. Waiting for the fix..
