### ISSUE TITLE
Application package in the context of a cluster

### ISSUE THREAD

**Issue by pierreozoux** [helm/charts#679]
To address @chrislovecnm [comment](https://github.com/kubernetes/charts/issues/44#issuecomment-256251007):

> are we going to name charts that have multiple variants
> For example Redis without ha, redis with slaves, redis clustered
> Do we have one massive nasty chart or three charts?

We have to define what is a packaged application in a context of a cluster.
If k8s offers me an abstraction of compute resources, helm offers me an abstraction to run application in this context.

IMHO, we deploy application on a cluster to be replicated and to avoid the SPOF. With this in mind, I would say that the default should be the replicated version of the application.

In this case, I'd rename `etcd-operator` to `etcd` for instance.

**Comment by seanknox** [comment]
> are we going to name charts that have multiple variants
For example Redis without ha, redis with slaves, redis clustered
Do we have one massive nasty chart or three charts?

One of the goals of the charts project is to provide cloud native patterns for applications on Kubernetes. While it's of course not possible to satisfy every possible need for an installation, we do try to handle these on a case-by-case basis.
