### ISSUE TITLE
Use existing jenkins instead of Provided by chart

### ISSUE THREAD

**Issue by devanshuoza** [helm/charts#6790]
**Is this a request for help?**:
Yes It is a request
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Version of Helm and Kubernetes**:
Helm
-------
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Kubernetes
-----------------------
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
spinnaker

**What happened**:
I am trying to use my existing jenkins with current spinnaker installation. I have fire below command to achieve the same & i have also disabled jenkins from values.yaml

helm install -f values.yaml --name spinnaker stable/spinnaker \
--set services.jenkins.enabled=true \
--set services.jenkins.defaultMaster.baseUrl=<jenkins url> \
--set services.jenkins.defaultMaster.username=<jenkins User> \
--set services.jenkins.defaultMaster.password=<jenkins password> \
--set services.igor.enabled=true \
--namespace=spinnaker

value.yaml changes
----------------------------------
# Configuration for the Jenkins instance that is attached to the
# igor component of Spinnaker. For more info about the Jenkins integration
# with Spinnaker, visit:
#   https://www.spinnaker.io/setup/ci/jenkins/
jenkins:
  enabled: false
  Master:
    Cpu: "500m"
    Memory: "512Mi"
    ServiceType: ClusterIP
    CustomConfigMap: true
    NodeSelector: {}

  Agent:
    Cpu: "500m"
    Memory: "512Mi"
    NodeSelector: {}

**What you expected to happen**:
After successfully installation i am able to set trigger point as my jenkins job in pipeline.

**How to reproduce it** (as minimally and precisely as possible):
Give proper documentation

**Anything else we need to know**:
I didn,t find any proper documentation related to same so can you guide me on same it will help me & thank you in advance for help

**Comment by alexvicegrab** [comment]
You should be able to provide your own Docker image and tag:

```
Master:
  Image: myawesomejenkinsimage
  ImageTag: lts-2018-07-30
```

**Comment by Devanshu5833** [comment]
@oliverisaac  thanks for your help but i am still not getting you exactly so is it fix or am i implementing something wrong ?
can you please help me to understand the same ?

**Comment by oliverisaac** [comment]
@Devanshu5833 : The PR I submitted is no longer relevant as #6407 does the same thing and much much more. If you really want to stick with the "old" Spinnaker implementation you can fork/clone my branch in #7208 but I really don't recommend that. I haven't implemented the "new" Spinnaker implementation yet so I can't provide any suggestions there.
