### ISSUE TITLE
 [stable/mogodb] Write access to volume broken

### ISSUE THREAD

**Issue by bastianeicher** [helm/charts#6791]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  BUG REPORT

**Version of Helm and Kubernetes**:
Helm Version: 2.9.1
Kubernetes Version: 1.10

**Which chart**:
`stable/mongodb`

**What happened**:
I installed the chart with no additional configuration. The pod went into a crash loop with the following log output:
```
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mongodb/data'
```

**How to reproduce it** (as minimally and precisely as possible):
```
helm install stable/mongodb --name mytest
kubectl logs deploy/mytest-mongodb
```

**Comment by EOS9Cat** [comment]
I had the same issue since the new version.

Version of Helm and Kubernetes:
Helm Version: 2.9.1
Kubernetes Version: 1.10.4

Which chart:
stable/mongodb

```
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues

nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB from scratch...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mongodb/data'
````

**Comment by bappr** [comment]
Seems buggy only with Chart Version: 3.0.4

```helm install stable/mongodb --name mytest --version 3.0.3``` works.

**Comment by redpolarbear** [comment]
I had the same issue.

**Version of Helm and Kubernetes:**
Helm Version: 2.9.1
Kubernetes Version: 1.10.4

**Which chart:**
stable/mongodb

What happened:

```
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mongodb/data'
```

**Comment by pmilewsk** [comment]
I have same issue for both charts 3.0.3 and 3.0.4

**Version of Helm and Kubernetes:**
Helm: 2.8.2
Kubernetes Version: v1.10.0

**Which Chart:**
stable/mongodb

**What happened:**
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mongodb/data'

**Comment by alexjg** [comment]
I'm also encountering this issue but can't find a reliable way to reproduce it.
