### ISSUE TITLE
Keycloak cannot be deployed with an external postgres named "postgres"

### ISSUE THREAD

**Issue by zcourts** [helm/charts#6802]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
No. This is more an FYI for others to document the issue.

**Version of Helm and Kubernetes**:
Helm 2.7.0, K8s 1.8

**Which chart**:
Keycloak

**What happened**:
If using an external postgres, the postgres service cannot be called `postgres`. The name results in `POSTGRES_PORT` being made an env. var. by K8s. There is legacy support in K8s for the env variable and the value that K8s puts in `tcp://some-ip:some-port` is wrong.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Configure keycloak to use an external postgres whose name/service is called `postgres`.

**Anything else we need to know**:

The fix/workaround is to rename the postgres service. If it's new, just avoid creating it with that name to begin with.

You can rename the postgres install by setting:
```
  fullnameOverride: postgresdb
```
when installing with the postgres chart.

**Comment by zcourts** [comment]
For reference the legacy support for this env var is in https://github.com/jboss-dockerfiles/keycloak/blob/master/server/docker-entrypoint.sh#L64

**Comment by manipulator01** [comment]
I am having the same issue.
I have some other services depending on 'postgres' name. Can you think of any other workaround @zcourts ?

p.s. thanks for creating an issue <3

**Comment by zcourts** [comment]
You could probably provide your own `docker-entrypoint.sh` (mount a volume at the path which points to yours) which removes/changes the function I mentioned above.
Provide a custom start command in the spec. I've not tried either but both should be doable
