### ISSUE TITLE
[stable/cert-manager]

### ISSUE THREAD

**Issue by drekle** [helm/charts#6816]
**Is this a request for help?**:
No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-rc.1", GitCommit:"2106a5910f6de3c07b8f329c7adaca38a0d3f825", GitTreeState:"clean", BuildDate:"2018-03-19T23:38:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
[stable/cert-manager]

**What happened**:
I wrote an umbrella chart for cert-manager where another chart deploys resources defined by the cert-manager chart.  It fails with error:
```
Error: apiVersion "certmanager.k8s.io/v1alpha1" in devops2-init/charts/cert-manager-configs/templates/certificates.yaml is not available
```
because the CRD's are not yet deployed.

**What you expected to happen**:
I expect the install of cert-managers CRD to be in helm pre-install

**How to reproduce it** (as minimally and precisely as possible):
Dependencies structured in the following way.
- cert-manager-consumsuer
   | - cert-manager

where cert-manager-consumer deploys any Custom Resource defined by cert-manager

**Anything else we need to know**:

**Comment by jstriebel** [comment]
I guess that is because of the order the resources (especially CRD) are installed.
This is defined [here](https://github.com/helm/helm/blob/506ed05b84a1477c96708c53a38eb86ba79a4670/pkg/tiller/kind_sorter.go#L29-L55).

This issue seems to be related: #2994

Installing this first without the certificates (or any other CRD resources) and then upgrading should help for the moment.

**Comment by drekle** [comment]
I believe there is just a set of helm hooks needed.  I had this working but got into an argument with myself.

https://github.com/helm/helm/blob/master/docs/charts_hooks.md#defining-a-crd-with-the-crd-install-hook

**Comment by jstriebel** [comment]
Yes, I guess you would need to add the annotation [here](https://github.com/helm/charts/blob/master/stable/cert-manager/templates/certificate-crd.yaml#L4). At the moment it's not defined and not possible with values, so maybe just test it manually once and have a PR in the upstream repo https://github.com/jetstack/cert-manager/

**Comment by drekle** [comment]
closing with relevant link:
https://github.com/helm/helm/issues/2680
