### ISSUE TITLE
[stable/rabbitmq] Not a directory error on start up

### ISSUE THREAD

**Issue by swackhamer** [helm/charts#6823]
**Version of Helm and Kubernetes**:
k8s: 1.10.5
helm: 2.9.1

**Which chart**:
stable/rabbitmq

**What happened**:
After installing the helm chart the container goes into a crash loop producing the following error before crashing.

`cp: cannot create regular file '/opt/bitnami/rabbitmq/.rabbitmq/': Not a directory
`

**How to reproduce it** (as minimally and precisely as possible):
Install the latest helm chart for rabbitmq v2.0.0

**Anything else we need to know**:
This bug is not present in version 1.1.9 of the helm chart.

It appears to be an issue with line 61 in statefulset.yaml https://github.com/helm/charts/commit/432c4b9e4b0610c5dd2a39bf96c8c5f9f9b71b27#diff-1e6c6c83dddf5c9d0e6789776eb17f8eL62

**Comment by romankor** [comment]
but present in version `2.2.0` not present in `1.1.8`
