### ISSUE TITLE
[stable/mongodb-replicaset] Why does the init container not log to stdout?

### ISSUE THREAD

**Issue by floriantraber** [helm/charts#6830]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE  REQUEST

**Which chart**: stable/mongodb-replicaset

**What happened**: The on-start script in the init container doesn't log to stdout but only to a log file. (See https://github.com/helm/charts/blob/master/stable/mongodb-replicaset/init/on-start.sh#L36)

**What you expected to happen**: I would expect the script to log to stdout. The command `kubectl logs POD_NAME-0 -c bootstrap` should return all logs. At a minimum I would expect the log file location to be mentioned in the readme.

**How to reproduce it** (as minimally and precisely as possible): Install the current version of the chart.

**Comment by unguiculus** [comment]
This is because the logs would be lost. The script is called by peer finder which doesn't capture the output.
