### ISSUE TITLE
[stable/mongodb-replicaset] Metrics cannot be enabled on an helm upgrade

### ISSUE THREAD

**Issue by sekka1** [helm/charts#6833]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
```
helm
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

**Which chart**:
stable/mongodb-replicaset

**What happened**:
If you start out with this chart (stable/mongodb-replicaset) without enabling the metrics, you are not able to enable it with an upgrade and the entire cluster goes into a `CrashLoopBackOff` state because the `metrics` container liveness probe fails.

**What you expected to happen**:
I expect the metrics to fully enable on an upgrade and not crash.

**How to reproduce it** (as minimally and precisely as possible):
1) Helm install this chart without enabling metrics, let the mongo cluster finish starting up

You can use any version of this chart.

2) enable the metrics by switching the flag in the values.yaml file
```
# Prometheus Metrics Exporter
metrics:
  enabled: true
```
3) Upgrade the helm chart with this new value

**Anything else we need to know**:
It looks like the mongo user for the metrics is never created on the upgrade.

This works on a new install with the metrics enabled.

**Comment by sekka1** [comment]
Looks like on an upgrade to enable the `metrics`, it will never reach this section and wont create the `metrics` user:  https://github.com/helm/charts/blob/master/stable/mongodb-replicaset/init/on-start.sh#L138

**Comment by ssalaues** [comment]
Yeah definitely an issue there when upgrading to enable metrics w/ auth enabled. Also when testing this I found that it looks like upgrades from `auth.enabled = false` to `auth.enabled = true` causes a crash loop =(
