### ISSUE TITLE
[stable/mongodb] Deploy mongoDB in replica-set mode the arbiter connect primary fail

### ISSUE THREAD

**Issue by mingyuanzhu** [helm/charts#6857]
**Is this a request for help?**:
---
Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
Helm version: 2.9.1
Kubernetes: 1.10.2

**Which chart**:
stable/mongodb

**What happened**:
The arbiter connection primary timeout cause the pod always restart
`Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues

nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB from scratch...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
mongodb INFO  ==> Writing keyfile for replica set authentication
mongodb INFO  ==> Configuring MongoDB replica set
mongodb INFO  ==> Enabling MongoDB replica set mode
mongodb INFO  ==> Configuring MongoDB arbiter node
INFO  Trying to connect to MongoDB server
Error executing 'postInstallation': Failed to connect to xxxxxxxxxxx:27017 after 36 tries`

**What you expected to happen**:
Connection sucessfully.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I use the nodeport type as the primary svc. Deploy the primary, secondary and arbiter in different node.

**Comment by mingyuanzhu** [comment]
Sorry, my mistake. Config the error network plugin.

**Comment by jimmiebtlr** [comment]
How did you fix this?  I'm having I think the same issue.

**Comment by zoonman** [comment]
What did you do?
