### ISSUE TITLE
[stable/prometheus] Unable to run multiple instances

### ISSUE THREAD

**Issue by mumarniaz** [helm/charts#6879]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Version of Helm and Kubernetes**:
Helm:
`Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}`
`Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}`

Kubernetes:
`Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

**Which chart**:
`6.8.0`

**What happened**:
Helm is failed to deploy multiple instances of Prometheus and Alertmananger, when i set the replica count for both Prometheus and Alertmanager to `2` in `values.yaml` file, only one instance created and 2nd one crashed due to persistence volume issue. Also there is no way to run alert manager in HA mode. There is no configuration available to run alertmanager in high availability mode.

**What you expected to happen**:
When i set the replica count to 2 in values.yaml file, it should spin up 2 pods for both Prometheus and Alert Manager.

**How to reproduce it** (as minimally and precisely as possible):
Change the replica count from `1` to `2` in values.yaml file for both prometheus server and alertmanager.

**Anything else we need to know**:

**Comment by rekcah78** [comment]
@mumarniaz 
it's normal with a persistent volume And Deployment, only one pod can be use the volume so replica max value is 1.

in my case for prometheus and alertmanager i use prometheus-operator an he deploy with a StatefulSet so all pod have a volume for himself if you want replica > 1.
