### ISSUE TITLE
OpenVPN improvements

### ISSUE THREAD

**Issue by cemo** [helm/charts#688]
I did not want to open issue for each one and want to summarize improvements which would be nice.

- [ ] Persistence storage / Multi user support (statefulset support)
- [ ] Google authenticator support
- [ ] Backup support 
- [ ] Batch creation of users 

Some of these issues are already solved in https://github.com/kylemanna/docker-openvpn. It might be better idea to rely on their image?

**Comment by cemo** [comment]
Gentle ping @jfelten :)

**Comment by seanknox** [comment]
Hi @cemo, we welcome improvements to charts through pull requests. Feel free to open one (or many!).
