### ISSUE TITLE
[stable/rabbitmq] Cannot update rabbitmq if PersistentVolume is used

### ISSUE THREAD

**Issue by desaintmartin** [helm/charts#6885]
StatefulSet.volumeClaimTemplates contains version of the chart as metadata, but StatefulSet.volumeClaimTemplates is immutable.

Trying to update it will cause error:

```
# statefulsets.apps "cayzn-cm-production-rabbitmq" was not valid:
# * spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```

Maybe we should remove metadata from the volumeClaimTemplates (if so, let me know so that I do a PR). Should we remove all of them? Only the "chart" one? Replace by chart name without version?

cc @prydonius @tompizmor @sameersbn @carrodher @juan131

**Comment by rekcah78** [comment]
@desaintmartin 
you can delete the statefulset with cascade: false
kubectl delete statefulset cayzn-cm-production-rabbitmq --cascade=false
with this command you delete only statefulset but not the pods.
After that your can apply a helm upgrade, he will recreate the statefulset and attach the existing pods.

**Comment by desaintmartin** [comment]
Thanks for the tip, but is that the official way of doing upgrades with Helm? I sometimes use this trick for dev purposes but I would like to avoid anything like this in production.

**Comment by rekcah78** [comment]
Yes is hard to think to do something like this in the production but actually is the only way to do that.

**Comment by desaintmartin** [comment]
Linked to https://github.com/helm/charts/issues/7680
