### ISSUE TITLE
pull e2e tests not showing up as required status anymore

### ISSUE THREAD

**Issue by foxish** [helm/charts#691]
http://prow.k8s.io/?type=presubmit&repo=kubernetes%2Fcharts
It seems like the last PR that the presubmits ran against was https://github.com/kubernetes/charts/pull/627

cc @viglesiasce @michelleN @spxtr

**Comment by spxtr** [comment]
I think it's working properly. Note that prow only keeps around the last day of data. https://github.com/kubernetes/charts/pull/686 was tested properly. https://github.com/kubernetes/charts/pull/690 was tested properly after saying `@k8s-bot ok to test`.

I recommend setting the prow test to required under protected branches in the settings for the repo. Then it's more difficult to merge if the test doesn't run.

**Comment by foxish** [comment]
@viglesiasce @michelleN, I think we should set the test as required. I can see that even now, several PRs aren't being blocked by e2es failing.
