### ISSUE TITLE
[incubator/jaeger] More configuration options for components

### ISSUE THREAD

**Issue by sta-szek** [helm/charts#6975]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST
**Which chart**: jaeger

It would be nice to have more configuration options like:
* env variables taken from `values.yaml` e.g.:
```
env:
  CASSANDRA_SERVERS: ...
  CASSANDRA_PORT: ...
```
* provide UI configuration file as config map, which is taken from `values.yaml`

**Comment by dvonthenen** [comment]
Hi @sta-szek 

For your first item, those are cassandra specific configuration parameters. For subcharts like cassandra or elasticsearch, you can already override all of the options that those charts expose. For specific options in cassandra and elasticsearch that might be missing, you might want to reach out to those chart maintainers.

For your second item, can you provide specific options? You can also add as many command line options to the Query UI (as well as other components) via the `cmdlineParams` field.
