### ISSUE TITLE
[incubator/jaeger] Sample configurations

### ISSUE THREAD

**Issue by sta-szek** [helm/charts#6976]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST
**Which chart**: jaeger

Hi, actually I don't know if that issue should be here, as sample configurations depends or kubernetes (ingress / services / ...) configuration.
However I believe it would be nice to prepare few (or at least one, the most used) configurations + images with description.

E.g. 
1. If you want to expose UI and hide everything else then use LoadBalancer or Ingress for query-pod. + image
2. If you disable host network then smth will stop working...

I know this is more k8s management knowledge, however it will be really helpful for people to start with that (quite complex) chart.

Maybe it would solve my problem -- I use default values (which I believe should be production ready) and have error on agents:
```
{"level":"info","ts":1533304410.5446763,"caller":"peerlistmgr/peer_list_mgr.go:157","msg":"Not enough connected peers","connected":0,"required":1}
{"level":"info","ts":1533304410.5447237,"caller":"peerlistmgr/peer_list_mgr.go:166","msg":"Trying to connect to peer","host:port":"jaeger-collector:14267"}
{"level":"error","ts":1533304410.7951396,"caller":"peerlistmgr/peer_list_mgr.go:171","msg":"Unable to connect","host:port":"jaeger-collector:14267","connCheckTimeout":0.25,"error":"tchannel error ErrCodeTimeout: timeout","stacktrace":"github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).ensureConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:171\ngithub.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).maintainConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:101"}
```
(does not have it when running docker all-in-one locally)

**Comment by dvonthenen** [comment]
Hi @sta-szek 

I would think the most used configuration is the default which is simply `helm install incubator/jaeger`. If you are looking for customizing paramters, I would read the helm documentation located at https://docs.helm.sh/using_helm and look for the section "Customizing the Chart Before Installing".

For #1, I am not sure what you mean by "hide everything else". The chart already supports using a LoadBalancer which can be configured using `--set query.service.loadBalancerSourceRanges` and ingress can be enabled using `--set query.ingress.enabled=true` providing you have an ingress controller setup.

Not really sure I understand your #2. You can find me in the Kubernetes slack channel #helm-users if you want to discuss.
