### ISSUE TITLE
Add `read-only` mode for weave scope

### ISSUE THREAD

**Issue by ivanfitenko** [helm/charts#6977]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Which chart**: weave-scope 
Weave Scope has an option to disable potentially dangerous controls, for example 'delete pod' or 'run shell on node'. It would be good to leverage this feature in chart. 
Also, as per https://github.com/weaveworks/scope/issues/3153,  we can reduce the number of perms given to cluster role (and thus, optionally, disable delete and update permissions).

**Comment by upalkhouski** [comment]
hey @unguiculus , would you please remove the stale status? We are still looking forward to the accepted PR
