### ISSUE TITLE
[stable/cert-manager] Does not use crd hook and fails when used as dependency

### ISSUE THREAD

**Issue by kbambridge** [helm/charts#6989]
**Is this a request for help?**:
Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Chart cert-manager v0.4.0

installing with no custom values.yaml other than `--name` and `--namespace cert-manager`

**Version of Helm and Kubernetes**:

`v2.10.0-rc.2`

**Which chart**:
cert-manager
v0.4.0

**What happened**:
Tried to install the chart as a dependency with a Certificate and ClusterIssuer in the upper helm chart, but it complains about the crds

```
Error: validation failed: [unable to recognize "": no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1", unable to recognize "": no matches for kind "ClusterIssuer" in version "certmanager.k8s.io/v1alpha1"]
```

**What you expected to happen**:

Install without problems

**How to reproduce it** (as minimally and precisely as possible):
Create a helm chart with cert-manager v0.4.0 as dependency, and in templates folder put a
`Certificate` and `ClusterIssuer` and `Secret` that's linked to the previous two.

**Anything else we need to know**:

I also tried installing the crds first with `helm template` but unfortunately it errors with:

```
Error: release aot-cert-manager failed: customresourcedefinitions.apiextensions.k8s.io "certificates.certmanager.k8s.io" already exists
```

even when using `helm install --no-crd-hook ...`

**Comment by sundeer** [comment]
Ran into this as well. Without crd hook, it a 2-step process to install.

**Comment by tranx** [comment]
Idem, it should be straightforward to use cert-manager as a dependency in another helm chart. For the moment it don't manage to get that working without introducing a multistage pipeline which seems to defeat the purpose of automation with helm.If it is possible as a dependency documentation needs to be clearer.

**Comment by davidjytang** [comment]
Can confirm the same with 0.5.0 as well.

**Comment by davidjytang** [comment]
Not sure if this would help. From documentation: [Installing cert-manager#With static manifests](https://cert-manager.readthedocs.io/en/latest/getting-started/2-installing.html#with-static-manifests)
It has links to example templates:
https://github.com/jetstack/cert-manager/blob/master/contrib/manifests/cert-manager

**Comment by wstewartii** [comment]
I'm running into this issue too. It would be great if this issue wasn't closed without a resolution.

**Comment by WCMinor** [comment]
I got this working in `v0.6.0` by setting in the values.yaml:
```
cert-manager:
  createCustomResource: true
```

But I had to do a fresh `heml delete --purge nameofrelease` + `helm install .`

Also, you have to make sure that the custom definitions are not externally created (as the cert-manager) people propose in their documentation, otherwise it will fail.

What it does is to create the custom resource definitions that is complaining of not being already there, you can check that they are present after the helm install:
```
$ kubectl get customresourcedefinitions
NAME                                CREATED AT
certificates.certmanager.k8s.io     2019-02-12T20:23:47Z
clusterissuers.certmanager.k8s.io   2019-02-12T20:23:47Z
issuers.certmanager.k8s.io          2019-02-12T20:23:47Z
```

This way I have it all working in a single step deployment, whoever, this is poorly documented, I just saw that the helm chart was able to create the custom resource definitions looking into the cert-manager chart templates.
