### ISSUE TITLE
mongodb chart: respect existingSecret in standalone deployment

### ISSUE THREAD

**Issue by xornet-sl** [helm/charts#7047]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
This is a BUG

**Version of Helm and Kubernetes**:
Helm version 2.9.1
Kubernetes version 1.11.0

**Which chart**:
stable/mongodb chart version 4.0.4

**What happened**:
standalone mongodb doesn't respect .Values.existingSecret but replicaset does.

**What you expected to happen**:
Secret handling with and without replicaset should be similar.

**How to reproduce it** (as minimally and precisely as possible):
```
helm install -n mongodb --set replicaSet.enabled=false --set usePassword=true --set existingSecret=mongodb --set fullnameOverride=mongodb stable/mongodb
```
This command will fail with `Error: release mongodb failed: secrets "mongodb" already exists` if there is a precreated secret with name `mongodb`.
Moreover `helm delete --purge mongodb` will delete this "existing", predefined secret.
if we omit `--set fullnameOverride` it will create another secret (i.e. won't use --set existingSecret).

**Anything else we need to know**:

**Comment by sfitts** [comment]
Just wanted to report the same issue.  Has not been addressed so hopefully it won't get aged out (makes the chart hard to use unless you only enable the replica set).
