### ISSUE TITLE
Statefulset replicas Update Error

### ISSUE THREAD

**Issue by Krueladin** [helm/charts#7070]
**BUG REPORT**

**Version of Helm and Kubernetes**:
Helm:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Kubernetes:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/rabbitmq

sources:
- https://github.com/bitnami/bitnami-docker-rabbitmq
version: 2.1.1

**What happened**:
Installed the chart onto the cluster, then ran a helm upgrade command which failed.

Fails with the following error message: `Error: UPGRADE FAILED: StatefulSet.apps "warped-zorse-rabbitmq" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.`

**What you expected to happen**:
Excepted the number of replicas to change from 1 to 5.

**How to reproduce it** (as minimally and precisely as possible):
`helm install stable/rabbitmq`
`helm upgrade warped-zorse stable/rabbitmq --set replicas=5`

**Comment by Simon3** [comment]
See https://github.com/helm/charts/issues/7803 ?
