### ISSUE TITLE
[stable/mongodb] [bitnami] replicaset.enabled=true cluster is not functional after any pod upgrade operation

### ISSUE THREAD

**Issue by dennybaa** [helm/charts#7075]
Replicaset gets broken after any upgrade... rs.initiate() initializes replicaset hosts with IP addresses, since any pod kill/restart produces a new IP address all hosts are removed from the replicaset.
Any clues how to overcome this? Where us rs.initiate() buried inside bitnmani configurations?

It would be nice to be able to use DNS hostnames instead of IPs, such as

```
{{ template "mongodb.fullname" . }}-secondary-0.{{ template "mongodb.fullname" . }}-headless.{{ .Release.Namespace }}.svc.cluster.local
```

```js
	"members" : [
		{
			"host" : "100.96.10.51:27017",
		},
		{
			"host" : "100.96.9.44:27017",
		},
		{
			"host" : "100.96.8.43:27017",
		}
	],
```

**Version of Helm and Kubernetes**: 1.9.2
**Which chart**: stable/mongodb 4.0.5

**Comment by juan131** [comment]
I just responded at https://github.com/bitnami/bitnami-docker-mongodb/issues/105

Let's try to continue with the discussion there so we avoid talking about the same thing twice. 

Thanks so much for reporting this issue.

**Comment by dennybaa** [comment]
np
