### ISSUE TITLE
[stable/prometheus] prometheus /metrics endpoint results in 404 when server.baseURL and server.prefixURL are configured

### ISSUE THREAD

**Issue by gajus** [helm/charts#7088]
**Version of Helm and Kubernetes**:

```
curiosity~ % helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
curiosity~ % kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.3", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-07-19T23:02:51Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

https://github.com/helm/charts/tree/master/stable/prometheus

**What happened**:

I have installed the prometheus chart using a custom `server.baseURL` and `server.prefixURL`. It appears that the underlying container is not passed all the relevant configuration. As a result, Prometheus is querying wrong endpoint.

<img width="1920" alt="screen shot 2018-08-08 at 17 47 31" src="https://user-images.githubusercontent.com/973543/43851799-9b2523d6-9b33-11e8-8a9d-72fb28697351.png">

**What you expected to happen**:

I expect Prometheus to query `/monitoring/prometheus/metrics` instead of `/metrics`.

**How to reproduce it** (as minimally and precisely as possible):

My configuration:

```yaml
alertmanager:
  persistentVolume:
    size: '32Gi'
server:
  baseURL: https://gajus.com/monitoring/prometheus/
  prefixURL: /monitoring/prometheus
storage:
  local:
    retention: '720h'

```

**Anything else we need to know**:

My guess is that you need to configure `--web.route-prefix`. See https://github.com/prometheus/prometheus/issues/1583#issuecomment-395617142.

**Comment by gajus** [comment]
> My guess is that you need to configure --web.route-prefix. See prometheus/prometheus#1583

Adding `--web.route-prefix` does not fix the issue.

**Comment by gajus** [comment]
The issue remains relevant.

**Comment by cpanato** [comment]
@gajus did you set the `alertmanager.baseURL`/`.prefixURL` values as well?

**Comment by cpanato** [comment]
and I think the prefixUrl should be just `/`

**Comment by gajus** [comment]
> @gajus did you set the alertmanager.baseURL/.prefixURL values as well?

Yes.
