### ISSUE TITLE
[stable/grafana] Grafana setup does not allow to configure baseurl

### ISSUE THREAD

**Issue by gajus** [helm/charts#7089]
**Which chart**:

https://github.com/helm/charts/tree/master/stable/grafana

**What you expected to happen**:

Add ability to configure service URL with a custom path.

It appears that ingress allows to configure path property (`ingress.path`). 

However, there is no way to configure Grafana [`root_url`](http://docs.grafana.org/installation/configuration/#root-url) setting.

**Comment by gajus** [comment]
https://github.com/helm/charts/issues/6264#issuecomment-399363457

**Comment by mabushey** [comment]
I would love if this was added / fixed.
