### ISSUE TITLE
MariaDB with custom configuration extensions

### ISSUE THREAD

**Issue by devurandom** [helm/charts#71]
I have to supply MariaDB with custom configuration extensions/overrides. For example:

``` ini
[mysqld]
max_allowed_packet = 64M
sql_mode=STRICT_ALL_TABLES
ft_stopword_file=/etc/mysql/stopwords.txt
ft_min_word_len=3
ft_boolean_syntax=' |-><()~*:""&^'
innodb_buffer_pool_size=2G
```

How do I do this with the MariaDB Chart?

**Comment by chrislovecnm** [comment]
@devurandom you will need to look at how the chart works, but I think you can have a custom config file.  We would need to have a file as described here https://github.com/bitnami/bitnami-docker-mariadb#configuration-file

@viglesiasce how can you have a dynamic file with charts ... if we have the file then use this?  Maybe init-containers, and a configmap?  Kinda like your Kungfu with Jenkins?

**Comment by viglesiasce** [comment]
@prydonius do you have any tips for @devurandom on how to implement the config file in the chart? 

You can do something similar to the [Jenkins chart](https://github.com/kubernetes/charts/tree/master/incubator/jenkins), wherein I used a [configmap](https://github.com/kubernetes/charts/blob/master/incubator/jenkins/templates/jenkins-master-deployment.yaml#L84) and an [init container to copy the file](https://github.com/kubernetes/charts/blob/master/incubator/jenkins/templates/jenkins-master-deployment.yaml#L29) to /bitnami/mariadb when the container is starting up.

If the image supported a CONFIG_FILE_LOCATION parameter then you could avoid copying it over to the /bitnami/mariadb and just mount it via the config map.

**Comment by prydonius** [comment]
It _should_ be possible to mount a config map directly at `/bitnami/mariadb/conf` (and a PV at `/bitnami/mariadb/data` to not conflict) with the custom configuration, but I ran into a bug in the image where this gets overwritten the first time the container starts up (https://github.com/bitnami/bitnami-docker-mariadb/issues/65). @devurandom do you think the proposed solution there will meet your need?

Once that gets fixed, we can modify the chart to take in a config map option. Do you think the chart should be responsible for creating the config map (like in your Jenkins example), and have people inline the config in values.yaml? Or would it be better to take in the name of an existing config map?

**Comment by devurandom** [comment]
@prydonius Thanks for working on this. Please see my answer to your question over at the other ticket.

**Comment by prydonius** [comment]
Turns out because `/bitnami/mariadb/conf` will contain `my.cnf` and a `my-custom.cnf`, I will need to use an init-container to copy the custom configuration over from a different mount point. Init containers are alpha in 1.3, so we will need to wait for the 1.4 release to add this.

**Comment by chrislovecnm** [comment]
@prydonius - all you. The jetty chart uses configmap + init-container in the same manner. You may be able to do a mount with configmap as well. Does the container image allow for a full replacement of my.cnf?

**Comment by prydonius** [comment]
sorry @chrislovecnm, missed your message! Now that 1.4 is out, I've opted for the configmap + init-container approach. PR in #98 :)

cc @devurandom
