### ISSUE TITLE
Gateway timeout create argument not supported by kiam v2.7

### ISSUE THREAD

**Issue by SteveCaswellTST** [helm/charts#7103]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm client 2.9.1
Helm server 2.9.1
Kubernetes client: 1.10.4
Kubernetes server: 1.9.8

**Which chart**: kiam

**What happened**:
I'm trying to use the helm chart stable/kiam to deploy kiam v2.7. The agent fails to start because the helm chart includes the --gateway-timeout-creation command line argument which is not supported prior to kiam v2.8.

I created a values file named kiam-values.yaml and specified v2.7 for the kiam server image tag:

agent:
  image:
    tag: v2.7
...
server:
  image:
    tag: v2.7

I installed the stable kiam chart using the -f flag to point to the values file.
helm install --name cluster-kiam stable/kiam -f kiam-values.yaml \
    --set=agent.tlsFiles.ca=${AGENTCA} \
    --set=agent.tlsFiles.cert=${AGENTCERT} \
    --set=agent.tlsFiles.key=${AGENTKEY} \
    --set=server.tlsFiles.ca=${SERVERCA} \
    --set=server.tlsFiles.cert=${SERVERCERT} \
    --set=server.tlsFiles.key=${SERVERKEY}

Helm installs the agent and server components. The server starts properly but the agent fails at startup.

```
$ kubectl get pods
NAME                        READY     STATUS             RESTARTS   AGE
cluster-kiam-agent-gqtfr    0/1       CrashLoopBackOff   1          8s
cluster-kiam-agent-ps6d7    0/1       CrashLoopBackOff   1          7s
cluster-kiam-server-5dvk8   0/1       Pending            0          0s

```
Log message from either agent pod is:
```
$ kubectl logs cluster-kiam-agent-gqtfr
agent: error: unknown long flag '--gateway-timeout-creation', try --help

```
**What you expected to happen**:
The agent should start properly. Kiam v2.7 does not support the --gateway-timeout-creation flag. The chart should work with kiam versions <2.8, at least 2.7. According to ihttps://github.com/uswitch/kiam/issues/128 the recommendation is to stick with v2.7 until a 3.x version is released.

I can helm fetch the chart and remove the --gateway-timeout-creation argument from the agent container, but I'd prefer to not need to maintain a local copy jut to work around this issue.

**How to reproduce it** (as minimally and precisely as possible):
1. Follow instructions at https://github.com/uswitch/kiam/blob/master/docs/IAM.md to set up AWS IAM for the cluster master.
2. Follow instructions at https://github.com/uswitch/kiam/blob/master/docs/TLS.md to create certificates.
3. Run the helm install command with the values file to override the default tag.

**Anything else we need to know**:

**Comment by SteveCaswellTST** [comment]
I just realized this flag is also used on the server liveness probe which causes the server pod to crash:

`Liveness probe failed: health: error: unknown long flag '--gateway-timeout-creation', try --help`

Applying any fix for agent would also be appropriate for the server.

**Comment by ewbankkit** [comment]
@SteveCaswellTST Did you try pinning the chart version?

```console
$ helm install --version 1.0.0 stable/kiam
```

**Comment by caussourd** [comment]
@SteveCaswellTST I tried that. It didn't seem to make any difference.

**Comment by hlascelles** [comment]
Agreed, I don't believe this chart could ever have worked with kiam 2.7. The gateway timeout flag has been present in the agent config since day 0: https://github.com/helm/charts/commit/cb9ae834cf88f7a01f9f04a1ecf02a88b1539d6c#diff-d99c68d5a5ccfeaeea50b15437ef9544R82
