### ISSUE TITLE
[incubator/elastic-stack] Hardcoded service address in probes fail chart customization with --name

### ISSUE THREAD

**Issue by caiobegotti** [helm/charts#7114]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug

**Version of Helm and Kubernetes**:

```
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.5", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-02T23:42:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

incubator/elastic-stack

**What happened**:

Installing the chart with `--name elk` make things like the logstash StatefulSet start to falling because it is apparently hardcoded to probe `elasticsearch-client.default.svc.cluster.local` instead of `<chart installation name>-elasticsearch-client.default.svc.cluster.local`

```
[2018-08-09T23:04:35,889][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. 
{:url=>"http://elasticsearch-client.default.svc.cluster.local:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>
"Elasticsearch Unreachable: [http://elasticsearch-client.default.svc.cluster.local:9200/][Manticore::ResolutionFailure]
elasticsearch-client.default.svc.cluster.local: Name or service not known"}
```

What I actually have:

```
$ kubectl get svc
NAME                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
elk-elasticsearch-client      ClusterIP   10.15.240.83    <none>        9200/TCP                     15m
elk-elasticsearch-discovery   ClusterIP   None            <none>        9300/TCP                     15m
elk-kibana                    ClusterIP   10.15.243.67    <none>        443/TCP                      15m
elk-logstash                  ClusterIP   10.15.240.3     <none>        5044/TCP                     15m
```

Because I installed the chart with this:

```
helm install --name elk charts/elastic-stack-*.tgz
```

**What you expected to happen**:

Service address inside the chart should respect the `--name` flag passed to Helm if that ever affects the deployments of the chart.

**How to reproduce it** (as minimally and precisely as possible):

Just install it with a different `--name` and wait for `elk-logstash-0` to fail and collect its container logs to see the message above.

**Anything else we need to know**:

It might be related to the oddness I am seeing in #7109 :-)

**Comment by caio1982** [comment]
That would be the hardcoded setting in ELASTICSEARCH_HOST.

**Comment by skarj** [comment]
It seems connected with  #2492 / #2133 and this PR https://github.com/helm/helm/pull/3252
I really look forward to this feature
It seems that we are forced to change these names manually for subcharts for now as I did here https://github.com/skarj/helm-elastic-stack/blob/master/values.yaml
