### ISSUE TITLE
[incubator/elastick-stack] Wrong label selector in the setup instructions

### ISSUE THREAD

**Issue by caiobegotti** [helm/charts#7115]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug

**Which chart**:

incubator/elastic-stack

**What happened**:

The setup instructions have an export command to do the port-forwarding and check everything is working but it is has the wrong app label selector.

**What you expected to happen**:

The template of the instructions should match the actual app label of the deployment.

**How to reproduce it** (as minimally and precisely as possible):

From the chart:

```
$ export POD_NAME=$(kubectl get pods --namespace default -l "app=elastic-stack,release=<chart --name value or the default>" -o jsonpath="{.items[0].metadata.name}")
```

It should read `app=elasticsearch`, which is the actual app label of the deployments, otherwise you get this when running the export command:

```
error: error executing jsonpath "{.items[0].metadata.name}": array index out of bounds: index 0, length 0
```

**Comment by caio1982** [comment]
Oh! In fact it seems your helper template is using the app label selector of the elastic-stack chart and NOT the kibana label, like `app=kibana,release=[...]`. After fixing this the instruction works.
