### ISSUE TITLE
Testlink does not support nodeSelector

### ISSUE THREAD

**Issue by Nopik** [helm/charts#7122]
**Is this a request for help?**:

No.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature request.

**Which chart**:

Testlink

**What you expected to happen**:

Testlink chart to obey nodeSelector in values.yaml. Currently testlink pods are scheduled randomly, supporting nodeSelector (just like other charts) will allow to place testlink pods according to user needs.

**Comment by jaredallard** [comment]
Hi @Nopik, will #7142 be sufficient?

**Comment by Nopik** [comment]
@jaredallard Yes, it will. I didn't noticed that PR, sorry. Closing this as duplicate.
