### ISSUE TITLE
[stable/verdaccio] Deployment fails to scale past 1 replica

### ISSUE THREAD

**Issue by snypelife** [helm/charts#7133]
**Is this a request for help?**:
Maybe? I believe since this has to do with the fact that Verdaccio is stateful when enabling persistence. In which case, a migration to StatefulSet would be needed? If you'd like I could make an attempt at a contribution.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
I guess I would say bug?

**Version of Helm and Kubernetes**:
Helm: 2.9.1
Kubernetes: 1.10.3

**Which chart**:
[stable/verdaccio]

**What happened**:
Attempted to scale deployment, with persistence enabled, to more than 1 replica. This resulted in an error with the additional replicas being unable to attach to an already attached volume.

**What you expected to happen**:
Successfully deploy additional replicas that share the volume?

**How to reproduce it** (as minimally and precisely as possible):
Deploy Verdaccio with 1 replica and persistence enabled, then scale up to more than 1.

**Anything else we need to know**:
I don't think so.

**Comment by jaredallard** [comment]
Wouldn't there be issues with two instances sharing different volumes? A `StatefulSet` would just provision a new PV, which wouldn't solve the issue I think you're having here which is that you want multiple replicas of the same verdaccio instance to run.
