### ISSUE TITLE
[stable/LAMP] Error 403 when accessing the website 

### ISSUE THREAD

**Issue by andrewcheny** [helm/charts#7135]
**Is this a request for help?**: Yes
Following the instruction to install. After getting the external IP address tried the website and get a 403 error. Forbidden.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
1.10

**Which chart**:
stable/LAMP

**What happened**:
After successful install the website encountered 403 error. Same behavior on AWS and Azure

**What you expected to happen**:
index.html

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by lead4good** [comment]
@andrewcheny if you start the lamp chart with the default configuration, the web directory will be empty which means apache wont find an index.html file and tries to fetch the directory listing of / which is not allowed by default and results in a 403 error. You can fix this by uploading your index.html into the web root or you could try one of the examples.
