### ISSUE TITLE
Default image, for redmine

### ISSUE THREAD

**Issue by flah00** [helm/charts#714]
I was going to add postgres as an optional sub-chart, for redmine. And then I looked at the bitnami redmine Dockerfile. It seems very well suited to a mariadb/mysql install. It doesn't support the options available to the community though. 

I have an existing redmine install, which uses postgres. I'd like to move my redmine into k8s, using helm, but right now I'm stuck. I'm happy to add postgres to the redmine chart... But how do we work around the default image's sole support for maria? As a user, I would expect the default image, for a project, to support as many of the project's options as it could. 

To that end, we can...

* [Update](https://github.com/bitnami/bitnami-docker-redmine/issues/25) bitnami image
    * This image is slightly disadvantaged, as it explicitly only supports env vars for Maria
* Switch to a different image, perhaps the [official](https://hub.docker.com/_/redmine/) one?
    * The official does come with some niceties, like agnostic db support, secret generation, rake integration (migrations), etc
* Leave an alternative image name in the comments, for postgres/sqlite3 users
    * This would merely be a quick and dirty compromise, IMHO
* Other alternatives?

**Comment by pierreozoux** [comment]
related to #220
