### ISSUE TITLE
[stable/influxdb] Update to influxdb 1.6.1

### ISSUE THREAD

**Issue by naseemkullah** [helm/charts#7143]
They did it:
https://github.com/influxdata/tick-charts/tree/master/influxdb

**Comment by davidkarlsen** [comment]
Fancy doing a PR?

**Comment by naseemkullah** [comment]
I want to but I need to get around to signing the cNCf thing

**Comment by naseemkullah** [comment]
I've emailed the CNCF with a question regarding the agreement  ""5. You represent that each of Your Contributions is Your original creation""
I'm not sure if bumping the image version is considered as My original creation. Still waiting on a response form the CNCF.

**Comment by naseemkullah** [comment]
I've got a responde from Mr. Dan Kohn saying it was fine. So I will be going ahead with the PR.
