### ISSUE TITLE
[incubator/elasticsearch] Add updateStrategy to Stateful sets

### ISSUE THREAD

**Issue by maver1ck** [helm/charts#7148]
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm: 2.9.1
K8S: 1.10.6

**Which chart**:
incubator/elasticsearch

**What happened**:

By default Stateful sets created by this chart have updateStrategy: onDelete

**What you expected to happen**:

I'd like to configure updateStrategy via values.yaml

**Comment by davidkarlsen** [comment]
Would you like to create a PR for it?

**Comment by maver1ck** [comment]
ping @davidkarlsen
