### ISSUE TITLE
Mongodb version 3.4

### ISSUE THREAD

**Issue by pierreozoux** [helm/charts#7151]
RocketChat depends on the official helm mongoDB chart.
RocketChat requires MongoDB version 3.4.
The official heml mongodb chart depends on bitnami chart that doesn't provide 3.4

In your opinion, what would be the best way to solve the issue?

Thanks for your feedback!

**Comment by gboston** [comment]
Hi, you can use the mongodb chart with the a bitnami/mongodb:3.4.10-r0 image.

**Comment by pierreozoux** [comment]
@gboston does it exist? I don't see it [here](https://hub.docker.com/r/bitnami/mongodb/tags/)

**Comment by gboston** [comment]
it's still available don't know why it's not listed.

**Comment by pierreozoux** [comment]
I didn't manage to docker pull it :/
