### ISSUE TITLE
[stable/jenkins] custom labels on the agent

### ISSUE THREAD

**Issue by techlunacy** [helm/charts#7166]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:
all

**Which chart**:
[stable/jenkins]

**What happened**:
cannot add custom labels to jenkins agent in the values file

**What you expected to happen**:
add custom labels to the agent in the values file

**How to reproduce it** (as minimally and precisely as possible):
try to add custom labels in the values file

**Anything else we need to know**:

**Comment by davidkarlsen** [comment]
Fancy doing a PR?

**Comment by techlunacy** [comment]
@davidkarlsen think i might be able to get it done

**Comment by techlunacy** [comment]
[pull request](https://github.com/helm/charts/pull/7167/)
