### ISSUE TITLE
[stable/fluentd-elasticsearch] fluentd-elasticsearch:v.2.2.0 not formatting JSON logs 

### ISSUE THREAD

**Issue by grebois** [helm/charts#7168]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

```
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:50:44Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/fluentd-elasticsearch

**What happened**:

gcr.io/google-containers/fluentd-elasticsearch:v.2.2.0 is not mapping json input

**What you expected to happen**:

Format json input in searchable fields

**How to reproduce it** (as minimally and precisely as possible):

Install chart as is
Log any json input
Check elasticsearch for the log entry 

**Anything else we need to know**:

Works fine when rolling back to gcr.io/google-containers/fluentd-elasticsearch:v.2.1.0

**Comment by grebois** [comment]
@monotek you can test this issue with standard nginx logs https://github.com/kubernetes/ingress-nginx/issues/1664

**Comment by monotek** [comment]
I can confirm the issue. 
Kibanas json log is not detected as json.

**Comment by monotek** [comment]
The problem is in the fluent-plugin-kubernetes_metadata_filter plugin. I've created a bugreport fluent-plugin-kubernetes_metadata_filter.

Pull request for fixed image is available too: https://github.com/kubernetes/kubernetes/pull/67544

**Comment by monotek** [comment]
Will be fixed with: https://github.com/helm/charts/pull/7307

**Comment by grebois** [comment]
@monotek great!!! thanks for the heads up.

**Comment by grebois** [comment]
@monotek had to went back to v.2.1.0, v2.3.1 also shows problem with formatting, cannot provide any output now, but just wanted to let you know.

**Comment by monotek** [comment]
I know. See: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/145#issuecomment-413888694
