### ISSUE TITLE
[stable/vault-operator] default value for service account name doesn't match readme

### ISSUE THREAD

**Issue by dcherman** [helm/charts#7185]
**Version of Helm and Kubernetes**:

Helm: 2.9.1
Kubernetes: 1.10.3

**Which chart**:

stable/vault-operator

**What happened**:

Installation fails by default with the error `Error: release vault-operator failed: ServiceAccount "" is invalid: metadata.name: Required value: name or generateName is required`

**What you expected to happen**:

The install to succeed

**How to reproduce it** (as minimally and precisely as possible):

`helm upgrade --install vault-operator stable/vault-operator` on a cluster with no release called `vault-operator` installed

**Anything else we need to know**:

It looks like the default value for `serviceAccount.name` is blank in `values.yaml` whereas the README.md  specifies a define value of `vault-operator-sa`.  I'm not sure which is correct whether it was intended to have a default, or require the user to provide one.

**Comment by cpick** [comment]
This is still valid.
