### ISSUE TITLE
stable/rabbitmq fails to start on tectonic 1.9.6

### ISSUE THREAD

**Issue by kimbad** [helm/charts#7192]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Version of Helm and Kubernetes**: 2.9.1 and 1.9.6 (tectonic)

**Which chart**:stable/rabbitmq version: 2.1.2

**What happened**:
Pod continually fails to start with error
bash: line 1: /opt/bitnami/rabbitmq/var/lib/rabbitmq/.erlang.cookie: Permission denied

**What you expected to happen**:
Pod to start successfully

**How to reproduce it** (as minimally and precisely as possible):
Start a vanilla Tectonic 1.9.6 cluster on AWS and then 
`helm init`
`helm install stable/rabbitmq`

**Anything else we need to know**:
I also tried this on a KOPS 1.9.6 cluster and the deployment was successful. This may suggest it is a Tectonic K8S issue rather than a chart issue.

**Comment by houstondapaz** [comment]
Any update?
