### ISSUE TITLE
incubator/elasticsearch needs enough flexibility in the chart to allow snapshotting

### ISSUE THREAD

**Issue by yokhahn** [helm/charts#7204]
In order to have a production elasticsearch run, I believe backups are probably a requirement.
If I understand correctly this is usually done with the snapshot capability (https://www.elastic.co/guide/en/elasticsearch/reference/6.3/modules-snapshots.html).

By default there is a filesystem snapshot, but there is nothing in the chart to allow a separate persistent volume to be allocated purely for backup.

Alternatively, there are snapshot/restore plugins which can use s3, hdfs, and other cloud specific APIs.
But, in order for that to work, the chart must somehow shim in a run of bin/elasticsearch-plugin before starting up (as described for s3 at: https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3.html).

**Comment by davidkarlsen** [comment]
@yokhahn You could just build your own image extending the official one and install a plugin and use that in the chart values.yaml?

**Comment by yokhahn** [comment]
That could possibly work as a work around,  I just thought folks might want to not depend on a custom image.

**Comment by yokhahn** [comment]
Also, mounting another volume for the file-system snapshot is really something that needs to be done in the chart.  Perhaps another set of persistent storage something like:
snapshot.persistence.enabled
snapshot.persistence.name
snapshot.persistence.size
.. etc

And just mount in one more volume.

**Comment by rewt** [comment]
I'm interested in this functionality for azure and running into same issue around keystore values.

**Comment by MathieuMailhos** [comment]
I would love to have this feature as well

**Comment by roonie007** [comment]
@davidkarlsen still no news about this absolutely needed feature ??
