### ISSUE TITLE
[stable/ark] Restic support

### ISSUE THREAD

**Issue by chavezmx** [helm/charts#7223]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: k8s 1.9.1, helm 2.8.2

**Which chart**: ark

**Feature**: I see the current chart don't have the proper template for creating the demonset for restic, it will be good to enable the creation of backups from pv other than snapshots and store them on buckets.

Here are some references: 
https://github.com/heptio/ark/blob/master/examples/gcp/20-restic-daemonset.yaml
https://github.com/heptio/ark/blob/master/docs/restic.md

**Comment by tarioch** [comment]
Would like that one as well. Works fine with using the linked daemonset above but adjusting the serviceaccount to "ark-server"
