### ISSUE TITLE
[stable/mssql-linux] Missing service annotations

### ISSUE THREAD

**Issue by TobiasWenzel** [helm/charts#7227]
**Is this a request for help?**: No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Depends on the perspective. From my POV, it's a bug report.

**Version of Helm and Kubernetes**:
Helm: 2.9.1
Kubernetes: 1.10.3

**Which chart**:
mssql-linux-0.5.0

**What happened**:
When I install the mssql-linux chart I am not able to specify a [parameter](https://github.com/helm/charts/tree/master/stable/mssql-linux#values) which sets annotations for a service. I need this in order to make MS SQL Server accessible from outside my Kubernetes cluster which uses the [MetalLB load balancer](https://metallb.universe.tf/).
This requires to have
```
  annotations:
    metallb.universe.tf/allow-shared-ip: myServiceSet
```
in the metadata of the service definition.

**What you expected to happen**:
A configuration parameter `service.annotations` should be added to the chart, so that it's possible to do

`helm install stable/mssql-linux --set service.type=LoadBalancer --set service.annotations."metallb\.universe\.tf/allow-shared-ip"=myServiceSet`

This should add the annotation

`metallb.universe.tf/allow-shared-ip: myServiceSet`

in the mssql-linux service.

This works e.g. in [Grafana](https://github.com/helm/charts/tree/master/stable/grafana#configuration), [Prometheus](https://github.com/helm/charts/tree/master/stable/prometheus#configuration) and since recently also in [MongoDB](https://github.com/helm/charts/tree/master/stable/mongodb#configuration) (see also [that issue](https://github.com/helm/charts/issues/6941) which is exactly the same one as this issue).

**How to reproduce it** (as minimally and precisely as possible):
`helm install stable/mssql-linux --set acceptEula.value=Y --set service.type=LoadBalancer --set service.annotations."metallb\.universe\.tf/allow-shared-ip"=myServiceSet`

--> does NOT add the annotation

**Comment by mattjmcnaughton** [comment]
I'd be happy to fix this for you :) PR on its way!

**Comment by TobiasWenzel** [comment]
@mattjmcnaughton Bringing that up again, as it would be a pity if that issue was closed only because your PR didn't get approved...
