### ISSUE TITLE
[stable/redis] Option for slave to have persistent volume

### ISSUE THREAD

**Issue by naseemkullah** [helm/charts#7264]
**Is this a request for help?**: I guess it is

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

I'd like to add persistence storage to the slave, as I would like to mount an nfs volume to the slave to add a backup cronjob to backup dump.rdb

I do not want to do this with master, as the nfs SC is a bit shakey, i've had a lot of stability using just the default ssd SC with the master, and dont want to mess with it. I will do my backups of dump.rdb by backing up the slave's. But I need it to have RWX on the data dir so that the cronJob can access it to backup and send to my object store.

**Version of Helm and Kubernetes**: latest, greatest

**Which chart**: stable/redis

**What happened**: no option to add persistence to slave

**What you expected to happen**: nothing

**How to reproduce it** (as minimally and precisely as possible): n/a

**Anything else we need to know**:

**Comment by juan131** [comment]
Hi @naseemkullah 

The original idea when designing this Helm Chart was to include persistence exclusively on master pods so the slave pods are "read-only".

Maybe you can create a CronJob with a Redis client which creates the dump and stores it on a different PV. Therefore, you don't need to have NFS on the master and you don't need to change the configuration that gave you a lot of stability.

**Comment by naseemkullah** [comment]
Thanks @juan131, that sounds like a good alternative.
