### ISSUE TITLE
[stable/fluentd-elasticsearch] starts from the top of the file on pod restart

### ISSUE THREAD

**Issue by aba182** [helm/charts#7271]
**Is this a request for help?**: YES

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

**Which chart**:
[stable/fluentd-elasticsearch]

**What happened**:
After I restart the fluentd-elasticsearch pods they go back to the beginning of the cluster's logs. I have a elasticsearch-curator that clears the data older than 7 days. After I restart the fluentd pods data from 20 days ago starts back populating until it gets back to current. 

I have tried to change a few things like changing `read_from_head` to true everywhere but this didn't seem to help. 

I can see the pos_file being mounted from the host server so the daemonset should be able to pickup from the pos_file.

**What you expected to happen**:

I expect the pos_file to work as expected. 

**How to reproduce it** (as minimally and precisely as possible):

I installed from defaults, delete old indexes, and then restart fluentd and it starts from top of log files. 

**Anything else we need to know**:

**Comment by aba182** [comment]
@monotek Any chance you could help me with this issue?

**Comment by monotek** [comment]
This should already be fixed by: https://github.com/helm/charts/pull/6696 which was merged with: https://github.com/helm/charts/pull/6925

**Comment by aba182** [comment]
Thanks!
