### ISSUE TITLE
[incubator/couchdb] Liveness probe fails, resulting in endless CrashLoopBackOff

### ISSUE THREAD

**Issue by robertgartman** [helm/charts#7278]
**Is this a request for help?**:
No
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:

> $ helm version
> Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
> 
> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
incubator/couchdb
commit b520660
**What happened**:
Chart does not form a CouchDB cluster. Pods keep ending up in CrashLoopBackOff status.

**What you expected to happen**:
At minimum - healthy pods

**How to reproduce it** (as minimally and precisely as possible):
On a 3-node cluster, run:
`helm install --name my-release --set image.tag=2.2  incubator/couchdb`

The issue is present also with the default CouchDB image 2.1.1.

**Anything else we need to know**:
Since Liveness probes defaults to the pod's ip and CouchDb by default binds 5984 to 127.0.0.1 there won't be any success. The K8S scheduler will reap the CouchDB and a `kubectl describe pods my-release-couchdb-0`will show:
>     Last State:     Terminated
>       Reason:       Error
>       Exit Code:    143

The Chart is using the CouchDB image config, which has:
```
{
  ...
  "chttpd": {
    "bind_address": "127.0.0.1",
  ...}
}
```
The chart is successful when launched like this:
`helm install --name my-release --set image.tag=2.2,couchdbConfig.chttpd.bind_address=0.0.0.0  incubator/couchdb`

Suggestion: update the documentation with a hint about `couchdbConfig.chttpd.bind_address=0.0.0.0`

**Comment by kocolosk** [comment]
Hi @robertgartman thanks for the report. I'm a little puzzled as I thought the official images override the `bind_address` to `any`:

https://github.com/apache/couchdb-docker/blob/master/2.2.0/Dockerfile#L144

**Comment by kocolosk** [comment]
Ah but obviously we override that .ini file because we have a `ConfigMap` mounted to that directory, so this just feels like we never completed the other half of the job.

This is likely the same problem from #6588 so will try to address it in that open PR.

**Comment by robertgartman** [comment]
Good catch!

In between your comments above I just reconfirmed the behaviour. To verify I've been running on a local checkout of the repo, where I just modified the statefulset.yaml setting the livenessProbe 'failureThreshold: 100'. This simply gives me the time to run things before container is reaped.

So running from within the local repo:

```
helm install --name my-release --set image.tag=2.2 .
kubectl exec my-release-couchdb-0 -c couchdb -- apt-get update -y
<output dropped>
kubectl exec my-release-couchdb-0 -c couchdb -- apt-get install net-tools
<output dropped>
kubectl exec my-release-couchdb-0 -c couchdb -- netstat -l
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 localhost:5984          0.0.0.0:*               LISTEN
tcp        0      0 localhost:5986          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN
tcp6       0      0 [::]:4369               [::]:*                  LISTEN
```

Note `localhost:5984`

And repeating with
```
helm install --name my-release --set image.tag=2.2,couchdbConfig.chttpd.bind_address=0.0.0.0 .
<as above>
kubectl exec my-release-couchdb-0 -c couchdb -- netstat -l        
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 localhost:5986          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:5984            0.0.0.0:*               LISTEN
tcp6       0      0 [::]:4369               [::]:*                  LISTEN
```

Keep up the great work!

**Comment by jonathan-r-young** [comment]
The solution would be to add values parameters to set the probe parameters , since they default 
 Liveness:   http-get http://:5984/ delay=0s timeout=1s period=10s #success=1 #failure=3
 Readiness:  http-get http://:5984/_up delay=0s timeout=1s period=10s #success=1 #failure=3
