### ISSUE TITLE
[nfs-client-provisioner] document inconsistencies

### ISSUE THREAD

**Issue by gengen1988** [helm/charts#7284]
**Is this a request for help?**:
No, just a notice

---

**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**Version of Helm and Kubernetes**:
- helm 2.10.0
- kubernetes 1.11.1

**Which chart**:
stable/nfs-client-provisioner

**What happened**:
Set the value `storageclass.defaultClass` to true as documents, but nothing happend

**What you expected to happen**:
The created storageclass `nfs-client` should has the annotation `storageclass.kubernetes.io/is-default-class: "true"` when set `storageclass.defaultClass` to true

**How to reproduce it**:
Run `helm install stable/nfs-client-provisioner --set storageclass.defaultClass=true`. Then watch the annotations in created sc.

**Anything else we need to know**:
In templates, `storageClass` was used, which is `storageclass` in documents. This affects every configuration under `storageclass`

**Comment by MaxDiOrio** [comment]
Just noticed this too.  Documentation is lower case and it didn't work.  Changed it to camel case, redeployed, and the values were taken properly.

**Comment by B3DTech** [comment]
Has this been updated in the documentation?
