### ISSUE TITLE
[stable/nginx-ingress] Unable to set false as a value in controller.extraArgs

### ISSUE THREAD

**Issue by jmcnevin** [helm/charts#7291]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm 2.9.0, Kubernetes 1.9.9

**Which chart**: nginx-ingress

**What happened**: 
Attempted to set `controller.extraArgs.enable-ssl-chain-completion=false`, which starts `nginx-ingress-controller` with an argument of just `--enable-ssl-chain-completion`.

**What you expected to happen**:
The argument should be set as `--enable-ssl-chain-completion=false`.  This feature is enabled by default.

**How to reproduce it** (as minimally and precisely as possible):
`helm install stable/nginx-ingress --set "controller.extraArgs.enable-ssl-chain-completion=false"`

**Anything else we need to know**:
I was able to get this working by passing "0" instead of "false", but there should probably be a note about that somewhere.

**Comment by mattjmcnaughton** [comment]
Mhmm, I see the problem :) Good catch! putting out a pr to fix rn!

**Comment by jmcnevin** [comment]
I can't test this at the moment, but I did notice that I pasted my command wrong, using `--string-string` rather than `--set`.   That was something else I was trying during troubleshooting that may be another way around this.  Can you reproduce the issue with just `--set`?  I will update the ticket.

**Comment by lucasmundim** [comment]
It seems that the problem is with the **if** statement evaluating to false on [controller-daemonset.yaml](https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-daemonset.yaml#L75)
 and [controller-deployment.yaml](https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-deployment.yaml#L77).

```
          {{- range $key, $value := .Values.controller.extraArgs }}
            {{- if $value }}
            - --{{ $key }}={{ $value }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
          {{- end }}
```

This logic tries to support both --some-arg and --some-arg-with-value=some-value, but it does not support --some-arg-with-false-value=false or --some-arg-with-zero-value=0 or --some-arg-with-empty-string-value=""

I was not able to get this working by passing "0" instead of "false" as @jmcnevin mentioned.

```
$ helm install stable/nginx-ingress --set "controller.extraArgs.enable-ssl-chain-completion=0"
```

```
$ kubectl exec -it -n ingress ingress-nginx-nginx-ingress-controller-gm526 bash
www-data@ingress-nginx-nginx-ingress-controller-gm526:/etc/nginx$ ps aux|more
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
www-data     1  0.1  0.0   2128   684 ?        Ss   22:35   0:00 /usr/bin/dumb-init /bin/bash /entrypoint.sh /nginx-ingress-controller --default-backend-service=ingress
/ingress-nginx-nginx-ingress-default-backend --election-id=ingress-controller-leader --ingress-class=nginx --configmap=ingress/ingress-nginx-nginx-ingress-controller --enable-ssl-chain-completion
www-data     8  0.0  0.0   3668  2764 ?        Ss   22:35   0:00 /bin/bash /entrypoint.sh /nginx-ingress-controller --default-backend-service=ingress/ingress-nginx-ngin
x-ingress-default-backend --election-id=ingress-controller-leader --ingress-class=nginx --configmap=ingress/ingress-nginx-nginx-ingress-controller --enable-ssl-chain-completion
www-data     9  5.0  0.9 136696 38084 ?        Sl   22:35   0:00 /nginx-ingress-controller --default-backend-service=ingress/ingress-nginx-nginx-ingress-default-backend
 --election-id=ingress-controller-leader --ingress-class=nginx --configmap=ingress/ingress-nginx-nginx-ingress-controller --enable-ssl-chain-completion
www-data    36  1.0  1.2 168344 49536 ?        S    22:35   0:00 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
www-data    66  0.0  1.1 436132 44892 ?        Sl   22:35   0:00 nginx: worker process
www-data    67  0.0  1.1 436132 44892 ?        Sl   22:35   0:00 nginx: worker process
www-data    68  0.0  1.1 436132 44892 ?        Sl   22:35   0:00 nginx: worker process
www-data    69  0.1  1.1 436132 44892 ?        Sl   22:35   0:00 nginx: worker process
www-data   198  0.5  0.0   3800  3224 pts/0    Ss   22:35   0:00 bash
www-data   204  0.0  0.0  11616  2788 pts/0    R+   22:35   0:00 ps aux
www-data   205  0.0  0.0   2484   900 pts/0    S+   22:35   0:00 more
```

**Comment by lucasmundim** [comment]
I got it working using _--set-string_.

```
helm install stable/nginx-ingress --set-string controller.extraArgs.enable-ssl-chain-completion=false
```
