### ISSUE TITLE
[stable/minio] Cannot upgrade deployed chart due to "make-bucket-job" already exists

### ISSUE THREAD

**Issue by andig** [helm/charts#7313]
**Is this a request for help?**: no (solved by deleting ressources directly in kubernetes)

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug

**Version of Helm and Kubernetes**:

    Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
    Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

**Which chart**:

stable/minio

**What happened**:

Upgrading minio delpoyment fails:

    ❯ helm upgrade -f minio-values.yml minio-cache stable/minio
    Error: UPGRADE FAILED: jobs.batch "minio-cache-make-bucket-job" already exists

**What you expected to happen**:

Upgrade executed 

**How to reproduce it** (as minimally and precisely as possible):

Deploy stable/minio, then upgrade using a new `minio-values.yml`:

    defaultBucket:
      enabled: true
      ## If enabled, must be a string with length > 0
      name: gitlab-cache
      ## Can be one of none|download|upload|public
      policy: none
      ## Purge if bucket exists already
      purge: false

**Anything else we need to know**:

Initial deployment was not using `minio-values.yml`.

**Comment by andig** [comment]
Update: it seems that even *delete* doesn't get rid of the job:

	~/htdocs/gitlab-runner
	❯ helm delete --purge minio-cache
	release "minio-cache" deleted

	~/htdocs/gitlab-runner
	❯ helm ls --all minio-cache

	~/htdocs/gitlab-runner
	❯ helm install -f minio-values.yml --name minio-cache stable/minio

	Error: jobs.batch "minio-cache-make-bucket-job" already exists

**Comment by andig** [comment]
More weirdness. Deployment is happy in the kubeui but fails inconsistently on the command line:

	❯ helm install -f minio-values.yml --name minio-cache stable/minio
	Error: a release named minio-cache already exists.

	❯ helm ls --all minio-cache
	NAME            REVISION        UPDATED                         STATUS  CHART           APP VERSION                     NAMESPACE
	minio-cache     1               Thu Aug 23 15:44:40 2018        FAILED  minio-1.6.2     RELEASE.2018-07-10T01-42-11Z    default

	❯ helm upgrade -f minio-values.yml minio-cache stable/minio
	Error: UPGRADE FAILED: "minio-cache" has no deployed releases

Please feel free to close if this is off-topic or more a kubernetes than help problem.

**Comment by dokipen** [comment]
The delete-job pod spits out this error during deletion: `Error from server (Forbidden): jobs.batch is forbidden: User "system:serviceaccount:default:default" cannot list jobs.batch in the namespace "default"`
