### ISSUE TITLE
Grafana: setting datasource doesn't work (missing 'database' option).

### ISSUE THREAD

**Issue by ghost** [helm/charts#732]
Chart for Grafana allows adding datasource, however it does not support all of datasource configuration options (specification of Http Auth, database, user, password).

Database field is required for proper configuration of Data Source in Grafana (see img below) and it should be possible to add it when using 'set_datasource' option in Grafana chart.

![image](https://cloud.githubusercontent.com/assets/6523391/23358322/cfdebcb4-fce1-11e6-9a19-ce2c56c04a0c.png)

It seems like it should be handled here: https://github.com/kubernetes/charts/blob/master/stable/grafana/templates/job.yaml#L32

**Comment by seanknox** [comment]
Hi @mkuculyma, is this still an issue?
