### ISSUE TITLE
stable/jenkins: ability to specify path for ingress

### ISSUE THREAD

**Issue by f-ld** [helm/charts#7334]
**Is this a request for help?**: No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Can be seen as both

**Version of Helm and Kubernetes**: Unrelated, but kubernetes 1.10 and helm 2.9.1 if you think it makes a difference

**Which chart**: stable/jenkins

**What happened**: Ingress path not configurable

**What you expected to happen**: I would like to be able to access jenkins via `mydomain.com/jenkins` (i.e. share the domain with other services) and not specifically via a dedicated domain like `jenkins.mydomain.com`. This can be done having in values the ability to specify a path on the ingress controller to reach jenkins. This should go in this file `https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-ingress.yaml` and would set `spec.rules[].http.paths[].path` (see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#httpingresspath-v1beta1-extensions) to `/jenkins` for example

**How to reproduce it** : assuming you have a kubernetes cluster and helm all configured, get a copy of https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml and set some value like `mydomain.com` for Master.HostName`. Then run `helm install --name jenkins -f values.yaml stable/jenkins --dry-run --debug` and check the ingress configuration -> there is no `/path` specified (even if `Master.JenkinsUriPrefix` has a value in the values.yaml file).

**Anything else we need to know**: No

**Comment by mrshoker** [comment]
I am also looking for a solution to configure the 'Path' parameter. Found any solutions?

**Comment by f-ld** [comment]
No, so far I postponed the migration of our jenkins to k8s.
When it will become high priority for us, if still not fixed, I will fork this repo, do the change and create a PR.

**Comment by f-ld** [comment]
@mrshoker : please have a look to the PR I created.
You can use it locally checking out the branch I did (from my fork) and locally pointing helm to that directory.

For example instead of installing jenkins from the official repo:
```
helm install --name jenkins --namespace=yournamespace -f helm-jenkins.values.yaml stable/jenkins --dry-run --debug
```
until the PR gets merged or this gets fixed somehow, you can try:
```
helm install --name jenkins --namespace=yournamespace -f helm-jenkins.values.yaml ~/path/to/where/you/checkd/out/charts/stable/jenkins --dry-run --debug
```
