### ISSUE TITLE
Chart Contribution Does Not Allow Install/Upgrade/Lint Arguments

### ISSUE THREAD

**Issue by mikeln** [helm/charts#734]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): contribute, contribution, default

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Helm version** (use helm version): 
Client: &version.Version{SemVer:"v2.2.0", GitCommit:"fc315ab59850ddd1b9b4959c89ef008fef5cdf89", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.0", GitCommit:"fc315ab59850ddd1b9b4959c89ef008fef5cdf89", GitTreeState:"clean"}

**Description**:
The current submission process requires a chart pass `helm lint .` and `helm install .`, i.e. the default `values.yaml` must contain all variables.

**Reasons**:
There are circumstances where the chart may not be complete without command line value setting via `--set` or perhaps `--values`.   This may be by design for various reasons.  (security issues for one).  

A Chart submission should be able to specify the correct example command line for evaluation.

Also, currently `helm lint` does not support some arguments and a separate issue has been opened for that: https://github.com/kubernetes/helm/issues/2036 .

**Comment by seanknox** [comment]
Hi @mikeln, sorry for the very slow response to your issue. I'm not quite sure I understand the use case behind your feature request. Can you elaborate?

**Comment by mikeln** [comment]
For example, if you want to minimize exposure to certain values, like setting a password value in the app.  You don't want to put that value in the values.yaml.  Also, to avoid issues later (like the old MySQL default password that many people didn't change), you may not want to even provide a default value.   Currently the most minimally exposed way to do that, is to require that value be passed into the chart as a command line argument.  

However, that type of chart could not be submitted to kubernetes/charts since the current process requires that the chart passes lint/etc using only the values.yaml file.   You can not specify lint,up command line arguments when submitting the chart to this repository.

**Comment by mattfarina** [comment]
@mikeln would the `--dry-run` flag on commands like `helm install` work instead of linting for this case?

**Comment by mikeln** [comment]
Hey @mattfarina, this issue isn't the lint'ing.   The issue is that to submit a chart to this repository, the steps quoted above are run for CI.   There is no provision in the CI pipeline for this repo to allow Chart values to be set on the command line, i.e. All the values must be submitted in the `values.yaml`.

The case is where we try to minimize exposure of passwords in the chart template.  The absolute minimum exposure is achieved by not including bogus password values in `value.yaml`, but by supplying them on the command line via `--set` or `--values`.   

So the other argument is, why not just supply bogus password values in the `values.yaml` file so it can get by CI?  The reason we are averse to that is, when someone picks up the chart to use, they can forget to remove or set those values.  To ensure the user doesn't forget, we would rather not include them there, and require them on the command line.  In this way, the chart will fail to install due to the missing values...a very brute force way to ensure the chart is being set up correctly.

**Comment by unguiculus** [comment]
It's now possible to specify custom values for CI.

See https://github.com/kubernetes/charts/blob/master/test/README.md#providing-custom-test-values
