### ISSUE TITLE
[stable/jenkins] Jenkins Helm Chart : Not able to change slave memory and cpu limits - minikube

### ISSUE THREAD

**Issue by mailtoraja18** [helm/charts#7358]
I tried the below and several other including changing the values.yaml. The limits dont seems to change.They always stick at 200m/256Mi.
Please help me change the slave pod cpu and memory limits. Thanks

**Agent specification [Kubernetes Pod Template] (jenkins-jenkins-slave): **
* [jnlp] jenkins/jnlp-slave:3.10-1(resourceRequestCpu: 200m, resourceRequestMemory: 256Mi, resourceLimitCpu: 200m, resourceLimitMemory: 256Mi)

`helm install --name jenkins --set Agent.resources.limits.cpu=2000m,Agent.resources.limits.memory=2048Mi -f jenkins-values.yaml stable/jenkins`

Edit 09/01 : tried again few times , this time the pod limits stick at 2 CPU and 2 GB and do not change when I fix the agent values in the values.xml

![image](https://user-images.githubusercontent.com/1549921/44945633-8fed8e00-adbb-11e8-9cc0-46787225895c.png)

[files.zip](https://github.com/helm/charts/files/2342332/files.zip)

**Comment by moyuanhui** [comment]
@mailtoraja18 Hi,do you have this problem 
![image](https://user-images.githubusercontent.com/18112282/44639504-e428f480-a9ee-11e8-868e-ce6719ba2431.png)
![image](https://user-images.githubusercontent.com/18112282/44639513-eee38980-a9ee-11e8-93a2-be33c3fc8bfe.png)

**Comment by mailtoraja18** [comment]
nope.

**Comment by r96725046** [comment]
You have to clean your jenkins home and reinstall with value.xml
If you wouldn't like to clean the data, you can change the values in "configure system" section 
![image](https://user-images.githubusercontent.com/42165511/46266414-9cebd180-c561-11e8-8763-96c0a85a8f35.png)

**Comment by dipeshm01** [comment]
I would like to know what was the solution of this issue, because apparently I also have this issue and no idea how to fix this...
