### ISSUE TITLE
MySql initializationFiles issue

### ISSUE THREAD

**Issue by farhan-sauce** [helm/charts#7366]
**Is this a request for help?**:
Yes,
---

**Version of Helm and Kubernetes**:
kubernetes 1.10.3
helm 2.9.1

**Which chart**:
mysql

**What happened**:
I am trying to use `sql` file in `initializationFiles` property, but it doesn't import the query from `sql` file.

**What you expected to happen**:
SQL file should work fine.

**How to reproduce it** (as minimally and precisely as possible):
Here I am attaching 

- `mysql-values.yaml` file
```
persistence:
  enabled: false
mysqlRootPassword: password
mysqlUser: test
mysqlPassword: password
mysqlDatabase: db
initializationFiles:
  - schema.sql
```

- `schema.sql` file
```
CREATE DATABASE IF NOT EXISTS second DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
```

**Anything else we need to know**:
Let me know if I am doing something wrong.

**Comment by kalexmills** [comment]
I am also seeing this issue. The files are being copied to the correct directory (docker-entrypoint-initdb.d) but they appear not to be run, and I am seeing nothing in the container logs.

**Comment by Dhananjay-J-P** [comment]
facing same issue. Not able to pass file using InitializationFiles argument

**Comment by Dhananjay-J-P** [comment]
@farhan-sauce have u been able to resolve this issue. I am passing below in answers.yaml, yet I cant see that file in container 

`initializationFiles:
  first-db.sql: |-
    CREATE DATABASE IF NOT EXISTS first DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;`

**Comment by bcouetil** [comment]
For anyone interesting, there is a (lost) MR whose code let me use SQL files, which are put in the configmap by the Helm chart : https://github.com/helm/charts/pull/10215
