### ISSUE TITLE
External-dns not taking PowerDNS answers

### ISSUE THREAD

**Issue by MaxDiOrio** [helm/charts#7397]
HELM  v2.9.1-rancher1
K8S.  v1.11.1-rancher1-1

external-dns

There are no parameters for powerDNS.  Missing are pdns-api-key and pdns-server

Without these two variables, the container won't come up.

**Comment by davidkarlsen** [comment]
Would you like to do a PR?

**Comment by MaxDiOrio** [comment]
It's not really in my time budget to do it.  I've deployed it manually in the mean time, and still running into permissions issues with the service account.
