### ISSUE TITLE
zookeeper chart error deploying to kubernetes 1.4

### ISSUE THREAD

**Issue by mcandre** [helm/charts#741]
Trace:

```console
$ helm install ./zookeeper/
Error: apiVersion "policy/v1beta1" in zookeeper/templates/pdb.yaml is not available
```

Is kubes 1.4.5 sufficient, or do I need a higher patch version in order to unlock the "v1beta" stuff?

**Comment by kow3ns** [comment]
You will need at least 1.5. StatefulSet is not supported until this version.

**Comment by lachie83** [comment]
This is mentioned in the chart prereq - https://github.com/kubernetes/charts/tree/master/incubator/zookeeper#zookeeper-helm-chart
