### ISSUE TITLE
Error: couldn't connect to server Caused By Connection Refused

### ISSUE THREAD

**Issue by antonyRoberts** [helm/charts#7419]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Version of Helm and Kubernetes**:
KubeCtl version 1.10.3 
Helm ClientVersion 2.10, ServerVersion 2.10
**Which chart**:
MongoDB

**What happened**:
Liveness Probe fails with Connection failed. and pod dies

**What you expected to happen**:
There not to be a connection issue.

**How to reproduce it** (as minimally and precisely as possible):
Install helm MongoDB on fresh install of Docker for Windows

**Anything else we need to know**:
Using Docker for Windows with Kubernetes

The Logs are below

`λ kubectl describe pod my-release-mongodb-67d97864bb-vxvlp
Name:           my-release-mongodb-67d97864bb-vxvlp
Namespace:      default
Node:           docker-for-desktop/192.168.65.3
Start Time:     Tue, 28 Aug 2018 23:23:25 -0400
Labels:         app=mongodb
                chart=mongodb-4.2.0
                pod-template-hash=2385342066
                release=my-release
Annotations:    <none>
Status:         Running
IP:             10.1.0.15
Controlled By:  ReplicaSet/my-release-mongodb-67d97864bb
Containers:
  my-release-mongodb:
    Container ID:   docker://b8358998b177b9cbae59647238ce4d69e9a8bb64c1a833b63e33f31685d0dde2
    Image:          docker.io/bitnami/mongodb:4.0.1-debian-9
    Image ID:       docker-pullable://bitnami/mongodb@sha256:8620699e9c7e9368330a7f36d6b18d375fdd9fff3c8cb9fb4fa77316c242099e
    Port:           27017/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 29 Aug 2018 11:17:23 -0400
    Ready:          False
    Restart Count:  29
    Liveness:       exec [mongo --eval db.adminCommand('ping')] delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:      exec [mongo --eval db.adminCommand('ping')] delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      MONGODB_ROOT_PASSWORD:  <set to the key 'mongodb-root-password' in secret 'my-release-mongodb'>  Optional: false
      MONGODB_USERNAME:
      MONGODB_DATABASE:
      MONGODB_EXTRA_FLAGS:
    Mounts:
      /bitnami/mongodb from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4ddm7 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  my-release-mongodb
    ReadOnly:   false
  default-token-4ddm7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-4ddm7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                  From                         Message
  ----     ------                 ----                 ----                         -------
  Normal   Pulling                10h (x16 over 11h)   kubelet, docker-for-desktop  pulling image "docker.io/bitnami/mongodb:4.0.1-debian-9"
  Warning  BackOff                10h (x464 over 11h)  kubelet, docker-for-desktop  Back-off restarting failed container
  Normal   SuccessfulMountVolume  39m                  kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "pvc-dec33566-ab3a-11e8-ab3b-00155d016b17"
  Normal   SuccessfulMountVolume  39m                  kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "default-token-4ddm7"
  Normal   SandboxChanged         39m                  kubelet, docker-for-desktop  Pod sandbox changed, it will be killed and re-created.
  Normal   Created                38m                  kubelet, docker-for-desktop  Created container
  Normal   Started                38m                  kubelet, docker-for-desktop  Started container
  Warning  Unhealthy              37m                  kubelet, docker-for-desktop  Liveness probe failed: MongoDB shell version v4.0.1
connecting to: mongodb://127.0.0.1:27017
2018-08-29T14:40:18.501+0000 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:257:13
@(connect):1:6
exception: connect failed
  Warning  Unhealthy  37m  kubelet, docker-for-desktop  Readiness probe failed: MongoDB shell version v4.0.1          
`

**Comment by yuswitayudi** [comment]
Hello @antonyRoberts ,

Do you solved thiw issue?
