### ISSUE TITLE
[stable/cockroachdb] for single node cockroachdb, deleting the pod doesn't restore it into a working state

### ISSUE THREAD

**Issue by prashant182** [helm/charts#7433]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
YES

When you install the helm chart for replicas = 1, and then delete the running pod, it comes back up but with a readiness prob failed state and db doesn't work. 
**Version of Helm and Kubernetes**:
helm : 2.10
k8s : 1.10

**Which chart**:
stable/cockroachdb

**What happened**:
deleting for from statefulset breaks the cockroachdb

**What you expected to happen**:
cockroachdb can't restore itself.

**How to reproduce it** (as minimally and precisely as possible):
```helm install --name my-release stable/cockroachdb
kubectl scale statefulset my-release-cockroachdb --replicas=1
kubectl delete po my-release-cockroachdb-0  
```
which will start cockroachdb in failed state.
```
NAME                                    READY     STATUS      RESTARTS   AGE
my-release-cockroachdb-0            0/1       Running     0          5m
my-release-cockroachdb-init-6t5q6   0/1       Completed   0          15m
```
** anything else we should know about ** 
logs 
```I180829 23:38:26.852352 16443 gossip/client.go:134  [n1] closing client to node 1 (my-release-cockroachdb-0.my-release-cockroachdb:26257): stopping outgoing client to node 1 (my-release-cockroachdb-0.my-release-cockroachdb:26257); loopback connection
W180829 23:38:27.086169 152 sql/jobs/registry.go:286  unable to get node liveness: node not in the liveness table
W180829 23:38:27.433420 117 storage/store.go:1463  [n1,s1,r7/1:/Table/{SystemCon…-11}] could not gossip system config: [NotLeaseHolderError] r7: replica (n1,s1):1 not lease holder; lease holder unknown
I180829 23:38:27.952348 16476 gossip/client.go:129  [n1] started gossip client to my-release-cockroachdb-0.my-release-cockroachdb:26257
I180829 23:38:27.952917 16476 gossip/client.go:134  [n1] closing client to node 1 (my-release-cockroachdb-0.my-release-cockroachdb:26257): stopping outgoing client to node 1 (my-release-cockroachdb-0.my-release-cockroachdb:26257); loopback connection
W180829 23:38:28.466634 117 storage/store.go:1463  [n1,s1,r7/1:/Table/{SystemCon…-11}] could not gossip system config: [NotLeaseHolderError] r7: replica (n1,s1):1 not lease holder; lease holder unknown
```
And 

`kubectl describe po my-release-cockroachdb-0`

 logs 
```
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir-my-release-cockroachdb-0
    ReadOnly:   false
  default-token-dx7d8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-dx7d8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age               From               Message
  ----     ------                 ----              ----               -------
  Normal   Scheduled              8m                default-scheduler  Successfully assigned my-release-cockroachdb-0 to minikube
  Normal   SuccessfulMountVolume  8m                kubelet, minikube  MountVolume.SetUp succeeded for volume "pvc-54d81355-abe2-11e8-819b-080027096c35"
  Normal   SuccessfulMountVolume  8m                kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-dx7d8"
  Normal   Pulling                8m                kubelet, minikube  pulling image "cockroachdb/cockroach:v2.0.5"
  Normal   Pulled                 8m                kubelet, minikube  Successfully pulled image "cockroachdb/cockroach:v2.0.5"
  Normal   Created                8m                kubelet, minikube  Created container
  Normal   Started                8m                kubelet, minikube  Started container
  Warning  Unhealthy              3m (x58 over 7m)  kubelet, minikube  Readiness probe failed: HTTP probe failed with statuscode: 500```

**Comment by robert-s-lee** [comment]
@prashant182 A default CockroachDB with --replicas=3 will withstand a single node failure without any loss of service time or data.  Is there a specific reason to use 1 replica instead of default 3 that provides the HA capability?

**Comment by prashant182** [comment]
Clusters, where we are deploying cockroachdb, doesn't necessarily have their ntp time sync. So we are keeping statefulset to 1 node.  If customers want to scale cockroachdb then they do the ntp timesync across their linux nodes and then they can scale it using `kubectl scale statefulset ... --replicas=n`.  Sometimes we can not This was our reasoning, we welcome other suggestions. Sometimes those clusters are in an air-gapped environment so customers are required to do ntp sync on their preferred method.

**Comment by robert-s-lee** [comment]
What are "air-gapped" environment limitations and accepted tradeoffs?  

For example, in terms of infrastructure, limitations might be CPU, RAM, Network, Storage capacity, running in a single replica, not changing the replica count once started, not reducing replica count below a certain level once expanded.  

The consequential tradeoffs could be reduced choice of database cluster topology patterns to choose from, maximum concurrency the database can accept, RPO and RPO, backup and recovery SLA, number of microservices or multitenancy per K8, the complexity of SQL or Schema.

**Comment by prashant182** [comment]
An “air-gapped” environment is a network that has no path to inbound or outbound internet traffic at all. So in terms of support and installation, we can not assume things that rely on the internet such as timesync. I believe on cockraochdb official website, the recommended way is to use `server time1.google.com iburst` which might not be available for air-gapped environment, so we are not hitting all the points from your production checklist.

**Comment by prashant182** [comment]
Also, the helmchart that is provided for such systems needs to be rock-solid and resilient in terms of reliability and failure tolerance. Let's say the single node cockroachdb goes down, then we should have a k8s cron job or some sort of mechanism which keeps checking on the health of the database and performs a series of steps to recover it from the failure. I have seen that k8s respawning of the crashed pod is not a reliable solution at least for cockroachdb.  Database is a fundamental platform to build apis and services upon, so downtime in a database affect all of these services.

**Comment by a-robinson** [comment]
Hi @prashant182, the problem is that you created a 3 node cluster and then scaled it down to 1 node when you ran the `kubectl scale statefulset my-release-cockroachdb --replicas=1` command. Once cockroach has replicated its data to 3 or more nodes, scaling down to 1 node is no longer supported.  In other words, your cluster stopped working because of the `kubectl scale` command, not because of the subsequent `kubectl delete` commands.

If you want a 1 node cluster, you must start it with only 1 node:

```
helm install stable/cockroachdb --name=my-release --set Replicas=1
```

That 1 node cluster should then be just fine across restarts and other such issues. If you manage to hit a problem after starting the cluster with just 1 node, I'd be incredibly interested to know about it.

**Comment by prashant182** [comment]
@a-robinson Sorry for late response, Turns out you were right, scaling statefulset up and down was the issue, keeping it to a single node worked out well.
