### ISSUE TITLE
Should we still add missing charts OWNERS files?

### ISSUE THREAD

**Issue by scottrigby** [helm/charts#7446]
Issue to track PRs adding [OWNERS](https://github.com/helm/charts/issues/3006) files to charts still missing them.

Note I'm not sure if it's worth the extra 148 PRs now that we're working toward the charts [distributed search proposal](https://github.com/helm/community/pull/24) 🤔 Then again, perhaps any little bit towards distributed ownership could be a help in the PR deluge (these ones at least would be quick & easy to review/merge)? Adding this issue for discussion.

`find incubator stable -mindepth 1 -maxdepth 1 -type d '!' -exec test -e "{}/OWNERS" ';' -print | sort -u`:

- [ ] incubator/burrow
- [x] incubator/cassandra
- [ ] incubator/check-mk
- [ ] incubator/common
- [ ] incubator/couchdb
- [ ] incubator/distribution
- [ ] incubator/drone
- [ ] incubator/etcd
- [ ] incubator/fluentd
- [ ] incubator/fluentd-cloudwatch
- [ ] incubator/gocd
- [ ] incubator/gogs
- [ ] incubator/goldfish
- [ ] incubator/istio
- [ ] incubator/jaeger
- [ ] incubator/keycloak
- [ ] incubator/keycloak-proxy
- [ ] incubator/kube-registry-proxy
- [ ] incubator/kube-spot-termination-notice-handler
- [ ] incubator/kubernetes-vault
- [ ] incubator/kubewatch
- [ ] incubator/mysqlha
- [ ] incubator/oauth-proxy
- [ ] incubator/patroni
- [ ] incubator/puppet-forge
- [ ] incubator/redis-cache
- [ ] incubator/riemann
- [ ] incubator/spring-cloud-data-flow
- [ ] incubator/tensorflow-inception
- [ ] incubator/vault
- [ ] incubator/vaultingkube
- [ ] incubator/webpagetest-agent
- [ ] incubator/webpagetest-server
- [ ] incubator/xray
- [ ] stable/acs-engine-autoscaler
- [ ] stable/aerospike
- [ ] stable/apm-server
- [ ] stable/ark
- [ ] stable/auditbeat
- [ ] stable/aws-cluster-autoscaler
- [ ] stable/bitcoind
- [ ] stable/buildkite
- [ ] stable/centrifugo
- [x] stable/chronograf
- [ ] stable/cluster-autoscaler
- [ ] stable/consul
- [ ] stable/coscale
- [ ] stable/dask
- [ ] stable/dask-distributed
- [ ] stable/dex
- [ ] stable/distributed-tensorflow
- [ ] stable/efs-provisioner
- [ ] stable/elasticsearch-exporter
- [ ] stable/ethereum
- [ ] stable/express-gateway
- [ ] stable/external-dns
- [ ] stable/factorio
- [ ] stable/filebeat
- [ ] stable/fluent-bit
- [ ] stable/gcloud-endpoints
- [ ] stable/gcp-night-king
- [ ] stable/gitlab-ce
- [ ] stable/gitlab-ee
- [ ] stable/grafana
- [ ] stable/hackmd
- [ ] stable/hadoop
- [ ] stable/heapster
- [ ] stable/heartbeat
- [ ] stable/hlf-ca
- [ ] stable/hlf-couchdb
- [ ] stable/hlf-ord
- [ ] stable/home-assistant
- [ ] stable/hubot
- [x] stable/influxdb
- [ ] stable/ipfs
- [ ] stable/janusgraph
- [ ] stable/kanister-operator
- [ ] stable/kapacitor
- [ ] stable/katafygio
- [ ] stable/keel
- [ ] stable/keycloak
- [ ] stable/kiam
- [ ] stable/kong
- [ ] stable/kube-lego
- [ ] stable/kube-ops-view
- [ ] stable/kube-slack
- [ ] stable/kube-state-metrics
- [ ] stable/kube2iam
- [ ] stable/kubernetes-dashboard
- [ ] stable/kuberos
- [ ] stable/kured
- [ ] stable/lamp
- [ ] stable/linkerd
- [ ] stable/locust
- [ ] stable/luigi
- [ ] stable/mailhog
- [ ] stable/mcrouter
- [ ] stable/metabase
- [ ] stable/metallb
- [ ] stable/minecraft
- [ ] stable/minio
- [ ] stable/msoms
- [x] stable/mssql-linux
- [ ] stable/namerd
- [ ] stable/neo4j
- [ ] stable/newrelic-infrastructure
- [ ] stable/nginx-ingress
- [ ] stable/nginx-ldapauth-proxy
- [ ] stable/nginx-lego
- [ ] stable/openebs
- [ ] stable/openldap
- [ ] stable/percona
- [ ] stable/postgresql
- [ ] stable/presto
- [ ] stable/prometheus-adapter
- [ ] stable/prometheus-mysql-exporter
- [ ] stable/prometheus-postgres-exporter
- [ ] stable/prometheus-rabbitmq-exporter
- [ ] stable/prometheus-redis-exporter
- [ ] stable/prometheus-to-sd
- [ ] stable/rabbitmq-ha
- [ ] stable/redis-ha
- [ ] stable/rethinkdb
- [ ] stable/risk-advisor
- [ ] stable/rocketchat
- [ ] stable/rookout
- [ ] stable/sapho
- [ ] stable/selenium
- [ ] stable/sensu
- [ ] stable/sentry
- [ ] stable/signalfx-agent
- [ ] stable/spark
- [ ] stable/spartakus
- [ ] stable/spotify-docker-gc
- [ ] stable/stackdriver-exporter
- [ ] stable/stolon
- [ ] stable/sugarcrm
- [ ] stable/sumokube
- [ ] stable/sumologic-fluentd
- [ ] stable/superset
- [ ] stable/telegraf
- [ ] stable/tomcat
- [ ] stable/uchiwa
- [ ] stable/unbound
- [ ] stable/verdaccio
- [ ] stable/weave-scope
- [ ] stable/zeppelin
- [ ] stable/zetcd

**Comment by cpanato** [comment]
i can own some if needed.

**Comment by cpanato** [comment]
@scottrigby cool, I will try to join the next meeting. the problem it is in the same time as my planning weekly meeting :(
but count me for any help

**Comment by mattfarina** [comment]
Before we make owners files we do need to make sure the people are trusted and have contributed. There are numerous people listed as owners who have not contributed before.

K8s has a trust system via sponsorships. How do we trust the people we add to owners files?

**Comment by christian-roggia** [comment]
Should this list exclude **deprecated** charts? incubator/drone has been moved to **stable** and it has its OWNER file, the **incubator** chart is there only because of the [deprecation process](https://github.com/helm/charts/blob/master/PROCESSES.md).

**Comment by maver1ck** [comment]
incubator/cassandra done :)

**Comment by scottrigby** [comment]
@cpanato The decision here was to add these OWNERS files only as needed (when people request to help maintain them), since our efforts would be better spent moving to the [distributed charts hub](https://github.com/helm/community/blob/master/proposals/distributed-search.md) than opening all of these PRs each with a chart bump (and the coordination with other PRs against those same charts also bumping the version).
