### ISSUE TITLE
[stable/openvpn] How to revoke a certificate

### ISSUE THREAD

**Issue by kilianc** [helm/charts#7487]
This could be added as helper script in the chart. At the moment is up to the user to figure out a proper way to revoke a certificate.

N.B. I am still working on a solution myself. Will post here.

**Comment by jmastr** [comment]
@kilianc have you found out how to do it?

**Comment by MikeSchuette** [comment]
I have a PR open which solves this:  https://github.com/helm/charts/pull/6841

**Comment by kilianc** [comment]
@jmastr I wish. I tried a couple of approaches but it didn't work out. I will try again using the scripts in #6841

**Comment by kilianc** [comment]
@MikeSchuette how can I help? Who did you ping? I can give it a try
