### ISSUE TITLE
[incubator/jaeger] Add option for specifying basePath

### ISSUE THREAD

**Issue by lambertjosh** [helm/charts#7489]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

Jaeger has added a new option to set the base path of the query UI, which makes it usable behind reverse proxies. This option should also be exposed in the chart as well.

PR which added this support: https://github.com/jaegertracing/jaeger/pull/748

**Comment by pavelnikolov** [comment]
I'll try to push it shortly. Thanks for reporting this.
