### ISSUE TITLE
[stable/keycloak] allow hostaliases to be set

### ISSUE THREAD

**Issue by jonsalvas** [helm/charts#7498]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

It should be possible to set hostaliases for the keycloak helm chart. This is needed when working with external identity providers from different customers across multiple networks, where host/dns names cannot always be resolved. It should be possible to configure aliases in the following manner:
```
hostAliases:
- ip: "1.2.3.4."
  hostnames:
  - "my.host.com"
```

**Comment by unguiculus** [comment]
Care to provide a PR?
