### ISSUE TITLE
[stable/kubernetes-dashboard] Allow HTTP connection

### ISSUE THREAD

**Issue by tonyxiao** [helm/charts#7516]
There are situations where the kubernetes dashboard is hosted behind ingress controllers / proxies that perform TLS termination already. Many ingress controllers / proxies (cloudflare argo ingress, oauth2_proxy) expect proxied services to be HTTP, and do not support HTTPS services. 

Recommend adding an input value to setup deployment to allow HTTP traffic (which is supported by k8s-dashboard binary itself via `--insecure-port`, `--insecure-bind-address` and `--enable-insecure-login` option. 

Reference: [On Securing the Kubernetes Dashboard by Joe Beda @ Heptio
](https://blog.heptio.com/on-securing-the-kubernetes-dashboard-16b09b1b7aca)

**Comment by desaintmartin** [comment]
I would be happy to review, although I don't have the mighty /approve power that @kfox1111 have as official maintainer. :)
I would use this feature myself as it seems unnecessary behind ingress.

**Comment by mbarrien** [comment]
Preventing this from being auto closed by commenting. Any feedback on my PR #9011 ?

**Comment by desaintmartin** [comment]
Dear bot, please don't.
cc @kfox1111
