### ISSUE TITLE
Nginx ingress as web-server for PHP-FPM without middleware nginx container.

### ISSUE THREAD

**Issue by SergeC** [helm/charts#7534]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST
**Version of Helm and Kubernetes**:
1.11.2

**Which chart**:
https://github.com/helm/charts/tree/master/stable/nginx-ingress

**What happened**:
I have PHP application running in fpm container and nginx. My setup is: nginx ingress => nginx => fpm. I'd like to use ingress as web server for the fpm and remove middleware nginx container. I need to set 'fastcgi_pass php-fpm:9000;' in nginx ingress config.

**What you expected to happen**:
Make use of nginx ingress as web server for PHP-FPM without having middleware nginx container.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by toruksmakto** [comment]
+!

**Comment by brianvoss** [comment]
This would not be a helm implementation.  You want the discussion happening here: https://github.com/kubernetes/ingress-nginx/issues/2982
