### ISSUE TITLE
.Release.Name used in config map title not forced to lower case

### ISSUE THREAD

**Issue by dwilliams782** [helm/charts#7544]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Version of Helm and Kubernetes**:
Helm: v2.9.1
Kube: 1.9.7

**Which chart**:
nginx-ingress

**What happened**:
When using nginx-ingress, where the release name is not all lower case, the nginx-ingress.controller.fullname function returns a name for the config map that contains capital letters so it fails validation.

**What you expected to happen**:

The fully qualified name could be passed through " | lower " to prevent this.

**How to reproduce it** (as minimally and precisely as possible):

Deploy the Helm chart with a release name containing any [A-Z] char.

**Anything else we need to know**:

**Comment by cpanato** [comment]
Thanks. I will take a look on that

**Comment by cpanato** [comment]
I did a test and I try to install the chart using for example `TESTNginx` and looks like chart itself does not like that, but the deployment was ok (after I did the modification to lower the names)

```
➜ helm install . -n TESTNginx
NAME:   TESTNginx
Error: getting deployed release "TESTNginx": release: "TESTNginx" not found
```

but anyways the PR is here: https://github.com/helm/charts/pull/7572

**Comment by cpanato** [comment]
@davidkarlsen sounds good, will close the PR
