### ISSUE TITLE
[incubator/kafka] Kafka pod crashloopback when external.enabled=true

### ISSUE THREAD

**Issue by thiennhan2310** [helm/charts#7556]
My current kafka image : confluentinc/cp-kafka:4.1.2-2
When I set  external.enabled=true , kafka pod is being crash
<img width="630" alt="screen shot 2018-09-05 at 9 47 35 pm" src="https://user-images.githubusercontent.com/12071356/45103475-2aeabd00-b15a-11e8-8fc5-9a4419972bb3.png">

**Comment by thiennhan2310** [comment]
I guess because of this line 
https://github.com/helm/charts/blob/c766da3ded48ac99dd0f74e98d5dfbb2b668f9fe/incubator/kafka/templates/statefulset.yaml#L42

**Comment by cristianodarocha** [comment]
I had the same issue when trying to set external.enabled=true. The kafka pod is being crash

**Comment by cristianodarocha** [comment]
I'm getting the same issue as follows:

```
+ kubectl label pods kafka-0 --namespace kafka pod=kafka-0
Error from server (Forbidden): pods "kafka-0" is forbidden: User "system:serviceaccount:kafka:default" cannot get pods in the namespace "kafka"
```

**Comment by sundhar010** [comment]
I have the same issue, still not able to spin up the pods after external.enabled=true. Followed @thiennhan2310 solution but no progress. Did anyone resolve this issue? I guess it's not about rbac as I am not getting any error as forbidden.

**Comment by arolls** [comment]
I had this problem initially when setting the external.enabled=true. In my case it turned out to be because my Kubernetes cluster was RBAC enabled. Adding an override for kafka to the values file:
`kafka: 
   rbac:
      enabled: true`
Fixed this issue for me.

**Comment by ardijusufi** [comment]
I managed to get the pods up and running by specifying rbac.enabled=true during the installation as follows:

`helm install --namespace kafka --name prod-kafka incubator/kafka --set rbac.enabled=true --set external.enabled=true`

**Comment by vemv** [comment]
not stale

---

there's a number of Kafka issues which probably have the same cause, and a handful of known fixes suggested from the community. Would really appreciate if things were left in a good shape finally!
