### ISSUE TITLE
How to enable wal-e for backup and restore in Stolon helm chart?

### ISSUE THREAD

**Issue by candysmurf** [helm/charts#7563]
**Is this a request for help?**:
Yes
---

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.
  * Enable backup and restore of DB using wal-e
  * Storage like S3 or Rook + Ceph

**Version of Helm and Kubernetes**:
Helm
```sh
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
Kubectl
```sh
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
Stolon

**What happened**:
Would like to setup Wal-E with Stolon. Please help.

**Comment by ken0x0a** [comment]
Hi stale bot, reopen please! This is important for production use.

**Comment by shishirkh** [comment]
Yes. Please reopen. Also, if there is a doc available to do this backup and restore - please send the link here. 

Thanks!
