### ISSUE TITLE
[stable/minio]  service.externalIPs is not defined in values.yaml and other lint issues

### ISSUE THREAD

**Issue by sanverm2** [helm/charts#7569]
Lint issues: 

1.  Parameter is used, but not defined: service.externalIPs is not defined, but used in [ibm-minio-objectstore/templates/service.yaml.  This is needed even as documentation purpose in values.yaml because if user  wants to use it, he is clueless how to specify it. 

2. Parameter is used, but not defined: persistence.existingClaim is not defined, but used in [ibm-minio-objectstore/templates/deployment.yaml ibm-minio-objectstore/templates/pvc.yaml

3. Missing readinessProbe: readinessProbe not found for container 0 in ibm-minio-objectstore/templates/deployment.yaml

**Comment by cpanato** [comment]
PR: https://github.com/helm/charts/pull/7588

**Comment by cpanato** [comment]
for item 2 it is defined in values.yaml https://github.com/helm/charts/blob/master/stable/minio/values.yaml#L45
