### ISSUE TITLE
Vitess chart

### ISSUE THREAD

**Issue by F21** [helm/charts#761]
[Vitess](https://github.com/youtube/vitess) allows you to easily run a sharded MySQL cluster.

According to the [user guide](http://vitess.io/getting-started/), it plays pretty well with Kubernetes. It would be awesome if someone can contribue a chart for it! 😄

**Comment by seanknox** [comment]
Hi @F21, that does sound like a useful addition for the chart community. Closing this issue, but feel free to open a PR!
