### ISSUE TITLE
Codestyle - dropCase or CamelCase

### ISSUE THREAD

**Issue by pierreozoux** [helm/charts#762]
For the values, which one should we use?

(Then, let's add it to the requirements, and update charts.)

Would it make sense to make `helm lint` warn about this too?
(This would ease our work here)

**Comment by ghost** [comment]
We talk about general best practices at #44 

Most of the charts, I see dropCase. I think the reason is kubernetes follow dropCase in yaml files such as imagePullPolicy, livenessProbe, initialDelaySeconds...

**Comment by so0k** [comment]
dropCase also provides the ability to include parts of `values.yaml` directly into manifest files
