### ISSUE TITLE
[stable/keycloak] Wrong type for value; expected string; got []interface {}

### ISSUE THREAD

**Issue by huychau** [helm/charts#7633]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm: 2.10.0 Kubernetes: 1.10.4

**Which chart**: stable/keycloak

**What happened**:
I got this error when install keycloak chart 
```
Error: render error in "keycloak/templates/statefulset.yaml": template: keycloak/templates/statefulset.yaml:68:7: executing "keycloak/templates/statefulset.yaml" at <.>: wrong type for value; expected string; got []interface {}
```
Can not convert this line: https://github.com/helm/charts/blob/master/stable/keycloak/templates/statefulset.yaml#L68
Please help to check.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by unguiculus** [comment]
Please provide more information. Otherwise I won't be able to assist you. What install parameters or `values.yaml` are you using?

**Comment by mrtndwrd** [comment]
I have experienced this issue (not 100% sure if it's the same line though), when I set the `extraEnv` value:

It was set like this:

```
  extraEnv:
    - name: "KEYCLOAK_LOGLEVEL"
      value: "DEBUG"

```

But, as the documentation suggests, you need to set it as a string instead of a list: 

```
  extraEnv: |
    - name: "KEYCLOAK_LOGLEVEL"
      value: "DEBUG"
```

Not a bug, IMO, although I also found it a bit weird that it had to be a string.

**Comment by unguiculus** [comment]
I has to be a string because it is passed through the tpl function. This is documented in the readme.
