### ISSUE TITLE
[stable/jenkins] pod has unbound PersistentVolumeClaims

### ISSUE THREAD

**Issue by salman-hayder** [helm/charts#7652]
After installing stable/jenkins chart, pod goes to pending state and it shows error: pod has unbound PersistentVolumeClaims
Any idea how to ressolve it?
I am working on kubernetes cluster installed on remote machine accessing virtually, running with kubectl.

**Comment by zdtsw** [comment]
saw "no persistent volumes available for this claim and no storage class is set" guess it is the same thing as you've mentioned?
there is no available pv created ahead

**Comment by salman-hayder** [comment]
I have solved this issue @zdtsw  by adding persistent volumes and claims...

**Comment by lnngle** [comment]
@salman-hayder 
I also have this problem. But how exactly do you adding persistent volumes and claims?

**Comment by vongrossi** [comment]
>@lnngle Do you add persistent volume  class using yaml file 
 
```
$ cat jenkins-pvc.yaml 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

```

And run helm install with this parameter to set pvc

```
$ helm install --name my-release --set persistence.existingClaim=jenkins-pvc stable/jenkins
```

**Comment by salamani** [comment]
Still facing same issue for NodePort

**Comment by pkaramol** [comment]
Isn't the `helm` chart supposed to be creating a PVC if we do not provide for an existing one?
