### ISSUE TITLE
[stable/jenkins] Readiness Probe Failed

### ISSUE THREAD

**Issue by salman-hayder** [helm/charts#7657]
![screenshot from 2018-09-11 14-04-22](https://user-images.githubusercontent.com/40059719/45350257-c2259980-b5cc-11e8-9387-b227bad7d32c.png)
While installing stable/jenkins, facing this error
Readiness probe failed: Get http://192.168.13.41:8080/login: net/http: request canceled (Client.Timeout exceeded while awaiting headers
Any idea how to resolve it? 
I'm using kubernetes based remote cluster using kubectl.

**Comment by kddejong** [comment]
similar issue and I have what looks to be a weird readiness and liveness url.
```
Liveness:   http-get http://:http/login delay=90s timeout=5s period=10s #success=1 #failure=12
Readiness:  http-get http://:http/login delay=60s timeout=1s period=10s #success=1 #failure=3
```

**Comment by salman-hayder** [comment]
I allocated 8GB but still same issue...

**Comment by r96725046** [comment]
Turn off HealthProbes to prevent from the pods are restarting by k8s. Then observe the pod log and status.
Use describe nodes to check the memory settings
![image](https://user-images.githubusercontent.com/42165511/46278913-38993400-c59a-11e8-96e8-de595e422ba4.png)

**Comment by NiuZhuang** [comment]
Same issue here. Failed to helm install jenkins.

**Comment by ayk33** [comment]
I seem to be running across the same issue. Looking at events for my jenkins deployment just shows that the readiness probe failed. Anyone else figure out the root cause of this? Could this be an issue with latest? I didn't notice this issue happening before.

```
2m 2m 1 jenkins-858f9695d7-gdtsl.1574fd231f31c959 Pod spec.containers{jenkins} Warning Unhealthy kubelet, <node_name> Liveness probe failed: Get http://<ip of pod>:8080/login: read tcp <unknown ip>:34216-><pod_ip>:8080: read: connection reset by peer
2m 1d 3 jenkins-858f9695d7-gdtsl.1574966ff3338a7f Pod spec.containers{jenkins} Normal  Pulled    kubelet, <node_name> Successfully pulled image "jenkins/jenkins:lts"
2m 1d 3 jenkins-858f9695d7-gdtsl.1574966fffce0346 Pod spec.containers{jenkins} Normal  Started   kubelet, <node_name> Started container
2m 1d 3 jenkins-858f9695d7-gdtsl.1574966ff79ad2d7 Pod spec.containers{jenkins} Normal  Created   kubelet, <node_name> Created container
1m 1d 4 jenkins-858f9695d7-gdtsl.1574967eb4c32924 Pod spec.containers{jenkins} Warning Unhealthy kubelet, <node_name> Readiness probe failed: Get http://:8080/login: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by coderiseio** [comment]
I have encountered the same error. After investigating, I found out that it's just a matter of waiting a few minutes until it extracts the war file to the mounted volume. This can sometimes take up to 5-10 minutes, depending upon disk iops. You can mount the same volume to a different container like busybox and run 'du -sh' to track progress. You can check the pod logs as well.
