### ISSUE TITLE
[stable/spinnaker] Add dwardu89 to OWNERS

### ISSUE THREAD

**Issue by dwardu89** [helm/charts#7669]
**Is this a request for help?**:

I'd like to be added as an Owner. I am currently working at ClearScore and we decided to use spinnaker as our cicd solution and believe in building repeatable solutions.
In order to automate spinnaker, its already hard on its own because of every command, and I want to push towards making it as customisable as possible and contribute it back instead of having our own fork.

@linki and @viglesiasce are currently the owners of this.

**Comment by linki** [comment]
@dwardu89 I'm actually not an owner of that chart. Adding @lwander here as well.
