### ISSUE TITLE
[stable/fluent-bit] ignores 'logstash_prefix' value for es backend

### ISSUE THREAD

**Issue by dankirkpatrick** [helm/charts#7675]
**Is this a request for help?**:

Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:
Helm v2.10.0
Kubernetes v1.10.6

**Which chart**:
fluent-bit

**What happened**:
The "logstash_prefix" for the es backend is ignored.  As a result, the elasticsearch indices always start with "logstash-".

**What you expected to happen**:
The "logstash_prefix" results in a line in the configmap in the [Output] section that reads:

    Logstash_Prefix <<given prefix>>

**How to reproduce it** (as minimally and precisely as possible):
Set logstash_prefix in values.yaml, deploy chart. 

**Anything else we need to know**:
This would be fixed by adding the following to charts/stable/fluent-bit/templates/config.yaml at line 76:

{{- if .Values.backend.es.logstash_prefix }} 
        Logstash_Prefix {{ .Values.backend.es.logstash_prefix }} 
{{- end }}

**Comment by davidkarlsen** [comment]
@dankirkpatrick would you fancy doing a PR for it?

**Comment by cpanato** [comment]
if you dont have time or dont want to make it i can do @dankirkpatrick

**Comment by dankirkpatrick** [comment]
Just read these comments.  If a PR hasn't been done yet I'll branch and do one now.

**Comment by dankirkpatrick** [comment]
https://github.com/helm/charts/pull/7694
