### ISSUE TITLE
Selectors for StatefulSets and PersistentVolumeClaims

### ISSUE THREAD

**Issue by ricardofbarros** [helm/charts#7677]
**Is this a request for help?**: 

No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature Request

**Version of Helm and Kubernetes**:
...

**Which chart**:
Pretty much every chart with a StatefulSet or a PersistentVolumeClaim.

**What you expected to happen**:
Charts that have a StatefulSet or a PersistentVolumeClaim to be able to use selectors (matchLabels or matchExpressions).

For StatefulSets we could have something like:

```
  volumeClaimTemplates
   ...
       spec:
       ...
           selector:
        {{- if .Values.persistence.matchLabels }}
              matchLabels:
        {{ toYaml .Values.persistence.matchLabels | indent x }}
        {{- end -}}
        {{- if .Values.persistence.matchExpressions }}
              matchExpressions:
         {{ toYaml .Values.persistence.matchExpressions | indent x }}
         {{- end -}}
```

and for PersistentVolumeClaims we could have:

```
  selector:
{{- if .Values.persistence.matchLabels }}
    matchLabels:
{{ toYaml .Values.persistence.matchLabels | indent x }}
{{- end -}}
{{- if .Values.persistence.matchExpressions }}
    matchExpressions:
{{ toYaml .Values.persistence.matchExpressions | indent x }}
{{- end -}}
```

This feature would be useful when dynamic provisioning isn't a option.

**How to reproduce it** (as minimally and precisely as possible):
...

**Anything else we need to know**:

I'll happily do a pull request with this feature (for a few charts or else it will be massive) if this feature request is accepted.

**Comment by servicemeshistio** [comment]
> **Is this a request for help?**:
> 
> No
> 
> **Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
> 
> Feature Request
> 
> **Version of Helm and Kubernetes**:
> ...
> 
> **Which chart**:
> Pretty much every chart with a StatefulSet or a PersistentVolumeClaim.
> 
> **What you expected to happen**:
> Charts that have a StatefulSet or a PersistentVolumeClaim to be able to use selectors (matchLabels or matchExpressions).
> 
> For StatefulSets we could have something like:
> 
> ```
>   volumeClaimTemplates
>    ...
>        spec:
>        ...
>            selector:
>         {{- if .Values.persistence.matchLabels }}
>               matchLabels:
>         {{ toYaml .Values.persistence.matchLabels | indent x }}
>         {{- end -}}
>         {{- if .Values.persistence.matchExpressions }}
>               matchExpressions:
>          {{ toYaml .Values.persistence.matchExpressions | indent x }}
>          {{- end -}}
> ```
> and for PersistentVolumeClaims we could have:
> 
> ```
>   selector:
> {{- if .Values.persistence.matchLabels }}
>     matchLabels:
> {{ toYaml .Values.persistence.matchLabels | indent x }}
> {{- end -}}
> {{- if .Values.persistence.matchExpressions }}
>     matchExpressions:
> {{ toYaml .Values.persistence.matchExpressions | indent x }}
> {{- end -}}
> ```
> This feature would be useful when dynamic provisioning isn't a option.
> 
> **How to reproduce it** (as minimally and precisely as possible):
> ...
> 
> **Anything else we need to know**:
> 
> I'll happily do a pull request with this feature (for a few charts or else it will be massive) if this feature request is accepted.

This is exactly what we need to be able to use either matchLabels or matchExpressions. 

@ricardofbarros - did you put in a pull request so that they can accept it? We need this feature.

**Comment by ricardofbarros** [comment]
@servicemeshistio Unfortunately I didn't did a PR with this feature because I didn't get any feedback from a core maintainer if this feature would be useful or not.
