### ISSUE TITLE
Datadog Request - Add option to specify DD_URL

### ISSUE THREAD

**Issue by pulberg** [helm/charts#768]
DD constructs a version specific URL that is used to send metrics data to DD - 

`https://5-11-0-app.agent.datadoghq.com`

Aside from the numerous reasons why this is a bad idea, it is especially bad for hyper-security envs like mine.  DD does provide an alternate URL to use - 

 `https://unversioned.agent.datadoghq.com`

It would be really helpful if this chart could be updated to include an option to specify the DD_URL - 

```
datadog.dd_url=<blank> - use url constructed by agent

datadog.dd_url=https://unversioned.agent.datadoghq.com
```

Thanks

**Comment by seanknox** [comment]
Hi @pulberg, that sounds like a reasonable suggestion. We'd love if you opened a pull request!

**Comment by pulberg** [comment]
@seanknox after looking at the deployed datadog.conf, the dd_url is not being set correctly anyway.  It is being set to `https://app.datadoghq.com` which is the url for the website, not data ingestion.   not sure where/how that is being set.
