### ISSUE TITLE
[stable/RabbitMQ-HA] Restarting all nodes of a cluster doesn't result in a healthy cluster

### ISSUE THREAD

**Issue by nickstolwijk** [helm/charts#7682]
I was trying to restart my RabbitMQ cluster after deploying a new version of the chart. I deleted all pods to let Kubernets create new pods of the new version. RabbitMQ expects that the last node to go down, will be the first that will come up. Unfortunately, Kubernetes started another node first. That node couldn't connect to the cluster and went down again. Rinse en repeat.

I found the setting for a statefullset to start all pods at once and thus could restart my cluster.

**Comment by steven-sheehy** [comment]
Use a rollingupdate to only bring down one at a time and allow RabbitMQ to maintain a quorum.
