### ISSUE TITLE
[stable/percona-xtradb-cluster] Random Pod name creates different deployment on every chart installation

### ISSUE THREAD

**Issue by maver1ck** [helm/charts#7708]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

Helm: v2.10.0
Kubernetes: 1.10.6

**Which chart**:
percona-xtradb-cluster

**What happened**:
Everytime I generate deployment from this chart I'm getting different Pod for test.
This make helm diff showing difference on every update. 
The reason is this line:
https://github.com/helm/charts/blob/master/stable/percona-xtradb-cluster/templates/tests/pxc-test.yaml#L4
Pod name is generated randomly on every run.

**What you expected to happen**:
Subsequent usage of percona chart without changing values show no differences.

**How to reproduce it** (as minimally and precisely as possible):

Install chart.
Run `helm diff` without changing anything in values.

**Comment by maver1ck** [comment]
CC: @paulczar

**Comment by maver1ck** [comment]
Up

**Comment by viglesiasce** [comment]
Hey @maver1ck!

We talked this over in the Charts Chat today and think that the current behavior is the lesser of two evils. The way it is at the moment is a workaround for the fact that test pods don't get auto-generated names and cleaned up when re-running helm test. 

This behavior will be fixed in Helm 3.

**Comment by maver1ck** [comment]
Hey @viglesiasce 
I think I have workaround for this. What do you think about flag `testEnabled: true` ?

**Comment by maver1ck** [comment]
@viglesiasce 
One more comment. After finding this issue
https://github.com/helm/helm/issues/1920
I think that we can use not random names and having resources removed at the end of the test.
WDYT ?
