### ISSUE TITLE
[stable/redis-ha]

### ISSUE THREAD

**Issue by pentago** [helm/charts#7722]
**Is this a request for help?**:

Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Any

**Which chart**:
stable/redis-ha

**What happened**:
Upon successful installation, I can't connect to the cluster from my application.
Pointing application to `redis-redis-ha.default.svc.cluster.local` returns connection error and even trying to connect to it from the client on my OS doesn't work and all I get is:

> Could not connect to Redis at redis-redis-ha.default.svc.cluster.local:6379: Name does not resolve
Is this bug or am I doing something wrong?

**What you expected to happen**:
Successful connection to the cluster.

**How to reproduce it** (as minimally and precisely as possible):
Install cluster as per instructions and attempt connecting to the cluster as per notes/instructions.

**Anything else we need to know**:
N/A

**Comment by pentago** [comment]
cc @nickgryg @smileisak @ianmaddox

**Comment by nickgryg** [comment]
Is your application launched in the same kuberentes cluster where you deployed `redis-ha` helm chart?

**Comment by naseemkullah** [comment]
Hi @pentago 
Try installing the latest version of the chart, the NOTES have been fixed. There is no service of that name, the service you can connect to will either end in `-slave-svc` or `-master-svc`

If you do not want to reinstall, just try connecting to `redis-redis-ha-slave-svc.default.svc.cluster.local` or `redis-redis-ha-slave-master.default.svc.cluster.local`, it should work. :)

https://github.com/helm/charts/blob/master/stable/redis-ha/templates/NOTES.txt

**Comment by giacomoguiulfo** [comment]
Just as a side note, I wouldn't recommend you using the `redis-ha` as of right now. It has many problems and I will suggest you look into this refactor	#7323

**Comment by pentago** [comment]
Any chance this @giacomoguiulfo PR could get merged soon?

**Comment by giacomoguiulfo** [comment]
@pentago It looks like it should be getting merged soon.
