### ISSUE TITLE
Opportunistic packages - automatic email provisionning

### ISSUE THREAD

**Issue by pierreozoux** [helm/charts#774]
The idea is from [libre.sh](https://github.com/indiehosters/libre.sh/blob/master/ROADMAP.md#opportunistic-packages) which I created. (It is just a set of best practices around docker-compose, that I plan to migrate to k8s + helm)

## Problem to solve

In the context of a hoster, like Bitnami or IndieHosters, we need to ease the deployment of web application. These web applications need access to external services. Sometimes, these external services need to be configured specifically for the need of this application. So let's discuss about a concrete use case:

```
As a k8s user
I want to install WordPress
```

The basic use case is to let our WP to send emails.

So the problem would be: how an helm chart could claim an email for itself.
(And this could apply to piwik configuration, ldap configuration and so on)

## Possible solution for email

Create an Email third party resource.
```
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "A specification of an Email to manage."
metadata:
  name: "email"
versions:
  - name: v1
```

Create an Email controller that would watch this resource.

Let's take the example of Amazon SES.

Our process could understand AMAZON_API_KEYS env variables.
Then whenever there is a request for an email resource, our controller would request a mail from SES, and fill in the necessary params like:
 - MAIL_HOST
 - MAIL_PORT
 - MAIL_USER
 - MAIL_PASS

And then our chart would be able to understand that. And finally, WordPress would be able to send emails \o/.

## Opportunistic

I call this opportunistic as, if there is this thirdparty configured, it would make use of it, if not, just fall back to the default.

It is more at the exploration phase, understanding the needs, and then, if there is a consensus, start to work on it. Feedback would be appreciated.

Another nice to have would be to have a common way of configuring emails among applications.

**Comment by prydonius** [comment]
This sounds like a problem that the Kubernetes service catalog is trying to solve. Have you taken a look at the work going on over at https://github.com/kubernetes-incubator/service-catalog?

**Comment by pierreozoux** [comment]
I didn't know about it! Thanks for pointing into that direction! I'll close this issue then.
