### ISSUE TITLE
4.4.0.Final changes /opt/jboss to /opt/jboss/tools

### ISSUE THREAD

**Issue by stormmore** [helm/charts#7748]
https://github.com/helm/charts/blob/d0d95fc130dcca6cf86a59507d6963e87636a7ff/stable/keycloak/templates/configmap.yaml#L24 needs updating

**Comment by mborst** [comment]
Before someone else tries to tackle this in an isolated manner, see #7650.

**Comment by unguiculus** [comment]
Clsing this in favor of #8192.
