### ISSUE TITLE
[stable/kiam] Add a way of specifying extra volumes and mounts to the agent and server

### ISSUE THREAD

**Issue by saplla** [helm/charts#7754]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**Which chart**: stable/kiam

The agent can currently take `agent.extraHostPathMounts`. This is too restrictive and presumptive. I want to use cert-manager to create certs for Kiam. To do so I need to specify additional secret volumes, not host paths.

The Kiam chart could be improved by just stuffing in the contents of maps called `agent.extraVolumes` and `agent.extraVolumeMounts` in which users could specify whatever types of volumes and volume mounts they need, instead of only supporting host path volumes/mounts. The same issue affects the daemonset too.

**Comment by kgoralski** [comment]
is it possible to specify `agent.extraHostPathMounts` to use mounted secrets like this?
https://github.com/uswitch/kiam/blob/master/deploy/server.yaml#L49

**Comment by keithmattix** [comment]
Bump - did this functionality ever get added?
