### ISSUE TITLE
More documentation on redis configmap creation

### ISSUE THREAD

**Issue by billykwooten** [helm/charts#7770]
**Version of Helm and Kubernetes**:

Helm: v2.10.0
Kubernetes: v1.10.5

**Which chart**:
stable/redis

**What happened**:
Installed redis, but unable to configure configmap.

**What you expected to happen**:

I expected the following to work for creating the redis config via values.yaml:
```## Redis config file
##
configmap: |-
#  Redis configuration file
tcp-keepalive 300
tcp-keepalive 0
```

However, that errors out, setting the values to be yaml does not create a configmap.

**How to reproduce it** (as minimally and precisely as possible):

Try to create a configmap using redis values.yaml file.

**Anything else we need to know**:

Need more documentation. Configuring redis via flags is not sufficient. All my attempts at creating a configmap have failed for redis via the stable/redis helm chart.

**Comment by 27Bslash6** [comment]
+1 The following modification to configmap also results in failed deployments:
```yaml
configmap: |-
  maxmemory 200mb
  maxmemory-policy volatile-lfu
```

**Comment by ekhaydarov** [comment]
ive managed to get it working by having
```
configmap: |+
    protected-mode no
```
and making sure the start command args had the conf file path
```
args: ['redis-server', '/opt/bitnami/redis/etc/redis.conf']
```

these are all default in `stable/redis`

However, I agree some more documentation around redis configmaps would be great

**Comment by desaintmartin** [comment]
Actually, https://github.com/helm/charts/blob/master/stable/redis/templates/configmap.yaml#L13 lacks a "toYaml" to work properly without hack.

**Comment by desaintmartin** [comment]
I am not able to reproduce the issue, using stable/redis 4.2.10 and a custom values.yaml as:
```yaml
configmap: |-
  client-output-buffer-limit pubsub 32mb 8mb 60
  maxmemory 1gb
  maxmemory-policy noeviction
```

Then within the pod:
```
I have no name!@redis-master-0:/$ redis-cli config get maxmemory
1) "maxmemory"
2) "1073741824"
```

**Comment by juan131** [comment]
```
configmap: |-
  maxmemory 200mb
  maxmemory-policy volatile-lfu
```

Me neither.. Using the previous **configmap** parameter and running the commands below:

```
$ helm install stable/redis --name redis -f values.yaml
$ export REDIS_PASSWORD=$(kubectl get secret --namespace default redis -o jsonpath="{.data.redis-password}" | base64 --decode)
$ kubectl run --namespace default redis-client --rm --tty -i --restart='Never' \
>    --env REDIS_PASSWORD=$REDIS_PASSWORD \
>   --image docker.io/bitnami/redis:4.0.12 -- bash
I have no name!@redis-client:/$ redis-cli -h redis-master -a $REDIS_PASSWORD config get maxmemory
Warning: Using a password with '-a' option on the command line interface may not be safe.
1) "maxmemory"
2) "209715200"
I have no name!@redis-client:/$ redis-cli -h redis-master -a $REDIS_PASSWORD config get maxmemory-policy
Warning: Using a password with '-a' option on the command line interface may not be safe.
1) "maxmemory-policy"
2) "volatile-lfu"
```

**Comment by juan131** [comment]
When using a custom configmap, it's mounted at **/opt/bitnami/redis/etc** both in the master&slaves nodes as you can check in the links below:

https://github.com/helm/charts/blob/master/stable/redis/templates/redis-master-statefulset.yaml#L148
https://github.com/helm/charts/blob/master/stable/redis/templates/redis-master-statefulset.yaml#L170
https://github.com/helm/charts/blob/master/stable/redis/templates/redis-slave-deployment.yaml#L148
https://github.com/helm/charts/blob/master/stable/redis/templates/redis-slave-deployment.yaml#L158

The image used on this chart, uses the **redis.conf** mounted and skips the rest of configuration (replicacion included) when it detects it, check the logic below:

https://github.com/bitnami/bitnami-docker-redis/blob/master/5.0/debian-9/rootfs/libredis.sh#L311

Therefore, when using a custom configuration file, there's no way to configure master/slave configuration with the current approach. We should think about how to solve this, what do you think @javsalgar ?

**Comment by 27Bslash6** [comment]
Beep.

**Comment by xtof2all** [comment]
Any update on this issue?

**Comment by juan131** [comment]
No updates so far, sorry for the delay. We have it in our scope but we did not have time to work on a solution for this yet. 

We'll keep you updated as soon as we have more news! Thanks for your patience and understanding.

**Comment by 27Bslash6** [comment]
> Beep.

**Comment by juan131** [comment]
We still have the corresponding task in our backlog but I'm afraid there's no ETA to address it.

**Comment by 27Bslash6** [comment]
sigh
