### ISSUE TITLE
[stable/nginx-ingress] Empty controller.service.clusterIP should omit setting clusterIP in service

### ISSUE THREAD

**Issue by llb4ll** [helm/charts#7782]
BUG REPORT Empty controller.service.clusterIP should omit setting clusterIP in service

According to the kubernetes service documentation (https://kubernetes.io/docs/concepts/services-networking/service/#choosing-your-own-ip-address) clusterIP should be left out in case it should be auto-generated.

The current helm chart however defaults to an empty clusterIP field:
eg: https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-service.yaml
`spec:
clusterIP: "{{ .Values.controller.service.clusterIP }}"`

I think we should check if the value is set and only then add the `clusterIP` definition.

**Which chart**: [stable/nginx-ingress] 
**What happened**: Used the default helm command to generate the templates where all services have an empty ClusterIP set `clusterIP: ""`
**What you expected to happen**: The line `clusterIP: ""` is not there ;)
**How to reproduce it** (as minimally and precisely as possible): Run helm template and inspect the generated yamls.
**Anything else we need to know**: -

**Comment by acrom18** [comment]
I can confirm this behavior. @jackzampolin @mgoodness @chancez can one of you guys look into it?

**Comment by vreon** [comment]
See also #8221
