### ISSUE TITLE
[stable/fluent-bit] multiple Decode_Field_As fields for custom parsers

### ISSUE THREAD

**Issue by max-rocket-internet** [helm/charts#7791]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

I need this in my `parsers.conf`:

```
[PARSER]
    Name         docker
    Format       json
    Time_Key     time
    Time_Format  %Y-%m-%dT%H:%M:%S.%L
    Time_Keep    On
    # Command      |  Decoder | Field | Optional Action
    # =============|==================|=================
    Decode_Field_As   escaped_utf8    log    do_next
    Decode_Field_As   json       log
```

But it's not possible in the [current configmap](https://github.com/helm/charts/blob/master/stable/fluent-bit/templates/config.yaml#L137-L152) to have multiple `Decode_Field_As` fields.

**Which chart**:

`stable/fluent-bit`

**Comment by max-rocket-internet** [comment]
@kfox1111 @mattfarina

**Comment by max-rocket-internet** [comment]
Should I make a PR?

**Comment by mattfarina** [comment]
@max-rocket-internet sure, you can make a PR.

**Comment by max-rocket-internet** [comment]
I was able to get it working by enabling `mergeJSONLog` in values file.

**Comment by kfox1111** [comment]
see: https://github.com/helm/charts/blob/master/stable/fluent-bit/values.yaml#L87
