### ISSUE TITLE
Mongodb PersistentVolumeClaim

### ISSUE THREAD

**Issue by OpenSourceZombie** [helm/charts#7792]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

K8s
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
mongodb

**What happened**:
When you install and then remove the chart the PersistentVolumeClaim does not get removed during the deletion.

**What you expected to happen**:
The PersistentVolumeClaim get deleted when I use `helm delete --prune my-release`

**How to reproduce it** (as minimally and precisely as possible):
`helm install --name my-release --set replicaSet.enabled=true --set replicaSet.name=hl  --set persistence.storageClass=gp2  --set persistentVolume.enabled=true stable/mongodb`

`helm delete --prune my-release`

**Anything else we need to know**:
I didn't enable the k8s dynamic volume provisioning at first, and then enabled it and remove and reinstalled chart but the claim was still there but the old claim was still there.

**Comment by ssalaues** [comment]
If I'm understanding this correctly, it sounds like you're describing the expected behavior of the StatefulSet "Limitations" as seen here: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations

> Deleting and/or scaling a StatefulSet down will not delete the volumes associated with the StatefulSet. This is done to ensure data safety, which is generally more valuable than an automatic purge of all related StatefulSet resources.

**Comment by giacomoguiulfo** [comment]
This is a feature, not a bug. In fact, it is a very desired behavior and the reason why some charts have been (or seek) to be ported from `Deployments` to `StatefulSets`.

**Comment by OpenSourceZombie** [comment]
Aha, I thought it's something stable/mongodb chart specific.

Thank you so much for your feedback, I'm closing it now
