### ISSUE TITLE
Unable to submit spark application through zeppelin IDE with spark standalone cluster as cluster manager

### ISSUE THREAD

**Issue by rkkrishnaa** [helm/charts#7811]
**Is this a request for help?**:

request

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

Helm version: 2.11.0
Kubernetes version: 1.8.1

**Which chart**:

spark

**What happened**:

I have deployed a spark standalone cluster from the helm chart available in this repository. I can access zeppelin IDE and spark master web UI from my local network. 

I executed a sample spark job through zeppelin. I used spark interpreter and created a notebook for running my program. I can execute spark jobs in local mode. But I intend to run this job with a cluster manager. I have modified the interpreter settings to refer our spark standalone cluster to act as a cluster manager for scheduling and managing spark application.

As usual I have updated the spark master as **spark://spark-master-service-name:7077**  from spark interpreter settings, restarted interpreter and executed the job. Zeppelin is not able to communicate with the spark master and the job is killed automatically. 

Initially, I suspected that the problem is due to the lack of communication between master and zeppelin pods. Later I came to know that spark is working fine with spark standalone cluster as a cluster manager when I execute the job from zeppelin pods. Here, I have mounted the spark binaries in zeppelin pod as same as worker pods and executed the job against spark master. It is communicating with cluster manager. Job scheduling is happening correctly as expected. Able to track the job from spark master web UI.

I have checked out zeppelin pod logs when I running my spark job from zeppelin with spark master as cluster manager. Please find the log message given below.

**ERROR actor.OneForOneStrategy: Error while decoding incoming Akka PDU of length: 1305
akka.remote.transport.AkkaProtocolException: Error while decoding incoming Akka PDU of length: 1305
Caused by: akka.remote.transport.PduCodecException: Decoding PDU failed.**
 
I have checked out the root cause of the problem from diffferent forums. They are stating that it might due to version compatibility between zeppelin ide version and spark version. Have you tested running spark jobs through zeppelin IDE with spark standalone cluster. Besides, I have checked the version compatibility of zeppelin wrt to spark. Even older version of Zeppelin has support to run spark up to version 2.0.0. Let me upgrade the spark and zeppelin version any way and try to run the job.

Please share the solution with me if you have already tested this option. The reason I am asking is I would like to utilise the resources from  worker pods and want to run this job in a distributed environment. 

**What you expected to happen**:

Need to submit spark jobs from zeppelin using spark standalone cluster as a cluster manager.

**How to reproduce it** (as minimally and precisely as possible):

1. Install spark helm chart. 
2. Open zeppelin IDE and create a notebook with spark as an interpreter
3. Run any spark program(scala)
4. Modify the spark interpreter settings and update spark master endpoint
5. Restart the interpreter and execute the job.
 
**Anything else we need to know**:

**Comment by rkkrishnaa** [comment]
Any updates?

**Comment by dNetGuru** [comment]
I'm running into the exact same issue.

**Comment by dbanda** [comment]
@dNetGuru @rkkrishnaa My PR solves this issue https://github.com/helm/charts/pull/11285
#11285 
Check it out and maybe we can get someone to review it
