### ISSUE TITLE
Chart for k8s-snapshots

### ISSUE THREAD

**Issue by andrewhowdencom** [helm/charts#783]
The following utility is a useful tool to automate snapshots of persistent volumes: 

https://github.com/miracle2k/k8s-snapshots

I have created a chart for this tool with (what I think are) sane defaults. Is this something that can be contributed to this repository?

Cheers.

**Comment by seanknox** [comment]
Hi @andrewhowdencom, this looks useful for the community at large at first glance. Feel free to open a PR and we can discuss further. Thanks!

**Comment by bhack** [comment]
Any pr?

**Comment by tewing-riffyn** [comment]
Was k8s-snapshots ever placed into a helm chart?  I have a sudden requirement for AWS EBS snapshotting and am hoping to find this tool already packaged into a chart.

**Comment by bhack** [comment]
https://kubernetes.io/blog/2018/10/09/introducing-volume-snapshot-alpha-for-kubernetes/

**Comment by cpanato** [comment]
I can create the chart, if there is interest on it
