### ISSUE TITLE
[incubator/fluentd-cloudwatch] permission denied error

### ISSUE THREAD

**Issue by neilhwatson** [helm/charts#7833]
**Is this a request for help?**:

Maybe

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

EKS 1.10.3
Helm 2.10

**Which chart**:

fluentd-cloudwatch-0.5.1

**What happened**:

Permission denied error:

```
   2018-09-19 15:22:36 +0000 [error]: unexpected error error_class=Errno::EACCES error=#<Errno::EACCES: Permission denied @ rb_sysopen - /var/log/fluentd-containers.log.pos>
```

**What you expected to happen**:

To see a cloudwatch 'kuberenets' logroup.

**How to reproduce it** (as minimally and precisely as possible):

```
   helm install --name fluentd-cloudwatch incubator/fluentd-cloudwatch \
      --namespace kube-system --set rbac.create=true --set awsRegion=us-west-2 \
      --wait
```

**Anything else we need to know**:

**Comment by neilhwatson** [comment]
Even if I use the suggested extra vars ```"{ name: FLUENT_UID, value: '0' }"``` the problem persists. Further, the get values suggest the extra vars are not parsed correctly:

```
$ helm get values fluentd-cloudwatch
awsRegion: us-west-2
extravars:
- ' name: FLUENT_UID'
- ' value: ''0'' '
rbac:
 create: true
```

**Comment by swibrow** [comment]
@neilhwatson As the reply I sent on slack, the extra vars should be added like it is in the readme. 
```
extraVars:
  - "{ name: FLUENT_UID, value: '0' }"
```

**Comment by neilhwatson** [comment]
That does seem to work. The readme is unclear. I tried to set the extra vars with the set option, and that did fail. So --values works and --set extravars'"{..}" fails.

**Comment by abhizersaifee80** [comment]
Getting below error while setting FLUENT_UID to 0.

> helm install --name fluentd incubator/fluentd-cloudwatch --set awsRegion=eu-west-1,rbac.create=true --set extraVars[0]="{ name: FLUENT_UID, value: '0' }"

Error: YAML parse error on fluentd-cloudwatch/templates/daemonset.yaml: error converting YAML to JSON: yaml: line 38: did not find expected ',' or ']'
