### ISSUE TITLE
[incubator/kafka] SSL documentation

### ISSUE THREAD

**Issue by caiobegotti** [helm/charts#7864]
**Is this a request for help?**:

Hard to say

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

```
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.2", GitCommit:"384b4eaa132ca9a295fcb3e5dfc74062b257e7df", GitTreeState:"clean", BuildDate:"2018-08-15T00:10:14Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

[incubator/kafka]

**What happened**:

Chart does not have a clear documentation on how to run it with SSL, only in an insecure way by default, without any example configuration or settings. Users have to figure out how the chart was developed and what options it does support to enable SSL, at all. The env var and mounted files option is a bit confusing too.

**What you expected to happen**:

The `secrets` option is not even documented in the instructions printed during the chart setup...

**Anything else we need to know**:

Running Kafka without SSL should be considered insecure and stated in the README of the chart, if this bug cannot be fixed with some documentation love 😥

**Comment by Arkoprabho** [comment]
Was this issue fixed? I cant find better documentation than #3951. @caiobegotti Did you manage to get SSL working on Kafka using this chart?

**Comment by amitsadafule** [comment]
Anyone was able to setup it with SSL? I can't still figure out good documentation about how to enable it

**Comment by amitsadafule** [comment]
In case anybody wants to setup SSL auth, I have documented the steps on below link
https://medium.com/inspiredbrilliance/helm-incubator-kafka-setup-with-ssl-auth-7cf6fbe333d4
