### ISSUE TITLE
[stable/jenkins] json parsing errors when including jobs

### ISSUE THREAD

**Issue by remmeier** [helm/charts#7865]
This is a BUG REPORT.

**Version of Helm and Kubernetes**:

Helm 2.9.1 with Kubernetes 1.9. Managed Kubernetes on Google Cloud.

**Which chart**:

stable/jenkins

**What happened**:

I defined my own jobs in the values.yaml file for inclusion. But when executing "helm template" of the chart, I got:

```
/charts/jenkins/templates/jobs.yaml" at <2>: wrong type for value; expected string; got map[string]interface {}
```

**What you expected to happen**:

The jobs to be included.

**Anything else we need to know**:

The problem is fixed by updating the jobs.yaml to:

```
{{ toYaml .Values.Master.Jobs | indent 2 }}
```

The `toYaml` seems to properly convert types and the job inclusion works as expected.

**Comment by scottrigby** [comment]
Reopening, as it's no longer stale via #9004
