### ISSUE TITLE
[stable/jenkins] allow to override jobs

### ISSUE THREAD

**Issue by remmeier** [helm/charts#7880]
FEATURE REQUEST stable/jenkins

The Jenkins Helm chart provides the means to bundle job config.xml with the Helm chart. However, so far it is not possible to update them along with a new version. Reason is within apply_config.sh due the use of `-n` in ` cp -n /var/jenkins_jobs/$job /var/jenkins_home/jobs/$job/config.xml`. Similar to `.Values.Master.OverwriteConfig` there should be a `.Values.Master.OverwriteJobs` to allow the update of jobs.

**Comment by remmeier** [comment]
thx for the fix. However, the commit seems to have accidently fixed https://github.com/helm/charts/issues/7866 while this one is unresolved.

For the fix here it would be great to have:

```
{{- if .Values.Master.Jobs }}
    for job in $(ls /var/jenkins_jobs); do
      mkdir -p /var/jenkins_home/jobs/$job
      cp {{- if .Values.Master.OverwriteJobs }}-n{{- end }} /var/jenkins_jobs/$job /var/jenkins_home/jobs/$job/config.xml
    done
{{- end }}
```

if there is a desire to have this fix. For a newbie it is at first sight not directly obvious how the chart is behaving and the expectation may rather be for jobs to get updated.

There could be two potential other things to make customizable:

- setting a serviceAccount for agents
- setting environment variables for agents

But not sure how far the chart would like to go in terms of customizablity since it is possible to provide the entire (but rather large) template.

**Comment by hpurmann** [comment]
@remmeier We ran into the same problem, thus I created https://github.com/helm/charts/pull/12427 for it.
