### ISSUE TITLE
[stable/grafana] Pod fails to start when plugins are configured to install

### ISSUE THREAD

**Issue by tardoe** [helm/charts#7905]
**Version of Helm and Kubernetes**:
Kubernetes: 1.10.3
Helm: 2.10.0

**Which chart**:
stable/grafana with grafana 5.2.4

**What happened**:
Deployed with the plugins section uncommented in the values.yaml file listing the basic clock plugin.

**What you expected to happen**:
Grafana deploys with the plug installed.

**How to reproduce it** (as minimally and precisely as possible):
Ensure this section is present in your values.yaml file when passed to the deployment.
```
## Pass the plugins you want installed as a list.
##
plugins: 
  - grafana-clock-panel
```
The following is shown on the pod as it crash-loops:
```
Failed to send requesterrorApi returned invalid status: 404 Not Found
Error: ✗ Failed to send request. error: Api returned invalid status: 404 Not Found
 NAME:
   Grafana cli plugins install - install <plugin id> <plugin version (optional)>
 USAGE:
   Grafana cli plugins install [arguments...]
```

**Anything else we need to know**:
Launching the deployment without any plugins is successful. The plugin can be installed manually while exec'd into the container:
```
grafana@grafana-666568d4cf-fhqz6:/$ grafana-cli plugins install grafana-clock-panel
installing grafana-clock-panel @ 0.1.0
from url: https://grafana.com/api/plugins/grafana-clock-panel/versions/0.1.0/download
into: /var/lib/grafana/plugins

✔ Installed grafana-clock-panel successfully 

Restart grafana after installing plugins . <service grafana-server restart>
```

**Comment by tabbabi** [comment]
same problem with zabbix plugin !

**Comment by camilorivera** [comment]
not only for grafana but for all of them

**Comment by icook** [comment]
Ran into this problem, the solution is simple. The value of `plugins` in yaml must be a string, not a list. This is because it gets stringified and passed as an enviroment variable. Lists interpolate to `[grafana-clock-panel, grafana-piechart-panel]`, not `grafana-clock-panel,grafana-piechart-panel` as expected. Don't do:

``` yaml
## Pass the plugins you want installed as a list.
##
plugins: 
  - grafana-clock-panel
```

Instead

``` yaml
## Pass the plugins you want installed as a comma separated string.
##
plugins: "grafana-clock-panel"
```

**Comment by kolesoffac** [comment]
I use:
```
plugins:
  - grafana-clock-panel
  - digrich-bubblechart-panel
  - grafana-worldmap-panel
  - grafana-piechart-panel
  - briangann-gauge-panel
```
in log:
```
installing grafana-clock-panel @ 1.0.0
from url: https://grafana.com/api/plugins/grafana-clock-panel/versions/1.0.0/download
into: /var/lib/grafana/plugins
 ✔ Installed grafana-clock-panel successfully 
 Restart grafana after installing plugins . <service grafana-server restart>
 installing digrich-bubblechart-panel @ 1.1.0
from url: https://grafana.com/api/plugins/digrich-bubblechart-panel/versions/1.1.0/download
into: /var/lib/grafana/plugins
```
Wrong in _digrich-bubblechart-panel_. If i remove _digrich-bubblechart-panel_ then all plugins installed.

**Comment by zmailloux** [comment]
> Ran into this problem, the solution is simple. The value of `plugins` in yaml must be a string, not a list. This is because it gets stringified and passed as an enviroment variable. Lists interpolate to `[grafana-clock-panel, grafana-piechart-panel]`, not `grafana-clock-panel,grafana-piechart-panel` as expected. Don't do:
> 
> ```yaml
> ## Pass the plugins you want installed as a list.
> ##
> plugins: 
>   - grafana-clock-panel
> ```
> 
> Instead
> 
> ```yaml
> ## Pass the plugins you want installed as a comma separated string.
> ##
> plugins: "grafana-clock-panel"
> ```

This didn't didn't solve the problem for me, still seeing the same error message.

**Comment by arilwan** [comment]
Facing same problem here. Grafana was running smoothly until very recently, don't understand the reason. The solution suggested above didn't work  for me. Grafana definition;
```
grafana:
    restart: always
    image: grafana/grafana
    container_name: fiware-grafana
    depends_on:
      - postgres
    ports:
      - "53153:3000"
    environment:
      - GF_INSTALL_PLUGINS=crate-datasource,grafana-clock-panel,grafana-worldmap-panel
    volumes:
      - ./grafana:/var/lib/grafana:rw

```

**Comment by tazchalmers** [comment]
> Facing same problem here. Grafana was running smoothly until very recently, don't understand the reason. The solution suggested above didn't work for me. Grafana definition;
> 
> ```
> grafana:
>     restart: always
>     image: grafana/grafana
>     container_name: fiware-grafana
>     depends_on:
>       - postgres
>     ports:
>       - "53153:3000"
>     environment:
>       - GF_INSTALL_PLUGINS=crate-datasource,grafana-clock-panel,grafana-worldmap-panel
>     volumes:
>       - ./grafana:/var/lib/grafana:rw
> ```

arilwan - did you be sure to change:
 - GF_INSTALL_PLUGINS=
to:
plugins: 
?
Initially I skimmed zmailloux solution and only added quotes to:
- GF_INSTALL_PLUGINS="crate-datasource,grafana-clock-panel,grafana-worldmap-panel"
failed. I then looked closer at the solution and changed to: 
plugins: "crate-datasource,grafana-clock-panel,grafana-worldmap-panel"
and Grafana works once again

**Comment by arilwan** [comment]
I didn't change anything, my grafana service definition (in compose file) is shown above, exactly as it is.

**Comment by tazchalmers** [comment]
> I didn't change anything, my grafana service definition (in compose file) is shown above, exactly as it is.

my grafana service definition matched yours but only because I changed this:
`- GF_INSTALL_PLUGINS="crate-datasource,grafana-clock-panel,grafana-worldmap-panel"`
to this:
`plugins: "crate-datasource,grafana-clock-panel,grafana-worldmap-panel"`
in docker-compose.yml and Grafana works once again

**Comment by arilwan** [comment]
@tazchalmers 
Ah, you're right, grafana works now.

**Comment by bhagujava** [comment]
> > I didn't change anything, my grafana service definition (in compose file) is shown above, exactly as it is.
> 
> my grafana service definition matched yours but then I changed this:
> `- GF_INSTALL_PLUGINS="crate-datasource,grafana-clock-panel,grafana-worldmap-panel"`
> to this:
> `plugins: "crate-datasource,grafana-clock-panel,grafana-worldmap-panel"`
> in docker-compose.yml, and Grafana works once again

After changing     ```` plugins= "crate-datasource,grafana-clock-panel,grafana-worldmap-panel"```` i could not able to see crate-datasource in grafana

**Comment by tazchalmers** [comment]
> > > I didn't change anything, my grafana service definition (in compose file) is shown above, exactly as it is.
> > 
> > 
> > my grafana service definition matched yours but then I changed this:
> > `- GF_INSTALL_PLUGINS="crate-datasource,grafana-clock-panel,grafana-worldmap-panel"`
> > to this:
> > `plugins: "crate-datasource,grafana-clock-panel,grafana-worldmap-panel"`
> > in docker-compose.yml, and Grafana works once again
> After changing ` plugins= "crate-datasource,grafana-clock-panel,grafana-worldmap-panel"` i could not able to see crate-datasource in grafana
@bhagujava try changing the `=` to a `:` so it is `plugins:` not `plugins=`

**Comment by bhagujava** [comment]
There is no official plugin available for crate 
This one work for me 

````   
environment:
  - GF_INSTALL_PLUGINS=https://github.com/raintank/crate-datasource/archive/master.zip;crate-datasource,grafana-clock-panel,grafana-worldmap-panel,natel-plotly-panel
 ````

For more details [https://stackoverflow.com/questions/56651482/grafana-adding-plotly-plugin-via-docker-compose](url)

**Comment by bhagujava** [comment]
> > > > I didn't change anything, my grafana service definition (in compose file) is shown above, exactly as it is.
> > > 
> > > 
> > > my grafana service definition matched yours but then I changed this:
> > > `- GF_INSTALL_PLUGINS="crate-datasource,grafana-clock-panel,grafana-worldmap-panel"`
> > > to this:
> > > `plugins: "crate-datasource,grafana-clock-panel,grafana-worldmap-panel"`
> > > in docker-compose.yml, and Grafana works once again
> > > After changing ` plugins= "crate-datasource,grafana-clock-panel,grafana-worldmap-panel"` i could not able to see crate-datasource in grafana
> > > @bhagujava try changing the `=` to a `:` so it is `plugins:` not `plugins=`

I am getting 
````
services.grafana.environment contains {"plugins": "crate-datasource,grafana-clock-panel,grafana-worldmap-panel"}, which is an invalid type, it should be a string
````

**Comment by tazchalmers** [comment]
> > > > > I didn't change anything, my grafana service definition (in compose file) is shown above, exactly as it is.
> > > > 
> > > > 
> > > > my grafana service definition matched yours but then I changed this:
> > > > `- GF_INSTALL_PLUGINS="crate-datasource,grafana-clock-panel,grafana-worldmap-panel"`
> > > > to this:
> > > > `plugins: "crate-datasource,grafana-clock-panel,grafana-worldmap-panel"`
> > > > in docker-compose.yml, and Grafana works once again
> > > > After changing ` plugins= "crate-datasource,grafana-clock-panel,grafana-worldmap-panel"` i could not able to see crate-datasource in grafana
> > > > @bhagujava try changing the `=` to a `:` so it is `plugins:` not `plugins=`
> 
> I am getting
> 
> ```
> services.grafana.environment contains {"plugins": "crate-datasource,grafana-clock-panel,grafana-worldmap-panel"}, which is an invalid type, it should be a string
> ```
> 
> This is my docker-compose configuration
> 
> ```
>   grafana:
>     image: grafana/grafana:latest
>     container_name: grafana
>     user: "104"
>     depends_on:
>       - prometheus
>     ports:
>       - 3000:3000
>     environment:
>       - GF_USERS_ALLOW_SIGN_UP=true
>       - plugins: "crate-datasource,grafana-clock-panel,grafana-worldmap-panel"
> ```

Try removing the - in front of plugins and making sure the indents are correct. The beginning of my docker-compose configuration is:

```
version: '3'
services:
  grafana:
    image: grafana/grafana:6.1.6
    depends_on:
      - crate
    environment:
      plugins: "crate-datasource,grafana-clock-panel,grafana-worldmap-panel"
```

**Comment by bhagujava** [comment]
I am using version 3.1 docker-compose

**Comment by ASangave** [comment]
> There is no official plugin available for crate
> This one work for me
> 
> ```
> environment:
>   - GF_INSTALL_PLUGINS=https://github.com/raintank/crate-datasource/archive/master.zip;crate-datasource,grafana-clock-panel,grafana-worldmap-panel,natel-plotly-panel
> ```
> 
> For more details [https://stackoverflow.com/questions/56651482/grafana-adding-plotly-plugin-via-docker-compose](url)

Even I want to install sysdig plugin for grafana which is not yet available on official & community built plugin page. So it needs to be installed manually but adding just below lines to values doesn't install this plugin inside grafana. Any idea??
env :
   GF_INSTALL_PLUGINS: "https://download.sysdig.com/stable/grafana-sysdig-datasource/grafana-sysdig-datasource-v0.7.zip;sysdig"
