### ISSUE TITLE
[stable/traefik] dashboard does not run on gke

### ISSUE THREAD

**Issue by hans-d** [helm/charts#7912]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.10
Kubernetes Server: v1.10.6-gke.2
Kubernetes Client: v1.11.2

**Which chart**:
stable/traefik

**What happened**:
Dashboard cannot run on GKE: `Error during sync: error while evaluating the ingress spec: service "example-ingress/traefik-controller-dashboard" is type "ClusterIP", expected "NodePort" or "LoadBalancer"`

**What you expected to happen**:
Dashboard to be deployed without issues

**How to reproduce it** (as minimally and precisely as possible):
Run on GKE
Use option: `dashboard.enabled: true`

**Anything else we need to know**:
Found on clean GKE cluster, where traefik is the only cluster controller installed

Manual intervention that provided results
- Updated the dashboard service to be of `kind: NodePort`
- Remove the dashboard ingress
- Redeployed using helm

**Comment by gd-jroberts** [comment]
I'm experiencing this issue as well in clusters using Traefik, both 1.6.6 and 1.7.1. Routes that had been created fine are now showing this error when they are updated.

Helm: 2.10.0
Kubernetes Server: 1.10.6-gke.2
Kubernetes Client: 1.12.0
