### ISSUE TITLE
[incubator/logstash] Provide a Way to Specify JVM Heap Size

### ISSUE THREAD

**Issue by chenchik** [helm/charts#7930]
**Is this a request for help?**:

yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

helm:
```
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```

kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:30:22Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.2", GitCommit:"384b4eaa132ca9a295fcb3e5dfc74062b257e7df", GitTreeState:"clean", BuildDate:"2018-08-15T00:10:14Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

 [incubator/logstash]

**What happened**:

I'd like to change the JVM Heap size using the helm chart, but the values file doesn't provide a way to do so. Also using the environment variable LS_JAVA_OPTS doesn't allow you to deploy the container with increased JVM Heap sizes.

**What you expected to happen**:

I would expect passing in the LS_JAVA_OPTS environment variable would allow you to change the JVM heap size, but it doesn't seem to. 

I'd also expect there to be a way to change the heap size using the helm chart, similar to [incubator/elasticsearch].

**How to reproduce it** (as minimally and precisely as possible):

`helm install --name logstash incubator/logstash --namespace logging -f custom.values.yaml`

Use the following values inside of custom.values.yaml:
```
  config:
    ls.java.opts: "-Xmx4g -Xms2g"
  resources:
    limits:
      memory: 8Gi
    requests: 
      memory: 8Gi
  replicaCount: 2
```

**Anything else we need to know**:

**Comment by abhishekjiitr** [comment]
Verified that it is working by passing LS_JAVA_OPTS environment variable through _config_ section in _values.yaml_

```
config:
  ls.java.opts: "-Xmx2g -Xms2g"
```
