### ISSUE TITLE
[stable/percona-xtradb-cluster] SSL support in stable/percona-xtradb-cluster

### ISSUE THREAD

**Issue by jaypipes** [helm/charts#7931]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature Request

**Version of Helm and Kubernetes**:

All

**Which chart**:

Percona-XtraDB-Cluster

**Feature Request**:

The stable/mysql chart has support for starting the MySQL server with SSL support:

https://github.com/helm/charts/blob/dafdf97d0c992ed85b3ce43476164c8ce3f93c92/stable/mysql/values.yaml#L134-L150

It would be awesome to have the stable/percona-xtradb-cluster Helm chart support the same options in the my.cnf. Alternately, just having some documentation on how to do the needful w.r.t. injecting my.cnf values for SSL options securely at helm install time would be useful.

**Comment by jgleonard** [comment]
+1 for this request.
