### ISSUE TITLE
[stable/redis] Would it be possible to implement deployment to use Sentinels for genuine HA?

### ISSUE THREAD

**Issue by pentago** [helm/charts#7968]
**FEATURE REQUEST**

Would it be possible to implement Redis Sentinels for genuine HA as current [redis-ha chart](https://github.com/helm/charts/tree/master/stable/redis-ha) isn't really production ready and has some drawbacks which require it to be refactored and there's almost no response from the developer side.

We could have one, single redis chart which could be configured to be HA (by using multiple replicas with Sentinels) or single-instance deployment if just one replica is desired.

Thoughts?

**Version of Helm and Kubernetes**:
Any

**Which chart**:
stable/redis-ha

**Comment by ssalaues** [comment]
@pentago Check out my PR! I'm made many necessary changes (turned into a refactor) to make the redis-ha chart genuinely HA and removes all external dev dependency so all changes can be made through the helm repo.
https://github.com/helm/charts/pull/7323

**Comment by pentago** [comment]
I did, can't wait for it to be merged.

**Comment by pentago** [comment]
Not stale.

**Comment by pentago** [comment]
Thanks a ton! Can't wait to test chart.
