### ISSUE TITLE
[stable/cockroach] Init container throws error (cluster already exists) when restoring the cluster

### ISSUE THREAD

**Issue by vidhy** [helm/charts#7972]
**Is this a request for help?**:
YES
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG 

**Version of Helm and Kubernetes**:
Helm
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Kubernetes
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/cockroach

**What happened**:
following error is being thrown continuosly in the init container.
```
+ /cockroach/cockroach init --insecure --host=my-release-0-cockroachdb-0.my-release-0-cockroachdb
E180925 18:11:09.336427 1 cli/error.go:112  rpc error: code = AlreadyExists desc = cluster has already been initialized with ID e9df292b-55cc-4f1c-bfb7-9370b8a51dc4
Error: rpc error: code = AlreadyExists desc = cluster has already been initialized with ID e9df292b-55cc-4f1c-bfb7-9370b8a51dc4
Failed running "init"
+ sleep 5
```

**What you expected to happen**:
Cluster Init container to get into completed state if the cluster already exists.

**How to reproduce it** (as minimally and precisely as possible):
Create a cockroach cluster with persistant storage. Helm delete the release (keeping the pvc). When installing again, the same persistant volumes are used restoring the cluster. hence cluster init throws error.

**Comment by prashant182** [comment]
@vidhy I don't work for cockroachdb team, but I have been using their helmchart extensively. Isn't that the expected behavior? if Persistent storage exists that means cluster was already initialized and you can just delete the db-init job. What were you expecting from this chart?
