### ISSUE TITLE
Keycloak chart - values yaml hides postgressql.persistence.enabled set to false. Should allow user to override

### ISSUE THREAD

**Issue by enenum** [helm/charts#7975]
**Is this a request for help?**:
no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): I think its a bug

**Version of Helm and Kubernetes**:
Helm: v2.9.1
K8s: v1.10.4

**Which chart**:
stable/keycloak

**What happened**:
deploy with postgres - won't use persistent volume for database. The chart has postgressql.persistence.enabled hard wired to false. Overridding in passed in values.yaml does nothing. Chart should expose value to user to set.

**What you expected to happen**:
I expect to set the flag in the overriding values.yaml and it to take effect.

**How to reproduce it** (as minimally and precisely as possible):
Set keycloak.persistence.deployPostgres=true in overridding yaml to let keycloak setup postgres. Postgres is setup alright, but not with persistent volume. The logic in stable/keycloak/templates/_helpers.tpl does

**Anything else we need to know**:

**Comment by unguiculus** [comment]
I just tested this again and it works as expected. If you set `postgressql.persistence.enabled=true` you get a PVC. This is BTW not the Keycloak chart's reponsibility. This is handled by the Postgres chart the Keycloak chart depends on.
