### ISSUE TITLE
[stable/jenkins] Random podname makes helm diff useless

### ISSUE THREAD

**Issue by henrikb123** [helm/charts#7979]
BUG REPORT 

**Version of Helm and Kubernetes**:
Helm 2.11.0
Kubernetes 1.8.15
Helm diff 2.10.0+1

**Which chart**:
stable/jenkins

**What happened**:
After upgrading from Helm 2.9.1 helm diff started to always report helm diffs between a deployed release and the chart/value files although nothing has changed.

**What you expected to happen**:
helm diff should not produce any output if nothing changed.

**How to reproduce it** (as minimally and precisely as possible):
-- Fresh install
helm upgrade --install --values abc.yaml my-release /path/to/stable/jenkins 
-- diff with exact same settings
helm diff upgrade --values abc.yaml my-release /path/to/stable/jenkins 

Output:
metatest, metatest-ui-test-qufuk, Pod (v1) has been removed: 
lots of text
metatest, metatest-ui-test-ey02f, Pod (v1) has been added:
lots of text

Reason being this line in jenkins-test.yaml:
name: "{{ .Release.Name }}-ui-test-{{ randAlphaNum 5 | lower }}"

**Comment by madAndroid** [comment]
We're experiencing the same issue - the `randAlphaNum` causes the test pod diff to be picked up on every run

**Comment by alecrubindev** [comment]
Having the same issue, any updates on this?
