### ISSUE TITLE
[stable/spinnaker] Is there any way to deploy without minio and redis?

### ISSUE THREAD

**Issue by atrauzzi** [helm/charts#7989]
I'd love to see the option to (and some light guidance for) installing this chart, but without having to take on Redis and/or Minio.  My reason being I plan on using an Azure Storage account for persistence.

**Version of Helm and Kubernetes**: N/A
**Which chart**: stable/spinnaker
**What happened**: Redis and minio are added to my cluster.
**What you expected to happen**: An option to prevent them from being installed and configured.
**How to reproduce it** (as minimally and precisely as possible): Go through default installation steps.

**Comment by nagonzalez** [comment]
Found this link in the Spinnaker slack channel:
https://www.spinnaker.io/setup/productionize/caching/externalize-redis/

As far as minio, you should be able to disable it in `values.yaml`:
https://github.com/helm/charts/blob/0a5ddac35d7e1a8820f3edb5198a648f706146ef/stable/spinnaker/values.yaml#L94

and configure your Azure particulars here:
https://www.spinnaker.io/setup/install/storage/azs/

**Comment by dpkirchner** [comment]
FYI for future searchers: Disabling minio in values.yaml won't disable minio deployment/STS installation, it just prevents minio use.
