### ISSUE TITLE
Change format of existing dm templates

### ISSUE THREAD

**Issue by sebgoa** [helm/charts#8]
update format of existing dm templates to new format

**Comment by jackgr** [comment]
Please move this issue to the kubernetes/helm repo.

**Comment by jackgr** [comment]
@runseb a quick scan of the charts suggests that most if not all of the existing dm templates have been converted into the new chart format. Can this issue now be closed?

**Comment by prydonius** [comment]
Closing this as charts have been cleared as of #18
