### ISSUE TITLE
create a drone.io chart

### ISSUE THREAD

**Issue by bacongobbler** [helm/charts#800]
Tracking this ticket for my own sake. We have a drone 0.5 cluster running on GKE. I'd like to package this into a usable `incubator/drone` package so others can install Drone on their kubernetes clusters.

**Comment by linki** [comment]
For reference, there's an open PR here: https://github.com/kubernetes/charts/pull/353.

I created a simpler version a couple of weeks ago:
https://github.com/linki/charts/blob/drone/incubator/drone

**Comment by bacongobbler** [comment]
thanks @linki! I guess we can consider this closed once there's a drone chart in the incubator since there doesn't seem to be any other ticket tracking this effort. :)

**Comment by seanknox** [comment]
Closing as we have your fine PR in progress...!
