### ISSUE TITLE
Pods does not create - status ContainerCreating for long time

### ISSUE THREAD

**Issue by iyappan-dcis** [helm/charts#8010]
**Is this a request for help?**:
Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
kubernetes - 1.11.2
Helm: 2.10.0

**Which chart**:
stable/wordpress

**What happened**:
Created deployment in both ways, 1. using values.yaml and 2. default command but the status of pods shows ContainerCreating for more than 2 hours. Tried different ways like excluding mariadb (providing a external database) but still the same issue. Please help

**What you expected to happen**:
Expect the pods to be created

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by marcadella** [comment]
Might be related to https://github.com/helm/charts/issues/14014
