### ISSUE TITLE
add storageClass.mountOption as configurable value

### ISSUE THREAD

**Issue by kmkramer** [helm/charts#8016]
**Is this a request for help?**:
no

FEATURE REQUEST
add storageclass.mountOptions as a configurable option

**Version of Helm and Kubernetes**:
2.9.1
1.11.2
on Rancher RKE provisioned but this shouldn't matter. I can use helm charts in here as well.

**Which chart**:
nfs-client-provisioner

**What happened**:
For my nfs export to work as a volume, I'm having to specify some mount options and I can't do those with the nfs-client-provisioner.

**What you expected to happen**:
be able to utilize storageClass mountOption so that volumes inherit them at mount time from the class.

**How to reproduce it** (as minimally and precisely as possible):
https://kubernetes.io/docs/concepts/storage/storage-classes/#the-storageclass-resource

> ..Persistent Volumes that are dynamically created by a storage class will have the mount options specified in the mountOptions field of the class.
If the volume plugin does not support mount options but mount options are specified, provisioning will fail. Mount options are not validated on either the class or PV, so mount of the PV will simply fail if one is invalid..." 

**Anything else we need to know**:
I don't think so

**Comment by treksler** [comment]
please see/test https://github.com/treksler/charts/tree/master/stable/nfs-client-provisioner

eg.
 helm install --name nfs-client --set nfs.server=my.server.com --set nfs.path=/mypath --set storageClass.defaultClass=true --set mountOptions="{nolock\\,sync}" .

**Comment by kmkramer** [comment]
It does not appear to be working.  I also have found that I cannot change storageclassName and thus cannot create multiple objects. Let me know what logs you need from me.

**Comment by treksler** [comment]
there is a typo in the README. 
it is supposed to be storageClass.name not storageclass.name
I have fixed it.

I also today changed mountOptions to storageClass.mountOptions
eg.
helm install --name nfs-client --set nfs.server=my.server.com --set nfs.path=/mypath --set storageClass.defaultClass=true --set storageClass.mountOptions="{nolock\\,sync}" .

git pull and try again with the new syntax. i confirmed it is still working for me

**Comment by kmkramer** [comment]
I think the template/storageclass.yaml is incorrect.
mountOptions: {{ .Values.mountOptions }} should be
mountOptions: {{ .Values.storageClass.mountOptions }}

Once I updated this the SC yaml looks correct.

The class is getting setup correctly now with the mount options but the provisioner pod will not start because it needs mount options as well.

it looks related to this issue, https://github.com/kubernetes-incubator/external-storage/issues/1008

**Comment by kmkramer** [comment]
I had to pull again to get that change, sorry.

I just tried to deploy again without any mount options and the pod doesn't start. 
I am able to deploy the chart against a simple Ubuntu NFS export (ext4). However it mounted it nfsv4 even though I set the vers=3 option.
`x.x.x.x:/ext4-export on /persistentvolumes type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.20.99.27,local_lock=none,addr=x.x.x.x)`

but this could be that I don't have v3 enabled and v4 disabled. I'll report back on that later.

Also in this case I used IP instead of FQDN because it doesn't have one. Interestingly enough on the pod running above I cannot ping the FQDN that I'm trying to use but can ping others on my network. I just tried to use IP instead and it still fails. I added nfs-utils to the pod and can indeed `showmount -e x.x.x.x` and see all the exports.

The export that won't work with this chart is Oracle NFS (zfs backed). I posted about this issue in the slack channels a few weeks ago.

**Comment by kmkramer** [comment]
I was able to disable nfsv4 and test externally to kubernetes on the previously working export with nfsv3. Now when I deploy the chart it can't start the pod. It looks like it isn't taking any of the mountOptions and complains about locks even though I am specifying the option.

`Output: mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
`
tried all of these
{"nolock\,vers=3"} previously worked when v4 was enabled
{"nolock"}
{"nolock\,vers=4"} I'd expect mount option not supported here

**Comment by kmkramer** [comment]
enabling v3 and v4 works again but mounts as v4 just like before
{"nolock,vers=3"}

**Comment by treksler** [comment]
have you tried nfsvers=3

**Comment by kmkramer** [comment]
yes. disabled v4 again, tested that manual mounting requesting v4 fails.

`helm install --name testv2 --set nfs.server=X.X.X.X --set nfs.path=/ext4-export --set storageClass.name=test --set storageClass.mountOptions={"nolock\,nfsvers=3"} .`

kubectl get pod | grep testv2
testv2-nfs-client-provisioner-7dcb7cc5dd-lw794   0/1       ContainerCreating   0          2m

kubectl get events
> 2m          2m           1         testv2-nfs-client-provisioner-7dcb7cc5dd-lw794.155a29b5dc52a99e   Pod                                                    Warning   FailedMount         kubelet, cow-workers-2   Unable to mount volumes for pod "testv2-nfs-client-provisioner-7dcb7cc5dd-lw794_default(540e7ed5-c732-11e8-873b-005056a31982)": timeout expired waiting for volumes to attach or mount for pod "default"/"testv2-nfs-client-provisioner-7dcb7cc5dd-lw794". list of unmounted volumes=[nfs-client-root]. list of unattached volumes=[nfs-client-root testv2-nfs-client-provisioner-token-4f92v]
29s         3m           9         testv2-nfs-client-provisioner-7dcb7cc5dd-lw794.155a299ba727ae88   Pod                                                    Warning   FailedMount         kubelet, cow-workers-2   MountVolume.SetUp failed for volume "nfs-client-root" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs X.X.X.X:/ext4-export /opt/rke/var/lib/kubelet/pods/540e7ed5-c732-11e8-873b-005056a31982/volumes/kubernetes.io~nfs/nfs-client-root
Output: mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.

**Comment by jdmaguire** [comment]
I've been silently lurking and following along; @kmkramer I'm running into the same issue and wondering if you've come to any conclusion yet?

**Comment by kmkramer** [comment]
@jdmaguire I have not. For now I'm just using standard PV,PVC and following the other issue that I believe is related. https://github.com/kubernetes-incubator/external-storage/issues/1008

**Comment by treksler** [comment]
hi, i switched the helm chart to use an explicit pv and pvc for the client root
https://github.com/treksler/charts/tree/master/stable/nfs-client-provisioner

the provisioner pod should start up now for you

**Comment by kmkramer** [comment]
I was able to get this working once and was able to dynamically provision storage. I'm having trouble doing it a second time.

I see a couple of issues or need some clarification of how this mimics something like the gce-pd provisioner. I'm not exactly sure why the provisioner pod needs an initial PV,PVC. In the example of using the gce-pd, you simply create the storageClass object, the PVC object and then have a pod use the PVC. The provisioner then creates a PV and binds the requested PVC to the newly created PV. Perhaps in this case the the provisioner keeps track of capacity requests so that the PV isn't oversubscribed? I only have on-premise so I haven't played with cloud storage with kubernetes to know the details.

1) You cannot create multiple StorageClass objects.
Error: release failed: persistentvolumes "nfs-client-pv" already exists
2) I assume there will be a need to set the capacity of the provisioner's PV,PVC instead of hard coded in the template. Assuming something tracks the resource usage. In my case the PV is only 32G for testing this.
3) I believe there will be a need to specify the initial PV,PVC names. {pv.Name}{pvc.Name} so that you can have multiple StorageClass objects. see issue 1 above
4) --set storageClass.provisionerName=test doesn't seem to apply the requested name.

Once the provisioner was deployed I was able to create a test pod and have the provisioner dynamically provision a 1Gi pvc

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-dyn-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: sleepypod
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: test-dyn-pvc
  containers:
    - name: sleepypod
      image: busybox
      env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      command:
        - sleep
        - "6000"
      volumeMounts:
        - name: data
          mountPath: /data
          subPath: sleepypod
          readOnly: false
```

```bash
kubectl get pv,pvc
NAME                             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                    STORAGECLASS   REASON   AGE
persistentvolume/nfs-client-pv   500Gi      RWO            Retain           Bound    default/nfs-client-pvc                           2m
persistentvolume/pvc-f3aa6887-ccb0-11e8-b6d3-080027f75299   1Gi        RWO            Retain           Bound    default/test-dyn-pvc     test              26m
NAME                                   STATUS   VOLUME          CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/nfs-client-pvc   Bound    nfs-client-pv   500Gi      RWO                           2m
persistentvolumeclaim/test-dyn-pvc     Bound    pvc-f3aa6887-ccb0-11e8-b6d3-080027f75299   1Gi        RWO            test    26m
```

**Comment by treksler** [comment]
Hi,

I tried the storageclass + PVC route, but couldn't get it to work, so I created the PV as well.
It appears the initial PV is needed so that the provisioner can create the folders for the dynamically created PVs. In the original code, it was simply mounting directly via NFS. As explained in kubernetes-incubator/external-storage#1008, that will not work with mountOptions, as only PVCs can specify them 

1. please make sure you do a git pull. I put in some changes from @OlegPS in PR #8327, which enable creation of multiple storageclasses

2. I am not sure the capacity matters here. As I understand it, and I could be wrong, the PV is only used for creating folders, so the size could be a) anything? b) minimum allowable value? c) maximum allowable value? d)some value that ought to be enough? eg 10MB? I  don't think it tracks oversubscription and thus i don't think it will be setup dependent and i don't think it will be need to be configurable. Hopefully someone who understands this inside and out can confirm

3. please make sure you do a git pull. I put in some changes from @OlegPS in PR #8327, which  dynamically create storageclass specific PV and PVC names

4. that seems to only be applied to the PROVISIONER_NAME env variable in the deployment and the provisioner: field in the storageClass

**Comment by OlegPS** [comment]
Hello! I was able to create two provisioners and 2 application deployments with PR #8327 
```
> helm install --set nfs.server=x.x.x.x --set nfs.path=/xxx/xxx --set storageClass.defaultClass=true --set nfs.mountOptions={nfsvers=3} ~/git/charts/stable/nfs-client-provisioner
> helm install --set nfs.server=x.x.x.x --set nfs.path=/xxx/xxx --set nfs.mountOptions={nfsvers=3} --set storageClass.name=second ~/git/charts/stable/nfs-client-provisioner
> helm install --name janus-default-storage-class stable/janusgraph
> helm install --name janus-second-storage-class --set persistence.storageClass=second stable/janusgraph

> kubectl get pv,pvc
NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                           STORAGECLASS
persistentvolume/pv-fancy-sparrow-nfs-client-provisioner    10Mi       RWO            Delete           Bound      test/pvc-fancy-sparrow-nfs-client-provisioner               
persistentvolume/pv-worn-lizzard-nfs-client-provisioner     10Mi       RWO            Delete           Bound      test/pvc-worn-lizzard-nfs-client-provisioner                
persistentvolume/pvc-544d488f-cd2e-11e8-998f-00505601224b   4Gi        RWO            Delete           Bound      test/janus-default-storage-class-janusgraph     nfs-client  
persistentvolume/pvc-f60dccf2-cd30-11e8-998f-00505601224b   4Gi        RWO            Delete           Bound      test/janus-second-storage-class-janusgraph      second      

NAME                                                             STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/janus-default-storage-class-janusgraph     Bound     pvc-544d488f-cd2e-11e8-998f-00505601224b   4Gi        RWO            nfs-client     28m
persistentvolumeclaim/janus-second-storage-class-janusgraph      Bound     pvc-f60dccf2-cd30-11e8-998f-00505601224b   4Gi        RWO            second         9m
persistentvolumeclaim/pvc-fancy-sparrow-nfs-client-provisioner   Bound     pv-fancy-sparrow-nfs-client-provisioner    10Mi       RWO                           32m
persistentvolumeclaim/pvc-worn-lizzard-nfs-client-provisioner    Bound     pv-worn-lizzard-nfs-client-provisioner     10Mi       RWO                           10m
```
