### ISSUE TITLE
[stable/kong] tls secret name is passed incorrectly in proxy ingress template

### ISSUE THREAD

**Issue by amkartashov** [helm/charts#8020]
**Is this a request for help?**:  No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

HELM
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

K8S
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.5", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-02T23:42:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

Chart: Kong
Chart version: 0.4.0

**What happened**:

Chart installation fails in case if proxy.ingress.tls is specified. Documentation says this should be 'Name of secret resource, containing TLS secret' so I just put it there:

```
$ helm install --name kong stable/kong \
>   --set proxy.useTLS=false \
>   --set proxy.ingress.hosts={'KONG.DOMAIN.COM'} \
>   --set proxy.ingress.enabled=true,proxy.ingress.tls=kong-tls \
>   --set proxy.ingress.annotations.kubernetes\\.io/ingress\\.global-static-ip-name=kong-ip \
Error: release kong failed: Ingress in version "v1beta1" cannot be handled as a Ingress: v1beta1.Ingress: Spec: v1beta1.IngressSpec: TLS: []v1beta1.IngressTLS: ReadArrayCB: expect [ o
r n, but found: ", parsing 424 ...}],"tls":"... at {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.global-static-ip-name":"kong-i
p"},"labels":{"app":"kong","chart":"kong-0.4.0","heritage":"Tiller","release":"kong"},"name":"kong-kong-proxy","namespace":"default"},"spec":{"rules":[{"host":"KONG.DOMAIN.COM","http":{"paths":[{"backend":{"serviceName":"kong-kong-proxy","servicePort":8443},"path":"/"}]}}],"tls":"kong-tls"}}
```
**What you expected to happen**:

Installation succeeds

**How to reproduce it** (as minimally and precisely as possible):

See helm command above.

**Anything else we need to know**:

Problem is in kong/templates/ingress-proxy.yaml. It generates

"tls":"kong-tls"

while it should generate

"tls": [ { "secretName": "kong-tls" } ]

W/A is to specify this directly. so instead of

--set proxy.ingress.tls=kong-tls

I use

--set proxy.ingress.tls[0].secretName=kong-tls

**Comment by BiggA94** [comment]
This issue is still relevant.
Either this needs a fix, or at least a comment in the Documentation.

**Comment by bluemalkin** [comment]
This is still not resolved.
