### ISSUE TITLE
metrics-server: User "system:anonymous" cannot list nodes.metrics.k8s.io at the cluster scope

### ISSUE THREAD

**Issue by amartorelli** [helm/charts#8024]
Hi,
not sure if this is a bug or something I haven't considered because I'm using EKS, but I hope someone will be able to help.

**Which chart**: metrics-server

**What happened**: I'm running this chart in EKS with the default values plus an extra argument:
```
- --kubelet-preferred-address-types=InternalIP
```

The installation of the chart was run using the command
```
helm install --name metrics-server -f metrics-server/values.yml stable/metrics-server --tls
```

When running the `kubectl get --raw "/apis/metrics.k8s.io/v1beta1/nodes"` command this error is returned:
```
Error from server (Forbidden): nodes.metrics.k8s.io is forbidden: User "system:anonymous" cannot list nodes.metrics.k8s.io at the cluster scope
```

**What you expected to happen**:
I'd expect the chart to install all the rbac properly and use the correct service account with the right permission to get the cluster metrics.

**How to reproduce it** (as minimally and precisely as possible):
Having EKS set up, just install the chart as specified above and run the following command:
```
kubectl get --raw "/apis/metrics.k8s.io/v1beta1/nodes"
```

**Anything else we need to know**:
Helm version:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Kubernetes version: v1.10.3 running in Amazon EKS

**Comment by steven-sheehy** [comment]
Not really an issue with the chart. Which args you pass highly depends on how your cluster is configured. Most likely you need to enable --authentication-token-webhook=true on the kubelet. See also https://github.com/kubernetes-incubator/metrics-server/issues/95

**Comment by steven-sheehy** [comment]
I don't have permission to close it. But the point was that the chart highly depends on how your environment is configured. So you should either change your cluster to support how the chart does things or change the chart args in values.yaml with the [flags](https://github.com/kubernetes-incubator/metrics-server#flags) you need.

**Comment by cnelson** [comment]
@amartorelli did you ever figure out the fix for this?  Seeing the same issue.

**Comment by ingshtrom** [comment]
For EKS created clusters, I found that running `kubectl get --raw "/apis/metrics.k8s.io/v1beta1/pods"` with the user/role that created the cluster works just fine, but if I run the same command using a user who has the `cluster-admin` ClusterRole attached to them, then it doesn't work... I'm digging into why this happens and what RBAC is needed in order to read the metrics.

**Comment by ingshtrom** [comment]
@cnelson Have you seen https://aws.amazon.com/premiumsupport/knowledge-center/eks-metrics-server/? I just had to add `username: admin:{{SessionName}}` for the role that I was using and it worked as expected.
