### ISSUE TITLE
Elasticsearch doesn't start, discovery service "pod has unbound PersistentVolumeClaims (repeated 3 times)"

### ISSUE THREAD

**Issue by reasv** [helm/charts#8029]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug, presumably

**Version of Helm and Kubernetes**:
Helm version:
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

Kubectl version:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
https://github.com/helm/charts/tree/master/incubator/elasticsearch
**What happened**:
I install it with no custom options, and helm tells me it has been installed.
However according to the kubernetes dashboard it isn't working:
In the discovery service I see that "elasticsearch-master-0" has an error:
>pod has unbound PersistentVolumeClaims (repeated 3 times)

While the client service pods have this:
>Back-off restarting failed container

The latter's logs only have one line:

>container "elasticsearch" in pod "search-elasticsearch-client-c444f99d5-9mfrz" is waiting to start: PodInitializing

The master's logs say nothing.

**What you expected to happen**:
Elasticsearch starts

**How to reproduce it** (as minimally and precisely as possible):
I installed Canonical Kubernetes with `conjure-up kubernetes` on Ubuntu 18.04, then added the helm repo.

 helm install --name NAME incubator/elasticsearch
**Anything else we need to know**:

**Comment by reasv** [comment]
Nevermind I managed to solve the problem on my own.

**Comment by bnnk** [comment]
Any input on how you got this resolved ?.
