### ISSUE TITLE
[stable/mongodb-replicaset] Metrics break upgrade for single replica

### ISSUE THREAD

**Issue by steven-sheehy** [helm/charts#8055]
**Is this a request for help?**:
Yes

**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

**Version of Helm and Kubernetes**:
Kubernetes: 2.10.3
Helm: 2.11

**Which chart**:
stable/mongodb-replicaset 3.5.7

**What happened**:
Enabling metrics and upgrading a single replica (no secondaries) mongodb-replicaset causes the metric sidecar container to crash repeatedly. This occurs because the on-start.sh does not handle creating the metric user in this scenario. The liveness probe fails as a result.

**What you expected to happen**:
The metric sidecar to not crash and the deployment to be successful with all pods ready.

**How to reproduce it**:
```shell
helm install --name mongo --set replicas=1 --set auth.enabled=true --set auth.adminUser=mongo --set auth.adminPassword=password --set auth.key=.... stable/mongodb-replicaset
helm upgrade mongo --reuse-values --set metrics.enabled=true --set auth.metricsUser=metrics --set auth.metricsPassword=password stable/mongodb-replicaset
```

```shell
[2018-09-26T21:54:56,296912312+00:00] [on-start.sh] Bootstrapping MongoDB replica set member: mongo-mongodb-replicaset-0
[2018-09-26T21:54:56,304678675+00:00] [on-start.sh] Reading standard input...
[2018-09-26T21:54:56,307749334+00:00] [on-start.sh] Peers:
[2018-09-26T21:54:56,310825000+00:00] [on-start.sh] Starting a MongoDB instance...
[2018-09-26T21:54:56,332832057+00:00] [on-start.sh] Waiting for MongoDB to be ready...
```

**Anything else we need to know**:
The PR #6834 addressed upgrades for replicas >1 and this issue was [discussed](https://github.com/helm/charts/pull/6834#issuecomment-424801509) there. I'm working on a PR to address it.

**Comment by ssalaues** [comment]
Yeah I was able to reproduce this as well
