### ISSUE TITLE
[stable/prometheus] chart fails to install with latest Tiller (v2.11.0-rc.2)

### ISSUE THREAD

**Issue by mravkine** [helm/charts#8058]
**Is this a request for help?**:  No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

Kubernetes v1.11.2

mike@nucleus1:~/ai/halo-toronto$ helm version
Client: &version.Version{SemVer:"v2.11.0-rc.2", GitCommit:"8d408876a059223c9a29d99efb35b3497a53504c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0-rc.2", GitCommit:"8d408876a059223c9a29d99efb35b3497a53504c", GitTreeState:"clean"}

**Which chart**: stable/prometheus

**What happened**:  The chart will not install, gives "Error: Chart incompatible with Tiller v2.11.0-rc.2"

**What you expected to happen**: The chart specifies a minimum Tiller version of 2.8, and I expect that 2.11 > 2.8 so this should work.

**How to reproduce it** (as minimally and precisely as possible):
Install latest version of helm with ```helm init``` then ```helm install stable/promethesus``` should give the errors.

**Anything else we need to know**:
It may be doing like it's doing a naive string compare and thinks "1"<"8" so .11 is older then .8.

**Comment by phihos** [comment]
+1 Same issue here

**Comment by mravkine** [comment]
6.7.3 is the oldest version of the chart that doesnt have a version restriction and works on latest helm, but be careful it has an old node exporter image tag you will need to bump to 0.16.0

I think the issue is actually in helm and not with the chart, this bug is a symptom of a bad version check.

**Comment by hickst** [comment]
Could someone please tell me what the fix for this was supposed to be. I'm still seeing the problem with the latest version:
```
helm install stable/prometheus
Error: Chart incompatible with Tiller v2.13.0-rc.2
```

**Comment by mravkine** [comment]
There's no actual fix.  This is Helm bug in that it doesn't undertand the "-rc.2" portion of the version string.  The only workaround I know of is to grab a Tiller version that strictly follows the "vx.y.z" convention, and deal with this headache every few months when upgrading.

**Comment by hickst** [comment]
@mravkine Thanks for the quick and helpful reply. Given the additional info in your answer, I was able to just "drop back" to the previous non-RC version (https://github.com/helm/helm/releases/tag/v2.12.3) and the installation appears successful. Unfortunately, of course, this workaround won't help if one really needs an RC version. :(

**Comment by mongakshay** [comment]
facing this issue

**Comment by AdeOpe** [comment]
facing this issue also

**Comment by harshalkwagh** [comment]
Facing same issue while installing Prometheus and Prometheus-operator with Tiller version v2.11.0 and v2.10.0 as well.
can someone one tell me the reason and how to get rid of this issue.
