### ISSUE TITLE
Concourse Readiness/Liveness Probe fails

### ISSUE THREAD

**Issue by rjain15** [helm/charts#8059]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.5", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-02T23:42:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"} 

**Which chart**:
Concourse

**What happened**:
Readiness/Liveness Probes failed. 
    Liveness:   http-get http://:atc/ delay=120s timeout=5s period=10s #success=1 #failure=3
    Readiness:  http-get http://:atc/ delay=5s timeout=1s period=10s #success=1 #failure=3

**What you expected to happen**:
Probes to work

**How to reproduce it** (as minimally and precisely as possible):
helm install --name concourse stable/concourse -f values.yaml

**Anything else we need to know**:
Events:
  Type     Reason                 Age                 From                                                  Message
  ----     ------                 ----                ----                                                  -------
  Normal   Scheduled              43m                 default-scheduler                                     Successfully assigned concourse-web-6bdcc4cf45-wg76s to gke-cluster-default-pool-bec82955-0rtc
  Normal   SuccessfulMountVolume  43m                 kubelet, gke-cluster-default-pool-bec82955-0rtc  MountVolume.SetUp succeeded for volume "concourse-keys"
  Normal   SuccessfulMountVolume  43m                 kubelet, gke-cluster-default-pool-bec82955-0rtc  MountVolume.SetUp succeeded for volume "concourse-web-token-lbgzh"
  Normal   Pulling                43m                 kubelet, gke-cluster-default-pool-bec82955-0rtc  pulling image "concourse/concourse:4.2.1"
  Normal   Pulled                 42m                 kubelet, gke-cluster-default-pool-bec82955-0rtc  Successfully pulled image "concourse/concourse:4.2.1"
  Normal   Created                42m                 kubelet, gke-cluster-default-pool-bec82955-0rtc  Created container
  Normal   Started                42m                 kubelet, gke-cluster-default-pool-bec82955-0rtc  Started container
  Warning  Unhealthy              40m (x3 over 40m)   kubelet, gke-cluster-default-pool-bec82955-0rtc  Liveness probe failed: Get http://10.28.0.19:8080/: dial tcp 10.28.0.19:8080: getsockopt: connection refused
  Normal   Killing                40m                 kubelet, gke-cluster-default-pool-bec82955-0rtc  Killing container with id docker://concourse-web:Container failed liveness probe.. Container will be killed and recreated.
  Normal   Pulled                 40m                 kubelet, gke-cluster-default-pool-bec82955-0rtc  Container image "concourse/concourse:4.2.1" already present on machine
  Warning  BackOff                8m (x45 over 26m)   kubelet, gke-cluster-default-pool-bec82955-0rtc  Back-off restarting failed container
  Warning  Unhealthy              3m (x150 over 42m)  kubelet, gke-cluster-default-pool-bec82955-0rtc  Readiness probe failed: Get http://10.28.0.19:8080/: dial tcp 10.28.0.19:8080: getsockopt: connection refused

**Comment by camillemahaut** [comment]
I have the same issue, do you have any update ?

**Comment by jacquelotjeff** [comment]
Same issue here with rabbitmq-ha : 

```
Warning  Unhealthy         28s (x18 over 1m)  kubelet, worker1  Readiness probe failed: Get http://10.244.4.88:15672/api/healthchecks/node: dial tcp 10.244.4.88:15672: connect: connection refused
```

Kubernetes version : v1.11.3

**Comment by jacquelotjeff** [comment]
In fact my mistake came from a dns problem : Kubedns was not able to connect to the api server.

To fix it, I add this rules in my iptables (was missing) : 

``` 
iptables -P FORWARD ACCEPT
```

**Comment by sunyuding** [comment]
I installed concourse in the sandbox k8s cluster `helm install --name concourse stable/concourse`. 

Get the following errors in for concourse-web pod
```
Warning  Unhealthy  7m8s (x6 over 8m53s)   kubelet, ip-10-86-137-149.us-west-2.compute.internal  Liveness probe failed: Get http://10.86.138.191:8080/api/v1/info: dial tcp 10.86.138.191:8080: connect: connection refused
  Warning  Unhealthy  4m14s (x30 over 9m4s)  kubelet, ip-10-86-137-149.us-west-2.compute.internal  Readiness probe failed: Get http://10.86.138.191:8080/api/v1/info: dial tcp 10.86.138.191:8080: connect: connection refused
```
