### ISSUE TITLE
Make redis-ha chart use local volume instead of using emptyDir with node selector.

### ISSUE THREAD

**Issue by happyyangyuan** [helm/charts#8062]
**Request for help**
---

**This is a FEATURE REQUEST**
 FEATURE REQUEST

**Which chart**:
redis-ha

**What happened**:
Currently the redis-ha chart's volume is using emptyDir with node selector

**What you expected to happen**:
use local volume

**Comment by ssalaues** [comment]
The PR #7323 should appropriately resolve this feature request 😁

**Comment by happyyangyuan** [comment]
> The PR #7323 should appropriately resolve this feature request 😁

THKS
