### ISSUE TITLE
Wordpress storageclass "default" fails with a k8s deployed NFS service

### ISSUE THREAD

**Issue by sputnick** [helm/charts#807]
Found a strange bug. The wordpress PVCs will not be bound by the cluster deployed NFS service (external provider) because of the KEY NAME for the default storage class "default". I'm using K8s 1.5.2.

In short this fails:
volume.alpha.kubernetes.io/storage-class: default

But this works!?
volume.beta.kubernetes.io/storage-class: default

Steps to reproduce.

Essentially I setup an NFS provisioner with this
https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/docs/deployment.md#in-kubernetes---deployment-of-1-replica

And created a Storage Class called "default" so i wouldn't need to change every Charts values to deploy with persistent storage. However that will fail to bind the a PV to the PVCs with the error message:

> Claim "default/wordypress-wordpress-wordpress": StorageClass "" not found

So that didn't make sense because specifying any other storage class worked. So on a whim I tried changing "alpha" in the annotation key name (only used when no storage class is provided) to "beta" and it instantly worked!

This is the "offending" line but I was very surprised that this mattered at all...
https://github.com/kubernetes/charts/blob/master/stable/wordpress/templates/wordpress-pvc.yaml#L15

I'm unsure if this is the fault of the provisioner, kubernetes or that we just need to change all charts to use the "beta" key name from now on...

Thoughts?

**Comment by sputnick** [comment]
Hopefully the NFS provisioner can be fixed instead of changing all the charts but perhaps one day we need to update to the "beta" api.

**Comment by sputnick** [comment]
There are a few comments on the referenced ticket and the conversations I had on the #helm slack channel seem to point to the same conclusion. We should be using the "beta" key in the charts now.
volume.beta.kubernetes.io/storage-class: default

**Comment by sputnick** [comment]
And this k8s 1.6 change basically means that ALL charts using the alpha key will break with 1.6.
https://github.com/kubernetes/kubernetes.github.io/pull/2557

**Comment by prydonius** [comment]
@sputnick sorry only just saw this. All the charts should support the beta annotation (#116) when you supply a custom storage class. See https://github.com/kubernetes/charts/blob/master/stable/wordpress/values.yaml#L127.

When k8s 1.6 is released, we will change all charts to only use the beta annotation.

**Comment by sputnick** [comment]
Good @prydonius. But is using the beta annotation + "default" the correct value or "" (for the default)?

**Comment by prydonius** [comment]
Not sure if I understand correctly, there is no default for the beta annotation as you have to specifically provide the storage class. The value of the alpha annotation is inconsequential, I believe, but we are following the guidelines described in https://kubernetes.io/docs/user-guide/persistent-volumes/#writing-portable-configuration.
