### ISSUE TITLE
Update postgres to use statefulset?

### ISSUE THREAD

**Issue by imranismail** [helm/charts#809]
As described in the following blog post: http://blog.kubernetes.io/2017/02/postgresql-clusters-kubernetes-statefulsets.html

**Comment by kachkaev** [comment]
@jmccormick2001 WDYT on contributing on the official chart following your great blog post?

**Comment by jmccormick2001** [comment]
I'd be open to doing that, let me see if I can contribute to this.

**Comment by mattfarina** [comment]
cc: @swordbeta @databus23 

This is a good idea. Some charts like the stable/consul chart are already using statefulsets. If someone is interested in contributing this would be nice to have.

**Comment by kfox1111** [comment]
I just noticed this when in my minikube I deleted postgresql and a new instance launched before the old one was deleted. This is potentially a data corrupting bug!

**Comment by gkarthiks** [comment]
i can work on this.

**Comment by gkarthiks** [comment]
seems there is one pending PR from someone on this chart https://github.com/helm/charts/pull/7589

**Comment by gkarthiks** [comment]
Is it fine if I create another PR separately ?

**Comment by desaintmartin** [comment]
This PR has nothing to do with StatefulSet, so yes, go on!

**Comment by desaintmartin** [comment]
Everyone: Just to be clear, would such a change break compatibility with official postgres image? Should this be a new, different chart named for example postgres-ha?

**Comment by cliedeman** [comment]
It would break backwards compatibility but there is not much choice. An alternative chart would duplicate work and cause confusion. And eventually, we would want to replace the original postgres chart with the stateful set version putting us right back at this discussion.

**Comment by mattfarina** [comment]
The semver on the chart would need to have a major version bump. Ideally, PVCs handling data could be handled gracefully (though this is an untested ideal)

**Comment by desaintmartin** [comment]
Beware that https://github.com/helm/charts/pull/8004 is in the process of being merged.

**Comment by gkarthiks** [comment]
@desaintmartin  I thought no one will pick this issue, since I committed on this sometime back. 

Closed the my new PR.

If possible i need a way of assigning the issues to my name. So that no conflicts will be arising. @desaintmartin  or @davidkarlsen can you please help me on that?
