### ISSUE TITLE
[stable/cockroachdb] StatefulSet upgrade fails because of chart label present in selector

### ISSUE THREAD

**Issue by rio** [helm/charts#8102]
Just like with the redis chart StatefulSet upgrades fail through the helm upgrade mechanism. This is because no explicit selector is set on the StatefulSet so it defaults to whatever is set in the template's labels. This includes the chart version which changes with every upgrade. Because the selector cannot be changed after the creation of the StatfulSet the upgrade fails because the template's chart label does get updated and so the selector doesn't match anymore.

This is how the redis chart fixed it: https://github.com/helm/charts/commit/c3bbcadcd3c722ece060ac9dd47dfa2e86df168d#diff-bff5387866dba6e2bb69e1feba09ea9b

Sadly this would mean a breaking change to the chart and downtime as the StatefulSet needs to be deleted.

**Comment by Rio** [comment]
For reference here is the general problem described https://github.com/helm/charts/issues/7680
