### ISSUE TITLE
[stable/prometheus] Add PodSecurityPolicy support (now fails instead)

### ISSUE THREAD

**Issue by verwilst** [helm/charts#8126]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: Kubernetes v1.11.3

**Which chart**: stable/prometheus

**What happened**:

Installed Kubernetes cluster with podsecuritypolicy enabled.

```
# kubectl get pods
NAME                                             READY     STATUS                            RESTARTS   AGE
prometheus-alertmanager-78f67cc7b9-hmxbr         0/2       CreateContainerConfigError        0          3m
prometheus-kube-state-metrics-5c88678db8-qk5k2   0/1       CreateContainerConfigError        0          3m
prometheus-pushgateway-58bbb659-kl2x8            0/1       CreateContainerConfigError        0          3m
prometheus-server-6c59f49df6-pffdz               0/2       Init:CreateContainerConfigError   0          3m
```

```
Events:
  Type     Reason     Age               From                     Message
  ----     ------     ----              ----                     -------
  Normal   Scheduled  3m                default-scheduler        Successfully assigned prometheus/prometheus-server-6c59f49df6-pffdz to k8s-acc-node02
  Warning  Failed     1m (x12 over 3m)  kubelet, k8s-acc-node02  Error: container has runAsNonRoot and image will run as root
  Normal   Pulled     1m (x13 over 3m)  kubelet, k8s-acc-node02  Container image "busybox:latest" already present on machine
```

**What you expected to happen**: Up and running Prometheus install

**How to reproduce it** (as minimally and precisely as possible):

Install Kubernetes cluster with podsecuritypolicy enabled.
Helm install stable/prometheus

**Anything else we need to know**:

**Comment by lcavajani** [comment]
being addressed in [PR 8264](https://github.com/helm/charts/pull/8264)

**Comment by verwilst** [comment]
#8264 is only node-exporter, this issue is about prometheus-server itself.

**Comment by verwilst** [comment]
The prometheus-server chart has an InitContainer that chowns /data before the server itself is started. That one is running as root, which is a no-no for PSP. :-)

**Comment by verwilst** [comment]
It's not defined in the charts, but an afaik InitContainer runs before actual PSP resources are created by the chart, thus falling back to kubernetes.io/psp=restricted .

```
Name:               prometheus-server-567b58bbd7-rjc2d
Namespace:          prometheus
Priority:           0
PriorityClassName:  <none>
Node:               k8s-acc-node02/10.75.1.7
Start Time:         Mon, 15 Oct 2018 08:55:16 +0000
Labels:             app=prometheus
                    component=server
                    pod-template-hash=1236146683
                    release=prometheus
Annotations:        kubernetes.io/psp=restricted
                    seccomp.security.alpha.kubernetes.io/pod=docker/default
Status:             Pending
IP:                 
Controlled By:      ReplicaSet/prometheus-server-567b58bbd7
Init Containers:
  init-chown-data:
    Container ID:  
    Image:         busybox:latest
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      chown
      -R
      65534:65534
      /data
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from storage-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-server-token-q4fgh (ro)
```

**Comment by myssa91** [comment]
+1 

I'm new to psp but we need to activate them for security purposes. I've tried to create a ClusterRoleBinding on ServiceAccount (alertmanager, kubeState-Metrics, ect ...) and bind them to psp:privileged but I still got the same error.
Would you have an ETA for this issue ?

Thanks a lot !

**Comment by verwilst** [comment]
Not sure if this issue is still current since stable/prometheus-operator works just fine with psp.
