### ISSUE TITLE
Kibana not loaded?

### ISSUE THREAD

**Issue by bradley-baker** [helm/charts#8133]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Helm version v2.10.0
Kubernetes v1.11.0

**Which chart**:
incubator/elasticsearch

**What happened**:
Ran helm install --name elastic-stack1 -f values.yaml incubator/elasticsearch --tls
Received the following output:
export POD_NAME=$(kubectl get pods --namespace default -l "app=elasticsearch,component=client,release=elastic-stack1" -o jsonpath="{.items[0].metadata.name}")
    
echo "Visit http://127.0.0.1:9200 to use Elasticsearch"

kubectl port-forward --namespace default $POD_NAME 9200:9200

Ran those  commands then attempted to access the url above and received:
{
  "name" : "elastic-stack1-elasticsearch-client-5f56dc7bc-jbgzl",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "YRfDmvwLQR-BFEQRNLofMg",
  "version" : {
    "number" : "6.4.1",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "e36acdb",
    "build_date" : "2018-09-13T22:18:07.696808Z",
    "build_snapshot" : false,
    "lucene_version" : "7.4.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

**What you expected to happen**:
Kibana or some web based user interface to load. 

**How to reproduce it** (as minimally and precisely as possible):
See above.

**Anything else we need to know**:
Not that I can think of.

**Comment by bdashrad** [comment]
The elasticsearch chart only stands up elasticsearch, not kibana. You would stand up kibana with a separate chart (https://github.com/helm/charts/tree/master/stable/kibana) and point it at a cluster, like the one you just stood up.

**Comment by bab5470** [comment]
That was exactly the problem. I'd done incubator/elastic-search not incubator/elastic-stack - i hadn't caught the nuance between search and stack. Thank you!
