### ISSUE TITLE
Enabling HiPe Compilation reproduces ConfigMap RO mount issue

### ISSUE THREAD

**Issue by gbates101** [helm/charts#8150]
**Is this a request for help?** _No_
---
 
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
k8s: v1.10.1
helm (both client/server): v2.11.0-rc.2

**Which chart**:
stable/rabbitmq-ha, v1.10.0 (app version 3.7.4)

**What happened**:
When enabling HiPe compilation, I experience the issue reported in https://github.com/helm/charts/issues/4166

**What you expected to happen**:
Not that.

**How to reproduce it** (as minimally and precisely as possible):
- `helm delete --purge <rabbitmq-release-name>`
- `kubectl delete pvc <persistent-volume(s)-if-they-exist>`
- Specify `rabbitmqHipeCompile: true` in values.yaml, and
- `helm install -n <rabbitmq-release-name> stable/rabbitmq-ha -f my-values.yaml`

Pod will enter `CrashLoopBackoff`, at this point I run:
`kubectl logs <pod-name> rabbitmq-ha`

and I see:
`sed: can't create temp file '/etc/rabbitmq/rabbitmq.confXXXXXX': Read-only file system`

**Anything else we need to know**:
Works just fine if I disable HiPe compilation. I tried with with and without PVCs enabled, and with/without exporter enabled. Made no difference, only configuration option that reproduces this is HiPe compilation.

**Comment by kfeh** [comment]
Same here!
