### ISSUE TITLE
Allow upgrade of rabbitmq chart without replacing the secret created on install

### ISSUE THREAD

**Issue by jonathan-r-young** [helm/charts#8168]
**Is this a request for help?**:

---

** FEATURE REQUEST ** :
Allow upgrade of rabbitmq chart without needing to specify the existing admin user / password / cookie. Currently the existing secret is replaced with new values if a helm upgrade occurs
Example of a solution is https://github.com/helm/charts/blob/master/incubator/couchdb/templates/secrets.yaml

**Version of Helm and Kubernetes**:

**Which chart**:
 charts/stable/rabbitmq/templates/secrets.yaml 

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by steven-sheehy** [comment]
This is a [known issue](https://github.com/helm/charts/issues/5167) with Helm charts in general and there's not really a solution. That couchdb chart you linked to would have the same issue regenerating the secret looking at its code.

**Comment by jonathan-r-young** [comment]
Sure, I think the work around that couchdb chart has is to allow the user to set a flag in the values 
`{{- if .Values.createAdminSecret -}}`
