### ISSUE TITLE
Anchore-Engine chart: wrong reference to value in DB SSL configuration

### ISSUE THREAD

**Issue by jaguasch** [helm/charts#8184]
About this ```globalConfig.dbConfig.ssl=True``` mentioned here:
https://github.com/helm/charts/tree/master/stable/anchore-engine#database

This value is not the one used for the template:

https://github.com/helm/charts/blob/master/stable/anchore-engine/templates/core_configmap.yaml#L79

Fix could be either:

- Documentation references that value should be ```postgresql.sslEnabled=True```
- Change template statement from ```{{ .Values.postgresql.sslEnabled }}``` to ```{{ .Values.globalConfig.dbConfig.ssl }}```

**Comment by zhill** [comment]
@jaguasch ack and thanks! We have some changes coming in soon for the chart that should resolve this.

**Comment by Btodhunter** [comment]
The chart has been changed significantly with commit 8eb06375ba7b0752ceb146b40026fdb935ded1c9. This should no longer be an issue. Thanks for the feedback!
