### ISSUE TITLE
Define how many old versions of Kubernetes that stable Charts should support

### ISSUE THREAD

**Issue by erictune** [helm/charts#820]
Propose 2 minor versions supported at any time.
Once 1.6 is released, then we would document somewhere that _charts work with 1.5 and 1.6_.
At that point, we could remove features that are for 1.4 (such as `volume.alpha.kubernetes.io/storage-class`).

**Comment by prydonius** [comment]
+1

Up until now, we've mostly been focused on supporting the latest stable version (1.5 right now), though most charts right now should work on 1.4 (with the exception of charts using the StatefulSet API). I agree that once 1.6 is released, we can more reliably say we support 1.5 and 1.6, and we should state this in the README and contribution docs.

**Comment by erictune** [comment]
Concrete example:
- Init containers became GA in 1.6.   So, it uses a proper field instead of an ugly annotation.  I'd like to update charts to use the field

With a two-release window model, shortly after Kubernetes 1.7 is released, we'd announce that Charts now support 1.7 and 1.6, but not 1.5 or older.   I'd  then be free to update all charts to use the features introduced in 1.6, such as the init-container field.

Alternatively, we could maintain multiple branches: one branch would allow features from latest kubernetes minor version, and another would work with older minor versions.  This is more works for charts, but allows Kubernetes developers to promote latest features at the same time as soon as they are released.

@viglesiasce
