### ISSUE TITLE
[redis-ha] Cannot configure down-after-milliseconds

### ISSUE THREAD

**Issue by stanltam** [helm/charts#8240]
**Is this a request for help?**:help

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Version of Helm and Kubernetes**:
helm:v2.9.1
k8s:v1.11.1

**Which chart**:stable/redis-ha

**What happened**: Cannot configure down-after-milliseconds

**What you expected to happen**:can configure values in sentinel.conf

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by ssalaues** [comment]
The chart doesn't currently support this, however with the changes in #7323 this will allow full configuration of the sentinel.conf

**Comment by stanltam** [comment]
@ssalaues , thank you for the replies. May I know when is the targeted release date for this?

**Comment by ssalaues** [comment]
There are some changes that I have to apply to the PR but should be able to merge this week.

**Comment by stanltam** [comment]
Thank you so much, looking forward to the merge
