### ISSUE TITLE
[stable/prometheus] No pod_name metric

### ISSUE THREAD

**Issue by kabudu** [helm/charts#8247]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes: v1.10.0
Helm: v2.8.2

**Which chart**:
stable/prometheus

**What happened**:
Installed `stable/prometheus` using the default chart configuration, and then installed `stable/grafana` using the default chart configuration. Tried to set up a panel to measure CPU usage broken down by pod, and there appears to be no pod_name metric when looking through the list of metric options.

**What you expected to happen**:
For there to be a pod_name metric available for prometheus query construction.

**How to reproduce it** (as minimally and precisely as possible):

Install prometheus

`helm install --name prometheus stable/prometheus`

Install grafana

`helm install --name grafana stable/grafana`

Configure panel for container CPU usage breakdown

`sum (rate (container_cpu_usage_seconds_total{image!=""}[1m])) by (pod_name)`

**Anything else we need to know**:

Query inspector output from Grafana

```
xhrStatus:"complete"
request:Object
method:"GET"
url:"api/datasources/proxy/1/api/v1/query_range?query=sum%20(rate%20(container_cpu_usage_seconds_total%7Bimage!%3D%22%22%7D%5B1m%5D))%20by%20(pod_name)&start=1538885580&end=1538907210&step=30"
response:Object
status:"success"
data:Object
resultType:"matrix"
result:Array[0]
```

**Comment by lcavajani** [comment]
By default, Prometheus scrapes the metrics every minute so I think you don't have enough data over one minute to calculate the rate. 

So you can use 2m minimum or 5m for example: 

* sum(rate(container_cpu_usage_seconds_total{image!=""}[2m])) by (pod_name)
* sum(rate(container_cpu_usage_seconds_total{image!=""}[5m])) by (pod_name)

Or you can increase the scrape metric internal.

**Comment by kabudu** [comment]
> By default, Prometheus scrapes the metrics every minute so I think you don't have enough data over one minute to calculate the rate.

Thanks for the insight, that was the problem. It didn't even occur to me that there could be an issue with the sample size. I'll keep that in mind as I continue to experiment with Grafana..
