### ISSUE TITLE
[stable/fluent-bit] Unable to use all configuration keys in ES output section.

### ISSUE THREAD

**Issue by onyxet** [helm/charts#8279]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm: v2.11.0, K8S: v1.9.6

**Which chart**: fluent-bit

**What happened**: Installed latest stable chart and tried to use ES output. When I configured TLS and basic auth in values.yaml I found that configuration for fluent-bit didn't contain it. Then I checked template of configmap and found that some sections from ES output are located in splunk output. Next config keys should be moved into ES output section:
- backend.es.logstash_prefix
- .backend.es.index
- backend.es.http_user
- backend.es.http_passwd
- backend.es.tls
- backend.es.tls_verify 
- backend.es.tls_debug

**What you expected to happen**: Fully working ES output with ability to use tls and basic auth

**How to reproduce it** (as minimally and precisely as possible): Use ES instance with TLS and basic auth enabled and try to configure fluent-bit for flushing logs into it

**Anything else we need to know**:

**Comment by kdhtrifork** [comment]
There is already a MR for that https://github.com/helm/charts/pull/8166

**Comment by onyxet** [comment]
@kdhtrifork Cool. Thanks
