### ISSUE TITLE
Unable to access kafka brokers from outside of cluster

### ISSUE THREAD

**Issue by ishantanu** [helm/charts#8283]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm version:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kafka

**What happened**:
I am trying to access kafka brokers from outside of k8s cluster for IoT use case. I've already made changes for external dns config in `values.yml`.

**What you expected to happen**:
Kafka brokers accessible from outside of k8s.

**How to reproduce it** (as minimally and precisely as possible):
1. Enable external settings related config in `values.yml` in kafka helm chart. 
2. Install helm chart on cluster and try to access the brokers externally with kafkacat.

**Comment by agolomoodysaada** [comment]
Which kubernetes service are you using to access Kafka externally?
By default, it uses NodePort services with ports 31090+.
Those services are named `*-external`.
This means you need your connection string to connect directly to the VMs. If you have a cluster loadbalancer, you should be able to add inbound rules that map ports 31090+ to your VMs.

**Comment by agolomoodysaada** [comment]
I think you should use an ELB for the worker nodes and use that ELB ip as the advertised listerner. For example in your values file: 

```yaml
  configurationOverrides:
    "advertised.listeners": |-
      EXTERNAL://<<INSERT WORKER NODE ELB_IP_ADDRESS >>:$((31090 + ${KAFKA_BROKER_ID}))
```

Also make sure the ELB has inbounnd rules for ports 31090, 31091, ...

**Comment by iamShantanu101** [comment]
Did you mean to say that I should create a LoadBalancer service for each broker? Because I am not sure how routing will work when I will create an ELB for 2 nodes. Won't it need some sort of ingress controller?

**Comment by agolomoodysaada** [comment]
One ELB is enough. One ELB with several forwarded ports should work well. Ingress could work as well but you might need special TCP configurations. I suggest you read about [NodePorts](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport)

**Comment by iamShantanu101** [comment]
@agolomoodysaada I got this working by accessing the brokers on `node-IP:port` with NodePorts.
