### ISSUE TITLE
[incubator/jaeger] Wrongly templated ES host

### ISSUE THREAD

**Issue by sta-szek** [helm/charts#8298]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT
**Version of Helm and Kubernetes**:
k8s - 1.10.3
```
$ helm version 
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

**Which chart**:
jaeger version: 0.7.0

**What happened**:
Value from `storage.elasticsearch.host` is used in query, collector and spark job which is wrong.
Value for collector and query must be without protocol, e.g. `https://` and for spark job must be prefixed with `https://` if ES is secured.

This causes that all components cannot work together.

Logs from spak job if es host is without protocol:
```
$ kubectl -n monitoring logs -f jaeger-spark-1538696940-qx2wh 
18/10/05 09:07:13 INFO ElasticsearchDependenciesJob: Running Dependencies job for 2018-10-05T00:00Z, reading from jaeger-span-2018-10-05 index, result storing to jaeger-dependencies-2018-10
-05/dependencies 
18/10/05 09:07:14 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable 
18/10/05 09:15:48 ERROR NetworkClient: Node [10.10.1.51:9200] failed (Operation timed out (Connection timed out)); selected next node [https://10.10.2.200:443] 
Exception in thread "main" org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: No data nodes with HTTP-enabled available 
```

If I add prefix then collector and query stop working.

**What you expected to happen**:
Spark job and ES storage work together

**How to reproduce it** (as minimally and precisely as possible):
```
storage:
  type: elasticsearch
  elasticsearch:
    scheme: https
    host: some.host
    port: 443
    user: ""
    password: ""
    nodesWanOnly: false

spark:
  enabled: true
```

**Comment by mentalblock** [comment]
I believe this is still a relevant and critical issue.
