### ISSUE TITLE
Add NOTES.txt for patroni chart

### ISSUE THREAD

**Issue by linki** [helm/charts#83]
charts for helm `v2.alpha.4+` should have a `NOTES.txt` to explain usage and additional information.

add a `NOTES.txt` for the `patroni` chart (https://github.com/kubernetes/charts/pull/57)

**Comment by lasomethingsomething** [comment]
Hi @viglesiasce, do you know when you might get around to checking out @mikkeloscar's commit?

**Comment by viglesiasce** [comment]
@LappleApple sorry for the delay.
