### ISSUE TITLE
Specify nodeport for tcp/udp services

### ISSUE THREAD

**Issue by fritchie** [helm/charts#8308]
Feature Request:

It would be nice to be able to specify a nodeport for tcp/udp services like you can for http/https here:

https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-service.yaml

**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:

nginx ingress

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by dalsh** [comment]
I confirm this would be nice to have. Otherwise when controller.service.type is set to NodePort, and a tcp port is specified, the corresponding nodePort will be set randomly in the controller service.

**Comment by stephenmuss** [comment]
Also running into this issue. Have controller service type as `NodePort` and need to be able to specify a node port rather than have a random one assigned.
