### ISSUE TITLE
[stable/ark]: Need a way to expose prometheus metrics and automatically create ServiceMonitor

### ISSUE THREAD

**Issue by agolomoodysaada** [helm/charts#8310]
**Is this a request for help?**: Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

  - Describe *in detail* the feature/behavior/change you'd like to see.

It should be easy to specify the port for exposing the prometheus endpoint for Ark. 

**Version of Helm and Kubernetes**: 2.9.1

**Which chart**: stable/ark

**What happened**: No way to expose prometheus metrics

**What you expected to happen**: Set some values in the values.yaml file to expose prometheus metrics and automatically create ServiceMonitor so that prometheus operator can start scraping those metrics.

**How to reproduce it** (as minimally and precisely as possible): N/A

**Anything else we need to know**: 

There are several examples such as `incubator/kafka` that support this expose of metrics easily.

**Comment by vsliouniaev** [comment]
@agolomoodysaada would you be interested in creating a PR to do this yourself?

**Comment by agolomoodysaada** [comment]
Sure. I'll post here when I get around some time to do it.
