### ISSUE TITLE
Influxdb environment variables are not working

### ISSUE THREAD

**Issue by jloaiza** [helm/charts#8313]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  BUG REPORT

**Version of Helm and Kubernetes**: 

```
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

```
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: influxdb

**What happened**: 

There is a section at the `values.yaml` file that is supposed to allow the user to declare environment variables used by the influxdb docker image, it says as follows:

```
## The InfluxDB image uses several environment variables to automatically
## configure certain parts of the server.
## Ref: https://hub.docker.com/_/influxdb/
env:
  # - name: INFLUXDB_DB
  #   value: "demo"
```
There are a set of variables that can be declared to create a default database and users with different roles (such as: INFLUXDB_DB, INFLUXDB_USER, ...).

There is also a section at the `values.yaml` file that sets a default user:

```
## Create default user through Kubernetes job
## Defaults indicated below
##
setDefaultUser:
  enabled: false
```

If you enable this section then the previously mentioned environment variables doesn't work.

**What you expected to happen**:

To found an initialized database with the name and users I declared using the environment variables.

**How to reproduce it** (as minimally and precisely as possible):

Enable the default user section, set the information of the user and also declare the INFLUXDB_USER, INFLUXDB_USER_PASSWORD, INFLUXDB_DB environment variables.

Enable the `auth_enabled` property of the `http` section.

Try to login to the database using the user previously declared at the environment variables. Try to list the databases and found the database you previously declared at the environment variables.

**Anything else we need to know**:

I think I figured out why this happen, and it could be because the following line of the init file of the influxdb docker image: https://github.com/influxdata/influxdata-docker/blob/master/influxdb/1.6/init-influxdb.sh#L14

It checks if there is no meta file in order to initialize the database with the environment variables `! "$(ls -d /var/lib/influxdb/meta 2>/dev/null)" `. The thing is that you guys are using a pod to initialize the default user, and this action (maybe not always) initializes the database before that line and so the script found a `meta` file and jumps the init section.

This could be resolved changing the template, so that it adds the default user as an environment variable with a secret, or well, just add a warning to the values file haha.

I've avoided this behavior disabling the defaultUser section and creating the admin user via environment variables.

**Comment by MaxDiOrio** [comment]
Variables defined in the HELM Chart answers section from within Rancher also do not make their way into the install.  I've seen Charts implement extraEnv configuration section that allows you to inject Environment variables into the container at launch.
