### ISSUE TITLE
[mongodb-replicaset] It should be possible to specify the namespace

### ISSUE THREAD

**Issue by mohitmutha** [helm/charts#8332]
**Is this a request for help?**: No
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST
Describe *in detail* the feature/behavior/change you'd like to see.
- We are deploying  the mongodb-replicaset in a different namespace from the application namespace. 
- We want to have the mongodb-replicaset as a subchart / dependency of our application chart. 
- Currently it is not possible to specify a separate namespace for the mongodb chart. We would like to propose the following

**Proposed alternative**
* It should be possible to specify the namespace through a value property. If the value property is not specified then the namespace specified in the `--namespace` parameter should be used

**Version of Helm and Kubernetes**:
`Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}`
`Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}`

**Which chart**: mongodb-replicaset

**Comment by steven-sheehy** [comment]
You can't deploy a subchart into a separate namespace from the parent chart. That's a limitation in Helm itself, not mongodb-replicaset. You should just deploy it as a separate chart instead of as a dependency.
