### ISSUE TITLE
[incubator/cassandra] Ability to override Cassandra configuration files

### ISSUE THREAD

**Issue by maver1ck** [helm/charts#8375]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature request

**Version of Helm and Kubernetes**:
Helm: 2.10
K8s: 1.10

**Which chart**:
incubator/cassandra

**What happened**:
There is no possibility of change to Cassandra configuration files

**What you expected to happen**:
Ability to change those files

**Comment by deyceg** [comment]
👍

**Comment by deyceg** [comment]
seems I'll be writing my own chart then...

**Comment by maver1ck** [comment]
ping @davidkarlsen
