### ISSUE TITLE
Prometheus is not scraping node-explorer and collecting node_* metrics

### ISSUE THREAD

**Issue by rorysavage77** [helm/charts#8386]
**Version of Helm and Kubernetes**:
```bash
charts (master ✘)✹✭ ᐅ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Kubernetes 1.12.1 - CentOS 7.5
```bash
# rpm -qa|grep -i kube
kubeadm-1.12.1-0.x86_64
kubernetes-cni-0.6.0-0.x86_64
kubelet-1.12.1-0.x86_64
kubectl-1.12.1-0.x86_64
```
Promethus version docker image: prom/prometheus:v2.4.3

**Which chart**:
prometheus

**What happened**:
I installed the prometheus server and prometheus-adapter charts per the README.md provided in the repo.  
```bash
helm install --name prometheus stable/prometheus
helm install --name prometheus-adapter stable/prometheus-adapter
```
Prometheus is collecting metrics for just about everything but "node_" metrics from the prometheus node-exporter.   Node exporter is running, and I am able to see the metrics node-exporter is retrieving from the host 

```bash
curl http://localhost:9100/metrics |grep node_
# HELP node_arp_entries ARP entries by device
# TYPE node_arp_entries gauge
node_arp_entries{device="docker0"} 14
node_arp_entries{device="eth0"} 7
node_arp_entries{device="weave"} 21
# HELP node_boot_time_seconds Node boot time, in unixtime.
# TYPE node_boot_time_seconds gauge
node_boot_time_seconds 1.53909549e+09
# HELP node_context_switches_total Total number of context switches.
# TYPE node_context_switches_total counter
node_context_switches_total 5.0819384e+08
# HELP node_cpu_guest_seconds_total Seconds the cpus spent in guests (VMs) for each mode.
# TYPE node_cpu_guest_seconds_total counter
node_cpu_guest_seconds_total{cpu="0",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="0",mode="user"} 0
node_cpu_guest_seconds_total{cpu="1",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="1",mode="user"} 0
node_cpu_guest_seconds_total{cpu="2",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="2",mode="user"} 0
node_cpu_guest_seconds_total{cpu="3",mode="nice"} 0
node_cpu_guest_seconds_total{cpu="3",mode="user"} 0
```

...etc...etc...

But I am NOT able to see these in Prometheus!!!  

**What you expected to happen**:  
See node_ metrics in Prometheus!!!

**How to reproduce it** (as minimally and precisely as possible):
```bash
helm install --name prometheus stable/prometheus
helm install --name prometheus-adapter stable/prometheus-adapter
```

```bash
ᐅ kubectl --namespace default port-forward `kubectl get all|grep pod/prometheus-server-|awk '{print $1}'|uniq` 9090
```

browse to http://localhost:9090 and look at the drop down, no node_ metrics!!!

**Anything else we need to know**:
Frustrated!!!  Documentation is lacking!

**Comment by rcsavage** [comment]
I just created a PR for this: https://github.com/helm/charts/pull/8390

Looks like you are missing the scraping job for node-exporter.  I am surprised nobody else has seen this and addressed it.

**Comment by lcavajani** [comment]
The scrape of prometheus node-exporter and kube-state-metrics is done by adding the [annotation](https://github.com/helm/charts/blob/master/stable/prometheus/values.yaml#L441-L443) : prometheus.io/scrape: "true" to the service. There is no need to declare a specific bloc for it.

Can you check the targets endpoints in Prometheus and check what you have for kubernetes-service-endpoints ?

**Comment by lcavajani** [comment]
This scraping configuration is defined here: https://github.com/helm/charts/blob/c679b675dec88945288c73b1663927e72002fbe0/stable/prometheus/values.yaml#L984-L1013
