### ISSUE TITLE
NOTES.txt loadBalancer service IP command doesn't work on AWS

### ISSUE THREAD

**Issue by prydonius** [helm/charts#84]
On AWS, LoadBalancer services get an Elastic Load Balancer hostname (*.region.elb.amazonaws.com), so the command charts are using in their NOTES.txt returns an empty string:

```
kubectl get svc --namespace {{ .Release.Namespace }} {{ template "fullname" . }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
```

should be 

```
kubectl get svc --namespace {{ .Release.Namespace }} {{ template "fullname" . }} -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
```

However, in GKE, you get an IP and hostname is blank so we can't switch to hostname.

We can use the following (nasty) `sed` to print out whatever isn't empty:

```
kubectl get svc --namespace {{ .Release.Namespace }} {{ template "fullname" . }} -o jsonpath='{.status.loadBalancer.ingress[0]}' | sed -E 's/.*"([^" ]+)".*/\1/'
```

/cc @viglesiasce @migmartri

**Comment by lachie83** [comment]
I wonder if this can be exposed by tiller as an output of the status command?

**Comment by prydonius** [comment]
@lachie83 I think it can be useful in NOTES.txt if you want to print out a specific path (e.g. [WordPress](https://github.com/kubernetes/charts/blob/master/stable/wordpress/templates/NOTES.txt#L15))

Been playing around, and the method I suggested above doesn't work anymore, I managed to find another hacky way:

```
kubectl get svc {{ template "fullname" . }} --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}"
```

**Comment by lachie83** [comment]
Looks good although having a tough time getting that by the go template rendering. Any luck getting that into NOTES.txt?

**Comment by prydonius** [comment]
@lachie83 check out https://github.com/kubernetes/charts/pull/177/files#diff-5e62c86851e1c53ed6bd260de2120fa8R21!

**Comment by lachie83** [comment]
I saw this as well today. https://github.com/kubernetes/charts/blob/master/stable/traefik/templates/NOTES.txt#L13

**Comment by lachie83** [comment]
I looks like we have some reasonable solutions. What do you propose as next steps?

**Comment by fhemberger** [comment]
@lachie83 Issue can be closed as the method described in https://github.com/kubernetes/charts/issues/84#issuecomment-257754892 is used everywhere.
