### ISSUE TITLE
Add @maver1ck as Trusted Collaborator

### ISSUE THREAD

**Issue by maver1ck** [helm/charts#8413]
Please add me as Trusted Collaborator to Helm Charts repository.
I talked with @mattfarina and this issue is "new way" of getting this role.

GitHub Username
@maver1ck

Sponsors
@davidkarlsen

My issues:
https://github.com/helm/charts/issues/8316
https://github.com/helm/charts/issues/8289
https://github.com/helm/charts/issues/7978
https://github.com/helm/charts/issues/7959
https://github.com/helm/charts/issues/7936
https://github.com/helm/charts/issues/7708
https://github.com/helm/charts/issues/7691
https://github.com/helm/charts/issues/7148
https://github.com/helm/charts/issues/7056
https://github.com/helm/charts/issues/6727
https://github.com/helm/charts/issues/4472
https://github.com/helm/helm/issues/4697
https://github.com/helm/helm/issues/4240
https://github.com/helm/helm/issues/4239
https://github.com/futuresimple/helm-secrets/issues/58
https://github.com/futuresimple/helm-secrets/issues/57
https://github.com/roboll/helmfile/issues/311
https://github.com/databus23/helm-diff/issues/81

PRs:
https://github.com/helm/charts/pull/8325
https://github.com/helm/charts/pull/8320
https://github.com/helm/charts/pull/8318
https://github.com/helm/charts/pull/8138
https://github.com/helm/charts/pull/7961
https://github.com/helm/charts/pull/7960
https://github.com/helm/charts/pull/7150
https://github.com/roboll/helmfile/pull/201
https://github.com/databus23/helm-diff/pull/62
https://github.com/databus23/helm-diff/pull/61
https://github.com/futuresimple/helm-secrets/pull/54

**Comment by davidkarlsen** [comment]
@maver1ck You've been added as a trusted collab.
Please read through https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md and it's links to see requirements for charts. You find us at https://kubernetes.slack.com/messages/C6E3XH1ED
