### ISSUE TITLE
[stable/concourse] username and password issue | Indefinite startup and termination of pods

### ISSUE THREAD

**Issue by demamoh** [helm/charts#8414]
**Is this a request for help?**:  Yes
---
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

Kubernetes: 1.10
Helm: v2.9.1

**Which chart**:

Concourse chart version: 2.0.2

**What happened**:

Username or password not working. This particular config makes it so the installation starts up with mount issues, and stays stuck in `ContainerCreating`. If I change create to "true" it installs but the username and password are not accepted as correct login credentials.  

**What you expected to happen**:

I expected the chart to install without being stuck in `ContainerCreating`, and terminate without being stuck on `terminating`, and after it starts up, be able to login with the username test and password test. 

**How to reproduce it** (as minimally and precisely as possible):

Use this below yaml
```
secrets:
  localUsers: "test:test"
  create: false
```

**Anything else we need to know**:

**Comment by demamoh** [comment]
@tareks I will give it a go now thanks.

**Comment by demamoh** [comment]
@tareks So that didn't work. I tried to signin with username: test, password: test and it gives me `login error: not authorized`.

**Comment by demamoh** [comment]
So it now lets me signin with the credentials `username: concourse`, and the `password: concourse`, but not the test:test that I expected.

**Comment by tareks** [comment]
Odd, it worked for me. Have you tried the base values.yaml provided with the chart as a test? It has the following:

`localUsers: "test:$2a$10$sDB6AsH2HheOWHILrnHVJOCZq/GYtUYE02ypJJTQBmWJNivYNhP3y"`

That also works when localAuth is enabled.

**Comment by demamoh** [comment]
Yeah. That was the first thing I did.

**Comment by tareks** [comment]
Can you try against a fresh/different database? I've seen it default to concourse/concourse when it's not happy with the localUser parameters. Are the logs saying anything useful?

**Comment by demamoh** [comment]
I'll give it a go. There was a tangent issue that popped up with workers dying. I'll delete the chart and start over.

**Comment by demamoh** [comment]
@tareks Things are still not working. I left the default values as they were. 

This is the values.yml that I am using. The helm chart recommended using btrfs but even with making the change it still says I am using naive.

```
worker:
  baggageclaim:
    driver: btrfs
secrets:
   localUsers: test:$2y$12$IxuOzPH3aUbgDYSlbL6K/Otju7zwu3ihXGjt2.d4Wr8DatbRoHtu.
```

**Comment by demamoh** [comment]
@tareks Turns out the workers are dying. Using the chart without any extra configuration. The test password and username at least work.

**Comment by tareks** [comment]
Good to hear you can login :)

Anything in the worker/web logs to indicate why? Sometimes the web instance (at least initially) will start up too late and the workers will have gone into CrashLoopBackOff by then and may need to be pruned. It depends on how fast containers are pulled etc. 

Can you connect using the fly cli to see the state of the workers? If they are stalled, try to prune the workers after the pods restart and see if that helps.

**Comment by demamoh** [comment]
@tareks I can't see the workers at all using the fly cli. I have manually restearted the pods but the error still persists. This is a a snapshot of the  of what one of the workers is outputting in the logs. 

```
{"timestamp":"1539813462.876529932","source":"worker","message":"worker.garden.extract-resources.extract.failed-to-extract-resource","log_level":2,"data":{"error":"exit status 2","output":"/concourse-work-dir/4.2.1/assets/bin/tar: etc/ssl/certs/02265526.0: Cannot utime: No such file  or directory\n/concourse-work-dir/4.2.1/assets/bin/tar:
```

Here is the env of the worker and the result of the liveness probe
```
Environment:
      CONCOURSE_WORK_DIR:                /concourse-work-dir
      CONCOURSE_TSA_HOST:                concourse3-web:2222
      CONCOURSE_TSA_PUBLIC_KEY:          /concourse-keys/host_key.pub
      CONCOURSE_TSA_WORKER_PRIVATE_KEY:  /concourse-keys/worker_key
      CONCOURSE_GARDEN_BIND_PORT:        7777
      CONCOURSE_BAGGAGECLAIM_DRIVER:     btrfs
      LIVENESS_PROBE_FATAL_ERRORS:       guardian.api.garden-server.create.failed
baggageclaim.api.volume-server.create-volume-async.failed-to-create
    Mounts:
```

**Comment by tareks** [comment]
is `concourse3-web` a valid service within the same namespace you're deploying the workers into? 

Have you made any other changes to the values.yaml? You should be able to use the stock one with very little change to get a basic functional system (assuming ingresses aren't involved).

**Comment by tareks** [comment]
I just ran `helm install stable/concourse` on a fresh EKS cluster and got the following:
```
NAME                                          READY     STATUS    RESTARTS   AGE
terrifying-sheep-postgresql-5989d6f79-kgjmk   1/1       Running   0          5m
terrifying-sheep-web-74d554757c-f42kz         1/1       Running   0          5m
terrifying-sheep-worker-0                     1/1       Running   2          5m
terrifying-sheep-worker-1                     1/1       Running   3          5m
```
PVCs look  like this:
```
NAME                                           STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
concourse-work-dir-terrifying-sheep-worker-0   Bound     pvc-344bf540-d324-11e8-89d5-12b644ebd5c4   20Gi       RWO            medium         5m
concourse-work-dir-terrifying-sheep-worker-1   Bound     pvc-344e184f-d324-11e8-89d5-12b644ebd5c4   20Gi       RWO            medium         5m
terrifying-sheep-postgresql                    Bound     pvc-34374e8b-d324-11e8-89d5-12b644ebd5c4   8Gi        RWO            medium         5m
```

Services look like this:
```
terrifying-sheep-postgresql   ClusterIP   10.100.73.133   <none>        5432/TCP            5m
terrifying-sheep-web          ClusterIP   10.100.37.204   <none>        8080/TCP,2222/TCP   5m
terrifying-sheep-worker       ClusterIP   None            <none>        <none>              5m
```
Namespaces:
```
NAME                    STATUS    AGE
default                 Active    35m
kube-public             Active    35m
kube-system             Active    35m
terrifying-sheep-main   Active    7m
```
I haven't defined any ingresses or anything other than the defaults and didn't verify logging in, but the workers are definitely running and connected to the web instance.

Do you get to this state? If not, there might be something more fundamental that's not right on the cluster itself.

**Comment by demamoh** [comment]
I do get up to that point. The kubernetes cluster that I use is the one that gets bundled with `docker for mac`.  I tried this on different mac computers and the problem still occurs. I'll try to give this a go on different platforms, but it definitely is an issue on `docker for mac kubernetes`.

**Comment by demamoh** [comment]
@tareks Setup up a new cluster in gcloud
