### ISSUE TITLE
bug in exporter configuration template

### ISSUE THREAD

**Issue by larstonne** [helm/charts#8427]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm: Version form Rancher v2.1.0
Kubernetes: v1.11.3

**Which chart**:
postgresql/templates/delpoyment.yml

**What happened**:
metrics tries to connect to non existing database

**What you expected to happen**:
metrics connects to database defined in values

**How to reproduce it** (as minimally and precisely as possible):
start template with any databasename not matching username

**Anything else we need to know**:
Code as is::
{{- if .Values.metrics.enabled }}
      - name: metrics
        image: "{{ .Values.metrics.image }}:{{ .Values.metrics.imageTag }}"
        imagePullPolicy: {{ default "" .Values.metrics.imagePullPolicy | quote }}
        env:
        - name: DATA_SOURCE_NAME
          value: postgresql://{{ default "postgres" .Values.postgresUser }}@127.0.0.1:5432?sslmode=disable
        {{- if .Values.metrics.customMetrics }}
        - name: PG_EXPORTER_EXTEND_QUERY_PATH
          value: /conf/custom-metrics.yaml
        {{- end }}
        ports:
        - name: metrics
          containerPort: 9187
code as ShouldBe:
value: postgresql://{{ default "postgres" .Values.postgresUser }}@127.0.0.1:5432/{{ default "postgres" .Values.postgresDatabase }}?sslmode=disable

**Comment by tompizmor** [comment]
@larstonne could you check if this is still an issue with the current version of the PostgreSQL chart? There have been major changes in the Postgres chart and the metrics code is not the one shown in the issue description anymore.

**Comment by tompizmor** [comment]
Thanks for letting me know! I will prepare a PR for that
