### ISSUE TITLE
[stable/stolon] needs a way to specify pull secrets so the image can come from a private registry

### ISSUE THREAD

**Issue by Shraa** [helm/charts#8436]
If you try to make a custom image stored on a private repository, there is no way in the chart to specify the secret to pull the image with.

**Version of Helm and Kubernetes:** helm 2.9.1, and Kubernetes 1.11.3

**Which chart:** stable/stolon

**What happened:** Unable to pull an image from a private repository with a password.

**What you expected to happen:** I expected to be able to use a custom image pulled from a private repository, specifying the pullSecrets as a value

**Comment by Shraa** [comment]
What need i do to verify it?

**Comment by francois-travais** [comment]
I guess you would need to pull a stolon image from a private registry.

**Comment by Shraa** [comment]
yes, i need to pull a stolon image with installed postgis extension from my private registry (nexus OSS or gitlab.com)

**Comment by Shraa** [comment]
I can't see 'image.pullSecrets' option in the README.md of master branch

**Comment by francois-travais** [comment]
Indeed it's not because it's only implemented in my [PR](https://github.com/helm/charts/pull/8607)

**Comment by Shraa** [comment]
@francois-travais, what should happen so that PR will be accepted?

**Comment by francois-travais** [comment]
I have no idea, I'm not a maintainer. Apparently the PR is assigned to @sameersbn, I guess he could do something about it.
