### ISSUE TITLE
[stable/enjoy] [feature request] - explode content of envoy.yaml

### ISSUE THREAD

**Issue by draeron** [helm/charts#8482]
Instead of considering all the content of envoy.yaml as a single text, having it as a yaml structure would enable merge the content from multiple value files. Check `stable/grafana` for an example.

ex : `helm install myrelease -f shared.values.yaml -f this.release.yaml stable/envoy`

this would require something like this in `templates/configmap.yaml` 

```yaml
  files:
    envoy.yaml : # note the removal of |- 
      # [...] 
```

Then you would have to modify the _templates/configmap.yaml_ with something like this :

```yaml
{{- if .Values.files }}
  {{- range $key, $value := .Values.files }}
  {{ $key }}: |
{{ toYaml $value | indent 4 }}
  {{- end -}}
{{- end -}}
```

**Comment by draeron** [comment]
should i tag the owner? 

@josdotso

**Comment by draeron** [comment]
it would break current usage of the chart though

**Comment by josdotso** [comment]
Agreed.  However, we could bump the semantic major version number to communicate that.
