### ISSUE TITLE
[stable/redmine] Chart is failing to deploy however all services are reachable.

### ISSUE THREAD

**Issue by guglez** [helm/charts#8500]
**Version of Helm and Kubernetes**:
Helm:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

```
**Which chart**:
stable/redmine

**What happened**:
I'm trying to deploy this chart via this command (and via terraform s well):
`helm --debug install -n redmine stable/redmine -f infrastructure/redmine/values.yaml --wait
`
Database and redmine container are able to deploy and they are reachable via browser however I see this error message:
`release redmine failed: timed out waiting for the condition
`

command
`"helm list --all | grep redmine"`
returns this:
`redmine                              	1       	Tue Oct 16 13:35:56 2018	FAILED  	redmine-5.1.0                          	3.4.6`

Logs from kubernetes:
```
16m         Normal    Created                 Pod                     Created container
16m         Normal    Pulled                  Pod                     Successfully pulled image "docker.io/bitnami/redmine:3.4.6-debian-9"
16m         Normal    Started                 Pod                     Started container
15m         Warning   Unhealthy               Pod                     Readiness probe failed: Get http://10.42.4.179:3000/: dial tcp 10.42.4.179:3000: connect: connection refused
15m         Warning   Unhealthy               Pod                     Readiness probe failed: Get http://10.42.4.179:3000/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

```

**What you expected to happen**:
I expect that this chart can be deployed.

**How to reproduce it** (as minimally and precisely as possible):
Use this command:
`helm --debug install -n redmine stable/redmine -f infrastructure/redmine/values.yaml --wait
`

**Anything else we need to know**:
If I use this command (--wait parameter is removed) than it works:
`helm --debug install -n redmine stable/redmine -f infrastructure/redmine/values.yaml`

**Comment by tompizmor** [comment]
Hi @guglez,

The `--wait` option makes the `helm install` command to wait for as long as `--timeout` option (300 seconds by default). Is it possible that you need more time than that until all chart resources are up and running? 

Also, I guess the `infrastructure/redmine/values.yaml` files is a file that you have prepared with custom values. Do you also see the issue if you use the default values?
