### ISSUE TITLE
[stable/rabbitmq-ha] Cannot start rabbitmq when using an existing secret

### ISSUE THREAD

**Issue by francois-travais** [helm/charts#8510]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: 

stable/rabbitmq-ha

**What happened**:

I stored RabbitMQ passwords in a secret I created a manually before the install. I specified the existing secret name in `values.yaml`. I also added custom policies.

RabbitMQ fail to start because it is missing `definitions.json` which is indeed not mounted when using an existing secret. see https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/templates/statefulset.yaml#L157

**What you expected to happen**:

I expected to be able to store my passwords in an existing secret and run RabbitMQ successfully. I'm also expecting to be able to specify custom policies at the same time.

**How to reproduce it** (as minimally and precisely as possible):

1. create a secret manually in kubernetes with the following keys: `rabbitmq-username`, `rabbitmq-password`, `rabbitmq-erlang-cookie`

2. put the newly created secret name in `values.yaml` (key `existingSecret`)

3. install the chart and check the logs

**Anything else we need to know**:

I suspect that `definitions.json` is not mounted because it contains information stored in the existing secret, and because `definitions.json` is generated by helm, there is no way to get the password in the file.

**Comment by steven-sheehy** [comment]
You will need to provide a definitions.json in the existing secret as well. See the [_helpers.tpl](https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/templates/_helpers.tpl) for the format.

I'm curious, what is the reason you're using an existing secret? What advantage does that provide over the built-in one?

**Comment by francois-travais** [comment]
As a matter of fact I did but that's not the problem, just look at this line: https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/templates/statefulset.yaml#L157. If one provides an existing secret, there is no way a `definitions.json` will find it's way in the container.

As for the reason to use an exiting secret, I don't want to write passwords in plain text in a `values.yaml`, and I don't want to provide them on the command line every time I invoke helm. So to me it looks much more convenient to store the secret in kubernetes once and for all.

**Comment by francois-travais** [comment]
ping @steven-sheehy

**Comment by steven-sheehy** [comment]
@francois-travais You're correct, it does look like an issue. A PR would be needed to address it.

**Comment by mdomke** [comment]
@francois-travais are you already working on a PR for this? I'm having the same problem and would otherwise work on this.

**Comment by francois-travais** [comment]
@mdomke no I'm not and I won't.

I submitted other PRs (#9311, #9224 and #9222), none of them got merged, and if an issue existed for them, they got closed even so they are pretty simple fixes.

I'm done trying to improve this chart, I did my own company-internal fork.

**Comment by steven-sheehy** [comment]
@francois-travais Your PRs have never been assigned to anyone, so that's why no one even looks at them. I understand your frustration, but there are only a handful of approvers and 400+ PRs. If you bump their chart versions, I can assign to someone and try to get them noticed and approved as they're good improvements. Or if you're against that, maybe I can create a combined PR incorporating your changes.

**Comment by vrathore18** [comment]
what's the status of this issue?
