### ISSUE TITLE
rabbitmq-ha chart is not setting correct cookie value for all the pods when using persistent volume of type hostpath

### ISSUE THREAD

**Issue by HariNarayananMohan** [helm/charts#8518]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes  1.9.9 - client, 1.11.1 - server 
helm v2.7.2 - client, v2.9.1 - server 

**Which chart**:
stable/rabbitmq-ha

**What happened**:
This chart works as expected with the default values. But it didn't work as expected when I used PVs. I enabled Persistent Volume and used a storage class that has Hostpath type PV by updating the values.yaml file. Also I provided a cookie value in the values.yaml file. The chart is not setting the correct cookie value in the pods, instead each pod is having a different cookie value that is randomly generated. This affects the rabbitmq cluster formation. 

**What you expected to happen**:
I expected all the pods should have the same cookie value in order to successfully form the rabbitmq cluster.

**How to reproduce it** (as minimally and precisely as possible):
Enable PV and Use storage class that uses hostpath type pv. 

**Anything else we need to know**:
I didn't try any other type PVs. I only have hostpath type PV. The cookie value is set correctly when I don't use the PV.  
I tried this several times and each time I see one of the pods having the correct cookie value which was given in values.yaml file and other pods having different randomly generated cookie value. 
Even if the cookie is not provided in the values.yaml and leveraged the default way of random cookie generation in the secret, only one of the pods is getting the correct cookie value from the secret and others two pods are having different cookie values.

**Comment by HariNarayananMohan** [comment]
I created 3 PVs using below mentioned yaml file, and then installed by updating below values in values.yaml file before the helm install

```## Data Persistency
persistentVolume:
  enabled: true
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: "local-storage"
  name: data
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}
```
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-043
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /tmp
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
```

**Comment by steven-sheehy** [comment]
I definitely wouldn't use /tmp as a volume. The OS can delete out of there at any time.

Since you're provisioning using hostPath, I'm assuming you're also putting a hard anti-affinity so the pods don't get scheduled on the same node? If there's multiple on one node, they can be attempting to write to the same host directory.

**Comment by HariNarayananMohan** [comment]
Wow! I apologize for my ignorance, this is a great piece of information for me. After I changed the path for each hostpath type PVs the cookie was set correctly. 
Thanks a ton!

**Comment by steven-sheehy** [comment]
Glad I can help. Can you please close this issue?

**Comment by HariNarayananMohan** [comment]
@steven-sheehy  I'm facing another issue with the rabbitmq chart. 
I get `failed to get nodes from k8s - 403 ` error in the logs when I deploy in any other namespace than default. I think the service mentioned in the config file is the reason for this as it is only available in default namespace.

`the cluster_formation.dns.hostname =kubernetes.default.svc.cluster.local`

 I get 403 when I deploy in other namespaces and I'm not able to reach it or not resolving. 

can you please tell me how to access it from other namespaces ?

**Comment by steven-sheehy** [comment]
`kubernetes.default.svc.cluster.local` is a special service created in the default namespace that points to the kube-apiserver. It's how rabbitmq-ha can list k8s nodes by contacting k8s API. Verify you have this service there:

`kubectl get service kubernetes -n default -o wide`

If you've deleted that service you can create one manually there or create one in your own namespace and update the rabbitmq configmap to point to it.

**Comment by HariNarayananMohan** [comment]
Thanks for your response!
Everything works fine in default namespace. But only when I deploy in other namespaces I get this error. I tried creating that service in a non-default namespace, and getting the below error 
```
2018-10-22 21:15:29.651 [info] <0.203.0> Peer discovery backend does not support locking, falling back to randomized delay
2018-10-22 21:15:29.651 [info] <0.203.0> Peer discovery backend rabbit_peer_discovery_k8s does not support registration, skipping randomized startup delay.
2018-10-22 21:17:37.410 [info] <0.203.0> Failed to get nodes from k8s - {failed_connect,[{to_address,{"kubernetes.rak.svc.cluster.local",443}},
                 {inet,[inet],etimedout}]}
```
