### ISSUE TITLE
traefik kvprovider etcd ssl client cert ?

### ISSUE THREAD

**Issue by KlavsKlavsen** [helm/charts#8525]
Hi,
I am trying to figoure out what is a valid setting for:

kvprovider.$name.tls.cert 

is it just a path on local filesystem to a file - which you will then use to setup the secret?

**Comment by gaui** [comment]
Yes, it's just a path, same as in `[etcd.tls]` in traefik.toml: https://docs.traefik.io/v1.4/configuration/backends/etcd/

**Comment by KlavsKlavsen** [comment]
How do I get helm to add a secret (to get k8s to mount the certs-secret in the traefik container) ?
