### ISSUE TITLE
Do some SEO

### ISSUE THREAD

**Issue by craigbox** [helm/charts#856]
searching for 'helm chart X' invariably gives me Old Helm URLs in results.

Are we ready for that not to be the case?

**Comment by seanknox** [comment]
Hi @craigbox, SEO is not a goal of charts project.

**Comment by craigbox** [comment]
@seanknox Sorry, I wasn't clear in my request. 

If Helm v1 is now deprecated (I see 'obsolete' in the descriptions) then some work should be done to ensure that when you search for things like "cassandra helm" you get a result which says "Helm v2 chart for Cassandra", not "OBSOLETE DO NOT USE" with no other result.

I have opened https://github.com/helm/charts-classic/issues/102 as it's that project that needs to change.
