### ISSUE TITLE
Concourse chart has a static user/password

### ISSUE THREAD

**Issue by jpds** [helm/charts#8568]
Every single Concourse deployment delivered by this chart has a `test`/`test` username and password. Even if you enabled something like Github authentication as I have.

https://github.com/helm/charts/blob/c890b997bb7b23bdce774b8e723668649132d005/stable/concourse/values.yaml#L971

This should be either be removed completely or be auto-generated like the Grafana chart does.

@frodenas @william-tran

**Comment by cirocosta** [comment]
Hey @jpds ,

I just submitted https://github.com/helm/charts/pull/9525, which should address this issue 👍 

Is that what you meant?

thx!

**Comment by jpds** [comment]
@cirocosta Yep, this looks good.

**Comment by cirocosta** [comment]
Hey, per https://github.com/helm/charts/pull/10766, I'd say this one can be closed :+1:  

Thanks for the suggestion, @jpds ! For the rationale regarding going for pure documentation, see https://github.com/helm/charts/pull/9525#issuecomment-454181068.

Thanks!

**Comment by cirocosta** [comment]
cc @paulczar
