### ISSUE TITLE
Who is responsible for spinnaker images on quay

### ISSUE THREAD

**Issue by VictorDenisov** [helm/charts#857]
I'm trying to use the latest image of deck from quay and it fails to start. The error message is: npm command is not found. Who builds those images?

**Comment by seanknox** [comment]
Hi @VictorDenisov, please file issues with upstream projects with the projects themselves.

**Comment by evaldasou** [comment]
@VictorDenisov @seanknox but it does not work , we should fix it.
I just simply deploy Spinnaker with helm and newest Deck image crashes :

```
root:spinnaker# kubectl logs spinnaker-spinnaker-deck-4123252478-44wvg 
/bin/bash: npm: command not found
```

This image has an issue : `gcr.io/spinnaker-marketplace/deck:1.3.0-72`
