### ISSUE TITLE
rbac apiVersion not set when running helm template

### ISSUE THREAD

**Issue by mrsmuneton** [helm/charts#8582]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Helm Version: Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Kubernetes Version:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8", GitCommit:"7eab6a49736cc7b01869a15f9f05dc5b49efb9fc", GitTreeState:"clean", BuildDate:"2018-09-14T15:54:20Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/jenkins

**What happened**:
Using helm template and kubectl create, the rbac apiVersion is not set.  An error arises:
`error: error validating "deployChart.yaml": error validating data: apiVersion not set; if you choose to ignore these errors, turn validation off with --validate=false`
on delete:
`no matches for kind "ClusterRoleBinding" in version ""`

**What you expected to happen**:
kubectl create to complete with no errors

**How to reproduce it** (as minimally and precisely as possible):
values.yaml:
```
rbac:
  install: true
```
**run the commands:**
```
helm template -f values.yaml jenkins > deployChart.yaml
kubectl create -f deployChart.yaml
```

**Anything else we need to know**:
https://github.com/helm/charts/pull/8583

**Comment by stieler-it** [comment]
@mrsmuneton I am experiencing the same problem while trying to upgrade Jenkins. The referenced PR has not been merged. Is there a workaround / other solution?

**Comment by mrsmuneton** [comment]
@stieler-it I just hardcoded the change in my chart locally, and reapply after a `helm fetch`.
I closed the PR due to inactivity, I'll reopen now that you mention the same issue occurs for you.

The reason this issue arises is running `helm template` compiles in a different context than `helm install`.  The `template` command is unaware of the cluster Capabilities, so this workaround assumes the rbac api is a Capability of the target cluster.

**Comment by stieler-it** [comment]
I have deleted our Jenkins deployment for now so I can't provide more details. I will create a new deployment for us but maybe it is still relevant for other users.

**Comment by jpalomaki** [comment]
I also see this, fixed by inserting the API version manually after templating: `sed -i '/kind: ClusterRoleBinding/iapiVersion: rbac.authorization.k8s.io\/v1' path/to/jenkins.yaml`

**Comment by maorfr** [comment]
Hey guys,

Why are you installing the chart using `kubectl` and not using `helm`?
I want to better understand this issue...

**Comment by stieler-it** [comment]
@maorfr I'm pretty sure I have been using helm directly. If this issue only occurs when using helm template, we probably experience a different problem. Sorry for not providing more details in the first place - I can't remember the exact problem now.

**Comment by maorfr** [comment]
thanks for you response!

let's wait for @mrsmuneton and @jpalomaki to respond.
If this is not an issue at this time i would suggest we close it. We can always reopen ;)

**Comment by mrsmuneton** [comment]
Thanks for following up @maorfr 
The deployment process for my use case is to simply use `helm template`, I don't install Tiller on the cluster (security hardening measure).
I don't believe this issue will occur if using `helm install`, i think this is unique to `helm template` since the `template` command doesn't connect to any remote cluster and cannot derive the Capability. 
My PR https://github.com/helm/charts/pull/8583 sets a sensible default for the `helm template` case.

**Comment by maorfr** [comment]
I have the perfect solution for you-
Tiller-less helm!
Read this post by @rimusz for details:

https://rimusz.net/tillerless-helm/

What do you think?

**Comment by mrsmuneton** [comment]
Thanks for the feedback.
Tiller-less helm is cool! However it is not an option for my use case at this time, as my team's discussion around Tiller is closed and we are happy with our solution of using `helm template`.
If you want to close this issue with that as the recommended solution, its fine.  I'll continue to modify the chart to support my use case of `helm template`.

**Comment by maorfr** [comment]
I think that a PR identical to yours was already merged...
https://github.com/helm/charts/blob/master/stable/jenkins/templates/rbac.yaml

Am I missing anything?

**Comment by maorfr** [comment]
Isn't the current situation already handling your PR?
https://github.com/helm/charts/blob/master/stable/jenkins/templates/rbac.yaml

**Comment by mrsmuneton** [comment]
Oh you're right, someone copied my changes and got them successfully merged! done and done 👍

**Comment by maorfr** [comment]
@jpalomaki If tiller-less helm will not work for you, you can also consider (if you haven't already) TLS communication between Helm and Tiller.
I wrote a post about it a while ago, you are welcome to use it -
https://medium.com/nuvo-group-tech/configure-helm-tls-communication-with-multiple-kubernetes-clusters-5e58674352e2
