### ISSUE TITLE
Add @stealthybox as a Trusted Collaborator

### ISSUE THREAD

**Issue by stealthybox** [helm/charts#8636]
I'm an existing kubernetes org member and am eligible per:
https://github.com/helm/charts/blob/deb8322/README.md#trusted-collaborator

I've reviewed https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md

Here are some small authored and merged changes to Jenkins:
https://github.com/pulls?utf8=%E2%9C%93&q=author%3Astealthybox+user%3Ahelm

/cc @bacongobbler 
:)

**Comment by bacongobbler** [comment]
Thanks @stealthybox!

cc'ing the @helm/charts-maintainers on this one; I'm not officially a charts maintainer so I have no say in this matter :)

**Comment by viglesiasce** [comment]
Hey @stealthybox!

It would be good to show some reviews of charts that you've done as well before we add you to the repo. If you haven't yet then applying the guidelines you pointed out to existing PRs would be a great way to show your engagement with the repo. 

Thanks for wanting to engage more deeply on the Charts repo, looking forward to working together.

**Comment by stealthybox** [comment]
Oh, I'm prioritizing this review because it affects the work to upstream kube-prometheus: 
https://github.com/helm/charts/pull/6765#issuecomment-414266399

**Comment by stealthybox** [comment]
Bump

I've also been reviewing some work related to adding ServiceMonitor to the elasticsearch charts.
Here's one of those patches:
https://github.com/helm/charts/pull/8228

**Comment by prydonius** [comment]
@stealthybox sorry for the delay - sent an invite to add you as a read-only contributor to this repo. Thanks!!
