### ISSUE TITLE
[stable/kured] clusterroles.rbac.authorization.k8s.io "kured" is forbidden

### ISSUE THREAD

**Issue by timfpark** [helm/charts#8649]
**Is this a request for help?**:

NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

Helm 2.11.0
Kubernetes 1.11.3

**Which chart**:
stable/kured

**What happened**:

Tried to install chart with:

$ helm install stable/kured --name kured --namespace kured

and received the error:

Error: release kured failed: clusterroles.rbac.authorization.k8s.io "kured" is forbidden: attempt to grant extra privileges: [{[get] [] [nodes] [] []} {[patch] [] [nodes] [] []} {[list] [] [pods] [] []} {[get] [] [replicationcontrollers] [] []} {[get] [apps] [statefulsets] [] []} {[get] [extensions] [daemonsets] [] []} {[get] [extensions] [replicasets] [] []} {[get] [batch] [jobs] [] []} {[create] [] [pods/eviction] [] []}] user=&{system:serviceaccount:kube-system:default afbb94d2-d668-11e8-9397-7a83a8749569 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]

**What you expected to happen**:

Chart to install, or the chart to have documentation about what I need to configure in RBAC.

**How to reproduce it** (as minimally and precisely as possible):

See above

**Anything else we need to know**:

**Comment by timfpark** [comment]
@plumdog

**Comment by plumdog** [comment]
@timfpark I'm fairly sure that error means that tiller doesn't have permission to create the clusterrole. I suspect that means your tiller pod is not running as a `cluster-admin`, but rather as something with more limited permissions.

If that is the case, then running:
```
helm install stable/kured --name kured --namespace kured --set rbac.create=false
```
ought to install the chart (at least, should make that error go away), though you'll then need to manually create the [clusterrole](https://github.com/helm/charts/blob/master/stable/kured/templates/clusterrole.yaml) and [clusterrolebinding](https://github.com/helm/charts/blob/master/stable/kured/templates/clusterrolebinding.yaml) yourself.

Depending on what permissions your tiller pod has, it may not be able to create serviceaccounts, in which case you'll need to set `serviceAccount.create=false` and set `serviceAccount.name=[mykuredserviceaccount]` and create this manually too, and link it with the clusterrolebinding.

FWIW, I'm not really very familiar with having to handle rbac any other way than letting helm do it, hence why the above is a bit vague.

**Comment by plumdog** [comment]
@timfpark I hope that my response was reasonably useful, and https://github.com/helm/charts/pull/9206 may also be relevant here.

At any rate, I think that maybe this issue can be closed?

**Comment by timfpark** [comment]
Yes - that was extremely helpful - thanks!
