### ISSUE TITLE
[stable/mongodb] use hostPath volume?

### ISSUE THREAD

**Issue by steebchen** [helm/charts#8660]
**Is this a request for help?**: yes

---

How can I map a host path from a node for my mongodb storage?
I have 3 mongodb nodes and I simply want to map a path from the node like /data/db to the pod. Is that possible? Or do I have to manually create PVs which are basically a HostPath and then somehow put that into the mongodb config?

**Version of Helm and Kubernetes**:
helm v2.10.0
kubectl v1.12.1

**Which chart**:
stable/mongodb

**Comment by steebchen** [comment]
I guess it can be solved by using [local persistent volumes](https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/).

**Comment by steebchen** [comment]
Thanks for the link, it looks cool. Is it production ready, though? Also, can it work with reclaimPolicy Retain?

It's a bit annoying with normal local PVs because I have to create them manually, but it's acceptable.

**Comment by juan131** [comment]
Hi @steebchen 

The default Reclaim Policy is "Delete" on dynamically provisioned PV. See https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/#why-change-reclaim-policy-of-a-persistentvolume

You can modify the default StorageClass (https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/) so the `reclaimPolicy` used on dynamic PVs is "Retain". Run the command below for more information:

```
$ kubectl explain storageclass.reclaimPolicy
```
