### ISSUE TITLE
Request to add myself as a trusted collaborator

### ISSUE THREAD

**Issue by desaintmartin** [helm/charts#8663]
Hello guys,
After some time reviewing and create PRs for charts, I now feel blocked because of no ability to ok-to-test other people's PRs.
This is why I ask to be added as a Trusted Collaborator.

Here are a few of my contributions so far to charts.git:
- PRs: https://github.com/helm/charts/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+author%3Adesaintmartin+ (~30)
- Issues: https://github.com/helm/charts/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Adesaintmartin+ (mostly "upgradability" issues)
- Reviews: https://github.com/helm/charts/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Adesaintmartin+ (~15)

Cheers!

cc @mattfarina @scottrigby

**Comment by desaintmartin** [comment]
Up?

**Comment by mattfarina** [comment]
Sorry for the slow response.

You should have an invitation waiting for you to join as a collaborator.
