### ISSUE TITLE
[stable/nginx-ingress] Why is there a service for the metrics export

### ISSUE THREAD

**Issue by floriantraber** [helm/charts#8677]
**Which chart**: stable/nginx-ingress

Why does the nginx-ingress chart expose a metrics service instead of directly adding the prometheus scrape annotations to the Pod?

**Comment by vsliouniaev** [comment]
Please see the discussion about these annotations here: https://github.com/prometheus/prometheus/pull/4131

Not all Prometheus deployment scenarios use this approach to find the correct endpoints. For example, the prometheus-operator version does not use this approach.
