### ISSUE TITLE
linkerd chart has incorrect resource limits

### ISSUE THREAD

**Issue by naveensrinivasan** [helm/charts#870]
The linkerd chart has resource limits https://github.com/kubernetes/charts/blob/master/stable/linkerd/values.yaml#L61 that are not what is recommended 
https://github.com/linkerd/linkerd/blob/master/project/LinkerdBuild.scala#L188 

From the linkerd [team](https://linkerd.slack.com/archives/C0JV5E7BR/p1490118106034271?thread_ts=1490116656.492933&cid=C0JV5E7BR)  the recommendation is
>2cpu and 1gb of memory per process.

**Comment by seanknox** [comment]
Hi @naveensrinivasan, would appreciate a PR if you're able!

**Comment by naveensrinivasan** [comment]
@seanknox Will do that. Thanks
