### ISSUE TITLE
[stable/rocketchat] permission issues with mongo

### ISSUE THREAD

**Issue by ahmadalli** [helm/charts#8712]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Version of Helm and Kubernetes**: Kubernetes v1.11.2 (RKE)

**Which chart**: rocketchat

**What happened**: rocketchat pod failed to start because mongo required authentication

**What you expected to happen**: rocketchat starts working

**How to reproduce it** (as minimally and precisely as possible): install the chart on rancher custom cluster

**Anything else we need to know**:

**Comment by ineffyble** [comment]
Setting `mongodb.usePassword` value to `false` fixes the issue, as a workaround until the chart is fixed.

**Comment by cfstras** [comment]
Another workaround is to set all required credentials in values.yaml:
- mongodbRootPassword
- mongodbUsername
- mongodbPassword

**Comment by nikoul** [comment]
> Another workaround is to set all required credentials in values.yaml:
> 
> * mongodbRootPassword
> * mongodbUsername
> * mongodbPassword

This does not help for my issue.

**Comment by geekgonecrazy** [comment]
#9605 would fix this issue.  I've opened #11016 which adds readme and shows how to deploy with the setting of the values
