### ISSUE TITLE
[stable/prometheus-operator] Update to 0.25.0

### ISSUE THREAD

**Issue by vsliouniaev** [helm/charts#8722]
**Which chart**: stable/prometheus-operator
**What happened**: using release 0.24.0
**What you expected to happen**: using release 0.25.0

This release (https://github.com/coreos/prometheus-operator/releases/tag/v0.25.0) introduces two new features
* [FEATURE] Allow passing additional alert relabel configs in Prometheus custom resource ( coreos/prometheus-operator#2022)
* [FEATURE] Add ability to mount custom ConfigMaps into Alertmanager and Prometheus ( coreos/prometheus-operator#2028)

_I plan on addressing this, opening issue to track_

**Comment by paskal** [comment]
(It's actually https://github.com/coreos/prometheus-operator/pull/2022 and https://github.com/coreos/prometheus-operator/pull/2028.)

**Comment by vsliouniaev** [comment]
Thanks, updated!

**Comment by paskal** [comment]
Per offline talk, relabeling won't be touched there, it could be changed only in coreos/prometheus-operator. What should be done here is just upgrade to 0.25.0 with support of new features from helm code.
