### ISSUE TITLE
[stable/prometheus-operator] Possible to replace node-exporter recording rules with relabelling?

### ISSUE THREAD

**Issue by vsliouniaev** [helm/charts#8727]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature Request

**Which chart**: stable/prometheus-operator

**What happened**: 
The alerts and dashboards in this chart appear to be leveraging recording rules to provide compatibility with node exporter v0.16

**What you expected to happen**: 
Since prometheus operator 0.24+ provides _some_ capability for relabelling it may be possible to replace the recording rules with labels. Using recording rules for the purpose of relabelling is bad practice.

**Comment by paskal** [comment]
Should this issue be moved to coreos/prometheus-operator maybe? We could maybe change the dashboards but not the rules.

**Comment by vsliouniaev** [comment]
I think you're right on this one, the issue is more relevant there
