### ISSUE TITLE
[stable/prometheus-operator] Provide kube-dns dashboard

### ISSUE THREAD

**Issue by vsliouniaev** [helm/charts#8728]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature request

**Which chart**: stable/prometheus-operator

**What happened**: There chart provides a coreos dashboard

**What you expected to happen**: There should also be a kube-dns dashboard

**Comment by paskal** [comment]
I think, it could not be done there, only somewhere near [coreos/prometheus-operator](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml) and imported there later.

**Comment by paskal** [comment]
I think, it could not be done there, only somewhere near [coreos/prometheus-operator](https://github.com/coreos/prometheus-operator/tree/master/helm/grafana/dashboards) and imported there later.
