### ISSUE TITLE
LEGO_EMAIL value from the kube-lego chart is bogus and invalid

### ISSUE THREAD

**Issue by pgporada** [helm/charts#874]
Per discussion on https://github.com/jetstack/kube-lego/issues/131#issuecomment-290692369, the default value for the LEGO_EMAIL will not allow a user of the kube-lego chart to receive certificate expiry emails. If the LEGO_EMAIL default is removed from the chart, the first time a user tries to use the chart, they will receive an early fail indicating they need to set a valid email address.

The specific line of code I am talking about is https://github.com/kubernetes/charts/blob/master/stable/kube-lego/values.yaml#L7

**Comment by mgoodness** [comment]
Resolved by #912
