### ISSUE TITLE
Unable to open node port when install minio using helmchart

### ISSUE THREAD

**Issue by CMADHANKUMAR** [helm/charts#8742]
I installed minio using helm.

The below is the pod.

[root@kube-master-0-prodes-1539172764 centos]# kubectl get pods
NAME                                                      READY   STATUS    RESTARTS   AGE
edgy-termite-minio-5bcb4b9694-tnhcs                       1/1     Running   0          50m

The below is the service of the respective service.

[root@kube-master-0-prodes-1539172764 centos]# kubectl get services
NAME                                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                           AGE
edgy-termite-minio                     ClusterIP      10.233.42.193   <none>        9000/TCP                                          51m

The service is actually not opening external port.So i am unable to access the minio from outside the kubernetes cluster .

How can i open the external port of minio so that i can accessing it outside .

**Comment by Towmeykaw** [comment]
You can open it by changing the service type from ClusterIP to NodePort.
``` helm install stable/minio --set service.type=NodePort ```

**Comment by CMADHANKUMAR** [comment]
> helm install stable/minio --set service.type=NodePort

It is working ,thankyou !
