### ISSUE TITLE
Grafana dashboard show no datapoints 

### ISSUE THREAD

**Issue by dolftax** [helm/charts#8744]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Possibly a bug report or maybe I am doing something wrong.

Prometheus configuration: http://dpaste.com/21FXP26.txt
Grafana configuration: http://dpaste.com/3AF9F3E.txt

**Version of Helm and Kubernetes**:

Helm
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Kubernetes
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.6", GitCommit:"06898a4d0f2b96f82b43d9e59fa2825bd3d616a2", GitTreeState:"clean", BuildDate:"2018-10-02T17:32:01Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
Prometheus and Grafana

**What happened**:
Most graphs returns 'no data points'. Example: https://grafana.com/dashboards/162

**What you expected to happen**:
All datapoints should be available. GCP's one click deploy works as expected on these dashboards.

**How to reproduce it** (as minimally and precisely as possible):
Try applying the above values.

**Anything else we need to know**:
I suspect something wrong with service account configuration.

A sample failing query: `sum(rate(node_cpu{mode="idle"}[2m])) * 100`

Screenshots:

<img width="1235" alt="screenshot 2018-10-25 at 17 16 10" src="https://user-images.githubusercontent.com/4883668/47498136-f4880f00-d879-11e8-84ff-0a2b251f4039.png">
<img width="1240" alt="screenshot 2018-10-25 at 17 17 46" src="https://user-images.githubusercontent.com/4883668/47498139-f4880f00-d879-11e8-83d7-731111028c41.png">

**Comment by jaipradeesh** [comment]
Found the cause: Its because of the `_bytes` suffix. Wondering when and why did this change happen.

Working query: `sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)`
Failing query: `sum(rate(node_cpu{mode="idle"}[2m])) * 100`
