### ISSUE TITLE
[stable/keycloak] Not working behind HTTPS reverse proxy

### ISSUE THREAD

**Issue by zanettea** [helm/charts#8751]
In version 4.5 of keycloak docker image the configuration is forced via command line. In particular, if no -c command is given, the configuration standalone-ha.xml is used.

Apparently this overrides the jboss cli settings, for instance reverse proxy settings.

Feature worked with 4.1 keycloak image

**Comment by zanettea** [comment]
Duplicate of #8777

**Comment by ariep** [comment]
Perhaps useful to know for others is that this problem can appear as a failure when attempting to access the Keycloak admin console, with an error mentioning an invalid redirect_uri.
