### ISSUE TITLE
[stable/anchore-engine] Add user to github org that is in our OWNERs as approver

### ISSUE THREAD

**Issue by zhill** [helm/charts#8762]
**Is this a request for help?**: Yes

Per the contribution guidelines in the readme, we have an OWNERs file in the stable/anchore-engine chart. I'm an approver and have approved a PR to add another member to that list as a maintainer of our chart. The last step required is to add that user @Btodhunter  to the github helm org to be able to approve PRs. I spoke with @viglesiasce and he indicated an issue here is the best way to approach this. I'm happy to do anything else needed to facilitate the process, thanks!

**Comment by mattfarina** [comment]
I've added @Btodhunter as a collaborator. An invitation was sent that will need to be accepted. If you need anything else please let us know.

**Comment by zhill** [comment]
many thanks @mattfarina
