### ISSUE TITLE
stable/rabbitmq install error Forbidden: may not be used when type is 'ClusterIP'

### ISSUE THREAD

**Issue by javajon** [helm/charts#8763]
**Is this a request for help?**: Yes
**BUG REPORT**

**Version of Helm and Kubernetes**:
Kubernetes 1.10

**Which chart**:
stable/rabbitmq

**What happened**:

Get this error message: 

> Error: release my-rabbit failed: Service "my-rabbit-rabbitmq-headless" is invalid: spec.ports[1].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'

**What you expected to happen**:

The chart used to install, but some recent changes to stable/rabbitmq has broken this.

**How to reproduce it** (as minimally and precisely as possible):

Run example here: https://www.katacoda.com/javajon/courses/kubernetes-applications/rabbitmq

or 

helm install stable/rabbitmq \
--name my-rabbit \
--namespace rabbit \
--set replicas=3 \
--set serviceType=NodePort \
--set rabbitmq.managerPort=31111 \
--set rabbitmq.nodePort=31112 \
--set rabbitmq.username=admin \
--set rabbitmq.password=admin \
--set rbacEnabled=false

**Anything else we need to know**:

Consider the problem is [svc-headless.yaml](https://github.com/helm/charts/blob/master/stable/rabbitmq/templates/svc-headless.yaml) allows the application of nodePort to 

  - name: amqp
    port: {{ .Values.rabbitmq.amqpPort }}
    targetPort: amqp
    {{- if (and (eq .Values.serviceType "NodePort") (not (empty .Values.rabbitmq.nodePort))) }}
    nodePort: {{ .Values.rabbitmq.nodePort }}
    {{- end }}

yet type at top of yaml is fixed to "clusterIP: None"

**Comment by dene14** [comment]
Blame it on me. I haven't considered this option initially.

**Comment by javajon** [comment]
Seems isolated to just Minikube version running in Katacoda:

With minikube version: v0.28.2 at the Katacoda link above the error does not appear with chart version 3.3.1, but does with 3.3.2+

`helm install stable/rabbitmq --name my-rabbit --namespace rabbit --set replicas=3 --set serviceType=NodePort --set rabbitmq.managerPort=31111 --set rabbitmq.nodePort=31112 --set rabbitmq.username=admin --set rabbitmq.password=admin --set rbacEnabled=false --version 3.3.1`

The installation works just fine with Minikube 0.30.0 with VirtualBox locally on a Windows 10 laptop.

**Comment by javajon** [comment]
@dene14 - Perhaps I'm misusing the combination of options.

**Comment by javajon** [comment]
@dene14 

This error has gone away with chart version: 3.6.1 but I cannot get to the RabbitMQ Portal.  Should be on nodePort 31112?
