### ISSUE TITLE
Trusted Collaborator of the Datadog Chart

### ISSUE THREAD

**Issue by CharlyF** [helm/charts#8787]
Hello all,

I would like to be added as a trusted collaborator of the Datadog chart.
Per the documentation: https://github.com/helm/charts#trusted-collaborator, I'm opening an issue here.

Let me know if you would like me to share more on my background and knowledge of this chart and the overall Datadog product.

Cheers,

**Comment by hkaj** [comment]
👍 Charly works on the Datadog Helm chart with us and it would be very helpful if he was authorized to participate in the PR lifecycle.

**Comment by hkaj** [comment]
pinging @timstoop as you reviewed #2980 🙏

**Comment by irabinovitch** [comment]
@mattfarina I think you helped us with this in December 2017, although the processes was different then (helm was still in the k8s org).  Anything we need to do here to get CharlyF added? Thanks!

**Comment by irabinovitch** [comment]
Hi @mattfarina Happy new year. Could you help CharlyF get added?
