### ISSUE TITLE
[stable/prometheus-operator] Error: validation failed

### ISSUE THREAD

**Issue by t-v** [helm/charts#8789]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**: 
```
$  kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
$  helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Which chart**: stable/prometheus-operator

**What happened**:
```
Error: validation failed: [unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1", unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1", unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"]
```

**What you expected to happen**: Something like, helm succesfully installed prometheus-operator

**How to reproduce it** (as minimally and precisely as possible): Nothing special actually, just install the default template:
`helm install --name prometheus stable/prometheus-operator`

**Comment by vsliouniaev** [comment]
Hi @t-v! Do you know if this API is supported by kubernetes version 1.9.x?

The chart has a requirement for Kubernetes 1.10 listed in its readme, it's possible it would work on earlier versions but I don't have one handy to test.

**Comment by t-v** [comment]
thank you @paskal that seems to have fixed it.

**Comment by angegar** [comment]
I updated helm to 2.12.2 and replaced policy/v1beta1 with extensions/v1beta1 everywhere in the code. And ..... IT WORKS !!!

Thank you
