### ISSUE TITLE
[stable/rethinkdb] Proxy doesn't reconnect to cluster after terminating cluster pod

### ISSUE THREAD

**Issue by Pupix** [helm/charts#8790]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
- Helm: 2.11.0
- Kubernetes: 1.10.6-gke.6

**Which chart**:
stable/rethinkdb

**What happened**:
For some reason the cluster pod got rescheduled and the proxy disconnected from said pod. So far so good, however after the new pod went back up the proxy didn't try to reconnect. It's just sitting idle without allowing any access to the cluster anymore.

**What you expected to happen**:
The proxy should start trying to reconnect to the cluster and succeed if the cluster pod is back up.

**How to reproduce it** (as minimally and precisely as possible):
1. Install the chart with 1 replica
2. Kill the cluster pod
3. Wait for new pod to spawn
4. Watch the proxy disconnect and do nothing 

**Anything else we need to know**:
The author (@meenie) of this chart says that he's continuing the work of another user, whom I informed about this very same problem a while ago but never bothered to answer. https://github.com/rosskukulinski/rethinkdb-kubernetes/issues/2

The problem is that the startup script when resolving these lines
https://github.com/helm/charts/blob/7de016bd664f76a538afb3cf6951e47de7d27bd9/stable/rethinkdb/init/files/run.sh#L37-L45 gets the pod's IP as a result, thus if the pod gets rescheduled it loses that IP, so whatever proxy was connected to it can't reconnect anymore. 

Cheers,
Pupix

**Comment by meenie** [comment]
Hey Pupix,

There's very interesting! To be honest, I never tried running with just one pod in the Cluster.  So the query needs to also look for endpoints in the proxy service as well and combine them.  Is that something you want to try and implement?

Cheers,
cody

**Comment by Pupix** [comment]
Even if you run with more pods, wouldn't the problem present itself if all of them get rescheduled since the IPs are hardcoded when launching the proxy?

Wouldn't know where to start on fixing it really. My best guess would be to give an IP to the cluster-service and use that when joining. Either grab the IP via the API or just let the DNS take care of the IP.

Something like this is what I was thinking:
```js
--join rethinkdb-cluster-service:29015
```

Do Services get rescheduled in K8s? If so, then we are back to square one.

**Comment by meenie** [comment]
> Even if you run with more pods, wouldn't the problem present itself if all of them get rescheduled since the IPs are hardcoded when launching the proxy?

No, because each one is rescheduled one by one from highest to lowest. Since there is at least one other cluster pod present, it will rejoin.  

The way to fix this is to just also search the proxy service when looking for IPs to join.  The proxy pod is not allowed to start up on its own, so it has to only search for cluster IPs, but if it's already started up because there was a cluster pod present (as is your case), the cluster pod needs to search for other cluster pods and proxy pods to rejoin the proxy.

**Comment by Pupix** [comment]
I did some tests with 3 replicas and killing the pods 1 by 1 does exactly what you said, they reconnect to each other. Killing all the pods at once however causes the problem to reemerge.
![image](https://user-images.githubusercontent.com/4929965/47919023-9b8a2d80-deae-11e8-877e-33ab25a39862.png)
and this happens when trying to add a new table
![image](https://user-images.githubusercontent.com/4929965/47919068-b5c40b80-deae-11e8-8c63-97a768c9b2b6.png)
