### ISSUE TITLE
[stable/grafana] Provide automatic redeployment option on configuration change

### ISSUE THREAD

**Issue by vsliouniaev** [helm/charts#8798]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature Request

**Which chart**: stable/grafana

**What happened**: When changing the password or altering some configuration of the .ini section in the values file the grafana pod stays up and new values are not loaded. It is necessary to delete the pod before changes are applied.

**What you expected to happen**: An option to be available in values that will cause the pod to be updated and new values to be loaded. This could be done by doing a hash of the configuration used in the various configuration options.

**How to reproduce it** (as minimally and precisely as possible):
1. Deploy the chart with default values
2. Do a chart upgrade without changing the values - the password in the secret will be re-created but the grafana pod will not be updated.

**Anything else we need to know**:
* I am happy to work on a PR for this feature if it is desirable. 
* I would like to know if there's a list of configurations that should be subject to this so I'm not missing anything I'm not currently aware of.

Relates to : https://github.com/helm/charts/issues/7891

**Comment by paskal** [comment]
Please, reopen.
@davidkarlsen @sameersbn could you please answer? It seems like @vsliouniaev is ready to fix that problem, only thing necessary is information from you what you acknowledge that issue and will approve fix PR.
