### ISSUE TITLE
[stable/keel] Missing AWS ECR polling support 

### ISSUE THREAD

**Issue by emmekappa** [helm/charts#8807]
According to [Keel official documentation](https://keel.sh/v1/guide/documentation#Polling-with-AWS-ECR) in order to configure polling for [AWS ECR](https://aws.amazon.com/ecr/) you need to provide the following env variable in the Deployment configuration:

* `AWS_ACCESS_KEY_ID`
* `AWS_SECRET_ACCESS_KEY`
* `AWS_REGION`

Right now it's not possible to specify those variables through values.

**Comment by allenwei** [comment]
+1

**Comment by allenwei** [comment]
just found latest keel charts in keel repo, but it is not updated here https://github.com/keel-hq/keel/blob/master/chart/keel/README.md
