### ISSUE TITLE
[stable/mongodb] Statefulsets doesn't inherit affinity from values

### ISSUE THREAD

**Issue by ath88** [helm/charts#8821]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
```
> helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
Kubernetes v1.11.4

**Which chart**:
stable/mongodb

**What happened**:
I installed the chart with affinities, and the pods were scheduled on unexpected nodes.

**What you expected to happen**:
I expected the pods to inherit the affinities, but they didn't.

**How to reproduce it** (as minimally and precisely as possible):
Install the chart with any affinity, it wont be there.

**Anything else we need to know**:
The statefulset templates just doesn't include the affinify-field, even though it is advertised in the README.md.

**Comment by tompizmor** [comment]
I just created [this PR](https://github.com/helm/charts/pull/9960) to fix this issue. Thanks for reporting it!
