### ISSUE TITLE
[stable/prometheus] Feature for supplying Alertmanager multiple ConfigMap volumeMounts

### ISSUE THREAD

**Issue by maguro** [helm/charts#8823]
**Which chart**: `stable/prometheus`

It would be nice if the template for Alertmanager had `extraConfigmapMounts`; we supply our templates via config maps.  Looking at the template for the Prometheus server, it may be a good idea to add the following to the Alertmanager template:

- `extraHostPathMounts`
- `extraConfigmapMounts`
- `extraSecretMounts`

**Comment by 1robroos** [comment]
I have the same issue: I want alertmanager to mount a configmap which holds a alertmanager-template.
Unfortunately there were no reactons on maguro.
