### ISSUE TITLE
[stable/fluentd-elasticsearch] - Failed to flush the buffer. Transport::Errors. AWS ES.

### ISSUE THREAD

**Issue by fog1985** [helm/charts#8826]
Using this helm chart via Terraform in order to set up fluentd logging in our k8s cluster. 

TF configuration:
`resource "helm_release" "fluentd_elasticsearch" {
  depends_on = ["module.es_domain"]

  chart     = "stable/fluentd-elasticsearch"
  name      = "fluentd"
  namespace = "logging"

  set {
    name  = "elasticsearch.host"
    value = "${module.es_domain.endpoint}"
  }

  set {
    name  = "elasticsearch.port"
    value = "443"
  }
}`

Fluentd pod's logs:

> 2018-10-28 21:09:51 +0000 [warn]: [elasticsearch] failed to flush the buffer. retry_time=41 next_retry_seconds=2018-10-28 21:10:23 +0000 chunk="579503a784093dfe42b41140eee005ed" error_class=Elasticsearch::Transport::Transport::Errors::BadRequest error="[400] "

When I try to log into POD's container and check ES connectivity etc, everything works. 
I do can push logs into AWS ES using `curl` and connectivity is just fine. 
But `fluentd` container's logs show only that record.

**helm version:**

> Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

**kubectl version:**

> Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:18:13Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by innovia** [comment]
default image will not work with AWS ES as it does not signthe request as v4 signature you will need to build your own image


```
FROM gcr.io/google-containers/fluentd-elasticsearch:v2.3.1

# Disable prompts from apt.
ENV DEBIAN_FRONTEND noninteractive

# Ensure there are enough file descriptors for running Fluentd.
RUN ulimit -n 65536

RUN apt-get update && apt-get install -y -q --no-install-recommends \
  curl ca-certificates make g++ bash ruby-dev libjemalloc-dev

# Install Fluentd.
# RUN /usr/bin/curl -sSL https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent2.sh | sh

# Change the default user and group to root.
# Needed to allow access to /var/log/docker/... files.
#RUN sed -i -e "s/USER=td-agent/USER=root/" -e "s/GROUP=td-agent/GROUP=root/" /etc/init.d/td-agent

# Install the Elasticsearch Fluentd plug-in.
# http://docs.fluentd.org/articles/plugin-management
RUN fluent-gem install --no-document fluent-plugin-kubernetes_metadata_filter -v 2.1.4
RUN fluent-gem install --no-document fluent-plugin-aws-elasticsearch-service -v 1.1.0

# Remove docs and postgres references
RUN rm -rf /opt/td-agent/embedded/share/doc \
  /opt/td-agent/embedded/share/gtk-doc \
  /opt/td-agent/embedded/lib/postgresql \
  /opt/td-agent/embedded/bin/postgres \
  /opt/td-agent/embedded/share/postgresql

RUN apt-get remove -y make g++
RUN apt-get autoremove -y
RUN apt-get clean -y

RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
ENV LD_PRELOAD /usr/lib/x86_64-linux-gnu/libjemalloc.so
```
