### ISSUE TITLE
[stable/prometheus-operator] add grafana auth.anonymous option

### ISSUE THREAD

**Issue by paskal** [helm/charts#8840]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST
**Which chart**:
stable/prometheus-operator

**Description**:
coreos version of prometheus-operator had [anonymous auth](https://github.com/coreos/prometheus-operator/blob/4510314/helm/grafana/values.yaml) Grafana option which was lost after migration.
Could someone please point me on how to work around that (when I'm not deploying Grafana by itself but trough prometheus-operator) or tell if it's OK to request adding this option in prometheus-operator code?
I thought I could pass configmap to Grafana trough prometheus-operator option, but didn't find how to achieve that. If there is no way of altering Grafana installation besides turning it off in prometheus-operator and deploying it separately, I think that it should be added.

**Comment by paskal** [comment]
Sadly these values aren't passed to Grafana:
```bash
>  kubectl exec -it prometheus-operator-grafana-79496ff6b7-x8w7r -c grafana -- sh
$ cat /etc/grafana/grafana.ini
[analytics]
check_for_updates = true
[grafana_net]
url = https://grafana.net
[log]
mode = console
[paths]
data = /var/lib/grafana/data
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
```

**Comment by paskal** [comment]
My values were not reloaded without `--recreate-pods` helm option. Works good, thank you!

**Comment by vsliouniaev** [comment]
This is quite annoying for me as well. I would like to add optional automatic annotations to the grafana pods so that the reload would happen automatically.

https://github.com/helm/charts/issues/8798
