### ISSUE TITLE
[stable/nginx-ingress] How to add correct config to ConfigMap

### ISSUE THREAD

**Issue by zhiweiv** [helm/charts#8845]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Maybe a BUG

**Version of Helm and Kubernetes**:
v2.11.0
1.12.1

**Which chart**:
stable/nginx-ingress

**What happened**:
When I use below command,
helm install --set controller.config.enable-underscores-in-headers=true stable/nginx-ingress --dry-run --debug > ingress.yaml
helm install --set controller.config.enable-underscores-in-headers="true" stable/nginx-ingress --dry-run --debug > ingress.yaml

I get the below ConfigMap
kind: ConfigMap
data:
  enable-vts-status: "false"
  enable-underscores-in-headers: true

When I use below command,
helm install --set controller.config.enable-underscores-in-headers=\ "true\ " stable/nginx-ingress --dry-run --debug > ingress.yaml
helm install --set controller.config.enable-underscores-in-headers="\ "true\ "" stable/nginx-ingress --dry-run --debug > ingress.yaml
(I added a space after \ for showing in this post, the space is not there in actual command)

I get the below ConfigMap
kind: ConfigMap 
data:
  enable-vts-status: "false"
  enable-underscores-in-headers: '"true"'

**What you expected to happen**:
I want to get enable-underscores-in-headers: **"true"** in ConfigMap

How can I set the command to get exptected config?

Thanks

**Comment by zhiweiv** [comment]
I found another way to achieve my goal, 
helm install stable/nginx-ingress -f values.yaml

Content in values.yaml
```
controller:
  config:
    enable-underscores-in-headers: "true"
```

**Comment by adnan-kamili** [comment]
Following worked for me:

> helm install stable/nginx-ingress --name nginx-ingress --set controller.publishService.enabled=true,controller.config.use-forwarded-headers='"true"'

**Comment by TiloGit** [comment]
see https://github.com/helm/helm/issues/2848

`	--set-string controller.config.enable-underscores-in-headers="true"`
