### ISSUE TITLE
stable/prometheus-operator rbac.authorization.k8s.io grafana-clusterrole is forbidden

### ISSUE THREAD

**Issue by rewt** [helm/charts#8869]
**Is this a request for help?**:
YES!  Please help identify setting prohibiting install. 
---

**Version of Helm and Kubernetes**:
`Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}`

**Which chart**:
stable/prometheus-operator

**What happened**:
`helm upgrade --install prometheus-operator stable/prometheus-operator -f values.yaml --namespace=monitoring --debug
[debug] Created tunnel using local port: '63930'

[debug] SERVER: "127.0.0.1:63930"

[debug] Fetched stable/prometheus-operator to /Users/kg/.helm/cache/archive/prometheus-operator-0.1.8.tgz

Release "prometheus-operator" does not exist. Installing it now.
[debug] CHART PATH: /Users/kg/.helm/cache/archive/prometheus-operator-0.1.8.tgz

Error: release prometheus-operator failed: clusterroles.rbac.authorization.k8s.io "prometheus-operator-grafana-clusterrole" is forbidden: attempt to grant extra privileges: [{[get] [] [configmaps] [] []} {[watch] [] [configmaps] [] []} {[list] [] [configmaps] [] []}] user=&{system:serviceaccount:kube-system:default 09634074-6f3d-11e8-8da6-b21078a91fea [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]`

**What you expected to happen**:
Successful install

**How to reproduce it** (as minimally and precisely as possible):

I've disabled anything related to rbac and service accounts, and yet still get error.

Here is my [values.yaml](https://pastebin.com/aWfgmbxU)

**Comment by vsliouniaev** [comment]
Hey @rewt, if you need to disable the grafana sub-chart RBAC you need to set the values specifically for that chart: https://github.com/helm/charts/blob/master/stable/grafana/values.yaml

Helm allows you to do this by referring to them by using the sub chart name, for example `grafana.rbac.create=false`

**Comment by rewt** [comment]
This is what I suspected, but hadn’t tried.

Can someone point out in code where prometheus-chart is linked to grafana?

I couldn’t find any reference....

**Comment by rewt** [comment]
> Helm allows you to do this by referring to them by using the sub chart name, for example `grafana.rbac.create=false`

Is this passed as parameter?  Is there a way to get helm to pickup values.yaml for grafana install?

**Comment by vsliouniaev** [comment]
The features you're looking for are all available in the grafana sub-chart, but you must access them using `grafana.*`. The documentation on how to do this is available here: https://docs.helm.sh/chart_template_guide/#subcharts-and-global-values

**Comment by rewt** [comment]
ahh thank you - added in values.yaml and worked well.
