### ISSUE TITLE
Kafka incubator 

### ISSUE THREAD

**Issue by nightguide** [helm/charts#8876]
Hello, 

I need help. I can't connecting and sending to external kafka, and i not understand this bug my k8s instance or this is Bug helm chart incubator/kafka

---

BUG REPORT 

**Version of Helm and Kubernetes**:

helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

Chart name:

**incubator/kafka**

I Deployed kafka chart this values in my k8s cluster:

_helm install --name kafka --namespace kafka-test incubator/kafka --set external.enabled=true  --set external.firstListenerPort=32090 --set persistence.enabled=true --set persistence.size=2Gi --set rbac.enabled=true --set external.domain=mydomain.local_

**What you expected to happen**:

**I see install message:**

### Connecting to Kafka from outside Kubernetes

You have enabled the external access feature of this chart.

**WARNING:** By default this feature allows Kafka clients outside Kubernetes to
connect to Kafka via NodePort(s) in `PLAINTEXT`.

Please see this chart's README.md for more details and guidance.

If you wish to connect to Kafka from outside please configure your external Kafka
clients to point at the following brokers. Please allow a few minutes for all
associated resources to become healthy.

  kafka.mydomain.local:32090
  kafka.mydomain.local:32091
  kafka.mydomain.local:32092

I add in my DNS server records type A with ip : 192.168.80.11 192.168.80.12 192.168.80.13

It's ip my nodes in cluster k8s.

![image](https://user-images.githubusercontent.com/37993560/47703172-f8d57300-dc51-11e8-879d-1ed2aaada5ad.png)

nslookup 

 nslookup kafka.mydomain.local
Server:         192.168.80.21
Address:        192.168.80.21#53

Name:   kafka.mydomain.local
Address: 192.168.80.12
Name:   kafka.mydomain.local
Address: 192.168.80.13
Name:   kafka.mydomain.local
Address: 192.168.80.11

Ping external DNS records from containers with kafka

# kubectl exec -ti -n=kafka-test kafka-0 -- bash
root@kafka-0:/# ping kafka.mydomain.local
PING kafka.mydomain.local (192.168.80.13) 56(84) bytes of data.
64 bytes from 192.168.80.13: icmp_seq=1 ttl=64 time=0.033 ms
64 bytes from 192.168.80.13: icmp_seq=2 ttl=64 time=0.078 ms

root@kafka-0:/# ping kafka.mydomain.local
PING kafka.mydomain.local (192.168.80.13) 56(84) bytes of data.
64 bytes from 192.168.80.13: icmp_seq=1 ttl=64 time=0.033 ms
64 bytes from 192.168.80.13: icmp_seq=2 ttl=64 time=0.045 ms

root@kafka-0:/# ping kafka.mydomain.local
PING kafka.mydomain.local (192.168.80.11) 56(84) bytes of data.
64 bytes from 192.168.80.11: icmp_seq=1 ttl=63 time=0.136 ms
64 bytes from 192.168.80.11: icmp_seq=2 ttl=63 time=0.245 ms

I can't connecting and sending messages to kafka topic from external clients. Internal connectivity works fine.

From my workstation test connection and send in topic test1 - Echo 123

_[root@kub-ansible bin]# echo 123 | ./kafka-console-producer --broker-list kafka.mydomain.local:32090,kafka.mydomain.local:32091,kafka.mydomain.local:32092  --topic test1
[2018-10-30 15:07:24,489] ERROR Error when sending message to topic test1 with key: null, value: 3 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms._

Configs:

> root@kafka-0:/# cat /etc/kafka/kafka.properties
> zookeeper.port.2181.tcp.addr=10.233.25.185
> 0.external.port.19092.tcp.addr=10.233.8.104
> 2.external.service.port=19092
> 2.external.port.19092.tcp.port=19092
> zookeeper.port.2181.tcp.proto=tcp
> zookeeper.port.2181.tcp.port=2181
> port.9092.tcp.proto=tcp
> 1.external.port.19092.tcp=tcp://10.233.39.191:19092
> 0.external.port.19092.tcp=tcp://10.233.8.104:19092
> zookeeper.service.port.client=2181
> 1.external.service.port.external.broker=19092
> service.port=9092
> 0.external.service.port.external.broker=19092
> 2.external.port.19092.tcp=tcp://10.233.16.28:19092
> advertised.listeners=PLAINTEXT://10.233.70.128:9092
> zookeeper.connect=kafka-zookeeper:2181
> 1.external.port.19092.tcp.proto=tcp
> 2.external.service.port.external.broker=19092
> port.9092.tcp=tcp://10.233.24.116:9092
> zookeeper.port.2181.tcp=tcp://10.233.25.185:2181
> 2.external.service.host=10.233.16.28
> jmx.port=5555
> port.9092.tcp.addr=10.233.24.116
> zookeeper.service.port=2181
> zookeeper.port=tcp://10.233.25.185:2181
> service.port.broker=9092
> port.9092.tcp.port=9092
> heap.opts=-Xmx1G -Xms1G
> zookeeper.service.host=10.233.25.185
> 1.external.service.port=19092
> 0.external.port.19092.tcp.port=19092
> confluent.support.metrics.enable=false
> 1.external.port.19092.tcp.addr=10.233.39.191
> 0.external.service.host=10.233.8.104
> broker.id=0
> offsets.topic.replication.factor=3
> service.host=10.233.24.116
> 2.external.port=tcp://10.233.16.28:19092
> 2.external.port.19092.tcp.proto=tcp
> log.dirs=/opt/kafka/data/logs
> listeners=PLAINTEXT://0.0.0.0:9092
> 1.external.port=tcp://10.233.39.191:19092
> 0.external.port=tcp://10.233.8.104:19092
> 1.external.service.host=10.233.39.191
> 0.external.port.19092.tcp.proto=tcp
> 2.external.port.19092.tcp.addr=10.233.16.28
> 0.external.service.port=19092
> 1.external.port.19092.tcp.port=19092
> 
> 
> [root@kub-master ~]# kubectl describe svc -n=kafka-test
> Name:              kafka
> Namespace:         kafka-test
> Labels:            app=kafka
>                    chart=kafka-0.12.0
>                    heritage=Tiller
>                    release=kafka
> Annotations:       <none>
> Selector:          app=kafka,release=kafka
> Type:              ClusterIP
> IP:                10.233.24.116
> Port:              broker  9092/TCP
> TargetPort:        kafka/TCP
> Endpoints:         10.233.64.163:9092,10.233.68.129:9092,10.233.70.128:9092
> Session Affinity:  None
> Events:            <none>
> 
> 
> Name:                     kafka-0-external
> Namespace:                kafka-test
> Labels:                   app=kafka
>                           chart=kafka-0.12.0
>                           heritage=Tiller
>                           pod=kafka-0
>                           release=kafka
> Annotations:              external-dns.alpha.kubernetes.io/hostname: kafka.mydomain.local
> Selector:                 app=kafka,pod=kafka-0,release=kafka
> Type:                     NodePort
> IP:                       10.233.8.104
> Port:                     external-broker  19092/TCP
> TargetPort:               19092/TCP
> NodePort:                 external-broker  32090/TCP
> Endpoints:                10.233.70.128:19092
> Session Affinity:         None
> External Traffic Policy:  Cluster
> Events:                   <none>
> 
> 
> Name:                     kafka-1-external
> Namespace:                kafka-test
> Labels:                   app=kafka
>                           chart=kafka-0.12.0
>                           heritage=Tiller
>                           pod=kafka-1
>                           release=kafka
> Annotations:              external-dns.alpha.kubernetes.io/hostname: kafka.mydomain.local
> Selector:                 app=kafka,pod=kafka-1,release=kafka
> Type:                     NodePort
> IP:                       10.233.39.191
> Port:                     external-broker  19092/TCP
> TargetPort:               19092/TCP
> NodePort:                 external-broker  32091/TCP
> Endpoints:                10.233.64.163:19092
> Session Affinity:         None
> External Traffic Policy:  Cluster
> Events:                   <none>
> 
> 
> Name:                     kafka-2-external
> Namespace:                kafka-test
> Labels:                   app=kafka
>                           chart=kafka-0.12.0
>                           heritage=Tiller
>                           pod=kafka-2
>                           release=kafka
> Annotations:              external-dns.alpha.kubernetes.io/hostname: kafka.mydomain.local
> Selector:                 app=kafka,pod=kafka-2,release=kafka
> Type:                     NodePort
> IP:                       10.233.16.28
> Port:                     external-broker  19092/TCP
> TargetPort:               19092/TCP
> NodePort:                 external-broker  32092/TCP
> Endpoints:                10.233.68.129:19092
> Session Affinity:         None
> External Traffic Policy:  Cluster
> Events:                   <none>
> 
> 
> Name:              kafka-headless
> Namespace:         kafka-test
> Labels:            app=kafka
>                    chart=kafka-0.12.0
>                    heritage=Tiller
>                    release=kafka
> Annotations:       service.alpha.kubernetes.io/tolerate-unready-endpoints: true
> Selector:          app=kafka,release=kafka
> Type:              ClusterIP
> IP:                None
> Port:              broker  9092/TCP
> TargetPort:        9092/TCP
> Endpoints:         10.233.64.163:9092,10.233.68.129:9092,10.233.70.128:9092
> Session Affinity:  None
> Events:            <none>
> 
> 
> Name:              kafka-zookeeper
> Namespace:         kafka-test
> Labels:            app=zookeeper
>                    chart=zookeeper-1.0.2
>                    heritage=Tiller
>                    release=kafka
> Annotations:       <none>
> Selector:          app=zookeeper,release=kafka
> Type:              ClusterIP
> IP:                10.233.25.185
> Port:              client  2181/TCP
> TargetPort:        client/TCP
> Endpoints:         10.233.64.162:2181,10.233.68.128:2181,10.233.70.129:2181
> Session Affinity:  None
> Events:            <none>
> 
> 
> Name:              kafka-zookeeper-headless
> Namespace:         kafka-test
> Labels:            app=zookeeper
>                    chart=zookeeper-1.0.2
>                    heritage=Tiller
>                    release=kafka
> Annotations:       <none>
> Selector:          app=zookeeper,release=kafka
> Type:              ClusterIP
> IP:                None
> Port:              client  2181/TCP
> TargetPort:        2181/TCP
> Endpoints:         10.233.64.162:2181,10.233.68.128:2181,10.233.70.129:2181
> Port:              election  3888/TCP
> TargetPort:        3888/TCP
> Endpoints:         10.233.64.162:3888,10.233.68.128:3888,10.233.70.129:3888
> Port:              server  2888/TCP
> TargetPort:        2888/TCP
> Endpoints:         10.233.64.162:2888,10.233.68.128:2888,10.233.70.129:2888
> Session Affinity:  None
> Events:            <none>

I testing telnet connectivity on port 32090,32091,32092 to kafka.mydomain.local , but get response 

Connection refused.

 
![image](https://user-images.githubusercontent.com/37993560/47704687-0d683a00-dc57-11e8-8412-da37f7ee7538.png)

Firewall on nodes k8d disabled. I can't understand why not working . external connectity

Plz Help

**Comment by cablespaghetti** [comment]
I've just got this working. The step missing in the documentation is to update the "listeners" configuration property. Here's my config:
```
configurationOverrides:
  "offsets.topic.replication.factor": 3
  "auto.leader.rebalance.enable": true
  "auto.create.topics.enable": true
  "confluent.support.metrics.enable": false
  "advertised.listeners": |-
    EXTERNAL://{{ .Environment.Name }}-kafka.internal.mydomain.com:$((31090 + ${KAFKA_BROKER_ID}))
  "listener.security.protocol.map": |-
    PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
  "listeners": "PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092"
external:
  enabled: true
  domain: internal.mydomain.com
```

Duplicate of #9062
