### ISSUE TITLE
prometheus-operator RBAC does not work

### ISSUE THREAD

**Issue by AkulovNV** [helm/charts#8877]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

Helm version
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
stable/prometheus-operator

**What happened**:

After setup helm chart node exporters does not work, daemoset didn't start because RBAC give an error:

>  daemonset-controller  Error creating: pods "kube-prometheus-prometheus-node-exporter-" is forbidden: unable to validate against any pod security policy: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 9100: Host port 9100 is not allowed to be used. Allowed ports: []]

**What you expected to happen**:

`helm upgrade -i kube-prometheus stable/prometheus-operator --namespace monitoring`

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by paskal** [comment]
Please include kubernetes version as well.

**Comment by AkulovNV** [comment]
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by AkulovNV** [comment]
What about this issue? Can anyone help me?

**Comment by paskal** [comment]
Could you please do `helm install stable/prometheus-operator --debug --namespace monitoring-8877` (with previously non-existent namespace), post the results to pastebin and post the link here?
I need to know how it behaves as clean install for you. If you used coreos prometheus-operator previously, it might affect new installation (however it did not in my case).
