### ISSUE TITLE
[stable/k8s-spot-rescheduler] Add pod disruption budget

### ISSUE THREAD

**Issue by QuingKhaos** [helm/charts#8895]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Which chart**:
stable/k8s-spot-rescheduler

**What happened**:
If I deploy one or more than one replica for k8s-spot-rescheduler the cluster-autoscaler is not able to evict it without pdb.

**What you expected to happen**:
Having the option to define a pdb with max unavailability set to 1 the cluster-autoscaler and any other parts of the system which need to evict pods/taint nodes is able to gracefully do this on the k8s-spot-rescheduler pods.

**How to reproduce it** (as minimally and precisely as possible):
* Have a autoscaling cluster (w/ stable/cluster-autoscaler) with e.g. two nodes
* Deploy stable/k8s-spot-rescheduler with replicas set to 2
* The cluster autoscaler is not able to evict one of the pods because of it's own restrictions when a pdb is missing

**Anything else we need to know**:

Normally you would run the k8s-spot-rescheduler on master nodes, which is not possible on AWS EKS. Thus the need to have a pdb.

**Comment by EmiiKhaos** [comment]
@komljen What do you think about it?

I first thought about defining the pdb by default with `maxUnavailability: 1`. But when this chart runs usually on master nodes, IMHO it should be not be created by default.
