### ISSUE TITLE
[stable/rabbitmq] `rabbitmq.diskFreeLimit` ignored

### ISSUE THREAD

**Issue by thomas-riccardi** [helm/charts#8901]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.9", GitCommit:"e6ab4ee54f71e7a403cc733534bab86fd959ecb7", GitTreeState:"clean", BuildDate:"2018-10-16T12:14:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.6", GitCommit:"06898a4d0f2b96f82b43d9e59fa2825bd3d616a2", GitTreeState:"clean", BuildDate:"2018-10-02T17:32:01Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
`stable/rabbitmq` version `3.6.0`

**What happened**:
`rabbitmq.diskFreeLimit` value is ignored (the default in `values.yaml` is `6GiB`):
When checking the rabbitmq pod logs:
```
2018-10-30 14:29:36.152 [info] <0.234.0> Disk free limit set to 50MB
```
`50MB` is the default limit (see https://www.rabbitmq.com/disk-alarms.html)

**What you expected to happen**:
`rabbitmq.diskFreeLimit` value should be taken into account by rabbitmq.

**How to reproduce it** (as minimally and precisely as possible):
- install the chart
- check pod logs for `Disk free limit`

**Anything else we need to know**:
It was initially added by #2325 as `rabbitmqDiskFreeLimit`, then renamed to `rabbitmq.diskFreeLimit` and broken by #4591 (notably as mentionned by https://github.com/helm/charts/pull/4591#issuecomment-378716805).

It was previously implemented by translating it to `RABBITMQ_DISK_FREE_LIMIT` environment variable handled by the bitnami docker image, but wouldn't work now that #4591 bypasses the `nami` CMD that setups lots of things...

**Comment by thomas-riccardi** [comment]
Also, the default value of `6GiB` is unusually close to the the default volume provision size of `8GB`.

**Comment by thomas-riccardi** [comment]
Issue is still there.

**Comment by tompizmor** [comment]
I just sent a PR https://github.com/helm/charts/pull/10070
