### ISSUE TITLE
[stable/postgresql] Read postgresql.conf / pg_hba.conf overrides from values

### ISSUE THREAD

**Issue by intelfx** [helm/charts#8916]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

[stable/postgresql](https://github.com/helm/charts/tree/master/stable/postgresql) chart reads complete `postgresql.conf` and `pg_hba.conf` from files. This is inflexible. I propose to change this chart to:

1. Read configuration overrides from values instead of files (see [stable/rabbitmq](https://github.com/helm/charts/blob/master/stable/rabbitmq/values.yaml#L99) for example);
2. Allow extending `postgresql.conf` instead of overriding it (cf. bitnami/bitnami-docker-postgresql#90).

**Comment by desaintmartin** [comment]
See https://github.com/helm/charts/pull/9117
Feel free to close or comment if something is not right.

**Comment by carrodher** [comment]
Hi @intelfx, yes I am currently working on that, but the TO-DO list is not short, any case I will try to do it before the end of next week
