### ISSUE TITLE
traefik chart fails in setup

### ISSUE THREAD

**Issue by KlavsKlavsen** [helm/charts#8952]
BUG REPORT

**Version of Helm and Kubernetes**:
v2.11.0 and kubernetes 1.11.0

**Which chart**:
traefik

**What happened**:
trying to setup traefik with below yaml - results in storeconfig-job failing with:
Error reading TOML config file /config/traefik.toml : Near line 26 (last key parsed 'etcd.tls.ca'): floats must start with a digit, not '.'

**What you expected to happen**:
that it created a working traefik or atleast told me my yaml was invalid :)

in readme for traefik chart it says for RootCA f.ex.: NOTE: You can use file path or cert content directly
it says nothing in kvprovider etcd - so perhaps it does not accept file paths? (and if not - how do I add the certs to the yaml ?) base64 encoded string of file?

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/traefik --name traefik-public --namespace kube-system --values traefik-publicsites.yaml

**traefik-publicsites.yaml**:
```
## Default values for Traefik
serviceType: LoadBalancer
whiteListSourceRange: []
externalTrafficPolicy: Cluster
replicas: 1
cpuRequest: 100m
memoryRequest: 20Mi
cpuLimit: 100m
memoryLimit: 30Mi
debug:
  enabled: false
kubernetes:
  labelSelector: 'realm=public'
ssl:
  enabled: true
kvprovider:
  storeAcme: true
  importAcme: false
  etcd:
    endpoint: traefik-etcd-wtzrrwbb6s.traefik-etcd.default.svc.k8cb.example.org:2379
    useAPIV3: true
    watch: true
    prefix: traefik
    tls: 
      ca: ./etcd-client-ca.crt
      cert: ./etcd-client.crt
      key: ./etcd-client.key
acme:
  enabled: true
  email: myemail@example.org
  onHostRule: true
  logging: false
  challengeType: tls-alpn-01
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
dashboard:
  enabled: false
  domain: traefik.k8cb.example.org
  service: {}
  ingress: {}
  auth: 
     basic:
       traefik: Traef1k
  statistics: {}
gzip:
  enabled: true
traefikLogFormat: json
accessLogs:
  enabled: false
metrics:
  prometheus:
    enabled: true
deployment:
  hostPort:
    httpEnabled: true
    httpsEnabled: true
    dashboardEnabled: true
```

**Comment by KlavsKlavsen** [comment]
if I try to replace the path to a file with base64 encoded contents of the file (starting with LS..) I get this:
 Error reading TOML config file /config/traefik.toml : Near line 26 (last key parsed 'etcd.tls.ca'): expected value but found "LS" instead

**Comment by gaui** [comment]
I get similar:

```
root@d99baa41f3c2:/data# kubectl logs -n traefik traefik-76c88f4d9-7tmhj
2018/11/04 20:14:54 Error reading TOML config file /config/traefik.toml : Near line 33 (last key parsed 'etcd.tls.ca'): expected value but found '/' instead
```
