### ISSUE TITLE
Jaeger chart doesn't include cronjob to run jaegertracing/jaeger-es-index-cleaner

### ISSUE THREAD

**Issue by joeauty** [helm/charts#8956]
**Is this a request for help?**:

No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature request

I'd like to run the es-index-cleaner script that appears to be available in this image: https://hub.docker.com/r/jaegertracing/jaeger-es-index-cleaner/

I haven't yet tested this specific image extensively, but it appears to be a way to run esCleaner.py as described here: https://github.com/jaegertracing/jaeger/tree/master/plugin/storage/es

I'm planning on adding a cronjob template to the Jaeger Helm chart, but I figured before I do so I'd check with the community to see that this would be desired? Otherwise, I'll just run this independent of the Jaeger helm chart.

If it is, it appears that there is kind of a model to follow in the Spark cronjob included in the current image. I'll model this after that.

Again, I'm happy to do this this work, just gauging interest in my contributing this feature...

**Comment by Towmeykaw** [comment]
There is a chart for elasticsearch-curator so it might be easier to use that.

**Comment by joeauty** [comment]
Cool, so would there be support to make this a conditional requirement with curator options/overrides settable within Jaeger's values.yaml file? If so, I'll go about it that way...

**Comment by joeauty** [comment]
Cool, obviously redundant then, I'll close this :)
