### ISSUE TITLE
redis sentinel return wrong master instance 

### ISSUE THREAD

**Issue by yyyyyyyyyg** [helm/charts#8970]
I am using the redis-ha chart, but found the sentinel sometime returns wrong master ip.

When run the command in a sentinel container, it return two different ip.
command:
kubectl get pod -o jsonpath='{range .items[*]}{.metadata.name} {..podIP} {.status.containerStatuses[0].state}{"\n"}{end}' -l redis-role=master

output:
redis-redis-ha-server-56579b75-72z8g **10.1.51.129** **10.1.51.142** map[running:map[startedAt:2018-10-08T05:15:01Z]]

When edit the master pod, I found the podIP in labels are:
podIP: 10.1.51.129
which is different with the pod current IP 10.1.51.142

I am using the chart
version: 2.2.0
appVersion: 4.0.8-r0

**Comment by ssalaues** [comment]
I would suggest upgrading to the newer 3.x versions as there were some big bugs that were recently merged with this PR https://github.com/helm/charts/pull/7323 including the issues you're experiencing.
