### ISSUE TITLE
[redis-ha]Service redirected to slave instead of master

### ISSUE THREAD

**Issue by stanltam** [helm/charts#8988]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.7.2+icp", GitCommit:"d41a5c2da480efc555ddca57d3972bcad3351801", GitTreeState:"dirty"}
Server: &version.Version{SemVer:"v2.7.3+icp", GitCommit:"6479e40ffa8ce42ca520c00a7f90eef45d8cbea3", GitTreeState:"dirty"}

**Which chart**:
redis-ha

**What happened**:
I am using the latest redis-ha which released two days ago:
version: 3.0.0
appVersion: 4.0.11

And I have 3 replica(default) specified in values.yaml. I can install the helm successfully. However, I failed to connect to redis using the service name. Attached please find the evidence:

**Current Running master:**
I have no name!@redis-db-new-redis-ha-server-1:/data$ redis-cli -p 26379  SENTINEL get-master-addr-by-name mymaster
1) "10.1.123.16"
2) "6379"

**failed to call using service name**
I have no name!@redis-db-new-redis-ha-server-1:/data$redis-cli -h redis-db-new-redis-ha.redis-new -p 6379 MSET firstname Jack lastname Stuntman age 35
(error) READONLY You can't write against a read only slave.

**able to call using master ip**
I have no name!@redis-db-new-redis-ha-server-1:/data$redis-cli -h 10.1.123.16 -p 6379 MSET firstname Jack lastname Stuntman age 35
OK

**Suspect**
So i find the service yaml and see the pod selector is simple as following:
    selector:
      app: redis-ha
      release: redis-db-new

And it will select all pods?
root@hci-apicee-master-ubuntu-5:~# kubectl get pods -n redis-new -l app=redis-ha,release=redis-db-new -o wide
NAME                             READY     STATUS    RESTARTS   AGE       IP            NODE
redis-db-new-redis-ha-server-0   2/2       Running   0          39m       10.1.57.205   9.37.134.81
redis-db-new-redis-ha-server-1   2/2       Running   0          38m       10.1.62.143   9.37.201.66
redis-db-new-redis-ha-server-2   2/2       Running   0          38m       10.1.123.16   9.42.1.109

In previous version, it select the pod with 
  selector:
    app: redis-ha
    redis-node: "true"
    redis-role: master
    release: redis-db

so, is something missing in this release?

**What you expected to happen**:
Able to call using service name 
redis-cli -h redis-db-new-redis-ha.redis-new -p 6379 MSET firstname Jack lastname Stuntman age 35
**How to reproduce it** (as minimally and precisely as possible):
simply install with replica 3 and call redis using cli

**Anything else we need to know**:

**Comment by alexvicegrab** [comment]
I'm having the same issue, seeing

```
Error ReplyError: READONLY You can't write against a read only slave.
```

when connecting to the Service.

**Comment by poknam** [comment]
same here:

(error) READONLY You can't write against a read only slave.

**Comment by poknam** [comment]
@ssalaues Can you advise how to configure client (outside the redis cluster) to use this new version of redis?

Thank you.

**Comment by ssalaues** [comment]
@poknam If you're trying to expose redis to clients external to the kubernetes cluster I would suggest using something like haproxy similar to how @prodriguezdefino uses.
https://github.com/helm/charts/pull/7323#issuecomment-436302976

Aside from this, the chart itself doesn't currently have provisions for exposing the services externally.

**Comment by hdimitriou** [comment]
If I understand well, on the previous 2.x chart version if you had a client it would connect to the master service and it would not be aware there are sentinels or redis-slaves. 
On 3.x version however, if I understand well we need a sentinel-aware client, right, like https://docs.spring.io/spring-data/redis/docs/2.1.2.RELEASE/reference/html/#redis:sentinel ?
Can you please verify?

To be frank, I did like the 2.x approach that used Kubernetes mechanics to hide the sentinels

**Comment by ssalaues** [comment]
Yes you are correct and the linked is a valid example @hdimitriou . The 2.x approach was nice in theory but the resulting implementation was too problematic to the point that it would cause critical failures, multiple masters, and/or partitioned servers.

**Comment by hdimitriou** [comment]
I was wondering,  implementing an operator who polls sentinel frequently and updates a redis master service with clusterip, that would just show a redis master.  
But I also wonder if it's worth doing that to 'hide' sentinel since Redis clients support sentinel..

**Comment by hdimitriou** [comment]
And one more question: on the redis client side, is it enough to put the service:<sentinel-port> on the configuration, instead of a string of host1:port,host2:port,... ?

**Comment by hustshawn** [comment]
It would be nice if separate services for both master and slave can be extracted. 
Users would have to access point, which should be like, `master.redis-ns.svc.cluster.local` and `slave.redis-ns.svc.cluster.local`, which brings the benefit for users to choose the master connection for the write operation and the slave for the read-only purpose, without caring about the HA details of Redis cluster underhood.
