### ISSUE TITLE
elasticsearch xpack for 5.* ES is causing issues

### ISSUE THREAD

**Issue by blazespinnaker** [helm/charts#8996]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
stable/elasticsearch

**What happened**:
fails to deploy for v5 because of xpack is enabled in v5 dockers, need to explicitly disable (see below)

**What you expected to happen**:
 success
`
**How to reproduce it** (as minimally and precisely as possible):
Diffs here:
--- a/stable/elasticsearch/values.yaml
+++ b/stable/elasticsearch/values.yaml
@@ -1,7 +1,7 @@
-appVersion: "6.4.2"
+appVersion: "5.4"

@@ -32,8 +32,9 @@ podSecurityPolicy:
 image:
-  repository: "docker.elastic.co/elasticsearch/elasticsearch-oss"
-  tag: "6.4.2"
+  repository: "centerforopenscience/elasticsearch"
+  tag: "5.4"
..
--- a/stable/elasticsearch/Chart.yaml
+++ b/stable/elasticsearch/Chart.yaml
@@ -1,7 +1,7 @@
 name: elasticsearch
 home: https://www.elastic.co/products/elasticsearch
 version: 1.13.2
-appVersion: 6.4.2
+appVersion: 5.4

**Anything else we need to know**:
I was able to fix it via this:
--- a/stable/elasticsearch/templates/configmap.yaml
+++ b/stable/elasticsearch/templates/configmap.yaml
@@ -39,13 +39,12 @@ data:
         ping.unicast.hosts: ${DISCOVERY_SERVICE:}
         minimum_master_nodes: ${MINIMUM_MASTER_NODES:2}

-{{- if .Values.cluster.xpackEnable }}
     xpack.ml.enabled: ${XPACK_ML_ENABLED:false}
     xpack.monitoring.enabled: ${XPACK_MONITORING_ENABLED:false}
     xpack.security.enabled: ${XPACK_SECURITY_ENABLED:false}
     xpack.watcher.enabled: ${XPACK_WATCHER_ENABLED:false}
-{{- end }}
+
`

**Comment by runningman84** [comment]
Feel free to check this out: https://github.com/arvatoaws/graylog-helm-chart/blob/master/graylog/values.yaml
I managed to disable it via some env settings
