### ISSUE TITLE
stable/verdaccio chart does not honor customConfigMap option

### ISSUE THREAD

**Issue by jeckhart** [helm/charts#9014]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm: 2.11.0
K8S: 2.10.2

**Which chart**:
stable/verdaccio

**What happened**:
The docs for verdaccio describe overriding the default config using a configmap and specify a chart option of `customConfigMap` for that purpose. However, the chart code does not actually use `customConfigMap` and always uses the default config map.

ie. the following command, according to the docs, should use a custom config map:
```helm install --name my-release --set customConfigMap=verdaccio-config stable/verdaccio```

However, when inspecting the output, verdaccio is built with the default config map.

**What you expected to happen**:
When installing using a custom config map, the deployed assets reference that config at runtime.

**How to reproduce it** (as minimally and precisely as possible):
```helm install --name my-release --set customConfigMap=verdaccio-config stable/verdaccio```

**Anything else we need to know**:

**Comment by jeckhart** [comment]
We've been using this branch on our side successfully. What is needed to get this merged?

**Comment by jeckhart** [comment]
bump

**Comment by Patafix** [comment]
I also need this fix. Thanks for you're work @jeckhart

**Comment by jeckhart** [comment]
Bump ... what it takes to get a PR merged for helm charts.

**Comment by jeckhart** [comment]
Can I get someone to review this, and if ready, give it a /lgtm please??

**Comment by Patafix** [comment]
Up

**Comment by djvs** [comment]
This is a serious bug with security consequences, please address

**Comment by djvs** [comment]
@etiennetremel
