### ISSUE TITLE
Unable to set env or config file

### ISSUE THREAD

**Issue by jonatasfreitasv** [helm/charts#9026]
Hi!

I'm using this chart (https://github.com/helm/charts/tree/master/stable/kibana)

I need to set elasticsearch.url config, but, not work.

How I use env or files parameter?

Any idea?

**Comment by vsliouniaev** [comment]
@jonatasfreitasv  you're probably looking for the Helm docs on how to use variables:
https://docs.helm.sh/using_helm/#customizing-the-chart-before-installing

So in your specific case it would be 
https://github.com/helm/charts/blob/master/stable/kibana/values.yaml#L14

`--set env.ELASTICSEARCH_URL=http://elasticsearch-client:9200`

Could you use the template that's provided when you open an issue? It makes it much easier to sort issues to the correct person.

**Comment by jonatasfreitasv** [comment]
Man, thx very very a lot!! I try a lot of options!!
