### ISSUE TITLE
No way to supply `initContainers` in prometheus-operator

### ISSUE THREAD

**Issue by kuznero** [helm/charts#9031]
**FEATURE REQUEST**

Add `initContainers` to make it possible to initialize e.g. storage with `hostPath` to be able to set appropriate permissions.

**Version of Helm and Kubernetes**: `helm, v2.11.0`, `kube, v1.12.1`

**Which chart**: `prometheus-operator, v0.1.12`

**What you expected to happen**: be able to supply `initContainers` in similar way `containers` supplied.

This is what we have today:

```yaml
{{- if .Values.prometheus.prometheusSpec.containers }}
  containers:
{{ toYaml .Values.prometheus.prometheusSpec.containers | indent 4 }}
{{- end }}
```

This is what needs to be added:

```yaml
{{- if .Values.prometheus.prometheusSpec.initContainers }}
  initContainers:
{{ toYaml .Values.prometheus.prometheusSpec.initContainers | indent 4 }}
{{- end }}
```

**Comment by paskal** [comment]
Could it be closed?
