### ISSUE TITLE
[stable/prometheus-operator] incorrect rules labels

### ISSUE THREAD

**Issue by paskal** [helm/charts#9034]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report

**Version of Helm and Kubernetes**:
```
➜  ~  helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
➜  ~  kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:18:13Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.6", GitCommit:"d1d4d355f9364d164ca6e485cea3e60e0fa913ca", GitTreeState:"clean", BuildDate:"2018-09-28T00:40:25Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
k8s cluster is GKE

**Which chart**:
stable/prometheus-operator v0.1.14

**What happened**:
Labels set for alert:
```
alertname="KubeJobCompletion"
endpoint="http"
instance="10.36.1.129:8080"
job="kube-state-metrics"
job_name="some_job-1537981200"
namespace="dev-env"
pod="prometheus-kube-state-metrics-69db7f65dc-t7nz9"
service="prometheus-kube-state-metrics"
severity="warning"
```
Alert annotation:
```
message
    Job /kube-state-metrics is taking more than one hour to complete.
```
**What you expected to happen**:
Alert annotation:
```
message
    Job dev-env/some_job-1537981200 is taking more than one hour to complete.
```
**How to reproduce it** (as minimally and precisely as possible):
Deploy chart in a quick way and fail a job, you'll see wrong alert annotation message as above.

**Anything else we need to know**:
[prometheus-rules.yaml](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus-rules.yaml) coreos file, imported by name of [all-prometheus-rules.yaml](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/all-prometheus-rules.yaml) here have misconfigured labels.
Following should be redefined:
```
{{ $labels.job }} -> {{ $labels. job_name }}
{{ $labels.namespaces }} -> {{ $labels.namespace }}
```
Interesting thing is what `labels.namespace` is already used in part of alerts.
@gianrubio, can I fix it in coreos/prometheus-operator? Or it's intentional and should (or should not) be fixed only in this repo?

**Comment by gianrubio** [comment]
Please read and follow the instructions on https://github.com/coreos/prometheus-operator/pull/2096
and them make a PR here with the changes

**Comment by paskal** [comment]
If I understand correctly, in the end we want import rules and dashboards directly from https://github.com/kubernetes-monitoring/kubernetes-mixin, without touching coreos/prometheus-operator.
What should i do **here** after https://github.com/coreos/prometheus-operator/pull/2096 will be merged? Sync everything somehow? Or fix only current issue and work on proper sync solution at https://github.com/helm/charts/issues/8749?
