### ISSUE TITLE
Redis connection issue

### ISSUE THREAD

**Issue by ravenzak** [helm/charts#9065]
**BUG REPORT** 

**Version of Helm and Kubernetes**:
$ helm version
Client: &version.Version{SemVer:"v2.11.0", 
Server: &version.Version{SemVer:"v2.11.0", 

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.13", GitCommit:"290fb182489a396dce5d136451388f9b12f29c94", GitTreeState:"clean", BuildDate:"2018-05-15T18:08:47Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
redis-ha

**What happened**:
There is a problem. After pod eviction (or pod deleting), redis slave pod recreates and doesn't have connection to master:
LOG:
active_defrag_key_misses:0
 
 Replication
 role:master
 connected_slaves:1
 master_replid:a7d98991e515a5df5c07c1bd6b23533a61d620cf
 master_replid2:0000000000000000000000000000000000000000
 master_repl_offset:142067
 second_repl_offset:-1
 repl_backlog_active:1
 repl_backlog_size:1048576
 repl_backlog_first_byte_offset:1
 repl_backlog_histlen:142067
 
 CPU
 used_cpu_sys:0.89
 used_cpu_user:0.39
 used_cpu_sys_children:0.00
 used_cpu_user_children:0.00
 
 Cluster
 cluster_enabled:0
 
 Keyspace
 68:C 07 Nov 08:34:03.647 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
68:C 07 Nov 08:34:03.647 # Redis version=4.0.9, bits=64, commit=757d0c15, modified=0, pid=68, just started
68:C 07 Nov 08:34:03.647 # Configuration loaded
68:S 07 Nov 08:34:03.659 # Can't open the append-only file: No such file or directory
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
.
. 
. 
 

**What you expected to happen**:
Right connection to master pod, after pod recreation by deployment or pod eviction.

**How to reproduce it** (as minimally and precisely as possible):
So, first of all deploy redis-ha with helm
$ helm install redis-ha
After pods and sentinels creation, you should check connection from slaves to master pod with:
$ kubectl logs <container_name>
After checking connectivity, you can simulate pod eviction or just delete him. After recreation, pod will not have connection to master.
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused

**Anything else we need to know**:
Redis image:
#redis_image: quay.io/smile/redis:4.0.8r0

Related issues:
68:S 07 Nov 08:00:50.798 # Error trying to rename the temporary AOF file temp-rewriteaof-bg-6404.aof into appendonly.aof: Permission denied 

Redis config:
6379> CONFIG GET *
  1) "dbfilename"
  2) "dump.rdb"
  3) "requirepass"
  4) ""
  5) "masterauth"
  6) ""
  7) "cluster-announce-ip"
  8) ""
  9) "unixsocket"
 10) ""
 11) "logfile"
 12) ""
 13) "pidfile"
 14) "/var/run/redis.pid"
 15) "slave-announce-ip"
 16) ""
 17) "maxmemory"
 18) "0"
 19) "proto-max-bulk-len"
 20) "536870912"
 21) "client-query-buffer-limit"
 22) "1073741824"
 23) "maxmemory-samples"
 24) "5"
 25) "lfu-log-factor"
 26) "10"
 27) "lfu-decay-time"
 28) "1"
 29) "timeout"
 30) "0"
 31) "active-defrag-threshold-lower"
 32) "10"
 33) "active-defrag-threshold-upper"
 34) "100"
 35) "active-defrag-ignore-bytes"
 36) "104857600"
 37) "active-defrag-cycle-min"
 38) "25"
 39) "active-defrag-cycle-max"
 40) "75"
 41) "auto-aof-rewrite-percentage"
 42) "100"
 43) "auto-aof-rewrite-min-size"
 44) "67108864"
 45) "hash-max-ziplist-entries"
 46) "512"
 47) "hash-max-ziplist-value"
 48) "64"
 49) "list-max-ziplist-size"
 50) "-2"
 51) "list-compress-depth"
 52) "0"
 53) "set-max-intset-entries"
 54) "512"
 55) "zset-max-ziplist-entries"
 56) "128"
 57) "zset-max-ziplist-value"
 58) "64"
 59) "hll-sparse-max-bytes"
 60) "3000"
 61) "lua-time-limit"
 62) "5000"
 63) "slowlog-log-slower-than"
 64) "10000"
 65) "latency-monitor-threshold"
 66) "0"
 67) "slowlog-max-len"
 68) "128"
 69) "port"
 70) "6379"
 71) "cluster-announce-port"
 72) "0"
 73) "cluster-announce-bus-port"
 74) "0"
 75) "tcp-backlog"
 76) "511"
 77) "databases"
 78) "16"
 79) "repl-ping-slave-period"
 80) "10"
 81) "repl-timeout"
 82) "60"
 83) "repl-backlog-size"
 84) "1048576"
 85) "repl-backlog-ttl"
 86) "3600"
 87) "maxclients"
 88) "10000"
 89) "watchdog-period"
 90) "0"
 91) "slave-priority"
 92) "100"
 93) "slave-announce-port"
 94) "0"
 95) "min-slaves-to-write"
 96) "0"
 97) "min-slaves-max-lag"
 98) "10"
 99) "hz"
100) "10"
101) "cluster-node-timeout"
102) "15000"
103) "cluster-migration-barrier"
104) "1"
105) "cluster-slave-validity-factor"
106) "10"
107) "repl-diskless-sync-delay"
108) "5"
109) "tcp-keepalive"
110) "60"
111) "cluster-require-full-coverage"
112) "yes"
113) "cluster-slave-no-failover"
114) "no"
115) "no-appendfsync-on-rewrite"
116) "no"
117) "slave-serve-stale-data"
118) "yes"
119) "slave-read-only"
120) "yes"
121) "stop-writes-on-bgsave-error"
122) "yes"
123) "daemonize"
124) "no"
125) "rdbcompression"
126) "yes"
127) "rdbchecksum"
128) "yes"
129) "activerehashing"
130) "yes"
131) "activedefrag"
132) "no"
133) "protected-mode"
134) "no"
135) "repl-disable-tcp-nodelay"
136) "no"
137) "repl-diskless-sync"
138) "no"
139) "aof-rewrite-incremental-fsync"
140) "yes"
141) "aof-load-truncated"
142) "yes"
143) "aof-use-rdb-preamble"
144) "no"
145) "lazyfree-lazy-eviction"
146) "no"
147) "lazyfree-lazy-expire"
148) "no"
149) "lazyfree-lazy-server-del"
150) "no"
151) "slave-lazy-flush"
152) "no"
153) "maxmemory-policy"
154) "noeviction"
155) "loglevel"
156) "notice"
157) "supervised"
158) "no"
159) "appendfsync"
160) "everysec"
161) "syslog-facility"
162) "local0"
163) "appendonly"
164) "yes"
165) "dir"
166) "/redis-master-data"
167) "save"
168) "900 1 300 10 60 10000"
169) "client-output-buffer-limit"
170) "normal 0 0 0 slave 268435456 67108864 60 pubsub 33554432 8388608 60"
171) "unixsocketperm"
172) "0"
173) "slaveof"
174) ""
175) "notify-keyspace-events"
176) ""
177) "bind"
178) "0.0.0.0"

**Comment by ssalaues** [comment]
It sounds like you're using the 2.x version of the chart. Many of the issues with that version was fixed in 3.x but changed some of the expected behavior. 

See PR:
https://github.com/helm/charts/pull/7323
Behavior discussion:
https://github.com/helm/charts/issues/8988

**Comment by ravenzak** [comment]
> It sounds like you're using the 2.x version of the chart. Many of the issues with that version was fixed in 3.x but changed some of the expected behavior.
> 
> See PR:
> #7323
> Behavior discussion:
> #8988

issue can be closed, because this issue was resolved by using redis-ha based on statefull-set.
