### ISSUE TITLE
[stable/prometheus-operator] warning: cannot overwrite table with non table for annotations (map[])

### ISSUE THREAD

**Issue by rewt** [helm/charts#9083]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm version                                                              
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

k8s v 1.11.3

**Which chart**:
stable/prometheus-operator

**What happened**:
warning on deploy - creates issues on VSTS release pipeline

**How to reproduce it** (as minimally and precisely as possible):
helm lint ./                                                               
2018/11/07 15:21:37 warning: cannot overwrite table with non table for annotations (map[])
2018/11/07 15:21:37 warning: cannot overwrite table with non table for annotations (map[])
2018/11/07 15:21:37 warning: cannot overwrite table with non table for annotations (map[])
2018/11/07 15:21:37 warning: cannot overwrite table with non table for annotations (map[])
==> Linting ./
Lint OK

1 chart(s) linted, no failures

**Anything else we need to know**:
Deploy completes successfully, but throws error.  What is the source of the warning?  Other threads suggestion something in values, but that was in coreos version these warnings weren't' popping up until latest version of chart.

**Comment by vsliouniaev** [comment]
I am unable to reproduce your issue

```
$ cat ./stable/prometheus-operator/Chart.yaml | grep version
version: 0.1.15
```
```
$ helm lint ./stable/prometheus-operator
==> Linting ./stable/prometheus-operator
Lint OK

1 chart(s) linted, no failures
```

**Comment by maver1ck** [comment]
I thinks this is the same bug:
https://github.com/coreos/prometheus-operator/issues/2025

**Comment by rewt** [comment]
> I am unable to reproduce your issue
> 
> ```
> $ cat ./stable/prometheus-operator/Chart.yaml | grep version
> version: 0.1.15
> ```
> ```
> $ helm lint ./stable/prometheus-operator
> ==> Linting ./stable/prometheus-operator
> Lint OK
> 
> 1 chart(s) linted, no failures
> ```

hmm...any insight what could be producing the warnings?  Must be typo somewhere.  There are 4 consecutive.  Reminds me of CRDs, though not sure what to look for.

**Comment by rewt** [comment]
> I thinks this is the same bug:
> [coreos/prometheus-operator#2025](https://github.com/coreos/prometheus-operator/issues/2025)

I've noticed this thread, but doesn't seem to apply to helm implementation as there doesn't appear be a values.yaml for prometheus.

**Comment by prajnadnayak** [comment]
i face the similar issue. I added  below line to the values.yaml under the grafana section

path: '/grafana/'
 grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  server:
    root_url: https://myhost.com/grafana/

But I get below error. 
 Warning: Merging destination map for chart 'prometheus-operator'. Cannot overwrite table item 'grafana.ini', with non table value: map[grafana_net:map[url:https://grafana.net] log:map[mode:console] paths:map[data:/var/lib/grafana/data logs:/var/log/grafana plugins:/var/lib/grafana/plugins provisioning:/etc/grafana/provisioning] analytics:map[check_for_updates:true]]
