### ISSUE TITLE
[stable/grafana] PodSecurityPolicy breaks install on hosts without AppArmor

### ISSUE THREAD

**Issue by drakedevel** [helm/charts#9090]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Version of Helm and Kubernetes**:
Helm 2.10.0, Kubernetes 1.10.7

**Which chart**:
stable/grafana

**What happened**:
I attempted to install the grafana/stable chart on our Kubernetes cluster running on Amazon Linux 2 with PodSecurityPolicy enforcement enabled. The resulting Grafana pod failed to start and entered state `Blocked` with the following message:

>Cannot enforce AppArmor: AppArmor is not enabled on the host

**What you expected to happen**:
I expected the Grafana pod to start up successfully.

**How to reproduce it** (as minimally and precisely as possible):
Install the Grafana chart with default values on a cluster with PodSecurityPolicy enabled, with nodes running any distribution without AppArmor (e.g. Amazon Linux 2, CentOS, Debian by default).

**Anything else we need to know**:
The best workaround at this point is to set `rbac.pspEnabled` to false and create the PSP and associated roles externally, which can be pretty painful.

I will try to send a PR later this week to add a setting to allow the AppArmor annotations to be turned off with a value change.

**Comment by rramadoss4** [comment]
I have the same issue..
Cannot enforce AppArmor: AppArmor is not enabled on the host

**kubernetes.io/psp**: kube-prometheus-stack-grafana
