### ISSUE TITLE
[stable/newrelic-infrastructure]Ability to set NewRelic Display Name

### ISSUE THREAD

**Issue by HeinrichL93** [helm/charts#9099]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Version of Helm and Kubernetes**:
helm v2.9.1
kubectl v1.12.0

**Which chart**:
stable/newrelic-infrastructure

**What happened**:
New Relic display name env "NRIA_DISPLAY_NAME" is set to display spec.nodeName

**What you expected to happen**:
The ability to set the NewRelic display name in the env "NRIA_DISPLAY_NAME".
currently it's set to display only spec.nodeName and thus cannot filter by Host name in NewRelic Infrastructure.

**Anything else we need to know**:
Setting "config" in values.yaml has no affect.
Tried to set the display name in newrelic-infra.yml. I can see the changes in /etc/newrelic-infra.yml but the env "NRIA_DISPLAY_NAME" takes priority and keep the spec.nodeName.

**Comment by millermatt** [comment]
Please re-open

**Comment by millermatt** [comment]
@jfjoly

**Comment by jfjoly** [comment]
@millermatt @HeinrichL93 can you give an example of what you would set the variable to be instead of spec.nodeName?
BTW; I don't have permissions to re-open issues.

**Comment by HeinrichL93** [comment]
@jfjoly potentially having the ability to set it to any value, as NewRelic Infrastructure groups by host.
it's easier to filter a Kubernetes cluster on NewRelic with multiple nodes when they all have the same hostnames. 
```
            - name: NRIA_DISPLAY_NAME
              value: {{ .Values.displayName }}
```

**Comment by millermatt** [comment]
Hi, @jfjoly - thanks for responding!

The newrelic-infrastructure Helm chart readme says that you can provide a `config` value that should have the contents of a newrelic.yaml file. It says you can use this to override the host display name:
- https://github.com/helm/charts/tree/master/stable/newrelic-infrastructure#config-file
- https://github.com/helm/charts/blob/master/stable/newrelic-infrastructure/values.yaml#L64 

This doesn't appear to work.

I have a file, `newrelic.yaml` with these contents:
```yaml
config:
    display_name: custom-host-name
```
I install the Helm chart:
```bash
helm upgrade newrelic stable/newrelic-infrastructure --install \
        --set licenseKey=$NEWRELIC_LICENSE \
        --set cluster=$CLUSTER_NAME \
        -f ./temp/newrelic.chart-values.yaml
        --namespace kube-system
```

I see that a ConfigMap gets created with the contents:
```yaml
newrelic.yaml: |
  display_name: custom-host-name
```

When I view the newrelic-infrastructure pod logs I see:
`Using Display Name: ip-10-40-236-178.us-west-2.compute.internal`, which is the EC2 instance name, not `custom-host-name`.
