### ISSUE TITLE
[stable/prometheus-operator] No migration path from coreos chart

### ISSUE THREAD

**Issue by maver1ck** [helm/charts#9108]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

Helm v2.10
K8s v1.10

**Which chart**:

stable/prometheus-operator

**What happened**:

I tried to migrate my env from coreos to stable Chart but some configuration changes are difficult or imposible to do.
1) New prometheus and alertmanager have different names (with same release name) than in coreos chart which mean that I can't use the same PVC. 
2) Some of the configuration options are very difficult or impossible to migrate. Example:
- grafana.serverDashboardFiles
- prometheus.rules.value
3) Existing documentation can be broken. Example:
- prometheus.prometheusSpec.storage in README is prometheus.prometheusSpec.storage**Spec** in template

**What you expected to happen**:

There should be documentation how to migrate between charts and way to use old PVC.

**Comment by maver1ck** [comment]
@gianrubio What do you think ?

**Comment by vsliouniaev** [comment]
Relates to https://github.com/helm/charts/issues/9288

**Comment by maver1ck** [comment]
@paskal 
1) I think there should be documentation with mapping from old to new options.
2) There is no possibility to reuse existing PVC (and this is a bug described in above issue)

**Comment by paskal** [comment]
I agree with you. However, you (and other people doing actual migrations to new chart) are the only persons who is capable of writing such documentation.
