### ISSUE TITLE
[stable/prometheus-operator] serviceMonitorSelector select all labels

### ISSUE THREAD

**Issue by dojadop** [helm/charts#9125]
Is there a way to serviceMonitorSelector all labels?  It looks like if you don't set serviceMonitorSelector then it defaults to the release label

prometheus.yaml
```
{{- if .Values.prometheus.prometheusSpec.serviceMonitorSelector }}
  serviceMonitorSelector:
{{ toYaml .Values.prometheus.prometheusSpec.serviceMonitorSelector | indent 4 }}
{{ else}}
  serviceMonitorSelector:
    matchLabels:
      release: {{ .Release.Name | quote }}
{{- end }}
```

**Comment by dojadop** [comment]
The only way I can think to do this is to remove this logic all together and just make it:
```
{{- if .Values.prometheus.prometheusSpec.serviceMonitorSelector }}
  serviceMonitorSelector:
{{ toYaml .Values.prometheus.prometheusSpec.serviceMonitorSelector | indent 4 }}
{{ else}}
  serviceMonitorSelector: {}
{{- end }}
```
although this changes the default behavior of just selecting service monitors of the same release. Could add some documentation around this, thoughts?

**Comment by vsliouniaev** [comment]
@dojadop You could provide a value here using `matchExpressions` that would effectively work the same way as selecting all servicemonitors in the same namespace. If this does not suit your needs, could you explain your use-case in more detail?

**Comment by dojadop** [comment]
The more I have worked with the service monitors the more I understand the best way to configure them.  I think i was struggling with how to monitor across namespaces and different release labels.  I think the documentation wasn't clear on the default behavior just like in #9140. 

I keep seeing something like this https://github.com/coreos/prometheus-operator/issues/1940#issuecomment-424624824 but its not possible with the helm chart, but I think I am fine now that I understand the default behavior of serviceMonitorSeletor.
