### ISSUE TITLE
Why do we have redundant charts for Prometheus components? 

### ISSUE THREAD

**Issue by teja-v1** [helm/charts#9155]
I would like to understand the purpose of having redundant charts in the stable directory.

We already have a Prometheus chart, which can enable a user to turn ON/OFF AlertManager, PushGateway, KubestateMetrics and Node Exporter.
Then what is the purpose to create separate charts for all these components again? Like a separate standalone Node Exporter, PushGateway charts...? Why do we need separate charts? what advantage do we get?

I would also like to know the benefit of using either the giant chart/standalone chart from the community. Which one is recommended for Production grade systems?

Thanks,
Teja

**Comment by vsliouniaev** [comment]
The `prometheus-node-exporter`, `kube-state-metrics`, `grafana` charts are used by the `prometheus-operator` chart. You could use the `prometheus-pushgateway` chart if required to connect `prometheus-operator` as well.

We are using `prometheus-operator` as opposed to the `prometheus` chart as it makes managing multiple separate instances of prometheus running in the same cluster easier.

**Comment by tejaswiniVadlamudi** [comment]
Hi Vasily Sliouniaev,

Thanks for the answer. I am already using "Prometheus" but why should one need to use this "Prometheus Operator"? What advantages do we have with it? Is there page/link which guides a newbie?

Thanks,
Teja
