### ISSUE TITLE
[stable/prometheus] Default rules

### ISSUE THREAD

**Issue by dolftax** [helm/charts#9167]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature req

**Version of Helm and Kubernetes**:
latest

**Which chart**:
stable/prometheus

**What happened**:
No default alert rules

**What you expected to happen**:
Add default alert rules

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by jaipradeesh** [comment]
Re-opening
