### ISSUE TITLE
[stable/mongodb-replicaset] Replica set for configsvr fails

### ISSUE THREAD

**Issue by zabirauf** [helm/charts#9186]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: v2.10.0, v1.12.1

**Which chart**: mongodb-replicaset

**What happened**:
Setting up a replica set for a config server fails with the following error
```
Nodes started with the --configsvr flag must have configsvr:true in their config" while validating
```

**What you expected to happen**:
The expected outcome is that the replica set for the configsvr cluster role is setup. When initiating the replica set the config server should be set to true.

**How to reproduce it** (as minimally and precisely as possible):
Deploy the helm with the following configmap
```
configmap:
    sharding:
        clusterRole: configsvr
```

**Anything else we need to know**:

**Comment by steven-sheehy** [comment]
Sharding/config servers is not supported in mongodb-replicaset. You're welcome to work on adding such a feature.
