### ISSUE TITLE
[stable/rabbitmq-ha] Support setting cluster_partition_handling

### ISSUE THREAD

**Issue by msvticket** [helm/charts#9194]
This is a **FEATURE REQUEST**

**Chart:** stable/rabbitmq-ha

I'd like to be able to configure setting cluster_partition_handling. This is now set to `autoheal`, but it's not he best option for all use cases. So support for a setting a value like called, say, `clusterPartitionHandling` would be welcome.

**Comment by steven-sheehy** [comment]
Unless you submit a PR that adds that functionality to templatize that variable, the only way to accomplish that would be to override the existingConfigMap and provide your own.
