### ISSUE TITLE
Add atlassian bitbucket chart

### ISSUE THREAD

**Issue by onyxet** [helm/charts#9210]
**Is this a request for help?**:

Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Anything else we need to know**:
I want to suggest add atlassian bitbucket chart to helm repo. It might be useful for containerized deployments of BB and for all who're using it.

**Comment by fsadykov** [comment]
Yes it will be very helpfull
