### ISSUE TITLE
[stable/redis-ha]Possible to run *only* sentinel using this?

### ISSUE THREAD

**Issue by iloveicedgreentea** [helm/charts#9211]
In the new redis-ha chart, is there a way to run only sentinel to point to another redis cluster?

**Comment by ssalaues** [comment]
@iloveicedgreentea Currently, no there is not a way to do this. The chart is too intertwined with redis to be able to do this. While this could be an interesting feature/update, honestly might be easier to create a `sentinel` chart.

**Comment by ssalaues** [comment]
Haha no problem! We all were in need of those redis updated. 

But yeah that makes sense. I think this could be an interesting feature for others with your use-case incase you plan to open a PR.
