### ISSUE TITLE
[stable/mariadb] files/docker-entrypoint-initdb.d/* on parent chart doesn't work

### ISSUE THREAD

**Issue by hidekuro** [helm/charts#9218]
# Summary

files/docker-entrypoint-initdb.d/* on parent chart doesn't work when use stable/mariadb as subchart.

# Description

## How to reproduce

files overview:

![tree](https://user-images.githubusercontent.com/3986668/48401674-066c1c00-e76d-11e8-9cd4-4b3d063800ad.png)

```bash
# 1. create sample
helm create sample

# 2. add deps `stable/mariadb` to sample
cat <<EOC | tee ./sample/requirements.yaml
dependencies:
- name: mariadb
  version: 5.2.3
  repository: https://kubernetes-charts.storage.googleapis.com
EOC

# 3. create initdb scripts in parent chart
mkdir -p ./sample/files/docker-entrypoint-initdb.d

cat <<EOC | tee ./sample/files/docker-entrypoint-initdb.d/test.sh
#!/bin/sh
echo "run test.sh"
EOC

# 4. install/update deps
helm dep up ./sample

# 5. render
helm template -f ./sample/values.yaml ./sample
```

as a result, empty `mariadb/templates/initialization-configmap.yaml` shown.

```
---
# Source: sample/charts/mariadb/templates/initialization-configmap.yaml

---
```

I expected non-empty `mariadb/templates/initialization-configmap.yaml` using `sample/files/docker-entrypoint-initdb.d/test.sh`.

Should I need any modification to mariadb?

I wouldn't like to do an approach to untar the subchart and change it.

**Comment by afroald** [comment]
Have you found a solution to this?

**Comment by juan131** [comment]
Hi everyone,

I just created a PR to add some alternatives to specify the initdb scripts to use. As you mentioned there's no way to indicate these scripts with the current method when using the chart as a dependency.

**Comment by bhagyas** [comment]
+1
