### ISSUE TITLE
[stable/concourse] imagepullSecrets support (use of images from private registry)

### ISSUE THREAD

**Issue by prein** [helm/charts#9228]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Version of Helm and Kubernetes**:
Helm 2.9.0
Kubernetes 1.9.0

**Which chart**:
stable/concourse version 3.0.0

**What happened**:
I am running Kubernetes behind firewall and wanted to use concourse docker image from private registry. Currently the helm chart doesn't allow for specifying imagepullSecrets so I had to modify the chart locally to use it.

**What you expected to happen**:
I would like to be able to provide image.pullSecrets as part of values.yaml, similarly to how I do it, for example, in postgresql chart

**How to reproduce it** (as minimally and precisely as possible):
Try using concourse image from a docker registry that requires auth

**Comment by cirocosta** [comment]
Hey @prein ,

Yesterday, I submitted a PR that might address this issue.

Would you mind taking a look at it?

thx!
