### ISSUE TITLE
Make optional MariaDB dependency for JasperReports

### ISSUE THREAD

**Issue by cemo** [helm/charts#923]
Please make MariaDB dependency as optional because we are using AWS MySQL and would like to persist all our data in this DB.  

Gentle ping @prydonius :)

**Comment by prydonius** [comment]
Thanks @cemo, we need to make use of the [condition fields](https://github.com/kubernetes/helm/blob/master/docs/charts.md#tags-and-condition-fields-in-requirementsyaml) in the chart's requirements.yaml to make the MariaDB chart optional, and then also extend the configuration of the chart to specify a custom database host.

I think this is something we need to do across all the charts that depend on a database.
