### ISSUE TITLE
[stable/spinnaker] Change halyard feature and add storageclass option

### ISSUE THREAD

**Issue by ricklagerweij** [helm/charts#9230]
**Is this a request for help?**:
No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

--pipelineTemplates should be changed to --pipeline-templates (last step, fails when running with 1.12.0) 
Add PVC StorageClass option in the values.yaml to define a storageclass.

**Version of Helm and Kubernetes**:
Helm 2.11.0 with Kubernetes 1.12.0

**Which chart**:
Stable

**What happened**:
Fails on last step with 1.12.0 upgraded from 1.9.1 (For future stable version), fail to create pvc because no storageclass matches.

**What you expected to happen**:
Finish the script in config map

**How to reproduce it** (as minimally and precisely as possible):
Change halyard image version

**Anything else we need to know**:

**Comment by rus4** [comment]
.
