### ISSUE TITLE
Jenkins Helm Chart is missing lifecycle PostStart Hooks

### ISSUE THREAD

**Issue by ramkumarit2007** [helm/charts#9256]
When trying to add lifecycle poststart for the jenkins pod which is created from jenkins chart, that is not working since the template does not have provision to add lifecycle.

Feature Request: 

**Version of Helm and Kubernetes**:
HELM:
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

K8S:

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
Jenkins

**What happened**:
Not able to do PostStart after the container is created. 

**What you expected to happen**:
I want to do some post container creating tasks using lifecycle.

**How to reproduce it** (as minimally and precisely as possible):
Just try to add a lifecycle PostStart in the jenkins Master section, that won't execute as the template does not have that.

**Comment by DGreenstein** [comment]
+1

**Comment by maorfr** [comment]
Hey @ramkumarit2007,

Thanks for bringing this up!
Would you like to get involved and create a PR to handle this issue?
