### ISSUE TITLE
[stable/rabbitmq] Add initContainer for downloading additional plugins

### ISSUE THREAD

**Issue by codemasterover9000** [helm/charts#9267]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

I would like to install additional plugins such as `rabbitmq_delayed_message_exchange`. This does not seem possible at this time. 

One solution I can think of is to have an initContainer that downloads the plugins. Maybe even just have an `initContainers` section in `values.yaml` that gets directly injected into the template using `toYaml`  so that this can be done through configuration at release.

**Comment by juan131** [comment]
In the past we talked about adding an env. variable to the image that allows you to list the plugins to install during the initialisation. See https://github.com/bitnami/bitnami-docker-rabbitmq/issues/73


What do you think about a solution like that?

**Comment by codemasterover9000** [comment]
Sounds good

**Comment by juan131** [comment]
Great @codemasterover9000 !!!

I'll continue the discussion on the original GitHub issue to see if we can include a task to work on that soon.

**Comment by juan131** [comment]
By the way, the chart already implements this solution using a custom configuration file:

See: 

- https://github.com/helm/charts/blob/master/stable/rabbitmq/values.yaml#L69-L71
- https://github.com/helm/charts/blob/master/stable/rabbitmq/templates/configuration.yaml#L12

**Comment by codemasterover9000** [comment]
Yes that enables/activates the plugins in RabbitMQ. The plugin binary must still be available though :)

**Comment by juan131** [comment]
You're right! I created a task to implement the solution in the image so it's downloaded/installed during the initialisation of the image.

**Comment by lbornov2** [comment]
Please include this as a core feature.

**Comment by LaEmma** [comment]
Please include this as a core feature. Thanks

**Comment by juan131** [comment]
We're working on a major refactor of RabbitMQ container. Hopefully we'll be able to address this request once we complete refactoring the container.

**Comment by nitrag** [comment]
5 month bump? Need plugin to be installed on init please.

**Comment by codemasterover9000** [comment]
tip: there also is a stable/rabbitmq-ha chart that does support extra volume configuration and thus the installation of additional plugins.
