### ISSUE TITLE
[incubator/gogs] Need to add administrator name/ password

### ISSUE THREAD

**Issue by obeyler** [helm/charts#9278]
## FEATURE REQUEST:
we deploy automatically Gogs as a service we need to be able to specify during install process an admin.
Note that I know that the first user declared is considered as an administrator (Id=1) but we remove remove the capability to selfregister so nobody can't be registered.

The INSTALL_LOCK = true fixed by default in helm chart make the curl to /install impossible.

We need either new parameter gogs.admin.name="admin" gogs.admin.password="XX"
who populate the base with admin
or a new parameter to unlock the install path
and a way to lock it after have done the curl POST creation of administrator account. 

@tvon @responsible @kevinschumacher @fuhbar @cheyang 
## relative issues
see [incubator/gogs] serviceDisableRegistration: false and user creation #6942

**Comment by abdennour** [comment]
@stale Thank you! but the feature is requested and not implemented
