### ISSUE TITLE
[stable/cluster-autoscaler] Extra argument valuess don't get added when the value is set to false, resulting in the flag being set to true

### ISSUE THREAD

**Issue by trobert2** [helm/charts#9280]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
any

**Which chart**:
cluster-autoscaler

**What happened**:
When passing in flags as extraArgs with the value set to `false`, they are not added.

**What you expected to happen**:
If I do this in the value files:
```yaml
extraArgs:
  skip-nodes-with-local-storage: false
```
It results in this in the deployment manifest which is the opposite of what the desired state is:
```
--skip-nodes-with-local-storage
```
I expect:
It results in this in the deployment manifest:
```
--skip-nodes-with-local-storage=false
```

**How to reproduce it** (as minimally and precisely as possible):
start a deployment with 
```yaml
extraArgs:
  skip-nodes-with-local-storage: false
```

**Comment by marcopaga** [comment]
The PR is still open.
