### ISSUE TITLE
[stable/jaeger-operator] Allow creating jaegers in any namespace

### ISSUE THREAD

**Issue by mihau** [helm/charts#9298]
FEATURE REQUEST:
Allow creating jaeger instances in any namespace using the jaeger-operator

Currently jaeger-operator refers to `metadata.namespace` while setting the `WATCH_NAMESPACE` variable. This implies creating jaeger instances only in the same namespace as the operator. Another limiting factor that would have to change is the usage of a `Role` instead of `ClusterRole`.

My question is - is this behaviour intentional and what is the reasoning behind it? 

I'm happy to provide necessary changes to fulfil this request. The way I would approach is by allowing to choose between a clusterwide and namespaced deployment. First would allow the operator to watch all namespaces and create a `ClusterRole` for it to be able to create the necessary resources, while the latter would require a list of namespaces and create a `Role` for each. The list could by default contain only `metadata.namespace` if backwards compatibility is desirable.

**Comment by cpanato** [comment]
@mihau no reason. I will work on that to make it available to any namespace

**Comment by mihau** [comment]
@cpanato I can fix that in the evening, my goal with this issue was to see if there isn't any specific usecase for how it's working right now. Also what is your stance on backwards compatibility here ? I'd prefer to break it and make the operator clusterwide by default.

**Comment by cpanato** [comment]
@mihau no reason. go for it

just make sure to document if there is a breaking change

**Comment by mihau** [comment]
@cpanato let me know your thoughts on the PR.
