### ISSUE TITLE
How to read and write kafka from outside using helm chart

### ISSUE THREAD

**Issue by sukanta1980** [helm/charts#9310]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm Version
Client: &version.Version{SemVer:"v2.10.0-rc.3", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Kubernetes Version
[root@nqa-ops-k8s-master-2-1c 10.0.12.208:~]  kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
https://github.com/helm/charts/tree/master/incubator/kafka

**What happened**:
We have launched kafka cluster using this chart , below is the pod information

[root@qa4-ops-new-k8s-master-2-1b 10.11.92.174:/mnt1/sukanta_works/spr-helm-charts/charts] kubectl get pods -n kafka -o wide
NAME                    READY   STATUS    RESTARTS   AGE   IP              NODE                                          NOMINATED NODE
spr-kafka-0             1/1     Running   1          1d    192.168.1.79    ip-10-11-87-46.ap-south-1.compute.internal    <none>
spr-kafka-1             1/1     Running   1          2h    192.168.13.13   ip-10-11-129-9.ap-south-1.compute.internal    <none>
spr-kafka-2             1/1     Running   1          1d    192.168.1.80    ip-10-11-87-46.ap-south-1.compute.internal    <none>

spr-kafka-zookeeper-0   1/1     Running   0          2h    192.168.13.14   ip-10-11-129-9.ap-south-1.compute.internal    <none>
spr-kafka-zookeeper-1   1/1     Running   0          1d    192.168.1.81    ip-10-11-87-46.ap-south-1.compute.internal    <none>
spr-kafka-zookeeper-2   1/1     Running   0          2h    192.168.12.14   ip-10-11-89-254.ap-south-1.compute.internal   <none>

[root@qa4-ops-new-k8s-master-2-1b 10.11.92.174:/mnt1/sukanta_works/spr-helm-charts/charts] kubectl get svc -n kafka -o wide
NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE   SELECTOR
spr-kafka              NodePort    10.106.57.194    <none>        9092:30043/TCP   1d    app=kafka,release=spr-kafka
spr-kafka-0-external   NodePort    10.100.110.153   <none>        9092:31408/TCP   1d    app=kafka,pod=spr-kafka-0,release=spr-kafka
spr-kafka-1-external   NodePort    10.100.251.235   <none>        9092:32238/TCP   1d    app=kafka,pod=spr-kafka-1,release=spr-kafka
spr-kafka-2-external   NodePort    10.102.9.176     <none>        9092:32515/TCP   1d    app=kafka,pod=spr-kafka-2,release=spr-kafka
spr-kafka-headless     ClusterIP   None             <none>        9092/TCP         1d    app=kafka,release=spr-kafka
spr-kafka-zookeeper    NodePort    10.102.27.175    <none>        2181:32171/TCP   1d    app=zookeeper,release=spr-kafka

We can able to create topic from out side

[root@qa4-core-kafka-1-1b 10.11.86.19:/mnt1/kafka/bin] ./kafka-topics.sh --zookeeper ip-10-11-87-46.ap-south-1.compute.internal:32171 --topic spr --create --partitions 2 --replication-factor 3

Created topic "spr".

We can able to list or describe topic from out side

[root@qa4-core-kafka-1-1b 10.11.86.19:/mnt1/kafka/bin] ./kafka-topics.sh --zookeeper ip-10-11-87-46.ap-south-1.compute.internal:32171 --list
__confluent.support.metrics
__consumer_offsets
spr
test1

When trying to write something getting this error

[root@qa4-core-kafka-1-1b 10.11.86.19:/mnt1/kafka/bin] ./kafka-console-producer.sh --broker-list ip-10-11-87-46.ap-south-1.compute.internal:31408,ip-10-11-129-9.ap-south-1.compute.internal:32238 --topic spr
hi
[2018-11-16 08:19:27,907] ERROR Error when sending message to topic spr with key: null, value: 2 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for spr-0: 1508 ms has passed since batch creation plus linger time

To listen using this command

root@spr-kafka-0:/# kafka-console-consumer --bootstrap-server spr-kafka:9092 --topic spr --from-beginning

**What you expected to happen**:

Expecting to read and write to kafka from outside 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by sukanta1980** [comment]
Can some one help me on this

**Comment by cablespaghetti** [comment]
I've just got this working. The step missing in the documentation is to update the "listeners" configuration property. Here's my config:
```
  "advertised.listeners": |-
    EXTERNAL://{{ .Environment.Name }}-kafka.internal.mydomain.com:$((31090 + ${KAFKA_BROKER_ID}))
  "listener.security.protocol.map": |-
    PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
  "listeners": "PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092"
external:
  enabled: true
  domain: internal.mydomain.com
```

**Comment by cablespaghetti** [comment]
Duplicate of #9062
