### ISSUE TITLE
helm makes no sense

### ISSUE THREAD

**Issue by mabushey** [helm/charts#9334]
Bug report

`git clone https://github.com/helm/charts.git` - I find it really stupid that you can render & install a template from the `cloud` with `helm install`, but if you want only the rendered template (`helm template`) you have to clone it locally. They should both work one way or the other. Consistency is wonderful.

`helm template -f my-wordpress/values.yaml charts/stable/wordpress`
Error: found in requirements.yaml, but missing in charts/ directory: mariadb

`helm install --namespace wordpress --name my -f ./my-wordpress/values.yaml  stable/wordpress` works (well it brings up broken containers anyway). Am I totally missing something or is helm just braindead?

It seems like helm wants to punish you for wanting to see what it's actually doing.

**Comment by monotek** [comment]
1.) this is the charts repo so complaints about the helm binyry makes no sense
2.) rtfm - you have to do a "helm dependency build" first to get the subcharts
3.) likely a misconfiguration.
