### ISSUE TITLE
[stable/elasticsearch]: Not worked with elasticsearch version 5.4 5.2.2 5.6.13 etc.

### ISSUE THREAD

**Issue by zh168654** [helm/charts#9343]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm: v2.11.0
kubernetes: v1.11.1

**Which chart**:
stable/elasticsearch

**What happened**:
except for appVersion and image, everything else is exactly the same.Then 6.4.2 works well, but 5.2.2/5.4/5.6.13 didn't work!

**What you expected to happen**:
work well

**How to reproduce it** (as minimally and precisely as possible):
values.yaml diff with different versions just like:
-appVersion: "6.4.2"
+appVersion: "5.4"

-repository: "docker.elastic.co/elasticsearch/elasticsearch-oss"
-tag: "6.4.2"
+repository: "docker.elastic.co/elasticsearch/elasticsearch"
+tag: "5.4"

**Comment by monotek** [comment]
whats the error?

**Comment by zh168654** [comment]
> whats the error?

thanks,

kubectl get pods:
es-test-elasticsearch-client-5489cfcb56-2wc4z      0/1       Running            1          3m
es-test-elasticsearch-client-5489cfcb56-l482d      0/1       Running            1          3m
es-test-elasticsearch-data-0                       0/1       Running            0          3m
es-test-elasticsearch-master-0                     0/1       Running            0          3m

kubectl describe pods es-test-elasticsearch-master-0:
Warning  Unhealthy               55s (x8 over 2m)  kubelet, k8s-master-01  Readiness probe failed: HTTP probe failed with statuscode: 401

kubectl logs es-test-elasticsearch-master-0:
failed to resolve host [es-test-elasticsearch-discovery]

**Comment by monotek** [comment]
ah, i think the discovery mechanism changed at the jump to 6.x.
i guess es 5.x is just not compatible anymore.

**Comment by hustshawn** [comment]
@zh168654 Hi, I customized the chart config if just modify the image repo and tag to 5.x, but keep the default `appVersion`, and it just works fine in my case.

**Comment by zh168654** [comment]
> @zh168654 Hi, I customized the chart config if just modify the image repo and tag to 5.x, but keep the default `appVersion`, and it just works fine in my case.
> My `values.yml` looks like
> 
> ```
> appVersion: "6.4.3"
> ...
> image:
>   repository: "my-registry/elasticsearch"
>   tag: "5.6.9"
> ```

I wonder if you have used the official image and enabled RBAC in apiserver. I don't know which config I got wrong.
Besides, just now I tried using the elder commit (id: 5635a5112df2b1f0e304b96024916849700ad405) and image version 5.4, and all worked well.

**Comment by anapsix** [comment]
Has some issues with version 5.6.14, resolution described in https://github.com/helm/charts/issues/9243#issuecomment-446671096

**Comment by manojtr** [comment]
> @zh168654 Hi, I customized the chart config if just modify the image repo and tag to 5.x, but keep the default `appVersion`, and it just works fine in my case.
> My `values.yml` looks like
> 
> ```
> appVersion: "6.4.3"
> ...
> image:
>   repository: "my-registry/elasticsearch"
>   tag: "5.6.9"
> ```

this didn't work for me :(
