### ISSUE TITLE
[stable/postgresql] Different affinities for master & slaves

### ISSUE THREAD

**Issue by ronaldgrn** [helm/charts#9349]
FEATURE REQUEST:

Can we have the option to set different affinities for the master vs slaves?

similiar to how redis does it https://github.com/helm/charts/tree/master/stable/redis

```
master.affinity []  
slave.affinity []
```

**Comment by tompizmor** [comment]
@ronaldgrn I just sent a PR implementing this improvement. Take a look if you want https://github.com/helm/charts/pull/9646

**Comment by ronaldgrn** [comment]
Excellent! It's exactly what I needed
