### ISSUE TITLE
[stable/prestashop] missing ingress template

### ISSUE THREAD

**Issue by Nittarab** [helm/charts#9359]
**Is this a request for help?**:
No, this is feature request, in the prestashop chart there isn't an ingress 
---

**FEATURE REQUEST** :

  - Add ingress template in the prestashop chart

**Which chart**:
 stable/prestashop

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. Check https://github.com/helm/charts/pull/9801

**Comment by juan131** [comment]
Hi @Nittarab 

I created a different PR to fix the same issue using a different approach. See https://github.com/helm/charts/pull/10335
