### ISSUE TITLE
Elasticsearch rollingUpdate

### ISSUE THREAD

**Issue by DaveWHarvey** [helm/charts#9389]
**Is this a request for help?**:
I've installed the elasticSearch chart, and I'm trying to understand the updateStrategy, which is OnDelete in the values.yaml file.    The ReadMe file does not describe anything about this or the hooks implementation.        My current understanding is that with the default settings, if I change the image (in our case we would have changed a custom plugin), and "helm upgrade", that nothing will happen, and I would have to manually delete each pod in turn, but if I set the updateStrategy to RollingUpdate then everything will work automatically, evacuating the data from the node being removed. especially if I increase the number of replicas at the start.

As I try this procedure, I would be willing to improve the README file to describe how to use this feature, but first I would appreciate any feedback on what the expected behavior is, and why RollingUpdate is not the default or at least mentioned in a comment around updateStrategy.  

**Version of Helm and Kubernetes**:
Helm v.2.11.0
K8s: Client v1.12.0, Server v1.10.3-eks

**Which chart**:
Elasticsearch 1.14

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by dannyjeck** [comment]
Would love to know the results of this.

**Comment by DaveWHarvey** [comment]
RollingUpdate worked for me on 6.5 and 1.11 but there might be issues with earlier ES or K8s versions.
I did have to increase the pod termination timeout to allow evacuation.

I did rewrite the shutdown/startup hooks in python because I added a statefulset per AZ for data nodes.   To handler the lack of atomicity/locking in the list of excluded nodes,   a node can only add or remove itself from the list, but if it wants to be excluded, it has to poll to ensure that it has remained on the exclusion list, and retry.      I hit a bug in 1.11.5 where a startfulSet pod that is restarted on the same node may hang on startup, but I could just delete the pod.      With a long termination timeout, there needed to be some tricks applied to the preshutdown hook to get it to exit when it was not going to evacuate anything but not exit on data nodes if the master nodes were upgrading.

For master nodes, I mounted a script and overrode container entry with this to get master failover not to take forever.   If you shutdown ES on hardware, the hardware stays up and refuses connections to the port, but pods can exit instantly.

if [[ -z $NODE_MASTER  || "$NODE_MASTER" = "true" ]] ; then
    
    
    # Run ES as a background task, and forward SIGTERM to it, then wait for it to exit
    trap 'kill $(jobs -p)' SIGTERM
    
    /usr/local/bin/docker-entrypoint.sh elasticsearch &
    
    wait
    
    # now keep the pod alive for 30s after ES dies so that we will refuse connections from
    # the new master rather than needing to time  out
    sleep 30
else
    
    exec /usr/local/bin/docker-entrypoint.sh elasticsearch
fi
