### ISSUE TITLE
[stable/keycloak] Cannot have keycloak+postgres as dependency chart

### ISSUE THREAD

**Issue by ariep** [helm/charts#9407]
**Is this a request for help?**: yes
---
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Version of Helm and Kubernetes**: helm 2.11, kubernetes 1.11.3

**Which chart**: stable/keycloak

**What happened**: I tried to create a chart (called "keycloak-oas") that has keycloak as a dependency chart, with `deployPostgres: true`. When trying to `helm install` that new chart, I get the following error:
```
Error: render error in "keycloak-oas/charts/keycloak/templates/statefulset.yaml": template: keycloak-oas/charts/keycloak/templates/_helpers.tpl:39:12: executing "keycloak.postgresql.fullname" at <{{template "postgres...>: template "postgresql.fullname" not defined
```

**What you expected to happen**: My new chart installs correctly, with keycloak as a subchart, and postgres as a subsubchart.

**How to reproduce it** (as minimally and precisely as possible): Create a fresh chart, without any templates, with just stable/keycloak as a dependency. `helm install` this new chart with this as values file:
```
keycloak:
  keycloak:
    persistence:
      deployPostgres: true
```

**Comment by ariep** [comment]
@unguiculus hi, anything further I can do to diagnose this? Or do you know what the problem is?

**Comment by unguiculus** [comment]
I didn't have time to look into this so far. I wonder why you want to have Keycloak itself as a dependency. What's your use case?

**Comment by andrewhowdencom** [comment]
In my case, I store configuration for the charts in parent charts. For example, I would sub-chart this and then store the overridden variables in the parent charts `Values.yml`. In this way they can be checked into version control easily and with minimal tooling.

**Comment by clkao** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/886 is an attempt to create a meta chart that depends on jupyterhub and keycloak, which runs into this issue.

As named templates are global, it seems the issue might be not loading deeply depended helper (in this case charts/keycloak/charts/postgresql)

(This is helm v2.12.1)

**Comment by clkao** [comment]
https://github.com/helm/helm/issues/4490 appears to be what's causing it - requirements condition evaluation context.

as suggested in the issue comments, having additional top-level keycloak entry to make the dependency evaluation should work, but it doesn't:

```
keycloak:
  persistence:
    deployPostgres: true

keycloak:
  keycloak:
    persistence:
      deployPostgres: true
```

**Comment by ariep** [comment]
> I wonder why you want to have Keycloak itself as a dependency. What's your use case?

I'd like to add some content to Keycloak (at least a realm, later probably also some roles/groups/etc.) as part of the helm install. I wanted to do that by creating a "wrapper chart" that depends on the keycloak chart, and additionally contains some templates for configmaps/secrets/jobs. I have done something similar succesfully for other applications.

Anyway, I'd say there could be many reasons to have any given chart as a dependency.

**Comment by andrewhowdencom** [comment]
Yo stalebot can you reopen plz

**Comment by daur88** [comment]
Any news on the issue? Any workarounds?

**Comment by sboardwell** [comment]
@daur88 , I ended up deploying our custom configmaps/secrets as a separate chart in the same namespace. Then installing keycloak on it's own whilst being able to reference the configmaps installed in the other release.

Seems to work well enough, if not perfect.
