### ISSUE TITLE
[stable/gocd] typo in values: agent.env.agentAutoRegisterEnvironemnts

### ISSUE THREAD

**Issue by matthias-k** [helm/charts#9420]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
helm: 2.11.0, kubernetes 1.12.2

**Which chart**:
stable/gocd

**What happened**:
The value for setting enviroments for agents is named `agent.env.agentAutoRegisterEnvironemnts`, which seems to be a typo

**What you expected to happen**:
I would expect the value to be named `agent.env.agentAutoRegisterEnvironments`

**How to reproduce it** (as minimally and precisely as possible):
install the chart with this values file:
```
agent:
  env:
    agentAutoRegisterEnvironments: test 
```
the created agends won't have a environment set

**Anything else we need to know**:
Fixing this should be trivial and I have already fixed it in my fork, but technically fixing the typo would break backwarts-compatibility and I don't know how you want to handle this.

**Comment by matthias-k** [comment]
@arvindsv @bdpiparva I forgot to tag you on this issue, so it likely didn't get your attention and got closed in the meantime. I still think this is a bug that could be fixed easily (and as I pointed out, I have a bugfix ready).

**Comment by arvindsv** [comment]
@matthias-k Good point. I think it's best to handle backwards compatibility around [here](https://github.com/helm/charts/blob/d8aa6b5109f8912af89aa039ce867714e73e6878/stable/gocd/templates/gocd-agent-deployment.yaml#L72-L75), by adding an else clause. But, fixing it everywhere, so that the documentation, etc. points to the right value.

/cc @varshavaradarajan @GaneshSPatil

**Comment by varshavaradarajan** [comment]
@arvindsv - yeah, that would work. Where do we announce deprecation of the typo? So that we can get rid of it in a future release? In the changelog?

**Comment by arvindsv** [comment]
@varshavaradarajan I'd assume so. We have no other means. We could also have a set of releases, where deployment (of the server through helm) will fail if it is set. :)

We could also show a warning message in the output of `helm status`.
