### ISSUE TITLE
Question about resizing persistent volume

### ISSUE THREAD

**Issue by minotaurrr** [helm/charts#9431]
Hi all,  this is more of a question than a bug report or feature request.

I've deployed a replica set using the yaml file provided under the production deployment section of this chart.

Is it possible to increase the volume size of the existing replica set? 

If so, do I have to manually increase the size of the block storage first at the cloud level? Or will k8s handle that for me?

**Comment by Towmeykaw** [comment]
It depends on what storage you are using. This blogpost has some good info. https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/

**Comment by minotaurrr** [comment]
@Towmeykaw might be a stupid question but is there a way to save the data while deleting/recreating pods for resizing? I thought the data lived in the block storage which i can attach to k8s

Just not sure how I would configure the yaml file to do that when I recreate

**Comment by Towmeykaw** [comment]
Im not sure about exactly how DO handles it but according to https://www.digitalocean.com/docs/kubernetes/how-to/add-persistent-storage/ it seems like it should be enough to resize the underlying storage and keep the PVC as it is.
