### ISSUE TITLE
sumologic-fluentd Temporary failure in name resolution (collectors.au.sumologic.com:443)

### ISSUE THREAD

**Issue by evanwoo** [helm/charts#9432]
**Is this a request for help?**: Yes...I am new to Kubernetes/Rancher

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT/Help

**Version of Helm and Kubernetes**: v2.11.0 and v1.11.3-rancher1-1

**Which chart**: sumologic-fluentd

**What happened**: I am using Rancher 2.1.1 on AWS, have created a Kubernetes cluster with multiple worker nodes using Amazon EC2 as nodes. I used the Catalog Apps to install the "sumologic-fluentd" app, passing in a variable named "sumologic.collectorUrl" with the value of my sumologic HTTP source URL.
The "sumologic-fluentd" app got installed fine, and under my cluster's workload I can see a sumologic-fluentd pod running in each of the worker nodes.
After some application testing, I found that logs from only one worker node are being sent to Sumo. When I checked the sumologic-fluentd pod logs, I found the following errors from all but one pod:

2018-11-20 23:49:37 +0000 [warn]: #0 failed to flush the buffer. retry_time=16 next_retry_seconds=2018-11-20 23:49:17 +0000 chunk="57b113cccf18d124339281e00f47d1da" error_class=SocketError error="getaddrinfo: Temporary failure in name resolution (collectors.au.sumologic.com:443)"

It appears that at anyone time, only one fluentd plugin can send logs to Sumo, all other pods/nodes all show the above error.

**What you expected to happen**: logs from all pods running on all worker nodes are sent to Sumo.

**How to reproduce it** (as minimally and precisely as possible): as per above.

**Anything else we need to know**: I have tried this "sumologic-fluentd" plugin on EKS and kops managed Kubernetes cluster (multiple worker nodes) and I don't have this problem there...so maybe its a Rancher config issue? Appreciate any help/guidance thank you.

**Comment by frankreno** [comment]
@evanwoo for the best response here, I would suggest you open a ticket thru the Sumo Logic support team so they can debug this thru your account on the backend.

**Comment by kb18951452** [comment]
@evanwoo Were you able to resolve this?
I am running into the same error, and I'd like to get a fix in place.
