### ISSUE TITLE
[stable/prometheus] prometheus node-exporter scrapes wrong disk usage metrics

### ISSUE THREAD

**Issue by jeremyxu2010** [helm/charts#9452]
**Is this a request for help?**:
no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:

**Which chart**:
stable/prometheus

**What happened**:
install chart stable/prometheus with default settings, the node-exporter scraps wrong disk usage metrics.

**What you expected to happen**:
the node-exporter scraps correct disk usage metrics.

**How to reproduce it** (as minimally and precisely as possible):
1. install stable/prometheus is k8s cluster:

```bash
helm install stable/prometheus
```

2. check node_filesystem_size_bytes metrics

```bash
curl http://${any_k8s_node_ip}:9100/metrics|grep 'node_filesystem_size_bytes'
```

and will find the wrong values.

**Anything else we need to know**:
[node_exporter](https://github.com/prometheus/node_exporter) suggested mount host's / to docker container's /host mount point if node_exporter is running in docker, see [here](https://github.com/prometheus/node_exporter#using-docker)

**Comment by monotek** [comment]
Imho this should be a bug agains node exporter repo instead of the helm chart.
