### ISSUE TITLE
[stable/grafana] Login issue after enabling PV

### ISSUE THREAD

**Issue by rishiraaz** [helm/charts#9472]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**:
Kubernetes v0.9.10
Helm v2.9.1

**Which chart**:
stable/grafana

**What happened**:
After I enabled Persistent volume for grafana chart and installed the chart, I was able to login to the grafana console. I did an upgrade on the same chart, got the password for admin user but was not able to login using the new password. I then tried with the old password, which worked. 

**What you expected to happen**:
The new password should get updated in the database in PV, each time a new pod is setup.

**How to reproduce it** (as minimally and precisely as possible):
Install the chart, after enabled PV
Generate the password for admin user and login.
Do an upgrade or delete the pod so that a new one get created
Generate the password for admin user and login, you wont be able to. use the password which was generated initially and try to login, you should be able to login

**Anything else we need to know**:

**Comment by mauritsvdvijgh** [comment]
Experiencing this same issue in the way you described it.
Makes sense seeing as the secret keys "admin-password" and "admin-user" of the "grafana" secret are not used anywhere.

**Comment by rishiraaz** [comment]
That is something we dont want to as it will lead to resetting password every time the pod changes. Something more permanent should be good.

**Comment by tjohnston-cd** [comment]
It would be really good if this was fixed (to match the desired behaviour described in the OP).

Most search results about the grafana admin password don't mention `grafana-cli` either. @mauritsvdvijgh 's solution definitely works, so thanks for that!

**Comment by rishiraaz** [comment]
It would be really good if this was fixed (to match the desired behaviour described in the OP).

**Comment by infa-kparida** [comment]
@rishiraaz  Did you get any workaround for this issue ?
