### ISSUE TITLE
stable/prometheus-node-exporter exposes metrics to everyone

### ISSUE THREAD

**Issue by ensonic** [helm/charts#9474]
BUG REPORT

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.11", GitCommit:"dc4f6dda6a08aae2108d7a7fdc2a44fa23900f4c", GitTreeState:"clean", BuildDate:"2018-11-10T20:22:02Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/prometheus-node-exporter

**What happened**:
`stable/prometheus-node-exporter/templates/daemonset.yaml` uses `--web.listen-address=0.0.0.0:{{ .Values.service.port }}`, since the config is also using `hostNetwork: true` this will make it externally accessible. This is confusing since the choise of the service-type with ClusterIP as a default would hint otherwise.

**What you expected to happen**:
I'd like to expose it only to the prometheus scraper running in the same cluster.

**How to reproduce it** (as minimally and precisely as possible):
Install the helm chart and check open ports (`sudo netstat -lntup`). I don't want to see the node_exporter showing up there.

**Comment by ensonic** [comment]
The issue has not been fixed, not is there any comment from the developers. The issue was introduced in the initial commit
https://github.com/helm/charts/commit/fb65df5bd017e9cc647ff5b9a313033553707127 by @gianrubio

**Comment by ensonic** [comment]
some 'further activity' to unstalify

**Comment by ensonic** [comment]
There were no updates. Warning to people, these charts are unmaintained. We'll go an look for alternatives.

**Comment by ensonic** [comment]
Still not fixed

**Comment by gianrubio** [comment]
@ensonic feel free to send a PR to fix this issue
