### ISSUE TITLE
[stable/redis-ha] server-0 failure can result in split-brain

### ISSUE THREAD

**Issue by aianus** [helm/charts#9488]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

Helm version:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.18", GitCommit:"5796233393d7bc034428de15191ad3d2eaff95fb", GitTreeState:"clean", BuildDate:"2018-11-08T20:49:08Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
redis-ha

**What happened**:
A single node failure (out of 3) resulted in a redis outage due to bad logic in redis-ha chart.

1) Server 0 crashed / had a network partition with the other nodes
2) Server 0 rebooted
3) Server 0 could not reach the other nodes while it was starting up so it decided it was the master (https://github.com/helm/charts/blob/master/stable/redis-ha/templates/redis-ha-configmap.yaml#L57)
4) Server 0 thinks it's master indefinitely and is waiting for other nodes to connect to it; it cannot learn about the other nodes at this point because it thought it was the first to start up and is just waiting for others to connect to it
5) Servers 1 and 2 marked server 0 as down and correctly failed over and are both in agreement about the new master (Server 1)
6) Our Rails pods never learn about the failover because they are configured to ask the Sentinel on Server 0 who the master is first; since Sentinel on Server 0 keeps replying successfully that it is the master, the Rails pods never bother to ask Sentinel 1 or Sentinel 2
7) Rails tries to write to Server 0
8) Writes fail because Server 0 has no slaves to replicate to and rejects the write
9) System was stuck in this state indefinitely until we manually rebooted Server 0 and it initialized itself correctly as a slave

**What you expected to happen**:
I expected Server 0 not to believe that it is the master indefinitely when it isn't connected to any of the other nodes. I expected Sentinel on Server 0 to report that it doesn't know who the master is and to eventually report the correct master.

**How to reproduce it** (as minimally and precisely as possible):
1. Cut off network connectivity from the node that hosts the server-0 pod to the nodes hosting server-1 and server-2.
1. Restart the server-0 pod.
1. Restore network connectivity

server-1 or server-2 will be the new master but the sentinel on server-0 is reporting that server-0 is the master and that it is up.

**Anything else we need to know**:

Two possible solutions off the top of my head:

1)  Have a helm config value to indicate a new cluster vs. an existing cluster so that a redis-ha statefulset pod rebooting in an existing cluster will never initialize itself as the master

2) Have a liveness check that eventually kills (and restarts) a statefulset pod that doesn't know about {quorum - 1}  other pods.

**Comment by ssalaues** [comment]
@aianus What chart version are you using?

Regardless, I can easily see how this can happen. I think your first solution would work fine for this specific issue but I worry it might open up other edge cases where manually initializing a master would be necessary. I'll try it out and see how it goes. 

Honestly the livenesss check would be a good as well. I've been trying to think of a way to improve the checks since they are very basic as is.

**Comment by aianus** [comment]
I'm on 3.0.0

**Comment by ssalaues** [comment]
@aianus The above issues aside, going back over your description, it seems like you may want to switch your Rails pods to point to all the sentinels:
> Our Rails pods never learn about the failover because they are configured to ask the Sentinel on Server 0 who the master is first; since Sentinel on Server 0 keeps replying successfully that it is the master, the Rails pods never bother to ask Sentinel 1 or Sentinel 2

You really shouldn't rely on any one Sentinel because even with no chart bugs, a single sentinel pod can go down/restart/update/etc shouldn't be the single point of failure for your app.  If you pass in all the sentinels the library you're using should simply attempt to contact in the case of a down Sentinel. Once this issue is fixed you could also simply point to the redis-ha service name and will pass through to an available endpoint.

**Comment by aianus** [comment]
> However it seems like it prevents the pods from starting back up after shutting down and restarting all nodes.

Yes, but I think manual intervention in the case where you lose quorum is an acceptable limitation. Other distributed HA stores exhibit this limitation too (consul, etc.).

> it seems like you may want to switch your Rails pods to point to all the sentinels:

Our Rails pods are pointed at all the sentinels.

However, the way the ruby client for redis is written, it will ask the sentinels one-by-one who the master is and stop once a single sentinel replies that it knows who the master is.

In the outage I described, sentinel 0 was asked first and replied successfully (albeit incorrectly) that it was the master. Therefore the Rails pods did not continue to iterate through the rest of the sentinels.

This matches the algorithm described in the official redis sentinel client guidelines: https://redis.io/topics/sentinel-clients

**Comment by ssalaues** [comment]
>Yes, but I think manual intervention in the case where you lose quorum is an acceptable limitation. Other distributed HA stores exhibit this limitation too (consul, etc.).

I agree. Updating the probe seems to work out the best as it leaves the partitioned master in a `CrashLoopBackoff` until the pod is deleted/recreated.

>Our Rails pods are pointed at all the sentinels.

Ahh my bad, I misunderstood the description then.

Another option (in addition to the probe) could be to setup the init script as the entry point script. This way when the probe fails and the container is restarted, the pod could attempt to find the other sentinels. Any thoughts on this @aianus ?

**Comment by aianus** [comment]
> Another option (in addition to the probe) could be to setup the init script as the entry point script.

I'm worried that if you make it part of the entry point script instead, it could cause bugs where the sentinel container thinks it's in one cluster and the redis container thinks it's in another.

I think config value for existing vs. new cluster plus a liveness check is sufficient.

The liveness check alone sort of works, but it can cause bouts of downtime between server-0 booting and then getting terminated a little while later when it realizes nobody is connecting to it. In that in-between time it would still be advertising itself as the live master.

We already have alerting and monitoring for pods being down so I'm totally fine with manually intervening (in the morning!) if a pod goes down but the service stays up.

Let me know what you think, @ssalaues

**Comment by ssalaues** [comment]
>I'm worried that if you make it part of the entry point script instead, it could cause bugs where the sentinel container thinks it's in one cluster and the redis container thinks it's in another.

Yeah I think you're right. 

>I think config value for existing vs. new cluster plus a liveness check is sufficient.

So I'm not 100% clear on the config value. Are you suggesting this should be like a value.yml option to disable/enable the init process?

**Comment by ssalaues** [comment]
Hmm ok I'll try something like this out and open a PR.

**Comment by ssalaues** [comment]
Bump to leave the discussion open until at least the PR is resolved.
