### ISSUE TITLE
Postgresql multiple/additional database using helm

### ISSUE THREAD

**Issue by e-jjj** [helm/charts#9493]
**Is this a request for help?**:

---feature request

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

 Need to have two databases instances running under the same postgresql pod.
For instance. Creating using helm 
helm upgrade --install \
--set postgresql.postgresDatabase="POSTGRES_DB" \

Can I create an additional database by running the same command in an additional line?

helm upgrade --install \
--set postgresql.postgresDatabase="POSTGRES_DB" \
--set postgresql.postgresDatabase="POSTGRES_DB_Additional" \

**Version of Helm and Kubernetes**: Helm: 2.10.0, Kubernetes: 1.8.6

**Which chart**: stable/postgresql

**What happened**:
If I create an additional database,
helm upgrade --install \
--set postgresql.postgresDatabase="POSTGRES_DB" \
--set postgresql.postgresDatabase="POSTGRES_DB_Additional" \

It only creates one

**What you expected to happen**:
I would expect to have to database instances under the same postgresql pod (container)

**How to reproduce it** (as minimally and precisely as possible):
With the commands as indicated above

**Anything else we need to know**:

**Comment by tompizmor** [comment]
I am afraid that currently, the Postgres chart does not support to create multiple databases using just the command line. 
However, you could use custom init scripts to create all the databases you want during the first Postgres initialization. 
Check this section in the [README](https://github.com/helm/charts/tree/master/stable/postgresql#initialize-a-fresh-instance)
