### ISSUE TITLE
[stable/postgresql] postgresql.master.fullname ignores fullnameOverride

### ISSUE THREAD

**Issue by kivoli** [helm/charts#9510]
https://github.com/helm/charts/blob/master/stable/postgresql/templates/_helpers.tpl

**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Version of Helm and Kubernetes**:

```bash
# Helm
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
# kubernetes
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

`stable/postgresql`

**What happened**:

Updated from earlier chart version to 2.6.4. Suddenly the release name is again part of the PostgreSQL server’s pod name, ignoring the fullnameOverride — but only for the pod name.

**What you expected to happen**:

The override to be obeyed.

**How to reproduce it** (as minimally and precisely as possible):

```bash
cat >values.yaml <<EOF
fullnameOverride: pg
EOF

helm install -f values.yaml -n longname stable/postgresql
kubectl get pods
# Returns:
# longname-postgresql-0   0/1     Init:0/1   0          13s
# Expected:
# shortname-0   0/1     Init:0/1   0          13s
# Or, with replication:
# shortname-master-0   0/1     Init:0/1   0          13s
```

**Anything else we need to know**:

N/A

**Comment by tompizmor** [comment]
The fix for this issue was proposed at https://github.com/helm/charts/pull/9512 and finally implemented at https://github.com/helm/charts/pull/9646. I think this issue can be closed

**Comment by kivoli** [comment]
Yes.
