### ISSUE TITLE
[stable/grafana] Install plugins

### ISSUE THREAD

**Issue by kolesoffac** [helm/charts#9564]
How can i install plugins after _helm install_ of grafana?

Thanks

**Comment by jpdasma** [comment]
Try editing the plugins value in values.yaml (e.g.):
```yaml
plugins:
- digrich-bubblechart-panel
- grafana-clock-panel
```
Then do a `helm upgrade -f values.yaml <release-name> grafana`

**Comment by kolesoffac** [comment]
Freezing on install digrich-bubblechart-panel and not started pod.

**Comment by larsduelfer** [comment]
Hi all, we were able to add the plugin to the config for grafana an run a helm upgrade (this was done as part of the prometheus operator helm chart, since it includes the grafana chart). The config map is updated but the new config is not picked-up by the pod automatically. We had to manually delete the pod and the new one that was automatically created used the new config and installed the plugin. 

Is this intended to happen automatically?

**Comment by paskal** [comment]
Absence of automatic configuration reload is an issue, which is described in detail at https://github.com/helm/charts/issues/8798

**Comment by jaletelier** [comment]
> I am using persistent volumes and what i did is to upgrade my helm with adding a plugin:
> ...
> but it basically deleted all my configuration instead of adding a new plugin only. (although plugin was added)
> 
> so is there something we can do to keep current configuration AND installing a plugin after installing helm chart for grafana

For anyone still wondering how to add new plugins without `helm upgrade`. If you are using persistent volumes you can access the grafana server pod to run `grafana-cli plugins install <plugin-id>`.

- `kubectl exec -it grafana-pod-id -n grafana -- grafana-cli plugins install <plugin-id>`
- Finally, delete the pod to restart the server: `kubectl delete pod grafana-pod-id -n grafana`

**Comment by holms** [comment]
`Finally, delete the pod to restart the server: kubectl delete pod grafana-pod-id -n grafana`

@jaletelier what do you  by mean 'restart the server'?

**Comment by holms** [comment]
> > I am using persistent volumes and what i did is to upgrade my helm with adding a plugin:
> > ...
> > but it basically deleted all my configuration instead of adding a new plugin only. (although plugin was added)
> > so is there something we can do to keep current configuration AND installing a plugin after installing helm chart for grafana
> 
> For anyone still wondering how to add new plugins without `helm upgrade`. If you are using persistent volumes you can access the grafana server pod to run `grafana-cli plugins install <plugin-id>`.
> 
>     * `kubectl exec -it grafana-pod-id -n grafana -- grafana-cli plugins install <plugin-id>`
> 
>     * Finally, delete the pod to restart the server: `kubectl delete pod grafana-pod-id -n grafana`
In my pod grafana-cli is absent.

**Comment by dguyhasnoname** [comment]
@holms you need to mention the container name of grafana e.g. 

kubectl exec -it grafana-pod-id -n grafana -c <grafana_container_name>-- grafana-cli plugins install <plugin-id>
