### ISSUE TITLE
[stable/redis-ha] implement fullnameOverride option into _helpers.tpl

### ISSUE THREAD

**Issue by ugoviti** [helm/charts#9568]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Please add upstream the option to specify `fullnameOverride` , to override the fullname of the deploy as is already possibile in many other charts.

example add the following code into _helpers.tpl:

```
{{- define "redis-ha.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

**Version of Helm and Kubernetes**: Helm 2.11, Kubernetes 1.10

**Which chart**: redis-ha

Kind regards

**Comment by ssalaues** [comment]
@ugoviti This should be fixed now with #10032 merged
