### ISSUE TITLE
[stable/sonarqube] Configure context path for sonarqube

### ISSUE THREAD

**Issue by johnzielke** [helm/charts#9577]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

I would like to deploy my sonarqube instance not on the root of the domain, but on a context-path such as "example.com/sonarqube". For this, I would need an option in the values file that I can pass the context path (by default "/"). This option would need to set the __sonar.web.context__ property in the sonar.properties file and configure the respective ingresses and readiness-probes

**Comment by vigohe** [comment]
@johnzielke this is already supported. But by using command `-Dsonar.web.context=/sonarqube`

set a vaules.yaml

```yaml
command: [ "-Dsonar.web.context=/sonarqube" ]
```

[info](https://github.com/SonarSource/docker-sonarqube/issues/17)

**Comment by sbabutk** [comment]
@vigohe What is the status of this feature?  I was able to setup the webcontext using extraEnv variable but readiness-probe is failing.
