### ISSUE TITLE
[stable/nginx-ingress] Upgrade chart to support features of v0.21.0

### ISSUE THREAD

**Issue by logicfox** [helm/charts#9580]
Upgrade to Nginx Ingress v0.21.0 support CVE fixes and many new features. See https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md

**Comment by floriantraber** [comment]
What features are you looking for that are missing?

**Comment by nhoughto** [comment]
Make default backend optional, more of a v0.20 feature tho..
same as https://github.com/helm/charts/issues/9257

**Comment by pinnymz** [comment]
I'm interested in this as well for geoip2 support.

**Comment by else** [comment]
I'm interested in this for TLS1.3 support.

**Comment by else** [comment]
Still relevant.

**Comment by pinnymz** [comment]
@else, hasn't this already been addressed? Master changelog shows 0.22.0 as the current image.

**Comment by else** [comment]
You're right. Thanks!
