### ISSUE TITLE
[stable/kubewatch] Impossible to use other provider than Slack

### ISSUE THREAD

**Issue by sebastien-prudhomme** [helm/charts#9596]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Which chart**:
stable/kubewatch 0.5.2

**What happened**:
tried to configure mattermost instead of slack, but as slack provider is not commented out with # in values.yaml, it still tries to contact slack

**Anything else we need to know**:

stash configuration should be commented out with #  in values.yaml

**Comment by juan131** [comment]
Hi @sebastien-prudhomme 

Do you mean "slack" when do you refer to "stash"?

**Comment by sebastien-prudhomme** [comment]
@juan131 sure, it's "slack". Will correct it.

**Comment by juan131** [comment]
Hi @sebastien-prudhomme 

I just created the PR above to address this issue.

**Comment by sebastien-prudhomme** [comment]
@juan131 thanks
