### ISSUE TITLE
initdbScripts is set but doesn't run

### ISSUE THREAD

**Issue by liyaka** [helm/charts#9619]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:40:58Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

helm version
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```
**Which chart**:

stable/postgresql

**What happened**:
I have set in my values.yaml:
```
initdbScripts:
  db-init.sql: |
    CREATE DATABASE xxx;
    CREATE DATABASE yyy;
    CREATE USER csr WITH PASSWORD 'aaa';
    CREATE USER xxx WITH PASSWORD 'xxx';
    GRANT ALL PRIVILEGES ON DATABASE xxx TO rrr;
    GRANT ALL PRIVILEGES ON DATABASE yyy TO rrr;
    GRANT ALL PRIVILEGES ON DATABASE xxx TO xxx;
    ALTER ROLE xxx SUPERUSER CREATEDB;
    ALTER ROLE rrr SUPERUSER CREATEDB;
```

I install my chart:
`helm install --name postgres -f helm/tools/postgres/values.yaml stable/postgresql`

**What you expected to happen**:
The script will run when i install my chart for the first time

**How to reproduce it** (as minimally and precisely as possible):
add the same configuration as I did

**Anything else we need to know**:
I can see the script I added in /docker-entrypoint-initdb.d/ in running container, the db is up and running but databases and other stuff from my init script are not created.

**Comment by natarajmb** [comment]
@liyaka 
Thanks for the report and it helped me solve my issue. Hope I could give my 2p knowledge here on the issue as I faced several. If you look at the logs while the pods are being created you would see the errors reported for any of the scripts (hint: kubectl logs <pod_id> -f). What I have noted is that you can't create the SUPERUSER role once a normal DB user is created (as normal user wont have rights to create user as superuser). So make sure to send the empty 'postgresqlUsername:' that would allow all execution to happen under the user 'postgres' and that should allow your scripts to execute as intended.

**Comment by liyaka** [comment]
@natarajmb 
In my case postgresqlUsername is not set, but still, nothing is running. I can see my script in ConfigMap, nothing appears in the log of the container.
I also tried to add a file under files/docker-entrypoint-initdb.d instead- same picture - appears in ConfigMap correctly but does not run, no errors in the log.
Suggestions?

**Comment by natarajmb** [comment]
@liyaka 
Adding files under files/docker-entypoint-initdb.d didn't work for me and your suggested approach in the bug report helped. If you don't set the postgresqlUsername to an empty string explicitly then the DB is created by the whatever the username and password you are passing in the chart. Hence to avoid that I had to set the postgresqlUsername explicitly so everything runs under the postgres user. 

If it helps this is what I have in my chart. 

  postgresqlUsername:
  initdbScripts:
    init.sql: |
      CREATE ROLE xxx WITH LOGIN PASSWORD 'xxx';
      CREATE SCHEMA ccc AUTHORIZATION xxx;
      GRANT ALL PRIVILEGES ON DATABASE xxx TO xxx;
      CREATE EXTENSION IF NOT EXISTS "pgcrypto" with SCHEMA ccc;

Also, check if you can see your SQL file under docker-entrypoint-initdb.d in the root of your PostgreSQL container.

**Comment by juan131** [comment]
Hi @natarajaya @liyaka 

I just want to mentioned that we recently fixed a similar feature (including the db ini files on gzip format). See the PR below:

- https://github.com/helm/charts/pull/10124

Regarding the issue you're facing @liyaka, could you share the output obtained when running the command below?

```
$ kubectl logs my-release-postgresql-0
$ kubectl get cm my-release-postgresql-init-scripts -o yaml
```

> Please note that you need to substitute `my-release` with the name you chose when releasing the PostgreSQL chart (I think it's `postgres` in your case).

**Comment by liyaka** [comment]
@natarajaya my configuration is just like this and as I said I could see my script in configMap and under  /docker-entrypoint-initdb.d
@juan131 My solution was to add a script that is called from docker-entrypoint and runs init_db.sql ( I use my image that is base on bitnami image), I would say it's a workaround and not a real solution, but it's ok for now.
When i'll be ready to upgrade to the latest postgres version, will check the original option again.

**Comment by juan131** [comment]
Great @liyaka !!

Do no hot hesitate to let us know if you need help when checking the original option again.
