### ISSUE TITLE
[minio] StatefulSet for minio standalone

### ISSUE THREAD

**Issue by victornoel** [helm/charts#9620]
In line with this issue #1863, I think it would be a good idea to make the minio chart in standalone mode also use a `StatefulSet` (only if there is persistence maybe?).

I create this issue to start the discussion for minio.

**Comment by victornoel** [comment]
An alternative would be to at least be able to specify the `"helm.sh/resource-policy": keep` annotation on the PVC when in standalone mode.

**Comment by desaintmartin** [comment]
Using the second option prevents you from reinstalling chart after deletion without manually modifying the values.yaml to use existing PVC.
Using statefulset actually allows you to be stateless (how ironic) from that point of view.
