### ISSUE TITLE
[prometheus-operator] - serviceMonitorSelector default values don't match rendered values

### ISSUE THREAD

**Issue by tim-beatson** [helm/charts#9621]
Is this a request for help?:

Is this a BUG REPORT or FEATURE REQUEST? (choose one):

Version of Helm and Kubernetes:
Helm: 2.10.0
Kubernetes: 1.10.8

Which chart:
stable/prometheus-operator

What happened:
serviceMonitorSelector in the default values file is {}, but the template then assigns values to serviceMonitorSelector if none are provided. This is missleading as it means Prometheus get's deployed with values that don't match the maintainer's default values or the defaults specified in the readme.

https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L69

What you expected to happen:
Rendered prometheus spec should have been:

serviceMonitorSelector: {}

rather than:

serviceMonitorNamespaceSelector:
  matchExpressions:
    release: prometheus-operator
        
How to reproduce it (as minimally and precisely as possible):

Provide values:

prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}

and the template will render it as:

serviceMonitorNamespaceSelector:
  matchExpressions:
    release: prometheus-operator

Anything else we need to know:
Nope, please either remove the else statement and let it render as per the default values, or update default values / readme to match the final result. My preference would be remove the else statement, I am working with one prometheus instance per cluster so want it to realise all serviceMonitor resources.

**Comment by dstockton** [comment]
:+1:

**Comment by paskal** [comment]
Could you please write your suggestion to https://github.com/helm/charts/pull/9190 which is about the same very problem?

**Comment by Mikewl** [comment]
@vsliouniaev
Maybe I am not seeing this right in the chart - it seems like you can only set them to `nil` not `{}`?
https://github.com/coreos/prometheus-operator/issues/1053#issuecomment-371733807 states that there's a difference between `nil` and `{}` for prometheus-operator.
Unless I am making a mistake where `serviceMonitorSelecorNilUsesHelmValues=false` in combination with `serviceMonitorSelector={}` currently doesn't create a valid prometheus-operator spec. It creates an array with `- ""` as it's only item.

I think to get all three behaviours, `{}` is going to have to be special cased in the helm chart. perhaps `ALL` or some other alternative. `nil` selector is functioning fine though!

**Comment by tim-beatson** [comment]
@vsliouniaev, I've spotted a slight typo in this: serviceMonitorSelecorNilUsesHelmValues. Missing t from selector - https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L740 https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L71
