### ISSUE TITLE
Halyard Pod not created while installing Spinnaker on Kubernetes(legacy) with default values using Helm chart

### ISSUE THREAD

**Issue by harshmehta93** [helm/charts#9627]
**Is this a request for help?**:
help
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm version:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Kubectl version:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/spinnaker

**What happened**:
Halyard Pod is not created while installing Spinnaker on Kubernetes(legacy) with default values using Helm chart

**What you expected to happen**:
Halyard Pod should be created while installing Spinnaker with default values using Helm chart.

**How to reproduce it** (as minimally and precisely as possible):
Just install Spinnaker using Helm chart with following command:
helm install --name spinnaker stable/spinnaker --timeout 600

**Anything else we need to know**:
Around 2 months ago, when I installed Spinnaker using Helm chart, Halyard Pod was successfully created, but now it is not created using latest git repo.

**Comment by dodizzle** [comment]
The problem is that there are several switches included in the /workdir/.hal/config file what are only compatible with the most recent versions of halyard. Even the latest stable version( 1.12.0) is not compatible.
The first of several is checkPermissionsOnStartup.
The work around is to use a 1.13.x version of halyard. That being said I still cannot get this chart to install successfully.
