### ISSUE TITLE
[stable/rabbitmq] GCE error when ingress is set to true

### ISSUE THREAD

**Issue by retpolanne** [helm/charts#9628]
**Is this a request for help?**: Yes

---

**BUG REPORT**

**Version of Helm and Kubernetes**:
Helm 2.8.0
Kubernetes 1.9.7

**Which chart**:
stable/rabbitmq

**What happened**:
When `ingress` is set to true on this chart, Helm creates an ingress and sets the rabbit service to ClusterIP. That led to errors like this:

```
Warning  GCE      5m (x17 over 8m)  loadbalancer-controller   googleapi: Error 400: Invalid value for field 'namedPorts[9].port': '0'. Must be greater than or equal to 1, invalid
```

**What you expected to happen**:
According to https://github.com/kubernetes/ingress-nginx/issues/1417#issuecomment-375838618, The service should be of type `NodePort` and it was created as `ClusterIP`

**How to reproduce it** (as minimally and precisely as possible):
Enable the ingress on the helm chart

```
ingress:
  ## Set to true to enable ingress record generation
  enabled: true
```

**Anything else we need to know**:
I'm not sure if you can reproduce the error on AWS.

**Comment by jpdasma** [comment]
I checked the chart. I think you should also set the following in values.yaml
```
serviceType: NodePort
```

**Comment by vinicyusmacedo** [comment]
@jpdasma sorry, I didn't see it. It should work now. Thanks!

**Comment by vinicyusmacedo** [comment]
@jpdasma actually, even with the `serviceType` set to `NodePort` it still creates it as `ClusterIP`

This is what I set
```
## Kubernetes service type
service:
- type: NodePort
  ## Node port
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  nodePort: 5672
```

This is what was created on Kubernetes.
`rabbit-mq-rabbitmq   ClusterIP   10.170.5.181   <none>        4369/TCP,5672/TCP,25672/TCP,15672/TCP   1m`
