### ISSUE TITLE
How to add alert rule to prometheus ?

### ISSUE THREAD

**Issue by ivan-meridianbanc-com** [helm/charts#966]
Could you give me simple example how to add alert rule to chart stable/prometheus ?

I install it with default values.
I added graph.

I cannot figure out how to add the rules.

**Comment by ohaiwalt** [comment]
Here: https://github.com/kubernetes/charts/blob/master/stable/prometheus/values.yaml#L406

This is looking for a file input similar to the `prometheus.yml` entry a few lines below.

For example:

```
serverFiles:
  alerts: |-
    ALERT K8SNodeDown
      IF up{job="kubelets"} == 0
      FOR 1h
      LABELS {
        service = "k8s",
        severity = "warning"
      }
      ANNOTATIONS {
        prefix = "[{{ .Labels.cluster }}]",
        summary = "Kubelet cannot be scraped",
        description = "Prometheus could not scrape a {{ .Labels.job }} for more than one hour",
      }
```

**Comment by wangybelle** [comment]
Hello, ohaiwait

 rules: |-
    ALERT K8SNodeDown
      IF up{job="kubelets"} == 0
      FOR 1h
      LABELS {
        service = "k8s",
        severity = "warning"
      }
      ANNOTATIONS {
        prefix = "[{{ .Labels.cluster }}]",
        summary = "Kubelet cannot be scraped",
        description = "Prometheus could not scrape a {{ .Labels.job }} for more than one hour",
      }

 **I installed prometheus 2.0.  In vlaues.yaml file, rules are configured as the above.
But I got following error. Can you help me? Thanks a lot!**

level=info ts=2018-01-25T09:21:45.950360872Z caller=kubernetes.go:100 component="target manager" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-01-25T09:21:45.9518776Z caller=kubernetes.go:100 component="target manager" discovery=k8s msg="Using pod service account via in-cluster config"
level=error ts=2018-01-25T09:21:45.953629284Z caller=manager.go:485 component="rule manager" msg="loading groups failed" err="yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `ALERT K...` into rulefmt.RuleGroups"
level=error ts=2018-01-25T09:21:45.95372839Z caller=main.go:413 msg="Failed to apply configuration" err="error loading rules, previous rule set restored"
level=info ts=2018-01-25T09:21:45.954347917Z caller=kubernetes.go:100 component=notifier discovery=k8s msg="Using pod service account via in-cluster config"
level=error ts=2018-01-25T09:21:45.95539898Z caller=main.go:356 msg="Error loading config" err="one or more errors occurred while applying the new configuration (--config.file=/etc/config/prometheus.yml)"

**Comment by sagikazarmark** [comment]
You need to use YAML format: https://prometheus.io/blog/2017/06/21/prometheus-20-alpha3-new-rule-format/#recording-rules-changes

**Comment by axk7812** [comment]
@wgiddens From the example rule, it shows the rules must be placed in `values.yaml`. If I'd like to separate out my rules into a `rules.yml` file how can I supply this file when installing the chart?

**Comment by gbuirel** [comment]
Hello,

I'd also like the ability to load rules from a rules.yml, maybe a configmap. I thought that job was done by the configmap-reload sidecar, but I can't seem to make whatever rules I add in it go to the main container ?
