### ISSUE TITLE
stable/grafana persistence.accessModes has a invalid default

### ISSUE THREAD

**Issue by ntbrittain** [helm/charts#9660]
**Is this a request for help?**:
I was able to work around it by setting a valid value

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Helm: 2.11.0
Kubernetes: 1.10.7

**Which chart**:
stable/grafana

**What happened**:
I enabled persistence, set storageClassName and size, and got the following error

`Error: UPGRADE FAILED: failed to create resource: PersistentVolumeClaim "prometheus-operator-grafana" is invalid: spec.accessModes: Required value: at least 1 access mode is required`

**What you expected to happen**:
I expected valid defaults or indication that this parameter is required when enabled

**How to reproduce it** (as minimally and precisely as possible):
Configure persistence with default persistence.accessModes value

**Anything else we need to know**:

**Comment by Dean-Coakley** [comment]
@ntbrittain https://github.com/helm/charts/blob/master/stable/grafana/values.yaml#L109 looks perfectly valid to me.

Would you suggest that this default should be uncommented by default?

**Comment by ntbrittain** [comment]
@Dean-Coakley I suggest either uncommenting the default, or updating the documentation to indicate that it is required: https://github.com/helm/charts/blob/master/stable/grafana/README.md

As it is, the documentation indicates that it has a default of `[]`, which I find misleading. I expect that if I leave out values which have defaults, that those defaults are valid.

**Comment by Dean-Coakley** [comment]
@ntbrittain I've opened a PR uncommenting the default. Feedback welcomed.

**Comment by maorfr** [comment]
@ntbrittain, can this issue be closed?
https://github.com/helm/charts/blob/master/stable/grafana/values.yaml#L114

**Comment by ntbrittain** [comment]
Yes, thank you!
