### ISSUE TITLE
[stable/postgresql] unable to initialize pod with docker-entrypoint-initdb/*.sql.gz

### ISSUE THREAD

**Issue by flah00** [helm/charts#9661]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

**Version of Helm and Kubernetes**:
helm: 2.9.1
k8s: 1.9.3

**Which chart**:
stable/postgresql

**What happened**:
I am trying to seed my db with data and provide a custom postgresql.conf. I was able to include my postgresql.conf file, by dropping it into files/. But my files/docker-entrypoint-initdb.d/db.sql.gz is not available on my pod. The directory is empty. 

**What you expected to happen**:
I expect the file to available on the pod, in /docker-entrypoing-initdb.d/

**How to reproduce it** (as minimally and precisely as possible):
1. `echo 'CREATE TABLE foo (i int);' | gzip -c > files/docker-entrypoint-initdb.d/db.sql.gz`
1. `helm install .`
1. `kubectl exec -ti postgresql-0 /bin/bash`
1. `ls -l /docker-entrypoint-initdb.d/`
    * should be empty

**Anything else we need to know**:
I already tried putting the file in `initdbScripts`, helm puked. My sql file uncompressed is about 4mb, which exceeds helm's limit. To successfully get it into the pod, I will need to compress it...

**Comment by flah00** [comment]
@prydonius @juan131 
Dunno how issues are bubbled up, thought I'd give you a ping.

**Comment by juan131** [comment]
Hi @flah00 

I was able to reproduce the issue on Minikube. I just followed the steps below (from this repo):

```
$ cd stable/postgresql
$ echo 'CREATE TABLE foo (i int);' | gzip -c > files/docker-entrypoint-initdb.d/db.sql.gz
$ helm install . --name postgres
$ kubectl exec -ti postgres-postgresql-0 -- ls -l /docker-entrypoint-initdb.d/
total 0
lrwxrwxrwx 1 root root 16 Dec 19 08:27 db.sql.gz -> ..data/db.sql.gz
lrwxrwxrwx 1 root root 16 Dec 19 08:27 README.md -> ..data/README.md
$ kubectl logs postgres-postgresql-0
...
INFO  ==> Loading user files from /docker-entrypoint-initdb.d
Executing /docker-entrypoint-initdb.d/db.sql.gz

gzip: /docker-entrypoint-initdb.d/db.sql.gz: not in gzip format
```

The problem is we're passing the `.gz` file as *data* instead of *binaryData*. I just created a PR to fix it.
