### ISSUE TITLE
[stable/phpmyadmin] Support for SSL

### ISSUE THREAD

**Issue by rnkhouse** [helm/charts#9662]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

  - In phpmyadmin chart, there should be SSL support.

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
phpmyadmin

**What happened**:
There is no way to provide SSL in connection.

**What you expected to happen**:
There should be option to connect database with ssl.

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. By being able to have SSL, you mean to connect to a database with SSL enabled, or to access phpmydamin with SSL?

**Comment by rnkhouse** [comment]
To connect the database with SSL.

**Comment by rnkhouse** [comment]
@juan131 
It looks like bitnami image now supports SSL.
Please take a look at this issue: https://github.com/bitnami/bitnami-docker-phpmyadmin/issues/21

**Comment by rnkhouse** [comment]
@juan131 @javsalgar 
Please confirm if it's done! Thanks.

**Comment by juan131** [comment]
Hi @rnkhouse

I'm sorry but we lost the track of this issue. 

As you mentioned the image supports SSL now by setting the `DATABASE_SSL_XXX` environment variables (more info in the link below).

- https://github.com/bitnami/bitnami-docker-phpmyadmin#environment-variables

So now we need to update the Helm chart to support it. I'll try to take a look into this tomorrow and come back to you with more information.

**Comment by juan131** [comment]
Hi @rnkhouse 

I created a PR to add support for this feature.

**Comment by juan131** [comment]
Hi @rnkhouse 

The PR was merged. Please feel free to take a look to the latest version of the chart and provide feedback about it.

**Comment by rnkhouse** [comment]
@juan131 I tested helm chart with SSL. According to Azure MySQL we just require ca-ssl. Please check this guide: https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl

I provided ca certificate file in chart but it's throwing me below error:

>Error: render error in "phpmyadmin/templates/certs.yaml": template: phpmyadmin/templates/certs.yaml:14:7: executing "phpmyadmin/templates/certs.yaml" at <required "A valid .Values.db.ssl.clientKey entry required!" .Values.db.ssl.clientKey>: error calling required: A valid .Values.db.ssl.clientKey entry required!

**Comment by juan131** [comment]
Hi @rnkhouse 

Could you share how you're providing the "ca certificate" in the chart? It'd be great to take a look to the "values.yaml" or settings you're using. Thanks in advance

**Comment by rnkhouse** [comment]
@juan131 

    db:
      host: DB_HOST
      enableSsl: true
      ssl:
        caCertificate: |-
          -----BEGIN CERTIFICATE-----
          MIIDdzCCAl+gAwIBAgIEAgAAuTANBgkqhkiG9w0BAQUFADBaMQswCQYDVQQGEwJJ
          RTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJlclRydXN0MSIwIAYD
          VQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTAwMDUxMjE4NDYwMFoX
          DTI1MDUxMjIzNTkwMFowWjELMAkGA1UEBhMCSUUxEjAQBgNVBAoTCUJhbHRpbW9y
          ZTETMBEGA1UECxMKQ3liZXJUcnVzdDEiMCAGA1UEAxMZQmFsdGltb3JlIEN5YmVy
          VHJ1c3QgUm9vdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKMEuyKr
          mD1X6CZymrV51Cni4eiVgLGw41uOKymaZN+hXe2wCQVt2yguzmKiYv60iNoS6zjr
          IZ3AQSsBUnuId9Mcj8e6uYi1agnnc+gRQKfRzMpijS3ljwumUNKoUMMo6vWrJYeK
          mpYcqWe4PwzV9/lSEy/CG9VwcPCPwBLKBsua4dnKM3p31vjsufFoREJIE9LAwqSu
          XmD+tqYF/LTdB1kC1FkYmGP1pWPgkAx9XbIGevOF6uvUA65ehD5f/xXtabz5OTZy
          dc93Uk3zyZAsuT3lySNTPx8kmCFcB5kpvcY67Oduhjprl3RjM7fwer12v/ye
          jl0qhqdNkNwnGjkCAwEAAaNFMEMwHQYDVR0OBBYEFOWdWTCCR1jMrPoIVDaGezq1
          BEsdfIGA1UdEwEB/wQIMAYBAf8CAQMwDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3
          DQEBBQUAA4IBAQCFDF2O5G9RaEIFoN27TyclhAO992T9Ldcw46QQF+vaKSm2eT92
          9hkTI7gQCvlYpNRhcL0EYWoSihfVCr3FvDB81ukMJY2GQE/szKN+OMY3EU/t3Wgx
          jkzSswF07r51XgdIGn9w/xZchMB5hbgF/X++ZRGewdahSNzkE1akxehi/oCr0
          Epn3o0WC4zxe9Z2etciefC7IpJ5OCBRLbf1wbWsaY71k5h+3zvDyny67G7fyUIhz
          ksLi4xaNmjICq44Y3ekQEe5+NauQrz4wlHrQMz2nZQ/1/I6eYs9HRuioiosdtTLS
          R9I4LtD+gdwyah617jzV/OeBHRnDJELqYzmp
          -----END CERTIFICATE-----

**Comment by juan131** [comment]
Hi @rnkhouse 

I could reproduce the issue! 

The current logic assumes that `db.ssl.clientKey`, `db.ssl.clientCertificate` and `db.ssl.caCertificate` parameters must be set. However, as you mentioned, they're not mandatory on every scenario. Let me work on a PR to address this.
