### ISSUE TITLE
Cannot scale JanusGraph due to use of PVC within Deployment

### ISSUE THREAD

**Issue by idcrosby** [helm/charts#9663]
BUG REPORT

**Which chart**:
janusgraph

**What happened**:
When attempting to scale the deployment, a second instance fails due to the single PVC.

**What you expected to happen**:
To be able to scale janusgraph. 

**How to reproduce it** (as minimally and precisely as possible):
Increase the `replicaCount` in `values.yaml` and install the chart

**Anything else we need to know**:
The Helm chart should be using a StatefulSet instead of a Deployment to allow scaling with PVCs. See: https://github.com/helm/charts/issues/1863

**Comment by bobvanluijt** [comment]
Any updates on this issue?

**Comment by idcrosby** [comment]
https://github.com/helm/charts/pull/10770
