### ISSUE TITLE
etcd is unable to recover when quorum is lost

### ISSUE THREAD

**Issue by jskelcy** [helm/charts#9664]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm Client Version: v2.11.0
Helm Server Version: v2.11.0
Kubernetes Version: v1.10.3

**Which chart**:
etcd version 0.6.0

**What happened**:
When the etcd cluster loses quorum nodes cannot be brought back.

**What you expected to happen**:
The nodes which were unavailable should be able to join the cluster once they have become available.

**How to reproduce it** (as minimally and precisely as possible):

- Start the helm chart, I am going to use persistent volumes but that is not required, you could also just use `kill -9` from inside the container:
`helm install --name etcd-bug ./ --set persistentVolume.enabled=true,persistentVolume.stroage=256Mi`

- Next stop 2 nodes (if you are running with a `repilca` different than the defualt you will need to stop n/2+1 nodes):`kubectl delete pods/etcd-bug-etcd-1; kubectl delete pods/etcd-bug-etcd-2`

You can then watch the nodes try to come back up and you will see that they are unable.

**Anything else we need to know**:

I suspect the issue is [here](https://github.com/helm/charts/blob/master/incubator/etcd/templates/statefulset.yaml#L115) where we are using etcdctl to set update member placement, however when the cluster has less then quorum nodes available it `etcdctl member update` is unavailable. This is because this is command prompts a write to the DB which is not possible with less than quorum nodes. The logs from the nodes which are attemping to join include this error:
`client: etcd cluster is unavailable or misconfigured`

It is the case that when a node exists it should be removed from the cluster using [the command in the preStop script](https://github.com/helm/charts/blob/master/incubator/etcd/templates/statefulset.yaml#L78), however potentially due to a race condition this command does have the desired effect of removing the node from the cluster. If [ line 115](https://github.com/helm/charts/blob/master/incubator/etcd/templates/statefulset.yaml#L115) is commented out the nodes are able to come back without a problem. If it seems reasonable I can put up a PR to remove this line unless someone is familiar with the reasoning for this.

**Comment by raoofm** [comment]
@hexfusion @gyuho just wanted to get your opinion on this?

**Comment by hexfusion** [comment]
>@hexfusion @gyuho just wanted to get your opinion on this?

basic logic is this. https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#update-a-member

If quorum loss is temporarily (restarted node) underlying data-dir exists and ${HOSTNAME} and ${SET_NAME} are unchanged member update is not required and would fail if cluster were not quorate.

If ${HOSTNAME} or ${SET_NAME} changes and existing data-dir is available then member update would be required for member to rejoin quorate cluster. But would fail if not quorate.

> client: etcd cluster is unavailable or misconfigured

https://github.com/helm/charts/blob/44c1f6d7674edd83e038e7ebb0a83674c5b461bb/incubator/etcd/templates/statefulset.yaml#L109-L121

So it seems if member update fails (timeout) then etcd is started regardless. This I think would cover a non quorate timeout and restore from temp loss of quorum and also if ${HOSTNAME} or ${SET_NAME} changed and cluster were quorate with member update. So I don't think removing that would be good. 

Where this would fail is if you delete a Pod and new Pod has different ${HOSTNAME} or ${SET_NAME} and cluster is not quorate. You would then start etcd with the new values which would be fine for client but the PeerUrls of the cluster would now be incorrect.

I would need to see the etcd logs to understand what exactly is happening.

**Comment by hexfusion** [comment]
Another thing I notice in v3 `etcdctl member update` requires `--peer-urls` flag

so this should look like this
`ETCDCTL_ENDPOINT=$(eps) etcdctl member update ${member_id} --peer-urls http://${HOSTNAME}.${SET_NAME}:2380`

**Comment by hexfusion** [comment]
etcdctl must be using `ETCDCTL_API=2` so disregard above re `--peer-urls`

**Comment by micw** [comment]
This issue is not stale and still exists. E.g. if the whole cluster is restarted, etcd is not able to recover and remains in a non-working state where all members are waiting for the culter to start so that they can join.

**Comment by Andrewjeska** [comment]
This is still an issue for me, removing the member update line seems to work. If all your pods live in a statefulset then the line is not necessary anyways
