### ISSUE TITLE
problem starting server on glusterFS

### ISSUE THREAD

**Issue by miramar-labs** [helm/charts#9666]
**Which chart**:
stable/postgres

**What happened**:
nami    ERROR Unable to start com.bitnami.postgresql: Cannot find pid file '/opt/bitnami/postgresql/tmp/postgresql.pid'

**What you expected to happen**:
no error, server starts up

**How to reproduce it** (as minimally and precisely as possible):
set your default storage class to be glusterFS (or specify glusterFS on the helm command-line)

**Anything else we need to know**:

**Comment by tompizmor** [comment]
Do you mind running `helm repo update` and try to install the chart again?

I have seen some issues fixed recently related with persistence so maybe is already fixed in the latest version.
