### ISSUE TITLE
[stable/fluent-bit] Consider making input path configurable

### ISSUE THREAD

**Issue by nvoskuilen** [helm/charts#9670]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
latest

**Which chart**:
stable/fluent-bit

**What happened**:
Unable to adjust the input path to filter out unwanted logs

**What you expected to happen**:
An easy and efficient way to exclude unwanted logs.
So one could do something like "Path             /var/log/containers/\*prod*.log" which effectively logs only the deployments with 'prod' in the name.

**Comment by naseemkullah** [comment]
Hi @nvoskuilen ,

There is another way to achieve this, please let me know if it would work for you:
By setting the chart value `filter.enableExclude` to true (which might be a default in future versions of the chart) and adding the following annotation to all pods whose logs you would like to exclude:
`fluentbit.io/exclude: true`

**Comment by nvoskuilen** [comment]
Hello Naseem,

Thanks for your input, but I was aware of the method you mentioned.
It would do the trick, but it takes more work then just exclude logs at the input level.

Also by excluding logs this early in the pipeline (input) Elasticsearch won't be flooded with unwanted data.

For now I adjust the config map manually, but this adjustment is lost when upgrading the chart.
