### ISSUE TITLE
[stable/traefik] Metrics cannot be enabled without dashboard

### ISSUE THREAD

**Issue by ms-choudhary** [helm/charts#9672]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:17:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
```
helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Which chart**:
stable/traefik

**What happened**:
If we disable dashboard but enable metrics in the chart, endpoint is not created for `metrics` port. And thus prometheus is not able to scrape the metrics (I'm using prometheus-operator). 

**What you expected to happen**:
Endpoint should be created for `metrics` port, if metrics is enabled. 

**How to reproduce it** (as minimally and precisely as possible):
```
metrics:
  prometheus:
    enabled: true

dashboard:
  enabled: false
```

**Anything else we need to know**:
This happens because in services, we've enabled metrics port:
```
  {{- if .Values.metrics.prometheus.enabled }}
  - port: 8080
    name: metrics
    targetPort: dash
  {{- end }}
```
However, `dash` port in pod is only exposed if dashboard is enabled:
```
        {{- if .Values.dashboard.enabled }}
        - name: dash
          containerPort: 8080
          {{- if .Values.deployment.hostPort.dashboardEnabled }}
          hostPort: 8080
          {{- end }}
          protocol: TCP
        {{- end }}
```
Would be happy to raise MR to fix this.

**Comment by dtomcej** [comment]
Hello @ms-choudhary, with the merging of https://github.com/helm/charts/pull/9430, there have been some changes to these ports.

Can you please try with the latest version of the chart, and see if you are able to accomplish this?

Thanks!

**Comment by ms-choudhary** [comment]
yeah sure.

**Comment by MisterTimn** [comment]
Ive encountered the same issue. Port for prometheus metrics only enabled when dashboard is enabled as well.

#9430 adds possibility to close of the metrics port when only deploying dashboard, but other way around isnt supported as I see it.

**Comment by pgressa** [comment]
We hit the same issue and agree with @MisterTimn that this does not solve an issue that for exposing metrics for prometheus the dashboard must be enabled as well which means the dashboard is accessible on main LoadBalancer.

I suggest to reopen https://github.com/helm/charts/issues/4473

**Comment by dennisotugo** [comment]
+1

**Comment by oz117** [comment]
+1

**Comment by mazzy89** [comment]
I've created a PR for this and fully tested https://github.com/helm/charts/pull/14946
