### ISSUE TITLE
Breaking Change - Load Balancer IP

### ISSUE THREAD

**Issue by ericrini** [helm/charts#9695]
I believe this modification is a breaking change for users who were allowing the load balancer IP to be selected automatically. When I deploy with this change...

https://github.com/helm/charts/commit/454a8a7a31d1a4bfcbe4cafd98888d17853e79cb#diff-d03daca2fd454740f43b1a61652b7a56

With the values...

```
external:
  loadBalancerIP: []
```

I receive the error...

```
Error: UPGRADE FAILED: render error in "kafka/templates/service-brokers-external.yaml": template: kafka/templates/service-brokers-external.yaml:11:27: executing "kafka/templates/service-brokers-external.yaml" at <index $root.Values.e...>: error calling index: index out of range: 0
```

Is it still possible to allow an ip address to be selected by the underlying provisioner as it was in previous releases?

**Comment by cablespaghetti** [comment]
Hi. If you could try the changes in my PR #10434 and tell me if they work for you, that would be really helpful!
