### ISSUE TITLE
"error creating server gateway: tls: failed to find any PEM data in certificate input"

### ISSUE THREAD

**Issue by syst0m** [helm/charts#9698]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
`helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}`

`kubectl version -o yaml
clientVersion:
  buildDate: 2018-10-30T21:39:16Z
  compiler: gc
  gitCommit: 17c77c7898218073f14c8d573582e8d2313dc740
  gitTreeState: clean
  gitVersion: v1.12.2
  goVersion: go1.11.1
  major: "1"
  minor: "12"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-09-21T21:00:04Z
  compiler: gc
  gitCommit: 58c199a59046dbf0a13a387d3491a39213be53df
  gitTreeState: clean
  gitVersion: v1.10.3-eks
  goVersion: go1.9.3
  major: "1"
  minor: 10+
  platform: linux/amd64`

**Which chart**:
kiam

**What happened**:
Followed the install isntructions in the readme, end up with:
`$ kubectl --namespace=default get pods -l "app=kiam,release=morbid-iguana"
NAME                              READY   STATUS             RESTARTS   AGE
morbid-iguana-kiam-agent-m46ms    0/1     CrashLoopBackOff   4          2m
morbid-iguana-kiam-agent-wkztn    0/1     CrashLoopBackOff   4          2m
morbid-iguana-kiam-server-kx42n   0/1     CrashLoopBackOff   4          2m
morbid-iguana-kiam-server-r7rwm   0/1     CrashLoopBackOff   4          2m

$ kubectl logs morbid-iguana-kiam-agent-m46ms
{"level":"fatal","msg":"error creating server gateway: tls: failed to find any PEM data in certificate input","time":"2018-12-03T16:46:55Z"}`

**What you expected to happen**:
kiam is deployed succesfully

**How to reproduce it** (as minimally and precisely as possible):
Create and install TLS certificates and private keys.
Do helm install of kiam.

**Anything else we need to know**:

Also, where/how am I supposed to do this:
>Define values agent.tlsFiles.ca, agent.tlsFiles.cert, agent.tlsFiles.key, server.tlsFiles.ca, server.tlsFiles.cert and agent.tlsFiles.key to be the base64-encoded contents (.e.g. using the base64 command) of the generated PEM files.

**Comment by syst0m** [comment]
Managed to resolve the issue.
Now I get the following in the pod logs:

`$kubectl logs pb-kiam-agent-ncpvm
container_linux.go:262: starting container process caused "exec: \"/agent\": stat /agent: no such file or directory"
$kubectl logs pb-kiam-server-j5hz9
container_linux.go:262: starting container process caused "exec: \"/server\": stat /server: no such file or directory"`

**Comment by syst0m** [comment]
And for the agent pods:
`container_linux.go:262: starting container process caused "exec: \"/agent\": stat /agent: no such file or directory"`

**Comment by bluebenno** [comment]
For sure it is nice to know, I'm not the only one who got the same errors: i.e.  `starting container process caused "exec: \"/agent\": stat /agent: no such file or directory"`.

working with a local older copy of the chart, but the same (my)values file - it does work. Which is odd. I'll update in 24hours.

**Comment by bluebenno** [comment]
this fails:
$  helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "ffxblue" chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈

kiam]$ helm search kiam
NAME       	CHART VERSION	APP VERSION	DESCRIPTION
stable/kiam	2.0.1-rc3    	3.0-rc1    	Integrate AWS IAM with Kubernetes

$ helm install stable/kiam --namespace kube-system --name kiam-v3 -f /Users/bluebenno/workspace/kiam/infrastructure/helm/values-common.yaml

$ helm ls | grep kiam
kiam-v3    	1       	Sat Jan  5 10:36:31 2019	DEPLOYED	kiam-1.2.2           	kube-system

*kiam-1.2.2* (!!)


this works:

$ cd /var/tmp
$ git clone git@github.com:helm/charts.git
$ helm install /var/tmp/charts/stable/kiam --namespace kube-system --name kiam-v3 -f /Users/bluebenno/workspace/kiam/infrastructure/helm/values-common.yaml

$ helm ls | grep kiam
kiam-v3    	1       	Sat Jan  5 10:28:13 2019	DEPLOYED	kiam-2.0.1-rc3       	kube-system


`$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
tmp]$`

Good news: it isn't a chart problem. Bad news is that I don't know what is causing this!

**Comment by idavidmcdonald** [comment]
> Managed to resolve the issue.
> Now I get the following in the pod logs for the server:
> 
> `$kubectl logs pb-kiam-agent-ncpvm container_linux.go:262: starting container process caused "exec: \"/agent\": stat /agent: no such file or directory" $kubectl logs pb-kiam-server-j5hz9 container_linux.go:262: starting container process caused "exec: \"/server\": stat /server: no such file or directory"`

Do you remember how you got around the original problem @syst0m? We are seeing the same issue with `error creating server gateway: tls: failed to find any PEM data in certificate input`

**Comment by mihirchakradeo** [comment]
@idavidmcdonald did you figure out a workaround?

**Comment by idavidmcdonald** [comment]
@mihirchakradeo so if I remember correctly it was not an interesting solution. We were pretty new to helm charts and had added a top level `kiam` key to our values (we had seen other charts do this) when we shouldn't have. Removing it fixed our problem.

**Comment by mihirchakradeo** [comment]
@idavidmcdonald Oh, I see. Thank you for your response.

**Comment by pnalamati-rms** [comment]
Anyone figure out the error $kubectl logs pb-kiam-agent-ncpvm container_linux.go:262: starting container process caused "exec: \"/agent\": stat /agent: no such file or directory" $kubectl logs pb-kiam-server-j5hz9 container_linux.go:262: starting container process caused "exec: \"/server\": stat /server: no such file or directory"
