### ISSUE TITLE
[stable/postgresql] postgresql.conf conversion fails to quote values

### ISSUE THREAD

**Issue by flah00** [helm/charts#9699]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
k8s 1.9.3
helm 2.9.1

**Which chart**:
postgresql

**What happened**:
I converted my config file from postgres to yaml. When the pod initialized, it failed to start, because option values are not quoted.

**What you expected to happen**:
I would expect the configuration file to be parse by postgres and the server to start. 

**How to reproduce it** (as minimally and precisely as possible):
```
cat <<EOT > /tmp/yaml
persistent:
  enabled: false
postgresqlConfiguration:
  maxConnections: '100'
  unixSocketDirectories: '/run/postgresql,/tmp'
  sharedBuffers: '128MB'
  dynamicSharedMemoryType: 'posix'
  sharedPreloadLibraries: 'pg_stat_statements'
  logTimezone: 'UTC'
  datestyle: 'iso, mdy'
  timezone: 'UTC'
  defaultTextSearchConfig: 'pg_catalog.english'
EOT
```

* `helm install --name pg -f /tmp/yaml stable/postgresql`

The pod will fail, because of a syntax errors in the postgresql.conf

* `kubectl exec -ti pg-postgresql-0 /bin/bash`

```
I have no name!@pg-postgresql-0:/$ cat -n /opt/bitnami/postgresql/conf/postgresql.conf
    1 datestyle=iso, mdy
    2 default_text_search_config=pg_catalog.english
    3 dynamic_shared_memory_type=posix
    4 log_timezone=UTC
    5 max_connections=100
    6 shared_buffers=128MB
    7 shared_preload_libraries=pg_stat_statements
    8 timezone=UTC
    9 unix_socket_directories=/run/postgresql,/tmp
```
```
I have no name!@pg-postgresql-0:/$ postgres --config-file=/opt/bitnami/postgresql/conf/postgresql.conf
2018-12-03 17:17:30.582 GMT [67] LOG:  syntax error in file "/opt/bitnami/postgresql/conf/postgresql.conf" line 1, near token ","
2018-12-03 17:17:30.582 GMT [67] LOG:  syntax error in file "/opt/bitnami/postgresql/conf/postgresql.conf" line 2, near token "pg_catalog.english"
2018-12-03 17:17:30.582 GMT [67] LOG:  syntax error in file "/opt/bitnami/postgresql/conf/postgresql.conf" line 9, near token "/"
2018-12-03 17:17:30.582 GMT [67] FATAL:  configuration file "/opt/bitnami/postgresql/conf/postgresql.conf" contains errors
```

**Anything else we need to know**:
Converting an exiting config file from postgres to yaml is cumbersome. The quoting issue could be easily resolved if the `postgresqlConfiguration` was a string, rather than a YAML data structure.

**Comment by flah00** [comment]
@prydonius @juan131 
Dunno how issues are bubbled up, thought I'd give you a ping.

**Comment by KeZhang** [comment]
I encounter the same issue and the template miss the quota, I use the following config as workaround
`postgresqlConfiguration:
    "sharedBuffers": "'1GB'"
    "maxConnections": 1000
    "listenAddresses": "'*'"`

**Comment by juan131** [comment]
Hi @flah00 @KeZhang 

As you may find in the README.md below:
https://github.com/helm/charts/blob/master/stable/postgresql/files/README.md

You can put your **postgresql.conf** under the **files/** directory. That'll be much easier than trying to pass your configuration through the **values.yaml**.

**Comment by KeZhang** [comment]
But how can I add the files if I use the remote repo to deploy?

**Comment by juan131** [comment]
Hi @KeZhang 

You can clone the repo locally (or just clone the **stable/postgresql** directory).

Another alternative would be using the workaround you suggested to "scape" the single quotes as you mentioned.

**Comment by deepaksood619** [comment]
This will work for newer configurations
`postgresqlConfiguration: {"maxConnections": "300", "sharedBuffers": "500MB", "listenAddresses": "'*'"}`
