### ISSUE TITLE
jenkins: helm upgrade

### ISSUE THREAD

**Issue by agonzalez-tk** [helm/charts#970]
Does Jenkins chart can handle upgrades ? I been trying to add plugins after installation, and it seems like nothing is happening nothing is added to jenkins, I also trying to update admin passowrd from values and nothing happened, am I missing someting ?

I tried: helm upgrade -f values.yaml release stable/jenkins

**Comment by berndtj** [comment]
The values make it into the /var/jenkins_home/config.xml file, but aren't reflected (even after explicit reload).  This may be a jenkins limitation.

**Comment by ptagr** [comment]
+1 seeing the same issue

**Comment by lachie83** [comment]
Thanks for raising this. I will take a look over the next couple of days

**Comment by errm** [comment]
It looks like the changed plugins.txt is not copied over because of a `cp -n`, I have opened a pr to fix this

**Comment by cmars** [comment]
After overwriting the config, you'd also need to do "Manage Jenkins -> Reload Configuration from Disk", or the Groovy script equivalent.

Or, just delete the pod and let it respawn.
