### ISSUE TITLE
[stable/fluentd] [stable/fluentd-elasticsearch] configmaps should be number-prefixed to avoid order confusion

### ISSUE THREAD

**Issue by tdihp** [helm/charts#9708]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Which chart**: stable/fluentd and stable/fluentd-elasticsearch

**What happened**: added a match block in an extra file before output.conf, ends up ignored due to the filename was alphabetically after "output.conf"

**What you expected to happen**: default configmap should be explicitly ordered, e.g. by using numbered prefix.

**Comment by mattshin** [comment]
Bump - this would be nice to have

Not sure what the process to revive stale issues is in this repo but I will work a quick fix to this and submit a PR
