### ISSUE TITLE
Support custom labels for deployments in Jenkins chart

### ISSUE THREAD

**Issue by erihanse** [helm/charts#9714]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Which chart**:
jenkins

Can the chart support custom labels for deployments, like it already does for pods and services?

**Comment by maorfr** [comment]
Hey @erihanse,

Thanks for bringing this up. Can you describe the issue with more details please?

**Comment by maorfr** [comment]
Sounds reasonable ;)
Would you like to get involved and create a PR for this issue?

**Comment by erihanse** [comment]
Sure. I've read CONTRIBUTING.md. Anything else I need to know?
