### ISSUE TITLE
[stable/prometheus-operator] helm install  unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"

### ISSUE THREAD

**Issue by enflo** [helm/charts#9719]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes version: 1.9.7-gke.11
Helm version: 
 - Client version: 2.11.0
 - Server version 2.11.0

**Which chart**: [stable/prometheus-operator] 

**What happened**:
When executing the command: *helm install --name myrelease stable/prometheus-operator*  . the console paints the following error: 
*Error: validation failed: [unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1", unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1", unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"]*

**What you expected to happen**:
By executing the command: *helm install --name myrelease stable/prometheus-operator* . The installation of the chart is performed correctly

**How to reproduce it** (as minimally and precisely as possible):
execute command: *helm install --name myrelease  stable/prometheus-operator*

**Comment by paskal** [comment]
Sorry, but [Readme](https://github.com/helm/charts/tree/master/stable/prometheus-operator#prerequisites) say that minimal k8s version is 2.10 with Beta APIs enabled. It won't work on your version of k8s.

**Comment by losil** [comment]
> Sorry, but [Readme](https://github.com/helm/charts/tree/master/stable/prometheus-operator#prerequisites) say that minimal k8s version is 2.10 with Beta APIs enabled. It won't work on your version of k8s.

Little detail: k8s version `1.10` is the minimal required.

**Comment by enflo** [comment]
Solved

**Comment by enflo** [comment]
Hi @OriHoch i upgraded my clusters.
Thanks
