### ISSUE TITLE
[nginx-ingress] imagePullSecrets is not working

### ISSUE THREAD

**Issue by steffenboe** [helm/charts#9740]
**Is this a request for help?**:
Yes!

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Starting the nginx-ingress Helm-chart with following command:
 `helm install --name nginx-ingress stable/nginx-ingress --set imagePullSecrets=[regcred] [...]`
(other options hidden for clarity)
is not working:
`Error: release nginx-ingress failed: DaemonSet in version "v1beta1" cannot be handled as a DaemonSet: v1beta1.DaemonSet.Spec: v1beta1.DaemonSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.ImagePullSecrets: []v1.LocalObjectReference: decode slice: expect [ or n, but found {, error found in #10 byte of ...|Secrets":{"name":"[r|..., bigger context ...|terFirst","hostNetwork":false,"imagePullSecrets":{"name":"[regcred]"},"serviceAccountName":"nginx-in|...
`
I tried several different approaches with "{" and "[", or with  --set imagePullSecrets.name, all leading to the same result. Am I getting something wrong?

**Version of Helm and Kubernetes**:
HELM VERSION:
$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

KUBERNETES VERSION:
1.10.6-gke.11

**Which chart**:
stable/nginx-ingress

**What happened**:
While trying to pull the nginx-Image from a private Repository, the Helm Chart is not taking the Secret with the error above. So the Chart starts to deploy the nginx-ingress-controller, but has no auth-credentials, to pull from the private Registry. Other deployments on the cluster already using the same secret can pull images.

**What you expected to happen**:
The given Secret is used for authenticating to the private Registry.

**How to reproduce it** (as minimally and precisely as possible):
1. Create Secret with Credentials for private Registry:
`kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> `--docker-email=<your-email>`
2. Deploy nginx-ingress Helm Chart
`helm install --name nginx-ingress stable/nginx-ingress --set imagePullSecrets=[regcred] --set rbac.create=true --set controller.kind=DaemonSet --set controller.image.repository=<private-registry>/kubernetes-ingress-controller/nginx-ingress-controller`

**Comment by huanwu** [comment]
@steffenb91 I hit the same issue as you when try to use the ngnix from the private repository.  To make it work, did you make your own version of nginx-ingress deployment instead of using the stable version? It seems you need update controller-deployment.yaml and value.yaml. Thanks!

**Comment by BojanZelic** [comment]
The value isn't being passed in correctly. Use the following;

```
helm install --name nginx-ingress stable/nginx-ingress --set imagePullSecrets[0].name=regdev
```
