### ISSUE TITLE
Error while creating Parser.

### ISSUE THREAD

**Issue by roys8** [helm/charts#9744]
**Is this a request for help?**:

Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

<!--
If this is a BUG REPORT, please:
  
When I am trying to run the stable chart, I am getting the error as below.

Error: render error in "fluent-bit/templates/daemonset.yaml": template: fluent-bit/templates/daemonset.yaml:19:28: executing "fluent-bit/templates/daemonset.yaml" at <include (print $.Tem...>: error calling include: template: fluent-bit/templates/config.yaml:153:23: executing "fluent-bit/templates/config.yaml" at <.name>: can't evaluate field name in type interface {}

**Version of Helm and Kubernetes**:
Helm 
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Kubernetes
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1",

**Which chart**:
stable/fluent-bit

**What happened**:
When I am trying to run the stable chart, I am getting the error as below. I am expecting this error is due to Parser block.

Error: render error in "fluent-bit/templates/daemonset.yaml": template: fluent-bit/templates/daemonset.yaml:19:28: executing "fluent-bit/templates/daemonset.yaml" at <include (print $.Tem...>: error calling include: template: fluent-bit/templates/config.yaml:153:23: executing "fluent-bit/templates/config.yaml" at <.name>: can't evaluate field name in type interface {}

**What you expected to happen**:
I expect to run the parser well.

**How to reproduce it** (as minimally and precisely as possible):
I dont know.

**Anything else we need to know**:

**Comment by tompizmor** [comment]
@roys8 Could you be more specific regarding the issue? Are you talking about the `parse` chart or is something else?
