### ISSUE TITLE
[stable/mongodb-replicaset] chart does not include link to peer-finder source

### ISSUE THREAD

**Issue by Freyert** [helm/charts#9753]
**Is this a request for help?**: Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**: 3.8.0

**Which chart**: stable/mongodb-replicaset

**What happened**: I'm working outside the bounds of the original chart, but I would like to still use the peer-finder. In short, I'm trying to attach a hidden secondary to an existing cluster deployed with mongodb-replicaset. The hidden secondary exists in another namespace and peer-finder just hangs when I try to look up like so:

`./peer-finder -ns=mongodb -service=mongodb-replicaset -on-start=/init/on-start.sh`

or 

`./peer-finder -ns=mongodb -service=mongodb-replicaset.mongodb -on-start=/init/on-start.sh`

**What you expected to happen**:
It finds the members of the replicaset.

**How to reproduce it** (as minimally and precisely as possible): Use `peer-finder` to find a replicaset in another namespace.

**Anything else we need to know**: It would be very convenient if I could see what `peer-finder` was doing and propose a PR myself. I think you should include a link to the source code in your `Chart.yaml`. Thanks @foxish!

**Comment by steven-sheehy** [comment]
It's at https://github.com/kubernetes/contrib/tree/master/peer-finder

@unguiculus Also has [PR](https://github.com/helm/charts/pull/9707) open to update the peer-finder version since it's out of date. Maybe your issue was already fixed in a newer version.

**Comment by SachinMaharana** [comment]
@unguiculus i don't find unguiculus/mongodb-install:0.8(0.7 doesn't has domain flag for peer-finder) which has fix for passing domain flag in case there is different cluster domain url. Can you point me in the right direction regarding this?
