### ISSUE TITLE
[stable/kiam] Add support for final kiam v3.0 release

### ISSUE THREAD

**Issue by ewbankkit** [helm/charts#9790]
kiam v3.0 has been [released](https://github.com/uswitch/kiam/releases/tag/v3.0) 😄.
Add support to the Helm chart.
The following should probably be merged first:
* ~One of https://github.com/helm/charts/pull/9755 or https://github.com/helm/charts/pull/9526~ https://github.com/helm/charts/pull/10353
* https://github.com/helm/charts/pull/9528
* https://github.com/helm/charts/pull/9262
* One of https://github.com/helm/charts/pull/7762 or https://github.com/helm/charts/pull/8942

**Comment by pingles** [comment]
Awesome, thanks for steering everything through. Please @ me or @uswitch/cloud if anything comes up we can help with.
