### ISSUE TITLE
[incubator/cassandra] backup fails with `container cassandra is not valid for pod deployment-cassandra-0`

### ISSUE THREAD

**Issue by joerghall** [helm/charts#9819]
BUG REPORT

Install Cassandra with backup enabled. The scheduled backup will fail.

**Version of Helm and Kubernetes**:
EKS 1.10
helm:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

**Which chart**:
incubator/cassandra

**What happened**:

{"log":"2018/12/08 04:10:54 Backup started!\n","stream":"stderr","time":"2018-12-08T04:10:54.010401031Z"}
{"log":"2018/12/08 04:10:54 Getting clients\n","stream":"stderr","time":"2018-12-08T04:10:54.010427176Z"}
{"log":"2018/12/08 04:10:54 Getting pods\n","stream":"stderr","time":"2018-12-08T04:10:54.147838609Z"}
{"log":"2018/12/08 04:10:54 Backing up schema\n","stream":"stderr","time":"2018-12-08T04:10:54.167857893Z"}
{"log":"2018/12/08 04:10:54 error in Stream: container cassandra is not valid for pod deployment-cassandra-0\n","stream":"stderr","time":"2018-12-08T04:10:54.175912875Z"}

**What you expected to happen**:
Successful backup. 

**How to reproduce it** (as minimally and precisely as possible):
Install Cassandra with backup enabled. The scheduled backup will fail.

**Anything else we need to know**:

Changing the StatefuleSet container name to Cassandra fixes the issue.

**Comment by maorfr** [comment]
Hey @joerghall,

Thanks for bringing this up.
The default container name to use is `cassandra`, as you found out.

To use a different container name, you can specify the `--container` flag in CronJob's arguments:
https://github.com/helm/charts/blob/master/incubator/cassandra/templates/backup/cronjob.yaml#L33

So instead of:
```
            args:
            - backup
            - --namespace
            - {{ $release.Namespace }}
            - --selector
            - release={{ $release.Name }}
            - --keyspace
            - {{ $schedule.keyspace }}
            - --dst
            - {{ $backup.destination }}
```

You should do:
```
            args:
            - backup
            - --namespace
            - {{ $release.Namespace }}
            - --selector
            - release={{ $release.Name }}
            - --keyspace
            - {{ $schedule.keyspace }}
            - --dst
            - {{ $backup.destination }}
            - --container
            - myCassandraContainerName
```

More options can be found here:
https://github.com/nuvo/cain

Let me know if this works for you!

**Comment by maorfr** [comment]
And after this PR is merged, you can define it in `values.yaml` under `backup.extraArgs`
