### ISSUE TITLE
[stable/keycloak] cannot deploy with custom values.yaml

### ISSUE THREAD

**Issue by haris44** [helm/charts#9825]
**Version of Helm and Kubernetes**:
Kubernetes 1.11

**Which chart**:
stable/keycloak

**What happened**:
when I try to deploy keycloak with default values.yaml, the container never start

**How to reproduce it** (as minimally and precisely as possible):
copy values.yaml, and try to deploy with "helm install -f keycloak.yaml stable/keycloak"

**Comment by haris44** [comment]
i think it's because keycloak values.yaml pull 4.5.0 image ?

**Comment by unguiculus** [comment]
It's hard to diagnose what your issue is. Every chart release is tested here and validated with a Selenium test that verifies a login is possible.
