### ISSUE TITLE
[stable/postgresql] securityContext is not set to initContainer

### ISSUE THREAD

**Issue by obeyler** [helm/charts#9844]
**BUG REPORT 
**Version of Helm and Kubernetes**:
Kubernetes 1.12.3
helm 2.10.0

**Which chart**:
stable/postgresql

**What happened**:
Unable to run chart with a PodSecurityPolicy witch has RunAsNonRoot even with the securityContext set.
(by default RunAsUser: 1001)

create Pod postgresql-postgresql-0 in StatefulSet postgresql-postgresql failed error: pods "postgresql-postgresql-0" is forbidden: unable to validate against any pod security policy: [spec.initContainers[0].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden]
postgres is not able to launch

**What you expected to happen**:
postrgres server run

**How to reproduce it** (as minimally and precisely as possible):
set a PodSecurityPolicy with RunAsNonRoot
helm install stable/postgresql -n postgresql --debug --namespace postgresql

**Anything else we need to know**:
I add some new message as comment to give more information

@prydonius 
@tompizmor 
@sameersbn
@carrodher
@juan131
@desaintmartin

**Comment by desaintmartin** [comment]
I have this problem. the "nami" daemon will run postgres with 1001:1001 anyway.

**Comment by obeyler** [comment]
Have you an idea of how to do to to deploy it on a K8S with RunAsNonRoot pod security policy?

**Comment by juan131** [comment]
Hi @obeyler @desaintmartin 

The `initContainer` was added to avoid issues on some K8s distributions were **SecurityContext** wasn't respected. Therefore, we needed a way to ensure the volumes had the proper permissions.

What do you think about adding a parameter such as `initContainer.enabled` that can be se to true/false so you can decide whether to install the chart with it or not? cc/ @tompizmor

**Comment by tompizmor** [comment]
Agree. We should have enough flexibility to enable/disable both the securityContext and the initContainer.
