### ISSUE TITLE
[stable/postgresql] Setting persistence.enabled=false breaks the chart

### ISSUE THREAD

**Issue by npiganeau** [helm/charts#9847]
**Version of Helm and Kubernetes**:
Helm: v2.11.0
Kubernetes: v1.12.2

**Which chart**:
stable/postgresql

**What happened**:
$ helm install --set "persistence.enabled=false" --name pg-demo stable/postgresql

Error: YAML parse error on postgresql/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 88: mapping values are not allowed in this context

**What you expected to happen**:
The chart to install successfully

**How to reproduce it** (as minimally and precisely as possible):
$ helm install --set "persistence.enabled=false" --name pg-demo stable/postgresql

**Anything else we need to know**:
Happens since commit c8330f2dbcf1075f1ed1d112f66c922a4a926083 

Maybe because we now have a duplicate `updateStrategy` in the stafulset.yaml.

I'll try to make a PR for this.

**Comment by stephenmoloney** [comment]
I've noticed this error also.

**Comment by chris-malloy-mri** [comment]
Fixed in https://github.com/helm/charts/pull/9952
