### ISSUE TITLE
[stable/mongodb-replicaset] helm tests are not correct

### ISSUE THREAD

**Issue by Freyert** [helm/charts#9858]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Not relevant

**Which chart**: stable/monodb-replicaset

**What happened**: 
With `auth` turned on we saw the following error when running `helm test`:
```
kubectl logs db-projects-rs0-test --namespace mongodb
1..4
ok 1 Testing mongodb client is accessible
ok 2 Connect mongodb client to mongodb pods
ok 3 Write key to master
not ok 4 Read key from slaves
```

After running several of these tests manually we concluded that tests 2-4 should have failed and test 1 was not very useful.

The core reason these fail is that `MONGOARGS` does not include auth credentials. The reason we get false positives is that no command executes with `--quiet`.

Test 1 should be renamed to `testing mongodb client is executable` to be more clear.

[This test](https://github.com/helm/charts/blob/master/stable/mongodb-replicaset/tests/mongodb-up-test.sh#L50) checks for the word `ok` in the response which is included whether the action succeeds or fails.

[This test](https://github.com/helm/charts/blob/master/stable/mongodb-replicaset/tests/mongodb-up-test.sh#L59) fails because without `--quiet` the output includes the connection port number which is by default `27017`.

**What you expected to happen**:

First, tests 2-4 should fail when `auth` is turned on.
Secondly, tests 2-4 should `auth` when `auth` is turned on, and then pass.

**How to reproduce it** (as minimally and precisely as possible):
`helm test` on a cluster using `auth`.

**Anything else we need to know**:

**Comment by unguiculus** [comment]
Thanks for the detailed analysis. Would you mind providing a fix?

**Comment by Freyert** [comment]
Sure thing!

**Comment by steven-sheehy** [comment]
Test 4 also has a sleep that is brittle and should really be changed to an until loop like in on-start.sh
