### ISSUE TITLE
[incubator/fluentd-cloudwatch] Permission denied @ rb_sysopen

### ISSUE THREAD

**Issue by mrichman** [helm/charts#9875]
I'm new to fluentd. Just deployed to my EKS cluster using helm for the first time using these commands:

```
aws logs create-log-group --log-group-name kubernetes
helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
helm install --name fluentd incubator/fluentd-cloudwatch --set awsRegion=us-east-1,rbac.create=true
```

When I look at the pod logs, I see this:

```
2018-12-10 21:16:37 +0000 [error]: unexpected error error_class=Errno::EACCES error=#<Errno::EACCES: Permission denied @ rb_sysopen - /var/log/fluentd-containers.log.pos>
```

I attached the CloudWatch Logs policy to the worker node IAM role.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "logs",
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:DescribeLogGroups",
                "logs:DescribeLogStreams"
            ],
            "Resource": [
                "arn:aws:logs:*:*:*"
            ]
        }
    ]
}
```

**Comment by mrichman** [comment]
I used this configuration, and it has no issues: https://eksworkshop.com/logging/deploy.files/fluentd.yml

Just wondering what the differences are. Perhaps your is intended to work with kops and the other with EKS?

**Comment by mseank** [comment]
I think this response would help: #7833 

But, essentially, you'll need to specify the FLUENT_UID
Why, I don't know. I just know that it works.

1) Make a YAML file: 
`awsRegion: us-west-2
extraVars:
  - "{ name: FLUENT_UID, value: '0' }"
rbac:
  create: true`
2) Don't use the --set flag (apart from the IAM role - that may be able to go in the YAML file as well, beats me)
3) Use a line similar to this: 
helm install --name fluentd-cloudwatch incubator/fluentd-cloudwatch --set awsRole=arn:aws:iam::<instance ID>:role/kubernetes-logs --values <filepath to YAML file> --namespace kube-system
