### ISSUE TITLE
[stable/phpmyadmin] not working with traefik ingress controller

### ISSUE THREAD

**Issue by cwinkler** [helm/charts#9914]
**Is this a request for help?**: yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
- Helm:
  - Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
  - Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
- Kubernetes:
  - Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
  - Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
- stable/phpmyadmin

**What happened**:
I'm trying to install phpyadmin with traefik as ingress controller. It deploys without problems but when I try to open the ingress url phpmyadmin only shows a blank page. When opening dev-tools in chrome I saw that the <html> element has a `display: none` style. After removing this I see an error message that a missassignment between HTTP and HTTPS. When I try to log in it errors with `Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.`

**What you expected to happen**:
Actually see the phpmyadmin login when opening the ingress URL.

**How to reproduce it** (as minimally and precisely as possible):
- Install traefik as an ingress controller
- run `helm install --name phpmyadmin stable/phpmyadmin --set ingress.enabled=true,ingress.host=phpmyadmin.example.com`

**Anything else we need to know**:
My k8s cluster is running on bare metal. I don't think this is the problem since everything else is running smoothly. Just FYI

**Comment by tompizmor** [comment]
I think the problem is one of the annotations set by default in the values.yaml. 
If you comment/delete the first annotation it works fine:

```
annotations:
    #ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /
```

**Comment by fabre-thibaud** [comment]
I had a different issue (CSS/JS were not loading due to strict mime type checking) but @tompizmor 's solution worked for me.

By any chance would it be possible to include that fix in the repository ?

**Comment by kurt---** [comment]
could this be reopened? The error still exists and phpmyadmin-chart does not work out of the box with the annotations. I wonder if the chart would work with the ngingx-controller and without the annotations or are they required?.

**Comment by Ankitchandre** [comment]
I would also like to request re open this issue . I am facing the same problem  with traefik controller as explained by cwinkler.
