### ISSUE TITLE
[stable/jenkins] Pre-provision agents

### ISSUE THREAD

**Issue by marcelloromani** [helm/charts#9934]
**FEATURE REQUEST**

Problem I'm facing: when launcing a build after the master has been idle for some time, I need to wait for an agent to be provisioned before the build can start.

Proposed solution (my feature request): keep a pool of agent pre-provisioned (akin to what happens in typical non-k8s deployments) so that builds can start executing right away, and the wait for new agents to be provisioned is only incurred in high-load scenarios.

My idea would be to add a configuration value, e.g.: `Agent.MinPoolSize = 4` to have 4 agents read to run at any given time.

**Version of Helm and Kubernetes**:
Helm version: v2.11.0
Kubernetes version: 1.10 (EKS)

**Which chart**:
stable/jenkins

**What happened**:
When building a job, an agent has to be provisioned first, adding setup time to the build time.

**What you expected to happen**:
Build should start straight away.

**How to reproduce it** (as minimally and precisely as possible):
Write the simplest possible job (any job).
Launch a build.

**Workaround**
Set the number of executors on the master to e.g. 4 (the chart default is 0)

**Comment by maorfr** [comment]
Hey @marcelloromani,

I agree that this can be a useful feature.
If you know how to implement it - we would love to get a PR for this.

What do you think?

**Comment by marcelloromani** [comment]
Hi @maorfr, I have other priorities atm, but I'm happy to look into putting together a PR as soon as I have time.

**Comment by marcelloromani** [comment]
A workaround worth investigating is setting PodRetention to Always:
```
  # Controls how slave pods are retained after the Jenkins build completes
  # Possible values: Always, Never, OnFailure
  PodRetention: Never
```
