### ISSUE TITLE
[stable/keycloak] Upgrade with h2 deletes credentials

### ISSUE THREAD

**Issue by codemasterover9000** [helm/charts#9936]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT(?)

Keycloak is part of a development/test stack running in minikube which imports a realm.json complete with users. We use the standard h2 database. 

When upgrading with Helm I expected the Keycloak instance to remain unchanged/untouched. This does not happen as the Keycloak admin credentials secret get removed from the environment of the container. Consequently login is not possible after a restart.

According to the following line the secret is only injected on a fresh installation: https://github.com/helm/charts/blob/dfaee2c8e5cf41c6913baf5c50918d0dddce9889/stable/keycloak/templates/statefulset.yaml#L66

Not sure if this is actually a bug, but also not sure how to fix this. Any help is appreciated.

**Comment by unguiculus** [comment]
The problem is that H2 doesn't survive a restart. It is recreated. H2 is not meant to be used for any real world scenarios.

**Comment by codemasterover9000** [comment]
I dont have a problem with H2 being completely reinstantiated. The problem is with Keycloak upgrading without respecting the admin credentials resulting in a Keycloak instance that is unusable.

Using a persistent database this is correct behavior. Not with H2. 

So I think there needs to be an exception in case of H2 at the code pointer I provided in my original post.
