### ISSUE TITLE
[stable/mariadb] probe failed if you set rootUser password

### ISSUE THREAD

**Issue by obeyler** [helm/charts#9940]
**BUG REPORT** :

**Version of Helm and Kubernetes**:
helm 2.10
K8S : 1.12.3

**Which chart**:
stable/mariadb

**What happened**:
probe failed if you set rootUser password
`helm install stable/mariadb -n mariadb --debug --namespace mariadb --set rootUser.password=mypassword
`
![image](https://user-images.githubusercontent.com/23224162/49878511-09b7fd80-fe28-11e8-8130-c77d8683c8c0.png)

**What you expected to happen**:
mariadb run 

**How to reproduce it** (as minimally and precisely as possible):
`helm install stable/mariadb -n mariadb --debug --namespace mariadb --set rootUser.password=mypassword
`

**Anything else we need to know**:
this is not systematic error
I retry the same after do a helm delete --purge mariadb and no more error
I redo that after delete namespace I found the error again
I suspect that it due to a delay during the create

**Comment by obeyler** [comment]
I see that other people have the same not systematic behavior
see https://github.com/helm/charts/issues/9524

**Comment by obeyler** [comment]
@prydonius , @tompizmor, @sameersbn, @carrodher, @juan131
Have you got any idea what should I do to solve it ?

**Comment by juan131** [comment]
Hi @obeyler 

It's very likely the master node was restarted before configuring the password, leaving the persisted data in an inconsistent state.

Could you please install the chart enabling the "debug" mode so we can identify the point where the pod is restarted? You can do it running the command below:

```
$ helm install stable/mariadb -n mariadb --set rootUser.password=mypassword,image.debug=true
```

**Comment by freshteapot** [comment]
I can confirm, I struggled with this.

After removing the pvc, so it reinstalled fresh.

It worked.
