### ISSUE TITLE
[stable/rabbimtq] Ingress path variable used in global scope

### ISSUE THREAD

**Issue by rishisharmamt** [helm/charts#9959]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm: v2.12.0, Kubernetes: minikube v0.31.0

**Which chart**: stable/rabbitmq

**What happened**: In templates/ingress.yaml, the chart is using ".path" variable from global scope, therefore, it cannot be changed from values.yaml. Therefore, I am unable to define a custom ingress path for rabbitmq service.

**What you expected to happen**: ".Values.ingress.path" variable should be used instead of ".path" so that it could be specified from values.yaml. 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by rishisharmamt** [comment]
@vtuson

**Comment by juan131** [comment]
I just created a PR to address this issue.
