### ISSUE TITLE
[incubator/kafka] zookeeper dependency

### ISSUE THREAD

**Issue by fabriziofortino** [helm/charts#9963]
**Which chart**:
[incubator/kafka]

The current zookeeper dependency points to `incubator/zookeeper`. This chart is based on https://github.com/kubernetes/contrib/tree/master/statefulsets/zookeeper and the last image is on zookeeper 3.4.10 (released more than a year ago).

@cablespaghetti has opened a [PR](https://github.com/kubernetes/contrib/pull/2965) to update the image to the latest stable version that includes important fixes, like [this one](https://issues.apache.org/jira/browse/ZOOKEEPER-2184). Looking at this [PR comment](https://github.com/kubernetes/contrib/pull/2965#issuecomment-439505483) it seems that kubernetes/contrib is not maintained.

Since the kafka chart uses `confluentinc/cp-kafka` as image I was wondering if it would be better to create a separate chart (eg: `[incubator/zookeeper-cp]`) that uses `confluentinc/cp-zookeeper` image and have this as a dependency in the requirements.

@benjigoldberg what do you think?

**Comment by bluebenno** [comment]
I am working on a Kafka + Zookeeper project.  I have a similar question.   Perhaps an alternative is to modify the incubator/zookeeper chart to use the confluent docker image?

My specific feature requirement is jaas authentication and ACLs

**Comment by benjigoldberg** [comment]
@fabriziofortino @bluebenno I definitely agree that the ZK image should be bumped. Is there a reason why you would prefer the confluent zookeeper vs the standard zookeeper docker image?

**Comment by fabriziofortino** [comment]
@benjigoldberg I would personally prefer to have a standard zookeeper docker image (since the confluent one is released only when confluent releases a new version of the cp platform). Unfortunately, there is no official standard zk image. The one used in the chart is outdated and is part of a repo that does not seem to be supported anymore.

**Comment by benjigoldberg** [comment]
@fabriziofortino I think we could like adopt this one https://hub.docker.com/_/zookeeper/ though to be fair I have not investigated what changes, if any, would be necessary to run this in k8s.

**Comment by cablespaghetti** [comment]
Unfortunately my PR to update the image we're using does introduce so
unexplained instability which is highly annoying.

It would be good to move to the "official" one from docker hub or maybe
something based on it. I'll have a go at it when I find myself with some
time if nobody else does sooner.

**Comment by donbowman** [comment]
I too now have this issue.
Any comments on your progress?

**Comment by donbowman** [comment]
I have created PR https://github.com/helm/charts/pull/11343 that could use some 3rd-party testing, but moves this to the official Zookeeper

**Comment by fabriziofortino** [comment]
waiting for #11343 to be reviewed / approved

**Comment by donbowman** [comment]
still waiting for review.

**Comment by donbowman** [comment]
the review has been done on PR #11343 I'll make the changes

**Comment by donbowman** [comment]
will be closed by #11343

**Comment by MartinX3** [comment]
Must stay open until #11343 got closed.

**Comment by agolomoodysaada** [comment]
Still an issue

**Comment by KealanM** [comment]
#16290 bumped Kafka chart zookeeper dependency to 2.0.0 from @donbowman so this should be resolved.
