### ISSUE TITLE
[stable/grafana] missing quoation mark

### ISSUE THREAD

**Issue by joluc** [helm/charts#9970]
**Which chart**:
[stable/grafana]

**What happened**:
Missing quotation mark in Notes for Grafana. In the description how to get the URL for Grafana, there is no closing quotation mark for the attribute _app_. Currently it is just _"app=grafana_. 

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/grafana

**Anything else we need to know**:
Solution: https://github.com/jonathanschwarze/charts/commit/4d15e70ff8131aef15526f7edc369f0dcbc3075c

**Comment by Dean-Coakley** [comment]
Fixed in: https://github.com/helm/charts/pull/10034

**Comment by maorfr** [comment]
@jonathanschwarze, can this issue be closed?
