### ISSUE TITLE
livenessprobe named port setting is solved as http://:http/status.php

### ISSUE THREAD

**Issue by peidong-hu** [helm/charts#9988]
https://github.com/helm/charts/blob/de9118bb98690b6b454efb2da34c73d067a5664f/stable/owncloud/templates/deployment.yaml#L97

**Comment by peidong-hu** [comment]
The kube version I have is 1.11

**Comment by carrodher** [comment]
I just answered the other issue #9989 but the answer is the same, can you take a look at the other one?
