### ISSUE TITLE
[stable/jenkins] Job definitions is broken in version 0.25.0

### ISSUE THREAD

**Issue by jpigree** [helm/charts#9992]
**Is this a request for help?**:
no

**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**Version of Helm and Kubernetes**:
```
helm version                                                                                                                                                        
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.4-gke.8", GitCommit:"338778b8cb8a1ac2654d0076351cf8eae280a24d", GitTreeState:"clean", BuildDate:"2018-11-26T15:35:08Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/jenkins, version: 0.25.0

**What happened**:
"helm install" throws an error:
```
helm install --name jenkins-test stable/jenkins --version 0.25.0 --namespace test -f ./jenkins.helm
Error: release jenkins-test failed: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadMapCB: expect { or n, but found ", error found in #10 byte of ...|","data":"seed: |-\n|..., bigger context ...|{"apiVersion":"v1","data":"seed: |-\n  \u003c?xml version='1.1' encoding='UTF|...
```

When downgrading the chart used to the last version I saw working (0.19.1), It starts working again.

```
helm install --name jenkins-test stable/jenkins --version 0.19.1 --namespace test -f ./jenkins.helm                                                                        
NAME:   jenkins-test                                                                                                                                                                           
LAST DEPLOYED: Thu Dec 13 09:01:03 2018                                                                                                                                                        
NAMESPACE: test                                                                                                                                                                                
STATUS: DEPLOYED                                                                                                                                                                               

RESOURCES:
==> v1/ServiceAccount
NAME          AGE
jenkins-test  2s

==> v1/ClusterRoleBinding
jenkins-test-role-binding  2s

==> v1/Service
jenkins-test-agent  2s
jenkins-test        2s
[...]
```
 
**How to reproduce it** (as minimally and precisely as possible):

The values.yaml is here: https://gist.github.com/jpigree/39c00c6126475c3ca5344085d163ef63

However, this values.yaml is just the standard values.yaml with one Job definition:

```
  # Jenkins XML job configs to provision
  Jobs: |-
    seed: |-
      <?xml version='1.1' encoding='UTF-8'?>
```

**Investigation**:
The only significant difference I found between the two charts is this:

templates/jobs.yaml 0.19.1:
`{{ .Values.Master.Jobs | indent 2 }}`

templates/jobs.yaml 0.25.0:
`{{ toYaml .Values.Master.Jobs | indent 2 }} `

I think this is what causes the issue. Moreover with a bit of "helm install --dry-run --debug", I came to this diff:

![diff_0 25 0-0 19 1](https://user-images.githubusercontent.com/3977280/49962082-6e229d80-feb8-11e8-932e-3044e805033c.png)

To confirm all this, removing the "toYaml" and launch the chart make it work again.

**We should remove the 'toYaml' from 'templates/jobs.yaml' from the 0.25.0.**

**Comment by kozejonaz** [comment]
I had the same problem. Just remove `|-` from `Jobs` like this

```
  # Jenkins XML job configs to provision
  Jobs:
    seed: |-
      <?xml version='1.1' encoding='UTF-8'?>
```

So I guess the `values.yaml` should be updated?

**Comment by jpigree** [comment]
Oh right. it works and it looks like a cleaner fix. :)

Actually, I still don't understand the value of the added "toYaml" call in 0.25.0 and I can't find a documentation about this template function.   

Anyway, I can submit a PR to fix this but let's decide which solution first.

**Comment by jpigree** [comment]
@kozejonaz, I submitted a PR with your fix in it. I mentioned you in the commit.
=> https://github.com/helm/charts/pull/10184/commits/4ca84af2915b1ceb50b049f36b25d35422a81c08

**Comment by kozejonaz** [comment]
@jpigree Cool, thanks :)
