### ISSUE TITLE
[stable/kong ] ingress health checks for proxy are generated incorrectly

### ISSUE THREAD

**Issue by yousafsyed-bg** [helm/charts#9993]
**Version of Helm and Kubernetes**:
helm
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```
kuebrnetes
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.11", GitCommit:"fa90543563c9cfafca69128ce8cd9ecd5941940f", GitTreeState:"clean", BuildDate:"2018-11-08T20:22:21Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
[stable/kong]-0.6.6

**What happened**:
Kong proxy ingress is generating the wrong health checks with `/` as the endpoint since proxy does not have any health check endpoints and the deployment uses the admin proxy for `readinessProbe` and `livenessProbe`. k8s automatically creates the default route for health check. which causes all the nodes to be marked as unhealthy

**What you expected to happen**:
It should create a health check that is on the proxy port in the deployment and to do that we should have an endpoint defined in kong proxy for that.

**How to reproduce it** (as minimally and precisely as possible):
Simply enabling ingress-proxy in the installation of [stable/kong] causes this problem.

**Comment by hbagdi** [comment]
PR welcome to fix this! We'll try to fix soon as well from our side.

**Comment by hbagdi** [comment]
@yousafsyed-bg What Ingress controller are you using?

I'm struggling to understand the exact issue here. Could you share more details? Some configs and specific health-checks that are failing?

AFAIK, there is no `healthcheck` associated with an Ingress resource.

**Comment by yousafsyed-bg** [comment]
@hbagdi 
I am using GKE's default ingress controller, and yes there are no `healthchecks` associated with ingress resource because ingress uses default health checks which are used for that specific port from the deployment i.e `proxy` or `admin`.

In the case of `admin` port its correct because the `healthchecks` are defined in the deployment of kong for `admin` port. Since there are no `healthchecks` associated with `proxy` port ingress creates some default `healthcheck` route at `root` of the `proxy` port which causes it to mark all the nodes as unhealthy.

**Comment by hbagdi** [comment]
> ingress creates some default healthcheck route at root of the proxy port

The GKE ingress controller shouldn't assume that the root will respond with HTTP 200 OK. I recommend you open an issue on their Github.

Regarding proxy port not having any associated health-checks, yes, we have to address that. The plan is to introduce a TCP check for the proxy port.
