### ISSUE TITLE
[stable/logstash] Liveness and readiness probes fail for default set up

### ISSUE THREAD

**Issue by nomadjourney** [helm/charts#9996]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/logstash, version: 1.4.0

**What happened**:
Installing chart with default values causes pod to fail both liveness and readiness probes causing to pod to restart over and over.

**What you expected to happen**:
Liveness and readiness probes should succeed for the default set up.

**How to reproduce it** (as minimally and precisely as possible):
```
helm install --name my-logstash --set persistence.enabled=false stable/logstash
```

**Anything else we need to know**:
Here's the output of `kubectl describe pods` for the pod in question:

```
Name:               my-logstash-0
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               iris-edge/10.0.2.15
Start Time:         Thu, 13 Dec 2018 21:25:58 +0000
Labels:             app=logstash
                    controller-revision-hash=my-logstash-867598f55f
                    release=my-logstash
                    statefulset.kubernetes.io/pod-name=my-logstash-0
Annotations:        checksum/patterns: e6d00cdf00ee3266a0ae0de38eea9dd30e0357bc10402ca5af8a6997a0a7e772
                    checksum/pipeline: 2fea58913ab4e39c8ecb0d07251888fab4d5c27a42cdb7052197e87c2fceff4a
                    cni.projectcalico.org/podIP: 192.168.0.10/32
Status:             Running
IP:                 192.168.0.10
Controlled By:      StatefulSet/my-logstash
Containers:
  logstash:
    Container ID:   docker://3d09d6617a0eeb0bf3a43c44ce3341f7bef7d52d1430749e9e65fdef628a32ab
    Image:          docker.elastic.co/logstash/logstash-oss:6.5.0
    Image ID:       docker-pullable://docker.elastic.co/logstash/logstash-oss@sha256:36b9cfe0b8e7c1ef469bc91749e873b6f450ca8057fe4a2124c0cbbab6912807
    Ports:          9600/TCP, 5044/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Thu, 13 Dec 2018 21:25:59 +0000
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:monitor/ delay=20s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:monitor/ delay=20s timeout=1s period=10s #success=1 #failure=3
    Environment:
      HTTP_HOST:                0.0.0.0
      HTTP_PORT:                9600
      ELASTICSEARCH_HOST:       elasticsearch-client.default.svc.cluster.local
      ELASTICSEARCH_PORT:       9200
      CONFIG_RELOAD_AUTOMATIC:  true
      PATH_CONFIG:              /usr/share/logstash/pipeline
      PATH_DATA:                /usr/share/logstash/data
      QUEUE_CHECKPOINT_WRITES:  1
      QUEUE_DRAIN:              true
      QUEUE_MAX_BYTES:          1gb
      QUEUE_TYPE:               persisted
    Mounts:
      /usr/share/logstash/data from data (rw)
      /usr/share/logstash/patterns from patterns (rw)
      /usr/share/logstash/pipeline from pipeline (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fbhkx (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  patterns:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      my-logstash-patterns
    Optional:  false
  pipeline:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      my-logstash-pipeline
    Optional:  false
  data:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  default-token-fbhkx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fbhkx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age   From                Message
  ----     ------     ----  ----                -------
  Normal   Scheduled  33s   default-scheduler   Successfully assigned default/my-logstash-0 to iris-edge
  Normal   Pulled     32s   kubelet, iris-edge  Container image "docker.elastic.co/logstash/logstash-oss:6.5.0" already present on machine
  Normal   Created    32s   kubelet, iris-edge  Created container
  Normal   Started    32s   kubelet, iris-edge  Started container
  Warning  Unhealthy  5s    kubelet, iris-edge  Readiness probe failed: Get http://192.168.0.10:9600/: dial tcp 192.168.0.10:9600: connect: connection refused
  Warning  Unhealthy  3s    kubelet, iris-edge  Liveness probe failed: Get http://192.168.0.10:9600/: dial tcp 192.168.0.10:9600: connect: connection refused
```

**Comment by petertang2012** [comment]
I am also getting **Liveness probe failed** with logstash-1.4.1. Any idea why it happened and how to work around it?

**Comment by nomadjourney** [comment]
Nope, I haven't found a workaround for this issue yet.

**Comment by metsuke0** [comment]
I increased my liveness and readiness probe timeouts to 90 seconds, and it bypassed the issue for me.

**Comment by petertang2012** [comment]
Tried increasing timeouts to 90 seconds with the 6.5.4 upgrade, still getting Readiness probe failed.

**Comment by skbly7** [comment]
This is because the logstash chart is assuming exporter is running. If the exporter isn't running readiness & liveness probes will fail. Just do `--set exporter.logstash.enabled=true` to mitigate the problem, until chart is fixed.

**Comment by david-kw-yeung** [comment]
When I get log of the pod, it shows as follow.
<pre>[2019-01-16T03:39:11,451][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Path "/usr/share/logstash/data" must be a writable directory. It is not writable.>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/settings.rb:447:in `validate'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:229:in `validate_value'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:140:in `block in validate_all'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:139:in `validate_all'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:278:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:237:in `run'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:73:in `<main>'"]}
[2019-01-16T03:39:11,468][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit</pre>

**Comment by procyclinsur** [comment]
This is not over yet.. I just ran into this issue this week.. didn't see this ticket until after the fact, but came to the same conclusion that @petertang2012 

I haven't been able to get the evidence to show, but I've seen late response from the liveness probe all the way till 110s which is thankfully still covered under the 90 second delay...  I think it would be beneficial to have a slightly higher default for this... seems to depend on the plugins loaded..?

**Comment by james-mchugh** [comment]
I am also seeing this error no matter how much I increase the delay or timeout periods for the probes. The interesting thing is, if I manually port-forward the service ports, I can access the probe URL  from my host machine without any issue. I am not sure where this inconsistent behavior is coming from.

**Comment by shahadarsh** [comment]
@james-mchugh We are having the same issue. Were you able to figure out what was happening?

**Comment by james-mchugh** [comment]
> @james-mchugh We are having the same issue. Were you able to figure out what was happening?

I believe so. I missed in the documentation that if you overwrite logstash.yml, you must set `http.host: 0.0.0.0`. I believe that resolved it for me.
