### ISSUE TITLE
[stable/mongodb] Documentation about stable/mongodb authentication

### ISSUE THREAD

**Issue by Philippe-Collignon** [helm/charts#9998]
Feature Request : 

It would be great to add some documentation about how to authenticate to stable/mongodb statefullset.

- The "one pod url"  `mongodb://user:password@mongodb:27017/dbname` does not work because we have to authenticate to the admin pod

- According to mongo documentation, we should use something like : 
`mongodb://user:password@mongodb-1,mongodb-2,mongodb-3:27017/dbname` 
but the chart only creates one service ?! 

I tried also to add `?authSource=admin&replicaSet=rs0` but authentication still fails..

So I am a bit lost ... 

Also can we configure the chart to not create headless service.
Thanks

**Comment by carrodher** [comment]
When you deploy the chart, this information should appear in the console:
https://github.com/helm/charts/blob/master/stable/mongodb/templates/NOTES.txt

This is a template file that should be rendered in a more readable way including your specific parameters, so although you see this content weird in the `NOTES.txt` file when the content is displayed in the console where you did `helm install` this information should appear in a clear way.

**Comment by juan131** [comment]
That's great @Philippe-Collignon 

Could we considered the issue solved?

**Comment by Philippe-Collignon** [comment]
Yes thanks .. this might be added to the doc for end users.
